### ISSUE TITLE
Japanese input-methode for on-screen-keyboard

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [xbmc/xbmc#14557]
Depending on that [forum post](https://forum.libreelec.tv/thread/13443-input-method-for-on-screen-keyboard-to-japanese) I open this Issue as a _Feature Request_.

I would like to input Japanese characters (Hiragana, Katakana, Kanji) with the on-screen-keyboard - because the Kodi is controlled via a FLIRC connected remote controll.

Kodi itself has no problems displaying japanese characters. This issue is only about input methode.

**Comment by MartijnKaijser** [comment]
Feature request need to be put on the forum
