### ISSUE TITLE
EGL_OPENGL_API is not supported in all EGL implemetations

### ISSUE THREAD

**Issue by boblun** [xbmc/xbmc#14560]
### Describe the bug
Here is a clear and concise description of what the problem is:

GLContextEGL.cpp:~161
if (!eglBindAPI(EGL_OPENGL_API)) returns EGL_BAD_PARAMETER resulting in failure of EGL on platforms not supporting the OPEN GL API

Kodi Build links libGL even when -DENABLE_OPENGL=OFF is specified in CMAKE

Kodi easilly mixes up GL Implementations (possibly from above) on EGL based platforms where there might be a MESA software libGL AND a Vendore supplied Hardware libGLES* and libEGL* even where 
-DENABLE_OPENGL=OFF is specified in CMAKE.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I
I expected that if I set KODI_GL_INTERFACE=EGL then Kodi would use EGL (GLES) instead of OpenGL.

## Actual Behavior

Regardless of the environment kodi attempts to use OpenGL Libraries which on my platform exist only in software MESA implementation. The contexts drawn from the H/W EGL don't work in the Mesa Lib.

## Possible Fix

GLContextEGL.cpp:~161 

if (!eglBindAPI(EGL_OPENGL_ES_API))

Note that Kodi binds libGL BEFORE libGLES even with -DENABLE_OPENGLES=ON -DENABLE_OPENGL=OFF arguments to cmake - which I think is probably wrong, this results in Kodi Calling mesa Opengl functions instead of the appropriate hardware GLES functions of the same name. It does this even when KODI_GL_INTERFACE=EGL and -DENABLE-OPENGL=OFF

Note that Kodi's execution path somehow lands me in RenderSystemGL rather than RenderSystemGLES if X11 is available. - Not yet investigated but probably due to -DENABLE-OPENGL=OFF failing.

Instead of Calling gl functions directly  use eglGetProcessAddress to load and validate the gl subset that kodi needs, adapt Kodi Properly to GLES semantics when KODI_GL_INTERFACE=EGL is set

### To Reproduce

1. Compile and Run Kodi on an Arm/Mali Platform with H/W rendering enabled.
2.
3.

### Debuglog

The debuglog can be found here:
Note: I have enhanced the debugging to show the cause of the EGL Failure (Created a Method GetEGLErrorString() to get the result code and translate it to a string)

if (!eglBindAPI(EGL_OPENGL_API))
    {
      CLog::Log(LOGERROR, "failed to bind egl API %s",this->GetEGLErrorString());
      XFree(vInfo);
      return false;
    }
10:35:34.813 T:548446380048  NOTICE: Using visual 0x21
10:35:34.813 T:548446380048   ERROR: failed to bind egl API Invalid argument
10:35:34.814 T:548446380048 WARNING: Visual 0x21 of the window is not suitable, 

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Ubuntu 18.04/ aarch64

 - Kodi version:
Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
same answer as https://github.com/xbmc/xbmc/issues/14559#issuecomment-428403516
