### ISSUE TITLE
Missing text when sorting from inside addon

### ISSUE THREAD

**Issue by bigretromike** [xbmc/xbmc#14573]
### Describe the bug
Here is a clear and concise description of what the problem is:
There is missing variables/text for year/rating in default skin when sorting content inside addon that have setContent(tvshows) and `isFolder=True`;
Currently this is omitted for addons, and show incorrect data: for rating showing year, and for year showing nothing.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Year/Rating should be visable to content that is created by addon.

## Actual Behavior
For Rating there is a Year, and for Year there is a date shown in place of proper data.

## Possible Fix
https://github.com/xbmc/xbmc/pull/14504 this was propose by me but @ronie suggested to fix it in core.

### To Reproduce
https://github.com/xbmc/xbmc/pull/14504#issuecomment-426200908
Here is a live demo

### Debuglog
The debuglog can be found here:
https://github.com/xbmc/xbmc/pull/14504

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 17.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Razzeee** [comment]
Rating seems to work fine for me with your addon
![image](https://user-images.githubusercontent.com/5943908/46754971-bb944b80-cc78-11e8-844e-86deab39d8cc.png)

But year has a date and date is empty/has nothing

**Comment by bigretromike** [comment]
those are files. not folder.
Files work fine, Folders are broken. 
Also @ronie confirm this as bug

**Comment by Razzeee** [comment]
But we're talking about the different sort by options and the data shown here in the section in the middle?
![image](https://user-images.githubusercontent.com/5943908/46761952-ad4f2b00-cc8a-11e8-8876-167166639688.png)

**Comment by ronie** [comment]
the problem is that ListItem.Label2 returns empty for folder items.

![label2](https://user-images.githubusercontent.com/687265/46771184-b8d63c80-ccf2-11e8-8885-7efd08a8c925.jpg)

**Comment by bigretromike** [comment]
Sorting works correct, it does sort by value but omit showing it:
**by TITLE** (both are correct)
![ep_title](https://user-images.githubusercontent.com/6052025/46781644-e509b180-cd22-11e8-8861-b86d53c5e42f.png)
![tv_title](https://user-images.githubusercontent.com/6052025/46781646-e935cf00-cd22-11e8-9437-103b11371609.png)

**by YEAR** (for episode its blank, for folder its DATE not YEAR)
![ep_year](https://user-images.githubusercontent.com/6052025/46781688-28642000-cd23-11e8-9755-88f6c82b5399.png)
![tv_year](https://user-images.githubusercontent.com/6052025/46781677-1da98b00-cd23-11e8-9134-9725bf561136.png)

**by RATING** (for episodes is correct, for folder is MISSING)
![ep_ratings](https://user-images.githubusercontent.com/6052025/46781706-4a5da280-cd23-11e8-9ecf-4ca90edba142.png)
![tv_rating](https://user-images.githubusercontent.com/6052025/46781707-4c276600-cd23-11e8-86a5-fc1665b8b505.png)

**by DATE** (for both DATE is missing, but date is there - seen in YEAR sorting)
![ep_date](https://user-images.githubusercontent.com/6052025/46781717-58132800-cd23-11e8-881e-c2938bb8ef03.png)
![tv_date](https://user-images.githubusercontent.com/6052025/46781793-a9231c00-cd23-11e8-9e41-5adbff6205a9.png)

**Comment by bigretromike** [comment]
> 
> 
> the problem is that ListItem.Label2 returns empty for folder items.
> 
> ![label2](https://user-images.githubusercontent.com/687265/46771184-b8d63c80-ccf2-11e8-8885-7efd08a8c925.jpg)

It's a wider issue.
Its for both folders and non-folder (see the compare), but folder is the most broken right now.

**Comment by Razzeee** [comment]
Don't confuse `Date` and `Year`. Year is the year when the media was released. Date is the date you added it to your library.

**Comment by bigretromike** [comment]
Im not confusing it. If I recall those are same with my examples.
One is `year` and other is `date`. 
No matter what they represents, they are both populated - and not display correctly, as you see yourself.

**Comment by bigretromike** [comment]
@ronie any updates on this issue, maybe it will be fixed in Leia ?

**Comment by bigretromike** [comment]
I tested Leia, and the issue is still there.
Could someone response to this? @MartijnKaijser @DaVukovic @pkerling @phate89 
Sorry if I marked wrong people, but this issue is ongoing and still present, and probably dig below anyone eyes.

**Comment by bigretromike** [comment]
Ok, my PR https://github.com/xbmc/xbmc/pull/16433 have been merge, this issue was resolved with that PR.
18.4 and 19.0 shouldn't be affected anymore. 
Thanks guys for the time.
