### ISSUE TITLE
xbmc.Player python module broken in Leia Beta 3

### ISSUE THREAD

**Issue by nomadyow** [xbmc/xbmc#14574]
On Leia Beta 3 my python addon that uses xbmc.player stopped working (just upgraded from Krypton).

There are two calls that seem broken.  inside onPlayBackStarted I call .isPlayingVideo() and it never fires when video is playing.  

Here is a simplified addon that illustrates the problem (see XXX below):

`import xbmc
import xbmcaddon
import os

addon                  = xbmcaddon.Addon()
addon_id               = addon.getAddonInfo('id')
addon_folder           = xbmc.translatePath("special://profile/addon_data/"+addon_id)
log_file               = os.path.join(addon_folder, "brodietheatre.log")

def log(message):
    logger = open(log_file, 'a')
    logger.write(message + "\n")
    logger.close()

class XBMCPlayer( xbmc.Player ):

    def __init__( self, *args ):
        pass
        
    def onPlayBackStarted(self):
        if self.isPlayingVideo():
            log("Video Started")
            # XXX Never reaches here when video is playing

    def onPlayBackPaused( self ):
        if self.isPlayingVideo():
            log("Paused")
            # This works fine

    def onPlayBackResumed( self ):
        if self.isPlayingVideo():
            log("Resumed")
            # This works fine
            
    def onPlayBackStopped( self ):
        log("Stopped")
        # This works fine

    
# Start of script
      
player = XBMCPlayer()
monitor = xbmc.Monitor()

while not monitor.abortRequested():
    if monitor.waitForAbort(.04):
        break`

**Comment by nomadyow** [comment]
Here is the code for the plugin in pastebin:

https://pastebin.com/bHEjia2y

**Comment by enen92** [comment]
On Leia the workflow is a bit different:

- `onPlayBackStarted()` is triggered when the player is initialized, it does not mean a media is playing
- `onAVChange()` (new) is triggered when the player gets a stream either video, audio or subtitles
- `onAVStarted()` (new) is called when the player actually starts playing the stream

So, please use `self.isPlayingVideo()` in the `onAvStarted()` event rather than on `onPlayBackStarted()`

**Comment by MilhouseVH** [comment]
```
    if monitor.waitForAbort(.04):
```
Maybe this is just your example but using a timeout of .04 defeats the entire purpose of `monitor.waitForAbort` - just use an infinite timeout.

In Kodi 18 you now need to support the `onAVStarted()` event: https://codedocs.xyz/xbmc/xbmc/group__python___player_c_b.html#ga61cb60571b974e447dba57bdaa77aace, which is when `isPlayingVideo()` can be tested reliably - see this comment under `onPlayBackStarted()`:
```
Video or audio might not be available at this point.
```

**Comment by nomadyow** [comment]
Yes, that was just my example for monitor (I had other reasons in my addon to check periodically).

onAVStarted works fine - Closing.

**Comment by MartijnKaijser** [comment]
@enen92 Seems the python_v18 changelog tags were not added when this change was done.

**Comment by enen92** [comment]
Yeah I noticed it too, will PR. Just trying to figure out why `updateInfoTag ()` is with that massive font
