### ISSUE TITLE
With wrapped mariadb_version.h, FindMariaDBClient.cmake fails

### ISSUE THREAD

**Issue by candrews** [xbmc/xbmc#14592]
### Describe the bug
Here is a clear and concise description of what the problem is:

Cannot compile Kodi on Gentoo with MariaDB because `/usr/include/mariadb/mariadb_version.h` doesn't contain the string `MARIADB_CLIENT_VERSION_STR` (I suspect this impact other distros, but haven't found out for sure)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

`USE="mariadb" emerge =media-tv/kodi-9999`
FindMariaDBClient.cmake module does not find what it needs. The module searches for `MARIADB_CLIENT_VERSION_STR` in `/usr/include/mariadb/mariadb_version.h`, but that file is just a wrapper header to include `/usr/include/x86_64-pc-linux-gnu/mariadb/mariadb_version.h` where the constant is actually defined. As the cmake module does not "parse" the wrapped header file but reads it line by line and searches for the constant with a regexp, cmake fails in the end.
Here's what `/usr/include/mariadb/mariadb_version.h` looks like: https://pastebin.com/h81cta5x
This header file is wrapped as that's how multilib support is implemented.

## Actual Behavior

You should be able to compile Kodi on Gentoo :)

## Possible Fix

Is extracting the version from the header file really necessary? Is there a better way to get the version? Is getting the version necessary at all?

### To Reproduce

1.  Compile Kodi 18 (current master) on a Gentoo system with MariaDB support

### Debuglog

The debuglog can be found here:

Since this is a build issue, a debug log doesn't appear to be applicable.

### Screenshots 
Here are some links or screenshots to help explain the problem:

Since this is a build issue, a screenshot doesn't appear to be applicable.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo Linux ~amd64
 - Kodi version: 18 (master, currently c997272e9edd34c1efb879b5f5ee2936c7a3e528 )

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by asavah** [comment]
> Here's what /usr/include/mariadb/mariadb_version.h looks like: https://pastebin.com/h81cta5x 
 > "This file is auto-generated by multilib-build.eclass"

Debian, Ubuntu , Fedora and etc don't do such magic and MARIADB_CLIENT_VERSION_STR is right where it's supposed to be, if gentoo makes use of some "magic" homegrown wrappers isn't it THEIR responsibility to patch the packages in order to be aware of such "magic" solutions?

Just my 5c (c)

**Comment by candrews** [comment]
I can see that perspective, of course. But then again, I think my original questions are still valid:
> Is extracting the version from the header file really necessary? Is there a better way to get the version? Is getting the version necessary at all?

**Comment by pkerling** [comment]
I see two easy options:

* Drop checking the version - we don't actually need it for anything as far as I can see
* Use pkgconfig

@wsnipex maybe?

**Comment by wsnipex** [comment]
Please provide cmake output and CMakeCache.txt.
Failing to parse the version string should not prevent the find module to detect mariadbclient, since MARIADBCLIENT_VERSION_STRING is not a required variable.

And we should use pkg-config now that newer versions actually seem to ship a pc file. There was none when the find module was added.

**Comment by Rechi** [comment]
I suspect that the following line fails with too less arguments.
https://github.com/xbmc/xbmc/blob/e7b98c9a3217f419f4849a97b1c56fc899edcffb/cmake/modules/FindMariaDBClient.cmake#L34


Does `find_path` (https://cmake.org/cmake/help/v3.12/command/find_path.html) look at `<prefix>/include/<arch>` before `<prefix>/include`? In that case your cmake doesn't have the correct value for `CMAKE_LIBRARY_ARCHITECTURE`.

**Comment by candrews** [comment]
build.log: https://pastebin.com/V0V1HD2S
CMakeCache.txt: https://pastebin.com/8f6CGub4
CMakeOutput.log: https://pastebin.com/2BnJr5fQ
CMakeError.log: https://pastebin.com/0MQsKRa5

**Comment by wsnipex** [comment]
>Could NOT find MariaDBClient (missing: MARIADBCLIENT_LIBRARY)
as expected, it's not the missing version.

**Comment by candrews** [comment]
I tried https://github.com/xbmc/xbmc/pull/14602 and that didn't fix the problem. The output from that run is:
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MariaDBClient (missing: MARIADBCLIENT_LIBRARY) (found
  version "10.3.9")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindMariaDBClient.cmake:52 (find_package_handle_standard_args)
  cmake/scripts/common/Macros.cmake:374 (find_package)
  cmake/scripts/common/Macros.cmake:442 (find_package_with_ver)
  CMakeLists.txt:187 (core_optional_dep)
```

In case it helps, here are all the files I have regarding the mariadb client; I can provide contents too, course:
```
/usr/bin/mariadb_config -> x86_64-pc-linux-gnu-mariadb_config
/usr/bin/x86_64-pc-linux-gnu-mariadb_config
/usr/include/mariadb/errmsg.h
/usr/include/mariadb/ma_list.h
/usr/include/mariadb/ma_pvio.h
/usr/include/mariadb/ma_tls.h
/usr/include/mariadb/mariadb/ma_io.h
/usr/include/mariadb/mariadb_com.h
/usr/include/mariadb/mariadb_ctype.h
/usr/include/mariadb/mariadb_dyncol.h
/usr/include/mariadb/mariadb_stmt.h
/usr/include/mariadb/mariadb_version.h
/usr/include/mariadb/mysql.h
/usr/include/mariadb/mysql/client_plugin.h
/usr/include/mariadb/mysql/plugin_auth.h
/usr/include/mariadb/mysql/plugin_auth_common.h
/usr/include/mariadb/mysqld_error.h
/usr/include/x86_64-pc-linux-gnu/mariadb/mariadb_version.h
/usr/lib/debug/usr/bin/x86_64-pc-linux-gnu-mariadb_config.debug
/usr/lib/debug/usr/lib64/libmariadb.so.3.debug
/usr/lib/debug/usr/lib64/mariadb/plugin/dialog.so.debug
/usr/lib/debug/usr/lib64/mariadb/plugin/mysql_clear_password.so.debug
/usr/lib/debug/usr/lib64/mariadb/plugin/remote_io.so.debug
/usr/lib/debug/usr/lib64/mariadb/plugin/sha256_password.so.debug
/usr/lib64/libmariadb.so -> libmariadb.so.3
/usr/lib64/libmariadb.so.3
/usr/lib64/mariadb/plugin/dialog.so
/usr/lib64/mariadb/plugin/mysql_clear_password.so
/usr/lib64/mariadb/plugin/remote_io.so
/usr/lib64/mariadb/plugin/sha256_password.so
```

What further information can I provide to debug this issue?

**Comment by wsnipex** [comment]
so you don't have a pkgconfig file? Upstream ships it since v10.1: https://github.com/MariaDB/server/blob/10.1/support-files/mariadb.pc.in

I added another commit that should fix your issue by finding libmariadb.so, but you should check why the .pc file is missing.

**Comment by candrews** [comment]
I think you mean this .pc from the connector not from the server itself, right? https://github.com/MariaDB/mariadb-connector-c/blob/master/mariadb_config/libmariadb.pc.in

I reported the missing pkgconfig issue in Gentoo at https://bugs.gentoo.org/668664 - I'll work on fixing it.

**Comment by wsnipex** [comment]
did you try the PR again?

**Comment by candrews** [comment]
I did - with https://github.com/xbmc/xbmc/commit/99c667d71d25cd116bf27fe3578ef9a58ab1ce41 the problem is now solved.

Thanks again!
