### ISSUE TITLE
Kodi beta 3 sometimes crashs after resume from standby - PVR related

### ISSUE THREAD

**Issue by popy2k14** [xbmc/xbmc#14606]
### Describe the bug
Two of my kodi beta 3 (windows 10 x64  1803) clients sometimes (~once a week) crashes after resuming from standby. There is an DVBViewer addon related error message on the GUI and than it crashs.

Here is a clear and concise description of what the problem is:

I was able to successfully debug the crash dmp in Visual Studio 2017 and the beta 3 pdb.
It is related to PVR.

The exception is the following:
`Ausnahmefehler bei 0x00007FF789D996A0 (kodi.exe) in kodi_crashlog-18.0-BETA3 Git_20181002-c2e1b316f5-20181013-231740.dmp: 0xC0000005: Zugriffsverletzung beim Lesen an Position 0x0000000000000010`

It occured on line 77 in file "NetworkWin32.cpp" on the return statement of this function:

> std::string CNetworkInterfaceWin32::GetCurrentIPAddress(void) const
> {
>   return CNetworkBase::GetIpStr(m_adapter.FirstUnicastAddress->Address.lpSockaddr);
> }

The call stack was:
> kodi.exe!CNetworkInterfaceWin32::GetCurrentIPAddress() Zeile 77	C++
> kodi.exe!CNetworkBase::IsLocalHost(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & hostname) Zeile 194	C++
> kodi.exe!PVR::CPVRGUIActions::EventOccursOnLocalBackend(const std::shared_ptr<CFileItem> & item) Zeile 1785	C++
> kodi.exe!PVR::CPVRGUIActions::AllLocalBackendsIdle(std::shared_ptr<PVR::CPVRTimerInfoTag> & causingEvent) Zeile 1750	C++
> kodi.exe!PVR::CPVRGUIActions::CanSystemPowerdown(bool bAskUser) Zeile 1657	C++
> kodi.exe!CApplication::CheckShutdown() Zeile 3917	C++
> kodi.exe!CApplication::ProcessSlow() Zeile 4348	C++
> kodi.exe!CApplication::Process() Zeile 4300	C++
> kodi.exe!CXBApplicationEx::Run(const CAppParamParser & params) Zeile 66	C++
> kodi.exe!XBMC_Run(bool renderGUI, const CAppParamParser & params) Zeile 80	C++
> kodi.exe!WinMain(HINSTANCE__ * hInst, HINSTANCE__ * __formal, char * commandLine, int __formal) Zeile 125	C++

@manuelm: stated in the addon github project that this issue is not addon related because no pvr addon related functions are called during the crash, see: https://github.com/manuelm/pvr.dvbviewer/issues/34#issuecomment-429624736

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should not crash!

## Actual Behavior

It crashes sometims.

## Possible Fix

More robust code in "NetworkWin32.cpp"

### To Reproduce

1. Install kodi beta 3 in windows
2. Setup DVBViewer addon with your backend
3. Do standby/resume multiple times over days
4. sometimes it crashes

### Debuglog

The debuglog can be found here: https://paste.ubuntu.com/p/pMswSMPff6/
Sadly no debug log but also a crash dump.
[kodi_crashlog-18.0-BETA3 Git_20181002-c2e1b316f5-20181013-231740.zip](https://github.com/xbmc/xbmc/files/2476405/kodi_crashlog-18.0-BETA3.Git_20181002-c2e1b316f5-20181013-231740.zip)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64 build 1803
 - Kodi version: 18 beta 3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

@ksooo: Can you please look into it, since you are the PVR chief :-)

**Comment by ksooo** [comment]
Seems to be no PVR problem. @afedchin might want to take a look because it is crashing in our Windows network implementation.

**Comment by popy2k14** [comment]
thx, wil test tomorrows build and come back if the issue is not solved.

**Comment by popy2k14** [comment]
No crash after 7 days, your fix solved the issue. thx
