### ISSUE TITLE
Last line in embedded cue sheet is ignored.

### ISSUE THREAD

**Issue by MacMajster** [xbmc/xbmc#14601]
### Describe the bug
Here is a clear and concise description of what the problem is:

Any Vorbis audio files with embedded cue sheet will not have the last line within this sheet processed.
For example, if last line happens to be TITLE command, then Kodi instead of showing the name of the track will display "Track N" (where N is the number for the last track in the cue sheet).
When the same cue sheet is removed from audio file and placed in an external .cue file, then Kodi processes its contents correctly.

Workaround: Add empty line at the end of embedded cue sheet. Not very practical when there are tens or hundreds of audio files with embedded cue sheets. Too much manual editing.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Cue command on last line within embedded sheet should be processed.
For most obvious/visible scenario: Track's title should be displayed in album's list of tracks.

## Actual Behavior

Cue command on last line within embedded sheet is ignored.

## Possible Fix

Ensure all lines of embedded cue sheet are read.

### To Reproduce

1. Embed into a .flac or .opus audio file a cue sheet with TITLE command on its last line.
2. Update Kodi's library.
3. View list of tracks in album stored in audio file prepared in step 1. Last one should be titled - "Track N".
4. Remove cue sheet from album file.
5. Create .cue file with exactly same content as in step 1 and obviously name the file same as the audio file.
6. Again, update Kodi's library and view list of album's tracks. Last one now should have its correct name shown.

### Debuglog
The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 -  Windows
 - [ ] Windows UWP

 - Operating system version/name: **Fedora 28, Windows 10**
 - Kodi version: **At least all of versions 17 and 18**.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
Can you upload a sample file please? Actual cue sheets embedded in FLAC files do not contain any title/artist information at all, so there is obviously some misunderstanding involved here. You're probably talking about vorbis tags.

**Comment by MacMajster** [comment]
[Embedded Cue sheet test.zip](https://github.com/xbmc/xbmc/files/2487416/Embedded.Cue.sheet.test.zip)

For sake of practicalities (size) I've put together a two-track .opus file.
Second track will be listed as Track 2.
Once you saved cue sheet into a .cue file and removed it from .opus, track's correct name will be shown.
Will have the same results with .flac
Btw, I edit my album files' tags with either with AIMP's Advanced Tags Editor (Win) or kid3 (Win/Linux).
