### ISSUE TITLE
XBOX: Problem with 2160p resolution (missing menu text in all panels)

### ISSUE THREAD

**Issue by akshatbh** [xbmc/xbmc#14610]
After a fresh install, if you do the following steps:
1) go to system settings: Kodi will autodetect reolutions, choose 'Yes' to save the detected resolution. In my case I have a 4K TV (LG OLED) but Kodi detected resolution is 1080p.
2) Change resolution to 2160p from the list options
3) Change refresh rate to 59.94 from the list

So far so good, everything works well.

Now if you quit Kodi and restart, then Kodi starts up with all menu text missing - only images and other graphics can been seen but there is no text of any kind.

this can only be fixed by renavigating to system and display option and resetting to defaults which then resets the resolution to 1080p.

This means that 2160p resolution cannot be enabled.

This only started happening with the 18.0 Beta 3 release. It had worked fine in the Beta 2.

**Comment by MartijnKaijser** [comment]
Why didn't you follow the template we made asking specific questions like debuglogs, screenshots and all that?

**Comment by akshatbh** [comment]
I cannot upload debug logs unfortunately as it is impossible to navigate once the text goes missing, unless you have a clever way of getting around that. I will be happy to upload a screenshot though if that helps? I thought the problem would be quite self explanatory.

**Comment by akshatbh** [comment]
Screenshots:
![20181014_230703](https://user-images.githubusercontent.com/10160858/46932945-db27cd00-d006-11e8-93bf-671bc71f9c70.jpg)
![20181014_230725](https://user-images.githubusercontent.com/10160858/46932946-db27cd00-d006-11e8-8998-2fc53115c5bd.jpg)

**Comment by pkerling** [comment]
Hi,

when you open a new issue for this that follows the template, we definitely do need a debug log. You can enable that before the problem appears.

See https://kodi.wiki/view/Log_file/Easy

**Comment by akshatbh** [comment]
ok, i have created a new issue with as much info as possible. hope that is enough to help fix the issue.
