### ISSUE TITLE
XBOX: Issue with 2160p resolution

### ISSUE THREAD

**Issue by akshatbh** [xbmc/xbmc#14617]
### Describe the bug
Here is a clear and concise description of what the problem is:

If I switch the resolution to 2160p and restart Kodi then Kodi comes up with all menu/panel text entries missing. Please see repro, debug log link and screenshots below.
The only resolution to this problem is to reset the display defaults, which resets the  resolution to 720p and then the menu/panel text reappears. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should startup normally with 2160p enabled, with menu and panel text displayed as expected.

## Actual Behavior

When Kodi is restarted after switching to 2160p, all menu/panel text disappears. See screenshots.

## Possible Fix

I have tried uninstalling and reinstalling a few times, but this did not fix the problem. Also I noticed this only in 18.0 Beta 3. It seemed to be working fine in Beta 2.

### To Reproduce

Fresh install or existing install:
1) go to system settings: Kodi will autodetect reolutions if fresh install, choose 'Yes' to save the detected resolution. In my case I have a 4K TV (LG OLED) but Kodi detected resolution is 720p.
2) Change resolution to 2160p from the list options
3) Choose any refresh rate

So far so good, everything works well.

4) quit Kodi and restart
5) Kodi starts up with all menu text missing - only images and other graphics can been seen but there is no text of any kind.
6) this can only be fixed by renavigating to system and display option and resetting to defaults which then resets the resolution to 720p.

This only started happening with the 18.0 Beta 3 release. It had worked fine in the Beta 2.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/amufelicob

### Screenshots 
Here are some links or screenshots to help explain the problem:

![46932945-db27cd00-d006-11e8-93bf-671bc71f9c70 - copy](https://user-images.githubusercontent.com/10160858/46971361-989ada80-d070-11e8-9e3e-08f1ef9366a3.jpg)
![46932946-db27cd00-d006-11e8-8998-2fc53115c5bd - copy](https://user-images.githubusercontent.com/10160858/46971362-989ada80-d070-11e8-8d86-8a9f3af54007.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: XBOX One S
 - Kodi version: 18.0 Beta 3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by kib** [comment]
Several other users on Xbox are reporting the same issue on this reddit thread:
https://www.reddit.com/r/kodi/comments/9nhqhz/

**Comment by akshatbh** [comment]
For other users having this issue, I can share that this problem does not happen for me with 720p or 1080p resolutions but only 2160p (4K). So if I drop down the resolution to 1080p, I can continue using Kodi in 'limp mode'

**Comment by akshatbh** [comment]
@afedchin - any idea when this will be fixed? There seem to be other resolution/whitelist/4K issues cropping up and may be related? It will be great if they can be fixed in v18 :)

**Comment by afedchin** [comment]
as fast as possible, sorry but I have no time absolutely, very busy at the work and home.
