### ISSUE TITLE
Information in Videosize transformation is missing

### ISSUE THREAD

**Issue by Canuma** [xbmc/xbmc#14634]
### Describe the bug
I noticed a Problem on Kodi 18 Beta (including V2)
Whenever I play a Video an press Z(oom) the information on the videosize transformation is missing 

## Expected Behavior
Show the orig video size --> upscaled size

## Actual Behavior
it shows 0,0 --> 0,0

## Possible Fix

Unknown

### To Reproduce

1. Play a Video
2. Resize Video 
3.

### Debuglog

The debuglog can be found here:
https://paste.ubuntu.com/p/SgB95yWhPh/

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://ibin.co/4FQ29v8o3K5R.png

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Bug report on kodi.tv:
https://forum.kodi.tv/showthread.php?tid=335470

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18 Beta 3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
@FernetMenta maybe a VP problem?

**Comment by phunkyfish** [comment]
@Canuma - Is this issue still occurring? If so could you also check Matrix nightlies?

**Comment by DaVukovic** [comment]
@phunkyfish 

yes it is. That's from Matrix

![image](https://user-images.githubusercontent.com/7235787/76349359-1f0d2780-630a-11ea-8774-fb77c00bc34f.png)

as you can see, there's still 0.0 -> 0.0 showing even if the zoom it x1.04
