### ISSUE TITLE
PAPlayer should follow url redirections

### ISSUE THREAD

**Issue by pitsi** [xbmc/xbmc#14631]
Bug report
I have made a single-entry pls file to listen to my favorite web radio station. Here are its contents

> [playlist]
> NumberOfEntries=1 
> File1=http://stream.radiojar.com/n4n9x10yzd5tv
> Title1=boombox.com.gr
> Length1=-1

It plays as it should on mpv, mplayer, deadbeef, vlc and foobar2k, but not on kodi.

 Expected Behavior
It should play on kodi like it does on the other players that were tested.

 Actual Behavior
It does not play on kodi only, because paplayer does not follow redirects

 Possible Fix
Only for kodi, I had to change the url to thisso that paplayer finds the "correct" one. I hope it won't change in the near future. 

`http://ample-10.radiojar.com/n4n9x10yzd5tv`

So please make, paplayer follow redirects

 To Reproduce
Make a plain text file and paste the above content. There are five lines thare, not one as github's editor merged them
Save it as whatever.pls and place it in a folder visible by kodi's music library. Try playing it with kodi. An error will come up saying it can not play it.

 Debuglog
Here. I used a pastebin service because github's editor would put them in one line
https://paste.kodi.tv/tuvolatoce.kodi

 Screenshots 
No screenshots

 Additional context or screenshots (if appropriate)
(none)

 Your Environment
Used Operating system: Debian testing x64 and libreelec arm 8.2.5 
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

Operating system version/name: Debian testing x64 (codenamed buster at the time of this report), libreelec 8.2.5 on rpi zero
Kodi version: 17.6 on both

**Comment by MartijnKaijser** [comment]
You did not follow our template you need to fill in with specific steps!

**Comment by pitsi** [comment]
I think my description is completely clear. However, I will try completing it. Give me a sec...

**Comment by pitsi** [comment]
Is it right now? Oddly, the forum I asked you to look is the one provided by YOUR site for YOUR app...

**Comment by pkerling** [comment]
> Is it right now? Oddly, the forum I asked you to look is the one provided by YOUR site for YOUR app...

GitHub issues should be self-contained and mention all relevant information in order to be useful to developers. This is exactly why the template exists which you chose to ignore. Forum threads (if available) are good for additional information, but cannot replace the text of the report.

Please assume we have reasons for why things are done the way they are and you need to follow the rules if you want to be taken seriously. This is true for any open-source project by the way.

**Comment by pitsi** [comment]
For ALL the issues I have opened here on github, I have provided all the extra info needed. It is not the first time I open one, nor the last, so yes I chose to "ignore the book" and focus on what really matters.
EVERY crucial information was given in my original post, the one before the forced editing. It is publically visible, feel free to check.

The reason for the edit was to comply to the bureaucracy of this, and only this. github repo. No other repo has asked me to edit my issue for a similar reason, just you.
And trust me, if I was good at programming, I would have also made a patch and have it submitted with the issue repost. I am not, so all I can provide is the "why" behind kodi's behavior. 

As for the "to be taken seriously" part of the conversation, how do you expect me to take you seriously with an answer like "try using v18, we do not fix anything on v17". Maintained or not, 17 is the current stable version = the one the average user should have if he does not wish to be a tester/reporter/etc. I would have no problem seeing the issue fixed on 18, but I will not be able to check if it is by the time 18 reaches stable.

**Comment by M2k80** [comment]
only for info, i tested his playlist on my shield, its not playing on kodi v18 latest beta

**Comment by pitsi** [comment]
@stealthflyer 
Let's agree to disagree, on both of the the facts you mention. I won't push that discussion further.
As for testing v18, please read what I said above on why I can not get v18 now.

@M2k80 
Thank you! Does it play with the redirected url (= the one starting with "ample-10")?

@MartijnKaijser 
Since it also fails to play on v18, as @M2k80 mentioned, how about adding the "v18 Leia" tag to it so it won't get ignored by the time 18 reaches stable?

**Comment by M2k80** [comment]
@pitsi with ample-10 links its working on kodi 18
without debug log i just only see this ERROR: CCurlFile::Stat - Failed: Unsupported protocol(1) for nfs://xxx.xxx.xxx.xx/downloads/test.pls

maybe i find time on weekend for a full debug log

**Comment by M2k80** [comment]
here the debug log
https://pastebin.com/xaa5yDLm
