### ISSUE TITLE
[Android] VisibleBehind only displaying a still image

### ISSUE THREAD

**Issue by CiNcH83** [xbmc/xbmc#14645]
### Describe the bug
Recent changes seem to have introduced a regression in VisibleBehind. When pressing the HOME button, only a still image is displayed in the background while audio continues. Pressing the HOME button again, therefore bringing Kodi back to the foreground, resumes video.

[EDIT]
Same thing happens when bringing up the [ACTION MENU](https://forum.kodi.tv/showthread.php?tid=309762&pid=2550207#pid2550207). Video is being "paused" while audio resumes. Looks like it happens when Kodi loses focus, probably related to [this PR](https://github.com/xbmc/xbmc/pull/14597), even though it only mentions that GUI is suspended/resumed, not video.

### To Reproduce
(1) start Kodi
(2) play video
(3) press HOME > VisibleBehind > still image of video in background
(4) press HOME > stop VisibleBehind > video continues
(5) stop video

### Debuglog
A debuglog, where the above steps have been executed, can be found here: [[LOG](http://paste.kodi.tv/ocuwofefug)]

### Environment
Used Operating system:
 - [x] Android

 - Operating system version/name: Android TV Nougat (Sony BRAVIA)
 - Kodi version: 18.0-BETA4 Git:20181017-389f30d

Pinging @peak3d

**Comment by da-anda** [comment]
can confirm this issue. Also happens on my Philips AndroidTV now. In addition, as soon as I bring up the TV OSD to f.e. adjust the picture, change Ambilight settings etc, KODI will "freeze" as long as it lost focus.
I suspect that it's related to #14597 but didn't test the nightly before this PR went in yet. @CiNcH83 - if you have a spare moment you could test and see if http://mirrors.kodi.tv/nightlies/android/arm/master/kodi-20181012-216317a3-master-armeabi-v7a.apk doesn't have that issue (according to the GIT hash, this build should not yet have that change in)

**Comment by M2k80** [comment]
@CiNcH83 you will get the same crash like in the forum thread, if you start kodi and switch to another app for ex. youtube and back to kodi ERROR: eglSwapBuffers failed (EGL error 12288)

**Comment by peak3d** [comment]
From documentation it is corect that we "pause" the playback because the android Intend tells kodi to pause. Sure we have to implement a real pause (decoding has to be suspended, too, but this needs some more implementation (e.g. we cannot pause livestreams easily)

**Comment by CiNcH83** [comment]
> From documentation it is corect that we "pause" the playback because the android Intend tells kodi to pause. 

What's the purpose of background playback (a.k.a. VisibleBehind) if video playback is paused?

**Comment by da-anda** [comment]
in Oreo, there is no "visible behind" anymore - they removed it. All you get is a small dialog on top of the channel/app lists that shows the currently active/playing app with the option to go back to it or close it (IIRC, so not even media controls).

**Comment by CiNcH83** [comment]
Fixed with https://github.com/xbmc/xbmc/pull/14686
