### ISSUE TITLE
Smart Playlist problems with audio search

### ISSUE THREAD

**Issue by antoniocaruso** [xbmc/xbmc#14659]
### Describe the bug
Here is a clear and concise description of what the problem is:

If you want a list of all movies that are stereo in my language (italian), you go to playlist and
create a smart playlist. I added the rules:
1) audio channel is 2
2) audio language is "ita"
then if you open the list you get movies with 5.1 dolby and dts. So the filter is not working at all.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The list must include only the movies that satisfy the search. Please, if this is an issue related to the
format of the db, you have to check that language based search is working. The player correctly
indicate if there is more than one track, and the language of each track, so it is a matter of properly
collect and search those infos.

## Actual Behavior

The list include movies with 5.1 dolby digital audio track, so movies that do not satisfy the query.

## Possible Fix

Just check if the way you build the sql query is correct. Please add in debug the query that is played 

### To Reproduce

1. Create a library of movies with stereo and dolby digital or dts audio tracks, add movies with different languages and different number of tracks for languages.
2. Create a smart playlist as described before, to select only the stereo movies in one specific language.
3. See the result if it is correct.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.beta

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
For what I can tell the query is 100% correct and the filter works as expected. I would go even further and say this is not even an issue with our database. 

Looking at the database, I see multi entries for the same movie being separated in different "streamdetails". For example:

one entry for movie "A" with 6 channels in english
one entry for movie "A" with 6 channel in german
one entry for movie "A" with 2 channels in english

Please see:

![image](https://user-images.githubusercontent.com/7235787/148677021-31f4321f-a3f1-4dc5-987c-39445fd3681c.png)

As you can see, it's all the same "idFile" which mean it's the same movie. It has multiple entries for the "streamdetails"-view as there are multiple streams.

The query we set when creating a smart playlist is to find movie IDs where audiochannel **is** 2. So we iterate over the DB searching for "iAudioChannels = 2" and provide that "idFile". This works 100% correctly with Kodi v20. It's neither Kodis fault nor an issue with the database if the same movie, which does contain a 2.0 audio stream also contains a 5.1 audio stream. It's more an issue with the creation of the smart playlist as one is able to set the following:

![image](https://user-images.githubusercontent.com/7235787/148677308-733338b2-2cf3-45db-8164-4342ffe7b3e5.png)

By setting `audiochannels = 2` **AND** `audio track count = 1` only those movies with 2.0 channels are listed. 

Going to close this
