### ISSUE TITLE
[games] Not possible to use controller on games

### ISSUE THREAD

**Issue by AlwinEsch** [xbmc/xbmc#14654]
### Describe the bug
Here is a clear and concise description of what the problem is:

During test of Game Add-ons was it not possible to control the games by the controller.
The control over Kodi with Joystick has worked normal, but on a started game was no control given to them.
Joystick button setup has worked normal.

Thought on begin it have something to do with the accelerometer of my Laptop but also after disable of them was the fault present.

Also by two connected Controllers still problem.

This shows a bit suspect for me:
```
DEBUG: AddOnLog: 2048: Port: 0, Device: RETRO_DEVICE_JOYPAD, Feature: RETRO_DEVICE_ID_JOYPAD_LEFT, Description: Left
....
ERROR: Failed to open port "1", no controller given
```
There brings it info of Port 0 but says that he open port 1.

## Expected Behavior
Maybe something related to my system, but has not found something what can explain me these circumstances. And because I do not quite understand the game system, I could not understand why.

### To Reproduce
No idea, was the normal use of the game addons.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ituwogoyoj.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Ubuntu 18.04
 - Kodi version:
Master branch

### Hardware:
https://paste.kodi.tv/iqezuzecej.kodi

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ccope** [comment]
I agree that the setup flow isn't very clear.  You have to make sure the joystick binary addon is enabled, and set up a controller profile in the input settings. It would be great if there was a pop-up wizard or message when controllers are missing.

**Comment by AlwinEsch** [comment]
@garbear Have looked over the code and found one part who bring the Problem.

The [CControllerPortNode::SetConnected ](https://github.com/xbmc/xbmc/blob/master/xbmc/games/controllers/types/ControllerTree.h#L1249) becomes only one time called on [CGameClientTopology::GetPortNode](https://github.com/xbmc/xbmc/blob/master/xbmc/games/addons/input/GameClientTopology.cpp#L57) with `portNode.SetConnected(false);` and the [m_bConnected](https://github.com/xbmc/xbmc/blob/master/xbmc/games/controllers/types/ControllerTree.h#L190) value of them is already set on construction to false.

No other place inside Kodi where this becomes set. Should this be a `portNode.SetConnected(true);` and only a Typo with **false** and **true**?

**Comment by AlwinEsch** [comment]
If only a typo is here a fix https://github.com/AlwinEsch/kodi/commit/1a263c8dc4dc46ac03ed2c8268b2768cb80d582e

**Comment by garbear** [comment]
@AlwinEsch you nailed the problem, thanks so much. The referenced line is actually correct, you want to recursively initialize the topology to unconnected. The problem is the line that sets it to true is missing :) I'll submit a PR now.

**Comment by garbear** [comment]
@ccope I agree that we should notify the user when they start a game with no controllers. I added the following help dialog when the user first loads a game:

![game_help_message](https://user-images.githubusercontent.com/531482/47271756-ea3fdb00-d530-11e8-9016-ff0ab32a85fd.png)

It says that controllers are required, but there's no feedback if controllers are connected but missing/broken/unmapped. What behavior do you think we should have?

**Comment by Razzeee** [comment]
In case of unmapped, just open up the mapping dialog?

**Comment by garbear** [comment]
The first time the user presses a button on an unmapped controller, they get a dialog (see https://github.com/xbmc/xbmc/pull/11648). However, if they dismiss this, it doesn't come back. That should handle unmapped controllers.

When the controller mapper is finished, we should be able to automatically generate button maps for most controllers, even if they've never been seen on that platform before, so as time goes on this dialog will be shown less and less.

Is that kind of what you're talking about?
