### ISSUE TITLE
PVR Connection Issue

### ISSUE THREAD

**Issue by Andystew94** [xbmc/xbmc#14661]
### Describe the bug
Here is a clear and concise description of what the problem is:

The PVR backend loses connection after waking the PC up from sleep mode.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The PVR backend does not lose connection after waking the PC up from sleep mode.

## Actual Behavior

1. The computer has gone into Sleep mode (with Kodi running).
2. User wakes up the computer after 5+ mins (with Kodi running).
3. User clicks on any of the "TV" related menu options (to see channels, recordings, etc).
4. No information appears.

It should be noted in the "system info" screen of Kodi, it says the PVR is still connected. 

## Possible Fix

The only resolution currently is to close Kodi 18 and restart.

### To Reproduce

1. Put the computer into Sleep mode (with Kodi running).
2. Wake up the computer after 5+ mins (with Kodi running).
3. User clicks on any of the "TV" related menu options (to see channels, recordings, etc).
4. Check if any information appears (channels, recordings, etc)

### Debuglog

Not available.

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://imgur.com/a/qvGJ9hK

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18 Beta 3, for the specific build version refer to screenshots.
 - PVR: NextPVR, specific build version, refer to screenshots.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
As this works with other pvr backends (like tvheadend) is say this is a problem with the nextpvr pvr client add-on. Open a ticket for the add-on, please.

**Comment by Andystew94** [comment]
Considering it works with Kodi 17 without any issues, what evidence points to the nextpvr pvr client add-on?

**Comment by ksooo** [comment]
Evidence? What are you going to tell me?

**Comment by ksooo** [comment]
@sub3 what's your take on this? Could you take a look? I want evidence, that Kodi core is guilty, haha.

**Comment by Andystew94** [comment]
I am not hear to tell you anything. I was simply raising a problem request as per the instructions. No need to be so abrupt and rude. I was simply asking for any information you had which I could pass onto the pvr add-on ticket.

**Comment by ksooo** [comment]
> No need to be so abrupt and rude. 

 OMG. I'm sorry. Where are you from? I'm German and used to say/write straight what I think.

> I was simply asking for any information you had which I could pass onto the pvr add-on ticket.

 If you would have written this instead of asking for some evidence, my reaction what have been different, for sure.

 Although I might ofc be wrong with my assumptions, as long time PVR mainainer (core and one addon as well) I have a pretty much experience when it comes to "guessing" where the root cause for problems could be located.

**Comment by sub3** [comment]
I'm not aware of any issue along the lines of the description above, and unfortunately I'm about 9000 miles from my development/test environment for about a week, so can't check it myself right now.

The NextPVR add-on doesn't hold a connection to the backend though, and simply makes http requests as required, so no connection to have been lost. @Andystew94, if you can supply the kodi.log (with debug logging enabled), and the NextPVR logs, I'm happy to take a look for you.

**Comment by Andystew94** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/2500716/kodi.log)

Please see attached. At the end of the log, is where I try and access the recordings via Kodi. It appears to fail to load the source. The IP address is the default as NextPVR is running on the same machine.

**Comment by ksooo** [comment]
<pre>
17:23:53.544 T:2792   ERROR: Error updating database Epg12 from version 11 to 12
17:23:53.554 T:2792  NOTICE: Old database found - updating from version 11 to 12
17:23:58.109 T:2792  NOTICE: Attempting to update the database Epg12 from version 11 to 12
17:23:58.418 T:2792   ERROR: SQL: [Epg12.db] Abort due to constraint violation
                                            Query: CREATE UNIQUE INDEX idx_epg_idEpg_iStartTime on epgtags(idEpg, iStartTime desc);
17:23:58.418 T:2792   ERROR: Exception updating database Epg12 from version 11 to 12
17:23:58.418 T:2792   ERROR: Error updating database Epg12 from version 11 to 12
</pre>

@Andystew94 most probably not related to this issue, but your EPG database somehow got damaged. You should delete the database file when kodi is down. It will be got recreated on next kodi startup.

**Comment by ksooo** [comment]
Lots of "Network down"  and "Add-on 'NextPVR  (127.0.0.1):connected' returned an error: server error" in your log after resuming. Can you access network resources from outside Kodi (e.g. using a web browser) after resuming?

**Comment by Andystew94** [comment]
I can access all network resources without any issues.

**Comment by Andystew94** [comment]
I will have a look at the database file.

**Comment by sub3** [comment]
I've just taken a look at the log, and also find it strange that other network activities are failing. It appears your networking is down at the time, or possibility you've got firewall/antivirus software doing something odd after a waking the machine.

**Comment by Andystew94** [comment]
It could be when the pc wakes up from sleep there is a delay from when kodi makes the query and the WiFi is reconnected. In regards to the pvr, would this matter? The pvr is running on the same machine.

**Comment by ksooo** [comment]
I don't think in case network is down localhost communication will work. But I'm not an expert on this.

Seems we're facing a more general problem here, not a PVR only issue.

Unfortunately, I'm the wrong person to fix this.

@afedchin in case it's a Windows problem, do you have any thoughts on this?

**Comment by afedchin** [comment]
on Windows there must be at least one interface to make sure that network is available. software loopback interface is ignored.

I suggest to apply this change
```patch
--- a/xbmc/filesystem/FileFactory.cpp
+++ b/xbmc/filesystem/FileFactory.cpp
@@ -130,7 +130,7 @@ IFile* CFileFactory::CreateLoader(const CURL& url)
 #endif
 
   bool networkAvailable = CServiceBroker::GetNetwork().IsAvailable();
-  if (networkAvailable)
+  if (networkAvailable || url.IsLocalHost())
   {
     if (url.IsProtocol("ftp")
     ||  url.IsProtocol("ftps")
```

**Comment by manuelm** [comment]
I've got two independent reports from `pvr.dvbviewer` users as well. All requests were killed with `Network down or unsupported protocol(http)`.

One with localhost as target: https://forum.kodi.tv/showthread.php?tid=336813 - He created a fake interface (`Microsoft test loopback adapter`) to trick Kodi into thinking the network is up all the time.

One with a LAN address as target: https://forum.kodi.tv/showthread.php?tid=336813

Since I never observed this myself I asked @popy2k14 if he could share/help with more details.

**Comment by popy2k14** [comment]
Because my two kodi clients will be used in "peoduction" and the WAF was very low i have changed it to shutdown instead of resume. Here in the thread (alrteady linked @manuelm) are some logs: https://forum.kodi.tv/showthread.php?tid=336813

It also has the same messages as above mentioned by @ksooo 

`20:24:08.676 T:8976 WARNING: XFILE::CFileFactory::CreateLoader - Network down or unsupported protocol(http) in http://192.168.0.5:8089/api/epg.html...`

and

`20:24:08.677 T:8976   ERROR: PVR::CPVRClient::GetEPGForChannel: Add-on 'DVBViewer Media Server 2.1.2.0 (MEDIASERVER):192.168.0.5:8089' returned an error: server error`

It happened randommly, i have'nt figered out how to reproduce the issue.
But on both windows 10 x64 1803 clients.

Also, like @Andystew94 stated, kodi sayed connected under system but PVR could not establish a connection. One time I have leaved kodi opened and swithced to explorer/chrome... network was working fine, just kodi did'nt recognized it correctly. After kodi restart everything was working "without" an windows restart.

Sadly havent tried any other kodi related network thing like playing an youtube videe, movie or anything else.

**Comment by d3m10n** [comment]
> One with localhost as target: https://forum.kodi.tv/showthread.php?tid=336813 - He created a fake interface (`Microsoft test loopback adapter`) to trick Kodi into thinking the network is up all the time.

thread: [lost connection to 127.0.0.1 when network disconnected](https://forum.kodi.tv/showthread.php?tid=337178)

**Comment by FernetMenta** [comment]
A network connection does not survive sleep/hibernation. It is the responsibility of the addon to check connection status and reconnect if required. This is obviously not done by the failing addons.
After an error message like:

```
ERROR: AddOnLog: DVBViewer Client: Unable to open url
```

you should see the addon taking action and reconnect to the backend.

**Comment by manuelm** [comment]
The PVR is trying to cnnect however Kodi kills the connection:
```
21:50:02.040 T:6464 WARNING: XFILE::CFileFactory::CreateLoader - Network down or unsupported protocol(http) in http://192.168.0.5:8089/....
21:50:02.040 T:6464   ERROR: AddOnLog: DVBViewer Client: Unable to open url: http://192.168.0.5:8089/...
```

There's nothing I (as PVR maintainer) can do about this.

**Comment by FernetMenta** [comment]
Wrong. First you have to notify Kodi about connection lost. If you did this, we would not see this error in the log. Then you have to re-establish backend connection and notify Kodi again.

**Comment by manuelm** [comment]
I'm doing all this since the API has been introduced...

See this debug log:
```
14:25:46.488 T:9876    INFO: AddOnLog: DVBViewer Client: Performing timer/recording updates!
14:25:46.490 T:9876 WARNING: XFILE::CFileFactory::CreateLoader - Network down or unsupported protocol(http) in http://127.0.0.1:8089/api/timerlist.html?utf8=2|Accept=text%2fxml&user-agent=Kodi%20PVR
14:25:46.490 T:9876   ERROR: AddOnLog: DVBViewer Client: Unable to open url: http://127.0.0.1:8089/api/timerlist.html?utf8=2
14:25:46.490 T:9876   DEBUG: AddOnLog: DVBViewer Client: Connection state change (5 -> 1)
14:25:46.490 T:9876   DEBUG: PVR::CPVRClient::cb_connection_state_change: State for connection '127.0.0.1' on client 'DVBViewer Client' changed from '5' to '1'
14:25:46.490 T:9876    INFO: AddOnLog: DVBViewer Client: Trying to connect to the backend server...
14:25:46.490 T:6288   DEBUG: PVR::CPVRRecordings::Update: Updating recordings
14:25:46.490 T:6288   ERROR: PVR::CPVRClient::GetRecordings: Add-on 'DVBViewer Recording Service 1.33.2.0 (beta) (DESKTOP-7D0JF0A):127.0.0.1:8089' returned an error: server error
14:25:46.490 T:6288   ERROR: PVR::CPVRClients::GetRecordings: PVR client 'DVBViewer Recording Service 1.33.2.0 (beta) (DESKTOP-7D0JF0A):127.0.0.1:8089' returned an error: server error
14:25:46.490 T:9876 WARNING: XFILE::CFileFactory::CreateLoader - Network down or unsupported protocol(http) in http://127.0.0.1:8089/api/version.html|Accept=text%2fxml&user-agent=Kodi%20PVR
14:25:46.490 T:9876   ERROR: AddOnLog: DVBViewer Client: Unable to open url: http://127.0.0.1:8089/api/version.html
14:25:46.490 T:9876    INFO: AddOnLog: DVBViewer Client: Connection to the backend server failed. Retrying in 10 seconds...
14:25:56.491 T:9876    INFO: AddOnLog: DVBViewer Client: Trying to connect to the backend server...
14:25:56.493 T:9876 WARNING: XFILE::CFileFactory::CreateLoader - Network down or unsupported protocol(http) in http://127.0.0.1:8089/api/version.html|Accept=text%2fxml&user-agent=Kodi%20PVR
14:25:56.493 T:9876   ERROR: AddOnLog: DVBViewer Client: Unable to open url: http://127.0.0.1:8089/api/version.html
14:25:56.493 T:9876    INFO: AddOnLog: DVBViewer Client: Connection to the backend server failed. Retrying in 10 seconds...
```

So please explain to me how I should reconnect to the backend if Kodi prematurely kills all http requests.

**Comment by manuelm** [comment]
I do not do that at all. I'm using `CURLCreate` + `CURLOpen`: https://github.com/manuelm/pvr.dvbviewer/blob/master/src/DvbData.cpp#L884

**Comment by FernetMenta** [comment]
> I do not do that. I'm using CURLCreate + CURLOpen: 

exactly, and this results in the error. You should not call those in any other state than connected

**Comment by manuelm** [comment]
You do understand that this issue is about the fact that this does not resolve even if the network connection is up again? The fact that those log lines exist don't bother me at all. The fact that the PVR stays disconnected (because Kodi does not allow the connection) although network connection is up again does.

Users create a fake network device just to trick Kodi into thinking there's a connected network. And suddenly the PVR can connect again.

**Comment by FernetMenta** [comment]
In current code I see that you call CURLCreate + CURLOpen in disconnected state. This is wrong. Why don't you correct this and post new logs for further investigation?

**Comment by manuelm** [comment]
As already said I never observed this myself. And the state code worked since the API has been introduced.

Also to which state shall I change? I'm changing to `PVR_CONNECTION_STATE_CONNECTING` exactly once on PVR initialization. Exactly like tvheadend does. Otherwise users constantly get annoying notifications. `..._STATE_CONNECTED` is obviously wrong too.

**Comment by d3m10n** [comment]
Like @manuelm mentioned for me the problem was that the PVR dvbviewer lost the connection to the backend on same machine (stand alone / 127.0.0.1 localhost), if I lost the wifi connection - thats happens only with kodi v18. PVR can't connect to backend if the isn't at least one network connection established.

I solved the problem for me with an installation of a loopback interface. Since i used the loopback i can use PVR without any other network connection like wifi or eth and there is'nt any disconnect PVR <> backend or interruption even if I lose the unnecessary wifi connection.

**Comment by popy2k14** [comment]
I can't reproduce it quickly, it happend once in 1-2 weeks.
Maybe @d3m10n can reproduce it faster?

**Comment by d3m10n** [comment]
I will reproduce what ever you want, but how could I test an other http source on localhost?

**Comment by manuelm** [comment]
You can create a local m3u file which contains the url to an recorded video or even to a livestream channel. That should work.

I'm still not able to reproduce this :/ Maybe it's a windows only issue.

**Comment by ksooo** [comment]
> Maybe it's a windows only issue.

 well, that could the case as so far we have only seen these error reports from windows users.

**Comment by d3m10n** [comment]
I've made my tests with test-http-local.strm file  containing one line `http://127.0.0.1:12345/test.avi`

With loopback adapter:
- PVR dvbviewer addon runs.
- Video test.avi runs.
```
00:09:35.650 T:6180   DEBUG: CGUIWindowVideoBase::OnPlayMedia C:\Users\username\Desktop\test-http-local.strm
00:09:35.650 T:6180    INFO: XCURL::DllLibCurlGlobal::easy_acquire - Created session to ://
00:09:35.650 T:6180   ERROR: CCurlFile::Stat - Failed: URL using bad/illegal format or missing URL(3) for C:\Users\username\Desktop\test-http-local.strm
00:09:35.650 T:6180   DEBUG: CCurlFile::GetMimeType - C:\Users\username\Desktop\test-http-local.strm -> failed
00:09:35.654 T:7108   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
00:09:35.654 T:7108   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
00:09:35.654 T:7108   DEBUG: CAnnouncementManager - Announcement: OnRemove from xbmc
00:09:35.654 T:7108   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnRemove
00:09:35.656 T:6180   DEBUG: CPlayerCoreFactory::GetPlayers(http://127.0.0.1:12345/test.avi)
00:09:35.656 T:6180   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: system rules
00:09:35.656 T:6180   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: system rules
00:09:35.656 T:6180   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mms/udp
00:09:35.656 T:6180   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
00:09:35.656 T:6180   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
00:09:35.656 T:6180   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
00:09:35.656 T:6180   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: streams
00:09:35.657 T:6180   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: streams
00:09:35.657 T:6180   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: aacp/sdp
00:09:35.657 T:6180   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mp2
00:09:35.657 T:6180   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvd
00:09:35.657 T:6180   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvdimage
00:09:35.657 T:6180   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
00:09:35.657 T:6180   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: nsv
00:09:35.657 T:6180   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: radio
00:09:35.657 T:6180   DEBUG: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
00:09:35.657 T:6180   DEBUG: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (VideoPlayer)
00:09:35.657 T:6180   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=0
00:09:35.657 T:6180   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
00:09:35.657 T:6180   DEBUG: CPlayerCoreFactory::GetPlayers: added 1 players
00:09:35.657 T:7108   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
00:09:35.657 T:7108   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
00:09:35.659 T:6180   DEBUG: Radio UECP (RDS) Processor - new CDVDRadioRDSData::CDVDRadioRDSData
00:09:35.659 T:6180  NOTICE: VideoPlayer::OpenFile: C:\Users\username\Desktop\test-http-local.strm
00:09:35.659 T:6180   ERROR: CCurlFile::Stat - Failed: URL using bad/illegal format or missing URL(3) for C:\Users\username\Desktop\test-http-local.strm
00:09:35.659 T:6180   DEBUG: CCurlFile::GetMimeType - C:\Users\username\Desktop\test-http-local.strm -> failed
00:09:35.659 T:6180   DEBUG: CApplication::OnPlayBackStarted: CApplication::OnPlayBackStarted
00:09:35.659 T:12048   DEBUG: Thread VideoPlayer start, auto delete: false
00:09:35.659 T:5636   DEBUG: Thread BackgroundLoader start, auto delete: false
00:09:35.659 T:12048  NOTICE: Creating InputStream
00:09:35.659 T:12048   DEBUG: CurlFile::Open(0x42ae5fe990) http://127.0.0.1:12345/test.avi
00:09:35.659 T:12048    INFO: XCURL::DllLibCurlGlobal::easy_acquire - Created session to http://127.0.0.1
00:09:35.661 T:11964   DEBUG: Loading settings for C:\Users\username\Desktop\test-http-local.strm
00:09:35.665 T:5636   DEBUG: Thread BackgroundLoader 5636 terminating
00:09:35.673 T:6180   DEBUG: CVideoGUIInfo::InitCurrentItem(C:\Users\username\Desktop\test-http-local.strm)
00:09:35.679 T:6180   DEBUG: CPlayerGUIInfo::InitCurrentItem(C:\Users\username\Desktop\test-http-local.strm)
00:09:35.680 T:7108   DEBUG: CAnnouncementManager - Announcement: OnChanged from xbmc
00:09:35.680 T:7108   DEBUG: GOT ANNOUNCEMENT, type: 1024, from xbmc, message OnChanged
00:09:35.682 T:7108   DEBUG: CAnnouncementManager - Announcement: OnPlay from xbmc
00:09:35.682 T:7108   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnPlay
00:09:35.780 T:6180   DEBUG: ------ Window Init (DialogBusy.xml) ------
00:09:35.884 T:12048   DEBUG: CFileCache::Open - opening <test.avi> using cache
00:09:35.884 T:12048   DEBUG: CurlFile::Open(0x217c5091140) http://127.0.0.1:12345/test.avi
00:09:36.378 T:12048  NOTICE: Creating Demuxer
00:09:36.378 T:5376   DEBUG: Thread FileCache start, auto delete: false
00:09:36.581 T:12048   DEBUG: CDVDDemuxFFmpeg::Open - probing detected format [mpegvideo]
00:09:36.581 T:12048   DEBUG: CDVDDemuxFFmpeg::Open - avformat_find_stream_info starting
00:09:38.459 T:12048   DEBUG: CDVDDemuxFFmpeg::Open - av_find_stream_info finished
00:09:38.459 T:12048    INFO: ffmpeg[2F10]: Input #0, mpegvideo, from 'http://127.0.0.1:12345/test.avi':
00:09:38.459 T:12048    INFO: ffmpeg[2F10]:   Duration: N/A, bitrate: N/A
00:09:38.460 T:12048    INFO: ffmpeg[2F10]:     Stream #0:0: Video: mpeg2video (Main), yuv420p(tv, bt709, progressive), 720x300 [SAR 1:1 DAR 12:5], 25 fps, 25 tbr, 1200k tbn, 50 tbc
00:09:38.460 T:12048   DEBUG: CDVDDemuxFFmpeg::AddStream ID: 0
00:09:38.460 T:12048  NOTICE: Opening stream: 0 source: 256
00:09:38.460 T:12048  NOTICE: Creating video codec with codec id: 2
00:09:38.460 T:12048  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: MPEG-2 video
00:09:38.460 T:12048   DEBUG: CDVDVideoCodecFFmpeg - Updated codec: ff-mpeg2video
00:09:38.460 T:12048   DEBUG: CVideoPlayerVideo::OpenStream - open stream with codec id: 2
00:09:38.460 T:12048  NOTICE: Creating video thread
00:09:38.460 T:12048   DEBUG: CVideoPlayer::SetCaching - caching state 2
00:09:38.460 T:12048   DEBUG: CDVDClock::SetSpeedAdjust - adjusted:0.000000
00:09:38.460 T:12048   DEBUG: CVideoPlayer::SetCaching - caching state 1
00:09:38.460 T:12048   DEBUG: CDVDClock::SetSpeedAdjust - adjusted:0.000000
00:09:38.460 T:3688   DEBUG: Thread VideoPlayerVideo start, auto delete: false
00:09:38.460 T:3688  NOTICE: running thread: video_thread
00:09:38.460 T:3688    INFO: CVideoPlayerVideo - Stillframe left, switching to normal playback
00:09:38.460 T:12048   DEBUG: CVideoPlayer::HandleMessages - player 2 reported state: 0
00:09:38.461 T:3688   DEBUG: DXVA: open decoder.
```
Without loopback and wifi

- PVR doesn't run
```
00:10:08.878 T:11364 WARNING: XFILE::CFileFactory::CreateLoader - Network down or unsupported protocol(pvr) in pvr://channels/tv/All channels/pvr.dvbviewer_53.tbn
```
- video test.avi doesn't run
```
00:09:56.378 T:6180   ERROR: CCurlFile::Stat - Failed: URL using bad/illegal format or missing URL(3) for C:\Users\username\Desktop\test-http-local.strm
00:09:56.378 T:6180   DEBUG: CCurlFile::GetMimeType - C:\Users\username\Desktop\test-http-local.strm -> failed
00:09:56.378 T:6180   DEBUG: CApplication::OnPlayBackStarted: CApplication::OnPlayBackStarted
00:09:56.379 T:12004   DEBUG: Thread VideoPlayer start, auto delete: false
00:09:56.379 T:12004  NOTICE: Creating InputStream
00:09:56.379 T:5636   DEBUG: Thread BackgroundLoader start, auto delete: false
00:09:56.379 T:12004   DEBUG: CurlFile::Open(0x42ae5fe900) http://127.0.0.1:12345/test.avi
00:09:56.380 T:6180   DEBUG: CVideoGUIInfo::InitCurrentItem(C:\Users\username\Desktop\test-http-local.strm)
00:09:56.383 T:11964   DEBUG: Loading settings for C:\Users\username\Desktop\test-http-local.strm
00:09:56.384 T:7108   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
00:09:56.384 T:7108   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
00:09:56.384 T:5636   DEBUG: Thread BackgroundLoader 5636 terminating
00:09:56.388 T:6180   DEBUG: CPlayerGUIInfo::InitCurrentItem(C:\Users\username\Desktop\test-http-local.strm)
00:09:56.388 T:7108   DEBUG: CAnnouncementManager - Announcement: OnChanged from xbmc
00:09:56.388 T:7108   DEBUG: GOT ANNOUNCEMENT, type: 1024, from xbmc, message OnChanged
00:09:56.391 T:7108   DEBUG: CAnnouncementManager - Announcement: OnPlay from xbmc
00:09:56.391 T:7108   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnPlay
00:09:56.488 T:6180   DEBUG: ------ Window Init (DialogBusy.xml) ------
00:09:56.542 T:12004   DEBUG: CFileCache::Open - opening <test.avi> using cache
00:09:56.547 T:12004 WARNING: XFILE::CFileFactory::CreateLoader - Network down or unsupported protocol(http) in http://127.0.0.1:12345/test.avi
00:09:56.547 T:12004   ERROR: XFILE::CFileCache::Open - failed to open source <http://127.0.0.1:12345/test.avi>
00:09:56.547 T:12004   ERROR: CVideoPlayer::OpenInputStream - error opening [C:\Users\username\Desktop\test-http-local.strm]
00:09:56.547 T:12004  NOTICE: CVideoPlayer::OnExit()
00:09:56.547 T:12004   DEBUG: Thread VideoPlayer 12004 terminating
```

**Comment by FernetMenta** [comment]
Looks like a general networking issue of Kodi on Windows. I recommend to open a new issue and reference this one here.

**Comment by popy2k14** [comment]
Just for reference, this issues are related to this one.
I have raised one because when this happened (kodi thinks its offline) it crashes, this was the first issue:

https://github.com/xbmc/xbmc/issues/14606

Then @Rechi fixed the crash with:

https://github.com/xbmc/xbmc/pull/14614

but it seems this was a workaround and the root cause is not yet fixed.
It's nice that @d3m10n can reproduce the issue faster than me.

@d3m10n: will you open a new issue or should i?

**Comment by d3m10n** [comment]
@popy2k14 feel free to open it. Thanks

**Comment by Rechi** [comment]
#14614 isn't a workaround, a network interface doesn't necessary have an IP address.
It seems like you hit a different bug now.

**Comment by popy2k14** [comment]
Sorry for getting this wrong, i have strikethrough my false text.
