### ISSUE TITLE
"Adjust display refresh rate" doesn't work in GBM Video Backend

### ISSUE THREAD

**Issue by AreaScout** [xbmc/xbmc#14671]
### Describe the bug
Enabling the '**Adjust display refresh rate**' feature under Settings->Videos->Playback doesn't seem to work anymore @lrusak @Kwiboo 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Display refresh rate should set to the video fps rate which highly improves the video quality

## Actual Behavior

It does nothing, display just stays at 60fps and does not adjust to the movie

## Possible Fix

Kodi Alpha1 20180305 was working, I didn't tracked down the problem to a certain commit :(

### Debuglog

The debuglog can be found here:
https://pastebin.com/cDVNLmef

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian GNU/Linux 9 (stretch) on RK3399
 - Kodi version: 17.99.804

**Comment by lrusak** [comment]
two things to check:

1) is your user a part of the `video` group?
2) have you whitelisted the modes that you actually want it to switch to? `settings -> system-> display -> whitelist`

**Comment by AreaScout** [comment]
Haha ! thank you Lukas :) The whitelist did the trick, I completely forgot about this, so my very old version back from march stores that whitelist in an different place as now ? did that change ? I remember I have set that whitelist once back then.

It seems to work very well now :)

I have another question, that new VTUtil class, what is that for  ? I had to remove the call to it because it was failing with ``CVTUtils::OpenTTY() - /dev/pts/0 is not a vt``

**Comment by lrusak** [comment]
>I have another question, that new VTUtil class, what is that for ? I had to remove the call to it because it was failing with CVTUtils::OpenTTY() - /dev/pts/0 is not a vt

@AreaScout this is something I am investigating and am not sure exactly yet the best way to fix it.

I assume you are either trying to start kodi from an ssh session or from an x11/wayland terminal, the latter of which is not aloud.

The code that was added in `CVTUtils` is very similar to what is in weston. So if you can run weston you should be able to run Kodi. I also don't want to require sudo rights when running kodi otherwise I would implement auto VT switching. I'm still looking to see if there is a way around that.

**Comment by AreaScout** [comment]
> I almost forgot. I will also look into using systemd-logind to do this VT stuff for us. The problem there is that our DBUS implentation is very limited and may not be able to do everything we need with logind

Ok it's used for intercommunication and yes I was starting it over ssh 😆 It's a little bit annoying if this is not working but usually you don't start _kodi_ from there 😊

Thanks again, I will follow your progress and get in touch with you if I can help

**Comment by lrusak** [comment]
@AreaScout Please test out this patch to see if you can start kodi from an SSH session
https://github.com/lrusak/xbmc/commit/tty-setup

Be aware that the remote session will have to be a logged in console as we don't do any authentication.
Also make sure that the VT is switched to with something like `sudo chvt 3`

Then you should be able to start Kodi when specifying a tty

Example from my ssh console is below (I know that tty3 is logged in on my machine at home)
```shell
lukas@nuc8i7hnk ~/Documents/git/xbmc/build$ kodi -fs --standalone
ERROR: /dev/pts/4 is not a vt
ERROR: Unable to create GUI. Exiting

lukas@nuc8i7hnk ~/Documents/git/xbmc/build$ kodi -fs --standalone --tty=/dev/tty3
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
^CExiting application
```

**Comment by AreaScout** [comment]
Yes that seems to work, although I had to choose _tty1_ because it was the only one without root ownership, that was fast ! :)  

`` odroid@odroid:~$ ps aux | grep tty``
``root       693  0.0  0.0   7364  3172 ttyFIQ0  Ss   20:01   0:00 /bin/login -f``
``root       694  0.0  0.0   5616  2792 tty1     Ss   20:01   0:00 /bin/login --``
``root       723  0.0  0.1   6700  4436 ttyFIQ0  S+   20:01   0:00 -bash``
``odroid     754  0.0  0.1   6936  4892 tty1     S+   20:02   0:01 -bash``
``odroid    1574  0.0  0.1  11872  4448 ?        S    20:56   0:00 sshd: odroid@notty``
``odroid    8245  0.0  0.0   1864  1108 pts/0    S+   22:01   0:00 /bin/sh /usr/local/bin/kodi -fs --standalone --tty=/dev/tty1``
``odroid    8253 34.5  3.0 2221772 123184 pts/0  Rl+  22:01   0:09 /usr/local/lib/kodi/kodi.bin -fs --standalone --tty=/dev/tty1``
``odroid    8293  0.0  0.0   4384   548 pts/1    S+   22:01   0:00 grep tty``

![2018-10-22](https://user-images.githubusercontent.com/1681560/47316368-3e3ce380-d647-11e8-8db6-950157f4c6cc.png)
