### ISSUE TITLE
UWP Crash report: null_class_ptr_read_c0000005_kodi.exe!cfileitemlist::copy

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/xbmc#14684]
### Describe the bug
Here is a clear and concise description of what the problem is:

This is a crash report gemnerated by Windows Store for the UWP version. It might be a more platform agnostic problem though.

### To Reproduce

1. Does not contain steps to repro
2.
3.

### Debuglog

The debuglog can be found here:
**null_class_ptr_read_c0000005_kodi.exe!cfileitemlist::copy** 
> 

Frame | Image | Function | Offset
-- | -- | -- | --
0 | kodi.exe | CGUIListItem::operator= | 0x000000000000003C
1 | kodi.exe | CFileItem::operator= | 0x000000000000003A
2 | kodi.exe | CFileItem::CFileItem | 0x00000000000001A5
3 | kodi.exe | CFileItemList::Copy | 0x0000000000000145
4 | kodi.exe | XFILE::CDirectoryCache::SetDirectory | 0x0000000000000232
5 | kodi.exe | XFILE::CDirectory::GetDirectory | 0x0000000000000B46
6 | kodi.exe | XFILE::CDirectory::GetDirectory | 0x00000000000000D5
7 | kodi.exe | XFILE::CVirtualDirectory::GetDirectory | 0x000000000000017E
8 | kodi.exe | `anonymous namespace'::CGetDirectoryItems::Run | 0x000000000000002A
9 | kodi.exe | CLambdaJob__lambda_3c8b9a4137f6399524cdc3383ea28e02_ _::DoWork | 0x0000000000000012
10 | kodi.exe | CJobWorker::Process | 0x000000000000005A
11 | kodi.exe | CThread::Action | 0x0000000000000033
12 | kodi.exe | CThread::staticThread | 0x000000000000010E
13 | ucrtbase.dll | thread_start_unsigned int (__cdecl*) | 0x000000000000003A
14 | ntdll.dll | RtlUserThreadStart | 0x000000000000002F

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name: 
 - Kodi version: V18 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
closing as stalled, no idea if it still happens on v20.
