### ISSUE TITLE
UWP Crash report: INVALID_POINTER_READ_c0000005_kodi.exe!XFILE::CPluginDirectory::SetResolvedUrl 

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/xbmc#14682]
### Describe the bug
Here is a clear and concise description of what the problem is:

This is a crash report gemnerated by Windows Store for the UWP version. It might be a more platform agnostic problem though.

### To Reproduce

1. Does not contain steps to repro
2.
3.

### Debuglog

The debuglog can be found here:
**INVALID_POINTER_READ_c0000005_kodi.exe!XFILE::CPluginDirectory::SetResolvedUrl** 
> Stack trace
Frame   Image   Function    Offset
0   kodi.exe    std::basic_string_char,std::char_traits_char_,std::allocator_char_ _::assign    0x0000000000000036
1   kodi.exe    CGUIListItem::operator= 0x000000000000004F
2   kodi.exe    CFileItem::operator=    0x000000000000003A
3   kodi.exe    XFILE::CPluginDirectory::SetResolvedUrl 0x0000000000000072
4   kodi.exe    XBMCAddon::xbmcplugin::setResolvedUrl   0x0000000000000054
5   kodi.exe    PythonBindings::xbmcplugin_setResolvedUrl   0x00000000000000FA
6   python27.dll    PyCFunction_Call    0x0000000000000076
7   python27.dll    Py_CheckRecursiveCall   0x0000000000000E2A
8   python27.dll    Py_CheckRecursiveCall   0x0000000000000954
9   python27.dll    PyEval_EvalFrameEx  0x0000000000002842
10  python27.dll    Py_CheckRecursiveCall   0x0000000000001908
11  python27.dll    Py_CheckRecursiveCall   0x0000000000000947
12  python27.dll    PyEval_EvalFrameEx  0x0000000000002842
13  python27.dll    Py_CheckRecursiveCall   0x0000000000001908
14  python27.dll    Py_CheckRecursiveCall   0x0000000000000947
15  python27.dll    PyEval_EvalFrameEx  0x0000000000002842
16  python27.dll    PyEval_EvalCodeEx   0x00000000000007F5
17  python27.dll    PyFrame_Init    0x0000000000000ACC
18  python27.dll    PyObject_Call   0x000000000000005D
19  python27.dll    PyCell_Set  0x00000000000035FF
20  python27.dll    PyObject_Call   0x000000000000005D
21  python27.dll    PyEval_CallObjectWithKeywords   0x00000000000000CC
22  python27.dll    PyInstance_New  0x0000000000000123
23  python27.dll    PyObject_Call   0x000000000000005D
24  python27.dll    Py_CheckRecursiveCall   0x0000000000000E3A
25  python27.dll    Py_CheckRecursiveCall   0x0000000000000954
26  python27.dll    PyEval_EvalFrameEx  0x0000000000002842
27  python27.dll    PyEval_EvalCodeEx   0x00000000000007F5
28  python27.dll    PyEval_EvalCode 0x0000000000000029
29  python27.dll    Py_SymtableString   0x0000000000000CBA
30  python27.dll    PyRun_FileExFlags   0x00000000000000AA
31  kodi.exe    CPythonInvoker::executeScript   0x0000000000000057
32  kodi.exe    CPythonInvoker::execute 0x00000000000010B2
33  kodi.exe    CLanguageInvokerThread::Process 0x0000000000000074
34  kodi.exe    CThread::Action 0x0000000000000033
35  kodi.exe    CThread::staticThread   0x000000000000010E
36  ucrtbase.dll    thread_start_unsigned int (__cdecl*)    0x000000000000003A
37  ntdll.dll   RtlUserThreadStart  0x000000000000002F

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 
 - Kodi version: V18 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Closing as matrix will include python3. Nobody is interested in python2.7 internal crashes anymore
