### ISSUE TITLE
UWP Crash report: moapplication_hang_cfffffff_xbmcfoundation.kodi!hang_navigation

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/xbmc#14681]
### Describe the bug
Here is a clear and concise description of what the problem is:

This is a crash report gemnerated by Windows Store for the UWP version. It might be a more platform agnostic problem though.

### To Reproduce

1. Does not contain steps to repro
2.
3.

### Debuglog

The debuglog can be found here:
**moapplication_hang_cfffffff_xbmcfoundation.kodi!hang_navigation**
> Stack trace
Frame   Image   Function    Offset
0   XBMCFoundation.Kodi HANG_NAVIGATION 0x0000000000000000
1   unknown.dll [.ecxr] 0x0000000000000000
2   sqlite3.dll sqlite3_column_name16   0x0000000000000000
3   sqlite3.dll sqlite3_column_name16   0x0000000000000000
4   sqlite3.dll sqlite3_column_name16   0x0000000000000000
5   sqlite3.dll sqlite3_win32_write_debug   0x0000000000000000
6   sqlite3.dll sqlite3_column_name16   0x0000000000000000
7   sqlite3.dll sqlite3_column_name16   0x0000000000000000
8   sqlite3.dll sqlite3_column_name16   0x0000000000000000
9   sqlite3.dll sqlite3_column_name16   0x0000000000000000
10  sqlite3.dll sqlite3_column_name16   0x0000000000000000
11  sqlite3.dll sqlite3_win32_write_debug   0x0000000000000000
12  sqlite3.dll sqlite3_win32_write_debug   0x0000000000000000
13  sqlite3.dll sqlite3_win32_write_debug   0x0000000000000000
14  sqlite3.dll sqlite3_win32_write_debug   0x0000000000000000
15  sqlite3.dll sqlite3_win32_write_debug   0x0000000000000000
16  sqlite3.dll sqlite3_column_name16   0x0000000000000000
17  sqlite3.dll sqlite3_column_name16   0x0000000000000000
18  sqlite3.dll sqlite3_column_name16   0x0000000000000000
19  sqlite3.dll sqlite3_column_name16   0x0000000000000000
20  sqlite3.dll sqlite3_column_name16   0x0000000000000000
21  sqlite3.dll sqlite3_column_name16   0x0000000000000000
22  sqlite3.dll sqlite3_win32_write_debug   0x0000000000000000
23  sqlite3.dll sqlite3_column_name16   0x0000000000000000
24  sqlite3.dll sqlite3_column_name16   0x0000000000000000
25  sqlite3.dll sqlite3_column_name16   0x0000000000000000
26  sqlite3.dll sqlite3_column_name16   0x0000000000000000
27  sqlite3.dll sqlite3_prepare_v2  0x0000000000000000
28  kodi.exe    dbiplus::SqliteDataset::query   0x0000000000000000
29  kodi.exe    CAddonDatabase::FindByAddonId   0x0000000000000000
30  kodi.exe    ADDON::CAddonMgr::FindInstallableById   0x0000000000000000
31  kodi.exe    ADDON::CAddonMgr::GetDepsRecursive  0x0000000000000000
32  kodi.exe    CGUIDialogAddonInfo::UpdateControls 0x0000000000000000
33  kodi.exe    CGUIDialogAddonInfo::OnInitWindow   0x0000000000000000
34  kodi.exe    CGUIWindow::OnMessage   0x0000000000000000
35  kodi.exe    CGUIDialog::OnMessage   0x0000000000000000
36  kodi.exe    CGUIDialogAddonInfo::OnMessage  0x0000000000000000
37  kodi.exe    CGUIDialog::Open_Internal   0x0000000000000000
38  kodi.exe    CGUIDialog::Open    0x0000000000000000
39  kodi.exe    CGUIDialogAddonInfo::ShowForItem    0x0000000000000000
40  kodi.exe    CGUIWindowAddonBrowser::OnClick 0x0000000000000000
41  kodi.exe    CGUIMediaWindow::OnSelect   0x0000000000000000
42  kodi.exe    CGUIMediaWindow::OnMessage  0x0000000000000000
43  kodi.exe    CGUIWindowAddonBrowser::OnMessage   0x0000000000000000
44  kodi.exe    CGUIBaseContainer::OnClick  0x0000000000000000
45  kodi.exe    CGUIBaseContainer::OnAction 0x0000000000000000
46  kodi.exe    CGUIWindow::OnAction    0x0000000000000000
47  kodi.exe    CGUIMediaWindow::OnAction   0x0000000000000000
48  kodi.exe    CGUIWindowManager::HandleAction 0x0000000000000000
49  kodi.exe    CGUIWindowManager::OnAction 0x0000000000000000
50  kodi.exe    CApplication::OnAction  0x0000000000000000
51  kodi.exe    CInputManager::HandleKey    0x0000000000000000
52  kodi.exe    CInputManager::OnKey    0x0000000000000000
53  kodi.exe    CInputManager::OnEvent  0x0000000000000000
54  kodi.exe    CApplication::HandlePortEvents  0x0000000000000000
55  kodi.exe    CApplication::FrameMove 0x0000000000000000
56  kodi.exe    CXBApplicationEx::Run   0x0000000000000000
57  kodi.exe    KODI::PLATFORM::WINDOWS10::App::Run 0x0000000000000000
58  kodi.exe    winrt::impl::produce_KODI::PLATFORM::WINDOWS10::App,winrt::Windows::ApplicationModel::Core::IFrameworkView_::Run    0x0000000000000000
59  twinapi.appcore.dll Windows::ApplicationModel::Core::CoreApplicationView::Run   0x0000000000000000
60  twinapi.appcore.dll _lambda_02cef69f8ae13d771fa47a74be974b8f_::operator 0x0000000000000000
61  SHCore.dll  _WrapperThreadProc  0x0000000000000000
62  ntdll.dll   RtlUserThreadStart  0x0000000000000000

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name: 
 - Kodi version: V18 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
closing as stalled, no idea if it still happens on v20.
