### ISSUE TITLE
BETA4 Git:20181022-fe875cf segfaults when trying to start on secondary monitor

### ISSUE THREAD

**Issue by the-black-eagle** [xbmc/xbmc#14694]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi 18.0-BETA4 Git:20181022-fe875cf segfaults at startup when guisettings.xml setting 'videoscreen.monitor' is **not** set to the default monitor. This is repeatable multiple times.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expected Kodi to start normally on my secondary monitor (actually a TV).

## Actual Behavior

Kodi starts but almost immediately crashes with a segmentation fault. No visual rendering was apparent.

### To Reproduce
1. Install 18.0-BETA4 Git:20181022-fe875cf and remove/rename guisettings.xml
2. Start Kodi normally and move it to secondary monitor. (Settings -> system ->display -> monitor)
3. Quit Kodi and restart it.  It will attempt to start on the secondary monitor and then segfault

### Debuglog
Log starting normally on default monitor - https://paste.kodi.tv/midisiqeta.kodi
Log crashing on secondary monitor - https://paste.kodi.tv/wulukuwipu.kodi
gdb backtrace - https://paste.kodi.tv/ubiviwazeh

### Screenshots 
N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Upgraded to a nightly as some changes I was interested in had been pulled into master.  Rolling back to the last BETA3 version in the unstable ppa fixes the issue (ie Kodi starts correctly on the secondary monitor).  No alterations were made to either the gfx drivers or to Xorg.conf in between testing the two versions.
I can start Kodi BETA4 normally on my default monitor and then move it to the secondary and that works OK, but I cannot start it on the secondary monitor at all.  Starting Kodi on the secondary monitor  from a terminal results in the following text

```
libEGL warning: DRI2: failed to authenticate
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
Segmentation fault

```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:  Ubuntu 16.04.5 LTS, kernel: Linux x86 64-bit version 4.15.0-33-generic
 - Kodi version:  18.0-BETA4 Git:20181022-fe875cf). Platform: Linux x86 64-bit

**Comment by fritsch** [comment]
Please remove:

libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so

the vdpau-va-driver - it is not supported by kodi

**Comment by the-black-eagle** [comment]
Only reference to that I could find was an old 32 bit driver related to an old wine installation.  Anyway, I removed it and the other bits 
`sudo apt-get remove vdpau-va-driver:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libvdpau1:i386 mesa-vdpau-drivers:i386 vdpau-driver-all:i386
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED
  va-driver-all:i386 vdpau-va-driver:i386`

Quit Kodi and restarted it from a terminal again.  Result (on secondary monitor) was

`libEGL warning: DRI2: failed to authenticate
libEGL warning: DRI2: failed to authenticate
Segmentation fault
`
 Again, changing 'videoscreen.monitor' in guisettings.xml from DVI-I-3 to DVI-I-2 allows Kodi to start on my desktop from where I can move it back to DVI-I-3. 

The libEGL warning I have always had I think and it doesn't appear related to the issue in any case.

**Comment by the-black-eagle** [comment]
I did a bisect on this (hopefully I did it right as it's the first time!) and got this as the result.

commit cad68b2df80d67e55f6cacd9428de581f2523b6f
Author: Rainer Hochecker <fernetmenta@online.de>
Date:   Mon Oct 15 09:58:43 2018 +0200

    X11: EGL - create PB if creation of surface for window fails

:040000 040000 ccdf5d4bdd57927457d0c45bf9c2d499d39feb68 0ab1fc70c7d0c7c5b40153603da794503d5c28df M	xbmc

@FernetMenta - this appears to be the cause of the segfault when starting up on the secondary monitor.  I have a log  of the bisect session should it be required.

**Comment by FernetMenta** [comment]
I know. For intermediate solution you can set environment variable KODI_GL_INTERFACE to GLX

**Comment by the-black-eagle** [comment]
Thanks !  I've added the export to the startup script for now.

**Comment by FernetMenta** [comment]
@the-black-eagle https://github.com/xbmc/xbmc/commit/df59f9c2e2b7591c1fb8bb96ff78e120c2462492#diff-f27d76f37e110f14d6b543cd6c98dcc3 might have fixed this issue too. Could you verify this?

**Comment by the-black-eagle** [comment]
@FernetMenta  - Sadly not.  Tested with 2:18.0+git20181113.0201-b3a7d3c-0xenial. Immediately segfaults as before if the environment variable above is not set.

**Comment by FernetMenta** [comment]
@the-black-eagle could you post a new back trace. the one posted above does not show running kodi at all.

**Comment by the-black-eagle** [comment]
Sure.  Debug log from Kodi - https://hastebin.com/vaharaqemu.makefile
Backtrace - https://hastebin.com/gasozogapu.shell

**Comment by FernetMenta** [comment]
fixed by https://github.com/xbmc/xbmc/pull/14900

**Comment by pkerling** [comment]
@the-black-eagle Is your problem solved now?

**Comment by the-black-eagle** [comment]
Going by the nightly from 20-12-18, yes it is.  Issue can therefore be closed now.  Thanks to all those that contributed to both a work-around and a proper fix.
