### ISSUE TITLE
Kodi 18 Resolution/refresh rate Whitelist is only showing 1920x1080/60hz 

### ISSUE THREAD

**Issue by dgindin-cp** [xbmc/xbmc#14696]
### Describe the bug
Here is a clear and concise description of what the problem is:

Refresh rate change does not work in Kodi 18 as whitelist only includes one resolution/refresh rate: 1920x1080/60hz. However, my TV supports all common resolutions. 

Kodi 17 works fine and automatically changes screen to 1920x1080/24hz for movies.  I am running Kodi on an Amazon Fire TV 2.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Whitelist allows you to enable/disable all of your TV’s supported resolutions.

## Actual Behavior

Whitelist only includes one resolution/refresh rate: 1920x1080/60hz. However, my TV supports many other combinations. 

### To Reproduce

1. Install latest Kodi 18 beta 3
2. Go to whitelist settings for screen resolution and refresh rate
3. Try to enable 1920x1080/24hz

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18 beta 3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jjd-uk** [comment]
Although you TV may support various resolutions at different refresh rates are you sure the Amazon Fire TV 2 as Amazon devices are normally bad at supporting this type of stuff. Please provide a debug log which will show what that Amazon Fire TV 2 reports it can do.

**Comment by MartijnKaijser** [comment]
I blame the firestick or the cable. Nothing we can lickely do about. A debug log will show.

**Comment by HeresJonny** [comment]
Maybe you turned on your box before your AVR/TV. Reboot the box while both AVR and TV are on and check if more resolutions are deected by Kodi. Also, try another HDMI cable.

**Comment by pkerling** [comment]
No debuglog provided despite a specific request. Closing as invalid.

**Comment by tcmbackwards** [comment]
I'm having the same issue, the display window doesn't match the actual window size

https://paste.kodi.tv/usegimakas
