### ISSUE TITLE
Python problem with os file.seek()

### ISSUE THREAD

**Issue by sraedler** [xbmc/xbmc#14690]
### Describe the bug
Here is a clear and concise description of what the problem is:

I implemented a small test to use a pure python git implementation. The Git implementation ist provided by [dulwich](dulwich.io).

By now the module only clone or checkout an static random git repository from github into a folder called test (inside the module folder)

With Windows 10 x64 everything works fine from my point of view. But on Android it causes problems.
I triple checked it with nox emulator, fire tv stick and a native android.

On Kodi 17.6 it works like it should. On Kodi 18 (latest nightly from today 23th october) it does not work at all. 

The test-plugin is attached.

[script.module.dulwich.zip](https://github.com/xbmc/xbmc/files/2506914/script.module.dulwich.zip)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Usually the plugin should run without any output. If you look into the plugin folder (addons/script.module.dulwich), there should be a folder called test including a .git folder and two small other files, which are included in the repository.

## Actual Behavior

On Kodi 18 an error occures.
Error: IOError: [Errno 22] Invalid argument

The lib with the error calls os.

## Possible Fix

No idea. Maybe os package is crashed ?!?

### To Reproduce

1. Install latest Kodi 18 nightly
2. Install [script.module.dulwich.zip](https://github.com/xbmc/xbmc/files/2506914/script.module.dulwich.zip)
3. Run Dulwich (it is inside addons->program)
4. See error in log file

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 5.1.1 and Fire Tv Stick
 - Kodi version: Kodi 18 nightly (23 october)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MartijnKaijser** [comment]
As reference this trac ticket:
https://trac.kodi.tv/ticket/17827

**Comment by zach-morris** [comment]
Just a note on this issue.  The trac ticket says:

> Investigation leads to the result that fseeko with OFF_T=64 is broken in android NDK. You can use io.FileIO() instead open()

Which works for opening files, but I believe this issue also effects Kodi's builtins like xbmcvfs.Stat, xbmc.Extract, etc.  See [here](https://forum.kodi.tv/showthread.php?tid=330124)

**Comment by enen92** [comment]
Android has no maintainer, v18 is not receiving changes anymore. Please comment if this still applies to v20.

**Comment by zach-morris** [comment]
No longer applies with the python version shipped with Kodi v19 or v20, so i agree it should be closed.
