### ISSUE TITLE
Error KODI Player Failed: URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by xperiafan13-rom** [xbmc/xbmc#14695]
Hi, I'm trying to play a video from a server, for example, openload, rapidvideo or streamango, I designed my own url to resolve from Selenium that throws me the direct link of playback, but when playing it records an error:

KODI ERROR LOG:
10:11:18.651 T:140044407611840   ERROR: CCurlFile::Stat - Failed: URL using bad/illegal format or missing URL(3) for https://www3615.playercdn.net/187/3/JCJMB2zR4NgbXm9G494Fuw/1540415472/170819/523FIP9HAWHRN3KOIOX6U.mp4
10:11:18.654 T:140044407611840  NOTICE: VideoPlayer: Opening: https://www3615.playercdn.net/187/3/JCJMB2zR4NgbXm9G494Fuw/1540415472/170819/523FIP9HAWHRN3KOIOX6U.mp4
10:11:18.654 T:140044407611840 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
10:11:18.654 T:140044407611840   ERROR: CCurlFile::Stat - Failed: URL using bad/illegal format or missing URL(3) for https://www3615.playercdn.net/187/3/JCJMB2zR4NgbXm9G494Fuw/1540415472/170819/523FIP9HAWHRN3KOIOX6U.mp4
10:11:18.674 T:140041665853184  NOTICE: Creating InputStream
10:11:18.674 T:140041665853184   ERROR: CCurlFile::FillBuffer - Failed: URL using bad/illegal format or missing URL(3)
10:11:18.674 T:140041665853184   ERROR: CCurlFile::Open failed with code 0 for https://www3615.playercdn.net/187/3/JCJMB2zR4NgbXm9G494Fuw/1540415472/170819/523FIP9HAWHRN3KOIOX6U.mp4
10:11:18.674 T:140041665853184   ERROR: CCurlFile::FillBuffer - Failed: URL using bad/illegal format or missing URL(3)
10:11:18.674 T:140041665853184   ERROR: CCurlFile::Open failed with code 0 for https://www3615.playercdn.net/187/3/JCJMB2zR4NgbXm9G494Fuw/1540415472/170819/523FIP9HAWHRN3KOIOX6U.mp4
10:11:18.674 T:140041665853184   ERROR: Open - failed to open source <https://www3615.playercdn.net/187/3/JCJMB2zR4NgbXm9G494Fuw/1540415472/170819/523FIP9HAWHRN3KOIOX6U.mp4
                                            >
10:11:18.674 T:140041665853184   ERROR: CVideoPlayer::OpenInputStream - error opening [https://www3615.playercdn.net/187/3/JCJMB2zR4NgbXm9G494Fuw/1540415472/170819/523FIP9HAWHRN3KOIOX6U.mp4
                                            ]
10:11:18.674 T:140041665853184  NOTICE: CVideoPlayer::OnExit()

The code I use to play the video is as follows:

try:
            command = "python .kodi/userdata/url/openload.py '%s'" % utils.get_format(
                server, key)
            resolved = subprocess.check_output(command, shell=True) # direct url from video
            li = ListItem(title, iconImage=ART + 'popular.jpg', thumbnailImage=ART + 'popular.jpg')
            li.setProperty('IsPlayable', 'true')
            dialog.ok('URL TO PLAY',resolved)
            xbmc.Player().play(resolved, li)
        except:
            dialog.ok('LInk Error', 'Sorry, we cant play')

When I open url in broswer all is ok:

Sample url: https://www3615.playercdn.net/187/3/JCJMB2zR4NgbXm9G494Fuw/1540415472/170819/523FIP9HAWHRN3KOIOX6U.mp4

Every link is generated at the moment that user select video to play

**Comment by enen92** [comment]
This is not a support forum nor the place to ask for support regarding plugin development. The only issues considered valid here are the ones that affect Kodi core itself and there's an issue template to follow.
I tried to play your link from a .strm file and it plays without any problem in Kodi 18 so this is definitely a false positive. Team Kodi will not offer you any support developing piracy based plugins nor to circumvent such filelockers. You're basically on your own.

Closing and removing all url entries according to our piracy policy (https://forum.kodi.tv/showthread.php?tid=119117)
