### ISSUE TITLE
Save default closed caption error

### ISSUE THREAD

**Issue by alandeman** [xbmc/xbmc#14699]
Kodi 18 beta 2 and 3 issue. If I try to select no closed captioning and save as default for closed captioning it does not work. Every time I have a new video on screen the closed captioning is automatically on I turn it off and select save as default and it does not work. every time another movie comes up closed captioning is enabled every time on Default. Keep up the great work thanks a lot for a great product!

**Comment by Razzeee** [comment]
Please use the supplied issue template.
