### ISSUE TITLE
BETA4 GBM segfaults when trying to start

### ISSUE THREAD

**Issue by bmaehr** [xbmc/xbmc#14703]
### Describe the bug
Here is a clear and concise description of what the problem is:
- Updated from previous beta version to Beta4 with apt upgrade
- Kodi crashes at start 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should start like before

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/lobojijani
https://paste.kodi.tv/axiracajez.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 Arch: x86_64
 Kernel: Linux 4.18.0-10-generic #11-Ubuntu SMP Thu Oct 11 15:13:55 UTC 2018
 Release: Ubuntu 18.10 (Cosmic Cuttlefish)

 - Kodi version:
Kodi (18.0-BETA4 Git:20181023-9d3a68a). Platform: Linux x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
@lrusak it's GBM

```
#0  0x00007f29edcae116 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f29ed68cce4 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000562b6a22aa37 in KODI::WINDOWING::GBM::CVTUtils::OpenTTY() ()
#3  0x0000562b6a239e3f in KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::InitWindowSystemEGL(int, int) ()
#4  0x0000562b6a253aa5 in KODI::WINDOWING::GBM::CWinSystemGbmGLContext::InitWindowSystem() ()
#5  0x0000562b6a6f470f in CApplication::CreateGUI() ()
#6  0x0000562b6a55eead in XBMC_Run ()
#7  0x0000562b6a089765 in main ()
```

**Comment by lrusak** [comment]
known issue, see #14689

**Comment by bmaehr** [comment]
> known issue, see #14689

I'm not sure what you are trying to tell me. The referenced MR is not merged, so it could not be the reason for the problem. Nevertheless I tried the both command lines (with tty and without tty) and neither worked. Additionally I'm not start kodi from a ssh session or systemd - I start it from kodi.desktop.

**Comment by lrusak** [comment]
> I'm not sure what you are trying to tell me. The referenced MR is not merged, so it could not be the reason for the problem. Nevertheless I tried the both command lines (with tty and without tty) and neither worked. Additionally I'm not start kodi from a ssh session or systemd - I start it from kodi.desktop.

It means I'm working on it :)

FYI: you cannot run kodi-gbm from an active x11 or wayland session, it needs it's own VT. If you are using a .desktop file you should be using kodi-x11 or kodi-wayland

**Comment by bmaehr** [comment]
It has been working with Beta3 and is failing since Beta4. That's why I' curious.

**Comment by lrusak** [comment]
> It has been working with Beta3 and is failing since Beta4. That's why I' curious.

Like I said it won't work like it did before. It was just luck before. You cannot run kodi-gbm from an active x11 or wayland session. It needs to be run in its own VT. 😸

**Comment by bmaehr** [comment]
With the new beta it is working again.

**Comment by MartijnKaijser** [comment]
fixed
