### ISSUE TITLE
Video calibration settings changes are lost after Kodi restart

### ISSUE THREAD

**Issue by nd299** [xbmc/xbmc#14700]
### Describe the bug
Here is a clear and concise description of what the problem is:

When GUI resolution is set to 1080p and refresh rate is set to 60Hz then any changes made to the Video calibration settings are lost after Kodi restart. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Changes made in video calibration settings should be saved and remain following Kodi restart. 

## Actual Behavior

After Kodi reatart, changes in the video calibration settings are lost:  i mean they return to their default settings of 
0,0 ; 0,0 ; and 1042 for subtitles position

This only applies when resolution = 1080p and refresh rate = 60Hz

## Possible Fix

Not sure, but it seems some code is resetting the video calibration to defaults upon restart, specifically for the 1080p / 60Hz

### To Reproduce

1. Start Kodi Leia beta 4
2. Go to system settings, display
3. Select resolution = 1080p and refresh rate = 60Hz
4. Go to video calibration and make any changes, e.g top-left overscan = -2,+3 and subtitles position=1020
5. Exit settings, exit kodi, restart kodi. 
6. Go back to video calibration: all changes have returned to default

### Debuglog

The debuglog can be found here:
Debuglog not applicable for this issue

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screenshot not needed, worded explanation is better

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

What i wanted was just to change the subtitle position for 1080p/60Hz but it keeps returning to default position. 

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 7.1
 - Kodi version: Leia beta 4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Confirmed fixed in https://forum.kodi.tv/showthread.php?tid=336883 addressed by PR referenced above. Closing the issue.

**Comment by micobarac** [comment]
The bug is still there with latest Kodi on Android.
