### ISSUE TITLE
UWP crash report: null_pointer_write_c0000005_libeay32.dll!rsa_get_default_method

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/xbmc#14712]
### Describe the bug
Here is a clear and concise description of what the problem is:

This is a crash report generated by Windows Store for the UWP version. It might be a more platform agnostic problem though.

### To Reproduce
Steps to reproduce the behaviour:

1. Does not contain steps to repro
2.
3.

### Debuglog

The debuglog can be found here:
**null_pointer_write_c0000005_libeay32.dll!rsa_get_default_method** 
> 

Frame | Image | Function | Offset
-- | -- | -- | --
0 | kodi.exe | CGUIListItem::operator= | 0x000000000000003C
1 | kodi.exe | CFileItem::operator= | 0x000000000000003A
2 | kodi.exe | CFileItem::CFileItem | 0x00000000000001A5
3 | kodi.exe | CFileItemList::Copy | 0x0000000000000145
4 | kodi.exe | XFILE::CDirectoryCache::SetDirectory | 0x0000000000000232
5 | kodi.exe | XFILE::CDirectory::GetDirectory | 0x0000000000000B46
6 | kodi.exe | XFILE::CDirectory::GetDirectory | 0x00000000000000D5
7 | kodi.exe | XFILE::CVirtualDirectory::GetDirectory | 0x000000000000017E
8 | kodi.exe | `anonymous namespace'::CGetDirectoryItems::Run | 0x000000000000002A
9 | kodi.exe | CLambdaJob__lambda_3c8b9a4137f6399524cdc3383ea28e02_ _::DoWork | 0x0000000000000012
10 | kodi.exe | CJobWorker::Process | 0x000000000000005A
11 | kodi.exe | CThread::Action | 0x0000000000000033
12 | kodi.exe | CThread::staticThread | 0x000000000000010E
13 | ucrtbase.dll | thread_start_unsigned int (__cdecl*) | 0x000000000000003A
14 | ntdll.dll | RtlUserThreadStart | 0x000000000000002F

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name: 
 - Kodi version: V18 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Neus252** [comment]
Some info found for this issue should be able to fix the problem with this.



"RSA_get_default_method() returns a pointer to the current default RSA_METHOD. However, the meaningfulness of this result is dependent on whether the ENGINE API is being used, so this function is no longer recommended.

RSA_set_method() selects meth to perform all operations using the key rsa. This will replace the RSA_METHOD used by the RSA key and if the previous method was supplied by an ENGINE, the handle to that ENGINE will be released during the change. It is possible to have RSA keys that only work with certain RSA_METHOD implementations (eg. from an ENGINE module that supports embedded hardware-protected keys), and in such cases attempting to change the RSA_METHOD for the key can have unexpected results."

found on. https://www.openssl.org/docs/man1.1.0/man3/RSA_get_default_method.html

**Comment by enen92** [comment]
Closing as stalled
