### ISSUE TITLE
Playing broken h264 stream from mkv container - incorrect keyframe flag - no sound after seek

### ISSUE THREAD

**Issue by nkichukov** [xbmc/xbmc#14718]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a mkv recording(tvheadend generated from IPTV) which seems to have 'Packets with incorrect keyframe flag'. Playback starts fine - both video and audio are in sync. Seeking forward the video causes video to resume but no audio.

If I play the same on mpv-player, it just complains:
'[mkv] This is a broken file! Packets with incorrect keyframe flag found. Enabling workaround.'

and the file remains seek-able and no loss of auido/video  synchronization in the beginning of the video.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expect to be able to seek forward and be able to have video/audio in sync up to the point in time where the stream ends and causes premature end of playback.

## Actual Behavior

Kodi seeks forward, but audio is lost.

## Possible Fix

Perhaps review how the demux happens in mpv-player and apply similar workarounds for broken content:
https://github.com/mpv-player/mpv/blob/master/demux/demux_mkv.c

### To Reproduce

1.) Install kodi 17.3 or 18 beta 4, download the video from:
https://kichukov.home.xs4all.nl/Nova-broken-2018-10-18_22-00.mkv
2.) Start playback and seek 30 seconds forward

### Debuglog

16:41:37.343 T:1569698736  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
...
16:41:37.354 T:1514132400  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
...
16:41:55.140 T:1960383408 WARNING: ActiveAE - large audio sync error: 20990.915313
16:41:55.140 T:1960383408 WARNING: ActiveAE - large audio sync error: 20990.915156
16:41:55.141 T:1960383408 WARNING: ActiveAE - large audio sync error: 20989.915781
...(loads of those)...

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I am trying to play and seek forward in a broken IPTV recording... It is not such a big concern, but if other players can do it, I am hoping kodi can do it too.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: GNU/Gentoo Linux, amd64 with kodi compiled with vdpau support(nvidia hw acceleration). Same is reproducible on GNU/Gentoo Linux, arm with kodi compiled with neon optimizations from popcornmix/xbmc -> newclock5 branch.
 - Kodi version: 17.3 and 18beta4 are affected, issue is reproducible.

Initial issue report in the forum: https://forum.kodi.tv/showthread.php?tid=336647

Thank you!

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by iz8mbw** [comment]
This Issue should be the same reported by me in that https://github.com/xbmc/xbmc/pull/14470 commit. Ping @peak3d

**Comment by peak3d** [comment]
@nkichukov sry, but if you want to have this fixed, you'll have to implemented by yourself.
Sure I'll review your PR.

**Comment by keithah** [comment]
I think this is fixed now, so closing out.
