### ISSUE TITLE
Screensavers, visualizations and test patterns do not work with GL core profile

### ISSUE THREAD

**Issue by yol** [xbmc/xbmc#14723]
### Describe the bug

Kodi v18 was updated to request a Core Profile context for OpenGL. Almost all core code is compatible with that, expect for the test pattern screen in settings. Also, most (if not all) screensaver and visualization add-ons are not updated yet.

## Expected Behavior

All of the features mentioned above should work as before

## Actual Behavior

Black screen, mostly

Note: Not on NVIDIA binary drivers apparently since the driver implements the compatibility extension (mesa does not).

## Possible Fix

Reimplement with Core Profile features (i.e. use shaders and not the fixed function pipeline)

### To Reproduce

1. Start GL Kodi on a mesa GL driver
2. Go to Settings/System/Display
3. Click on "Test patterns"

### Screenshots 

Just close your eyes and imagine a black screen :-)

## Additional context or screenshots (if appropriate)

Just opening this so we don't forget about it for v18. Still need to reach a conclusion whether we want to disable all broken functionality or fix it in some way.

See also xbmc/screensaver.asteroids#10

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux x64
 - Kodi version: 18

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
@AlwinEsch I believe you had a list of broken add-ons?

@VelocityRa How far did you get with the test pattern screen?

@MartijnKaijser What's your verdict for v18 if we don't make it for all add-ons (likely)? Rip out?

**Comment by pkerling** [comment]
@FernetMenta Can you confirm whether this issue affects OS X, too?

**Comment by notspiff** [comment]
I have fixed most of em.. just a lot on my list so not merged or published in all yet.

**Comment by pkerling** [comment]
Very nice! I've taken the liberty of assigning this bug to you then.

**Comment by FernetMenta** [comment]
@pkerling IMO testpatterns is a rather useless feature that I have never used a single time. I think it still works if you force legacy OpenGL. I would drop it completely. There are many videos available that do a better job.

**Comment by pkerling** [comment]
Related: https://forum.kodi.tv/showthread.php?tid=292330

If we drop test patterns, we should also do it for DirectX I guess.

**Comment by VelocityRa** [comment]
I've not done much with porting test patterns and if dropping them is an option I'd vote for it - I've never actually used them either.
I can do it myself if we reach a consensus to drop them.

**Comment by MartijnKaijser** [comment]
I think it's hard to find some one against dropping it :)

**Comment by notspiff** [comment]
note i have opened various pr's in screensavers at least so make sure you don't dupe work.

**Comment by AlwinEsch** [comment]
Ah, was to fast with write here :-D.

Thanks a lot!

**Comment by pkerling** [comment]
@notspiff @AlwinEsch what's the status?

**Comment by pkerling** [comment]
@notspiff @AlwinEsch what's the status?

Test patterns are apparently taken care of.

**Comment by AlwinEsch** [comment]
The most are working, but still not finished also still waiting about this request where needed for the screensavers.rsxs https://github.com/xbmc/pipeline-library/pull/2

**Comment by AlwinEsch** [comment]
Think they are now all fixed and time to close this issue.
