### ISSUE TITLE
NVIDIA SHIELD TV - Kodi 17.6 - interface freezing each 7-8 minutes after start up

### ISSUE THREAD

**Issue by Goga777** [xbmc/xbmc#14733]
### Describe the bug
Here is a clear and concise description of what the problem is:

in 8 minutes after start up  the interface kodi frozen, the running rss string is frozen as well. But i can heard the kodi ui sounds when i pressed the button on RC. With HOME button i can return to shield tv interface and after that i can return ti kodi back - it wil continue to work. But after 7-8 min the interface will again frozen. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

normally, no any frozen interface should happen. I dont expect that any interface will frozen

## Actual Behavior

each 7-8 min the kodi interface was frozen, except of sound, which still alive. Such behaviour can happen during video watching 0 the video will be frozen, but  i able to heard the sound and voice.

## Possible Fix

i don't have idea why it can happen

### To Reproduce

1. start up of the kodi
2. wait 7-8 minutes or to start the video watching
3. the interface will be frozen or the video will stop but the sound will continue

### Debuglog

The debuglog can be found here:

see the lof files after 7-8 minutes of the kodi start up - at 16:52 and others 
http://slexy.org/view/s2ThRS9hJ7
http://slexy.org/view/s2phEOZ1of
http://slexy.org/view/s2FqUt8PAn - see at 17:28 
https://forum.kodi.tv/showthread.php?tid=304226&pid=2782612#pid2782612
 

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://drive.google.com/open?id=1lUFGsL_YpeSw_tuCGp6GDznTnukrjKlt
photo with frozen interface

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

such bug can disappear and appear again in several days/hours

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
17.6
nvidia shield tv 2017

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by da-anda** [comment]
I had a similar issue once, and mine was related to some UPNP capable device in my network spamming the UPNP ports and KODI on Android not liking it for some yet unknown reason. So it might be worth a try to disable UPNP support entirely in Settings -> Services -> UPNP/DLNA. You can only disable it entirely in v18 though, since only there the new setting that allows this has been added. So if you don't mind, install the latest beta and give it a try.

If you don't think it's related to UPNP, please still try to see if it's still occuring in v18. So many things have changed since v17.6, so the chances are very high that the issue is already fixed.

**Comment by MartijnKaijser** [comment]
Only reports for v18 are allowed as v17 is end of life

**Comment by da-anda** [comment]
I did have a look at one of your logs, and they are full of UPNP stuff, so I suspect it's the same issue I had, and the only solution we found so far is to completely disable UPNP in KODI if you don't need it. The other solution would be to find out which of the devices in your network is causing the UPNP spam and turn off UPNP on that device (in case you don't need it). In my case it was a network enabled radio causing the issue

**Comment by Goga777** [comment]
yes, indeed "guilty" upnp device was internet radio OCEAN WR-282CD, i can't disable upnp on it - no nay options for it. In kodi 17.6 upnp was disabled in system settings, but it didn't help me. As you mentioned, only on kodi 18 there is a possibility to completely disable upnp. But upnp will need to me to open some ports.

**Comment by Goga777** [comment]
with kodi 18 beta4 and disabled upnp in kody system settings i don't have that issue
