### ISSUE TITLE
Resolution Whitelist issues (Win 10 | v18 latest nightlies and beta/rc)

### ISSUE THREAD

**Issue by liquidskin76** [xbmc/xbmc#14735]
### Describe the bug
Here is a clear and concise description of what the problem is:

Windows 10 using nightlies and beta 4. I'm seeing strange behaviour (both 4k and 1080p screen resolutions and videos) with resolution switching using the resolution whitelist feature.

**3840 x 2160 screen resolution playing 1080p videos...**

With my screen resolution set to 3840x2160, and with all 1920x1080 resolutions selected in the resolution whitelist, 1080p video displays in top left corner as 1920x1080, however screen resolution remains at 3840x2160.

Screenshot... https://imgur.com/FGsf2GV
Debug log... https://paste.kodi.tv/qaruxaluce.kodi

**1920 x 1080 screen resolution playing 4k videos...**

With my screen resolution set to 1920x1080, and with all 3840x2160 resolutions selected in the resolution whitelist, only the top left quarter of the 4k video displays, however screen resolution remains at 1920x1080.

Screenshot... https://imgur.com/G8ZMIGf
Debug log... https://paste.kodi.tv/okodawoxix.kodi

Forum post related to issue... https://forum.kodi.tv/showthread.php?tid=336934

**The whitelist feature works fine if run Kodi as a fullscreen window.
However behaves as above if i run true fullscreen.**

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

With the screen resolution set 3840x2160, and with the 1920x1080 resolutions selected in the resolution whitelist, 1080 resolution videos should switch the display to 1920x1080.

With the screen resolution set 1920x1080, and with the 3840x2160 resolutions selected in the resolution whitelist, 4k resolution videos should switch the display to 3840x2160.

## Actual Behavior

**3840 x 2160 screen resolution playing 1080p videos...**

With my screen resolution set to 3840x2160, and with all 1920x1080 resolutions selected in the resolution whitelist, 1080p video displays in top left corner as 1920x1080, however screen resolution remains at 3840x2160.

Screenshot... https://imgur.com/FGsf2GV
Debug log... https://paste.kodi.tv/qaruxaluce.kodi

**1920 x 1080 screen resolution playing 4k videos...**

With my screen resolution set to 1920x1080, and with all 3840x2160 resolutions selected in the resolution whitelist, only the top left quarter of the 4k video displays, however screen resolution remains at 1920x1080.

Screenshot... https://imgur.com/G8ZMIGf
Debug log... https://paste.kodi.tv/okodawoxix.kodi

### To Reproduce

1. set screen resolution to 3840x2160
2. select all 1920x1080 resolutions in the resolution whitelist
3. set kodi to true fullscreen
4. play 1080p video

This results in... https://imgur.com/FGsf2GV

or

1. set screen resolution to 1920x1080
2. select all 3840x2160 resolutions in the resolution whitelist
3. set kodi to true fullscreen
4. play 4k video

This results in... https://imgur.com/G8ZMIGf

### Debuglog

The debuglog can be found here:

**3840 x 2160 screen resolution playing 1080p videos...**
Debug log... https://paste.kodi.tv/qaruxaluce.kodi

**1920 x 1080 screen resolution playing 4k videos...**
Debug log... https://paste.kodi.tv/okodawoxix.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

**3840 x 2160 screen resolution playing 1080p videos...**
Screenshot... https://imgur.com/FGsf2GV

**1920 x 1080 screen resolution playing 4k videos...**
Screenshot... https://imgur.com/G8ZMIGf

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro v1803
 - Kodi version: Nightlies and Beta 4
- GPU: NVidia GT 1030

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by liquidskin76** [comment]
NVidia GT 1030 GPU in use, on latest NVidia drivers.

Some further testing...

The whitelist feature works fine if run Kodi as a fullscreen window.

However behaves as above if i run true fullscreen.

**Comment by ralphsinclair** [comment]
This is a general issue with resolution switching in Kodi 18 on Windows.  Every Windows system I've tried this on has the same issue, exactly as described here.  Please note that the display refresh rate changes, just not the resolution.

This is a regression from Kodi 17 for Windows systems not capable of smoothly rescaling or smoothly playing back in fullscreen window.

**Comment by liquidskin76** [comment]
FYI... I’ve retested in beta 5 and the same issue exists. And same again, it works as intended when running kodi as a fullscreen window, but not when running true fullscreen. Thanks

**Comment by ralphsinclair** [comment]
Thanks for letting me know.


I had opened a similar ticket in Trac a few months ago.


https://trac.kodi.tv/ticket/18045#comment:3

When I added a comment to my Trac ticket with a link to your github ticket, Martjin assigned your git ticket to the same dev.


I'm not sure why they aren't looking into it.



________________________________

**Comment by pkerling** [comment]
Sometimes people are just busy. Thanks for your understanding. You are welcome to help out any time.

**Comment by liquidskin76** [comment]
Hi afedchin ,

I pulled out my nvidia gt 1030 card and tested using my 6th generation intel i5-6500 HD 530 graphics. Still had the same issue so not gpu dependant.

Many thanks

**Comment by liquidskin76** [comment]
Oh, and i'm seeing micro stuttering on playback. And some green blocking now and then. I'll try and grab a log for that and open a separate ticket. Thanks

**Comment by afedchin** [comment]
please try this build http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20181210-6350b012-fix-14735-x64.exe

**Comment by ralphsinclair** [comment]
Thanks afedchin.  This time the UI is the right size and video is also the right size, but video is cropped down to the windows desktop resolution.  I think to continue with this approach the video rendering window still needs to be resized to match the new screen resolution.  Sorry I can't provide logs right now; I will look into it some more same time tomorrow,

**Comment by afedchin** [comment]
please try updated build http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20181211-842b1516-fix-14735-x64.exe

**Comment by liquidskin76** [comment]
Hi afedchin,

That sorted the issue for me perfectly. 4k vids switch to the whitelisted 4k resolutions, and 1080p vids switch to the 1920x1080 resolutions. All good from me.

Cheers for fixing.

Have a great Christmas.

**Comment by ralphsinclair** [comment]
Thanks afedchin.  It worked!  The first time, I saw the usual prompt about accepting the changed resolution (the prompt shown when changing resolution manually through UI - I have seen this before in other betas).  But it's been working perfectly since then - I have not been able to replicate getting the resolution change prompt.

Will we see this fix in the next RC?

Thanks again!

**Comment by afedchin** [comment]
thanks for feedback.
