### ISSUE TITLE
Kodi 18 beta not show subtitles on nvidia shield tv

### ISSUE THREAD

**Issue by elricmel** [xbmc/xbmc#14749]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello, I just tested the beta 4 version of Kodi 18 on shiel tv and no more subtitles are displayed, those in file as the subtitles of the films. I had to exit the beta program and return to 17.6 for the subtitles to be displayed. Do you have a solution ?
I have tested on samsung tablet, the subtitles work perfectly

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

 try video calibration but even putting original (1280x720) subtitles do not display, I tried to change the subtitle button on / off no effect . kodi seems to no longer want to display subtitles with nvidia shield tv.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: nvidia shield tv
 - Kodi version:
18 beta 4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Dnkhatri** [comment]
To fix this
From the main menu, navigate to Settings > Player Settings.
In the Videos tab, make sure that Play Next Video Automatically is turned OFF.

When the Play Next Video is on kodi 18 makes a playlist and plays that and in kodi 18 it breaks external subtitles at least for nfs shares. If you like using play next video for tv shows I would recommend using Next Up Notifications addon instead. As I don't think the kodi developers think this is a bug as both my threads about this bug were either ignored or  marked as fixed without actually confirming anything.

**Comment by MartijnKaijser** [comment]
Try a new nightly build

**Comment by elricmel** [comment]
Hello, I managed to raise the subtitles, the bar was very low. on the other hand as soon as I leave kodi, it is reset.
have you a solution please ?

**Comment by peak3d** [comment]
there are changes in the latest kodi nightly regarding subtitle position / calibration.
Pls. test the latest kodi nightly.

**Comment by thezoggy** [comment]
v18 nightlies with subtitles on nvidia shield work fine here. now i will say that in v18 the toggle subs button results in a pop up for subs being disable but rarely that it was enabled.. but the subs do actually get enabled. so more of just a cosmetic thing on the pop up not firing

**Comment by elricmel** [comment]
this work correctly with beta5 of 11/02. thanks very much for your help

**Comment by sspilleman** [comment]
This shouldn't be closed. Still no subtitles on my shield with beta 5!

**Comment by peak3d** [comment]
@sspilleman deinstall / reinstall kodi with the default skin and verify if it works.
If so, start customizing your kodi and pay attention when subs get lost.
