### ISSUE TITLE
Player infolabels not giving correct results when accessed from Python

### ISSUE THREAD

**Issue by gilesp1729** [xbmc/xbmc#14740]
Player infolabels not giving correct results when accessed from Python on Leia beta 4, when playing live TV. Krypton builds work OK. e.g. Player.StartTime and Player.Duration. There may be others.

## Expected Behavior
Result agrees with accessing infolabels in XML.

## Actual Behavior
Random results.

### To Reproduce
Python script calls xbmc.getInfoLabel('Player.Duration(hh:mm)') in the context of a PVR OSD.
e.g. in the Mousetuary skin (in github at gilesp1729/skin.mousetuary, leia branch)
Other skins or addon scripts may do this too, I just haven't got another good example to hand.

### Debuglog
No error messages in the log.

### Your Environment
Used Operating system:
 - [ ] Windows

 - Operating system version/name:
 - Kodi version:
Leia 18 beta 4

**Comment by gilesp1729** [comment]
In Leia, Player.Duration returns a consistent value in XML (Estuary displays it). That is, it agrees with the length of the live TV program. However, when called from Python, it appears to display the length of time I have been viewing the program (i.e. it counts up from zero). Player.StartTime is also strange, it is only Player.FinishTime that appears to be consistent all the time.

In Krypton, both the XML and Python usages of Player.Duration were correct and agreed with each other.


Should I only be using Player infolabels when referencing a recording, and PVR when viewing live from the EPG? I will try that too.

**Comment by ksooo** [comment]
> In Leia, Player.Duration returns a consistent value in XML (Estuary displays it). That is, it agrees with the length of the live TV program. However, when called from Python, it appears to display the length of time I have been viewing the program (i.e. it counts up from zero). 

What you describe for the python  case  is the desired Leia behavior. Please double check that the behavior for xml is actually different. Looking at the code (quickly) this can hardly be. VideoPlayer does not know any longer about EPG time, this it cannot return "length of tv show" anymore.

If your test was to look what estuary displays, you need to test again, as estuary dies no longer use player.duration when playing live tv with epg data.

**Comment by gilesp1729** [comment]
Thanks ksooo. If this is by design you can close the issue.

**Comment by ksooo** [comment]
np
