### ISSUE TITLE
VideoPlayer.Year Issue

### ISSUE THREAD

**Issue by lorkadiscovery** [xbmc/xbmc#14754]
### Describe the bug
Here is a clear and concise description of what the problem is:

https://github.com/trakt/script.trakt/issues/446

Hi there,

I have a quick question if you could help.

I am making a little addon for my local anime series I have so I can watch them when away and I have found a little issue I cannot work around.

When not playing from library trakt falls back to the year from the player infolabel for year.

I have found that if you set "year" as an InfoLabel trakt uses that year for the tv show.

However, if you set an "aired" info label for an episode trakt gets the year from that infolabel and not the "year" infolabel.

So as an example Yu-Gi-Oh" Duel Monsters first aired in 2000

So on my episodes the "year" info label is set to 2000, the "aired" info label is set to a different year as the show went on for 5 years.

When trakt picks up im watching this the log shows this.

10:53:08.419 T:5280 DEBUG: [script.trakt] resources.lib.scrobbler: playbackStarted(data: {u'episode': 21, u'title': u'Double Trouble Duel (Part 3 of 3)', u'season': 1, u'year': 2002, u'type': u'episode', u'showtitle': u'Yu-Gi-Oh! Duel Monsters'})

As you can see year is 2002, that is the right year of the episode but its a 404 from trakt as the show started airing in 2000.

If i remove the "aired" info label trakt shows me watching the episode and the log shows the year as 2000, but with aired it swaps to 2002 and does not sync to the trakt website.

Some further thinking on this issue:

If the issue comes from

year = xbmc.getInfoLabel('VideoPlayer.Year')

Providing the year in ['premiered', 'aired'] instead of the year set via

item.setInfo(type='Video', infoLabels=meta)

So meta = {'aired': '2017-05-10', 'year': '2015'}

As xbmc.getInfoLabel('VideoPlayer.Year') is reporting 2017 instead of 2015 I assume this is not an issue for you but more an issue for Kodis core?

Any advice please?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

VideoPlayer.Year should display the {year: int} set as item.infolabels not take the year from the {aired} date.

## Actual Behavior

VideoPlayer.Year displays the year from an aired or premiered infolabel not the year infolabel.

## Possible Fix

Unsure

### To Reproduce

In any video addon sent year and aired as the infolabel of a playable item.

item.setInfo(type='Video', infoLabels= {'aired': '2017-05-10', 'year': '2015'})

Then check the VideoPlayer.Year from the Kodi player.

### Your Environment
Used Operating system:

 - [Yes ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [Yes ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

Windows and Android
Kodi 18 Beta 4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lorkadiscovery** [comment]
It seems to me that the issue is here

  `value["premiered"] = m_premiered.IsValid() ? m_premiered.GetAsDBDate() : StringUtils::Empty;
  value["status"] = m_strStatus;
  value["productioncode"] = m_strProductionCode;
  value["firstaired"] = m_firstAired.IsValid() ? m_firstAired.GetAsDBDate() : StringUtils::Empty;
  value["showtitle"] = m_strShowTitle;
  value["album"] = m_strAlbum;
  value["artist"] = m_artist;
  value["playcount"] = GetPlayCount();
  value["lastplayed"] = m_lastPlayed.IsValid() ? m_lastPlayed.GetAsDBDateTime() : StringUtils::Empty;
  value["top250"] = m_iTop250;
value["year"] = m_premiered.GetYear();`

https://github.com/xbmc/xbmc/blob/0978b1dfa3923726841a04b11202eff44552d644/xbmc/video/VideoInfoTag.cpp

So the video player reports the year as the year of the episode.

However when the kodi trakt addon is sending the info to trakt to find a show trakt wants the year the show aired not the year the episode aired.

Would it not be better for the video player to attempt to take the year from the year infolabel or the firstaired infolabel before trying premiered/aired?

**Comment by lorkadiscovery** [comment]
@Razzeee Thank you.

**Comment by lorkadiscovery** [comment]
I believe this is not an issue kodi will look at due to the framework being that kodi wants to show the year as the year of the episode and not the year of the show itself. 

In future maybe the videoplayer could return an infolabel like VideoPlayer.ShowYear but thats down to the team.

Thanks, I will close the issue.

**Comment by Razzeee** [comment]
While that's not a bug I feel like it's a reasonable thing to implement. Will hopefully have some time in one or two weeks for this.
