### ISSUE TITLE
Files does not show up when using FTP with TLS authentication with a self signed certificate in Kodi 18 beta 4

### ISSUE THREAD

**Issue by oddhap** [xbmc/xbmc#14757]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using FTP with TLS authentication (self signed certificate) as a source files no longer shows up in Kodi 18, tested with Kodi 18 beta 4 and lates nightly as of 31.10.18 on both windows and android.

Source is added with the following command: ftp://username:password@ftp.address.com:port/|auth=tls

Kodi 17.4 shows the files and playback is working correctly, but it does not remember what files you have watched when using FTP + tls.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Files show up. Videos gets marked as watched after watching.

## Actual Behavior

No errors when adding source. No files show up.
In 17.4 files show up and playback works, but videos does not get marked as watched.

### To Reproduce

1. Add a secure FTP server with TLS authentication as source
ftp://username:password@ftp.address.com:port/?auth=tls
2. Try to browse files.

### Debuglog

The debuglog can be found here:
https://pastebin.com/UeJVPMBs
(ftp address replaced with ftp.address:21)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
17.4
18 beta 4
18 nightly 31.10.18

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Rechi** [comment]
> WARNING: XFILE::CCurlFile::ParseAndCorrectUrl: ftp url option is deprecated, please switch to use protocol option (change '?' to '|'), url: [ftp://USERNAME:PASSWORD@ftp.address:21/folder.jpg?auth=tls]

Your log already tells you the solution. Post a new log if it still doesn't work.

**Comment by oddhap** [comment]
> 
> 
> > WARNING: XFILE::CCurlFile::ParseAndCorrectUrl: ftp url option is deprecated, please switch to use protocol option (change '?' to '|'), url: [ftp://USERNAME:[PASSWORD@ftp.address](mailto:PASSWORD@ftp.address):21/folder.jpg?auth=tls]
> 
> Your log already tells you the solution. Post a new log if it still doesn't work.

If you scroll a little further down the logfile you will see that I tried using both methods with the same result.

**Comment by Rechi** [comment]
Haven't looked that far, now I've looked at the whole log and it tells you the real reason for your issue.

> ERROR: CCurlFile::FillBuffer - Failed: Peer certificate cannot be authenticated with given CA certificates(60)

You can find more info at https://forum.kodi.tv/showthread.php?tid=331918

**Comment by oddhap** [comment]
Added cert to cacert.perm and seems to be working. Issue solved. Thanks.
