### ISSUE TITLE
Lockup and Crash on AMD Ryzen 3 2200G with Radeon Vega Graphics 

### ISSUE THREAD

**Issue by awcoding** [xbmc/xbmc#14762]
### Describe the bug
Here is a clear and concise description of what the problem is:

kodi  17.6 doesn't play video on AMD Ryzen 3. So I upgraded to kodi:all/bionic 2:18.0+git20181023.1820-beta4-0bionic on ubuntu. That was an improvement and now works but it randomly crashes or induces a crash during playback. It manifests a frozen image stuck on screen and no possible way to recover the session without hard rebooting the machine. Playing back the same part of the video doesn't crash it. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No crash.

## Actual Behavior

Crash.

### To Reproduce

1. Play video with this cpu / kodi version, wait for crash.
2.
3.

### Debuglog

The debuglog can be found here:
https://pastebin.com/MQ5hB25q

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - X Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu
 - Kodi version:18.0-BETA4 Git:20181023-9d3a68a

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
Hi,

> It manifests a frozen image stuck on screen and no possible way to recover the session without hard rebooting the machine.

What ways have you tried? Can you verify whether the machine complete locks up e.g. by trying to ssh into it from another computer? Please try to get a kernel log. This looks like it might be a kernel problem, and them I'm afraid this would be the wrong place to report it.

Also, if you want us to consider this further, please replace your log with a *debug log* (yours did not have debugging enabled). See https://kodi.wiki/view/Log_file/Easy for details. Please use a proper paste/upload service and do not copy-paste it into the issue.

**Comment by awcoding** [comment]
kern.log: https://pastebin.com/tMeAXhvr
It seems kernel-y or videocard related. I can still ssh into the machine but issuing a poweroff from the command prompt won't halt the machine but it will log me out of the ssh session.

The only strange thing is that I don't have this problem at all with vlc 3.0.3-1.  I'd prefer to use kodi since I can barely read the vlc text on the 4K bigscreen. So if you can do whatever it is they are doing, that would probably work.

**Comment by fritsch** [comment]
Your kernel and your mesa is quite old, also your linux-firmware. Upgrade those bits first.

VLC does not use OpenGL for rendering, means: weak drivers, broken kernel are first detected by kodi.

Come back with kernel 4.18 or later with updated linux-firmware and mesa 18.2.3 including kodi v18, please.

**Comment by pkerling** [comment]
@awcoding Please respond or we will close this issue in the next few days.

**Comment by awcoding** [comment]
Apologies for not responding sooner. fritsch's advice was good and a kernel update helped alot.
Thanks!
