### ISSUE TITLE
Kodi App causes Windows 10 1809 Issues

### ISSUE THREAD

**Issue by mikeyhalla** [xbmc/xbmc#14769]
Issue that is caused is the right click context menu on the desktop or any directory background with "new".
As soon as you hover over New then it freezes up for about 10 seconds and then finally shows whatever is available in that context such as New Folder, etc...

Note that the Windows version is 1809.

**Comment by MartijnKaijser** [comment]
You did not provide the requested info.

**Comment by mikeyhalla** [comment]
Pardon me. Allow me to spend even more time on this so that I can alert YOU of YOUR errors. Please, forgive me great one!

**Comment by mikeyhalla** [comment]
I am already looking for a replacement so YOU can take your precious Kodi and stick it straight up.... Also, I'm pretty sure the problem is just Windows anyway so you can go back to being lazy now. xd
