### ISSUE TITLE
wrong CPU temperature reported on RPi with w1 temperature sensor connected on w1-gpio

### ISSUE THREAD

**Issue by alinnastac** [xbmc/xbmc#14775]
## Bug report
CCPUInfo::CCPUInfo() try to read temperature from /sys/class/hwmon/hwmon0/temp1_input before falling back to  /sys/class/thermal/thermal_zone0/temp.
### Describe the bug
On Raspberry PI CPU temperature can be read from /sys/class/thermal/thermal_zone0/temp, but when a temperature sensor is connected through w1-gpio,  the temperature reported  in System Info page is the one read from w1_slave device that is available in file /sys/class/hwmon/hwmon0/temp1_input.
## Possible Fix
The easiest way to fix it would be to reverse the order, first try to read /sys/class/thermal/thermal_zone0/temp and if this fail, switch to /sys/class/hwmon/hwmon0/temp1_input. However, this is not in line with the [cputemp](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/mediacenter/kodi/scripts/cputemp) script available on LibreElec which uses a different logic. According to this logic, CPU temperature should be read from these sources in this exact order of precedence:
- /sys/class/hwmon/$X/temp1_input or /sys/class/hwmon/$X/temp2_input when /sys/class/hwmon/$X/name content is coretemp, k10temp or scpi_sensors
- /sys/class/hwmon/hwmon0/device/temp1_input
- /sys/class/thermal/thermal_zone0/temp

As you can see, /sys/class/hwmon/hwmon0/temp1_input is not even tried in this script, but if you have to try to read it, please ignore it when /sys/class/hwmon/hwmon0/name contains w1_slave_temp.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [X] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.0-BETA4 Git:newclock5_18.0b4-Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Thanks for the report, however I am going to mark this invalid as it doesn't actually pertain to the thermal sensor on the SOC which is supported in Kodi.

You can use a custom shell script (like what LibreELEC does) to allow reading from other devices.
see, https://kodi.wiki/view/Advancedsettings.xml#cputempcommand

for example, `~/.kodi/userdata/advancedsettings.xml`
```
<advancedsettings>
  <cputempcommand>/usr/local/bin/cputemp</cputempcommand>
</advancedsettings>
```

then, `/usr/local/bin/cputemp`
```
#!/bin/sh

TEMP="$(cat /sys/class/hwmon/hwmon0/temp1_input)"
echo "$(( $TEMP / 1000 )) C"
```
then, `chmod +x /usr/local/bin/cputemp`

**Comment by MilhouseVH** [comment]
> However, this is not in line with the cputemp script available on LibreElec which uses a different logic.

LibreELEC 9.0 has [reimplemented](https://github.com/LibreELEC/LibreELEC.tv/blob/6db1ac5f83968c6ecaf303294e650d7814440844/projects/RPi/filesystem/usr/bin/cputemp) the `cputemp` script to avoid the problem described in this issue, and no longer depends on the internal Kodi sensor selection.
