### ISSUE TITLE
Add-on zips with a plus '+' sign in the filename fail to install from repo

### ISSUE THREAD

**Issue by glennguy** [xbmc/xbmc#14779]
### Describe the bug
Here is a clear and concise description of what the problem is:

The zip file is being downloaded from the repo and placed in special://home/addons/packages but the '+' becomes a space eg. `plugin.video.cricketaustralia-0.0.1~5+gitg6da9f43.zip` becomes `plugin.video.cricketaustralia-0.0.1~5 gitg6da9f43.zip`. So it would seem that the plus character is not being unescaped to a space or otherwise dealt with incorrectly. In turn, Kodi can't find the zip it is trying to install.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Add-on to install correctly

## Actual Behavior

Add-on failed to install. From log: 
```
13:17:18.987 T:1460163488   ERROR: GetDirectory - Error getting zip://special%3a%2f%2fhome%2faddons%2fpackages%2fplugin.video.cricketaustralia-0.0.1%7e5%2bgitg6da9f43.zip/
13:17:18.987 T:1460163488   ERROR: CAddonInstallJob[plugin.video.cricketaustralia]: invalid package special://home/addons/packages/plugin.video.cricketaustralia-0.0.1~5+gitg6da9f43.zip
```

### To Reproduce

1. Download and install this [repo](https://github.com/aussieaddons/repo-devel/raw/kodi_plus_bug/repository.aussieaddons-devel/repository.aussieaddons-devel-bug.zip)
2. Attempt to install video addon 'Cricket Australia' version 0.0.1~5+git6da9f43

### Debuglog

The debuglog can be found here: https://hastebin.com/raw/ekogaqetim

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro 17134
 - Kodi version: 18 Beta 5 20181101-8f12995cac

**Comment by mpember** [comment]
I experienced this issue on a Linux-based setup (LibreELEC 8.2.5)

**Comment by pkerling** [comment]
> are hyphens meant to be excluded from valid add-on versions

Add-on versions are similar to debian package versions - `<version>-<revision>:<epoch>`. As such, `-` is invalid inside the version and revision components (epoch is just one number anyway).

> The tests seem to indicate that this may be in error

As you probably noticed, the tests run fine.

**Comment by pkerling** [comment]
> The whole reason I've changed the versioning in the repo from how git describe formats it was the apparent invalidity of hyphens in add-on versions in Kodi 18

What concrete add-on version did you have issues with?

**Comment by glennguy** [comment]
> As you probably noticed, the tests run fine.

Yes, it seems that it is me who is in error! My reading comprehension is to blame:

> What concrete add-on version did you have issues with?

eg. `1.1.2-5-gfca6347` (which just comes from `git describe`)
It's been staring me in the face that there are *2* hyphens in the version 😟 . I know what to do now. Thanks so much for having a look.

Anyway the main issue here of not being able to install eg. `0.0.1~5+gitg6da9f43` from a repo still stands.

**Comment by pkerling** [comment]
> It's been staring me in the face that there are 2 hyphens in the version worried . I know what to do now. Thanks so much for having a look.

Yes, that seems to be the problem.

> Anyway the main issue here of not being able to install eg. 0.0.1~5+gitg6da9f43 from a repo still stands.

Agreed. Just wanted to clarify about the versions.
