### ISSUE TITLE
External NAS Drive not configurable or accessable in 18b4 on android 7.1.1

### ISSUE THREAD

**Issue by kiwikwik** [xbmc/xbmc#14778]
After updating from v17.6 to 18.4 -64bit, my Android system is unable to access network storage (WD MyBook Live).  SMBDirectory errors are visible in log where system is attempting to scan library based on inherited configuration data.  Cannot create new link to NAS server via IP address or hostname via NFS and SMB.  'Browse' function brings back no data after entering connection detail.    Tried adding Host Entry in AdvancedSettings file, followed by complete reboot with no benefit,   Observed MyBookLive/Public as the only server listed in mediasources.xml.  No other system or network changes have taken place and several other devices have no problem mapping network drive.

**Update1**:  Same behavior noted with 18.5 and RC1.  I was able to confirm that the NAS was running SMB dialog 2.0.2 when connected to my windows 10 device.  I uninstalled and did Clean Reinstall of RC1 with no improvement.  Tried creating SMB connection with and without User/Pwd.  NFS connection request just hangs and I had to exit Kodi to recover.  Clean log is now attached.

**Update 2:**  In order to maximize throughput my TV Box has always been hardwired direct from one of my DSL ethernet out ports (66.x.x.x).  The only other port out from the DSL was the wifi Router, with all other devices, including the NAS connected from the Router (192.x.x.x).  I moved the TV Box to the Router and NFS didn't work until I re-entered the path.  SMB connections worked without redefinition.   SO, Why were these devices working in 17.6 with their original network configuration, but broken in 18.x?  Can you either fix this so it works again or add an Error message indicating the 2 devices are not on the same subnet if that is going to be critical going forward?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Should be able to see server name when browsing to create new link to music share.
Should be able to play music files stored on drive.

## Actual Behavior
'Cannot Connect' and 'Server Not Found' error messages received when trying to link with NFS or SMB options.
System displays list of albums/songs scanned previously, and seems to roll from one song to the next every few seconds - perhaps searching for a file to play, but does not play anything.

## Possible Fix

Wild guess:  New Network protocols?

### To Reproduce

1. On Android 7.1.1 System, Link external device to Music Source.  
2. From menu, choose to play music from source.
3.

### Debuglog

The debuglog can be found here: 
Latest debug log for RC1:  https://paste.kodi.tv/ukayukejot.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:  Android 7.1.1 -25
 - Kodi version:  now on RC1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
I don't think this is a valid issue. It sounds like it worked by luck before. You cannot expect Kodi to look for devices on a different subnet unless you explicitly setup your own network to handle that.
