### ISSUE TITLE
None responsive when minimising Kodi Mac OSX

### ISSUE THREAD

**Issue by 20mxm** [xbmc/xbmc#14773]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I minimise then reopen, Kodi becomes none responsive(Crash)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Be able to use Kodi normally.  keyboard or mouse

## Actual Behavior

When I minimise then reopen, Kodi becomes none responsive(Crash)
Cannot use keyboard or mouse to navigate around Kodi 

### To Reproduce

1.open Kodi
2.click minimise(yellow icon)
3.click on the minimised Kodi icon(Dock)

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/bezinexafu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

minimise icon(yellow)
<a href="https://imgur.com/o3O9AjM"><img src="https://i.imgur.com/o3O9AjM.png" title="source: imgur.com" /></a>
kodi minimised bottom right(Dock)
<a href="https://imgur.com/57dLUW6"><img src="https://i.imgur.com/57dLUW6.png" title="source: imgur.com" /></a>

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

When I minimise then reopen, Kodi becomes none responsive(Crash)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:Mojave 10.1.41
 - Kodi version:Kodi 18 Nightly 1-11-2018

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by zag2me** [comment]
Thankyou for your report, but all reports must use the template provided. Please edit your post with the required template.

**Comment by 20mxm** [comment]
Updated
Thanks

**Comment by zach-morris** [comment]
I'd guess it's the same issue described [here](https://forum.kodi.tv/showthread.php?tid=336076).
I have the same issue, and this only seems to occur on OSX 10.14

**Comment by Memphiz** [comment]
fix proposed in PR #15105

**Comment by enen92** [comment]
Fixed in https://github.com/xbmc/xbmc/pull/15105
