### ISSUE TITLE
setFocus() Broken Kodi 18 Estuary

### ISSUE THREAD

**Issue by lorkadiscovery** [xbmc/xbmc#14780]
### Describe the bug
Here is a clear and concise description of what the problem is:

Raised here on the forum with no response:
https://forum.kodi.tv/showthread.php?pid=2727573#pid2727573

Issue raised here with no response:
https://github.com/phil65/skin.estuary/issues/250

In Estuary Kodi 17, we are able to call addon settings and display a specific tab and a specific setting by using the following code

`execute('Addon.OpenSettings(%s)' % id)
execute('SetFocus(%i)' % (int(c) + 100))
execute('SetFocus(%i)' % (int(f) + 200)`
However the same code when run on Estuary Kodi 18, only opens the default first tab and sits there

Can you please look into why this feature has stopped working in Kodi 18 Estuary or advise if the setfocus codes have changed. Thanks 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When the settings open setFocus should make kodi focus on the correct submenu and item in settings as set in setfocus.

## Actual Behavior

Settings open on normal top positions ignoring the setfocus.

### Your Environment
Used Operating system:

 - [ x ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ x ] Windows
 - [ x ] Windows UWP

 - Operating system version/name:
    Windows 10 x64 
 - Kodi version:
    Kodi 18 Beta 4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
the addon settings code has changed a lot in v18 (see https://github.com/xbmc/xbmc/pull/12125)
this means you will have to update the id's you use in your code:
https://github.com/xbmc/xbmc/blob/4dda45ca29f5c388e9ab4db04b63686c667e6782/xbmc/settings/dialogs/GUIDialogSettingsBase.h#L29-L30


not a kodi bug. closing.

**Comment by lorkadiscovery** [comment]
Thanks @ronie 

Would you be able to go a little bit further in depth about the changes to the ids please.

I've followed your links but have no idea what all that means.

Thanks I'm advance.
