### ISSUE TITLE
UPNP menu missing from Kodi 18.x beta. 

### ISSUE THREAD

**Issue by ZaphodX77** [xbmc/xbmc#14788]
### Describe the bug
The menu for selecting files no longer has the UPNP selection to get to Serviio.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The menu for selecting files must have the UPNP selection to get to Serviio.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MartijnKaijser** [comment]
Report is incomplete
