### ISSUE TITLE
NVIDIA SHIELD Android TV -  KODI 18.0-RC1 - strange empty black rectangle after click on exit button 

### ISSUE THREAD

**Issue by Goga777** [xbmc/xbmc#14786]
### Describe the bug
Here is a clear and concise description of what the problem is:

after clicking on shutdown button there is strange empty rectangle. I clicking on it, but nothing happened 
in advancedsettings i have showexitbutton = false

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

i expect that after clicking on shutdown button the kodi will normally exit immediately after click

## Actual Behavior

but after clicking on shutdown button i see empty rectangle

### To Reproduce

1. click on exit/shutdown button
2.after that you will see strange empty black rectangle
3.

### Debuglog

The debuglog can be found here:
http://slexy.org/view/s2yrE7doAV

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18b5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HitcherUK** [comment]
Can't reproduce and your debuglog has expired.

**Comment by HitcherUK** [comment]
That should be the exit button. Try removing your advanced setting showexitbutton = false

**Comment by Goga777** [comment]
yes, with showexitbutton = true i can see perfectly the exit button. The question is how to hide it definitely? on kodi under linux i haven't seen it and i was happy without this button

**Comment by HitcherUK** [comment]
For Confluence you'd have to remove this code from Home.xml.

```
			<control type="button" id="20">
				<description>Power push button</description>
				<left>55</left>
				<top>0</top>
				<width>45</width>
				<height>45</height>
				<label>31003</label>
				<font></font>
				<onclick>ActivateWindow(ShutdownMenu)</onclick>
				<texturefocus border="5">floor_buttonFO.png</texturefocus>
				<texturenofocus border="5">floor_button.png</texturenofocus>
				<onleft>21</onleft>
				<onright>21</onright>
				<onup>9002</onup>
				<ondown>9003</ondown>
			</control>
			<control type="image">
				<description>Power Icon</description>
				<left>60</left>
				<top>5</top>
				<width>35</width>
				<height>35</height>
				<aspectratio>keep</aspectratio>
				<texture>icon_power.png</texture>
			</control>
```

**Comment by Goga777** [comment]
sorry, but after removal above lines the main "power" button on the left bottom part of the screen disappeared. I would like to keep it, but without exit button

**Comment by HitcherUK** [comment]
But the only shutdown option you have on the Shield is Exit which is why that dialog is empty when you use showexitbutton = false otherwise you'd see all options apart from Exit.
