### ISSUE TITLE
Gui set to unlimited causes kodi to not launch

### ISSUE THREAD

**Issue by JonnyGadd** [xbmc/xbmc#14792]
### Describe the bug
Here is a clear and concise description of what the problem is:

When you set to Gui limit to unlimited in display settings kodi does not launch

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android Android nvidia shield 
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MartijnKaijser** [comment]
There's no useful information at all in this ticket.
