### ISSUE TITLE
UPnP/DLNA feature is currently badly broken

### ISSUE THREAD

**Issue by EricV2** [xbmc/xbmc#14793]
### Describe the bug
I can't get Kodi 18 to correctly browse my multimedia library exposed via a DMS (minidlna/readynas) on a NAS. The discovery works (find the nas), but fails to actually access any content.

## Expected Behavior
After the discovery, I should be able to select the data I actually want to display (e.g videos)  by browsing the content using various criteria (e.g recent files)  but I can get access to a screen describing the correct content.

## Actual Behavior
I get correctly the first level of server description

- find server, find pseudo categories : video, music, photos)

- In the first level description, it finds pseudo first level categories (recent files, all files, browse)

- But as sson as I want to enter one item of this level it fails displaying either ".." as if there where no content or recursively itself phtos->photos->photos)

The same server can be correctly accessed from the same machine via vlc, upnp av client, and from various android DLNA application (like Hifi cast, bubble UPnp, ....)

## Possible Fix
The actual code for storing/speeding up/caching content retrieval from server is probably broken

### To Reproduce
Install a DMS server on anas and fill it with substantial content (100 GB order of music, photos, videos)

### Debuglog

I already reported this bug to track and debug log is already there. You can retrieve it. If needed as for new log and tell me what flags to select.

### Your Environment
Used Operating system:

 - [ X] Android arm 32 8.1, and 9
 - [X ] Linux amd64 debian unstable
 

 - Kodi version:
**For Linux**, I tested many git version since even before beta1, last tested is described below:
git show
commit d0a7c35877c0978e68c55412cf9e0dcab0916b22 (HEAD -> master, origin/master, origin/HEAD)
Merge: 78b6e289ae a283ecaa2f
Author: Markus Pfau <pfau@peak3d.de>
Date:   Fri Nov 2 01:03:26 2018 +0100

    Merge pull request #14770 from peak3d/videoview
    
    [Android] Wait 2000 instead 500ms until videoview is created

For android I installed several official kodi 18 beta version including at least beta4 with same result.

**Comment by DaVukovic** [comment]
Could you please at least link to your already reported ticket at trac. You can´t expect that we are going to search for an older bug report. So please either link to that ticket at trac or post new debuglog. 

Thanks in advance.

**Comment by EricV2** [comment]
Apparently all data have been cleared. Nice way to lost information about problem. Will post a new debug session when I have time.

**Comment by pkerling** [comment]
> Apparently all data have been cleared.

All trac tickets are still there, nothing was deleted.

**Comment by EricV2** [comment]
Well I logged in and clicked "view tickets" and got no tickets...

**Comment by pkerling** [comment]
There seems to be a rights issue, sorry! We'll try to get it fixed. In the meantime, you can click on "Custom query" and they should show up when you search for them.

**Comment by pkerling** [comment]
Should be fixed, thanks for making us aware of the problem

**Comment by EricV2** [comment]
It is indeed fixed and I accepecessed the trac bug but my memory was wrong : the bug in trac does not contain any log. I probably did it for another UPnP bug I reported for the kodi 17 dev era. So I will put a brand new log here. Any specific debug flag you want me to activate?

**Comment by EricV2** [comment]
Here is a paste of kodi.loh with debug enabled and specifically UPnP traces (only anonymized login/home name)

https://paste.ee/d/0HR1D 

The Nas server has 192.168.8.18 address in the log. clicked first on video NAS to select it, then video container and then on "recent files" container and got only ".." displayed where I have more than 40 items with gupnp-av-cp or vlc.

**Comment by EricV2** [comment]
I can no more reproduce the problem. So something might have fixed it.
