### ISSUE TITLE
Kodi fails to open TV recording if hard drive is asleep

### ISSUE THREAD

**Issue by RKCRLR** [xbmc/xbmc#14801]
### Describe the bug
Here is a clear and concise description of what the problem is:

I use Kodi for OTA PVR recordings on a Nvidia Shield TV.  I use Tvheadend on the Shield as a backend and have a Toshiba Canvio USB 3.0 3TB hard drive connected directly to the Shield to store and view recordings.  The hard drive will go to sleep after about 10 minutes of inactivity.  It takes a few seconds for the hard drive to wake up.  
I can play the recordings OK if the hard drive is awake.  However, I get the "spinning wheel" if I try to start playing recordings while the hard drive is asleep.  The hard drive starts waking up as soon as I try to play the recording but the spinning wheel remains for about 30 seconds.  Once the wheel goes away I either get back to the menu where I tried to play the recording or sometimes I get booted out of the recordings menu.  Once this process has completed I can start playing the same recording.  However, if the recording was previously viewed I no longer have the option to pick up where I left off.  
If I access the files on the hard drive from a file manager (X-plore) within the Shield environment things work normally (the file manager waits for the hard drive to wake up).  
Tvheadend can make scheduled recordings OK.  It wakes the hard drive if it is asleep.  

Update: The problem only occurs if I access the recording through the TV Recordings menu.  Kodi waits for the hard drive to wake up and then starts playing the recording if I access the same recording through the Videos menu.  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi waits for the hard drive to wake up and then starts playing the recording.  

## Actual Behavior

Kodi doesn't wait for the hard drive to wake up when attempting to play a recording while the hard drive is asleep.  

## Possible Fix

Incorporate something similar to waiting for NAS to wake up.  

### To Reproduce

1. On a Shield TV with a USB hard drive attached, attempt to play a partially viewed video while the hard drive is asleep.  
2.Wait for the spinning wheel to go away
3.Play the video (notice there is no option to pick up where playback was left off).  

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/upecogebiv.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 8.0, Shield Experience 7.1
 - Kodi version: Leia Beta 5 (but the problem occurs on all Leia versions and likely earlier Kodi versions)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by RKCRLR** [comment]
I'm now on RC4 and the problem is still there.  
This only seems to effect OTA recordings.  I moved my Tvheadend timeshift folder to the hard drive.  When I select a channel in the guide Kodi waits for the hard drive to wake up and then starts showing live TV.  
It would me nice to get an acknowledgement that this is considered a bug or if there are no plans to address this.  
Thanks

**Comment by pkerling** [comment]
We cannot say either way until someone has investigated it further. I can't guarantee when that will happen as we are all volunteers. We will close the issue if we don't think it's valid.

**Comment by RKCRLR** [comment]
I understand.  Please let me know if you need more information.  Actually, my other bug report (Leia stopping when TV/receiver is turned off/on) is more of a concern to me.

**Comment by RKCRLR** [comment]
Posting some additional information.  This problem only occurs when I try to play the recording through the Live TV Recordings menu option.  If I start playing the recording through any other menu option Kodi will wait for the hard drive to wake up and then start playing the recording.

**Comment by RKCRLR** [comment]
I'm now on 18.5 and this behavior has changed.  
The recording starts playing immediately without the hard drive spinning up (how is this possible?).  The recording will play for a few seconds and the then the light on my hard drive comes on.  The recording plays for a few more seconds and then stops (I get kicked back into the recordings menu).  I can then select the recording again and it plays normally.
