### ISSUE TITLE
QNAP-remote is not working properly anymore

### ISSUE THREAD

**Issue by traeuble** [xbmc/xbmc#14807]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using Kodi on a QNAP-NAS device most buttons of the QNAP-remote are not working. Only the buttons "up" and "down" have the expected result. All other buttons like "enter", "return", "mute"... have no effect.
I don't have further knowledge how the control information of the remote is passed down into the lxc-container where kodi is running in. But since years this functionality was working out of the box for all previous kodi versions.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The full functionality of the remote should work.

## Actual Behavior

Most buttons don't work.

## Possible Fix

The first version having this behavior is the alpha kodi_18.0+git20180422.0201-121cd5c-0xenial
The version kodi_18.0+git20180406.0201-c691ac1-0xenial doesn't have this problem including all previous versions of kodi to my knowledge starting from kodi 15.

I am not in possession of an alpha version between 20180406 and 20180422 to track it down further.

### To Reproduce

Use of kodi alpha 18.0+git20180422 (or later including all beta's) in the QNAP-"linux-station" environment with Ubuntu 16.04.
Linux-station is an lxc container running Ubuntu on the NAS with access to the build in HDMI-port.  

### Debuglog

The debuglog can be found here:
https://paste.ubuntu.com/p/HZTvz5WJQD/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Ubuntu 16.04.5 LTS (lxc-container on a Qnap TS-253A)
 - Kodi version: 18.0-BETA5 Git:20181104-920e823

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Lirc input changed around April 2018. You now need to set the environment variable `LIRC_SOCKET_PATH` if you use a non standard lirc socket. You might want to check into this.

This is of course assuming that your remote is an IR remote and uses lirc.
