### ISSUE TITLE
Library stucks on loading when there is no Internet connection

### ISSUE THREAD

**Issue by axlt2002** [xbmc/xbmc#14817]
**Description**

Kodi stucks on "Loading directory" when it is used without Internet connection.

**Steps to reproduce the bug**

1. Clean installation of Kodi 18
2. Add a sample movie to the Movies library (and retrieve its information through TMDB addon)
3. Exit Kodi
4. Disconnect the computer from Internet (i.e. unplug the Ethernet cable and/or disable WiFi)
5. Run Kodi
6. Enter the Movie library in the main menu of the Home page
7. A popup saying "Loading directory" appears and stays like that...

_Note: the same issue happens if you try to enter the "Recently added", "Genres", "Years", etc. menus from the shortcuts at the top of the Home page. The issue is probably happening also for TV Shows and other contents._

**Setup**

Kodi 18.0 beta 5 x64
Windows 10

**Debug log**

The debug log can be found [here](https://pastebin.com/7ipgjTTR).

**Forum thread**

The related Kodi forum thread can be found [here](https://forum.kodi.tv/showthread.php?tid=337149).

**Comment by pkerling** [comment]
Maybe related to #14811

**Comment by axlt2002** [comment]
> Maybe related to #14811

I think these are two different issues.

For this issue, just consider the situation in which you run Kodi in offline mode on purpose e.g. I use a tablet to watch movies that are locally stored on it (no need for an Internet connection).

**Comment by d3m10n** [comment]
> > Maybe related to #14811
> 
> I think these are two different issues.
> 
> For this issue, just consider the situation in which you run Kodi in offline mode on purpose e.g. I use a tablet to watch movies that are locally stored on it (no need for an Internet connection).

So maybe related to [#14811](https://github.com/xbmc/xbmc/issues/14811)

**Comment by axlt2002** [comment]
Ok, I trust on you experts then...sorry about that.

Hope is going to be solved.

**Comment by garbear** [comment]
I solved similar issues for the add-on browser. The fixes were: https://github.com/xbmc/xbmc/pull/14479. I bet we just need to extend the check for `special://` or `multipath://`

**Comment by axlt2002** [comment]
Yes, I think you got it! :)

I will just wait for the fix then.

Thanks a lot!

**Comment by garbear** [comment]
No one has volunteered to fix this yet, so you should investigate the fix yourself or recruit a dev on the forum.

**Comment by axlt2002** [comment]
Thanks enen92. Does this resolve the issue also for "Last added", "Genres", "Years", etc.? Would be better to have something like "videodb://movies/" to cover all the cases?

**Comment by axlt2002** [comment]
Sorry enen92 for my lack in terminology...what does "vfs paths" mean?

Just to be more clear for me: if I try to enter, for example, the "Last added" movies from the shortcuts widget in the Home screen of Estuary, does your modification include also this case?

**Comment by enen92** [comment]
Virtual filesystem (includes all those paths such as special://, addons://, videodb://, etc) that are virtual and kodi treats internally.

It didn't work for those shortcuts as they are library folders, thanks for reporting. Should also be fixed now.
