### ISSUE TITLE
PVR (Live TV) deinterlacing issue

### ISSUE THREAD

**Issue by axlt2002** [xbmc/xbmc#14816]
Hi All,

I'm bringing again to your attention an issue that was opened last May on track.kodi.tv (https://trac.kodi.tv/ticket/17712) and that it would be great to have solved before the first release of Kodi 18.0. There is also a [related thread](https://forum.kodi.tv/showthread.php?tid=326616) on the Kodi forum that provides some further information.

**Description and steps to reproduce the bug**

If you start to watch a HD 1080i live TV channel, after few seconds the video is no more correctly deinterlaced. Going to the video options and changing the deinterlaced method from DXVA to Off and again to DXVA, makes the video again perfectly deinterlaced (until the channel is changed). The issue reported repeats at every change of channel.

**Setup**

Kodi 18.0 beta 5 x64
Windows 10
AMD graphic card and APU
Argus TV PVR add-on

**Debug log**

The debug log can be found [here](https://pastebin.com/yfhEmvXX). Please note that it refers to an older nightly version of Kodi 18 but the same issue is still present in beta 5.

**Comment by pkerling** [comment]
Hi, please link the trac ticket and next time use the provided issue template :-)

(Reports not following the template might be auto-closed as invalid at some point)

**Comment by axlt2002** [comment]
Thanks for your feedback. I have reported the track ticket number as requested.

I will keep in mind your suggestion about the template. Sorry for the issue.

**Comment by axlt2002** [comment]
Dear @FernetMenta and @afedchin hope you are doing well.

I'm bringing up this issue again since it seems that Kodi 18 is approaching to its release...can you please give it a check? I can provide new debug logs if needed.

Thanks in advance!

**Comment by neeto33** [comment]
Unfortunately I have to report this is still an issue with 18.2
And if anything it's gotten worse.
There is also a strange side effect of going in & turning on/of DXVA sometimes the subtitles is turned on without me going into the subtitles menu.
Also the sometimes the Tone mapping (re)sets itself to Reinhard.
Any channel change or stopping/starting TV/PVR can cause this to happen.

**Comment by AndyGHenderson** [comment]
I too see the issue showing subtitles when switching deinterlacing while watching TV via PVR.

Kodi 18.2 (also occured in Kodi 17, same as OP)
Intel core I3
Integrated HD graphics 4600
NextPVR
Windows 10 32bit fully patched (seen over last two versions)

Andy

**Comment by SelcalHF** [comment]
I'm having this exact same issue on 18.4, any update on this?
