### ISSUE TITLE
Kodi looses network connection (after wifi outage or standby/resume) on Windows

### ISSUE THREAD

**Issue by popy2k14** [xbmc/xbmc#14811]
### Describe the bug
Here is a clear and concise description of what the problem is:

I had an issue that kodi crashed sometimes (once per 1-2 weeks) when comming out of standby.
There was an popup stating DVbViewer PVR addon is offline and than it crashes.
**This seems an windows only issue!**
Here are the references with logs::

https://github.com/manuelm/pvr.dvbviewer/issues/34

It seemes it was no PVR issue, so i created an kodi issue:

https://github.com/xbmc/xbmc/issues/14606

@Rechi jumped on the train and fixed the NPE here:

https://github.com/xbmc/xbmc/pull/14614

The crash was gone but another issue popped up:

https://forum.kodi.tv/showthread.php?tid=336813

The root issue causes kodi to think it's offline and no curl or any other communication is working in this state. The only solution is to restart kodi (NOT windows). When kodi has this issue other windows programs like chrome/explorer are working fine and could communicate without an issue to the outside world.

Other users reported similar issues when using wifi which had an outage.
See references here:

https://forum.kodi.tv/showthread.php?tid=337178
https://github.com/xbmc/xbmc/issues/14661

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi network request should work because windows PC is online!

## Actual Behavior

Kodi network requests fails and it shows online on the system page (see screenshots).

### To Reproduce

It's rather hard to reproduce the issue on my side.
Sometimes it takes 2 weeks that the issue pops up.
@d3m10n can reproduce the issue quickly and also done some tests to proove that no http request is working in this state, see: https://github.com/xbmc/xbmc/issues/14661#issuecomment-436076816

### Debuglog

Please see debug logs from attached issues and mentioned thread above.

### Screenshots 
Here are some links or screenshots to help explain the problem:

Kodi is thinking its connected but curl and so on isnt working:
https://imgur.com/a/qvGJ9hK

thx to @Andystew94

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: WIndows 10 x64 build 1803
 - Kodi version: 18 beta 4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by popy2k14** [comment]
Anything we can do to help find the issue @afedchin @FernetMenta @Rechi ?
As stated, @d3m10n can reproduce the issue easily, logs are in the referenced PVR issue.

I think such an issue would be an showstopper bug for RC release, would'nt it?

thx
pOpY

**Comment by d3m10n** [comment]
Windows 10 1803 64bit
Standalone machine with temporary wifi, without any other network.
Kodi 18 

Without an established wifi connection, http requests on 127.0.01 localhost (pvr, local streaming server) via kodi aren't possible. All other connection on 127.0.0.1 outside of kodi works fine within this state.

Workaround:
I added a loop-back adapter which spoofs a established network connection and kodi runs fine.

**Comment by kib** [comment]
It is really weird that you needed to add a loopback adapter.
In Windows (10) you normally always have a hidden adapter called `Software Loopback Interface 1` with id `1` which is the loopback interface, whether your network cards are installed, installed and connected or not at all.

Could you test whether you have a route to loopback when your loopback adapter is removed and the wifi is disabled ? Eg. open a command prompt as admin and run `route print`. I am interested to see what it shows for you.

**Comment by Rechi** [comment]
@kib 
https://github.com/xbmc/xbmc/blob/41e39d2a96a0188d211764f35e93da825b10d45d/xbmc/platform/win32/network/NetworkWin32.cpp#L186-L191

**Comment by d3m10n** [comment]
@kib 
```
PS C:\WINDOWS\system32> route print
===========================================================================
Liste d'Interfaces
 18...76 da 38 97 31 7c ......Microsoft Wi-Fi Direct Virtual Adapter #3
  4...74 da 38 97 31 7c ......Microsoft Wi-Fi Direct Virtual Adapter #4
 12...74 da 38 97 31 7c ......Realtek RTL8821AU Wireless LAN 802.11ac USB 2.0 Network Adapter
 16...74 da 38 97 31 7d ......Bluetooth Device (Personal Area Network)
  1...........................Software Loopback Interface 1
===========================================================================

IPv4 Table de routage
===========================================================================
Itinéraires actifs :
Destination réseau    Masque réseau  Adr. passerelle   Adr. interface Métrique
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    331
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    331
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    331
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    331
===========================================================================
Itinéraires persistants :
  Adresse réseau    Masque réseau  Adresse passerelle Métrique
          0.0.0.0          0.0.0.0     192.168.43.1  Par défaut
===========================================================================

IPv6 Table de routage
===========================================================================
Itinéraires actifs :
 If Metric Network Destination      Gateway
  1    331 ::1/128                  On-link
  1    331 ff00::/8                 On-link
===========================================================================
Itinéraires persistants :
  Aucun
```

**Comment by kib** [comment]
@d3m10n Thanks for the information.
In the meantime Rechi has identified why Kodi believes it is without network, and a fix is being prepared.
The ticket will stay open until the fix has been merged into the code.
