### ISSUE TITLE
[skin.estouchy] Recent Movies not showing the latest movies added

### ISSUE THREAD

**Issue by robertxgray** [xbmc/xbmc#14813]
### Describe the bug

I'm using an updated OSMC with Kodi 17.6 and the Estouchy skin. On the home screen, the "Recent Movies" list includes just the first 10 movies in alphabetical order. When movies are added to my library, they're not included in the list unless they're in the top of the alphabetical order.

If I select Movies and choose to sort Date added / Descending, the library view shows the latest additions to my library as expected. I also get the same expected behaviour in the Chorus web interface under Movies -> Recently Added.

I found another person reporting the same problem in the forum one year ago, with Kodi 17.4.
https://forum.kodi.tv/showthread.php?tid=315640

## Expected Behavior

Recent Movies should list the new movies in the library.

## Actual Behavior

Recent Movies is showing the top movies in alphabetical order.

## Possible Fix

I found a workaround by editing the line 110 in 
addons/skin.estouchy/xml/IncludesHomeRecentlyAdded.xml

Original
`<content target="movies" sortby="date" limit="10">videodb://recentlyaddedmovies/</content>`

Possible Fix
`<content target="movies" sortby="dateadded" sortorder="descending" limit="10">videodb://recentlyaddedmovies/</content>`

### To Reproduce

1. Select Estouchy as the Kodi skin.
2. Have some movies in your library.
3. Enter the home screen.

## Additional context or screenshots (if appropriate)

The Recent TV Shows and Recent Music lists may have the same problem. I can't confirm because there are only movies in my library.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC 2018.10-1
 - Kodi version: 17.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MartijnKaijser** [comment]
V17 is no longer supported
