### ISSUE TITLE
Seasons poster broken on some skins since Beta 3

### ISSUE THREAD

**Issue by yoshitslc** [xbmc/xbmc#14819]
Show posters show up instead of seasons posters
Since beta3 seasons posters are replaced by show poster in some skins, but it works with Estuary

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Displaying seasons poster in the seasons screen like in Beta2

## Actual Behavior
Displays tv show poster all the same.

## Possible Fix
Some modifications may have been made in the skinning API, I would like to know what are they and how I can modify that ?

**Comment by MartijnKaijser** [comment]
"some skins". Why don't you say exactly which?

**Comment by yoshitslc** [comment]
Because I don't know all of them. But after a little investigation, a saw that Aeon Nox Silvo has been impacted in some views, and I  am using Grid, wich seems not maintened anymore by the author and that's why I want to be able to fix it myself.

**Comment by MartijnKaijser** [comment]
If you want help use the forum. GitHub is for bugs and not for issues about skins we do not maintain
