### ISSUE TITLE
OK dialog box silently overwrites multiline text lines if arguments are emitted

### ISSUE THREAD

**Issue by traveaston** [xbmc/xbmc#14824]
### Describe the bug
Here is a clear and concise description of what the problem is:

When calling xbmcgui.Dialog().ok() with a multiline string as the second argument, the following single line arguments overwrite the multiline lines.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Dialog().ok() should ignore following arguments if second argument (first arg is title) contains newline. (or at least append instead of overwriting)

## Actual Behavior

Dialog().ok() function overwrites text from the second argument with the third and fourth's default value (empty string)

## Possible Fix

(I don't speak C++)  
My calculated trace are these files and functions

ShowOKDialogLines [xbmc/xbmc/messaging/helpers/DialogOKHelper.cpp:39](https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/messaging/helpers/DialogOKHelper.cpp#L39)  
ShowOKDialogLines [xbmc/xbmc/messaging/helpers/DialogOKHelper.h:71](https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/messaging/helpers/DialogOKHelper.h#L71)  
Interface_GUIDialogOK::show_and_get_input_line_text [xbmc/xbmc/addons/interfaces/GUI/dialogs/OK.cpp:50](https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/addons/interfaces/GUI/dialogs/OK.cpp#L50)  
ShowAndGetInput [xbmc/xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/dialogs/OK.h:83](https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/dialogs/OK.h#L83)

It looks like the first file is the issue. It looks to be moving each arg into the array without checking anything (std::move)  
I'm also not sure whether checking would be suited here or somewhere else in the chain.

I wrote a python wrapper to elicit the correct behaviour, if anyone's curious
```python
def wrap_broken_kodi_dialog(title, lines):
    line1 = lines.pop(0)
    line2 = lines.pop(0)
    remaining_lines = '\n'.join(lines)

    xbmcgui.Dialog().ok(title, line1, line2, remaining_lines)

wrap_broken_kodi_dialog('title', ['multi','line','message','works'])
```
[result of python wrapper function](https://i.imgur.com/zppYYWq.jpg)

I've just realised before submitting this that my wrapper works, but still doesn't follow the docs ([here](https://codedocs.xyz/AlwinEsch/kodi/group__python___dialog.html#gaa2e71498b420cb4f58e82a467f27c659)) as only line1 is supposed to be multiline and I'm dumping my remaining multiline string in the last argument (line3).

### To Reproduce

1. Make or modify a python addon with the following code:
```python
import xbmcgui
xbmcgui.Dialog().ok('title', 'multiline1 \n multiline2 \n multiline3 \n multiline4 \n multiline5')
sys.exit()
```
2. Trigger the addon
3. Notice that multiline 2 and 3 are blank

### Debuglog

The debuglog can be found here:

I only gave part of the debug log as it's verbose af  
It starts just before clicking my context menu item, the linebreak is after the dialog box was shown. The remaining is clicking the okay button.  
It's probably useless as I suspect the code is technically doing the right thing.  
I can provide more logs if someone who knows what they're doing think's it's necessary.

14:46:52.496 T:4820137408   DEBUG: Keyboard: scancode: 0x24, sym: 0x000d, unicode: 0x000d, modifier: 0x0
14:46:52.539 T:4820137408   DEBUG: Keyboard: scancode: 0x24, sym: 0x000d, unicode: 0x0000, modifier: 0x0
14:46:52.539 T:4820137408   DEBUG: HandleKey: return (0xf00d) pressed, action is Select
14:46:52.783 T:4820137408   DEBUG: ------ Window Deinit (DialogContextMenu.xml) ------
14:46:52.799 T:123145423253504   DEBUG: Thread LanguageInvoker start, auto delete: false
14:46:52.800 T:123145423253504    INFO: initializing python engine.
14:46:52.800 T:123145423253504   DEBUG: CPythonInvoker(3, /Users/trav/Library/Application Support/Kodi/addons/context.show.runtime/main.py): start processing
14:46:52.827 T:123145420570624 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
14:46:52.850 T:123145423253504   DEBUG: -->Python Interpreter Initialized<--
14:46:52.851 T:123145423253504   DEBUG: CPythonInvoker(3, /Users/trav/Library/Application Support/Kodi/addons/context.show.runtime/main.py): the source file to load is "/Users/trav/Library/Application Support/Kodi/addons/context.show.runtime/main.py"
14:46:52.851 T:123145423253504   DEBUG: CPythonInvoker(3, /Users/trav/Library/Application Support/Kodi/addons/context.show.runtime/main.py): setting the Python path to /Users/trav/Library/Application Support/Kodi/addons/context.show.runtime:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/site-packages/Pillow-3.0.0-py2.7-macosx-10.12-x86_64.egg:/Applications/Kodi.app/Contents/Libraries:/Applications/Kodi.app/Contents/Libraries/lib/python27.zip:/Applications/Kodi.app/Contents/Libraries/lib/python2.7:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/site-packages:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/plat-darwin:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/plat-mac:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/plat-mac/lib-scriptpackages:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/lib-tk:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/lib-old:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/lib-dynload
14:46:52.851 T:123145423253504   DEBUG: CPythonInvoker(3, /Users/trav/Library/Application Support/Kodi/addons/context.show.runtime/main.py): entering source directory /Users/trav/Library/Application Support/Kodi/addons/context.show.runtime
14:46:52.851 T:123145423253504   DEBUG: CPythonInvoker(3, /Users/trav/Library/Application Support/Kodi/addons/context.show.runtime/main.py): instantiating addon using automatically obtained id of "context.show.runtime" dependent on version 2.25.0 of the xbmc.python api
14:46:52.862 T:4820137408   DEBUG: ------ Window Init (DialogConfirm.xml) ------
14:46:52.862 T:4820137408    INFO: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY

14:47:01.270 T:4820137408   DEBUG: Keyboard: scancode: 0x24, sym: 0x000d, unicode: 0x000d, modifier: 0x0
14:47:01.339 T:4820137408   DEBUG: Keyboard: scancode: 0x24, sym: 0x000d, unicode: 0x0000, modifier: 0x0
14:47:01.340 T:4820137408   DEBUG: HandleKey: return (0xf00d) pressed, action is Select
14:47:01.591 T:4820137408   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
14:47:01.604 T:123145423253504    INFO: CPythonInvoker(3, /Users/trav/Library/Application Support/Kodi/addons/context.show.runtime/main.py): script aborted
14:47:01.605 T:123145423253504   DEBUG: onExecutionDone(3, /Users/trav/Library/Application Support/Kodi/addons/context.show.runtime/main.py)
14:47:01.607 T:123145423253504    INFO: Python interpreter stopped
14:47:01.607 T:123145423253504   DEBUG: Thread LanguageInvoker 0 terminating
14:47:01.627 T:123145420570624 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
14:47:02.880 T:123145413619712   DEBUG: Thread JobWorker 123145413619712 terminating (autodelete)

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://i.imgur.com/FUKpVap.jpg
https://i.imgur.com/vNTxLtZ.jpg

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS Mojave 10.14.2 Beta 18C31g
 - Kodi version: 18.0-BETA5-Git:20181103-920e823249

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
a few recommendations:

1) best practice is not to use line-breaks in your strings.
the addon does not know the text width of the ok dialog, so there's no guarantee the part before the line-break even fits on a single line.  
kodi will handle the insertion of line breaks, depending on the text width of the dialog.
worst case scenario, kodi will insert a line break just a word before your harcoded line break.

2) your 'possible fix' (passing three lines instead of one) is kind of deprecated and will potentially be removed in future kodi versions.

**Comment by MartijnKaijser** [comment]
What ronie said is correct.
You either use the multi line option or the separate lines one which is deprecated.

**Comment by MartijnKaijser** [comment]
What you want will not work anyway because you have no idea how big the ok dialog is. Not all skins have such a big ok dialog and only half will be shown.

**Comment by traveaston** [comment]
Are you speaking about horizontally or vertically?  
I was under the impression the dialog will scroll if there are too many lines, which is perfectly okay.  
If you're saying it's not wide enough, I could probably reword to be shorter.

**Comment by HitcherUK** [comment]
Use the [textviewer](https://kodi.wiki/index.php?title=List_of_Built_In_Controls#DialogTextViewer.xml) instead.

**Comment by traveaston** [comment]
Thank you @HitcherUK, this will work for my use case. 

I still think this issue should be fixed, however. Either the documentation for dialog ok is incorrect, or the function behaviour is incorrect.

**Comment by MartijnKaijser** [comment]
@enen92 @romanvm your opinion?

**Comment by enen92** [comment]
I also agree this is not the correct usage of dialogOk, however maybe the function can be extended to support other options (such as receiving a list as the author illustrates). I've reopened the issue for now and will have a look when I have some time.

**Comment by Zomboided** [comment]
I've been using dialog with multiple lines, including \n to show a list of 4 items and am now seeing this.
I see just the first and fourth lines, eg :

xbmcgui.Dialog().textviewer(addon_name, "Disconnected from VPN.\nNetwork location is " + country + ".\nIP address is " + ip + ".\nService Provider is " + isp)

will display :
Disconnected from VPN
<blank line>
<blank line>
Service provider is something

I'd really like to see this fixed as textviewer just is too big a box, and has no ok, which is more friendly for remote controls.

**Comment by ronie** [comment]
potential fix: https://github.com/xbmc/xbmc/pull/15434

**Comment by ronie** [comment]
fixed by https://github.com/xbmc/xbmc/pull/15434
