### ISSUE TITLE
Internal/external subtitles not displayed (Android)

### ISSUE THREAD

**Issue by Jocala** [xbmc/xbmc#14826]
### Describe the bug
Internal/external subtitles are not displayed on Amazon Cube/Nvidia Shield devices

Both internal subtitles and external srt files fail to display on Amazon Cube and Nvidia Shield devices. This issue does not occur on the Mac.
## Expected Behavior
Expected behavior is display is proper display of subtitles

No subtitles are displayed

## Actual Behavior

No subtitles are displayed when subtitles are selected.

### To Reproduce

1. Select subtitle
2.Turn subtitles on
3.Press play

### Debuglog

The debuglog can be found here:

https://pastebin.com/LTDsL59v

Possible related debug data:

12:28:21.506 T:18446744072963119392   DEBUG: CSettingsManager: requested setting (subtitles.enable) was not found.
12:28:21.506 T:18446744072963119392   DEBUG: CSettingsManager: requested setting (subtitles.delay) was not found.
12:28:21.507 T:18446744072963119392   DEBUG: CSettingsManager: requested setting (subtitles.stream) was not found.
12:28:21.507 T:18446744072963119392   DEBUG: CSettingsManager: requested setting (subtitles.browser) was not found.
12:28:21.507 T:18446744072963119392   DEBUG: CSettingsManager: requested setting (subtitles.search) was not found.
12:28:21.508 T:18446744072963119392   DEBUG: CSettingsManager: requested setting (audio.makedefault) was not found.
### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Nvidia Shield TV/Amazon Fire OS
 - Kodi version:18.0-RC1 Git:20181107-5a42446

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
@tamland this seems to be related to your commit here -> https://github.com/xbmc/xbmc/commit/fda4c81bf18b89faca131b6a9eee8e80517ffe55

It looks like the subtitle setting strings don't actually have a definition. Did you forget to add them?

**Comment by Jocala** [comment]
I'm not sure how this is related to my report.

**Comment by MartijnKaijser** [comment]
I'm sure a developer knows when it's related or not.

**Comment by Jocala** [comment]
Perhaps I misunderstood, I thought I was being asked to add subtitle setting strings. Anyway, I hope the report helps.

**Comment by tamland** [comment]
@lrusak I don't think that's related. Afaik nothing settings related was changed in that commit. Everything's there, it's just moved.

**Comment by lrusak** [comment]
@tamland grepping the code only shows this one reference

```
$ find xbmc/ cmake system -type f | xargs grep -E -i 'subtitles.enable|subtitles.delay|subtitles.stream|subtitles.browser|subtitles.search|audio.makedefault'
xbmc/video/dialogs/GUIDialogAudioSettings.cpp:#define SETTING_AUDIO_MAKE_DEFAULT             "audio.makedefault"
xbmc/video/dialogs/GUIDialogSubtitleSettings.cpp:#define SETTING_SUBTITLE_ENABLE                "subtitles.enable"
xbmc/video/dialogs/GUIDialogSubtitleSettings.cpp:#define SETTING_SUBTITLE_DELAY                 "subtitles.delay"
xbmc/video/dialogs/GUIDialogSubtitleSettings.cpp:#define SETTING_SUBTITLE_STREAM                "subtitles.stream"
xbmc/video/dialogs/GUIDialogSubtitleSettings.cpp:#define SETTING_SUBTITLE_BROWSER               "subtitles.browser"
xbmc/video/dialogs/GUIDialogSubtitleSettings.cpp:#define SETTING_SUBTITLE_SEARCH                "subtitles.search"
xbmc/video/dialogs/GUIDialogSubtitleSettings.cpp:#define SETTING_MAKE_DEFAULT                   "audio.makedefault"
```

**Comment by tamland** [comment]
That's a define. The defined identifier is referenced multiple times in that file.

**Comment by tamland** [comment]
@lrusak These are some special settings, not gui settings. That's why they arn't in settings.xml.

**Comment by lrusak** [comment]
@tamland do you see the problem though? There are being set and retrieved through the settings manager which requires a setting definition in `settings.xml` or similar. Or am I missing something?

**Comment by xodidox** [comment]
I reported this issue twice before, but never got attention from developer. This issue exist for both Krypton and Leia (never used previous version of Kodi though).

There are more information in the forum threads with my test:

https://forum.kodi.tv/showthread.php?tid=326007
https://forum.kodi.tv/showthread.php?tid=335747

**Comment by msj33** [comment]
I had similar subtitle issues one of the test builds from november.

Subtitles where enabled and you could toogle between different languages, but it never showed in the mkv playback.

Rolled back to official stable and subs worked just fine again on the exact same movie.

Unfortunately I do not have any kodi logs from my Xiaomi mi box 3(amlogic 905X).

**Comment by elguapo361** [comment]
I'm seeing the same issue, in RC1, RC2 on NVIDIA Shield.

I've tried using internal, external subs. I've tried stripping all other sub tracks in the mkv file. Subs work fine directly in Plex and Emby. Subs not working directly in Kodi, EmbyCon, or Plex for Kodi addons, all of which I believe use the Kodi video player.

**Comment by enen92** [comment]
@elguapo361 @msj33 @xodidox @jocala what is the current state of this? Have you tried to replicate using a Matrix nightly?
I guess this is fixed already otherwise we'd have probably a bunch of bug reports for this exact same issue :)

**Comment by enen92** [comment]
Closing as no feedback was provided, this is likely fixed already.
