### ISSUE TITLE
Please order the installed addon list alphabetically

### ISSUE THREAD

**Issue by Wintermute0110** [xbmc/xbmc#14825]
### Describe the bug
When Kodi Leia starts, a list of installed addons is printed on the log like this
```
 Running the application...
19:07:30.467 T:7188  NOTICE: ES: Starting UDP Event server on port 9777
19:07:30.467 T:7188  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
19:07:32.747 T:8028  NOTICE: Skin Helper Service --> WebService - start helper webservice on port 52307
19:07:32.747 T:4120  NOTICE: Skin Helper Service --> Skin Helper Service version 1.1.3 started
19:07:41.621 T:6128  NOTICE: ADDON: resource.images.moviegenreicons.transparent v0.0.6 installed
19:07:41.621 T:6128  NOTICE: ADDON: game.libretro.beetle-bsnes v0.9.26.1 installed
19:07:41.621 T:6128  NOTICE: ADDON: xbmc.json v9.7.2 installed
19:07:41.621 T:6128  NOTICE: ADDON: metadata.common.fanart.tv v3.5.0 installed
19:07:41.621 T:6128  NOTICE: ADDON: script.module.autocompletion v1.1.2 installed
19:07:41.621 T:6128  NOTICE: ADDON: game.controller.ps.guncon.japan v1.0.8 installed
...
```

## Expected Behavior
It would be very nice if this list is printed in alphabetical order to quickly find a particular addon and version.

## Actual Behavior
The addon list is in a random order.

### To Reproduce
Install Kodi Leiba beta 5, start Kodi, see kodi.log

### Your Environment
Used Operating system: tested in Windows 7 64 bit with Kodi Leia Beta 5

**Comment by MartijnKaijser** [comment]
Sadly this is not possible due to the used code library

**Comment by Wintermute0110** [comment]
OK, but maybe this idea could be interesting for the future ...

**Comment by pkerling** [comment]
Found a way to do it

**Comment by MartijnKaijser** [comment]
Yep. Seems i had old info cause in the past it wasn't possible for some reason.
Will be added to RC1

**Comment by pkerling** [comment]
@MartijnKaijser Yeah I remember talk about that, dunno the technical reason though. Well it works now :-)
