### ISSUE TITLE
Track naming template (Label Formatting) not working properly

### ISSUE THREAD

**Issue by NeroRome** [xbmc/xbmc#14823]
### Describe the bug
The Label Formatting in the "Track naming template" is not working properly.

Not even the example of the [wiki](https://kodi.wiki/view/Settings/Media/Music#Track_naming_template) is working.

## Expected Behavior
The formatting should work correct, e.g. the example of the wiki should work and also my samples (screenshots comming later).

### To Reproduce

1. Enter a [formatted](https://kodi.wiki/view/Label_Formatting) "Track naming template"
2. Check result in Music Library (Albums)

### Debuglog

No debuglog. Just screenshots.

### Screenshots 
Here are some links or screenshots to help explain the problem:

NOK:
![screenshot_2018-11-08_01-06-25](https://user-images.githubusercontent.com/44007403/48170227-da791280-e2f6-11e8-835a-4dccf4820c4a.png)
![screenshot_2018-11-08_01-07-29](https://user-images.githubusercontent.com/44007403/48170229-df3dc680-e2f6-11e8-9c47-703a138d3578.png)

NOK:
![screenshot_2018-11-08_01-08-37](https://user-images.githubusercontent.com/44007403/48170234-e533a780-e2f6-11e8-90ff-81c3685f3fc9.png)
![screenshot_2018-11-08_01-09-16](https://user-images.githubusercontent.com/44007403/48170236-e8c72e80-e2f6-11e8-957a-fdf1bda51b1f.png)

OK:
![screenshot_2018-11-08_01-10-05](https://user-images.githubusercontent.com/44007403/48170243-ed8be280-e2f6-11e8-9410-1c128e80b0c1.png)
![screenshot_2018-11-08_01-10-50](https://user-images.githubusercontent.com/44007403/48170245-f086d300-e2f6-11e8-87fa-ab74ee5429b1.png)

NOK:
![screenshot_2018-11-08_01-12-18](https://user-images.githubusercontent.com/44007403/48170254-f5e41d80-e2f6-11e8-903f-8f24e7cba299.png)
![screenshot_2018-11-08_01-13-17](https://user-images.githubusercontent.com/44007403/48170256-f977a480-e2f6-11e8-9deb-a9a2af10fe52.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux Mint Xfce 19
 - Kodi version: 17.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Kodi version 17.6 won't be getting any updates. Please updated to Kodi 18 beta5 and see if your problem persists.

**Comment by NeroRome** [comment]
If there are no updated for 17.6 this is OK.
I'll not update to the beta version now.

It's a common way to report bugs in the actual released version. It's generally not usual to request a beta version.
If it's already fixed in v18, it's fine! I was not able to find a fixing for that.

**Comment by NeroRome** [comment]
I reckon a bug at the RegEx in [LabelFormatter.cpp](https://raw.githubusercontent.com/xbmc/xbmc/18.0b5-Leia/xbmc/utils/LabelFormatter.cpp): `CLabelFormatter::AssembleMask`.
This function was not changed (17.6 vs. 18.0b5).
For me the RegEx is too complicated and C++ is also not my language.

**Comment by DaVukovic** [comment]
Could you please, for a test, try to move characters like "." and ":" out of the square brackets? Like:

`[%N]. %A - [[B]%T[/B]]`

As our wiki doesn´t show that as well.

**Comment by NeroRome** [comment]
> 
> Could you please, for a test, try to move characters like "." and ":" out of the square brackets? Like:
> 
> `[%N]. %A - [[B]%T[/B]]`
> 

I've tried this expression and it is working.

Note: I'm currently testing it in Kodi 17.6 on Windows 10 but it seems the results are the same like on Linux.

![kodi - track naming template 01a](https://user-images.githubusercontent.com/44007403/48296718-ae969200-e49a-11e8-98d6-73dbdbacb50d.PNG)
![kodi - track naming template 01b](https://user-images.githubusercontent.com/44007403/48296722-b5bda000-e49a-11e8-839b-43cb6ced2a19.PNG)

There are expressions which are okay but, not all.

---

Finally I'd like to have the Track-Number (light), than the **Title** (bold) and the _Artist_ (italic) at the end, with useful delimiters.

This is the expression I'd like to have:
![kodi - track naming template 02a](https://user-images.githubusercontent.com/44007403/48296777-1f3dae80-e49b-11e8-9c1b-a9c4b8b15622.PNG)
![kodi - track naming template 02b](https://user-images.githubusercontent.com/44007403/48296781-29f84380-e49b-11e8-979f-37b7e4bc0400.PNG)
![kodi - track naming template 02c](https://user-images.githubusercontent.com/44007403/48296783-2ebcf780-e49b-11e8-8dbf-11fd43ac1e47.PNG)
Note: It seems to work in the settings menu (when the template entry is not selected: you can clearly see bold and italic), but not in the music library.

I also tried it with the static text outside the square brackets, but it's also not working.
![kodi - track naming template 03a](https://user-images.githubusercontent.com/44007403/48296809-c3bff080-e49b-11e8-99f9-f4b5b176600c.PNG)
![kodi - track naming template 03c](https://user-images.githubusercontent.com/44007403/48296811-c6bae100-e49b-11e8-9db1-97e48a0ab9ee.PNG)

I also tried some other version to get my favorite style, but I didn't get it working.

---

In my point of view my expressions should be correct (based on the comments in `LabelFormatter.cpp` and [Label Formatting](https://kodi.wiki/view/Label_Formatting)).
It should be possible to put static text in the squared brackets and this also makes sense, e.g. show the _point_ only if the track number is filled in the metadata. If you put the point outside the brackets it should only be shown if the left and right metadata blocks are filled. If the title (for example) is not filled then there will be no point shown. (This might be even more critical if you have the artist before the title because maybe more often the artist than the title is missing, but it's also possible to don't have the title, e.g. on opera albums where you don't have the title for all tracks).
Also the default expression has static text in the brackets.

**Comment by DaVukovic** [comment]
I did some tests myself now and what I find out is, if you are using two tags directly next to each other, for example:

`[[B]%N[/B]]. [[B]%A[/B] - %T`

It does not work and I get similar outputs like you see.

If the tags are written like:

` [[B]%B[/B]]. %A - [[B]%T[/B]]` 

It works like a charm (at least for bold, italic and color). So there seems to be a problem if two formatting tags/labels are used directly after another.

**Comment by NeroRome** [comment]
I looked to the RegEx a little bit deeper.
The problem is the RegEx itself or the usage of the square brackets for both, formatting and selection of metadata.
The RegEx is quite straightforward and is just looking for matches between opening and closing square brackets. It doesn't take care of hierarchy, i.e. to have the same number of closing than opening brackets. So it's not possible to use formatting in all cases, independently if the formatting is in the metadata block or outside.
I think it's not possible to fix this issue with an easy change from a greedy to an ungreedy expression.


My favorite expression now would be: `[[LIGHT]%N. [/LIGHT]][[B]%T[/B]] - [[I]%A[/I]]`

I did some [tests](http://regexr.com) of the expression.
As you can see, the first matching is too long.
![kodi - track naming template ii 2 01b](https://user-images.githubusercontent.com/44007403/48596932-67594700-e95b-11e8-9371-4d489f0f6924.PNG)


After several trials I found a quite good workaround _for me_. I use a metadata mask which doesn't exist (for my) music files to force the end of a matching:
`[[LIGHT]%N. [/LIGHT]]%X[[B]%T[/B]]%X[[I] - %A[/I]]`
I've used `%X` (Bitrate) here.
As you can see, now we have 3 matchings (one for each relevant metadata mask).
![kodi - track naming template ii 2 02](https://user-images.githubusercontent.com/44007403/48596620-20b71d00-e95a-11e8-9341-9c2fb96b2cb6.PNG)
Note: Groups 2 (prefix), 4 (metadata mask) and 5 (postfix) will be used (see [`CLabelFormatter::AssembleMask`](https://github.com/xbmc/xbmc/blob/a9a7a20071bfd759e72e7053cee92e6f5cfb5e48/xbmc/utils/LabelFormatter.cpp#L405))


With this expression I (nearly) get my favorite layout:
![kodi - track naming template ii 1 01](https://user-images.githubusercontent.com/44007403/48596977-a8e9f200-e95b-11e8-8a89-68a2cfb1dccd.PNG)

![kodi - track naming template ii 1 02](https://user-images.githubusercontent.com/44007403/48596983-b30bf080-e95b-11e8-8e07-fded575d4280.PNG)

![kodi - track naming template ii 1 03](https://user-images.githubusercontent.com/44007403/48596989-b7380e00-e95b-11e8-8bff-e02e2833ac9c.PNG)

Note: The best position for the delimiting hyphen ("`-`"), between title and artist, in the expression would be between the metadata blocks for title and artist, but outside. So the hyphen would only be displayed if both are filled. Because of the non-existing `%X` I have to give the hyphen as prefix (or postfix) into a metadata block.

---

Even if I have a solution that fits my requests, it's just a workaround.
The basic _problem_ seems to be the usage of square brackets for both, metadata and formatting.
I'm sure it's possible to find a solution with a better regular expression to handle also this problem but by now I didn't find it. Hopefully the expression will not be too complicated (i.e. it should still be easy to read/understand and have a good performance).
