### ISSUE TITLE
Power Save display sleep (no signal) does not work if screensaver is also used, it used to work.

### ISSUE THREAD

**Issue by xekon** [xbmc/xbmc#14833]
### Describe the bug
First goto settings / interface / screensaver / set screensaver mode dim, wait time 1 minute.
Next go to settings / system / power saving / set put display to sleep when idle, set to 5 minutes.

## Expected Behavior
The screensaver should dim at 1minute, then at 5 minutes the display should go into "no signal mode" allowing the tv to power off according to your tv "no signal" settings (mine is set to turn off after 15 minutes of no signal.)

## Actual Behavior
The screen does not go into "no signal mode" at the 5 minute mark, instead it goes blank for a second, like it tried, but then goes back to the dim screensaver, and stays on indefinitely.

## Possible Fix
Currently if you set Screensaver to "none" instead of dim, the power saving feature will work. So I believe the Screensaver may be the culprit. Furthermore this worked properly under Kodi 17.

### Your Environment
Used Operating system:
 - Linux, Ubuntu 18.04 with Kde Plasma
 - Kodi version: 18 beta5 / latest

### Debug log

[https://paste.kodi.tv/zuxahinoni.kodi](https://paste.kodi.tv/zuxahinoni.kodi)

**Comment by pkerling** [comment]
To explain: That it is easily reproducible on your system does not mean that this is the case everywhere - for example it might be DE-dependent. Anyway, looking at a debug log to get a better idea of your environment is usually one of the first things we do when analyzing a bug. I'm not sure what part of "A debuglog is always mandatory when creating an issue" (stated in the template) is unclear.

Done rambling now ;-)

**Comment by candrews** [comment]
I'm seeing the same behavior:
* Screensaver comes on
* 5 minutes pass
* Screen blinks (turns black for a moment)
* Screensaver re-appears - but is now frozen. I'm using Kaster and the image no longer changes and the time in the bottom right never does again either.

I have debugging logging enabled and this what is logged when that blink happens when the screen should be turning off:
```
17:01:10.645 T:139968889702976    INFO: DPMS: enabled power-saving mode SUSPEND
17:01:10.645 T:139968889689856   DEBUG: CAnnouncementManager - Announcement: OnDPMSActivated from xbmc
17:01:10.646 T:139968889689856   DEBUG: GOT ANNOUNCEMENT, type: 4, from xbmc, message OnDPMSActivated
17:01:10.646 T:139968889702976   DEBUG: started alarm with name: sssssscreensaver
17:01:10.647 T:139968743827200   DEBUG: Thread AlarmClock start, auto delete: false
17:01:10.743 T:139965916808960  NOTICE: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from xbmc/GUI.OnDPMSActivated: null
```
There aren't any messages for a minute before or a minute after.

I'm using current master a948f998d91724407ab90a89ddc0ae2745021aa0

**Comment by pkerling** [comment]
Can reproduce, DPMS also broken for me.

@FernetMenta something come to mind or should I bisect?

**Comment by pkerling** [comment]
Note: also happens with screensaver disabled

**Comment by xekon** [comment]
For me if I set the screensaver to None then my TV shuts off like it should.... let me know if there is anything else you need from me.

**Comment by pkerling** [comment]
> I sincerely hope those aren't different bugs :-(

They are.

Anyway, please test #14845.
