### ISSUE TITLE
No navigation on partial recordings and videos

### ISSUE THREAD

**Issue by mrblond18** [xbmc/xbmc#14835]
I often start watching PVR recordings before they have finished downloading. In Krypton I was always able to start the video and navigate by pressing the right button a few times to skip forward a certain amount of time. The seeking took more time than normal because the mkv file was not finished. Pressing up did not do anything because it is unable to determine the length of the video and therefore not able to calculate how much to skip forward.

I recently installed Leia Beta3 in Libreelec and I can still play these files that are still recording but I can not navigate at all, even not pause. I can only stop the video.

I reproduced the problem under Ubuntu 18.04 with Kodi 18 beta 5

This is of course unwanted behavior. 

## Expected Behavior
Being able to skip forwards in a .mkv PVR recording that is still running.

## Actual Behavior
Pressing either of the video playback navigation buttons does not do anything.

## Possible Fix
The behaviour was as expected in Kodi 17.6.

### To Reproduce
1. Start a recording in TVHeadend
2. While the recording is still running open the file in Kodi via Video files.
3. Press forward in video navigation, nothing happens.

### Debuglog
The debuglog can be found here:
https://pastebin.com/ENxqA2Cy

interesting lines:
16:21:12.666 T:140517726864320   DEBUG: OnPlayMedia smb://NUC/Data/Data/Media/Video/TV-Recordings/Pauw2018-11-09.mkv

16:21:15.944 T:140517207611136   DEBUG: LIRC: - NEW 000000037ff07bde 00 KEY_RIGHT mceusb (KEY_RIGHT)
16:21:15.955 T:140517726864320   DEBUG: HandleKey: 168 (0xa8, obc87) pressed, action is StepForward

and then nothing happens.

### Screenshots 
none

## Additional context or screenshots (if appropriate)
none

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04
 - Kodi version: Kodi Leia beta 5

**Comment by FernetMenta** [comment]
recodings in progress don't work with mkv. if you experienced anything different in the past, it was only by chance.
it works with ts files, because those don't have an index.

**Comment by mrblond18** [comment]
It might have been by chance, but I have used the functionality succesfully on Kodi 17 on OSX, Debian, Windows and iOS. It was working without problems there.

For me it would increase the WAF significant...

**Comment by FernetMenta** [comment]
btw: you should not open tvh recordings through kodi video files but via pvr recordings. did you try this?
