### ISSUE TITLE
External subtitles not in the list when "Play from here" is used

### ISSUE THREAD

**Issue by arthur-liberman** [xbmc/xbmc#14841]
### Describe the bug
When I use "Play from here" with content located on a remote machine (SMB, FTP shares) that has external subtitles, they are not in the subtitle list, and can't be selected.
This does not reproduce when playing the same content from a local folder.
Internal subtitles are still there and can be selected.
When selecting "Play", both external and internal subtitles are available as expected.

## Expected Behavior

Start playback with "Play from here", then select an external subtitle.

## Actual Behavior

Start playback with "Play from here", external subtitles are not in the subtitle list.

### To Reproduce

1. Setup a folder with video and matching subtitle files on a remote machine (tested with SMB and FTP shares)
2. Right click a file, select "Play from here".
3. Look in the subtitle options dialog and see that the external subtitles are missing.

### Debuglog

The debuglog can be found here:
https://pastebin.com/iQg4Wu2k

### Screenshots 

Regular playback, works as expected:
![image](https://user-images.githubusercontent.com/502466/48302599-f521d600-e506-11e8-84fd-45c496778272.png)

"Play from here"
![image](https://user-images.githubusercontent.com/502466/48302608-0e2a8700-e507-11e8-925b-ed9264cf82ae.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64bit 
 - Kodi version: 9th Nov 64-bit nightly Kodi build.

**Comment by Meliox** [comment]
I can also confirm this bug on windows 10, kodi 18.0-beta3 git 20181002

**Comment by DaVukovic** [comment]
Could someone please confirm if this issue is fixed now?
@arthur-liberman 
are you still able to reproduce it?

**Comment by arthur-liberman** [comment]
@DaVukovic I'll have to test it out, I'll try to do it today after work.

**Comment by arthur-liberman** [comment]
@DaVukovic Just tested on the latest 64-bit nightly. "Play from here" seems to work as expected now.

**Comment by enen92** [comment]
Confirmed fixed by the reporter
