### ISSUE TITLE
Losing Resume Point once leaving directory when play next file automatically is ticked.

### ISSUE THREAD

**Issue by mazeyx** [xbmc/xbmc#14847]
### Describe the bug
Here is a clear and concise description of what the problem is:

start watching something you get a resume point if you exit the video. you can resume multiple times fine but as soon as you leave the directory of the show it loses its video resume point so you need to start from the beginning again.

if you turn off play next video automatically then everything works fine you can leave and reenter and the video resume point is not lost. but with play next video automatically its broken and loses resume point once you leave the directory it also seems to only affect library added content in "tv shows" and "movies" if you browse via video tab and play video and leave reenter its fine also even with play next video automatically enabled. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

resume point should not be lost reset regardless if you leave the directory like old 17.6 behaviour hence we have some regression here which has appeared in all v18 builds alpha 1+ and has never been fixed.

## Actual Behavior

resume point is lost when you leave the directory if play next file automatically is ticked.

## Possible Fix

i wish i knew this is driving me crazy i assume its to do with play next file automatically code as with it unticked it all works fine.

### To Reproduce

1.  home screen select TV Shows hit enter the tv shows are listed pick any,  
2. episode list shows up with episodes for that tv show. start it skip forward 1/2 way now press stop, youll see a resume point.
3. now press back to exit episode list back to tv shows listing now select that tv show again. the episode you skipped 1/2 way through the resume point is lost if you select it now it starts from the beginning. 

### Debuglog

The debuglog can be found here:
https://paste.ubuntu.com/p/fMnKJMhsS5/
https://paste.ubuntu.com/p/5kXFkcMSnC/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

https://trac.kodi.tv/ticket/17857
https://forum.kodi.tv/showthread.php?tid=331246

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] Linux
 - [x] OSX
 - [x] Raspberri-Pi
 - [x] Windows
 - [x] Windows UWP

affects all platforms.

 - Operating system version/name:
 - Kodi version: 
v18 alpha1 -> beta 5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Fixed in RC1.
