### ISSUE TITLE
Kodi does not properly clear calibrated area when video aspect ratio differs to gui aspect ratio

### ISSUE THREAD

**Issue by fritsch** [xbmc/xbmc#14849]
### Describe the bug
Here is a clear and concise description of what the problem is:
When  one uses kodi's internal Calibration functionality, because of the TV has no setting to compensate over / underscan the screen is not properly cleared when starting certain movies. It seems like that video rendering produces an issue if the aspect ratio of the video (W divided by height) is bigger than the aspect ratio of the gui (W divided by H). So with a calibrated: 1000 x 900 gui and a video playing with 1000 x 800 the top and bottom of the screen (50 pixels on top, 50 bottom) are not cleared correctly and artefacts appear (see attached screenshot).

## Expected Behavior
Kodi should properly clear the screen which it is responsible for. This means the whole region inside the calibrated screen.

## Actual Behavior
When calibrating kodi, the GUI is properly rendered in the new dimensions. Meaning the full image is properly presented on screen and the gui image is filling the entire calibrated area, but when starting videos with different aspect ratio, bottom / top / left / right are not properly cleared and leave artefacts on screen.

## Possible Fix
The entire screen managed by kodi should be properly cleared when rendering videos.

### To Reproduce
1.) Open the calibration screen and do some calibration, e.g. move left, right and top and bottom borders towards the middle. For testing purpose 20% each is a nice benchmark to directly see the artifacts
-> Result: You now see kodi's gui moved into the middle of the screen with proper black bars around
2.) Play a video (please stay on the same resolution / refreshrate). Use a full hd video where the blackbars were not encoded, e.g. 1920x800 or something like that.
-> Result: The upper / lower parts of the screen produce artifacts, e.g. parts of the GUI still appear during rendering.
### Debuglog
Showing calibration and video playback can be found here: http://paste.ubuntu.com/p/VWFdVdP46w/

### Screenshots 
Here are some links or screenshots to help explain the problem:
![bildschirmfoto von 2018-11-11 11-45-05](https://user-images.githubusercontent.com/1089309/48311935-847ec600-e5a7-11e8-91d9-c82bda268945.png)
![bildschirmfoto von 2018-11-11 11-45-29](https://user-images.githubusercontent.com/1089309/48311942-93657880-e5a7-11e8-88c4-41017c2bc086.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04 running VAAPI
 - Kodi version: 18.0-BETA4 Git:20181021-17dc0bc165-dirty (still present in current master as of today, including beta5)

**Comment by FernetMenta** [comment]
![image](https://user-images.githubusercontent.com/576009/48312019-c3614b80-e5a8-11e8-85b7-97410c3130ca.png)

there is much more going wrong with calibrations :)

**Comment by fritsch** [comment]
Reverting 6248c15f8d6aab5cf8ad80c5629466fdd39bf35c fixes the issue for me:http://paste.ubuntu.com/p/z5jRZt8wgq/ (hack compiled to compensate advancedsettings gone).

**Comment by fritsch** [comment]
This will fix the issue: http://paste.ubuntu.com/p/g67mMXkd53/ we only clean what is inside the area we are responsible for, properly intersecting the non covered regions. This would "legally" still produce what fernet posted.

Question is: Do we want to start properly "drawing black quads" on the entire area?

**Comment by fritsch** [comment]
Fix was updated after discussion with @FernetMenta to blacken the entire window area that is not repainted by the video (top, bottom, left, right).

Result:
![bildschirmfoto von 2018-11-11 14-46-53](https://user-images.githubusercontent.com/1089309/48313730-daac3300-e5c0-11e8-9dd0-d37b95c1319a.png)
