### ISSUE TITLE
Crash after display switch

### ISSUE THREAD

**Issue by TeHaX** [xbmc/xbmc#14843]
### Describe the bug
Here is a clear and concise description of what the problem is:

Now Kodi v18 is in RC state i would like to report a constant crash which happens since V18 alpha. I use a Windows 10 HTPC connected to Denon Receiver X7200WA with two monitor out together with a TV and Beamer connected over HDMI and an analog (VGA) 2nd HTPC case 4,3" display to my nvidia GTX1050TI over displayport 1.4 with an Rankie DisplayPort (DP) to VGA adapter. Same issue when 4,3" case display is connected with Intel cpu i3-7100 internal HD graphic over vga port.
Kodi crash when getting back from sleep after standby or when i want to switch from my TV to Beamer and vice versa. I notice that in the time from switching or come back from sleep the Windows desktop move for less than some seconds to the case display (but not in fullscreen, only in window). After the TV or Beamer have the desktop back Kodi crashes and looks like the picture below. 
I tried in settings to use fullscreen or not, disable other displays but nothing works.

### To Reproduce

1. Kodi is in fullscreen
2. use windows hotkey win+p to switch to 2nd display
3. switch back win+p to enhanced or pc-screen

### Debuglog

The debuglog can be found here:
https://paste.ubuntu.com/p/wTM3YmCwV6/

### Screenshots 
Here are some links or screenshots to help explain the problem:

<a href="https://imgur.com/lmMSXW8"><img src="https://i.imgur.com/lmMSXW8.png" title="source: imgur.com" /></a>

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows 10
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.0-RC1 Git:20181106

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Heinrich711** [comment]
I have the exact same problem except under different but similar circumstances - when exiting an external player like MPC-BE after either 4K iso or 3D iso. I have tried multiple drivers, multiple skins, all sorts of adjustments to refresh and blanking times etc. The only thing that varies is the size of the painted interface once it's reduced to a postage stamp.

**Comment by kozamek** [comment]
Yeah i Got this behavior on Xbox one, I was disconect from live and kodi change to windowed mode. To solve a i have conect USB keyboard to Xbox one and use shortcut \ to go back on fullscren mode.

**Comment by anrxc** [comment]
I've been using v17, then v18 nightlies... and then just around the time of the alpha Kodi started crashing on display switches. 

To reproduce 1: 
- I have secondary HDMI display (LCD TV) with Kodi in fullscreen
- I have primary DisplayPort display (LCD Monitor)
- I decide to shut off TV, Kodi automatically moves to the primary display now
- Old behavior: Kodi keeps functioning on the new display
- New behavior: Kodi crashes a few seconds after it moved it self

To reproduce 2:
- I have HDMI display (LCD TV) with Kodi in fullscreen
- I shut off TV in the evening
- Old behavior: Kodi is still in fullscreen when I turn on TV in the morning
- New behavior: Kodi has crashed when TV was shut off


Software: Windows 10, Kodi 18 RC1
Hardware: Nvidia GTX1080Ti, Driver: 390.65
Debug log, stack trace and crash log: Attached.
[kodi_crashlog-18.0-RC1_Git_20181121-314c302559.zip](https://github.com/xbmc/xbmc/files/2611360/kodi_crashlog-18.0-RC1_Git_20181121-314c302559.zip)

**Comment by DeckardCain2014** [comment]
I have the same issue. Also described it in the forum (https://forum.kodi.tv/showthread.php?tid=337932)

**Comment by e1d1s1** [comment]
You can reproduce the same behavior on Windows 10 if you "switch windows user". If you leave Kodi open, enter the windows login screen, and then log back in, the Kodi window will rescale incorrectly in exactly the same way.

**Comment by afedchin** [comment]
please enable _component-specific logging_ and specify _Verbose logging of **Windowing** component_. then try to reproduce the issue and provide new debug log

**Comment by TeHaX** [comment]
Thanks for  your  answer. Enclosed some logs with crash while turning off or on TV or Beamer. Switching to window mode Kodi crash too (log no.3+4).  
1. [https://paste.kodi.tv/pecepolemu.kodi](url)
2. [https://paste.kodi.tv/uzorariney.kodi](url)
3. [https://paste.kodi.tv/vaxaticima.kodi](url)
4. [https://paste.kodi.tv/cumakabewi.kodi](url)
Strange but i can´t reproduce the false window as seen in my first post. I have no entries in whitelist. Seems to work now but i don´t know if it works too after wake up from S3 sleep next day. 
Please let me know if you need more.

**Comment by TacoVerhagen** [comment]
Same problem here. PC connected to Receiver to TV.
Small catch, it seems to happen after the SECOND sleep. Start Kodi, Sleep, Wake up (90% change this works), Sleep again, Wake up => Kodi Crash

https://paste.kodi.tv/zosozezesu.kodi

Tested this without the receiver, same results. I do have a CEC adapter. Graphics are supplied through a ryzen 2400G iGPU

**Comment by erikpa1** [comment]
Same problem (Kodi Leia), i have acer notebook with 1050ti  and when i move kodi window to another screen (which runs on different graphic card because  extern monitor runs on nvidia card) with playing video it will crash. when i stop video at first there is no problem

**Comment by dmonch** [comment]
I am having the same problem.   Using a 4k TV and a 4k Monitor, switching either one on or off causes Kodi to crash. Kodi v18.3 "Leia" for Windows 10.

**Comment by Kiristiba** [comment]
I have the same issue in Windows 10 with an i7-8700, 1x LCD (primary) and 1x Samsung TV (secondary). When I turn off the TV, Kodi crashes. Happens even with the latest Kodi 19 nightly :'(

**Comment by phunkyfish** [comment]
@TeHaX is this still an issue today?

**Comment by TeHaX** [comment]
Until i used a case with second display the issue was still present! Since four months i changed HTPC case without display so i am not be able to confrim this from today point of view.

**Comment by phunkyfish** [comment]
Can anyone else on the the thread confirm if this is still an issue?

**Comment by Kiristiba** [comment]
I just checked the latest nightly of Kodi 19 and the issue ist still there.

**Comment by erikpa1** [comment]
Still there problem is mainly when you switch from 1920x1080 to different size  secondary monitor (maybe problem with switching between graphics cards or resolition itself)

**Comment by MichalK6677** [comment]
The same issue on 19 RC1 Matrix.

**Comment by arkonbob** [comment]
Still present in 19.0 for me, on Linux/Xorg with 1 HDMI TV and 1 mirrored virtual head for VNC. Crashes frequently when the TV is turned off and on again.
