### ISSUE TITLE
Loosing watched state if refreshing the informations

### ISSUE THREAD

**Issue by M2k80** [xbmc/xbmc#14850]
### Describe the bug
Here is a clear and concise description of what the problem is:

you have a movie or a series with old/wrong informations, because it was not availble or not translated when you added your series, so you want to refresh the informations, but after this the watched state is lost.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

watched state should be saved until i change it to unwatched or delete the series/movie from the database

## Actual Behavior

watched state will be deleted if you redownload informations of a series or video

### To Reproduce

1. right click on a series 
2. go to informations
3. and press refreh
after this whatched state is resetted

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Nvidia Shield 7.1
Latest nibghtly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MartijnKaijser** [comment]
This is not a bug. It has been like this for years and is more feature request to keep it

**Comment by HitcherUK** [comment]
> its allways much work, if a series has 25 episodes and you have already watched 15 and after that you need to set watched state again for every single episode

You could mark the whole series as watched and then mark the ones you haven't as unwatched. ;)

**Comment by M2k80** [comment]
this i actually do, but sometimes i forgot which was the last watched one xD

**Comment by zag2me** [comment]
Also the Trakt Add-on to always keep your watched status synced with the cloud. Simply run the Add-on to ever restore watched status to your DB on any client.
