### ISSUE TITLE
no adding of new series/films on update

### ISSUE THREAD

**Issue by DjSni** [xbmc/xbmc#14861]
### Describe the bug
Here is a clear and concise description of what the problem is:

Currently I have a Xiaomi MI Box running on this AndroidTV 8.0.
Since i updated to the current beta of the Play Store (Kodi-18.0-Beta5 Git:20181103-920e823), I have to add every folder Manuel to the library in every SMB source. When I tell him to search for new content, only the movies, series deposited in the library are updated, everything unknown is ignored!

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

That new movies and series will be found and added to the library.

## Actual Behavior

Only the series/films already in the library will be updated. 

### To Reproduce

1. add a new SMB source
2. update library
3. add new series/film to the source
4. update library

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - [x] AndroidTV
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: AndroidTv 8.0
 - Kodi version: Kodi-18.0-Beta5 Git:20181103-920e823

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@DjSni where is your debug log?

**Comment by DjSni** [comment]
Hello there,

the bug report can be closed, I found the bug. Someone found it funny to put ".nomedia" files in my source directories.

Maybe a note in the Kodi GUI would be helpful.

Greetings
