### ISSUE TITLE
UI unresponsive for entire duration of playback sometimes (with PVR recordings)

### ISSUE THREAD

**Issue by andrewgreenwood** [xbmc/xbmc#14867]
_I'm going to try and gather more information about this - at the moment I have a core-dump but no corresponding debug log file but have enabled this since and will provide more detail once available. I can provide a coredump file if required (it's ~500MB in size)._

## Bug report
When beginning playback of a PVR recording with Kodi Leia, sometimes the UI will become unresponsive for the entire duration of playback. Throughout the entire video, a circle will be displayed in the middle of the screen as if Kodi is waiting for something.

It is not possible to bring up the play/pause/stop etc. controls, nor is it possible to seek backwards/forwards when this problem occurs. The video plays without issue. At the end of playback, the circle disappears and I am returned to the PVR recording list where I'm able to navigate the UI.

There does not appear to be any consistent pattern as to which videos this affects - I can re-play a video that I had the problem with, and it's usually fine the second time around.

I'm mainly testing Leia with the MythTV PVR add-on and the BBC iPlayer WWW add-on. Mostly I am using the PVR functionality, so this is where the problem is mostly apparent - _I'm not sure if it happens with regular video files as I've not added my media library (yet). I'll try this at some point later on and update this as necessary._

Initially I thought this was a bug with the MythTV PVR add-on, and reported it here:
https://github.com/janbar/pvr.mythtv/issues/108

But the author of the add-on has experienced the same issue and it seems to be a bug in Kodi itself - hence the report being made here :)

## Expected Behavior
When beginning playback of a PVR recording, it should be possible to seek forward/backward and pause/stop playback at any point during the video.

## Actual Behavior
Intermittently, the UI stops responding and displays a circle in the middle of the screen for the entire duration of the video. When the end of the video is reached, playback stops, I am returned to the Kodi menus and UI becomes responsive again.

## Possible Fix
I'm guessing there is a race condition of some kind, particularly as it is quite intermittent and doesn't appear to be specific to the video being played.

### To Reproduce
1. Ensure you have some TV shows recorded via a PVR add-on
2. Navigate to the PVR recordings via the Kodi menus
3. Play a recording
4. If there is no circle in the middle of the screen, use the UI to stop the recording
5. Repeat steps 3 and 4 and hopefully you'll eventually find the UI doesn't respond and shows a circle

So far however, I have been unable to reproduce this on-demand.

### Debuglog

Sorry, I've only got a core dump for now but I will provide a debug log the next time this happens. Stack traces from the core dump can be found here:

https://pastebin.com/8kvc7fJD

I manually created this by using gdb's generate-core-file during an occasion where the problem happened.

### Screenshots 
Here are some links or screenshots to help explain the problem:
_TODO: I'll take a photo of the TV screen next time this happens._

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC devel-20181105114526-e019ab9 9.0
 - Kodi version: 18.0-BETA5 Git:newclock5_18.0b5-Leia

**I built LibreELEC from source on 5th November** to ensure I had an up-to-date version to work with before reporting bugs. It doesn't look like this issue has been reported so far.

I have a bit of an unusual setup in that I'm using a Raspberry Pi 3 with network booting (so, TFTP and NFS used for storage), as I got fed up with microSD cards failing. I don't think this will be specifically causing the problem but as storage seems to be faster, I suppose if there is some kind of race condition it may be making it more apparent.

**Comment by andrewgreenwood** [comment]
I've replicated this after repeatedly playing and stopping the same PVR recording. The resulting log file is over 200MB large and the coredump 500MB. I'll try and upload these at some point soon but looking at the window init/deinit log messages, when it works:

00:14:02.173 T:1938247696 DEBUG: ------ Window Init (MyPVRRecordings.xml) ------
00:14:03.317 T:1938247696 DEBUG: ------ Window Init (DialogBusy.xml) ------
00:14:03.388 T:1938247696 DEBUG: ------ Window Deinit (DialogBusy.xml) ------
00:14:09.072 T:1938247696 DEBUG: ------ Window Init (DialogBusy.xml) ------
00:14:09.853 T:1938247696 DEBUG: ------ Window Deinit (MyPVRRecordings.xml) ------
00:14:09.854 T:1938247696 DEBUG: ------ Window Init (VideoFullScreen.xml) ------
00:14:09.861 T:1938247696 DEBUG: ------ Window Deinit (DialogBusy.xml) ------
00:14:19.292 T:1938247696 DEBUG: ------ Window Init (VideoOSD.xml) ------
00:14:19.372 T:1938247696 DEBUG: ------ Window Init (DialogSeekBar.xml) ------
00:14:19.512 T:1938247696 DEBUG: ------ Window Init (Custom_1109_TopBarOverlay.xml) ------
00:14:21.542 T:1938247696 DEBUG: ------ Window Deinit (VideoOSD.xml) ------
00:14:21.543 T:1938247696 DEBUG: ------ Window Deinit (VideoFullScreen.xml) ------

When the problem happens:
00:15:20.985 T:1938247696 DEBUG: ------ Window Init (MyPVRRecordings.xml) ------
00:15:21.858 T:1938247696 DEBUG: ------ Window Deinit (DialogSeekBar.xml) ------
00:15:21.971 T:1938247696 DEBUG: ------ Window Deinit (Custom_1109_TopBarOverlay.xml) ------
00:15:23.569 T:1938247696 DEBUG: ------ Window Init (DialogBusy.xml) ------
00:15:24.981 T:1938247696 DEBUG: ------ Window Deinit (MyPVRRecordings.xml) ------
00:15:25.024 T:1938247696 DEBUG: ------ Window Init (VideoFullScreen.xml) ------

I suspect DialogBusy is what remains on the screen and I see that the VideoOSD, DialogSeekBar and TopBarOverlay don't get init'ed.

I've found that the rewind/forward buttons work on my remote control, along with play/pause. I can also input a time using the number buttons (inputting a time beyond the end of the recording will end playback and the problem will go away).

It took probably 30-40 attempts before the problem occurred. Still yet to test with regular media files.

**Comment by vbier** [comment]
I am also seeing this on my FireTV (android 32 bit) with beta5. Beta4 also had the problem, but as far as I can remember the previous versions worked fine.

**Comment by andrewgreenwood** [comment]
In my case, I don't spin down my drives but I've got a bit of an unusual network setup where I net-boot Kodi and also the MythTV backend. It takes a couple of seconds or so to begin streaming a recording through Kodi but a majority of the time, this issue doesn't happen.

Delays could provoke it but I'm not sure what exactly Kodi doing at the time - if it's simply a case of some messages being sent in an unexpected order or similar, it's most likely just a race condition.

I bought a Pi 3+ yesterday which I'll set up later to have a spare one to do some testing with. Replicating the issue on-demand takes a bit of time. I'm hoping to get more familiar with the Kodi source code to be able to work out what it's doing, but I could probably progressively checkout older commits and build those until the problem goes away to get a rough idea of where the problem was introduced. Using LibreELEC's build system though so I'd need to work out how to do that.

**Comment by janbar** [comment]
I am seeing this on my Linux Ubuntu x64.

**Comment by andrewgreenwood** [comment]
In my case, the problem can happen with any recording, even ones that have finished. I previously managed to reproduce the problem by starting playback, pressing the "OK" button on my TV remote to bring up the controls, press the stop button on the screen, and repeat this process over and over until eventually the circle appeared during the beginning of playback.

I haven't had it happen for several days now but have been busy with other things so haven't had an opportunity to try and replicate by force lately. I've got my Pi 3B+ ready(ish) for doing some testing so I'll get onto that within the next few days hopefully.
