### ISSUE TITLE
Grey letterbox when playing HDR content on Sony Android TV

### ISSUE THREAD

**Issue by generalmilk** [xbmc/xbmc#14865]
### Describe the bug
When playing a 2.35:1 4K HDR video file, the blank area/letterbox is grey insead of black. Only happens on Mediatek chip Android TV such as Sony. 

## Expected Behavior
Letterbox is black.

## Actual Behavior
Letterbox is grey.

## Possible Fix

Quote Koying:
“Yeah, that seem to be a(nother) bug on the Sony/Philips/Mediatek devices.
There is a programmatic workaround, though, it's to have the root window (and eveything in-between) made transparent.

It's how it was on SPMC, and how it will be in MrMC 3.7”

Another hint is it works fine on the 20180120 build of Kodi, not after that. 
I know it is a sony bug, but sony will never fix it, therefore I'm asking for help here.

### To Reproduce

1. Play an HDR video that does not fill up the full screen on a Sony Android TV

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

https://forum.kodi.tv/showthread.php?tid=328294

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 7.0
 - Kodi version: every build after 20180120 nightly

**Comment by mossopinc** [comment]
sony bravia kd55xe8596 i have and have to put up with the grey borders, i was hoping the it would get fixed by the time kodi 18 gets a full release but we are at RC1 and its still got these grey borders :( makes me sad

**Comment by MartijnKaijser** [comment]
This is a Sony firmware issue. Other mediaplayer added hacks/workarounds to solve this problem but we certainly won't Please contact Sony support to get this fixed correctly

**Comment by fritsch** [comment]
Please test: https://jenkins.kodi.tv/job/BuildMulti-Choice/194/ which will result in: http://mirrors.kodi.tv/test-builds/android/ - it will have the name "trans" in it ~ 20 minutes.

**Comment by generalmilk** [comment]
Sony will not fix this issue. They are aware of this for years. They are recently banning Kodi from their TV as well.

**Comment by fritsch** [comment]
Try my testbuild, thanks.

**Comment by generalmilk** [comment]
> Try my testbuild, thanks.

Will do. Thank you so much!

**Comment by fritsch** [comment]
Here, 32 bit: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20190109-5e28590f-trans-armeabi-v7a.apk
Here, 64 bit: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20190109-5e28590f-trans-arm64-v8a.apk

**Comment by mossopinc** [comment]
v7a didnt work for me :( and arm64 dont install

**Comment by fritsch** [comment]
Next try please: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20190109-6f6cbd6e-trans-armeabi-v7a.apk

**Comment by mossopinc** [comment]
for me dude this new one is a winner

**Comment by fritsch** [comment]
@MartijnKaijser so easy ...

**Comment by mossopinc** [comment]
no probs dude.....glads to see it being looked at finally

**Comment by fritsch** [comment]
Here: https://jenkins.kodi.tv/view/Automation/job/BuildMulti-Choice/197/ will have "trans2" in the name and result here: http://mirrors.kodi.tv/test-builds/android/arm/

Sony's job :-) not mine ...

**Comment by mossopinc** [comment]
Not Found
The requested URL /xbmc/test-builds/android/arm/kodi-20190109-8c831dd9-trans2-armeabi-v7a.apk was not found on this server.

**Comment by fritsch** [comment]
Wait a bit - mirror needs to sync. Try again in 5 minutes.

**Comment by mossopinc** [comment]
10 out of 10 movies tested so far are just great now though the interface seems a tad laggy now

**Comment by fritsch** [comment]
Is it the "same" laggy for both versions?

**Comment by mossopinc** [comment]
never noticed anything in trans1

**Comment by fritsch** [comment]
Okay - let me PR it and ask our Android maintainer what he thinks about it.

**Comment by fritsch** [comment]
You will see another testbuild: trans3 in name - that one uses the "minimal" subset from both changes. Let's see.

**Comment by mossopinc** [comment]
np

**Comment by fritsch** [comment]
Here we go: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20190109-6f984677-trans3-armeabi-v7a.apk

**Comment by fritsch** [comment]
Let's continue on the forum: https://forum.kodi.tv/showthread.php?tid=328294&pid=2807197#pid2807197

Where the other guy said: Version b is faster than a ;-) see, that's going to be funny, hehe.
