### ISSUE TITLE
Feature request: dynamically load libdvdcss/libdvdnav/libdvdread at runtime

### ISSUE THREAD

**Issue by wberrier** [xbmc/xbmc#14875]
Most linux distributions don't ship with libdvdcss.

Some apps load the shared library at runtime to support dvds if libdvdcss is available.

It seems like kodi has functionality available at runtime, but it must be compiled in.

It would be great if the functionality could be enabled at runtime by dynamically loading the necessary dvd libraries instead of having to recompile kodi to get this functionality.

**Comment by FernetMenta** [comment]
> Most linux distributions don't ship with libdvdcss.

those would be useless for kodi. Kodi needs modified versions.

**Comment by wberrier** [comment]
Ah, good to know, thanks for the clarification.

**Comment by pkerling** [comment]
@wberrier Please post feature requests to the corresponding forum section in the future. Thanks!
