### ISSUE TITLE
problem building on host systems with dual lib/ and lib64/ directories

### ISSUE THREAD

**Issue by teratux** [xbmc/xbmc#14870]
## Bug report
Kodi 18.0 build fails when compiling dependencies on systems with two library directories: **lib/** and **lib64/**

Here is a clear and concise description of what the problem is:

I'm using openSUSE Leap 42.3 a 64-bit system that handles system libraries in two distinct directories with separate functions.  I've noticed that the build system for Kodi is mainly focused on Ubuntu where there is only one library directory.  I'm successfully building Kodi by doing some tweaks that I think can be prevented from the build config files.  One of the things that start failing y native/python27 and the way I found to fix it is by copying everything built in the **PREFIX_DIR/NATIVE_DIR/lib64** directory to the **PREFIX_DIR/NATIVE_DIR/lib** directory.  Maybe a fix would be to try to look in both locations if they exist.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

A correct build on systems with two library directories

## Actual Behavior

Failure to build dependencies that look only in the **lib/** directory of the PREFIX_DIR

## Possible Fix

Try to look in both locations if they exist **lib64/** and **lib/**.

### To Reproduce

1.  Install a system that uses two library directories
2. configure the tools/depends directory with the specific configuration you're looking for
3. execute the make command

### Debuglog

The debuglog can be found here:
An error saying that the python executable in the PREFIX_DIR cannot find specific modules such as **time**, **site**, **os**, etc .. the error varies sometimes.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: openSUSE Leap 42.3 64-bits
 - Kodi version:
18.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Sounds to me like you are compiling the depends which you don't need to do on linux. Just use the system's native libraries.

see here for the build dependencies on linux -> https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md#3-install-the-required-packages

**Comment by teratux** [comment]
Ok .. my mistake, I'm trying to cross build for Raspberry Pi

**Comment by teratux** [comment]
This is the output error when issuing **make**, after following the steps of the README.RaspberryPi.md.  Step 4, specifically:

 ```
 File "/home/teratux/work/pkgs/kodi-18.0/tools/depends/native/distribute-native/x86_64-linux-native/setuptools/extension.py", line 2, in <module>
    from setuptools.dist import _get_unpatched
  File "/home/teratux/work/pkgs/kodi-18.0/tools/depends/native/distribute-native/x86_64-linux-native/setuptools/dist.py", line 6, in <module>
    from setuptools.command.install import install
  File "/home/teratux/work/pkgs/kodi-18.0/tools/depends/native/distribute-native/x86_64-linux-native/setuptools/command/__init__.py", line 8, in <module>
    from setuptools.command import install_scripts
  File "/home/teratux/work/pkgs/kodi-18.0/tools/depends/native/distribute-native/x86_64-linux-native/setuptools/command/install_scripts.py", line 3, in <module>
    from pkg_resources import Distribution, PathMetadata, ensure_directory
  File "/home/teratux/work/pkgs/kodi-18.0/tools/depends/native/distribute-native/x86_64-linux-native/pkg_resources.py", line 16, in <module>
    import sys, os, zipimport, time, re, imp, types
ImportError: No module named time
Makefile:22: recipe for target '.installed-x86_64-linux-native' failed
make[2]: *** [.installed-x86_64-linux-native] Error 1
make[2]: Leaving directory '/home/teratux/work/pkgs/kodi-18.0/tools/depends/native/distribute-native'
Makefile:64: recipe for target 'distribute-native' failed
make[1]: *** [distribute-native] Error 2
make[1]: Leaving directory '/home/teratux/work/pkgs/kodi-18.0/tools/depends/native'
Makefile:8: recipe for target 'native/.installed-x86_64-linux-native' failed
make: *** [native/.installed-x86_64-linux-native] Error 2
You have new mail in /var/spool/mail/teratux
teratux@linux-xfvt:~/work/pkgs/kodi-18.0/tools/depends>
```

To fix it, I copy everything from PREFIX_DIR/NATIVE_DIR/lib64 to the PREFIX_DIR/NATIVE_DIR/lib.  Make again in the distribute-native directory (so I can capture the screen output):

```
creating 'dist/distribute-0.6.21-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing distribute-0.6.21-py2.7.egg
creating /home/teratux/kodi-rpi/x86_64-linux-gnu-native/lib/python2.7/site-packages/distribute-0.6.21-py2.7.egg
Extracting distribute-0.6.21-py2.7.egg to /home/teratux/kodi-rpi/x86_64-linux-gnu-native/lib/python2.7/site-packages
Adding distribute 0.6.21 to easy-install.pth file
Installing easy_install script to /home/teratux/kodi-rpi/x86_64-linux-gnu-native/bin
Installing easy_install-2.7 script to /home/teratux/kodi-rpi/x86_64-linux-gnu-native/bin

Installed /home/teratux/kodi-rpi/x86_64-linux-gnu-native/lib/python2.7/site-packages/distribute-0.6.21-py2.7.egg
Processing dependencies for distribute==0.6.21
Finished processing dependencies for distribute==0.6.21
After install bootstrap.
Creating /home/teratux/kodi-rpi/x86_64-linux-gnu-native/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info
Creating /home/teratux/kodi-rpi/x86_64-linux-gnu-native/lib/python2.7/site-packages/setuptools.pth
touch .installed-x86_64-linux-native
teratux@linux-xfvt:~/work/pkgs/kodi-18.0/tools/depends/native/distribute-native>
```

And we got an OK build.

**Comment by teratux** [comment]
On a related note, this error when reaching TexturePacker is also caused by the duality **lib64/** and **lib/** 

```
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for pkg-config... /home/teratux/kodi-rpi/x86_64-linux-gnu-native/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for PNG... no
configure: error: "libpng not found"
Makefile:38: recipe for target 'x86_64-linux-native' failed
make: *** [x86_64-linux-native] Error 1
teratux@linux-xfvt:~/work/pkgs/kodi-18.0/tools/depends/native/TexturePacker>
```

If I export the correct PKG_CONFIG_PATH dir: export PKG_CONFIG_PATH=/home/teratux/kodi-rpi/x86_64-linux-gnu-native/lib64/pkgconfig

```
mv -f $depbase.Tpo $depbase.Po
/home/teratux/work/adbox/dtt/build/host/usr/usr/bin/ccache /usr/bin/g++ -DTARGET_POSIX -DTARGET_POSIX -DTARGET_LINUX -D_LINUX -std=c++0x -I/home/teratux/kodi-rpi/x86_64-linux-gnu-native/include  -llzo2 -ljpeg -lgif  -L/home/teratux/kodi-rpi/x86_64-linux-gnu-native/lib64 -lpng16 -lm -lz -lm  -static -L/home/teratux/kodi-rpi/x86_64-linux-gnu-native/lib  -o TexturePacker md5.o XBTFWriter.o TexturePacker.o DecoderManager.o decoder/PNGDecoder.o decoder/JPGDecoder.o decoder/GifHelper.o decoder/GIFDecoder.o XBTF.o  -llzo2 -ljpeg -lgif  -L/home/teratux/kodi-rpi/x86_64-linux-gnu-native/lib64 -lpng16 -lm -lz -lm 
make[2]: Leaving directory '/home/teratux/work/pkgs/kodi-18.0/tools/depends/native/TexturePacker/x86_64-linux-native'
make[1]: Leaving directory '/home/teratux/work/pkgs/kodi-18.0/tools/depends/native/TexturePacker/x86_64-linux-native'
make -C x86_64-linux-native install
make[1]: Entering directory '/home/teratux/work/pkgs/kodi-18.0/tools/depends/native/TexturePacker/x86_64-linux-native'
make[2]: Entering directory '/home/teratux/work/pkgs/kodi-18.0/tools/depends/native/TexturePacker/x86_64-linux-native'
 /usr/bin/mkdir -p '/home/teratux/kodi-rpi/x86_64-linux-gnu-native/bin'
  /usr/bin/install -c TexturePacker '/home/teratux/kodi-rpi/x86_64-linux-gnu-native/bin'
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/teratux/work/pkgs/kodi-18.0/tools/depends/native/TexturePacker/x86_64-linux-native'
make[1]: Leaving directory '/home/teratux/work/pkgs/kodi-18.0/tools/depends/native/TexturePacker/x86_64-linux-native'
touch .installed-x86_64-linux-native
#TEMP workaround for skins: create legacy link. Remove me when skins are fixed
teratux@linux-xfvt:~/work/pkgs/kodi-18.0/tools/depends/native/TexturePacker>
```
Another correct build ...
