### ISSUE TITLE
Suggestion to improve distclean command and speed-up build time

### ISSUE THREAD

**Issue by teratux** [xbmc/xbmc#14872]
## Bug report
This is not a bug report.  This is a suggestion for cleaning the build system if a user wants to regenerate the whole build.  When issuing the make distclean command a lot of packagss from the xbmc-tarballs directory get deleted.  Users working behind slow connections, like I am right now for example, will lose some time again downloading the packages, and if they symlink their xbmc-packages to a central directory of packages, the problem gets worse, maybe they'll lose packages for other systems.  Honestly it's the first time in my experience building packages that I've seen that a distclean clears my offline repositories, I think that cleaning only temporary libs and binaries without touching the downloades packages could be beneficial in the end.

## Possible Fix

Only delete libs and binaries generated after the make command.

### To Reproduce

1.  make 
2. packages get downloaded
3. make distclean
4. packages get removed

### Your Environment
 - Operating system version/name: openSUSE Leap 42.3 64-bits
 - Kodi version: 18.0

**Comment by pkerling** [comment]
> a lot of packagss

Please specify. Provide a log of `make distclean` that shows which files get deleted.

**Comment by teratux** [comment]
I'll try to reproduce, but now I issued the make distclean command for the whole project and didn't happen and I have to build the entire project again, and download the missing packages once more.

**Comment by Razzeee** [comment]
Any news or should this be closed?

**Comment by teratux** [comment]
Close it ... I managed to finally compile it but couldn't reproduce the issue.
