### ISSUE TITLE
Suggestion for including build step in documentation regarding the PATH variable for toolchains

### ISSUE THREAD

**Issue by teratux** [xbmc/xbmc#14871]
## Roadmap or todo suggestion
**Detailed Description**

### Context
I believe there is an aspect of the documentation for building on specific systems that is somewhat missing.  I've been building custom Linux systems for some time and didn't stumble on to the problem the first time I tried.  I'm following the simple documentation for building Kodi on Raspberry Pi systems.  I believe that what is missing is a step instructing the user to add to it's PATH environment variable the location of the custom toolchain he's using.  Maybe some toolchains when installed do this automatically, but, when building your own like the ones from Buildroot or Yocto, for example, this doesn't happen and if you're building outside their environment it's something you have to do.  I know it, because I've done it, but a new user that's trying to compile and already has specified the cross build triplet in the configure without setting the PATH variable correctly, will get incorrectly built packages since every configure step in target packages silently fail on finding the cross toolchain and fallback to the one from the host.  The result? The user thinks all is built correctly, no errors on screen, and the binaries and libs have been built for another architecture.

### Possible Implementation
Include a step in the documentation for reminding the user to export their PATH variable correctly should they use custom toolchains

### Additional context, screenshots or links
Here are some relevant links or screenshots

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by Rechi** [comment]
The `--with-toolchain` argument (https://github.com/xbmc/xbmc/blob/master/docs/README.RaspberryPi.md#4-build-tools-and-dependencies) for depends already does what is needed for the official raspberry pi toolchain.
We don't support other toolchains.

**Comment by MartijnKaijser** [comment]
Additionally what part of the "team member only" description did you miss creating the ticket?

**Comment by teratux** [comment]
Ok ... two things.  Firstly the **--with-toolchain** does not work.  This is my configure line:

`./configure --host=arm-buildroot-linux-gnueabihf --prefix=$HOME/kodi-rpi --with-toolchain=/home/teratux/work/adbox/dtt/build/host/arm-buildroot-linux-gnueabihf/sysroot --with-firmware=/home/teratux/work/adbox/dtt/build/build/rpi-firmware-287af2a2be0787a5d45281d1d6183a2161c798d4 --with-platform=raspberry-pi2 --disable-debug --build=i686-linux`

Perhaps you've only tried using toolchains installed from specific vendors in installable packets in specific distros.  Way before those existed, even before Ubuntu existed, people also used to create their own toolchains, and including this suggestion gives you a wider range of inclusions in users.

Secondly ... I resent your last comment, you are not the only project in GitHub and other projects tend to use the Issues channel for ... wait for it ... Issues, this is not an issue, it's an improvement based on something that does ... not ... work.  Maybe you should create a private channel for devs or members only, since anyone could write in it.  Maybe you're just having a bad day today, so, I believe the last comment you were going for is: "Hello, thanks for the feedback, we advise that future suggestions be addressed in Issues channel since this channel is for members only and we have no way of controlling that non-members write in it, our bad".

I'm expecting the next comment would be something along these lines: "You are right, this is something that will help future users, thanks again and remember to post in the other channel".  No need to answer, I already know what the solution is.

**Comment by Rechi** [comment]
> --with-toolchain=[...]/arm-buildroot-linux-gnueabihf/[...]

> **We don't support other toolchains.**

Is my comment that unclear?

**Comment by teratux** [comment]
Even in using the supported one https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/ the same problem persists.  My suggestion is not whether you  support other toolchains or not, it's a suggestion to correctly guide the user in to making, whatever toolchain they use the supported or the unsupported ones work correctly.  I downloaded the supported toolchain to prove my point and ran the whole steps one by one, still the same problem needing the same solution: exporting the PATH variable to include the location of the binaries of that toolchain.
