### ISSUE TITLE
feature_python3 branch not compatible with python 3.7

### ISSUE THREAD

**Issue by ronie** [xbmc/xbmc#14885]
### Describe the bug

i've been testing the feature_python3 branch on my Manjaro linux installation (which ships with python 3.7.1) and as far as i can tell, our feature_python3 branch is not compatible with the current python 3 version.

when you try to run an addon 'nothing happens'.
in the logfile i see:
`22:58:19.618 T:140117763139328    INFO: initializing python engine.`
but the addon is not run after that.

it looks like kodi is waiting indefinitely somewhere here: 
https://github.com/xbmc/xbmc/blob/93bc8be8d44259aa292f04b7392ab37077865d1a/xbmc/interfaces/python/XBPython.cpp#L625-L633

there are some changes in python 3.7 that may be relevant:
https://docs.python.org/3/c-api/init.html#low-level-api

## Expected Behavior
python addons should work as usual

## Actual Behavior
kodi does not run any python addon

## Possible Fix

add support for python 3.7.x

### To Reproduce

1. start kodi
2. check logfile to see if the versioncheck addon is run at startup

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/kulixexoru

### Your Environment
Used Operating system:

- Manjaro Linux
- Unbuntu 19.04 (nightly)

both ship with python 3.7.1

### Operating system version/name
 - Kodi version: 18 (feature_python3 branch)

**Comment by romanvm** [comment]
Yes, looks like a deadlock over the GIL. Probably the line 630 should be changed to this:
```c
if (PyEval_ThreadsInitialized() && !PyGILState_Check()) 
```

**Comment by romanvm** [comment]
@ronie  Can you compile and check if it works: https://github.com/romanvm/xbmc/tree/fix_python37

**Comment by Rechi** [comment]
@romanvm It fixed non working add-ons on windows with python 3.7 for me.

**Comment by ronie** [comment]
thx! fixes the issue.
