### ISSUE TITLE
Hardware acceleration on Android Shield TV makes some videos extremely dark

### ISSUE THREAD

**Issue by mineral4x** [xbmc/xbmc#14894]
### Describe the bug
Here is a clear and concise description of what the problem is:

When starting playback of certain videos(appears to be HEVC encoded ones) on the Android Shield TV the image appears extremely dark and crushes details and color is lost in the scene. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expect that the video is accurately represented.

## Actual Behavior

The entire image is extremely dark with color and detail loss.

## Possible Fix

By disabling acceleration for MediaCodec(Surface) the image appears normal again.
If acceleration is enabled when the video is started, I can background the video then foreground it again and the image seems normal until the video is stopped next.

See video demo.

### To Reproduce

1.  Tested with nvidia shield tv 7.1.0 / android 8.0.0 / kodi 17.6 or 18.0b5
2. Enable hardware acceleration MediaCodec(Surface)
3. Play HEVC video from a stopped state. Dark scenes make the issue most apparent.

### Debuglog

The debuglog can be found here:

kodi.log from the demo video
https://gist.github.com/mineral4x/15e45bf599fbb2b8694f7f501906d48f

media info for the file i show playing in the demo video
https://gist.github.com/mineral4x/7d6dd561b18a331c9914242530060e19

### Screenshots 
Here are some links or screenshots to help explain the problem:

demo video of the issue
https://youtu.be/dSLz_wz8IzA

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: nvidia shield tv 7.1.0 / android 8.0.0
 - Kodi version: kodi 17.6 and 18.0b5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Please disable Mediacodec-Surface and try again. This thingy is a blackbox and we have no influence on what it does to the colors.

If you find time - test a different player (vlc, etc.) with Mediacodec Surface _enabled_ as well - same issue?

**Comment by iz8mbw** [comment]
I have Nvidia Shield connected to a Panasonic OLED TV and both with Mediacodec and Mediacodec Surface I don't have that issue. HEVC videos are OK both with Mediacodec and Mediacodec Surface.

**Comment by fritsch** [comment]
Yes - which is totally unrelated to OP's post. Depending on the TV if it supports BT709 or HDR you get totally different results.

**Comment by M2k80** [comment]
if this is not a problem that could be fixed by kodi-devs....maybe he should write about this problem on nvidia shield forums?

**Comment by Razzeee** [comment]
Closing this due to no followup by the reporter.
