### ISSUE TITLE
MySQL upgrade violates GTID consistency checks

### ISSUE THREAD

**Issue by faminebadger** [xbmc/xbmc#14893]
### Describe the bug
I've just tried upgrading to the Kodi 18 beta 5 (from kodi 17) on my (gentoo) linux machine.  I use a MySQL server on a separate machine to store my Videos and Music databases.

After installation, Kodi 18 delayed for a long while during "Upgrading databases", which I took as a good sign, but at the end of it all, my databases were empty.

The log file shows this to be because of an SQL exception:
`00:23:55.648 T:139668226135808   ERROR: SQL: [MyVideos112] Undefined MySQL error: Code (1786)
                                            Query: CREATE TABLE settingsnew CHARACTER SET utf8 COLLATE utf8_general_ci AS SELECT idFile, Deinterlace, ViewMode, ZoomAmount, PixelRatio, VerticalShift, AudioStream, SubtitleStream, SubtitleDelay, SubtitlesOn, Brightness, Contrast, Gamma, VolumeAmplification, AudioDelay, ResumeTime, Sharpness, NoiseReduction, NonLinStretch, PostProcess, ScalingMethod, DeinterlaceMode, StereoMode, StereoInvert, VideoStream FROM settings
00:23:55.648 T:139668226135808   ERROR: Exception updating database MyVideos112 from version 107 to 112
`
Error 1786 is "Statement violates GTID consistency: CREATE TABLE ... SELECT."

This is because creating tables from another table in this way is inherently not safe with respect to transactions, presumably because it uses a temporary table.

## Expected Behavior
Upgrade databases successfully

## Actual Behavior
Fails to upgrade databases as described

## Possible Fix
Suggested solution would be to re-write the SQL to use transactionally safe statements.

### To Reproduce
1. Have Kodi 17 using MySQL server running with GTID consistency checks enabled
2. Upgrade to Kodi 18

### Your Environment
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo
 - Kodi version: 18 beta 5

**Comment by MartijnKaijser** [comment]
You did not follow the issue template which is required. Update your issue or this will be closed

**Comment by kib** [comment]
Why you are running MySQL with `--enforce-gtid-consistency` enabled. Is it a clustered instance ?

**Comment by faminebadger** [comment]
>> You did not follow the issue template which is required. Update your issue or this will be closed
Wow, aggressive much?

I think the issue is pretty clearly and obviously described, but sure, if you're unable to read it then I can add the extraneous information if it makes you happy.

**Comment by faminebadger** [comment]
> Why you are running MySQL with --enforce-gtid-consistency enabled.  Is it a clustered instance ?

Yes, there are slaves to the db server - it has other uses besides kodi.  Note, having this enabled is also the the default in the package for several OSes - e.g. FreeBSD I believe.

**Comment by kib** [comment]
I do not believe we have a solution at this time, this is simply an edge case to using SQL.

At this point I am afraid that in order to success with the upgrade you would have to (temporarily) turn off `--enforce-gtid-consistency`. Alternatively you could export the database to files, delete the database tables, let kodi create new ones, and re-import the expored NFO files, but the previous option seems simpler.

We welcome PR's and suggestions on how to do these transactions in a way which would be possible while having --enforce-gtid-consistency enabled.

**Comment by faminebadger** [comment]
Yeah, I already disabled it for the upgrade, thanks.

Note, regarding a way to do it - you just need to use a straight "CREATE TABLE" followed by an "INSERT INTO ... AS SELECT ..." statement instead of a "CREATE TABLE ... AS SELECT" statement.  The latter creates a temporary table, which is the problem.

There are performance reasons not to use the "CREATE TABLE ... AS SELECT" form too - for example it locks locks the metadata (because it's changing table definitions) for the entire duration, whereas separating it into create and insert does not.

**Comment by pkerling** [comment]
@faminebadger @bartmans please test #15092

**Comment by pkerling** [comment]
@faminebadger ping

**Comment by faminebadger** [comment]
@pkerling Unfortunately, I can't easily test this - as mentioned previously I forced the upgrade through by disabling consistency checking temporarily.  As there's no downgrade path, it would require a complete re-install of an older kodi and creating new databases.

**Comment by pkerling** [comment]
@faminebadger I was hoping you might have an older backup that you can just put in for testing. Also as far as I'm aware the old DBs are not deleted after upgrade, right? So you could just rename the new ones temporarily to force the upgrade process to rerun.

**Comment by faminebadger** [comment]
@pkerling Ah, if it's true they're not deleted, then I may be able to try.  I'll have a look over the weekend if I can.
