### ISSUE TITLE
Suggestion: MySQL performance tuning

### ISSUE THREAD

**Issue by annomatik** [xbmc/xbmc#14892]
## Roadmap or todo suggestion
**Detailed Description**

Hi! Here's Johnny from the Kodi-Forums suggested, I post my findings here.

**Big Disclaimer**: I'm using Kodi just as a user, not as a developer. So I'm on the latest stable version ( Kodi 17.6 ), meaning some of these things might already look a bit different. I don't want to install the latest (development / beta) version due to stability and because I'm just "using" Kodi to get order into my media library, not as a developer. But I'll happily test every database change in the final released version, as soon as it is available for Windows 7, Windows 10 and RetroPie (a Raspbian distribution I'm using).

**Background**: I always had performance and stability problems with Kodi, since day one. What I did was reduce all the plugins to the minimum, recreate the database a couple of times and always update to the newest Kodi versions. Didn't help much, the performance wasn't that great (I have a Synology as a backend device, storing my files + my MySQL db) and Kodi still crashed a lot. After a lot of unsuccessful forum threads, I started implementing a big Monitoring solution and I also started digging into what Kodi does with the db. Here are some of my findings.

**Finding 1**: For the video-database, there's a "master / view" concept. There's the master-table for most things (episodes / tvshows / movies) and a corresponding view-table which connects everything it can (episodes_view, tvshows_view, etc.). In my case, accessing the view was, even with a count(*), up to 15 times slower than accessing the master table. Joining just some tables manually was sometimes faster, sometimes not.

**Finding 2**: There are already a couple of indexes set, unfortunatelly, they don't help the views. For example, there is a "ix_movie_file_1", which is an index on idFile,idMovie. and a "ix_movie_file_2", which is an index on idMovie,idFile. But the view uses a join on just idFile, so none of both indexes apply and it does a full scan. Not a problem for 10 movies and a i9 processor, but running a Synology and over 3000 movies in the table, this is a big optimization potential.

**Finding 3**: For some columns, the foreign-keys are stored as text, not as int. For example:

````
MariaDB [myvideos107]> describe movie;
+------------+---------+------+-----+---------+----------------+
| Field      | Type    | Null | Key | Default | Extra          |
+------------+---------+------+-----+---------+----------------+
| idMovie    | int(11) | NO   | PRI | NULL    | auto_increment |
| idFile     | int(11) | YES  | MUL | NULL    |                |
| c05        | text    | YES  | MUL | NULL    |                |
:
+------------+---------+------+-----+---------+----------------+
29 rows in set (0.01 sec)

MariaDB [myvideos107]>
````

This doesn't help performance, especially if there is no index and c05 is used in the join:

````
"...left join `rating` on(`rating`.`rating_id` = `movie`.`c05`)) ..."
````

Instead, c05 should be an integer, like the key on maybe even an unique index:

````
MariaDB [myvideos107]> describe rating;
+-------------+---------+------+-----+---------+----------------+
| Field       | Type    | Null | Key | Default | Extra          |
+-------------+---------+------+-----+---------+----------------+
| rating_id   | int(11) | NO   | PRI | NULL    | auto_increment |
:
+-------------+---------+------+-----+---------+----------------+
6 rows in set (0.00 sec)
````

**Finding 4**: "lastPlayed" and "dateAdded" of the files table are text as well. This would be probably more performant with the native date type also, especially together with queries like "select * from movie_view WHERE ((movie_view.dateAdded > '1900-01-01')) -- a simple integer-comparison (a date is nothing but a fancy integer) is a lot faster than a string comparison, even if dateAdded gets its much needed index.

**Finding 5**: During startup, Kodi is running (almost) the same query 6 times (!) in parallel. And this is just for the standard-Kodi theme Estuary on Kodi 17.6. Arctic Zephyr with its Skin Helper plugin probably does even more things that can be optimized, but I still have to analyze that:

````
Id      User    Host    db      Command Time    State   Info    Progress
1       system user             NULL    Daemon  NULL    InnoDB purge coordinator        NULL    0.000
2       system user             NULL    Daemon  NULL    InnoDB purge worker     NULL    0.000
3       system user             NULL    Daemon  NULL    InnoDB purge worker     NULL    0.000
4       system user             NULL    Daemon  NULL    InnoDB purge worker     NULL    0.000
5       system user             NULL    Daemon  NULL    InnoDB shutdown handler NULL    0.000
2563635 kodi    Host:58089      myvideos107     Query   3       Sending data    select * from movie_view  WHERE ((movie_view.dateAdded > '1900-01-01')) AND ((movie_view.playCount IS NULL OR movie_view.playCount < 1))        0.000
2563639 kodi    Host:58106      myvideos107     Query   3       Sending data    SELECT * FROM tvshow_view       0.000
2563640 kodi    Host:58107      myvideos107     Query   3       Sending data    select * from movie_view  WHERE ((movie_view.playCount IS NULL OR movie_view.playCount = 0))    0.000
2563641 kodi    Host:58108      myvideos107     Query   3       Sending data    select * from movie_view  WHERE ((movie_view.playCount IS NULL OR movie_view.playCount < 1))    0.000
2563642 kodi    Host:58115      myvideos107     Query   3       Sending data    select * from movie_view        0.000
2563643 kodi    Host:58116      myvideos107     Query   3       Sending data    select * from movie_view  WHERE ((movie_view.playCount IS NULL OR movie_view.playCount < 1))    0.000
2563644 kodi    Host:58123      myvideos107     Query   3       Sending data    select * from movie_view        0.000

````

This surely can be optimized. A "cheap" way of doing that would be just putting some sort of simple "db-cache" function in Kodi and trying to use the same statement in all 6 cases. Then, the db-cache function should remember that it already queried that and just give back the (Already generated) result. Or something like that. You figure it out :-)

And that is that. I'll probably do some more digging, but this already should help. The indexes I have created and which also, interestingly enough, improve logoff-performance (it would hang all the time but this seems to have improved) can be found below.

This is a work in progress and surely can benefit from additional thoughts.

Here's a small shell-script that shows you, what MySQL is currently doing:
````
$ cat mysql-loop
#!/bin/bash
while true; do
        clear
        echo "show full processlist" | mysql -u <user> -p<pass> -h <host>
        sleep 5
done

````

### Context

Better response-time.

### Possible Implementation

These are the indexes I'm currently adding to all of my 4 Kodi databases (I have 4 profiles), and I'm happy with the result. Most are because of the views, the idSet one is because I kept seeing a query to idSet all the time in the MySQL process list. And again: c05, c09, c04 and c12 should be integers, not text. and lastPlayed and dateAdded should be date.

````
create index episode_idFile on episode(idFile);
create index episode_idShow on episode(idShow);
create index episode_idSeason on episode(idSeason);
create index episode_c03 on episode(c03);
create index episode_c20 on episode(c20);
create index movie_idFile on movie(idFile);
create index movie_idSet on movie(idSet);
create index movie_c05 on movie(c05(20));
create index movie_c09 on movie(c09(20));
create index files_lastPlayed on files(lastPlayed);
create index files_dateAdded on files(dateAdded);
create index files_playCount on files(playCount);
create index files_idPath on files(idPath);
create index tvshowlinkpath_idShow on tvshowlinkpath(idShow);
create index tvshowlinkpath_idPath on tvshowlinkpath(idPath);
create index tvshow_c04 on tvshow(c04(20));
create index tvshow_c12 on tvshow(c12(20));
````

### Additional context, screenshots or links
Here are some relevant links or screenshots

https://forum.kodi.tv/showthread.php?tid=329046

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by kib** [comment]
Please post feature requests to the corresponding forum section in the future. Thanks!

**Comment by MartijnKaijser** [comment]
Additionally we only accept issues for v18 and up. Testing v18 is quite simple as you drop the newly created database tables after testing

**Comment by kib** [comment]
please move all further discussion to forum until proper testing has been done, as I already mention in my post there.
