### ISSUE TITLE
3D H-SBS/H-OU movie files are played wrong with OMX-Player on RPi 3 Mod. B

### ISSUE THREAD

**Issue by agsmf** [xbmc/xbmc#14907]
### Describe the bug
Here is a clear and concise description of what the problem is:

When starting playback of 3D H-SBS (Side-by-Side) or H-OU (Over-Under) MKV-files (x264) the files are displayed with the original splitscreen pictures instead with correct 3D or 2D pictures. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expect that the movie files played with correct 3D or 2D pictures

## Actual Behavior
When starting playback of 3D H-SBS (Side-by-Side) or H-OU (Over-Under) MKV-files (x264) you will get a selection how to play this 3D file (Preferred mode, Monoscopic/2D, Select alternative mode). None of them is working with the OMX-Player option activated -> every time the file is played it shows the original splitscreen pictures instead of the correct 3D or 2D pictures
If OMX-Player is deactivated and only MMAL hardware acceleration is activ everything went fine.

## Possible Fix
As a workaround you can disable the OMX-Player option.

### To Reproduce

- fresh install of LibreELEC 18 (Leia) v8.90.007 ALPHA
- activate OMXPlayer
- start a 3D H-SBS (x264) movie file and choose one the following options:
  -> Preferred mode
  -> Monoscopic/2D
  -> Select alternative mode -> side by side

I've tested it with two different TV devices (LG, Samsung). On both devices the problem occurs.
In LibreELEC 17 (Krypton) 8.2.5 with the OMX-Player activated this ERROR did not occur.
I also tested it with different 3D H-SBS (Side-by-Side) or H-OU (Over-Under) MKV-files (x264). In all cases the ERROR occurs.

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/abawomaxov

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberri-Pi 3 Mod. B
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Libreelec 18 (Leia) v8.90.007 ALPHA (also present in v8.90.006)
 - Kodi version: 18.0-BETA5 Git:newclock5_18.0b5-Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by da-anda** [comment]
@popcornmix mind having a look?

**Comment by agsmf** [comment]
@popcornmix The new nightly build has fixed the problem. Everything works now as expected.

**Comment by edwardo040** [comment]
I have the same problem, and i dont know how to workarround.

My Environment
Used Operating system:

  Android Nvidia Shield and the TV Sony Bravia 

Kodi version: 18.1 Git:20190228-80b339717w

Compiled:2019-02-28

Does anyone have an idea or workarround?
