### ISSUE TITLE
Issue when switching from file playback to live TV

### ISSUE THREAD

**Issue by smp79** [xbmc/xbmc#14915]
### Describe the bug
Sometimes when I switch to a live TV channel during a video file playback I get a black screen or a frozen frame until I switch to another channel. This is a long-standing issue. I thought that this issue occur randomly but I did more testing and it's actually quite easy to reproduce.

### To Reproduce

1. Play any video file.
2. Fast forward to nearly the end of the video.
3. When ~5 seconds is left until the end of the video switch to a TV channel.
The issue occur only at the very end of the file playback, when there is about 5 seconds left.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/kuquxagafe.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 9
 - Kodi version: 18, current master

**Comment by FernetMenta** [comment]
Very likely that this is a Raspverry Pi issue and not a generic one
