### ISSUE TITLE
Missing PVR feature (continue last channel on startup) in Kodi 18 RC5

### ISSUE THREAD

**Issue by Donderstraal** [xbmc/xbmc#14913]
## Missing past available feature (not really a bug)
Here is a clear and concise description of what the problem is:

Normally on my htpc with dedicated tv card I turn it (by remote), starts windows, starts automatically Kodi and it would resume the last channel like a tv would. My htpc is primarily used to watch TV en Kodi really makes the the 'dumb' tv 'smart' in a nice way. Anyways I have been really enjoying this feature and saw it was missing on my test setup in the RC's and beta's. I think it deserves to be added again. Tried to find it at other places that made sense within settings but it doesn't appear to be moved places. Maybe something for Ksooo? (how many o's again?)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Once toggled it should start the last watched channel on the start of Kodi.

## Actual Behavior
The option is gone

## Possible Fix
Simply add it again

### To Reproduce
1. go to Settings -> PVR Service -> Playback -> Continue last channel on startup
2. see if it's there
3. confirm it's not there...

### Debuglog
not needed

### Screenshots 
Here are some links or screenshots to help explain the problem:

Function highlighted here on Kodi v17.6;
![ScreenShot](https://i.imgur.com/slW0bzD.png)

Missing on the latest v18 nightly;
![ScreenShot](https://i.imgur.com/2SXs1KZ.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [X ] OSX
 - [ ] Raspberri-Pi
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 / OSX
 - Kodi version: 18 RC5

**Comment by ksooo** [comment]
1.  go to Settings -> Interface -> Startup -> Perform on startup -> Play TV
2. see if it's there
3. confirm it's there...
4. close the bug
5. smile :-)

**Comment by MartijnKaijser** [comment]
Settings do t accidentally disappear so it was removed by choice. Since this is not a big but a request you should start a thread on the forum.

**Comment by Donderstraal** [comment]
Smile =)

Just would never have looked for it in that place... while I like the idea, hiding it under interface feels a bit odd. Startup under System would make more sense IMO.
