### ISSUE TITLE
Android Low Memory Killer (LMK) killing Kodi app due to high memory consumption

### ISSUE THREAD

**Issue by tpvkrishnadass** [xbmc/xbmc#14919]
**Environment:** 
Kodi app version: 17.6
Android-P TV platform

**Background:** 
Google has made significant changes in LMK design from Android O to P. The memory criteria is now more aggressive and also includes in the scope foreground tasks consuming high memory. It can kill a foreground app with oom_adj value 0 when memory pressure reaches critical level. Android reference: https://source.android.com/devices/tech/perf/lmkd

**Issue scenario:** 
While browsing picture files in Kodi app on a connected USB stick, we observe the app getting killed by LMK as it is consuming upto 600 MB memory (it could be more depending on the USB stick contents). The issue does not happen while browsing video or music files. The app seems to be caching the pictures or thumbnails to improve performance and user experience. We observed the same memory allocation by Kodi on our Android-O TV platform as well, but in Android-O, by design the LMK does not kill foreground app. Since this is a design change in Android-P LMK, probably it is expected that apps adapt to it. 

**Log download link:**
https://drive.google.com/file/d/1HXgC_8EFf67WQ7kOwRtcyhVq0N7_joAR/view?usp=sharing

**Snippet from above log:**       
11-15 08:03:55.116  2391  2391 I lowmemorykiller: Killing 'org.xbmc.kodi' (13957), uid 10092, adj 0
11-15 08:03:55.116  2391  2391 I lowmemorykiller:    to free 1291644kB because system is under critical memory pressure oom_adj 0

**Comment by MartijnKaijser** [comment]
V17 is no longer supported please try. v18

**Comment by tpvkrishnadass** [comment]
Hi Martijn,

Thank you for your quick response.

We don't see v18 on Google Play Store from our TV. We see only v17.6. Is it already released on Play Store? Can you please share the apk here?

Regards
Krishnadass

**Comment by MartijnKaijser** [comment]
It's available through beta channel https://play.google.com/apps/testing/org.xbmc.kodi
Or download form 
http://mirrors.kodi.tv/nightlies/android/arm/master/

**Comment by tpvkrishnadass** [comment]
Thank you Martijn

**Comment by MartijnKaijser** [comment]
If you know how to fix it perhaps you can create a pull request?

**Comment by mthokozicy** [comment]
I need a job offer people, anyone looking to hire ?

**Comment by theseraphim** [comment]
There are a couple of options here realistically, first is that on a rooted device you can script xbmc to have a lower oom_adj value, down to -17 if you want, how this would be integrated into this codebase i'm not sure, some more info on it here

[https://android.stackexchange.com/questions/23469/how-to-lower-oom-value-of-an-app-permanently](url)

Second option would be to look deeper into your use case, would need some more information re: how many images are on this USB, what size, what happens if you break it up into subfolders of half the total pictures etc, but someone would need to point me to the code that handles the caching/preloading of the pictures to see if it can be optimised somewhat on low memory environments.

**Comment by tpvkrishnadass** [comment]
Hi Theseraphim,

Thank you for your suggestions. 

Our Android-P TV is a production device and the end users cannot root it. We'll check if there is a way to pre-build the system SW image with oom_adj value reduced to -17 for Kodi app. 

Optimizing the picture caching logic to work within the limits set by Android-P LMK would be the best solution, as Kodi app will hit this issue on other Android-P devices as well. 
The USB memory we used to test was:

- 16 GB pen drive.

- Mostly empty with only about 900 MB media content (included music, videos, and pictures). Total picture files out of this was about 500 MB. 

- Pictures included one high resolution 8000 x 8000 pixels bmp file of 183 MB size and a few UHD files of about 50 MB and 10 MB sizes.
The picture folder contents are shared below for your reference:
https://drive.google.com/open?id=14nw4hOvSvHGQdyAlw-wGx9bj1x6ePqrF

- LMK kills Kodi app only while browsing the pictures folder. At this time, we observed around 600 MB memory held by Kodi app.  

Regards
Krishnadass

**Comment by tpvkrishnadass** [comment]
Hi Martijn, Theseraphim,

Last week we tested the same USB contents on Google Android-P Reference TV platform (Augie). Also on this platform we observe LMK killing Kodi app during picture browsing due to high memory consumption. So it is exactly the same behaviour as on our device. This issue will potentially impact all Android-P platforms/devices owing to the change in LMK design in Android-P. Hence probably the picture caching/pre-decoding algorithm needs to be adapted. 

Regards
Krishnadass

**Comment by pkerling** [comment]
@tpvkrishnadass We welcome contributions to the caching/decoding logic such that it consumes less memory.

**Comment by deepu458** [comment]
I had a similar issue with 18.1 App version on my Android Nougat Based tablet. In my case even if i just open app and browse to list of addons and then launch other app and bring Kodi from recents it just jumps back to App loading.
