### ISSUE TITLE
Video freeze during playback on kodi-x11 

### ISSUE THREAD

**Issue by kib** [xbmc/xbmc#14917]
### Describe the bug
When playing back a video from a NFS source Kodi freezes during video playback. 
This seems to usually happen after pausing and resuming playback, for instance when downloading a subtitle. It doesn't always happen when pausing but downloading a subtitle seems to trigger it semi-consistently.
After waiting for a long time Kodi will crash but without a crashlog.

## Expected Behavior
Kodi does not freeze during video playback

## Actual Behavior
Kodi freezes during video playback

### To Reproduce
On a system running kodi-x11 in standalone mode with a video source located on NFS
1. Start playing the video
2. While playing navigate to the subtitle settings and select 'download subtitle'
3. The subtitle dialog will pause the video
4. Select any subtitle and back out of the window, the video will continue
5. Watch the rest of the video. Kodi freezes a minute or so later.

### Debuglog
I supplied a debug log over team internal channels but it did not provide anything useful. 
The last lines of the debug log seemed to indicate an issue with NFS because thy always were similar:
```22:04:34.540 T:140733959374592   DEBUG: CVideoReferenceClock: detected -1 vblanks, missed 0, refreshrate might have changed
22:04:37.166 T:140737353675712  NOTICE: NFS is idle. Closing the remaining connections.
22:04:59.397 T:140737353675712  NOTICE: AddOnLog: NFS support: NFS is idle. Closing the remaining connections.
```

I'm opening an issue ticket because I managed to get a stack trace of the issue, which can be found here: https://paste.kodi.tv/exipohupug.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 18.04.1 LTS (Bionic Beaver), set up using @fritsch tutorial on the forums.
 - Kodi version: 2:18.0+git20181114.0201-fce4d88-0bionic

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by FernetMenta** [comment]
You seem to use https://github.com/notspiff/vfs.nfs. BT indicates that it hangs there.
Did you try to disable this addon and use Kodi's NFS?

**Comment by kib** [comment]
Ah! 
I installed that from the Team-Kodi PPA, it is `kodi-vfs-nfs` version `1.0.1-2~bionic`.
I probably was testing the binary add-on at some point long ago, and actually did not realised we still had nfs support internal as well. 
I will test, thank you.

**Comment by avivg** [comment]
Happens to me too, when the file is on smb.
