### ISSUE TITLE
Boolean expression in visible tag does not behave like it should

### ISSUE THREAD

**Issue by dmitry-vinogradov** [xbmc/xbmc#14928]
### Describe the bug
Here is a clear and concise description of what the problem is:

Following boolean expression in `visible` tag in skin xml file does not behave like it should (or like it behaves in v. 17.*):

```
<control type="group">
...
<visible allowhiddenfocus="true">
                        [Control.IsVisible(4200)|Control.IsVisible(4300)]
                        +StringCompare(Container(4200).ListItem.Property(cid), Container(4300).ListItem.Property(cid))
                    </visible>
...
</control>
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The visibility of container should depend on defined expression like it does in previous versions of KODI

## Actual Behavior

The container is not visible.

### To Reproduce

Affected skin XML file: [tv_dialog.xml](https://github.com/kodi-iptv-addons/kodi-iptv-addons/blob/master/script.module.iptvlib/resources/skins/Default/720p/tv_dialog.xml#L583)

### Debuglog

There's nothing related in debug log

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] Linux
 - [x] OSX
 - [x] Raspberri-Pi
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi v18 "Leia" RC 1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by rmrector** [comment]
StringCompare was deprecated in favor of String.IsEqual in [Krypton](https://forum.kodi.tv/showthread.php?tid=250862) and removed in Leia.

**Comment by HitcherUK** [comment]
As rmrector said, StringCompare is depreciated in Leia so this can be closed.

**Comment by dmitry-vinogradov** [comment]
My fault, overlooked ...  Thanx
