### ISSUE TITLE
Warning toast "Detected Problems with app native libraries" appears when Kodi app is launched

### ISSUE THREAD

**Issue by tpvkrishnadass** [xbmc/xbmc#14920]
**Environment:** 
Kodi app version: 17.6
Android-P TV platform

**Screen snapshot:**
![toast](https://user-images.githubusercontent.com/45250106/48885667-1c559d00-ee4f-11e8-864c-49c7dafb4e12.jpg)

Log and screen snapshot download link:
https://drive.google.com/file/d/1vqS8nfcD8BtZ4jGHHnkkLTnmXfIT6UF5/view?usp=sharing

**Log snippet:** 
09-26 13:14:33.629  3378  3378 W linker  : Warning: "/data/app/org.xbmc.kodi-t_SMaQkhn1IvBuiMT-HAcQ==/lib/arm/libkodi.so" has text relocations and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/Text-Relocations-Enforced-for-API-level-23) (allowing for now because this app's target API level is still 22)

**Comment by MartijnKaijser** [comment]
v17 is no longer supported. Please install v18

**Comment by tpvkrishnadass** [comment]
Hi Martijn,

Thank you for your quick response. 

We don't see v18 on Google Play Store from our TV. We see only v17.6. Is it already released on Play Store? Can you please share the apk here? 

Regards
Krishnadass

**Comment by tpvkrishnadass** [comment]
Hi Martijn,

We tested with app v18-RC1 and found the issue is fixed. Thank you for your support.

Regards
Krishnadass
