### ISSUE TITLE
blank screen after startup LETV android TV

### ISSUE THREAD

**Issue by gello0** [xbmc/xbmc#14925]
### Describe the bug
Here is a clear and concise description of what the problem is:

so I have always had trouble using kodi on my letv super3 x55 with MStar 6A928 SoC and mali mali-t760 mp4. After installing kodi 18.0 alpha1 finally boxy letters stopped this version was obviously alpha so i continued using this until any updated got realeased. All versions alpha2 and above have startup issue on my tv. after instalation of alpha 2to rc1 after startup loading screen there is a blank screen and kodi never starts.  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

kodi should start normally like alpha 1

## Actual Behavior

kodi will show blank screen forever

### To Reproduce

1. If Posibally use same spec meachine 

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/hovonixuba.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://m.imgur.com/a/d5uJCcy

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

 Screenshot 1) 17.6
Screenshot 2) 18.0 alpha1
Screenshot 3) 18.0 RC1

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:android 5.0.1
 - Kodi version:18.0 rc1
 
### Update 
I tried installing RC2 and RC3 still having same issue but when it goes into black screen UI sounds can be heard when arrow keys are pressed on remote
Here's the debug log for RC3 https://paste.kodi.tv/ofifoxukaq.kodi
### Update 2
Installed RC4 this time im the splash screen is black too after few seconds of opening app UI sounds can be heard when arrow keys are pressed on remote. https://paste.kodi.tv/bigamakewa.kodi

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by gello0** [comment]
https://github.com/xbmc/xbmc/issues/15053#issuecomment-448194589 I installed latest nightly and 2018/12/17 now the app crashes after startup screen.

**Comment by DaVukovic** [comment]
Neither of the builds you mentioned (2018/12/17 or 2018/12/25) will show `Kodi 18.0 Alpha 1 from a git version from March 2018. So you clearly don't use a current Kodi version. Please update to a recent kodi version and always provide a full debug log. 

Thanks.

**Comment by metronidazole** [comment]
Try reinstalling the latest nightly (or beta/RC if there is a newer one), then reset app data, and try again.

**Comment by gello0** [comment]
I do clean installation every time I update

**Comment by cherrot** [comment]
I found a way to fix this issue. 
I was testing kodi apks to find which version works on my LeTV (ROM is EUI 6.0, based on Android 7.0 I guess). This is what I tried:

1. Install `kodi-18.0-Leia-armeabi-v7a.apk` (2019-Jan-28 18:31). After startup logo, it goes black. (UI reacts normally because I could hear the responsive beep sound)
2. Uninstall and install `kodi-18.0-Leia_rc4-armeabi-v7a.apk` with no luck.
3. Uninstall and install `kodi-18.0-Leia_alpha2-armeabi-v7a.apk` (or alpha1, I am not sure now...). Finally I can see kodi's UI!
4. Then I tried to install `rc5` and `kodi-18.0-Leia-armeabi-v7a.apk` again. Both works fine.

**Comment by cherrot** [comment]
And another tip:
Remember to exit kodi by clicking the power button on the top-left. Otherwise you will encounter the black screen again :D  (Reinstall kodi could fix it)

**Comment by cherrot** [comment]
kodi 18.0 is not very stable on my LeTV. 

Finally I switched to kodi 17.6. It works fine so far.

**Comment by gello0** [comment]
I have tried almost release none of them. @cherrot Check these screenshots https://imgur.com/a/d5uJCcy if i didnt have that blocky animations i wouldve never tried 18.

**Comment by cherrot** [comment]
@gello0 I did have exactly the same issue for 1 or 2 times. A simple app restart could fix it. 

Just to make sure, have you changed the font of skin to `Aria based` before changing region and language?

**Comment by gello0** [comment]
i use default skin and default english font, is default Aria?

**Comment by cherrot** [comment]
No but it makes no difference to English. Could you fix this by restarting `kodi` app?

**Comment by gello0** [comment]
i tried installing 17.6 i got blocky font on first install, i changed font to Arial the blocky font was gone right after changing to Arial. After restarting ``kodi`` again the blocky fonts appeared, it was gone when I changed font back to ``default skin-font``
