### ISSUE TITLE
Netflix Video doesn't since RC1

### ISSUE THREAD

**Issue by AndrewGermany** [xbmc/xbmc#14936]
### Describe the bug
Here is a clear and concise description of what the problem is:

Netflix doesn't work proper in Kodi 18 RC1, in Alpha everything worked fine. You can list video, but the playback doesn't start

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Actual Behavior

Videoplayback using netflix addon an inputstram fails

### To Reproduce

installed Kodi 18 alpha playback of netflix videos worked fine
after installing kodi rc1 playback fails (see error log)

### Debuglog

The debuglog can be found here:

10:51:08.774 T:4780  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27writer%27%3A+%27%27%2C+%27episode%27%3A+1%2C+%27plot%27%3A+u%27Der+brutale+Mord+an+einer+militanten+jungen+Lehrerin+bringt+Conde+auf+die+Spur+eines+Drogenbarons+mit+Verbindungen+zu+seiner+ehemaligen+Schule.%27%2C+%27season%27%3A+1%2C+%27tvshowtitle%27%3A+u%27Four+Seasons+in+Havana%27%2C+%27title%27%3A+u%27Die+Winde+der+Fastenzeit%27%2C+%27mediatype%27%3A+u%27episode%27%2C+%27mpaa%27%3A+u%27-%27%2C+%27director%27%3A+%27%27%2C+%27genre%27%3A+u%27Spanische+Serien%27%2C+%27year%27%3A+2016%2C+%27duration%27%3A+5776%7D&video_id=80149088&pin=False&start_offset=2794
10:51:08.777 T:11160  NOTICE: Creating InputStream
10:51:08.793 T:11160   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Program Files\Kodi\addons\inputstream.adaptive\
10:51:10.805 T:12008   ERROR: Traceback (most recent call last):
10:51:10.805 T:12008   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 290, in _handle_request_noblock
10:51:10.806 T:12008   ERROR:     self.process_request(request, client_address)
10:51:10.806 T:12008   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 318, in process_request
10:51:10.806 T:12008   ERROR:     self.finish_request(request, client_address)
10:51:10.806 T:12008   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 331, in finish_request
10:51:10.806 T:12008   ERROR:     self.RequestHandlerClass(request, client_address, self)
10:51:10.806 T:12008   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 652, in __init__
10:51:10.806 T:12008   ERROR:     self.handle()
10:51:10.806 T:12008   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\BaseHTTPServer.py", line 340, in handle
10:51:10.808 T:12008   ERROR:     self.handle_one_request()
10:51:10.808 T:12008   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\BaseHTTPServer.py", line 328, in handle_one_request
10:51:10.808 T:12008   ERROR:     method()
10:51:10.808 T:12008   ERROR:   File "C:\Users\andreas\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\MSLHttpRequestHandler.py", line 69, in do_GET
10:51:10.809 T:12008   ERROR:     dolby, hevc, hdr, dolbyvision, vp9)
10:51:10.809 T:12008   ERROR:   File "C:\Users\andreas\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\MSL.py", line 225, in load_manifest
10:51:10.809 T:12008   ERROR:     return self.__tranform_to_dash(data)
10:51:10.809 T:12008   ERROR:   File "C:\Users\andreas\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\MSL.py", line 311, in __tranform_to_dash
10:51:10.809 T:12008   ERROR:     manifest = manifest['result']['viewables'][0]
10:51:10.809 T:12008   ERROR: KeyError: 'viewables'
10:51:10.810 T:11160   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
10:51:10.810 T:11160   ERROR: CCurlFile::Open failed with code 0 for http://localhost:51600/manifest?id=80149088&dolby=true&hevc=false&hdr=false&dolbyvision=false&vp9=false:
10:51:10.810 T:11160   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://localhost:51600/manifest?id=80149088&dolby=true&hevc=false&hdr=false&dolbyvision=false&vp9=false
10:51:10.810 T:11160   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://localhost:51600/manifest?id=80149088&dolby=true&hevc=false&hdr=false&dolbyvision=false&vp9=false)
10:51:10.811 T:11160   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27writer%27%3A+%27%27%2C+%27episode%27%3A+1%2C+%27plot%27%3A+u%27Der+brutale+Mord+an+einer+militanten+jungen+Lehrerin+bringt+Conde+auf+die+Spur+eines+Drogenbarons+mit+Verbindungen+zu+seiner+ehemaligen+Schule.%27%2C+%27season%27%3A+1%2C+%27tvshowtitle%27%3A+u%27Four+Seasons+in+Havana%27%2C+%27title%27%3A+u%27Die+Winde+der+Fastenzeit%27%2C+%27mediatype%27%3A+u%27episode%27%2C+%27mpaa%27%3A+u%27-%27%2C+%27director%27%3A+%27%27%2C+%27genre%27%3A+u%27Spanische+Serien%27%2C+%27year%27%3A+2016%2C+%27duration%27%3A+5776%7D&video_id=80149088&pin=False&start_offset=2794]
10:51:10.811 T:11160  NOTICE: CVideoPlayer::OnExit()
10:51:10.870 T:4780  NOTICE: CVideoPlayer::CloseFile()

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Raspberri-Pi
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18 RC1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MartijnKaijser** [comment]
Netflix is not a core part of Kodi. Please report this in the correct location.
