### ISSUE TITLE
Leia RC1 inexplicably thinks that the system is muted

### ISSUE THREAD

**Issue by froginperil** [xbmc/xbmc#14932]
Environment = Amazon Fire TV, second generation.
I have been running Krypton for some time without issue. Leia RC installed yesterday (32 bit).
Running a smart playlist. Around the 6th track it suddenly stopped producing sound.
Screen displayed a red speaker with an x and no sound would be produced.
All apps outside of Kodi working as expected. Full sound and no indication of mute.
After re-boots did nothing, I shut my entire entertainment system down from the power supply. No joy. The red speaker with the black X still there.
I installed a nightly via adb (-r). No help.
I uninstalled Kodi and then installed a nightly to solve the problem.

**Comment by MartijnKaijser** [comment]
Additionally the red speakers means it's muted. Use the android remote or something else to increase the volume again. Please use the forum for questions like this
