### ISSUE TITLE
Screens flicker when going in and out of fullscreen

### ISSUE THREAD

**Issue by Djinn1** [xbmc/xbmc#14931]
### Describe the bug
Here is a clear and concise description of what the problem is:

I am using Kodi 18 RC1 when going in and out fullscreen all my screens flicker for just one second. Why is that? 

I have 3 screens connected to my computer. Even when TV is off with dual screen setup it flickers.

Same problem on all Kodi 18 releases, tried them all.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No flickering should happen like Kodi 17.6. 

## Actual Behavior

All screen flicker for  just 1 second. I am using alt + enter to go on and off fullscreen.

## Possible Fix

I don't know

### To Reproduce

1. Maybe using same spec machine, AMD CPU with NVIDIA video card with latest drivers.
2. Dual setup monitor or 3 monitor.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/iyilihocaq

### Screenshots 
Here are some links or screenshots to help explain the problem:

Not possible it is a video issue

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Nothing

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 1803
 - Kodi version: Kodi 18 RC1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*
I

**Comment by pkerling** [comment]
@afedchin @Paxxi Is this expected behavior? Did fullscreen change in v18?
