### ISSUE TITLE
[games] controllers not working on Android due to virtual system controllers

### ISSUE THREAD

**Issue by da-anda** [xbmc/xbmc#14938]
### Describe the bug
Here is a clear and concise description of what the problem is:

On many Android platforms the OS is reporting "virtual" controllers in addition to the physically connected ones to Kodi. Those virtual devices are in many cases listed as the first device/controller in the peripherals dialog in Kodi. When launching a game, Kodi is using the first controller from that list as input device for the games instead of the physical controller which results in the controller not working in games.

Affected devices are f.e. the nVidia SHIELD TV as well as several Smart TVs running AndroidTV (f.e. Philips).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

KODI should either forward just any controller input, regardless of which device as long as there is no player manager and thus no multiplayer-support yet, or keep track on the last used controller and use that (or ask on launch of a game)

## Actual Behavior

KODI just picks whatever controller is reported as first controller by the OS and uses it for games

## Possible Fix

a) forward any input
since we don't have a player manager yet and thus also no proper multiplayer support for games, just forward any controller input to player 1 and be done. Might be the easiest solution for Leia release.

b) smart choice + user choice
smart choice:
Kodi could track which controller has been used to launch the game (last active controller) and simply use this controller for the current gaming session

user choice:
If more than one controller are connected, ask the user on start of a game to press any button on the controller to use for this gaming session. The choice could/should be cached in either a setting or just in memory for as long as the number of connected controllers does not change (creating a hash over all controller IDs and remember the user decision per hash-list). As soon as the list of connected devices/controllers changes, either ask user again on next launch of a game, or be smart and use the last used controller if it's still connected.
For cases when user decides to plug another controller after the game has already been launched, there needs to be a way to switch to the new controller. For this we should add a new entry to the game menu ("choose controller" or alike) which then triggers the dialog "press any key on the controller you would like to use for this game" again (same dialog that would be fired on launch on a game and no cached user decision).

### To Reproduce

just try to play any game on a SHIELD TV or AndroidTV based smart TV

### Debuglog

Debuglog was already provided to @garbear and he identified the issue as per my description above.
https://paste.kodi.tv/maraqowiha

### Screenshots 
Here are some links or screenshots to help explain the problem:

user report with response by garbear https://forum.kodi.tv/showthread.php?tid=335770&pid=2790772#pid2790772
some more info/discussion in the comments of #14658

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Leia RC1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

@Razzeee FYI

**Comment by Razzeee** [comment]
So should this be closed?

**Comment by Razzeee** [comment]
Tested this yesterday and it worked without a hitch.
