### ISSUE TITLE
RPI3B+ Player can't Stop after switching Framerate adjust is active on Milhouse Build

### ISSUE THREAD

**Issue by Timmiotool** [xbmc/xbmc#14953]
### Describe the bug
Here is a clear and concise description of what the problem is:
Milhouse # 1024, is OK # 1124 not OK.

After activate the option Adjust Display Refresh Rate to start/stop or always there is a Problem with the Player. When you stop a Movie nothing happends theres a freeze. When the Option is deactivated theres no Problem..it seems here is a Problem with the Framerate adjust from the Movie back to the Kodi GUI.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix
switch Adjust Display Framerate to OFF.

### To Reproduce

1. KODI GUI 60 HZ, Adjust Display Framerate ON (start/stop)
2. Play a Movie with 25 HZ or whatever
3. Stop the Movie and then the Player freeze.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Milhouse # 1124

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by da-anda** [comment]
thanks for your report. Since there is an entire month in between those builds it would be good if you identify the specific build

**Comment by Timmiotool** [comment]
I'm back to #1104, 04-Nov-2018: RPi / RPi2 -- Release post (New 4.19.1 kernel; eventlircd: prevent race with libinput / kodi; avoid managing ZeroTier network interfaces) there is the Problem to.

so the Problem beginns with one of these:
#1103, 03-Nov-2018: RPi / RPi2 -- Release post (bump to v18.0 RC1; FFmpeg: Bump to 4.0.3-Leia-Beta5)
#1102, 02-Nov-2018: RPi / RPi2 -- Release post ([GLES] VideoPlayer: more cleanup; libcec, p8-platform updates; cputemp fixes)
#1101, 01-Nov-2018: RPi / RPi2 -- Release post (bump libdvdcss to 1.4.2-Leia-Beta-5 (kodi PR); [VideoPlayer] SetResolution synchronously instead RM::TriggerResolution)
#1031, 31-Oct-2018: RPi / RPi2 -- Release post (Fix RES_DESKTOP calibration setting assignement; fix include auto-mounted drives remote access allowed check)
#1030, 30-Oct-2018: RPi / RPi2 -- Release post (Correctly read artist art after Coverity scan fix; [Estuary] Video OSD and Music OSD enhancements/fixes.)
#1029, 29-Oct-2018: RPi / RPi2 -- Release post ([GLES] VideoPlayer: YUV2RGB rework, Tonemapping, and other cleanup)
#1028, 28-Oct-2018: RPi / RPi2 -- Release post (Resolution: Use v17 behaviour if whitelist is not present; [PVR][Estuary] Add GUI for Radio Data System (RDS).)
#1027, 27-Oct-2018: RPi / RPi2 -- Release post (Fix RDS stream support)
#1026, 26-Oct-2018: RPi / RPi2 -- Release post ([Estuary] bug fixes; fix DVD Menu issues with MMAL)
#1025, 25-Oct-2018: RPi / RPi2 -- Release post (Various Game related changes)

Sorry, i can't say the correct Build for now  but i think after #1101.... if you want i can test this later ...!

**Comment by MartijnKaijser** [comment]
Please do not use the # symbol cause that starts linking completely unrelated issues/PRs. So edit all your comments @Timmiotool

**Comment by lrusak** [comment]
@Timmiotool before the commit https://github.com/xbmc/xbmc/commit/1e439443c4836667a034839af7e5ba1344eb97e9 you had to manually add the desired modes to the whitelist (settings -> system -> display -> whitelist). You had to choose the modes that you want to use (not necessarily all of them). So if I was you I would play with setting some whitelist values and seeing if you can get it to work properly.

Before https://github.com/xbmc/xbmc/commit/1e439443c4836667a034839af7e5ba1344eb97e9 if you didn't have a any resolutions selected in the whitelist then no resolution switching would occur. So you need to verify that you were actually switching resolution in build 1027.

I hope that makes sense.
