### ISSUE TITLE
Movie Sets with Overviews not showing Movie List

### ISSUE THREAD

**Issue by heitbaum** [xbmc/xbmc#14955]
### Describe the bug
Here is a clear and concise description of what the problem is:

As per the documentation https://kodi.wiki/view/Movie_sets and I believe the functionality in 17.0 was that the Movie Set would show the movies in the set. e.g.
Star Wars Collection
1977 - A New Hope
1980 Empire Strikes Back 
..... 

What is happening the 18.0 is that the list is not appearing - but the overview is appearing if it has been set.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

That both the overview and the list of moves is displayed. e.g.

BOLD Star Wars Collection BOLD
In a  galaxy far, far, away .....
1977 - A New Hope
1980 Empire Strikes Back 
..... 

## Actual Behavior

BOLD Star Wars Collection BOLD
In a  galaxy far, far, away .....

## Possible Fix

I have looked into the code - but can't find the skin location but I'm thinking the code is written as such.
if (overview) then 
 print(overview) 
else
 print (list)

I would think it should be
 print(overview) 
 print (list)

### To Reproduce

1. Movie collections with Overviews 

### Debuglog

The debuglog can be found here:
Debug is at http://ix.io/1rxq

I had originally thought that the issue was isolated to some sets, but after validating the data queries - the "list" works only when there is no overview.
And worked out using debug - that when we see: "DEBUG: CWebServer[8080]: request received for /jsonrpc" - the set list is not there
and that when we see "DEBUG: CDirectoryProvider[videodb://movies/sets/14/?setid=14]: refreshing.." we do see the data.
99% of the data is from Online - TheMovieDB

### Screenshots 
Here are some links or screenshots to help explain the problem:

This is the expected list view:
https://kodi.wiki/images/thumb/3/33/MovieSets01.jpg/400px-MovieSets01.jpg

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

https://forum.libreelec.tv/core/attachment/4096-screen-shot-2018-09-08-at-10-54-04-am-png/
These were the originally reported bugs - but as further testing has been done - it is isolated to sets with overviews.

Some examples of it working with the titles.
![screenshot002](https://user-images.githubusercontent.com/6086324/49075850-c8521a80-f28b-11e8-89e9-e57b3d654622.png)
![screenshot001](https://user-images.githubusercontent.com/6086324/49075852-c8eab100-f28b-11e8-8ca2-cae1a589e7fc.png)
![screenshot000](https://user-images.githubusercontent.com/6086324/49075854-c8eab100-f28b-11e8-9d25-63faf68e2cf6.png)

Original LibreELEC bug: https://forum.libreelec.tv/core/ticketsystem/ticket/14-in-sets-the-side-bar-is-not-consistently-showing-the-movies-within-the-set/?action=firstNew
TRAC reported: https://trac.kodi.tv/ticket/18044

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC (Milhouse): devel-20181126210238-#1126-g4904957 (Generic.x86_64)
 - Kodi version: 18.0 RC

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Should be fixed already for Kodi master:

https://github.com/xbmc/xbmc/pull/14909

**Comment by DaVukovic** [comment]
Sorry, have to add something, because I missed that part:

>That both the overview and the list of moves is displayed. e.g.

We tried that, but we can't do that for every view at Estuary because of the lack of space which is available. It might work for sets which only have a few movies. But what would you do with the "James Bond" collection which has about 20+ movies?

For now it's like

- if the set has an overview show that
- if the set doesn't have an overview, show the movies which the set contains in a list.

**Comment by huseyin7734** [comment]
Hey

27 Kas 2018 23:16 tarihinde "DaVukovic" <notifications@github.com> yazdı:

Sorry, have to add something, because I missed that part:

That both the overview and the list of moves is displayed. e.g.

We tried that, but we can't do that for every view at Estuary because of
the lack of space which is available. It might work for sets which only
have a few movies. But what would you do with the "James Bond" collection
which has about 20+ movies?

For now it's like

   - if the set has an overview show that
   - if the set doesn't have an overview, show the movies which the set
   contains in a list.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/xbmc/xbmc/issues/14955#issuecomment-442201727>, or mute
the thread

**Comment by heitbaum** [comment]
> Sorry, have to add something, because I missed that part:
> 
> > That both the overview and the list of moves is displayed. e.g.
> 
> We tried that, but we can't do that for every view at Estuary because of the lack of space which is available. It might work for sets which only have a few movies. But what would you do with the "James Bond" collection which has about 20+ movies?
> 
> For now it's like
> 
> * if the set has an overview show that
> * if the set doesn't have an overview, show the movies which the set contains in a list.

Thanks for the full and complete explanation. 

I had a try with the code e.g. making some changes to MyVideoNav.xml - and I concur, just not enough space. Some ideas may be to have 2 textbooks on the Left in list view - maybe with autoscroll for the movie list / overview - or even popup like is in the info section.

In the interim I have gone back to the previous behaviour (list of movies) instead of the overview for the set -- I'm actually not sure which one i like - now that I have done that. 

I was thinking of putting a variable on the settings page that would allow me to change the style - from overview to list. I'll keep trying some options and will update if I stumble across something that "might work".

Thanks again for the response

**Comment by heitbaum** [comment]
@DaVukovic, I agree. Let’s close it (it’s not a bug now) and now is relegated to a potential enhancement if someone... (me/you/others) can work out a way the user interface can be done elegantly.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DaVukovic** [comment]
Ok closed
