### ISSUE TITLE
OMX Live playback stuttering

### ISSUE THREAD

**Issue by hpmueller1971** [xbmc/xbmc#14958]
### Describe the bug

with the Leia/Millhouse builds and the LE-alphas, i have an annoying stuttering when switching to a channel, it plays for about 1second, then pauses for 1second, plays 0.1-0.2 seconds, pauses for 0.2seconds and then plays without any interruptions.

I originally opened this on the pvr.hts bugtracker, which was promptly closd ("Definatly not an addon issue"), which turned out to be completely right, i can now also reproduce the issue with pvr.simpleiptv and with pvr.zattoo. Happens on high-bitrate-fullhd (SRF1 HD with 18mbps) channels as well as on super-low-bitrate-SDTV channels. Except OMX, no other option seems to have any impact on the issue (including the usual suspects like framerate-switch, sync-to-display, PLL, or various buffering settings in advanced.xml). Its also worth mentioning that everything else, including DVR-Recordings do *not* have the stutter.

## Expected Behavior
Smooth Playback ;)

## Actual Behavior
Stuttering for the first ~5sec of a live-channel

## Possible Fix
Use MMAL, or revert to KRYPTON

### To Reproduce
Start any live DVR program with OMX enabled  (tested with pvr.hts, pvr.simpeiptv and pvr.zattoo)

### Debuglog

I combs hours through the logs, the only thing that stands out:

19:38:37.542 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:37.645 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:37.759 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:37.908 T:1497748336 DEBUG: CVideoPlayer::OMXDoProcessing Pause 0.43,0.00 (A:01 V:10) EOF:0 FULL:0 T:0.40
19:38:37.908 T:1497748336 DEBUG: OMXClock::OMXSetSpeed(0.000) pause_resume:1
19:38:37.959 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:38.259 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:38.376 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:38.576 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:38.676 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:39.194 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:39.410 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:39.611 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:39.727 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:39.927 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:40.028 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:40.244 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:40.344 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:40.346 T:1497748336 DEBUG: CVideoPlayer::OMXDoProcessing Resume 3.03,0.40 (A:01 V:01) EOF:0 FULL:0 T:0.40
19:38:40.346 T:1497748336 DEBUG: OMXClock::OMXSetSpeed(1.000) pause_resume:1
19:38:40.461 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:40.561 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:40.661 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:38:40.855 T:1497748336 DEBUG: CVideoPlayer::OMXDoProcessing Pause 2.87,-0.04 (A:01 V:10) EOF:0 FULL:0 T:0.80
19:38:40.855 T:1497748336 DEBUG: OMXClock::OMXSetSpeed(0.000) pause_resume:1
19:38:40.878 T:1309660016 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer

This is from playback with OMX, when using MMAL it looks the same, the only difference are the lines with OMX, but the CRender-Timeouts are there with MMAL too, but no stuttering. Is there a way to log more that just "turn on debug"...?

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC, Millhouse builds and official alphas
 - Kodi version: Kodi 18 since at least July (when i started testing Lea)

Regards

/hp

**Comment by lrusak** [comment]
I'm just curious as to why you want to use OMX? MMAL is the default now.

**Comment by mkreisl** [comment]
> I'm just curious as to why you want to use OMX? MMAL is the default now.

I'm struggling with OMX stuttering too, but here, that strange stuttering never goes away. Using XBian instead of LE

@lrusak 
For RPi2 and higher MMAL is ok, but with an RPi1, MMAL is still not usable for me, I never get completely smooth playback with MMAL That's why I'm still using OMX on Pi1

**Comment by allcoolusernamesaregone** [comment]
I also have this issue.
It's easy to  reproduce: current libreelect 9.0.1 on a rpi 3 with tvheadend addon 4.4.16 and omx player hardware accelaration enabled. With https://tvheadend.org/issues/5611 I added a verbose debug log and more information. If omx hardware acceleration is disabled the issue disappears.

**Comment by iMiMx** [comment]
Seeing exactly the same, disabling OMX fixes the issue.

But on a Pi 3B running OSMC, MMAL is unusable, sync drifts in and out and I can't find any buttons to twiddle that help.  Similar to someone else, I'd rather put up with the initial stutter than use MMAL.

**Comment by fuzzard** [comment]
Ive been told OMX is no longer relevant in v19, and there are no further v18 releases
