### ISSUE TITLE
I can't play some mp4 files. 

### ISSUE THREAD

**Issue by kolunio82** [xbmc/xbmc#14968]
Hi guys,

what is wrong with you? I still have a problem with playing files. I attached log from kodi Andorid and from kodi windows. But issue is marked as invalid and thread is closed. Can someone please explain me why? 

https://github.com/xbmc/xbmc/issues/14809#issuecomment-442593359

**Comment by MartijnKaijser** [comment]
You were asked to take further discussions and testing to the Kodi forum here:
https://github.com/xbmc/xbmc/issues/14809#issuecomment-437086846
Since this is not a correctly submitted bug issue (and judging from the other ticket not entirely clear as well) i will close this one.
