### ISSUE TITLE
Inferior GUI performance after running a game or enabling teletext

### ISSUE THREAD

**Issue by smp79** [xbmc/xbmc#14966]
### Describe the bug

I noticed this issue over a year ago, so it's not new. If I enable and then disable teletext - the frame rate of the "sliding" Estuary menus will drop - the smoothness is gone until Kodi is restarted (this issue is very noticeable when using a TV channel list). It's not a massive drop - but just enough to make it noticeable and annoying. I didn't really care about this because who really use teletext, right? However, I recently found out that this issue is also triggered by using Retroplayer. If I run and then exit any game - Estuary is not smooth anymore until Kodi is restarted.

### To Reproduce

Enable and disable teletext **or** run and exit any game from within Kodi.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/opuxazigiz.kodi

### Your Environment
Used Operating system:

 - [x] Raspberry-Pi

The issue could be specific to Rpi/GLES because I don't see this behavior on a powerful PC.

 - Operating system version/name: LibreELEC
 - Kodi version: 18, current master

**Comment by lrusak** [comment]
I don't see anything specific in the log just a lot of sync stream errors. I will see if we can reproduce the issue.
