### ISSUE TITLE
Leia - no video on start live TV

### ISSUE THREAD

**Issue by gilesp1729** [xbmc/xbmc#14969]
### Describe the bug
Here is a clear and concise description of what the problem is:

I am getting a video problem, new on Leia. On starting live TV there is no video, the Music OSD comes up instead, or else video freezes for ~10 seconds and audio is out of sync. Eventually comes good after a couple of channel changes. Leia beta5 or RC1 (doesn't happen in Krypton), Windows, with LibreELEC Rpi backend. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video and audio start together and in sync.

## Actual Behavior

Intermittently, No video, music OSD appears instead of video/liveTV OSD. Audio plays. Alternatively, video starts but freezes ~10 sec (like issue 14828). Clears after 2-3 channel changes and does not appear to return in that Kodi session.

### To Reproduce

1. Start Kodi
2. Tune in any live TV channel from guide, channels, or recents
3.

### Debuglog

The debuglog can be found here:
https://pastebin.com/z8Q37c4H

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Leia Beta4, 5, RC1 (Windows 10), TVH client addon 4.4.2
TVHeadend on LibreELEC on RaspberryPi (server)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Thanks for the report. I'll attach someone to look at it.

Seems like an odd issue and I'm not sure what is causing the following behavior
```
09:04:41.168 T:9532   DEBUG: CVideoPlayer::HandleMessages - player started 2
09:04:41.168 T:7528   DEBUG: CApplication::OnAVChange: CApplication::OnAVChange
09:04:41.168 T:8664   DEBUG: CAnnouncementManager - Announcement: OnAVChange from xbmc
09:04:41.168 T:8664   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnAVChange
09:04:41.187 T:2496   DEBUG: CWinRenderer::CreateIntermediateRenderTarget: format 87.
09:04:41.336 T:2496   DEBUG: ------ Window Deinit (MyPVRGuide.xml) ------
09:04:41.336 T:7840   DEBUG: Thread epg-grid-refresh-timeline-items 7840 terminating
09:04:41.345 T:2496   DEBUG: FreeVisualisation() done
09:04:41.383 T:2496   DEBUG: ------ Window Init (MusicVisualisation.xml) ------
09:04:41.383 T:2496    INFO: Loading skin file: MusicVisualisation.xml, load type: KEEP_IN_MEMORY
09:04:41.386 T:2496   DEBUG: ------ Window Init (DialogSeekBar.xml) ------
09:04:41.388 T:2496   DEBUG: ------ Window Init (Custom_1109_TopBarOverlay.xml) ------
09:04:41.438 T:9532   DEBUG: CDVDClock::SetSpeedAdjust - adjusted:0.000000
09:04:41.937 T:1964   DEBUG: ActiveAE::SyncStream - average error 19.988307, last average error: 860.747447
09:04:42.020 T:9532   DEBUG: CVideoPlayer::HandleMessages - player 1 reported state: 2
09:04:42.045 T:1964   DEBUG: ActiveAE::SyncStream - average error of -25.023640, start adjusting
09:04:42.045 T:1964   DEBUG: ActiveAE::SyncStream - average error -10.023640 below threshold of 30.000000
09:04:43.046 T:2496   DEBUG: ------ Window Init (MusicOSD.xml) ------
09:04:43.046 T:2496    INFO: Loading skin file: MusicOSD.xml, load type: KEEP_IN_MEMORY
```

**Comment by gilesp1729** [comment]
Then why does it not happen on Krypton?

**Comment by FernetMenta** [comment]
> Then why does it not happen on Krypton?

If a symptom does show does not mean the issue is not there.

After having refreshed my memory I noticed that I addressed this shortcoming of tvh in Kodi already:

https://github.com/xbmc/xbmc/pull/14408

Seems it broke for some reason.

**Comment by M2k80** [comment]
i have the same problem on enimga2 live plugin.
it feels like its getting worse since dts/pts fix from 28.

**Comment by M2k80** [comment]
@FernetMenta this happens for pvr.vuplus too on android (nvidia shield), so its not only a windows or tvh problem

**Comment by FernetMenta** [comment]
I doubt that this (vuplus/Android) is the same issue. The issue related to this bug report here is already identified. It is caused by a change by @peak3d https://github.com/xbmc/xbmc/pull/14545
I pinged him for a fix.

**Comment by peak3d** [comment]
Please try https://github.com/xbmc/xbmc/pull/15010

**Comment by peak3d** [comment]
@M2k80  a build artefact can be found here: https://jenkins.kodi.tv/job/Android-ARM64/8427/

**Comment by M2k80** [comment]
thank you, i will report later this day

**Comment by M2k80** [comment]
@peak3d actually it seems there is no more music osd and its fine on my shield, but another problem is still there. i hoped this fix would fix it too, but it does not.

should i open a new issue for that?
it happens on start or channel switch, screen stays black for 5 sec, sound is working.
just havent debug enabled, but a short snippet with many error reports
https://paste.ubuntu.com/p/FSF8dkJDMn/

**Comment by gilesp1729** [comment]
I tested again on RC3 and could no longer repro. Have any changes gone in that could affect? Or is it a heisenbug?
