### ISSUE TITLE
EPG update interval doesn't match with the PVR setting 

### ISSUE THREAD

**Issue by janbar** [xbmc/xbmc#14963]
### Describe the bug

EPG update runs every 5 minutes , despite the setting (defaulted with 120 min). Getting guide for many channels is an high cost operation for the backend and can get more than 5 minutes to retrieve the range of data. Is the reason of the setting and its default value (120 min). 

## Expected Behavior

EPG update should run every 120 min according to the setting.

## Actual Behavior

An EPG update bumps the backend every 5 min.

## Possible Fix

Use the PVR setting to schedule the EPG update.

### To Reproduce

1. Launch kodi 
2. scan for api call in log

### Debuglog

The debuglog can be found here:
https://pastebin.com/e6e7avmk

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.0-RC2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Is "Don't cache in local database" setting enabled or disabled? If it is enabled (which means no cache - confusing, but another story) does disabling it (means to enable caching) make a difference?

**Comment by janbar** [comment]
it is disable.

**Comment by janbar** [comment]
The same with the cache enabled: every 5 minutes it launch an update.

**Comment by ksooo** [comment]
For which channels GetEPGForChannel gets called every 5 mins? For all channels? Or only for those which have no EPG?

**Comment by janbar** [comment]
don't know :D. I have to get more log...

**Comment by janbar** [comment]
It calls for channels without EPG

**Comment by ksooo** [comment]
Seems to work as designed. It worked always like that. No changes in logic since first merge of PVR code into kodi master. I tend to say this is not a bug.

**Comment by ksooo** [comment]
Kodi has no clue why it gets no EPG data for a certain channel. There could be so many reasons for that. If people dont like that (or because your latest performance improvements in pvr.mythtv clash with that) they can increase value of advanced setting `updatecheckinterval`.

**Comment by janbar** [comment]
Thanks for your help. I didn't aware about this behavior and the related setting. I don't think the end user want to setup kodi, and so instead I could fill the epg for those channels with fake data. That's should work.

**Comment by lama18** [comment]
https://github.com/kodi-pvr/pvr.iptvsimple/issues/202

Again, I'm opening this issue, I still have the impression that this bug is. I have an XMLTV file for 3 days, but Kodi downloads data every 5 minutes.

**Comment by AnonTester** [comment]
epg.epgupdate interval setting doesn't appear to be working as it should. I set the value to 1500 minutes, but it's trying to update more often (the default of 120 mins is also being ignored):

$ grep "EPG" kodi.log 
10:31:16.338 T:140575193941760  NOTICE: EPG thread started
10:31:17.383 T:140575076509440  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
10:36:17.772 T:140575076509440  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
11:36:17.411 T:140575076509440  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
11:41:17.465 T:140575076509440  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.

Kodi version: 18.1-RC1 Git:20190204-077fde4 Media Center Kodi
OS: Ubuntu 18.04.1 LTS, 
Kernel: 4.15.0-45-generic

**Comment by AnonTester** [comment]
Added to advancedsettings.xml and restarted kodi:
  <epg>
    <updatecheckinterval>1500</updatecheckinterval>
    <updateemptytagsinterval>2880</updateemptytagsinterval>
  </epg>

Update frequency for an empty EPG is every 50 minutes:
12:41:37.850 T:140060007585536  NOTICE: EPG thread started
12:41:38.851 T:140059890153216  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
13:31:38.410 T:140059890153216  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
14:21:38.919 T:140059890153216  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.

It appears the updateemptytagsinterval setting is interpreted as seconds and not in minutes as the wiki states.
This post from 2015 noted a seconds/minutes issue as well: https://forum.kodi.tv/showthread.php?tid=237109

https://github.com/xbmc/xbmc/blob/master/xbmc/settings/AdvancedSettings.cpp
It appears the default is set to 1 minute for empty EPGs and 5 minutes for regular updates.

I'm still learning python, but I couldn't see references to the updatecheckinterval / epg.epgupdate user setting from the settings -> PVR -> Guide settings menu in the EPG code here https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/epg/Epg.cpp and I'm wondering if the user setting is ignored and therefore an advancedsettings entry is required?

For empty EPG urls, what's the point in checking it over and over again anyway? Wouldn't it make more sense to stop checks when initialising and no URL is available?

**Comment by ksooo** [comment]
Please move this kind of discussion to the forum. There is a pvr Deb section.

**Comment by lama18** [comment]
https://forum.kodi.tv/showthread.php?tid=340357&pid=2818278#pid2818278

**Comment by ksooo** [comment]
> For empty EPG urls, what's the point in checking it over and over again anyway? Wouldn't it make more sense to stop checks when initialising and no URL is available?

 Kodi knows nothing about (empty) EPG URLs. If at all the, the PVR addon does. Thus, only the addon could “fix” something here.

**Comment by ksooo** [comment]
> and I'm wondering if the user setting is ignored and therefore an advancedsettings entry is required?

 Definitely not. The settings simply have different semantics. Try harder to understand the code. ;-)

**Comment by AnonTester** [comment]
not sure why you're ignoring the main issue I'm trying to highlight here:
updateemptytagsinterval in advancedsettings.xml is used as seconds where the kodi documentation for advancedsettings.xml states it's in minutes. https://kodi.wiki/view/Advancedsettings.xml#epg

This means either the wiki is wrong and needs to be updated or the code is wrong.

**Comment by lama18** [comment]
please let's solve the forum, it would be good to think of a solution and implement / modify it. Existing is not ideal if we all agree.

**Comment by ksooo** [comment]
> not sure why you're ignoring the main issue I'm trying to highlight here:

 Calm down. Who says I'm ignoring it? Meanwhile I "just" updated the Wiki page: https://kodi.wiki/view/Advancedsettings.xml#epg

**Comment by AnonTester** [comment]
well, a brief response as in "looking into the main issue" or such like would have helped and I wouldn't have assumed that you're ignoring me, my bug report or the issue itself. 

Anyway, thank you very much for updating the wiki and adding the additional information! That's very helpful and answers in detail how the EPG update logic works and why the GUI setting is unrelated to the channels without EPG data (and the minutes/seconds issue is fixed).

I agree with you all that there appears to be quite some room for improvement, and that's a different discussion for the forums :)

**Comment by ksooo** [comment]
> well, a brief response as in "looking into the main issue"

 Don't want to start any lengthy discussions, but the point is that the documentation bug in the wiki is far from being the "main issue" of this bug report. It's at best related, but not the main issue. That's why I in the first place decided not to answer this here. But I changed my mind, obviously.
