### ISSUE TITLE
Leia RC1 - Linux - 48 kHz AAC -> no audio

### ISSUE THREAD

**Issue by camelreef** [xbmc/xbmc#14973]
### Describe the bug
Here is a clear and concise description of what the problem is:

Video streams (from TV catch-up addons) and files (local) with a 48 kHz AAC audio track have no audio sent to my receiver (it shows nothing from its input info)
Resampling files to 44.1 kHz audio makes them play fine.
Youtube streams with 44.1 kHz AAC play audio fine.
multichannel 48 kHz AAC plays audio fine
48 kHz MP2 works fine

This used to work fine in 18beta4 and before (sorry, skipped 18beta5). I have switched to the nightly PPA, but no fix there.

I have found one stereo 48 kHz AAC file that plays fine, for some reason, which is very strange.

Existing Kodi Forums thread:
https://forum.kodi.tv/showthread.php?tid=337885

## Expected Behavior

Audio received by receiver through HDMI.

## Actual Behavior

No audio received by receiver through HDMI

### To Reproduce

A few sample files there. The -passthrough is the original stream, the other files were generated using Handbrake. Anything 48 kHz will output no audio

https://youplala.net/~nico/kodi/

### Debuglog

Various logs can be found here, with anything else needed provided if you need it:

KODI DEBUG LOG: 
https://paste.ubuntu.com/p/W8hxKDywXN/
MESA info:
http://paste.ubuntu.com/p/9KSfnj3GZv/
VAINFO:
http://paste.ubuntu.com/p/6YF6tnMtKp/
DMESG:
http://paste.ubuntu.com/p/t9gXPYDXBQ/
ID:
http://paste.ubuntu.com/p/tcsMJPNm8Y/
AMIXER:
http://paste.ubuntu.com/p/VKywCYQKgH/
XORG LOG:
https://paste.ubuntu.com/p/dFxnqbkFJy/

### Your Environment
Used Operating system:

Linux

 - Operating system version/name: Ubuntu 18.04.1 LTS, kernel: Linux x86 64-bit version 4.15.0-39-generic
 - Kodi version: 18.0-RC1 Git:20181121-314c302 x64 build
 - FFmpeg version/source: 4.0.3-Kodi
 - Host CPU: Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz, 4 cores available (Sandy Bridge)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by FernetMenta** [comment]
I tested on Ubuntu 18.04 and OSX. No issue.
I suspect an issue with your AVR.

**Comment by camelreef** [comment]
Hello!
Well, how do you explain the change from working to not working from one Kodi version to another, with the same OS and the same AVR? There was a clear failure after a Kodi upgrade.
I used to watch the French news stream every night without any problem, and it was already 48 kHz AAC...
So, I am not doubting that it worked for you, and that I may be a corner case, but I still went from "working" to "not working" after a Kodi change.
What changed between 18b4 and 18rc1 that broke it for me?

**Comment by camelreef** [comment]
There was a recent ffmpeg version change. Something worth investigating?
What can I do to help?
Is there any way I could compile an 18rc1 without that change?
If given enough instructions, I'm willing to do the leg work and put the CPU cycles.

**Comment by FernetMenta** [comment]
If it was an ffmpeg issue, I would have noticed the issue too. I am sure you'll get audio if you move your AVR out of the chain. Try connecting the PC directly to the TV and drop the did preload hack.

**Comment by camelreef** [comment]
it... worked...until... I got to rc1...
The only change was the Kodi software. The AVR was there, the HDMI cable was there...
I would fully blame the AVR if it had never worked before. But it did.
I'm not saying that the AVR is totally blameless, those things are quirky and firmwares written with varied attention to details... I actually had to upgrade my AVR's firmware (the serial cable way) because it was buggy around HD bitstreams. I accept that my AVR may have an issue, this issue only recently got highlighted by a change in Kodi.

it... worked... before...

**Comment by FernetMenta** [comment]
Since you do not follow my instructions to narrow down the issue, I stop wasting my time on this. Good luck.

**Comment by FernetMenta** [comment]
This proves that ffmpeg does not cause the issue. Put the AVR back and disable refresh rate switching. I guess this will make it work too.

**Comment by camelreef** [comment]
OK. Tip of the hat...
Indeed, I get sound back with refresh rate switching disabled!

What does it point to, at this stage?

**Comment by camelreef** [comment]
So, with refresh rate switching as a factor, I came back to that other 48 kHz AAC audio file I had, and that worked. The difference with the one that didn't work was the video FPS. 

So I took my problematic test file, kept the audio as-is, and forced the video from 25fps to 50fps in Handbrake. (test file added to the others online)
And I got audio back.

Another proof that the audio quirk is linked to the video track's refresh rate...

**Comment by nsenica** [comment]
Could this be linked somehow to #14939 ?

**Comment by camelreef** [comment]
In Settings / System / Audio, I switched Output configuration from "Optimized", to "Fixed" and gained audio back.

What consequence does it have elsewhere?

**Comment by camelreef** [comment]
Yes, I had a delay of 2.5s. I tried pushing it up to 5s with no positive result.
I had also tried none, 0.5, 3 and 4s.

I am not home anymore for a few hours, but I can try to progressively go beyond 5s, just in case, even if not really a solution that I am contemplating with any sort of eagerness!

Also, what sort of difference is there / can I expect between the "Always" and "On Start/Stop" refresh rate switched?
I have played with this setting and various delays, already, with no positive result, but wonder how systematic I was...

When you say "old hardware", do you mean the computer or the AVR?

And, remember, it used to work at least until 18b4! :-)

(in parallel, I have managed to have a line opened with Denon support, initially because of a, now fixed using the latest firmware, HD bitstreams issue. I am going to poke then about that 25fps/48kHz PCM thing, you never know... But I do not expect a new firmware version to be released in any way, shape or form!)

**Comment by FernetMenta** [comment]
> When you say "old hardware", do you mean the computer or the AVR?

I mean the PC, Sandy Bridge was released 2011.

> Also, what sort of difference is there / can I expect between the "Always" and "On Start/Stop" refresh rate switches?

Not related here. If you set it to Start/Stop, you can leave fullscreen video and browse the UI while video keeps plying at video fps. Avoids a switch back to desktop refresh rate.

I think the code change that triggered the issue here is that the change of refresh rate happens earlier now. Means audio configure is done after mode change. Your observation of setting audio config to "fixed" cures the issue points into the same direction. This setting instructs audio engine not to change the config.

**Comment by camelreef** [comment]
> I think the code change that triggered the issue here is that the change of refresh rate happens earlier now. Means audio configure is done after mode change. Your observation of setting audio config to "fixed" cures the issue points into the same direction. This setting instructs audio engine not to change the config.

Does that give me a sliver of hope? Or was the change made to fix a much bigger issue making mine irrelevant?

**Comment by camelreef** [comment]
OK, I tested a delay of 7, 15 and 20s (the max).
Still no sound...

The funny thing is that when I stop the video, I get the UI back pretty quickly, but the sound takes the time of the delay to come back. I would have expected more time for the UI to come back too...

**Comment by fritsch** [comment]
Remove the AVR, please - and test with the TV directly ... what happens with your 48 khz / 2 channel 32 bit ACC?

**Comment by Leatherface75** [comment]
Maybe you could try play with .asoundrc file?
I have a similar problem but with 44100hz sound and i solved that with this in that file

pcm.!default {
    type hw
    card 0
    device 7
    rate 48000
}

You could use builtin resample in Kodi but that makes Dolby Pro Logic and things like that not working on AVR.

**Comment by camelreef** [comment]
I'm not a total numpty, but not an exert either!
I've found the build instructions. But I have not found the set that spits deb packages, which would be my prefered approach instead of having wild binaries that may clash with the installed packages or that I need to manually clean up at some point
Did I miss a page?

**Comment by FernetMenta** [comment]
You can run Kodi from the folder you built it. If you do "make install", it gets installed into /usr/local. "make uninstall" used to work. Check /usr/local after uninstall -> no need to worry about clashing binaries.

**Comment by camelreef** [comment]
OK, I'll give it a go in a few hours!

**Comment by fritsch** [comment]
@fernetmenta: jep I plain overread that, thst we already have this information... yeah what I expected.

**Comment by camelreef** [comment]
Do I need to build the binary addons?

**Comment by camelreef** [comment]
> @camelreef you know how to compile from source, don't you? comment this line and try again:
> https://github.com/xbmc/xbmc/blob/master/xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp#L832

Same result, I'm afraid...

Debug log: https://pastebin.com/2khRuwgR

**Comment by camelreef** [comment]
The debug log from using my self built Kodi from git, but with the display reset line commented out.

Same result, no sound, and I get a picture freeze after a while.

https://youplala.net/~nico/kodi/no_display_reset_kodi.log

**Comment by camelreef** [comment]
It really appears that 25fps refresh rates are a trigger...
Using the nightly build PPA, mkv file with 1920x960x25 h.264 video, and EAC3 audio, with passthrough audio, no sound when adjust refresh rate is on. Audio comes back when the adjust is off.
Same thing, it used to work until 18b4.

Debug log: https://paste.ubuntu.com/p/H8p4pPdnrS/

**Comment by FernetMenta** [comment]
> https://youplala.net/~nico/kodi/no_display_reset_kodi.log

This log is useless. Please turn off component logging and post a new log. Also disable passthrough audio for all further tests. (there is no passthrough for live tv -> you compare apples and oranges)

**Comment by camelreef** [comment]
Here is, I hope, a more usable debug log from the self built with the display reset line commented out:
Passthrough audio disabled

https://paste.ubuntu.com/p/cTHtd9jPxt/

I'm sorry if I mess up sometimes or if I provide useless or irrelevant data in the wrong context. I'm just trying to participate beyond "it doesn't work, it used to, fix it!". 
I am very happy that you are giving me all that time of yours!

**Comment by FernetMenta** [comment]
Could you please test another scenario with non self-compiled build.

- make sure ou desktop is at 60Hz
- start kodi in standalone mode
- go do settings and set display to 50 Hz
- make sure 25Hz mode is NOT whitelisted
- play video that caused issues

Do you have sound? Please post debug log.

**Comment by camelreef** [comment]
Sure, no problem, I'll do that once I get back home in a few hours (I'm not ignoring the request!).

As a note, Kodi is always started as stand-alone, if I understand the following command in the Openbox autostart:

```
$cat /home/kodi/.config/openbox/autostart 
OUTPUT=`xrandr -display :0 -q | sed '/ connected/!d;s/ .*//;q'`
xrandr --display :0 --output LVDS-1 --off
xrandr -display :0 --output HDMI-1 --set "Broadcast RGB" "Full"
xsetroot #000000
xset -dpms
devmon &
MALLOC_MMAP_THRESHOLD_=131072 /usr/bin/kodi --standalone
#MALLOC_MMAP_THRESHOLD_=131072 /home/nico/src/kodi-build/kodi-x11 --standalone
while [ $? -ne 0 ]; do
 MALLOC_MMAP_THRESHOLD_=131072 /usr/bin/kodi --standalone
 #MALLOC_MMAP_THRESHOLD_=131072 /home/nico/src/kodi-build/kodi-x11 --standalone
done
openbox --exit
```

Also, I have nothing whitelisted at all since the beginning, if that is useful info.

**Comment by camelreef** [comment]
You ask me to make sure that my desktop is at 60Hz before I start Kodi in stand-alone mode.
Does that mean that I need to add something to the xrandr command for HDMI-1?

**Comment by camelreef** [comment]
I'm using HDMI-1, LVDS-1 is turned OFF.
xrandr --verbose --prop -display :0
https://paste.ubuntu.com/p/VshQbsfKhQ/

**Comment by FernetMenta** [comment]
> -s 60 in the xrandr for HDMI-1?

yes, this should work

> Also, I have nothing whitelisted at all since the beginning, if that is useful info.

whitelist 1080@60hz and 50hz for the test

**Comment by camelreef** [comment]
So, got the refresh rare at 60 Hz and started Kodi as stand-alone with 1080*60 and 1080@50 whitelisted (nothing else, especially no 25 Hz mode). No audio passthrough. Refresh adjust is ON.

xrandr -display :0 --output HDMI-1 --rate 60 --set "Broadcast RGB" "Full"

Went to Settings / System / Display and set refresh rate to 50 Hz.

Played problematic video.

And audio is being played!

Debug log: https://paste.ubuntu.com/p/nYbrhsYFVB/

**Comment by camelreef** [comment]
So I did whitelist all the 1080p modes, except the 25 Hz.

It appears that it's happy enough to double the framerate to 50Hz and play song.

The other media with different refresh rates appear happy enough too.

I've put audio passthrough back, appears happy enough.

**Comment by FernetMenta** [comment]
Are you saying it is working now with 25hz removed from whitelist?

**Comment by camelreef** [comment]
yes...
Kodi and its friends down the line appear happy when I specifically whitelist **only** the 1080 modes that are **not** 25 Hz.
They keep being happy when I revert the starting refresh rate and the OSD to 60 Hz as well as the audio passthrough.
My understanding of the logs is that Kodi tries a mode with double the refresh rate (50 Hz) and runs with it.

```
16:38:27.319 T:140142635382528   DEBUG: Trying to find exact refresh rate
16:38:27.319 T:140142635382528   DEBUG: No exact whitelisted resolution matched, trying double refresh rate
16:38:27.319 T:140142635382528   DEBUG: No double refresh rate whitelisted resolution matched, trying current resolution
16:38:27.319 T:140142635382528   DEBUG: No larger whitelisted resolution matched, trying current resolution with double refreshrate
16:38:27.319 T:140142635382528   DEBUG: Matched fuzzy whitelisted Resolution 1920x1080@ 50.00 (16)
16:38:27.319 T:140142635382528  NOTICE: Display resolution ADJUST : 1920x1080@ 50.00 (16) (weight: 0.000)
```

**Comment by FernetMenta** [comment]
Thanks a lot. Then we also know what change triggered the issue:
https://github.com/xbmc/xbmc/pull/14701

@fritsch ^^

In earlier versions the 25Hz mode never got auto selected.

**Comment by fritsch** [comment]
I don't see a bug when user has broken modeline, incompatible to the Audio bits of the TV / AVR. He can happily fine tune the resolutions if needed.

Btw. 3840x2160@25p is a common format and ignoring 25 hz would render HDMI 1.4 devices unable to play such content in 4k resolution by default.

The "choose 50 hz" instead of 25 was a year long workaround cause of not being able to detect interlaced 50i content in time / playback start.

The PR you linked enables resolution switching if user has enabled it but no whitelist set. Without this PR no switch at all would have happened.

**Comment by fritsch** [comment]
For the record: https://github.com/xbmc/xbmc/pull/13274 <- this changed the favoring of 50 hz over 25 hz.

**Comment by camelreef** [comment]
Guys, I, the user with a broken modeline:-), am happy with my situation right now (what I don't know or don't notice is broken or sub-par... Ignorance is bliss!).

But if you would like me to do any further testing (and if you can accept my limitations), I'll gladly do it as a way to give back some of the time you have given me. I'll keep following this issue.

In the meantime, thanks a lot, you guys rock!

**Comment by FernetMenta** [comment]
@camelreef thanks for your help and your patience. Autoselecting resolutions has even been unreliable. Kodi lacks a UI that guides a user through the process of selecting/whitelisting desired resolutions if mode switching is activated. Unfortunately nobody volunteered to implements that. Instead v17 behaviour (not ideal) was brought back.

If you don't mind, I would close this case now.

**Comment by camelreef** [comment]
As I said, I'm happy with my situation. So closing the case is your final call, I'm fine with it if you do.
Again, many thanks!
