### ISSUE TITLE
18.0 does not start on Amazon Fire TV Stick 4K attached to TV with "low" Resolution

### ISSUE THREAD

**Issue by godoll** [xbmc/xbmc#14974]
### Describe the bug
Here is a clear and concise description of what the problem is:

Set up a new FTVS4K as a replacement for a 1.Gen Stick, which properly ran - though with less "horse power" with 18.0.x version attached to an ["HD Ready only" Samsung TV](https://www.samsung.com/uk/support/model/LE37S62BX/XEC/).

The cloned 4K stick ran properly when still attached to my Teac AG-D500 AVR's AUX port, but when put to the Samsung's HDMI port Amazon works, but Kodi won't start.
(Was a bit confused about that and started a [thread in a German forum](https://www.kodinerds.net/index.php/Thread/63792-FireTV-Stick-4K-Kodi-Leia-startet-nicht-mehr/) as my first guess was, that I screwed some configs, eb, by "power cycling the 4k stick.)

Though 17.6 on 4k stick works as well when attached to that TV.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should start.

## Actual Behavior

18.0 won't start while installed on FTV 4K device

## Possible Fix

Either use 17.6 on 4k stick
or use (1. Gen) stick with 18.0.x

### To Reproduce

Install 18.0 on ATFV 4K still and attach to TV with low resolution 1080i? only

### Debuglog

The debuglog can be found here:

Here are some logs:

AFTV 1.Gen stick with Leia attached to "problem" TV working
[FTVSw18.0onTV.kodi.log](https://github.com/xbmc/xbmc/files/2633391/FTVSw18.0onTV.kodi.log)

AFTV 4K stick with Leia attached to Teac AVR working
[FTVS4Kw18.0onAVR.kodi.log](https://github.com/xbmc/xbmc/files/2633392/FTVS4Kw18.0onAVR.kodi.log)

AFTV 4K stick with Leia attached to "problem" TV **not** working
[FTVS4Kw18.0onTV.kodi.log](https://github.com/xbmc/xbmc/files/2633390/FTVS4Kw18.0onTV.kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android

 - Kodi version: 18.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by da-anda** [comment]
when you attach the FireStick to your TV, is your AVR on or off in this situation? I suppose you are using the ARC to get audio from your TV to the AVR? Reason I'm asking is, that I have the same issue when I try to run KODI natively on my Philips AndroidTV and KODI does only start when the AVR is on. It's somehow related to missing HDMI device info or something like that. 

@peak3d can probably tell more about it.

**Comment by godoll** [comment]
Hi da-anda, no these are two distinct setups:

One is a (Samsung LE40B679) TV, but FullHD with the AVR in my living room, while the HDReady LE37S62B TV where I have the issue is a "stand-alone" one in another room.

**Comment by godoll** [comment]
Just installed 20181223 nightly and issue seems to be gone, Kodi starts and works as expected. Thx!
