### ISSUE TITLE
low res video dont run smooth and sync anymore (720x576)

### ISSUE THREAD

**Issue by M2k80** [xbmc/xbmc#14987]
### Describe the bug
Here is a clear and concise description of what the problem is:

on leia beta5 this video was running fine, it has 720x576 
on latest rc2 this video is lagging and not sync anymore.

edit: on 18.0-RC2 Git:20181124-4ab27b67df-dirty its also working fine

if more info is needed, no problem.
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

it should run like on older kodi18 releases

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
18.0-BETA5 Git:20181024-02b03e7-dirty debug log, when all was fine
https://paste.ubuntu.com/p/kD2CDGFJps/
18.0-RC2 Git:20181202-812855d84e-dirty debug log 
https://paste.ubuntu.com/p/gmKMQByxFW/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi 18 RC2
Nvidia Shield Experience 7.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by M2k80** [comment]
this is the latest running version 18.0-RC2 Git:20181127-93086fd842-dirty

**Comment by M2k80** [comment]
reverted this commit https://github.com/xbmc/xbmc/pull/14950 and the low resolution videos are working fine again

**Comment by Frodonf** [comment]
Yesterday I've posted an issue that seems related: https://github.com/xbmc/xbmc/issues/15005

**Comment by M2k80** [comment]
problem is fixed with https://github.com/xbmc/xbmc/pull/15078
