### ISSUE TITLE
KODI 18 RC1 subtitle issue with playlists

### ISSUE THREAD

**Issue by idorose** [xbmc/xbmc#14980]
### Describe the bug
Here is a clear and concise description of what the problem is:

When choosing "Play from here" in the context menu after loading a smart playlist the video is playing without subtitles as if there is no subtitle file present

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

video should play with the subtitle just like when playing a single video from the playlist

## Actual Behavior

subtitles are not loaded and do not appear in the option to change subtitles, it is required to redownload or point to a local file in order to have subtitles

### To Reproduce

1. create a smart playlist
2. show the playlist content (dont play it)
3. click play from here on one of the videos

### Debuglog

The debuglog can be found here:

https://paste.ubuntu.com/p/RrpsrNYrb9/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [V] Windows
 - [ ] Windows UWP

 - Operating system version/name: windows 10
 - Kodi version: 18 rc1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Can confirm and reproduce on osx.

**Comment by DaVukovic** [comment]
@idorose could you please use some paste service you prefer to post the complete logfile instead of spamming the bug report with a (probably) useless snippet from your log.

Thanks in advance.

**Comment by kib** [comment]
@idrose could you please post a link to a full debug log and remove all the non-supported / piracy repositories from the system you reproduce the bug on as well ?

**Comment by DaVukovic** [comment]
There are still way too many banned add-ons and leftovers present on your system.

For a fast vanilla Kodi setup, please rename the `Kodi` folder at `%APPDATA%\Kodi` to something else, restart Kodi and only install the necessary add-ons you need to reproduce your issue.

Please submit that clean logfile soon. Otherwise there's a high risk that this issue will be closed.

**Comment by idorose** [comment]
I will try to reproduce with vanilla installation when I get home

**Comment by idorose** [comment]
I will do that this evening, thanks.

**Comment by idorose** [comment]
ok, I updated the log with vanilla installation

**Comment by Dnkhatri** [comment]
I believe this is the same issue as these tickets 
https://github.com/xbmc/xbmc/issues/14947
https://github.com/xbmc/xbmc/issues/14841

**Comment by idorose** [comment]
yes seems similar to #14841

**Comment by enen92** [comment]
@idorose please test https://github.com/xbmc/xbmc/pull/15132

**Comment by idorose** [comment]
@enen92 I dont understand what i need to do

**Comment by idorose** [comment]
the link is not working for me

**Comment by idorose** [comment]
I can confirm its solved
