### ISSUE TITLE
Leia RC on FireTVStick gets minimized after some time even sleep and so on is off

### ISSUE THREAD

**Issue by Erestris** [xbmc/xbmc#14981]
### Describe the bug
Hello,

I use Leia RC on a FireTVStick. Screensaver and so on are off in Kodi Settings and in FireTV Settings. If I pause a video oder simply do nothing Kodi gets minimized/shut down and i have to Open it again. With Kodi 17.6 this never happened. Is there a solution?
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HitcherUK** [comment]
Same issue as this? - https://github.com/xbmc/xbmc/issues/14949

**Comment by Erestris** [comment]
Yes. Sorry. Did  not See this issue.
