### ISSUE TITLE
Kodi crashes/closes when trying to install add-on from zip-file

### ISSUE THREAD

**Issue by EmilVogt** [xbmc/xbmc#14989]
### Describe the bug

After adding a source to the file manager and trying to install an add-on from a zip-file, Kodi is forced to close without any warning and doesn't install the add-on.

## Expected Behavior

Kodi installs the add-on from the zip-file.

## Actual Behavior

Kodi closes immediately without installing the add-on.

### To Reproduce

1.  Download the zip-file from [kodinerds](https://github.com/kodinerds/repo/raw/master/repository.kodinerds.zip) and save it onto your disc. 
2. In Kodi, go to file-manager and add the directory you saved the zip-file to as new source.
3. In Kodi, go to add-ons and choose "Install from zip-file".
4. Navigate to your newly added source and select the zip-file ("repository.kodinerds.zip").
After a short while Kodi closes.

### Debuglog

The debuglog can be found here:
[https://paste.kodi.tv/ililemesup.kodi](https://paste.kodi.tv/ililemesup.kodi)

## Additional context
Since there's almost nothing in the debuglog, I added the kodi_crashlog.dmp. Maybe it helps.
[kodi_crashlog-18.0-RC2 Git_20181202-812855d84e-20181204-151448.dmp.zip](https://github.com/xbmc/xbmc/files/2644556/kodi_crashlog-18.0-RC2.Git_20181202-812855d84e-20181204-151448.dmp.zip)

### Your Environment

Operating system version/name: Windows 10 Pro (1803), 64bit
Kodi version: Kodi Leia 18 RC2, 64bit

**Comment by Motabus** [comment]
Can confirm this issue with the 32 and 64 bit Android and Windows RC1 and RC2 releases.

**Comment by DaVukovic** [comment]
I can't replicate that problem using Linux (Ubuntu)

For installing add-ons or repos via zip you should use the method explained here:

https://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files

Anyway, if I add a source at the file manager and select a zip file, Kodi simply shows the content of that zip and, AFAICT, there's no way to install add-ons from that location. 

This behaviour should normally be the same on Windows as well. So I would recommend to the method mentioned above.

**Comment by EmilVogt** [comment]
@DaVukovic When doing step 7 in your linked [Wiki article](https://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files) and selecting the zip-file ("repository.kodinerds.zip"), Kodi crashes on my Windows 10 machine. 

Maybe the wording was bad. To be precise, I want to add a **repository** via the "Install from zip-file"-method.

**Comment by Motabus** [comment]
Same for me as @EmilVogt.  It crashes at step 7

**Comment by DaVukovic** [comment]
So to be precise....

you are *not* doing that: 

>After adding a source to the file manager and trying to install an add-on from a zip-file

you are trying to use the method mentioned in the wiki...

That method works fine on Ubuntu with Kodi 18 RC2 and the add-on (a skin) was installed successfully.

**Comment by Motabus** [comment]
That is correct.  I tried adding a few different sources to the file
manager in Android and Windows and when i try to install from zip Kodi 18
RC1 or RC2 just crash closes.

**Comment by DaVukovic** [comment]
ok, but I can reproduce that with the kodinerds.repo

Best would be to contact the maintainer of that repo

**Comment by MartijnKaijser** [comment]
@tamland ping

**Comment by EmilVogt** [comment]
@DaVukovic 

> So to be precise....
> 
> you are _not_ doing that:
> 
> > After adding a source to the file manager and trying to install an add-on from a zip-file

I'm adding the **folder**, which has the external repositories (e.g. repository.kodinerds.zip) in it, as "source". As I understand, that is just a link/short-cut. That way I can find my zip-files easier.
But Kodi also crashes using the method in the wiki.

**Comment by e1d1s1** [comment]
I can also confirm the bug on Windows 10 with multiple repo zips.

**Comment by Rechi** [comment]
@AlwinEsch this crash is caused by #14884.

Division by zero (`total == progress == 0`) is happening at https://github.com/xbmc/xbmc/blob/34e99be84bcc1d7e19fc2ac3aa60640053568600/xbmc/addons/AddonInstaller.cpp#L88

**Comment by apothegm** [comment]
Holy moly! I'm so glad I found this bug. This was driving me crazy for for way longer than I'm willing to admit.

Thanks!

**Comment by homeslixe** [comment]
Confirmed for me too. windows 10, Leia RC2. Nightlies are more stable at the moment :<
