### ISSUE TITLE
Lag when opening Kodi when in memory on Android

### ISSUE THREAD

**Issue by tmortonorr** [xbmc/xbmc#14988]
### Describe the bug
Here is a clear and concise description of what the problem is:

When Kodi 18 RC1 is in memory and you switch to it/open it, there is 5 second lag before it opens. This was not the issue on Kodi 17.

When Kodi is not in memory it opens the kodi boot screen straight away.

This affect the Android version on Fire TV 3 and Nvidia Shield, others are possibly affected as well.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should open near instantly when the app is requested to open.

## Actual Behavior

There is a 5 second lag when requesting the Kodi app to open (when in memory)

### To Reproduce

1. Open Kodi
2. Go to your home screen launcher or a different app
3. Go back to Kodi

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ujimekivib.kodi

I opened Kodi at 17:48:00.412
I went to my home screen launcher at 17:49:01.582
I reopened Kodi at 17:49:59.456
Kodi actually opened at 17:50:04.507

It seems to be the following process that cause the lag - DEBUG: CAndroidUtils: SetNativeResolution: 2: 1920x1080 1920x1080@59.940060

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 32 bit Arm processor (Fire TV 3)
 - Kodi version: 18 RC1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by h45rd** [comment]
Can confirm this issue on the Nvidia Shield TV box with RC1.
Has not been present with any of the Leia Betas.

**Comment by McChen147** [comment]
I tested RC2, it has this same issue as well

**Comment by MartijnKaijser** [comment]
@peak3d most likely the following change its the cause according to @lrusak ;)
https://github.com/xbmc/xbmc/pull/14686/commits/c4580af31f2a5a96c6b13392bd08d75452e82bd9

**Comment by MartijnKaijser** [comment]
Fixed
https://github.com/xbmc/xbmc/pull/14993
