### ISSUE TITLE
Kodi 18 "Leia" RC 1 Cannot use controlers

### ISSUE THREAD

**Issue by GuillaumeDua** [xbmc/xbmc#14982]
### Kodi 18 "Leia" RC 1 Cannot use controlers
Here is a clear and concise description of what the problem is:

Using latest Fedora Workstation, and Kodi 18, controlers does not work.
Tested with an **Xbox360 wireless controler**, and an USB-wired **MS joystick**.
Tested when launching Kodi as an application, and a graphical environment.
For xbox 360 controler, tested with both xpad and xboxdrv.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Control Kodi using a controler (select movies, musics, app ...)

## Actual Behavior
Controlers are not even listed as periphericals

### To Reproduce

1. Plug an USB controler
2. Start the device
3. Start Kodi on Fedora as application or graphical environment
4. try to use the controlers buttons/pads

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - [ ] Linux (Fedora Workstation)

 - Operating system version/name:
 - Kodi version: 18 RC1

**Comment by garbear** [comment]
Where is the debug log? You are probably missing the Joystick Support binary add-on but without a debug log there's no way to know.

**Comment by GuillaumeDua** [comment]
Here is the debug log : https://paste.kodi.tv/ikasanegum

**Comment by MartijnKaijser** [comment]
Install the peripheral.joystick addon and update to something more recent. Beta5 is way too old.

**Comment by MartijnKaijser** [comment]
Then you should complain there that they didn't supply a correct version.
