### ISSUE TITLE
Skin can't be updated as long it is in use

### ISSUE THREAD

**Issue by SkyBird1980** [xbmc/xbmc#14990]
### Describe the bug
If you have a  Skin in use. e.g. Transparency or Rapier you can not update the Skin.

## Expected Behavior
Skin Updates and  will be reloaded.

## Actual Behavior
Skin don't update.
Notice about Update failed.
Your actual skin Settin will be set to 'None'

### To Reproduce
I only tested it with Windows 10 (1809) 64 Bit Professional:
1.) Install an old Version of a Skin. e.g: http://mirrors.kodi.tv/addons/leia/skin.transparency/skin.transparency-11.0.3.zip
2.) switch to this Skin in settings.
3.) Force an Update of your addons, problem will be visible.

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/baqipewija.kodi

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64 Bit (1809)
 - Kodi version: 18.0-RC2 Git:20181202-812855d84e
[kodi.log](https://github.com/xbmc/xbmc/files/2644635/kodi.log)

**Comment by MartijnKaijser** [comment]
Duplicate https://github.com/xbmc/xbmc/issues/14663
