### ISSUE TITLE
Error freadahead.c:92:3: error: #error "Please port gnulib freadahead.c 

### ISSUE THREAD

**Issue by xperiafan13-rom** [xbmc/xbmc#14995]
Im compile kodi on ubuntu 18.10, but i get this error on make -j$(getconf _NPROCESSORS_ONLN)

ERROR:
make[5]: Entering directory '/home/xperiafan13/Documentos/kodi/tools/depends/native/m4-native/x86_64-linux-native/lib'
make  all-am
make[6]: Entering directory '/home/xperiafan13/Documentos/kodi/tools/depends/native/m4-native/x86_64-linux-native/lib'
  CC       freadahead.o
freadahead.c: In function 'freadahead':
freadahead.c:92:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
   ^~~~~
make[6]: *** [Makefile:1910: freadahead.o] Error 1

**Comment by MartijnKaijser** [comment]
Please ask compiler questions on the forum
