### ISSUE TITLE
No web interface images with libmicrohttpd-0.9.61

### ISSUE THREAD

**Issue by candrews** [xbmc/xbmc#14991]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm using Kodi 18.0rc2 with libmicrohttpd 0.9.61.

When using the web interface (in my case, the URL is http://192.168.0.101:8080/#movies ), all the movie covers are missing.
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Cover art should appear. Using earlier versions of libmicrohttpd before 0.9.61 this works as it expected.

## Actual Behavior

Cover art images do not appear.

## Possible Fix

Not sure. `}8]` in #kodi-dev on IRC says:
```
}8] | i used git so i could bisect
}8] | the specific part of the commit is https://gnunet.org/git/libmicrohttpd.git/commit/src/microhttpd/connection.c?id=7b92bb1cdebfaefd0fe778f63542ce5d465daa94
```

### To Reproduce

1. Have libmicrohttpd 0.9.61 installed
2. Have Kodi 18 installed
3. Use the web interface

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://i.imgur.com/GwQ1vmy.png

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.0rc2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MartijnKaijser** [comment]
We use VERSION=0.9.55

**Comment by bacon-cheeseburger** [comment]
MartijnKaijser, 0.9.55 is a year and a half old, there's no configure flag to compile & use the internal copy (I heard cross-compiling will but that's useless for self-compilers), and this *will* need to be addressed for distros that are already at 0.9.61 or getting close to it (which is several after a quick search). I assume the easiest solution is to just add a configure flag allowing users to build & use the internal copy like other stuff (ffmpeg, rapidjson, etc) as downgrading a system version and keeping it that way may be too messy.

**Comment by MilhouseVH** [comment]
Has this been reported upstream to libmicrohttpd, as it looks like they're now unescaping the requested URI twice with 0.9.61 ([here](https://gnunet.org/git/libmicrohttpd.git/tree/src/microhttpd/connection.c?id=7b92bb1cdebfaefd0fe778f63542ce5d465daa94#n2282) and again [here](https://gnunet.org/git/libmicrohttpd.git/tree/src/microhttpd/connection.c?id=7b92bb1cdebfaefd0fe778f63542ce5d465daa94#n2311)), when in previous versions they only unescaped the URI once ([here](https://gnunet.org/git/libmicrohttpd.git/tree/src/microhttpd/connection.c?id=8466a08d3588608f018722d6a176ced2e0c2a539#n2303)). This additional unescape results in libmicrohttpd 0.9.61 not being able to find the requested resource, which should still be in an escaped form.

Removing the second unescape from 0.9.61 with http://ix.io/1qKG resolves the issue.

**Requested URL**:
```
http://192.168.0.20:8080/image/image%3A%2F%2Fnfs%253a%252f%252f192.168.0.3%252fmnt%252fshare%252fmedia%252fVideo%252fMoviesSD%252f2012%2520(2009)%255bDVDRip%255d-poster.jpg%2F
```

**With 0.9.61**:

input line:
```
GET /image/image%3A%2F%2Fnfs%253a%252f%252f192.168.0.3%252fmnt%252fshare%252fmedia%252fVideo%252fMoviesSD%252f2012%2520(2009)%255bDVDRip%255d-poster.jpg%2F HTTP/1.1
```
parsed uri:
```
/image/image://nfs://192.168.0.3/mnt/share/media/Video/MoviesSD/2012 (2009)[DVDRip]-poster.jpg/
```
Result: Failure (404)

**With 0.9.55 (or 0.9.61 + http://ix.io/1qKG)**:

input line:
```
GET /image/image%3A%2F%2Fnfs%253a%252f%252f192.168.0.3%252fmnt%252fshare%252fmedia%252fVideo%252fMoviesSD%252f2012%2520(2009)%255bDVDRip%255d-poster.jpg%2F HTTP/1.1
```
parsed uri:
```
/image/image://nfs%3a%2f%2f192.168.0.3%2fmnt%2fshare%2fmedia%2fVideo%2fMoviesSD%2f2012%20(2009)%5bDVDRip%5d-poster.jpg/
```
Result: Success (200)

If kodi were to "triple escape" the artwork URLs, ie.:
```
http://192.168.0.20:8080/image%252Fimage%253A%252F%252Fnfs%25253a%25252f%25252f192.168.0.3%25252fmnt%25252fshare%25252fmedia%25252fVideo%25252fMoviesSD%25252f2012%252520(2009)%25255bDVDRip%25255d-poster.jpg%252F%2520HTTP%252F1.1%250A
```
then it would be possible to retrieve the posters using an unmodified libmicrohttpd 0.9.61... but of course Kodi then wouldn't work with any earlier version of libmicrohttpd which expects only "double-escaped" URLs.

Therefore this has to be an upstream bug, which should be reported to libmicrohttpd (no idea how, their infra seems totally broken).

**Comment by MilhouseVH** [comment]
This is a link to issue `#5473` (as mentioned in the libmicrohttpd 0.9.61 [Changelog](https://gnunet.org/git/libmicrohttpd.git/tree/ChangeLog?id=7b92bb1cdebfaefd0fe778f63542ce5d465daa94)) which seems to be the reason for the change in the breaking commit: https://gnunet.org/bugs/view.php?id=5473

I'll see if I can ping them on that issue and make them aware of this new behaviour, and determine if it is intentional or not.

**Comment by candrews** [comment]
I just reported this regression to libmicrohttpd at https://gnunet.org/bugs/view.php?id=5496

**Comment by MilhouseVH** [comment]
Thanks - you saved from creating a duplicate. :)

**Comment by MilhouseVH** [comment]
Fixed upstream in (what will be) 0.9.62: https://gnunet.org/git/libmicrohttpd.git/commit/src/microhttpd/connection.c?id=79a8955bb61d62f6dc4fc93d2f05a08adf8596d5

**Comment by wsnipex** [comment]
I guess this can be closed as fixed upstream bug?

**Comment by candrews** [comment]
Agreed!

Thanks!
