### ISSUE TITLE
all current versions of Kodi only display in 9.7 format on new iPad Pro 11"

### ISSUE THREAD

**Issue by cl0udk1ckr** [xbmc/xbmc#14994]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [x] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MartijnKaijser** [comment]
Please edit and fill in all required information or we will close thos

**Comment by Memphiz** [comment]
Please test with this version and report back:

http://mirrors.kodi.tv/test-builds/darwin/ios-arm64/kodi-20181205-b6789f7d-ios_devices-ios64.deb

**Comment by cl0udk1ckr** [comment]
i tried the deb you sent. its still the cropped 9.7 screen. resolution reads 1536x2048. the new 11” iPads res. is 2388-x-1668

**Comment by Memphiz** [comment]
Please post a debug log

**Comment by Memphiz** [comment]
Fyi this might be unsolvable for Leia as apple might require to use latest Xcode 10.1 to make use of the new resolution of the iPad 11 inch. For us this means we need to update our build farm to latest Mac OS an Xcode versions. This is a bigger undertaking and can‘t be done in this phase of the Kodi release cycle.
Usually it is enough to provide a launch image in the correct size to unlock the full resolution. But the 11 inch screen is way more different to all others.

I will need the debug log anyway but just in case you think this is trivial ... ;)

**Comment by cl0udk1ckr** [comment]
oh ok. that makes sense. ill have to look up how to find the debug log as im unsure how to do that. thanks for your time and happy holidays!

**Comment by Memphiz** [comment]
OK - another test version - please report back. You can fetch the debug log via itunes kodi app shared documents:

http://mirrors.kodi.tv/test-builds/darwin/ios-arm64/kodi-20181206-9fcaef0e-ios_devices-ios64.deb

(link might need up to 30 minutes from now to become valid)

**Comment by cl0udk1ckr** [comment]
YAHTZEE!!! the macbook xcode 10.1 compiled RC3 stretched it full screen. looks good guys! 

the logs will be attached anyhow. thanks again you wizards!

**Comment by Memphiz** [comment]
That doesn‘t help as we can‘t switch to Xcode 10.1 on our build farm. So the version before does not do anything good? Thx for the feedback so far though. Debug log is not needed in that case.

**Comment by cl0udk1ckr** [comment]
the first revision you sent today stretched the screen closer to the edges. the resolution read correctly but it didnt stretch to use the full real estate. it did stretch further than the 9.7 version tho. id assume it was equivalent to using a 10.5 iPad. in all honesty both revisions you sent me were better than the original which was a cropped 9.7.

**Comment by Memphiz** [comment]
Yep stretching to the 10.5 inch resolution is what i have expected. That’s what i have read somewhere. I think this will be what Leia will have. Full support then for a later release. Thx for testing.

**Comment by cl0udk1ckr** [comment]
hey Memphiz, any chance you could compile me a copy of 18.1 with the newer xcode again? the 10.5" crop isnt bad at all on the official release. i just REALLY loved when kodi was the full 11".

**Comment by Memphiz** [comment]
That’s not the kind of person I am really.

**Comment by cl0udk1ckr** [comment]
im assuming its more of a pain in the butt than i imagined. is there any possibility Leia will support the iPad 11” full res in 18.2+ or will that have to be something that has to be done for a future Kodi 19?

 anyway, thanks for your time and all your awesome work. u guys rock!

**Comment by Memphiz** [comment]
We normally don‘t bump build tools for bug fix releases. We‘ll see.
