### ISSUE TITLE
Android  - Leia  v18 - DVD ISO playback not working since RC2 (nVidia Shield)

### ISSUE THREAD

**Issue by Frodonf** [xbmc/xbmc#15005]
### Describe the bug

When playing DVD ISO (any DVD ISO), menu animation is working fine, but when I'm starting the actual movie/episode or if there is a promo/intro video before the menu, the audio is working but not the video part : it shows a frame or two, waits 5 to 10 seconds, skip to another frame (trying to sync with sound?).

No problem with Blu-ray or UDH-Blu-ray ISO.

Issue was not present in v18 RC1 and before.

Edit 1: I tried directly with a .VOB file that I've extracted from a DVD and put in a local folder of the nVidia Shield (link to that file in the screenshot section). The problem is the same. I really think it's a deinterlacing problem.

Edit 2: I've pinpointed when the problem was introduced: in November 28th nightly (kodi-20181128-5880ccf2-master-arm64-v8a.apk)

No problem with November 27th nightly (kodi-20181127-93086fd8-master-arm64-v8a.apk)

## Expected Behavior

Video should play fine

## Actual Behavior

Video not playing

### To Reproduce

1. Select and play a DVD ISO
2. Select "Start" or "Play movie" in the DVD menu (if present)
3. Wait...

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/vosewejixu

### Screenshots 

Here's a video recording of the problem (shot with a DSLR at 29,97fps):
https://drive.google.com/open?id=1SLQ-sh...y8hnBbwpBU

And here's a vob file that I can reproduce the problem with:
https://drive.google.com/open?id=1Asw7xYZbGwB-K9njbal8ZdtU-VTFirIA

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Shield Experience 7.1.0 (now updated to 7.2)
 - Kodi version: v18 RC2

My setup: nVidia Shield TV -> Pioneer AV receiver -> LG OLED UHD TV
Video files are streamed from a NAS thru NFS.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Frodonf** [comment]
Here's a small update :

Still unable to read video correctly after a factory reset of the Shield and a clean install of the latest Kodi nightly (kodi-20181214-4c17e776-master-arm64-v8a.apk).

I just installed Kodi, installed Kodi Log Uploader and play the video file (stored on the "Movies" folder of the Shield internal memory).

The video file used is there: https://drive.google.com/open?id=1CqILOH..._jUlSW7RpT

The log file is there: https://paste.kodi.tv/nevayahoye

**Comment by Frodonf** [comment]
Another Update,

Thanks to peak3d, this apk is resolving the issue: https://jenkins.kodi.tv/job/Android-ARM64/8501/

**Comment by KarellenX** [comment]
Reporter stated issue is solved.

Issue closed
