### ISSUE TITLE
Build fails using cmake's ninja backend

### ISSUE THREAD

**Issue by candrews** [xbmc/xbmc#15008]
### Describe the bug
Here is a clear and concise description of what the problem is:

Building Kodi with cmake using ninja currently fails.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should build with either cmake's ninja or make backends.

## Actual Behavior

```
-- Configuring done
-- Generating done
-- Build files have been written to: /var/tmp/portage/media-tv/kodi-9999/work/kodi-9999_build
>>> Source configured.
>>> Compiling source in /var/tmp/portage/media-tv/kodi-9999/work/kodi-9999 ...
>>> Working in BUILD_DIR: "/var/tmp/portage/media-tv/kodi-9999/work/kodi-9999_build"
ninja -v -j5 -l0 all
ninja: error: build.ninja:7721: multiple rules generate addons/xbmc.json/addon.xml [-w dupbuild=err]
```

### To Reproduce

1. Grab Kodi's source
2. Build using cmake with the `-G Ninja` argument

### Debuglog

The debuglog can be found here:
This is a build failure so runtime debuglog is N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

This is a build failure so runtime screenshots are N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

It would be nice to use ninja :)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo ~amd64
 - Kodi version: 18.0rc2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by wsnipex** [comment]
Looks like ninja made dupbuild an error by default.
This is an old issue I wasn't able to fix without removing functionality back when ninja support was added. I will take another look, in the meantime you can use -w dupbuild=warn

**Comment by candrews** [comment]
I just tested and confirm that https://github.com/xbmc/xbmc/pull/15011 fixes this issue.
