### ISSUE TITLE
Android - Leia v18 - Split Movie End Bug

### ISSUE THREAD

**Issue by rahadiancs** [xbmc/xbmc#15018]
When a movie consisted of several part (split movie) ends, it's going back to 2nd part of the movie.

**Comment by MartijnKaijser** [comment]
Please fill out the issue template as requested by editing the issue. If not done this issue will be close without looking at it.

**Comment by DaVukovic** [comment]
Ok, 3 days have been passed with zero reaction.

We can´t do anything without a logfile. 

Issue closed.
