### ISSUE TITLE
Kodi 18-rc2 (linux) doesn't allow reading of artwork

### ISSUE THREAD

**Issue by Uatschitchun** [xbmc/xbmc#15013]
Kodi doesn't provide correct URLs or is prohibiting access, so yatse doesn't display any thumbs.

[Link to post in yatse forum](https://community.yatse.tv/t/preview-image-for-movies-without-poster-jpg/1185/9?u=uatschitchun)
```
14:16:41.544 T:140507508832000   DEBUG: CAnnouncementManager - Announcement: OnScanStarted from xbmc
14:16:41.544 T:140507508832000   DEBUG: GOT ANNOUNCEMENT, type: 16, from xbmc, message OnScanStarted
14:16:41.549 T:140506797647616   DEBUG: VideoInfoScanner: Scanning dir ‘/media/8TB/Bilder/Canon/Movies/Bulli/’ as not in the database
14:16:41.557 T:140506797647616   DEBUG: VideoInfoScanner: No (new) information was found in dir /media/8TB/Bilder/Canon/Movies/Bulli/
14:16:41.561 T:140506797647616   DEBUG: VideoInfoScanner: Scanning dir ‘/media/8TB/Bilder/Canon/Movies/Bulli/Bulli Abschied 1/’ as not in the database
14:16:41.567 T:140506797647616   DEBUG: VideoInfoScanner: Found matching full NFO file: /media/8TB/Bilder/Canon/Movies/Bulli/Bulli Abschied 1/Bulli Abschied 1 JPEG-480p PCM-1ch.nfo
14:16:41.579 T:140506797647616   DEBUG: Caching image ‘/media/8TB/Bilder/Canon/Movies/Bulli/Bulli Abschied 1/Bulli Abschied 1 JPEG-480p PCM-1ch-thumb.jpg’ to ‘f/fd95db8d.jpg’:
14:16:41.579 T:140506797647616   DEBUG: cached image ‘special://masterprofile/Thumbnails/f/fd95db8d.jpg’ size 640x480
14:16:41.619 T:140506797647616   DEBUG: VideoInfoScanner: Adding new item to movies:/media/8TB/Bilder/Canon/Movies/Bulli/Bulli Abschied 1/Bulli Abschied 1 JPEG-480p PCM-1ch.avi
14:16:41.639 T:140507508832000   DEBUG: CAnnouncementManager - Announcement: OnUpdate from xbmc

14:17:19.784 T:140502531827456   DEBUG: CWebServer[8080]: request received for /jsonrpc
14:17:19.905 T:140502531827456   DEBUG: CWebServer[8080]: request received for /image/image%3A%2F%2F%252fmedia%252f8TB%252fBilder%252fCanon%252fMovies%252fBulli%252fBulli%2520Abschied%25201%252fBulli%2520Abschied%25201%2520JPEG-480p%2520PCM-1ch-thu
mb.jpg%2F
14:17:19.906 T:140502531827456   DEBUG: CUtil::GetMatchingSource: no matching source found for [/net/atom/media/8TB/Bilder/Canon/Movies/Bulli/Bulli Abschied 1/Bulli Abschied 1 JPEG-480p PCM-1ch-thumb.jpg]
14:17:19.908 T:140503077091072   DEBUG: Previous line repeats 5 times.
```

Add NFOs for the movies
Start with a fresh kodi
Add source and scrape local information only
Let kodi create thumbs
Export DB (thumbs are created fine)
Add kodi to yatse
Update movies (movies are shown without thumb)
Cache art from yatse settings
Still no art within yatse

Movie folders look like:
filename-thumb.jpg
filename.avi
filename.nfo

I'm sure this issue is incomplete (no complete debug-log), but my time is rare atm and I wanted it to be known.

**Comment by DaveTBlake** [comment]
>I'm sure this issue is incomplete (no complete debug-log), but my time is rare atm and I wanted it to be known.

I certainly is incomplete, and without a full debug log it is unknown what build you actually have. I know you say RC2 in the title but prove it! It matters because this sounds a lot like an issue that has already been solved.

Also are thumbs missing browsing via web using Chorus?

I won't be news that time is precious for all of us, and it is team policy to close  issues posted without sufficient data so please follow up with a full log

**Comment by Uatschitchun** [comment]
http://paste.ubuntu.com/p/nhv9PnRXVY/

**Comment by Uatschitchun** [comment]
Yes, Chorus is missing thumbs

**Comment by wsnipex** [comment]
it appears the share is really mounted on /net/atom/media/ and not /media/
So you have to add a source for /net/atom/media/

**Comment by DaveTBlake** [comment]
@Uatschitchun have you defined a symlink for  `/net/atom/media/` to `/media/` or is that something that has happened automatically? I know nothing about Linux let alone Kodi on it, but I know that on some platforms sources get automounted is that what happened here?

**Comment by DaveTBlake** [comment]
I have tested on using symlinks on Windows and the webserver has no problems seeing art from a media source defined by a symlink (if a user is so smart as to create such a thing), the symlink is used throughout. But `CFileUtils::CheckFileAccessAllowed` has a different implementation for Posix targets and that possibly converts any symlinks it is checking into the real path, meanwhile the list of sources it is checking in holds the symlink version of the source path.

@wsnipex I can't test but does `realpath()` resolve any symlinks to their actual location? I am guessing that it might. The call to `RemoteAccessAllowed()` in `CFileUtils::CheckFileAccessAllowed` needs to be passed the path leaving any symlinks unresolved i.e. in the form it is requested less any encoding such as "image://"
https://github.com/xbmc/xbmc/blob/aadfe2eca7fe72706c17de87246149b5c0ac1e01/xbmc/utils/FileUtils.cpp#L291
Are you able to test that and fix the Posix implementation if my guess is correct?

**Comment by wsnipex** [comment]
yes, symlinks are resolved and this is on purpose and an important detail of the security fix.

**Comment by Uatschitchun** [comment]
Yes, on the system the log comes from, the share is auto-mounted (autofs) @ /net/server/share/ and linked to /media/ then for convenience. So the new security fix needs both "ends" of a symlink added as source?

**Comment by wsnipex** [comment]
no, not both. You have to use the real path for the source, as already said above. The /media stuff is not needed at all.

**Comment by DaveTBlake** [comment]
>yes, symlinks are resolved and this is on purpose and an important detail of the security fix.

I can see why that would be for blacklist/whitelist testing, but when it comes to checking if the path is in the sources list it is comparing apples with pears (resolved symlinks against those that are not).

**Comment by DaveTBlake** [comment]
>You have to use the real path for the source

It is more that the real path, or a parent folder of the  real path come to that, needs to be added as some kind of source, video, music or pictures etc. is does not matter what kind of sources it is added as. You can still use /media as a source as well if you wanted.

But that does seem a user work around, I still think that if a user can add symlink as a source then Kodi should deal with permitting webserver access to images on that source too.

**Comment by wsnipex** [comment]
You're not wrong, but resolving to real path is the only proper method to prevent path traversal attacks.
It might be a little inconvenience for users with existing setups with symlinks. I'd argue that those are a small minority of users, let alone those who also want to use the web interface or remote apps.
But that is a small price to pay for the security of your data.

The fix is really easy: Just add your media sources with the real path instead of a symlinked one.

**Comment by pkerling** [comment]
You could also realpath() both paths (i.e. also the registered source path) before the check to rectify this, or am I missing something?

**Comment by wsnipex** [comment]
We probably could do that. But as always with those "small" changes, you always seem to have missed something after a while, just like this issue here ;)

**Comment by DaveTBlake** [comment]
>...you always seem to have missed something after a while, just like this issue here ;)

I thought that was the standard team approach - make changes, see what breaks, make some more changes.... ;) Although preferably not in this phase of the release cycle of course.

It is a shame there isn't a Linux call that resolves /../.. kinds of path to the actual location but leaves direct symlinks intact.

**Comment by lrusak** [comment]
> It is a shame there isn't a Linux call that resolves /../.. kinds of path to the actual location but leaves direct symlinks intact.

```
lukas@nuc8i7hnk ~/Documents/test$ ln -s ../../ testlink

lukas@nuc8i7hnk ~/Documents/test$ readlink testlink
../../

lukas@nuc8i7hnk ~/Documents/test$ readlink -f testlink
/home/lukas
```
???

**Comment by pkerling** [comment]
@wsnipex I think it's strictly an improvement. I could be wrong though :-D

> It is a shame there isn't a Linux call that resolves /../.. kinds of path to the actual location but leaves direct symlinks intact.
Resolving the symlinks is the proper solution. Otherwise you could have weird situations like e.g. if there is a symlink to `/etc` inside a shared folder (for whatever reason), you would be able to access it. Not sure how practically relevant that is, but with stuff like that you also don't want to have to think about it.

@lrusak 
1. readlink(3p) does not resolve `../..`
2. "The function canonical() is modeled after the POSIX realpath"

**Comment by DaveTBlake** [comment]
We have a user work around for users smart enough to have added their own symlinks, but are there situations where symlinks are used automatically and so user won't understand they need to add a special source? 

For example do LibreElec or OSMC use symlinks for the automounted sources?

**Comment by Uatschitchun** [comment]
Problem with using autofs and the reason for using symlinks is that /net/server/share isn't browseable but only becomes available when accessed. That's why symlinks to /media come in handy, as the do persist, even if the share gets automatically unmounted. I'll check that...
