### ISSUE TITLE
Allow use of system libupnp

### ISSUE THREAD

**Issue by candrews** [xbmc/xbmc#15014]
### Describe the bug
Here is a clear and concise description of what the problem is:

Currently, bundled libupnp is always used: https://github.com/xbmc/xbmc/blob/master/lib/libUPnP/

Just like the other libraries, it would be great if system upnp could be used instead.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

There should be a cmake option to use system libupnp:
`-DENABLE_INTERNAL_LIBUPNP=ON`

## Actual Behavior

Bundled libupnp is always used.

### To Reproduce

N/A

### Debuglog

The debuglog can be found here:
N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux
 - Kodi version: 18.0rc2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by asavah** [comment]
Please note that https://github.com/xbmc/xbmc/blob/master/lib/libUPnP/ is the platinum/neptune sdk  -> https://github.com/plutinosoft/Platinum and not libupnp -> https://github.com/mrjimenez/pupnp , and AFAIK no distro ships platinum as a package.

**Comment by candrews** [comment]
> AFAIK no distro ships platinum as a package.

That can be changed :-)

**Comment by MartijnKaijser** [comment]
We use a very very heavily patched version so it would basically be completely broken if you would use an upstream version.

**Comment by wsnipex** [comment]
going to close this, since it's not going to happen in the near future
