### ISSUE TITLE
v18 No https radio stream playback

### ISSUE THREAD

**Issue by YggdrasiI** [xbmc/xbmc#15025]
### Describe the bug

The playback of internet radio streams failed, if they use https. Playing these urls with an other player on the same system, works.
Example links to affected streams:

https://dg-ndr-https-fra-dtag-cdn.sslcast.addradio.de/ndr/ndrkultur/live/mp3/128/stream.mp3
https://swr-dasding-live.sslcast.addradio.de/swr/dasding/live/mp3/128/stream.mp3
https://wdr-1live-live.icecastssl.wdr.de/wdr/1live/live/mp3/128/stream.mp3

I've tested playing above streams with several versions of Kodi 18.x/17.x, see below. The result (no playnig of files) was on all of them the same.

[Here](https://paste.kodi.tv/oralomovif.kodi) is a debug log with extra logging information for curl: 
and [here](https://paste.kodi.tv/asumajavud) is a log on the same system for 
```curl --verbose "https://dg-ndr-https-fra-dtag-cdn.sslcast.addradio.de/ndr/ndrkultur/live/mp3/128/stream.mp3" > https_stream.mp3``` 

I'm not sure if the curl log helps, because kodi and curl are linked to different libcurl versions...
```
> ldd /usr/lib/x86_64-linux-gnu/kodi/kodi-x11 | grep curl
libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007fa12deeb000)
> ldd /usr/bin/curl | grep curl
libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f0201d73000)

```

## Expected Behavior
Playing of streams regards if it's a https or http stream.

## Actual Behavior
Only http streams of German media stations could be played.

### To Reproduce
1. Start kodi normally
2. Feed it with a https streaming url
 ```kodi-send -a 'PlayMedia("https://swr-dasding-live.sslcast.addradio.de/swr/dasding/live/mp3/128/stream.mp3",0)'```

2b. For comparison here a link to an http-stream of the 'same network':
 ```kodi-send -a 'PlayMedia("http://dg-rbb-http-fra-dtag-cdn.cast.addradio.de/rbb/radioeins/live/mp3/128/stream.mp3",0)'```

### Debuglog

The debug log can be found here:
https://paste.kodi.tv/oralomovif.kodi
Edit: A log with clean .kodi/addons:
https://paste.kodi.tv/borayusafa.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 16.04.5 LTS and others
 - Kodi version:
  • 18.0-ALPHA2 Git:20180612-8e7b085 on Ubuntu 16.04.5 LTS, kernel:  Linux x86 64-bit version 4.13.0-32-generic
  • 18.0-RC1 Git:d99f45c on LibreELEC (Milhouse): devel-20181115210223-#1115-gcf9a0c9 [Build #1115
] 9.0, kernel: Linux ARM 32-bit version 4.19.2
  • 17.6 on Open Source Media Center 2018.10-1, kernel: Linux ARM 32-bit version 4.14.78-2-osmc

**Comment by wsnipex** [comment]
I cannot reproduce on ubuntu 18.04 with kodi rc2, works fine.
I suggest you first upgrade your 5months old kodi version to v18rc2 and provide a new log

**Comment by wsnipex** [comment]
live streams are not supposed to be pauseable

**Comment by YggdrasiI** [comment]
Well, as long as I could the expected behaviour (pausing+caching) with the direct url, I will not argue against this design decision. 

Thanks for your reply.
