### ISSUE TITLE
Dialog for where to save a screenshot opens twice

### ISSUE THREAD

**Issue by EmilVogt** [xbmc/xbmc#15030]
### Describe the bug

When pressing <kbd>Ctrl</kbd> + <kbd>S</kbd> to make a screenshot for _the first time_, the dialog where to save the screenshot ("Select folder") pops up. After clicking on "Cancel" (because you actually don't want to save the screenshot), the dialog closes and opens again. Either you close the dialog again, or you finally give up and let the screenshot be saved somewhere.

## Expected Behavior

Dialog "Select folder" closes and doesn't open again.

## Actual Behavior

Dialog opens again.

### To Reproduce
Steps to reproduce the behavior: (on Windows 10)

1. go to `%APPDATA%\kodi\userdata` and open the "guisettings.xml" file
2. go to line 44 and replace `<setting id="debug.screenshotpath">C:\Path\for\Screenshots\</setting>` with `<setting id="debug.screenshotpath" default="true"></setting>` to reset the location for the screenshots
3. open Kodi and press <kbd>Ctrl</kbd> + <kbd>S</kbd> to make a screenshot
4. in the dialog, which opened, select "Cancel"

### Debuglog

The debuglog can be found here:
[https://paste.kodi.tv/asedayiwal.kodi](https://paste.kodi.tv/asedayiwal.kodi)

### Your Environment
Operating system version/name: Windows 10 (1803), 64bit
Kodi version: 18 (Leia) RC2, 64bit

**Comment by DaVukovic** [comment]
I can kind of reproduce that. But hitting "Cancel" a 2nd time, the window closes and doesn't open anymore. 

Not saying that this behaviour is correct, as it should stay closed after the 1st selection of "Cancel". 

Are you sure you can't close the window by selecting "Cancel" a 2nd time?

Tested on Ubuntu, btw.

**Comment by DaVukovic** [comment]
The more interesting part is, that the screenshot is saved to the kodi temp folder even if you select `cancel` for the first time:

```
17:43:08.575 T:12668   DEBUG: Keyboard: scancode: 0x1d, sym: 0x0132, unicode: 0x0000, modifier: 0x40
17:43:08.575 T:12668   DEBUG: CInputManager::HandleKey: ctrl-leftctrl (0x1f0d0) pressed, action is
17:43:08.857 T:12668   DEBUG: Keyboard: scancode: 0x1f, sym: 0x0073, unicode: 0x0013, modifier: 0x40
17:43:08.857 T:12668   DEBUG: CInputManager::HandleKey: ctrl-s (0x1f053) pressed, action is Screenshot
17:43:08.858 T:12668    INFO: Loading skin file: FileBrowser.xml, load type: KEEP_IN_MEMORY
17:43:08.863 T:12668   DEBUG: ------ Window Init (FileBrowser.xml) ------
17:43:09.033 T:12668   DEBUG: Keyboard: scancode: 0x1f, sym: 0x0073, unicode: 0x0000, modifier: 0x40
17:43:09.412 T:12668   DEBUG: Keyboard: scancode: 0x1d, sym: 0x0132, unicode: 0x0000, modifier: 0x0
17:43:10.762 T:12668   DEBUG: Keyboard: scancode: 0x4d, sym: 0x0113, unicode: 0x0000, modifier: 0x0
17:43:10.762 T:12668   DEBUG: CInputManager::HandleKey: right (0xf083) pressed, action is Right
17:43:10.902 T:12668   DEBUG: Keyboard: scancode: 0x4d, sym: 0x0113, unicode: 0x0000, modifier: 0x0
17:43:11.205 T:12668   DEBUG: Keyboard: scancode: 0x50, sym: 0x0112, unicode: 0x0000, modifier: 0x0
17:43:11.206 T:12668   DEBUG: CInputManager::HandleKey: down (0xf081) pressed, action is Down
17:43:11.309 T:12668   DEBUG: Keyboard: scancode: 0x50, sym: 0x0112, unicode: 0x0000, modifier: 0x0
17:43:12.155 T:12668   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x000d, modifier: 0x0
17:43:12.294 T:12668   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x0000, modifier: 0x0
17:43:12.294 T:12668   DEBUG: CInputManager::HandleKey: return (0xf00d) pressed, action is Select
17:43:12.541 T:12668   DEBUG: ------ Window Deinit (FileBrowser.xml) ------
17:43:12.613 T:12668   DEBUG: Saving screenshot special://temp/screenshot010.png
17:43:12.615 T:10220   DEBUG: cached image 'special://temp/screenshot010.png' size 1920x1080
17:43:12.616 T:12668    INFO: Loading skin file: FileBrowser.xml, load type: KEEP_IN_MEMORY
17:43:12.621 T:12668   DEBUG: ------ Window Init (FileBrowser.xml) ------
17:43:13.465 T:12668   DEBUG: Keyboard: scancode: 0x4d, sym: 0x0113, unicode: 0x0000, modifier: 0x0
17:43:13.465 T:12668   DEBUG: CInputManager::HandleKey: right (0xf083) pressed, action is Right
17:43:13.603 T:12668   DEBUG: Keyboard: scancode: 0x4d, sym: 0x0113, unicode: 0x0000, modifier: 0x0
17:43:13.874 T:12668   DEBUG: Keyboard: scancode: 0x50, sym: 0x0112, unicode: 0x0000, modifier: 0x0
17:43:13.874 T:12668   DEBUG: CInputManager::HandleKey: down (0xf081) pressed, action is Down
17:43:14.009 T:12668   DEBUG: Keyboard: scancode: 0x50, sym: 0x0112, unicode: 0x0000, modifier: 0x0
...
...
...
17:43:15.084 T:12668   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x000d, modifier: 0x0
17:43:15.186 T:12668   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x0000, modifier: 0x0
17:43:15.187 T:12668   DEBUG: CInputManager::HandleKey: return (0xf00d) pressed, action is Select
17:43:15.439 T:12668   DEBUG: ------ Window Deinit (FileBrowser.xml) ------
```

Here's the section where you pressed `ctrl`+`s`, the filebrowser gets initialized and at the moment you went down and hit select, the screenshot has been saved to: `special://temp/screenshot010.png`  which in your case (as you are using Windows) should be: `%appdata%\Kodi\temp` (not so sure, not using Windows much, tbh)

At least I can confirm that the screenshot is being saved at: `~/.kodi/temp` while using Ubuntu even if you select `cancel`

**Comment by EmilVogt** [comment]
:smile: Found them. 
Thanks for telling me. So, Kodi saved the screenshots in `%APPDATA%\Kodi\Cache` (Windows 10) even though I clicked on "Cancel".

**Comment by lrusak** [comment]
What do you think the expected behaviour should be?

If you select "cancel" should we just bail out instead of taking a screenshot or are you ok with the behavior as it is now?

**Comment by MartijnKaijser** [comment]
Bail imo

**Comment by lrusak** [comment]
> Bail imo

If that's the case it should be a trivial fix and we should just bail out here if `CGUIControlButtonSetting::GetPath` returns false
https://github.com/xbmc/xbmc/blob/master/xbmc/utils/Screenshot.cpp#L249

**Comment by DaVukovic** [comment]
@lrusak generally I would say, if I cancel something there shouldn´t be another window popping up asking me for the same. I also would vote for, that if I cancel something, that Kodi shouldn´t do that anyway. The actual behaviour saves a screenshot after pressing `ctrl`+`s` and I can´t do anything against it. 

So my suggetion is, if I cancel something, it should simply be canceled and Kodi shouldn´t do that in the background anyway with zero information for the user what has happened (beside the log). 

If no path is set to where the screenshot saved to and you press `ctrl`+`s`, I`m fine with using `special://temp` but then we should probably sent a notification like `Your screenshot has been saved to.....` or something like that. But then there might be no need to ask for a path. And if we would like to ask to ask for a path (if none is set) and if I cancel that window, Kodi shouldn´t do anything. 

jm2c
