### ISSUE TITLE
Amazon Fire TV 4k and Kodi 18 RC3: No gz/gzip installed/available

### ISSUE THREAD

**Issue by Krawei** [xbmc/xbmc#15039]
### Describe the bug

Hello everybody,

I have a nasty problem with a freshly-installed kodi 18 nightly and app "Mediathekview" under my Fire-TV 4K Stick Kodi-Setup:

When I click on "Datenbank aktualisieren" Kodi tells me that my DB is going to be updated in a few moments. MEdiathekview starts to ownload the "Filmliste-akt.gz", but after the download completes, nothing happens, the db is not going to be initially build or updated.

It seems that Mediathekview can't decompress the .gz-file:

22:17:27.714 T:18446744071768066336 NOTICE: [plugin.video.mediathekview-0.5.0:Updater]: Trying to decompress gz file...
22:17:43.174 T:18446744071768066336 ERROR: [plugin.video.mediathekview-0.5.0:Updater]: gz decompression failed: [Errno 22] Invalid argument
22:17:43.175 T:18446744071768066336 NOTICE: [plugin.video.mediathekview-0.5.0:Updater]: Return -1
22:17:43.175 T:18446744071768066336 NOTICE: [plugin.video.mediathekview-0.5.0:Updater]: Cleaning up downloads...

Is that problem known? What can I do to solve it?

FYI: All archive addons has been installed from the official kodi repository (under "virtual filesystems")

## Expected Behavior
Decompress the "Filmliste-akt.gz" and fill up the app's own sqlite-db

## Actual Behavior
Nothing happends after the download of "filmliste-akt.gz" due to the missing gz (see debug log)

## Possible Fix
deploy gzip addon via official kodi repository (like the rar-archive plugin for example)

### To Reproduce
- install Kodi 18 nightly via adblink on fire tv 4k
- install archive-plugins from official kody repository (under "virtual file systems)
- install Mediathekview app in kodi
- initiate an manual db update
- see bug

### Debuglog
The debuglog can be found here:
https://privatebin.net/?3104ad37af7e121a#skwWqYNBlY3LZ9jrjsZJ/XYE4ljo+q+E2PJpDy/CNKI= 

### Your Environment
Used Operating system:
 - [x] Android
 
 - Operating system version/name: Fire OS 6.2.3.2 (NS6232/1268)
 - Kodi version: Kodi 18.0-RC3 Git:20181210-10edcdb

**Comment by lrusak** [comment]
Thanks for the report, however upon inspection this issue doesn't have anything to do with core Kodi. Please report this to the add-on author. Thanks.

**Comment by tuxpoldo** [comment]
Hi @lrusak ,

unfortunately this is not correct. The problem is related to core Kodi, but only in the Version for Android running on devices like the Amazon Fire TV 4K: it seems that starting from some RC-Version of Kodi 18 the included Python `gzip` library crashes when trying to decompress `gzip` files in an add-on.

We made several tests and were able to reproduce the issue. The add-on now contains a workaround: if the python routine crashes, it tries to determine if a `gzip` utility is available on the target system and if yes, it decompresses the file by calling `gzip` in a subprocess:

````
def _decompress_gz(self, sourcefile, destfile):
    blocksize = 8192
    # pylint: disable=broad-except

    try:
        with open(destfile, 'wb') as dstfile, gzip.open(sourcefile) as srcfile:
            for data in iter(lambda: srcfile.read(blocksize), b''):
                dstfile.write(data)
    except Exception as err:
        self.logger.error(
            'gz decompression of "{}" to "{}" failed: {}', sourcefile, destfile, err)
        if mvutils.find_gzip() is not None:
            gzip_binary = mvutils.find_gzip()
            self.logger.info(
                'Trying to decompress gzip file "{}" using {}...', sourcefile, gzip_binary)
            try:
                mvutils.file_remove(destfile)
                retval = subprocess.call([gzip_binary, '-d', sourcefile])
                self.logger.info('Calling {} -d {} returned {}',
                                 gzip_binary, sourcefile, retval)
                return retval
            except Exception as err:
                self.logger.error(
                    'gz commandline decompression of "{}" to "{}" failed: {}',
                    sourcefile, destfile, err)
        return -1
    return 0
````

Although the add-on now works thanks to this workaround, it is a fact that the `gzip` library in the Android-Version of Kodi 18 is broken. In addition we noticed that the Android-Version of Kodi lacks also the `bz2` library that can be loaded from an add-on in all other versions of Kodi.

**Comment by Krawei** [comment]
@lrusak Please reopen this issue.

**Comment by tuxpoldo** [comment]
@lrusak I would like to point out that the logfile posted by @Krawei was taken with a special version of the plugin that outputs better debug information in order to determine where the exception occurs. The specific logfile line is:

````
2019-03-09 21:30:32.506 T:6302   ERROR: [plugin.video.mediathekview-0.6.0:Updater]: gz decompression of "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.mediathekview/Filmliste-akt.gz" to "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.mediathekview/Filmliste-akt" failed on reading gz file: [Errno 22] Invalid argument
2019-03-09 21:30:32.506 T:6302  NOTICE: [plugin.video.mediathekview-0.6.0:Updater]: Return -1
````

The debug version of the routine that created this log entry was:

````
def _decompress_gz(self, sourcefile, destfile):
    blocksize = 8192
    # pylint: disable=broad-except,line-too-long

    try:
        srcfile = gzip.open(sourcefile)
    except Exception as err:
        self.logger.error('gz decompression of "{}" to "{}" failed on opening gz file: {}'.format(
            sourcefile, destfile, err))
        return -1

    try:
        dstfile = open(destfile, 'wb')
    except Exception as err:
        self.logger.error('gz decompression of "{}" to "{}" failed on opening destination file: {}'.format(
            sourcefile, destfile, err))
        return -1

    try:
        for data in iter(lambda: srcfile.read(blocksize), b''):
            try:
                dstfile.write(data)
            except Exception as err:
                self.logger.error('gz decompression of "{}" to "{}" failed on writing destination file: {}'.format(
                    sourcefile, destfile, err))
                return -1
    except Exception as err:
        self.logger.error('gz decompression of "{}" to "{}" failed on reading gz file: {}'.format(
            sourcefile, destfile, err))
        return -1
    return 0
````

This shows clearly that the exception occurred in `srcfile.read(blocksize)` where `srcfile` is the result of a successful `gzip.open`.

**Comment by Endur** [comment]
The error we got is because the gzip library included into Python doesn't work as expected for Android. This isn't related to Fire TV only, instead it seems to be a general issue :(

**Comment by nuwonda** [comment]
last working build for fire tv basic is:
kodi-20190523-3bb5115b-master-armeabi-v7a.apk dated May 24th (build from 23rd)

any build after that keeps crashing immediately back to Fire TV home menu after the "clearing cache" followed by "preparing for first launch..." message disappears.

reinstalling the kodi-20190523-3bb5115b build will work, so it must be a change from this build to the one after that broke it.
