### ISSUE TITLE
Scaling between different resolution screens problem and save in memory start

### ISSUE THREAD

**Issue by Djinn1** [xbmc/xbmc#15048]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have multiply screen 1080p screens and 4K TV. When moving Kodi from 1080p screen or vice versa to the next screen the scaling is gets messed up and Kodi is stuck on same size on frame but not the background.

When starting Kodi on one screen then when I close it, Kodi does not remember latest screen to start from and always goes back to screen 1 (not even my default screen chosen in Window).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

1. Both the frame and background should be the same and it should scale down or up to the screen resolution size without a issue of stretching or scaling problem.

2. Should save the latest screen to start from in memory

## Actual Behavior

The Scaling is off and Kodi don´t start where it left of.

## Possible Fix

Kodi Krypton worked great

### To Reproduce

1. Move Kodi from different resolution screens and this will happened every time.

2. Start Kodi, move it to desire screen, close Kodi then restart computer and open Kodi again.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/aqecodowed

### Screenshots 
Here are some links or screenshots to help explain the problem:

<a href="http://tinypic.com?ref=29nv7yg" target="_blank"><img src="http://i64.tinypic.com/29nv7yg.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 X64 1809
 - Kodi version: Kodi RC2 X64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
The moderators have determined that Banned_addons are present on your system. To receive assistance here, these banned items must be removed. If a clean log is not submitted within 3 days, then this Issue will be closed

**Comment by KarellenX** [comment]
Thanks but...
1 there are still left over 13Clowns modules.
2 Debug Mode was not enabled
3 Capture the problem while debug mode is running.

Still Invalid.

**Comment by Djinn1** [comment]
@KarellenX Reinstalled Kodi completely. Have to be clean now. Same problem with clean install.

**Comment by DaVukovic** [comment]
`NOTICE: Disabled debug logging due to GUI setting. Level 0.`

Still not a debuglog. 

Enable debug logging via: settings -> system -> logging -> enable debug logging

We are now waiting since more than 3 days. Please submit the log in the next 24 hours. If not done, then this issue will be closed.

**Comment by MartijnKaijser** [comment]
install a nightly version

**Comment by DaVukovic** [comment]
Installing add-ons isn't the problem here.

Can you confirm if your problem is solved with that Kodi version?

**Comment by Djinn1** [comment]
nope

**Comment by Djinn1** [comment]
I updated the loggfile with debug mode enable

**Comment by Rechi** [comment]
> Starting Kodi (18.0-RC2 Git:20181202-812855d84e)

@Djinn1 that version is two weeks old, share the log from a more recent one.

**Comment by e1d1s1** [comment]
@Rechi This is just another way to reproduce the scaling issues reported with #14843 , that one has all the logs you should need. Problem still exists in RC3.

**Comment by DaVukovic** [comment]
@Djinn1 I removed the label (for now) as you submitted a logfile with debugging enabled, but you still have to share a logfile with a recent nightly build. 

If you won t do that, we can't do anything and this issue might even get closed. 

Thanks in advance.

**Comment by Djinn1** [comment]
@DaVukovic 

Problem still exist in latest version of Kodi 18 x64. Why have this not been fixed? I though in final release it gonna be fixed.

**Comment by pkerling** [comment]
> Why have this not been fixed?

Because you did not submit a fix.
