### ISSUE TITLE
[Linux] VAAPI HEVC causes video hardware hang

### ISSUE THREAD

**Issue by mlauss** [xbmc/xbmc#15041]
### Describe the bug
Linux: 4K HEVC video, played back with kodi HEVC VAAPI acceleration enabled, causes the i915 video
decoder hardware to crash.   A single frame is displayed, audio continues in the background.
The same video file played with "mpv --hwdec=vaapi --vo=vaapi" shows no such problems,
which leads me to believe that this is a problem in the way kodi uses vaapi.
Disabling HEVC acceleration works around it (poorly).  No issues with other codecs.

[drm] GPU HANG: ecode 9:2:0xa8dfbffd, in VideoPlayer [47328], reason: hang on vcs0, action: reset
[drm] GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
[drm] Please file a _new_ bug report on bugs.freedesktop.org against DRI -> DRM/Intel
[drm] drm/i915 developers can then reassign to the right component if it's not a kernel issue.
[drm] The gpu crash dump is required to analyze gpu hangs, so please always attach it.
[drm] GPU crash dump saved to /sys/class/drm/card0/error
i915 0000:00:02.0: Resetting vcs0 for hang on vcs0

### To Reproduce
kodi as of commit  eab9e42f98fdb64cc7ef72b492936c90a2134964
have i915 hardware (tested on KabyLake ), linux-4.19.6
libva-2.3.0,  libva-intel-driver-2.2.0
Test video file here: https://drive.google.com/file/d/1LuQaFt2QrucZ6qiIcLaQG3e3VuxR0AQy/view?usp=sharing   (10s, 64MB)

### Your Environment
Used Operating system:

 - [X] Linux

 - Operating system version/name: linux-4.19.6, mesa-18.3-rc5, libva-2.3.0, libva-intel-driver-2.2.0
 - Kodi version: 18, commit eab9e42f98fdb64cc7ef72b492936c90a2134964
 - Hardware: core i5-7260U (Kabylake)

Thanks!

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
I can try on my hardware, but problems like this usually indicate driver issues. It should not be possible for applications to hang the GPU.

**Comment by mlauss** [comment]
Maybe; I first reported this to the vaapi developers, but I can't reproduce the hang with "mpv" player, just with kodi's integrated player.

**Comment by pkerling** [comment]
Also please remove your log from the issue description and upload a complete and debug-enabled log (on GH or via paste.kodi.tv)

**Comment by pkerling** [comment]
Does it work with mpv and without `-vo vaapi`? (You are actually not supposed to use it)

**Comment by mlauss** [comment]
mpv -v --hwdec=vaapi testfile.mkv    works well, fluid playback while I recompile kodi in the background.

**Comment by mlauss** [comment]
I've changed kodi parameters to precache as much of the file as RAM allows before starting playback, because it's on a nfs share over a (not so good) wireless link, and the problem has gone away.

**Comment by pkerling** [comment]
Curious case. I assume that the VAAPI decoder times out because the buffer is not filled in time and the GPU hang happens on shutdown (which means it's not directly related to the problem of not being able to play the file).

@FernetMenta Your opinion?

**Comment by pkerling** [comment]
OK then I think we can keep this closed at least until we get another bug report/more input if this is actually a persistent issue.
