### ISSUE TITLE
problem with "longpress" actions in keymap.xml under LibreELEC (Leia) v8.90.009 ALPHA

### ISSUE THREAD

**Issue by MisterFloppy** [xbmc/xbmc#15058]
### Describe the bug
Here is a clear and concise description of what the problem is:

My previous modified "keymap.xml" located in the "userdata" folder/"keymaps" subfolder does not work anymore with my remote control after I've upgraded from KODI v17.6 to KODI v18 (RC2) using LibreELEC (Leia) v8.90.009 ALPHA. There are two issues:

1. the codes of the remote control buttons did change from KODI v17.6 to 18, so I had to determine them all again with the help of the "Keymap Editor" AddOn
2. the "longpress" actions are not working anymore and also prevent the "normal" behaviour of the short pressed key

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

1. the codes of the remote control buttons under KODI v17.6 should be valid under KODI v18, too, to avoid the hassle of having to determine them all again
2. "mod=longpress" should work under KODI v18 like it did under KODI v17.6 and should not interfere with the "normal" behaviour when short pressing the remote control buttons

## Actual Behavior

1. the codes did change
2. "mod=longpress" does not work and interferes with the "normal" behaviour when short pressing the remote control buttons

### To Reproduce

Example 1:
-----------
```
<keymap>
  <global>
    <keyboard>
      <key id='232'>ActivateWindow(TVRecordings)</key>
    </keyboard>
  </global>
</keymap
```

When pressing my remote control button 30 in this example it works as it should (-> the window with the TV recordings pops up).

Example 2:
-----------
```
<keymap>
  <global>
    <keyboard>
      <key id='232'>ActivateWindow(TVRecordings)</key>
      <key id='232' mod="longpress">ActivateWindow(Favourites)</key>
    </keyboard>
  </global>
</keymap>
```

When long pressing my remote control button 30 in this example it does not work as it should (-> the window with the favourites does not pop up), and when short pressing my remote control button 30 the window with the TV recordings also does not pop up....

### Debuglog

The debuglog can be found here:

Example 1
At  03:36:17.816 I did press remote control button 30 for the first time
https://pastebin.com/9nx2YF9v

Example 2
At  03:53:30.332 I did press remote control button 30 for the first time
https://pastebin.com/rZDp5ULK

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC (Leia) v8.90.009 ALPHA
 - Kodi version: 18 RC2
![oe-remote](https://user-images.githubusercontent.com/6067839/49974665-a79bed00-ff3a-11e8-9d0a-ffcccc1c2041.png)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Did you report this to LibreELEC at all? Lot's has changed with the input handling for lirc / eventlircd / ir-keytable between 8.2.5 and 8.90.009. It might be worth making an thread on the LibreELEC forum describing your issue as it might be a configuration error or some legacy interaction.

**Comment by DaVukovic** [comment]
This issue is now handled at LibreELEC forums.

So I guess that one is good to close then.

**Comment by JanOonk** [comment]
Can you post a link to the specific LibreElec forum and/or thread/topic for reference? So we can monitor the progress of the bug.
