### ISSUE TITLE
"import socket" prevents python script execution when using "RunScript" method under KODI 18 for Windows

### ISSUE THREAD

**Issue by MisterFloppy** [xbmc/xbmc#15059]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm using the "RunScript" method to execute the python script "texturecache.py" by Milhouse in the background and not in the context of the Kodi process - for details please look here: http://forum.kodi.tv/showthread.php?tid=158373&pid=2233049#pid2233049
http://forum.kodi.tv/showthread.php?tid=158373&pid=2799416#pid2799416

Since upgrading from KODI v17.6 to KODI v18 (RC2), the solution I posted in the links mentioned above doesn't work under Windows 7 anymore. Milhouse and me found out that there is a problem regarding the use of "import socket" under "KODI 18 for Windows", so he advised to report this bug here.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The python script should be executable using the "RunScript" method.

## Actual Behavior

The python script does not execute using the "RunScript" method.

### To Reproduce
Notes:
a) Since Windows (other than Linux) has no built-in Python interpreter and bash shell, you have to install them separately.
b) To avoid any problems with KODI, you have to install "Python 2.x" - "Python 3.x" won't work!
c) The paths to the executable files must be added to the environment variable PATH in Windows.

1. Download and install a "Python 2.x" version from the website under https://www.python.org/downloads/windows/ ; make sure that you enable "Add python.exe to path" in the process of installation!
2. Download and install "Git for windows" (which provides a BASH emulation) from the website under https://git-for-windows.github.io/ ; make sure that you enable "Use Git and optional Unix tools from the Windows Command Prompt" in the process of installation!

Here's the script called "shell.py" for running the other python script via "Runscript":

```
!/usr/bin/env python
# -*- coding: utf-8 -*-
import os, subprocess, sys, xbmc
def shellcmd(args):
  if sys.argv[1].endswith(".py"):
    command = "python " + " ".join(args)
  elif sys.argv[1].endswith(".sh"):
    command = "sh " + " ".join(args)
  subprocess.call(command, shell=True)
def notify(header, text):
  xbmc.executebuiltin('notification(%s, %s)' % (header, text))
def shellnotify(args):
  os.chdir(os.path.dirname(os.path.realpath(__file__)))
  pidfile = "shellpy.pid"
  if os.path.isfile(pidfile):
   notify("Already running!", file(pidfile, 'r').read())
   sys.exit(1)
  file(pidfile, 'w').write(" ".join(args))
  try:
    notify("Starting...", " ".join(args))
    shellcmd(args)
    notify("Finished", " ".join(args))
  finally:
    os.unlink(pidfile)
shellnotify(sys.argv[1:])
```

Example 1 ("test.py" without "import socket"):

```
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
import os, sys, time
c = int(sys.argv[1])
for z in range(0,c):
  sys.stdout.write("\a")
  time.sleep(3)
```

by calling "RunScript(special://userdata/scripts/shell.py,./test.py,6)"
-> it works, I can hear the sound 6 times in total

Example 2  ("test.py" with "import socket"):

```
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
import os, sys, time, socket
c = int(sys.argv[1])
for z in range(0,c):
  sys.stdout.write("\a")
  time.sleep(3)
```

by calling "RunScript(special://userdata/scripts/shell.py,./test.py,6)"
-> the script test.py isn't executed

### Debuglog

The debuglog can be found here:
http://pastebin.com/EEnEpY9X

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 7
 - Kodi version: KODi v18 (RC2)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MilhouseVH** [comment]
Could this have anything to do with Python Reuse #13814?

**Comment by ronie** [comment]
just as a side note, running .py files directly has been deprecated since several years

```01:54:31.515 T:5272   DEBUG: CPythonInvoker(13, special://userdata/scripts/shell.py): the source file to load is "special://userdata/scripts/shell.py" ("C:\Users\Stefan\AppData\Roaming\Kodi\userdata\scripts\shell.py")```
```01:54:31.515 T:5272 WARNING: CPythonInvoker(13): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.```

while i don't think the functionality has been deliberately been removed in v18, the proper fix would be to convert your python code into  proper addon.

**Comment by pkerling** [comment]
Why do you need to use `RunScript` just to create an external process anyway?

**Comment by MisterFloppy** [comment]
@pkerling:
By using "texturecache.py" with parameters via "RunScript" it is possible to create a button in the kodi home menu or map this to a remote control button. 

For instance to map this to a remote control button:
<red>XBMC.RunScript(special://profile/shell.py,./texturecache.py,c)</red>

As a bonus you'll get notifications on start and finish, and you won't be able to run multiple instances (which wouldn't be good).

Source:
https://forum.kodi.tv/showthread.php?tid=158373&pid=2233049#pid2233049

**Comment by MilhouseVH** [comment]
I'd forgotten I gave you that script sooo long ago. I've just tested it on LibreELEC (Linux) with latest Kodi master and it's working fine with texturecache.py (and probably any other script that uses `import socket`) so I'm not sure why Kodi 18 on Windows would now have a problem.

Presumably you've gone back to Kodi 17.6 and confirmed that is still working? And only when you upgrade to Kodi 18-RC does it stop working (no other changes to your environment?)

Are there nightly Windows builds of Kodi 18 available that would help you to narrow down when the problem started?

**Comment by MisterFloppy** [comment]
Yes, exactly:
- KODI v17.6: "RunScript" method running fine on all platforms (LibreElec and Windows 7)
- after upgrading to KODI 18 RC2 without changing anything to my environment: "RunScript" method running fine on LibreELEC, but not under Windows 7 anymore
- tested it also with the newest build, RC3, same problem

**Comment by MisterFloppy** [comment]
Guys, I've found the cause!!!

As I'm using Windows 7 64bit version, I was asuming that installing KODI 18 64bit version would be the best choice.  I've just tested installing KODI 18 32bit version  (and I got immediatley the message that there is a more suitable 64bit version for download available and was asked if I would like to install it anyway) and guess what? The "RunScript" method is working fine!!!!!

So, it is the 64bit version of KODI 18 that's giving trouble, KODI 18 32bit version has not this problem!

In the meantime, I will stay with the 32bit version, but I'm of course hoping that some developer will make KODI 18 64bit compatible, too :-)

**Comment by MisterFloppy** [comment]
Oh my god.... everything is okay, also KODI 18 64bit version IS working fine regarding the "RunScript" method - it was all my fault...

Obviously, I had installed "Python 2.x" in its 32bit version, and because there is only a 32bit version of KODI v17.6, no problems occured.

Then KODI 18 came out, and I chose the first download link (=64bit version), but did forget to remove the 32bit version of "Python 2.x" and replace it with its 64bit version...

After doing so, all is working fine now!

I'm sorry for having caused confusion :-)
