### ISSUE TITLE
Kodi crashes by pressing 'x' to stop DVD .iso image when "Player Process Info" is displayed

### ISSUE THREAD

**Issue by MHSwizzleStick** [xbmc/xbmc#15055]
### Describe the bug
Here is a clear and concise description of what the problem is:

While playing a DVD image iso file, press "o" to display "Player Process Info". While this is being displayed, press "x" to stop the playback. Kodi crashes. See thread [https://forum.kodi.tv/showthread.php?tid=338307](url)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The playback of the DVD .iso image should simply stop.

## Actual Behavior

Kodi crashes.

### To Reproduce

1. Play a DVD .iso image
2. Press 'o'
3. Press 'x'

### Debuglog

The debuglog can be found here:
[https://paste.kodi.tv/xuperuqowo.kodi](url)

### Screenshots 
Here are some links or screenshots to help explain the problem:

See screenshots in the following thread:
[https://forum.kodi.tv/showthread.php?tid=338307](url)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I have found no other situation in which pressing 'x' causes Kodi to crash. The crash seems to be very specific to the one scenario described above.

### Your Environment
Used Operating system:

 - [ ] Windows 7

 - Operating system version/name: Windows 7 Ultimate, Service Pack 1, 64-bit
 - Kodi version: kodi-18.0-Leia_rc2-x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
here is a crashlog from this being reproduced using LibreELEC -> https://pastebin.com/EUHzzfKr

**Comment by FernetMenta** [comment]
@lrusak release the shared ptr at the end of the if block https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L4267
