### ISSUE TITLE
Black screen when starting Leia on 720p TV

### ISSUE THREAD

**Issue by metronidazole** [xbmc/xbmc#15053]
### Describe the bug
I have a black screen on starting Leia. It was working fine initially on a 1080p TV, but I recently moved my NVIDIA shield to a 720p TV and updated to the latest SHIELD update 7.2 (at the same time) and now I have a black screen on startup.

## Expected Behavior
Kodi is visibile.

## Actual Behavior
Blackscreen.

## Possible Fix
N/A

### To Reproduce
1. Attach android TV device to 720p TV
2. Run kodi 18
3. Blackscreen.

### Debuglog
The debuglog can be found here:
https://pastebin.com/y52fj8Ld

## Additional Info
Other people with 720p TVs have the same issue: https://forum.kodi.tv/showthread.php?tid=337238

### Your Environment
Used Operating system:
Android 8
NVIDIA shield experience 7.2
Kodi 18 RC

**Comment by MartijnKaijser** [comment]
duplicate https://github.com/xbmc/xbmc/issues/14925

**Comment by metronidazole** [comment]
This issue is resolved in the latest nightly (2018/12/17).
