### ISSUE TITLE
Addon Settings: Visibility Not Working

### ISSUE THREAD

**Issue by goocreations** [xbmc/xbmc#15062]
### Describe the bug
The "visible" option does not work if it has a condition that pulls the value of a setting that was previously declared in another category. For instance:

```
<category label="Group 1">
   <setting id="option1" type="bool" visible="false" />
</category>
<category label="Group 2">
   <setting id="option1" type="bool" label="Option 1" default="false" />
   <setting id="option2" type="text" default="some value here" label="Option 2" visible="eq(-1,true)" />
</category>
```

In this example "option2" always stays hidden, even if "option1" is enabled. The problem seems to be that the setting was declared in a PREVIOUS category (in my case, the value of "option1" is used in category 1, so it is required there). If "option1" is removed from "Group 1", then "option2" is correctly hidden.  But if "option1" is added to a previous category, it stops working.

## Expected Behavior
The "visible" attribute should work, even if the condition relies on an element previously defined in another category/group.

## Actual Behavior
The "visible" option stops working if its conditions relies on an element declared in a previous group. This might not only be restricted to the "visible" attribute, but all attributes that can take conditions (eg: "enable").

## Possible Fix
Don't know. Somehow parsing stops after the element was found the first time, instead of continuing to search until the actual element declaration was discovered. This only happens in Kodi 18, previous versions worked fine. Maybe check how it was done in Kodi 17.

### To Reproduce

1. Create a new default addon.
2. Add the settings XML provided above to "settings.xml".
3. Open the addon's settings dialog and enabled "option1".
4. As can be seen, "option2" is never made visible.

### Debuglog
Nothing in the debug log about this. 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 7, Windows 10, Ubuntu 16, Ubuntu 18 (most likely happens on all OSs).
 - Kodi version: 18.0 RC2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by goocreations** [comment]
Just installed the latest nightly and it seems that this issue has been fixed. However, there are now a bunch of other issues:

1. Some of the cross-group dummy settings that have visible="false", now show up in the dialog.
2. Some other settings never show up in the dialog, although they don't even have a visible attribute.

**Comment by enen92** [comment]
Closing this issue as it was reported fixed.
@goocreations please open a new issue for the other regressions you identified and please give concrete examples.
