### ISSUE TITLE
Addon Settings: Labels starting with numbers

### ISSUE THREAD

**Issue by goocreations** [xbmc/xbmc#15064]
### Describe the bug
When using labels that start with a digit (0 - 9), the label is not displayed in the addon settings. For instance:

`<setting id="setting1234Q" type="bool" label="1234Q" />
`

Here Kodi 18 only shows an empty string in the settings dialog, instead of the string: "1234Q"

## Expected Behavior
The label should show as provided in the XML attribute. In this example "1234Q".

## Actual Behavior
An empty string is displayed instead of the string. Only happens in Kodi 18, older versions are fine.

## Possible Fix
This might be due to the detection of msg numbers in the translation file (.po files). Maybe the new code checks if the label starts with a number, and if so it assumes it is the ID of the entry int he translation file. This detection should be reverted to what Kodi 17 did. If this is done with regex, then the expression is not complete. Check if the ENTIRE string matches a number without any other characters, not that the string STARTS WITH a digit. This might be the case, since if I add a letter in front of the label (eg "a1234Q"), then it is displayed as intended.

### To Reproduce
1. Create a default addon
2. Create a XML element with a label that starts with a number.
3. The label is not displayed in the addon setting dialog.

### Debuglog
Nothing in debug log.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 7, Windows 10, Ubuntu 16, Ubuntu 18 (other OSs might have the same issue)
 - Kodi version:  18.0 RC2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
likely this was fixed last week:
https://github.com/xbmc/xbmc/pull/15015

if you can, please test with the latest nightly build.

**Comment by host505** [comment]
To my experience with the problem, hardcoded labels (ie labels not defined via strings in language files) starting with a number, get the string definition from kodi's used ui language.
@goocreations do you use a language on kodi ui other than english? If yes, can you check that the 1234 string of your example exists on your language's lang file?
https://github.com/xbmc/repo-resources/tree/leia
Also, can you switch to en language on kodi, your example should appear as [Programs & pictures & music](https://github.com/xbmc/xbmc/blob/master/addons/resource.language.en_gb/resources/strings.po#L4260-L4262).

Not sure if it's actually a kodi bug, but I've found 2 ways to circumvent this:
1. Define the label via string on add-on's language file
2. If hardcoded label is preferred, append the $NUMBER[] keyword to the label (eg `label="$NUMBER[1234]Q"` in your case)

**Comment by goocreations** [comment]
I have only an English file, no other languages. And my Kodi is also English.
And no, I do not have any string in the language file with "1234". I think that's why it shows and empty label, because Kodi tries to lookup 1234 in the language file, cannot find it, and then displays an empty string.
