### ISSUE TITLE
Please add support for ApplePi DAC

### ISSUE THREAD

**Issue by orchardaudio** [xbmc/xbmc#15066]
## Roadmap or todo suggestion
**Detailed Description**
Please add support for ApplePi DAC that is reference here:
https://github.com/raspberrypi/linux/issues/2302

### Context
This change will make it easier for user to use the ApplePi DAC with your software. I have had multiple customer request.

Here are the overlay files.
[ApplePi-DAC_dtbo_dts.zip](https://github.com/xbmc/xbmc/files/2681723/ApplePi-DAC_dtbo_dts.zip)

**Comment by lrusak** [comment]
I'm sorry but this doesn't have anything to do with Kodi. Please ask the relevant distros (LibreELEC, OSMC, etc) to add support.
