### ISSUE TITLE
Kodi segfaults on start.

### ISSUE THREAD

**Issue by BytEvil** [xbmc/xbmc#15060]
Hi. Last worked build b788e08. At commit 0665f06 and up to latest commit Kodi segfaults on start. Crashlog is [here](https://pastebin.com/4z7mmBGZ).

**Comment by ksooo** [comment]
Which kind of special  build you are using that the Kodi log file cannot  be found? The Fatah dump looks weird, as there seems not to be a "main" thread. Crash is do to some JSON rpc call from python...

Without more information and a log file I cannot make anything useful out of this.

**Comment by BytEvil** [comment]
[Here](https://pastebin.com/mhMMY0a8) is kodi.log. What other information is needed?

**Comment by ksooo** [comment]
Have you an explanation where the python to json-rpc call during start up comes from? This call is causing the crash (if the crash dump is correct).

**Comment by ksooo** [comment]
Is this some addon doing pvr stuff on startup?

**Comment by ksooo** [comment]
> load skin from: /home/vis/.kodi/addons/skin.aeon.madnox

Please uninstall this skin and all the stuff it depends on (skinhelper etc.). Does the crash also happen with the default skin Estuary?

**Comment by ksooo** [comment]
Are you doing your own builds? If so, can you enable debug and post another crash dump, then?

**Comment by BytEvil** [comment]
Where can i turn on debugging? 1.2.3 advancedsettings.xml for everything @ https://kodi.wiki/view/Log_file/Advanced

**Comment by enen92** [comment]
Might be another issue related to the busydialog, similar to this one?
https://github.com/xbmc/xbmc/issues/14838

If python calls some method that activates the busydialog that "guard" will be triggered and Kodi just crashes

**Comment by ksooo** [comment]
> Where can i turn on debugging?

 I ment can you compile your own kodi, with debug symbols so that i can get a more comprehensive crash dump?

**Comment by ksooo** [comment]
> If python calls some method that activates the busydialog that "guard" will be triggered and Kodi just crashes

 The crash dump looks different.

**Comment by BytEvil** [comment]
Please see here [xbmc/xbmc@0665f06#diff-27075c504fe0bd619ec3c459cdb92d41R355](https://github.com/xbmc/xbmc/commit/0665f06670962f1adbb9bcb9643c014d4ffa6802#diff-27075c504fe0bd619ec3c459cdb92d41R355)
Send a OnUpdate notification without data value, but the definition clearly state that data is mandatory
[https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/notifications.json#L250](https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/notifications.json#L250)
Any notification consumer will crash and causes issues.

**Comment by ksooo** [comment]
Good catch. 

@Davukovic can you please the regression you've introduced with your PR?  Thanks.

**Comment by DaVukovic** [comment]
Will do :+1:

**Comment by DaVukovic** [comment]
@BytEvil 

could you please check if that ^^ fixes your problem? Thanks and sorry.

**Comment by BytEvil** [comment]
@DaVukovic 

Thanks. Problem solved , no segfaults at start...

**Comment by DaVukovic** [comment]
Cool. Thanks for the feedback
