### ISSUE TITLE
Timeshift offset does not decrease when skipping forward

### ISSUE THREAD

**Issue by rbuehlma** [xbmc/xbmc#15076]
### Describe the bug
Here is a clear and concise description of what the problem is:

When pausing a live (PVR) stream, the timeshift indicator starts to increase after 10 seconds. If I then continue to play the stream, the indicator freezes which i think is correct. But If I then skip forward, the indicator does not decrease.

This has been tested with pvr.zattoo and inputstream.adaptive (dash stream).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Timeshift incidator decreases if stream is skipped forward.

## Actual Behavior

Timeshift indicator does not change on skipping forward.

### To Reproduce

1. Start a live DASH stream (e.g. with pvr.zattoo)
2. Pause stream for e.g. 60 seconds
3. Resume stream
4. Skip forward by e.g 60 seconds
5. Timeshift still shows -60 seconds.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/hinesesada.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.10
 - Kodi version: 18.0-RC3 Git:20181215-4c17e77

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
inputstream.adpative needs to implement ITime interface. Otherwise some timeshift timings will not work correctly.

**Comment by ksooo** [comment]
@peak3d ping

**Comment by rbuehlma** [comment]
Found this issue https://github.com/peak3d/inputstream.adaptive/issues/154
In this case, this one is probably a duplicate and at the wrong repo :)

**Comment by ksooo** [comment]
yep
