### ISSUE TITLE
Amazon Fire TV 4k and Kodi 18 nightly: Debug log is not being generated in current build

### ISSUE THREAD

**Issue by Krawei** [xbmc/xbmc#15071]
### Describe the bug
When I'm activating the debug log function under Settings => System => Logging => enable debug log, Kodi shows me the well-known LOG-Path, and the MEM and CPU consumption. 
But when I'm opening the kodi.log with adbLink, the file is kinda empty. 

All I see are just the first 4 lines of notice entries from the kodi start:

13:50:28.835 T:18446744071938210080  NOTICE: -----------------------------------------------------------------------
13:50:28.835 T:18446744071938210080  NOTICE: Starting Kodi (18.0-RC3 Git:20181214-4c17e77). Platform: Android ARM 32-bit
13:50:28.837 T:18446744071938210080  NOTICE: Using Debug Kodi x32 build
13:50:28.837 T:18446744071938210080  NOTICE: Kodi compiled 

Any other action after that seems not being logged.

## Expected Behavior
Kodi should fill up its debug file "kodi.log" with every single usage detail like it did before.

## Actual Behavior
See "Describing the bug"

### To Reproduce
- install Kodi 18 nightly via adblink on fire tv 4k
- enable debug log
- edit the debug log or pull it from the fire tv via adblink
- see bug

### Debuglog
Not available due to the issue.

### Your Environment
Used Operating system:
 - [x] Android

- Operating system version/name: Fire OS 6.2.5.8 (NS6258/1604)
- Kodi version: Kodi 18.0-RC3 Git:20181214-4c17e77

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
That looks funny

Could you try the kodi logfile uploader addon for a 2nd check, please.

**Comment by Krawei** [comment]
@DaVukovic 
Thanks for your help, that way worked like a charm.

Debug log here: paste.kodi.tv/vuwogelajo .

**Comment by DaVukovic** [comment]
So probably more a adbLink problem?!

Good to close this issue then? As the logfile is obviously created fine.
