### ISSUE TITLE
Mac os X Mojave does not detect Pulse Eight libcec correctly

### ISSUE THREAD

**Issue by palhaland** [xbmc/xbmc#15073]
## Bug report
MacOS Mojave have broken the support for Pulse-Eight CEC
### Describe the bug
Here is a clear and concise description of what the problem is:
Pulse-Eight CEC is detected differently in Mojave than in previous versions of the and does therefore not work in Kodi. 
For more information about this issue, have a look here: https://github.com/plexinc/plex-media-player/issues/800

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

when I connect the pulse-eight libcec box to the PC I expect that it will be detected automatically

## Actual Behavior

It does not show up under the peripherals in the settings

## Possible Fix

update libcec to version 4.0.3 as done here: https://github.com/plexinc/plex-media-player/issues/800

### To Reproduce

1. connect pulse-eight cec adapter to the pc
2. go to Setting -> System -> Input -> Peripherals
3. the libcec device is not listed

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: MacOS Mojave 
 - Kodi version:
Leia RC2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
Thanks for the report, should be fixed in rc4
