### ISSUE TITLE
Alternative sorting of series with tmdb scraper

### ISSUE THREAD

**Issue by draekster** [xbmc/xbmc#15080]
## Bug report
With the scraper for The Movie Db (tmdb) it is not possible to select an alternative sorting for the default sorting.

In my specific case, I would like to switch from "Original Air Date" to "German Broadcast (TV)" for the series Case Closed.  However, this is currently not possible.

Here is a link to the page:

https://www.themoviedb.org/tv/30983-case-closed?language=en-EN

## Expected Behavior
For individual series or at least generally it should be possible to select an alternative sorting.

## Actual Behavior
Currently it is not possible to select an alternative sort order.

## Possible Fix
-

### To Reproduce
For series select the scraper for tmdb and try to change sort order.

### Debuglog
-

### Screenshots 
-

## Additional context or screenshots (if appropriate)
-

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 8.2.5
 - Kodi version: 17.6 Git:a9a7a20

**Comment by MartijnKaijser** [comment]
Please ask on the forum cause it's not a core code part.

**Comment by KarellenX** [comment]
Now supported.

See here... https://forum.kodi.tv/showthread.php?tid=338467&pid=2801494#pid2801494
