### ISSUE TITLE
Kodi not working with Alex on  nvidia shield. 

### ISSUE THREAD

**Issue by kasheimw** [xbmc/xbmc#15081]
### Describe the bug
Here is a clear and concise description of what the problem is:

Alexa doesn't work properly with kodi 18 Leia RC 3. It says it cannot do this command 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should be controlled with Alexa. Opening and closing the app. Finding movies tv shows and music. Scrolling up and down and selecting with voice commands.
https://www.nvidia.com/en-us/shield/

## Actual Behavior

It crashes the Kodi or nothing happens at all. 

## Possible Fix

Maybe take a look and see if the new Nvidia shield update is baked into the Kodi platform. 

### To Reproduce

1. Ask Alexa to find a movie on Kodi 
2.ask Alex to play a movie on Kodi
3.ask Alexa to open kodi

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android -Nvidia Shield TV 
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Android Oreo 8.1/Nvidia shield TV Upgrade 7.2
Kodi leia RC 3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
Hello,

please provide a debug log as requested or this issue will be closed within 3 days. From your bug report it is also not clear how Kodi core is involved in the problem. As far as I am aware, Alexa integration is not part of Kodi.

**Comment by MartijnKaijser** [comment]
Some fixes were done in v18.1
Regardless there no response so closing this
