### ISSUE TITLE
small kodi kodi.binary-addons packaging bug - cannot update to most recent tumbleweed

### ISSUE THREAD

**Issue by bassman56** [xbmc/xbmc#15086]
### Describe the bug
Here is a clear and concise description of what the problem is:

when trying to upgrade from tumbleweed 20181205 to latest tumbleweed I get the following
problem:
Problem: kodi.binary-addons-17.6-1.11.x86_64 requires libtag1 = 1.11.1, but
this requirement cannot be provided
   deleted providers: libtag1-1.11.1-4.1.x86_64
  Solution 2: keep obsolete libtag1-1.11.1-4.1.x86_64

problem: The packaging of  kodi.binary-addons-17.6-1.11.x86_64  was built  requiring "= 1.11.1" rather than ">= 1.11.1". So the uprade of tumbleweed providing a slightly newer library leads to a packaging conflict.

## Expected Behavior
a newer libtag1 library should not lead to a conflict.

## Possible Fix

Please change the dependency to libtag1 to require ">= 1.11.1" instead of "= 1.11.1"

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Rechi** [comment]
We don't do the packaging for openSUSE.

You have to report this issue to your distro maintainer.
