### ISSUE TITLE
Empty movie library (Error updating database MyVideos112 from version 110)

### ISSUE THREAD

**Issue by bartmans** [xbmc/xbmc#15089]
When I update from Kodi 17.6 to Kodi Leia 18 Alpha, Beta or Nightly (6th september) I lose my video database. The log (attached) stated that migration of the MyVideo110 tot MyVideo112 failed.

Using MariaDB on a Synology NAS and Kodi on Windows 10.

I then switched to another MariaDB, which didn't have the MyVideos110 dbase, but MyVideos109. The database migration worked.

I then switched back. Deleted the MyVideos110 dbase (after I made a copy). The database migration worked. Unfortunately all my saved states are in MyVideos110.

The new dbase 110 is created though.

I checked the Mysql user permissions, the kodi user has full rights and the password is okay.

From the log (full log attached) 
[kodi.log](https://github.com/xbmc/xbmc/files/2694024/kodi.log)

**Comment by DaVukovic** [comment]
`Starting Kodi (18.0-BETA2 Git:20180905-b69ac07180). Platform: Windows NT x86 64-bit`

Could you try a recent nightly please?

**Comment by bartmans** [comment]
10:05:50.913 T:9140  NOTICE: Starting Kodi (18.0-RC4 Git:20181217-4a52640cf3). Platform: Windows NT x86 64-bit

**Comment by KarellenX** [comment]
_When I update from Kodi 17.6 to Kodi Leia 18 Alpha, Beta or Nightly (6th september) I lose my video database. The log (attached) stated that migration of the MyVideo110 tot MyVideo112 failed._

Kodi v17.6 uses video database **MyVideos107.db**

If you are upgrading v17.6 then you cannot be using database MyVideos110. Most likely you have corrupted your installation with a previous upgrade.

**Comment by bartmans** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/2702298/kodi.log)
[kodi_stacktrace--20181221-104026.txt](https://github.com/xbmc/xbmc/files/2702299/kodi_stacktrace--20181221-104026.txt)

**Comment by bartmans** [comment]
Tried this on a number of devices: Windows 10, Windows 7, Odroid C2 and Raspberry PI. Always getting the same error when upgrading.

On my main devices I installed a fresh Kodi 18. That works perfectly with my MariaDB setup.

**Comment by pkerling** [comment]
You have to try #15092

**Comment by pkerling** [comment]
https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20181221-9b6270a1-PR15092-merge-x64.exe

**Comment by bartmans** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/2706055/kodi.log)
The warning is different but still an error:
16:04:28.303 T:8428  NOTICE: Attempting to update the database MyVideos113 from version 107 to 113
16:04:28.303 T:8428   DEBUG: Mysql Start transaction
16:04:28.312 T:8428   DEBUG: Mysql execute: ALTER TABLE settings RENAME TO settingsold
16:04:28.312 T:8428   ERROR: SQL: [MyVideos113] Undefined MySQL error: Code (1050)
                                            Query: ALTER TABLE settings RENAME TO settingsold
16:04:28.312 T:8428   ERROR: Exception updating database MyVideos113 from version 107 to 113
16:04:28.312 T:8428   ERROR: Error updating database MyVideos113 from version 107 to 113
16:04:28.313 T:8428   DEBUG: Mysql rollback transaction
16:04:28.322 T:8428  NOTICE: Old database found - updating from version 112 to 113
16:04:28.325 T:8428   ERROR: SQL: Can't create database for copy: 'MyVideos112' (1007)
16:04:28.325 T:8428   ERROR: Unable to copy old database MyVideos112 to new version MyVideos113

**Comment by Rechi** [comment]
It has been determined that [Banned_addons](https://kodi.wiki/view/Banned_addons) are present on your system. To receive assistance here, these banned items must be removed.
If a clean log is not submitted within 3 days, then the then this issue will be closed.

The Invalid label will be removed if you provide the clean log.

**Comment by pkerling** [comment]
@bartmans Please provide a clean log *when running the test build* (linked above).

**Comment by bartmans** [comment]
[kodi_rc4_merge.log](https://github.com/xbmc/xbmc/files/2707444/kodi_rc4_merge.log)
Clean logs from test build.

**Comment by pkerling** [comment]
It seems there are some problems with your database from the failed update attempts. Can you (after making a back-up) remove all `MyVideo` databases newer than 107?

**Comment by pkerling** [comment]
Wait are the new logs from an SQLite install?

**Comment by pkerling** [comment]
Ah no, sorry for the noise. But debugging is disabled for the rc4 log. Please remember to enable it the next time after removing the old dbs.

**Comment by bartmans** [comment]
[kodi_rc4_merge_updatefrom107.log](https://github.com/xbmc/xbmc/files/2708650/kodi_rc4_merge_updatefrom107.log)

okay, removed all db's > 107 and switched logging on.

Still the same error:
11:37:32.641 T:12168  NOTICE: Attempting to update the database MyVideos113 from version 107 to 113
11:37:32.642 T:12168   DEBUG: Mysql Start transaction
11:37:34.078 T:12168   DEBUG: Mysql execute: ALTER TABLE settings RENAME TO settingsold
11:37:34.078 T:12168   ERROR: SQL: [MyVideos113] The table does not exist
                                            Query: ALTER TABLE settings RENAME TO settingsold
11:37:34.078 T:12168   ERROR: Exception updating database MyVideos113 from version 107 to 113
11:37:34.078 T:12168   ERROR: Error updating database MyVideos113 from version 107 to 113
11:37:34.079 T:12168   DEBUG: Mysql rollback transaction![2018-12-25 11_36_30-greenshot]
(https://user-images.githubusercontent.com/5506518/50420876-f189aa80-0839-11e9-9fe8-e04239ff7d7a.png)

The table 'settings' is indeed missing from the dbase, so the error is correct.

**Comment by Rechi** [comment]
@bartmans you don't use a nightly you use a test build for a PR which isn't merged into master yet.

**Comment by bartmans** [comment]
@rechi. Yes as @pkerling asked to test this particular build.

**Comment by Rechi** [comment]
Ah yes, my fault only read the first comments where you were asked to use a recent nightly.

**Comment by pkerling** [comment]
@bartmans Still an artifact. If you have no backup, please rename `settingsold` (I assume that is there) back to `settings` in `MyVideos107` so the update can run.

**Comment by bartmans** [comment]
No, don't have the 'settings' table in the 107 dbase. I just installed a clean Kodi 18 so issue closed.

**Comment by pkerling** [comment]
Ah, that's a pity. Clearly something must have gone wrong at some intermediate stage during update testing. Theoretically, updates are performed in a transaction that is rolled back when any error is encountered, but this failsafe does not seem to have worked in your case.

Thanks for sticking with us through debugging so far.

**Comment by bartmans** [comment]
Well I install quite a few beta / alpha Kodis on some of my machines (not the Pi the kids / wife use :-), but they all use the same Mariadb. One of the reasons for reinstalling was to move the 'production' dbase to another NAS so in the future it is really separated: newest Kodi for me and stable for the rest. We thank you all for Kodi ... use it everyday!
