### ISSUE TITLE
2-3sec freeze when opening EPG or menu or pressing ESC while watching live TV

### ISSUE THREAD

**Issue by Qlink84** [xbmc/xbmc#15096]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Actual Behavior

posted problem here: https://github.com/kodi-pvr/pvr.vuplus/issues/144
referenced to this issue: https://github.com/xbmc/xbmc/issues/14828 but this issue got closed

problem still persists for me, even on latest nightly 18.2 ...

here's a full debug log: http://paste.kodi.tv/somuhocane.kodi

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: SHIELD Experience Upgrade 7.2
 - Kodi version: Kodi 18.2 nightly from 24-02-2019

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
>referenced to this issue: #14828 but this issue got closed

The issue you referenced is not related to your problem as you got that already as an answer in the issue you linked (instead of explaining your problem once again). 

Anyway, we can't do anything without a full debug log with debugging enabled. Please submit that. Otherwise this issue might get closed without looking at it.

**Comment by ksooo** [comment]
How many channels, how many days of epg data configured, which platform?

**Comment by Qlink84** [comment]
here's a full debug log: http://paste.kodi.tv/ezesihuqap.kodi
i've switched between some channels, pressed EPG button, pressed menu button, pressed fullscreen button during recording of log file. each of this button pushes creates a 2-3 sec freeze/delay/audio+video drop out.

i have 79 channels and 3 days of epg data configured. what do you mean witch which platform ?
i have a vu+ solo 4k with open atv...

**Comment by Qlink84** [comment]
seems like this is a android/nvidia shield specific problem. i've tried the same settings with actual RC4 release on my windows 10 laptop. no problems, everything smooth here

**Comment by Qlink84** [comment]
any progress concerning this issue ? problem still persists with todays nightly ... :(

**Comment by ksooo** [comment]
No progress.

**Comment by ksooo** [comment]
Using a shield myself, with  ~100 channels, 30 days of  EPG. Sometimes I also experience  a 2-3 secs delay until epg window gets filled, but never audio / video freeze or drop out. So, no real problem for me.

**Comment by ksooo** [comment]
Seems that you are not using  the default skin. Does it make a difference of you use stock Estuary?

**Comment by phunkyfish** [comment]
If you can step back through the nightlies and find on which one it changed that could help track down the issue.

**Comment by ksooo** [comment]
Could this  be related to recent massive changes in  the enigma 2 addon? Maybe downgrading it gives some new insights?

**Comment by phunkyfish** [comment]
Ah that’s right. The addons are not included in android kodi nightlies.

**Comment by TeHaX** [comment]
Maybe off topic but i want to mention that in Windows the pvr picture also freeze but for less than a second while audio have no drop out. This issue is present since all v18 builds.

**Comment by Qlink84** [comment]
problem still exists with latest leia 18.2 nightly
here's another full debuglog as it seems the full debug log i made few posts earlier is gone:

http://paste.kodi.tv/somuhocane.kodi

**Comment by ksooo** [comment]
A fix for this is high effort, as it is due to bad design of the guide window data model and as I consider the small "freeze" more a visual glitch than a bug it is unlikely that I will find the time to deal with this issue anytime soon, sorry.

**Comment by Qlink84** [comment]
hmm, you think the problem is EPG window related ?
but why does it just occur on my shield device ? and why does the freeze also happen when i press esc key during watching live tv. it also happens when i press tab key (fullscreen) when i'm in kodi main menu and live tv is running in the background...
another thing is i'm using 4 different kodi devices (2 different android cellphones, windows 10 laptop and windows 10 pc) and they all are working fine and smooth without any freezes, audio drops etc.

so i think it's a shield related problem, don't you think so ?

**Comment by ksooo** [comment]
> (at least this is my assumption)

I know that there can be a (short) delay not only on the Shield when opening/closing the guide window and I know why this can be happen. That's all I know. Everything else is pure guessing on my end.

**Comment by Qlink84** [comment]
problem solved by disabling refresh rate switching and setting refresh rate to 50hz - big thanks to peak3d for guiding me to the solution (https://github.com/kodi-pvr/pvr.vuplus/issues/144#issuecomment-468819220)
