### ISSUE TITLE
Kodi 18 RC3: Plot spoilers due to re-designed "Show plot for unwatched items" option

### ISSUE THREAD

**Issue by simpucker** [xbmc/xbmc#15107]
### Describe the bug
Here is a clear and concise description of what the problem is:

The following menu option has changed:

System\Media\Library\Videos --> "Library" section --> "Show plot for unwatched items"

In earlier versions, this used to be a simple on/off switch (toggle). Now, there is a sub menu. This results in the following: No matter which setting I use in the sub menu, I get plot spoilers in my Addon (even with every sub menu option inactive). In the National Hockey League Addon (NHL.tv), the selection menu now always shows the current team records (wins, losses, overtime losses). In earlier Kodi versions, the team records where hidden behind a "*Hidden to prevent spoilers*" tag. Please bear in mind that by knowing the current team record, the purpose of watching a recording of the game is rendered moot.

I downgraded to Kodi 17 and used the old on/off toggle with the "Show plot for unwatched items." As a result, the team record was hidden again (as it is supposed to be). Details can be found here:

https://forum.kodi.tv/showthread.php?tid=243756&pid=2801695#pid2801695

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Plot summary (such as details about a sports team's record) is hidden to prevent spoilers in video addon.

## Actual Behavior

Plot summary (such as details about a sports team's record) is displayed in video addon.

## Possible Fix

Adjust the "Show plot for unwatched items" option to what it was under Kodi 17.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Please bear in mind that by knowing the current team record, the purpose of watching a recording of the game is rendered moot. It kills the element of surprise.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.0-RC2 and 18.0-RC3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by simpucker** [comment]
Thank you for your prompt reply. Here is a screenshot of Kodi 17, showing how it is supposed to look:

![screenshot_20181221-153048](https://user-images.githubusercontent.com/46050443/50347592-55f4f300-0536-11e9-8b39-f41f5a5795b7.jpg)

This is how it looks in Kodi 18 RC2 and RC3:

![screenshot_20181221-153502](https://user-images.githubusercontent.com/46050443/50347597-5b523d80-0536-11e9-9b18-e72b33d6bc4c.jpg)

Hope this helps, many thanks again.

**Comment by simpucker** [comment]
Just for the record, I have taken both screenshots from Kodi 17 with different settings of the "Show plot for unwatched items" toggle (off in the 1st screenshot, on in the 2nd screenshot). With Kodi 18 RC2/RC3, which I had installed previously, it always looks like in the 2nd screenshot. Different configurations of the "Show plot for unwatched items" settings do not help in Kodi 18 RC2/RC3 (as opposed to Kodi 17, where the setting does affect the behavior).

It seems as if everything that is a video "Addon" is not affected by the "Show plot for unwatched items" setting in Kodi 18 RC2/RC3.

**Comment by DaVukovic** [comment]
I took a look and for me it looks like that:

![nhl1](https://user-images.githubusercontent.com/7235787/50348200-568e8900-0538-11e9-8ea7-deaaba84ec43.png)

There's also a setting, to hide the scores:
![nhl2](https://user-images.githubusercontent.com/7235787/50348201-568e8900-0538-11e9-81a2-f04baf25a632.png)

After choosing "on" for  "Hide scores" it looks like:
![nhl3](https://user-images.githubusercontent.com/7235787/50348202-57271f80-0538-11e9-8bae-54eddbd1ee37.png)

That won't change if you mark the item as watched, but that still has to be done at the add-on. As a suggestion I would probably think about adding conditions to:

https://github.com/eracknaphobia/plugin.video.nhlgcl/blob/master/resources/lib/nhl_tv.py#L139-L148

But that's something @eracknaphobia has to decide, as he is the add-on author. 

You already reported that at the forums a few hours ago. So I just be patient and see if he jumps in.

**Comment by eracknaphobia** [comment]
@simpucker looks like you downloaded directly from my github page as the record code has not be released to the kodi repo or my own repo. Can you confirm this is the case?

**Comment by HitcherUK** [comment]
Previously it was a blanket condition for any 'plot' but now it's specifically 'Movies' and 'Episodes' which is why you're not seeing now with v18. For addons it should be handled by the addon itself imo.
It's also worth noting that the description clearly stats 'library' -

> Show information for unwatched media in the video library or hide them if not selected to prevent spoilers. Available options are 'Movie plot', 'Episode plot' and 'Episode thumb'.

**Comment by HitcherUK** [comment]
Previously it was a blanket condition for any 'plot' but now it's specifically 'Movies' and 'Episodes' which is why you're not seeing now with v18. For addons it should be handled by the addon itself imo.
It's also worth noting that the description clearly stats 'library' -

> Show information for unwatched media in the video library or hide them if not selected to prevent spoilers. Available options are 'Movie plot', 'Episode plot' and 'Episode thumb'.

**Comment by HitcherUK** [comment]
Previously it was a blanket condition for any 'plot' but now it's specifically 'Movies' and 'Episodes' which is why you're not seeing now with v18. For addons it should be handled by the addon itself imo.
It's also worth noting that the description clearly stats 'library' -

> Show information for unwatched media in the video library or hide them if not selected to prevent spoilers. Available options are 'Movie plot', 'Episode plot' and 'Episode thumb'.

**Comment by HitcherUK** [comment]
Previously it was a blanket condition for any 'plot' but now it's specifically 'Movies' and 'Episodes' which is why you're not seeing now with v18. For addons it should be handled by the addon itself imo.
It's also worth noting that the description clearly stats 'library' -

> Show information for unwatched media in the video library or hide them if not selected to prevent spoilers. Available options are 'Movie plot', 'Episode plot' and 'Episode thumb'.
