### ISSUE TITLE
Kodi on WeTek Openelec Box crashes permanently

### ISSUE THREAD

**Issue by MobiletoGo** [xbmc/xbmc#15114]
V18.0 Leia RC2 on my good old wetek openelec box (alias WeTeK Play) running the upcoming LibreElec 9.0 is always crashing after a more or less random period of time, lasting not much longer than 2 days. Here the kodi.log:

[http://ix.io/1wqz](http://ix.io/1wqz)

Seems to be a memory issue in CLinuxTimezone::CLinuxTimezone()?!

Here is the output dmesg provides

[http://ix.io/1wqa](http://ix.io/1wqa)

After the crash always the libreelec ** safemode ** screen is shown. Hope anybody can help. Thanks in advance.

**Comment by DaVukovic** [comment]
This should be reported to the guy who provided the community build to you as it's not an official LibreELEC version.

Either upgrade to one of the official LibreELEC Wetek Play builds from here: http://archive.libreelec.tv/ or report it  it to the guy who did that build for you.

**Comment by MobiletoGo** [comment]
Hi DaVukovic , 

I'm the builder of this package myself. The only things I've changed compared to the core is 

- a new editor joe and in the options 
- I've disabled NANO_EDITOR,
- I've my own Welcome Message (for e.g. the SSH Server), 
- a new root password.
- and KODI_AIRPLAY_SUPPORT, KODI_AIRTUNES_SUPPORT, OPENVPN_SUPPORT as well as CEC_SUPPORT is disabled.

That's it - nothing that should affect the LinuxTimzone?!

In case you have a glance to the referenced constructor method you'll see a @todo STRING_CLEANUP as well as the last free(line) in the end doesn't checks if (line) is ensured. All remaining stuff seams to work fine.

So far - I wish a happy X-mas and a happy new year.

**Comment by DaVukovic** [comment]
Talked to a Team LibreELEC member and this seems to be a kernel problem and probably nothing LE is able to change. 

You could try using a cron job restarting Kodi every now and then. 

Anyway you should submit that bug at LE and not at Kodi. Could be that you will get a "nothing we can do"-answer as well unfortunately.

**Comment by MobiletoGo** [comment]
However, thanks for all you efforts so far. 

Currently I've a time scheduled wlan smart plug doing this nasty job. But it can't be a solution for a real linux enthusiast. ;)

I'll talk to the libreelec members to get the issue fixed - if possible.
