### ISSUE TITLE
Enigma2 client doesnt work with OpenPLi 0.7-rc 

### ISSUE THREAD

**Issue by Dinth** [xbmc/xbmc#15112]
### Describe the bug
Since i updated my sat box to OpenPLi 0.7-rc (build 20181220) yesterday it's not possible to enable Enigma2 client in Kodi. Whenever i restart Kodi or manually go to addons list and disable/re-enable Enigma2 addon im getting "Add-on couldn't be loaded. An unknown error has occured" error. 

## Expected Behavior

Addon should start fetching current channel list.

## Actual Behavior

An error "Add-on couldn't be loaded. An unknown error has occured" appears. 

### Debuglog

```
20:06:47.836 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Open - VU+ Addon Configuration options
20:06:47.836 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Open - Hostname: '192.168.1.175'
20:06:47.836 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Open - WebPort: '80'
20:06:47.836 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Open - StreamPort: '8001'
20:06:47.836 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Open Use HTTPS: 'false'
20:06:47.989 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - DeviceInfo
20:06:47.989 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - E2EnigmaVersion: 2018-12-19-rc
20:06:47.989 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - E2ImageVersion: 7.0-rc
20:06:47.989 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - E2DistroVersion: openpli
20:06:47.989 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - E2WebIfVersion: OWIF 1.3.5
20:06:47.989 T:139678803232512  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - E2DeviceName: 1
20:06:48.473 T:139678803232512   ERROR: ADDON: Dll Enigma2 Client - Client returned bad status (1) from Create and is not usable
20:06:49.959 T:139678803232512   ERROR: UpdateAddons: Failed to create add-on Enigma2 Client, status = 1

```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 8.90.009 Generic x86_64
 - Kodi version: Kodi 18.0-RC2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
This is not a kodi issue. Please file an issue for the vuplus pvr addon: https://github.com/kodi-pvr/pvr.vuplus/issues
