### ISSUE TITLE
Controller not recognized

### ISSUE THREAD

**Issue by knuxyl** [xbmc/xbmc#15127]
8Bitdo N30 Pro 2 Bluetooth controller not recognized

 - Operating system: Xubuntu 18.04.1 x86_64
 - Kodi version: 17.6

This controller has a X-Input mode and a D-Input mode, and neither can be recognized by Kodi. Using either and trying to map the buttons does nothing. Controller works fine for all other software I have used. When connected while Kodi is running, a new controller pop up does not come up. Not sure what logs I should share or where they are. I know previous versions of Kodi had problems with the older version of this controller (NES 30), and now it seems like the new Kodi has problems with new controller.

1. Connected bluetooth from PC to controller
2. Open Kodi and go to Settings
3. Try to map the controller input

Link to controller website
http://www.8bitdo.com/n30pro-2/

**Comment by MartijnKaijser** [comment]
We do not support v17 anymore. Please try v18 and report back if there's still a problem. Maybe you can ask on the forum
