### ISSUE TITLE
4 - 18s GUI freeze when music track changes in Leia RC3.

### ISSUE THREAD

**Issue by MarkCallow** [xbmc/xbmc#15129]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing music, the GUI freezes when the track changes during party mode or playing any other playlist. This is most easy observed by watching the OSD with the track progress bar and song info visible. As a track finishes the blue bar never quite gets to the end and although the audio for the next track starts and the OSD does not show the new track info for several seconds. The shortest freeze I've seen is 4 seconds in, the longest 18 seconds in as shown by the progress bar when the new track info is finally displayed.

If you happen to be trying to do anything in the GUI, e.g navigating the top level menu, you will notice that everything freezes when the track changes.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect the new track info to be displayed immediately in the OSD and I expect the GUI to never freeze.

## Actual Behavior

There is a lengthy freeze in the GUI response during a music track change.

### To Reproduce

1.  Run party mode.
2. Open the on-screen music display.
3. Wait for the track to change and observe the delay
OR
4. Navigate to somewhere else in the GUI, e.g. settings, wait for the track to change and immediately try to select something or change a selection in the GUI.

### Debuglog

During the last song change shown in this debug log there was a 10 second freeze.

https://paste.kodi.tv/xusuvofoxi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

This started happening immediately I updated to Leia v18 RC3 from v17.6. In the log right now you can see that I am running a modified Estuary skin, however the problem started immediately after the update when I was still running the standard Estuary skin. So the modified skin is unrelated.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 10.14.2 / macOS Mojave
 - Kodi version: 18 RC 3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
`21:51:09.634 T:4478539200  NOTICE: Disabled debug logging due to GUI setting. Level 0.`

Not a debuglog. The invalid label will be removed once a new log with debugging enabled is submitted

**Comment by MarkCallow** [comment]
I have uploaded a log with debug logging turned on and have edited the link in the bug description. Please remove the invalid label.

**Comment by DaVukovic** [comment]
Will try later

**Comment by DaveTBlake** [comment]
Unable to reproduce on Win10 or using LibreElec on RPi

**Comment by DaveTBlake** [comment]
Noticed you are using a modified skin, please use default Estuary and see if issue persists. So yes do a clean install and paste new debug log if it does.

**Comment by MarkCallow** [comment]
I have not tried a 100% clean installation. I use MySQL so if I use a new profile I'll have to copy back at least part of it in order to have some music to test with. And it's not MySQL. This is the 3rd major version of Kodi with which I've used the same MySQL server and never had an issue like this before.

I had the problem immediately I updated to Leia before I installed the modified skin. Because of that and because switching skins loses all the skin settings, I did not bother to switch back before capturing the debug log. If I can find some time this weekend, I'll try but I feel it is a waste of time.

**Comment by pkerling** [comment]
> I use MySQL so if I use a new profile I'll have to copy back at least part of the old in order to have some music to test with.

Just test with default SQLite (that will then also rule out MySQL automatically)

**Comment by DaveTBlake** [comment]
From the db access times in the log I don't think that MySQL is the issue here. Although ruling it out totally would be useful, just copying the advancedsettings.xml into a clean install so it can use the existing db would be a workwhile interim step.

@MarkCallow since others can't reproduce this issue it means that you will need to put in the effort to provide us with edivence to work with.

**Comment by DaVukovic** [comment]
I can't reproduce that as well. Also installed the pkscout Estuary Mod to see if that changes something. But everything is instant. Created a partymode playlist and simply let it play. There's absolutely no freeze.

Not using a MySQL db, tbh

**Comment by MarkCallow** [comment]
@DaVukovic are you using macOS? If so, which version.

Thanks to all for your time looking at this so far. Hopefully I can make time to try on a clean install this weekend.

Could the number of tracks affect this? I have upwards of 6000 in my library.

**Comment by DaVukovic** [comment]
My initial test was on Ubuntu, but as you asked for....I tested now with my iMac late 2009 (which still is capable running Sierra 10.12.6) and a freshly created music library. I have way over 10000 tracks in my library and the party mode playlist I created has 2370 songs in it. 

I still can't reproduce your issue at all. Even not with such an oldish hardware ;)

**Comment by enen92** [comment]
Can't reproduce as well on OSX 10.14.2 with latest Kodi master. Can you try to disable the visualization (if enabled) or try to reproduce without using mysql?

**Comment by MarkCallow** [comment]
I reverted to a clean install and scanned my library into the default SQLite. This problem then did not appear.

I again reverted to a clean install and this time copied `advancedsettings.xml` from my saved profile into the clean install profile. With this MySQL on an NAS is used for both the video & music libraries. With this setup I experience the freeze but the time range is greatly reduced: min 1 second, max 4 seconds. Obviously at 1 second the freeze is not noticeable.

I've uploaded a new debug log to https://paste.kodi.tv/penilafovu.

In this I started Party Mode then entered full screen with the Info display. I clicked near the end of the progress bar to save time and waited for the track to finish & the audio of the next one to start playing. When the new track started I pressed Pause. I repeated these steps a few times. Some of the times the change was quick and playback of the new track was paused. In the last one before I captured & uploaded the log it was 4 seconds before the new track info was displayed. I pressed Pause twice after the audio started playing. Nothing happened on the first press. The second one was after the new track info was displayed and playback was paused. I pressed again to restart playback.

I will continue to try and discover which part of my profile causes the huge delays and will report back.

**Comment by MarkCallow** [comment]
I believe that something is acquiring a lock during automatic track change that blocks the GUI and the problems I noted in issue #15130 made the track change take time and thus made the locking v. obvious. In operation with the default SQLite track changes are fast enough that the lock is not apparent.

The problems #15130 have been largely resolved. In my next few days of use with the fixed version, I will see whether a freeze can still be felt while using the GUI.

**Comment by DaveTBlake** [comment]
I think it very likely that the GUI freeze on track change you experienced is related to the MySQL optimiser weakness that your other issue https://github.com/xbmc/xbmc/issues/15130 revealed. The artistview query that caused party mode start up to crawl, is also called on track change and will be causing a full scan of the artist table.

This means that will also be fixed by https://github.com/xbmc/xbmc/pull/15284

The GUI and fetching the data are being done on the same thread, so the GUI waits until it has the data to display.

**Comment by MarkCallow** [comment]
Yes, the speed up of #15284 has made the freeze negligible so I will close this. However data fetches on a UI thread are prone to this type of freeze whenever there is a delay. For v19, please consider fetching on a separate thread.

**Comment by DaveTBlake** [comment]
Someone else reported party mode switch song GUI delay (https://forum.kodi.tv/showthread.php?tid=340758) that I could reproduce. GUI freeze was possible in Kodi going back at least to v16 if the party mode was slow to fetch a new song for any reason e.g. MySQL (in your case) or just complex smart playlist rules on a huge library. 

Anyway https://github.com/xbmc/xbmc/pull/15557 fixes the GUI delay, I hope it will get into 18.2
