### ISSUE TITLE
[Systeminfo/Storage] mount points (df -h output) overwrite information fields

### ISSUE THREAD

**Issue by 5schatten** [xbmc/xbmc#15134]
### Describe the bug
Basically have a look at the screenshot it's self explanatory. Mount points screw up the information fields.

## Expected Behavior
It should list the mounts points, maybe scrollable

## Actual Behavior
Once more mount points are listed than rows are available it overites the version & compilation information fields.

### To Reproduce
Get a lot of mount points e.g. nfs shares for several rom folders.
https://pastebin.com/cm9jLryM

### Screenshots 
https://i.imgur.com/uANtqwL.jpg

### Your Environment
Used Operating system:
LE 9 dev builds & Kodi 18 RC4

**Comment by fuzzard** [comment]
Believe this has been fixed in (at least) v19 alpha1. Team members are unable to replicate behaviour on linux and osx.
