### ISSUE TITLE
Smart Playlist for any video

### ISSUE THREAD

**Issue by gsantner** [xbmc/xbmc#15131]
### Describe the bug
Kodi only allows to specify one type for Smart playlists, like:
![grafik](https://user-images.githubusercontent.com/6735650/50423566-1e948800-084f-11e9-8f28-4ed40e640322.png)

Unfortunately there is no type option that matches for both, movies and series-episodes.
It would be really great to have such an option, for example named `videos`.
Very simple case: Want to just watch Anime. With looking at anime only, it's about 40% of my library being movies and 60% episodes. With a `video` option I don't need to choose anymore if I take one of the 40% or 60% but any of both. 
(My personal target in the end here, is to make a `order=random` playlist which just starts playback with some anime, whatever type it is. )

Notice: You can replace `Anime` with something else, just thought thats the best example overall.

[Current options](https://kodi.wiki/view/Smart_playlists#Types)
![grafik](https://user-images.githubusercontent.com/6735650/50423643-f5c0c280-084f-11e9-93d9-64d0be5327a2.png)

## Expected Behavior
The goal is that a user is able to queue videos, independent if it's series-episodes or movies. 

## Actual Behavior
No such type available

## Possible Fix
* Either add an additional `type` option that holds library contents from all videos. Just like `mixed` is for `songs+musicvideos`.
* Or allow to specify multiple types, like `types="episodes,movies"`

The goal is that a user is able to queue videos, independent if it's series-episodes or movies, and which solution is taken.

### Your Environment
 - [x] Raspberri-Pi
 - Kodi version: 17.1, OSMC

**Comment by DaVukovic** [comment]
A missing feature is not a bug. This section at Github is for bug reports. For feature requests please use the specific subforum at forum.kodi.tv or submit a PR which shows the code to get that done. 

Thanks
