### ISSUE TITLE
Kodi 18 RC3 Resolution/refresh rate Whitelist is only showing 1920x1080/60hz

### ISSUE THREAD

**Issue by Ersh0w** [xbmc/xbmc#15135]
### Describe the bug
Here is a clear and concise description of what the problem is:

Problem just like in issue https://github.com/xbmc/xbmc/issues/14696:
Refresh rate change does not work in Kodi 18 RC3 as whitelist only includes one resolution/refresh rate: 1920x1080/60hz. However, my TV (Xiaomi 4a 65") supports all common resolutions.

Kodi 17 works fine and automatically changes screen to 1920x1080/24hz for movies. I am running Kodi on a tv box X96MAX (tried stock firmware; beelink gt1 mini firmware; atv from superceleron; XTMOD from Xannytech). Android settings includes all resolutions. Tried 5 different hdmi cables (even optic hdmi). 
Also tried connect tv box to monitor Samsung C32JG50 - android settings includes all resolutions that supported by monitor; Kodi - again only 1920x1080/60hz.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Whitelist allows you to enable/disable all of your TV’s supported resolutions.

## Actual Behavior

Whitelist only includes one resolution/refresh rate: 1920x1080/60hz. However, my TV supports many other combinations.

## Possible Fix

Enable manually editing whitelist

### To Reproduce

1. Install latest Kodi 18 RC3
2. Go to whitelist settings for screen resolution and refresh rate
3. Try to enable 1920x1080/24hz

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/xiwijagezo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

![screenshot_20181226-194201](https://user-images.githubusercontent.com/46130789/50454584-9222bc00-0959-11e9-9a61-62384c8fd432.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

![screenshot_20181226-193511](https://user-images.githubusercontent.com/46130789/50454590-9bac2400-0959-11e9-97c2-e96ecb45c8d9.png)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 8.1.0 (4.9.76 (gcc version 6.3.1 20170109 (Linaro GCC 6.3-2017.02)) yxt000@yxt000-S2600JF #3
 - Kodi version: 18 RC3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by mo123** [comment]
Xiaomi tv's and tv boxes don't support auto frame-rate switching, so you will only be able to use 1080p@60hz. The same for the generic Amlogic tv box you mention. Amlogic's Android Oreo SDK doesn't support auto frame-rate switching in Kodi even if the hardware is more than capable of doing it, they didn't implement Android's Display API correctly. Kodi 18 also dropped support for Amlogic's propriety AMLCodec and moved to MediaCodec that is supposed to be supported on every Android device now.
You only solution is to use an old Kodi 17 or SPMC based on Kodi 16 if you want to use auto frame-rate switching.
