### ISSUE TITLE
Leia: (Partial) Video Playback issue on FTV 4K Stick

### ISSUE THREAD

**Issue by godoll** [xbmc/xbmc#15143]
Example: Copy of my "Kraftwerk - Minimum-Maximum" DVDs as ISOs on my local NAS (Cubietruck with Armbian)
Leia Beta/RCs and actually 20181223

While the playback (smb) of the isos on my 1. Gen FireTV Stick and Fire TV2 works without any issues - even with WiFI only, the video and sound is out of sync on my newly acquired FireTV Stick 4k. (video lagging behind the audio)
The AFTVS4k is connected via a GigE built-in into an Ugreen  4-Port USB3.0 Hub to the network.

However I think it's not related to a network issue as the playback of e.g. an UHD/4k mkv file from the NAS is perfectly done by the FTV4KS.

## Expected Behavior
smooth playback

## Actual Behavior
playback stutters

## Possible Fix
tried to disable HW accelerating with any success

### Debuglog

The debuglog of the FTVS, FTV2 and problematic FTVS4k can be found here:

[kodi-aftvs.log](https://github.com/xbmc/xbmc/files/2712385/kodi-aftvs.log)
[kodi-aftv2.log](https://github.com/xbmc/xbmc/files/2712389/kodi-aftv2.log)
[kodi-aftvs4k.log](https://github.com/xbmc/xbmc/files/2712391/kodi-aftvs4k.log)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help: as I think I'm not the only person having this issue:
https://forum.kodi.tv/showthread.php?tid=338521
https://forum.kodi.tv/showthread.php?tid=338009)

### Your Environment
Used Operating system:

 - [X] Android

 - Operating system version/name:
 - Kodi version: 18.0.X

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by godoll** [comment]
PS: another minor issue. I think even though the DTS 5.1 audio stream was selected / highlighted as the default playback audio stream in the DVD menu, the playback started with 2.0 PCM stream.

**Comment by godoll** [comment]
PS: comparing your FTVS4k log above excerpt with the one from the FTV2 the only difference I see is the weight in th last entry.
```
10:26:54.448 T:367458365680   DEBUG: Trying to find exact refresh rate
10:26:54.448 T:367458365680   DEBUG: No exact whitelisted resolution matched, trying double refresh rate
10:26:54.448 T:367458365680   DEBUG: No double refresh rate whitelisted resolution matched, trying current resolution
10:26:54.448 T:367458365680   DEBUG: No larger whitelisted resolution matched, trying current resolution with double refreshrate
10:26:54.448 T:367458365680   DEBUG: No whitelisted resolution matched
10:26:54.448 T:367458365680  NOTICE: Display resolution ADJUST : 1920x1080 @ 59.939999 - Full Screen (16) (weight: 0.000)
```

**Comment by fritsch** [comment]
IDs change ... this is the real issue. A weight of 0.0 makes no sense for 25 fps on 59.94 hz. I think refreshrate ids change every time adjusting and afterwards it just switches to "bogus.

Best: disable adjust refreshrate entirely.

**Comment by MartijnKaijser** [comment]
@fritsch, remember I linked to several commits in spmc/mrmc that handle that stuff?

**Comment by fritsch** [comment]
Yes. That might be it. Something for @peak3d after his internet comes back perhaps.

**Comment by godoll** [comment]
as some (most?) of my 'plain' video files play propperly I thought the issue my be related to the 'embedded' DVD format and thus I extracted the VTSes and (binary) concatenated them to an mpg file. (1-4 and just 0 'menu' & 1)
However the playback of those videos stutter as well ...

**Comment by godoll** [comment]
Playback via VLC of the video on same device is O.K.

**Comment by fritsch** [comment]
Which does not help us in any way. But please go ahead and use vlc for the time being.

**Comment by godoll** [comment]
Thx peak3d, but as to DaVukovic request a few weeks ago I alreeady performed some test, but without any success: https://github.com/xbmc/xbmc/issues/15143#issuecomment-450351568

When you say "Please select Auto in android GUI HDMI settngs" who would I have to translate it to the setting I have to change on a FTVS 4K?

BTW: I downgraded back to 17.6 without neither changing **any FTVS4k** nor any kodi settings (even running the risk having a 18.0 config read by 17.6) and voila, the movies play without stuttering.
[kodi17.6-AFTVS4k.log](https://github.com/xbmc/xbmc/files/2772302/kodi17.6-AFTVS4k.log)
I don't want to be offensive, but me as an end user I'd say: "You broke, you own it" ;-)

**Comment by godoll** [comment]
OK, I think I found the section in the FTVSs config which you ment to switch to auto. However it made it worse as I could start the playback of the "DVD", but starting the movie in DVD menu didn't worked and when I went back Kodi froze and I had to kill it from the FTVS app menu.
[kodi.old.log](https://github.com/xbmc/xbmc/files/2772645/kodi.old.log)
I started Kodi a second time with same behaviour for the "DVD", but I could start the playback of extracted VTSes, but it was still stuttering.
[kodi.log](https://github.com/xbmc/xbmc/files/2772652/kodi.log)

**Comment by sleeksorrow** [comment]
I started evaluating Kodi 18 RC 5.2 now, too, and find the very same issue on my [Fire TV 2nd gen](https://en.wikipedia.org/wiki/Amazon_Fire_TV#Second_generation). A/V is out of sync by quite some seconds. When I disable both hardware acceleration options (mediacodec and mediacodec surface), the sync is back again, but the video is played with very low fps (like about 10 I feel). I can see no difference in behavior with avi, mp4 and mkv containers, no difference in video resolutions from 480p to 1080p, or anything else. Every video is affected.

I usually use the 64-bit arm v8 version, but for testing I also tried the 32-bit arm v7 version without any difference.

Tried to downgrade to RC1 to see when this problem first occurs, but the system refuses to easily downgrade. At the moment I don't have enough spare time to backup settings, remove and reinstall an older version. If you think this might bring some insight, please let me know then I'll do that.

**Comment by godoll** [comment]
(Think we have another report about the issue? https://github.com/xbmc/xbmc/issues/15285)

> find the very same issue on my Fire TV 2nd gen

That's odd, as within my zoo [1] of Kodis only the combination of FTVS4k and 18.0 has that issue.
18.0 on all my other even much weaker platforms [1] plays smoothly and even 17.6 plays smoothly on the FTVS4k.
[1] Raspi1 with OpenElec, OE on an Zotac CI320 (or win10), W10 on other systems, FVTS 1. gen, FTV2
(obviously 4k material my have issues on some of the platforms though ;)

**Comment by MartijnKaijser** [comment]
Please install latest v18 nightly version and confirm if it's fixed

**Comment by godoll** [comment]
Hoi Martijn, tested kodi-20190206-7001c652-master-arm*.apk on Amazon FTV2, FTV Stick 4k and a Samsung Galaxy Tab A6 device: all play the video smoothly, now. Perfect! Thx a lot and greetings to the team.

**Comment by godoll** [comment]
Sry, I have to reopen:

o) movie starts without stuttering, now, which is good.
i) (minor issue) in my example though the DTS5.1 audio stream is selected (as the default) the movie is played with the 2.0 PCM stream
ii) (main issue) video / playback stops (or betten freezes) after a few minutes (still pictures, no sound). I think it happens when it is getting from one chapter to next next (1 -> 2 in this case). I can still move to next / previous chapters an d see this reflected in the icons on top of the screen, but playback does not resume. My AVR signals the HDMI (audio) port as still being busy. When pressing the stop button on the remote the (silent) audio signal (though no sound) seems to stop as the AVR's indicator changes.
(Though still picture).
I can't control Kodi any longer with the (IR) remote, but with Kore. I can still e.g. get to Home or select files from the video menu, however neither any movie or audio file will be started.
It's also not possible to end Kodi via Kore's / Yatse's end/shgutdown/reboot function and I have to kill Kodi via Amazon's App mgmt function.

Here's an actual log file of the situation.
[kodi.log](https://github.com/xbmc/xbmc/files/2848025/kodi.log)

**Comment by DaVukovic** [comment]
Just for the note as you are currently not using `kodi-20190206-7001c652` anymore and are using current Kodi master...did you noticed the same behaviour with `kodi-20190206-7001c652` as well?

In case you didn't noticed: 18.1-RC1 Git:20190207-fee3771

that's the version you are currently using and which is shown in your log.

**Comment by godoll** [comment]
Hi DaVukovic, just to be safe I downgraded to kodi-20190206-7001c652-master and unfortunately, yes: the issue is here already as well. (let me know if you need a log for that version as well)
However it seems not to be related by the transition between chapters. The movie went to chapter two already for a few minutes (better a couple of seconds) before the playback stopped and the picture froze.

![20190209_183045](https://user-images.githubusercontent.com/14141675/52524170-7faada80-2c9a-11e9-8cd4-dc6aef98a396.jpg) (The video played for only 2 min and a few sec before it stopped).

Another odd thing: Even I killed the Kodi process I had to restart the AFTV 4k stick before I culd start the main moving again. Before that I could go still the DVD main menu and select "play movie", but it froze immediately just showing the DVD Main Menu

**Comment by peak3d** [comment]
Pls. deactivate Refreshrate switching and tell if the issue still appears, thx.

**Comment by godoll** [comment]
Set Refreshrate from Always to Start/Stop: played for ~ 4 min, I switched audio from 2.0 to DTS5.1 and froze shortly after that.

Rebooted AfTV 4k stick and set Refreshrate to Off.
Went down selected Stereo on DVD main menu and altered it back to DTS starting movie after that.
Movie started in stereo, I switched to DTS while playing. Picture frozes again later and after that a sec later sound, too. Time's still counting on "progress bar". I stopped video, but progress bar is still visible, but time stopped ticking. Can't go back to Kodi main menu nor close it normally.

Rebooted device starting Kodi/Movie leaving at 2.0. At ~ 3:30 video froze and sound a few seconds later, too.
Rebooted device ...

**Comment by godoll** [comment]
No relief with kodi-20190224-7e853c72-master-armeabi-v7a.apk, yet.
I can select a specific track from the DVD menu, but playback stops after a few minutes and picture freezes. Can't stop Kodi. Even when I kill Kodi via FireTV Settings -> App -> Kodi -> force stop
it leaves the stick in an odd mode as the playback of Amazon movies or Netfix isn't working properly any longer.
Rebooting the device mitigates the issue

**Comment by peak3d** [comment]
@godoll pls. try this build regardng the "need reboot" issue:

https://mirrors.kodi.tv/test-builds/android/arm/kodi-20190225-b81ab0fa-eos-armeabi-v7a.apk

**Comment by godoll** [comment]
@peak3d Thx Markus, but sry no - playback still freezes.
[kodi.log](https://github.com/xbmc/xbmc/files/2907332/kodi.log)

**Comment by peak3d** [comment]
This one has more logs, can you pls try again and provide log ? Thx!

https://jenkins.kodi.tv/job/Android-ARM/13062/

**Comment by peak3d** [comment]
@godoll , sorry for beeing impatient, plan is to merge before RC2

**Comment by godoll** [comment]
@peak3d, np, but sry, that version froze more or less immideatly after starting the DVD's track
[kodi.log](https://github.com/xbmc/xbmc/files/2909555/kodi.log)

**Comment by peak3d** [comment]
@godoll I'll ned a log where the stream at least starts. The log you provided stopps immediately when opening the decoder, so it seems the device is already in broken decoder state.

Pls. restart the device and try to make a log file similiar to yesterday's one, thx

**Comment by godoll** [comment]
Ah, yes, sry - accidentically overwrote the first log, but didn't reboot the FTV before making a new one.
[kodi.log](https://github.com/xbmc/xbmc/files/2910044/kodi.log)

**Comment by peak3d** [comment]
@godoll oh no, I'm so sorry, I linked the wrong PR yesterday (had 3 open, and mixed something)
https://jenkins.kodi.tv/job/Android-ARM/13063/ is the correct one.

**Comment by godoll** [comment]
np, here it is - froze quite soon: 
[kodi.log](https://github.com/xbmc/xbmc/files/2910596/kodi.log)

**Comment by peak3d** [comment]
@godoll this is a first try: https://jenkins.kodi.tv/job/Android-ARM/13074/

Can you pls. enable Video Component debugging? Thx

**Comment by godoll** [comment]
ran a bit longer this time, however it also froze finally. (Looking at the audio stream I think it always said 2.0 PCM when I had a look though I tried to switch to the DTS one.)
[kodi.log](https://github.com/xbmc/xbmc/files/2911105/kodi.log)

**Comment by peak3d** [comment]
@godoll  The root issue is from what I read not video, its audio. what we are currently trying to reach is that audio issue does not lead to the broken video decoder. If this video decoder issue is solved, we can look for the audio root cause.

I pushed a new commit https://github.com/xbmc/xbmc/pull/15622 but build system is busy right now.

**Comment by peak3d** [comment]
@godoll : https://jenkins.kodi.tv/job/Android-ARM/13076/

**Comment by godoll** [comment]
another early freeze
[kodi.log](https://github.com/xbmc/xbmc/files/2911773/kodi.log)

**Comment by peak3d** [comment]
@godoll  Seems that video decoder gets in some strange state if it gets no data for some seconds (which is cause by audio)

1.) New build run here: https://jenkins.kodi.tv/job/Android-ARM/13079/
2.) what do you exactly do to trigger the issue? Do you switch audio track? If so, how?

**Comment by godoll** [comment]
re i) [kodi.log](https://github.com/xbmc/xbmc/files/2912303/kodi.log)
re ii) nothing special this time, just started playback and waited a few mins. Usually the video plaback freezes a few seconds before the sound stops. I can still push to next track back or forth, which is also shown, but usually Kodi freezes completely when I try to exit.

Though if you'll be still busy you'll have to wait for tomorrow for the next logs ;-)

And btw: can the crash been used to exploid the 4k stick?! ;-))

**Comment by peak3d** [comment]
@godoll what I can say is that I have the same device, but do not have such issues.
No idea, really, why the OMX player stalls, could be of various reasons.

Maybe logcat tells something, if possible pls. provide one tomorrow.
To keep it small adb logcat -c before playback pls.

**Comment by peak3d** [comment]
@godoll can you make the dvd iso somehow accessible for me? You can use my mail of this git account.

**Comment by peak3d** [comment]
@godoll next build is here: https://jenkins.kodi.tv/job/Android-ARM/13087/

**Comment by godoll** [comment]
@peak3d as to our interim private communication and are the results of your last build:
i) Playback on "Main" 4k fTV stick froze soon: [kodi-main.log](https://github.com/xbmc/xbmc/files/2914142/kodi-main.log)
ii) Playback on "2nd" 4k stick played much longer (till into 2nd track IMO, wasn't in the room at that time), but stalled in the end: [kodi-2nd.log](https://github.com/xbmc/xbmc/files/2914152/kodi-2nd.log)
iii) and I made a test with an "extrcated" video file of the DVD (image) on the "Main" stick, which froze very soon after the playback started. Think I'm gonna upload you a snippet of that for further testing. 
[kodi.log](https://github.com/xbmc/xbmc/files/2914175/kodi.log)

**Comment by sleeksorrow** [comment]
I want to thank you both for your time and dedication to dive into this. I for myself don't have the time to provide so many logs and make tests as you, so I appreciate your work a lot.

I'm also still affected from this on my FTV 4K 2nd Gen, can reproduce issues with every movie I tried from my NAS. A/V Sync is way off (just can guess it must be about 10sec at least), sometimes video is running too fast and freezing now and then. It only works nearly stable when I deactivate both hw accel settings in player settings. With Kodi 18.1 at the moment it plays smooth without hw accel, but obviously that's just a workaround, can break anytime, and I can only test up to 1080p.
