### ISSUE TITLE
Some DVD Folder (video_ts.ifo) movies won't play from Search tool results

### ISSUE THREAD

**Issue by GaryPSmith** [xbmc/xbmc#15147]
https://paste.kodi.tv/ahuzucagiq
LibreELEC v8.95.1 Beta, fresh install from 12/23/2018 / Kodi 18 RC3 (Leia)
ZOTAC ZBOX​, Intel Core 13-3120M CPU @ 2.50 GHz, GPU: Mesa DRI Intel Ivybridge Mobil

What seems to work well:
​1. From the files folder, I can browse to the movies source directory and launch the video_ts.ifo file for a movie which brings up the DVD menu, where I can play the movie.
2. From the Movies Library, I can sort the movies by Title, find the Movie in the List Format, click the OK button on my remote, will bring up the DVD menu from where I can play the movie.
3. Any other movie format (e.g. .mkv), I can do the above and also use the Search tool to find a movie by title, click on its Poster Art in the Infowall, and it will play.
4. Some DVD folders (e.g. movie name folder->video_ts folder->video_ts files including .ifo), will also play correctly from the Search tool result list.

What is not working:
For some DVD folders containing video_ts.ifo files, when attempting to play the movie from the Search tool results list, the DVD menu never appears with only the "spinning wheel" icon presented on the screen.  The system is not hung up as I can exit out and do other things, but when trying to play this menu, it is "stuck" in a wait state.

The movie I am trying to play is the 1964 version of Mary Poppins.  Some movies ripped to this format play, others don't, and I am not able to pinpoint any differences between those that work and those that don't.

**Comment by DaVukovic** [comment]
Thanks for your report. 

Just to be sure...the Mary Poppins file you try to play works fine if you are not using the search tool? 

I want to rule out a file issue so it would be nice if you are able to submit another log which shows that this file is playing fine (using one the other methods you mentioned to start it) and then additionally show that it doesn't play while using the search tool

In any case, I (personally) do not recommend to store DVDs in their open structure. Kodi is able to handle DVDs if their structure has been put into an ISO file. Not sure how you rip your movies, but some tools are able to do exactly that by ripping. That's more a topic for the forums, so please take this as a hint only ;)

Thanks in advance

**Comment by GaryPSmith** [comment]
Hi DaVukovic,

https://paste.kodi.tv/fewaraheri

This log contains four actions.
1. Select the movie from the File Manager directory: successfully brings up DVD Menu, click the Play option and let the movie stream for about 30 seconds.
2. Select the movie from the Titles sorted A to Z list: successfully brings up the DVD Menu, click the Play option and let the movie stream for about 30 seconds.
3. Searched for "poppins" which displayed the poster, clicked on the poster: failed to present the DVD menu.
4. Selected the Genres->Family tag, scrolled down and found Mary Poppins, and selected it: successfully brings up the DVD Menu (did not click play on this one but pretty sure it will work).

I can't remember which tool I used to rip these.  I started in 2013 trying to preserve all the features for "wife acceptance factor".  But that took a lot of disk space.  After about 300 or 400 titles, I switched to AnyDVD / Handbrake to leave off all the "features" and just stream the .m4v (mkv) format.

I just don't relish the thought of going back and converting all the 400 titles I did in the video_ts format.

**Comment by DaVukovic** [comment]
Thanks for your effort. Much appreciated!!

No need for a further log, but are you able to reproduce that with any movie which has a DVD menu and using the global search addon?

I tried here with different DVDs stored in a ISO and I couldn't reproduce. The movies (and therefore the DVD menus) start no matter from where I selected them. I'm goiing to re-rip a movie to it's open structure and will also try that. I just want to be sure if the mary poppins movie is the only movie which is affected for you.

**Comment by GaryPSmith** [comment]
Yes, I can reproduce.  Examples:

Happy Feet plays correctly.
Happy Gilmore plays correctly.
The Happy Elf does not play (spinning wait state).
The Pursuit of Happiness plays.
Brewster's Millions does not play (spinning wait state).
Million Dollar Baby plays correctly.
Millions plays correctly.
The Happiest Millionaire does not play correctly (shows spinning wait state but can hear the DVD menu music).
