### ISSUE TITLE
"Compiled" date info not correct in Kodi.log and System Information GUI

### ISSUE THREAD

**Issue by VanFleet2019** [xbmc/xbmc#15145]
## Bug report

"Compiled"  date information  not correct in Kodi.log and Sytem Information GUI 

### Describe the bug

"Compiled"  date information  not correct in Kodi.log and Sytem Information GUI 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

"Compiled"  date information should report the  compilation date

## Actual Behavior

"Compiled"  date information not correct in Kodi.log and Sytem Information GUI. Garbage info logged/shown

## Possible Fix

The problem is in CompileInfo.cpp.in

const char* CCompileInfo::GetBuildDate()
{
  const std:: string bdate = "@APP_BUILD_DATE@";
  if (!bdate.empty())
  {
    std:: string datestamp = bdate.substr(0, 4) + "-" + bdate.substr(4, 2) + "-" + bdate.substr(6, 2);
    return datestamp.c_str();
  }
  return "1970-01-01";
}

https://stackoverflow.com/questions/22330250/how-to-return-a-stdstring-c-str

Should be changed in 

std:: string CCompileInfo::GetBuildDate()
{
const std:: string bdate = "@APP_BUILD_DATE@";
if (!bdate.empty())
{
std:: string datestamp = bdate.substr(0, 4) + "-" + bdate.substr(4, 2) + "-" + bdate.substr(6, 2);
return datestamp;
}
return "1970-01-01";
}

Of course changed also in CompileInfo.h

static const char* GetBuildDate();

with 

static std:: string GetBuildDate();

### To Reproduce

1.  Activate Kodi.log 
2. Go to System Information GUI
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:  Android 5.1.1,  and 6.0.1
 - Kodi version:

v18 - Leia - RC4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
You are 12 hours too late :-)

#15140

**Comment by pkerling** [comment]
PR merged.
