### ISSUE TITLE
Is Leia coming 2019 to tvOS, is this a dead end for now or dead for ever ?

### ISSUE THREAD

**Issue by fdm96** [xbmc/xbmc#15150]
**Hello,**
 
I Saw in the Leia Changelog on the wiki that there are 

> tvOS

optimizations and a couple of socialmedia confirm that there is something else? So I am just curious if the tvOS branch is coming later or if at this time, it is going to stop on Krypton? 

i Hope so Hope this Project is not to stop!

Thank you all for your time and for all the work that you do to bring this excellent media player to all of us is pur amazing and im love it tooo much with this player. 

**Happy New Year Team Kodi, Skinners and modders!**

Greez fdm96

**Comment by MartijnKaijser** [comment]
Ask on the forum. This is no place for questions
