### ISSUE TITLE
Kodi 18 rc3 Android Audio drop outs DD

### ISSUE THREAD

**Issue by krille30** [xbmc/xbmc#15151]
### Describe the bug
Here is a clear and concise description of what the problem is:
Getting random Audio drop outs when playing DD or DTS videos in Kodi 18 rc2 and rc3. Having Android box Minix u9h connected to AVR Onkyo 626 through hdmi.

Issue comes randomly somtimes every minute sometimes it can take 15min. In other video apps playing same video I dont get issue e.g VLC.

Noticed same isdue also on kodi 17.6

In this attached errolog I got audio drop outs after playing 20 sec, 34sec, 44sec, 7min and 9 min 30 sec.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expecting not to have audio drop outs when playing DD or DTS.

## Actual Behavior

Getting randomly audio drop outs.

### To Reproduce

1. Play video with DD or DTS
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 18 RC3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You mentioned it, but I don't see it. 

Where is your log? 

I'll mark that as invalid as long as you submitted the log. If no log has been submitted in the next 3 days, we will close that issue.

**Comment by kib** [comment]
You forgot the log you mentioned and filling out the rest of the report. Please edit / add the required information and a link to your debuglog.

**Comment by krille30** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/2715229/kodi.log)

Sorry missed to attached it. Here it is.

**Comment by krille30** [comment]
![20181228_171925](https://user-images.githubusercontent.com/8210362/50521636-ee571e80-0ac6-11e9-968e-49944b43f983.jpg)
![20181228_171947](https://user-images.githubusercontent.com/8210362/50521644-f911b380-0ac6-11e9-9134-f4f6b9874981.jpg)

Also attached screenshot of sound setting

**Comment by fuzzard** [comment]
DD on android is working for current team devs knowledgable in the area. If the issue persists with v19, please open a ticket and provide all relevant logs and media info details
