### ISSUE TITLE
Please improve your handling of banned addons in logs - by listing which ones are banned

### ISSUE THREAD

**Issue by Dave-Lowndes** [xbmc/xbmc#15163]
## Bug report
Currently any banned addon in a debug log results in a bug report being marked invalid, but there's no indication of which addons in the log are banned.
By reporting issues we're trying to help - make it easier for us to comply with this requirement by listing which addons in the debug log are banned - that way we'll be able to remove the offender quickly and update the bug report.

## Expected Behavior
Rather than just saying a log contains banned addons, list which they are.

## Actual Behavior
All we know is that there is presumably one or more banned addons

## Possible Fix
List the offenders.

**Comment by pkerling** [comment]
We use GitHub exclusively for issues with the core code. Please discuss this in the forums. Thanks!

PS: The list of banned add-ons is usually linked in the message requesting a new log. Here it is again for your information: https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons

**Comment by pkerling** [comment]
Also as hint for the future: You should *always* reproduce in a clean installation, so banned add-ons should in fact never become a problem in the first place (since you can't have any then).

**Comment by Dave-Lowndes** [comment]
I've seen the list, but it'd make everyone's job easier to have them identified by whatever is invalidating the bug reports. As to always reproducing in a clean installation - clearly that's highly inconvenient.

**Comment by pkerling** [comment]
> clearly that's highly inconvenient

Clearly it is highly inconvenient for us to identify whether the issue is in the environment, installation, an add-on etc. without the help of issue reporters. Please remember that we are all volunteers and *you need to do your part if you want something fixed*. Expect low motivation to investigate any issue reported by you that shows you are not willing to put effort into the analysis.

Anyway, if you still feel the need to discuss this, head to the forums.

**Comment by Dave-Lowndes** [comment]
I have posted on the forums - though I see this as an issue with the bug reporting rather than a topic for a forum discussion!

I appreciate you're volunteers - and don't forget that we are volunteering our time in reporting these things too. I hope we're all after the same goal - improving what is a fantastic piece of software.

**Comment by pkerling** [comment]
> though I see this as an issue with the bug reporting rather than a topic for a forum discussion!

Exactly. It is a meta issue and not an issue of the application. The GH workflow in this repository is adjusted to code issues.

> I hope we're all after the same goal - improving what is a fantastic piece of software.

:+1:
