### ISSUE TITLE
Video playback, heavily stuttering

### ISSUE THREAD

**Issue by j-snijder** [xbmc/xbmc#15169]
### Describe the bug
Here is a clear and concise description of what the problem is:

Video playback stutters heavily on video_TS an ISO files !
AFAIK its due to buffering, as a few settings in disablig hardware an buffer size does improve a little its not far as good as in version 17.6
In LEIA the problem is so big that watching movies is fairly impossible.
The problem occurs with my H96pro+ with 3Gb ram and 32Gb rom
With my MXQ pro 4K there is no problem as far as I can find out, on that box I run Leia fairly smooth, but when I change the buffering into 100% and disable the hardware coding it stutters just as the H96 pro+
So my conclusion is that LEIA is way too needy in resources, OR there is something wrong with coding.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expected vido to play smooth and in a decent matter, it does not, 

It should be possible to revert to the videoplayer compnent in v.17.6 or even before that I guess.

Why ?: users like KODI and as in LEIA the audio setting and performance is way better I like to keep using KODI as well :)

## Actual Behavior

Video stutters (kinda freezes) heavily

## Possible Fix

many users have the same problem and even some improvements by changing the setting is offered throughout the internet but none of them really tackles the problem.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
Debugging log is not available (or anyway not logged afaik) on my system, why ?? don't know

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android 7.x.x
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: LEIA all versions

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
> Debugging log is not available (or anyway not logged afaik) on my system, why ?? don't know

I highly doubt that you are not able to enable debug logging at: 
settings -> system -> logging -> enable debug logging

and then use the Kodi logfile uploader addon:
https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

and use that to upload your log. 

As long as no log is submitted we will mark this as invalid. That label will be removed after you submitted a logfile. If you don't provide a log within the next 3 days, we will close that issue as we can't do anything without a log.

**Comment by DaVukovic** [comment]
No log, no further reaction. 

Issue closed

**Comment by neelusR** [comment]
I am experiencing stuttering as well. I am not sure if it is related to this [post](https://forum.kodi.tv/showthread.php?tid=340822&pid=2822735#pid2822735) . 

For me in Kodi 17.x everything was working fine. After updating to LibreElec 9 I experienced heaving stuttering at some stream and unable to playout some live streams at all. Also out of sync audio and my processing settings are not available. 

My system is an old x86 netbook.

I've uploaded the [log file](https://mega.nz/#!W3ZSlCKa!RtxF6_AGIsFVIu96NyaJ0iGd8F4BuPQ-EQvx2sSDf7I). Let me know if there are other things I can add.

**Comment by fritsch** [comment]
@neelusR this will never go away:

```
11:04:51.717 T:140023295855936  NOTICE: Host CPU: Intel(R) Atom(TM) CPU N450 @ 1.66GHz, 2 cores available
```

No video acceleration, nothing. Time to replace it with a Raspberry Pi - much better for video decoding.

**Comment by neelusR** [comment]
@fritsch I know it is not very powerful, but it does have a graphics card  Intel GMA 3600 and in Kodi 17.6 it runs perfectly. The thing I don't get is, in 17 i have hardware acceleration - VAAPI enabled. However in Leia, there are no settings under Processing at all.

I am thinking Kodi 18 is not using the hardware acceleration. Could this be the case?
(I have a Nvidia dev board lying around I might try e ;-)

**Comment by fritsch** [comment]
18.0 does not support this outdated OpenGL level anymore.  Furtherrmore it does not support the oldish VAAPI-Output anymore. See also our wiki: https://kodi.wiki/view/Supported_hardware#Desktop

If you want support for this hardware: Use 17.6

**Comment by neelusR** [comment]
Thanks for the feedback. According to the specs the video card supports "OpenGL 2.1 with Linux" and the wiki says "Intel, or NVIDIA which support OpenGL 2.0 or later." Maybe I am not looking in the correct place, I cannot find 18 specific release notes. I also see "VAAPI is recommended" on the wiki.

Anyhow, the facts confirm what you are saying and I probably need to look for an alternative when wanting to upgrade. Thanks.
