### ISSUE TITLE
Timeshift time shown even after channel switch

### ISSUE THREAD

**Issue by benroe89** [xbmc/xbmc#15175]
### Describe the bug
Here is a clear and concise description of what the problem is:
Once the Timeshift is triggered by pressing Pause, the time is shown properly in the channel info overlay. But when switching the tv channel, the Timeshift time still got shown.
To my understanding, the Timeshift should be reset after a channel switch. Thus it is no more shown in the channel info overlay.

Currently running the latest build of OSMC, 17.8-383, with the PVR Tvheadend client.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. Open a tv channel for watching
2. Open channel info overlay (pressing "Info" on tv remote)
3. Press "Pause" button on tv remote
4. (Wait till Timeshift info appears on channel info overlay)
5. Switch tv channel by pressing Channel Up on tv remote 
6. The Timeshift info still shown on channel info overlay.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC 17.8-383
 - Kodi version: 18.0 RC4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
> Running the latest build of OSMC, 17.8-383

Does this also happen with stock Kodi v18 RC4?

**Comment by ksooo** [comment]
As  I don't know what you mean exactly, could you post some screen shots explaining the problem?

**Comment by ksooo** [comment]
And, please post a debug log file, please.

**Comment by benroe89** [comment]
Please find the log files at the following address: https://paste.osmc.tv/avabozizus.
I enabled the PVR and EPG component specific logging.

**Comment by ksooo** [comment]
Can  you please post step  by step instructions how to reproduce - which keys to press in which order, just  everything. There are so many ways  to  switch channels...

**Comment by ksooo** [comment]
If you untick "on-demand", does this make a difference?

**Comment by benroe89** [comment]
Yes, it starts immediately to record whenever you switch to a tv channel.
So the Timeshift info gets reset properly.

**Comment by ksooo** [comment]
> Yes, it starts immediately to record whenever you switch to a tv channel.
So the Timeshift info gets reset properly.

 Sorry, I do not understand what that means.

 My question was: Does unselecting "On-demand (no first rewind)" in tvheadend server timeshift settings "fix" the wrongly displayed timeshift time after channel switch. So, the answer (i can understand) would be simply "yes" or "no". ;-)
