### ISSUE TITLE
Video OSD doesn't come up while playing BR ISO using the keyboard

### ISSUE THREAD

**Issue by DaVukovic** [xbmc/xbmc#15178]
### Describe the bug
Here is a clear and concise description of what the problem is:

Normally if you start a video from the beginning and press "Enter" on your keyboard the video OSD with all its controls (play/pause, stop, skip etc...) comes up.
If you try to play the same movie from its resume point (and that's important that is has a resumepoint), and if you then press enter on your keyboard, the video OSD doesn't come up anymore and I had to use the mouse to bring it up again.

This only happens with BR ISO files. I tried a few mkv files which don't have that problem!!

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The video OSD should be shown even if you play BR ISO files from their resume point.

## Actual Behavior

The video OS is not shown if you press "Enter" on your keyboard if you start a BR ISO from its resume point. 

### To Reproduce

1. Play a BR ISO and skip so it gets a resume point 
2. Restart that ISO at its resume point
3. Press the "Enter" key on your keyboard and you'll see that there's no video OSD coming up

### Debuglog

The debuglog can be found here:

http://paste.ubuntu.com/p/nCzthBkYmK/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 16.04
 - Kodi version: 18.0-RC5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by da-anda** [comment]
@ace20022 since you know this code best, mind having a look? Thanks.

**Comment by snake3ca** [comment]
This is still an issue in Kodi 18.1 as well.

**Comment by DaVukovic** [comment]
Fixed at least at Kodi 19. Not sure about recent Kodi 18 releases. So I'm going to close this one
