### ISSUE TITLE
myvideos113.tvshow_view not ANSI 92 compliant and therefore broken 

### ISSUE THREAD

**Issue by wildcat2020** [xbmc/xbmc#15173]
### Describe the bug
Here is a clear and concise description of what the problem is:

myvideos113.tvshow_view not ANSI  92 compliant as it includes group by clause without all the selected fields in the select statement. Therefore any normal ANSI 92 compliant RDBMS such as MySQL 5.7 fails to create the view succesfully.

## Expected Behavior
Succesfully create the view and be able to select from it

## Actual Behavior
It errors out: SELECT list is not in GROUP BY clause ERROR MySQL

## Possible Fix

GROUP BY clause should be eliminated. There is no need for GROUP BY clause as there is no agregate function in the SELECT clause.

OR

Rewrite select statement to include full GROUP BY clause, i.e. as follows:

select `myvideos113`.`tvshow`.`idShow` AS `idShow`,`myvideos113`.`tvshow`.`c00` AS `c00`,`myvideos113`.`tvshow`.`c01` AS `c01`,
       `myvideos113`.`tvshow`.`c02` AS `c02`,`myvideos113`.`tvshow`.`c03` AS `c03`,`myvideos113`.`tvshow`.`c04` AS `c04`,`myvideos113`.`tvshow`.`c05` AS `c05`,
       `myvideos113`.`tvshow`.`c06` AS `c06`,`myvideos113`.`tvshow`.`c07` AS `c07`,`myvideos113`.`tvshow`.`c08` AS `c08`,`myvideos113`.`tvshow`.`c09` AS `c09`,
       `myvideos113`.`tvshow`.`c10` AS `c10`,`myvideos113`.`tvshow`.`c11` AS `c11`,`myvideos113`.`tvshow`.`c12` AS `c12`,`myvideos113`.`tvshow`.`c13` AS `c13`,
       `myvideos113`.`tvshow`.`c14` AS `c14`,`myvideos113`.`tvshow`.`c15` AS `c15`,`myvideos113`.`tvshow`.`c16` AS `c16`,`myvideos113`.`tvshow`.`c17` AS `c17`,
       `myvideos113`.`tvshow`.`c18` AS `c18`,`myvideos113`.`tvshow`.`c19` AS `c19`,`myvideos113`.`tvshow`.`c20` AS `c20`,`myvideos113`.`tvshow`.`c21` AS `c21`,
       `myvideos113`.`tvshow`.`c22` AS `c22`,`myvideos113`.`tvshow`.`c23` AS `c23`,`myvideos113`.`tvshow`.`userrating` AS `userrating`,
       `myvideos113`.`tvshow`.`duration` AS `duration`,`myvideos113`.`path`.`idParentPath` AS `idParentPath`,`myvideos113`.`path`.`strPath` AS `strPath`,
       `tvshowcounts`.`dateAdded` AS `dateAdded`,`tvshowcounts`.`lastPlayed` AS `lastPlayed`,`tvshowcounts`.`totalCount` AS `totalCount`,
       `tvshowcounts`.`watchedcount` AS `watchedcount`,`tvshowcounts`.`totalSeasons` AS `totalSeasons`,`myvideos113`.`rating`.`rating` AS `rating`,
       `myvideos113`.`rating`.`votes` AS `votes`,`myvideos113`.`rating`.`rating_type` AS `rating_type`,`myvideos113`.`uniqueid`.`value` AS `uniqueid_value`,
       `myvideos113`.`uniqueid`.`type` AS `uniqueid_type` 
  from (((((`myvideos113`.`tvshow` left join `myvideos113`.`tvshowlinkpath` on((`myvideos113`.`tvshowlinkpath`.`idShow` = `myvideos113`.`tvshow`.`idShow`))) 
       left join `myvideos113`.`path` on((`myvideos113`.`path`.`idPath` = `myvideos113`.`tvshowlinkpath`.`idPath`))) 
       join `myvideos113`.`tvshowcounts` on((`myvideos113`.`tvshow`.`idShow` = `tvshowcounts`.`idShow`))) 
       left join `myvideos113`.`rating` on((`myvideos113`.`rating`.`rating_id` = `myvideos113`.`tvshow`.`c04`))) 
       left join `myvideos113`.`uniqueid` on((`myvideos113`.`uniqueid`.`uniqueid_id` = `myvideos113`.`tvshow`.`c12`)))
 Group by `myvideos113`.`tvshow`.`idShow` ,`myvideos113`.`tvshow`.`c00` ,`myvideos113`.`tvshow`.`c01` ,
       `myvideos113`.`tvshow`.`c02` ,`myvideos113`.`tvshow`.`c03` ,`myvideos113`.`tvshow`.`c04` ,`myvideos113`.`tvshow`.`c05` ,
       `myvideos113`.`tvshow`.`c06` ,`myvideos113`.`tvshow`.`c07` ,`myvideos113`.`tvshow`.`c08` ,`myvideos113`.`tvshow`.`c09` ,
       `myvideos113`.`tvshow`.`c10` ,`myvideos113`.`tvshow`.`c11` ,`myvideos113`.`tvshow`.`c12` ,`myvideos113`.`tvshow`.`c13` ,
       `myvideos113`.`tvshow`.`c14` ,`myvideos113`.`tvshow`.`c15` ,`myvideos113`.`tvshow`.`c16` ,`myvideos113`.`tvshow`.`c17` ,
       `myvideos113`.`tvshow`.`c18` ,`myvideos113`.`tvshow`.`c19` ,`myvideos113`.`tvshow`.`c20` ,`myvideos113`.`tvshow`.`c21` ,
       `myvideos113`.`tvshow`.`c22` ,`myvideos113`.`tvshow`.`c23` ,`myvideos113`.`tvshow`.`userrating` ,
       `myvideos113`.`tvshow`.`duration` ,`myvideos113`.`path`.`idParentPath` ,`myvideos113`.`path`.`strPath` ,
       `tvshowcounts`.`dateAdded` ,`tvshowcounts`.`lastPlayed` ,`tvshowcounts`.`totalCount` ,
       `tvshowcounts`.`watchedcount` ,`tvshowcounts`.`totalSeasons` ,`myvideos113`.`rating`.`rating` ,
       `myvideos113`.`rating`.`votes` ,`myvideos113`.`rating`.`rating_type` ,`myvideos113`.`uniqueid`.`value` ,
       `myvideos113`.`uniqueid`.`type`;

### To Reproduce
Run view creation SQL against any 5.7 or later MySQL database version, or any other ANSI 92 compliant database (like Oracle RDBMS for instance).

### Debuglog
N/A

### Screenshots 
N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

### Your Environment
Used Operating system:

 - [ X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: MS Windows 10, Android Lollipop 5.0
 - Kodi version: 18 RC 4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Rechi** [comment]
As you already have investigated what has to change, can you submit a Pull Request?

**Comment by wildcat2020** [comment]
Hi, no problem, but I don't know how to do it...can you help me?
Also I am not sure how the scripts are written exactly, you see I am only correcting the select so I am not sure how Kodi team has coded the create view as select exactly...
If you guide me I can do it.

**Comment by wildcat2020** [comment]
OK, I went through the wiki, and managed to setup GIT, clone the repository, create my branch.
Now I guess I have to create a commit and then make a pull request?
But to create a commit I need to find the file I guess that includes this create statement so that I update it. Accordingly. Where can I get that one?

**Comment by pkerling** [comment]
I'll merge this to #15172. This is getting really confusing ;-) It already mentions where you have to go.

**Comment by pkerling** [comment]
Merged into #15172 since it is almost the same issue.
