### ISSUE TITLE
myvideos113.season_view and tvshow_view not ANSI  92 compliant and therefore broken

### ISSUE THREAD

**Issue by wildcat2020** [xbmc/xbmc#15172]
### Describe the bug
Here is a clear and concise description of what the problem is:

myvideos113.season_view and tvshow_view not ANSI  92 compliant as it includes group by clause without all the selected fields in the select statement. Therefore any normal ANSI 92 compliant RDBMS such as MySQL 5.7 fails to create the view succesfully.

## Expected Behavior
Succesfully create the view and be able to select from it

## Actual Behavior
It errors out: SELECT list is not in GROUP BY clause ERROR MySQL

## Possible Fix
View definition should change as follows: 

select `myvideos113`.`seasons`.`idSeason` AS `idSeason`,`myvideos113`.`seasons`.`idShow` AS `idShow`,`myvideos113`.`seasons`.`season` AS `season`,
       `myvideos113`.`seasons`.`name` AS `name`,`myvideos113`.`seasons`.`userrating` AS `userrating`,`tvshow_view`.`strPath` AS `strPath`,
       `tvshow_view`.`c00` AS `showTitle`,`tvshow_view`.`c01` AS `plot`,`tvshow_view`.`c05` AS `premiered`,`tvshow_view`.`c08` AS `genre`,
       `tvshow_view`.`c14` AS `studio`,`tvshow_view`.`c13` AS `mpaa`,
       count(distinct `myvideos113`.`episode`.`idEpisode`) AS `episodes`,
       count(`myvideos113`.`files`.`playCount`) AS `playCount`,
       min(`myvideos113`.`episode`.`c05`) AS `aired` 
  from (((`myvideos113`.`seasons` join `myvideos113`.`tvshow_view` on((`tvshow_view`.`idShow` = `myvideos113`.`seasons`.`idShow`))) 
       join `myvideos113`.`episode` on(((`myvideos113`.`episode`.`idShow` = `myvideos113`.`seasons`.`idShow`) 
       and (`myvideos113`.`episode`.`c12` = `myvideos113`.`seasons`.`season`)))) 
       join `myvideos113`.`files` on((`myvideos113`.`files`.`idFile` = `myvideos113`.`episode`.`idFile`))) 
 group by `myvideos113`.`seasons`.`idSeason`,`myvideos113`.`seasons`.`idShow`,`myvideos113`.`seasons`.`season`,`myvideos113`.`seasons`.`name`,
          `myvideos113`.`seasons`.`userrating`,`tvshow_view`.`strPath`,`tvshow_view`.`c00`,`tvshow_view`.`c01`,`tvshow_view`.`c05`,`tvshow_view`.`c08`,
          `tvshow_view`.`c14`,`tvshow_view`.`c13`;

tvshow_view:

GROUP BY clause should be eliminated. There is no need for GROUP BY clause as there is no agregate function in the SELECT clause.

OR

Rewrite select statement to include full GROUP BY clause, i.e. as follows:

select `myvideos113`.`tvshow`.`idShow` AS `idShow`,`myvideos113`.`tvshow`.`c00` AS `c00`,`myvideos113`.`tvshow`.`c01` AS `c01`,
       `myvideos113`.`tvshow`.`c02` AS `c02`,`myvideos113`.`tvshow`.`c03` AS `c03`,`myvideos113`.`tvshow`.`c04` AS `c04`,`myvideos113`.`tvshow`.`c05` AS `c05`,
       `myvideos113`.`tvshow`.`c06` AS `c06`,`myvideos113`.`tvshow`.`c07` AS `c07`,`myvideos113`.`tvshow`.`c08` AS `c08`,`myvideos113`.`tvshow`.`c09` AS `c09`,
       `myvideos113`.`tvshow`.`c10` AS `c10`,`myvideos113`.`tvshow`.`c11` AS `c11`,`myvideos113`.`tvshow`.`c12` AS `c12`,`myvideos113`.`tvshow`.`c13` AS `c13`,
       `myvideos113`.`tvshow`.`c14` AS `c14`,`myvideos113`.`tvshow`.`c15` AS `c15`,`myvideos113`.`tvshow`.`c16` AS `c16`,`myvideos113`.`tvshow`.`c17` AS `c17`,
       `myvideos113`.`tvshow`.`c18` AS `c18`,`myvideos113`.`tvshow`.`c19` AS `c19`,`myvideos113`.`tvshow`.`c20` AS `c20`,`myvideos113`.`tvshow`.`c21` AS `c21`,
       `myvideos113`.`tvshow`.`c22` AS `c22`,`myvideos113`.`tvshow`.`c23` AS `c23`,`myvideos113`.`tvshow`.`userrating` AS `userrating`,
       `myvideos113`.`tvshow`.`duration` AS `duration`,`myvideos113`.`path`.`idParentPath` AS `idParentPath`,`myvideos113`.`path`.`strPath` AS `strPath`,
       `tvshowcounts`.`dateAdded` AS `dateAdded`,`tvshowcounts`.`lastPlayed` AS `lastPlayed`,`tvshowcounts`.`totalCount` AS `totalCount`,
       `tvshowcounts`.`watchedcount` AS `watchedcount`,`tvshowcounts`.`totalSeasons` AS `totalSeasons`,`myvideos113`.`rating`.`rating` AS `rating`,
       `myvideos113`.`rating`.`votes` AS `votes`,`myvideos113`.`rating`.`rating_type` AS `rating_type`,`myvideos113`.`uniqueid`.`value` AS `uniqueid_value`,
       `myvideos113`.`uniqueid`.`type` AS `uniqueid_type` 
  from (((((`myvideos113`.`tvshow` left join `myvideos113`.`tvshowlinkpath` on((`myvideos113`.`tvshowlinkpath`.`idShow` = `myvideos113`.`tvshow`.`idShow`))) 
       left join `myvideos113`.`path` on((`myvideos113`.`path`.`idPath` = `myvideos113`.`tvshowlinkpath`.`idPath`))) 
       join `myvideos113`.`tvshowcounts` on((`myvideos113`.`tvshow`.`idShow` = `tvshowcounts`.`idShow`))) 
       left join `myvideos113`.`rating` on((`myvideos113`.`rating`.`rating_id` = `myvideos113`.`tvshow`.`c04`))) 
       left join `myvideos113`.`uniqueid` on((`myvideos113`.`uniqueid`.`uniqueid_id` = `myvideos113`.`tvshow`.`c12`)))
 Group by `myvideos113`.`tvshow`.`idShow` ,`myvideos113`.`tvshow`.`c00` ,`myvideos113`.`tvshow`.`c01` ,
       `myvideos113`.`tvshow`.`c02` ,`myvideos113`.`tvshow`.`c03` ,`myvideos113`.`tvshow`.`c04` ,`myvideos113`.`tvshow`.`c05` ,
       `myvideos113`.`tvshow`.`c06` ,`myvideos113`.`tvshow`.`c07` ,`myvideos113`.`tvshow`.`c08` ,`myvideos113`.`tvshow`.`c09` ,
       `myvideos113`.`tvshow`.`c10` ,`myvideos113`.`tvshow`.`c11` ,`myvideos113`.`tvshow`.`c12` ,`myvideos113`.`tvshow`.`c13` ,
       `myvideos113`.`tvshow`.`c14` ,`myvideos113`.`tvshow`.`c15` ,`myvideos113`.`tvshow`.`c16` ,`myvideos113`.`tvshow`.`c17` ,
       `myvideos113`.`tvshow`.`c18` ,`myvideos113`.`tvshow`.`c19` ,`myvideos113`.`tvshow`.`c20` ,`myvideos113`.`tvshow`.`c21` ,
       `myvideos113`.`tvshow`.`c22` ,`myvideos113`.`tvshow`.`c23` ,`myvideos113`.`tvshow`.`userrating` ,
       `myvideos113`.`tvshow`.`duration` ,`myvideos113`.`path`.`idParentPath` ,`myvideos113`.`path`.`strPath` ,
       `tvshowcounts`.`dateAdded` ,`tvshowcounts`.`lastPlayed` ,`tvshowcounts`.`totalCount` ,
       `tvshowcounts`.`watchedcount` ,`tvshowcounts`.`totalSeasons` ,`myvideos113`.`rating`.`rating` ,
       `myvideos113`.`rating`.`votes` ,`myvideos113`.`rating`.`rating_type` ,`myvideos113`.`uniqueid`.`value` ,
       `myvideos113`.`uniqueid`.`type`;

### To Reproduce
Run view creation SQL against any 5.7 or later MySQL database version, or any other ANSI 92 compliant database (like Oracle RDBMS for instance).

### Debuglog
N/A

### Screenshots 
N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

### Your Environment
Used Operating system:

 - [ X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: MS Windows 10, Android Lollipop 5.0
 - Kodi version: 18 RC 4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Rechi** [comment]
As you already have investigated what has to change, can you submit a Pull Request?

**Comment by wildcat2020** [comment]
Hi, no problem, but I don't know how to do it...can you help me?
Also I am not sure how the scripts are written exactly, you see I am only correcting the select so I am not sure how Kodi team has coded the create view as select exactly...
If you guide me I can do it.

**Comment by pkerling** [comment]
The `CREATE VIEW` is here: https://github.com/xbmc/xbmc/blob/master/xbmc/video/VideoDatabase.cpp#L427
You just have to change the string contents.
If you are unfamiliar with GitHub pull requests, you can walk through an introduction such as https://codeburst.io/a-step-by-step-guide-to-making-your-first-github-contribution-5302260a2940?gi=4c3dc8afa63 (I think you can also make this simple change from the Web UI without using a desktop Git client)

What I don't understand though: We have users that are running Kodi with a MySQL database at the moment, and no one else has reported this problem. How did it work until now? How exactly did you encounter these errors?

**Comment by wildcat2020** [comment]
Hello, thanks for your reply and guidance. MySQL database prior to 5.7, was allowing extended SQL format, but frm 5.7 onwards,  as explained in sqlmode_only_full_group_by is in effect by default as explained in "https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by" 
What I have is  a central MySQL 5.7 database where all my kodi installations are pointing to for video and music database. I guess most of the users are either on a earlier version or haven't realized that. What I did to realize the issue because some of the adding tvshows operations were not working properly, I went via MySQL workbench and tried to query those two views and I got error. This is how I realized they are not working and checked myself their definition. I hope that answers your question.

**Comment by pkerling** [comment]
Well this change has been around since MySQL 5.7.5 which was released in 2014, so it's quite peculiar that no one tripped over it yet. So thanks for reporting.

Wait, so are you saying that Kodi happily starts and you can use it even though the views couldn't be created?

**Comment by wildcat2020** [comment]
Yes, correct Kodi starts properly even with those two views not properly created (actually they get created but they have "invalid" status) and I guess Kodi only checks for creation so it finds them there and it continues working...
Anyway thanks for pointing out to the file, I have found it and I will try to edit it and save it on my client (within my branch which you can see now exists as "feature_myvideos113". 
From there on, once I save the corrected file, please confirm my understanding I will have to:

1. Create a commit
2. Create a pull request for that commit

Thanks and regards

**Comment by pkerling** [comment]
> Yes, correct Kodi starts properly even with those two views not properly created (actually they get created but they have "invalid" status) and I guess Kodi only checks for creation so it finds them there and it continues working...

Oh OK, I did not know they could be "invalid". Not sure we can do much in Kodi then if creation succeeds.

> From there on, once I save the corrected file, please confirm my understanding I will have to:

Yes, exactly.

**Comment by wildcat2020** [comment]
Created the pull request. I hope it is ok. I leave it up to you guys now :-)
