### ISSUE TITLE
Bug -  LEIA - External Players Do Not Update Watched Status

### ISSUE THREAD

**Issue by zxaura1** [xbmc/xbmc#15179]
### Describe the bug
Here is a clear and concise description of what the problem is:

All titles played using KODI's internal VideoPlayer with various skins including Estuary update the watched status fine.
All titles played using an external player launched via the playercorefactory.xml do not update the watched status no matter the skin used including Estuary. 
KODI versions prior to 18 always updated watched status when using external players launched from the playercorefactory.xml but sadly no longer do.
Fwiw, I do have <playcountminimumtime>1140</playcountminimumtime> added in the playercorefactory.xml.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Movies or shows watched status when using external players launched from the playercorefactory.xml has to be changed after watching them

## Actual Behavior

All titles played using an external player launched via the playercorefactory.xml do not update the watched status no matter the skin used including Estuary.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

http://paste.kodi.tv/subaqotaze

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system: Windows 10 x64 v.1809

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64 v.1809
 - Kodi version: LEIA RC3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
duplicate: #14957 

and will be marked as fixed if #15126 will be merged
