### ISSUE TITLE
Putting device into standby and waking leaves PVR guide on previous time instead of jumping to current time

### ISSUE THREAD

**Issue by raccettura** [xbmc/xbmc#15177]
### Describe the bug
Here is a clear and concise description of what the problem is:

Open PVR guide (in my case tvheadend based) and browse at current time.  Put device (in my case android) into standby.  Come back hours later and wake it.  Kodi doesn't go to the current time, it stays at the previous time.  This is confusing behavior.  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should jump to the current time so that you can see what's presently on, not what was on last night.

## Actual Behavior

Kodi stays on the previous time.

### To Reproduce

1. Open PVR guide (in my case tvheadend based) and browse at current time.  
2. Put device (in my case android) into standby.
3. Come back hours later and wake it.  

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18RC4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Works as designed. Please use the forum for feature requests.
