### ISSUE TITLE
ShowTime action does not work 

### ISSUE THREAD

**Issue by loeffelpan** [xbmc/xbmc#15170]
### Describe the bug
A Bug is a clear and concise description of what the problem is:

Action "SHOWTIME" does not work in Krypton. It works on kodi before Jarvis.
Doesn‘t work on Leila RC4. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I think progressbar and information about playback time should appear.

## Actual Behavior

Nothing happens.

### To Reproduce

1. Set ShowTime in a keymap.
example keyboard.xml
<?xml version="1.0" encoding="UTF-8"?>
<keymap>
  <FullscreenVideo>
    <keyboard>
      <pageup>ShowTime</pageup>
    </keyboard>
  </FullscreenVideo>
</keymap> 
2. It is not displayed even by pressing pageup.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC
 - Kodi version: 17.6 but doesn‘t work in 18 RC4 (See above)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
thanx for the report!

this should fix it: https://github.com/xbmc/xbmc/pull/15174

**Comment by loeffelpan** [comment]
Thanks.
But in my case its another skin with same behaviour.

Please fix the action not Estuary with V18.

**Comment by ronie** [comment]
since this is not a kodi bug but a skin problem, you'll have to report the issue on the forum in the support thread of the skin you are using.

**Comment by loeffelpan** [comment]
Seems not to work in any theme?
Sure that the action is implemented in the core and this is really a skin problem?

I will create an issue at skins github. Thanks.

**Comment by ronie** [comment]
yup, i'm sure it's a skin thing.
works fine with Confluence for instance.

**Comment by loeffelpan** [comment]
OK, otherwise the "Info" action does the trick for me.
Thanks again.
