### ISSUE TITLE
Problems creating custom keybindings on Android (shield)

### ISSUE THREAD

**Issue by grimpy** [xbmc/xbmc#15189]
### Describe the bug
Problem when overriding a joystick keybinding:

Ever since 18alpha3 (probably earlier) I've been struggling to configure my keymaps.
Overriding joystick keys only seem to work when it wasn't already defined in the default joystick.xml

Reference to forum discussion:
https://forum.kodi.tv/showthread.php?tid=334168

## Expected Behavior

When overriding a key in josystick.xml
my key should override the default config keys.

## Actual Behavior

My key is only overridden if it wasn't defined in the original joystick.xml

## Possible Fix

Seems somewhere in the code when merging the default joystick.xml with the override config something goes wrong only keys that where not defined in the original joystick.xml gets overriden (on window/global basis)

### To Reproduce

override a key that is defined in the original joystick.xml key will not be overriden

### Debuglog

Config based on https://raw.githubusercontent.com/xbmc/xbmc/master/system/keymaps/joystick.xml
https://gist.github.com/7409e79516d9c484180535466383263f
And added
```xml
    <leftbumper>ActivateWindow(Videos, MovieTitles)</leftbumper>
    <rightbumper>ActivateWindow(Videos, TVShowTitles)</rightbumper>
    <rightthumb>ActivateWindow(Favourites)</rightthumb> 
```

In both global and in home section on the home screen these overriden buttons do work but on any other screen they do not.
If you look at the logs you should see me first pressing buttons while being on the homescreen and they work then I switch to the series page and my bumpers start scrolling instead.
I repeated with some of the other buttons above.

Selfmade joystick.xml
https://gist.github.com/b56f2ddb260fdfad77f8aca3c12a8968
debuglog + used joystick.xml

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] iOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18rc4
 - Shield TV 2015 latest Android TV

**Comment by MartijnKaijser** [comment]
Same https://github.com/xbmc/xbmc/issues/15003

**Comment by grimpy** [comment]
@MartijnKaijser I was request in the forum to create a seperate issue for this.
I aslo beleive they are not 100% the same issue as #15003 talks about media keys specific which I asume are play/pause/forward/back/volume keys only while this ticket talks about all buttons they might (maybe not) be two diffrent issues

**Comment by Wintermute0110** [comment]
This bug could be related to #15316

**Comment by grimpy** [comment]
@Wintermute0110 my device isn't rooted so I can't do this unfortunately but judging on the PR linked to that issue it feels similar indeed

**Comment by memzila** [comment]
I have the same problem with my shield and kodi 18.1
