### ISSUE TITLE
Setting 'Confirm channel switches by pressing "OK"' not respected

### ISSUE THREAD

**Issue by hitn** [xbmc/xbmc#15188]
### Describe the bug
Here is a clear and concise description of what the problem is:

The setting 'PVR&Live TV -> Playback -> Confirm channel switched by pressing "OK"' is not respected for entering channel numbers. Instead of waiting for a "OK" as user confirmation, the channel is immediately switched after the number was entered. This is independent of the mentioned setting. 

The setting *is* however respected for changing the channel via the cursor keys.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Mentioned setting should be respected for PVR channel changes by the cursor keys as well as for PVR channel changes by entering the channel number via digits. If the setting is active, wait for user pressing "ok", otherwise switch immediately.

The expected behavior can also be seen in the KODI documentation wiki [https://kodi.wiki/view/Settings/TV/Playback](url), eventhough the behavior for option enabled and disabled seems to be mixed up there.

## Actual Behavior

When in PVR a channel number is entered by digits, channel is switching immediately instead of waiting for the user to press "ok".

### To Reproduce

1. Use TV Headend client (and be sure your whole PVR stuff is working)
2. Set the setting 'PVR&Live TV -> Playback -> Confirm channel switched by pressing "OK"' to active
3. Go to TV and start Live TV
4. Enter another channel number but do not hit "ok"

### Debuglog

The debuglog can be found here:
See attachment. Here I once changed channel via cursor keys (and of course had to confirmed with "OK") and another time via entering digits (where KODI did not wait for "ok").
[kodi.log](https://github.com/xbmc/xbmc/files/2722645/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LE9 (8.95.001)
 - Kodi version: 18.0-RC3 Git:18.0rc3-Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Works a designed and I actually see no need for changing this.

You can control the delay from entering last digit to  channel switch with the setting value  "channel switch delay" but not  completely disable the automatic switch.

**Comment by ksooo** [comment]
Seems  the wiki need to be fixed, though. Thanks for pointing that out.

**Comment by ksooo** [comment]
Thanks @DaVukovic

**Comment by DaVukovic** [comment]
Closing that for now

**Comment by hitn** [comment]
Oh, it is regrettable to see, that a configurable and well established feature since XBMC times (since when I'm using this) now falls out without any real need.

There is a perfect use case for this behavior: It let's the user exactly the time he needs to enter the digits, without putting him under timely pressure, but also without introducing any additional delays.

I'm using Kodi boxes very often to allow elder people to continue to use their old CRT when analogue broadcasts are stopped and only DVB is left.

These people are often too slow to enter longer digits within the timeout. But if you make the timeout arbitrary long, there are long delays for simple channel numbers like "1", which leads to a bad user experience and compliance.

In fact, older TV sets had often a similar feature by keys like "-/--". If it was a one key digit, you just entered the number and the channel switched right away. But for a two digit channel, you first pressed "-/--". The TV set now *knew* to expect two digits and also waited for the two digits to be entered, no matter how long it took for the user. Without any kind of functionality like this, switching to "29" will result in switching so "2" or to "2" and then to "9" oh so often.

I really hope to see this feature back as an accessibility feature and will open a feature request.

**Comment by ksooo** [comment]
> But if you make the timeout arbitrary long, there are long delays for simple channel numbers like "1", which leads to a bad user experience and compliance.

 You can press OK at anytime to speedup switching.

 OTOH, the switching algorithm is pretty smart. Example: if "1"  was entered and there there is no other possibility according channel numbers (means tere is no 10, 11, 12, 1245, ...), channel switching occurs immediately, no need to press OK.

> I really hope to see this feature back as an accessibility feature and will open a feature request.

 Sorry, wont happen.

**Comment by hitn** [comment]
> You can press OK at anytime to speedup switching.

I invite you to explain it to a 90 year old lady, that "OK" is only needed from time to time to make it faster, but if she presses it and it was not needed, it will falsely enter a menu. :-)

Anyway, I'm just humbly pointing out other perspectives.

For reference:
https://forum.kodi.tv/showthread.php?tid=338967

In any case, thanks for the effort

**Comment by ksooo** [comment]
> I invite you to explain it to a 90 year old lady,

 The day Kodi will be designed to satisfy the needs of 90 year old ladies will be the day I'm leaving the project. ;-)
