### ISSUE TITLE
Infolabel Player.Duration(format)  not working in v18

### ISSUE THREAD

**Issue by trogggy** [xbmc/xbmc#15181]
## Bug report
Infolabel Player.Duration(format) and MusicPlayer.Duration(format)  not working in leia.
### Describe the bug
Previously Player.Duration(hh) , Player.Duration(mm)  and Player.Duration(ss)  would give the respective hours, minutes and seconds for a video or audio file.
Use them in v18 and they all return just Player.Duration  (ie hours:minutes:seconds)
I tested MusicPlayer.Duration(format) and had the same issue.

## Expected Behavior

If a file has a duration of 1 hour, 45 minutes, 3 seconds...
If I use Player.Duration(mm) I expect to get the number of minutes (ie 45)

## Actual Behavior

If I use Player.Duration(mm) I actually get the total duration in hh:mm::ss, eg 1:45:03
Same result for Player.Duration(hh) and Player.Duration(ss)

### To Reproduce

Tested on 17.6 and v18 (last test on windows nightly x64 - 2019.01.01)
To test: start kodi, play file, run test script, view log.
My test script:

`# -*- coding: utf-8 -*-

import xbmc
if xbmc.Player().isPlaying():
    mediaFile = xbmc.Player().getPlayingFile()
    title = xbmc.getInfoLabel('Player.Title')
    position = xbmc.Player().getTime()
    hours = xbmc.getInfoLabel('Player.Duration(hh)')
    minutes = xbmc.getInfoLabel('Player.Duration(mm)')
    seconds = xbmc.getInfoLabel('Player.Duration(ss)')
    # output
    print ('mediaFile is %s'% mediaFile)
    print ('title is %s'% title)
    print ('position is %s'% position)
    print ('hours: %s'% hours)
    print ('minutes: %s'% minutes)
    print ('seconds: %s'% seconds)`

### Debuglog

The debuglog can be found here:
[https://pastebin.com/J3gT5Knx](url)
Script run @ 10:23:30.281

## Additional context or screenshots (if appropriate)
17.6 and older would typically return something like this (with my wife's music!):
`DEBUG:mediaFile is smb://xxx.1995 - Jagged Little Pill/08. Head Over Feet.mp3

DEBUG: title is Head over Feet
DEBUG: position is 9.68400001526
DEBUG: hours: 00
DEBUG: minutes: 04
DEBUG: seconds: 27`

### Your Environment
Used Operating system:

Tested in windows 7 and 10 with  v18.

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: v18

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Should be fixed with #15184

**Comment by trogggy** [comment]
Blimey, that was quick.
Tested on windows, works perfectly.
Thanks ronie, thanks ksooo.
