### ISSUE TITLE
Edit Decision List Cuts are not Working

### ISSUE THREAD

**Issue by TexasRaptor** [xbmc/xbmc#15186]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm using an Edit Decision List with Cuts (0) and Mutes (1).   
When the 1st cut is placed near the beginning of the movie only 17 seconds in playback does not happen as expected.   Rather than cutting forward the movie starts over and over several times before jumping forward to the end of the cut.  When it does skip forward it skips to the wrong point in time.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Here is the following line from the EDL file. 
00:00:17.0    00:03:00.0    0

My expectation is it should cut from 17 seconds to 3 minutes.  And playback should resume at 3 min. 

## Actual Behavior

The movie plays to 17 sec and then starts over.  This happens multiple times reaching 17 seconds and then starting over at a point slightly greater than 0 seconds.  Then it happens again reaching 17 seconds and then starting over at around 5 second.  Then is happens again reaching 17 seconds and starting over at 10 seconds.  After repeating this behavior multiple times starting the movie over rather than cutting forward the movie reaches the 17 sec mark and will finally skip forward, but to an incorrect point time past the end of the edit.

When the movie finally skips forward it skips past the seek time by quite a bit.  However the time stamp on the Player in the GUI does not reflect this and will show it skipped to exactly 3min even though it cut way past the 3 min.   Here is an excerpt from the log....

21:28:19.163 T:14528   DEBUG: CVideoPlayer::CheckAutoSceneSkip - Clock in EDL cut [00:00:17.000 - 00:03:00.000]: 00:00:17.001. Automatically skipping over.
21:28:19.163 T:14528   DEBUG: CVideoPlayer::SetCaching - caching state 1
21:28:19.163 T:14528   DEBUG: CDVDClock::SetSpeedAdjust - adjusted:0.000000
21:28:19.163 T:14528   DEBUG: demuxer seek to: 343000.000000
21:28:19.163 T:14528   DEBUG: CDVDDemuxFFmpeg::SeekTime - seek ended up on time 342384

   

Interestingly I've played around with the EDL file in my experiments and injected a mute for the first 4 seconds before the cut at 17 sec. 
00:00:00.0    00:00:04.0    1
00:00:17.0    00:03:00.0    0

For some reason this changed the behavior.   When having the first 4 seconds muted the player will reach 17 seconds and skip forward rather jump back to the beginning.   The movie still jumps forward past the 3 min mark to 3 minutes and 43 seconds and the time indicator on the player in the GUI does not reflect this

## Possible Fix

I've tried replacing the cuts (0) with commercial skips (3) and the desired behavior is mostly what I'm wanting and that seems to be a workaround for now.   However with the commercial skip if I rewind it will go into the cut scene.  So as long as I don't rewind it gives me the desired behavior.  It would be nice to have the cut work as expected.

### To Reproduce

1.   Load the provided EDL file to a movie with the proper name and folder location
2.   Playback the movie with the cut near the start of the movie
3.   Try removing the mute for the first 4 second from the EDL file and see if the viedo will start over as described

### Debuglog

The debuglog can be found here:

Please see the link for debug log
https://paste.kodi.tv/tafoqajezo.kodi

The log file represents opening Kodi waiting for the libraries to update.  Then launching the moive Mission Impossible.   I allow it to play back to the point it will skip forward to the wrong point.  

### Screenshots 
Here are some links or screenshots to help explain the problem:

No screenshots are provided, please let me know if some would be helpful

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Please see the link for the EDL file being used during this log file
https://paste.kodi.tv/yoreradivu

You will notice that I have comments in the EDL file to the right of the edit decision.   The presence of these comment do not seem to effect anything and I have tried this with and without those comments.  You will also notice in the log the EDL file is read correctly even with the comment in there.   

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [X ] Windows
 - [x] Windows UWP

 - Operating system version/name:   Windows 10 Pro 64 bit
 - Kodi version:     18.0-RC4
I've also tried this with Kodi 17.6 and got the same behavior

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lilgandhi1199** [comment]
And what about with V17.0?
I found that everything worked back then and since then https://github.com/xbmc/xbmc/pull/11714
everything has been consistently incorrect
