### ISSUE TITLE
Slideshowing KODI interface after JSON Error

### ISSUE THREAD

**Issue by BytEvil** [xbmc/xbmc#15180]
Hi! Slideshowing KODI interface after JSON unknown error. After restarting KODI all worked as expected.
Please see [kodi.log](https://pastebin.com/eAQ8ZS2E)

**Comment by pkerling** [comment]
Hello,

you chose to ignore our issue template when reporting this bug. Your report does not contain any useful information. Please edit your post to use the provided template and enter *all* required information. Otherwise, we will close this issue after 3 days of inactivity. Thanks!

**Comment by pkerling** [comment]
No further activity. Closed.
