### ISSUE TITLE
OSX Leia RC4: Video freezes while audio continues when Kodi loses focus

### ISSUE THREAD

**Issue by drl123** [xbmc/xbmc#15198]
I'm having an issue where the video will freeze, but audio continues to play when streaming LiveTV using the Zuki PVR client for HDHomerun tuners when I click off of the Kodi window in OSX.  As soon as the app receives OS focus again, the video syncs back up.  I confirmed it is not specific to the PVR by installing the official HDHomerun addon from the Kodi repository (Silicon Dust's video addon/app).  It behaves exactly the same. As soon as I click outside of Kodi, the video will stop but audio continues until I click back into Kodi.

I confirmed that it does the same when streaming a stored MP4 video from the HD, so not isolated to the TV tuners, seems like all video is doing this.

I also have the SiliconDust OSX native app (not in Kodi) installed and it does not behave that way, so seems to be something isolated to Kodi Leia.  Krypton worked just fine.  The issue started after installing Leia overtop of Krypton.

Running OSX Mojave on iMac late 2013 4xCore-i7 w/ NVIDIA GeForce GTX 775M and latest nightly (Kodi-20190103-79873d86-master-x86_64.dmg)

I just did a clean install on MacBook Pro and same result, so was not isolated to laying Leia overtop of Krypton, nor to the hardware.  Both are running Mojave version of OSX.

Log attached.
[kodi.log](https://github.com/xbmc/xbmc/files/2729388/kodi.log)

If you need any more information, I'll be happy to provide it.

**Comment by drl123** [comment]
Apparently will be fixed with this PR


https://github.com/xbmc/xbmc/pull/15199

**Comment by pkerling** [comment]
@drl123 Please keep issues open until they are actually fixed :-)

**Comment by drl123** [comment]
Sorry, didn't think the PR was because of my issue, but rather that I didn't know it was the same thing someone else was working on and didn't want to clog issues unnecessarily.  Thanks for fixing so quickly.  I'll pull latest nightly tomorrow and verify it solves the issue.

**Comment by drl123** [comment]
Just FYI - confirmed that the issue is now resolved with latest nightly.
