### ISSUE TITLE
Unable to play AVI files with packed b-frames due to FFMPEG code change

### ISSUE THREAD

**Issue by Gertbucket** [xbmc/xbmc#15196]
## Expected Behavior
Play AVI with packed b-frames. No problem in versions previous to Leia.

## Actual Behavior
Playback jittery. Unwatchable.

## Possible Fix
Suggested by Davilla
https://forum.kodi.tv/showthread.php?tid=332945&pid=2805134#pid2805134

Since ffmpeg removed the code to handle avi files with packed b-frames, this could be resolved in the code base by added a mpeg4_unpack_bframes filter after demuxing avi video, before it's sent off to decoder. The code base 'knows' then the demux video packets are coming from avi/dvix media content and this could be used to switch in the ffmpeg filter. Presto, no need to externally remux any media content.

### To Reproduce
 - [ ] Android

Please see the following thread:

https://forum.kodi.tv/showthread.php?tid=332945&pid=2804404#pid2804404

 - Operating system version/name:
 - Kodi version: Leia

**Comment by DaVukovic** [comment]
Where's the debuglog we ask for in the template you obviously decide to ignore?

If there's no log, we can't do anything. I don't doubt davilla that this could probably be fixed. But a debuglog is mandatory.

**Comment by KarellenX** [comment]
No response. Issue closed.

**Comment by w7my** [comment]
I found that I could not play any AVI files without jerking/jumping. Kodi 17.6 works perfectly with all of them.
