### ISSUE TITLE
[GBM] CEC disconnects when refresh rate switching is on

### ISSUE THREAD

**Issue by AreaScout** [xbmc/xbmc#15192]
### Describe the bug

First I don't know if this is a GBM window backend specific issue or device specific but when I compile **_Kodi_** with CEC support and ``Adjust display refresh rate`` is on, it disconnects the CEC adapter when display resolution is changing, all CEC functionally is gone, I have to restart **_Kodi_** to get CEC working again

## Expected Behavior
CEC should not lose connection or re-establish it if display resolution is changing  

## Actual Behavior
When movie starts and **_Kodi_** adjust it's resolution to the one from the movie CEC connection is lost

## Possible Fix
I haven't found and didn't had the time to look closer to the source code but maybe this is easy to fix, after screen resolution changes it should reconnect with the CEC adapter/hardware

again without ``Adjust display refresh rate`` ON it's working without any issues

### To Reproduce
1. Kodi with GBM windowing backend and CEC support 
2. Settings -> Player -> Adjust display refresh rate -> ON
3. Play movie -> CEC will disconnect

### Debuglog
The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/2724129/kodi.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] ODROID-XU4
 - [ ] Windows
 - [ ] Windows UWP

p.s.: I know Exynos is not officially supported by GBM, but maybe this is a general problem

 - Operating system version/name:
Platform: Linux ARM 32-bit, Debian 9.6
 - Kodi version:
18.0-RC5 Git:20181230-3a0ee7c377

**Comment by Kwiboo** [comment]
@AreaScout I do not belive this is an Kodi issue but an issue with the cec-framework adapter for libcec.
I have been trying to improve the cec-framework libcec adapter for the last few days and have pushed two fixup commits to https://github.com/Pulse-Eight/libcec/pull/380.

Please test the updated libcec code togheter with https://github.com/Kwiboo/linux-rockchip/commit/9a248d0ac4902cfe1c8c62325f9194616b03cc9d and see if anything improves.
Also enable cec-framework debug logging with `echo 1 > /sys/module/cec/parameters/debug` and see if that shows anything useful.

By looking at your log it looks like the physical address is lost and never recovered so your HDMI driver (Exynos?) may suffer from the same issue dw-hdmi has, physical address is lost after first HPD pulse and not recovered until get_modes is called.
If possible, something like https://github.com/Kwiboo/linux-rockchip/compare/v4.20...026c7a2d831393a94bbd83c276087e25196685e1 can be adapted to Exynos HDMI driver?

(All kernel patches linked are in the process of being sent upstream)

**Comment by Kwiboo** [comment]
I took a closer look at the Exynos HDMI driver and it looks like it suffers from the same issue observed with dw-hdmi driver, i.e. cec driver gets notified with an invalid address but never with a valid one on HPD pulse.

See https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/exynos/exynos_hdmi.c#L846-L856, when disconnected is directly signals invalid address to cec driver, when connected it should parse new EDID and update drm connector property and notify cec driver with new or same physical address.

**Comment by AreaScout** [comment]
@Kwiboo 

woohoo that's a lot, first I will try the user space library changes + the cec-notifier.c this weekend, again thank you so much 💯 so far ! 👍 

btw. that dw-hdmi.c is also used by Exynos, exynos_hdmi.c is just an extra HW depended layer

**Comment by fuzzard** [comment]
Howd you go with this @AreaScout ? 

@Kwiboo looks like this stalled upstream with the pulseeight side of things, howd the kernel patches go?
