### ISSUE TITLE
NFS: Commit failed with NFS3ERR_ROFS(-30)

### ISSUE THREAD

**Issue by fccagou** [xbmc/xbmc#15194]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm using kodi 18.0 provides by LibreElec on a PI3.
Kodi uses remote nfs source on my local network.
The NFS mount point is readonly.
The NFS server is provides by an uptodate CentOS 7.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No log for each closed file.

## Actual Behavior

Everything works perfectly BUT kodi  sends emergency logs with NFS3ERR_ROFS(-30) for each file it wants to close.
 
    Message from syslogd@localhost at Jan  3 18:51:59 ...
    kodi 18:51:59.410 T:1465041776   ERROR: Failed to close(vol/r12t/Musique/Totem/08 Flower Power.mp3) - close call failed with "NFS: Commit failed with NFS3ERR_ROFS(-30)"

### To Reproduce

1. install libreelec
2. install and configure a NFS readonly mount point with a core CentOS7 server
3.declare the new nfs source in kodi
4. play music
5. look syslog mssages

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

NFS RFC  says https://tools.ietf.org/html/rfc1813

   NFS3ERR_ROFS
       Read-only file system. A modifying operation was
       attempted on a read-only file system.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [X] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreElec 8.90.1
 - Kodi version: 18.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Could you please follow our template and provide a full debuglog?

For the time being, we will mark this as invalid and if you haven't provided a degulog within the next 3 days, this issue will be closed

Thanks in advance.

**Comment by fccagou** [comment]
Ok, I'll try to do get such logs

**Comment by pkerling** [comment]
If you can get hold of a pcap dump of the NFS packets exchanged between Kodi and your server that would be quite helpful, too.

**Comment by fccagou** [comment]
How can I send you the 1.5M pcap file ?

**Comment by pkerling** [comment]
Either upload it here on GitHub (if you are sure it contains no private information) or send me an email (yol@kodi.tv) and I will share it with the team privately.

**Comment by fccagou** [comment]
mail sent

**Comment by pkerling** [comment]
To clarify, you are using the Linux Kernel NFS server?

**Comment by fccagou** [comment]
Yes

**Comment by pkerling** [comment]
Interesting. According to [the NFSv3 specification](https://tools.ietf.org/html/rfc1813), NFS3ERR_ROFS is not a valid error on COMMIT.

Related libnfs change: sahlberg/libnfs#178

**Comment by pkerling** [comment]
@fccagou Also please do attach a debug log :-)

**Comment by fccagou** [comment]
Done

[kodi-nfs-error-debug.log](https://github.com/xbmc/xbmc/files/2727246/kodi-nfs-error-debug.log)

**Comment by DaVukovic** [comment]
@fccagou 

Could you please test: https://forum.kodi.tv/showthread.php?tid=298461&pid=2805469#pid2805469

There was a commit for libnnfs: https://github.com/sahlberg/libnfs/commit/38b62bcf873c778ebde79707bb0409b6a09ee608

which is now included in the milhouse test builds for RPi.

**Comment by MilhouseVH** [comment]
@fccagou can you test build [`#0104`](https://forum.kodi.tv/showthread.php?tid=298461&pid=2805469#pid2805469) of LibreELEC 9.0 for RPi, as this includes the `libnfs` commit that should fix this issue.

You can upgrade to the test build from 8.90.1 by copying the tar file into the `.update` (ssh)/`Update` (Samba) folder, then reboot (and you can go back to 8.90.1 using the same method).

**Comment by fccagou** [comment]
@MilhouseVH I have a RPi3, which tar must I use ?

**Comment by MilhouseVH** [comment]
@fccagou use the RPi2 version for RPi2/RPi3/RPi3+.

**Comment by fccagou** [comment]
Thanks !

**Comment by fccagou** [comment]
LibreElec upgrade is OK (nice boot logo !!) ... but my NFS server is down (murphy's law/single core old CPU)
I make it alive and test Kodi on it !

**Comment by fccagou** [comment]
Seems OK, I have no more log \o/ ... 
but  now, kodi logs are not sent to remote syslog server ...

**Comment by graysky2** [comment]
> can you test build #0104 of LibreELEC 9.0 for RPi, as this includes the libnfs commit that should fix this issue.

@MilhouseVH - Is the commit you referenced ported to the x86_64 version of kodi or is it actually in libnfs?  I found this on a goggle search for `close call failed with "NFS: Commit failed with NFS3ERR_ROFS(-30)` which I am seeing on my x86_64 box's logs (18.0RC5.2) as well.

**Comment by pkerling** [comment]
@graysky2 See https://github.com/sahlberg/libnfs/commit/38b62bcf873c778ebde79707bb0409b6a09ee608. And please read the whole issue report, everything is explained.

**Comment by graysky2** [comment]
@pkerling - Thanks... I totally missed that above.

**Comment by MilhouseVH** [comment]
>  that bumps LibreELEC master to the latest libnfs release.

Apologies for this misinformation as the latest libnfs *release* is of course still 3.0.0 which does not include the fix. I have bumped LibreELEC master to the latest development snapshot (not release) and the snapshot does include the fix.

**Comment by WizBangCrash** [comment]
I'm getting this same error on macOS connecting to a Synology NAS server running DSM 6.2.1. Logs attached.
Any ideas on how I can fix it?
[kodi.old.log](https://github.com/xbmc/xbmc/files/2825069/kodi.old.log)

**Comment by pkerling** [comment]
@WizBangCrash everything was already said in this thread. Please read it.

**Comment by WizBangCrash** [comment]
Hi @pkerling, I have, but I guess I'm not as clever as you as I haven't been able to decipher how the thread relates to macOS??
It talks about adding a later libnfs library to LibreELEC, but I'm not using LibreELEC. I'm using Kodi on macOS.
Is the thread actually saying that Kodi needs to be built with a later version of libnfs, but that hasn't;t been done yet?
I'm not usually this thick. When clear concise information is presented to me I usually understand it.
Sorry!

**Comment by graysky2** [comment]
@WizBangCrash - You need to patch libnfs 3.0.0 (as I type this the current release) and cherry pick/apply https://github.com/sahlberg/libnfs/commit/38b62bcf873c778ebde79707bb0409b6a09ee608 to it.  Build and use the resulting package on your system.

**Comment by fritsch** [comment]
@Memphiz ping

**Comment by pkerling** [comment]
@fritsch permafix is pending on the next libnfs release. it's just a warning without any consequences so no need to rush it

**Comment by fritsch** [comment]
Perfect. Thx

**Comment by WizBangCrash** [comment]
@graysky2 Thank you.

**Comment by Memphiz** [comment]
You need me for the libnfs bump once it’s in upstream @fritsch ?

**Comment by DaVukovic** [comment]
@fritsch @Memphiz @pkerling 

FYI: 

https://github.com/sahlberg/libnfs/commit/030814506e529ef1f1572c7b6e3fc2e4c10cb544

probably bump to libnfsv4 for Kodi 19

**Comment by fuzzard** [comment]
Platforms using tools/depends (osx/ios/tvos, android) now are running a version that includes the fix. Windows also has been bumped to the libnfs 4.0.0 release as well.
