### ISSUE TITLE
18 RC4 Estuary does not visualize the "watched" status for FOSDEM Videos addon (and others)

### ISSUE THREAD

**Issue by thresheek** [xbmc/xbmc#15201]
### Describe the bug
Here is a clear and concise description of what the problem is:

While browsing the videos in the FOSDEM Videos addon it's no longer possible to visually identify non-watched videos.  It used to work in Kodi 17, but after upgrading to 18 RC4 (via LibreELEC 9.0 beta 2), the problem manifests itself.
It might be the issue with the addon, but it works in other skins (e.g. Estouchy), where the watched status is perfectly visible, and works in Kodi 17.6.  The problem also manifests on NASA videos addon. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Estuary should show the watched status for the items.

## Actual Behavior

Estuary only shows the thumbnail (?) but not the watched status for the menu item;

### To Reproduce

0. Use Estuary skin from Kodi 18 RC4.
1. Install FOSDEM Videos add-on (https://kodi.wiki/view/Add-on:FOSDEM_Videos)
2. Browse to 2018 -> Day 1 -> Janson. 
3. Mark "Consensus as a service" as watched via the context menu
4. The UI doesnt change a bit to designate the item was previously watched.

### Debuglog

The debuglog can be found here: http://thre.sh/stuff/kodi-debug-estuary-non-watched.log

### Screenshots 
Here are some links or screenshots to help explain the problem:

1. Current behaviour in FOSDEM Videos when "Consensus as a Service" is marked as watched: no visual distinction on Estuary: https://photos.google.com/share/AF1QipPrnI3hoyuZbTM2o9_CQ8sdZpzGBS7atiRztla8cIR6mw-zyBeWz4mYmFV1dz__HA/photo/AF1QipMyJxj5F7B08c0VYklfsJuEXyeEZQUdstnME8Fi?key=cGdDcmtPQ3BtaU1YYXBERlREdVRuYVdnc1RFcWJ3

2. Current behaviour in FOSDEM Videos when "Consensus as a Service" is marked as watched: there is a visual distinction on Estouchy: https://photos.google.com/share/AF1QipPrnI3hoyuZbTM2o9_CQ8sdZpzGBS7atiRztla8cIR6mw-zyBeWz4mYmFV1dz__HA/photo/AF1QipOE8F8_xXXlHVEaIYMl7LfOW59JtfFVNdeqBpTK?key=cGdDcmtPQ3BtaU1YYXBERlREdVRuYVdnc1RFcWJ3

3. Current behaviour in Youtube when something is marked as watched: there is a visual way to figure out which one is watched in Estuary: https://photos.google.com/share/AF1QipPrnI3hoyuZbTM2o9_CQ8sdZpzGBS7atiRztla8cIR6mw-zyBeWz4mYmFV1dz__HA/photo/AF1QipPHPobyovxbLxkYF8Orpd2VnuIV5qrdtMHiBgkA?key=cGdDcmtPQ3BtaU1YYXBERlREdVRuYVdnc1RFcWJ3

4. Previous behaviour in FOSDEM Videos on Kodi 17.6 (Debian 9): There is a way to distinguish unwatched videos from watched: https://photos.google.com/share/AF1QipPrnI3hoyuZbTM2o9_CQ8sdZpzGBS7atiRztla8cIR6mw-zyBeWz4mYmFV1dz__HA/photo/AF1QipPJKshUVUShG9MpStwsLMrPsUDZyD9YZdA40L4K?key=cGdDcmtPQ3BtaU1YYXBERlREdVRuYVdnc1RFcWJ3

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The same issue is with NASA videos addon.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC (Leia) v8.95.2 BETA
 - Kodi version: 18 RC4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
The problem lies on the addon code which should flag kodi of the content type it provides. 
In the top of the file https://github.com/jelly/plugin.video.fosdem/blob/master/addon.py#L8 add `setContent` to the list of imports from the `xbmcplugin` module:

```python
from xbmcplugin import addDirectoryItem, endOfDirectory, setResolvedUrl, getSetting, setContent
```

Then, just before the end of directory in https://github.com/jelly/plugin.video.fosdem/blob/master/addon.py#L108:

```python
setContent(plugin.handle, 'files')
```

`setContent` can be one of the following: files, songs, artists, albums, movies, tvshows, episodes or musicvideos. See: https://codedocs.xyz/xbmc/xbmc/group__python__xbmcplugin.html#gaa30572d1e5d9d589e1cd3bfc1e2318d6

By the way, if you bring this to the developer attention tell him that currently the addon is only installable in linux due to: https://github.com/jelly/plugin.video.fosdem/blob/master/addon.xml#L15 which should be changed to `all`.

Closing as invalid.
