### ISSUE TITLE
Wrong teletext color order

### ISSUE THREAD

**Issue by engelmarkus** [xbmc/xbmc#15206]
I've noticed that in the teletext window the order of the colors in the bottom seems to be wrong:
![colors_wrong](https://user-images.githubusercontent.com/1225951/50731086-98384a00-115c-11e9-9471-a7945aff4162.png)

On remote controls, the order is usually "red green yellow blue". Note that the buttons work correctly, e. g. the second button opens the page shown in the second field, only the colors of the second and third field are exchanged.
This little patch fixes the problem.
![colors_right](https://user-images.githubusercontent.com/1225951/50731085-98384a00-115c-11e9-8e0a-3a5f05c9b6a5.png)

```
--- a/xbmc/video/Teletext.cpp	2018-12-28 16:55:25.000000000 +0100
+++ b/xbmc/video/Teletext.cpp	2019-01-06 01:44:14.608178161 +0100
@@ -105,8 +105,8 @@
   { TXT_ColorWhite  , TXT_ColorBlack , C_G0P, 0, 0, 0 ,0, 0, 0, 0, 0, 0, 0, 0x3f}, /* ATR_WB */
   { TXT_ColorWhite  , TXT_ColorBlack , C_G0P, 0, 0, 1 ,0, 0, 0, 0, 0, 0, 0, 0x3f}, /* ATR_PassiveDefault */
   { TXT_ColorWhite  , TXT_ColorRed   , C_G0P, 0, 0, 0 ,0, 0, 0, 0, 0, 0, 0, 0x3f}, /* ATR_L250 */
-  { TXT_ColorBlack  , TXT_ColorYellow, C_G0P, 0, 0, 0 ,0, 0, 0, 0, 0, 0, 0, 0x3f}, /* ATR_L252 */
   { TXT_ColorBlack  , TXT_ColorGreen , C_G0P, 0, 0, 0 ,0, 0, 0, 0, 0, 0, 0, 0x3f}, /* ATR_L251 */
+  { TXT_ColorBlack  , TXT_ColorYellow, C_G0P, 0, 0, 0 ,0, 0, 0, 0, 0, 0, 0, 0x3f}, /* ATR_L252 */
   { TXT_ColorWhite  , TXT_ColorBlue  , C_G0P, 0, 0, 0 ,0, 0, 0, 0, 0, 0, 0, 0x3f}, /* ATR_L253 */
   { TXT_ColorMagenta, TXT_ColorBlack , C_G0P, 0, 0, 0 ,0, 0, 0, 0, 0, 0, 0, 0x3f}, /* ATR_TOPMENU0 */
   { TXT_ColorGreen  , TXT_ColorBlack , C_G0P, 0, 0, 0 ,0, 0, 0, 0, 0, 0, 0, 0x3f}, /* ATR_TOPMENU1 */
```

Regards,
Markus

**Comment by KarellenX** [comment]
If you have the patch, maybe a PR would have been better, and the developers could have inspected and decided there?

**Comment by engelmarkus** [comment]
#15207 

Fair enough, I just wasn't keen on forking and cloning the whole repo for swapping two lines :).

**Comment by pkerling** [comment]
> I just wasn't keen on forking and cloning the whole repo for swapping two lines :).

fwiw, you can edit files in the web UI now, so no need to clone to your machine. And GitHub won't be mad at you for forking, it's what the whole system is built for ;-)
