### ISSUE TITLE
Bookmark thumbnails corrupted

### ISSUE THREAD

**Issue by planetmarshall** [xbmc/xbmc#15202]
## Bug report

Bookmark thumbnails appear to be corrupted on creation. Looks like the stride length is off.

## Expected Behavior

Bookmark thumbnails should be a copy of the image frame when the bookmark was taken.

## Actual Behavior

Bookmark thumbnails are corrupted. It looks like the kind of image you get when stride length is not accounted for.

## Possible Fix

It looks like there are two issues
* The screenshot appears to be from a previous buffer
* The stride length appears to be incorrect

### To Reproduce

1. Start a movie.
2. Capture a bookmark

### Debuglog

The debuglog can be found here:

http://paste.osmc.tv/ovocubatew

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://www.dropbox.com/s/aq3rf8t8n9et525/screenshot000.png?dl=0

### Your Environment
Used Operating system:

 - Operating system version/name: Linux osmc 3.14.29-134-osmc
 - Kodi version: 18.0-RC5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by planetmarshall** [comment]
Note that the main image in the linked screenshot does *not* reflect the actual display at the time the screenshot was taken - this may provide a hint as to the bug, as I assume that the screenshot code is not dissimilar from the mechanism used to produce bookmark thumbnails.

**Comment by fritsch** [comment]
Please open the bug with osmc. This is patched AMLdecoder failing to properly do GetPicture. Just disable AML and see that it works.

**Comment by planetmarshall** [comment]
@fritsch Yes, you're correct - thanks. Have filed the bug [here](https://github.com/osmc/osmc/issues/484) with OSMC in case anyone else comes across it via Kodi.
