### ISSUE TITLE
Kodi crashes when trying to resume an .mka or .m4b file

### ISSUE THREAD

**Issue by dimitry-ishenko** [xbmc/xbmc#15203]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi v18 added basic support for audio books, which enables one to resume playing .mka and .m4b files (not entirely unlike video files). However, when I select "Resume audiobook" from the context menu, Kodi freezes breefly and crashes.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When I select "Resume audiobook" from the context menu, Kodi should resume playing the file.

## Actual Behavior

Kodi stops responding breefly and then crashes.

## Possible Fix

/me scratching head

### To Reproduce

1. Start playing an .mka file.
2. Stop it in the middle.
3. Pull up the context menu (eg, by pressing 'c') -- there will be an item called "Resume audiobook".
4. Select the "Resume audiobook" item.
5. Kodi stops responding.
6. Kodi crashes generating crash log.

### Debuglog

The debuglog can be found here:
[kodi_crashlog-20190105_132238.log](https://github.com/xbmc/xbmc/files/2729797/kodi_crashlog-20190105_132238.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04.1 LTS
 - Kodi version: 18.0-rc4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by dimitry-ishenko** [comment]
I am observing same exact behavior with .m4b files.

**Comment by KarellenX** [comment]
Do you have an mka or m4b file to share in case none of the developers have one, and the mod team could test also. One that is confirmed to cause the problem.

**Comment by KarellenX** [comment]
> 
> 
> @KarellenX I've tried more than one, but yes, if anyone needs one for testing, just holler and I will share it.

Yep, I did holler that was the point of my post ;) but seems another mod has a copy anyway.

**Comment by dimitry-ishenko** [comment]
> > @KarellenX I've tried more than one, but yes, if anyone needs one for testing, just holler and I will share it.
> 
> Yep, I did holler that was the point of my post ;) but seems another mod has a copy anyway.

Heh, sorry didn't get that :smile: Well in case one of the devs still needs it, here the [file](https://ufile.io/wsjeu).

**Comment by dimitry-ishenko** [comment]
Here the offending code that causes the crash:
https://github.com/xbmc/xbmc/blob/4abe3490217c76d13751ebd6270e40e837bb0953/xbmc/music/windows/GUIWindowMusicBase.cpp#L694-L696

All of the items in `m_vecItems` have zero `m_lEndOffset`, so `i` ends up pointing to one-past-last element in the array and `m_vecItems->Get(i)` online 696 returns null pointer, which `CFileItem` copy constructor then tries to dereference.

**Comment by MartijnKaijser** [comment]
If you feel like it we would welcome a pull request with the code changes needed :)

**Comment by dimitry-ishenko** [comment]
Further looking at the code it seems Kodi expects audio books to be a single .mka/.m4b file with multiple chapters. In my case I have a directory with several .mka files -- one for each chapter...

This makes sense why all of the items in `m_vecItems` had zero `m_lEndOffset`.

I can try doing a pull request, but my question is: Should Kodi be able to handle audio books with multiple tracks/files? Or was the intention for audio books to be a single file with chapters only?

**Comment by MartijnKaijser** [comment]
@notspiff what was the idea?

**Comment by dimitry-ishenko** [comment]
Looking at it from a broader viewpoint, we are essentially adding RESUME functionality to the audio files. We don't necessarily wan't/need this the songs, but it is essential for audio books and podcasts.

.mka and .m4b files were somewhat arbitrarily chosen to be audiobook-capable formats:
https://github.com/xbmc/xbmc/blob/4abe3490217c76d13751ebd6270e40e837bb0953/xbmc/FileItem.cpp#L908-L911
presumably due to their capability to have chapter marks. However, there are plenty of other formats that have this capability:
* .mp3 [ID3v2 Chapter Frame Addendum](http://id3.org/id3v2-chapters-1.0)
* .flag .ogg .opus [Chapter Extension](https://wiki.xiph.org/Chapter_Extension)

I can see the chapter marks being a delineation point between songs and audio books/podcasts and therefore only files with chapter marks should be resumable.

Users like me, who have their audio books as a bunch of separate .mp3 files, would need to combine them into a single file with chapter marks. Perhaps a tool can be made (or already exists) that can be used for that.

This leaves corner case for audio books with single chapter or podcasts that rarely have chapters (don't quote me on that -- it's been a while since I've downloaded and listened to podcasts).

What would be the solution here?

**Comment by dimitry-ishenko** [comment]
I realize that I am biting off more than I can chew here, so for the sake of keeping this issue on topic, we can assume that the intention for the audio books was to be a single .mka/.m4b file with multiple chapters.

Maybe a separate issue can be opened for other file formats supporting chapter marks.

As a note, it is fairly simple to convert a bunch of separate chapter files into single .mka file with chapter marks using `mkvmerge` program from the [MKVToolNix](https://mkvtoolnix.download/) suite:

    mkvmerge --output merged.mka --title "Audio Book Title" --generate-chapters when-appending Chapter01.mka + Chapter02.mka + Chapter03.mka ...

Feel free to close this issue.

**Comment by pkerling** [comment]
> Feel free to close this issue.

A crash is always an issue, so I'd keep this open until that is fixed (irrespective of underlying functionality).

**Comment by dimitry-ishenko** [comment]
Well, it turns out the resume function is broken even for properly formatted multi-chapter .mka files... I will open a separate issue for that.

In the meantime, I made a small fix that at least prevents a crash for single-chapter .mka files. Will submit pull request shortly.

**Comment by DaVukovic** [comment]
@dimitry-ishenko Please see my comment on your PR. Kodi still crashes for me using the file I provided at your PR. 

The file is played via the filemanager and is not part of my library at all. Not sure if that's important.

**Comment by pkerling** [comment]
@DaVukovic can you confirm this is now fixed with #15213?
