### ISSUE TITLE
Audiobook resume function is broken

### ISSUE THREAD

**Issue by dimitry-ishenko** [xbmc/xbmc#15216]
### Describe the bug
Here is a clear and concise description of what the problem is:

When trying to resume playback in an audiobook file (.mka) with chapter marks, a strange list of chapters is shown and playback starts from the beginning instead of resuming.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

At the minimum the playback should resume from the last stopped point. It would be nice if the strange list of chapters didn't show up either. See screenshots below.

## Actual Behavior

When I select "Resume audiobook" from the context menu, the playback starts from the beginning and lsit of chapters shows up on the screen. See screenshots below.

## Possible Fix

Dunno really.

### To Reproduce

1. Add any audiobook file (.mka or .m4b with chapter marks) to your library
2. Navigate to the file and start playing any chapter
3. Just forward a bit, let it play and press stop
4. Navigate back to the chapter and select "Resume audiobook" from the context menu
5. Observe a strange list of tiles with chapters show up on the screen and the playback will start from the beginning.

### Debuglog

The debuglog can be found here: [kodi.log](https://github.com/xbmc/xbmc/files/2735220/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

I navigate to the audiobook and select chapter 3:
![screenshot from 2019-01-07 23-47-12](https://user-images.githubusercontent.com/2858291/50810358-3819e300-12d7-11e9-8c58-810f89f536fd.png)

I press ENTER and the chapter starts playing:
![screenshot from 2019-01-07 23-47-34](https://user-images.githubusercontent.com/2858291/50810398-73b4ad00-12d7-11e9-81b6-2b2ce395c4a2.png)

I press TAB to see the playback and jump forward a bit:
![screenshot from 2019-01-07 23-47-48](https://user-images.githubusercontent.com/2858291/50810417-8dee8b00-12d7-11e9-8550-30adca6f5e2d.png)

I stop and go back to Chapter 3 and press "c" to pull up the context menu:
![screenshot from 2019-01-07 23-48-23](https://user-images.githubusercontent.com/2858291/50810451-b70f1b80-12d7-11e9-8115-bee1213b5406.png)

I select "Resume audiobook" and end up with this strange screen:
![screenshot from 2019-01-07 23-49-09](https://user-images.githubusercontent.com/2858291/50810516-01909800-12d8-11e9-8801-19ef78d32e8f.png)
What the hell is this screen? I didn't ask for it. I just wanted it to stay on the previous screen, like it did before. Note that it also says that Chapter 2 is playing even though I selected Chapter 3. And the book actually starts playing from the beginning!

I press TAB to go to the playback screen:
![screenshot from 2019-01-07 23-49-24](https://user-images.githubusercontent.com/2858291/50810624-84b1ee00-12d8-11e9-9def-2190b5302c33.png)
It still says it's playing Chapter 2, which (a) I didn't ask for -- I asked for Chapter 3, and (b) it's incorrect --  it's actually playing from the very beginning (Chapter 1).

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04.1 LTS
 - Kodi version: v18-rc4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by dimitry-ishenko** [comment]
Sample audiobook file can be downloaded [here](https://ufile.io/gn0di).

**Comment by dimitry-ishenko** [comment]
I believe it's also incorrect that the "Resume audiobook" shows when you select the chapter. Instead it should show when you pull up context menu for the audiobook "folder" itself.

In other words, you navigate to the audiobook:
![screenshot from 2019-01-08 00-09-34](https://user-images.githubusercontent.com/2858291/50810913-06564b80-12da-11e9-8a28-ed13ac3c0ac1.png)

Then pull up the context menu and if there is a resume point, it should have the "Resume audiobook" item:
![screenshot from 2019-01-08 00-09-46](https://user-images.githubusercontent.com/2858291/50811042-ac09ba80-12da-11e9-98ce-71827ebe9a40.png)

**Comment by dimitry-ishenko** [comment]
Another problem with current implementation is that one play several chapters half way through and each chapter will have its own resume point, which doesn't make sense. There should be single resume point for the entire audiobook.

**Comment by dimitry-ishenko** [comment]
Methinks the starting point would be to save the resume point for the entire audiobook (ie, the album).
In this code:
https://github.com/xbmc/xbmc/blob/adb55e29fdd5e965756c876861adbd615d84cf25/xbmc/music/MusicDatabase.cpp#L10719-L10733
we use path to the chapter (`item->GetPath()`) as a unique ID.

For example in my case it's: `musicdb://albums/2/4.mka?albumid=2`.

I see the `albumid=2` option appended to it. My guess is I could use the `CURL` class to parse  the URL and extract the albumid from it. My question is, what's the proper way to then construct path to the album? Eg, `musicdb://albums/2/`

**Comment by dimitry-ishenko** [comment]
Instead of doing a context menu IMHO it would be better to pop up a small dialog asking if the user wants to resume or play from the beginning.

Same way it's done for the movies:
![screenshot from 2019-01-09 15-39-30](https://user-images.githubusercontent.com/2858291/50927195-0adb4b00-1425-11e9-907d-495ef8bb521a.png)

So, to slightly backtrack on my earlier comment, we would forgo the "Resume audiobook" context menu and instead, when the user tries to play any chapter of the audio book, pop up a dialog similar to the above.

**Comment by notspiff** [comment]
Audiobooks are single files with chapters. Anything album related is something u have invented, and as these are not bugs.

The paths stored used to be the actual paths, but fileitem handling has changed, and it now stores the musicdb paths instead (a regression). If u do what u suggest u will mandate library usage, the code was restricted by the requirement to avoid this.

**Comment by dimitry-ishenko** [comment]
@notspiff where did you get the idea that I invented something? I am dealing with single .mka file with chapters. And looking at the existing code and databases.

**Comment by dimitry-ishenko** [comment]
My understanding from looking at the code here:
https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/filesystem/FileDirectoryFactory.cpp#L183-L192
and here:
https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/filesystem/AudioBookFileDirectory.h#L17-L28
is that individual .mka files are treated as directories (albums?) and chapters inside them as songs. Is that what you were referring to? But, again, that's not my invention that's existing Leia code.

I see your point on mandating library usage. I can look further how this is done with videos that are not part of the library and maybe we can mimic that?

**Comment by dimitry-ishenko** [comment]
Fixed in #15227
