### ISSUE TITLE
Dublicated entries in library in RC5

### ISSUE THREAD

**Issue by wintuxx** [xbmc/xbmc#15212]
### Describe the bug
Here is a clear and concise description of what the problem is:
This error is mainly noticed in series.
Episodes from various sources have been listed under RC4. From RC5 there are now 2 entries in the library.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
In series with episodes from different sources are merged into one entry in library

## Actual Behavior

For serials with episodes from different sources, multiple entries of the same series are now created in the library

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: libreelec
 - Kodi version:
Kodi 18 RC 5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You missed to add a debuglog. And also missed the steps to reproduce. 

Until those informations have been added, I'll mark this as invalid. I also highly guess that this might be something which is better placed at forums as you won't get duplicated entries by simply updating Kodi. 

Consider to clean the library and make sure you don't have different sources added or something like that.

**Comment by MartijnKaijser** [comment]
Fix is being worked on
https://github.com/xbmc/xbmc/pull/15200

**Comment by wintuxx** [comment]
i think a debug log would not help here, because i think it is a database issue.

When I updated to the new Milhouse build # 105 yesterday, I noticed the duplicate entries in the library.
Since I have outsourced my database on a different device, I noticed that a new database was created (MyVideos114). Now I'm back on RC4 (milhouse build # 101) and the duplicates are gone.
