### ISSUE TITLE
TV Show folders not working on XBOX One with NFS media share

### ISSUE THREAD

**Issue by markjritchie** [xbmc/xbmc#15210]
## Bug report
When selecting a TV Show icon from the "In progress TV shows" instead of being presented with a list of episodes I'm taken to the screen with a list of sources e.g.
Movies
TV Shows
Files
Playlists
Video add-ons

Also if I click into the TV Shows menu on the left I get the list of TV Shows but if I select a show the busy spinner displays for a second then nothing happens. No drill-down into the show and no error message.

If I navigate to the Videos menu item I can drill down into the folders and I can also play shows from the "Recently added episodes" list

**Comment by DaVukovic** [comment]
Thanks for ignoring our issue template. Until you provided the missing information our template asks for, we will mark this as invalid. 

Be aware that we will close this issue in 3 days if you don't add the missing informations. 

Thanks in advance.

**Comment by DaVukovic** [comment]
No logfile no further reaction. Issue closed
