### ISSUE TITLE
Player hangs or the GUI freezes when I stop playback

### ISSUE THREAD

**Issue by graysky2** [xbmc/xbmc#15220]
### Describe the bug
Hitting exit on the remote causes video play back to stop, but the Kodi GUI does not return. All I see on the screen is the frozen frame of the video as if I paused playback (of course without the Kodi GUI that is displayed when video playback is paused).  Kodi does not respond to subsequent buttons on my remote or to physical key presses on the attached keyboard.  I can only recover by restarting kodi.  This happened 5 times  since I built RC4, so it is rather infrequent and difficult to reproduce.

## Expected Behavior
Hitting exit on the remote should stop the video without a freeze.

## Actual Behavior
Hitting exit on the remote often stops as expected, but sometimes freezes as described above.

### To Reproduce
As mentioned, it is difficult to reproduce.  What I have been doing is simply playing some content and hitting exit at random times.  I managed to capture a gdb trace which I attached.

### Debuglog

* The debuglog can be found [here](https://gist.github.com/graysky2/457182d33e9c79fca6b67330cc441920) 
* The gdb trace can be found [here](https://gist.github.com/graysky2/b9b07164db816d75cc63cf53a4a6014b)

@fritsch - Commented that, "some script's monitor blocks on exit for a long time" when he saw the gdb trace in the [forum](https://forum.kodi.tv/showthread.php?tid=339097).

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux (x86_64)
 - Kodi version: v18RC4

**Comment by pkerling** [comment]
> Commented that, "some script's monitor blocks on exit for a long time" when he saw the gdb trace in the forum.

Where's the link to the forum thread?

**Comment by graysky2** [comment]
RC5.2 continues to give these intermediate freezes (2 so far).

**Comment by graysky2** [comment]
> @fritsch - Commented that, "some script's monitor blocks on exit for a long time" when he saw the gdb trace in the forum.

Could it be due to `texturecache vscan` to update the videodatabase?  When you used the term script in that reply, I got to thinking that I may have run that command at some point.  I uninstalled [texturecache](https://github.com/MilhouseVH/texturecache.py) about a week ago and I haven't experienced this freeze.  Since it's difficult to reproduce/trigger, I might need to give it more time to verify.

@MilhouseVH @fritsch - Does the gdb trace indicate anything to point to `/usr/bin/texturecache` (python script)?

**Comment by FernetMenta** [comment]
> @fritsch - Commented that, "some script's monitor blocks on exit for a long time" when he saw the gdb trace in the forum.

this is wrong

```
--- a/xbmc/windowing/X11/GLContextEGL.cpp
+++ b/xbmc/windowing/X11/GLContextEGL.cpp
@@ -21,6 +21,7 @@
 #include "ServiceBroker.h"
 #include "settings/AdvancedSettings.h"
 #include "settings/SettingsComponent.h"
+#include "threads/SingleLock.h"
 
 #define EGL_NO_CONFIG (EGLConfig)0
 
@@ -420,6 +421,8 @@ void CGLContextEGL::SwapBuffers()
   uint64_t sbc1, sbc2;
   struct timespec nowTs;
   uint64_t now;
+  uint64_t cont = m_sync.cont;
+  uint64_t interval = m_sync.interval;
 
   eglGetSyncValuesCHROMIUM(m_eglDisplay, m_eglSurface, &ust1, &msc1, &sbc1);
 
@@ -432,7 +435,7 @@ void CGLContextEGL::SwapBuffers()
 
   if ((msc1 - m_sync.msc1) > 2)
   {
-    m_sync.cont = 0;
+    cont = 0;
     // CLog::Log(LOGDEBUG, "CGLContextEGL::SwapBuffers: sync reset");
   }
 
@@ -443,12 +446,12 @@ void CGLContextEGL::SwapBuffers()
   {
     if ((msc1 - m_sync.msc1) == 2)
     {
-      m_sync.cont = 0;
+      cont = 0;
     }
     else if ((msc1 - m_sync.msc1) == 1)
     {
-      m_sync.interval = (ust1 - m_sync.ust1) / (msc1 - m_sync.msc1);
-      m_sync.cont++;
+      interval = (ust1 - m_sync.ust1) / (msc1 - m_sync.msc1);
+      cont++;
       // CLog::Log(LOGDEBUG, "CGLContextEGL::SwapBuffers: sync interval: %ld", m_sync.interval);
     }
   }
@@ -468,7 +471,7 @@ void CGLContextEGL::SwapBuffers()
       }
       uint64_t sleeptime = m_sync.interval - lastIncrement;
       usleep(sleeptime);
-      m_sync.cont++;
+      cont++;
       msc2++;
       CLog::Log(LOGDEBUG, "CGLContextEGL::SwapBuffers: sync sleep: %ld", sleeptime);
     }
@@ -488,10 +491,15 @@ void CGLContextEGL::SwapBuffers()
     msc2++;
   }
 
-  m_sync.ust1 = ust1;
-  m_sync.ust2 = ust2;
-  m_sync.msc1 = msc1;
-  m_sync.msc2 = msc2;
+  {
+    CSingleLock lock(m_syncLock);
+    m_sync.ust1 = ust1;
+    m_sync.ust2 = ust2;
+    m_sync.msc1 = msc1;
+    m_sync.msc2 = msc2;
+    m_sync.interval = interval;
+    m_sync.cont = cont;
+  }
 }
 
 uint64_t CGLContextEGL::GetVblankTiming(uint64_t &msc, uint64_t &interval)
@@ -502,6 +510,8 @@ uint64_t CGLContextEGL::GetVblankTiming(uint64_t &msc, uint64_t &interval)
   now = nowTs.tv_sec * 1000000000 + nowTs.tv_nsec;
   now /= 1000;
 
+  CSingleLock lock(m_syncLock);
+
   msc = m_sync.msc2;
 
   interval = (m_sync.cont > 5) ? m_sync.interval : m_sync.ust2 - m_sync.ust1;
diff --git a/xbmc/windowing/X11/GLContextEGL.h b/xbmc/windowing/X11/GLContextEGL.h
--- a/xbmc/windowing/X11/GLContextEGL.h
+++ b/xbmc/windowing/X11/GLContextEGL.h
@@ -9,6 +9,7 @@
 #pragma once
 
 #include "GLContext.h"
+#include "threads/CriticalSection.h"
 #include "EGL/egl.h"
 #include "EGL/eglext.h"
 #include "EGL/eglextchromium.h"
@@ -48,5 +49,7 @@ protected:
     uint64_t interval = 0;
   } m_sync;
 
+  CCriticalSection m_syncLock;
+
   bool m_usePB = false;
 };
-- 
2.18.0
```

**Comment by fritsch** [comment]
Thx much fernet.

Will pick it that evening.

Am Di., 22. Jan. 2019, 14:14 hat Rainer Hochecker <notifications@github.com>
geschrieben:

**Comment by fritsch** [comment]
@graysky2 Can you please pick: https://github.com/fritsch/xbmc/commit/61e03befc05ccabcd52885056cc1158487205440 and test?

**Comment by graysky2** [comment]
@fritsch - You bet.  Again, it is difficult to get this bug to be triggered and I haven't experienced it in over a week.  Running with your patch now.
