### ISSUE TITLE
DVD movie does not resume from the last position in the timeline where it was stopped

### ISSUE THREAD

**Issue by MisterFloppy** [xbmc/xbmc#15221]
### Describe the bug
Here is a clear and concise description of what the problem is:

I've enabled "Auto resume" in the KODI settings, and it is working fine with all videos - except DVD movies... when I play a DVD movie that has been stopped before, it does not resume from the last position in the timeline where it was stopped, but with a huge amount of seconds ahead.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

"Auto resuming" from the last position should start exactly at the position in the timeline where it was stopped.

## Actual Behavior

"Auto resuming" starts with a huge amount of seconds ahead after the position in the timeline where it was stopped.

## Possible Fix

Under KODI v17.6, this problem occured with all kind of movies: local videos, online videos, DVD movies, etc.. With the upgrade KODI 18, the problem went away - with the exception for DVD movies... Obviously the developers already did find a fix for this issue, but somehow "forgot" to consider it for DVD movies :-)

### To Reproduce

1. Enable "Auto resume" in the KODI settings
2. Play a DVD movie
3. Stop it.
4. Play the DVD movie again and watch the position in the timeline!

### Debuglog

The debuglog can be found here:
https://pastebin.com/hJ9Pt7w5

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP
- LibreELEC
 - Operating system version/name:
Windows 7; LibreELEC (Leia) v8.90.009
 - Kodi version: KODI v18 RC 4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Sorry for the delay. Totally missed that.

**Comment by MisterFloppy** [comment]
While "KODI v18 (Leia) final" is out, the problem has not been solved...

**Comment by MisterFloppy** [comment]
... and under "KODI v18 (Leia) final" I've found out that the problem has returned, too, regarding resuming TVrecordings where HEVC (H265 codec) is involved :-(  Here the amount of seconds ahead when the playing continues is not as big as with DVD movies (maybe "only" 3 seconds), but of course still noticeable.

So please fix this, too - thank you in advance!
