### ISSUE TITLE
No volume control when using mouse only.

### ISSUE THREAD

**Issue by Sopor-** [xbmc/xbmc#15245]
When playing music there is no volume control. Some suggested to change skin, some that use alternative keymaps, but these are only work-a-rounds. A volume control should be something that was obvious when playing music. I have a volume control when i play video, so why should i not need one when playing music only? I use the mouse to control Kodi and i can't change the volume with only the mouse.

**Comment by ronie** [comment]
you should be able to control the volume with a mouse by enabling this setting:
Settings > Interface > Skin Settings > Touch mode

this will add some additional buttons in the skin for touchscreen and mouse users.

![vol](https://user-images.githubusercontent.com/687265/51091813-0057e300-1790-11e9-912f-e496cdd4eef9.jpg)

**Comment by Sopor-** [comment]
That option is not available in the Confluence skin. How do i report this to [skin.confluence](https://github.com/xbmc/skin.confluence)?

**Comment by ronie** [comment]
it's to report it in the confluence support thread on our forum:
http://forum.kodi.tv/forumdisplay.php?fid=125
