### ISSUE TITLE
Kodi is unable to detect internal subtitle language when they are named in chinese apart from chinese

### ISSUE THREAD

**Issue by Dnkhatri** [xbmc/xbmc#15240]
### Describe the bug

Kodi is unable to detect internal subtitle language when they are named in chinese apart from the chinese subtitles so the prefered subtitle are not autoselected.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should detect and show the subtitles if required language is available

## Actual Behavior

Kodi sees the subtitles but as it is unable to detect the language they show up as unknown and have to be manually selected.

## Possible Fix

Mediainfo is able to read and detect the subtitle languages so it should be possible no matter what the language internal subtitles are named in. As can be seen from the mediainfo output
General
Unique ID                                : 229028255213515805556483742568438308957 (0xAC4D3CCBA9AB287DFDB80627D7D0205D)
Complete name                            : /The Girl Who Can See Smells/S01E01 - Episode 1.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 2.84 GiB
Duration                                 : 58 min 37 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 6 927 kb/s
Movie name                               : 看见味道的少女 S01E01
Writing application                      : Lavf58.12.100
Writing library                          : Lavf58.12.100
ErrorDetectionType                       : Per level 1

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L4
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 3 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 58 min 37 s
Bit rate mode                            : Variable
Bit rate                                 : 6 810 kb/s
Maximum bit rate                         : 10.2 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.137
Stream size                              : 2.73 GiB (96%)
Writing library                          : x264 core 148 r2715 7e75228
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x1:0x111 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=8 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / stitchable=1 / constrained_intra=0 / bframes=2 / b_pyramid=0 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=48 / keyint_min=25 / scenecut=0 / intra_refresh=0 / rc_lookahead=48 / rc=2pass / mbtree=1 / bitrate=6810 / ratetol=1.0 / qcomp=0.50 / qpmin=6 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=10215 / vbv_bufsize=13620 / nal_hrd=vbr / filler=0 / ip_ratio=1.40 / aq=1:1.00
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 58 min 37 s
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Bit depth                                : 32 bits
Compression mode                         : Lossy
Stream size                              : 53.7 MiB (2%)
Title                                    : 韩文 [原始] [2.0]
Language                                 : Korean
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

Text #1
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 58 min 37 s
Title                                    : 简体中文
Language                                 : Chinese-Hans
Default                                  : No
Forced                                   : No

Text #2
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 58 min 37 s
Title                                    : 英语
Language                                 : English
Default                                  : No
Forced                                   : No

Text #3
ID                                       : 5
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 58 min 37 s
Title                                    : 阿拉伯语
Language                                 : Arabic
Default                                  : No
Forced                                   : No

Text #4
ID                                       : 6
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 58 min 36 s
Title                                    : 泰语
Language                                 : Thai
Default                                  : No
Forced                                   : No

Text #5
ID                                       : 7
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 58 min 37 s
Title                                    : 法语
Language                                 : French
Default                                  : No
Forced                                   : No

Text #6
ID                                       : 8
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 58 min 37 s
Title                                    : 繁体中文
Language                                 : Chinese-Hant
Default                                  : No
Forced                                   : No

Text #7
ID                                       : 9
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 58 min 35 s
Title                                    : 土耳其文
Language                                 : Turkish
Default                                  : No
Forced                                   : No

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android Nvidia Shield 7.2.2
 - Kodi version: kodi 18 latest nightly though the problem is in all 18 nightlies that i have tried on

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You missed to provide a full debuglog which shows that issue. Please provide that. Otherwise this issue will be closed within the next 3 days.

I'll mark this as invalid for the time being.

**Comment by Dnkhatri** [comment]
> You missed to provide a full debuglog which shows that issue. Please provide that. Otherwise this issue will be closed within the next 3 days.
> 
> I'll mark this as invalid for the time being.
I could not paste my android logs as they might not have been accepted because of some of the addons.
Installed kodi on my linux box just for this  
https://paste.kodi.tv/ogebuvemef

**Comment by fritsch** [comment]
Broken Linux installation without even Audio devices ... and running on Linux Mint. We won't come further here.

**Comment by Dnkhatri** [comment]
> Broken Linux installation without even Audio devices ... and running on Linux Mint. We won't come further here.
Yeah I need to reinstall the os but as I mostly use it as a server haven't gotten around to it. 
here is the android log
https://paste.kodi.tv/imuxipasek
