### ISSUE TITLE
Kodi crashes when the second screen is powered off

### ISSUE THREAD

**Issue by MrMilk23** [xbmc/xbmc#15244]
### Describe the bug
Here is a clear and concise description of what the problem is:

When Kodi is displayed on my TV (second screen) and is going to be switched off, Kodi crashes

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

That Kodi jumps on the first monitor and continues to run there. 

## Actual Behavior

Crashes immediately

### To Reproduce

1. Kodi Plays something on the second screen
2. Second screen is going to be switched off
3. Kodi crashes

### Debuglog

The debuglog can be found here:
https://pastebin.com/SbaWtRz3

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

In Kodi 17, that didn't happen.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win10 x64 1809
 - Kodi version: kodi-18.0-Leia_rc5.2-x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by TeHaX** [comment]
I reported same issue here [https://github.com/xbmc/xbmc/issues/14843](url)
