### ISSUE TITLE
SMB V2/V3 issue for Kodi Leia on Android

### ISSUE THREAD

**Issue by Hawkedon** [xbmc/xbmc#15241]
### Describe the bug

I'm using Kodi Leia RC5 on both Windows 10 and Android system. There is a SMB file server running on Windows Server to host media files. Due to the security issue of SMB V1, the SMB server only support SMB V2/V3 protocol. Kodi works great on a Windows 10 system with this SMB server, but on Android system the playback usually just freeze and stop after playing about 10 minutes (this time is not fixed, sometimes only several minutes, sometimes around 30 minutes). From the log, I get something like "CVideoPlayerAudio::Process - stream stalled" and "Software caused connection abort"

But if I enable the SMB V1 protocol in the SMB server and set both min and max SMB versions to SMB V1 in Kodi, the playback works fine. It never freeze and stop automatically. It seems there is issue for the SMB client in Kodi to support SMB V2/V3 on Android platform

## Expected Behavior

Kodi should works fine for SMB V2/V3 on Android platform

## Actual Behavior

Kodi just works fine for SMB V1 on Android platform

### To Reproduce

Set the system/software configuration like I described in the question

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android
 - Kodi version: V18 RC5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Thanks much. This is a known issue and as you already found out forcing SMB1 is the only workaround as of now.

**Comment by frankyifei** [comment]
since SMBv1 is not safe, forcing smbv1 is not a good solution.

**Comment by Dnkhatri** [comment]
nvidia shield developers seem to have fixed smb2/3 client for shield if any kodi developer is in contact with them maybe it could be ported to kodi. They have even separated out as a google play updated service so can be easily updated.
https://play.google.com/store/apps/details?id=com.nvidia.shield.nas&hl=en

**Comment by MartijnKaijser** [comment]
Don't think it's all that easy by "just" asking some one else
