### ISSUE TITLE
Kodi does not find TV audio output

### ISSUE THREAD

**Issue by MrMilk23** [xbmc/xbmc#15243]
### Describe the bug
Here is a clear and concise description of what the problem is:

If I start my TV and after that Kodi kodi doesn't find the audio output in the audio settings
1. Start TV (wait a few seconds)
2. Start Kodi and go to the audio settings
3. TV Audio output is not displayed

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

That the TV audio output is displayed

## Actual Behavior

It is not displayed

## Possible Fix

1.Start TV
2.Open Windows Sound settings
3.Start Kodi
4.Now the TV audio output is displayed.

### To Reproduce

1. Start TV (wait a few seconds)
2. Start Kodi and go to the audio settings

### Debuglog

The debuglog can be found here:
Bug: https://pastebin.com/ZkyGvLV2
This is what it looks like if you open the Windows Audio settings first : https://pastebin.com/pPBG1UDz

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I have two monitors. My main monitor and my TV on the Kodi are always running
In Kodi 17, that didn't happen.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win10 64x 1809
 - Kodi version: kodi-18.0-Leia_rc5.2-x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MrMilk23** [comment]
Push

**Comment by MartijnKaijser** [comment]
There's no reason to "push" this issue. Someone will respond when there's time.

**Comment by MrMilk23** [comment]
Still not fixed in 18.1

**Comment by MrMilk23** [comment]
Is there a chance that the bug will be fixed?

**Comment by fritsch** [comment]
Every time you bump it, chances decrease.

**Comment by MrMilk23** [comment]
> 
> 
> Every time you bump it, chances decrease.

bump

**Comment by fritsch** [comment]
Issue won't be fixed this time ... user repeatadly sent mails to more than 40 developers. Let's keep it closed for 4 weeks.
