### ISSUE TITLE
Settings Default Text

### ISSUE THREAD

**Issue by goocreations** [xbmc/xbmc#15253]
### Describe the bug
In the addon's settings, if a text element does not have an ID, it's default value is not displayed. A non-ID element is useful for adding notes to help users. This is only a problem in Kodi 18, previous versions worked perfectly.

## Expected Behavior
The default value should show.

## Actual Behavior
The default values does not show.

## Possible Fix
No idea. 

### To Reproduce
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<settings>
	<category label="category 1">
		<setting type="text" default="This text DOES NOT show" label="Label 1" />
		<setting id="test" type="text" default="This text DOES show" label="Label 2" />
	</category>
</settings>
```

### Debuglog
Nothing in log.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows and Linux
 - Kodi version: Kodi 18 RC5

**Comment by ronie** [comment]
i'm afraid you've been using that addon setting incorrectly..

a setting of type `text` is meant to be used for user input.
see: https://kodi.wiki/view/Add-on_settings#Text_input

for your purpose, you should use a `lsep` setting type.
see: https://kodi.wiki/view/Add-on_settings#type.3D.22lsep.22
