### ISSUE TITLE
Android  app hangs / crashes during startup (only using advancedsettings & MySQL)

### ISSUE THREAD

**Issue by raadoop** [xbmc/xbmc#15269]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have problem with both Android isnstances of Kodi (Android TV 7.0 on Sony and Android 8.0 on Samsung S7) only if I try to use mysql. Kodi opens without problem if no advancedsettings (mysql) added. After adding advancedsettings and sources etc, AndroidTV Kodi crashes and S7 kodi hang. xml files are ok, I.ve taken them from working W10 instances, so it's for sure not a problem with xlm nor with sql database.

This is log from debug mode on Android on S7. I cannot see any problem...

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Andoid instances should work alike W10.

## Actual Behavior

After adding advancedsettings and sources etc, AndroidTV Kodi crashes and S7 kodi hang. xml files are ok, I.ve taken them from working W10 instances, so it's for sure not a problem with xlm nor with sql database.

### To Reproduce

1. start clean Android app
2. add advacedsettings file with mysql
3. Android app crashes or hangs forever

### Debuglog

The debuglog can be found here:
http://pasted.co/d79a28b3

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 7.0 and Android 8.0
 - Kodi version: v18 RC

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
Please enable debug logging for the database component and submit a new log

**Comment by raadoop** [comment]
Here you are. 
http://pasted.co/53d96dea

**Comment by raadoop** [comment]
Is log ok, or should I prepare better one.

**Comment by MartijnKaijser** [comment]
Please try again with latest nightly version
