### ISSUE TITLE
Specific picture sources causing crashes in RPi on Leia RC4

### ISSUE THREAD

**Issue by ParadoxGBB** [xbmc/xbmc#15260]
### Describe the bug

Starting with Kodi Laia builds, picture content taken from my specific camera (a Canon PowerShot SX730 HS) causes a crash on my configuration running Leia RC1 and later RC4 builds on RetroPie 4.4.

I had posted a question asking for clarification from picture support prior to the holidays but decided to escalate here in the new year.

Log is saved here:

https://paste.kodi.tv/aduyahorum.kodi

Problem lines appear to be (in case others are searching for this):

22:37:40.933 T:1460658928   ERROR: COMXCoreComponent::WaitForOutputDone OMX.broadcom.image_encode wait event timeout
22:37:40.933 T:1460658928   ERROR: COMXReEnc::ReEncode smb://192.168.29.3/ScreenSaver/2018/IMG_1428.JPG m_omx_encoder.WaitForOutputDone result(0x80001011)
22:37:40.933 T:1460658928   ERROR: COMXImage::CreateThumb smb://192.168.29.3/ScreenSaver/2018/IMG_1428.JPG 5184x3888 failed to encode
22:37:42.057 T:1800401648   ERROR: COMXCoreComponent:Big GrinecoderEventHandler OMX.broadcom.image_decode - OMX_ErrorStreamCorrupt, Bitstream corrupt
22:37:42.063 T:1681912560   ERROR: COMXCoreComponent::FreeInputBuffers WaitForCommand:OMX_CommandPortDisable failed on OMX.broadcom.image_decode omx_err(0x8000100b) 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Like previous Krypton versions of Kodi, picture viewing, screensaver configurations, etc. should display without booting the user out of Kodi post-crash.

## Actual Behavior

After seconds of delay, Kodi terminates.

### To Reproduce

Sample image that causes the crash is here (it is zipped to help ensure binary integrity):

https://1drv.ms/u/s!ArVgGNNmR7mK2IFHnd0B7B9RV5fByw

### Debuglog

https://paste.kodi.tv/aduyahorum.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Additional information can be found in the Kodi Forums:

https://forum.kodi.tv/showthread.php?tid=338157

And also starting at comment #55 at the RetroPie forums where the builds for Leia were announced to gather testers:

https://retropie.org.uk/forum/topic/19328/testing-kodi-18-0-leia-beta-versions-now-available-for-retropie/55

Thanks to the help there, it's apparent that this crash is Raspberry Pi specific and doesn't reproduce on others' Ubuntu configurations.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ X ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspbian GNU/Linux 9 (stretch) (Kernel: Linux 4.14.79-v7+)
 - Kodi version:  18.0-RC4 Git20181231-d4f08ffds35-dirty). Note that this is provided via the repository at https://github.com/PIPplware/xbmc/tree/leia_new

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Unfortunaltely both logs are not showing Kodi 18 RC4. Kodi 18 RC1. Are you able to get a more recent version?

Not too familiar with the RPi, but are you able to select something else rather than OMX?

I downloaded the picture and it's shown fine on latest Kodi master using Ubuntu on x86. So this might be RPi specific

Probably something where @popcornmix might know best.

**Comment by ParadoxGBB** [comment]
Updated RC4 debug log (it's the same):

https://paste.kodi.tv/ocenavuzug.kodi

In the bug I already confirmed that this appears to be an RPi only issue. I attempted to engage @popcornmix in the forums (link in report).

If someone could assign or escalate here that might move things along.

**Comment by fritsch** [comment]
COMXImage::CreateThumb smb://192.168.29.3/ScreenSaver/2018/IMG_1428.JPG **5184x3888** failed to encode

**Comment by ParadoxGBB** [comment]
Oddly this went away after upgrade to offical. RTM build.
