### ISSUE TITLE
Video playback does not start at beginning of video

### ISSUE THREAD

**Issue by LoneFenris** [xbmc/xbmc#15278]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing certain URLs, playback starts about 4-5 seconds into the video. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Videos should start playback at the beginning of the video

## Actual Behavior

Certain videos start playback 4-5 seconds in.

## Possible Fix

None found so far after trying various display sync settings and trying with hardware acceleration on/off.

### To Reproduce

1. Install Roosterteeth addon
2. Try to play a video from the RWBY series on the Roosterteeth addon
3. Notice that playback starts at the ~4-5 second mark

OR

1. Create a STRM file containing the URL:
 https://rtv2-video.roosterteeth.com/uploads/videos/fa7d12f3-9145-4689-89df-3a38890a8178/NewHLS-1080P.m3u8
2. Try to play it

### Debuglog

The debuglog can be found here:

Using Rooster Teeth addon: https://paste.kodi.tv/qaromavecu

Using STRM file: https://paste.kodi.tv/towifarape

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

It seems that some URLs from at least Roosterteeth may be getting handled incorrectly by Kodi. The same URL used in the STRM file example works correctly in VLC and youtube-dl (ie. the video starts at the beginning, not 4-5 seconds in).

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name: Xbox One X, Windows 10 PC, Android 6 (Razer Forge)
 - Kodi version: 
Discovered in 18 Beta 5 on Xbox One
Still affects 18 RC5 on Xbox One
Reproduced in 17.6 on Windows, Arch Linux, and Android

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by LoneFenris** [comment]
I've tried various permutations of the refresh rate change settings, including turning it off. Nothing seemed to affect the reproducibility of the issue. Note that the audio does not pick up until the same point, as well.

**Comment by LoneFenris** [comment]
I decided to do some more testing with other versions/platforms/displays. 

I had an Android TV box  connected to the same TV as the Xbox with 17.6 installed. Same problem was present there while testing with the Roosterteeth addon.

I then tried installing 17.6 from the Windows Store on my PC (different display) and the problem was present there while testing with Roosterteeth as well. I tried to see if I could replicate the issue with Youtube on my PC, but couldn't seem to definitively reproduce it there during quick testing. 

So I'm now suspecting it may be more isolated to the Roosterteeth addon than I originally thought (at least the worse 4-5 second late starts). I will try to see if I can re-verify on Xbox with the Youtube addon as soon as I can to make sure my original testing with it wasn't a fluke.

**Comment by LoneFenris** [comment]
Alright. After testing with Youtube on my Xbox again, I found that the late starts I was seeing there were in fact due to testing while "Adjust display refresh rate" was on (btw, is there setting to mitigate this, other than turning "Adjust display refresh rate" off?). With it off, I can only still reproduce the problem on the Roosterteeth addon, so I will close this and bring it to the addon author's attention. 

Sorry for any trouble.

**Comment by LoneFenris** [comment]
After investigation, the Roosterteeth addon appears to be providing the correct URL to Kodi. I was able to reproduce the issue outside of the Roosterteeth addon just by putting the URL it provides for an affected video in a STRM file and playing that. I tested the URL in VLC and youtube-dl as well and it worked properly in both. This may simply be a relatively longstanding issue with stream handling on multiple platforms that few video streams expose.

I created a new debug log on Xbox One demonstrating the issue with a STRM file as well. The URL used in the STRM file was https://rtv2-video.roosterteeth.com/uploads/videos/fa7d12f3-9145-4689-89df-3a38890a8178/NewHLS-1080P.m3u8

The STRM file debug log is at https://paste.kodi.tv/towifarape

I've updated the report at the top with this information as well.

**Comment by LoneFenris** [comment]
If it helps, this is another video from Roosterteeth that cuts off a different amount of time from the beginning in Kodi -- only ~2 seconds instead of ~4. 

https://rtv2-video.roosterteeth.com/uploads/videos/06864dd8-0b79-4a41-b785-a0960ba047e1/NewHLS-1080P.m3u8

**Comment by afedchin** [comment]
the issue isn't Xbox related. the same behavior on desktop. @peak3d any thoughts?

**Comment by peak3d** [comment]
What I can say is that the stream is started not from 0 because of:

`16:54:51.405 T:3364    INFO: ffmpeg[D24]:   Duration: 00:06:18.92, start: 1.436889, bitrate: 0 kb/s`

Even if I disable the seek (comment DVDDemux.cpp:1129 ff) stream starts not earlier because dxva decoder can not decode the frames.

The first PTS played is after the seek at ~ 4 secs, not sure if other players don't respect start-time (??)

**Comment by afedchin** [comment]
`16:54:51.405 T:3364 INFO: ffmpeg[D24]: Duration: 00:06:18.92, start: 1.436889, bitrate: 0 kb/s`
iirc `start` means that pts starts not from 0 but from start value and seeking has to consider this.

> stream starts not earlier because dxva decoder can not decode the frames.

dxva isn't used (I didn't see in the log dxva decoder usage)

> The first PTS played is after the seek at ~ 4 secs, not sure if other players don't respect start-time (??)

may be seeking does apply `start` value twice?

**Comment by LoneFenris** [comment]
I will note that other streams with even a larger start value still seem to properly start at or close to zero (and at least qualitatively the same place VLC starts it). I'm not really sure what's different about about the streams like Rooster Teeth's.

example with a start value of 3.092000: http://docs.evostream.com/sample_content/assets/hls-bunny-166/playlist.m3u8

**Comment by LoneFenris** [comment]
I decided to try and download the first .ts file in the m3u8 list with wget and open that in Kodi to see what would happen. 

Opening the .ts file directly with Kodi started the video properly at the beginning. Opening the local .m3u8 file referencing the local .ts file started the video 4-5 seconds in. 

Could there simply be a problem with the m3u8 handling?

**Comment by LoneFenris** [comment]
Just noting that this still seems be present in 18.2

**Comment by fritsch** [comment]
Just noting: Nobody is working on this issue.

**Comment by LoneFenris** [comment]
You say that like it wasn't apparent. Is there harm in keeping an issue up to date?

**Comment by fritsch** [comment]
You send mails to 100 people without any additional value. When issue is
fixed or worked by someone it gets closed or updated.

Kyle Tirak <notifications@github.com> schrieb am Di., 7. Mai 2019, 16:32:

**Comment by LoneFenris** [comment]
Apologies for the email "spam", but I have to ask -- is it common for team members to take up an issue that hasn't been updated in several versions? Speaking as a dev, myself, it's been my experience that issues that become stale tend to be assumed no longer an issue.

**Comment by pkerling** [comment]
> Speaking as a dev, myself, it's been my experience that issues that become stale tend to be assumed no longer an issue.

Yes and no. The first step is that someone must be interested in investigating and solving this bug. Then that person will, if there are any doubts, ask to reconfirm on latest master. As long as no one is working on this, you are just spamming the whole team, unfortunately. And from my experience as a dev, this does not improve your chances of getting this fixed (no offense intended)

**Comment by peak3d** [comment]
@LoneFenris Is it correct the issue can be reproduced with the bucksbunny sample from earlier post?

**Comment by peak3d** [comment]
From kodi log the video posted above fails to decode the first 67 frames (~ 1 second), but starts for me at 1 second. So this seems to be Ok. It's the same using hw or sw decoder (disable DX accelleration in settings::player::Video)

**Comment by LoneFenris** [comment]
@peak3d I captured four logs on 18.2 Linux 

Log 1: https://paste.kodi.tv/obiwocoqaq

Log 1 is using the example URL (the m3u8) in a STRM file. It still shows the issue behavior.

Log 2: https://paste.kodi.tv/uzoqaxuliq

Log 2 is using a direct URL to the first .ts file found in the m3u8 file in Log 1 in a STRM file. It starts properly at the beginning.

Logs 3 and 4 repeat the above tests with hardware acceleration turned off. The same results were found as in Logs 1 and 2, respectively.

Log 3: https://paste.kodi.tv/etiyucapej

Log 4: https://paste.kodi.tv/inapewodom

**Comment by peak3d** [comment]
@LoneFenris this seems to be a ffmpeg issue and should be reported there.
You may see the same issue if you use ffplay to playback the m3u8 stream.

I tested the playlist with inputstream.adaptive HLS after some modifications (pushed, but not released) and the m3u8 playlist starts at beginning.

This is the strm file content:

```
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
https://rtv2-video.roosterteeth.com/uploads/videos/fa7d12f3-9145-4689-89df-3a38890a8178/NewHLS-1080P.m3u8
```
depending on your OS you can pick inputstream.adaptive artifact from here:
https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/master/64/artifacts

**Comment by peak3d** [comment]
Additional note for rooster teeth: The web-site already supports m3u8 master playlists for adaptive bitrate switching. These master playlists are already supported by inputstream.adaptive. I would suggest to contact the addon author to provide the master playlist instead selecting one of those contained.

**Comment by LoneFenris** [comment]
@peak3d I can confirm that with added properties to the STRM file and inputstream.adaptive git build, the issue is not present.

It does not seem to be an ffmpeg issue, however, as the issue does not occur with ffplay. It must be something else handling it wrong.

I will suggest using the master playlists to the addon author. Thanks.

**Comment by peak3d** [comment]
What wonders me is the fact that ffmpeg debug output is so completely different if one compares .ts playback against m3u8 playback, but I don't like ffmpeg diagnostic sessions so it will not be further investigated from me. Maybe @fritsch has some ideas.

Stream start times for ffmpeg are also long even  we playback only a single playlist (not multi bitrate one). This was the main reason for the HLS implementation in inputstream.adaptive.

**Comment by LoneFenris** [comment]
@peak3d I'm not sure if I'm testing the master playlist right as it doesn't seem to be using inputstream.adaptive automatically (or at least, it still shows the issue, even with inputstream,adaptive git). 

I put the following URL, which from my understanding is the master m3u8 as it contains the playlists for the different qualities, in a strm file: 

https://rtv2-roosterteeth.akamaized.net/uploads/videos/fa7d12f3-9145-4689-89df-3a38890a8178/index.m3u8

Are the kodiprop lines still needed? Would the addon need to set those somehow as well? Or am I still using the wrong m3u8?

**Comment by peak3d** [comment]
@LoneFenris yes, they must be set, if not, ffmpeg is used (and with master playlists ffmpeg is slow starting)

example: https://github.com/liberty-developer/plugin.video.prime_instant/blob/master/default.py#L767-L772

**Comment by LoneFenris** [comment]
@peak3d Got it. Thanks.
