### ISSUE TITLE
Unable to handle skipping when 2ch Dolby audio - Fire TV

### ISSUE THREAD

**Issue by capGrundy** [xbmc/xbmc#15270]
### Describe the bug
Here is a clear and concise description of what the problem is:

If video content contains Dolby 2ch audio, you are using audio passthrough settings for AC3, and you try to skip forwards or backwards, play does not continue.  You can stop and restart and play is fine.  All other content (Dolby 5.1, AAC 2ch, etc) do not suffer this issue.  Switching to PCM allows for normal behavior.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

e.g., When watching a show, skipping the opening credits works, and play continues when skips are completed.

## Actual Behavior

The skipping does occur, but is now in a frozen/paused state.  It is trying to play, as if the skip is right at the beginning/end of a second tick on the time bar, you can see it flick back and forth like a car tire spinning in the snow. 

## Possible Fix

Aside from a technical solution that addresses the specific bug, maybe allowing custom rules for passthrough settings.  e.g., if 2ch Dolby, disable AC3 passthrough setting. 

Also, 2 CH AC3 is played as 5.1 CH on receiver.  But, playing an mp3 2 CH shows as 2 CH.  It is possible that there is a default of 5.1 being set on AC3, and the confusion when it is actually only 2 CH is causing the hangup. 

### To Reproduce

1. Be set up for audio passthrough.  No of channels 2, Upmix off, Allow passthrough On, DD and DTS capable receiver On
2. Play a video file with 2 CH Dolby audio
3. Press left or right on the dial on a Fire remote.

### Debuglog

The debuglog can be found here:
https://drive.google.com/open?id=1GOuAPktrc59eefopltJ3j6io59Ysovqn

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 1.7.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
It seems you have to login into google to read that debuglog. Could you please use some paste service, such as paste.kodi.tv or pastebin or whatever paste service you prefer.

Thanks

**Comment by capGrundy** [comment]
https://paste.kodi.tv/ogehufiyun.kodi

I also fixed the settings on Drive:
https://drive.google.com/file/d/1GOuAPktrc59eefopltJ3j6io59Ysovqn/view?usp=sharing

**Comment by DaVukovic** [comment]
That's not a full debuglog from Kodi start. 

Please submit the full log.

**Comment by capGrundy** [comment]
Sorry, first time reporting.  New log:

https://paste.kodi.tv/obobaqalaf.kodi

**Comment by MartijnKaijser** [comment]
Sorry but you are running v17 and we only accept GitHub issues for v18. Please upgrade to latest v18 version and try again or ask the question on the forum.
Closing this for now
