### ISSUE TITLE
Empty bottom row in TV guide 

### ISSUE THREAD

**Issue by Paulemann** [xbmc/xbmc#15271]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using Estuary as the default skin and setting guide viewtype to "Horizontal channels, no group selector" you get an extra blank bottom row in the tv or radio guide which is not present when setting viewtype to "Horizontal channels". 
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I'd expect the bottom row to display info of the last channel in the current group ("All Channels").
## Actual Behavior

Looks the "No group selector" setting causes the addition of an extra blank line at the bottom of the tv or radio guide
### To Reproduce

1. Select Estuary as your interace skin
2. Go to TV or Radio section
3. Select Guide
4. Call Channel View Options (Press "<")
5. Set Viewtype to "Horizontal channels, no group selector"
6. Scroll guide down and look at bottom row
### Debuglog

No debug log attached as this is rather a "cosmetical" than a "functional" issue,

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04 Server
 - Kodi version: Kodi 18 RC 5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
I tried to replicate the issue on Win10 platform and was unable to. Though I did have trouble with your Step 5 as I do not have the option **no group selector**

Please post a screenshot of the issue, as well as a debug log to gather more info about your setup.

**Comment by Paulemann** [comment]
Yes, that's it. As I mentioned, it seems to be only a "cosemetical" issue, nothing that affects functionality. Just noticed it and tried to bring it to your attention.
