### ISSUE TITLE
FireStick 4K GUI resolution limit is affecting video playback resolution

### ISSUE THREAD

**Issue by FoxForce5ive** [xbmc/xbmc#15285]
Here is a clear and concise description of what the problem is:

GUI resolution limit is affecting video playback resolution.

When GUI resolution limit is set to Auto, 3840x2160 files play at 1920x1080 (with the exception of 3840x2160 that are 60hz,which play at 3840x2160), files in lower resolutions play at their correct resolutions regardless of their frame rate.

When GUI resolution limit is set to Unlimited, 3840x2160 files play at 3840x2160, files in lower resolutions all then also play at 3840x2160, at their correct frame rate.

## Expected Behavior

Regardless of GUI resolution limit, the file should always switch to the correct resolution of the file.

## Actual Behavior
The file resolution only actually switches resolution if Auto is selected on GUI resolution limit, & if the file is 1920x1080 or lower. Any 3840x2160 files will play only at 1920x1080 (with the exception of 3840x2160 that are 60hz, which play at 3840x2160).

## Possible Fix
Unsure, as the logs (to my untrained eye) seem to show Kodi switching the resolution, whereas it is not actually doing so (as both my eyes & the signal info on my TV show me).

### To Reproduce
1. Ensure Display refresh rate is set to Start/Stop & GUI resolution limit is set to auto
2. Try to open a 3840x2160 file that is not 60hz (such as a movie at 24fps),
3. Check the resolution of TV signal & see 1920x1080 is actually being displayed.

## The debuglog can be found here:

With GUI Resolution Limit set to Auto:
https://paste.kodi.tv/itagovaxih.kodi

With GUI Resolution Limit set to Unlimited:
https://paste.kodi.tv/obukakuhuq.kodi

## Other information that may be relevant:
One other user has reported this in the Firestick 4K thread back in November:

https://forum.kodi.tv/showthread.php?tid=336151&pid=2792228#pid2792228:

I have all resolutions added to the whitelist.

I have attempted this on the last few nightly builds (as of today January 18 2019), & the results have remained exactly the same.

Interestingly, when trying to play a 3840x2160 test file which is 60hz, (the well known LG Chess demo), the correct resolution is displayed even when GUI resolution is set to Auto, so to reproduce the issue you may need to use a file that has a lower frame rate such as a movie.

Despite the resolution being incorrect when you try to play a 3840x2160 file, the frame rate is correct & HDR is working.

Used Operating system:
Firestick 4K
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android/Fire OS
 - Kodi version:18.0-RC5

**Comment by lrusak** [comment]
```
16:42:37.495 T:18446744071738239264    INFO: ffmpeg[8A802920]:     Stream #0:0(eng): Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 1k tbn, 24 tbc (default)

<snip>

16:42:37.526 T:18446744071738239264   DEBUG: Matched exact whitelisted Resolution 3840x2160 @ 24.000000 - Full Screen (26)
16:42:37.528 T:18446744071738239264  NOTICE: Display resolution ADJUST : 3840x2160 @ 24.000000 - Full Screen (26) (weight: -0.000)
16:42:37.553 T:18446744071957911840   DEBUG: CAndroidUtils: SetNativeResolution: 10: 1920x1080 3840x2160@24.000000

<snip>

16:42:40.563 T:18446744071957911840   DEBUG: Trying to find exact refresh rate
16:42:40.566 T:18446744071957911840   DEBUG: No exact whitelisted resolution matched, trying double refresh rate
16:42:40.567 T:18446744071957911840   DEBUG: No double refresh rate whitelisted resolution matched, trying current resolution
16:42:40.568 T:18446744071957911840   DEBUG: Matched fuzzy whitelisted Resolution 1920x1080 @ 24.000000 - Full Screen (31)
16:42:40.568 T:18446744071957911840  NOTICE: Display resolution ADJUST : 1920x1080 @ 24.000000 - Full Screen (31) (weight: -0.000)
16:42:40.572 T:18446744071957911840   DEBUG: CAndroidUtils: SetNativeResolution: 15: 1920x1080 1920x1080@24.000000
```

I think what is happening is when you have the gui limit to auto or 1920x1080 and kodi doesn't find an exact resolution then kodi will try to match the current resolution (which I think takes the gui limit value).

I'm not exactly sure how this is expected to work but if you want to be able to limit the gui but still play 4k videos at the proper resolution then I think we need to tweak the selection logic.

@fritsch or @peak3d can probably weigh in here

**Comment by fritsch** [comment]
```
16:42:37.528 T:18446744071738239264  NOTICE: **Display resolution ADJUST : 3840x2160 @ 24.000000** - Full Screen (26) (weight: -0.000)
```

Is it gone? After it was found?

**Comment by FoxForce5ive** [comment]
My set can play 3840x2160 24fps though, & does just that when the gui resolution is set to unlimited. 

It seems to find the resolution & match it, but then sets the resolution to match the gui when set to auto/1080 regardless. 

When you set the gui to unlimited it will play at 3840x2160 at 24fps, but then it will also play 1080p & 720p content at 3840x2160 also, I'm not familiar at all with reading these logs but I can't see that noted on the logs (in the second/unlimited gui log) when I played a 1080p & 720p file after the 3840x2160 file.

**Comment by lrusak** [comment]
If you want to play 1080p media at 1080p or 720p media at 720p then you need to whitelist those resolutions in the whitelist

**Comment by Kwiboo** [comment]
I think gui limit is implemented in a similar way as amlogic and my rockchip-hdr branch (using iWidth and iScreenWidth) for android, you will need something like https://github.com/Kwiboo/xbmc/commit/9c48072b453b486b047f6cfb97e080dafef065b8 to get correct resolution selected.

**Comment by peak3d** [comment]
@FoxForce5ive I don't see any issue in the unlimited log file:

- you played 3 videos (4k / 1080p / 720p) and for all kodi switched to the correct mode:

16:36:56.612 T:18446744071957911840   DEBUG: CAndroidUtils: SetNativeResolution: 10: 3840x2160 3840x2160@24.000000
...
16:37:25.970 T:18446744071957911840   DEBUG: CAndroidUtils: SetNativeResolution: 14: 1920x1080 1920x1080@23.976000
...
16:38:08.114 T:18446744071957911840   DEBUG: CAndroidUtils: SetNativeResolution: 18: 1280x720 1280x720@50.000000

**Comment by peak3d** [comment]
@Kwiboo verified that your commit works for android, do you want to PR ? Or should I (crediting you) ?

**Comment by peak3d** [comment]
@FoxForce5ive  seems your device / your settings let Android compute a bigger display size of your movie:

```
16:37:28.664 T:18446744071572027680   DEBUG: CDVDVideoCodecAndroidMediaCodec:: width(1920), height(1088), stride(1920), slice-height(1088), color-format(2130706433)
16:37:28.664 T:18446744071572027680   DEBUG: CDVDVideoCodecAndroidMediaCodec:: crop-left(0), crop-top(0), crop-right(1919), crop-bottom(1087)
CRenderManager::Configure - change configuration. 1920x1088. display: 1934x1088. framerate: 23.98.
```

On my 4K display / GUI set to unlimited it looks like that:

```
22:15:30.031 T:2971   DEBUG: CDVDVideoCodecAndroidMediaCodec:: width(1920), height(1088), stride(1920), slice-height(1088), color-format(2130706433)
22:15:30.032 T:2971   DEBUG: CDVDVideoCodecAndroidMediaCodec:: crop-left(0), crop-top(0), crop-right(1919), crop-bottom(1087)
CRenderManager::Configure - change configuration. 1920x1088. display: 1920x1080. framerate: 30.00.
```
This is caused of a display aspect ratio which is slightly different than mine.
Could be sream related / ffmpeg related / or related to screen settings / calibration.

Have you changed something in calibrations? If not, can you share some MB of the 1080p stream you use for testing?

**Comment by FoxForce5ive** [comment]
The TV aspect ratio setting in the TV itself is greyed out (locked) to 16:9 when using the firestick, otherwise I'd set it to direct, or untouched as I usually do with kodi devices to ensure I get a true pixel to pixel image. 

The firestick unfortunately doesn't have an aspect ratio setting, just a calibration screen not dissimilar to the video calibration screen in kodi with four arrows to adjust size. 

I can trim a part of the file, but it does it with every single 1080p or 720p file I try, so I doubt that will help. I have a windows kodi htpc which I use as my daily machine & that plays those same files correctly on the same TV.

As someone else had the same problem might it be the firestick display calibration causing the issue? Just spit balling obv, as I struggle to think of another culprit.

**Comment by peak3d** [comment]
@FoxForce5ive 
From code your display sizes should not occur, I triggered a test-build: https://jenkins.kodi.tv/job/Android-ARM/12673/

If this is finished, pls. install this version and play one 1080p stream (regardless if Auto or unlimited) and provide the debug log afterwards, thx!

**Comment by peak3d** [comment]
@FoxForce5ive there is a new test-build here: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20190123-6d3fce0a-aspect-armeabi-v7a.apk

It will most likely work, but I need the log to see why the stream forces the aspect ration (what my streams never do)

**Comment by FoxForce5ive** [comment]
Debug Log with that test-build:
https://paste.kodi.tv/sinivomoge.kodi

Unfortunately, it made the image 'squashed' centrally to less than a third of the screen.

Screenshot here:
https://ibb.co/9YXwZdd

**Comment by FoxForce5ive** [comment]
FWIW, it's the first build that will play 4k, 1080p, & 720p all at the correct resolution & frame rate automatically whilst Unlimited is set as the GUI resolution limit.

**Comment by peak3d** [comment]
The log file is still from old apk : Starting Kodi (18.0-RC5 Git:20190123-**9555f4d**). Platform: Android ARM 32-bit

**Comment by peak3d** [comment]
http://mirrors.kodi.tv/test-builds/android/arm/kodi-20190123-3f418def-aspect-armeabi-v7a.apk

**Comment by FoxForce5ive** [comment]
Apologies, too many logs in the same folder.

This is the log when unlimited is set in GUI resolution limit:
https://paste.kodi.tv/betabimuwe.kodi

When Auto is set as GUI resolution limit:
https://paste.kodi.tv/ogojegogih.kodi

**Comment by peak3d** [comment]
Ok, thx, so from log the streams tell kodi that the aspect ratio should be "forced".
What kind of threams are these? Self decoded? Rips from DVD?

IIRC this is an option when encoding (recording) the streams, For my streams this is false, so I wonder why it is set in your case.

---

Have you realized the new apk link 2 posts above?

**Comment by FoxForce5ive** [comment]
The counterpart file is an Amazon web rip, not ripped by myself.

I hadn't spotted that new apk, will test shortly.

I have a Bluray 1080p rip I will use to test this one.

I can't help but wonder if the fact I cannot change my TV set's aspect ratio when using the firestick is involved somehow (I can when using the set with every other device I own) in that the firestick4k 'locks' the aspect ratio. Are you testing using a firestick4k or a different android device? If you're using the firestick4k & don't have the same problem then obviously that's not the issue,

**Comment by peak3d** [comment]
The current issue is not related to the device / tv, its a pure stream only issue.
Android returns the correct video dimensions after analyzing the video stream,

Only difference is that for you the aspect calculation in MediaCodec is skipped because the stream tells that aspect ratio is forced. Thats not true for the videos I play (mainly addon related content over inputstream.adaptive which does not set the flag)

**Comment by FoxForce5ive** [comment]
The latest test-build log when GUI set to Auto:
https://paste.kodi.tv/ihililebod.kodi
When set to Unlimited:
https://paste.kodi.tv/usojaselit.kodi

I hear you about the streams, & whilst I don't understand the technical side at all, I get the explanation enough to understand. It's good news in that it's not a hardware constraint, bad news in that the files I'm using are almost certainly the most commonly used in our community, web/tv rips & bluray/UHD Bluray rips,

**Comment by peak3d** [comment]
@FoxForce5ive I cannot help for your 4K stream, if container (mkv) has incorrect information, we cannot avoid the double display refresh. Pls. make sure / resample your videos correctly if you have still issues after the PR is merged.

**Comment by FoxForce5ive** [comment]
No, the last apk still has the same problem.

To clarify, if Auto GUI resolution limit is set, 1080p files all play at 1080p, & 720p at 720p, but some 3840x2160 files (like a UHD Bluray rip), play at 1080p also.

If Unlimited GUI resolution limit is set, 1080p & 720p files all play at 3840x2160, & 3840x2160 files play at 3840x2160 also.

I've just had a thought which may explain the issue with Auto not switching & fits in with what you're saying regards the aspect ratio being forced. 

The UHD rips I'm having trouble with are all films that have a 21:9 ratio. They're ripped excluding the black bars (this is usually done as standard to keep the file size lower without losing image quality) so the file has a different height resolution, meaning it falls back to the native Kodi resolution. The test file I've been using has the resolution of 3840x1608.

If I understand your pull request, that would seemingly fix this issue.

**Comment by peak3d** [comment]
Next try, pls play 1080 video with unlimited:

http://mirrors.kodi.tv/test-builds/android/arm/kodi-20190123-20b736e9-aspect_test-armeabi-v7a.apk

and provide the log, thx

**Comment by peak3d** [comment]
If its easier to you, pls, provide some MB of the 1080p stream, either here or something like dropbox and provide the link to it via mail.

**Comment by peak3d** [comment]
@FoxForce5ive unfortunately there are limits on our side t fix you stream definition.
For example the last investigated stream is tagged as 1920x1032 in mkv contaier, but decoded frames are 1920x1088 (which is out of bounds 1920x1080 TV resolution.

That your tests succeeds with GUI limit set to Auto (what is 1080p) is wrong and will be fixed.
The only offer I can do is trying to make whitelist search more fuzzy, but there are limits, too.

Maybe it would be also an idea that you change the source of your video streams if resloution switch is important for you :-)

**Comment by FoxForce5ive** [comment]
Ok, that makes sense.

Thanks for your time & effort, it's most appreciated!

**Comment by peak3d** [comment]
@FoxForce5ive you can try this PR https://jenkins.kodi.tv/job/Android-ARM/12704/artifact/kodi-20190124-d4c59da5-PR15318-merge-armeabi-v7a.apk and look how many issues it solves for you....

**Comment by peak3d** [comment]
Fixable issues solved in https://github.com/xbmc/xbmc/pull/15318

**Comment by robbyfine** [comment]
Personally , I watch 4k content through my FireStick. I installed some great  Supremacy Kodi addon that allows 4K content.Supremacy offers an incredible library of 4K movies that you can stream in just a few clicks. If you need some recommendations concerning installation, you may find this resource pretty useful https://www.firesticktricks.com/best-kodi-addons.html . By the way,  the majority of 4K Kodi addons bring HD content as well, and Supremacy is no an exception. Good luck!

**Comment by MartijnKaijser** [comment]
We do not support that piracy junk.
