### ISSUE TITLE
Play Using to DLNA audio receiver

### ISSUE THREAD

**Issue by pmar999** [xbmc/xbmc#15287]
## Kodi default volume setup in guisettings.xml audio <fvolumelevel>1.0</fvolumelevel> is highly excessive.

**Detailed Description**
Imagine when you just install Kodi and make a first trial, there is risk of destroying your external audio speakers or waking up your neightbors ! This make a shock ! I tested it on DLNA Audio and also on TV.

**Suggestion**
You should simply set it up to <fvolumelevel>0.5</fvolumelevel> and guide the user how to increase it if not sufficient.

**Comment by MartijnKaijser** [comment]
Please make feature requests on the forum

**Comment by pmar999** [comment]
> 
> 
> Please make feature requests on the forum
Hello Martijn, I am new here. Where exactly should I push the feature request, which forum. I thought I was on the Kodi forum via Github..
