### ISSUE TITLE
Audio DLNA - does not play the selected song but other song

### ISSUE THREAD

**Issue by pmar999** [xbmc/xbmc#15291]
### Describe the bug
Audio DLNA - does not play the selected song but another one

## Expected Behavior
DLNA renderer is standby mode. I launch KODI, select song=A. Kodi switches on the renderer.
Kodi shall play the selected song=A.

## Actual Behavior
Kodi does play another song=B !!!

Remark 1: once Kodi is launched and the renderer is switched on, the renderer remote (android app) does manage Kodi audio library without any issue.

Remark 2: I was also using foobar2000 in exact same configuration, and foobar2000 interface on Windows7 does manage songs playback to same DLNA renderer without any issues.

### Debuglog

https://paste.kodi.tv/kaxerawici.kodi

### Your Environment
Used Operating system:
  -Kodi installed on Windows 7 x64
  -Kodi version: kodi-18.0-Leia_rc5.2-x64
  -Kodi DLNA mode active...
  -Connection: Wifi

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Do I get this right....you want to play `Rollercone - Daydreaming`, but Kodi plays "Sun Trust - How Insensitive"?

**Comment by pmar999** [comment]
I did post into the Debuglog file header:
1- DLNA renderer = Yamaha RN-602 audio player is STAND-BY OFF
2- I launch KODI/ Select Music song= "Electronic\Claude Challe\Buddha Bar II - Party & Dinner\01 - Sun Trust - How Insensitive.mp3"
3- Kodi then switches ON the renderer
4- The renderer does not play the selected song (above line 2), but plays 'Electronic\Air\The Virgin Suicides\04 - Cemetary Party.mp3'

The generated logfile corresponds to exact above operations (so both Kodi and renderer started from Off state). It seems like the DLNA server receives some 'remaining' requests (may be from the renderer?).
