### ISSUE TITLE
Kodi crashes with access violation when restoring full screen

### ISSUE THREAD

**Issue by Dave-Lowndes** [xbmc/xbmc#15295]
## Bug report
Kodi crashes with an access violation when restoring full screen after switching AV receiver to standby.

### Describe the bug
I have Kodi running on a Windows 8.1 PC connected via HDMI to a Denon AV receiver, and from there via HDMI to a Samsung TV.

With Kodi running full screen, if I switch off (put into standby) the AV receiver, it passes the HDMI through to the TV.
At this point the Kodi display is corrupted - texts are shown with the top cut off, and the Windows task bar appears over Kodi.
If I use Alt+Enter to restore Kodi to full screen, it repaints correctly, but then immediately crashes with an access violation.

Here are the event logs records:
Faulting application name: kodi.exe, version: 17.9.952.0, time stamp: 0x5c3a4875
Faulting module name: kodi.exe, version: 17.9.952.0, time stamp: 0x5c3a4875
Exception code: 0xc0000005
Fault offset: 0x0000000000684439
Faulting process ID: 0x728
Faulting application start time: 0x01d4b0ad2823dec0
Faulting application path: C:\Program Files\Kodi\kodi.exe
Faulting module path: C:\Program Files\Kodi\kodi.exe
Report ID: 7ba9fd63-1ca0-11e9-bec0-902b34196d12
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket 1416888504389535875, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: kodi.exe
P2: 17.9.952.0
P3: 5c3a4875
P4: kodi.exe
P5: 17.9.952.0
P6: 5c3a4875
P7: c0000005
P8: 0000000000684439
P9: 
P10: 

Attached files:
C:\Users\MediaUser\AppData\Local\Temp\WER1EF.tmp.WERInternalMetadata.xml

These files may be available here:
C:\Users\MediaUser\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_kodi.exe_4a44e1d9a72bb87f4901bf569259d6fbd0582d_49ffe117_0903177b

Analysis symbol: 
Rechecking for solution: 0
Report ID: 7ba9fd63-1ca0-11e9-bec0-902b34196d12
Report Status: 0
Hashed bucket: f3ce538baf5605f673a9cc9676790883

## Expected Behavior
It shouldn't crash.

## Actual Behavior
It crashes.

## Possible Fix
N/A

### To Reproduce
See the bug description above.

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/atacuqagij.kodi

### Your Environment
Used Operating system:
 - [X] Windows

 - Operating system version/name: Windows 8.1 (fully updated)
 - Kodi version: 18 RC5

**Comment by Dave-Lowndes** [comment]
Still happens with 18.1 FWIW

**Comment by emveepee** [comment]
I see this regularly too on resume and since I often run Kodi in the debugger the line that fails is in CharsetConverter.cpp

std::string FromW(const std::wstring& str)
{
  return FromW(str.c_str(), str.length());
}

Unhandled exception thrown: read access violation.
**str** was 0x20. occurred
