### ISSUE TITLE
 Kodi not reading some languages codes right

### ISSUE THREAD

**Issue by Essam315** [xbmc/xbmc#15308]
### Describe the bug
Kodi reads some languages codes wrong if they are in this way "pt-BR" (Brazilian Portuguese) and "es-ES" (European Spanish), it reads "pt-BR" as "Portuguese - Breton" and reads "es-ES" as "Spanish - Spanish", it reads the abbreviation "BR" as the language "Breton" when it should read it as the country "Brazil" and reads "ES" as "Spanish" instead of the country "Spain", and this leads to choosing the wrong language for the audio and subtitles (usually chooses the default language), it should read the codes the same way it does in "ar-EG", Kodi reads it as Arabic, "EG" is the abbreviation of the country Egypt.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix

I noticed that this problem happens only when there are a country and a language have the same abbreviation like "br" for "Brazil" and "br" for "Breton", and "es" for "Spain" and "es" for "Spanish", in this case Kodi chooses the language instead of the country, the fix for this problem might be by making Kodi considers any abbreviation after "-" is a country code.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

Here is the debug log for "Spanish" "es-ES" after downloading the language from 'Download" then "Look and Feel", then "languages", then "Spanish", and choosing "Spanish" for the preferred audio and subtitle, then running the first episode from the TV show "Elite".

It downloads

C:\Users\Essam\AppData\Roaming\Kodi\addons\resource.language.es_es

https://pastebin.com/b5bNZgbG

and here are "manifest.json" and "manifest.mpd" for this episode

[manifest.es-ES.zip](https://github.com/xbmc/xbmc/files/2784689/manifest.es-ES.zip)

Here is the debug log for "Portuguese (Brazil)" "pt-BR" after downloading the language from 'Download" then "Look and Feel", then "languages", then " Portuguese (Brazil)", and choosing "Portuguese (Brazil)" for the preferred audio and subtitle, then running the first episode from the TV show "3%".

It downloads

C:\Users\Essam\AppData\Roaming\Kodi\addons\resource.language.pt_br

https://pastebin.com/RMJVNNyj

and here are "manifest.json" and "manifest.mpd" for this episode

[manifest.pt-BR.zip](https://github.com/xbmc/xbmc/files/2784691/manifest.pt-BR.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://i.ibb.co/cDxKGxW/1.jpg

https://i.ibb.co/RQXXyTY/2.jpg

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

This problem is with Kodi 18 Leia RC, Windows 10, and this Netflix plugin (using paid subscription in the official Netflix site).

https://github.com/asciidisco/plugin.video.netflix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MediaBrasil** [comment]
PT-br issue is ausence language support in utils\LangCodeExpander.cpp, need included suport for pt-br and pob for work fine.

{ "pb", "pob", NULL, NULL},

{ "pb", "pob" },

{ MAKECODE('\0','p','o','b'), "Portuguese (Brazil)" },

{ "pb", "pob", NULL, NULL},

WIth code added, no more unknow language or subtitle when playing video.

But probably need more work, I changed one line plugin video netflix for work fine, work for me and now language and subtitle is fine (Portuguese Brazil)..using version 1.4.0 addon I change converter.py file in msl folder , line 83 to

return xml.replace('pt-BR', 'pob').replace('\n', '').replace('\r', '')

@Essam315 and @enen92. Hope this info help a little solve properly.

**Comment by scott967** [comment]
If a decision is taken to open LangCodeExpander, ask that consideration be given to parsing language tags formed IAW IETF BCP-47.  Implementations of BCP-47 parsers can be found for eg Python (language-tags 0.4.6).  Basic well-formed language tags consist of subtags 2ALPHA language ISO 639-1 and 3ALPHA ISO 639-2 only when 2-letter code does not exist) hyphen 4ALPHA (script ISO 15924 minimum should support Hans, Hant, Cyrl, Latn) hyphen 2ALPHA (region ISO 3166-1).  For Kodi M**** recommend UI support for displaying appropriate labels for language and script.
