### ISSUE TITLE
Kodi log file records does not contain a date or timestamp, only time

### ISSUE THREAD

**Issue by RomanGatchenko** [xbmc/xbmc#15304]
### Describe the bug
Kodi log file records does not contain a date or timestamp, only time

## Expected Behavior
The presence of the date of the event in the file line

## Actual Behavior
Only time is recorded, no timestamp or date.

> 15:21:46.397 T:1945555616  NOTICE:

## Possible Fix
Add date or timestamp to kodi.log file 
For example:

> \utils\log.cpp CLog::WriteLogString

`  strData = StringUtils::Format(prefixFormat,
                                  hour,
                                  minute,
                                  second,
                                  static_cast<int>(millisecond),
                                  (uint64_t)CThread::GetCurrentThreadId(),
                                  levelNames[logLevel]) + strData, timestamp;`

### To Reproduce
1. Open  kodi.log file 

### Your Environment
Used Operating system:

 - [X] Android
 - [X] iOS
 - [X] Linux
 - [X] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [X] Windows UWP

 - Operating system version/name:
 - Kodi version:
All versions

**Comment by DaVukovic** [comment]
Feature requests should be made at the Kodi forums. A non existing feature is not a bug. This might be debatable in some cases, but not in this case, I would say ;).

Open a feature request at the Kodi forums or feel free to PR something to improve the actual logging behaviour.

**Comment by JimmyS83** [comment]
@RomanGatchenko I added [PR](https://github.com/xbmc/xbmc/pull/15456) to this. It actually bothered me since beginning but finally decided to do something with it :)  @DaVukovic, is this OK?

**Comment by DaVukovic** [comment]
Sure, PRs are always welcome ;) 

Not saying that it will be accepted ;)
