### ISSUE TITLE
Overlapping text in SliderEx control in DialogAddonSettings.xml

### ISSUE THREAD

**Issue by jurialmunkey** [xbmc/xbmc#15302]
### Describe the bug
In DialogAddonSettings.xml - for control="sliderex" the text overlaps the slider.

## Expected Behavior
Long text should be truncated so that it does not overlap the slider control.

## Actual Behavior
Long text overlaps the slider control.

### To Reproduce
1. Open the Settings of the UpNext addon - the slider control in this addon is a good example.

### Screenshots 
![screenshot006](https://user-images.githubusercontent.com/4618719/51460449-9c48a680-1daf-11e9-979c-f5a6e21c2080.png)

## Additional context
This bug affects all skins, not just Estuary. The bug was not present in previous versions of Kodi.
This bug is not a skin issue - it is an issue with how Kodi is handling this control.
It is possible (likely) that this bug is present in other Dialogs/Windows that use the sliderex control.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18 RC 5.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
as a workaround, skins can define a `<textwidth>` to avoid this problem

**Comment by HitcherUK** [comment]
Can't this be automatic like radio buttons where the position and width of the texture are used to adjust the length of the label?

**Comment by HitcherUK** [comment]
This has been fixed.
