### ISSUE TITLE
Re-enable "Mark as watched" on folders in file mode when content is "none"

### ISSUE THREAD

**Issue by Nostalgist** [xbmc/xbmc#15324]
### Describe the bug
Here is a clear and concise description of what the problem is:

If no library is set up, the option to mark a whole folder as watched/unwatched by either pressing "w" or context menu is missing since Kodi 17. Doing this with single files still works.

The Trac ticket should explain the problem better.

Forum discussion: https://forum.kodi.tv/showthread.php?tid=311447
Trac ticket: https://trac.kodi.tv/ticket/17744

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

"w" on folder --> all files marked as watched/unwatched

## Actual Behavior

"w" on folder --> nothing happens

### To Reproduce

1.  Go to videos and browse to a folder with video files inside
2. Make sure content is not set to anything other than "none", or better: use a fresh install with no library set up
3. right click and "see" the missing option

### Debuglog

The debuglog can be found here:
(collected on a clean/fresh install of Leia RC5.2)
https://paste.kodi.tv/masipokahu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - Windows

 - Operating system version/name: 10, but this bug is OS independent
 - Kodi version: Leia RC5.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by LeeThompson** [comment]
Would love this functionality.  (And also have it on the context menu)

**Comment by abhijeetgaiha** [comment]
This is a regression from older versions. The workarounds are not great either. I have resorted to removing and adding sources entirely.

**Comment by DaVukovic** [comment]
for v18 this issue has been fixed by: 
https://github.com/xbmc/xbmc/pull/18024

**Comment by abhijeetgaiha** [comment]
Thank you.
