### ISSUE TITLE
Refresh rate randomly reverts to default setting

### ISSUE THREAD

**Issue by smp79** [xbmc/xbmc#15338]
### Describe the bug
Here is a clear and concise description of what the problem is:

This is a very old issue - I see this since early Kodi 17 alpha builds. I use PVR a lot and all TV channels are 50Hz. I use the auto refresh rate switching feature but I manually set the refresh rate to 50Hz, so Kodi would start at 50Hz rather than default 60Hz.
The issue: sometimes it reverts back to default 60Hz for no apparent reason. This usually happens after Kodi crash, sometimes after a normal system/Kodi restart. I have no idea how to reliably reproduce this. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When I set System-->Refresh rate to 50Hz I expect it to always stay at 50Hz.

### To Reproduce

Crash Kodi multiple times, reboot the device multiple times. 

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ahuluwolor.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC
 - Kodi version: 18, current master

**Comment by paol** [comment]
I've seen this happen too. In my case I'm on Linux, and my TV reports 50Hz as preferred mode, but I set it to 60Hz in the kodi settings.
From time to time it reverts itself to 50Hz, not sure what causes it. It's fairly rare, Id say it happens to me less than once a month.
