### ISSUE TITLE
Crash when pressing filter button in episode view

### ISSUE THREAD

**Issue by hugegreenbug** [xbmc/xbmc#15336]
### Describe the bug

Kodi crashes on Android after navigating to the tv shows, selecting a show, selecting a season, and then pressing the filter button.

## Expected Behavior

It shouldn't crash and it should show the filter options.

## Actual Behavior

It crashes.

### To Reproduce

1. Select tvshows
2. Select a show
3. Select a season
4. Press the filter button

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/2798607/kodi.log)
[logcat.log](https://github.com/xbmc/xbmc/files/2798608/logcat.log)

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.0-RC5 Git:20190123-1d6010c

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Please upload your log to a pastebin site, preferably https://paste.kodi.tv/

**Comment by hugegreenbug** [comment]
Kodi Log: https://paste.kodi.tv/racedefeqa.kodi
Logcat log: https://paste.kodi.tv/akeginegad.kodi

**Comment by thezoggy** [comment]
I can confirm this causes the crash on windows as well. same entries logs (nothing helpful):
```
00:17:28.470 T:9492   DEBUG: CInputManager::HandleKey: return (0xf00d) pressed, action is Select
00:17:28.470 T:9492    INFO: Loading skin file: DialogSettings.xml, load type: KEEP_IN_MEMORY
00:17:28.474 T:9492   DEBUG: ------ Window Init (DialogSettings.xml) ------
00:17:28.474 T:9492   DEBUG: CSettingsManager: requested setting (filter.episodes.30) was not found.
00:17:28.474 T:9492   DEBUG: CSettingsManager: requested setting (filter.episodes.41) was not found.
00:17:28.474 T:9492   DEBUG: CSettingsManager: requested setting (filter.episodes.97) was not found.
```

**Comment by ssweeper** [comment]
Any news here? Still running into the same issue (fire-tv & windows) i kodi 19.1.

**Comment by thexai** [comment]
Can you test if issue still exist in v21 beta2?

https://mirrors.kodi.tv/releases/

**Comment by thexai** [comment]
I can't reproduce in latest master

**Comment by thezoggy** [comment]
testing on latest nightly, filter seems to work. but woof trying to filter by year is awful. the ui hitches on any change so it tries to apply said filter and makes trying to do a range a pain with a mouse since it wants to always assume your changing the end year not the start year..  keyboard works fine on it though.
