### ISSUE TITLE
Crash when playing XVID with Render Method on "Auto Detect"

### ISSUE THREAD

**Issue by jurialmunkey** [xbmc/xbmc#15335]
### Describe the bug
Kodi crashes when playing XVID videos with the default render method settings of "Auto Detect". 

## Expected Behavior
Kodi will auto detect the correct render method and play the video.

## Actual Behavior
Kodi crashes.

### To Reproduce
1. Play an AVI file with an XVID codec.

### Debuglog

The debuglog can be found here:
https://pastebin.com/9JXyBKCv

## Additional context
Here is some additional context or explanation that might help:
H.264 videos play fine.
If Render Method is set to "Software", then XVID videos will play correctly.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18 RC5 Git:20190124-bd99f17b03

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by barbafa** [comment]
samme issue and solution here. 
Kodi Leia 18.5 
Hardware: NUC (nuc6i5syb) i5-6260U @ 1,8 GHz Skylake with Intel Iris Graphics 540
OS: windows 8.1. 
Videofile codec (as reported by vlc): Xvid MPEG-4 Video (XVID)

**Comment by tllph** [comment]
This problem has actually gotten worse; I keep Kodi 17.6 _and_ 18.8 on my Intel machine for this reason, but now XviD/H.263 crashes both versions when "Render method" is left on "Auto detect". The problem does not occur on my AMD Win10 machine with any Kodi version.

Hardware: i5-8400 @ 2.8 GHz Coffee Lake with integrated UHD 630 Graphics; Dell 0H4VK7 motherboard; 12GB RAM
OS: Windows 10 (version 1903)
Codec: XviD/H.263
