### ISSUE TITLE
Kodi does not correctly recognize subtitle language in 4KUHD

### ISSUE THREAD

**Issue by momokind** [xbmc/xbmc#15337]
### Describe the bug
Here is a clear and concise description of what the problem is:

Since the subsequent version of Kodi v18 Leia (Beta 1v2), the language of subtitles cannot be correctly recognized when playing 4KUHD, and the subtitle language in 4KUHD is recognized as “unknown”.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
https://pastebin.com/wnQxvh8W

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Pic](https://github.com/momokind/CoreELEC/blob/master/screenshot001.png?raw=true)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 -  Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi (18.0-RC5 Git:18.0rc5.2-Leia)
 - System: CoreELEC 8.95.7-nightly_20190120

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Please head over to the CoreELEC forums or try to reproduce the issue with one of our supported operatiing systems (Windows, Linux (Ubuntu), MacOS or Anndroid). 

We leave that issue open for the next 3 days to submit a new logfile with a different OS, but I'll mark it as invalid for the time being.

**Comment by Dnkhatri** [comment]
I think this bug is the same as this one and it is for all files not just uhd4k where internal subs are named in chinese
https://github.com/xbmc/xbmc/issues/15240

**Comment by momokind** [comment]
The latest Kodi v18 Leia RC 5.2 was installed in win10, and the same 4KUHD movie was played. The same problem occurred, the subtitle language was displayed as "unknown".

The debuglog can be found here:
https://pastebin.com/zRJewSYe

**Comment by PelicanHu** [comment]
I've tested this bug on Windows in Kodi versions from 18.0 to 18.7beta and 19beta. All version still has this bug. The language info on UHD BD is the same as on the normal BD. Somebody could give a hint how this info read. Through ffmpeg? libbluray? Is it reads from the mpls or from the clpi file?
