### ISSUE TITLE
Skinning - ListItem infolabels in nested variables do not populate when a dialog is visible.

### ISSUE THREAD

**Issue by jurialmunkey** [xbmc/xbmc#15348]
### Describe the bug
If a listitem infolabel is in a variable nested in another variable, then the info will not show when a dialog such as contextmenu is on screen.

## Expected Behavior
The info will show even if a dialog is on screen.

## Actual Behavior
The info does not show.

### To Reproduce
1. Add a label control in MyVideoNav which references a variable:
```
<control type="label">
<label>$VAR[var_foo]</label>
</control>
```

In an includes file add the variable:
```
<variable name="var_foo">
<value>$VAR[var_bar]</value>
</variable>

<variable name="var_bar">
<value>$INFO[ListItem.Label]</value>
</variable>
```

The label will show when the library is visible. Open the context menu and it disappears. However, if you reference $VAR[var_bar] directly from the label control instead, then the info will stay.

## Additional context 
Nested variables help cut down on code sizes considerably. For instance, it is necessary to nest a variable that converts audio channel numbers into the correct speaker configuration (e.g. 2 = 2.0, 3 = 2.1, 4 = 3.1 etc.). Without a nested variable, complex labels need a condition for every single possible configuration.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

The bug happens on Linux (Fedora), Windows 10, and Libreelec. (i.e. not platform dependent).
 - Kodi version: RC5.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
i can't reproduce this..
i've tested with estuary / current master / linux

**Comment by jurialmunkey** [comment]
@ronie - Sorry, my mistake. I meant Home.xml not MyVideoNav.xml

It works in the library, but not on Home or in a Custom window.

**Comment by ronie** [comment]
yup, that i can reproduce.
i've no clue what might be causing it.

**Comment by jurialmunkey** [comment]
@thexai - Why is this issue obsolete? The bug still persists in the skinning engine in Matrix and I assume also Nexus (unless there is a PR that solves it which I am unaware of)

**Comment by enen92** [comment]
I've tested this in nexus (placing the label on Home.xml and the variable definition on variables.xml and I Can't reproduce the issue:

![Screenshot from 2022-04-22 12-59-33](https://user-images.githubusercontent.com/7375276/164710187-eda5ceb7-a816-4dee-b21c-cb00a6115d83.png)

**Comment by enen92** [comment]
Nevermind, confirmed it now. I missed the context menu part.
