### ISSUE TITLE
Kodi crashes when scanning to library

### ISSUE THREAD

**Issue by ender1598** [xbmc/xbmc#15349]
### Describe the bug
Here is a clear and concise description of what the problem is:

I browsed to a new folder of videos chose the option to Scan to Library. It then prompted me for the title and I deleted the extra text at the end and submitted. Shortly after this I got a Windows dialog for Kodi crashing.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The folder of videos would be added to the library and then you can browse the episodes like normal.

## Actual Behavior

The program crashes after starting to scan to library and you have to restart. Repeated attempts seem to cause similar crashes.

### To Reproduce

1. Launch Kodi and browse to new video folder
2. Select the option to Scan to Library
3. It asks to refresh from the internet and I click OK
4. Wait a few seconds and see the crash dialog.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/owevehusus.kodi

[Kodi.zip](https://github.com/xbmc/xbmc/files/2800932/Kodi.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 7 64-bit
 - Kodi version: 18.0-RC5 Git:20190126-d465913c34

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by b1ck0** [comment]
I have the same problem, I can scan folders one by one, but if I try to scan my entire 'Movies' source Kodi just crashes.

**Comment by ender1598** [comment]
I have updated to Kodi 18.1 and deleted my \AppData\Roaming\Kodi folder so that all the settings would be reset. I still have the same problem happening with the crashes. This never happened with the same folders and library in Kodi 17.

Logs available here: https://paste.kodi.tv/zuyetoquva.kodi

**Comment by ender1598** [comment]
How do I get another label added to this ticket for further troubleshooting?

**Comment by arnova** [comment]
@ksooo : This crash seems PVR related. Could you have a look at the stacktrace?

**Comment by ender1598** [comment]
FYI I upgraded from Windows 7 to Windows 10 and couldn't reproduce this issue. Not sure if I should close this out or leave it open.
