### ISSUE TITLE
CRenderCaptureGL: GL_ARB_occlusion_query not supported

### ISSUE THREAD

**Issue by AnonTester** [xbmc/xbmc#15345]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi logs issue warning about GL_ARB_occlusion_query not being supported and that performance might suffer. However, occlusion query 2 (fully backwards compatible) is available and was identified by Kodi as available GL extension.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

GL_ARB_occlusion_query2 is fully backwards compatible and no warning should be issued if query2 is available.

## Actual Behavior

Warning displayed while query2 is available.

## Possible Fix

Only issue warning if both occlusion_query and occlusion_query2 are unavailable and use either occlusion_query or occlusion_query2 in coding. Possibly use a wrapper for occlusion_query when only occlusion_query2 is available.

This commit refers to the code change for the warning but only checks for occlusion_query and not for occlusion_query2
https://gitlab.com/ember-dev/kodi/commit/2083490458ab959e873f4231c7e62b79a9e3483c

### To Reproduce

1. Start Kodi
2. Start video playback
3. check kodi log file

### Debuglog

The debuglog can be found here:
13:32:15.722 T:140161941558208  NOTICE: Checking resolution 16
13:32:15.800 T:140161941558208  NOTICE: Using visual 0x21
13:32:15.835 T:140161941558208  NOTICE: VAAPI::Close - closing decoder context
13:32:15.835 T:140161941558208  NOTICE: GL_VENDOR = Intel Open Source Technology Center
13:32:15.835 T:140161941558208  NOTICE: GL_RENDERER = Mesa DRI Intel(R) HD Graphics 500 (Broxton 2x6)
13:32:15.835 T:140161941558208  NOTICE: GL_VERSION = 4.5 (Core Profile) Mesa 18.0.5
13:32:15.835 T:140161941558208  NOTICE: GL_SHADING_LANGUAGE_VERSION = 4.50
13:32:15.835 T:140161941558208  NOTICE: GL_EXTENSIONS = GL_3DFX_texture_compression_FXT1 GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_AMD_shader_trinary_minmax GL_
AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_APPLE_object_purgeable GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_AR
B_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_s
hader GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_derivative_control GL_ARB_direct_state_ac
cess GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_
conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gpu_shader5 GL_ARB_gpu_sha
der_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alig
nment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_occlusion_query2 GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_post_depth_coverage GL_A
RB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture
 GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_
load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_A
RB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_buffer_object GL_ARB_texture_buffer_objec
t_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map_array GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_
edge GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_AR
B_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_uniform_
buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_A
TI_blend_equation_separate GL_ATI_texture_float GL_EXT_abgr GL_EXT_blend_equation_separate GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT
_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_shader_integer_mix GL_EXT_shader_samples_identical GL_EXT_texture_array GL_EXT_texture
_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm 
GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_IBM_multimode_draw_arrays GL_INTEL_conservative_rasterization GL_INTEL_performance_query GL_KHR_blend_equation_advanced GL_KHR_blend_equation_
advanced_coherent GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sli
ced_3d GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_signed_rgba GL_NV_conditional_render GL_NV_depth_clamp GL_NV_packed_depth_stencil GL_NV_texture_barrier GL_OES_EGL_image GL_S3_s3tc
13:32:16.208 T:140161054930688  NOTICE: Running database version Addons27
13:32:16.209 T:140161054930688  NOTICE: Running database version ViewModes6
13:32:16.210 T:140161054930688  NOTICE: Running database version Textures13
13:32:16.217 T:140161054930688  NOTICE: MYSQL: Connected to version 5.7.25-0ubuntu0.18.04.2
13:32:16.221 T:140161054930688  NOTICE: Running database version MyMusic72
13:32:16.225 T:140161054930688  NOTICE: Running database version MyVideos116
13:32:16.226 T:140161054930688  NOTICE: Running database version TV32
13:32:16.227 T:140161054930688  NOTICE: Running database version Epg12
13:32:16.250 T:140161941558208  NOTICE: start dvd mediatype detection

...
...

14:12:57.281 T:140161941558208  NOTICE: VideoPlayer::OpenFile: smb://x.x.x.x/dir/somefile.mkv
14:12:57.284 T:140158474401536  NOTICE: Creating InputStream
14:12:57.879 T:140158474401536  NOTICE: Creating Demuxer
14:12:57.940 T:140158474401536  NOTICE: Opening stream: 0 source: 256
14:12:57.940 T:140158474401536  NOTICE: Display resolution ADJUST : DP-1: 3840x2160 @ 23.98Hz (21) (weight: 0.000)
14:12:57.949 T:140161941558208  NOTICE: CWinSystemX11::SetFullScreen - calling xrandr
14:12:58.033 T:140161941558208  NOTICE: VideoPlayer: OnLostDisplay received
14:12:58.033 T:140161941558208 WARNING: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
14:12:58.033 T:140161941558208 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
14:12:58.391 T:140158474401536  NOTICE: Creating video codec with codec id: 27
14:12:58.391 T:140158474401536  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
14:12:58.391 T:140158474401536  NOTICE: Creating video thread
14:12:58.391 T:140158234924800  NOTICE: running thread: video_thread
14:12:58.391 T:140158474401536  NOTICE: Opening stream: 1 source: 256
14:12:58.391 T:140158474401536  NOTICE: Finding audio codec for: 86019
14:12:58.392 T:140158474401536  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder ac3
14:12:58.392 T:140158474401536  NOTICE: Creating audio thread
14:12:58.392 T:140158265583360  NOTICE: running thread: CVideoPlayerAudio::Process()
14:12:58.529 T:140161941558208  NOTICE: VideoPlayer: OnLostDisplay received
14:12:58.639 T:140161941558208  NOTICE: VideoPlayer: OnResetDisplay received
14:12:58.651 T:140158265583360  NOTICE: Creating audio stream (codec id: 86019, channels: 6, sample rate: 48000, no pass-through)
14:12:58.697 T:140158226532096  NOTICE: COutput::OnStartup: Output Thread created
14:12:58.815 T:140161941558208  NOTICE: GL: Selecting YUV 2 RGB shader
14:12:58.824 T:140161941558208  NOTICE: GL: NPOT texture support detected
14:12:58.824 T:140161941558208  NOTICE: GL: Using GL_ARB_pixel_buffer_object
14:12:58.824 T:140161941558208  NOTICE: Using GL_TEXTURE_2D
14:12:58.824 T:140161941558208 WARNING: CRenderCaptureGL: GL_ARB_occlusion_query not supported, performance might suffer
14:12:58.824 T:140161941558208 WARNING: CRenderCaptureGL: GL_ARB_occlusion_query disabled, performance might suffer
14:12:58.849 T:140161941558208  NOTICE: GL: Selecting YUV 2 RGB shader
14:12:58.859 T:140161941558208  NOTICE: GL: NPOT texture support detected
14:12:58.859 T:140161941558208  NOTICE: GL: Using GL_ARB_pixel_buffer_object
14:12:58.893 T:140161941558208  NOTICE: Display resolution ADJUST : DP-1: 3840x2160 @ 23.98Hz (21) (weight: 0.000)
14:12:58.904 T:140161941558208  NOTICE: GL: Selecting YUV 2 RGB shader
14:12:58.913 T:140161941558208  NOTICE: GL: NPOT texture support detected
14:12:58.913 T:140161941558208  NOTICE: GL: Using GL_ARB_pixel_buffer_object
14:12:59.332 T:140158234924800 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
14:12:59.419 T:140158234924800  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 41727
14:22:41.382 T:140158195705600  NOTICE: COutput::OnStartup: Output Thread created
14:22:41.852 T:140161941558208  NOTICE: VAAPI::Close
14:22:41.853 T:140158226532096  NOTICE: COutput::OnExit: Output Thread terminated

Weirdly, glxinfo on the command line reports both occlusion_query and occlusion_query2 as extensions whereas Kodi only lists query2. glxinfo output here:
[glx.txt](https://github.com/xbmc/xbmc/files/2800160/glx.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

This project appears to have had the same issue and solved it:
https://github.com/apitrace/apitrace/issues/358

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu Server 18.04 LTS, kernel 4.15.0-43-generic x86_64
Device: Mesa DRI Intel(R) HD Graphics 500 (Broxton 2x6)  (0x5a85)
Version: 18.0.5

 - Kodi version: 
18.0-RC5 Git:20190127-d465913 Media Center Kodi

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Does this: http://paste.ubuntu.com/p/3NHVHtp8fw/ work for you?

**Comment by AnonTester** [comment]
Thanks for responding so quickly. As I don't know why kodi is checking explicitly for GL_ARB_occlusion_query, I can't say if dropping the explicit check and checking for the GL version instead will solve the issue or not. GL 4.5 on my system lists the query2 extension, it doesn't list the previous query extension though. I do not know if its backward compatibility means that code that may exist and might be referring to the query will be redirected to query2 instead or if it would fail...

**Comment by fritsch** [comment]
Could you post:

```
fritsch@L380:~/Desktop/xbmc-fritsch/xbmc$ glxinfo |grep -i occlus
    GL_ARB_multi_draw_indirect, GL_ARB_occlusion_query2, 
    GL_ARB_occlusion_query, GL_ARB_occlusion_query2, 
    GL_EXT_occlusion_query_boolean, GL_EXT_polygon_offset_clamp

```

Which drivers / vendor do you use? The above is from Intel

**Comment by AnonTester** [comment]
full glx output in bug submission above, but here's the grep:
$ glxinfo |grep -i occlus
    GL_ARB_occlusion_query2, GL_ARB_pipeline_statistics_query, 
    GL_ARB_multisample, GL_ARB_multitexture, GL_ARB_occlusion_query, 
    GL_ARB_occlusion_query2, GL_ARB_pipeline_statistics_query, 
    GL_EXT_occlusion_query_boolean, GL_EXT_polygon_offset_clamp, 

graphics drivers in use is the i915 intel kernel driver with xserver-xorg-video-intel

**Comment by fritsch** [comment]
Thx. I see the issue. Needed a bit longer ;-)

**Comment by AnonTester** [comment]
Thanks. Saw your patch commit and tested the latest nightly. The error message "GL_ARB_occlusion query not supported, performance might suffer" is gone. However, I'm still seeing "GL_ARB_occlusion_query disabled, performance might suffer" messages in my log from CRenderCaptureGL.

Looking at the code of xbmc/cores/VideoPlayer/VideoRenderers/RenderCapture.cpp, lines 152/153 appear to be missing the "not" if I'm reading it right as the UseOcclusionQuery() function returns true if all is well?!
      if (UseOcclusionQuery())
CLog::Log(LOGWARNING, "CRenderCaptureGL: GL_ARB_occlusion_query disabled, performance might suffer");

**Comment by fritsch** [comment]
Jep :-)

**Comment by MartijnKaijser** [comment]
This can be closed now?

**Comment by AnonTester** [comment]
Double-checked and yes, the warning messages are gone now. Thanks.
