### ISSUE TITLE
smartredraw:true doesnt close Library update window

### ISSUE THREAD

**Issue by JimmyS83** [xbmc/xbmc#15354]
### Describe the bug
Here is a clear and concise description of what the problem is:

If **smartredraw** feature is set to **true**, library progress window isnt much updated, when scanning library. It wouldnt be much problem, but leaving window drawed even after library update finish, is little bit annoying.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Library progress window dissappears after library update is finished.

## Actual Behavior

Library progress window is still drawed. Its "cleared" logically, when redraw is done (for example by starting and stopping video), but it isnt dissappear automatically, after update ends.

### To Reproduce

1. Enable smartredraw feature
2. Enable showing Library update progress window
3. Run Library update

### Debuglog

The debuglog can be found here:
https://pastebin.com/EpMv0BbU

### Screenshots 
Here are some links or screenshots to help explain the problem:

Expected behauviour: https://i.ibb.co/rdChfxR/20190128-174357.jpg
Behauviour after update library: https://i.ibb.co/BN7hcQM/20190128-174444.jpg

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP
 - [X] Odroid C2

 - Operating system version/name: CoreELEC nightly_20190109 (9.0), kernel: Linux ARM 64-bit version 3.14.29 aarch64
 - Kodi version: 8.0-RC4 Git:18.0rc4-Leia

**Comment by DaVukovic** [comment]
Just to mention it, I am able to repruce the same using Confluence on Ubuntu. So that's not a CE only issue. But...I can't reproduce this issue using Estuary. So it might also be a Confluence related issue.

Probably @HitcherUK if you have the time to look into it.

**Comment by HitcherUK** [comment]
Just tested and it's not a skin issue - seems linked to progress bars as the volume dialog is affected as well.

**Comment by DaVukovic** [comment]
Digged a bit deeper (updated our Wiki as well) and also looked at the PR itself, this advancedsetting still seems to be an experimental feature. Let's keep it open so it won't get forgotten.

**Comment by HitcherUK** [comment]
Did some further testing using Estuary and the same thing is happening here with progress bars. The volume one is clear to see - it only updates at start/stop of controlling the volume but not during the change. The only reason it doesn't happen for the library update is because there's a rotating texture displayed above the progress.

@peak3d progress bar updates are ignored by smartredraw:true.

**Comment by JimmyS83** [comment]
I found, that `animation effect="fade"`, used on Confluence for example for[ hiding audio/subtitle window](https://github.com/xbmc/skin.confluence/commit/82ebd98b86d303d0224d782675dd07f0d0474b60), when offset adjust window is showed (and actualy users needs to see image to adjust offset properly).

@peak3d did you think thats by design of original feature, or it could be improved in future? If yes, should I just update this Issue, or create another one, to keep track of it?

**Comment by smf007** [comment]
With regard to the toast notification, I can confirm that smart redraw blocks the Window DeInit.  Tested various Kodi v18 from Ubuntu repo, CoreElec and LibreElec.  Is it perhaps that smart redraw get confused and puts the toast notification part of the screen in a list of no paint?

There is also a report of this still impacting v19.
https://forum.kodi.tv/showthread.php?tid=359240&pid=3011002#pid3011002

**Comment by smf007** [comment]
@peak3d can you take a look at this?

Prior to pull https://github.com/xbmc/xbmc/pull/17782 and the associated Leia backport https://github.com/xbmc/xbmc/pull/17760, Toast notifications are created and destroyed, but the text does not scroll.  After that pull, the Toast notification does scroll but they are never destroyed.
