### ISSUE TITLE
Leia 18 > RC5: Playback of Main Movie of DVD (img) no longer possible on Android

### ISSUE THREAD

**Issue by godoll** [xbmc/xbmc#15357]
Till RC5.2 it was possible to start the main movie via a DVD's (img) menu, but when done these days, Kodi "pretends to play" something. When trying to stop Kodi freezes / doesn't react any longer and has to closed the "hard way".

## Expected Behavior
Selected movie should be played

## Actual Behavior
Kodi freezes

## Possible Fix
Downgrade to at least RC5.2

### To Reproduce
Update to recent nightlies

### Debuglog
First log has been posted here: https://github.com/xbmc/xbmc/issues/15143#issuecomment-455508526

### Screenshots 
I took some video with my mobile and uploaded them to Youtube to show the issue:

i) Kodi 18.0 Leia RC5.2 Amazon FireTV 2
DVD Image properly played on AFTV2 (see also related issue re stuttering playback of movie on FTVS4k https://github.com/xbmc/xbmc/issues/15143#issue-394380602)
https://youtu.be/MDehQ8e1Pqk

ii) Kodi 18.0 Leia RC4 Amazon FireTV Stick 4k
DVD (img) main movie starts, but video is lagging behind audio, movie is stuttering (see also related issue re stuttering playback of movie on FTVS4k https://github.com/xbmc/xbmc/issues/15143#issue-394380602)
https://youtu.be/7x1AE9Ymj_E

iii) same as above but with Nightly 20190128
Playback main movie of DVD img stucks - Kodi has to be forced to shut down
https://youtu.be/Am5TqdY_iV4

iv) same as above, but now on a Samsung Galaxy Tab A6
Playback main movie of DVD img stucks - Kodi has to be forced to shut down
https://youtu.be/7aoklsNhYhI

v) as i) playback of same DVD (img) w LibreELEC RC5 on RasPi 1 Model A is OK

### Your Environment
Used Operating system:

 - [x] Android

 - Operating system version/name: Android
 - Kodi version: 18.x

**Comment by MartijnKaijser** [comment]
This is fixed for 18.1
