### ISSUE TITLE
Kodi crashes when video finishes playing

### ISSUE THREAD

**Issue by ender1598** [xbmc/xbmc#15350]
### Describe the bug
Here is a clear and concise description of what the problem is:

Playing a video file will repeatedly cause a crash once the end is reached and it should be back to the selection screen.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Normally once the file is finished, you would be back to the selection screen of the folder or whatever location you had browsed to for launching the specific file.

## Actual Behavior

The video can play normally and you can seek forward without any problem. But once you get to the end, the Windows dialog comes up to say that Kodi crashed.

### To Reproduce

1. Play the video file.
2. Wait until you get to the end.
3. Crash dialog appears.

### Debuglog

The debuglog can be found here:
[Kodi.zip](https://github.com/xbmc/xbmc/files/2800939/Kodi.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

This crashing behavior never happened in Kodi 17.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 7 64-bit
 - Kodi version: 18.0-RC5 Git:20190126-d465913c34

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ender1598** [comment]
> Please post your log to a pastebin site, preferably https://paste.kodi.tv/

https://paste.kodi.tv/wuzagiresu.kodi for the logs. Be aware they are in the zip file that I dragged and linked under the Debuglog heading.

**Comment by thezoggy** [comment]
you are not using v18 final or latest nightly, so I would suggest try updating to see if it resolves your issue.

about:
> MSGQ_ABORT or MSGO_IS_ERROR return true
https://forum.kodi.tv/showthread.php?tid=339710

**Comment by ender1598** [comment]
Updated Kodi to the v18 final release. Logs are available here: https://paste.kodi.tv/wexaneyoho.kodi

This time I tested with a video that was not in an archive. I was able to play, fast forward to the end, and complete with no problem. Then I tested it on the same file as before which is in an archive. The same crashing behavior was present when I got to the end.

**Comment by ender1598** [comment]
FYI this problem persists with 18.2 as well.
