### ISSUE TITLE
HTML entities in subtitles not decoded

### ISSUE THREAD

**Issue by dagwieers** [xbmc/xbmc#15365]
### Describe the bug
When using the Kodi Netflix addon, the subtitles from Netflix are shown with HTML entities visible (undecoded). This appears to be an issue that other addons seem to have as well, as shown at: https://bitbucket.org/basrieter/xbmc-online-tv/issues/1011/npo-ondertitels-decode

## Expected Behavior
Subtitles with HTML entities decoded.

## Actual Behavior
Visible HTML entities like **&amp;amp;** or **&amp;quot;** in subtitles.

## Possible Fix
Decoding HTML entities in Netflix subtitles.

### To Reproduce
Watch on Netflix Series "De Ridder" Season 2 Episode 1 (may require Dutch subtitles) which repeatedly talks about a company named OT&amp;C which is shown as OT&amp;amp;C.

### Your Environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - LibreELEC v8.95.003
 - Kodi v18.0-RC5

**Comment by dagwieers** [comment]
This is related to: https://github.com/asciidisco/plugin.video.netflix/issues/621

**Comment by CastagnaIT** [comment]
I confirm the problem, in my link, there is a good example, some screenshots are also visible

https://github.com/CastagnaIT/plugin.video.netflix/issues/120

someone can investigate the problem?

**Comment by lameventanas** [comment]
+1 on this very annoying issue.

**Comment by Essam311** [comment]
@lameventanas You could merge this PR https://github.com/xbmc/xbmc/pull/17085 in the latest master and compile the version of Kodi for your device and this will fix this issue for you.

**Comment by Essam311** [comment]
@lameventanas This issue solved with this PR https://github.com/xbmc/xbmc/pull/17085.

**Comment by lameventanas** [comment]
@Essam311 thanks! Applied and it seems to work.

**Comment by dagwieers** [comment]
And we missed the 18.6 release for this as well... :disappointed:

**Comment by lrusak** [comment]
@dagwieers think of it as just in time for 18.7! 📈

**Comment by fuzzard** [comment]
As mentioned, PR fixing issue has been merged into master.

**Comment by DaVukovic** [comment]
Backport is PRd. I highly guess we will get that into 18.7
