### ISSUE TITLE
kodi-game-libretro is unavailable for bionic

### ISSUE THREAD

**Issue by bgemmill** [xbmc/xbmc#15366]
### Describe the bug
For users of ubuntu bionic or derivatives, there is currently no way to install the kodi-game-libretro package.

The ubuntu stable ppa only has it available for ubuntu cosmic:
https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa?field.series_filter=cosmic

The binary addons package site does not appear to support ubuntu:
http://mirrors.kodi.tv/addons/leia/

The ubuntu binary package wiki doesn't list game availability at all:
https://kodi.wiki/view/Ubuntu_binary_add-ons

Within Kodi itelf, on a default ubuntu install, the only available addon in the game addons menu that looks relevant is rom-collection-browser, which could be set up to run retroarch externally.

## Expected Behavior

If game functionality is not available on linux (yet), and users are encouraged to spin up retroarch as a separate process, the documentation should be clear about that.

Otherwise, there should be a ppa of binary packages that looks the same as:
http://mirrors.kodi.tv/addons/leia/
And the wiki for linux installing should mention it:
https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux#Installing_Kodi_on_Ubuntu-based_distributions

## Actual Behavior

On bionic, kodi-game-libretro is unavailable, and the documentation is unclear about how to proceed.

## Possible Fix

In the short term, please update the documenation to either say that this isn't expected to work, or be a bit more clear on how to make it go.

### To Reproduce

1. docker run -it --rm ubuntu:18.04 bash 
2. apt-get update -yq && apt-get install -yq software-properties-common
2. add-apt-repository -yq ppa:team-xbmc/ppa && apt-get update -yq
3. apt-get install -yq kodi
4. apt-get install -yq kodi-game-libretro # this line fails

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: ubuntu 18.04
 - Kodi version: 18 from ppa:team-xbmc/ppa

**Comment by pkerling** [comment]
ping @wsnipex

Thanks for the report (and it looks like a valid issue from a quick glance) - but we like to use GitHub exclusively for code problems and review so devs don't get overrun with mails and messages. Next time, please open a thread in the forums over at https://forum.kodi.tv/forumdisplay.php?fid=52 for Linux packaging issues and the like. I'll keep this one here since you went through all the effort already.

**Comment by bgemmill** [comment]
@pkerling thanks for the reply, I wasn't sure the best place to put this since the platform choices for packaging look to be git based starting with this repository:
https://github.com/xbmc/xbmc/blob/18.0-Leia/cmake/addons/bootstrap/repositories/binary-addons.txt
https://github.com/xbmc/repo-binary-addons/blob/master/game.libretro/game.libretro.txt
https://github.com/kodi-game/game.libretro/tree/master/debian

And according to platforms, seems like bionic should be there:
https://github.com/xbmc/repo-binary-addons/blob/master/game.libretro/platforms.txt

Happy to move this to the forums if you think that's a better place. Happy Wednesday!

**Comment by wsnipex** [comment]
the addon should be build automatically by jenkins (also for the ubuntu PPA), but the packaging files have some error, so building fails. I'll try to look into it, but probably not before the weekend

**Comment by bgemmill** [comment]
@wsnipex thanks for that, I see it in the repo now:
https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa?field.series_filter=bionic

To close the usability portion of this bug out, do you know what ppa has the kodi-game-libretro-* cores? I'm assuming the equivalent of:
http://mirrors.kodi.tv/addons/leia/
