### ISSUE TITLE
Kodi V18.0 - Leia, Locks at splash screen when central database specified in advancedsetting.xml

### ISSUE THREAD

**Issue by RBalfour** [xbmc/xbmc#15364]
### Describe the bug

Kodi V18.0 hangs at the splash screen when advancedsettings.xml specifies shared library on NAS

I have been using Kodi 17.6 on several android and win/10 devices sharing a single movie, tv, music library on a database hosted on my Synology NAS for over 6 months with no issues.

Today I started my Kodi app on my Nvidia Shield and was presented with the new Kodi V18.0 splash screen saying that it was converting my library and please wait.
After several minutes the conversion message disappeared and the standard splash screen remained. I have left it for over 30 minutes with no response.  I have rebooted and restarted the app, which promptly hangs again on the splash screen.  

If I remove the advancedsettings.xml file it will start normally.
Putting the advancedsetting.xml file back, results in the application hanging at the splash screen.

All other devices are still on version 17.6 and continue to function normally allowing them share the single library located on my Synology NAS database server.

## Expected Behavior
It should go to the main screen and display the contents of the shared library.

## Actual Behavior

The application hangs at the splash screen

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
Nvidia Shield Model P2897 V8.0.0   -  Kodi V18.0
Amazon Fire TV  - Kodi V17.6
Samsung Note3 - Kodi V17.6
 - [ ] Windows
Win/10 - Kodi V17.6

[advancedsettings.txt](https://github.com/xbmc/xbmc/files/2810524/advancedsettings.txt)

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by vpeter4** [comment]
Btw: there is also a typo for xml comment **<!  -->**.

**Comment by RBalfour** [comment]
I've resolved the problem, thank you for your help.
I had a look at the debug log and it was hanging when it couldn't find the version table in the MyVideo116 database.  The database conversion on initial startup didn't finish (not sure why, could have been my fault) stopped midway through the movie table conversion.
Deleted MyVideo116 database and the migration completed successfully the second go around.
Have since installed V18 on a win/10 device and sharing of the library works as expected.
Thanks
