### ISSUE TITLE
xbmc-18.0-Leia/xbmc/video/Teletext.cpp:1287]: (warning) Redundant assignment of 'm_RenderInfo.PageChar[32+i]' to itself.

### ISSUE THREAD

**Issue by dcb314** [xbmc/xbmc#15361]
Source code is

       else
        {
          SetPosX(33+i);
          m_RenderInfo.PageChar[32+i] = m_RenderInfo.PageChar[32+i];
        }

**Comment by MartijnKaijser** [comment]
You failed to follow our issue template

**Comment by dcb314** [comment]
>You failed to follow our issue template

Quite possibly, but issue still exists many months later.

If someone doesn't fix them, then it's a lot pointless to report them.

Rejecting free bug reports seems slightly less than optimal too.

**Comment by phunkyfish** [comment]
If you follow the template your bug has a chance of being fixed.

If you don’t that chance is zero. The template is there for a reason.
