### ISSUE TITLE
xbmc-18.0-Leia/xbmc/addons/interfaces/GUI/controls/FadeLabel.cpp:56]: (style) Boolean result is used in bitwise operation

### ISSUE THREAD

**Issue by dcb314** [xbmc/xbmc#15360]
Source code is

  if (!addon || !control | !label)

Maybe better code

  if (!addon || !control || !label)

**Comment by dcb314** [comment]
Same thing at xbmc-18.0-Leia/xbmc/addons/interfaces/GUI/ListItem.cpp:277

**Comment by Rechi** [comment]
@dcb314 please submit a PR.

**Comment by dcb314** [comment]
Thanks, but I won't bother on this occasion. I've reported it somewhere reasonable, that's
enough for me.

Nothing stopping someone else duplicating the report elsewhere, however.

**Comment by MartijnKaijser** [comment]
Then we can't bother fixing it, certainly because you failed to follow our issue template
