### ISSUE TITLE
Video Slowdown/Stutter for HD Live TV/Recording on Fire TV 3 running Kodi 18 Latest (worked on RC3)

### ISSUE THREAD

**Issue by tmortonorr** [xbmc/xbmc#15379]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I playback recorded or live TV from a HD source (e.g. BBC One HD), the video stutters but the audio keeps playing back at normal speed then the video catches up again. This happens every few seconds but always in the same place if it's a recording i.e. if I stop the recording and play it again the stutter happens in the exact same place.

This problem never happened in RC3, started from at least RC5 (I skipped RC4)

I have attached a debug log with component specific logging enable for PVR, video/audio timing and FFMPEG.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The video should have a smooth playback as in RC3

## Actual Behavior

Video stutter, audio carries on at normal speed. Video then catches up.

### To Reproduce

1. Install latest Kodi v18 Release (or RC5 same issue)
2. Install TV server backend (I use TVMosaic)
3. Play HD source (confirmed broken with BBC One HD/ITV HD)

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ovucuholix.kodi

The log is form a complete clean install with nothing but the PVR plugin installed, so it's not a plugin issue. I also started with RC3 to confirm the issue wasn't there then did a upgrade to v18 release with no other changes and the problem came back so somewhere in between those version some change has caused this bug.

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://www.youtube.com/watch?v=SKcpji4ttJ4

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android (Fire TV 3)
 - Kodi version: v18 Release

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
could it be related to: https://forum.kodi.tv/showthread.php?tid=340013

**Comment by tmortonorr** [comment]
I noticed this in the debug log:

CRenderManager::Configure - change configuration. 1920x1080. display: 1920x1080. framerate: 25.00.

It shouldn't be trying to change the refresh rate as I have that turned off (I have also tried turning it on but that doesn't help) I think the problem only occurs with 1080p 25Hz content, it's fine with other HD tv sources that aren't in 25Hz

**Comment by tmortonorr** [comment]
also this seems weird? - CAndroidUtils: selected resolution: 0x0

**Comment by tmortonorr** [comment]
Anyone able to help on this issue? I'm happy to get any further information as needed.

**Comment by tmortonorr** [comment]
I've just tested and the problem happens between Kodi versions 18 RC3 and 18 RC4. Is there any changes in RC4 that could have caused this problem?

**Comment by MartijnKaijser** [comment]
Any chance you can test latest nightly as we did some more fixes?

**Comment by tmortonorr** [comment]
Sure, will let you know as soon as I can.

**Comment by tmortonorr** [comment]
Hi @MartijnKaijser 

I have tested the latest nightly and it seems to have fixed the playback issue thank you!

What was the problem in the end?

**Comment by MartijnKaijser** [comment]
Several issues.
Solved
