### ISSUE TITLE
Official Android TV Remote app not working in 18.0

### ISSUE THREAD

**Issue by Gustav0ar** [xbmc/xbmc#15372]
### Describe the bug
Here is a clear and concise description of what the problem is:
Official Android TV Remote App for Android (https://play.google.com/store/apps/details?id=com.google.android.tv.remote) doesn't work with Kodi 18.0 (stable) on both Nvidia Shield TV devices that I have (one 2015 model and the other 2017). The directional buttons, and back button don't work while I'm in Kodi, but works fine otherwise. It used to work fine with Kodi 17.6, but stopped working as soon as updated to 18.0 yesterday. The only buttons that work are the play and pause button and the home button, all others are unresponsive.
This problem doesn't occur if I use the official Nvidia Shield Remote app and hardware controllers.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
For it work normally

### To Reproduce
1. Connect Android TV Remote app to Nvidia Shield TV
2. Use it in default homescreen
3. Enter Kodi 18.0 Stable
4. Try to navigate using the app

### Debuglog

http://paste.kodi.tv/owozazamef

### Your Environment
Used Operating system:
 - [ x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Android TV 8.0
 - Kodi version:
18.0 Stable

**Comment by ATGardner** [comment]
I have the exact same problem on my Nexus Player

**Comment by Gustav0ar** [comment]
Ok, I'll do that when I get home

**Comment by garbear** [comment]
Try [configuring controllers](https://kodi.wiki/view/HOW-TO:Configure_controllers) and see if the non working buttons can be mapped to controller buttons

**Comment by da-anda** [comment]
if it's working after you mapped the buttons as controller, please share your button map so that we can ship it. See https://kodi.wiki/view/HOW-TO:Share_button_maps

**Comment by Gustav0ar** [comment]
I got it working with the following button map:

[virtual-remote_23b.zip](https://github.com/xbmc/xbmc/files/2819190/virtual-remote_23b.zip)

**Comment by jas-jas** [comment]
Thanks, this worked immediately for me.
Full path here: **\\your.nvidia.shield.ip.goes.here\internal\Android\data\org.xbmc.kodi\files\.kodi\userdata\addon_data\peripheral.joystick\resources\buttonmaps\xml\**  drop the file Gustav0ar linked to above there. Thanks Gustav0ar and da-anda
Hopefully this gets updated in future releases.

**Comment by garbear** [comment]
> Hopefully this gets updated in future releases.

If you send a PR it will get into 18.1. I wrote a small guide:

https://github.com/kodi-game/peripheral.joystick/blob/contributing/docs/CONTRIBUTING.md
