### ISSUE TITLE
only 4 out of 6 drives are visible

### ISSUE THREAD

**Issue by kenofstephen** [xbmc/xbmc#15377]
I have 6 drives connected to my mini PC:

1 x ADATA thumb drive (visible)
2 x SanDisk thumb drive (visible)
1 x 512GB USB-C SSD (invisible)
1 x 2TB USB-HDD (invisible)
1 x 256GB Micro SD card (visible)

Only 4 of them can be seen, the other 2 are not visible when I navigate through the "Movies" Menu.
I can add them back manually, of course.

Running official Kodi v18.0 Leia Windows x64 version.

**Comment by DaVukovic** [comment]
Please use the forums for support questions. This area is for development bugs at Kodi itself and not for user or OS support.
