### ISSUE TITLE
Kodi PVR manager not starting after addon fails load on startup

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#15375]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using Enigma2 devices for a PVR backend many users have there set top boxes in deep standby mode. This means that when kodi is started the device is not available and the addon fails to load. If a user then proceeds to wake their box from deep standby and access the PVR GUI a message appear stating PVR Manager Starting but it never does and nothing much appears in the log.

![image](https://user-images.githubusercontent.com/4601187/52016940-d4ea2d80-24dd-11e9-8b25-3118b561c641.png)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After the failed addon start at startup when the PVR GUI is accessed PVR Manager Startup occurs as well as the message saying it is.

## Actual Behavior

After the failed addon start at startup when the PVR GUI is accessed PVR Manager Startup occurs instead of a message saying it is.

## Possible Fix

When PVR Manger startup is re-attempted have it attempt to load the addon.

### To Reproduce

1. Install pvr.vuplus (Enigma2) addon
2. Put STB in deep standby mode.
3. Start Kodi, PVR startup will fail.
4. Wait a minute
5. Access the PVR UI, message will display stating "Starting PVR Manager...". However no startup is attempted.

### Debuglog

The debuglog can be found here:

https://gist.github.com/phunkyfish/9d7bbd907ca4d15c354c817bd3d6e0fe

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screenshot in main description

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [x] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreElec 18 testbuild Milhouse, 2019-01-26, OSX High Sierra, Windows 10 Pro 64 bit
 - Kodi version: 18 RC5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by phunkyfish** [comment]
Reproduced on Official Kodi 18 release on Windows 10 Pro 64 bit

**Comment by ksooo** [comment]
Well, the addon most not fail to load if the backend is not available. This is a pvr addon  API change introduced years ago and due to the fact that pvr.vuplus was orphaned so long nobody took care.

It must implement async connect to notify Kodi on connect, disconnect, reconnect whenever this  happens. It's not just for startup. 

Look for "pvrconnectionstate" in the PVR addon API docs and the code of the addons doing it right  (i.e. pvr.hts).

**Comment by phunkyfish** [comment]
Amazing, I can work on this so. Apologies for the disturbance!
