### ISSUE TITLE
Bug report: 1080p resolution selection only displays upper left quadrant of screen

### ISSUE THREAD

**Issue by user8446** [xbmc/xbmc#15374]
v18.0 on Nvidia Shield (Android TV)
After the auto update from 17.6 to v18.0, only the top left quadrant of the GUI is shown. Settings were set to 1920x1080p. Changing the setting in Kodi to 1280x720p will display the whole GUI but is obviously not ideal and it's not as clear on my large display (1080p 120" front projection screen)

 Expected Behavior
The whole GUI is shown in 1080p

Actual Behavior
Only the top left quadrant of the screen is shown in 1080p

Switching back to 1920x1080p reproduces the issue

**Comment by NBroomfield** [comment]
Dito me too, but I'm on 4k and the issue only happenes on one profile, mine (I have 4 profiles, me, son, wife, master) all other profiles than mine look okay... Very strange.

**Comment by NBroomfield** [comment]
Is there anyway to roll back the update?

**Comment by user8446** [comment]
Is there any differences in settings between your profiles?

As for rolling back you would have to sideload v17.6 and then make sure you choose to not auto update in the play store so it doesn't update back to 18

On Sat, Feb 2, 2019, 1:12 PM NBroomfield <notifications@github.com<mailto:notifications@github.com> wrote:

Dito me too, but I'm on 4k and the issue only happenes on one profile, mine (I have 4 profiles, me, son, wife, master) all other profiles than mine look okay... Very strange.

**Comment by NBroomfield** [comment]
Think I found the difference under system settings gui resolution limit, set it to auto.
