### ISSUE TITLE
Flatten hierarchy doesn't work in Estuary if Category widgets are disabled

### ISSUE THREAD

**Issue by sepodele** [xbmc/xbmc#15370]
### Describe the bug
Here is a clear and concise description of what the problem is:

If Category widgets are enabled on home screen in Estuary, flatten hierarchy doesn't work.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Flatten hierarchy should skip the selection of Genres, Titles, etc.

## Actual Behavior

I get a selection of Genres, Titles etc.

### To Reproduce

1. Disable category widgets in Estuary
2. Enable flatten hierarchy
3. Select Movies on home screen and see Genres, Titles etc.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

### Your Environment
Used Operating system:

 - [x] Windows

 - Operating system version/name: Windows 10
 - Kodi version: 18.0

**Comment by DaVukovic** [comment]
You missed following our issue template. Please add a full debuglog from Kodi start. 

We'll mark this as invalid for the time being and if no debuglog is provided we'll close the issue in 3 days.

Thanks in advance

**Comment by The-Choo-Choo-Shoe** [comment]
> You missed following our issue template. Please add a full debuglog from Kodi start.
> 
> We'll mark this as invalid for the time being and if no debuglog is provided we'll close the issue in 3 days.
> 
> Thanks in advance

I came here with the same issue, is this log enough or you need something else?
[kodi.log](https://github.com/xbmc/xbmc/files/2825386/kodi.log)
