### ISSUE TITLE
performance improvement

### ISSUE THREAD

**Issue by quickmic** [xbmc/xbmc#15389]
Hello
I uploaded a snippet of code and maybe some of the devs can have a look at it.
The goal is to fix some design based performance problems in case using large (e.g. music) collections.
The current problem is, e.g. playlist creation can take on highend hardware minutes, on lowend hardware half an hour.
Imagine, you have a playlist with around 50.000 songs. The current approach creates the whole playlist before continuing with anything else, for example start playing the first song.
My snippet will now generate the actual playlist in a separate thread to get rid of this performance lag.

Actually in the end, all list-generations should be modified to a threading approach.

As I'm not a professional c-programmer and not familiar complete kodi code, the snippets just shows a functional version of the playlist threading.
Maybe the devs can check it and give a feedback if this approach is total crap and triggers issues in other modules of kodi or they can give it a shot.

Also as mentioned, I'm not an C expert. I program my own projects in different languages, so I'm not sure e.g. if using pthread for the threading is the best for generating threads etc.
Maybe such things can be also checked by the dev to rule out there are conceptional problems.

The following snippets just have the mods included.

GUIMediaWindow.h
https://pastebin.com/e68kE7Jr

GUIMediaWindow.cpp
https://pastebin.com/RY1zSAB7

**Comment by DaVukovic** [comment]
Could you please submit that as a PR as it will get more attention then. 

This section is for bug reports and not for pull requests ;)

**Comment by quickmic** [comment]
ok, thanks for the hint.
I will do so, and close that thread.
