### ISSUE TITLE
Kodi crashes when any video starts playing

### ISSUE THREAD

**Issue by nonninz** [xbmc/xbmc#15386]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi crashes to the desktop every time it start playing a movie. Sometimes it may display the first frame before crashing, sometimes just a black screen.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi would start playing the movie.

## Actual Behavior

It crashes.

### To Reproduce

1.  Open Kodi
2. Select any movie from the library
3. Press play

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/opamasevox.kodi
The crash dump can be found here: https://drive.google.com/file/d/18wDRel_h_vARYy_0vkJ8uuZ5odiclQMx/view?usp=sharing

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I tried updating the NVIDIA drivers, disabling hardware file decoding, and starting with a completely fresh installation (the Kodi directory in %APPDATA%). Nothing helped.

For context, up to yesterday I was using the windows store version of Kodi 17.6, which never gave me this problems. Today it automatically updated to kodi 18, losing my library. I uninstalled it, downloaded it from the website and copied the old library over at first.

But now I have uninstalled it, removed all kodi files, reinstalled it fresh, and added one of the sources to try. But it still crashes.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Kodi 18.0 Leia x64 (not from windows store)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jbhudson64** [comment]
Im having this same problem.  I built a new computer for Christmas and Kodi 17.6 was running fine and it auto updated to Kodi 18 and now it crashes everytime I start any video/movie.  It's so frustrating and it's the only thing I use this computer for...Media center.  Please help us.

**Comment by fritsch** [comment]
@jbhudson64 "me too" on github bugtracker are not welcome. If you have the "same issue" then provide your debuglog.

It's so frustrating that we have to waste developer time to always ask for the same input ...

**Comment by jbhudson64** [comment]
Fritsch, excuse me for just finding this site because I found someone with my exact issue.  I have no idea what a debuglog is or how to create one.  I was hoping an answer to nonninz would solve my problem and I just wanted him to know there were others with the same issue.

**Comment by nonninz** [comment]
Update. The crash happens *also* with 17.6 (downloaded from website, not windows store). It plays the video for half a second and then crashes. 

So it appears that either the windows store version of Kodi 17 was different enough to work, or something changed in Windows that makes Kodi of any version crash on my system.

Stacktrace: https://paste.kodi.tv/erojerejob
Dump: https://drive.google.com/file/d/1aTnLCfo0lbgvLd0sqyyr42WpUkr9tx_L/view?usp=sharing
Log: https://drive.google.com/file/d/1Z5Tm935T1ddr-zY6qVMvPe09DDyF0oHL/view?usp=sharing

**Comment by lbschenkel** [comment]
I am experiencing a similar issue immediately after upgrading to Leia v18 (none of this were happening on 17 nor with 18 RC1):
- Kodi completely freezes just after changing refresh rate; video does not start
- Sometimes the very first playback works, then if I stop the video and play the same file again it freezes. Sometimes it freezes on first try.
- Once the a video starts playing without freezing, the problem never happens. It's only on playback start.
- Freezing happens irrespective of file: I tried dozens of different files
- Freezing happens irrespective of refresh rate: I can reproduce with files in 23.97/24 and 59.9/60 fps
- I tried changing between WASAPI/DirectSound, changing "render method", toggling "hardware acceleration" and none of this had any apparent effect on mitigating the issue
- If I disable "exclusive fullscreen" then this issue almost disappears, however Kodi still freezes in the same way once in a while (let's say every 10 or 20 plays instead of every 1-2)

I have created a completely new profile, set it up as close as possible to my actual settings and played a single file and then Kodi froze: https://paste.kodi.tv/conoketina.kodi
```
15:42:23.940 T:8008   DEBUG: ------ Window Init (DialogBusy.xml) ------
15:42:23.942 T:8008   DEBUG: CWinSystemWin32::SetFullScreen: (true fullscreen) with size 1920x1080, refresh 59.940056
15:42:23.942 T:8008   DEBUG: DX::DeviceResources::ReleaseBackBuffer: release buffers.
15:42:23.943 T:8008   DEBUG: CWinSystemWin32::AdjustWindow: adjusting window if required.
15:42:23.943 T:8008   DEBUG: DX::DeviceResources::SetFullScreen: switching from fullscreen (1920 x 1080) to fullscreen (1920 x 1080)
15:42:23.943 T:8008   DEBUG: DX::DeviceResources::SetFullScreen: changing display mode to 1920x1080@59.940
15:42:24.264 T:10596   DEBUG: CVideoSyncD3D: Cleaning up Direct3d
15:42:24.264 T:10596   DEBUG: CVideoSyncD3D: Setting up Direct3d
15:42:24.265 T:8008   DEBUG: CWinEventsWin32::WndProc: display change event
15:42:24.268 T:8008   DEBUG: CWinSystemWin32DX::FixRefreshRateIfNecessary: refreshRate: 59.9401, desired: 59.9401, deviation: 0.00000, fixRequired: no, 0
15:42:24.320 T:8008   DEBUG: Previous line repeats 1 times.
15:42:24.320 T:8008   DEBUG: DX::DeviceResources::ResizeBuffers: resize buffers.
15:42:24.338 T:8008   DEBUG: CWinSystemWin32DX::FixRefreshRateIfNecessary: refreshRate: 59.9401, desired: 59.9401, deviation: 0.00000, fixRequired: no, 1
15:42:24.338 T:8008   DEBUG: Previous line repeats 1 times.
15:42:24.338 T:8008   DEBUG: DX::DeviceResources::SetFullScreen: switching done.
15:42:24.338 T:8008   DEBUG: CWinSystemWin32::OnDisplayLost: notify display lost event
15:42:24.418 T:8008  NOTICE: VideoPlayer: OnLostDisplay received
15:42:24.418 T:8008 WARNING: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
15:42:24.418 T:8008 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
15:42:24.418 T:8008   DEBUG: CRenderManager::Flush - flushing renderer
```
Please let me know if I can further help troubleshooting or if this is an unrelated bug and I should create a new issue.

**Comment by fede91it** [comment]
Any news here?

**Comment by DaVukovic** [comment]
Unfortunately most of the logs are already gone. The last log @nonninz provided was from an outdated Kodi version. 

To get this solved we probably might need more new logfiles instead of "me too"s.

**Comment by lbschenkel** [comment]
Hi, Kodi 18 completely broke on Windows for me so (as stated on https://github.com/xbmc/xbmc/issues/15386#issuecomment-462142170) I had to change to Linux (LibreELEC). I can try installing latest Kodi again on Windows to see what happens and post the logs, if the problem is the lack of logs...

**Comment by DaVukovic** [comment]
@lbschenkel Sure, as said, paste.kodi.tv doesn't holg logs for months. So the devs in question can't access them anymore. So new logs are most likely welcome. 

Also, if possible, provide a snippet of that video file if you are able to

**Comment by lbschenkel** [comment]
Is there any suggested upload site that will hold the logs for longer than `paste.kodi.tv`? I pasted full logs last time, but thas has been so long ago that they now vanished.

**Comment by DaVukovic** [comment]
You can try paste.ubuntu.com 

IIRC that will hold logs longer.

**Comment by enen92** [comment]
@nonninz does the issue still occur?

**Comment by nonninz** [comment]
@enen92 I just tried with the lastest version and the issue does not occur.

Thank you.
