### ISSUE TITLE
[Vero 4K+ BUG REPORT] OSMC/Kodi freezes when trying to play 8K video

### ISSUE THREAD

**Issue by martinrotter** [xbmc/xbmc#15388]
### Describe the bug
Here is a clear and concise description of what the problem is:
1. Obtain some 8K video from YouTube and place onto USB flash drive.
2. Insert USB flash drive into Vero.
3. Try to play video from USB flash drive.
4. Video does not start playing (of course).
5. **Whole GUI of Kodi completely freezes and I have to hard reboot with SSH or plug-out/in power cord.**

LOGS - `https://paste.osmc.tv/qeyukatesi`

## Expected Behavior
Kodi/OSMC should handle unsupported video/audio/whatever formats gracefully and should maybe display messagebox "Cannot play this file." instead of just freezing.

Moreover, when I tried to reboot via SSH, the whole process hanged on systemd-shutdown trying to kill hanging Kodi process and I ultimately had to hard reboot via power cord anyway.

**Comment by pkerling** [comment]
Hey,

OSMC is not supported here. Please reproduce with Kodi v18 and upload a new debug log.

**Comment by fritsch** [comment]
Vero cannot play 8K files - it's not supported.

**Comment by martinrotter** [comment]
I do not complain about inability to play 8k files. I complain about Kodi freezing.

**Comment by fritsch** [comment]
You complain at the wrong github. Vero's osmc does not share the same codebase for its aml videodecoder.
