### ISSUE TITLE
PVR - cannot open external player

### ISSUE THREAD

**Issue by tomwagner** [xbmc/xbmc#15384]
### Describe the bug
Here is a clear and concise description of what the problem is:

When i setup external player in `playercorefactory.xml` eg. VLC. There is the problem passing `pvr://` url to external player and the player won't start playing. Is there a possibility to pass right stream url from PVR extension or not?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

To pass right stream url instead of `pvr://` url.

## Actual Behavior

External player works everywhere except of PVR (TV section). In tv section player send `pvr://` link and external player of course didn't resolve it. `16:53:30.918 T:12622   ERROR: CXBMCApp::StartActivity - ExceptionOccurred launching org.videolan.vlc
`

### To Reproduce

1. Setup PVR client (for me vuplus addon https://github.com/kodi-pvr/pvr.vuplus)
2. Setup streaming as external player `https://kodi.wiki/view/External_players#Android`
3. Play some channel.

### Debuglog

The debuglog can be found here: [https://paste.kodi.tv/ucamuhesis.kodi](https://paste.kodi.tv/ucamuhesis.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.0 Git:20190128-d81c34c

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Seems to by another 'dynpath' issue.
