### ISSUE TITLE
Kodi periodically crashes when playing video youtube or see iptv player

### ISSUE THREAD

**Issue by krent84** [xbmc/xbmc#15391]
### Describe the bug

Kodi periodically crashes to the desktop when playing a youtube video or see iptv.

## Expected Behavior

Kodi NOT crashes to the desktop when playing a youtube video or see iptv.

## Actual Behavior

Program terminated with signal SIGABRT, Aborted.

### To Reproduce

1) Open Kodi
2) Select any program from the youtube or iptv player
3) Press play

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/izopipedip.kodi
The crash dump can be found here: https://drive.google.com/file/d/1NY5SW66Ry-_-al0xqcAkh5hpUnJeHMYw/view?usp=sharing

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The problem was observed in the 17 and 18 versions of Kodi. How to solve it, I do not know

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora release 29 (Twenty Nine)
 - Kodi version: kodi-18.0-0.24.rc5

**Comment by krent84** [comment]
Tell me, please, what kind of banned repositories do I use?

**Comment by DaVukovic** [comment]
The only one you installed `repostiory.iptv`

This repository holds banned add-ons and therefore it's also banned. So please remove the repository and all the add-ons which you installed from there

**Comment by krent84** [comment]
I deleted iptv addons but the problem did not disappear

log - https://paste.kodi.tv/vimowekuhu.kodi
dump - https://drive.google.com/file/d/1JmC4atWC229a_0IuYfqxVEbTTJMBrzjE/view?usp=sharing

**Comment by DaVukovic** [comment]
> I deleted iptv addons but the problem did not disappear

You have not:

14:05:44.219 T:139879020373440  NOTICE: ADDON: script.module.iptvlib v1.1.2 installed
14:05:44.220 T:139879020373440  NOTICE: ADDON: script.video.iptv.ottclub v1.1.1 installed

Those add-on have been installed from the repository I named before and therefore those are also banned. 

If you still have the problem after removing those, make sure, you enabled debug logging before grabbing the log

**Comment by krent84** [comment]
> > I deleted iptv addons but the problem did not disappear
> 
> You have not:
> 
> 14:05:44.219 T:139879020373440 NOTICE: ADDON: script.module.iptvlib v1.1.2 installed
> 14:05:44.220 T:139879020373440 NOTICE: ADDON: script.video.iptv.ottclub v1.1.1 installed
> 
> Those add-on have been installed from the repository I named before and therefore those are also banned.
> 
> If you still have the problem after removing those, make sure, you enabled debug logging before grabbing the log

i delete iptvlib and ottclub. turn on debug mode

debub log - https://paste.kodi.tv/ebuvumiwug.kodi
crash dump - https://drive.google.com/file/d/1t4pBPu1m7xDgsbYdlLxZPFc5VrTC066X/view?usp=sharing

**Comment by krent84** [comment]
Steps to reproduce the behavior:

1) open kodi
2) reboot kodi (and my computer), turn off monitor when computer rebooting
3) kodi not autostart with error: "Program terminated with signal SIGSEGV, Segmentation fault."

see video: https://drive.google.com/open?id=1CwDSAB2JBJP1fPi-_U6JMZ2MUi9RpJON

kodi always crashes after a while if i turn off the monitor ((((

**Comment by DaVukovic** [comment]
> i delete iptvlib 

you did not:

`20:27:38.307 T:140574350017984  NOTICE: ADDON: script.module.iptvlib v1.1.2 installed`

That's from the crashlog you posted above...
and now it's enough. The issue you are mentioning now is a completely different one to the one you mentioned initially. Please open a new bug report and make sure you have a complete vanilla Kodi.

Closed

**Comment by dmitry-vinogradov** [comment]
As side  question @DaVukovic: when and why this repository and addons from it were banned?
