### ISSUE TITLE
Update of SFTP location not working

### ISSUE THREAD

**Issue by hatl** [xbmc/xbmc#15404]
## Bug report
Kodi is unable to scan the contents of a library added via SFTP.
Browsing the files via Kodi and watching the videos works but the library scan doesn't work.
### Describe the bug
- used a clean installation
- enabled sftp addon
- added sftp location
- set type to tv shows
- scan stops immediately
- no items are found

Tried username/password authentication as well as public key authentication - both work for browsing the files but the library scan fails.

The same setup worked with Kodi 17 (same machines, same network)
The update to Kodi 18 broke the library scan

## Expected Behavior
- kodi searches the sftp locatoin for items and adds them to the library

## Actual Behavior
scan doesn't seem to start at all

### Debuglog
The debuglog is attached

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.10
 - Kodi version: latest stable package from team-kodi ppa - kodi/cosmic,cosmic,now 2:18.0+git20190128.1934-final-0cosmic all [installed]
[kodi.log](https://github.com/xbmc/xbmc/files/2824523/kodi.log)

**Comment by hatl** [comment]
![screenshot001](https://user-images.githubusercontent.com/70505/52165660-f0cf1880-2703-11e9-9206-ad3c88afaa3a.png)
![screenshot002](https://user-images.githubusercontent.com/70505/52165661-f0cf1880-2703-11e9-9b6a-571352bada88.png)
![screenshot003](https://user-images.githubusercontent.com/70505/52165662-f0cf1880-2703-11e9-811f-1fb31edb69f9.png)
![screenshot004](https://user-images.githubusercontent.com/70505/52165663-f167af00-2703-11e9-9dfd-84755497c6d9.png)
![screenshot005](https://user-images.githubusercontent.com/70505/52165664-f167af00-2703-11e9-9037-a860335316cd.png)
![screenshot006](https://user-images.githubusercontent.com/70505/52165665-f167af00-2703-11e9-9a22-da5be4fbf9a6.png)

**Comment by DaVukovic** [comment]
You missed to follow our issue template. A debuglog is always mandatory

> scan doesn't seem to start at all

Maybe you simply haven't enabled debuglog. That's why we always ask for that debug log. If you have problems how to get the log file, please see: https://kodi.wiki/view/Log_file

We can't do anything without the log. So please share it. Otherwise this issue will be closed soon. 

I'll mark this issue as invalid for the time being.

**Comment by hatl** [comment]
Sorry! Here's the log generated with the "Kodi Logfile Uploader" addon:
http://paste.kodi.tv/hixovikaso

**Comment by hatl** [comment]
Same error with 18.1 RC
Switched to NFS for now - works fine
