### ISSUE TITLE
UPnP / DLNA Problem - started after Kodi 16.1 and continues in 18

### ISSUE THREAD

**Issue by blueribb** [xbmc/xbmc#15407]
Older Kodi versions up to and including 16.1 worked perfectly for me when accessing my Verizon Media Server from my (2) Intel NUC's running Libreelec & (2) Windows 10 desktops to play live TV channels over my wired network. The channels are encrypted (.dtcp-ip). Kodi did a fine job of streaming my subscribed channels to my Intel NUC running Kodi 16.1 and older versions.

All newer versions of Kodi either fail to detect my UPnP/DLNA server or fail to play the streams. With the latest LE 9 (Kodi 18), my server is detected and the channel groups are displayed, but not the individual channel list with tags.

I first posted about this issue a little over 2 years ago on the Kodi forum and got zero help. They suggested filing a bug report which I did in March 2018. I supplied logs and actual videos showing the problem but they are so overloaded with new Bugs that I'm not sure anyone will ever see the Bug Report I posted there.

Maybe a developer here could spot the issue by examining my logs. I know they could time out again since I had to upload them twice. Let's hope they're still working. Here are links to my Kodi Forum Post and Bug Report:

https://forum.kodi.tv/showthread.php?tid=302641

https://trac.kodi.tv/ticket/17797#ticket (contains logs & video links)

Note: The logs were produced from a Windows 10 desktop computer, not my Intel NUC's

**Comment by andre-koch** [comment]
Yeah I'm having trouble with setting up a UPnP client as well. The kodi UPnP server isnt being detected at all 🤔

**Comment by dierre72** [comment]
Yeah me too, same issue, UnPnP is enable but I cannot recognize it from other kodi clients

**Comment by blueribb** [comment]
Three and a half years later and this issue is still not fixed. Oh well, I tried. I still love both Kodi and Libreelec.

**Comment by fritsch** [comment]
Three and a half years is a long time to learn c++ and trying to fix it byself? Maybe throughout this time you realized that major parts of Kodi have no maintainer anymore? And outside help, especially for features few people use, is needed?

**Comment by blueribb** [comment]
There is a Windows App called "DLNA Browser" that connects to my networked Verizon Media Server and allows streaming of my subscribed channels from my set-top box. I was hoping that Kodi's UPnP / DLNA feature would continue to work past Version 16.1, especially on my Intel NUCs running Libreelec. I actually reported this issue 5 years ago on the Kodi Forum and was instructed by a Mod to submit a bug report here. I realize the DLNA / UPnP feature is not the most popular and have accepted the fact that it will most likely never be fixed.

**Comment by enen92** [comment]
@blueribb does it still happen on Nexus/v20?

**Comment by blueribb** [comment]
Yes - I have Kodi 20 on a Windows 10 Desktop Computer and it still will not play. It finds the source, identifies and tags the channels correctly but will not play them.

**Comment by enen92** [comment]
It'd be nice if you could provide a log with upnp component and libcurl component enabled on a Kodi installation that works (Jarvis?) and the same on matrix our nexus for comparison.

**Comment by thexai** [comment]
Debug logs were never provided...
