### ISSUE TITLE
kodi 18.1 rc1 - nvidia shield - voice search doesn't work

### ISSUE THREAD

**Issue by Goga777** [xbmc/xbmc#15400]
### Describe the bug
Here is a clear and concise description of what the problem is:

voice search doesn't work in the kodi. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I go to search field in the kodi. I press voice button on remote control and said HELLO. 
I EXPECTED THAT in kodi search field i will see HELLO AND and after that KODI will try to search anything related with HELLO

## Actual Behavior

I can see that there are several results for youtube and other android apps on my shield, but nothing in the kodi

THE search field in the kodi is empty with the cursor.

### To Reproduce

1. go to search field of the kodi
2.press voice button on the RC
3. SAY something, for example HELLO

### Debuglog

The debuglog can be found here:
http://slexy.org/view/xxxxxxxxx

https://slexy.org/view/s2BsS9TIYZ

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android NVIDIA SHIELD
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.1 RC1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Rechi** [comment]
@Goga777 [Banned_addons](https://kodi.wiki/view/Banned_addons) are present on your system. To receive assistance here, these banned items must be removed.
If a clean log is not submitted within 3 days, then the then this issue will be closed.

The Invalid label will be removed if you provide the clean log.

**Comment by Goga777** [comment]
i have corrected and upload new log
https://slexy.org/view/s2BsS9TIYZ

**Comment by Goga777** [comment]
seems, need to press central button on rc, not voice one - in this case voice search is working.

**Comment by MartijnKaijser** [comment]
Ok, thx
