### ISSUE TITLE
Creating profile in non-English Kodi with copying settings produces broken profile

### ISSUE THREAD

**Issue by lukjak** [xbmc/xbmc#15402]
### Describe the bug
Creating a new profile with copying default settings in non-English Kodi produces unusable profile.

## Expected Behavior
The new profile opens after creation.

## Actual Behavior
After trying to switch to the new profile, a dialog to change profile name/picture appears. After accepting it there is short screen blink and I return to profile selection screen.

### To Reproduce
1. Set Kodi to some language (I used Polish)
2. Create a new profile. Select "Copy from default" for settings. I am not sure whether the following two matter: also select "Fresh" for media sources; there are no media sources defined in the default profile. Accept defaults for all other options.
3. Log out of the current profile and try to open the new profile

### Debuglog
https://paste.kodi.tv/emotozenut.kodi

### Your Environment
 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 7
 - Kodi version: 18

**Comment by KarellenX** [comment]
A forum thread exists here... https://forum.kodi.tv/showthread.php?tid=340062

Member has failed to carry out the simplest request which will possibly resolve the issue.

**Comment by lukjak** [comment]
@KarellenX  Please note the forum solution does NOT resolve the problem described.
It refers to a different problem altogether (creating new empty profile), while this report refers to creating profile based on existing profile.

**Comment by pkerling** [comment]
As this is profile-related: See https://github.com/xbmc/xbmc/issues/14732#issuecomment-433699136

**Comment by lukjak** [comment]
Well, closing this one then as profile issues are a known problem and not fixable as a simple code fix.

**Comment by DaVukovic** [comment]
I just played around with it and I'm facing the same problem as the language addon is disabled for the new profile.

A solution (and unfortunately I can't give full paths as you are using Android) is to edit the guisettings.xml at the profile you created. So try to access the userdata-folder. In that folder there you also exist a "profile"-folder and inside that there should be another subfolder  which is named in the same way as the profile is named. 

At this profile folder try to edit the "guisettings.xml" and search for a line that starts with:

` <setting id="locale.language" ..... `

and set that to:

` <setting id="locale.language" default="true">resource.language.en_gb</setting>`

After that the new profile should load in english language and you are able to enable the polish language addon again. After enabling that and also using that for the profile the specific profiles should load as expected. At least it does it for me using current Kodi master. 

Maybe this helps.
