### ISSUE TITLE
Kodi crashes to the desktop starting 720p video

### ISSUE THREAD

**Issue by rglover666** [xbmc/xbmc#15406]
### Describe the bug
Here is a clear and concise description of what the problem is:
Kodi crashes when attempting to play a 720p video.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Kodi should play the 720p video

## Actual Behavior
Kodi crashes to the desktop

## Possible Fix
Unknown

### To Reproduce
1. Start Kodi
2. Select a 720p video to play
3. Kodi crashes to desktop

### Debuglog
[kodi.log](https://github.com/xbmc/xbmc/files/2824657/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:
N/A

## Additional context or screenshots (if appropriate)
This problem does not occur with 480p or 1080p videos.  It only happens using Kodi v18 (x86 or x64)
System uses Intel HD Graphics and Realtek HD Audio.  I have updated to the latest driver versions.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64
 - Kodi version: 18.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You have banned add-ons and repositories installed. Please remove them and provide a new logfile. Otherwise this issue will be closed in 3 days

**Comment by rglover666** [comment]
Removed as requested.  New log is attached
[kodi.log](https://github.com/xbmc/xbmc/files/2824784/kodi.log)

**Comment by DaVukovic** [comment]
You still have leftovers in your log. Please make sure you have a vanilla Kodi

Do the following

- rename the `%appdata%\Kodi` folder to something else: `%appdata%\kodi-backup`
Now you have a complete vanilla Kodi like you have just installed it for the very first time. But all previous setting, add-ons and whatnot are stored in the "kodi-backup" folder. So you don't loose anything. 

Now:
- close and restart Kodi
- enable debug logging
- restart Kodi once more
- reproduce your issue
- provide the debuglog

**Comment by rglover666** [comment]
As you may have suspected, once I followed your instructions the problem is not reproducible.  This is fine by me since I don't use any of those add-ons any longer.  Thanks for you assistance.  You may close this bug now.
