### ISSUE TITLE
Subtitle positioning values are not saved between Kodi sessions

### ISSUE THREAD

**Issue by graysky2** [xbmc/xbmc#15411]
### Describe the bug
Alternative values for subtitle positioning are applied to the active session but are not saved between Kodi sessions/they reset back to the default value .  I use the term "session" to mean while Kodi s running.  If it is exited, or the system reboots etc., the user defined value is lost.

## Expected Behavior
User defined values for subtitle positioning should be retained between stopping and starting Kodi.

## Actual Behavior
A user defined value for subtitle positioning is reset to the default value upon stopping and starting Kodi.

### To Reproduce

1. Navigate to: Setting (gear icon) > System
2. You will need to be in "expert" level in order to see the video calibration option, (toggle through basic/standard/advanced/expert) at the bottom of the column of options.
3. Go to Display>Video calibration (bottom of the submenu right above the "reset to default option").
4. Hit "Enter" until "Subtitle positioning" is active.
5. On my 1080p display, a value of 1042 is defaulted.  Raise the physical position of the subtitles by setting this to a numerically lower value, say 950, then exit.

You can play a video that has subtitles at this point and the subtitles will be rendered at the custom position.  If you exit Kodi and reload it, user defined value is no longer there/the default value is back.

Filesystem permissions/ownership on `/var/lib/kodi` which is where the kodi user has its homedir mapped on this system, are correct.

### Debuglog
The debuglog detailed the process of setting the subtitle positioning value to 950 can be found [here](https://gist.github.com/graysky2/c844ee00d4811bc0bf34715d2f57cafb).  

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux (rolling release)
 - Kodi version: 18.0

**Comment by DaVukovic** [comment]
duplicate: #15165

**Comment by graysky2** [comment]
@DaVukovic - Thanks for the reference... I searched for 'subtitles' not the more general 'video calibration' :+1:
