### ISSUE TITLE
Bluray and DVD ISO playback from library not working

### ISSUE THREAD

**Issue by snake3ca** [xbmc/xbmc#15414]
### Describe the bug
Here is a clear and concise description of what the problem is:

[bluray-kodi.log](https://github.com/xbmc/xbmc/files/2825900/bluray-kodi.log)
[dvd-kodi.log](https://github.com/xbmc/xbmc/files/2825901/dvd-kodi.log)
On Kodi 18 playback of DVD & Bluray ISO files from the library dont play correctly.  Blurays fail to start playing or show the menu.  DVDs start but dont allow you to access the DVD menu or allow you to navigate the DVD menu.  If you load the ISO from the file manager it plays correctly for both Blurays and DVDs.  Also if you goto the library and bring up the contextual menu and play it from there it plays correctly.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Would expect the bluray menu to start.  Would allow you to use DVD menu.

## Actual Behavior

Bluray ISOs fail to play from library only.  DVD ISOs start but menus dont work when played from library. Both work fine from the file manager and playing from the contextual menu.

## Possible Fix

Duplicate behavior of playing from the contextual menu or file manager in the library.

### To Reproduce

1.  Scan Bluray and DVD ISOs to the library.
2. Try to playback the Bluray or DVD ISO from the library using the enter key.

### Debuglog

The debuglog can be found here:
Bluray playback debug log: https://paste.kodi.tv/hojenekite.kodi
DVD Playback debug log: https://paste.kodi.tv/pulojirame.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.0
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Try: KODI_GL_INTERFACE=GLX kodi

If you can remove the nvidia card from the system. year long hacks for nvidia shader optimizations produce an issue ...

**Comment by fritsch** [comment]
If above does not work, try upgrading nvidia drivers to 410.93

**Comment by snake3ca** [comment]
This issue is also affecting Kodi on my PC which uses an Intel GPU.  I am able to get both DVD and Bluray ISOs working fine from the file manager or contextual menu so they do play fine with both the Intel and Nvidia Gpus.  I believe the issue is related to the way it tries to play the ISO files when scanned from the library.  It must be starting playback differently.

**Comment by fritsch** [comment]
What I saw in your log was a lot of shaders that don't properly compile which makes me really wonder.

**Comment by fritsch** [comment]
```
08:58:08.253 T:140202007061440   DEBUG: GL: Enabling non-linear stretch
```

^^ could you try to disable that?

**Comment by fritsch** [comment]
But I see - that's not the issue you originally posted about

```
08:58:08.279 T:140202007061440   ERROR: GL: Error compiling and linking video filter shader
08:58:08.279 T:140202007061440   ERROR: GL: Falling back to bilinear due to failure to init scaler
```

but that got my interest.

**Comment by snake3ca** [comment]
Hi I tried disabling non liear stretch, set it to normal, but it didnt help.  I have attached a log from my system with an Intel GPU.  I played an ISO twice, first time I played by hitting enter on the keyboard in the library, and it failed to play.  The second time I hit "C" on the keyboard and selected "Play" from the contextual menu and it played fine.

[IntelGPU - kodi.log](https://github.com/xbmc/xbmc/files/2825964/IntelGPU.-.kodi.log)

**Comment by DaVukovic** [comment]
Not sure if that´s related. But the difference I see is:

not working and opened without context menu (line 1455 to 1474): 

```
14:31:00.483 T:139973702882240   DEBUG: CPlayerCoreFactory::GetPlayers(nfs://192.168.0.100/mnt/Concerts/Concerts/Aerosmith Rocks Donington 2014 (2015)/Aerosmith Rocks Donington 2014.iso)
...
...
14:31:00.489 T:139973702882240  NOTICE: VideoPlayer::OpenFile: videodb://musicvideos/titles/5345
```

working and opened with context menu (line 1514 to 1567): 


```
14:31:11.957 T:139973702882240   DEBUG: CPlayerCoreFactory::GetPlayers(nfs://192.168.0.100/mnt/Concerts/Concerts/Aerosmith Rocks Donington 2014 (2015)/Aerosmith Rocks Donington 2014.iso)
...
...
14:31:13.562 T:139973702882240  NOTICE: VideoPlayer::OpenFile: nfs://192.168.0.100/mnt/Concerts/Concerts/Aerosmith Rocks Donington 2014 (2015)/Aerosmith Rocks Donington 2014.iso
```

**Comment by notspiff** [comment]
this is 100% certainly a DynPath fallout. ie Path() is taken instead of DynPath() in some library code.

**Comment by fritsch** [comment]
Thx much @notspiff - yes that's the case.

**Comment by Dela-D** [comment]
I'm completely new here, so I'm very sorry if I'm not following protocol correctly.

I have the exact same issue with DVD's starting from the Library, but the menu not responding at all.
The issue occurs with both ISO and flat file (VIDEO_TS) DVD's.

I am running Kodi Leia on Android TV. I did not have this problem with Krypton on the same system.
I didn't follow the comment about DynPath fallout, so I hope someone is willing to clarify that a bit.

Thanks,
Arjan

**Comment by MartijnKaijser** [comment]
@Dela-D this is exactly **not** the same issue but a different one that has already been fixed. Install a new nightly version or wait till next release

**Comment by Dela-D** [comment]
@MartijnKaijser Ah, ok, my apologies! And thank you for responding. I will wait for a new release.

**Comment by enen92** [comment]
@snake3ca can you check if https://github.com/xbmc/xbmc/pull/15718 solves the issue? Test builds can be found here: https://jenkins.kodi.tv/job/BuildMulti-PR/11501/

**Comment by snake3ca** [comment]
@enen92 I was able to test on the Android build you posted, not the linux, and yes DVD and bluray menus worked correctly from the library.  Thank you for fixing this!

**Comment by snake3ca** [comment]
issue resolved in master, thanks for fix.

**Comment by enen92** [comment]
The fix was never merged so I'm reopening this issue now that we have another proposed fix
