### ISSUE TITLE
No streamdetails update on "play" with Leia (on videos at least)

### ISSUE THREAD

**Issue by Mjibey** [xbmc/xbmc#15413]
### Describe the bug
Here is a clear and concise description of what the problem is:

After changing one file by another (same name), the streamdetails informations aren't updated in db. This functionality worked great under krypton version and permitted to easily update these informations without remove file/clean db/add file/update db operations. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When file changed, on "play" streamdetails informations linked to the file were refreshed on krypton (when changed).

## Actual Behavior

This behavior don't exist anymore on Leia, at least it doesn't update the streamdetails on the played file. 
By the way, it still works on fresh "adding file to the library" 

### To Reproduce

1. Have 1 video entry in the library with valid file and stream details extracted into db
2. Change this file to another one (same name and extension)
3. Play this video in kodi
4. Stop playing
5. Streamdetails not updated in db (and on screen)

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/jirufemoxi.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Android TV (nvidia Shield TV, Oreo)
 - Kodi version:
Kodi 18 (Leia)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
where's your debuglog?

This issue is invalid as long as you don't provide one. Please do that in the next 3 days or your issue will be closed.

For a how-to, please follow: https://kodi.wiki/view/Log_file

**Comment by Mjibey** [comment]
Ok, thank you for the how-to. Due to the reproductability of the issue (originally seen on my Android TV), I didn't think a log was necessary. I'll produce it this evening (not at home right now).

**Comment by Mjibey** [comment]
I've uploaded Kodi Log with one updated file (same same and extension).

Note that this new file is a mkv renamed as avi (search "true lies"). But worked like a charm with Krypton.
