### ISSUE TITLE
EPG update every 5 minutes

### ISSUE THREAD

**Issue by lama18** [xbmc/xbmc#15429]
Duplicate #14963 

Again, I'm opening this issue, I still have the impression that this bug is. I have an XMLTV file for 3 days, but Kodi downloads data every 5 minutes.

**Comment by DaVukovic** [comment]
This can be adjusted. Please read:

https://kodi.wiki/view/Advancedsettings.xml#epg

That was also answered in the issue you already replied to. Also you missed to follow our issue template and haven't pretty much given any of the requested info we asked for. But anyway, you should probably simply adjust that by using the advancedsettings.xml like suggested before.

**Comment by lama18** [comment]
Ok, but this will not be normal users, what is the reason for updating EPG every 5 minutes?

When you realize that one EPG file can have, for example, 10 MB, it will be downloaded for 250+ days, which is 2.5 GB + completely unnecessary.

I'm just interested in the meaning of this setting? In this case, a check would be sufficient, for example, once a day / at startup / if the data ends.
