### ISSUE TITLE
settings.xml type=addon with multiselect doesn't display selection

### ISSUE THREAD

**Issue by Zomboided** [xbmc/xbmc#15423]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using this option in settings.xml : 
setting label="32015" type="addon" id="addons_list" addontype="xbmc.python.pluginsource" multiselect="true" default=""
After selecting multiple plugins, and returning to the settings dialog, no selections are displayed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

In Kodi 17, the list of selected plugins was shown.
If multiselect is not used, then the selected plugin is shown as expected.

## Actual Behavior

No plugins are displayed, making it very difficult for a user to see what plugins they've selected without going back into the dialog.   In my addon I have a screen full of these type="addon" directives and it's making the selection of addons unusable

### To Reproduce

Use this line, try and select multiple plugins
setting label="32015" type="addon" id="addons_list" addontype="xbmc.python.pluginsource" multiselect="true" default=""

Or install the attached addon which goes and pokes at all of the broken settings.xml issues.  This problem is displayed on the third tab.
[service.test.settings-0.0.1.zip](https://github.com/xbmc/xbmc/files/2828810/service.test.settings-0.0.1.zip)

### Debuglog

The debuglog is attached
[kodi.log](https://github.com/xbmc/xbmc/files/2828809/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Montellese** [comment]
This should be fixed by fce0b9138d11257b5c667c9fab977749ef283c9d from #16660.
