### ISSUE TITLE
Sort by date doesn't work in sftp add-on (vfs issue)

### ISSUE THREAD

**Issue by jonbrock** [xbmc/xbmc#15426]
### Describe the bug
Sort by date doesn't work in the sftp add-on. When you browse an sftp location and choose sort by date, it instead sorts by filename.

## Possible Fix
I looked through the code and found that the sftp add-on is populating the timestamp of the file:
`kodi::vfs::CDirEntry entry;
[...]
entry.SetDateTime(attributes->mtime64);`

However, in VFSEntry.cpp (in kodi core), you find this code:
`static void VFSDirEntriesToCFileItemList(int num_entries,
                                         VFSDirEntry* entries,
                                         CFileItemList& items)
{
  for (int i=0;i<num_entries;++i)
  {
    CFileItemPtr item(new CFileItem());
    item->SetLabel(entries[i].label);
    item->SetPath(entries[i].path);
    item->m_dwSize = entries[i].size;
    //item->m_dateTime = entries[i].mtime;`

Note the commented out line. I don't know why this was done. I believe m_dateTime is a CDateTime which has an override for assigning a time_t value so fixing this issue should be as simple as uncommenting that line.

### To Reproduce
1. Add an sftp source
2. Browse files, select your source
3. Choose to sort by date

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ahtokca** [comment]
I got the issue too with android tv from Philips. very annoying issue

**Comment by s1sfa** [comment]
I have the issue too. this problem was introduced when sftp was no longer built in.

**Comment by swampdogmash** [comment]
I have the same issue on both the Xbox One Store version and on a raspberry Pi 3 running latest version (today) of OSMC with Leia 18.2 RC1.  SFTP plugin worked on 17 ok before but now does seem to only be sorting alphabetically and not showing the dates on the view either when in "date" sort mode,, which means it's very hard to work out what files are new :P Folders also show as -1 bytes when in "size" sort mode too when i believe in previous version they were just shown with no size.

**Comment by roninn23** [comment]
Is there any update/timelines about this issue?

**Comment by arnova** [comment]
ping @notspiff . Don't know who's responsible for this but if we don't fix stuff like this in vfs addons, there was no point in moving this out of core.

**Comment by notspiff** [comment]
I only accept whines in patch form.

**Comment by arnova** [comment]
@notspiff : Any pointers why this isn't working/why it wasn't implemented?

**Comment by notspiff** [comment]
Because of missing filetime stuff in platform lib. Code is there in
commented form I believe, it used to work in my fork years ago.

**Comment by swampdogmash** [comment]
Would someone be able to take a look? Im not a dev, just a user but im guessing there was a reason it was commented out? Anyone know why please? Can it be reinstated?

**Comment by arnova** [comment]
https://github.com/xbmc/xbmc/pull/16431, https://github.com/xbmc/vfs.sftp/pull/32 and https://github.com/xbmc/vfs.sftp/pull/30 should take care of this.

**Comment by swampdogmash** [comment]
Awesome. Thanks for this.


How does this make its way into a major release? Will it now be in tonights nightly build for instance? Showing my ignorance, sorry.

**Comment by arnova** [comment]
> Awesome. Thanks for this.
> 
> How does this make its way into a major release? Will it now be in tonights nightly build for instance? Showing my ignorance, sorry.

Unfortunately this could take a while because both Kodi and the sftp addon require updating. Also it probably won't appear in an 18.x update. So unless you can build yourself, you'll have to be patient. Sorry.
