### ISSUE TITLE
PVR: Recordings window no longer shows recording icon for in-progress recordings

### ISSUE THREAD

**Issue by jahutchi** [xbmc/xbmc#15421]
### Describe the bug
Here is a clear and concise description of what the problem is:

In Krypton, the PVR Recordings window used to show a recording (red dot) icon next to any recordings that were currently in-progress. This is no longer the case in Kodi Leia 18.0

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

In the PVR Recordings window, the recording icon (red dot) should show next to any items that are currently recording.

## Actual Behavior

For an item that is recording, it just shows the normal icon for an unwatched, finished recording.

## Possible Fix

From what I've found, when in the PVR Recordings window, it seems that the ListItem.IsRecording boolean condition returns false for shows that are currently recording.

### To Reproduce

1. Start a recording on a TV Show
2. Navigate to the PVR Recordings window
3. See whether the icon next to the recording shows as the recording in progress icon (windows/pvr/record.png)

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC
 - Kodi version: 18.0

 Running pvr.hts against TVHeadend server version 4.2.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jahutchi** [comment]
Apologies, here is a debug log [kodi.log](https://github.com/xbmc/xbmc/files/2828459/kodi.log)
On this capture, Judge Rinder was recording, but when I navigated to the PVR Recordings window it doesn't show as recording.

**Comment by DaVukovic** [comment]
Seeing that you are using OSMC. Best bet will be to head over to their forums if you can't reproduce your issue using native Kodi.

**Comment by jahutchi** [comment]
No problems. I am using the standard estuary skin, with the OSMC Leia builds, so had assumed this would be a general problem. Though I don't have any other "native" kodi environment to test on.

I've therefore reported this over on the OSMC forums as you suggest:
https://discourse.osmc.tv/t/testing-kodi-18-leia-builds-for-vero-2-4k/23059/942?u=jahutchi

**Comment by ksooo** [comment]
Cannot reproduce with Vanilla Kodi latest master + Stock Estuary.

![screenshot000](https://user-images.githubusercontent.com/3226626/52221512-97045500-28a1-11e9-8841-e689b6e61510.png)

**Comment by ksooo** [comment]
Now I can reproduce this. Confirming the issue.
