### ISSUE TITLE
PVR Timer loaded multiple times on startup

### ISSUE THREAD

**Issue by emveepee** [xbmc/xbmc#15436]
PVR Timers are opened multiple times on startup in v18

Each time Kodi is started timers are loaded twice.  Once in LoadComponents() before the main loop probably with this line

m_timers->Load();

and then in the "main loop" of PVRManager in the general processing of jobs

Note that after a system wake with a reload of connection state even more timer updates are triggered as well as a second updating recordings because additional triggers are called.

To duplicate start Kodi with PVR logging on and look for the first timer updates,  mine are ~5 seconds apart

14:43:43.202 T:9108   DEBUG: PVR::CPVRTimers::Update: Updating timers
14:43:48.806 T:9108   DEBUG: PVR::CPVRTimers::Update: Updating timers

**Comment by ksooo** [comment]
You seem to have some developer skills. How about going one step further an submitting PR with fixes?

**Comment by ksooo** [comment]
Hint: The first update from LoadComponents() befor pvr mananger main loop is mandatory to get initial data while bootstrapping pvr; all further calls are triggered by the PVR addons. So, if you want to fix this, check whether your favorite PVR addon only triggers a timers update when it is really necessary.

Short: No Kodi issue, but, if at all, a pvr addon issue.

**Comment by emveepee** [comment]
Basically it is this function that triggers two updates

bool CPVRTimers::Load(void)
{
  // unload previous timers
  Unload();

  // (re)register observer
  CServiceBroker::GetPVRManager().EpgContainer().RegisterObserver(this);

  // update from clients
  return Update();
}

The Update() triggers the first load of timers and by registering the the observer when the initial EPG update is notified , there is a hard coded second update

void CPVRTimers::Notify(const Observable &obs, const ObservableMessage msg)
{
  if (msg == ObservableMessageEpgContainer)
    CServiceBroker::GetPVRManager().TriggerTimersUpdate();
}
