### ISSUE TITLE
AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by islipfd19** [xbmc/xbmc#15432]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi suddenly/randomly stops playing on android 8.0 (Nvidia Shield v7.2.2). Working with the LibreELEC team (I'm a team member) we were able to narrow down the possible cause of this issue being related to the quantity of video playlists (m3u files).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should not stop running/playing when there is a large quantity of video playlists

## Actual Behavior

I have a large collection of movies, and a number of them are within sets, and with these sets I've created playlists. I have more than one hundred video playlists. This large quantity of playlists will cause Kodi stop running and Nvidia Shield returns to the home screen. There is no Kodi crash report, I've enabled debugging in Kodi to collect as much information as I can though there is nothing worth while that I can see in the logs.

I have also noticed that the more video playlists there are Kodi will stop more often.

### To Reproduce

1. Remove all video playlists and play movies for a long duration (longer than 12 hours). Kodi runs without any issue.
2. Increase the number of play lists until Kodi begins to stop running. I increased the quantity of playlists by 10 until I was able to get Kodi to stop. After having 60 playlists in the video folder Kodi can/will stop playing within an hour or so.
3. I began to remove one playlist at a time to determine the maximum number of playlists that can theoretically be listed without Kodi stopping and I've reached the quantity of 49.
4. To determine if it was quantity was the issue over the number of total playlist entries in a file. I listed all of the playlist contents into a single file formatted properly and Kodi did not stop. It played for a few hours.
5. It was suggested that I take a logcat from the Nvidia Shield to determine if there were any OOM errors. To do this I placed a large quantity of playlists in the video folder (approx 100), this guaranteed that (at least for me) to be reproducible. Before starting Kodi I began to capture the logcat and noticed the following in the logs.

AndroidRuntime: FATAL EXCEPTION: AsyncTask #7
02-05 09:39:17.232  9213  9391 E AndroidRuntime: Process: org.xbmc.kodi, PID: 9213
02-05 09:39:17.232  9213  9391 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at android.os.AsyncTask$3.done(AsyncTask.java:353)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:271)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at java.lang.Thread.run(Thread.java:764)
02-05 09:39:17.232  9213  9391 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at android.os.Parcel.readException(Parcel.java:1959)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at android.os.Parcel.readException(Parcel.java:1897)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:180)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at org.xbmc.kodi.channels.util.TvUtil.scheduleTriggeredSyncingProgramsForChannel(TvUtil.java:223)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at org.xbmc.kodi.channels.SyncChannelJobService$SyncChannelTask.doInBackground(SyncChannelJobService.java:206)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at org.xbmc.kodi.channels.SyncChannelJobService$SyncChannelTask.doInBackground(SyncChannelJobService.java:78)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-05 09:39:17.232  9213  9391 E AndroidRuntime:     ... 4 more
02-05 09:39:17.234  3759  6431 W ActivityManager:   Force finishing activity org.xbmc.kodi/.Main

### Debuglog

The debuglog can be found here:
[kodi-56 video playlists.log](https://github.com/xbmc/xbmc/files/2832833/kodi-56.video.playlists.log)
[nvidia-shield-logcat.log](https://github.com/xbmc/xbmc/files/2832835/nvidia-shield-logcat.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android (8.0) Nvidia-Shield v7.2.2
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18 Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by islipfd19** [comment]
Issue still exists for version 18.1.

**Comment by islipfd19** [comment]
Issue still exists for Nvidia Shield version 7.2.3.

**Comment by IAmTheDude** [comment]
`Shield Pro 2019, 8.1.0 (32.7.301.32)`

Was scratching me head on this one until I stumbled on this issue. My [Kodi forum post here](https://forum.kodi.tv/showthread.php?tid=340352)

Was in the same boat, 17.6 ran all off playlists. Tried loads of different things but was about to give up until I found this post here. I knew it was related to '100 jobs' and 'channels' but Git search never brought up this post (_SyncChannelTask_ did though)

Originally thought it was to do with the TV side of it with all the Channel info preceding ie: 

```12-12 11:18:19.951 10179 11086 D TvUtil  : Channel already exists. Returning channel 130 from TV Provider.
12-12 11:18:19.954 10179 11086 D TvUtil  : Channel already exists. Returning channel 131 from TV Provider.
12-12 11:18:19.958 10179 11086 D TvUtil  : Channel already exists. Returning channel 132 from TV Provider.
12-12 11:18:19.962 10179 11086 D TvUtil  : Channel already exists. Returning channel 133 from TV Provider
```
It wasnt until I left in a misnamed playlist (.xps**1**) did I see the relation of playlists to channels in the logs:

```
12-12 15:52:26.022 19215 22873 D TvUtil  : Creating channel: 01   TV Shows.xsp1
12-12 15:52:26.026 19215 22873 D TvUtil  : channel insert at content://android.media.tv/channel/209
12-12 15:52:26.026 19215 22873 D TvUtil  : channel id 209
12-12 15:52:26.041  3680 11102 W JobScheduler: Too many jobs for uid 10136
--------- beginning of crash
12-12 15:52:26.098 19215 22873 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #11
12-12 15:52:26.098 19215 22873 E AndroidRuntime: Process: org.xbmc.kodi, PID: 19215
12-12 15:52:26.098 19215 22873 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1958)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1918)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1868)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:184)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at org.xbmc.kodi.channels.util.TvUtil.scheduleTriggeredSyncingProgramsForChannel(TvUtil.java:223)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at org.xbmc.kodi.channels.SyncChannelJobService$SyncChannelTask.doInBackground(SyncChannelJobService.java:206)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at org.xbmc.kodi.channels.SyncChannelJobService$SyncChannelTask.doInBackground(SyncChannelJobService.java:78)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	... 4 more
12-12 15:52:26.098 19215 22873 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at com.android.server.job.JobSchedulerService.scheduleAsPackage(JobSchedulerService.java:881)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2579)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:60)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:731)
12-12 15:52:26.098 19215 22873 E AndroidRuntime: 
12-12 15:52:26.103  3680  6027 W ActivityManager:   Force finishing activity org.xbmc.kodi/.Main
```

Taking out playlist one-by-one to no avail though, mine crashes with even just one playlist so have had to scrap them all for the time being. and move to basic multi-path sources.

17.6 was stable but now I can enable auto-updates apps again with 18 :)
