### ISSUE TITLE
Regression Leia v18.0 - Nvidia Shield TV - playing 4K files impossible

### ISSUE THREAD

**Issue by EmEnVee** [xbmc/xbmc#15433]
### Describe the bug
Here is a clear and concise description of what the problem is:

The issue appeared after auto update from v17 to v.18.0, i.e. regression.

HW: 4K Samsung TV, Nvidia Shield TV. 

SW: All latest stock updates. Kodi auto updated via Google Play.

If Kodi resolution is set to one out of two (sic) 3840x2160, the entire GUI is visible, but any video playback shows only upper left quadrant of the picture full screen (controls are functional, but are outside of viewing area). This happens no matter what is the source video's resolution.

If Kodi resolution is set to the other out of two (sic) 3840x2160, the only upper left quadrant of GUI is visible (full screen). I did not attempt to proceed further, reverting to the previous setting instead.

If Kodi resolution is set to 1920x1080, GUI and playback of videos of up to FullHD are OK. 4K video playback shows only upper left quadrant of the picture full screen (controls are functional, but are outside of viewing area). 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

1. One 3840x2160 resolution available.
2. 4K video playback displays the entire picture full screen

## Actual Behavior

See above.

## Possible Fix

It worked fine in v17.6, no?

### To Reproduce

1. See above.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system: Nvidia Shield TV (the latest)

 - [ x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You forgot to provide a debuglog. Please do that. 

We'll mark this issue as invalid for the time being you need to provide a logfile. Be aware, that we will close that issue in 3 days, if no log is submitted.
