### ISSUE TITLE
Kodi v18 Leia - Certified certificates can not be authenticated with given CA certificates

### ISSUE THREAD

**Issue by 32Dexter** [xbmc/xbmc#15440]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'd like to see a video on the Wstream site (https://wstream.video) where the link looks like this:
https://wpurple.fastcdn.stream/xyz/v.mp4
Unfortunately when I go to reproduce the link Kodi v18 releases this error in the log:
Certified certificates can not be authenticated with given CA certificates (60).
Is it possible to deactivate this function? Otherwise how can I escape it? Thank you

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The video in the version of Kodi v17.6 works perfectly but in the new version of Kodi v18 the movie does not start.

## Actual Behavior

Unfortunately, the movie does not start

## Possible Fix

I ask if you can disable this feature? Otherwise how can I avoid it?

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 7 x64 Pro - Windows 10 x64
 - Kodi version: v18 Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
For support questions, please head to the [forums](https://forum.kodi.tv/) - we use GitHub exclusively for technical issues with the core. Thanks!
