### ISSUE TITLE
Kodi 18 - nvidia shield - random - video not starting - dialogBusy ad vitam

### ISSUE THREAD

**Issue by djoole** [xbmc/xbmc#15447]
### Video playback not starting, UI stuck on DialogBusy

This problem is random, but occurs quite often. When the shield is waken up, often on first wanted playback. When the problems occurs, it does for any video. A kodi soft restart is needed to get back to a normal situation.

In the logs, I see this : 
>08:09:06.523 T:26124  NOTICE: VideoPlayer: OnLostDisplay received

and this : 

>08:09:07.524 T:26124   ERROR: Flush - timed out waiting for renderer to flush

### Debuglog
The debuglog can be found here: https://paste.ubuntu.com/p/sFXzDTNF3q/

### Environment
Used Operating system: Android 8.0.0 API LEVEL 26 (KERNEL: LINUX 4.9.109-TEGRA-G2DAFED3)
Kodi version: 18.0 GIT:20190128-D81C34C

**Comment by djoole** [comment]
Arg.. By now I would have thought to get some support from other user getting the same issue.. pleaaaase don't tell me i'm alone to get this :(
Everything was working flawless with krypton but now I get this issue everytime i want to launch a video on a kodi which has been idle for a while (first video launch in the morning, first video launched after getting back from work, etc.)

**Comment by double-bee** [comment]
I have exactly the same issue, exactly the same operating system and Kodi version. It happens almost every time after the shield wakes up. Unfortunately, i can't reproduce it so that happens every time. The only way for me to recover is "force stop" Kodi using the shield menu.

**Comment by djoole** [comment]
Yes, it's systematic after a while doing nothing. Very annoying.

**Comment by djoole** [comment]
Please if any one has or hasn't got the same problem with the same setup, let us know.. I'm desperate to see this issue advance... I have this bug everytime I want to use Kodi after being a while idle.

**Comment by McChen147** [comment]
i have this issue as well. it's not exclusive to the shield, i have this problem on my shield and the mi box. they are both on oreo

**Comment by stefano70** [comment]
I can test since I have two Android TV: nVidia Shield TV and a Mi Box S
I am not suffering this problem. can you shortly advise hot to reproduce?

**Comment by djoole** [comment]
Let the shield idle for a while with kodi started. Systematic for me.

Here is a new full debug log (shorter, cleaner, without library update in it) : 
https://paste.ubuntu.com/p/sFXzDTNF3q/

**Comment by McChen147** [comment]
I just tested 18.1 rc1 and this issue is still there. Tested on Shield TV, original Mi Box and the Mi Box S, all on oreo

**Comment by stefano70** [comment]
Got it !
Tested on both nVidia Shield TV and Mi Box S too.
It happens ALWAYS (in my personal setup) playing some DVDs (I mean DVD ripped from original media with the classic folders\file structure).

I removed Kodi 18 Leia and manually re-installed Kodi 17.6 because of other problems, but my little daughter called me for help, since she was trying to view a movie and Kodi was blocked.
I checked and Kodi 18 was again there, because I forgot to stop automatic updates.

So, no way to play this DVD; have to kill kodi and play something else.
The same with other DVD
With some classic DVD ripped from my personal collection to save space in the bookshelf, they start playing but video is stuttering. Audio OK.

**Comment by djoole** [comment]
Not the same problem.
My issue is not related to a specific video. It's any video after a while idle. Actually I haven't tested with DVDs, only MKVs.

**Comment by McChen147** [comment]
I only use Kodi for DVR, it happens for me with the recorded TV files through ServerWMC. I have to shutdown Kodi and restart the app to fix it. Oddly, it doesn't happen with Live TV streams though

**Comment by djoole** [comment]
Maybe it has something to do with network access?
All of you who get this issue, what share do you use? I'm using SMB.

**Comment by McChen147** [comment]
I'm also using SMB via ServerWMC

**Comment by orty87** [comment]
I have a similar Problem.

I use kodi 18.1 on my shield tv with the addon plexkodiconnect. 

When I start kodi fresh, the Video Playback works. 

But If i press the home Button to minimize kodi, Set the shield to sleep, wakeup the shield and open kodi again, the Video files don't play anymore. It just loads forever.

When I close kodi through the menu and Start it again the playback issue is gone.

**Comment by djoole** [comment]
Any news from the support? Did you have the chance to analyse the logs?

**Comment by fritsch** [comment]
All slots currently taken ... waiting for new volunteers to arrive.

**Comment by djoole** [comment]
Still getting this issue on daily basis.. guess I'll have to put in my habit to quit kodi before turning off the shield, a pity (never had an issue with krypton).
Kodi version: 18.1 GIT:20190222-75DC3D5

**Comment by PetitCanard** [comment]
Same problem on shield TV, after standby, the frist Video playback not starting,
i need to close Kodi and restart for working

**Comment by djoole** [comment]
Still getting this issue on daily basis.. 

Kodi 18.1 GIT:20190311
Android 8.0.0 API LEVEL 26 (KERNEL: LINUX 4.9.109-TEGRA-G4FA2F5B)
Shield Android TV 7.2.3(30.6.131.70)

**Comment by McChen147** [comment]
18.2 rc1 still has this issue

**Comment by djoole** [comment]
Couldn’t tell, I’ve taken the habit to kill Kodi after using it and before putting the shield to sleep.

**Comment by Scooper2** [comment]
Maybe a bit far fetched, but do you guys use a Flirc as receiver for your remote? I did and after the update I encountered this issue. I also found that Kodi wants to play the last played file again when resuming from sleep. Could it be that some shortcuts has been changed in the update? (this affects Flirc)

My Harmony One broke recently and I bought a new Harmony Elite which doesn't use IR to communicate with the Shield and I don't seem to have the issue anymore. I don't need to restart Kodi to be able to play a video after resuming from sleep.

**Comment by djoole** [comment]
NI, I use original shield remote

**Comment by santakrooz** [comment]
I'm get the same "no video" every time after waking from sleep on Shield now. Requires a Kodi exit and re-launch to fix. I don't think it's SMB, it's getting the file ok, there is audio, but the video shown is the main UI and it's navable, but slightly confused UX tho (extra icons, some double menu entires etc).  Exit and restart Kodi, and you get video and audio like always before. 

Kodi 18.3 Git:20190619-89472b7d69
Android 8.0.0 Kernel 4.9.109-tegra-g4fa2f5b
Shield 7.2.3(30.6.131.70)

**Comment by jeppuraj** [comment]
Same issue here. If my shield has been asleep I have to restart Kodi, else I get audio only when playing video files. I have had this issue for at least 2 months.

Kodi 18.3 Git:20190619-89472b7d69
Android 8.0.0 Kernel 4.9.109-tegra-g4fa2f5b
Shield 7.2.3(30.6.131.70)

**Comment by namob** [comment]
I got the exact same problem with a Nvidia Shield 2015 and Kodi 18.4. This has been a problem for me since 18 got released. Only way to fix it is to stop the app and start it again. Affects PVR and any regular movie file (AVI, MKV, DVDISO and so on)

**Comment by kaazvaag** [comment]
I also having this issue. Kodi sometimes freezes after I stop a video file. Only fix is to force stopping the app and start it again.

**Comment by Bulletbling** [comment]
Same issue. Happens anytime I play a remux video on my Nvidia Shield with Kodi Leia 18.9. I get the exact same flush error.

**Comment by kszaq** [comment]
Possible cause: https://github.com/xbmc/xbmc/pull/13629/files#r178433923
