### ISSUE TITLE
Malware downloaded with Beta 18 'leia' 

### ISSUE THREAD

**Issue by jloome** [xbmc/xbmc#15446]
### Malware
Here is a clear and concise description of what the problem is:
Malwarebytes
www.malwarebytes.com

-Log Details-
Protection Event Date: 2/6/19
Protection Event Time: 12:23 PM
Log File: bdd58858-2a44-11e9-92e8-f0795961fc17.json

-Software Information-
Version: 3.6.1.2711
Components Version: 1.0.527
Update Package Version: 1.0.9146
License: Premium

-System Information-
OS: Windows 10 (Build 17134.523)
CPU: x64
File System: NTFS
User: System

-Blocked Website Details-
Malicious Website: 1
, , Blocked, [-1], [-1],0.0.0

-Website Data-
Category: Malware
Domain: rgho.st
IP Address: 104.27.181.254
Port: [56628]
Type: Outbound
File: C:\Program Files\Kodi\kodi.exe

This appears to have been embedded in either the build or an addon around Jan. 24.
I believe it's likely the iptv simple client player, as that's the only additional code I have installed. Everything else is minimal install.

My email is j_loome@yahoo(dot)com if you need to reach me.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Windows 10 Home 64 bit
16 gb
i5 -4690k

**Comment by lrusak** [comment]
I'm going to say you have some nasty piracy add-ons installed. A debug log would be able to prove that if you provided one.

**Comment by jloome** [comment]
I've turned on logging and will demonstrate I have no 'add ons' installed other than IPTV simple client.
I've got an iptv subscription but it's connecting directly through simple client. 
I have all auto updates turned off. It gives me an update check notice each time I log on but I ignore it because it's a beta build anywhere.




    On Wednesday, February 6, 2019, 12:55:22 PM MST, Lukas Rusak <notifications@github.com> wrote:  
 
 
I'm going to say you have some nasty piracy add-ons installed. A debug log would be able to prove that if you provided one.

**Comment by lrusak** [comment]
I'm still waiting for a debug log. 

Also Kodi V18 final is out so you may want to update to that as it sounds like you are on a beta.

**Comment by jloome** [comment]
I tried turning it on and a bunch of code came up in the corner of the screen. when I turned it off, I went through the 'kodi' folder on my computer and I couldn't find a 'debug' report but there were hundreds of 'crash' reports, and a crapload of stuff that I didn't recognize. 
I suspect my son has been fiddling with it when I'm  not around and downloading things he shouldn't, as there were at least three other builds in there, some downloaded plugins or addons, some movie files.
Sorry about that.
    On Wednesday, February 6, 2019, 1:41:30 PM MST, Lukas Rusak <notifications@github.com> wrote:  
 
 
I'm still waiting for a debug log.

Also Kodi V18 final is out so you may want to update to that as it sounds like you are on a beta.

**Comment by jloome** [comment]
Also, in the event of future problems, where do I find a debug log?
    On Wednesday, February 6, 2019, 1:41:30 PM MST, Lukas Rusak <notifications@github.com> wrote:  
 
 
I'm still waiting for a debug log.

Also Kodi V18 final is out so you may want to update to that as it sounds like you are on a beta.

**Comment by MartijnKaijser** [comment]
Please look at our wiki which has all info needed
Closing this ticket now.
