### ISSUE TITLE
Cursor Mouse Issue

### ISSUE THREAD

**Issue by Golgo0013** [xbmc/xbmc#15451]
I am having an issue with Leia where the Cursor only appears & works in the top left hand quarter of the screen.  The rest of the screen is has no affect except that on the normal cursor scrolling across the desktop.

I am running a Mac Pro with Mojave.

**Comment by lrusak** [comment]
Why did you not use the issue template?

Can you provide a debug log?

**Comment by Golgo0013** [comment]
Hi Lukas,

This is my first time having to report a problem. There is no log, because no error is reported on screen, it’s just the mouse will not respond on screen like it does in Krypton.

Regards,

Fabian Mavath
Ph: +61 0418 337 337
fabian.mavath@mac.com

**Comment by a1rwulf** [comment]
@Golgo0013 You did not answer @lrusak 's question.
If you use the issue template that gives us very valuable information on how to track down your problem.
So why did you just throw the text away and start from scratch?
That being said, please use the information provided in the following link and post a link to your debug log:
https://kodi.wiki/view/Log_file

**Comment by Golgo0013** [comment]
While I understand this is frustrating for you dealing with a Noob like me, the problem is there is no way to navigate in Kodi's Leia to get the log's as the mouse cursor or using the keyboard will not move to those settings so I have now way of uploading a debug log for you.

**Comment by a1rwulf** [comment]
It wouldn't be frustrating if you would actually read(!!!) the information you got from me.
There's even a dedicated section in the wiki about `3 Kodi Is Unresponsive`.
So I'd suggest you start actually reading what you get from us, otherwise you'll need to fix the issue without any help.

**Comment by DaVukovic** [comment]
I´ll mark this a invalid for the time being. The label will be removed if we see a log.
