### ISSUE TITLE
Kodi 18 does not shows posters if file name is not <movie_name>-poster.jpg

### ISSUE THREAD

**Issue by stefano70** [xbmc/xbmc#15463]
### Describe the bug

Kodi 18 Leia does not show movie posters whenever the poster's file name is in the form
poster.jpg
Kodi 18 seems able to show posters only if the file name is in the form
<movie_name>-poster.jpg
Kodi 17.x does not suffer.

## Expected Behavior

Make Kodi 18 behaves like previous versions.

## Actual Behavior

Kodi 18 displays movie thumbnails instead of posters whenever posters are not
<movie_name>-poster.jpg

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10, Android 8, Android TV 8
 - Kodi version: 18 Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Abbreviated artwork names are scanned when the following conditions are met...
1. Movie Folders are used
2. **Movies are in separate folders that match the movie title** must be **Enabled** in the Set Content Screen.

This setting also allows the **movie.nfo** filename to be scanned.

This has not changed in v18 and operated the same in v17. I suggest that you have forgotten to enable the setting.

This is not a bug. There is no debug log which makes this an invalid report. This issue will be closed shortly.

**Comment by KarellenX** [comment]
https://forum.kodi.tv/showthread.php?tid=340426

**Comment by stefano70** [comment]
Thanks for the feedback.
Anyway before opening this "bug" I read carefoully the official documentation
https://kodi.wiki/view/Movie_artwork#Movie_.22poster.22
Where I read that both
poster.jpg
<movie_name>-poster.jpg
are both supported
Running Kodi 17.x, posters are showed with both the naming, but with Kodi 18 Leia only with the second one.

**Comment by stefano70** [comment]
KarellenX
1. I am using movie folders
2. half of the movies are in folders that match the movie name, other half are not
3. Kodi 18 Leia is showing posters only if posters' file are in the form <movie_name>-poster.jpg
4. This happens regardless the radio button "Movies are in separate folders that match the movie title"
5. Tested on two Windows (10 and 2016)

**Comment by DaVukovic** [comment]
@stefano70 

>Anyway before opening this "bug" I read carefoully the official documentation

then you didn´t read carefully enough ;)

> The short name can only be used if your movie source folder is configured with Movies are in separate folders that match the movie title

So you also should have your movies in seperated folders. As that´s the structure how it should be, shown at this section:

https://kodi.wiki/view/Movie_artwork#Local_movie_artwork

As you can see there for the poster.jpg:


`poster  ->   poster.jpg  ->    f:\Movies\Blade Runner 2049 (2017)\poster.jpg`

It clearly shows, that the poster.jpg needs to be stored under the specific moviename-folder. If you don´t have a moviename folder, I highly guess that won´t work and you should use `<moviename>-poster.jpg` instead. 

Anyway, `<moviename>-poster.jpg` will always work, regardless if you store your movies inside seperated folders or not. Hence Kodi always exports posters in that way. 

So you can say:

`<moviename>-poster.jpg` - works if you store movies in seperated folders or not
`poster.jpg` - only works if you have stored your movies in seperated folder **AND** have the `Movies are stored in seperated folders matching the moviename` checked

**Comment by stefano70** [comment]
If you read what I wrote,
having movie's file inside a folder with the same movie's name\title, having enabled the radio button 4\. "Movies are in separate folders that match the movie title", then Kodi 18 shows the correct poster if and only the poster's file is in the form movie_name-poster.jpg.

Keep in mind: I appreciate a lot the effort the Kodi team is spending, but I am using Kodi since YEARS and sorry to say... but moving from 17.x to 18 Leia... something changed for sure because I have the expected behaviour with Kodi 17.x and the unexpected behaviour upgrading to 18 and the movie repository is the same for all.

I understand that using movie_name-poster.jpg always works, but docs are saying that even poster.jpg must works (under some conditions I am adopting).

Regards.

**Comment by DaVukovic** [comment]
>     2\. half of the movies are in folders that match the movie name, other half are not

What sense does it make to enable "Movies are in folders matching the moviename" if half of your movies aren´t stored that way?

Store **all** your movies inside seperated folders and I highly guess it will magically work with the short version (not tested yet, but I will). My guess is, that if you have a mixed structure (mixed in meaning of some movies are in separated folder and some are not), Kodi will simply search for the filename which woll work for both, regardless of the setting. So I still understand that as expected behaviuor. Not too sure, tbh.

**Comment by stefano70** [comment]
So, I cleaned up all my test computer and setup 1 single movie for the test.

Here you can find the filesystem structure
![short_naming_folder](https://user-images.githubusercontent.com/24544301/52475982-83a50280-2b9d-11e9-8626-512acb666b56.jpg)

The Kodi 18 Leia settings
![kodi_18_settings](https://user-images.githubusercontent.com/24544301/52476013-9fa8a400-2b9d-11e9-8c32-4810c50c1cef.jpg)

The Kodi 18 Leia poster display after scarping the above single folder
![kodi_18_display](https://user-images.githubusercontent.com/24544301/52476055-bcdd7280-2b9d-11e9-8f06-0179d28ee259.jpg)

As you can see, Kodi is displaying the movie thumbnail instead of the poster

Then, keeping the same test folder, removing Kodi 18, deleting the database, etc. and installing Kodi 17.6
Here the same settings for Kodi 17.6
![kodi_17 6_settings](https://user-images.githubusercontent.com/24544301/52476119-fca45a00-2b9d-11e9-84e0-0d37f3ad9cae.jpg)

And then what Kodi 17.6 display. You can see that the poster is the correct one.
![kodi_17 6_display](https://user-images.githubusercontent.com/24544301/52476149-15147480-2b9e-11e9-9e1c-7e0f97920ad1.jpg)

Movie are in separate folders, Folder's name and movie file match the movie title, there is no mess since I have 1 only file for the test.
What else?

Regards.

**Comment by DaVukovic** [comment]
Thanks for testing. 
>What else?

a debuglog showing that behaviour would be nice now

**Comment by DaVukovic** [comment]
Btw, I can't reproduce your issue using Estuary:

![poster](https://user-images.githubusercontent.com/7235787/52477271-97eafe80-2ba1-11e9-91ce-46940320455e.png)

- Added some movies stored in folders matching the moviename
- Let Kodi export the library to separated files
- renamed the specfic files from <moviename>-poster.jpg to poster.jpg
- as Estuary doesn't export thumbs from movies automatically I downloaded some ramdom image and named it "thumb.jpg"
- then I swapped the filenames from the thumb to the actual poster file ("poster.jpg" became "thumb.jpg" and otherwise)
- deleted my .kodi folder to have a vanilla Kodi
- added a source, selected to use nfo only, and enabled the "folders matching the moviename"-setting

as you can see, the poster.jpg is perfectly used (showing the thumb ;) ) as the poster like shown in the filestructure at the screenshot above.

Tested with Kodi 18 on Ubuntu.

**Comment by stefano70** [comment]
OK. here is the link of the full debug log.
[https://paste.kodi.tv/ifaposutes.kodi](url)
Unfortunately on this test PC there is no audio card, so you can see a lot of errors belonging to this matter.
the scan\scraping starts at T = 16:20:08.457
You can see that Kodi 18 Leia find the movie, load the .nfo, but does not cache the artworks.

Many thanks for your effort.

**Comment by DaVukovic** [comment]
Could you please enable "Component specific logging" and also enable "Verbose logging for the Database component" 

Your log currently doesn't show enough informations about which images are cached and which not. 

I did further tests and I'm still not able to reproduce. Further more Kodi behaves exactly like it should:

Here does my scan start:

```
19:12:42.324 T:140411851691776  NOTICE: VideoInfoScanner: Starting scan ..
19:12:42.324 T:140412307166976   DEBUG: CAnnouncementManager - Announcement: OnScanStarted from xbmc
19:12:42.324 T:140412307166976   DEBUG: GOT ANNOUNCEMENT, type: 16, from xbmc, message OnScanStarted
19:12:42.324 T:140411851691776   DEBUG: VideoInfoScanner: Scanning dir '/home/davu/Videos/Filme/' as not in the database
19:12:42.325 T:140411851691776   DEBUG: VideoInfoScanner: No (new) information was found in dir /home/davu/Videos/Filme/
19:12:42.325 T:140411851691776   DEBUG: VideoInfoScanner: Scanning dir '/home/davu/Videos/Filme/minority_report/' as not in the database
19:12:42.329 T:140411851691776   DEBUG: VideoInfoScanner: Found matching full NFO file: /home/davu/Videos/Filme/minority_report/minority_report.nfo
19:12:42.334 T:140411851691776   DEBUG: Caching image '/home/davu/Videos/Filme/minority_report/thumb.jpg' to '8/8c01d965.jpg':
19:12:42.334 T:140411851691776   DEBUG: cached image 'special://masterprofile/Thumbnails/8/8c01d965.jpg' size 480x720
19:12:42.362 T:140411833104128   DEBUG: Caching image '/home/davu/Videos/Filme/minority_report/fanart.jpg' to '1/1ca48d42.jpg':
19:12:42.362 T:140411833104128   DEBUG: cached image 'special://masterprofile/Thumbnails/1/1ca48d42.jpg' size 1920x1080
19:12:42.363 T:140411851691776   DEBUG: VideoInfoScanner: Adding new item to movies:/home/davu/Videos/Filme/minority_report/minority_report.mp4
19:12:42.377 T:140412307166976   DEBUG: CAnnouncementManager - Announcement: OnUpdate from xbmc
19:12:42.377 T:140412307166976   DEBUG: GOT ANNOUNCEMENT, type: 16, from xbmc, message OnUpdate
19:12:42.380 T:140411851691776   DEBUG: VideoInfoScanner: Finished adding information from dir /home/davu/Videos/Filme/minority_report/
19:12:42.382 T:140411851691776  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
19:12:42.382 T:140412307166976   DEBUG: CAnnouncementManager - Announcement: OnScanFinished from xbmc
19:12:42.382 T:140412307166976   DEBUG: GOT ANNOUNCEMENT, type: 16, from xbmc, message OnScanFinished
19:12:42.390 T:140412897061248   DEBUG: CGUIMediaWindow::GetDirectory (sources://video/)
19:12:42.390 T:140412897061248   DEBUG:   ParentPath = [sources://video/]
19:12:42.390 T:140411632850688   DEBUG: Thread waiting start, auto delete: false
19:12:42.390 T:140411632850688   DEBUG: Thread waiting 140411632850688 terminating
19:12:42.390 T:140411833104128   DEBUG: Caching image '/home/davu/Videos/Filme/minority_report/poster.jpg' to '0/0b380a46.jpg':
19:12:42.390 T:140411833104128   DEBUG: cached image 'special://masterprofile/Thumbnails/0/0b380a46.jpg' size 256x256
```

You can see, that both, the thumb.jpg and the poster.jpg are cached. The important part is

```
19:12:42.390 T:140411833104128   DEBUG: Caching image '/home/davu/Videos/Filme/minority_report/poster.jpg' to '0/0b380a46.jpg':
19:12:42.390 T:140411833104128   DEBUG: cached image 'special://masterprofile/Thumbnails/0/0b380a46.jpg' size 256x256```

make a note: `0/0b380a46.jpg`

Then I swapped the images (poster.jpg <-> thumb.jpg) and refreshed the movie information, which starts here:

```
19:16:18.700 T:140412897061248   DEBUG: VideoInfoScanner: Found matching full NFO file: /home/davu/Videos/Filme/minority_report/minority_report.nfo
19:16:18.713 T:140412897061248   DEBUG: DialogProgress::Open called
19:16:18.713 T:140412897061248   DEBUG: ------ Window Init (DialogConfirm.xml) ------
19:16:19.105 T:140412307166976   DEBUG: CAnnouncementManager - Announcement: OnRemove from xbmc
19:16:19.105 T:140412307166976   DEBUG: GOT ANNOUNCEMENT, type: 16, from xbmc, message OnRemove
19:16:19.135 T:140412897061248   DEBUG: GetMovieId (/home/davu/Videos/Filme/minority_report/minority_report.mp4), query = select idMovie from movie where idFile=1
19:16:19.145 T:140412897061248   DEBUG: VideoInfoScanner: Found matching full NFO file: /home/davu/Videos/Filme/minority_report/minority_report.nfo
19:16:19.162 T:140411632850688   DEBUG: Recaching image '/home/davu/Videos/Filme/minority_report/poster.jpg' to '0/0b380a46.jpg':
19:16:19.162 T:140411632850688   DEBUG: cached image 'special://masterprofile/Thumbnails/0/0b380a46.jpg' size 480x720
19:16:19.196 T:140412897061248   DEBUG: VideoInfoScanner: Adding new item to movies:/home/davu/Videos/Filme/minority_report/minority_report.mp4
19:16:19.196 T:140412897061248   DEBUG: GetMovieId (/home/davu/Videos/Filme/minority_report/minority_report.mp4), query = select idMovie from movie where idFile=1
```

Here the important part is:

```
19:16:19.162 T:140411632850688   DEBUG: Recaching image '/home/davu/Videos/Filme/minority_report/poster.jpg' to '0/0b380a46.jpg':
19:16:19.162 T:140411632850688   DEBUG: cached image 'special://masterprofile/Thumbnails/0/0b380a46.jpg' size 480x720
```

Note: It "recaches" the image to `0/0b380a46.jpg` which is the same cached filename as above, but as you can see it has another resolution which indicates, that it's now the actual cover and not the dummy thumb I added. So the name "poster.jpg" is always used to show the thumb. 

I'm completely out of ideas what might go wrong on your side as it's exactly the behaviour me and @KarellenX  are telling you how Kodi should work and how it works obviously. 

Here is my full log for reference so you are able to see I'm not kidding you. 

http://paste.ubuntu.com/p/h6Jggfkwyb/

**Comment by stefano70** [comment]
[https://paste.kodi.tv/juticusazi.kodi](url)

here there is the detailed log.
Scanning start at row 1144

Regards.

**Comment by KarellenX** [comment]
@stefano70

Can you please provide the nfo file for Babel (2006)

Also, can you use a different computer to test this, as the Audio spam is making it extremely difficult to follow the scrape in the log. 

Three of us have tested this scenario, but unable to replicate. We now want to add your nfo file to our replicated folder.

If you remove the nfo file, do you still have the same issue with Artwork? You will have to replace Local Info Only scraper with TheMovieDB scraper

**Comment by stefano70** [comment]
Here is the .nfo file
[https://paste.kodi.tv/ogiyorudud.kodi](url)

Later I will try do find a sound card to plug into this Windows PC.

**Comment by DaVukovic** [comment]
I downloaded your nfo file and created the same structure you have. Please see:

![test-poster](https://user-images.githubusercontent.com/7235787/52524413-0cef2e80-2c9d-11e9-883f-aa426b77f18d.png)

Everything works as expected even with your NFO file and the exact filenamings you are using.

**Comment by stefano70** [comment]
I see... thanks for your tests.

Unfortunately I do not have a deep knolwledge on Kodi in order to try to find out where is the problem.
Anyway, I appreciate you demonstrate the correct working, but also consider please that I can reproduce the issue.

Anyway, let me ask 2 questions... to let me better understand how the process works:
1) the setting "Movies are in separate folders that match the movie title"
Literally should mean that each movie is in a dedicated folder and each folder's name matches the movie title
All my movies are in separate folders... one movie... one folder, but not always folder's name matches the movie title, but I never cared since with Kodi 17.x it always worked fine.
I do not understand the correct relationship between:
movie FILE name
Movie title
Folder name

2) is the .nfo file involved to let Kodi to load\cache and/or show the artworks?
I mean... since in the .nfo there is no reference to the poster

**Comment by KarellenX** [comment]
@stefano70 

We are not discounting this report anymore. We "think" there may be a bug somewhere and we are proceeding under that assumption. We are not sure if it is a skin issue, or core issue. It is just a pity that three of us cannot replicate the issue.

@rmrector , one of the developers is looking into it, but don't expect a quick fix as these pesky little bugs can be difficult to track down.

As for your other questions, I will answer them on the forum. I don't want to clutter up this thread with too much off topic discussion.

**Comment by stefano70** [comment]
KarellenX
you asked:
If you remove the nfo file, do you still have the same issue with Artwork? You will have to replace Local Info Only scraper with TheMovieDB scraper

1) if I remove the .nfo file and keep the same settings, then instead of the poster Kodi displays the icon of a videocamera
2) If I replace the scraper with the TMDB scraper, then Kodi correctly displays the right poster

Moreover, if then I export the Kodi library, then the movie folder is populated with the following:
- .nfo file generated by Kodi
- movie_name-poster.jpg

At this point if I delete again the source, clean the library and rescan with local info only, then everything is perfect.
Again, I remove the source, clean the library, rename the movie_name-poster.jpg into poster.jpg and rescan, again... poster not shown but replaced with it's thumbnail.

I can say that:
- with Kodi 17, was always perfect
- with Kodi 18 and movie_name-poster.jpg is again always perfect
- with Kodi 18 and poster.jpg, it is quite a mess and I am not able to find a rule.

**Comment by boerngen-schmidt** [comment]
Hi everyone,
I experience the same Behavior as @stefano70 does. One thing I noticed is, that when I select a movie and hit refresh, it tells me that local information is there and will be overwritten by the one from the internet.
Once I update, I see the poster. Then I closed Kodi, changed the poster.jpg to some other, restarted and Kodi does not pick the new poster.jpg.

The problem seems to be:
`DEBUG: Mysql execute: INSERT INTO art(media_id, media_type, type, url) VALUES (455, 'movie', 'poster', 'http://image.tmdb.org/t/p/original/4uIPXX8DjTsCzUAdtMKHTpojYLq.jpg')`

So when Kodi should scan for local media, it prefers the data from the DB and here it should not matter wether I'm using MySQL or SQLite. If I had to guess where to start I would choose https://github.com/xbmc/xbmc/blob/master/xbmc/video/VideoThumbLoader.cpp 
I'm guessing it fails to check wether there is a poster.jpg in the moviefolder and if so take this, compare with the cached Picture, update if nessescary, OR download poster from the internet etc ...

Another thing I noticed was, when I changed the scraper from MovieDB to Local only it updated all my movies, that had nfo files and it corrected the posters using the local files and inserted them into the DB. When I changed back from local to MovieDB it picked up a movie that had no nfo and a wrong (on purpose) poster.jpg and this got added to the DB. Afterwards I deleted the wrong poster.jpg, cleaned the library and updated.
My expected behaviour would have been, that Kodi recognizes, that the cached image is not valid any more (btw why cache it if you have a local resource with a poster.jpg in the folder) since the base file does not exist, thus scans for a new one. But debig logs says skipping since there are no changes.

**Comment by brutog** [comment]
I'm spinning up and migrating to a new server and noticed something similar on 18.5.

I've tried universal scraper and themoviedb scraper. When I scrape a fresh library, movies with poster.jpg end up with a thumbnail poster. Reloading the movie and using the Internet as a source fixes the issue and I get a nice poster.

I'm using mysql as a backend as well.

**Comment by nambpgh** [comment]
On my side (Kodi 18.8, Linux), movies in folders, it's basically working, but something is strange to me and IMHO not okay.

If I have a "poster.jpg" in the folder for a new movie and I scrap it (with Universal Movie Scraper) the poster will be used (as poster, also as thumb). Okay, so far.
If I want to change the poster, the local one is not listed as "Local art" (but of course, it is shown as "Current art"). Other options are "Remote art" (if there are any) and "No art". In other words: I can change the poster to a remote poster or to no poster, but I see no way to change it back to the local "poster.jpg" then. For me this is not okay. "poster.jpg" should always be a proper name for a poster in a movie folder.

For "fanart.jpg" it is working like expected: It is used on adding the move, I can switch to "Remote fanart" (if there are any) but I also have the option to switch back to the "Local fanart". This is how it should be.
On the other side: I'm missing an option "No fanart" in this case and for me this should be a possible option in any case.
