### ISSUE TITLE
Player status not correctly reflected through web api

### ISSUE THREAD

**Issue by jvisser** [xbmc/xbmc#15462]
Hi,

Since updating to kodi 18 final release my home automation system is not correctly working anymore. It dims the lights based on player status (playing or stopped). Sometimes when a video starts playing the lights dim and then undim. When I look up the player status in my home automation system it appears pauzed while the video is playing on screen. This is also reflected in the Yatse android remote and the chorus 2 web interface.

Im running on an Nvidia shield tv.

Hope this can be fixed in the next release 👍

Thanks,
Jvisser

**Comment by MartijnKaijser** [comment]
First you did not follow our issue template.
Second there was a change in the player status code.
Yatsee and chorus have to be updated to follow that change
