### ISSUE TITLE
Unable to run ScummVM

### ISSUE THREAD

**Issue by SzymonZy** [xbmc/xbmc#15475]
### Describe the bug
ScummVM plugin is not runable. It is installed but it does not appear in addons menu and in information screen run is grayed out. Raspberry Pi 3 with LibreElec 9.
[kodi.log](https://github.com/xbmc/xbmc/files/2848109/kodi.log)
[kodi.log](https://github.com/xbmc/xbmc/files/2848111/kodi.log)

ScummVM plugin is not runable. It is installed but it does not appear in addons menu and in information screen run is grayed out. Raspberry Pi 3 with LibreElec 9.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Plugin should appear in addons menu and user should be able to run it. 

## Actual Behavior

Plugin is installed but runing is not enabled. 

### To Reproduce

1.  Install ScummVM plugin on rPi 3 with Libreelec 9
2. Open informations via plugin context menu
3. Check plugin presence in  Add On menu. 

### Debuglog

The debuglog can be found here:

No folder in user data is created. 

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [x] iOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreElec 9
 - Kodi version: Kodi 19 Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
It works the same way other game add-ons work where you need to select the actual file you want to open. You don't open the emulator directly.

This emulator only runs files with a .scummvm extension.

For future usage issues please open a thread in the forum. Thanks.

**Comment by SzymonZy** [comment]
It's unconsistent. In CoreElec it just run and pop up with classic menu. On LibreElec it is slipping out of logic. I didn't receive any support, also find nothing on wiki.

**Comment by CvH** [comment]
we push some update that should fix this, hopefully
