### ISSUE TITLE
DVD (video_ts) not scanned to the library anymore

### ISSUE THREAD

**Issue by djoole** [xbmc/xbmc#15473]
### Video library update no longer adds DVDs (video_ts folders) to the library
Here is a clear and concise description of what the problem is:

Video library scanner don't scan (DVD) film folders with video_ts subfolders

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video library scanner should go through DVD folders

## Actual Behavior

I have some DVDs in one folder which is scanned by Kodi as films.
Folders are structured as movie_title (year)/video_ts/xxxxx
xxxx are common dvd files (video_ts.bup, video_ts.ifo, vts_01_0.bup, vts_01_0.ifo, etc
and in video_ts dir there is also a video_ts.nfo file containing metadata

Well, these movies are not scanned anymore, not a trace in the logs.

## Possible Fix

Go back to where it worked before? I looked for a specific setting but couldn't find any

### To Reproduce

1. Put a DVD rip in on of your source movie folder, with structure "movie_title (year)/video_ts"
2. Launch a video library update
3. See if the new movie has been scanned

### Debuglog

Nothing at all interesting in the logs.. an excerpt of video scan : 
```
15:31:05.719 T:13343   DEBUG: CAnnouncementManager - Announcement: OnScanStarted from xbmc
15:31:05.719 T:13343   DEBUG: GOT ANNOUNCEMENT, type: 16, from xbmc, message OnScanStarted
15:31:05.776 T:13394   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender xbmc - method: VideoLibrary.OnScanStarted  - data: null
15:31:05.815 T:13389   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: VideoLibrary.OnScanStarted  - data: null
15:31:05.900 T:14044   DEBUG: CWebServer[8090]: request received for /jsonrpc
15:31:06.977 T:14369   DEBUG: VideoInfoScanner: Skipping dir 'smb://192.168.1.1/ZePool/videos/concerts/' due to no change (fasthash)
15:31:06.983 T:14369   DEBUG: VideoInfoScanner: Skipping dir 'smb://192.168.1.1/ZePool/videos/concerts/Muse Live At Rome Olympic Stadium (2013)/' due to no change (fasthash)
15:31:06.989 T:14369   DEBUG: VideoInfoScanner: Skipping dir 'smb://192.168.1.1/ZePool/videos/concerts/The Chemical Brothers Don't Think (2012)/' due to no change (fasthash)
15:31:06.994 T:14369   DEBUG: CAddonSettings[metadata.themoviedb.org]: loading setting definitions
15:31:06.994 T:14369   DEBUG: CAddonSettings[metadata.themoviedb.org]: trying to load setting definitions from old format...
15:31:06.994 T:14369   DEBUG: CAddonSettings[metadata.themoviedb.org]: loading setting values
15:31:07.220 T:14044   DEBUG: CWebServer[8090]: request received for /jsonrpc
15:31:08.366 T:14369   DEBUG: Previous line repeats 1 times.
15:31:08.366 T:14369   DEBUG: VideoInfoScanner: Skipping dir 'smb://192.168.1.1/ZePool/videos/dessins animes/' due to no change (fasthash)
```
In "concerts" folder, there are DVDs, not scanned... the ones you can see in the logs are MKVs or Bluray rips.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 8.0.0 API level 26 (kernel: Linux 4.9.109-tegra-g2dafed3)
 - Kodi version: 18.0 Git:20190128-d81c34c

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by djoole** [comment]
I've found the problem : all my sources are now set not analyse recursively. I don't know why, maybe a surprise from migration to Leia.

**Comment by djoole** [comment]
I've spoken too early :(
Even with recursive scan activated my DVDs (VIDEO_TS) folders are not scanned.
NB : no problem with Bluray structures (BDMV subfolders)

**Comment by DaVukovic** [comment]
Please post your full logs and not only some snippets. That's mandatory for those kind of reports. 

Also make sure you enabled "Movies are in folders matching the movie names" if it's about movies

Regarding the concerts, which scraper do you use? Are you sure, the specific concert in question can be found by the scraper (in meaning, does it exist on the online service you are trying to scrape from)?

Please also name the concert you are trying to scrape. 

I'll mark this as invalid for the time being because of the missing debug log. I'll remove the label after you provided the full log file.

**Comment by djoole** [comment]
"Movies are in folders matching the movie names" is indeed enabled.

As for the concerts, I don't use any scrapper, I have only a few of them, got them from a long time, and the info is locally stored on .nfo files
This not a problem of scrapping, but of scanning. In the logs you can see (well you cannot see, should I say) that these folders are not scanned.

I have this problem for every VIDEO_TS in my sources, musicvideo and movie sources.

Here is the full log : 
https://paste.ubuntu.com/p/WVC5zRvtzd/

**Comment by DaVukovic** [comment]
You have banned add-ons installed on your system. You should also stop editing your log or at least do it properly ;)

Anyway, while those add-ons are installed on your system you won't get any kind of support in here. Our issue tracker has the same rules as our forums. 

Please make sure you are using a vanilla Kodi and share a new and clean debuglog.

Thanks in advance.

**Comment by djoole** [comment]
Could you mention which addons are banned? So that I can remove them (i think i don't even use them as the only addons installed are depedencies from skins... just missing movie that I installed today).

I don't understand your saying about editing the logs... I've just cut after the library scan (the logs were way too big to post them).

**Comment by djoole** [comment]
Looking at my logs, I see that it talks about series I don't have anymore, although I've launched "library clean" several times. How come?

**Comment by djoole** [comment]
I've checked my repos and addons with the list I've found on the wiki, I've only found a banned repo, but no addon. I hope it's good this time and you can offer support.

https://paste.ubuntu.com/p/TdMF3S863T/

**Comment by djoole** [comment]
I seem to have found a solution.
The .NFOs seem to prevent Kodi 18 from scanning the folders... weird.
I've removed the metadata file and the movie has been detected on following scan.

FYI the content of the NFO : https://pastebin.com/nDM16whL

**Comment by djoole** [comment]
Mmmm not out of the wood yet.
Very, very strange behavior..
For Alice, I had to removre the NFO so that Kodi scan the folder.
For Bambi, it did not do the trick. The video_ts subfolder was in lower case... i renamed it in upper case, and after that kodi could scan it.
But video_ts of Alice is in lower case..
And for Aladdin, I've just moved the VIDEO_TS.nfo file from the video_ts subfolder to Aladdin (1992) folder... and guess what? After that Kodi was able to find Aladdin and even the 101 Dalmatians

If someone understands something.... :)

**Comment by djoole** [comment]
The common denominator seems to be altering the file system... maybe Kodi use a hash of the folders to decide wether or not to scan them?

**Comment by KarellenX** [comment]
Yes, Kodi does use a hash. When it skips a scan due to hash, you see the following in the log...
**/Asterix - Asterix chez les Bretons (1986)/' due to no change (fasthash)**

You can disable that via advancedsettings.xml... https://kodi.wiki/view/Advancedsettings.xml#videolibrary

The nfo file you posted looks fine. It looks like a Kodi generated nfo file, so there should be no problem for Kodi to re-scan it, as long as you did not move it to another location.

As for the dvd issue, I could not follow the scrape/scan for two reasons. I did not know what dvd I was looking for and 2 The log was too busy. If you could restart Kodi after you enable debug mode. Don't run an Update Library. Instead navigate to the DVD in Videos>Files and call up the Information page, which will start the scan of that one title.

Of course, tell us the name of the movie.

**Comment by djoole** [comment]
OK, so I've done what you asked for with "Aladdin". Info dialog called at 03:10:35.263.
Aladdin is one of the DVDs that are not scanned during a library update.
https://pastebin.com/FjRNtyst

**Comment by KarellenX** [comment]
I don't see any scraping or scanning. I just see activity from the helper add-ons.

What you pointed to is the helper add-ons.

Just to confirm that Aladdin is not already in the library?

**Comment by djoole** [comment]
Aladdin IS already in the library.
As I told in this [comment](https://github.com/xbmc/xbmc/issues/15473#issuecomment-462085498) I managed to add everything, but "touching" something in each folder (passing from lower case to upper case, putting the NFO in the movie name instead of the VIDEO_TS name, etc.)

But when I launch a lib update, the DVD movies folder are not scanned anymore, on the contrary of non DVD movies.
ie I never see those lines in the logs : 
**/Asterix - Asterix chez les Bretons (1986)/' due to no change (fasthash)**

And if I remove from the lib Aladdin and launch an update, it won't be scanned and added.

**Comment by Yahkob** [comment]
So as a work around I did this today by going to settings > media > library 

Do add sources and add the actual video_ts directory to your videos (can’t really remember if I did this with recursive or folder contains single video) it should add something to your video library with a name containing “video” the first time it added some movie named “dear, video” to my library and today it added some movie called “video girl”

Anyways find what new movie was added and right click it change the title to the right movie go to information and refresh - I think it asks to input the title again. Once you do that it will ask you to pick suggested names from a list and you should be good

**Comment by KarellenX** [comment]
Unable to replicate this issue in my own library.
