### ISSUE TITLE
Impossible install addon on T95K Pro

### ISSUE THREAD

**Issue by LodocArt** [xbmc/xbmc#15471]
### Describe the bug
Hello everyone ! Since Kodi updated to Leia, my addons like Quasar or Autosub were not working anymore, crashing as I started them ! I've tried to reinstall them or remove Kodi, installed Jarvis and Krypton, resetting the android box, but I just simply cannot install any addo. When I try to install Elementum it says it installed successfully, but then tries to launch it, the app crashes, then restart, crashes, before saying to me "Crashed to many times, aborting..."
My logs are filled, so I don't have any more informations :c

### Your Environment
Used Operating system:
 - [ ] Android

 - Operating system version/name:
Android Marshmallow, Kodi Leia

PS : I've just tested it with Windows, with the latest release of Kodi and Elementum and it works without any problem, must be an Android problem D:

**Comment by MartijnKaijser** [comment]
Go away with your piracy add-ons
