### ISSUE TITLE
kodi tmdb addon not scraping 50% of my movies (in french language)

### ISSUE THREAD

**Issue by nigelmerle** [xbmc/xbmc#15472]
### Describe the bug
Here is a clear and concise description of what the problem is:

kodi 18: the tmdb addon is not scraping my movies (in french language), i reinstalled kodi many times..I suspect  that with new updates of kodi some shit had happened, i did not had this problem before with the older version of kodi though and this is very annoying. kindly help us fix this issue

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Movies was susposed to scrape without issues in kodi

## Actual Behavior

I think that kodi  tmdb addon needs to be updated, it seems that the movie db is not allowing us to scrape movies to a certain extent, this is very annoying. If kodi tmdb could be customizable like elysium and covernant addons that would be nice, where each user could create his own api from tmdb website.
note : If I use the missing movie addons in kodi it will list all the movies that are missing, however with kodi 18 I have no more 'information' option in my context menu, so it means I cannot update these movies manually in  the missing movie addon :(

## Possible Fix

I think that kodi  tmdb addon needs to be updated, it seems that the movie db is not allowing us to scrape movies to a certain extent, this is very annoying. If kodi tmdb could be customizable like elysium and covernant addons that would be nice, where each user could create his own api from tmdb website.
note : If I use the missing movie addons in kodi it will list all the movies that are missing, however with kodi 18 I have no more 'information' option in my context menu, so it means I cannot update these movies manually in  the missing movie addon :(

### To Reproduce

1. open tmdb addon , go to settings and set all options to french language
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Where is your debuglog? We need those, hence we asked for it at our issue template which you obviously ignored. 

We can't do anything without that log and as long as there's none, we'll mark this issue as invalid. If you don't provide a log, this issue will be closed in 3 days.

**Comment by nigelmerle** [comment]
Hmmm ok thank you for your cooperation. We are not humans i see. Close it or do whatever you want, it was my first contact with you, very very disappointed with this kodi fucking shit !. How come people can be so aggressive nowadays when you ask for help.
I'd rather not waste my time with you, its not worth it.



Get Outlook for Android<https://aka.ms/ghei36>

________________________________
