### ISSUE TITLE
Does not play certain videos on Fire TV

### ISSUE THREAD

**Issue by ChristianKuehnel** [xbmc/xbmc#15470]
### Describe the bug
I'm using Kodi 18 on my Fire TV Stick. This usually works nicely (thx for the great work!), but I have problem playing certain videos. When I start to play those videos Kodi locks up for 2 secs and then just keeps showing the list of files. There is not video or audio. When playing the videos with VLC on my PC they work just fine.

Only videos with these 2 codecs seem to be affected so far:
* Video: MPEG-H Part2/HEVC (H.265) (hevc) H.265
* Audio: TrueHD Audio (trhd)

## Expected Behavior
Just play the video.

## Actual Behavior
Kodi seems to be loading the file and then does nothing.

## Possible Fix
Could not find any workaround for this.

### To Reproduce
1. Select a "problematic" movie from my database.
2. Hit play.

### Debuglog
The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/2846729/kodi.log)

The log contains a few videos that are playing nicely and some that are not playing at all.

### Screenshots 
Here are some links or screenshots to help explain the problem:
N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
N/A

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fire TV Stick
 - Kodi version:
```
19:09:34.229 T:9445  NOTICE: Starting Kodi (18.0 Git:20190128-d81c34c). Platform: Android ARM 32-bit
19:09:34.229 T:9445  NOTICE: Using Release Kodi x32 build
19:09:34.229 T:9445  NOTICE: Kodi compiled 2019-01-28 by Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242ddd5815e4a043907ea9004281) (https://android.googlesource.com/toolchain/llvm 1d739ffb0366421d383e04ff80ec2ee591315116) for Android ARM 32-bit API level 21 (API level 21)
19:09:34.230 T:9445  NOTICE: Running on Amazon AFTT with Android 5.1.1 API level 22, kernel: Linux ARM 32-bit version 3.10.54+
19:09:34.230 T:9445  NOTICE: FFmpeg version/source: 4.0.3-Kodi
19:09:34.230 T:9445  NOTICE: Host CPU: ARMv7 Processor rev 3 (v7l), 4 cores available
19:09:34.230 T:9445  NOTICE: Product: full_tank, Device: tank, Board: tank - Manufacturer: Amazon, Brand: Amazon, Model: AFTT, Hardware: mt8127
```

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
could you please stop editing your logfile:

`20:15:03.424 T:9445  NOTICE: VideoPlayer::OpenFile: smb://<path to video>`

And unfortunately your log isn't a debuglog. Please enable debug logging in system settings, restart Kodi (we need the log from Kodi start), reproduce your problem and then share the full and unedited log. We don't care about your internal IP adress as noone is able to use that anyway.
