### ISSUE TITLE
Invert stereoscopic 3D mode does not work anymore on Raspberry Pi

### ISSUE THREAD

**Issue by killerhaehnchen** [xbmc/xbmc#15474]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing back 3D video files with stereoscopic mode activated it is not showing any effect to switch on or off "Invert stereoscopic 3D (flip eyes)" in "Settings -> Video settings".

Different 3D video files (SBS or TAB coded into a full HD frame, like this movie trailer as a [sample 3D video file](https://thedigitaltheater.wetransfer.com/downloads/5f67d777b663a9aeba45ae5db939ffbd20190115005442/cc3bff)) have been tested resulting in the same behavior.
This behavior could be reproduced on different hardware (a Raspberry Pi 3 Model B and a Raspberry Pi 3 Model B+) while using different display devices (a Sony 3D TV KDL-50W685A or a 3D DLP beamer Acer H6510BD) .

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After switching on or off "Invert stereoscopic 3D (flip eyes)" during 3D video playback the left eye and right eye view on the 3D display device should interchange.

## Actual Behavior

After switching on or off "Invert stereoscopic 3D (flip eyes)" during 3D video playback the left eye and right eye view on the 3D display are remaining the same as before switching the above setting.

## Possible Fix

Workaround for a single 3D video file: Use a tool like MKVToolNix to edit the StereoMode flag of the .mkv file. Adapt the value of StereoMode to your needs by using the values as described [here](https://matroska.org/technical/specs/index.html#StereoMode).

Alternatively: When downgrading Kodi from version 18 to 17.6 by downgrading LibreELEC from 9.0.0 to 8.25, the setting "Invert stereoscopic 3D (flip eyes)" is working as expected on the above mentioned hardware.

### To Reproduce

1. Play back a 3D video file with stereoscopic mode activated ([sample 3D video file](https://thedigitaltheater.wetransfer.com/downloads/5f67d777b663a9aeba45ae5db939ffbd20190115005442/cc3bff)). 
2. During playback go to "Settings -> Video settings" and toggle the switch next to "Invert stereoscopic 3D (flip eyes)" (see also in [screenshot](https://snag.gy/V9T8i2.jpg)).
3. Monitor the video output on your 3D display device: Left eye and right eye view are not interchanged.
4. Toggle the switch next to "Invert stereoscopic 3D (flip eyes)" again.
5. Again watch the video output on your 3D display device to confirm that left eye and right eye view are not interchanged.

As a reference: During 3D video playback turn your 3D glasses upside down (left eye looks through the former right eye glass and vice versa) to get to know, how the inverted stereoscopic image would look like.

### Debuglog

The debuglog can be found here:
[https://paste.kodi.tv/cokaguzegi.kodi](https://paste.kodi.tv/cokaguzegi.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

[Screenshot of "Settings -> Video settings" menu during playback](https://snag.gy/V9T8i2.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

When I play back 3D video files that have left eye and right eye view interchanged by default, I use "Invert stereoscopic 3D (flip eyes)" to get the correct stereoscopic image output on my 3D display. After upgrading to LibreELEC 9.0.0/ Kodi v18.0, toggling this setting did not help anymore, since it is showing no effect.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 9.0.0
 - Kodi version: 18.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by killerhaehnchen** [comment]
Toggling the switch next to "Invert stereoscopic 3D (flip eyes)" corresponds in the debuglog to:

> 14:22:39.292 T:1937554976   DEBUG: HandleKey: return (0xf00d) pressed, action is Select
14:22:39.292 T:1937554976   DEBUG: Activating window ID: 10123
14:22:39.292 T:1937554976   DEBUG: ------ Window Init (DialogSettings.xml) ------
14:22:39.293 T:1937554976   DEBUG: CSettingsManager: requested setting (video.interlacemethod) was not found.
14:22:39.293 T:1937554976   DEBUG: CSettingsManager: requested setting (video.stream) was not found.
14:22:39.293 T:1937554976   DEBUG: CSettingsManager: requested setting (video.viewmode) was not found.
14:22:39.294 T:1937554976   DEBUG: CSettingsManager: requested setting (video.zoom) was not found.
14:22:39.294 T:1937554976   DEBUG: CSettingsManager: requested setting (video.verticalshift) was not found.
14:22:39.294 T:1937554976   DEBUG: CSettingsManager: requested setting (video.pixelratio) was not found.
14:22:39.294 T:1937554976   DEBUG: CSettingsManager: requested setting (video.orientation) was not found.
14:22:39.294 T:1937554976   DEBUG: CSettingsManager: requested setting (vdpau.sharpness) was not found.
14:22:39.294 T:1937554976   DEBUG: CSettingsManager: requested setting (video.stereoscopicmode) was not found.
14:22:39.294 T:1937554976   DEBUG: CSettingsManager: requested setting (video.stereoscopicinvert) was not found.
14:22:39.294 T:1937554976   DEBUG: CSettingsManager: requested setting (video.save) was not found.
14:22:39.295 T:1937554976   DEBUG: CSettingsManager: requested setting (video.calibration) was not found.

If I understand this correctly the issue is not only limited to the setting `video.stereoscopicinvert`, but also to the other settings in the video settings window.
I assume maybe in file `xbmc/settings/lib/SettingsManager.cpp` in function `CSettingsManager::GetSetting()` (line 537) the execution of `auto setting = FindSetting(id);` does not yield the expected result.

**Comment by popcornmix** [comment]
I've had a look and have a potential fix. Can you test tonight's [milhouse build](https://forum.kodi.tv/showthread.php?tid=298461) and confirm if problem is resolved for you?

**Comment by popcornmix** [comment]
@killerhaehnchen please test https://forum.kodi.tv/showthread.php?tid=298461&pid=2824936#pid2824936

**Comment by killerhaehnchen** [comment]
@popcornmix Good job. Works like a charm now. Thank you very much!
