### ISSUE TITLE
Kodi 18 can't load TV episode nfo files over http

### ISSUE THREAD

**Issue by sanmadjack** [xbmc/xbmc#15481]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a library set up using local nfo files only that are hosted over http. Adding a TV Show source over http results in shows being imported but no episodes being imported. Works properly over SMB. works properly over HTTP in Kodi 17.6. Based on the debug log it appears that the episode nfo files are not being read/seen.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
TV Show episodes should be imported over http.

## Actual Behavior
TV Show episodes are not imported into the library.

## Possible Fix
Change to smb protocol instead, or revert to Kodi 17.6.

### To Reproduce
1. Add video source using an https URL.
2. Set content of a subfolder to "TV Show" using local information only.
3. Scan for new content.

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/ufesetozed.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:
https://forum.kodi.tv/showthread.php?tid=340621&pid=2820560#pid2820560

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
Files are hosted on a debian linux server over nginx. nfo files are hosted as text/plain with utf8 encoding. Normally used with a mariadb database, but the issue occurs regardless of whether a database is in use.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64-bit
 - Kodi version: 18

**Comment by KarellenX** [comment]
Possibly a second report on the same issue, but using **sftp**...
https://forum.kodi.tv/showthread.php?tid=340375

There is a third similar report, but unable to locate it at this time.

**Comment by DaVukovic** [comment]
Just out of curiousity:

`10:01:24.050 T:17160   ERROR: VideoInfoScanner: Asked to lookup episode https://kodi.darkholme.net/kids/Series/Azumanga%20Daioh/Season%2000/Azumanga%20Daioh%20-%20S00E01%20-%20Azumanga%20Daioh%20-%20The%20Very%20Short%20Movie.mkv online, but we have no episode guide. Check your tvshow.nfo and make sure the <episodeguide> tag is in place.`

**Check your tvshow.nfo and make sure the <episodeguide> tag is in place**

Did you check your tvshow.nfo?

**Comment by KarellenX** [comment]
An <episodeguide> is **not** required if all episode nfo files are available, which they are in this case.

**Comment by sanmadjack** [comment]
> Just out of curiousity:
> 
> `10:01:24.050 T:17160 ERROR: VideoInfoScanner: Asked to lookup episode https://kodi.darkholme.net/kids/Series/Azumanga%20Daioh/Season%2000/Azumanga%20Daioh%20-%20S00E01%20-%20Azumanga%20Daioh%20-%20The%20Very%20Short%20Movie.mkv online, but we have no episode guide. Check your tvshow.nfo and make sure the <episodeguide> tag is in place.`
> 
> **Check your tvshow.nfo and make sure the <episodeguide> tag is in place**
> 
> Did you check your tvshow.nfo?

Yes, I did. Shows both with and without that field would not load, same error message.

**Comment by stefano70** [comment]
Same problem here.
Since i moved to Kodi 18 from 17.6, I am experiencing new problems.
While trying to find out why my setup of Kodi 18 Leia does not show posters but thumbnails using local .nfo, I changed the protocol, from SAMBA to HTTP.
I have an HPE Proliant server running SAMBA on Ubuntu and hosting all my movies.
I loaded lighttpd ad exported my movies in HTTP (and SAMBA, as well).
Everything working well with SAMBA, but not with HTTP

Here is the debug log
[https://paste.kodi.tv/uloquruwiw.kodi](url)

Kodi 18 clean and fresh setup
addedd the HPPT source
added Twin Peaks 3 series
... nothing to display, nothing imported
removed the source, cleaned the database
added the SAM source
added Twin paks again
OK!

**Comment by arnova** [comment]
I just reproduced the issue here with https://, so I can confirm the issue. I'll look into it.

**Comment by arnova** [comment]
Something broke in our Curl filesystem, but it's totally unclear what:
20:06:45.525 T:140704758286720   DEBUG: Curl::Debug - HEADER_OUT: GET /video/series/Oz/tvshow.nfo HTTP/1.1
....
20:06:45.525 T:140704758286720   DEBUG: Curl::Debug - HEADER_OUT: Range: bytes=0-
20:06:45.525 T:140704758286720   DEBUG: Curl::Debug - HEADER_OUT: User-Agent: Kodi/18.1-RC1 (X11; Linux x86_64) Linux Mint/18.3 App_Bitness/64 Version/18.1-RC1-Git:20190129-6cce837
20:06:45.525 T:140704758286720   DEBUG: Curl::Debug - HEADER_OUT: Accept: */*
20:06:45.525 T:140704758286720   DEBUG: Curl::Debug - HEADER_OUT: Accept-Charset: UTF-8,*;q=0.8
20:06:45.584 T:140704079152896   DEBUG: Curl::Debug - TEXT: The requested URL returned error: 404 Not Found

**Comment by arnova** [comment]
Ignore my previous comment.. I found the real issue, which was introduced with https://github.com/xbmc/xbmc/commit/217b723c5dd41a98e82c1c3786601d0814e37b94#diff-d8f9f1e35e27970247154bb5d27c27cf . Basically the IsinternetStream() check on line 26 needs to go...

**Comment by arnova** [comment]
PR15492 should take care of this.

**Comment by KarellenX** [comment]
Thanks for the quick fix. 

Will that also solve the sftp issue reported in the second post above?

**Comment by arnova** [comment]
> Thanks for the quick fix.
> 
> Will that also solve the sftp issue reported in the second post above or is that a different issue?

Although I haven't looked into that yet, I'm pretty sure the sftp issue is unrelated. Will do as soon as I can find the time.

**Comment by uotw** [comment]
I can confirm that after installing the latest Android nightly build that the sftp issue persists.

**Comment by sanmadjack** [comment]
To be fair, the latest nightlies don't have the fix for this issue either. Since 18.1 is already in release candidate, are we going to have to wait for 18.2 for this?

**Comment by sanmadjack** [comment]
The fix got added to 18.1-final, so I guess it'll make it to that. Cool.

**Comment by sanmadjack** [comment]
Confirmed working with the latest nightly.

**Comment by uotw** [comment]
Confirmed to still be an issue with sftp with the latest nightly.  Should I create a new issue?

**Comment by KarellenX** [comment]
Yes, create a new issue. This one is closed and it may be forgotten about.
