### ISSUE TITLE
kodi crashes when asked to play second video

### ISSUE THREAD

**Issue by prometheanfire** [xbmc/xbmc#15487]
### Describe the bug
Here is a clear and concise description of what the problem is:
I'm running 18.0 (libreelec)
whenever I play a video via the api (request to play a youtube video via 'play to kodi' in Firefox) while another video is already playing I get a crash.  Kodi then relaunches (think systemd restarts it).

## Expected Behavior
No crashes.

## Actual Behavior
Crash - 22:28:22.545 T:139750329122112   ERROR: Control 55 in window 10025 has been asked to focus, but it can't.

## Possible Fix
I think hardware acceleration can only handle decode of one video at a time on this hardware and the previous hardware use is not fully stopped.  Had a similar problem recording world cup games and not being able to encode them as well (though it could have been problems with how I called ffmpeg).

### To Reproduce
1. Run kodi (possibly on an Atom E3930
2. play video
3. request second video to be played
4. watch crash

### Debuglog
The debuglog can be found here: https://pasted.tech/pastes/b9528bc4a2f43fe177e99cdc4648ad07bb6d0f09

### Screenshots 
Here are some links or screenshots to help explain the problem: N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help: N/A

### Your Environment
Used Operating system:
 - [x] Linux
 - Kodi version: 18.0 (libreelec 9.0.0)
 - Intel(R) Atom(TM) Processor E3930 @ 1.30GHz

**Comment by DaVukovic** [comment]
Could you please provide the full log from Kodi start and unfortunately you missed to enabled debug logging. 

To get the log:

- enable debug logging
- restart kodi
- reproduce your issue as fast as you can
- paste the log
- share the URL

**Comment by prometheanfire** [comment]
had to cycle through a few video attempts, but it triggered eventually.  This is kodi.old.log (compressed), seemed like the right one as it was largest and had the right modification time.

https://mthode.org/kodi.old.log.xz
