### ISSUE TITLE
[REQUEST] Enhancements to skinning

### ISSUE THREAD

**Issue by bkury** [xbmc/xbmc#15498]
## Roadmap or todo suggestion

DialogNotification.xml
----------------------
Please add a way to get notification information (ID 400,401,402) via skinning engine, making something like this work would be sufficient:
```
<onload>Skin.SetString(notification1,$INFO[Control.GetLabel(401)])</onload>
<onload>Skin.SetString(notification2,$INFO[Control.GetLabel(402)])</onload>
```
(if that isn't possible, maybe set a window property?)

Unfortunately, "onload" method does not work with modeless dialogs like DialogNotification.xml

New boolean condition
---------------------
```
File.Exist(/test)
!File.Exist(/test/theme.mp3)
```
(path has to be translated on windows /test --> C:\test)

Returns true if a specific file or directory exist

Container (Content)
-------------------
Ability to fill a container with static items from an URL e.g.:
```
<control type="list">
        ...
        <content>http://kodi.tv/items.xml</content>
                        OR
        <content><include>http://kodi.tv/items.xml</include></content>
</control>

items.xml:
-----------
<item>
        <label>test</label>
        ...
</item>
```

### Context
**DialogNotification.xml:**
This change would allow skin developers to create a "Notification Center", Home automation triggers on certain notifications (e.g. Incoming Call --> Pause Video --> Turn on Light) and more ...
(most useful with apps like yatse, ..)

**Boolean Condition:**
Check if a file/dir exist before calling "PlayMedia()", this is especially useful for playing "theme" files while browsing your library, can also be useful to check user input "e.g. The directory/file you entered does not exist!"

**Container (Content):**
Useful for containers which static items change frequently. Normally you have to update the skin .xml file to add/remove or change a static item, with this method you could just edit the .xml on the server side and users will automatically get the new content.

Thanks for considering these changes!
---

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by DaVukovic** [comment]
Feature requests need to be done at forums at the specific subsection. Please open a thread and post it there. This section is for bugs at Kodi core. A missing feature is most likely not a bug ;)
