### ISSUE TITLE
"Flatten hierarchy" doesn't work if "Category widgets" are disabled

### ISSUE THREAD

**Issue by The-Choo-Choo-Shoe** [xbmc/xbmc#15493]
### Describe the bug
Here is a clear and concise description of what the problem is:

When you disable "Category widgets" in Estuary skin "Flatten hierarchy" is disabled so when you go into a menu item like "Movies" from the main menu you still need to browse by actor, sets etc before getting to the title menu instead of going straight there.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

With "Flatten hierarchy" enabled it should still work even with "Category widgets" disabled.

## Actual Behavior

"Flatten hierarchy" is only working when "Category widgets" is also enabled.

### To Reproduce

1. Disable "Category widgets"
2. Enable "Flatten hierarchy"
3. Go back to the main menu and click on Movies or TV shows and it goes to the nodes menu.

### Debuglog

The debuglog can be found here: [kodi.log](https://github.com/xbmc/xbmc/files/2853345/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 8.0.0
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by The-Choo-Choo-Shoe** [comment]
New issue of this: https://github.com/xbmc/xbmc/issues/15370

**Comment by The-Choo-Choo-Shoe** [comment]
Not fixed in 18.2

**Comment by luke255** [comment]
Still seeing this in 18.3

**Comment by mtcdood** [comment]
Still unresolved in 18.5.

Bet this regression won't even get a reply before Kodi starts shipping an entirely new default skin.

**Comment by niawag** [comment]
Facing the same problem in 18.8 (Coreelec 9.2.4.2)

**Comment by imathew** [comment]
Seeing this on 18.8, Android TV.

(Thanks to the reporter, made me realise I could enable category widgets as a begrudging workaround)

**Comment by jbrown1597** [comment]
Still an issue. 3/21/2021. Please. Somebody.

**Comment by Yega2k** [comment]
Just got Kodi 19 installed. Still an issue in 2022!

**Comment by Fire69** [comment]
19.4, still here.  Took me quite some time to figure out...
