### ISSUE TITLE
trakt

### ISSUE THREAD

**Issue by ib1ub12** [xbmc/xbmc#15501]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I initially go to a trakt tv list all is correct until I click on a show and then return to list. When i return to the list all are shows previously marked as watched have lost their tick mark indicating they have been watched. I have to then completely back out of the add on and go back in to have the tick marks showing again 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Usually when u click on a show and finish watching it u get a ratings box (which i still do) then u back out and the show u just watched now has a tick mark along with all other eps and shows u previously watched. All tick marks are now gone in k@di 18

## Actual Behavior

When I initially go to a trakt tv list all is correct until I click on a show and then return to list. When i return to the list all are shows previously marked as watched have lost their tick mark indicating they have been watched. I have to then completely back out of the add on and go back in to have the tick marks showing again 

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 
 - Kodi version: K@di 18 using an minix android box

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You missed to provide a debuglog

Please share that as it might be important.

**Comment by ib1ub12** [comment]
un how do i get the debuglog?


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by ib1ub12** [comment]
sorry...how to i get the debug log?

**Comment by DaVukovic** [comment]
Please take a look at 

https://kodi.wiki/view/Log_file

**Comment by ib1ub12** [comment]
https://paste.kodi.tv/ulabigawow

**Comment by DaVukovic** [comment]
You have banned add-ons and repositoriew installed on your system. 

Please remove those first, reproduce your issue and then provide a new log

I'll mark this issue as invalid for the time being. This label will be removed after a new and clean log is submitted.

**Comment by ib1ub12** [comment]
what banned add ons and repos??

**Comment by Rechi** [comment]
read https://kodi.wiki/view/Banned_addons

**Comment by ib1ub12** [comment]
lol ok so everything good. hahhaha ok guess i wont be getting any help here. i understand
