### ISSUE TITLE
Kodi leia v18 - SMBv1 legacy not working with legacy Apple Time Capsule SMBv1

### ISSUE THREAD

**Issue by pininy** [xbmc/xbmc#15500]
legacy SMBv1 Client not working for Kodi v18.x, no problems with v17, 

TO:Submit_a_bug_report  -->
### Describe the bug
Problem when the network share keeps time out on Kodi v18 on Android TV box, installed Network browser doing SMBv1 no issues - it was pretty fast on Android itself.

## Expected Behavior
When adding new movies into the network folder, Kodi took a long time to update, and it should be quite fast since Kodi v17.

## Actual Behavior
Time Out or just ended by itself

## Possible Fix
 it should be a SMBv1 support have been removed from Kodi v18, i have tried setting the maximum to SMBv1 and using legacy security - forced for legacy NAS, it didn't work.

### To Reproduce
Easy, just put a legacy SMB it will time out by itself - always

logging uploaded.
https://paste.kodi.tv/execekigad

### Your Environment
Used Operating system:

 - [X] Android TV 7.1.2
 
 - Operating system version/name:
 - Kodi version: v18

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You have banned add-ons and repositories install on your system. Please remove them and retry with a vanilla Kodi. 

I'll mark this as invalid until we see a clean logfile. 

Thanks in advance.

**Comment by pininy** [comment]
Yes sir! reinstalling a fresh kodi.

**Comment by chewitt** [comment]
Closing due to #15502 being opened.
