### ISSUE TITLE
DVD player freezes when the audio format of the DVD menu is different from the one used in the movie

### ISSUE THREAD

**Issue by Mochilote** [xbmc/xbmc#15504]
### Describe the bug
The problem occurs with several DVDs that I have tried. If we play the DVD and use the DVD menus (not the Kodi player menu) to select an audio track other than the default one, when we then play the DVD (from the beginning or selecting a chapter) the playback begins without sound and after 10 seconds the image freezes. Kodi is not completely hung up as we can stop the player and go back to the Kodi menus.

UPDATE: Finally, it also affects the reproduction of files (and surely the blu-ray with menu), see the third comment https://github.com/xbmc/xbmc/issues/15504#issuecomment-463306943

## Expected Behavior
That works without problems. Those same DVDs work perfectly in VLC or even Kodi 18.1 RC on Windows.

## Actual Behavior

The playback begins without sound and after 10 seconds the image freezes

### To Reproduce

1. We play a DVD that has more than one audio track.
2. We use the on-screen menu of the DVD itself to select an audio track other than the one by default.
3. We use the on-screen menu of the DVD itself to start playing (from the beginning or a specific chapter).

### Debuglog

I have done the debug logs with a DVD that has two audio tracks, one PCM 2.0 (by default) and another DTS. (But also it has happened to me with other DVDs with three tracks (DD 2.0, DD5.1 and PCM 2.0) for example).

Log1 (DTS track is selected, it is played from the beginning, there is no sound and after 10 seconds (more or less) the image freezes): https://paste.kodi.tv/hejenasulo

Log2 (DTS track is selected, chapter 9 is selected, there is no sound and after 10 seconds (more or less) the image freezes): https://paste.kodi.tv/osuyivaxaz

Log3 (Audio track is not selected (by default it uses pcm 2.0), we select chapter 9, then we show the menu again we select chapter 16, it works perfectly, both audio and video): https://paste.kodi.tv/bagonahepo

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: NVIDIA SHIELD Android TV with Android 8.0.0 API level 26 (SHIELD Experience 7.2.2)
 - Kodi version: 18.1-RC1 Git:20190211-379f5f9 (Also on Kodi 18.1 official)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Mochilote** [comment]
I had already commented on this problem days ago in the forum: https://forum.kodi.tv/showthread.php?tid=339983&pid=2820782#pid2820782

**Comment by Mochilote** [comment]
I just verified that the problem is not present in Kodi 18.1 RC on Windows using the same DVD to test.

**Comment by Mochilote** [comment]
The problem is not only with the reproduction of DVDs, I just discovered that if I play a file with AC3 and without stopping playback I try to play a file with DTS the problem repeats itself (there is no sound and after several seconds the image freezes) and the same if first it is DTS and then AC3. Of course if I stop the files before playing the next one, it works perfectly. So I suppose it is a 'general' problem in Android that affects any change in audio format if during one playback we jump to another, that's why the DVD menus of the logs were in PCM and it worked if you left the video in PCM. I suppose that this bug also affects the playback of blu-ray with menu if the audio format change equally between the menu and playback.

**Comment by iz8mbw** [comment]
Hi @fritsch
I think you can close this issue. Thank you.

**Comment by Mochilote** [comment]
Issue solved with https://github.com/xbmc/xbmc/pull/15631

Many thanks @fritsch
