### ISSUE TITLE
FTPS (TLS) does not work after upgrading from 17.6 to 18

### ISSUE THREAD

**Issue by bleze** [xbmc/xbmc#15513]
### Describe the bug
Here is a clear and concise description of what the problem is:
FTPS has been working fine prior to upgrade to Kodi 18. I first noticed issue on Shield which was auto updated. Then today I tried testing this on Windows and got the following errors in log. Connection works fine in FTP clients like FileZilla.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
That Kodi could still connect with FTPS and list files.

## Actual Behavior
No thing happens when trying to connect in Kodi.

### To Reproduce
1. Source is in this format; `ftps://<user>:<pass>@<ip>:<port>/<path>|auth=TLS`
2. Server is a Synology NAS with FTPS (SSL/TLS) and the default range of passive ports.

### Debuglog
I get the following error in log file;
`
10:41:46.755 T:4100   ERROR: CCurlFile::FillBuffer - Failed: SSL connect error(35)
10:41:46.755 T:4100   ERROR: CCurlFile::Open failed with code 0 for ftps://USERNAME:PASSWORD@192.168.1.10:21/:
10:41:46.755 T:4100   ERROR: XFILE::CDirectory::GetDirectory - Error getting ftps://USERNAME:PASSWORD@192.168.1.10:21/|auth=TLS
`

### Your Environment
Used Operating system:
 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Windows 10, x64. nVidia Shield with Android-TV 8
 - Kodi version:
18.0

**Comment by DaVukovic** [comment]
Please get us the full debuglog

Thanks

**Comment by wsnipex** [comment]
very likely a Certificate verification issue. Self signed cert?

**Comment by bleze** [comment]
There really isn't anything else interesting in the log, but here goes;
[kodi.log](https://github.com/xbmc/xbmc/files/2872051/kodi.log)

**Comment by bleze** [comment]
Well, it's a certificate that the NAS OS has created valid until 2038. Common name does not match server name my FTP client tells me.
This was not a problem in 17.6 but is in 18.
It's fine that software warns you and you choose to accept continuing using the unsafe certificate.

**Comment by vpeter4** [comment]
You can try with `|auth=TLS&verifypeer=false` but obviously this is not good from security perspective.

**Comment by bleze** [comment]
Thanks for the suggestion, but it does not help. Still getting error 35.

I have tried Let's encrypt certificate but could not get that to work at all. Also it seems to expire after 90 days.

**Comment by vpeter4** [comment]
Enable Kodi debug log to see more messages.

**Comment by bleze** [comment]
Seems it is looking for a file which does not exist, but error 35 indicates a certificate issue at connect. I guess Kodi does not write a readout of the error buffer to log. Might be interesting to see what Curl thinks is wrong

`19:59:58.884 T:15128    INFO: XCURL::DllLibCurlGlobal::easy_acquire - Created session to ftps://192.168.1.10
19:59:58.896 T:15128   ERROR: CCurlFile::Exists - Failed: SSL connect error(35) for ftps://USERNAME:PASSWORD@192.168.1.10:21/folder.jpg|auth=TLS&verifypeer=false
20:00:01.278 T:15128   ERROR: XFILE::CDirectory::GetDirectory - Error getting`

'CURLE_SSL_CONNECT_ERROR (35)
A problem occurred somewhere in the SSL/TLS handshake. You really want the error buffer and read the message there as it pinpoints the problem slightly more. Could be certificates (file formats, paths, permissions), passwords, and others.'

**Comment by vpeter4** [comment]
Post debug kodi log where SSL/TLS handshake is visible.
Btw: around 1 month back I was checking ftps on LibreELEC and was working fine.

**Comment by bleze** [comment]
I don't see any handshake. [kodi.log](https://github.com/xbmc/xbmc/files/2872299/kodi.log)

Yes FTPS worked fine for me before 18.0. I did nothing to setup on neither server nor client side. Something in Kodi is different since 17.6.

**Comment by wsnipex** [comment]
use the hostname from the cert to connect, not the IP

**Comment by bleze** [comment]
I did try to use the hostname from the Let's encrypt it cert which I created with hostname 'hostname.com' while connecting with 'ftp.hostname.com'. That did not work at all. Perhaps the cert needs to be using ftp.hostname.com? But I find this strange since it is a multipurpose cert also used for https.

**Comment by vpeter4** [comment]
Do you have component logging enabled with debug? Then select curl there or disable it completely.

**Comment by bleze** [comment]
Peter, that was a new feature to me. Thanks. That seems to show the error that occurs; error:1408F10B:SSL routines:ssl3_get_record:wrong version number

[kodi.log](https://github.com/xbmc/xbmc/files/2872318/kodi.log)

**Comment by vpeter4** [comment]
There is no SSL handshake meaning you are connection to plain ftp server? Don't use ftps then with auth: just ftp?

**Comment by bleze** [comment]
That's not true. FTP is only configured for FTPS and when connecting with FlashFXP or Filezilla, I get the accept certificate dialog.

**Comment by vpeter4** [comment]
With same address (ftps://USERNAME:PASSWORD@192.168.1.10:21/)? Maybe you need different port?

**Comment by bleze** [comment]
Yes, I can connect both from outside via public IP or hostname, and locally using lan ip of server. Only place I cannot connect is in Kodi 18

**Comment by bleze** [comment]
Server setup;

![ftps](https://user-images.githubusercontent.com/1309917/52904426-7e465880-322c-11e9-9280-3b9dd177208a.png)

**Comment by vpeter4** [comment]
Then I'm out of ideas.
Log shows `Curl::Debug - SSL_DATA_IN: 220 D` and 220 is FTP response code with message. Like `220 mynas FTP server ready.`
Meaning there is FTP server on the other side.
Try to disable server on Synology, press apply, and then enable it again.

**Comment by bleze** [comment]
Reenabling FTP server settings does not help with Kodi.

**Comment by bleze** [comment]
Comparing with FlashFXP's log, the 220 response seems normal. Afterwards it continues to setup TLS before finally logging in successfully.

`[21:01:46] [R] Connecting to 192.168.1.10 -> IP=192.168.1.10 PORT=21
[21:01:46] [R] Connected to 192.168.1.10
[21:01:46] [R] 220 DS FTP server ready.
[21:01:46] [R] AUTH TLS
[21:01:46] [R] 234 AUTH TLS command successful.
[21:01:46] [R] TLSv1.2 negotiation successful...
[21:01:46] [R] TLSv1.2 encrypted session using cipher ECDHE-RSA-AES256-GCM-SHA384 (256 bits)
[21:01:48] [R] PBSZ 0
[21:01:48] [R] 200 PBSZ command successful (PBSZ=0).`

**Comment by vpeter4** [comment]
Ok, got access to one Synology and I think I got it working.
Instead of ftps:// use ftp:// and leave auth at the end. Does it work now? Maybe you will also need to add verifypeer.

**Comment by bleze** [comment]
Yep, that works but only when verifypeer is false. Thanks for the help :)

As a side note, I really think Kodi can be improved in this area;

1. Adding a FTP source should have more options in the GUI, voiding the need for editing XML files and putting in wrong settings there. Less error prone.
2. Connection pooling. Having only one FTP connection is not a good experience. While updating library you cannot do anything but what. NFS or SMB does not have this one connection limitation.

**Comment by vpeter4** [comment]
Yes, verifypeer is needed. You could use Let's encrypt certificate or add cert to your Kodi to avoid that.

Now who would by me one Synology to test such issues more easily :)

**Comment by bleze** [comment]
If you add the connection pool to the source, I'll get you one ;)

I once added a FTP connection pool to my code at work and it made delivery of data 1000x faster. Before it was connecting, uploading a file, disconnecting, and then connected again for next file for same server.  Sadly I do not have time to work on Kodi source any more.

**Comment by bleze** [comment]
Do you really think man-in-middle attacks are that common? Let's encrypt expires after 90 days which is crazy. Not sure if Synology will auto renew it - if not it will not be an option to work on more.

**Comment by bleze** [comment]
I created a Let's Encrypt cert again and have it working for http and ftps from the outside, however connecting from the inside I cannot use the domain probably due to some setting in my router?
I can connect with local IP however I get this error;

`21:47:27.499 T:1828   DEBUG: Curl::Debug - TEXT: Server certificate:
21:47:27.499 T:1828   DEBUG: Curl::Debug - TEXT:  subject: CN=blahblah.com
21:47:27.499 T:1828   DEBUG: Curl::Debug - TEXT:  start date: Feb 16 19:44:44 2019 GMT
21:47:27.499 T:1828   DEBUG: Curl::Debug - TEXT:  expire date: May 17 19:44:44 2019 GMT
21:47:27.499 T:1828   DEBUG: Curl::Debug - TEXT:  subjectAltName does not match 192.168.1.10
21:47:27.499 T:1828   DEBUG: Curl::Debug - TEXT: SSL: no alternative certificate subject name matches target host name '192.168.1.10'
21:47:27.499 T:1828   DEBUG: Curl::Debug - TEXT: Closing connection 1`

Is it possible to ignore this error? verifypeer is false.

**Comment by pkerling** [comment]
No. verifyhost is always enabled, so the host you connect to has to match the certificate. Please fix your setup. If you have any further need for discussion, please head to the forums for support as there is no code issue with Kodi here.

**Comment by blunden** [comment]
It's worth pointing out that most FTP servers generate self-signed certificates, most FTP clients don't treat a certificate from an unknown CA as an error in the way browsers do (with good reason), just popping up a certificate trust dialog instead. It's actually quite uncommon even for corporate FTP servers to use certificates issued by well known CAs, even less so for home users. At this point, it's unlikely to ever change for this particular protocol so "silently" failing (as in no UI error message apart from the log) on verification of the peer certificate chain probably isn't a particularly great user experience. :)

**Comment by pkerling** [comment]
@blunden We welcome PRs that improve the user experience :)

**Comment by blunden** [comment]
@pkerling I took a quick look and it seems like the dialog for configuring the FTP source was shared with a few other protocols as well that I didn't want to mess with. :)

**Comment by mslake** [comment]
Why has this bug been closed but not actually fixed?  As is, SSH connections are unusable in 18.4 but work perfectly in 17.6 and prior releases.

**Comment by fritsch** [comment]
See: https://github.com/xbmc/xbmc/issues/15513#issuecomment-464398665

For your ssh issue (works for me, just tested with kodi vfs sftp) open another ticket if you care. Providing all the logs, etc.

**Comment by arnova** [comment]
> See: [#15513 (comment)](https://github.com/xbmc/xbmc/issues/15513#issuecomment-464398665)
> 
> For your ssh issue (works for me, just tested with kodi vfs sftp) open another ticket if you care. Providing all the logs, etc.

It's correct that ssh is broken in Kodi 18 and that won't be resolved until v19 is released. But ssh is beyond the scope of this PR which is about FTP with SSL/TLS

**Comment by fritsch** [comment]
What do you mean with broken? I tested it 60 minutes ago, installed the sftp add-on, enabled it and connected to my remote ssh server.

**Comment by arnova** [comment]
> What do you mean with broken? I tested it 60 minutes ago, installed the sftp add-on, enabled it and connected to my remote ssh server.

Eg. video scanning is broken due to missing date/time support.

**Comment by fritsch** [comment]
Initial scanning works fine. So delta scanning, okay that I did not test.

**Comment by arnova** [comment]
> Initial scanning works fine. So delta scanning, okay that I did not test.

Right, see: https://github.com/xbmc/vfs.sftp/commit/053a71eadd590505f2f0b94aaa7130bd6f9cd5cc & https://github.com/xbmc/xbmc/pull/16431

**Comment by fritsch** [comment]
As a workaround, users can disable fasthash via advancedsettings.xml - not a nice solution, but better than v18 being broken.

**Comment by fritsch** [comment]
Alternatively after having checked the fix and having checked GetFastHash, perhaps adding ->mtime64 to fasthash's function will work without changing the addon?

**Comment by arnova** [comment]
> Alternatively after having checked the fix and having checked GetFastHash, perhaps adding ->mtime64 to fasthash's function will work without changing the addon?

Nope, it does not since you also need the changes in https://github.com/xbmc/xbmc/pull/16431/files which were never backported to Leia.
