### ISSUE TITLE
Movie thumbnail/poster URLs not read/displayed from NFO files in v18+

### ISSUE THREAD

**Issue by tmtisfree** [xbmc/xbmc#15514]
### Describe the bug
Since v18, thumbnail poster URLs given as file names only are not read anymore from NFO files unless the aspect="poster" property is set in "thumb" tags.

In my case, all movies, posters and NFO files are in the same directory, with this tree structure:
```
moviefilename1.jpg
moviefilename1.m2ts
moviefilename1.nfo
moviefilename2.jpg
moviefilename2.m2ts
moviefilename2.nfo
etc.

```
The structure of my empty (not working) NFO file is as follows:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<movie>
  <title>title</title>
  <thumb>title.jpg</thumb>

  <year></year>
  <runtime></runtime><!-- Runtime in minutes -->
  <genre></genre>
  <plot>

  </plot><!-- Can contain more information on multiple lines, will be wrapped. -->

  <playcount>1</playcount><!-- Setting this to > 0 will mark the movie as watched if the "importwatchedstate" flag is set in advancedsettings.xml -->

  <originaltitle></originaltitle>
  <sorttitle></sorttitle>
  <set></set>
  <rating></rating>
  <top250></top250>
  <votes></votes>
  <outline></outline><!-- Should be short, will be displayed on a single line. -->
  <tagline></tagline><!-- Should be very short, will be displayed on a single line. -->
  <mpaa></mpaa>
  <id></id>
  <filenameandpath></filenameandpath>
  <trailer></trailer><!-- plugin://plugin.video.youtube/?action=play_video&videoid=PUT HERE THE VIDEO ID FROM YOUTUBE -->
  <fileinfo>
      <streamdetails>
      </streamdetails><!-- While it is possible to manually set the information contained within the "streamdetails" tag, there is little point in doing so, as the software will always overwrite this data when it plays back the video file. In other words, no matter how many times you try to manually set it, it will be undone the moment the video is played.-->
  </fileinfo>
  <studio></studio>
  <director></director>
  <credits></credits><!-- Library exports uses this field for writers.-->
  <actor>
    <name></name>
    <role></role>
  </actor>
  <actor>
    <name></name>
    <role></role>
  </actor>
  <actor>
    <name></name>
    <role></role>
  </actor>
  <actor>
    <name></name>
    <role></role>
  </actor>
</movie>
<!--
[COLOR tan]Avertissement : des scènes, des propos ou des images peuvent heurter la sensibilité des spectateurs[/COLOR]
[COLOR darkred]Interdit aux moins de 16 ans[/COLOR]
[COLOR red]Interdit aux moins de 12 ans[/COLOR]
[COLOR mediumturquoise]À partir de 10 ans[/COLOR]
[COLOR limegreen]À partir de 6 ans[/COLOR]
[COLOR greenyellow]À partir de 3 ans[/COLOR]
-->
```

## Expected Behavior

Thumbnail poster URL should be read and displayed (as on v17.6) if the "thumb" tag is provided in the NFO file.

## Actual Behavior

Thumbnails are not read/displayed from NFO files.

## Possible Fix

Remove enforcing the aspect="poster" property in "thumb" tags.

### To Reproduce

1. Update from v17.6 to, or install v18+
2. Update a video library (NFO files without the aspect="poster" property in "thumb" tags)
3. Browse the library: posters are not displayed
4. Display movie info: poster is not shown in the window
5. Add the aspect="poster" property in the "thumb" tag of a NFO file
6. Update the library once more
7. Poster is now displayed both in the library and the movie info window

### Debuglog

Attached: 
[kodi.log](https://github.com/xbmc/xbmc/files/2865721/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows7 x64
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: tested with 18 and 18.1 (RC1) x32

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
First, your log isn't a debuglog. Please enable debug logging, restart Kodi, reproduce your issue and then grab the log.

But...you have banned add-ons/repositories installled. So you need to remove them first before grabbing a new log. You won't get support in here while those are installed.

I'll mark this as invalid for the time being.

**Comment by tmtisfree** [comment]
I have uploaded the debug file and removed the offending repository.

Note that I merely point to a possible bug, I don't request or need "support".
