### ISSUE TITLE
Cache remote filesystem directory content

### ISSUE THREAD

**Issue by anatol** [xbmc/xbmc#15517]
Some kodi systems work in environments with high-latency networks. In such case working with remote filesystems, like SAMBA shares is quite painful. Even initial directory list step might take a lot of time.

One thing that can help here is to cache content of SAMBA directory (list of filenames). And when a user starts kodi the content is served quickly from this case. Meanwhile Kodi should start updating the cache asynchronously. And if dir content has changed - then update UI as well, to reflect those changes.

Having remote filesystem dir caching will help to make Kodi UI much more usable in case of high-latency networks.

**Comment by MartijnKaijser** [comment]
Feature request should be made on the forum
