### ISSUE TITLE
Play Next Video Automatically not working for ISO movies in Kodi 18 Leia

### ISSUE THREAD

**Issue by Sword0fTheSpirit** [xbmc/xbmc#15519]
### Describe the bug
Here is a clear and concise description of what the problem is: 

In Kodi 18 Leia, the 'play next video automatically' feature is not working for DVD & Bluray ISO's in my movie collection.

When I have 'play next video automatically' selected for 'movies', not only does it not play the next video automatically for both DVD ISO's and Bluray ISO's when they end but additionally the Bluray ISO's will not play when I left click them. I have to right click on Bluray ISO's and select play from the menu in order for them to play (only when 'play next video automatically' is selected for movies). 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When I have 'play next video automatically' selected, I would love it if Kodi would play the next video automatically as it used to a long time ago, & without opening up additional menus like the movie list that I have to take action to close so I can see the next movie 'fully'.

## Actual Behavior

Play next video automatically has not worked properly on Kodi for several editions now. It started with an error message that said 'playback has failed' back in Kodi 15, but the next video would still play anyways, it would just load up the movie list over the playing movie and I would have to close it, which is annoying. For Kodi 16 and 17, using the play 'play next video automatically' feature would also make it so it did not remember your place in the movie list so each time you exited a movie it would return to the top of the list, also very annoying. I was eagerly anticipating that Kodi 18 would fix this bug and it would finally work properly again, but it has gotten worse. Now the feature does not work at all.

## Possible Fix

Please, please, please somebody who knows what they are doing fix this problem, because I am simply not educated in computer coding to even attempt to fix this myself and that feature is super super important to me. I want my movies to just keep playing one after the other with the random feature selected and I am unable to do that anymore.

### To Reproduce

1. Select 'play next video automatically' for the movies option.
2. Go to movies and try to left click a DVD or Bluray ISO (which you may have to use the menu instead)
3. Go to the end of the movie and wait for when it should play the next movie and nothing happens and it just returns to the movie list.

### Debuglog

The debuglog can be found here:

https://pastebin.com/embed_js/mxA53SLV

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 7 Ultimate
 - Kodi version: Kodi 18 Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You have banned add-ons and repositories installen. Please remove them first, then try to reproduce your problem and grab a new and clean logfile

I´ll mark this as invalid for the time being. The label will be removed if you submit a new log.

**Comment by Sword0fTheSpirit** [comment]
How do I know what is banned and what to remove?
Sent from Yahoo Mail on Android 
 
  On Fri, Feb 15, 2019 at 12:45 AM, DaVukovic<notifications@github.com> wrote:   
You have banned add-ons and repositories installen. Please remove them first, then try to reproduce your problem and grab a new and clean logfile

I´ll mark this as invalid for the time being. The label will be removed if you submit a new log.

**Comment by DaVukovic** [comment]
https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons

For what I can tell so far, every repository (beside the xbmc repository) is banned and therefore also any add-which comes from those repos. So I would recommend to rename your `%appdata%\Kodi` folder to something else, restart Kodi, enable debugging try reproducing your issue (which shouldn´t require any additional add-on) and then provide a new logfile.

**Comment by Sword0fTheSpirit** [comment]
Thank you for your help, sir. I believe I have done what you asked and changed the log file. I hope there is a solution to my issue. 
    On Friday, February 15, 2019, 4:22:35 AM CST, DaVukovic <notifications@github.com> wrote:  
 
 
https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons

For what I can tell so far, every repository (beside the xbmc repository) is banned and therefore also any add-which comes from those repos. So I would recommend to rename your %appdata%\Kodi folder to something else, restart Kodi, enable debugging try reproducing your issue (which shouldn´t require any additional add-on) and then provide a new logfile.

**Comment by DaVukovic** [comment]
I ´ll remove that invalid label for now, but I really doubt that it´s normal that we have over 1300 lines of notifications from installed addons. In sum we 19 times the notification that Estuary has been installed. 

So either something is really strange with your installation (where I would suggest a completely fresh install including deinstalling the existing Kodi installation) or you haven´t done what I´ve asked for ;) 

But I´m not too sure, so I let others look into this issue.

**Comment by Sword0fTheSpirit** [comment]
Thank you sir for your help
Sent from Yahoo Mail on Android 
 
  On Fri, Feb 15, 2019 at 6:15 AM, DaVukovic<notifications@github.com> wrote:   
I ´ll remove that invalid label for now, but I really doubt that it´s normal that we have over 1300 lines of notifications from installed addons. In sum we 19 times the notification that Estuary has been installed.

So either something is really strange with your installation (where I would suggest a completely fresh install including deinstalling the existing Kodi installation) or you haven´t done what I´ve asked for ;)

But I´m not too sure, so I let others look into this issue.

**Comment by Sword0fTheSpirit** [comment]
Just to let you know sir, I did a full reinstall of Kodi, uninstalling my previous install. This solved the problem for me. Also, I did not reinstall any of the banned add-ons that I put on many years ago (and never used anyways). Thank you very much for helping me with my issue sir.
Much appreciation,Craig K

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 15, 2019 at 4:16 PM, Craig Kusmierski<craigkusmierski@sbcglobal.net> wrote:   Thank you sir for your help
Sent from Yahoo Mail on Android 
 
  On Fri, Feb 15, 2019 at 6:15 AM, DaVukovic<notifications@github.com> wrote:   
I ´ll remove that invalid label for now, but I really doubt that it´s normal that we have over 1300 lines of notifications from installed addons. In sum we 19 times the notification that Estuary has been installed.

So either something is really strange with your installation (where I would suggest a completely fresh install including deinstalling the existing Kodi installation) or you haven´t done what I´ve asked for ;)

But I´m not too sure, so I let others look into this issue.

**Comment by Sword0fTheSpirit** [comment]
I apologize sir. I made a mistake. A full reinstall of Kodi did not solve the problem. When I play videos from the 'FILES' category everything works correctly, but when I access my library from the 'Movies' category I still get the same exact problem I described above, even after the full reinstall of Kodi. I think it may be a problem with Kodi.

**Comment by snake3ca** [comment]
This sound like the same issue im having.  I reported it previously.  #15414 Bluray and DVD ISO playback from library not working.  I have installed the Kodi 18.1 build that was just released today and same issue is happening but my issue is not marked resolved yet.

**Comment by Sword0fTheSpirit** [comment]
I agree Snake3ca, this sounds like the exact same problem. Is your problem related to the 'play next video automatically' feature being on or off also though I'm curious?

**Comment by snake3ca** [comment]
Hi yeah I tested and when play next video automatically is on the DVD/Bluray menu also does not display..

**Comment by Sword0fTheSpirit** [comment]
So the problem persists even when 'play next video automatically' is turned off?

Sent from Yahoo Mail on Android 
 
  On Sat, Mar 9, 2019 at 8:07 AM, snake3ca<notifications@github.com> wrote:   
Hi yeah I tested and when play next video automatically is on the DVD/Bluray menu also does not display..

**Comment by snake3ca** [comment]
Yeah every iso i play from library the menu does not work. If I right click and goto play it works fine though. Also plays fine from the movie information menu.

**Comment by enen92** [comment]
@Sword0fTheSpirit can you please test https://github.com/xbmc/xbmc/pull/15718? Test builds can be found here: https://jenkins.kodi.tv/job/BuildMulti-PR/11501/

**Comment by Sword0fTheSpirit** [comment]
I'm confused because I want to install the Win-64 version, but it has a different build # next to it...


WIN-64build #8689( 16 min )

    On Sunday, March 10, 2019, 6:12:51 PM CDT, enen92 <notifications@github.com> wrote:  
 
 
@Sword0fTheSpirit can you please test #15718? Test builds can be found here: https://jenkins.kodi.tv/job/BuildMulti-PR/11501/

**Comment by enen92** [comment]
@Sword0fTheSpirit my bad, I thought Jenkins would upload the build artifact for windows too. You can try this testbuild:

http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20190311-91b0cf7a-PR15718-merge-x64.exe

**Comment by Sword0fTheSpirit** [comment]
Sir, I thank you. This has fixed my problem completely. I haven't had Kodi working this perfectly in years. Thank you very much.

I have 2 more questions for you if you will.

1. Does this mean that I will not be able to download future releases of Kodi, or will this build be built into the future updates?

2. Is there any way to set up Kodi so that the Shuffle/Random button in the video player is always turned on, it always seems to reset itself to off?

Once again, thank you so much.
    On Monday, March 11, 2019, 7:01:41 AM CDT, enen92 <notifications@github.com> wrote:  
 
 
@Sword0fTheSpirit my bad, I thought Jenkins would upload the build artifact for windows too. You can try this testbuild:

http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20190311-91b0cf7a-PR15718-merge-x64.exe

**Comment by enen92** [comment]
@the-black-eagle looking around my assigned issues found this one. I believe you fixed this already for Matrix and superseeded my pr, am I right?

**Comment by the-black-eagle** [comment]
@enen92 Yes, although I am unable right now to test whether 'play next video automatically' works correctly.  Looking at the two PR's yours was different in that area.

**Comment by enen92** [comment]
Ok I'll do some tests with the current nightly to check wether I can still reproduce the issue. Thanks for the answer

**Comment by enen92** [comment]
Tested and confirm this is fixed in current Matrix nightly build. Both playback and play next movie work fine.
