### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by unknowtech** [xbmc/xbmc#15528]
When i have bluethoot enabled , i trying open kodi  apps closed forcing and comme back launcher 

when disabled bluethoot and trying it,s work , and enabled after enter apps bluethoot work

**Comment by DaVukovic** [comment]
You haven't followed our issue template. Please follow the template and get us the information we ask for. We will at least need a debog or a crashlog.

I'll mark this as invalid for the time being.

**Comment by DaVukovic** [comment]
7 days, no reaction

closed
