### ISSUE TITLE
Unable to switch Audio Stream (from Dolby Digital to DTS) during playback

### ISSUE THREAD

**Issue by iz8mbw** [xbmc/xbmc#15523]
### Describe the bug
Hi.
Using Kodi version 18 (18.1-RC1 Git:20190211-379f5f9).
Kodi is configured for audio passtrought, so both Dolby Digital and DTS will pass over HDMI passtrought.
'Adjust display refresh rate' is setted to Start/Stop, 'White list' is populated.

If I put in play a movie with DTS audio during playing a Dolby Digital movie, no audio is heard and from my AVR I still see the previous codec (Dolby Digital) instead to switch to DTS.
So it seems, for same reasons, that Kodi will not go to switch to new audio codec.
This problem was already discussed here: https://forum.kodi.tv/showthread.php?tid=327486 and solved in the past by @fritsch with this PR https://github.com/xbmc/xbmc/pull/14598

May be this my "new issue" is related to that issue https://github.com/xbmc/xbmc/issues/15490

I don't know if also this info can help: generally when I play a movie if I go to pause it, on my AVR I see the codec disappear for some instants and after some instants reappears. If I go to put in play again this happens again: on my AVR I see the codec disappear for some instants and after some instants reappears.
So it seems Kodi will go to close and reopen the audio stream both when I put in pause and when i put again in play.
I don't think this behaviors is the best approach also because, when I put again in play I lost some milliseconds of audio....

## Expected Behavior
Audio should correctly switch according to new audio stream

## Possible Fix
May be by fixing this issue https://github.com/xbmc/xbmc/issues/15490 my issue will also be solved.

### To Reproduce
1. Set Kodi for audio passtrought, enable refreshrate / resolution switch
2. Put in play a movie with Dolby Digital audio track
3. During that movie playing go to your library (so your movie play remains playing in background)
4. Choose to play a movie with DTS audio track
5. Now the DTS movie will play but Kodi will not switch to DTS (from Dolby Digital) then no audio is heard and wrong stream type on receiver

### Debuglog
The debuglog can be found here: https://dpaste.de/1k2L/raw

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nvidia Shield firmware 7.2.3 (Android 8)
 - Kodi version: 18.1-RC1 Git:20190211-379f5f9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by iz8mbw** [comment]
ping @fritsch ping @peak3d 
Thanks guys!

**Comment by Mochilote** [comment]
Related to https://github.com/xbmc/xbmc/issues/15504

**Comment by iz8mbw** [comment]
Issue solved with last nightly. Thanks
