### ISSUE TITLE
kodi-x11 package script defaults to kodi-gbm binary

### ISSUE THREAD

**Issue by AnonTester** [xbmc/xbmc#15536]
### Describe the bug
Here is a clear and concise description of what the problem is:

The shell script /usr/bin/kodi that's part of the kodi-x11 package erroneously points to kodi-gbm as it's app-binary. While the script contains various checks to determine the window manager in use, when called from the command line or remotely for something as simple as version check, it fails.

$ /usr/bin/kodi --version
Error: /usr/lib/x86_64-linux-gnu/kodi/kodi-gbm not found
$ dpkg -L kodi-x11
/.
/usr
/usr/bin
/usr/bin/kodi
/usr/bin/kodi-standalone
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/kodi
/usr/lib/x86_64-linux-gnu/kodi/kodi-x11
/usr/lib/x86_64-linux-gnu/kodi/kodi-xrandr
/usr/lib/x86_64-linux-gnu/kodi/system
/usr/lib/x86_64-linux-gnu/kodi/system/libsse4-x86_64-linux.so
/usr/lib/x86_64-linux-gnu/kodi/system/players
/usr/lib/x86_64-linux-gnu/kodi/system/players/VideoPlayer
/usr/lib/x86_64-linux-gnu/kodi/system/players/VideoPlayer/libdvdnav-x86_64-linux.so
/usr/share
/usr/share/doc
/usr/share/doc/kodi-x11
/usr/share/doc/kodi-x11/NEWS.Debian.gz
/usr/share/doc/kodi-x11/changelog.Debian.gz
/usr/share/doc/kodi-x11/copyright

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The expected behaviour is for the shell script part of the kodi-x11 package to refer to the binary that came with it or to be sufficiently flexible as to find the correct one even on the command line without a window manager running.
Therefore, for the kodi-x11 package script, the binary /usr/lib/x86_64-linux-gnu/kodi/kodi-x11 should be called and not the non-existing binary /usr/lib/x86_64-linux-gnu/kodi/kodi-gbm.

## Actual Behavior

Script refers to /usr/lib/x86_64-linux-gnu/kodi/kodi-gbm instead of /usr/lib/x86_64-linux-gnu/kodi/kodi-x11

## Possible Fix

Change line 28 in the script from
APP_BINARY=$LIBDIR/${bin_name}/kodi-gbm
to
APP_BINARY=$LIBDIR/${bin_name}/kodi-x11

### To Reproduce

1. Kodi installation via apt-get install kodi kodi-x11
2. check version from command line via ssh as in kodi --version
3. see error message

### Debuglog

The debuglog can be found here:
N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Not sure if this is the right place to report this bug, I posted this in kodi forum already but got no response from anyone to my question where best to report it:
https://forum.kodi.tv/showthread.php?tid=340371

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04.2 LTS / kernel 4.15.0-45-generic
 - Kodi version: 18.1-RC1 Git:20190217-33be1ec Media Center Kodi

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by wsnipex** [comment]
While you're not wrong, you have a corner case there: You're trying to run kodi from a console without X or Wayland, but don't have the gbm binary, which is needed for this.
Try running kodi --version in a X session and it will work just fine.

**Comment by Rechi** [comment]
@wsnipex if you reorder the install commands in debian/rules the `APP_BINARY` would be set to X11.

**Comment by wsnipex** [comment]
yes I know, but I don't consider this as a real bug. After all, you do need kodi-gbm when not using any window manager.

**Comment by AnonTester** [comment]
It might be a corner case as I'm ssh'ing into my kodi box and just want to get the version information and keep running into the error message. The kodi-standalone script points back to the kodi script and thus fails too as kodi-gbm isn't part of the package.

$ kodi-standalone --version
Error: /usr/lib/x86_64-linux-gnu/kodi/kodi-gbm not found
Error: /usr/lib/x86_64-linux-gnu/kodi/kodi-gbm not found
Error: /usr/lib/x86_64-linux-gnu/kodi/kodi-gbm not found
/usr/bin/kodi --standalone --version has exited in an unclean state 3 times in the last 0 seconds.
Something is probably wrong

You're right that the script works when I export the display variable in that ssh session, however, my main point here is that the script provided with the x11 package defaults to a binary that is not part of the package itself and therefore results in an error message. Obviously very very low priority, but still a bug.

**Comment by fritsch** [comment]
No - it does not.

In order to use kodi-x11 you are responsible to start an xserver, export it. If you don't do that, the kodi script tries a fallback, which is kodi-gbm.

**Comment by fritsch** [comment]
And btw. it has a parameter, called: --windowing that you can use, the parameter would be x11. kodi is a catch all script for every platform, but I think you figured that already.

**Comment by AnonTester** [comment]
The script is aware that there are multiple binaries available depending of the configuration. It checks for both the binaries and whether the relevant windowing system is available later. My point is that the script must not default to a particular binary when it may not exist.

Suggested fix, replace line 28 with this and leave the variable empty if nothing can be found. The script will issue an error later if the file in variable doesn't exist:
if [ -x $LIBDIR/${bin_name}/${bin_name}-wayland ]; then
    APP_BINARY=$LIBDIR/${bin_name}/${bin_name}-wayland
elif [ -x $LIBDIR/${bin_name}/${bin_name}-x11 ]; then
    APP_BINARY=$LIBDIR/${bin_name}/${bin_name}-x11
elif [ -x $LIBDIR/${bin_name}/${bin_name}-gbm ]; then
    APP_BINARY=$LIBDIR/${bin_name}/${bin_name}-gbm
else
    APP_BINARY=""
fi

**Comment by fritsch** [comment]
Thanks for your point.

**Comment by bernd-wechner** [comment]
> While you're not wrong, you have a corner case there: You're trying to run kodi from a console without X or Wayland, but don't have the gbm binary, which is needed for this.
> Try running kodi --version in a X session and it will work just fine.

That works. Thanks. But corner case or no it's a clear bug. And easy enough to fix. Consequence is low, but I wanted the version for another reason and ran into this. Am thankful for this clarification as I could and did remote to X11 session and ran it and got the version. But it remains odd and begs the question Not least because it's referring to a file that no package seems to deliver:

```
$ dpkg-query -S kodi-gbm
dpkg-query: no path found matching pattern *kodi-gbm*
```

Anon-testers fix works. And I see no reason why it shouldn't be merged into the master. Would the Kodi team be open to a PR for that? Has it been tried ...?

**Comment by wsnipex** [comment]
a PR is always welcome

**Comment by lrusak** [comment]
Should be fixed in master due to the multi-windowing changes.
