### ISSUE TITLE
Video player breaks GUI and makes it unusable

### ISSUE THREAD

**Issue by rayfun** [xbmc/xbmc#15530]
### Describe the bug
Here is a clear and concise description of what the problem is:

With a fresh install (config folder previously completely deleted) of Kodi Leia on a Raspberry Pi 3+ playing a video causes all GUI to break.
Player controls are not available/usable and returning to Kodi menus is not possible after starting to play a video.
Interestingly everything works as expected when debugging is enable, presumably because of the top left live debugging information.
The linked video (to my Nextcloud) in the below screenshot section shows quite clear whats happening.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When playing a video in-video player controls can be opened and used.
Going back from a playing video returns the user to the Kodi GUI/menu.

## Actual Behavior

Player controls are not usable when playing a video.
It's not possible to return to Kodi menu after having started to play a video.
It can be seen that controls are there but huge and completely unusable. The GUI is somehow broken in a way that seems to be related to resolution/video mode.

## Possible Fix

As I wrote there's one case when it works as expected and that's also the reason why I cannot deliver a "real"  debug log.
Because when debugging is enabled, player controls can be opened, look as expected and I can return to Kodi menus from playing a video.
I'm most certainly sure the reason for that is that the debug information shown in the top left corner are causing the video mode/graphics to behave differently.

### To Reproduce

1. Select video from disk/library and play it.
2. Video plays.
3. Opening player controls via keyboard or controller does something but controls seem to be broken in regard to resolution/video mode.
4. Going back will stop video as expected and presumably returns to Kodi menu but it's not visible or usable.

### Debuglog

The debuglog can be found here:
As I mentioned above I cannot deliver a "real" debug log as when debugging is enabled everything works as expected.
The log I'm delivering has component-specific loggin enabled for several relevant components as video, window, dbus etc.
Here it is:
https://pastebin.com/qZmpHnze

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screen video: 
Shows two attempts to use player controls that don't work and one attempt using debug logging when it works as expected.
https://cloud.mooselook.de/s/bgEJx3QSPKDmtdQ

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi - RetroPie
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

pi@pi43:~ $ kodi --version
18.0 Git:20190130-aa48862e98 Media Center Kodi
Copyright (C) 2005-2018 Team Kodi - http://kodi.tv
pi@pi43:~ $ apt-cache policy kodi
kodi:
  Installed: 2:18.0-1~stretch
  Candidate: 2:18.0-1~stretch
  Version table:
 *** 2:18.0-1~stretch 500
        500 http://pipplware.pplware.pt/pipplware/dists/stretch/main/binary ./ Packages
        500 http://archive.raspberrypi.org/debian stretch/main armhf Packages
        100 /var/lib/dpkg/status

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by rayfun** [comment]
I've also already tried to change some settings in the "Player" settings section but without any changes.

**Comment by rayfun** [comment]
Everything worked fine with the previous version Kodi 17.6

**Comment by DaVukovic** [comment]
Unfortunately all the component logging you enabled won't show anything if you don't enable debug logging which you missed:

> 10:55:05.637 T:1900240528  NOTICE: Disabled debug logging due to GUI setting. Level 0.

So please enable debug logging and reproduce your issue.

Could you also please do some screenshots from the following settings:

settings -> system -> video
settings -> player -> videos

If I interpret the filename correctly you are trying to play back a 360p file:

> 10:57:11.628 T:1900240528  NOTICE: VideoPlayer::OpenFile: /export/apollon/Movies/(500) Days of Summer (2009)/(500) Days of Summer (2009) 360p.avi

The debuglog will show exactly what kind of file that is. So please add that.

**Comment by rayfun** [comment]
> Unfortunately all the component logging you enabled won't show anything if you don't enable debug logging which you missed:
> 
> > 10:55:05.637 T:1900240528  NOTICE: Disabled debug logging due to GUI setting. Level 0.
> 
> So please enable debug logging and reproduce your issue.

As I mentioned in my bug report only **when I enable debug logging** everything works as expected and **the problem will not occur**. I suppose because of these live debug information showing in the top left corner. So debug logging unfortunately will not help much I suppose. This can also be seen in the screen video linked in my bug report. Still I have attached a debug log but that is not containing info about the problem as it does not occur when debugging is enabled.
This can be seen in the screen video I took.
https://cloud.mooselook.de/s/bgEJx3QSPKDmtdQ
Actual problem can be seen starting at the beginning of the video.
Problem not occuring with debugging enabled in the last third of the third of the video.

[kodi.log](https://github.com/xbmc/xbmc/files/2872102/kodi.log)

> Could you also please do some screenshots from the following settings:
> 
> settings -> system -> video
> settings -> player -> videos

![screenshot000](https://user-images.githubusercontent.com/15213735/52901776-f8181b00-3207-11e9-9ec3-844e8f03df66.png)
![screenshot001](https://user-images.githubusercontent.com/15213735/52901777-f8181b00-3207-11e9-9cf8-9d04c12c8247.png)
![screenshot002](https://user-images.githubusercontent.com/15213735/52901778-f8181b00-3207-11e9-8836-fb50cc695932.png)

> If I interpret the filename correctly you are trying to play back a 360p file:
> 
> > 10:57:11.628 T:1900240528  NOTICE: VideoPlayer::OpenFile: /export/apollon/Movies/(500) Days of Summer (2009)/(500) Days of Summer (2009) 360p.avi
> 
> The debuglog will show exactly what kind of file that is. So please add that.

The problem occurs **with all video files**.

Thanks for your help.

**Comment by rayfun** [comment]
Is it possible to have debug logging without this debug live monitor layover in the top left corner? that way the problem might actually occur but with debug logging.

**Comment by DaVukovic** [comment]
Yes
https://kodi.wiki/view/Advancedsettings.xml#loglevel

Open the drop down menus to see the available options.

**Comment by rayfun** [comment]
So here is the the full debug log with LogLevel 3 with the problem occuring.

https://paste.kodi.tv/pukewimowi.kodi

Sorry about not knowing how to do that earlier.

Again: Problem can be seen in screen video mentioned above.

**Comment by kib** [comment]
It looks like your screen is changing to 640x272 because of the very low resolution of the video, and the old screen actually able to show this resolution.
I think you can solve this by selecting only the desired output sizes in the whitelist, removing everything below 720 from it. Kodi will then upscale.

**Comment by rayfun** [comment]
I've whitelisted the 1920x1080 modes and also played a larger resolution file. Problem still persists. 

Test scenario is:
1. Play video file
2. Open player controls

Updated debug log: https://paste.kodi.tv/ocutecojer.kodi

![screenshot003](https://user-images.githubusercontent.com/15213735/52902997-e2f7b800-3218-11e9-997a-4f14d736bbef.png)
![screenshot004](https://user-images.githubusercontent.com/15213735/52902998-e2f7b800-3218-11e9-9343-7a9e909359ec.png)

**Comment by DaVukovic** [comment]
With the last test with the 1080p file, have you enabled "Adjust display refresh rate" and set it to start stop? If not, could you please enabling that and see if that fixes something for the 1080p file?

Could you also confirm that all this worked fine on the same TV using Kodi 17.6?

For what I can tell, your TV is a HD ready TV which only supports 50 or 60 fps modes on each resolution. So I would also suggest to enable "Synch playback to display" if that hasn't been the case yet. From the screenshots above I see those disabled.

**Comment by fritsch** [comment]
No. That's not correct. He has no support for 50hz / 60hz. 1080 is only an **interlaced** solution. Why his gui is running on interlaced is already wrong.

Besides that: It's not a kodi problem but a debian / stretch / whatever distro problem. As you can see: broken beyond repair. How do I know? Add LibreELEC / osmc / whatever for a test on the SDCard and it will work just fine. So please open a bug with your distribution.

**Comment by kib** [comment]
@fritsch My apologies, as usual you are right and I was very wrong 👍

**Comment by rayfun** [comment]
Indeed switching to LibreElec did the trick. Even though Rasbpian does have many settings in regard to HDMI and video modes I'm not going to play around with that and stay with LibreElec hoping that the game emulation functionality works just as good as with RetroPie/EmulationStation/RetroArch.
Though I cannot only blame the underlying OS, as everything worked fine with 17.6. So there must have been changes that broke it for me.
Thanks for your support.
Cheers, rayfun
