### ISSUE TITLE
Pop up prevent system from suspend.

### ISSUE THREAD

**Issue by gioalex** [xbmc/xbmc#15533]
### Describe the bug
Here is a clear and concise description of what the problem is:

Immediately after the start of the pc I get the attached message.
Same message after resuming from suspend.
Xubuntu 18.10 configured with static IP.
The problem is that this pop-up prevent the system from going to suspend.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect that the system can go in suspend event with this popup.

## Actual Behavior

System stay on power on.

## Possible Fix

inhibith this popup from preventing suspend

### To Reproduce

1. Put kodi in the autostart list
2. reboot system

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/2872242/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

[Impossibile to download informations.]
![screenshot_20190216_175232](https://user-images.githubusercontent.com/8467793/52902994-d83d2300-3218-11e9-94e3-aa88b19485d3.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: xubuntu 18.10 64 bit
 - Kodi version: 18.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Disable **Update library on startup**
https://kodi.wiki/view/Settings/Media/Library#Video_Library

**Comment by gioalex** [comment]
Yes, I can but I think that this is a workaround...not a solution.
