### ISSUE TITLE
Kodi 18.0 and 18.1 Won’t connect to SMB Network Drive

### ISSUE THREAD

**Issue by TBNRerebus** [xbmc/xbmc#15544]
### Encounters “Error: Operation Timed Out” / “Remote share: Couldn’t connect to network server"
Here is a clear and concise description of what the problem is:
I store my movie files on a 1 Terabyte Apple AirPort Time Capsule (3rd Generation) drive and access them through the SMBv1 share on Kodi and have never had a problem with it on Krypton v17.6. However, when I upgraded from v17.6 to v18.0 and 18.1, the SMB share doesn’t work much anymore. Leia will sometimes connect to my SMB drive for a short thirty seconds or so immediately when you open the program but after that minute it will give you a “Error: Operation timed out” message, even if I try to re-add the remote path under “add videos”. I have tried re-installing the program, tried using another device with a different OS, and tried hard wiring my devices to eliminate any network issues. Kodi v17.6 has no problems even when I uninstall v18 and then immediately install v17.6. This issue only occurs in v18/v18.1.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Kodi connects to SMBv1 share and streams video files from network drive without any errors or issues.

## Actual Behavior
Kodi connects to share for the first thirty seconds after program launch, then displays an Error: Operation timed out” / “Remote share: Couldn’t connect to network server” forever after when trying to access files on the share from Videos>Files.

## Possible Fix
Revert the SMB protocol back to what it was in v17.6

### To Reproduce

1. Copy Video files to a Apple AirPort Extreme Time Capsule drive
2. (Attempt to) Connect Kodi v18 to the AirPort Drive from Videos>Files>Add Videos>Browse>Add network location…>(enter Server name: 192.168.1.1/Shared folder <name of your time capsule hard drive>/Username: anything, really/Password: (password to your time capsule)
3. If connection was successful, wait a couple minutes, then try to play one of the files on the network drive

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/2873495/kodi.log)

### Screenshots 
Here are some screenshots to help explain the problem:

![screen shot 2019-02-17 at 5 17 59 pm](https://user-images.githubusercontent.com/47725141/52920218-32e98400-32d8-11e9-8cdb-5dc1a1873c54.png)
![screen shot 2019-02-17 at 5 18 09 pm](https://user-images.githubusercontent.com/47725141/52920227-485eae00-32d8-11e9-83b8-fe721ba57c0c.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ADun3306x** [comment]
same issue occurs in the recent Linux build... My Samba servers work fine on Ubuntu 18.10 for other connections, but with Kodi its game over, as it continually fails

**Comment by DaVukovic** [comment]
duplicate #15502 
closed

**Comment by w7my** [comment]
The error seems to be related to 'workgroups' and only with browsing. Setting a file location:
\\smb\hostname\foldername\file   works as well as
\\smb\IP ADDRESS\foldername\filename

**Comment by patricksavalle** [comment]
I have this behavior on a Sony KD-55XH8096BAEP 4K TV with Android v9 running Kodi v18.9 from the Playstore. Pretty annoying.
