### ISSUE TITLE
[UWP] The nightly builds and Offical Microsoft Store build are created differently (Source)

### ISSUE THREAD

**Issue by ritzcrackr** [xbmc/xbmc#15551]
### Describe the bug
Here is a clear and concise description of what the problem is:

The Official build as installed from the Microsoft Store is built differently than the nightly builds. The package from the Microsoft Store includes the SMB support via XFILE::CWin32SMBDirectory and CWin32SMBFile. The nightly builds do not include this support. When looking at the source in master and looking at the other commits this difference is not possible. The only explanation is that the Microsoft Store build is created from a private fork with undisclosed changes. Below is the output of strings and searching for "SMB" in the output. I have run this against the latest 18.1.500.0 release and two builds from http://mirrors.kodi.tv/test-builds/windows/uwp64/. I have also tested several other nightly builds to confirm that they don't support SMB in their default configuration.

F:=\>$s1 = strings.exe -a  'C:\Program Files\WindowsApps\XBMCFoundation.Kodi_18.1.500.0_x64__4n2hpmxwrvr6p\kodi.exe'
F:=\>$s1 | ?{$_ -match "SMB"}
SMBA
smb
smb:
smb://
smb.winsserver
smb.workgroup
smb.minprotocol
smb.maxprotocol
smb.legacysecurity
_smb._tcp.
has_filesystem_smb
^smb:// , / , \\ , g
^smb:\\\\ , smb:(\\\\[^\\]*\\) , \1 ,
**XFILE::CWin32SMBDirectory::GetDirectory
XFILE::CWin32SMBDirectory::RealCreate
XFILE::CWin32SMBDirectory::GetNetworkResources
XFILE::CWin32SMBDirectory::ConnectAndAuthenticate**
smb
smbs
SMB
SMBS
tsmb_size is 0
**.?AVCWin32SMBDirectory@XFILE@@
.?AVCWin32SMBFile@XFILE@@**

F:=\>$s2 = strings.exe -a F:\Kodi-20190217-8cfdc895-master-x64\kodi.exe
F:=\>$s2 | ?{$_ -match "SMB"}
smb.winsserver
smb.workgroup
smb.minprotocol
smb.maxprotocol
smb.legacysecurity
smb
smb://
tsmb_size is 0

F:=\>$s3 = strings.exe -a F:\Kodi-20190122-aca0bd51-upw_17.9.143-x64\kodi.exe
F:=\>$s3 | ?{$_ -match "SMB"}
smb.winsserver
smb.workgroup
smb.minprotocol
smb.maxprotocol
smb.legacysecurity
smb
smb://
tsmb_size is 0

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expect the Official and night builds to be produced from the same source but signed using different signing keys.

## Actual Behavior

The nightly and official builds are produced from different source and signing keys.

## Possible Fix

Commit the changes that are used to produce the official Microsoft Store builds to main repo.

### To Reproduce

1. Install the official build from the Microsoft Store
2. Connect to an SMB share or Enable PVR WMC Client
3. Connect to SMB share. (This should fail)

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [X] Windows UWP

 - Operating system version/name: Windows 10 1809
 - Kodi version: 18.1.500.0 x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MartijnKaijser** [comment]
No it's build from the same source.

**Comment by ritzcrackr** [comment]
Thanks for that clarification. Where is this documentation then on how this is built/packaged. I am aware of the bridges there was no evidence anywhere that this was being done. Especially when the UWP code is in folders called Win10. How exactly are the Win10 UWP versions supposed to be tested, package the Win32 versions as UWP?
