### ISSUE TITLE
Movies by year lists 1601 with no movies in it

### ISSUE THREAD

**Issue by tylerszabo** [xbmc/xbmc#15554]
### Describe the bug

A movie with an empty year will cause a year 1601 to be listed when sorting by release year.

## Expected Behavior

- Movies without a known year should cause a spurious year entry.
- Movies without a known year should either be omitted entirely or be listed under a category of "Unknown" (or equivalent).

## Actual Behavior

Causes movies listed by year on the default theme to show a 1601 folder; this folder will be empty when opened. Movies with the `0` year cannot be found via the by-year index.

## Possible Fix

It appears that Kodi correctly queries by the year 1601 and (rightly) finds no movies from that year when listing movies under a heading. Thus some code to display a nully year value as "Unknown" and query for that same nully value should solve both issues.

## To Reproduce

(only tested with MariaDB backend)
1. Create a movie `.nfo` file that contains en explicit empty element `<year></year>` (can occur when using MediaElch)
2. Use a "local information only" movie scraper and scan a directory containing that `.nfo` and video.
3. This will cause Kodi to set `'0'` in `premiered` for that entry in the database.

```SQL
SELECT * FROM movie WHERE premiered = '0';
```

4. Navigate to movies sorted by year in the default skin.
5. Observe a year of 1601 is listed (screenshot)
6. When selecting that year observe there are no titles (if the database is explicitly edited to have a movie from 1601 it will still appear).

### Debuglog

None.

### Screenshots 

![year 1601](https://user-images.githubusercontent.com/315343/53007425-176f9d80-33ec-11e9-83a9-1c1169890909.PNG)

## Additional context or screenshots (if appropriate)

1601-01-01 is the `FILETIME` epoch on Windows ([background](https://blogs.msdn.microsoft.com/oldnewthing/20090306-00/?p=18913/), [converter](https://www.epochconverter.com/ldap)). `FILETIME` uses [unsigned members](https://docs.microsoft.com/en-us/windows/desktop/api/minwinbase/ns-minwinbase-filetime) and thus doesn't support any times before it's epoch (no negative dates).

It seems to be reasonable enough to assume a `FILETIME` of `0` (or January 1, 1601) is a good "null" value as that predates movies ([earliest animation](https://en.wikipedia.org/wiki/Flip_book), [earliest film](https://en.wikipedia.org/wiki/Sallie_Gardner_at_a_Gallop)).

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64-bit
 - Kodi version: 18.1 8cfdc895f3

**Comment by zag2me** [comment]
This has bugged me for years! It happens especially when TMDB doesnt scrape properly for any reason. Awesome if we can get a fix. I'm not sure if this effects music as well?

**Comment by tylerszabo** [comment]
@zag2me if you can point me to a bug and a repro I might be able to take a crack at it. It so happened that I had a repro for this one.

**Comment by zag2me** [comment]
Just tested with music and I don't see any issue.

**Comment by ribtin** [comment]
I'm also experiencing this issue, and I opened the MyVideos.db file in DBbrowser to see what was going on. Turns out all the TV-shows I've added myself by making .nfos have somehow automatically been assigned the date 1601-01-01.

![screenshot at 22-27-43](https://user-images.githubusercontent.com/13023948/53702097-a7a5dd80-3e03-11e9-9030-1fe7281397f4.png)

**Comment by tylerszabo** [comment]
@ribtin if you can get a repro I'll take a look to see if there's another path causing this. I was only able to get `0` as the date entry in the DB when the `<year></year>` was empty in the .nfo but I wouldn't be surprised if import/export/import caused this.

I'd also open a separate bug for it; but if you do please @ me on it.

**Comment by ribtin** [comment]
@tylerszabo Hi. I'm new to github, so sorry but not exactly sure what you mean by "get a repro"?

I can however tell you that I didn't actually include the year tag at all in the .nfos of the affected shows. I just made tvshow.nfo very simple, like this:
```
<tvshow xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <title>3D Examples</title>
  <plot>Various clips that show off 3D in a spectacular way.</plot>
  <locked>false</locked>
</tvshow>
```
And then also very simple .nfo for each episode, which looks like this:
```
<episodedetails>
  <title>The Suicide Shop 1</title>
  <runtime>1</runtime>
  <aired>2012-01-01</aired>
  <season>1</season>
  <episode>1</episode>
  <plot>Cartoons work especially well in 3D. Particularly those that are drawn in 2D, so that the borders around each individual object is clear and precise.</plot>
  <locked>false</locked>
</episodedetails>
```

**Comment by tylerszabo** [comment]
By "repro" I mean method of consistently reproducing the error; sorry for the jargon. The details you gave here seem pretty good - if they're sufficient to reproduce the issue (ie. no additional steps) then I can take a crack at it. It'd help to first verify on the latest nightly build to ensure that #15615 didn't fix it (Nightly builds of `master` after 2019-02-26 will have this change).

If it is reproducible on that build or later I'd suggest creating another issue with the bug report (since this one is scoped to just the movies-by-year display and is closed)
