### ISSUE TITLE
18.1 & FireTV Stick: Massive Lags on playing video files

### ISSUE THREAD

**Issue by Xembalo** [xbmc/xbmc#15550]
### Describe the bug
Here is a clear and concise description of what the problem is:

18.0 on my FireTV Stick works very fine. 18.1 RC and Final have massive lags and "speeds" playing all types of video files. Voice and video is all times asynchron, sometimes video is faster than the voice, sometimes slower. 
After downgrading keeping all data to 18.0, everything is fine again. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Videos playing fine

## Actual Behavior

see above

### To Reproduce

1. see above
2.
3.

### Debuglog

The debuglog can be found here:
t.b.d.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Xembalo** [comment]
What do you need to mark it as valid? Debug-Log from 18.0 vs. 18.1?

**Comment by DaVukovic** [comment]
yes

The invalid label will be removed after you submitted a log

**Comment by DaVukovic** [comment]
I guess waiting 10 days for a log is long enough

Issue closed
