### ISSUE TITLE
[music] Support the universal FMPS standard (FMPS_RATING tag) along with the RATING & POPM tag

### ISSUE THREAD

**Issue by kyriakosbrastianos** [xbmc/xbmc#15558]
[music] Support the universal FMPS standard (FMPS_RATING tag) along with the RATING & POPM tag

The fmps_rating is already fully supported (read/write) by a lot of music players like Amarok, Clementine, Cantata (mpd client) Rhythmbox, Banshee etc. 
So a lot of users have their library rated with the fmps_rating tag but on KODI is not usable / visible.
Also there is no easy solution as i can see for a user to convert the fmps_rating tag to POPM or RATING to be able to use it with KODI.

**Comment by KarellenX** [comment]
Thank you for your report, but our Issues/Bugs section is not the place for Feature Requests

Please use the Features Request section in the Kodi forum.

**Comment by KarellenX** [comment]
Thanks @kyriakosbrastianos 

Thread is here... https://forum.kodi.tv/showthread.php?tid=341103

I'll close this now.
