### ISSUE TITLE
Rename internal MusicBrainz" Track" ID references to properly note that they're Recording IDs

### ISSUE THREAD

**Issue by Freso** [xbmc/xbmc#15567]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi currently [internally references "MusicBrainz Track ID"](https://github.com/xbmc/xbmc/search?q=MusicBrainzTrackID&unscoped_q=MusicBrainzTrackID) where it is actually referring to [MusicBrainz Recordings](https://musicbrainz.org/doc/Recording), which can "bleed out" to the public leading to confusing/ambiguous announcements when features or fixes related to this are published (e.g., "Improved handling of duplicate MusicBrainzTrackID within the same album" in [Kodi 18’s changelog](https://kodi.wiki/view/Kodi_v18_(Leia)_changelog#Music_Library)).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

References in the code to "MusicBrainz Track" should refer to [MusicBrainz Tracks](https://musicbrainz.org/doc/Track). If talking about [MusicBrainz Recordings](https://musicbrainz.org/doc/Recording), "MusicBrainz Recording" should be used.

## Actual Behavior

"MusicBrainz Track" references refer to MusicBrainz Recordings.

## Possible Fix

Rename "MusicBrainz Track" to "MusicBrainz Recording" in most (if not all?) places of the code, except where referring to tag names. (MusicBrainz Recording IDs are, for legacy reasons, stored in `UFID://musicbrainz.org`/`MUSICBRAINZ_TRACKID`/`----:com.apple.iTunes:MusicBrainz Track Id`; see [Picard’s tag mappings](https://picard.musicbrainz.org/docs/mappings/).)

**Comment by DaveTBlake** [comment]
This is an area where Musicbrainz Picard has created naming confusion itself by mismatching tags and internal names. I am unconvinced that Kodi is in anyway responsible for any public confusion, or has any reason to change to follow Picard _internal_ naming. After all Kodi talks about "albums" not "releases" too.

Kodi uses the `MUSICBRAINZ_TRACKID` ,  UFID://musicbrainz.org,  `----:com.apple.iTunes:MusicBrainz Track Id`, `MusicBrainz/Track Id` tag, and thus refers to it internally as Musicbrainz Track Id or MusicBrainzTrackId. Makes sense to me.

Inexplicably but I guess historically Picard calls this "Musicbrainz Recording ID", and then labels a set of tags with "releasetrack" in the name as "Musicbrainz Track Id". So TRACKID is recording id, and RELEASETRACKID is trac id. Yucky!!

The interesting point is if MUSICBRAINZ_RELEASETRACKID is guaranteed to be unique across albums, it could be worth considering switching to using that tag instread. However it would be a breaking change requiring total rescanning of all music files, and even for some users retagging too.

**Comment by Freso** [comment]
It's not a Picard thing, it's a MusicBrainz thing. MusicBrainz prior to [NGS](https://wiki.musicbrainz.org/History:Next_Generation_Schema) has no separate notion of "Recordings" (shared between mediums/releases) and "Tracks" (unique across mediums/releases), so when the tag names were first coined, "Track ID" was used because MusicBrainz has tracks on Releases. During NGS, tracks were converted to recordings and the notion of "tracks" per se was actually dropped entirely for a while, until it was realised that it wasn't actually possible to uniquely identify the position of a track on a given medium/release because sometimes the same recording was used multiple times in a track listing, and thus track as-an-(semi)entity was reinstated.

"`MUSICBRAINZ_TRACKID`" predates MusicBrainz Recordings, but a MusicBrainz "Track" ID from 2004 *should* resolve to a MusicBrainz Recording today.

**Comment by DaveTBlake** [comment]
Thanks for the Musicbrainz history. Honestly I can't see any issue with Kodi code using the name of the tag it fetches data from in the names of variables, and data fields where that value is stored. What Musicbrainz currently calls that information is up to them.
