### ISSUE TITLE
Videos in the picture browser are played in an infinite loop

### ISSUE THREAD

**Issue by RetroGreaser** [xbmc/xbmc#15569]
I am using Kodi 18.1 on Windows 7. I have a folder with jpg pictures and mp4 videos, that I access from the "Pictures" main menu item. Now I can skip through the items of the folder by using the cursor left/right keys. When coming to a video, I get the following behavior:

In Kodi 17 I get an Icon instead of the video showing that I can start the video playback with the "Play" button. Upon pressing "Play" the video playbacks and when finished the Icon is displayed again and I can skip to the next element in the folder or start playback again.

In Kodi 18 the behavior is a bit different: As soon as I reach the video with e.g. the Cursor right key, the playback starts immediately (which IMHO is good), but when finished it immediately starts again (which is not good). So the video is played in an infinite loop.

**Comment by RetroGreaser** [comment]
Logfile: https://paste.kodi.tv/dujusekipi

**Comment by DaVukovic** [comment]
Same here, please remove the banned add-ons and repositories

**Comment by RetroGreaser** [comment]
Banned Add-Ons removed.
Logfile: https://paste.kodi.tv/axifobahul

**Comment by DaVukovic** [comment]
There are still leftovers here as well as in the other log at the other report you created

Pease retry with a vanilla Kodi.

**Comment by RetroGreaser** [comment]
OK, I have scrapped my complete installation an have installed Kodi 18.1 completely from scatch. With the exact same result.
Here's the log: https://paste.kodi.tv/varikofove
