### ISSUE TITLE
Launching cross scripts via RunScript is not compatible with Kodi17.6 behavior (in some cases)

### ISSUE THREAD

**Issue by bigretromike** [xbmc/xbmc#15565]
### Describe the bug

Here is a clear and concise description of what the problem is:
When lunching script from plugin code that was working for 17.6 and 18-alpha now does nothing. Without clear error message. 
When running `xbmc.executebuildin('RunScript('script.name','?param=par')` from inside not scrip.name plugin code just fail. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When I run `RunScript` I expect to script being executed

## Actual Behavior

When I run `RunScript` nothing happens

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
[debuglog](https://paste.kodi.tv/kifimibula.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 7 Pro x64, Windows 10 Pro x64
 - Kodi version: 18.0 x64, 18.1 x64, 18.0-python3, 18.1-python3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by bigretromike** [comment]
The only workaround I find is:
- inside main plugin import script 1
- in script 1 make function that call `RunScript` of script 2
- now main plugin can Invoke `RunScript` of script 2, because directly it doesn't work.

**Comment by bigretromike** [comment]
Just now, I discovered that `xbmc.sleep(1000)`, is this intended thing? why do we need sleep kodi to make windowXML with progress bar appear?

**Comment by enen92** [comment]
@bigretromike can you provide steps to reproduce the error?

**Comment by bigretromike** [comment]
the workaround this issue was to put `xbmc.sleep(500)` before doing `doModal` on custom `WindowXML` The issue is that for some reason in kodi18.x when executing custom window from script inside plugin there need to be added some delay, because without delay the window would fail to show up without anything interesting in debug.log. The code worked fine in kodi17.x. If anyone will have problem, try to add small delay between running it and showing it. I would prefer someone fixing my older issue: https://github.com/xbmc/xbmc/issues/14573 than this one.
