### ISSUE TITLE
Kodi 18.1 starts audio playback twice in Searchlist

### ISSUE THREAD

**Issue by RetroGreaser** [xbmc/xbmc#15568]
I use Kodi 18.1 on Windows 7. When I select songs using the local search, they are played twice. They will be played for a second and then immediately played in their entirety. See video: https://www.youtube.com/watch?v=KEstn-g2aWk

**Comment by DaVukovic** [comment]
Could you please follow our issue template and submit the debuglog we asked for?

I´ll mark this issue as invalid for the time being. The label will be removed after we see the debuglog

In case you don´t know how to get the log, please follow our wiki: 

https://kodi.wiki/view/Log_file/Easy

Thanks in advance.

**Comment by RetroGreaser** [comment]
Logfile: https://paste.kodi.tv/itelufokax

**Comment by DaVukovic** [comment]
You have banned repositories/add-ons installed. Could you please remove them first and provide a new log, thanks

**Comment by RetroGreaser** [comment]
Banned Add-Ons removed.
New Logfile: https://paste.kodi.tv/kuvigakepo

**Comment by RetroGreaser** [comment]
Sorry, wrong skin. New Logfile: https://paste.kodi.tv/obovesibin

**Comment by RetroGreaser** [comment]
OK, I have scrapped my complete installation an have installed Kodi 18.1 completely from scatch. With the exact same result.
Here's the log: https://paste.kodi.tv/noqocibuzo

**Comment by lich000king** [comment]
This may well be fixed in 18.6. Have you checked?
