### ISSUE TITLE
MacOS Kodi Crash when opening screen sharing

### ISSUE THREAD

**Issue by stratosnik** [xbmc/xbmc#15573]
### Describe the bug
Kodi 18 crash when opening screen sharing on OSX on imac with radeon discreet graphics card.
screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system: OSX 10.14.3

 - Operating system version/name:
 - Kodi version: 18

**Comment by stratosnik** [comment]
Tested again. No problem when the system has English as Preferred Language. It crashes when the selected language is my prefered lnguage, Greek. I do not know if this happens using other locales a well.

**Comment by stratosnik** [comment]
> ## Bug report
> ### Describe the bug
> Kodi 18 crash when opening screen sharing on OSX on imac with radeon discreet graphics card.
> screenshots (if appropriate)
> Here is some additional context or explanation that might help:
> 
> ### Your Environment
> Used Operating system: OSX 10.14.3
> 
> * Operating system version/name:
> * Kodi version: 18
Tested again. Try to view via remote desktop any computer when kodi is open, there is no problem when the system Language is English. It definetly crashes when the selected language is Greek, my preferred language. I can send the crash log. It is systematic, and occurs even if kodi is playing nothing.

**Comment by DaVukovic** [comment]
@stratosnik 

In case you are wondering why we added the invalib label...it's because you ignored the issue template and miss to provide the info we asked for (e. g. a full debuglog).

Nor providing it will cause that nearly nobody will look at your issue at all and it might get closed if you don't provide it. 

Just FYI

**Comment by DaVukovic** [comment]
No response anymore. Issue closed
