### ISSUE TITLE
Introduce user-selectable options to disable Mediacodec for mpeg2, mpeg4, and h.264

### ISSUE THREAD

**Issue by alekseyzimin** [xbmc/xbmc#15571]
## Roadmap or todo suggestion
**Detailed Description**

For android platforms, I propose an addition to "Player" section of settings under "Acceleration", below Mediacodec options, to allow user to enable/disable Mediacodec for mpeg2, mpeg4 and h264 codecs with options 
"Always"
"HD and up"
"Never"

### Context

In many popular android platforms, such as Amazon Fire TV, not all legacy codecs, such as mpeg2 and especially interlaced mpeg2, interlaced h.264 are implemented properly, resulting in stuttering or otherwise unusable video playback for these formats. Currently most android arm devices can decode mpeg2 in software, and code to for that is present and works fine in current Kodi Leia 18.1. In the future Android arm processors will get faster and eventually they will be able to software decode and deinterlace h.264. I do not expect that Android firmware manufacturers will keep support for legacy video format in their firmware.  Giving users an option for software decoding will give users more flexibility and reduce user complaints. 

Currently I have this code implemented in my fork of Kodi, and I set mpeg4 and mpeg4 to hardware decode only "HD and up" and h.264 to hardware decode "Always".  Works fine on Amazon Fire TV 3 and Fire TV stick 4K.  Before these options my DVD ISOs with interlaced mpeg2 did not play properly.

### Possible Implementation

Fritsch has a patch for this already under branch androidswmpeg2 in his fork of Kodi:

commit 77fadaea2c2adb49e57cf4940453b21b40f98ef4 (has a bug)
and 
commit 4666efbf60ac61b0e2dddd9024b3004fc2249f8b (fixes the bug)

I can create and provide the patch for Kodi-master from these two commits. 

### Additional context, screenshots or links
Here are some relevant links or screenshots

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by MartijnKaijser** [comment]
This is a feature request which belongs on the forum

**Comment by alekseyzimin** [comment]
Posted in the forum:
https://forum.kodi.tv/showthread.php?tid=341163
