### ISSUE TITLE
Flatpack/Flathub version fails to start with "ERROR: Unable to create GUI. Exiting" on openSUSE

### ISSUE THREAD

**Issue by januhlir** [xbmc/xbmc#15575]
### Describe the bug
Here is a clear and concise description of what the problem is:

Because openSUSE/PackMan does not currently provide latest Kodi version, that is recently released version 18 Leia I decided to give a Flatpack a try and installed Kodi from:
https://flathub.org/apps/details/tv.kodi.Kodi  

After installation it initially refused to start because it looked for Wayland display server, but I'm using X11. This can be fixed by setting environmental variable WINDOWING to "x11". I figured that only by reading you shell startup file. It would be nice to fix this too and provide better detection what windowing system is actually running.

However application still didn't start. Application quits now with laconic:
"ERROR: Unable to create GUI. Exiting"  
Hmm, no other details given. This being a Flatpack I don't even know where to look for log files :(

I am very sorry if this is not the right place where to report Flatpack version of your software but there seems to be no other. Flathub forwards issue reporting into here.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Previous version, from openSUSE PackMan, de-facto official extension repository, 17.6 worked well for me well. I have reasonably new PC, from 2018, albeit only with Intel card. I don't see why 18 shouldn't work.

### To Reproduce

1. assuming you have openSUSE Leap 15.0 (latest) installed
2. Install Kodi from here: https://flathub.org/apps/details/tv.kodi.Kodi 
3. Follow Flatpak installation instructions:
    flatpak install flathub tv.kodi.Kodi
4. Try to run it as: 
    flatpak run tv.kodi.Kodi

### Debuglog

The debuglog can be found here:

Err, I don't know where to get one...

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: openSUSE Leap 15.0
 - Kodi version: 18 Leia from Flathub

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
> Err, I don't know where to get one...

https://kodi.wiki/view/Log_file/Easy

**Comment by januhlir** [comment]
Thank you Davu
```
20:04:36.575 T:140310640355840  NOTICE: Log File is located: /home/espinosa/.var/app/tv.kodi.Kodi/data/temp/kodi.log
...
20:04:36.725 T:140310640355840   ERROR: X11 Error: No Display found
20:04:36.725 T:140310640355840   FATAL: CApplication::Create: Unable to init windowing system
```

Hmm, `X11 Error: No Display found` is that then.
I run it from command line, while logged through VNC, KDE Konsole, to be most precise.
```
$ export WINDOWING=x11
$ flatpak run tv.kodi.Kodi
ERROR: Unable to create GUI. Exiting
```
Could VNC caused that? Otherwise,  can run any desktop app from this terminal.
I can provide full log if you with.

**Comment by januhlir** [comment]
Aha! This worked:
```
DISPLAY=:1 flatpak run tv.kodi.Kodi
```
Looks like VNC is the culprit. It runs by default on DISPLAYs > 0, in my case DISPLAY=1, aka 5901.
Why cannot Kodi find the correct display itself? Every other application can.

**Comment by fritsch** [comment]
What is "the correct display?" 

0 on Desktop or 1 when vnc / virtual desktop is running or 2 if two are running or 123 if someone has a custom display? All of them? 0 before 12 and 123 after 12?

This is not a bug and works exactly as intended. If you need a special DISPLAY make sure to properly export it in your environment.

Nice, that you got it working, though.

**Comment by januhlir** [comment]
How come the that other applications does not need DISPLAY explicitly specified?
Kodi 17.6 from openSUSE Packman repositories also didn't need that and I did run it through VNC too.
This is the first time ever I had to specify DISPLAY.

**Comment by januhlir** [comment]
Another possibly related information. Current display, ie display my X11 and shell running on, should have env variable DISPLAY set. Well, it does, thou in my case, it has a peculiar format:
```
$ echo $DISPLAY
::1:1
```

**Comment by pkerling** [comment]
Well can you run other FlatPak UI applications? The fault doesn't have to lie with Kodi.
