### ISSUE TITLE
Some timers showing incorrect duration in PVR UI using pvr.vuplus

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#15572]
### Describe the bug
Here is a clear and concise description of what the problem is:

In the Kodi PVR timer UI for some timers the duration is incorrect. It should report the the duration between the start and end time.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

In the Kodi PVR timer UI the duration should report the time from the start time to the end time.

## Actual Behavior

For some timers the duration is incorrect. For many it reports as 1 hour and 5 minutes.

### To Reproduce

1. Create a manual timer with a short duration 3/4 mins using pvr.vuplus
2. Highlight the item in the UI
3. Duration will be incorrect

### Debuglog

The debuglog can be found here:

https://gist.github.com/phunkyfish/dae9df4a1d28344720d05f59351aa3e7

### Screenshots 
Here are some links or screenshots to help explain the problem:

Here is a timer showing the correct duration you can note that the start and end times are correct.

![screen shot 2019-02-21 at 07 23 29](https://user-images.githubusercontent.com/4601187/53187663-8a9b2e80-35fb-11e9-9767-e5cfb67011e2.png)

Here is the next showing the incorrect duration:

![screen shot 2019-02-21 at 07 23 41](https://user-images.githubusercontent.com/4601187/53187701-9c7cd180-35fb-11e9-88e3-f813070c944c.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The start and end times of the timers are correct, there appears to be no option to set the duration in PVR_TIMER so I assume the issue is in the PVR subsystem.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

LibreElec on Intel x86_84

 - Operating system version/name: LibreElec (Intel and Rpi), Windows, MacOsx
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Could it be that the duration is from the epg tag related to the timer? 

Looking at the code, Listitem.Duration for epg tags/timers and recordings gets always resolved via the related epg tag, which would be ofc. not correct.

**Comment by phunkyfish** [comment]
This makes perfect sense. If the use case is recording the remainder of the programme then this would always be incorrect. 

Maybe the duration should be calculated if start and end time differ from the EPG entry.

**Comment by ksooo** [comment]
@phunkyfish could you try this patch and report back:

```
diff --git a/xbmc/pvr/PVRGUIInfo.cpp b/xbmc/pvr/PVRGUIInfo.cpp
index d798d06d1c..ccb8eefc36 100644
--- a/xbmc/pvr/PVRGUIInfo.cpp
+++ b/xbmc/pvr/PVRGUIInfo.cpp
@@ -297,6 +297,13 @@ bool CPVRGUIInfo::GetListItemAndPlayerLabel(const CFileItem *item, const CGUIInf
       case LISTITEM_ENDTIME:
         strValue = timer->EndAsLocalTime().GetAsLocalizedTime("", false);
         return true;
+      case LISTITEM_DURATION:
+        if (timer->GetDuration() > 0)
+        {
+          strValue = StringUtils::SecondsToTimeString(timer->GetDuration(), static_cast<TIME_FORMAT>(info.GetData4()));
+          return true;
+        }
+        return false;
       case LISTITEM_TITLE:
         strValue = timer->Title();
         return true;
@@ -314,7 +321,6 @@ bool CPVRGUIInfo::GetListItemAndPlayerLabel(const CFileItem *item, const CGUIInf
       case LISTITEM_GENRE:
       case LISTITEM_PLOT:
       case LISTITEM_PLOT_OUTLINE:
-      case LISTITEM_DURATION:
       case LISTITEM_ORIGINALTITLE:
       case LISTITEM_YEAR:
       case LISTITEM_SEASON:
diff --git a/xbmc/pvr/timers/PVRTimerInfoTag.cpp b/xbmc/pvr/timers/PVRTimerInfoTag.cpp
index c87fe8fed7..76d68cd308 100644
--- a/xbmc/pvr/timers/PVRTimerInfoTag.cpp
+++ b/xbmc/pvr/timers/PVRTimerInfoTag.cpp
@@ -821,6 +821,14 @@ CDateTime CPVRTimerInfoTag::EndAsLocalTime(void) const
   return retVal;
 }
 
+int CPVRTimerInfoTag::GetDuration() const
+{
+  time_t start, end;
+  m_StartTime.GetAsTime(start);
+  m_StopTime.GetAsTime(end);
+  return end - start > 0 ? end - start : 3600;
+}
+
 CDateTime CPVRTimerInfoTag::FirstDayAsUTC(void) const
 {
   CDateTime retVal = m_FirstDay;
diff --git a/xbmc/pvr/timers/PVRTimerInfoTag.h b/xbmc/pvr/timers/PVRTimerInfoTag.h
index b292e7f051..ba503216ef 100644
--- a/xbmc/pvr/timers/PVRTimerInfoTag.h
+++ b/xbmc/pvr/timers/PVRTimerInfoTag.h
@@ -186,6 +186,12 @@ namespace PVR
     void SetEndFromUTC(CDateTime &end) { m_StopTime = end; }
     void SetEndFromLocalTime(CDateTime &end) { m_StopTime = end.GetAsUTCDateTime(); }
 
+    /*!
+     * @brief Get the duration of this timer in seconds, excluding padding times.
+     * @return The duration.
+     */
+    int GetDuration() const;
+
     CDateTime FirstDayAsUTC(void) const;
     CDateTime FirstDayAsLocalTime(void) const;
     void SetFirstDayFromLocalTime(CDateTime &firstDay) { m_FirstDay = firstDay.GetAsUTCDateTime(); }
```

**Comment by phunkyfish** [comment]
Will do.

**Comment by phunkyfish** [comment]
Patch works perfectly 😉

**Comment by ksooo** [comment]
Thanks for testing. Will PR the fix later today.
