### ISSUE TITLE
Sony DualShock 3 detected as keyboard & input not detected

### ISSUE THREAD

**Issue by psyke83** [xbmc/xbmc#15588]
### Describe the bug
Here is a clear and concise description of what the problem is:

On Kodi 18.x, my Sony DualShock 3 connected via Bluetooth using the default `hid-sony` kernel driver is detected, but Kodi does not recognize any button or axis presses. It was working fine in version 17.6 just prior to upgrading my packages to a 18.0 (and recently 18.1) release.

The issue appears to stem from controller being detected as a "keyboard type" input device: 
```
2019-02-23 00:46:26.869 T:1879044848   DEBUG: CLibInputHandler::DeviceAdded - keyboard type device added: Sony PLAYSTATION(R)3 Controller (event2)
```
The `open_restricted` function's `EVIOCGRAB` ioctl [here](https://github.com/xbmc/xbmc/blob/0bbeefdadbc243a39d3f73124278d37e060836b7/xbmc/platform/linux/input/LibInputHandler.cpp#L35) causes the device to be grabbed, which is presumably blocking the `Joystick Support` add-on from detecting input events. This also causes external applications (such as `evtest`) to complain that the device is grabbed, and actual button/axis presses no longer appear as events until Kodi is exited.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The controller should work normally, and not be detected as a "keyboard type" device.

## Actual Behavior

The controller is detected by Kodi (and a [matching](https://github.com/xbmc/peripheral.joystick/commit/08e4a1adcd0328c0ac00157053e5ee4a3abf3243) button map exists), but no buttons are detected or can be remapped in Kodi's UI.

## Possible Fix

Ensure that the controller is not erroneously flagged as a keyboard-type device in Kodi's input handler.

### To Reproduce

1. Start Kodi
2. Connect controller (tested via Bluetooth using the default `hid-sony` kernel driver)
3. Press buttons and observe for any feedback in Kodi's UI (there is none).

### Debuglog

The debuglog can be found here:
https://gist.github.com/psyke83/0f41e823c293e03629d4756d46d0e0f7

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspbian Stretch
 - Kodi version: 2:18.1-1~stretch (pipplware repository)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by diogomsantos** [comment]
@garbear might help here

**Comment by garbear** [comment]
thanks for the excellent bug report. I'll look into this over the weekend.

**Comment by lrusak** [comment]
```
2019-02-23 00:46:26.869 T:1879044848   DEBUG: CLibInputHandler::DeviceAdded - keyboard type device added: Sony PLAYSTATION(R)3 Controller (event2)
```
This shouldn't happen. It doesn't happen with my PS3 controller when plugged in via usb. I'll try again with bluetooth when my battery is charged.

running the following command:
```
$ udevadm info -n  /dev/input/js0
```
shows this, can you post a similar output?
```
P: /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:054C:0268.0011/input/input56/js0
N: input/js0
S: input/by-id/usb-Sony_PLAYSTATION_R_3_Controller-joystick
S: input/by-path/pci-0000:00:14.0-usb-0:1:1.0-joystick
E: DEVLINKS=/dev/input/by-id/usb-Sony_PLAYSTATION_R_3_Controller-joystick /dev/input/by-path/pci-0000:00:14.0-usb-0:1:1.0-joystick
E: DEVNAME=/dev/input/js0
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:054C:0268.0011/input/input56/js0
E: ID_BUS=usb
E: ID_FOR_SEAT=input-pci-0000_00_14_0-usb-0_1_1_0
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_MODEL=PLAYSTATION_R_3_Controller
E: ID_MODEL_ENC=PLAYSTATION\x28R\x293\x20Controller
E: ID_MODEL_ID=0268
E: ID_PATH=pci-0000:00:14.0-usb-0:1:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_1_1_0
E: ID_REVISION=0100
E: ID_SERIAL=Sony_PLAYSTATION_R_3_Controller
E: ID_TYPE=hid
E: ID_USB_DRIVER=usbhid
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=Sony
E: ID_VENDOR_ENC=Sony
E: ID_VENDOR_ID=054c
E: MAJOR=13
E: MINOR=0
E: SUBSYSTEM=input
E: TAGS=:seat:uaccess:
E: USEC_INITIALIZED=2668174466720
```

as you can see there is no `ID_INPUT_KEYBOARD=1` property. Does your controller work when just using USB?

**Comment by psyke83** [comment]
The problem also occurs via USB. I'm not seeing `ID_INPUT_KEYBOARD` for either type, but unlike your output, I do see `ID_INPUT_KEY`:

Bluetooth:
```
P: /devices/platform/soc/3f201000.serial/tty/ttyAMA0/hci0/hci0:11/0005:054C:0268.000C/input/input12/js0
N: input/js0
E: DEVNAME=/dev/input/js0
E: DEVPATH=/devices/platform/soc/3f201000.serial/tty/ttyAMA0/hci0/hci0:11/0005:054C:0268.000C/input/input12
E: ID_BUS=bluetooth
E: ID_FOR_SEAT=input-platform-soc
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_INPUT_KEY=1
E: ID_PATH=platform-soc
E: ID_PATH_TAG=platform-soc
E: MAJOR=13
E: MINOR=0
E: SUBSYSTEM=input
E: TAGS=:uaccess:seat:
E: USEC_INITIALIZED=11121010322
```

USB:
```
P: /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:054C:0268.000A/input/input9/js0                                                                     
N: input/js0
S: input/by-id/usb-Sony_PLAYSTATION_R_3_Controller-joystick
S: input/by-path/platform-3f980000.usb-usb-0:1.3:1.0-joystick
E: DEVLINKS=/dev/input/by-id/usb-Sony_PLAYSTATION_R_3_Controller-joystick /dev/input/by-path/platform-3f980000.usb-usb-0:1.3:1.0-joystick
E: DEVNAME=/dev/input/js0
E: DEVPATH=/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:054C:0268.000A/input/input9
E: ID_BUS=usb
E: ID_FOR_SEAT=input-platform-3f980000_usb-usb-0_1_3_1_0
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_INPUT_KEY=1
E: ID_MODEL=PLAYSTATION_R_3_Controller
E: ID_MODEL_ENC=PLAYSTATION\x28R\x293\x20Controller
E: ID_MODEL_ID=0268
E: ID_PATH=platform-3f980000.usb-usb-0:1.3:1.0
E: ID_PATH_TAG=platform-3f980000_usb-usb-0_1_3_1_0
E: ID_REVISION=0100
E: ID_SERIAL=Sony_PLAYSTATION_R_3_Controller
E: ID_TYPE=hid
E: ID_USB_DRIVER=usbhid
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=Sony
E: ID_VENDOR_ENC=Sony
E: ID_VENDOR_ID=054c
E: MAJOR=13
E: MINOR=0
E: SUBSYSTEM=input
E: TAGS=:uaccess:seat:
E: USEC_INITIALIZED=10777980216
```
This is with Raspbian stretch using the latest updates, including a recent RPi kernel update (1.20190215-1, 4.14.98-v7+).

**Comment by psyke83** [comment]
As a temporary troubleshooting measure, I installed these udev rules:
```
ACTION=="add", SUBSYSTEMS=="input", ENV{DEVNAME}=="/dev/input/event*", ATTRS{name}=="*PLAYSTATION(R)3 Controller", ENV{ID_INPUT_KEY}=""
ACTION=="add", SUBSYSTEMS=="input", ENV{DEVNAME}=="/dev/input/js*", ATTRS{name}=="*PLAYSTATION(R)3 Controller", ENV{ID_INPUT_KEY}=""
```
After confirming that `ID_INPUT_KEY` no longer appeared in `udevadm`'s info for either node, I tried launching Kodi again... but it didn't change anything, unfortunately.

**Comment by aannenko** [comment]
I'm having a similar issue with Xbox One controller connected via Bluetooth. The system is Retropie (Stretch), Kodi 18.1, last update - today. One single key works - the one to the right of the left stick, by default it works similar to Escape or Backspace keyboard button; other buttons do not react and can't be mapped in Kodi. The problem can't be reproduced when the same controller is attached via USB though.

**Comment by psyke83** [comment]
I did some more experimenting with udev rules, and noticed that the parent of the device event node also contains the `ID_INPUT_KEY`. 

So, I changed the udev rule so that it will also apply to the parent node:
```
ACTION=="add", SUBSYSTEMS=="input", ATTRS{name}=="*PLAYSTATION(R)3 Controller", ENV{ID_INPUT_KEY}=""
```
This appears to resolve the issue. The controller now works as expected, and `evtest` no longer complains about the device being grabbed when running concurrently with Kodi.

I suppose we can chalk this up to a Raspbian stretch bug (perhaps in udev) and not Kodi, then? I've also tested my controller on my laptop running Ubuntu 18.10, and the `ID_INPUT_KEY` property is not propagated to the device via udev.

**Comment by psyke83** [comment]
Relevant bug report: https://github.com/systemd/systemd/issues/5703 (issue present on systemd 233)

Raspbian stretch systemd version:
```
ii  systemd                               232-25+deb9u9                       armhf        system and service manager
```

This is definitely not a Kodi issue, and is already fixed by a later upstream version of systemd, so I'll close this issue. Thanks for the assistance.

**Comment by aannenko** [comment]
In my case installation of [xpadneo](https://github.com/atar-axis/xpadneo) driver fixed the problem with unresponsive buttons and I was able to remap them in Kodi.
