### ISSUE TITLE
FireTV 4K Audio out of sync after skipping

### ISSUE THREAD

**Issue by stepman0** [xbmc/xbmc#15599]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have Kodi 18.2 RC (Nightly 20190222) running on a FireTV 4K 3rd generation. Previously I used 18.0, 18.1 and other nightlies, the issue was the same)

I play videos from my NAS (over NFS). If I start at the beginning, audio and video are in sync. As soon as I skip forward (or backward), audio and video are out of sync (audio is about 5 to 10 seconds behind video).
If I start a movie in the middle, audio and video are also out of sync.

Videos are from onlinetvrecorder. Spec:
H264 - MPEG-4 AVC (part 10) H264
720x576 px
25 fps
MP3 audio (Stereo, 48 kHz)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Audio and video should stay in sync after skipping forward/backward.

## Actual Behavior

Audio and video are out of sync after skipping.

## Possible Fix

No Idea.
This issue does not occur on MrMC (but I have some other issues with MrMc and prefer Kodi)

### To Reproduce

1. Install Kodi 18 nightly on FireTV 4K 3rd generation 
2. Play a H264 movie (e.g. from onlinetvrecorder) 
3. Skip a few steps forward
4. Audio and video are out of sync

### Debuglog

The debuglog can be found here:
 https://paste.kodi.tv/opogohoset.kodi

I started Kodi, played "The Big Bang Theory - S12E08.avi", watched about 30 seconds (sync was fine) and then skipped forward 10 minutes --> audio/video were out of sync

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fire OS 6.2.5.8
 - Kodi version: Kodi 18.2-RC Nightly 20190222

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by stepman0** [comment]
Do you need any further information? What can I do to help fixing this???

**Comment by fritsch** [comment]
No - 20 more Android developers ... thanks for the bug, all information is there.

**Comment by Gertbucket** [comment]
I'd like to amend this issue. 

**System**
Amazon Firestick 4K. Tested all clean default installs of Kodi from 18.0 through to 18.2, both from USB and SMB. 

Sony 4K TV.

**Observation**

**_Not related to skipping_**. All videos are out of sync from the outset.  From my observation, the higher the resolution, the more out of sync. The audio offset to adjust typically: ahead .05 - .125 seconds.

**Affects**

I won't comment on all codecs but it affects x.264, x.265 and VP9. There's another issue with certain AVI's. This isn't about that.

**Other players**

MrMC lite plays the same files in sync with default settings. However Amazon System X-Ray informs it's successfully switching the resolution. Kodi doesn't. Manually changing the resolution/refresh rate in Kodi doesn't not resolve the sync error.

Kodi 18.2 natively on the TV (Android TV) has no sync issues.

**More**

Please let me know if I can provide more information.

**Comment by H3X1C** [comment]
I also am having the issue of videos being out of sync from the start of playback.
Also Amazon firestick 4k

**Comment by stepman0** [comment]
I fixed this issue with disabling hardware acceleration for certain playbacks:
https://forum.kodi.tv/showthread.php?tid=340822&pid=2840569#pid2840569

I use this decoder-filter.xml:
```
<decoderfilter>
    <filter>
        <name>OMX.MTK.VIDEO.DECODER.AVC</name>
        <allowed>true</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>true</dvd-allowed>
        <min-height>600</min-height>
    </filter>
    <filter>
        <name>OMX.MTK.VIDEO.DECODER.DVAV.SER</name>
        <allowed>true</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>true</dvd-allowed>
        <min-height>600</min-height>
    </filter>
    <filter>
        <name>OMX.MTK.VIDEO.DECODER.DVHE.STH</name>
        <allowed>true</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>true</dvd-allowed>
        <min-height>600</min-height>
    </filter>
    <filter>
        <name>OMX.MTK.VIDEO.DECODER.DVHE.STN</name>
        <allowed>true</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>true</dvd-allowed>
        <min-height>600</min-height>
    </filter>
    <filter>
        <name>OMX.MTK.VIDEO.DECODER.H263</name>
        <allowed>true</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>true</dvd-allowed>
        <min-height>600</min-height>
    </filter>
    <filter>
        <name>OMX.MTK.VIDEO.DECODER.HEVC</name>
        <allowed>true</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>true</dvd-allowed>
        <min-height>600</min-height>
    </filter>
    <filter>
        <name>OMX.MTK.VIDEO.DECODER.MPEG2</name>
        <allowed>true</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>true</dvd-allowed>
        <min-height>600</min-height>
    </filter>
    <filter>
        <name>OMX.MTK.VIDEO.DECODER.MPEG4</name>
        <allowed>true</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>true</dvd-allowed>
        <min-height>600</min-height>
    </filter>
    <filter>
        <name>OMX.MTK.VIDEO.DECODER.VP9</name>
        <allowed>true</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>true</dvd-allowed>
        <min-height>600</min-height>
    </filter>
    <filter>
        <name>OMX.MTK.VIDEO.DECODER.VPX</name>
        <allowed>true</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>true</dvd-allowed>
        <min-height>600</min-height>
    </filter>
    <filter>
        <name>OMX.dolby.ac3.decoder</name>
        <allowed>true</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>true</dvd-allowed>
        <min-height>600</min-height>
    </filter>
    <filter>
        <name>OMX.dolby.eac3.decoder</name>
        <allowed>true</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>true</dvd-allowed>
        <min-height>600</min-height>
    </filter>
    <filter>
        <name>OMX.google.aac.decoder</name>
        <allowed>false</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>false</dvd-allowed>
        <min-height>0</min-height>
    </filter>
    <filter>
        <name>OMX.google.amrnb.decoder</name>
        <allowed>false</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>false</dvd-allowed>
        <min-height>0</min-height>
    </filter>
    <filter>
        <name>OMX.google.amrwb.decoder</name>
        <allowed>false</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>false</dvd-allowed>
        <min-height>0</min-height>
    </filter>
    <filter>
        <name>OMX.google.g711.alaw.decoder</name>
        <allowed>false</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>false</dvd-allowed>
        <min-height>0</min-height>
    </filter>
    <filter>
        <name>OMX.google.g711.mlaw.decoder</name>
        <allowed>false</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>false</dvd-allowed>
        <min-height>0</min-height>
    </filter>
    <filter>
        <name>OMX.google.h263.decoder</name>
        <allowed>false</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>false</dvd-allowed>
        <min-height>0</min-height>
    </filter>
    <filter>
        <name>OMX.google.h264.decoder</name>
        <allowed>false</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>false</dvd-allowed>
        <min-height>0</min-height>
    </filter>
    <filter>
        <name>OMX.google.mp3.decoder</name>
        <allowed>false</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>false</dvd-allowed>
        <min-height>0</min-height>
    </filter>
    <filter>
        <name>OMX.google.mpeg2.decoder</name>
        <allowed>false</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>false</dvd-allowed>
        <min-height>0</min-height>
    </filter>
    <filter>
        <name>OMX.google.mpeg4.decoder</name>
        <allowed>false</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>false</dvd-allowed>
        <min-height>0</min-height>
    </filter>
    <filter>
        <name>OMX.google.opus.decoder</name>
        <allowed>false</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>false</dvd-allowed>
        <min-height>0</min-height>
    </filter>
    <filter>
        <name>OMX.google.raw.decoder</name>
        <allowed>false</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>false</dvd-allowed>
        <min-height>0</min-height>
    </filter>
    <filter>
        <name>OMX.google.vorbis.decoder</name>
        <allowed>false</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>false</dvd-allowed>
        <min-height>0</min-height>
    </filter>
    <filter>
        <name>OMX.google.vp8.decoder</name>
        <allowed>false</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>false</dvd-allowed>
        <min-height>0</min-height>
    </filter>
    <filter>
        <name>OMX.google.vp9.decoder</name>
        <allowed>false</allowed>
        <stills-allowed>false</stills-allowed>
        <dvd-allowed>false</dvd-allowed>
        <min-height>0</min-height>
    </filter>
</decoderfilter>

```

In Short: it disables hardware acceleration for resolutions below 600px height, which can be perfectly decoded in software.
