### ISSUE TITLE
Low GUI performance after stopping the video playback

### ISSUE THREAD

**Issue by Romank1** [xbmc/xbmc#15590]
### Describe the bug
Here is a clear and concise description of what the problem is:

Sometimes, after stopping the video playback, the frame rate of the "sliding" Estuary menus will drop - the smoothness is gone until Kodi is restarted or new video playback is started.

### To Reproduce

1. Turn on "Adjust display refresh rate" option.
2.  Start video file or youtube video.
3.  Stop the playback.
4.  Check the "sliding" of Estuary menus.

Repeat these steps many times, until you see the problem.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/utusavukoq.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

To see the problem, please check [this video](http://www.mediafire.com/file/n427jvdjdj8wf2q/VID_20190223_105420_bad.mp4/file), captured by smartphone camera.

To see the normal behavior of Kodi (without the problem), please check [this video](http://www.mediafire.com/file/9s6wvpsihmzw90c/VID_20190223_105821_good.mp4/file), captured by smartphone camera.

### Your Environment
Used Operating system:

 - [x] Windows

 - Operating system version/name: Windows 10 Pro x64, Build 1809
 - Kodi version: 18.1 Leia x64

**Comment by DaVukovic** [comment]
You have banned add-ons and repositories installed. Please remove those first and provide a new and clean logfile.

I'll mark this issue as invalid for the time being

Thanks in advance

**Comment by Romank1** [comment]
New and clean logfile:
https://paste.kodi.tv/utusavukoq.kodi

**Comment by DaVukovic** [comment]
No, it's not clean. Please rename your `%appdata%\Kodi` folder to something  else, then restart Kodi and see if the issue still exists. The renaming of that folder will cause that you have a completely vanilla Kodi. No add-ons, no settings, nothing. But everything is stored at the renamed folder, so you change it back if you want.

**Comment by Romank1** [comment]
I can't reproduce the issue after renaming the`%appdata%\Kodi` folder.

**Comment by DaVukovic** [comment]
Good,

Then we don't have a Kodi issue. You had an issue by installing one of those banned add-ons and repositories. To solve your problem permanently, simply don't install them.

closed
