### ISSUE TITLE
tvOS compiling errors

### ISSUE THREAD

**Issue by Tommrodrigues** [xbmc/xbmc#15594]
### Describe the bug

I have successfully been able to run the following commands in the correct order with no visible issues:
```
cd $HOME
git clone https://github.com/xbmc/xbmc kodi
cd $HOME/kodi/tools/depends
./bootstrap
```

However, after running `./configure --host=arm-apple-darwin --with-platform=tvos`, I receive the following:

```
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
checking build system type... x86_64-apple-darwin18.2.0
checking host system type... arm-apple-darwin
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=c++11... yes
checking for ccache... no
checking for curl... /usr/bin/curl
checking for tar... /usr/bin/tar
found xcodebuild at /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
checking for "*86"... auto is not "*86"
checking for arm-apple-darwin-gcc... no
checking for gcc... gcc
configure: WARNING: using cross tools not prefixed with host triplet
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for main in -lz... yes
configure: error: unsupported platform (tvos)
```

If I then ignore this and attempt to run `make -j$(getconf _NPROCESSORS_ONLN)`, I receive the following:

```
Makefile:1: Makefile.include: No such file or directory
make: *** No rule to make target `Makefile.include'.  Stop.
```

Is anyone aware of what is causing these errors and if there is a fix?

### Operating system
 - [x] OSX

Thank you in advance for your help,

Kind regards, Tom

**Comment by davilla** [comment]
configure: error: unsupported platform (tvos)

says it all :)

**Comment by Tommrodrigues** [comment]
@davilla Indeed, you'd think so, but `tvos` is listed as a supported platform [here](https://github.com/xbmc/xbmc/blob/master/tools/depends/README.md#darwin).

**Comment by jjd-uk** [comment]
@hudokkow That's your documention isn't it? As far as I'm aware tvos is not official supported and all that's ever been provided is experimental builds from a branch on @Memphiz github which I believe is stuck at v17 so it's not currently possible to build tvos based on Master.

**Comment by Memphiz** [comment]
TvOS was supported for depends build in master for quiet a while. No idea what broke it but it doesn’t really matter as there is no official tvOS support for the rest ...

**Comment by Tommrodrigues** [comment]
Ah I see, any possibility for `tvOS` to be officially supported? I think the take-up would large as there are already many online guides (like [this](https://www.macworld.co.uk/how-to/iosapps/how-install-kodi-on-apple-tv-2017-3640061/) one) which walk you through the process of using [these](http://mirrors.kodi.tv/test-builds/darwin/tvos/) precompiled binaries on the Apple TV. Yet it would be great if this repository allowed us to compile up-to-date and maintained versions of Kodi with all the add-ons etc.

**Comment by MartijnKaijser** [comment]
Only if some one is willing to take up support for it.

**Comment by Rechi** [comment]
@Memphiz https://github.com/xbmc/xbmc/pull/13526/commits/9e5f864b2efc678120fbc6f7fde5a208eb564621, FFmpeg and OpenSSL bumps broke tvOS depends build.

**Comment by Memphiz** [comment]
Good to know - that git hash in your message looks unrelated though?

**Comment by Rechi** [comment]
It is the reason for `unsupported platform (tvos)` message.
