### ISSUE TITLE
PVR on Android: AC3 stream will be sometimes detected with 0 channels

### ISSUE THREAD

**Issue by M2k80** [xbmc/xbmc#15604]
### Describe the bug
Here is a clear and concise description of what the problem is:

Sometimes after channel switch the primary AC3 stream will be detected with 0 Channels, then the second stream with another language will be used. manually change back to the primary wrong detected AC3 stream works.
Using pvr.vuplus

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

AC3 stream should detected with 6 or 2 channels and the priorised channel should be used like normal.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

normal log (wrong detection on last channel change) 
https://www.dropbox.com/s/6qypka37nysehen/PVR_0_AC3_Channels.log?dl=0

advanced log
https://www.dropbox.com/s/lkghjbyin7s78k7/PVR_0_AC3_Channels_advanced.log?dl=0
### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

https://www.dropbox.com/s/nh7lmxwma6g7jok/IMAG1189.jpg?dl=0

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: NVIDIA SHIELD Android TV with Android 8.0.0 API level 26, kernel: Linux ARM 64-bit version 4.9.109-tegra-g5e85e89
 - Kodi version: 18.2-RC1 Git:20190223-c275da3a42-dirty

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by iz8mbw** [comment]
Have you tried last (28 feb) nightly version?

**Comment by M2k80** [comment]
udpated last night, and i got first time that both, first and second stream were detected with 0 channels and i got no sound. i had to switch to another channel and back again to get it working
