### ISSUE TITLE
Fields in PVR_TIMER never used in UI in preference of EPG data which can be incorrect

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#15606]
### Describe the bug
Here is a clear and concise description of what the problem is:

If the backend populates fields such as plot, plot outline, genre, season and episode they will not be displayed, instead these fields from the EPG data will be displayed. This means the lifetime of a timer's data is bound to the EPG data which can be incorrect on backends where this information lives separately to the EPG data.

Loosely related to #15572

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Either use the data in PVR_TIMER first and if not available fall back to EPG data or vice versa.

## Actual Behavior

Once EPG data is expired the fields plot, plot outline, genre, season and episode will not be populated even tough they are supplied in the PVR_TIMER.

### To Reproduce

1. Create a once off timer using pvr.vuplus
2. Wait until 24 hours after it's completed
3. Timer data will no longer be displayed even though it's populated by the backend.

### Debuglog

The debuglog can be found here:

https://gist.github.com/phunkyfish/54f3f6f06ff51b9ff9c8a156bf9f7eb9

### Screenshots 
Here are some links or screenshots to help explain the problem:

Can supply if required.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [x] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: MacOSx, Windows 10, LibreElec Rpi/Intel
 - Kodi version: 18.1/18.2RC

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
> fields such as plot, plot outline, genre, season and episode

PVR_TIMER has none of these fields. Not sure which fields you are referring to.

**Comment by phunkyfish** [comment]
Apologies, there is summary, genreType and genreSubType all which are pulled from EPG (Season and Episode were an assumption as they would make sense there).

It's mainly the summary field that doesn't get used after the EPG entry is no longer in the EPG, at least as far as I can tell.

**Comment by ksooo** [comment]
> there is summary, genreType and genreSubType

 Seems, those are are all completely ignored by Kodi, not just that there is no fallback epg->timer.

 Not sure whether timer.summary is semantically identical to epg.plot (or epg.plotoutline).

**Comment by phunkyfish** [comment]
Ah, falling back to using summary as plot would be useful if it’s possible.

**Comment by phunkyfish** [comment]
Genre not so much.

**Comment by ksooo** [comment]
> Ah, falling back to using summary as plot would be useful if it’s possible.

Again, not sure whether timer.summary is **semantically identical** to epg.plot.

**Comment by phunkyfish** [comment]
I’m not sure how you figure out the answer to that question.

**Comment by ksooo** [comment]
> I’m not sure how you figure out the answer to that question.

 As documentation is not clear on this we would have to check implementation of each and every pvr addon, hoping to find a single pattern that can be documented. Or the other wy round, we define something and "force" the addon maintainers to fix their implementation if it violates the new definition. :-)

**Comment by phunkyfish** [comment]
After some brief checking I found the following:

pvr.hts - Summary as timer description
pvr.vbox - Summary as timer description
pvr.vuplus - Summary as timer description
pvr.nextpvr - Not used (only populated with “summary”)
pvr.mythtv - Summary as timer description
pvr.dvbviewer - Not used
pvr.dvblink - Not used

It will be hard to discern what the content of a timer description is meant
to contain without knowing each PVR backend (or asking the maintainers).
Will look as the others tomorrow but not sure there will be anything
different.

**Comment by phunkyfish** [comment]
And the rest:

pvr.argustv - Not used
pvr.filmon - Summary as summary
pvr.hdhomerun - No timers
pvr.mediaportal.tvserver - Summary as description
pvr.njoy - No timers
pvr.pctv - Not used
pvr.stalker - No timers
pvr.vdr.vnsi - Not used
pvr.wmc - Summary as description 

So in general summary is set to the timer description or not used at all.

**Comment by ksooo** [comment]
There are some  other official pvr-addons, which are not hosted in xbmc/kodi-pvr. Check out xbmc/repo-binary-addons.

**Comment by ksooo** [comment]
For me "timer description" sounds more like unrelated to epg plot. Sounds more like  "This is my lovely timer I use for..." - by means of  any arbitrary string I can put in manually to  remind myself what this timer is good for.

**Comment by phunkyfish** [comment]
That’s fair. Is there any reason you wouldn’t just add plot, plotOutline, season and episode?

**Comment by phunkyfish** [comment]
And leave summary unused as it is now

**Comment by ksooo** [comment]
> Is there any reason you wouldn’t just add plot, plotOutline, season and episode?

 You mean to add those fields to PVR_TIMER?

 Nothing speaks against this besides that somebody needs to find the time to implement that for the Kodi PVR component, inluding the PVR Addon API change and Estuary, and at least for one PVR addon. Definitely doabale, but not on my personal todo list currently.

**Comment by phunkyfish** [comment]
Once more, that's fair.

**Comment by phunkyfish** [comment]
Might try to do it myself. I assume as there is an API change this would be a Kodi 19 thing?

I might end up annoying the hell out of you with questions ;)

**Comment by phunkyfish** [comment]
Having not contributed to kodi proper before could you give me some pointers on the code areas I should be looking at. I assume the skin is separate.

**Comment by ksooo** [comment]
PVR Addon API type definitions: https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_pvr_types.h

pvr component : https://github.com/xbmc/xbmc/tree/master/xbmc/pvr

timer info tag (wrapping PVR_TIMER): https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/timers/PVRTimerInfoTag.h

epg info tag (wrapping EPG_TAG): https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/epg/EpgInfoTag.h

**Comment by phunkyfish** [comment]
Thanks!

**Comment by emveepee** [comment]
In NextPVR the EPG data is deleted from the database daily so any links on old recurring times is lost to Kodi.  However the tag data is maintained and could populate some of the missing data.   Perhaps in V19 we could pass back a populated EPG_TAG rather than requiring Kodi to do the additional lookup.  It might mean some mandatory fields would become optional.

**Comment by phunkyfish** [comment]
In next pvr is this data stored with the timers? On Enigma2 it is so a fallback would be possible.

**Comment by emveepee** [comment]
Yes when a repeating or one time recording is created from the EPG the original data is serialized to xml and stored in the database.  Future timers from repeating rules will also have the serialized EPG data from "found" guide items.

**Comment by phunkyfish** [comment]
Cool, then that’s two PVR’s that would benefit from this feature.

**Comment by ksooo** [comment]
Please keep in mind that I will have an eye that we do not bloat the addon API. 

I'm a fan of uids as "pointers" to additional data ehich can be fetched separately on demand. I do not like to duplicate epg data fields in recordings, for example.

**Comment by phunkyfish** [comment]
Are you ok with the approach for timers as outlined above?

I.e. If an EPG entry is not found, loads the required fields from PVR_TIMER instead. The fields already exist in Recordings. It would simply be to make timers consistent with EPG entry and recordings.

**Comment by phunkyfish** [comment]
I wasn't planning any fetching, the fields could be populated by the addon just like the other fields.

**Comment by emveepee** [comment]
I think a new call  to get the EPG info from a Recording ID on demand would be fine, I would prefer that to the current approach of doing an EPG lookup on demand for those old shows.

**Comment by ksooo** [comment]
INo new API functions of this can be avoided.

**Comment by ksooo** [comment]
Doing an epg lookup call if an EPG tag is needed is fine. Best would be to pass the uid and get back the tag. Currently we  can only  pay time spans. That could be improved. No special handling or even special calls for recordings etc. needed. As the addon created the uid there should be no problem with that.

**Comment by emveepee** [comment]
Behind the scenes that is fine if Kodi passes both recording and epg uids that it is expecting.  On NextPVR this is actually a recording call.

**Comment by ksooo** [comment]
> Behind the scenes that is fine if Kodi passes both recording and epg uids that it is expecting. On NextPVR this is actually a recording call.

 This is not needed, sorry. Nothing is easier on the addon side than to hold a map <epguid, recordinguid>.

**Comment by phunkyfish** [comment]
@ksooo there are two approaches I could take with this.

1) Generate an EpgInfoTag containing the extra information added to the timer. Could either use an EPG_TAG to create this or have a constructor using the TimerInfoTag. In this case the UI would not need to be modified as far as I can tell.

2) Rewire the UI to fallback to the information contained in the TimerInfoTag if it's not contained in the EpgInfoTag.

Which of the above would be your preference or would you take a different approach altogether?

**Comment by phunkyfish** [comment]
I went with approach 1 in the referenced PR

**Comment by phunkyfish** [comment]
What's interesting is pvr.vuplus doesn't store an eventId with the recording. However using the approach in the PR it still finds the recording correctly from the timer, must be using channel, start time and duration to find it behind the scenes. Nice
