### ISSUE TITLE
Start Live TV channel from JSON-RPC --> unexpected behavior

### ISSUE THREAD

**Issue by SylvainCecchetto** [xbmc/xbmc#15618]
### Describe the bug

I want to start a specific TV channel from this JSON-RPC request:
```
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":"1","method":"Player.Open","params":{"item":{"file": "pvr://channels/tv/Toutes les chaînes/pvr.hts_1179414945.pvr"}}}' http://root:libreelec@192.168.1.23:8080/jsonrpc
```

In the past, on Kodi 17 everything worked well. But since Kodi 18 this does not work properly.
At the beginning it was completely broken but since I upgrade LibreElec (see https://github.com/xbmc/xbmc/issues/15611) I can now start my Live TV channel again BUT:

Kodi seems to not correctly understand that the "file" `pvr://channels/tv/Toutes les chaînes/pvr.hts_1179414945.pvr` is not a simple regular file but a real Live TV channel from my TVHeadend PVR.

Then, if I start the channel from the JSON-RPC request, I cannot switch channel from my remote (with the desired channel number or with the P+ and p- button), also if I press "info" I have no EPG infos, also the channel name et logo is not here.

If I want to switch channel I have to go back in the main Kodi menu and start a new channel "by hand".

## Expected Behavior
I would like Kodi to guess that the file `pvr://channels/tv/Toutes les chaînes/pvr.hts_1179414945.pvr` is a Live TV channel and start this TV channel exactly the same way that when I start it from the Live TV menu. (This behavior worked well on Kodi 17)

## Actual Behavior
See bug description.

### To Reproduce

Send this command with a correct channel and try to switch channel from remote.
```
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":"1","method":"Player.Open","params":{"item":{"file": "pvr://channels/tv/Toutes les chaînes/pvr.hts_1179414945.pvr"}}}' http://root:libreelec@192.168.1.23:8080/jsonrpc
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

* Actuel behavior after the JSON request: 
![img_9082](https://user-images.githubusercontent.com/11562279/53398668-7adc6b00-39aa-11e9-8729-7fb14a4f8e77.JPG)
* Expected behavior: 
![img_6443](https://user-images.githubusercontent.com/11562279/53398687-8760c380-39aa-11e9-9de9-fa24b3ebce01.JPG)

 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC-Generic.x86_64-9.1-Milhouse-20190224215456-%230224-gc71997a.tar
 - Kodi version: 18

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by vpeter4** [comment]
Instead of a file you could use _channelid_ parameter with a number. Like `"channelid":14`.

**Comment by SylvainCecchetto** [comment]
Works like a charm, thank you very munch!

**Comment by fatshotty** [comment]
Hi, I read the thread but I didn't understand what is the correct syntax for jsonrcp request to send to my kodi.
where should I add the `channelid` parameter?

thanks in advance

**Comment by vpeter4** [comment]
`curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1,"method":"Player.Open","params":{"item":{"channelid":14}}}' http://localhost:8080/jsonrpc`
