### ISSUE TITLE
Scroll to bottom of panel control using scrollbar wraps focus to first row if no item in focus position.

### ISSUE THREAD

**Issue by jurialmunkey** [xbmc/xbmc#15626]
### Describe the bug
Here is a clear and concise description of what the problem is:

For panel controls, if you scroll to the bottom of the panel control using a scroll bar and there is no item in the focus position column, then focus wraps to the top row.

This is a problem not only because it shows info for an item that is not on screen, but also when you move off the scrollbar the focus is in a position which is off screen.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If there is no item at the focus column position, focus should be on the last item in the panel rather than wrapping around.

## Actual Behavior

The focus wraps around to the top row.

### To Reproduce

1. Use info wall view in Estuary.
2. Find a folder where the number of items leaves a blank space in the bottom right of the panel.
3. Focus the bottom right position of the panel.
4. Move to the scrollbar and the scroll down the panel. 
5. Because there is no item in the very last position of the panel where focus was previously, the focus wraps around to the top row.

### Screenshots 
Here are some links or screenshots to help explain the problem:

In this screenshot you can see that as there is no item in the last row and column, the focus has wrapped around to the top row of the panel and the info is showing for "8 out of 10 cats" rather than "That Mitchell and Webb Look"

![screenshot186](https://user-images.githubusercontent.com/4618719/53451029-e9d0c700-3a71-11e9-85ee-eae228cdb3f9.jpg)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by joseluismarti** [comment]
A fix has proposed, please check if now works as expected.
