### ISSUE TITLE
Integrate with subsync

### ISSUE THREAD

**Issue by StCyr** [xbmc/xbmc#15623]
## Roadmap or todo suggestion
I've recently read about subsync (https://github.com/smacke/subsync) to automaticaly sync subtitles, and thought it could be nice to have it integrated with kodi.

### Context
Sometimes subtitles are not synchronized and manually synchronizing them may be tedious.

That could be a good thing to have something like a checkbox "attempt to automaticaly synchronize subtitle?" when loading a .srt file,

Apparently the automatic sync process takes no more than 30 seconds (down to 1 second possible) to complete.

PS: There's a VLC integration patch available (https://raw.githubusercontent.com/smacke/subsync/master/subsync-vlc.patch)

**Comment by MartijnKaijser** [comment]
Roadmap tickets are for members only to make. Please use the forum for requests
