### ISSUE TITLE
At video end a black screen appears and you don't have any controls any more

### ISSUE THREAD

**Issue by rainman74** [xbmc/xbmc#15637]
### Describe the bug
At video end a black screen appears and you don't have any controls any more.
The problem very often arises after the end of the 2nd or 3rd video/episode that you watch in sequence.
Then you can only force Kodi to quit and restart again.

This is the case since some of the last Nightly builds of the 18.2 version.
Last test was with the build: 18.2-RC1 Git:20190227-0ae0429874

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

You get back to the episodes overview

## Actual Behavior

Black screen appears

### To Reproduce

1. Watch two or three episodes in a row
2. Select the next episode at the end of each episode and start it normally with play

### Debuglog

The debuglog can be found here:
https://paste.ee/p/Z7ZNT

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Sony BRAVIA 4K GB ATV3 with Android 8.0.0
 - Kodi version: 18.2-RC1 Git:20190227-0ae0429874

**Comment by DaVukovic** [comment]
Your log is not a debuglog: 

> 2019-02-28 20:00:23.880 T:9394  NOTICE: Disabled debug logging due to GUI setting. Level 0.

Please enable debug logging and provide a new log

Thanks in advance

**Comment by rainman74** [comment]
This happens occasionally and I don't want to look at the debug messages all the time now and I am now using the 18.1 again because of the error.

**Comment by rainman74** [comment]
fixed in 18.3 RC
