### ISSUE TITLE
Changing the artwork of multipart video files crashes Kodi

### ISSUE THREAD

**Issue by rainman74** [xbmc/xbmc#15638]
### Describe the bug
Kodi crashes when changing the artwork of multipart video files.

## Expected Behavior
No crash

## Actual Behavior
Crash

### To Reproduce
1. Use a multipart video, for example:
"Video part01.mp4"
"Video part02.mp4"
"Video part03.mp4"

2. Changing the poster or fanart leads to an immediate crash.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 8.0 & Windows 10

 - Kodi version: Kodi 18 Final, Kodi 18.1 Final, Kodi 18.2 Nightly

**Comment by DaVukovic** [comment]
Where's your debuglog?

**Comment by rainman74** [comment]
> Where's your debuglog?

https://paste.ee/p/jbcEn

**Comment by rainman74** [comment]
@DaVukovic 
https://paste.ee/p/jbcEn

**Comment by rainman74** [comment]
status?

**Comment by DaVukovic** [comment]
I can comfirm this issue. Kodi crashes directly once you hit "Chose Art" from the movie info 

Crashlog: http://paste.ubuntu.com/p/T2mzgGy5n8/

**Comment by rainman74** [comment]
Thank you!
