### ISSUE TITLE
Music playback stops when screen goes off (Shield) 

### ISSUE THREAD

**Issue by RayBan91** [xbmc/xbmc#15645]
### Describe the bug
Hello,
according to closed issue https://github.com/xbmc/xbmc/issues/15632, I want to report problem. After upgrade Kodi to 18 and now 18.1 version I lost pssibility to lissten my music when screen is off.
In 17.x version I controled music playback using Yatse without turning on scrren, now I need to power on my projector.

Now I'm working on fresh install of Kodi server and adding only few albums free of errors during scan directories.

Please be professional and take this time my issue seriously.

Regards, Rafał.

## Expected Behavior
Music still plays when screen goes off.

## Actual Behavior
Music stops playing after screen goes off.

## Possible Fix
Restore this function or give possibility to choose.

### To Reproduce
1. Start listen music
2. Off the screen

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/girefacedi.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:
https://1drv.ms/v/s!AoWffRc_P_i7g6xZOXGR5N5W93NY0A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
 - Android
 - Nvidia Shield 
 - external USB audio DAC.
 
- Operating system version/name:
 - Kodi version: 18.1

**Comment by KarellenX** [comment]
Really?? I will block your account if you open another issue
