### ISSUE TITLE
Playback stalls when AVR is turned off during playback and ARC falls back to TV speakers

### ISSUE THREAD

**Issue by da-anda** [xbmc/xbmc#15650]
### Describe the bug
Here is a clear and concise description of what the problem is:

On Android, when you run KODI on your AndroidTV based TV and connect the AVR via ARC, video playback stalls/freezes when AVR is turned OFF during playback. On the other hand, turning ON the AVR during playback via TV speakers is working fine - video continues to play and audio switches smoothly to AVR.

Once AVR  is off and video froze, KODI is still responding, so it's just the video thread that seems to be frozen. Best guess is that KODI is waiting on the sink to output the remaining audio packages, but sink can't do so any longer and is in a deadlock. But that's just a guess.
When I stop playback after the issue occured, I can start playback again and video continues to play without sound for a few seconds and then again seems to freeze. This at least happened during the session of which I grabbed the below linked logcat from.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video should continue to play and audio should be played via TV again.

## Actual Behavior

Video playback get's stuck (picture freezes, audio stops).

## Possible Fix

drain the sink and don't wait on it to output remaining packages - but that's just a guess.

### To Reproduce

1. turn on AVR and TV
2. start KODI on an AndroidTV enabled TV, like Sony or Philips
3. play any video
4. turn off AVR and try to continue watching on TV speakers

### Debuglog

The debuglog can be found here:

Peak3D requested a logcat instead of a debug log, which can be found here: https://paste.kodi.tv/iwikidezoj.kodi
Timestamp of KODI startup `2019-03-02 19:00:36.794 T:6920`

Performed actions in this logcat:
- started KODI with AVR turned off
- started video playback
- turned on AVR (everything still fine)
- seeked forward a few secs
- turned AVR OFF (video froze, audio gone)
- tried to recover playback by seeking - no help
- stopped playback
- started playback again, video froze after a few secs, no audio
- grabbed logcat

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Environment:
- Philips AndroidTV with Mediatek chipset
- AVR Denon X2400-H

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.2 nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by iz8mbw** [comment]
Just an info, this don't happenes with Nvidia Shield. Setup is: Shield on HDMI1 of TV, AVR on HDMI2 (ARC) of TV.
If I power off AVR during playback, audio switch to TV speakers and video/audio are smooth.
