### ISSUE TITLE
Scroll EPG when powering on with remote

### ISSUE THREAD

**Issue by svenbieg** [xbmc/xbmc#15656]
No way? Ain't there a signal from HDMI?

**Comment by DaVukovic** [comment]
Please follow our issue template and provide at least a debuglog

I'll mark this as invalid for the time being

Thanks in advance

**Comment by ksooo** [comment]
Do you have a clue what you are doing here? What do you think closing and re-opening the issue is good for?

**Comment by svenbieg** [comment]
The point is powering on Your TV and getting EPG of two days ago. I've found myself two times looking through.


---- Kai Sommerfeld schrieb ----


Do you have a clue what you are doing here? What do you think closing and re-opening the issue is good for?

**Comment by svenbieg** [comment]
I don't think my Rpi3 is streaming video even without a display.

**Comment by svenbieg** [comment]
It ain't a bug, so there is no bug-report. It is more a question, if this ain't possible. Maybe someone in Your team has time for this issue.

**Comment by ksooo** [comment]
If It's no bug report or or feature request, ask your question in the forum, please.

**Comment by svenbieg** [comment]
I'm a hobby-programmer. Maybe You get a Power-Off and Power-On Event. It ain't my problem. Best regards, Sven Bieg.
