### ISSUE TITLE
Video Playback stops on DVD ISO, Subtitles flickering fast

### ISSUE THREAD

**Issue by corsalibra** [xbmc/xbmc#15666]
## Bug report
Subtitles Flickering and Playback stops at Britannia Season 01 Disc 01 ISO
### Describe the bug
Loading DVD Iso-File of "Britannia" Series, Season 01 Disc 01.
Loading Iso File was successful.
Language "German"
Starting playback of DVD over DVD menu.
Starting with Episode 01.

At the Beginning there are some subtitles shown, but these are flickering fast.
At timestamp 01:20 Minute the playback stops and the charging indicator (circle) is shown
with a value of "100". The audio is playing further for some seconds, bt the screeplay stops.Here is a clear and concise description of what the problem is:

Playback is stopping. Other Software Media Player as VLC Player did not stop.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No flickering of Subtitles.
No stopping of Video playback.

## Actual Behavior

Flickering of Subtitles.
Stopping of Video playback, at least at 01:20 Minute

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android  (on FANTEC 4KP6800)
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MartijnKaijser** [comment]
Where's the debuglog that is mandatory?

**Comment by DaVukovic** [comment]
no response anymore. Issue closed
