### ISSUE TITLE
Issue template not available after deleted in github

### ISSUE THREAD

**Issue by radoslavv** [xbmc/xbmc#15668]
Can't reload template in github for issue after unintentionally deleted.
Tried do submit new Issue, but github keeps in cache last edited. So if you delete template, no new is inserted, no way how to get it back.

**Comment by Rechi** [comment]
Nonthing we can do about, it's a GitHub feature or bug.
You can find our issue template at https://github.com/xbmc/xbmc/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by radoslavv** [comment]
Understand.
At least I was able to create new ticket after this one :-) and new Issue ticket had a template.
That would be perfect to have at least some reset Issue template button. Otherwise I have to create dummy issue and close it...
