### ISSUE TITLE
BD Menu High CPU Usage 

### ISSUE THREAD

**Issue by AMKnock** [xbmc/xbmc#15660]
### Describe the bug
Here is a clear and concise description of what the problem is:

So far, every Blu-Ray disc I tried out on Leia plays well (including one 4k UHD disc) , but there is a problem when it reaches the BD menu screen. That's when CPU usage jumps up to 100% and navigating the menu gets extremely slow. Then when I manage to start the movie, everything is fine again and CPU usage goes back to normal.
So far I've tried every official version of Kodi Leia available, including some nightlies, but the problem is still there.

My Android Box is A95X Pro operating on Android 7.1.2.

Interestingly, back on Kodi Jarvis on BD Menu screen CPU usage is nowhere near 100%, but unfortunately the problem there is that once you press okay on something in the menu you have to wait about 10 seconds before it registers the command plus it has some other bugs.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

So far I've tried messing with the options, enabling/disabling Media Codec and Media Codec (Surface), but the situation is still the same.

### To Reproduce

1. Play any BD or UHD Disc
2. Observe CPU Usage (Especially when it reaches the BD Menu)
3.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/osovovicig.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 7.1.2
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Please provide a debug log which captures the issue.

**Comment by AMKnock** [comment]
https://paste.kodi.tv/osovovicig.kodi

**Comment by AMKnock** [comment]
Okay, I pinpointed the issue with BD Menus.

For some reason it doesn't use HW acceleration.

Pressing codec info in the BD menu I get: 
Hardware Decoding: Inactive
Decoder: ff-h264, yuv420p

Everything besides this menu says:
Hardware Decoding: Active
Decoder: amc-h264(s), Surface

Any chance of a fix?
