### ISSUE TITLE
PVR Timer States - Aborted, Cancelled and Disabled all show as "Disabled" in Timer UI

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#15679]
### Describe the bug
Here is a clear and concise description of what the problem is:

Whether a timer is read from the backend it's not possible to distinguish the Aborted, Cancelled and Disabled states base on the timer UI screen list view. All will display as Disabled.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When a timer is read from the backend display the text "Disabled" if it's deactivated and "Cancelled" is it cancelled or aborted (assume cancelled and aborted mean the same thing).

## Actual Behavior

Disabled is shown for all 3 states.

## Possible Fix

https://github.com/xbmc/xbmc/blob/4de59727e6c8e986f17e539ff62e0e7191f8ac11/xbmc/pvr/timers/PVRTimerInfoTag.cpp#L371-L382

For CANCELLED and ABORTED simply use the text "Cancelled" instead of disabled.

### To Reproduce

1. Load timers with a cancelled or aborted state from a PVR backend
2. Load PVR Timer UI
3. See that state is always displayed as "Disabled" and that deactivate is selectable in the context menu.

### Debuglog

The debuglog can be found here:

https://gist.github.com/phunkyfish/fe15e102bcc7b7c4dc49942abdb8e0a3

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSX, Windows, LibreElec 9 Intel/Rpi
 - Kodi version: 18.2RC

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Whether we fix this depends on the outcome of the discussion we have in #15682 (Does it make sense to show aborted/cancelled timers in Kodi UI?)

**Comment by phunkyfish** [comment]
Closing as not relevant after fix for #15682
