### ISSUE TITLE
Video cache settings are ignored on Kodi 18.1

### ISSUE THREAD

**Issue by gorman42** [xbmc/xbmc#15676]
### Describe the bug
Here is a clear and concise description of what the problem is:

Adding cache settings in advancedsettings.xml appears to have no effect.
I've tried these settings (Windows x64, Kodi x64, on a 32GB RAM machine) and Kodi RAM usage remains at about 300MB.

```
<advancedsettings>
  <cache>
    <buffermode>1</buffermode>
    <memorysize>8289999999</memorysize>
    <readfactor>9999999999</readfactor>
  </cache>
</advancedsettings>
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would expect RAM usage to increase, proving that video is actually cached in RAM. This is not the case.

## Actual Behavior

RAM usage is stuck at a "standard" level no matter what cache settings are being used in advancedsettings.xml

### To Reproduce

1. Check Kodi memory usage while playing a sizable video files (say at least a 10GB one).
2. Change advancedsettings.xml in order to have Kodi use more RAM to cache more of the video file.
3. Check Kodi memory usage again and see that basically nothing has changed.

### Debuglog

The debuglog for a bluray remux playback  can be found here: https://paste.kodi.tv/kuwonodefo.kodi
Kodi RAM usage remained around 300MB even though the file itself is over 30GB, giving plenty to cache, considering the settings.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Windows x64 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by popcornmix** [comment]
memorysize is a 32-but integer so cannot exceed 0xffffffff (4294967295)

**Comment by gorman42** [comment]
I'm sorry, I previously checked with different values and I was experimenting.
Just used:```

<advancedsettings>
  <cache>
    <buffermode>1</buffermode>
    <memorysize>4294967290</memorysize>
    <readfactor>9999999999</readfactor>
  </cache>
</advancedsettings>
```
And nothing changes anyway. Kodi uses about 300MB of RAM and that's it.

**Comment by popcornmix** [comment]
Does halving that number make a difference? It's possible it's treated as signed at some point.

**Comment by gorman42** [comment]
Tried with this. No change.

`<advancedsettings>
  <cache>
    <buffermode>1</buffermode>
    <memorysize>2147483645<memorysize>
    <readfactor>9999999999</readfactor>
  </cache>
</advancedsettings>`

**Comment by gorman42** [comment]
I remember using this set of settings some versions of Kodi ago and they actually worked. Something must have happened. Unfortunately it's been a while since I last used them, so I wouldn't be able to pinpoint when this changed.

**Comment by gorman42** [comment]
I suggest this gets reopened.

**Comment by arnova** [comment]
Also note it won't exceed the currently playing file's filesize. Furthermore your readfactor probably also won't work.

**Comment by gorman42** [comment]
Filesize (this being a remux) is 34.5 GB.
With this:

`<advancedsettings>
  <cache>
    <buffermode>1</buffermode>
    <memorysize>2147483645<memorysize>
    <readfactor>20<readfactor>
  </cache>
</advancedsettings>`

Kodi RAM usage is still hovering around 300MB. If there's a skin that actually displays the cache size (like the old playback stats did), please advise.
There's another report about this in the forum: https://forum.kodi.tv/showthread.php?tid=310497&pid=2804446#pid2804446

**Comment by arnova** [comment]
Where in the wiki does it say 9999999999 ? I can hardly imagine someone wrote that nonsense there.

**Comment by gorman42** [comment]
https://kodi.wiki/view/HOW-TO:Modify_the_video_cache#Example_5

But again, I've tried with all sort of readfactor and memorysize values. RAM usage stays completely stable, no matter what the values there.

**Comment by arnova** [comment]
@gorman42 : Please check the actual "forward" value in VideoPlayer's codec debug info screen (CTRL-SHIFT-o shortcut). Does it increase or does it stall at some value?

**Comment by zehnerGIT** [comment]
> Filesize (this being a remux) is 34.5 GB.
> With this:
> 
> ```
> <advancedsettings>
>   <cache>
>     <buffermode>1</buffermode>
>     <memorysize>2147483645<memorysize>
>     <readfactor>20<readfactor>
>   </cache>
> </advancedsettings>
> ```
> Kodi RAM usage is still hovering around 300MB. If there's a skin that actually displays the cache size (like the old playback stats did), please advise.
> There's another report about this in the forum: https://forum.kodi.tv/showthread.php?tid=310497&pid=2804446#pid2804446
> 
> PS
> Readfactor at 9999999999 was taken straight from an example in the Wiki.

Be careful, not all playback methods can cache. 
It's not implemented in some PVR clients and inputstream addons (Netflix, Amazon, ...). Kodi uses only a small default cache if it's not implemented, so at least a few of the many buffer topics in Leia should be because of this.
But your bluray playback should work (with unprotected content). I use LibreELEC 9.0.1 and can see, that the cache progressbar increases. With cache I've nearly no stalls while watching movies from my nas (with increasing progressbar), but Netflix and Amazon are unwatchable (progressbar stalls), because I have one of those Celeron boards with kernel 4.19 problems. At least with linux, cache seems to work if it's implemented

**Comment by gorman42** [comment]
> 
> 
> @gorman42 : Please check the actual "forward" value in VideoPlayer's codec debug info screen (CTRL-SHIFT-o shortcut). Does it increase or does it stall at some value?

This is what I get:

![image](https://user-images.githubusercontent.com/38404727/53956672-8df2e780-40dc-11e9-8dd5-078970028629.png)

While using these settings:

````
<advancedsettings>
  <cache>
    <buffermode>1</buffermode>
    <memorysize>139460608</memorysize>
    <readfactor>20</readfactor>
  </cache>
</advancedsettings>
```

I'm playing back from a local resource but buffermode setting should have the settings apply to it. No PVR or inputstream addons to answer @zehnerGIT

**Comment by arnova** [comment]
@gorman42 : And the "forward:" value flatlines at ~ 50 MB (is in your picture) or does it increase when you keep playing?

**Comment by gorman42** [comment]
It flatlines, as mentioned. That's what I meant with "the value remains identical throughout playback", sorry for not being clearer.

**Comment by arnova** [comment]
Just tested it here and it looks like, as I already suspected, the insane value for readfactor you're using seems the culprit. Try lowering it to something like 1000, which should still be more than enough.

**Comment by arnova** [comment]
Btw. I've also "fixed" it in our wiki.

**Comment by gorman42** [comment]
I'm sorry, arnova, but I posted above my latest settings. Readfactor is at 20 in the above example.

**Comment by arnova** [comment]
> I'm sorry, arnova, but I posted above my latest settings. Readfactor is at 20 in the above example.

Strange, I've tested this on both Windows and Linux with your settings and the only thing that caused problems was the readfactor, after changing that it worked fine. Please post a new debug log with your "latest" settings, since for now I'm out of ideas.

**Comment by gorman42** [comment]
Hi @arnova, here's a log with the above settings. RAM usage always hovering around the 250-300MB figures and CTRL+SHIFT O reporting 50MB of cache.

https://paste.kodi.tv/yefubavibe.kodi

**Comment by arnova** [comment]
What happens if you play a (much) smaller file?

**Comment by gorman42** [comment]
With a 1.76GB AVI file, Kodi reports "forward:61.78MB" with CTRL+SHIFT O. After a short while it goes back to 49.88MB and remains like that. Tried this with different files of different sizes.
Same settings as the last posted for buffermode, memorysize and readfactor.

**Comment by arnova** [comment]
Well if you've used  <memorysize>139460608</memorysize> then that's about right. For MKV/AVI/MP4 it always uses double buffering, furthermore there's some "backward" cache so the actual forward cache is ~50MB. The fact that it initially *may* increase above this value is because at start we have no backward cache yet, so while filling everything is considered "forward" cache. Depending on how fast it fills and how fast your video progresses forward, forward cache size will decrease and is added to the backward cache. If you double this value (278921216) it gives me about 100MB of forward cache and I think the same thing should happen for you too. Again: I can't find anything wrong with it.

**Comment by gorman42** [comment]
Ok. Two things about this. First of all: my bad. I didn't realize that the number I ended up using was an order of magnitude smaller than the one I was using before.

Second thing is: ok, now I have set up a bigger number and SHIFT+CTRL O reports "forward" in the 700-900 MB range. But RAM usage keeps hovering around 350MB in Windows Task Manager. So I'm not sure where the 768MB of cache I'm seeing now reported are coming from. Are they real?

Also, is there anything that could be done to allow for higher values of cache? 8/16GB machines are not so rare now (at least in Windows x64 environment).

Thanks for the help and sorry for the mishap. I was misled by the "hyper" readfactor value in the wiki and then I misread the new value I input for memsize (always change ONE thing at a time, I know...).

But RAM usage still tells a different story from the one Kodi is internally telling.

Edit: if I go to the Performance tab of Task Manager, under RAM, I see that RAM usage indeed raises by 1GB when playback starts, according to the "forward" value rasing till it hits the 1GB limit.

Sooo... well, probably it's just due to the way this "cache" is handled internally, that doesn't register as "Kodi" RAM usage, for some reason.
Still it would be nice to be able to exceed 1GB effective cache, if one has the machine to do it. But it's more of a feature request, probably, to go along with the fact that Windows now has an x64 build.
At least it led to the Wiki being corrected, so others won't be misled as how I was by that example.
Maybe it would be good to clearly list the limits for the different values.

**Comment by arnova** [comment]
I don't know anything about Windows's memory management but the "forward" value I mentioned is the actual memory value used by our file cache, so that's the one to look at. Furthermore really don't see the point of having huge caches: you're either streaming from the internet with a little help from the cache to buffer glitches or you're playing something locally. Being able to cache huge files as soon as possible simply isn't something that improves user experience that much, so I don't see this happen in the (near) future.
