### ISSUE TITLE
MAC discovery Failed message when enabling Wake on LAN in power settings

### ISSUE THREAD

**Issue by erkr** [xbmc/xbmc#15674]
### Describe the bug
Here is a clear and concise description of what the problem is:

When enabling "Try to wake remote servers on access" under system->power saving I get an error for every server: "MAC discovery Failed for 192.168.xx.xxx" using Kodi 18.1 Leia.
Kodi should resolve the MAC adress of the servers IP/hostnames and create a WakeOnLan.xml file. 
On Windows this works fine!
On both Android TV ( 7 nougat) and my Xbox one, this fails. I get the MAC discovery errors in stead (with the right IP addresses, so it is not host name related). No xml file is created,
After I manually copied the XML file from my  Windows PC to the TV and XBOX, both work and wake the servers when accessing the shares,
So the OS call used to retrieve the MAC address doen't seem to work on Android TV and XBOX

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should resolve the MAC adress of the servers IP/hostnames and create a WakeOnLan.xml file. 
On Windows this works fine!

## Actual Behavior

When enabling "Try to wake remote servers on access" under system->power saving I get an error for every server: "MAC discovery Failed for 192.168.xx.xxx"

## Possible Fix

Maybe retrieving the MAC addresses programmatically on these devices is simple not possible?!
BUT in that case this could be fixed by adding the option to enter the server MAC addresses manually in the system->power saving menu 

### To Reproduce

1. enable "Try to wake remote servers on access" under system->power saving
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [X ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.1 Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by bennyk** [comment]
Hi Erkr,
could you elaborate how you might solve this error in your Windows?
"copied the XML file from my Windows PC"

For unknown reason I find "MAC discovery Failed" with similar error.

Thanks

**Comment by erkr** [comment]
I have that issue on android only. Only fix is to hard code the IPs in the Wake XML.
The error will still occur but it works

**Comment by erkr** [comment]
Sorry 
Hard code the MAC addresses for the IPs

**Comment by wsnipex** [comment]
those are OS limitations. Kodi is not allowed to access ARP tables

**Comment by bennyk** [comment]
Is this alright way to fix my hard code? This is how I tried my wakeonlan.xml.

wakeonlan.xml:
<onaccesswakeup>
   <netinittimeout>60</netinittimeout>
   <netsettletime>500</netsettletime>
   <wakeup>
       <host>10.0.1.99</host>
       <mac>74:d4:35:e9:c0:58</mac>
       <pingport>0</pingport>
       <pingmode>1</pingmode>
       <timeout>600</timeout>
       <waitonline>38</waitonline>
       <waitonline2>40</waitonline2>
       <waitservices>0</waitservices>
   </wakeup>
</onaccesswakeup>             

Settings/System->Power Saving->Try to wakeup remote servers on access:
Mac discovery Failed for XXX

Thanks in much.

**Comment by erkr** [comment]
Hi Benny

I solved it using by an autoexec.py file that is automaticallyt executed
every time KODI starts up (you can't get rid of the dicovery error on
android with the build in Wake On LAN option).
Additional advantage is that you can easily wake as many devices you like.
Just add one line per device.
Script example for 2 devices:
import xbmc
xbmc.executebuiltin('WakeOnLan(EC:43:F6:AA:AA:BB)')
xbmc.executebuiltin('WakeOnLan(10:7B:EF:FA:AA:BB)')

Just replace the MAC adresses with yours. This will not give error messages
and works fine on all KODI targets.
Success
Eric

**Comment by bennyk** [comment]
Hi Eric,

I tried it with below still getting with the red cross letter on Kodi. Do you might know anything to try this out?

userdata/autoexec.py:

```
import xbmc
xbmc.executebuiltin('WakeOnLan(74:d4:35:e9:c0:58)')
xbmc.executebuiltin('WakeOnLan(88:6b:6e:49:c8:dd)')
```

Settings/System->Power Saving->Try to wakeup remote servers on access:
Mac discovery Failed for XXX

Thanks very much.
Benny.

**Comment by erkr** [comment]
Hi benny
When you use the autoexec.py script (same directory as the wakeonlan.xml), you just have to disable the system power save option! It fully replaces the Wake on lan script and uses the same build in command.
Also make sure to save the file in plain ascii format.
Regards
Eric

**Comment by bennyk** [comment]
Hi Eric,
I mean invoking XBMC like regular in Android box given that I added autoexec.py?

Or should I be able to do something like “python autoexec.py”? I am still very newbie in Android.

My bad for adding you it very much.

**Comment by erkr** [comment]
Hi Benny
I don't know why you want to run the autoexec.py in plain python. I don't believe it is even possible as the script invokes the xmbc build in method for sale on Lan. So the script has to run in the python interpreter from kodi! Kodi automatically runs it at startup.

BUT I understand your still get the MAC discovery error, right? If so That means you simply forgot to disable the Wake on lan option in the system-menu. This py script will simply not give this error!! I have tested the autoexec.py on windows, android tv and Xbox one. It works on all platforms

**Comment by bennyk** [comment]
Hi Eric,
I was finally solved it simply by removing and re-installing the XBMC app. The default settings appear to be solved alright perhaps I might messed up with XBMC settings.

Thank you kindly by your kind assistance. +2

**Comment by erkr** [comment]
You're welcome, thnx for the follow up
