### ISSUE TITLE
Favorite link won't play, freezing in video addon.

### ISSUE THREAD

**Issue by vphuc81** [xbmc/xbmc#15673]
### Describe the bug
Here is a clear and concise description of what the problem is:
When play a link in a addon, that link from another addon, it is freezing. It was working fine with Kodi 17.6.
Example: Get a live tv link in a addon plugin.video.allinone to plugin.program.super.favourites.
Then open addon super favourites, and play that link, then it is freezing.
Some shortcut links are working fine, some are freezing.
Hope you understand what I wrote.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix

If I can get this one fix, it should be great link version 17.6. 
Thank you so much for reading.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 7, 10, Android 5, 6
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
we don't provide help for addons that provide illegal/pirated streams.
