### ISSUE TITLE
Incorrect signal handling will deadlock

### ISSUE THREAD

**Issue by jdebp** [xbmc/xbmc#15677]
The [signal handling in `xbmc/main.cpp`](https://github.com/xbmc/xbmc/blob/0978b1dfa3923726841a04b11202eff44552d644/xbmc/platform/posix/main.cpp#L56) is incorrect.  You rightly try to avoid a non-async-signal-safe function call that will cause a deadlock, and employ an alternative mechanism that &hellip; calls _two_ non-async-signal-safe things, heap allocation and the thread API, that can cause deadlocks.

There are three ways to do this sort of stuff right:
* Assign to a `volatile sig_atomic_t` flag in the handler, and have the main event loop of the program, whatever that is, test and reset it, generating an appropriate internal event if it found it set.
* Use `kevent()` to obtain an event for the signal synchronously.
* Use a signalfd.

This issue comes to you because a user noticed that Kodi "seems to do nothing" when it receives an interrupt signal from the terminal, and [posted to StackExchange](https://unix.stackexchange.com/questions/504560/).

**Comment by pkerling** [comment]
Thanks for the input and you are right, this is surely something we can improve - but you do know that this is unrelated to and will not improve the shutdown (i.e. signal handling) time, right? :-)
