### ISSUE TITLE
PVR Timers - Deactivate context menu available in Cancelled and Aborted states

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#15682]
### Describe the bug
Here is a clear and concise description of what the problem is:

If a timer is cancelled or aborted it's still possible to deactivate it.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If the state is cancelled or aborted it should not be possible to Deactivate the timer. (Assumes cancelled and aborted mean the same thing).

## Actual Behavior

If timer is in state cancelled or aborted deactivate is selectable in context menu.

## Possible Fix

Grey out the deactivate button in the context menu if the state is cancelled or aborted.

### To Reproduce

1. Load timers with a cancelled or aborted state from a PVR backend
2. Load PVR Timer UI
3. See that deactivate is selectable in the context menu.

### Debuglog

The debuglog can be found here:

https://gist.github.com/phunkyfish/fe15e102bcc7b7c4dc49942abdb8e0a3

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSX, Windows, LibreElec 9 Intel/Rpi
 - Kodi version: 18.2RC

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
> If timer is in state cancelled or aborted deactivate is selectable in context menu.

 What is the ratio for displaying aborted or cancelled in Kodi UI? Does this make sense? What can I do with cancelled/aborted timers? How long will I see those? pvr.hts for example never transfers cancelled/aborted timers to Kodi.

**Comment by phunkyfish** [comment]
I discovered this when fixing a bug around disabling timers.

I agree with you. I don’t think the states Cancelled and Aborted serve any purpose and they are confusing from an API perspective. I’ve completely removed them from pvr.vuplus.

Might be better to just remove them completely or force those states to Disabled explicitly so behaviour is clear.

**Comment by phunkyfish** [comment]
Dug a little further but found a use case. 

A timer can have a cancelled state on Enigma2 devices. The user can’t initiate that state but it’s possible due to tuner not available and various other reasons.

If the addon suppresses cancelled timers then the user does not know when the timer did not work without going to the backend. Disabled is not appropriate here as a disabled timer can be enabled but a cancelled one cannot.

I don’t think we need both states, a state which represents the fact this timer could not be run would be good though.

**Comment by ksooo** [comment]
I thought we have `PVR_TIMER_STATE_ERROR` ("the timer is scheduled, but can't be recorded for some reason") for the use case you described. Or is this different?

**Comment by phunkyfish** [comment]
Ah, let me check that out.

**Comment by phunkyfish** [comment]
Ok cool, there is that state that works as expected and displays "Error".
However you can still deactivate a timer in an error state which doesn't
make a whole lot of sense as a timer can only have a single state in Kodi
PVR.

So if a timer is in a the state PVR_TIMER_STATE_ERROR it would make sense
to remove/disable the Activate/Deactivate in the context menu.

**Comment by ksooo** [comment]
> So if a timer is in a the state PVR_TIMER_STATE_ERROR it would make sense to remove/disable the Activate/Deactivate in the context menu.

 I agree. => https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/PVRContextMenus.cpp#L363 ;-)

**Comment by ksooo** [comment]
+ https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/timers/PVRTimerInfoTag.h#L130

**Comment by ksooo** [comment]
This is easy and a good candidate for your first xbmc contribution... ;-)

**Comment by phunkyfish** [comment]
Haha, I had a feeling this is what you were going to suggest!

**Comment by phunkyfish** [comment]
So as simple as:

return timerType && timerType->SupportsEnableDisable() && !
timer->IsBroken();

Will create PR shortly.

**Comment by ksooo** [comment]
Can be done a bit more clever... First check isbroken and only if it is not obtain timertype and check it.

**Comment by phunkyfish** [comment]
Gotcha

**Comment by phunkyfish** [comment]
https://github.com/xbmc/xbmc/pull/15689

**Comment by phunkyfish** [comment]
I think I need to do something similar on the skin as if you view the timer from the menu it still shows and enabled toggle.

**Comment by ksooo** [comment]
you mean in the timer settings dialog?

**Comment by ksooo** [comment]
Please prefix the PR title with [PVR], btw.

**Comment by phunkyfish** [comment]
Correct, the timer setting dialog.

**Comment by phunkyfish** [comment]
I'm getting closer: CGUIDialogPVRTimerSettings

**Comment by ksooo** [comment]
Yep. => https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/dialogs/GUIDialogPVRTimerSettings.cpp#L98 is the line to change...

**Comment by ksooo** [comment]
plus / or this one => https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/dialogs/GUIDialogPVRTimerSettings.cpp#L1128

It's been a long time since I implemented this. ;-)

**Comment by phunkyfish** [comment]
I think this is just the value of the toggle not it's visibility: https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/dialogs/GUIDialogPVRTimerSettings.cpp#L98

**Comment by ksooo** [comment]
! https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/dialogs/GUIDialogPVRTimerSettings.cpp#L1128 !

**Comment by phunkyfish** [comment]
Yup

**Comment by phunkyfish** [comment]
Sweet, but the plot thickens...

**Comment by phunkyfish** [comment]
If a timer is in error state it still shows on the main PVR screen as an upcoming recording but the card is pretty much blank.

**Comment by phunkyfish** [comment]
Leave me dig on this one

**Comment by phunkyfish** [comment]
Ok, I think it looks good now, omitted error timers from active timers list and recording active timer. Did I miss anything?
