### ISSUE TITLE
pvr.iptvsimple - Switch button in the EPG will open the program in the background

### ISSUE THREAD

**Issue by Sopor** [xbmc/xbmc#15681]
### Describe the bug
Here is a clear and concise description of what the problem is:

When i select a program in the EPG and use the `Switch` button it seems that the program starts but in the background. I will then need to go to the left menu and press `Full screen`.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When i do the same in Kodi 17.6 it will open the program in full screen.

## Actual Behavior

The program (channel) will start in the background.

### To Reproduce

1. Open TV / Guide
2. Select a program in the EPG
3. Press the Switch button

### Debuglog

The debuglog can be found here:
If you really need a debuglog let me know because it will contain sensible information i need to remove first.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 8.1
 - Kodi version: 18.1 and 18.2 RC1 x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
User error and not related to pvr.iptvsimple.

Settings => PVR & Live TV => Playback => "Switch to fullscreen" => On

**Comment by Sopor** [comment]
This isn't the same settings. If i enable `Switch to fullscreen` it will switch to fullscreen even when i select from the program list. In 17.6 i have `Start playback minimised` and it will still work from the EPG.

**Comment by ksooo** [comment]
Sorry, I do not understand what you mean. Could you make a short video showing the issue?

**Comment by Sopor** [comment]
In Kodi 18 the `Start playback minimised` is replaced with `Switch to full screen` and if i have this enabled it will be full screen from the program list and also if i use the `Switch` button in the EPG. If i disable `Switch to full screen` both ways to start a program will now open the screen minimised (background).

You have changed the name of the option but you have also changed the behavior because it will now affect both ways to bring up a program. In Kodi 17.6 the `Start playback minimised` was only affecting if i open a program from the program list. The EPG was unaffected of the option `Start playback minimised`.

I don't know if you have made it like this by design or it was something you didn't thought about when you changed the option from `Start playback minimised` to `Switch to full screen` but i see no reason to have a `Switch` button that open the video in the background (minimised).

It is also much easier to switch from minimised to full screen when i'm in the program list. I only press the program list twice on the same channel and it will switch to full screen.

If i want to go to full screen from the EPG i have to use the `Switch` button twice or go to the upper right corner (almost) and press there, but maybe there was a reason for changing both the program list and the EPG to follow the option `Switch to full screen`?
I know there are many other ways to switch to full screen but it depends on if you are using a mouse, keyboard, remote or a combination of them all. It also has to do with what skin you are using. I understand you optimise it for the Estuary skin, but i believe Confluence is also very popular?

So what i mean is, the `Start playback minimised` did not change how the `Switch` button worked in Kodi 17.6, but it do in Kodi 18.x (`Switch to full screen`).
I would like to have the old behavior back, were this option only affected the program list and not the EPG.
