### ISSUE TITLE
some DVD not played by 18.0 and 18.1

### ISSUE THREAD

**Issue by stefano70** [xbmc/xbmc#15693]
### Describe the bug
In Kodi 18.1 Leia some DVD with the classic video_ts\ifo\vob structure are not played

## Expected Behavior
DVD played as they were played with Kodi 17

## Actual Behavior
DVD are not played

### To Reproduce

1. starting from a fresh install, add a HTTP or SMB source and import DVD media
2. hit play on a poster or play in other ways
3. media are not played

### Debuglog
https://paste.kodi.tv/awolovupay

the movie name is Bee Movie (Bee%20Movie)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.0 and 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
I cannot replicate this issue on Windows... https://paste.kodi.tv/xavilapuhe.kodi

I suggest it is a problem with the video file. Can you play the dvd in another player?

**Comment by stefano70** [comment]
Yes. It is correctly played in every other appliance media player (Western Digital TV, Sony smart TV, etc.) and/or SW pleayer (Microsoft Windoes media player, VLC, etc.).
It is also correctly played in Kodi 17.x
Not played on Kodi 18.0 or 18.1
