### ISSUE TITLE
all DVD not played hitting the .IFO file

### ISSUE THREAD

**Issue by stefano70** [xbmc/xbmc#15694]
### Describe the bug
using a SAMBA source or local file source, it is always possible to play a DVD by hitting its .ifo file, but using a HTTP source it does not work

## Expected Behavior
To have Kodi play DVD by hitting its .ifo even with HTTP sources

## Actual Behavior
DVDs are not payed

### To Reproduce

1. starting froma clean Kodi install, add an HTTP source and do not import media (directory contains: NONE)
2. browse the source's file, navigate to any DVD\Video_TS folder
3. hit the .ifo

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/xomurifejo

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.0 and 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by stefano70** [comment]
is there someone looking into this issue?

**Comment by stefano70** [comment]
This problem continues to apply also to the 18.2 version of Kodi
https://paste.kodi.tv/xalubehusu.kodi

Is there someone looking into that?

**Comment by pkerling** [comment]
You will see it in this issue if someone starts working on it.

**Comment by arnova** [comment]
The problem is how emu_msvcrt dll_stat() & dll_stat64() (don't) handle http/https. Will look into it.
