### ISSUE TITLE
[Music] Choose Art - does not list all available images

### ISSUE THREAD

**Issue by ronie** [xbmc/xbmc#15699]
### Describe the bug
Here is a clear and concise description of what the problem is:

Artist Info > Choose Art > Thumbnail
- only 1 thumbnail is shown, even though multiple thumbnails are stored in the database

Artist Info > Choose Art > Fanart
- only 1 fanart image is shown, even though multiple fanart images are stored in the database

## Expected Behavior

All available images (current + remote) should be listed for the selected art type.

## Actual Behavior

Only the currently selected thumbnail and/or fanart image is listed.

### To Reproduce

1. Find an artist in the music.db that has multiple thumbnails / fanart images
2. Navigate to this artist in the Kodi Music Library
3. Artist Info > Choose Art > Thumbnail

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/yucuyayata.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

**_thumbnail:_**
![screenshot000](https://user-images.githubusercontent.com/687265/53993007-75abb880-412e-11e9-8166-bef4b29e793f.png)

**_fanart:_**
![screenshot001](https://user-images.githubusercontent.com/687265/53993039-8fe59680-412e-11e9-9e4e-0e58a058ebb9.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

For Albums, it is working ok:

![screenshot002](https://user-images.githubusercontent.com/687265/53993727-7a716c00-4130-11e9-8e3a-86c38b5c7141.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi (18.2-RC1 Git:20190307-7efb8a64d1). Platform: Linux x86 64-bit
Using Release Kodi x64 build
Kodi compiled 2019-03-07

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaveTBlake** [comment]
Thanks @ronie, a gremlim crept in with https://github.com/xbmc/xbmc/pull/15277
Fix on the way

**Comment by DaveTBlake** [comment]
Fixed by #15701
