### ISSUE TITLE
PVR Timers and multiple PVR addons

### ISSUE THREAD

**Issue by emveepee** [xbmc/xbmc#15709]
### Describe the bug
Kodi v18 supports multiple PVR addons but when I try to add a timer Kodi crashes.

I have installed pvr.nextpvr and pvr.iptvsimple  things look reasonable for playback but when I try and add a timer Kodi crashes

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should open the Add timer dialog 

## Actual Behavior

Memory fault

## Possible Fix

When the timer is created
 bool CPVRGUIActions::AddTimer(bool bRadio) const
  {
    const CPVRTimerInfoTagPtr newTimer(new CPVRTimerInfoTag(bRadio));

Kodi is getting the clientid of the first addon

  m_iClientId(CServiceBroker::GetPVRManager().Clients()->GetFirstCreatedClientID()),  m_iClientId(CServiceBroker::GetPVRManager().Clients()->GetFirstCreatedClientID()),

pvr.iptvsimple which does't support timers

In 

void CGUIDialogPVRTimerSettings::SetTimer(const CPVRTimerInfoTagPtr &timer)

  if (m_bIsNewTimer && m_timerInfoTag->m_strDirectory.empty() && m_timerType->SupportsRecordingFolders())

crashes because m_timerType is not defined.  

I can fake it and ignore the first client but if there are multiple clients that support timers I am not sure if the dialog would be populated appropriately.

### To Reproduce

1.  install a pvr addon that supports timer
2.  install pvr.iptvsimple 
3. try and add a timer

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.2 rc

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
As the crash occurs because iptvsimple does not offer any timers by itself, it will be fixed once #15467 is merged as then every pvr addon will always support at least reminder timers (for which the addon has nothing to implement).

**Comment by emveepee** [comment]
> 
> 
> As the crash occurs because iptvsimple does not offer any timers by itself, it will be fixed once #15467 is merged as then every pvr addon will always support at least reminder timers (for which the addon has nothing to implement).

Originally I thought you could simply ignore clients without timers, but figured there still be an issue if there is a difference in the recording directories that populate the timer picklist.

**Comment by fuzzard** [comment]
@emveepee Are you able to provide any feedback on if this is solved in master since https://github.com/xbmc/xbmc/pull/15467 was merged?

**Comment by emveepee** [comment]
> 
> @emveepee Are you able to provide any feedback on if this is solved in master since #15467 was merged?

It is solved in master as @ksooo  referenced (using pvr.demo and pvr.iptvsimple and pvr.nextpvr) 

It still crashes in Leia with pvr.iptvpvrsimple  and pvr.nextpvr  but no fix was mentionned

**Comment by fuzzard** [comment]
Cool, @ksooo says in that thread no intention to backport due to the amount of code changes.
Not sure if he could partial backport the fix or not.
Ksooo, did you just want to confirm no backport (partial or otherwise) and if so I'll close this off.

**Comment by phunkyfish** [comment]
No, it won't be possible to partial back port this even partially. It would mean bringing over way too much supporting code.
