### ISSUE TITLE
Video-Audio signal lost during playback

### ISSUE THREAD

**Issue by mancio61** [xbmc/xbmc#15717]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a Wetek Play2 connected through HDMI to a Marantz NR1607 AVR and then to a 4K Sony TV
During playback, every 5-6 minutes the audio/video signal is lost for 3-4 secs and (black screen).
It happens with all the movies, and did'n happened with LibreELEC 8.2.5 (Krypton based)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The video shouldn't be interrupted

## Actual Behavior

some seconds (3-4) of lost audio/video signal in the Play2->AVR->TV chain

## Possible Fix

unknown

### To Reproduce

Issue is present with every movie played since from the update to LibreELEC 9.0

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/omukagijeq

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux (LibreELEC)
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.1 RC1 ( LibreELEC 9.0.1)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Have you requested assistance on the forum, first?. If yes, link your thread here.

You have not enabled debug mode.
