### ISSUE TITLE
PVR Radio timer rules for any channel appear in TV Timer Rules

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#15710]
### Describe the bug
Here is a clear and concise description of what the problem is:

PVR Radio timer rules created for any channel appear in TV Timer Rules instead of Radio.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

PVR Radio timer rules created for any channel appear in Radio Timer Rules.

## Actual Behavior

PVR Radio timer rules created for any channel appear in TV Timer Rules instead of Radio.

## Possible Fix

I assume this is because timers require a similar channel type field to recordings. This could even be defaulted to the correct type in the add timer dialog.

### To Reproduce

1. Create a radio epg auto timer for any channel using Enigma2 addon 
2. Go to timer rules in Radio and it will not be displayed 
3. Go to timer rules in TV and it will be displayed

### Debuglog

The debuglog can be found here:

I don’t believe a debug log is required here. Happy to provide if it is.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ x] OSX
 - [ ] Raspberry-Pi
 - [ x] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSX, Librelec x86, Windows
 - Kodi version: 18.2RC

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by emveepee** [comment]
In pvr.nextpvr I just tried this and it worked fine.  The radio program, scheduled via Kodi or with the NextPVR client show up as radio timers.

**Comment by phunkyfish** [comment]
You mean a regular timer or a timer rule for any channel?

**Comment by emveepee** [comment]
Sorry I misunderstood and didn't read any channel as "Any Channel"  NextPVR doesn't have a concept of  "Any Radio Channel" or "Any TV Channel" so I would expect the timer rule to appear in TV with individual recordings and timers to properly appear in the right group.

**Comment by phunkyfish** [comment]
It should be possible to denote a timer rule as type both, TV or Radio.

So if both the rule should appear in Radio and TV but only contain the timers for that type. I.e. in TV it could have timers but in Radio it might be empty.

**Comment by phunkyfish** [comment]
Looking into this further I see that the timer rule that appears in TV will state it has e.g. 4 scheduled, however if I enter to see the timers there are none (as they are all radio timers). Apart from the name there is no obvious way to see these timers grouped in the UI.

**Comment by ksooo** [comment]
I think we need to extend PVR adon API for this, seems in adition to existing  PVR_TIMER_ANY_CHANNEL, we need PVR_TIMER_ANY_TV_CHANNEL and PVR_TIMER_ANY_RADIO_CHANNEL.

Unfortunately, this change cannot be done for v18.

**Comment by ksooo** [comment]
For v18 I will fix it so that "any channel" timer rules will appear both under tv and radio and the respective child timers according to their channel either under tv or radio.

**Comment by phunkyfish** [comment]
Honestly I think that the fix for v18 is sufficient. Once they appear both under radio and TV with their respective children then I think we’re good.

**Comment by phunkyfish** [comment]
The configuration required on Enigma2 to make the v19 changes a requirement are unlikely to be configured by any user. It took me hours to figure out how to do it.

**Comment by ksooo** [comment]
> Honestly I think that the fix for v18 is sufficient. 

Yep. This is my opinion, too.

**Comment by phunkyfish** [comment]
For V19 there would be two things that would be useful to know. When a timer is added did it originate from TV or Radio. Also which Chanel group it originated from.
