### ISSUE TITLE
Kodi V18: xmbcgui.WindowXMLDIalog does not display a list of Listitems

### ISSUE THREAD

**Issue by jmooremcc** [xbmc/xbmc#15729]
### Describe the bug
Here is a clear and concise description of what the problem is:

My addon was developed under V17.6 and creates a main window (windowXMLDialog) that utilizes a ControlList in the xml file. The addon works perfectly under V17.6 but under V18.0 the list of Listitems are not displayed.

I used Web-Pdb to attempt to debug the problem after loading data into the window list.
Interactively I ran the self.getCurrentListPosition() function and -1 was returned.
Under V17.6 the value 0 (zero) is returned. I believe this erroneous CurrentListPosition value is the reason the list is not being displayed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Once loaded, List items should display in the list control and the xml window current list position should be set to 0.

## Actual Behavior

list items are not displayed in the list control and the xml window current list position remains at -1 even after explicitly setting it to zero in the Python code.

### To Reproduce

1. This is sample Python code illustrating how I generated a list of 2 Listitems and added them to the XML Window.

```
props=['abc','def']
dateformat = xbmc.getRegion('dateshort')
dataSetData = data
ilist = []
for prop in props:
      obj = xbmcgui.ListItem()
      obj.setProperty('Description', prop)
      ilist.append(obj)

#add iList to window list
self.addItems(iList)

self.setCurrentListPosition(0)
self.setFocusId(LISTCONTROL_ID)
```

### Debuglog

The debuglog can be found here:
https://pastebin.com/embed_js/usCfnciw"

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
V18.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jmooremcc** [comment]
Raspberry Pi running:
   LibreElec Version 9.0.0
   Lixux 4.19.17

Windows is running Version 10

**Comment by ronie** [comment]
adding listitems to the built-in container will only work for windows and no longer for dialogs.

you'l have to use something like this instead:
```
self.list = self.getControl(50)
self.list.addItems(iList)
```

**Comment by jmooremcc** [comment]
I did more testing to figure out what was happening. I eliminated the list in the original sample code and used the addItem method to add the Listitem.
`props=['abc','def']
dateformat = xbmc.getRegion('dateshort')
dataSetData = data

for prop in props:
      obj = xbmcgui.ListItem()
      obj.setProperty('Description', prop)
      self.addItem(obj)

self.setCurrentListPosition(0)
self.setFocusId(LISTCONTROL_ID)`
`
The above code did not work so I have to conclude that something else is behind the problem.

> adding listitems to the built-in container will only work for windows and no longer for dialogs.
> 
> you'l have to use something like this instead:
> 
> ```
> self.list = self.getControl(50)
> self.list.addItems(iList)
> ```



> adding listitems to the built-in container will only work for windows and no longer for dialogs.
> 
> you'l have to use something like this instead:
> 
> ```
> self.list = self.getControl(50)
> self.list.addItems(iList)
> ```

**Comment by ronie** [comment]
read my answer ;-)

**Comment by jmooremcc** [comment]
@ronie Thanks for the advice. It did work and I can now see my list being displayed.
However setFocusId(50) does not set focus on the list. Is there a new technique now for setting focus?

**Comment by ronie** [comment]
have also adopted the rest of the code?
```
self.list.setCurrentListPosition(0)
self.list.setFocusId(LISTCONTROL_ID)
```
