### ISSUE TITLE
Control appears in every next video played automatically

### ISSUE THREAD

**Issue by DeniR** [xbmc/xbmc#15722]
In Kodi 18 control button and seek panel appears in every next video, when 'play next video automatically' enabled.
In Kodi 17 nothing appear.

Windows 10.

**Comment by DaVukovic** [comment]
Could you please follow our issue template? We have that for a reason ;)

I'll mark your issue as invalid for the time being you provided all missing information we ask for in our template.

**Comment by DeniR** [comment]
I want to hide buttons in Kodi18 when next video is playing. Like in Kodi17.

**Comment by enen92** [comment]
@DeniR please use our issue template and fill the required information like any other issue we have in the repo. Close this one and open another if it's easier for you.
