### ISSUE TITLE
Same movie name causes information mismatch

### ISSUE THREAD

**Issue by trancenoid** [xbmc/xbmc#15731]
### Describe the bug
Here is a clear and concise description of what the problem is:

The information retrieval for movies is done automatically, and as I noticed if there are two movies of same name (and probably same year, for e.g see [this](https://www.imdb.com/title/tt5862312/) and [this](https://www.imdb.com/title/tt3183402/), There happens to be no option to choose manually which is the actual one (I tried searching, but I found no option to edit the information)  . This may result wrong labeling of movies (and music too). 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I had Veronica (spanish horror) movie in my movies folder, which should be identified as the spanish horror and not the other one ( a drama film of same name ). 

## Actual Behavior

I found that the information for the movie is picked up as another drama film of same name (I couldn't find that movie on imdb). 

## Possible Fix

There must a conflict resolution method to choose between the conflicting choices, or there must be option to change the info later.

### To Reproduce

1. Put a movie in the search directories which have same name as another movie released the same year (for example, see the movies pointed above) 
2. Open movies tab and browse for that movie.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You simply need to refresh the movie. 

See this. I scraped "Veronica" and got a movie from 1970

![grafik](https://user-images.githubusercontent.com/7235787/54219500-ef0d2780-44ef-11e9-9bef-c6be405b9801.png)

If I then enter the movie information window and hit "refresh":

![grafik](https://user-images.githubusercontent.com/7235787/54219557-0ba95f80-44f0-11e9-826c-8377da65b3eb.png)

Kodi claims, that it found local information and if you want to ignore that and rescrape online. 

![grafik](https://user-images.githubusercontent.com/7235787/54219645-309dd280-44f0-11e9-8d21-207b43579852.png)

After selecting "Yes" I get a bunch of "Veronica"-movies I can choose manually from.

Please, and don't take any offense, seek for assistance at the forums for such things. Github issues is meant for real bugs. ;)

Closing this

**Comment by trancenoid** [comment]
Sorry for posting it here, It did occurred to me to post it on forums but I found a link to github under "bug tracker" so I posted it here. I didn't knew that refreshing will prompt me to choose between movies. Thanks for your clarification @DaVukovic
