### ISSUE TITLE
Kodi 18 isssue with NFS share

### ISSUE THREAD

**Issue by Kal42** [xbmc/xbmc#15735]
### Describe the bug
Here is a clear and concise description of what the problem is:

Sometimes Kodi lost the connection to NFS share.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should be able to always read file on NFS share.

## Actual Behavior

Sometimes Kodi was not able to access NFS share. TCPdump on the device show that only the MySQL is going out, no NFS go throw the network when it failed.

## Possible Fix

I don't know, I will try Kodi 18.0 as during all the nightly/beta/rc no issue append. 

### To Reproduce

1. The NFS server is a standard Debian Stretch, with mariadb database.
2. Add a NFS share in kodi
3. Sometimes Kodi was not able to access it.

### Debuglog

The debuglog can be found here:
https://pastebin.com/cEi34tBt

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Mounting the NFS on the linux is working without issue. The server also have the mariadb database, and no issue with this part.
Workaround : Add a new NFS share, that trigger a scan of NFS share. Don't need to really add it, just listing the directory of the server.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X ] Raspberry-Pi (2, 3, 3B+)
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.2 RC1 on OSMC and LibreELEC 9.0.1 with Kodi 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lucky62** [comment]
Hello Friends,

Similar problem with NFS I have on Android TV box Tanix TX6.
After upgrade to Android 9 Pie the Kodi cannot browse/mount NFS shares.
I am using Kodi 18.2 (latest from Google Play).
The same version was working before upgrade on Android 7.
Seems that some OS dependency is broken.

In debug log I see only these two error messages:

`
2019-06-17 17:25:48.490 T:5997   ERROR: GetDirectory - Error getting nfs://
2019-06-17 17:25:48.491 T:5997   ERROR: CGUIDialogFileBrowser::GetDirectory(nfs://) failed
`
Messages were generated when I try to find/browse NFS shares.

What are the dependencies on Android? Which system calls/utilities are required to have NFS working?

**Comment by Kal42** [comment]
An update, I have also the issue on android tv.

**Comment by brucewzp** [comment]
I got same problem and I found coreElEC(v9.2.0) is working well.

**Comment by Gong-Bao-Chicken** [comment]
Android V 18.6 Leia - NFS not working, probably same issue.

**Comment by jesshaas** [comment]
I just wanted to confirm that NFS browsing is broken on android TV. I have a brand new Nvidia Shield updated to latest firmware with Kodi 18.6 (newest on play store). Browsing for NFS does not work. It works on my FireTV box with same version of Kodi which is also android but a different version and not android TV. I copied my sources.xml over from the firetv and I can access the files fine on the shield and scan the sources so it is just NFS browsing that is broken.

**Comment by Kal42** [comment]
I have found my issue, I don't know if it's related to timeout on nfs.

I had an old "photo" source that point to nfs share. And this nfs share doesn't exist anymore. So when I start Kodi, all my nfs was unavailable.

Since i have remove this old source, all is working back.

I think it still an issue, beaucse an non working NFS, should not break all the NFS.

**Comment by bbaserdem** [comment]
I have this problem; but without having configured anything before.

**Comment by DaveTBlake** [comment]
Closing this issue because the OP @Kal42 has resolved their problem. 

None of the rest of the "me too" have provided logs so there is no way to know anything about their problems. NFS browsing in Kodi is only supported on NFS v3, and not v4. So if having an issue browsing for shares  try manually adding a valid share at OS level.

**Comment by thomas-mc-work** [comment]
Is that documented somewhere?
