### ISSUE TITLE
Handling of Curl error prevents stream playback

### ISSUE THREAD

**Issue by theOehrly** [xbmc/xbmc#15745]
### Describe the bug
Here is a clear and concise description of what the problem is:

Playing a http video stream fails. The stream server is a television receiver inside my local network. (VLC plays the stream perfectly fine on the same machine)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video playback should start.

## Actual Behavior

The loading animation is shown for some time. Playback does not start.
The Debug Log shows:
`ERROR: CCurlFile::FillBuffer - Failed: Transferred a partial file(18)`

## Possible Fix

Here is what I have concluded after some testing. (I'm not a C++ dev and this might not be entirely correct.):
If a CURLE_PARTIAL_FILE error occurs during playback of a videostream, Kodi does not use the downloaded video data.  As these errors happen at the beginning of the playback Kodi cannot figure out the correct codec information and therefore does not play the stream.

CURLE_PARTIAL_FILE ERROR (Quoting from Curl documentation ):
> A file transfer was shorter or larger than expected. This happens when the server first reports an expected transfer size, and then delivers data that doesn't match the previously given size. 

As an experiment I just added the following lines of code in CCurlFile::CReadState::FillBuffer
`if (msg->data.result == CURLE_PARTIAL_FILE)
         return FILLBUFFER_OK;`
thereby effectively ignoring the error.
I did build Kodi myself and with this "fix" the stream is now starting to play.

The stream plays for 1-3 seconds. Then playback freezes (only playback, not Kodi itself). With SD quality streams the player recovers after some time with message "Source too slow". Now playback is perfectly fine as expected and the stream does not freeze again. 
720p streams did not start playing again, even after multiple minutes. Wild guess: Because Curl did not download the expected amount of data, the buffer is confused?

Better fix would be to check how much data was actually downloaded and do everything as it should be done... (I don't know how. This is way above my level)

### To Reproduce

- Difficult, use a Kathrein UFS 923 television receiver for streaming.
- If necessary, I might be able to set up access to the stream from outside my local network for a dev

### Debuglog

The debuglog can be found here:
Official Build, playback fails: https://pastebin.com/xjtH6gw9

Own Build, playback freezes and recovers:   https://pastebin.com/3TXCKKCP
PARTIAL_FILE errors are still logged but ignored

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64 bit, LibreElec 9.0
 - Kodi version: Kodi 18.1

**Comment by wsnipex** [comment]
please enable curl component logging and provide a new log

**Comment by theOehrly** [comment]
Here it is. 
[kodi_curl_component.log](https://github.com/xbmc/xbmc/files/2973768/kodi_curl_component.log)

**Comment by wsnipex** [comment]
That looks like a broken server. It does not use transfer-encoding chunked and it responds to range requests on a live stream.

Please try if you can play those streams by adding &seekable=0 to the URL.
e.g. http://192.168.178.16/content/live-streaming/liveStream-http-5-1.ts&seekable=0

**Comment by theOehrly** [comment]
No, still not working. Here's the new log but I can't spot any difference.
[kodi.log](https://github.com/xbmc/xbmc/files/2975003/kodi.log)

**Comment by wsnipex** [comment]
ah sorry, it should be  http://192.168.178.16/content/live-streaming/liveStream-http-5-1.ts?seekable=0

**Comment by theOehrly** [comment]
Again not working. Don't think anything changed
[kodi.log](https://github.com/xbmc/xbmc/files/2979283/kodi.log)
