### ISSUE TITLE
Media added from an http source don`t autoload external subtitles

### ISSUE THREAD

**Issue by zentown** [xbmc/xbmc#15742]
### Describe the bug
Here is a clear and concise description of what the problem is:

Media added from an http source don`t autoload external subtitles but kodi's http client recognize the subtitles in the dir because when you browse for subtitles it shows all the subs in the directory

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The subtitles should be recognized and matched and loaded by its name as the others video sources do

## Actual Behavior

Subtitles are recognized in the subtitles browser but are not auto loaded

### To Reproduce

1. Create an apache http server
2. Put video files with subtitles with same name inside htdocs folder
3. Add apache http as a video source on kodi and scan the media
4. Play the video
5. Subtitles are not loaded need to load trough the subtitle browser

### Debuglog

The debuglog can be found here:
1. Debug log for a session just playing a video in with subtitle are not recognized https://paste.kodi.tv/mojepiciza.kodi

2. Debug log for a session playing a video in with subtitle are not recognized and manually selected trough the subtitle browser https://paste.kodi.tv/mojepiciza.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

1. Video playing without subtitle recognized https://postimg.cc/pp8JQMN1
2. Subtitles In browse menu https://postimg.cc/Snh7D1kQ
3. Subtitle correctly manually loaded https://postimg.cc/18r0T03G

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

-How has this bug affected you? 
The Google drive addon from the kodi repository expose the files as an http server so videos played from this addon don`t auto load the sub

-Y think that this bug is also present in android (and probably in the others platforms to) but y didn't properly test/confirm

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sopparus** [comment]
Has been like this always, try webdav until/if this gets fixed

**Comment by arnova** [comment]
Partially fixed with #16070. This should fix the issue for most scenarios. Optionally one could add a remote host to the system's hosts file to also take advantage of this.

**Comment by 7596ff** [comment]
still having this issue, should this be reopened? didn't want to duplicate
