### ISSUE TITLE
Video Issue after Leia Upgrade

### ISSUE THREAD

**Issue by mmBesar** [xbmc/xbmc#15752]
### Describe the bug
Here is a clear and concise description of what the problem is:

My x265 videos - used to work in 17.6 with the same PC under the same OS - now playing as if the GPU has no drivers!
Be noted that x264 files playback not smooth too and subtitles always just white box!

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The videos should work normally as it was working under 17.6

## Actual Behavior

The videos act as we use to get in the old days under windows 98 when the GPU has no drivers installed.
Subtitles are big White Box.

## Possible Fix

Add support for Intel old GPUs

### To Reproduce

1. X265 file.
2. Run Kodi 18 under Linux Mint
3. Motherboard GA-G31M-ES2L with built-in  GPU

### Debuglog

The debuglog can be found here:
https://pastebin.com/zHqgrYRW

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://imgur.com/a/VKn2AZ9

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux Mint
 - Kodi version: 18

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
We don't support your GPU anymore

```
GL_VERSION = 1.4 Mesa 18.2.2
```

Switch back to 17.6 - for using upcoming kodi versions in good quality, make sure to support OpenGL 3.1 or higher - 4.x recommended.

**Comment by mmBesar** [comment]
Thank you for the quick and clear answer, I hope you guys reconsider.
If anything I can do from my side - to get Leia working on my old hardware - it would be great. 
Love your project, thanks.
