### ISSUE TITLE
Duplicate Movie entry for stale paths

### ISSUE THREAD

**Issue by christianstock** [xbmc/xbmc#15761]
### Describe the bug
Here is a clear and concise description of what the problem is:

I get a duplicate movie entry for a movie where I changed the letter case of the path name in Windows  10 on a NAS location for Kodi Leia (18 and 18.1).

I think I've figured out the cause of this issue. The myvideos database is recording all paths in the path table without ever cleaning this table up when I remove titles (or run clean). I'm guessing that when running a scan, Kodi is using this table in addition to scanning the file system. In my log I'm getting multiple "path not found" errors in the log file, for stale paths.

However, I got 2 paths "Dial M for Murder" and "Dial m for Murder" after I renamed the path (correcting the lower case M) and while the database is case sensitive, Windows isn't, so a movie scan will add 2 entries for the same movie.

A clean doesn't remove the stale paths in the path table.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

1) remove 2 movie entries
2) run clean
3) run scan

=> 2 entries, one each for lower and upper case path.

## Actual Behavior

should be only one entry

## Possible Fix

Don't allow identical paths with different letter cases in table paths?

Clean performs a clean in table path?

For Windows Kodi, check if path is identical to an existing entry before adding to library?

### To Reproduce

1.  Create folder on NAS
2. Scan
3. Rename folder with a changed letter case
4. Scan

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/utamopovof.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

https://forum.kodi.tv/showthread.php?tid=342057&pid=2834961#pid2834961

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Similar report with mis-matched case also on Windows... 
https://forum.kodi.tv/showthread.php?tid=341552&pid=2829885#pid2829885
