### ISSUE TITLE
[games] In most games only one controller works

### ISSUE THREAD

**Issue by cpfaff** [xbmc/xbmc#15765]
### Describe the bug
Here is a clear and concise description of what the problem is:

I use kodi on an odroid c2. Attached to the odroid are two buffalo classic USB gamepads. Both of them are working fine inside of Kodi. When playing 
multiplayer games, however, only one of them seems to work e.g. the option for two players is grayed out or simply not selectable. This behaviour however is not consistent. I have at least one game where it is working, however most are 
not.

## Expected Behavior

Both controllers should work in games to play multiplayer games. 

### To Reproduce

Install a fresh kodi 18.1 using coreelec on odroid c2. Add two buffalo USB controllers to the odroid. Configure the controllers in system > controllers to be sure. Confirm that both controllers work fine in kodi. Add a multiplayer game (or play from IAGL) and try to play it with two controllers. 

### Debuglog

https://gist.github.com/cpfaff/b18294a2aa21a576877140f0571f4629

### Your Environment

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Coreelec 9.0.1
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by chchia** [comment]
i have a similar issue
https://forum.kodi.tv/showthread.php?tid=347196

https://github.com/xbmc/peripheral.joystick/issues/172

looking forward for suggestion

**Comment by KOPRajs** [comment]
Possibly related issue: https://github.com/kodi-game/game.libretro.genplus/issues/11

However for me this problem seems to only affect the Genesis Plus GX emulator. The following emulators are tested and work with 2 players:
Nestopia
SNES9x
PCSX-reArmed

I've found out that Mega Bomberman in Genesis Plus GX emulator works even with 4 players / controllers.

My setup:
CoreELEC 9.2.7 (Amlogic-ng)
Kodi 18.9
Chinese Bluetooth gamepads (Gen Game S5 and similar)

**Comment by KOPRajs** [comment]
I believe this issue might be closed as solved by the port setup dialog. At least for me most of the emulators can play 2 players.

If there is still a problem, then it is probably emulator specific. In such case we should create new issue for every emulator that is not working as expected.

Genesis Plus GX is probably a candidate for a topology specific issue.

**Comment by garbear** [comment]
Agreed, the Port Manager released in v20 lets multiple controllers work in a game.
