### ISSUE TITLE
when Install from repository, kodi says "Could not connect to repository"

### ISSUE THREAD

**Issue by tskten** [xbmc/xbmc#15760]
### Describe the bug
Here is a clear and concise description of what the problem is:

First I installed kodi by 'pacman -S kodi'.
Right after kodi is installed, I start it,  go to [Add-ons > Download > Install from repository].
Then kodi says:"Could not connect to repository".

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect kodi connect to repository correctly.

## Actual Behavior

It didn't.

## Possible Fix

It seems the problem happens at CRepository::FetchChecksum.
 the function will fetch addons.xml.gz , taking its first line of text as checksum, while the file itself is a binary file. 

### To Reproduce

1. install kodi ('pacman -S kodi' on arch linux)
2. start kodi
3. go to [Add-ons > Download > Install from repository]

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/buhunuduxi.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [o] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux 5.0.0-arch1-1-ARCH
 - Kodi version: 18.1-2 or "18.1 Git:20190224-nogitfound" from log file

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
Hi! This is clearly a problem with your network. You get redirected to another server unrelated to Team Kodi:

```
2019-03-16 15:23:21.012 T:140239068718848   DEBUG: CurlFile::Open(0x7f8bec0d5160) http://mirrors.kodi.tv/addons/leia/addons.xml.gz?sha256
2019-03-16 15:23:21.275 T:140239068718848   DEBUG: CCurlFile::Open - effective URL: <http://45.252.224.198/files/406900000D444DC4/mirrors.kodi.tv/addons/leia/addons.xml.gz>
```

This is presumably a cache server, but who knows. It is not under our control. During the URL rewrite, the query string `?sha256` is removed, which leads to the wrong content being returned. The solution is to fix your network or complain to your service provider if it is not under your control.

As this is a support request, please open a thread over at the [forums](https://forum.kodi.tv/) if you have further trouble.

Hope that helps!
