### ISSUE TITLE
xbmc.SendButton (c++ client api) does not work for return, escape

### ISSUE THREAD

**Issue by v44r** [xbmc/xbmc#15772]
### Describe the bug
xmbc.SendButton used to work for all keys in kodi 17. Now some keys such as return or escape do nothing. This has happened at least since august (when I asked this in the forums: https://forum.kodi.tv/showthread.php?tid=334606).

## Expected Behavior
Return / Escape should behave as if the keys were pressed in an actual keyboard.

## Actual Behavior
They do nothing.

## Possible Fix

?

### To Reproduce
Compile this:
```
#include "xbmcclient.h"

int main(int argc, char* argv[])
{
  CXBMCClient xbmc;
  xbmc.SendButton(argv[1], "KB", BTN_NO_REPEAT);
}
```
And run as ./a.out _key_. Keys such as "left", "right", "s", perform the expected action. Keys such as "return" or "escape" do nothing. They used to work fine in kodi 17.

This also happens with kodi-send.py and the other examples in EventClients/Clients and EventClients/examples.

### Debuglog

When running ./a.out down:
```
2019-03-19 13:14:37.447 T:1615811312   DEBUG: EventClient: button code 0 pressed
2019-03-19 13:14:37.462 T:1916384816   DEBUG: HandleKey: down (0xf081) pressed, action is Down
```

When running ./a.out return:
`2019-03-19 13:15:38.126 T:1615811312   DEBUG: EventClient: button code 0 pressed`
...and nothing else.

When running ./a.out invalidname (different from "return", which seems to indicate "return" is recognized but ignored):
```
2019-03-19 13:16:06.338 T:1615811312   DEBUG: EventClient: button code 0 pressed
2019-03-19 13:16:06.338 T:1615811312   ERROR: Keyboard Translator: Can't find button invalidname
2019-03-19 13:16:06.341 T:1916384816   DEBUG: HandleKey: 0 (0xf000, obc-61185) pressed, action is
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux, OSMC
 - Kodi version: Kodi 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
Please provide a *full* debug log running Kodi (OSMC is not supported here, they have their own support channels). Thanks!

**Comment by v44r** [comment]
https://paste.kodi.tv/ofugezoqaz.kodi

13:58:13.708: send "down" three times (menu selection goes down three times).
13:58:17.775: send "return" three times and "escape" another three times (hence the "Previous line repeats 6 times.", nothing happens)
13:58:24.366: send "invalidkey" three times (nothing happens).

**Comment by mglae** [comment]
Same for [xbev](https://github.com/bobo1on1/xbev), all keys with long press mapping are suppressed. Try:
```
--- a/xbmc/input/InputManager.cpp
+++ b/xbmc/input/InputManager.cpp
@@ -467,7 +467,7 @@ bool CInputManager::OnKey(const CKey& key)
     }
     else
     {
-      if (!m_buttonTranslator->HasLongpressMapping(CServiceBroker::GetGUI()->GetWindowManager().GetActiveWindowOrDialog(), key))
+      if (key.GetFromService() || !m_buttonTranslator->HasLongpressMapping(CServiceBroker::GetGUI()->GetWindowManager().GetActiveWindowOrDialog(), key))
       {
         m_LastKey.Reset();
         bHandled = HandleKey(key);
```

**Comment by v44r** [comment]
Yep, with that patch everything works as in v17:

```
2019-03-20 17:03:11.479 T:139815160878848   DEBUG: EventClient: button code 0 pressed
2019-03-20 17:03:11.483 T:139816246499968   DEBUG: HandleKey: enter (0xf065) pressed, action is Select
2019-03-20 17:03:15.462 T:139815160878848   DEBUG: EventClient: button code 0 pressed
2019-03-20 17:03:15.478 T:139816246499968   DEBUG: HandleKey: escape (0xf01b) pressed, action is PreviousMenu
```

**Comment by mglae** [comment]
Alternative regression fix. I'm undecided which to PR.
```
--- a/xbmc/input/InputManager.cpp
+++ b/xbmc/input/InputManager.cpp
@@ -260,7 +260,9 @@ bool CInputManager::ProcessEventServer(int windowId, float frameTime)
       else
         key = CKey(wKeyID);
       key.SetFromService(true);
-      return OnKey(key);
+      OnKey(key);
+      OnKeyUp(key);
+      return true;
     }
   }
 
```

**Comment by v44r** [comment]
Yeah, that also works fine.

**Comment by sirchia** [comment]
I also suffer from this issue. It causes the iOS app I normally use to control Kodi (which apparently uses an EventClient to send at least some of its commands as keystrokes) to not function completely.

I'm eagerly awaiting the correct fix for this issue, but the analysis of @mglae did hint me to a workaround to keep my set-up fully functioning in the mean time. I thought I'd share this for everyone affected and who is not able/willing to recompile from scratch with the provided patches.

As described in [the manual for keymaps](https://kodi.wiki/view/Keymap#Removing_a_long-press_action_from_a_default_keymap) it is possible to place an override keyboard.xml in userdata/keymaps that removes the longpress mapping for the keys that are giving you issues.

**Comment by snixel** [comment]
Thx for the tip sirchia! I used the below custom keymap to remove the longpress keys giving me issues.

`<keymap>
  <global>
    <keyboard>
      <return mod="longpress"></return>
      <enter mod="longpress"></enter>
      <escape mod="longpress"></escape>
    </keyboard>
  </global>
</keymap>
`

**Comment by dvershinin** [comment]
Note that `.xml` way of disabling long-press is only a workaround. E.g. in my case, I had to override several screens, `<global>` section was not enough. 

Please have this pull request merged. It works fine and fixes a whole bunch of clients which rely on the event server!

**Comment by fuzzard** [comment]
Following PR was merged  to resolve this issue

https://github.com/xbmc/xbmc/pull/17806
