### ISSUE TITLE
Kodi fails to build with Linux 5.1-rc1

### ISSUE THREAD

**Issue by MilhouseVH** [xbmc/xbmc#15775]
### Describe the bug

When building Kodi against Linux 5.1-rc1, Kodi fails to build as follows:
```
In file included from
/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.1-devel-next/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/linux/kernel.h:5,
                 from
/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.1-devel-next/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/sys/sysinfo.h:24,
                 from ../xbmc/platform/linux/PlatformDefs.h:44,
                 from ../xbmc/XBDateTime.h:12,
                 from ../xbmc/utils/StringUtils.h:35,
                 from ../xbmc/utils/log.h:15,
                 from ../xbmc/filesystem/DllLibCurl.cpp:13:
/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.1-devel-next/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/linux/sysinfo.h:9:2:
error: '__kernel_long_t' does not name a type; did you mean
'__syscall_ulong_t'?
  __kernel_long_t uptime;  /* Seconds since boot */
  ^~~~~~~~~~~~~~~
  __syscall_ulong_t
/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.1-devel-next/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/linux/sysinfo.h:10:2:
error: '__kernel_ulong_t' does not name a type; did you mean
'__syscall_ulong_t'?
  __kernel_ulong_t loads[3]; /* 1, 5, and 15 minute load averages */
  ^~~~~~~~~~~~~~~~
  __syscall_ulong_t
```

The change in behaviour is due to this 5.1-rc1 commit: https://github.com/torvalds/linux/commit/a623a7a1a5670c25a16881f5078072d272d96b71

However this change shouldn't be an issue for user space apps, but for Kodi it is.

## Expected Behavior

Kodi builds successfully with Linux 5.1-rc1 (it builds fine with Linux 5.0.2).

## Actual Behavior

Kodi fails due to undefined type.

## Possible Fix

I pinged this issue over to the [glibc mailing list](https://sourceware.org/ml/libc-help/2019-03/msg00010.html) and they concluded this is a [Kodi issue](https://sourceware.org/ml/libc-help/2019-03/msg00014.html) that Kodi needs to fix as it misuses headers.

### To Reproduce
1. Build LibreELEC with kernel 5.1-rc1

### Debuglog

Kodi build log: http://ix.io/1DXy

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 17.10
 - Kodi version: Kodi 18 master (76db73d1020c91378572fc4fb2b627b71293ea0b)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
did you try moving the include out of the namespace, just for fun?

**Comment by MilhouseVH** [comment]
Not yet. Do you mean this:
```
diff --git a/xbmc/filesystem/DllLibCurl.h b/xbmc/filesystem/DllLibCurl.h
index 5b978a1..e6d70cd 100644
--- a/xbmc/filesystem/DllLibCurl.h
+++ b/xbmc/filesystem/DllLibCurl.h
@@ -17,13 +17,14 @@
 #include <type_traits>
 #include <vector>

-/* put types of curl in namespace to avoid namespace pollution */
-namespace XCURL
-{
 #define CURL CURL_HANDLE
 #include <curl/curl.h>
 #undef CURL

+/* put types of curl in namespace to avoid namespace pollution */
+namespace XCURL
+{
+
 class DllLibCurl
 {
 public:
```
?

**Comment by pkerling** [comment]
yup

**Comment by MilhouseVH** [comment]
Not that now fails for a different reason: http://ix.io/1DYA
```
../xbmc/filesystem/CurlFile.cpp: In member function 'virtual bool XFILE::CCurlFile::Exists(const CURL&)':
../xbmc/filesystem/CurlFile.cpp:1254:9: error: reference to 'curl_slist' is ambiguous
         curl_slist *list = NULL;
         ^~~~~~~~~~
In file included from ../xbmc/filesystem/CurlFile.cpp:9:
../xbmc/filesystem/CurlFile.h:21:10: note: candidates are: 'struct XCURL::curl_slist'
   struct curl_slist;
          ^~~~~~~~~~
In file included from ../xbmc/filesystem/DllLibCurl.h:21,
                 from ../xbmc/filesystem/CurlFile.cpp:33:
/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.1-devel-next/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/curl/curl.h:2413:8: note:                 'struct curl_slist'
 struct curl_slist {
        ^~~~~~~~~~
```

This is how `xbmc/filesystem/DllLibCurl.h` looks now: http://ix.io/1DYC

**Comment by pkerling** [comment]
OK then someone will have to dig a little deeper - I just hoped it for once could be that easy :-)

**Comment by pkerling** [comment]
Try this: https://pastebin.com/2VRfPbWU

**Comment by MilhouseVH** [comment]
Many thanks - your patch is building successfully with both 5.1-rc1 and 5.0.2.

Playback of a YouTube video with the resulting 5.1-rc1/5.0.2 builds is working fine, as is seeking, so it looks good here!
