### ISSUE TITLE
autobot response contains broken URL

### ISSUE THREAD

**Issue by olafhering** [xbmc/xbmc#15789]
### Describe the bug
Here is a clear and concise description of what the problem is:
The autoresponse for a new, but eventually incomplete, issue references a link to a template.
The used url does not work, as it can be see in issue  #15788 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If there is a link included it would be nice if the URL points to an existing location.

## Actual Behavior
The link to https://github.com/xbmc/xbmc/issues/.github/ISSUE_TEMPLATE.md does not work as of now.

## Possible Fix
Adjust the template.

### To Reproduce
1. find an issue with xbmc.git
2. report it in the issue tracker
3. observe the broken URL in the  autoresponse

### Debuglog

The debuglog can be found here:
got to issue #15788, second comment, observe the link to "template":
https://github.com/xbmc/xbmc/issues/.github/ISSUE_TEMPLATE.md

### Screenshots 
Here are some links or screenshots to help explain the problem:

issue #15788 

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Leap 15.0
 - Kodi version: none

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
Thanks, fixed, but please report non-code issues to the forums in the future
