### ISSUE TITLE
Help information for binary addons settings - bug or feature request?

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#15793]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using the new settings format in a binary addon even though help information is set in the addons settings.xml it will not display in the addon settings dialog.

Not clear if this is a bug or feature request.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When using the new settings format in a binary addon when help information is set in the addons settings.xml it displays in the addon settings dialog.

## Actual Behavior

When using the new settings format in a binary addon even though help information is set in the addons settings.xml it will not display in the addon settings dialog.

### To Reproduce

1. Add a help tag to pvr.vuplus settings element in the addons settings.xml
2. Build and install the addon
3. Help info is not displayed

### Debuglog

The debuglog can be found here:

Happy to provide if this is a bug and not a feature request.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [x ] iOS
 - [ ] Linux
 - [x ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

Kodi 18.2, LibreElec Intel/Rpi3, MacOSX

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
can confirm.
skins have not been updated for the use of the new settings system.

DialogAddonSettings.xml needs a textbox control with id="6"

**Comment by phunkyfish** [comment]
A bit of an aside but should the level button also exist here, I.e. Basic, Normal, Advanced, Expert? Is that also a missing skin update?

**Comment by ronie** [comment]
fix for the missing help text: https://github.com/xbmc/xbmc/pull/15795

adding a settings level button to the addon settings dialog would require core changes.
it would make sense though to have it there as well...

**Comment by ronie** [comment]
settings level button: https://github.com/xbmc/xbmc/pull/15796
