### ISSUE TITLE
[Android TV][Multi-language] Chinese-Simplified and Chinese-Traditional displays tofu

### ISSUE THREAD

**Issue by rawghtsteven** [xbmc/xbmc#15797]
### Describe the bug
On Android TV Kodi, switch language to Chinese doesn't work

## Expected Behavior

Language displays correctly

## Actual Behavior

Characters turned to tofu

### To Reproduce

1.Go to Settings-Interface-Regional-Languages
2.Select Chinese-Simplified or Chinese-Traditional
3.After language patch downloaded and reseted, characters all turned to tofu.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android TV 8.0

 - Operating system version/name: Android TV 8.0
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Which skin are you using?

**Comment by DaVukovic** [comment]
duplicate: #15154
