### ISSUE TITLE
Screen goes black after video playback finishes

### ISSUE THREAD

**Issue by tamparob** [xbmc/xbmc#15806]
### Describe the bug
Here is a clear and concise description of what the problem is:

After video playback finishes, the screen goes black and Kodi no longer responds.  If I stop the video before playback ends, Kodi goes back to the menu screen.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When video playback ends, Kodi should go back to the previous menu screen.

## Actual Behavior

When video playback ends, screen goes black and will no respond.  My Anodroid box must be powered off and back on to restart Kodi.

### To Reproduce

1. Play video (I was playing a TV show from an SBM share)
2. Let video play all the way through
3. Screen goes black and Kodi no longer responds.

### Debuglog

The debuglog can be found here:
https://www.dropbox.com/s/aht568usbzc4xo1/kodi.old.log?dl=0

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

This is a new bug.  I tried to change to a skin that was supported by 18.1 and that didn't change the behavior.  I changed from Confluence to Estuary.

### Your Environment
Used Operating system:

 - [ X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.1/Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by tamparob** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/3006512/kodi.log)

at around 23:45 the screen froze.  I left Kodi running and went to sleep.  When I woke up, Kodi was responding again.  Before the screen froze, I noticed that some shows that I marked as watched, no longer had the check mark.  I also had a show that was halfway watched and that icon changed to the normal unwatched icon as well.

**Comment by rainman74** [comment]
same here: [15637](https://github.com/xbmc/xbmc/issues/15637)

**Comment by Sopor** [comment]
@tamparob You need to read the rules. The developers don't want to download any log files. They need to read them easy, so follow the rules if you want your issue to be fixed.
`Do NOT post your logs directly in a forum. Always use a paste site like https://paste.kodi.tv`
And why did you ignored `Operating system version/name:`?

**Comment by tamparob** [comment]
Already moved on to Plex after years of Kodi.

Sent from my iPhone

On Mar 28, 2019, at 8:59 PM, Sopor <notifications@github.com<mailto:notifications@github.com>> wrote:


@tamparob<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftamparob&data=02%7C01%7C%7C1c5dab848a9f4f76750708d6b3a713cb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636893927498467400&sdata=HWU6BL1uORjDalidDJV8QY4xS78hw9ten23%2FM2JBO4U%3D&reserved=0> You need to read the rules. The developers don't want to download any log files. They need to read them easy, so follow the rules if you want your issue to be fixed.
Do NOT post your logs directly in a forum. Always use a paste site like https://paste.kodi.tv
And why did you ignored Operating system version/name:?

**Comment by rainman74** [comment]
For example, I cannot use paste.kodi.tv because it has a line boundary and debug logs are often longer!

**Comment by Sopor** [comment]
@rainman74 Default seems to be 400000 characters. Maybe you could tell the devs to increase it if this is an issue for you?

**Comment by MartijnKaijser** [comment]
If your logs are too big you aren't doing your logs correctly.

**Comment by DaVukovic** [comment]
or simply use paste.ubuntu.com as that will be less restrictive.

**Comment by rainman74** [comment]
@DaVukovic thx

**Comment by DaVukovic** [comment]
Closing this for now. 

No new log was provided. If the issue still exists, feel free to comment here with a new and clean logfile (clean in meaning "no banned add-ons" installed) and I'll happily reopen it again.

**Comment by rainman74** [comment]
That's ok, the error doesn't occur with the current nightly builds anymore!
