### ISSUE TITLE
Display overlay player on autoplay

### ISSUE THREAD

**Issue by Dirk97** [xbmc/xbmc#15809]
Hello,
when switching from Kodi v 17.3 to Kodi v18.1 with Standardskin Estuary (LibreELEC 9.0.1 on Raspberry Pi 3), I noticed the following: If you enable the automatic playback of the next file, for example, from musicvideos, then when playing the next File briefly overlay the player (pause button, stop button, info, setting, artist, title, etc.). Can one deactivate this? I found nothing in the settings. It was not shown on Kodi v 17.3.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MartijnKaijser** [comment]
GitHub is not for asking questions. Use the forum.
