### ISSUE TITLE
audio dropouts in file mode

### ISSUE THREAD

**Issue by lich000king** [xbmc/xbmc#15807]
When starting a playback of an audio file, the first split second is heard, then there is a ~0.5s interrupt, then playback continues normally.

Point to note: this interrupt only appears when starting playback in file mode through a remote app (like kore), not when starting playback browsing through the audio files in the kodi GUI using the app's navigation buttons or a keyboard.

- It didn't happen in v17
- It doesn't matter if it's mp3 or flac
- It doesn't matter if the file is stored on a network share, a usb drive, the internal SD card
- It happens also when using file mode in yatse remote
- Tested on a rpi 3 model B+ using a freshly installed libreelec 9.0.1 image (no addons no nothing), though this happened throughout leia's alpha/beta phase
- This also happens in OSMC (their nightlies are on 18.1), though, perhaps interestingly, the dropout is much shorter.

Here's a log where this happens:
https://pastebin.com/Viw5xCHn

Here's a log where playback is started through the kodi GUI and this does not happen:
https://pastebin.com/38SF2nc6

Another thing that may be related is the following: when pausing playback and starting a different file, a split second of the old file is played first. However, *this happens in both cases*, e.g. through remote and through GUI (and should thus be covered by both logs).

This may or may not be related to this issue:
https://github.com/xbmc/xbmc/issues/15568

**Comment by lich000king** [comment]
Fixed in PR 17038.

**Comment by DaveTBlake** [comment]
Fix backported to Leia by https://github.com/xbmc/xbmc/pull/17084
