### ISSUE TITLE
Compiling against newer crossguid

### ISSUE THREAD

**Issue by sagitter** [xbmc/xbmc#15802]
### Describe the bug
Kodi currently requires `guid.h` for compiling but [crossguid](https://github.com/graeme-hill/crossguid) has been recently modified with the release 0.2*

Any chance to adapt your code with `crossguid-0.2*` ?

Thanks.

**Comment by MartijnKaijser** [comment]
This is not a bug but a request

**Comment by MartijnKaijser** [comment]
Also see
https://github.com/xbmc/xbmc/pull/15790

**Comment by sagitter** [comment]
> This is not a bug but a request

Okay.
But has Kodi recently been modified for using latest `crossguid` code? 
See [this comment](https://github.com/graeme-hill/crossguid/pull/50#issuecomment-475463506)

**Comment by MilhouseVH** [comment]
@sagitter I wrote that comment, and perhaps Kodi will be updated in time, but the recent `crossguid` changes (C++17, .h -> .hpp) seem to be rather unnecessary and have rendered the latest `crossguid` incompatible with a number of downstream projects, which doesn't seem very sensible. Maybe the new and incompatible CPP version of `crossguid` should have been created as a completely separate project/repo (ie. `crossguid2`), leaving the old C-based `crossguid` to continue/die as the legacy version for existing downstream projects.

**Comment by pkerling** [comment]
> But has Kodi recently been modified for using latest crossguid code?

I'm not sure what you are expecting here? There is no released version with substantial changes, the API/ABI is not stable, and if it ever does get released it *will* need a SONAME bump in order to not annoy lots of downstream projects. There is nothing for us to do at this point.

**Comment by pkerling** [comment]
I think I get it now. You want to compile against the released 0.2.x version and not master, I think? Sorry for mixing that up, we recently had another issue report about crossguid master.

**Comment by pkerling** [comment]
crossguid 0.2.0 was released 2017, so I got confused by your wording "was *recently* updated" :-)

**Comment by pkerling** [comment]
I've looked into it, and I don't think we will be adding support for crossguid 0.2.x either. It seems every version renames the header file...

For 0.1.x it was guid.h, then Guid.hpp in 0.2.x, and now guid.hpp (lowercase) in master. I think it is best to wait until the author eventually settles on something and releases version 1.x. Distributions also seem to package crossguid 0.1.x. Please just use the included version.

**Comment by sagitter** [comment]
There is a conflict of dependencies on Fedora in this moment: software that requires recent `crossguid` code (`guid.hpp`) and software that requires the older version like `Kodi`.
I fear we will have to use separated packages: one for old `crossguid` and another for that newer one.

**Comment by pkerling** [comment]
> I fear we will have to use separated packages: one for old crossguid and another for that newer one.

Yes, I'm afraid this is bound to happen when libraries break API. As said, you can still use internal crossguid. It is just a few lines of code.

> At this point, precisely.

??? https://github.com/graeme-hill/crossguid/tree/v0.2.0

**Comment by sagitter** [comment]
> > At this point, precisely.
> 
> ??? https://github.com/graeme-hill/crossguid/tree/v0.2.0

It was modified later, with a new library name (`guid.hpp`) and newer .so library (`libcrossguid.so`, no longer `xg.so`).

**Comment by pkerling** [comment]
So there are different 0.2.x? Great! Can I have more confusion please? :-)
