### ISSUE TITLE
Movie Sets with one member don't appear in "Select movie set" list

### ISSUE THREAD

**Issue by MilhouseVH** [xbmc/xbmc#15814]
### Describe the bug

If a movie set contains one member, and the setting `Include sets containing a single movie` is disabled, then it is not possible to add a second member to the Movie Set as the Movie Set is not listed in the `Manage movie set` > `Select movie set` dialog.

## Expected Behavior

All Movie Sets with single or multiple movies should be listed in the `Select movie sets` dialog regardless of the `Include sets containing a single movie` setting.

## Actual Behavior

Movie Sets that contain a single movie are not listed in the `Select movie sets` dialog, making it (almost) impossible to add a second movie to an existing Movie Set that contains only a single movie.

## Possible Fix

Presumably a SQL query somewhere needs to ignore the single-movie filter when populating the "Select movie sets" dialog. Not sure if the same query is used for the "Select movie set" dialog as it is elsewhere, which would complicate the change.

### To Reproduce

1. Set `Include sets containing a single movie` to disabled
2. Enter the Movies listing
3. For any random movie (not already in a movie set), from the context menu select `Manage...` > `Manage Movie Set` then click on `Add movie to a new set` and create Movie Set `ABC`
4. For a second random movie (not already in a movie set), from the context menu select `Manage...` > `Manage Movie Set`
5. Attempt to add the second movie to the Movie Set `ABC` - the movie set `ABC` is not listed

Clicking `Add movie to a new set` and then entering the title of the existing Movie Set (ie. `ABC`) will allow the second movie to be added to the existing Movie Set, at which point the Movie Set `ABC` will start to appear in the `Select movie set` dialog list whenever adding additional movies.

Obviously this solution isn't practical unless the name of the Movie Set is trivially simple (as per the example).

### Debuglog

Not relevant.

### Screenshots 

This is the meta data for the Movie Set `Fantastic Beasts Collection` when attempting to add a second movie set member:
```
  {
    "art": {
      "fanart": "image://nfs://192.168.0.3/mnt/share/media/Video/MoviesHD/Fantastic Beasts Collection/fanart.jpg/",
      "poster": "image://nfs://192.168.0.3/mnt/share/media/Video/MoviesHD/Fantastic Beasts Collection/poster.jpg/"
    },
    "label": "Fantastic Beasts Collection",
    "setid": 79,
    "tc.members": [
      {
        "file": "nfs://192.168.0.3/mnt/share/media/Video/MoviesHD/Fantastic Beasts Collection/Fantastic Beasts - The Crimes of Grindelwald (2018)[BDRip].mkv",
        "movieid": 2771,
        "sorttitle": "FB02",
        "title": "Fantastic Beasts: The Crimes of Grindelwald"
      }
    ],
    "title": "Fantastic Beasts Collection"
  },
```
`Include sets containing a single movie` disabled:
![s1](https://i.imgur.com/t8mO9Fh.jpg)
![s2](https://i.imgur.com/7yc8ib0.png)

`Include sets containing a single movie` enabled:
![s3](https://i.imgur.com/waYi8ju.jpg)
![s4](https://i.imgur.com/22oK4sc.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 10.0 (test build)
 - Kodi version: 18.2 master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Thanks for bringing that up again. This was already reported some time ago but as it was on trac: https://trac.kodi.tv/ticket/17880

**Comment by MilhouseVH** [comment]
Ah yes, thanks, that's certainly the same issue. However on that ticket @KarellenX appears to have been happy to accept the `Include sets containing a single movie` setting as a solution, but from an end-user experience point of view I don't think that's really acceptable as you shouldn't have to toggle that setting just to add a second movie to a Movie Set - that setting should have absolutely no impact on Movie Set _management_.

**Comment by HunterZ** [comment]
I just banged into this, and emphatically agree that the "include sets containing a single movie" setting should *not* need to be enabled in order for a movie set with only one movie assigned to be listed in the "select movie set" GUI.

**Comment by howie-f** [comment]
@MilhouseVH 
> Presumably a SQL query somewhere needs to ignore the single-movie filter when populating the "Select movie sets" dialog. Not sure if the same query is used for the "Select movie set" dialog as it is elsewhere, which would complicate the change.

...where can i find the "Select movie sets" dialog ? i want to check if #17865 needs adjustment
