### ISSUE TITLE
 Amazon Fire TV 4k and Kodi 18.2-RC1: Crash at startup

### ISSUE THREAD

**Issue by Krawei** [xbmc/xbmc#15815]
## Bug report
If you try to start kodi, the startup crashes and you'll find yourself back in the main Fire TV menu.

## Expected Behavior
Kodi should start normally and the user should be able to see the kodi menu.

## Actual Behavior
Kodi crashes after being started with no failure message,.

## Possible Fix
Wipe kodis' cache and data. You'll lost all your configuration and start with a blank kodi.

### To Reproduce
1. Grab a Amazon Fire TV 4k Stick with FireOS 6.2.6.0
2. Install Kodi nightly
3. Configure it
4. Use it several times
5. Problem should appear after few days

### Debuglog
https://privatebin.net/?3d59b4a26f339272#dndUk2PtqUwmlcu4OjpmKaTEKH8RjT241m5ln0ORcHA=

## Additional context or screenshots (if appropriate)
@lrusak  Please take a look on my other issue #15039 : There was a lot of debugging regarding this other issue. Please take a look on our results, it should be re-opened.

### Your Environment
Used Operating system:
 - [x] Android
- Operating system version/name: Fire OS 6.2.6.0 (NS6260/1840)
- Kodi version: 18.2-RC1 Git:20190319-76db73d102

**Comment by M2k80** [comment]
Profile.xml is corrupted I think its 0 byte.
Same happens sometime to guisettings.xml if a device will powered off when kodi is running.

**Comment by divadkha** [comment]
I'm also getting the same issue on my Bravia Android TV. My power supply needs to be replaced and will completely shut off at times. This last time that it happened, opening Kodi would load but always crashes right before showing the dash. Clearing cache for the app does not work either.

Deleting profile.xml and guisettings.xml got it to work again. And, as M2k80 mentioned, both of those files had a size of 0 byte, which suggests that they went corrupt when powered off incorrectly.

**Comment by nuwonda** [comment]
last working build for fire tv basic is:
kodi-20190523-3bb5115b-master-armeabi-v7a.apk dated May 24th (build from 23rd)

any build after that keeps crashing immediately back to Fire TV home menu after the "clearing cache" followed by "preparing for first launch..." message disappears.

reinstalling the kodi-20190523-3bb5115b build will work, so it must be a change from this build to the one after that that broke it

**Comment by Krawei** [comment]
FIrst of all: Thanks for your great information and hints.

I could be the issue with corrupted files after power shutdown.

My current workaround is to close kodi before shutting down the fire tv's power circle.

@nuwonda Do you have an own issue created regarding your problem? I would like to see the developers reaction to it.

Nevertheless, I think we can close my issue here.

Thanks for your great support, folks :).
