### ISSUE TITLE
PVR - Deleting timer rule infers deletion of child timers

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#15812]
### Describe the bug
Here is a clear and concise description of what the problem is:

The dialog when reading a timer rule reads as follows: "Are you sure you want to delete this timer rule and all timers it has scheduled?"

This infers that the PVR backed acts in this manner. It would not be the case for pvr.vuplus.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The timer type should be able to specify if child timers would be deleted or not.

## Actual Behavior

Only the timer rule would be deleted on pvr.vuplus but the child timers would not be.

## Possible Fix

Add a timer type flag for "DELETES_TIMER_RULE_CHILDREN" or "ONLY_DELETES_TIMER_RULE" to allow the dialog to display the correct text.

### To Reproduce

1. Create an auto guide based timer rule for pvr.vuplus
2. Wait 30 minutes for timers to be generated
3. Delete the timer rule and the observe that the child timers still exist

### Debuglog

The debuglog can be found here:

Not applicable here. 

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [x ] OSX
 - [ ] Raspberry-Pi
 - [ x] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreElec 9 (RPi/Intel), Windows 10, OSX High Sierra
 - Kodi version: 18.2 RC

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
> This infers that the PVR backed acts in this manner. It would not be the case for pvr.vuplus.

 I would say, the addon should handle this and delete the children. I don't want to introduce API support (and corresponding PVR core code) to handle each and every possible behavior of the several today and future backends, tbh. The addon is ment to be an adapter between Kodi and the backend.

**Comment by phunkyfish** [comment]
Understood. I just spotted it today and now I'm trying to think of a situation where this shouldn't be the expectation but I can't ;)

**Comment by ksooo** [comment]
Yeah, for me this should feel the same as deleting a file folder...
