### ISSUE TITLE
Remove `porn/bukkake` from demo script

### ISSUE THREAD

**Issue by bigretromike** [xbmc/xbmc#15820]
Could someone remove porn related text in demo ?:-)
https://github.com/xbmc/xbmc/blob/a19fb7e999c917227fdf496bc047fe9f6e3a5dbb/addons/metadata.demo.movies/demo.py#L60

Some probably like `bukkake`, but probably not some youngster that want to learn something :-)

**Comment by pkerling** [comment]
I'll let our official porn advisor handle this

**Comment by bigretromike** [comment]
thanks, I read about how what team-kodi thinks about porn related things, so it was ironic that someone left that in demo-script. 
Happy bukkake guys

**Comment by notspiff** [comment]
just having my fun, thanks for reporting :+1:

**Comment by bigretromike** [comment]
https://github.com/xbmc/xbmc/blob/c5fb63bc42c8492a56ad6e9ecf6158585a7bfb06/addons/metadata.demo.tv/demo.py#L59
https://github.com/xbmc/xbmc/blob/c5fb63bc42c8492a56ad6e9ecf6158585a7bfb06/addons/metadata.demo.tv/demo.py#L70

Also :-) 
Someone loving bukkake, pm/dm me some cools sites 
Easter egg ?
