### ISSUE TITLE
Won't autoload subtitles if in RAR file or IDX+RAR

### ISSUE THREAD

**Issue by Sopor** [xbmc/xbmc#15824]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi won't autoload sub/idx subtitle files in RAR (compression stored). If i unpack the subtitle so instead of one rar file i have idx + rar (sub) it will crash Kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should autoload the subtitle. It is working in Kodi 17.6.

## Actual Behavior

In Kodi 17.6 it will ask you if you want to unpack big files (if the subtitle file is bigger than a certain size) and when i press Yes it will unpack the sub/idx files, but in Kodi 18.2-RC1 Git:20190326-2bc5c9ba29 it will either ask or load the subtitles from the Subs folder.
If i manually select the subtitle file it will load but without any unpack big files requester as it do in Kodi 17.6.
I have tried with smaller sub/idx files too and they won't autoload either if the files are in a RAR file.

## Possible Fix

To make it work i need to unpack the subtitle so i have one idx and one sub file only.

### To Reproduce

1. Start a video with a sub/idx subtitle in a stored RAR file.
2.
3.

### Debuglog

The debuglog can be found here:
[kodi-rar.log](https://paste.kodi.tv/oxijubixej.kodi)

[kodi-rar+idx.log](https://paste.kodi.tv/ohilowifuy.kodi)

Do you want the dmp file too?

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64
 - Kodi version: Kodi 18.2-RC1 x64 Git:20190326-2bc5c9ba29

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Sopor** [comment]
18.2 seems to load those subtitles now but if i press the `Browse subtitle` Kodi crash. So it seems that i need to create a new issue ...

**Comment by Sopor** [comment]
Kodi will still crash with idx + rar (sub).

**Comment by Sopor** [comment]
It seems that i can't even open the folder where the idx + rar (sub) are. If i disable Archive and RAR support it won't crash but it won't load the subs either.

If i enable Archive support it crash but if i only enable RAR archive support it seems to not crash and the subtitle will also load as it should.

**Comment by notspiff** [comment]
i need the archive used.

**Comment by Sopor** [comment]
@notspiff [idx + rar (sub)](https://github.com/xbmc/xbmc/files/3224029/tgtbatu.zip)

If i only have RAR archive support installed it won't auto-load the subtitle if it is in [RAR](https://github.com/xbmc/xbmc/files/3224046/tgtbatu.subs.zip)

Github only supports ZIP files ...

**Comment by Sopor** [comment]
I have tested it with latest vfs.rar (2.0.8) and it still won't autoload subtitles :(

**Comment by jonathanbower** [comment]
I can confirm this issue, would be nice to have fixed.

**Comment by DaveTBlake** [comment]
Fixed by #18202
