### ISSUE TITLE
Using Git Browser to add a zip, keep having an error message after download

### ISSUE THREAD

**Issue by allo1234567** [xbmc/xbmc#15829]
### Describe the bug
I've installed Indigo and Git Browser Addons in order to install a zip file (https://github.com/dualB/DepotQuebec). Adding from repository did not work and since it's my firestick, I don't know how to install the zip in any other way. 

So I do a search with the user name : dualB    and I can find the repo. Once i launch the download, I see the progress bar, it finished but then have the error message: Git Browser error... 
I don't know what to do... 

This is my log : 
https://paste.ubuntu.com/p/QXBKSc3Yhj/

Thank you guys ! 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MartijnKaijser** [comment]
Not supported
