### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [xbmc/xbmc#15837]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [CSimpleFileCache](https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/filesystem/CacheStrategy.cpp#L49)
- [Dataset](https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/dbwrappers/dataset.cpp#L71)

**Comment by pkerling** [comment]
PR welcome - not an actual issue, so closing. Thanks for the suggestion though.
