### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [xbmc/xbmc#15836]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [CGUIFontTTFDX](https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/guilib/GUIFontTTFDX.cpp#L39 "Destructor for CGUIFontTTFDX")
- [CLinuxRendererGL](https://github.com/xbmc/xbmc/blob/e759ef620c108270753348ca409c76d19d2878fd/xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGL.cpp#L138 "Destructor for CLinuxRendererGL")
- [CXHandle](https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/platform/linux/XHandle.cpp#L56 "Destructor for CXHandle")

**Comment by fritsch** [comment]
PR welcome.

**Comment by pkerling** [comment]
Closing, not an actual issue. Thanks for the suggestion though. As @fritsch said, we welcome PRs in this regard.

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?
