### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [xbmc/xbmc#15838]
### Describe the bug
Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [CRecursiveMutex constructor](https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/threads/platform/RecursiveMutex.h#L30)
- [pthread_mutex_lock](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html "Lock a mutex.") ⇒ [COMXCoreComponent::GetInputBuffer](https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/platform/linux/OMXCore.cpp#L430)

**Comment by pkerling** [comment]
The pthread code will likely be replaced with C++11 threading soon-ish, so not a priority. PR welcome in the meantime. Not an actual issue, so closing. Thanks for the suggestion though.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by pkerling** [comment]
If someone is willing to do the work, sure :+1:

**Comment by ksooo** [comment]
> How do you think about to improve static source code analysis also for this software?

Sure, go ahead and come up with a PR, if you want to help us.

**Comment by elfring** [comment]
* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by pkerling** [comment]
We can continue this conversation after the first PR.

**Comment by elfring** [comment]
I am curious on how the support will evolve for recent software development tools around affected implementation details.
