### ISSUE TITLE
Show Multi-Episodes as one entry, not multiple

### ISSUE THREAD

**Issue by TheT113** [xbmc/xbmc#15846]
### Describe the bug
Here is a clear and concise description of what the problem is:

When a multi-episode file is scraped, it displays in Kodi as multiple episodes. This causes issues with Automatically play next, and makes it unclear that the episode you're about to watch is actually multiple episodes. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Have the single entry contain the information from all the relevant episodes, ie, display the episode title as "[Episode 1], [Episode 2]". Place the episode descriptions in the box together with a paragraph break between them. Display the episode number as it should be, ie "1x1-2".

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Current version as of 3/30/2019.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Don't you think that this is more a feature request instead of a bug report and that shouldn't be better placed here: https://forum.kodi.tv/forumdisplay.php?fid=9

As this behaviour is actually correct by design, AFAICT
