### ISSUE TITLE
[skin.estouchy] Addon Shortcut #15 not displayed

### ISSUE THREAD

**Issue by DaedalusBLN** [xbmc/xbmc#15840]
# **Bug report** 

**Describe the bug** 

Here is a clear and concise description of what the problem is:

15th addon shortcut on Estouchy skin is not displayed.

**Expected Behavior**
Should display 3 rows of 5 items.

**Actual Behavior**
The 15th addon shortcut on this skin is not displayed. Should be 3 rows of 5 items, third row only shows 4. 

**To Reproduce** 

1. Launch Kodi.
2. Set skin to Estouchy.
3. Create 15 add-on shortcuts. 

**Debuglog** 

Not relevant. 

**Your Environment** 

Used Operating system:

- Android

Operating system version:
Oreo

Kodi versions:
17.6 and 18.1

**Comment by DaedalusBLN** [comment]
Template guidelines incorporated.

**Comment by ronie** [comment]
thanx for the report!

fix pending: https://github.com/xbmc/xbmc/pull/15842
