### ISSUE TITLE
Kodi should not play and rip audio CD at the same time

### ISSUE THREAD

**Issue by glaubersm** [xbmc/xbmc#15847]
### Describe the bug

Kodi allows us to play and rip an audio cd at the same time.
Obviously the audio becomes choppy when Kodi tries to do both tasks at the same time.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should stop disc playback before to start CD ripping proccess.

## Actual Behavior

Audio becomes choppy and CD ripping is very slow while Kodi plays and rips the disc at the same time.

### To Reproduce

1.  insert an audio cd and open Kodi
2. click "Disc" in the left side and "Play disc" button
3. while Kodi plays the audio CD, click "Rip audio CD" button

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
The problem with that one is, that there will not be a good solution for everyone.

You claim that it stutters if one plays a CD and rip it at the same time. The next user has 2 drives and simply is able to do exactly that. So I guess there will not be a good solution. Simply make sure you stopped the playback before ripping or wait until the ripping process is finished before you start the playback.

**Comment by glaubersm** [comment]
Kodi should only stop the playback of the same cd that the user starts to rip.

**Comment by DaVukovic** [comment]
Yes, I understand what you are asking for. AFAICS there's nothing built in to achieve that. As we have to think of 2 cases now.

Case 1: 
User listens to a CD and starts ripping it -> CD needs to be stopped before ripping

Case 2:
User starts ripping a CD and during the ripping process the user starts the playback -> playback shouldn't be possible during the ripping process. 

So we need to check for 2 cases. First case is if the player plays an audioCD and the 2nd case is if the system does some ripping currently. There's no boolean condition currently built-in which does those checks. So we have to add them. 

Just saying that it's probably not a simple fix (at least not for me ;) )

**Comment by malard** [comment]
This is a user driven error and the user can resolve this with a change in behaviour, if someone wishes to submit a PR with associated settings entries then feel free, however closing this as I don't feel its a useful focus for the team

**Comment by Pwnbroker** [comment]
I've found if you go into settings/player/discs and set Audio CD Insert Action to Rip, it will not play upon loading the CD, and will rip much faster.  This is on Windows 11.
