### ISSUE TITLE
Kodi starts fail

### ISSUE THREAD

**Issue by hungpham2411** [xbmc/xbmc#15844]
[kodi_crashlog-20190331_025525.log](https://github.com/xbmc/xbmc/files/3025903/kodi_crashlog-20190331_025525.log)

### Describe the bug
Here is a clear and concise description of what the problem is:

When I start kodi, it closes after a few seconds. Then I try to start in terminal to see what happened:

> libva info: VA-API version 1.1.0
> libva info: va_getDriverName() returns 0
> libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
> libva info: Found init function __vaDriverInit_1_0
> libva info: va_openDriver() returns 0
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  No splash image found
> Aborted (core dumped)
> find: ‘/home/myuser/.gvfs’: Permission denied
> find: ‘/home/myuser/.dbus’: Permission denied
> Crash report available at /home/myuser/kodi_crashlog-20190331_025525.log

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Start normally

## Actual Behavior

Kodi crash after few seconds start, nothing appears except a transparent background

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04 LTS
 - Kodi version: Krypton, maybe found in crash log for exact

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
No further response, no clean logfile. Issue closed
