### ISSUE TITLE
TMDB language code incorrect for simplified Chinese

### ISSUE THREAD

**Issue by RuralHunter** [xbmc/xbmc#15852]
### Describe the bug
See the detail in https://forum.kodi.tv/showthread.php?tid=329639
I posted the issue in the forum one year ago but it seems no one cares to fix this simple problem. 
The problem itself is very simple that "zh-cn" language code Kodi uses is just not supported by TMDB.  I put the log and analysis in the forum post. The Universal Scraper addon already fixed this one year ago.

## Possible Fix

Just change "zh-cn" to "zh" in label item 30002 in the file: addons/metadata.themoviedb.org/resources/settings.xml

### To Reproduce

1. Set language to "zh-cn" in the settings of TMDB addon.
2. Update any movie info from TMDB
3. Only English post image is fetched although there is Chinese version.

### Debuglog

The debuglog can be found here:
see the forum post.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP
I checked above marked platforms. But actually the problem is platform independent. 

 - Operating system version/name:
 - Kodi version:
18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@Rechi 

Probably better suited in repo-scrapers

https://github.com/xbmc/repo-scrapers/issues
