### ISSUE TITLE
xbmc.getRegion("time") returns bad format

### ISSUE THREAD

**Issue by deadlocker8** [xbmc/xbmc#15862]
### Describe the bug
Here is a clear and concise description of what the problem is:  
When choosing a time format in the regional settings that consists of more than one letter for the hours (e.g. `HH:mm:ss`) a call to `xbmc.getRegion("time")` returns a bad format string.
Example:
Time format in regional settings:  `HH:mm:ss`
Returned format string: `%H%H:%M:%S`

## Expected Behavior
Calling  `xbmc.getRegion("time")` should return a valid format string even if the time format set in the regional settings contains more than one letter for the hour part.

Time format in regional settings:  `HH:mm:ss`
Expected format string: `%H:%M:%S`

## Actual Behavior
Time format in regional settings:  `HH:mm:ss`
Returned format string: `%H%H:%M:%S`

The original letters `H` get both replaced by the format directive `%H` which leads to a duplication of the format directive `%H`.

### To Reproduce
1. Go to regional settings
2. Choose a time format that includes two letters for the hours part (e.g. `HH:mm:ss`)
3. Call `xbmc.getRegion("time")`

### Debuglog
The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [X] Windows UWP

 - Operating system version/name: Windows 10 (1809)
 - Kodi version: 18.1 (Git: 20190217-8cfdc895f3)

- Operating system version/name: ibreELEC Offical 9.0.1 (Kernel 4.19.23)
 - Kodi version: 18.1 newclock5_18.1-LEIA Compile Date: 21.02.19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by mglae** [comment]
A work around:
```
xbmc.getRegion('time').replace('%H%H','%H').replace('%I%I','%I')
```
The bug does exist in older Kodi versions too. It's maybe a good idea to only do the fix in V19 and just document it for older versions.

**Comment by ronie** [comment]
can confirm.

https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/legacy/ModuleXbmc.cpp#L450-L458

**Comment by dagwieers** [comment]
IMO this needs to be backport to Kodi v18.6 asap.

**Comment by sarbes** [comment]
Fixed.
