### ISSUE TITLE
Parental controls: Restrictions contents based on its age rating

### ISSUE THREAD

**Issue by amirrammari** [xbmc/xbmc#15866]
## Bug report
Hello
Parental controls feature allow parents to set controls on their children's use.
Please add a feature to block content based on its age rating. (like iTunes store)
![iTunes Restrictions Preferences](https://user-images.githubusercontent.com/23485114/55659897-e242d180-5818-11e9-845e-5e19f488eb85.png)

### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@amirrammari 

Sorry but Git Issues are exclusively for reporting bugs.

Please post your **Feature Request** in the Kodi forum
