### ISSUE TITLE
[Retroplayer] Kodi crashes when starting a Nintendo 64 game

### ISSUE THREAD

**Issue by meigele** [xbmc/xbmc#15874]
### Describe the bug
When I go to the games section of Kodi, choose a Nintendo 64 game and an emulator afterwards, the screen turns black and Kodi crashes after maybe a second.

## Expected Behavior
Kodi doesn't crash and starts playing the Nintendo 64 game.

## Actual Behavior
Kodi crashes.

### To Reproduce
1. Go to "games"
2. Choose a Nintendo 64 game (for me it's with any N64 game)
3. Choose an emulator

### Debuglog
The debuglog can be found here:
[https://paste.kodi.tv/umofuzoray.kodi](https://paste.kodi.tv/umofuzoray.kodi) (on Kodi 18.0)
[https://paste.kodi.tv/umefadumiw.kodi](https://paste.kodi.tv/umefadumiw.kodi) (on Kodi 18.1)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
The crash happens with any N64 game I have. Try for example: [https://github.com/meeq/FlappyBird-N64](https://github.com/meeq/FlappyBird-N64).
Other emulators work well so far (like Gameboy, ...)

### Your Environment
 - Operating system version/name: Windows 10 Education (1809)
 - Kodi version: ~~18.0~~ 18.1

**Comment by lrusak** [comment]
Kodi doesn't support games that require an OpenGL context at this time. So N64 isn't currently possible (along with dreamcast and some others).

**Comment by TheCherry** [comment]
Why then the status in the wiki on "done"? https://kodi.wiki/view/Game_add-ons
I looking forward for to this.

**Comment by lrusak** [comment]
> Why is then the status in the wiki on "done"? https://kodi.wiki/view/Game_add-ons
> I looking forward to this.

because the add-on is there, it just doesn't work yet because changes are needed in Kodi's retroplayer

**Comment by ccope** [comment]
Does https://github.com/xbmc/xbmc/pull/15610 mean that these emulators should work on v19 now?

**Comment by lrusak** [comment]
> Does #15610 mean that these emulators should work on v19 now?

Nope

**Comment by jachin99** [comment]
Does adding angle support for flycast and Mupen64Plus Next get Kodi any closer to fixing n64 or Dreamcast support?

**Comment by lrusak** [comment]
> Does adding angle support for flycast and Mupen64Plus Next get Kodi any closer to fixing n64 or Dreamcast support? https://www.libretro.com/index.php/retroarch-1-8-3-released/

Nope, sorry.

**Comment by garbear** [comment]
I'm going to close this issue as completed, due to https://github.com/xbmc/xbmc/pull/26091 fixing the crash when starting an N64 game. After that PR, Kodi will show a helpful error message explaining the problem, and there's no more crash:

![Screenshot 2024-12-14 at 3 50 03 PM](https://github.com/user-attachments/assets/7ad39448-9fad-48c6-9281-743e4c32d80b)

The actual "it plays a game" fix will come with full GL support. We can continue that aspect of this issue in the GL tracking thread, https://github.com/xbmc/xbmc/issues/17743.
