### ISSUE TITLE
Kodi Leia dropping frames in HD videos

### ISSUE THREAD

**Issue by AMKnock** [xbmc/xbmc#15871]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a problem with HD videos on Leia on my Android TV box. Picture tends to tear or stutter quite a bit because looking at the debug info on the screen I see that frames drop a lot (very rarely are they around 59-60 FPS) on HD videos.
Playing SD videos with hardware acceleration turned off plays without a hitch.

I tried out an earlier version of Kodi Krypton and I don't have that problem with HD videos.

Here is the Kodi Krypton log:
https://hastebin.com/mugowonape.sql

And here are two Kodi Leia logs:
one is with Media Codec turned on:  https://hastebin.com/icepepedux.sql  (here the video is completely unwatchable, it's tearing non-stop)
and this one is with Media Codec (Surface) turned on: https://hastebin.com/awoyehefan.sql (more watchable, but tearing is still noticeable and distracting)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Less (or none at all) frame drops. They should stick around 60 FPS.

## Actual Behavior

Frame drops causing video to not play smoothly.

## Possible Fix

Seeing as it worked fine on Krypton, the frame drop issue is not related to AMCodec so I guess it can be fixed on Leia.

### To Reproduce

1. Play any HD content (1080p, 4k, even 720p)
2. Activate debug log and watch the fluctuation in FPS
3. Also notice tearing during video playback.

### Debuglog

The debuglog can be found here:

Two Kodi Leia logs (the first one with Media Codec turned on,  the second one with Media Codec Surface
https://hastebin.com/icepepedux.sql
https://hastebin.com/awoyehefan.sql

Kodi Krypton log with normal playback and pretty much constant 60FPS playback:
https://hastebin.com/mugowonape.sql

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 7.1.2
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
The Moderators have determined that [Banned_addons](https://kodi.wiki/view/Banned_addons) are present on your system. To receive assistance here, these banned items must be removed. If a clean log is not submitted within 3 days, this issue will be closed.

**Comment by AMKnock** [comment]
Okay, I submitted new clean logs in my original post.
