### ISSUE TITLE
xbmc.getRegion('dateshort') returns a bad format

### ISSUE THREAD

**Issue by jmooremcc** [xbmc/xbmc#15876]
### Describe the bug
Here is a clear and concise description of what the problem is:

A European user uses a Central Europe Region Default Format
He uses a single digit Short Date Format: day.month.year
He uses h:mm:ss xx  as the Time Format
The following code produces an exception:
`dateformat = xbmc.getRegion('dateshort') + " %I:%M %p"

liDateTime = datetime.strptime(xbmc.getInfoLabel('Listitem.Date'), dateformat)
`
The above code causes an exception because of the bad date format returned by the xbmc.getRegion function.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expected the format returned by xbmc.getRegion('dateshort') to be: "%d.%m.%Y"
which works correctly.

## Actual Behavior

The date format returned by xbmcgetRegion() is "%-d.%-m.%Y "
The error it produces is:
 '-' is a bad directive in format '%-d.%-m.%Y %I:%M %p'
which causes an exception when you use it to convert to a datetime object.

## Possible Fix

The following code fixes the format:
`dateformat = dateformat.replace('-', '')
`

### To Reproduce

1. Set the short date format to day.month.year
2. Use xbmc.getRegion('dateshort') to retrieve the date format
3. Use the dateformat from step 2 in the following code:
`datetime.strptime(xbmc.getInfoLabel('Listitem.Date'), dateformat)`

### Debuglog

The debuglog can be found here:
https://pastebin.com/embed_js/1KpHQ6Mh

Goto 22:45:05.668 in the debug log to see the error message.
I'm applying the suggested fix to keep the add-on from crashing.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X ] Linux
 - [ ] OSX
 - [ X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC (official): 8.2.5, kernel: Linux ARM 32-bit version 4.9.80

 - Kodi version: 17.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
17.6 is end of life. Can you confirm the issue also occurs in Leia?

**Comment by jmooremcc** [comment]
Yes. A user of my add-on in central Europe running Leia first brought it to my attention. I didn't realize what version of Kodi he was running until he submitted a full debug log after I posted this bug report.

**Comment by mglae** [comment]
IMO it's a feature.

xbmc.getRegion() does return platform depended strftime() format strings:

https://github.com/xbmc/xbmc/blob/f2643566d0fe86534aa6732cc5c95ede220705c5/xbmc/interfaces/legacy/ModuleXbmc.cpp#L437-L443

The strftime() format strings are not supported by Pythons [strptime() implementation](https://github.com/python/cpython/blob/2.7/Lib/_strptime.py) and must be filtered.

The suggested fix fails on ISO date `%Y-%m-%d`, better use:
```
dateformat = dateformat.replace('%-', '%').replace('%#', '%') 
```

**Comment by jmooremcc** [comment]
There are legitimate date formats that use '-' characters. If that is the case, your suggested fix would create an invalid format that would fail. 

If the format on the Regional Format page in the settings menu does not show '-' characters, the format string returned by getRegion() should not contain any '-' characters.
If the format on the Regional Format page in the settings menu does show '-' characters, the format string returned by getRegion() should contain '-' characters.

IMO, the C++ code above is incorrect. I'm sure someone may have had a good reason for doing what they did at the time, but under the current versions of Python, that code makes no sense and should be removed.

**Comment by mglae** [comment]
The code is used to i.e. differentiate between kodi internal formats DD.MM.YYYY (-> 01.01.2019) and D.M.YYYY (-> 1.1.2019).

Python's strftime() does accept the "%#d"/"#m" or "%-d"/"%-m" formats and I do not see any replacements for them.

**Comment by jmooremcc** [comment]
I understand your point. How about a compromise that will make getRegion friendly for use with strptime. My recommendation would be to pass a parameter like "p" to getRegion that would cause "%d" to be generated  instead of "%#d" or "%-d" and "%m" to be generated instead of "%#m" or "%-m". Doing this will make the function more add-on programmer friendly and eliminate the need for filtration.

**Comment by sarbes** [comment]
xbmc.getRegion returns a string influenced by settings. It is not suitable for parsing. Works as intended.
