### ISSUE TITLE
SSL Problems on Shield TV

### ISSUE THREAD

**Issue by sebastianhaba** [xbmc/xbmc#15875]
### Describe the bug
Here is a clear and concise description of what the problem is:
Plugins and repositories that use https are not working.

### To Reproduce
1. Clean Shield Experience Upgrade 7.2.3
2. Clean Kodi 18.1 from google play store
3. Add network location to file explorer with https. Try to open this location. 
4. Use any plugin that make request using ssl library.

### Debuglog
The debuglog can be found here:

ERROR: CCurlFile::FillBuffer - Failed: SSL connect error(35)
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                            - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                           Error Type: <class 'requests.exceptions.SSLError'>
                                           Error Contents: HTTPSConnectionPool(host='****', port=443): Max retries exceeded with url: /url (Caused by SSLError(SSLError(1, u'[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:726)'),))

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: AndroidTV
 - Kodi version: 18.1

**Comment by DaVukovic** [comment]
No full debug, no issue

closed
