### ISSUE TITLE
Choppy video 

### ISSUE THREAD

**Issue by soulterror** [xbmc/xbmc#15890]
### Describe the bug
Here is a clear and concise description of what the problem is:

Smooth video and audio 

## Actual Behavior

Hello

I have an Android box

Updated to Leia. 

Made sure all my add on were updated

Links load right away

Now.  When the video starts playing the auto track is perfect. You would think it’s working from the sound. 

But the video itself is all choppy. It’s hard to explain. It’s not exactly buffering because it never stops playing. It’s more like it plays every other frame rather then smooth and continuous 

This only seemed to start after updating 

I have tried several shows and several links. 

All of them do the exact same thing 

I cleared my cache. Check my internet connection. Went into the program add one and “ tweakEd it”

But it’s still the same. 

Can anyone tell me what’s going on. Thanks 

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

I don’t even know what a debuglog is. 

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I just want to be able to watch some tv
### Your Environment
Used Operating system:

 - [*] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 6.0.1
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by kib** [comment]
This is not a help forum, this is for reporting actual bugs. For help go to https://forum.kodi.tv and be sure to have a debug log ready.

**Comment by soulterror** [comment]
Ok. Sorry about that. 

Here’s the log of you want it

https://paste.kodi.tv/ahemopoheb
