### ISSUE TITLE
JSON-RPC API v10 Files.GetFileDetails not supporting plugin:// (plugin source)

### ISSUE THREAD

**Issue by bigretromike** [xbmc/xbmc#15897]
### Describe the bug
Sending JSONRPC request for file that was added with plugin source failed with `Invalid params`.
Files added with source plugin results in adding as:
`MyVideos<id>.db -> files.strFilename = plugin://plugin.video.nakamori/tvshows/98939/play, idPath = 2`
`MyVideos<id>.db -> path.idPath = 2, strPath = plugin://plugin.video.nakamori/`

Sending JSONRPC for file = strPath + strFilename, or file=strFilename both failes.

It looks like the function for this don't support anything that starts with `plugin://` (that what I assume) 
https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/FileOperations.cpp#L164

## Expected Behavior
Sending JSONRPC like this:
`{"jsonrpc":"2.0","method":"Files.GetFileDetails","params":{"file":"plugin://plugin.video.nakamori/tvshows/98939/play","media":"video","properties":["title"]},"id":1}`
should return valid response or invalid parms when the `file` is wrong

## Actual Behavior
Sending JSONRPC like on of those:
`{"jsonrpc":"2.0","method":"Files.GetFileDetails","params":{"file":"plugin://plugin.video.nakamori/tvshows/98939/play","properties":["title"]},"id":1}`
`{"jsonrpc":"2.0","method":"Files.GetFileDetails","params":{"file":"plugin://plugin.video.nakamori/tvshows/98939/play","media":"video","properties":["title"]},"id":1}`
`{"jsonrpc":"2.0","method":"Files.GetFileDetails","params":{"file":"plugin://plugin.video.nakamori/plugin://plugin.video.nakamori/tvshows/98939/play","properties":["title"]},"id":1}`
`{"jsonrpc":"2.0","method":"Files.GetFileDetails","params":{"file":"plugin://plugin.video.nakamori/plugin://plugin.video.nakamori/tvshows/98939/play","media":"video","properties":["title"]},"id":1}`

Results with
```
XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nakamori/tvshows/98939/play
2019-04-11 06:58:45.132 T:7068  NOTICE: {"error":{"code":-32602,"message":"Invalid params."},"id":1,"jsonrpc":"2.0"}
```

## Possible Fix
I have no idea about c++ but the fix would be add code to function to support this: https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/FileOperations.cpp#L164

### To Reproduce
1. use supported video plugin as library source
2. scan as local info (media scraper)
3. send jsonrpc with filepath take out of myvideo.db

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: KodiSetup-20190406-39c78c00-master-x64.exe (18.2 RC?)

**Comment by bigretromike** [comment]
dear bot, I included everything necessary for this issue. Hope it will be unmarked as "Ignored"

**Comment by bigretromike** [comment]
@rmrector Should I close this issue then, if by what we talk in PR `Files` command from `json-rpc` shouldn't handle files added by `plugin://` source to Library ?

**Comment by rmrector** [comment]
No, this is a valid issue and that PR #16087 has useful information for a future fix.

**Comment by bigretromike** [comment]
Anything I can do to move this forward. Without this feature adding video from plugin via new method is only one way, because there is no way to retrieve the information about added file from database.

**Comment by rmrector** [comment]
Like everything else around here, this needs development resources, someone to actually do the work and follow the code down to where plugin listing and other behavior diverge from other file system handling. Investigating this turned up plenty of other goofy behavior that needs addressed before a lot of folks start using this interface, which is more work yet and still requires someone to do the work.

> Without this feature adding video from plugin via new method is only one way, because there is no way to retrieve the information about added file from database.

This is not true. You can use methods in the `VideoLibrary` namespace to get information on library items, just like always.

**Comment by bigretromike** [comment]
@rmrector If I recall I tried most if not all jsonrpc calles, and non did work for items added from plugin source. because how you address it yourself `Investigating this turned up plenty of other goofy behavior` and one of it is not being able to get those items. 

But fell free to correct me, because it is the only thing that I'm missing to use it full potential.

**Comment by bigretromike** [comment]
Sorry, my bad. You are right on this one `VideoLibrary` I was trying to get information from Player that time, I totally missed `VideoLibrary` namespace. I'm unable to `filter` them by `uniqueid` that I injected there to know that those files are from source plugin, but other than that I can iterate over them.

**Comment by doko-desuka** [comment]
Is there any way I can get the "idFile" value of a file item whose path is "plugin://plugin.video.myplugin/?arg=bla.mp4"?  

I tried File.GetFileDetails:  
`r = xbmc.executeJSONRPC('{"jsonrpc": "2.0", "id": 1, "method": "Files.GetFileDetails", "params": {"file": "plugin://plugin.video.myplugin/?arg=bla.mp4", "media": "files", "properties": ["playcount"]}}')`

I also tried with the "media" param set to "video" but it gives the same error message, "Invalid params".  
Are there any work-arounds for the lack of being able to get the data from plugin-based file paths?

**Comment by doko-desuka** [comment]
@bigretromike could you please show me the call you used in here? https://github.com/xbmc/xbmc/pull/16087#issuecomment-498223906

**Comment by bigretromike** [comment]
> 
> 
> @bigretromike could you please show me the call you used in here? [#16087 (comment)](https://github.com/xbmc/xbmc/pull/16087#issuecomment-498223906)

You wont be able to do that. This is the whole issue here. I was able to do that with a custom build from my PR which was rejected https://github.com/xbmc/xbmc/pull/16087
The whole point is that you cannot access those files by giving them path with `plugin://` because its not supported by jsonrpc.

**Comment by doko-desuka** [comment]
I see. Thanks for explaining.  
I wish that such a thing was eventually implemented, because items with URLs using the `plugin://` protocol are often used by video add-ons that rely on resolving/fetching the media in some non trivial way (asking a server for it etc.), then starting playback with `xbmcplugin.setResolvedUrl()`.  
So this class of add-on has no way to manage the bookmarks, playcount etc. of its items using the JSON commands.
