### ISSUE TITLE
"Refresh" does not refresh codec information

### ISSUE THREAD

**Issue by JGoutin** [xbmc/xbmc#15896]
### Describe the bug

The "refresh" button in the "information" windows does not refresh codec information (`7.1`, `DOLBY-HD`, `1080 HD`, ...)

## Expected Behavior

Theses information should be updated when "refreshing" if the source file was updated (By example, replaced by a better quality version).

## Actual Behavior

"Refresh" only refresh informations from NFO and scrapers, but do not refresh codec information from media file itself.

I didin't find any easy way to refresh theses codec information, only workarounds like :
* Removed the video from the library
* Renamed the file on hard drive to a temporary name (To simulate file deletion).
* Cleaned the media library in options.
* Renamed back the file to its previous name.
* Scanned the video source to import the video back to the library.

### To Reproduce

1. Replace the file by another with different codec
2. click "Refresh"
3. See that codec information are same as previous file and not up to date.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/damipihago.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

The "Refresh" is "individual refresh" in doc : https://kodi.wiki/view/Updating_or_removing_videos#Individual_Refresh

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora 29
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by JGoutin** [comment]
Completed as best as possible.

**Comment by KarellenX** [comment]
> Should not be useful for this specific issue.
Yes it is. I could then see what version you are using then advise you if this PR applies...
https://github.com/xbmc/xbmc/pull/15589

I'll let you figure out if it applies.

**Comment by KarellenX** [comment]
There are also a number of threads on this topic in the forum. 

https://forum.kodi.tv/showthread.php?tid=342277&highlight=15589
https://forum.kodi.tv/showthread.php?tid=342320&highlight=15589
https://forum.kodi.tv/showthread.php?tid=337890&highlight=15589

**Comment by JGoutin** [comment]
Updated with debuglog.
>     * Kodi version: 18.1

Nice, if there is already a merged PR for the next version.

**Comment by KarellenX** [comment]
Your version is 20 February, and that PR was merged on 4 March.

Would you like to try a recent nightly? But I do have a suspicion the issue will still exist when refreshing from NFO files, 

The updated nightly will allow you to update the codec information by playing the video for a few seconds and will be a workaround if the Refresh option does not work.

**Comment by JGoutin** [comment]
Personally, I can wait the full release, this machine is under Fedora, there is no Nightly pre-build package for it and I prefer avoid to install all the requirements packages on it.

I can therefore install the Nightly build on another machine (Under windows) and do some tests on this if that can help (Using Refresh option and few second playback workaround).
I mainly reported this to help improve this nice project.

**Comment by KarellenX** [comment]
Thanks. That will certainly help if you are able to provide feedback from your Windows install.

**Comment by JGoutin** [comment]
Tested today with Nightly 2019/05/07 46b6abdf on Windows 10 64Bits.

Using a 1080p movie on the library (With correct information on Kodi).

- Replaced the file by a 4K movie.
- Used "Refresh" button on Kodi: Movie still show as 1080p.
- Played the film one second: Movie correctly updated as 4K.
- Restored the original file.
- Used "Refresh" button on Kodi: Movie still show as 4K.
- Played the film one second: Movie correctly updated as 1080p.

Sorry for the delay, I was a little busy last weeks.
