### ISSUE TITLE
[VideoPlayer] multithreaded AV1 SW decoding does not work / always falls back to a single thread

### ISSUE THREAD

**Issue by 5schatten** [xbmc/xbmc#15893]
### Describe the bug

When no HW decoder is available Kodi should fall back to SW decoding and use an appropriate amount of cores to do this. While testing the new dav1d release for LE https://github.com/LibreELEC/LibreELEC.tv/pull/3411 I've seen stuttering playback on my J3455-ITX system when playing this test file http://download.opencontent.netflix.com.s3.amazonaws.com/AV1/Chimera/Chimera-AV1-8bit-1920x1080-6736kbps.mp4

## Expected Behavior
According to this https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp#L359 Kodi should at least try multi threaded software decoding before falling back to single threaded decoding.

## Actual Behavior

If now HW decoder is available it skips checking if mt SW decoding is possible and start single threaded which leads to stuttering on low end systems.

## Possible Fix
I changed this block:

```
// setup threading model
  if (!(hints.codecOptions & CODEC_FORCE_SOFTWARE))
  {
    if (m_decoderState == STATE_NONE)
    {
      m_decoderState = STATE_HW_SINGLE;
    }
    else
    {
      int num_threads = g_cpuInfo.getCPUCount() * 3 / 2;
      num_threads = std::max(1, std::min(num_threads, 16));
      m_pCodecContext->thread_count = num_threads;
      m_pCodecContext->thread_safe_callbacks = 1;
      m_decoderState = STATE_SW_MULTI;
      CLog::Log(LOGDEBUG, "CDVDVideoCodecFFmpeg - open frame threaded with %d threads", num_threads);
    }
  }
  else
    m_decoderState = STATE_SW_SINGLE;
```
to this

```
int num_threads = g_cpuInfo.getCPUCount() * 3 / 2;
      num_threads = std::max(1, std::min(num_threads, 16));
      m_pCodecContext->thread_count = num_threads;
      m_pCodecContext->thread_safe_callbacks = 1;
      m_decoderState = STATE_SW_MULTI;
      CLog::Log(LOGDEBUG, "CDVDVideoCodecFFmpeg - open frame threaded with %d threads", num_threads);
```

and the test file played fine, ofc this is not a proper fix but points to the right direction. As @lrusak suggested I tried to disable vaapi acceleration & played some h264 files which were fine. And used the right amount of cores:

`2019-04-09 19:38:17.830 T:140352686126848   DEBUG: CDVDVideoCodecFFmpeg - open frame threaded with 6 threads`

So it is somewhat specific for this new video format?

### To Reproduce

1. Install this image https://forum.kodi.tv/showthread.php?tid=298462&pid=2844220#pid2844220
2. Play some AV1 media on non-AVX low-end systems.

### Debuglog

The debuglog can be found here:

https://pastebin.com/kQvSZDM2
https://pastebin.com/KFigfyq2

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.1
- latest LibreELEC master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Please try: http://paste.ubuntu.com/p/qqwWZXbphG/

This might make it work, but I don't fully understand the old logic.

Above pastebin just falls back to multi threaded decoding by default - I have something in mind for "single threaded" thumb extraction, but let's see.

**Comment by FernetMenta** [comment]
> This might make it work

it does not make it work but it breaks thumb extraction

**Comment by FernetMenta** [comment]
Does team kodi now accept bug reports for modified code? current master has no support for av1. supported codecs are working correctly.

**Comment by lrusak** [comment]
> Does team kodi now accept bug reports for modified code? current master has no support for av1. supported codecs are working correctly.

This is not specific to AV1. It will happen for any codec that doesn't have a hw decoder available.

**Comment by FernetMenta** [comment]
I just tried with h264 and sw decode runs mutlithreaded.

**Comment by lrusak** [comment]
> I just tried with h264 and sw decode runs mutlithreaded.

Do you have an h264 decoder available? It work properly if the HW decoder is available but disabled in kodi.

**Comment by FernetMenta** [comment]
> Do you have an h264 hw decoder available?

yes and no (vtb i.e. won't take interlaced)

I suggest that you file a bug with a supported codec and describe a way how to reproduce.

**Comment by lrusak** [comment]
> > Do you have an h264 hw decoder available?
> 
> yes and no (vtb i.e. won't take interlaced)
> 
> I suggest that you file a bug with a supported codec and describe a way how to reproduce.

VTB doesn't have a VP8 or VP9 decoder so the issue should be present when trying those codecs

**Comment by FernetMenta** [comment]
wrong

**Comment by lrusak** [comment]
> wrong

which part?

**Comment by fritsch** [comment]
Asked differently: Why does it work for VP9 but not for AV1? From the code it "seems" that it only takes the multithreaded path whenever it falls back, which means the the state was at least ones not HW_STATE_NONE

**Comment by FernetMenta** [comment]
> which part?

the entire bug report.

I doubt you can construct a case with unmodified code that fails.

I had vtb enabled:

```
2019-04-10 20:55:46.216 T:123145476927488  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: Google VP9
2019-04-10 20:55:51.682 T:4506498496   DEBUG: ------ Window Init (DialogBusy.xml) ------
2019-04-10 20:55:51.682 T:4506498496   DEBUG: Window DialogBusy.xml was already loaded
2019-04-10 20:55:51.682 T:4506498496   DEBUG: Alloc resources: 0.01ms
2019-04-10 20:55:51.682 T:123145476927488   DEBUG: CDVDVideoCodecFFmpeg - open frame threaded with 12 threads
2019-04-10 20:55:51.683 T:123145476927488   DEBUG: CDVDVideoCodecFFmpeg - Updated codec: ff-vp9
```

**Comment by lrusak** [comment]
> > which part?
> 
> the entire bug report.
> 
> I doubt you can construct a case with unmodified code that fails.

ffmpeg was just built with AV1 support that's all.

> I had vtb enabled:

was `CDVDVideoCodecFFmpeg::Open()` called twice? or how did you get out of the `STATE_NONE`?

**Comment by FernetMenta** [comment]
> was CDVDVideoCodecFFmpeg::Open() called twice? 

that's the design. the only reason I can think of why it fails for av1 is that this codec does not call get_format

as long as there is no supported codec that does not call get_format, this bug report is invalid. in case you follow your own rules :)

**Comment by popcornmix** [comment]
I seem to recall dvdec.c and rv34.c don't call get_format and are supported kodi codecs.

**Comment by lrusak** [comment]
shouldn't `GetFormat` always be called? https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/decode.c#L1357

**Comment by FernetMenta** [comment]
I think it should but I doubt av1 does. I suggest to ask ffmpeg devs about the strategy here

**Comment by lrusak** [comment]
This patch seems to fix it so it is indeed an issue with the codec itself. https://termbin.com/ve8g

**Comment by lrusak** [comment]
http://ffmpeg.org/pipermail/ffmpeg-devel/2019-April/242484.html

**Comment by fritsch** [comment]
That came back as a boomerang: http://ffmpeg.org/pipermail/ffmpeg-devel/2019-April/242485.html - relying on getFormat for swdecoders is wrong, they say.

**Comment by FernetMenta** [comment]
How should a client app like Kodi know if the selected codec is a swdecoder? Does the absence of hwaccels make a decoder a swdecoder. Again, how should a client app know. Will they call get_format once av1 gets supported by hw? The fact that threading can't be changed once initialized makes it already hard for clients. Maybe they should start consuming their own API :)

**Comment by fritsch** [comment]
I asked on the ML - let's see.

**Comment by fritsch** [comment]
http://ffmpeg.org/pipermail/ffmpeg-devel/2019-April/242512.html <- hard coding we must?

**Comment by rozhuk-im** [comment]
Why this is closed without fixing problem?!

**Comment by fritsch** [comment]
Because it's not a defect but a PR which would  introduce errors.

If you have a valid fix, please provide it.

rim <notifications@github.com> schrieb am Sa., 26. Okt. 2019, 08:07:

**Comment by rozhuk-im** [comment]
kodi does not play most av1 videos just because it set only one thread to decode, why this is not defect?

IMHO algo/solution from https://github.com/mpv-player/mpv/blob/c184e290b0f7bbf9eb8a87c9e87c9aa870ca2c3f/video/decode/vd_lavc.c should be ported.

**Comment by fritsch** [comment]
Port it! Go ahead - what is blocking you?

**Comment by fritsch** [comment]
Lol - after reading your code. I am quite sure you don't know what you just posted ...

**Comment by fritsch** [comment]
```
diff --git a/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp b/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp
index 3b5d1756d7..c52c18f2e3 100644
--- a/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp
+++ b/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp
@@ -355,10 +355,13 @@ bool CDVDVideoCodecFFmpeg::Open(CDVDStreamInfo &hints, CDVDCodecOptions &options
   m_pCodecContext->get_format = GetFormat;
   m_pCodecContext->codec_tag = hints.codec_tag;
 
-  // setup threading model
+  bool isSWCodec = false;
+  if (hints.codec == AV_CODEC_ID_AV1)
+    isSWCodec = true;
+
   if (!(hints.codecOptions & CODEC_FORCE_SOFTWARE))
   {
-    if (m_decoderState == STATE_NONE)
+    if (m_decoderState == STATE_NONE && !isSWCodec)
     {
       m_decoderState = STATE_HW_SINGLE;
     }
```

Try that. If ffmpeg people want us to use a white / blacklist. This should do it, without breaking thumb extraction.

**Comment by fritsch** [comment]
Works:
```
2019-10-26 13:18:12.529 T:9391  NOTICE: Creating video codec with codec id: 32797
2019-10-26 13:18:12.529 T:9391  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: libaom AV1
2019-10-26 13:18:12.529 T:9391   DEBUG: CDVDVideoCodecFFmpeg - open frame threaded with 12 threads
2019-10-26 13:18:12.529 T:9391    INFO: ffmpeg[0x55661f38df70X]: [libaom-av1] v1.0.0
2019-10-26 13:18:12.529 T:9391   DEBUG: CDVDVideoCodecFFmpeg - Updated codec: ff-libaom-av1
```

**Comment by FernetMenta** [comment]
Night work Most of the time but implementation is Bad

**Comment by fritsch** [comment]
Jep, I fully agree. Do you have a hint for a better approach?

**Comment by FernetMenta** [comment]
Currently it starts single-threaded and does a reinit if there is no hw decoder. Change it to multi-threaded as default and reinit if there is a hw decoder found working in get_format().

**Comment by fritsch** [comment]
Thank you, that makes sense. I will implement it next week.

**Comment by rozhuk-im** [comment]
@fritsch any progress with av1 multi-thread?

**Comment by fritsch** [comment]
No - go ahead with your contribution.

Having small "things" that currently use my time :-)

**Comment by sfxworks** [comment]
Hi - 
Was there ever a PR for this? Youtube uses VP9 for anything beyond 1080p now and I am trying to get at least 1440p to run smoothly. Almost made it with overclocking but I see it only using a single core.

**Comment by fritsch** [comment]
No, feel free to go ahead and submit it.

**Comment by sfxworks** [comment]
Thanks for the update. I'll do my best. Though, I am a bit of a novice when it comes to C so it may take a bit. I'll be referencing https://github.com/xbmc/xbmc/issues/15893#issuecomment-546592726 and the build instructions in hopes that is all that is needed.

**Comment by fritsch** [comment]
The code posted there was the "quick hack". A far better solution would be:

Open Decode multithreaded always, but not in case when we do thumbnail caching. IF a hw accel is available, reconfigure, else continue. That's the idea.

**Comment by sfxworks** [comment]
Ah understood. Unfortunentally, such a feature may be beyond my capabilities at this time. I will yield the floor to anyone else more capable for the PR and see about building that locally and learning from there.
