### ISSUE TITLE
Build error (undefined reference to 'Matrix4Mul(float*, float const*)')

### ISSUE THREAD

**Issue by tadaka9** [xbmc/xbmc#15895]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm trying to compile Kodi (master-branch, and 18.1) on a RK3399 board (RockPro64), I compile with: https://pastebin.com/2m2d6U5J and after make -j6 (i reach the 100% compilation step, but it fails with: undefined reference to " 'Matrix4Mul(float*, float const*)') "
or I compile with: 
cmake .. (and i reach 100% too, but it fails at the end with " undefined reference to 'Matrix4Mul(float*, float const*)') " and after " make -j6 " | " cmake --build . -- VERBOSE=1 -j6"
Operative System arch. is aarch64. 

This is the result:
build/rendering/gl/rendering_gl.a(MatrixGL.cpp.o):MatrixGL.cpp:function CMatrixGL::Ortho(float, float, float, float, float, float): error: undefined reference to 'Matrix4Mul(float*, float const*)'
build/rendering/gl/rendering_gl.a(MatrixGL.cpp.o):MatrixGL.cpp:function CMatrixGL::Ortho2D(float, float, float, float): error: undefined reference to 'Matrix4Mul(float*, float const*)'
build/rendering/gl/rendering_gl.a(MatrixGL.cpp.o):MatrixGL.cpp:function CMatrixGL::Frustum(float, float, float, float, float, float): error: undefined reference to 'Matrix4Mul(float*, float const*)'
build/rendering/gl/rendering_gl.a(MatrixGL.cpp.o):MatrixGL.cpp:function CMatrixGL::Translatef(float, float, float): error: undefined reference to 'Matrix4Mul(float*, float const*)'
collect2: error: ld returned 1 exit status
CMakeFiles/kodi.dir/build.make:526: set di istruzioni per l'obiettivo "kodi-x11" non riuscito
make[2]: *** [kodi-x11] Errore 1
make[2]: uscita dalla directory "/home/rock/kodi/build"
CMakeFiles/Makefile2:799: set di istruzioni per l'obiettivo "CMakeFiles/kodi.dir/all" non riuscito
make[1]: *** [CMakeFiles/kodi.dir/all] Errore 2
make[1]: uscita dalla directory "/home/rock/kodi/build"
Makefile:138: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expected to finish the build, also because i tried to edit the file MatrixGL.cpp changing code from:

#if defined(HAS_NEON) && !defined(__LP64__)
#include "utils/CPUInfo.h"
void Matrix4Mul(float* src_mat_1, const float* src_mat_2);
#endif

to:
void Matrix4Mul(float* src_mat_1, const float* src_mat_2);

in every place of file.
## Actual Behavior

I obtained the same behaviour.

## Possible Fix

I don't know right now.
### To Reproduce

0. https://pastebin.com/22L77dJ1 what packages I installed
1. Install Feature Complete Debian Desktop - First Release on a RockPro64 
2. git clone https://github.com/xbmc/xbmc kodi
3. mkdir kodi/build; cd kodi/build; cmake .. (or what i wrote before); make -j8

### Debuglog

The debuglog can be found here:
https://pastebin.com/jJxWZj6J < CMakeError.log
https://pastebin.com/z4FuMDKU < CMakeOutput.log

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I'm trying to make a .deb of Kodi 18 for the O.S. specified below.

### Your Environment
Used Operating system: https://github.com/mrfixit2001/debian_desktop/releases/tag/190315

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: https://github.com/mrfixit2001/debian_desktop/releases/tag/190315 < (this is the operative system that I'm using)
 - Kodi version:
master-branch, 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
You will most likely have to build for gbm or wayland and not for x11

add `-DCORE_PLATFORM_NAME=GBM` or `-DCORE_PLATFORM_NAME=WAYLAND` to your cmake command
