### ISSUE TITLE
Vertical scrolling on Android is inconsistent and barely works.

### ISSUE THREAD

**Issue by jungletek** [xbmc/xbmc#15907]
### Describe the bug
Using the latest version of Kodi for Android (and presumably this has been an issue with earlier versions), with the default shipped skin, attempting to scroll pages of content vertically is frustratingly almost broken. It seems the app always assumes you're trying to scroll horizontally because of the natural inaccuracy of human movement in general, and while using a touch-screen. Trying to swipe the screen upwards or downwards requires multiple attempts to get it to realize you want to go up or down, rather than scroll a horizontal element horizontally.

## Expected Behavior
If I swipe up or down, the screen should move accordingly, rather than ignoring that up/down movement and assuming that any horizontal 'jitter' while doing so means that I really wanted to scroll the content horizontally. In years and years of using various Android apps, I've never encountered such a frustrating and broken implementation.

## Actual Behavior
Seems I've already covered this, but if you need me to elaborate, I'd be glad to...

### To Reproduce
1. Go to a page/tab that has more content than can fit on the screen vertically. The movies or tv page/tab is a good example.
2. Swipe upward to try to scroll the page upward.
3. Be frustrated when the UI thinks you're trying to scroll horizontally instead, or trying to interact with a particular other UI element instead (i.e. the cover art of a movie or tv show in a horizontally scrolling sub-element like 'recently added', etc.)
4. Try over and over again until the UI suddenly realizes you want to vertical scroll.
5. Realize that it doesn't matter where you place your finger to try to start the scroll (be it 'dead' space in the UI, or a cover of a movie/show, etc.), it just works really badly.

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/uziqajulig.kodi

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 8.1.0 (Android ARM 64-bit)
 - Kodi version: 18.1 Git:20190410-b6745d835c

**Comment by kib** [comment]
If I am correct you are using the estuary skin which is not meant / created for touch.
Is the behaviour the same with the Estouchy skin ?

**Comment by ronie** [comment]
no response from OP. closing.
