### ISSUE TITLE
Player.SetRepeat API Call Fails to Function As Expected with Music Player

### ISSUE THREAD

**Issue by dguyton** [xbmc/xbmc#15908]
### Describe the bug
Here is a clear and concise description of what the problem is:

2 issues, but submitting them both in 1 bug report as they are closely related (same API call):

1. Parameter "cycle" of Player.SetRepeat does not function properly with music player
2. Player.Repeat API function (called by Set.Repeat) ignores "cycle" parameter and treats "one" parameter with behavior assigned to "all" parameter.

Making a Player.SetRepeat call to Kodi's JSON-RPC API to PlayerID 0 while music is playing results in an "OK" response from the API engine:

{
    "id": 1,
    "jsonrpc": "2.0",
    "result": "OK"
}

Comment above tested with this call:

{"jsonrpc": "2.0", "method": "Player.SetRepeat", "params":{"playerid":0,"repeat":"cycle"},"id": 1}

However, the current track does not repeat. Rather, the player skips to the next track in the album.

The current API documentation (JSON-RPCv9) indicates the function Player.SetRepeat in turn calls the Player.Repeat function, with a default setting of "cycle." The possible enumerations of Player.Repeat are off, one, and all. 

Furthermore, this very similar API call:

{"jsonrpc": "2.0", "method": "Player.SetRepeat", "params":{"playerid":0,"one":"one"},"id": 1}

Should cause a track to repeat one time, but when used with the music player it causes the track to repeat constantly (as if the user had entered the "all" parameter).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The API function should accept a command parameter of "cycle" and automatically change to the next mode in the aforementioned order (off / one / all). For example, if the Repeat status is "off" prior to receiving the API command and the API command is to "cycle" the Repeat function, then the Repeat function should change to the next lineal choice (i.e. "one" in the case of this example).

The API accepts any of these parameters: cycle, off, one, all. Each of these function as expected, with the exception of "cycle" which does not appear to do anything.

Note that the API feedback provides an "OK" response when either "cycle" or "one" parameters are used in the API call, giving the user the false impression the command was accepted and properly processed.

What should happen is:

1. When "cycle" is a parameter in the Player.SetRepeat API call and the music player is the target Player ID, the repeat function status should be cycled from its current state through one/all/off per the documentation under Player.SetRepeat.

2. Player.SetRepeat should repeat the current track one time only when the music player PlayerID is selected and the API request either explicitly asks for "one" repeat or Player.SetRepeat has requested to cycle the repeat level, in which case when the repeat status was formerly off, the cycle parameter should cause the status to change to one repetition.

## Actual Behavior

When targeting the music player ID:

When repeat is off and the new status is "cycle" no repeats occur
When repeat is off and the new status is "one" the track repeats indefinitely

## Possible Fix

1. Correct the "cycle" behavior so it is actually cycling the repeat status
2. Correct the behavior of the repeat function so when just one repetition is requested, the player repeats only one time

### To Reproduce

1. Start Kodi and goto the Music section
2. Ensure Kodi's "repeat" status is off
3. Begin playing a music track with Kodi*
4. Launch Postman or a similar tool and send this command to Kodi as a JSON request using HTTP POST:

{"jsonrpc": "2.0", "method": "Player.SetRepeat", "params":{"playerid":0,"repeat":"cycle"},"id": 1}

5. Observe the track does not repeat.
6. Try again, but this time use this command

{"jsonrpc": "2.0", "method": "Player.SetRepeat", "params":{"playerid":0,"repeat":"cycle"},"id": 1}

7. Observe results and notice the track repeats continuously

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Discovered while testing API integration in Kodi 18.1

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 16.04.5 Server
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
This is not a bug:

"Cycle" does exactly what its meant to be. It cycles through the different repeat states: 
Using this command: 
`curl -g --data-binary '{ "jsonrpc": "2.0", "method": "Player.SetRepeat", "params":{"playerid":0,"repeat":"cycle"},"id": 1}' --header 'content-type: application/json;' http://192.168.1.181:8080/jsonrpc`

current state, normal playback (or "repeat off"):
![grafik](https://user-images.githubusercontent.com/7235787/56076111-1431d600-5dcd-11e9-8185-9b5aca8ef2f6.png)

executed once (results in "Repeat all"):
![grafik](https://user-images.githubusercontent.com/7235787/56076119-2dd31d80-5dcd-11e9-87a8-ff85d7caf00b.png)

executed again (results in "Repeat one"):
![grafik](https://user-images.githubusercontent.com/7235787/56076139-75f24000-5dcd-11e9-9664-62ebe4129dd4.png)

So it "cycles" pretty fine as you can see in the green square. 

You also have to understand that "one" is not meant to be a single tracked only repeated once. It means, that only "one" track is repeated continously. Where "all" means the full album/playlist gets repeated. 

So, tbh, I don't see a bug here. The only thing which could probably improved might be the documentation if you say, the documented order of the cycle is: `off -> one -> all`. As currently it's `off -> all -> one`. But yeah. That's kind of nitpicking ;)

Using commands like: 
`curl -g --data-binary '{ "jsonrpc": "2.0", "method": "Player.SetRepeat", "params":{"playerid":0,"repeat":"off"},"id": 1}' --header 'content-type: application/json;' http://192.168.1.181:8080/jsonrpc`

or: 
`curl -g --data-binary '{ "jsonrpc": "2.0", "method": "Player.SetRepeat", "params":{"playerid":0,"repeat":"all"},"id": 1}' --header 'content-type: application/json;' http://192.168.1.181:8080/jsonrpc`

or:
`curl -g --data-binary '{ "jsonrpc": "2.0", "method": "Player.SetRepeat", "params":{"playerid":0,"repeat":"one"},"id": 1}' --header 'content-type: application/json;' http://192.168.1.181:8080/jsonrpc`

are working perfectly.

**Comment by DaveTBlake** [comment]
>Note that the API feedback provides an "OK" response when either "cycle" or "one" parameters are used in the API call, giving the user the false impression the command was accepted and properly processed.

@dguyton it may also be useful for you to know that an "OK" response from API calls generally means that the request was sucessfully made, not that what has been requested has been completed successfully.

**Comment by dguyton** [comment]
> 
> 
> > Note that the API feedback provides an "OK" response when either "cycle" or "one" parameters are used in the API call, giving the user the false impression the command was accepted and properly processed.
> 
> @dguyton it may also be useful for you to know that an "OK" response from API calls generally means that the request was sucessfully made, not that what has been requested has been completed successfully.

Hi Dave. Thanks. I suspected that, but GTK it is indeed just acknowledging receipt and syntax was correct before handing off to another process. I figured as much since some calls return data and others simply return the OK response, which I inferred meant the syntax was OK.

**Comment by dguyton** [comment]
@DaVukovic Thank you for your thorough response. Now that you've framed the expected behavior in that context, yes it makes sense. 

Then the issue here is the documentation. Kodi's API docs are quite frankly terrible, IMHO. I mean, if you read them there is virtually no explanation of commands. The JSON schema is there, but that's it. The average person who just wants to know how to program their remote is not going to have a clue how to structure many of the commands properly. This creates a barrier to using the API (which has some really cool features, btw) and unnecessary confusion.

And you can call me nit-picky if you like, but IMO, yes the documentation should reflect the correct order of command execution when "cycle" is implemented. When the dox don't match the code, user confusion and frustration (and sometimes devs) is the result.

Now, that said.... I do understand what a pain it is to keep up with technical documentation. Most developers loathe writing dox. FWIW, I have signed up to participate in helping edit the Wiki. It looks as if the API section is one where I could potentially be useful. :-)

**Comment by DaveTBlake** [comment]
> Kodi's API docs are quite frankly terrible, IMHO....  I have signed up to participate in helping edit the Wiki. It looks as if the API section is one where I could potentially be useful. :-)

@dguyton offering to contribute is definitely preferred to complaining :)
Historically the Wiki for JSON has been little more than the JSON schema manually converted into wiki, this is far from ideal as it is labour intensive to maintain, easy to make mistakes and adds little value (may as well read the schema). Those are some of the reasons why the wiki has not been updated with the schema changes for v18.  The other being that a partial or inaccurate update is worse than having a section that is known to be out of date.

Writing a more descriptive section on how to use JSON could be useful, although perhaps much is already covered in the forum (if in a disorganised way). The forum is certainly a source for infomation about JSON, and that information could be consolidated.

**Comment by dguyton** [comment]
@DaveTBlake ...

> @dguyton offering to contribute is definitely preferred to complaining :)

LoL. :)

> Historically the Wiki for JSON has been little more than the JSON schema manually converted into wiki, this is far from ideal as it is labour intensive to maintain, easy to make mistakes and adds little value (may as well read the schema). Those are some of the reasons why the wiki has not been updated with the schema changes for v18. The other being that a partial or inaccurate update is worse than having a section that is known to be out of date.
> 
> Writing a more descriptive section on how to use JSON could be useful, although perhaps much is already covered in the forum (if in a disorganised way). The forum is certainly a source for infomation about JSON, and that information could be consolidated.

Ironically... since we are having this discussion... I've been meaning to reach out to you on that subject, via the forum. I've been a lurker for quite some time and I've read most if not all of your posts on Krypton and Leia's media player behavior, and especially music metadata. I would be glad to help contribute to consolidating the large amount of information you've provided the community over the past 2+ years on those subjects.

I actually have a head-start sorting the information that is scattered about (mostly on the Kodi forum). I could really use a set of expert eyes on it to advise me if I've got the facts straight or not. My existing documentation on Krypton is much more complete vs. Leia, but I believe that's a good thing since the changes to media handling in Leia seem to have used lessons learned from Krypton as a launchpad.

Would you be interested in collaborating? Perhaps we could shift this discussion to Kodi forum PM.

I have a document ready for review that pertains to music metadata in Krypton (v17). I believe it's relatively comprehensive. I welcome constructive criticism.

I am planning to update the same doc for Leia (v18) when I have time to pour over the UI and process changes, as I know some are significant. The Krypton doc is 18 pages atm. I have not added screenshots, but that's on my long to-do list.

Regarding Leia, my immediate focus is wrapping my head around these API calls. I have started with what I believe are the most common needs (e.g. UI navigation, Input.Action enums, etc.). Since my time to focus on this is limited, that approach seems logical to me versus chronological order. Some of the API calls are very esoteric and I doubt there's high demand for them.

I'm not sure who I should vet that doc with, but I do not want to publish potentially erroneous info in the Wiki, so I'll be looking for a good contact on that front as well (proof-reading and providing feedback on my related dox).

TBH with you, from my perspective, Kodi's documentation is probably the single biggest roadblock preventing wider adoption. As a user, you can see the incredible options available based on what others have accomplished, but figuring out how to implement a custom Kodi solution often feels like a daunting task. To your point, it's usually not due to lack of shared knowledge, but rather the fact that shared knowledge is spread far and wide.

**Comment by rmrector** [comment]
To see what options are available via JSON-RPC, use something like the JSON-RPC browser "The Lab" built in to the default web interface Chorus2 to browse and interact with the current schema. My [Devhelper web](https://github.com/rmrector/webinterface.devhelper) also features a helpful JSON-RPC browser. These will be useful tools for your documentation quest.

**Comment by dguyton** [comment]
Awesome. Thank you, @rmrector 

I had seen the link to The Lab in Chorus but hadn't explored it. Just checked it out. Very useful. Thanks. :)

**Comment by DaveTBlake** [comment]
>Ironically... since we are having this discussion... I've been meaning to reach out to you on that subject, via the forum. 

Yeap forum is a good way to communicate with me and discuss things.

>Would you be interested in collaborating? Perhaps we could shift this discussion to Kodi forum PM.

My problem is finding the time to collaborate, but I'll do my best to be supportive. Just open a thread and start talking, you can PM links to anything you want be to read or post on your own Git repo and send me a link.

**Comment by dguyton** [comment]
@DaVukovic 

Follow-up question and observation on this....

> So, tbh, I don't see a bug here. The only thing which could probably improved might be the documentation if you say, the documented order of the cycle is: `off -> one -> all`. As currently it's `off -> all -> one`. But yeah. That's kind of nitpicking ;)
> 
> Using commands like:
> `curl -g --data-binary '{ "jsonrpc": "2.0", "method": "Player.SetRepeat", "params":{"playerid":0,"repeat":"off"},"id": 1}' --header 'content-type: application/json;' http://192.168.1.181:8080/jsonrpc`
> 
> or:
> `curl -g --data-binary '{ "jsonrpc": "2.0", "method": "Player.SetRepeat", "params":{"playerid":0,"repeat":"all"},"id": 1}' --header 'content-type: application/json;' http://192.168.1.181:8080/jsonrpc`
> 
> or:
> `curl -g --data-binary '{ "jsonrpc": "2.0", "method": "Player.SetRepeat", "params":{"playerid":0,"repeat":"one"},"id": 1}' --header 'content-type: application/json;' http://192.168.1.181:8080/jsonrpc`
> 
> are working perfectly.

I just read over the JSON-RPC v9 wiki and the Methods API code at  xbmc/xbmc/interfaces/json-rpc/schema/methods.json 

I noticed the JSON syntax lists "cycle" as the only valid enum value, and yet I have tested your code above on my Linux box and indeed _off_, _one_, and _all_ commands also function. I don't understand how those commands can work when they don't exist in methods.json. That's a mystery to me. Would you shed some insight into how that is possible?

Aside from that, clearly the documentation is not up-to-date.
