### ISSUE TITLE
Crash when starting to play some videos

### ISSUE THREAD

**Issue by jorgenbosman** [xbmc/xbmc#15903]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi crashes when playing some older avi files. Newer files work fine. When i try to play such a file, I get a brief black screen like it is setting up everyting to play, and then kodi disappears without any error message. A crashdump is produced. This worked perfectly in the latest Kodi 17

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The file is played normally

## Actual Behavior

Kodi crashes

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

[kodi.zip](https://github.com/xbmc/xbmc/files/3072641/kodi.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Please post your log to a paste type service... https://paste.kodi.tv/ 

If log is too big then use https://paste.ubuntu.com/

**Comment by jorgenbosman** [comment]
You can find the log here: https://paste.kodi.tv/vudisixolu.kodi

**Comment by jorgenbosman** [comment]
It seems the crash was caused by Intel video drivers. I updated to the latest version and now Kodi no longer crashes
