### ISSUE TITLE
Path Substitution for Sources.xml not working

### ISSUE THREAD

**Issue by linknetx** [xbmc/xbmc#15917]
### Describe the bug
Path substitution for the sources.xml file is only partly working.

With the path to the sources.xml file set to a remote location using the following in the advancedsettings.xml file:
```
  <pathsubstitution>
    <substitute>
      <from>special://profile/sources.xml</from>
      <to>smb://MEDIASERVER/Shared Media/Kodi/UserData/sources.xml</to>
    </substitute>
  </pathsubstitution>
```
Any new sources are correctly written to the remote sources.xml file but the remote sources.xml file is not read when restarting Kodi resulting in no sources being shown on the home page and the files menu.

With the path substitution still in place and temporarily copying the remote sources.xml file to the local path the sources now appear showing that the data is being read from the local path and not the remote path as it should be.

Path substitution works perfectly for the favourites.xml file so it's not a remote network access issue.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The remote source.xml should be read, not the local source.xml

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/3079341/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

**Remote Source**
![1 Home Remote Source](https://user-images.githubusercontent.com/25765532/56120904-044df980-5f67-11e9-9d40-9b3c24336b54.png)
![2 Files Remote Source](https://user-images.githubusercontent.com/25765532/56120905-044df980-5f67-11e9-982b-219ec214e0ee.png)

**Local Source**
![3 Home Local Source](https://user-images.githubusercontent.com/25765532/56120906-044df980-5f67-11e9-9ee3-8a8c0c10ab8c.png)
![4 Files Local Source](https://user-images.githubusercontent.com/25765532/56120907-04e69000-5f67-11e9-8cf0-55a350ecbabe.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.1RC

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Please read the red note: https://kodi.wiki/view/Path_substitution

**Comment by linknetx** [comment]
OK, is there any particular reason for not fixing this?

**Comment by DaVukovic** [comment]
Please continue the discussion at the forums: https://forum.kodi.tv/showthread.php?tid=336371
