### ISSUE TITLE
Nvidia shield auto framerate switching not working in 4k@60hz

### ISSUE THREAD

**Issue by ptidav** [xbmc/xbmc#15915]
### Describe the bug
Here is a clear and concise description of what the problem is:

Auto frame rate switching not working in kodi 18.1 fresh install if the nvidia shield TV resolution is set to 4k@59,94hz ou 60hz.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should set the framerate to the frame rate of the played content keeping the 4K resolution (to keep the benefit of the TV upscaling)

## Actual Behavior

Contents are all played at 60hz instead of 24 or 25/50hz

### To Reproduce

1. Set your nvidia shield tv resolution to 3140x2160@59,94hz
2. Launch Kodi (fresh install), set the auto frame rate switching to "on start/stop" ; do not add resolutions to whitelist.
3. Play a 24hz movie, the resolution stays at 3140x2160p@60hz

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/aroyabacun.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android -Nvidia Shield TV
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 8.0 / Nvidia Shield TV 7.2.3
 - Kodi version: 18.1 (2019/04/10)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HitcherUK** [comment]
Have you enabled 3140x2160p@24hz in the whitelist?

**Comment by ptidav** [comment]
If i enable it in the whitelist, 1080p 24hz is played at 60hz....
Normally without elements in the whitelist, KODI should switch to the correct framerate without changing the resolution, no ?

**Comment by DaVukovic** [comment]
As mentionerd above by the bot, could we see a debuglog, please?

**Comment by ptidav** [comment]
Yes, i will upload it soon

**Comment by M2k80** [comment]
you need to setup the whitelist, your log sais whitelist is empty, so default resolution will be used.
i am using a shield too, and resolution switching is working for me

**Comment by ptidav** [comment]
Hum, the framerate switch correctly when i watch 4K content (25hz or 24hz) without the withelist.
In the log i can see that kodi try to detect the framerate ; so why it can not ?...
Futhermore, after new tests this morning, there are some movies that I have already watched for which the framerate is set correctly !
It seems that the problem occurs for new films not yet watched

> you need to setup the whitelist, your log sais whitelist is empty, so default resolution will be used.
> i am using a shield too, and resolution switching is working for me
If you play a 24hz 1080p movie then your resolution is set to 3140x2160@24hz ?

**Comment by M2k80** [comment]
i have enabled all resoloutions in the whitelist, exept 1080p/25hz. if i watch an 1080p/24hz movie its switching to 1080p/24hz

**Comment by M2k80** [comment]
in your logfile the movie has 23.97fps so you need to enable in whitelist 23.98hz too, 24hz is not enough.

here a screenshot with a part of my whitelist and enabled resolutions
![IMAG1256](https://user-images.githubusercontent.com/6137556/56161297-76572a80-5fc9-11e9-8a05-bf16a18288ba.jpg)

**Comment by lrusak** [comment]
If you don't have any mode's selected in the whitelist Kodi will just try and match a refresh rate for your current resolution. So if you have kodi set to 4K, then it will look for 4k modes (even for 1080p content).

The whitelist is really meant for people that want to allow certain refresh rates only or if you want to allow switching down to a lower resolution.

So if you only want to watch content at your native resolution with whatever refresh rate is available it's best to just keep the whitelist blank.

**Comment by M2k80** [comment]
hm ok, if he dont want use 1080p as resolution, his logfile sais something other as you just said.
No exact whitelisted resolution matched, trying double refresh rate
No double whitelisted resolution matched, trying 3:2 pullback
No double refresh rate whitelisted resolution matched, trying current resolution
Matched current Resolution 3840x2160 @ 59.940060 - Full Screen (16)
Display resolution ADJUST : 3840x2160 @ 59.940060 - Full Screen (16) (weight: 0.000)

**Comment by lrusak** [comment]
I think #15385 broke this behavior. @peak3d please take a look

**Comment by ptidav** [comment]
> in your logfile the movie has 23.97fps so you need to enable in whitelist 23.98hz too, 24hz is not enough.
> 

Already tried 23.98hz and 24hz of course, but no framerate switching...

**Comment by M2k80** [comment]
@ptidav you said you want the benefit of tv upscaling, then you need to whitelist 1080p for your 1080p content, if you stay at 4k resolution and only want to set the correct Hz for the movie, then shield upscaler is used and not the Tv upscaler ;)

**Comment by ptidav** [comment]
> If you don't have any mode's selected in the whitelist Kodi will just try and match a refresh rate for your current resolution. So if you have kodi set to 4K, then it will look for 4k modes (even for 1080p content).
> 
that's what I want

> The whitelist is really meant for people that want to allow certain refresh rates only or if you want to allow switching down to a lower resolution.
> 
> So if you only want to watch content at your native resolution with whatever refresh rate is available it's best to just keep the whitelist blank.
>
Yes, I want to see contents in 4K and at the right framerate ; that's all

**Comment by M2k80** [comment]
@lrusak i just tested on my shield, i cleared my whitelist. framerate switch will happen on 24fps movies, but wont happen on 23.97fps movies

**Comment by ptidav** [comment]
SOMETHING INTERRESTING : I just changed the kodi resolution to 3140x2160@50hz and... the movie framerate is set correctly now !!
movie is played at 3140x2160 at the correct framerate : 24hz switching is working !

if I go back in 3140x2160 @ 60hz then the framerate does not switch...

**Comment by ptidav** [comment]
> @ptidav just only for your information, the shield upscaler is not good, you would have a nicer picture if you would use it like i said. if you stay at 4k on your shield, your shield is upscaling 1080p content to 4k, if you use the whitelist, like i said, and send the movie in 1080p to your tv, your tv will upscale the 1080p to 4k.

If i use whitelist to do that, my tv (panasonic fz800) switch to 1080p ; i loose the benefits of the 4K upscaling

**Comment by M2k80** [comment]
no you wont, the screen on your tv shows 1080p, this is correct, but it internaly upscale to 4k (tv´s native resolution), because its an 4k tv. try and test the screen quality by yourself.

you can easily test this, 
go to shield home menu and look at the quality of the screen now, when the shield is set to 4k resolution. 
now change the shield resolution to 1080p and watch the home menu again, it should be much sharper now -> now tv does the upscaling (for this test dont use kodi).
if you now think your picture looks better when your shield is on 1080p, then set your resolution back to 4k and enable 1080p in whitelist, but if you think there is no change or with 4k it looks better, then stay at your default settings.

**Comment by ptidav** [comment]
oh ok, i will test this tomorrow

**Comment by HitcherUK** [comment]
> If i use whitelist to do that, my tv (panasonic fz800) switch to 1080p ; i loose the benefits of the 4K upscaling

No, your TV is is only showing you the input signal resolution (1080p) it will then upscale it to 4k; if it was displaying it at 1080p it would only take up a quarter of the screen.
Best option is to let the TV do the scaling so you want to enable everything in the whitelist.

**Comment by peak3d** [comment]
@ptidav I reread the thread and I'm confused about the usage of 59.94 / 60Hz and 23.97 / 24 fps movies.
Can you pls. write exactly (!!) what switch do you expect? Without mixing 59.94 and 60 and 23.97 and 24? Those are different values. (24 != 23.97 and 59.94 != 60 )

**Comment by ptidav** [comment]
My shield recommends the use of the resolution 3140x2160@59,94hz. So it's configured with this resolution

Kodi uses this default resolution.

When i play a movie (1080p 23,98hz), Kodi does not switch the framerate at 23,98hz but stay at 59,94hz. So there is jittering during playback !
I've enabled auto framerate switching.

I'll take a look to my log to see EDID datas

**Comment by peak3d** [comment]
I cannot say from here if your settings on shield are the cause, or if the TV provides non parseable EDID.
But as long you don't find the enumeration in kodi.log, kodi will not switch.

**Comment by M2k80** [comment]
@peak3d I tested last night with an empty Whitelist. My resolution was set to 4k@59.94. I tested a movie with 1080p 23.97, the shield dont switch. If I play a movie with 24p the shield is switching to 24hz.
So actually there is no switching if resolution is set at 4k@59.94 and a movie played with 23.97fps.

**Comment by peak3d** [comment]
@M2k80 23.97 on 59.94 is "Ok" after latest commit (allow 2:3 pullback)

**Comment by ptidav** [comment]
> @peak3d I tested last night with an empty Whitelist. My resolution was set to 4k@59.94. I tested a movie with 1080p 23.97, the shield dont switch. If I play a movie with 24p the shield is switching to 24hz.
> So actually there is no switching if resolution is set at 4k@59.94 and a movie played with 23.97fps.
> 
> This is the same way he used.
> I can add 23.97 to Whitelist then it works. But I think he wants to use the auto function without adding resolutions to whitelist

Exactly !

**Comment by M2k80** [comment]
Ok, then it works like exepted
But this not switching is the reason why he made this bugreport.

**Comment by peak3d** [comment]
@M2k80 no, he has a different issue, look at his log (s), and compare to yours.
There is nothing for kodi to switch to.

**Comment by peak3d** [comment]
@ptidav try selecting another color space on nvisia shield in Advanced / HDMI.
If you want you can also provide a logcat (adb logcat -d | pastebinit from a remote device).

With some luck we hit the place where Android enumerates the modes internally.

**Comment by M2k80** [comment]
He wanted to play an 1080p@23.97 movie with kodi set to 4k@59.94. He dont wanted a resolution switch, he wanted only refreshrate switch.
And as you explained with 59.94 -> 23.97 will be no Auto switch. And the movie will played with 59.94. Correct?

**Comment by peak3d** [comment]
@M2k80 for android >= 6.0 there is no "refreshrate switch". Its only mode switch, either mode to same reso + matching refresh rate, or to mode with both different. Its all the same from technical POV.

Whisout additional modes, you want have refreshrate switches and you want have reso switches (wich maybe contain reso switch). Its all steered by modes.

**Comment by ptidav** [comment]
@peak3d This is my debug log, i just launched kodi and record it.
https://paste.kodi.tv/avipukujag.kodi
you cans see the "available modes" lines

Sorry my first log, was truncated ; that's why "available modes" was not shown...

**Comment by HitcherUK** [comment]
Those modes might be available but won't actually be used because you haven't specified them in the whitelist.

**Comment by peak3d** [comment]
@ptidav thx for the complete log. And yes, 59.94 s from sorting order the first match we find (matches are in your case 23.97 and 59.94 (what is called 3:2 pullback and should play fine on nowdays devices. This is the reason why shield's default refreshrate is 59.94: to play 23.97 movies fine.

If your 23.97fps movie does not play smooth, pls. enable "Sync Playback To Screen" in kodi settings (settings::player::video).

What we can do for the future kodi releases: Priorize 59.94 down (sort resolutions before search) to hit first 23.97. But: This would mean a refreshrate switch (~ 1 second gap) and slower GUI. I personally play all my 23.97 videos on 59.94 because of the beforementioned reasons.

You may see, that there is no real right and wrong, all depends on what users prefer or not.

Final question: do you have any issues playing 23.97 on 59.94 ?

**Comment by ptidav** [comment]
> Final question: do you have any issues playing 23.97 on 59.94 ?
in this case the content is not displayed smoothly...every 10 sec there is stuttering effects....

I find all this complicated as a basic user ; for me, simply, Kodi MUST adapt automatically the refresh rate correctly according to the source played. 

in a previous post i wrote :
>SOMETHING INTERRESTING : I just changed the kodi resolution to 3140x2160@50hz and... the movie framerate is set correctly now !!
movie is played at 3140x2160 at the correct framerate : 23,98hz switching is working !
>
Can you tell me why, with this refresh rate, kodi switch correctly to the good content framerate ?

**Comment by peak3d** [comment]
@ptidav sure I can look why 23.97 is selected if you provide a log for this task.

"Good 23.97" depends on users POV, for me and many others I know 59.94 is good, and 23.97 not (because of the resons I told earlier). Question again: Whats wrong with your 23.97 on 59.94? What is your real reason to want to have the 1 second black screen if movie plays perfect on 59.94? Isn't it better if you have less switches as possible if the playback quality is fine? We are not discussing a pure technical  topic here.

**Comment by ptidav** [comment]
> no you wont, the screen on your tv shows 1080p, this is correct, but it internaly upscale to 4k (tv´s native resolution), because its an 4k tv. try and test the screen quality by yourself.
> 
> you can easily test this,
> go to shield home menu and look at the quality of the screen now, when the shield is set to 4k resolution.
> now change the shield resolution to 1080p and watch the home menu again, it should be much sharper now -> now tv does the upscaling (for this test dont use kodi).
> if you now think your picture looks better when your shield is on 1080p, then set your resolution back to 4k and enable 1080p in whitelist in kodi, but if you think there is no change or with 4k it looks better, then stay at your default settings.

@M2k80 you are right, fonts are sharper ; display is less blur

**Comment by ptidav** [comment]
> @ptidav sure I can look why 23.97 is selected if you provide a log for this task.
> 
Here : https://paste.kodi.tv/udugoyodur.kodi

> "Good 23.97" depends on users POV, for me and many others I know 59.94 is good, and 23.97 not (because of the resons I told earlier). Question again: Whats wrong with your 23.97 on 59.94? What is your real reason to want to have the 1 second black screen if movie plays perfect on 59.94? Isn't it better if you have less switches as possible if the playback quality is fine? We are not discussing a pure technical topic here.
> 

in this case the content is not displayed smoothly...there is stuttering effects.... it's horrible...

>Edit: a basic user does not care about the refresh rates **if the movie playback is fine,** But a basic user asks why there are so many refreshrate switches which annoy.
>

In my case the playback is not fine : stuttering

**Comment by peak3d** [comment]
@ptidav I assume you have Sync Playback to display off (as already mentioned in one of the earlier posts), right? If so, switch it on and try again.

**Comment by ptidav** [comment]
yes, i will try

**Comment by ptidav** [comment]
i'have set off autoframerate and enabled Sync Playback to display.
The playback is continously stuterring (more ou less depending of the movies), travellings are worse....

not convincing

**Comment by avihaybar** [comment]
@ptidav, 
I also had the same issue you are describing, with 23.97 videos playback being choppy and stuttering. I assume your Kodi was auto updated to V18 (and V18.1) on the shield? 

In my case I managed to mostly solve it (not 100% but way better) by renaming the userdata/guisettings.xml (it reverted my skin and some gui settings but resolved some weird resolution issues I had since the auto update such as showing only 1/4 of the screen on 2160p@59.94, etc).
after that everything looks much better (but not 100% smooth playback, and it seems the UI interactions might cause some framerate issues).

**Comment by ptidav** [comment]
I've problem both with uptated kodi or with a fresh install

**Comment by peak3d** [comment]
@ptidav pls. provide a kodi log with component video logging enabled.
And please enable your adjust refreshrate, there is no need to disable for this test.

**Comment by ptidav** [comment]
> @ptidav pls. provide a kodi log with component video logging enabled.
> **And please enable your adjust refreshrate**, there is no need to disable for this test.
you mean "autoframerate switching" or "Sync Playback to display" ??....

**Comment by peak3d** [comment]
@ptidav 
![image](https://user-images.githubusercontent.com/22704999/56597373-a074a200-65f2-11e9-9f40-ac3d57724f56.png)

**Comment by ptidav** [comment]
this is the log with component video logging enabled :
https://paste.kodi.tv/puxijilami.kodi

**Comment by peak3d** [comment]
@ptidav  Sync playback to display is not working with audio set to passthrough.
You will have smooth video playback with passthrough disabled.
But we'll rework the selection of the refresh rate in the near future (not in kodi v18, but v19)

**Comment by peak3d** [comment]
Beside this "Sync Playback To Display" is still not on during your test.
At the time you find this one: "CVideoSyncAndroid::Setup setting up" in your debug log file, its really on.
Its not found in your log, maybe start really with a clean / fresh install.

**Comment by ptidav** [comment]
> @ptidav Sync playback to display is not working with audio set to passthrough.
> You will have smooth video playback with passthrough disabled.

I want audio passthrough : sound dynamic is really better, less crushed.
But i will try to disable it and watch the result


> But we'll rework the selection of the refresh rate in the near future (not in kodi v18, but v19)

ok, one year to wait...do your best as usual ! thanks for your work

**Comment by peak3d** [comment]
v19 is already out (build every night), so I assume it's more weeks than a year.

Beside this: on my shield I get the above mentioned log line even I have passthrough enabled, so it still semms that there is something wrong with your settings / setup.

**Comment by ptidav** [comment]
@peak3d Sorry but i understood that i have to activate ONLY the autoframe rate switching, not "Sync Playback To Display"...
I've enable "Sync Playback To Display" and i have the mention "CVideoSyncAndroid::Setup setting up" in the debug log but movies don't play smoothly...

should I still try with a fresh install ?

**Comment by peak3d** [comment]
Now you have it in log, pls. Provide a new log file with video component logging enabled, thx

**Comment by ptidav** [comment]
Ok, resolution set to 4K@59,94hz
"adjust display refresh rate" set to ON START/STOP
"Sync Playback To Display" set to ON
Played 3 movies 1080p@23,94hz (no switch, kodi played them at 59,94) and one 4k content for wich kodi switched to 23,98hz (that's good for me)

This is the log :
https://paste.kodi.tv/ekeqayubeb.kodi

**Comment by Dnkhatri** [comment]
> @peak3d Ok, resolution set to 4K@59,94hz
> "adjust display refresh rate" set to ON START/STOP
> "Sync Playback To Display" set to ON
> Played 3 movies 1080p@23,94hz (no switch, kodi played them at 59,94) and one 4k content for wich kodi switched to 23,98hz (that's good for me)
> 
> This is the log :
> https://paste.kodi.tv/ekeqayubeb.kodi

Does your tv support that 1080p@23.94hs in the color space. I was having a similar problem later found out that my tv supports all frame rates at 4k but only specific frame rates at lower resolution. And even those are dependent on the color space. So my tv might support 1080p 23.98hz in 2020 color space but not in others. You can see what frame rates and what color space is supported my checking advance hdmi settings in nvidia shield.

**Comment by brettwnaylor** [comment]
This may be helpful, just say if u want me to stay out of it.

My set up, Sony x900f, Shield tv, Kodi Leia. All set to recommended settings, whitelist is enabled.

When Kodi display resolution is set to 3840x2160p and playback is 1920x1080p I have to manually change to the correct option in whitelist. 

when Kodi display resolution is set to 1920x1080p and playback is 1920x1080p the whitelist works, correct frame rate is auto selected.

when Kodi display resolution is set to 3840x2160p and playback is 3840x2160p the whitelist works, correct frame rate is auto selected.

My work around is to set up two profiles, one to playback 4k ( display resolution is set to 3840x2160p - all frame rates selected, all are available ) and the second one to playback 1920x1080p, display resolution is set 1920x1080p - all frame rates selected from 1920x1080p and below. As I have very little 4k content, I don't need to switch profiles often. This works 100% of the time. Playing any 1920x1080p content when display resolution set to 3840x2160p will never select correct frame rate for me, I have to manually select the correct one for smooth playback.

Is this the same issue as above? No big deal for me as the fix is quick to access and i have little 4K content. Tell me to bigger off if this is no help, no offence taken, trying to help.Big Kodi fan, thanks for the great software.

**Comment by M2k80** [comment]
@brettwnaylor I have the Xf9005, I believe its the same like x900f. I dont
have any problems with the with the whitelist. Tested with 10bit 2020 on 4k
and 12bit 2020 on 4k resolution. All modes are switching correct. Like they
should.

brettwnaylor <notifications@github.com> schrieb am Do., 25. Apr. 2019,
11:11:

**Comment by peak3d** [comment]
@ptidav sry I'll stop supporting this issue from now, I don't understand why you provide truncated / modified logs.

**Comment by ptidav** [comment]
> @ptidav sry I'll stop supporting this issue from now, I don't understand why you provide truncated / modified logs.

@peak3d 
Sorry but I had to cut the log because it was too big and I could not save it on paste.kodi.tv
I just removed the part relating to another film in 4K

There is no bad intention on my part


I did not see also that we could attach files directly to the discussion
This is the full log :
[kodi.log](https://github.com/xbmc/xbmc/files/3116981/kodi.log)

**Comment by peak3d** [comment]
@ptidav your log contains a.) no alternative display modes (same issue we had at the beginning of this thread), and it contains only 1 refreshrate switch (search log for "SetNativeResolution").

1.) from the log your 23.97 videos are playing at 50Hz, but I don't think so, it looks more like that there are several log lines inbetween missing.

2.) the only refreshrate switch in the log cannot be happen because of the missing mode enumerations.

-> The log is not only truncated, there are missing lines here and there for whatever reason.

**Comment by ptidav** [comment]
@peak3d 
I don’t know why there are missing lines... it’s tiring...
I will make a reset of my shield and reinstall Kodi from scratch and see what happens

**Comment by ptidav** [comment]
@peak3d 
Ok, i've uninstalled KODI then make a fresh install, without addons, skins, etc
I've played a sequence of movies encoded with differents refresh rates (always in the same order ) ; for some movies kodi switch (24hz, 25hz, 50hz but never switch for 23,976hz)

**I provide 3 logs taking care each time to launch kodi and close it at the end of the tests :**
1 log debug with "adjust display refresh rate" set to ON START/STOP
[kodi debug.log](https://github.com/xbmc/xbmc/files/3117821/kodi.debug.log)

1 log debug with video component and "adjust display refresh rate" set to ON START/STOP
[kodi debug video comp.log](https://github.com/xbmc/xbmc/files/3117825/kodi.debug.video.comp.log)

1 log debug with video comp - adjust display refresh rate AND sync playback to display ON
[kodi debug video comp - adjust display refresh rate AND sync playback to display ON .log](https://github.com/xbmc/xbmc/files/3117827/kodi.debug.video.comp.-.adjust.display.refresh.rate.AND.sync.playback.to.display.ON.log)


I sincerely hope they will help you understand why kodi does not switch when a 23,976h movie is played

**Comment by M2k80** [comment]
> @ptidav thx for the complete log. And yes, 59.94 s from sorting order the first match we find (matches are in your case 23.97 and 59.94 (what is called 3:2 pullback and should play fine on nowdays devices. This is the reason why shield's default refreshrate is 59.94: to play 23.97 movies fine.
> 
> If your 23.97fps movie does not play smooth, pls. enable "Sync Playback To Screen" in kodi settings (settings::player::video).
> 
> What we can do for the future kodi releases: Priorize 59.94 down (sort resolutions before search) to hit first 23.97. But: This would mean a refreshrate switch (~ 1 second gap) and slower GUI. I personally play all my 23.97 videos on 59.94 because of the beforementioned reasons.
> 
> You may see, that there is no real right and wrong, all depends on what users prefer or not.
> 
> Final question: do you have any issues playing 23.97 on 59.94 ?

peak3d already explained it here. without using the whitelist, kodi wont switch to 23.97hz if 59.94hz is set as default framerate, because its normaly working fine and no extra time for switching is needed. if you want that extra switch you have to use the whitelist and enable all that resolutions you want to switch to.

**Comment by ptidav** [comment]
@M2k80 : ok, if i add 3840x2160@23,976hz in the whitelist kodi will switch at 3840x2160@23,976 when i'll play a 1080p@23,976hz movie ?

**Comment by peak3d** [comment]
@ptidav we are currently not looking for the reason why it does not switch, we look for the reaon why 23.97 is not smooth on your 59.94Hz display. So -> I only need exactly 1 log with one movie playing (23.97 video on 59.94Hz), let it run some seconds until you investigate stutter, provide the log and try to explain how your stutter looks like (hickup every n sec? Or do you mean micro-stutter which normally are only when pans?).

**Comment by ptidav** [comment]
> > @ptidav thx for the complete log. And yes, 59.94 s from sorting order the first match we find (matches are in your case 23.97 and 59.94 (what is called 3:2 pullback and should play fine on nowdays devices. This is the reason why shield's default refreshrate is 59.94: to play 23.97 movies fine.
> > If your 23.97fps movie does not play smooth, pls. enable "Sync Playback To Screen" in kodi settings (settings::player::video).
> > What we can do for the future kodi releases: Priorize 59.94 down (sort resolutions before search) to hit first 23.97. But: This would mean a refreshrate switch (~ 1 second gap) and slower GUI. I personally play all my 23.97 videos on 59.94 because of the beforementioned reasons.
> > You may see, that there is no real right and wrong, all depends on what users prefer or not.
> > Final question: do you have any issues playing 23.97 on 59.94 ?
> 
> peak3d already explained it here. without using the whitelist, kodi wont switch to 23.97hz if 59.94hz is set as default framerate, because its normaly working fine and no extra time for switching is needed. if you want that extra switch you have to use the whitelist and enable all that resolutions you want to switch to.

Sorry but it does not work, no switching ; framerate still @59,94hz

**Comment by ptidav** [comment]
> @ptidav we are currently not looking for the reason why it does not switch, we look for the reaon why 23.97 is not smooth on your 59.94Hz display. So -> I only need exactly 1 log with one movie playing (23.97 video on 59.94Hz), let it run some seconds until you investigate stutter, provide the log and try to explain how your stutter looks like (hickup every n sec? Or do you mean micro-stutter which normally are only when pans?).

There is micro-stuttering effects during the playback ; about 4 snags per second
This is the log :
[kodi.log](https://github.com/xbmc/xbmc/files/3118940/kodi.log)

I've tested with "sync playback to display" OFF : same problem during the playback.
It's like the option "sync playback to display" had no effect

**Comment by peak3d** [comment]
@ptidav the mkv container does not provide stable PTS values, this is the reason why this movie does not playback well. Until we have more options with refreshrate in kodi, simply add your 23.97 refreshrates in the whitelist. 1080p@23.97 will then be scaled from TV to your native display resolution (TV does the job)

**Comment by ptidav** [comment]
@peak3d 
no stable PTS, ok, i'll google this later
I've added refreshrates to the wthitelist.
But for some movies kodi does not switch, why ?
This is the log :
[kodi.log](https://github.com/xbmc/xbmc/files/3120779/kodi.log)

**Comment by peak3d** [comment]
> Whitelist search for: width: 1280, height: 534, fps: 23.976, 3D: false

There is no exact 1280x534 screen resolution, because of that there is no switch using whitelist.
For your usecase (switch only refreshrate, but not resolution) you'll have to wait for the implementation in kodi.

**Comment by ptidav** [comment]
OK, I wait the neXt kodi
you mean V19 ?

**Comment by peak3d** [comment]
yes, v19, not sure if we beckport it to 18.3

**Comment by ptidav** [comment]
18.3 would be great !
Thanks for your time and your work

**Comment by Rumpa112** [comment]
Its the same on Win10 when I use Real Fullscreen. Everything plays at 60  and HDR looks crap btw.

**Comment by thexai** [comment]
Switch display refresh rate at Start/Stop works fine in current master/Matrix (Shield)
