### ISSUE TITLE
JSON API Player.Seek: Negative Time Interval Causes Incorrect Behavior

### ISSUE THREAD

**Issue by dguyton** [xbmc/xbmc#15914]
### Describe the bug
Here is a clear and concise description of what the problem is:

Use of negative "seconds" time unit in **Player.Seek** JSON command results in unexpected behavior that is inconsistent with every other behavior pattern from Player.Seek

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Error message. Any time interval other than seconds produces an error message, as expected. **Player.Seek** should not hand off the properties to another process.

If the user enters a negative minutes, hours, or milliseconds property, an error message is returned: "_Received value does not match any of the union type definitions_"

## Actual Behavior

Produces erroneous behavior inconsistent with **Player.Seek** expected behavior. The media player acts as if it received a Rewind command.

Example:

`{"jsonrpc": "2.0", "method": "Player.Seek", "params":{"playerid":1,"value":{"seconds":-15}},"id": 1}`

The result in this use case is similar to Rewind (re: **Input.Action**). **Player.Seek** appears to use the incorrect time index, to which the negative "seconds" value is applied. The time offset appears to be indexed (incorrectly) from the current time instead of time 0 (zero; i.e. beginning of media). The latter pattern is consistent with all other behavior from **Player.Seek**

## Possible Fix

This only occurs under one scenario. When all of the following are true:

1. Player ID is valid
2. Only the Seconds time unit is received
3. Unit time Value is a negative integer

For example:

`{"jsonrpc": "2.0", "method": "Player.Seek", "params":{"playerid":1,"value":{"minutes":15, "seconds": 12}},"id": 1}`

I suspect one of two scenarios is occurring. Either 

a) Code is branching incorrectly when **Player.Seek** receives the specified object properties

OR

b) The logic surrounding the time index, which is normally zero (0) or the beginning of the media content (e.g. movie) is not being zero'd out, but rather the current media player time pointer is being used as an index, to which the time value in the JSON command is then applied

### To Reproduce

1. Begin playing a video file in Kodi
2. Wait until the timer for the video is past the first minute
3. Using CURL, Postman, or similar test tool, send a JSON-RPC API command to Kodi, similar to the following example. The command should include a Player ID = 1 and the Seconds parameter equal to a negative integer less than 60. Suggest using a value greater than 10 to ensure the behavior is obvious.

`{"jsonrpc": "2.0", "method": "Player.Seek", "params":{"playerid":1,"value":{"seconds":-15}},"id": 1}`

4. Observe that Kodi behaves as if it received a Rewind command (e.g. via **Input.Action**), and rewinds the timer pointing to the current time being played on the video media by the same number of seconds indicated in the JSON command.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

How do I know this is a bug and not WAD? Because if I use any other time unit (i.e. milliseconds, minutes, hours), I receive an error message. Furthermore, the opposite behavior (using a positive integer) results in a different set of behavior. Namely, **Player.Seek** moves the media player time pointer to an offset from the beginning of the media (start) equal to the time units passed in the JSON command.

For example, if I am watching a movie that is at time point 01:02:03 and I execute this command in the API:

`{"jsonrpc": "2.0", "method": "Player.Seek", "params":{"playerid":1,"value":{"minutes":15, "seconds": 12}},"id": 1}`

The result is the media player moves the current pointer (point in the movie being played right now) to 15 minutes, 12 seconds from the beginning of of the movie.

Another example supporting my argument: If the same type of command as the error-producing command is implemented, except the Value integer is positive, **Player.Seek** treats the Value as a percentage and passes the instruction on to **Player.Position.Percentage**

`{"jsonrpc": "2.0", "method": "Player.Seek", "params":{"playerid":1,"value":17},"id": 1}`

The result is the currently playing media pointer shifts the time to 17% of the total movie length. On a 2 hour long movie, that would be 20.4 minutes into the film.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 16.04.5 Server Edition
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
I can confirm it's somewhat inconsistent. 

Looking at the description mentioned here: 

https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/methods.json#L299

while using the `seconds` parameter, Kodi should seek "by a given number or seconds". That's the behaviour you get while using a negative integer (`-15` for example). While using a positive value (`15`) the player seeks always to: 00:00:15 of the movie, no matter what the actual player position is. 

So from my understanding negative values behave correctly, positive do not. 

Positive values seem to behave like the "time" option: 
https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/methods.json#L297

where we have `"description": "Time to seek to"`. 

Normally the time option is used like: 

`curl -g --data-binary '{ "jsonrpc": "2.0", "method": "Player.Seek", "params":{"playerid":1,"value":{"time":{"minutes":15, "seconds":30}}},"id": 1}' --header 'content-type: application/json;' http://192.168.1.181:8080/jsonrpc`

So, not sure how to fix that, but I can at least confirm.

**Comment by dguyton** [comment]
@DaVukovic it seems to me it's a multi-faceted issue. I agree it's a can-o-worms, but I also believe the logical choice is clear-cut when you analyze the Big Picture. I'll offer my analysis and opinion FWIW.

Let me preface my next comments by saying I don't have any idea how the underlying code works, so I am analyzing this from a QA perspective. I am inferring which part of the code is doing what based on observation and my experience testing this on a headless Linux server.

**Facets of The Problem**

1) Time values that are ONLY in seconds get treated differently than time values that contain any other combination of milliseconds/seconds/minutes/hours. The request gets routed differently per the schema.

2) When # 1 happens, the index to which the time interval (jump request) changes. It becomes the current position of the media player's time pointer. It doesn't get reset to zero like every other time expression (see # 3 below). I am wondering if a process to zero that pointer is being skipped under this condition.

3) If Time values don't match # 2 above, OR if "seconds" are sent WITH the "time": property, the request gets sent to **Player.Position.Time** for further processing. This is when we see the behavior where the index to which the jump is applied is the start of the media (i.e. media time 0 + the specified interval). This is the "consistent" behavior seen with every other time-value scenario.

AND here is when an error message is generated if a value is negative or not an integer. Can't go backwards in time from index zero (0). I presume the error logic is coming from Player.Position.Time. That is the more likely possibility, though not a foregone conclusion w/out looking at the code (but a logical place to start looking for the error message handling).

4) Something else interesting with regards to behavior is if I send this command:

`{"jsonrpc": "2.0", "method": "Player.Seek", "params": { "playerid": 1 , "value": {"time": {"seconds":-10 }}}, "id": 1}`

The result is an error message: "Received value does not match any of the union type definitions"

In contrast, if I send this command:

`{"jsonrpc": "2.0", "method": "Player.Seek", "params": { "playerid": 1 , "value": {"time": {"seconds":10 }}}, "id": 1}`

BTW, I'm not intending to repeat your observation in your post above. I'm adding to your comment by demonstrating the fact this behavior inconsistency occurs regardless of whether the "time" property is passed or not. These commands behave identically:

`{"jsonrpc": "2.0", "method": "Player.Seek", "params": { "playerid": 1 , "value": {"time": {"seconds":10 }}}, "id": 1}`

`{"jsonrpc": "2.0", "method": "Player.Seek", "params": { "playerid": 1 , "value": {"seconds":10 }}, "id": 1}`

From what I've gathered, that is most likely coming from **Player.Position.Time**, based on how the logic flow appears most likely to be processed... just looking at behavior from a QA perspective. Obviously that is unknown without reviewing the **Player.Seek** code first to discover where and when branches occur.


**Thoughts/Suggestions**

I personally would favor removing line 299 in the schema, i.e.

`          { "type": "object", "properties": { "seconds": { "type": "integer", "required": true, "description": "Seek by the given number of seconds" } }, "additionalProperties": false, "required": true }`


**Reasoning Behind Proposed Resolution**

1) Ought to solve the problem in the most expeditious manner, while resolving the consistency of behavior issue.
2) The current schema causes the inconsistent behavior (or at the very least it triggers the inconsistent behavior, even if it isn't the only responsible party per se)
3) The functionality created by the behavior we're talking about is already available under another API function (**Input.Action**'s _rewind_ and _fastforward_ properties)

The other option would be to"fix it" so it works consistently. Problems with that approach:

1) More work

2) How does the user differentiate for the parser between a "I want you to index from zero" request versus a "I want you to index from where the media player is pointing right now" request?

3) How does one reconcile the current behavior? Do you add more code and another feature so when "seconds" is the only value and "time" is not a parameter/property, and "seconds" is a positive integer? And if you do that, doesn't that predispose creating the same new functionality for _milliseconds_, _minutes_, and _hours_, in order to maintain consistency?

4) Which function does one modify? I don't know where the code gets routed when the current oddball scenario occurs (negative _seconds_ value only). I do see that any other time values get sent to Player.Position.Time. Does one streamline the schema here and modify **Player.Position.Time** to add new functionality? 


**Conclusions and Recommendation**

The ONLY logical reason I can think of for the 2nd route... adding new functionality... would be because right now Input.Action's _rewind_ and _fastforward_ functions only work with seconds IIRC. Therefore, if **Player.Seek** were expanded, 

It's a big can-of-worms if a decision is made to make the behavior more consistent by adding code that expands the single oddball current behavior into a bona-fide feature. As I said, the operations already exist in **Input.Action**. One just has to use seconds as the only time value. How many users want to be able to jump via seeking by milliseconds (pointless), minutes (use a calculator for Pete's Sake), or hours (really??? how long is your movie?)? Not a logical choice, IMHO.

I think a solution is clear-cut, personally. I'll get off the soap box now. :)

**Comment by rmrector** [comment]
You are over thinking it. The first three options are legacy and should be planned for removal. They have been re-implemented as separate property names `percentage`, `time`, and `step` in the next three options. The continued existence of the legacy options is causing this incorrect behavior and is extra complication we don't need.

The ideal way to use this is to pass in a value with one property `percentage`, `time`, `step`, or `seconds`. `percentage` and `time` go to a specific percentage or time of the full video, while `step` and `seconds` are relative to the current time.

```js
// "Percentage value to seek to"
{"percentage":50}

// "Time to seek to"
{"time":{"minutes":15,"seconds":45}}

// "Seek by predefined jumps"
{"step":"smallforward"}

// "Seek by the given number of seconds"
{"seconds":7}
```

**Comment by dguyton** [comment]
> You are over thinking it. 

How is that over thinking? I like clarity. It prevents confusion. If the schema and documentation were clear, we wouldn't be having this full discussion (though we might still be discussing whether or not parts of Player.Seek are redundant). It's one thing when you work with an application every day and you understand it's quirks. It's another when you are a user who just wants to figure out how to solve a problem and move on. Poorly documented features result in inefficiencies and waste peoples' time trying to figure out why things don't work as expected.

I'm explaining the behavior and my thoughts on fixing it, from the perspective of a user. I could have left out my opinions, but this is a grey area when it comes to functionality. How should Player.Seek function? It's subjective (unless there is a road map and documented feature set requirements for it somewhere that I'm not aware of).

> The first three options are legacy and should be planned for removal. They have been re-implemented as separate property names `percentage`, `time`, and `step` in the next three options. 

Remove ambiguity in syntax and force the user to clearly specify intent? Great! Totally agree.

> The continued existence of the legacy options is causing this incorrect behavior and is extra complication we don't need.

I don't think that is true. Based on my observations, it appears an URL formed with just the "seconds" property is being handled by the this line in the schema and not the legacy code:

`          { "type": "object", "properties": { "seconds": { "type": "integer", "required": true, "description": "Seek by the given number of seconds" } }, "additionalProperties": false, "required": true }`

Caveat: I have not reviewed the relevant code and have no clue where it is or which code (though if someone is kind enough to point it out to me, I'll go fishing... I enjoy learning new things). :)

If I'm correct, your proposal won't solve that problem. If I'm wrong then I don't understand how removing the legacy code is going to fix the underlying operational issue, but I would love to learn if you're willing to elaborate and provide guidance.

Otherwise, it seems to me that to proceed as you suggest is helpful because it eliminates most of the ambiguity, but I think you're missing the point on some of the nuances here. Removing legacy code from the schema only solves part of the problem. 

Am I wrong? To wit:

By retaining a property called "seconds" you're leaving two other issues unresolved:

1. If a user is not forced to funnel parameters through a particular property, and the parameter may appear in more than one context, this create ambiguity and can cause confusion when the user doesn't understand why their JSON code isn't resulting in the desired outcome.

Why not either combine both seek behaviors where the index they start from is the current media position? Either make "seconds" one of the enums of `step` or force the user to clearly declare intent when they want to seek by given number of seconds vs. seek by time, such as:

```
// "Seek by the given number of seconds"
{"seek":"seconds":7}
```

2. The inconsistent behavior I described above regarding positive versus negative _seconds_ values for `seek` would remain.

Am I missing something on that front? How would your suggestion solve that issue?

**Comment by rmrector** [comment]
I just described a clear and **simple** solution.

> pass in a value with one property `percentage`, `time`, `step`, or `seconds`

This is already solved, we just need to clear out the legacy behavior to fix the actual problem.

**Comment by rmrector** [comment]
> If a user is not forced to funnel parameters through a particular property

Incorrect assumption. Removing legacy code **will** force the use of a property.

> How would your suggestion solve that issue?

The legacy code is causing the ambiguity, so removing the legacy code removes the ambiguity.

**Comment by dguyton** [comment]
> > If a user is not forced to funnel parameters through a particular property
> 
> Incorrect assumption. Removing legacy code **will** force the use of a property.
> 
> > How would your suggestion solve that issue?
> 
> The legacy code is causing the ambiguity, so removing the legacy code removes the ambiguity.

You just mentioned cleaning up the JSON schema.

How does a schema change solve the underlying behavioral issue with the `seconds` option?

You're addressing part of the problem (schema ambiguity), but not the underlying (inconsistent) behavior of the code which the `seconds` command option results in a hand-off to. 

Cleaning up the schema clarifies the expected behavior. I'm all for that and agree it's a good idea. And your proposal allows carving out the `seconds` option so its behavior can be handled on its own. But, it still leaves us with inconsistent behavior, no?

1. Negative values result in a seek from index where index = current player position
2. Positive values result in a seek from index where index = global time zero relative to the current media

So, again.... how does a JSON schema change resolve that issue? If the code that executes the instructions (whichever process gets the hand-off per JSON schema mapping) is not modified, the existing, problematic behavior won't change. Am I wrong here?
