### ISSUE TITLE
No UI Sounds for iOS using 18.1 deb release

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#15927]
### Describe the bug
Here is a clear and concise description of what the problem is:

Using http://mirrors.kodi.tv/releases/darwin/ios-arm64/org.xbmc.kodi-ios_18.1-0_iphoneos-arm64.deb on an iPhone UI sounds do not appear to work.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

UI Sounds should work after install.

## Actual Behavior

No audible UI sounds.

### To Reproduce

1. Use iOS signer to sign deb file
2. Install on iOS device
3. Navigate the UI, no UI sounds audible.

### Debuglog

The debuglog can be found here:

To be added.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [x ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: iOS 12
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by kambala-decapitator** [comment]
As we have recently found out on Slack, looks like it had been like that forever, as input manager doesn't play sounds for touch events. For keyboard events it does, and that's exactly what is simulated with touches when iOS enters external screen mode.

**Comment by fuzzard** [comment]
Just linking this back to an existing Issue with some commentary from garbear

https://github.com/xbmc/xbmc/issues/15031

Effectively any input that isnt classed as keyboard, doesnt provide gui sounds. This affects both ios/tvos, and as in the other issue, gamepads/controllers.

Not sure if you want to close this off as duplicate @phunkyfish ?
