### ISSUE TITLE
No media flags shown for DVDs

### ISSUE THREAD

**Issue by arnova** [xbmc/xbmc#15929]
While debugging another issue related to DVDs I noticed that the skin no longer shows any media flags while playing DVDs. I don't know the root cause but I did figure out that data set in CVideoPlayer::GetVideoStreamInfo() is empty. Since I don't know much about this area of Kodi, someone else may have a look at this. Obviously this is a regression from v17.

**Comment by arnova** [comment]
@FernetMenta : Any ideas?

**Comment by DaVukovic** [comment]
@arnova 

"Playing DVDs" in meaning of ISO files or native discs?

**Comment by arnova** [comment]
@davukovic: at least native discs. i'll have to check isos

**Comment by arnova** [comment]
@DaVukovic : Just tested it with ISOs: Same problem (= no media flags). Btw. this is on Linux but I assume it's a crossplatform issue.

**Comment by KarellenX** [comment]
https://github.com/xbmc/xbmc/pull/15589#issuecomment-476446565

**Comment by 1024mb** [comment]
I have the same thing happening to me with DVD and Blu-ray ISOs.

**Comment by arnova** [comment]
@FernetMenta / @peak3d / @pkerling : I did some digging and forcing DVDs to use muxer info instead of navigator info in void CSelectionStreams::Update(std::shared_ptr<CDVDInputStream> input, CDVDDemux* demuxer, std::string filename2), fixes the problem. I can't seem to figure out why, you guys any ideas?

**Comment by arnova** [comment]
I just had another look at this issue, it seems that updating stream details for dvd's never worked properly since everything depends on the fact that a demuxer id is set, which isn't the case since dvd's are special cased in CSelectionStreams::Update(). I think the proper fix would be combining the info from demuxer and DVDInputStreamNavigator for dvd's. Any pointers in the right direction are much appreciated.
