### ISSUE TITLE
After playing a movie, all the subtitles and video aspect information disappeared

### ISSUE THREAD

**Issue by Hawkedon** [xbmc/xbmc#15934]
### Describe the bug
Here is a clear and concise description of what the problem is:

For a MKV movie with subtitle tracks, after playing the movie (or just playing for several minutes), all the subtitles and video aspect information for the video file disappeared from streamdetails table of video database. All the subtitle stream records for the video file were deleted, the fVideoAspect field for video stream was cleared. This issue only appears in 18.2rc1, works fine in 18.1, should be a bug introduced by https://github.com/xbmc/xbmc/pull/15589

Aeon MQ8 skin has these information displayed, so it's very easy to see this bug with that skin. Because this stream detail auto update feature, I can't fix these information by using a NFO file, I think give user an option for this behavior is better. For example, Aeon MQ8 skin doesn't support to show some aspect ratio, I manually edit the NFO file to override the data, but it got override by this update, which is not what I want. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by apguy** [comment]
I am also having this bug.

I would prefer to have the aspect ratio stay as the value from the nfo instead of being autodetected from the video stream like it was in previous versions.  This is because I save the aspect ratio of the movie (ie 2.35 or 2.4 etc) even if the black bars are encoded into the stream (eg direct bluray rips).   This is useful because it can be used to write macros to automatically control projector zoom and lenses etc.  Maybe like Hawkedon suggests may a toggle switch to either use the data from the nfo or the videostream would be the best solution.

**Comment by DaVukovic** [comment]
probably something for @arnova 

Sorry for the noise if I'm wrong

**Comment by arnova** [comment]
Full debug log please

**Comment by arnova** [comment]
This has been fixed by reverting the responsible commit in master/v18. The next (point) release should work as before. Please reopen if the issue persists.
