### ISSUE TITLE
kodi updates library on startup, even when configured not to

### ISSUE THREAD

**Issue by lameventanas** [xbmc/xbmc#15943]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a hard disk with only media, and an ssd with all the software, config files, etc.

I configured kodi to not update the library on startup.

But whenever I start (or restart) kodi, I can hear the disk spinning up, and I see the dialog of "library update" running.  It's kind of fast, but it still spins up the hard disk, so it's annoying and also shortens the lifespan of the hard disk.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The library shouldn't be scanned, the hard drive shouldn't wake up.

## Actual Behavior

Library scanned, hard drive spins.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaveTBlake** [comment]
Are you absolutely sure that the (video?) library is being scanned? It is more likely that the drive is being spun up to retrieve art, or at least check that art cached **more than 1 day ago** has not been updated and needs re-caching.

Turn on debug, reproduce the behaviour and post a link to the log

**Comment by lameventanas** [comment]
That is possible, but I thought the cache and artwork was stored in kodi's userdata directory, not together with the media.

Is it possible to change this in any way so that it doesn't wake up the disk?

**Comment by KarellenX** [comment]
As you have not really pointed out a bug, but are only searching for assistance on why your hard drives wake, I will close this.

Please continue your search for an answer on the forum.

This might be of interest... https://forum.kodi.tv/showthread.php?tid=342272
