### ISSUE TITLE
Playback aspect ratio not picked up on some mp4 files, Android only, 18.2rc1 still.

### ISSUE THREAD

**Issue by AndrewBienhaus** [xbmc/xbmc#15952]
### Describe the bug
Here is a clear and concise description of what the problem is:

Android Kodi playback of some mp4 files, is not picking up or passing the aspect ratio correctly to the decoder/player, when hardware acceleration/decoding is enabled. 

(sorry, first time on GitHub, doing my best to use the template as Fritsch asked me to) ;-)

All taken from the forum posting at:
https://forum.kodi.tv/showthread.php?tid=340953&pid=2825338#pid2825338

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Playback of all files, would pickup the aspect ratio, and use appropriately, to not distort the image.

## Actual Behavior

Some mp4 files (I have samples) stretch vertically to fill the screen, instead of being letterbox.
Using the onscreen data display, the aspect ratio of these files shows incorrectly as 0.00

## Possible Fix

Disabling the hardware acceleration within Kodi, resolves it, and files playback in the correct aspect ratio. However, on larger files, and in particular when playing back at 1080p, the movie becomes jittery and the sound is affected, without the assistance of the hardware.
(Onscreen display shows that the processor cores are hitting 100%)

Reprocessing these files through handbrake (either back to an mp4, or to an mkv) also resolves the issue.
Perhaps it's just a malformed header, analysis issue, or the like, that only the Android version is having a problem with? (all of the same files are fine on a parallel Windows version)

### To Reproduce

Ensure hardware acceleration is enabled.
1. [http://www.bienhaus.org/jb-mp4.mp4](url)  this one will stretch, and show 0.00 AR
2. [http://www.bienhaus.org/jb-mkv.zip](url)  same snippet, reprocessed, and it will not (had to zip)

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/sibineseko  (updated, clean 18.1)

### Screenshots 
Here are some links or screenshots to help explain the problem:

http://www.bienhaus.org/jb-stats-mp4.jpeg - mp4 showing 0.00AR
http://www.bienhaus.org/jb-stats-mkv.jpeg - same snippet, reprocessed, now showing 2.35AR

http://www.bienhaus.org/jb-screen-mp4.jpeg - playback as it should not look
http://www.bienhaus.org/jb-screen-mkv.jpeg - playback as it should look

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: FireOS 6.2.6.3
 - Kodi version: 18.2rc1 (also in 18.0, 18.1)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Similar report prematurely closed... https://github.com/xbmc/xbmc/issues/15733

**Comment by DaVukovic** [comment]
> Sorry, very new to digging into Android, and don't know exactly how to get this off the device in question... open to a link to instructions, if that is something you want to, or need to see.

As requested by fritsch, we will probably need a debuglog. Instructions can be found here: 

https://kodi.wiki/index.php?title=Log_file

**Comment by Leatherface75** [comment]
Having a similar problem with PVR on Android while it works perfectly everywhere else.

**Comment by AndrewBienhaus** [comment]
Additional:
Between the time of my posts on the Kodi forums, and the time to figure out how to post the details here, I received a few PMs from folks, saying that they had the same issue, and had simply been reprocessing/repackaging files through handbrake to resolve it when important to them.
Perhaps this suggests a bug in error-trapping a malformed header somewhere, for lack of a better term?

DaVukovic, yes, I have read those a few times... but can you suggest a way to move the log file off the stick, and onto my PC? (sorry, really not a regular droid user, and totally ignorant to the quickest way)

**Comment by DaVukovic** [comment]
@AndrewBienhaus 

There's an add-on for it available named "Kodi logfile uploader" which will do exactly what you are asking for. 

- install the add-on
- enable debug logging
- restart your device
- reproduce your issue as fast as you can (don't do anything else)
- use the add-on and upload the log
- get us the link to it

Thanks

**Comment by AndrewBienhaus** [comment]
Awesome @DaVukovic thanks. Exactly what I needed. :)

done and done, and if I did it right, here's the link:
https://paste.kodi.tv/idefefunux

**Comment by AndrewBienhaus** [comment]
@Rechi I have done my best for a first posting, which part of the rules have I broken?
I have also followed up as requested.

**Comment by DaVukovic** [comment]
> Reports must follow our template and have all relevant fields filled in.
you did that. So :+1:

>A full debug log is always mandatory. 
You did all of that as well. So :+1:

>You may not have any unsupported add-ons installed.
and here the story begins. Have you even tried to look at the link and compare the add-ons you have installed with the list the link points you to? ;) 

In short, you have WAY!!!! to many banned add-ons installed. Please remove all of them (I would suggest a factory reset, but that's up to you) and provide a new and clean logfile

Thanks

**Comment by AndrewBienhaus** [comment]
Ah. That.
ok.
I have access to a dozen of these sticks... so I'll fire another one up, and go from there.
Thanks for the clarity. :)

**Comment by AndrewBienhaus** [comment]
thanks for the patience with me.
I have only 4 addons on this additional stick, and none of them are on the banned list.

new log file (as the result was the same) is at:
https://paste.kodi.tv/sibineseko

(I will also update the template above)

**Comment by woutervanh** [comment]
I (and a quick search gave a lot of others) have a similar issue with PVR-content. I have a TV-headend server and using the official kodi client. HD-video look ok, but SD-video has the wrong aspect ratio. I have this issue on my Android TV (mi box) as on my smartphone android (samsung galaxy A3). On a raspberry pi, it works perfectly, so it seems it has someting to do with Android + kodi

**Comment by Leatherface75** [comment]
Same problem here but i also see this problem on a friends Wetek Play 2 with LibreELEC so i think its the drivers that many android boxens use.

**Comment by CastagnaIT** [comment]
i tested sample test on current Kodi 20 nightly on three
Android devices Nvidia shield, Honor, Belink and Windows AMD system

i can confirm AR value to 0 (imo suggest a ffmpeg problem) but the images on screen have the right aspect, so letterbox and not stretched

so if someone else want confirm or deny behaviour on Kodi 20,
otherwise the issue can be closed

**Comment by AndrewBienhaus** [comment]
Yes. This got fixed in 19 I think?
________________________________

**Comment by CastagnaIT** [comment]
could be thanks for report
