### ISSUE TITLE
Player use only half of available network bandwidth

### ISSUE THREAD

**Issue by mougnibas** [xbmc/xbmc#15954]
### Describe the bug
Player use only half of available network bandwidth.

## Expected Behavior
Player should use all the available network bandwidth.

## Actual Behavior

With a 80Mb/s video content, when 90Mb/s is available, player will read up to 42Mb/s.

## Possible Fix

No idea how to fix this behavior...

### To Reproduce

1. Get/Make a video content at network target bitrate (80Mb/s for 100Mb NIC, with 256Mb buffer using libx265), on a remote computer
2. Using ssh, transfert this file to /dev/null to get the actuel transfert rate.
3. On the remote computer, monitor the NIC usage to confirm the transfert rate
4. Start to play the remote content (tested with SMB protocol)
5. On the remote computer, monitor again the NIC usage. This should be half the previous rate.
6. The player buffer can't be filled (or if you "pause", the buffer will be filled, then after "unpause", the buffer will decrease to 0%).

This behavior can be reproduce using two powerline network adapter, to reduce the network available bandwidth (adapt the bitrate content to match this new network speed).

## Debuglog

It's not a crash or something. Can't provide a debug log.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The context / history : 

I've a powerline network at home.
I can achieve up to 4.50MiB/s (42Mb/s) transfert, so I've transcoded some content to almost match this speed (4.00MiB/s).
This wasn't work at all, so I've set a 3MiB/s bitrate.
Still nothing! What the hell ?
2MiB/s is fine. Wait, what ?
Is it an hardware bottleneck ? Let's transfert a file while playing the remote content...
Server upload at 2MiB/s. Fine, let's begin the transfert.
Server is now uploading at 4.5MiB/s.
Why ? What is happening ?

### Your Environment
Used system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP
-  [x] LePotato (S905X-CC) / LibreELEC (9.0.1) / Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment]
You should still provide a (full) debug log, even if not a crash. In this case of you playing the file question. Also, it's not entirely clear to me whether you're able to play the file at all.

**Comment by DaVukovic** [comment]
No log provided

Issue closed
