### ISSUE TITLE
inputstream.adaptive not available in official kodi repo anymore

### ISSUE THREAD

**Issue by momo42** [xbmc/xbmc#15965]
---
name: Problem report
about: Create an extensive report to help us document a problem

---

### Describe the bug
Here is a clear and concise description of what the problem is:

Today I installed Kodi 18.0 on a new Android device (version from f-droid) and unlike before I wasn't able to install "InputStream Adaptive" from official kodi repository. Only "RTMP Input" is available under "Video InputStream Addons".

Then I checked my old Android device and saw that InputStream Adaptive (2.3.13) is still installed but on its info screen the source repository is remarked as "unknown".

Before I found this issue tracker I already opened a corresponding bug report over at InputStream Adaptive project: https://github.com/peak3d/inputstream.adaptive/issues/253

I'm just a user and have really no idea where the problem is. So please chose the right place to  discuss/fix this issue. Thanks for your time!

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

"InputStream Adaptive" should be in official kodi repository

## Actual Behavior

"InputStream Adaptive" is not available in official kodi repository

### To Reproduce

1. try to install "InputStream Adaptive" from official kodi repository

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: various
 - Kodi version: 18.0 (from F-Droid)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Rechi** [comment]
This is a F-Droid building/packaging issue.

**Comment by fachprojekt** [comment]
sad news. Didn't realize that on my old tablet KODI has been installed as apk. Any idea how to fix that f-droid problem? Will F-Droid version be broken forever? btw: Whats the recommended way for installing KODI on a non-google android device? Is KODI on android able to update itself?

**Comment by kib** [comment]
> Any idea how to fix that f-droid problem? 
Not really, they need to package Kodi correctly.

> Whats the recommended way for installing KODI on a non-google android device?
APKs can be downloaded directly from our site

> Is KODI on android able to update itself?
Yes, when installed from the play store.

**Comment by licaon-kter** [comment]
@kib What does the F-Droid build do wrong exactly?

**Comment by Eluminae** [comment]
Is there anyway to bypass the problem. I just cannot install inputstream.adaptive atm

**Comment by earithramir** [comment]
any news on this, just migraded from linux to android 10, just to find all my addons to be unusedfull.

**Comment by fuzzard** [comment]
This issue is/was an f-droid packaging issue. 

Inputstream.adaptive is a binary addon, and is bundled with the application from official sources (Google Play store, kodi website for sideloading)

If your issue stems from an install from one of those locations, create a separate issue, with debug logs.

if your issue is from an F-Droid (or some other source) installation, you need to contact the packager for a fix.

**Comment by earithramir** [comment]
Hi, i will do so tonigh. I indeed installled the latest kodi from the playstore yesterdag or the day before.
Thanks for the quick response.
