### ISSUE TITLE
Kodi does not render Indic scripts correctly in labels

### ISSUE THREAD

**Issue by scott967** [xbmc/xbmc#15968]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi nominally provides support for Indic Languages (language resources exist for at least Hindi and Malayalam).  Indic languages generally use their own scripts.  For Hindi, Devanagari and for Malyalam, Malayalan.  There have been requests for additional languages including Kannada and Bengali (both of these have their own scripts as well).

Unicode 12.0 provides codepoints and rules for composing characters in these scripts.

Default skin Estuary does not provide font support for  Indic languages, but it is possible for addon skins or advanced users to install  a suitable ttf font.  When an appropriate font is installed it is possible to switch language in the UI.

When viewing labels from Indic scripts in the UI, the rendered form is incorrect

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Indic scripts are rendered correctly

## Actual Behavior

Indic scripts are rendered incorrectly.  See screenshot of "lorem ipsum" style sample text in Kodi 19A1 nightly and compared to Windows text program "Babelpad" (as an alternative, use "Libre Office")

## Possible Fix

In investigating how Kodi rendering labels it appears the library freetype2 is used to access ttf fonts to extract the needed glyphs and associated table data and then render the resulting characters to bitmaps possibly with hinting.  Unfortunately, it appears that several years ago freetype project elected to terminate support for open type character shaping as being "outside scope".  As a result Kodi is unable to apply the shaping rules needed for Indic language scripts.  It appears that the shaping algorithm support that was originally part of freetype has been incorporated into its own project , HarfBuzz.  It is unknown what would be required to incorporate any libraries from HarfBuzz library.

### To Reproduce

1. Install a suitable font into Estuary that supports Malyalam script (tested: Microsoft Kartika.ttf )
2. In Kodi interface settings, select font and set language to Malayalam (requires download and install of the language resource addon)
3.  Observe sample text (I created a sample text for a movie plot that I scraped from nfo file to display on the movie info dialog window).

### Debuglog

The debuglog can be found here:
https://pastebin.com/1fChxYxm

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://i.imgur.com/IPywBfM.jpg

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Investigation started after user support request on Kodi forum.

Sample text in utf-8 encoding:
https://pastebin.com/L7VSakpg

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 7 sp1 x64
 - Kodi version: 19 A1 190417 nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
Hi!

This would surely be a cool feature to have, but you are kindly requested to raise feature requests in the appropriate [forums section](https://forum.kodi.tv/forumdisplay.php?fid=9) - thanks!
