### ISSUE TITLE
Logfile Uploader max size 1 MB

### ISSUE THREAD

**Issue by awtoner** [xbmc/xbmc#15979]
### Describe the bug
Here is a clear and concise description of what the problem is:

The max size file for the Kodi Logfile Uploader add-on is apparently 1 MB. It is easy to exceed this size limit, rendering the Logfile Uploader useless for my recent debugging and requiring me to use other methods to transfer the logfile.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I should be able to create a reasonably large logfile and easily upload it for debugging and posting to bug reports without jumping through hoops, using the file manager, etc.

## Actual Behavior

An error appears:
Kodi Logfile Uploader
Error posting the kodi.log file
This file is too large. Max size is 1MB.

## Possible Fix

Increase the limit

### To Reproduce

1. Install the Logfile Uploader add-on then enable logging in settings
2. Do something for a few minutes, in my case it was watching a few minutes of The Simpsons on a ripped DVD folder to reproduce a problem
3. Disable logging to limit logfile size
3. Attempt to upload a logfile with the uploader add-on

### Debuglog

The debuglog can be found here:
Sorry, I'm not going through the hassle to create a logfile for this obvious issue.

### Screenshots 
Here are some links or screenshots to help explain the problem:

None

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: both OSMC and LibreELEC
 - Kodi version: 18.1 - 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Jalu1** [comment]
From what I can tell, this addon is maintained [here](https://gitlab.com/ronie/script.kodi.loguploader). I have found the part limiting the file size. I can fork the repo there, but what do you think a more reasonable max size would be?

**Comment by awtoner** [comment]
Both of my recent logs have been just over to 1 MB. I tried posting 10 MB to https://paste.ubuntu.com/ and that seemed to go just fine. I don't know what the practical limit is, but 10 MB seems reasonable. Thanks.

**Comment by KarellenX** [comment]
The Logfile uploader posts to paste.kodi.tv

This site has the file size limit and accepts approx 1MB files or approx 8,800 lines of a typical logfile.

The request should be for the site to increase the file size limit.

This is not a Kodi bug, and would be better asked in the forum.

**Comment by DaVukovic** [comment]
@awtoner 

If you are talking about the log at your other issue you opened, then you should probably disable things at start which you don't need. For example a library scan/update at startup or pvr services. Nearly everything which might not be related to the bug you want to report should be disabled. That will decrease the logsize and it might be easier for a dev to find the issue. 

As Karellen is right, this is not a Kodi bug, probably a feature request and this should be spoken about at the forums.

Thanks
