### ISSUE TITLE
Building with internal fstrcmp fails

### ISSUE THREAD

**Issue by rezso** [xbmc/xbmc#15989]
Building Leia with internal fstrcp fails:

make[2]: *** No rule to make target 'build/lib/libfstrcmp.a', needed by 'kodi-x11'.  Stop.
The libfstrcmp.a is really missing lib, because the build system builds the shared lib only.
(In addition, the fstrcmp build requires ps2pdf and groff to build mans and pdf documentation, which is garbage in this case.)

**Comment by DaVukovic** [comment]
Have you installed libfstrcmp-dev ?

**Comment by rezso** [comment]
No. I haven't any libfstrcmp package.

**Comment by rezso** [comment]
Here is the libtool link command output:

`libtool: link: x86_64-linux-gnu-gcc -shared  -fPIC -DPIC  lib/ac/.libs/string.o lib/.libs/downcase.o lib/.libs/fmemcmp.o lib/.libs/fmemcmpi.o lib/.libs/fstrcasecmp.o lib/.libs/fstrcasecmpi.o lib/.libs/fstrcmp.o lib/.libs/fstrcmpi.o lib/.libs/fstrcoll.o lib/.libs/fstrcolli.o lib/.libs/fwcscmp.o lib/.libs/fwcscmpi.o lib/.libs/mbs_to_wcs.o lib/.libs/nmalloc.o lib/.libs/program_name.o lib/.libs/version.o lib/.libs/version_print.o    -g -O2   -Wl,-soname -Wl,libfstrcmp.so.0 -o lib/.libs/libfstrcmp.so.0.6.0
libtool: link: (cd "lib/.libs" && rm -f "libfstrcmp.so.0" && ln -s "libfstrcmp.so.0.6.0" "libfstrcmp.so.0")
libtool: link: (cd "lib/.libs" && rm -f "libfstrcmp.so" && ln -s "libfstrcmp.so.0.6.0" "libfstrcmp.so")
libtool: link: ( cd "lib/.libs" && rm -f "libfstrcmp.la" && ln -s "../libfstrcmp.la" "libfstrcmp.la" )
libtool: link: gcc -g -O2 -Wall -Wextra -Wshadow -o bin/.libs/fstrcmp fstrcmp/.libs/main.o  lib/.libs/libfstrcmp.so -Wl,-rpath -Wl,/var/uhubuild/work/compile/build/build/lib
config.status: creating script/test_prelude.sh
libtool: compile:  gcc -g -O2 -Wall -Wextra -Wshadow -I. -c test_user/main.c  -fPIC -DPIC -o test_user/.libs/main.o
libtool: link: gcc -g -O2 -Wall -Wextra -Wshadow -o bin/.libs/test_user test_user/.libs/main.o  lib/.libs/libfstrcmp.so -Wl,-rpath -Wl,/var/uhubuild/work/compile/build/build/lib
[  1%] Performing install step for 'fstrcmp'
libtool: warning: 'lib/libfstrcmp.la' has not been installed in '/var/uhubuild/work/compile/build/build/lib'
libtool: install: /bin/install -c bin/.libs/fstrcmp /var/uhubuild/work/compile/build/build/bin/fstrcmp
libtool: install: /bin/install -c -m 644 lib/.libs/libfstrcmp.so.0.6.0 /var/uhubuild/work/compile/build/build/lib/libfstrcmp.so.0.6.0
libtool: install: (cd /var/uhubuild/work/compile/build/build/lib && { ln -s -f libfstrcmp.so.0.6.0 libfstrcmp.so.0 || { rm -f libfstrcmp.so.0 && ln -s libfstrcmp.so.0.6.0 libfstrcmp.so.0; }; })
libtool: install: (cd /var/uhubuild/work/compile/build/build/lib && { ln -s -f libfstrcmp.so.0.6.0 libfstrcmp.so || { rm -f libfstrcmp.so && ln -s libfstrcmp.so.0.6.0 libfstrcmp.so; }; })
libtool: install: /bin/install -c -m 644 lib/.libs/libfstrcmp.lai /var/uhubuild/work/compile/build/build/lib/libfstrcmp.la
`

Kodi "main" cmake options:
	-DVERBOSE=ON \
	-DENABLE_INTERNAL_FLATBUFFERS=ON \
	-DENABLE_INTERNAL_FMT=ON \
	-DENABLE_INTERNAL_FSTRCMP=ON \
	-DENABLE_INTERNAL_RapidJSON=ON \
	-DJava_JAVA_EXECUTABLE=/usr/lib/java/jre/bin/java
