### ISSUE TITLE
External subtitles out of sync when playing ISOs

### ISSUE THREAD

**Issue by 1024mb** [xbmc/xbmc#15983]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing ISOs the external subtitles are out of sync. They are ahead for at least 1 minute, I haven't measured how much actually.
I do know that the subs are well synchronized because I used the m2ts to make the synchronization and also I tested the sub using MPC-BE and playing the ISO mounted to a virtual drive.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Play the movie with the subtitles well synchronized.

## Actual Behavior

Kodi plays the movie but the subtitles are out of sync.

## Possible Fix

I don't know but I guess Kodi is playing the subtitle the same moment when the ISO is loaded so the ads and warnings are counting for the player and that's why it shows the sub out of sync, it has started playing, but not being shown, before the actual movie has started playing. I don't know, is what I can guess.

### To Reproduce

1. Load ISO movie.
2. Select any sub in the Setup menu because otherwise Kodi won't show any sub.
3. Play.
4. From the OSD select the external sub.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/fepojadejo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Are they needed?

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I don't know what to say.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro 10.0.17763
 - Kodi version: 19.0-ALPHA1

The same was happening in Kodi 18.1.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by icetea0822** [comment]
The Android version have the same problem!

**Comment by 1024mb** [comment]
> 
> 
> The Android version have the same problem!

Yep, still not fixed. Hope someone can look into this.

**Comment by RRRichardLi** [comment]
still not fixed.

**Comment by 78zhanghao87** [comment]
Same problem in kodi 19.I guess possible Blu-ray have Multiple chapter,main movie chapter is not chapter 1,but subtitles timer is counting by chapter 1.

**Comment by laithalfar** [comment]
Would an external disc be needed to test this issue? If not can someone provide an .iso file somehow to make the testing process easier, as I cannot find any online?

**Comment by 1024mb** [comment]
> Would an external disc be needed to test this issue? If not can someone provide an .iso file somehow to make the testing process easier, as I cannot find any online?

Here you can download an ISO: https://download.blender.org/durian/movies/

**Comment by enen92** [comment]
> > Would an external disc be needed to test this issue? If not can someone provide an .iso file somehow to make the testing process easier, as I cannot find any online?
> 
> Here you can download an ISO: https://download.blender.org/durian/movies/

Can you test nexus or omega? I think I fixed some similar issue a while ago

**Comment by enen92** [comment]
Closing as this can't be reproduced on omega, I fixed a similar issue a while ago but can't link to the original PR.
