### ISSUE TITLE
The Crow is incorrectly scraped as Crows / scraper should prefer exact title match

### ISSUE THREAD

**Issue by HunterZ** [xbmc/xbmc#15985]
### Describe the bug
Here is a clear and concise description of what the problem is:

The Crow (1994)\The Crow (1994).mkv is incorrectly scraped as Crows.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Scraper should prefer exact title match.

## Actual Behavior

Scraper mis-detects as Crows. Manual refresh shows Crows as the first suggestion, followed by The Crow.

### To Reproduce

1. Create a folder called The Crow (1994)
2. Put a video file in the folder called The Crow (1994).mkv (or .avi or whatever)
3. Update library

### Debuglog

The debuglog can be found here:
N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Trying to import The Crow (1994) into my library.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.1 release

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Can't confirm

![grafik](https://user-images.githubusercontent.com/7235787/56710491-b7b4ac00-6726-11e9-889f-a3a39e4bac81.png)

And as you have missed to provide a debuglog, we can't even help now. This might depend on the scraper in use and which setting you have done for it. 

Additionally the issue tracker is not meant for support in regard of scraping questions. Please ask those questions at the forums.
