### ISSUE TITLE
Estuary settings scrollbar "traps" focus

### ISSUE THREAD

**Issue by MilhouseVH** [xbmc/xbmc#15994]
### Describe the bug

The stock Estuary skin has a scrollbar in the "Main menu items" skin setting and if the user moves focus to this scrollbar there is no way to move the focus back to the settings other than to press "back" and exit from the skin settings.

## Expected Behavior

Should be able to move the focus back from the scrollbar to the settings.

## Actual Behavior

Focus is "trapped" by the scrollbar.

### To Reproduce

1.  Go to Settings > Interface > Skin > - Configure skin... > Main menu items
2. Move the input focus to the scrollbar
3. Focus is now "trapped", only option is to press "Back" (on keyboard/remote/mouse)

### Debuglog

I don't think it's likely to be relevant, but it's here: http://ix.io/1Hhc

### Screenshots 

Start here:
![s1](https://i.imgur.com/b1Dul4j.jpg)

Then move focus to the scrollbar, here:
![s2](https://i.imgur.com/INr0Fzr.jpg)

and now you are unable to return to the position in the first screenshot as focus is "trapped" by the scrollbar.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC RPi/X86_64 and Ubuntu x86_64.
 - Kodi version: 19 (latest master), but I've gone back through 365 days of test builds and it's the same in Kodi 18 from 16 April 2018, so not a new issue.

**Comment by HitcherUK** [comment]
Thanks, fixed https://github.com/xbmc/xbmc/pull/15996
