### ISSUE TITLE
PVR EPG first channel data missing and +1 shift all list

### ISSUE THREAD

**Issue by lama18** [xbmc/xbmc#15990]
### Describe the bug

PVR is missing the first line of EPG data and at the same time it is shifted by one channel, ie. (see screenshot) program that is for CT1 is in position for CT2 etc, interesting that everything in the "All channels" view is OK, only "Guide" is problem.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Open Kodi
Open PVR (TV), Channel list etc.

## Possible Fix

In <19 it works .. at the moment I have 18.2 and i works fine.

### To Reproduce

1.  Open Kodi
2. Open PVR (TV), Channel list etc.
3. If I try to erase the program data, or the epg12.db file, everything will load fine, but the error will be repeated after Kodi restarts.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ulagufesag.kodi

### Screenshots
![image](https://user-images.githubusercontent.com/20426629/56516723-8d52cb00-653b-11e9-9b51-44dcaa19727b.png)

![image](https://user-images.githubusercontent.com/20426629/56516383-9727fe80-653a-11e9-9ef9-29f5c8decbf9.png)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.0-ALPHA1 Git:20190425

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Reopened https://github.com/xbmc/xbmc/issues/15960.
