### ISSUE TITLE
4K Resolution in xbmc/utils/StreamDetails.cpp Line 573 is Incorrectly Specified

### ISSUE THREAD

**Issue by chadm** [xbmc/xbmc#15992]
### Describe the bug

4K UHD movies are 3840x2160.  The code currently assumes it is 4096x2160:

From https://github.com/xbmc/xbmc/blob/master/xbmc/utils/StreamDetails.cpp#L573

  else if (iWidth <= 4096 && iHeight <= 2160)
return "4K";

This should be 
  else if (iWidth <= 3840 && iHeight <= 2160)
return "4K";

**Comment by chadm** [comment]
Template is longer than the one line code change.

**Comment by pkerling** [comment]
Did you consider making a pull request?

**Comment by rmrector** [comment]
I don't agree. 4096px wide 4K videos do exist and shouldn't be identified as 8K.

> The term "4K" is generic and refers to any resolution with a horizontal pixel count of approximately 4,000.

-- https://en.wikipedia.org/wiki/4K_resolution

**Comment by fritsch** [comment]
Original code is correct, nothing to change.

**Comment by pkerling** [comment]
I agree, misread the change. DCI 4K is 4096x2160. @chadm Please see https://en.wikipedia.org/wiki/4K_resolution#4096_%C3%97_2160

**Comment by arnova** [comment]
Perhaps we could use a +/- margin for what we consider 720/1080/4k instead of being so strict?

**Comment by chadm** [comment]
Sorry for the DCI/SMPTE/ITU standards collision/assumption (I read SMPTE).  From the same link provided:

_"In 2012, the International Telecommunication Union, Radiocommunication Sector published Recommendation ITU-R BT.2020, also known as the Ultra High Definition Television (UHDTV) standard.[16] This standard adopts the same image parameters defined in SMPTE ST 2036-1.[17]

Although the UHDTV standard does not define any official names for the formats it defines, ITU typically uses the terms "4K", "4K UHD", or "4K UHDTV" to refer to the 3840 × 2160 system in public announcements and press releases ("8K" for the 7680 × 4320 system).[18] In some of ITU's other standards documents, the terms "UHDTV1" and "UHDTV2" are used as shorthand"_

I opened this bug because none of the UHD discs I have ripped/stored on my NAS deviates from 3840x2160.

**Comment by pkerling** [comment]
I think it's fine if we just keep everything as "4K" in Kodi
