### ISSUE TITLE
coredump with abort when accessing a samba share

### ISSUE THREAD

**Issue by mobidyc** [xbmc/xbmc#15995]
### Describe the bug
try to add a SAMBA share crashes kodi with a coredump

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
list the content of the share to select a folder to add as a media source.

## Actual Behavior
crashes when accessing the listed server names

## Possible Fix
looks similar to https://lists.samba.org/archive/samba/2018-November/219141.html
but different as the coredump does not point to "read_data" but to "name_queries_send"

### To Reproduce
1. add a media source
2. enter into the SMB section
3. crash occurs  immediately

### Debuglog
quick core info:
```
# coredumpctl dump >/tmp/coredumpctl.dump
           PID: 5724 (kodi-x11)
           UID: 1000 (mobidyc)
           GID: 1000 (mobidyc)
        Signal: 6 (ABRT)
     Timestamp: Fri 2019-04-26 12:15:54 CEST (6h ago)
  Command Line: ./kodi-x11
    Executable: /home/mobidyc/kodi-build/kodi-x11
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (mobidyc)
       Boot ID: 808458435f5342fa859add350f55c0da
    Machine ID: 1d181e6dfc0f4361848892790fd76cc7
      Hostname: argon
[kodi-infos.zip](https://github.com/xbmc/xbmc/files/3122268/kodi-infos.zip)

       Storage: /var/lib/systemd/coredump/core.kodi-x11.1000.808458435f5342fa859add350f55c0da.5724.1556273754000000.lz4
       Message: Process 5724 (kodi-x11) of user 1000 dumped core.
                
                Stack trace of thread 5724:
                #0  0x00007f06062ca57f raise (libc.so.6)
                #1  0x00007f06062b4895 abort (libc.so.6)
                #2  0x00007f06044d07d5 n/a (libgenrand-samba4.so)
                #3  0x00007f0605229c6e name_query_send (libgse-samba4.so)
                #4  0x00007f060522a869 name_resolve_bcast_send (libgse-samba4.so)
                #5  0x00007f060522ab7b name_resolve_bcast (libgse-samba4.so)
                #6  0x00007f0607226b2a n/a (libsmbclient.so.0)
                #7  0x00007f0607223935 smbc_opendir (libsmbclient.so.0)
                #8  0x0000000000c1b465 n/a (/home/mobidyc/kodi-build/kodi-x11)
                #9  0x0000000000eabcc1 n/a (/home/mobidyc/kodi-build/kodi-x11)
More than one entry matches, ignoring rest.
```

"bt" and "bt full" info in attachment
[kodi-bt.log](https://github.com/xbmc/xbmc/files/3122253/kodi-bt.log)
[kodi-bt-full.log](https://github.com/xbmc/xbmc/files/3122254/kodi-bt-full.log)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
fresh compiled kodi version.
last commit: 439aa4a184 - (HEAD -> Leia, origin/Leia) Merge pull request #15972 from ksooo/leia-fix-media-source-pathsubstitutions

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: fedora 29
 - Kodi version: Leia

**Comment by chhe** [comment]
I get the same error using a freshly compiled Kodi from master on Fedora 31. Here is the strange part: if I compile Kodi with FFmpeg libraries provided by RPMFusion everything works fine. If I let Kodi compile it's own FFmpeg libs, Kodi crashes with the described error everytime I try to access an SMB share.
