### ISSUE TITLE
PaPlayer handles *.dtshd music files in the wrong way

### ISSUE THREAD

**Issue by michmetz** [xbmc/xbmc#16022]
### Describe the bug
Here is a clear and concise description of what the problem is:

in 17.6 PaPlayer plays *.dtshd music files ok. The Configuration: PC ->HDMI->Denon AVR
using Wasapi ->Denon AVR shows DTS-HD
in 18, 18.1, 18.2 same configuration as above, same music file - all is exactly the same, but
Denon AVR shows DTS.
VideoPlayer(DVDPlayer) in 17.6 and 18,18.2+18.2 is ok->Denon AVR shows DTS-HD.
I copied out the lines of the log files I had made and put them in but you can see the log files also
in  Kodi/support/general support/windows in the thread: Bug - No passthrough with Paplayer

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

VideoPlayer(DVDPlayer) doesnt play my music*.dtshd files from the beginning and doesnt
initialize Milkdrop.
Thats why I would be happy if PaPlayer would recognize dtshd files in that way like in 17.6

One wish do i have too: Crossfade between dtshd files does not work in no Kodi Version - that would be sensationel if you could manage that.
Excuse my bad english and if something is wrong with the text above please understand that it is the first posting so excuse.

## Possible Fix

Maybe using the code of 17.6

### To Reproduce

1. http://www.mediafire.com/file/bjo9o89c32oxfpa/Music.dtshd/file
2.
3.

### Debuglog

The debuglog can be found here:
17.6 with Paplayer-> *.dtshd in the avr display and milkdrop is ok:

              CActiveAESink::OpenSink - trying to open device WASAPI:{2E0C8FEB-FFD8-4AC1-AF96-7B257E97C6A6}                             
              CAESinkWASAPI::InitializeExclusive: WASAPI Exclusive Mode Sink Initialized using: AE_FMT_S16NE, 192000, 8
DEBUG:  CActiveAESink::OpenSink - WASAPI Initialized:
DEBUG:   Output Device : HDMI - Denon AVR (AMD High Definition Audio Device)
DEBUG:   Sample Rate   : 192000
DEBUG:   Sample Format : AE_FMT_S16NE
DEBUG:   Channel Count : 8
DEBUG:   Channel Layout: FL,FR,FC,LFE,BL,BR,SL,SR
DEBUG:   Frames        : 9600
DEBUG:   Frame Size    : 16

18.1 with paplayer->*.dts in the avr display and no milkdrop:

2019-03-12 10:05:45.725 T:8792 INFO: CAEStreamParser::SyncDTS - dtsHD (core) stream detected (6 channels, 48000Hz, 16bit BE, period: 512, syncword: 0x41a29547, target rate: 0x18, framesize 2080))

CActiveAESink::OpenSink - initialize sink
DEBUG:  CActiveAESink::OpenSink - trying to open device WASAPI:{2E0C8FEB-FFD8-4AC1-AF96-7B257E97C6A6}
              CAESinkWASAPI::InitializeExclusive: WASAPI Exclusive Mode Sink Initialized using: AE_FMT_S24NE4MSB, 44100, 2
DEBUG: CActiveAESink::OpenSink - WASAPI Initialized:
DEBUG:   Output Device : HDMI - Denon AVR (AMD High Definition Audio Device)
DEBUG:   Sample Rate   : 44100
DEBUG:   Sample Format : AE_FMT_S24NE4MSB
DEBUG:   Channel Count : 2
DEBUG:   Channel Layout: FL, FR
DEBUG:   Frames        : 2208
DEBUG:   Frame Size    : 8

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro
 - Kodi version: 17.6, 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
@michmetz Could you please be so kind and proviide the full debuglog of both Kodi versions. And it would be nice if you could do that using some paste service like: paste.kodi.tv

Thanks in advance.

**Comment by michmetz** [comment]
Kodi 18.1 Paplayer debug log: https://paste.kodi.tv/iliyahecap.kodi
  Kodi 18.1 VideoPlayer debug log: https://paste.kodi.tv/xajotarove.kodi
  Kodi  17.6 PaPlayer debug log: https://paste.kodi.tv/ziduzanari.kodi
Thanks that you are looking for
Michael

**Comment by fritsch** [comment]
See:
```
diff --git a/xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp b/xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp
index 0b3c07e416..2e6e77365b 100644
--- a/xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp
+++ b/xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp
@@ -622,7 +622,7 @@ unsigned int CAEStreamParser::SyncDTS(uint8_t *data, unsigned int size)
       hd_sync = data[m_fsize + header_size] << 24 | data[m_fsize + header_size + 1] << 16 | data[m_fsize + header_size + 2] << 8 | data[m_fsize + header_size + 3];
 
       /* set the type according to core or not */
-      if (m_coreOnly)
+      if (m_coreOnly && hd_sync != DTS_PREAMBLE_XLL)
         dataType = CAEStreamInfo::STREAM_TYPE_DTSHD_CORE;
       else if (hd_sync == DTS_PREAMBLE_XLL)
         dataType = CAEStreamInfo::STREAM_TYPE_DTSHD_MA;
```

That though will break for old AVRs without DTS-HD support I assume.

@graham8 Any idea on how we can distinguish that properly withouth breaking the fallback?

**Comment by fritsch** [comment]
Got it ... PR upcoming.

**Comment by fritsch** [comment]
Leia based Win64 build will be upcoming here: http://mirrors.kodi.tv/test-builds/windows/win64/

**Comment by jjd-uk** [comment]
This is the Win64 build http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20190501-2842cb02-PR16027-merge-x64.exe

**Comment by michmetz** [comment]
I downloaded the test file and will try it. Its great that you all are so enganged in that project.
Thanks a lot. Michael.
PS: Maybe it would be possible to declare *.dtshd and *.truehd files to music files like mp3 or flac without using advancedsettings.xml and maybe it would be possible to put them in the database too. You can tag
dtshd files (renaming to mp3, tagging, renaming to dtshd - its in the database but get lost with the next file which gets put in). Maybe if its declared to music files also crossfade would be okay - that would be the greatest.
Thanks in advance and remember my bad english Michael

**Comment by fritsch** [comment]
PAPlayer misses two lines of code for TrueHD.

Is there an official source (Where can I buy them?) for ".dtshd or .truehd" file endings? Which players are meant to play them?

**Comment by jjd-uk** [comment]
Crossfade won't happen I believe as you need to mix the tracks, so this can only be done with PCM audio (AAC, mp3) or passthrough audio (e.g. dts-hd) decoded to LPCM.

**Comment by fritsch** [comment]
From the list:
```
  m_musicExtensions = ".nsv|.m4a|.flac|.aac|.strm|.pls|.rm|.rma|.mpa|.wav|.wma|.ogg|.mp3|.mp2|.m3u|.gdm|.imf|.m15|.sfx|.uni|.ac3|.dts|.cue|.aif|.aiff|.wpl|.xspf|.ape|.mac|.mpc|.mp+|.mpp|.shn|.zip|.wv|.dsp|.xsp|.xwav|.waa|.wvs|.wam|.gcm|.idsp|.mpdsp|.mss|.spt|.rsd|.sap|.cmc|.cmr|.dmc|.mpt|.mpd|.rmt|.tmc|.tm8|.tm2|.oga|.url|.pxml|.tta|.rss|.wtv|.mka|.tak|.opus|.dff|.dsf|.m4b";
```

You could name them just .dts and it would work, not matter if dtshd or dts.

**Comment by jjd-uk** [comment]
@fritsch one source I found https://ultimae.com/product-category/product-type/multichannel-music/dts-hd-master-audio/

**Comment by fritsch** [comment]
Crossfade won't work for any RAW Codec, therefore this is not a stopper for TrueHD, as it's the same for the others as well.

It's easy to add it:
```
diff --git a/xbmc/cores/paplayer/VideoPlayerCodec.cpp b/xbmc/cores/paplayer/VideoPlayerCodec.cpp
index d761d09294..f3195c9d16 100644
--- a/xbmc/cores/paplayer/VideoPlayerCodec.cpp
+++ b/xbmc/cores/paplayer/VideoPlayerCodec.cpp
@@ -514,6 +514,11 @@ CAEStreamInfo::DataType VideoPlayerCodec::GetPassthroughStreamType(AVCodecID cod
       format.m_streamInfo.m_sampleRate = samplerate;
       break;
 
+    case AV_CODEC_ID_TRUEHD:
+      format.m_streamInfo.m_type = CAEStreamInfo::STREAM_TYPE_TRUEHD;
+      format.m_streamInfo.m_sampleRate = samplerate;
+      break;
+
```

And:

```
index 2ba973aed1..0fd07bcd22 100644
--- a/xbmc/settings/AdvancedSettings.cpp
+++ b/xbmc/settings/AdvancedSettings.cpp
@@ -428,7 +428,7 @@ void CAdvancedSettings::Initialize()
   m_databaseVideo.Reset();
 
   m_pictureExtensions = ".png|.jpg|.jpeg|.bmp|.gif|.ico|.tif|.tiff|.tga|.pcx|.cbz|.zip|.rss|.webp|.jp2|.apng";
-  m_musicExtensions = ".nsv|.m4a|.flac|.aac|.strm|.pls|.rm|.rma|.mpa|.wav|.wma|.ogg|.mp3|.mp2|.m3u|.gdm|.imf|.m15|.sfx|.uni|.ac3|.dts|.cue|.aif|.aiff|.wpl|.xspf|.ape|.mac|.mpc|.mp+|.mpp|.shn|.zip|.wv|.dsp|.xsp|.xwav|.waa|.wvs|.wam|.gcm|.idsp|.mpdsp|.mss|.spt|.rsd|.sap|.cmc|.cmr|.dmc|.mpt|.mpd|.rmt|.tmc|.tm8|.tm2|.oga|.url|.pxml|.tta|.rss|.wtv|.mka|.tak|.opus|.dff|.dsf|.m4b";
+  m_musicExtensions = ".nsv|.m4a|.flac|.aac|.strm|.pls|.rm|.rma|.mpa|.wav|.wma|.ogg|.mp3|.mp2|.m3u|.gdm|.imf|.m15|.sfx|.uni|.ac3|.dts|.cue|.aif|.aiff|.wpl|.xspf|.ape|.mac|.mpc|.mp+|.mpp|.shn|.zip|.wv|.dsp|.xsp|.xwav|.waa|.wvs|.wam|.gcm|.idsp|.mpdsp|.mss|.spt|.rsd|.sap|.cmc|.cmr|.dmc|.mpt|.mpd|.rmt|.tmc|.tm8|.tm2|.oga|.url|.pxml|.tta|.rss|.wtv|.mka|.tak|.opus|.dff|.dsf|.m4b|.dtshd|.truehd";
   m_videoExtensions = ".m4v|.3g2|.3gp|.nsv|.tp|.ts|.ty|.strm|.pls|.rm|.rmvb|.mpd|.m3u|.m3u8|.ifo|.mov|.qt|.divx|.xvid|.bivx|.vob|.nrg|.img|.iso|.udf|.pva|.wmv|.asf|.asx|.ogm|.m2v|.avi|.bin|.dat|.mpg|.mpeg|.mp4|.mkv|.mk3d|.avc|.vp3|.svq3|.nuv|.viv|.dv|.fli|.flv|.001|.wpl|.xspf|.zip|.vdr|.dvr-ms|.xsp|.mts|.m2t|.m2ts|.evo|.ogv|.sdp|.avs|.rec|.url|.pxml|.vc1|.h264|.rcv|.rss|.mpls|.webm|.bdmv|.wtv|.trp|.f4v";
   m_subtitlesExtensions = ".utf|.utf8|.utf-8|.sub|.srt|.smi|.rt|.txt|.ssa|.text|.ssa|.aqt|.jss|.ass|.idx|.ifo|.zip"
```

It's a solved issue, someone with more time than me, then can add it - after testing obviously.

**Comment by fritsch** [comment]
In the meantime, please test the WIN64 build.

**Comment by michmetz** [comment]
Hello, I have tested the build you have linked and *.dtshd files now are working great. AVR shows DTS-HD MA as it should be and thats very great and I'm very happy. 
So: i think (but I'm no coder and maybe  i'm wrong) if *.dtshd files were in that list above ( without using advancedsettings.xml) maybe mikdrop would work again. In 17.6 that happens - in 18, 18.1, 18.2 only
goes with *.dts and not with *.dtshd Files. Crossfading is, if i understand right what you have written, not possible - thats a pitty. DTSHD Music Files are in blurays and you can rip them with hdstreamextractor if you only want the music and don't want a lot of GB with static pictures. So instead of 40 GB you have
3 or 4 GB music files. I think a lot of people would love that quality and would be happy if they could play
it in Kodi with its skins, instead of a player like MPC-BE. MPC-BE also plays *.dtshd files but is a little poor
in his skin and possibilities.
But the most importand thing is: you have solved the *.dtshd problem for me and now i can use 18.2
and thats great. Many Thanks for that.

**Comment by fritsch** [comment]
Crossfade never worked with passthrough. Reason is simple, in order to crossfade we would need to decode RAW formats, mix it and encode it - which basically drives the concept of passthrough nuts.

Will send a PR adding .dtshd to the list. Thanks for feedback. I will push to 18.3-rc1 and to master. You can keep the build I made for you in the meantime.

**Comment by graham8** [comment]
I'm not able to get DTS-HD playing by applying your patch on OSMC.  Investigating....

**Comment by fritsch** [comment]
See the PR I linked, please. There was a root issue to that.

Tested on Linux and Windows. Take it's DTS_XLL and if you use AMLogic there is still these "many" kernel hacks to workaround non standard alsa drivers.

**Comment by graham8** [comment]
So I need both the PR and the patch to AEStreamInfo.  Yes, that works.

**Comment by fritsch** [comment]
Nope - that's totally unlikely. The AEStreamInfo would just overwrite the Supports(format) call by ActiveAE - I think there is something wrong on OSMC.

Cause now you overwrite the capabilities, means: with the AEStreamInfo hack, you could never use DTS Core for such files.

Please find out why supports(format) with format ==DTSHD fails for you on OSMC

**Comment by fritsch** [comment]
Find out why: https://github.com/xbmc/xbmc/pull/16026/commits/6b74bd376b64b58cbae9439363a4985505333844#diff-cfd4da0c21e5e63f53e671b2a50900f5R521 returns false for you.

The whole log ic is: go with DTS-HD, if not supported, go with DTSHD_CORE only.

**Comment by graham8** [comment]
False alarm: in the end re-starting the AVR fixed it.
