### ISSUE TITLE
Enable selecting multiple subtitles 

### ISSUE THREAD

**Issue by moham96** [xbmc/xbmc#16029]
### Describe the bug
Here is a clear and concise description of what the problem is:

This is 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

This is a feature request to enable selecting multiple subtitles in the subtitles dialog, this is useful in some cases like:
-  A user wants to download two subtitles in one go so that he can switch between them later on.
- Downloading multiple subtitles and combining them so they appear simultaneously (one at the top of screen and one on the bottom), this can be useful for multilingual families and people that learn new languages by using TV shows and movies material, I've already modified the opensubtitle addon to include this feature but I had to use a workaround to get the user to select multiple items and it is very annoying since it displays two dialogs
The original discussion on kodi forums: https://forum.kodi.tv/showthread.php?tid=330813

## Actual Behavior

The `xbmcplugin` API doesn't allow  multiselect dialogs.

## Possible Fix

make the `xbmcplugin` accept a parameter let's call it `multiselect` that is `False` by default and when set to `True` it allows multiselect

### To Reproduce

This is how it looks right now with the workaround I mentioned above: https://gfycat.com/fortunatevalidamericancreamdraft
The modified opensubtitles addon can be found here: https://github.com/moham96/service.subtitles.opensubtitles_by_opensubtitles

### Debuglog

The debuglog can be found here:
Not important

### Screenshots 
Here are some links or screenshots to help explain the problem:

see the gfycat link above

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 17

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Leatherface75** [comment]
This is something i have requested for PVR too but could support all types of media.

https://forum.kodi.tv/showthread.php?tid=324344

**Comment by DaVukovic** [comment]
Please use the forums for feature requests: 

https://forum.kodi.tv/forumdisplay.php?fid=9

Thanks
