### ISSUE TITLE
Music library scanning badly handles semicolon in path

### ISSUE THREAD

**Issue by MaximeLussier** [xbmc/xbmc#16032]
### Describe the bug
Here is a clear and concise description of what the problem is:

Sometimes, when there are folder with semicolons, the parser makes mistakes.
When scanning music into the library, the parser creates entries in the MyMusic72.path table like the following:
idPath, strPath, strHash
'38335', 'ftp://user:password@10.35.2.1:21/Music/Soundtrack/Bernard Herrmann; Sinfonia of London, Bruce Broughton/', 'f433c4b3ef7e2742f88870eca6b9a101'
'38336', 'ftp://user:password@10.35.2.1:21/Music/Soundtrack/Bernard Herrmann/Marnie/01 Prelude.mp3; Sinfonia of London, Bruce Broughton/', NULL
 idPath | strPath | strHash

And the entries in the MyMusic72.song table where strFilename is empty.

However, these are NOT for the path with a semicolon but for subsequent folders.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The folders with semicolon should be handled properly.
The path should end before the ";" and the filenames should be in strFilename.

## Actual Behavior

Database is filled in wrong, semicolons are badly handledé

### To Reproduce

1. Create a Music folder with some directories containing semicolon and some not.
2. Scan them into the library
3. Check the DB, some path and strFileName are wrong.
4. The files cannot be played (obviously)

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@MaximeLussier 

Thanks for your report. Can you please provide a debug log which captures the problem.

**Comment by DaveTBlake** [comment]
Not able to reproduce this immediately. 
@MaximeLussier  can you provide a debug log of scanning this folder into the library

**Comment by MaximeLussier** [comment]
@KarellenX @DaveTBlake I will try to reproduce and provide a debug log. The music library is huge and I've renamed the folders to prevent the issue from happening. I will try with a smaller subset of files.

**Comment by DaveTBlake** [comment]
@MaximeLussier a log from scanning a smaller example will be great. I have been unable to reproduce any issue with semi-colon in folder names.
