### ISSUE TITLE
DVD not played when the source is HTTP

### ISSUE THREAD

**Issue by stefano70** [xbmc/xbmc#16038]
### Describe the bug
Here is a clear and concise description of what the problem is:

This problem affect 18.2 and 18.x generally speaking.
Already reported in the past, still not solved.
Having an HTTP source containing ripped DVDs with the classic filesystem structure (VIDEO_TS, .IFO, .VOB, etc.) and selecting to play the .IFO file DOES NOT work. The movie is not played at all.
Exporting the same source using SAMBA, works.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

To have the movie played hitting its .IFO file not only when the source is SAMBA, but also HTTP

## Actual Behavior

selecting to play the .IFO file in a VIDEO_TS folder, exported using HTTP does not work

### To Reproduce

1. having a remote source containing DVD folders
2. exporting the source with HTTP protocol
3. adding this source to Kodi
4. browsing the source from Kodi, choosing a .IFO file and hitting play
5. the movie is not played

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/xalubehusu.kodi
see row # 1577 and following.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.0, 18.1, 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by stefano70** [comment]
debulog and info added.
https://paste.kodi.tv/xalubehusu.kodi
row 1577 and following

**Comment by DaVukovic** [comment]
I guess we don´t need muktiple issues explaining the same problem:

#15694 
#15693 

Please continue the discussion on the issues you already opened.
