### ISSUE TITLE
 Arabic letters not connected when using virtual keyboard 

### ISSUE THREAD

**Issue by moham96** [xbmc/xbmc#16040]
### Describe the bug
Here is a clear and concise description of what the problem is:

There is an issue in the virtual keyboard in kodi when writing in Arabic, Arabic is a compound form language(the letters are connected rather than separated like in Latin), the problem is that the virtual keyboard doesn't connect the letters and instead they are written as isolated letters, the problem doesn't appear when writing using the physical keyboard.
This issue is very old and has been around since Kodi 16 I think  and still no fix
link to old thread that mentions the bug with screenshots:https://forum.kodi.tv/showthread.php?tid=246853
link to trac ticket: https://trac.kodi.tv/ticket/17703

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The letters should be written connected to each other

## Actual Behavior

Arabic letters are isolated

## Possible Fix

This quote from the forum thread linked above may help to find a fix:
> I think the problem here, is that the Arabic keyboard is using the wrong Arabic Unicode block. Instead of using [Arabic Presentation Forms-B](https://en.wikipedia.org/wiki/Arabic_Presentation_Forms-B), it should use the [standard Arabic block](https://en.wikipedia.org/wiki/Arabic_(Unicode_block)).

### To Reproduce

1. open kodi and go to the interface settings and add the Arabic QWERTY keyboard layout
2. go back to the home kodi page and click on the search icon and choose any type of search
3. change the layout to Arabic in the virtual keyboard and try writing an arabic word like "اللغه العربيه"

### Debuglog

The debuglog can be found here:
not applicable since the problem doesn't produce any debug log entries

### Screenshots 
Here are some links or screenshots to help explain the problem:

- This is what it looks like when writing "اللغه العربيه" using virtual keyboard (signifies the problem):
https://i.imgur.com/xUJxlgLl.png
- This is what it looks when writing the same words using the physical keyboard(this is the correct form): 
https://i.imgur.com/XzIDAell.png

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
> I think the problem here, is that the Arabic keyboard is using the wrong Arabic Unicode block. Instead of using [Arabic Presentation Forms-B](https://en.wikipedia.org/wiki/Arabic_Presentation_Forms-B), it should use the [standard Arabic block](https://en.wikipedia.org/wiki/Arabic_(Unicode_block)).

can you check if the correct code block is used in this file:
https://github.com/xbmc/xbmc/blob/master/system/keyboardlayouts/arabic.xml

**Comment by moham96** [comment]
> > I think the problem here, is that the Arabic keyboard is using the wrong Arabic Unicode block. Instead of using [Arabic Presentation Forms-B](https://en.wikipedia.org/wiki/Arabic_Presentation_Forms-B), it should use the [standard Arabic block](https://en.wikipedia.org/wiki/Arabic_(Unicode_block)).
> 
> can you check if the correct code block is used in this file:
> https://github.com/xbmc/xbmc/blob/master/system/keyboardlayouts/arabic.xml

This is the unicode code points of the first row in that file
`'\\u0634\\u0633\\u064a\\u0628\\u0644\\u0627\\u062a\\u0646\\u0645\\u0643\\u0629'`

So I think that comment is not correct

**Comment by peylight** [comment]
The issue is about Kodi.
Kodi separate any characters when we type it. like this:
For example if i type hello in Arabic ==> 'السلام'
And Kodi will be show it like this ==> 'ا‌ل‌س‌ل‌ا‌م'
In some languages like Arabic and Persian, the character must be change when they come together. But in Kodi the characters noting to happened when they come together.
It is tested in Kodi v18.2 by Android v8.1 and the problem exist.

**Comment by peylight** [comment]
I test Kodi 18.2 in Linux.
When i use Kodi keyboard the problem is exist. but when i use Linux native keyboard the letters are works correct and they are not separated.
So the issue is about Kodi virtual keyboard
