### ISSUE TITLE
Kodi WebServer fails to start on Android with no Internet connection

### ISSUE THREAD

**Issue by D3VL-Jack** [xbmc/xbmc#16041]
### Describe the bug
Kodi WebServer fails to start on Android devices where no internet connection is present.

Under windows, Without an internet connection the WebServer is allowed to start.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The WebServer should be allowed to start on devices without an internet connection to allow for other local services & plugins to access Kodi's JSON-RPC via localhost

## Actual Behavior

When Kodi starts without an internet connection, a error message is displayed informing the user that the WebServer failed to start

### To Reproduce

1.  Obtain an Android Device
2.  Disable Data & WiFi
3.  Open Kodi
4.  Attempt to start the WebServer (Settings -> Services -> Control -> Allow remote control via HTTP)

### Debuglog

The debuglog can be found here:
N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Jack-Rogers** [comment]
@Rechi please see my below reasoning as to why the rules have not been ignored.

Reports must follow our template and have all relevant fields filled in. <- Done

A full debug log is always mandatory. <- This is NOT applicable, it contains no errors, nothing. this is a bizarre issue 

You may not have any unsupported add-ons installed. If possible, reproduce on a clean Kodi installation or at least remove all offending add-ons. <- Clean Kodi Install

**Comment by ritiek** [comment]
I was able to reproduce the problem as @Jack-Rogers.

I tried to enable the webserver with mobile data and WiFi turned off but it gave me this error:

![kodi_webserver_error](https://user-images.githubusercontent.com/20314742/57383312-32bc9e80-71cc-11e9-9957-7d078066fc69.png)

and the option automatically turned back off after this error:

![kodi_option_turns_off](https://user-images.githubusercontent.com/20314742/57383311-32240800-71cc-11e9-89a3-f8ff7697f7fa.png)

Here is the log while me doing all this: [kodi_webserver_failed.log](https://gist.githubusercontent.com/ritiek/de68aea06280b8d24c48e1d91d603637/raw/054fecd2a74bee528b49a5f22e3ff38e11dc1cfc/kodi_webserver_failed.log)

----------

And here is the log when I connect to a WiFi network and restart Kodi to enable the webserver successfully: [kodi_webserver_success.log](https://gist.githubusercontent.com/ritiek/de68aea06280b8d24c48e1d91d603637/raw/054fecd2a74bee528b49a5f22e3ff38e11dc1cfc/kodi_webserver_success.log)

**Comment by DaVukovic** [comment]
@ritiek 

You have banned add-ons/repositories installed. Please remove them and provide a new log.

Thanks in advance.

**Comment by ritiek** [comment]
@DaVukovic Sorry about that, I've updated my previous post with new logs.

**Comment by DaVukovic** [comment]
@ritiek sorry for the delay. 

I labeled this issue now and asked a team member. Generally I don't see a reason to start the webserver if no network connection can be established. 

I don't know enough about Android network management and if there's a loopback adress or not. Maybe @peak3d is able to answer that.

**Comment by ritiek** [comment]
No problem! Let me know if you need any more information.

**Comment by peak3d** [comment]
@ritiek it makes not much sense to fallback to localhost / 127.0.0.1, because kodi will not be reachable from outside (and the web server should be reachble, right?).
Either way there must be a proper implementaion which restarts all TCP server if a network change occurs. Not sure if / how this is implemented currently.

What happens, if you plugin / enable network after a failed start?

**Comment by ritiek** [comment]
> it makes not much sense to fallback to localhost / 127.0.0.1, because kodi will not be reachable from outside (and the web server should be reachble, right?).

@peak3d Yup, Kodi will indeed not be reachable from outside in case it listens on 127.0.0.1 (localhost).

But also as @Jack-Rogers mentioned in the original issue:

> The WebServer should be allowed to start on devices without an internet connection to allow for other local services & plugins to access Kodi's JSON-RPC via localhost

And I think instead of 127.0.0.1, we could also fallback to 0.0.0.0 (listen to all interfaces). That way Kodi will also be able to communicate atleast with other local devices connected to the Android device's hotspot (without mobile data turned on).

> Either way there must be a proper implementaion which restarts all TCP server if a network change occurs. Not sure if / how this is implemented currently.

Yup, that would be nice.

> What happens, if you plugin / enable network after a failed start?

I'll check it and report back soon.

**Comment by teamonce** [comment]
Any news? that bugs still continues :S

**Comment by lacek** [comment]
Having the same issue. I use [Launch on Boot](https://play.google.com/store/apps/details?id=news.androidtv.launchonboot) to start Kodi when the Android TV boots. When configured to use cable network, the error seldom occurs. When configured to use WiFi instead, the error occurs almost every boot.

Two of workarounds I could think of are:

1. Listen for network state change and start the serve only when network is available.
2. Retry web server start up with some reasonable interval for a few times before announcing failure.

**Comment by SamJongenelen** [comment]
I also use launch on boot on android tv.

A third workaround for me would be to optionally delay start the webserver by n seconds.

**Comment by pgcd** [comment]
I have a different use case: I use my phone to connect to my a tablet's hotspot while driving, so my children can watch shows on Kodi; since I store the videos on the tablet itself, I don't need any external connection - and Kodi should be able to start the webserver regardless of Internet connection.
As it is, it seems that I can start the server while connected to Wifi and then turn the hotspot on, but it's a bit cumbersome.

**Comment by diogosena** [comment]
This still hapenning consistently, kodi should be able to detect network changes and try to start webserver.

**Comment by thexai** [comment]
> 1. Obtain an Android Device
> 2. Disable Data & WiFi
> 3. Open Kodi
> 4. Attempt to start the WebServer (Settings -> Services -> Control -> Allow remote control via HTTP)

This is inherent to how TCP/IP works: to start a web server it is necessary to have a valid IP address assigned (no Internet connection is necessary).

If data and WiFi are disabled on a mobile (there is no Internet or local network) there is no IP to start any server.

This by itself is not a bug...

It can be implemented "listen network change events" and re-start services if is detected a change from not valid IP to valid IP... but this is a feature/improvement.

**Comment by pgcd** [comment]
> This is inherent to how TCP/IP works: to start a web server it is necessary to have a valid IP address assigned (no Internet connection is necessary).

You can start a web server on 0.0.0.0, though. I do it daily in my dev VMs.

**Comment by D3VL-Jack** [comment]
Closing this feels counter intuitive.
It's a valid issue on android, a behaviour that (as far as I know) is handled properly on other platforms.

**Comment by thexai** [comment]
"WebServer fails to start on Android with no Internet connection" is bad formulated as OP says "WebServer fails to start on Android with no valid IP address" and this is no a bug.

Is not possible bind a TCP server without valid/reachable IP. If device not has connectivity (Disable Data & WiFi) 
What's the point of having a server?

**Comment by D3VL-Jack** [comment]
> "If device not has connectivity (Disable Data & WiFi) What's the point of having a server?"
Other local applications that may want to control, or (if memory serves) our original case for making this issue, a python plugin within kodi using the RPC api.

**Comment by pgcd** [comment]
> Is not possible bind a TCP server without valid/reachable IP. If device not has connectivity (Disable Data & WiFi)
What's the point of having a server?

In my case I *did* have local connectivity and an IP address - just no *Internet* connectivity. And the point is, as mentioned, to be able to control it from another device on the same local network.

**Comment by thexai** [comment]
> In my case I did have local connectivity and an IP address - just no Internet connectivity. And the point is, as mentioned, to be able to control it from another device on the same local network.

Then provide debug log demonstrating that Kodi on device with valid local IP address (e.g.: 192.168.1.x) with connectivity on local network can not start a web server.

**Comment by pgcd** [comment]
> > In my case I did have local connectivity and an IP address - just no Internet connectivity. And the point is, as mentioned, to be able to control it from another device on the same local network.
> 
> Then provide debug log demonstrating that Kodi on device with valid local IP address (e.g.: 192.168.1.x) with connectivity on local network can not start a web server.

I'd be happy to, although it would've been much easier **three years ago** when I had the actual setup I was talking about.
But it's outside the scope of the issue (which mentions no connectivity at all) and, frankly, I don't feel the need to score points with you, especially not after you've been moving targets to justify closing a 5yrs old issue ("it's TCP/IP" -> "well it's useless anyway" -> "oh then provide debug logs").

Do whatever you want, I'm no longer affected by the specific problem and rude open source maintainers contributors don't put any bread on my table. =)
