### ISSUE TITLE
OpenConnection - could not opening a connection to the CEC adapter

### ISSUE THREAD

**Issue by adrian-maurin** [xbmc/xbmc#16053]
### Describe the bug
After upgrading to 18.2 CEC stopped working
I use Pulse-Eight USB - CEC Adapter w/ libcec 4.0.3

## Expected Behavior
CEC should work as usual :D

## Actual Behavior
On kodi startup I get a notification telling that the adapter as been found then an other notification tells me that it could not connect to it.
In the log I have the following line : 
`ERROR: OpenConnection - could not opening a connection to the CEC adapter`

In setting/input the adapter appears, settings can be changed but nothing works.

### To Reproduce
1. Start Kodi
2. Do not enjoy CEC capabilities :D

### Debuglog
https://pastebin.com/euwevT5Y

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux 5.0.9-arch1-1-ARCH
 - Kodi version: 18.2
 - libcec version: 4.0.3

**Comment by DaVukovic** [comment]
could you please show me: `ls -al /dev/ttyACM*` in a paste

Could it be possible you aren´t part of the specific group? Because it seems to be a permission problem

**Comment by adrian-maurin** [comment]
```
# ls -al /dev/ttyACM*
crw-rw---- 1 root uucp 166, 0 May  3 14:44 /dev/ttyACM0
```
My user was not in `uucp` group, adding him to it make the error go away.
My guess is that `/dev/ttyACM0` group/rights changed for whatever reason (kernel update or whatnot)

**Comment by DaVukovic** [comment]
cool. Issue can be closed then. 

Use the forums next time please ;)
