### ISSUE TITLE
iOS 12 install not working

### ISSUE THREAD

**Issue by xXBannedXx** [xbmc/xbmc#16064]
### Describe the bug
Here is a clear and concise description of what the problem is:

On both iOS 11 and 12 kodi arm64 will not open.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After I install the kodi 64 bit from the arm64 repo. I should be able to run the .deb file and install kodi then run it from the home screen.

## Actual Behavior

When I try to open the app, I receive the error that the developers need to update the app to be compatible with iOS 11 and 12.

### To Reproduce

The debuglog can be found here:

I don’t have any logs.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:iOS 12

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by xXBannedXx** [comment]
Sorry my steps to reproduce didn’t post

1.jailbreak an iOS 12 device using chimera jailbreak
2. Download and install filza
3. Open safari and go to the kodi mirror page and go to iOS arm64
4. Download any version in safari(wait for blue bar at top) then select more, and select open in filza
5.In filza open the file and hit install
6. After installation go to the homescreen and try to open kodi

**Comment by xXBannedXx** [comment]
Screenshot link
https://drive.google.com/file/d/1QkETBgUK8wrQl1ScqUKjjd-ZaifqdQzT/view?usp=drivesdk

**Comment by xXBannedXx** [comment]
Kodi version 18.2

**Comment by xXBannedXx** [comment]
This work as debug?

bash-4.4$ cd "/Applications/Kodi.app";./Kodi
2019-05-04 18:20:22.901 Kodi[2090:107197] [DEBUG] Detected 64bit system!!!
objc[2090]: Class XBMCApplicationDelegate is implemented in both /Applications/Kodi.app/./Kodi (0x102e59318) and /Applications/Kodi.app/Kodi (0x3827dd318). One of the two will be used. Which one is undefined.
objc[2090]: Class IOSDisplayLinkCallback is implemented in both /Applications/Kodi.app/./Kodi (0x102e59368) and /Applications/Kodi.app/Kodi (0x3827dd368). One of the two will be used. Which one is undefined.
objc[2090]: Class IOSEAGLView is implemented in both /Applications/Kodi.app/./Kodi (0x102e593b8) and /Applications/Kodi.app/Kodi (0x3827dd3b8). One of the two will be used. Which one is undefined.
objc[2090]: Class IOSExternalTouchController is implemented in both /Applications/Kodi.app/./Kodi (0x102e59408) and /Applications/Kodi.app/Kodi (0x3827dd408). One of the two will be used. Which one is undefined.
objc[2090]: Class KeyboardView is implemented in both /Applications/Kodi.app/./Kodi (0x102e59458) and /Applications/Kodi.app/Kodi (0x3827dd458). One of the two will be used. Which one is undefined.
objc[2090]: Class IOSScreenManager is implemented in both /Applications/Kodi.app/./Kodi (0x102e594a8) and /Applications/Kodi.app/Kodi (0x3827dd4a8). One of the two will be used. Which one is undefined.
objc[2090]: Class XBMCController is implemented in both /Applications/Kodi.app/./Kodi (0x102e594f8) and /Applications/Kodi.app/Kodi (0x3827dd4f8). One of the two will be used. Which one is undefined.
2019-05-04 18:20:22.948 Kodi[2090:107197] [DEBUG] Detected 64bit system!!!

**Comment by DaVukovic** [comment]
@Memphiz could you take a look please

**Comment by Memphiz** [comment]
all my devices have a to new iOS version to be jailbroken. Can‘t look into it.

**Comment by SylvainCecchetto** [comment]
Hi, I have a jailbroken iPhone 7 (12.1.1) with unc0ver.
Kodi 18.2.0 (http://mirrors.kodi.tv/releases/darwin/ios-arm64/org.xbmc.kodi-ios_18.2-0_iphoneos-arm64.deb) works well on my device (installed with Filza).
