### ISSUE TITLE
Kodi 18.2 crashes when creating new group in PVR iptv simple client

### ISSUE THREAD

**Issue by Dumua1312** [xbmc/xbmc#16079]
### Describe the bug
Here is a clear and concise description of what the problem is:

 In PVR iptv simple client after the update to Kodi 18.2 in xbox one, android and windows 10 after creating a new group in Group Manager, and adding the first channel Kodi crashes

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After creating the new group before the Kodi 18.2 update i could add as many channels as i needed in pvr simple client.

## Actual Behavior

Now in KOdi 18.2 in android, xbox one and windows 10 as soon as i cick to a channel to be added in a group in pvr simple client Kodi crashes.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
android log : https://pastebin.com/00Vz5Cgh
Windows 10 log: https://pastebin.com/QF2vqnAb

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Not specific for pvr.iptvsimple. Crashes for all addons. Kodi PVR core issue.

**Comment by Dumua1312** [comment]
> Not specific for pvr.iptvsimple. Crashes for all addons. Kodi PVR core issue.

I reported this problem for iptv simple because is the main addon i use and i don't know about problems in others. Thank you.

**Comment by Sopor** [comment]
I can't even find how to add a new group in the `Group manager`. Have you removed it?
