### ISSUE TITLE
Kodi in my philips TV (50puf6061/t3) is unworked , because the tv system will reset all data in /sdcard/Android/data ，kodi cannot save the settings!

### ISSUE THREAD

**Issue by RockSecLab** [xbmc/xbmc#16099]
### Describe the bug
Here is a clear and concise description of what the problem is:

My philips tv will clear /sdcard/Android/data when I reboot or poweroff(disconnect the power)
I want know can I move the settings and profiles in /data/data/org.xbmc.kodi , or can I rebuild some apk in my Android TV to solve this problem.
This problem also in some box as Xiaomi MIBox and some other tvbox , almost in china .
I hope I can get yours help ! 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix

move the profiles to /data/data/org.xbmc.kodi

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.2
18
16.4
16

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Could you please confirm that you exit Kodi before powering off the TV. Some settings are only safed when Kodi has been exited properly. 

And please provide a debug log as our template asks for that. 

Thanks in advance.

**Comment by RockSecLab** [comment]
yeah , I'm sure I exit kodi before power off tv . And if I start kodi without reboot TV ,it's worked very well!
The TV will clear all data in /sdcard when reboot , but not clear /data.The kodi profile files in /sdcard/Android/data/org.xbmc.kodi/files/.kodi, So it will lost in reboot . So  I hope the profile files move to /data/data/org.xbmc.kodi/files/.kodi , Can you help me? I cannot re-build it because I don't know about  Android develop . I can't provide the debug log because after I reboot ,it LOST ALSO! In the end ,whatever you can or can't help me , THANKS A LOT! Hope get your reply early!

**Comment by RockSecLab** [comment]
@peak3d Yeah ,I am sure . nothing about "Clean on Boot" in general setting , factory setting or another.
Also this TV is customs edition， whitout any setting like hotel mode . So I only have one way to solve this problem that change profile path QAQ ,Thanks very much!

**Comment by RockSecLab** [comment]
@peak3d Yeah , I am sure that my TV doesn't have any setting like  "Clean on Boot" .Also I search all possible  location in setting like factory setting.My TV is customs edtion, so it don't have some hotel mode and so on.So I think the only way that solve the problem is change the second profiles path to /data/data/org.xbmc.kodi/files/.kodi .I saw  the  official kodi wiki : https://kodi.wiki/view/Userdata . I hope find a funtion to change the second path ! Thanks Very much!

**Comment by M2k80** [comment]
i think there is something wrong with your tv and you should contact the manufactor.
if this is right what you say, all installed apps on your tv would lost their settings on reboot, because every app installs their settings in /sdcard/Android/

**Comment by mrmojo666** [comment]
on my philips android tv , seems that the kodi config files are read only
