### ISSUE TITLE
Sign on folder name

### ISSUE THREAD

**Issue by valoulou** [xbmc/xbmc#16090]
---
name: Problem report
about: Create an extensive report to help us document a problem

---

### Describe the bug
Here is a clear and concise description of what the problem is:
On Kodi, when there is a folder with a + sign in it, it is not possible to see it in the folder manager (for https directory). For example :

"A Great Movie + A Second Great Movie"

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1.  Create a folder with a + sign in it on a https server
2. Go into the folder manager and try to see it 

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - Raspberry-Pi
 - Windows

 - Operating system version/name: OSMC 2019 04 20
 - Kodi version: Kodi 18.2-RC1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Sounds kind of related to #16032 
at least Kodi seems to behave similar.

@valoulou we need for sure a debuglog. Without that we can't do anything

**Comment by valoulou** [comment]
Thanks for the reply.

Are you talking about '/home/osmc/.kodi/temp/kodi.log' ?

Thanks

**Comment by valoulou** [comment]
I have a little update :

If you put a folder like "bob + Ross" on an usb drive, the folder is visible.

Is it possible that XBMC has difficulty with some symbols encoded in URL? (with the example : bob%20%2B%20Ross)

Thanks

**Comment by DaVukovic** [comment]
> '/home/osmc/.kodi/temp/kodi.log

Yes that's what I'm talking about. As said, we can't do anything without that

**Comment by valoulou** [comment]
Here it is 

[kodilog.log](https://github.com/xbmc/xbmc/files/3198514/kodilog.log)

**Comment by DaVukovic** [comment]
2019-05-20 02:25:19.849 T:1915901488  NOTICE: Disabled debug logging due to GUI setting. Level 0.

You need to enable debug logging. Otherwise that log is useless. 

Thanks in advance

**Comment by valoulou** [comment]
Here it is 

[kodi.log](https://github.com/xbmc/xbmc/files/3198664/kodi.log)

**Comment by valoulou** [comment]
Hello,

I read the code today. And it looks like the line 658 of the URL.cpp file is a problem. Here are the changes to make the '+' sign in HTTP item no longer a problem:

From: 
```
if (kar == '+') strResult += ' ';
    else if (kar == '%')
```
To (remove the first condition):
```
if (kar == '%')
```

Does anyone know if this change can be a problem? I have not seen one so far.

Thanks!

**Comment by valoulou** [comment]
We made a correction for this problem: https://github.com/xbmc/xbmc/pull/16402

Thanks
