### ISSUE TITLE
Youtube playlist - titles and thumbnails missing

### ISSUE THREAD

**Issue by recod4** [xbmc/xbmc#16118]
### Describe the bug

When I've added a couple of youtube tracks to video playlist, both titles and thumbnails are missing (apart from the first one that's currently playing). I don't see them neither in Chorus interface nor Kore app, though it fills missing data of the currently playing track. 

## Expected Behavior

I think it should fetch the both title and thumbnail on every track on playlist when added, not after it's played.

### To Reproduce

1. Queue some youtube videos
2. Check playlist tab

### Screenshots 

https://images2.imgbox.com/08/1d/M5jvbS4L_o.png

### Your Environment
Used Operating system: 

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspbian 9
 - Kodi version: 18.2

**Comment by KarellenX** [comment]
@recod4 

Unfortunately this is the wrong location to post. This Issues section is for the core component of Kodi, not for add-ons.

I suggest you post here for an initial response...
https://forum.kodi.tv/showthread.php?tid=325740

I will close this Issue as it is not applicable.
