### ISSUE TITLE
Video freezes after a number of minutes

### ISSUE THREAD

**Issue by okrikos** [xbmc/xbmc#16124]
### Describe the bug
Here is a clear and concise description of what the problem is:
Simply watching YouTube with John Oliver. Every time it gets close to the end of the clip, the video freezes. No access via ssh or vnc either, but ping is OK.  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
http://www.tyoma.com/real/kodi.old.log.gz

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC (official): 8.2.5 (RPi2.arm)
 - Kodi version: 17.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by okrikos** [comment]
Crash file http://www.tyoma.com/real/kodi_crash.log

**Comment by KarellenX** [comment]
@okrikos 

Unfortunately this is the wrong location to post. This Issues section is for the core component of Kodi, not for add-ons.

I suggest you post here for an initial response...
https://forum.kodi.tv/showthread.php?tid=325740

I will close this Issue as it is not applicable.
