### ISSUE TITLE
Feature Request: Ability to Mute Center Channel

### ISSUE THREAD

**Issue by jkms** [xbmc/xbmc#16125]
### Describe the bug
Here is a clear and concise description of what the problem is:

I would like the ability to Mute the center channel.  The rationale for this is to be able to disable the audio commentary on sports broadcasts.  I'm almost able to achieve this with the **Downmix: Center Mix Level** option, but there are two problems with this:
1. The audio slider only goes to -9db, which isn't enough to effectively mute the commentary ![image](https://user-images.githubusercontent.com/660916/57671649-80b91400-75c9-11e9-87a6-3c7d73115be2.png)
2. Although it doesn't affect me and my Stereo Sound Impoverishment, a user that actually did have surround sound wouldn't be able to use this option (their AVR may be able to do it, but obviously they wouldn't be downmixing in Kodi).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Navigate to the OSD audio settings, and find an option like **Mute Center Channel**

## Actual Behavior

As above in the screenshot. Setting doesn't exist

### To Reproduce

1. Play a 5.1 Channel Video/Stream
2. Navigate to the Video OSD Audio Settings
3. Behold the inability to mute the center channel

### Debuglog

The debuglog can be found here:
http://sorry.i/dont/have/a/debug/log/obviously

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

If you're a sports fan, and you've never watched a game without the audio commentary, you're really missing out.  It's like being at the stadium/arena.  It's really, really nice to have on in the background.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora KDE 30 / Android / LibreELEC
 - Kodi version: 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jkms** [comment]
> Thank you for using Kodi and our issue tracker. This is your friendly Kodi GitHub bot wink
> 
> It seems that you have not followed the template we provide and require for all bug reports (or have opened a roadmap item by accident). Please understand that following the template is _mandatory_ and required for the team to be able handle the volume of open issues efficiently.
> 
> Please edit your issue message to follow our [template](https://github.com/xbmc/xbmc/blob/master/.github/ISSUE_TEMPLATE.md) and make sure to fill in all fields appropriately. The issue will be closed after one week has passed without satisfactory follow-up from your side.
> 
> This is an automatically generated message. If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.

Ouch

**Comment by DaVukovic** [comment]
Thanks for your suggestion. We appreciate the effort. But unfortunately this section is only for bug reports and not for feature requests. Sometimes a missing feature could be considered as a bug as well, but feature requests have to be submitted to our forums at this section: 

https://forum.kodi.tv/forumdisplay.php?fid=9

Please open a thread at this subforum

Thanks in advance.

**Comment by jkms** [comment]
> > Thank you for using Kodi and our issue tracker. This is your friendly Kodi GitHub bot wink
> > It seems that you have not followed the template we provide and require for all bug reports (or have opened a roadmap item by accident). Please understand that following the template is _mandatory_ and required for the team to be able handle the volume of open issues efficiently.
> > Please edit your issue message to follow our [template](https://github.com/xbmc/xbmc/blob/master/.github/ISSUE_TEMPLATE.md) and make sure to fill in all fields appropriately. The issue will be closed after one week has passed without satisfactory follow-up from your side.
> > This is an automatically generated message. If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.
> 
> Ouch

Okay.  I think I'm using the template exactly now.

**Comment by jkms** [comment]
> Thanks for your suggestion. We appreciate the effort. But unfortunately this section is only for bug reports and not for feature requests. Sometimes a missing feature could be considered as a bug as well, but feature requests have to be submitted to our forums at this section:
> 
> https://forum.kodi.tv/forumdisplay.php?fid=9
> 
> Please open a thread at this subforum
> 
> Thanks in advance.

D'oh!!

Thanks :)
