### ISSUE TITLE
Microsoft Connect Test failed

### ISSUE THREAD

**Issue by HeresJonny** [xbmc/xbmc#16129]
### Describe the bug
Into the Kodi windows .exe for some reason there is a Microsoft connect test incorporated which tries to connect to http://www.msftncsi.com/ncsi.txt
This address is obsolete and can never be reached, leading to Kodi becoming unresponsive for short periods of time. If this really is needed, the correct updated connect test uses www.msftconnecttest.com/connecttest.txt 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

2019-05-14 22:35:04.932 T:8104   ERROR: CCurlFile::Exists - Failed: Couldn't resolve host name(6) for http://www.msftncsi.com/ncsi.txt

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Matrix 2019-05-12

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Rechi** [comment]
Where did you get the info that http://www.msftncsi.com/ncsi.txt is obsolete? It works fine here.

**Comment by HeresJonny** [comment]
https://campus.barracuda.com/product/websecuritygateway/knowledgebase/50160000000auwRAAQ/should-i-block-http-www-msftncsi-com-ncsi-txt-on-my-barracuda-product/

**Comment by HeresJonny** [comment]
Also, have a look at this registry key and values to see the adresses used: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet

**Comment by kib** [comment]
Whether it is true that Microsoft switched to a more complex scheme to check for internet connection with Windows 10 (first checking a dns request against dns.msftncsi.com and thén moving on to check a simple http get against the new address http://www.msftconnecttest.com/connecttest.txt) , that does not mean that they **deprecated** the domain or usage of http://www.msftncsi.com/ncsi.txt which was hardcoded into Windows releases until Windows 8.1.

Extended support for Windows 8.1 is until January 10, 2023 so we have at least 3,5 more years to change the URL.

**Comment by GiannisProkopiou** [comment]
Greetings,i would like to know if this is still open.I see @gusandrianos saying that his PR does it.
If it is open let me know if there is anything other that what i see that i need to know!
Thanks in advance!

**Comment by gusandrianos** [comment]
I don't think I ever opened a PR for this issue 🤔

**Comment by GiannisProkopiou** [comment]
I am sorry,it was a mistake.I edited it :/

**Comment by ritik-chauhan** [comment]
hello,
So we only have to change the URL in the responsible file. right?

**Comment by guneshmunjal** [comment]
hi 
is this issue still open??

**Comment by AbdelrhmanHan** [comment]
How are you?
What do you want?
I don't understand what this about?
