### ISSUE TITLE
Ipad Pro 12.9 3rd Generation Black bars top and bottom

### ISSUE THREAD

**Issue by Lukrativehd** [xbmc/xbmc#16128]
### Describe the bug
Here is a clear and concise description of what the problem is: There is black bars top and bottom on my iPad Pro 12.9 3rd Gen, I think i remember seeing something about the fact that it was updated for all iPads but im not sure what that was in relation to whether it was just support for the app for those devices or not, if this is already something that has been fixed and something I'm failing to notice then I apologise. it just doesn't quite seem like the resolution is adjusted properly for this device 

This issue is in both the menus and when watching a movie

Yes this issue carries across both, when watching a movie at 16:9 aspect ratio and during the menus

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I'd have expected it to run at full resolution

## Actual Behavior

There's black bars top and bottom, instead of fitting the screen  

## Possible Fix

Adjusting the resolution to support 2388 x 1668 I would presume, how you'd go about doing that I don't know

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

I'm not on a rooted device so I dont know how to get a debug log ? 

### Screenshots 
Here are some links or screenshots to help explain the problem:

http://prntscr.com/noj2n8
http://prntscr.com/noj31w

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [X] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.0 ALPHA Nightly build

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by keithah** [comment]
install the Kodi log uploader, and it will give you a url for a log you can put in the issue.

**Comment by fuzzard** [comment]
@Lukrativehd is there any chance you can test a master nightly on the ipad Pro to see if this is resolved?
None of our team members have one to test on unfortunately.

**Comment by fuzzard** [comment]
We believe this is fixed with the migration to storyboard use. As no one on the team has an iPad pro to test with, and the user has been unresponsive, will close. 
If anyone has an issue, feel free to open another issue up.
