### ISSUE TITLE
PVR: Instand Recording doesnt work right from The OSD

### ISSUE THREAD

**Issue by boogaloo7** [xbmc/xbmc#16135]
### Describe the bug
Here is a clear and concise description of what the problem is:

If i hit the Recording Button within the VideoOSD, i get a message "recording planned" instead of Instand recording. It doesnt matther if i set Instand recording to "record 60 Min" or "record ongoing show"
I have to press the recording Button twice to start a recording.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Instand recording by clicking on the recording Button within the Video OSD. (+ Button shuld go in the "red" recording state.

## Actual Behavior

thers just a message about a pllaned recording, button stays white.  I have to cklick twice to start the recording. (which give me than two recordings)

### To Reproduce

1.  Start a TV Channel
2.  Go to Fullscreen
3. hit "Enter" to bring up the "OSD"
4. And click on the "record" icon.

### Debuglog

The debuglog can be found here:
Link: https://pastebin.com/s9ztw0dM

**NEW** Debug Log (PVR debugging enabled): https://paste.ubuntu.com/p/6cz5d4q3YM/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Please enable debug logging and pvr component logging in Kodi settings and resubbmit a debug log.

**Comment by ksooo** [comment]
@rbuehlma Can you reproduce this issue? Could this be an addon problem?

**Comment by ksooo** [comment]
@margro I've just seen in the logs that user used pvr.mediaportal-tvserver, not pvr.zattoo. So, Could this be an addon problem? Instant recording needs special treatment in the addon.

**Comment by rbuehlma** [comment]
In pvr.zattoo, the recordings seem to work using the OSD on the current stream. Just the recording and the notification is only showing up as soon as the recording list is update. But this is an issue of pvr.zattoo and not Kodi.

**Comment by boogaloo7** [comment]
Did disable the Zatto PVR Addon, and have still the same Issue.

heres a new debug Log (PVR debugging enabled): https://paste.ubuntu.com/p/6cz5d4q3YM/

**Comment by ksooo** [comment]
I suspect this could be a problem with the mediaportal addon @margro
