### ISSUE TITLE
PVR: Switching to a certain Channel brings up wrong (play recording) Window.

### ISSUE THREAD

**Issue by boogaloo7** [xbmc/xbmc#16134]
### Describe the bug
Here is a clear and concise description of what the problem is:

if i switch to a certain Channel, in my case its "Disney Channel" i get the "play Recording" Window where i can choose to watch "the" Recording (Button: play recording) or switch to the Channel (Button: switch to channel).
The "Funny part" is, that there is no ongoing recording at this Channel!

I once had a series recording timer active on this specivic channel but deleted the specivic Timer, at least thats the only difference i can see to other channels where this window doesnt appear.

if i choose "watch recording" then it shows me also the show/episode i once recorded via recording Timer.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Dont show the Window to choose to watch a recording if there is no ongoing recording for this channel. (I just want to switch to this Channel.)

## Actual Behavior

i always get this "play recording" Dialog if i switch to this certain Channel. (Disney channel)

## Possible Fix

?

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
Link: https://pastebin.com/p3DjAPd9

NEW (pvr debbuging enabled): https://paste.ubuntu.com/p/2JVmB55pRj/

### Screenshots 
Here are some links or screenshots to help explain the problem:

There is no ongoing timer and it looks like this:
[img]https://i.imgur.com/BCAehLw.jpg[/img]

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
@margro Can you reproduce this issue? I think, this could be an addon problem.

**Comment by boogaloo7** [comment]
i've updated the first Post with a new Debug-Log (pvr debugging enabled)

https://paste.ubuntu.com/p/2JVmB55pRj/
