### ISSUE TITLE
PVR: Wrong Teletext size on Clients

### ISSUE THREAD

**Issue by boogaloo7** [xbmc/xbmc#16136]
### Describe the bug
Here is a clear and concise description of what the problem is:

If i open the Teletext from an other client than the one the PVR server is installed, it shows up just 2/3 size

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Teletext shows up in the right size

## Actual Behavior

teletext sizes to 2/3 on my second client.

### To Reproduce

1. Start a PVR TV Channel on a different Client/PC than the one the TV server is installed
2. Got to Fullscreen
3. hit "Enter to bring up the OSD
4. Navigate to the teletext Icon within the OSD, click it
5. Teletext shows up 2/3 of the usual size.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://imgur.com/a/IRV6YF6

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows
 - Kodi version: 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
I doubt that this is caused by the fact that the PVR server is located on a different machine than Kodi+PVR-Client addon. It must be something with the configuration of the misbehaving client compared to the well-behaving client..

**Comment by ksooo** [comment]
Please proved debug logs for both the well-behaving client and the mis-behaving client.
