### ISSUE TITLE
Videos started using JSON API do not provide subtitle info on first playback

### ISSUE THREAD

**Issue by basrieter** [xbmc/xbmc#16151]
### Describe the bug
Here is a clear and concise description of what the problem is:

If a remote app (like Kore or Yatse) is used to start a video stream from a video add-on there is a problem with subtitles not being detected correctly on the first play. The remote app will not show available subtitles to select. If the same video is started again, the subtitles are show for selection in the app.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

- Browse a video add-on via Kore/Yatse (remote app)
- Start a video that contains subtitles from the add-on (subtitles may be set via the ListItem.setSubtitles() method)
- The video starts
- Within the remote app the available subtitles are shown and one can be selected
- Those subtitles are the same as one would see from Kodi itself

## Actual Behavior

- At the initial playback attempt, the video starts, however, within the remote app, there is no indicator or selector for subtitles: the app does not receive any subtitle info for the stream.
- If I start the same video again from the remote app, it will play again, but now it will show available subtitles and a user can select them
- Within Kodi itself the subs are listed and can be selected

## Possible Fix

Check the JSON data to see if it includes the correct subtitle information?

### To Reproduce

1. Browse a video add-on (such as Youtube) and select a video that has subtitles (you might need to configure the YT add-on to use us-en subs)
2. For the first start, no subs can be selected from the app
3. Within Kodi the subtitles can be selected from the normal GUI
4. Stop the video and start it again via the remote app
5. Now the subs do show in the remote app

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/tizinajive.kodi

The logfile shows playback of the same video from the Youtube add-on twice. Once without sub info send to the remote app. And the second run where the info is available.

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Screenshot_20190516-210006](https://user-images.githubusercontent.com/1310443/57880241-8fe4cf80-781e-11e9-9335-b9fc7a69f6d5.jpg)
Screenshot of Yatse after the first playback: so sub selection

![Screenshot_20190516-210021](https://user-images.githubusercontent.com/1310443/57880260-9a9f6480-781e-11e9-8b6e-453d6f11e3c6.jpg)
Screenshot of Yatse after the second playback: there is a subtitle selection option

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I tested this with Kore and Yatse on my Windows Kodi Leia install. However, I have user reports for Retrospect from users with LibreElec and Kodi on Android. So this seems to be a platform independent issue.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64
 - Kodi version: Kodi Leia 18.2 (normal installer version)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@basrieter please test the above PR to check if the issue persists

**Comment by basrieter** [comment]
So I did test this and it fixed the issue.
