### ISSUE TITLE
DSD in Wavpack cannot be played

### ISSUE THREAD

**Issue by HeresJonny** [xbmc/xbmc#16156]
### Describe the bug
Here is a clear and concise description of what the problem is:

When trying to play a music file which is DSD packed losslessly with WAVPACK, Kodi will neither play the file nor report its length correctly.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
After issue https://github.com/xbmc/xbmc/issues/14771 was fixed by https://github.com/xbmc/xbmc/pull/15234 I was under the impression that playback of these kinds of files was already possible. However, I may be mistaken and only the crash might have been fixed to pave the way for future inclusion of this format.

### To Reproduce

1. I've uploaded a 6 sec file to test playback https://www.dropbox.com/s/1je8wxyotz0lmz9/11%20-%20Bright%20Noise%20%285.1%20mix%29.DSD-24bit.wv?dl=0
2. Kodi will skip over this file
3. Length will be reported as 4 times the correct value
4. The file is multichannel, but stereo DSD will show the same problems.

### Debuglog

The debuglog can be found here:
2019-05-17 10:07:24.076 T:7508   DEBUG: CDVDDemuxFFmpeg::Open - probing detected format [wv]
2019-05-17 10:07:24.076 T:7508   DEBUG: ffmpeg[1D54]: [wv] WV DSD is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Matrix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Could we please see the full debug log at paste.kodi.tv as requested at the issue template. That snippet might be useless. 

Thanks in advance

**Comment by pkerling** [comment]
> However, I may be mistaken and only the crash might have been fixed to pave the way for future inclusion of this format.

Yes, I'm afraid this is exactly what happened. The patch only fixes the crash. Please direct this feature request to ffmpeg.
