### ISSUE TITLE
Crash Kodi 18.2 when loading PVR 

### ISSUE THREAD

**Issue by betmensk** [xbmc/xbmc#16154]
## Bug report

### Describe the bug
Here is a clear and concise description of what the problem is:
the system crashes after updating Kodi to ver 18.2 and Yatse 9.1.5 when loading PVR.  when using the Kore app or web interface, the desired TV channel will start.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

properly loading PVR and then launching the desired TV channel without crashing the system.

## Actual Behavior
after running the Yatse app and opening the PVR item, endless synchronization with Kodi remains, and after a while, the system where Kodi is running crashes.  hardreset is required to restore functionality.

## Possible Fix
repair PVR API control

### To Reproduce

1. open Yatse
2. click to PVR

### Debuglog

The debuglog can be found here:
[debug-20190514_184237.zip](https://github.com/xbmc/xbmc/files/3188897/debug-20190514_184237.zip)

[kodi_1.log](https://github.com/xbmc/xbmc/files/3193736/kodi_1.log)
[kodi_2.log](https://github.com/xbmc/xbmc/files/3193737/kodi_2.log)
[kodi_full_1.log](https://github.com/xbmc/xbmc/files/3193738/kodi_full_1.log)
[kodi_full_2.log](https://github.com/xbmc/xbmc/files/3193739/kodi_full_2.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 
Ubuntu desktop 16.04 64bit
 - Kodi version: 18.2

- satelite PCIe card TBS (tbs open drivers), Argolis card reader ver2
- OSCam: 1.20-unstable_svn Build: r11410 Compiler: x86_64-linux-gnu
- Tvheadend Build: 4.2.8-21~g0c36205f7~xenial 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
If it requires Yatse to make Kodi crash and if it works via other apps using generally the same way to connect to Kodi, then I would blame Yatse. 

As Yatse is its own closed source thing there's not much we can do and you are reporting this issue at the wrong team unfortunately ;). I would suggest to create an issue against Yatse using their own forums: https://community.yatse.tv/

**Comment by DaveTBlake** [comment]
The only interaction that Yatse can have with Kodi is vai the JSON API. It is Kodi that crashes, not Yatse, therefore this means that there is an issue with the processing triggered by the JSON API.

As devs we prefer issues we can reproduce without needing other software - neither remote app nor TV addon - in this case we may need both. But that does not mean Kodi crashing is not worthy of proper investigation. Hence reopening.

@betmensk to investigate this issue we need a crash log please provide soonest or this issue will be closed.

**Comment by betmensk** [comment]
please agree who the app is causing the crash.  one side says Kodi and the other side say it's Yatse... https://community.yatse.tv/t/crash-kodi-18-2-when-loading-pvr/1776

@DaveTBlake thanks...

**Comment by DaveTBlake** [comment]
@betmensk no one here is going to look at a Yatse debug log.  The more you mention Yatse the less likely that anyone from the team will look into your issue. There is longstanding hatred between many Kodi team members and the author of Yatse, it is childish but a fact of life. 

I think you have a Kodi issue with the API call causing a crash, but it could easily be in the addon you use to provide TV. You need to provide more evidence or nothing can be done.

The last Kodi debug log entry shows a JSON API call to the PVR, 
```
DEBUG: JSONRPC: Incoming request: {"id":796,"jsonrpc":"2.0","method":"PVR.GetChannelGroups","params":{"channeltype":"radio"}}
```
so that is a place for others to start, but there are no error shown.

You claim that Kodi crashes, so please provide the **Kodi cash dump files** from such a crash.

**Comment by betmensk** [comment]
debug file never continues because always crashes and file fails to write :( try to let me write what debug files to ...

**Comment by ksooo** [comment]
Im not childish, thus I even looked at the yatse debug log. All calls to  PVR.GetChannelGroups are returning with okay, so Kodi did not crash during this calls.

Attach gdb to the running Kodi process and once it crashed, dump the stack trace for all threads to a file and post it here. Once I have this information I can start investigation. No chance for a fix without the stack traces, sorry.

**Comment by DaveTBlake** [comment]
>Im not childish, thus I even looked at the yatse debug log.
Good for you @ksooo :)
Thanks for looking into this. If I can help with any API aspects then ping me.

@betmensk do provide the information needed, the PVR expert is giving you his attention

**Comment by michaelarnauts** [comment]
I can confirm this issue. I will try to see if I can come up with a crash dump or more logs.

It doesn't happen every time I open the PVR view though.

**Comment by michaelarnauts** [comment]
I saw my kodi crash with this message in syslog. My kodi wasn't in debugging logging, and the logfile didn't contain any new message. I will try to enable debug mode and make it crash again.

```
May 18 06:55:18 osmc mediacenter[750]: kodi.bin: pthread_mutex_lock.c:349: __pthread_mutex_lock_full: Assertion `INTERNAL_SYSCALL_ERRNO (e, __err) != EDEADLK || (kind != PTHREAD_MUTEX_ERRORCHECK_NP && kind != PTHREAD_MUTEX_RECURSIVE_NP)' failed.
```

**Comment by michaelarnauts** [comment]
Just made it crash by using the webapp (Chrous), but haven't found a way to make kodi actually write crash dumps.

May 18 07:18:48 osmc mediacenter[750]: *** Error in `/usr/lib/kodi/kodi.bin': double free or corruption (fasttop): 0xaec1be10 ***

@betmensk what is your PVR backend? I'm using tvheadend, might be related?

**Comment by ksooo** [comment]
Again, I need full stacktraces to debug this. Everything else (like 200 more comments here) wont help.

**Comment by ksooo** [comment]
Use gdb to create the stack traces.

**Comment by ksooo** [comment]
start gdb, attach it to kodi. Produce the crash, from inside kodi create the stack trace, dump them to a file. google for the exact details how to do this.

**Comment by ksooo** [comment]
> Just made it crash by using the webapp (Chrous), but haven't found a way to make kodi actually write crash dumps.

Do not spam this discussion with most probably unrelated issues, please. Open a separate issue.

**Comment by betmensk** [comment]
top I added 4 debug protocols I got this morning.  all unfortunately ending the same, Kodi was no longer able to write more data ...
`2019-05-18 08:16:59.564 T:139916881159936   DEBUG: JSONRPC: Incoming request: {"id":521,"jsonrpc":"2.0","method":"PVR.GetChannelGroups","params":{"channeltype":"tv"}}
 `

**Comment by ksooo** [comment]
I don't need debug logs!

**Comment by betmensk** [comment]
under gdb mas mean this?
 http://www.gdbtutorial.com/

**Comment by DaVukovic** [comment]
generally yes....

I guess what @ksooo wants to see is either the crashlog Kodi creates. That file should be located at your homefolder. But it would be somewhat useless if `gdb` is not installed. So please install `gdb` first: 

`sudo apt install gdb`

after that reproduce your crash and at least attach the crashlog Kodi created 

there are more debugging options with gdb. After you have `gdb` installed run it with:

`gdb /usr/lib/x86_64-linux-gnu/kodi/kodi-x11`

after that you will get a prompt that will look like: `(gdb) ` and a cursor next to it. Enter `run` on that. This will then start Kodi. Then reproduce your issue and after that issue has been reproduced you will get some error messages and you will get the prompt back `(gdb) ` 

at this prompt then enter `thread apply all bt full` and capture the output in a file and post that file in here. At least that's how I did it in the past

**Comment by betmensk** [comment]
I am adding a crashlog and hope this is what you wanted;)
[kodi_crashlog-20190518_093258.log](https://github.com/xbmc/xbmc/files/3193784/kodi_crashlog-20190518_093258.log)

**Comment by ksooo** [comment]
Yep, that's what I need. Thanks. No further input needed for now.

BTW: seems to be a deadlock, not actually a crash.

**Comment by arnova** [comment]
@ksooo : Looks like Yatse is sending a request twice in a row causing the issue (see thread 23 & 28). I recall we had similar issues with Yatse in the past causing crashes (non-PVR related back then).

**Comment by betmensk** [comment]
duplicate sending of requests can also be caused by me, because I had to click around in yatse on PVR to create a problem.

**Comment by DaveTBlake** [comment]
Well even if it is two JSON API requests in a row that triggers the issue, it is still a Kodi problem isn't it. Nothing to stop _any_ API consumer making muliple requests, Kodi should be able to handle it (if that is the issue).

**Comment by ksooo** [comment]
It is a Kodi problem and I know the root cause.

**Comment by ksooo** [comment]
Root cause it's not yatse sending two requests in a row. It's that  CFileItem must not be used in  PVR core. Unfortunately, this is done at several places. To fix all of this s**t is larger effort. I have a git branch open for this and work on it when I find the time.

I hope to come up with a point patch for the particular issue reported here.

**Comment by betmensk** [comment]
so it would be wonderful if you could solve this problem and issue a patch.

**Comment by ksooo** [comment]
sure sure

**Comment by michaelarnauts** [comment]
> > Just made it crash by using the webapp (Chrous), but haven't found a way to make kodi actually write crash dumps.
> 
> Do not spam this discussion with most probably unrelated issues, please. Open a separate issue.

Relax, I assume this was the same issue, since I've opened the PVR view in Chorus and I saw kodi restart.

This was just an attempt to bring in additional information and to give a clue to others on how to reproduce this better.
