### ISSUE TITLE
[LibCurl-Component Logging] Increase the string of the response if the server return 401

### ISSUE THREAD

**Issue by wwark** [xbmc/xbmc#16179]
### Describe the bug
Here is a clear and concise description of what the problem is:

During some work, to implement DRM for a french channel.
I got HTTP 401 and in the github of inputstream.adaptive they proposed to me to add logs debug for the libcurl.
It is working but the response is truncated. (ticket below)
https://github.com/peak3d/inputstream.adaptive/issues/264

In this code (https://github.com/xbmc/xbmc/blob/4e60402138c29d25a2737591602ae4c0208741e7/xbmc/filesystem/CurlFile.cpp) line 1009 the response is limited to 256 characters.

Do you think it is possible to increase this value to get more datas of this response ?
I don't know what is the correct number to increase it.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

To have the whole response of the server called by libCurl of Kodi 

## Actual Behavior

The response of server called by libCurl of Kodi is truncated if the size is more than 256 characters. 

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
2019-05-20 20:20:57.371 T:140294804715264   DEBUG: Curl::Debug - TEXT: Connection #0 to host secure-gen-hapi.canal-plus.com left intact
2019-05-20 20:20:57.371 T:140294804715264   ERROR: CCurlFile::Open failed with code 401 for http://secure-gen-hapi.canal-plus.com/conso/view/028fd970-7b2c-11e9-8b93-839d24259d89/licence:
                                            **{"status":401,"code":"AUTH-401-1","requestId":"secure-gen-hapi.canal-plus.com-15291-1558376457.384-10.205.22.102-676-cpfra-mycanal-pc","headers":{"XX-ECK":"cpfra-mycanal-pc","XX-DEVICE":"pc 9d6b98c4-433a-4150-9778-b668cc980109","XX-DOMAIN":"cpfra","XX-SER**
2019-05-20 20:20:57.372 T:140294804715264   ERROR: AddOnLog: InputStream Adaptive: License server returned failure
2019-05-20 20:20:57.372 T:140294804715264   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
2019-05-20 20:20:57.372 T:140294804715264   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment]
Any idea what the size is of the string returned for your case?

**Comment by wwark** [comment]
Hi @arnova,

I compiled Kodi and i replaced 256 by 2048 to get the whole response (but maybe we need less to get it)
I think also to add the parameter (below) in advancesettings.xml to be able the value of the size of the response we want and let 256 as default.
\<setting id="debug.setextraloglevel" ****size="2048"***>64\</setting>

Thanks

**Comment by arnova** [comment]
Fixed by #16179

**Comment by wwark** [comment]
Thank you !
