### ISSUE TITLE
All-season poster propagates to other shows

### ISSUE THREAD

**Issue by CosKen** [xbmc/xbmc#16188]
### Describe the bug
Here is a clear and concise description of what the problem is:

Setting any specific multi-season show’s “All season" poster will propagate that image to all multi-season shows’ “All season” poster.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

A specific show's All-season poster once set should not change unless another is specifically selected to change it.

## Actual Behavior

The last All-season poster image set in any multi-season show is seen in every multi-season show visited after selection.

### To Reproduce

1) In any show title with multiple seasons select a poster art file. (I do mine from a show’s smb attached NAS episode directory and the name "season-all-poster.jpg".)  Note the image after selection.
2) Exit the show and proceed to any other multiple season show.
3) Select and enter the show. Note the all-season poster is the same as the one selected in the previous show.
4) Change the all season poster in this show to “No Art”. Note the image after selection.
5) Exit the show and proceed to the show used in step 1.
6) Select and enter the show. Note the all-season poster previously selected has now been replaced by the “No Art” image.
7) This “No Art” image is the least offensive image that will now propagate throughout the database of multi-season shows.

## Debuglog

The debuglog can be found here:
## Screenshots

Here are some links or screenshots to help explain the problem:
## Additional context or screenshots (if appropriate)

Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

Kodi 18.2 Git: 20190422-f2643566d0
Shield Android TV Model P2897 Version 8.0.0 API Level 26
Kernal: Linux 4.9.109-tegra-g4ga2f58
Hardware: ARMv8 processor Rev 1 (v81)

Skins tested:
Estuary 2.0.22: View Type: Wall
Aeon Nox Silvo 7.0.1: View: Fullscreen Wall

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
I could not replicate this problem. The season-all-poster shows where expected, and nowhere else.

I followed your steps above and unable to replicate.

Using my own personal library for numerous years, I have never noticed this issue.

Unless you can provide further information the issue will be closed. Start off with a debuglog that captures a library update, and anything else you may think is relevant.

**Comment by KarellenX** [comment]
Request for further comment unanswered.

Issue not reproducible.

Issue closed.
