### ISSUE TITLE
DLNA  not working with rar archives

### ISSUE THREAD

**Issue by faltaren** [xbmc/xbmc#16182]
### Describe the bug
The dlna do not work with rar archives in kodi 18+. Worked fine in 17.6. The problem is that I can browse everything and it looks fine. But when I try to start it it never stops loading. Unpacked files are fine, they work. So only rar. I use vlc on my android 9 phone but I have tried on a macbook, hp laptop with win 10. Same problem. I use the rar addon. Cant use the archive one, then everything crasches. I have the latest version of win 10. desktop pc.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

That the vidoesfile plays in vlc. 

## Actual Behavior

Everything browses but never plays. Only loading.

## Possible Fix

Fix the rar support fully. 

### To Reproduce

1. Install kodi 18+ and activate the rar vfs addon
2. add a rar videofile 
3. start the dlna service and try to play

### Debuglog

The debuglog can be found here:
Cant provide that. Nothing happens so no log to read. 

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 10 pro x64
 - Kodi version: 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Please provide a full debug log.

**Comment by faltaren** [comment]
Here you go. Kodi crashed when I tried to close so added the crashlog to. 
[kodi.log](https://github.com/xbmc/xbmc/files/3200929/kodi.log)

**Comment by KarellenX** [comment]
Please read and provide a proper debug log... https://kodi.wiki/view/Log_file/Easy

**Comment by faltaren** [comment]
Im trying but when I replicate the issue and then try to close kodi. It crashes. Tried 4 times. Only happens after I try to play over dlna.

**Comment by DaVukovic** [comment]
Therefore we have the kodi.log and the kodi.old.log 

And you need to enable debug logging before you grab the log. In doubt which might be necessary/important, simply provide both logs

If Kodi crashes (in meaning it closes magically), then there should also be some crashlog located probably in `%appdata%\Kodi`. Not 100% sure about its location on Windows based systems

**Comment by faltaren** [comment]
Here we go. Crashed again when I closed it but the logs are there. Reinstalled kodi so now the loging works. 

[kodi.old.log](https://github.com/xbmc/xbmc/files/3201261/kodi.old.log)
[kodi.log](https://github.com/xbmc/xbmc/files/3201262/kodi.log)

**Comment by faltaren** [comment]
Anything?

**Comment by faltaren** [comment]
Noone is working on this?

**Comment by faltaren** [comment]
18.3 same problem. No fix? No one cares?

**Comment by Sopor** [comment]
@faltaren You are not reading the rules... You need to upload the debug logs to  http://paste.kodi.tv or https://paste.ubuntu.com and make a link to them here. So read the https://kodi.wiki/view/Log_file/Easy one more time and do as it says.

**Comment by DaveTBlake** [comment]
Fixed by  https://github.com/xbmc/xbmc/pull/16553
