### ISSUE TITLE
Kodi freezes when trying to pause or to advance to a certain position

### ISSUE THREAD

**Issue by mhaelsig** [xbmc/xbmc#16196]
### Describe the bug
I am playing the above file from a USB Stick or SMB mount. This runs fine.
When I try to pause or stop the playing, or to advance to another position, Kodi freezes. 
I have to reboot the system (Wetek Play 1 with LibreElec 19.02).

## Expected Behavior
Kodi should pause or stop the playing, or advance to another position. 

## Actual Behavior
Kodi freezes.

## Possible Fix
??

### To Reproduce
1. Start playing this mp4 file:
http://cdn-storage.br.de/b7/2019-05/24/f56d0f747e6911e9bca2984be109059a_C.mp4
e.g. from USB or SMB mount. 

2. During play, open navigation window, and try to stop or pause the playing.

### Debuglog
https://paste.ubuntu.com/p/4QYWMSHZRS/

### Screenshots 
-none-

## Additional context or screenshots (if appropriate)
Playing this mp4 with another player (VLC) on my PC works fine - I can pause, stop and advance to a certain position. 

### Your Environment
Can be found in Debug Log: Wetek Play with LibreElec 19.02
 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Leia 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Unfortunately that file is not available anymore

This seems to be a LibreELEC specific problem as a LibreELEC dev with the same hardware was able to reproduce. So I would suggest you open a bug report at the LibreELEC forums. 

I'm going to close that for now as the issue seems not to be present with Kodi on other OSs.
