### ISSUE TITLE
Kodi issue with importing strm movie files in library

### ISSUE THREAD

**Issue by eric859** [xbmc/xbmc#16193]
### Describe the bug
I am using the Library Integration Tool to create strm files in the kodi library from another addon.  What I'm seeing is that Kodi cannot import strm files that are larger than 4kb.  I edited one of the strm files and removed some actors from the metadata to get it under 4kb and it imported just fine.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Kodi should update it's library and add a movie entry for all strm files in the library folder

## Actual Behavior
Kodi is only importing strm files that are smaller in size than 4KB.  Strm files larger than 4KB are not imported

## Possible Fix
[kodi.log](https://github.com/xbmc/xbmc/files/3214411/kodi.log)
[kodi.log](https://github.com/xbmc/xbmc/files/3214418/kodi.log)

Don't know.

### To Reproduce

1. Add a folder with a strm file larger than 4KB and try to import it
2.
3.

### Debuglog

The debuglog is attached.  Start at line 864

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Could you please test with at least Kodi 18.2. 

Kodi 17.6 is outdated and there won't be a fix for that version anymore

**Comment by KarellenX** [comment]
Banned Add-ons are installed.

This issue section is for v18 onwards. No support for v17 here.

It sounds like you are having issues with an add-on, not Kodi core.

You also have a thread on the forum. I suggest you monitor that for now.

**Comment by eric859** [comment]
I have verified this issue on 18.2 first, then 17.6 to see if the problem was only with the new version.  It happens on both versions.  Here is a link to 2 strm files.  If you try to import both into Kodi, only 1 will work.  The only difference between the 2 files is the size.  https://gofile.io/?c=OsJziQ

**Comment by eric859** [comment]
Can you please re-open this issue?  I posted a reply I believe proves that the issue is in Kodi and not the addon.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
