### ISSUE TITLE
Folders are missing in WebDAV network locations

### ISSUE THREAD

**Issue by erpalma** [xbmc/xbmc#16194]
### Describe the bug
Here is a clear and concise description of what the problem is:

On Kodi 18.2 WebDAV network locations do not show subfolders. Just tested on a fresh install (18.04) and I can only see files but no subfolders. I guess this is a regression since 17.6 does not have this issue.

### To Reproduce

1. Add a new remote, eg. `davs://example.com/share` which contains `A.avi` and a subfolder `B` which contains `C.avi`;
2. Navigate to the new remote (just Files view);
3. Only `A.avi` is visible.

### Your Environment
Used Operating system:

 - Operating system version/name: Ubuntu 18.04
 - Kodi version: 18.2

**Comment by hnz101** [comment]
I can confirm and reproduce this issue under
    Operating system version/name: Fire OS 6.2.6.3
    Kodi version: 18.2 (32bit)

**Comment by arnova** [comment]
We don't need more people to confirm this, we need more people to provide the required information to fix this issue. So first of all: debug log with libcurl component logging enabled and information about the webdav-server used.

**Comment by hnz101** [comment]
Here is a log from my Android Smartphone which also shows this bug.
Operating system version/name: Android 9
Kodi version: 18.2 (64bit)
(IIRC the issue occurred first with 18.1 or 18.2)

WebDAV Server is an nginx Server with https and http basic auth enabled, but you will see all that in the log file. Creating the log I opened the dav share two times which listed none of the many subfolders and just the one file I put there for testing in the root directory. After that I played the test file successfully.

I hope I successfully redacted all privacy information in the log and that it will help you.
[kodi_censored.log](https://github.com/xbmc/xbmc/files/3219268/kodi_censored.log)

**Comment by arnova** [comment]
Strange. Could somebody please test in which version it stopped working? This would help a lot.

**Comment by hnz101** [comment]
I just downgraded to 18.1 and it works again like it should. (fresh install)

I created a test folder with some sub-folders and logged it again. Kodi listed the sub-folders and I could browse and play stuff from them.
[kodi18.1censored.log](https://github.com/xbmc/xbmc/files/3219479/kodi18.1censored.log)

**Comment by arnova** [comment]
Anyone that can test this with a non-Android client and/or non-nginx server? @erpalma : Are you also using an nginx server?

**Comment by erpalma** [comment]
Yes I do. I can do a test with WsgiDAV or Apache this evening.

**Comment by arnova** [comment]
Tested it here myself with a Linux Kodi client and a Debian 9 machine + nginx + mod-http-dav-ext  and I can't reproduce it. If it turns out to be a nginx problem, I need its config.

**Comment by erpalma** [comment]
This is the relevant section:
```
# TLS Stuff...

auth_basic "Restricted";
auth_basic_user_file /etc/nginx/htpasswd;

location /vids {
        alias      /volumes/vids/;
        client_body_temp_path /tmp;
        dav_ext_methods   PROPFIND OPTIONS;
        dav_access    user:r group:r all:r;
        fancyindex on;
        fancyindex_exact_size off;
    }
```

**Comment by wsnipex** [comment]
can you try with fancyindex off;?

**Comment by arnova** [comment]
Just tried those settings here: still can't reproduce it. Only thing I can come up with for now is that it's somehow related to either 05fff94ec9064c3ff914a10c0857408a79bb58dd or 1dcf93e5860613ab9e31316f78f08458e24c1b36

**Comment by arnova** [comment]
> can you try with fancyindex off;?

I think if you disable that you need to enable normal indexing (autoindex on) else webdav won't work.

**Comment by kib** [comment]
do you have a real certificate or something self-signed ?

**Comment by erpalma** [comment]
I use a valid cert from letsencrypt

**Comment by hnz101** [comment]
I also can't reproduce it under Windows with Kodi 18.2 x64 build. So my guess is that it is somehow an Android specific problem.

btw my nginx webdav settings also using a valid let's encrypt certificate:
```
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
ssl_ecdh_curve secp384r1;
ssl_session_cache shared:SSL:10m;
ssl_session_tickets off;
ssl_stapling on;
ssl_stapling_verify on;
resolver 8.8.8.8 8.8.4.4 valid=300s;
resolver_timeout 5s;
add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";
add_header X-Frame-Options DENY;
add_header X-Content-Type-Options nosniff;

server {
	listen 443 http2 ssl;
	server_name myurl.com;
	root /srv/htdocs/root;

	[...]

	location /dav {
		auth_basic "priv";
		auth_basic_user_file /etc/nginx/.videousers;

		autoindex on;
		autoindex_exact_size off;

		dav_methods PUT DELETE MKCOL COPY MOVE;
		dav_ext_methods PROPFIND OPTIONS;

		alias /mnt/videos;
		index index.php index.html index.htm;
		location ~ \.php$ {
			try_files /dummy/$uri @php;
		}
	}
	include /etc/nginx/conf.d/ssl-common;
}
```

**Comment by erpalma** [comment]
Interestingly switching to plain HTTP (dav://) does "fix" this issue. I tried to play with TLS settings in nginx but folders are not displayed. To save time when I performed the test with WsgiDAV I did it without TLS, I'll repeat this test with encryption enabled.

**Comment by hnz101** [comment]
> 
> 
> Just tried those settings here: still can't reproduce it. Only thing I can come up with for now is that it's somehow related to either [05fff94](https://github.com/xbmc/xbmc/commit/05fff94ec9064c3ff914a10c0857408a79bb58dd) or [1dcf93e](https://github.com/xbmc/xbmc/commit/1dcf93e5860613ab9e31316f78f08458e24c1b36)

Just a thought regarding [05fff94](https://github.com/xbmc/xbmc/commit/05fff94ec9064c3ff914a10c0857408a79bb58dd)
there is "GetValue("Content-Encoding").empty()" but nginx for an instance response is lower case "content-encoding: gzip". Can that be a problem here?

**Comment by arnova** [comment]
> > Just tried those settings here: still can't reproduce it. Only thing I can come up with for now is that it's somehow related to either [05fff94](https://github.com/xbmc/xbmc/commit/05fff94ec9064c3ff914a10c0857408a79bb58dd) or [1dcf93e](https://github.com/xbmc/xbmc/commit/1dcf93e5860613ab9e31316f78f08458e24c1b36)
> 
> Just a thought regarding [05fff94](https://github.com/xbmc/xbmc/commit/05fff94ec9064c3ff914a10c0857408a79bb58dd)
> there is "GetValue("Content-Encoding").empty()" but nginx for an instance response is lower case "content-encoding: gzip". Can that be a problem here?

Unfortunately not: the value is internally first made lower case and then compared.

**Comment by arnova** [comment]
> Interestingly switching to plain HTTP (dav://) does "fix" this issue. I tried to play with TLS settings in nginx but folders are not displayed. To save time when I performed the test with WsgiDAV I did it without TLS, I'll repeat this test with encryption enabled.
> 
> Edit: working fine with WsgiDAV and TLS + basic auth enabled

Strange: http or https (dav/davs) shouldn't make any difference since it's only the transport layer. Are you absolutely sure that's the only difference?

**Comment by erpalma** [comment]
I agree with you that this is strange. I didn't change nginx config, just used dav:// instead of davs://

**Comment by arnova** [comment]
Having another look at your log, I see that you're using http2 so it could also be related to the simple fact that we enabled support for http2 in https://github.com/xbmc/xbmc/commit/8839957437f2c1557c5810aff2af820e50826370#diff-5c33c135f4ea7b423852cdc0951d5282

**Comment by erpalma** [comment]
I already tried to disable http2, but I just realized that it gets disabled only if *all* the other servers configured for the same port have http2 disabled as well. I'll try again this evening.

**Comment by hnz101** [comment]
> ps. Could you try disabling http2 in nginx?

you guessed right, I tested today with http2 disabled and it just works again under android while it doesn't make a difference with the windows build (http1.1 and http2 works).

So there must be some problem with the the android curl version.

**Comment by arnova** [comment]
> > ps. Could you try disabling http2 in nginx?
> 
> you guessed right, I tested today with http2 disabled and it just works again under android while it doesn't make a difference with the windows build (http1.1 and http2 works).
> 
> So there must be some problem with the the android curl version.

Thanks for reporting back. @erpalma can you confirm this?

@wsnipex: I think we need to add an as.xml option for this in Matrix and revert http2 support for Leia (?)

**Comment by wsnipex** [comment]
why not just add the same as.xml to leia as well? Removing http2 support in 18.3 would be a regression in terms of functionality.
Even better would be to fix the actual issue on android though.

**Comment by kib** [comment]
WebDAV is an extension to http 1.1 as far as I know. Isn't this just a misconfiguration of your nginx server which is not made aware of the fact that there is a http 1.1 only protocol behind it ?

**Comment by hnz101** [comment]
Like erpalma said it is not possible to enable http2 just for a few sites on the server. Even without the http2 tag in this webdav related block nginx would serve this webdav folder using http2.

AFAIK http2 is mainly transport layer like optimizations and shouldn't interfere with http1.1 features or extensions. But I am no expert here.

**Comment by arnova** [comment]
> WebDAV is an extension to http 1.1 as far as I know. (see https://tools.ietf.org/html/rfc4918)
> Isn't this just a misconfiguration of your nginx server on which you are offering an http 1.1 only protocol over http2?
> Not saying that this shouldn't be handled on our side as well, but that config is not supposed to work, and only works because the applications are (correctly) falling back to http1.1.

I'm tempted to say that http2 is only transport so it shouldn't matter for Webdav which is on a different layer (like eg. html).

**Comment by kib** [comment]
I would say, there is no need for nginx to handle the headers correctly because they do not exist in http2.

**Comment by wsnipex** [comment]
I cannot find any evidence for that claim. In fact nextcloud/owncloud seem to support webav over http2.

I'd really like to see another debug log with curl component logging enabled.

**Comment by wsnipex** [comment]
not familiar with the dav code at all, but https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/DAVFile.cpp#L77 looks like something we probably shouldn't do

**Comment by erpalma** [comment]
Sorry guys, busy week. I confirm that nginx without http2 works fine for Kodi under Linux!

**Comment by arnova** [comment]
> not familiar with the dav code at all, but https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/DAVFile.cpp#L77 looks like something we probably shouldn't do

Yes, good catch. Although I think it isn't responsible for the problem in this ticket. It looks like it will only catch failures and otherwise will just continue. But it's certainly something that needs some love.

**Comment by arnova** [comment]
> I would say, there is no need for nginx to handle the headers correctly because they do not exist in http2.
> However, as far as I can see the connection should just fall back to http/1.1

I don't know much about the internals of http2 so this may sound stupid but how are options and such passed between client and server then if there are no headers?

**Comment by wsnipex** [comment]
Http2 is a binary protocol, but was designed to be backwards compatible in the sense that you can translate/proxy to http1.1 easily. Curl also translates http2 frames to http1.1 style headers, so you get the same human readable output when using it e.g on the command line. IMHO the easiest fix for now would be to just disable http2 for WebDAV until is can be investigated more in depth

**Comment by wsnipex** [comment]
ok, from a very quick test https://github.com/wsnipex/xbmc/commit/1a605f0782b15999e566d05d62f9fe30f3007398 makes it work for me on linux.
I'm sure there is a cleaner solution, but I'll provide a android test build for you guys.

**Comment by arnova** [comment]
> ok, from a very quick test [wsnipex@1a605f0](https://github.com/wsnipex/xbmc/commit/1a605f0782b15999e566d05d62f9fe30f3007398) makes it work for me on linux.
> I'm sure there is a cleaner solution, but I'll provide a android test build for you guys.

Looks good. I was just about to mention DAVDirectory's http check but you beat me to it ;-)

**Comment by wsnipex** [comment]
android arm 32bit test build: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20190610-1a605f07-dav-http2-armeabi-v7a.apk

**Comment by hnz101** [comment]
> android arm 32bit test build: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20190610-1a605f07-dav-http2-armeabi-v7a.apk

This test build works for me. Debug log attached.
[kodi-20190610-1a605f07-dav-http2-armeabi-v7a..log](https://github.com/xbmc/xbmc/files/3275192/kodi-20190610-1a605f07-dav-http2-armeabi-v7a.log)

Also I am a little bit confused looking at the commit. curl recognizes http/2 as "HTTP/0.0"? unknown protocol?

**Comment by erpalma** [comment]
Thanks guys.
