### ISSUE TITLE
Build binary add-ons failed(Could NOT find OpenGLES2)

### ISSUE THREAD

**Issue by tigerjiang** [xbmc/xbmc#16205]
### Describe the bug
Build binary add-ons failed!!!

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I can continue the next step after the success of the add-ons building
## Actual Behavior

The add-ons build failed

### To Reproduce

Follow the [README.Android.md](https://github.com/xbmc/xbmc/blob/master/docs/README.Android.md), When I reach the 6 step , It failed
1. cd $HOME/kodi
2. make -j$(getconf _NPROCESSORS_ONLN) -C tools/depends/target/binary-addons

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

[ 66%] Performing configure step for 'visualization.spectrum'
-- Checking for module 'glesv2'
--   No package 'glesv2' found
-- Could NOT find OpenGLES2 (missing: OPENGLES2_gl_LIBRARY OPENGLES2_egl_LIBRARY) 
CMake Error at CMakeLists.txt:70 (message):
  No rendering API found.  Bailing

-- Configuring incomplete, errors occurred!
See also "/home/jiangzehu/open-source/kodi-android/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug/visualization.spectrum-prefix/src/visualization.spectrum-build/CMakeFiles/CMakeOutput.log".
See also "/home/jiangzehu/open-source/kodi-android/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug/visualization.spectrum-prefix/src/visualization.spectrum-build/CMakeFiles/CMakeError.log".
CMakeFiles/visualization.spectrum.dir/build.make:106: recipe for target 'visualization.spectrum-prefix/src/visualization.spectrum-stamp/visualization.spectrum-configure' failed
make[4]: *** [visualization.spectrum-prefix/src/visualization.spectrum-stamp/visualization.spectrum-configure] Error 1
make[4]: Leaving directory '/home/jiangzehu/open-source/kodi-android/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug'
CMakeFiles/Makefile2:6425: recipe for target 'CMakeFiles/visualization.spectrum.dir/all' failed
make[3]: *** [CMakeFiles/visualization.spectrum.dir/all] Error 2
make[3]: Leaving directory '/home/jiangzehu/open-source/kodi-android/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug'
CMakeFiles/Makefile2:6437: recipe for target 'CMakeFiles/visualization.spectrum.dir/rule' failed
make[2]: *** [CMakeFiles/visualization.spectrum.dir/rule] Error 2
make[2]: Leaving directory '/home/jiangzehu/open-source/kodi-android/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug'
Makefile:2458: recipe for target 'visualization.spectrum' failed
make[1]: *** [visualization.spectrum] Error 2
make[1]: Leaving directory '/home/jiangzehu/open-source/kodi-android/tools/depends/target/binary-addons/arm-linux-androideabi-21-debug'
touch .installed-arm-linux-androideabi-21-debug
make: Leaving directory '/home/jiangzehu/open-source/kodi-android/tools/depends/target/binary-addons'

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [×] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by AMoo-Miki** [comment]
I had exactly the same problem compiling an Android arm build on the 64-bit Ubuntu 18.04.2. Even if I skip the binary-addons, Kodi's build fails with exactly the same error.

To work around it, I ...

1. renamed `~/android-tools/arm-linux-androideabi-vanilla/android-21/sysroot/usr/lib` to `lib2`
1. copied the content of `~/android-tools/arm-linux-androideabi-vanilla/android-21/sysroot/usr/lib2/arm-linux-androideabi` **(cp \*.a)** into the new `lib`
1. copied the content of `~/android-tools/arm-linux-androideabi-vanilla/android-21/sysroot/usr/lib2/arm-linux-androideabi/21` **(cp \*)** into the new `lib`

Looking at the Jenkins builds, the paths in the toolchain seem to be different.

**Comment by Rechi** [comment]
Which Android NDK are you using? Also post a complete build log including the exact executed commands.

**Comment by AMoo-Miki** [comment]
I got the error when executing `make -j$(getconf _NPROCESSORS_ONLN) -C tools/depends/target/binary-addons` as well as with `make -C tools/depends/target/cmakebuildsys`; steps 6 and 7 of the [Android build guide](https://github.com/xbmc/xbmc/blob/master/docs/README.Android.md).
My NDK was r19c and I changed the command that referenced r18 to use this.
The error message was identical to the one @tigerjiang posted above.

**Comment by Rechi** [comment]
Only NDK r18 is supported.

**Comment by AMoo-Miki** [comment]
I just noticed that. Perhaps @tigerjiang used r18. I will try with r18 and post back if I had the problem.

**Comment by AMoo-Miki** [comment]
I tested r18b (renamed to 18) and binary-addons compile just fine.

**Comment by tigerjiang** [comment]
@AMoo-Miki  My NDK version is r19, I will use the r18 to rebuild, Thanks
