### ISSUE TITLE
Kodi on Android TV (SHIELD TV) keeps failing to install add-on dependencies

### ISSUE THREAD

**Issue by Verequies** [xbmc/xbmc#16203]
### Describe the bug
When you go to install any add-on that tries to install dependencies, most of the time those dependencies fail. You have to keep trying to install them, and eventually they will install.

## Expected Behavior
Dependencies are installed the first time.

## Actual Behavior
The dependencies fail to install until they do install.

### To Reproduce
Install Kodi on Android TV (on a SHIELD TV) and try to install add-ons.

### Debuglog
Example error:
```
2019-05-26 19:30:47.940 T:10742 WARNING: CGUIMediaWindow::OnMessage - updating in progress
2019-05-26 19:31:13.938 T:11642   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
2019-05-26 19:31:13.939 T:11642   ERROR: CCurlFile::Open failed with code 400 for http://kodi.melbourneitmirror.net/addons/leia/weather.metoffice/weather.metoffice-2.0.1.zip:
2019-05-26 19:31:13.939 T:11642   ERROR: CAddonInstallJob[weather.metoffice]: failed to download special://home/addons/packages/weather.metoffice-2.0.1.zip
```

### Your Environment
- Android 8.0.0
- NVIDIA SHIELD TV 2017 16GiB
 - Operating system version/name: Android TV
 - Kodi version: 18.2

**Comment by KarellenX** [comment]
Similar reports here, using the same mirror... https://forum.kodi.tv/showthread.php?tid=343468

@Verequies Is that your thread?
Can you also post the full debug log thanks.

**Comment by bossanova808** [comment]
Can confirm this also definitely happens on a Nexus 7 tablet and Motorola G4 phone.  In Australia, as least.

**Comment by Verequies** [comment]
@KarellenX That isn't my thread, but I will definitely do a full debug log tonight when I get home.

**Comment by Verequies** [comment]
Sorry guys for the wait, finally managed to get round to doing this. Here is an attached log.
[kodi.log](https://github.com/xbmc/xbmc/files/3245633/kodi.log)

**Comment by DaVukovic** [comment]
For what I can see in the log it only fails for  http://kodi.melbourneitmirror.net/ and works fine as long as that mirror is not in use

Probably @Rechi is able to tell more as I can reach the source to download the file manually pretty fine.

**Comment by Rechi** [comment]
It is cause by https://github.com/apache/trafficserver/issues/3813. There isn't much we can do except disabling the mirror, which I already did.

**Comment by Verequies** [comment]
So if I understand correctly, we are presenting an upgrade header when connecting to the mirror? Should we be doing that at all if its not a websocket?

**Comment by Rechi** [comment]
Curl does that, because Kodi sets `CURLOPT_HTTP_VERSION` to `CURL_HTTP_VERSION_2_0`. Yes this behaviour is correct, see https://tools.ietf.org/html/rfc7540#section-3.2.

I don't know why the label Websockets was added at https://github.com/apache/trafficserver/issues/3813. Maybe it is something different in their product then the WebSocket protocol or they just added it accidentally.

**Comment by fuzzard** [comment]
Is this still an issue any more, or has it been resolved by the mirror provider?

**Comment by bossanova808** [comment]
I've not had any issues lately personally.

**Comment by fuzzard** [comment]
Thanks for the feedback. I'll close this out for now.

Any issues pop up, feel free to open another issue. Sounds like we may not be using that mirror provider currently from what im told.
