### ISSUE TITLE
Audio channels not correct when playing Atmos on Nvidia Shield

### ISSUE THREAD

**Issue by Bimmerstyle** [xbmc/xbmc#16214]
### Describe the bug
Here is a clear and concise description of what the problem is:

The problem I have is the following: Whenever I play a movie/clip with Atmos sound, the sound does work. My receiver recognizes it as being Atmos and sound is coming from my speakers. However 2 times out of 3 the channels aren't placed correctly. Sometimes the audio that is supposed to come out of the center channel comes out of the left surround speaker, the atmos info comes out of the right front speaker, surround comes out of one of the Atmos speakers,... It's all messed up. When I restart the movie/demo sometimes it fixes itself, sometimes it doesn't. There are times I have to restart a video 3 or 4 times to get the sound to play correctly.

One demo, Dolby Nature's Fury, downloaded from Demo-World.eu never seems to work in Kodi. The channels are always messed up I redownloaded it with the same result. I thought it was a corrupt file but then I played it with VLC and in VLC it works just fine.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Sound that is suppose to come out of the center channel should come out of the center speaker.
Sound thas is suppose to come out of the right channel should come out of the right speaker.
The same goes for all other channels

## Actual Behavior

Sound that is suppose to come out of the center channel comes out of the left surround speaker
Sound that is suppose to come out of  the left channel comes out of one of the atmos speakers
This is an example. I wasn't able yet to pinpoint which channels come out which speakers exactly. Fact is that the channels are not in the correct place

### To Reproduce

Play the Dolby Nature's Fury demo in Kodi. It can be found on www.demo-world.eu/2d-demo-trailers-hd/ (I have no idea if this file is copyrighted however). This is the file I have the most problems with and is verified by an other user to give the same problem on his system. 

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/povibuwomi.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Created issue following this thread on Kodi Forums: https://forum.kodi.tv/showthread.php?tid=344212

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 8 (Android 8.0.0 API level 26, kernel: Linux ARM 64-bit version 4.9.109-tegra-g4fa2f5b)
 - Kodi version: 18.2 Git:20190422-f2643566d0

 - Receiver: Onkyo TX-NR676E

**Comment by HitcherUK** [comment]
Can confirm it took 3 attempts to get the sound to some out of the correct channels on my Shield TV + Denon Atmos amp.
First go the centre channel started ok, then during playback it came out the surround channel, and further still it came out of the right channel/
Second playback resulted in nothing.
Will supply my debug logs as well if needed.

**Comment by fritsch** [comment]
```
2019-05-26 16:35:01.144 T:25466  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 192000 format: AE_FMT_S16LE (AE) method: IEC (PT) stream-type: STREAM_TYPE_TRUEHD min_buffer_size: 196864 m_frames: 6152 m_frameSize: 16 channels: 8
2019-05-26 16:35:01.148 T:25466   DEBUG: CActiveAESink::OpenSink - AUDIOTRACK Initialized:
2019-05-26 16:35:01.148 T:25466   DEBUG:   Output Device : android
2019-05-26 16:35:01.148 T:25466   DEBUG:   Sample Rate   : 192000
2019-05-26 16:35:01.148 T:25466   DEBUG:   Sample Format : AE_FMT_S16NE
2019-05-26 16:35:01.148 T:25466   DEBUG:   Channel Count : 8
2019-05-26 16:35:01.148 T:25466   DEBUG:   Channel Layout: FL, FR, FC, LFE, BL, BR, SL, SR
2019-05-26 16:35:01.148 T:25466   DEBUG:   Frames        : 6152
2019-05-26 16:35:01.148 T:25466   DEBUG:   Frame Size    : 16
```

IEC mode in use. If it's working on Windows / Linux it's a firmware bug. If it's broken there, too - it's an IEC packaging bug. Please try with the "forceraw" build on the Shield. This will use nvidia's own IEC packer - just to compare.

**Comment by xinseo** [comment]
Can confirm this issue exists. Can anyone explain where I can get this forceraw build.

**Comment by sectune** [comment]
Hi xinseo,
you can find the forceraw build here:
http://mirrors.kodi.tv/test-builds/android/arm64-v8a/
P.S: not affiliated with Kodi in any way. Just an interested lurker looking for upcoming features in Kodi :)

**Comment by Bimmerstyle** [comment]
Tested various files with the Forceraw build and the sound played like it should everytime.

**Comment by xinseo** [comment]
So that means it's a Kodi issue?

**Comment by fritsch** [comment]
No. Please read. For now it's your issue. Someone needs to test on windows / Linux as those use the same code. If it works: shield firmware bug, else packer bug.

I already told that above.

**Comment by blunden** [comment]
I might be able to try this with my Atmos soundbar from my laptop. It has a micro-HDMI port but I think I have an adapter somewhere, if I can find it. :)

Is the issue visible in the debug log (i.e. is the Channel Layout values expected to change order between runs when the issue occurs?) or will I have to listen for the incorrect speaker output?

**Comment by fritsch** [comment]
If you install the newest v19, you can choose from the settings: Audiotrack (RAW) instead of Audiotrack (IEC), please try that - does it work for you as well?

**Comment by blunden** [comment]
> If you install the newest v19, you can choose from the settings: Audiotrack (RAW) instead of Audiotrack (IEC), please try that - does it work for you as well?

I can try both. IEC is the one you are most interested in though, right?

But just to confirm, is it enough to run the demo video a few times and compare the channel layout values between those runs in the debug log?

**Comment by blunden** [comment]
I couldn't find that adapter so I bought a new one that just arrived. :)

@fritsch So simply playing the demo clip using Kodi on Windows a few times with full logging enabled should get you what you need in terms of confirmation of the issue on other platforms?

**Comment by fritsch** [comment]
Please install a v19 nightly on your Android box and play the file two times. One time with the passthrough device RAW and one time with IEC and if you can compare on windows, try it as well.

**Comment by blunden** [comment]
@fritsch That would replace my current stable version of Kodi 18.x though since they have the same package name. I would really prefer not to do that. I thought people had already confirmed that it worked on Android using RAW mode with the forceraw build though?

What I can do is help you confirm whether it happens on other platforms or not, as you requested earlier.
