### ISSUE TITLE
WARNING: ActiveAE - large audio sync error + hard crash

### ISSUE THREAD

**Issue by stephen147** [xbmc/xbmc#16236]
## Bug report
Hard crash when playing media (which can be anything as I've tried quite a few)

### To Reproduce
1. Clean install
2. Start playing media.
2. Hard crashes instantly.
4. Same with any media I try.

### Debuglog
https://pastebin.com/PUMG58Vi

### Your Environment
 - [x] Windows
 - Microsoft Windows 10 Pro _10.0.17763 N/A Build 17763_
 - Kodi version: v18.2 (_portable on 10G NAS_)

## Note
The install is on my 10G Synology NAS. Playing the files are fine in any media player even in 4k. See transfer results.
```
-----------------------------------------------------------------------
CrystalDiskMark 6.0.0 Shizuku Edition x64 (C) 2007-2017 hiyohiyo
                          Crystal Dew World : https://crystalmark.info/
-----------------------------------------------------------------------
* MB/s = 1,000,000 bytes/s [SATA/600 = 600,000,000 bytes/s]
* KB = 1000 bytes, KiB = 1024 bytes

   Sequential Read (Q= 32,T= 1) :  1175.857 MB/s
  Sequential Write (Q= 32,T= 1) :   418.553 MB/s
  Random Read 4KiB (Q=  8,T= 8) :    84.528 MB/s [  20636.7 IOPS]
 Random Write 4KiB (Q=  8,T= 8) :    65.890 MB/s [  16086.4 IOPS]
  Random Read 4KiB (Q= 32,T= 1) :    79.386 MB/s [  19381.3 IOPS]
 Random Write 4KiB (Q= 32,T= 1) :    63.244 MB/s [  15440.4 IOPS]
  Random Read 4KiB (Q=  1,T= 1) :     7.196 MB/s [   1756.8 IOPS]
 Random Write 4KiB (Q=  1,T= 1) :     7.107 MB/s [   1735.1 IOPS]

  Test : 1024 MiB [Z: 42.1% (12049.5/28598.1 GiB)] (x5)  [Interval=5 sec]
  Date : 2019/06/04 22:32:00
    OS : Windows 10 Professional [10.0 Build 17763] (x64)
```

**Comment by KarellenX** [comment]
> Kodi version: v18.2 (portable on 10G NAS)

And is your NAS plugged into your TV/Monitory via HDMI cable?

**Comment by stephen147** [comment]
Kodi is installed on that 10G mapped network drive. NAS is just connected to my PC via a cat 6e cable.

Kodi opens fine and runs smooth but playing any media hard crashes it within 10seconds.

The problem doesn't arise when I switch the audio device to the front headphone jack. 

Just when audio is played through a Bluetooth speaker. I'll get the model no' of the speaker and driver details when I'm at my PC tomorrow.

**Comment by KarellenX** [comment]
No, don't need speaker model no's. 

If I understand correctly, you do not have Kodi on your local machine which is attached to a TV/Monitor. Rather you have NAS>PC>TV, and somewhere in that is an AVR.

This is not an issue with Kodi, rather it is an issue with an unconventional setup.

Kodi is designed to be plugged directly into a TV/Monitor, not at the start of a chain of connections.

I would suggest posting on the forum, but I am pretty sure you won't receive many useful responses about your setup there either.

**Comment by stephen147** [comment]
#### I've installed as per kodi's official docs:
https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Windows#Portable_Mode

Not sure why this can't be classed as a bug.

**Comment by KarellenX** [comment]
Yes, but it needs to be installed on the equipment directly connected to your TV. Using Portable Mode does not bypass that requirement. 

Kodi is not a server.

**Comment by DaVukovic** [comment]
Í'm pretty much confused as well. The error in the log shows Kodi installed on a normal windows 10 machine, still you (@stephen147 ) are saying that Kodi is installled on some NAS. 

Probably you should explain a bit more what is installed on what device and which device has the problem. 

What I see here: 

2019-06-04 22:19:03.306 T:23340  NOTICE: special://xbmc/ is mapped to: Z:\Movies & TV\Apps\Kodi_Clean_Install\Kodi

Does that mean you have a shared folder (using a network drive "Z:" in that case) and simply change the installation path for Kodi on that windows 10 machine being that network drive?

Have you tried installing Kodi natively on C:\Program_Files or whatever the default installation path is and see if that makes any difference?

For what I suspect Kodi is not natively installed on the NAS. Kodi is installed on that Windows 10 machine but has a different installation path. 

I might be wrong though

**Comment by KarellenX** [comment]
Yes the way it is written is confusing, but he has mentioned install on a NAS three times

> Kodi version: v18.2 (portable on 10G NAS)

> Note: The install is on my 10G Synology NAS

> Kodi is installed on that 10G mapped network drive. NAS is just connected to my PC via a cat 6e cable.

I think the member is under the impression that Portable Install should work "anywhere"

**Comment by DaVukovic** [comment]
I'm under the same impression, tbh ;)

As it's only a simple network drive which still uses the same resources from the machine where the network drive is connected to. 

But you will know better in that case as I'm not much of a Windows guy

**Comment by stephen147** [comment]
## Yes, this
> 10G mapped network drive

Kodi is installed as per the official guide for portable installation on windows with the only difference being to my **mapped drive** `Z:` as opposed to a thumb drive.

I'm in the process of testing the `C:\Program_Files` method.

To clarify, it's a mapped network drive. I have many other programs installed directly on it with very little issues.

**Comment by stephen147** [comment]
Exact same issue with installing to `C:\Program_Files\kodi`

## New Bug report
* Hard crash when playing **any media**.

### Steps To Reproduce
1. Clean install to `C:\Program_Files\kodi`
2. Open kodi
2. Start playing media
2. Hard crash instantly


### New Debuglog
https://pastebin.com/ak5EUEbY

### Environment
 - *Microsoft Windows 10 Pro* 10.0.17763 N/A Build 17763
 - Kodi version: v18.2

**Comment by stephen147** [comment]
Additional info
---
Like I have mentioned in this thread the issue appears to arise when the default audio device is a Bluetooth speaker _(I had the same issues with a different BT speaker in the past listed below)_.

My current BT speaker is the: [ SoundCore Pro ]( https://www.anker.com/uk/products/variant/soundcore-boost/A3145011 )

* As the front audio jack works as expected with headphones.
* It does appear as though it's related to a Bluetooth issue.
* I have the most up to date drivers installed and firmware for the device.

I had the exact same issue with this model below
---
[ Creative Sound BlasterX Katana Multi-Channel Gaming Soundbar ]( https://smile.amazon.co.uk/gp/product/B01N5FV9PC/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1 )
