### ISSUE TITLE
Fire TV Basic: Kodi 19 crashes on startup back to Fire TV menu without error message

### ISSUE THREAD

**Issue by nuwonda** [xbmc/xbmc#16233]
### Describe the bug
last working build for fire tv basic is:
kodi-20190523-3bb5115b-master-armeabi-v7a.apk dated May 24th (build from 23rd)

any build after that keeps crashing immediately back to Fire TV home menu after the "clearing cache" followed by "preparing for first launch..." message disappears.

reinstalling the kodi-20190523-3bb5115b build will work, so it must be a change from this build to the one after that broke it.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

1. install any Kodi 19 build  after kodi-20190523-3bb5115b-master-armeabi-v7a.apk on a Fire TV Basic Stick or a Fire HD 8 Tablet
2. Launch Kodi from Fire TV Home menu after successful installation
3. Kodi displays clearing cache and preparing for first launch message and launches normally into the Kodi Home menu

## Actual Behavior

1. install any Kodi 9 build  after kodi-20190523-3bb5115b-master-armeabi-v7a.apk on a Fire TV Basic Stick 
2. Launch Kodi from Fire TV Home menu after successful installation
3. Kodi displays clearing cache and preparing for first launch message and after progress bar is complete it crashes back to the Fire TV home menu without giving any error message.

## Possible Fix

reinstalling the kodi-20190523-3bb5115b build will work, so it must be a change from this build to the one after that broke it.

### To Reproduce

1. Install any kodi 19 build  after kodi-20190523-3bb5115b-master-armeabi-v7a.apk on a Fire TV Basic Stick (Fire OS 5.2.6.9, FireTV Home Version 6.1.5.1-002) 
2. Launch Kodi after successful installation
3. Kodi will crash  immediately back to the fire tv home menu after the "clearing cache" followed by "preparing for first launch..." message disappears without any error message.

### Debuglog

The debuglog can be found here:
https://pastebin.com/6dFNFBmG

### Screenshots 
Here are some links or screenshots to help explain the problem:

n/a

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

n/a

### Your Environment
Used Operating system:

 - [X] Android (Fire OS 5.2.6.9, FireTV Home Version 6.1.5.1-002) 
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
 any Kodi 9 build  after kodi-20190523-3bb5115b-master-armeabi-v7a.apk

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Not much help from my side, but if Kodi crashes it normally creates a crashlog. Could you please provide that?

**Comment by nuwonda** [comment]
added a link to the kodi.log didnt find any crashlog anywhere
the log ends with:
2019-06-03 18:58:14.729 T:3896  NOTICE: CWinSystemAndroid::DestroyWindow
which results in Kodi quitting (maybe not crashing then) back to Fire TV Home menu.

**Comment by nuwonda** [comment]
> Not much help from my side, but if Kodi crashes it normally creates a crashlog. Could you please provide that?

log added. let me know if i can help in any other way. cheers

**Comment by nuwonda** [comment]
Issue still persists with latest build from July 12th. Did a complete new install as well on both devices.

**Comment by federicobriata** [comment]
Hi, I confirm I'm able to reproduce this issue on Amazon Firestick Tank and that with Kodi 18.x and till kodi-20190523-3bb5115b-master-armeabi-v7a.apk once Kodi is started I'm able to press "home" to put kodi in background and when I click on kodi Icon is opening from where I left, this is no more possible to kodi 19.
@DaVukovic can you support us or clarify what information you need still?
thanks

**Comment by atrasatti** [comment]
At least the symptoms are the same as #20620

**Comment by thexai** [comment]
Closed for now as it seems resolved in latest Fire TV firm. update.

See : https://github.com/xbmc/xbmc/issues/20620
