### ISSUE TITLE
Crash, crash 

### ISSUE THREAD

**Issue by faltaren** [xbmc/xbmc#16234]
### Describe the bug
Here is a clear and concise description of what the problem is: Kodi crashes when i start it. stops after like 10 tries.

Crashing and keeps crashing on start

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Well not crash when it starts

## Actual Behavior

crashes multi times when i try to start it

## Possible Fix

Dunno

### To Reproduce

1. i start kodi on win 10, dont know more
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ x] Windows 10
 - [ ] Windows UWP

 - Operating system version/name: win 10 8latest update)
[kodi_stacktrace-19.0-ALPHA1 Git_20190602-cf9c1b2db2-20190603-193959.txt](https://github.com/xbmc/xbmc/files/3249232/kodi_stacktrace-19.0-ALPHA1.Git_20190602-cf9c1b2db2-20190603-193959.txt)
[kodi_stacktrace-19.0-ALPHA1 Git_20190602-cf9c1b2db2-20190603-194005.txt](https://github.com/xbmc/xbmc/files/3249233/kodi_stacktrace-19.0-ALPHA1.Git_20190602-cf9c1b2db2-20190603-194005.txt)
[kodi.log](https://github.com/xbmc/xbmc/files/3249234/kodi.log)
[kodi.old.log](https://github.com/xbmc/xbmc/files/3249235/kodi.old.log)

[kodi_stacktrace-18.2 Git_20190422-f2643566d0-20190603-192508.txt](https://github.com/xbmc/xbmc/files/3249236/kodi_stacktrace-18.2.Git_20190422-f2643566d0-20190603-192508.txt)
[kodi_stacktrace-18.2 Git_20190422-f2643566d0-20190603-192531.txt](https://github.com/xbmc/xbmc/files/3249237/kodi_stacktrace-18.2.Git_20190422-f2643566d0-20190603-192531.txt)
[kodi_stacktrace-18.2 Git_20190422-f2643566d0-20190603-192553.txt](https://github.com/xbmc/xbmc/files/3249238/kodi_stacktrace-18.2.Git_20190422-f2643566d0-20190603-192553.txt)
[kodi_stacktrace-18.2 Git_20190422-f2643566d0-20190603-192605.txt](https://github.com/xbmc/xbmc/files/3249239/kodi_stacktrace-18.2.Git_20190422-f2643566d0-20190603-192605.txt)
[kodi_stacktrace-18.2 Git_20190422-f2643566d0-20190603-192609.txt](https://github.com/xbmc/xbmc/files/3249240/kodi_stacktrace-18.2.Git_20190422-f2643566d0-20190603-192609.txt)
[kodi_stacktrace-18.2 Git_20190422-f2643566d0-20190603-192616.txt](https://github.com/xbmc/xbmc/files/3249241/kodi_stacktrace-18.2.Git_20190422-f2643566d0-20190603-192616.txt)
[kodi_stacktrace-18.2 Git_20190422-f2643566d0-20190603-192629.txt](https://github.com/xbmc/xbmc/files/3249242/kodi_stacktrace-18.2.Git_20190422-f2643566d0-20190603-192629.txt)
[kodi_stacktrace-18.2 Git_20190422-f2643566d0-20190603-192839.txt](https://github.com/xbmc/xbmc/files/3249243/kodi_stacktrace-18.2.Git_20190422-f2643566d0-20190603-192839.txt)
[kodi_stacktrace-18.2 Git_20190422-f2643566d0-20190603-192845.txt](https://github.com/xbmc/xbmc/files/3249244/kodi_stacktrace-18.2.Git_20190422-f2643566d0-20190603-192845.txt)
[kodi_stacktrace-18.2 Git_20190422-f2643566d0-20190603-192851.txt](https://github.com/xbmc/xbmc/files/3249245/kodi_stacktrace-18.2.Git_20190422-f2643566d0-20190603-192851.txt)
[kodi_stacktrace-18.2 Git_20190422-f2643566d0-20190603-193048.txt](https://github.com/xbmc/xbmc/files/3249246/kodi_stacktrace-18.2.Git_20190422-f2643566d0-20190603-193048.txt)
[kodi_stacktrace-18.2 Git_20190422-f2643566d0-20190603-193502.txt](https://github.com/xbmc/xbmc/files/3249247/kodi_stacktrace-18.2.Git_20190422-f2643566d0-20190603-193502.txt)
[kodi_stacktrace-18.2 Git_20190422-f2643566d0-20190603-193528.txt](https://github.com/xbmc/xbmc/files/3249248/kodi_stacktrace-18.2.Git_20190422-f2643566d0-20190603-193528.txt)
[kodi_stacktrace-18.2 Git_20190422-f2643566d0-20190603-193822.txt](https://github.com/xbmc/xbmc/files/3249249/kodi_stacktrace-18.2.Git_20190422-f2643566d0-20190603-193822.txt)
[kodi_stacktrace-19.0-ALPHA1 Git_20190602-cf9c1b2db2-20190603-193951.txt](https://github.com/xbmc/xbmc/files/3249250/kodi_stacktrace-19.0-ALPHA1.Git_20190602-cf9c1b2db2-20190603-193951.txt)

 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@faltaren

I have closed your Issue report as it is a problem with your local system, not a general Kodi bug.

Please ask your question on the forum, where members can assist in diagnosing the cause.
