### ISSUE TITLE
Default Playback Speed

### ISSUE THREAD

**Issue by Mongoo8e** [xbmc/xbmc#16235]
It would be really nice if a playback speed (tempoup?) could be set as **default** in the settings menu somewhere so we can watch everything at "x" Speed.  I made a messy add-on to handle this.  Personally I watch everything at 1.10x and it makes no observable difference except for giving me 10% more time.  To be quite specific, 1.12x is the maximum before I start noticing (tested with VLC) but the playback speed can not be fine tuned in Kodi currently, I'm sure this value will be different for a lot of people.  Make this a setting and imagine how much time people can save (or waste to watch more stuff!).

**Comment by Mongoo8e** [comment]
This is an enhancement, not a bug report which the template supplies.

> Thank you for using Kodi and our issue tracker. This is your friendly Kodi GitHub bot 😉
> 
> It seems that you have not followed the template we provide and require for all bug reports (or have opened a roadmap item by accident). Please understand that following the template is _mandatory_ and required for the team to be able handle the volume of open issues efficiently.
> 
> Please edit your issue message to follow our [template](https://github.com/xbmc/xbmc/blob/master/.github/ISSUE_TEMPLATE.md) and make sure to fill in all fields appropriately. The issue will be closed after one week has passed without satisfactory follow-up from your side.
> 
> This is an automatically generated message. If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.

This is a product enhancement, not a bug report which the template supplies.

**Comment by lrusak** [comment]
Feature requests are done in the forum. Thanks for understanding.
