### ISSUE TITLE
Kodi does not work with mesa 19.0.6

### ISSUE THREAD

**Issue by texstar** [xbmc/xbmc#16251]
I updated mesa to 19.0.6 and kodi stopped working. 

$ kodi
/usr/bin/kodi: line 219: 27205 Bus error               ${KODI_BINARY} $SAVED_ARGS
Crash report available at /home/user/kodi_crashlog-20190608_103242.log

919136320   ERROR: DBus error: org.freedesktop.DBus.Error.ServiceUnknown

**Comment by DaVukovic** [comment]
@texstar 

please provide a full debuglogg or the crash report the message points you to. Otherwise this issue will be closed

Thanks in advance

**Comment by texstar** [comment]
There is no full debuglog. Just a dbus error so go ahead and close it. I've already backed down to mesa 19.0.5 so I can use kodi and will wait for mesa 19.1.0 and see what that version brings to the table.

**Comment by bkuhls** [comment]
Saw the same problem here with kodi-17.6, reverting to mesa3d 19.0.5 also fixed the problem. I suspect this commit being responsible:
https://cgit.freedesktop.org/mesa/mesa/commit/?h=19.0&id=0b9b177f4d42951f63eb896850bf35da3b04abab
gdb showed a crash in some egl function, will report back with a backtrace if you wish.

**Comment by bkuhls** [comment]
Please try mesa3d 19.0.8:
https://lists.freedesktop.org/archives/mesa-announce/2019-June/000525.html

**Comment by texstar** [comment]
Those mesa fellers sure got things kinda messed up. mesa3d 19.0.8 fixed all of my issues with kodi, vlc and minitube using the opensoure nouveau driver.
