### ISSUE TITLE
feature_python3 - Illegal instruction: 4 (core dumped)

### ISSUE THREAD

**Issue by FraserChapman** [xbmc/xbmc#16256]
### Describe the bug

feature_python3 branch crashes when any addon is run on macOS.

## Expected Behavior

I would expect to be able to open/run some addons that are "python 3" compatible. 

## Actual Behavior

Kodi freezes and crashes out with: Illegal instruction: 4 (core dumped)

### To Reproduce

1. Build https://github.com/xbmc/xbmc/tree/feature_python3 for macOS
2. Add any addon
3. Run the addon

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/quvituhebe.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Mojave - OS X 10.14.5, kernel: Darwin x86 64-bit version 18.6.0
 - Kodi version:  Kodi (19.0-ALPHA1 Git:20190604-1dd3b4584c)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by FraserChapman** [comment]
Just to note - I had raised this here - https://forum.kodi.tv/showthread.php?tid=344500 - but wasn't sure if this was a better place for it. Obviously if this isn't the right place, or the bug report isn't valid - apologies and feel free to delete.

**Comment by Rechi** [comment]
This should be fixed in the feature_python3 branch. Please report back.

**Comment by enen92** [comment]
@FraserChapman can you confirm this is already fixed in master?

**Comment by FraserChapman** [comment]
@Rechi @enen92  - Hi, sorry for the delay (was walking across the UK then cycling across France!) - yes I can confirm this is working in the feature_python3 branch and will test master today. Again apologies for the lack of response before now.

**Comment by fuzzard** [comment]
Thanks for reporting the issue. Closing as fixed
