### ISSUE TITLE
Video playback "resume" does not work for DVD ISOs

### ISSUE THREAD

**Issue by ronbaby** [xbmc/xbmc#16252]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi's video playback resume functionality fails to work properly when an attempt is made to resume watching a video file that happens to be a .ISO file representing a DVD rip. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Of course, the user expects the video "resume" operation/selection to behave as it should, as it historically always has, and as it still does for other kinds of video files being played back (e.g. .mp4 files).

## Actual Behavior

Instead of resuming video playback at the placed where video playback last stopped, in the case of DVD .ISO files (only) selecting "Resume" from the on-screen menu instead causes the video playback of the DVD .ISO to start again from the very beginning.

## Possible Fix

Resume of DVD .ISO files used to work just fine, and was only broken relatively recently (perhaps starting with the 18.x releases).  So the "fix" would be to just put back the code that formerly handled this properly in the case of DVD .ISO files.

### To Reproduce

1.  Start video playback of a particular .ISO file representing a DVD rip.
2.  Let the video playback run for a little while... say like 10+ minutes.
3. Stop playback.
4.  Exit Kodi and restart it.  NOTE!  This step appears to be necessary to reproduce the issue.
5.  Navigate again to the specific .ISO file that was played in step 1 above.
6. Click/select that .iso file.
7.  You should get a little menu which should allowing you to choose to either (a) restart playback from the point where you left off watching last time or else (b) start playing the .ISO file from the beginning again.  Select (a), resume, from where you left off watching last time.
8. Note that playback of the DVD .ISO *actually* starts from the very beginning again, contrary to what you had requested.

### Debuglog

The debuglog can be found here:
NOTE:  I am providing log files from both before and after the Kodi shutdown/restart that is apparently needed in order to reproduce this issue:

Before:
https://pastebin.com/raw/MvK3qxcy
After:
https://pastebin.com/raw/ueF2trkz

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP
NOTE: This issue also appears to affect LibreELEC 9.0.2 (based on Kodi 18.2)

 - Operating system version/name: Ubuntu 16.04
 - Kodi version: 18.2
(Note:  resume for DVD ISO worked properly as recently as Kodi 17.6.)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by bahusoid** [comment]
I'm not sure if it's the same issue or not but for me resume doesn't work for blue-ray/dvd videos stored  as folders (so in `BDMV`, `VIDEO_TS` folders ) with setting `Media -> Videos -> Combine Split Video Items` enabled:
![image](https://user-images.githubusercontent.com/22025304/68853307-57954f80-06e2-11ea-8a5d-8680cb9a0080.png)

And setting  `Settings -> Player  -> Discs -> Blue-ray playback mode`  set to "Show simplified menu":
![image](https://user-images.githubusercontent.com/22025304/68853423-a347f900-06e2-11ea-994a-563854d2b2a4.png)

In this case on request to resume video Blue-ray/DVD Menu is opened instead:
<details> <summary>Resume Request</summary> 

![image](https://user-images.githubusercontent.com/22025304/68853954-bd360b80-06e3-11ea-9e89-921631a49f03.png)
</details>

<details> <summary>Blue-Ray menu is opened instead</summary> 

![image](https://user-images.githubusercontent.com/22025304/68854217-49483300-06e4-11ea-81fd-e816dfbfa803.png)
</details>



As a workaround I changed `Settings -> Player  -> Discs -> Blue-ray playback mode` to `Play main movie`. With this setting KODI able to properly resume video.

**Comment by Sopor** [comment]
I have noticed that if i don't leave the folder where the ISO file is located it will work to resume, but if i press the Home button and enter the same folder again it will not work to resume.

**Comment by 133794m3r** [comment]
This also doesn't work even if you have it run from an IFO. It still doesn't resume playback.

**Comment by enen92** [comment]
This was fixed in Nexus (https://github.com/xbmc/xbmc/pull/21245)
Closing. If you still find some issue in some recent nightly build please report back.
