### ISSUE TITLE
Tone mapping parameter reset to default setting after Kodi restart

### ISSUE THREAD

**Issue by smp79** [xbmc/xbmc#16257]
### Describe the bug
Here is a clear and concise description of what the problem is:

Tone mapping parameter always reset to default "1.00" after Kodi is restarted.

### To Reproduce

Set it to anything other than 1.00, click "Set default for all media" and restart Kodi.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/tusaxibehu.kodi

### Your Environment
Used Operating system:

 - [x] Linux

 - Operating system version/name: LibreELEC
 - Kodi version: current master

**Comment by lrusak** [comment]
could be related
```
2019-06-10 21:13:33.055 T:140193060165760   DEBUG: CSettingsManager: requested setting (video.tonemapmethod) was not found.
2019-06-10 21:13:33.055 T:140193060165760   DEBUG: CSettingsManager: requested setting (video.tonemapparam) was not found.
```

although I don't see you playing any media that requires tonemapping in your log.

**Comment by smp79** [comment]
Method is set to Reinhard (default). I had some videos with HDR, I already deleted them. I can download some and make a new debug log if required. But that doesn't make a difference - tone mapping parameter always reset to default.

**Comment by neeto33** [comment]
I believe this may also be related to a PVR bug where DXVA is enabled in the settings but not applied when starting TV or changing channels. 
There is sometimes a strange side effect where if you change DXVA on/off and/o the Tone Mapping to "off", the Subtitles get enabled(!)

**Comment by EnragedN3wb** [comment]
Has there been any progress with this?

I'm a new user of Kodi & love it so far! Unfortunately the Reinhard preset looks absolutely awful on my new display, & having to constantly reconfigure tone mapping to off is my only real gripe, but setting as default after changing it does not seem to do anything. =\
