### ISSUE TITLE
Crash when using Sync To Display on Windows 10

### ISSUE THREAD

**Issue by ajm83** [xbmc/xbmc#16264]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi crashes when trying to play a video file with Sync To Display enabled.  It sometimes takes a few play/stops before it crashes but will usually do so within 3 or 4 attempts. If not then playing a different video will almost always trigger the crash. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video plays back synced to display

## Actual Behavior

Crash in approx 30% of attempts

### To Reproduce

1. Enable sync to display
2. Play and stop video or play a different one.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/wapizawera.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Trying to achieve smooth 24 hz playback. Not smooth with this enabled (when it does not crash) so issue seems to be unrelated to that.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X ] Windows
 - [ ] Windows UWP

GPU is a NVIDIA gt 1030 with latest driver from NVIDIA.com.  TV supports 24, 25, 50 and 60hz.

 - Operating system version/name: Win 10 Pro x64 build 1809 
 - Kodi version:
18.2 Git:20190422-f2643566d0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by shiftnumlock** [comment]
Same problem here. It also exists in Kodi 17.6. I have two Nvidia 780 GTX in SLI. I've tried disabling the SLI and running single GPU mode and setting the VSync properties to Application controlled. Let me know if there's anything else you'd like me to try. Also not sure why when it does work bitstreaming gets disabled and only PCM plays from my receiver.

**Comment by ajm83** [comment]
I believe disabling bit streaming is expected behaviour because the audio
needs to be sped up/slowed down to match the video.


On 24 Jul 2019 at 05:01, shiftnumlock <notifications@github.com> wrote:

Same problem here. It also exists in Kodi 17.6. I have two Nvidia 780 GTX
in SLI. I've tried disabling the SLI and running single GPU mode and
setting the VSync properties to Application controlled. Let me know if
there's anything else you'd like me to try. Also not sure why when it does
work bitstreaming gets disabled and only PCM plays from my receiver.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/xbmc/xbmc/issues/16264?email_source=notifications&email_token=AC4MSXYRKZO7MNVCXTFOPYDQA7H3HA5CNFSM4HXDLTG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2VDCVY#issuecomment-514470231>,
or mute the thread
