### ISSUE TITLE
Jerky GUI windows

### ISSUE THREAD

**Issue by popeye2468** [xbmc/xbmc#16278]
Running kodi 18.2 on windows 7 x64 and windows 10 x64

The kodi gui is jerky and not smooth its almost like refresh rate starts at 60hz but then drops to 24hz then eventually back to 60hz

this issue is present with no addons installed and with original skin and there is nothing in the log

its also been driving me insane so please help

**Comment by KarellenX** [comment]
@popeye2468 

A completely unhelpful report. You have ignored the template, you have not provided a debuglog, no idea what platform or what version of anything you are using.

I suggest you quickly rewrite your issue or it will be closed shortly.

**Comment by popeye2468** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/3293105/kodi.log)


sorry uploaded log

im on windows 7 x64 ( was on windows 10 x64 same issue )

im running i7 6700k
gtx 970
nvme
64gb ram

using the kodi leia 18.2 x64

**Comment by DaVukovic** [comment]
> 2019-06-15 13:55:05.343 T:5020  NOTICE: Disabled debug logging due to GUI setting. Level 0.

Not a debuglog

**Comment by popeye2468** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/3293197/kodi.log)
again sorry here is debug log

i couldnt get it to replicate this time, what seems to happen is it seems to drop the refresh rate and then almost stutter i would say

**Comment by KarellenX** [comment]
What setting have you selected for **Adjust display refresh rate**? Off, Always, On Start/Stop, or On Start?

Also **Sync playback to display**?

**Comment by popeye2468** [comment]
both are off
its literally just the navigation of the menus withn kodi, it happens more f kodi is left idle

there is a few of us that are having the issue only in windows

https://forum.kodi.tv/showthread.php?tid=327254

**Comment by popeye2468** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/3293891/kodi.log)


Here is a new log of my daily setup where the refresh rate drops like mad, fps drop to 12 and stay there until you get it to do something such as open an addon

**Comment by KarellenX** [comment]
The Moderators have determined that [Banned_addons](https://kodi.wiki/view/Banned_addons) are present on your system. To receive assistance here, these banned items must be removed. If a clean log is not submitted within 3 days, this issue will be closed.

**Comment by DaVukovic** [comment]
oops, missed that. Sorry

**Comment by popeye2468** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/3294305/kodi.log)

Sorry again

**Comment by DaVukovic** [comment]
This log still contains banned add-ons. In other words, not much has changed to the log you provided before. Could be please stop that spamming and could you please use a vanilla Kodi (no add-ons beside the default ones installed)?

If you are able to reproduce that issue with a vanilla Kodi, then please provide a new log. If you can't and it depends on the installation of some add-ons make sure you don't have any!!!! other 3rd party repo installed and you are only using add-ons from the Kodi repository. 
We don't care if Kodi issues do come up if you are using 3rd party repos especially not if those add-ons/repos are listed on our banned list. 
If there might be a problem with some add-on causing the Kodi GUI being jerky, then please tell us which add-on is required to reproduce this issue. 

Please do NOT provide any other logfile if you insist on keeping those banned add-ons installed. As mentioned above, if no 'clean' logfile will provided the issue will be closed. 

Thanks for understanding.

**Comment by popeye2468** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/3294363/kodi.log)

that one does it with only addons installed from official kodi repo

**Comment by ronie** [comment]
i've seen a number of reports on the forum where the CU LRC Lyrics addon is causing GUI issues.

while i have not been able to reproduce it myself, you might want to check if diabling that addon fixes your issue.

**Comment by popeye2468** [comment]
yeah done that but doesnt make a difference, it happens more if kodi has to load thumbnails from an addon such as iplayer or youtube

the issue is not present in kodi 17.6 it is also not present under libreelec or linux this only affects windows

**Comment by DaVukovic** [comment]
> it happens more if kodi has to load thumbnails from an addon such as iplayer or youtube

Which both are *not* installed by default. Hence I suggested to try it with a vanilla Kodi (no additional add-ons installed), then install add-ons one-by-one and let us know which add-on is causing the trouble. 

To have a fast "vanilla" Kodi, please close Kodi, rename the "Kodi" folder in `%appata%\Kodi` to something else like: `Kodi-backup` and restart Kodi. That's like a factory reset but all other add-ons, settings and such are stored at the "Kodi-backup" folder. Then try installing the add-ons one by one and let us know when the effect comes up

**Comment by popeye2468** [comment]
I did this but its present even when browsing the kodi repo i could install every addon available and not have an issue then at random times (Mainly after leaving system idle) it will struggle to move through the menus until you get it going again by loading an addon or scanning library etc

**Comment by popeye2468** [comment]
what does have an improvement is if i add --standalone to the shortcut then it happens less often if i set the refresh rate to 60hz

**Comment by popeye2468** [comment]
So just curious as to whether anything else has moved forward on this issue, it's driving me mental lol

**Comment by KarellenX** [comment]
No, not really. The issue is localised to your setup and is not a common problem for all Kodi users. We have suggested possible common errors and solutions which have not worked for you so we are at a loss as what could be causing it on your setup.

The only other thing that comes to mind is Nvidia's G-Sync setting. Do you have this enabled? If yes, then disable it.

If that does not solve the issue for you, then there is nothing else we can suggest at this stage.

**Comment by bigretromike** [comment]
I would love to see you @popeye2468 record what jerky gui you have. I have a slow downs in GUIs also but those are most of the times because of kodi slow down internally for some reason after long period of being inactive or when Library scanning is in background. But those slow down from kodi being inactive are present on all my devices. But those are probably not the type of 'jerky gui' you talking about.
