### ISSUE TITLE
Request for podcast addon to be submitted to official Kodi.tv repo

### ISSUE THREAD

**Issue by leopheard** [xbmc/xbmc#16287]
Please find a request for a Kodi addon submission as detailed in: [https://kodi.wiki/view/Submitting_Add-ons](url)

- Add-on name: Criminal Podcast
 - Add-on ID: plugins.audio.thisiscriminal
 - Version number: 1.0.1
 - Kodi/repository version: https://github.com/leopheard/thisiscriminal/
 - Code location URL: https://github.com/leopheard/thisiscriminal.git
 - Branch: master

I have checked the guidelines and the add-on adheres to the required guidelines.

Thanks

**Comment by kib** [comment]
Please read taht page more carefully and submit a pull request to the correct project repository. This is the Kodi project git repository itself, not one of the Kodi addons git repositories.

https://kodi.wiki/view/Submitting_Add-ons#Repository_lists <- those are the relevant repositories.
