### ISSUE TITLE
24 -> 25 FPS speedup no longer works.

### ISSUE THREAD

**Issue by Avi0** [xbmc/xbmc#16286]
### Describe the bug
Here is a clear and concise description of what the problem is:

My setup: Raspberry Pi 3+, LibreELEC 9.0.2 (Kodi 18.2).

I can't get 23.976 FPS movies play at 25 FPS speed. "Sync playback to display" on, "Adjust Display Refresh Rate" on. In advancedsettings.xml, I configured the refresh rate of 25 Hz for movies of 23-23 FPS.

This setup worked perfectly on Kodi 17 with LibreELEC 8.2.5, but no longer works with new LibreELEC/Kodi versions.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Display switches to 25Hz, movie speeds up to 25FPS with audio resample.

## Actual Behavior

Instead, display switches to 25Hz, but movie plays at ~24FPS speed with frame repeat each second.

### To Reproduce

1. Turn on "Sync playback to display", "Adjust Display Refresh Rate". 
2. In userdata/advancedsettings.xml, set the refresh rate for videos:

```
<advancedsettings>
	<video>
		  <adjustrefreshrate> 
			  <override>
				  <fpsmin>23.9</fpsmin>
				  <fpsmax>24.5</fpsmax>
				  <refresh>25.0</refresh>
			  </override>
		  </adjustrefreshrate>
	  </video>
</advancedsettings>
```

3. Attempt to play a 23.976 FPS video.

### Debuglog

The debuglog can be found here (playback starts at about 09:23:18):
https://paste.kodi.tv/zezijenomo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 9.0.2
 - Kodi version: 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Please provide a logfile

**Comment by Avi0** [comment]
Report updated with the log file.

**Comment by Oibaf66** [comment]
I have the same issue with Kodi 18.4 running on a Mi Box 3

**Comment by Oibaf66** [comment]
If it can help, this my logfile:

https://paste.kodi.tv/filapahidu.kodi

**Comment by fuzzard** [comment]
Are any affected users able to test a build with https://github.com/xbmc/xbmc/pull/18442 to confirm if this resolves the issue or not?
Let me know what platform you use, and we may be able to create some test builds if needed.

**Comment by Avi0** [comment]
I can test it on Windows and on Linux on Raspberry Pi 4.

**Comment by fritsch** [comment]
I will trigger a new build for you, you can then download the windows build. One moment.

**Comment by fuzzard** [comment]
I'll start a windows build. https://jenkins.kodi.tv/view/Automation/job/BuildMulti-PR-Manually/374/

Look for PR18442 in the filename located at http://mirrors.kodi.tv/test-builds/windows/win64/

**Comment by fuzzard** [comment]
Build is now available http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20200927-8e846be9-PR18442-merge-x64.exe
let us know how it goes please

**Comment by fritsch** [comment]
Any results?

**Comment by Avi0** [comment]
I'm sorry I did not test it right away. Now I did and I confirm that the issue is resolved. Thank you!
