### ISSUE TITLE
Kodi 18.2 slow with subtitles on

### ISSUE THREAD

**Issue by kees100** [xbmc/xbmc#16283]
I upgraded my Kodi version 17,2 to 18.2 on Android 6.01 tv box
Everything looks to work fine.
Only when I select subtitles the video output shows glitches (Exodus redux). When turning off subtitles the video is smooth again.
It looks like the subtitles are taking to much resources. What can I do.
Never had this issue with Kodi 17.2

**Comment by enen92** [comment]
No support for piracy addons. Please read the rules.
