### ISSUE TITLE
App keeps crashing every time I open it.

### ISSUE THREAD

**Issue by TheKingSlayer-7** [xbmc/xbmc#16289]
### Describe the bug
Here is a clear and concise description of what the problem is:
The app keeps crashing every time I open it.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### Debuglog

The debuglog can be found here:

[kodi_crashlog-20190620_101030.log](https://github.com/xbmc/xbmc/files/3308854/kodi_crashlog-20190620_101030.log)

or this link (https://paste.kodi.tv/jomufukige.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating sysem version/name: Linux Manjaro
 - Kodi version: 18.2-3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
```
Thread 1 (Thread 0x7f8af8dbdac0 (LWP 3960)):
#0  0x00007f8af827d298 in ?? () from /usr/lib/libEGL_mesa.so.0
#1  0x00007f8af188775a in ?? () from /usr/lib/dri/nouveau_dri.so
#2  0x00007f8af188916c in ?? () from /usr/lib/dri/nouveau_dri.so
#3  0x00007f8af1cbdd2a in ?? () from /usr/lib/dri/nouveau_dri.so
#4  0x00007f8af1cbe035 in ?? () from /usr/lib/dri/nouveau_dri.so
#5  0x00007f8af1888b9d in ?? () from /usr/lib/dri/nouveau_dri.so
#6  0x00007f8af1883056 in ?? () from /usr/lib/dri/nouveau_dri.so
#7  0x00007f8af827bafd in ?? () from /usr/lib/libEGL_mesa.so.0
#8  0x00007f8af826a489 in eglMakeCurrent () from /usr/lib/libEGL_mesa.so.0
#9  0x00007f8afe7a86c1 in ?? () from /usr/lib/libEGL.so.1
#10 0x00007f8afe7a8780 in ?? () from /usr/lib/libEGL.so.1
#11 0x000055fefb6d3739 in CGLContextEGL::Refresh(bool, int, unsigned long, bool&) ()
#12 0x000055fefb6ddbe6 in CWinSystemX11GLContext::RefreshGLContext(bool) ()
#13 0x000055fefb6dde17 in CWinSystemX11GLContext::SetWindow(int, int, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*) ()
#14 0x000055fefb6d9638 in CWinSystemX11::SetFullScreen(bool, RESOLUTION_INFO&, bool) ()
#15 0x000055fefb6dd7e0 in CWinSystemX11GLContext::SetFullScreen(bool, RESOLUTION_INFO&, bool) ()
#16 0x000055fefb6da024 in CWinSystemX11::CreateNewWindow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, RESOLUTION_INFO&) ()
#17 0x000055fefb6dd682 in CWinSystemX11GLContext::CreateNewWindow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, RESOLUTION_INFO&) ()
#18 0x000055fefbda86aa in CApplication::CreateGUI() ()
#19 0x000055fefbaa1192 in XBMC_Run ()
#20 0x000055fefb4ace8b in main ()
```

Noveaou is not compatible with kodi and these crashes are as old as noveaou. Please file a bug with the mesa developers.
