### ISSUE TITLE
Playback slower in foreground than in background

### ISSUE THREAD

**Issue by dagwieers** [xbmc/xbmc#16299]
### Describe the bug
So when testing Kodi on an older 32-bit Intel computer running Windows 10, the playback of the video was sluggish and stuttering while it worked fluent and flawlessly when it was running in the background (i.e. a Kodi menu was on top and the playback was dimmed).

I tried it several times, even after rebooting. It was clear that the system was not able to handle normal playback (in foreground) but handled playback in the background without any issues.

Most likely this effect also happens for other systems, but goes unnoticed because the system can handle it in both cases, even though foreground playback is probably less efficient.

I don't know how to debug/troubleshoot this, or think of a cause for this.

This happened on my sister's desktop, so I don't have any logs and I cannot access it now, but maybe this can trigger someone who understand what's going on?

## Expected Behavior
I would have expected that background playback was as sluggish/stuttered as the frontend playback, but that was not the case. It was fluent and flawless.

## Actual Behavior
Sluggish/stuttered playback because the system was probably too old for normal playback, however playback was fluent, crisp and flawless when dimmed in the background.

## Possible Fix
I don't understand how dimmed playback in the background can be more efficient/better than foreground playback on an older 32-bit Windows system.

### To Reproduce
1. Take older hardware that seems to struggle with playback (possibly use higher resolution than what would work)
2. Go back to menu while playing
3. See it play more fluently/picture-perfect than when it was in foreground (it's really noticeable!)

### Debuglog
Debuglog will be provided when I visit that computer again, but likely reproducible on slower hardware elsewhere.

### Screenshots 
No screenshots, would probably have an impact anyway.

## Additional context or screenshots (if appropriate)
N/A

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows 10, 32-bit, 4GB memory
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 (1803)
 - Kodi version: 18.2

**Comment by DaVukovic** [comment]
We can't do anything without a debuglog. 

I could think of a refreshrate/whitelist problem. But that's only a guess. And guessing without a log is contra-productive. 

If you can't provide logs and if the issue can't be reproduced, then I guess thiss issue will either get closed soon or will not get any attraction. I would also suggest to seek for assistance at our forums. But we might need a log over there as well. But maybe there are others who could confirm and provide a log instead.

**Comment by DaVukovic** [comment]
No log 

Issue closed
