### ISSUE TITLE
Arabic Language

### ISSUE THREAD

**Issue by peylight** [xbmc/xbmc#16290]
### Describe the bug
In the Android 8.1 Kodi v18.2 I see only cubes as letters.

## Expected Behavior
I expect to see Arabic letters. not only cubes!

## Actual Behavior

When i choose Arabic keyboard or Language i see cube as letter!

### To Reproduce

1. Go to the settings
2. Change or add Arabic keyboard.
3. Use the Arabic keyboard to see cubes.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

[Click Here for screenshot](http://s4.picofile.com/file/8364172600/photo_2019_06_20_12_47_49.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Have you tried using an arial based font? 

![grafik](https://user-images.githubusercontent.com/7235787/59840803-67874e00-9353-11e9-9946-e77e1d4eddce.png)


![grafik](https://user-images.githubusercontent.com/7235787/59840849-81289580-9353-11e9-9bf0-a6ce1bb9ad0e.png)

**Comment by peylight** [comment]
It's Worked. Thanks.
However there are another issue that not related to this topic and already has been reported:
https://github.com/xbmc/xbmc/issues/16040

**Comment by DaVukovic** [comment]
Discuss the other issue at the specific section. 

Thanks
