### ISSUE TITLE
Add Persian Language Keyboard

### ISSUE THREAD

**Issue by peylight** [xbmc/xbmc#16291]
### Describe the bug
Here is a clear and concise description of what the problem is:

Please add Persian language keyboard.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When i want to choose keyboard, i like to see Persian Language.

## Actual Behavior

There are no Persian Language keyboard in the Keyboard list.

### To Reproduce

1. Go to the Settings.
2. Choose keyboard languages.
3. There are no Persian Language.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] Linux
 - [x] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@peylight 

The issues section is for bugs in Kodi, not for feature requests.

Please create your Feature Request on the forum here... https://forum.kodi.tv/forumdisplay.php?fid=9

Issue closed
