### ISSUE TITLE
[docs/linux] README.Linux.md binary addon installation instructions outdated/wrong

### ISSUE THREAD

**Issue by leezu** [xbmc/xbmc#16293]
### Describe the bug
The `README.Linux.md` describes an in-tree installation of binary addons (such as PVR addons). The in-tree installed addons are not recognized by Kodi, at least when following out-of-tree compilation of Kodi itself as instructed in the Readme. Thus the instructions in the Readme are wrong/misleading. Further out-of-tree install of the addons would be preferable over in-tree install, but is not described in the Readme.

## Expected Behavior
The Readme contains instructions that are simple and actually work.

## Actual Behavior
- Follow Step 1 - 6 of the Readme.Linux.md
- Kodi does not recognize that any binary addons were installed

## Possible Fix
Replace the broken Step 5 In-Tree addon installation instructions with working Out-of-Tree instructions. Alternatively fix the recognition of in-tree installed addons.

Exemplary out-of-tree instructions for the `platform`, `kodi-platform` and `pvr.iptvsimple` are below:

> the platform add-on, required to be able to build&install other add-ons:
> Code:
> 
> cd ~src/
> git clone https://github.com/Pulse-Eight/platform.git
> cd ~src/platform/
> cmake -DCMAKE_INSTALL_PREFIX=/usr/local
> make && make install
> 
> the kodi-platform add-on, required to be able to build&install other add-ons:
> Code:
> 
> cd ~src/
> git clone https://github.com/xbmc/kodi-platform.git
> cd ~src/kodi-platform/
> cmake -DCMAKE_INSTALL_PREFIX=/usr/local
> make && make install
> 
> the pvr.hts add-on, in case you want to connect to a TVheadend backend and watch TV:
> Code:
> 
> cd ~/src
> git clone https://github.com/kodi-pvr/pvr.iptvsimple.git
> cd ~/pvr.iptvsimple/
> cmake -DCMAKE_INSTALL_PREFIX=/usr/local
> make && make install

### To Reproduce
- Follow README.Linux.md Step 1-6

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
- This is a well known problem, that has made trouble for many users. See for example this thread on a linux forum: https://www.linuxquestions.org/questions/slackware-14/kodi-18-pvr-hts-tvheadend-4175647592/
- The instructions for out-of-tree build which I suggest should be incorporated into the README.Linux.md are taken from https://www.linuxquestions.org/questions/slackware-arm-108/kodi-leia-18-x-mediaplayer-optimized-for-raspberry-pi1-zero-pi2b-pi3b-on-slackware-arm-14-2-sf-and-slackware-arm-current-hf-4175647585/#post5957433

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian Buster (Debian 10)
 - Kodi version: 18.3

**Comment by leezu** [comment]
The ignored rules label seems to be in error.

**Comment by ronie** [comment]
perhaps it's because the libraries get installed in `/usr/local/lib/kodi/addons/` instead of `/usr/local/share/kodi/addons/`
```
[100%] Built target pvr.demo
make[6]: Leaving directory '/home/ronie/software/kodi/tools/depends/target/binary-addons/native/pvr.demo-prefix/src/pvr.demo-build'
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/kodi/addons/pvr.demo/pvr.demo.so.4.0.0
-- Installing: /usr/local/lib/kodi/addons/pvr.demo/pvr.demo.so.19.0
-- Installing: /usr/local/lib/kodi/addons/pvr.demo/pvr.demo.so
-- Installing: /usr/local/share/kodi/addons/pvr.demo
-- Installing: /usr/local/share/kodi/addons/pvr.demo/PVRDemoAddonSettings.xml
-- Installing: /usr/local/share/kodi/addons/pvr.demo/genre-numbers.txt
-- Installing: /usr/local/share/kodi/addons/pvr.demo/resources
-- Installing: /usr/local/share/kodi/addons/pvr.demo/resources/language
-- Installing: /usr/local/share/kodi/addons/pvr.demo/resources/language/resource.language.en_gb
-- Installing: /usr/local/share/kodi/addons/pvr.demo/resources/language/resource.language.en_gb/strings.po
-- Installing: /usr/local/share/kodi/addons/pvr.demo/data
-- Installing: /usr/local/share/kodi/addons/pvr.demo/data/06.png
-- Installing: /usr/local/share/kodi/addons/pvr.demo/data/07.png
-- Installing: /usr/local/share/kodi/addons/pvr.demo/data/11.png
-- Installing: /usr/local/share/kodi/addons/pvr.demo/data/04.png
-- Installing: /usr/local/share/kodi/addons/pvr.demo/data/01.png
-- Installing: /usr/local/share/kodi/addons/pvr.demo/data/02.png
-- Installing: /usr/local/share/kodi/addons/pvr.demo/data/03.png
-- Installing: /usr/local/share/kodi/addons/pvr.demo/data/05.png
-- Installing: /usr/local/share/kodi/addons/pvr.demo/data/10.png
-- Installing: /usr/local/share/kodi/addons/pvr.demo/data/08.png
-- Installing: /usr/local/share/kodi/addons/pvr.demo/data/09.png
-- Installing: /usr/local/share/kodi/addons/pvr.demo/README.md
-- Up-to-date: /usr/local/share/kodi/addons/pvr.demo
-- Installing: /usr/local/share/kodi/addons/pvr.demo/addon.xml
```



log snippet when trying to enable the addon:
```
2019-06-23 22:43:49.814 T:139912663406336   DEBUG: CBinaryAddonManager::EnableEvent: Enable addon 'pvr.demo' on binary addon manager
2019-06-23 22:43:49.817 T:139912010954496   DEBUG: ADDON: Dll Initializing - PVR Demo Client
2019-06-23 22:43:49.818 T:139912010954496   ERROR: ADDON: Could not locate pvr.demo.so.4.0.0
2019-06-23 22:43:49.818 T:139912010954496   ERROR: UpdateAddons: Failed to create add-on PVR Demo Client, status = 5
2019-06-23 22:43:49.822 T:139912010954496   DEBUG: CAddonMgr: pvr.demo disabled
```

**Comment by leezu** [comment]
What do you do to obtain "log snippet when trying to enable the addon"?
In my case, following the README.Linux.md instructions, the addon did not show up at all in the "Settings - Addons" interface; ie. I could not even try to enable it.
It only showed up when following the out-of-tree build described above.

**Comment by ronie** [comment]
ok, at my end at least the addon did get installed and showed up in kodi, i just couldn't enable it.

can you build 1 addon following the instructions in README.Linux.md and upload the output of step 5 to some pastebin site?

**Comment by wsnipex** [comment]
the problem is that mixing building kodi with system libs (or installing kodi from linux repositories) and building addons with our depends system doesn't work. The reason are different install paths.
Our depends system doesn't support multi-arch paths or setting libdir and datadir explicitly. I've looked into adding that in the past and it is non-trivial to do correctly without breaking other platforms.

So this is a valid issue and we should add the suggested documentation how to build addons "standalone"

@leezu do you want to send a PR?

**Comment by leezu** [comment]
@wsnipex can you clarify what you mean with "mixing building kodi with system libs"? How to build kodi without system libs (so that the current in-tree addon installation instructions would work)? Ie, what is the use-case where the current in-tree-build of addons applies?
Or should the current in-tree instructions be completely removed from the Readme and replaced by the "standalone" building instructions?

**Comment by wsnipex** [comment]
> @wsnipex can you clarify what you mean with "mixing building kodi with system libs"? How to build kodi without system libs (so that the current in-tree addon installation instructions would work)? Ie, what is the use-case where the current in-tree-build of addons applies?
Kodi uses it's own depends system for most platforms, where needed libraries are simply not easily available.
Those builds are cross-compiled. An example for linux is https://github.com/xbmc/xbmc/blob/master/docs/README.RaspberryPi.md
You can build kodi on x86 in the same way by using the correct --host and other relevant options.

> Or should the current in-tree instructions be completely removed from the Readme and replaced by the "standalone" building instructions?
I suggest adding a new section 5.1 in https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md#5-build-binary-add-ons that explains how to build binary addons out of tree
and move the current in-tree instructions to an alternative section 5.2.
We have to explain under which circumstances in-tree building is supposed to work:
- no multiarch libs dirs (.e.g. CMAKE_INSTALL_LIBDIR NOT set). This usually works with the default CMAKE_INSTALL_PREFIX=/usr/local

**Comment by leezu** [comment]
@wsnipex I opened https://github.com/xbmc/xbmc/pull/16304. Feel free to edit the PR (add more commits)
