### ISSUE TITLE
Kodi 18 zoom overlay missing scaling info (always 0)

### ISSUE THREAD

**Issue by sky42src** [xbmc/xbmc#16302]
### Describe the bug
The zoom overlay always shows (0,0)->(0,0) as scaling info

When you hit z one time you see the viewing mode and the the first line with information start with the scaling info, where the source and the scaled resolution is stated.
This is always 0 in Kodi 18 (also 18.3) on Linux or Windows.

## Expected Behavior

In Kodi 17 it was e.g. (1920x1080)->(3840x2160) for a bluray mkv playing on a 4k TV.

## Actual Behavior

It shows always (0,0)->(0,0)

## Possible Fix

I dont know.

### To Reproduce

1.  play any video and hit z shortly one time
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC, OSMC, Windows 10
 - Kodi version: 18.2 and 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
duplicate: #15952
