### ISSUE TITLE
Kodi Leia freezing on photo viewing with mixed content (jpg + mov)

### ISSUE THREAD

**Issue by BytEvil** [xbmc/xbmc#16309]
### Describe the bug
Kodi Leia (18.3) freezing on photo viewing with mixed content (jpg + mov).

### To Reproduce
1. Open folder with *. jpg and *.mov files. View photo, then play video, press back or forward to view next or previous photo. Kodi freezed totally.

### Backtrace

Backtrace can be found [here](https://pastebin.com/7Rf417U2).

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux
 - Kodi version: 18.3 (89472b7d)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Seems like a t duplicate: #16288 

At least it sounds pretty related.

**Comment by brjhaverkamp** [comment]
Not sure if it is related. The issue in #16288 is really only about the video playing but only showing a black screen. The audio is playing correctly and you can stop the video and restart it. There is no freezing at all.
