### ISSUE TITLE
avoid episode thumbs spoilers in home

### ISSUE THREAD

**Issue by bite-your-idols** [xbmc/xbmc#16306]
It would be nice to change order of "Recently added episodes" and "Unwatched shows" in home screen to avoid possible spoilers produced by seeing episode thumbs. Some years ago I posted it in estuary repo but I realized that the good place is here:
https://github.com/phil65/skin.estuary/pull/232#issuecomment-505429135

**Comment by DaVukovic** [comment]
It's possible to hide the thumbs completely

See: #14971

Anyway this is a feature request and not a bug report. Festure request should be placed at our forums at the specific subsection.
