### ISSUE TITLE
PVR crash when switching TV channels

### ISSUE THREAD

**Issue by Koumes** [xbmc/xbmc#16303]
### Describe the bug

Kodi crashes unexpectedly several times a day when switching TV channels.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Watching another channel by pressing the previous/next channel button.

## Actual Behavior

The image of the currently watched channel freezes and the Kodi restarts with crashlog.

### To Reproduce

1. go to TV, select TV Channel and watch TV full screen
2. press the "next" or "previous" channel button
3. repeat 2. until it crashes

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/jododifuru.kodi
https://paste.kodi.tv/ogiyiqigag.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: CoreELEC 9.0.1, CoreELEC 9.0.2, CoreELEC devel/nightly
 - Kodi version: Leia 18.2/18.3
 - PVR addon: Tvheadend HTSP Client 4.4.17.1/4.4.18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
This crash is already fixed in master: https://github.com/xbmc/xbmc/pull/16217 and obviously needs a backport.

**Comment by ksooo** [comment]
Will be fixed in 18.4 (if at all and whenever this will be released).

**Comment by Koumes** [comment]
Thank you very much. It works great.
