### ISSUE TITLE
onPlayBack* events seem to be broken from Python addons

### ISSUE THREAD

**Issue by MrDini123** [xbmc/xbmc#16301]
### Describe the bug
Here is a clear and concise description of what the problem is:

Since I would like to know when does the playback of my addon initiated hls stream stops (or the user stops it, doesn't matter), I followed the docs, subclassed the xbmc.Player but the callbacks still won't get called...

I have created an example addon to describe the situation: [[link]](https://github.com/MrDini123/PlaybackTestAddon/blob/master/plugin.video.playbacktest/default.py)

Then if I open this addon, only the addon started and the playback initialized one gets logged.

```
2019-06-24 23:46:09.645 T:16860 ERROR: Addon started!
2019-06-24 23:46:09.645 T:16860 ERROR: The Player has been initialized with the URL: http://distribution.bbb3d.renderfarming....normal.mp4
```

I thought maybe it's just not logged properly since it's from a callback so I also tried to make a request to my local webserver. The request never arrived.

Is i me being a noob and that's not how it works or it's broken for some reason?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

To have the callbacks actually called.

## Actual Behavior

Nothing happens.

### To Reproduce

1. I used Kodi Windows (18.2 (x64 version) and 17.6)
2. try the code linked below
3. check the kodi.log

### Debuglog

The debuglog can be found here:
```
2019-06-24 23:46:09.645 T:16860 ERROR: Addon started!
2019-06-24 23:46:09.645 T:16860 ERROR: The Player has been initialized with the URL: http://distribution.bbb3d.renderfarming....normal.mp4
```

(that's the only relevant part)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Rechi** [comment]
This is not a Kodi bug, but your example code is wrong.
After executing the play statement the add-on stops. As your add-on isn't running anymore there is no way Kodi can invoke a callback.
