### ISSUE TITLE
Kodi 18.3 Mac Crash on Boot

### ISSUE THREAD

**Issue by SoulTV** [xbmc/xbmc#16320]
#16254  Bug report
### Describe the bug

Kodi 18.3 crashes on startup. Mac Pro Xeon E5 4-core 3.7ghz 2013, Mac OS Mojave 10.14. I cannot get it to start even with a fresh install so I'm unable to turn on logging.

## Expected Behavior
Start into home sreen of Kodi

## Actual Behavior
Shows Kodi 18.3 splash, flickers once and crashes

## Possible Fix
Not sure, I tried a fresh install to no avail

### To Reproduce
1. Install Kodi on aforementioned hardware
2. Start Kodi
3. Kodi crashes

### Debuglog
Unable to get past splash to enable logging

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Mojave 10.14
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Post the crash log mscOS has produced.

**Comment by DaVukovic** [comment]
This one is over a month old without any further information. 

I'll close that for now. Happy to re-open it if the requested crash log has been provided
