### ISSUE TITLE
Channel Group not activated while using OFFICIAL Kodi parameter to do so. Verified multi platform issue.

### ISSUE THREAD

**Issue by kalynn3282** [xbmc/xbmc#16329]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have my main menu set as “TV”   
and then my sub menu buttons under it as “X Channels”, “Y Channels”, “Z Channels”. Etc.

On the submenu’s various button’s action/on-click/press command I have:  
Button X: “ActivateWindow(TVGuide,pvr://channels/tv/X Channels/)”  
Button Y: “ActivateWindow(TVGuide,pvr://channels/tv/Y Channels/)”  

And when I press any of them, it just opens the guide with no difference/change. 

(No errors, no log issues, it’s a brand new test install with no “evil” third party things)

(Kind of important as anyone who’s particular skins knows it’s almost impossible to click the “options->channel group” button in the corner as you can’t navigate to it while in the EPG without activation a mouse cursor, and the second a mouse cursor is activated it will essentially exit the EPG/Channel list anyways once it touches a button with a widget)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

According the the INTENDED BEHAVIOR of the official Kodi page, when calling  “ActivateWindow(TVGuide,pvr://channels/tv/X Channels/)”  the channel guide should load with only channels in the X channel group.

## Actual Behavior

Instead of calling channels in the X channel group, it just brings up the guide with no change at all and shows whatever channels were being viewed before.

## Possible Fix

The parameter of “pvr://channels/tv/X Channels/“ is being completely and totally IGNORED by Kodi, even though it has the functionality built in already, it’s almost like the call to add it to the instance of Activate Guide was never even written?

### To Reproduce

1. Setup a channel group on the PVR settings. Name the channel group whatever you want, we’ll call it “X Channels”
2. Activate Guide by assigning it to a menu button via “ActivateWindow(TVGuide)” and verify it works
3. Now, based on the OFFICIAL KODI documentation and Wiki Page, add the parameter for your new channel group we’ve created and change the button to: “ActivateWindow(TVGuide,pvr://channels/tv/X Channels/)”

And notice there are no changes to the group of channels when activating the button even though Kodi was designed to change the channels based on that parameter, has the functionality built in, and even advertises that it IS a function that SHOULD work.

### Debuglog

The debuglog can be found here:

N/A No warnings or errors present in log. See above.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 7 and 10 (verified not working on both, but likely on ALL Kodi Platforms)
 - Kodi version: 17.6 with Simple Client

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Please update to the latest stable version. Kodi 17.6 won't receive any fixes anymore.

And please provide a debuglog after you installed Kodi 18 if the issue still exists, thanks

**Comment by kalynn3282** [comment]
Will do a portable install of 18, follow the same steps, and post log (as I’m sure this issue is widespread through all versions/platforms/etc. and a fix for one can be patched into others, even if it has to be done by the users. 

Will post an update shortly with log.

**Comment by asavah** [comment]
This has been discussed at https://forum.kodi.tv/showthread.php?tid=344930

**Comment by DaVukovic** [comment]
Thanks for the link. By reading the comments on that thread and especially what @ksooo said:
> The guide window currently does not handle any parameters on open

I would say this is more a feature request rather than a bug report. 

@kalynn3282 Feature request need to be done at the forums at its specific subsection: https://forum.kodi.tv/forumdisplay.php?fid=9

I'm going to close this one as a missing feature can be somewhat related for a report being a bug, but not in this case.

**Comment by ksooo** [comment]
Maybe someone can correct the wiki?

**Comment by kalynn3282** [comment]
Why would you want to “correct the wiki” for a simple advertised issue?

If I say, “the program will play tv channels” and it doesn’t, then that’s an issue. Even if there’s no errors being thrown, it’s supposed to do that. Whether someone writes the wrong line of code of forgets to write it is no difference. Kodi was supposed to do just that by design, was advertised to do that by design, and regardless of WHY it’s not maintaining a simple function is not the point, the fact is it IS an oversight that needs correction.

**Comment by ksooo** [comment]
The wiki should reflect the current state because it is  OFFICIAL, to put it with your words. Otherwise random demanding and rude guys show up and claim everything in the wiki is the truth and developers HAVE to implement everything to match the wiki content. But it is vice versa - the wiki is written by volunteers after the implementation not the other way around.

Kodi PVR windows are currently NOT designed to support parameters. Whoever wrote the wiki page has not checked that it actually works. So, we are facing a documentation bug, not a code bug. Period.

As I already told you in the forum, the more demanding or rude you are presenting yourself here the lower are your chances that somebody will step up and implement what you're missing.

**Comment by ksooo** [comment]
> If I say, “the program will play tv channels” and it doesn’t, then that’s an issue. 

 sure, but we're not talking about not being able to play channels here.

> Kodi was supposed to do just that by design, was advertised to do that by design, 

 Oh, then you know more the I and I'm one of the designers of Kodi PVR. And if your source is the wiki, I can only repeat that the code is the truth, not the wiki as wiki follows  the code, not vice  versa.

> and regardless of WHY it’s not maintaining a simple function is not the point, the fact is it IS an oversight that needs correction.

 I tend to agree, but as long as you don't change your attitude there are good chances that this will  NOT happen anytime soon.

**Comment by kalynn3282** [comment]
Wow, never mind then, I went to a couple freelancer/code hire websites earlier today and less than an hour I have a bid from twelve different coders, all coming in for under three figures that are all quoting me less than two days to delivery/completion INCLUDING THE REBUILD.

So much for the “official” developers standing behind their work I suppose. Asking for an explicitly stated feature to properly function is NOT a feature request, it IS an issue. Again, whether it’s broken or never written, no one could care less WHY it doesn’t work, it simply doesn’t work.

And those are facts, not attitudes. Advertising a function on an official documentation and not delivering that function for YEARS after those statements were written is disgusting (now THAT’S an attitude), but simply saying it’s an oversight? No, if it wasn’t a fact then there wouldn’t be a discrepancy between what the “Kodi team” says their product can do and what it actually does.

Saying “it’s not an issue, it’s a FEATURE REQUEST” is NOT applicable when the feature has been advertised for SEVERAL VERSIONS now. No “deleting the wiki” will change that fact. Yes it’s annoying, but what would make it go away is simply have saying “oh, it looks like this happened, we’ll put it on our scrum list so even if we don’t get to it soon, at least it’s eventually going to be fixed”

Don’t want to do something? That’s fine, it’s a free open source product, (ignore it even though on google and the Kodi forums are endless amounts of requests saying “it doesn’t work”.) but don’t try and call it something that it isn’t like “oh it’s really a feature request, we didn’t forget it or screw up or advertise it when we really weren’t going to do it ever” just to try and save face.

Do you know WHY they were saying that/complaining/asking for help? Because it was TOLD to them by Kodi that it WOULD work and they do all the steps instructed to them, and because the software constantly has bugs even with no other addons integrated to it, of course people will assume it’s a bug. 

But even if it wasn’t a bug, it is still by definition an ISSUE. Trying to say it’s a request indicates it’s something someone wants that is new. This is something that SHOULD HAVE been around for years apparently based on all the people having issues trying to get it to work when apparently no one even bothered to write any part of it. 

And I will NOT be contributing whatever script, or addon they give me to fix the issue until this place takes their own functionality seriously and doesn’t brush it off to the side, BUT I’ll happily post up an executable just to simply prove that it can be done in a couple days time, though imagine what could’ve been done or the possible features it could have had if the actual developers who make the platform and say it can be done had done it?

We’ll see what the two reddit subs think when I recap the situation, show them it’s been complained about and ignored for YEARS apparently yet left advertised (and archived in case deleted out of laziness), the unnecessary back and forth instead of a simple “oh, it’s not there? We’ll get to it”, and post a new version that actually HAS that functionality.

Thank you?

**Comment by ksooo** [comment]
Don't you get that Kodi is a hobby project where all work is done by volunteers after their day job, not something a company is developing with paid developers?

**Comment by MartijnKaijser** [comment]
@kalynn3282 then those coders are obsolete morons. Setting up the complete build environment, finding out the correct part of the code to change, QA testing, compiling, complying to the GPL license and delivering a completed build for the customer (that's your whining little self in this case) takes well over couple of hours. So if you say below three figures then that means they are dirty cheap or have absolutely no comprehension of the coding and financial system that's around in the world.
Now change your attitude or leave.

**Comment by arnova** [comment]
@kalynn3282 : And you paid how much $$$$ for Kodi exactly? Right.....
