### ISSUE TITLE
Use utf8mb4_general_ci instead of utf8_general_ci in MySql/MariaDB

### ISSUE THREAD

**Issue by moeppe** [xbmc/xbmc#16328]
### Describe the bug
Some UTF characters are not stored in the MySQL database, e.g. if file names contains some special characters like emoticons. utf8_ charsets can contain only 3-byte-characters (design flaw in MySQL).

## Possible Fix
Use utf8mb4_general_ci as default collation and charset for MySQL.

**Comment by DaVukovic** [comment]
@moeppe 

Could you please mention a movie which might have those characters.

**Comment by moeppe** [comment]
It's not really about titles (they might exist). I detected it while using emojis in folder names of my music folder.

**Comment by a1rwulf** [comment]
> It's not really about titles (they might exist). I detected it while using emojis in folder names of my music folder. The character is e.g.

Why would you do that?

**Comment by DaVukovic** [comment]
Ok, I guess we can easily close this. There's really no need to have emoticons in filesnames. 

If there's any real usecase for that, then I'll happily re-open this issue.

**Comment by kalaksi** [comment]
@DaVukovic soo... could you reopen this?

**Comment by jmbannon** [comment]
Ran into this issue when trying to display YouTube videos in Kodi as a TV show. Many videos have emojis in them that should be able to be used in a Kodi title.

**Comment by jmbannon** [comment]
Not stale

**Comment by mintsoft** [comment]
I am pretty sure that https://www.themoviedb.org/tv/126308-shogun trips over this issue. When scanning it errors with `SQL: [xbmc_video131] Undefined MySQL error: Code (1267)` (if the query is executed manually it will show `ERROR 1267 (HY000): Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb3_general_ci,COERCIBLE) for operation '='`)
