### ISSUE TITLE
Changes in (future) libbluray 1.2.0 require these changes in Kodi (if you want to use them)

### ISSUE THREAD

**Issue by MistahLu** [xbmc/xbmc#16331]
This is not a bug report. Just a reminder (well ahead of time).
Current versions of libbluray has a few issues that will get fixed in v1.2.0, which require apps to adapt:

Currently, when you press a key, KEY_PRESSED **and** KEY_RELEASED is both called. This is of course wrong. KEY_RELEASED should only be called when the key is actually released.
This will be fixed in libbluray 1.2.0 by adding a new function; bd_input_flag()
The old function (bd_input()) will still be available though. So in order to use this new function, it needs to be changed in Kodi too.

Currently, there is no mouse-support in libbluray. This will also be added in v1.2.0
Kodi should adapt and add this too.

**Comment by DaVukovic** [comment]
https://forum.kodi.tv/forumdisplay.php?fid=9

or create a PR

**Comment by enen92** [comment]
I'd prefer to keep this open and changed to a roadmap ticket instead of burying it in the pile of closed issues. Libbluray will be updated at some point in the future I guess. Opinions?

**Comment by MilhouseVH** [comment]
Just as background, this is the upstream PR: https://code.videolan.org/videolan/libbluray/issues/8

**Comment by fuzzard** [comment]
Just some notes around this.

The implementation that was merged into libbluray is an optional implementation. ie, it can optionally continue to use the existing way (keypress/keyrelease are sent as the 1 stroke) or you can mask you're key with the 3 states (KEY_PRESSED, KEY_RELEASED, KEY_TYPED)

Commit that was merged with the optional change.

https://code.videolan.org/videolan/libbluray/commit/4d45011536b3288cd822983411b6d50b0a223ba9

I dont believe this stops us from bumping to libbluray 1.2.0, as it will continue as the existing method without the ORing of the flags.
