### ISSUE TITLE
Kodi 18.3 does not compile on Fedora 30 due to rpc.h issues

### ISSUE THREAD

**Issue by wfriesn1** [xbmc/xbmc#16333]
### Describe the bug
Here is a clear and concise description of what the problem is:

In Kodi 18.3 NFSDirectory and NFSFile need rpc.h.  Conventional rpc.h is no longer provided in Fedora 30 and has been replaced with libtirpc.  As a result the build fails with an error related to not finding rpc.h. 

In Fedora  (https://fedoraproject.org/wiki/Changes/SunRPCRemoval) - libc bundles an implementation of Sun RPC (including XDR support, on which Sun RPC is based). This implementation is not compatible with IPv6, and due to the way addresses are represented, adding IPv6 support would need an ABI bump. As a result, upstream decided to move Sun RPC support to a separate library, libtirpc, which has been packaged since Fedora 7.  This started around Fedora 28. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The build should detect that the system supports RPC using libtirpc and use it's headers and libraries.

## Actual Behavior

The build is attempting to use the legacy location for the rpc.h header and link to glibc.

## Possible Fix

tactical solution....
manually add "/usr/include/tirpc" to include_directories list in CMakeLists.txt

### To Reproduce

1.  Current Fedora 30 build and updates as of June 30, 2019
2.  Kodi 18.3 from GitHub
3. Build as per linux build guide

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedoia 30
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by wsnipex** [comment]
please provide a build log showing the issue.

**Comment by wfriesn1** [comment]
Discovered I was missing a dependency libnfs-devel.  Once that was installed the compile completed successfully.  
[CMakeError.log](https://github.com/xbmc/xbmc/files/3348164/CMakeError.log)
[CMakeOutput.log](https://github.com/xbmc/xbmc/files/3348165/CMakeOutput.log)

**Comment by wfriesn1** [comment]
Was seeing the error due to a missing dependency.  Completed build successfully. Closing this case.
