### ISSUE TITLE
kodi alone doesn't show texts

### ISSUE THREAD

**Issue by yurivict** [xbmc/xbmc#16350]
I installed the kodi package into the FreeBSD jail. UI is displayed, but there are no texts at all.

Apparently, it depends on some fonts that happen to be installed for other software, but kodi package itself doesn't depend on fonts, and they aren't installed.

What is kodi's fonts requirement? What fonts are needed?

Arch linux kodi package doesn't install any fonts either: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kodi-devel

kodi-17.6

**Comment by wsnipex** [comment]
any fonts that fontconfig handles should work.
E.g. We require https://github.com/liberationfonts and https://dejavu-fonts.github.io/ for our ubuntu packages

**Comment by yurivict** [comment]
I added ```liberation-fonts-ttf``` and ```dejavu``` packages, but this made no difference.

**Comment by yurivict** [comment]
ping.

Any idea how to solve this? Which fonts to add to the kodi container to make kodi work?

You should define a set of fonts that are required, make sure they are installed and usable when kodi starts, and fail if they aren't installed.

Otherwise kodi would look broken on some systems due to missing fonts.

**Comment by bsdlme** [comment]
Maybe you can start kodi with truss or ktrace and see which font files are getting opened.

**Comment by yurivict** [comment]
```ktrace``` shows that the only font files it opens are installed by kodi itself:
```
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Regular.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Regular.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Regular.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Regular.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Regular.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Regular.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Regular.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Regular.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/Roboto-Thin.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Bold.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Bold.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Bold.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Bold.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Bold.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Bold.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Bold.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Bold.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Bold.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoSans-Bold.ttf" -> 35/0x23 (  )
openat  "/usr/local/share/kodi/addons/skin.estuary/fonts/NotoMono-Regular.ttf" -> 35/0x23 (  )
```

**Comment by DaVukovic** [comment]
Template ignored, no logfile provided and in the end I would rather suggest to seek for assistance at our forums. This section is for bug reports only and not for answering questions. 

Please don't take this as an offense.
