### ISSUE TITLE
error: undefined reference to 'pthread_atfork'

### ISSUE THREAD

**Issue by nephaste** [xbmc/xbmc#16354]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hi Kodi Team,

i used to build Kodi from source.. but with Kodi 18.3 from git release

build remain this error when linking kodi-x11

`[100%] Linking CXX executable kodi-x11
/usr/local/lib/libcrypto.a(threads_pthread.o):threads_pthread.c:function fork_once_func: error: undefined reference to 'pthread_atfork'
collect2: error: ld returned 1 exit status
CMakeFiles/kodi.dir/build.make:526: recipe for target 'kodi-x11' failed
make[2]: *** [kodi-x11] Error 1
CMakeFiles/Makefile2:1590: recipe for target 'CMakeFiles/kodi.dir/all' failed
make[1]: *** [CMakeFiles/kodi.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
`
OS is Ubuntu 1804
GCC  7.4.0
cmake version 3.10.2
OpenSSL 1.1.1

command issue 

`mkdir build && cd build

cmake ../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=/opt/Kodi18  -DENABLE_INTERNAL_FMT=ON -DENABLE_INTERNAL_CROSSGUID=ON -DENABLE_INTERNAL_RapidJSON=ON

make -j$(nproc) && make install`

all was compiling fine with 18.2 ... i dont understand how can i link this libs ? think about a -lpthread is missing somewhere in code... but not sure

## Expected Behavior

fixed linking issue

## Actual Behavior

crash on linking pthread

## Possible Fix

no idea

### To Reproduce

1. ubuntu 1804
2. pickup release for git (wget)
3. see upper

### Debuglog

The debuglog can be found here:

[CMakeCache.txt](https://github.com/xbmc/xbmc/files/3362479/CMakeCache.txt)
[CMakeError.log](https://github.com/xbmc/xbmc/files/3362480/CMakeError.log)
[CMakeOutput.log](https://github.com/xbmc/xbmc/files/3362481/CMakeOutput.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

thanks for your help....

**Comment by nephaste** [comment]
fixed template rules  ^^ sorry

**Comment by wsnipex** [comment]
get rid of your custom openssl in /usr/local/ and try again

**Comment by nephaste** [comment]
was orignally 1.1.0.g ... but was failing
just did an apt upgrade for my distro and it self upgraded it into 1.1.1 but failed too with same error

not other solution than removing it  ?   can impact Kodi... i think  

no flag can be passed to cmake ? kind of LIBS="-lpthread" (if it was autoconf )

**Comment by wsnipex** [comment]
All I can tell you is that kodi compiles fine on ubuntu 18.04 when following the docs.

**Comment by nephaste** [comment]
very strange... i will recreate my LXC bionic and follow it again... tell you that in few hours

**Comment by nephaste** [comment]
you were right... dont understand what happened to my previous LXC bionic

thanks
