### ISSUE TITLE
3D subtitle bug on Raspberry Pi

### ISSUE THREAD

**Issue by Shasarak** [xbmc/xbmc#16362]
### Describe the bug
Here is a clear and concise description of what the problem is:

Distortion of subtitles when playing a 3D video on Raspberry Pi. Some subtitles display okay, but others are displayed horizontally stretched, so up to half of the text is off the screen. I *think* it affects image-based subtitle formats (e.g. PGS) but not text-based (e.g. SRT) - but I'm not certain of that. It's quite easy to reproduce. I've seen this under both OSMC and LibreELEC.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Subtitles work correctly!

## Actual Behavior

Some subtitles are displayed horizontally stretched.

## Possible Fix

No idea.

### To Reproduce

I've created a short sample video that reproduces the problem reliably. It's about 90MB in size.

Download from https://www.dropbox.com/s/z8r69svwxs6mk2q/Gravity.extract.3d.mkv?dl=0

### Debuglog

The debuglog can be found here: https://paste.osmc.tv/vixehejawe

### Screenshots 
Here are some links or screenshots to help explain the problem:

See attached photo.

### Your Environment
Used Operating system: OSMC (but issue also occurs with LibreELEC)

Running on a Raspberry Pi 3B+.
 - Kodi version: 18.3

![gravity screenshot](https://user-images.githubusercontent.com/43468346/60899769-f6a4c900-a262-11e9-9757-79156dc6036a.jpg)

**Comment by mkreisl** [comment]
FYI: this problem occurs in all Kodi versions

**Comment by TheMontezuma** [comment]
FYI - similar ticket:
https://github.com/xbmc/xbmc/pull/17317

Please fix this issue

**Comment by TheMontezuma** [comment]
I created a RPI2/RPI3 [image](https://github.com/TheMontezuma/LibreELEC.tv/releases/tag/9.2.6_MVCSUBFIX) with a fixed "3D subtitle bug". The bug fix is applied directly on top of 9.2.6 LibreELEC.
I still hope, the bug fix will find it's way to the KODI repository...

**Comment by DaVukovic** [comment]
@popcornmix ^^

Ist that something for you?

**Comment by popcornmix** [comment]
No fixes for kodi 18 and 3d isn't supported with gbm on kodi 19.

**Comment by TheMontezuma** [comment]
> 
> 
> No fixes for kodi 18 and 3d isn't supported with gbm on kodi 19.

I understand "No fixes for kodi 18", but what do you mean with "3d isn't supported with gbm on kodi 19" ?

Not supported right now or you are not even going to support 3D in future ?

**Comment by popcornmix** [comment]
No current support.

**Comment by mkreisl** [comment]
Will there ever be support for 3D again or will they continue to work diligently to break Kodi?

**Comment by TheMontezuma** [comment]
> 
> 
> Will there ever be support for 3D again or will they continue to work diligently to break Kodi?

3D support is still there for RPI3 variant. RPI4 is very different than RPI3 and lacking 3D support is not a KODI issue.

**Comment by enen92** [comment]
Fixed by https://github.com/xbmc/xbmc/pull/17317
