### ISSUE TITLE
[Feature Request] Allow Tags to be assigned for Media Sources

### ISSUE THREAD

**Issue by Philps** [xbmc/xbmc#16366]
It would be great if you could assign Tags during initial scrobbling for media sources.

For Example:
- i could assign a tag "local" for media sources which are on my local harddrive
- i could assign "cloud" for medias in the cloud
- i could assign "nas" for medias on NAS Devices

So instead of me assigning Tags to each Media Stream manually, i like to add a generic Tag for the Source of the media Stream.

**Comment by DaVukovic** [comment]
This section is for bugs/issues and not for feature requests. 

Please open a thread here: https://forum.kodi.tv/forumdisplay.php?fid=9

Thanks
