### ISSUE TITLE
Amazon Fire TV 4K - NFS/SMB issues

### ISSUE THREAD

**Issue by fegauthier** [xbmc/xbmc#16376]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a movie folder in my NAS. I use Kodi NFS or SMB feature to add this folder as a movie source. The NAS is in my local network. When I add a movie that the bitrate is more than 8000kbps, I expected many buffering issue. Under 8000kbps everything is fine. So I can forget some 1080p movies or 4K movies. NFS or SMB, the result is the same. I use Kodi on my Fire TV 4K. 

I tried Kodi on Windows to see if the problems still there. I add a NFS/SMB source via Kodi. The problem is the same. There is buffering on video that are more than 8000kbps. I tried to add a mapped drive network share directly with Windows. Every thing is fine when the NAS is mounted by Windows instead of Kodi.

I think the library that Kodi use for SMB/Kodi has some issue.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Normally, I would not expect buffering.

## Actual Behavior

Every movie that bitrate is over 8000kbps buffered every 10 seconds...

## Possible Fix

Maybe update the NFS/SMB library that Kodi use because if the share is mounted directly from Windows, it's working.

### To Reproduce

1. Put a movie that the birate is 20000kbps in a folder on your NAS
2. In Kodi, use NFS/SMB to add the movie.
3. Play this movie. You should expect buffering.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Leia 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Please provide 2 debuglogs

- one which shows Kodi is buffering
- one which shows the normal playback

Btw:

Bit rate                                 : 13.3 Mb/s

That's the bitrate of one of my rips which has zero problems playing on Windows/Linux using a wired connection and adding the sources via Kodi (SMB or NFS)

If we are talking about a wireless connection in your case, then I would also take a look at: 

https://kodi.wiki/view/HOW-TO:Modify_the_video_cache

But provide the logs first

thanks
