### ISSUE TITLE
Kodi Not running after installation

### ISSUE THREAD

**Issue by strike4295** [xbmc/xbmc#16379]
### Describe the bug The Kodi program successfully installs, then gives me an error when trying to run it. Asking me to redownload. I have redownloaded at least 10 times with still not resolution.
Here is a clear and concise description of what the problem is:
 Because I have downloaded it multiple times to try and correct the issue and it's still not working. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Way too many info missing. 

Please do not ignore the issue template and at least mention the OS in use. 

Anyway, I guess the forums might be a better place for those kind of questions.

**Comment by KarellenX** [comment]
@strike4295 

If no response is made to the post by @DaVukovic above this issue will be closed in 24 hours
