### ISSUE TITLE
TV show listing does not show season+episode

### ISSUE THREAD

**Issue by dagwieers** [xbmc/xbmc#16371]
### Describe the bug
If you open a TV show from a local directory of episodes *ordered by Episode*, the episodes are listed as:

>    - 1x05. Katrien onderzoekt Buck in het ziekenhuis

If you open the same listing from an addon (online content) *ordered by Name* the episodes are listed as:

>    - Katrien onderzoekt Buck in het ziekenhuis                                       15:00

And if you would use *ordered by Episode* they are listed as:

>    - &#48;5. Katrien onderzoekt Buck in het ziekenhuis

## Expected Behavior
I would like to see the same thing for online content, if you *order by Episode* it should be showing also the season and the duration:

>    - 1x05. Katrien onderzoekt Buck in het ziekenhuis                                       15:00

*(The duration would just be optional, probably a feature request, rather than a bug)*

## Actual Behavior
If you would use *ordered by Episode* they are listed as:

>    - &#48;5. Katrien onderzoekt Buck in het ziekenhuis

## Possible Fix
Including the season helps with multi-season views, where now they are listed as:

>    - &#48;1. Aflevering 1
>    - &#48;2. Aflevering 2
>    ...
>    - &#49;0. Aflevering 10
>    - &#48;1. Aflevering 1
>    - &#48;2. Aflevering 2

This would look a lot better using 1x10. and 2x01.

### To Reproduce
1. Use an addon showing TV shows (e.g. VRT NU)
2. Browse to a show with multiple seasons (e.g. Sedes en Belli)
3. See the order being correct, but the numbering incomplete

### Debuglog
Not relevant

### Screenshots 
![screenshot011](https://user-images.githubusercontent.com/388198/61128960-a2dcee80-a4b3-11e9-8664-6994fbd8b2ae.png)

### Your Environment
Used Operating system (is irrelevant):
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 9.0.2
 - Kodi version: 18.2

**Comment by DaVukovic** [comment]
Talked to our add-on devs and this is not a Kodi core issue if the source doesn't provide the season or episode numbers. So this depends on the add-on in use and on the source the add-on fetches the data from. 

Nothing which can be solved by Kodi core.

**Comment by dagwieers** [comment]
We do provide the season _and_ episode, but only the episode is being shown. If you go to the episode information at the top both season and episode is shown. You closed this prematurely IMO.

**Comment by DaVukovic** [comment]
Might be, I'll let @enen92 comment on that.

**Comment by HitcherUK** [comment]
When I order my local episodes by 'Name' I only see the name of the episode and not the SxEE.

**Comment by dagwieers** [comment]
@HitcherUK You are correct, this is about **Sort by Episode** only. Let me correct my description.

**Comment by HitcherUK** [comment]
It must be something in the core code because all a skin is using is `ListItem.Label` and Kodi does the rest depending on sort order. I'm afraid I can't help with that though.

**Comment by dagwieers** [comment]
Going over the code I think I found the reason for this. From the **LabelFormatter** you can tell that `%E` only shows the episode (or at least not the `1x01` format.
https://github.com/xbmc/xbmc/blob/0420094ed11f68d8e7d5f4739c51afea7204be9e/xbmc/utils/LabelFormatter.cpp#L263-L271
 and `%H` shows the season+episode (including the `1x01` format:
https://github.com/xbmc/xbmc/blob/0420094ed11f68d8e7d5f4739c51afea7204be9e/xbmc/utils/LabelFormatter.cpp#L276-L284

Now if we look at what is used for plugin directories, you can see it exclusively uses `%E`:
https://github.com/xbmc/xbmc/blob/0420094ed11f68d8e7d5f4739c51afea7204be9e/xbmc/filesystem/PluginDirectory.cpp#L389-L393

And what is used for Episode listings in general in code (where sort methods are pre-stuffed in that view), it uses `%H` for those listings:
https://github.com/xbmc/xbmc/blob/0420094ed11f68d8e7d5f4739c51afea7204be9e/xbmc/video/GUIViewStateVideo.cpp#L541-L566

*Notice the fact that the first part is disabled, and the second part is activated.*

**Comment by HitcherUK** [comment]
@dagwieers Want to try changing it and see what happens?

**Comment by dagwieers** [comment]
@HitcherUK If I easily could, I would.

**Comment by HitcherUK** [comment]
I'll see what I can do.

**Comment by HitcherUK** [comment]
This build seems to work correct -

http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20190716-4db0f3cc-video_addon_season_episode_formatting_fix-x64.exe

@dagwieers can you please test?

**Comment by bigretromike** [comment]
Could this be releted to https://github.com/xbmc/xbmc/issues/14573 ?

**Comment by HitcherUK** [comment]
> Could this be releted to #14573 ?

In what way? This is a fix for season/episode labels.

**Comment by bigretromike** [comment]
> > Could this be releted to #14573 ?
> 
> In what way? This is a fix for season/episode labels.

It was a sorting/label issue, and was hoping this could be related and fix together.

**Comment by dagwieers** [comment]
@DaVukovic @HitcherUK I tried a recent build and it was fixed. Thanks a lot !

cc @mediaminister
