### ISSUE TITLE
Amazon FireTV - 18.3 - Intermittent freezing after video ends 

### ISSUE THREAD

**Issue by Gentatsu** [xbmc/xbmc#16375]
### Describe the bug
Here is a clear and concise description of what the problem is:

Intermittently, after a video ends, Kodi will stay on a black screen, and stay like that until I force close it. This is only observable on releases on 18. When I had 17, this did not happen. Seems to be no correlation between length of the video, or other factors. 

Only happens when the video gets to the very end. I do not --think-- it happens when I stop playback.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video should end, and goes back to the library

## Actual Behavior

Screen goes to black, kodi debug log view in corner also freezes. 
Watched status is recorded in sql db, and persists when going back to video. 

### To Reproduce

Took me a long time to reproduce, as it's annoying having the debug log text on the screen most of the time, so I had it up when I was watching stuff in background.
1. Watch video until end
2.
3.

### Debuglog

The debuglog can be found here:
http://paste.kodi.tv/ululazovod

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android - Amazon Fire TV 2
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Gentatsu** [comment]
Which bit is ignored, so I can fix?

**Comment by DaVukovic** [comment]
It's fine after you edited the inital report and added a debuglog

**Comment by Gentatsu** [comment]
Still persistent in 18.4.

**Comment by Gentatsu** [comment]
Happening more often in 18.4. Even if I stop playback prior to the video ending, it will do it often now.

**Comment by liquidblasted** [comment]
Exactly the same problem on Sony Bravia TV after updating to Android 7->8 and Kodi 18.1->18.5

**Comment by fritsch** [comment]
Nice. Does your debuglog look exactly like his as well?

**Comment by liquidblasted** [comment]
@fritsch I can't see debuglog attached here anymore, but I'll try to attach my own log next time I'll catch this bug

**Comment by liquidblasted** [comment]
@fritsch Just catch it again, here is my log: http://paste.kodi.tv/ojifekobak.kodi

**Comment by fritsch** [comment]
Thanks. Sadly this was not a debuglog. Btw. if you have an adb logcat that would be very helpful as well.

**Comment by Gentatsu** [comment]
I'll try and generate another debuglog. Essentially it simply stops logging anything until it's restarted. Also persistent in 18.5.

**Comment by Gentatsu** [comment]
Still in 18.8. Observed more often, tbh.

**Comment by Gentatsu** [comment]
Uh, is this complete? Can you pop the PR that addresses this issue?

**Comment by thexai** [comment]
No, it is not complete but completely obsolete : )

What we are interested in knowing is if it continues to happen with v20 alpha2 since v18.8 will not receive any more updates.
