### ISSUE TITLE
v18.3 forgets all library items

### ISSUE THREAD

**Issue by johnicon1** [xbmc/xbmc#16372]
### Describe the bug
Here is a clear and concise description of what the problem is:
After setting content for a movie or TV show directory on an external hard drive and downloading metadata and then restarting Kodi 18.3, I get the message: "Item not available, would you like to remove it from the library?" for every single item that had been added.  Kodi 18.3 effectively forgets every item in the library between reboots.  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Kodi 18.3 should retain it's database between restarts

## Actual Behavior

All library items in the database are missing after every restart.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Since I had been using Kodi since Krypton, I assumed that the update to 18.3 may have broken something.  So, I cleaned the libraries, uninstalled 18.3, powered-down, restarted and then reinstalled 18.3 and Set Content for all items.  No change in behavior, Kodi still forgets all of the movies and TV show episodes after every restart.

### Your Environment
Used Operating system:

Android 8.0 on a Sony XBR65X850E TV.

 - Operating system version/name:
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HitcherUK** [comment]
Sounds like the HDD isn't being recognised after a reboot but without a debug log we can only guess.

**Comment by DaVukovic** [comment]
Or the drive is recognized but has a different path.

Anyway we need the log. I'll set the "ignored rules" label for the time being.

**Comment by johnicon1** [comment]
You're right, it looks like my TV is continuously recognizing my USB drive as a new drive with every restart.

Thanks for the suggestion and sorry for wasting your time with a non-Kodi issue.
