### ISSUE TITLE
EPG is not listed

### ISSUE THREAD

**Issue by Durlyn** [xbmc/xbmc#16386]
## Describe the bug
after the commit ca5caa7d56178dc371816448d343cb40f09f988c, the information of the EPG is no longer displayed. If i disable the addon pvh.hts, clear the data on the channels and EPG and turn on the addon, then EPG will be shown. After rebooting the Kodi, everything will be empty.

HTS Tvheadend 4.3-1801~g8f1de1621
pvr.hts - last version from git

### Debuglog

The debuglog can be found here:
2019-07-19 22:43:00.961 T:140175476762368   ERROR: Deliver: Unable to obtain EPG for client 2025648334 and channel 1891931487! Unable to deliver state change for tag '67656903'!

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora 30, kernel 5.1.17-300
 - Kodi version:last master from git

**Comment by Durlyn** [comment]
## Bug report
### Describe the bug
Here is a clear and concise description of what the problem is:
after the commit ca5caa7, the information of the EPG is no longer displayed. If i disable the addon pvh.hts, clear the data on the channels and EPG and turn on the addon, then EPG will be shown. After rebooting the Kodi, everything will be empty.

HTS Tvheadend 4.3-1801~g8f1de1621
pvr.hts - last version from git

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
In the list of channels was supposed to be EPG information

## Actual Behavior
only channel list, without EPG

## Possible Fix
if you roll back to the previous commit, everything works correctly

### To Reproduce
Steps to reproduce the behavior:
1.In git go to commit ca5caa7
2. compile Kodi from source
3. install and reboot
4. EGP gone

### Debuglog
The debuglog can be found here:
https://pastebin.com/AULLZDsw


### Screenshots 
Here are some links or screenshots to help explain the problem:


## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:


### Your Environment
Used Operating system:


 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora 30, kernel 5.1.17-300
 - Kodi version: master from git

**Comment by ksooo** [comment]
Definitely unrelated to the mentioned commit.

> 2019-07-19 22:39:09.882 T:140175008921344   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command hello failed: No response received

 This log entry is a clear indicator that Kodi cannot connect to your tvheadend server.

**Comment by Durlyn** [comment]
channels work. no, just EPG. this situation occurs after switching to this commit

**Comment by Durlyn** [comment]
and further in the log:
019-07-19 22:39:31.849 T:140175008921344  NOTICE: PVR Manager: Started
2019-07-19 22:39:31.852 T:140175065716480  NOTICE: EPG thread started

**Comment by ksooo** [comment]
Please reset pvr data in pvr settings general section and restart Kodi. Does that help?

**Comment by Durlyn** [comment]
I wrote in the description of the problem. clearing data channels and EPG helps before rebooting. after reboot, the EPG is empty again.

**Comment by ksooo** [comment]
Please activate component logging for PVR and EPG in Kodi settings and post a new log here.

**Comment by debutanker** [comment]
Sorry for hijacking here, but i am on TVMosaic PVR-Addon facing the same problems with my epg-data.
Debug log with component logging activated -> http://ix.io/1P5U

**Comment by DaVukovic** [comment]
@debutanker 

Sorry, but you have banned add-ons installed. Please remove those first and, tbh, I would start with a vanilla Kodi installation and install as less as possible add-ons to reproduce your bug. Beside that's a recommendation, you need to remove the banned add-ons you are using.

**Comment by debutanker** [comment]
Thanks for your fast reaction and your hints @DaVukovic !
Ahhh, you mean this banned addon which should protect me from banned addons...sorry, but this addon is the "anti virus software" for my family and me on our libreelec-systems and i exceptionally disagree with you guys here!
So i sadly got to get off here...

**Comment by ksooo** [comment]
@debutanker could you post a log file for the same installation for an older Kodi version, where EPG still works?

**Comment by debutanker** [comment]
Many thanks for sharing your time here @ksooo !
Here's a log file (component logging activated/"anti virus addon" temporary deactivated ;) ) with last working milhouse version #0713.

**Comment by Durlyn** [comment]
This commit has not solved my problem.
the log of Kodi where EPG was read: https://pastebin.com/ekDw9nLv
and EPG not listed: https://yadi.sk/d/hQk54DIS2J8dEQ

**Comment by ksooo** [comment]
@Durlyn Please post 

1) a log from the last working kodi build.
2) a log where you applied the commits from #16386

**Comment by ksooo** [comment]
@Dumyat I assume you applied the fix yourself and built your own Kodi version to test and find out the fix not working? If so, please post a debug log for that private version.

If you have not built Kodi yourself, please note that the fix was not yet merged to Kodi master, there is no nightly build with that fix applied available atm.

**Comment by debutanker** [comment]
Will test with tonights Milhouse build and report back - many thanks @ksooo !

**Comment by ksooo** [comment]
@debutanker it seems you have not the same problem as @Dumyat has. Even if my fix did not fix the problem for @Dumyat there are good chances that it does fix your problem. So, please test and report back.

**Comment by ksooo** [comment]
@Durlyn your  log for the last working version has debug logging not enabled while Kodi is starting up, but this is what I need to compare working and non working version. Please resubmit a new log with debug enabled from the beginning.

**Comment by Durlyn** [comment]
Yes, I did not notice that there are no such commits in the master branch. I rebuild Kody, the EPG worked. Thanks.

**Comment by ksooo** [comment]
@Durlyn thanks for reporting back. Glad, that it works again for you. Let's wait for the feedback from @debutanker now. If he also confirms the fix working I will merge the fix PR into master.

**Comment by debutanker** [comment]
A thankful 'Go' from my side for PR-ing! Again and again many thanks for your great job @ksooo !
