### ISSUE TITLE
Play button pauses instead of plays when in FF or RW

### ISSUE THREAD

**Issue by dkadioglu** [xbmc/xbmc#16388]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I play some media (tested with streaming video from Netflix and ARDMediathek) and start to FF or RW I can only go into normal play state after pressing play two times. The first press always pauses the video, the second press plays again.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When in FF or RW pressing play should go to normal play instantly, without pausing first.

## Actual Behavior

When in FF or RW, the first press always pauses the video, the second press plays again.

## Possible Fix

I don't know, if this part of the code could be the culprit. Thought it might make sense to link to this code section: https://github.com/xbmc/xbmc/blob/817e7a8ca3bf662fc481c37b40ef62ab2cca53f7/xbmc/Application.cpp#L1598-L1606

### To Reproduce

1. Play some video
2. Start to FF or RW 
3. Press Play

### Debuglog

The debuglog can be found here:
https://paste.ee/p/9x3uc

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Others are also complaining:
https://forum.kodi.tv/showthread.php?tid=340477
https://www.reddit.com/r/kodi/comments/aloud2/kodi_18_android_tv_playbutton_after_ff/

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi 3B+
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC (Milhouse)
 - Kodi version: 19.0-ALPHA1 Git: 1584368

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
I just tested here with Kodi on Ubuntu and I don't use a remote. But I use my keyboard instead.

The shortcuts for that keyboard are "F" for "Fast Forward" and "P" for "Play". I also tested with the YouTube add-on and with local files and if I press "P" while the video is in FF, the video does not pause, but it plays again. 

Now it depends on how you control your LibreELEC installation. I suspect you are using some IR remote. If that's the case I would simply try to map specific functions or shortcuts to the buttons on your remote. For example I also tried to send an built-in python function (which you could also use as buttons on your remote) to send "Play" to Kodi while in FF: `kodi-send -a "PlayerControl(Play)"` which also works like a charm. So I guess there's no need to modify the Kodi code base if you are able to modify the keymapping matching to the device you are using.

**Comment by dkadioglu** [comment]
Thanks @DaVukovic for looking into this. Indeed, you're right, I am using a remote. Thanks for the tip regarding the mapping. As I already have a custom mapping in place, I added another for mapping the remote key 'play' to 'Play' instead of 'PlayPause' ('Play' should be the old behaviour, as far as I understand the corresponding entry in https://kodi.wiki/view/Action_IDs).
My mapping looks like the following:
`<keymap>
  <global>
    <remote>
      <print>ActivateWindow(Home)</print>
      <start>ActivateWindow(Favourites)</start>
      <play>Play</play>
    </remote>
  </global>
  <FullscreenVideo>
    <keyboard>
      <o>Info</o>
      <play>Play</play>
    </keyboard>
  </FullscreenVideo>
  <visualisation>
    <keyboard>
      <o>Info</o>
      <play>Play</play>
    </keyboard>
  </visualisation>
</keymap>
`
But Kodi still pauses when I press play on the remote. Am I misunderstanding something here?

**Comment by DaVukovic** [comment]
Could you please do me a favour: 

- provide the full debuglog (you haven't in the link above. There are things missing)
- provide your keymap xml file in a paste

Thanks in advance. I will look into it more tomorrow. 

What I've tested so far is, that it doesn't make a difference if I use: 

`kodi-send -a "Play"` or `kodi-send -a "PlayerControl(Play)"` while the video is in FF. Either will continue the normal playback and will not pause the video. 


@MilhouseVH Do we change something for LibreELEC in regard of the keymappings? I guess not.

**Comment by MilhouseVH** [comment]
> @MilhouseVH Do we change something for LibreELEC in regard of the keymappings? I guess not.

The only possibly relevant change I can find is this one:

https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/mediacenter/kodi/patches/kodi-995.10-devinputmappings.patch#L24

I can't reproduce the described behaviour with a LibreELEC master build using default keymaps and VRC-1100 remote - during FF when I press play, playback resumes and it does not pause.

This is my log with default keymaps: http://ix.io/1P1p

Below is the edited log where I seek FF (2x then 4x), then press play (default mapping `Play/Pause`), and playback resumes:
```
2019-07-21 00:03:14.942 T:1855976320   DEBUG: LIRC: - NEW d0 0 KEY_FASTFORWARD devinput (KEY_FASTFORWARD)
2019-07-21 00:03:14.950 T:1932701712   DEBUG: HandleKey: red (0xe3) pressed, action is FastForward
2019-07-21 00:03:14.954 T:1429791616   DEBUG: CMMALPool::Configure pool:0x5d0cf760 1920x1080 (1920x1088) pix:-1 size:128 fmt:OPQV
2019-07-21 00:03:14.960 T:1932698496   DEBUG: CAnnouncementManager - Announcement: OnSpeedChanged from xbmc
2019-07-21 00:03:14.960 T:1932698496   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnSpeedChanged
--
2019-07-21 00:03:16.357 T:1855976320   DEBUG: LIRC: - NEW d0 0 KEY_FASTFORWARD devinput (KEY_FASTFORWARD)
2019-07-21 00:03:16.366 T:1932701712   DEBUG: HandleKey: red (0xe3) pressed, action is FastForward
2019-07-21 00:03:16.374 T:1932698496   DEBUG: CAnnouncementManager - Announcement: OnSpeedChanged from xbmc
2019-07-21 00:03:16.375 T:1932698496   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnSpeedChanged
2019-07-21 00:03:16.375 T:1411957632   DEBUG: CDVDAudio::Pause - pausing audio stream
--
2019-07-21 00:03:19.775 T:1855976320   DEBUG: LIRC: - NEW cf 0 KEY_PLAY devinput (KEY_PLAY)
2019-07-21 00:03:19.777 T:1475089280   DEBUG: OutputPicture - dropped in output
2019-07-21 00:03:19.783 T:1932701712   DEBUG: HandleKey: homepage (0xea) pressed, action is PlayPause
2019-07-21 00:03:19.783 T:1932698496   DEBUG: CAnnouncementManager - Announcement: OnResume from xbmc
2019-07-21 00:03:19.783 T:1932698496   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnResume
```

In the OP's log, the key being pressed while seeking is `space` which is mapped to `Pause`, not `PlayPause` so the special logic to handle PlayPause during FF/REW does not apply in this case.
```
--
2019-07-20 12:02:24.577 T:1923085184   DEBUG: CLibInputKeyboard::ProcessKey - using delay: 500ms repeat: 33ms
2019-07-20 12:02:24.577 T:1932541968   DEBUG: Keyboard: scancode: 0x21, sym: 0x0066, unicode: 0x0066, modifier: 0x0
2019-07-20 12:02:24.577 T:1932541968   DEBUG: HandleKey: f (0xf046) pressed, action is FastForward
2019-07-20 12:02:24.577 T:1494852480   DEBUG: Thread Timer start, auto delete: false
2019-07-20 12:02:24.579 T:1186960256   DEBUG: CDVDAudio::Pause - pausing audio stream
--
2019-07-20 12:02:27.188 T:1494852480   DEBUG: Thread Timer start, auto delete: false
2019-07-20 12:02:27.193 T:1932541968   DEBUG: Keyboard: scancode: 0x39, sym: 0x0020, unicode: 0x0020, modifier: 0x0
2019-07-20 12:02:27.193 T:1932541968   DEBUG: HandleKey: space (0xf020) pressed, action is Pause
2019-07-20 12:02:27.197 T:1186960256   DEBUG: CDVDAudio::Pause - pausing audio stream
2019-07-20 12:02:27.202 T:1348449152   DEBUG: CMMALPool::Configure pool:0x6e026890 1280x720 (1280x720) pix:-1 size:128 fmt:OPQV
--
2019-07-20 12:02:30.170 T:1494852480   DEBUG: Thread Timer start, auto delete: false
2019-07-20 12:02:30.177 T:1932541968   DEBUG: Keyboard: scancode: 0x39, sym: 0x0020, unicode: 0x0020, modifier: 0x0
2019-07-20 12:02:30.177 T:1932541968   DEBUG: HandleKey: space (0xf020) pressed, action is Pause
2019-07-20 12:02:30.185 T:1186960256   DEBUG: CDVDAudio::Resume - resume audio stream
2019-07-20 12:02:30.185 T:1910231936   DEBUG: ActiveAE - start sync of audio stream
```
I don't know if `space` -> `Pause` is the default mapping behaviour although I suspect it is, in which case the OP may wish to try mapping `<space>PlayPause</space>` in keyboard.xml and see if that helps.

**Comment by dkadioglu** [comment]
Hi @MilhouseVH and @DaVukovic,

thank you very much for looking into this. Adding the mapping <space>PlayPause</space> in keyboard.xml works and now, after FF or RW, normal play starts instantly after pressing play. I have a Logitech Harmony Remote configured as Microsoft Media Center Remote 1039. The Play button is configured as MCE Play. I don't know if it is the default, that an MCE remote Play is mapped to space. What to do now? Is the behaviour intentional, which means I just keep the custom mapping <space>PlayPause</space>? Or is it not intentional and should be further investigated? Is there anything I can do to help?

Thanks again and best

**Comment by DaVukovic** [comment]
From my POV there are some mappings which could be improved. But, as said, that's my POV and if I want to have something customized I do that for myself. Therefore we either have the keymap editor add-on or are able to customize the keymapping manually by editing the specific files. 

For example...I don't like that the shutdown-menu opens if I press the "power off" button on my remote. As I also use a harmony and if I press the "power off"-button, my TV turns off, the AVR turns off and (by default) Kodi shows the shutdown menu and stays at this. So the HTPC doesn't turn off. The harmony doesn't have any "activity" anymore. So by pressing "ok" to shutdown the HTPC, I need to enter the "devices" sections, select the HTPC and press "ok" blindly. 

Showing the shutdown menu might be better for others instead of turning off their HTPC. So that's something I need to resolve on my own. The same counts for your usecase. Some ppl like to have the video being paused after FF. So I guess that's a thing you can't do correct as usecases might differ and customization will come in. 

So, if you don't mind, I would rather close this issue as it's not really an issue, more a request of a "nice to have"-change, which we give the option for by customizing the keymapping if someone needs something else.

**Comment by MilhouseVH** [comment]
@DaVukovic this is off topic but I just wanted to say I don't get the power menu when I press the "power off" button on my Harmony One remote - Kodi goes straight to "Shutdown" or "Suspend" (depending on the configured `Shutdown function`), and I don't see the power menu appear. Check that you have a `Shutdown function` configured and it hasn't become lost/corrupted (wild guess).

My remote control device from the Harmony database is `ORtekVRC-1100`, and the remote control device I've added is configured to use a toggle button for power (ie. one button turns on/off the AV equipment). Maybe try adding the ORtek remote control and test the `PowerToggle` button? Perhaps your remote device just needs to send the correct "off" IR code?

I'm testing with latest Kodi 19, stock Estuary, LibreELEC (in case any of that makes a difference) - I also tested with stock remote mappings (ie. without a custom `remote.xml`), and I don't see the power menu.

**Comment by dkadioglu** [comment]
I totally understand your point (@DaVukovic) and I am fine with that. As you said, people have different use cases and likings and, with methods like the keymap.xml, they can customize things as they want. So, also from my POV, we can close this issue.
And again, sorry for creating an issue for this. Although I already had a custom mapping, I did not have the idea to create one, before you proposed that to me. Thanks to both of you for pushing me in the right direction!
