### ISSUE TITLE
Label Error at Addonsettings Dialog

### ISSUE THREAD

**Issue by harryberlin** [xbmc/xbmc#16382]
## Bug report
Check thread for bug report: https://forum.kodi.tv/showthread.php?tid=345384
### Describe the bug
Check thread for bug description: https://forum.kodi.tv/showthread.php?tid=345384

## Expected Behavior
Have no idea

Check thread what happen: https://forum.kodi.tv/showthread.php?tid=345384

## Actual Behavior

don't know

## Possible Fix

Have no idea

### To Reproduce

Check thread for steps: https://forum.kodi.tv/showthread.php?tid=345384

### Debuglog

The debuglog can be found here:
You need some more infos?

### Screenshots 
Here are some links or screenshots to help explain the problem:

Check thread for screenshots: https://forum.kodi.tv/showthread.php?tid=345384

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

no additional screenshots

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HitcherUK** [comment]
Check thread for answer: https://forum.kodi.tv/showthread.php?tid=345384&pid=2869654#pid2869654
