### ISSUE TITLE
Can be deleted

### ISSUE THREAD

**Issue by hr77** [xbmc/xbmc#16389]
If you don't want bugs to be reported, then I won't.

**Comment by DaVukovic** [comment]
>The debuglog is probably not relevant for this bug report.

"probably"....if you are unsure, I guess it's not a burden to provide it, no? So please be so friendly and share it for the devs which might look into this bug. As we have the streamdetails in the debuglog I would say a log is pretty much relevant in that case. 

Thanks in advance

**Comment by DaVukovic** [comment]
>If you don't want bugs to be reported, then I won't.

lol

I simply asked for more information. If it such a burden to provide a simple debuglog, then I'm fine closing this report.
