### ISSUE TITLE
RasPi and vertical screen in landscape mode: garbled image

### ISSUE THREAD

**Issue by ldev** [xbmc/xbmc#16396]
### It seems Kodi have issues rendering properly on a vertical screen (1080x1920 instead of 1920x1080) rotated to horizontal mode
Here is a clear and concise description of what the problem is:

I am trying to use the Manga Screen 2 (https://www.thing-printer.com/product/manga-screen/) together with a Raspberry Pi as a small video displaying machine. The problem is that the Manga Screen 2 is a vertical/portrait 1080*1920 display, and rotating it to a horizontal/landscape display with the Raspberry Pi's config.txt makes the Kodi output only showing a intersection (half of the output us drawn outside of the display, half of the display is black. See attached image for a better understanding)

I've tested with Raspberry Pi 2 and Raspberry Pi 3, and with OpenELEC, LibreELEC, OSMC. The result is the same.

The Raspberry Pi config.txt file, which in other desktop environments makes the Manga Screen 2 function as a horizontal display:

    hdmi_group=2
    hdmi_mode=87
    hdmi_timings=1080 1 100 10 60 1920 1 4 2 4 0 0 0 60 0 144000000 3
    max_framebuffer_width=1920
    max_framebuffer_height=1920
    display_rotate=1

Kodi is picking up on this when I looked into the logs:
    2019-07-23 23:08:57.555 T:1936933536  NOTICE: Config:
                                            device_tree=-
                                            hdmi_timings=1080 1 100 10 60 1920 1 4 2 4 0 0 0 60 0 144000000 3

Kodi still shows garbled output as shown in the screenshot section.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expected Kodi to be drawn the same way as a desktop environment or the boot process output.

## Actual Behavior

When the Kodi application starts, the output is garbled and stretched as shown in the screenshot section.

### To Reproduce

1. Flash a MicroSD-card with either OSMC (OSMC_TGT_rbp2_20180109.img), OpenELEC (OpenELEC-RPi2.arm-8.0.4.img) or LibreELEC (LibreELEC-RPi2.arm-9.0.2.img). These are the latest stable images from the respective websites.
2. Edit the config.txt file (location varies based on distro) and add these six lines:
    hdmi_group=2
    hdmi_mode=87
    hdmi_timings=1080 1 100 10 60 1920 1 4 2 4 0 0 0 60 0 144000000 3
    max_framebuffer_width=1920
    max_framebuffer_height=1920
    display_rotate=1
3. Save and reboot. Kodi will start at boot, and the output will be as shown in the screenshot section.

### Debuglog

The debuglog can be found here: http://ix.io/1Pic

### Screenshots 
Here are some links or screenshots to help explain the problem:

When Kodi has started:
![20190724_005915](https://user-images.githubusercontent.com/6319859/61754435-77aba680-adb3-11e9-8e4f-cb65f089d3f2.jpg)

When booting the OS, before Kodi starts:
![20190724_014419](https://user-images.githubusercontent.com/6319859/61754762-cdcd1980-adb4-11e9-9a5d-824baeb3206a.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

x

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC-RPi2.arm-9.0.2.img
 - Kodi version: Kodi (18.2 Git:newclock5_18.2-Leia). Platform: Linux ARM 32-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ldev** [comment]
Hello, and thank you for reading my issue. Any possibility to remove the "Ignored rules" label?

**Comment by ldev** [comment]
From the logs:

```
2019-07-23 23:08:57.555 T:1936933536  NOTICE: Config:
                                            device_tree=-
                                            hdmi_timings=1080 1 100 10 60 1920 1 4 2 4 0 0 0 60 0 144000000 3
2019-07-23 23:08:57.556 T:1936933536   DEBUG: EGL initial desktop resolution 1080x1920 (608x1080) @ 60.00 - Full Screen (3.16)
2019-07-23 23:08:57.556 T:1936933536   DEBUG: EGL get supported modes (2) = 3, prefer_group=2, prefer_mode=57
2019-07-23 23:08:57.556 T:1936933536   DEBUG: EGL mode 0: 640x480 (640x480) @ 60.00 - Full Screen (1.00) :4
2019-07-23 23:08:57.556 T:1936933536   DEBUG: EGL mode 1: 1024x768 (1024x768) @ 60.00 - Full Screen (1.00) :10
2019-07-23 23:08:57.556 T:1936933536   DEBUG: EGL mode 2: 1080x1920 (608x1080) @ 60.00 - Full Screen (3.16) :57
2019-07-23 23:08:57.557 T:1936933536   DEBUG: EGL probe resolution 1080x1920 (608x1080) @ 60.00 - Full Screen:57020004
2019-07-23 23:08:57.557 T:1936933536  NOTICE: Found resolution 640 x 480 with 640 x 480 @ 60.000000 Hz
2019-07-23 23:08:57.557 T:1936933536  NOTICE: Found resolution 640 x 480 with 640 x 480 @ 59.940063 Hz
2019-07-23 23:08:57.557 T:1936933536  NOTICE: Found resolution 1024 x 768 with 1024 x 768 @ 60.000000 Hz
2019-07-23 23:08:57.557 T:1936933536  NOTICE: Found resolution 1024 x 768 with 1024 x 768 @ 59.940063 Hz
2019-07-23 23:08:57.557 T:1936933536  NOTICE: Found resolution 608 x 1080 with 1080 x 1920 @ 60.000000 Hz
2019-07-23 23:08:57.557 T:1936933536  NOTICE: Found resolution 608 x 1080 with 1080 x 1920 @ 59.940063 Hz
2019-07-23 23:08:57.557 T:1936933536  NOTICE: Found (608x1080@60.000000) at 20, setting to RES_DESKTOP at 16
```

To me (not familiar with EGL and such) it seems that it detects the correct resolution for the display (1080x1920), but lacks the possibility to understand that it is rotated 90° and that Kodi should draw at 1920x1080. Where 608x1080 comes into play I do not understand.

**Comment by popcornmix** [comment]
Rotated displays are not supported by kodi on Pi.
Even if it were supported the performance would be very much reduced (we have to take every output frame, render to on off-screen transposed buffer and then display that) which makes 50/60fps video (which includes interlaced content) not possible.

**Comment by DaVukovic** [comment]
I guess this one is good to close then

**Comment by ldev** [comment]
Thank you for looking into this and providing an explanation, even though it's not what i hoped for.
