### ISSUE TITLE
Resampling with ffmpeg + Sox

### ISSUE THREAD

**Issue by miketyson666** [xbmc/xbmc#16391]
### Describe the bug
Here is a clear and concise description of what the problem is:

ffmpeg resampling is not the best possible. Sox may improve it
See comparisons here: http://src.infinitewave.ca/

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Comparison tests among pure ffmpeg and ffmpeg using Sox show improvements in audio quality.

## Actual Behavior

Poor resampling with ffmpeg

## Possible Fix

Change the setting on the AE_QUALITY_HIGH option with code like this (just a suggestion, not sure the code is correct)
./xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAEResampleFFMPEG.cpp

if(quality == AE_QUALITY_HIGH)
  {
    av_opt_set_double(m_pContext,"cutoff", 1.0, 0);
    //av_opt_set_int(m_pContext,"filter_size", 256, 0);
    av_opt_set(m_pContext,"resampler", "soxr", 0);
    av_opt_set_int(m_pContext,"precision", 28, 0);
    av_opt_set_int(m_pContext,"linear_interp", 1, 0);
  }
  ...
  if (m_dst_fmt == AV_SAMPLE_FMT_S32 || m_dst_fmt == AV_SAMPLE_FMT_S32P)
  {
    // av_opt_set_int(m_pContext, "output_sample_bits", m_dst_bits, 0);
  }

### To Reproduce

1. not needed
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Feature requests go to forum, please.
