### ISSUE TITLE
Audio can be missing upon resumption of playback

### ISSUE THREAD

**Issue by ukmark62** [xbmc/xbmc#16390]
## Bug report
Running CoreELEC v9.0.3 on Android TV box - S905X with 2GB ram and 16GB internal memory, installed on 32GB class10 SD card. This issue is not present with LibreELEC 8.2.x, or Kodi Leia v18.3 on Windows 10 or Android. I've provided a sample highlighting the issue (below) and this should help devs to re-create and hopefully fix the problem. Also debug log is provided with audio, video and audio/video timing information component specific logging turned on.

I’ve noticed that occasionally when resuming playback on a video, there is no audio for up to several seconds. I think there is a pattern to this on the testing I have done so far and it appears to be related to video keyframes (i.e. video resumes at previous keyframe whereas audio resumes at "actual" resume time). There was a change done in Kodi (https://github.com/xbmc/xbmc/pull/11713), where resumption of video playback was fixed to look for the previous keyframe as the resumption point (it used to look for the next keyframe). 

### Describe the bug
For example up until this change, if you stopped playback at 5:00, where the previous keyframe in the video stream was at 4:55 and the next keyframe was at 5:05, then when resuming playback, the video would start at 5:05 (5 seconds too late). After this fix, the video resumed at 4:55 (and audio also re-started at 4:55). With the vast majority of video streams it appears that video keyframes are very close to each other, and the time difference between the previous video keyframe resume time and the "actual" resume time is negligible, so you won’t notice any audio problems. I’ve found that very occasionally, the gap between keyframes can be several seconds, and what appears to be happening here is that whilst the video resumes at the previous keyframe, the audio seems to resume at the "actual" time playback was stopped. So, using the above example, playback between 4:55 and 5:00 would mean no audio was heard, and once we reached 5:00, the audio resumed.

## Expected Behavior
Audio should be present from the determined resume point.

## Actual Behavior
Audio is missing from the determined resume point, until we reach the "actual" resume point.

## Possible Fix
The "selfish" fix is to revert the change for #13665:-

Namely, in the kodi file videoplayer.cpp file, I removed the line number 1341:-
**FlushBuffers(starttime / 1000 * AV_TIME_BASE, true, true);**

I forked CoreELEC, made the above change with a patch to remove the line and made a test image - that’s the only change from CoreELEC master.
Now, the audio is heard immediately upon resume. So far I’ve not had any issues.
This line was not present when #11713 was first done.
Maybe make this change conditional depending upon the environment??

### To Reproduce
NB. "Hardware Decoding" must be set ON in Kodi/Settings/Player/Allow hardware acceleration.

I've posted a link to a small 15Mb sample.mkv showing the issue where the gap between keyframes is several seconds:- https://mega.nz/#F!DhxBDY4L!WY62ZBT0rHSf7meo-LTTMA

If you stop playback at 40 seconds, then resume from there, you should notice that video playback resumes from about 33-34 seconds (the previous keyframe closest to resume time), and there is no audio until you hit the 40 second mark. (You may need to add the following to your Kodi "advancedsettings.xml" file or the video won't be marked as "in progress"):-

-advancedsettings>
-video>
-ignoresecondsatstart>30</ignoresecondsatstart>
-/video>
-/advancedsettings>
NB. I had to remove the leading "<" as the editor removed the text following it,

It does appear that audio always resumes from the resume time regardless of where the previous video keyframe is. This issue is not present using LibreELEC v8.2.5 (Kodi 17.6). With that version the video resumes from 33 seconds with accompanying audio.

### Debuglog
http://ix.io/1P3F

### Screenshots 
N/A

## Additional context or screenshots (if appropriate)
N/A

### Your Environment
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: CoreELEC and LibreELEC
 - Kodi version: Leia v18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
What about PRing it if you have the fix already at hand?

**Comment by ukmark62** [comment]
The fix would revert the fix for #13665.

Sent from Mail for Windows 10

**Comment by FernetMenta** [comment]
> I don't understand why the fix for #13665 works for Windows 10 and Android, but does not work for LibreELEC/CoreELEC - maybe the "flushbuffers" only works for Windows and Android - I'm just guessing here??

#13665 works quite well for Linux x86 which differs heavily from Linux ARM. I assume that hardware decoders for those ARM boards have issues with accurate seeks. Not the hw decoders itself but their implementations into Kodi.

**Comment by ukmark62** [comment]
Thanks - I should have clarified that the issue only shows itself with "hardware decoding" on. With hardware decoding turned off, the resume point will always be the same as the "actual" resume time. I'll update the report to say that.

**Comment by FernetMenta** [comment]
In your case you have to blame CDVDVideoCodecAmlogic, which was already removed in v19

**Comment by ukmark62** [comment]
So maybe when we have a version of LibreELEC/CoreELEC running kodi v19, the problem may no longer be present?

**Comment by jjd-uk** [comment]
It's not clear whether you have also tested LibreELEC 9.2 since you only mention using CoreELEC for Leia? after CoreELEC forked from LibreELEC they have done their own changes to the Kodi player core code and as such CoreELEC is unsupported here.

**Comment by ukmark62** [comment]
It's exactly the same for LibreELEC - problem exists there also on v9.2 (using Kodi Leia v18.3) and my "fix" works on LibreELEC for Amlogic, Allwinner and Rockchip compiles I have made using LibreELEC v9.2 with this fix applied.

**Comment by jjd-uk** [comment]
Kodi for v19 will see big changes for ARM devices as we attempt to get everything on mainline kernel (or as close as possible with minimal patching) using GBM/DRM so all ARM devices use a common codebase. This will be a lot of work and as such usable v19 builds for Amlogic hardware maybe a long time off.  This is why I was asking if you had tried LE, but since you have and seen the same issue then there's going to be no short term fix for you.

**Comment by FernetMenta** [comment]
> there's going to be no short term fix for you.

Oh, would you reject a fix fo this if it was submitted tomorrow? The fact that nobody seems to care for a fix for v18 does not mean that is is hard to fix.

**Comment by jjd-uk** [comment]
Not my area, you seemed to imply problem was in Amlogic platform specific stuff which is no longer in Master, so no fix could be submitted. Unless you think there is something that could be done in the generic parts of code that would cause no regression to other platforms.

**Comment by DaVukovic** [comment]
I guess what fernet wants to say is, that there could still be a fix for v18. 

Th fact that specific code is not part of the v19 codebase does not mean we can't fix it for v18, I guess ;)

**Comment by FernetMenta** [comment]
> Not the hw decoders itself but their implementations into Kodi.

^^ What I wanted to say it that the problem is not the platform itself but code that belongs to Kodi.

**Comment by jjd-uk** [comment]
If there is something can be submitted to Master then for sure that wouldn't be rejected then a backport could be done for a potential 18.4 release. That is assuming we stick to normal ways of working where a fix must be in Master before it gets back ported and added to Leia branch. If you mean PR to Leia branch only and not to Master then that would not be how we normally do things. Either way I wouldn't be involved in any decision.

**Comment by fritsch** [comment]
I disagree. If it's gone in v19 and the fix only touches the amlogic codec in v18 it's obviously a fix. One not relevant for master but obviously welcome for the stable release.

**Comment by bronnel** [comment]
there is an audio gap (missing a couple of seconds of audio ) when resuming any locally present video file of any format , mp4 , mkv , avi , etc.
This issue still exists on latest v19 Matrix Nightly , this issue has been present since v16 , it is platform independent , it happens to me on iOS , Android , Mac , Windows 7/10 , Linux/ubuntu , you name it , this is still alive, it is the reason I no longer use kodi , I was a skin modder , until this issue gets fixed I will not go back to kodi and mod skins,

**Comment by evlo** [comment]
Issue is still present in 9.2.2

**Comment by arnova** [comment]
Just for the record: I also see this happening on RPi(2) + Kodi 18.5 and MPEG4/AVI.

**Comment by redec** [comment]
FWIW I'm also getting this on RPi4 running Kodi 18.7, I have observed it in mkvs with DTS and Dolby, happens regardless of using passthrough or not
