### ISSUE TITLE
TV SHOWS: no more posters

### ISSUE THREAD

**Issue by stefano70** [xbmc/xbmc#16394]
### Describe the bug
Here is a clear and concise description of what the problem is:

Adding TV SHOWS from SMB or HTTP source will not show posters

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Just show posters like in the older versions

## Actual Behavior

Adding TV SHOWS from SMB or HTTP source will not show posters

### To Reproduce

1.  Add a source as TV SHOW
2. Using local NFO
3. when browsing, no posters at all

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/gadawosuga.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Please post one of your NFO Files. Same place as where you posted the log.

**Comment by stefano70** [comment]
this is Shaun The Sheep

here the tvshow.nfo
https://paste.kodi.tv/bofaridoza

here one episode
https://paste.kodi.tv/nogikikose

I tested again with 17.x Kodi and it was working...

**Comment by HitcherUK** [comment]
`<thumb></thumb>` is empty?

**Comment by KarellenX** [comment]
>Do you have local artwork?

**Comment by stefano70** [comment]
Yes I have
Here you can find the directory output
https://paste.kodi.tv/sirebegasa

**Comment by KarellenX** [comment]
Ok, I see you have already seen this Issue... https://github.com/xbmc/xbmc/issues/15481#issuecomment-462193945

One of the developers will need to look into this issue as I cannot see any fault in your setup.  As a side-note and not the cause of this problem, but your nfo files are not fully Kodi compatible.

Possibly @arnova might have some comment if he is available.

**Comment by stefano70** [comment]
any improvement on this topic?
Maybe fixed in 18,4 ?

thanks
