### ISSUE TITLE
Yahoo! Weather add-on exception thrown 

### ISSUE THREAD

**Issue by timmcdonald** [xbmc/xbmc#16400]
### Describe the bug
Here is a clear and concise description of what the problem is:

An exception is thrown when the Yahoo! Weather add-on attempts to collect the weather. 
Here is a clear and concise decription of what was expected to happen:

Weather should be collected and displayed.
## Actual Behavior

Exception thrown.
Exception continues every hour while Kodi runs.

### To Reproduce

1.  Weather in side-bar, wait for about 20 minutes. Error reported.
2. 
3. 

### Debuglog

The debuglog can be found here:
2019-07-24 14:57:24.575 T:1799328624   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/weather.yahoo/default.py", line 285, in <module>
                                                forecast(location, locationid)
                                              File "/storage/.kodi/addons/weather.yahoo/default.py", line 142, in forecast
                                                properties(data, loc, locid)
                                              File "/storage/.kodi/addons/weather.yahoo/default.py", line 169, in properties
                                                set_property('Updated'                   , convert_datetime(data['observation']['observationTime']['timestamp']))
                                              File "/storage/.kodi/addons/weather.yahoo/default.py", line 32, in convert_datetime
                                                timestruct = time.strptime(stamp[:-5], "%Y-%m-%dT%H:%M:%S")
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:  Kodi 18.2 Git:newclock5_18.2-Lela
LibreELEC 9.0.2 (kernel: Linux 4.19.36)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@timmcdonald 

Thank you for your report, but this area is for Issues with Kodi core program and not add-ons.

Please re-post your problem on the forum here... https://forum.kodi.tv/showthread.php?tid=169410 where the add-on developer is more likely to see it.

I will close this report.
