### ISSUE TITLE
Shield TV Experience Update 8 broke auto color space switching.

### ISSUE THREAD

**Issue by ljsvv** [xbmc/xbmc#16428]
### Describe the bug
Here is a clear and concise description of what the problem is:

After doing the Nvidia Shield TV experience 8 update Kodi doesn't switch Color Space anymore. Offcourse the Auto Color Space switch option is turned on in the Shield settings.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Having Kodi to switch to the right Color Space automatically.

## Actual Behavior

Kodi doesn't switch.

## Possible Fix

Perhaps this Android Pie functionality must be integrated in Kodi?

### To Reproduce

1.  Play different Movies with different Color Spaces.
2. Kodi stays on the Color Space selected in the Nvidia Shield Output settings.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Please provide thee requested debulog

**Comment by jjd-uk** [comment]
You do know there's a problem with the auto-switching in new Shield TV Experience Update 8 software, perhaps it's this you are seeing https://forums.geforce.com/default/topic/1158216/shield-tv/shield-experience-upgrade-8-0/post/6126666/#6126666

**Comment by HitcherUK** [comment]
Kodi has nothing to do with switching anyway; it's handled by the Shield.

**Comment by Dnkhatri** [comment]
color space switching is working perfectly for me on new shield update
