### ISSUE TITLE
Live TV Subtitles settings not persistent

### ISSUE THREAD

**Issue by psko** [xbmc/xbmc#16434]
### Describe the bug
Here is a clear and concise description of what the problem is:

After I upgraded to Kodi 18, the "enabled" subtitles setting (PVR) is not persistent after switching a TV Channel back and forth (on either iptv simple client or tvh client). This is a problem because I have to bring up the menu and enable subtitles each time I switch channels.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After enabling subtitles on a specific Tv Channel it is expected that the subtitles remains enabled for this channel after zapping through other channels.

## Actual Behavior

After enabling subtitles on a specific Tv Channel and then pressing stop (or switching to another channel) and playing the original channel again the subtitles are disabled.

### To Reproduce

1. Play a TV Channel (which has subtitles)
2. Enable subtitles
3. Press stop (or switch channel)
4. Play the same TV Channel again
5. The subtitles are now disabled (should be enabled as in Kodi 17)

### Debuglog

The debuglog can be found here:
https://paste.osmc.tv/casalaxaho
or
https://paste.kodi.tv/komagegeve

### Screenshots 
Here are some links or screenshots to help explain the problem:

Link to screen recording: 
https://www.dropbox.com/s/fvionl7ha38n2n3/test_video.zip?dl=0

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Reproduced the behaviour on all Kodi 18 versions;

Reproduced the behaviour on both IPTV Simple Client and Tvheadend client

Reproduced the behaviour on Android TV (Oreo), OSX , Raspberry Pi 3 (OSMC) and Vero 4k+ (OSMC)

Backend is TVheadend version 4.2.8

On some channels, the subtitles also disappears when a tv show goes to the commercials (I have to manually enable it again)

Works as expected on Kodi 17 and on other apps, so I ruled out a backend problem.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC June 2019 2019.06-1 (Debian Stretch)
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
> After enabling subtitles on a specific Tv Channel it is expected that the subtitles remains enabled

I disagree. 

There might be cases where this would be pretty annoying. Rather than making that setting persistent after enabling, I would suggest to use the keyboard shortcut (button `t` on your keyboard in that case) to toggle the subtitles. That would be at least work on your OSX System.

For the RPi, if you are using a remote, you could also map a button for that toggle using the keymap editor add-on. If you have a keyboard attached, then `t` will work there as well. 

In either case, it's not needed to bring up the OSD if you don't want to.

**Comment by Leatherface75** [comment]
It should say enabled if user has enabled it so i agree with him.
That's the normal behavior for subtitles on TV boxes.

**Comment by psko** [comment]
> > After enabling subtitles on a specific Tv Channel it is expected that the subtitles remains enabled
> 
> I disagree.
> 
> There might be cases where this would be pretty annoying. Rather than making that setting persistent after enabling, I would suggest to use the keyboard shortcut (button `t` on your keyboard in that case) to toggle the subtitles. That would be at least work on your OSX System.
> 
> For the RPi, if you are using a remote, you could also map a button for that toggle using the keymap editor add-on. If you have a keyboard attached, then `t` will work there as well.
> 
> In either case, it's not needed to bring up the OSD if you don't want to.

So do you think this is not a bug and it was an intended change from Krypton to Leia? 

If that is the case then the audio track selection shouldn't also be persistent (it is) and there shouldn't also be the subtitles option "set as default to all media".  And as I mentioned there is also the problem of the subtitles disabling by itself on some channels when a Tv Show goes to the commercials (with no channel switch). So I think it is indeed a bug.

**Comment by Leatherface75** [comment]
I have seen this myself on free streams on the net and i need to turn subtitles on again after every commersial and that can be 5-6 times in an hour.

**Comment by vlouis** [comment]
Same on my HTPC (Raspberry 3 B+, Astrometa DVB-C tuner, Tvheadend server), only for channels with single subtitle steam: starting with Kodi 18: "Select which subtitle stream to display. If only one subtitle track is available, this option will not be available." (more info: https://kodi.wiki/view/Subtitles (wiki). I checked in MyVideo116.db, settings table, the issue can be, if no subtitle stream selected (because if only one stream exist and the box is disabled) the stream value remain "-1", this value are stored in database only if I change the subtitle offset ("settings" table, "SubtitleStream").
A possible solution can be, if the "Enable subtitles" switch changed to "ON", to be verified if only one stream is present and store in DB value "0" to "SubtitleStream" (and "1" to "SubtitlesOn").
I have very little programming experience, but I will try to find where need change in codes.
![videoDB-1](https://user-images.githubusercontent.com/40323785/64009454-8e66bb00-cb20-11e9-8ddb-0c28de379689.jpg)

**Comment by psko** [comment]
Thanks for the info @vlouis ! If anyone can point out which file contains the related code I can also try to help (couldn't find the file).

Another workaround I found is to use Tvheadend's matroska profile with IPTV simple client. The cons here are: no channel numbering from backend and also a little delay of the playback (sucks for live sports).

**Comment by vlouis** [comment]
Hi @psko 
I started with /xbmc/video/dialogs/GUIDialogSubtitleSettings.cpp, then \xbmc\video\PlayerController.cpp, but still learning and searching... I try to find where is the code for saving video parameters to database... but I don't have enough time for this (family, job...)

**Comment by notspiff** [comment]
call me crazy, but CVideoDatabase::SetVideoSettings sounds like it might be
related (it even has doxy!) then just trace it back from there (you'll find
a few call sites but nothing that is too hard to decode).

**Comment by emveepee** [comment]
@ksooo @phunkyfish  has fixing this issue been considered for Matrix?  I regularly have to answer questions from pvr.nextpvr users who want these enabled by default.  I understand hitting the T is not difficult but if the subtitles where on by default and we told users to simply hit the T to turn them off  each time they tuned a channel user would be understandably annoyed.

**Comment by phunkyfish** [comment]
PRs welcome 😉

**Comment by emveepee** [comment]
> 
> 
> PRs welcome 😉

I only have access to North American subtitle and since the issue hasn't even been acknowledged or flagged for Matrix I was reluctant.  It isn't hard to enable subtitles as a default, but I don't even think that the global setting is currently linked to guisettings.xml but I probably could persist subtitles.enabled to avoid the hitting the T key if you think it is worth the effort.  

There also doesn't appear to be way to save individual setting for channels North American broadcasts in the setting table which use CC1-4 and not languages so cycling through them with the L still seems necessary.

**Comment by phunkyfish** [comment]
Well I guess any PR should solve it for all subtitles. So are you saying some subtitles are languages and some are not?

We store a last played time in the channels table, I guess we could store the last language track/subtitle there too. But it could be tricky as there are defaults for audio tracks that you would be overwriting (such as match original language etc.). But I guess if you have manually selected a track that is your preference.

**Comment by phunkyfish** [comment]
BTW, I've noticed this in the past with default audio tracks (not subtitles) so I do this: https://github.com/kodi-pvr/pvr.vuplus/issues/218

**Comment by emveepee** [comment]
> 
> 
> Well I guess any PR should solve it for all subtitles. So are you saying some subtitles are languages and some are not?

My local experience is all the CEA 708 closed captioning show as Unknown [captions] (1/1)  or sometimes Unknown [captions] (1/2)  and Unknown [captions] (2/2) 

I understand that in the US they have Spanish captions typical on CC3  I don't know if those can be distinguished with spa or not.  I guess we'd need a sample to find out.  I don't know how CC4 is used.

**Comment by phunkyfish** [comment]
Do the captions appear as audio tracks? What I see on my local streams are options like English, Descriptive English and Subtitled. Subtitled is English with subtitles.

**Comment by emveepee** [comment]
> 
> 
> Do the captions appear as audio tracks? What I see on my local streams are options like English, Descriptive English and Subtitled. Subtitled is English with subtitles.

We don't but typically DVB transport streams can have subtitle type streams as well as audio/video  in the mux like this sample

```
  Program 4287
    Stream #0:0[0xc9]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, top first), 704x576 [SAR 16:11 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Side data:
      cpb: bitrate max/min/avg: 15000000/0/0 buffer size: 1835008 vbv_delay: N/A
    Stream #0:1[0xca](eng): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 256 kb/s
    Stream #0:2[0xce](eng): Audio: mp3 ([3][0][0][0] / 0x0003), 0 channels, fltp (visual impaired) (descriptions) (dependent)
    Stream #0:3[0xcd](eng): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006)
```
If this is what you mean for the purpose of this issue do those subtitles come back on in PVR either from the streamdetails table and/or globally?

**Comment by phunkyfish** [comment]
Sorry my question was specifically around close captions. So they appear like subtitles.

**Comment by emveepee** [comment]
> 
> 
> Sorry my question was specifically around close captions. So they appear like subtitles.

Yes on the subtitle not audio screen.   I did test a couple of DVB streams as fake Live TV  and they do not appears to suffer from the same problem

**Comment by emveepee** [comment]
Your suggestion to use the User interface language works for me for DVB subtitles so others in this thread might give that a try.

For CC's I had good success with this https://github.com/emveepee/xbmc/blob/seeccing/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L140

and have asked some users to see if it helps.  I got that idea after seeing this.

https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxCC.cpp#L317

**Comment by phunkyfish** [comment]
Nice. Let’s see if it works for others and then possibly PR it.

**Comment by Leatherface75** [comment]
> Well I guess any PR should solve it for all subtitles. So are you saying some subtitles are languages and some are not?
> 
> We store a last played time in the channels table, I guess we could store the last language track/subtitle there too. But it could be tricky as there are defaults for audio tracks that you would be overwriting (such as match original language etc.). But I guess if you have manually selected a track that is your preference.

Yeah a setting with prefer manually selected subtitles would make sense or just make it the normal behaviour.

**Comment by ksooo** [comment]
This long standing issue is fixed for Kodi v21 Omega. :-)
