### ISSUE TITLE
kodi Appimage

### ISSUE THREAD

**Issue by cmatomic** [xbmc/xbmc#16430]
[kodi_crashlog-20190801_143451.log](https://github.com/xbmc/xbmc/files/3457159/kodi_crashlog-20190801_143451.log)
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Actual Behavior

I created a Kodi Appimage but the inputstream.adaptive crashed the Kodi appimage 5 minutes later playing a streming.

## Possible Fix
official release of a Kodi appimage made by the kodi team

### To Reproduce

1  if you  want test this Appimage
This sequence of commands will download the necessary files and execute them to generate the appimage. ( in Ubuntu ) then you can go to the kodi-Nightly/out  folder and click on the generated appimage
` mkdir kodi-Nightly;cd kodi-Nightly;wget https://raw.githubusercontent.com/AppImage/AppImages/master/pkg2appimage; mv pkg2appimage pkg2appimage.sh;chmod +x pkg2appimage.sh;wget https://raw.githubusercontent.com/cmatomic/RecipesAppimage/master/kodi-Nightly-xenial.yml ; ARCH=x86_64 ./pkg2appimage.sh kodi-Nightly-xenial.yml  `
2 installing netflix plugin
3 play streaming and wait 5-10 minutes

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 16.04.6 LTS (Xenial Xerus)
 - Kodi version: 19.0-ALPHA1 Git:20190801-6aba73b

This issue is also reported in the official Appimage repository.
https://github.com/AppImage/pkg2appimage/issues/380
and 
https://github.com/peak3d/inputstream.adaptive/issues/292
*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
@cmatomic 

The crashlog you provided is pretty useless as it has debugging information disabled. The stacktrace is also empty. Please install gdb via: `sudo apt install gdb` and then retry and provide a new log please.

Thanks in advance.

**Comment by wsnipex** [comment]
I'm going to close this, since we don't have any intention to officially support appimage.
