### ISSUE TITLE
Latest release on github not set to latest stable release

### ISSUE THREAD

**Issue by majamee** [xbmc/xbmc#16445]
### Describe the bug
Here is a clear and concise description of what the problem is:
On https://github.com/xbmc/xbmc/releases is the latest release not set to the latest stable version of Kodi (18.3), but instead the previous release is still marked as latest.
This is especially an issue for me as I have written a small Android app for Amazon Fire TV devices, which automatically checks for updates and if available offers to download and install it.
(If you are interested I am happy to hand over the code)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
The latest release tag should be set on github to the latest version (currently 18.3).

## Actual Behavior

On https://github.com/xbmc/xbmc/releases is the latest release not set to the latest stable version of Kodi (18.3), but instead the previous release is still marked as latest.

## Possible Fix

Please set the latest release tag to match your latest stable release on https://github.com/xbmc/xbmc/releases

**Comment by DaVukovic** [comment]
Done, thanks for the heads up

**Comment by majamee** [comment]
@DaVukovic Would you or anyone else from the Kodi Team interested in having a look at my FireTV Updater & Launcher application for Kodi? I am happy to give you access to/ hand over the code or to send over a pre-build apk to test it out. I hope you are interested :) Looking forward to hearing from you.
