### ISSUE TITLE
Stream parameters change ignored

### ISSUE THREAD

**Issue by korni** [xbmc/xbmc#16446]
### Describe the bug
When a running, displayed stream changes its parameters, most prominently its aspect ratio, this change is not carried out, but ignored. This worked in an earlier version (regression).

Using Kodi with a live backend (TVheadend), certain programmes (SD) change their stream parameters on the fly, e.g. when switching from an old 4:3 programme to 16:9 commercials. Kodi used (afair, in a pre 18 version) to notice that change and modified the display parameters accordingly. While Kodi has no problem interpreting the stream parameters when the channel is switched/selected, all further changes are ignored.

## Expected Behavior

When a stream coming from a backend (like TVheadend) changes its parameters, like aspect ratio changing from 16:9 to 4:3, Kodi should change the display accordingly.

## Actual Behavior

When a stream coming from a backend (like TVheadend) changes its parameters, like aspect ratio changing from 16:9 to 4:3, Kodi does not modify the display and shows the video vertically stretched or condensed.

## Possible Fix

As this is known to have worked at some point in time, it may be possible to fix the regression by undoing the change.

### To Reproduce

1. Watch live TV with changing aspect ratios (old shows mixed with commercials)
2. Notice, that switching from/to a commerical the display gets streched/condensed
3. Switch to another channel and back and notice that the aspect ratio is correct now until the next change.

### Debuglog

The debuglog can be found here:

https://raw.githubusercontent.com/korni/scratch/master/kodi-16446.log

Short sequence. Went on a channel, waited for aspect change, switched channel for and back, stopped stream, quite.

### Screenshots 
Here are some links or screenshots to help explain the problem:

Visual should be obvious.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Android TV on NVIDIA Shield

 - Operating system version/name:
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
>The debuglog can be found here:

Sorry, none.


We will need it. Otherwise we can't help

**Comment by korni** [comment]
Added log.
