### ISSUE TITLE
Cancel Button missing in some progress dialogs

### ISSUE THREAD

**Issue by DaVukovic** [xbmc/xbmc#16459]
### Describe the bug
Here is a clear and concise description of what the problem is:

While installing skins or cleaning library, nearly everywhere a progressbar is usually shown, there was also a cancel-button shown to cancel the current action. That's not the case anymore. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

See a cancel button during installations of skins/add-ons or while cleaning the library for example

## Actual Behavior

Cancel button is not shown

## Possible Fix

I don't have a fix for that at hand, but I compiled Kodi 19 and reverted this PR completely. 

#16393 

After that, the cancel button was shown again. So I guess that PR might need some love ;)

### To Reproduce

1. compile current Kodi master (make sure #16393 is included)
2. install an add-on or clean the library

### Debuglog

The debuglog can be found here:
I guess we won't need a debuglog in that case. It will simply show that DialogConfirm.xml is initiated but not which buttons are shown or not. 

### Screenshots 
Here are some links or screenshots to help explain the problem:

with the mentioned PR above included:
![image (1)](https://user-images.githubusercontent.com/7235787/62737309-c2722300-ba2f-11e9-88ce-ee7fe09c2f0c.png)

after reverting the PR:
![grafik](https://user-images.githubusercontent.com/7235787/62737197-7e7f1e00-ba2f-11e9-9f7b-7ddc42f1d88a.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19 alpha 1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
BTW: Issue subject is misleading, as this issue is not related to the skin xml file. It's a core issue.

**Comment by DaVukovic** [comment]
Thanks
