### ISSUE TITLE
Season name has json in it

### ISSUE THREAD

**Issue by seth--** [xbmc/xbmc#16451]
Season name is supposed to be "Season 1" but kodi shows json instead

![screenshot001](https://user-images.githubusercontent.com/1149570/62671551-b9208200-b96d-11e9-892f-a3c6a588508b.png)

This only happens using the standard interface, the web interface shows Season 1 as expected

The season name is broken in the database:
` sqlite> select * from seasons where idSeason = 202;
idSeason|idShow|season|name|userrating
202|31|1|Roadkill Garage","next_episode_to_air":null,"networks":[],"number_of_episodes":28,"number_of_seasons":3,"origin_country":[],"original_language":"en","original_name":"Roadkill Garage","overview":"Roadkill Garage is where David Freiburger and Steve Dulcich show you how to do the wrong thing the right way! Whether the guys are wrenching on project cars from the Roadkill show or creating their own moving violations, you'll always get info and action on Roadkill Garage.","popularity":1.049,"poster_path":"/72N48zfRBnkj9BIE5o4MKocgoBh.jpg","production_companies":[],"seasons":[{"air_date":"2016-01-22","episode_count":13,"id":100290,"name":"Season 1|
`

Scraper cache file (.kodi/temp/scrapers/metadata.tvshows.themoviedb.org/tmdb-77661-en.json) looks good:

`{"backdrop_path":"/lnDiJ3M8Nosuqs9wwz0mRIFkhUa.jpg","created_by":[{"id":1746361,"credit_id":"5a9c23ea0e0a260658034859","name":"David Freiburger","gender":0,"profile_path":"/tWhDjlgcTLk9GjQ3oHUBkjxo9Jv.jpg"}],"episode_run_time":[],"first_air_date":"2016-01-22","genres":[{"id":99,"name":"Documentary"},{"id":35,"name":"Comedy"}],"homepage":"https://www.motortrendondemand.com/show/roadkill-garage-/42024902/","id":77661,"in_production":true,"languages":["en"],"last_air_date":"2019-07-15","last_episode_to_air":{"air_date":"2019-07-15","episode_number":7,"id":1869636,"name":"Suspension Upgrades for the Disgustang!","overview":"What’s the use of more power if you can’t handle it? Last episode, David Freiburger and Steve Dulcich refreshed the drivetrain in the Disgustang but now they are tackling the rest of the project to truly make it a daily-driving beast. Up front, it’s getting a new suspension with plenty of stiffening to the flimsy Ford while still making it a smooth ride. In the hind quarters, they are upgrading the shocks, swapping the rear gears, and beefing up the axles. Once everything is together, the guys finally get to take the Disgustang on its maiden voyage. Will it pass the Roadkill daily-driver test? Find out on this episode of Roadkill Garage!","production_code":"","season_number":4,"show_id":77661,"still_path":"/lnDiJ3M8Nosuqs9wwz0mRIFkhUa.jpg","vote_average":0.0,"vote_count":0},"name":"Roadkill Garage","next_episode_to_air":null,"networks":[{"name":"Motor Trend","id":2444,"logo_path":"/2BGpHwd0CpeH4fKN32O217RbtI8.png","origin_country":"US"}],"number_of_episodes":45,"number_of_seasons":4,"origin_country":["US"],"original_language":"en","original_name":"Roadkill Garage","overview":"Roadkill Garage is where David Freiburger and Steve Dulcich show you how to do the wrong thing the right way! Whether the guys are wrenching on project cars from the Roadkill show or creating their own moving violations, you'll always get info and action on Roadkill Garage.","popularity":0.6,"poster_path":"/72N48zfRBnkj9BIE5o4MKocgoBh.jpg","production_companies":[],"seasons":[{"air_date":"2016-01-22","episode_count":13,"id":100290,"name":"Season 1","overview":"Season 1 of Roadkill Garage, featuring David Freiberger and Steve Dulcich. Episodes 1 - 13 originally aired on Motor Trend on Demand.","poster_path":"/hvA4qes1pPy2V2JCpsSxJXfiapC.jpg","season_number":1},{"air_date":"2017-02-09","episode_count":12,"id":100291,"name":"Season 2","overview":"Season 2 of Roadkill Garage, featuring David Freiberger and Steve Dulcich. Episodes 14 - 25 originally aired on Motor Trend on Demand.","poster_path":"/EfziE2dMGM4pq4yquhxpuJNKYg.jpg","season_number":2},{"air_date":"2018-01-01","episode_count":13,"id":100292,"name":"Season 3","overview":"Season 3 of Roadkill Garage, featuring David Freiberger and Steve Dulcich. Starting at Episode 26, the show originally aired on Motor Trend on Demand.","poster_path":"/irtaFhjxgrQGcyYgiAAlhu86eme.jpg","season_number":3},{"air_date":"2019-01-28","episode_count":7,"id":128729,"name":"Season 4","overview":"Season 4 of Roadkill Garage, featuring David Freiberger and Steve Dulcich. Starting with Episode 39 (MTOD numbering) and  originally aired on Motor Trend on Demand.","poster_path":null,"season_number":4}],"status":"Returning Series","type":"Scripted","vote_average":10.0,"vote_count":1}
`

That file seems to match the scraper regex as expected https://github.com/xbmc/xbmc/blob/master/addons/metadata.tvshows.themoviedb.org/tmdb.xml#L70

### Debuglog

Not really sure how to get an useful debug file. What are the steps to have the season name fetched again?

### Your Environment
 - Operating system version/name: Raspbian 9
 - Kodi version: 18.2

**Comment by DaVukovic** [comment]
>Not really sure how to get an useful debug file. What are the steps to have the season name fetched again?

by looking at: https://www.thetvdb.com/series/roadkill-garage

There are no "Season names". The seasons are called "Season 1", "Season 2" and so on. But to see what has been scraped (again), I would just refresh the TV show information (ignore local data and rescrape online) or, if that doesn't help, remove that show from your library, probably clean it if necessary and then scan for new data

**Comment by seth--** [comment]
A refresh fixed it. I will leave debug logging enabled just in case this happens again

**Comment by DaVukovic** [comment]
ok. Probably Kodi had a hickup ;)

I'll close this for now. Feel free to comment here if you encounter the issue again and I'll happily re-open it.
