### ISSUE TITLE
Feature Request: Move library update and other processes outside of Kodi GUI exe

### ISSUE THREAD

**Issue by Viper911** [xbmc/xbmc#16469]
I would like to have library scans, etc. to be able to run as a service outside of Kodi running.  For example on Windows if I shut down Kodi, I don't want to have to do scans when I come in if they could be running separately.  

Also this would be good for Nvidia Shield where Kodi isn't always active (although I am not sure if there is something similar to a service in andoird)

**Comment by DaVukovic** [comment]
Feature request needs to be done at our forums. This section here is for bug reports. 

Please open a thread here: https://forum.kodi.tv/forumdisplay.php?fid=9
