### ISSUE TITLE
how to compile on android? I am a developer

### ISSUE THREAD

**Issue by tubeuchiha** [xbmc/xbmc#16462]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Rechi** [comment]
Read the documentation in the docs folder, https://github.com/xbmc/xbmc/blob/master/docs/README.Android.md

**Comment by notspiff** [comment]
i don't believe you. why would a developeropen a bug report cause of their inability to build software?

**Comment by tubeuchiha** [comment]
> i don't believe you. why would a developeropen a bug report cause of their inability to build software?

Ha ha, I don't know where to ask questions, see issue can ask questions, so...

**Comment by notspiff** [comment]
forum.kodi.tv

**Comment by tubeuchiha** [comment]
> forum.kodi.tv

ok，thanks you
