### ISSUE TITLE
Wrong audio channel format shown (5.0 vs. 4.1)

### ISSUE THREAD

**Issue by basicmaster** [xbmc/xbmc#16473]
### Describe the bug
Kodi displays a wrong audio channel format. When a video contains AC-3 audio with 5.0 channels, an audio channel format of 4.1 is displayed.

## Expected Behavior
The correct audio channel format 5.0 should be displayed.

## Actual Behavior
The wrong audio channel format 4.1 is displayed.

## Possible Fix
It seems that the audio channel format only covers the resulting count of channels, but not the actual channel configuration. So five channels are assumed to always result in a "4.1" configuration. However "5.0" is also valid in such a case. 5.0 is a configuration that is sometimes used in German TV for concerts e.g. Jazz.

So the fix would be to rather propagate the actual channel configuration instead of only the channel count, as the latter will not be sufficient in some cases.

### To Reproduce
1. Play the [example file, containing 5.0 audio](https://basicmaster.de/test/ac3_5.0.ts).
2. Press the "Backspace" button (on PC) to return to the file list, showing also video information at the bottom (assuming default theme)
3. The wrong channel format "4.0" is shown.

(note that this example file contains 5.0 audio by mistake; actually this movie would have been broadcasted in 5.1)

### Screenshots 
![kodi_audio_channel_count](https://user-images.githubusercontent.com/7103991/62822398-fca00980-bb82-11e9-86fc-0a38d2da5ba1.png)

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu Linux 16.04 LTS AMD64
 - Kodi version: Git master (1661e19b113bc55dfa15441f59ae0421b19b3fad)

**Comment by fritsch** [comment]
> 2019-08-10 15:41:47.063 T:139978050877184    INFO: ffmpeg[7F4F2DFFB700]: Input #0, mpegts, from 'ac3_5.0.ts':
2019-08-10 15:41:47.063 T:139978050877184    INFO: ffmpeg[7F4F2DFFB700]:   Duration: 00:00:16.40, start: 62735.350778, bitrate: 14916 kb/s
2019-08-10 15:41:47.063 T:139978050877184    INFO: ffmpeg[7F4F2DFFB700]:   Program 11130
2019-08-10 15:41:47.063 T:139978050877184    INFO: ffmpeg[7F4F2DFFB700]:     Stream #0:0[0x18a6]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc
2019-08-10 15:41:47.063 T:139978050877184    INFO: ffmpeg[7F4F2DFFB700]:     Stream #0:1[0x18b0](deu): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 256 kb/s
2019-08-10 15:41:47.063 T:139978050877184    INFO: ffmpeg[7F4F2DFFB700]:     Stream #0:2[0x18b1](deu): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 192 kb/s (visual impaired) (descriptions)
2019-08-10 15:41:47.063 T:139978050877184    INFO: ffmpeg[7F4F2DFFB700]:     Stream #0:3[0x18b2](deu): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, 5.0(side), fltp, 448 kb/s
2019-08-10 15:41:47.063 T:139978050877184    INFO: ffmpeg[7F4F2DFFB700]:     Stream #0:4[0x18b3](mul): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 192 kb/s
2019-08-10 15:41:47.063 T:139978050877184    INFO: ffmpeg[7F4F2DFFB700]:     Stream #0:5[0x18ba](deu): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006), 492x250

Seems we decode and detect it properly, so only a "visual" issue.

**Comment by DaVukovic** [comment]
https://github.com/xbmc/xbmc/tree/master/addons/skin.estuary/media/flags/audiochannel

There's no flag for `5.0`

**Comment by fritsch** [comment]
Yes - and kodi's gui layer lacks the infrastructure to query for subwoofers, which I consider a minor. It starts in process info where we just expose the "amount of channels".

**Comment by HitcherUK** [comment]
Unfortunately a skin can only assume that 5 channels is 4.1 as that's probably more common.

**Comment by fritsch** [comment]
I checked again, ProcessInfo has all the channels we use. It's a string in there already. Which method do you call to get the number of channels?

**Comment by fritsch** [comment]
I see:
```
addons/skin.estuary/xml/DialogSeekBar.xml:                                              <param name="texture" value="$INFO[VideoPlayer.AudioChannels,flags/audiochannel/,.png]" />
```

You could tell that a sub has a value of 10 - with that:

5.0 -> 5
4.1 = 14
7.2 = 27
7.0 = 7
7.1 = 17

**Comment by HitcherUK** [comment]
`VideoPlayer.AudioChannels` uses the same as `ListItem.AudioChannels`

```Shows the number of audio channels of the currently selected video (possible values: 1, 2, 4, 5, 6, 7, 8, 10)```

**Comment by fritsch** [comment]
Yes. If you want to keep your integer interface and want to only distinguish between 8.0 and 7.1 - the above "encoding" is a possibility.

Although VideoPlayer already returns a layout as well and processinfo has the same layout as a string.

In short: the underlaying information is already there, but not processed by the gui.

**Comment by HeresJonny** [comment]
Just a as a hint: For DSD encoded music, the LFE channel is especially problematic. It is used in a different way as in the PCM, cf the last third of this article https://bobpariseau.com/blog/2018/4/28/calibration-discs-you-need-these . For that reason, some SACD publishers have opted to mix music as 5.0 without an LFE channel to avoid calibration/reproduction problems. In this context, proper channel detection within Kodi becomes especially relevant.

**Comment by fritsch** [comment]
Kodi itself detects all the channels properly. Audioengine handles 5.0 just
fine.

The issue at hand is a gui issue only. A cosmetic problem, nothing else.

HeresJohnny <notifications@github.com> schrieb am So., 18. Aug. 2019, 14:40:
