### ISSUE TITLE
Video/Audio sluggish with Audio pass-through

### ISSUE THREAD

**Issue by sscobici** [xbmc/xbmc#16479]
### Describe the bug
Here is a clear and concise description of what the problem is:

On 16.1 playing 5.1 movie with audio path-through is working ok.
On 18.3 I have an issue with audio path-through option.
When the pass-through is disabled the video and audio works fine while playing a movie although audio is 2 channel.
After enabling pass-through video is sluggish and drop frames, audio is 5.1 but with a lot of interruptions.
I also reproduced the issue with 17.6 and nightly build 20190810, so it seems like a regression from 16.1.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The movie is played smoothly with 5.1 sound.

## Actual Behavior

Video is sluggish and drop frames, audio is 5.1 but with a lot of interruptions.

### To Reproduce

1. Install clean 18.3 with default settings
2. Go to System->Audio->Enable path-through
3. Play a movie with 5.1 audio

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/xurudavije.kodi - kodi-16.1-with-path-through.log
https://paste.kodi.tv/ecomuhicic.kodi - kodi-20190810-no-pass-though.log
https://paste.kodi.tv/wojudamive.kodi - kodi-20190810-with-path-through.log  (BAD)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
With version 17 the private API of the amldecoder was removed to fully support Android's Mediacodec only. Some (older) boxes that do not implement official Android API work now worse than before.

Best thing you can do:
a) Stay with Version 16
b) Ask your vendor to upgrade the firmware to properly support Mediacodec Surface.

**Comment by sscobici** [comment]
It's Android 5.1.1 on MXIII-G device. I haven't found any new firmware for this device from the vendor so I will stick with Version 16.

Thanks.

**Comment by da-anda** [comment]
can we close this issue then?

**Comment by sscobici** [comment]
Yes please, I will try to hack the code to be able to run 18 version on my device.

**Comment by 520ph** [comment]
> Yes please, I will try to hack the code to be able to run 18 version on my device.

Did you successfully crack it in the end?
