### ISSUE TITLE
No Passthrough HD audio on Xiaomi Mi Box S 

### ISSUE THREAD

**Issue by cgaspard3333** [xbmc/xbmc#16474]
### Describe the bug
Here is a clear and concise description of what the problem is:
On the Xiaomi Mi Box S, the HD audio Passthrough is not working (the options "TrueHD Capable receiver" and "DTS-HD capable receiver" are not shown in the system -> audio menu).
These options are available on the Xiaomi Mi Box 3, which is older but had exactly the same processor. 
I obviously have a Onkyo amplifier compatible with HD audio like Dolby Atmos or DTS:X

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
The options "TrueHD Capable receiver" and "DTS-HD capable receiver" should appear in the System -> Audio -> Passthrough menu of the Xiaomi Mi Box S. (Just as it is working on the Mi Box 3)

## Actual Behavior
The options "TrueHD Capable receiver" and "DTS-HD capable receiver" are not shown in the System -> Audio -> Passthrough menu of the Xiaomi Mi Box S.

## Possible Fix
A fix is to let appear these options because the Mi Box is totally compatible with Passthrough, and obviously because it's working with the Mi Box 3 which has the same hardware ! 

### To Reproduce
1. Launch Kodi on the Xiaomi Mi Box S connected to a compatible HD audio (Atmos/DTS:X) amplifier
2. Open Settings -> System 
3. Go at the bottom of the screen on "Basic" and click multiple times to have "Expert" 
4. Go upward to "Audio" 
5. Select "Allow Passthrough" 
6. "TrueHD Capable receiver" and "DTS-HD capable receiver" are not shown

### Screenshots 
![IMG_20190810_173857](https://user-images.githubusercontent.com/28164044/62823855-5fe76700-bb96-11e9-9cc6-294ca367fcc3.jpg)
This is the menu on the Mi Box 3 (Android TV 8.0) (Options are availables)

![IMG_20190810_174234](https://user-images.githubusercontent.com/28164044/62823859-6fff4680-bb96-11e9-8a30-58db5b564af6.jpg)
This is the menu on the Mi Box S (Android TV 8.1) (Option are not shown)

### Your Environment
Used Operating system:
 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 8.1 arm7a - Mi Box S

 - Kodi version: 18.3 
(Same problem on 18.4 beta (09/08/2019) and 19.0 alpha (09/08/2019)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Return the box. They broke passthrough with the update. Nothing to fix for kodi, we only use the public Apis and no hacks.

**Comment by fritsch** [comment]
You can downvote this as much as you want, it won't change the facts.

Btw. you were told in the forum thread already.

**Comment by cgaspard3333** [comment]
I downvoted it because this is a machine on which your software is suppose to work on. It's really simple to say that I have to send it back to the reseller. You should either work with Xiaomi to tell them why your software isn't working on their platform and help them to fix it maybe. Xiaomi box are very popular in the marketplace so it is not juste a personnal bad experience in my opinion.

**Comment by fritsch** [comment]
See, you are wrong, but you don't get it. Kodi supports the official Android standards, verified on many boxes, TVs, out there. Your vendor instead cares not a single bit to provide standard APIs and demands money from you - while kodi is entirely for free.

Sorry, that you invested your money in a wrong way.

**Comment by fritsch** [comment]
Further discussion goes in your forum thread: https://forum.kodi.tv/showthread.php?tid=338047
