### ISSUE TITLE
ListItem "year" infoLabel is not used in Information pane

### ISSUE THREAD

**Issue by dagwieers** [xbmc/xbmc#16486]
### Describe the bug
Here is a clear and concise description of what the problem is:

When we set the `year` infoLabel on a ListItem, it is not being used in the Information pane when selecting **Information** in the context menu of that item. Instead it is using the year of the `aired` or `premiered` infoLabel.

Since our add-ons are listing TV streaming content, the `aired` infoLabel actually is when it was broadcasted on the TV channel (usually the same or previous year), not when it first was broadcasted. That is why we set the `year` infoLabel for the movie explicitly.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The Information pane should be showing the `year` infoLabel if that is explicitly set, rather than use the `aired` date's year value. It could still use that if the `year` infoLabel wasn't set.

## Actual Behavior
The Information pane is ignoring the `year` infoLabel, but is using the year from the `aired` infoLabel.

## Possible Fix
Use the `year` infoLabel if it was set, otherwise fall back to the `premiered` infoLabel, or `aired` infoLabel.

### To Reproduce
1. Create a ListItem with a `year` and `aired` infoLabel using a different year
2. Open the Information pane
3. Conclude that Kodi is using the year from the `aired` infoLabel

### Debuglog
The debuglog is of no help in this issue.

### Screenshots 
The below screenshot shows the movie year as **2019** whereas the `year` infoLabel was correctly set to `2013`.
![screenshot010](https://user-images.githubusercontent.com/388198/62903472-11d38e80-bd63-11e9-8b96-1c65a53b77eb.png)
*The VOD metadata shows season-metadata as year, and episode-metadata as 1, that is why you also see 2013x1 below the movie title.*

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC v9.0.2
 - Kodi version: 18.2

**Comment by dagwieers** [comment]
This relates to: pietje666/plugin.video.vrt.nu#401

**Comment by bigretromike** [comment]
This is also semi related to: https://github.com/xbmc/xbmc/issues/14573,
When you pick `year` to sort by it will display `airing` date as label2.

![airing in year](https://user-images.githubusercontent.com/6052025/46781688-28642000-cd23-11e8-9755-88f6c82b5399.png)

**Comment by dagwieers** [comment]
This issue was also reported here, seems broken since Kodi 17: https://forum.kodi.tv/showthread.php?tid=302622
