### ISSUE TITLE
Using default action: 'show information' result in "one or more items failed to play'

### ISSUE THREAD

**Issue by bigretromike** [xbmc/xbmc#16481]
### Describe the bug
Here is a clear and concise description of what the problem is:

When user change default behavior in kodi from 'Play' to 'Show information' and try to play listitem that has url as a routing plugin with no advancesettings.xml every 5 try end up with Error. This happens in 17.6, 18.3 and 19.0-pre. Playing file directly never results in any error.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Play same file multiply time should end up with same result (while file is all the time available)

## Actual Behavior

Almost everytime when I play same file I end up with DialogBox about file not being able to play, while the file plays in background, clicking 'OK' results in aborting play, next play will always work.

## Possible Fix

https://github.com/xbmc/xbmc/blob/6aba73be78e8228195c3326590d191a2c65760c4/xbmc/PlayListPlayer.cpp#L322
```
((XbmcThreads::SystemClockMillis() - m_failedSongsStart  >= static_cast<unsigned int>(advancedSettings->m_playlistTimeout) * 1000)
``` 
this fails always after few (~ 5) executions, it looks like the time of execution is added across multiply execution, changing timeout from default `20`, to `200` make it 10x less appearing. 
Looks like something is not clean up.

### To Reproduce

1. change default action to 'show information' instead of 'play'
2. enter multiply time same file, and pick play 
3. ensure that the file you trying to play use routing to resolve it and maybe somekind of backend so the response is not from internal kodi database.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/avojarakaq.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.0-pre, 18.3, 17.6

edit: sorry, I hit enter and it auto submit without body

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
A title is way not enough. Please fill out the template. Otherwise this issue will be closed in 7 days.

Thanks

**Comment by bigretromike** [comment]
@DaVukovic sorry I hit enter and it auto submit it, now it should be all ok

**Comment by bigretromike** [comment]
Not sure how important this is but someone point out that I should try using `setResolvedUrl` instead of `xbmc.Player().play` and it looks like this is a workaround this bug.

**Comment by bigretromike** [comment]
I will be closing this.. better to put time in fixing bigger issues than those with workarounds
