### ISSUE TITLE
xbmc.translatepath and xbmcvfs.exists do not support user variable

### ISSUE THREAD

**Issue by zach-morris** [xbmc/xbmc#16483]
### Describe the bug
Here is a clear and concise description of what the problem is:

xbmc.translatepath and/or xbmcvfs.exists do not return expected results if "~" or "~user" is in the provided path.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

xbmc.translatepath and/or xbmcvfs.exists expand "~" or "~user" if they are in the provided path.

## Actual Behavior

Code:
```
from kodi_six import xbmc, xbmcvfs
import os
print('ztest')
print(xbmc.translatePath('~'))
print(xbmcvfs.exists('~/mytestfile.txt'))
print(os.path.expanduser('~'))
print(xbmcvfs.exists(os.path.expanduser('~/mytestfile.txt'))
```
Results in:
```
DEBUG: ztest
DEBUG: ~
DEBUG: 0
DEBUG: /Users/myusername
DEBUG: 1
```

### To Reproduce

1. See code above

### Debuglog

The debuglog can be found here:
See code above

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Hey @zach-morris,
I don't see this as an issue (definitely not a bug) but rather a feature request. Kodi is multi-platform while expanding such paths will be platform dependent and introduce complexity in the codebase for no apparent gain. I suggest you open a thread in the forum in the feature requests section so someone might look at it. In the meanwhile, and as you must likely already know, you can use `os.path.expanduser` from python as a workaround before passing the path to the kodi xbmcvfs module:
https://docs.python.org/3/library/os.path.html#os.path.expanduser

Cheers
