### ISSUE TITLE
Struggered live TV playback with AirPlay audio output

### ISSUE THREAD

**Issue by sy6sy2** [xbmc/xbmc#16489]
### Describe the bug

When I watch a live TV channel (TVHeadend/terrestrial channel) with an AirPlay audio receiver selected on my macOS audio system setting, the playback is "chopped" (playback works well during 1 or 2 second, then I see the bleu wheel for 1 or 2 second, etc ...).

This issue does not appear when I watch a movie from my SMB hard drive.

I was able to reproduce the problem with this configs combo:

* Kodi 17.6 on macOS with Apple TV as AirPlay audio receiver
* Kodi 17.6 on macOS with Shairport-sync as AirPlay audio receiver
* Kodi 17.6 on Apple TV with Shairport-sync as AirPlay audio receiver

Each time with a Live TV channel from TVHeadend.

Also, it is important to note that this issue does not appear when I use my internal speaker on my Mac or the television speakers with the Apple TV.

## Expected Behavior

After a short time of synchronisation the video and audio should be in sync and playback smooth (like this is the case when I watch a movie with a selected AirPlay audio output).

## Actual Behavior

Is not possible to correctly watch a live TV channel, with fall in an infinite loop of play-wheel-play-wheel

### To Reproduce

1. Install Shairport-sync on any Linux computer (or maybe use an Apple AirPort or your Apple TV or an HomePod)
2. On your Mac choose your AirPlay audio receiver
3. Start Kodi
4. Start a live TV channel (on my case with TVHeaded/HDHomeRun/DVB-T channel)
5. Video is not smooth

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/soducafeni.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS 10.14.6
 - Kodi version: 17.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
I guess I'm not much of help here, but could you also reproduce your issue with Kodi 18,x? As there won' t be any fixes for Kodi 17.6 anymore

and please provide a full debuglog

**Comment by SylvainCecchetto** [comment]
Kodi 18.3 seems better to sync, but is not yet fantastic.
Full log: https://paste.kodi.tv/yidejuyida.kodi
