### ISSUE TITLE
DTS ES XLL displays incorrect mediaflag

### ISSUE THREAD

**Issue by apguy** [xbmc/xbmc#16497]
### Describe the bug
MKV files with the a single audio track with the codec DTS ES XLL is given the media flag DTS instead of DTS-HD-MA

DTS ES XLL is a type of DTS encoding where there is a lossy DTS ES matrix core with the MA lossless extension.  When played with a compatible player it should be lossless DTS MA sound.  

When first scanning the library KODI displays files with this codec as DTS in the mediaflag on the skin.   That implies lossy DTS only.   After playing the file once it is then correctly changed to display DTS-HD-MA.  Adding a DTS-HD-MA tag to the filename does not change this behaviour.  I usually add an audiocodec extension to all my filenames to overcome KODI not yet detecting Atmos nor DTSX audiocodecs.

## Expected Behavior

The correct DTS-HD-MA mediaflag should be displayed after updating the library

## Actual Behavior

The mediaflag DTS is displayed

## Possible Fix

Could improve the detection of audiocodecs , maybe along with atmos and dtsx at the same time

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

have the correct audio codec displayed

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Windows 10 1803
 - Kodi version:
18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Could you please share a testfile, thanks

A snippet from about a minute would be enough. If you are not comfortable by sharing it here, lthen et me know.

**Comment by apguy** [comment]
I’ll send a snippet when I get home.

I’ve got about 20 mkv files that I ripped myself from Blu-ray all with the same

Interestingly all of the star wars first 6 movies have the dts es xll audio codec

On 15 Aug 2019, at 2:43 pm, DaVukovic <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you please share a testfile, thanks

A snippet from about a minute would be enough. If you are not comfortable by sharing it here, lthen et me know.

**Comment by DaVukovic** [comment]
And please get us a logfile as well by playing the shared file.

**Comment by apguy** [comment]
I am so sorry for opening this but I believe that it can be closed.

The problem was not with Kodi at all.  It was with a 3rd party media manager that was writing the incorrect audiocodec to the nfo files that I use.

My apologies
