### ISSUE TITLE
Crash when calling `Player().play()` in python plugin

### ISSUE THREAD

**Issue by jaylinski** [xbmc/xbmc#16491]
### Describe the bug

I'm the developer of the SoundCloud Plugin and am facing a crash when calling
```
xbmc.Player().play()
```
in the plugin code.

Here is the line that causes the crash:
https://github.com/jaylinski/kodi-addon-soundcloud/pull/20/files#diff-2c4065511eff519de303a2347b89e946R108

Either this is a real bug, or I'm doing something very wrong (since this function is successfully used by countless of other plugins).

## Expected Behavior
The ListItem added to the playlist (https://github.com/jaylinski/kodi-addon-soundcloud/pull/20/files#diff-2c4065511eff519de303a2347b89e946R107) should start playing.

## Actual Behavior
Kodi freezes immediately and crashes after about 15 seconds.

## Possible Fix

I have no idea what the problem is. But if there is a document that explains how to troubleshoot a Kodi crash report, I'll be happy to try and find out about the issue myself.

### To Reproduce

1. Install the plugin https://kodi.wiki/view/Add-on:SoundCloud
2. Apply the patch by adding this line: https://github.com/jaylinski/kodi-addon-soundcloud/pull/20/files#diff-2c4065511eff519de303a2347b89e946R108
3. Open Firefox, install the extension https://addons.mozilla.org/en-GB/firefox/addon/echo-for-kodi/
4. Enable "Allow remote control from applications on other systems" in Kodi
5. Add your Kodi IP to the "Echo for Kodi" extension (you should have a connection)
6. Visit SoundCloud (eg https://soundcloud.com/polo-g/polo-g-feat-lil-tjay-pop-out) open the extension and click "PLAY"
7. Kodi freezes and crashes

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/aminemeyaq.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04 LTS (inside VirtualBox)
 - Kodi version: 18.3

**Comment by L2501** [comment]
might be related to https://github.com/xbmc/xbmc/pull/16450

**Comment by DaveTBlake** [comment]
I could be way off, you probably need someone with more Python knowledge to advise, but since no one has stepped up here are my thoughts. 

Your addon seems to set up a playlist and then tell the player to play without telling it _what_ to play.  Without parameters  the Player will try to play the current item in the current playlist, but Kodi has to have a current item and a current playlist for that to work.

Be nice to get SoundCloud working again, it is my favorite test music addon (I don't use them in real life, my music collection is large enough to satisfy).

**Comment by basrieter** [comment]
What I can see is that the call via the API results in a call to the plugin:

> 2019-08-13 12:59:38.462 T:140565632112768   DEBUG: StartScript - calling plugin SoundCloud('plugin://plugin.audio.soundcloud/play/','1','?url=https%3A%2F%2Fsoundcloud.com%2Fpolo-g%2Fpolo-g-feat-lil-tjay-pop-out','resume:false')

However, that one actually resolves to another call to: 

> 2019-08-13 12:59:44.989 T:140565632112768   DEBUG: StartScript - calling plugin SoundCloud('plugin://plugin.audio.soundcloud/play/','2','?url=https%3A%2F%2Fsoundcloud.com%2Fpolo-g%2Fpolo-g-feat-lil-tjay-pop-out','resume:false')

(For me, it even redirected to `play/?media_url=` at some point?)

Both will end up accessing the xbmc.Player().play() which causes weird stuff to happen. What you should do is generate a playlist (as you do). Then call the `xbmcplugin.setResolvedUrl` method and pass the correct and already resolved item of the first item in the playlist.

**Comment by jaylinski** [comment]
@basrieter Thanks, I'll try that.

**Comment by jaylinski** [comment]
@basrieter Resolving the URL did the trick. Thanks again.

Fix: https://github.com/jaylinski/kodi-addon-soundcloud/pull/20/files

**Comment by notspiff** [comment]
for reference; using player.play() in a plugin is contract breakage and is not supposed to work. you are implementing a file system entry with an expected behavior, not a generic script.
