### ISSUE TITLE
Clean Library causes crash

### ISSUE THREAD

**Issue by jonathanjones2** [xbmc/xbmc#16495]
Here is a clear and concise description of what the problem is:
When running the clean library function Kodi will crash.

Here is a clear and concise description of what was expected to happen:
Kodi would iterate through my library and remove missing or deleted items

Actual Behavior:
The progress window appears but freezes immediately. I've read that sometimes this process can be slow for large libraries so I walked away for an hour. However the logs will only track activity for about 2 minutes after starting the clean operation then it stops. When I go back to Kodi the application restarts.

## Possible Fix
I've double checked that all my library mount points are corrected and accessible. They are.

1. Open Kodi
2. Goto settings -> media -> library -> click clean library
3. Click yes on the confirmation screen

The debuglog can be found here:
[https://paste.kodi.tv/hamakeheca](https://paste.kodi.tv/hamakeheca) see line ~271 for start of cleaning

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Sony Bravia TV (XBR-49X900E), andriod 8.0.0, security patch level May 1, 2019. Kernel 3.10.79, build BRAVIA_ATV2_UC-user 8.0.0 OPR2.170623.027.S25 665201
 - Kodi version: 18.3 (latest available from the store)

**Comment by DaVukovic** [comment]
Could you please provide a debuglog from startup?

If I see it correctly you are not playing anything while doing the library clean, correct?

If you are playing something while doing the library clean, does this sound familiar then?
https://forum.kodi.tv/showthread.php?tid=345261

**Comment by jonathanjones2** [comment]
There is no media running while I run the cleaning function.

Here is the log output from a fresh start. The clean function is called on line 1337
[http://paste.kodi.tv/oxisifesot](http://paste.kodi.tv/oxisifesot)

**Comment by boot2k3** [comment]
The similar issue on Windows
Cleaning up library.. and kodi freezes. 
tested on KodiSetup-20190821-04d70092-Leia-x64.exe
After 5 minutes it's done.. but I have only several videos in library...
2019-08-23 12:01:25.669 T:10848  NOTICE: CVideoDatabase::CleanDatabase: Cleaning videodatabase done. Operation took 05:13
Debug log attached if it could help somehow...
[kodi_log.log](https://github.com/xbmc/xbmc/files/3533710/kodi_log.log)

**Comment by DaVukovic** [comment]
@boot2k3 

Looks like that you have several network problems: 

> 2019-08-23 11:56:51.534 T:1196   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for ftp://USERNAME:PASSWORD@172.16.1.1/sda1/entware/tmp/TV/4_xmltv.xml.gz

> 2019-08-23 11:56:57.897 T:10848   ERROR: CCurlFile::Exists - Failed: Couldn't connect to server(7) for http://192.168.100.100:4044/proxy/0_10_26.mpeg

From the other log above, I'm not so sure if that's related. 

@jonathanjones2 could you please enable curl specific logging and please get us a new log, so we are able to compare. 

Thanks

**Comment by boot2k3** [comment]
Thank you for fast reply
I disabled PVR to have more clean log related to this issue.
I don't have now any videos in movie library, but the situation is the same... but it still tries to remove something at 192.168.100.100:4044. This address is not available now.
[kodi_debug_curl.log](https://github.com/xbmc/xbmc/files/3533998/kodi_debug_curl.log)
If you need another issue to open I can do it, but for me it looks related. On Android it also hangs the same way for me.

**Comment by arnova** [comment]
That's your problem: the address is not available causing a timeout for every item in your db located on that ftp server. Either remove the ftp host from your sources or bring the server back up.

**Comment by arnova** [comment]
Btw. note that your description is confusing. This is considered a "freeze" not a crash. Furthermore I think this belongs on the forum, not here.

**Comment by boot2k3** [comment]
ok, I will open a thread on forum
With this freeze I couldn't press any button... If I press a button than it causes application hung. And some of watchdog monitored system kill kodi.
Why not to delete all of this unavailable paths? I don't have them configured somewhere in library
@arnova, I don't have some library files on ftp, it was spam from PVR, sorry
See log in my previous message https://github.com/xbmc/xbmc/files/3533998/kodi_debug_curl.log
And I don't understand where this http://192.168.100.100:4044 could be removed? I don't have such sources

**Comment by jonathanjones2** [comment]
Here is the new log with CURL logging enabled
[http://paste.kodi.tv/ujiqehemar](http://paste.kodi.tv/ujiqehemar)

See line 1351, I let it hang for about 10 minutes before doing a force stop

**Comment by DaVukovic** [comment]
Thanks, I'm completely out of ideas currently. If that log has curl logging enabled then it was not usefull as it doesn't tell anything more. Sorry for wasting your time. 

Maybe someone else has an idea.

**Comment by jonathanjones2** [comment]
Yeap, the option was enabled, but it dies so quick it's like it doesn't have a chance to do anything.
