### ISSUE TITLE
Visualizations (projectm, spectrum) cause crash (Ubuntu 18.04, Kodi 18.3, Intel i915 graphics)

### ISSUE THREAD

**Issue by flakey-bit** [xbmc/xbmc#16493]
### Describe the bug
When either the ProjectM visualization or the Spectrum visualization is enabled, Kodi will crash after playing music for some time (around 20 minutes). With no visualizations enabled, Kodi can play music overnight at least.

## Expected Behavior
Kodi should not crash w/ the ProjectM/Spectrum visualization enabled

## Actual Behavior
Kodi crashes after around 20 mintues w/ ProjectM (I think it might take longer to crash with Spectrum, however I'm not sure about that).

### To Reproduce
1. Turn on ProjectM visualization
2. Start playing a playlist of local MP3s & switch to 'player' mode
3. Wait for crash

### Debuglog
[kodi_visualization_crash.zip](https://github.com/xbmc/xbmc/files/3500059/kodi_visualization_crash.zip)

## Additional context or screenshots (if appropriate)
* https://forum.kodi.tv/showthread.php?tid=305558
* https://forum.kodi.tv/showthread.php?tid=306064
* https://trac.kodi.tv/ticket/17204

*NB*: I don't think these are relevant since `visualization.projectm.so` apparently no-longer links against `glew`:

```
ldd visualization.projectm.so
	linux-vdso.so.1 (0x00007ffd15ef7000)
	libprojectM.so.2 => /usr/lib/x86_64-linux-gnu/libprojectM.so.2 (0x00007f30114bb000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3011132000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3010f1a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3010b29000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f301089d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3010699000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f30102fb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3011a1d000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f30100ca000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f300fe14000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f300fbf5000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f300f8bd000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f300f695000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f300f491000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f300f28b000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f300f076000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f300ee6e000)
```

### Your Environment
`Ubuntu Linux 18.04 / 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
`Intel NUC NUC5CPYH (intel i915 integrated graphics)`
`00:02.0 VGA compatible controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller (rev 21)`
Kodi 18.3 (`2:18.3+git20190621.1610-final-0bionic`) `deb-src http://ppa.launchpad.net/team-xbmc/ppa/ubuntu bionic main`
kodi-visualization-projectm: 2.2.0-1~xenial

**Comment by notspiff** [comment]
Kodi 18.3 (2:18.3+git20190621.1610-final-0bionic) deb-src http://ppa.launchpad.net/team-xbmc/ppa/ubuntu bionic main
kodi-visualization-projectm: 2.2.0-1~xenial

from gut reaction that looks bad.

**Comment by flakey-bit** [comment]
It seems to be stable now after ensuring both Kodi & plugin versions are from "bionic":

* kodi: `Version: 2:18.3+git20190621.1610-final-0bionic`
* kodi-visualization-projectm: 2.2.0-1~bionic

Closing issue. Sorry for wasting your time!

**Comment by flakey-bit** [comment]
Update: I spoke too soon, it's crashing again :(

**Comment by flakey-bit** [comment]
[kodi_crashlog-20190815_201806.log](https://github.com/xbmc/xbmc/files/3505192/kodi_crashlog-20190815_201806.log)

Latest crashlog (this is with both packages @ bionic)

**Comment by localhoster** [comment]
Can confirm, but with Ubuntu 16.04. 
Also intel graphics. Crashes every time i am playing music with visualisation enabled after 20-30 minutes.

**Comment by AlwinEsch** [comment]
Are the crashes still present or no more occur? 
The issue is now old and not sure if still present, there was some fixes and updates in API and addons since them.

For now I close them, if still same problem present, give me info and I open again.
