### ISSUE TITLE
Kodi does not find The Handmaid's Tale

### ISSUE THREAD

**Issue by milankragujevic** [xbmc/xbmc#16515]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi does not find certain titles that are avilable on TMDB and TVDB. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi finds The Handmaid's Tale (2017) metadata.

## Actual Behavior

2019-08-19 19:25:24.479 T:1586492128  NOTICE: VideoInfoScanner: Starting scan ..
2019-08-19 19:25:24.846 T:1586492128 WARNING: No information found for item 'smb://192.168.1.200/Media120GB/TVShows/The Handmaid's Tale (2017)/', it won't be added to the library.
2019-08-19 19:25:24.900 T:1586492128  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00

### To Reproduce

1. Create folder "The Handmaid's Tale (2017)" and put a video file
2. Try scanning library

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC
 - Kodi version: v18

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HitcherUK** [comment]
Drop the year as it's not needed for either scraper and try again.

https://www.thetvdb.com/series/the-handmaids-tale

https://www.themoviedb.org/tv/69478-the-handmaid-s-tale?language=en-US

**Comment by DaVukovic** [comment]
I would also suggest to remove the `'` in `Handmaid's`

That's how I scraped it. 

But, tbh, isn't that more a support question for the forums rather than opening an issue on github. If one scraper might find it (TMDB) but the other one not (TVDB), then this might be worth opening an issue. For me this doesn't sound like a bug report.

**Comment by milankragujevic** [comment]
I had tried both without ' and without (2017), it didn't find it, thought I understand that this is not considered a bug report. In any case, I'll seek help on the forum. Sorry for the inconvenience caused.

**Comment by KarellenX** [comment]
Actually I think this is an emerging problem and I am seeing similar reports trickle into the forum as well as me being able to replicate the problem

@milankragujevic You should certainly open another bug report in the correct repo. Try here...

https://github.com/xbmc/repo-scrapers/issues

Similar report...
https://forum.kodi.tv/showthread.php?tid=346226&pid=2878576#pid2878576

**Comment by KarellenX** [comment]
@Rechi Can you move this to repo-scrapers and re-open?

**Comment by DaVukovic** [comment]
@milankragujevic 

Should be fixed by https://github.com/xbmc/repo-scrapers/commit/7f0cbd3e673107f70e84e351f1278f1f0965ea5c

That commit is in the TMDB scraper for tv shows version 3.1.3

At least it works now for me by using `The_Handmaid's_Tale` as a folder name. 

Thanks for reporting. :+1:

Please test and it would be nice if you could confirm it working. 

Thanks in advance.

**Comment by milankragujevic** [comment]
Hi, I'm sorry for the additional question, but how can I install the update, other than manually editing or replacing files? Check for updates yields no new version. This is OSMC armhf raspberrypi3b+

**Comment by DaVukovic** [comment]
[metadata.tvshows.themoviedb.org.zip](https://github.com/xbmc/xbmc/files/3520935/metadata.tvshows.themoviedb.org.zip)

Try this please

**Comment by DaVukovic** [comment]
[metadata.tvshows.themoviedb.org.zip](https://github.com/xbmc/xbmc/files/3520951/metadata.tvshows.themoviedb.org.zip)

This one please. 

Thanks

**Comment by milankragujevic** [comment]
It works. Thank you very much. Folder name is "The Handmaid's Tale (2017)". 

![63353234-ba38b280-c362-11e9-9716-da113b5c5b11.jpg](https://user-images.githubusercontent.com/7611163/63353234-ba38b280-c362-11e9-9716-da113b5c5b11.jpg)

**Comment by DaVukovic** [comment]
Cool thanks. Going to close that one then.
