### ISSUE TITLE
Importing video in kodi Movies Library using metatag

### ISSUE THREAD

**Issue by amirrammari** [xbmc/xbmc#16538]
Hi, Kodi team.
Kodi doesn't support MP4 metadata.
I tagging movies using [MetaX](https://www.danhinsley.com/) but my movies don't show in Kodi library.
iTunes supported MP4 metadata.
![MetaX](https://user-images.githubusercontent.com/23485114/63909509-29379a80-ca38-11e9-9c0c-50784025852a.png)

**Comment by amirrammari** [comment]
Now everythings working fine.
I must enable this option:
![image](https://user-images.githubusercontent.com/23485114/63909690-e0ccac80-ca38-11e9-9204-2bc423845778.png)

**Comment by amirrammari** [comment]
@KarellenX MP4 movies added in the library but MKV movies don't add in the library. Why?

**Comment by KarellenX** [comment]
@amirrammari 

Please read here... https://forum.kodi.tv/showthread.php?tid=345660&pid=2871492#pid2871492
