### ISSUE TITLE
Kodi Hard Windows Crash during resloution change

### ISSUE THREAD

**Issue by Mastercharger** [xbmc/xbmc#16537]
### Describe the bug
Here is a clear and concise description of what the problem is:

Whenever Kodi switches resolution between my 2 different screens (which have different resolutions) Kodi locks up and the computer freezes. 
The 2 screen resolutions are:  
Primary (1): 3840 x 2160 
Secondary (2): 1920 x 1018  

According to Kodi's GUI (and the debug logger) it recognizes the screen resolutions accordingly. 

Usually the freeze happens after a RDP session when the screens are off or when the computer has been inactive for some time. Instead of defaulting to  Screen 1 it then defaults to Screen 2 and forcing it back to Screen 1 results in the freeze.

The freese can be forced by switching between screen 1 and 2 repaitly as you can see in the debug logger. due to the nature of the freez there is no additional data than what the debug logger generates before the freeze

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
1. Not randomly changing to a default other screen when the underlying layout doesn't change
2. A crash of kodi itself rather then a freeze of the OS

## Actual Behavior

Whenever Kodi switches resolution between my 2 different screens (which have different resolutions) Kodi locks up and the computer freezes. 

## Possible Fix

A reset of the resolution and screen buffer if no reactions on the GUI for more than 15 seconds?

### To Reproduce

1.  Boot Kodi as normal
2. Switch rapitly betwean screens and accepting resolution changes 
2.1 after a number of try's the computer should lock up

3. Boot the computer as normal
4. let the computer become inactieve for an hour and try booting Kodi. if the GUI defaulds to the other screen force it back to the other screen.

### Debuglog

The debuglog can be found here:

[Kodi Debug.log](https://github.com/xbmc/xbmc/files/3552478/Kodi.Debug.log)
Note that the Freeze starts at "2019-08-28 20:38:19.695"

### Screenshots 
Here are some links or screenshots to help explain the problem:

Welp, I could make a picture of the screen but it wouldn't help mutch...

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: 

OS Name	Microsoft Windows 10 Pro
Version	10.0.17763 Build 17763
System Type	x64-based PC
Name GPU	NVIDIA GeForce GTX 1080
Driver Version	26.21.14.3160

 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by beigexperience** [comment]
I've also experienced this on a machine with 4 monitors with identical resolution. 

Instead if I force the app to go into windowed mode with right-alt+enter and move the window around with winkey+left/right it's fine. 

But if I change the display used from inside kodi while it's in fullscreen the whole OS hangs and stops registering input. This is on Windows 10 V.1903

**Comment by Mastercharger** [comment]
Issue #16981 dual monitor behaviour, seams to be related to this problem.
[https://github.com/xbmc/xbmc/issues/16981]

From what I can tell of the logs is that the application cant get resolution from one of the screens and defaults to one it can get. As soon as you then change the display output kodi will continuesly try to get the resolution of the other screen and crash in an infinite loop. At least that is my speculation.

@beigexperience, are you using a Nvidia or AMD graphics card?

**Comment by beigexperience** [comment]
@Mastercharger  
I'm using an NVidia GTX 1080TI. 
The latest kodi version i've used on this machine is KODI 17.6 GIT:20171114-A9A7A20
DirectX 11.1 (FL 11.1)
