### ISSUE TITLE
Crash when trying to add a timer

### ISSUE THREAD

**Issue by MagicOneFr** [xbmc/xbmc#16533]
### Describe the bug

I simply go to the TV section, Timers.
The list is empty.
I use "Add timer" and kodi crashes immediately.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No crash

## Actual Behavior

Crash

### To Reproduce

1. See above
2.
3.

### Debuglog

The debuglog can be found here:
[kodi_stacktrace-18.3 Git_20190619-89472b7d69-20190826-212342.txt](https://github.com/xbmc/xbmc/files/3542601/kodi_stacktrace-18.3.Git_20190619-89472b7d69-20190826-212342.txt)
[kodi_crashlog-18.3 Git_20190619-89472b7d69-20190826-212342.zip](https://github.com/xbmc/xbmc/files/3542605/kodi_crashlog-18.3.Git_20190619-89472b7d69-20190826-212342.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Could you please mention which PVR client you are using?

Thanks in advance

**Comment by MagicOneFr** [comment]
tvheadend htsp client 4.4.18 + PVR iptv simple client 3.7.2
