### ISSUE TITLE
Kodi crashes at sunset

### ISSUE THREAD

**Issue by realitylpma** [xbmc/xbmc#16544]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi crashes a few minutes after sundown. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should remain active and function normally regardless of the time of day.

## Actual Behavior

It freezes and crashes, and needs to be booted again.

### To Reproduce

1. 
2.
3.

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/viyehukefe

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Running on NVIDIA SHIELD Android TV with Android 8.0.0
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by realitylpma** [comment]
I have edited to follow the template!

**Comment by DaVukovic** [comment]
Try playing this shortly before sunset: https://youtu.be/RsKqMNDoR4o?t=130
(j/k ;) )

The log you provided is not a debuglog. And I highly guess Kodi does not care about the time of the day. It might be either some shutdown setting done in Kodi or at your Shield. At least this is the first report I heard of that Kodi cares about the time of a day. 

But please try to grab a debulog and provide that. 

Thanks in advance.

**Comment by KarellenX** [comment]
Is this your post... https://forum.kodi.tv/showthread.php?tid=345287

It is impossible to see how this could possibly be a bug. Millions of users and not a single report except for yours.

**Comment by realitylpma** [comment]
Hello everyone,

Thanks for the replies. If it’s not a bug, does anyone have an idea how/where to turn it off? I’ve looked at every single setting in both Kodi and the Shield, to no avail. Also, the Shield itself doesn’t seem to be performing any action, other than Kodi shutting down.

I have a smart light (LIFX) that is connected to Google Home and on the same network that is scheduled to turn on at sunset. However, the shutdown always happens a few minutes after the light turns out. Also, the issue was introduced with my Shield setup (I had a previous Android box and also briefly used Kodi on my Sony XBR900F).

@DaVukovic, I got this log by activating the Debug log function so I thought it would be sufficient. Are there additional steps I need to take? I know there is components logging that can be activated, but the instructions mentioned not to do that unless asked.

@KarellenX that is indeed my post.

**Comment by DaVukovic** [comment]
Sorry, missed the section where you enabled debug logging. 

But I'm a bit confused about that log anyway as it seems to be 2 months old. Are you sure Date and Time are set correct at the Shield and at Kodi? Also the timestamps are a bit confusing as they have big "jumps" where there shouldn't be any. But not so sure tbh

But to answer your question.... I don't have a clue why it crashes/closes each day at the same time. I can't see anything relevant in the logs. Maybe someone else does.

**Comment by realitylpma** [comment]
The log actually dates back to July, I generated it back then and haven’t pulled a more recent one. I can try to do that tonight.

I think the chain of events that lead to the shutdown/crash start at 20:44:54, towards the very bottom of the log.

**Comment by M2k80** [comment]
i have read on a german forum, there are ppl too that have had this problem, kodi, emby and other apps froce close at same time, they all have a nvidia shield, and it seems only a factory reset helped to stop this.
https://www.kodinerds.net/index.php/Thread/66539-Kodi-terminiert-auf-shield-jeden-Abend-zur-gleichen-Zeit/

**Comment by realitylpma** [comment]
I keep forgetting to generate a new log. I also want to try to do a factory reset when I have some time to devote to that. 

One interesting thing I've noted is that while it's linked to sunset, it seems to be getting further and further behind. Back when I generated the log in July, the crash happened more or less a minute after sunset. Today it was closer to 5 minutes later.

**Comment by thezoggy** [comment]
might be a IFTT recipe that is set to fire off at sunset....  what happens if you leave kodi running with no network?

**Comment by realitylpma** [comment]
I tried cutting off the network and the crash still happened. Haven't had time to properly do a factory reset, but will be looking into that hopefully soon.

**Comment by realitylpma** [comment]
Quick update: I finally got around to doing a full reset (I wish I hadn't held off for so long - I was convinced it would be a much longer process) and it seems the issue is gone. Thanks everyone for your help!

**Comment by KarellenX** [comment]
Great. Thanks for letting us know.
