### ISSUE TITLE
[pvr] If using channel order from backend sorting only by Number, name and last played

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#16546]
### Describe the bug
Here is a clear and concise description of what the problem is:

The sorting options for channels conflict with PVR options `Use channel numbers from backend` and `Use channel order from backend`. With both of this enabled there is no way to see the channels in the backend order as sort options are limited to Number, Name and Last Played. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Channels should show in the backend channel order.

## Actual Behavior

Channels do not show in the backend channel order.

### To Reproduce

1. Create a simple M3U file with 3 channels, setting tag-chno for each one in reverse order
2. Enable both `Use channel numbers from backend` and `Use channel order from backend`
3. Observe it is not possible to see the channels in backend order.

### Debuglog

The debuglog can be found here:

https://pastebin.com/ARppc3mK

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Example M3U

```
#EXTM3U
#EXTINF:-1 tvg-chno="3" group-title="Group1",Channel3
http://mystreamer.com:8000/live/ch3.ts
#EXTINF:-1 tvg-chno="2" ,Channel2
http://mystreamer.com:8000/live/ch2.ts
#EXTINF:-1 tvg-id=""ch1" tvg-chno="1" ,Channel1
http://mystreamer.com:8000/live/ch1.ts
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSX Mojave 14.14.6
 - Kodi version: Matrix Alpha

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Not sure I understand the problem.

 Do mean the backend could define a channel order which is independent from the numerical value of the backend channel numbers?

**Comment by phunkyfish** [comment]
Correct, that's it exactly. So maybe a 4th sort order like "Backend" or "Backend Order" is needed.

**Comment by phunkyfish** [comment]
So if you create a favourites group, and put the channels you want in there in the order you want (regardless of channel number) you probably won't be able to see them in that order.

**Comment by phunkyfish** [comment]
So settings iChannelNumber in PVR_CHANNEL_GROUP_MEMBER would not appear to have any effect due to the applied sorting.

**Comment by ksooo** [comment]
Wow, this is what I call an edge case feature. ;-)

=> easy part: CPVRChannel::ToSortable => new case for new sort field => m_clientChannelNumber

=> more advanced part: CPVREpgInfoTag::ToSortable => new case for new sort field => extend m_channelData to carry channel's client channel number (aka backend channel number) => use that

=> imo not so easy part: new sort field (to add somewhere outside pvr code, can't remember where exactly, sorry)

**Comment by phunkyfish** [comment]
Ok, got it. Let me give it a try.

**Comment by phunkyfish** [comment]
It’s the channel number from the group I want to use though right?

How would that work for all channels?

**Comment by ksooo** [comment]
For a channel contained in multiple groups, there is one dedicated CPVRChannel instance in every affected group, each Chanel instance is carrying the right per group backend channel number. At least this is what I remember. 😉

**Comment by ksooo** [comment]
No idea how that would work for the "all channels" group that gets created by Kodi.

BTW: if I only would find the time I would rewrite the whole channel and channel group code. It's unmaintainable in its current state and I try to avoid to touch that code, tbh.

**Comment by phunkyfish** [comment]
Ok, cool. Let me have a play and see how far I get.

Maybe we two of us having some knowledge of it will help if it ever does get rewritten.

**Comment by phunkyfish** [comment]
So I succeeded. In adding no new functionality.

Turns out sorting by backend channel number is already supported. I want to add support for sorting by backend channel order (aka, channel group member channel number). Not sure if that will be easier or not.

**Comment by ksooo** [comment]
> I want to add support for sorting by backend channel order (aka, channel group member channel number). Not sure if that will be easier or not.

 Not easier, as an API change is needed for that. You need to extend API struct `PVR_CHANNEL_GROUP_MEMBER` by something carrying the order, similar to `PVR_CHANNEL_GROUP`'s member 'iPosition', fill that in the addon and extend Kodi PVR core to support that. 

Is this feature really worth the effort?

**Comment by phunkyfish** [comment]
ChannelGroupMember contains a channel pointer and the number. I'm not sure there is a way to do this as I would need a reference to the current group from within the two ToSortable functions.

**Comment by ksooo** [comment]
> ChannelGroupMember contains a channel pointer and the number

 Not sure that we are on the same page. I thought you want to define a sort order for channels in the addon/backend which is independent from the backend channel number.

channel "A", number "1", order "3"
channel "B" number "2", order "2"
channel "C" number "3", order "1"
=> order by backend channel order, ascending: C, B, A
=> order by backend channel order, descending: A, B, C
(number is ignored, sort criteria is order)

If I got the exercise right, we currently do not have a struct that has an "order" member, only "number". This, we need to extend the struct, no?

**Comment by phunkyfish** [comment]
There shouldn’t be an API change needed. `iChannelNumber` in `PVR_CHANNEL_GROUP_MEMBER` is the position in that group I believe.

**Comment by phunkyfish** [comment]
I think channel number in group member is a misleading name. It would be better named position.

**Comment by ksooo** [comment]
> iChannelNumber in PVR_CHANNEL_GROUP_MEMBER is the position in that group I believe.

> I think channel number in group member is a misleading name. It would be better named position.

 I don't think so. It's actually ment to be the number, not position. That's why I'm saying we need to add "position".

**Comment by phunkyfish** [comment]
So `iChannelNumber` in `PVR_CHANNEL_GROUP_MEMBER` is independent of backend channel number.

**Comment by ksooo** [comment]
Nope.

**Comment by ksooo** [comment]
Let's ask @AlwinEsch . Maybe he knows.

**Comment by ksooo** [comment]
I think the idea was that a channel can have different channel numbers in every group it was added to.

**Comment by phunkyfish** [comment]
> Not sure that we are on the same page. I thought you want to define a **sort order** for channels in the addon/backend which is **independent from the backend channel number**.
> 
> channel "A", backend number "1", order "3"
> channel "B" backend number "2", order "2"
> channel "C" backend number "3", order "1"
> => order by backend channel order, ascending: C, B, A
> => order by backend channel order, descending: A, B, C
> (backend number is ignored, sort criteria is order)
> 

What's above is exactly what I want to achieve.

Even if we have an order value in group member we still have the problem that the UI is sorted by channel data (both by channels and EPGInfoTags). So we would need a way to retrieve the order value from the corresponding member of the current group on the UI to be able to sort the channels. Or am I thinking about this completely backwards.

**Comment by ksooo** [comment]
> So we would need a way to retrieve the order value from the corresponding member of the current group on the UI to be able to sort the channels. Or am I thinking about this completely backwards.

 I guess you are right.

**Comment by phunkyfish** [comment]
Hmmm, so ChannelGroup can already sort its members correctly. 

I wonder can the sort options on the left menu just not sort at all. Cause then the order would likely be correct.

**Comment by AlwinEsch** [comment]
Have looked over it, it can definitely confirm. Unfortunately, I'm just out of the system of processing a little bit out and can not say directly which point must be taken exactly.

**Comment by phunkyfish** [comment]
Ok, so I've set everything up to sort by the order on the backend, pulling the group member channel id (which I'm using for the order). However this does not equal the value set in the addon in `GetChannelGroupMembers` which it should. It is just set to the same number as the channel number. 

Now trying to find out why that is ;)

**Comment by phunkyfish** [comment]
So I got this working but instead of extending the API I just used the creation order for the value. I see what you mean about maintainability. I may be missing pieces I'm not aware of. Let me when you get a chance to have a look at the PR which I raise shortly.

**Comment by ksooo** [comment]
> instead of extending the API I just used the creation order for the value.

 Why do you hack around? Who guaranties that the order is maintained while transferring data from the addon to Kodi?

 We have so many time until Matrix release. I suggest to come up with a clean implementation in the first way.

**Comment by phunkyfish** [comment]
Sure, let me add the API changes for group member.

For the `all channels` group I could add a similar value to channnel.

Then there are zero hacks.

**Comment by ksooo** [comment]
> Then there are zero hacks.

 Despite from the design breakage I pointed out in the code review of the PR. Still some more work to do, unfortunately. ;-)
