### ISSUE TITLE
Can not scrap some TV show due to JSON field order in TheMovieDB not matching Kodi expected order

### ISSUE THREAD

**Issue by schodet** [xbmc/xbmc#16540]
### Describe the bug
Here is a clear and concise description of what the problem is:

I try to scrap data for the Maisy (1999) (Mimi in french) TV show using TheMovieDB scrapper, but Kodi wrongly scrap data for 미미 (2014) (Mimi in english). If I try to refresh from the information page, the list does not include my TV show while it is available on TheMovieDB site, and I can see it in the API response captured with wireshark. Other TV shows are missing from the list.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should find the good TV show and give me the complete list when I try to refresh.

## Actual Behavior

It does not find my TV show and the list given on refresh is not complete.

## Possible Fix

I read the `addons/metadata.tvshows.themoviedb.org/tmdb.xml` file and I think there is a problem because it expects the field of the JSON response in a specific order, which does not match the field order in the response.

### To Reproduce

1. Have a TV show named "Mimi (1999)"
2. Set the scrapping language as French
3. Update the database

Also:

4. Select the wrongly scrapped TV show
5. Go to information page
6. Refresh -> all episodes -> no local data

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ecizesunum.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

No screenshot, I can provide it if not clear enough.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The TV show: Maisy (1999), Mimi in french

The HTTP exchange capture: https://paste.kodi.tv/ugabevilil
Same thing, but formatted JSON response: https://paste.kodi.tv/yetocacale
The XML result from Kodi log: https://paste.kodi.tv/uhologorag

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian GNU/Linux 9 (stretch)
 - Kodi version: 17.1 Debian package version: 2:17.1+dfsg1-3)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
I cannot replicate your problem.

Your log is incomplete. FULL LOGS ONLY!!!!

**Comment by schodet** [comment]
The RegExp (here: https://github.com/xbmc/xbmc/blob/master/addons/metadata.tvshows.themoviedb.org/tmdb.xml#L41) expect the JSON fields in a specific order, but TheMovieDB is free to return them in any order (https://paste.kodi.tv/yetocacale). It does not match.

There are several reports of problems in the forum, I think are related to the same problem:
- https://forum.kodi.tv/showthread.php?tid=200504&pid=2879883#pid2879883
- https://forum.kodi.tv/showthread.php?tid=346700

I used ctrl+shift+d around the problem, but I can dump a full log if you like. I can even run a Kodi directly from the kodi web site. However, I think I have shown the reason of the problem.

**Comment by KarellenX** [comment]
> I can dump a full log if you like.

Really???????? How many times do I need to ask for it???

**Comment by KarellenX** [comment]
Cannot replicate. Issue closed.

**Comment by schodet** [comment]
Here is a full log: https://paste.kodi.tv/wajojeneve.kodi

**Comment by KarellenX** [comment]
I cannot replicate your issue.

Here is my log. Scrape at Line 1007... https://paste.kodi.tv/lijuviveka.kodi Let me know if you spot a difference.

Though I do agree there is an emerging issue with foreign content, I do not think this is part of that issue. But the developer @olympia will need to look closer to confirm.

**Comment by olympia** [comment]
@KarellenX the latest fixes for the scraper has not been back ported to Krypton. 
You are using Leia, schodet is using Krypton, hence the difference...

I will see if I can find the time... Till then, upgrade to Leia...

**Comment by schodet** [comment]
Thanks for trying to reproduce.

You have version 3.1.3 of the scrapper, I have 2.0.8… It may be the
difference.

**Comment by schodet** [comment]
Ok this was fixed here: https://github.com/xbmc/repo-scrapers/commit/7f0cbd3e673107f70e84e351f1278f1f0965ea5c

I am surprised that this is not on kodi master branch, but I am not familiar with kodi dev rules.

**Comment by KarellenX** [comment]
Thanks @olympia I did not realise that a backport was not submitted. 

I should have paid closer attention :)

**Comment by DaVukovic** [comment]
@schodet 

Just to clarify...

1. you reported a bug to Kodi where you have a problem with a scraper. Hence it should be reported to the scraper addon which you found already. Hence this report is closed, because it's not a "Kodi" issue, but a scraper issue. So it's reported at the wrong place. 

2. The PR you linked is for the scraper add-on which is used in Kodi Leia. As you are using Kodi Krypron you are only able to get the current scraper add-on version 2.0.8 for that Kodi version. If you upgrade to Kodi Leia you will also receive an update for this add-on being 3.1.3 then. 

3. 
> I can even run a Kodi directly from the kodi web site
You can't while using Debian (beside you compile Kodi from source). The Debian repositories are not providing Kodi 18.x AFAIK. You will probably get Kodi 17.6 but that would not change anything for you, as that's still Kodi Krypton so the scraper version you will get will still be 2.0.8. If olympia has backported the changes to the Krypton branch of the scraper add-on, then you are able to benefit from that. 

So you have 3 options now: 

- take it as it is, wait and hope that olympia will find the time to fix it
- compile Kodi 18.3 from source by selecting the specific branch (then you will also receive an update for that scraper)
- switch your distro to Ubuntu so you are able to install Kodi from the Kodi PPA in case you can't/won't compile from source (you will receive an update for the scraper add-on as well).

**Comment by schodet** [comment]
Just to clarify:

- I am here to help, not to fix _my_ problem. I have work around the problem on my installation with an tvshow.nfo file anyway.
- I had a problem with scraping on my Kodi installation. After having tracked down the problem, I have seen that:
    - several people seems to have the same problem on the forum,
    - they don’t seems to have a solution,
    - the file on this repository stills have the bug, I did not know there was another authoritative copy in another repository.
- Therefore, I opened an issue after having read many pages on the wiki and forum to try to do it the right way, I included targeted information on what I considered was wrong so that a member of the project could come with an easy fix.

If I was wrong, may I suggest some changes:

- https://github.com/xbmc/repo-scrapers/blob/master/CONTRIBUTING.md says: "Do not open an issue on Github for your questions or bug reports.", is it still right?
- on https://kodi.wiki/view/Bug_tracker there is no mention of a different bug tracker for kodi team add-on, may be it should be added.

I think I can come up with a fix for the Krypton branch if nobody is working on it yet.

**Comment by KarellenX** [comment]
Sure, I understand you are here to help. Thank you.

Are your comments in relation to the Issue being closed? The developer @olympia is aware of the issue and will backport the fix when time is available. Would you prefer it reopened?

Ideally, this issue should be raised in the appropriate repository here... https://github.com/xbmc/repo-scrapers. Unfortunately I do not have the required permission to move Issues between repositories.

**Comment by schodet** [comment]
It's written in https://github.com/xbmc/repo-scrapers/blob/master/CONTRIBUTING.md that issues should not be reported there, so who is right?

**Comment by DaVukovic** [comment]
I installed Kodi 17.6 and I could reproduce your problem

Could you please check if this version of the scraper fixes your problem

[metadata.tvshows.themoviedb.org.zip](https://github.com/xbmc/xbmc/files/3568094/metadata.tvshows.themoviedb.org.zip)

I did the same changes Olympia did for the Kodi 18 scraper version and it works for me

If it works for you I'll PR it

**Comment by phunkyfish** [comment]
@schodet, what the contributing doc means is to please open the issue against the repo for your specific scraper addon on not this repo.

Think of repo-scrapers as a collection of all the scrapers.

**Comment by schodet** [comment]
@DaVukovic it does work, I have actually done the same change here :)

**Comment by DaVukovic** [comment]
cool. thanks for the confirmation. 

I'll PR it

**Comment by schodet** [comment]
Cool, thanks.

**Comment by DaVukovic** [comment]
Fixed and merged by the mentioned PR

Users should receive an update soon
