### ISSUE TITLE
Video playback error in other apps after playing content in Kodi App.

### ISSUE THREAD

**Issue by saiga006** [xbmc/xbmc#16543]
### Describe the bug
Here is a clear and concise description of what the problem is:

Video Playback error happens in other apps after playing a content in Kodi Android Tv App.
After Playing a local content from USB/ any online content from repository in Kodi, switch to youtube or any video playing capable app, the first video doesn't play with a black screen appears. Video playback (in other app) recovers only after playing second video. This is seen only after playing content in Kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video playback should happen in other apps too, irrespective of switching from kodi while content is played in it. 

## Actual Behavior

Video playyback fails in other apps, while switching when video is played in kodi app 

## Possible Fix

During initial debugging, found that video decoder resource is not been released by Kodi even after switching to other apps. Its been held in the background. So proper video decoder release when the app is switched to background may fix this issue 

### To Reproduce

1. Play any content in Kodi Tv App
2. Switch to Any video playback capable app, while the content is playing in kodi.
3. Play any video in other app like youtube and observe the black screen behavior in youtube / any video playback app.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [*] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android OS Pie 
 - Kodi version: Kodi Android Tv App v18.3 -Leia Git:20190619-89472b7d69 Compiled: 2019-06-28

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
No log, no further information. Issue closed
