### ISSUE TITLE
getPremiered() returns the same date as getFirstAired() for seasons

### ISSUE THREAD

**Issue by vitorp07** [xbmc/xbmc#16549]
### Describe the bug
Here is a clear and concise description of what the problem is:

After adding tv shows to the library, when looking at the "season_view" table in the database, the "premiered" column gets populated with the tv show's release date while the "aired" column gets populated with the season's release date.

From a context item add-on, trying to get the tvshow's release date from a season item in the library with
sys.listitem.getVideoInfoTag().getPremiered() always returns the season's release date, same as  sys.listitem.getVideoInfoTag().getFirstAired() instead of the tv show's release date but doing the same on a season item from a video add-on returns the expected tvshow's release date.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

sys.listitem.getVideoInfoTag().getPremiered() returns the tv show's release date for season items

## Actual Behavior

In the library sys.listitem.getVideoInfoTag().getPremiered() always returns the season's release date, same as  sys.listitem.getVideoInfoTag().getFirstAired()

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
No log provided, no further comments since a month. Issue closed
