### ISSUE TITLE
Event Server is no no longer working for certain key presses on certain windows. 

### ISSUE THREAD

**Issue by SireGoatMonkey** [xbmc/xbmc#16548]
### Describe the bug
Here is a clear and concise description of what the problem is:

Depending on what Window is currently active, the EventServer is no longer handling all button presses.  For example, if I send a "right" or "down" button on the main screen.  Both work fine.  However, if I send a "down" when playing a video full screen, it does not work.  These are just two examples.  There are several buttons that don't work depending on the window.  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

While a video is playing in full screen, when I send a Button press packet of "down", I expect Kodi to respond with whatever action is in the keyboard mapping.  In this case it's the default of 'ChapterOrBigStepBack'.

## Actual Behavior

While a video is playing in full screen, when I send a button press packet of "down", Kodi does not respond at all.  However, other button presses like "right" do respond correctly.

Looking at the log file, I see that the EventServer is receiving and successfully parsing the "down" packet:
2019-08-30 13:55:36.540 T:2707399536   DEBUG: EventClient: button code 129 pressed.

However, it doesn't seem to follow it with the expected "HandleKey" entry.
For contrast, if I send a "right" packet, I see both the "EventClient" entry AND the HandleKey entry:
2019-08-30 13:55:37.541 T:2707399536   DEBUG: EventClient: button code 131 pressed
2019-08-30 13:55:37.543 T:3011700048   DEBUG: HandleKey: right (0xf083) pressed, action is StepForward

## Possible Fix

I pulled the code but can't for the life of me see anything wrong.  It looks like it should work.  It does seem like the key presses that aren't working are any that have a mod="longpress" line?

### To Reproduce

1. Ensure Kodi is running
2. Ensure Event Server is enabled
3. Start playing a video.
4. Send a "right" button press.  Using either the button name or button code.
5. Notice that the video skips forward.
6. Now send a "down" button press.  Using either the button name or button code.
7. Notice the video does not respond.

I am using C# to send the packets using the C# client example on this github.
        static void Main(string[] args)
        {
            EventClient eventClient = new EventClient();
            eventClient.Connect("192.168.1.123"); 
            eventClient.SendButton("right", "KB", ButtonFlagsType.BTN_DOWN | ButtonFlagsType.BTN_NO_REPEAT | ButtonFlagsType.BTN_VKEY, 0);
            System.Threading.Thread.Sleep(1000);
            eventClient.SendButton("down", "KB", ButtonFlagsType.BTN_DOWN | ButtonFlagsType.BTN_NO_REPEAT | ButtonFlagsType.BTN_VKEY, 0);
            System.Threading.Thread.Sleep(1000);
            eventClient.SendButton(0x81, ButtonFlagsType.BTN_DOWN | ButtonFlagsType.BTN_NO_REPEAT | ButtonFlagsType.BTN_VKEY, 0);
            System.Threading.Thread.Sleep(1000);
            eventClient.SendButton(0x83, ButtonFlagsType.BTN_DOWN | ButtonFlagsType.BTN_NO_REPEAT | ButtonFlagsType.BTN_VKEY, 0);
            System.Threading.Thread.Sleep(1000);
            eventClient.Disconnect();
        }

### Debuglog

The debuglog can be found here:
https://pastebin.com/m82i4cde

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Leia 18.3/LibreElect 9.1.002

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
The kodi eventserver (kodi-send) is not a keyboard. It simply sends built in functions to Kodi whereever those can be used or not. 

In case of the homescreen navigation you call "Down" here: https://github.com/xbmc/xbmc/blob/master/system/keymaps/keyboard.xml#L37

which is `<down>Down</down>` So you do not call a keypress "down" instead you call the Action "Down" (the one that is in the middle of the `<down>....</down>` tags. 

"Down" as an action, is not defined while Kodi is in `Fullscreenvideo`. The keypress "down" is defined to be `ChapterOrBigStepBack`. See: https://github.com/xbmc/xbmc/blob/master/system/keymaps/keyboard.xml#L371

So in order to do that via "kodi-send" you have to call it via `kodi-send -a "ChapterOrBigStepBack"` as down as a function is not defined in that window. 

So this is not a bug, but a misunderstanding how "kodi-send" works (or not ;) ). 

Closed

**Comment by SireGoatMonkey** [comment]
Thanks for the clarification!  Just a few questions.  Did this change with Leia?  Because it worked with button presses from Isengard to Krypton.  Also, that doesn't quit add up.  I'm aware I can send Actions, but I was pretty sure I could send a button presses with the name of the key map to use.

See the comments at:
https://github.com/xbmc/xbmc/blob/6fcbb13a90d8cd9782e4bfaee9ea19459e7aa45d/tools/EventClients/lib/c%23/EventClient.cs Line 350

Looking at the code, it also looks like the EventClient class very much can handle either Actions or Buttons.  See the OnPacketBUTTON and OnPacketACTION methods in the EventClient class.  Both of which are called by the ProcessPacket method.
https://github.com/xbmc/xbmc/blob/770c691bfeea88d561b39d2e38348ac434db3adc/xbmc/network/EventClient.cpp  Line 208

It can tell which of those method it should call by the packet type(from the Type property of the CEventPacket).  CEventPacket is constructed by parsing the actual byte array received over the wire.  Blah, blah, blah.  I already feel like I'm getting too verbose.  But looking at the code, and tracing the path of the logic, it **does** seem to look at a keymapping to determine the action. Though it's very possible I'm misreading it.

But, the final nail in the coffin that makes me think it can handle button presses is in the behavior of sending a 'right' when in FullScreenVideo.  As can be seen in the log file I pasted above. 

You can see where I send a "right" with the EventServer(kodi-send).  And it gets translated into a StepForward:
2019-08-30 13:55:34.539 T:2707399536   DEBUG: EventClient: button code 0 pressed
2019-08-30 13:55:34.543 T:3011700048   DEBUG: HandleKey: right (0xf083) pressed, action is StepForward

In that example I sent the 'name' of the button.  But in the same log file you can see, a few seconds later, I also sent the button code for 'right'.
2019-08-30 13:55:37.541 T:2707399536   DEBUG: EventClient: button code 131 pressed
2019-08-30 13:55:37.543 T:3011700048   DEBUG: HandleKey: right (0xf083) pressed, action is 

Both work. However, if I sent a 'down'.  It doesn't work.  Either with the button code:
2019-08-30 13:55:36.540 T:2707399536   DEBUG: EventClient: button code 129 pressed
2019-08-30 13:55:36.615 T:2542408560   DEBUG: CDVDClock::ErrorAdjust - CVideoPlayerAudio::OutputPacket - error:34029.887933, 
or with the button name:
2019-08-30 13:55:35.540 T:2707399536   DEBUG: EventClient: button code 0 pressed
2019-08-30 13:55:35.551 T:2585785200   DEBUG: CMMALPool::Configure pool:0xb2f29570 1920x800 (1920x800) pix:-1 size:128 fmt:OPQV

I got the button code by looking at the line 199 of https://github.com/xbmc/xbmc/blob/770c691bfeea88d561b39d2e38348ac434db3adc/xbmc/input/XBMC_keytable.cpp

Anyway.  Let me know where I'm off.  Or, as I suspect, if there is an actual bug.  Thanks for the speedy reply to the original post.  And a huge thanks to everyone actively working on KODI!!!!  You guys are awesome!!

**Comment by SireGoatMonkey** [comment]
I'm still a bit salty this was ignored/dismissed.  The readme for event server itself says it handles button/key presses.

https://github.com/xbmc/xbmc/blob/master/tools/EventClients/README.txt
