### ISSUE TITLE
Clean library on startup 

### ISSUE THREAD

**Issue by amirrammari** [xbmc/xbmc#16556]
Hello, Kodi can't clean my library on startup
Please add a feature for this issue (for example below option):
![Kodi Settings](https://user-images.githubusercontent.com/23485114/64076644-8f444c00-ccdc-11e9-8170-205458b79013.jpg)

**Comment by DaVukovic** [comment]
@amirrammari 

Hello, please follow the template and provide at least a debuglog which shows that Kodi can't clean the library. Otherwise this issue will be closed in 7 days. 

Thanks in advance

**Comment by KarellenX** [comment]
@amirrammari 

As previously advised, the Issues section is for BUG reports. It is not a place for Feature Request.

Use the forum.

If you insist on continuing to misuse this reporting facility, we will need to block you.
