### ISSUE TITLE
feature_python3 - not compatible with Python 3.8

### ISSUE THREAD

**Issue by mooninite** [xbmc/xbmc#16560]
### Describe the bug
Here is a clear and concise description of what the problem is:

xbmc/interfaces/python/PythonInvoker.cpp

There are a three references in the file above to the private interfaces of PyInterpreterState.

Example:

    s = state->interp->tstate_head;

Python 3.8 has finally removed the public interfaces to PyInterpreterState. The C documentation has always stated that there were never any public interfaces but projects such as Kodi used them anyway.

Announcement:
https://mail.python.org/pipermail/python-dev/2019-February/156344.html

Bug tracker to request a public interface:
https://bugs.python.org/issue35886

## Possible Fix
Work with upstream to create a real public interface.

Workaround:

Adding the following to the top of PythonInvoker.cpp will expose the structs again.

    #if PY_VERSION_HEX >= 0x03080000
    # define Py_BUILD_CORE
    # undef HAVE_STD_ATOMIC
    /* for access to the fields of PyInterpreterState */
    #  include "internal/pycore_pystate.h"
    # undef Py_BUILD_CORE
    # define HAVE_STD_ATOMIC
    #endif

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.4 / 19.x

**Comment by mooninite** [comment]
Please remove the "Ignored rules" label.

**Comment by louiestevenson** [comment]
window.YTD.direct_message.part0 = []

**Comment by yol** [comment]
Thanks @ronie

However I'd prefer not to have this closed since it is not really fixed and it will bite us again when they stop installing the internal headers
