### ISSUE TITLE
[gdb bt] kodi doesn't start on raspi1 because of total deadlock of all threads

### ISSUE THREAD

**Issue by ProhtMeyhet** [xbmc/xbmc#16566]
### Describe the bug
Here is a clear and concise description of what the problem is:

on a raspi1 kodi doesn't start because of a deadlock of all threads. attached please find a `bt full` of each thread.

```bash
[Current thread is 1 (Thread 0x71822a40 (LWP 850))]
  Id   Target Id                                     Frame 
* 1    Thread 0x71822a40 (LWP 850) "kodi-rbpi"       0x76f46b14 in __pthread_mutex_lock_full () from /usr/lib/libpthread.so.0
  2    Thread 0x7181f140 (LWP 855) "Announce"        0x76f4b260 in pthread_cond_wait@@GLIBC_2.4 () from /usr/lib/libpthread.so.0
  3    Thread 0x70eff140 (LWP 856) "Lirc"            0x76f4b63c in pthread_cond_timedwait@@GLIBC_2.4 () from /usr/lib/libpthread.so.0
  4    Thread 0x706fe140 (LWP 857) "libinput"        0x75a86280 in epoll_wait () from /usr/lib/libc.so.6
  5    Thread 0x6fcff140 (LWP 858) "ActiveAE"        0x76f4b63c in pthread_cond_timedwait@@GLIBC_2.4 () from /usr/lib/libpthread.so.0
  6    Thread 0x6f4fe140 (LWP 859) "AESink"          0x76f4e134 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  7    Thread 0x6ecfd140 (LWP 860) "FDEventMonitor"  0x75a7b990 in poll () from /usr/lib/libc.so.6
  8    Thread 0x6a4fc140 (LWP 865) "VCHIQ completio" 0x75a7e13c in ioctl () from /usr/lib/libc.so.6
  9    Thread 0x6e375140 (LWP 866) "HDispmanx Notif" 0x76f4e134 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  10   Thread 0x6db74140 (LWP 867) "HTV Notify"      0x76f4ef44 in __lll_lock_wait () from /usr/lib/libpthread.so.0
```

## Expected Behavior
kodi should start

## Actual Behavior
kodi deadlocks

### To Reproduce
1. start kodi with --standalone
2. ??
3. gdb attach ...

### Your Environment
Used Operating system:

 - [x] Raspberry-Pi

 - Operating system version/name: arch linux (fully updated)
 - Kodi version: `alarm/kodi-rbp-git 18.2rc1.20190415-2 [installed]`
it's the same with `alarm/kodi-rbp 18.4-1`

**Comment by ProhtMeyhet** [comment]
[kodigdb.txt](https://github.com/xbmc/xbmc/files/3572327/kodigdb.txt)

**Comment by ProhtMeyhet** [comment]
> This is an automatically generated message. If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.

i have deleted the comments, because they were annoying and left out what was unneccesary. otherwise i followed your template.

**Comment by popcornmix** [comment]
You haven't included a debug enabled log file.
This should probably be directed at arch maintainers to confirm if their build has been tested on a Pi1.
Kodi does run on Pi1 with some builds (e.g. LibreELEC), but I'm not familiar with arch builds.
