### ISSUE TITLE
[pvr] Group specific backend channel numbers not used on UI

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#16562]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using backend channel numbers for a PVR backend both the channel itself has a backend channel number and also possibly in addition the group member does. In the case the channel number is set in the group member (via the addon) it does not appear to be used or displayed in the UI.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If a channel number is set by the addon for the group member it should be displayed in the UI.

## Actual Behavior

Only the backend channel number set on the channel is displayed in the UI.

## Possible Fix

I spotted an issue on the backend that would cause this not to work however I wonder how the UI displays them on estuary. My skin knowledge is limited.

### To Reproduce

1. Use an an addon such pvr.vuplus where different groups have different channel numbers than main channels.
2. Flip between groups on PVR Guide UI
3. Channel numbers from group members are not displayed.

### Debuglog

The debuglog can be found here:

https://pastebin.com/dHKzGynk

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSX 10.14.6
 - Kodi version: Matrix Alpha 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by phunkyfish** [comment]
I thought this function would be called to populate channel numbers on the guide  UI but I don't think it ever is.

https://github.com/xbmc/xbmc/blob/7405d260471212b58c517a9c06e58d2e3da1ad65/xbmc/pvr/windows/GUIWindowPVRGuide.cpp#L761-L766

So not sure how they get populated.

**Comment by phunkyfish** [comment]
It's set here: https://github.com/xbmc/xbmc/blob/7405d260471212b58c517a9c06e58d2e3da1ad65/xbmc/pvr/PVRGUIInfo.cpp#L653

**Comment by ksooo** [comment]
@phunkyfish i think this Issue can be closed?

**Comment by phunkyfish** [comment]
Fixed by referenced issue above.
