### ISSUE TITLE
Consistent random crashes

### ISSUE THREAD

**Issue by JannemanDev** [xbmc/xbmc#16561]
### Describe the bug
Here is a clear and concise description of what the problem is:

The crashes appear random but are pretty consistent. It crashes after a few hours of use for example when watching a serie or movie but also when just simply navigating the interface.
The crash is not because of a specific user action.
I have had these crashes for multiple months. In that time I have used versions v18.1, v18.2, v18.3 and v18.4. The debug log's are from v18.3 and v18.4.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should not crash :)

## Actual Behavior

Kodi and my NVidia Shield crashes hard. I have to unplug the power of the NVidia Shield so it reboot's.

### To Reproduce

1. Just use Kodi for several hours for example watching movies or using the interface, it doesn't matter what you do.
2. Hard crash will occur

### Debuglog

The debuglog can be found here:

I have 4 debug log's each from right after a crash.
[kodi crashlogs.zip](https://github.com/xbmc/xbmc/files/3568201/kodi.crashlogs.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: NVIDIA SHIELD Android TV with Android 9.0.0 API level 28, kernel: Linux ARM 64-bit version 4.9.140-tegra-g8e6798163e77
 - Kodi version: v18.1 - v18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Could you please try to disable anything PVR related and see if it still crashes. The last lines in those logs always mentioning something PVR related

@ksooo could it be PVR related?

**Comment by JanOonk** [comment]
yeah noticed that also... but thats because TV Mosaic is triggered every minute :)

I just found something about this common problem on Shield... the fix what I am reading about talks about increasing the shield logging to the maximum:
-Settings > Device preferences > About > Build (select it several times to unlock developer options 
-Settings > Device preferences > Developer Options > Logger Buffer Sizes > I increased it from 256Kb to 16MB. 

Hopefully this will fix it. I will update this ticket coming days.

**Comment by JanOonk** [comment]
I promised an update:
After the updated log buffer size setting, Kodi was stable for about 2 weeks then suddenly I experienced the same problem for a few days with multiple crashes on one day (never had that before), and now it's stable again for like 4 weeks. 
Also recently the Shield got updated from 8.0 to 8.01
So I really dont have a clue whats going wrong here... But nevertheless this updated log setting is much better than the old lower value.
