### ISSUE TITLE
Kodi 18.4 does not skip commericals

### ISSUE THREAD

**Issue by doktourtv** [xbmc/xbmc#16564]
### Describe the bug
Here is a clear and concise description of what the problem is:

18.4 release does not skip commercials on playback from "recordings" button

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If a valid .edl file exists in the same directory as the video, then commercials should be skipped on playback. 18.4 never reads the .edl file (see debug log)

## Actual Behavior

On playback from the 'recordings' button, the .edl file should be read and the commercials should be skipped.

## Possible Fix

18.3 did NOT have this problem so something changed between 18.3 and 18.4. Possibly revert back to 18.3 code for the recordings playback.

### To Reproduce

1. Ensure kodi 18.4 is installed
2. Create a valid .edl file for the recorded video (I use comskip)
3. Play the video from the 'recordings' button and the commericals will not be skipped

### Debuglog

The debuglog can be found here:
18.4 not reading edl file found here: https://pastebin.com/bm16xrJi
For comparison:
18.3 properly reading edl file for same recording found here: https://pastebin.com/6svNXgUW

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

In comparing the debug log from 18.3 to 18.4, it is clear the .edl file is never read in 18.4

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Professional 
 - Kodi version: 18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by emveepee** [comment]
Testing with Win64 with 18.4 nightlies EDL support in the Video Library broke starting with

KodiSetup-20190730-7a48397b-Leia-x64.exe

Martin.

**Comment by DaVukovic** [comment]
@emveepee So you say, by reverting the mentioned commit `7a48397b` EDL works?

That commit seems not even related to the current topic

https://github.com/xbmc/xbmc/commit/7a48397b

**Comment by emveepee** [comment]
No I am saying 7a48397b doesn't support EDL files.  I didn't check which commit after d092fd29 breaks it.

**Comment by Rechi** [comment]
> EDL support in the Video Library broke starting with KodiSetup-20190730-7a48397b-Leia-x64.exe

So with KodiSetup-20190728-62786e3a-Leia-x64.exe it works as expected?

**Comment by emveepee** [comment]
With KodiSetup-20190728-62786e3a-Leia-x64.exe and the later KodiSetup-20190729-d092f92d-Leia-x64.exe comskip works as expected.  I see EDL's being read for files

2019-09-03 21:09:12.921 T:8448   DEBUG: CEdl::ReadEditDecisionLists - Checking for edit decision lists (EDL) on local drive or remote share for: K:\The Strain\Season 01\The Strain.S01E13.The Master.ts

logs are similar to those posted with the thread for PVR recordings.

Martin

**Comment by jsnj** [comment]
Since this bug report specifies Windows OS, I just wanted to point out that I had the same issue on nVidia Shield Android 9 using the mythtv pvr plugin. Had to revert back to Kodi v18.3 for commercial detection to work.

**Comment by phunkyfish** [comment]
Ok, so the EDLs are never read in the 18.4 log. They should be read here:

https://github.com/xbmc/xbmc/blob/8b4547955bb8f1f19792ce660f4e139888eee68b/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L3603-L3610

So for some reason `hint.fpsrate > 0 && hint.fpsscale > 0` is false so they are never read.

@FernetMenta could this be related to https://github.com/xbmc/xbmc/commit/9a6a4ec80743de6bae16e601d80db73e0b4dfaa3 and it's subsequent revisions?

**Comment by ksooo** [comment]
Dors reverting the commit in question fix the edl problem?

**Comment by phunkyfish** [comment]
The two most recent commits would need to be reverted to check this as they are dependent on each other. I'll need to do a full rebuild of Leia to verify this which will take me some unless @emveepee can do this easily?

**Comment by phunkyfish** [comment]
Will kick off the build anyway.

**Comment by phunkyfish** [comment]
Or maybe not:

https://github.com/xbmc/xbmc/blob/3ade758ceb0f8fe6d0cb7f2dcd758c873c80cb1f/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L3707-L3724

Hmmm...

**Comment by phunkyfish** [comment]
So if I revert both 0338e992ff63acb598b71df1a9bfb8535ee42d53  9a6a4ec80743de6bae16e601d80db73e0b4dfaa3 the issue does not occur.

**Comment by phunkyfish** [comment]
I have a workaround, the defaults only kick in for the code snippet above it you have a fallback frame rate set for PVR (50 or 60hz):

![Screenshot 2019-09-05 at 09 50 24](https://user-images.githubusercontent.com/4601187/64326865-9dd38180-cfc2-11e9-87c1-4c9258ba1824.png)

Should allow users to get past this as we figure out how to correctly set `hint.fpsscale` and `hint.fpsrate`.

**Comment by doktourtv** [comment]
On Windows 10 with frame rate set to NONE there still appears to be no read of edl file.
Here is debug log: https://pastebin.com/bTMSTYyk

**Comment by a1rwulf** [comment]
That's what @phunkyfish said above.
Set it to 50Hz as a workaround.

**Comment by emveepee** [comment]
This issue impacts playback from the Video Library too.   I made the PVR change to 50Mhz and still no EDL file loaded in the library playback.

@phunkyfish I tried to build the Leia branch yesterday for Win x64 but the build system is not working for me.  Complaints about java -version in cmake and python_binding.lib.

**Comment by phunkyfish** [comment]
EDL from any location is affected. The code is common to both code paths.

@FernetMenta, any hints on the best way to set `hint.fpsscale` and `hint.fpsrate` since the streaminfo change?

**Comment by FernetMenta** [comment]
handle fpsrate and scale like duration https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp#L602

**Comment by emveepee** [comment]
In the module that FernetMenta discussed, this is likely not a good solution but it worked for me with PVR and Video Library files so it might give a starting point.

    int64_t duration = m_pFormatContext->duration;
    AVRational frame_rate = {0,0};
    if (m_pFormatContext->nb_streams > 0)
      frame_rate = m_pFormatContext->streams[0]->r_frame_rate;

    std::shared_ptr<CDVDInputStream> pInputStream = m_pInput;
    Dispose();
    if (!Open(pInputStream, false))
      return false;
    m_pFormatContext->duration = duration;
    if (m_pFormatContext->nb_streams > 0)
      m_pFormatContext->streams[0]->r_frame_rate = frame_rate;

I could not find a test file where streams[] was larger than one, even when nb_streams was high.

**Comment by FernetMenta** [comment]
You should not bother with pFormatComtext, just save fpsrate and scale from the parameters of the object.

**Comment by phunkyfish** [comment]
Ok, it's far more long winded then what's above but does use the fpsrate and scale from the stream.

```
    int64_t duration = m_pFormatContext->duration;
    int fpsScale = 0;
    int fpsRate = 0;
    CDemuxStreamVideo* videoStream = nullptr;
    for (auto stream : GetStreams())
    {
      if (stream->type == StreamType::STREAM_VIDEO)
      {
        videoStream = static_cast<CDemuxStreamVideo*>(stream);
        fpsScale = static_cast<CDemuxStreamVideo*>(stream)->iFpsScale;
        fpsRate = static_cast<CDemuxStreamVideo*>(stream)->iFpsRate;

        break;
      }
    }

    std::shared_ptr<CDVDInputStream> pInputStream = m_pInput;
    Dispose();
    if (!Open(pInputStream, false))
      return false;
    m_pFormatContext->duration = duration;

    if (videoStream)
      m_pFormatContext->streams[videoStream->uniqueId]->r_frame_rate = {fpsRate, fpsScale};
```

Finding the values is a bit bulky unless there is a more succinct way to find them.

**Comment by phunkyfish** [comment]
Updated, saving the pointed caused a seg fault some times:

```
    AVRational frameRate = {0};
    int streamIndex = -1;
    for (auto stream : GetStreams())
    {
      if (stream->type == StreamType::STREAM_VIDEO)
      {
        streamIndex = static_cast<CDemuxStreamVideo*>(stream)->uniqueId;
        frameRate.num = static_cast<CDemuxStreamVideo*>(stream)->iFpsRate;
        frameRate.den = static_cast<CDemuxStreamVideo*>(stream)->iFpsScale;

        break;
      }
    }

    std::shared_ptr<CDVDInputStream> pInputStream = m_pInput;
    Dispose();
    if (!Open(pInputStream, false))
      return false;
    m_pFormatContext->duration = duration;

    if (streamIndex >= 0)
      m_pFormatContext->streams[streamIndex]->r_frame_rate = frameRate;
```

**Comment by emveepee** [comment]
We now know duration, fpsscale and, fpsrate are needed but lost because of the recursive Open() call not reloading   avformat_find_stream_info(m_pFormatContext, NULL). Are there other potential issues?   Won't it be safer to just call this again on the second pass?

Martin

**Comment by phunkyfish** [comment]
I reckon as 18.4 is just out we have time before 18.5 to see if there are any further issues. My 2 cents are that I wouldn't like to make a change like you suggest if it's not required.

**Comment by FernetMenta** [comment]
> Won't it be safer to just call this again on the second pass?

The whole idea of the second pass is to skip avformat_find_stream_info because it does not work reliable on mpeg-ts.

**Comment by emveepee** [comment]
Shouldn't this be backed out now that the source for the backport is now undergoing change?  User are already complaining that automatic Android are breaking playback.

**Comment by fritsch** [comment]
Users always complain, no hurry.

**Comment by phunkyfish** [comment]
Fixed by: https://github.com/xbmc/xbmc/pull/16596

**Comment by popy2k14** [comment]
thx a lot for the fix.
Also noticed that in kodi 18.4.

Any news when official stable 18.5 with the fix will be out?

If i use an 18.5 nightly and side load it, will it be overwritten by stable 18.5 when out?
(Using an Philips android tv and kodi officially installed througth play store)

thx

**Comment by phunkyfish** [comment]
There will be an 18.5 release, not sure when. Please be patient.

**Comment by popy2k14** [comment]
thx, take your time.
installed the current 18.4 nightly and EDL is working again.
Hope play store upgrades to stable when its done.
