### ISSUE TITLE
Using Alt+Space I can move kodi on full-screen mode

### ISSUE THREAD

**Issue by xmha97** [xbmc/xbmc#16571]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello, There is a bug on Kodi (tested on Windows Store version)
Using Alt+Space I can move Kodi on full-screen mode

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce
1. 
2.
3.

### Debuglog
The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/23485114/64302195-71564000-cf97-11e9-829f-622fec9e9e9f.png)

After:
![image](https://user-images.githubusercontent.com/23485114/64302197-74513080-cf97-11e9-9c57-e413498a49b9.png)

All move item disabled for all maximize windows (like below picture)
![image](https://user-images.githubusercontent.com/23485114/64302198-761af400-cf97-11e9-904d-21c08d11b579.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [X] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
I guess the logfile is rather useless in that case.  Hence I'll remove the 'ignored rules' label

Anyway, if you don't mind if would be nice if you could provide it and also stop ignoring our template like you have been advised some times before.

Maybe @afedchin can have a look?!

**Comment by KostasAndrianos** [comment]
Hey! Can you provide the log, please? I will look into it and *try* to fix it. Thanks.

**Comment by amirrammari** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/3719522/kodi.log)

**Comment by GiannisProkopiou** [comment]
Greetings,i would like to know if this is still open.
If it is open let me know if there is anything other that what i see that i need to know!
Thanks in advance!

**Comment by xmha97** [comment]
> 
> 
> Greetings,i would like to know if this is still open.
> If it is open let me know if there is anything other that what i see that i need to know!
> Thanks in advance!

Yes, I downloaded Kodi v18.6 from Microsoft Store.
This is still open.
![Kodi](https://user-images.githubusercontent.com/23485114/76688235-42a0dc80-6640-11ea-858a-bcad142afb21.png)

**Comment by GiannisProkopiou** [comment]
I am thinking about implementing this code below in the form which allows me to have messages as inputs or in the _**CWinSystemWin32::SetFullScreen**_ whick is used to set full screen,what do you say?

```
protected override void Move_Disable(ref Message m)
  {
      if (state == WINDOW_FULLSCREEN_STATE)
      {
        if (m.Msg == WM_MOVE && m.WParam == (IntPtr)SC_MOVE)
        {
          return;
        }
        base.Move_Disable(ref m);
      }
  }
  
// they are the (win32) windows messages that you're handling (defined in winuser.h).

//WndProc is the method used to handle the main message queue.

// move generates the WM_MOVE / SC_MOVE notification used to move the window's.

// by returning (not allowing base.WndProc to process the message) you stop the message from being sent / handled by the window.

// SC_MOVE         0xF010
// WM_MOVE                         0x0003
```

**Comment by moneyback665** [comment]
wow it good thankyou!!!

**Comment by Sherlock-liufr** [comment]
强啊大佬

**Comment by bloghotro** [comment]
thank you <3 <3 <3 <3

**Comment by I-Cat** [comment]
Excuse me the answer is


    protected override void OnKeyDown(KeyEventArgs e)
    {
        if (Keyboard.Modifiers == ModifierKeys.Alt && e.SystemKey == Key.Space)
        {
            e.Handled = true;
        }
        else
        {
            base.OnKeyDown(e);
        }
    }

**Comment by I-Cat** [comment]
> Maybe @afedchin can have a look?!

Hey look I have the answer But I can't fix it bc I dont see all of the code and im not on team kodi to be able to fix this.

**Comment by fuzzard** [comment]
All the source used for Kodi is in the github repo. PR's are welcome from anyone with fixes to issues. You dont need to be a team member to raise a PR against the xbmc repo

**Comment by I-Cat** [comment]
> All the source used for Kodi is in the github repo. PR's are welcome from anyone with fixes to issues. You dont need to be a team member to raise a PR against the xbmc repo

Okay, When I look at the code it all I see is readme.md 
I don't have the ability to see past the blob/
Via https://github.com/xmbc/xmbc

Also when I look at the wiki it is wrong? It is nearly impossible for me to try to make a pr honestly when I can't see the whole path?
Also I don't have write access with out being on team kodi.
Not too sure if you can see the path but I know the answer I just can't implement it because or do a PR / fix the issue bc the code is missing on my end.
Can any one can help me to put this code in to kodi?

**Comment by fuzzard** [comment]
You dont need write access to raise a PR.  All dev you do can be done locally on your device, and then git push to your own github repo, at which point a PR can be raised between the 2.

The readme is the default file to show, but it still has the entire folder structure above it. Click on any folder/file, and you can view that file.

In particualr, app source is in the xbmc folder https://github.com/xbmc/xbmc/tree/master/xbmc

May be worth doing some beginner git tutorials and what not to get your head around it all. Theres nothing special around how kodi uses git compared to any other project

**Comment by I-Cat** [comment]
Yey Thank you. :) I didn't even think of git tree. duh. 
Noob moment.

**Comment by ritik-chauhan** [comment]
so, we need to not be able to move kodi windows size using alt+space. I mean what is the problem with having the ability to change the window size.

**Comment by sahilbutola08** [comment]
Hi, I am Sahil. I really want to contribute but don't know how to start. Can anyone please guide me what should I learn and how to step by step start contributing. I am aware of python, c++ and html, css and js.

**Comment by nishiket04** [comment]
Hey
May I know whether this issue still needs to be fixed and is open? I would like to help.

**Comment by gusandrianos** [comment]
@nishiket04 Can you try to reproduce it? It might still occur.

**Comment by nishiket04** [comment]
i cant build it.

**Comment by nishiket04** [comment]
![image](https://user-images.githubusercontent.com/102466371/213712305-db8e1e2e-d8a3-46f5-b36b-aaa00f13f35c.png)
i am trying build kodi manully. but dont know what this error means,what should i do?

**Comment by the-black-eagle** [comment]
Please use the forum for support!  https://forum.kodi.tv/    Thanks!!

BTW, it means you need to install Visual Studio 17 but I would suggest that if you really didn't know what the error meant, that building Kodi from source is probably not what you should be attempting.

**Comment by nishiket04** [comment]
> Please use the forum for support! https://forum.kodi.tv/ Thanks!!
> 
> BTW, it means you need to install Visual Studio 17 but I would suggest that if you really didn't know what the error meant, that building Kodi from source is probably not what you should be attempting.

Thanks, i am new to this.
