### ISSUE TITLE
Option to change default websocket port 9090

### ISSUE THREAD

**Issue by JumBay** [xbmc/xbmc#16580]
### Describe the bug
Here is a clear and concise description of what the problem is:

This is not a bug but a feature request. 

As there is an option to change the default webserver 8080 port it should be very handy to have the same option for websocket. 

With android boxes becoming more and more popular, installing kodi on it is so easy but the default websocket port 9090 could be blocked or already used and changing it is really hard. 

Thx. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: android tv
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by rmrector** [comment]
Closing, feature requests go in the forums.

Ideally Websocket would run on the same port as the web server, and there is already a feature request for this - [Websocket and HTTP on same port](https://forum.kodi.tv/showthread.php?tid=317608).

**Comment by JumBay** [comment]
Great. Thanks.

**Comment by tomachinz** [comment]
That would be amazing if it could run on same port.
