### ISSUE TITLE
[macos] Lags in System info - Summary and Network

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/xbmc#16594]
### Describe the bug
Here is a clear and concise description of what the problem is:

Opening System info - Summary or System info - Network causes mouse pointer to not move smoothly (to lag). In Network it's much worse.

I've tested 17.6 (not so good), 18.3 (lags are more noticeable) and master (even worse).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Mouse pointer doesn't lag when System info - Summary or System info - Network is opened.

## Actual Behavior

Mouse pointer lags in these cases.

## Possible Fix

Maybe data is queried too often and main thread is overwhelmed with updates?

### To Reproduce

1. Go to Settings - System info 
2. Open Summary or Network
3. Move mouse around

### Debuglog

The debuglog can be found here: I'll add it if it's really needed.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS Mojave 10.14.6
 - Kodi version: 17.6, 18.3, 19 alpha

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Fixed by https://github.com/xbmc/xbmc/pull/23680 and https://github.com/xbmc/xbmc/pull/23724
