### ISSUE TITLE
[REQUEST] play m3u8 content with "EXT-X-MEDIA-SEQUENCE" 

### ISSUE THREAD

**Issue by wwark** [xbmc/xbmc#16621]
### Describe the bug
Here is a clear and concise description of what the problem is:

The content m3u8 with these headers not play in Kodi 18.4
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:268998

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

To be able to play these type of contents
VLC can play this content

## Actual Behavior

Not playable

### To Reproduce

1. Use this file M3u file : [1501.zip](https://github.com/xbmc/xbmc/files/3612599/1501.zip)
2. Play in Kodi

### Debuglog

The debuglog can be found here:
Log : https://pastebin.com/0aLjaTs9
Full Log: [kodi.log](https://github.com/xbmc/xbmc/files/3612613/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

No screenshot to provide

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

No more context

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
I guess this is currently not supported and therefore it might be a feature request which has to be submitted here: https://forum.kodi.tv/forumdisplay.php?fid=9

I know that a missing feature or something, which does not work (in meaning "being broken") is sometimes pretty related. So I leave this open to let a dev decide. 

Maybe @DaveTBlake is able to help out if it's expected to be supported and is broken or if it's currently not implemented. As I can't see anything related to "EXT-X-MEDIA-SEQUENCE" in the Kodi core code.

**Comment by DaveTBlake** [comment]
No, extended format in mixed media playlists is not currently supported in Kodi. This mean is this is a feature request and not a bug

**Comment by wwark** [comment]
Thank you I will open a ticket on the forum.
