### ISSUE TITLE
all of builds which newer than 17.0 can't startup after install, only 17.0 works on Mi Laser Projector (Android 6.0.1)

### ISSUE THREAD

**Issue by xnklerEd** [xbmc/xbmc#16629]
### Describe the bug
Here is a clear and concise description of what the problem is:

actually there is not really detailed info to feedback since its just keep crashing after install, only on log file submit on below
i've tried all of those newer version than 17.0, like 17.6, 18.0~18.4, also the 19.0-ALPHA1 Git:20190914-170d309853, all of those can not startup success, only 17.0 works great with my TV (Mi Laser Projector Android 6.0.1), i have spend around 3 days to test of those version.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Actual Behavior

just keep crashing on startup even reset my TV to factory 

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/dayoyijivo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:Android 6.0.1 API level 23 (kernel: Linux 3.14.29)
 - Kodi version:19.0-ALPHA1 Git:20190914-170d309853

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by M2k80** [comment]
your log is no debug log

**Comment by mkz899** [comment]
a newer log file submit to hastebin again which with the code `<loglevel>2</loglevel>` added to advancedsettings.xml, here is the link below 

https://paste.kodi.tv/fenolurapa.kodi

also there is a log file generated by kodi v17.0 (works on device) pasted here:

https://paste.kodi.tv/ejalalinik.kodi
@M2k80 thanks for your warming tips

**Comment by DaVukovic** [comment]
Is this your thread: https://forum.kodi.tv/showthread.php?tid=335136&highlight=mi+laser+projector
?

Sounds at least familiar.

**Comment by mkz899** [comment]
> Is this your thread: https://forum.kodi.tv/showthread.php?tid=335136&highlight=mi+laser+projector
> ?
> 
> Sounds at least familiar.

no it’s not me, but the 100% same issue we had.

**Comment by fritsch** [comment]
Please try: https://jenkins.kodi.tv/job/Android-ARM/19407/ when it's finished.

I have something very far behind in my brain, that these boxes use a totally fucked up firmware, which collides with v18 behaviour to actually probe supported audio formats. Those boxes just segfault, which they are not allowed to do at all.

But as always: you don't get any updates anymore, right?

Next time: Buy a good projector and a separate android box that you can replace whenever it goes on your nerves. (Hard lesson learned: if vendor does not do its job, OSS won't reimburst you for buying its hardware - but let's see now).
