### ISSUE TITLE
Broken zoom

### ISSUE THREAD

**Issue by alex-eri** [xbmc/xbmc#16624]
### Describe the bug

I have a TV with cutted AndroidTV 6.0. I installed Kodi, but have some video problems. One is then i try to zoom picture it not zoomed as expected. it zooms a litle then just move up.

Sometimes i have black screen on h264 iptv.

## Expected Behavior

Zoom and stable picture.

## Possible Fix

I think service that controls aspect ratio on tv break hardware decoder.

### To Reproduce

1. buy a rebrended china tv with modified  android
2.
3.

### Debuglog

https://paste.kodi.tv/pupazodube
https://paste.kodi.tv/lujosuxufu

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Andoid TV 6.0

 - Kodi version: 18.03

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Please provide a debuglog at least. Maybe there's already enough info in it

**Comment by DaVukovic** [comment]
Thanks, but if that is required: 

> buy a rebrended china tv with modified android

I guess this bug will not get much love ;). Noone will buy some crappy Android TV to reproduce your problem you have with this Android version. So I would probably blame Android itself in that case. 

But our devs will know

**Comment by alex-eri** [comment]
Workaround for black screen is switch to launcher then switch back.
