### ISSUE TITLE
 [Feature request] Add autoclose and oklabel parameters to xbmcgui.Dialog().ok

### ISSUE THREAD

**Issue by Wintermute0110** [xbmc/xbmc#16635]
## Roadmap or todo item
**Detailed Description**

Can you please add the autoclose parameter to the xbmcgui.Dialog().ok dialog, in a similar fashion to xbmcgui.Dialog().yesno() Also, can a parameter oklabel also added to the xbmcgui.Dialog().ok dialog? It will be very nice to be able to change the label of the OK dialog.

Is there any chance this can be backported for Leia 18.5?

### Context

In [Advanced Emulator Launcher](https://forum.kodi.tv/showthread.php?tid=287826) some operations take a long time to complete, for example scraping a launcher with many items may take hours to complete. In order to realise unattended scraping (users left the scraper running overnight), if an error happens (network down, etc.) AEL displays the error with a yesno() dialog which autocloses in one minute and then the scraping continues. However, the proper way to display the error must be an OK dialog, just with one button.

I'm sure other plugin/addon authors will find this change useful for their addons.

### Possible Implementation

No idea, sorry. I am not an expert of the C++ core.

### Additional context, screenshots or links

No screenshots needed, description is clear.

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by DaVukovic** [comment]
@Wintermute0110 that's an interesting request. But, as it is a request, it would be better placed here: https://forum.kodi.tv/forumdisplay.php?fid=9

GitHub issues is for bug reports only. If you don't mind, could you please open a thread at the Kodi forums for further discussion? 

What I can already answer is: 

> Is there any chance this can be backported for Leia 18.5?

I guess this can be for sure answered with "no". As Kodi 18.x will only receive bug fixes. This would be kind of an "improvement" which will not be accepted as a backport. We have to draw the line at some point ;)

**Comment by Wintermute0110** [comment]
@DaVukovic For the record, I already posted the Feature Request in the forum (here)[https://forum.kodi.tv/showthread.php?tid=346944]. I posted the request here as suggested by Lunatixz.

**Comment by DaVukovic** [comment]
Then @Lunatixz was wrong ;). Those things happen. 

![grafik](https://user-images.githubusercontent.com/7235787/65954198-ce81cc00-e445-11e9-9079-cd86f7361af6.png)

This issue is not an issue. The "Roadmap" is for Team members only

I'll move your thread to the feature request subforums.

**Comment by Wintermute0110** [comment]
@DaVukovic Thanks for your answer. I already created a new thread in the forum, no need to move the original one!
