### ISSUE TITLE
[REQUEST] Show installed version number in Add/Remove Programs

### ISSUE THREAD

**Issue by campbellkerr** [xbmc/xbmc#16630]
Since Kodi doesn't (currently?) check for updates, it would be useful to be able to see the version number from Add/Remove Programs (on Windows at least). Currently this field isn't populated.
Thanks!
![image](https://user-images.githubusercontent.com/38451588/64920407-c1849c00-d7fa-11e9-968f-c1af4bf164d7.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

**Comment by DaVukovic** [comment]
Sorry to close that, but this section here is for bug reports and not for feature requests ;)

Please submit your feature request here: https://forum.kodi.tv/forumdisplay.php?fid=9

Thanks for understanding
