### ISSUE TITLE
Audio info does not get updated with replacement file bug back again!!!

### ISSUE THREAD

**Issue by gate1975mlm** [xbmc/xbmc#16639]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi 18.4 and Kodi 19 Alpha builds have the issue again where if a movie in the directory is replaced with a new file with different audio the movie info is not being updated to the new audio like Dolby Digital to DTS. :(

This bug was fixed a while ago and it's back again what happened and will this be fixed again?

Thanks

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When you replace a movie with the same movie but with different audio the audio info should be updated in the movie directory.

Example Dolby Digital info changing to DTS.

## Actual Behavior

When you replace a movie with the same movie but with different audio the audio info is not updated in the movie directory.

### To Reproduce

1. Again replace a movie with the same movie but with different audio and you will see that the audio indo does not get updated. 

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Windows 10 Pro 64 Bit
 - Kodi version:
18.4 and 19 Alpha builds

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment]
With 18.4 you can now refresh the stream details by refreshing the movie information.

**Comment by gate1975mlm** [comment]
> With 18.4 you can now refresh the stream details by refreshing the movie information.

Cool I did not realize this.

I just tried it and yep you are right :)

Thanks for the info and glad it's not a new bug :)

**Comment by gate1975mlm** [comment]
Just one question

Any idea why it was changed from having the audio info updated after starting a movie vs now having to refresh the movie information?

Doing it this new way adds some extra clicks.

I guess there was no way to allow the audio info be updating both ways?

**Comment by KarellenX** [comment]
Not a bug, but by design. Issue closed, but conversation can continue.
