### ISSUE TITLE
Separate sort order for folders and photos in the Pictures view

### ISSUE THREAD

**Issue by brjhaverkamp** [xbmc/xbmc#16647]
I have looked at this forum and several other places, but there is as far as I can tell no way of doing this currently in Kodi:

Simply put I want to set the sort order for folders and pictures independently.
- Sort folders alphabetically
- Sort pictures on date taken

I can do either or, but not both.
Kodi  now has a date sorting, but it then sorts the folders by creation date.
I can sort all alphabetically, but then my pictures are not in chronological order.

The background is that I (and many others) organize pictures in folders that are named Date-Topic, e.g. "2018-06-17 Holiday Greece". I haven't necessarily created the folders in date order, so to view them in "chronological" order I need them sorted alphabetically.
Within each folder there are pictures from several cameras and smartphones, each with their own naming convention. I don't want to bother touching the names, but use the date sorting to view them in chronological order.

Most viewers and phot editors  have this ability to set the sort-order for folders and images separately.  So I am lead to believe this is a common problem. I hope someone can add this to the Picture add on! and make Kodi from 99% to 100% awesome!

Kind regards,

Bert

**Comment by KarellenX** [comment]
@brjhaverkamp

You are misusing the Issues section of Github. This is not the location for support or feature requests. This is the location to report confirmed bugs in Kodi.

Please use the forum for assistance.

Both your issues will be closed.
