### ISSUE TITLE
Secondary profile UI settings not honored when Show login screen on startup is enabled

### ISSUE THREAD

**Issue by IslandJohn** [xbmc/xbmc#16644]
### Describe the bug

When Show login screen on startup is enabled after setting up secondary profiles, any secondary profiles selected during startup seem to get the master profile UI settings.

1. Fresh install Kodi
2. Launch and remove everything from home screen except Add-Ons
3. Add a new profile (Test)
4. Switch to "Test" profile and remove everything from home screen except Favorites
5. Enable Show login screen on startup
6. Quit
7. Launch Kodi
8. Select "Test" profile
9. Notice that it shows "Add-On" instead of "Favorites"

## Expected Behavior

After step 8 above, the home screen should show Favorites.

## Actual Behavior

After step 8 above, the home screen shows Add-Ons.

## Possible Fix

None

### To Reproduce

1. Fresh install Kodi (18.4 macOS)
2. Launch and remove everything from home screen except Add-Ons
3. Add a new profile (test)
4. Switch to profile and remove everything from home screen except Favorites
5. Enable Show login screen on startup
6. Quit
7. Launch Kodi
8. Select "test" profile
9. Notice that it shows "Add-On" instead of "Favorites"

### Debuglog

Tried with or without locks, only removing some things. This behavior begins after Show login screen on startup is enabled.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP
 
 - Operating system version/name: macOS Mojave 10.14.6
 - Kodi version: 18.4 and 18.5 (20190918-c20baba8)

**Comment by DaVukovic** [comment]
Does it show Favorites if you try that workaround:

https://kodi.wiki/view/Profiles#Missing_texts.2Fdifferent_skins_not_loading_while_using_profiles

In meaning, put an autoexec.py in the userdata folder and in each profile folder which reloads the skin after the profile is loaded? See the wiki for the content of the autoexec.py

**Comment by DaVukovic** [comment]
No log, no comments. Issue closed
