### ISSUE TITLE
Easy profile switcher

### ISSUE THREAD

**Issue by brjhaverkamp** [xbmc/xbmc#16646]
I am setting up the Kodi's in my home to use a single database and profiles for myself, my wife and our two children. As they are getting the age they are watching the same movies and series, I want to be able to separate their watchlist and watched status from mine.

To make use of that, the barier to switch user-profiles should be as little as possible.
For this I would like to have the power button replaced by a user symbol, a bit lilke netflix has this in the upper left corner. 
Envisioned behavior:
The icon shows the avatar of the current user and his name beside/under it.
When selecting and pressing the icon, a list of users is shown, and below that the rest of the current options of the power button: Exit, Power off system, custom shutdown timer, reboot.
Log off <current user> is not needed in this setup.

This user switching option should only be enabled if multiple profiles are created. Otherwise the current behaviour with a power button should be shown.

I hope you can take this usability request into acount.
Bert Haverkamp
P.S. I know there is a shortcut with the guide button for profile switching, but this is less user-friendly (e.g. no visible indication of the current user) and I personally have a problem on my Sony Bravia screen to hook the guide function to a physical button on my remote. The guide button on the remote is not mapable..

**Comment by KarellenX** [comment]
@brjhaverkamp 

You are misusing the Issues section of Github. This is not the location for support or feature requests. This is the location to report confirmed bugs in Kodi.

Please use the forum for assistance.

Both your issues will be closed.
