### ISSUE TITLE
Newest Kodi (18.4) is not available in F-Droid yet! (on Android)

### ISSUE THREAD

**Issue by 4tip** [xbmc/xbmc#16656]
Hi. 
Kodi 18.4 is not available for download in F-Droid yet (on Android)! 
There's only 18.3, link: https://f-droid.org/en/packages/org.xbmc.kodi/
Please try to help fixing this! 

Please also check if future releases gets available in F-Droid repo, the day they get released.

Thank you.
Best regards

**Comment by Darren-Hill** [comment]
The site is entirely third party to us, and is not supported, controlled or endorsed by Team Kodi.

Keeping it up to date with packages and apks is entirely down to whoever maintains the site. Please contact them concerning your request.

This issue is closed.
