### ISSUE TITLE
Audio stream does not play in pvr.iptvsimple if audio decoder addons installed

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#16652]
### Describe the bug
Here is a clear and concise description of what the problem is:

By default kodi installs the AAC and WMA decoders. If any additional decoder addons are installed, audio streams will not play in pvr.iptvsimple.

This appears to have been an issue wince kodi 18 release so probably also exists in master.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

With any additional decoder addons installed, audio streams should play in pvr.iptvsimple.

Forum post: https://forum.kodi.tv/showthread.php?tid=347437
Older pvr.iptvsimple issue: https://github.com/kodi-pvr/pvr.iptvsimple/issues/212

## Actual Behavior

By default kodi installs the AAC and WMA decoders. If any additional decoder addons are installed, audio streams will not play in pvr.iptvsimple.

## Possible Fix

Really not sure. Afraid I don't understand how the audio decoders work.

### To Reproduce

1. Install any additional audio decode addon
2. Use the M3U file below in pvr.iptvsimple
3. Play radio channel, it will fail to play

```
#EXTM3U
#EXTINF:-1 radio=true tvg-logo="JB-Radio2.png",JukeBox2
http://cristina.torontocast.com:8007/mp3-320
```

### Debuglog

The debuglog can be found here:

With only the default WMA and AAC decoders installed it's works: https://pastebin.com/u2NSPyeg

With additional decoders installed it does not work: https://pastebin.com/BmeGqc8d

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [X] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSX/Ubuntu 18.04.2 LTS
 - Kodi version: 18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment]
I have an idea what could cause this (we had the same problem for our addon filesystem). PR coming up. Can you compile/test it?

**Comment by phunkyfish** [comment]
Sure. Will check it later today.
