### ISSUE TITLE
[settings] Using a real number binary addon setting causes crash - new settings format

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#16663]
### Describe the bug
Here is a clear and concise description of what the problem is:

If a real number (as opposed to integer) is used in a binary addon setting it will cause a crash.

This should work based on:

https://github.com/xbmc/xbmc/blob/master/xbmc/settings/lib/SettingsManager.cpp#L950 and https://github.com/xbmc/xbmc/blob/master/xbmc/settings/lib/Setting.h#L328-L369.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

A real number setting works similar to how integer settings do.

## Actual Behavior

A crash happens.

### To Reproduce

Starting with the old settings format I wanted to convert this to the new format:

```
<setting id="epgTimeShift" type="slider" label="30024" default="0" range="-12,.5,14" option="float"/>
```

This should look like this:

```
        <setting id="epgTimeShift" type="number" label="30024" help="30625">
          <level>0</level>
          <default>0</default>
          <constraints>
            <minimum>-12</minimum>
            <step>0.5</step>
            <maximum>14</maximum>
          </constraints>
          <control type="slider" format="number">
            <formatlabel>17998</formatlabel>
          </control>
        </setting>
```

However this caused a crash so had to use this integer based solution instead:

```
        <setting id="epgTimeShift" type="integer" label="30024" help="30625">
          <level>0</level>
          <default>0</default>
          <constraints>
            <minimum>-720</minimum>
            <step>30</step>
            <maximum>960</maximum>
          </constraints>
          <control type="slider" format="integer">
            <formatlabel>14044</formatlabel>
          </control>
        </setting>
```

### Debuglog

The debuglog can be found here:

 https://pastebin.com/zybEGi20

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSX Mojave
 - Kodi version: Kodi 19 Alpha

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Montellese** [comment]
The problem is the `<formatlabel>17998</formatlabel>` which resolves to the following (English) string: `{0:d} hours`. This means that the format label expects an integer (`d`) but the provided value when trying to generate the label is a double which requires a format label with `f` e.g. `{0:.1f} hours` to show the value with a single precision digit. Could you give that a try?

The remaining question is whether we should add some sanity checking when parsing the `<formatlabel>` property. The problem is that we can only check it against the currently loaded language. If a user changes the language it will also change the localized label but the setting has already been loaded and validated. Maybe we should do the sanity check before generating the actual label and in case of a potential issue log a warning and fall back to a default format label.

**Comment by phunkyfish** [comment]
That was exactly the problem, thanks.

Any kind of warning would be great, it certainly shouldn’t crash and being able tell why would have helped.

**Comment by Montellese** [comment]
See 6fdf65ab90320c8e8cbbc04112d8e403dc0fedb3 for catching the bad formatting and falling back to a default formatting string. I need to check other formatting logic for the same issue.

**Comment by phunkyfish** [comment]
Found something interesting. You have to use a float type when reading a setting. It you use double the value will be wrong.

I guess this was less likely to happen with the old settings format as the type was float.

**Comment by Montellese** [comment]
@phunkyfish I'm guessing you are talking about reading the value in python? Maybe we can fix that in the python API implementation.

**Comment by phunkyfish** [comment]
No, this is C++. If I use a float it work, double it doesn’t.

Let me give you a reference.

**Comment by phunkyfish** [comment]
https://github.com/kodi-pvr/pvr.iptvsimple/pull/281/commits/379f08d5518a8399ed916f0e127473681568b7b2

If I attempt to cast the void star to a double I get a crazy number. It only works with floats.

The example is a little hard to understand due to the templates used.

**Comment by phunkyfish** [comment]
It's not really an issue. You just need to know to use float. But as the backend code uses double you would kind of assume it's ok.

**Comment by phunkyfish** [comment]
On Mac if that makes any difference.

**Comment by Montellese** [comment]
Casting a `double` to a `void*` sounds like a bad idea. AFAIK `double` is stored within 8 bytes on many systems but a `void*` only addresses 4 bytes.

**Comment by Montellese** [comment]
I also just saw that the binary add-on API only covers `float` see https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/AddonBase.h#L286.

**Comment by phunkyfish** [comment]
Ok, so just a lack of understanding on my part. Thanks for explaining.
