### ISSUE TITLE
Playback of Bus Encryption Enabled Blu-ray discs is broken since commit 25d755c0365b2699161bc303bd55afae895fc2ec

### ISSUE THREAD

**Issue by cpmw167** [xbmc/xbmc#16672]
### Describe the bug
I recently updated to Leia and I noticed that playback of BEE Blu-ray discs was broken when using libbluray/libaacs. After a very interesting git bisect session it turns out switching from bd_open_disc() to bd_open_files() in commit 25d755c0365b2699161bc303bd55afae895fc2ec was the reason why playback of Bus Encryption Enabled Blu-ray discs are failing to open properly. This doesn't seem to affect non-BEE discs.

It seems bd_open_files() doesn't call aacs_decrypt_bus(), therefore discs should be opened using bd_open_files() instead.

## Expected Behavior
Playback should work.

## Actual Behavior
Playback fails.

## Possible Fix

Reverting back to using bd_open_disc() seems to fix playback of all BEE BDs, including UHDs.

### To Reproduce

1. Try playing Bus Encryption Enabled Blu-ray disc with libbluray/libaacs.

### Debuglog

No debuglog. The problem is that libbluray doesn't call aacs_decrypt_bus() when disc is opened using bd_open_files() therefore bus encryption is not handled.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by cpmw167** [comment]
Is that bot telling me that this is not being considered because I didn't provide (in this case) irrelevant debuglog? Debuglog doesn't contain anything useful regarding this issue so I don't see why I should waste my time anonymizing it.

This regression is caused by Kodi using libbluray incorrectly when opening a original Blu-ray disc on a real optical drive. Hard disk folders and smb:// shares don't have Bus Encryption (or any kind of encryption) so bd_open_files() is sufficient in those cases, but it's not sufficient when 1) disc wants Bus Encryption and 2) drive supports it.

In case anyone else is experiencing this, I pushed a quick fix here https://github.com/cpmw167/xbmc/commit/19d86e1cad07713325a3bdbbeb7ee54f2ca85d1f . It's not a proper fix so I didn't open a pull request, but it fixes playback of BEE Blu-ray discs and UHD Blu-ray discs when using libbluray and libaacs.

However, the above fix may break menus when using protocol like smb:// (I can't test). It should probably use bd_open_files() when root IsSmb(). Unfortunately, besides that I can't test smb:// protocol, I'm not familiar with Kodi internals so I'm unable to fix this properly.

Until a proper fix is available, it's basically a trade off between losing menus on smb:// protocol or not handling Bus Encryption at all. When Bus Encryption is not handled, content on the disc remains encrypted and playback fails completely. Therefore if this was my decision, I would rather break menus on smb:// protocol than completely break playback for thousands of discs, but obviously it's not my call.

**Comment by DaVukovic** [comment]
If one of our core devs has the opinion he wants to see a log, then you should at least waste that little time and provide one. As you are asking us for getting that fixed. And if you want us to help you, then providing a logfile should be only a little waste of time. 

Anyway, as it seems you don't want to provide that logfile (as it's only a waste of time in your eyes), we are now going to close this issue. 

I'll happily re-open this issue again after you have submitted the log

Thanks for understanding

**Comment by cpmw167** [comment]
I'm terribly sorry for not including the debuglogs. I should have included them from the start.

So here are two debuglogs from Kodi v19 git when I'm trying to play BEE Blu-ray disc. First one is unpatched and the second one contains the patch I linked earlier. Playback fails in the first one and succeeds in the second one.

Debuglog from unpatched Kodi v19
https://paste.kodi.tv/ejanipugak.kodi

Debuglog from patched Kodi v19
https://paste.kodi.tv/uniwiqufuy.kodi

In the unpatched Kodi, when I try to play BEE disc, playback fails after selecting a title (simple menu) and debuglog states that "Unable decrypt unit (AACS)" - which is caused by the bus encryption not being handled.

In the patched Kodi, playback begins immediately and everything works like it worked in Krypton - including UHD discs. Note that I'm using libbluray with libaacs and not libmmbd from MakeMKV.

This regression is present on Leia as well. Playback works in Krypton, because Krypton uses bd_open(), which is just a shortcut for bd_open_disc(), see libbluray documentation[1]

Kodi probably needs to check whether the root is an optical drive, hard disk folder or a disc image and use then use bd_open_disc(), bd_open_files() or bd_open_stream() accordingly.

@DaVukovic could you perhaps re-open this issue? And also, let me know if something else is needed.

[1] https://www.videolan.org/developers/libbluray/doc/doxygen/html/bluray_8h.html#a6250c70fd06a2478e6df57b30ad2fec8

**Comment by cpmw167** [comment]
Fixed in v19
