### ISSUE TITLE
kodi 18.4 crashing.

### ISSUE THREAD

**Issue by candy-kishor** [xbmc/xbmc#16679]
when i open kodi its just load skin and when i press any button it'll crash.
I'm using windows machine. 
i tried reinstalling kodi. results are negative.

i attached crash log
[Kodi.zip](https://github.com/xbmc/xbmc/files/3661930/Kodi.zip)

**Comment by DaVukovic** [comment]
Could you also please paste the kodi.log. The crashlog.txt file seems a bit useless. The kod.log is generated anyway. Maybe this shares more info

**Comment by DaVukovic** [comment]
friendly reminder for the log. We will close this issue if no log will be provided until monday.
