### ISSUE TITLE
de todas as versões do kodi,apresenta erros de log de alguns addons e não funciona,quando atualiza o pvr simple client,fica incompativel em qualquer versao que seja do kodi

### ISSUE THREAD

**Issue by DNA31** [xbmc/xbmc#16671]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DNA31** [comment]
erros de funcionamento de alguns addon e incompatiblidade de pvr simple client

**Comment by KarellenX** [comment]
Please post in English.

I suggest you start seeking assistance in the forum first.
https://forum.kodi.tv/index.php
