### ISSUE TITLE
Duplicate movie entries

### ISSUE THREAD

**Issue by fganter** [xbmc/xbmc#16684]
### Describe the bug
Here is a clear and concise description of what the problem is:

After scanning for new content, KODI creates duplicate entries (3 in total) for the same item.  All three are in the same file location, which is an SMB share.

For years I've had my KODI devices using a MySQL database.

KODI set up to use local metadata only.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

only 1 entry per movie

## Actual Behavior

3 entries per movie

### To Reproduce

1.  Re-scan existing content on SMB share
2.  Look in your movie listing
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi 3
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:  18.4 running on LibreELEC 9.2 Beta1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by kib** [comment]
I'm going to hazard a guess that you have multiple sources pointing to the same thing.
This is not a common issue (and surely not reproducable for anyone by just scanning again).

What happens in the debug log while the extra items are being added ? You forgot to add one...
