### ISSUE TITLE
delete watched files for kodi apk for AFTV

### ISSUE THREAD

**Issue by Benman2785** [xbmc/xbmc#16686]
## Expected Behavior
Here is a clear and concise description of what was expected to happen:
i select "Löschen" (german for delete) - the fill will get deleted

## Actual Behavior

i select "Löschen" (german for delete) and nothing happens - no error code - it only falls back to the normal list view of the files

## Possible Fix

add a AFTV OS permission-prompt to ensure i can write/delete on external USB drives on AFTV

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.3; 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Benman2785** [comment]
i tried my best xD

**Comment by DaVukovic** [comment]
You missed to provide the logfile which shows that behavior. 

Anyway, are you sure you enabled this: 

![grafik](https://user-images.githubusercontent.com/7235787/65857657-92c30580-e364-11e9-8106-d417c4cf29c4.png)

**Comment by DaVukovic** [comment]
No repsonse anymore. Issue closed

**Comment by Benman2785** [comment]
sry forgot about it - kill check it today and reponse
