### ISSUE TITLE
First PVR recording fails to play when selected while playing music

### ISSUE THREAD

**Issue by arnova** [xbmc/xbmc#16690]
I have a strange problem with my Kodi/TVHeadEnd setup. Every now and then when my Linux (Ubuntu 18.04-AMD64) system resumes from suspend, it fails to play the first recording I select (without an error message). When retrying, it keeps failing over and over again. Now I figured out that when, after the first failure, I select another recording (which does play successfully) and then select the first recording again, it will work. I have no idea whether this is a Kodi problem or a problem in the TVHeadEnd backend.

Log here: http://eld.leidenuniv.nl/~arnova/kodi.log . The problem starts at time/date ~ "2019-09-29 17:19:27.538"

**Comment by ksooo** [comment]
> 2019-09-29 10:15:15.113 T:139756021217024   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - vfs read failed after 1 attempts

 Tvheadend does not deliver data for the recording. Could it be the case that a NAS (or another external storage device) hosting your recording files is not (yet) ready when Kodi wants to read the recordings data?

 You wrote, that the second recording will play fine, but I think it's not the position of the recording in your list of recordings, but the point in time you're trying to play it.

**Comment by ksooo** [comment]
You could try to increase the request response time in pvr.hts settings, let's say to 30 secs? Does that help?

**Comment by arnova** [comment]
> > 2019-09-29 10:15:15.113 T:139756021217024   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - vfs read failed after 1 attempts
> 
> Tvheadend does not deliver data for the recording. Could it be the case that a NAS (or another external storage device) hosting your recording files is not (yet) ready when Kodi wants to read the recordings data?
> 
> You wrote, that the second recording will play fine, but I think it's not the position of the recording in your list of recordings, but the point in time you're trying to play it.

No it's not the position in the list, but the first one "in time" I try to play. And the item keeps failing over and over again (even minutes later), until I first play another item in the list. The data is stored locally (not on a NAS) but since the system is resuming from suspend, the harddrive could still be spinning up.

 I'll try upping the response timeout, but that doesn't explain why the item won't play, even after several retries.

**Comment by ksooo** [comment]
> but that doesn't explain why the item won't play, even after several retries.

 right.

**Comment by ksooo** [comment]
Could be related to https://github.com/kodi-pvr/pvr.hts/commit/c26a452747c854860db9b2c82906f04dc5cdc422

**Comment by arnova** [comment]
> Could be related to [kodi-pvr/pvr.hts@c26a452](https://github.com/kodi-pvr/pvr.hts/commit/c26a452747c854860db9b2c82906f04dc5cdc422)

I doubt it. I'm looking for "something" that remembers (flags) that the item failed to play and only resets the error-state when another item is played.

**Comment by ksooo** [comment]
> I'm looking for "something" that remembers (flags) that the item failed to play and only resets the error-state when another item is played.

 https://github.com/tvheadend/tvheadend ?!

**Comment by arnova** [comment]
> > I'm looking for "something" that remembers (flags) that the item failed to play and only resets the error-state when another item is played.
> 
> https://github.com/tvheadend/tvheadend ?!

Yes, that's what I'm afraid of where the issue is.

**Comment by Leatherface75** [comment]
Having big trouble here with channels too.
Kodi really needs improved handling there maybe an option or something to not timeout when going to suspend?

**Comment by arnova** [comment]
@ksooo : I think I just figured out how to reproduce this issue for you. It seems to occur specifically when there's already music playing. So try to play a pvr recording while there's already playing music seems to result in consistent pvr playback failure.

**Comment by ksooo** [comment]
> It seems to occur specifically when there's already music playing. So try to play a pvr recording while there's already playing music seems to result in consistent pvr playback failure.

 So, you are saying this is unrelated to suspend/resume?

**Comment by arnova** [comment]
> > It seems to occur specifically when there's already music playing. So try to play a pvr recording while there's already playing music seems to result in consistent pvr playback failure.
> 
> So, you are saying this is unrelated to suspend/resume?

Yes, unrelated to suspend/resume. On suspend/resume my system automatically starts playing music that's why I thought that was the thing triggering it. But now that I know it, it's quite easy to reproduce: Play music, and while playing select a PVR item to play.

**Comment by ksooo** [comment]
> Yes, unrelated to suspend/resume. 

 Okay, please update the subject of this PR, then.

> Play music, and while playing select a PVR item to play.

 What exactly happens? Hang? Crash?

**Comment by arnova** [comment]
> > Yes, unrelated to suspend/resume.
> 
> Okay, please update the subject of this PR, then.
> 
> > Play music, and while playing select a PVR item to play.
> 
> What exactly happens? Hang? Crash?

No hang/crash, it's just that nothing happens (=music stops, but PVR recording playback doesn't start). Also selecting the SAME PVR item again results in failure again, only selecting a different PVR item works.

**Comment by ksooo** [comment]
Hmm, I'm getting a 100% reproducible GUI hang here (macOS).

Anyway, seems to be no PVR problem, as we can see that VideoPlayer thread (playing music) seems not to stop when trying to play the recording:

<img width="930" alt="Screenshot 2020-01-01 at 17 41 08" src="https://user-images.githubusercontent.com/3226626/71643810-4918ec80-2cbe-11ea-93e8-e9c92de221fa.png">
<img width="639" alt="Screenshot 2020-01-01 at 17 42 30" src="https://user-images.githubusercontent.com/3226626/71643811-4918ec80-2cbe-11ea-9375-a8a86835bd5d.png">

**Comment by ksooo** [comment]
@FernetMenta do you have an idea what goes wrong here?

**Comment by arnova** [comment]
@ksooo : Why is VideoPlayer playing music and not PAPlayer?

**Comment by ksooo** [comment]
No idea. I don't remember that I have changed any settings.

**Comment by a1rwulf** [comment]
@ksooo https://github.com/xbmc/xbmc/pull/16429
I plan to work on this somewhen this month.

**Comment by arnova** [comment]
@ksooo: i wonder if it's the same issue then as what  I'm experiencing. do you have calltrace for all threads?

**Comment by ksooo** [comment]
@a1rwulf thanks for the heads up. Yes, this seems to be exactly the same issue.

**Comment by FernetMenta** [comment]
The root cause of this bug report has nothing to do with the issue linked by @a1rwulf . The root cause here is that playlist player shuts down player right after application has started playback of pvr.

**Comment by arnova** [comment]
> The root cause of this bug report has nothing to do with the issue linked by @a1rwulf . The root cause here is that playlist player shuts down player right after application has started playback of pvr.

Any idea what the proper fix for this would be?

**Comment by FernetMenta** [comment]
You can't properly fix playlistplayer without rewriting large portions of it. This crap is woven into a dozen components which makes it almost impossible to capture the intended logic. Currently it listens to gui and thread messages, acting in the shadow against user and application.

A quick and ugly fix could be:

```
diff --git a/xbmc/PlayListPlayer.cpp b/xbmc/PlayListPlayer.cpp
index 8b637cd88e..c2a185b1bd 100644
--- a/xbmc/PlayListPlayer.cpp
+++ b/xbmc/PlayListPlayer.cpp
@@ -863,6 +863,7 @@ void PLAYLIST::CPlayListPlayer::OnApplicationMessage(KODI::MESSAGING::ThreadMess
     // first check if we were called from the PlayFile() function
     if (pMsg->lpVoid && pMsg->param2 == 0)
     {
+      Reset();
       CFileItem *item = static_cast<CFileItem*>(pMsg->lpVoid);
       g_application.PlayFile(*item, "", pMsg->param1 != 0);
       delete item;
```

I see no reason why the current playlist should be kept if TMSG_MEDIA_PLAY gets posted with just a single item. But, as mentioned, you can't be sure here.

**Comment by a1rwulf** [comment]
> The root cause of this bug report has nothing to do with the issue linked by @a1rwulf . The root cause here is that playlist player shuts down player right after application has started playback of pvr.

There may be several scenarios that trigger this deadlock.
As long as close is not async or render thread is split from mainthread we may see this deadlock again and again.

**Comment by FernetMenta** [comment]
this bug report is not about a deadlock

**Comment by a1rwulf** [comment]
True - my post was meant as an answer to @ksooo's post where he stated he sees a GUI hang which shows a deadlock in his stacktraces which is identical to the issue I've linked.

**Comment by ksooo** [comment]
Yep, sorry that we mixed up to different things in one issue. The hang is something different. This issue is not about a deadlock, but about

> that playlist player shuts down player right after application has started playback of pvr
