### ISSUE TITLE
Context-Menu of Music-Addons contains wrong entries

### ISSUE THREAD

**Issue by malvinas2** [xbmc/xbmc#16708]
### Describe the bug
Opening the context menu of a music addon shows entries like "Queue item", "Play next" or "Play" which in most cases lead to a neverending busy-dialog aca crash as you can't queue an addon etc. 

## Expected Behavior
Context menu should only contain "Information", "Disable", "Settings" and "Add to favourites". 

## Actual Behavior
neverending busy-dialog

### To Reproduce
1. Go to addons / music-addons
2. Select an addon 
3. Press 'c' 
4. Select one of the mentioned entries

### Debuglog
The debuglog can be found here:  not necessary

### Screenshots 
[https://i.imgur.com/QrRFIhY.jpg](https://i.imgur.com/QrRFIhY.jpg)

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 8.1 Pro
 - Kodi version:
18.4

**Comment by malvinas2** [comment]
> This is an automatically generated message. If you believe it was sent in error, please say so
so

**Comment by ronie** [comment]
confirmed, those options even show up in the root listing of the music section.
