### ISSUE TITLE
No Scrollbar at Addon Settings Dialog in skin.estuary

### ISSUE THREAD

**Issue by harryberlin** [xbmc/xbmc#16711]
### Describe the bug
Here is a clear and concise description of what the problem is:

There is no Scrollbar at Addon Settings Dialog.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Takes a long time to pos the cursor, if there are lot of settings in the list.

## Actual Behavior

Nothing

## Possible Fix

Add Scrollbar.

### To Reproduce

1. Open Addon Settings Dialog of an addon with lot of settings
2. Now you can't see no Scrollbar.

### Debuglog

The debuglog can be found here: no debug log

### Screenshots 
Here are some links or screenshots to help explain the problem:

No Screenshot requiered.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

No

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: from 17

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
applies to both DialogAddonSettings.xml & DialogSettings.xml

**Comment by ronie** [comment]
https://github.com/xbmc/xbmc/pull/16782
