### ISSUE TITLE
dash mpd problem.

### ISSUE THREAD

**Issue by vstavrinov** [xbmc/xbmc#16722]
[kodi.log](https://github.com/xbmc/xbmc/files/3696304/kodi.log)
---
name: dash mpd problem
about: couldn't play mpd file

---

### Describe the bug
This works:
```
ffplay https://rfeingest-i.akamaihd.net/dash/live/677329/DASH_RFE-TVMC5/manifest.mpd
```
This doesn't work:
```
kodi https://rfeingest-i.akamaihd.net/dash/live/677329/DASH_RFE-TVMC5/manifest.mpd
```
The problem exists for kodi 19.0 and 18.3 under Linux, but there are no such problem for versions 17.6 for Linux and 18.4 for Android

## Expected Behavior
It should work with all versions

### To Reproduce

1. See above examples 
2.
3.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian GNU/Linux bullseye/sid
 - Kodi version: 19.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Please don't ignore our template. We will need logs for that. Otherwise we can't help.

**Comment by DaVukovic** [comment]
Still no debuglog. Please be aware that we will close this issue in 5 days if you don't provide one.

**Comment by DaVukovic** [comment]
Obviously no interest in providing a logfile. Issue closed

**Comment by vstavrinov** [comment]
> Obviously no interest in providing a logfile. Issue closed

Strange statement. Log was added 3 weeks ago into description of this issue and seen on very top of this page.

**Comment by DaVukovic** [comment]
Feeling sorry, that I missed that. 

Happy to re-open this issue now. 

@peak3d might that be an inputstream problem? I tried:
https://github.com/peak3d/inputstream.adaptive/blob/master/README.md
to create a strm-file, but I failed

**Comment by sarbes** [comment]
Works with 19.
