### ISSUE TITLE
Missed semicolon changes flow of execution (minor bug)

### ISSUE THREAD

**Issue by IlyaGainulin** [xbmc/xbmc#16734]
We noticed that there is a missed semicolon in AdvancedSettings.cpp file in the 1476th line.
It clearly changes the expected flow of execution. Here is the part of the code with this problem:
```
void CAdvancedSettings::SetExtraArtwork(const TiXmlElement* arttypes,
   std::vector<std::string>& artworkMap)
{
  if (!arttypes)
    return          // Here should be a semicolon
  artworkMap.clear();
  const TiXmlNode* arttype = arttypes->FirstChild("arttype");
  ....
}
```

According to formatting of the code, we expect that the method _SetExtraArtwork_ will be returned if _!arttypes_ is true. But instead we clear _artworkMap_ and return the result of the _artworkMap.clear()_ method. On the other hand when _!arttypes_ is false we expect that _artworkMap_ gets cleared, but it doesn't. That could lead to potential incorrect behavior.

We managed to find this issue and some others by using our static code analyzer. We actually dedicated a [part of our article](https://www.viva64.com/en/b/0676/) to checking Kodi project.
We also would like to offer you a free license for your usage of our static code analyzer so you can check this project by yourself and get rid of some bugs which could be found:

Name: Kodi media player
Key: A9F0-51ZZ-1KXG-T6R4
License Type: Team9 License up to 9 developers
License Valid Thru: Nov 08, 2019

**Comment by DaveTBlake** [comment]
Yes there is a semi-colon missing
