### ISSUE TITLE
Menu stutters while video is playing

### ISSUE THREAD

**Issue by S2-** [xbmc/xbmc#16752]
### Describe the bug
Here is a clear and concise description of what the problem is:
While playing back video on a Bqeel Android 9.0 TV Box R1 Pro - RK3318 Quad-Core 64bit Cortex-A53 cpu, if I press back on the remote to go back to the main menu or some other gui part of kodi, the menu stutters/flickers badly.
This makes it difficult to select items on the gui.
The android box is connected via hdmi to a monitor.
This happens only while there is some video playing back in the background. If I stop the video everything is fine.

If I disable video acceleration in settings -> player, the menu works fine. But if I do that the video does not play back smoothly any more. So the video acceleration has something to do with it.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
The animations in the menu/gui part of kodi should be smooth and nice, and it should be possible to select items in the menu.

## Actual Behavior
The menu animations stutter/flicker badly, and sometimes does not appear at all. This makes it difficult to navigate video controls and menu items.

## Possible Fix
Disable video acceleration. Disabling video acceleration breaks the video playback, but fixes the menus.

### To Reproduce
1. buy an RK3318 cpu android device
2. install the latest kodi version from the play store
3. start a video
4. press esc to get to the video controls
5. see that video controls stutter badly and it becomes very frustrating selecting something.

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/bitamujoye

### Screenshots
Here are some links or screenshots to help explain the problem:
Not applicable?

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 9.0 
 - Kodi version: 18.4

**Comment by DaVukovic** [comment]
Not providing the debuglog will get this issue closed as the bot mentions. 

Just that you are aware.

**Comment by DaVukovic** [comment]
In case you might wondering why this issue still has the "ignored rules" label set....your log is full of banned add-ons. 

Please provide a new logfile where those add-ons and repositories are removed in the next 7 days or your issue will be closed. 

Thanks in advance

**Comment by S2-** [comment]
Thanks @DaVukovic, I didn't know there is a list of banned addons. Those addons where already installed on the device I bought on amazon. I will try to reset everything to default and reproduce the issue.

**Comment by S2-** [comment]
I tried to get to a clean state and reuploaded a log.
