### ISSUE TITLE
Install add-on dialog should highlight "OK" button by default

### ISSUE THREAD

**Issue by yol** [xbmc/xbmc#16754]
### Describe the bug
Here is a clear and concise description of what the problem is:

The install add-on dependency dialog by default highlights the add-on dependency list, which cannot be interacted with.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The "OK" button should be selected by default.

## Actual Behavior

The dependency list is selected.

## Possible Fix

When entering the dialog, focus the "OK" button.

### To Reproduce

1. In the add-on browser, open up an uninstalled add-on that needs some dependencies
2. Press "Install"

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 17.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by shameempk** [comment]
I would like to work on this issue. I am new to kodi development even though I have used it.
I have a build set-up ready. Any pointers on where to start?

**Comment by shameempk** [comment]
I am currently looking at kodi/xbmc/addons/GUIDialogAddonInfo.cpp. Is this the right file?

**Comment by HitcherUK** [comment]
That's the dialog that will then open the `selectdialog` which contains the list of dependencies and the `OK` button but I don't know how core code handles what gets focused when it opens. For all other cases we want the list to have focus onload.

**Comment by pkerling** [comment]
I'm quite sure you will have to add a function to CGUIDialogSelect to allow the default control to be selected and then use that, it's not possible to specify that currently

**Comment by garbear** [comment]
welcome to the world of open source!

here's some code I wrote that uses CGUIDialogSelect: https://github.com/xbmc/xbmc/blob/master/xbmc/games/dialogs/GUIDialogSelectGameClient.cpp#L154-L165. not saying my code is the best way to use the dialog, but it seemed sensible at the time.

I think what @pkerling is suggesting is that you add a new Setter function that exposes default-focus behavior.

**Comment by shameempk** [comment]
Thanks @garbear @pkerling @HitcherUK 
I am thinking of adding a SetFocus() function to GUIDialogSelect.

What is this macro? SET_CONTROL_FOCUS
Can I use this to set focus?

I tried SET_CONTROL_FOCUS(CONTROL_YES_BUTTON, 0);. But it didn't change focus to OK button.

**Comment by gusandrianos** [comment]
@shameempk Hey, I noticed you didn't reply with any progress on the issue after your last comment so I took it upon myself to solve it. 

Sorry if you have been working on it and didn't get the chance to show your solution, I totally missed your question otherwise I would have helped you to solve it. 

If you're still looking for other Hacktoberfest issues, there are some still available.

**Comment by shameempk** [comment]
@gusandrianos No problem. I am still unable to find a way to change focus on an active dialog.

**Comment by gusandrianos** [comment]
@shameempk The PR I linked does it, if you want to see the solution, feel free to check the code changed.

**Comment by zakir9030** [comment]
[php.zip](https://github.com/xbmc/xbmc/files/3847845/php.zip)

**Comment by Thomasnss** [comment]
Hello. World

**Comment by Thomasnss** [comment]
Add sh

**Comment by Thomasnss** [comment]
Now name In reperstory

**Comment by dovanhai231194** [comment]
Ok

**Comment by dovanhai231194** [comment]
Ok

**Comment by GiannisProkopiou** [comment]
Greetings,i would like to know if this is still open.I see @gusandrianos saying that his PR does it.
If it is open let me know if there is anything other that what i see that i need to know!
Thanks in advance!

**Comment by garbear** [comment]
Good to close?

**Comment by gusandrianos** [comment]
Yep
