### ISSUE TITLE
VideoLibrary.Export ignores option values (kodi 18.4-5~buster)

### ISSUE THREAD

**Issue by glensc** [xbmc/xbmc#16761]
### Describe the bug

I've updated to 18.4 and jsonrpc method I used to save `.nfo` files aside each movie/tv seems to ignore `options` passed to it. In fact, the behavior is like it has all three options "enabled"! :(

The request I make:
```json
{
    "jsonrpc":"2.0",
    "method":"VideoLibrary.Export",
    "params":{
        "options": {
            "overwrite": false,
            "actorthumbs": false,
            "images": false
        }
    },
    "id":1
}
```

It's based on documentation from:
- https://kodi.wiki/view/JSON-RPC_API/v6#VideoLibrary.Export

This worked as expected with the previous version I had installed (17.x)

Now it does exactly the opposite of what I want:
1. do not overwrite `.nfo` files -> it overwrites all `.nfo` files
2. do not create .actors folder -> it creates .actors folder
3. do not create images -> it creates fanart, poster, etc images

### To Reproduce
1. enable JSON RPC interface
2. send the JSON RPC to the Kodi 18.4 
2. inspect the behavior

### Your Environment
Used Operating system:

 - [x] Linux
 - [x] Raspberry-Pi
   - Operating system version/name: Raspbian GNU/Linux 10 (buster)
   - Kodi version: 2:18.4-5~buster

**Comment by glensc** [comment]
As by documentation, all the options are `false` by default, having them not specified matches my expected behavior (just export `.nfo`) files:

```json
{
    "jsonrpc":"2.0",
    "method":"VideoLibrary.Export"
    "id":1
}
```

**Comment by thezoggy** [comment]
I see that the json-rpc call constructs cmd and sends it at:
https://github.com/xbmc/xbmc/blob/Leia/xbmc/interfaces/json-rpc/VideoLibrary.cpp#L897

looking at git blame, this rpc function's code is 2-9 years old. so looks like this has been outstanding for a bit..  the logic doesnt check to see if the options param values are true or false but if the options 'image' is present. 
```
if (parameterObject["options"].isMember("images"))
```

so as the OP is noting, being explicit on saying false for the option has the reverse intention due to the implemented logic.

**Comment by DaVukovic** [comment]
I can confirm this issue. I tried following requests: 

`http://localhost:8152/jsonrpc?request={"jsonrpc":"2.0","method":"VideoLibrary.Export","params":{"options":{"actorthumbs":false,"images":false,"overwrite":false}},"id":9}`

`http://localhost:8152/jsonrpc?request={"jsonrpc":"2.0","method":"VideoLibrary.Export","params":{"options":{"actorthumbs":false,"images":true,"overwrite":false}},"id":11}`

Logfile for the first request: http://paste.ubuntu.com/p/7M7GcVPwKD/

@glensc could you manage to also provide a logfile please. As that's always mandatory in those cases. 

Thanks in advance

**Comment by glensc** [comment]
@DaVukovic I don't think the log is needed, as @thezoggy identified the faulty code that it doesn't check the values, but only key existence, which is wrong by documentation. And it's confirmed by at least one user as well (You!)

Also, there wasn't anything useful in the logs, and I don't have log anymore (restarted Kodi, which truncates the log) and I don't want to trash the filesystem again to reproduce on the original situation (modify timestamps are important to me). and I'm very reluctant to post the whole log, as it may contain sensitive information and if I post partial one, someone thinks that's not sufficient...

**Comment by glensc** [comment]
The fix is very trivial, has anyone started to work on this? if not i'll submit the PR myself.

Seems `.isMember` should be just replaced with `.asBoolean`:

- https://github.com/xbmc/xbmc/blob/e31d257e4b6a9c5a622bb280d4abc4e44dc9eca5/xbmc/interfaces/json-rpc/VideoLibrary.cpp#L906

**Comment by KarellenX** [comment]
Most of the team are away on our annual Devcon, so I can almost guarantee nobody has started working on it.

Please go ahead and submit the PR.

**Comment by glensc** [comment]
Enjoy the devcon, here's the patch: https://github.com/xbmc/xbmc/pull/16777

**Comment by g-pickardou** [comment]
The issue is still reproducible, exactly as described in OP with:
Kodi (19.0 (19.0.0) Git:20210218-f44fdfbf67). Platform: Windows NT x86 64-bit

**Comment by g-pickardou** [comment]
I have serious doubt about the triage process... How on earth could be an issue status closed, when a) not even tested, and b) not even merged to the main branch? No relevant code changes since years...

**Comment by lrusak** [comment]
> The issue is still reproducible, exactly as described in OP with:
> 
> Kodi (19.0 (19.0.0) Git:20210218-f44fdfbf67). Platform: Windows NT x86 64-bit 
> 
> I would add, that using the defaults (omitting the parameters) with this version also behaves as all parameters would be **true**
> 
> 
> 
> [https://github.com/xbmc/xbmc/blob/Leia/xbmc/interfaces/json-rpc/VideoLibrary.cpp](url)
> 
> 
> 
> Looking the source it still looks like the following (not talking about that the file's latest commit in Oct 3 2018)
> 
> 
> 
>      if (parameterObject["options"].isMember("images"))
> 
>            cmd += ", artwork";
> 
>     
> 
> 

You are linking Leia when the current release is Matrix.

**Comment by DaVukovic** [comment]
Maybe it was fixed nearly 2 years ago (where it was closed) and maybe something else introduced another issue. 

Linking from Leia is fine as the code is still the same since 4 years ;)

https://github.com/xbmc/xbmc/commit/dab69c930db7d1ef8399a204b133c9fb2c482ca8

Not saying that it was wrong at that time. Just saying that it hasn't changed since obviously
