### ISSUE TITLE
[PVR] Past EPG data (mostly) deleted on reconnect to TVHeadend server

### ISSUE THREAD

**Issue by arnova** [xbmc/xbmc#16762]
Whenever my system suspends and resumes again, any past EPG is (mostly) deleted. As it turns out the actual action that triggers the EPG deletion is the disconnect, and specifically the reconnect to the TVHeadend server.

I have the option "Past days to display" set to "7 days". I also tried enabling/disabling "Don't cache in local database" but that doesn't make a difference. I'm not sure whether this is a Kodi/PVR problem or a problem in the HTSP addon.

Log can be found here: https://secure.eld.leidenuniv.nl/~arnova/kodi-pvr-epg-past-bug.log . I've also added 2 screenshots showing the issue here: https://secure.eld.leidenuniv.nl/~arnova/pvr-epg-bug1.png and https://secure.eld.leidenuniv.nl/~arnova/pvr-epg-bug2.png

**Comment by ksooo** [comment]
I will take a look. I guess this is a Kodi problem, not something with pvr.hts.

**Comment by arnova** [comment]
> I will take a look.

Thanks. Let me know if you want me to test/try something.

**Comment by arnova** [comment]
Could be related to https://github.com/xbmc/xbmc/issues/15497

**Comment by ksooo** [comment]
That issue is about exit behavior. This issue is about suspend. If store in local DB is disabled it is okay to loose old epg data on Kodi restart. This should not happen on resume, though, regardless of state of store in local DB.

**Comment by ksooo** [comment]
Could you give Matrix nightly a try and report back?

**Comment by ksooo** [comment]
Have you tried without the addon service.tvh.manager?
Please activate EPG in component specific logging and post a new log.

**Comment by arnova** [comment]
Will test with Matrix this week and I'll also provide a new log with EPG logging enabled.

Note that in the meantime I've disabled "Async EPG update" and that seems to fix my problem. It gets even stranger: I've reenabled the option and the problem is still mostly gone although some holes start to appear again. Does this give a clue?

**Comment by ksooo** [comment]
Does disabling the add-on service.tvh.manager make a difference?

**Comment by ksooo** [comment]
In any case: disable the local epg database. Buggy (fixed in matrix?) and does not add any value.

**Comment by arnova** [comment]
> In any case: disable the local epg database. Buggy (fixed in matrix?) and does not add any value.

@ksooo : I disabled the local epg database and that  made things even worse: ALL past EPG data is deleted after a resume from suspend. Note that I've noticed that the past EPG data does exist if you immediately check the guide after resume, but as soon as TVHeadend reconnects it gets deleted. New log with EPG component logging enabled here: https://secure.eld.leidenuniv.nl/~arnova/kodi-with-epg-component-logging . Hopefully it gives a clue.

**Comment by arnova** [comment]
@ksooo : I've been testing this for a few days now. And it seems that the only way I can reliably make this work at the moment is by having "Don't cache in local database" disabled(!) and in the TVHeadEnd addon disable "Async EPG updates".

**Comment by ksooo** [comment]
Again, please disable service.tvh.manager and report back whetehr this makes a difference. I want to make sure we don't have any bad side effects here.

**Comment by ksooo** [comment]
Re. service.tvh.manager: What do you need this addon for? I for years used a tvheadend server running on the same machine as Kodi (a LibreELEC box) , including suspend/automatic resume of the box for recordings etc. wizhout the need for any special addon. Things have improvend since Eden...

**Comment by arnova** [comment]
> Re. service.tvh.manager: What do you need this addon for? I for years used a tvheadend server running on the same machine as Kodi (a LibreELEC box) , including suspend/automatic resume of the box for recordings etc. without the need for any special addon. Things have improvend since Eden...

Will try without the addon although afaik if I want my Linux HTPC to powerup/resume automatically for recordings I need this addon? But from what you're saying I get the idea that we also have this functionality in Kodi core? How is that suppose to work?

**Comment by ksooo** [comment]
> But from what you're saying I get the idea that we also have this functionality in Kodi core? 

 Yes, at least if tvh server and kodi are located on the same machine.

> How is that suppose to work?

![screenshot001](https://user-images.githubusercontent.com/3226626/67284233-7df60f80-f4d5-11e9-8730-fa5d6b322be6.png)

Wakeup command is a smal script, like provided by LibreELEC: https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/mediacenter/kodi/scripts/setwakeup.sh

**Comment by arnova** [comment]
> 
> 
> Again, please disable service.tvh.manager and report back whetehr this makes a difference. I want to make sure we don't have any bad side effects here.

Just test it without the service enabled: doesn't make a difference. I also figured out the exact steps to reproduce this issue (for you):
- Disable EPG database storage
- Enable async EPG transfers in the tvheadend addon
- Reboot your system (so it starts with an empty epg)
- Leave it running for eg. an hour
- Stop the tvheadend service and wait till Kodi reports it lost connection to it
- Start the tvheadend service again and wait till Kodi reports it established the connection again
- Check your guide and notice all past data is gone.

**Comment by ksooo** [comment]
Works as designed. On reconnect after backend failure PVR manager restarts to synchronize backend data with local data. And as tvheadend does not have the outdated epg data anymore they will be gone in Kodi as well.

**Comment by arnova** [comment]
> Works as designed. On reconnect after backend failure PVR manager restarts to synchronize backend data with local data. And as tvheadend does not have the outdated epg data anymore they will be gone in Kodi as well.

Yes, this means that everytime Kodi looses connection to the server any past data will be wiped. But perhaps more important: when I disable async EPG transfers AND enable database caching I can workaround this issue. I don't know much about EPG/PVR internals but I guess using database should always provide past EPG data, even if not available from the TVHeadend backend.

**Comment by ksooo** [comment]
>  using database should always provide past EPG data, even if not available from the TVHeadend backend.

Yes.  And if this does not work, please open an issue.

**Comment by arnova** [comment]
> > using database should always provide past EPG data, even if not available from the TVHeadend backend.
> 
> Yes. And if this does not work, please open an issue.
> 
> > when I disable async EPG transfers AND enable database caching I can workaround this issue.
> 
> Do you say it does not work if you enable both epg DB storage and async epg transfer? Iirc, this is indeed broken in Leia but fixed in Matrix.

Open a new issue? Isn't this issue sufficient?

**Comment by ksooo** [comment]
Please answer my question.

**Comment by arnova** [comment]
> 
> 
> Please answer my question.

Oh sorry, I missed the second part of your reply. Didn't try with Matrix yet but will test it as soon as I can find the time (= my kid allows it ;-)). Why wasn't that backported to Leia? No trivial fix?

**Comment by ksooo** [comment]
I'm not even sure it IS actually fixed for Matrix. That's why I'm asking you to test. I think I did something in that area but can't remember right now.

**Comment by ksooo** [comment]
Could you please runtime test the backport of the Matrix fix? => #16832

**Comment by arnova** [comment]
@ksooo : I've tested #16832 and it indeed seems to fix my issue with async epg transfers. Thanks!

**Comment by arnova** [comment]
> @ksooo : I've tested #16832 for a while now and it indeed seems to fix my issue with async epg transfers. Thanks!
