### ISSUE TITLE
Add Setting to disable picture zoom minimap

### ISSUE THREAD

**Issue by Heathcliff77** [xbmc/xbmc#16764]
### Describe the bug

When a picture is zoomed in, a minimap appears in the upper right corner of the screen. 
Screenshot: https://imgur.com/Fh5aJjT
This minimap is sometimes annoying, it blocks the rest of the picture.

I can't find a way to get rid of the minimap.
There should be an option in Settings in Kodi for toggling the minimap functionality on/off. 

## Expected Behavior

An option in Settings in Kodi for toggling the minimap functionality on/off shall exist.

## Actual Behavior

Right now there is no way to disable picture zoom minimap.

### To Reproduce

1. View a picture (JPG, PNG et.c.) using "Picture"
2. Zoom in
3. Minimap will appear,
4. Zoom out >> Minimap goes away

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/rakusapaxi.kodi
Around line 8564 I view a picture and zoom in and out.

### Screenshots 

Screenshot of picture zoom minimap: https://imgur.com/Fh5aJjT

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora Linux 30 and Android 9.
 - Kodi version: 18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
This looks more like a feature request than a bug
