### ISSUE TITLE
7.1.2 atmos issue on AFTV stick 4k 

### ISSUE THREAD

**Issue by ilbefun** [xbmc/xbmc#16772]
### Describe the bug
Here is a clear and concise description of what the problem is:

when I played 5.1.2 atmos media, my sony speakers recoganized correctly as Dolby Atmos
but when 7.1.2 atmos media was played, the speakers only display LPCM 7.1CH

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

7.1.2 Atmos can be recoganized by speakers

## Actual Behavior

speakers display LPCM 7.1CH

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Please provide a debug log which captures the problem.

**Comment by M2k80** [comment]
if i am right, is the FTV 4k not able to play Truehd Atmos, only DD+ with atmos.
https://translate.google.at/translate?hl=de&tab=rT&authuser=0&sl=de&tl=en&u=https%3A%2F%2Faftvhacks.de%2Fquicktipp-kodi-dts-passthrough-beim-neuen-fire-tv-stick-4k-aktiveren%2F

**Comment by DaVukovic** [comment]
No log, no further reaction since 2 weeks. Issue closed
