### ISSUE TITLE
Typo error in "xbmc/addons/skin.estuary/language/resource.language.da_dk/strings.po"

### ISSUE THREAD

**Issue by SteenH68** [xbmc/xbmc#16774]
### Describe the bug
There is a typo error in "xbmc/addons/skin.estuary/language/resource.language.da_dk/strings.po" file.

Line 209: msgstr "Tryk {B]Venstre[/B] for tilbagespoling, eller [B]Højre[/B] for at spole fremad"

## Possible Fix

Change '{' to '[' in the relevant line.

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Kodi typo error](https://user-images.githubusercontent.com/56536039/66737753-1bfe3000-ee6d-11e9-9c0d-a983061cef3d.PNG)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Libreelec 9.2 / Windows 10 Build 1903
 - Kodi version: 18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Thanks for reporting. I've fixed that in Transifex and the next language update will have that fix included
