### ISSUE TITLE
Python attribute error in South Park Addon

### ISSUE THREAD

**Issue by nanthony21** [xbmc/xbmc#16781]
### Describe the bug
Here is a clear and concise description of what the problem is:
When trying to stream an episode of South Park using the official add-on the stream fails to start. `kodi.log` reveals what appears to be a serious issue in a python script, there are a few other errors reported which may or may not be related. I have noticed that this python error occasionally pops up when doing other things in Kodi.

## Expected Behavior
Kodi begins to stream a video from the South Park addon.

## Actual Behavior
After selecting an episode kodi shows the loading screen for about 1 second. The loading screen briefly disappears and then it reappears for ~10 seconds. Then kodi returns to the episode selection menu.

### To Reproduce
1.  Go to the official `South Park` addon
2. Select any episode to play
3. I had one time where the stream miraculously worked. Every other time it has failed.

### Debuglog
The debuglog can be found here, this log shows startup, navigation to the South Park addon, and a single failed attempt to view an episode: https://paste.kodi.tv/raw/rimunuyudi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
I used to use the official SouthPark Add-on all the time on test builds of Kodi. After being away for a few months I came back and realized that Kodi V18 now had an official release version. After updating to the Kodi v18 release I am having this issue.

### Your Environment
Used Operating system:
This is Kodi v18 running in OSMC on an rPi3

**Comment by DaVukovic** [comment]
Thanks for reporting

If the error is limited to this specific add-on, then it's most likely not a Kodi problem and you reported it at the wrong section. I would suggest to ping the author at the forums: 

https://forum.kodi.tv/showthread.php?tid=224662&page=12

**Comment by ronie** [comment]
looking at the log, the error is produced by service.osmc.btplayer.
i'm not familiar with that addon, it is not in our repo.
you might want to contact the addon dev of service.osmc.btplayer as well.

**Comment by nanthony21** [comment]
Thanks for the help. I tried libreelec and the problem is solved. I'll report this on osmc's forums.
