### ISSUE TITLE
OSS broken on FreeBSD

### ISSUE THREAD

**Issue by rozhuk-im** [xbmc/xbmc#16780]
### Describe the bug

OSS does not work on FreeBSD.

At 44a808cb4aed399ea65caf7d85bc0ee647311abf @lrusak - removes  xbmc/platform/freebsd/OptionalsReg.cpp and set xbmc/platform/linux/OptionalsReg.cpp, and this brokes OSS initialization.

xbmc/platform/freebsd/OptionalsReg.cpp was added at: dbfe0bc969f582f32b572181c7ce1e163e68bce0 by @t6 

## Expected Behavior
I expect that OSS sound system will work like before.

## Actual Behavior
It does not work, I see no devices in audio output.

## Possible Fix
Partially revert 44a808cb4aed399ea65caf7d85bc0ee647311abf

### To Reproduce

1. Build and install master or our current multimedia/kodi-devel port ( 0bc5954818e6b55a98f551a540a4d3589b60297f ) without sndio and pulse support
2. Run
3. Go to setting, audio output section and see no devices

### Your Environment
Used Operating system:

 - [x] FreeBSD
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: FreeBSD rimwks 12.1-PRERELEASE amd64
 - Kodi version: 0bc5954818e6b55a98f551a540a4d3589b60297f

**Comment by DaVukovic** [comment]
We will most likely need a logfile.

Or are you saying that if you have done the changes you mentioned above will fix that issue? If so, feel free to PR

**Comment by rozhuk-im** [comment]
There is no ```CAESinkOSS::Register();``` in kodi code base, OSS does not initialize.

**Comment by fuzzard** [comment]
OSSSink still exists at xbmc/cores/AudioEngine/Sinks/AESinkOSS.h

short term fix for yourself could be to just do the following 2 patches and then recompile

```
--- a/xbmc/platform/linux/OptionalsReg.cpp
+++ b/xbmc/platform/linux/OptionalsReg.cpp
@@ -27,10 +27,23 @@
 }
 #endif
 
+//-----------------------------------------------------------------------------
+// OSS
+//-----------------------------------------------------------------------------
+
+#ifdef HAS_OSS
+#include "cores/AudioEngine/Sinks/AESinkOSS.h"
+bool OPTIONALS::OSSRegister()
+{
+  CAESinkOSS::Register();
+  return true;
+}
+#else
 bool OPTIONALS::OSSRegister()
 {
   return false;
 }
+#endif
 
 //-----------------------------------------------------------------------------
 // PulseAudio
```

and then in cmake/scripts/freebsd/ArchSetup.cmake

```
--- a/cmake/scripts/freebsd/ArchSetup.cmake
+++ b/cmake/scripts/freebsd/ArchSetup.cmake
@@ -31,4 +31,4 @@
 endif()
 
 # Additional SYSTEM_DEFINES
-list(APPEND SYSTEM_DEFINES -DHAS_LINUX_NETWORK)
+list(APPEND SYSTEM_DEFINES -DHAS_LINUX_NETWORK -DHAS_OSS)
```

Long term proper fix is more likely to add a cmake/modules/FindOSS.cmake to detect OSS and then define HAS_OSS if found

**Comment by rozhuk-im** [comment]
Thank you, I will try it in next 6 hours.
I hope a long term fix will look like partial revert that restore xbmc/platform/freebsd/OptionalsReg.cpp.
@t6 already done this in past.

**Comment by rozhuk-im** [comment]
Yes, patch works, as expected.

**Comment by fuzzard** [comment]
The team is always open to PR's. 
I dont run freebsd, so i really dont have an idea around audio systems on it (is alsa/pulse able to be used? is it only OSS?)

As stated above, what i believe the most acceptable fix would be to add a findmodule for OSS to detect if its on the system the same as alsa/pulse. If OSS is the only sound system on freebsd, then this could be skipped, and you just hardcode the define in the archsetup as given in the above patches.

If freebsd doesnt need anything else in OptionalsReg, then a revert to the freebsd specific one could be done, but if it does use the linux optionalsreg for other things (alsa/pulse?) then duplicating the entire thing would probably not be recommended, as it will most likely sit and rot unless a freebsd platform dev takes up the mantle for maintenance.

**Comment by rozhuk-im** [comment]
FreeBSD have: OSS in kernel and alsa, pulse, sndio, jack and probably something more as userspace wrappers/libs. I use sndio in past few day, until apply you patch.

DragonFlyBSD - OSS, OpenBSD and NetBSD - OSS via wrapper lib, if I understand correct.

OSS pr: #13793 about how it should be, @FernetMenta approve it.

Current patch looks good to me :)
IMHO, it restores all logic that was lost in 44a808cb4aed399ea65caf7d85bc0ee647311abf.

You can take https://github.com/FreeRDP/FreeRDP/blob/master/cmake/FindOSS.cmake to detect OSS.
And extend logic in ```xbmc/cores/AudioEngine/Sinks/AESinkOSS.cpp``` by adding:
```
#if defined(__OpenBSD__)
#include <soundcard.h>
#else
#include <sys/soundcard.h>
#endif
```

**Comment by fuzzard** [comment]
As i said, i dont run freebsd, so i wont be doing a PR. Feel free to send one through yourself though.
The info ive said earlier is the best advice i could give to get it through clean and quick, however other team members may have different views/requirements, only way to find out is to PR.

**Comment by rozhuk-im** [comment]
Thanks, I will try to do this in next few days.

**Comment by fuzzard** [comment]
Thanks for reporting, as well as PRing a fix
