### ISSUE TITLE
Can you help to bring the Kodi 18.4 update to the F-Droid repo?

### ISSUE THREAD

**Issue by 4tip** [xbmc/xbmc#16798]
### Describe the bug
Here is a clear and concise description of what the problem is:

The update to Kodi 18.4 is not available in the F-Droid repo. They only have the 18.3 version.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Can you help to bring the Kodi 18.4 update to the F-Droid repo?

## Actual Behavior

It's not updateable.

## Possible Fix

I miss the competense for this. I'm just a F-Droid user.

### To Reproduce

1. https://f-droid.org/en/packages/org.xbmc.kodi/
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
As this is not a bug report and this section is only meant for that purpose, I'm going to close that. 

We are also somewhat in contact with responsible persons. Not saying that I know how it will work out, but let's see

**Comment by Korb** [comment]
Same with 21.0. Google Play:
![Screenshot_2024_0429_080142](https://github.com/xbmc/xbmc/assets/3509797/d37df7ad-6da9-4346-9c17-429f6257fe29)
F-Droid:
![Screenshot_2024_0429_080224_org fdroid fdroid](https://github.com/xbmc/xbmc/assets/3509797/677b2235-ea37-4138-be13-d4ccabfd9bc8)
