### ISSUE TITLE
Missing context menu in MyMusicPlaylistEditor

### ISSUE THREAD

**Issue by nonJon** [xbmc/xbmc#16793]
### Describe the bug

As of Krypton, the context menu from the songs/tracks  list (list id=100) is not available. 

## Expected Behavior

A context menu should be available to /move up/move down/clear/save/ etc allowing users to reorder tracks in an existing playlist.

## Actual Behavior

Cannot summon context menu at all.  Tested with multiple skins including Estuary and Confluence.  Working in Jarvis 16.1 and older versions of KODI.

## Additional context or screenshots (if appropriate)

Issue discussed/confirmed in this forum thread:
https://forum.kodi.tv/showthread.php?tid=330277

### Your Environment
Used Operating system: 

Irrelevant

**Comment by DaveTBlake** [comment]
Fixed by https://github.com/xbmc/xbmc/pull/18838 in v19 beta 2
