### ISSUE TITLE
kodi 18.4 on rpi 4 hang (kodi 18.4-5~buster)

### ISSUE THREAD

**Issue by vtolstov** [xbmc/xbmc#16796]
### Describe the bug
I have rpi 4 attached via hdmi to my tv and play video from youtube via youtube plugin. Sometimes when i'm turn off tv without stopping playing video in kodi, and after 2-3 hours power on tv video can't be played. After i'm hit next button i see loading indicator and kodi does not respond to any action.

## Expected Behavior
continue when you left

## Actual Behavior
kodi does not respond

### To Reproduce
install kodi 18.4-5~buster, play video from from youtube and poweroff tv. After some hours power on tv and check.

### Debuglog
The debuglog can be found here: https://gist.github.com/456668902babab8d9d658bd1e9686bfd

### Your Environment
Used Operating system:
rpi 4 with debian buster and kodi 18.4
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [x] Raspberry-Pi
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.4-5~buster with linux 4.19.75-v7l+

**Comment by DaVukovic** [comment]
Your installation has banned add-ons installed. 

Please retry with a vanilla Kodi which only has those add-ons installed which are needed to reproduce your issue. 

This bug report will be closed after 7 days if you haven't submitted a new and clean log.

**Comment by vtolstov** [comment]
did you mean this log message
```
2019-10-16 21:17:15.776 T:2774196432 WARNING: Repository add-on superrepo.kodi.krypton.programs uses plain HTTP for add-on downloads in path http://redirect.superrepo.org/v7/addons/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
```
?

**Comment by chewitt** [comment]
He was referring simply to the presence of banned add-ons being installed.

**Comment by kib** [comment]
also, that is not a log with debugging enabled

**Comment by vtolstov** [comment]
ok thanks, where i can find info how to enable debug log? i'm try to reproduce issue with debug enabled

**Comment by kib** [comment]
https://kodi.wiki/view/Log_file/Easy#Steps

**Comment by DaVukovic** [comment]
No further reaction, no logfile. 

Happy to re-open this issue if a new and clean logfile will be provided.
