### ISSUE TITLE
negative GPU temperature is displayed

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/xbmc#16809]
### Describe the bug
Here is a clear and concise description of what the problem is:

System info - Video displays negative temperature. Tested on macOS Catalina with integrated graphics card active.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Temperature value displayed is above zero.

## Actual Behavior

Temperature value displayed is below zero, but my mbp is not in a fridge or Siberia.

### To Reproduce

Check system info when integrated graphics card is active.

### Debuglog

The debuglog can be found here: I'll attach one if really needed.

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Screenshot 2019-10-19 at 17 31 54](https://user-images.githubusercontent.com/1557784/67150733-3a788700-f2c4-11e9-8553-25dc684cac98.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS 10.15 Catalina
 - Kodi version: 18.4
 - Graphics card of mbp used: integrated.
 - Device: MacBook Pro 2010.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by kambala-decapitator** [comment]
the following entitlements from https://github.com/oshi/oshi/issues/343 worked:
```
  <key>com.apple.security.temporary-exception.sbpl</key>
  <array>
  	<string>(allow iokit-open (iokit-user-client-class "AppleSMCClient"))</string>
  </array>
```
but I also had to replace `TC0D` code with `TC0P` to fix CPU temperature on mini 2018. Couldn't find the right GPU code.

**Comment by enen92** [comment]
This is likely fixed by https://github.com/xbmc/xbmc/pull/23770
