### ISSUE TITLE
Kodi 18.4 won't Stream

### ISSUE THREAD

**Issue by DonaldMaulidi** [xbmc/xbmc#16815]
### Describe the bug
Here is a clear and concise description of what the problem is:

I consider this a bug as neither of the add-ons which I have on my MacBook are able to stream, somehow the very same add-ons work on my Xbox.  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect to be able to stream movies/series from any of the add-ons which I have installed on my MacBook the same way they work on my Xbox or Fire Stick. 

## Actual Behavior

Whenever I attempt to stream a movie/series Kodi loads up the screams and pop up box but never plays. There's no error that pops up on the screen it just stops loading. 

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/eninecaqoh.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS MoJave
 - Kodi version: 18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HitcherUK** [comment]
No support for piracy addons, please read the rules in future.
