### ISSUE TITLE
No video on 18.4, but same machine on 17.6 works 

### ISSUE THREAD

**Issue by Stady234** [xbmc/xbmc#16819]
I have an older HP mini desktop that i have been using for about 2yrs.  The last "auto update" or any update for that manner has been to 17.6 Krypton.  The Win7 has been disabled from internet.  I load movies via the external drive from my machine, then restart Kodi to add to library for the kids.

I tried to update to the 18.4 and no video on any file (just color flashes) within kodi.  I can independently start any video and everything works as intended in the OS.  

I fully uninstalled and deleted all preferences... then reinstalled 17.6.. to which everything works.  So I performed an upgrade again.. and the problem happened again.

I tried to follow multiple YT help videos about changing the different "render" methods, but no change.

## Expected Behavior
Play video file and see the content.

## Actual Behavior
Video plays, but only audio is heard.. and the video signal is only flashes of color.

## Possible Fix
Revert back to 17.6

### To Reproduce
upgrade 17.6 to 18.4

### Your Environment
Used Operating system:
 - [ ] Windows

 - Operating system version/name:
   Windows 7
 - Kodi version:
17.6/18.4

**Comment by DaVukovic** [comment]
Please provide the debuglog we asked for at our templare.

Thanks
