### ISSUE TITLE
PINSentry can now be easily circumvented due to disabling plugins now on context menu

### ISSUE THREAD

**Issue by nwaltham** [xbmc/xbmc#16810]
This pull request https://github.com/xbmc/xbmc/pull/11124 as been included in Leia.

The result is that it breaks PINSentry (useful for parental controls on Kodi), 
https://github.com/robwebset/script.pinsentry/wiki

since the plugin can be easily disabled from the context menu. 

To fix, please allow this option to be disabled in the settings.

**Comment by DaVukovic** [comment]
Generally I wouldn't call this a "bug". But I understand the problem. Maybe the PR in question could be modified in a way, that the enable/disable option in the context menu is only visible while in Add-ons -> My Add-ons -> <category> -> <Add-on>. As the settings can be password protected by using profiles.
