### ISSUE TITLE
Kodi 18.4 TV Shows issue

### ISSUE THREAD

**Issue by stefano70** [xbmc/xbmc#16814]
### Describe the bug
Here is a clear and concise description of what the problem is:

Starting froma clean install of 18.4 on Windows
Adding a remote share as a source, type TV SHOW, using only local .nfo file
Nothing is scraped
Now... remove the TV SHOW source, then clean the library, then add the same source as MOVIE, it is scraped, now... change the content of the source from MOVIE to TV SHOW, it is now perfectly scraped.
In the Kodi v17 the bahaviour was correct

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Have a TV SHOW source being scraped without adding it firt as MOVIE then change to TV SHOW

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
An incomplete report and one that is most likely user error. 

I suggest starting on the forum first for assistance to rule out problems with your setup, steps you have taken or the nfo file. If it turns out to be a but, then you will be advised to repost an issue.

FYI, I do not encounter the problem when performing what you describe.

Closed.
