### ISSUE TITLE
SFTP Scraping Broken

### ISSUE THREAD

**Issue by HPMSGEN8** [xbmc/xbmc#16827]
### Describe the bug
Here is a clear and concise description of what the problem is:
SFTP Not Working From Parent To Child Objects

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
SFTP Scraping

## Actual Behavior
SFTP Not Working From Parent To Child Objects 

### To Reproduce
1. Setup The TVDB On Parent Folder
2. Setup he TVDB Child Folder

### Your Environment
Used Operating system:
 - Linux

 - Operating system version/name: CoreElec v9.2.0
 - Kodi version:

**Comment by arnova** [comment]
It's correct this isn't fixed in 18.4 and it also won't be fixed in future 18-series. You need Matrix/19 for this to work properly. Sorry, nothing we can do about it.

**Comment by HPMSGEN8** [comment]
@arnova If this is the case how do i set each folder via SSH to set "The TVDB" I really do not want to do one by one.

Also since i have SQL if i change to SMB or NFS i will lose my watched states and if so how do i recover from this.

Thanks.

**Comment by arnova** [comment]
If you want to switch to smb/nfs you could use path substitution: https://kodi.wiki/view/Path_substitution

**Comment by HPMSGEN8** [comment]
@arnova Thanks alot
