### ISSUE TITLE
KODI v19 interlaced video (e.g. TV RECORDS) seeking dont work! -Fundamental Funktion-

### ISSUE THREAD

**Issue by Gee1111** [xbmc/xbmc#16837]
### Describe the bug
Here is a clear and concise description of what the problem is:
 Seeking of interlaced Video dont work, it hangs on buffering

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

it seeks

## Actual Behavior

it dont seeks

### To Reproduce

1. start a TV Record or another interlaced Video
2. try to seek!

### Debuglog

The debuglog can be found here: not needed

### Screenshots 
Here are some links or screenshots to help explain the problem:

Also not needed, easy 4 everyone to reproduce

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: v19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
No logs, no further reaction from the OP

closed
