### ISSUE TITLE
Unable to display value of action type setting

### ISSUE THREAD

**Issue by ronie** [xbmc/xbmc#16839]
i'm trying to migrate two weather addons to the new settings style, but i've hit a roadblock.

weather addons use an action type setting to select a weather location.
with the new style setting, the selected location (value) is not saved to settings.xml,
and thus not shown in the settings dialog.

**old style setting**

```
<setting id="Location1" label="32111" type="action" action="RunScript($ID,Location1)" enable="!eq(-1,)" default=""/>
```

![old](https://user-images.githubusercontent.com/687265/67627287-54ccda80-f859-11e9-98c3-f543786fc784.jpg)

**new style setting**
```
<setting help="" id="Location1" label="32111" type="action">
	<level>0</level>
	<dependencies>
		<dependency type="enable">
			<condition operator="!is" setting="API"/>
		</dependency>
	</dependencies>
	<data>RunScript(weather.weatherbit.io,Location1)</data>
	<control format="action" type="button"/>
</setting>
```

![new](https://user-images.githubusercontent.com/687265/67627294-7928b700-f859-11e9-9e25-4c0ff1173105.jpg)

**Comment by Montellese** [comment]
You're using the wrong setting type. A setting of `type="action"` does not have any value. It's only a setting to be able to initiate some kind of action.
If you want a setting that stores a string returned by some kind of action you need to use something like https://github.com/xbmc/xbmc/blob/master/system/settings/settings.xml#L3210-L3222 with `<data>RunScript(weather.weatherbit.io,Location1)</data>` as part of the `<control>` block.

**Comment by ronie** [comment]
thanx for the hint @Montellese , i've tried your suggestion but nothing happens when i click this settings button:
```
<setting help="" id="Location1" label="32111" type="string">
	<level>0</level>
	<default></default>
	<constraints>
		<allowempty>true</allowempty>
	</constraints>
	<control format="action" type="button">
		<data>RunScript(weather.yahoo,Location1)</data>
	</control>
</setting>
```
