### ISSUE TITLE
Addon get run twice when executed from settings

### ISSUE THREAD

**Issue by ronie** [xbmc/xbmc#16833]
### Describe the bug
Here is a clear and concise description of what the problem is:
an addon gets executed twice when it is run from addon settings.

example: try to setup a weather location in one of the weather addons.
(Settings > Services > Weather > -Settings)

edit: this issue happens with 'old-style' addon settings
`<setting id="Location1" label="32111" type="action" action="RunScript($ID,Location1)" enable="!eq(-1,)" default=""/>`

### Debuglog
https://paste.kodi.tv/nijukimiya.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi (19.0-ALPHA1 Git:20191025-8f0bbc3b0c). Platform: Linux x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
issue is caused by this commit: https://github.com/xbmc/xbmc/pull/16660/commits/84b719c36b4aebc1fd8d92230d051cc0c3c9af41

**Comment by Montellese** [comment]
@ronie thanks for looking into it. Did it work before 84b719c36b4aebc1fd8d92230d051cc0c3c9af41? Because I would expect actions not to work at all before that commit.

**Comment by ronie** [comment]
yeah sure, old-style action settings have always worked.

while removing that single commit fixes the old-style action setting, it breaks the new-style equivalent.

**Comment by Montellese** [comment]
Ah I missed your edit of the PR description. Could you try commenting out https://github.com/xbmc/xbmc/blob/master/xbmc/addons/settings/AddonSettings.cpp#L713 and see if this solves the issue for old-style action settings?

**Comment by ronie** [comment]
confirmed, that fixes the issue. thx!

**Comment by Montellese** [comment]
@ronie: Please see #16901. Since the python 3 merge my build setup is broken and I can't test it myself...
