### ISSUE TITLE
Audio is out of sync

### ISSUE THREAD

**Issue by felixg3** [xbmc/xbmc#16835]
## Bug report

Cross posted from https://github.com/CastagnaIT/plugin.video.netflix/issues/273, they have referred me to this repository to file the bugreport.

#### Your Environment
- Netflix add-on version: 0.15.7 (issue since 0.15.6)
- Operating system version/name: LibreElec 9.1.501 (9.2 beta)
- Device model:  Raspberry Pi 3b+

Used Operating system:
Raspberry-Pi / LibreElec

### Describe the bug
The audio is heavily out of sync. 2-3 Seconds. Setting the resolution to lower (576p) or disabling DD+ or other fancy audio codecs didn't help.

#### Expected behavior
Audio should be in sync.
#### Actual behavior
Audio is not in sync.

#### Steps to reproduce the behavior

1. Play any video
2. Wait 30 seconds before audio is out of sync
3. Pause video, it continues playing without sound
4. Start again, will be out of sync after that duration.

#### Possible fix
I don't know what could cause the issue.

### Debug log
The debug log can be found on my own server. I enabled Enhanced debugging due to the video related issues.
Check out the following 25k lines:
Edit: Nope, crashed my Etherpad.
Edit 2: a base64 paste of my .tar.xzipped log? Can it be more complicated? Nevermind here it is.
https://server.giessmann.net/pad/p/YsxCBFdBpUwxt0HYUpUR

I uploaded the log to Firefox Send, zipped.
https://send.firefox.com/download/004c4e191c5ee365/#1oOY5D2TQQsdmZbXixyCYQ

### Additional context or screenshots (if appropriate)
No screenshots useful

#### Installation
Using the CastagnaIT repository.

**Comment by felixg3** [comment]
Dear Team members, I think that the bug report is filled appropriately, following the template of the addon. It is almost identical, just in a different oder.

**Comment by popcornmix** [comment]
The log file shows you are playing the 1920x1080 stream which is too high for a Pi3B+ (for netflix which is software decoded).
Set it to 720p max resolution in inputstreamadaptive settings.

**Comment by felixg3** [comment]
popcornmix thank you for the reply. I will try that out and close the issue in case the issue goes away.

**Comment by felixg3** [comment]
Indeed, switching to 720p in the inputstreamadaptive settings fixed the issue. Changing the max resolution settings in the netflix addon wasn't enough.
