### ISSUE TITLE
Fire Stick 4K audio is out of sync for some videos

### ISSUE THREAD

**Issue by HunterZ** [xbmc/xbmc#16838]
### Describe the bug
Here is a clear and concise description of what the problem is:
Audio delayed by 300ms in some videos when played on Fire Stick 4K.

So far I have only encountered this with an SD video with MP3 audio. Sync is fine when played on my HTPC instead of the Fire Stick, so it's not necessarily a problem with the video itself.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Audio should be in sync with the video.

## Actual Behavior

Audio is delayed by 300ms.

## Possible Fix

Works best when set to 5.1 speakers, enable upmix, disable passthrough, except there is still a reverb effect indicating that some speakers are still out of sync.

### To Reproduce

1. Play video containing MP3 audio.
2. Observe that spoken dialogue or other audio is delayed by approximately 300ms.
3. Set audio delay to -300ms and observe that it is now in sync.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/apowomudut

### Screenshots 
Here are some links or screenshots to help explain the problem:

Not applicable.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Not available.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fire Stick 4K running Fire OS 6.2.6.8 (NS6268/2315) / Fire TV Home Version 6.1.8.1-012.
 - Kodi version: Kodi 18.4 2019-09-01 official Android release from the Kodi web site
- TV: Vizio E472VLE 47" 1080p
- A/V Receiver: Yamaha RXV-665.
- Other notes: Fire Stick is connected to the receiver via HDMI, and receiver is connected to TV via HDMI.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Have you tried the solution posted on reddit?

>in the fire stick settings click on Display and Sound, then go into Audio, scroll to Dolby Digital Output, and make sure this fits with the TV ability, meaning that thefirestick default is Dolby Digital Plus, 

Anyway, I don't see any logfile posted anywhere. I highly guess we might need that.

**Comment by HunterZ** [comment]
@DaVukovic bug updated with detailed info.

**Comment by HunterZ** [comment]
88keyz on the forum has found that this only occurs with videos that have stereo audio tracks: https://forum.kodi.tv/showthread.php?tid=343831&pid=2898606#pid2898606

This seems to corroborate with my finding, as I was testing a video with a stereo MP3 audio track, and it only occurs if I don't let Kodi upmix it to 5.1.
