### ISSUE TITLE
Some special characters not properly escaped in HTTPS source URLs

### ISSUE THREAD

**Issue by Maltz42** [xbmc/xbmc#16841]
### Describe the bug
Here is a clear and concise description of what the problem is:

File names containing an ampersand do not play from HTTPS (and presumably HTTP) data sources.  I've not done extensive testing into this area, so other special/reserved characters may also have problems.  Expanding further, I wonder if things like unicode characters might also be problematic.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When attempting to play a file with an ampersand in the filename from an HTTPS source, the video should play.

## Actual Behavior

When attempting to play a file with an ampersand in the filename from an HTTPS source, the video fails to play.

### To Reproduce

1)  Create an HTTP/HTTPS data source that contains videos with an ampersand in the name.
2)  Add data source to library (Not sure if this is necessary, but included to precisely mirror my setup)
3)  Attempt to play video with ampersand in the filename.  (A TV Show, in my case)
3a)  The malformed URL with the un-escaped ampersand is also visible when looking at the refresh button in the Info screen.

### Debuglog

The debuglog can be found here:
At first I thought this was related to escaping the ampersand, so I didn't generate a debug log, but now I'm not as certain as to that being the issue.  I'll generate one and post it below.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspbian Buster
 - Kodi version: 18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by kib** [comment]
I'd like to see the log from the webserver showing the file being served and the (snipped) relevant part from the kodi debug log where it grabs it.

**Comment by DaVukovic** [comment]
No further information. Closed for the time being.
