### ISSUE TITLE
cache setting is ignored when streaming bluray over smb

### ISSUE THREAD

**Issue by oldk1331** [xbmc/xbmc#16845]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have changed cache setting in `advancedsettings.xml`, so if I stream bluray over http, cache setting is working; if I stream mkv over smb, cache setting is working; but if I stream bluray over smb, then cache setting is not working -- it seems we are using default cache setting instead.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Cache setting in `advancedsettings.xml` should be respected when streaming bluray over smb.

## Actual Behavior

Cache setting in `advancedsettings.xml` doesn't work when streaming bluray over smb.

## Possible Fix

I did some debugging, the call chain is

` CDVDInputStreamBluray::Open -> bd_open_files -> CBlurayCallback::file_open -> CFile::Open(std::string) -> CFile::Open(CURL)`

In `CFile::Open(CURL)`, `IsInternetStream` is called, this function returns `false` for smb.  I don't have context to decide if this is expected bahavior.

After adding "smb" to `IsInternetStream`, I have the expected behavior.

### To Reproduce
1. Modify cache setting in `advancedsettings.xml`.
2. Add a Video location that is smb and contains a bluray. 
3. Open the bluray and pause, the observe the network usage to decide if the cache setting is working.

### Debuglog
The debuglog can be found here:
https://gist.github.com/oldk1331/3ad8030b8321b0eb932c32f609b4e564

As you can see in the log, it uses `CSMBFile::Open` instead of `CFileCache::Open`.

### Screenshots 
Here are some links or screenshots to help explain the problem:

None

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I think this issue is easily reproducible.

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: `android-9 | linux`
 - Kodi version: `18.4 | 19-git`

**Comment by arnova** [comment]
This is by design. Only true internet protocols have caching enabled by the default. I think this policy is something that may be reconsidered.

For now, if you want different behavior have a look at https://kodi.wiki/view/HOW-TO:Modify_the_video_cache and specifically <buffermode>

**Comment by arnova** [comment]
This is the reason this is happening: https://github.com/xbmc/xbmc/blob/29f64ce850040abc9972fcf015a02a3804bdf8c6/xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamFile.cpp#L61 As I recall there were problems playing (certain) DVDs or blurays using cache.

**Comment by arnova** [comment]
This is what introduced it: https://github.com/xbmc/xbmc/commit/018fab22495e5de370b1e6b69e37e93657921f89 Not sure if it's still relevant.

**Comment by oldk1331** [comment]
> This is the reason this is happening:
> 
> https://github.com/xbmc/xbmc/blob/29f64ce850040abc9972fcf015a02a3804bdf8c6/xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamFile.cpp#L61
> As I recall there were problems playing (certain) DVDs or blurays using cache.

I add a log in this function, but this function is never called during my test.

**Comment by arnova** [comment]
> > This is the reason this is happening:
> > https://github.com/xbmc/xbmc/blob/29f64ce850040abc9972fcf015a02a3804bdf8c6/xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamFile.cpp#L61
> > 
> > As I recall there were problems playing (certain) DVDs or blurays using cache.
> 
> I add a log in this function, but this function is never called during my test.

Ah yes. The reason is that bluray and dvd use the dll-loader instead of opening them as regular files in VideoPlayer (through CDVDInputStreamFile). And only regular files in DVDPlayer have caching logic. Furthermore back then there must have been a reason to explicitly disable caching for DVD/Bluray in CDVDInputStreamFile itself. Not sure if those reasons still apply.

**Comment by oldk1331** [comment]
So my original analysis was right, and you thought so too:

`Should improve performance for filesystems like smb://`
https://github.com/xbmc/xbmc/commit/22245aebaaeb954c0fc71e35027d72853a22e0da#diff-2d4c1004e9d2f1e13de5886821aa3cdbR295

But quickly reverted `until we've sorted out the best approach`:
https://github.com/xbmc/xbmc/commit/073828985900db2e3b0d02ad92908beaebdeddcf#diff-2d4c1004e9d2f1e13de5886821aa3cdbR295

Do you think now is the right time to support caching for smb?

**Comment by arnova** [comment]
> So my original analysis was right, and you thought so too:
> 
> `Should improve performance for filesystems like smb://`
> [22245ae#diff-2d4c1004e9d2f1e13de5886821aa3cdbR295](https://github.com/xbmc/xbmc/commit/22245aebaaeb954c0fc71e35027d72853a22e0da#diff-2d4c1004e9d2f1e13de5886821aa3cdbR295)
> 
> But quickly reverted `until we've sorted out the best approach`:
> [0738289#diff-2d4c1004e9d2f1e13de5886821aa3cdbR295](https://github.com/xbmc/xbmc/commit/073828985900db2e3b0d02ad92908beaebdeddcf#diff-2d4c1004e9d2f1e13de5886821aa3cdbR295)
> 
> Do you think now is the right time to support caching for smb?

The problem is not so much supporting smb, the problem is whether we should enable caching for bluray and dvd. I'll have to think about this.

**Comment by lharms** [comment]
When I looked at it a few years ago.  I came to the same conclusion.  I could not decide if it should be turned on at the whole file level at the vfs level or left off all together.  If I remember there was some concern about double caching of items.  It looks like it started with this pull request that deliberately disabled it.  https://github.com/xbmc/xbmc/pull/2607 and 1388  The 831 pull request that started the whole thing looks like it let you do it.  So there may be something in the forums saying why?  Judging by the commit message comments on https://github.com/classicspam/xbmc/commit/36a8e363f9d13e3bd6b10a2aad91b7608849c098 I think the idea was if you were on a local network you did not need it?  The downside is if you are using wireless, looks like a normal 'local' connection anyway.

**Comment by arnova** [comment]
> When I looked at it a few years ago. I came to the same conclusion. I could not decide if it should be turned on at the whole file level at the vfs level or left off all together. If I remember there was some concern about double caching of items. It looks like it started with this pull request that deliberately disabled it. #2607 and 1388 The 831 pull request that started the whole thing looks like it let you do it. So there may be something in the forums saying why? Judging by the commit message comments on [classicspam@36a8e36](https://github.com/classicspam/xbmc/commit/36a8e363f9d13e3bd6b10a2aad91b7608849c098) I think the idea was if you were on a local network you did not need it? The downside is if you are using wireless, looks like a normal 'local' connection anyway.

No, double caching is not the issue. There's only a single point where file caching could be done and that's in CFile which is toggled by flags. Back then I initially implemented the "buffering logic" in  CFile but I didn't realise that anything from a network filesystem would be cached (eg. nfo-files, picture, etc.) not just audio/video files, which caused more overhead than desired. But that's many years ago and devices have become more powerful (and especially have more RAM) now. Furthermore most folks use wifi nowadays which IMO justifies enabling caching (at least for audio/video) by default for *any* network filesystem. That only leaves the question what to do with bluray/dvd, since that logic was not done by me and I still can't figure out the exact reasons for it, only guess.

**Comment by arnova** [comment]
@FernetMenta / @notspiff : You guys have any idea why filecaching is always disabled for dvd/bluray (when played from VideoPlayer)?

**Comment by FernetMenta** [comment]
afaik reading from a VOB results in many seeks triggered by nav blocks. reading ahead and caching would only result overhead because most of the cache won't ever be used.

**Comment by lharms** [comment]
Ah that would make sense as the cache is a window style cache and not a block level cache.  The cache would probably need to be at the vfs level instead then for this to be effective.  Or you would have to make the cache in memory very big.  That could be true for any file that is of a vfs type.

**Comment by arnova** [comment]
> afaik reading from a VOB results in many seeks triggered by nav blocks. reading ahead and caching would only result overhead because most of the cache won't ever be used.

@FernetMenta : I don't know much about VOB, but isn't this something our DoubleCache could handle? DoubleCache is already used for avi/mkv/mp4 to prevent issues with files which have poorly muxed audio/video. For VOB this can obviously only work if there's only constantly being seeked between (roughly) 2 positions.

**Comment by oldk1331** [comment]
So VOB has this seeking problem, but bluray doesn't have this problem?  At least when I was streaming bluray over HTTP, the cache seems always working (hit).

**Comment by arnova** [comment]
Tested it here with a few DVDs/VOBs and I don't see any crazy seeking, so imo we can safely enable caching for at least DVD. Don't have any bluray to test with but I expect the same results.

**Comment by oldk1331** [comment]
So we can move ahead by enabling cache for DVD/Bluray then?
