### ISSUE TITLE
no actions for brightness, contrast regulation

### ISSUE THREAD

**Issue by bam80** [xbmc/xbmc#16854]
### Describe the bug

Brightness, contrast regulation can only be accessible from Video settings menu.
There is no actions which could be mapped to keys to change them.

We already have such actions for:

- volume amplification
`volampup`
`volampdown`
`volumeamplification`

https://github.com/xbmc/xbmc/blob/cce81198925f2a2ebc0365b42defcda6e678aac6/xbmc/input/actions/ActionTranslator.cpp#L190

- zoom
`zoomout`
`zoomin`

## Expected Behavior

For all (GUI)regulated parameters, actions for change them should be provided.

## Actual Behavior

The actions exist only for certain parameters.

## Possible Fix

Provide missing actions:
`brightnessup`
`brightnessdown`
`brightness`

`contrastup`
`contrastdown`
`contrast`

### Debuglog

not needed

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: CoreELEC
 - Kodi version: Kodi (18.4 Git:e95dc442265375aa0cd75284eeaf70ad99b04862). Platform: Linux ARM 32-bit

**Comment by bam80** [comment]
Please, remove the "Ignored rules" label. I've edited the issue.

**Comment by DaVukovic** [comment]
A missing feature is not a bug report. It would be a bug report if it would be possible to map those keys, but they don't have an effect on the playback. 
Therefor this is a feature request and not a bug report. Feature requests should be handled at our forums at this section: https://forum.kodi.tv/forumdisplay.php?fid=9

Please understand that this section here is for bug reports only. Feel free to create your feature request at the forums.

Cheers
DaVukovic

**Comment by bam80** [comment]
https://forum.kodi.tv/showthread.php?tid=348879
