### ISSUE TITLE
"back" action in "tvguide" window always returns to home screen

### ISSUE THREAD

**Issue by bam80** [xbmc/xbmc#16857]
### Describe the bug

"back" action in ["tvguide" window](https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/MyPVRGuide.xml) always returns to home screen, wherever the window was opened from

## Expected Behavior

It should  Go back 1 step in navigation. 

## Actual Behavior

home screen is always opened

### To Reproduce

1. Open any sub-screen from Home screen, e.g - Settings.
2. Open `tvguide` window. By the `e` key or running `kodi-send -a 'ActivateWindow(tvguide)'` in the console
3. Invoke `back` action by `backspace` key or running `kodi-send -a back`
4. Home screen will be opened, instead of returning to Settings screen.

### Debuglog

http://ix.io/20vb

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: CoreELEC
 - Kodi version: Kodi (18.4 Git:e95dc442265375aa0cd75284eeaf70ad99b04862). Platform: Linux ARM 32-bit

**Comment by bam80** [comment]
@Rechi sorry, what is missed? I just deleted Screenshots sections

**Comment by Rechi** [comment]
> * A full [debug log](https://kodi.wiki/view/Log_file) is always mandatory.

**Comment by bam80** [comment]
@Rechi sorry for that. Fixed

**Comment by bam80** [comment]
@Rechi please remove `Ignored rules` label

**Comment by vpeter4** [comment]
If _keyboard.xml_ is used then adding _backspace_ to it could help to get to previous menu.
```
  <TVGuide>
    <keyboard>
      <backspace>PreviousMenu</backspace>
    </keyboard>
  </TVGuide>
```

**Comment by bam80** [comment]
Thanks, I'm aware of the workaround. The report is about a bug

**Comment by ksooo** [comment]
I see from the code that this behavior seems to be intented: https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/windows/GUIWindowPVRBase.cpp#L217

I have no clue what the reason for this special behavior is.

**Comment by ksooo** [comment]
The code is there since "Helix" (PVR window rewrite). @xhaggi do you remember what this special handling of "back" is good for?

**Comment by bam80** [comment]
Thanks @ksooo.
Even if its a "feature", it seems quite useless and confusing to me.
Having no benefits, it requires from user to apply workaround above to make proper behavior.

**Comment by ksooo** [comment]
> Having no benefits

 I presume the special handling was added for a reason. I want to understand that first, otherwise we easily could introduce another regression.

**Comment by bam80** [comment]
Different, but similar problem:
if `Info` window is opened in Fullscreen video, `Back` action doesn't close it, as expected.
Instead, it seems handled in underneath Fullscreen window, and exits fullscreen mode.

Maybe this is consequence of the windowed system implementation, but for the user it seems inconsistent and wrong.

**Comment by ksooo** [comment]
Different problem, different issue, please.

**Comment by bam80** [comment]
> Different problem, different issue, please.

#16876

**Comment by bam80** [comment]
> I want to understand that first, otherwise we easily could introduce another regression.

@ksooo any luck with the understanding?

**Comment by xhaggi** [comment]
> The code is there since "Helix" (PVR window rewrite). @xhaggi do you remember what this special handling of "back" is good for?

Not really, but the comment `don't call CGUIMediaWindow as it will attempt to go to the parent folder which we don't want.` tells us the issue.

**Comment by bam80** [comment]
https://github.com/xbmc/xbmc/blob/f6311e3c5559ced201fb8ff91846fe4b9b668a9a/xbmc/pvr/windows/GUIWindowPVRBase.cpp#L214
Probably that comment refers to this line
https://github.com/xbmc/xbmc/blob/f6311e3c5559ced201fb8ff91846fe4b9b668a9a/xbmc/pvr/windows/GUIWindowPVRBase.cpp#L223
...and has nothing to do with `WINDOW_FULLSCREEN_VIDEO` check above:
https://github.com/xbmc/xbmc/blob/f6311e3c5559ced201fb8ff91846fe4b9b668a9a/xbmc/pvr/windows/GUIWindowPVRBase.cpp#L215
So why we should go to `WINDOW_HOME` if previous window is not Fullscreen video - is still a mystery..
https://github.com/xbmc/xbmc/blob/f6311e3c5559ced201fb8ff91846fe4b9b668a9a/xbmc/pvr/windows/GUIWindowPVRBase.cpp#L217 
Please correct me if I'm wrong.

**Comment by bam80** [comment]
Since there were no more responses are we all agree now that odd special 'back' handling for WINDOW_HOME could be removed?

**Comment by xhaggi** [comment]
After a second look I think you're right and removing the `WINDOW_FULLSCREEN_VIDEO` condition should be fine. Please submit a PR and test if everything works. After that I'll approve it asap.

```c++
bool CGUIWindowPVRBase::OnBack(int actionID)
{
  // don't call CGUIMediaWindow as it will attempt to go to the parent folder which we don't want.
  if (actionID == ACTION_NAV_BACK)
  {
    return CGUIWindow::OnBack(actionID);
  }
  return CGUIMediaWindow::OnBack(actionID);
}
```

**Comment by bam80** [comment]
@thexai what's the reason of closing, was it fixed eventually or it doesn't reproduce any more?

**Comment by thexai** [comment]
If is still relevant for v20 can be opened again
