### ISSUE TITLE
[Matrix] Kodi Windows 32 bit broken (want -llibeay32  & -lssleay32 where not present)

### ISSUE THREAD

**Issue by AlwinEsch** [xbmc/xbmc#16861]
### From build created Kodi for Windows 32bit not startable

With https://github.com/xbmc/xbmc/commit/1eb552a924fda4d901d20cde6b0e754c87b38f50#diff-6cb94d9a930067de547d33b42201203f on https://github.com/xbmc/xbmc/pull/16116 was the `openssl` updated from **1.0.2o** to **1.1.1b**, on the old was `-llibeay32`  and `-lssleay32` present, on the new no more.

On this patch for ffmpeg are still the two no more present libs added; https://github.com/xbmc/xbmc/blob/master/tools/buildsteps/windows/patches/0001-ffmpeg-detect-openssl.patch#L20

As a result, a Kodi start, by means of two Windows dialogues, indicated that they are missing and Kodi aborts the start.

## Expected Behavior
Normal Kodi start

## Actual Behavior
Kodi start canceled by OS

## Possible Fix
Add the two libs to https://mirrors.kodi.tv/build-deps/win32/openssl-1.1.1b-win10-Win32-v141.7z or remove from ffmpeg depends?

### To Reproduce

1. Build current Kodi Matrix for windows 32bit
2. Start kodi.exe
3. Two windows dialogs are then present

### Debuglog
Becomes not created

### Screenshots 
<img width="366" alt="Anmerkung 2019-11-02 142629" src="https://user-images.githubusercontent.com/6879739/68079044-f23c8700-fde2-11e9-9472-6343b361718b.png">
One of the messages

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows (32bit)
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro, Version 1903 (64bit)
 - Kodi version: 19 Matrix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by AlwinEsch** [comment]
One step further (possibly), the curl-7.59.0 also found the old ssl used.
But the 64bit (and only there) is already curl-7.61.1 therefore I can imagine that it only works.
Unfortunately, only https://mirrors.kodi.tv/build-deps/win32/curl-7.61.1-x64-v141.7z is available and not for Win32

**Comment by AlwinEsch** [comment]
Probably will be fixed by https://github.com/xbmc/xbmc/pull/16850

**Comment by jimfcarroll** [comment]
I thought we were dropping 32 bit windows.

**Comment by thexai** [comment]
Tested current master/Matrix 32 bit and is working fine, so it's closed for now.
