### ISSUE TITLE
Marking item as watched while filter is "Unwatched" resets position to first item

### ISSUE THREAD

**Issue by xyz-coder** [xbmc/xbmc#16873]
### Describe the bug
Here is a clear and concise description of what the problem is:

If you are viewing a playlist that has been filtered to only show "Unwatched" and you mark an item as watched (e.g. by clicking W on the keyboard) the position is reset to the start of the playlist, not to the preceding item.

For e.g. I display my "Japanese Movies" playlist, it has the items:
[..]
Akira
Bakudan
Jinja
Kamera Taimu
Kyoto Koukou
Michiko
Shinjuku no Baka
Tokyo Dame

I select "Shinjuku no Baka" and click W. "Shinjuku no Baka" disappears and position is reset to [..]. It should select the previous item, "Michiko". At present it makes it very frustrating to review your unwatched items and update their status.

Note: [..] refers to the "Folder Up" icon, which takes you to the parent

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When you mark an item as watched it should select the preceding item

## Actual Behavior

The first item in the playlist is selected ("Folder Up")

## Possible Fix

Remember position when refreshing content and select item at preceding position

### To Reproduce

1. Go to movies
2. Open a playlist where filter is "Unwatched"
3. Browse to a movie
4. Click W
-> Movie disappears and selected item is now the first one in the playlist ("Folder Up")

### Debuglog

https://paste.kodi.tv/reqowativo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 latest update
 - Kodi version: 18.4, Compiled 2019-09-01

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
>Unnecessary? Should be easily reproducible.

It's not a matter if it's easy to reproduce or not. What if we can't reproduce it (haven't tried it yet, but I will) and you are the only one who is able to "reproduce" it. Then we will have to ask for your logfile. So, why don't provide it in the first place like our template politely asks for it?

**Comment by xyz-coder** [comment]
Well, it's a massive file to read through to ensure no personal information is leaked, but I have uploaded it now.

**Comment by I-Cat** [comment]
Make a back up of your kodi. With =https://kodi.tv/addon/program-add-ons-scripts/backup .
Looks like a trakt.py issue. Check on trakt web site that you have, Checked the permissions /checkin and /scrobble boxes.

**Comment by xyz-coder** [comment]
I don't believe Trakt is installed on this system. It does not appear under Kodi add-ons and searching the system for trakt* reveals nothing.

**Comment by thexai** [comment]
Removed Platforms tags as this is common to all platforms. 

Also is not only in "playlist" but any list of movies or sources: when one item is removed resets focus to top of list (not to item -1 or item +1).
