### ISSUE TITLE
Kodi 18.4 adjusting contrast/brightness turns on subtitles in mkv files

### ISSUE THREAD

**Issue by ac16161** [xbmc/xbmc#16871]
### Describe the bug
Here is a clear and concise description of what the problem is:
 

All my mkv rips include a subtitle track with the default flag unset, unless the subtitles are for a forced track. That way I get my forced subtitles seamlessly, and a full subtitle track is available for me to switch on if I want to.

During playback with subtitles initially disabled, adjusting contrast/brightness is switching on the subtitle track. This is a x-platform issue (OSMC and Windows). Obviously this should not happen. Can this be investigated, thanks.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by samnazarko** [comment]
Does the issue occur with hardware acceleration disabled?

**Comment by ac16161** [comment]
On my Vero 4K I just went into player settings and disabled the amcodec acceleration option - is that what you had in mind? It had no effect, first file I played triggered the subtitles as soon as I adjusted contrast.

**Comment by samnazarko** [comment]
Yes -- that's what I had in mind. Thanks for ruling that out.

**Comment by DaVukovic** [comment]
No log, no further information. Closed for the time being
