### ISSUE TITLE
Windows depends build broken due to old wget certs

### ISSUE THREAD

**Issue by lrusak** [xbmc/xbmc#16872]
The `wget.exe` binary uses it's own cert store which is now outdated and causes the build to fail.

```
Connecting to ftp.halifax.rwth-aachen.de (ftp.halifax.rwth-aachen.de)|2a00:8a60:e012:a00::21|:443... connected.
ERROR: cannot verify ftp.halifax.rwth-aachen.de's certificate, issued by 'CN=DFN-Verein Global Issuing CA,OU=DFN-PKI,O=Verein zur Foerderung eines Deutschen Forschungsnetzes e. V.,C=DE':
  Self-signed certificate encountered.
To connect to ftp.halifax.rwth-aachen.de insecurely, use `--no-check-certificate'.
```

The `wget.exe` either needs to be updated or (in my opinion) changed to use curl (which has regular updates to it's windows builds).

**Comment by afedchin** [comment]
use `--no-check-certificate` as suggested in error description. the **ftp.halifax.rwth-aachen.de** uses self-signed certificate which cannot be verified and this isn't related to certificate storage.
from manual:

> As of Wget 1.10, the default is to verify the server’s certificate against the recognized certificate authorities, breaking the SSL handshake and aborting the download if the verification fails. Although this provides more secure downloads, it does break interoperability with some sites that worked with previous Wget versions, particularly those using self-signed, expired, or otherwise invalid certificates. This option forces an “insecure” mode of operation that turns the certificate verification errors into warnings and allows you to proceed.

> ... For self-signed/internal certificates, you should download the certificate and verify against that instead of forcing this insecure mode. ...

**Comment by lrusak** [comment]
I disagree. The certificate is valid on other platforms
```
* Server certificate:
*  subject: C=DE; ST=Nordrhein-Westfalen; L=Aachen; O=RWTH Aachen; OU=Studentenwohnheim Halifax; CN=ftp.halifax.rwth-aachen.de
*  start date: Jul  9 09:55:23 2019 GMT
*  expire date: Oct 10 09:55:23 2021 GMT
*  subjectAltName: host "ftp.halifax.rwth-aachen.de" matched cert's "ftp.halifax.rwth-aachen.de"
*  issuer: C=DE; O=Verein zur Foerderung eines Deutschen Forschungsnetzes e. V.; OU=DFN-PKI; CN=DFN-Verein Global Issuing CA
*  SSL certificate verify ok.
```

ssllabs also says it is valid
https://www.ssllabs.com/ssltest/analyze.html?d=ftp.halifax.rwth%2daachen.de&s=137.226.34.46

it may be due to the cert chain but the issue is still valid.

**Comment by lrusak** [comment]
Ok I think I fixed it by following this http://woshub.com/updating-trusted-root-certificates-in-windows-10/

will reopen if I see more cert issues on the jenkins slave
