### ISSUE TITLE
Database "cleanup" is VERY costly when library has network files

### ISSUE THREAD

**Issue by jcea** [xbmc/xbmc#16880]
### Describe the bug
Here is a clear and concise description of what the problem is:

_HEADUP: I guess this issue exists also for local files, but doing an existence test per file locally is cheap. Would be cheaper, nevertheless, to retrieve a local directory listing instead of testing each file separately. I am documenting this for webdav because it is my usecase and because it is an actual problem with a heavy impact._

I have several thousands of files in my library. A database "clean" can take many many hours and my webdav server is swamped with "HEAD" requests. Each file does a HEAD request and several server roundtrips.

As far as I understand the issue, Kodi is trying to determine if a file in the database exists or not doing a file access... per file.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would expect Kodi to reuse scan algorithm, in particular doing directory listing and comparing it with library database.

Instead of a webdav access per file, it would be a webdav access (directory listing) per directory.

## Actual Behavior

Every item in the library is tested for existence with an individual HTTP request.

## Possible Fix

I would do something like this:

1. currentPath = None
2. Iterate over files not by database insertion time, but grouped by directory container. That is, grouped by "idPath".
3. Iterate while more files to check.
4. If file "idPath" != currentPath:
4.1. If the file "idPath" DOESN'T allow directory listing (let's say, a plugin), test the file existence just like Kodi does today. Go to step 3.
4.1. currentPath =  file "idPath"
4.2. currentPathListing = get the directory listing for file "idPath".
5. If file not in currentPathListing.
5.1. Delete the file in the library.
6. Go to step 3.
7. When done, free currentPathListing.

Too bad I am not familiar enough with Kodi internals neither comfortable enough with C++ to try to implement this myself.

### To Reproduce

1. Add a webdav source.
2. Have several files there.
3. Add a scrapper.
4. Scan.
5. Do a database cleanup and check the webdav server logs or a network sniffer.

**_(this issue exists also for local files. You can do the same steps and use "strace" or similar tools to verify system calls when cleaning the database; you will see a file access per file in the library instead of a directory listing per directory. I have directories with thousands of files, so I can see the slowness even with local files instead of network files)._**

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.4.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment]
I already tried to fix this issue many years ago but back then getting a directory listing didn't help that much. But since then we've enabled gzip-compression for Curl-filesystems by default which could help a lot. When I can find the time I'll give this another go.

**Comment by Leatherface75** [comment]
What about making cleanup process in background like scanning?
Then you can do other things while waiting for cleanup to finish.

**Comment by DaveTBlake** [comment]
> What about making cleanup process in background like scanning?

You have to take care with that, while playback or browsing seem harmless activities, you don't want other things to attempt to update the db while the clean process is running. It was designed to be a modal activity, so making it a background task may need some thought.

**Comment by arnova** [comment]
> > What about making cleanup process in background like scanning?
> 
> You have to take care with that, while playback or browsing seem harmless activities, you don't want other things to attempt to update the db while the clean process is running. It was designed to be a modal activity, so making it a background task may need some thought.

Yes, this is not the way to move forward. And I also think there's no need to. I believe there are 2 performance issues at play here: performing exists-checks on Curl-based filesystems (http,webdav, etc.) are costly/slow and performing exists-checks on sources (servers) which are down cause a major slow for each file in the db. I think both can be fixed, but it requires some good thinking about the proper solution.

**Comment by Leatherface75** [comment]
Maybe an option to select which sources to cleanup?
Often you have sources that not is changed so often so they could be skipped.

**Comment by arnova** [comment]
> Maybe an option to select which sources to cleanup?
> Often you have sources that not is changed so often so they could be skipped.

Perhaps yes, but that IMO would have to be in the context menu then.

**Comment by arnova** [comment]
@Leatherface75 : Can you test #16940 ?

**Comment by Leatherface75** [comment]
@arnova I tried this patch now and it's not removing deleted stuff anymore.
But also removed stuff that still is there.

**Comment by arnova** [comment]
> @arnova I tried this patch now and it's not removing deleted stuff anymore.
> But also removed stuff that still is there.
> Going to test some more this is strange.
> Does it matter if i am using an month old git?
> I am using that because a few addons doesn't work with python3 branch yet.

Hmmm, I partially understand why this happening: my logic was flawed. I've updated the PR. Please give it another try.

**Comment by Leatherface75** [comment]
I will after i have fixed my database.
It's totally fucked up now and after removing my Kodi doesn't even start anymore hmm

**Comment by arnova** [comment]
@Leatherface75 : Any update on this?
