### ISSUE TITLE
Deleting and renaming files from FTP-Videosources is not possible

### ISSUE THREAD

**Issue by Praggle** [xbmc/xbmc#16883]
### Describe the bug

Missing 'Delete'-Option in the Context-Menu of Media-Files that are placed on FTP-Sources.

## Expected Behavior

-> Adding FTP-Network location with media files (file rights are set to 777)
-> Adding new video-source from this location
-> Allow file renaming and deleting is enabled
-> **The C-Menu should show a 'Delete' and 'Rename' option as with SMB-Network-Sources**

## Actual Behavior

- The C-Menu is not showing 'Delete' or 'Rename' 

## Possible Fix

Deleting Files via SMB

### To Reproduce

1. Adding FTP-Network location with media files (file rights are set to 777)
2. Adding new video-source from this location
3. Allow file renaming and deleting is enabled
4. Settings -> Media -> Library -> Videos ... -> FTP-Source 
5. Select file
6. Press C
7. Check for "Delete"-Entry

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/useyujapoc

### Screenshots 
Here are some links or screenshots to help explain the problem:

This problem is discussed since a long time here:
https://forum.kodi.tv/showthread.php?tid=222075

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

https://ibb.co/WBYGMLW
https://ibb.co/3mjnYzn
https://ibb.co/42DwHL3

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment]
This is not a bug but by design. Most of the Curl-based filesystems are readonly. So if you want write functionality, select another filesystem.

**Comment by gadelkareem** [comment]
@arnova it seems that also samba has the same problem. Which network protocol is recommended for read/write?

**Comment by arnova** [comment]
Samba IS write-capable and nfs as well. Webdav should also be write-capable but I never got it to work with my lighttpd-server but honestly I didn't spend too much time on looking into it since I don't really need it.
