### ISSUE TITLE
Default selection action "choose" don't work in widgets

### ISSUE THREAD

**Issue by edjalmobf** [xbmc/xbmc#16918]
### Describe the bug

I always use the default selection action in Kodi to show informations, but today I changed it to "choose". This work good inside libraries but this not work when select itens in widgets. If the default selection action is show information they work in widgets too.

## Expected Behavior

When click in a movie/episode in widgets show the options of "choose", because we can't see informations about the episode, just they title, and since we enable this option we want to choose options.

## Actual Behavior

When click in a movie or episode in widgets they don't show the option to choose, they just play.

### To Reproduce

1.  Go to Kodi settings > Media > Video > Default select action > Put in "Choose"
2. Back to main menu > go to recently added movies or recently added episodes > Press enter (it will not show the options to choose, it will just play)

### Debuglog

The debuglog can be found here: https://pastebin.com/2nYqaw7k

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 and LibreELEC 9.0.2
 - Kodi version: Leia 18.4 (Windows) and Kodi 18.2 (Raspberry Pi)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by edjalmobf** [comment]
I think some informations of template is not needed here.

**Comment by DaVukovic** [comment]
I can confirm this issue. But I would also say, that a logfile is mandatory in that case. 

https://termbin.com/sxk8

As it shows that, while being at the widgets, Kodi tries to open the movie from the file-POV by accessing my NFS share directly. 
While being in the library (where "choose" works), Kodi reads from the `videodb://....` path

Anyway. We have a log and @edjalmobf it would be nice if you would provide your own as well. 

Thanks in advance.

**Comment by edjalmobf** [comment]
> 
> 
> I can confirm this issue. But I would also say, that a logfile is mandatory in that case.
> 
> https://termbin.com/sxk8

Thanks! I Updated the problem with a log file.
