### ISSUE TITLE
Player[Process|Debug]Info for audio only media is not available?

### ISSUE THREAD

**Issue by Da-kota** [xbmc/xbmc#16922]
### Describe the bug
Player[Process|Debug]Info for audio only media is not available?

For video files there are Player[Process|Debug]Info overlays.   This is very useful for audio only files too.  Seems like  'very low hanging fruit'  to implement and make many users happy.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Would very much  like to see: codec info, bitrate, sample rate, sample width in a PlayerProcessInfo overlay for audio files/streams

## Actual Behavior

No Player[Process|Debug]Info overlay is showing.

## Possible Fix

Analog to video 'Player[Process|Debug]Info' overlays.

### To Reproduce

1.  Play an audio file or stream
2.  Press 'o' or 'ctrl-shift-o'
3.  No information is shown.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
17.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Da-kota** [comment]
I did provide all information necessary for the specific issue.  Please remove 'Ignored rules'  label.  

Best regards.

**Comment by fritsch** [comment]
It's a feature request which should go to the forum, that's the reason.

**Comment by DaVukovic** [comment]
Correct. Feature requests should be done at the forums

Closed
