### ISSUE TITLE
Inconsistent documentation configuration files

### ISSUE THREAD

**Issue by albert-github** [xbmc/xbmc#16930]
### Describe the bug
There are a number of doxygen configuration files in the project a.o.
- docs\doxygen\Doxyfile.doxy
- addons\kodi-addon-dev-kit\doxygen\Doxyfile

but they are not consistent, e.g.  the `ALIASES` contains in the later `cpp_class` that is missing in the first one.

## Expected Behavior
Consistent doxygen configuration files
- containing the same information
- using the same information by means of  `@include`  (see doxygen documentation chapter Configuration, http://www.doxygen.nl/manual/config.html)

## Actual Behavior
When creating doxygen output from all files when can get confusing warnings when using the wrong `ALIASES` set and has to merge both sets.

## Possible Fix
See Expected behavior

### To Reproduce
 Not relevant

### Debuglog
None

### Screenshots 
None

## Additional context or screenshots (if appropriate)
None

### Your Environment
Used Operating system:
Operating system is not really relevant
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: master / 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by AlwinEsch** [comment]
Has created a fix request about here https://github.com/xbmc/xbmc/pull/20432 and where about version and aliases files are used.
