### ISSUE TITLE
Kodi OSD/overlay flickering when compton (window compositor) is active.

### ISSUE THREAD

**Issue by Stevie-O** [xbmc/xbmc#16934]
### Describe the bug

On my system, when the `compton` compositor is active, Kodi's OSD flickers as follows:

- No issues observed before opening a video.
- No issues observed when playing fullscreen videos without the OSD/overlay active
- When the OSD is brought up (e.g. when pausing), the OSD itself flickers on/off.  The video itself displays normally.

There was a forum post about this bug -- https://forum.kodi.tv/showthread.php?tid=341450&highlight=osd+flicker -- although for me it's GalliumOS and Kodi 18.5 or so -- but it ended with a workaround, not a bugfix: manually killing compton before launching Kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect the OSD and menu to display without flickering when a video is opened.

## Actual Behavior

The OSD flickers when a video is opened.
(This also affects the overlay caused by Ctrl-Shift-D.)

## Possible Fix

The issue is clearly some sort of compatibility issue with compton, because terminating compton before launching Kodi prevents the issue.

### To Reproduce

1. Take a Chromebook suited to running Gallium OS.
     I am using an Acer Chromebook 14 (CB3-431 "EDGAR") reflashed with the MrChromebox coreboot firmware

2. Install Gallium OS on it

3. Install Kodi:

sudo apt-get install python-software-properties pkg-config software-properties-common
sudo add-apt-repository -y ppa:team-xbmc/ppa
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 241FE6973ZB765FAE
sudo apt-get update
sudo apt-get install kodi

(note: if you don't do the repository bit first, you get v17.6, not v18.5; furthermore, you can't do a direct upgrade due to packaging differences, but instead must first completely remove the `kodi` and `kodi-bin` packages.)

3. Start Kodi
4. Add some media
5. Start playing a video
6. Hit space to pause and display the main overlay -OR- hit Ctrl-Shift-D to cause the debug info overlay to show

### Debuglog

The debuglog can be found here:

Running Kodi without compton active (issue does not occur): https://paste.ubuntu.com/p/pB2B9jF4ds/

Running Kodi with compton active (issue occurs): https://paste.ubuntu.com/p/qs9YbK7JYH/

I don't see any obvious differences between the logs, though it's difficult to tell.

### Screenshots 

(N/A)

## Additional context or screenshots (if appropriate)

Here is some additional context or explanation that might help:

Additionally, with v17.6, if I hit ESC to go back to the main menu, the menu would also flicker between the UI and the last-displayed frame of the video.  This does not appear to happen with v18.5. 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 GalliumOS v3.0 (appears to be Ubuntu-based)

 - Kodi version: 18.5 (2:18.5+git20191117.0758-final-0bionic)

I am a fair hand at software, so I'd like to work on getting this fixed.  However, I'm not sure where to start looking.  Since the problem affected the main menu in 17.6 but not in 18.5, I could theoretically bisect between 17.6 and 18.5 and find out what changed between them that addresses the problem, but that seems more like a last-resort thing.

**Comment by DanielSentinelli** [comment]
As a workaround, try starting `compton` with `--unredir-if-possible` option.

It stopped Kodi overlay flickering on all different setups I could test.
