### ISSUE TITLE
DVD iso subtitles placed wrongly

### ISSUE THREAD

**Issue by lin88xu** [xbmc/xbmc#16938]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hi all,

Recently I have been using Kodi to run dvd isos. I realised that since version Kodi "Leia" 18.4 the default subtitles (.vob) has been in the wrong placement. Such problems did not exist for Kodi "Leia" 17.6

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Subtitles should be placed the the bottom of the screen spreaded out, like how original dvd is

## Actual Behavior

Subtitles are now placed on the left side of the screen

### To Reproduce

1.  Make an iso out of a disk
2. Run the iso using Kodi "Leia" 18.4 on Android 7.1.2
3. Make sure subtitles is enabled

### Debuglog

The debuglog can be found here:

https://pastebin.com/FwRjsUW5

### Screenshots 
Here are some links or screenshots to help explain the problem:

![IMG_20191118_094429](https://user-images.githubusercontent.com/29219177/69019591-2ec7cf80-09ec-11ea-893b-55ff058ab0ad.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - .Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Android version [7.1.2]
 - Kodi version:
Kodi "Leia" 18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lin88xu** [comment]
Hi sorry for not reading the rules, I have just added a debug log with the bug replicated. Is there anything I can do to facilitate the degugging process?

**Comment by DaVukovic** [comment]
Please don't place the full log at the issue itself. Just use a paste-service for the next time. 

I edited your issue and put your log on pastebin.com

**Comment by lin88xu** [comment]
> Please don't place the full log at the issue itself. Just use a paste-service for the next time.
> 
> I edited your issue and put your log on pastebin.com

Thanks!

**Comment by CastagnaIT** [comment]
@lin88xu a bit late but
do you have the possibility to do a test with current Kodi 20 Nexus to see if the problem still persist?
apk here:
http://mirrors.kodi.tv/nightlies/android/arm/master/
or 64bit: http://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/

can you provide other DVD titles that have this type of problem?
