### ISSUE TITLE
Removing or prevent setting a focus

### ISSUE THREAD

**Issue by groesser** [xbmc/xbmc#16948]
Hi,
how is it possible to remove the focus in a window?
For example i configured in "user interface startup" to startup with the weather window.
In this case KODI starts with weather window without any focus. this is great. Now on any action (e.g. using built-in functions) the focus is set.
I want to remove this focus again or to do any action (e.g. start PVR-Radio via built-in function) without setting a focus.
 
Best regards,
Marcus

**Comment by KarellenX** [comment]
Bug reporting only. No support, No feature requests.
