### ISSUE TITLE
compile Addon remain : warning: die() called many times. Recursion error or racy threaded death!

### ISSUE THREAD

**Issue by nephaste** [xbmc/xbmc#16947]
### git command line updated from ppa but no change....

Here is a clear and concise description of what the problem is:

compiled fine Kodi 18.5 download the .tar.gz from Release
but when i start compiling addon

with 

make -j$(nproc) -C tools/depends/target/binary-addons PREFIX=/opt/Kodi18

make -j$(nproc) -C tools/depends/target/binary-addons PREFIX=/opt/Kodi18
make: Entering directory '/SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons'
cat: /SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/../../../../cmake/addons/.failure: No such file or directory
cd /SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/../../../../cmake/addons && (git clean -xfd || rm -rf CMakeCache.txt CMakeFiles cmake_install.cmake build/*)
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
mkdir -p native
cd native; \
         cmake -DCMAKE_INSTALL_PREFIX=/opt/Kodi18 -DOVERRIDE_PATHS=ON  -DAUTOCONF_FILES=" " \
          \
         -DADDONS_TO_BUILD="all" /SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/../../../../cmake/addons -DBUILD_DIR=/SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/native/build ;\
         for addon in $(make supported_addons | awk '/^ALL_ADDONS_BUILDING: .*$/ { first = $1; $1 = ""; print $0 }'); do \
           make $addon && echo $addon >> /SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/../../../../cmake/addons/.success || echo $addon >> /SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/../../../../cmake/addons/.failure ;\
         done
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Addon source tarball caching is enabled
-- Building following addons: all
--
-- ---- Preparing general dependencies ----
-- Processing /SRC/xbmc-18.5-Leia/cmake/addons/depends/common/kodi-platform/kodi-platform.txt
-- kodi-platform url: https://github.com/xbmc/kodi-platform
-- kodi-platform depends: tinyxml;p8-platform
-- Processing /SRC/xbmc-18.5-Leia/cmake/addons/depends/common/p8-platform/p8-platform.txt
-- p8-platform url: https://github.com/xbmc/platform.git
-- Processing /SRC/xbmc-18.5-Leia/cmake/addons/depends/common/tinyxml/tinyxml.txt
-- tinyxml url: http://mirrors.kodi.tv/build-deps/sources/tinyxml-2.6.2_2.tar.gz
-- No platform specific file /SRC/xbmc-18.5-Leia/cmake/addons/depends/linux/CMakeLists.txt found
-- Bootstrapping all default repositories as no addons were found...
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Bootstrapping all repositories
-- Bootstrapping following addons: all
-- Bootstrapping addons from binary-addons (https://github.com/xbmc/repo-binary-addons.git Leia)...
-- Configuring done
-- Generating done
-- Build files have been written to: /SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/native/build/bootstrap
make[1]: Entering directory '/SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/native/build/bootstrap'
make[1]: Warning: File 'Makefile' has modification time 0.34 s in the future
make[2]: Entering directory '/SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/native/build/bootstrap'
make[2]: Warning: File 'CMakeFiles/Makefile2' has modification time 0.31 s in the future
make[3]: Entering directory '/SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/native/build/bootstrap'
make[3]: Warning: File 'CMakeFiles/binary-addons.dir/progress.make' has modification time 0.3 s in the future
Scanning dependencies of target binary-addons
make[3]: warning:  Clock skew detected.  Your build may be incomplete.
make[3]: Leaving directory '/SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/native/build/bootstrap'
make[3]: Entering directory '/SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/native/build/bootstrap'
make[3]: Warning: File 'CMakeFiles/binary-addons.dir/progress.make' has modification time 0.27 s in the future
[ 12%] Creating directories for 'binary-addons'
[ 25%] Performing download step (git clone) for 'binary-addons'
Cloning into 'binary-addons'...
fatal: premature end of pack file, 52 bytes missing
warning: die() called many times. Recursion error or racy threaded death!
fatal: premature end of pack file, 103 bytes missing
fatal: index-pack failed
Cloning into 'binary-addons'...
warning: die() called many times. Recursion error or racy threaded death!
fatal: premature end of pack file, 52 bytes missing
fatal: premature end of pack file, 103 bytes missing
fatal: index-pack failed
Cloning into 'binary-addons'...
fatal: premature end of pack file, 52 bytes missing
warning: die() called many times. Recursion error or racy threaded death!
fatal: index-pack failed
-- Had to git clone more than once:
          3 times.
CMake Error at /SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/native/build/bootstrap/binary-addons/tmp/binary-addons-gitclone.cmake:66 (message):
  Failed to clone repository:
  'https://github.com/xbmc/repo-binary-addons.git'

CMakeFiles/binary-addons.dir/build.make:89: recipe for target 'binary-addons/src/binary-addons-stamp/binary-addons-download' failed
make[3]: *** [binary-addons/src/binary-addons-stamp/binary-addons-download] Error 1
make[3]: Leaving directory '/SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/native/build/bootstrap'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/binary-addons.dir/all' failed
make[2]: *** [CMakeFiles/binary-addons.dir/all] Error 2
make[2]: Leaving directory '/SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/native/build/bootstrap'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/native/build/bootstrap'
CMake Error at CMakeLists.txt:226 (message):
  No addons available to be built

-- Configuring incomplete, errors occurred!
See also "/SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/native/CMakeFiles/CMakeOutput.log".
make[1]: *** No rule to make target 'supported_addons'.  Stop.
make[1]: *** No rule to make target 'need-sudo'.  Stop.
touch .installed-native
make: Leaving directory '/SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons'

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*`

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

compiled fine and can retrieve from github

## Actual Behavior

ADdon compilation crash on start 

Cloning into 'binary-addons'...
fatal: premature end of pack file, 52 bytes missing
warning: die() called many times. Recursion error or racy threaded death!
fatal: index-pack failed
-- Had to git clone more than once:
          3 times.
CMake Error at /SRC/xbmc-18.5-Leia/tools/depends/target/binary-addons/native/build/bootstrap/binary-addons/tmp/binary-addons-gitclone.cmake:66 (message):
  Failed to clone repository:
  'https://github.com/xbmc/repo-binary-addons.git'

### Your Environment

 - [ ] Android
 - [ ] iOS
 - [ X ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04.03
 - Kodi version: 18.5

**Comment by nephaste** [comment]
moreover

git clone https://github.com/xbmc/repo-binary-addons.git
Cloning into 'repo-binary-addons'...
remote: Enumerating objects: 1583, done.
remote: Total 1583 (delta 0), reused 0 (delta 0), pack-reused 1583
Receiving objects: 100% (1583/1583), 215.21 KiB | 847.00 KiB/s, done.
fatal: premature end of pack file, 52 bytes missing
warning: die() called many times. Recursion error or racy threaded death!
fatal: index-pack failed
root@Bionic_Kodi:/SRC#

i have no clue how to fix it... first time i see that happening

**Comment by DaVukovic** [comment]
Just for my own interests

Why are you downloading a tar.gz and why are you trying to compile anything if everything is available at the Kodi stable PPA for Ubuntu?

Also...have you read the compile instructions at our docs?

**Comment by nephaste** [comment]
because i need compile it for HDStation on Qnap  ;)

i am the maintainer for the qpkg... and need be compiled in a $PREFIX

**Comment by vpeter4** [comment]
@nephaste: On which type of filesystem are you cloning repo when you get error **fatal: premature end of pack file,**?

**Comment by nephaste** [comment]
my system is a LXC Ubuntu 1804 container (built on Qnap Container Station)

all previous version was working fine , including from 18.0 to 18.4 ... and not problem for cloning other git repo ... I am really stuck

I published a 18.5 version with the old 18.4 addon (my prefix compilation point to the previous 18.4 version) ... cross fingers it will not be a problem for users...

but wonder if i can update the addons part as well... for the 18.5

**Comment by nephaste** [comment]
found the issue... is not LXC environment, but the NFS mount point where i build Source
building out the mount point .. it works ...

sorry for the trouble
