### ISSUE TITLE
Windows ARM64 build

### ISSUE THREAD

**Issue by crispyduck00** [xbmc/xbmc#16952]
Are there any plans to make native Windows ARM64 builds?

**Comment by fuzzard** [comment]
Github is for bug reporting only sorry. Feature requests will need to be made on the forums.

Having said that, the likelihood is extremely low right now. There are minimal windows devs for the current platforms, let alone additional ones.

see https://kodi.tv/article/windows-developers-kodi-needs-you

**Comment by crispyduck00** [comment]
Thanks! Sorry, was looking for the feature request option here and tought I can tag it. For now I can only donate to the project to support your work!
