### ISSUE TITLE
XSS on Kodi Web interface

### ISSUE THREAD

**Issue by haocheng1** [xbmc/xbmc#16960]
### Describe the bug
Here is a clear and concise description of what the problem is:

Has been detected a reflected XSS vulnerability in the web interface of
Kodi, that allows the execution of arbitrary HTML/script code to be
executed in the context of the victim user's browser.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

send text to Kodi

## Actual Behavior

XSS Vulnerability

## Possible Fix

validating input and sanitizing and escaping output

### To Reproduce

1. Download and Install Kodi v18.4 “Leia” 
2. Go to Settings -> Services -> Control, and turn on Allow remote control via HTTP
3. Open a web browser and type http://<device_ip_address>:<port>
4. Once you are in the web interface, on the bottom right corner you can see a ... symbol. Click it and it will expand, click the “Send text to Kodi” option. 
5. An input bar will pop up, now just run your XSS command

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

https://drive.google.com/file/d/1b3O9rUNKD7k9baSe_35MWTp5kwgmw7hJ/view?usp=sharing

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ X ] OSX
 - [ ] Raspberry-Pi
 - [ X ] Windows
 - [ ] Windows UWP
Tested on both OS

 - Operating system version/name:
 - Kodi version: v18.4 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by rmrector** [comment]
DOM-based and the source doesn't seem attacker controllable, so this looks low-level.

I suggest posting this to [chorus2](https://github.com/xbmc/chorus2/issues), the project for the web interface.

**Comment by malard** [comment]
this is filed in the wrong project and this is entirely user driven, the user has to enable this attack to happen and assuming they only permit control within their home network (which is the likely scenario) then the attacker almost certainly is more interested in other things in the home than this attack surface. Closing
