### ISSUE TITLE
WakeOnLan built in function does not accept IP/FQDN

### ISSUE THREAD

**Issue by B0ycee** [xbmc/xbmc#16966]
The built in application function "WakeOnLan" (https://kodi.wiki/view/List_of_built-in_functions) only accepts a single parameter of "mac" (address).  However, there should be a way to allow an IP address/FQDN to be passed so that nodes on different subnets can be "woken".

## Expected Behavior

xbmc.executebuiltin('WakeOnLan(02:12:34:56:78:90)') (existing)
xbmc.executebuiltin('WakeOnLan(02:12:34:56:78:90, 192.168.100.100)')
xbmc.executebuiltin('WakeOnLan(02:12:34:56:78:90, myremoteserver.home)')

## Actual Behavior

xbmc.executebuiltin('WakeOnLan(02:12:34:56:78:90)')

Wake packet is sent to 255.255.255.255 which is all nodes on local subnet only and device is not woken.

i.e. a device with IP 192.168.1.100/24 could not wake 192.168.100.100/24 although both are feasibly within a users multi-subnet home network.

## Possible Fix
If expected behaviour above is not possible, then perhaps a new function:

xbmc.executebuiltin('WakeOnLanRemote(02:12:34:56:78:90, 192.168.100.100)')
xbmc.executebuiltin('WakeOnLanRemote(02:12:34:56:78:90, myremoteserver.home)')

**Comment by B0ycee** [comment]
I do not think I can provide any further information to this report.

Clearly an oversight with the built in function.  Referenced documentation.

**Comment by DaVukovic** [comment]
This sounds more like a feature request to me rather than a bug report. Feature requests have to be submitted at our forums: https://forum.kodi.tv/forumdisplay.php?fid=9

**Comment by B0ycee** [comment]
The feature is there though.  Kodi supports WakeOnLan, right?  The problem is the implementation assumes an IP broadcast would reach the recipient (or even that the IP address can always be resolved from MAC address) which is incorrect.  Therefore surely it is a bug?

In another sense, the bug/issue is that wakeonlan function doesn't work.  I've tried to dig into why, and the reason is the packet generated is an IP broadcast.  Digging further, the function cannot do anything else as the IP address is not passed into it.  Hope that makes sense.

**Comment by kib** [comment]
Your request does not make much sense.

You seem to talk about WOL as if it is simple directed IP unicast, but it is not.
It is a specially formatted ethernet frame sent over the data layer. The frame is broadcast out and contains basically a magic signal (lots of 1's followed by the MAC address of the receiving machine multiple times). The receiving machine's network card is specially tuned to pick up this magic signal and action on it.

Because it is an ethernet frame it will therefore not traverse networks without ARP forwarding on the network components, or the usage of a tunnel (eg a VPN with a forwarding rule set up.)

**Comment by B0ycee** [comment]
@kib 

Your understanding of WOL is not entirely correct.  I agree and I am fully aware it contains specific data in the payload as you state, based on MAC address in order for the network card to trigger the wake.

However, it is still an IP packet (i.e. at layer 3) and is not restricted to a bespoke or specially constructed frame (at layer 2 - ethernet).  I can demonstrate this easily by waking various devices (with NICs from Intel/Realtek/Broadcom/etc) even over the internet using Linux command wakeonlan.  If this was not a routed IP packet, this would not be possible.

As the Kodi function is only passed a mac address (which is required to create the specific payload as you state) Kodi has no information as to the destination of the packet at layer 3.  I have found it is sent to the IP broadcast address (255.255.255.255).  Packet capture of Kodi wake packet:

192.168.1.100.55188 > 255.255.255.255.9: UDP, length 102

As you can see this is a UDP packet on destination port 9 which is typical.  This works if the node exists in the same broadcast domain (i.e subnet).  However a broadcast does not transverse a router, meaning Kodi cannot wake device in another subnet (for example if you have a wired and a separate WiFi subnet).  Using Linux's wakeonlan this wake works (i.e wakeonlan -i 192.168.100.100 02:12:34:56:78:90).
