### ISSUE TITLE
episodeguide URL from tvshow.nfo overrides the one set by a Python scraper

### ISSUE THREAD

**Issue by romanvm** [xbmc/xbmc#16979]
## Bug report

When a TV show directory contains tvshow.nfo file with XML info and this file has `episodeguide` section as below:
```xml
<episodeguide>
  <url>http://www.thetvdb.com/api/1D62F2F90030C444/series/328634/all/en.zip</url>
</episodeguide>
```
this URL is passed to `getepisodelist` and `getepisodedetails` plugin calls to a Python scraper regardless of list item properties and plugin directory item URLs that were set by a Python scraper on previous scraping stages, e.g. getdetails.

## Expected Behavior

Kodi should respect list item and and plugin directory item properties set by a Python scraper and pass them to the subsequent plugin calls to a Python scraper.

## Actual Behavior

episodeguide URL from a NFO file is passed to `getepisodelist` and `getepisodedetails` scraper plugin actions which makes no sense, especially if this URL points to, for example, TheTVDB episode guide but the Python scraper actually works with another site (TheMovieDB, TVmaze, etc.)

## Possible Fix
?

### To Reproduce

Add tvshow.nfo file with XML content including `episodeguide` section to a TV shof directory as described above. The try to scrape this TV show with a Python scraper, e.g. TVmaze.

### Debuglog
https://paste.kodi.tv/cuburiyalu.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04
 - Kodi version: Leia, Matrix

**Comment by Webbeh** [comment]
This issue, coincidentally, breaks the scraping of "Local metadata" scraper as well.

The file seems to be downloaded just fine, but "GetEpisodeList" fails on it.

Removing the tag from the NFO makes the scraping work properly.

https://github.com/Sonarr/Sonarr/issues/4448

**Comment by romanvm** [comment]
I'm slowly trying to investigate this issue.
@Webbeh  As a TVmaze scraper developer I understand how this issue affects Python scrapers. But could you describe in details how it affects local metadata?

**Comment by Webbeh** [comment]
Basically, the local metadata scraper sees the file, downloads it and tries to parse it, but it seems to indicate that the "getEpisodeInfo" or "getEpisodeList" method doesn't exist in that scraper,  and the scrapers fails from there.

It just shouldn't even try to download that file and should skip it entirely.

Also, the episode guide zip is a TMDB v1 API, should it maybe be ignored entirely?

**Comment by romanvm** [comment]
The goal of my investigation is to use episodeguide url defined by a scraper and not the one from an NFO file. But I'll check this as well.

**Comment by romanvm** [comment]
I finally found the root cause :tada:

**Comment by Webbeh** [comment]
Wow, finally! What is it?

**Comment by romanvm** [comment]
Some bug in Kodi code. I mean the original issue. My quick checks of local metatata did not reveal any issues.

**Comment by KarellenX** [comment]
Thanks @romanvm 

I'm not sure about the UniqueID issue, but hopefully it won't interfere with this recent fix... https://github.com/xbmc/xbmc/pull/19527
