### ISSUE TITLE
Kodi 18.5 update made existing Kodi installation inaccessible

### ISSUE THREAD

**Issue by jfudger** [xbmc/xbmc#16972]
### Describe the bug
Here is a clear and concise description of what the problem is:
Just updated to Kodi 18.5 on a Mecool M8S Pro L running Android 7. After the update, the existing Kodi installation is inaccessible. The icon is not in the app drawer or on the home screen. Went to Google Play. Kodi was still showing there. Clicked on open and nothing happened. Restarted, cleared cache, Still no install showing. Update trashed existing install.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Github Issues is not for user support.  Please head over to the forum and describe your problem there.

Issue Closed.
