### ISSUE TITLE
dual monitor behaviour

### ISSUE THREAD

**Issue by Flexmaen** [xbmc/xbmc#16981]
### Describe the bug
Here is a clear and concise description of what the problem is:

Dual Monitor behaviour could be improved because it is not always possible to move the window freely when selecting the "windowed mode". Also system shortcuts are overruled.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

- When enabling the "windowed" mode, it should be possible to move the window freely. Kodi should stay at the position where you release the window.
- Windows shortcuts should change the monitor where Kodi will be displayed.

## Actual Behavior

- When running Kodi in "windowed" mode, window can be moved. Sometimes it will stay where you release the window (even between two monitors), but most of the time it will jump back to the screen that is set in the "monitor" option.
- Windows shortcuts (like Shift+Windows+Left/Right) have no effect. Kodi will jump back to the monitor that is selected in the options.

## Possible Fix

In general I think once you enable the Windows-Mode, Monitor settings should be obsolete.
Additionally it would be nice to have the default monitor changed by using system shortcuts.

### To Reproduce

1. Go to Settings "Display"
2. Change display mode to "Windowed"
3. Try to move and release the Window freely.
or
1. Press Shift+Windows+Left or Shift+Windows+Right

### Debuglog

The debuglog can be found here:
This is an easy reproduceable usability issue, if still needed I'd create a debuglog.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I tried to move Kodi between two monitors. Turned out you need to leaving the video and go to the settings instead of using systems standard functions.
I do not know if this also happens in Linux or MacOS, so I didn't restrict this to Windows yet.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
I'm not so sure if a logfile will be helpful in that regard. But I guess it won't hurt if you share it please. 

Thanks in advance

**Comment by Flexmaen** [comment]
I tried on another computer and uploaded the log here.

On this computer, problems were less, but still existed. Moving the window in windowed mode was only a problem if moving it on the smaller screen while it still had a bigger size. Than it jumped back to the original screen.
However at some point, the shortcuts failed to work, while they worked in the beginning.

[kodi.log](https://github.com/xbmc/xbmc/files/3911529/kodi.log)

I could also record a screen video from the other computer if you want.

**Comment by Flexmaen** [comment]
There is the debugfile from the other computer (with some personal info removed).
[kodi2.log](https://github.com/xbmc/xbmc/files/3912092/kodi2.log)

This also happened on a fresh install without plugins.

**Comment by Flexmaen** [comment]
On the 2nd computer I also was able to try with Linux. There everything worked fine in the windowed mode. Logfile of the working Linux is here:
[kodi.log](https://github.com/xbmc/xbmc/files/3913351/kodi.log)

**Comment by Flexmaen** [comment]
I can confirm that this issue still exists in the current 18.7.
