### ISSUE TITLE
Banner instead of Poster using an iOS app connected to Kodi 18.5

### ISSUE THREAD

**Issue by th3boz** [xbmc/xbmc#16984]
### Describe the bug
Here is a clear and concise description of what the problem is:

I use Kodi 18.5 within the OSMC image distro for Raspberry Pi 3 (november 2019 update) in combination with 2 app on my iPad to control it (The Remote for Kodi and Constellation for XBMC).
Kodi is configured to use local media files instead of scraping them from internet: each file is in a different folder that has the name of the film and the local media files are in the format filmtitle-poster.jpg , filtitle-banner.jpg, etc.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Using Kodi directly I should see the correct poster of the film scrolling them.
When I connect my iPad apps to Kodi I should see the correct poster of the film scrolling them.

## Actual Behavior

Using Kodi directly I see the correct poster of the film scrolling them.
When I connect my iPad apps to Kodi I don't see the correct poster of the film scrolling them, but I see the banner instead. This happens with both apps (and I also tested with other apps on different iOS devices.. having the same problem).

### To Reproduce

1. Install OSMC distro on a Raspberry Pi 3
2. Configure Kodi to use local media files naming filmname-poster.jpg and filmname-banner.jpg
3. Use an iOS app to connect to kodi
4. Browse the Library from an iOS app

### Debuglog

The debuglog can be found here:

Sorry.. where can I find the debuglog?

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [x] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC 2019.01
 - Kodi version: 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
This sounds like a problem with the iOS app and not with Kodi at all. Will give it a try later and see if I get similar results. 

For the time being you could test this one: https://apps.apple.com/us/app/unofficial-official-xbmc-remote/id520480364?ls=1

That's the official Kodi remote app and the only one we might have control over.

**Comment by th3boz** [comment]
Hi DaVukovic,
thank you for your support.
I just tried with the official Kodi remote app and I have the problem also with it: I think it’s not an app problem, but it’s in the way Kodi expose the media files to remote apps.
Best regards.
Andrea

**Comment by DaVukovic** [comment]
I just tried with the IPhone from my GF and the official remote app using LibreELEC and unfortunately I can't reproduce your issue: 

![IMG_20191202_221710](https://user-images.githubusercontent.com/7235787/69997322-304cd800-1554-11ea-9ded-bc0d07816277.jpg)


I have to admit that I'm using a LibreELEC with a Kodi 19 build here, but that shouldn't make any difference. But I will try to add a banner-file to my movies as well. Normally movies don't have banners, but TV shows do. There might be skins which supports banners for movies, but at Estuary, there's no banner-view for movies.

**Comment by DaVukovic** [comment]
Just tried with Kodi 18.4 and with a movie which also contains a moviename-banner file. But still I can't reproduce your problem. 

Please share at least a screenshot from your tablets/phones. And also a screenshot from your filestructure on the host machine.

**Comment by th3boz** [comment]
Hi DaVkovic,
thank you so much for your time!
I have some news.. well.. let me start posting some screenshots

Folder Structure of the film "12 anni schiavo" (12 Years A Slave)
![folder_structure](https://user-images.githubusercontent.com/40967044/69999666-7b1d1e80-1559-11ea-8cd0-cf68aea6bc16.jpg)

Screenshot #1 of the iPad App (List of movies)
![screenshot_movie](https://user-images.githubusercontent.com/40967044/69999669-7b1d1e80-1559-11ea-9b68-878e4f31abec.jpg)

Screenshot #2 of the iPad App (Detail of the movie)
![screenshot_list](https://user-images.githubusercontent.com/40967044/69999671-7b1d1e80-1559-11ea-8aa4-9672861d5c10.jpg)

The news is that I think that the app does not take the banner file, but the -landscape.jpg or the -thumb.jpg files instead of the -poster.jpg file.
I also see that the films that only has the -poster.jpg file in the movie folder works well also on the iPad App.

I hope it could be useful.

Thanks again!
Andrea

**Comment by rmrector** [comment]
Most likely the remote is asking for the "thumb" image expecting it to fallback to "poster". The remote is doing it wrong.

https://rmrector.github.io/script.artwork.beef/otherdetails/#a-kodi-skin-or-web-interface-is-showing-a-thumbnail-image-instead-of-a-movie-poster

**Comment by th3boz** [comment]
Oh, thank you rmrector!
Well.. could someone also tell me if it’s correct that the Official Kodi App asks for the thumb instead of the poster file? Is it a preference within the App?
Have a nice day!!
Andrea

**Comment by DaVukovic** [comment]
I would suggest to simply remove the thumb from the movie folders. Thumbs are only exported from the Kodi database for TV shows episodes. Kodi does not expect thumbs for movies. 

See: 

Movie artwork: https://kodi.wiki/view/Movie_artwork

Episode artwork: https://kodi.wiki/view/TV-Show_artwork#Local_episode_artwork

**Comment by th3boz** [comment]
Oh yes yes.. I already did it :)
I asked for the behaviour of the official Kodi app only because I think it could be useful (in case of investigation).

For me the problem is resolved (I’ll close it after this post).

Thanks again!!!!!!
Have a nice day.

Andrea

**Comment by rmrector** [comment]
The official remote does it wrong, too, unfortunately. And the official web UI.
