### ISSUE TITLE
Option to use (also) YAML configuration files instead of only XML

### ISSUE THREAD

**Issue by bamartos** [xbmc/xbmc#16983]
## Roadmap or todo item
**Detailed Description**

Since a Yaml is much easier to read/edit using simple text editors I guess would be a very useful option in order to save files and edit/read manually.

### Context

Configuration files are much more readable like that and easier to edit using a text editor. (especially sources)

### Possible Implementation

In the current parser add yaml feature if the config files under /userdata are in .yaml

### Additional context, screenshots or links
Here are some relevant links or screenshots

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by bamartos** [comment]
I added the template options :) I guess now you can remove "Ignore rules" label

**Comment by fuzzard** [comment]
Feature requests should be posted on the forums. https://forum.kodi.tv/forumdisplay.php?fid=9

Github is for bug tracking only.
