### ISSUE TITLE
Remove requirement for an optical drive in order to display Stub file messages

### ISSUE THREAD

**Issue by apostolostopalidis** [xbmc/xbmc#16998]
Hi All, I am not a programmer but I want to request the resolution of a previously discussed issue (by @dml33 and @Woerd88) that was initially worked on but has not been resolved.

Issue references
https://github.com/xbmc/xbmc/pull/11655
https://github.com/xbmc/xbmc/pull/11317

The need: To support users that want to reference and retrieve movies/series via kodi in offline collections be it dvd, bluray, vhs or whatever other format they spend significant ammount of money and time building. The intent is to play this media with a dedicated piece of hardware (bluray, dvd or vhs players) that is not the same that is hosting kodi. This is also from the perspective of a user that is setting up kodi on a nvdia shield as opposed to a pc, so attaching an optical drive is not supported. It has to be noted that the intent is to seamlessly manage  all movies be it files in a hard drive or offline media through the same list.

Expected Behavior
When a stub file is "played" to display the message regardless if there is connceted optical drive or not. Differentiate the message options if there is optical drive to stay as is, and if there is no optical drive to display the message with the option to aknowledge "OK" in order to close the message.

Your Environment
Used Operating system:  Android

Operating system version/name: 

Kodi version: 18.5 Leia

note: Once the issue is made we require you to update it with new information or Kodi versions should that be required. Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.

**Comment by apostolostopalidis** [comment]
Having referenced previously well defined items, I thought a repeat of the detail apart the need for resolution was not required

**Comment by apostolostopalidis** [comment]
Please remove "ignored rules" label

**Comment by DaVukovic** [comment]
This is more a feature request rather than a bug report. So I will close this for now. Please feel free to open a thread at the Kodi forums at the specific subforum.

**Comment by apostolostopalidis** [comment]
Hi, @DaVukovic I am sorry I didn't have the chance to write earlier since I went through attention diverting situations. I disagree with you that this is not a bug but a feature since in Android systems there is no CD/Bluray drive connectivity, so it is not possible to insert any disk. It is a feature request for PC systems but a bug for Android systems. I tried to locate a GitHub repository for Kodi android but the one found is an archived one. I may be in the wrong repository requesting this, so if this is the case can you please advise?

Regards
A
