### ISSUE TITLE
Video calibration settings are lost on Kodi restart

### ISSUE THREAD

**Issue by micobarac** [xbmc/xbmc#16992]
### Describe the bug
Here is a clear and concise description of what the problem is:

Video calibration settings are lost on Kodi restart

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video calibration settings should not be lost on Kodi restart

## Actual Behavior

Video calibration settings are lost on Kodi restart

## Possible Fix

This looks like a bug to me, so it should be fixed.

### To Reproduce

1. Start Kodi Settings
2. Enter System -> Display -> Video calibration
3. Change the subtitles position
4. Restart Kodi

### Debuglog

The debuglog can be found here:

This isn't actually a crash situation, so a debug log is not applicable here.

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screenshots wouldn't help much, as there isn't any visual disarray with application.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

No additional context.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

Android 8.0
Kodi Leia 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by kekePower** [comment]
I see this as well on LibreELEC 9.2 on a rockpro64.

**Comment by DaVukovic** [comment]
Requested log not provided. Closed until a log has been delivered.
