### ISSUE TITLE
KODI 18.5 playback still stuttering ONLY with subtitles

### ISSUE THREAD

**Issue by versus2** [xbmc/xbmc#17001]
This problems has been reported extensively ever since KODI 18  was introduced. Playback is butter smooth without using subtitles. Whenever subtitles appear on screen playback skips. No solution has ever worked to remedy this problem.

**Comment by KarellenX** [comment]
@versus2 

I have closed your report as you failed to provide any information of value and ignored the questions and template that you were required to complete.

If you choose to post a valid issue, complete all questions and template.
