### ISSUE TITLE
ass subs not loaded/shown under certain condition

### ISSUE THREAD

**Issue by Deadsign** [xbmc/xbmc#17004]
### Describe the bug
Subtitles in ASS format (maybe others too) wont get shown on the actual file if it contains complex formatings/positioning stuff in the first line

Here is a clear and concise description of what the problem is:

If the ASS Subtitle file has some special formatting directly in the first line (see screenshot), the subtitles wont be shown regardless if they are auto detected by Kodi, or loaded manual into the file.
If the Lines appear later in the ass file (like on second line and in first something "normal" gets posted) the subs will processed correctly

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Subtitles should be shown

## Actual Behavior

Subtitles wont be shown

## Possible Fix

Getting the subtitle parser to process the lines correctly even if they appear directly at the beginning (

### To Reproduce

1.  Load a ass with such special start
2. Choose it as a sub for a video
3.

### Debuglog
http://ix.io/23GM
http://ix.io/23GP

### Screenshots 
Here are some links or screenshots to help explain the problem:
https://abload.de/image.php?img=bugblk4e.jpg

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Additional Info to the debug logs.
First one is generated with the "broken" subtitle file, Second one got generated with the beginning of it moved under something else

Sampel Subs
https://drive.google.com/file/d/1xTlvqjfMulW236EXLxNyHtgwK8ASwimA/view?usp=sharing
One is the original file which does not work, the other a edited Version which plays fine

### Your Environment
Used Operating system:

 - [ ] Raspberry-Pi 4 2GB
 

 - Operating system version/name:
 - Kodi version: Kodi 18.5/LibreELEC-RPi4.arm-9.2.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Can you share the subtitle file?

**Comment by Deadsign** [comment]
Ah sorry.
Forgot that it might be helpful to have those here too.
Added a link in the original post, hope to have made the files accessible correctly
