### ISSUE TITLE
Scan for new content can't handle extras +

### ISSUE THREAD

**Issue by teotikalki** [xbmc/xbmc#17017]
Ok. I have had problems with Kodi automatic library scanning (in my experience it's total garbage with things like BDMVs) so I don't use it (ever since... I think it was 'Here Comes the Boom' added dozens of little files that scanned as some short). I manually ad each item. This has been working ok... until today.
I noticed that my movie library had dropped from ~450 items to ~350 items. I freaked out! A whole bunch of items now appeared in Videos view but were NO LONGER IN THE LIBRARY. WTF. My movie library is 3 hdds merged with mergerfs under openmediavault, but looking into the sources the missing items weren't even on the same HDD (where the source could have gone missing during a cleanup to explain this).

I selected my movies folder and said 'scan for new content'. I had EXPLICITLY EXCLUDED the folders 'Movies-Depracated', '#B', '#Classic', #'Childrens'. They all got scanned. WTF
Attempting to fix this I went to Videos and selected the directories, changed content to 'None', selected 'remove all items in this path from library'.... and a number of items from these directories STAYED in the library and would NOT remove after repeated attempts until I manually 'Manage-Remove from Library'. (I now consider the library F*C#&D.)

I have the Extras add-on installed. I have a number of 2-disc editions, which I have had to format as:
Moviefolder/Movie.disc1.folder
Moviefolder/Extras/Movie.disc2.folder
Doing this allowed me to 'Scan to library' these items; they showed properly and the extras were viewable from the context menu. During the rescan this FAILED. All of the 'extras' folders were scanned in as an extra copy of the movie (except for one which scanned in a ~dozen copies of some Batman short).

Furthermore, I use the Backup add-on and restoring every backup for the last week changed NOTHING in my library.

The worst part of this is that I'm just preparing to set up a kodi-headless and convert to mysql so that I can start using the new media player device I got as well as my desktop. From what I've read its functionality is largely reliant upon autoscanning.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

With the Extras add-on installed I expect to do a library scan and have movies with an extras folder scan as ONE move item.

With the Backup add-on I expect to restore my library when I restore (library is checked) and is in fact THE REASON I INSTALLED THIS ADD-ON.

Note: I also expect my library not to lose ~100 items, but I'm currently working on the assumption that that was somehow MY fault. I can't figure out how or why, but in theory I took steps to prevent/fix this problem and THEY'RE BROKEN so I'm screwed anyways. :(

## Actual Behavior

Restoring from backup did apparently nothing. Library contents were unchanged. Multiple backups were restored, going back to a time when the library was KNOWN to have more items.

Scanning the library folder that has the items that USED TO BE IN THE LIBRARY CORRECTLY AFTER A SIMPLE 'Scan to Library' incorrectly scans everything with Extras

### To Reproduce

I'm in personal hell here. I'm about to reconstruct my Kodi library from scratch for the 4th time; it's been several years since I've had to endure this. I will update with further real0-life examples from my experience....

But I think that you install Kodi, install the Extras add-on, format your movie correctly as per the add on, then:
 'Scan to Library' -> movie will be scanned and a single library entry will appear
 'Scan for new content' -> extras will be treated as separate items and library will get messy

Then try to fix it by selecting the folder the movie is in in Videos, change the content to none, remove all items in this path from your library, and go see them still being there. Cry at how utterly nonsensical this is.

### Debuglog

The debuglog can be found here:

This bug report comes after hours of restarting, backup/restore attempts, etc. If there is any way to find a log of what ACTUALLY happened instead of what has since failed to fix it, please let me know.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

As stated above, I am now in my personal hell. I devote an inordinate amount of time and energy to my media library and my sense of reward is gone. Right now I really wish that there was an alternative to Kodi because it disgusts me and I don't want to look at it. 

### Your Environment
Used Operating system: Debian 10
Kodi version: 10.4

**Comment by KarellenX** [comment]
Please take your support question to the forum.

Github issues is for bug reports and your report most certainly reads like a support question.

**Comment by teotikalki** [comment]
If anything, what wrote reads like a rant. It didn't actually involve ANY support questions. It involved 'why did/does this happen, because it shouldn't'. THAT is what a BUG REPORT is.

For example, a support question is something like 'how do I separate documentaries in my library'. A bug report is appropriate after being told that you CAN'T because you have to pick either tv or movies, which is rigidly poor library management.

I don't know if you ACTUALLY read what I wrote. I dispute your understanding of it given your reply. I am going to attempt to distill my original post to the essence of the issue, since I am currently far from the negativity that I was letting out in that rant at this moment.


Install Kodi, install the Extras add-on, format your movie correctly as per the add on, then:
'Scan to Library' -> movie will be scanned and a single library entry will appear
'Scan for new content' -> extras will be treated as separate items and library will get messy

This is inconsistent behaviour. I consider this BUGGY. Telling me that I should file it with the extension creator would have implied reading comprehension on your part. Telling me that what I wrote 'reads like a support question' feels, to me, completely inappropriate...

Although, sadly, what I would expect from you. I'm not lying when I say that your dismissive condescension is the WORST thing about Kodi to me. In my many years as a user who has ALWAYS gleaned MOST of my troubleshooting from the support forums your username is literally the ONLY one I remember and it's because you're like a No Bot. I call you the 'Anti-Doc' because for YEARS I have found you shooting people down every time someone ANYWHERE suggests that library organization might extend beyond 'tv show' and 'movie' (or eventually 'music video', but NEVER documentary or anything that anyone who ISN'T you might want...
