### ISSUE TITLE
ADCIRC v54 bug report - fort.61 netcdf and ascii output are not identical

### ISSUE THREAD

**Issue by makbar1999** [xbmc/xbmc#17020]
### Describe the bug
Here is a clear and concise description of what the problem is:

ASCII output option for fort.61 in ADCIRC v54 produces mixed results. Results of some stations are good and comparable with those from netcdf or observed data. For other stations it produces mostly -99999. NETCDF output option for fort.61 in both v53_04 and v54 versions of ADCIRC produce good results. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Both netcdf and ASCII options of fort.61 should produce identical results.
People who use the ASCII option probably would not even know that their results are not correct. All ASCII output files (fort.61, 62, 63, 64, 71, etc) should be compared against those using netcdf option.

## Actual Behavior

Both netcdf and ASCII options are not producing identical results.

## Possible Fix

Probably parallelization needs to be double checked for bugs.

### To Reproduce

1. Just run two identical cases - one with ascii and one with netcdf output option
2. Have some stations for fort.61
3. Compare the results.
We tested Irma hindcast. I can share input files, if needed.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/47638661/70562300-c59e2c80-1b51-11ea-8191-f3d4f2705261.png)
![image](https://user-images.githubusercontent.com/47638661/70562320-d058c180-1b51-11ea-9b8c-81598c4b034a.png)
![image](https://user-images.githubusercontent.com/47638661/70562346-d9499300-1b51-11ea-87f8-e2ae58ed0a59.png)
![image](https://user-images.githubusercontent.com/47638661/70562371-e2d2fb00-1b51-11ea-834a-b2f1a759f370.png)
![image](https://user-images.githubusercontent.com/47638661/70562390-ebc3cc80-1b51-11ea-888b-8b2ccf5f4352.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
We use RENCI

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
What exactly does this have to do with Kodi?

**Comment by makbar1999** [comment]
Oh sorry, I think I got lost. I meant to submit it to ADCIRC group. Let me
see if I can delete it. Thank you
