### ISSUE TITLE
Event Log - Unhelpful messages

### ISSUE THREAD

**Issue by KarellenX** [xbmc/xbmc#17027]
# Bug report
### Describe the bug

Event Log Messages are too generic and unhelpful for faults relating to Scraping. More details are required to allow a user to properly rectify any issues. Especially as we announce this feature as a replacement for the now defunct Missing Movie Scanner

## Expected Behavior

Event Log messages contain specific details of which show or movie failed to scrape. 

## Actual Behavior

A generic message is logged that does not enlighten the user of which items failed. For those with large libraries, this is problematic.

### To Reproduce

1. Scan tv shows to the library. Name them so scraping will fail
2. Check Event Log
3. Generic messages are logged, but 

### Debuglog

Not of any use

### Screenshots 
Example of generic messages
![eventlog](https://user-images.githubusercontent.com/44626605/70673186-ccee4300-1cd5-11ea-8dc9-aa94f7e35ef3.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
@KarellenX While you don't see the messages for the filename at the Eventlog, are those visible at the Kodi log in that 
"No information found for item '%s', it won't be added to the library."
message where `%s` replaces the filename/path?

The problem seems to be at this section: https://github.com/xbmc/xbmc/blob/master/xbmc/video/VideoInfoScanner.cpp#L477-L478

where it seems `URIUtils::GetFileName(pItem->GetPath()).c_str())` doesn't work for some filenames (your image shows that others are working). Can you name those filenames which aren't shown?

**Comment by KarellenX** [comment]
I'll have to run the test again to see what is shown in the log. 

Those last three files where you can see the name were random test files I had in the root folder. So they would not be scanned anyway as they were not in a TV Show folder.

Those first four unhelpful entries are tv show folders, which means that the entire tv show (and episodes) were not scanned, due to the fact that they were (intentionally) named incorrectly. So it seems that "folder names" are not logged, but that is required to correctly display failed tv show scrapes.

**Comment by DaVukovic** [comment]
Ok, run the test again. A logfile seems to be mandatory in that case as the string is interpreted by Kodi core.

**Comment by KarellenX** [comment]
Here is a new test.

Image from test...
![screenshot000](https://user-images.githubusercontent.com/44626605/70987573-480b8b00-2114-11ea-97fd-abed166357be.jpg)


Log from test
https://paste.kodi.tv/yiyaxucoha.kodi

**Comment by DaVukovic** [comment]
I can reproduce. Will try something later
