### ISSUE TITLE
Games: Sync with popular gaming libraries

### ISSUE THREAD

**Issue by trymeouteh** [xbmc/xbmc#17026]
I think a good feature for Kodi Games tab would be to allow Kodi to sync with locally install gaming libraries such as Steam, Playnite and Lutris. This way you can organise your games with one of these libraries software but Kodi can grab the games in these libraries and be able to launch them within Kodi.

**Comment by DaVukovic** [comment]
Might be, but this section here is not for feature requests. It's for bug reports only. Feature requests have to be submitted at the forums at this subsection:

https://forum.kodi.tv/forumdisplay.php?fid=9
