### ISSUE TITLE
PVR Recordings don't show genre

### ISSUE THREAD

**Issue by emveepee** [xbmc/xbmc#17025]
### Describe the bug
PVR Recordings in v18 and v19 stored using tag.strGenreDescription with tag.iGenreType=EPG_GENRE_USE_STRING do not get displayed.  They display as Other/Unknown.

Using the same code and populating the iGenreType and iGenreSubtype work.

## Expected Behavior
Documentation says that strGenreDescription should display. when tag.iGenreType=EPG_GENRE_USE_STRING 

## Possible Fix

In v19 
https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/recordings/PVRRecording.cpp#L370 the test on m_iGenreType  is a on a value that wasn't initialized.  

Same for v18

https://github.com/xbmc/xbmc/blob/Leia/xbmc/pvr/recordings/PVRRecording.cpp#L367

A few solutions are possible

1.  Earlier in the function initialization set

m_iGenreType  = tag.iGenreType;

2 or not knowing the impact of changing the property test on 

if (tag.iGenreType == EPG_GENRE_USE_STRING || tag.iGenreSubType == EPG_GENRE_USE_STRING)

(testing for both seems unnecessary if the documentation is followed)

3. Ensure m_iGenreType doesn't get reset to zero (not tested)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: V18 V19

No information on this is available in the debug logs.

**Comment by DaVukovic** [comment]
probably something for @ksooo

**Comment by emveepee** [comment]
I will submit a PR for this using option 1 m_iGenreType = tag.iGenreType; if there is no objection
