### ISSUE TITLE
Music database should store more info about songs

### ISSUE THREAD

**Issue by avibrazil** [xbmc/xbmc#17038]
## Describe the bug

Music database should store more info about songs

## Expected Behavior

A suggestion to the music scanner and database is to include very important tags as:

- ISRC (global song ID by the music industry)
- Album barcode
- MusicBrainz work/composition ID; this is very important for classical music or to track different versions by other artists of the same work/song
- purchase_date

[Here are some files](http://avi.alkalay.net/clipboard.priv/kodi-issue-17038/) that contain these tags, you can inspect them with ffprobe. They have [same ISRC that can be looked up](https://isrcsearch.ifpi.org/#!/search?isrcCode=BRUUL1800019). Other files are also different recordings of same work, so **MusicBrainz Work ID** is the same while **MusicBrainz Recording ID** is different.

## Actual Behavior

Music database doesn't include such important tags.

## Output of ffprobe (excerpt)

$ ffprobe "08 Teu sorriso.m4a"
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55939d67cc40] stream 0, timescale not set
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '08 Teu sorriso.m4a':
  Metadata:
    major_brand     : M4A
    minor_version   : 512
    compatible_brands: isomiso2
    title           : Teu sorriso
    BARCODE         : **7893248793307**
    MusicBrainz Work Id: [2e6929d6-fd6b-4d55-9dd5-a25a23f0e13d](https://musicbrainz.org/work/2e6929d6-fd6b-4d55-9dd5-a25a23f0e13d)
    MusicBrainz Track Id: dc872a9f-2330-4894-9095-34bc873ac18f
    ISRC            : [BRUUL1800019](https://isrcsearch.ifpi.org/#!/search?isrcCode=BRUUL1800019)
    purchase_date   : **2019-12-15**

## Set these tags by yourself

The only tagger that I know that is capable of settings this on M4A files is AtomicParsley, like this:

```shell
AtomicParsley "08 Teu sorriso.m4a" \
           --rDNSatom BRUUL1800019 name=ISRC domain=com.apple.iTunes \
           --rDNSatom 7893248793307 name=BARCODE domain=com.apple.iTunes \
           --purchaseDate 2019-12-15
```

Maybe MusicBrainz Picard (mutagen) can write these tags too, but I'm not sure.

### Your Environment

```shell
$ uname -a
Linux <<supressed>> 5.3.15-200.fc30.x86_64 #1 SMP Thu Dec 5 15:18:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ rpm -qa | grep kodi | sort
kodi-18.4-1.fc30.x86_64
kodi-common-18.4-1.fc30.x86_64
kodi-wayland-18.4-1.fc30.x86_64
```

**Comment by avibrazil** [comment]
I edited the bug to follow the template. Please remove the **"ignored rules"** tag.

**Comment by DaVukovic** [comment]
> Music database doesn't include such important tags.

This all sounds like a "feature request" and an "improvement" to me. This section is for bug reports only. Feature requests have to be submitted to our forums at the specific subsection. Please feel free to open a thread at our forums. 

Please don't feel offended. I'm not saying that this is useless, but it's generally simply not a bug ;)

**Comment by avibrazil** [comment]
Indeed it’s a feature request.

Would you please point me to the correct forum to post this?

Thank you

**Comment by DaVukovic** [comment]
[hit me hard](https://forum.kodi.tv/forumdisplay.php?fid=9)
