### ISSUE TITLE
Ubuntu PPA: Python2 depends from python-bluez | python-lightblue (and also consider rm python-imaging)

### ISSUE THREAD

**Issue by BryanQuigley** [xbmc/xbmc#17037]
### Describe the bug
Here is a clear and concise description of what the problem is:
Kodi nightly ppa depends on python2 packages - https://launchpad.net/~team-xbmc/+archive/ubuntu/xbmc-nightly/+packages

Tested on Focal with Eoan packages (no focal on PPA yet).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

As Kodi is killing python2 support, it shouldn't depend on it anymore. Ideally, more testing will be done on system that don't even have python2.

## Actual Behavior

It installs python2 files because kodi depends on them.  It may also be better to move bluetooth to a recommends.

## Possible Fix

Current depends:
$ apt-cache show kodi | grep python
Depends: kodi-x11 (<< 2:19.0+git20191215.0311-29cbd865f6-0eoan.1~), mesa-utils, x11-utils, fonts-liberation | ttf-liberation, fonts-dejavu-core | ttf-dejavu-core, python-bluez | python-lightblue, python3-pycryptodome, python3-pil | python-imaging, python3-simplejson, libbluray2 | libbluray1, libshairplay0, libvorbisfile3, libaacs0, libcec4, libegl-mesa0 | libegl1-mesa, libxslt1.1

Ideally switch "python-bluez | python-lightblue" to Recommends make it just "python3-bluez"
I believe it's also time to drop python-imaging as python3-pil is available on 16.04 as well.

I did find some depends like this in cmake/cpack/deb/packages/kodi-eventclients-ps3.txt.in, but that doesn't quite make sense to me for the main kodi package..

Note: .travis.yml also includes python2 bits that might be worth removing: python-dev python-imaging python-sqlite

### To Reproduce

1.  Install https://launchpad.net/~team-xbmc/+archive/ubuntu/xbmc-nightly/+packages on a fresh newer Ubuntu release focal/eoan. 
2.  apt-get install kodi.  Note the python2 packages

### Debuglog

Proposed packages to Install output

$ sudo apt install kodi  --no-install-recommends 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  kodi-x11 libcec4 libcrossguid0 libfstrcmp0 libmicrohttpd12 libp8-platform2 libpcrecpp0v5 libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib libshairplay0 python-bluez python2 python2-minimal python2.7
  python2.7-minimal python3-pycryptodome
Suggested packages:
  kodi-pvr-mythtv kodi-pvr-vdr-vnsi kodi-pvr-tvheadend-hts kodi-pvr-dvbviewer kodi-pvr-iptvsimple kodi-audioencoder-vorbis kodi-audioencoder-flac kodi-audioencoder-lame python2-doc python-tk python2.7-doc binfmt-support
Recommended packages:
  kodi-peripheral-joystick kodi-inputstream-adaptive kodi-inputstream-rtmp
The following NEW packages will be installed:
  kodi kodi-x11 libcec4 libcrossguid0 libfstrcmp0 libmicrohttpd12 libp8-platform2 libpcrecpp0v5 libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib libshairplay0 python-bluez python2 python2-minimal python2.7
  python2.7-minimal python3-pycryptodome
0 upgraded, 18 newly installed, 0 to remove and 3 not upgraded.
Need to get 42.4 MB of archives.
After this operation, 119 MB of additional disk space will be used.
Do you want to continue? [Y/n] n

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu / Focal (20.04)
 - Kodi version: Nightly builds

**Comment by wsnipex** [comment]
this should be fixed in the nightly ppa, please confirm

**Comment by BryanQuigley** [comment]
all fixed and installed and playing media now without any python2.. Thanks!
