### ISSUE TITLE
uninstalling then installing the same addon fails until kodi is restarted (or another add-on installed)

### ISSUE THREAD

**Issue by MilhouseVH** [xbmc/xbmc#17049]
### Describe the bug

If add-on XYZ is uninstalled Kodi will often fail to install the same XYZ add-on again until Kodi is restarted (or a different non-XYZ add-on is installed, then XYZ will install successfully).

## Expected Behavior

It should be possible to uninstall XYZ then install XYZ, without failure, ad infinitum (barring download issues etc.)

## Actual Behavior

After uinstalling an addon (eg. YouTube),  if the user attempts to install the same YouTube add-on Kodi will fail with the following lines in the log:
```
2019-12-17 19:07:48.330 T:20797   ERROR: Rename - Error renaming file /home/neil/.kodi/addons/plugin.video.youtube
2019-12-17 19:07:48.330 T:20797   ERROR: Failed to move old addon files from '/home/neil/.kodi/addons/plugin.video.youtube' to '/home/neil/.kodi/addons/temp/7a014754-ffca-458e-98a4-a3194169ecee'
```

## Possible Fix

Fix the zip handling.

### To Reproduce

This issue is not specific to the YouTube add-on, I'm just using it as an example - this issue has been reproduced with multiple different add-ons, on LibreELEC and Ubuntu (and according to Google, Windows).

1. Install the YouTube addon, and exit Kodi - this gives a baseline state
2. Start Kodi, and navigate to Settings > Add-ons > Kodi Repository > Install from repository > Kodi Add-on repository > Video add-ons > YouTube
3. Press Enter on the YouTube add-on, then click "Uninstall" (answer "Yes" to the next 2 prompts)
4. Press Enter on the YouTube add-on, then click "Install" (click "OK" on the dependency dialog)
5. There's a 50/50 chance the You-tube add-on will fail to install.

If the YouTube add-on does install successfully, answer "No" to the Wizard dialog and repeat steps 3 and 4.

If the add-on does fail to install, there's 2 ways to fix it:
1. Restart Kodi
or
2. Install a different add-on , then installing the YouTube add-on becomes possible

### Debuglog

Ubuntu (latest Kodi master):  http://ix.io/24IK (failed first time), http://ix.io/24IL (succeeded first time, failed second time)

### Screenshots 

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

1. Reproducible with pretty much any add-on
2. Reproduced with LibreELEC and Ubuntu (all with latest Kodi master)

Google suggests this is [not a new issue](https://www.reddit.com/r/Addons4Kodi/comments/88ku6m/support_unable_to_update_dependencies/) and [affects Windows](https://forum.kodi.tv/showthread.php?tid=309531) as well as Linux.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 10, Ubuntu 19.10
 - Kodi version: Latest master (c7e9b0b38c253612d145a905eba8b78fcd5e90b5)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ritiek** [comment]
I am able to reproduce this without even having to exit on the first install.

It seems like when an addon is uninstalled, the corresponding addon's data directory is also removed from `~/.kodi/addons/` but Kodi fails to update this knowledge in its memory cache. And when installing the same addon again, it assumes that the directory still exists and then fails on attempting to rename this non-existent directory. This also explains why restarting Kodi allows for addon to be installed successfully.

I'll see if I can get more info.

**Comment by ritiek** [comment]
So if change this line here:
https://github.com/xbmc/xbmc/blob/3375a26606b3a6913bea18f4ef7b85a72b724915/xbmc/addons/FilesystemInstaller.cpp#L41

to:
```cpp
bool hasOldData = CDirectory::Exists(addonFolder, false);
```

Then the original issue is corrected, as passing `false` as the second argument to
https://github.com/xbmc/xbmc/blob/3375a26606b3a6913bea18f4ef7b85a72b724915/xbmc/filesystem/Directory.cpp#L345
ignores searching in cache and allows addons to install successfully immediately after they have been uninstalled.

----------

I think another (and IMO better) solution would be to remove an addon's data directory from the cache when the corresponding addon is being uninstalled. To do so, I've tried including `filesystem/DirectoryCache.h` (to bring `g_directoryCache` into scope)

and making calls to
```cpp
g_directoryCache.ClearDirectory(m_addon->Path());
```

when an addon is being uninstalled in here:

https://github.com/xbmc/xbmc/blob/3375a26606b3a6913bea18f4ef7b85a72b724915/xbmc/addons/AddonInstaller.cpp#L856-L879

but for some reason it doesn't remove the directory from the cache.

However, clearing all cache by instead calling:
```cpp
g_directoryCache.Clear();
```
does work the fixes the original issue. Although we probably do not want to clear everything in cache when an addon is being uninstalled.

Any ideas how to clear the addon data directory from cache when the corresponding addon is being uninstalled? Or are we fine with the first solution?

**Comment by bigretromike** [comment]
I can confirm this issue too. It was strange that I would have to restart kodi to reinstall plugin.

**Comment by H-KY** [comment]
I believe that addon's data directory is already being cleared from the cache when the corresponding addon is uninstalled. 
https://github.com/xbmc/xbmc/blob/3e02df2a10f02ec8a9c84a1f4383fd28e98d904f/xbmc/addons/FilesystemInstaller.cpp#L70
as `CFile::Rename` removes the corresponding folder from cache
https://github.com/xbmc/xbmc/blob/3e02df2a10f02ec8a9c84a1f4383fd28e98d904f/xbmc/filesystem/File.cpp#L923-L928
 But it's strange that `CDirectory::Exists` still returns true for old addon directory.
The solution that @ritiek proposed of changing
https://github.com/xbmc/xbmc/blob/3375a26606b3a6913bea18f4ef7b85a72b724915/xbmc/addons/FilesystemInstaller.cpp#L41
to 
```
bool hasOldData = CDirectory::Exists(addonFolder, false);
```
might not be optimal.
Other equally strange observation is that if we copy-paste the implementation of
https://github.com/xbmc/xbmc/blob/3375a26606b3a6913bea18f4ef7b85a72b724915/xbmc/filesystem/Directory.cpp#L345
and change 
https://github.com/xbmc/xbmc/blob/3375a26606b3a6913bea18f4ef7b85a72b724915/xbmc/addons/FilesystemInstaller.cpp#L41
line to 
```
  bool hasOldData, bPathInCache;
  if (g_directoryCache.FileExists(addonFolder, bPathInCache))
    hasOldData = true;
  else if (bPathInCache)
    hasOldData = false;
  else
    hasOldData = CDirectory::Exists(addonFolder, false); 
```
the original problem is solved(`hasOldData` returns `false`)
This is better than not looking in cache and has equal performance as original code.
Although I was not able to figure out why this should work. I see that the addon directory is being cleared from cache but still `CDirectory::Exists` returns true and the problem lies in this function.
Should I create a pull request for the same?

**Comment by MilhouseVH** [comment]
Just a little more info for this issue, as I had the time to bisect some old builds...

It's a Kodi-19 only issue. Pre-Kodi 19 (tested Kodi 18.6) does not have this problem.

Given that it is Kodi 19 only, I went back through old [Kodi 19 builds](https://forum.kodi.tv/showthread.php?tid=343069) and [this build](https://forum.kodi.tv/showthread.php?tid=343069&pid=2870019#pid2870019) is the first to have this issue, which makes me suspect #14908 introduced this problem.

**Comment by DaveTBlake** [comment]
Is this issue fixed by https://github.com/xbmc/xbmc/pull/17701 or not?
Can it be closed and marked resolved if it is.
