### ISSUE TITLE
Kodi crashes when trying to play some Matroska file (mkv)

### ISSUE THREAD

**Issue by pols12** [xbmc/xbmc#17057]
### Describe the bug
Kodi achieve to recognize Matroka file (with MKV extension) and well add them to the movie library. However, when I try to play the movie (selecting and pressing Enter, like I do with all other movies), Kodi instantly crashes.

Similar to #16704, but my MKV audio stream is in MP4A.

## Expected Behavior
Kodi should play the movie like any other DIVX or XVID movie.

## Actual Behavior
Kodi instantly self closes as soon as I press the Enter key while a MKV movie is selected. No message is displayed.

### To Reproduce
1. Add a MKV file in your movie repertory and let Kodi scan it and add it to the library. You can view its information which is well get and displayed.
2. Try to play it through Kodi. → The software crashes.

### Debuglog
Debug log: https://paste.kodi.tv/iyapomatiz.kodi 
Crash log: https://paste.kodi.tv/dideqoxiza.kodi 

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian GNU/Linux 10.2 (“Buster”)
 - Kodi version: 17.6 (Debian package version: 2:17.6+dfsg1-4+b1)

**Comment by DaVukovic** [comment]
Your Kodi version is 
 - outdated (Kodi 17.6 is no longer supported anymore)
 - not supported in here. As you are using a wrong ffmpeg version for the Kodi version. Kodi 18.5 is using ffmpeg 4.0.4. You are using ffmpeg 4.1.3

Recommendation: 

 - update your Kodi version to 18.5
 - make sure to downgrade ffmpeg
 - if downgrading of ffmpeg is not working for you, try to build Kodi 19 alpha from source or use one of our nightlies. Be aware that most add-ons might not work currently as we are switching to Python3 and not all add-ons are compatible with that python version yet.

Going to close this now. Please feel free to open a new bug with a supported Kodi version.
