### ISSUE TITLE
Audio/video unsync after pause or seek, unstable playback resume

### ISSUE THREAD

**Issue by bakatrouble** [xbmc/xbmc#17053]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I increase video playback speed at first, it works as expected. Then after I toggle pause on and off, video starts, but audio follows only after a small (usually under 1 sec) delay, which makes watching videos uncomportable nonetheless. Also, if I toggle pause or seek a few times, video playback freezes (debug info shows decreasing down to 0 video buffer percentage, but the picture is still). Sometimes it restores, sometimes it resets progress bar to the beginning of the media.
Debug log contains repeating lines like following:
```
[...]
2019-12-17 22:31:30.019 T:140424817940224 WARNING: ActiveAE - large audio sync error: 7224.811036
2019-12-17 22:31:30.020 T:140424817940224 WARNING: ActiveAE - large audio sync error: 7231.663704
2019-12-17 22:31:30.020 T:140424817940224 WARNING: ActiveAE - large audio sync error: 7230.785120
2019-12-17 22:31:30.083 T:140424817940224 WARNING: ActiveAE - large audio sync error: 7211.098948
[...]
```
The hardware perfectly capable to perform the same operations using `mpv`, and it is reproducible on two of my PCs (same OS/Kodi versions, GPUs are AMD Radeon RX 480 and integrated Vega 8, application and standalone respectively). Toggling hardware decoding state has no effect.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

* Audio and video streams should be synced after pause or seek when tempo is changed
* Playback should always continue from pause or seek position when tempo is changed

## Actual Behavior

* Audio playback continues with delay after seek or unpause when tempo is changed, resulting in A/V unsync
* Video stream freezes after seek or unpause sometimes, and sometimes it resets seekbar to 0 and is counting time while image is still frozen.

## Possible Fix

I've found a way to avoid these bugs by resetting tempo to 1x before attempting to pause or seek

### To Reproduce

1. Follow instructions in [this post](https://forum.kodi.tv/showthread.php?tid=10023&pid=2420219#pid2420219) to enable tempo controls
2. Start video playback
3. Increase tempo using keys which were set (ctrl+right if you precisely followed instructions)
4. Either pause and unpause playback or seek a few times

### Debuglog

The debuglog can be found here:
https://gist.github.com/0c3a7686201448c87971e2c5c7c2749a

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Manjaro (not sure if applicable) 18.1.4 Juhraya
 - Kodi version: 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
please get us a full debuglog from Kodi start. There's info missing which might be important. 

I'll mark this issue with the "ignored rules" flag as long as you have provided the full log. 

I already tried that with Fedora and Ubuntu and I can't replicate that issue. Everything is perfectly fine after you resume playback after pause even if you setup a 1.5 playback speed.

**Comment by bakatrouble** [comment]
https://gist.github.com/693ff0c6587c35da11c8f57b58ff5531
Here's a full log from my another PC, the issue persists.
