### ISSUE TITLE
Forward and Back are not usable when playing at 1.5xspeed

### ISSUE THREAD

**Issue by Dnkhatri** [xbmc/xbmc#17064]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing a video at faster Tempe @ 1.5x speed. The forward and rewind buttons become unusable as soon as you press it most of the time the video gets stuck or if it is still playing the audio is completely out of sync

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/geqikohaxa
### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ *] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nvidia Shield Tv with the latest update
 - Kodi version: 18.5 latest nightly although this has always been the case as long as I can remeber

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Can't reproduce that on Linux (Ubuntu Fedora). Everything works as expected. Rewind is not as smooth as fast forward, but everything is in sync again if you stop rewinding and move on with 1.5 playspeed.

Not saying that it might not be an Android-only bug.

**Comment by Dnkhatri** [comment]
> Can't reproduce that on Linux (Ubuntu Fedora). Everything works as expected. Rewind is not as smooth as fast forward, but everything is in sync again if you stop rewinding and move on with 1.5 playspeed.
> 
> Not saying that it might not be an Android-only bug.

Thanks for the feedback I will try on my linux install to check

**Comment by Dnkhatri** [comment]
You are correct on linux the video and audio is in sync when it starts up again after forward or rewind. On Android though it doesn't sometimes the video freezes completely  and you can still here the audio.

**Comment by HeresJonny** [comment]
There have been some PR's lately that have improved buffering and searching in audio context, so the issue is not as big as it was before. You can still see that it's not quite optimal, however, when you use skipping instead of fast forward or rewind. If you tap once, twice or three times to advance 10, 30 or 60 secs, playback always needs some time to recover. After a double or triple tap there is even a chance that the buffer doesn't recover at all and playback starts from 0. Obviously, the severity differs with the OS as different mechanisms for audio buffering are employed.

This has been pointed out in the respective forum thread but it was indicated that FernetMentha had abandoned the issue.

**Comment by fritsch** [comment]
Wait silently until our single Android developer has time to look into this issue. If you have time to solve the issue, now is time to dig into it.

This issue has zero priority as there are multiple higher rated bugs that want some love.

**Comment by bakatrouble** [comment]
> There have been some PR's lately that have improved buffering and searching in audio context, so the issue is not as big as it was before. You can still see that it's not quite optimal, however, when you use skipping instead of fast forward or rewind. If you tap once, twice or three times to advance 10, 30 or 60 secs, playback always needs some time to recover. After a double or triple tap there is even a chance that the buffer doesn't recover at all and playback starts from 0. Obviously, the severity differs with the OS as different mechanisms for audio buffering are employed.
> 
> This has been pointed out in the respective forum thread but it was indicated that FernetMentha had abandoned the issue.

I have the same issue with seeking on Linux (described in https://github.com/xbmc/xbmc/issues/17053)
