### ISSUE TITLE
 Addons with multiple provides are not treated properly with "RunAddon".

### ISSUE THREAD

**Issue by Opvolger** [xbmc/xbmc#17073]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have written an addon with [multiple provides](https://kodi.wiki/view/Addon.xml#.3Cprovides.3E_element) (audio and video). In different skins you can put plugins in your main window. These are called with "RunAddon ([addon-id])". In this way of starting the addon, the context_type is always video.
If you adjust the skin xml and pass on the content_type audio, you will get the right content, but the skin of video.

I have already looked up the code where the problem is, only I am a c # developer. I succeed in debugging, but I am not able to make adjustments.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

My expectation is if the content_type is given. This is correctly added to the addon and the correct skin (video / music) is opened

```xml
<onclick>RunAddon($INFO[Skin.String(HomeVideosButton1)],content_type=video)</onclick>

<onclick>RunAddon($INFO[Skin.String(HomeMusicButton1)],content_type=audio)</onclick>
```

Yes, I know that (almost) no skin has correctly implemented this. (But that problem is independent of this)

## Actual Behavior

in the addon I can query the content_type argument, but the "ActivateWindow (Videos" is called instead of "ActivateWindow (Music").

## Possible Fix

In the code (branch Leia).

I have found 2 points in the code that are simply not good at dealing with this. (multiple providers), calling RunAddon:

xbmc\view\GUIViewState.cpp@589

```c++
  if (items.IsPlugin())
  {
    CURL url(items.GetPath());
    AddonPtr addon;
    if (CServiceBroker::GetAddonMgr().GetAddon(url.GetHostName(), addon, ADDON_PLUGIN))
    {
      PluginPtr plugin = std::static_pointer_cast<CPluginSource>(addon);
      if (plugin->Provides(CPluginSource::AUDIO))
        m_playlist = PLAYLIST_MUSIC;
      if (plugin->Provides(CPluginSource::VIDEO))
        m_playlist = PLAYLIST_VIDEO;
    }
  }
```

This ensures that with multiple providers (music and video). You always get video "Listing"

xbmc\interfaces\builtins\AddonBuiltins.cpp@112

```c++
      std::string cmd;
      if (plugin->Provides(CPluginSource::VIDEO))
        cmd = StringUtils::Format("ActivateWindow(Videos,plugin://%s%s,return)", addonid.c_str(), urlParameters.c_str());
      else if (plugin->Provides(CPluginSource::AUDIO))
        cmd = StringUtils::Format("ActivateWindow(Music,plugin://%s%s,return)", addonid.c_str(), urlParameters.c_str());
      else if (plugin->Provides(CPluginSource::EXECUTABLE))
        cmd = StringUtils::Format("ActivateWindow(Programs,plugin://%s%s,return)", addonid.c_str(), urlParameters.c_str());
      else if (plugin->Provides(CPluginSource::IMAGE))
        cmd = StringUtils::Format("ActivateWindow(Pictures,plugin://%s%s,return)", addonid.c_str(), urlParameters.c_str());
      else if (plugin->Provides(CPluginSource::GAME))
        cmd = StringUtils::Format("ActivateWindow(Games,plugin://%s%s,return)", addonid.c_str(), urlParameters.c_str());
      else
        // Pass the script name (addonid) and all the parameters
        // (params[1] ... params[x]) separated by a comma to RunPlugin
        cmd = StringUtils::Format("RunPlugin(%s)", StringUtils::Join(params, ",").c_str());
      CBuiltins::GetInstance().Execute(cmd);
    }
```

This ensures that if you call "RunAddon" with multiple providers, the first valid option is returned. Not the provided "context_type"

### To Reproduce

1. Use a skin (like Confluence)
2. Go to Configure skin...
3. Go to "Addon Shortcuts"
4. Add a addon with multiple providers in music and video (like: [plugin.video.hanssettings](https://github.com/Opvolger/plugin.video.hanssettings/releases))
5. Click on the addon in main window.
6. even after adjusting the xml (C:\Users\Opvolger\AppData\Roaming\Kodi\addons\skin.confluence\720p\IncludesHomeMenuItems.xml@437)

```xml
<onclick>RunAddon($INFO[Skin.String(HomeMusicButton1)],content_type=audio)</onclick>
```

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.5 (Real version, Lokal build)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
I'm not too sure if that helps and I can't help in that regard. But could you please be so kind to add a Kodi debuglog to your issue. I guess developers might ask for it. 

Thanks in advance
