### ISSUE TITLE
Wrong placment for the diacritical marks in the Arabic subtitles

### ISSUE THREAD

**Issue by Essam311** [xbmc/xbmc#17076]
### Describe the bug

The diacritical marks in the Arabic subtitles not in its correct placement above the letters, Kodi moves them one letter to the right. I'm using the Arial font that comes with Kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The diacritical marks should be above the letters that are used with them

## Actual Behavior

Kodi moves them one letter to the right 

### To Reproduce

1. Play any video using Kodi with this Arabic subtitle that contains diacritical marks.
2. Play any video with the same Arabic subtitle in another media player like media player classic.
3. Compare the placement of the diacritical marks.

[Rick.and.Morty.S04E02.The.Old.Man.And.The.Seat.720p.AMZN.WEB-DL.DD+5.1.H.264-CtrlHD.zip](https://github.com/xbmc/xbmc/files/4000787/Rick.and.Morty.S04E02.The.Old.Man.And.The.Seat.720p.AMZN.WEB-DL.DD%2B5.1.H.264-CtrlHD.zip)

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

This how it looks
![1](https://user-images.githubusercontent.com/59211054/71449905-0c01a700-2760-11ea-91cc-f8f098868820.png)

This how it should look

![2](https://user-images.githubusercontent.com/59211054/71449909-1f147700-2760-11ea-8e2e-debf26eb0fcc.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Kodi 19 Alpha (the same problem in Kodi 18.5)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
you deleted the message, should i compile it for you?

**Comment by Essam311** [comment]
@CastagnaIT
I was trying to find a better fix, please compile this newer branch.

https://github.com/Essam311/inputstream.adaptive/commits/diacritical-marks

**Comment by CastagnaIT** [comment]
please don't connect that PR to this issue if it doesn't talk about this issue, can cause confusion with other developers

Compiled: [inputstream.adaptive_win_x64.zip](https://github.com/xbmc/xbmc/files/4019839/inputstream.adaptive_win_x64.zip)

**Comment by Essam311** [comment]
Sorry, I edited my post, thank so much, I have a little problem here, If the diacritical mark repeated in the subtitle line, it only removes the first one.

like

‫حقيقة أنّ الجدّات لسن حقيقيات؟

it remove the first one only

حقيقة أن الجدّات لسن حقيقيات؟

**Comment by CastagnaIT** [comment]
yes becouse you need to use replaceAll instead of replace

**Comment by Essam311** [comment]
Could you add this regular expression to your fork and compile it?

`"\p{Mn}", ""`

**Comment by CastagnaIT** [comment]
Yes, i included it in the pr
but `\p{Mn}` doesn't seem a good regex pattern...

**Comment by CastagnaIT** [comment]
you have tried to replace arial font of Kodi with the arial font of contained in windows\font folder?
might make some difference

**Comment by Essam311** [comment]
Yes i tried doing that, I tried many fonts, and older versions of Kodi, the same problem.

**Comment by Essam311** [comment]
Could you compile this new branch?

https://github.com/Essam311/inputstream.adaptive/tree/Essam311-patch-1

**Comment by CastagnaIT** [comment]
Here: [inputstream.adaptive_win_x64.zip](https://github.com/xbmc/xbmc/files/4020023/inputstream.adaptive_win_x64.zip)

**Comment by Essam311** [comment]
Thank you so much, all the Arabic diacritical marks are removed now.

**Comment by Essam311** [comment]
@CastagnaIT Is it possible to add two regular expressions to your fork from inputstream adaptive for the webvtt subtitles, the first one of them add space to the end of the subtitle line if the diacritical marks were at the end of the line like:

إن كنت مستعداً


and the second regular expression is the equivalent of  (this regular expression moves the diacritical marks one letter to the left so Kodi shows them in the correct position)  

 text = re.sub(u'([\u0651\u064e\u064b\u064f\u064c\u064d\u0650\u0652])(.)', r'\2\1', text, flags=re.MULTILINE)

the diacritical marks Encoding

http://unicode.scarfboy.com/?s=%D9%91%D9%8E%D9%8B%D9%8F%D9%8C%D9%8D%D9%90%D9%92 


`'\xd9\x91\xd9\x8e\xd9\x8b\xd9\x8f\xd9\x8c\xd9\x8d\xd9\x90\xd9\x92'`

**Comment by Essam311** [comment]
@AhmedAdelAbouzeid Could you help with this problem?

**Comment by AhmedAdelAbouzeid** [comment]
The actual issue is the lack of a text shaping library in general and will affect any text that contains complex script. You can easily see that this isn't about subtitles if you open the srt file as a text file inside kodi; you will find the diacritics location is wrong. This also affects other languages, see #15968. To solve this a text shaping library such as HarfBuzz should be used.

If you want a quick solution for subtitles, use aegisub to convert the .srt file to .ass and use that instead in kodi, I found that this eliminates most misplaced diacritics. You can improve placement further if you specify a character spacing of 1 inside the style configuration but then there will be a small gap between letters. I converted the srt file you previously attached as a sample, rename it to match your video name and check if it solves the problem for you (make sure that there is no srt file with the same name in the folder containing the video) 
[test.zip](https://github.com/xbmc/xbmc/files/4495482/test.zip)

**Comment by Essam311** [comment]
@AhmedAdelAbouzeid Thank you, I used to convert the Arabic subtitles to ASS format and use them with Kodi before as a fix for a problem that Kodi not remembering the the position of the subtitles after a restart https://forum.kodi.tv/showthread.php?tid=340313&pid=2818094#pid2818094 (which if fixed now in Kodi) and later I tried that as a fix for the problem of the misplaced diacritics, but I'm using Kodi only with the Netflix add-on and the Amazon VOD add-on and to use the Arabic subtitles in ASS format with them I must download the subtitles from Netflix and primevideo.com and convert the subtitles from SRT to ASS format and use them as external subtitles which takes a lot of effort to do and I must use them every time I resume an episode or a movie.

**Comment by Essam311** [comment]
@AhmedAdelAbouzeid Could this PR https://github.com/xbmc/xbmc/pull/885 get modified to fix the problem of the misplaced diacritics?

**Comment by naseef** [comment]
@Essam311 and @AhmedAdelAbouzeid . I had submitted a pull request for incorporating harfbuzz. Could you please check if it works for Arabic?

**Comment by Essam311** [comment]
@naseef Thank you so much, could you compile a windows 64bit version from Kodi so I can test it.

**Comment by naseef** [comment]
@Essam311  I do not have a windows build right now. Do you got an android phone? Then please test with this apk 

https://github.com/naseef/xbmc/blob/upload/kodiapp-arm64-v8a-debug.apk

**Comment by Essam311** [comment]
@naseef I tested it and some of the diacritical marks seems to be in the correct place above the letters.

**Comment by Essam311** [comment]
@naseef I installed the latest nightly of Kodi 20 on the android phone and compared between the latest nightly of Kodi 20 and your android build and it seems that your build fixed a lot in the problem of Arabic diacritical marks on Kodi.

**Comment by naseef** [comment]
@Essam311 thanks for testing. 👍🏻

**Comment by Essam311** [comment]
@naseef Here is the same line of the Arabic subtitle in the first post using your Kodi build for windows, and the diacritical marks are above the letters as it should be. Thank you so much you really did an excellent job.

![222](https://user-images.githubusercontent.com/59211054/119101199-02de3d80-ba19-11eb-86f5-83133bde8623.png)

This is how it looked before, which is not correct.

![155](https://user-images.githubusercontent.com/59211054/119101474-52bd0480-ba19-11eb-84a1-04cea1f05656.png)

**Comment by naseef** [comment]
@Essam311 Thanks for testing. Kindly do not close the issue until the PR is merged.

**Comment by naseef** [comment]
@sammahafza Could you please provide font file and srt file for the screenshot in #19887

**Comment by sammahafza** [comment]
This is the subtitle file, and the font is the Dejavu Sans which comes with Kodi by default called (**Arial**)

[Gladiator 2000.ar.zip](https://github.com/xbmc/xbmc/files/6667210/Gladiator.2000.ar.zip)

**Comment by naseef** [comment]
@sammahafza Ok. I will test when I get some spare time.
@Essam311 Did  you faced this problem with your font? Could you please test whether @sammahafza 's patch improves rendering?

**Comment by CastagnaIT** [comment]
Now with Kodi 20 has been done a subtitle rendering rework that use Libass rendering
by testing your subtitle file, seem to look right:

![immagine](https://user-images.githubusercontent.com/3257156/143550592-96272591-27fa-4a37-ba79-afab6488c91c.png)

If you confirm this can be closed
