### ISSUE TITLE
Can't run Kodi (Microsoft Store Edition) with parameter

### ISSUE THREAD

**Issue by amirrammari** [xbmc/xbmc#17088]
Hello Kodi team,
I installed Kodi from Microsoft Store.
I can run Kodi using command line:
`shell:AppsFolder\XBMCFoundation.Kodi_4n2hpmxwrvr6p!Kodi`
But that does not support parameters (for example below command line not working)
~~`shell:AppsFolder\XBMCFoundation.Kodi_4n2hpmxwrvr6p!Kodi "D:\Inside Out (2015).mkv"`~~
The solution is $PATH folder
You must add Kodi to $PATH folder (like Python or iTunes)
![Windows 10 Path Folder](https://user-images.githubusercontent.com/23485114/71544899-bc0e2480-2999-11ea-8c20-7ce74acbd8f6.png)
The Kodi can then be run with a parameter:
`%LocalAppData%\Microsoft\WindowsApps\Kodi.exe "D:\Inside Out (2015).mkv"`
Thanks for your attention

**Comment by DaVukovic** [comment]
Not a bug report

**Comment by amirrammari** [comment]
I posted this issue on Kodi forum:
https://forum.kodi.tv/showthread.php?tid=350499
