### ISSUE TITLE
Scraper picks wrong tv show (wrong year)

### ISSUE THREAD

**Issue by Esokrates** [xbmc/xbmc#17086]
The following problem happens with Kodi (18.5 and 19 nightly as of today) on Android and Linux X11 (that's the only platforms I tested).

I noticed the problem for the following tv show: "Die Biene Maja (1975)". I have a folder named "Die Biene Maja (1975)" and all the video files in it are named "Die Biene Maja (1975) S01Exy".

Notice the following: There are two tv shows with identical names on themoviedb.org:
https://www.themoviedb.org/search/tv?query=Die%20Biene%20Maja&language=de-DE

Despite correctly naming the files and specifying the correct year, Kodi picks the wrong tv show from 2013, all the metadata are picked from the 2013 show instead of the 1975 one.

**Comment by DaVukovic** [comment]
Beside the fact that you missed to provide a debuglog where we would see this issue, I also guess that this is more a scraper problem rather than a Kodi problem and therefore opened at the wrong location. 

Please feel free to open another report at: https://github.com/xbmc/repo-scrapers/issues

But generally, I would suggest to seek for assistance at the forums. Most likely it's a naming issue. I got no problems while using this structure: 

```
[davu@fedora-lap tv]$ ls -R
.:
'Die Biene Maja (2013)'

'./Die Biene Maja (2013)':
S01

'./Die Biene Maja (2013)/S01':
S01E01.mkv  S01E03.mkv  S01E05.mkv  S01E07.mkv  S01E09.mkv  S01E11.mkv  S01E13.mkv  S01E15.mkv  S01E17.mkv  S01E19.mkv  S01E21.mkv  S01E23.mkv  S01E25.mkv
S01E02.mkv  S01E04.mkv  S01E06.mkv  S01E08.mkv  S01E10.mkv  S01E12.mkv  S01E14.mkv  S01E16.mkv  S01E18.mkv  S01E20.mkv  S01E22.mkv  S01E24.mkv  S01E26.mkv
[davu@fedora-lap tv]$ 
```

So please seek for assistance at our forums. Thanks

**Comment by Esokrates** [comment]
@DaVukovic First of all thanks for your reply. While it is true that I discarded the template because I thought it would lead to repetitions regarding expected and observed situation I believe this is truly a scraper issue, so I'll open a bug at the respective location.

> But generally, I would suggest to seek for assistance at the forums. Most likely it's a naming issue. I got no problems while using this structure:

I think you misunderstood something here: You tested the wrong TV show, I was talking about the **1975** show while you tested for the 2013 show.

Is a debug log still relevant here? I thought it wouldn't help so much because it is clearly 100% reproducible.

**Comment by Esokrates** [comment]
@DaVukovic May I ask you to have a look at the debug look before opening the bug at the other location? If it's appropriate here please reopen.

Debug log can be found here: https://gist.github.com/Esokrates/7adc97586800947b6bf59fdd896eaaab

Notice I named the folder "Die Biene Maja (1975)" and it fetched info from the 2013 show instead the 1975 one, so this is definitely not a naming issue and therefore not appropriate for the forums.

**Comment by DaVukovic** [comment]
Sorry for misunderstanding. I can reproduce your issue. Anyway, I would suggest to reopen that issue at the specific location. This is either a scraper issue or an issue with TMDB as it scrapes fine using TVDB as a scraper. Just tested that and I got the version of 1975 scraped fine.
