### ISSUE TITLE
Kodi can't find files anymore after television reboot

### ISSUE THREAD

**Issue by ssougnez** [xbmc/xbmc#17082]
### Describe the bug
I connected an external hard drive (exFS) to my Sony Bravia Android TV and want to use it as a Media source in Kodi.

It works well and Kodi is able to index all of it. However, when I reboot the television, it seems that Kodi is mounting the hard drive under a different name (as it is using a GUID for the name), meaning that all the files indexed in the library don't work anymore, so I have to reindex everything...

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
The external drive should be always mounted with the same name (relative to the USB port I guess) for the file in the library to works. So I guess it should be avoided to use a GUID as the name of the mount...

## Actual Behavior

Currently, a GUID is using to name the external drive mount, meaning that everytime it gets mounted, the name is different => the library can't locate the file anymore.

## Possible Fix

Use a name relative to the USB port instead of a GUID.

### To Reproduce

1. Plug the hard drive
2. Clean Kodi library
3. Set the content of the hard drive as Movie
4. Wait for the indexing to be done.
5. Turn off completely the television
6. Turn on the television again
7. Try to play a movie...

### Debuglog

The debuglog can be found here: ?

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 8.0.0
 - Kodi version: Leia 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
This is more an Android problem rather than a Kodi problem. I'm not too sure that's something we are responsible for as, and I might be wrong probably, we don't handle how an underlying OS mounts external drives. 

Let's wait for someone else to confirm the one or the other

**Comment by ssougnez** [comment]
That was my initial thought as well but by looking over internet I found a lot of people complaining about this issue related to kodi but no post of user compalining about this issue related to the Sony television.

Of course, it does not prove that it's indeed a Kodi issue. If it's not I'll create an issue on the Sony GitHub if they have one ;-)
