### ISSUE TITLE
Kodi lock up after overnight tv turn off

### ISSUE THREAD

**Issue by rakess70** [xbmc/xbmc#17091]
### Describe the bug

I have installed the latest Kodi on a window 10 laptop.  I have it plugged into a tv via HDMI.  When I turn the tv off at night the window resizes on the Kodi screen and then proceeds to look of the program to an unresponsive mode.  I have to force close the window each morning and restart. 

## Expected Behavior

I would expect the program to stay functional

## Actual Behavior

I get the spinning icon and the program will not respond

### To Reproduce

1. Run Kodi in full screen mode 
2. Turn off TV for a considerable time.  It only happens overnight not just when turning the tv off and on.  I suspect it is when the computer sees that the TV is no longer a monitor source
3. Turn TV back on and see results

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You missed to provide a debuglog

**Comment by DaVukovic** [comment]
No log since 2 weeks. Issue closed
