### ISSUE TITLE
Win x64 master nightlies from 1225 can't open kodi addon repo

### ISSUE THREAD

**Issue by scott967** [xbmc/xbmc#17102]
### Describe the bug
Here is a clear and concise description of what the problem is:

Win x64 master nightlies from 1225 9f0a835d can't reach the kodi addon repo  Kodi UI opens OK dialog with "could not connect to repository"

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi addon repo opens with categories listed in addon browser

## Actual Behavior

Unable to open the addon repo

### To Reproduce

1. Install nightly to new folder and run in portable mode
2.Open Kodi and navigate addons/addon  browser/Install from repository
3.

### Debuglog

The debuglog can be found here:  

https://paste.kodi.tv/royihazitu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Also tested 1228 and 1229 nightlies that fail, and various nightlies prior that work, all without changing windows environment or rebooting.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:  Win 10 x64 home 1903
 - Kodi version:  KodiSetup-20191225-9f0a835d-master-x64 from mirrors.kodi.tv

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Possibly related to the following PR https://github.com/xbmc/xbmc/pull/17081

**Comment by ronie** [comment]
yes, looking at the log it's same issue as i had https://github.com/xbmc/xbmc/pull/17042#issuecomment-569079948

PR https://github.com/xbmc/xbmc/pull/17081 does indeed fix that issue.

**Comment by arnova** [comment]
Should be fixed with the merge of https://github.com/xbmc/xbmc/pull/17081

**Comment by scott967** [comment]
Fix confirmed in 200101 nightly
