### ISSUE TITLE
[DXVA] "Resume From" with VC-1 encoded content crashes Kodi

### ISSUE THREAD

**Issue by djp952** [xbmc/xbmc#17105]
### Describe the bug
Here is a clear and concise description of what the problem is:

On Windows platforms with DXVA acceleration enabled and (perhaps exclusive to) an Intel-based Graphics chipset, attempting to "Resume From" on VC-1 encoded Blu-Ray content will cause an unhandled exception in CDVDVideoCodecFFmpeg::AddData(), crashing Kodi.

Digging deeper, the exception occurs at the following function call in ffmpeg (dxva2.cpp):

```
if (ff_dxva2_is_d3d11(avctx))
  hr = ID3D11VideoContext_SubmitDecoderBuffers(D3D11VA_CONTEXT(ctx)->video_context,
                                               D3D11VA_CONTEXT(ctx)->decoder,
                                               buffer_count, buffer11);
```

The exception is always the same, and always occurs in **igd11dxva64.dll**:
```
Unhandled exception at 0x00007FF975BD6C15 (igd11dxva64.dll) in kodi.exe: 0xC0000005: Access violation reading location 0x0000000000000020. occurred
```

I have tried a number of things to resolve the problem to try and propose a solution, but have essentially come up empty.  Adding a __try/__except block in ffmpeg to ignore the exception came closest to functional, but (and this might be relevant) while playback would resume, there would be no audio stream.

Disabling DXVA in favor of software decoding solves the problem. Unfortunately I am not in a position to try this on DXVA-enabled nVidia or AMD chipsets so I cannot assist with any determination if this is an Intel-specific bug/concern, or if it's systemic to ffmpeg.  I did diff Kodi's ffmpeg against the latest formal ffmpeg and didn't find anything of concern in the VC-1 decoding module(s).

I am also not in a position to provide sample content, which makes this difficult.  The only content I have that will reliably exhibit the problem is protected by Copyright -- The "Harry Potter" series of movies, which are all (legally) sourced from VC-1 encoded Blu-Ray discs.  I did extract a 10-minute clip of "Harry Potter and the Chamber of Secrets" that is reasonably sized and proven to be reliable for replicating the issue, but I don't believe it's legal for me to share it.  I have not been able to find free VC-1 encoded content of sufficient length to link to that would allow Kodi to use it's "Resume From" functionality.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Playback should resume from the designated timestamp without crashing the application.

## Actual Behavior

Kodi will crash with an unhandled exception in igd11dxva64.dll.

## Possible Fix

Tried and failed multiple times

### To Reproduce

1. Obtain a legal copy of "Harry Potter and the Chamber of Secrets" on Blu-Ray
2. Decrypt and store "Harry Potter and the Chamber of Secrets" using SlySoft's AnyDVD-HD application
3. Add "Harry Potter and the Chamber of Secrets" to the Kodi Movies or Videos libraries
4. Play "Harry Potter and the Chamber of Secrets" to a point sufficient to allow "Resume From"
5. Attempt to "Resume From" "Harry Potter and the Chamber of Secrets"

### Debuglog
The debuglog can be found here (Updated for Kodi 19 "Matrix"):

https://paste.kodi.tv/iciliwaxeb.kodi

### Screenshots 
N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I am prepared to share a 10-minute VC-1 encoded sample from "Harry Potter and the Chamber of Secrets", but I would need some assurance that I would not be violating any Copyright laws by doing so.  If I can find any FOSS VC-1 content that will serve the purpose, I will link to it.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.0-ALPHA1 (18.9.701) Git:20200908-41546e6ec5), Windows x64 (Desktop)

**Comment by DaVukovic** [comment]
You have banned add-ons installed. Please remove those first and provide a new and clean debuglog. 

Thanks in advance.

**Comment by djp952** [comment]
Hi, can you please be more specific? I don't have any add-ons at all except the ones built into Kodi and my own PVR.

**Comment by DaVukovic** [comment]
>Hi, can you please be more specific?

sure:

2019-12-31 22:48:38.982 T:3392  NOTICE: ADDON: repository.xbmchub v3.0.0 installed

**Comment by djp952** [comment]
Ok. No idea where that came from (seriously). I'll clean install and do the log again. I'll also check out what that addon is and report in the forums if I can find out how it ended up on my test instance, I certainly didn't install it intentionally.

**Comment by djp952** [comment]
Debuglog regenerated with same steps on clean Kodi 18.5 instance with nothing but the Movies library initialized and link replaced.  My apologies again.

**Comment by djp952** [comment]
This concern still exists on Matrix; now that Leia is assumed to be done with would the correct course of action be to close this and open a new Issue against that even though the basic information will not change, or can this Issue be re-targeted for v19 Matrix?

Thank you!

**Comment by fuzzard** [comment]
Just add a v19 debug log and update the issue as relevant. No need to close and reopen another

**Comment by djp952** [comment]
Thank you very much @fuzzard, the issue and debuglog has been updated for Matrix; would you mind changing the "v18 Leia" tag?

**Comment by djp952** [comment]
This Issue no longer occurs on recent nightly builds of Matrix or master/Nexus. with current Intel video drivers.  The content will now restart without crash.  There is no audio, but I see this on all platforms so I'll check for matching Issues on that particular problem.

My assumption is that it was an Intel driver bug I don't see any code changes on the Kodi side that would have fixed this.  Either way - gone!

**Comment by bcutter** [comment]
Unfortunately KODI (20.2.0.0) crashed because of `igd11dxva64.dll`. Playing on internal display. The module is the graphics driver of Intel from the iGPU used by KODI.

![grafik](https://github.com/xbmc/xbmc/assets/13799156/72f9b082-5c87-40c2-8b03-456210df38c2)

```
Name der fehlerhaften Anwendung: kodi.exe, Version: 20.2.0.0, Zeitstempel: 0x649d320b
Name des fehlerhaften Moduls: igd11dxva64.dll, Version: 31.0.101.4032, Zeitstempel: 0x63a2e184
Ausnahmecode: 0xc0000005
Fehleroffset: 0x000000000017553a
ID des fehlerhaften Prozesses: 0x0x5958
Startzeit der fehlerhaften Anwendung: 0x0x1DA14D679C1D91A
Pfad der fehlerhaften Anwendung: C:\Program Files\Kodi\kodi.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_6fcd49f9b74fd805\igd11dxva64.dll
Berichtskennung: 21533ee8-1b1b-468f-bed3-f3df81a6003c
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

The video is freezing for a few seconds, after max. 3 to 5 minutes KODI crashes completely.
Also tried to disable deinterlacing method, but even set to Inactive (no DXGA) the video continues to behave exactly the same.

I use the latest Intel driver of my hardware manufacturer.
