### ISSUE TITLE
Music: Unexpected behaviour of "Scan item to library"

### ISSUE THREAD

**Issue by HeresJonny** [xbmc/xbmc#17119]
### Describe the bug
The command "Scan item to library" wipes information from the database under certain circumstances

In music file mode, music items can be scanned into the library by selecting "Scan item to library" from the context menu of an item. This triggers a deep (re-)scan of format specific music tags. However, under certain circumstances existing information is neither updated nor supplemented but cleared/wiped. I have confirmed this by running the command on a single album and checking the (MySQL)database afterwards.

In the table mymusicxx/album I have looked at the columns album, strMusicBrainzAlbumID and strReleaseGroupMBID after each update. After each update the information populated from the respective file tags in column 2 and 3 is first missing and then present. This can be repeated ad nauseam, like an on/off switch.

## Expected Behavior

Running the command "Scan item to library" is always expected to add information to the music library, never to remove it.

## Actual Behavior

If "Scan item to library" is run on an album that is already present in the music database, certain fields are vacated. When the command is run again, those fields are populated again. 

## Possible Fix

I think what was intended when "Scan item to library" is run is that some or all fields would be cleared and then repopulated with the values that are now read from the file. However, it seems that same target fields are only cleared but not updated during the same command run; or that the update routine checks for an emtpy field at the wrong time.

### To Reproduce

1. Run "Scan item to library" on an album that has proper MusicBrainz tags.
2. Check the mymusic/album database row for that album.
3. Run "Scan item to library" on the same album again.
4. Check the mymusic/album database row for that album again.

### Debuglog

Not that kind of bug.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18 Leia
19 Matrix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
I cannot replicate your issue, but I am not using a MySQL/MariaDB setup.

What selection are you making for the question "Do full tag scan when music files are unchanged?"

Please provide a debug log which captures this issue.

**Comment by DaveTBlake** [comment]
@HeresJonny I think you probably have "Fetch Additional Info on update" enabled and I suspect that what you describe is just the album mbid tags being picked up by the scraper, having not been found by scannning the metadata tags because your tagging is faulty. See my reply to your forum post about the tagging. 

Hence closing this issue

**Comment by HeresJonny** [comment]
Just as an addendum, not to open the issue again:

I drew the wrong conclusions from my observations. @DaveTBlake who has the best overview of the inner workings rightly corrected them. 

That means for me, the issue has something to do with embedded cuesheets which Dave has long stated he won't look into, which I respect. 10 years ago my focus was on having a file that could be burned to a CD as backup for my original one. Times have changed and now the focus is on portability between differen playback devices. That said, I will convert all my single .flac files with embedded cuesheets to separate tracks. Will take me several weeks since the conversion will need to be made manually with cuetools but in the end I will have better compatibility overall.

**Comment by DaveTBlake** [comment]
>That means for me, the issue has something to do with embedded cuesheets which Dave has long stated he won't look into, which I respect.

Not sure how what you reported here relates to cuesheets. Anyway just to clarify what I have no time for is adding functionality to the cuesheet implementation. Glaring bugs in basic cuesheet processing I would consider, but do not see any compelling reasons to make custom additions to the cuesheet format and related processing.

Glad to hear you are converting to a single file per track approach, that does allow for the richest library experience and flexibility.

**Comment by HeresJonny** [comment]
I suspect it would be a cuesheet issue because that is the only thing where my tag separator ";" doesn't work because Kodi reads it as ",".
