### ISSUE TITLE
Difficulty MANUALLY identifying movies when they are badly named

### ISSUE THREAD

**Issue by GiganteX** [xbmc/xbmc#17116]
Movies I download often have scrambled names. The folder is aptly named, but the movie file itself will have a name like "1ac798f06538474fbbd9e1788cc9f3a8.mkv".

The Kodi identifier fails to handle that, I wish it would check the folder name, but alas, it ends up in the event log with a line "Video library scanner" and "Failed to scan movie 1ac798f06538474fbbd9e1788cc9f3a8.mkv". 

That's fine, I have come to expect that, but then I try to add it to the library myself, manualy, with the "Scan to Library" option. The problem I have is that I add a bunch of movies at a time, and Kodi shows me the filename (which of course does not help in cases like these) and a frame from the movie. I don't know how that frame is selected, I assume Kodi jumps into the movie X minutes and grabs the frame. Sometimes I can figure it out, other times I can't. And then I'm out of luck. And this happens a lot....

My preferred perfect solution; Show me the folder name as well as the filename.
Alternate solution: Show me more frames, or maybe even let me view a part of the movie
Alternate solution 2: Let me click a button to open the folder on disk

Thanks!

**Comment by KarellenX** [comment]
Your post sounds like a feature request and support question. You have ignored the required template and no debug log to verify any bug is provided.

I will close this issue.

Please resubmit your questions to the Kodi forum in the metadada scraper sub-forum. Be sure to provide a debug log which captures you scraping problem.
