### ISSUE TITLE
Mediasources "lockcode" not working from Estuary/Homescreen-Widget

### ISSUE THREAD

**Issue by howie-f** [xbmc/xbmc#17110]
### Describe the bug

*** Hi everybody :) and a happy new year
this is my first issue report on this awesome project and I would appreciate contributing in the future ***

SKIN ESTUARY:
If you code-locked a video-source and access to it  via
"Home-Screen -> Video -> Media-Sources-Widget -> specific source", the source can be accessed without querying the lock-code.
In contrast "Home-Screen -> Video -> Categories-Widget -> Files -> specific source" works as expected. 

## Expected Behavior
Should query lock-code if using Media-Sources-Widget on Home-Screen.

## Actual Behavior
Just let's you in...

## Possible Fix
sorry, don't know if this is skin- or core-related

## To Reproduce
1. Select "Videos"-item on the Home-Screen
2. Switch to Media sources-Widget on the right, select a lock-code-protected source
3. You're in (but shouldn't)

## Debuglog
The debuglog can be found here: https://paste.kodi.tv/aqubapitob.kodi

## Your Environment
Used Operating system:
 - [X] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian Stretch, Raspbian Stretch
 - Kodi version: Krypton, Leia, master ... unfortunately all affected

**Comment by DaVukovic** [comment]
Not sure I get how you lock a source. I just can tell you how I did it: 

- enabled "Master lock" in system settings and selecting a numeric password
- locked Video like this: 

![lock1](https://user-images.githubusercontent.com/7235787/71645155-35788080-2cd4-11ea-8738-6eaf9a258596.png)

And if I then try to access the sources: 

![lock2](https://user-images.githubusercontent.com/7235787/71645161-43c69c80-2cd4-11ea-9da3-caaa6555dfa8.png)
I'm asked for the password as expected. 

If your way differs from the way I did it, then please explain it to me and I happily try to reproduce. 

If it's the same way, then I have to admit that I can't reproduce your issue and we will for sure need a debuglog to see what you have done. So I won't remove the "ignored rules" label for the time being. 

Thanks for understanding.

**Comment by howie-f** [comment]
Hi DaVukovic, thanks for investigating...
it happens in the "**Media-Sources**-Row" on the screen you posted above
(right beneath your green quare).
You are checking **Categories**-section, which works as expected.
hope you understand what i mean?

my debug log: https://paste.kodi.tv/aqubapitob.kodi

thank you

**Comment by DaVukovic** [comment]
ok, I can confirm your issue now. 

I saw that you posted a logfile (as I can see in which way you have edited your message). But that log wasn't a debuglog. Anyway, it would be nice if you could provide one. 

Thanks. 

Here's mine for the time being: https://termbin.com/k9yj

**Comment by howie-f** [comment]
debug log: https://paste.kodi.tv/voqiruqina.kodi

as i said: my first issue report :flushed: - still learning...

**Comment by howie-f** [comment]
@DaVukovic after longtime digging i think i found out where to start.
made commit 0a3406c on branch howie-f/stop-bypassing-lock but this is half-baked as i have no idea how to find out which source is being opened at this point.
but the debug-log tells me i'm on the right way.
would you (or s.o. of the devs) have a look on this and should i open a PR?
thanks in advance

**Comment by howie-f** [comment]
closed by #17129
