### ISSUE TITLE
Python script do not run if the main type is ADDON_SCREENSAVER

### ISSUE THREAD

**Issue by enen92** [xbmc/xbmc#17125]
I'm keeping this issue here just to keep the backlog. @AlwinEsch said he would look into it.

### Describe the bug
Here is a clear and concise description of what the problem is:

I have an addon that is a screensaver (main type), a script (so it runs from the video addons section of kodi) and a service. Since Matrix, I can't execute the script from the Kodi interface. This was introduced either with the Python3 migration or Cpluf removal. 

Addon.xml is defined as shown below:

```
<extension point="xbmc.ui.screensaver" library="entrypointscreensaver.py" />
<extension point="xbmc.python.script" library="entrypointscript.py">
	<provides>video</provides>
</extension>
<extension point="xbmc.service" library="service.py" start="login"/>
```

If `xbmc.python.script` is moved before `xbmc.ui.screensaver`, it works again.

## Expected Behavior

Addon should just run like in 18.5 regardless of the entrypoint position in addon.xml (main type).

## Actual Behavior
Addon fails to start since the script path is not filled. Log shows Kodi is trying to play an empty file when the addon icon is clicked:

```
│2020-01-04 10:15:09.353 T:18446744073709551615   DEBUG: Thread LanguageInvoker 0x700008694000 terminating                                                                                                 │
│2020-01-04 10:15:16.940 T:18446744073709551615   DEBUG: ------ Window Init (Pointer.xml) ------                                                                                                           │
│2020-01-04 10:15:20.728 T:18446744073709551615   DEBUG: ProcessMouse: trying mouse action leftclick                                                                                                       │
│2020-01-04 10:15:20.728 T:18446744073709551615   ERROR: Keymapping error: no such action 'playmedia("")' defined                                                                                          │
│2020-01-04 10:15:20.729 T:18446744073709551615   DEBUG: ExecuteXBMCAction: Tried translating, but failed to understand PlayMedia("")                                                                      │
│2020-01-04 10:15:21.235 T:18446744073709551615   DEBUG: ------ Window Deinit (Pointer.xml) ------                                                                                                         │
│2020-01-04 10:15:21.643 T:18446744073709551615   DEBUG: ------ Window Init (Pointer.xml) ------                                                                                                           │
│2020-01-04 10:15:23.386 T:18446744073709551615   DEBUG: WinSystemOSX: Fullscreen window iTerm obscures Kodi!
```

## Possible Fix

The error occurs because when `CAddonsDirectory::GetScriptsAndPlugins` is called to populate the list of addons (https://github.com/xbmc/xbmc/blob/f8d76ac9fe3d9e71c3773193c554b8961ad7ae9e/xbmc/filesystem/AddonsDirectory.cpp#L886) the value inside the switch (`addon->Type()`) gets the maintype of the addon (`ADDON_SCREENSAVER`), so the path is never filled. Setting a breakpoint before the switch, its possible to see `m_type` in `CAddon` is defined as a script:

![alt text](https://i.imgur.com/Expqa51.png "Breakpoint")

However `addon->Type()` gets the maintype from `Addon:IAddon`. Using a new method that returns `m_type` instead of `addon->Type()` solves the issue but don't seem to be the appropriate fix for this.

### To Reproduce
1 - Install the version in master branch of my addon (https://github.com/enen92/screensaver.atv4). Addon in repo is not yet compatible with python3.
2 - Run the addon from Video Addons

### Debuglog
Not needed. Log is shown above.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by AlwinEsch** [comment]
Fixed with https://github.com/xbmc/xbmc/pull/17130
