### ISSUE TITLE
Python addons services start at Kodi login screen

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#17136]
### Describe the bug
Here is a clear and concise description of what the problem is:

By fixing problems with Netflix addon in order to work with multiple Kodi profiles,
I noticed a Kodi strange behavior in the Kodi profile switch window,
that causes the addon services to start without reason.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The addons services should be started always and only _after_ a user select a Kodi profile in the Kodi profiles window

## Actual Behavior

When logout from non Master profile addon services start in the login screen

### To Reproduce

How to test:
1. Create two Kodi profiles (1 is the existing master and another one with a new settings), and set to show Kodi window profiles at kodi startup
2. Install netflix addon on the two profiles, _no need to configure Netflix addon, only installing it_
3. Close Kodi
4. Re-open Kodi and login with Master profile, so wait Netflix service notification running
5. Log out from Master profile, in this case there is no Netflix service notification running, and it is right
6. Login with another kodi profile, wait Netflix service notification running
7. Log out from this kodi profile, now in the Kodi switch profile window the services will be started for no reason...

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/rotopesuqa.kodi

Reading the log there is:
`2020-01-05 13:51:17.662 T:12576   DEBUG: QUInf_service_status_Master_user`
The string is ugly i kwnow,
I had added in the netflix service a Print, that when start the service it would check the active Kodi profile name from RPC `Profiles.GetCurrentProfile`
and this indicates that despite logging off from the second profile, inexplicably is logged into the 
**Master user** before selecting it in the Login Kodi window, so the service is started without reason.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64
 - Kodi version: 18.5 (I don't know if Matrix is affected too)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Not that I'm able to confirm it, but I guess it's a valid issue. We had the same behavior for the PVR add-ons as well (starting the service at the login-screen) which was fixed by: 

https://github.com/xbmc/xbmc/pull/16842

Probably this gives an idea how to solve that.

**Comment by enen92** [comment]
Maybe because you don't define the behaviour of your service in addon.xml (https://github.com/CastagnaIT/plugin.video.netflix/blob/master/addon.xml#L14) ?

Extension point definition has been:
`<extension point="xbmc.service" library="service.py" start="[login|startup]" />`

IIRC at some time ago the behaviour was changed to default always to login. Maybe try adding `start="startup"` to your extension point and see if the issue persists.

Disclaimer: I might be totally wrong :)

**Comment by CastagnaIT** [comment]
@enen92 I perform the test immediately

**Comment by CastagnaIT** [comment]
no `start` property do not work...

**Comment by CastagnaIT** [comment]
I will try to make a similar modification as DaVukovic suggested
when i have news I'll update you

**Comment by enen92** [comment]
Issue fixed in https://github.com/xbmc/xbmc/pull/17138
