### ISSUE TITLE
Error Profiles kodi 18

### ISSUE THREAD

**Issue by videofree** [xbmc/xbmc#17135]
### Describe the bug

Here is a clear and concise description of what the problem is:

Then when trying to use the profile kodi does not work properly.

Error when I will use more than one user Kodi takes all the configuration of the user mastrer, even when you configure every user and restart it is not the configuration you made when restarting it loads the master configuration again.

I tried to check in other versions of kodi 18 and confided all versions have the same problem with profile

**Comment by DaVukovic** [comment]
I have several users on different Kodi version (18 and 19). So I can't reproduce your problem at all. 

As a hint, please select "start fresh" for everything if you want a completely separated profile. 

Feel free to ask at our forums for further support questions.
