### ISSUE TITLE
Can't disable logging

### ISSUE THREAD

**Issue by snakyjake1** [xbmc/xbmc#17139]
### Describe the bug
Can't disable logging.

## Expected Behavior
For Kodi to not generate a log file.

## Actual Behavior
Kodi generates a log file.

### Screenshots
I have logging disabled in the GUI:
![Kodi Logging](https://user-images.githubusercontent.com/8312560/71793112-42c69f80-3033-11ea-88ca-390455151fcb.png)

I have logging disabled in advancedsettings.xml:
```
<advancedsettings version="1.0">
     <loglevel hide="true">-1</loglevel>
</advancedsettings>
```

### Your Environment
Kodi v18.5 (Portable)
Windows 7 x64

### Debuglog
https://paste.kodi.tv/loqigapugu.kodi

So why is Kodi still creating a log file?  What/where do I need to change seetings?

Thank you.

P.S.
Need to disable log file because it can get extremely large (gigabytes).

**Comment by DaVukovic** [comment]
Can confirm  this issue. 

`<loglevel hide="true">-1</loglevel>`

From our Wiki, the value `-1` should suppress all log outputs and that's not the case. The log output is the same as for `<loglevel hide="true">0</loglevel>`

>Need to disable log file because it can get extremely large (gigabytes).

Beside that I doubt that a bit... A logfile with normal logging shouldn't end up that large as there's only very basic logging. To achive that your machine has to run 24/7 over a year without being powered off. 

But it's still an issue as `-1` has no effect over `0`

**Comment by DaVukovic** [comment]
I'm closing this for now as Kodi does exactly what we want it to do. 

I'll happily re-open it again if there's any further logging after the `Disable debug logging..."-line. But that's something I cannot reprocude currently and also your log stops at that point.
