### ISSUE TITLE
Using "Next" in Video playlist does not always load "Volume amplification" setting for video

### ISSUE THREAD

**Issue by markosjal** [xbmc/xbmc#17155]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using Kodi for music Videos I use the "Volume amplification" feature set for each video. However when I use the "Next" or "Play Next" button on remote the "volume amplification " setting will show in the GUI but will not apply to the playing video . Making a slight adjustment to the setting causes it to kick in fully (I can sometimes hear it jump from 0 to +12 when I adjusted from +11 to +12)  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would expect that "volume amplification" set for a video would always apply . 

On a further note, I would expect the "Volume Amplification" to allow me to adjust in the negative direction but it does not which makes getting consistent levels across videos is more difficult than it needs to be.

## Actual Behavior

The volume amplification will show on the screen however is not applied to the playing sound.

## Possible Fix

This may or may not be related to the use of the "next" (or "back"?) buttons but I have not seen thie when playing a playlist without using "next" or "back"

### To Reproduce

1. create video playlist 
2.Set different volume levels for each playlist item using "Volume amplification"
3.Use "Next" button on remote
You may not hear your volume amplification adjustments on all videos

### Debuglog

The debuglog can be found here:
Sorry but the requirements placed on debug logs are far too restrictive, limiting addons and how log is posted. The problem is easy enough to reproduce. 

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 9.2.0
 - Kodi version: 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

You really should consider changing some of the language here such as "we require you" especially given you make "no promises" but seemingly demand participation.

**Comment by DaVukovic** [comment]
No log, no further comment, user is unwilling to provide a log. Waited long enough, issue closed
