### ISSUE TITLE
Kodi switches off HDMI display after 10mins playing audio. Works for movies / nothing playing

### ISSUE THREAD

**Issue by matbon108** [xbmc/xbmc#17150]
## Bug report
https://paste.kodi.tv/tecuxifovi.kodi
### Describe the bug
When playing any music after 10 mins Kodi cuts the HDMI signal. The TV shows "No input". There are no screen savers and power saving is disabled. Only happens with Kodi 18. Using Kodi 17 no issues, upgraded to 18 and has this issue. Clean install of Linux and 18 does the same.

Even if I load and loop pictures while playing music it will switch off after 10 mins. Leaving nothing playing on the Kodi menu the screen stays on indefinitely so this proves no screen saver etc.

I consider this a bug as it does it on both a clean install and existing installation and not on Kodi 17. Movies, Pictures etc all play past 10 mins without switching off the HDMI signal. I have attached the debug log and in this message just prior to screen switch off and when I thereafter manually switch the TV off and on again.

## Expected Behavior
I expect the audio to play until end of song / playlist without switching off HDMI.

## Actual Behavior
Switches off HDMI signal after 10 mins.
## Possible Fix
Something happening with the audio sink?
### To Reproduce
1. Play music
2. Wait 10mins
3. Music stops as TV loses signal
### Debuglog
https://paste.kodi.tv/vulotilufe.kodi
### Your Environment
Used Operating system:

 - Operating system version/name: Manjaro - 4.19.91-1-MANJARO
- CPU: AMD Ryzen 3 2200G (4) @ 3.500GHz
- GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series

 - Kodi version: 18.5 Git:20191116-nogitfound

**Comment by matbon108** [comment]
Just to add - when I switch the TV off and on again KODI will still be playing music so there is no crashing just switching off of HDMI signal.

**Comment by a1rwulf** [comment]
Your log indicates that the HDMI signal changes after 10 minutes, it's not kodi that switches off HDMI.

**Comment by matbon108** [comment]
Thanks, I appreciate your response - I thought that too but then why only when playing audio through KODI. Kodi 17 doesn't do this. In addition when I play through a console session in the background via MPG123 while Kodi is on the MENU and KODI itself with nothing playing all works great? In fact thats my current workaround. Yet the moment I play music through kodi 10 mins later HDMI goes off. Movies / series anything else doesn't switch off only music.

**Comment by a1rwulf** [comment]
I don't know and yes, it sounds weird.
But I see you have a ton of piracy addons installed, so if you want further help, you have to remove all of them and post a clean debug log.

**Comment by DaVukovic** [comment]
unfortunately your logfile is incomplete and there might be information missing. Hence I mark this issue accordingly. 

As a suggestion I would try to do: `xset -dpms` and then see if the issue still persists. If not, then that's your solution.

**Comment by DaVukovic** [comment]
No new log, no further comments. Issue closed
