### ISSUE TITLE
Kore 2.5.0 playlist issue

### ISSUE THREAD

**Issue by hetzalwel** [xbmc/xbmc#17152]
### Describe the bug
Here is a clear and concise description of what the problem is:

In version 2.5.0 playlist continuously goes to first song in list.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
in version 2.4.7 playlist stays where you stopped scrolling, starts at song being played

Best regards,

**Comment by ronie** [comment]
please report issues with Kore here: https://github.com/xbmc/Kore/issues
