### ISSUE TITLE
PVR: current channel is not pre-selected in Channel manager

### ISSUE THREAD

**Issue by bam80** [xbmc/xbmc#17167]
## Bug report

When Channel manager is opened from channel's context menu in PVR Live TV channels list - it always opens with the same first channel selected, regardless what channel it was opened from.

It creates significant problems when trying to sort channels right from PVR Live TV channels list, having to search the channels twice - first in the channels list, and then again in Channel manager, since the first search seems unexpectedly just was not used.

## Expected Behavior

The same channel Channel manager was opened from should be pre-selected there.

## Actual Behavior

Channel manager is always opens with the same first channel selected.

## Possible Fix

Channel manager window seem doesn't use any additional info of what channel to select on opening.

### To Reproduce
(see screenshots below):

1. From TV window, select random channel and open context menu on it (`c` key)
2. In the context menu, go Manage...->Channel manager
3. The Channel manager will open. Note it has first channel selected, regardless the channel it was opened from.

### Debuglog

The debuglog can be found here:
http://ix.io/274N

### Screenshots 

Here we have selected "Demo TV Channel 2":
![screenshot000](https://user-images.githubusercontent.com/233979/72195476-8bab9900-3423-11ea-9a0f-7966e552875f.png)
Context menu of that channel:
![screenshot001](https://user-images.githubusercontent.com/233979/72195481-92d2a700-3423-11ea-875f-f4be015ec03d.png)
![screenshot002](https://user-images.githubusercontent.com/233979/72195482-936b3d80-3423-11ea-907d-3fab40378340.png)
Wrong channel pre-selected!:
![screenshot003](https://user-images.githubusercontent.com/233979/72195483-936b3d80-3423-11ea-872a-f3bf63c487a7.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Kodi version: 18.5

**Comment by ksooo** [comment]
Confirming the issue.

**Comment by bam80** [comment]
Thanks a lot!
