### ISSUE TITLE
Some problem of Input method of Chinese,Thks

### ISSUE THREAD

**Issue by lufeilm** [xbmc/xbmc#17168]
### Describe the bug
Here is a clear and concise description of what the problem is:

Candidate characters of Chinese input method cannot be displayed normally. See pic k1.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Actual Behavior

In Windows10, Chinese BadiduPY and Chinese BasePY have the problem.
In Android, Chinese BadiduPY have the problem but Chinese BadiduPY have not. So strange.

## Possible Fix

I think the problem may be Chinese transcoding.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
2020-01-11 10:59:38.277 T:26928   DEBUG: CurlFile::Open(0x330faff450) http://olime.baidu.com/py?input=wo&inputtype=py&bg=0&ed=20&result=hanzi&resultcoding=unicode&ch_en=0&clientinfo=web
2020-01-11 10:59:43.107 T:2220   DEBUG: Thread JobWorker 2220 terminating (autodelete)
2020-01-11 10:59:44.395 T:4800   DEBUG: ------ Window Deinit (Pointer.xml) ------
2020-01-11 11:00:08.675 T:4800    INFO: XCURL::DllLibCurlGlobal::CheckIdle - Closing session to http://olime.baidu.com (easy=0x16c95eb5b30, multi=0x16c95363c70)

Can't see the red error. I try access online input method(BaiduPY:http://olime.baidu.com...) by browser, Response is ok and get right data. So I think the problem may be Chinese transcoding. See pic k2.

### Screenshots 
Here are some links or screenshots to help explain the problem:

![k1](https://user-images.githubusercontent.com/8934829/72198206-fdf09d80-3464-11ea-93b8-a0a000a066d6.png)

![3](https://user-images.githubusercontent.com/8934829/72198367-3e511b00-3467-11ea-97cf-a729a2238708.png)

![4](https://user-images.githubusercontent.com/8934829/72198378-5fb20700-3467-11ea-9b79-24c147212001.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: KODI 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Could you please try to use an arial based font. That can be changed in the settings -> interface -> skin -> font

Please confirm if that fixes your issue or not.

**Comment by superhukun** [comment]
I've tried using an arial based font for Kodi 18.5 on Windows 10, but the issue is still there.

**Comment by DaVukovic** [comment]
Could you please provide a full debuglog. Thanks

Took a deeper look at the image you posted and seen something like "Fusion install" on it. Be aware, that if you are using banned add-ons, that we neither give support nor are interested in bugs which are related to banned add-ons.

**Comment by lufeilm** [comment]
> Could you please provide a full debuglog. Thanks
> 
> Took a deeper look at the image you posted and seen something like "Fusion install" on it. Be aware, that if you are using banned add-ons, that we neither give support nor are interested in bugs which are related to banned add-ons.

Yes，I install some the third addons. and the third addons may be cause the issue. 
Previously, to be in a clean and new environment, I have reinstalled os system(Windows10 Multiple versions) and Kodi , but the test result is still the same . I am very sorry for provided the test that has installed the third-party addons. Thks.

**Comment by taxigps** [comment]
bug confirmed.
1. problem of BaiduPY is the webapi changed.
the request:
`http://olime.baidu.com/py?input=wo&inputtype=py&bg=0&ed=20&result=hanzi&resultcoding=unicode&ch_en=0&clientinfo=web`
returns only one word, not a word list:
`{"0":[[["我",2,{"pinyin":"wo","type":"IMEDICT"}]]],"1":"wo","result":[null]}`
may be the web service is closed.

2. problem of BasePY is a encoding issue under windows development environment. add a build option /utf-8 fixed this.
![buildkodi](https://user-images.githubusercontent.com/102434/80793678-5b525b00-8bca-11ea-9436-73ffb90d58c3.jpg)

**Comment by DaVukovic** [comment]
@taxigps 

Could you please tell me the exact!!!! steps how to reproduce this?

**Comment by taxigps** [comment]
there is a chinese word map in https://github.com/xbmc/xbmc/blob/master/xbmc/input/InputCodingTableBasePY.cpp, and this file save as utf-8 with no BOM, need build with utf-8 encoding. no problem under linux becasue the system use utf-8 encoding.

**Comment by taxigps** [comment]
@DaVukovic to reproduce the issue:
test with Kodi under windows 10. set Fonts to `Arial based`,  set Keyboard layouts to `Chinese BasePY `. open virtual keyboard and type `wo`.  you can see the unintelligible text
![screenshot_bug](https://user-images.githubusercontent.com/102434/80865626-3f7bb180-8cbd-11ea-9a19-b2c54930b627.png)

and after bug fixed, the right screen is:
![screenshot_fixed](https://user-images.githubusercontent.com/102434/80865676-84074d00-8cbd-11ea-932e-98120e4275fe.png)

**Comment by DaVukovic** [comment]
Ok, thanks. I don't have that problem under linux and I also don't have Windows installed anywhere anymore. So I can't reproduce. 

The reported is also saying that he has the problem on Android as well. I just tested on Android with Kodi 18.6 and it works fine for me using Estuary and an Arial based font. 

But I won't doubt that this might be a Windows related problem. So I'll label this issue accordingly. 

Btw...if you @taxigps have a fix at hand. Feel free to PR it.

**Comment by taxigps** [comment]
@DaVukovic sorry, i don't know where to add the option /utf-8 into the cmake files.

**Comment by lufeilm** [comment]
> Ok, thanks. I don't have that problem under linux and I also don't have Windows installed anywhere anymore. So I can't reproduce.
> 
> The reporter is also saying that he has the problem on Android as well. I just tested on Android with Kodi 18.6 and it works fine for me using Estuary and an Arial based font.
> 
> But I won't doubt that this might be a Windows related problem. So I'll label this issue accordingly.
> 
> Btw...if you @taxigps have a fix at hand. Feel free to PR it.

In Android,   baidupy is not work，  basepy works fine .  As what taxigps say, may be add the option /utf-8,. but  I 'm sorry can't  do something for you.

**Comment by scott967** [comment]
This issue still exists in Kodi 19.1 for BasePY keyboard.  See user support issue here:[https://forum.kodi.tv/showthread.php?tid=364644](url) and I also confirmed in Windows 10 21H1 x64.

**Comment by taxigps** [comment]
I'll fix this bug in few days.

**Comment by taxigps** [comment]
Done.

**Comment by scott967** [comment]
Fix confirmed on Win 10 x64

**Comment by Shiliu-daddy** [comment]
请问下，这个修复后的文件怎么使用？ @taxigps @scott967

**Comment by Shiliu-daddy** [comment]
> @taxigps@scott967

请问如何使用你们修复后的文件呢
