### ISSUE TITLE
Feature request: Implement Google Assistant/Home Local Execution

### ISSUE THREAD

**Issue by muhkuhgh** [xbmc/xbmc#17162]
There are many guides and complicated work-arounds out there to make it possible to control Kodi with our Voice using Google Home devices.

With the release of Local Execution this could be natively integrated into Kodi. https://developers.google.com/assistant/smarthome/concepts/local

**Comment by fuzzard** [comment]
Git is for bug issues only.

Feature requests can be submitted on the forums at https://forum.kodi.tv/forumdisplay.php?fid=9
