### ISSUE TITLE
Documentation: sources.xml, wrong name of source section

### ISSUE THREAD

**Issue by doko-desuka** [xbmc/xbmc#17165]
### Describe the bug
Here is a clear and concise description of what the problem is:

In the sources.xml documentation page, "1.3 Required Fields" section, it says that other valid section names are "(...) \<videos\>", but Kodi uses `<video>` in the actual file (singular, not plural).  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Are both `<videos>` and `<video>` names supported? If not, that docs page should be corrected so that `<video>` is used.

### To Reproduce

See this page: https://kodi.wiki/view/Sources.xml#Required_Fields

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 8 x64
 - Kodi version: 17.6 Krypton

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
i have fixed the wiki page. thanx for the heads-up!

**Comment by doko-desuka** [comment]
Thank you @ronie!
