### ISSUE TITLE
Crash Windows 7 x86

### ISSUE THREAD

**Issue by armandojrod** [xbmc/xbmc#17175]
### Describe the bug

It crashes on startup, unintsalled and removed profiles, installed again and it crashes no matter what

## Expected Behavior
Not to crash

## Actual Behavior
Crash on startup

### To Reproduce
Cant seen to know reproduce steps

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Windows
 

 - Operating system version/name:
 - Kodi version:
18.5 x86
[kodi_stacktrace-18.5 Git_20191116-37f51f6e63-20200111-154848.txt](https://github.com/xbmc/xbmc/files/4049724/kodi_stacktrace-18.5.Git_20191116-37f51f6e63-20200111-154848.txt)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Please provide a debug log or this issue will be closed in 3 days.

If you don't know how to provide a debuglog, then close this issue and request assistance on the forum.
