### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by MikeDickert** [xbmc/xbmc#17177]
### Describe the bug
Here is a clear and concise description of what the problem is:

Multiple issure:

1 - Can't get Library to populate using instructions included with program.
     files are on external drive.
  
2 -  Program uses the same thumbnail for all movies in a series

3 - Program creates multiple entries for the same move

4 - Program s[ends hours on Movie Database with no noticible changes.

Windows 10

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
This is clearly user error and not a bug in Kodi.

Please submit your request for assistance on the Kodi forum

**Comment by MikeDickert** [comment]
How is creating 2+ entries for the same movie, or using the same thumbnail for a series of movies (I.E. Saw 1's thumbnail for Saw 2-7) a user error.  I'll give you the library population. 

There Is a Goddess and She LOVES me! 

-----Original Message-----

**Comment by KarellenX** [comment]
Please take your questions to the forum and I will assist you there.

I will not respond any further here.
