### ISSUE TITLE
Kodi crashes when playing mp4 file

### ISSUE THREAD

**Issue by timbe16** [xbmc/xbmc#17174]
### Describe the bug
Kodi crashes while playing specific mp4 file

## Expected Behavior
Kodi does not crash.

## Actual Behavior
Kodi crashes.

### To Reproduce

1. Download small 30 second sample file here:
https://drive.google.com/open?id=1U3T17CfSCs6kt-SxejRWhE_uIWZxgQEr
1. Copy the sample mp4 into the Kodi
1. Play the file (from Video menu)
1. Kodi crashes

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/ufeqamobax.kodi
The crash log can be found here: https://paste.kodi.tv/avolocukub.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC (official): 9.2.0 (RPi2.arm)
 - Kodi version: 18.5 (Git:newclock5_18.5-Leia)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
```
2020-01-11 16:55:21.418 T:1471140736   ERROR: CMMALVideo::Open : Video codec unknown: ad
2020-01-11 16:55:21.419 T:1471140736  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: HEVC (rpi)
2020-01-11 16:55:21.420 T:1471140736   DEBUG: CDVDVideoCodecFFmpeg - open frame threaded with 8 threads
```

Please headover to LibreELEC's github. The HEVC funcationality you are using and where it crashes is not related to kodi's current codebase.
