### ISSUE TITLE
Crash when entering Music with Windows x64 nightlies from Git #13b742ee

### ISSUE THREAD

**Issue by jjd-uk** [xbmc/xbmc#17180]
### Describe the bug
Beginning with http://mirrors.kodi.tv/nightlies/windows/win64/master/KodiSetup-20200107-13b742ee-master-x64.exe Kodi crashes when selecting Music button on Estuary Home menu, it doesn't happen when selecting Movies, TV Shows etc on Home menu. This is a new clean install with nothing added.

When using http://mirrors.kodi.tv/nightlies/windows/win64/master/KodiSetup-20200106-e9806a39-master-x64.exe everything is ok.

Therefore it would seem to be a commit from the 7th causing the issue, most likely candidate to me would seem to be https://github.com/xbmc/xbmc/pull/17143

## Expected Behavior
When selecting Music on Home menu the node list should open.

### To Reproduce

1. Install http://mirrors.kodi.tv/nightlies/windows/win64/master/KodiSetup-20200107-13b742ee-master-x64.exe or any nightly after this.
2. Launch Kodi.
3. Select Music button on Estuary Home menu.
4. New window where node list would appear begins to open but nothing gets displayed and then the Kodi force closes.

### Debuglog
Log https://paste.kodi.tv/ulifijiyux.kodi
Crash log https://drive.google.com/open?id=1RsMtKRn3fKAXErVKdaATj-dGfxLG5z8c
Stacktrace https://drive.google.com/open?id=1Tmw-mMU7MrNqvspBBkXpTiK9200zG8eA

### Screenshots 
N/A

## Additional context or screenshots (if appropriate)
N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 
 - Kodi version: Kodi (19.0-ALPHA1 Git:20200107-13b742ee75)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jjd-uk** [comment]
@Paxxi confirmed on Slack he was able to replicate and is it crashing in libcdio so would seem to be due to depends update for Windows only.

**Comment by DaveTBlake** [comment]
I think @Paxxi has fixed this, but somehow managed to merge the fix to master without a PR so I can't link it just the commit https://github.com/xbmc/xbmc/commit/9a42e315496d57614f0b988a060d6660f415c230. 

Can you test the current nightly @jjd-uk and set labels/close this if successful

**Comment by jjd-uk** [comment]
Yes it's fixed now.
