### ISSUE TITLE
linker error with scummvm

### ISSUE THREAD

**Issue by svenfoo** [xbmc/xbmc#17199]
### Describe the bug
Here is a clear and concise description of what the problem is:

The ScummVM add-on does not start due to a linker error:
game.libretro.scummvm.so: undefined symbol: _ZN3 GUI13OptionsDialog5cleanEv

ScummVM version 2.0.0.6.1 from the Libreto add-on repository

Kodi is version 9.2.0, running on a Raspberry Pi 4.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

ScummVM should start.

## Actual Behavior

A popup appears, telling me that the add-on can not be loaded. 

## Possible Fix

Looks like a build issue.

### To Reproduce

1. Install ScummVM emulator from the official repository.
2. Try to start the ScummVM add-on.
3. Does not start.

### Debuglog

```
2020-01-15 22:06:05.639 T:3011355232   ERROR: AddOnLog: ScummVM: Unable to load: /storage/.kodi/addons/game.libretro.scummvm/game.libretro.scummvm.so: undefined symbol: _ZN3
GUI13OptionsDialog5cleanEv
2020-01-15 22:06:05.639 T:3011355232   ERROR: AddOnLog: ScummVM: Failed to load /storage/.kodi/addons/game.libretro.scummvm/game.libretro.scummvm.so
2020-01-15 22:06:05.639 T:3011355232   ERROR: ADDON: Dll ScummVM - Client returned bad status (5) from Create and is not usable
2020-01-15 22:06:08.054 T:3011355232   ERROR: RetroPlayer[PLAYER]: Failed to initialize game.libretro.scummvm


```
### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 9.2.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
This is a LibreELEC problem. Please report it on their forum.

**Comment by svenfoo** [comment]
It's been reported there, months ago, but it's still broken in the same way:
https://forum.libreelec.tv/thread/14371-retroplayer-scummvm/?postID=116866#post116866

Anyway, thanks for pointing me into the right direction and please accept my apologies for reporting it in the wrong place.
