### ISSUE TITLE
[v18] Empty default="" values in rating tag will crash Kodi when scanning

### ISSUE THREAD

**Issue by Borromini** [xbmc/xbmc#17191]
I first reported this issue on the [forum](https://forum.kodi.tv/showthread.php?tid=350961), but was asked to file it here as well.

A scan of my series library would trigger a Kodi crash - crashlog is [here](https://paste.kodi.tv/xuveyiduyo.kodi) and the offending .NFO content [here](https://paste.kodi.tv/hugidatemo). It turns out an .NFO containing `<rating default="" max="10" name="thetvdb">` would crash Kodi. The .NFO files were produced by SickGear (related bug [here](https://github.com/SickGear/SickGear/issues/1162)).

Replacing `default=""` with `default="true"` (or false) will make Kodi happily scan my whole library as if nothing happened.

### Debuglog
* Debug log [here](https://paste.kodi.tv/xuveyiduyo.kodi) (same as above)
* NFO contents [here](https://paste.kodi.tv/hugidatemo) (same as above)

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 9.2.0
 - Kodi version: 18.5

**Comment by Borromini** [comment]
Hi,

The report contains everything necessary - problem & solution.

Thanks

B

-------- Oorspronkelijk bericht --------
Aan 14 jan. 2020 22:20, xbmc-gh-bot[bot] schreef:

**Comment by KarellenX** [comment]
Thank you @Borromini 

There have been further reports here... https://github.com/SickGear/SickGear/issues/1162#issuecomment-573330382 by @JackDandy

**Comment by JackDandy** [comment]
> It turns out a malformed .NFO (containing <rating default="" max="10" name="thetvdb">) 
  
**malformed** is not correct given that the pattern `default=""` is [documented here](https://kodi.wiki/view/NFO_files/TV_shows#nfo_Tags) in the Kodi wiki. The issue was first discovered 4th Jan on OSMC, and SickGear found it too - I blame the docs :p  
   
Kodi wiki NFO_files guidance...
<img src="https://i.vgy.me/yXg9N4.png">
  
@KarellenX The links I forwarded indicate code in Kodi core that _may_ be the cause of the crashing when it reads the `.nfo` text file, and the issue only seems to happen with particular configurations.

**Comment by Borromini** [comment]
@JackDandy There was no judgement in that 😄

**Comment by JackDandy** [comment]
@Borromini 

Gotchya. I added clarity because the word `malformed` _can_ be read to place responsibility. Anyway, SickGear released handling for this issue 2 days ago. On application update, as a one time process, **all** `.nfo` files are scanned and fixed where required.

**Comment by KarellenX** [comment]
@JackDandy 

I have updated the wiki, hopefully removing the ambiguity.
