### ISSUE TITLE
Kodi 18.5 Nightly (Android) terminates instantly playing music when visualisation enabled

### ISSUE THREAD

**Issue by Angadang** [xbmc/xbmc#17207]
### Describe the bug
Kodi Leia Nightly - Amazon Fire TV 4K - crashes instantly when attempting to play music with Visualisation enabled. Works as expected (excepting ProjectM) with 18.5 release. Tested with clean install. No add-ons other than Updater and the Visualisation plug-ins.

## Expected Behavior
Should play music, display visualisation after interval.

## Actual Behavior
Player instantly terminates. 

## Possible Fix
Could be related to this commit:
https://github.com/xbmc/xbmc/pull/17101

### To Reproduce
1. Enable visualisation.
2. Play Music.
3. Crash

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/4074791/kodi.log)

### Your Environment
Android: Amazon Fire TV OS

 - Kodi version:
Kodi (18.5 Git:20200115-4db5f328d1). Platform: Android ARM 32-bit

**Comment by Angadang** [comment]
Still an issue with Nightly release: kodi-20200126-4a590f58-Leia-armeabi-v7a.apk

**Comment by djp952** [comment]
Being the one that submitted https://github.com/xbmc/xbmc/pull/17101 I felt kinda bad when I saw this.  I've run a number of Android tests with the same Visualization on recent Leia Nightlies and haven't been able to reproduce the problem (my intention being requesting the PR be revoked if it was the cause).  I do have a FireStick 4K I can test on, understanding it's not exactly the same device, if you think that will help.

All the PR does is prevent a Visualization from receiving "no data at all", which most of them don't appear to be coded to handle.  I don't see how that could cause Kodi to crash, quite the opposite in fact, but if there is any additional information you can provide I would love to try it out as best I can to see if I can corroborate this and help get the PR pulled out before 18.6/19.0 come to fruition.

I sincerely apologize if a fix for my PVR addon users broke something for you, but I have not been able to prove that.

**Comment by fritsch** [comment]
Let me build a testbuild with a revert tonight, then we will see. I am quite sure it's not your change.

@AlwinEsch ping. Do you have an idea here?

**Comment by Angadang** [comment]
Tested it with the kodi-20200203-2c4bcdbf-Leia-armeabi-v7a build. Crashes instantly with all visualisations. Rolling back to the release restores funcionality. 

Have not confirmed it with other Fire TV hardware.

**Comment by AlwinEsch** [comment]
Because of your case, can you start the music without a visualization (all deactivated) to determine differences and upload the corresponding log?.

What confuses me that after the first log no visualization addon was loaded and points to a crash in Kodi itself.

**Comment by Angadang** [comment]
@AlwinEsch
4 logs included: nightly with and without visualisation (Shadertoy), release with and without visualisation. Filenames related.

In each case I opened Kodi and played an MP3 located on an SMB drive for a few seconds then exited the program. The release played the visualisation as expected. The nightly immediately terminated without
[kodi-20200203-2c4bcdbf-Leia-armeabi-v7a - no Visualisation.log](https://github.com/xbmc/xbmc/files/4162757/kodi-20200203-2c4bcdbf-Leia-armeabi-v7a.-.no.Visualisation.log)
[kodi-20200203-2c4bcdbf-Leia-armeabi-v7a - Shadertoy.log](https://github.com/xbmc/xbmc/files/4162758/kodi-20200203-2c4bcdbf-Leia-armeabi-v7a.-.Shadertoy.log)
[kodi-18.5-Leia-armeabi-v7a - Shadertoy.log](https://github.com/xbmc/xbmc/files/4162760/kodi-18.5-Leia-armeabi-v7a.-.Shadertoy.log)
[kodi-18.5-Leia-armeabi-v7a - no Visualisation.log](https://github.com/xbmc/xbmc/files/4162761/kodi-18.5-Leia-armeabi-v7a.-.no.Visualisation.log)



 playing any sound.
