### ISSUE TITLE
ListItem.Title is used as Label when SortMethod is added

### ISSUE THREAD

**Issue by dagwieers** [xbmc/xbmc#17200]
### Describe the bug
When you have a virtual listing that has a (any) SortMethod added, the listing uses `ListItem.Title` as label and not `ListItem.Label`.

We need to have a different label because in the listing we show both the TvShow name (ListItem.TvShowTitle) as well as the Episode name (ListItem.Title) inside the label.

This issue is explained in pietje666/plugin.video.vrt.nu#667 (and in #17156).

## Expected Behavior
We expected to always see the ListItem.Label no matter if a SortMethod was added.

## Actual Behavior
We get the ListItem.Title instead.

## Possible Fix
I couldn't find the cause in the Estuary code, so I believe this is a problem in Kodi itself. As confirmed by @ronie.

### To Reproduce
1. Take the code from #17156 (https://github.com/xbmc/xbmc/pull/17156#issuecomment-572543143)
2. Add a SortMethod 
3. See that not the Label was used, but the Title

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 9.2.0
 - Kodi version: Kodi 18

**Comment by DaVukovic** [comment]
PR already merged. So this one is good to close
