### ISSUE TITLE
EjectTray() function does not stop playback before ejecting

### ISSUE THREAD

**Issue by duck7000** [xbmc/xbmc#17203]
This is a small bug but it is "bugging" me for quite a while

In short:
I have configured the remote eject button to the kodi EjectTray() function.
Suppose i playback a blu-ray or dvd disc.
if i use the eject button the EjectTray() function does not stop playback before ejecting the disc.

In other words the EjectTray() function does not check if the videoplayer is active or not, just kicks out the disc even if the drive is in use by the videoplayer.

It is platform independent and is in all kodi versions from 16 until current afaik

the EjectTray() function should stop playback first if the drive is in use, then eject the disc.

**Comment by duck7000** [comment]
I made it very clear what the issue is, there is no point to fill in a useless form for this small issue like providing log files i think.

I understand the need for following a template for larger or complex issues but in this case i think it is unnecessary so i hope a team member will remove the ignore rules tag.

**Comment by ronie** [comment]
ok
