### ISSUE TITLE
WASAPI Audio collision with YouTube in Chrome  [Version 79.0.3945.117]

### ISSUE THREAD

**Issue by j13ag0** [xbmc/xbmc#17204]
### Describe the bug
When I set Audio output device to:  WASAPI  
any attempt to play a YouTube video in Chrome generates a YouTube error that says:
"Audio renderer error. Please restart your computer."
Similarly, streaming radio like that from CBC will not play.
https://www.cbc.ca/listen/live-radio?radio_one=toronto&cbc_music=toronto
Setting 'Audio output device' in Kodi back to  DIRECTSOUND: default  fixes the problem.

## Expected Behavior

As noted above, before January 14, I had no problems with running Kodi and Chrome [for YouTube content] side by side on the Windows 10 desktop.  

## Actual Behavior

As of now, using WASAPI for audio device in Kodi is not an option if I want to use Chrome to watch YouTube content.

## Possible Fix

This problem is new as of Tuesday or Wednesday, January 14 or 15, 2020.
I suspect that a new version of Chrome [auto-updated] created the new circumstance.
I have not updated Kodi lately.

### To Reproduce

1. Start Chrome and load a YouTube video.
2. In Kodi, set Audio output device to:  WASAPI
3. Chrome displays the error message:  "Audio renderer error. Please restart your computer."

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/4072374/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![NUC_shot1](https://user-images.githubusercontent.com/7916043/72543258-771c3600-3853-11ea-94d7-1b28b897396f.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
            Windows 10
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:   18.9    Git:20191116-37f51f6e63

I'm running KODI [ 18.9 ] on Windows 10 on an Intel NUC.  It's running headless, so I access the desktop using Microsoft Remote Desktop from my iMac.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
This is wanted behaviour. Wasapi is exclusive to be able to do passthrough. If you want to mix choose directsound.

**Comment by j13ag0** [comment]
Sorry for the noise and thanks for clarifying.
-jg-
