### ISSUE TITLE
Subtitle background opacity setting does not work properly

### ISSUE THREAD

**Issue by mimmiepower** [xbmc/xbmc#17216]
### Describe the bug
Here is a clear and concise description of what the problem is:

Setting subtitle background opacity to anything in-between 1% and 100% will make it opaque; it is not possible to make it transparent. Setting it to 0% will make it disappear (so that works).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When setting the opacity to 50% the background would have a 50% opacity, i.e. you would be able to see through it.

## Actual Behavior

The background has 100% opacity.

## Possible Fix

I do not have any.

### To Reproduce

1. Go to System settings > Player > Language
2. Set "background opacity" under "Subititles" to 50%
3. Restart Kodi.
4. Play a video with subtitles (that is not ASS/SSA, unless you have chosen to override that in settings) and scrobble to a part with subtitles.

### Debuglog

The debuglog can be found here:
Sorry, I just wanted to report it so that you can fix it if you want to. I do not have time to provide one. 

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.5.0 - Leia

By the way, I wish it was possible to configure the outline of the subtitles as well as apply a shadow that you can customize. The default is too thick for my liking.

**Comment by ronie** [comment]
can't reproduce and no debuglog to investigate any further.
