### ISSUE TITLE
RTP streams that use an interface IP incorrectly interpreted as username

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#17220]
### Describe the bug
Here is a clear and concise description of what the problem is:

As an example if a stream has this URL: `rtp://87.141.215.251@232.0.20.35:10000`

The `87.141.215.251` will be interpreted as the username instead of being passed at part of the URL.

Reported in forum post: https://forum.kodi.tv/showthread.php?tid=350901

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The `87.141.215.251` will be interpreted as part of the URL.

## Actual Behavior

The `87.141.215.251` will be interpreted as A username.

## Possible Fix

Check when extracting a username if it’s an IP. If not then leave the URL as is. Not sure of the impact/side effects of doing this.

### To Reproduce

1. Add an RTP stream with the above format to IPTV Simple 
2. Play the stream/channel
3. Stream not recognised error

### Debuglog

The debuglog can be found here:

From forum post: https://paste.kodi.tv/wufogamapi.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 16.04 LTS
 - Kodi version: 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
root@L380:/home/fritsch# LANG=US adduser 10.0.0.1
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "US"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
adduser: Please enter a username matching the regular expression configured
via the NAME_REGEX[_SYSTEM] configuration variable.  Use the `--force-badname'
option to relax this check or reconfigure NAME_REGEX

User the NAME_REGEX[_SYSTEM] if it does not match, pass it along?

**Comment by fritsch** [comment]
I know that you can use --force-badname, but at least then we have a kind of default that is matching common standards.

**Comment by fritsch** [comment]
And for the record: I did not find any standard that would say: if you need to tunnel an IP address, please just write it prior to the @ sign, so that clients need to role a dice to differentiate passing through with usernames. This really looks like selfmade pain and some VPN usage for workarounding misconfigured local network settings.

**Comment by fritsch** [comment]
I am wrong! Cool - learned something.

See: https://open.cinegy.com/products/route/user-manual/cinegy-route-browser/rtp-udp-url/
StreamIP can be: [SourceIP][@MulticastIP]

That means for us: IP1@IP2 is valid and is used to transmit the source IP towards the MulticastIP

That means:
if you detect an IP prior to the @ - pass it along and don't assume a username if we speak rtp
