### ISSUE TITLE
Random black square on top of film

### ISSUE THREAD

**Issue by MuadDib69** [xbmc/xbmc#17221]
### Describe the bug
Kodi Leia 18.4 running on Pi4 (buster) updated && upgraded.
Some times on playing video files just after fresh boot, a black square appears on top the movie (upperleft corner)(see capture, marked with pink arrows) not covering all screen. It is not file-deppendant, once occurs, will happen with all video files. Even happened after long-time paused movie, on going back to play it, black square again.
Only solution is reboot.

## Expected Behavior
No black square

## Actual Behavior
Occasional black square

## Possible Fix
Dunno

### To Reproduce

1. Start PI4 > start kodi
2. Movies > play one
3. Black square on top upper left corner

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://imgur.com/a/DFMmGTr
![aSWOXyQ](https://user-images.githubusercontent.com/20368939/72680499-c7e19800-3aba-11ea-967d-9049c4b516ec.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspbian Buster
 - Kodi version: 18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You missed to provide a debuglog.

Also please do us a favour and try to reproduce your issue using LibreELEC. Debian is using an outdated Kodi 18 Version, as we are actually on 18.5. So fixes might be missing which LibreELEC do contain. 

If you are able to reproduce your issue with LibreELEC, then please get us a logfile

**Comment by MuadDib69** [comment]
I'm sorry, didnt install from libreELEC.
Thanks 4 your comments.

**Comment by MuadDib69** [comment]
Closing
