### ISSUE TITLE
Audio visualizations broken in Kodi 18.5 on macOS

### ISSUE THREAD

**Issue by MarkCallow** [xbmc/xbmc#17244]
### Describe the bug
Here is a clear and concise description of what the problem is:

After updating to Kodi on macOS to Leia 18.5, Spectrum and ProjectM visualizers stopped working.  I have not tried any others but suspect they are all broken.

Message boxes appear saying that starting visualization failed.

The log reveals that the system would not load the visualizers' .dylibs because the .dylibs  are completely unsigned but the Kodi process is using library validation. It is using validation because Kodi 18.5 has been signed and notarized (for which a big thanks to the Kodi team) and is using the macOS hardened runtime.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Visualization should continue to run as it  did in Kodi 18.4

## Actual Behavior

Instead of visualization running message boxes appear saying that starting visualization failed.

## Possible Fix

Sign the visualizers' .dylibs. An ad-hoc signature may be sufficient.

### To Reproduce

1.  Install Kodi 18.5 on macOS 10.14.5+ or 10.15
2. Install ProjectM visualizer
3. Play some music
4. Go to the full-screen music display.
5. Set ProjectM as the visualizer.
6. Press backspace to return to previous screen.

Step 6 may not be necessary. An error message box may show up at step 5.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/cunerazapa.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS 10.14.6
 - Kodi version: 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Angadang** [comment]
Tested all visualizations with 18.5 on Fire TV (Android). All but ProjectM working. 

ProjectM error: Addon couldn't be loaded. An unknown error has occurred.

But all broken in Nightlies: https://github.com/xbmc/xbmc/issues/17207

**Comment by MarkCallow** [comment]
@Angadang the problem described here is specific to macOS. If visualizations aren't working on other platforms or in later versions of Kodi, the causes are different.

**Comment by fuzzard** [comment]
Issue is resolved regarding current releases.
