### ISSUE TITLE
Please clarify the license of tools/EventClients/icons/bluetooth.png

### ISSUE THREAD

**Issue by rbalint** [xbmc/xbmc#17252]
### Describe the bug

I could not find the license for the tools/EventClients/icons/bluetooth.png file.
There is embedded authorship information in the EXIF information:
`Desktop-sized icon.============..(c) 2003 Jakub 'jimmac' Steiner, .http://jimmac.musichall.cz..created with the GIMP,.http://www.gimp.org`

## Expected Behavior

The license for all files distributed in Kodi is expected to be clear.

## Actual Behavior

There is no license file relevant to the file.

## Possible Fix

Please clarify the source and the license of the file or replace it with one with a known license.

### To Reproduce

Browse the source tree around the file and find no relevant license.

### Your Environment
Used Operating system:
 - [X ] Linux

 - Operating system version/name:
 - Kodi version: 18.5 / master

**Comment by rbalint** [comment]
Most likely @jimmac can clarify the license easily.

**Comment by lrusak** [comment]
Just as an aside, it looks like this icon was added back in 2008 via https://sourceforge.net/p/xbmc/svn/12101/

There is no licencing details present there either.

**Comment by jimmac** [comment]
The icon comes from gnome-icon-theme which was GPL v2 / LGPL

**Comment by DaVukovic** [comment]
@rbalint 

So good to close this issue then? Or is there something else which needs to be done?

**Comment by rbalint** [comment]
@DaVukovic I think it is worth adding the info to the source, too, see the PR.
