### ISSUE TITLE
PVR: On Replay, allow to play next show 

### ISSUE THREAD

**Issue by Mannshoch** [xbmc/xbmc#17256]
### Describe the bug
In most TV-Box from internet providers you have the ability to show a replay TV and after that you get asked if you wish to see the next in EPG following show.
I reported this Request on a PVR-Addon. It seems that it is not possible to setup this because of missing API
https://github.com/rbuehlma/pvr.zattoo/issues/71

## Expected Behavior

1. A TV show watched as Replay TV finish is finishing in the next 120s: 
1. The application check what show on this timestamp where this show end in this channel is running 
1. A popup appear and request if user wish to show the next show after end of this show
1. If user select yes, kodi try to seamless handover to the next TV show after the current show finish
    e.g. 
   1. the yesterday shows ending is at 11:35. 
   1. EPG see the show which currently running ends at 11:35 is "AmazeingFilm" which started yesterday 11:30.
   1. The app put "AmazeingFilm" to the queue with starting time 5min 
 1. User has a seamless transfer to the next show.

## Actual Behavior
The show simply end. User have to search in EPG for the following show.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Libreelec (Kodi 18.5)

**Comment by DaVukovic** [comment]
This is not the correct place for feature requests. Feature requests have to be made at the "Feature requests" subforum at forum.kodi.tv
