### ISSUE TITLE
Arch Linux Arm 4.19  ‘#include <cassert>’?

### ISSUE THREAD

**Issue by StuartIanNaylor** [xbmc/xbmc#17279]
Arch linux Arm 4.19.97-1

[ 38%] Building CXX object build/pvr/addons/CMakeFiles/pvr_addons.dir/PVRClients.cpp.o
cd /home/alarm/kodi-build/build/pvr/addons && /usr/bin/c++  -DHAS_NEON -I/home/alarm/kodi -I/home/alarm/kodi/lib -I/home/alarm/kodi/lib/gtest/include -I/home/alarm/kodi/xbmc -I/home/alarm/kodi/xbmc/platform/linux -I/home/alarm/kodi/xbmc/cores/VideoPlayer -I/home/alarm/kodi-build/build -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/python2.7 -I/usr/include/samba-4.0 -I/usr/include/libxml2 -I/home/alarm/kodi-build/build/cpluff/include -I/home/alarm/kodi-build/build/include -I/home/alarm/kodi-build/build/cores/RetroPlayer/messages -I/usr/include/freetype2 -I/home/alarm/kodi-build/build/libdvd/include -I/usr/include/lzo -I/usr/include/libdrm  -std=c++11 -DPLATFORM_SETTINGS_FILE=x11.xml -Wall -O3 -DNDEBUG -s   -D_LINUX -DTARGET_POSIX -DTARGET_LINUX -D_GNU_SOURCE -DHAVE_LINUX_MEMFD=1 -DHAVE_MKOSTEMP=1 -D__STDC_CONSTANT_MACROS -D_FILE_DEFINED -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DHAS_LINUX_NETWORK -DHAVE_STD__U16_STRING=1 -DHAVE_STD__U32_STRING=1 -DHAVE_CHAR16_T=1 -DHAVE_CHAR32_T=1 -DHAVE_STDINT_H=1 -DHAS_BUILTIN_SYNC_ADD_AND_FETCH=1 -DHAS_BUILTIN_SYNC_SUB_AND_FETCH=1 -DHAS_BUILTIN_SYNC_VAL_COMPARE_AND_SWAP=1 -DHAVE_INOTIFY=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_LOCALTIME_R=1 -DHAVE_INTTYPES_H=1 -DHAS_ALSA=1 -DHAS_AVAHI=1 -DHAS_ZEROCONF=1 -DHAVE_LIBBLURAY=1 -DHAVE_LIBBLURAY_BDJ=1 -DHAVE_LIBCEC=1 -DHAS_DBUS=1 -DHAVE_LCMS2=1 -DHAS_LIRC=1 -DHAS_WEB_SERVER=1 -DHAS_WEB_INTERFACE=1 -DHAS_FILESYSTEM_NFS=1 -DHAS_PULSEAUDIO=1 -DHAS_PYTHON=1 -DHAS_FILESYSTEM_SMB=1 -DHAS_SNDIO=1 -DHAVE_LIBUDEV=1 -DHAVE_LIBXSLT=1 -DHAVE_LIBVA=1 -DHAVE_LIBVDPAU=1 -DHAS_GLX=1 -DHAS_AIRPLAY=1 -DFFMPEG_VER_SHA=\"4.0\" -I/usr/include/fribidi -DHAS_GL=1 -DHAS_EGL=1 -DHAVE_X11=1 -DHAVE_LIBXRANDR=1 -DHAS_MYSQL=1 -DHAS_UPNP=1 -DHAS_DVD_DRIVE -DHAS_CDDA_RIPPER -DHAS_AIRTUNES=1 -DBIN_INSTALL_PATH=\"/usr/local/lib/kodi\" -DINSTALL_PATH=\"/usr/local/share/kodi\" -std=c++11 -o CMakeFiles/pvr_addons.dir/PVRClients.cpp.o -c /home/alarm/kodi/xbmc/pvr/addons/PVRClients.cpp
/home/alarm/kodi/xbmc/profiles/dialogs/GUIDialogProfileSettings.cpp: In static member function ‘static bool CGUIDialogProfileSettings::ShowForProfile(unsigned int, bool)’:
/home/alarm/kodi/xbmc/profiles/dialogs/GUIDialogProfileSettings.cpp:174:5: error: ‘assert’ was not declared in this scope
  174 |     assert(profile);
      |     ^~~~~~
/home/alarm/kodi/xbmc/profiles/dialogs/GUIDialogProfileSettings.cpp:33:1: note: ‘assert’ is defined in header ‘<cassert>’; did you forget to ‘#include <cassert>’?
   32 | #include "utils/URIUtils.h"
  +++ |+#include <cassert>
   33 | #include "utils/Variant.h"
make[2]: *** [build/profiles/dialogs/CMakeFiles/profiles_dialogs.dir/build.make:76: build/profiles/dialogs/CMakeFiles/profiles_dialogs.dir/GUIDialogProfileSettings.cpp.o] Error 1
make[2]: Leaving directory '/home/alarm/kodi-build'
make[1]: *** [CMakeFiles/Makefile2:6761: build/profiles/dialogs/CMakeFiles/profiles_dialogs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by bkuhls** [comment]
https://github.com/xbmc/xbmc/pull/17213 should fix the build error

**Comment by DaVukovic** [comment]
#17213 is merged
