### ISSUE TITLE
NextPVR Client "Add-on couldn't be loaded. An unknown error has occured"

### ISSUE THREAD

**Issue by ksandrar** [xbmc/xbmc#17308]
### Describe the bug
Here is a clear and concise description of what the problem is: 
After a mid-January W10 update Kodi/NextPVR stopped recording files. The Kodi Events log indicates: "NextPVR PVR Client Server is unreachable." Preceded by multiple instances of "Video Library Scanner Failed to scan tvshow:"
[kodi log 2.txt](https://github.com/xbmc/xbmc/files/4143276/kodi.log.2.txt)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Individual program recordings should be stored in appropriate video folders and the list of vide recodring should expand and display the most recent recording. The video should launch when selected.

## Actual Behavior
Folders were created for scheduled recordings but no content/video file was created. 

## Possible Fix
I'm, sorry but I have no idea what the problem or fix is

### To Reproduce
I'm, sorry but I have no idea what the problem or fix is

### Debuglog
The debuglog can be found here:
within the attached full log the following appear to be relevenat:
2020-02-01 15:16:24.499 T:8556   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
2020-02-01 15:16:24.499 T:8556   ERROR: CCurlFile::Open failed with code 0 for http://127.0.0.1:8866/service?method=session.initiate&ver=1.0&device=xbmc:
2020-02-01 15:16:24.499 T:8556   ERROR: XFILE::CFileCache::Open - failed to open source <http://127.0.0.1:8866/service?method=session.initiate&ver=1.0&device=xbmc>
2020-02-01 15:16:24.506 T:8556   ERROR: ADDON: Dll NextPVR PVR Client - Client returned bad status (1) from Create and is not usable
2020-02-01 15:22:51.007 T:8556   ERROR: PVR::CPVRClients::UpdateAddons: Failed to create add-on NextPVR PVR Client, status = 1

### Screenshots 
Here are some links or screenshots to help explain the problem:
not avaible from this device

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The bug appeared in mid-January after a W10 update.

### Your Environment
Used Operating system:
[kodi log 2.txt](https://github.com/xbmc/xbmc/files/4143281/kodi.log.2.txt)

 - Operating system version/name: Windows 10 Pro Version 1903
 - Kodi version: 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Your log is not a debuglog and you have banned add-ons installed. Please provide a new clean debuglog withing the next 7 days or your issue will be closed.

Thanks in advance

**Comment by ksandrar** [comment]
[kodi.old.log](https://github.com/xbmc/xbmc/files/4144721/kodi.old.log)
