### ISSUE TITLE
Proxy without username and password doesnt work (here is a fix) 

### ISSUE THREAD

**Issue by stiray** [xbmc/xbmc#17336]
Http proxy doesnt work without aparent reason.

You are having a trivial to fix bug in filesystem/CurlFile.cpp[605] which probably brakes proxy functionality when no password is set.

`  
const std::string userpass =
      m_proxyuser + std::string(":") + m_proxypassword;

    if (!userpass.empty())
      g_curlInterface.easy_setopt(h, CURLOPT_PROXYUSERPWD, userpass.c_str());

`
userpass is NEVER empty due to ":" and i suspect it translates to http://:@proxy:8080 which is invalid. 

`
    const std::string userpass =
      m_proxyuser + std::string(":") + m_proxypassword;

    if ( ":" != userpass)
      g_curlInterface.easy_setopt(h, CURLOPT_PROXYUSERPWD, userpass.c_str());
`

**Comment by KarellenX** [comment]
Thanks for your comments.

Could you convert this into a PR so the developers can review?

**Comment by stiray** [comment]
Ok this is hell of a lot of work for one liner.

https://github.com/xbmc/xbmc/pull/17338

**Comment by phunkyfish** [comment]
Fixed in https://github.com/xbmc/xbmc/pull/17338 and 
https://github.com/xbmc/xbmc/pull/17698
