### ISSUE TITLE
Crash on seek

### ISSUE THREAD

**Issue by psonnosp** [xbmc/xbmc#17337]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using the keyboard to go back or forth in a movie Kodi crash to desktop. Sometimes it happen when navigating menues too but the provided log is from when trying to jump forward in an episode of a tv-show.
The nightly from 20191011 is the last version that works for me so guess something changed in the versions after that.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should jump in time according to whatever key I press.

## Actual Behavior

Kodi crash to desktop.

### To Reproduce

1. Start a TV-show or movie.
2. Use any of the left/right/up/down keys to skip in time a few times.
3. Kodi crashes to desktop.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/adesupoluq.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: 10
 - Kodi version: Log from nightly 20200203 x64 but every version after 20191011 is affected.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by psonnosp** [comment]
Just did a fresh install of the latest stable and the same thing still happens.

Close to dump Kodi all together, when you have to evaluate if its worth the risk to gamble on a rewind to catch the dialogue you missed and maybe crash Kodi, plus the audio glitch problem that also seems unsolvable, kind of takes the joy out of it :(

**Comment by fritsch** [comment]
You should keep kodi 17.x or older - that fits the hardware, you are using. No one has ever tested DXVA2 DirectX11 on a nvidia 9300 Geforce from 2008.
