### ISSUE TITLE
Play Using fails to send resource to receiver

### ISSUE THREAD

**Issue by yellowpattern** [xbmc/xbmc#17339]
### Describe the bug
Here is a clear and concise description of what the problem is:

Trying to use the "Play Using" feature of the Kodi UI to have a receiver play an MP3 file results in this entry in the kodi.log file:

20:37:39.124 T:4541531584   ERROR: CUPnPPlayer::PlayFile(musicdb://songs/971.mp3) failed to find a matching resource
20:37:39.125 T:4541531584   ERROR: UPNP: CUPnPPlayer::OpenFile - unable to open file musicdb://songs/971.mp3
20:37:39.125 T:4541531584   ERROR: Playlist Player: skipping unplayable item: 87, path [musicdb://songs/971.mp3]

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should send the resource to the receiver to play.

## Actual Behavior

An error is logged in Kodi.log and no music is played by the receiver.

### To Reproduce

1. Turn on receiver (Denon X3500H)
2. Start kodi
3. Browse to Music area of Kodi
4. Bring up the context menu
5. Select "Play Usng"
6. Select the Denon X3500H

### Debuglog

https://paste.kodi.tv/raw/ewoqewugir

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Darwin macbook.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
 - Kodi version: 18.5 Git:20191116-37f51f6e63

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by yellowpattern** [comment]
I've also tried 18.5 on Android and it also fails to work there.

**Comment by DaVukovic** [comment]
Getting the logs for Android is as easy as for any other platform using the Kodi logfile uploader add-on

>Kodi version: 17.6 Git:20171114-a9a7a20
 
Kodi 17.6 is not supported anymore and won't receive any fixes. Please update your Kodi to at least 18.5 on Windows and/or OSX and provide a new debuglog. Also please provide the full debuglog in a paste (paste.kodi.tv). Snippets are mostly useless and you should avoid posting it directly inside this ticket. A link is enough.

I'll mark this issue with "Ignored rules" for the time being. 

Thanks

**Comment by yellowpattern** [comment]
Updated.

**Comment by enen92** [comment]
Closing this as obsolete. It'd be nice if it can be checked on recent omega nighties, there were many changes regarding UPnP.
