### ISSUE TITLE
Problem accessing folder of SACD iso files on firestick

### ISSUE THREAD

**Issue by JonnyGators** [xbmc/xbmc#17350]
### Describe the bug
Here is a clear and concise description of what the problem is:

I am using kodi on a firestick.  I've upgraded to the latest stable version.  I installed the SACD add-on.  I have a windows share on my network with various folders of different media.  Under music, I added a path/folder of music content, which contains various SACD iso files.  When I go under music and try to view the folder, before it shows me the contents of the folder, it crashes out to the firestick menu.  

On a possibly related or unrelated note, I've noticed that when trying to listen to music, after about half an album, the app crashes out.  Before that point, if I try to take an action in kodi, it is frozen but still playing music.  I've not used kodi a whole lot for music up to this point, so I don't know if this is something new that started happening after adding the SACD iso folder.  

Here is a log file I created of trying to view the SACD iso folder and it crashing out - https://paste.kodi.tv/nubadogaqe

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Show me the contents of the SACD iso folder, and allow me to select and playback music

## Actual Behavior

Crashes out to firestick menu

## Possible Fix

don't know

### To Reproduce

1.  Under Music, add path to windows share / folder that contains my SACD ISO library
2. Try to view the contents of the folder
3. Crash

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/nubadogaqe

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP
firestick
 - Operating system version/name: 
 - Kodi version: 18.5

Edited by fritsch to indicated this is Android

**Comment by fritsch** [comment]
@AlwinEsch any idea or already fixed?

**Comment by JonnyGators** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/4189556/kodi.log)

Installed on my windows machine.  Setup same share path as on the firestick.  Get the same thing....crashes when trying to view the contents of the folder.  this log should be useful.  Please take a look.  Thanks.

**Comment by JonnyGators** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/4189582/kodi.log)

Created a test folder in my share, copied 1 iso to it.  I can browse and view the file.  Not sure what is causing kodi to crash when viewing the full folder.  Does it not like file names that windows allows, or something like that?  

When trying to play the iso I copied into the test folder, I get only buzzy noise.

I am able to playback the same SACD iso on the same PC/soundcard/receiver setup by using the SACD add in on foobar.  

Also, the sacd is stere/multichannel.  Foobar will show me 2 tracklistings, stereo and multichannel.  I only get 1 tracklisting in kodi, and I haven't found a setting to set it to stereo or multichannel.

**Comment by AlwinEsch** [comment]
I will soon see what can be done, our SACD version is unfortunately very different from the one on "foobar" and also noticed some limitations during testing.

I will eventually take over the entire route from "foobar".

**Comment by AlwinEsch** [comment]
@JonnyGators can you test how works on new addon about https://github.com/xbmc/audiodecoder.sacd.

The other vfs.sacd is obsolete now.

**Comment by AlwinEsch** [comment]
As there was come fixes related to sacd iso's on addon and Kodi can be this closed.

Related to fault about play of DVD iso's and SACD addon present need to wait for release of 19.4 Matrix
