### ISSUE TITLE
Improve scraping of multi-language movie libraries

### ISSUE THREAD

**Issue by mvglasow** [xbmc/xbmc#17354]
### Describe the bug
Here is a clear and concise description of what the problem is:

Some users of Kodi may have movie collections with movies in multiple languages. They know the movie by its original title and expect to find it when looking for that title. However, Kodi (when using the TheMovieDB scraper) translates the movie title into the UI language (at which it even does a remarkable job). For movies in a language different from the UI language, one has to look for the translated title, which may be very different from the original one. “Fantozzi” becomes “White Collar Blues”, “Wer früher stirbt, ist länger tot” becomes “Grave Decisions”, and “Pakėliui” becomes “When you wake up”.

Now I could create `.nfo` files for all the non-English movies in my collection, but this involves a lot of manual work for something that could be automated.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Deciding what language to display movie titles and descriptions in may be complex in itself. Some of the following criteria might help:
* Let the user select the languages they wish to receive movie titles and descriptions in. This will constrain movie titles and descriptions to these languages.
* From the selected languages, preference is as follows:
  1. Original language of the movie
  2. Language determined from the file name (if that is ambiguous, as the movie may have the same title in different languages, prefer “matching“ languages over the others)
  3. If possible, one of the languages available for the audio track and/or subtitles of the main movie (not all file formats may support this, but it might work for a `VIDEO_TS` directory from a DVD).
  4. UI language (can also be a fallback if there are multiple options without a clear “winner” in the previous steps)

Optionally, give the user a choice of having the description in the same language selected for the title or always use the UI language.

## Actual Behavior

All movie titles and descriptions are in the UI language (English in my case), regardless of the original language of the movie

## Possible Fix

Design change, as described above

### To Reproduce

1. Populate a media library with original versions of movies in various languages
2. Scan the media library
3. Examine movies in the library (titles, descriptions)

### Debuglog

The debuglog can be found here:
(This is a design issue, not something which needs debugging, hence I doubt a log is going to be useful here.)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC 2020.01-1
 - Kodi version: 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Thank you for your well written report. Unfortunately this is a Feature Request and not a bug report. (I know you could argue this is a bug from your point of view, but it is not) so this issue will be closed.

Could you please copy and paste your feature request on the forum. But before you do so, please take note of my comments below.

1. The current generation of XML scrapers are not receiving any new features.
2. Some of what you ask requires changes to Kodi core program and not the scraper which on the surface sounds simple, but will be quite complex and I doubt any volunteer developer will undertake this.
3. Kodi is not translating anything. The information comes from the scraper site and it is scraping the language **you** set in the scraper settings. 

Your workaround to achieve your request is simple. Move your non-English movies into their own Source folder and enable the setting **Keep Original Title** in the scraper settings.
