### ISSUE TITLE
PVR: no way to order channels in groups

### ISSUE THREAD

**Issue by bam80** [xbmc/xbmc#17364]
### Describe the bug

Channel manager can only show channels in 'All Channels' group, so no ordering possible for other groups.

## Expected Behavior

If opened from PVR TV, Channel manager should manage channels of the current group only. Also, Group manager should activate the current group on opening. 

## Actual Behavior

Channel manager always shows channels in 'All Channels' group only.

### Debuglog

The debuglog can be found here:
http://ix.io/274N

### Screenshots 
Have 'TV Group #3' current group, but 'All channels' group activated in Channel/Group managers. For Channel manager, there is no way to change it.
![image](https://user-images.githubusercontent.com/233979/74261914-03affc00-4d0d-11ea-833b-ecbec1eed765.png)
![image](https://user-images.githubusercontent.com/233979/74261930-090d4680-4d0d-11ea-9b01-f92a7ad12c79.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Kodi version: 19.0-ALPHA1 Git:20200117-01149380a2

#17167

@ksooo @phunkyfish

**Comment by ksooo** [comment]
This is actually a feature request, not a bug.

**Comment by bam80** [comment]
@ksooo Yes, probably. Forgive me for that)

**Comment by DaVukovic** [comment]
Feature requests have to be submitted at the forums at the specific subsection: 

https://forum.kodi.tv/forumdisplay.php?fid=9

closed

**Comment by bam80** [comment]
Hope it helps: https://forum.kodi.tv/showthread.php?tid=351673
