### ISSUE TITLE
Movie Scraper

### ISSUE THREAD

**Issue by therisod** [xbmc/xbmc#17361]
### Describe the bug
Here is a clear and concise description of what the problem is:

When scraping the movies information the scraper cannot find/download the information about several of the movies I have in my collection.
I did try using TMDB and Universal movie scraper but I'm getting the same results.
In a test directory I created some empty txt files I renamed them exactly as the files I couldn't download the information. I did try to save those files in the root serching directory or in some subdirectories. The result of all the above experiments has been successfull. Every time the file have been recognized and the information has been downloaded by the movie scraper. I also did try to paste and copy the complete filename of the original, non working, file in the test file just in case there were some hidden characters somewhere. Also in this case everything worked fine.

When copying the non working file in the test directory the non working file did not work. The scraper didn't manage to download the information about the movie.
I then changed the non working movie filename to a different working filename and, again, the scraper has not been able, at all, to download the movie information. 

Looks like the problem isn't the name of the file beiing scraped but the file itself.
If the file called xyz doesn't work if I rename the file zyx it still doesen't work.
If i create a dummy file called xyz or zyx doth files work.

Do you have any idea of why this is happening?
Are the scraper using only the name of the file or also some other information that might be responsible for the movie information download failure?

I have this behaviour when running KODI 18.5 on Ubuntu 18.04.4
When running KODI 18.3 on Windows 10 everything works fine
When running KODI 18.5 on Windows 10 everything works fine

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When scraping a movie with the title and year matching a movie in the TMDB database the movie should be recognized and the information downloaded in the library.

## Actual Behavior

Some files aren't recognized. 

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04.4
 - Kodi version: 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
>Do you have any idea of why this is happening?

No, unfortunately we do not have any idea. Because:

* you missed to provide a debuglog
* you missed to provide the names of the files you are going to scrape

Most likely those problems come up because
* the file-naming is wrong
* the movie information doesn't exist in the specific language the scraper is set to

And those problems should be solved at the forums as this isn't a support section. 

So please provide a debulog which exactly shows the scraping process, so we can see if it's a real bug or a support question. I'll mark this issue as "ignored rules" because you have ignored the template and didn't provide a logfile. I'll happily remove that label, if the logfile is provided and if it's a real bug.

**Comment by therisod** [comment]
Hi, 
reading blogs on the web I found out why I had those problems.
Under:
Settings->Media->Videos 
I had to uncheck: "Use video tags"

Thank you for your help,
       Stefano

P.S. Reading my problem description you can rule out the two possible errors root cause you suggested in your reply.
