### ISSUE TITLE
Is not possible hide context menus on video listitem when playcount/resumetime are overrided

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#17372]
### Describe
Here is a clear and concise description of what the problem is:

I'm working on implementing a two-way communication between kodi and netflix service to synchronize video progress like watched/resumetime.
after various difficulties, i take in consideration to implement the override of PlayCount and ResumeTime info of ListItems

then every time the a video list is loaded these two properties are set e.g.:
list_item.setInfo('video': {'playcount': 0})
list_item.setProperty('ResumeTime', 1500)
list_item.setProperty('TotalTime', 3000)

this works, but i have a problem with these context menus
because after override the properies above, become totally unusable, and i can not replace them, and i can not hide them, the user should not see them becacuse not works
![image](https://user-images.githubusercontent.com/3257156/74440718-d24f4180-4e6e-11ea-88f4-329578f4c0f2.png)
therefore i want to create them inside the addon by creating them manually
with a custom behaviour

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

possibility to hide these context menu  when the properties above are set

## Actual Behavior

is not possible hide these context menu when the properties above are set

## Possible Fix

I have already worked out a possible solution to hide menus when information is overwritten:

https://github.com/CastagnaIT/xbmc/commit/5394b88f5deda81d2fabc580194abb54ae674658

already tested and working,
but i don't know if that would be okay,
an opinion is welcome

### To Reproduce

1. Override info like above
2. Open context menu on a video item
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/jofejakovi.kodi
but it is not useful...

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Matrix latest build

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by L2501** [comment]
This was possible in the past, but was removed in Kodi 17.

**Comment by CastagnaIT** [comment]
if you mean the `replaceItems` which has been removed, i'm not interested in cutting out all the functional menus like Play, Play at, Information, etc...
but just hidden these two menus, because they are actually the only ones that are useless with the override

**Comment by DaVukovic** [comment]
Isn't this more a support question/feature request rather than a bug report?

**Comment by ksooo** [comment]
I see it more like we have to make the context menu items working, even if related list item values get overridden by add-ons.

This is imo a better solution compared to allowing add-ons to hide unwanted context menu items. Especially, if semantics of existing menu item matches what the add-on is trying to achieve.

Otherwise, we easily can end up with technically different but semantically identical menu items, basically all doing the same, each with (slightly) different label, each appearing on (slightly) different location within the context menu which would lead to a inconsistent UI.

**Comment by CastagnaIT** [comment]
the problem and the solutions i think are two and depends on the needs of VOD addon service (like Netflix):

-easy way: hidden these two menu. Because if they were really working, there is no python callback to have a chance to send a request to the (netflix or other) server to update the wathed status,
or perform other operations

-alternative: restore their functionality, but is needed to add the missing python callback, getting callbacks in python i don't see a very simple thing...

**Comment by CastagnaIT** [comment]
i opened a feature request
then i close the issue
