### ISSUE TITLE
Nvidia Sheild 2019 v9 Pie Problem

### ISSUE THREAD

**Issue by markoco** [xbmc/xbmc#17370]
### Describe the bug
Here is a clear and concise description of what the problem is:Tested 2 new 2019 versions of NVIDIA Shield Running Pie v9 And Kodi  v17.6 through 18.5 and the problem is playing video files over network share. Video will stop playing at different points in time and revert to the menu to play the video again, video will resume from where it was stopped. I also tested the SPMC fork 16.7 where the video plays just fine on the 2019 v9 pie 
I also tested Kodi18.5 on the 2017 v8 of Shield and it plays fine  no issues.

 Since it plays great using SPMC 16.7  on both the 2017 and 2019 version of shield running both v8 and v9 of android. Believe its a Issue with Kodi v 17.6 all the way through 18.5 and v9 Pie of android.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video should play without issues like tested on the 2017 NVIDIA Shield 

## Actual Behavior

The video will just stop like hitting the stop button at different points in time on any video played over my network shard folders

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You missed to provide a logfile. We can't do anything without it. 

Please provide a full debuglog within in the next 7 days. Otherwise this issue will be closed. 

Thanks in advance

**Comment by markoco** [comment]
the Debug Log can be found here https://paste.kodi.tv/yibovapihu

**Comment by da-anda** [comment]
would it be possible for you to test playback using a v19 nightly build to see if the issue still is present there? Alternatively, could you try running a 32bit build of 18.5 on Pie?

I remember having a similar issue a couple years back, but in my case playback just froze IIRC. The reason was some issue with 32bit integer vs 64bit integer conversion (or something like that) inside of KODI which lead to a stall when trying to read from a file larger than 2GB over a network share.
This is the PR that fixed the issue back then https://github.com/xbmc/xbmc/pull/3164
@peak3d could a similar issue be happening on Pie now?

**Comment by M2k80** [comment]
i see he uses smb connection. if i remember correct, there a some problems with smb/android/shield/kodi. 
@markoco do you used the shield internal smb client to mount your shares or did you use kodi´s smb client? you should not use kodi´s internal smb client and use instead the shield´s internal client

**Comment by markoco** [comment]
will try it as you suggested

 

Sent: Sunday, February 16, 2020 at 4:31 AM

**Comment by markoco** [comment]
I am using the smb client on kodi , I could not mount any network shares in the nightly build so i installed the 18.5 32 bite version and it the same issue. I borrow my friends 2017 version of shield and he has Pie on it also and his box runs perfect. as i have been reading the hardware is identical to the 2017 version.

**Comment by leo06** [comment]
Do you have installed es file explorer?

**Comment by markoco** [comment]
yes i have
 

Sent: Friday, February 28, 2020 at 4:39 AM

**Comment by leo06** [comment]
Uninstall it and check it again

**Comment by markoco** [comment]
is es file explorer cousing the problem ?

 

 
 

Sent: Friday, February 28, 2020 at 5:05 PM

**Comment by leo06** [comment]
Yes, if you want file manager try xplore

**Comment by markoco** [comment]
Ok i looked and i only have X-plore installed dont have the se exporer
 

Sent: Friday, February 28, 2020 at 5:09 PM
