### ISSUE TITLE
Scan to library function not recursive

### ISSUE THREAD

**Issue by Bob-I** [xbmc/xbmc#17371]
### Describe the bug
Here is a clear and concise description of what the problem is:

My folder structure is:
-Movies
  - individual movie folder
     - movie.mkv / movie.nfo

Navigating to movies and choosing "scan to library" results in no movies found. I have to go to the individual movie folder, then it works. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Scan to library should be recursive? 

## Actual Behavior

-

## Possible Fix

Make it recursive or provide an option to enable it. 

### To Reproduce

1. Go to your movies folder, choose scan to library. See result. 
2. Go to individual movie folder that contains mkv, see result
3.

### Debuglog

The debuglog can be found here:

Debuglog not necessary, but sure yet if wad or actually a bug. 

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I had an issue with Kodi and had to restore a backup. Now some movies are visible but hundreds are only visible by directly browsing the source. Scrapping does not fix the issue. Scan to library does fix it, but it would take weeks for hundreds of movies to scan individually. 

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

18.5
SHIELD

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Please ask your support question on the forum. There is no support here on Github.

Issue closed.
