### ISSUE TITLE
Add NFS 4 support in kodi?

### ISSUE THREAD

**Issue by montvid** [xbmc/xbmc#17387]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi  does not support NFS 4 so I can't connect to my share on mobile. I can access my share with NFS 3 fine but I would like to turn off NFS 3. I can access my share with Kodi via Debian NFS 4 mount and via file manager so the configuration is fine.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

nfs://server/share?version=4 does work.

## Actual Behavior

nfs://server/share?version=4 does not work on Android and Linux.

## Possible Fix

Update libnfs

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

My /etc/exports
> /mnt    *(fsid=0,ro,all_squash,async,no_subtree_check,insecure,anonuid=1000,anongid=1000)
/mnt/sda1 192.168.1.241(rw,all_squash,async,no_subtree_check,insecure,anonuid=1000,anongid=1000)
/mnt/sda1 192.168.1.0/24(ro,all_squash,async,no_subtree_check,insecure,anonuid=1000,anongid=1000)

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi 18.5 Git:20191116-37f51f6e63 Android
Kodi 18.5 compiled 20191209 flatpak Debian Linux

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Feature requests are done in the forum thanks

**Comment by montvid** [comment]
Well, it is not a feature support. Kodi already has NFS support via libnfs. Libnfs DOES support NFS 4 but Kodi does not. So it is a bug or I don't know the syntax for enabling NFS 4 on Kodi.

**Comment by a1rwulf** [comment]
Just because an external library supports a feature that is not used by a software, doesn't make it a bug automatically.

**Comment by montvid** [comment]
So you are saying that enabling NFS 4 when there already is NFS 3 and NFS 4 support in a library a feature? :) OK.

**Comment by a1rwulf** [comment]
We could debate this forever, it definitely does not qualify as a bug either unless it's considered a considerable security hole - at least that's my perception and I see @lrusak has the same opinion.

**Comment by lrusak** [comment]
Yea unfortunately even though libnfs now supports nfsv4 changes will have to be made to Kodi to support this. I would like to split out nfs into vfs.nfs first though

**Comment by montvid** [comment]
I see someone is working on vfs.nfs 4 https://github.com/notspiff/vfs.nfs Thanks for your support. :)
