### ISSUE TITLE
Raspberry pi won't show GUI if you start kodi via VNC

### ISSUE THREAD

**Issue by ReddotCleaner** [xbmc/xbmc#17396]
### Describe the bug

Here is a clear and concise description of what the problem is:
This is not a issue. I am here beacuse I encounter a problem while a try to start kodi via vnc,as the title said, Gui wont show up on vnc, but, actually kodi is running while you type kodi in terminal. Here is thread for the reason and solution. -https://forum.kodi.tv/showthread.php?tid=327203
Hope this can help.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix

Here is thread for the reason and solution. -https://forum.kodi.tv/showthread.php?tid=327203

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:Raspberry-Pi
 - Kodi version:18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Please use the forums for such things
