### ISSUE TITLE
Kodi crash when scanning due to infinite recursion in FindNFO

### ISSUE THREAD

**Issue by solarus** [xbmc/xbmc#17391]
### Describe the bug
I've recently started getting crashes when scanning in my media library. The problem seems to be an infinite recursion in CVideoTagLoaderNFO::FindNFO which is called over and over with same arguments. The issue is triggered by having rar files in rar files in a specific way, exact way to reproduce can be found below. The stack trace for the crash looks like this:

```
Thread 1 (Thread 0x7f3532f3a700 (LWP 108442)):
#0  0x00007f3565d22ffb in __vfscanf_internal () from /usr/lib/libc.so.6
#1  0x00007f3565d228e2 in __isoc99_sscanf () from /usr/lib/libc.so.6
#2  0x000055b83dac7ffd in CURL::Decode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#3  0x000055b83dacb4a6 in CURL::Parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#4  0x000055b83d62296b in URIUtils::IsInRAR(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#5  0x000055b83d3c8245 in CVideoTagLoaderNFO::FindNFO[abi:cxx11](CFileItem const&, bool) const ()
#6  0x000055b83d3c8500 in CVideoTagLoaderNFO::FindNFO[abi:cxx11](CFileItem const&, bool) const ()
#7  0x000055b83d3c8500 in CVideoTagLoaderNFO::FindNFO[abi:cxx11](CFileItem const&, bool) const ()
... # repeats a couple thousand times
#4253 0x000055b83d3c8500 in CVideoTagLoaderNFO::FindNFO[abi:cxx11](CFileItem const&, bool) const ()
#4254 0x000055b83d3c8500 in CVideoTagLoaderNFO::FindNFO[abi:cxx11](CFileItem const&, bool) const ()
#4255 0x000055b83d3c918d in CVideoTagLoaderNFO::CVideoTagLoaderNFO(CFileItem const&, std::shared_ptr<ADDON::CScraper>, bool) ()
#4256 0x000055b83d3c1389 in VIDEO::CVideoInfoTagLoaderFactory::CreateLoader(CFileItem const&, std::shared_ptr<ADDON::CScraper>, bool, bool) ()
#4257 0x000055b83d4c2192 in VIDEO::CVideoInfoScanner::OnProcessSeriesFolder(std::vector<VIDEO::EPISODE, std::allocator<VIDEO::EPISODE> >&, std::shared_ptr<ADDON::CScraper> const&, bool, CVideoInfoTag const&, CGUIDialogProgress*) ()
#4258 0x000055b83d4c3e46 in VIDEO::CVideoInfoScanner::RetrieveInfoForEpisodes(CFileItem*, long, std::shared_ptr<ADDON::CScraper> const&, bool, CGUIDialogProgress*) ()
#4259 0x000055b83d4c43f6 in VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(CFileItem*, bool, std::shared_ptr<ADDON::CScraper>&, bool, CScraperUrl*, bool, CGUIDialogProgress*) ()
#4260 0x000055b83d4c55f7 in VIDEO::CVideoInfoScanner::RetrieveVideoInfo(CFileItemList&, bool, CONTENT_TYPE, bool, CScraperUrl*, bool, CGUIDialogProgress*) ()
#4261 0x000055b83d4c67e8 in VIDEO::CVideoInfoScanner::DoScan(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#4262 0x000055b83d4bb114 in VIDEO::CVideoInfoScanner::Process() ()
#4263 0x000055b83d4bb71f in VIDEO::CVideoInfoScanner::Start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
#4264 0x000055b83d3d4cd6 in CVideoLibraryScanningJob::Work(CVideoDatabase&) ()
#4265 0x000055b83d3d04b5 in CVideoLibraryJob::DoWork() ()
#4266 0x000055b83d5a64e1 in CJobWorker::Process() ()
#4267 0x000055b83d644665 in CThread::Action() ()
#4268 0x000055b83d64610d in CThread::staticThread(void*) ()
#4269 0x00007f35674d846f in start_thread () from /usr/lib/libpthread.so.0
#4270 0x00007f3565dc93d3 in clone () from /usr/lib/libc.so.6
```
## Expected Behavior
Scanning should proceed without crashing

## Actual Behavior
Kodi crashes

## Possible Fix
I believe the bug is here (in FindNFO method):

https://github.com/xbmc/xbmc/blob/353d61085acd8af33394051d207a5eabdd2fd657/xbmc/video/tags/VideoTagLoaderNFO.cpp#L98

Changing `m_item` to `item` and the loop does not happen and scanning seems to work as intended again.

### To Reproduce

1. First create a fake tv show file
```bash
mkdir -p /tmp/foo/test
cd /tmp/foo/test
touch s01e01.idx s01e01.sub
rar a s01e01.rar s01e01.sub
rar a subs.rar s01e01.idx s01e01.rar
rm s01e01.*
```
2. The add /tmp/foo as a video medio source in kodi
3. Initiate a scan of /tmp/foo/test (e.g. by clicking "scan for new content" on the test directory
4. Kodi will crash

### Debuglog
The debuglog can be found here:
* http://sprunge.us/c3Mus3

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux laptop 5.5.5-arch1-1 #1 SMP PREEMPT Thu, 20 Feb 2020 18:23:09 +0000 x86_64 GNU/Linux
 - Kodi version: 18.5
 - Using vfs.libarchive-1.0.6 and vfs.rar-2.0.8 plugins

**Comment by fuzzard** [comment]
There is a PR that sounds like it fixes this.
https://github.com/xbmc/xbmc/pull/17347

If you can build and test, might be good just for verification

**Comment by solarus** [comment]
Yep that seems exactly what I found also. I have a running Kodi version now with that exact change (on Leia branch though, the PR seems to be on the new version) and it is currently managing to scan my library without issues at least. Further, all tests seems to be running fine (except for TestWebServer.CanHeadFile but that failed without the change also for me).

**Comment by KarellenX** [comment]
Also reported on the forum and confirmed by spiff...

https://forum.kodi.tv/showthread.php?tid=351748

**Comment by DaVukovic** [comment]
@solarus 

The specific PR has been merged. Could you please confirm that it fixes your issue?

**Comment by Leinad4Mind** [comment]
I've an issue with libarchive probably related with this:

https://github.com/xbmc/vfs.libarchive/issues/41

But it was with zip and 7z files. With .rar all ok.
