### ISSUE TITLE
Addon repo (Leia) for windows contains wrong pvr.zattoo version

### ISSUE THREAD

**Issue by rbuehlma** [xbmc/xbmc#17394]
### Describe the bug
Here is a clear and concise description of what the problem is:

The version 19.*.* of pvr.zattoo got publish in the Leia repo for windows. This version is meant for Matrix while the 18.*.* versions are meant for Leia.

http://mirrors.kodi.tv/addons/leia/pvr.zattoo+windows-x86_64/

I already created an issue in pvr.zattoo but the problem does not seem to be there since other platforms have the correct version for Leia.
https://github.com/rbuehlma/pvr.zattoo/issues/69

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

http://mirrors.kodi.tv/addons/leia/pvr.zattoo+windows-x86_64/ should contain a 18.*.* version of the addon.

## Actual Behavior

http://mirrors.kodi.tv/addons/leia/pvr.zattoo+windows-x86_64/ contains a version meant for Matrix

### Debuglog

The debuglog can be found here:
Since this is a build time issue, there is no debug log.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
while i don't have an idea why it happened, i've done some cleaning up on our end.
the incorrect versions should be done once it's synced across the mirrors.

**Comment by rbuehlma** [comment]
Thanks for the help. I will see what will happen on the next update. Now it looks fine.
