### ISSUE TITLE
Bug: YouTube add-on not working...

### ISSUE THREAD

**Issue by xmha97** [xbmc/xbmc#17392]
Hello,
YouTube add-on not working...
![Screenshot_20200223-022254](https://user-images.githubusercontent.com/23485114/75100628-1b6a6880-55c8-11ea-88ff-d088d0e6cf9d.png)

**Comment by fuzzard** [comment]
Issues here are for bugs in Kodi, not the add-ons.
You are better off to and look at the support thread for the add-on at the Kodi forums.

In particular, also look at the following link about setting up google API personal keys.
https://github.com/jdf76/plugin.video.youtube/wiki/Personal-API-Keys
