### ISSUE TITLE
xbmc.getInfoLabel('VideoPlayer.Season') and xbmc.getInfoLabel('VideoPlayer.Episode') Not Integers for Specials

### ISSUE THREAD

**Issue by lorkadiscovery** [xbmc/xbmc#17402]
### Describe the bug
Here is a clear and concise description of what the problem is:

https://github.com/trakt/script.trakt/issues/490

As raised in the issue above. The kodi video player reports a special episode as ES1 instead of S0E1

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

xbmc.getInfoLabel('VideoPlayer.Episode') and xbmc.getInfoLabel('VideoPlayer.Season') should always return an int not a string as anyone who codes to grab these values expects ints to be returned.

## Actual Behavior

If the infolabels of an item in an plugin are set to {'season': 0, 'episode': 1} then Kodi returns the season as None and the episode as S1

## Possible Fix

Set xbmc.getInfoLabel('VideoPlayer.Season') to return 0 when the infolabel for the listitem is 0
and set xbmc.getInfoLabel('VideoPlayer.Episode') to return the int of the episode not add S to highlight the episode as a special.

### To Reproduce

1. Setup the trakt script from the Kodi repo and watch any file from a plugin where the season is set to 0 on its infolabel.

### Your Environment
Used Operating system:

 - [ Yes ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ]  OSX
 - [ ] Raspberry-Pi
 - [ Yes ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Martix 19 Any Nightly 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
yup, makes sense to me.

https://github.com/xbmc/xbmc/pull/17408

**Comment by lorkadiscovery** [comment]
Thank you @ronie I don't know if you want me to close now so please close if you feel this requires no further input from anyone. Thanks again.

**Comment by ronie** [comment]
no worries, the ticket will be closed automatically when the PR gets merged.
