### ISSUE TITLE
Issues with HDR playback on Android with Huawei MediaPad M5 (CMR-W09)

### ISSUE THREAD

**Issue by fonic** [xbmc/xbmc#17401]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have trouble playing back HDR content with Kodi on my Android-based _Huawei MediaPad M5 (CMR-W09)_. HDR videos play fine regarding fluidity and sound, but colors are completely off. See screenshots below.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect HDR videos to play with correct colors or at least with _watchable_ colors.

## Actual Behavior

HDR videos play fine regarding fluidity and sound, but colors are completely off. See screenshots below.

### To Reproduce

Use Kodi on Huawei MediaPad M5 to play HDR content, e.g. [Dolby Leviathan](https://www.demo-world.eu/download-2d-trailers-uhd/?file=dolby_leviathan_uhd-DWEU.mkv&pic=dolby_leviathan.jpg) from [this page](https://www.demo-world.eu/2d-demo-trailers-uhd/).

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/4250210/kodi.log)

Possible hint (just a smart guess):
```2020-02-25 14:21:48.380 T:22976   DEBUG: ffmpeg[74EA5BB4F0]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.```

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Screenshot_20200225_140122_org xbmc kodi](https://user-images.githubusercontent.com/14027079/75251802-a2435f00-57db-11ea-8f31-2b29fc67c136.jpg)
![Screenshot_20200225_140202_org xbmc kodi](https://user-images.githubusercontent.com/14027079/75252298-b2a80980-57dc-11ea-8001-19f4f76868c5.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I'd really like this to be resolved, I'll be happy to provide whatever further information or testing might be required.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Huawei MediaPad M5 (CMR-W09)
Build 9.1.0.332 (C432E5R1P3)
EMUI 9.1.0
Android 9
CPU Hisilicon Kirin 960s
Kernel 4.9.148

 - Kodi version:
18.5 Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
HDR plays correctly on hardware that supports it well, i.e. : Shield 2019

This issue seems a duplicate https://github.com/xbmc/xbmc/issues/20695

**Comment by fonic** [comment]
I don't see how this is a duplicate of #20695. The colors are not just washed out or mapped wrongly, HDR videos are downright unwatchable (stutter, color artifacts like shown in the screenshots I provided).

**Comment by thexai** [comment]
Huawei MediaPad M5 (your hardware) even supports HDR?

I mean with other player i.e Netflix App your device plays 4K HDR perfectly and is only Kodi issues?

**Comment by fonic** [comment]
That I don't know. Don't have anything besides Kodi for testing.

I'd say it probably doesn't. However, I wonder why Kodi tries to run such content through hardware decoding without checking whether HDR is actually supported (and falling back to software decoding if it isn't).

**Comment by thexai** [comment]
> I wonder why Kodi tries to run HDR content through hardware decoding without checking whether HDR is actually supported or not (falling back to software decoding if it isn't).

These devices usually do not have enough power to decode H.265 4K by software (not even 8bit SDR), that is to say that the only option is that they have the HW support anyway.

**Comment by fonic** [comment]
That is certainly the case for 4k, but there is enough power to decode 1080p HDR in software.

**Comment by thexai** [comment]
> but there is enough power to decode 1080p HDR in software.

I don't know because I don't have this device.

You can test it by disabling HW acceleration from Settings / Player and test 1080p HDR10 video.

The pixelation problems will probably disappear but it will still be seen with the colors off.

I think there may be some unresolved issue regarding HDR to SDR tonemapping on Android on systems that don't do it by HW.

It reopens for this reason, although I doubt that anything can be done for this particular device.
