### ISSUE TITLE
Add support for jetson nano decoder/encoder via jetson-ffmpeg

### ISSUE THREAD

**Issue by GavinDarkglider** [xbmc/xbmc#17400]
## Roadmap or todo item
**Detailed Description**

Currently on the jetson-nano board, the hwdecoder isnt used, because it uses a mixture of omx/v4l/gstreamer calls to be used. Recently someone started a project called jetson-ffmpeg which is a wrapper library for ffmpeg to interact with the decoder/encoder, and works really well for moonlight. It would be nice to see more video players support these on this board, since the same chip is the basis of the Nintendo Switch.

### Context

On my nintendo switch.... short of missing wedevine for aarch64, it is probably my favourite kodi streaming device. It would be nice for me a developer for the linux stuff in the nintendo switch community to see more software opportunities for my userbase. Also Kodi makes a really nice interface for a hand held tablet with game controllers.

Read Above.

### Possible Implementation

https://github.com/jocover/jetson-ffmpeg
Use the ffmpeg_nvmpi decoders supplied by this lib. They work for moonlight-qt really nice, and ffplay works decently enough.

### Additional context, screenshots or links
Here are some relevant links or screenshots

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by GavinDarkglider** [comment]
no

**Comment by lrusak** [comment]
Feature requests are done via the forum (but I can tell you right now it won't happen unless the code makes it into upstream ffmpeg).
