### ISSUE TITLE
some smi subtitles not appear

### ISSUE THREAD

**Issue by DevSejin** [xbmc/xbmc#17418]
### Describe the bug

===perfectly work====
```<SYNC Start=1694><P Class=KOKRCC>subtitle text</P></SYNC>```

===but this type not work===
```<SYNC Start="1694"><P Class="KOKRCC">subtitle text</P></SYNC>```

i think parameter with "quotes" is causing fail.
some subtitle makers are using "this" for compatibility.
i can remove that every subtitles but it is very tired.

Can you update both type to work?

## Expected Behavior

display subtitles 

## Actual Behavior

some subtitles(without parameter qoutes smi file) are display, 
but some subtitles(with parameter qoutes smi file) are not display.

ex) plex and plex official app and plex web player can play both type subtitles well

### To Reproduce

1. [subtitles.zip](https://github.com/xbmc/xbmc/files/4268420/subtitles.zip)
2. download and unarchive subtitles, and play working.smi/not working.smi with any videos
3.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/4268472/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: windows10 19h2, android with bluestacks, libre-elec

 - Kodi version: 18.5 Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by phunkyfish** [comment]
Closed by: https://github.com/xbmc/xbmc/pull/17749
