### ISSUE TITLE
Third-party binary addons cannot be loaded on Notarized macOS Kodi

### ISSUE THREAD

**Issue by djp952** [xbmc/xbmc#17411]
After implementation of PR [17178](https://github.com/xbmc/xbmc/pull/17178), third-party binary addons (Visualizations, PVR Clients, etc.) cannot be loaded on macOS.

### Describe the bug
Here is a clear and concise description of what the problem is:

Now that the formal Kodi macOS packages have been Notarized, binary addons that are not signed with the Kodi certificate cannot be loaded.  While the premise is understood and reasonable, there needs to be a path forward for these community contributions to the Kodi platform.

I am by no means an Apple ecosystem expert (very far from it, in fact), but it does appear that there are ways to allow this, for example by selecting the "Disable Library Validation" option? Kodi also already has the "Unknown Sources" setting, is there any possibility to allow the end user to control this somehow?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

My expectation is that Kodi would have provided a path forward for third party binary addons prior to implementing this.

If there is no way to allow unsigned third-party addons to load, perhaps there is a way to allow ad-hoc signed ones to load (I tried this, just a different error occurs).  If a formal Apple Developer ID based signature could be made to work I suppose that's an option, but I fear most Kodi contributors would not be willing to absorb the cost associated with that.

## Actual Behavior

Kodi fails to load unsigned or self-signed "ad-hoc" binary addons.

## Possible Fix

Don't know enough about the Apple ecosystem to suggest anything here.  Took me quite a while just to figure out how to ad-hoc sign a .dylib with an existing private key on this platform.

### To Reproduce

1. Install Kodi 18 "Leia" formal .DMG created on or after Feb. 16, 2020.
2. Attempt to install or enable a third party binary addon that isn't signed with Kodi's certificate.

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/tiwudiwamo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:
N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:

Kodi version: 18.5 "Leia"
OS: macOS "Catalina" 15.10.3

**Comment by DaVukovic** [comment]
Interesting. That's the first bug report I see where the PR which might introduce this bug is not even merged yet. ;)

**Comment by fuzzard** [comment]
@DaVukovic the release files have been manually notarized already, hence the issue.

Working with Kambala at the moment to implement a working solution

**Comment by fuzzard** [comment]
@djp952 If you have some time, could you give the following dmg a try. Its all codesigned and notarized, and i was able to run your addon downloaded from your repo. Just want to make sure it works for someone else

https://drive.google.com/open?id=1DzjTX0aJKvbiF380VEGGAkFr2NFbm19A

**Comment by djp952** [comment]
Absolutely, can do it this evening.  Access request sent via G Drive.

**Comment by fuzzard** [comment]
cheers. Have given access, thought i had it set to allow all, but kodi org had me tricked, haha

**Comment by djp952** [comment]
No worries.  Verdict = perfection! Works flawlessly for me!

**Comment by fuzzard** [comment]
Cheers. Give us some time to clean it up and renotarize the existing downloads

**Comment by djp952** [comment]
I know it's a pretty small number in the grand scheme of things, but I can vouch for about 90 macOS Kodi users by saying **THANK YOU**.  I am extraordinarily impressed that you guys were able to work out a solution so quickly.  Please let me know if there is anything else I can help test.

**Comment by fuzzard** [comment]
an 18.6 release is imminent. Its been signed and notarized using the new method. You're addon doesnt load (assume version bumps and what not in a release build "dependency on kodi.binary.global.main could not be satisfied"), so when it comes out and you rebuild, give it a try and let us know if it works.

**Comment by djp952** [comment]
Will do!  I can't thank you guys enough for making this work.  macOS wizards :)

**Comment by djp952** [comment]
Downloaded and installed 18.6 release from mirrors.kodi.tv today, no issues noted loading addon, worked dandy.  Looks good to me!  Do you want me to go ahead and close this?

**Comment by phunkyfish** [comment]
Yup 😉
