### ISSUE TITLE
src/libavformat/hlsenc.c:258:29: warning: logical ‘or’ of collectively exhaustive tests is always true [-Wlogical-op]

### ISSUE THREAD

**Issue by dcb314** [xbmc/xbmc#17424]
Source code is

   if ((*(pos - 1) != '/') || (*(pos - 1) != '\\')) {

**Comment by dcb314** [comment]
I believe the automated bot sent a message in error.

**Comment by fuzzard** [comment]
As stated in other issue you raised, this warning is located i upstream dependency (ffmpeg), so if you wish to support, you are better to raise the issue there.

https://www.ffmpeg.org/bugreports.html
