### ISSUE TITLE
src/libavformat/mpegtsenc.c:1646:35: warning: logical ‘and’ of mutually exclusive tests is always false [-Wlogical-op]

### ISSUE THREAD

**Issue by dcb314** [xbmc/xbmc#17423]
Source code is

       if ((state & 0x7e) < 2*16 && (state & 0x7e) >= 2*24)
            extradd = 0;

**Comment by dcb314** [comment]
I believe the automated bot sent a message in error.

**Comment by fuzzard** [comment]
As stated in other issue you raised, this warning is located i upstream dependency (ffmpeg), so if you wish to support, you are better to raise the issue there.

https://www.ffmpeg.org/bugreports.html
