### ISSUE TITLE
Kodi crashes randomly overnight

### ISSUE THREAD

**Issue by mathieugouin** [xbmc/xbmc#17420]
### Describe the bug
Here is a clear and concise description of what the problem is:

In reference to the following thread:
https://forum.libreelec.tv/thread/21384-kodi-crash-randomly-overnight/

I have a raspberry pi 3, running LibreELEC 9.2.0 with Kodi 18.5.

Almost every night, kodi crashes.  (Refer to crash logs in the forum thread, I can include more if required)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would expect Kodi to not crash, and keep running for multiple days (at least).

## Actual Behavior

Kodi crashes when the system is idle, eg: nobody watching TV, the TV is OFF, but the raspberry pi system is still running.

## Possible Fix

From my limited investigation, it seems a string overflow assertion.  (refer to the crash dump)

### To Reproduce

The following steps are based on my setup, not all steps might be required...
1. Get a Raspberry Pi 3B
2. Install LibreELEC 9.2.0
3. Install tvheadend
4. Configure tvheadend (ATSC receiver, recording saved to locally attached USB external drive...)
5. Watch some recorded TV shows in the evening
6. Power off TV
7. Next day, check if Kodi restarted (as confirmed by the selection changed from the last selected menu, or by the Kodi Info uptime, or by the crash dump in : /storage/.kodi/temp)
8. Repeat to step 5 if Kodi did not crash.

Sorry, it looks funny, but it is really what is causing the crash.  I have default skin and no banned addons.

### Debuglog

The debuglog can be found here:

DMESG: http://ix.io/2c68

kodi.log: http://ix.io/2c69

kodi.old.log: https://gist.github.com/mathieugouin/9f75613841e7456a4501b27db6d4c428

kodi_crashlog_20200218083716.log: https://gist.github.com/mathieugouin/3a1472f7b36665e6f12609bcf7403441

### Screenshots 
Here are some links or screenshots to help explain the problem:

I analyzed the CPU, RAM, & Temperature of the system overnight.  Here is the zoom of when the crash happens.  Notice the jump in the %iowait line.  Could this be a cause?
https://imgur.com/lpzkCjT

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

It affects the system stability, and robustness.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 9.2.0
 - Kodi version: 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
@MilhouseVH or @popcornmix would you have a look please

**Comment by HeresJonny** [comment]
This happened to me with a Windows installation as well (Kodi froze). 2 things to try:

1. Check your Power Save settings, especially the Shutdown function. If anything is set there, turn Power Save off and see if the problem persists.
2. TV add-ons have their own power setting. If the above does not solve your problem, disable TV Headone temporarily. If that is the culprit, check the power save settings.

**Comment by mathieugouin** [comment]
Thanks for the reply.  Any idea how does this translate on raspberry pi?

I'm a bit confused: do you mean power saving settings are set "per-addon" ?

**Comment by phunkyfish** [comment]
If you disable TVheadend do you still get a crash?

**Comment by mathieugouin** [comment]
Thanks for the suggestion.  However, disabling TVheadend for a long period of time is going to be challenging, as we rely on it heavily here...

I was able to disable it for the night and did not get a crash.  BUT, I also disabled wifi power saving on the PI, as suggested by @HeresJonny (refer to: https://forum.libreelec.tv/thread/294-pi-3-wlan-power-save-enable-by-default/?postID=7141#post7141).

I will try to find appropriate down time to disable it again.  I will keep you updated.

Thanks again!

**Comment by phunkyfish** [comment]
Once you can isolate the thing that is causing the crash it will make fixing it much easier ;)

**Comment by HeresJonny** [comment]
I was referring to Kodi's internal Power Save settings, but hey... if it works for you...

**Comment by mathieugouin** [comment]
I just confirmed that all KODI internal Power Save settings are set to OFF.

**Comment by mathieugouin** [comment]
@phunkyfish, just to be sure, do you mean disabling the tvheadend service addon (provided by LibreElec official addon repository) OR the tvheadend client addon (https://kodi.wiki/view/Add-on:Tvheadend_HTSP_Client) ?

Also, I had other nightly crashes with Wifi power saving disabled, so apparently, this was not related.

**Comment by phunkyfish** [comment]
Start with both. Then if there are no crashes try the service. If still no crashes try the PVR addon.

**Comment by DaVukovic** [comment]
Any news on this?

**Comment by mathieugouin** [comment]
Sorry for the delay...

The problem with this issue is because is does not happen every night, so disabling both addons for x amount of time to see if the crash still happens is close to unfeasible.  Disabling addons means missing on-going recordings.  My approach to overcome that was to only disable the TVH client addon, therefore keeping TVH server running in the background to still record shows.

I tried it a few nights, but for sure this is not enough.  I have not been diligent about disabling the addon before closing my TV at night.

However, I got a slight improvement in frequency of occurrence of the crashes.  It went from almost every day to once every 4-5 days.  I don't know if it's a pure coincidence, but I disabled the option "Display a notification on timer updates".  Refer to image: https://imgur.com/RSv5zme  (in this image the option is turned ON).

**Comment by w3tech** [comment]
DISCLAIMER: I am a newbie and may not know anything. My previous dev experience comes from web dev, and I am teaching myself embedded Linux.

I learned about this issue from this forum thread on LibreELEC's website.

[https://forum.libreelec.tv/thread/21384-kodi-crash-randomly-overnight/](url)

I posted in reply there, and it is awaiting approval.

So, I cloned Kodi, and simply tested this one file [https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/guiinfo/GUIInfoLabel.cpp](url)

The actual path in source is:

`xbmc/xbmc/guilib/guiinfo/GUIInfoLabel.cpp`

Here is what happens when I run:

`gcc GUIInfoLabel.cpp -lstdc++`

[https://imgur.com/gluFQSU](https://imgur.com/gluFQSU)

As you can see the path for the `GUIInfoLabel.h` file is not the same as its location. It is looking for subfolders `guilib/guiinfo/`, but `GUIInfoLabel.h` is already inside the `cwd`.

Using nano to change the path of the `GUIInfoLabel.h`, I find the next file that it cannot locate is `FileItem.h`, and this is in the source directory root. Using find to track down the rest of the files proves it is more than just a couple incorrect paths.

`find /src/xbmc/ -name FileItem.h`

If you move this file it continues to prove an issue with other includes.

**Comment by w3tech** [comment]
And so even though I can fix this now after playing around, I do not know if that is where they really want all these includes. And I have not tried compiling all of Kodi with the corrections. I suspect those files were moved to accessible elsewhere? I have read briefly Kodi uses special protocols that can affect paths, but I am not entirely sure if any of that pertains to this issue.

**Comment by fuzzard** [comment]
It's definitely not what you are looking at. Source path, and all headers are relative to XBMC/ so they are correct

**Comment by w3tech** [comment]
Okay. I thought maybe that was the answer I would get.

**Comment by w3tech** [comment]
The [original posting of this issue](https://forum.libreelec.tv/thread/21384-kodi-crash-randomly-overnight/), the post author stated he noticed that the Get()) method is causing a too big string in [GUIInfoLabel.cpp](https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/guiinfo/GUIInfoLabel.cpp). What do you think of that possibility?

**Comment by mathieugouin** [comment]
Ok, so I have found something interesting regarding this issue.

When we are done watching TV, I normally let Kodi on the TV main screen, refer to image: https://imgur.com/8SjCeGF 

This is not my Kodi screen shot, but it is almost identical.  In these conditions, the crash would normally happen every few days.

Recently, I noticed that if instead of leaving Kodi in the TV home screen for the night, I stay in one of the Recordings subfolder sub-menu, no crash would happen.  At least I never encountered one since I'm doing that.

Could it be related to the TV home screen?  I know that this screen is fairly dynamic... It show the next recording, the recent channels programs airing, etc...

**Comment by mathieugouin** [comment]
I confirm still no crash when staying in the Recordings subfolder sub-menu.

**Comment by enen92** [comment]
@mathieugouin might be a long shot but in your stacktrace you have this:

```
#2  0x74e618bc in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
#3  0x00850b38 in XBMCAddon::xbmc::sleep(long) ()
#4  0x0085cd38 in ?? ()
#5  0x76bfe1c0 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#6  0x6f039840 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

This means some python script (probably a service) is running at the time of the crash. Looking at your debug log the only addon that is likely to be a service is weather.yahoo. Weather info is only shown in the main screen (and not in list views) and might explain why the crash only happens in the main window.

Can you try disabling the weather addon (maybe the weather functionality completely) and leave your system on the home/tv window overnight?

**Comment by mathieugouin** [comment]
Before finding my "temporary" fix, I tried disabling the weather addon with no success... but thanks anyways!

I want to report still no crash by staying in the Recordings subfolder sub-menu.

**Comment by ccope** [comment]
Can you check if you have any screensavers enabled? I think I encountered similar issues myself until I disabled the picture slideshow screensaver, which is a python addon.

**Comment by mathieugouin** [comment]
@ccope I confirm, I have no screensaver installed.  Thanks!

**Comment by mathieugouin** [comment]
Still no crash by staying in the recordings submenu.  My last crash was 2020-03-26.  So this is quite concluding.

Is there anything I can do to help see what is the issue with the TV main screen?

**Comment by DoughMucker** [comment]
I've had this issue for quite some time now. I have just learned to live with it by not having the TV category selected on Kodi's home screen (like your workaround of leaving the recordings screen displayed). It's not Pi specific. I had it on my Pi2s and also have it on my Odroid N2s.

Another N2 user has the same issue. There are other posts out there showing others with the issue too.
https://discourse.coreelec.org/t/tvh-client-crashing/11400

I first saw the issue on a Milhouse testbuild years ago:
https://forum.kodi.tv/showthread.php?pid=2645223#pid2645223

**Comment by J4nsen** [comment]
Hi,
I also have these random crashes over night. They always happen at this function: `#0  0x004c65a8 in PVR::CGUIEPGGridContainer::HandleChannels(bool, unsigned int, std::vector<CDirtyRegion, std::allocator<CDirtyRegion> >&) ()`

I will test if staying in the recordings menu also works for me.

Here is the full log file: http://ix.io/2NBp

**Comment by lrusak** [comment]
Please test with Kodi master (19.0 RC1) as this has likely been fixed. Kodi 18.x is unlikely to receive any further updates.

We can reopen if it's still an issue on master.

**Comment by DoughMucker** [comment]
I've been testing 19.0 RC1 for about a week without a crash.
