### ISSUE TITLE
Two monitors with different ratios, video not centered

### ISSUE THREAD

**Issue by onlymash** [xbmc/xbmc#17422]
OS: ArchLinux
DEVICE: Ryzen 3550H Laptop
Kodi version: 18.5

The screen ratio of my laptop is 16:10 (2560 * 1600). I connected an external 16:9(2560*1440) monitor, and the video on the external monitor is not centered(shifted downward).

[screenshot/photo](https://user-images.githubusercontent.com/5838634/75618786-05ebd480-5bae-11ea-9920-a08961edfb9d.jpg)

**Comment by DaVukovic** [comment]
Please use the forums for such kind of support-questions. Thanks
