### ISSUE TITLE
Error with versioncheck in the latest Kodi 19 win64

### ISSUE THREAD

**Issue by Essam311** [xbmc/xbmc#17429]
### Describe the bug
Here is a clear and concise description of what the problem is:

After starting the latest nightly for Kodi 19 win64 "KodiSetup-20200302-bbe9b0f9-master-x64.exe"  for the first time I get this error message (I get it only the first time I start Kodi).

<img width="545" alt="222" src="https://user-images.githubusercontent.com/59211054/75763989-dff93800-5d45-11ea-99a7-6a1f2484c424.png">

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Not to get this error message.

## Actual Behavior

Getting the error message.

## Possible Fix

Modify "addon.xml" in 

C:\Program Files\Kodi\addons\service.xbmc.versioncheck

to

`<import addon="xbmc.python" version="3.0.0"/>`

### To Reproduce

1. Install the nightly for Kodi 19 win64

https://mirrors.kodi.tv/nightlies/windows/win64/master/KodiSetup-20200302-bbe9b0f9-master-x64.exe

2. Open Kodi.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 19 win64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Essam311** [comment]
@anxdpanic Please check this issue, thanks.

**Comment by enen92** [comment]
Issue is not related to kodi core. Since https://github.com/xbmc/xbmc/pull/17188 only python addons that set the abi to 3.0.0 (and in the matrix branch of both addons) are activated. There's a PR pending for that particular addon https://github.com/xbmc/repo-scripts/pull/1320
