### ISSUE TITLE
album track skipping using FTP (kodi leia -> FTP)

### ISSUE THREAD

**Issue by stepfr64** [xbmc/xbmc#17436]
### Debuglog
Sorry that i can not give a log, the device is some hundred miles away from me. 
### Screenshots
Same thing.
### Your Environment
Device: Android Xiaomi (8.0)
Kodi Leia 18.5 up to date (autoupdate from play store).
### Describe the bug
I have some flac files (indexed using musicbrainz client and with all tagging). 
Whatever the indexation made (with/out singer, album additional information), using FTP and album view, it skips some tracks.
## Actual Behavior
The track seems to be downloaded, his title is written on the top right of the screen... but nothing is played. After a few seconds, the next track is played, and 5/10 seconds later the information about the track played is refreshed. Using "file" view, all tracks are played without problem.

## Expected Behavior
Using SMB protocol, all seems to work (I play the track i launch). But through VPN, SMB have very poor performance, so i prefer use FTP.
## Possible Fix
I found no solution for the moment. Does somebody experienced anything similar ? 
### To Reproduce
Play flac ripped CD through kodi using FTP.

**Comment by DaVukovic** [comment]
Can we expect to see a debuglog at some time? If yes, when? Unfortunately we can't help without it.

**Comment by stepfr64** [comment]
I will be able to test such a problem in a few months (july). Not before, I'm really sorry. Hope anyway some others will be able to.

**Comment by DaVukovic** [comment]
Ok. Ping me if you have the log available. Going to close this issue for the time being. I'll happily reopen it if you have the log handy.
