### ISSUE TITLE
Some key events (e.g. KEY_CHANNELUP / KEY_NUMERIC_X) ignored when running from the framebuffer

### ISSUE THREAD

**Issue by yarda** [xbmc/xbmc#17430]
### Describe the bug
Here is a clear and concise description of what the problem is:

When running from the framebuffer (on raspbian) and not from the X, my IR driver successfully emits media key codes to the /dev/input/event0 (there is no other input device except the IR receiver connected). I can correctly read the correct key codes from the /dev/input/event0, but kodi ignores most of them. I would e.g. expect the KEY_CHANNELUP to increase the channel in the PVR, but nothing happen. But e.g. the KEY_VOLUMEUP/KEY_VOLUMEDOWN seems to work OK in kodi, so it's apparently reading and parsing the evdev correctly.

Moreover there is some even more strange behavior for the KEY_NUMERIC_0 - 9 / KEY_0 - 9. If I press them it switches to the channel once, e.g. if I press KEY_NUMERIC_1 it switches correctly to the channel 1, but then any more KEY_NUMERIC events are ignored by kodi, i.e. I cannot switch to the different channel until kodi is restarted. Then it works just once. On the other hand KEY_VOLUMEUP/KEY_VOLUMEDOWN works consistently all the time.

It could be related to the old bug report in the Trac:
https://trac.kodi.tv/ticket/15797

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Events correctly processed as specified in the kodi XML keymap.

## Actual Behavior

See the problem description. TLDR: some key events are not processed by kodi, some are processed only once when running without X.

## Possible Fix

None found at the moment, maybe running from the X.

### To Reproduce

Possible reproducer:
1. Install raspbian buster to the RPI, install kodi and vdr and configure kodi for PVR with vdrvnsi (I think this is not related to the VDR/VNSI)
2. Connect external DVB-T card with integrated IR receiver, configure it to correctly send KEY_ events through the /dev/input/event0
3. Start kodi on the framebuffer (not in X), switch to the PVR, 
4. Sent KEY_ events to the kodi from the IR, e.g KEY_CHANNELUP

### Debuglog

The debuglog can be found here:
I will paste kodi debuglog once I will get to the machine.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspbian Buster
 - Kodi version: 
kodi-18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by yarda** [comment]
The problem is reproduced without LIRC.

If running with the LIRC, and configured LIRC just as an devinput/LIRC bridge, i.e. the lircd to read the /dev/input/event0 and translate it 1:1 to the LIRC events through the provided/auto-generated devinput LIRC configuration files, then also removed kodi from the 'input' group (otherwise it would steal the /dev/input/event0 from the lircd and opened it exclusively) then the KEY_CHANNELUP events are correctly processed by the kodi, but only once (i.e. just the first KEY_CHANNELUP event, similarly as with the KEY_NUMERIC_X).

So there maybe two bugs:
1. Some events ignored when kodi uses /dev/input/eventX (e.g. KEY_CHANNELUP event)
2. Some events processed only once in the PVR (or channels can be switched only once) no matter from where the events are coming from (e.g. KEY_NUMERIC_X). When controlling kodi from the web browser and sending events from there (AWX) it correctly switches channels.

**Comment by DaVukovic** [comment]
No log since 2 months. Closed
