### ISSUE TITLE
Google Drive addon in Kodi doesn´t select desired audio stream when it modify the download stream quality

### ISSUE THREAD

**Issue by sergiocortina** [xbmc/xbmc#17446]
### Describe the bug
Here is a clear and concise description of what the problem is:  if you have a mkv file with two audio language ei google drive addon, and select reduce the stream quality, yo can not switch betwen audio trakcs. only work one. i tried everithin in settings traying to change the audio prefered language, but doesnt work, like if cody, when download the cuality stream, put the other audio languages away

so, in order to can change the audio stream, the defaul stream quality hast to be set in original.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sergiocortina** [comment]
some one know how can i down the stream quality and yet select an audio language in addon google drive?

**Comment by KarellenX** [comment]
Please ask your support questions on the forum and ensure you ask in the proper Google Drive addon thread where the addon developer can respond to your question.
