### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rsa2418** [xbmc/xbmc#17440]
Hello I have been using Kodi on my Windows Desktop as well as Android device since a week. I can truly assure that Kodi is a best. Please consider these two Feature additions:
 
1) While using Kodi I thought I could be great If I could continue playback of recent videos where I left them.
2) Ability to fast seek (like we can in MX Player) the progress bar.

 - Operating system version/name: Android 10 ( Oxygen OS)
 - Kodi version: 18.5

Thank you.

**Comment by enen92** [comment]
Our forum is the place for feature requests: https://forum.kodi.tv/forumdisplay.php?fid=9

**Comment by rsa2418** [comment]
Sorry. I didnt know. I will surely request on mentioned site. Thank you.
