### ISSUE TITLE
kodi-20200304-96c0d173-PR17359-merge-tvos Python Issue

### ISSUE THREAD

**Issue by flynhawaiian** [xbmc/xbmc#17443]
---
name: kodi-20200304-96c0d173-PR17359-merge-tvos Python Issue
about: Python Not Installing

---

### Describe the bug
Install plugins requiring Python there are dependency errors.

## Expected Behavior
Add-ons should install

## Actual Behavior
Dependency Issues because Python will not install

## Possible Fix
New Build?

### To Reproduce

1. Install Add-on using Python
2.
3.

### Debuglog

The debuglog can be found here: None Available with TvOS

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system: TvOS

 - [ ] Android
 - [ ] iOS
 - [X ] TvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please use the Kodi forum for your issue discussion please

**Comment by flynhawaiian** [comment]
I see no particular place in the forums to discuss a bug issue with the TvOS build can you direct me.

**Comment by fuzzard** [comment]
https://forum.kodi.tv/forumdisplay.php?fid=137

Please note, your issue just sounds like the plugins need to be update due to https://github.com/xbmc/xbmc/pull/17188 being merged 4 days ago.

**Comment by flynhawaiian** [comment]
Sounds about right.  Thanks sorry about that!

**Comment by phunkyfish** [comment]
Cause the plugins are missing I’d guess
