### ISSUE TITLE
DVD: video_ts folder wrongly scanned into a series of "Video Girl" films

### ISSUE THREAD

**Issue by lmarceg** [xbmc/xbmc#17452]
Hi everybody,
I am using Kodi 17.6 on my Mac and 17.5 on my FireTV, but I believe the issue is not the version of Kodi, but rather of the scraper (TheMovieDB) I am using.

I have a couple of DVD which I added to Kodi a couple of years ago. I manually scan the folders each time I add a new video and everything worked fine until last week or so, when all of a sudden, scraping a new film triggered the scraping of the DVD that already available in my library.

The DVD are stored in a folder structured like Film (year) / video_ts / xxxx where xxxx are all the files that the DVD needs.
Basically, what the scraper is doing is scanning the video_ts folder thinking this is a film (because in the scraping option I have set the "Films are in separate folders", and creating as many "Video Girl" movies as the amount of .ifo, .bup and .vob files it encounters within that folder.
Setting or unsetting "recursive" doesn't change anything.
I have seen a small improvement by removing everything (scraping options all unchecked), because in this case I will still see "Video Girl" as an entry, but only one entry is then shown. The problem is that the video.vob is chosen as video and if I try to click on it, nothing will work.

How can I solve this?
Thanks

**Comment by HitcherUK** [comment]
Please ask on the forum for scrapper issues.
