### ISSUE TITLE
[Python API]: xbmc.Player().getPlayingFile() returns empty string if previous video wasnt played to the end when using OMXPlayer

### ISSUE THREAD

**Issue by xoleja01** [xbmc/xbmc#17476]
### Describe the bug
xbmc.Player().getPlayingFile()  doesnt return playing video if previous video wasnt played to the end when using OMXPlayer

## Expected Behavior
It should return video file name always

## Actual Behavior
It doesnt return anything if previous video didnt end naturaly

### To Reproduce

1. Play video, and pause it in the middle
2. play another video and call xbmc.Player().getPlayingFile() - it probably returns ""
3. play it to the end, and it should work fine again

### Debuglog

The debuglog can be found here: https://paste.osmc.tv/itizixoric
2020-01-29 20:26:58.746 T:1471144672 DEBUG: ### [BSPlayer.params] - Current Action: search.
**2020-01-29 20:26:58.746 T:1471144672 DEBUG: ### [BSPlayer.video_path] - Current Video Path: .**
2020-01-29 20:26:58.746 T:1471144672 DEBUG: ### [BSPlayer.languages] - Current Languages: {‘slo’: ‘Slovak’, ‘eng’: ‘English’, ‘cze’: ‘Czech’}.
2020-01-29 20:26:58.748 T:1471144672 DEBUG: ### [BSPlayer.api_request] - Sending request: logIn.
2020-01-29 20:26:58.877 T:1471144672 DEBUG: ### [BSPlayer.login] - Logged In Successfully.
2020-01-29 20:26:58.877 T:1471144672 DEBUG: ### [utils.movie_size_and_hash] - ERROR: SizeError (0).
2020-01-29 20:26:58.877 T:1471144672 DEBUG: ### [BSPlayer.api_request] - Sending request: logOut.
2020-01-29 20:26:59.009 T:1471144672 DEBUG: ### [BSPlayer.logout] - Logged Out Successfully.

From code of subtitle provider : https://github.com/realgam3/service.subtitles.bsplayer/blob/15a1fa338379ae88bb8d13190d9abbe89e6da1a8/service.py#L32 

```
if params['action'] == 'search':
    video_path = get_video_path() <--this returns nothing
    if video_path.startswith('http://') or video_path.startswith('https://'):
        notify(__scriptname__, __language__, 32001)
        log("BSPlayer.get_video_path", "Streaming not supported.")

    log("BSPlayer.video_path", "Current Video Path: %s." % video_path) <--line from log
```

https://github.com/realgam3/service.subtitles.bsplayer/blob/15a1fa338379ae88bb8d13190d9abbe89e6da1a8/resources/lib/utils.py#L26

```
def get_video_path(xbmc_path=''):
    xbmc_path = xbmc_path or urlparse.unquote(xbmc.Player().getPlayingFile().decode('utf-8'))
    if xbmc_path.startswith('rar://'):
        return path.dirname(xbmc_path.replace('rar://', ''))
    elif xbmc_path.startswith('stack://'):
        return xbmc_path.split(" , ")[0].replace('stack://', '')
    return xbmc_path
```
xbmc.Player().getPlayingFile() probably return empty string. Or at least I cant find any other place where this can come from.

## Additional context or screenshots (if appropriate)

I found about this while using BSplayer subtitle provider.
If you interupt previous video early (let say, skip credits),  subtitle downloader for next one will fail. There is blank space where name of actualy playing video should be when you try to download subtitles. This issue doesnt occur when previous video run to the end and close naturaly."

If this happens, all what is need to do is to move any video to the end so it close naturaly and downloader is working again, it is a bit annoying solution thou.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [*] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC
 - Kodi version: 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Have you configured an external player? In other words, you are not using the Kodi default player?

**Comment by xoleja01** [comment]
> Have you configured an external player? In other words, you are not using the Kodi default player?

Im using OMXPlayer because of HW acceleraton on RsPi, but It is default anyway , I think.

> Please get us a full debug log. Snippets are mostly useless.

Sorry about logs, when I was creating issue, the link was working. I recreated it and replace url with working one.

**Comment by enen92** [comment]
So what is BSPlayer?

**Comment by xoleja01** [comment]
> So what is BSPlayer?

in this case, subtitle provider plugin

**Comment by bigretromike** [comment]
Maybe it's somehow related to this issue: https://github.com/xbmc/xbmc/issues/16183 ? both have broken external player support

**Comment by xoleja01** [comment]
I tryed to switch off OMXPlayer (it is checkbox in Settings/Player/Videos/Processing : Allow hardware acceleration - OMXPlayer) and it looks like it is working without it.

**Comment by enen92** [comment]
@xoleja01 am I correct into assuming you **can't** reproduce this issue without omxplayer? Your last comment is not really clear for me.

**Comment by xoleja01** [comment]
Im not completely sure what exacly does that checkbox do. But if I untick it, I cant reproduce issue.

**Comment by enen92** [comment]
closing as we don't have omxplayer anymore in the main codebase (removed for leia)
