### ISSUE TITLE
Movieposters won't show up anymore in chorus2 and remote

### ISSUE THREAD

**Issue by howie-f** [xbmc/xbmc#17487]
### Describe the bug
since PR #17127 movie-posters won't show anymore in the webinterface and official-kodi-remote (ios).

## Possible Fix
testing with this pr reverted shows the known behavior.

### To Reproduce
1. Open webinterface in browser

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/ebeqalobah.kodi

### Screenshots 
![IMG_0038](https://user-images.githubusercontent.com/58829855/76560097-bad09c00-64a0-11ea-98b6-6b856e0e2da8.PNG)

screenshot of kodi-remote not available but it's the same

### Your Environment
 - [X] Linux
 
 - Operating system version/name: Deb. Stretch
 - Kodi version: 19 Alpha

@enen92 there you are, thanks

**Comment by enen92** [comment]
@howie-f the issue happens due to the removal of the thumb fallback to the movie poster in the linked PR. Both applications should request the art parameter from the json rpc. The poster and all the other artwork is there.
Unfortunately I think both chorus and the official ios remote are without maintainers at the moment...

@rmrector any thoughts? Should we reintroduce the fallback?

**Comment by howie-f** [comment]
as this was an intentional removal i could probably _try_ to fix chorus by myself. ios remote would be a bit too hard for me, as i have no idea how to test (or even find the source). the thing is it really doesn't look nice actually. thanks for your investigation

**Comment by KarellenX** [comment]
It is ignoring my posters also, instead prefering what looks like screen captures...

![chorus2](https://user-images.githubusercontent.com/44626605/76577658-302c8300-651a-11ea-9cc4-63f577887281.JPG)

**Comment by howie-f** [comment]
@KarellenX i guess those are the autogenerated thumbs

**Comment by enen92** [comment]
Unfortunately I don't think there is anything to fix in kodi. All the `CFileItem` artwork is in the art map, so consumers of the jsonrpc API should decide what to use (or how to perceive) the concept of thumbnail.  If the thumbnail is the movie poster...use the art.poster, if it is the banner...use art.banner, and so on. Kodi should not make any assumptions on how third party tools use the data.

I fixed the issue for chorus2 here: https://github.com/xbmc/chorus2/pull/392 and attached there is a test version that have this fixed ([webinterface.default.19.x-0.0.1.zip](https://github.com/xbmc/xbmc/files/4329797/webinterface.default.19.x-0.0.1.zip)). Unfortunately I don't think it is being maintained at the moment...

For IOS remote I can't do much but hopefully we may soon have news regarding that.

**Comment by howie-f** [comment]
@enen92 i'm afraid, that's not working
of course **no** priority to me

![screenshot003](https://user-images.githubusercontent.com/58829855/76652909-d652aa00-6567-11ea-9615-662008ed5f4a.png)

![IMG_0039](https://user-images.githubusercontent.com/58829855/76652868-be7b2600-6567-11ea-85e7-0f7830604cb1.PNG)

**Comment by DaVukovic** [comment]
Can confirm that it works

**Comment by howie-f** [comment]
.....ok.

Firefox on Debian is doing fine with this! :+1: 

Safari on iPad2 worked with Kodi18 :+1: 

Safari on iPad2 with your patched version does this: :-1: 

1. Login screen
![IMG_0040](https://user-images.githubusercontent.com/58829855/76655462-a1495600-656d-11ea-8be0-ae9c5e75099c.PNG)

2. after login
![IMG_0041](https://user-images.githubusercontent.com/58829855/76655475-a7d7cd80-656d-11ea-9ff6-d9b85ee687c6.PNG)

3. Opening from the left side
![IMG_0042](https://user-images.githubusercontent.com/58829855/76655491-aefedb80-656d-11ea-8b69-195fadeb5d38.PNG)

strange.. but forget about it ;)

**Comment by enen92** [comment]
Are you sure about the caching? chorus2 itself caches the items. Can you somehow do a force refresh on the ipad/safari or try another browser on the same device?
Just curious as I doubt I will be able to do much

**Comment by howie-f** [comment]
Yes absolutely sure. cleared the cache once again but Safari still no posters.
Can confirm now that Firefox on iPad2 also works.
I'm fine with that, thanks again
