### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by RyKaj** [xbmc/xbmc#17505]
I am not sure if anyone is working on this or not.  I use Kodi on Windows. I have configure my add-on to download to my local hard drive. It would be nice to have a page that only shows the what is still being downloaded. The left toaster notification does not show the all the items being downloaded and status.

**Comment by DaVukovic** [comment]
Not sure which addon you are using or if it's banned or not, but those question do either belong to the forums or asked at those who are maintaining the addon you are using

Closed
