### ISSUE TITLE
Backport "Dark Grey" subtitle feature in Kodi 18.6 Stable (Android TV)

### ISSUE THREAD

**Issue by xinseo** [xbmc/xbmc#17519]
### Describe the bug
Here is a clear and concise description of what the problem is:

On Most LCD/LED/OLED TVs, watching HDR content with Subtitles is blinding as they are super bright. This has been somewhat fixed in Kodi 19 by introduction of 'Dark Grey subtitle color' as a new feature.

Considering that it would take some time for Kodi 19 to reach stable milestone, it would be beneficial to all Android TV users if the 'Dark Grey subtitle color' feature be backported to Kodi 18.6 stable.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Dark grey subtitle feature should be backported.

## Actual Behavior

Subtitles are at least 2 times as bright as the rest of the screen

## Possible Fix

'Dark grey subtitle' feature introduced in Kodi 19 be backported to 18.6

### To Reproduce

1. Watch any HDR content with external srt subtitles on an OLED TV.

### Debuglog

The debuglog can be found here:
Not needed.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system: NVIDIA Shield TV.

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.6 Stable.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Bringing up a feature request where we only accept bug reports won't get that feature into Kodi 18. 

Even if you request that feature for Kodi 18 at the forums (where feature requests should be placed instead) won't help you unfortunately. 

Discussion starts here: https://github.com/xbmc/xbmc/pull/16222
