### ISSUE TITLE
Kodi cannot start, closes itself automatically

### ISSUE THREAD

**Issue by tingjhenjiang** [xbmc/xbmc#17526]
## Expected Behavior

Kodi app should start and enter menu.

## Actual Behavior

The error is that I cannot start Kodi and make it correctly enter menu, and the app will close automatically, easpecially:
1. after my computer boot into desktop for a while;
2. after I initiated and closed Kodi once or more times.

I can see Kodi trying to start: the Kodi app icon displayed in the taskbar, but it cannot proceed to enter the menu.

This error won't happen when I start Kodi right after computer boot up into Windows desktop.
I've tried a clean install to see if this error persists, and find out that this error still happens.

Also, the same Kodi environment (settings and plugins) are applied to a Kodi Leia 18.5 installation on Raspbian on Raspberry Pi 4, but no errors happened there.

## Possible Fix
None found.

### To Reproduce

1. start the Kodi app after Windows boot for a while (I'm not clearly know how much time it exactly needed); or:
2. restart Kodi for one or few times.

### Debuglog
The debuglog can be found here:
1. failed startup log 1 https://paste.kodi.tv/apahudolob.kodi
2. failed startup log 2 https://paste.kodi.tv/dudovivuma.kodi
3. successful startup log 1 https://paste.kodi.tv/icahesuhog.kodi
4. successful startup log 2 https://paste.kodi.tv/joyodubuna.kodi
4. successful startup log 3 https://paste.kodi.tv/mucivanoyu.kodi

Under situations that errors happened, the last line of logs would always read `DEBUG: CIRServerSuite::Connect: connecting to: ::1:24000 ...
`

### Screenshots 
https://imgur.com/a/NHvFGu4

## Additional context or screenshots (if appropriate)
You can see that the Kodi icon appeared and then disappeared.
There is also an another situation that I did not capture and provide, where the app might just display a black screen and then closes.

### Your Environment
Kodi Leia 18.5, 18.6. 
Windows 10.

**Comment by KarellenX** [comment]
@tingjhenjiang 

Thank you for your report and correct logs.

Github issues are reports for bugs. I don't believe you are experiencing a bug in Kodi, rather some unusual settings on your PC.

I will close this for now, Please repost on the forum along with your logs.

When you do post on the forum, please also explain why the logs show different and unusual screen resolutions and using different graphics cards.

Thanks
