### ISSUE TITLE
Pink Artifacts in h.265 videos since 18.6 on android tv

### ISSUE THREAD

**Issue by popy2k14** [xbmc/xbmc#17520]
### Describe the bug
The issue popped up after update to kodi 18.6 on my two android TVs (Philips 65PUS8102 & 55PUS9104).

My issue is a "color" issue reproduceable with h.265 content since the upgrade.
I have several h265 movies which shows some "pink" artifacts every few seconds.
It seems they are on dark parts of the scene.
I dont know if the issue is just on h265 or also on h264 because most of my collection is h265 and i downgraded before i tried h264 content -> because the tvs are in use more often now because of the corona virus.

I can reproduce the issue on my two sets with the same movie (Men in Black -> i own he Bluray and ripped it myself, so i can provide the movie for testing purposes)!
Restarting kodi 18.6 does'nt help.

After downgrade to 18.5 (and deactivate play store auto update), the issue disappear on both of my tv sets (without restarting android)!

## Expected Behavior
The pink artiacts should not appear, as it was on kodi 18.5 and lower.

## Actual Behavior
Pink artifacts appears every few seconds, mostly after scenes changing and on dark scenes.

## Possible Fix
If anyone could provide test build of 18.6+ without some commits missing, i can test those and provide feedback. A 100% workaround is to use kodi 18.5 (or lower? but this is not tested by me).

### To Reproduce
1. install kodi 18.6 on antroid tv (maybe just philips devices)
2. watch h.265 (maybe h.264 also) content -> i can provide a test movie
3. every few seconds (~30s)  a pink artifact occurs, mostly after changing scenes (i frames?)

### Debuglog
The debuglog can be found here: [kodi.zip](https://github.com/xbmc/xbmc/files/4354238/kodi.zip)

### Screenshots 
sorry no screenshots

## Additional context or screenshots (if appropriate)
sorry no screenshots

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Philips TPM171E with Android 8.0.0 API level 26, kernel: Linux ARM 32-bit version 3.10.79
 - Kodi version: Kodi (18.6 Git:20200229-8e967df921). Platform: Android ARM 32-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
If you find the time (and I totally understand the current situation that the TV is mostly in use), it would be awesome if you could try/confirm the following:

- try without emby (probably play the file from the filemanager)
- please confirm, that it happens with h.265 or .264 only or with both. Making assumptions in that regard means more testing on our side. So we would be thankful if you can the one or the other out (or confirm on both).

**Comment by popy2k14** [comment]
Got a time frame to test your suggestions :-)
I have reripped the same movie as h264 (from bluray) again to have the same movie for the tests.
Choosed a scene where both jumps from the bridge for all tests @ 10min.

Tests on 18.6:
1. Start kodi and  let it run until the PVR & emby things got silent
2. played h265 movie with emby -> visible pink artifacts
3. played h265 movie without emby -> visible pink artifacts
4. played h264 movie without emby -> NO visible artifacts -> OK

Downgraded kodi to 18.5 and repeated the tests without reboot android TV -> no issues at all with h265.

It seems there is an h265 color space issue on 18.6.
Also older movies which i have ripped and converted to h265 suffer from this pink artifacts issue.

Please find the logs from my tests above with 18.5 & 18.6 here: [kodi_logs.zip](https://github.com/xbmc/xbmc/files/4362932/kodi_logs.zip)

Hope you can identify and fix the issue.
If you need testers for test builds, i am here.

**Comment by popy2k14** [comment]
Maybe one of these?

https://github.com/xbmc/xbmc/pull/17356
https://github.com/xbmc/xbmc/pull/17305
https://github.com/xbmc/xbmc/pull/17111

**Comment by fritsch** [comment]
Try: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20200319-691e040e-revertdvonly-armeabi-v7a.apk please

**Comment by popy2k14** [comment]
Tested with same tests as above, issue is still present with the test build.

**Comment by fritsch** [comment]
What about this: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20200319-255d2e7e-revertdv-armeabi-v7a.apk - anything better?

**Comment by popy2k14** [comment]
On this build the issue is gone!
All my movies are working as expected, without any artifacts.

Can you please explain from a technical standpoint what the issue was or what you have changed?
Just because i want to understand the issue :-)

PS.: Will there be an bugfix release 18.7 soon because 18.6 was rolled out on play store to other android TVs too. Will this fix also cover: https://github.com/xbmc/xbmc/issues/17513 ?

Thanks a lot

**Comment by fritsch** [comment]
Too bad. That fix was introduced cause it fixed wrong aspect ratio on Philips devices.

So then. Let's revert it.

**Comment by popy2k14** [comment]
ok, got you.
Thanks for getting into it and finding the culprit.

Will there be an hotfic release 18.7 soon in play store?
Asking because i have deactivated auto update in the mean time.

**Comment by fritsch** [comment]
There won't be any hotfix. If we fix the one broken firmware the other broken firmware will get kaputt ... here: #17356 <- that's the reason for your issue. Fixing your's will make the others unhappy.

Though - as it's a regression I revert it.

**Comment by popy2k14** [comment]
Ok, thanks.
When i got the issue right it fixes some aspec ratio related issues because of lacking "optional" width/height fields.

But how about matrix? Will the fix in it -> some, like i, have issues again?

As stated above, i can provide samples to reproduce the issue.

**Comment by fritsch** [comment]
Discuss with those folks: https://forum.kodi.tv/showthread.php?tid=352515&page=3

If you agree, tell me: Fixing Philips 1 and breaking Sony and Philips 2 or other way round :-)

**Comment by fritsch** [comment]
Samples are useless, the broken HW is needed. Standard device like FireTV 4K, etc. are fine.

**Comment by fritsch** [comment]
Sorry, I meant these folks: https://forum.kodi.tv/showthread.php?tid=341491&page=5

Btw. does your issue only appear with 1080p content or does the size not matter? Is H264 really affected or just H265.

**Comment by popy2k14** [comment]
hmmm, thats so sad that there so many little differences in implementations from vendor side...

I have watched h264 720p HD content over PVR addon without an issue on 18.6.
And yes, it seems h265 1080p only. Not tried h265 720p.

I am on the newest android version which is available for my TV, it is: "Philips TPM171E with Android 8.0.0 API level 26, kernel: Linux ARM 32-bit version 3.10.79"

Seems that the folks over there (in the linked thread) have other platforms / android versions.

Any chance of doing some quirks like: if platform is like XY with version XY, do not this.

**Comment by fritsch** [comment]
No. Quirks are a route to nowhere. 2 Quirks for Sony, 3 for Rockchip, 12 for AMLogic, 3 for Philips - and if you provide support for e.g. DolbyVision the Philips Quirk comes back and says: But, but, but it broke my Home-Videos.

I will apply the min-height / max-height only for formats NOT being HEVC. But therefore I need to see what files the other guys in the forum thread have.

**Comment by fritsch** [comment]
Do you a hevc file that is NOT 1920x1088 (the 88 is important) that has these effects?

**Comment by popy2k14** [comment]
Can try tomorrow, All TVs in use now.

PS.: Have readed in the revert commit that you have another idea: query before set.
If you have an test build i can test it also tomorrow

**Comment by fritsch** [comment]
Yes: Updates in regression forum thread to not spam entire developers here.
