### ISSUE TITLE
PIL error under linux

### ISSUE THREAD

**Issue by daggs1** [xbmc/xbmc#17522]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a plugin I support (https://github.com/daggs1/plugin.audio.100fm-Digital) which uses Image from PIL.
on a master snapshot from a few months ago it worked, on dabb6343c399366e18b6026163ed6bc08024ae95 I get this:
2020-03-19 21:25:04.784 T:18214   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'ModuleNotFoundError'>
                                            Error Contents: No module named 'PIL'
                                            Traceback (most recent call last):
                                              File "/home/dagg/workspace/xbmc/build/portable_data/addons/plugin.audio.100fm-digital/main.py", line 8, in <module>
                                                from PIL import Image
                                            ModuleNotFoundError: No module named 'PIL'
                                            -->End of Python script error report<--

the configure phase had -DX11_RENDER_SYSTEM=gl only.
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

the addoon should boot

## Actual Behavior

the addon crashes with the error mentioned above.

### To Reproduce

1. compile latest kodi
2. install https://github.com/daggs1/plugin.audio.100fm-Digital/archive/v1.0.x.zip
3. try to execute.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: gentoo
 - Kodi version: dabb6343c399366e18b6026163ed6bc08024ae95

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
This sounds more like a support question which should be asked at the forums first. AFAICT (and maybe I'm wrong on that) PIL is deprecated anyway. 

I'll happily re-open this issue if it's a Kodi bug.

**Comment by daggs1** [comment]
> This sounds more like a support question which should be asked at the forums first. AFAICT (and maybe I'm wrong on that) PIL is deprecated anyway.
> 
> I'll happily re-open this issue if it's a Kodi bug.

I don't know, as said suggested by the-black-eagle, compiling kodi against a specific python version works but a few months back I didn't needed to specify a specific version and it worked out of the box.
my system always had several python versions.

**Comment by DaVukovic** [comment]
please read the comment here: https://github.com/daggs1/plugin.audio.100fm-Digital/issues/1#issuecomment-601564354
