### ISSUE TITLE
DSD music playback too low

### ISSUE THREAD

**Issue by HeresJonny** [xbmc/xbmc#17537]
### Describe the bug
Here is a clear and concise description of what the problem is:
Playback of .dsf (possibly all DSD) audio files is 6db lower than playback of PCM audio files.

Music files are expected to be have more or less the same volume (recording age nonwithstanding but that's what replaygain is for). In the case of .dsf files which are of the DSD domain, however, playback is done at consistently much lower volume. Since DSD in theory also bypasses all PCM post-processing, replaygain is not expected to have any effect. The only remedy is to really turn up the volume on my digital receiver by at least +6db.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

DSD files should be decoded with +6db.

## Actual Behavior

DSD music playback is much too low when compared to PCM music playback.

### To Reproduce

1. Play a .dsf file
2. Play a .flac/.mp3 file
3. Notice the volume difference.

### Debuglog

The debuglog can be found here:
I don't think the described effect would show up there but if you think it will help I would provide a log if asked.
Dummy: https://localhost/kodi.log

### Screenshots 
Here are some links or screenshots to help explain the problem:

Not of the visual kind

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18 or 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
> I don't think the described effect would show up there but if you think it will help I would provide a log if asked.

Isn't asking at the template enough?

For what I understand, DSD do come from Super Audio CDs and can also contain multichannel audio tracks. So it should be bitstreamed from Kodi to the AVR in use. In that case Kodi doesn't touch the audio at all. I might be wrong, but I would compare it to the same behaviour Kodi does for movies and digital audio streams, such as DD, DTS or their respective HD-alternatives, where Kodi is simply bitstreaming the audio to the AVR and the AVR does the decoding. If that's the case, Kodi doesn't decode anything and you simply have to turn the volume a bit higher. 

Anyway, provide the log first

**Comment by HeresJonny** [comment]
AVR says it is sent as PCM, not DSD, so it looks like Kodi decodes it. Anyway, you have all the info you need to reproduce it and you know your code better than me.

**Comment by DaVukovic** [comment]
Most of us don't have DSD files, could you provide a sample

Next to the logfile we have asked for

**Comment by HeresJonny** [comment]
Sure, here are PCM and DSD releases for the same track for comparison https://www.dropbox.com/s/370c1ezez67pf80/flac_dsf.zip?dl=0
Here's a 5.1 DSD file for future reference https://www.dropbox.com/s/k0w8u6bohk01rkb/DSD_5.1mix.7z?dl=0

I don't know if DSD passthrough (over HDMI) is already implemented, that would really be great.
Also there are some open tagging issues because ffmpeg doesn't support that yet but @DaveTBlake is already aware of that and there's probably not much to be done right now (if you don't want to add non-main patches) 

I'll generate a log file later today.
