### ISSUE TITLE
Kodi only audio without video on HBO and Netflix

### ISSUE THREAD

**Issue by TomaszM13** [xbmc/xbmc#17530]
Hi,

At HBO and Netflix I have a sound without video and I can't do anything about it.  Turning off hardware acceleration doesn't help.  Reinstallation too.  It doesn't matter which Kodi version I have. Plugins use Input Stream Adaptive.  Other plugins work.

Everything is normal until the movie starts.  When selected, a black screen appears or a small photo.  Time goes by, is sound but no video.

Logi:

https://drive.google.com/file/d/1CwTYndPxYldfEWUzD0l6MhIA4GzwJWQQ/view?usp=drivesdk

 - [ x] Android

 - Operating system version/name: 9
 - Kodi version: 18
Device: Beelink GT1-mini2

Please help.

Regards

**Comment by TomaszM13** [comment]
Tell me what I didn't post

**Comment by DaVukovic** [comment]
Forgive our bot. That happens if you delete the template and post in your own stuff ;)

I'll remove that flag

**Comment by DaVukovic** [comment]
But...your log is not a debuglog. You missed to enable debug logging at the system settings. Our devs can't help without that. So please get us a new log with debugging enabled.

**Comment by TomaszM13** [comment]
Maybe now?

https://drive.google.com/file/d/1CwTYndPxYldfEWUzD0l6MhIA4GzwJWQQ/view?usp=drivesdk
