### ISSUE TITLE
special://envhome/ won't resolve to /var/mobile/ on iOS

### ISSUE THREAD

**Issue by Lamoboy** [xbmc/xbmc#17553]
### Describe the bug
Here is a clear and concise description of what the problem is:

In order to be able to download videos after I set a directory in [Videodevil addon](https://github.com/xbmc-adult/xbmc-adult) settings, I should replace in file `\var\mobile\Library\Preferences\Kodi\userdata\addon_data\plugin.video.videodevil\settings.xml` this `special://envhome/` with that `/var/mobile/`.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Once the directory is set in Videodevil addon settings, the videos should download without any additional manipulations.

## Actual Behavior

The videos won't download until I replace in file `\var\mobile\Library\Preferences\Kodi\userdata\addon_data\plugin.video.videodevil\settings.xml` this `special://envhome/` with that `/var/mobile/`.

## Possible Fix

Fix resolving of `special://envhome/` to `/var/mobile/` on iOS.

### To Reproduce

1. Install Kodi on iOS.
2. Install Videodevil addon.
3. Set download directory in Videodevil addon settings.
4. Try to download any video with Videodevil addon.

### Debuglog

The debuglog can be found here:
https://mega.nz/#!M08wyKqL!uIAPs6N-cKrlx0HxrXriJQKKCawMqM3iGwCpTjjlYGI

### Screenshots 
Here are some links or screenshots to help explain the problem:

http://i.piccy.info/i9/a55551aafb453e5688258189f56f8c31/1585055757/85791/1369127/2020_03_24_14_57_IMG_2306.jpg

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

[Here is a link to the issue](https://github.com/xbmc-adult/xbmc-adult/issues/333) where the contributor of Videodevil addon says that it is the issue of the Kodi itself.

### Your Environment
Used Operating system:

 - [ ] Android
 - [x] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 12.4
 - Kodi version: 18.7

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by kambala-decapitator** [comment]
your device is jailbroken, isn't it?

**Comment by Lamoboy** [comment]
Yes, my device is jailbroken with unc0ver.

> so seems it already works correctly.
but it doesn't.

**Comment by kambala-decapitator** [comment]
I think you'd want this folder:

> 2020-03-24 14:57:02.540 T:6169161728  NOTICE: special://masterprofile/ is mapped to: /var/mobile/Library/Preferences/Kodi/userdata

Your log doesn't really contain any useful info, unfortunately. Also, I don't see the same path there as in your screenshot.

And FYI: that addon makes use of illegal sources, Kodi team doesn't provide support for such kind of add-ons. So your best shot would be to check with add-on dev or investigate yourself. If you can reproduce the same issue with a legal add-on, then the issue will be valid and won't be closed.

**Comment by Lamoboy** [comment]
Please let me know what legal addon has a feature of downloading files and ability to set download folder in settings and I’ll reproduce the issue.

**Comment by DaVukovic** [comment]
Tbh that´s not our problem. We don´t support that stuff in here and you also have way too many banned add-ons and repos installed. Please open a new issue with an add-on in use which is not on our banned list

I´ll close this now.
