### ISSUE TITLE
Issue with Interlaced Video Streams on 18.6

### ISSUE THREAD

**Issue by bootyshine** [xbmc/xbmc#17559]
### Describe the bug
Here is a clear and concise description of what the problem is:

I am experiencing troubles with interlaced video on 18.6, where the image is all scrambled. I didn't have problems before updating from 18.5.
I'm attaching screenshot from 18.6 and since downgraded back to 18.5

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Correctly deinterlace the video stream.

## Actual Behavior

Stream is not playing correctly.

### To Reproduce

1. Play any interlaced stream
2. Either you get frozen frame with audio only or **screenshot**
3.

### Debuglog

The debuglog can be found here:
I don't have 18.6 currently installed, if needed I'll provide asap !

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://i.imgur.com/AXkVjUB.png

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 9.0
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Yes, we need a log, hence we are asking for it at our template
Please provide one. 

Thanks in advance

**Comment by bootyshine** [comment]
Is there going to be a problem if I delete all links to the streams? And also delete my PC name off it ?

**Comment by bootyshine** [comment]
I've removed sensitive info from log and here it is -> 18.5 - https://pastebin.com/GMzGxNX7
18.6 - https://pastebin.com/mGc7KbPM 
Let me know if you need anything else, and thanks ! :)

**Comment by bootyshine** [comment]
Weird since I didn't have any problems with 18.5, and all I did when I said "I removed sensitive info" is to obfuscate my stream, and hide the name of my computer :)

**Comment by bootyshine** [comment]
Just tested with local interlaced file, the problem persists on 18.6 :(

**Comment by DaVukovic** [comment]
get us a log from that local file

**Comment by bootyshine** [comment]
There you go :) https://pastebin.com/tG5gwkyp

**Comment by fritsch** [comment]
Turn off Mediacodec and Mediacodec Surface. Sadly your android's firmware does not properly support Interlaced video via Mediacodec. 

Unticking that will most likely cause sever issues with other files.

**Comment by bootyshine** [comment]
Disabling both results in lag, however if only Mediacodec is turned on, file is playable however i get frameskips, Turning on Mediacodec Surface results in incorrectly playback. 
Just reinstalled 18.5, both of the options turned on, have no problems with playback of the file and no frameskips or anything.

**Comment by fritsch** [comment]
Perfect Thanks for this pointer, please try this build: http://mirrors.kodi.tv/nightlies/android/arm/Leia/kodi-20200326-4e967666-Leia-armeabi-v7a.apk

Something slipped into 18.6 for Philips TVs to workaround one of their FW issues which sadly had impact (too much impact on other devices). I already reverted that in Leia and master. The above link installs a Leia nightly, the base for upcoming 18.7

**Comment by bootyshine** [comment]
Installed nightly, and now its perfectly working with the local file, will setup my IPTV later and will report back if needed, I'm so glad that you guys fixed it, thanks a lot !

**Comment by fritsch** [comment]
Thanks much for helping us!
Fixed via: https://github.com/xbmc/xbmc/pull/17557
