### ISSUE TITLE
Black screen when switching from PVR TV channel to PVR radio channel

### ISSUE THREAD

**Issue by ou-li** [xbmc/xbmc#17556]
### Describe the bug
Using  PVR (local tvheadend), launching radio channels from EPG, home screen or switching between radio channels is fine. However, when I switch from an active tv channel directly to a radio channel, the screen turns black.
I have checked this on my LibreElec 9.2.0 box as well as on a clean and fresh install (18.6 Compiled 2020-03-01 on Ubuntu 18.04 via official ppa:team-xbmc/ppa repository).

[Reportedly,](https://forum.kodi.tv/showthread.php?tid=352660&pid=2934281#pid2934281) this also applies to Matrix and also disables Shoutcast metadata.
The screen is actually not completely black, by changing the background pattern you can see that its just very high opacity: [Screenshot](https://nuage.balad.in/index.php/s/xZyyj9iBMoG6KSk/preview)

## Expected Behavior
Artwork or background image should be visible, ideally Info window should stay in foreground for radio.

## Actual Behavior
Screen turns black and remains black.

## Possible Fix
First figure out whether this is a PVR issue, a player issue ore a combination of both?

### To Reproduce
1. Tune into a PVR TV channel (tvheadend connected to DVB-S2 tuner in my case).
2. Leaving the TV channel active in background, press back on remote control tu return to home screen, launch radio channel from there. (also works if you use favourites instead).
3. Wait for 5 seconds for info and a couple of more seconds for player controls to disappear --> black screen.

### Debuglog
https://nuage.balad.in/index.php/s/dPTLXQdBr8kfsao

### Screenshots 
Video of the problem, black screen at the very end:
https://nuage.balad.in/index.php/s/Bm57r9jZGCZydQo

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
-  [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Kodi version: LibreElec 9.2.0 and Kodi 18.6 Compiled 2020-03-01 on Ubuntu 18.04 via official ppa:team-xbmc/ppa repository

**Comment by ksooo** [comment]
Confirmed: Root cause is that PVR Live TV and PVR Radio need different windows (VideoFullscreen vs. MusicVisualization) and "PVR fast cahnnel switch" does technically work but windows get not "exchanged" when switching from Live TV to radio and vica versa. This leads to the reported visual glitches. @FernetMenta do you have an idea how to force a window switch?

**Comment by ksooo** [comment]
This issue is platform indipendent
