### ISSUE TITLE
Volume low despite settings in audio gui for Volume Amplification

### ISSUE THREAD

**Issue by biner73** [xbmc/xbmc#17564]
### Describe the bug
Here is a clear and concise description of what the problem is:
Sometimes when launching Kodi, the volume is low, despite having Volume amplification set as default for all, (.set at 14db currently) and Audio settings in gui showing 14db.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Once the Volume Amplification is set correctly, it should always work.

### To Reproduce

Steps to recreate:
1. Launch Kodi
2. Play media (movie or tvshow)
3. Volume will be low (despite setting in gui)
4. Bring up the Audio Settings in gui, and select the Volume Amplification slider.
5. Move the slider down or up from current position, and volume will jump back up to current setting (14db) and will now be correct.
6. Select "set as default for all media" again 
7. Close media and exit Kodi
7. Start Kodi and volume will be low again, despite Volume Amplification will still be showing 14db.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/4391907/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.6 release
WIndows 10 with all latest updates

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Thanks for ignoring our template by not providing a debuglog. 

Please provide one. We have to ask way to many questions to solve that what a simple logfile will answer.

**Comment by biner73** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/4391903/kodi.log)
Attaching debug log

**Comment by pcurtis456** [comment]
Hi there.
Ive got exactly the same problem.
[kodi.log](https://github.com/xbmc/xbmc/files/4395834/kodi.log)

**Comment by DaVukovic** [comment]
@biner73 You are using directsound if I'm not mistake. Does it make any difference if you are using WASAPI?
Also, just for the note. It's pretty normal that movies do have a different loudness. Beside using the volume amplification, I would rather suggest to regulate the volume on the TV/AVR in use. Not saying that there might not be a bug somewhere. Just making a suggestion. Using the volume amplification on such a high level wouldn't be something I would recommend at all. As (as far as I understand), by using the Kodi amplification, at some point it will sound pretty bad and I guess your TV or your AVR can do a better job on this. 

Maybe @fritsch is able to confirm. 

@pcurtis456 You are not playing anything in that log.

**Comment by biner73** [comment]
Yes using directsound, I haven’t tested wasapi enough to know if it’s also affected.

Completely understand that this is a tricky one, since it’s intermittent. To add to the note below, it’s not so much the differences in volume between movies (as yes that can vary), but it’s like sometimes the volume amplification is not working at all. Then if you adjust while playing, it jumps up instantly to the set value.

In addition, this only happens on startup, and only sometimes. When the first movie is played after startup, this is when the issue occurs. If the volume amplification is then adjusted during playback (even if reset to all media) it remains fine until Kodi is exited.

Also at plus 14 on volume amplification, there is no clipping, or signs of distortion. This basically makes Kodi the same volume as other sources on the media centre box (music, YouTube etc). If left at zero, Kodi is much quieter than the other sources.

**Comment by biner73** [comment]
I've been doing more testing, and I think this issue started with Kodi 18.0 when the menus for audio settings and subtitle settings were split apart. In Kodi 17.6, where the audio/subtitle onscreen menu is together in one, this issue does not occur.

I also noticed that in Kodi 18 in addition to the volume amplification "not remembering" the setting after Kodi is shutdown/started, subtitles flash at the beginning of playback. I believe that during the transition from Kodi 17->18 where the audio/subtitles dialogs are seperated, there is a bug somewhere around how they read/process the settings from guisettings.xml on startup.

Hope this might be a direction to look in.
