### ISSUE TITLE
[PVR] Watched Count GUI item being displayed regardless of PVR supporting bSupportsRecordingPlayCount

### ISSUE THREAD

**Issue by djp952** [xbmc/xbmc#17568]
### Describe the bug
Here is a clear and concise description of what the problem is:

After PR [17516](https://github.com/xbmc/xbmc/pull/17516), the Kodi PVR GUI is displaying the watched count even if the PVR addon does not support reporting of Last Played Count.  If the addon cannot support this functionality, the GUI will always display "0/x" for this count, with x being the number of recordings in the folder.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If a PVR addon does not support Recording Play Count, my expectation is that the Kodi GUI would omit this secondary label altogether since it cannot be accurate based on how "watchedcount" is calculated internally.

## Actual Behavior
PVR addons that are unable or unwilling to report a play count will cause the GUI to always display "0/x", with x being the number of recordings in the folder.

## Possible Fix
The PVR_ADDON_CAPABILITIES::bSupportsRecordingPlayCount property should be examined prior to adding this GUI element via the call to SetLabel2().

### To Reproduce

- Install Kodi "Matrix" nightly on or after PR [17516](https://github.com/xbmc/xbmc/pull/17516) was merged
- Install a PVR addon that reports bSupportsRecordingPlayCount as 'false'
- All Folder under TV/Recordings will report a a watched count of 0/x, where x is the number of recordings in the folder.

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/ofaxizisow.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

A great deal of these recordings have been watched, but since the PVR addon does not support bSupportsRecordingPlayCount, they will always show up as 0/x:

![playcount](https://user-images.githubusercontent.com/706055/77720405-33198000-6fbe-11ea-8e28-41758565fde4.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.0 Nightly running on Windows 10 x64, version 1909.

**Comment by ksooo** [comment]
If I remember correctly, play counts work even if the addon does not support this feature. In this case, local play counts will be maintained by Kodi. So, the real question is why Kodi does not display the local play counts.

**Comment by djp952** [comment]
Ah, OK.  The problem is that all our recordings have end padding so they never really get 'watched' all the way.  If I get one close enough to the end to trigger it the count will be reported accurated.

This new indicator will be weird in distributed environments where many clients share one backend that is unable to report the play count.  Not sure how common that scenario would be.  It confused me since I had to go through PRs to find out what it was even supposed to be reporting.

This would be more of a suggestion than an Issue, fine with cancelling it out; appears to be working as designed.  I think it would work better if it was tied to the PVR's ability to report the information, or maybe if there was a setting in PVR & Live TV / Recordings to turn it off on a client-by-client basis.

If neither of those suggestions have any merit, this can be closed :)

Thanks!

**Comment by ksooo** [comment]
> or maybe if there was a setting in PVR & Live TV / Recordings to turn it off on a client-by-client basis.

 This should be offered by the addons. For example, pvr.hts has a setting to control this.

**Comment by ksooo** [comment]
Closing, as the issue reported here is non-existent.

**Comment by djp952** [comment]
> > or maybe if there was a setting in PVR & Live TV / Recordings to turn it off on a client-by-client basis.
> 
> This should be offered by the addons. For example, pvr.hts has a setting to control this.

Point was that the addon cannot turn off this new feature since it's not tied to any capabilities ...

**Comment by ksooo** [comment]
sorry, which feature exactly?

**Comment by ksooo** [comment]
There is a new add-on capability for recording size support...

**Comment by ksooo** [comment]
You mean display of watched/total for recordings folders, right?

I suggest to open a new issue for that.

**Comment by ksooo** [comment]
>> This new indicator will be weird in distributed environments where many clients share one backend that is unable to report the play count. 

 Sure, this is the same problem as with media sources shared between different Kodi clients. Solution is to use a shared (MySQL) database for this scenarios.

**Comment by djp952** [comment]
> You mean display of watched/total for recordings folders, right?
> 
> I suggest to open a new issue for that.

That's what this Issue was for.  Let's just go with "nevermind" - as is typical it's far too frustrating to bother with.
