### ISSUE TITLE
Kodi crashes when Greek GUI language selected 

### ISSUE THREAD

**Issue by leo06** [xbmc/xbmc#17578]
### Describe the bug
Here is a clear and concise description of what the problem is:

When Greek GUI language selected Kodi crashes if selected skin is other than estuary. This behavior started February 17th and still present in v18.6. After first crash Kodi keeps crashing in load screen

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Not to crash 

## Possible Fix

It starts normal again if I change el_gr to en_gb in guisettings.xml 

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/kiqaxemuli.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Android
Kodi 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
> When Greek GUI language selected Kodi crashes if selected skin is other than estuary

As you are using a skin from a completely different repository and as you found out yourself, it doesn't happen with stock Estuary, that's not a Kodi issue then. Please report that to the skin author. 

Thanks

**Comment by leo06** [comment]
It's not happening only in titan bingie I tested. It happens in every skin other than estuary and started on February 17th, before all worked ok, no skin update on that date so it's not skin issue
