### ISSUE TITLE
kodi 18.6 windows server 2019 X3421

### ISSUE THREAD

**Issue by luoxing** [xbmc/xbmc#17585]
### Describe the bug
Here is a clear and concise description of what the problem is:

No video is played after booting, the GPU‘ 3D occupies 100% of a long time until quite Kodi。

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: windows server 2019 datacenter with desktop
 - Kodi version:18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Your issue has been closed as there is no information of any use in your report.

If you are experiencing problems, please raise your question on the Kodi forum.

**Comment by sysdl132** [comment]
![image](https://user-images.githubusercontent.com/54708046/77983731-4c198c80-7342-11ea-9d5a-70433e94721a.png)
please view your license(there is a very tiny problem)

**Comment by DaVukovic** [comment]
Not sure what you are referring to. That's just a template which might get used as a header at the code and then the rest is filled out. So I don't see a problem there.

**Comment by sysdl132** [comment]
> Not sure what you are referring to. That's just a template which might get used as a header at the code and then the rest is filled out. So I don't see a problem there.

I mean,you should fill the license text with your name.Like:
```
Copyright (c) 2020 (your name)
```

**Comment by DaVukovic** [comment]
Yes, if someone uses this license, he can use that as a template and then fill out his name and year. But why should we do that before hand without knowing who and when this license will be used?

I guess you misunderstand the part "template" ;)

But please let's stop that discussion here. It annoys plenty of devs. Please continue this discussion at the forums
