### ISSUE TITLE
CPU usage won't fit the screen

### ISSUE THREAD

**Issue by Sopor** [xbmc/xbmc#17581]
### Describe the bug
Here is a clear and concise description of what the problem is:

When running Kodi in debug mode it would be nice if the CPU's could fit the whole screen. I'm running 1920x1080 and i have 16 logical processors.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix

Make the text wrap to the next row.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/5789283/77859638-db238900-720a-11ea-84f8-3f80dabb3cce.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
related PR:
https://github.com/xbmc/xbmc/pull/14119

**Comment by Sopor** [comment]
@ronie That seems to be almost two years old :(
