### ISSUE TITLE
UPnP / DLNA regression: albumArtURI is pointing to the video rather than the poster image

### ISSUE THREAD

**Issue by sialivi** [xbmc/xbmc#17587]
### Describe the bug
Thumbnails for videos no longer work over UPnP / DLNA. This is a regression, since it works in 18.6.

## Expected Behavior
When viewing the Kodi library on a DLNA client, in my case an LG webOS TV, Kodi is normally using the poster images as the thumbnails.

## Actual Behavior
With Kodi 19 as the DLNA server the thumbnails are missing on the client.

## Possible Fix

I used wireshark to compare the metadata Kodi sends, and for whatever reason Kodi 19 is using the video URI rather than the poster image URI. This was not the case in Kodi 18.

**Kodi 18.6:**
`<upnp:albumArtURI dlna:profileID="JPEG_TN">http://192.168.2.116:1998/%25/4b003382b6490bc3a9682f223e60e683/Fight.Club.1999.1080p.BluRay.X264-poster.jpg</upnp:albumArtURI>`

**Kodi 19:**
`<upnp:albumArtURI dlna:profileID="JPEG_TN">http://192.168.2.116:1889/%25/bc1efdd9cfe15fda86ef87e57f5ed2e4/Fight.Club.1999.1080p.BluRay.X264.mkv</upnp:albumArtURI>`

### To Reproduce
1. Browse the Kodi video library on a DLNA client.
2. Observe the missing thumbnails.

The debuglog can be found here: https://paste.kodi.tv/hadiyutudi.kodi

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64 (10.0.18363.752)
 - Kodi version: 19 (KodiSetup-20200329-e7878130-master-x64)

**Comment by howie-f** [comment]
not sure as i'm not using upnp, maybe s.th. similar to #17487 (fallback) @enen92

**Comment by enen92** [comment]
I know, that's the reason I self-assigned myself to it. Will have a look, but this takes some time (even just to set up a test scenario).
