### ISSUE TITLE
Can't Open ISO

### ISSUE THREAD

**Issue by kalimaenergy** [xbmc/xbmc#17588]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello,
I have issue for opening ISO (4k and 1080p) files from SMB share (Windows Server 2016) with latest build.

Already tested build :

- KodiSetup-20200330 : Issue
- KodiSetup-20200314 : Issue
- KodiSetup-20200311 : Issue
- KodiSetup-20200310 : Issue
- KodiSetup-20200301 : Work

Same error on other computer and on a Android tablet S5E

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

ISO is not open and kodi show error message

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
[kodi01March Build work.log](https://github.com/xbmc/xbmc/files/4408904/kodi01March.Build.work.log)
[kodi10March Build Crash.log](https://github.com/xbmc/xbmc/files/4408905/kodi10March.Build.Crash.log)
[kodi11March Build Crash.log](https://github.com/xbmc/xbmc/files/4408906/kodi11March.Build.Crash.log)
[kodi14March Build Crash.log](https://github.com/xbmc/xbmc/files/4408907/kodi14March.Build.Crash.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![error iso](https://user-images.githubusercontent.com/62940623/78024948-7c205a00-7359-11ea-977f-2427fe1567e9.JPG)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro X64 19041.172 Build (Windows 10 2004/20h1)
 - Kodi version: 19.0
 - AMD Drivers : 20.3.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jjd-uk** [comment]
@lrusak could this have anything to do with your recent changes surrounding the code for ISO handling.

If I've got time later I'll see if I can replicate.

**Comment by DaVukovic** [comment]
Confirmed on Fedora as well: 

debuglog: https://paste.centos.org/view/e31da3ea

**Comment by jjd-uk** [comment]
It seems that the cause has been found, it just needs to be decided how to handle the fix. It might take a few weeks to get this working again in Nightlies.
