### ISSUE TITLE
Split actor's art_urls between movies and tv shows

### ISSUE THREAD

**Issue by IzK666** [xbmc/xbmc#17597]
### Describe the bug

Using a shared url for actor thumbnails makes that the first match is always used (for movies and tv shows).
For movies alone works fine. TMDB uses a single updated photograph of every actor. The worst thing that could happen is showing an old picture from the cache.
But doesn't work for the TVshows. TVDB uses a single photograph for each show, usually in the role or with the aesthetics of the show.
Two examples are [dark crystal](https://thetvdb.com/series/the-dark-crystal-age-of-resistance/people) or [Stranger Things](https://thetvdb.com/series/stranger-things/people).

Now, I have many movies and tv shows portrayed with gelflings and skeksis. Is funny, but useless.

## Actual Behavior

![Equalizer2](https://user-images.githubusercontent.com/2158443/78164991-f7ae0400-744a-11ea-80a7-98cb05d1583a.jpg)
The mandalorian in Equalizer 2
Lucky for me, the skin I use only shows the first 8 actors, which limits these duplicates: Pedro Pascal doesn't appear in the cast of GoT, because he appears on the 25th position.

## Expected Behavior

The thumbs from TMDB should be used only for movies and shared among them (one link for all).
For tvshows, every show should have one single link of each actor.

## Possible Fix

Maybe a quick solution is to create a new column named thumb_url (for example) in actor_link table and store the links only for tvshows and episode (although episodes don't use to have as much information/no information).
For movies keep the actual system inside actor table.

For migration purposes just copy link from actor table to the new actor_link.

### Your Environment
Used Operating system:

 - [X] Raspberry-Pi

 - Operating system version/name:
 - Kodi version: Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
I don't think this is a bug, but more of a feature request.
