### ISSUE TITLE
movieset should have a sorttitle equivalent

### ISSUE THREAD

**Issue by mitchellim** [xbmc/xbmc#17599]
### Describe the bug

Although movies support `sorttitle` for arbitrary sorting, movie sets don't have an equivalent non-visible sortable title. They should, in order to allow for grouping sets of movies in user-desired fashion. For example, keeping the Sam Raimi Spider-Man films as a set separate from the Marc Webb Spider-Man films, but being able to sort them in a specific order. The Star Trek Kelvin timeline movies would be another example.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The Video.Fields.MovieSet JSON schema should have a `sorttitle` (or equivalent) field, and movie sorting by title should sort sets with that string instead.

## Actual Behavior

N/A - feature request

## Possible Fix

Implement a MovieSet `sorttitle` in a similar fashion to the Movie `sorttitle`.

### To Reproduce

1. N/A - feature request

### Debuglog

The debuglog can be found here:
N/A - feature request

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A - feature request

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A - feature request

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by mitchellim** [comment]
I was trying to remove sections that weren't applicable since this is essentially a feature request. I rewrote the ticket with the template (with the inapplicable sections), but it looks like the bot is looking for something very specific.

**Comment by fuzzard** [comment]
Template is as it is because github is just for bug reports.

Feature requests are to be done on the forums https://forum.kodi.tv/forumdisplay.php?fid=9
