### ISSUE TITLE
Master Lock code doesn't work on brand new installation

### ISSUE THREAD

**Issue by xupamisto20** [xbmc/xbmc#17595]
[Kodi bug report.docx](https://github.com/xbmc/xbmc/files/4416375/Kodi.bug.report.docx)

**Comment by DaVukovic** [comment]
Please don't ignore our template and use some paste-service to upload logs.

Beside that, Kodi still locks everything where it should. So I guess you simply did it worng and this is not a support section. This section is for bug-reports. Support will be given at the forums

**Comment by xupamisto20** [comment]
First I didn't ignore the rules! I used the template and uploaded all  
in a Word file.
You just closed the case way too fast without even checking the Word  
file attached.

Secondly, I didn't do nothing wrong! I use Kodi for more then 6 years  
and I'm an IT engineer for almost 30 years, so software and apps  
aren't that new to me... So, stop assuming that everyone is stupid and  
you are some kind of god.

Clearly I'm wasting my time reporting basic bugs that you guys can't  
even find!
Install a CLEAN FRESH copy of Kodi in an Android TV box wand test it  
yourself. I'm out! Sick of Kodi bugs and crashes!
Couldn't care less about it anymore, specially creating accounts to  
report bugs and dealing with idiots!

Cheers
MX

 

Citando DaVukovic <notifications@github.com>:

> Please don't ignore our template and use some paste-service to upload logs.
>
> Beside that, Kodi still locks everything where it should. So I guess  
> you simply did it worng and this is not a support section. This  
> section is for bug-reports. Support will be given at the forums
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or unsubscribe[2].

 

Ligações:
---------
[1] https://github.com/xbmc/xbmc/issues/17595#issuecomment-607349736
[2]
