### ISSUE TITLE
Crash if google services & framework are not enabled

### ISSUE THREAD

**Issue by robo2bobo** [xbmc/xbmc#17590]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have several NVIDIA Shield TV devices and I've removed all google apps, including google play store, google services and google framework.

Unfortunately, Kodi crashes when the services and the framework apps are missing or disabled. The crash happens at random, as if some background process or thread times out and causes the crash. For example, I can start Kodi, move around the UI or just leave it there sitting, eventually it crashes in a few seconds or a few minutes, no need to play a movie.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect Kodi not to crash.

## Actual Behavior

Crash of Kodi and I'm taken back to the android TV launcher.

## Possible Fix

Some apps require google services/framework for some API, like battery usage information, so a fix may require significant changes?

I'd like to mention at this point that if I enable the two google services and framework apps then Kodi does not crash and works smoothly and without problems.

### To Reproduce

1. Go to Apps and disable all google apps, especially services & framework
2. Or use adb to do the same thing
3. Just start Kodi and wait...

Sometimes the crash happens within a few seconds, sometimes it happens after a few minutes. It seems like a background thread or task it running and eventually crashing.

### Debuglog

The debuglog can be found here:

Debug log 1: https://paste.kodi.tv/onixibimij.kodi
Debug log 2: https://paste.kodi.tv/agavuralah.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

not relevant.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

not relevant.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 9
 - Kodi version: 19.0-ALPHA1 Git:20200110-6e017a3044

 - Device: NVIDIA Shield TV

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by I-Cat** [comment]
I am having a hard time finding this build, Can you tell me where you downloaded it from? 
Looks like this apk was built on googlecode okay
The omx.google is SW decoders

anyways the decoders set up is in the;
special://masterprofile/decoderfilter.xml file 
I saw HW decoder of - OMX.Nvidia
So should be easy to set to HW decoders.

If it breaks videos from playing it is possable it is needed for playback due to the encode/decode process

**Comment by robo2bobo** [comment]
I downloaded from:
- go to https://kodi.tv/download
- click android
- click development builds
- click ARMV8A (64BIT)
- I'm redirected to: http://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/

This build was a bit old (from February). So I downloaded and tested with the following builds:
- kodi-20200328-1e627d23-master-arm64-v8a.apk
- kodi-18.6-Leia-arm64-v8a.apk (official Kodi v18.6 Leia)

Same result. When the google services and framework are disabled, kodi crashes. There is no need to play anything, I can just sit in the menu and wait.

I am not sure why you mention the decoders, I am not playing anything, the crash happens anywhere, in the main screen, in the settings, it does not matter. Could you please elaborate?

**Comment by I-Cat** [comment]
Yes The omx.google    software decoder is trying to load because of the xml file.
With out google it crashes because it tried to load some thing that is not there.

**Comment by robo2bobo** [comment]
Ah I see.

Would it be a reasonable thing to ask for someone to implement a change, that makes Kodi ignore the decoder entirely if google services are not enabled/available? for example switch to a different decoder?

Maybe I am a unique case, to run all my android devices without anything by google (well, except Android itself)...

Thank you for taking the time to help and explain, I appreciate it.

**Comment by I-Cat** [comment]
Hi I looked. the core is based off of google, I have something for you tho. 1 question 1st. Is your device rooted or stock?

**Comment by robo2bobo** [comment]
They are all stock.

I am lucky that NVIDIA allows the user to disable all google apps and services (but not to uninstall them). So there has been no need to root them.

Also, I have no plugins installed in Kodi.

**Comment by I-Cat** [comment]
https://anonfile.com/h5n6j0l7oc/YeY._txt

ok you can close as it wont be resolved
I-Cat I-send
u a gift
ttyl

**Comment by robo2bobo** [comment]
Thank you for the gift, appreciated.

**Comment by I-Cat** [comment]
okay ttyl

**Comment by robo2bobo** [comment]
Nobody cares.
