### ISSUE TITLE
Compilation Issue on Raspberry 3

### ISSUE THREAD

**Issue by bmschwa** [xbmc/xbmc#17591]
### Describe the bug

I followed the instructions to compile in the [README.RaspberryPi.md](https://github.com/xbmc/xbmc/blob/master/docs/README.RaspberryPi.md) file.  In section 3.1 of the document, the instructions to get the tools are 
```
git clone https://github.com/raspberrypi/tools --depth=1
```

However during the build process we find that $HOME//tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc does not work.  When I invoke that gcc alone, I get 

```text
/home/pi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc: cannot execute binary file: Exec format error
```

## Expected Behavior

Kodi compiles without issues.

## Actual Behavior

Cannot compile

## Possible Fix

- Modify the docs to let us know where we should find the correct toolchain
- Where can we get a version of arm-linux-gnueabihf-gcc / complete toolchain 

### To Reproduce

Just follow the instructions for the raspberry compile

### Debuglog
The debuglog can be found here:

From build/CMakeFiles/CMakeError.log:

```
Compiler: /home/pi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ 
Build flags: -fPIC;-mcpu=cortex-a7;-mfloat-abi=hard;-mfpu=neon-vfpv4;-mvectorize-with-neon-quad;-pipe;-mabi=aapcs-linux;-Wno-psabi;-Wa,-mno-warn-deprecated;-Wno-deprecated-declarations;-isystem/home/pi/firmware/opt/vc/include;-isystem/home/pi/firmware/opt/vc/include/interface/vcos/pthreads;-isystem/home/pi/firmware/opt/vc/include/interface/vmcs_host/linux;-DNDEBUG=1;-Os;;;-isystem;/home/pi/kodi-rpi/raspberry-pi2-release/include
Id flags:  

The output was:
2
/home/pi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++: 1: /home/pi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++: ^?ELF^B^A^A^B: not found
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
 N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspberry Pi 3
```
uname -a
Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
```
 - Kodi version: 18.6-Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by howie-f** [comment]
you're trying to build natively on rpi3. the mentioned guide is used for crosscompiling.
`This guide has been tested with Ubuntu 16.04 (Xenial) x86_64 and 18.04 (Bionic). It is meant to cross-compile Kodi for the Raspberry Pi`
you should use a ubuntu-vm as building native would take ages :)

**Comment by DaVukovic** [comment]
I guess we can savely close this one now.
