### ISSUE TITLE
Missing audio language code "gsw"

### ISSUE THREAD

**Issue by PeterCodar** [xbmc/xbmc#17604]
### Describe the bug
In the file https://github.com/xbmc/xbmc/blob/master/xbmc/utils/LangCodeExpander.cpp the language code "gsw" Schweizerdeutsch | Swiss German; Alemannic; Alsatian | Schwiizerdütsch is missing. 

## Expected Behavior
If I load a multi-language MKV file - including an audio stream with "gsw" set - I would like to see "Schweizerdeutsch" or "Swiss German" as language, not "undefined".

## Actual Behavior

gsw will not be recognized as official valid code from https://de.wikipedia.org/wiki/Liste_der_ISO-639-2-Codes. KODI display such audio streams as "unknown".

## Possible Fix

Add "gsw" to https://github.com/xbmc/xbmc/blob/master/xbmc/utils/LangCodeExpander.cpp in the range lines 900-905

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 9.2.2 (Leia)
 - Kodi version: v18.6

**Comment by DaVukovic** [comment]
Well, as that seems to be a one-liner, why haven't you created a PR yet? ;)

**Comment by PeterCodar** [comment]
Because I have no idea how to do that. Sorry.

**Comment by MediaBrasil** [comment]
Check the comments in the issue 15308, similar, before the team doesn´t accept changes here..

https://github.com/xbmc/xbmc/issues/15308
