### ISSUE TITLE
Video sources ordered by date shows all files with 01-03-1601 date

### ISSUE THREAD

**Issue by thexai** [xbmc/xbmc#17607]
### Describe the bug
Here is a clear and concise description of what the problem is:

Current alphas Kodi 19 shows incorrect date '01-03-1601' in some places:

![Anotación 2020-04-03 151240](https://user-images.githubusercontent.com/58434170/78366544-f0106b80-75c0-11ea-84b6-4ed21a7e1d47.png)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Real item added date should be shown.

## Possible Fix

Previous alphas from 18 Feb are OK.

### To Reproduce

Open video sources from  Videos / Media sources (not from movies) and sort list by date. All dates are 01-03-1601.
Same opening from Settings / Media / Library / Videos.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/4427571/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Running on Windows 10, kernel: Windows NT x86 64-bit version 10.0.18363

 - Kodi version:
Kodi (19.0-ALPHA1 Git:20200402-76a8d61325)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
The log is no good.

How did you populate the library- Kodi scraper or NFO files? If NFO files, please post the contents of one to paste.kodi.tv/ and provide the link.

**Comment by DaVukovic** [comment]
Tested on Linux and can't reproduce. 
I went to "video"->"files"->one of my sources and sorted by "date" order "ascending":

![image](https://user-images.githubusercontent.com/7235787/78376838-28b74180-75cf-11ea-9502-65cfa97d4e01.png)

Fine for me. 

If I use my library all is fine as well. As that date shouldn't be related to the library at all. This date comes from your filesystem. Compare that from the screenshot above:

![image](https://user-images.githubusercontent.com/7235787/78377272-b561ff80-75cf-11ea-9a9b-87aaa8b6530b.png)

So please check the date on your filesystem

**Comment by thexai** [comment]
> How did you populate the library- Kodi scraper or NFO files?

Kodi scraper

**Comment by thexai** [comment]
> Tested on Linux and can't reproduce.

Because bug is on Windows build :)

**Comment by KarellenX** [comment]
I can also replicate this issue and I am using an older build compiled 2020-03-12. It is not apparent until you change the sort by method to Date.

![1601](https://user-images.githubusercontent.com/44626605/78378638-f5030880-761c-11ea-9f48-778648341059.jpg)

**Comment by thexai** [comment]
Uninstalling (preserving data) and installing previous alpha e.g. 18-feb the problem disappears.

**Comment by scott967** [comment]
Also on Win x64 0327 nightly ListItem.Date infolabel provides bad data for files in local Win 10 1903 NTFS file system.  But sometimes it shows 01/03/1601, other times 49/00/16712 so that may give some idea what is going on here.  Went back to 0303 nightly, that one's giving me 5923/00/0 and 01/02/1601.  I then went back to the 0101 nightly which is sort of my sanity checker, and ListItem.Date seems good there.

scott s.
.

**Comment by djp952** [comment]
I hope I'm not overstepping, but I saw this Issue and thought it would be pretty easy to replicate and fix, and have issued a PR to correct it: PR [17625](https://github.com/xbmc/xbmc/pull/17625) - "[Windows] Correction to Windows date/time calculations after PR 17358".  

It appears to have been the result of a simple typographical error.

**Comment by KarellenX** [comment]
Thank you @djp952

**Comment by thexai** [comment]
I confirm that works fine.

Patch included in latest HDR compilation:

http://www.mediafire.com/file/ycgbqdcnhq7jg3u/KodiSetup-20200406-07fc3236-Windows-HDR-x64.exe/file

Thanks you @djp952 for investigate it.
