### ISSUE TITLE
Notify other Kodi about new media

### ISSUE THREAD

**Issue by GiganteX** [xbmc/xbmc#17601]
I am running Kodi on Windows, with a MySQL DB on a separate machine.
I sit at my computer, adding movies and doing maintenance work and such.

Then I go to my movie room, where I have another Windows computer connected to my projector. Kodi is running there too, connected to the same MySQL DB of course.

But when I add a movie at my computer, the Kodi in my movie room isn't updated.

It isn't made aware of the new media, and it won't bother to refresh from the database until it is restarted.

When media is added, please notify my second Kodi so that it properly displays the new media without a restart!

**Comment by KarellenX** [comment]
Please do not use this section for support or feature requests. Use the forum.
