### ISSUE TITLE
Addons wont work (retrospect and youtube)

### ISSUE THREAD

**Issue by faltaren** [xbmc/xbmc#17615]
### Describe the bug
Here is a clear and concise description of what the problem is:

Addons wont start. I get an error check log. Both retrospect and youtube. Worked fine a week ago.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Addons should start

## Actual Behavior

Error check log. Addon wont start

## Possible Fix

Dont know

### To Reproduce

1. Start kodi
2. start addon
3.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/4433709/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ x] Windows 10
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
out of curiousity...does it work if you select english as the Kodi language?

**Comment by faltaren** [comment]
I always have english :)

**Comment by basrieter** [comment]
Could it be that your `chardet` package got corrupted?

**Comment by faltaren** [comment]
Whats that? I did a clean install. Same problem.

**Comment by basrieter** [comment]
> Whats that? I did a clean install. Same problem.

Can you zip the `script.module.chardet` folder from your add-on folder `C:\Kodi18\portable_data\addons\`

**Comment by faltaren** [comment]
[script.module.chardet.zip](https://github.com/xbmc/xbmc/files/4438357/script.module.chardet.zip)
Here you go

**Comment by ronie** [comment]
i suspect a corrupted chardet installation as well.

can you delete this file:
C:\Kodi18\portable_data\addons\script.module.chardet\lib\chardet\langhebrewmodel.pyo

judging by it's filesize & creation date i think it's borked.

**Comment by faltaren** [comment]
F*ck me it worked. Fixed my problem with tvmaze and vfs rar to. Ho did you know that 💪

**Comment by basrieter** [comment]
Good to hear that.
