### ISSUE TITLE
CEC suspends source while browsing Kodi menus

### ISSUE THREAD

**Issue by Janhouse** [xbmc/xbmc#17628]
Whenever I have something playing in Kodi and I start browsing menus, my TV video source gets suspended after a few minutes (and switches from HDMI to TV), while Kodi keeps running.

It doesn't happen when nothing is playing.

If I get out of the menus in time back to the content that is playing, it works fine.

I have Pulse-Eight USB CEC adapter, so that is the only thing that comes to my mind that could do this. But for it to do this, it must get some command from Kodi.

Could someone else please check if you get the same problem?

I'm running Archlinux with Kodi 18.6, but I have had this problem for some time now.

**Comment by Janhouse** [comment]
I'd rather live with this bug than fill out that stupid template. :laughing:

**Comment by phunkyfish** [comment]
The template is there for a reason. For instance, a debug log which would help anyone trying to resolve this.

BTW, you can configure many CEC options if you edit the input adapter in kodi settings.

**Comment by Janhouse** [comment]
That is the thing. I have already configured the adapter to do nothing.

I'll try to find that moment in the logs.

**Comment by phunkyfish** [comment]
But don’t just post a log snippet. The full debug log (From boot) of it happening will be needed.

It would also help if you could screenshot your CEC settings. Then we could try and reproduce. It may just be your CEC device and maybe it’s more widespread. We don’t know yet.
