### ISSUE TITLE
Low-Res netflix streams have green and purple lines

### ISSUE THREAD

**Issue by emc02** [xbmc/xbmc#17647]
### Describe the bug
Here is a clear and concise description of what the problem is:
Some Streams (I guess the ones with low resolution) result in a bad image with green and purple colors. High resolution content works fine

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
good picture quality
![IMG_20200410_114109 (Groß)](https://user-images.githubusercontent.com/5359218/78988939-877e3d00-7b32-11ea-8d1d-65d13903b11a.jpg)

## Actual Behavior
bad image with green and purple colors on some streams
![IMG_20200410_114026 (Groß)](https://user-images.githubusercontent.com/5359218/78988953-8f3de180-7b32-11ea-8501-8af1bacaeb08.jpg)

## Possible Fix
set max. stream resolution lower than 1080p in netflix plugin (but then you have to switch this every time you want to watch high-res content)

### To Reproduce
1. set max. stream resolution to 1080p
2. open stream in netflix (or maybe any other similar stream provider) like "Trotro" or "Star Trek - Next Generation"
3. see bad image (see attachement)

### Debuglog
[kodi.log](https://github.com/xbmc/xbmc/files/4461410/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:
see above

### Your Environment
 - Operating system version/name: LibreElec 9.2.2 on Raspberry Pi 4

#### Other information
The issue is not present on Windows 10 platform

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lslomczynski** [comment]
Hello, I just want to confirm that I have the same issue. Similar reports were made in CastagnaIT's GitHub, but he marked them as Plugin-independant, as "audio/video streams are handled by Kodi core".

**Comment by lrusak** [comment]
> Hello, I just want to confirm that I have the same issue. Similar reports were made in CastagnaIT's GitHub, but he marked them as Plugin-independant, as "audio/video streams are handled by Kodi core".

@lslomczynski Are you using an RPi4 as well?

**Comment by lslomczynski** [comment]
> @lslomczynski Are you using an RPi4 as well?
@lrusak: that is right, Sir.
    Netflix add-on version: 1.1.1
    Operating system version/name: Raspbian GNU/Linux 10 (buster)
    Device model: Raspberry Pi 4 / 4GB
    Kodi: 18.6

I encountered it first few days ago while watching "Casa del Papel".
S01E01 - no issues, all subsequent ones with distorted colours 
S02E01 - no issues, I didn't check the rest.

I also saw similar ticket for FireTV: https://github.com/CastagnaIT/plugin.video.netflix/issues/505 
If I can be useful in any means for diagnosis please let me know and I'll try to do my best :-)

**Comment by matthuisman** [comment]
maybe related to my (Kodi 19: Ffmpeg selects lowest quality stream by default (instead of highest):
https://github.com/xbmc/xbmc/issues/17664

**Comment by emc02** [comment]
> I also saw similar ticket for FireTV: [CastagnaIT/plugin.video.netflix#505](https://github.com/CastagnaIT/plugin.video.netflix/issues/505)
> If I can be useful in any means for diagnosis please let me know and I'll try to do my best :-)

That was my ticket too ;-)
I don't know to what part of Kodi or the Addon it's related, but the bug is definitely there.
Is the bug not present on RPi3?!

Maybe someone else can confirm, or I can test it the next days, because I have a RPi3 here, but without Kodi on it.

**Comment by quietvoid** [comment]
I have opened https://github.com/xbmc/xbmc/issues/17451 for the Netflix Dolby Vision ticket.
Not related to stream resolution though, so this issue is not really related.

**Comment by popcornmix** [comment]
Yes, two issues look unrelated to me (very different forms of corruption).

Could someone with the Pi4 issue check with a [milhouse nightly](https://forum.kodi.tv/showthread.php?tid=343068) build? The decode/rendering path is quite different so there's a good chance the issue won't occur.

Note: Matrix builds moving to python 3 means a number of addons won't work, but netflix should be working. Might be best to test on a separate sdcard.

**Comment by emc02** [comment]
> Could someone with the Pi4 issue check with a [milhouse nightly](https://forum.kodi.tv/showthread.php?tid=343068) build? The decode/rendering path is quite different so there's a good chance the issue won't occur.

Is libreelec at the same level with nightlys, or what would be the best OS on Pi4 to test latest kodi nightly?

**Comment by emc02** [comment]
> Could someone with the Pi4 issue check with a [milhouse nightly](https://forum.kodi.tv/showthread.php?tid=343068) build? The decode/rendering path is quite different so there's a good chance the issue won't occur.

Will test it tomorrow and report here!

**Comment by teiafra** [comment]
Same weird colors also on kodi AmazonVod. Some movies are good, some others look like that picture.
More details here [https://forum.kodi.tv/showthread.php?tid=352844] (https://forum.kodi.tv/showthread.php?tid=352844)

**Comment by emc02** [comment]
> Will test it tomorrow and report here!

- I've tested it on RPi3 and it works.
- Tested on a fresh install on RPi4 with Libreelec 9.2.1 shows the ugly picture
- Latest Milhouse build disables netflix and Version 1.1.1 can't be installed yet. Latest daily build is also outdated, so I've to wait till a new version of netflix-plugin is available

Will report here again!

**Comment by emc02** [comment]
Can confirm: on Milhouse-nightly #0412, 12-Apr-2020 with latest netflix-matrix-plugin it works fine!

I guess this will not be backported and we have to wait for v19 in Libreelec to get this fixed?! So this issue can be marked as solved in v19.

**Comment by teiafra** [comment]
What fix for Kodi Leia 18.6 on Raspbian (so not LibreElec) and AmazonVod add-on?

**Comment by emc02** [comment]
> What fix for Kodi Leia 18.6 on Raspbian (so not LibreElec) and AmazonVod add-on?

Let me explain what I think about: The issue depends on some "inputstream.adaptive"-plugin or something like that, that is needed for netflix and amazonVOD and many other streaming-plugins. The issue is solved in the next major version of Kodi (v19) (I've tested with the newest testbuild of libreelec which uses the testbuilds of Kodi) and I because of the huge changes from Kodi v18 to v19 I don't think this issue can be backported to v18, so I guess we will have to wait till v19 to get this issue solved.

**Comment by teiafra** [comment]
Clear, thanks a lot.
Yes I guess it's something in IS.A, not AmazonVod or Netflix add-on per se.
Let's hope in the major upgrade

**Comment by autagi** [comment]
> 
> 
> Same weird colors also on kodi AmazonVod. Some movies are good, some others look like that picture.
> More details here [https://forum.kodi.tv/showthread.php?tid=352844] (https://forum.kodi.tv/showthread.php?tid=352844)

I have the same problem

**Comment by teiafra** [comment]
No workaround possible???

**Comment by w1k1n9cc** [comment]
I have the same issue with the Amazon VOD plugin and a raspberr pi 3. I have it only with some movies and if it happen with a series then a reboot helps.
I encountered this issue since the update of the latest kodi version. With the milhouse version before the python3 change was done, everything works well for me.

**Comment by kolAflash** [comment]
I'm having the same issue with Netflix.

I use Kodi-18.7 via LibreELEC-9.2.3 on a Raspberry Pi 4 (4 GB) and a TV connected via HDMI adapter.

Seems to happen for the remastered "Star Trek" shows "TOS" (original series) and "TNG" (The Next Generation).
 
My workaround:
Netflix Add-On settings > Expert > InputStream Adaptive > Stream selection: manual video
(translated from German ui)
Then select the low resolution (576x432) in the settings when watching Netflix.

**Comment by wilc0x** [comment]
I am seeing this issue with Kodi 18.7/LibreELEC-9.2.3 on a Pi 4 when playing certain low res streams (576x432) of Star Trek DS9 through CastagnaIT's Netflix plugin.  Most episodes are fine, but the episodes that have the issue have it every time and I have not found a workaround.  They appear in black and white with strange pink and green shadows, and sometimes also with solid vertical green bars on the right side of the screen.

**Comment by MarcT** [comment]
I recently ran in to this issue on LibreELEC-9.2.3 with Kodi 18.7 also on a Pi 4 when I saw my kids watching the Avatar the Last Airbender cartoon. It only affects older TV shows that are in 4:3, but some shows, like DS9, it does not happen every season.
Shows in 4:3 with the issue:
- Avatar The Last Airbender
- Star Trek: TOS
- Star Trek: TNG
- Star Trek: DS9 (seasons 1 - 5 only, for some reason season 6 and 7, while still 4:3, are working)
- Danger Mouse classic cartoon

**Comment by ScorpioBroker** [comment]
Hi,
Had the same problem with TNG on a Pi4/3. Enabling VP9 profiles in the netflix add on settings (expert settings) solved it for me for TNG.
LE 9.2.6

Cheers

**Comment by djraw** [comment]
If anyone else has this problem on a Pi4 and LibreELEC (as I did)..
Downgrade to LE 9.2.0 (Kodi18.5) and everything works like a charm again.

**Comment by CastagnaIT** [comment]
Someone have this problem on Kodi 19 and/or last LibreELEC 10 (Matrix) ?

otherwise this issue will be closed since no fixes will be done on Kodi 18
