### ISSUE TITLE
Kodi YouTube Addon throws Error

### ISSUE THREAD

**Issue by SubZero5** [xbmc/xbmc#17653]
### Describe the bug
Here is a clear and concise description of what the problem is:

I open the YouTube addon and sometimes when I try to enter My Subscriptions and osmetimes (as now) I want to browse the Page (2) of my subscription, the YouTube Addon gives up and Error and the list fails to open.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect it to list some content

## Actual Behavior

It stays as if I never clicked on the menu item.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/datifoqeyi.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Please use the forum for plugin related issues: https://forum.kodi.tv/showthread.php?tid=353278&page=166

cc @anxdpanic
