### ISSUE TITLE
Kodi 19: Ffmpeg HLS selects lowest quality stream by default (instead of highest)

### ISSUE THREAD

**Issue by matthuisman** [xbmc/xbmc#17664]
### Describe the bug

When playing a HLS stream, ffmpeg chooses the lowest quality by default instead of the highest quality. 

In Kodi 18 - the highest quality is correctly chosen. 

All kodi settings are default (including bandwidth limitation)

## Expected Behavior

FFMPEG chooses the highest quality stream

## Actual Behavior

FFMPEG chooses the lowest quality stream

### To Reproduce

1. Download [test.strm.txt](https://github.com/xbmc/xbmc/files/4465805/test.strm.txt)
2. Rename it to test.strm
3. Play it in Kodi
4. Observe quality is 320x180 instead of highest 1920x1080

### Debuglog

The debuglog can be found here:
https://pastebin.com/t0DxXAJW

### Screenshots 
Here are some links or screenshots to help explain the problem:

Kodi 18 - selects highest
![screenshot001](https://user-images.githubusercontent.com/6225961/81230833-4ea88980-9046-11ea-84ea-3cd4ffc975b3.png)
Kodi 19 - selects lowest
![screenshot000](https://user-images.githubusercontent.com/6225961/81230838-4fd9b680-9046-11ea-828b-7e73a738c051.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows X64
 - Kodi version: Latest 19 Nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jaylinski** [comment]
Maybe @FernetMenta can help out?

https://github.com/xbmc/xbmc/blame/master/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp#L2025-L2080

Do you use a inputstream addon?

**Comment by matthuisman** [comment]
The test strm above is not using Inputstream.
Just directly via Kodi ffmpeg.

Had added some screenshots showing the Select Program dialog after playback in 18 & 19.

Also, in 19 playing a strm via file-manager doesn't make it go full screen when played...
It just starts playback in the background

**Comment by FernetMenta** [comment]
> Maybe @FernetMenta can help out?
> 
> https://github.com/xbmc/xbmc/blame/master/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp#L2025-L2080
> 
> Do you use a inputstream addon?

https://github.com/FFmpeg/FFmpeg/commit/abfeba97241e3cd485580b66b8b712d9a9779888

**Comment by jaylinski** [comment]
@FernetMenta Thanks for your help! Will you open a PR? (Otherwise I will do)

Corresponding code in Kodi: https://github.com/xbmc/xbmc/blob/66bb80a81866b24b0883d555976db811b2aa3424/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp#L591-L594

**Comment by FernetMenta** [comment]
> Will you open a PR?

probably not :)

**Comment by matthuisman** [comment]
i assume this is the fix (just waiting on a build)
https://github.com/xbmc/xbmc/commit/e65eb6bd82f8323da38fcc56a1c27654eb255f2e

**Comment by matthuisman** [comment]
fixed with https://github.com/xbmc/xbmc/pull/17816
