### ISSUE TITLE
Kodi fails to load Euronews HLS stream (Kodi 18.6)

### ISSUE THREAD

**Issue by ksl1989** [xbmc/xbmc#17672]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi can't load the m3u8 link from the Euronews public API.

To get a link please access `https://www.euronews.com/api/watchlive.json`, there will be a 'url' key with the URL to a second .json file (missing "http:"). This .json file will have a 'primary' and a 'backup' keys with a link to a .m3u8 file as value. Any of these links should work.

An example:
```
{
  "status": "ok",
  "protocol": "hls",
  "primary": "http://euronews-en-p13-cdn.hexaglobe.net/4c7cf9759a8e0112c1a52cbe77979539/5e9460d0/euronews/euronews-euronews-website-web-responsive-2/ewnsabren_eng.smil/playlist.m3u8",
  "backup": "http://euronews-en-b13-cdn.hexaglobe.net/4c7cf9759a8e0112c1a52cbe77979539/5e9460d0/euronews/euronews-euronews-website-web-responsive-2/ewnsabren_eng.smil/playlist.m3u8"
}
```

Please get new links to test.

I can open these links in VLC, ffplay, and Firefox ( with the Native MPEG-Dash + HLS Playback add-on) but Kodi always fails after loading for a few seconds. At first I was trying on my Raspberry Pi with OSMC, but I installed Kodi on my Manjaro laptop to test and had the same result.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should be able to play this stream.

## Actual Behavior

Kodi fails to play this stream.

## Possible Fix

Wish I knew.

### To Reproduce

1. Get the link as described above.
2. Open in Kodi.
3. Watch it loading and failing

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/4469585/kodi.log)

This log shows:
1. Opening an HLS stream known to work in Kodi to confirm there there is no connection issue (with kodi-send). It works and I close it after a few seconds.
2. Opening the Euronews primary link. It fails.
3. Opening the Euronews backup link. It fails.

CURL and ffmpeg logging is enabled.

I the opened these links on VLC to confirm the stream wasn't to blame. It played without any issue.

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Manjaro (rolling distro, up to date) x86 64-bit / OSMC 2020.03-1, 32bit ARM
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
Works for me with the current master and 18.6.

**Comment by ksl1989** [comment]
I have retried this and it's working for me as well now. But I did try repeatedly for maybe a week and it wasn't. 

I guess this issue can be closed, it must have been an issue in the server side, even if it was working for other players.
