### ISSUE TITLE
Subtitle icon always visible even if no subtitles are enabled

### ISSUE THREAD

**Issue by Sopor** [xbmc/xbmc#17674]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing a video there are two symbols that show the sound and subtitle languages. In Kodi 18.x it is now showing the subtitle language even if the subtitles are not enabled. This is the only way to quickly see if the subtitles are enabled or disabled, but now that isn't possible anymore because this symbol is always there when a video has subtitles.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No subtitle symbol when subtitles are disabled.

## Actual Behavior

The subtitle symbol is always visible.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/5789283/79168689-ce965780-7dea-11ea-83e7-c1bbb693b7aa.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
judging by the screenshot it's not the Estuary or Estouchy skin.
as such we can not fix the issue.

you'll have to report this to the author of the skin you're using.
