### ISSUE TITLE
v19 - First video bookmark has negative number timestamp

### ISSUE THREAD

**Issue by nonJon** [xbmc/xbmc#17681]
### Describe the bug
Here is a clear and concise description of what the problem is:

Chapter 1 video bookmark sometimes presents with a negative number (e.g., -00:05:15) and is unusable.  Selecting it does nothing.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Chapter 1 bookmark should have timestamp 00:00:00 and go to beginning of video when selected.

### To Reproduce

1. Play video 
2. Call bookmarks dialog
3.

### Debuglog

The debuglog can be found here: https://pastebin.com/E83SSA8n

### Screenshots 
Here are some links or screenshots to help explain the problem:

![bookbug2](https://user-images.githubusercontent.com/21987082/79320596-a896b300-7ecf-11ea-9fbe-78f741adafbd.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Issue is present in all available nightly builds.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by nonJon** [comment]
Issue updated to comply template rules.  Please remove ignored rules label.  thx

**Comment by DaVukovic** [comment]
Obviously Kodi shows correctly what's fetched from the file: 

```
2020-04-15 04:33:38.198 T:9632    INFO: ffmpeg[0x1fe75b04070X]:     Chapter #0:0: start -315.815567, end 0.000000
2020-04-15 04:33:38.198 T:9632    INFO: ffmpeg[0x1fe75b04070X]:     Metadata:
2020-04-15 04:33:38.198 T:9632    INFO: ffmpeg[0x1fe75b04070X]:       title           : Chapter 1
2020-04-15 04:33:38.198 T:9632    INFO: ffmpeg[0x1fe75b04070X]:     Chapter #0:1: start 0.000000, end 206.758600
2020-04-15 04:33:38.198 T:9632    INFO: ffmpeg[0x1fe75b04070X]:     Metadata:
```

Chapter 1 starts at a negative timestamp. That's simply what Kodi displays. So Kodi, in that case, does everything correct, no?

Tbh, I see an issue with the video as it doesn't make any sense to have a chapter which starts with a negative timestamp

**Comment by nonJon** [comment]
Yeah, after a bunch of testing it's pretty clear to me that older versions of handbrake had issues with chapter stops so kodi is somewhat off the hook.  That said. leia handles this much more gracefully.

Same movie on v18.  Negative timestamp is zeroed and the bookmark also works..
![screenshot000](https://user-images.githubusercontent.com/21987082/80246539-32622100-8632-11ea-8dc5-90c56b8099b3.png)

I wonder why this would be.  Did some range checking get regressed out of the code?

**Comment by DaVukovic** [comment]
My testing above was done on v19. So, if v18 does it different, then I guess there also was some fix in ffmpeg which might be causing this. Maby ffmpeg didn't recongnize it before.

Anyway. For what I can tell, there's still no issue with Kodi. So I would close this ticket if you agree.
