### ISSUE TITLE
Kodi crashes on click "Active" button under Wireless Networks

### ISSUE THREAD

**Issue by EmeEleonu** [xbmc/xbmc#17696]
### Describe the bug
Here is a clear and concise description of what the problem is:

KODI crashes immediately I click on the "Active" button to activate Wifi network under the Wireless Networks in LiberELEC settings window. My build is a fresh install of LiberELEC OS running on a Rasberry Pi3 without Network Port. Install is stable with a LibreELEC(Official) distribution. Version 9.2.0 running on a Linux 4.19.83 Kernel.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

From System Settings - LIBREELEC - Network - Wireless Networks 
As expected, clicking on the Active or the directly at the button should enable/activate the system to be able to search and list all available WIFI Networks and Hotspots around. These Hotspots should then be available under the connections Tab. 

## Actual Behavior

KODI crashes immediately I click on the "Active" button to activate Wifi network under the Wireless Networks in LiberELEC settings window.

### To Reproduce

1. From KODI Home page 
2. Select the Settings Icon at the tope left corner (the Gear Icon)
3. In the System Settings page click on "LibreELEC" at the bottom of the page
4. On the left pane, select "Network"
5. In the Right pane, under "Wireless Networks" click on "Active" or Directly at the button on the right
6. Pi Resets instantly and Reboots

### Debuglog

The debuglog can be found here:

The Log files simply says 
Kodi Successfully Started 11-042019 17:30:18
Kodi has been successfully stated.

### Screenshots 
Here are some links or screenshots to help explain the problem:

I have no screen shots except the picture of my Pi. looks like it will need to be copied into a browser cos its not displaying. Its a Raspberry Pi 3 Model A+
[https://a.pololu-files.com/picture/0J7010.1200.jpg](url)
## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I am unable to use my installation, though the system is installed, I am unable to connect or access it remotely or even upload media to it. I have tried unsuccessfully to get it to work, that's why I am trying this medium. I am sorry if the solution is trivial, I have tried several solutions without luck.

### Your Environment
Used Operating system:

 - [X ] Linux
 - [ X] Raspberry-Pi

 - Operating system version/name: LibreELEC (official) 9.2.0 (kernel: Linux 4.19.83
 - Kodi version: 18.5 Git: newclock5_18.5-Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MilhouseVH** [comment]
Closing this, for a few reasons:

* You haven't submitted any logs, as instructed (doing so would have been extremely useful)
* Problems with wifi networking and/or LibreELEC Settings add-on is an OS issue, not a Kodi issue. As such, you should open an issue on the [LibreELEC forum](https://forum.libreelec.tv/board/8-general-support/)
