### ISSUE TITLE
Proxy settings are not considered or http header information are not send through proxy

### ISSUE THREAD

**Issue by GitHubMyHub** [xbmc/xbmc#17709]
### Describe the bug
Here is a clear and concise description of what the problem is:

Proxy (Socks4) settings are not considered when using a Stream url or http header information are not send through the proxy.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

See the video playback.

## Actual Behavior

Stream doesnt start.

### To Reproduce

1. Set Proxy type to Socks4
2. Set ip adress  to 213.58.196.146
3. Set port to 61221

### Debuglog

The debuglog can be found here:
https://gist.github.com/GitHubMyHub/513acd98d64f0a827868fdd4232cd1b3

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.6 Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by phunkyfish** [comment]
Please post your log using a paste site or a gist. Straight posting in an issue makes it unreadable.

**Comment by phunkyfish** [comment]
Note that M3U8 streams are handled by FFmpeg and so will only support a http proxy as far as I'm aware.

**Comment by GitHubMyHub** [comment]
@phunkyfish
Thanks for your reply. I posted my log into gist now.
Good to know that. Unforunatly I have no experience in that subject to contribute something.
But I looked into Stackoverflow and found this: https://stackoverflow.com/questions/22098045/ffmpeg-socks4-proxy-parameter-with-rtmp
Is this a sign it might work?

**Comment by phunkyfish** [comment]
That seems to be specific to `rtmp` streams. You are using `http` so I don't think so.

**Comment by GitHubMyHub** [comment]
But Kodi runs in front of FFmpeg right or does FFmpeg manage his own internet connections? Sry Im just curious. ^^

**Comment by phunkyfish** [comment]
Yes it does but there are some streams that it handles directly. HLS (m3u8), rtp, rtsp are examples of those.

For these special streams where kodi doesn’t have to do anything extra there is only an http proxy to configure. There is no way to configure a socks proxy.

When kodi reads a stream internally using curl it can support the full set of proxies (because curl does).

**Comment by GitHubMyHub** [comment]
Thanks for the explanation. What a pitty it doesnt work as I desired.^^
It might be something it could be implemented, if it is possible.
Why someone should use only internal proxies. This features should also be available outside if requested by the user. Otherwise it would be a little missleading to the users.

**Comment by phunkyfish** [comment]
This is feature request to make of FFmpeg. Once they support it we can also support it.

Your other option is to configure your machine to use a proxy, i.e. not kodi, the entire PC/laptop. This way it's doesn't matter if it's kodi or ffmpeg they will all use it and won't be aware they are.

**Comment by GitHubMyHub** [comment]
Yes I already thought about it. I only have to find the appropriate Software to do only the kodi routing not the complete system. And maybe platform indepentend would be nice.

**Comment by DaVukovic** [comment]
Can we close this issue then?

**Comment by phunkyfish** [comment]
Yes, can only be fixed by ffmpeg.
