### ISSUE TITLE
ARM version missing on flathub

### ISSUE THREAD

**Issue by cintema** [xbmc/xbmc#17700]
### Describe the bug
Here is a clear and concise description of what the problem is:

                     flatpak install flathub tv.kodi.Kodi 

does not find any matches on flathub
### Provide a more detailed introduction to the issue itself, and why you consider it to be a bug 
According to https://github.com/flathub/tv.kodi.Kodi/blob/master/flathub.json, the flatpak release of Kodi is limited to x86 and amd64.
### Put your text below this line 
I consider this a bug since the ARM release seems to be intentionally missing on flathub.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should be installed 

## Actual Behavior

Kodi is not installable

## Possible Fix

Put the ARM version on flathub

### To Reproduce

1.Attempt to install the ARM release from flathub
2.Observe the error message that no matching packages were found
3.Write a bug report on github

### Debuglog

The debuglog can be found here:
Not necessary, I presume

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://github.com/flathub/tv.kodi.Kodi/blob/master/flathub.json

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I cannot use Kodi on my Gemini PDA but I would like to.
### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux Sailfish 3.18.41 #1 SMP PREEMPT Mon Jun 3 09:10:16 UTC 2019 aarch64 GNU/Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Jolla SailfishOS Rokua 3.3.0.14 
- Kodi version:
19.08

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
We don't supply official flatpak releases.
