### ISSUE TITLE
Kodi's proxy settings don't work

### ISSUE THREAD

**Issue by xmha97** [xbmc/xbmc#17729]
Hello Kodi team.
Do Kodi's proxy settings work?
I want to use a proxy for addons (for example YouTube)
![Kodi](https://user-images.githubusercontent.com/23485114/79966504-c43b2400-84a2-11ea-8433-849d7d3c7ee7.png)
I using Shadowsocks.
Please fix this issue.
Thanks.

**Comment by phunkyfish** [comment]
You need a attach a full debug log of the proxy not working.

Also, does the YouTube addon use an inputstream addon?

**Comment by enen92** [comment]
Kodi addons implement their own clients using their own libraries, so it ends up to be the addon developer responsibility to get kodi settings and passing the proxy configurations. I'd suggest you bring this to the developer of the addon

**Comment by xmha97** [comment]
Ok, I send the log file.

![Screenshot (13)](https://user-images.githubusercontent.com/23485114/79976189-72e66100-84b1-11ea-8a32-ff5f69f85067.png)

See [kodi.log](https://github.com/xbmc/xbmc/files/4515751/kodi.log)

(YouTube is blocked in my country, so I want to use a proxy.)

**Comment by xmha97** [comment]
> 
> 
> Kodi addons (at least python ones) implement their own clients using their own libraries, so it ends up to be the addon developer responsibility to get kodi settings and passing the proxy configuration before actually doing the requests. I'd suggest you bring this to the developer of the addon

Ok, I asked the developer of this plugin about this problem and I am waiting for the answer.
https://github.com/jdf76/plugin.video.youtube/issues/795

**Comment by chewitt** [comment]
I'm closing this ticket because there is no bug and user help is done via the forums. That said, how to bypass geoblocks isn't something you'll get much help with in the forums, as it's not a topic we encourage, and any threads that do appear are a magnet for people trying to spam the forum with adverts for their VPN services.
