### ISSUE TITLE
Kodi can't stream any video and crashes all the time

### ISSUE THREAD

**Issue by il-Nurz** [xbmc/xbmc#17738]
### Describe the bug
Here is a clear and concise description of what the problem is:

Every time I try to play a video stream, Kodi crashes and exits. This happens with each video add-on from official repo (Google Drive, YouTube, Adult Swim, ANSA...) but I can play local files.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi plays video streams from web, add.ons, file .strm...

## Actual Behavior

Kodi crashes and exits as soon as I try to play a stream.

## Possible Fix

I already tried many different solutions:
- Clear video cache
- Manually update streaming addons and all of their dependencies (all of them from official repo)
- Change DNS
- Use VPN
- Uninstall Kodi and start with a fresh installation

Nothing worked...

### To Reproduce

1. Download and install Kodi
2. Download and install video add-ons from official repo (such as Google Drive, YouTube, Adult Swim, ANSA...) 
3. Play any streams
4. Wait few seconds for Kodi crashing

### Debuglog

Hereby I enclose the Debug Log from my last run on a Kodi UWP fresh installation using ANSA (video add-on from official repo): https://paste.kodi.tv/qajipokijo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

- I have found out that while on Windows 10 environment I can't play any streams (both Kodi x64 and Kodi UWP), Android app works properly on my smartphone (on same Wi-Fi network)!
- I recently experienced another issue installing Kodi on a different drive (D:) infact I get installation errors for most of default add-ons:
_ADD-ON Installation failed
ADD-ON Failed to install a dependency_
I hereby enclose the Debug Log for this issue as well: https://paste.kodi.tv/emuvanafok.kodi
So I moved back to drive C: (maybe there is a correlation between these two issues).

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
I cannot confirm this issue with Kodi 19. I copied the link from your log and did: 

`kodi-send -a "PlayMedia(https://primoitaliablob.blob.core.windows.net/cdn/109672/483027/109672_483027_g202004171920.mp4)"`

and the stream works perfectly

Could you please try a Kodi 19 alpha version. Please create a backup from your 
`%appdata%\Kodi` folder first before updating to Kodi 19 as Kodi 19 might break some add-ons you are currently using and while having a backuped folder from that 18.6 installation it's easy to copy it back after you downgraded to Kodi 18.6 again.

Thanks in advance

**Comment by il-Nurz** [comment]
Kodi 19 crashes as well.
I even tried with another add-on: IMDb Trailers.
This is my new Debug Log: [https://paste.kodi.tv/wocucaveti.kodi](url)

**Comment by enen92** [comment]
See https://github.com/xbmc/xbmc/pull/17679

**Comment by il-Nurz** [comment]
Thanks for your support @enen92 but I have this issue with any video stream and any streaming add-on

**Comment by il-Nurz** [comment]
No updates here?

**Comment by enen92** [comment]
No. Provide a crashlog, the debug log you added is pretty much unusable to debug anything crash related.

**Comment by il-Nurz** [comment]
> Kodi 19 crashes as well.
> I even tried with another add-on: IMDb Trailers.
> This is my new Debug Log: https://paste.kodi.tv/wocucaveti.kodi

I'm sorry @enen92 but that one above is the Debug Log I got after Kodi crash: I tried to open a stream in IMDb Trailers but Kodi freezed for few seconds and then closed automatically.

**Comment by enen92** [comment]
@il-Nurz please check if the issue still happens in current nightlies
