### ISSUE TITLE
Matrix service addon does not show in "myaddons"

### ISSUE THREAD

**Issue by scott967** [xbmc/xbmc#17742]
### Describe the bug
Here is a clear and concise description of what the problem is:

When an installed addon provides
``<extension point="xbmc.service" library="service.py" `start="login"/>``
it does not get listed in "my add-ons" in the service category, if there is also a library entry
``<extension point="xbmc.python.module" library="resources/lib" />``
The addon is only listed as an orphaned dependency.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Same behavior as in Kodi 18, namely an addon with both these extensions points will be shown in the my add-ons / service category.  Have not tested if other addon extension categories also exhibit this behavior.

## Actual Behavior

As indicated.

### To Reproduce

1.   Install an addon with the extension points as listed above in its addon.xml
2.  Navigate in the UI to the addonbrowser and open the "my add-ons" item
3.  The addon is not listed either in the service category or in "all"
4.  Open the addon's addon.xml and comment out the extension point xbmc.python.module entry.
5.  Repeat.  Now the addon is shown as expected.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/vekaxigabu.kodi
(nothing to see)
Actual addon.xml:
https://paste.kodi.tv/okesonumuw.kodi
Full addon (Martrix_py3 branch)
https://github.com/scott967/service.tvtunes/tree/Matrix_py3

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 10 x64 1903
 - Kodi version:
Kodi 19 win x64 19.0-ALPHA1-Git:20200421

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Can confirm this issue

**Comment by scott967** [comment]
Fix confirmed for issue as identified.
