### ISSUE TITLE
Kodi cannot play video url with custom video request header pipeline correctly

### ISSUE THREAD

**Issue by zhengfan2014** [xbmc/xbmc#17759]
### Describe the bug
Here is a clear and concise description of what the problem is:
Kodi cannot play video url with custom video request header pipeline correctly

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After receiving the video url with a custom video request header pipeline, Kodi adds referer = https://api.bilibili.com/x/web-interface/view?bvid= to the request header of the video url

## Actual Behavior
The same video URL with a custom video request header pipeline can be played normally in Kodi under Linux and Win10, but it cannot be played normally on Android

### To Reproduce

1. Create a strm file
2.The content of strm file is:
http://upos-sz-mirrorks3.bilivideo.com/upgcxcode/03/40/183554003/183554003-1-64.flv?e=ig8euxZM2rNcNbKB7zUVhoMM7WuBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1587966719&gen=playurl&nbs=1&oi=1947902450&os=ks3bv&platform=pc&trid=9470bf27e17d4fdaaa70f7915c758ccd&uipk=5&upsig=3e1390744cb00f9c5215d44026e912ec&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&mid=0|Referer=https://api.bilibili.com/x/web-interface/view?bvid=

3.On Android kodi18.6 and kodi19.0 cannot be opened

### Debuglog

The debuglog can be found here:
[kodi (1).log](https://github.com/xbmc/xbmc/files/4539307/kodi.1.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You did not enable debug logging. Please do so, reproduce your issue and share another log

Thanks

**Comment by zhengfan2014** [comment]
> You did not enable debug logging. Please do so, reproduce your issue and share another log
> 
> Thanks

Hello, I have enabled debug logging, this is my debug log file
[kodi (1).log](https://github.com/xbmc/xbmc/files/4538226/kodi.1.log)

**Comment by DaVukovic** [comment]
Looking at the log, Kodi fails with a 403. So you don't have the permission to access that content (whatever that is). 

The section you are claiming about is part of the strm-file. So I don't see Kodi adding anything which you haven't added yourself. Look at the section where you are mentioning how we should reproduce those steps. `referer=https://api.bilibili.com/x/web-interface/view?bvid=` is part of your strm-file. 

Anyway, by looking at this line: 

```2020-04-27 15:45:24.464 T:32547   ERROR: CCurlFile::Open failed with code 403 for http://upos-sz-mirrorhw.bilivideo.com/upgcxcode/78/35/183303578/183303578-1-80.flv?e=ig8euxZM2rNcNbUBhwdVtWUBhwdVNEVEuCIv29hEn0lqXg8Y2ENvNCImNEVEUJ1miI7MT96fqj3E9r1qNCNEto8g2ENvN03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&deadline=1587980717&gen=playurl&nbs=1&oi=1947902450&os=hwbv&platform=pc&trid=b756d50fedc749ebaf7a1f7e203f2fb4&uipk=5&upsig=e902883fad977d6e43ab180c4f3144b8&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&mid=0:```

Kodi drops that section but fails with a 403. So you don't have the permission anymore and the content isn't even reachable anymore. At least that's what I get by trying to access that content. 

So I'm going to close this issue for the time being. I will happily re-open it, if you have a simple way to reproduce that problem.

**Comment by zhengfan2014** [comment]
> Looking at the log, Kodi fails with a 403. So you don't have the permission to access that content (whatever that is).
> 
> The section you are claiming about is part of the strm-file. So I don't see Kodi adding anything which you haven't added yourself. Look at the section where you are mentioning how we should reproduce those steps. `referer=https://api.bilibili.com/x/web-interface/view?bvid=` is part of your strm-file.
> 
> Anyway, by looking at this line:
> 
> `2020-04-27 15:45:24.464 T:32547 ERROR: CCurlFile::Open failed with code 403 for http://upos-sz-mirrorhw.bilivideo.com/upgcxcode/78/35/183303578/183303578-1-80.flv?e=ig8euxZM2rNcNbUBhwdVtWUBhwdVNEVEuCIv29hEn0lqXg8Y2ENvNCImNEVEUJ1miI7MT96fqj3E9r1qNCNEto8g2ENvN03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&deadline=1587980717&gen=playurl&nbs=1&oi=1947902450&os=hwbv&platform=pc&trid=b756d50fedc749ebaf7a1f7e203f2fb4&uipk=5&upsig=e902883fad977d6e43ab180c4f3144b8&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&mid=0:`
> 
> Kodi drops that section but fails with a 403. So you don't have the permission and the content isn't even reachable anymore. At least that's what I get by trying to access that content.
> 
> So I'm going to close this issue for the time being. I will happily re-open it, if you have a simple way to reproduce that problem.

Regarding the previous one, I guess because the website restricts non-Chinese ips, only Chinese ip access will get the video, so you cannot reproduce

But I found a simple way to reproduce in the kodi forum:
[90015](https://forum.kodi.tv/showthread.php?tid=90015)

Create strm file and add content:
`http://openmedia.yale.edu/cgi-bin/open_yale/media_downloader.cgi?file=/courses/spring07/astr160/mov/astr160_01_011607.mov|Referer=http://oyc.yale.edu/astronomy/frontiers-and-controversies-in-astrophysics/content/downloads`

this is my debug log file
[kodi (2).log](https://github.com/xbmc/xbmc/files/4567448/kodi.2.log)

**Comment by DaVukovic** [comment]
I just tried with the content you posted above and I can't complain. Everything works as expected. I also asked for help and let some android users test if that stream works for them. And they are also saying that it plays without issues. 

So please seek for assistance at the forums. This seems clearly not to be a general Kodi bug. 

And if the `referer` section is the problem, simply avoid adding it. But as far as I could see, Kodi drops that anyway.
