### ISSUE TITLE
[skin.estouchy] Missing watched status for files in Videos if Content set to None

### ISSUE THREAD

**Issue by bahusoid** [xbmc/xbmc#17752]
There is currently no indication if file is watched or in progress if source content is not set ([set to None](https://user-images.githubusercontent.com/22025304/80298856-d665dc80-8798-11ea-88cc-d08a68622f59.png))

I checked both views:
![EstouchyNoWatchingStatusList](https://user-images.githubusercontent.com/22025304/80287474-87895a00-873a-11ea-9f06-a200d18ebb45.jpg)
![EstouchyNoWatchingStatusThumbs](https://user-images.githubusercontent.com/22025304/80287488-ac7dcd00-873a-11ea-8616-884c910ba2d3.jpg)

Another issue on last one is no file name is shown.

According to logs it's `MyVideoNav.xml` window.

## Expected Behavior
There should be some marks like in Estuary to indicate watching status:
![EstuaryWatchingStatus](https://user-images.githubusercontent.com/22025304/80287507-cddeb900-873a-11ea-9f0f-1a4003fe06a5.jpg)

### Your Environment
Used Operating system:

 - [x] Android

 - Operating system version/name: Android 6.0
 - Kodi version: 18.6
 - Estouchy version: 2.0.28
 - Device: Nexus 10

**Comment by bahusoid** [comment]
> If you believe it was sent in error, please say so

I believe all the relevant information is provided...

**Comment by enen92** [comment]
This is actually a feature request (as it looks like it's a feature not available in the estouchy skin and not exactly something that isn't working as expected). I'll leave it open though, some skinner should probably decide what to do with this issue

**Comment by bahusoid** [comment]
> This is actually a feature request (as it looks like it's a feature not available in the estouchy 

But this feature was always present in built-in skins - I can't believe it's missing feature. And I see some logic regarding watched/watching status in skin files:
https://github.com/xbmc/xbmc/blob/6fcbb13a90d8cd9782e4bfaee9ea19459e7aa45d/addons/skin.estouchy/xml/ViewsList.xml#L124-L125

So it looks like a bug to me...

**Comment by bahusoid** [comment]
I've been able to return watching icons by removing all `Container` related checks from code above:
```xml
<texture>OverlayWatching.png</texture> 
<visible>ListItem.IsResumable</visible>
```

Also there is no such checks in Estuary:
https://github.com/xbmc/xbmc/blob/e491a3575f2c65ded43bd5bf0e0ebf26107e2cc8/addons/skin.estuary/xml/Variables.xml#L357-L365

**Comment by DaVukovic** [comment]
I can not replicate your issue with current Kodi 19 alpha. Even if the files are scanned into my library or if I'm using the file-mode only (without items scanned into my library). The watched icon is always shown no matter which view I'm  using: 

![image](https://user-images.githubusercontent.com/7235787/80298590-46229a00-878e-11ea-897a-2fe47fd76af5.png)

I cannot see any changes regarding that for Estouchy. The youngest change for Estouchy is 7 months old and not related to this problem. The rest is about 12 months old and older. The file you have mentioned for estouchy (skin.estouchy/xml/ViewsList.xml) hasn't been touched for about 3 years now. So this is the same state for Kodi 18.6 as well as for Kodi 19 alpha. 

Beside that I'm missing something, I would say everthing works as expecte.

So I guess you should probably share a debuglog which is missing from your report hence the bot has marked it with "ignored rules". As long as a skinner doesn't jump in and probably sheds some more light into it, we won't remove that label if you don't provide one. 

Thanks in advance

**Comment by bahusoid** [comment]
> Even if the files are scanned into my library or if I'm using the file-mode only (without items scanned into my library).

@DaVukovic  What about content type ? Did you try it with set to None? 

![image](https://user-images.githubusercontent.com/22025304/80298844-c77f2a00-8798-11ea-9aa5-de0efd7967d8.png)
![image](https://user-images.githubusercontent.com/22025304/80298856-d665dc80-8798-11ea-88cc-d08a68622f59.png)

**Comment by DaVukovic** [comment]
True if I set content type to "none" the watched icon isn't shown. 

And there's already a fix for it: https://github.com/xbmc/xbmc/pull/17414

This will also probably be backported to Kodi 18: https://github.com/xbmc/xbmc/pull/17415

For the time being, please set some content to your sources and your problem is solved

**Comment by bahusoid** [comment]
Are you sure it's the same? As as I said https://github.com/xbmc/xbmc/issues/17752#issuecomment-619435772 I've been able to return icons just by removing Container related checks in xml.

From
```xml
<visible>[Container.Content(Movies) | Container.Content(Episodes) | Container.Content(MusicVideos) | Container.Content(Videos)] + ListItem.IsResumable</visible> 
```
to 
```xml
<visible>ListItem.IsResumable</visible>
```

Mentioned PR seems like fixing something in context menu or context menu actions.

**Comment by DaVukovic** [comment]
And as I said ( https://github.com/xbmc/xbmc/issues/17752#issuecomment-619484852 ) the file you mentioned hasn't been touched for about 3 years. And it works if you set content to your sources

See: 

![image](https://user-images.githubusercontent.com/7235787/80299270-7f113d80-8793-11ea-90c0-72996cb53fc9.png)

As "Container" might be related to the content you set on those sources.

**Comment by bahusoid** [comment]
I got it about workaround - thanks. I just don't think that suggested PR will fix this issue (it seems about showing/hiding "Mark as watched" action in context menu) So don't close it yet.

**Comment by DaVukovic** [comment]
You are right. Sorry. I applied the patch and rebuild Kodi and yeah, it's not related
