### ISSUE TITLE
v18.6 - Kodi does not save language in Movie->"Audio Setting"->"Set as default..."

### ISSUE THREAD

**Issue by DevStevo** [xbmc/xbmc#17762]
### Describe the bug
Here is a clear and concise description of what the problem is:
Dt. (Engl. always below): Wenn man bei einem Film mit mehreren Audio-Streams eine Sprache einstellt und "Als Standard für alle Medien übernimmt", dann speichert KODI nicht die dabei gewählte Sprachversion.
Engl: When setting the language in a movie with multiple audio streams and use "setting as default" KODI does not save the choosen language.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Dt.: Beim anwenden der Audio-Standards sollte immer erst die Sprachversion berücksichtigt werden und innerhalb der Spache die Audio-Qualität.
Engl: When apply the audio standard KODI should first consider the language and afterwards the audio quality.

## Possible Fix

Dt.: erst Sprache prüfen, dann Audio-Qualität prüfen
Engl. first check language, then check audio quality

### To Reproduce

Dt.:
1. Video-Datei mir mehreren Sprach-Streams starten
2. eine Sprachversion wählen (möglichst nicht den primären Stream)
3. diese Audio-Auswahl als Standard setzen
4. zweite Video-Datei mir mehreren Sprach-Streams starten und Sprache prüfen

Engl.:
1. start video file with multiple language audio streams 
2. chose another language (preferably dont take the first stream)
3. set the actual settings as default
4. start a second video file with also multiple language audio streams and check language

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi (LibreElec)
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Just use another setting: 

For german:
Settings -> Player -> Sprache -> Bevorzugte Audiosprache -> "Sprache der Benutzeroberfläche"

or whatever matches your needs. You could also select "German" if your GUI language might be set to englisch. Tested with a a bunch of video and german is always selected. 

For the future, please check the forums first as this is a support question rather than a bug. Support is given at the forums

Thanks for understanding

Cheers
