### ISSUE TITLE
ADDONS_TO_BUILD #17699 causing unwanted libretro addons to build

### ISSUE THREAD

**Issue by StormTrooper** [xbmc/xbmc#17773]
### Describe the bug
Here is a clear and concise description of what the problem is:

https://github.com/xbmc/xbmc/pull/17699 adds regex arguments for ADDONS_TO_BUILD

This is causing issues in OSMC build script for game.libretro in that all game.libretro.* addons in the repo are being built.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Only the addons listed should be built. If I use "game.libretro.*" then all matched addons should be built however as there is no * I do not expect it to include all.

## Actual Behavior

 
The build script lists specific game.libretro addons to be built:

```
ADDONS_GAME="game.libretro game.libretro.mame2000 game.libretro.mame2003 game.libretro.scummvm"
```
However this is causing all game.libretro.* addons in the repo to be built which is causing build failures. 

```
-- Pattern game.libretro matches game.libretro.beetle-psx, building addon
```

## Possible Fix

In the PR:

>I think the easier way to resolve this would be to rename game.libretro to something like game.libretro.core. I couldnt come up with anything easy to handle this case, and game.libretro is the only case i could find this happens to across any binary addons. No other active binary addon, has the name that is a subset of other active addons

### To Reproduce

1.  Point build script to list of addons. This contains all addons including ones that that should not be included due to build error/incompatible etc. 
https://github.com/StormTrooper/repo-binary-addons/tree/gmc-19 
2. Run a build

### Debuglog

The debuglog can be found here:

```
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Addon source tarball caching is enabled
-- Building following addons: game.libretro game.libretro.mame2000 game.libretro.mame2003 game.libretro.scummvm

-- Pattern game.libretro matches game.libretro.2048, building addon
-- Pattern game.libretro matches game.libretro.beetle-pce-fast, building addon
-- Pattern game.libretro matches game.libretro.beetle-psx, building addon
-- Pattern game.libretro matches game.libretro.beetle-vb, building addon





```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Linux raspberrypi4 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
Running OSMC nightly Matrix build.

 - Kodi version:
https://github.com/xbmc/xbmc/commit/9216e28bc4300eca57dc9671035fc49beb1fa007

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Unfortunately the way we use the cmake matches term, this is an issue. even though you dont necessarily think game.libretro is a regex, when used with matches, its considered a regex, and will match all others like game.libretro.mrboom, etc.

If you are willing to build/try something, maybe test the below and give me any feedback

https://github.com/fuzzard/xbmc/commits/cmake_addonregexmatching

There are 3 commits that you will need (well you can forget the docs one i guess)

https://github.com/fuzzard/xbmc/commit/50ec042f205f2b9f58813dfdc07e7555292e5c67
https://github.com/fuzzard/xbmc/commit/f479fb7a0fe6ed57c7535f2fc831ebeb8dae2646

without changing the way we provide regexes (think a +game.libretro or something of its like, similar to -game.libretro for an exclusion), all i can come up with is to get a list of addons that match exactly, and then anything passed through ADDONS_TO_BUILD that isnt an exact match is considered a regex argument.
I have to take a liberty here to strip * from anything provided via ADDONS_TO_BUILD, or again we end in the situation where it matches everything (list filter regex in this case)

Anyway, not sure if this is the best path, but at least it doesnt change existing behaviour (much).

some example usage

```
ADDONS_TO_BUILD='game.libretro peripheral.*'"
```
This will match game.libretro (and only game.libretro), but also match peripheral.joystick and peripheral.xarcade

```
ADDONS_TO_BUILD='game.libretro.* game.libretro peripheral.*'"
```
This will match game.libretro exactly, everything in game.libretro (regex), and both peripheral addons

```
ADDONS_TO_BUILD='game.libretro.mame* game.libretro peripheral.*'"
```
this will match game.libretro.mame, mame2000, mame2003 (7 mame addons in kodi-game binary addon repo), etc, game.libretro (exact) and then both peripheral addons

```
ADDONS_TO_BUILD='game.libretro.mame game.libretro peripheral.*'"
```
this will match game.libretro.mame (exact), game.libretro (exact) and then both peripheral addons

**Comment by StormTrooper** [comment]
Thanks for the patches. This is looking good. I ran a few test builds with various options and it works well. But there is one exception (Not sure if this is expected)

Works 100%:
```
-- Building following addons: game.libretro.mame2000 game.libretro.mame2003 game.libretro
-- Exact match game.libretro.mame2003, building addon
-- Exact match game.libretro.mame2000, building addon
-- Exact match game.libretro, building addon
```

One thing to note here is with the following game.libretro.mame* with not include game.libretro.mame2000, however using game.libretro.mame.* build will include it:
```
-- Building following addons: game.libretro.mame* game.libretro
-- Exact match game.libretro, building addon
```

Works 100%:
```
-- Building following addons: game.libretro.mame.* game.libretro
-- Pattern game.libretro.mame.* matches game.libretro.mame2003, building addon
-- Pattern game.libretro.mame.* matches game.libretro.mame2003_plus, building addon
-- Exact match game.libretro, building addon
```

Works 100%, all the libretro.* addons are included:
```
-- Building following addons: game.libretro.* 
-- Pattern game.libretro.* matches game.libretro.2048, building addon
-- Pattern game.libretro.* matches game.libretro.beetle-gba, building addon
```
