### ISSUE TITLE
screen flickering and artifacts on athlon vega3 graphics 

### ISSUE THREAD

**Issue by vladimirardelean** [xbmc/xbmc#17771]
### Describe the bug
Here is a clear and concise description of what the problem is:

I get a lot of screen flickering and artifacts in kodi menu. The issue gets worse when i navigate or move the mouse to the right panel (selection details) and gets better if i return to the main menu (left menu) and i move the mouse over it. In some cases the artifacts and the flickering  gets so bad that i cannot see anything. I saw that tends to make more artifacts at buttons/ buttons text. 
It gets so bad in so little time that i cannot even reach the menu to import a movie in order to see how it looks.
Hint: if i open kodi and i make no action the artifacts are not appearing, maybe a little flickering from time to time.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The menu should be clearly visible with no flickering.

## Actual Behavior

I get a lot of screen flickering and artifacts in kodi menu on user interactions.

## Possible Fix

Not managed to fix it.

### To Reproduce

1.  start debian 10 (no desktop envoirment)
2. install xorg and xdm
3. run xorg -configure (is selecting amdgpu driver)
3. add jessie backport and install kodi with apt-get 
4. run. kodi with xinit

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

CPU/GPU : Athlon 3000g with vega3 graphics
Motherboard: Gygabyte aorus b450 i

 - Operating system version/name: Debian 10 
 - Kodi version: 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by smp79** [comment]
I don't have such issues on Vega 3 with LibreELEC.

**Comment by DaVukovic** [comment]
And we need a debuglog. 

Please be aware that Kodi from Debian is not maintained by us, as Debian is changing the code. So it would be nice if we could see a logfile

**Comment by DaVukovic** [comment]
No log, no issue

Closed
