### ISSUE TITLE
metadata.themoviedb.org belarusian 

### ISSUE THREAD

**Issue by antikruk** [xbmc/xbmc#17778]
### Describe the bug

Hi. Add, please belarusian in this addon. I can't choose belarusian as preffered language.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@antikruk 

Feature requests must be submitted on the forum. Please write your request here... https://forum.kodi.tv/showthread.php?tid=339672

Is Belarusian language available at TheMovieDB?

**Comment by basilgello** [comment]
> @antikruk
> 
> Feature requests must be submitted on the forum. Please write your request here... https://forum.kodi.tv/showthread.php?tid=339672
> 
> Is Belarusian language available at TheMovieDB?

Yes, is ISO 631 code is "be-BY":

![tmdb-be](https://user-images.githubusercontent.com/3913291/80562687-1e7f3c00-89f1-11ea-87c0-2c63065ac9a2.png)

**Comment by antikruk** [comment]
Thanks

**Comment by KarellenX** [comment]
Thanks. 

@olympia the scraper developer will see your new post on the forum.
