### ISSUE TITLE
TS Streams not working since 18.4 - Also not working on kodi 19

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#17783]
### Describe the bug
Here is a clear and concise description of what the problem is:

Certain TS streams no longer play and appear to hang once played from PVR IPTV Simple since Kodi 18.4.

Likely introduced by:
- [VideoPlayer] Load program from stream property without using streaminfo: https://github.com/xbmc/xbmc/commit/e68bc9f22a576bc143014a7c3b46108a0388402f#diff-4b73a3a0982479ec64d6aba7b0f64380
- [VideoPlayer] Fix TS resume point, related to PR16314: https://github.com/xbmc/xbmc/commit/ea38c89c0e623548838f4138838cae86e0535d45#diff-4b73a3a0982479ec64d6aba7b0f64380

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When the stream is played video should start similar to how it played in 18.3.

## Actual Behavior

When the stream is played it appears to hang.

## Possible Fix

Not sure I need some help with this.

### To Reproduce

1. Add user supplied URL to M3U file in IPTV Simple
2. Play URL in IPTV Simple
3. Stream will fail to play.

### Debuglog

The debuglog can be found here:

Debug log: https://gist.github.com/phunkyfish/22f33eee0254e46ffd9df9ee33b4392d

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Reported here: https://github.com/kodi-pvr/pvr.iptvsimple/issues/350

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSX Catalina 10.15.4
 - Kodi version: 19 Alpha - latest master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by phunkyfish** [comment]
@FernetMenta I could once more use your advice.

So I've followed this down through the demuxer and on the first pass it probes and finds that it's `mpegts`. However on the second pass it appears to just hang and never create the streams (if that is what is supposed to a happen).

I used a user supplied stream to test this, opened up fro from their neutrino tv box on their local network.

**Comment by FernetMenta** [comment]
> Add user supplied URL to M3U file in IPTV Simple

what URL?

**Comment by phunkyfish** [comment]
Sent to you via email.

**Comment by FernetMenta** [comment]
CDVDDemuxFFmpeg::Open should be called with streaminfo set to false for this type of stream.

**Comment by phunkyfish** [comment]
Amazing, thanks. One other question.

As this will open as a DVDInputstreamFile how would I tell that streaminfo should be false prior to creating the demuxer?

Currently the default would be true in the demuxer factory.

**Comment by phunkyfish** [comment]
Or is it that streaminfo is not being set to false at some point during the first call to Open() in the demuxer?

**Comment by FernetMenta** [comment]
The code in demuxer factory is quite an ugly hack. It was introduced for live tv aka realtime streams. Now (we have IsRealTimeStream) it should be possible to drop the streaminfo parameter from open() together with all this ugly code. In demuxer use !inputstream->IsRealtime instead of the old parameter.

```
bool CDVDDemuxFFmpeg::Open(std::shared_ptr<CDVDInputStream> pInput, bool fileinfo)
{
  AVInputFormat* iformat = NULL;
  std::string strFile;
  m_streaminfo = !pInput->IsRealtime();
```

**Comment by phunkyfish** [comment]
How about something this in DVDDemuxFFmpeg around this line: https://github.com/xbmc/xbmc/blob/79f12660493807e6fa7e7ef150e9fad0d667863f/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp#L348-L354

```cpp
    if (iformat == nullptr)
    {
      // let ffmpeg decide which demuxer we have to open
      bool trySPDIFonly = (m_pInput->GetContent() == "audio/x-spdif-compressed");

      if (!trySPDIFonly)
      {
        av_probe_input_buffer(m_ioContext, &iformat, strFile.c_str(), NULL, 0, 0);

        if (iformat && strcmp(iformat->name, "mpegts") == 0)
          m_streaminfo= false;
      }
```

As m_streaminfo is not used till further down in open this would appear to solve it but is it the right way to do it?

**Comment by FernetMenta** [comment]
> Or is it that streaminfo is not being set to false at some point during the first call to Open() in the demuxer?

Not directly, it is set to false on reopen but this can be done without exposing this parameter to the outside world.

**Comment by FernetMenta** [comment]
> As m_streaminfo is not used till further down in open this would appear to solve it but is it the right way to do it?

Definitely not. streaminfo does harm on mpegts realtime streams the the code should reflect this.

**Comment by phunkyfish** [comment]
> The code in demuxer factory is quite an ugly hack. It was introduced for live tv aka realtime streams. Now (we have IsRealTimeStream) it should be possible to drop the streaminfo parameter from open() together with all this ugly code. In demuxer use !inputstream->IsRealtime instead of the old parameter.
> 
> ```
> bool CDVDDemuxFFmpeg::Open(std::shared_ptr<CDVDInputStream> pInput, bool fileinfo)
> {
>   AVInputFormat* iformat = NULL;
>   std::string strFile;
>   m_streaminfo = !pInput->IsRealtime();
> ```

Much clean that my proposal, NICE ;)

**Comment by phunkyfish** [comment]
So I guess also drop the fastswitch logic for PVR in the factory. Prior to this change streaminfo would have been false for any PVR channel. Now it will only be for realtime which is more correct.

**Comment by FernetMenta** [comment]
right

**Comment by phunkyfish** [comment]
Ok, let me know what you think: https://github.com/xbmc/xbmc/pull/17786
