### ISSUE TITLE
Android volume control only works when "Audio > Output Configuration"  = Fixed

### ISSUE THREAD

**Issue by fredd-427** [xbmc/xbmc#17821]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm running Kodi 18.6 (git: 20200229-8e967df921) on ARM android 7.1.2 box (AZW Beelink GT1) installed from official google play store. I used the french language for the Interface, in english i have the same problem.
I have an AVR Onkyo TX-NR646 connected via HDMI.

When i set System > Audio > Output Configuration = Fixed, the Android volume control works fine (ie when i'm using the android remote)
But i want to set this parameter to "Best Match" as recommended in this [guide](https://kodi.wiki/view/Audio_quickstart_guide) but in this case and for "Optimized" value, the Android volume control stops working :(

I've searched in the forum.kodi.tv, no one has sent the problem before.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The Android volume can be controled with Output Configuration != Fixed

## Actual Behavior

Android volume control works only when "Audio > Output Configuration"  = Fixed

### To Reproduce

1. "Audio > Output Configuration"  = Fixed
2. Android volume control works
3. "Audio > Output Configuration"  = Best Match or Optimized
4. Android volume control stops working

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android ARM 64-bit 7.1.2 API level 25, kernel 3.14.29
 - Kodi version: 18.6 (git: 20200229-8e967df921) compiled by Clang 7.0.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
> the Android volume control works fine 

It might depend which volume is set then. The Kodi volume or the android system (OS) volume. It might be possible that the volume keys are not setup properly to work with the Kodi GUI and then I would recommend to remap those keys to work with the Kodi GUI. 

Anyway. Please seek for assistance at our forums first.
