### ISSUE TITLE
Kodi doesn't show local lyrics

### ISSUE THREAD

**Issue by xmha97** [xbmc/xbmc#17823]
Hello Kodi Developers.
Kodi doesn't show local lyrics :(
Is the support for lyrics files stopped?
![image](https://user-images.githubusercontent.com/23485114/81386589-7bce6800-912a-11ea-9c3c-dcd98e241a65.png)
![image](https://user-images.githubusercontent.com/23485114/81386787-d798f100-912a-11ea-9043-a910e263ebc7.png)

**Comment by KarellenX** [comment]
@xmha97 

Please do not use Github for support questions. IIRC I have advised you of this previously.

Ask your question in the Lyrics thread here... https://forum.kodi.tv/showthread.php?tid=147340

And yes, local lyrics do work as I use them.
