### ISSUE TITLE
Add a portable option to the installer

### ISSUE THREAD

**Issue by Sopor** [xbmc/xbmc#17829]
### Describe the bug
Here is a clear and concise description of what the problem is:

When running several installations of Kodi the easiest way is to run one installation and the others as portable (for the moment i have 4 Kodi installed/extracted).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When installing portable i checkmark the option `Do not create shortcuts` so it won't override my shortcuts to my installed Kodi i have in `C:\Program Files\Kodi`.

## Actual Behavior

So now when i install/extract Kodi to another path it will remove my start menu icons from my default installation `C:\Program Files\Kodi` because `Do not create shortcuts` is checked.

## Possible Fix

There should be an option in the installer to choose `Portable` were it only extract the files to the selected folder instead of messing up my existing installation by adding shortcuts and uninstaller information.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/5789283/81485445-63a33980-924d-11ea-929b-00e521fa6389.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I have seen other program that have this option and when using `portable` there shouldn't be an option to add shortcuts to the Start menu and it shouldn't either remove any.

It shouldn't add it self to the `Program & features` (Uninstall) either because this will also mess up my existing installation. I can see it remembers my last installed/extracted Kodi when i run another version. So it seems to write to the Registry too.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.0 and higher

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Feature requests have to be submitted at the forums at this section: 

https://forum.kodi.tv/forumdisplay.php?fid=9

This section here is for bug reports only. 

Thanks for understanding
