### ISSUE TITLE
libsoxr instead of libsamplerate

### ISSUE THREAD

**Issue by mistepien** [xbmc/xbmc#17825]
libsoxr is faster then libsamplerate. it matters in case of miscellaneous arm devices.

**Comment by fritsch** [comment]
Most socs have an integrated asrc, but only one is implemented which is raspberry pi.

Come back with benchmarks for socr vs ffmpeg with same quality settings. You can see kodi's nicquist, window, etc in kodi's ffmpeg resample.

I am very curious on your use case and what you resample.

**Comment by DaVukovic** [comment]
@mistepien are you going to investigate this any further?

If not, I will close this issue
