### ISSUE TITLE
libaacs not creating keys

### ISSUE THREAD

**Issue by smf007** [xbmc/xbmc#17839]
### Describe the bug
Here is a clear and concise description of what the problem is:

The libaacs included in Kodi 18.6 does not decode bluray disc, thus the bluray cannot be played.  Basically, decode keys are not created in ~/.cache/aacs
When opening the same disc in VLC 3, the decode keys are created.  Once VLC creates the keys, the disc plays fine in Kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

That the libaacs included in Kodi would create the keys in ~/.cache/aacs

## Actual Behavior

Kodi does not create the keys in ~/.cache/aacs

### To Reproduce

1. Delete the contents of ~/.cache/aacs
2. Open Kodi and try to play a physical bluray
3. 

### Debuglog

The debuglog can be found here:
[Debug Log Intel-Ubuntu 20.04](https://paste.kodi.tv/hesorehuqa.kodi)
[Debug Log C2-CoreELEC](http://ix.io/2ltd)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Intel-Ubuntu 20.04
Odroid C2-CoreELEC 9.2.2

 - Kodi version:
Kodi 18.6 - Ubuntu 20.04
Kodi 18.6 - CoreELEC 9.2.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by smp79** [comment]
It's not supposed to create any keys.

**Comment by asavah** [comment]
Kodi does not include/build/link or provide libaacs on any platform.
libaacs itself does not include or provide keys.
Providing or distributing decription keys would be illegal in many countiries and most certainly would result in a DMCA takedown of the whole project.
Users could grab such a a keylist from a more or less shady sources themselves.

**Comment by smf007** [comment]
libaacs is included as part of libbluray.

While I said keys, I guess they aren't keys.  They are the resulting vuk/vid after applying a master key.
[See step 3.2.2 here](https://wiki.archlinux.org/index.php/Blu-ray#Decryption_process)

**Comment by smf007** [comment]
@ace20022 would you be able to look at this?  My guess would be something in routine libaacs_open of libbluray.

**Comment by smf007** [comment]
For completeness, I've been tracing this through over on the [CoreELEC forum](https://discourse.coreelec.org/t/encrypted-physical-blu-rays-not-playing/11149/36).  At this point it appears the device_path sent to libbluray is inconsistent with how VLC uses the library.  As such, Kodi is treating physical discs as images instead of a real device.  Libaacs is then not able to find the ID for the real physical disc.

**Comment by smf007** [comment]
Maybe I have this wrong, but in [DVDInputStreamBluray.cpp](https://github.com/fandangos2/xbmc/blob/f2f97235d17b0f4f8706cf98aab16eba1a85e4ef/xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamBluray.cpp), does not have bd_open_disc as an option.  Instead only bd_open_stream or bd_open_files are used.  Both of those routines set device_path to NULL.  With device_path being NULL, libaacs is unable to determine the device ID.  Instead, physical discs should be opened with bd_open_disc.

**Comment by vpeter4** [comment]
But you open your BR disk in file mode and not with **Play Disc**. I think this is the main issue you have.

**Comment by smf007** [comment]
I believe this was the commit [a73923](https://github.com/xbmc/xbmc/commit/a73923eda1d6717f7f7c417c029e632605ed3f62) from [pull 12339](https://github.com/xbmc/xbmc/pull/12339) that breaks this.

**Comment by smf007** [comment]
ace20022 was the author of that commit.  If I read that commit correctly he added the call bd_open_stream to handle image files (e.g. .ISO).  However, the other path changes from bd_open_disc to bd_open_files.  I gather this was for `adds bd-j menu support for disc on samba shares and the like`.  Unfortunately that breaks physical local discs.

**Comment by smf007** [comment]
This was already fixed in master, [pull 17145](https://github.com/xbmc/xbmc/pull/17145)

**Comment by smf007** [comment]
Terms out this is a duplicate of [issue 16672](https://github.com/xbmc/xbmc/issues/16672)

**Comment by enen92** [comment]
I'd say its a likely candidate to a backport. @smf007 can you handle the backport PR against the Leia branch?

**Comment by smf007** [comment]
I've created a PR of the backport [#17852](https://github.com/xbmc/xbmc/pull/17852).  Hopefully I did this right, first time doing a pull on github.

**Comment by enen92** [comment]
I don't think it is right, you're backporting the merge commit and not the one that fixes the issue: f4d6b4022fc3122471f0d39aeb58abafc9412a10

**Comment by smf007** [comment]
Thanks.  I'll try that again.

**Comment by smf007** [comment]
Should be fixed now.

**Comment by smf007** [comment]
As it has now been merged, I will close this issue.
