### ISSUE TITLE
OpenRPC support 

### ISSUE THREAD

**Issue by shanejonas** [xbmc/xbmc#17832]
OpenRPC provides a base foundation for service discovery and tooling such as documentation and client generation for JSON-RPC akin to OpenAPI/Swagger.

Seems like this project has something similar to describe json-rpc methods and types, but collaborating on an industry standard spec would benefit the whole JSON-RPC ecosystem.

Let me know how I can help.

link to the spec: https://spec.open-rpc.org/
playground https://playground.open-rpc.org/

**Comment by fuzzard** [comment]
PRs are always welcome.

Closing this as feature requests are for the forums.
