### ISSUE TITLE
Video node / Sorting / Internationalization

### ISSUE THREAD

**Issue by malaterre** [xbmc/xbmc#17842]
### Describe the bug

I'd like the Video node for 'Titles' to list the movies in alphabetical order esp. in the case of internationalization. 

## Expected Behavior

For native French speaker it would make sense to order the movies in the following order:

1. A...
2. Â...
3. B...
4. ...
5. Z...

## Actual Behavior

Right now order is :

1. A...
2. B...
3. ...
4. Z...
5. Â...

## Possible Fix

You would need to handle 'Â' just as if it was simply 'A'

### To Reproduce

See screenshots, hopefully this is enough.

### Screenshots 
Here are some links or screenshots to help explain the problem:

![IMAG0670](https://user-images.githubusercontent.com/228803/81550956-4b343b80-9381-11ea-89d0-e5ebdf8a3ea2.jpg)

![IMAG0671](https://user-images.githubusercontent.com/228803/81550977-54bda380-9381-11ea-9047-9aee19687866.jpg)

## Additional context or screenshots (if appropriate)

Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X ] Linux
 - [X] Raspberry-Pi

 - Operating system version/name: LibreELEC 9.2.1
 - Kodi version: v18.6

**Comment by malaterre** [comment]
I believe all information is now properly filled. Thanks

**Comment by DaveTBlake** [comment]
The lack of correct sorting of accented characters on RPi has been resolved for v19 by https://github.com/xbmc/xbmc/pull/17562 
It is not possible to backport this improvement to v18, but is in the current nightly and Milhouse builds of LibreElec
