### ISSUE TITLE
kodi-send from Stable PPA broken on Ubuntu 20.04

### ISSUE THREAD

**Issue by snake3ca** [xbmc/xbmc#17848]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using kodi-send from package kodi-eventclients-kodi-send in the stable PPA for Ubuntu 20.04 it throws a python error.  

-bash: /usr/bin/kodi-send: /usr/bin/python: bad interpreter: No such file or directory

When running the command using the kodi-eventclients-kodi-send package in the default ubuntu 20.04 repository it works properly and does not give the error.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Would expect it to allow you to send command using kodi-send.

## Actual Behavior

Gives error :  -bash: /usr/bin/kodi-send: /usr/bin/python: bad interpreter: No such file or directory

## Possible Fix

in /usr/bin/kodi-send python script on line 1 change #!/usr/bin/python to  #!/usr/bin/python3

also change line 87 from     "if len(actions) is 0:" to    "if len(actions) == 0:"

### To Reproduce

1. install kodi-eventclients-kodi-send
2.run kodi-send 
3.

### Debuglog

The debuglog can be found here:

-bash: /usr/bin/kodi-send: /usr/bin/python: bad interpreter: No such file or directory

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by wsnipex** [comment]
why doesn't /usr/bin/python exist on your system?

**Comment by radhad** [comment]
@wsnipex 

Ubuntu 20.04 deprecated /usr/bin/python and comes only with /usr/bin/python3.8 
Same as FreeBSD 12.

**Comment by snake3ca** [comment]
That is correct /usr/bin/python no longer exist on Ubuntu 20.04.

**Comment by wsnipex** [comment]
thanks ubuntu I guess...
please verify if it works when you install python-is-python3

**Comment by ccope** [comment]
[PEP 394](https://legacy.python.org/dev/peps/pep-0394/#recommendation) declared in 2011 that python = python2. It was only [updated](https://github.com/python/peps/pull/989/files) in July last year to allow python = python3, at the discretion of distributors. Debian and Ubuntu (and probably others) have decided not to change the behavior of the `python` binary yet, probably to avoid throwing syntax errors when users try to run third-party scripts that have not been ported to python3. Scripts that are designed to work with modern versions of python should use python3 in their shebang lines.

**Comment by snake3ca** [comment]
If you install the package python-is-python3 it works but still throws the error "/usr/bin/kodi-send:87: SyntaxWarning: "is" with a literal. Did you mean "=="? if len(actions) is 0:"

**Comment by ccope** [comment]
Master already has the python3 shebang, it just wasn't backported to Leia: https://github.com/xbmc/xbmc/blob/master/tools/EventClients/Clients/KodiSend/kodi-send.py

@snake3ca The warning you pasted was added in python 3.8 (the default python3 in Ubuntu 20.04). It doesn't prevent the script from running successfully (I just did a trivial test with a print statement inside an `if` block).
https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/

**Comment by snake3ca** [comment]
Sounds good I will close this as its fixed already.

**Comment by snake3ca** [comment]
Issue fixed in master.
