### ISSUE TITLE
Multiple test failures in 18.6

### ISSUE THREAD

**Issue by candrews** [xbmc/xbmc#17858]
### Describe the bug
Running the tests while building Kodi 18.6 results in multiple test failures:
```
28 - TestXBMCTinyXML.ParseFromFileHandle (Failed)
201 - TestPOUtils.General (Failed)
440 - TestPlayListXSPF.Load (Failed)
450 - TestZipFile.Read (Failed)
451 - TestZipFile.Exists (Failed)
452 - TestZipFile.Stat (Failed)
453 - TestZipFile.CorruptedFile (Failed)
455 - TestFileFactory.Write (Failed)
456 - TestFile.Read (Failed)
```
Here is the log with full output: [build.log](https://github.com/xbmc/xbmc/files/4618077/build.log)

## Expected Behavior
No tests should fail.

## Actual Behavior
There are test failures.

### To Reproduce
Run the tests as part of the Kodi 18.6 build.

### Debuglog
n/a (this is a build / test issue, not a runtime one)

### Screenshots 
n/a (this is a build / test issue, not a runtime one)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Originally reported at https://bugs.gentoo.org/722578

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo/Linux, amd64
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by wsnipex** [comment]
could you run this please? I suspect it might not be finding the reffile.txt.zip.
strace ./kodi-test --gtest_filter="TestZipFile*" 1>TestZipFile.log 2>TestZipFile.trace

**Comment by wsnipex** [comment]
see https://github.com/xbmc/xbmc/issues/17860
