### ISSUE TITLE
Context menu after long pressing a confirm button

### ISSUE THREAD

**Issue by TomasLudvik** [xbmc/xbmc#17851]
## Feature request

I am using Kodi installed on Xbox One S and I am controlling it using my TV remote (Samsung). The problem is, that the context menu on Xbox is opened by "X" button, which is not present on my TV remote, so in order to open the context menu, I need to use my Xbox remote.

## Expected Behavior

The context menu can be opened by a longer pressing of the confirm / OK button.

## Actual Behavior

Cannot open context menu using TV remote.

### To Reproduce

1. Install latest Kodi on Xbox One
2. Run Kodi
3. Try to open context menu with the TV remote.

**Comment by TomasLudvik** [comment]
I think that including more information is not needed as the problem described is perfectly clear.

**Comment by scj643** [comment]
This issue might be due to a limitation on the remote and not an issue with Kodi.The way that IR remotes work don't allow long presses normally.

**Comment by DaVukovic** [comment]
>I think that including more information is not needed as the problem described is perfectly clear.

It's not only about the description. It's more the info we might read from a debuglog (which you missed to provide). As the info is not present, we have to ask for that. If we would ask every reporter for specific things (which we could read from such logs), we would need a lot more manpower to get things done. 

So, I guess you are currently using CEC with the Samsung-remote, true?

Btw. longpresses are for sure supported with IR remotes which do interact direclty with the device. I'm not so sure about CEC, tbh. But let's get the answer first. 

And.....get us the debuglog (with debugging enabled, ofc)

**Comment by DaVukovic** [comment]
https://forum.kodi.tv/showthread.php?tid=292261

Here is a solution for your problem in case you are using CEC

**Comment by guss77** [comment]
For keyboards (and RF remotes that identify as keyboards - I am using the popular [C120](https://www.amazon.com/Calvas-Gyroscope-Wireless-Rechargeable-Controller/dp/B07RCBDDYB) RF remote), Kodi already supports a `longpress` option for the keymap key modifier configuration (`mod`) and the default keyboard keymap even has a "long press enter" mapped to the context menu - so even though there's no menu button on the top face of my remote, I can access the context menu by holding the OK button.

(I got here looking for a similar solution for RF keyboards and needed this prompt to find that the solution is already available and on by default).

**Comment by DaVukovic** [comment]
I guess this one is fine to close. The reporter doesn't seem to be interested in answering the question and workarounds have been provided.
