### ISSUE TITLE
Multiple test failures in Kodi 19 / current master

### ISSUE THREAD

**Issue by candrews** [xbmc/xbmc#17860]
### Describe the bug
Running the tests while building Kodi 19 / current master https://github.com/xbmc/xbmc/commit/875a8f65805b82fa95e902ec194f8a4673a9b3e1 results in 37 test failures:
```
         32 - TestXBMCTinyXML.ParseFromFileHandle (Failed)
        206 - TestPOUtils.General (Failed)
        468 - TestDateTime.GetAsTimeStamp (Failed)
        508 - TestPlayListXSPF.Load (Failed)
        517 - TestWebServer.CanHeadFile (Failed)
        519 - TestWebServer.CanGetFile (Failed)
        520 - TestWebServer.CanGetFileForcingNoCache (Failed)
        521 - TestWebServer.CanGetCachedFileWithOlderIfModifiedSince (Failed)
        524 - TestWebServer.CanGetCachedFileWithNewerIfModifiedSinceForcingNoCache (Failed)
        525 - TestWebServer.CanGetCachedFileWithOlderIfUnmodifiedSince (Failed)
        526 - TestWebServer.CanGetCachedFileWithExactIfUnmodifiedSince (Failed)
        527 - TestWebServer.CanGetCachedFileWithNewerIfUnmodifiedSince (Failed)
        528 - TestWebServer.CanGetRangedFileRange0_ (Failed)
        529 - TestWebServer.CanGetRangedFileRange0_End (Failed)
        530 - TestWebServer.CanGetRangedFileRange0_2xEnd (Failed)
        531 - TestWebServer.CanGetRangedFileRange0_First (Failed)
        532 - TestWebServer.CanGetRangedFileRangeFirst_Second (Failed)
        533 - TestWebServer.CanGetRangedFileRange_Last (Failed)
        534 - TestWebServer.CanGetRangedFileRangeFirstSecond (Failed)
        535 - TestWebServer.CanGetRangedFileRangeFirstSecondLast (Failed)
        536 - TestWebServer.CanGetCachedRangedFileWithOlderIfRange (Failed)
        537 - TestWebServer.CanGetCachedRangedFileWithExactIfRange (Failed)
        538 - TestWebServer.CanGetCachedRangedFileWithNewerIfRange (Failed)
        547 - TestZipFile.Read (Failed)
        548 - TestZipFile.Exists (Failed)
        549 - TestZipFile.Stat (Failed)
        550 - TestZipFile.CorruptedFile (Failed)
        551 - TestZipFile.ExtendedLocalHeader (Failed)
        553 - TestHTTPDirectory.ApacheDefaultIndex (Failed)
        554 - TestHTTPDirectory.ApacheFancyIndex (Failed)
        555 - TestHTTPDirectory.ApacheHtmlIndex (Failed)
        556 - TestHTTPDirectory.BasicIndex (Failed)
        557 - TestHTTPDirectory.BasicMultilineIndex (Failed)
        558 - TestHTTPDirectory.LighttpDefaultIndex (Failed)
        559 - TestHTTPDirectory.NginxDefaultIndex (Failed)
        561 - TestFileFactory.Write (Failed)
        562 - TestFile.Read (Failed)
```
Here is the log with full output: [build.log](https://github.com/xbmc/xbmc/files/4618502/build.log)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No tests should fail.

## Actual Behavior

There are test failures.

### To Reproduce

Run the tests as part of the Kodi build.

### Debuglog

n/a (this is a build / test issue, not a runtime one)

### Screenshots 
Here are some links or screenshots to help explain the problem:
n/a (this is a build / test issue, not a runtime one)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo/Linux, amd64
 - Kodi version: master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by candrews** [comment]
Per @wsnipex's request at https://github.com/xbmc/xbmc/issues/17858#issuecomment-627571318
> could you run this please? I suspect it might not be finding the reffile.txt.zip.
> strace ./kodi-test --gtest_filter="TestZipFile*" 1>TestZipFile.log 2>TestZipFile.trace

[TestZipFile.trace](https://github.com/xbmc/xbmc/files/4618518/TestZipFile.trace.txt)
[TestZipFile.log](https://github.com/xbmc/xbmc/files/4618520/TestZipFile.log)

**Comment by wsnipex** [comment]
your log shows that needed input files are searched in /usr/share/kodi/xbmc/filesystem/test/
This looks like your kodi_install path.
Our tests are designed to be run only from the build directory(where the kodi-test binary resides)
The env var KODI_HOME must either be empty or set to the build dir.

Assuming my build dir is /data/src/xbmc/build, I can run the kodi-test binary from anywhere like this:
KODI_HOME=/data/src/xbmc/build ./kodi-test --gtest_filter="TestZipFile*"

Please note that there are 3 Tests (TestDateTime) that fail for me as well

**Comment by candrews** [comment]
Excellent! With the `KODI_HOME` change, now all tests but the one you mentioned (`468 - TestDateTime.GetAsTimeStamp`) pass.

Is there any info I could provide that would help with fixing that failure?

**Comment by wsnipex** [comment]
the TestDateTime failure is unrelated. If you want to get rid of those errors in your package, just add them to --gtest_filter="-TestDateTime.GetAsTimestamp" for now.

I guess this can be closed?

**Comment by candrews** [comment]
> the TestDateTime failure is unrelated. If you want to get rid of those errors in your package, just add them to --gtest_filter="-TestDateTime.GetAsTimestamp" for now.
> 
> I guess this can be closed?

I created https://github.com/xbmc/xbmc/issues/17909 to track the `TestDateTime.GetAsTimestamp` failing test.
