### ISSUE TITLE
Kodi resets to a low resolution on startup after setting/using a HiDPI resolution

### ISSUE THREAD

**Issue by piejanssens** [xbmc/xbmc#17871]
### Describe the bug
Here is a clear and concise description of what the problem is:

The best resolution on my MacBook Pro 2017 (15 inch) is 2880x1800. I can set this resolution in Kodi and when it switches, everything looks crisp with razor sharp textures and texts.

Once I quit Kodi and reopen it, it then scales the window up causing only a small part of the GUI to be visible on the screen. 
Then I do the old CMD+F trick to switch to windowed and back to full screen. This scales it back to full screen, but unfortunately also resets the resolution to 1680x1050.

On that resolution everything looks jaggy and unsharp. You can see this in the screenshots below. Even 4K video seems to be impacted (even though I once was told the GUI resolution had nothing to do with the playback resolution). 

This all comes down to support HiDPI mode on macOS. However, there might be a workaround as setting a HiDPI resolution works, but is lost upon startup.

I found one workaround to get my resolution to stick to 2880x1800. It seems to stick once I have opened Kodi while my secondary 4K monitor was attached. Please note that Kodi is not using the secondary monitor and when I do use Kodi for playback it's always without an external monitor. So it's not a workaround that works for my use case.

## Expected Behavior
Setting a resolution that matches the display to have a good looking UI.

## Actual Behavior
Kodi resets to a low resolution on startup.

## Possible Fix
If the windowing implementation of macOS could execute the same steps as it does when switchin to the higher resolution (becuase at that moment it sticks) then it more or less resolves this issue and there is a lesser need to implement real HiDPI support.

### To Reproduce

1. Set resolution of fullscreen Kodi to HiDPI resolution 2280x1800
2. Quit Kodi
3. Start Kodi
4. Resolution is reset to 1680x1050

### Debuglog

- Change to 2880x1800 which sticks until startup: https://pastebin.com/0QB97UR4

- Startup which goes back to 1680x1050: https://pastebin.com/NcmBUY7Q

- Changed to 2880x1800 with second monitor attached (not used for Kodi) where it sticks to 2880x1800 even after restart: https://pastebin.com/k5rPQ9HY

### Screenshots 
The lower resolution seems to affect both textures/font renderings and video.
Please be aware these differences can best be seen by zooming in or using a monitor with a sufficiently high res.

 Viewport size when starting Kodi the next time, after resolution was set 2880x1800:
<img width="1152" alt="Schermafbeelding 2020-05-15 om 14 45 07" src="https://user-images.githubusercontent.com/829098/82051769-ca47ad80-96ba-11ea-87db-23ba1d51c3e7.png">

 4K-video-at-GUI-on-1680x1050
<img width="1680" alt="4K video at GUI on 1680x1050" src="https://user-images.githubusercontent.com/829098/82047182-a1231f00-96b2-11ea-90be-41c110e7a92c.png">

 4K-video-at-GUI-on-2880x1800
![4K video at GUI on 2880x1800](https://user-images.githubusercontent.com/829098/82047204-aed8a480-96b2-11ea-9df3-2eb551c4580f.png)

 menu-at-GUI-on-1680x1050
<img width="1680" alt="menu at GUI on 1680x1050" src="https://user-images.githubusercontent.com/829098/82047221-b7c97600-96b2-11ea-86ab-d9e955781158.png">

 menu-at-GUI-on-2880x1800
![menu at GUI on 2880x1800](https://user-images.githubusercontent.com/829098/82047243-c2840b00-96b2-11ea-8703-f8a15c442be1.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The bug has affected all Retina mac users since retina was first introduced. @Memphiz looked into it a while back, but - even though he wanted - was not able to assist without the proper hardware. 
Maybe this can help for macOS devs to simulate HiDPI: https://github.com/xzhih/one-key-hidpi

Related topics:

- https://forum.kodi.tv/showthread.php?tid=216159
- https://www.reddit.com/r/kodi/comments/4bn5eq/kodi_and_retina_display_support_on_os_x/
- https://forum.kodi.tv/showthread.php?tid=304139
- https://forum.kodi.tv/showthread.php?tid=177253
- https://forum.kodi.tv/showthread.php?tid=210268
- https://forum.kodi.tv/showthread.php?tid=223544
- https://forum.kodi.tv/showthread.php?tid=331816
- https://forum.kodi.tv/showthread.php?tid=294065
- https://forum.kodi.tv/showthread.php?tid=187652
- https://forum.kodi.tv/showthread.php?tid=298516
- https://forum.kodi.tv/showthread.php?tid=130092

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS 10.15
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by I-Cat** [comment]
almost looks like embuary skin issue call. It is loading Old set....
Wait do we support embuary?

**Comment by piejanssens** [comment]
@I-Cat Embuary is not from Team Kodi. I have the exact same observations between Estuary and Embuary and the screenshots provided are made with Estuary to make sure there wouldn't be any concerns about this issue being 3rd party skin related. 😃

**Comment by piejanssens** [comment]
I no longer have this issue running macOS 11 (Big Sur)!

**Comment by piejanssens** [comment]
No issue with Matrix either on Big Sur.
