### ISSUE TITLE
UPnP: Display cover art of movies

### ISSUE THREAD

**Issue by malaterre** [xbmc/xbmc#17870]
### Describe the bug
Here is a clear and concise description of what the problem is:

I would like to request the feature to extract the cover art (jpeg/png) from an MP4 container. This extracted jpeg/png should be displayed from a UPnP client (eg. Windows Media Player).

Right now, no cover is displayed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would like to have the following behavior in Windows Media Player:

![minidlna_dumbo](https://user-images.githubusercontent.com/228803/82038285-9ad97680-96a3-11ea-8708-211c757939a9.png)

Server is Debian/buster with default minidlna server installation.

## Actual Behavior

Right now no icon are displayed:

![kodi_dumbo](https://user-images.githubusercontent.com/228803/82038337-af1d7380-96a3-11ea-9894-70aa5e277cc2.png)

## Possible Fix

The MP4 stream should contain all information for this feature. In any case kodi internally has access to *poster* or *fanart* when media are properly setup.

### To Reproduce

Follow instruction from:

* https://ffmpeg.org/ffmpeg.html

> To add an embedded cover/thumbnail:
> 
> `ffmpeg -i in.mp4 -i IMAGE -map 0 -map 1 -c copy -c:v:1 png -disposition:v:1 attached_pic out.mp4`
> 

Check in windows explorer that the file has an icon displayed at the bottom of the explorer screen:

![explorer_dumbo](https://user-images.githubusercontent.com/228803/82039008-a24d4f80-96a4-11ea-9c24-4415aec443d0.png)

### Screenshots 
Here are some links or screenshots to help explain the problem:

See above.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreElec/9.2.1
 - Kodi version: v18.6

Windows Media Player on Windows 7/64bits.

**Comment by KarellenX** [comment]
@malaterre 

We do not accept Feature Requests here. It is for bug reporting only.

Please make  your request on the forum here... https://forum.kodi.tv/forumdisplay.php?fid=9

**Comment by malaterre** [comment]
For reference:

* https://forum.kodi.tv/showthread.php?tid=354444

Thanks for the link.
