### ISSUE TITLE
fite tv - kodi settings lost

### ISSUE THREAD

**Issue by stschulze1972** [xbmc/xbmc#17882]
### Describe the bug
Kodi 18.6 Laia
Kodi lost the settings after poweroff
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi settings permanently safed is recomended

### To Reproduce
1. Install kodi on fireTV
2. Make Regional settings to German
3. poweroff
4. wait some hours
5. start fireTV 
6. start Kodi
7. sometimes settings are save - look if german is working; if not -> never come back; if german works ... goto 3.

### Your Environment
Used Operating system:
 - Operating system version/name: fireTV 4k
 - Kodi version: 18.6 stable

**Comment by howie-f** [comment]
@stschulze1972 please try the nightly build of Leia 18.7 - meanwhile some issues regarding this have been fixed. also it's not a good idea to just `3. poweroff`. you should always try to at least shutdown kodi cleanly before pulling the cable.

**Comment by DaVukovic** [comment]
correct ^^ 

Kodi settings are stored while closing Kodi. If you poweroff your device (in meaning pull the cable or something similar instead of exiting Kodi and then power the device off), a lost of settings is to be expected.
