### ISSUE TITLE
Malwarebytes 4.10 Prem blocks Kodi access to ftp2.nluug.nl - as INFECTED web site

### ISSUE THREAD

**Issue by Newsangel** [xbmc/xbmc#17884]
Bug report
Malwarebytes 4.10 Premium blocks Kodi access to ftp2.nluug.nl deeming it as an INFECTED web site

Here is a clear and concise description of what the problem is:
MWB occasionally reports blocked access to the above mentioned web site, which is trying to be accessed by my Win 10 Pro (1909 latest build) operating system... when I run or use Kodi 18.6

As a PC tech of 30 years, I have run every scanner known to man to see if my computer is infected with malware. All scans show I am not infected with anything. Not even rootkits.

When I use Google to research the address ftp2.nuluug.nl  said site is associated with Kodi. 

I am assuming Kodi is invoking calls to this site, perhaps to check its version or something similar. I am curious to why an ftp access is being requested, as I have ZERO Kodi addons or plugins... and then how odd that Malwarebytes is now suddenly identifying said URL as a trojan-laced site. 

If not, then perhaps the Kodi team should communicate with the MWB team. MWB is a huge top notch malware software company, the MOST respected in the business... and Kodi's reputation is not going to fare well if this continues.

Thanks kindly

Expected Behavior
Normal use of Kodi should NOT result in activation of web based anti-malware protection

Actual Behavior
Kodi is calling this web site.... and access to said URL is blocked, though Kodi functions normally, no errors

Possible Fix
Contact Malwarebytes

To Reproduce
Use Kodi normally with MWB Premium installed, wait for blocked site warning pop up

Debuglog
No debug needed

Screenshots
None

Additional context or screenshots (if appropriate)
None

Your Environment
Win 10 Pro 64 bit    ver 1909 (latest build .826)

Kodi version: 18.6

**Comment by arnova** [comment]
This is a mirror website, so there isn't much we can do. Furthermore I think the actual problem is on MalwareBytes, so again not our turf. Thanks for reporting though.

**Comment by DaVukovic** [comment]
I doubt that it is: ftp2.nuluug.nl but I guess it's ftp2.nluug.nl which is one of our mirrors: 

As you can see: https://ftp2.nluug.nl/

They are a mirror for many other things and, tbh, you should contact them instead of us. Because if their service is blamed for being a malware site, then they have to contact MWB. 

Anyway, nothing what we can do about that.
