### ISSUE TITLE
[JSON-RPC] Player.OnPropertyChanged not sent when the player is inactive

### ISSUE THREAD

**Issue by regseb** [xbmc/xbmc#17896]
### Describe the bug
Here is a clear and concise description of what the problem is:

In JSON-RPC API, the [`Player.OnPropertyChanged`](https://kodi.wiki/view/JSON-RPC_API/v10#Player.OnPropertyChanged) notification isn't sent when `shuffle` (or `repeat`) properties changed and player is inactive.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should send the notification when `shuffle` properties changed and player is inactive.
```json
{"jsonrpc":"2.0","method":"Player.OnPropertyChanged","params":{"data":{"player":{"playerid":1},"property":{"shuffled":true}},"sender":"xbmc"}}
```

## Actual Behavior

Kodi doesn't send the notification when `shuffle` properties changed and player is inactive.

## Possible Fix

Remove conditions on active players in [`CPlayListPlayer::AnnouncePropertyChanged()`](https://github.com/xbmc/xbmc/blob/master/xbmc/PlayListPlayer.cpp#L760):

```cpp
void CPlayListPlayer::AnnouncePropertyChanged(int iPlaylist, const std::string &strProperty, const CVariant &value)
{
  if (strProperty.empty() || value.isNull())
    return;

  CVariant data;
  data["player"]["playerid"] = iPlaylist;
  data["property"][strProperty] = value;
  CServiceBroker::GetAnnouncementManager()->Announce(ANNOUNCEMENT::Player, "xbmc", "OnPropertyChanged", data);
}
```

### To Reproduce

1. In Kodi, *Allow remote control from applications on other systems* (*Settings* / *Services* / *Control*).
2. Add a video to the playlist and play it.
3. Execute (by changing the IP address) : `curl --include --no-buffer --header "Connection: Upgrade" --header "Upgrade: websocket" --header "Sec-WebSocket-Version: 13" --output out.log http://192.168.1.2:9090/jsonrpc/`
3. Go to the video playlist and change the shuffle.
4. Stop `curl`.
5. Open *out.log* that contains `Player.OnPropertyChanged` notification.
6. Stop video.
7. Execute (by changing the IP address) : `curl --include --no-buffer --header "Connection: Upgrade" --header "Upgrade: websocket" --header "Sec-WebSocket-Version: 13" --output out.log http://192.168.1.2:9090/jsonrpc/`
8. Go to the video playlist and change the shuffle.
9. Stop `curl`.
10. Open *out.log* that doesn't contain `Player.OnPropertyChanged` notification.

### Debuglog

The debuglog can be found here:

Kodi log nothing.

### Screenshots 
Here are some links or screenshots to help explain the problem:

NA

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

NA

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC 2020.03-1
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by malard** [comment]
inactive players should be treated as being in an 'undefined' state and as such state is unreliable. While I accept that toggling the shuffled state is better tracked, the same general assumption should be assumed and as soon as content is played on the player the correct state information is populated.
