### ISSUE TITLE
[JSON-RPC] Application.OnVolumeChanged returns float volume

### ISSUE THREAD

**Issue by regseb** [xbmc/xbmc#17894]
### Describe the bug
Here is a clear and concise description of what the problem is:

In JSON-RPC API, the [`Application.OnVolumeChanged`](https://kodi.wiki/view/JSON-RPC_API/v10#Application.OnVolumeChanged) notification returns the `volume` in a float. The documentation indicates that it's an integer. And the [`Application.GetProperties`](https://kodi.wiki/view/JSON-RPC_API/v10#Application.GetProperties) method returns an integer.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should send the notification with an integer for the `"volume":98`.
```json
{"jsonrpc":"2.0","method":"Application.OnVolumeChanged","params":{"data":{"muted":false,"volume":98},"sender":"xbmc"}}
```

## Actual Behavior

Kodi sends the notification with an float for the `"volume":98.88888549804688`.
```json
{"jsonrpc":"2.0","method":"Application.OnVolumeChanged","params":{"data":{"muted":false,"volume":98.88888549804688},"sender":"xbmc"}}
```

## Possible Fix

As in the [`CApplicationOperations::GetPropertyValue()`](https://github.com/xbmc/xbmc/blob/654c1471a62deeec8a6c6b485f7bb2e1969924ea/xbmc/interfaces/json-rpc/ApplicationOperations.cpp#L107), cast the volume in int: **`data["volume"] = static_cast<int>(GetVolumePercent());`** (cf. [`CApplication::VolumeChanged()`](https://github.com/xbmc/xbmc/blob/654c1471a62deeec8a6c6b485f7bb2e1969924ea/xbmc/Application.cpp#L4469)).

### To Reproduce

1. In Kodi, *Allow remote control from applications on other systems* (*Settings* / *Services* / *Control*).
2. Execute (by changing the IP address) : `curl --include --no-buffer --header "Connection: Upgrade" --header "Upgrade: websocket" --header "Sec-WebSocket-Version: 13" --http0.9 --output out.log http://127.0.0.1:9090/jsonrpc/`
3. Change volume in kodi.
4. Stop `curl`.
5. Open *out.log* that contains `Application.OnVolumeChanged` notification.

### Debuglog

The debuglog can be found here:

Kodi log nothing.

### Screenshots 
Here are some links or screenshots to help explain the problem:

NA

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

NA

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC 2020.03-1
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@regseb can you send a pull request with your proposed fix?
