### ISSUE TITLE
[JSON-RPC] Global.Time: do not limit the time to 24 hours

### ISSUE THREAD

**Issue by regseb** [xbmc/xbmc#17907]
### Describe the bug
Here is a clear and concise description of what the problem is:

In JSON-RPC API, the types [`Global.Time`](https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/types.json#L26) and [`Player.Position.Time`](https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/types.json#L181) don't accept a duration greater than *23:59:59.999*. A duration should not be limited to one day. Videos or music can last more than 24 hours ([example](https://www.twitch.tv/videos/558585800)).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should accept a duration greater than *23:59:59.999*.

```json
{
  "jsonrpc": "2.0",
  "method": "Player.Seek",
  "params": {
    "playerid": 1,
    "value": {
      "time": { "hours": 24 }
    }
  },
  "id": 1
}
```

## Actual Behavior

Kodi returns an error.
```json
{
  "error": {
    "code": -32602,
    "data": {
      "method": "Player.Seek",
      "stack": {
        "message": "Received value does not match any of the union type definitions",
        "name": "value",
        "type": ["string", "number", "object"]
      }
    },
    "message": "Invalid params."
  },
  "id": 1,
  "jsonrpc": "2.0"
}
```

## Possible Fix

Remove the `"maximum"` property of `"hours"` in [`Global.Time`](https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/types.json#L26) and [`Player.Position.Time`](https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/types.json#L181).

```json
{
  "Global.Time": {
    "type": "object",
    "properties": {
      "hours": { "type": "integer", "required": true, "minimum": 0 },
      "minutes": { "type": "integer", "required": true, "minimum": 0, "maximum": 59 },
      "seconds": { "type": "integer", "required": true, "minimum": 0, "maximum": 59 },
      "milliseconds": { "type": "integer", "required": true, "minimum": 0, "maximum": 999 }
    },
    "additionalProperties": false
  },
  "Player.Position.Time": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "hours": { "type": "integer", "minimum": 0, "default": 0 },
      "minutes": { "type": "integer", "minimum": 0, "maximum": 59, "default": 0 },
      "seconds": { "type": "integer", "minimum": 0, "maximum": 59, "default": 0 },
      "milliseconds": { "type": "integer", "minimum": 0, "maximum": 999, "default": 0 }
    }
  }
}
```

### To Reproduce

1. In Kodi, *Allow remote control via HTTP* (*Settings* / *Services* / *Control*).
2. Play a video.
3. Execute (by changing the IP address) : `curl -d '{ "jsonrpc": "2.0", "method": "Player.Seek", "params": { "playerid": 1, "value": { "time": { "hours": 25 } } }, "id": 1 }' -H 'Content-type: application/json' -X POST 192.168.1.2:8080/jsonrpc`
4. Kodi returns an error: *Invalid params.*

### Debuglog

The debuglog can be found here:

Kodi log nothing.

### Screenshots 
Here are some links or screenshots to help explain the problem:

NA

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

NA

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC 2020.03-1
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Tolriq** [comment]
IMO the name is time so the limits makes senses, if you allow 24h then why not 70 minutes?

Proper solution would be to add a days parameter to keep consistency.

**Comment by regseb** [comment]
The hour limit can be removed because it is the highest unit. If the maximum of minutes is removed: there will be several ways to write a duration (70 minutes = 1 hour 10 minutes).

Kodi already displays durations without limit on hours (like [*YouTube*](https://www.theverge.com/2020/2/24/21150488/chilledcow-lofi-hiphop-livestream-youtube-termiantion-vod-anime-study-girl) or [*Twitch*](https://www.twitch.tv/videos/558585800)):

![kodi](https://user-images.githubusercontent.com/1262990/82572735-15633400-9b85-11ea-94b6-be2dbce046f7.jpg)

The `Player.GetProperties` method returns the following value for `totaltime` (which is of type [`Global.Time`](https://kodi.wiki/view/JSON-RPC_API/v10#Player.Property.Value)):

```json
{"id":1,"jsonrpc":"2.0","result":{"totaltime":{"hours":46,"milliseconds":0,"minutes":0,"seconds":37}}}
```

The display and output data of the API don't have maximum for hours. Only the input data are limited. So I propose to remove the maximum on the hours to solve this issue.
