### ISSUE TITLE
Leia 18.7 - Firestick 4K - Crash on playback

### ISSUE THREAD

**Issue by matthuisman** [xbmc/xbmc#17904]
I've now heard from 2x users using Firestick 4K that trying to playback content in Leia nightly causes crashes.

https://github.com/peak3d/inputstream.adaptive/pull/440#issuecomment-628886818
https://forum.kodi.tv/showthread.php?tid=353316&pid=2950893#pid2950893

Needing more info - but wanted to start this so I can update with info as I get it.
It doesn't happen in 18.6 - so it's a regression.

I know 18.7 is close  and not many users will be using 18.7 nightlies - so could be quite a big issue if 18.7 is released for Firestick users

### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by matthuisman** [comment]
@facakente
Can you please confirm you are still having the crash issue on Leia 18.7 nightly?
I assume you reverted back to 18.6 - but if you could help us diagnose the 18.7 issue - that would be great.

Did it crash on all content / other add-ons?
Was it related to frame-rate switching (eg. if disable that - it works?)

**Comment by facakente** [comment]
Just tested this build , still crashing kodi and kicking me out , it happens with mandalorian for example or Togo where it starts loses dv signal and crashes or lady and tramp where the same happens as in mandalorian , if playing Star Wars movie it works fine , currently with framerate set to on start /stop .

Btw if playing in hdr10 the same happens.


Tested Netflix and works fine , no problems so far.

Resuming only some titles from Disney where pattern is the one above.

**Comment by matthuisman** [comment]
If you turn off frame rate matching does it work? Just trying to find cause of crashing- nothing else

**Comment by matthuisman** [comment]
So it only crashes in Disney? No where else.
Even DV elsewhere etc.

 If so, could be an issue with chapters or inputstream adaptive.

**Comment by facakente** [comment]
I have disabled framerate match and same happens.

This might be related with changes in the input stream definitely , as it used to work before , when I had other issues , Which were resolved with changes , but something is causing this now .

**Comment by matthuisman** [comment]
OK. So I'm confident its not a kodi issue then. I've closed this issue. Didn't want to hold up 18.7. 

Its a hard crash correct? Kicks you out of kodi altogether? And it does it as soon as you try to play? Or after a bit of time? Do you see any video before it crashes?

**Comment by facakente** [comment]
Mandalorian and lady and tramp i see no video it kicks me straightway , with Togo it plays a bit and kicks me out . My audio is English , no subtitles.

**Comment by matthuisman** [comment]
If you turn off L1 device in Disney settings does it work?

If yes, how about if you have that on, but all settings below it turned off?

**Comment by facakente** [comment]
I need to test it , but I suppose that will work as before it worked for me in the matrix build , only after changes applied in the input stream it started to crash.

I can test later anyway .

Just post me the old version of input stream, or does it come already with nightly leia ?!

**Comment by facakente** [comment]
With this build u sent me , only way to play mandalorian is disabling l1, otherwise it kicks me out. However maximum I get is 720p which is expected.

**Comment by facakente** [comment]
Can u post me the original input stream where I was unable to play DV ?! So I can install it on top of this nightly leia build

**Comment by facakente** [comment]
Ok just tried 2.4.5 Input stream in nightly leia and it starts but sec later it crashes and kicks me out.

**Comment by matthuisman** [comment]
pretty sure you can't actually update IA on Matrix correctly.
So just keep testing with 18.7 nightly

I'll get a 2.4.4 build soon

**Comment by facakente** [comment]
Ok let me know when u have it and I will install , in meantime I have uninstalled 2.4.5
