### ISSUE TITLE
Lircmaps.xml in .kodi/keymaps ignored

### ISSUE THREAD

**Issue by royboy626** [xbmc/xbmc#17918]
### Describe the bug
Here is a clear and concise description of what the problem is:

Linux Fedora 32; Kodi and pvr.mythtv compiled from master github branches; LIRC and mceusb remote
$HOME/.kodi/userdata/keymaps/Lircmaps.xml ignored.
$HOME/.kodi/userdata/Lircmaps.xml is read/used.
Using the \<remote device="mceusb"\> section of Lircmap.xml and added line:
\<recordedtv\>RecTV\</recordedtv\>
to get my 'Recorded TV' remote button to work. Perhaps this line needs to be added to Lircmaps.xml?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

$HOME/.kodi/userdata/keymaps/Lircmaps.xml should be read and merged/used

## Actual Behavior

$HOME/.kodi/userdata/keymaps/Lircmaps.xml is ignored
$HOME/.kodi/userdata/Lircmaps.xml is used/merged

## Possible Fix

code adjustment to read user localized maps from the keymaps directory.
add \<recordedtv\>RecTV\</recordedtv\> or similar to Lircmap.xml

### To Reproduce

1. Edited $HOME/.kodi/userdata/keymaps/Lircmaps.xml
2. Kodi ignores the above file.
3. Edit $HOME/.kodi/userdata/Lircmaps.xml
4. Changes are read by Kodi ('Recorded TV' button works)

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/nahiruweri.kodi
This is with $HOME/.kodi/userdata/Lircmaps.xml present

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Using LIRC and 'Recorded TV' button inactive. Read documentation and found remote.xml properly set up. A line with recordedtv was missing from Lircmaps.xml. Added the line (as above) and button works when Lircmap.xml is in userdata directory, but not when present only in userdata/keymaps

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: github master branch pulled May 16, 2020

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by asavah** [comment]
The file should be named `Lircmap.xml` not Lircmap**s** (no 's' after map)
The file should be placed in `$HOME/.kodi/userdata/` and not in `$HOME/.kodi/userdata/keymaps`
This is properly documented in the wiki https://kodi.wiki/view/LIRC

Quote from the wiki:
>  Do not confuse the Lircmap.xml with Keyboard.xml.

**Comment by DaVukovic** [comment]
thanks ^^
