### ISSUE TITLE
TVDB scraper not parsing results correctly leading to bad Titles and no plot.

### ISSUE THREAD

**Issue by at2010** [xbmc/xbmc#17911]
### Describe the bug
Here is a clear and concise description of what the problem is:

TVDB scraper version 3.2.5 (metadata.tvdb.com)

The scraper seems to be retrieving information correctly but is parsing it incorrectly so that the episode Title and Plot are not correct.
Error seems to be in **ParseEpisodeDetails of tvdb.xml**
Authorization Bearer id may not be valid in **GetEpisodeDetailsAuth**

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Example input file name:
Gangs of London\Gangs of London - 1x06 - Episode 6.x265.mkv
should yield title:
**1x06. Episode 6**
and a plot.
## Actual Behavior

The title shows as
**1x06. Episode 6","filename":"series/364387/episodes/5ea32f02a504d.jpg**
plot is empty

## Possible Fix

Error seems to be in **ParseEpisodeDetails of tvdb.xml**
Authorization Bearer id may not be valid in **GetEpisodeDetailsAuth**. This function returns an empty `<Details></Details>`

### To Reproduce

1. Create a "Gangs of London" folder
2. Rename a video file to "Gangs of London - 1x06 - Episode 6.x265.mkv" and put in folder (1)
3. add folder to kodi videos with type "TV shows" and information provider "The TVDB", language "en"
4. scan folder into Kodi

### Debuglog

The debuglog can be found here:
https://pastebin.com/8YVXEiR5

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

This is the cache file cache="episode-7596879-en.json" referenced in the log file
`{"data":{"absoluteNumber":null,"airedEpisodeNumber":6,"airedSeason":1,"airedSeasonID":1821976,"airsAfterSeason":null,"airsBeforeEpisode":null,"airsBeforeSeason":null,"contentRating":null,"directors":["Xavier Gens"],"dvdChapter":null,"dvdDiscid":"","dvdEpisodeNumber":null,"dvdSeason":null,"episodeName":"Episode 6","filename":"series/364387/episodes/5ea32f02a504d.jpg","firstAired":"2020-05-28","guestStars":[],"id":7596879,"imdbId":"tt10062166","isMovie":0,"language":{"episodeName":"en","overview":"en"},"lastUpdated":1588097936,"lastUpdatedBy":84702,"overview":"With the Wallaces retreating to a safehouse, Marian puts the pressure on Sean to uncover Finn’s killer – and Sean wrestles with who he has become. How far is he prepared to go in pursuit of the truth? Meanwhile, Elliot’s recuperation is interrupted by a new danger.","productionCode":"","seriesId":364387,"showUrl":"","siteRating":0,"siteRatingCount":0,"thumbAdded":"","thumbAuthor":null,"thumbHeight":"360","thumbWidth":"640","writers":["Lauren Sequeira"]}}`

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows Pro 1909 x64
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@at2010 

Thanks for the report, but the issue was resolved yesterday. Update to v3.2.6

**Comment by at2010** [comment]
For me only version 3.2.5 is showing in the repository using 18.6

**Comment by at2010** [comment]
Also this page shows 3.2.5 as current.
https://kodi.tv/addon/tv-information/tvdb
Where can I find 3.2.6

**Comment by at2010** [comment]
ok found 3.2.6 by changing the download link from the information page. But this new version still has an issue. Opening new bug
