### ISSUE TITLE
TVDB scraper not parsing results correctly. No Plot for some episodes

### ISSUE THREAD

**Issue by at2010** [xbmc/xbmc#17912]
### Describe the bug
Here is a clear and concise description of what the problem is:

TVDB scraper version 3.2.6 (metadata.tvdb.com)

The scraper seems to be retrieving information correctly but is parsing it incorrectly so that the episode Plot is missing.
This is not a new episode, but rather selecting Refresh/Ignore Local Data and refresh from internet.

Error seems to be in **ParseEpisodeDetails of tvdb.xml**

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Example input file name:
Gangs of London\Gangs of London - 1x05 - Episode 5.mkv
should have a plot (from thetvdb.com)

> Hidden safely away in a farmhouse in the middle of nowhere, Darren wrestles with the chaos he has unleashed. But when a mysterious group of mercenaries set their sights upon him, will Kinney be able to get there in time to prevent bloodshed?

**Please Note:**
The epsiode "Gangs of London - 1x06 - Episode 6.mkv" reported in issue 17911 now parses plot correctly. Episodes 3, 5, 8, 9 do not parse the plot, but the title is ok.

## Actual Behavior

Plot is empty

## Possible Fix

Error seems to be in **ParseEpisodeDetails of tvdb.xml**

### To Reproduce

1. Create a "Gangs of London" folder
2. Rename a video file to "Gangs of London - 1x05 - Episode 5.mkv" and put in folder (1)
3. add folder to kodi videos with type "TV shows" and information provider "The TVDB", language "en"
4. scan folder into Kodi

### Debuglog

The debuglog can be found here:
https://pastebin.com/x303B1WE

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

This is the cache file cache="episode-7596878-en.json" referenced in the log file
`{"data":{"id":7596878,"airedSeason":1,"airedSeasonID":1821976,"airedEpisodeNumber":5,"episodeName":"Episode 5","firstAired":"2020-05-21","guestStars":[],"directors":["Gareth Evans"],"writers":["Gareth Evans","Matt Flannery"],"overview":"Hidden safely away in a farmhouse in the middle of nowhere, Darren wrestles with the chaos he has unleashed. But when a mysterious group of mercenaries set their sights upon him, will Kinney be able to get there in time to prevent bloodshed?","language":{"episodeName":"en","overview":"en"},"productionCode":"","showUrl":"","lastUpdated":1588097928,"dvdDiscid":"","dvdSeason":null,"dvdEpisodeNumber":null,"dvdChapter":null,"absoluteNumber":null,"filename":"series/364387/episodes/5ea32ee1cf356.jpg","seriesId":364387,"lastUpdatedBy":84702,"airsAfterSeason":null,"airsBeforeSeason":null,"airsBeforeEpisode":null,"imdbId":"tt10062164","contentRating":null,"thumbAuthor":null,"thumbAdded":"","thumbWidth":"640","thumbHeight":"360","siteRating":0,"siteRatingCount":0,"isMovie":0}}`

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows Pro 1909 x64
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
I can confirm the issue. Episodes 2, 6, 7 & 9 do not scrape plots for me when using v3.2.6 on Kodi v18.6

Log... https://paste.kodi.tv/fuvilacira.kodi

**Comment by KarellenX** [comment]
Fixed with the release of v3.2.7

https://github.com/xbmc/repo-scrapers/commit/b8c015aff3179af3ab301b3d7c32dcca8e96ecfc
