### ISSUE TITLE
Documentation - README.Linux.md

### ISSUE THREAD

**Issue by royboy626** [xbmc/xbmc#17919]
### Describe the bug
Here is a clear and concise description of what the problem is:

github master branch pulled May 16, 2020
file kodi/docs/README.Linux.md - possible addition of text:
For Fedora 32, an incomplete dependency install:
dnf groupinstall 'C Development Tools and Libraries'

 noone='alsa-lib-devel avahi-devel bzip2-devel ccache cmake crossguid
 dbus-devel doxygen egl-wayland ffmpeg-devel fmt fstrcmp-devel giflib-devel
 gtest gtest-devel libass-devel libbluray-devel libcdio-devel
 libcec-devel libcurl-devel libjpeg-turbo-devel libtool libusbx-devel
 libuuid-devel libva-devel libvdpau-devel libXext-devel libXrandr-devel
 libxkbcommon-devel lirc-devel lzo-devel mariadb-devel mesa-libEGL-devel
 mesa-libGL-devel mesa-libGLU-devel openssl-devel pulseaudio-libs-devel
 rapidjson-devel shairplay-libs sqlite-devel swig systemd-devel taglib-devel
 tinyxml-devel wayland-devel wayland-protocols-devel yasm-devel'
dnf install $noone
This incomplete list should be enough to get someone started with a compile on a rpm/dnf based system. Some features will be missing but hopefully it compiles an executable file.

END OF REPORT

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Add text to documentation for compile on rpm/dnf based Linux systems.

## Actual Behavior

documentation for compile on rpm/dnf based Linux systems absent.

## Possible Fix

Add text

### To Reproduce

1. rpm/dnf documentation missing
2.
3.

### Debuglog

The debuglog can be found here:
Debug log

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: github master branch pulled May 16, 2020

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Why don't you make a PR instead?

**Comment by DaVukovic** [comment]
Probably because we already have: 

https://github.com/xbmc/xbmc/blob/master/docs/README.Fedora.md

If this is based on system which are using rpm/dnf it should not be located at the general Linux.md file, no? Some deps might be missing for being able to build current Kodi master and those missing deps should be added then to the Fedora-docs
