### ISSUE TITLE
Json RPC "Player.GetProperties" missing data - strange behaviour

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#17915]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have Netflix add-on installed on latest Kodi 19 nightly
i have exported some tvshows and enabled kodi scraper to the exported folder
(all exported files are STRM that point to add-on to play a video with inputstreamadaptive)

now i trying to play the episodes from Tv Show menu but from "Recentry added episodes" section:
![image](https://user-images.githubusercontent.com/3257156/82584469-d210c180-9b94-11ea-83b4-d08bd61122c6.png)

but the RPC Json `Player.GetProperties` return partial data
and happen only if you try to play a video from Recentry added episodes screen

i use these properties: (player id is taken in realtime so it is exactly)
```python
            player_state = common.json_rpc('Player.GetProperties', {
                'playerid': self.active_player_id or player_id,
                'properties': [
                    'audiostreams',
                    'currentaudiostream',
                    'currentvideostream',
                    'subtitles',
                    'currentsubtitle',
                    'subtitleenabled',
                    'percentage',
                    'time']
            })
```

In my tests json rpc call return always this,
so many data are missing: `currentsubtitle`, `currentvideostream`, `subtitles`
<pre>
{
    'audiostreams': [{
            'bitrate': 131072,
            'channels': 2,
            'codec': 'aac',
            'index': 0,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'ger',
            'name': 'AAC ',
            'samplerate': 0
        }, {
            'bitrate': 655360,
            'channels': 6,
            'codec': 'eac3',
            'index': 1,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'ger',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 131072,
            'channels': 2,
            'codec': 'eac3',
            'index': 2,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': True,
            'language': 'eng',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 655360,
            'channels': 6,
            'codec': 'eac3',
            'index': 3,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': True,
            'language': 'eng',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 131072,
            'channels': 2,
            'codec': 'aac',
            'index': 4,
            'isdefault': False,
            'isimpaired': True,
            'isoriginal': False,
            'language': 'eng',
            'name': 'AAC ',
            'samplerate': 0
        }, {
            'bitrate': 655360,
            'channels': 6,
            'codec': 'eac3',
            'index': 5,
            'isdefault': False,
            'isimpaired': True,
            'isoriginal': False,
            'language': 'eng',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 131072,
            'channels': 2,
            'codec': 'eac3',
            'index': 6,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'fre',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 655360,
            'channels': 6,
            'codec': 'eac3',
            'index': 7,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'fre',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 655360,
            'channels': 6,
            'codec': 'eac3',
            'index': 8,
            'isdefault': True,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'ita',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 131072,
            'channels': 2,
            'codec': 'aac',
            'index': 9,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'ita',
            'name': 'AAC ',
            'samplerate': 0
        }, {
            'bitrate': 131072,
            'channels': 2,
            'codec': 'eac3',
            'index': 10,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'rum',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 655360,
            'channels': 6,
            'codec': 'eac3',
            'index': 11,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'rum',
            'name': 'DD+ ',
            'samplerate': 0
        }
    ],
    'currentaudiostream': {
        'bitrate': 655360,
        'channels': 6,
        'codec': 'eac3',
        'index': 8,
        'isdefault': True,
        'isimpaired': False,
        'isoriginal': False,
        'language': 'ita',
        'name': 'DD+ ',
        'samplerate': 0
    },
    'currentsubtitle': None,
    'currentvideostream': None,
    'percentage': 0.021548116579651833,
    'subtitleenabled': False,
    'subtitles': [],
    'time': {
        'hours': 0,
        'milliseconds': 309,
        'minutes': 0,
        'seconds': 0
    },
    'elapsed_seconds': 0
}
</pre>

if i try to play by browsing folders data are right
if try to play by  browsing add-on folders data are right

UPDATE:
the problem happen also when you not set a video screaper to folder
and try to play a video

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

return all video data of played video

## Actual Behavior

missing: `currentsubtitle`, `currentvideostream`, `subtitles`

### To Reproduce

1. Install netflix 
2. export a season
3. play from Kodi menu page Tv shows , "Recentry added episodes" section

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/nozawicatu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64
 - Kodi version: 19, 20 nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
i confirm that this still happens on Kodi 20
@enen92 can you give another attempt to fix it before the Kodi 20 final?
thank you

**Comment by enen92** [comment]
Nope sorry. This issue happens because JSON rpc uses fixed IDs to decide on the fact it is playing video or audio. Kodi itself assigns an id to a player. Looks like changing those fixed IDs breaks some sort of obscure functionality like mixed playlists (no idea if that actually is a supported and documented feature or something that has always worked by luck). Anyway, changing this is opening a can of worms I am not interest in opening.
Maybe the way to go is to create a new endpoint: `PlayerGetPropertiesByPlayerId` and leave this one as is.

**Comment by CastagnaIT** [comment]
then please add a new RPC endpoint
since `Player.GetProperties` is currently useless because it does not work

**Comment by enen92** [comment]
> then please add a new RPC endpoint since `Player.GetProperties` is currently useless because it does not work

I am not interested in fixing this sorry. I did not break this in the first place and tried once to fix it just for the sake of it (for the challenge, correctness and to learn a bit more) but it was refused (no hard feelings). That being said, I won't spend more time into it.

**Comment by CastagnaIT** [comment]
@enen92 i start debuggin and i have found the problem

since RPC call `Player.GetActivePlayers` also give a wrong playerid (the value is 0 instead of 1)
i start debugging from here,
`GetActivePlayers` request get the playerid from `PlayListPlayer`, and this class has a wrong id set to `m_iCurrentPlayList`

this value in this case is set by `PlayListPlayer::SetCurrentPlaylist` that come from: `CPlayListPlayer::Play`
so here: https://github.com/xbmc/xbmc/blob/master/xbmc/PlayListPlayer.cpp#L260-L273

we can see that the `playlist` var is set to 0 when `pItem->IsAudio()` is true
this method IsAudio come from `CFileItem`, and when executed is all good until arrive to this last line:
`return URIUtils::HasExtension(m_strPath, CServiceBroker::GetFileExtensionProvider().GetMusicExtensions());`
where check for the file extension, this is the problem
because it check also for `.strm` extension then return always true because think that the file is audio where instead is video,
then playerid become wrong (0 instead of 1 of video type) with all others ripercussions to JSON-RPC calls

this extension has been add somewhere but until now i dont have understand where is
the method called to get the list of audio extension is this `GetMusicExtensions`:
https://github.com/xbmc/xbmc/blob/master/xbmc/utils/FileExtensionProvider.cpp#L54-L61

in fact if i force removing the `.strm` from the list of extensions and the RPC calls now works good!

so what we can do? STRM can be both types audio and video,
what to do now?
remove STRM extension from these list of extension or what else?

**Comment by CastagnaIT** [comment]
the behaviour is changed from this PR: https://github.com/xbmc/xbmc/pull/11747
has changed the method `CGUIWindowVideoBase::PlayMovie` in GUIWindowVideoBase.cpp
where before the playlist was fixed to PLAYLIST_VIDEO, after that use the IsAudio/IsVideo to set the playlist type
