### ISSUE TITLE
Media Stubs Cannot Display Messages without Optical Drive Present

### ISSUE THREAD

**Issue by pkscout** [xbmc/xbmc#17934]
### Describe the bug

If you create media stub files (either with custom messages or no messages at all), the stub message is never displayed because Kodi instead shows a message that there is no optical drive present.  If you connect an optical drive then the stub messages are displayed.

I believe this is bug because user preferenced messages should show instead of generic messages that have no effect on functionality (the fact that there is no optical drive doesn't mean Kodi will crash or malfunction if the media stub message is display).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When I create a media stub, I would expect either the default media stub message or the custom one written into the media stub to be displayed.
## Actual Behavior

I get a message that no optical drive is present.

## Possible Fix

Kodi should not check for the presence of an optical drive before displaying media stub messages.

Please see #11655 for information on a fix that was almost implemented 2 years ago.

### To Reproduce

1. Create a media stub as per https://kodi.wiki/view/Media_stubs
2. Scan into library.
3. Select the library item generated by the media stub without an optical drive attached.

### Debuglog

The debuglog can be found here:
N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I am trying to use the media stubs to catalog items from outside services in my Kodi library that will give me a message indicating on what service the item is.  For instance, Netflix or Disney+.  While I know there are addons for many of these services and ways to have items from those addons into the library, the addons are most often limited to 720p. By using media stubs, I can have the item remind me what service/device to use (like the Disney+ app on my TV).

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP
 - [x] OSMC

 - Operating system version/name: any
 - Kodi version: 18.7 (has occurred on any version since media stubs became available)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Yep, that is an oldie. Seen it mentioned a few times. 

Previously reported here and closed, but I believe it is a bug... https://github.com/xbmc/xbmc/issues/16998
