### ISSUE TITLE
[Feature Request][Cosmetic Change] Show Sync playback to display is enabled in audio settings

### ISSUE THREAD

**Issue by Dnkhatri** [xbmc/xbmc#17930]
Sync playback to display breaks or stops passthrough audio. Advance kodi users are probably aware of it but new and novice users are not. A button on 1 settings page breaking all the options on another page without any visual indicator is bad UI. So I think a text indicator that says sync playback to display is enabled  and audio passthrough will not work should be mentioned above the audio passthrough settings when enabled.

**Comment by enen92** [comment]
We don't use github issues for feature requests, only actual issues.
Please use the forum instead: https://forum.kodi.tv/forumdisplay.php?fid=9
