### ISSUE TITLE
Subtitles are covered by OSD on pause

### ISSUE THREAD

**Issue by guss77** [xbmc/xbmc#17952]
### Describe the feature
Here is a clear and concise description of what the problem is:

Some skins - and very notably the current Kodi default skin Estuary - have a "video paused" view that shows a UI covering the bottom and top of the screen. When viewing video with subtitles or closed captions, the UI elements cover the captions, making it harder - sometimes impossible - to read them.

This is a serious problem for people that are hard of reading, or even just when there is a lot of stuff going on in the video: I find myself pausing when viewing Japanese videos when the characters are talking very fast or one on top of each other (it is common in some types of videos), so I can take the time to read the subtitles. This effort is completely undone by over-enthusiastic skins - and Estuary is a great example although far from the only one - that like to cover the bottom 10% of the screen on pause. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I think the correct approach is to make sure that subtitles are not covered by skin UI regardless of which UI is used and its size. When paused, and a skin UI is layered over the subtitles, the subtitle position should be changed so that it is not covered - likely just raised above the bottom UI part. This is similar to how the Netflix web player behaves: when you move the mouse and a the bottom seekbar and buttons are showing, the Netflix player raises the location of the subtitles so they show above the player UI.

## Actual Behavior

Here is Estuary blocking the viewer from reading the captions:

![Screenshot_20200527-182848](https://user-images.githubusercontent.com/381782/83041344-0d096e00-a049-11ea-917b-818c1a39a36a.png)

I've tried reporting the issue in Estuary bug report forum, but it wasn't addressed (or even acknowledged) - and I'm actually OK with that, as this is not only an Estuary problem (there are other skins with similar issues: the otherwise excellent Estouchy skin has a pause UI that takes a huge 20% of the screen, while the popular Aeon Nox skin completely covers the captions and there isn't even a part that is somewhat transparent, like in Estuary).

## Possible Fix

A possible fix is discussed in the expected behavior. Another - possibly easier - fix would be to have an alternate way to pause the video player without showing the paused view. This would also be useful for Frame Advance control for people who want to use that without the overlaying UI.

### To Reproduce

1. Play a video with subtitles or closed captions.
2. Press pause while a caption is being shown

### Screenshots 
Here are some links or screenshots to help explain the problem:

See above.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu
 - Kodi version: 18.6

**Comment by guss77** [comment]
I believe I have followed the rules, except that I removed the "debug log" section as I do not think it is relevant.

**Comment by ronie** [comment]
there's a proposed change being discussed here: https://github.com/xbmc/xbmc/pull/17920

**Comment by DaVukovic** [comment]
I changed the issue-title as we don't accept "Feature requests" in here. But this also sound like an "issue" to me.

**Comment by jjd-uk** [comment]
> See issue #17952 for the pause OSD problem. I don't think using a timeout here will be a good solution: hide the OSD after some time, or show the OSD after some time? The first one makes the use case of pausing to read subtitles annoyingly slow, while the second one makes it annoyingly repetitive (pause, try to read something, curses - the OSD came up again, play and immediatly pause to get a few more seconds to read, lather rinse repeat).

> Moving the subtitles, while understandably a lot of core work, seems like the sanest approach: it will solve the problem for all skins instead of just for Estuary and is also what other video players with a similar OSD problem are doing.

Replying here as although has some relevance to PR it doesn't specifically concern that PR.

My plan was to have several selectable options for what happens to OSD when paused governed by a setting that includes timeout values.

Show OSD when paused:

Always - present behavior
Never - OSD does not show when paused
10s, 20, 30s, 1 min, 2 min - OSD disappears after this amount of time, reason is for people with plasma oled displays who want to protect against burn in.

**Comment by guss77** [comment]
Awesome to see this solved! Thank you very much.
