### ISSUE TITLE
[JSON-RPC] VideoLibrary.RefreshEpisode always uses file name instead of the given title

### ISSUE THREAD

**Issue by bbijoch** [xbmc/xbmc#17959]
### Describe the bug
Kodi is ignoring 'title' field in JSON-RPC VideoLibrary.RefreshEpisode and is always using filename to search movie db. 

I have a tvshow episode file: "Big Little Lies S01E06.mp4" and Kodi recognized it correctly. But I want to change the metadata for that file for completely different tvshow and episode. I see that Kodi JSON-RPC gives us this possibility, because there is an API call VideoLibrary.RefreshEpisode with "title" field in it. I want this episode to be recognized as "Breaking Bad S01E05" (I know that is ridiculous, but that's just an example). So I am sending a request filled with that title - the request is under "To Reproduce". Episode is updated but to the same metadata as before, so my guess is that filename was taken to consideration, "title" field was omitted.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Episode under episodeid=1897  should contain updated title and other info according to data provided in VideoLibrary.RefreshEpisode.

## Actual Behavior

Let's check, request:
```
{
  "jsonrpc": "2.0",
  "method": "VideoLibrary.GetEpisodeDetails",
  "id": 45,
  "params": {
    "episodeid": 1897,
    "properties": [
      "title",
      "season",
      "episode",
      "showtitle",
      "file"
    ]
  }
}
```
Responce:
```
{
  "id": 45,
  "jsonrpc": "2.0",
  "result": {
    "episodedetails": {
      "episode": 6,
      "episodeid": 1897,
      "file": "smb://192.168.1.100/TVShows/Big Little Lies/Big Little Lies Season 1 Mp4 1080p/Big Little Lies S01E06.mp4",
      "label": "Burning Love",
      "season": 1,
      "showtitle": "Big Little Lies",
      "title": "Burning Love"
    }
  }
}
```
So, nothing has changed. I also tested VideoLibrary.RefreshMovie and movie refreshing is working fine with custom title.

### To Reproduce

Request:
```
{
  "jsonrpc": "2.0",
  "method": "VideoLibrary.RefreshEpisode",
  "params": {
    "episodeid": 1897,
    "ignorenfo": true,
    "title": "breaking bad s01e05"
  }
}
```
Response:
```
{
  "jsonrpc": "2.0",
  "method": "VideoLibrary.OnRemove",
  "params": {
    "data": {
      "id": 1897,
      "type": "episode"
    },
    "sender": "xbmc"
  }
}
```
```
{
  "jsonrpc": "2.0",
  "method": "VideoLibrary.OnUpdate",
  "params": {
    "data": {
      "added": true,
      "item": {
        "id": 1897,
        "type": "episode"
      }
    },
    "sender": "xbmc"
  }
}
```

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.7

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Do I understand correctly?

You have a file named **Big Little Lies S01E06.mp4**
It is in a folder named **/Big Little Lies/**

You want to rescrape so it becomes... **breaking bad s01e05**

Sorry, but that is not going to happen and this is not a bug. Unless you can clearly explain what the bug is (and not a wish list) this issue will be closed.

**Comment by bbijoch** [comment]
Yes, you are right, but this is only a simple example. In real life I have more complex cases. As your API says there is a possibility to change to what ever I want.
<img width="705" alt="Zrzut ekranu 2020-05-29 o 11 39 29" src="https://user-images.githubusercontent.com/66076388/83245866-a186e400-a1a1-11ea-82a1-354c0f40e766.png">
Please read carefully my bug report again. 
So please fix the "VideoLibrary.RefreshEpisode" api call, or fix the api description.

**Comment by KarellenX** [comment]
Ok, then this is not a bug and the issue will be closed.

As you can appreciate, and I am sure you understand, the Movie component of the library has many differences compared to TV Shows and Episodes. It is not possible to scrape individual episodes. It is not possible to mix episodes from different shows under the one tv show, which is exactly what you are trying to do. 

Refresh means just that. Refresh the information for the episode belonging to the TV Show in which it is located. It does not mean, rescrape into a completely different episode and tv show.

Frankly, I fail to comprehend why you would/need to do this. It is just crazy. Rename your episode file, place it in the correct tv show folder and scrape. How do you end up with an episode named _Big Little Lies S01E06.mp4_ which is actually _breaking bad s01e05_?

**Comment by bbijoch** [comment]
Thank you for the response and I agree with you, that this is crazy.

On the other hand I am using Refresh**Movie** in my app with a "title" property set and it is pretty handy (library scanner makes mistakes sometimes). Then I saw RefreshEpisode and I just try to test that and it is not working the same way - parameter "title" is unused/redundant. The documentation is misleading in that case.

Best regards and keep the great work!

**Comment by HitcherUK** [comment]
I noticed that in your initial test that `title` returns the title of the episode not the TV show which isn't what you were using in your following request.
