### ISSUE TITLE
Only audio on video playback on latest master after PR #17724 (CDVDVideoCodecDRMPRIME)

### ISSUE THREAD

**Issue by J-Bu** [xbmc/xbmc#17968]
---
### Describe the bug
I am using kodi build from git and update it from time to time. After the update today most videos stopped playing like HTS PVR or Videos from the ArdZdf Mediathek. What still worked was Netflix.

During playback of faulty videos the log is filled with following message:
```
2020-05-31 00:53:47.463 T:222833   ERROR <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: End of file (-541478725)
2020-05-31 00:53:47.463 T:222833   ERROR <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: End of file (-541478725)
2020-05-31 00:53:47.655 T:222833   ERROR <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: End of file (-541478725)
```
After git bisect I found the faulty commit which is edea4bcd7e5c578e6d7bae5d48b74ab468f05fb2 which was merging pull request #17724 after reading the pull request I found that there is a new setting to disable this new feature which I did and things started working again.

Should the feature be working on my hardware? Maybe adding a white or black list for it would be a good idea as this could happen to other users too.

Attached is the complete [kodi.log](https://github.com/xbmc/xbmc/files/4706772/kodi.log) and the output of [lspci -vv](https://github.com/xbmc/xbmc/files/4706773/lspci.txt) so you can see detailed hardware informations. Worth noting is also that I am using kodi-gbm maybe that is of interest.

## Expected Behavior
Kodi should play video files without any problems with default settings

## Actual Behavior
Only audio is played back no video

## Possible Fix
Disable setting "Allow using DRM PRIME decoder"

### To Reproduce
Play video via HTS PVR or stream videos via [ARD and ZDF mediathek addon](https://github.com/rols1/Kodi-Addon-ARDundZDF)

### Debuglog
The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/4706772/kodi.log)
[kodi.log with debug logging enabled](https://github.com/xbmc/xbmc/files/4739513/kodi.log)

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo Linux
 - Kodi version: kodi-gbm from git master

**Comment by J-Bu** [comment]
Updated issue according to template

**Comment by jernejsk** [comment]
Please provide proper debug log - Settings -> System -> Logging -> Enable debug logging

**Comment by J-Bu** [comment]
Added [kodi log with enabled debug logging](https://github.com/xbmc/xbmc/files/4739513/kodi.log) to issue description
