### ISSUE TITLE
Kodi 18.7 PVR Simple - Stretch 16:9 Overstretching

### ISSUE THREAD

**Issue by rechena** [xbmc/xbmc#17963]
### Describe the bug
Here is a clear and concise description of what the problem is:

When watching non HD channels on PVR Simple the Stretch 16:9 option on display should resize to 16:9 but its overstretching causing the image to get out of the screen. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The video should be resized(stretched to the 16:9) resolution of the TV which happened in the 18.6 version of Kodi. 

## Actual Behavior

Its overstretching causing the image to get out of the screen. 

### To Reproduce

1. install PVR Simple
2. Setup non HD channel (4:3) 
3.Ask to stretch to 16:9

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Please provide your debuglog - without that we cannot help you.

@peak3d might be the same scaling crop issue we talked lately.

**Comment by rechena** [comment]
Will reinstall the new version again and will report back. I’m doing this in a firestick what’s the best way to get the log? Thanks

**Comment by KarellenX** [comment]
Use the logfile uploader... https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

**Comment by rechena** [comment]
Here’s the log. 

https://paste.kodi.tv/ititemiqun

I can confirm again that after the update to the newest version the issue happens again.

**Comment by peak3d** [comment]
@rechena pls. enable debug logging in settings::system::logging and create another log. thx!
Beside this it's a very old device (Android 5.1 / API level 22), I cannot guarantee that we build special workarounds for such old devices.

**Comment by rechena** [comment]
Will enable and run again @peak3d 
I’m running this on a amazon fire stick I bought last week, so you are saying that I won’t be able to use it with future versions? Seems a bit limiting.

**Comment by peak3d** [comment]
> Running on Amazon AFTT with Android 5.1.1 API level 22, kernel: Linux ARM 32-bit version 3.10.54+
I doubt that amazon sells devices with this Android verion t.b.h. Can you send a reference to the device you bought?

**Comment by peak3d** [comment]
Pls. try this build: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20200530-8f8a2d6d-leia_noscale-armeabi-v7a.apk

**Comment by rechena** [comment]
> > Running on Amazon AFTT with Android 5.1.1 API level 22, kernel: Linux ARM 32-bit version 3.10.54+
> 
> 
> 
> I doubt that amazon sells devices with this Android verion t.b.h. Can you send a reference to the device you bought?
> 
> 
> 
> This is what my 2 years old AFTV stick say:
> 
> Running on Amazon AFTMM with Android 7.1.2 API level 25, kernel: Linux ARM 32-bit version 4.4.120+
> 
> 
> 
> Edit: identified your device, in Germany it's not sold anymore.

![image](https://user-images.githubusercontent.com/3226822/83326911-94382b00-a26f-11ea-8944-6c554ca0efa0.jpeg)

![image](https://user-images.githubusercontent.com/3226822/83326921-aade8200-a26f-11ea-8c21-5335bf70603b.jpeg)

Amazon link: Fire TV Stick with Alexa Voice Remote | streaming media player https://www.amazon.co.uk/dp/B0791RGQW3/ref=cm_sw_r_cp_api_i_KeK0EbMDF26MD

Hope it helps

**Comment by rechena** [comment]
> Pls. try this build: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20200530-8f8a2d6d-leia_noscale-armeabi-v7a.apk

Yep works perfectly :) well at least the issue does not happen anymore :) 

Do you still need the debug log?

**Comment by rechena** [comment]
Oh I’ve also have another older firestick where the same was happening will need to plug it back and check.

**Comment by peak3d** [comment]
A log would be fine nevertheless, we'll need it for further discussions about fix / workaround

**Comment by rechena** [comment]
Here ya go :) 

https://paste.kodi.tv/ufugedutef

Thanks for looking into this

**Comment by peak3d** [comment]
@rechena we need the log after you played a stream which causes the issue.
The linked log ^^ does not contain any video playback.

**Comment by rechena** [comment]
Ok will need to install the official release and do it again, will get it soon

**Comment by peak3d** [comment]
You can also use the fixed version

**Comment by rechena** [comment]
https://paste.kodi.tv/aguxasugib
Took the log with debug and while the playback in the back.  But be aware that the issue does not happen in the fixed version you sent me. 

Log link: https://paste.kodi.tv/aguxasugib

**Comment by peak3d** [comment]
@rechena Is it possible that you record some seconds of the stream which displays the overstretch?
In the log file there are 3 streams played (one HD, and 2 SD), its not clear wich of those have the issue.

**Comment by rechena** [comment]
I can try and do it but will prob need to install the buggy version since it does not happen on this one. But if it helps the issue was happening on the SD channels only.

**Comment by peak3d** [comment]
If you remember the problematic channel, there is no need to re-install the buggy version.
Just provide some seconds recording of your SD channel.

**Comment by rechena** [comment]
Will do. Sorry for the lack of knowledge but how do I share the recording?

**Comment by peak3d** [comment]
Best would be a dropbox link (or similiar) here. you can remove the file after a short time.
If you care about privacy with this snippet, send it via mail to the mail adress linked to my git account.

**Comment by peak3d** [comment]
We push the change as it is - no more debug information necessary, thx for your support here @rechena

**Comment by peak3d** [comment]
Fixed with 18.7.1 Hotfix version
