### ISSUE TITLE
Kodi crashes as soon as it opens on Beelink GT-King doesnt work

### ISSUE THREAD

**Issue by jgalode** [xbmc/xbmc#17980]
### Describe the bug
Here is a clear and concise description of what the problem is:

Here is the other subject where the problem appeared: @CastagnaIT 

Request failed validation during key exchange
>> https://github.com/CastagnaIT/plugin.video.netflix/issues/677

In summary, using the Netflix plug-in while wanting to launch a video after a few seconds Kodi ended up crashing, I provided 3 LOGS and videos in the report

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

launch of the Netflix plug-in and play movie

## Actual Behavior

Error

## Possible Fix

none

### To Reproduce

1. access to the Netflix plug-in : https://github.com/CastagnaIT/plugin.video.netflix/
2. connection on plugin plugin.video.netflix
3. launching a video on the plug-in no matter which one

### Debuglog

The debuglog can be found here:
LOG 1 with Youtube video (part 1): https://paste.kodi.tv/evoxozazed.kodi
LOG 2 with Youtube video (part 2): https://paste.kodi.tv/gonoterani.kodi
LOG 3 with Youtube video (part 3): https://paste.kodi.tv/sasixujaga.kodi

### Screenshots / Videos
Here are some links or screenshots to help explain the problem:

Youtube video with the 3 Kodi crashes:

crash kodi with plug in plugin.video.netflix_1.4.0_20200531_t1 (part1):
>> https://youtu.be/kUuWp0P3xfM

crash kodi with plug in plugin.video.netflix_1.4.0_20200531_t1 (part 2):
>> https://youtu.be/_gf27T_UeQ4

crash kodi with plug in plugin.video.netflix_1.4.0_20200531_t2 (part 3):
>> https://youtu.be/U9l1kyiZ4pk

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: AZW GTKing with Android 9.0.0 API level 28, kernel: Linux ARM 32-bit version 4.9.113
 - Kodi version: Kodi (18.7 Git:20200520-f14f7a84e3). Platform: Android ARM 32-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by peak3d** [comment]
@jgalode pls. attach if possible to the device by terminal then
- adb logcat -c (to clear the log)
- crash kodi
- adb logcat -d | pastebinit to provide the logcat

Thx!

**Comment by jgalode** [comment]
@peak3d @CastagnaIT 

here is the crash log indicated on line 506 : https://paste.kodi.tv/vezehuzuli.kodi

**Comment by peak3d** [comment]
Thx much, this is exactly what I was searching for.
We'll provide a test version soon

**Comment by peak3d** [comment]
@jgalode can you pls. try our hotfix release?
http://mirrors.kodi.tv/releases/android/arm/kodi-18.7.1-Leia-armeabi-v7a.apk

**Comment by jgalode** [comment]
@peak3d

Youtube crash kodi with plug in plugin.video.netflix_1.4.0_20200531_t2 (part 4):
 >> https://youtu.be/NrU6z__0Z00

new log kodi.log: https://paste.kodi.tv/kozorefifu.kodi
new log logcat.txt, the crash log indicated on line 44 : https://paste.kodi.tv/etatifaleq.kodi

**Comment by peak3d** [comment]
This log is not with kodi and the apk I linked, correct? Pls. install first the apk I lined above.

**Comment by peak3d** [comment]
@jgalode can you pls. enable debug logging and provide a new kodi log?

**Comment by jgalode** [comment]
@peak3d 

new big file kodi.log: https://paste.kodi.tv/xuvawuyegu.kodi

**Comment by peak3d** [comment]
@jgalode: Currently I still need both: kodi.log + matching logcat, sry.

**Comment by jgalode** [comment]
@peak3d 

logcat.txt: https://paste.kodi.tv/eqakujetov.kodi

**Comment by peak3d** [comment]
1.) Was this working with kodi version 18.6?
2.) I'll have to add more debug logging and come back with a new apk later...

**Comment by jgalode** [comment]
@peak3d @CastagnaIT 

so I downgrade the version of kodi to 18.6 but this time I have no crash but I have problems with streaming no image of the videos and a micro cut of the loading of the videos around 8 seconds with the disappearance of sound and a continuous black screen without sound and video:

LOG kodi.log: https://paste.kodi.tv/uceluvuyiz.kodi
LOG logcat.txt: https://paste.kodi.tv/vemikiwuja.kodi

**Comment by peak3d** [comment]
Yes issue is that your h/w decoder does not get properly build up (insufficient memory)
What we currently try to archieve is that this gets properly detected - currently the Android API does not provide any information about the failure. Beside this the logcat buffer is very small, so I was not able to read the interesting part (was rolled out). If you have some time left, pls. create another logcat, but play the stream only some seconds.

The test bu

**Comment by peak3d** [comment]
@jgalode test build with more debug: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20200531-9afd7ab5-jgalode-armeabi-v7a.apk

**Comment by jgalode** [comment]
@peak3d 

error 404:
![Capture](https://user-images.githubusercontent.com/19157935/83426291-33efe780-a42f-11ea-9e0f-f6fcc574ed3f.PNG)

**Comment by peak3d** [comment]
It takes some minutes until the build is distributed on all mirrors

**Comment by jgalode** [comment]
@peak3d 

test with new apk kodi:

new LOG kodi.log: https://paste.kodi.tv/awotetakat.kodi
new LOG logcat.txt: https://paste.kodi.tv/ezoqemopoz.kodi

**Comment by peak3d** [comment]
:-( sorry, the build was without changes committed, my fault. Next build is already running and will be soon in this folder: http://mirrors.kodi.tv/test-builds/android/arm

**Comment by peak3d** [comment]
@jgalode ^^ comment edited

**Comment by jgalode** [comment]
@peak3d 

new LOG kodi.log: https://paste.kodi.tv/mapumeyumi.kodi
new LOG logcat.txt: https://paste.kodi.tv/akayejureb.kodi

**Comment by jgalode** [comment]
I'll post the rest tomorrow if necessary for the moment break for tonight

**Comment by peak3d** [comment]
ok, I'll search and maybe come tomorrow with a new test version

**Comment by peak3d** [comment]
Next test build: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20200601-8ab2be56-jgalode-armeabi-v7a.apk

**Comment by jgalode** [comment]
@peak3d 

new LOG kodi.log: https://paste.kodi.tv/giriwujego.kodi
new LOG logcat.txt: https://paste.kodi.tv/ujoditosox.kodi

**Comment by jgalode** [comment]
@peak3d 

I created a share folder on Google drive with the LOGS files, the last 2 LOGs are in the folder 10:

>> https://drive.google.com/drive/folders/1jkr8-aLZGFxKh05cniz5qylRlWjdFigB?usp=sharing

**Comment by jgalode** [comment]
@peak3d 

Files available in folder 11 on Google drive.

kodi.log files are much too heavy in line of code and in size:

new LOG kodi.log: https://drive.google.com/file/d/1ZT_ooXcSeOLRMCSzJ2xgHHRAA-6VR2EW/view
new LOG logcat.txt: https://paste.kodi.tv/ogecusedez.kodi

**Comment by peak3d** [comment]
Thx @jgalode, I'm working on the test build. At least it seems that it's not crashing anymore at playback.

**Comment by jgalode** [comment]
@peak3d 

if it crashes, I will send you the kodi reaction on video

**Comment by jgalode** [comment]
@peak3d 

>> https://drive.google.com/file/d/1vPiBck2uhOwNmNMjNDIT66vl9XM2BApA/view

**Comment by peak3d** [comment]
@jgalode in the first step it was important to get the kodi crashes sorted out. This is nearly finished.
The issue on your device is now, that the AVC secure decoder cannot be initialized, but this is something wrong with your device OS. What you now should try is to enable HEVC codec in netflix options, and hope that a.) the HEVC decoder works fine and b:) most of the streams you are watching are provided in the HEVC codec.

**Comment by jgalode** [comment]
@peak3d @CastagnaIT 

There is a HEVC option for the 4K that I activated, despite that there was no impact on the video streams, still the same bug since the beginning of the subject, I can not do anything more I tried all the possibilities in the plug-in.

Files available in folder 12 on Google drive.

new LOG kodi.log: https://drive.google.com/file/d/19rDxsp48MwuHExnpDJqCoPTrPyM-o_Ml/view
new LOG logcat.txt: https://paste.kodi.tv/iqodixeqip.kodi

**Comment by peak3d** [comment]
Still the h264 (AVC) stream is used, not sure if Netflix provides the hevc streams to your device.
You can also try to use VP9, maybe it works better.

There are 2 more tests we can do, apk 1 is coming soon, but I doubt that it solves the issue.
@CastagnaIT what are the options to set in NX settings that in manifest secure decoder is not forced?

**Comment by peak3d** [comment]
@jgalode while the next apk is building you can try to comment out these lines:
https://github.com/CastagnaIT/plugin.video.netflix/blob/master/resources/lib/services/msl/converter.py#L110-L113

On device the file is in:
 /sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/converter.py

**Comment by peak3d** [comment]
@jgalode the next apk is ready: next apk is ready: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20200602-d9ac6e23-jgalode-armeabi-v7a.apk

I doubt that it solves the issue, but now you have still these 2 options, hopefully one works.
Let me know what happens

**Comment by jgalode** [comment]
> Still the h264 (AVC) stream is used, not sure if Netflix provides the hevc streams to your device.
> You can also try to use VP9, maybe it works better.
> 

![20200602_170035](https://user-images.githubusercontent.com/19157935/83537374-c3130300-a4f4-11ea-94dd-f8ddcf79906e.jpg)


Files available in folder 13 on Google drive.

new LOG kodi.log: https://drive.google.com/file/d/1pmVMrloWpptXdt1zhCDHHUpCmHAQjPEn/view
new LOG logcat.txt: https://paste.kodi.tv/izibubugew.kodi

I will do the manipulations with the new apk and the secure decoder.

**Comment by jgalode** [comment]
> @jgalode the next apk is ready: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20200602-d9ac6e23-jgalode-armeabi-v7a.apk
> 
> I doubt that it solves the issue, but now you have still these 2 options, hopefully one works.
> Let me know what happens

@peak3d 

![20200602_174524](https://user-images.githubusercontent.com/19157935/83540740-01aabc80-a4f9-11ea-9e62-616f4c351b29.jpg)

Files available in folder 14 on Google drive.

new LOG kodi.log: https://paste.kodi.tv/fozezicaco.kodi
new LOG logcat.txt: https://paste.kodi.tv/umoxanejun.kodi

**Comment by peak3d** [comment]
@jgalode have you restarted kodi after the change in python? Because secure decoder is still requested (what shouldn't)

**Comment by jgalode** [comment]
Files available in folder 14 in bis, on Google drive.

to be sure that I restarted well, I forced the stop of kodi this time then I launched it @peak3d 

new LOG kodi.log: https://paste.kodi.tv/bivevukoce.kodi
new LOG logcat.txt: https://paste.kodi.tv/wexukutali.kodi

**Comment by peak3d** [comment]
Sad that nothing changes in behaviour :-( Neither VP9, HEVC, nor disabling secure decoder works for you. All this is working fine here on my test devices.

I finally create a new apk with secure decoder removed (what the change in python file should has be done)

**Comment by jgalode** [comment]
@peak3d 

Do you also have a Beelink GT-King? I have the impression that nothing is optimized for my android TV box for kodi.

**Comment by peak3d** [comment]
No, but it's quite obvisious that they have some issues with their widevine implementation.
I doubt that this device has an official widevine L1 certificate t.b.h., or maybe you can get an firmware update?

http://mirrors.kodi.tv/test-builds/android/arm/kodi-20200602-245c3201-jgalode-armeabi-v7a.apk
disables secure h/w decoder which could work for you, because your device will most probably not get streams from netflix which have high protection (4K / HDR / DV)

**Comment by CastagnaIT** [comment]
@peak3d i am sorry but i was out of the house all day
if you need something i am here

**Comment by jgalode** [comment]
@peak3d @CastagnaIT 

your new apk seems to work, see the video below:
>> https://drive.google.com/file/d/1ffxjErCeQbkNHTJfyDwseHthBh_K8wKG/view

the device has an L1 certificate:
![20200602_184449](https://user-images.githubusercontent.com/19157935/83546827-987b7700-a501-11ea-9801-373e0b73293d.jpg)

the update is good:
![20200602_184559](https://user-images.githubusercontent.com/19157935/83546844-9dd8c180-a501-11ea-8e87-375b5b3e0bbb.jpg)

**Comment by jgalode** [comment]
@peak3d @CastagnaIT 

> For your resolution issue you can try to set min-bandwidth in inputstream.adaptive to 4000000.
> But as said above: netflix will most likely not provide high res videos for your box.
> 
> Do you have Netflix native app installed, and does it provide hier resolution? The go in the native app, and look for the esn. This esn you can check / edit in kodi netflix addon settings.
> 
> If Netflix native app works with higher resolution, then pls. provide a logcat.
> But first try to copy the esn into kodi netflix app

Resolution max 720 x 480 :
>> https://drive.google.com/file/d/11sIm9F_4Lu0ry2c6glOQFJbJlJdo-vxd/view

new LOG kodi.log: https://paste.kodi.tv/cazuxiteso.kodi
new LOG logcat.txt: https://paste.kodi.tv/avohibahuq.kodi

ESN is good:

![20200602_192535](https://user-images.githubusercontent.com/19157935/83550859-c9f74100-a507-11ea-818d-f34e23b64ff0.jpg)

the official netflix app tells me this:
![20200602_193401](https://user-images.githubusercontent.com/19157935/83551104-2a867e00-a508-11ea-89f7-90a5c0575f68.jpg)

**Comment by peak3d** [comment]
So question is if @CastagnaIT can detect this L3^^ and if so avoid writing the HW_SECURE_CODECS_REQUIRED element.

Maybe we can use the same logic as in the esn creator, the created esn already contains the L3 token. 

@jgalode why is the esn "good" ? It is most likely not the same as you can find somewhere in netflix native app.

**Comment by chewitt** [comment]
@jgalode It might be worth looking at the Beelink forums for info about Widevine suppoort. IIRC one of their boxes (GT Ultimate?) had its L1 cert revoked by Google as it was issued to another Beelink box, but the certification is device specific. In those situations Google revokes the cert which kills support on both devices, and then they refuse to recertify.

**Comment by jgalode** [comment]
> @jgalode why is the esn "good" ? It is most likely not the same as you can find somewhere in netflix native app.

look:

![20200602_194602](https://user-images.githubusercontent.com/19157935/83552422-05930a80-a50a-11ea-8c85-67371817dfac.jpg)

**Comment by peak3d** [comment]
@jgalode yes, thats fine

**Comment by peak3d** [comment]
@CastagnaIT or you add an option for such devices to avoid HW_SECURE_CODECS_REQUIRED?

**Comment by CastagnaIT** [comment]
I tested on my L3 device, this modified version HW_SECURE_CODECS_REQUIRED is not more added to MPD manifest i have leave the tag value empty (from what I've seen ISA only checks the word "HW"), you can try:
[plugin.video.netflix_1.4.0_20200602_t1.zip](https://github.com/xbmc/xbmc/files/4718844/plugin.video.netflix_1.4.0_20200602_t1.zip)

@peak3d what are the consequences of removing HW_SECURE_CODECS_REQUIRED for all L3 devices?

**Comment by jgalode** [comment]
@CastagnaIT I will test with the official version of kodi without the modifications and take your modified plug-in.

**Comment by CastagnaIT** [comment]
i think you should use the last modified kodi apk of peak3d not the regular kodi verison

@peak3d FYI i had added in the modified NF addon version for jgalode a custom behaviour (specified for this device) to force the L3 ESN, because this device is a L1 and so generate a wrong esn as:
`NFANDROID2-PRV-GTKING-AZW==GTKING-9727-`

**Comment by peak3d** [comment]
@CastagnaIT Issue is that the box DRM tells, that is L1. because of that HW_SECURE is used.
There is no need for you to do it for real L3 devices. only for L1 devices where netflix provides L3 material. Not sure if you get this information from somewhere, but I guess, that beelink is on their blacklist and will alwasy only be L3 (regardless what the device tells)

**Comment by peak3d** [comment]
@CastagnaIT to check if commenting the HW_SECURE_CODECS_REQUIRED works, you'll need a L1 device. On L3 devices inputstream.adaptive already removes the flag.

**Comment by jgalode** [comment]
> I tested on my L3 device, this modified version HW_SECURE_CODECS_REQUIRED is not more added to MPD manifest i have leave the tag value empty (from what I've seen ISA only checks the word "HW"), you can try:
> [plugin.video.netflix_1.4.0_20200602_t1.zip](https://github.com/xbmc/xbmc/files/4718844/plugin.video.netflix_1.4.0_20200602_t1.zip)

yes, it actually crashes:

new LOG kodi.log: https://paste.kodi.tv/ecijotiquw.kodi
new LOG logcat.txt: https://paste.kodi.tv/efakiqagop.kodi

**Comment by CastagnaIT** [comment]
>Not sure if you get this information from somewhere, but I guess, that beelink is on their blacklist and will alwasy only be L3 (regardless what the device tells)

yes beelink should be in blacklist

i was also thinking of finding a way to recognize a non-certified/blacklist L1 device to fall back to L3 automatically, but at the moment i don't understand what checks the official app does...
so for now i am adding a check per device model

@jgalode you have to use last modified apk not regular kodi

**Comment by peak3d** [comment]
> CDVDVideoCodecAndroidMediaCodec::Open: Secure decoder requested: true (stream flags: 1)

This should not be if HW_SECURE_CODECS_REQUIRED is not passed.

**Comment by jgalode** [comment]
@CastagnaIT 

as well as this version of the plug-in that you created for me:

>> https://github.com/CastagnaIT/plugin.video.netflix/files/4707980/plugin.video.netflix_1.4.0_20200531_t2.zip

**Comment by CastagnaIT** [comment]
@peak3d i have removed the text value.... so there is other that set it
@jgalode we are talking about plugin.video.netflix_1.4.0_20200602_t1.zip you can use always this modified version excclude the others

**Comment by peak3d** [comment]
@CastagnaIT do you have a L1 device? If so, how does it look like if you remove / comment out the part and play a stream with it?

**Comment by CastagnaIT** [comment]
@peak3d hi
no i have only a L3 device

No i can not see if he has installed correctly, but if @jgalode follow this path of internal memory card by browsing with some file browser app:
Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.netflix/manifest.mpd

can provide the manifest generated
(some folder can be hidded you have to enable to view also hidden folder)
(FYI this file is created/updated only when netflix verbose debug is enabled)

**Comment by jgalode** [comment]
@CastagnaIT 

hi,

File available in folder 16 on Google drive.

file manifest.mpd: https://paste.kodi.tv/xajicojuro

**Comment by CastagnaIT** [comment]
@jgalode well i think you have done some confusion with files...

delete all nf addon test versions zip's, and use/install only this:
[plugin.video.netflix_1.4.0_20200602_t2.zip](https://github.com/xbmc/xbmc/files/4721879/plugin.video.netflix_1.4.0_20200602_t2.zip)

you have to run it with last modified Kodi apk that peak3d have provided
then let know the results

**Comment by jgalode** [comment]
@CastagnaIT 

File available in folder 17 on Google drive.

file manifest.mpd: https://paste.kodi.tv/yasuzotohi

**Comment by CastagnaIT** [comment]
it is not possible that return this...
are you sure that verbose debug is enabled in nf expert settings?

**Comment by jgalode** [comment]
@CastagnaIT 

as you can see it is active:
![Screenshot_20200603-103928](https://user-images.githubusercontent.com/19157935/83615348-b8a14980-a586-11ea-8c50-55cb9f9945ce.png)

**Comment by CastagnaIT** [comment]
makes no sense....
reboot the device,
then try to play a video and get mpd and kodi.log

**Comment by jgalode** [comment]
@CastagnaIT 

test 1°)

new LOG kodi.log: https://paste.kodi.tv/kirowuyoxi.kodi
file manifest.mpd: https://paste.kodi.tv/giqofojipo

test 2°)

new LOG kodi.log: https://paste.kodi.tv/duvekiruda.kodi
file manifest.mpd: https://paste.kodi.tv/femavatawe

**Comment by CastagnaIT** [comment]
the log shows that you have not installed plugin.video.netflix_1.4.0_20200602_t2.zip
That's why it's all wrong

**Comment by jgalode** [comment]
@CastagnaIT 

I installed your version for a while everything is correct:

![Screenshot_20200603-110758](https://user-images.githubusercontent.com/19157935/83618328-9c071080-a58a-11ea-8c61-6d9a24891c2a.png)

**Comment by CastagnaIT** [comment]
I'm not talking about ESN... but the addon installed:

from your log:

> 2020-06-03 10:55:57.459 T:5905    INFO: [plugin.video.netflix (1)] Started (Version 1.4.0)

this is not the version that i send to you here
if I installed it properly, it would look like this in log:

`INFO: [plugin.video.netflix (1)] Started TEST VERSION T2 (Version 1.4.0)`

then you have not installed the plugin.video.netflix_1.4.0_20200602_t2.zip

**Comment by jgalode** [comment]
@CastagnaIT 

I put everything back in place with your new plugin:

new LOG kodi.log: https://paste.kodi.tv/exabirokag.kodi
file manifest.mpd: https://paste.kodi.tv/udoxubekup

**Comment by CastagnaIT** [comment]
@peak3d now the addon is installed correctly

> 2020-06-03 11:22:01.984 T:9461  NOTICE: CDVDVideoCodecAndroidMediaCodec::Open: Secure decoder requested: false (stream flags: 0)

you can check

**Comment by peak3d** [comment]
@jgalode now with the (for you) correct netflix addon installed, it should work even with stock 18.7. Or, at least with our 18.7.1 Hotfix version

**Comment by jgalode** [comment]
@peak3d @CastagnaIT 

ok thanks for your help, i think passing from the chrome browser i can get the 1080p for nextflix.

It does not matter ;) , I have another option to watch movies in 1080P or 4K (IPTV / torrent / Plex lifetime etc)

**Comment by peak3d** [comment]
Are you talking about Chrome Browser on the beelink GT-King device?
If so, from which information do you know that's 1080p ?

**Comment by CastagnaIT** [comment]
let we know if now the videos played are working

at least i understand if i have to add these changes officially in the addon or not

**Comment by peak3d** [comment]
@CastagnaIT In general the removal of HW_SECURE_CODECS_REQUIRED is not required, because IA already removes the flag for L3 devices, and L1 devices work with it (its even required for L1 devices).

But we have learned here, that there are broken devices, which need a special handling. It's on you to make a settings option (force L3) or handle it hard coded by device. Not sure if you really want to have a special / hardcoded handling for this beelink device. Chinese boxes are in general somewhat out of the ordinary.
I remember my cheap tablet I ordered with 128GB storage, but every byte I wrote to the device  allocated 4 bytes -> It was a physical 32GB, but they modified OS to display 128GB.
-> I propose a setting

**Comment by CastagnaIT** [comment]
@peak3d mmmh yes i understand, but i need to handle also in special way the ESN, I suspect i can't handle it in a "standard" custom way

i mean, in this moment i have another user with an asian android device that is problematic, first i have to figure out how and if i can solve his problem, then i can understand the better way, add a new setting (as you proposed) or add special handling per device model (due to special ESN cases)

**Comment by jgalode** [comment]
@CastagnaIT 

> let we know if now the videos played are working
> 
> at least i understand if i have to add these changes officially in the addon or not

here is a video preview:
https://drive.google.com/file/d/1s9ZCQY0Owb6O5FUQwHfi-mn0M5XVwArs/view

new LOG kodi.log: https://paste.kodi.tv/unaguzabuh.kodi

**Comment by jgalode** [comment]
@CastagnaIT 

yes, as I indicated in video everything works in 540P max in standard quality except that my video capture is blocked the image of the films does not surely pass because of the DRM security of netflix.

**Comment by peak3d** [comment]
Segfault issues are solved, thx @jgalode. Can we close this issue?

**Comment by jgalode** [comment]
@peak3d 

Yes you can close the subject, you're welcome for the information that I have transmitted.

good evening or day
