### ISSUE TITLE
kodi 19 menù bluray

### ISSUE THREAD

**Issue by mistero708** [xbmc/xbmc#17997]
https://we.tl/t-qgyIuM0tRO

**Comment by mistero708** [comment]
log  https://we.tl/t-qgyIuM0tRO  the operating system used is windows 10

**Comment by DaVukovic** [comment]
Good that you closed this one. I edited your initial issue to another title. Please see: https://github.com/xbmc/xbmc/issues/17989#issuecomment-639269200

And as I said at the other issue. Please disable vu+ add-on while trying to grab the log.

**Comment by mistero708** [comment]
https://paste.kodi.tv/eyinuzokoy.kodi
