### ISSUE TITLE
[Depends] failed to find toolchain when building linux native

### ISSUE THREAD

**Issue by sprhawk** [xbmc/xbmc#17999]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm building kodi from source code ( tag: 18.7.1-Leia) under Linux ( Debian 10.2 , arch: x86_64 )
I'm following building guide and first build some depends with  **Kodi's unified depends build system**.

I followed the guide, first run configure under `kodi/tools/depnds`
```
./configure --with-toolchain=/usr --prefix=$HOME/Developer/kodi-deps --host=x86_64-linux-gnu
```
then execute make with
```
make -C target/flatbuffers/
```
it reported `/bin/sh: 1: {MY HOME PATH}/Developer/kodi-deps/x86_64-linux-gnu-native/bin/cmake: not found`

I'm new in building Kodi, I'm not sure this is a bug or a "feature".

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

when execute
```
make -C target/flatbuffers/
```
it should build.

## Actual Behavior

it reported `/bin/sh: 1: {MY HOME PATH}/Developer/kodi-deps/x86_64-linux-gnu-native/bin/cmake: not found`

## Possible Fix

I read `Makefile.include.in ` inside `depends dir`
 https://github.com/xbmc/xbmc/blob/8f9ff4c11f7f8acdf609484d61b82b25f875c21a/tools/depends/Makefile.include.in#L63
here the cmake path doesn't use toolchain argument passed to configure, it looks in prefix, which will be `x86_64-linux-gnu-native/bin/`

I changed L63 in `Makefile.include.in` as
```
CMAKE=$(TOOLCHAIN)/bin/cmake -DCMAKE_TOOLCHAIN_FILE=$(PREFIX)/share/Toolchain.cmake -DCMAKE_INSTALL_PREFIX=$(PREFIX) 
```
and run configure again, and make will succeed.

### To Reproduce

1. clone Kodi source code with tag: 18.7.1-Leia
2. install required build dependencies
3. inside {kodi source}/tools/depends, execute `./configure --with-toolchain=/usr --prefix=$HOME/Developer/kodi-deps --host=x86_64-linux-gnu`
4. make -C target/flatbuffers/

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian 10.2 x86_64
 - Kodi version: 18.7.1-Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sprhawk** [comment]
Is it that I  should use depends/target/cmakebuildsys for cmake bin?

**Comment by sprhawk** [comment]
I have used `make -C tools/depends PREFIX={My Depends Path}` to start build

**Comment by lrusak** [comment]
Do you actually need a full depends build?

**Comment by sprhawk** [comment]
I am using Debian 10, and following building guide for Linux, it says I need to build depends. So you mean I should use system provided version?

**Comment by sprhawk** [comment]
Oh maybe I misunderstood the document, I thought it was step by step procedure
