### ISSUE TITLE
[settings] New Settings - Slider control is not disabled by dependency and spinner control does not show format label

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#17992]
### Describe the bug
Here is a clear and concise description of what the problem is:

- Slider control is not disabled by dependency but shows format label
- Spinner control does not show format label but is disabled by dependency

Example setting for slider control:
```
        <setting id="timeshiftEnableLimit" type="boolean" label="30022" help="30622">
          <level>2</level>
          <default>true</default>
          <control type="toggle" />
        </setting>
        <setting id="timeshiftOnDiskLength" type="number" parent="timeshiftEnableLimit" label="30023" help="30623">
          <level>0</level>
          <default>1</default>
          <constraints>
            <minimum>0.25</minimum>
            <step>0.25</step>
            <maximum>24</maximum>
          </constraints>
          <dependencies>
            <dependency type="enable" setting="timeshiftEnableLimit">true</dependency>
          </dependencies>
          <control type="slider" format="number">
            <formatlabel>30024</formatlabel>
          </control>
        </setting>
```

```
        <setting id="timeshiftEnableLimit" type="boolean" label="30022" help="30622">
          <level>2</level>
          <default>true</default>
          <control type="toggle" />
        </setting>
        <setting id="timeshiftOnDiskLength" type="number" parent="timeshiftEnableLimit" label="30023" help="30623">
          <level>0</level>
          <default>1</default>
          <constraints>
            <minimum>0.25</minimum>
            <step>0.25</step>
            <maximum>24</maximum>
          </constraints>
          <dependencies>
            <dependency type="enable" setting="timeshiftEnableLimit">true</dependency>
          </dependencies>
          <control type="spinner" format="number">
            <formatlabel>30024</formatlabel>
          </control>
        </setting>
```

```
#. format-label: Timeshift - timeshiftOnDiskLength
msgctxt "#30024"
msgid "{0:.2f} hours"
msgstr ""
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

- Slider control is not disabled by dependency but shows format label
- Spinner control does not show format label but is disabled by dependency

## Actual Behavior

Slider control is not disabled by dependency
Spinner control does not show format label.

### To Reproduce

1. Use the provided code samples in any addon
2. Open chosen addons settings to see.

### Debuglog

The debuglog can be found here:

Will upload later today.

### Screenshots 
Here are some links or screenshots to help explain the problem:

<img width="1996" alt="Screenshot 2020-06-03 at 13 47 07" src="https://user-images.githubusercontent.com/4601187/83639117-2018c280-a5a2-11ea-8307-b170016aa748.png">

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by phunkyfish** [comment]
I wan't sure if this was a skin issue, a settings issue or both ;)

**Comment by ronie** [comment]
as for the slider control, this is not implemented in core.
for several other control types, skins can define two sets of textures:
- textures to use when the control is enabled
- textures to use when the control is disabled
this functionality does not exist for the settings slider control though.

**Comment by phunkyfish** [comment]
Cool, thanks for clarifying
