### ISSUE TITLE
menù bluray hd non funzionante su kodi 19  e funzionanente su kodi 18.7

### ISSUE THREAD

**Issue by mistero708** [xbmc/xbmc#18003]
https://paste.kodi.tv/eyinuzokoy.kodi

**Comment by mistero708** [comment]
menù bluray hd non funzionante su kodi 19 e funzionanente su kodi 18.7
log  https://paste.kodi.tv/eyinuzokoy.kodi

**Comment by the-black-eagle** [comment]
As you already have an issue open, can you please stick to posting your logs, comments etc in just that issue https://github.com/xbmc/xbmc/issues/17989 please, rather than keep opening a new one.  Thanks.
