### ISSUE TITLE
[PVR] Reminder feature: Stuck at startup.xml

### ISSUE THREAD

**Issue by sualfred** [xbmc/xbmc#18006]
## Bug report
If a PVR reminder has been set and you startup Kodi at the time when it kicks in,  Kodi will be stucked at `startup.xml` and won't switch to the defined `System.StartupWindow`

### Describe the bug
This is caused by the reminder dialog. 
The very first active window in Kodi is always `startup.xml` and usually there is only a `ReplaceWindow($INFO[System.StartupWindow])`in there. But since the reminder dialog pops in, any `ReplaceWindow()` or `ActivateWindow()` is blocked because of the modal dialog. 
If you press `Cancel` on the reminder, Kodi will be stucked on `startup.xml`. 

Here's a video:
https://www.youtube.com/watch?v=fUFoxtIqNmA

## Expected Behavior
Don't show a reminder dialog during the Kodi startup or login process.

## Actual Behavior
Reminder is kicking in as soon as the PVR stuff is loaded, which is going to happen right at the Kodi startup.

## Possible Fix
Don't show the reminder dialog while `startup.xml` and `loginscreen.xml` is active.
Plus:
Since a lot of skins are using own skin setup or startup routines with custom windows I suggest to delay the reminder dialog if the Kodi uptime is below 30s. This should be enough to bypass any other unexpected skin behaviours or skinshortcuts menu generations to win the race condition.

### To Reproduce
- Set a reminder for a EPG item that is going to start in a few minutes
- Close Kodi an wait until the selected show is live
- Start Kodi

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/abixeveyow.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: matrix master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Dies this also happen with Estuary?

**Comment by sualfred** [comment]
can happen on all skins, see my explanation above. the skin anatomy is the same in all skins

**Comment by ksooo** [comment]
@sualfred could you give this test build a try? => http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20200607-4dbf0995-pvr-fix-reminders-on-startup-x64.exe

**Comment by sualfred** [comment]
@ksooo 
Works perfect
