### ISSUE TITLE
Test failures building Debian package using pbuilder / sbuild

### ISSUE THREAD

**Issue by basilgello** [xbmc/xbmc#18000]
### Describe the bug

Here I will drop test failures and fixes for tests breaking Debian build similar to issue created by @candrews 

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian GNU/Linux 10 buster
 - Kodi version: 19.0 trunk

**Comment by basilgello** [comment]
@lrusak

**Comment by lrusak** [comment]
Why do you run the test suite in the first place?

**Comment by basilgello** [comment]
Building Debian package official way (i.e pbuilder / sbuild) requires "make check" and autopkgtest.
I am preparing the Debian packagibg for 19.0 and whole binary archive.

Of course I can add a fix to Debian patch but I decided to follow the recommended way and file a bug against upstream.
-- 
Vasyl Gello
==================================================
Certified SolidWorks Expert

Mob.:+380 (98) 465 66 77

E-Mail: vasek.gello@gmail.com

Skype: vasek.gello
==================================================
호랑이는 죽어서 가죽을 남기고 사람은 죽어서 이름을 남긴다

June 4, 2020 3:03:29 PM UTC, Lukas Rusak <notifications@github.com> написав(-ла):

**Comment by basilgello** [comment]
Looks like /sys was not bound-mount at all. I am rebuilding the package and will close the issue of build succeeds.

**Comment by basilgello** [comment]
@lrusak For previously failing test (GetCPUFrequency), the issue was in `/sys/bus/cpu/devices/cpu0` not mounted inside pbuilder.

However, the TestSysfsPath test is not thread-safe because of hardcoded `/tmp/kodi-test` file:

https://github.com/xbmc/xbmc/blob/a288c97e191a45ff3c5c3bb54c6ec0bebff854cb/xbmc/platform/linux/test/TestSysfsPath.cpp#L28

The bug manifests only if `ctest` invokes `kodi-test` with `-jX` argument, but Debian's `dh_auto_test` helper is multi-threaded.

I created the following patch adding nanosecond timestamps to file names:

```patch
From 30371e7806913ddf7232cde01cd046531721f9f3 Mon Sep 17 00:00:00 2001
From: Vasyl Gello <vasek.gello@gmail.com>
Date: Fri, 5 Jun 2020 16:23:49 +0300
Subject: [PATCH] TestSysfsPath: Use unique file name for every test

Parallel execution of gtest / ctest exposed data race on
hardcoded file '/tmp/kodi-test'. Add nanosecond timestamp
to filename to mitigate an issue.

Signed-off-by: Vasyl Gello <vasek.gello@gmail.com>
---
 xbmc/platform/linux/test/TestSysfsPath.cpp | 36 +++++++++++++++++++---
 1 file changed, 31 insertions(+), 5 deletions(-)

diff --git a/xbmc/platform/linux/test/TestSysfsPath.cpp b/xbmc/platform/linux/test/TestSysfsPath.cpp
index d43b46a..ac7f621 100644
--- a/xbmc/platform/linux/test/TestSysfsPath.cpp
+++ b/xbmc/platform/linux/test/TestSysfsPath.cpp
@@ -8,24 +8,38 @@
 
 #include "platform/linux/SysfsPath.h"
 
+#include <chrono>
+#include <string>
+#include <sstream>
 #include <fstream>
 
 #include <gtest/gtest.h>
 
 struct TestSysfsPath : public ::testing::Test
 {
-  ~TestSysfsPath() { std::remove("/tmp/kodi-test"); }
+  std::string GetTestFilePath()
+  {
+    using namespace std::chrono;
 
-  std::ofstream m_output{"/tmp/kodi-test"};
+    std::stringstream ss;
+    unsigned long long timestamp = duration_cast< nanoseconds >(
+      system_clock::now().time_since_epoch()).count();
+
+    ss << "/tmp/kodi-test" << timestamp;
+    return ss.str();
+  }
 };
 
 TEST_F(TestSysfsPath, SysfsPathTestInt)
 {
+  std::string filepath = GetTestFilePath();
+  std::ofstream m_output(filepath);
+
   int temp{1234};
   m_output << temp;
   m_output.close();
 
-  CSysfsPath path("/tmp/kodi-test");
+  CSysfsPath path(filepath);
   ASSERT_TRUE(path.Exists());
   EXPECT_EQ(path.Get<int>(), 1234);
   EXPECT_EQ(path.Get<float>(), 1234);
@@ -34,28 +48,40 @@ TEST_F(TestSysfsPath, SysfsPathTestInt)
   EXPECT_EQ(path.Get<uint16_t>(), 1234);
   EXPECT_EQ(path.Get<unsigned int>(), 1234);
   EXPECT_EQ(path.Get<unsigned long int>(), 1234);
+
+  std::remove(filepath.c_str());
 }
 
 TEST_F(TestSysfsPath, SysfsPathTestString)
 {
+  std::string filepath = GetTestFilePath();
+  std::ofstream m_output{filepath};
+
   std::string temp{"test"};
   m_output << temp;
   m_output.close();
 
-  CSysfsPath path("/tmp/kodi-test");
+  CSysfsPath path(filepath);
   ASSERT_TRUE(path.Exists());
   EXPECT_EQ(path.Get<std::string>(), "test");
+
+  std::remove(filepath.c_str());
 }
 
 TEST_F(TestSysfsPath, SysfsPathTestLongString)
 {
+  std::string filepath = GetTestFilePath();
+  std::ofstream m_output{filepath};
+
   std::string temp{"test with spaces"};
   m_output << temp;
   m_output.close();
 
-  CSysfsPath path("/tmp/kodi-test");
+  CSysfsPath path(filepath);
   ASSERT_TRUE(path.Exists());
   EXPECT_EQ(path.Get<std::string>(), "test with spaces");
+
+  std::remove(filepath.c_str());
 }
 
 TEST_F(TestSysfsPath, SysfsPathTestPathDoesNotExist)
-- 
2.17.1

```

and now rebuilding the package fully.
