### ISSUE TITLE
[PVR] Timer settings UI showing first item in list instead type and channel from timer tag

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/xbmc#18010]
### Describe the bug
Here is a clear and concise description of what the problem is:

Timer settings UI showing first item in list instead of timer type and channel from timer tag.

Issues presents itself on both pvr.vuplus and pvr.nextpvr.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Timer settings UI shows the correct items from the new timer tag.

## Actual Behavior

Timer settings UI showing first item in list instead of timer type and channel from timer tag.

## Possible Fix

I think the screen just needs to redraw when opened I'm just not sure how to make the dialog do that. As the dialog is based on a settings dialog maybe this change was introduced by a change to settings. Not sure.

### To Reproduce

1. Go to Guide
2. Select any future programme and add timer
3. The settings UI will show the first timer type in the list and the Any channel (first channel in the list)
4. Select timer type and then cancel, followed by channel and then cancel.
5. Both fields will not show the correct values.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/4740019/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Select a future programme:
![Screenshot 2020-06-06 at 13 34 48](https://user-images.githubusercontent.com/4601187/83944443-72085500-a7fb-11ea-9130-e8109db7933c.png)

Programme info:
![Screenshot 2020-06-06 at 13 35 00](https://user-images.githubusercontent.com/4601187/83944451-89dfd900-a7fb-11ea-8ed4-ab54265c4c79.png)

Add timer dialog - Both timer type and channel are defaulting to first item in list:
![Screenshot 2020-06-06 at 13 35 17](https://user-images.githubusercontent.com/4601187/83944472-b267d300-a7fb-11ea-87fc-6ee07f4b4c2b.png)

But timer type is not the first item in the list:
![Screenshot 2020-06-06 at 13 35 29](https://user-images.githubusercontent.com/4601187/83944500-daefcd00-a7fb-11ea-83a3-6ce385a1939e.png)

Either is channel:
![Screenshot 2020-06-06 at 13 35 42](https://user-images.githubusercontent.com/4601187/83944517-e642f880-a7fb-11ea-9cbc-a8f57fc1391c.png)

After cancelling each change the UI is redrawn and the values are correct.
![Screenshot 2020-06-06 at 13 35 52](https://user-images.githubusercontent.com/4601187/83944535-04a8f400-a7fc-11ea-90ed-9390312b323b.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 10.15.5
 - Kodi version: Latest form git

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by phunkyfish** [comment]
@ksooo any thoughts as to what my might cause this? 

@emveepee FYI

**Comment by emveepee** [comment]
@phunkyfish  thanks.  It is any timer dialog.   Comparing with Leia I can get the desired behaviour by adding 

UpdateFromSetting(false);  

after 

https://github.com/xbmc/xbmc/blob/master/xbmc/settings/windows/GUIControlSettings.cpp#L568

**Comment by phunkyfish** [comment]
Nice, I think you can just call: `UpdateFromSetting();`

It’s looks like this was omitted in the last rework. 

Do you want to PR the change?

**Comment by emveepee** [comment]
I don't think I have enough background for that PR since that Leia Update() wasn't copied over for several of the control BaseSettings overrides There may be a general spot that I haven't found yet

**Comment by phunkyfish** [comment]
If you create the PR someone who knows the code can review and provide feedback.

I see something similar is done for the label types: https://github.com/xbmc/xbmc/blob/f76ad6a5ab5170661f401604b21a040443a434e7/xbmc/settings/windows/GUIControlSettings.cpp#L1611-L1623

**Comment by phunkyfish** [comment]
I hadn't seen you had already created the PR. Thanks!

**Comment by Montellese** [comment]
I found the root of the issue and created a PR to fix it at #18027.
