### ISSUE TITLE
Support to display emojis

### ISSUE THREAD

**Issue by satrik** [xbmc/xbmc#18012]
### Describe the bug
I've tried to display emojis in in the `xbmcgui.Dialog()` but neither the title nor the message can display emojis. 

## Possible Fix
Update the used utf-8/unicode character map.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [x] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
$ uname -a
Linux rpi4 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
$ lsb_release -d
Description:	Raspbian GNU/Linux 10 (buster)
 
- Kodi version:
$ kodi --version
18.6 Git:20200506-40c074c06b Media Center Kodi

**Comment by HitcherUK** [comment]
Requests should be opened on the forum.

**Comment by DaVukovic** [comment]
And because of that, the issue will be closed ;)
