### ISSUE TITLE
Chorus and Kore cannot display addons anymore (since 18.7 upgrade)

### ISSUE THREAD

**Issue by bernd-wechner** [xbmc/xbmc#18049]
### Describe the bug
I use the Chorus (web interface) and Kore (Android app) all the time and use an addon to create great music mixes. Recently we had an upgrade to 18.7 (May 22). No guarantee this correlates perfectly with that but it's possible (as in I'm not 100% sure I've actually done a mix since then but it's likely I have in which case it's not correlated with the upgrade).

Today (after rebooting the Kodi machine actually) I find Chorus just hangs when I got to addons and Kore just reports:

```
Couldn't get addon information. Error: Invalid params.
```

in a pop up.

And Chorus reports on the console:

```
TypeError: _ref is undefinedkodi-webinterface.js:3035:22
    parseAddons http://cyclops.lan/js/kodi-webinterface.js:3035
    getCollection http://cyclops.lan/js/kodi-webinterface.js:3022
    doCallback http://cyclops.lan/js/kodi-webinterface.js:10348
    getEnabledAddons http://cyclops.lan/js/kodi-webinterface.js:10612
    doCallback http://cyclops.lan/js/kodi-webinterface.js:10348
    getAddons http://cyclops.lan/js/kodi-webinterface.js:10599
    doCallback http://cyclops.lan/js/kodi-webinterface.js:10348
    multipleCommands http://cyclops.lan/js/kodi-webinterface.js:10305
    k http://cyclops.lan/js/kodi-webinterface.js:3
    fireWith http://cyclops.lan/js/kodi-webinterface.js:3
    f[0] http://cyclops.lan/js/kodi-webinterface.js:3
    success http://cyclops.lan/js/kodi-webinterface.js:10
    k http://cyclops.lan/js/kodi-webinterface.js:3
    fireWith http://cyclops.lan/js/kodi-webinterface.js:3
    c http://cyclops.lan/js/kodi-webinterface.js:4
    b http://cyclops.lan/js/kodi-webinterface.js:4
```

## Expected Behavior
Well I expect it to work as it always has. Nothing special ;-).

## Actual Behavior
Chorus hangs, and reports a message on the console. Kore reports message in small pop up but neither display my addons any more.

## Possible Fix
Not sure about a fix, but there's a chance this is related to a specific addon and some change to it or to Kodi recently. Any tips on diagnosis are welcome. 

### To Reproduce
Hard to say.

### Debuglog
The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/4768036/kodi.log)

To produce this I:
1. Enabled debug logging
2. Went to Chorus
3. Reloaded the page
4. Clicked on Addons
5. Checked the console and found the above message
6. Tailed the log to confirm last entry was after that.

### Screenshots 
Chorus just looks like this:
![image](https://user-images.githubusercontent.com/7296506/84453727-f2b3cf00-ac9b-11ea-9021-490bc2f0c252.png)

And Kore is trickier as it's a pop up that disappears so a short video rather than static shot is the only way to catch it but I shot the vid then nabbed the frame:
![image](https://user-images.githubusercontent.com/7296506/84453961-9d2bf200-ac9c-11ea-9e46-4fbeddac84ac.png)

## Additional context or screenshots (if appropriate)
In Chorus I can break the JS where the _ref error happens and see:
```
addon
{…}
​addonid: "audioencoder.kodi.builtin.aac"
​label: undefined
​provides: Array []
​type: "kodi.audioencoder"
​<prototype>: Object { … }

addons
addons
(67) […]
​0: Object { addonid: "audioencoder.kodi.builtin.aac", type: "kodi.audioencoder", provides: [], … }
​1: Object { addonid: "audioencoder.kodi.builtin.wma", type: "kodi.audioencoder" }
​2: Object { addonid: "game.controller.default", type: "kodi.game.controller" }
​3: Object { addonid: "game.controller.snes", type: "kodi.game.controller" }
​4: Object { addonid: "metadata.album.universal", type: "xbmc.metadata.scraper.albums" }
​5: Object { addonid: "metadata.artists.universal", type: "xbmc.metadata.scraper.artists" }
​6: Object { addonid: "metadata.common.allmusic.com", type: "xbmc.metadata.scraper.library" }
​7: Object { addonid: "metadata.common.fanart.tv", type: "xbmc.metadata.scraper.library" }
​8: Object { addonid: "metadata.common.imdb.com", type: "xbmc.metadata.scraper.library" }
​9: Object { addonid: "metadata.common.musicbrainz.org", type: "xbmc.metadata.scraper.library" }
​10: Object { addonid: "metadata.common.theaudiodb.com", type: "xbmc.metadata.scraper.library" }
​11: Object { addonid: "metadata.common.themoviedb.org", type: "xbmc.metadata.scraper.library" }
​12: Object { addonid: "metadata.local", type: "xbmc.metadata.scraper.albums" }
​13: Object { addonid: "metadata.themoviedb.org", type: "xbmc.metadata.scraper.movies" }
​14: Object { addonid: "metadata.tvshows.themoviedb.org", type: "xbmc.metadata.scraper.tvshows" }
​15: Object { addonid: "repository.xbmc.org", type: "xbmc.addon.repository" }
​16: Object { addonid: "resource.images.weathericons.default", type: "kodi.resource.images" }
​17: Object { addonid: "resource.language.en_gb", type: "kodi.resource.language" }
​18: Object { addonid: "resource.uisounds.kodi", type: "kodi.resource.uisounds" }
​19: Object { addonid: "screensaver.xbmc.builtin.black", type: "xbmc.ui.screensaver" }
​20: Object { addonid: "screensaver.xbmc.builtin.dim", type: "xbmc.ui.screensaver" }
​21: Object { addonid: "script.module.pil", type: "xbmc.python.module" }
​22: Object { addonid: "script.module.pycryptodome", type: "xbmc.python.module" }
​23: Object { addonid: "service.xbmc.versioncheck", type: "xbmc.service" }
​24: Object { addonid: "skin.estouchy", type: "xbmc.gui.skin" }
​25: Object { addonid: "skin.estuary", type: "xbmc.gui.skin" }
​26: Object { addonid: "webinterface.default", type: "xbmc.webinterface" }
​27: Object { addonid: "script.module.urllib3", type: "xbmc.python.module" }
​28: Object { addonid: "script.module.chardet", type: "xbmc.python.module" }
​29: Object { addonid: "script.module.idna", type: "xbmc.python.module" }
​30: Object { addonid: "script.module.certifi", type: "xbmc.python.module" }
​31: Object { addonid: "script.module.requests", type: "xbmc.python.module" }
​32: Object { addonid: "script.module.beautifulsoup4", type: "xbmc.python.module" }
​33: Object { addonid: "weather.ozweather", type: "xbmc.python.weather" }
​34: Object { addonid: "script.favourites", type: "xbmc.python.library" }
​35: Object { addonid: "script.module.simplejson", type: "xbmc.python.module" }
​36: Object { addonid: "script.module.simplecache", type: "xbmc.python.module" }
​37: Object { addonid: "script.module.beautifulsoup", type: "xbmc.python.module" }
​38: Object { addonid: "script.module.six", type: "xbmc.python.module" }
​39: Object { addonid: "script.module.dateutil", type: "xbmc.python.module" }
​40: Object { addonid: "script.module.arrow", type: "xbmc.python.module" }
​41: Object { addonid: "script.module.thetvdb", type: "xbmc.python.module" }
​42: Object { addonid: "script.module.musicbrainz", type: "xbmc.python.module" }
​43: Object { addonid: "script.module.metadatautils", type: "xbmc.python.module" }
​44: Object { addonid: "script.skin.helper.service", type: "kodi.context.item" }
​45: Object { addonid: "resource.uisounds.amber", type: "kodi.resource.uisounds" }
​46: Object { addonid: "script.skin.helper.widgets", type: "xbmc.python.pluginsource" }
​47: Object { addonid: "script.grab.fanart", type: "xbmc.python.library" }
​48: Object { addonid: "script.module.unidecode", type: "xbmc.python.module" }
​49: Object { addonid: "script.skinshortcuts", type: "xbmc.python.library" }
​50: Object { addonid: "skin.amber", type: "xbmc.gui.skin" }
​51: Object { addonid: "script.module.elementtree", type: "xbmc.python.module" }
​52: Object { addonid: "script.lastfmplaylistgeneratorPM", type: "xbmc.python.script" }
​53: Object { addonid: "script.cu.lrclyrics", type: "xbmc.python.lyrics" }
​54: Object { addonid: "script.audio.musicip", type: "xbmc.python.script" }
​55: Object { addonid: "script.globalsearch", type: "xbmc.python.script" }
​56: Object { addonid: "script.keymap", type: "xbmc.python.script" }
​57: Object { addonid: "script.module.kodi-six", type: "xbmc.python.module" }
​58: Object { addonid: "script.module.future", type: "xbmc.python.module" }
​59: Object { addonid: "script.module.autocompletion", type: "xbmc.python.module" }
​60: Object { addonid: "plugin.program.autocompletion", type: "xbmc.python.pluginsource" }
​61: Object { addonid: "plugin.program.super.favourites", type: "xbmc.python.pluginsource" }
​62: Object { addonid: "script.commands", type: "xbmc.python.pluginsource" }
​63: Object { addonid: "plugin.library.node.editor", type: "xbmc.python.pluginsource" }
​64: Object { addonid: "script.user.rating", type: "xbmc.python.script" }
​65: Object { addonid: "script.module.backports.functools_lru_cache", type: "xbmc.python.module" }
​66: Object { addonid: "script.cdartmanager", type: "xbmc.python.script" }
​length: 67
​<prototype>: Array []
```
Of deep important note is that it is the lack of an `extrainfo` attribute on the `audioencoder.kodi.builtin.aac` addon that causes this entire loop to break. Inference: it is nothing to do with any of the other addons, just this first one, as the whole loop over addons breaks on the first pass in Chorus.

It's a bultin addon at that!

### Your Environment
Used Operating system:
 - Android: for Kore
 - Linux: Mint 19.3 for Kodi
 - Operating system version/name: Mint 19.3 For Kodi and for Chorus clients (both Firefox and Chrome tried)
 - Kodi version: 18.7 (albeit newly installed (form May 22) so possibly caused this?

**Comment by DaVukovic** [comment]
Well, I can't confirm your problem with Kodi 19 and the webinterface: 

![image](https://user-images.githubusercontent.com/7235787/84488842-14638500-aca1-11ea-8666-79c8d1e01d0c.png)

That add-on is also shown in Kore. So I can't confirm that either. 

Are you able to confirm your bug is resolved while using Kodi 19?

Please make a backup of your existing `~/.kodi`-folder by copying it to somewhere else with a different foldername: `cp -r ~/.kodi ~/kodi.backup` before upgrading to Kodi 19

**Comment by bernd-wechner** [comment]
@DaVukovic thanks kindly. Just a quick not to assure you I will try that and report back soon!

**Comment by DaVukovic** [comment]
To use Kodi 19, you simply have to switch/add the PPAs in use

https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux#Installing_Kodi_on_Ubuntu-based_distributions

If things go wrong during updating Kodi, then you might have to deinstall kodi 18 first via `sudo apt purge kodi\*`, then switch/add the ppa: `xbmc-nightly`, update your repos: `sudo apt update` and then install kodi. that should give you Kodi 19 in the end. 

But I would first try to test with Kodi 18 as I don't know which addons are important for you which probably might not work after the switch to Kodi 19

**Comment by bernd-wechner** [comment]
OK, finally made time to progressing this. Apologies for the delay. Followed the Kodi18 tips you provided. Cost me a lot of hassles and time because of endless crashes, and refusals to run properly but, I think I nailed all that down to one simple issue which is completely unrelated. I will share it though to aid in understanding later.

First though short version is, it works. I can see add-ons in Chrorus2 and Kore again that way. I have an empty library and pristine Kodi but hey at least we have proof that Kodi core is fine in that space.

On to the crash hassles. They all got nailed to this:
![image](https://user-images.githubusercontent.com/7296506/84980745-34e68000-b176-11ea-8212-2fc8e51d7ff4.png)

If I enable the bottom option, then a "Failed to start" message pops up, Kodi locks up and eventually crashes.  Oh well. Side issue. Besides which I am happy to move to 19! I want to do that for other reasons, namely python3 development of an addon I work with.

So I'll give that a shot next.

**Comment by bernd-wechner** [comment]
So started with 19, installed fine. Loading media now (will take a long time, I have a large NAS). I could migrate the old library if I could be bothered researching which bits of ~/.kodi-backup to copy over.

Alas I tried to install the Amber skin (as it's my favourite and what I'm used to) and:

![image](https://user-images.githubusercontent.com/7296506/84981847-ca830f00-b178-11ea-90cc-66a44caf9b93.png)

Thus begins the the Kodi 19 journey. I shall delve ...

**Comment by bernd-wechner** [comment]
Ah, found the cause of crashes (not that it justifies crashes). When you enable the bottom option "Allow remote control from other systems". Then it tries to open port 9090 for listening. If that's taken, freeze and crash. Which it is on my system. So moved it in advancedsettings to 9091 with:

```
  <jsonrpc>
    <compactoutput>false</compactoutput>
    <tcpport>9091</tcpport>
  </jsonrpc>
```

and now Chorus 2 works again as is Kore etc. Library loading. Amber skin seems to use an addon that still has Python 2 hence not supported. C'est la vie. If 19 works well still worth sticking to it, as I want to push forward with python 3 addons anyhow. If I find time or interest I'll try and port Amber to Python 3 but it's low on my list.

**Comment by bernd-wechner** [comment]
I guess, while we don't know what caused this, a clean v18 or v19 doesn't show the problem, so this can close. Not worth my time or anyone else's trying to find the exact cause at this stage alas.
