### ISSUE TITLE
Not Able to Access ListItem Properties from a Plugin

### ISSUE THREAD

**Issue by finkleandeinhorn** [xbmc/xbmc#18048]
### Describe the bug
Here is a clear and concise description of what the problem is:
Properties set on `ListItem`s are not able to be retrieved in any way via another plugin, after creation time. The only way that they are accessible is by parsing them as an InfoLabel in a skin window, and are not returned via any existing JSON-RPC call.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
My desired behavior would be that available properties from a `ListItem` would be retrievable via JSON-RPC, similar to how their existing InfoLabels are accessible now.

## Actual Behavior
After the `ListItem` has been added to the directory, and `endOfDirectory(...)` has been called, there is not any method that allows for a Python script to retrieve properties from it.

## Possible Fix
The most logical change, in my opinion, would be for these properties to be returned as an extra object in the JSON response from [List.Item.File](https://kodi.wiki/view/JSON-RPC_API/v10#List.Item.File).

### To Reproduce
There is a small example add-on at https://www.github.com/drinfernoo/plugin.program.example/, which demonstrates the difficulty with retrieving these properties "after the fact".

### Debuglog
This issue isn't for a particular issue that requires a debug log, as far as I'm aware. If it becomes apparent that I've missed some relevant logging, I'll gladly provide any this is required.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
There is also a thread on the forum at https://forum.kodi.tv/showthread.php?tid=354817, highlighting the issue (also where the previously mentioned example add-on came from), but nobody seems to have engaged the poster.

### Your Environment
Used Operating system:
 - [x] Android
 - [x] iOS
 - [x] Linux
 - [x] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name: Any
 - Kodi version: All

**Comment by DaVukovic** [comment]
I talked to the team and they said this is more a feature request rather than a bug report.

As this section is for bug-reports only, I would like you to ask to open a feature request at the Kodi forums at this section: https://forum.kodi.tv/forumdisplay.php?fid=9

Thanks
