### ISSUE TITLE
“Modify the video cache” can not work

### ISSUE THREAD

**Issue by qwerttvv** [xbmc/xbmc#18066]
## Expected Behavior
Modify the video cache via https://kodi.wiki/view/HOW-TO:Modify_the_video_cache

## Actual Behavior
set A：
```json
<buffermode>1</buffermode>
<memorysize>209715200</memorysize>
```
set B：
```json
<buffermode>1</buffermode>
<memorysize>1048576</memorysize>
```
The results of setting A and B are the same

### To Reproduce
1-set A
2-watch video with 30000 kb/s from internet(http) and local(usb3.0)
3-set B
4-reload
5-watch the same video
A and B video playback screen has not changed

### Your Environment
Android kodi-18.7.2-Leia-armeabi-v7a
sony x900f

## Additional context or screenshots (if appropriate)
http with IPTV Simple PVR 3.9.8-Leia
full advancedsettings.xml file in Android/data/org.xbmc.kodi/files/.kodi/userdata/
```json
    <advancedsettings>
      <cache>
        <buffermode>1</buffermode>
        <memorysize>209715200</memorysize>
        <readfactor>20</readfactor>
      </cache>
    </advancedsettings>
```

**Comment by DaVukovic** [comment]
Could you please tell me what we should do with this report? Are you facing problems and if so, which problems?

You are just saying: 
> A and B video playback screen has not changed

"Hast not changed" means to me, that with both setups, your video playback is still fine and you simply don't notice any difference.
In case you have problems, you should stop ignoring our template and provide the debuglog we are asking for and also explain a bit more what kind of issue you have.

Cheers

**Comment by DaVukovic** [comment]
This issue will be closed now. Feel free to post any comments if you have the time and if further information have been given, I will happily re-open it.
