### ISSUE TITLE
Kodi crashed on start (Android on ChromeOS)

### ISSUE THREAD

**Issue by rupaschomaker** [xbmc/xbmc#18085]
### Describe the bug

Kodi doesn't get to the point where it displays it's startup screen.  Just the initial black and then crashes out. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should flash it's startup screen and then continue to the home screen.

## Actual Behavior

It crashes.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/4809605/kodi.log)

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
ChromeOS Version 83.0.4103.77
Running on a i5 Pixel Slate 
- Kodi version: Kodi (18.7 (18.7.200) Git:20200609-dbf8e077ea)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by rupaschomaker** [comment]
I renamed the .kodi directory out the way to do a "from scratch" install.  Crashes on start, but slightly different error:

2020-06-21 09:26:55.875 T:4187  NOTICE: -----------------------------------------------------------------------
2020-06-21 09:26:55.876 T:4187    INFO: loading settings
2020-06-21 09:26:55.889 T:4187  NOTICE: special://profile/ is mapped to: special://masterprofile/
2020-06-21 09:26:55.898 T:4187   ERROR: CSettings: unable to load settings from special://masterprofile/guisettings.xml, creating new default settings
2020-06-21 09:26:55.901 T:4187 WARNING: Failed to save the default settings to special://masterprofile/guisettings.xml
2020-06-21 09:26:55.901 T:4187   FATAL: unable to load settings

**Comment by I-Cat** [comment]
Looks like u installed the wrong Kodi apk

**Comment by CastagnaIT** [comment]
hi @rupaschomaker Sorry about the OT but i see that you have a Pixel Slate perhaps you can help me

from Chrome can you give me the User Agent of your browser?
https://www.whatismybrowser.com/detect/what-is-my-user-agent
thanks a lot

**Comment by rupaschomaker** [comment]
> Looks like u installed the wrong Kodi apk

it is what was delivered through the app store.

**Comment by rupaschomaker** [comment]
> hi @rupaschomaker Sorry about the OT but i see that you have a Pixel Slate perhaps you can help me
> 
> from Chrome can you give me the User Agent of your browser?
> https://www.whatismybrowser.com/detect/what-is-my-user-agent
> thanks a lot

Mozilla/5.0 (X11; CrOS x86_64 13020.55.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.77 Safari/537.36

**Comment by I-Cat** [comment]
[ ok so it is kinda android. Guessing dir ]
a, uninstall apk
b, reboot 
find
[ If ] org.xbmc.kodi exists Delete it

Looks like you need 64 version

Test Dis one

https://drive.google.com/file/d/1-UHKFwT-9xEPbw1ZSOBo-qAR84PPQ6_F/view?usp=sharing

**Comment by rupaschomaker** [comment]
So, I can't run random build links anyway under chromeos (only play store allowed).  However, I realized that I hadn't tried uninstalling the kodi that was installed prior.  So, I did a full kodi uninstall and then redownloaded the current kodi (beta) and it is starting ok.  

Reviewing the log files, the build # is the exact same, so... Dunno.
