### ISSUE TITLE
If screenshot location is SMB then kodi will die

### ISSUE THREAD

**Issue by gridl0k** [xbmc/xbmc#18080]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Entering a screenshot location in Settings > System that is browsed from the list and is an SMB share, kodi should save a screenshot to that location.

## Actual Behavior

When you screenshot, it dies

## Possible Fix

Mount share using systemd and enter location as /mnt/SHARE and it will work

### To Reproduce

1. Add smb://server/ to sources list
2. Set screenshot location to a folder on this share eg smb://server/screenshots/
3. Play a video
4. Take a screenshot

### Debuglog

The debuglog can be found here:

"The debuglog can be found here:"

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
thanx for the report, could you please add a debuglog?

fwiw, i cannot reproduce it.

**Comment by gridl0k** [comment]
will do

**Comment by KarellenX** [comment]
Could not reproduce either Win10 SMB shares, v18.7

**Comment by DaVukovic** [comment]
>Kodi version: 18.2

If that's correct (the log wil tell), then I would highly recommend to update first to the currenct stable version (which is 18.7 and see if that fixes something.

**Comment by gridl0k** [comment]
Sorry for not attaching originally;

https://pastebin.com/G5vArmFQ

**Comment by fuzzard** [comment]
Just adding, cant replicate on osx v19 alpha 1
