### ISSUE TITLE
DRM bug on Android by Kodi Ver 18.7.200 and Kodi 18.8

### ISSUE THREAD

**Issue by Testato** [xbmc/xbmc#18086]
On Android (ver 10 on Samsung S9+) the DRM Widevine Live Stream is broken.

You can simply test it by install the LA7 addon by official kodi repo and play the first two Live Channel 

On kodi 18.6 and also on the very first 18.7 version all work regularly. The bug is present only on kodi 18.7.200

**Comment by matthuisman** [comment]
also seeing reports of this. 18.6 working ok, 18.7.200 - not working.
I'll try get logs etc

**Comment by I-Cat** [comment]
can confirm 18.7.200 is broken

**Comment by Testato** [comment]
Bug also present on Kodi 18.8

**Comment by DaVukovic** [comment]
No log, no issue. It's simple as that and our bot already mentioned that moons ago. 

Please open a new ticket tested with Kodi 19 as Kodi 18 won't receive any bugfixes anymore. And don't forget to attach a debuglog.

**Comment by Testato** [comment]
I writed exactly how reproduce the error.
I'm a developer, replicate the error on my side is always better than a third person Logfile.

Kodi 18.x is the last official version and it will stay in the Android store for a long time to come
