### ISSUE TITLE
Raspberry PI 4B - Problems with buffering over wifi

### ISSUE THREAD

**Issue by Harvie** [xbmc/xbmc#18089]
Hello,
i have relatively solid internet connection, but i get "stream stalled" and similar messages in log when watching PVR streams or Video Addons (usualy few times each hour). I have 5GHz wifi connection to raspberry 4B (4G RAM) and the speedtest on raspberry usualy shows something like 60-80 Mbps download speed (tested both speedtest-clip and kodi speedtest addon), but latency might vary. I don't have these problems when connected using ethernet (says 300-400Mbps download speed). But i am pretty sure this is way too fast to be required for FullHD streams. There is no error in dmesg and according to htop there is a lot of RAM and computing power left. Using kodi leia 18.7 on raspbian, but happend even on 18.6. Also this only seems to affect HTTP live streams, SFTP mountpoints are OK.

U put `gpu_mem=512` into `/boot/config.txt`, which helped with some decoder related problems, but the buffering still sucks.

i tried following in `~/.kodi/userdata/advancedsettings.xml`, but i don't feel like it helped at all.
```XML
<advancedsettings>
  <cache>
    <buffermode>1</buffermode>
    <memorysize>524288000</memorysize>
    <readfactor>10</readfactor>
  </cache>
  <network>
    <curlclienttimeout>10</curlclienttimeout> <!-- Timeout in seconds for libcurl (http/ftp) connections -->
    <curllowspeedtime>20</curllowspeedtime> <!-- Time in seconds for libcurl to consider a connection lowspeed -->
    <curlretries>4</curlretries> <!-- Amount of retries for certain failed libcurl operations (e.g. timeout) -->
  </network>
</advancedsettings>
```

I also put `iw wlan0 set power_save off` to `/etc/rc.local`, which improved wifi latency a bit. When i run `ping -f 8.8.8.8` over the wifi, the latency is improved much more, but the streaming problems still happen. I use the same 5GHz wifi to watch FullHD videos on my laptop (which is located much further away from AP than raspi) and there is no problem. Also sometimes the stream connection drops and does not reconnect without user interaction, which is annoying. (maybe some URL token validity timed out).

I think there is some problem with kodi's buffering strategy. 5GHz wifi in raspberry 4B is more than capable of playing FullHD videos when buffering and reconnecting is correctly handled... Can you please make this work? I believe lot of people will be using similar setup, so i think it would make sense to tune the kodi a bit, so it would work better on fast wifi with sloppy latency.

I've googled the problem and there are lots of people struggling with the same. Usualy they fiddle with advancedsettings.xml and then give up, but no really usable workaround is available.

**Comment by KarellenX** [comment]
@Harvie 

You have ignored the required template to submit a bug report.

At this stage, your post sounds like a support request. We do not provide support on Github.

Please post your question on the Kodi forums for assistance.
