### ISSUE TITLE
Kodi will not show local subtitles if ISO has no subtitles

### ISSUE THREAD

**Issue by Grunthos** [xbmc/xbmc#18107]
### Describe the bug

When playing a DVD ISO that has no 'native' subtitles, selecting a local subtitle file does not show any subtitles on screen.

## Expected Behavior

Should display subtitles from the SRT contents in sync with the playing video.

## Actual Behavior

No subtitles, or -- very rarely -- a rapid flicker of a subtitle, then noting.

## Possible Fix

None. 

### To Reproduce

1. Find a DVD ISO that has no subtitles.
2. Get any SRT file (or create a dummy one), and place in a folder accessible to Kodi.
3. Start playing one of the titles in the DVD ISO
4. Pause, and select the SRT file as the subtitle file for the current video.
5. Resume video

-> No subtitles

A simple dummy SRT file follows:
```
1
00:00:05,500 --> 00:10:53,260
Let me start at the beginning.
```

### Debuglog
The debuglog can be found here:

https://paste.kodi.tv/vasicasozu.kodi

### Screenshots 

NA

## Additional context or screenshots (if appropriate)

NA

### Your Environment
Used Operating system:

NVidia Shield (Android) + NAS running SMB

(See log for Android version info)
 - Kodi version: 18.7.200

**Comment by Grunthos** [comment]
FWIW, this remains an issue in 18.9.0.

**Comment by CastagnaIT** [comment]
have the opportunity to test on Kodi 20 nightly?
