### ISSUE TITLE
File manager failure when the folder is deleted

### ISSUE THREAD

**Issue by marcuszani** [xbmc/xbmc#18119]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello there is a problem that occurs in the kodi file manager, when you open a folder and then it is deleted the kodi gets lost and cannot identify it.
Let's say that I enter the kodi file manager in a folder, press esc to exit the screen, if otherwise that folder is deleted it is lost needing to close the application and open it again.

## Expected Behavior
In this case, the solution would be that if he tries to open a folder and it does not exist, he returns to the main folder.

## Actual Behavior

File manager interruption.

## Possible Fix

In this case, the solution would be that if he tries to open a folder and it does not exist, he returns to the main folder.

### To Reproduce

1.  Open a folder with the file manager;
2. Exit the file manager screen but without going back to the main folder;
3. Delete this same folder using samba, ssh, winscp and others.
4. Open the file manager again.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
thanx for the report!

fix pending: https://github.com/xbmc/xbmc/pull/18121
