### ISSUE TITLE
Kodi crashes when trying to add SFTP media source

### ISSUE THREAD

**Issue by sylr** [xbmc/xbmc#18115]
### Describe the bug

I've installed a fresh OSMC 2020-06-07 on a raspberry pi 3.

I've activated the SSH/SFTP addon.

As soon as I hit enter after adding the source details in the GUI kodi crashes.

No iseful logs found is ~/.kodi/temp/kodi.log.

### Debuglog

The debuglog can be found here:

```
Jun 29 14:17:06 smj-cbc-osmc1 mediacenter[336]: /usr/bin/mediacenter: line 142:   398 Segmentation fault      sudo -u osmc LIRC_SOCKET_PATH=/var/run/lirc/lircd $KODI --standalone -fs
Jun 29 14:17:06 smj-cbc-osmc1 mediacenter[336]: Kodi exited with return code 139 after 0 hours, 9 minutes and 31 seconds
Jun 29 14:17:17 smj-cbc-osmc1 mediacenter[336]: Starting Kodi...
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: osmc
 - Kodi version: 18.7

```
2020-06-29 14:17:18.394 T:1915713072  NOTICE: Starting Kodi (18.7). Platform: Linux ARM (Thumb) 32-bit
2020-06-29 14:17:18.394 T:1915713072  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
2020-06-29 14:17:18.394 T:1915713072  NOTICE: Kodi compiled 2020-06-03 by GCC 6.3.0 for Linux ARM (Thumb) 32-bit version 4.9.110 (264558)
```

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
>No iseful logs found is ~/.kodi/temp/kodi.log.

Maybe you think they are useless, but I guess they aren't . So please enable debugging in system settings and reproduce your issue.

If Kodi crashes there should be a crashlog at your home-directory and there should also be a `kodi.log` and a `kodi.old.log`at the `~/.kodi/temp`-folder. Provide them both, please

**Comment by sylr** [comment]
Here you are. I've redacted the keystrokes with:

```
sed -i -E -e 's/scancode: 0x[0-9a-f]+, sym: 0x[0-9a-f]+, unicode: 0x[0-9a-f]+/scancode: ..., sym: ..., unicode: .../' file
```

[kodi.log](https://github.com/xbmc/xbmc/files/4863649/kodi.log)
[kodi.old.log](https://github.com/xbmc/xbmc/files/4863650/kodi.old.log)

**Comment by AlwinEsch** [comment]
There seems a bug inside vfs.sftp addon. Hopefully I find the time soon to look more about.
Without a backtrace hard to say which place exact produce it.

Have you the possibility to Test Kodi on e.g. normal Ubuntu (Linux) by your Computer (also by Windows possible to test, but not so fast todo)?

If yes I can give you instructions how todo a backtrace.

**Comment by sylr** [comment]
I only have raspberries OSMC available.

**Comment by AlwinEsch** [comment]
NP, then I try by my one at home. Hopefully I can reproduce something, cross then the fingers that crashes come :stuck_out_tongue_winking_eye:

**Comment by malard** [comment]
this is a bug with an addon and needs to be resolved there. Or the addon developer needs to raise a ticket explaining what they are trying to do that is expected that kodi is failing to do and crashing
