### ISSUE TITLE
Need suggestion with a function implemented on kodi under RPI OS

### ISSUE THREAD

**Issue by Askmewho** [xbmc/xbmc#18118]
HI!! I saw than KODI on raspberry pi RPI OS does shutdown X11 and start a gbm environment for kodi to avoid
tearing. I need to know the execution line than you use to do that!! hope you wanna help. I need to launch an app
on gbm the same way.

**Comment by lrusak** [comment]
The app requires architecture to run directly on the frame buffer. You can’t just run any application like that. You are better off asking for help in the forums.

**Comment by Askmewho** [comment]
@lrusak  but my app can run on gbm!! I just need the line you use to shutdown x11 and run it. please
