### ISSUE TITLE
Subtitle background color opactity always at 100%

### ISSUE THREAD

**Issue by XGamerYU** [xbmc/xbmc#18117]
### Describe the bug
The subtitle color opacity is always at 100% when it's not 0%. Anything above 0% means that the background is constantly 100%. I tested on multiple systems, on win 10 and win 7, both 64bit with the same issue, same Kodi version. 

## Expected Behavior
To be able to set the the color opacity not too much, not too little. But it's 100% if it's turned on.

## Actual Behavior
The opacity stays 100% whenever you turn it on, wherever the slider may be.

### Debuglog
https://paste.ubuntu.com/p/4PhHpR9vfB/

### Screenshots 
Here are some links or screenshots to help explain the problem:
https://imgur.com/a/dMN8Qnb

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 7, 10 64bit
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@XGamerYU can you verify if the same issue happens if set the subtitle opacity (not the background opacity)?

**Comment by XGamerYU** [comment]
> @XGamerYU can you verify if the same issue happens when setting the subtitle opacity (not the background opacity)?

What do you mean with that? There's only one setting regarding the subtitle opacity, and it is setting the opacity of the background COLOR of the subtitles.

**Comment by enen92** [comment]
Ah sorry, I think the opacity for subtitles themselves was introduced in Matrix. Do you mind testing last nightly build for windows (backup your userdata folder first) and check if opacity for subtitles (not the background) works? Nightly builds can be found here: http://mirrors.kodi.tv/nightlies/windows/win64/master/

**Comment by XGamerYU** [comment]
I just tried it. Same issue. Used the latest version.
