### ISSUE TITLE
Tag not scanned for flac/ogg/mp3 from http source (but ok for mka)

### ISSUE THREAD

**Issue by NewRoberto** [xbmc/xbmc#18110]
### Describe the bug
When configuring http as source for audio library, flac, mp3, ogg (and probably others) are not added to the library.
Strangely, mka files are.
When looking at the debug, it's because kodi think that these files have not tags.

## Expected Behavior
All audio files should be added to the library even if the source is http.

## Actual Behavior
mka files are added to the library, but not flac, mp3, ogg.
Behavior should be consistent between files.

## Possible Fix
After digging in the source code it's because of this.
In music/tags/MusicInfoTagLoaderFactory.cpp tag loader is not the same between flac/ogg/mp3 and mka :

    if (strExtension == "aac" ||
    [...]
          strExtension == "flac" ||
    [...]
          strExtension == "wv")
      {
        CTagLoaderTagLib *pTagLoader = new CTagLoaderTagLib();
        return pTagLoader;
      }
    [...]
      else if (strExtension == "mka" || strExtension == "dsf" ||
               strExtension == "dff")
        return new CMusicInfoTagLoaderFFmpeg();
    [...]

CMusicInfoTagLoaderFFmpeg seems to have no issue with http source, but CTagLoaderTagLib has.

When looking at music/tags/TagLoaderTagLib.cpp this is due to this test :

    bool CTagLoaderTagLib::Load(const std::string& strFileName, CMusicInfoTag& tag, const std::string& fallbackFileExtension, EmbeddedArt *art /* = NULL */)
    {
      // Dont try to read the tags for streams & shoutcast
      if (URIUtils::IsInternetStream(strFileName))
        return false;

By removing this test, everything works fine with http source (nginx server). All flac files are now inserted correctly in the database.

As IsInternetStream is also checking other protocol than http (rtsp for example), maybe removing this line at all may break other protocols, but I didn't check.

It seems strange to me, to put local http source under "InternetStream" category.

### To Reproduce

1. Add new audio source from http server (nginx for example), and try to scan flac/ogg/mp3 files.
2.

### Debuglog
NA

### Screenshots
NA

## Additional context or screenshots (if appropriate)
NA

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Archlinux arm
 - Kodi version: 18.7

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by NewRoberto** [comment]
I have added all missing fields.
Thanks

**Comment by DaveTBlake** [comment]
An `URIUtils::IsInternetStream` check is performed by both 
`CMusicInfoTagLoaderFactory::CreateLoader` https://github.com/xbmc/xbmc/blob/7b33aec3055870a36fb93648afa3bf7175d1ea51/xbmc/music/tags/MusicInfoTagLoaderFactory.cpp#L33 (code over 11 years old) and `CTagLoaderTagLib::Load` https://github.com/xbmc/xbmc/blob/7b33aec3055870a36fb93648afa3bf7175d1ea51/xbmc/music/tags/TagLoaderTagLib.cpp#L1179 because Tablib can not cope with being passed a continuous music stream rather than a finite music file. See discussion https://github.com/xbmc/xbmc/pull/11759

This poses a problem with adding music files located on a local http source. But the solution is not simply to remove the IsInternetStream check, and any changes to that check need to be carefully considered as it is used extensively and unwanted side-effects extremely likely.

**Comment by NewRoberto** [comment]
Hi DaveTBlake

Thank you for your answer, and thank you for the link on the discussion. Yes I wouldn't expect this easy to fix...
What is strange is that by removing the check in TagLoaderTagLib.cpp made the scan of my library work even if I didn't change anything on the factory (I didn't see this check).

So I don't know what to do with this bug, maybe you can close it as it seems not so easy to fix, and just put a warning in the kodi wiki.
I raised this bug, because I was very surprised to see my mka file imported while flac/ogg/mp3 where rejected.

Thank you for your time !

Regards
