### ISSUE TITLE
Kodi built-in RSS feed support under Videos

### ISSUE THREAD

**Issue by BullShark** [xbmc/xbmc#18129]
### Describe the bug
Here is a clear and concise description of what the problem is:

Only one video from a podcast rss feed gets added in Kodi using Kodi's native rss feed support under Videos.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

All of the videos from the Podcast should be added to Kodi the same as gPodder or AntennaPod (for Android).

## Actual Behavior

Only one video gets added. The video occasionally updates to a different video, but still, only one shows.

### To Reproduce

Try this in Kodi.

Kodi Main Menu -> Videos -> Files -> Add Videos... -> rss://odin.root.sx/getRSS.php and name it Latest Videos

Does it add only one video? For me it's just one video at a time that occasionally updates to a different video.

### Debuglog
The debuglog can be found here:

I turned on debug logging while creating this log.

http://odin.root.sx/files/kodi.log

### Screenshots 
Here are some links or screenshots to help explain the problem:

![kodi1](https://user-images.githubusercontent.com/1526595/86425532-0fe02a00-bcab-11ea-8182-7876625b0aa4.PNG)
![kodi2](https://user-images.githubusercontent.com/1526595/86425535-11115700-bcab-11ea-9f02-55835a910418.PNG)
![kodi3](https://user-images.githubusercontent.com/1526595/86425540-12db1a80-bcab-11ea-9b9d-a1bfd032a3c0.PNG)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

For the expected behavior, try loading the same rss podcast feed into gPodder (Linux and Windows) or AntennaPod (Android App).

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

Slackware latest and Windows 8.1

Kodi 18.7 Latest

**Comment by sarbes** [comment]
Can't confirm. I've tried two different feeds with no issue.

Without being able confirming due to a 404 of the server, I suspect a malformed xml on your part.

**Comment by BullShark** [comment]
I will reopen this when the server is back up. I went over the bandwidth for this month. It should be good in about 1 week.

**Comment by BullShark** [comment]
The server is back up. Try again.

**Comment by sarbes** [comment]
Works as intended. Your feed is violating the specs:  
`Subordinate to the <rss> element is a single <channel> element, which contains information about the channel (metadata) and its contents. `
