### ISSUE TITLE
Running JSONRPC Player.Open in quick succession crashes Kodi

### ISSUE THREAD

**Issue by dagwieers** [xbmc/xbmc#18122]
## Bug report
A user reported an add-on issue which appears to be an upstream Kodi issue. (https://github.com/add-ons/plugin.video.vrt.nu/issues/788)

When running JSON-RPC `Player.Open` in quick succession using a `plugin://`-type URL crashes Kodi.

This is easily reproduced using e.g.
```bash
$ curl -n -X POST -H "content-type:application/json" http://kodi01/jsonrpc -d '{"jsonrpc": "2.0", "method": "Player.Open", "params": {"item": {"file": "plugin://plugin.video.netflix/foo/bar" }}, "id": 1}'
```
or using **kodi-send**:
```bash
$ kodi-send -a 'PlayMedia(plugin://weather.yahoo)'
```
in quick succession.

> **NOTICE**: The URL does not even have to be real, but the add-on does need to exist on the system.

Instead of crashing Kodi in some cases it rebooted the system into LibreELEC SAFE MODE...

## Expected Behavior
No crash or reboot.

## Actual Behavior
Crash and restart.
Or alternatively a LibreELEC reboot into SAFE MODE.

### To Reproduce
1. Perform a JSON-RPC call using `Player.Open` on a `plugin://`type URL in quick succession
2. Kodi will crash, dump core and eventually restart

### Debuglog
TBD

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC v9.2.3 (also reported on OSMC)
 - Kodi version: v18.7

**Comment by ccope** [comment]
Might be related to #17776

**Comment by mediaminister** [comment]
I could reproduce this running Kodi 19 master branch and Kodi crashes with:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  busy dialog already running
```

**Comment by malard** [comment]
While I don't object to the bug report, the issue is that there is excessive calls to the JSONRPC for this url. Given this is a resource intensive operation, the plugin developer should be minded to manage their resource usage.
