### ISSUE TITLE
Issues with switch to visualisation on playback option when in video section

### ISSUE THREAD

**Issue by manfeed** [xbmc/xbmc#18135]
### Describe the bug
Here is a clear and concise description of what the problem is:

When the new Matrix setting to switch to visualisation on playback (add setting to switch to visualisation on playback #17225) is turned on, the option to play a theme.mp3 when browsing movies becomes impossible. One second after the theme.mp3 starts to play, the fullscreen music window tries to open, and the theme.mp3 stops. When the option is turned off there's no problem, so this is clearly the cause.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The switch to visualisation on playback option (which I really like) should only work outside of video section.

## Actual Behavior

The switch to visualisation on playback option also tries to work in video section and prevents theme.mp3 files to be played when browsing movies.

## Possible Fix

Prior to this new option, I had an invisible window dialog in my skin Aeon Tajo to launch music visualisation screen, and to prevent this behavior I had an onload condition that included !Window.IsActive(videos), but not sure if a similar approach could be used in this case.

### To Reproduce

I'm in the first stages of adapting my skin Aeon Tajo to Matrix so I can't provide a suitable way to reproduce this...

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Matrix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
@manfeed just wondering, do you have the same problem with the startup music (tajo_melodies) your skin uses?

perhaps we can look into adding a ',1' parameter to PlayMedia() for music (like we have for videos) that would prevent the fullscreen switch...

**Comment by manfeed** [comment]
@ronie 
No, that works faultlessly, it's only when browsing videos ot tvshows...

**Comment by ronie** [comment]
https://github.com/xbmc/xbmc/pull/18138

**Comment by ronie** [comment]
> No, that works faultlessly, it's only when browsing videos ot tvshows...

hmm, is there any difference in how you start the playback in those 2 cases?

**Comment by manfeed** [comment]
Themes
PlayMedia($ESCINFO[ListItem.Path,,theme.mp3])

Melodies
PlayMedia($VAR[Path_melodies],playoffset=$VAR[ThemeHome])

**Comment by manfeed** [comment]
Sorry, I just double checked and it also happens in the main menu, only difference is that after a couple hiccups the song keep playing and in videos it stops altogether... That's the reason I haven't noticed until now.

**Comment by ronie** [comment]
yup, was just testing myself.
it is definitely trying to switch to fullscreen (debuglog confirms).

anyway, the PR will allow you to start playback without the fullscreen switch, by adding ',1' to PlayMedia()

**Comment by manfeed** [comment]
Perfect then, thanks for the quick and smart fix!
