### ISSUE TITLE
Kodi does not startup correctly when operated headless, since recent updates

### ISSUE THREAD

**Issue by jejo86** [xbmc/xbmc#18136]
### Describe the bug
Here is a clear and concise description of what the problem is:

Until around two weeks ago, I could plug in the power of my RaspberryPi 1 Model B. I could start playing music without problems via a remote control application on my phone. When connecting the cable to my TV, the Kodi GUI would be displayed and I could e.g. play a video.

Since the latest updates, this is not possible anymore. OSMC does boot and I can start the music with my phone, but the music is stuttering. When connecting the HDMI cable to my TV, I see a black screen.

Excerpt of errors in log (see full logs below):
```
2020-07-04 16:59:00.110 T:2510234336   ERROR: OpenConnection - could not opening a connection to the CEC adapter
2020-07-04 16:59:25.920 T:2979394768   ERROR: Previous line repeats 1 times.
...
2020-07-04 16:59:33.666 T:2942296800  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
2020-07-04 16:59:40.463 T:2510234336   ERROR: OpenConnection - could not opening a connection to the CEC adapter
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

OSMC should start normally, even without the HDMI cable connected to any display.

## Actual Behavior

OSMC does not start correctly when operating in headless mode.

## Possible Fix

When booting, the HDMI cable needs to be connected to a monitor. Already when the first boot logs/OSMC boot screen appears the cable can be plugged out and in as many times as wanted without issues.

### To Reproduce

1. Pull the HDMI cable of the Raspberry Pi
2. Turn on the power so that OSMC boots
3. Try to play music or connect the HDMI cable to a monitor to see the Kodi GUI.

### Debuglog

The debuglog can be found here:

Headless startup, started playing music, stuttering: [kodi.notworking..log](https://github.com/xbmc/xbmc/files/4873066/kodi.notworking.log)

TV connected while booting, started playing music, everything works fine: [kodi.working.log](https://github.com/xbmc/xbmc/files/4873067/kodi.working.log)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

OSMC is installed via [NOOBS](https://www.raspberrypi.org/downloads/noobs/).

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Raspberry-Pi 1 Model B

NOOBS v3.3

Kodi (18.7). Platform: Linux ARM 32-bit
Release Kodi x32 build (version for Raspberry Pi)
Kodi compiled 2020-06-03 by GCC 6.3.0 for Linux ARM 32-bit version 4.9.82

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
No debug log attached.

Enable debug logging in the settings, restart and reproduce.

**Comment by jejo86** [comment]
Here it is: [kodi.log](https://github.com/xbmc/xbmc/files/5003106/kodi.log)
