### ISSUE TITLE
Linux git build File "FindLibDRM.cmake" missing ")" Line 36,  under cmake/modules

### ISSUE THREAD

**Issue by DAVITALI** [xbmc/xbmc#18148]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
I'm not sure if this is due to the cmake version you are using but the block is valid

```
check_c_source_compiles("#include <drm_mode.h>
                         int main()
                         {
                           struct hdr_output_metadata test;
                           return test.metadata_type;
                         }
                         " LIBDRM_HAS_HDR_OUTPUT_METADATA)
```

https://github.com/xbmc/xbmc/blob/master/cmake/modules/FindLibDRM.cmake#L36-L43

**Comment by DAVITALI** [comment]
Prob cmake from debian then, sorry for thatDennis
    On Tuesday, July 7, 2020, 01:23:31 PM EDT, Lukas Rusak <notifications@github.com> wrote:  
 
 


I'm not sure if this is due to the cmake version you are using but the block is valid
check_c_source_compiles("#include <drm_mode.h>
                         int main()
                         {
                           struct hdr_output_metadata test;
                           return test.metadata_type;
                         }
                         " LIBDRM_HAS_HDR_OUTPUT_METADATA)

https://github.com/xbmc/xbmc/blob/master/cmake/modules/FindLibDRM.cmake#L36-L43

**Comment by DaVukovic** [comment]
I guess we can close this one then
