### ISSUE TITLE
Sony XG85 android 9 HDMI ARC DTS passthrough problem

### ISSUE THREAD

**Issue by Mutronics** [xbmc/xbmc#18146]
TV: Sony XG85 with android 9
Connected: HDMI ARC
Receiver: Pioneer VSX-830
Kodi 18,7.2 settings all defaults, only enabled DTS and AC3 passthrough.
All moves with DTS sound broken bitstream every second.
This problem in all Kodi version 17-19, only SPMC 16.7 working fine.

**Comment by fritsch** [comment]
Nothing to fix here. Sony Firmware flaw. SPMC works, cause it tunnels DTS via PCM-Stream. Will kill your ears is unsupported. In the forum a build called "shitty" is provided, which you can use on your own risk, this uses SPMC PT behaviour. We don't support this build, it was just done  to show people the firmware flaw.

**Comment by Mutronics** [comment]
Resign yourself and watch in stereo.
You do not care about the quality of your software

**Comment by fritsch** [comment]
Infact I will do that. Thinking about it since longer time. Thanks for helping to make the final decision.

**Comment by Mutronics** [comment]
New information!
DTS sound is interrupted only if the movie contains a VC-1 codec.
