### ISSUE TITLE
Some .jpg images don't render in current master

### ISSUE THREAD

**Issue by ronie** [xbmc/xbmc#18153]
### Describe the bug

A small portion of of my .jpg images don't render anymore inside Kodi.
I suspect it's due to the update of ffmpeg to 4.3 (https://github.com/xbmc/xbmc/pull/18071)

## Expected Behavior

When i'm browsing my images inside the Pictures section of Kodi, i expect to see the thumbnails of those images.

## Actual Behavior

No thumbnails are shown. These images also don't render when starting a slideshow.

log extract:
```
2020-07-09 03:45:22.140 T:156327   ERROR <general>: ffmpeg[0x555afd294380X]: [mjpeg] unable to decode APP fields: Invalid data found when processing input
2020-07-09 03:45:22.140 T:156327   DEBUG <general>: ffmpeg[0x555afd294380X]: [mjpeg] No JPEG data found in image
2020-07-09 03:45:22.140 T:156327   DEBUG <general>: Error [-1094995529] while decoding frame: Unknown error 1094995529
2020-07-09 03:45:22.140 T:156327   DEBUG <general>: LoadFromFileInternal - Load of /home/ronie/pictures/2011 - Frankrijk/februari maart 2011 043.JPG failed.
```

### To Reproduce

download this  sample image and test if it renders in kodi. it doesn't on my end.

![test](https://user-images.githubusercontent.com/687265/86987846-429c8d80-c197-11ea-916b-bb4738e09687.jpg)

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ogikeseriv.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

![screenshot001](https://user-images.githubusercontent.com/687265/86987700-f3eef380-c196-11ea-9e8f-87ab25eee5d5.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Manjaro Linux
 - Kodi version: Kodi (19.0-ALPHA1 (18.9.701) Git:20200708-75d6f16f78)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Have confirmed latest nightly on OSX has the same behaviour.
Nightly from 21st June (pre 4.3 merge) image works correctly.

**Comment by ronie** [comment]
thanx for confirming!
pinging @lrusak

**Comment by lrusak** [comment]
after a bisect it looks like this is the offending commit that breaks it. https://github.com/FFmpeg/FFmpeg/commit/ec3d8a0e6945fe015d16cd98a1e7dbb4be815c15

if someone could please verify that reverting it that would be great. Next step after would be to see if ffmpeg master fixes it.

**Comment by ronie** [comment]
i can confirm reverting that commit fixes the issue.

**Comment by lrusak** [comment]
@ronie the patch author said that he posted a new patch to fix the issue. Could you please test? https://patchwork.ffmpeg.org/project/ffmpeg/patch/20200709225549.14033-1-michael@niedermayer.cc/

**Comment by ronie** [comment]
nice, tested and works ok.
