### ISSUE TITLE
Import bz2 module fails with Kodi 19

### ISSUE THREAD

**Issue by LS80** [xbmc/xbmc#18152]
### Describe the bug
Here is a clear and concise description of what the problem is:

`import bz2` fails in Kodi 19.
```
    import bz2
  File "/Applications/Kodi 19.app/Contents/Libraries/lib/python3.7/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

`import bz2` succeeds

## Actual Behavior

`import bz2` fails

## Possible Fix

Compile Python interpreter with bzip2 support

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Essentially the module isnt built on anything that uses tools/depends (Apple/android platforms).

The following patch is applied to all target platforms that essentially skips all module detection

https://github.com/xbmc/xbmc/blob/75d6f16f782da3d86a8d4ca59bea1a74f1a6b1c2/tools/depends/target/python3/crosscompile.patch#L107

The following patch adds the bz2 module and a quick build test of target python3 it succeeds. Havent runtime tested at all to see if it loads though.

```
--- a/tools/depends/target/python3/Makefile
+++ b/tools/depends/target/python3/Makefile
@@ -22,7 +22,9 @@ endif
 CONFIGURE=./configure --prefix=$(PREFIX) \
   --disable-shared \
   --without-ensurepip \
-  --disable-framework --with-system-expat --with-system-ffi --without-pymalloc --enable-ipv6
+  --disable-framework --with-system-expat --with-system-ffi --without-pymalloc --enable-ipv6 \
+  CFLAGS="$(CFLAGS) -I$(PREFIX)/include" CPPFLAGS="$(CPPFLAGS) -I$(PREFIX)/include" \
+  LDFLAGS="$(LDFLAGS) -lbz2"
 
 LIBDYLIB=$(PLATFORM)/libpython3.7.a
 
diff --git a/tools/depends/target/python3/modules.setup b/tools/depends/target/python3/modules.setup
index 37ca064e2b..c578acb47c 100644
--- a/tools/depends/target/python3/modules.setup
+++ b/tools/depends/target/python3/modules.setup
@@ -190,6 +190,7 @@ _heapq _heapqmodule.c       # Heap queue algorithm
 _asyncio _asynciomodule.c  # Fast asyncio Future
 
 unicodedata unicodedata.c    # static Unicode character database
+_bz2 _bz2module.c
 
 
 # Modules with some UNIX dependencies -- on by default:
```
