### ISSUE TITLE
Idea to deal with movie and tv in the same folder.

### ISSUE THREAD

**Issue by 1970633640** [xbmc/xbmc#18159]
### Describe the bug
Here is a clear and concise description of what the problem is:

When adding a folder as media source, either Movie or TV can be chosen. I have an idea to deal with folder containing both files.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Add one folder. Movie and TV files go to the appropriate catalog.

## Actual Behavior

User can only choose the folder containing Movie **OR** TV 

## Possible Fix

If file name contains string like ```S01E01```, it is TV, or it is Movie.

### To Reproduce

1. Add a file as media source

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi 18.7

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
That's kodi expected behaviour not a bug. We do not accept feature requests in github, only real bug reports. Please post your feature request on the forum instead: https://forum.kodi.tv/forumdisplay.php?fid=9
