### ISSUE TITLE
incorrect Mythtv disconnected / reconnected messages, can't disable

### ISSUE THREAD

**Issue by darmbrust** [xbmc/xbmc#18163]
### Describe the bug
Here is a clear and concise description of what the problem is:

Running the current version of Kodi, on Android (Sony TV), and also have it linked to my MythTV server.

Any time you push the power button for the TV, while Kodi is running - upon turning the TV back on, the screen starts flashing the MythTV Disconnected error message, followed by the MythTV Reconnected error message.

This loop repeats, for upward of 5 minutes, before it (apparently) has time to get through its entire backlog of disconnect / reconnect message, which each sit on the screen for ~ 5 seconds.  Even when you are trying to watch something else, that isn't even coming from MythTV.  There must be something on the order of 60 of these disconnect / reconnect message pairs in the queue for display.

The only way to stop this loop, is to exit Kodi, and relaunch it.  Or, always exit Kodi before you turn off the TV.

Note that MythTV functions work perfectly fine, even while these silly error messages continue to flash on screen.

Seems that there are a number of issues here:
1) its getting confused about the state of the MythTV connection upon a power down / up.
2) The logic of the error queue is silly, and should not display a "disconnect" message if there is already a reconnected message in the queue later.
3) I shouldn't be seeing MythTV connection errors when I'm not using a function that requires MythTV - especially not during playback of something else.
4) There is no GUI option to disable these pointless MythTV disconnected messages... If MythTV is disconnected, how about you just let me find out when I click on something that needs it?  This error message does nothing but aggravate a user that can't do anything about it anyway.  This one is just pointless.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Don't show wrong, pointless error messages.

## Actual Behavior

Wrong pointless error messages on every power off / on.

### To Reproduce

1. Use Kodi with MythTV on Android TV
2 .Turn off TV with Kodi open
3. Turn on TV
4. Be annoyed.

### Debuglog

The debuglog can be found here:
No debug log required... details are above.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Current in play store for Android

**Comment by darmbrust** [comment]
Not sure why the ignored rules flag is still here, I filled out the template.

**Comment by DaVukovic** [comment]
As you are refusing to provide a log which shows that problem, this label will stay as it is. But I will reply to some of your statements...

>its getting confused about the state of the MythTV connection upon a power down / up.

That's why we need a Kodi debuglog to see what happens

>The logic of the error queue is silly, and should not display a "disconnect" message if there is already a reconnected message in the queue later

That's on purpose and might help developers to debug errors. Kodi tries to connect, then disconnects and reconnects afterwards. 

>I shouldn't be seeing MythTV connection errors when I'm not using a function that requires MythTV - especially not during playback of something else.

Might depend on your usecase. Others might record something in the backgroud while watching something else from their library. If MythTV then disconnects, the user should be notified.

>There is no GUI option to disable these pointless MythTV disconnected messages... If MythTV is disconnected, how about you just let me find out when I click on something that needs it? This error message does nothing but aggravate a user that can't do anything about it anyway. This one is just pointless.

No, it's not. See my answer above. There might be services in the background

So either you provide a log, so we are able to see what happens on your side, or you don't. It's up to you. But we will close this issue in 7 days if no log was provided (beside some of our devs already know what might happen on your side).

**Comment by ksooo** [comment]
Reconnect logics is implemented in the different PVR addons. Kodi just reacts on what it receives from the addon. As other addons do not cause the problem you described, I think this is a problem with by the PVR addon used. Please open an issue for pvr.mythtv.

**Comment by darmbrust** [comment]
> > The logic of the error queue is silly, and should not display a "disconnect" message if there is already a reconnected message in the queue later
> 
> That's on purpose and might help developers to debug errors. Kodi tries to connect, then disconnects and reconnects afterwards.

You seem to be confused about what belongs in a log, and what should be shown to end users....  One log entry that says dropping X duplicate / repeated messages would suffice....

> > I shouldn't be seeing MythTV connection errors when I'm not using a function that requires MythTV - especially not during playback of something else.
> 
> Might depend on your usecase. Others might record something in the backgroud while watching something else from their library. If MythTV then disconnects, the user should be notified.

And notifying the user would do what for them, other than annoy them?  They are going to stop watching their show, to go off and quick check the status of their mythTV?  Give me a break.  9 times out of 10, the person using the Kodi frontend is a different member of the household than the one that maintains the mythtv server.

This shows why there should be an option to disable these messages - as while you, as a tech person, might want to see that error immediately, nobody else does. I believe I saw another thread somewhere stating that the option was removed, and wouldn't be returning, for reasons I can't fathom.

 
> So either you provide a log, so we are able to see what happens on your side, or you don't. It's up to you. But we will close this issue in 7 days if no log was provided (beside some of our devs already know what might happen on your side).

So, you can see that it disconnects and reconnects during power down/up?  Thats hardly the point of the bug. 
The point of the bug is the terrible handling of messages that aren't even errors.  
We don't need an error log to discuss the design behavior of errors in the UI.

**Comment by darmbrust** [comment]
> Reconnect logics is implemented in the different PVR addons. Kodi just reacts on what it receives from the addon. As other addons do not cause the problem you described, I think this is a problem with the PVR addon used. Please open an issue for pvr.mythtv.

Thank you for providing a useful reply :)
