### ISSUE TITLE
Log dosent clear after metadata added

### ISSUE THREAD

**Issue by bluboyo** [xbmc/xbmc#18177]
### Describe the bug
Here is a clear and concise description of what the problem is:

In the log were movies/tv that kodi that cant scan will appear (very nice). But when the meta data is added and I scan again it still appears. This gives loooong list and its very hard to find the ones that needs to be fixed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

That items with metadata dont appear in the error log

## Actual Behavior

All items that ever had a problem will still show up even if there are fixed. This gives long list.

## Possible Fix

Clear movies that have meta data so only the ones without show up and can be fixed. 

### To Reproduce

1. Name a movie with a bad name
2. Scan for metadata
3. Check the log and then add the movie. Scan again and it will still show up. 

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows 10 
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18,7

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Just to ensure I understand your issue, can you provide a debug log and post it to paste.kodi.tv/ then provide line numbers from the log where your movies are being scanned.

**Comment by faltaren** [comment]
https://paste.kodi.tv/lowocezobu.kodi

Check stand by me. It has metadata but shows up every time. I got 40 more.

**Comment by KarellenX** [comment]
That log does not help at all. It is a small snippet that can be interpreted many ways.

I need a full log that shows you scraping the show the first time, then immediately running an Update Library again, so I can see the second attempt at scraping. Just as you tried to describe in your first post.

Also disable item **1d** here and see if it makes a difference... 
https://forum.kodi.tv/showthread.php?tid=336969

**Comment by DaVukovic** [comment]
@faltaren 

@KarellenX is absolutely correct and I've tried the following now: 

* create a new folder with the name: `asdofihjp9q2342rt` and a mkv file in it: `asdofihjp9q2342rt.mkv` (just to have something which can't be found during a normal library scan
* after the scan, I went to the source of my video and hit `i` on that folder to perform a manual scan. Doing so, I have the option to choose a name and I took "Alien"
* the scraper found that movie and it was added to my library using the path: `/home/davu/Videos/movie-test/asdofihjp9q2342rt/asdofihjp9q2342rt.mkv`
* then I updated my library and all I could find in the log was: 

```
2020-07-18 06:20:26.738 T:3507    DEBUG <general>: VideoInfoScanner: Finished adding information from dir /home/davu/Videos/movie_test/asdofihjp9q2342rt/
2020-07-18 06:20:26.741 T:3507     INFO <general>: VideoInfoScanner: Finished scan. Scanning for video info took 00:00

```
That's the full log: https://paste.centos.org/view/63fa45aa

So I did what you explained to reproduce that but. I renamed a file having a bad title, scanned my library, added the movie manually and then trying to update my library (as you can see in the log)

Please tell us exactly (every little step, beginning from naming the file) what we need to do to reproduce your issue

**Comment by faltaren** [comment]
I couldent paste the whole log. To big. The issue isnt the scraper. It will add the meta data. The problem is that the movie/tv still shows up in the event log after its added with correct meta data. All files har in rar. Som are allso isofiles in rar.

**Comment by faltaren** [comment]
[kodi.old.log](https://github.com/xbmc/xbmc/files/4941341/kodi.old.log)
Cant paste them. Here is the log.

**Comment by KarellenX** [comment]
Which movie am I looking for?

Did you check setting **1d** as previously requested.

**Comment by faltaren** [comment]
> Which movie am I looking for?
> 
> Did you check setting **1d** as previously requested.
> 
> Event Log, which is different to Debug Log which is what is in the link you provided. I assume you mean Debug Log.

Yes my settings are good, moiviedb check, no tags etc. 

Take you pick, stand by me, alien_uhd.iso, bohemian rapsody, american assassin, dredd, forest gump, iron man 2. All the are in with the correct metadata. I can play them etc. But they still show up in the eventlog. These are bluray iso in rar. Its also good to know that some of these didnt scrape at fist, but when I do a manual scrape the scan without a problem. Non iso are ss-bd.mkv (blood diamond) mkv in rar, intothewild is another one. They still show up in the log.

**Comment by faltaren** [comment]
> Which movie am I looking for?
> 
> Did you check setting **1d** as previously requested.
> 
> Event Log, which is different to Debug Log which is what is in the link you provided. I assume you mean Debug Log.

About the log. Yes you got the debug log. But the problem I have is the eventlog in kodi. Im using it to fix media that didnt scan. But they are still there even after they are scraped. Thats the whole problem.

**Comment by KarellenX** [comment]
Ok, so all these posts are irrelevant.

The Event Log is a session log. It does not get cleared until Kodi is restarted. That is by design.

There is no bug.

**Comment by faltaren** [comment]
But why are movies that are scraped and fully working show up? They shouldent be there. I get long list of movies that are scraped and cant find the ones that i have to fix manually. Thats a bugg in i my book.

**Comment by KarellenX** [comment]
For the third and final time. What have you done about item **1d**

**Comment by DaVukovic** [comment]
>But why are movies that are scraped and fully working show up?

and

>Its also good to know that some of these didnt scrape at fist, but when I do a manual scrape the scan without a problem

As it was said already, the "Event Log" is not a "just for the moment" log. It shows things that happened for that Kodi session. So let me explain that a bit more. 

You start scraping your movies and some aren't found by the scraper for whatever reason (the reason is not important here). Then the Kodi Evenlog will mention those movies which aren't found.  It only shows, let's say, errors. Then you perform a manual scan and those movies are added. This does *not* mean, that the log entries at the Eventlog are deleted, because there have been movies in that Kodi session which haven't been found. 

The Eventlog does *not* show a "success"-message if a movie was found by the scraper nor does it remove entries which are found afterwards by a manual scan. If that confuses you, simply restart Kodi and do a library update to be sure which movies have to be added to the library.

**Comment by faltaren** [comment]
> > But why are movies that are scraped and fully working show up?
> 
> and
> 
> > Its also good to know that some of these didnt scrape at fist, but when I do a manual scrape the scan without a problem
> 
> As it was said already, the "Event Log" is not a "just for the moment" log. It shows things that happened for that Kodi session. So let me explain that a bit more.
> 
> You start scraping your movies and some aren't found by the scraper for whatever reason (the reason is not important here). Then the Kodi Evenlog will mention those movies which aren't found. It only shows, let's say, errors. Then you perform a manual scan and those movies are added. This does _not_ mean, that the log entries at the Eventlog are deleted, because there have been movies in that Kodi session which haven't been found.
> 
> The Eventlog does _not_ show a "success"-message if a movie was found by the scraper nor does it remove entries which are found afterwards by a manual scan. If that confuses you, simply restart Kodi and do a library update to be sure which movies have to be added to the library.

I understand all this, I dont know if im saying it wrong. "Then the Kodi Evenlog will mention those movies which aren't found." Exacly this, but when they are scraped and I told kodi what it was they still show up. Thats the problem. So if i then restart kodi and do a new scan they still show up.

**Comment by faltaren** [comment]
> For the third and final time. What have you done about item **1d**

Yes I did before. But here it is again. I dont have any scraping problems.  I dont use mysql database for multi installations. I use themoviedb. No videotags.  Everything is up to date. The name inside the rar is the problem in some cases but I cant change that. But when i manually tell kodi what it is and it scrapes the "error" should disappear after the next restart and scan . But even after restart and a new scan scraped movies still show up as an error.

**Comment by DaVukovic** [comment]
I cannot reprduce your problem. I did:

I'm using the same naming convention as in the posting here: https://github.com/xbmc/xbmc/issues/18177#issuecomment-660429804

* created that folder and put a file into it
* added as a source in Kodi and let it scan
* movie was not found and I got a notification at the Eventlog (that's expected)
* then I manually added the movie to my library by navigating to the source and hit "i" on my keyboard (changed the name to "Alien" and it was added to the library
* after that scan and without a Kodi restart I checked the Eventlog which still shows the notification (also expected as it's the same Kodi session and Kodi was not restartet)
* updated the library and checked the Eventlog again, the notification still exists (for the same reason as before)
* exited and started Kodi again
* checked the Eventlog (only the "Kodi successfully started" message was in)
* performed a library update
* checked the  Eventlog again and still no notification about a movie which couldn't be found

So either you are not restarting Kodi or the Eventlog is simply correct by mentioning those movie. I'm in no way able to reproduce that and I iwll flag this issue accordingly now

**Comment by faltaren** [comment]
> I cannot reprduce your problem. I did:
> 
> I'm using the same naming convention as in the posting here: [#18177 (comment)](https://github.com/xbmc/xbmc/issues/18177#issuecomment-660429804)
> 
> * created that folder and put a file into it
> * added as a source in Kodi and let it scan
> * movie was not found and I got a notification at the Eventlog (that's expected)
> * then I manually added the movie to my library by navigating to the source and hit "i" on my keyboard (changed the name to "Alien" and it was added to the library
> * after that scan and without a Kodi restart I checked the Eventlog which still shows the notification (also expected as it's the same Kodi session and Kodi was not restartet)
> * updated the library and checked the Eventlog again, the notification still exists (for the same reason as before)
> * exited and started Kodi again
> * checked the Eventlog (only the "Kodi successfully started" message was in)
> * performed a library update
> * checked the  Eventlog again and still no notification about a movie which couldn't be found
> 
> So either you are not restarting Kodi or the Eventlog is simply correct by mentioning those movie. I'm in no way able to reproduce that and I iwll flag this issue accordingly now
> 
> You could do a video and show us what you see. That would probably help to either support you or to see how to reproduce that bug.

Did you have the files in rar?

**Comment by DaVukovic** [comment]
No as I can't get rar-support to work on Kodi master branch (build today). And if that problem is related to rar-files only, then probably submit this issue to the vfs.rar binary add-on itself or simply unrar your files.

**Comment by faltaren** [comment]
> No as I can't get rar-support to work on Kodi master branch (build today). And if that problem is related to rar-files only, then probably submit this issue to the vfs.rar binary add-on itself or simply unrar your files.

I have done that. But it seems something with the log and the the vfs.rars compabilty. Dont know where the problem is. Most movies with problems are ISO in rar (reported) . Unrar is not an option... Need the rar support.
