### ISSUE TITLE
"Browse" button in "Information" window not works with the add-ons in Tv show folder case

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#18187]
### Describe the bug
Here is a clear and concise description of what the problem is:

A user report me that the "Browse" button in tv show folders
from add-on (so not kodi library) not works

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Press "Browse" button and kodi callback the addon to open the next add-on folder (seasons list)

## Actual Behavior

When press Browse button

On Kodi 18:
Kodi try to play the folder... a folder can not be played :-)

On Kodi 19:
Kodi try to open the Kodi library!? and list all the seasons contained in kodi library,
and if you press back button, the browser return to the Kodi library instead the add-on...pretty mess

## Possible Fix

Add code to manage addon callback paths?
or hidden the "browse" button in add-ons case?

### To Reproduce

1. Have a tvshow folder in an addon (like netflix)
2. Open the context menu "Information" in the tvshow folder
3. Select "Browse" button

### Debuglog

The debuglog can be found here:
Kodi 18: https://paste.kodi.tv/wofukataxo.kodi
Kodi 19: https://paste.kodi.tv/iwimamegar.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

On Kodi 19, the wrong behaviour should be here:
https://github.com/xbmc/xbmc/blob/d7836a622650b280c59d2bfcfc9eb36bc57d0aaf/xbmc/video/dialogs/GUIDialogVideoInfo.cpp#L619-L627

On Kodi 18, the method used is the same but comes to the end of the method to try to play the folder..

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 / CoreElec
 - Kodi version: 18 and 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
@CastagnaIT could you please test if this fixes the problem?
https://github.com/xbmc/xbmc/pull/18188

**Comment by CastagnaIT** [comment]
hi @ronie super speed
can you enable build artifact output? thanks

**Comment by ronie** [comment]
@CastagnaIT test builds for windows / osx / android are now available at http://mirrors.kodi.tv/test-builds/
look for the ones with PR18188 in the filename

**Comment by CastagnaIT** [comment]
i have tested and it is partially working

now when press "browse" open successfully the season folder,
but if you try to go back do not go back (not return to the previous list of titles)
and the navigation starts again from beginning (like when you open your addon for the first time)

seem that the previous navigation history is deleted

log https://paste.kodi.tv/xuguxekaba.kodi

**Comment by ronie** [comment]
ok, i gave it another shot and tried to fix it a different way...
the new test build available now the mirrors (20200720-f87bdc04-PR18188) 

please let me know if that works ok.

**Comment by CastagnaIT** [comment]
now is working good thanks!
do you think that will be backported or Kodi 18 is now closed?

**Comment by sarbes** [comment]
No backports, sorry.

**Comment by ronie** [comment]
let's keep this one open for now, the PR has not been approved/merged yet.

**Comment by CastagnaIT** [comment]
> No backports, sorry.

thanks for the info, now i have an answer for the users
