### ISSUE TITLE
Monitor().waitForAbort partially works on add-on/script instances

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#18191]
### Describe the bug
Here is a clear and concise description of what the problem is:

Use Monitor().waitForAbort to exit from a loop in particular cases not always work on add-on or script instance,
and cause Kodi to freeze in memory

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Make Kodi send abort event correctly

## Actual Behavior

If you try to use:
<pre>
    monitor = xbmc.Monitor()
    while not monitor.abortRequested():
        if monitor.waitForAbort(1):
            print('ADDON TEST - BREAK FOR ABORT')
            break
    print('ADDON TEST - EXIT')
</pre>

and you try to exit from kodi with:
- Key S (shutdown menu)
- "X" button on windows title
- Send Exit json RPC:
`curl -s --data-binary '{"jsonrpc": "2.0", "method": "Application.Quit", "id":1}' -H 'content-type: application/json;' http://192.168.2.2:8080/jsonrpc --user kodi:kodi`

on an add-on or script instance, the code will not exit, and Kodi will not be terminated
will remains freezed on window or in memory (see task manger)

### To Reproduce

1. Install the test add-on https://www.dropbox.com/s/q56t9hadghuewz2/test.addon_monitor.zip?dl=0
2. Open the addon
3. On loading screen, close Kodi only with one of case mentioned above
4. See log, the service exit correctly but the add-on remains in the loop and kodi will be freezed

### Debuglog

The debuglog can be found here:
log (test of atteched test addon, and close kodi with the shutdown menu)
https://paste.kodi.tv/usavaxokef.kodi

On last line
`2020-07-20 09:44:34.877 T:820      INFO <general>: Application stopped`
is declared as stopped but the kodi window is currently freezed on screen and on task manager still persistent in memory

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Kodi 18 and 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by WelpThatWorked** [comment]
This seems to occur with any python script that continues to run after the application stops. Possible solution is to kill any running scripts on exit?

**Comment by CastagnaIT** [comment]
the right way is that: 1) Kodi try send the abort request 2) if the abort fails then force close

the force close already exists, and is executed afterwards with a certain delay to give the closing time
but it appears to be working only for service instances
