### ISSUE TITLE
No 3d-output under Lubuntu

### ISSUE THREAD

**Issue by MPconta** [xbmc/xbmc#18206]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have some half-TAB-mkv's, which i want to playback in Kodi to watch them with a Panasonic pt at6000 projector. (In USA the device is called 'Panasonic pt ae8000')
Kodi is able to identify the file as 3d-film and gives me a menu with output-options to choose from. I take the "hardware-based" option to get a frame-packing signal, which the projector is able to process. Then the film starts, but instead of a stereo-signal, i get just a standard mono picture, like watching a 2d-movie.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect Kodi to deliver a proper frame-packing signal to the projector.

## Actual Behavior

I get just a 2d signal.

## Possible Fix

Kodi 18.7 is running under a standard Lubuntu 20.04. Maybe some drivers are missing?

### To Reproduce

 
Just start a half-TAB-mkv and choose hardware-based output.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/uwazuzayal

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Lubuntu 20.04
 - Kodi version: 18.7

- Hardware: ASRock J5005-ITX with Intel Pentium Silver J5005 and UHD Graphics 605

I hope there is still somebody, who is interested in 3d...

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
Hardware frame packing is not supported by the drivers/window system, which is not a Kodi bug. 

Instead, set your selection to TAB/same as movie and switch manually. 

If you are feeling really fancy, you could cobble up an IR blaster invoked by a Python script. Some devices can be controlled over Ethernet/RS232.
