### ISSUE TITLE
Kodi 19/Matrix: CECStandby UI Issue in system/peripherals.xml

### ISSUE THREAD

**Issue by satmandu** [xbmc/xbmc#18224]
### Describe the bug
```kodi-send -a CECStandby``` Does not work to turn off the TV.
```echo 'standby 0.0.0.0' | cec-client -s -d 1 ``` does work to turn off the TV.

kodi-wayland is starting on an ubuntu/dev (groovy) system with amdgpu and recent (5.7.* or 5.8rc7) kernel.

Kodi is compiled from master branch as of this morning. Libcec is compiled from https://github.com/Pulse-Eight/libcec using either 4.0.7 or 6.0.2. 

kodi-wayland is being started in gnome on Wayland (same results with fractional scaling enabled and disabled). 

The display driver is the kernel amdgpu driver.

(Originally reported here: https://github.com/add-ons/screensaver.turnoff/issues/18 )

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

```kodi-send -a CECStandby``` should turn put the TV in standby.

## Actual Behavior

Nothing happens at all.

```
2020-07-30 13:04:54.608 T:204593   DEBUG <general>: ToggleDeviceState - putting CEC device on standby...
2020-07-30 13:04:54.611 T:204729   DEBUG <general>: ProcessStandbyDevices - sending inactive source commands
2020-07-30 13:04:54.611 T:204728   DEBUG <general>: CecLogMessage - marking Playback 1 (4) as inactive source
2020-07-30 13:04:54.611 T:204728   DEBUG <general>: CecLogMessage - usbcec: updating active source status: inactive
2020-07-30 13:04:54.674 T:204728   DEBUG <general>: CecLogMessage - >> source deactivated: Playback 1 (4)
2020-07-30 13:04:54.689 T:204728   DEBUG <general>: CecLogMessage - << Playback 1 (4) -> broadcast (F): inactive source
2020-07-30 13:04:54.689 T:204728   DEBUG <general>: CecLogMessage - << 40:9d:11:00
2020-07-30 13:05:00.516 T:204728   DEBUG <general>: CecLogMessage - >> 80:8f
2020-07-30 13:05:00.564 T:204728   DEBUG <general>: CecLogMessage - >> 08:90:00
2020-07-30 13:05:08.517 T:204728   DEBUG <general>: CecLogMessage - >> 80:8f
2020-07-30 13:05:08.565 T:204728   DEBUG <general>: CecLogMessage - >> 08:90:00
```

### To Reproduce

**kodi-send --host=localhost -a CECStandby**

Using what I think is a reproducible build process for kodi I build kodi.

First I get the most recent kodi source from the Kodi nightly ppa.
```
echo "deb-src http://ppa.launchpad.net/team-xbmc/xbmc-nightly/ubuntu focal main" | sudo tee -a /etc/apt/sources.list.d/team-xbmc-ubuntu-xbmc-nightly-groovy.list
cd /tmp && sudo apt-get source kodi
cd kodi-*
tar -f ~/src/kodi.debian.tgz -cz debian
```
Then I run this:
```
#!/bin/bash
kodi_work=~/src/kodi_build
kodi_branch=master
dist=groovy
mkdir -p $kodi_work
cd $kodi_work
mkdir -p $kodi_work/packages
mv *.deb $kodi_work/packages
rm -f kodi*
[[ ! -d kodi_work/kodi ]] && git clone --depth=1 -b $kodi_branch https://github.com/xbmc/xbmc kodi
cd $kodi_work/kodi
git reset --hard
git clean -f
git pull
kodirev=$(git -C $kodi_work/kodi rev-parse --short $kodi_branch)
kodi_commitmsg=$(cd $kodi_work/kodi && git log -1 --pretty=%B)
cd $kodi_work/kodi && tar fx /localnet/build/kodi.d.tgz
sed -i '/BUILD_GBM :=/c\BUILD_GBM = no' $kodi_work/kodi/debian/rules
VERS=$(grep ADDON_API version.txt | awk '{print $2}')
date=$(date +%Y%m%d.%H%M)
dch --distribution ${dist} -b -v 2:$VERS+git${date}-${kodirev}-${dist} "${kodi_commitmsg}"
nice -n 20 debuild --no-tgz-check
```
Then I install the packages which have been made.

I reboot, and have kodi opened.

Then:
```
kodi-send --host=localhost  --action="ToggleDebug()"
kodi-send --host=localhost  -a CECStandby
sleep 15
kodi-send --host=localhost --action="ToggleDebug()"
sleep 5
pastebinit ~kodi/.kodi/temp/kodi.log
```

(The screen should turn off now.)

### Debuglog

Debug log can be found here:
**Kodi 19**: https://paste.ubuntu.com/p/TgpWw6tXdz/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 20.10 (dev/groovy)
 - Kodi version: 19-20200730-d302cb32ff

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by satmandu** [comment]
Ok, I've tracked this down in part.
If I have the TV set in "Devices to Power off during shutdown" under the CEC peripheral config screen this works.
But I don't want this to be powered off during shutdown!

There is also a toggle button which probably shouldn't be a toggle button for "Devices to also put in standby mode".

I really just want to be able to put the TV in standby, but not turn it off at shutdown (since I have other apps on there I want to keep open.)

Does that make sense?

The issue is likely here: https://github.com/xbmc/xbmc/blob/6fcbb13a90d8cd9782e4bfaee9ea19459e7aa45d/system/peripherals.xml#L20

This needs to have values options.

**Comment by satmandu** [comment]
OK I think I realized what my problem was.

In the CEC peripheral interface you can only mark devices to be turned off when kodi closes. Those devices are the ones that get turned off with the screensaver.

Basically, **if you don't have devices marked in "Devices to power off during shutdown" then the screensaver options just won't work.** Maybe those settings should be turned off when no devices are selected for being powered off during shutdown?

**Comment by cinatic** [comment]
this settings structure is really confusing, also testing is hard, additionally sometimes the settings only kick in when you restart kodi
