### ISSUE TITLE
Error playing video from Onedrive

### ISSUE THREAD

**Issue by leshafiq** [xbmc/xbmc#18221]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video should be play

## Actual Behavior

Something went wrong with this operation.
                                            
                                            Response <Exception>: {

                                              "error": {

                                                "code": "badArgument",

                                                "message": "One of the provided arguments is not acceptable.",

                                                "innerError": {

                                                  "date": "2020-07-28T06:40:14",

                                                  "request-id": "b1bba6a5-c7fb-41c4-bca4-f15a4fd98f7c"

                                                }

                                              }

                                            }
                                            Please try again later.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/4990154/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/68889041/88623481-9f74cf00-d0d7-11ea-9329-a216ca626273.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [/ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Kodi 18.1 is long outdated and unsupported. Please try to update to our current stable version and try to reproduce. 

If you can confirm then get us a new log

**Comment by DaVukovic** [comment]
Took a deeper look at your log. This seems to be a problem with the add-on itself and not with Kodi core. 

So please report here: https://github.com/cguZZman/plugin.onedrive/issues

**Comment by leshafiq** [comment]
Okay will do. Thanks !
