### ISSUE TITLE
Kodi 18.8 ReplaceWindow is broken

### ISSUE THREAD

**Issue by roidy** [xbmc/xbmc#18239]
### Describe the bug
Here is a clear and concise description of what the problem is:

As of Kodi 18.8 ReplaceWindow is broken.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When using ReplaceWindow the back history should not be updated so that when you actually go back you go back to the window before the one you replaced.

## Actual Behavior

When using ReplaceWindow in Kodi 18.8 pressing back returns you to the window you replaced and not the one before it.

### To Reproduce

This example skin (a modified version of Estuary) demonstrates the issue.

[skin.replacewindow_broken.zip](https://github.com/xbmc/xbmc/files/5010917/skin.replacewindow_broken.zip)
Changes are in Home.xml and MyVideoNav.xml

Please try it on both Kodi 18.7 and 18.8 and note that in 18.8 ReplaceWindow is broken 

### Debuglog

The debuglog can be found here: https://pastebin.com/5xTYWPs8

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 
18.7 Working
18.8 Broken

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@roidy are you using the return parameter?

**Comment by roidy** [comment]
Yes, I noticed the only recent changes are this commit:- https://github.com/xbmc/xbmc/commit/cb8b7f9b4fa0437ad184b5170f065333e44c5b51

**Comment by ronie** [comment]
as mentioned on the forum (https://forum.kodi.tv/showthread.php?tid=356174), i can confirm this issue.

a simple test method is to add a key mapping
```
<keymap>
	<global>
		<keyboard>
			<f2>ReplaceWindow(Videos,videodb://movies/genres/,return)</f2>
		</keyboard>
	</global>
</keymap>
```
and hit the 'back' button afterwards.

**Comment by roidy** [comment]
Also doing the following combination:-

```
ActivateWindow(Videos,videodb://movies/titles/,return)
ReplaceWindow(Videos,videodb://movies/genres/,return)
ReplaceWindow(Videos,videodb://movies/titles/,return)
```

Works as expected on 18.7, opens titles then replaces with genres then replaces with titles again.

However on 18.8 the final replace back to titles fails.

**Comment by roidy** [comment]
Any update on this?

**Comment by enen92** [comment]
Sorry I am a bit busy with real life so haven't looked into it yet.
But it's assigned to me and I will fix it as soon as possible. I doubt anything will be done for Leia though, that PR shouldn't have been accepted as a backport.

**Comment by roidy** [comment]
Sure I understand real life gets in the way 😄 

> I doubt anything will be done for Leia though, that PR shouldn't have been accepted as a backport.

That's disappointing 😞 This is a pretty major bug for skins that rely on ReplaceWindow, could that PR not just be rolled back?

Also this is broken in Kodi 19 as well.
