### ISSUE TITLE
Fire TV - Kodi fails to play video over ftp

### ISSUE THREAD

**Issue by puigru** [xbmc/xbmc#18248]
### Describe the bug

I'm trying to play a MKV video on my Fire TV. Once selecting the file, Kodi buffers for a bit and returns back to the file listing, if I attempt to play the same file again Kodi crashes out to the Fire TV launcher. The same file plays without issue on my computer.

## Expected Behavior

Kodi plays the file or at least doesn't crash.

## Actual Behavior

First time I select the file, Kodi buffers then brings me back to the file listing.
Second time, Kodi buffers then crashes out to the Fire TV menu.

### To Reproduce

1. Go to Movies
2. Navigate to file
3. Play file

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/ipikoqavem

## Additional context or screenshots (if appropriate)
The file is being streamed over FTP.
I've tried disabling hardware acceleration but nothing changed.
ffprobe output: https://pastebin.com/yvMfTh8M

Looking at the debug log, it would seem that when the file is first selected this pops up:
`ERROR: ffmpeg[B8CC1520]: [matroska,webm] Read error`
At the very top it says the version of ffmpeg used is 4.0.4.
I tried the Windows build of 4.0.2 and had no problem with the file (even from the same FTP server).
The second time, this pops up:
`CFileCache::Process - Source read didn't return any data! Hit eof(?)`
The log seems to end there and the log uploader didn't find any crash log.

## Possible Fix

I believe the reason for the crash could be related to the cache being bad due to the previous failure in playing the file.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fire OS 5.2.7.3 (652614020)
 - Kodi version: Kodi 18.8 (Leia)

**Comment by DaVukovic** [comment]
Could you confirm, that the same mkv file plays fine on the FireTV from another source (in meaning: not using frp)?

**Comment by XXLuigiMario** [comment]
@DaVukovic Tried over SSH, still get `ERROR: ffmpeg[B8CC1520]: [matroska,webm] Read error`.
However, trying to play the file over and over doesn't crash it, while it does over FTP.
Maybe something's wrong with the FTP VFS.

I can also confirm that the same file plays fine on the same version of Kodi on Windows.

**Comment by DaVukovic** [comment]
Well, from your log above I see: 

```
2020-08-03 22:30:20.704 T:15738  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
2020-08-03 22:30:20.706 T:15738  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
```
if that was changed in between, you should probably post another log to see what you have done

As it has something to do with ftp, I changed the title to something more suitable.

**Comment by XXLuigiMario** [comment]
I just copy pasted the cache settings from the cited examples in the Kodi wiki page I linked. As I mentioned, the video still doesn't play over SSH, so I wouldn't say it's strictly FTP related (meaning the ffmpeg Read error). It just doesn't crash when retrying to play it.

**Comment by malard** [comment]
this is a highly edge case scenario and has had no developer attention for 3.5 years, closing. We will accept a PR if someone wishes to resolve this. But its not a focus for the development team
