### ISSUE TITLE
Kodi on RPi3 cannot start

### ISSUE THREAD

**Issue by k0st1x** [xbmc/xbmc#18243]
Starting the device it shows only "LibreELEC (official): 9.2.3" (and the logo - smthng like this https://news-cdn.softpedia.com/images/news2/happy-pi-day-raspberry-pi-3-model-b-plus-support-comes-to-the-libreelec-embedded-os-520235-2.jpg ) and stop loading.
but the device is answered over the network by ssh and by samba.
so i've looked at the logs ( \\device.ip\Logfiles\ )

it is many lines with errors like "ERROR: SQL: [MyVideos116.db] SQLite error SQLITE_CORRUPT (database disk image is malformed)"
so i've tries to rename the file ~/.kodi/userdata/Database/MyVideos116.db -> MyVideos116.db.bak (i believed that file will be recreated automatically) but it does not work.

also the strange errors like "Backtrace stopped: previous frame identical to this frame (corrupt stack?)" - i dont know, was it before or not.

my log files i've attached here. 
[log-2020-08-02-19.56.57.zip](https://github.com/xbmc/xbmc/files/5012807/log-2020-08-02-19.56.57.zip)

previously i've not installed the os updates or the new addons.
may be some addon was auto-self-updated.

Please guide me, give me some advice, what to try next?

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
dont know hot wo view, but the latest stable.

**Comment by DaVukovic** [comment]
![grafik](https://user-images.githubusercontent.com/7235787/89132048-99388580-d511-11ea-9632-f56357ec2184.png)

2020-08-02 22:40:36.702 T:1936687120  NOTICE: Host CPU: ARMv7 Processor rev 4 (v7l), 4 cores available

I'm not so sure if we are talking about a RPi3, but the images for RPi2/3 are the same. So it shouldn't matter much. But as this seems to be a LibreELEC specific problem, you have to report that to LibreELEC: 

https://github.com/LibreELEC/LibreELEC.tv/issues

I'll keep this one open for the time being. But please report it to the issue tracker linked above. 

As a hint, I would try another SD card or probably at least try to reinstall LE

**Comment by k0st1x** [comment]
@DaVukovic i'm very appreciate for your initiative!
i've copied the issue to https://github.com/LibreELEC/LibreELEC.tv/issues/4505

also i dont get what the info i can read from your attached screenshot? that my hardware is 32bit?

**Comment by DaVukovic** [comment]
> also i dont get what the info i can read from your attached screenshot? that my hardware is 32bit?

No, the screenshot and the snippet from the log tells me, that you are *not* using a RPI3, but using a `RPi 2 Mod. B`. But it shouldn't make much of a difference boot-wise as both RPis are using the same image. I might also be wrong, but at least that's what the Raspberry Wiki tells me.

**Comment by k0st1x** [comment]
thx, i'll try to change the sd card
