### ISSUE TITLE
Set subtitles on when changing subtitle language (Feature request)

### ISSUE THREAD

**Issue by ElektroVirus** [xbmc/xbmc#18253]
### Describe the bug
Here is a clear and concise description of what the problem is:

This is more a feature request than bug report!
When subtitles are disabled (Video player -> Menu bar -> Subtitles -> Enable subtitles checkbox), it would be useful to automatically enable (change the state of the checkbox) if the user changes the subtitle language. I believe there are hardly any cases that the user will change the language, but still wants to have subtitles disabled. 

This is important, because the language selection box is easier to detect visually. The user finds the box, navigates to it, changes language, but the subtitles don't show up.  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If subtitles are disabled, changing the subtitle language should enable subtitles. 

## Actual Behavior

Subtitles language changed like expected, but subtitles didn't show up. Only after finding the checkbox "enable subtitles" was I able to get the subtitles.

## Possible Fix

Subtitle language change should change the state from the "subtitles enabled" checkbox to Enabled-state.
If subtitles are already enabled, this issue does not exist.
If the language is changed to the same language (it is by default e.g. English, and the sets the language to English), this action should also enable the subtitles.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo Linux
 - Kodi version: 18.7

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
>This is more a feature request than bug report!

Thanks. Feature requests have to be submitted at the forums: https://forum.kodi.tv/forumdisplay.php?fid=9

Please open a thread over there. This section is for bug-reports only
Thanks for understanding
