### ISSUE TITLE
Starting an ISO from the library twice doesnt load dvd/bluray menu the 2nd time

### ISSUE THREAD

**Issue by snake3ca** [xbmc/xbmc#18250]
### Describe the bug
Here is a clear and concise description of what the problem is:

If you play an ISO DVD or Bluray the menu will load fine the first time but on the second playback attempt the dvd/bluray menu will not work.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Would expect playing the ISO a second time would produce the same results as the first time playing it and show the menu.

## Actual Behavior

DVD/Bluray menu fails to load when playing the ISO a second time.

## Possible Fix

Have the ISO load the second time the same way as the first time.

### To Reproduce

1. Scan dvd or bluray ISO's to library
2. Play DVD or Bluray ISO
3. Stop playing the ISO
4. Start the ISO again.  DVD or Bluray menu will not work.

### Debuglog

The debuglog can be found here:
https://pastebin.com/LGxjUQA6

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

In the debug log on line 673 you can see the ISO playback matches the rule dvdimage, this is on the first playback attempt.  In the debug log on line 1187 you can see the second playback attempt of the ISO shows GetPlayers: matched 0 rules with players.

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.8 & 19 Alpha

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
As I see you are trying a concert, where is that musicvideo placed inside Kodi? Under "Music Videos" or under "Movies"? If it's under "Music Videos", does it make any difference if you sort it under "Movies"? 

I don't have any problems with DVD-ISOs under movies (those always start with the menu), but concert DVDs, which also have a menu and which I have sorted under "Musiv Videos" don't play a DVD menu at all. 

Could you probably do a video/screen cast of how you try to play that file? That would help much in that case to try to reproduce

**Comment by snake3ca** [comment]
They were scanned as music videos.  I tried rescanning my concerts as movies instead of music videos and it works fine when scanned to the library as movies.  So the issue only affects ISOs scanned as music videos.

**Comment by snake3ca** [comment]
I do have a video of the steps I take to reproduce the issue but github wont let me upload any files.

**Comment by snake3ca** [comment]
https://www15.zippyshare.com/v/caizIR2N/file.html

That link has a copy of the video I made. You can see on the first play attempt the dvd menu displays and the dvd menu option is available from the kodi menu bar, on the 2nd and 3rd attempt the menu doesnt work and dvd menu option is not available.

**Comment by DaVukovic** [comment]
I get a 403 from that link.

**Comment by snake3ca** [comment]
Try this

https://filebin.net/ed7w0pq8wl7ztovs

**Comment by snake3ca** [comment]
I see what your saying that ISOs scanned as musicvideos dont show the menu at all.  This only happens when "Attempt to skip introduction before DVD menu" option is not checked. 

Music Video ISOs seem to play regardless of that settings and regardless of whether or not its played the first or second time if you press "C" on the keyboard then goto "Information" then play the ISO.

**Comment by the-black-eagle** [comment]
@snake3ca I have a PR https://github.com/xbmc/xbmc/pull/18271 which should fix this if you're able to build it yourself on linux and test it?

**Comment by snake3ca** [comment]
I compiled and tested and its all working fine now.  Thanks for fixing this.

**Comment by DaVukovic** [comment]
Let's keep this open until the PR is merged. This issue should be auto-closed if the PRs makes its way into master
