### ISSUE TITLE
Sub Station Alpha subtitles stop working on release 18.8

### ISSUE THREAD

**Issue by jdh23662** [xbmc/xbmc#18259]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
You're going to have to provide a lot more information than that.

Start with a debug log at the very least.

**Comment by jdh23662** [comment]
Sorry, I thought I canceled the post to go set up debug logs. I instead completely uninstalled (personal setting also) and reinstalled.  The behavior stopped and all subtitles worked.  Realize there is not alot to analyze from me, but it repeated on 4 machines in my house. Maybe something in the uninstall during reinstall? Not expecting anything back but FYI eh?  Again sorry and goodbye..

**Comment by fuzzard** [comment]
All good mate. If you do capture logs and run across the same issue, just let us know
