### ISSUE TITLE
EmbyCon Streams on Android, stoping during watching (randomly)

### ISSUE THREAD

**Issue by lukkie112** [xbmc/xbmc#18265]
name: lukkie
about: EmbyCon Streams on Android, stoping during watching (randomly)

### Describe the bug
Here is a  description of what the problem is:
Hello!
Sorry for my bad english
I am usig EmbyCon few month with "http" Connection without problems
Now I have to use "https" instead of "http" to connect to my Server, because http is for me not available any more
Connection to Server is no Problem Streams are starting without problems but during streaming, streams abort/stops
Than I can push play and stream starts on the position, where the stream aborted
I have testet some EmbyCon Settings, but nothing helps
This Bug is only on multiple android devices, on Windows Kodi it works fine 

Fore excample some Hardware Sytstems with this issue:

FireTV1 / Kodi18.7 / EmbyCon stable 
nvidia shield 2017 / Kodi 18.6 / embycon stable 
nvidia shield pro / kodi 18.8 / Embycon stable 
xioami Mi Box / kodi 18.7 / embycon stable

## Expected Behavior
For this Problem i have had contact to the Emby Developer [Link to Emby](https://emby.media/community/index.php?/topic/88770-embycon-streams-stoping-during-watching-randomly/) but he said it is not an Emby problem rather a kodi problem with android

### To Reproduce

1. 
2.
3.

### Debuglog
her is a logfile from mey firetv1

[kodi.log](https://github.com/xbmc/xbmc/files/5048149/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
Internet is over stable Cable form my provider (75Mbit/s Download, 15Mbit/s Upload) and LAN Cable in the house 

I was doing a test on Windows PC and Android Handy (Samsung Galaxy A6+) over WLAN
It is definitely an android problem
On Windows PC the stream is working fine from begin to the end of an episode
But the same Episode on Android Handy stops
The Emby settings on Windows and Handy are the same
My FireTV1 (from my first posting) is connected over LAN Cable 
So you can see it's a problem of android with Kodi/Emby and not the internet connection

I hope this can help you to fix that issue 
 - [x ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.6 / 18.7 / 18.8

**Comment by enen92** [comment]
Sorry, this is not a Kodi bug but some issue related to the embycon plugin. Please bring it to the add-on developers instead.
Thanks for reporting the issue though.
