### ISSUE TITLE
v19 - Andoid TV - Channels not displaying posters

### ISSUE THREAD

**Issue by timfehr** [xbmc/xbmc#18272]
### Describe the bug
Here is a clear and concise description of what the problem is:
After the update to the alpha version of Matrix the channels on the Android TV homescreen do not show movie posters anymore. Instead a thumbnail is shown.
Also for some channels the format is is changed from potrait to landscape.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Same behaviour as v18, because nothing was mentioned in the changelog regarding this.

## Actual Behavior
Instead of posters, sometimes thumbnails and sometimes posters are shown. The thumbsnails are still in potrait mode, if posters are shown, there are in landscape. See pictures below.

## Possible Fix
No possible fix unfortunatetly

### To Reproduce
1. Start v19 alpha
2. Create e.g a "Recently added" channel as described [here](https://forum.kodi.tv/showthread.php?tid=332589)
3. Add the channel to the Android TV homescreen

### Debuglog

The debuglog can be found here:
[DebugLog](https://paste.kodi.tv/sazesedere.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:
![IMG_20200810_174149](https://user-images.githubusercontent.com/41877084/89802263-96e9b300-db31-11ea-82e0-d3b2048404bd.jpg)
![IMG_20200810_174205](https://user-images.githubusercontent.com/41877084/89802273-9b15d080-db31-11ea-8dd0-11586890c551.jpg)
![IMG_20200810_174212](https://user-images.githubusercontent.com/41877084/89802285-9f41ee00-db31-11ea-83c9-432ed509cc1d.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nvidia Shield TV 2019 Pro with firmware 8.1.1
 - Kodi version: v19 Matrix - Alpha

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Dnkhatri** [comment]
it was changed months ago 
https://github.com/xbmc/xbmc/pull/16741

**Comment by timfehr** [comment]
I know this PR, I can see the informations which got added in #16741 in the channel (In the pictures you see for example the rating), but no posters are shown and sometimes for movies landscape is used instead of potrait.
