### ISSUE TITLE
Let Kodi make use of android.permission.WRITE_MEDIA_STORAGE permission

### ISSUE THREAD

**Issue by DaisyF8** [xbmc/xbmc#18277]
### Describe the bug
Here is a clear and concise description of what the problem is:

On Bravia Android TV apps can write to USB Storage when Special app access / Directory access is given (this is what I assume is happening ).  With adb I want to grant Kodi android.permission.WRITE_MEDIA_STORAGE.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi uses the permission to write to USB

## Actual Behavior

I get an error Message when using adb to grant Kodi android.permission.WRITE_MEDIA_STORAGE
Security exception: Package org.xbmc.kodi has not requested permission android.permission.WRITE_MEDIA_STORAGE

## Possible Fix

Let Kodi make use of android.permission.WRITE_MEDIA_STORAGE permission

### To Reproduce

1. Be on Android TV (Android 9) or on Bravia Android TV (Android 9) 
2.Give permission android.permission.WRITE_MEDIA_STORAGE with adb

Debuglog
The debuglog can be found here:

Screenshots
Here are some links or screenshots to help explain the problem:

Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android Version 9, Kernel 4.9.125, Bravia firmware build 6.3632
 - Kodi version:18.7

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaisyF8** [comment]
Ignored rules concerning template : I think I just messed up the template code so the bot spanked me.  I think everything is present.

**Comment by DaVukovic** [comment]
Well, you missed to provide a debuglog. But I guess that's not of any help in that case. So I'll remove that label. 

I'm also not sure if this is more a feature request rather than a bug report. @peak3d might be able to tell more.
