### ISSUE TITLE
Enhancement request: Supporting external sup subtitles

### ISSUE THREAD

**Issue by lonecrane** [xbmc/xbmc#18283]
### Describe the bug
Here is a clear and concise description of what the problem is:

I am from a non-English country, and I used to collect the subtitles of English as well as my native language almost for every movie. In recent years, a growing number of subtitle files are in the form of ".sup" as they are demuxed from BD sources. 
At present, kodi only support internal sup subtitles and doesn't support the external ones. Thus, the external sup files need to be muxed with the main media file just to make them can be played by kodi, almost every time. Such a mux work may take tens of minutes, especially for the intact BD sources with large sizes. Moreover, the original materials, i.e., main media files, external subtitle files and external audio files, need to be kept for potential version updating. In my opinion, it is somewhat imperfect.
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It would be wonderful if kodi supports external sup subtitles as srt/idx/sub ones.

## Actual Behavior

At present, kodi doesn't support external sup subtitles. Actually, internal sup subtitles have been supported.

### To Reproduce

1. Play a BD source
2. Browser external subtitles by "Loading external subtitles"
3. Cannot find the existed sup subtitles

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64
 - Kodi version: 18.8

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Thanks for your report. But this is a "bug report"-section only. Feature requests have to be submitted at our forums. 

Please see: https://forum.kodi.tv/forumdisplay.php?fid=9

Please open a thread at our forums and explain your request. 
Cheers
