### ISSUE TITLE
Live TV Home Screen Display Issue in Estuary on Matrix Alpha 1

### ISSUE THREAD

**Issue by pkscout** [xbmc/xbmc#18285]
### Describe the bug
Here is a clear and concise description of what the problem is:

In Estuary on Matrix Alpha 1, there is some information at the bottom right of the screen that is jammed up and overlapping. See screenshot. Below.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I'd expect either the date or show duration to be shifted left so that both are visible.

## Actual Behavior

The two items are overlapping.

### To Reproduce

1. With a valid PVR addon activated, go to the LiveTV home screen area.
2. Highlight a last played channel.

### Debuglog

The debuglog can be found here:

https://pastebin.com/p54NVuHP

### Screenshots 
Here are some links or screenshots to help explain the problem:

![z3cHX9r](https://user-images.githubusercontent.com/1402018/90043226-8b000d00-dc67-11ea-9419-44616a09af43.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

19.0 Alpha 1 (18.9.701)
20200810-f0cb03b8fd

(note that I am using an artifact build to test an issue I found with the OSX compile where Pillow didn't work, but I saw the issue on the original Alpha 1 build as well)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
the skin expects a dd/mm/yyyy formatted date, see example for episodes:
![date](https://user-images.githubusercontent.com/687265/90061962-37350880-dce7-11ea-9729-4b69d29b64f8.jpg)

i'm not sure if it's supposed to be the same for pvr recordings or not... @ksooo ?

**Comment by pkscout** [comment]
OK, there is something odd going on related to the regional settings.  I went into the Regional Settings and changed the long date format to another format. I checked that same spot again, and the new long date format was showing. I then changed the long date format to the "default" regional date format, at which point the short date showed up on the PVR screen.  So apparently I had selected a non-default long date in region before, and that somehow triggers the long date to show instead of the short date.  I can generate some other log files if that will help any.

**Comment by ronie** [comment]
i you can still reproduce it, can you post a screenshot of Settings > Interface > Region ?
might be useful to know which combination of those settings triggers the problem.

**Comment by pkscout** [comment]
OK, things are getting stranger.  In the regional settings if I set it for anything other than US 12 hour with the defaults for the region (even some other country, even if I match the language), the long date is not converted to a short date on the PVR home screen.  Here's an example of a setting that, for me, causes the long date to show and overlap with the time of the show.

![Screen Shot 2020-08-13 at 9 44 24 AM](https://user-images.githubusercontent.com/1402018/90180485-bc9dd480-dd4a-11ea-9b19-5361fa80130c.png)

I've also got lots of strange duplicated options in the long date format:

![Screen Shot 2020-08-13 at 9 46 32 AM](https://user-images.githubusercontent.com/1402018/90180525-cc1d1d80-dd4a-11ea-8f54-26b5d6d6301c.png)

BTW, at this stage, I'm perfectly willing to accept that this is something strange on my machine. It's my development machine, so it's definitely not configured the way one might normally do things.

**Comment by ksooo** [comment]
Most probably the inconsistency and finally the GUI glitch is a result from slightly different implementation of ListItem.FirstAired and VideoPlayer.FirstAired for Video and PVR component.

Does this patch fix the issue?

```c++
diff --git a/xbmc/pvr/guilib/guiinfo/PVRGUIInfo.cpp b/xbmc/pvr/guilib/guiinfo/PVRGUIInfo.cpp
index 60babd77f8..2758ca5067 100644
--- a/xbmc/pvr/guilib/guiinfo/PVRGUIInfo.cpp
+++ b/xbmc/pvr/guilib/guiinfo/PVRGUIInfo.cpp
@@ -432,7 +432,7 @@ bool CPVRGUIInfo::GetListItemAndPlayerLabel(const CFileItem* item, const CGUIInf
       case LISTITEM_PREMIERED:
         if (recording->FirstAired().IsValid())
         {
-          strValue = recording->FirstAired().GetAsLocalizedDate(true);
+          strValue = recording->FirstAired().GetAsLocalizedDate();
           return true;
         }
         else if (recording->HasYear())
@@ -634,7 +634,7 @@ bool CPVRGUIInfo::GetListItemAndPlayerLabel(const CFileItem* item, const CGUIInf
       case LISTITEM_PREMIERED:
         if (epgTag->FirstAired().IsValid())
         {
-          strValue = epgTag->FirstAired().GetAsLocalizedDate(true);
+          strValue = epgTag->FirstAired().GetAsLocalizedDate();
           return true;
         }
         else if (epgTag->Year() > 0)
```

**Comment by pkscout** [comment]
@ksooo, will there be a Jenkins build artifact for that patch, or will it make it into a nightly? Or is there some other way to apply the patch on my Mac so I can check for you?

**Comment by ksooo** [comment]
@pkscout macOS build: https://jenkins.kodi.tv/job/OSX-64/19159/artifact/tools/darwin/packaging/osx/kodi-20200814-f081b5f9-PR18289-merge-x86_64.dmg

**Comment by ksooo** [comment]
Please report back in #18289, thanks.
