### ISSUE TITLE
Screensaver mode options

### ISSUE THREAD

**Issue by CaptainRewind** [xbmc/xbmc#18282]
### Describe the bug

Hello,

I use Kodi on Android TV (Nvidia Shield) to play music and video. When I pause either, only the screensaver turns on. The Power Saving settings never take effect.

It would be helpful to have an option to Quit after media is paused for x minutes, thereby allowing system power-saving measures to be applied. In my case, this turns off several power-hungry components along with it.

I have had people (kids) leave it on for a really long time. It would be nice to have all systems turn off.

There are some community screensavers which are supposed to exit Kodi. Not one works on my system, and even if they did, they would not achieve the full desired behavior. For example, the current screensaver behavior is great when playing audio, but I wouldn't want Kodi to exit while it's playing.

Thanks!

## Expected Behavior

When enabled, and media is paused for a configurable time period, Kodi will Quit.

## Actual Behavior

No such option exists, and Kodi remains the foreground app indefinitely.

## Possible Fix

An option to Quit after Kodi has been paused for a configurable time.

### To Reproduce

1. Open Kodi on Android TV
2. Play any audio or video
3. Pause
4. Observe that Kodi does not exit/quit, superseding system idle settings in perpetuity

### Debuglog

The debuglog can be found here:

http://paste.kodi.tv
with the following path:
/anotadigaz

(note - the screensaver timeout was set to 1 minute, and the power saving to 5 minutes. The screensaver enables exactly 1 minute after PlayPause, but no Power saving init.)

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 
Shield Android TV SW Version 
8.1.1(32.7.301.99)

 - Kodi version:
18.7 Leia

**Comment by DaVukovic** [comment]
Thanks for your report, but eature requests have to be submitted to the forums: 

https://forum.kodi.tv/forumdisplay.php?fid=9

**Comment by CaptainRewind** [comment]
My mistake, I thought this was the correct place.

I will do that, thanks.
