### ISSUE TITLE
Multi-episode regex matches common filenames

### ISSUE THREAD

**Issue by ned-martin** [xbmc/xbmc#18290]
### Describe the bug

Multi-episode regex matches common filename pattern, resulting in the same episode being incorrectly added to Kodi multiple times as multiple episodes.

Here is an example using a commonly used filename structure which causes this problem:

```
DEBUG: VideoInfoScanner: Found episode match <path>\Elementary\Season 1\Elementary_S01E01_x265_720p_WEB-DL.mkv (s1e1) [s([0-9]+)[ ._x-]*e([0-9]+(?:(?:[a-i]|\.[1-9])(?![0-9]))?)([^\\/]*)$]
DEBUG: VideoInfoScanner: Adding multipart episode 265 [^[-_ex]+([0-9]+(?:(?:[a-i]|\.[1-9])(?![0-9]))?)]
DEBUG: VideoInfoScanner: Adding multipart episode 720 [^[-_ex]+([0-9]+(?:(?:[a-i]|\.[1-9])(?![0-9]))?)]
```

## Expected Behavior
Episode 1 of Season 1 of TV show Elementary should appear in Kodi.

## Actual Behavior
Episodes 1, 265 and 720 of season 1 of TV show Elementary appear in Kodi.

## Possible Fix
Update regex to be more specific.

### To Reproduce
Add episode file `Elementary_S01E01_x265_720p_WEB-DL.mkv` with matching NFO file `Elementary_S01E01_x265_720p_WEB-DL.nfo` to a TV show (i.e. folder with valid `tvshow.nfo`) and scan into media library using Local Information Only scanner.

### Debuglog
```
DEBUG: VideoInfoScanner: Found episode match <path>\Elementary\Season 1\Elementary_S01E01_x265_720p_WEB-DL.mkv (s1e1) [s([0-9]+)[ ._x-]*e([0-9]+(?:(?:[a-i]|\.[1-9])(?![0-9]))?)([^\\/]*)$]
DEBUG: VideoInfoScanner: Adding multipart episode 265 [^[-_ex]+([0-9]+(?:(?:[a-i]|\.[1-9])(?![0-9]))?)]
DEBUG: VideoInfoScanner: Adding multipart episode 720 [^[-_ex]+([0-9]+(?:(?:[a-i]|\.[1-9])(?![0-9]))?)]
```

### Your Environment
Replicated on Kodi 18.2 and 17.6, Windows 7 and 10

**Comment by ned-martin** [comment]
Bug report provides sufficient information to easily replicate problem and follows the template.

**Comment by KarellenX** [comment]
The full debuglog is missing. Please provide it. 3 lines are not enough

**Comment by ned-martin** [comment]
> 
> 
> The full debuglog is missing. Please provide it. 3 lines are not enough

I believe those three lines are all that's needed to debug this issue. What extra information do you need?

Feel free to install a fresh, unmodified install of Kodi on Windows to demonstrate this issue if you distrust my configuration in some manner.

**Comment by KarellenX** [comment]
If you are experiencing problems, then please edit your default regex or change your file naming style...

https://kodi.wiki/view/Advancedsettings.xml#tvmultipartmatching
