### ISSUE TITLE
Movie name is not properly sorted in movie database for certain languages, such as chinese and so on. setLocale isn't called.

### ISSUE THREAD

**Issue by phantasm658** [xbmc/xbmc#18295]
### Describe the bug
Here is a clear and concise description of what the problem is:

Movie name is not properly sorted in movie database for certain languages, such as chinese and so on.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Movies in database could be sorted in localized name.
Like this:
https://am.zdmimg.com/201902/26/5c75271fdbd965930.png_e680.jpg

## Actual Behavior

Movies in database is sorted in raw unicode strings, so non-english movies are sorted randomly...

## Possible Fix

The problem is SQLite use unicode strings. and setLocale hasn't been called.

https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase#setLocale(java.util.Locale)

### To Reproduce

1. Import some movies and change their name to chinese.
2. Here's a test case. 

English| Chinese | Chinese-Pinyin
------- | ---------| ---------
Aladin | 阿拉丁 | **a** la ding
Jaws | 大白鲨 | **d**a bai sha
Matrix | 黑客帝国 | **h**ei ke di guo
Lion King | 狮子王 | **s**hi zi wang
The Lord of the Rings: The Fellowship of the Ring | 指环王:护戒使者 | **z**hi huan wang

3. When properly localized, movies named in Chinese above should be sorted by the first character of Chinese-Pinyin

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [*] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Android TV 9.0
 - Kodi version:
18.7 leca

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by yol** [comment]
Hi, I can recognize the problem that you are having, but we are not using Android SQLite; we are using the regular C library on all platforms. So, it is neither possible nor necessary to call `setLocale`. Sorting is done by Kodi and not by SQLite.

There is already a roadmap issue for this: https://github.com/xbmc/xbmc/issues/15125 so I'm closing this.

**Comment by yol** [comment]
Thanks for reporting. You could help test #17833 I think

**Comment by phantasm658** [comment]
Thanks anyway!
