### ISSUE TITLE
Kodi 18.8 Crashing After Closing

### ISSUE THREAD

**Issue by Blurayx** [xbmc/xbmc#18324]
### Describe the bug
Here is a clear and concise description of what the problem is:

Crashing after Closing

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Close as normal no Crash report

## Actual Behavior

After closing Kodi I always get an error report

## Possible Fix

None. This issue has been going on for years. The issue was on the previous Kodi's 17 & 16

### To Reproduce

1. open Kodi
2. close Kodi
3.  Mac generates an error report

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ivoxobovos    

### Screenshots 
Here are some links or screenshots to help explain the problem:

<img width="1000" alt="Screenshot 2020-08-25 at 11 08 56" src="https://user-images.githubusercontent.com/2873112/91163168-10061000-e6c5-11ea-8a92-126204ae5c77.png">

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [11] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
MacOS Big Sur Beta 5
 
As mentioned before regardless of the OS this has always been an issue. The issue happens with macOS Catalina.

Kodi 18.8.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Please provide the full output of that crashreport you posted on your screenshot. That snippet is likely useless and the log doesn't show anything as well as it was uploaded while Kodi is still running. 

So we need the output of that report and not only a snippet like it's currently shown

Thanks in advance

**Comment by Blurayx** [comment]
> Please provide the full output of that crashreport you posted on your screenshot. That snippet is likely useless and the log doesn't show anything as well as it was uploaded while Kodi is still running.
> 
> So we need the output of that report and not only a snippet like it's currently shown
> 
> Thanks in advance

Sorry I thought the Kodi log was enough
I hope this helps

[ Kodi error report.txt](https://github.com/xbmc/xbmc/files/5152220/Kodi.error.report.txt)

**Comment by Blurayx** [comment]
Thank you for replying😀
Yes, this also happens with Kodi 19. but it only happens when I first install it. after that, it behaves normally.
 I have attached another log for Kodi 19 if you're interested.
[Kodi 19 crash Log.txt](https://github.com/xbmc/xbmc/files/5166943/Kodi.19.crash.Log.txt)

**Comment by DaVukovic** [comment]
ok, so sounds to me, that it's somewhat fixed if everything works well after the 2nd run.

**Comment by Badsheep** [comment]
Same here with Kodi 19.3 and Big Sur 11.6

**Comment by enen92** [comment]
Please shout out if the same issue still happens on recent nighlies. Closing as obsolete.
