### ISSUE TITLE
[GUIEngine] Wraplist containers are broken

### ISSUE THREAD

**Issue by ronie** [xbmc/xbmc#18325]
### Describe the bug
Here is a clear and concise description of what the problem is:

wraplists are currently broken when they contain only a few items (less than what would fit on screen).
they do not align properly and the scrolling behaviour is acting weird.
i have tracked down to issue down to the changes in https://github.com/xbmc/xbmc/pull/17548

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

![expected](https://user-images.githubusercontent.com/687265/91172831-24560700-e6dd-11ea-8fa4-e14f2e492b6d.jpg)

## Actual Behavior

![actual](https://user-images.githubusercontent.com/687265/91172847-2ae47e80-e6dd-11ea-9de6-189dad8e72e5.jpg)

## Possible Fix

as a test i've reverted the changes to GUIBaseContainer.cpp (https://github.com/xbmc/xbmc/pull/17548/files),
which fixes the issue for me. 

### To Reproduce

1. pick a skin that uses wraplists (estuary doesn't)
2. navigate to a list that only contains a few items
3. notice the alignment is completely off and scrolling the lists behaves weird

see also: https://forum.kodi.tv/showthread.php?tid=356650

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/wezunawuju.kodi
(nothing interesting though)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Manjaro Linux
 - Kodi version: 19.0-ALPHA1 Git:20200324-f98fe01801

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by gade01** [comment]
I can confirm this issue inside libraries.

Also confirmed here: https://forum.kodi.tv/showthread.php?tid=343552&pid=2977184#pid2977184

**Comment by ronie** [comment]
ping @peak3d

**Comment by jjd-uk** [comment]
@peak3d in case you didn't realise @ronie has this marked as a release blocking issue here https://forum.kodi.tv/showthread.php?tid=352798  so needs to be fixed for v19.

**Comment by peak3d** [comment]
I'll try to reproduce, thx for tracking it down to this point already!

**Comment by jjd-uk** [comment]
@peak3d to save you looking for it in the log (if you haven't already seen), the skin ronie used to reproduce in his screenshots was his Transparency skin.

**Comment by peak3d** [comment]
one of you guys @jjd-uk , @ronie is able to test the change with transparent when artifacts are finished pls.?

**Comment by gade01** [comment]
I can confirm all issues are fixed now, thanks.

**Comment by DaveTBlake** [comment]
Fixed by #18683
