### ISSUE TITLE
Nightlies use high amount of CPU while doing nothing 

### ISSUE THREAD

**Issue by kraaa** [xbmc/xbmc#18326]
### Describe the bug
Kodi nightlies from a week until now use 18-30+% cpu usage when just idling on second screen in fullscreen.

Here is a clear and concise description of what the problem is:

I can find nothing extra in debug that shows why Kodi should be working in 10-30+% cpu usage when just idling on main menu.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi would use 0.5-2% cpu usage as older version 18.5 when idling

## Actual Behavior

Kodi uses 30% of CPU on seemingly nothing.

### To Reproduce

1. Run Windows x64 nightly
2. Maybe it's some of my addons but they don't show errors in debug.
3.

### Debuglog

The debuglog can be found here:

**Nightlies running cpu at 10-30+% just idling**:
https://paste.kodi.tv/awosojorav.kodi

**18.5 running cpu at 0.5-2% just idling**
https://paste.kodi.tv/hinomucate.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 2004 H2, kernel: Windows NT x86 64-bit version 10.0.19042.450 
 - Kodi version: Kodi compiled 2020-08-25 by MSVC 191627035 for Windows NT x86 64-bit version 10.0
Dual monitor, Kodi Fullscreen, GTX1060 6gb HDMI > AVR Video passthrough HDMI > Sony X950G
i7-4790K CPU @ 4.00GHz, 8 cores available, 16.0 GB RAM
Kodi installed on SSD.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by kraaa** [comment]
Apparently clean install of Kodi does not use as much CPU, i will investigate my addons.

**Comment by kraaa** [comment]
Library watchdog is the culprit.

**Comment by enen92** [comment]
Hey @kraaa 
Thanks for the bug report. Unfortunately this is not related to the kodi core but with a specific addon. Please bring the issue request to the library watchdog author
