### ISSUE TITLE
Android Kodi 18.8 sound issue with Receiver Sony STR DN1070 but not WBMC  18.0 RC1

### ISSUE THREAD

**Issue by bibble235** [xbmc/xbmc#18329]
### Describe the bug
When I tried to play some videos audio falls out of sync within the first 1-2 minutes. 

## Expected Behavior
Audio in video should be played in sync 

## Actual Behavior
Audio is is play out of sync within 1-2 minutes of starting

## Possible Fix
No idea but happy to help

### To Reproduce

1. Open Kodi
2. Play Video

### Debuglog

The debuglog can be found here:

### Screenshots 
Not valid

## Additional context or screenshots (if appropriate)
None

### Your Environment
Used Operating system:

 - [ X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.8

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

Other relevant Hardware
Sony Receiver STR DN1070
Sony TV Bravia_ATV2 pa-user 8.0.0
Android Kodi 18.8
HDMI

More than happy and capable to provide more information. I have built Kodi for my TV before.

Thanks

**Comment by fuzzard** [comment]
Definitely provide debug logs of the failure.

**Comment by DaVukovic** [comment]
can't confirm with Android on the shield. Everything is perfectly in sync

**Comment by DaVukovic** [comment]
No debuglog, No reaction.

Issue closed
