### ISSUE TITLE
[Request] Http streaming --ignore-content-length

### ISSUE THREAD

**Issue by Jeronimo17** [xbmc/xbmc#18344]
Hi, is it possible to ignore the content-length header or activate some option for it? as is done with Curl with --ignore-content-length or --http-continuous in VLC, because I think Kodi uses Curl.

My server sends a false Content-Length header: 2624204796, when it reaches that download the stream stops, this happens on the PC if I don't add the headers I think that on Kodi it cuts me off for that too

Thank you

**Comment by DaVukovic** [comment]
This is not a support section. If you need support please head over to our forums: https://forum.kodi.tv
