### ISSUE TITLE
Kodi v18.8 on Nvidia Shield missing Play Only, when autoplaynext is enabled

### ISSUE THREAD

**Issue by dayton967** [xbmc/xbmc#18347]
### Describe the bug
when you have any combination of Auto Play Next for Video Items configured, it will only show "Play from here" as an option, and the "Play only this" is never shown.  As the code still has the "Play only this" context menu still in the code, but there was a change  to the videoplayer.autoplaynext option from a boolean to a string, it seems that this code was missed in xbmc/video/windows/GUIWindowVideoBase.cpp on line 892.

## Expected Behavior
When auto play is enabled, the context menu "Play from here", should change to "Play only this"

## Actual Behavior
No matter the the configuration only "Play from here" is in the context menu.

### To Reproduce
1. Turn on Autoplaynext for the video 
2. go to a movie and open up the context menu

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
thanx for the report!
potential fix pending: https://github.com/xbmc/xbmc/pull/18349
