### ISSUE TITLE
[PVR] Playback of MPEG-TS stream with audio bitrate higher than video bitrate fails

### ISSUE THREAD

**Issue by djp952** [xbmc/xbmc#18389]
### Describe the bug
When attempting playback of PVR MPEG-TS streams where the audio bitrate is higher than the video bitrate (i.e. MusicChoice), Kodi may stutter/buffer (live) playback or prematurely abort (recorded) playback.

This is difficult to observe from a recorded MPEG-TS file as opposed to a live MPEG-TS stream, however I was able to capture a sample that behaves poorly in the recorded case and hope that the information from the logs will prove useful. 

This problem was also reported in the Kodi forums: https://forum.kodi.tv/showthread.php?tid=354587

## Expected Behavior
The expectation is that Kodi will behave like VLC and/or the included video player(s) in Windows 10 and not stutter/buffer (live) or prematurely abort (recorded) playback of the stream.  No other applications tested have any problems with playback of the sample file linked below:

SAMPLE FILE (MS OneDrive): https://1drv.ms/v/s!AgEGEEVzGNq-jJRM39iuZBGIRgn9Eg?e=bXhAze (musicchoice-1827.mpg)

## Actual Behavior
Kodi has difficulty with these streams.  In the live/real-time case Kodi will repeatedly stop audio momentarily, in the recorded case, Kodi will abort playback prematurely.

## Possible Fix
Can't help that much other than testing a potential solution.  Suspect that the video PTS is taking priority over the audio PTS for streams like this where both video and audio are present, but audio is the dominating stream.

### To Reproduce
Download linked file, attempt playback via Kodi.  Sample is 30 seconds long, on Windows (at least) playback will stop at 26 seconds, which is incorrect.  If Verizon FiOS "MusicChoice" channel(s) are available to test via a PVR, attempt to stream/playback via the PVR as a "live" channel, playback will suffer from audio stopping and/or buffering taking place.

### Debuglog
Debug log (live playback): https://paste.kodi.tv/efixoricib.kodi
Debug log (recorded playback): https://paste.kodi.tv/igafifevoh.kodi

### Screenshots 
I've uploaded a couple videos illustrating the behavior seen on both Matrix and Leia (onedrive): https://1drv.ms/u/s!AgEGEEVzGNq-jJRLAQ1wnjfu0JfHfg?e=UZllUP

The Matrix.mp4 shows the behavior via PVR binary addons (pvr.hdhomerun and zuki.pvr.hdhomerundvr).  The addons use different methods for playback, pvr.hdhomerun specifies a URL, zuki.pvr.hdhomerundvr handles the Input Stream itself.

Matrix.mp4 -> zuki.pvr.hdhomerundvr then pvr.hdhomerun

The Leia.mp4 shows the behavior via the PVR binary addons as well as a couple Python-based addons.  Note that the SiliconDust HDHomeRun View addon used here has been modified to flag the stream as 'realtime', otherwise it would buffer and stall similarly to HDHomeRun Simple when the problem is encountered.

Leia.mp4 -> pvr.hdhomerun then zuki.pvr.hdhomerundvr then HDHomeRun View then HDHomeRun Simple

The lengthy amount of time it takes to start the streams may also be a symptom that was best illustrated rather than described.  I believe Kodi is waiting for a video keyframe or something along those lines, and again the video stream bitrate is very low here.

## Additional context or screenshots (if appropriate)
N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Microsoft Windows 10, version 2004, current as of 2020.09.08.

 - Kodi version: 20200904-339dd24a8c (master branch)

**Comment by djp952** [comment]
Added a couple videos to help illustrate the behavior being experienced on both Matrix and Leia.  Leia was included due to having a couple Python-based addons to use as well.

**Comment by L2501** [comment]
possibly due to the small default caches
https://github.com/xbmc/xbmc/issues/16003#issuecomment-606306601

**Comment by djp952** [comment]
> possibly due to the small default caches
> [#16003 (comment)](https://github.com/xbmc/xbmc/issues/16003#issuecomment-606306601)

Thank you for the suggestion! I rebuilt per the recommended increases to SetMaxDataSize and SetMaxTimeSize, but sadly it had no effect on the underlying Issue.  Much appreciated, though!

**Comment by emveepee** [comment]
Here is another issue that probably can be linked with this one https://github.com/xbmc/xbmc/issues/17041

**Comment by djp952** [comment]
> Here is another issue that probably can be linked with this one #17041

That Issue appears to be more accurate and on-point as to the underlying reason of the concern than this Issue is; would you recommend closing this Issue in favor of that Issue?

**Comment by FernetMenta** [comment]
solution:
VP should tolerate stalling of video stream, if this is a still image. ffmpeg seems to be able to detect this:

```
Stream #0:0[0x10cd], 0, 1/90000: Video: mpeg2video ([2][0][0][0] / 0x0002), none, 90k tbn (still image)
```

**Comment by djp952** [comment]
Based on @FernetMenta's comment I have a relatively unintrusive proposed PR that solves most of this that I will submit once it's tested on a Release build and the logs look clean enough to proceed with it.  Of note is that I think there are actually **two** separate concerns here; the periodic pause of audio over time and the initial delay of playback in conjunction with a potential for a one-time pause of the audio stream.  The PR (if submitted) will only attempt to fix the first concern.

The secondary concern is tied more to stream startup than general playback -- playback will not start until the first video still frame has been decoded and a one-time pause in the audio stream is being caused by the following condition as opposed to the general presence of still frames in the video stream:
https://github.com/xbmc/xbmc/blob/bd9f2877aad8e6d9365b9c5692f2ef338c56866a/xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp#L218

I think these concerns should be treated separately since the potential side-effects of trying to fix them will be very different.

**Comment by djp952** [comment]
I believe this issue can be closed due to the merge of PR [19048](https://github.com/xbmc/xbmc/pull/19048).
