### ISSUE TITLE
Remove trac.kodi.tv account

### ISSUE THREAD

**Issue by CurtisLeeBolin** [xbmc/xbmc#18387]
Since trac.kodi.tv is no longer used, could all accounts be deactivated?   I am still able to login to my account, but there is no way for me to change my password or disable my account.

**Comment by CurtisLeeBolin** [comment]
Please removed the "Ignored rules" label.

**Comment by jaylinski** [comment]
I think that's something you should ask in the IRC channel or in the forum.

**Comment by DaVukovic** [comment]
If I'm not totally mistaken, trac uses the same login the forums are using. I can't remember creating an account on that separately. 

If you want to remove that account, then I guess you also have to remove your account at forums.kodi.tv. 

In any way, that's not something which should be discussed here. As this section is for Kodi core bug reports. So either ask at the forums or at IRC. 

Cheers

**Comment by CurtisLeeBolin** [comment]
@DaVukovic, thank you.  I was able to change my password at forum.kodi.tv, and it was also changed for trac.kodi.tv.
