### ISSUE TITLE
Kodi crashes on startup when Addons.db is removed and language pack is not default 'English'

### ISSUE THREAD

**Issue by howie-f** [xbmc/xbmc#18384]
### Describe the bug
When database file AddonsXY.db is removed prior to startup for any reason (testing, db-corruption etc.) and the installed and selected language pack addon is not the default `English` Kodi crashes.

The crash happens after the re-creating the database file.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Kodi should recreate the missing Addons database and startup normally.

## Actual Behavior
db file is created but kodi crashes afterwards

### To Reproduce
1. set your gui language to anything but english (for example german, has alse been reproduced with french)
2. remove your database file(s) AddonsXY.db from directory `.kodi/userdata/Database`
3. start kodi

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/jurobicoya.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian Stretch, Ubuntu 18, Ubuntu 20
 - Kodi versions: current master built from source - leia from official ubuntu ppa

@da-anda could you please add information if you reproduced this on windows?

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Application fails to initialize because CLangInfo::SetLanguage returns false.. The crash is not the cause, but fallout.

<img width="921" alt="Screenshot 2020-09-07 at 21 13 45" src="https://user-images.githubusercontent.com/3226626/92413170-22655c80-f14f-11ea-9e62-f8efcf8574b6.png">

**Comment by ksooo** [comment]
And this is the problem: Language resource addon can't be loaded (ofc, because we deleted Addons.db):

<img width="1077" alt="Screenshot 2020-09-07 at 21 34 51" src="https://user-images.githubusercontent.com/3226626/92413804-0a430c80-f152-11ea-9cdd-76c0a2040652.png">

**Comment by phunkyfish** [comment]
Ok, so just need to figure out why the DB is not initialised before this point. I guess when a fresh install initialises userdata would be a good starting point.

**Comment by ksooo** [comment]
The DB is empty, no db file present. If you recreate the db (what will happen in this scenario), will it scan the addons folder and recreate information? I don't think so.

**Comment by the-black-eagle** [comment]
It does, but, all languages are disabled apart from english.  If I edit the db and enable it, Kodi will start.

**Comment by ksooo** [comment]
Not sure what this code wants to achieve, but for our scenario the if block gets not executed, because the call to GetAddon succeeds because `false` means also to return not enabled addons.

<img width="967" alt="Screenshot 2020-09-07 at 21 53 19" src="https://user-images.githubusercontent.com/3226626/92414525-eb924500-f154-11ea-9021-5f89043d2055.png">

**Comment by ksooo** [comment]
I guess the fix is as simple as changing that `false`to `true` to get Kodi started with the default language, which is always available.

**Comment by ksooo** [comment]
Yep, this will do the trick.

Sigh, the problem with bool params. When looking at the code, you will never know with this true or false in the parameter list actually means...

**Comment by ksooo** [comment]
Feel free to PR:

```diff
diff --git a/xbmc/LangInfo.cpp b/xbmc/LangInfo.cpp
index 70699bc15b..dc51fd26cb 100644
--- a/xbmc/LangInfo.cpp
+++ b/xbmc/LangInfo.cpp
@@ -662,7 +662,7 @@ bool CLangInfo::SetLanguage(std::string language /* = "" */, bool reloadServices
     language = CServiceBroker::GetSettingsComponent()->GetSettings()->GetString(CSettings::SETTING_LOCALE_LANGUAGE);
 
   ADDON::AddonPtr addon;
-  if (!CServiceBroker::GetAddonMgr().GetAddon(language, addon, ADDON::ADDON_RESOURCE_LANGUAGE, false))
+  if (!CServiceBroker::GetAddonMgr().GetAddon(language, addon, ADDON::ADDON_RESOURCE_LANGUAGE, true))
   {
     CLog::Log(LOGWARNING, "CLangInfo: could not find language add-on '%s', loading default..", language.c_str());
     language = std::static_pointer_cast<const CSettingString>(CServiceBroker::GetSettingsComponent()->GetSettings()->GetSetting(
```

**Comment by phunkyfish** [comment]
We could also enable the addon if disabled. Any reason we would not do that?

**Comment by howie-f** [comment]
@ksooo you found it, you‘ll pr it ;) i‘ll runtime test and approve .. thanks a lot.

**Comment by phunkyfish** [comment]
@ksooo might be too busy.

**Comment by ksooo** [comment]
@phunkyfish I would stick with that simply fix. But no hard feelings on this.

**Comment by howie-f** [comment]
ok, if it‘s not open tomorrow, then i‘ll take on 😀

**Comment by ksooo** [comment]
@howie-f  do it. I wont PR this - as @phunkyfish says, it is pure luck that I found a couple of minutes for Kodi today...

**Comment by howie-f** [comment]
ok

**Comment by ksooo** [comment]
Thx, saves me some time.
