### ISSUE TITLE
CEC adapter notification stuck on screen if smartredraw is enabled

### ISSUE THREAD

**Issue by HiassofT** [xbmc/xbmc#18391]
### Describe the bug
When enabling smartredraw in advanced settings the "Pulse-Eight CEC adapter" notification appears after kodi startup, but the "Connecting to..." text doesn't scroll and the notification doesn't disappear.

When playing a video the text scrolling finishes, but the notification is still shown. Bringing up the progress bar doesn't help, but bringing up the player process windows and then closing it makes the notification disappear.

Another way to make the notification go away is to stop the video and then start playback a second time.

## Expected Behavior
CEC notification animation and removal works identically to normal mode (smartredraw disabled).

## Actual Behavior
Notification is stuck.

### To Reproduce
1. enable smartredraw in advancedsettings.xml
2. start kodi - notification is stuck on screen without animation
3. play a video - message text in notification scrolls but notification doesn't disappear
4. press "o" to bring up player process - no change to notification
5. close player process with "ESC", notification disappears

### Debuglog
The debuglog can be found here: http://ix.io/2wVP

### Screenshots 
Here are some links or screenshots to help explain the problem:

After kodi startup:
![screenshot002](https://user-images.githubusercontent.com/3920953/92589610-15558400-f29b-11ea-89b5-44d31bfc756a.png)

After starting video playback:
![screenshot003](https://user-images.githubusercontent.com/3920953/92589697-39b16080-f29b-11ea-9e3d-543d20644eab.png)

After bringing up player process window:
![screenshot004](https://user-images.githubusercontent.com/3920953/92589721-49c94000-f29b-11ea-97e2-6c1be6ee8920.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC master, RPi4
 - Kodi version: master 2b4f988e329a0271724c7d804ac3c7163b771897

**Comment by iax2RqPZbq** [comment]
Also seeing this. I have found playing/stopping a video a few times makes the notification disappear.

Using Kodi version: `18.9 (18.9.0) Git:newclock5_18.9-Leia Media Center Kodi`

**Comment by smf007** [comment]
Same as #15354
