### ISSUE TITLE
tvOS movie posters not being populated

### ISSUE THREAD

**Issue by scj643** [xbmc/xbmc#18409]
### Describe the bug
Movies are no longer showing images on the topshelf 

## Expected Behavior
Movie posters for recently added movies

## Actual Behavior
The posters are blank for recently added movies. TV shows are unaffected.

## Possible Fix
Changes made to the Topshelf handler might have introduced this bug.

### To Reproduce
Add new movies.
Go to the main menu 

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/safexixugu.kodi

### Screenshots 
https://imgur.com/a/z5UZSq9

### Your Environment
Used Operating system: tvOS

 - [ ] Android
 - [ ] iOS
 - [x] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: tvOS 13.4.8
 - Kodi version: 20200910-afbd3f9c-master-tvos

**Comment by sy6sy2** [comment]
Hi!
Thank you for the issue. We are aware of this issue. 
As you said this bug was introduced by the recent PR concerning TopShelf. 
This PR (https://github.com/xbmc/xbmc/pull/18383) is on the road and should fix the issue 😉
