### ISSUE TITLE
Unable to seek or pause video playback using HLS event playlist with missing EXT-X-ENDLIST tag

### ISSUE THREAD

**Issue by djbloc** [xbmc/xbmc#18415]
### Describe the bug
Here is a clear and concise description of what the problem is:

During playback of HLS Event type playlist, Kodi will not seek or pause if the playlist doesn't initially have an EXT-X-ENDLIST tag, indicating that new media files are being added to the playlist as they become available.

Event Playlist Construction Example - [https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming/event_playlist_construction](https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming/event_playlist_construction)

## Expected Behavior

The VideoPlayer will allow seeking or pausing playback of video from HLS event type playlist streams which don't initially have an EXT-X-ENDLIST tag

## Actual Behavior

The VideoPlayer only allows stopping of the video from HLS event type playlist streams which don't initially have an EXT-X-ENDLIST tag

Note: If the HLS event type playlist has EXT-X-ENDLIST tag at start of playback then VideoPlayer will allow seeking and pausing playback of video

### To Reproduce

1. Play back any stream where m3u8 event playlist doesn't have EXT-X-ENDLIST tag at the end. [Redacted Example](https://paste.kodi.tv/etodugujut)
2. Note unable to pause or seek video
3.

### Debuglog

The debuglog can be found here:

[Playback Debug Log](https://paste.kodi.tv/ayumujugiy.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Tested Kodi 18.8 and latest git version of Kodi 19 on Ubuntu Linux. Same behaviour seen on OSMC Kodi 18.7 on Raspberry PI

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04
 - Kodi version: Build 19.0-ALPHA1 (18.9.701) / Git: 20200910-caa2023f09

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
Please don't cut logs. 

Have you tried inputstream.adaptive?

**Comment by djbloc** [comment]
Yes, I tried on Kodi 18. To initiate inputstream.adaptive from a file I used .strm. I don't know of another way to use inputstream.adaptive using files

Using inputstream.adaptive enables seeking and pausing video playback but there are at least a couple of compromises:
- By using .strm file, the resume functionality in Kodi doesn't work
- Video codec support appears limited. It works with h.264/aac but not mpeg2/aac (in the UK, recording TV broadcasts over DVB-T use mixture of both types). It seemingly doesn't have ffmpeg level of flexibility for different codec types
- Subtitles (dvb_subtitles) that are within the stream are not displayed.

**Comment by sarbes** [comment]
- The HLS implementation of FFmpeg is pretty basic, so you have to use IA if you want more features. Improving FFmpeg it is out of the scope for this project (in general). IA can also be invoked by Python/Binary Add-ons by adding the related properties.
- IA still uses FFmpeg for decoding, nothing changed in this regard.
- Subtitles in ts streams are not supported as far as I know. In general, sub decoding is the job of the frontend add-on or the backend.

I'm going to close this issue, as your initial problem is solved by using IA. You are welcome to open separate issues for IA, but make sure you are adding an uncut log along with playlist examples and a proper description. If you have questions about IA or you're unsure about certain aspects of content playback, the forum is the better place to start.
