### ISSUE TITLE
file manager becomes unusable when 

### ISSUE THREAD

**Issue by mvhulten** [xbmc/xbmc#18426]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I'm in the filemanager in 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Give it another try ;)

In case you will edit this issue and fill it with any usefull information, I'll happily re-open it.
