### ISSUE TITLE
file manager becomes unusable when current directory is removed

### ISSUE THREAD

**Issue by mvhulten** [xbmc/xbmc#18427]
### Describe the bug

* I create a directory (say, in a terminal, `mkdir some-dir`).
* Then in Kodi I open the file manager and go into this directory.
* I delete the directory (in the terminal again, `rmdir some-dir`).
* I switch to Kodi, go out of the file manager and into the filemanager again, and I get the message that the directory is not available.

This is all fine, however, this panel of Kodi's file manager becomes unusable.  In case it is the left panel, the one that the file manager starts in, the only way to get back to using Kodi's file manager is to restart Kodi.

## Expected Behavior

I expected to be able to keep on using Kodi's file manager, for instance by traversing to `..` or `/`.

## Actual Behavior

In the current panel of the file manager I keep on getting the message `Path not found or invalid`, without a possibility to go into a different (existing) directory.

## Possible Fix

I'm not sure.  Maybe, when this happens, the file manager travers back one directory automatically, or at least it could give back control such that the user can do this.

### To Reproduce

1. Create a directory: `mkdir /home/kodi/Videos/test/`.
2. In Kodi, open the file manager and go into this directory.
3. Delete the directory again: `rmdir /home/kodi/Videos/test/`.
4. Switch to Kodi where you quit the file manager and start it again.

### Debuglog

The debuglog can be found [here](http://paste.debian.net/1163923/).
Central excerpt:

    ERROR: GetDirectory - Error getting /home/kodi/Videos/test/

### Your Environment
Used Operating system:

 - [X] GNU/Linux

 - Operating system version/name: GNU Guix 1.1.0
 - Kodi version: 18.8.0

**Comment by ronie** [comment]
this has been fixed in kodi 19: https://github.com/xbmc/xbmc/pull/18121
