### ISSUE TITLE
Missing API to set external .srt file from URL for the running video through json-RPC interface

### ISSUE THREAD

**Issue by pespin** [xbmc/xbmc#18443]
As of current kodi (923c3549c8a4c5cc3e7224ac450a1d50586f94f1, 19.0a1), there is no way to set an external .srt file from eg. a http URL using the json RPC interface.

There's currently only support for Play.SetSubtitle API as seen in xbmc/interfaces/json-rpc/schema/methods.json, which as  far as I can tell expects the subtitles to be already loaded (internal subtitles inside the media file?).

I see the IPlayer internal interface has a AddSubtitle(string) API (xbmc/cores/VideoPlayer/VideoPlayer.cpp), which I think should be the one to use, but it is not exported on the json-rpc external interace. So I propose making it available in the json-rpc.

Use for this:

1. I have my video files on my laptop's web server, available through home's local network to kodi running on rpi attached to the TV, together with .srt file in the same(web) directory.
2. I usually use castkodi firefox addon [1] to submit http urls from my webserver for kodi to play using json-rpc.

However there's currently no way to pass related .srt file to it using the castkodi UI. I'd like to implement that but there's no RPC API to do it.

[1] https://addons.mozilla.org/en-US/firefox/addon/castkodi/

**Comment by DaVukovic** [comment]
Thanks for the report. As said at IRC, this is a feature request and should be posted at the forums at the specific subforum: 

https://forum.kodi.tv/forumdisplay.php?fid=9

This section is for bugreports only. Sorry
