### ISSUE TITLE
Feature: Set different subtitle colors for SDR and for HDR content

### ISSUE THREAD

**Issue by kristofferR** [xbmc/xbmc#18449]
Kodi 19 [adds a feature to set the subtitles to Dark Grey](https://github.com/xbmc/xbmc/pull/16222), fit for HDR content. However, it is quite annoying currently, as it leaves the subtitles way too dark when watching SDR content. 

Kodi 19 should add a feature to select different subtitle colors for SDR and HDR content, so the subtitles are appropriately bright while watching either SDR or HDR. 

Currently you have to manually change the settings every single time you switch between watching SDR and HDR, which isn't really a viable option in practice.

**Comment by kristofferR** [comment]
I don't the template is applicable in this instance since it's not a bug report, please remove the "Ignored rules" label if you could be so kind.

**Comment by chewitt** [comment]
Feature requests should be submittted via that section in the Kodi forums (hence the template here is for bugs)
