### ISSUE TITLE
Passthrough audio out-of-sync after unpausing or seeking

### ISSUE THREAD

**Issue by elonliu** [xbmc/xbmc#18440]
### Describe the bug
Here is a clear and concise description of what the problem is:

During the play of a movie with multi-channel sound passthrough, if I pause the video, or seek forward/backward, the sound will be slightly out-of-sync when resuming. The audio will be lagged perhaps 200ms or so, not much, but enough to be noticed, especially when the actors are talking.

In these scenarios, things are good though:
1. Stop the video, and play it. Starting from either the beginning or the last played position is fine, until I pause or seek.
2. Play a movie with passthrough disabled, or a stereo movie, in such cases pausing and seeking will be fine

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Audio is expected to be synchronized no matter I pause it or seek to an arbitrary position.

## Actual Behavior

In prementioned cases, audio is slightly lagged after unpausing or seeking.

### To Reproduce

1. Enable audio passthrough
2. Play a movie with multi-channel sound
3. Pause & resume, or seek to an arbitrary position

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/govuqeqeko

In the log, between the switching of DEBUG level, I did these things:
1. Open a movie and resume last played position: audio is ok
2. Pause and resume: audio is lagged
3. Seek randomly: audio is lagged

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 9.0.0 API Level 28 (Kernel: Linux 4.9.125) (inside my Sony TV)
 - Kodi version: v18.8

Some of my settings I think might be related:
- Player
  - Enable hardware accl. MediaCodec (surface): On
  - Enable hardware accl. MediaCodec: On
- Audio
  - Number of channels: 2.0
  - Output configuration: Optimized
  - Enable Passthrough: On
  - AC3 capable receiver: On
    - Enable AC3 transcoding: On
  - EAC3/DTS/DTS-HD capable receiver: Off

Hardware:
- TV: Sony BRAVIA KD-65X9000H
- Speaker: Sonos Playbase system
The two are connected through optical SPDIF

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Please backup your data and retry with a v19 nightly build.

Leia 18.8 implements an ancient sync method for audio data, which was later replaced by google. This already exists in kodi v19.

For the log:
Please enable Audio component logging additionally and directly reproduce afterwards and then immediately post the log. Please turn off that component logging afterwards - I spam every single delay call I get in there and the logfile will overflow that way.

**Comment by elonliu** [comment]
Thanks for the reply @fritsch 
I tried kodi v19 nightly build, and the problem is gone. Seems it has been fixed in the new version. I think this issue can be closed.
