### ISSUE TITLE
Occasional Kodi lockup on Stop button press

### ISSUE THREAD

**Issue by whzzz28** [xbmc/xbmc#18452]
### Describe the bug
Sometimes when pressing the Stop button when playing a media file (media can be in a state of play, or pause), Kodi locks up and needs to be terminated and reloaded.
This is hard to reproduce on command. One video file that causes a lockup may not cause a lockup the next time you play it.
Some times you will get the lockup on every video. Other times you can go hours without an issue.

When the issue does occur the status bar remains (with the Play/Pause/Stop buttons on it), the video goes black, and there is no audio. You can sometimes move around the status bar with the remote, but if you click on any button, it locks completely.
If you go back to the home screen on Android TV, then click Kodi again to open it, you are presented with a grey-scale gradient. If you press a button and then wait 5-10 seconds, Android will pop up advising the application is not responding, and you can close it. You cant also close it manually via Settings -> Apps -> Kodi -> terminate.
Kodi reloads fine after this.

## Expected Behavior
When the stop button is pressed, Kodi should not lock up and should return the user to the view they were on previously.

## Actual Behavior
Kodi locks up (sometimes) when the Stop button is pressed and requires a termination and reload before Kodi becomes usable again.

### To Reproduce
This is hard/impossible to reproduce at will, but on average for around 3 hours of video playback, it will occur once. 
When the issue occurs, it is fairly obvious as you are not returned to the previous view. 

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/eluyigimaf.kodi

Note: That is only for the date of the 22nd. If you want the full log, you will need to get it here. paste.kodi.tv would not accept the full log (too big). If you want me to upload it somewhere else, let me know.
https://drive.google.com/file/d/1qrizYSIfEJ9QsqZjuvlI9qN9D-um3uUv/view

## Additional context or screenshots (if appropriate)
Things I have tried:

- Tried to just let it run, see if it closes the video/works eventually. 30mins later, nope.
- Replaced the Nvidia shield (was 2015 model) with the Nvidia Shield Pro (2019) model. The issue persists. This was with a new profile etc, nothing was carried over from the old shield.
- I run Kodi in its base form, with only one addon (TVDB information provider). I tried without any addons, but the issue persists.
- Disabled MediaCodec to see if its a hardware decoding issue. The issue persists with software decoding.
- Turned off adaptive display sync options. The issue persists without any adaptive display options enabled.
- Replaced the ethernet cable to the Shield.
- Replaced the NAS housing the media, to a different brand (from Qnap -> Synology)
- Raised ticket with Qnap as I believed it was an issue with the QNAP NAS. This was raised on 25th of July 2019. So I first saw issues around this time in Kodi, maybe a month or so before. I spent 3 months of back/forwads with QNAP to no success.
- Bypassed the network switches, direct connection from Shield into NAS. The issue persists.
- Tried various different media types; xvid, h264, etc. Media format does not appear to play a role.
- Issue occurs regardless of how you start the media. IE, start from the TV Series window vs browsing the network share (viewing the raw folder).
- Checked samba logs on the NAS in case of some streaming/network issue, but nothing.
- Mentioning just in case, but sometimes i notice when stopping a video, there can be a significant delay on the video list screen appearing. Say 3-5 seconds. Random when this occurs. Not often. I often think it may be this lockup problem, but it does appear.

This issue has been ongoing for quite a while (a year atleast). I originally thought it was a NAS problem, as I just happened to replace my NAS roughly around the time the issues started. The NAS was brought online around May 9th, 2019.
But I do not believe there is related to hardware given what I have tried above. Instead I believe there may have been a software change that caused what I am seeing. Sadly I do not remember what version I was using prior to the issues starting. 
Given the release dates, version 18.2 may be where the issues started. 

I also note that something that looks the same/similar was raised in December 2019:
https://github.com/xbmc/xbmc/issues/17061

My next test will be to try downgrading to 18.0/18.1 and see how it goes.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android (TV) 9.0.0
 - Kodi version: 18.8.8.0 (Git: 20200727-45686bddb1) (Latest available on play store)

- Media source: Samba shares
- Media source hardware: Synology NAS (two NAS, media from both cause the same issue)

**Comment by kizza42** [comment]
Just want to pipe in and say I have also been experiencing this for some time. Exactly the same symptoms.

**Comment by whzzz28** [comment]
Downgraded to 17.6. The issues have disappeared. So whatever it is appeared in version 18.x somewhere.

For now i guess ill stay on 17.6.

PS: the latest release still has the same issues.

**Comment by fonic** [comment]
I experienced this very same issue with my _NVIDIA Shield TV Pro (2019)_, accessing media via _Samba shares_ on a PC running Gentoo Linux.

**The issue seems to be gone since I upgraded to Kodi 19 on the NVIDIA Shield.**

My guess is this has/had something to do with Samba, as this seems to be the common denominator here.
