### ISSUE TITLE
Kodi 19 crashes when using Simple IPTV client with Inputsteam FFmpeg Direct

### ISSUE THREAD

**Issue by berkhornet** [xbmc/xbmc#18457]
### Describe the bug
Here is a clear and concise description of what the problem is:

Using Kodi 19 nightly from KodiSetup-20200924-39d2a7bc-master-x64.exe (on Windows 10 version 2004), a clean install with Simple IPTV client version 6.3.1 and Inputsteam FFmpeg Direct version 1.15.2. Selecting any channel from the EPG causes Kodi to crash. If Inputstream FFmpeg Direct is disabled, the channel streams ok.

This problem does not occur when using Kodi 19 Alpha 1.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The channel should play ok (as it does if Inputstream FFmpeg Direct is disabled)

## Actual Behavior

Kodi crashes.

[kodi_stacktrace-19.0-ALPHA1 Git_20200924-39d2a7bca2-20200925-095941.txt](https://github.com/xbmc/xbmc/files/5281815/kodi_stacktrace-19.0-ALPHA1.Git_20200924-39d2a7bca2-20200925-095941.txt)

## Possible Fix

The bug occurs using an HPTC connected to a TV. I have tested on a laptop with the same software versions etc. and the bug does NOT occur. As mentioned above the problem does not occur using Kodi 19 Alpha 1.

So the problem seems to be limited to a code change since Alpha 1 and when using an external monitor.

### To Reproduce

1. Install Kodi
2. Install Simple IPTV client and Inputstream FFmpeg Direct
3. Configure Simple IPTV client
4. Select channel

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

None provided

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Cannot use Timeshift functionality in Simple IPTV client

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 version 2004
 - Kodi version: KodiSetup-20200924-39d2a7bc-master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by berkhornet** [comment]
Here is the crash lug (zipped)
[kodi_crashlog-19.0-ALPHA1 Git_20200924-39d2a7bca2-20200925-095941.zip](https://github.com/xbmc/xbmc/files/5281980/kodi_crashlog-19.0-ALPHA1.Git_20200924-39d2a7bca2-20200925-095941.zip)

**Comment by SerhiyRomanov** [comment]
I get the same error on Ubuntu 20.04 with Kodi (19.0-ALPHA1 (18.9.701) Git:20200925-39d2a7bca2)

Here is crash log 
[kodi_crashlog-20200925_140125.log](https://github.com/xbmc/xbmc/files/5282338/kodi_crashlog-20200925_140125.log)

**Comment by phunkyfish** [comment]
Does it crash with any channel using ffmpegdirect?

**Comment by berkhornet** [comment]
Hi

Yes, any channel i try causes Kodi to crash when ffmpegdirect is enabled.

Regards Mick

________________________________

**Comment by phunkyfish** [comment]
Hmmm, it works for me which is strange. @SerhiyRomanov can you send me a test stream via PM? Once I can repro it should be easy to fix.

**Comment by phunkyfish** [comment]
Oh, no need. I know the issue. Please use the Alpha until the end of next week. I'll have it fixed by then.

**Comment by berkhornet** [comment]
Many thanks for your help.

Regards Mick

________________________________

**Comment by berkhornet** [comment]
should have added that I'm able to test a fix if that helps

**Comment by phunkyfish** [comment]
Cool, i will ping you by the end of the week with links to testbuilds 😉

**Comment by phunkyfish** [comment]
I was able to test locally so next release of the addons should be working again.

**Comment by berkhornet** [comment]
Many thanks for the update. Will it be changes to both IPTV Simple Client and Inputstream.fgmpegdirect?

Regards Mick

________________________________

**Comment by phunkyfish** [comment]
Yes, both v1.15.4 of ffmpegdirect and 6.3.2 of iptvsimple

**Comment by berkhornet** [comment]
I’ve updated both addons and all is working well now. Many thanks for your help and prompt fix.

**Comment by SerhiyRomanov** [comment]
@phunkyfish 
2020-10-02 13:04:53.539 T:7917     INFO <general>: CAddonMgr::FindAddons: pvr.iptvsimple v6.3.2 installed
2020-10-02 13:04:53.537 T:7917     INFO <general>: CAddonMgr::FindAddons: inputstream.ffmpegdirect v1.15.4 installed

But still, crash(
[kodi_crashlog-20201002_130508.log](https://github.com/xbmc/xbmc/files/5317453/kodi_crashlog-20201002_130508.log)

**Comment by phunkyfish** [comment]
Hmmm, I have tested locally here and it appears ok. Can you run it in gdb and get a backtrace for the crash?

**Comment by SerhiyRomanov** [comment]
@phunkyfish I hope this help, else let me know how to do this correctly

[crash.txt](https://github.com/xbmc/xbmc/files/5317712/crash.txt)
![image](https://user-images.githubusercontent.com/11770485/94919913-f3c47280-04bd-11eb-9f6c-d19a48a7f5f3.png)

**Comment by phunkyfish** [comment]
That's really strange, I have no idea what that error means unfortunately.

**Comment by SerhiyRomanov** [comment]
Yeah, it appears fixed in today's nightly build!
