### ISSUE TITLE
Kodi 18.8 crashes on iOS after “First Run” message

### ISSUE THREAD

**Issue by JanX2** [xbmc/xbmc#18473]
## Bug report
When the Kodi app is launched on iOS/iPadOS and there is no previous launch registered in `userdata`, Kodi 18.8 crashes after acknowledging the “First Run” message.

## Expected Behavior
Kodi should continue onward without a crash.

## Actual Behavior
Crash.

## Possible Fix
There probably is an issue with the first-run code that hasn’t been debugged on iOS, because developers usually have their old settings files.

### To Reproduce
1. Delete/move aside `Kodi/userdata`
2. Launch app 
3. Tap “OK” button

### Debuglog
The debuglog can be found here:
https://p.nnev.de/9559

### Your Environment
Used Operating system:
 - [ ] Android
 - [x] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: iOS 13.5, iPadOS 13.6
 - Kodi version: 18.8

**Comment by sy6sy2** [comment]
Hi, how do you sign/install Kodi on your device?

**Comment by JanX2** [comment]
@sy6sy2 
It’s a bit complicated: 

1. Install AltStore
2. Convert .deb to .ipa
3. Find a way to transfer the .ipa to the device
4. Find a way to send the .ipa to the AltStore app

I use FileBrowser for 3. and 4. There may be other/better ways, but this is what worked for me.

**Comment by sy6sy2** [comment]
AltStore does not support Kodi yet (because Kodi uses frameworks that AltStore does not sign yet) (see https://github.com/rileytestut/AltStore/issues/159).

If you device is not jailbroken you need to use iOS App Signer (see https://kodi.wiki/view/HOW-TO:Install_Kodi_for_iOS).

**Comment by JanX2** [comment]
@sy6sy2 
Funny thing is that Kodi works perfectly fine, if I just copy my `Kodi/userdata` from an old install. This way I skipping the “First Run” message and have been using Kodi for weeks. I just wanted to report the crash. The installation method appears to work fine and isn’t at issue here!

**Comment by sy6sy2** [comment]
I am unable to produce the crash after "First run" message that you describe here :-/
@kambala-decapitator, did you notice something like that?

Concerning your install method ; is your device jailbroken?

**Comment by gqbre** [comment]
> @sy6sy2
> Funny thing is that Kodi works perfectly fine, if I just copy my `Kodi/userdata` from an old install. This way I skipping the “First Run” message and have been using Kodi for weeks. I just wanted to report the crash. The installation method appears to work fine and isn’t at issue here!

I am curious how yours works about "copy Kodi/userdata"

**Comment by gqbre** [comment]
> @sy6sy2
> Funny thing is that Kodi works perfectly fine, if I just copy my `Kodi/userdata` from an old install. This way I skipping the “First Run” message and have been using Kodi for weeks. I just wanted to report the crash. The installation method appears to work fine and isn’t at issue here!

I am curious how yours works about "copy Kodi/userdata" @JanX2

**Comment by JanX2** [comment]
@gqbre I use iMazing to copy `Kodi/userdata` to the side loaded app on my iPad.
