### ISSUE TITLE
CRT shaders in the vide player, for SD-Video, DVD, Digital TV etc

### ISSUE THREAD

**Issue by stuaxo** [xbmc/xbmc#18478]
Apologies if this is the wrong place for feature requests, feel free to close this if so.

It would be great if KODI supported CRT shaders in the video player.

SD-Digital TV and DVDs could potentially benefit.

The ZFAST shaders seem interesting, they're fairly good and performant on the Raspberry Pi.

**Comment by fuzzard** [comment]
The bots right. GitHub is used for issue tracking only.

Feature requests can be made on the forums.
https://forum.kodi.tv/forumdisplay.php?fid=9

**Comment by stuaxo** [comment]
Thanks for pointing me in the right direction.
