### ISSUE TITLE
KODI crashes on loading EPG file every 2 hours

### ISSUE THREAD

**Issue by eloscuro** [xbmc/xbmc#18477]
### Describe the bug

I am running KODI on a Raspberri Pi 2 / OSMC.

Every 2 hours KODI shows a blue sad face and reloads itself. The OS is not rebooted.

I found in logs some clues leading to something about EPG updating and tried to turn off EPG updating completely - that helped, KODI worked for a week without restarting.

I also tried to download that remote EPG file and put it locally - it did not help.

Strange thing is that the same EPG file loads perfectly on KODI startup.

### Debuglog

The debuglog can be found here:

https://www.dropbox.com/s/mvi0gi2meil96sy/kodi.old.log?dl=0
https://www.dropbox.com/s/6fnocl2jl1lngh7/kodi2.old.log?dl=0

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux osmc 4.19.122-1-osmc
 - Kodi version: 18.7

**Comment by phunkyfish** [comment]
You are running OSMC. Can you reproduce using a kodi build and supply that debug log?

If not you should post on the OSMC forum.

**Comment by eloscuro** [comment]
Thank you for your answer.
No, I did not try that on a standalone KODI.
Will post that on the OSMC forum, thanks again!
