### ISSUE TITLE
Cannot build Android on macOS Catalina: "undefined reference to `fstrcmp'"

### ISSUE THREAD

**Issue by LucasVanDongen** [xbmc/xbmc#18475]
### Describe the bug
I have managed to get as far as the last three steps before generating the APK, following [these instructions](https://github.com/xbmc/xbmc/blob/master/docs/README.Android.md). In my case they look as follows:
```
make -C tools/depends/target/cmakebuildsys BUILD_DIR=/Volumes/android-dev/kodi-build 
cd /Volumes/android-dev/kodi/build
make -j$(getconf _NPROCESSORS_ONLN)
```

After running `make -j$(getconf _NPROCESSORS_ONLN)` the build errors out as follows:
```
[ 98%] Linking CXX shared library libkodi.so
build/utils/utils.a(StringUtils.cpp.o): In function `StringUtils::CompareFuzzy(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)':
/Volumes/android-dev/kodi/xbmc/utils/StringUtils.cpp:1678: undefined reference to `fstrcmp'
build/addons/addons.a(Scraper.cpp.o): In function `ADDON::CScraper::FindMovie(XFILE::CCurlFile&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, int, bool)':
/Volumes/android-dev/kodi/xbmc/addons/Scraper.cpp:975: undefined reference to `fstrcmp'
build/xbmc/xbmc.a(Util.cpp.o): In function `CUtil::AlbumRelevance(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)':
/Volumes/android-dev/kodi/xbmc/Util.cpp:1410: undefined reference to `fstrcmp'
/Volumes/android-dev/kodi/xbmc/Util.cpp:1418: undefined reference to `fstrcmp'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libkodi.so] Error 1
make[1]: *** [CMakeFiles/kodi.dir/all] Error 2
make: *** [all] Error 2
```

## Expected Behavior
Kodi builds without error and I can create the APK.

## Actual Behavior
Several files cannot find fstrcmp

## Possible Fix
Unknown

### To Reproduce
1. Follow the build instructions for macOS

### Debuglog
[Here is the full output of the command](https://pastebin.com/LW7G0pGd)

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I had several issues where just following the steps + macOS extra steps simply didn't work. It still relied on an outdated Java version and I had to install several tools using brew. For example:

```
brew install gcc
brew install libiconv
brew cask install homebrew/cask-versions/adoptopenjdk8    
```

Unfortunately I didn't document every exception to the instructions I've did but there were numerous occasions where I already had to intervene besides above mentioned.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS Catalina 10.15.6 (19G2021)
 - Kodi version: 18.9.701

**Comment by LucasVanDongen** [comment]
I followed the template, perhaps I renamed Debuglog since it wasn't relevant to build log.

**Comment by fuzzard** [comment]
I'll be honest, don't bother. I spent ages trying to get a OSX native build Env running. Just use a Linux VM imo

**Comment by LucasVanDongen** [comment]
> I'll be honest, don't bother. I spent ages trying to get a OSX native build Env running. Just use a Linux VM imo

I think that if the README would have told me that a few days ago I would have gone that route. However it looks like I'm one bump away of getting it to work, it's literally happening at 99% of the last step.

Already trying to get VirtualBox running with Ubuntu 16.04 but for some reason none of the images seem to boot :/
Really no luck with this one.

**Comment by hugbug** [comment]
I had the same issue but was able to fix it manually.

The failed command is a linker command, which is saved in "kodi/build/CMakeFiles/kodi.dir/link.txt". This is a very long command (more than 20000 characters), which among other parameters lists all the required libraries. One of them is `libfstrcmp` containing function `fstrcmp`.

Despite the fact the required library is properly passed to the linker it is unable to find the function `fstrcmp` nonetheless.

In my experience linkers can be fussy about the order of parameters. More than once I could fix failed linker commands by reordering parameters. That did work in that case too.

How to fix (manually)
---------------------
Open the file `kodi/build/CMakeFiles/kodi.dir/link.txt` in a text editor. Search for `libfstrcmp`. Copy the whole parameter (something like `/Volumes/kodi-dev/xbmc-depends/aarch64-linux-android-21-debug/lib/libfstrcmp.a`) to the clipboard. Then paste the parameter somewhere near the beginning of the command. I did this just after the parameter `--whole-archive`. You don't have to remove the previous occurrence of the parameter; linker doesn't care if the same library is listed more than once. Do not save the modified file `link.txt` (this may cause a rebuild).

Then copy the whole command (the whole edited file) to the clipboard and paste it into your terminal window where the kodi was building. Run the command. It should work properly now and you'll have `libkodi.so` in your `kodi/build` directory.

After that run `make` again. It will continue.

**Comment by phunkyfish** [comment]
Nice, now if only we could fix it without the manual step.

**Comment by LucasVanDongen** [comment]
Thank you for your answer and hopefully this will help somebody in the same position as me. Regretfully the project already ended but I managed to work around the issue.
