### ISSUE TITLE
X11 (multiple virtual desktop) kodi is changing virtual desktop after the monitor turn off

### ISSUE THREAD

**Issue by Mannitou** [xbmc/xbmc#18483]
### Describe the bug
Here is a clear and concise description of what the problem is:
It is strange but after I turn off my monitor, kodi will be alway in front of other applicatication when I turn my monitor on.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Kodi should not move of virtual desktop from it owns.

## Actual Behavior
Kodi change to last virual desktop used before the turn off.

### To Reproduce
1. Launch kodi on virtual screen "2"
2. Put kodi in full screen mode
3. Change to another virtual desktop like "1"
4. Turn off the monitor or remove the HDMI cable 
5. Turn on the monitor or plug the HDMI cable
6. Kodi will be on virtual desktop "1". Kodi will not stay on the virtual desktop "2". I don't know why?

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: SparkyLinux (debian)
 - Kodi version: 18.7 Git:202000525-nogitfound
- Installation package: flatpak
- kernel: 5.8.0-2
- WindowsManager Xfce
- I have only 1 monitor.

**Comment by Mannitou** [comment]
please reclasify this like a feature. https://forum.kodi.tv/showthread.php?tid=357418

**Comment by DaVukovic** [comment]
ok, I guess if this is more a feature request rather than a bug report, we can close this.
