### ISSUE TITLE
Error with CPythonInvoker(8, /storage/.kodi/addons/service.system.docker/default.py

### ISSUE THREAD

**Issue by heitbaum** [xbmc/xbmc#18501]
### Describe the bug

The log file is showing errors with the default.py file on startup of the service.system.docker in nightly-20201002-0bfa8aa
I have captured the from the kodi.log in - http://ix.io/2zzj

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No errors expected on the startup of the service.system.docker addon

## Actual Behavior

2020-10-03 16:56:01.097 T:1663    ERROR <general>: "is" with a literal. Did you mean "=="?

## Possible Fix

In the http://ix.io/2zzj a DIFF is attached.
I have started with the proposed DIFF // though not sure if it behaves as designed now.

### To Reproduce

Use this version of docker addon: service.system.docker v9.80.6.128 installed
Use libreelec nightly-20201002-0bfa8aa

### Debuglog

NA - code issue - http://ix.io/2zzj
Full kodi.log - for versioning comparisons: http://ix.io/2zzm

### Screenshots 
Here are some links or screenshots to help explain the problem:

NA

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

NA

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
LibreElec nightly-20201002-0bfa8aa
https://test.libreelec.tv/

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
This isnt a Kodi issue as far as i can see in those logs.

Just looks like the service addon needs to be updated/altered to support whatever python version libreelec is deploying currently.

Probably best to post on libreelec issue tracker, or possibly just their forums to start with.

Python BPO that introduced the behaviour https://bugs.python.org/issue34850

**Comment by heitbaum** [comment]
Thanks @fuzzard  - I have proposed the patch for libreelec. Thanks for sending me in the right direction.
