### ISSUE TITLE
Files with names starting with "epXX" not recognized as episodes.

### ISSUE THREAD

**Issue by eduarrrd** [xbmc/xbmc#18505]
### Describe the bug

Default `m_tvshowEnumRegExps` does not match episodes starting with `ep01 [...]`.

https://kodi.wiki/view/Naming_video_files/TV_shows#Single_Episodes suggests that this is NOT intended.

code: https://github.com/xbmc/xbmc/blob/ddcbadf2c0f631cddd58ea36d926beebc27dc363/xbmc/settings/AdvancedSettings.cpp#L235

## Expected Behavior

It should match.

## Actual Behavior

It doesn't match.

## Possible Fix

1. Make the first character class an optional.
2. Have the first character class match beginning-of-string as well.

### To Reproduce

1. Name an episode `ep01 - title.mkv` => doesn't match.
2. Name an episode ` ep01 - title.mkv` (ASCII space before the `e`) =>  matches.

**Comment by KarellenX** [comment]
Please provide a debug log as required when reporting a bug. Full log only, no snippets.

**Comment by eduarrrd** [comment]
The log contains information I consider sensitive. 

If you're disagreeing about  https://github.com/xbmc/xbmc/blob/cccae01fd5a8f08b661c4fde5663c02a629f975e/xbmc/settings/AdvancedSettings.cpp#L234-L235 (current master revision) which, un-c-escaped is

```
[\._ -]()e(?:p[ ._-]?)?([0-9]+(?:(?:[a-i]|\.[1-9])(?![0-9]))?)([^\\/]*)$
```

 not matching the string `" ep01 - title.mkv"` (without the quotation marks) because it requires a `.`, `_`, ` `, or `-` before the `e`, I'm afraid there's nothing I can do.

**Comment by KarellenX** [comment]
If you already have a fix, then lets bypass this issue report and PR the fix, thanks.

**Comment by enen92** [comment]
I agree this should be fixed as the wiki states:

Spaces, periods, or underscores **may be used to separate words** in the folder and file names, but shouldn't be mixed in the same name. The regex is not case-sensitive and either uppercase or lowercase may be used. The examples on this page use uppercase.

So either `ep01 - title.mkv` or ` ep01 - title.mkv` should match regardless of the starting space char
