### ISSUE TITLE
Extra colon in finishing time's Hebrew translation

### ISSUE THREAD

**Issue by haggaie** [xbmc/xbmc#18512]
### Describe the bug
Here is a clear and concise description of what the problem is:

The string 31080 ("Ends at") is shown in the skin with a colon immediately afterwards and then the remaining time. In Hebrew, the translation for it is "מסתיים ב-", which ends with a dash, and doesn't need a colon.

## Expected Behavior
I think that either the colon should be removed (perhaps by putting it inside the localized string) or the Hebrew translation should be rephrased.

## Actual Behavior
The remaining time is presented as:
מסתיים ב-: 13:45

With a redundant colon.

## Possible Fix
I'll be happy to send a patch, but I'd like to know the preferred solution.

### To Reproduce
1. Play a video on a system with a Hebrew interface
2. Show the OSD
3. See the remaining time translation

### Debuglog
I don't think the debug log is needed here.

### Screenshots
![Inkedscreenshot000_LI](https://user-images.githubusercontent.com/35070/95010330-11661900-0631-11eb-911c-b19fdee94656.jpg)

## Additional context or screenshots (if appropriate)
The screenshot is from an Ubuntu VM with Kodi v18.6.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

I used LibreELEC 9.2.4 on Raspberry Pi with Kodi v18.8.

*EDITED to match template and add screenshot*

**Comment by haggaie** [comment]
I tried to fix the issue so it will match the template and added a screenshot.

**Comment by DaVukovic** [comment]
Thanks for your report.

Translations are done at Transifex. So there's no need to send a PR as the solution I would suggest is to change it at the Hebrew language translation for Estuary as otherwise a bunch of language files have to be changed at Transifex which would over-complicate things if the colon is only redundant and not wrong.

**Comment by haggaie** [comment]
Okay, I'll try changing the Hebrew translation through Transifex. Thanks!

**Comment by DaVukovic** [comment]
@haggaie 

I just did the changes. Is this correct now?

![image](https://user-images.githubusercontent.com/7235787/95301661-2df89000-0881-11eb-9740-a018afca4f46.png)

**Comment by haggaie** [comment]
I think a better translation that is compatible with the colon would be:
שעת סיום

Which means literally "ending hour". The translation of the "at" preposition as "ב-" typically requires a dash in Hebrew as it is a prefix and not a word on its own.

**Comment by DaVukovic** [comment]
But the time shown is not an "hour" only. It's an exact time where something, which starts at some time before, ends. 

I'm fine if we ignore what is "typically" for a specific language. But if something translates to "Ending hour", this is semantically wrong as we are not talking about an "hour". And, tbh, we won't change the skin and >75 languages (to add the colon at the translation if we remove it from the skin) just because something is "typically incorrect" ;)

**Comment by haggaie** [comment]
The phrase שעת סיום can also mean "ending time". I should probably have used that in my previous comment. 

I understand changing the skin and all the languages is hard - I wouldn't want to create extra work for anyone :-)
When I suggested that solution I assumed I would be able to find a way to automate the work somehow.

Regarding the current translation being "typically incorrect", I didn't mean that it can be seen as correct. I meant that the prefix can be used either with a dash (when it comes before a number or a time in this instance), or without a dash, when it is used as part of the next word. Again, sorry for the confusion :-)

**Comment by gade01** [comment]
@haggaie Any news regarding this issue?

Translations are now moved to Weblate: 
https://kodi.weblate.cloud/

If you haven't done so already, feel free to sign up to translate all parts of Kodi.
https://forum.kodi.tv/showthread.php?tid=363132

**Comment by haggaie** [comment]
The translation in the 19.3 results in:

מסתיים ב:

Which is better than before as it doesn't have both punctuation marks, but it still looks wrong.

I'll try suggesting another translation on Weblate.

**Comment by gade01** [comment]
@haggaie 
I just accepted you suggestion at Weblate.
Will this fix the issue?

**Comment by gade01** [comment]
Thanks, sounds great.
Closing this issue.
