### ISSUE TITLE
Kodi 19 - Log spam on pausing video

### ISSUE THREAD

**Issue by Gujal00** [xbmc/xbmc#18535]
### Describe the bug
Here is a clear and concise description of what the problem is:

While playing a Video from local drive  in Windows, if video is paused by pressing space, immediately the log starts filling with the following message at rate of 2 messages per second.
`WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer`
So if I pause the video for 5 minutes to go do something, the log gets 600 of these messages.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Pausing a Video should not cause LOG file to fillup

## Actual Behavior

```
2020-10-07 18:02:18.417 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-10-07 18:02:18.918 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-10-07 18:02:19.419 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-10-07 18:02:19.920 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-10-07 18:02:20.421 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-10-07 18:02:20.922 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
```

### To Reproduce

1. play any video from kodi library, files in local drive
2. pause the video for 30 seconds
3. log has 60 messages

### Debuglog

The debuglog can be found here:
[Debug Log](http://paste.kodi.tv/luqejuhaxu)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Not Applicable

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Not Applicable

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Windows 10 2004
 - Kodi version:
Nightly 19.0-ALPHA2 (18.9.702) Git:20201007-f1074bd420
(Tested from Alpha1 snapshot to 7 OCT 2020 nightly)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Gujal00** [comment]
This problem still exists in Beta2, anyone looking at this?

**Comment by enen92** [comment]
@Montellese maybe something like https://github.com/gabime/spdlog/issues/696 could be implemented to avoid this and similar issues?

**Comment by Gujal00** [comment]
@enen92 This is not about repeated messages, the issue here is pausing a video should not cause any "Warning" messages to start with

**Comment by Montellese** [comment]
@enen92 while your idea would mitigate the issue and will restore the previous logging behaviour I have to agree with @Gujal00.

But in case you want to integrate the `dup_filter_sink` anyway there are two places it can go:
* if it should apply only to the logs being written to the log file it should be placed "around" `CLog::m_fileSink` as a `dup_filter_sink_mt`.
* if it should apply to all log outputs (including platform specific debug logs) we could change the initialization of `CLog::m_sinks` from `m_sinks(std::make_shared<spdlog::sinks::dist_sink_mt>())` to something like `m_sinks(std::make_shared<spdlog::sinks::dup_filter_sink_mt>(std::chrono::seconds(10)))`.

**Comment by enen92** [comment]
Thanks for the tips Montellese, and glad you're feeling well again :)
My comment was not an attempt to swipe this or similar issues under the bed but to know exactly if (and where) such a "feature" could be implemented. There are certainly legit cases for repeated log messages in a short period of time and we have a lot of bug reports regarding the log size. Filtering similar messages could at least help with that.
Thanks

**Comment by Gujal00** [comment]
Problem still persisting on the RC1 release.
Would be great if someone looks at this before final release

**Comment by Montellese** [comment]
Please see #19082 for a generic solution to the logging problem since we moved to `spdlog`.
