### ISSUE TITLE
Request: add folder.webp + fanart.webp as default files options

### ISSUE THREAD

**Issue by toccata10** [xbmc/xbmc#18531]
The webp format is well supported by kodi. It has many advantages: smaller size than jpg for the same visual quality, transparency as png...
I tried to have a folder.webp instead of a folder.jpg in a music album: by default, no thumbnail was displayed.
Adding this, in the advancedsettings.xml:
<musicthumbs>
  <add>folder.webp</add>
</musicthumbs>
showed the correct thumbnail.
I think, the fanart.webp was taken into account by default (and it didn't need some extra config in the advancedsettings).

For the movies: neither folder.webp, nor fanart.webp, nor movie_name-fanart.webp were recognized (and there doesn't seem to be any setting in the advancedsettings to allow non default filenames).

So, my request is: when folder.webp, fanart.webp, movie_name-fanart.webp, etc... are present, please use them  to show the artwork without any additionnal setting.
I can't imagine any drawback to this, just a nice improvement in the size.

**Comment by KarellenX** [comment]
@toccata10 

This section of Github is for bug reports not feature requests, so I will close your report.

I will also ping @DaveTBlake and @rmrector to read your post as they are currently working on Artwork improvements.

Feature request can be made on the forum here... https://forum.kodi.tv/forumdisplay.php?fid=9
