### ISSUE TITLE
Kodi v19 - Thumbnails/Icons are displayed instead of posters at Favorites and Android TV Tiles

### ISSUE THREAD

**Issue by rainman74** [xbmc/xbmc#18565]
### Describe the bug

Thumbnails or icons are shown instead of posters since Kodi 19 Alpha1/2 (I can't say the exact version)

## Expected Behavior

The behaviour as it was before.

At Favorites:
- Movies are shown with poster
- TV shows are displayed with poster

For Android TV tiles
- Movies are displayed with posters

## Actual Behavior

At Favorites:
- Movies are shown with the thumbnails
- Series are indicated with a star icon

For Android TV tiles
- Movies are also displayed with thumbnails

### To Reproduce
1. Add a movie and a TV show as favourite
2. Show favorites menu
3. Create a playlist and select it as Android TV tile

### Debuglog

not necessary!

### Screenshots 

Android TV Tiles: https://i.imgur.com/0yf9b60.png
Movies @Favorites: https://i.imgur.com/hosslA6.jpg
TV shows @Favorites: https://i.imgur.com/bfPeHjP.jpg

### Your Environment
Used Operating system:
 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

Operating system version/name:
 - Kodi version: kodi-20201012-ef3ea1b2-master-arm64-v8a

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Partially fixed in: https://github.com/xbmc/xbmc/pull/18701

I confirmed the issue with saving favourites, hopefully the last one introduced by the "it is no longer used"(TM) episode. I'll try to figure out a fix.
