### ISSUE TITLE
Estouchy: No scrollbar visible for epg guide at resolution 3000:2000

### ISSUE THREAD

**Issue by StefanS52u1** [xbmc/xbmc#18564]
### Describe the bug

I am using Kodi 18.8 to watch TV. with Estouchy. The EPG GUIDE is not functional with my Matebook X Pro (3:2 Display). The Program and channels columns are mixed up. There is no scrollbar visible (see attachached png). 
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Everything should be visible. Otherwise i can't use the touchscreen.

## Actual Behavior

With this computer resolution i'm forced to use the keyboard.

### To Reproduce

1. Open kodi with Estouchy as interface
2. Press EPG Shortcut (E)

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/5373437/kodi.log)

### Screenshots
Here are some links or screenshots to help explain the problem:

![Epg](https://user-images.githubusercontent.com/61708828/95902372-0465ca00-0d95-11eb-87b0-392793572b4f.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.8

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
@StefanS52u1 thanx for your report!

it's not related to your resolution... there simply is not scrollbar in the guide view.
i can add one of course, but out of interest, doesn't swipe up/down and/or swipe left/right work on your touchscreen to scroll the epg?

as for the other issues:
- the channel names are currently right-aligned. i will change that to left-aligned. that should look a bit better.
- i don't really see what your issue is with the program columns, so if you could please elaborate?

**Comment by StefanS52u1** [comment]
Hi Ronie,
thank you for your answer. I thought a scrollbar must be visible because
only 8 channels of many more are visible. I don't know how to scroll down
with the touchscreen. I can scroll using the arrow keys of the keyboard,
but how to use the touchscreen?.
Regards Stefan

ronie <notifications@github.com> schrieb am Sa., 17. Okt. 2020, 15:14:

**Comment by ronie** [comment]
i'm not familiar with the Matebook X Pro, but i assume you can swipe up and down like on any other touchscreen device.
