### ISSUE TITLE
I should also add, I tried on most operating systems.

### ISSUE THREAD

**Issue by oruize01** [xbmc/xbmc#18575]
I should also add, I tried on most operating systems.
Windows with kodi 18.5 works fine, no problems
Coreelec with kodi 18.8 fails
Android Kodi 18.8 fails
Ubuntu 20.04 kodi 18.8 fails
IpadOS 13 Kodi 18.5 fails
Manually loading the m3u after downloading, as said above all channels fail
Changing the DNS to the server IP, taking out the cloudflare protection, every one works fine.

_Originally posted by @Ballz2k7 in https://github.com/xbmc/xbmc/issue_comments/709456318_

----------------------------------------

"Changing the DNS to the server IP, taking out the cloudflare protection, every one works fine." 

Please, explain again. I don't understand. Thank You

**Comment by KarellenX** [comment]
Please use the forum for support...

https://forum.kodi.tv/index.php
