### ISSUE TITLE
Kodi high CPU usage on addons menu

### ISSUE THREAD

**Issue by vpeter4** [xbmc/xbmc#18588]
### Describe the bug
Here is a clear and concise description of what the problem is:
When you navigate from main screen to addons menu (where on top is the number of addons to be updated) the cpu usage become higher. Also if video is played on background it get slow playback. The issue happens after https://github.com/xbmc/xbmc/pull/18546. Seems addons are checked even if not installed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
CPU usage should be the same as before and playback on background should be normal.

## Actual Behavior
CPU usage is higher and video playback is not smooth.

## Possible Fix
Not known.

### To Reproduce
1. went back to main kodi screen
2. went to addons menu
3. check cpu usage before and after

### Debuglog
The debuglog can be found here: https://pastebin.com/J9zsL04j

### Screenshots 
Here are some links or screenshots to help explain the problem:
https://ibb.co/SP2zVm3
https://ibb.co/xs9sMdp

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04.5 LTS, kernel: Linux x86 64-bit version 5.4.0-51-generic
 - Kodi version: Kodi (19.0-ALPHA2 (18.9.702) Git:20201016-f68475a8d5). Platform: Linux x86 64-bit

**Comment by ksooo** [comment]
Confirmed. Unusable in its current state.

<img width="1431" alt="Screenshot 2020-10-18 at 12 31 24" src="https://user-images.githubusercontent.com/3226626/96364997-fa015280-113d-11eb-9c60-573a6c2be434.png">

**Comment by ksooo** [comment]
@howie-f @phunkyfish calling this guiinfo label in a tight loop is not acceptable.

<img width="1561" alt="Screenshot 2020-10-18 at 12 34 33" src="https://user-images.githubusercontent.com/3226626/96365075-6419f780-113e-11eb-99c0-a4c8cc562033.png">

**Comment by phunkyfish** [comment]
@howie-f the result of that call should be stored in the AddonManager (when it's called elsewhere) and then just return that member variable here.
