### ISSUE TITLE
Exit does not exit kodi (freezes on exit) and requires the process to be killed with the process manager / System Monitor

### ISSUE THREAD

**Issue by mYnDstrEAm** [xbmc/xbmc#18603]
### Describe the bug
Often pressing exit does not exit Kodi so one is required to kill it with the System Monitor.

## Expected Behavior
When pressing exit it should end Kodi.

## Actual Behavior
Kodi does not exit and is frozen.

### To Reproduce

I haven't tested much here. I hope the logs are enough to find the cause of it. But I'll edit this issue when I find out more.
This is all I did:
1. Play a few videos
2. Pause the video (spacebar) and wait a short while (like until the screen gets dimmed)
3. Try to exit with the exit button in the upper left -> Exit

It used to happen almost every time but currently I can't reproduce it. It also happened when I recorded the debuglog for another Kodi bug report where I didn't do much else than these two steps.

I have mostly default settings and use the default skin.

### Debuglog

The debuglog can be found here:
https://pastebin.com/GkDuXDag

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian 10 stable (KDE)
 - Kodi version: 17.6

**Comment by fuzzard** [comment]
Same reply as the other issue.

You'll need to test and provide logs from a Kodi v19 (Alpha 2 or a nightly). Nothing will be done for 17.6, and im also told debian go a bit off script with their packages, but i'll let other linux users/devs chime in on that.

**Comment by mYnDstrEAm** [comment]
Same reply as the other issue.
I really would like to use v19 but 17.6 is the latest version that I could get under Debian. I asked about how to get a newer or the latest version running under Debian [here](https://unix.stackexchange.com/questions/584798/how-to-install-latest-kodi-on-latest-debian). The only way seems to be [via flatpak](https://www.flathub.org/apps/details/tv.kodi.Kodi) and I don't want to do this (or have people required to do this) mostly for security reasons that include the issues described [here](https://github.com/flathub/flathub/issues/1498). If you know of any other way please add a reply to the question. I'm interested what other users/devs have to say about it and maybe I'll use flatpak at some point even though I think the version in Debian's repos should work fine and if it isn't the repos most likely need a newer version.

**Comment by DaVukovic** [comment]
First...thanks for your report. But Fuzzard is correct.

You are still able to either compile Kodi yourself or you are free to use another OS (Ubuntu for example, where we ship the current Kodi version via our own PPA). The fact Debian doesn't provide anything newer than Kodi 17.6 is not a problem Kodi has. It's something you have to claim at Debian. 

Anyway, please try to reproduce with a supported Kodi version. Kodi 17.6 is highly outdated and noone will look at this. 

Feel free to open a new issue which contains a log from a supported Kodi verion.

**Comment by mYnDstrEAm** [comment]
Since I created this issue this problem never occurred again but before there were times when it occurred basically every time. Maybe it had to do with free space available. Otherwise no idea what might have caused this. It neither occured with v 17.6 nor with v 19.0 which I'm currently using. I'll update this issue once it occurs again with an issue with a log for v 19.0 instead of v 17.6.
