### ISSUE TITLE
TV channel number truncated on channel info gui when using arial-based font

### ISSUE THREAD

**Issue by badbob001** [xbmc/xbmc#18601]
### Describe the bug
Here is a clear and concise description of what the problem is:
Kodi 18.8.

When changing TV channels, the large channel number shown in the middle of the channel information gui is truncated. This only occurs when the channel number is above 3 digits and skin (estuary) is using arial-based font.

For example:
Channel "9.1" shows as "9.1", but channel "39.1" shows as "3...".
See the same issue on android and windows.

## Expected Behavior
If channel is 39.1, see 39.1 in channel information gui.

## Actual Behavior
Channel number shows as 3...

## Possible Fix
Widen truncation threshold to support more characters and test with non-default fonts such as Arial.

### To Reproduce
1. Set skin font to arial.
2. In Settings / PVR & Live TV, enable: Use channel numbers from backend (I'm pulling TV from hdhomerun so backend channels show up as 2.1, 4.1, 11.1, etc). 
3. Display a channel and press up and down to switch channel. While switching channels, the channel information gui will appear briefly.
4. Change to a channel with more than 2 digits (eg: 11.1) and look at channel number in middle of the screen, just above the channel information pane.

### Debuglog
The debuglog can be found here:
n/a

### Screenshots 
Here are some links or screenshots to help explain the problem:
https://live.staticflickr.com/65535/50504743317_69e0dc78a7_c.jpg

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
This makes it harder to change to the correct channel.

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10, Android 5.x (firetv)
 - Kodi version: 18.8

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
@ronie maybe something for you?

**Comment by ronie** [comment]
yup i will fix that.
i've added it to the other bunch of fixes: https://github.com/xbmc/xbmc/pull/18574
