### ISSUE TITLE
Crash on plugin opening

### ISSUE THREAD

**Issue by syco** [xbmc/xbmc#18621]
### Describe the bug
I installed kodi from the opensuse repository, opened it, and installed the plex plugin.
But as soon as I try to open the plex plugin kodi crashes.

### Debuglog
please see attached file
[kodi_crashlog-20201022_140649.log](https://github.com/xbmc/xbmc/files/5422989/kodi_crashlog-20201022_140649.log)

### Your Environment
Used Operating system: openSUSE Tumbleweed
Kodi version: 18.8-2.20

Please let me know if I can provide any other info or log.
Thanks

**Comment by DaVukovic** [comment]
2020-10-22 13:56:45.218 T:139902889100672  NOTICE: Disabled debug logging due to GUI setting. Level 0.

Provide a debuglog please. 

Enable debug logging via advancesettings.xml: https://kodi.wiki/view/Advancedsettings.xml#Troubleshooting_settings

**Comment by syco** [comment]
Hi,
I've created the file `~/.kodi/AdvancedSettings.xml` with the following content:
```txt
<advancedsettings>
  <loglevel hide="false">3</loglevel>
</advancedsettings>
```

and restarted kodi, here's the new log file
[kodi_crashlog-20201023_210952.log](https://github.com/xbmc/xbmc/files/5431593/kodi_crashlog-20201023_210952.log)

Thanks

**Comment by syco** [comment]
Just want to add that I've installed the flatpak version and it works.
We can continue looking for a solution to these crashes, but I'm happy to close it if version 18 is not supported any more.
Thanks.

**Comment by wsnipex** [comment]
This is a known issue on tumbleweed, see https://forum.kodi.tv/showthread.php?tid=354879
