### ISSUE TITLE
Sound volume control does not work

### ISSUE THREAD

**Issue by rozhuk-im** [xbmc/xbmc#18623]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have Kodi connected to TV via HDMI, soundbar connect to TV via HDMI eARC.

After some Kodi update at ~last year I can not change sound then I watch movie with DD/DTS, it always 100% but indicator show last volume level and does not react.

I found that this happen if sound sample rate 48000, with 44100 - all works as expected.
I suspect that with 48000 dd/dts directly output via pass-trough to soundbar and volume control cannot be aplly.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After fix I expect that sound volume control will work for all videos.

## Actual Behavior

Sound volume control works with some videos.

## Possible Fix

Force  sound resample, even if src sample rate equal dst (48000) sample rate.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: FreeBSD 12.2-STABLE
 - Kodi version: 19.0a2-Matrix

**Comment by rozhuk-im** [comment]
@lrusak, @fritsch, @AlwinEsch can you look into this, please.

**Comment by fritsch** [comment]
Ah look on what? The missing debuglog?

When passthrough is active all kodi internal volumes are disabled, as we cannot alter the bitstream _at all_ this never was different.

If you want kodi to control the volume, go to audio settings and disable Passthrough.

**Comment by rozhuk-im** [comment]
Yes, you are right.
I miss that with 44100 soundtrack soundbar switch from DD to PCM mode.
Sorry for noise.

Is there any options to keep DD sound features with volumes?
