### ISSUE TITLE
*All seasons" section poster not displaying

### ISSUE THREAD

**Issue by baggypants71** [xbmc/xbmc#18634]
### Describe the bug
Here is a clear and concise description of what the problem is:

In the "*All seasons" section of TV Shows a folder icon is displayed instead of a poster. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

A poster should display.

## Actual Behavior

A folder icon displays

## Possible Fix

Goddam it Jim I'm a doctor not a programmer!

### To Reproduce

1. N/A
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Untitled](https://user-images.githubusercontent.com/44626605/97099088-df4c5200-16d8-11eb-8659-a6dbd0b2076e.jpg)

https://i.ibb.co/QDz01h9/Untitled.jpg

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [tick ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Issue confirmed.

This has been broken in v17 and possibly earlier.

Also of note is when selecting `Context Menu>Manage` on the *All Seasons entry, nothing happens.

**Comment by roidy** [comment]
> Issue confirmed.

Umm.... both `season-all-poster.jpg` and `season-specials-poster.jpg` work fine for me.

> Also of note is when selecting `Context Menu>Manage` on the *All Seasons entry, nothing happens.

This works fine for me on Kodi 18.9 Windows and CoreELEC 18.8, I am able to select artwork for *All Season from `Context Menu>Manage`

**Comment by enen92** [comment]
It'd be nice to have more details on this, can you fill the steps to reproduce section?

**Comment by KarellenX** [comment]
@roidy 

It has never worked for me, across multiple major versions of Kodi, so struggling to understand how it works for you on Windows.

Please post a screenshot like the one in the first post, using Estuary, of the poster being displayed

Are you using local artwork, or was it scraped that way? 
- If using local, can you tell me how you named the poster file.
- If scraped, which tv show, so I can test also. 

Thanks

**Comment by KarellenX** [comment]
@enen92 

All you need to do is add local artwork as named below to a tv show and scan the show into your library.

**season-all-poster.jpg**

**Comment by roidy** [comment]
> @roidy
> 
> It has never worked for me, across multiple major versions of Kodi, so struggling to understand how it works for you on Windows.
> 
> Please post a screenshot like the one in the first post, using Estuary, of the poster being displayed
> 
> Are you using local artwork, or was it scraped that way?
> Are you using local artwork, or was it scraped that way?
> 
> * If using local, can you tell me how you named the poster file.
> * If scraped, which tv show, so I can test also.

@KarellenX 

Here's a video of Kodi 18.9 on Windows setting the poster for *All Seasons using `Context Menu>manage>Set Art`

This also works for special season. This is for a scraped TV Show but it also works for local art.

https://www.youtube.com/watch?v=7xUJN3bYwNQ
