### ISSUE TITLE
Cannot switch to another TTY in kodi-gbm

### ISSUE THREAD

**Issue by Nomeji** [xbmc/xbmc#18652]
### Describe the bug

In kodi-gbm it's impossible to switch to another TTY.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When pressing CTRL + ALT + F1-6 we should be able to switch to another TTY.

## Actual Behavior

When pressing CTRL + ALT + F1-6 nothing append.

### To Reproduce

1. Run kodi-gbm in a TTY
2. Press CTRL + ALT + F1-6
3. Nothing append

### Debuglog

The debuglog can be found here:
http://ix.io/2CbD

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I tried a workaround using a keymap xml. I mapped a key to a script running "sudo chvt 2" (I removed password prompt), it's still doesn't work. Kodi freeze for a few seconds but doesn't switch to a TTY. It still does something since when I close Kodi, it crash and after manually killing it, I'm actually on TTY2.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: ArchLinux 5.9.1
 - Kodi version: 18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
It's on the roadmap https://github.com/xbmc/xbmc/issues/14876
