### ISSUE TITLE
playback bug when seeking on MPEG-TS

### ISSUE THREAD

**Issue by shMatrix** [xbmc/xbmc#18653]
### Describe the bug
Here is a clear and concise description of what the problem is:

Rewind\seeking don't work during playback all MPEG-TS files with such parameters. The picture freezes after seeking and the sound continues.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce
 https://drive.google.com/file/d/1RkNZV1KdSNrqoj21lSk7JTQg8NtFKdkq/view?usp=sharing

1. Download the file
2. Start playback
3. Just seek any

### Debuglog

https://paste.kodi.tv/eropapolol.kodi

The debuglog can be found here: https://paste.kodi.tv/eropapolol.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The problem occurs only with such file formats

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Just to note. Using the provided sample and Kodi 19 Alpha 2 on macos, seeking back and forwards works as expected

**Comment by shMatrix** [comment]
Kodi 19 Alpha 3 works as expected
