### ISSUE TITLE
Library Scrapers Don't Work

### ISSUE THREAD

**Issue by DarkKnight-0987654356789** [xbmc/xbmc#18666]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have been using kodi for nearly a month now.However,Whenever I scan my library for new content,the **scrapers don't work** and the **whole window freezes**.I use Task Manager To Close Kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The Library Scrapers are Expected to Scan my content and provide Posters,Fanart,****all the GOOD BITS**...**

## Actual Behavior

**The Screen Freezes and I have to restart the whole Program.**

### To Reproduce

1.You just select any average content.
2.Then right click your pointer,and select**"Scan to Content"** or **Change Content".**
3.Wait 2 Mississippis and it Freezes. 

### Debuglog

The debuglog can be found [here:](http://paste.kodi.tv/xosefasonu)

### Screenshots
Here are some links or screenshots to help explain the problem:

![Error 1](https://user-images.githubusercontent.com/69567729/97530992-415acf00-19d9-11eb-8981-e2536308aff3.png)
![Error 2](https://user-images.githubusercontent.com/69567729/97531008-49b30a00-19d9-11eb-8914-fd07579c98ce.png)
![Error Message](https://user-images.githubusercontent.com/69567729/97531018-4e77be00-19d9-11eb-8708-43fbb475af4e.PNG)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

1. I Also Tried to Overwrite the Installation
2. ,Reinstalled it.
3. ,Ran it as Administrator but to no avail.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:Windows 7
 - Kodi version:Leia v.18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Not a bug. A problem with your setup. I'll deal with you on the forum.

**Comment by DarkKnight-0987654356789** [comment]
**How To fix IT.**
