### ISSUE TITLE
The volume is set to maximum after pausing a video in Kodi for a few minutes

### ISSUE THREAD

**Issue by mYnDstrEAm** [xbmc/xbmc#18665]
### Describe the bug
When resuming a video after having pressed pause it has the volume set to the maximum.

This does not occur when pausing for just a short while - it only appears when pausing for a few minutes until the screen gets dimmed a bit (I haven't tested if it occurs before the screen gets dimmed yet).

It might be related to the System->Audio setting to keep the audio device active. If changing this option (from 1 minute to something larger) solves this issue then the volume should not be set to the max (with any other setting than "always") after pausing nevertheless.

I created an issue before but it was for v17.6 - now this is for 19.0 and on another machine.

## Expected Behavior
The volume should be exactly as before (when one pressed pause).

## Actual Behavior
The volume is set to the maximum.

### To Reproduce

1. Play a video (filename.mp4 in the logs)
2. Pause the video (spacebar)
3. Wait a short while (like until the screen gets dimmed a second time)

### Debuglog

The debuglog can be found here:
https://pastebin.com/tirLRPMZ

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian 10 stable
 - Kodi version: 19.0

[Previous issue for the version 17.6 here](https://github.com/xbmc/xbmc/issues/18602).

**Comment by basilgello** [comment]
I have never seen such behavior but my sound system is ALSA. You can try uninstalling PulseAudio on your Kodi box and check if the problem goes away. If it does, we'll unwind this issue further.

**Comment by fritsch** [comment]
Can you please post your: /etc/pulse/daemon.conf - I think, based on the ancient distribution you are running, that you are running into the issue with flat-volumes, thankfully pulseaudio changed this default some years ago - but let's see first.

**Comment by fritsch** [comment]
See from debian wiki: https://wiki.debian.org/PulseAudio#Sound_level_is_low_or_suddenly_becomes_too_loud

**Comment by mYnDstrEAm** [comment]
I'm using the latest Debian 10 stable. I run PulseAudio 12.2. I have some other problems with audio sometimes. I'm using the Phonon GStreamer Backend (4.9). The `daemon.conf` file is empty / only has commented-out settings. I changed this by setting `flat-volumes = no` as described in the Debian Wiki but this didn't help - the problem still occurs.

**Comment by fritsch** [comment]
Jep, then I cannot help you. Most likely debian uses local config as pulse is not a system wide daemon anymore and run as user.

Therefore try your distro documentation on how to change it. Kodi does not reset these volumes at all besides being told. Flat volumes is one reason for this, but a server setting without our influence.

**Comment by fritsch** [comment]
Try to create it under: 
~/.config/pulse/daemon.conf
~/.config/pulse/daemon.conf.d/*.conf

one of these, and check if there is already something in there. The default upstream changed some time ago, therefore it could be an ancient config file.

Also a pulseaudio log would help, therefore "mask" your user pulseaudio and disable its autospawn. After **you are fully sure** it is not running, start it with pulseaudio -vvv and then start kodi.

pulseaudio should tell now exactly by itself who changes the volume.

**Comment by mYnDstrEAm** [comment]
Those two files don't exist. `/etc/pulse/daemon.conf` does exist but only had commented-out settings. Maybe you misunderstood me there. (I changed `; flat-volumes = yes` to `flat-volumes = no`.)

I killed pulseaudio with the process manager even though that's not part of the guide in the wiki and it automatically restarts so the setting should be loaded.

The strange thing is that on one of my machines the screen doesn't dim at all anymore even though it's the same version of Kodi and version of PulseAudio as on another machine and also has the keep audio device alive setting set to 1 minute and used to dim the screen. I'll see why that is and whether it stays that way.

Anyways: it works now. It seems like the daemon.conf setting did solve this problem. Maybe it should be made a default setting but that would be a Debian / PulseAudio problem. Thank you!

**Comment by fritsch** [comment]
It is a default setting - upstream :-). Therefore I totally wondered to see so many problems here with a setting that was years ago swapped.

**Comment by fritsch** [comment]
Btw. kodi's wiki: https://kodi.wiki/view/PulseAudio mentions to restart PA properly.

**Comment by ryanthemadone** [comment]
I have this exact issue, but running Kodi on a Google TV (Android) stick. In fact sometimes the volume is maximum, or at least really high and sometimes when unpausing it's half what it was prior to pausing.

Doesn't happen every time, but happens frequently.

Do I need to raise a new ticket for this?
