### ISSUE TITLE
KODI18 - Different sources are mixed in library (for TV Shows only)

### ISSUE THREAD

**Issue by Capslock2204** [xbmc/xbmc#18661]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have created two sources (one from my NAS, one from my remote server, so different paths) and two smart playlists.
I want to display the smart playlist A for the source A and I want to display the smart playlist B for the source B.

On the two sources there are the same TV Shows. When I update my library for my source A everything is fine, the TV show is displayed correctly on the smart playlist A. 
If I update my library for my source B (same TV show), the episodes are added in the smart playlist A.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I'm doing the same thing for movies, and it works fine. So I was expecting for the TV shows to work the same way. Unfortunately, it is not the case.
I was expecting, even if it is the same TV Show, to display in the smartplay list A, the TV shows from source A (path is smb://XXXX), the good TV shows, and same thing for smart playlist B, the TV shows from source B (path is ftp://XXXX).

## Actual Behavior

When I update source A, smart playlist A displays the good TV Show.
When I update source B, smart playlist A displays the TV Show from A and B , and smart playlist B displays nothing.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP
 - [X] Raspberry PI 3

 - Operating system version/name:  LibreElec 9.2
 - Kodi version: Kodi 18.8 (Linux Kernel 4.19.x)   

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
No, this is not a bug. What you are encountering is intentional.

Kodi intentionally combines separate folders of the same tv show into one.

Issue closed. If you need further support, please take it to the forum.
