### ISSUE TITLE
Exit does not exit: kodi freezes on exit and requires the process to be killed with the process manager

### ISSUE THREAD

**Issue by mYnDstrEAm** [xbmc/xbmc#18673]
### Describe the bug
Often pressing exit does not exit Kodi 19.0 so one is required to kill it with the process manager (e.g. System Monitor in KDE).

## Expected Behavior
When pressing exit it should end Kodi.

## Actual Behavior
Kodi does not exit and is frozen.

### To Reproduce

I haven't tested much here. I hope the logs are enough to find the cause of it. But I'll edit this issue when I find out more.

Try to exit with the exit button in the upper left -> Exit

In this case I tried running the [Kodi-Lutris addon of latest.zip](https://github.com/RobLoach/lutris-kodi-addon/issues/46#issuecomment-713880848) (eeaa9d53620e165e94acbe9dcedb51f0601cde2ceab5a7e977b4f7e8bd5920cc) with Kodi 19.0 from Basil Gello's repository for Debian 10. But I also had this problem doing nothing but playing a video file, pausing it and exiting afterwards and even doing nothing at in Kodi and just clicking exit soon after it started.

It used to happen almost every time but currently I can't reproduce it.

I have mostly default settings and use the default skin.

### Debuglog

The debuglog can be found here:
https://pastebin.com/bNy0NjBw

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian 10 stable (KDE)
 - Kodi version: 19.0 alpha 2

[Had the same problem with v17.6](https://github.com/xbmc/xbmc/issues/18603)

**Comment by KarellenX** [comment]
Please provide a debug log with debug mode enabled.

**Comment by mYnDstrEAm** [comment]
Sorry for not having debug mode enabled: it didn't happen again for a long while and I can't reproduce it. I have the debug mode enabled now and will post the log if I can make it happen again / if it happens again.

**Comment by KarellenX** [comment]
Ok. I will close this issue as you are unable to replicate it.

If you do capture the problem in the log, post on the forum, and if it turns out to be a real bug, we can re-open this report.
