### ISSUE TITLE
Kodi 19 from nightly ppa does not install on Ubuntu 20.10

### ISSUE THREAD

**Issue by rbuehlma** [xbmc/xbmc#18687]
### Describe the bug
Here is a clear and concise description of what the problem is:

Installing Kodi 19 from nightly PPA (deb http://ppa.launchpad.net/team-xbmc/xbmc-nightly/ubuntu groovy main # disabled on upgrade to focal disabled on upgrade to groovy) under Ubuntu 20.10 does not work due to this error:

The following packages have unmet dependencies:
 kodi : Depends: libcec4 but it is not installable

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi from nightly PPA should install.

## Actual Behavior

Missing dependency during install.

## Possible Fix

libcec6/groovy,now 6.0.2-1 would be available. May be that version can be used?

### To Reproduce

1. Install Ubuntu 20.10
2. Add nightly PPA
3. Try to install Kodi 19

### Debuglog

The debuglog can be found here:

There is no debug log since installing fails.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 20.10 upgraded from 20.04
 - Kodi version: 19 Nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by phunkyfish** [comment]
There are some major changes in libcec6 from what I recall so it's not a drop in replacement.

@wsnipex any guidance here?

**Comment by wsnipex** [comment]
I just pushed a build(ETA ~1-2h) that removes that hard runtime dependency on libcec4, so it should use libcec6.
No idea if that actually works, I cannot test it myself.

**Comment by rbuehlma** [comment]
I'm now able to install Kodi and its also running fine but I do not use CEC.
ldd seems to be happy:
`libcec.so.6 => /usr/lib/x86_64-linux-gnu/libcec.so.6 (0x00007fb143ea9000)`
but I do not know if this means anything about functionality.

In any case, my issue is solved, thank you for this :) Shall I close this ticket or do you want it to stay open?

**Comment by phunkyfish** [comment]
Please close as the issue is resolved.
