### ISSUE TITLE
Built-in subtitle tracks do not display on and after October 25th nightly.

### ISSUE THREAD

**Issue by jakkerson** [xbmc/xbmc#18693]
### Describe the bug
Here is a clear and concise description of what the problem is:

Since the merge of this PR https://github.com/xbmc/xbmc/pull/18445 subs built into files no longer display on playback.
(Since the nightly on October 25th no built in file subs display, 23rd and before do display)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Display the subs when selected via the Kodi player.

## Actual Behavior

No subtitles show when a built in track is selected (Since October 25th).

## Possible Fix

Fix PR/Revert?

### To Reproduce

1. Play any file that has sub tracks built in on the latest Kodi nightly 

### Debuglog

The debuglog can be found here:
Will update the issue with a log in the coming days when I can. I am only posting now as I can see you are getting ready for an Alpha 3 snapshot release with this bug.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ Yes ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi Nightly 31st October

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Dnkhatri** [comment]
I had no problems with internal subtitles on Android ie nvidia shield or linux mint currently using the last 31st oct nightly.

**Comment by jakkerson** [comment]
> 
> 
> I had no problems with internal subtitles on Android ie nvidia shield or linux mint currently using the last 31st oct nightly.

Sorry you are correct, it was due to Forced subtitle tracks not displaying any subs with English audio
