### ISSUE TITLE
 Bad sound on Kodi

### ISSUE THREAD

**Issue by Sidordroid** [xbmc/xbmc#18707]
Dear developers. Work on the sound quality and add the function of activating low frequencies. It is unbearable to listen to music on this application - I have a 200W audio system with a subwoofer, but even it does not take out empty Kodi sound. Forced to use another player where possible, but on OS CoreElec Recalbox Kodi is built in and you have to endure obscene sound when listening to music

**Comment by KarellenX** [comment]
Invalid issue report.

Please post your comments on the Forum. This area is for confirmed bugs.
