### ISSUE TITLE
Copy paste error in PVRClientMenuHooks.cpp

### ISSUE THREAD

**Issue by qarmin** [xbmc/xbmc#18716]
https://github.com/xbmc/xbmc/blob/5230b683323ca58c62459a371c1306a6cb4d4644/xbmc/pvr/addons/PVRClientMenuHooks.cpp#L23-L31

Look at `PVR_MENUHOOK_RECORDING`

**Comment by basilgello** [comment]
Please PR the fix - it is really easy! :+1:

**Comment by domielias** [comment]
Hi, what should i need to do for PR this?

**Comment by fuzzard** [comment]
one of the PVR_MENUHOOK_RECORDING items just needs to be changed to PVR_MENUHOOK_DELETED_RECORDING

**Comment by domielias** [comment]
He would make a PR or i can do? He found so, i don't know.

**Comment by fuzzard** [comment]
Doesnt seem like the issue reporter is going to PR the change, so go ahead

**Comment by domielias** [comment]
I made the commit but i don't found the option to use the label so the CI gave me a error.

**Comment by fuzzard** [comment]
All good, labels/milestones are added by team members. lrusak has done that just now
