### ISSUE TITLE
[Leia/Matrix] Invalid translation string in resource.language.pl_pl

### ISSUE THREAD

**Issue by eremem** [xbmc/xbmc#18712]
### Describe the bug
The translation in the polish language package (resource.language.pl_pl) is invalid for string #19175 and currently equals to the one for #19176:

msgctxt "#19175"
msgid "Default start padding time"
msgstr "**Nagrywaj po zaplanowanym czasie końca**"

msgctxt "#19176"
msgid "Default end padding time"
msgstr "**Nagrywaj po zaplanowanym czasie końca**"

## Expected Behavior
The correct translation entry for #19175 should be:

msgctxt "#19175"
msgid "Default start padding time"
msgstr "Nagrywaj przed zaplanowanym czasem początku"

## Actual Behavior
"Nagrywaj po zaplanowanym czasie końca" is shown instead of "Nagrywaj przed zaplanowanym czasem początku".

## Possible Fix
The entry for #19175 should be fixed in resource.language.pl_pl\resources\strings.po as proposed above in _Expected Behavior_.

### To Reproduce
Both string are visible in:
System settings/PVR & Live TV/Recording (in polish version obviously).

### Debuglog

The debuglog can be found here:
N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: XBian & Windows 10
 - Kodi version: 18.9.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Thanks for your report. Using a bit of google translate you seem to be correct as your proposed string means something like "start *before* scheduled time" which seems to be what that setting causes. 

Anyway, translations have to be done at our translation system which is currently in change. So please be patient and there's also no need to create a PR for that as those changes will be done automatically by the system we are using. So a PR won't be accepted. Just to let you know ;)

After the translation has been changed, the specific addons need to be updated and after that you will see the changes. So it might take a while.

**Comment by eremem** [comment]
I hope I'm not wrong with this translation as it would be a great disgrace, since polish is my mother tongue;).
After posting my report I noticed that there is already an equivalent pair of entries: #813 & #814, so it can serve as reference and/or a proof that my suggestion is not that bad;).

Thank you guys for your great work with this project and I hope to see this fix in the near future:)

**Comment by gade01** [comment]
@eremem 
Thanks so much for reporting this.

As I wrote in the other issue, we are currently working on moving translations to Weblate.
Currently we still have some remaining things to sort out, which is why we have not yet opened fully up for regular users and translators.

Once we open up, you can fix issues like this by registering as a user.
We will keep the issue open until then.

**Comment by gade01** [comment]
@eremem 
Fix pending:
https://github.com/xbmc/repo-resources/pull/125/files#diff-fc1d73e5c3b3fef1967ef3e06e4ea610d28e163676da5cba8fbb66da60e33fb5R7663

Please check if this is correct.

**Comment by eremem** [comment]
**@gade01**
The corrected translations look now good to me.

**Comment by gade01** [comment]
The changes and fixes are pushed to the new language addons.

Thanks again for reporting this.
