### ISSUE TITLE
Possible usage of null pointer

### ISSUE THREAD

**Issue by qarmin** [xbmc/xbmc#18718]
https://github.com/xbmc/xbmc/blob/5230b683323ca58c62459a371c1306a6cb4d4644/xbmc/utils/StringUtils.cpp#L1613

Probably correct code should looks that.
`while (s && *s == ' ') s++;`

This seems to be bug, because s may be null pointer and `*s` or `*s == ' '` will use invalid memory

**Comment by DaVukovic** [comment]
If you think this is a bug, then feel free to PR it and discuss the possibility if it's a bug or not at the PR in question ;)

**Comment by ksooo** [comment]
All your issues are very good catches on code flaws/bugs. Why don't you just open PRs instead of issues? Would make everyone's life easier.

**Comment by domielias** [comment]
Hi, can i make the pull request?

**Comment by DaVukovic** [comment]
Everybody is allowed to do it.

**Comment by bad-ed** [comment]
> https://github.com/xbmc/xbmc/blob/5230b683323ca58c62459a371c1306a6cb4d4644/xbmc/utils/StringUtils.cpp#L1613
> 
> Probably correct code should looks that.
> `while (s && *s == ' ') s++;`
> 
> This seems to be bug, because s may be null pointer and `*s` or `*s == ' '` will use invalid memory

The code is correct. `s` cannot be `nullptr` at this point, because if it were, function would crash much earlier (when `c` is dereferenced).

**Comment by garbear** [comment]
I think a more clear expression of this logic would be

```c++
 while (*s != '\0' && *s == ' ') s++; 
```

**Comment by domielias** [comment]
I made the PR for this issue.

**Comment by qarmin** [comment]
If `s` cannot be null pointer then function should look that:
```
 while (*s == ' ') s++; 
```
because in
```
 while (*s && *s == ' ') s++; 
or 
 while (*s != '\0' && *s == ' ') s++; 
```
first condition is redundant(if `*s == ' '` then always `*s != '\0'`)

**Comment by fritsch** [comment]
Yeah, it's wrong, the original author meant an || or he got it wrong :-)

**Comment by malard** [comment]
closing this ticket as the PR is still open but ignored
