### ISSUE TITLE
Self assignment bug

### ISSUE THREAD

**Issue by qarmin** [xbmc/xbmc#18717]
https://github.com/xbmc/xbmc/blob/770c691bfeea88d561b39d2e38348ac434db3adc/xbmc/network/websocket/WebSocketManager.cpp#L68

https://github.com/xbmc/xbmc/blob/ffca90e599d78d8147c02276d209ef65f8c68d37/xbmc/network/websocket/WebSocketV8.cpp#L119

https://github.com/xbmc/xbmc/blob/770c691bfeea88d561b39d2e38348ac434db3adc/xbmc/network/websocket/WebSocketManager.cpp#L52

https://github.com/xbmc/xbmc/blob/53f2fd8f1ded07a10b16dc9be266afab6ca2b634/xbmc/video/Teletext.cpp#L1288

**Comment by ksooo** [comment]
Good catch. Please PR.

**Comment by domielias** [comment]
Hi, can i make the pull request?

**Comment by ksooo** [comment]
sure

**Comment by domielias** [comment]
I made the PR for this issue.

**Comment by ksooo** [comment]
Fixed with #18725
