### ISSUE TITLE
Kodi-send fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by jmgibson1981** [xbmc/xbmc#18728]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi-send command fails on Ubuntu 20.04

## Expected Behavior

My script for shutdown / reboot should execute.

## Actual Behavior

`bad interpreter no such file or directory /usr/bin/python`

## Possible Fix

Reason for bug seems to be the way Ubuntu 20.04 links python versions. Both python3.8 and python2.7 symlink to /usr/bin/python2 /usr/bin/python3 respectively. Fix is change shebang in kodi-send to /usr/bin/python2 or create symlink from /usr/bin/python2 > /usr/bin/python.

Patch as suggested by greysky on forums.

Apply to /usr/bin/kodi-send

```
--- kodi-send	2020-11-04 12:22:19.498358893 -0700
+++ "kodi-send (copy 1)"	2020-11-04 12:25:08.227612493 -0700
@@ -1,4 +1,4 @@
-#!/usr/bin/python
+#!/usr/bin/python2
 #
 # XBMC Media Center
 # XBMC Send
```

### To Reproduce

Run kodi-send of any variation.

### Debuglog

The debuglog can be found here:

https://paste.ubuntu.com/p/3HqZ4X7n3j/

### Your Environment
Used Operating system:

Ubuntu 20.04 Focal x64
 - Kodi version:
```
kodi-eventclients-kodi-send:
  Installed: 2:18.9+git20201024.0821-final-0focal
  Candidate: 2:18.9+git20201024.0821-final-0focal
  Version table:
 *** 2:18.9+git20201024.0821-final-0focal 500
        500 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu focal/main amd64 Packages
        500 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
     2:18.6+dfsg1-2ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu focal/universe i386 Packages
```

**Comment by wsnipex** [comment]
v18 needs python 2, which commonly is /usr/bin/python. To fix this on you system, either install python-is-python2 or manually create the symlink or change the shebang in kodi-send.
In any case v18 is EOL and this doesn't justify a new release, because the workaround is trivial.

It's fixed for v19
