### ISSUE TITLE
Add-on migration stuck on Kodi update from Leia to Matrix

### ISSUE THREAD

**Issue by vlmaksime** [xbmc/xbmc#18723]
### Describe the bug
Here is a clear and concise description of what the problem is:

I was tested the new repository structure for automatic add-on updating from my repository at Kodi 19 update and ran into the problem of the Kodi freezing on message "Add-on migration in progress - please wait...".
I tested on alpha-3 build. Here is profile folder, which was used in tests: [kodi_data.zip](https://vlmaksime.github.io/repository.vlmaksime.test/files/kodi_data.zip)
According kodi.log, it's freezing after updating of my repository, here is full log: [kodi.log](https://vlmaksime.github.io/repository.vlmaksime.test/files/kodi_matrix.log)
I'm waited about 20 minutes, before stopping Kodi process. After Kodi restarts, it successfully completes add-on migration. 
Here is repository, that I'm using for tests: [vlmaksime.repository.test](https://vlmaksime.github.io/repository.vlmaksime.test/repo/)

I also noticed that add-ons disappear from the list if an error with a dependency occurred during their update.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After repository updating, Kodi should install updates for add-ons, presented at my Matrix repository. Then it should open user interface, but not stuck on loading screen.

## Actual Behavior

After successful update of my repository add-on, Kodi freezing on message "Add-on migration in progress - please wait...".
If I remove repository add-on before Kodi update, it's loads successful.

### To Reproduce

1. Unpack [kodi_data.zip](https://vlmaksime.github.io/repository.vlmaksime.test/files/kodi_data.zip) into Kodi 19 data folder
2. Launch Kodi

### Debuglog

The debuglog can be found here:
[kodi.log](https://vlmaksime.github.io/repository.vlmaksime.test/files/kodi_matrix.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64
 - Kodi version: 19.0-ALPHA3 (18.9.730)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by howie-f** [comment]
@vlmaksime i tested your provided zip and ran into the same issue on linux. on the other hand a migration of my current leia installation, without any third party repo installed, proceeds flawlessly. can you try to remove your repo prior to migration please and report back?

**Comment by vlmaksime** [comment]
@howie-f, I wrote about this in issue
>  If I remove repository add-on before Kodi update, it's loads successful.

**Comment by howie-f** [comment]
ah yes, ok, will have a closer look on that repo

**Comment by nonobio** [comment]
Hi,

After my last message (Aug 26, 2021) when updating from Kodi 18 to 19, I had to restore my advancedsettings file, set Kodi to French regional, and update my addons, then it seems it was ok.

**Today I have the same issue after installing Kodi 20.1 to update my 19.4 version on windows: it stuck on "Add-on migration..."** for about 15 minutes:

![image](https://user-images.githubusercontent.com/7425799/236676477-4f757ab1-f5d2-4c7a-a331-08141a214f14.png)

I think I can resolve the issue like the last time but **do you know why I have this problem and what the best solution to resolve it?**

Thanks :)

I use a MySQL shared database and Kodi said database migration very quickly before saying "Add-on migration".

**Comment by nonobio** [comment]
Thanks, I don't know if it is sufficient: I just killed Kodi (it was still stuck) and this is the Kodi log I have (I didn't enable the debugging log because I can't go to Kodi settings):

https://paste.kodi.tv/oduwemocak.kodi

**Comment by howie-f** [comment]
> it started! Everything "seems" to be ok.

hm, this log claims the opposite
honestly, try to get rid of `catchuptvandmore.kodi.release` and `plugin.video.amazon-test` and be glad that it is running now.

> should I check or clean something

yup :) ^^

**Comment by nonobio** [comment]
Thanks, I will take a look at this add-ons :)
