### ISSUE TITLE
Matrix: 4:3 4K TV/Movies showing 8K tags

### ISSUE THREAD

**Issue by deadman0713** [xbmc/xbmc#18738]
### Describe the bug
Here is a clear and concise description of what the problem is:

A movie or tv show that is "4K" 4:3 (1.33:1) shows with an 8K tag in the info screens.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Should display the 4K tag, instead of the 8k tag.

## Actual Behavior

Is displaying the 8K tag.

## Possible Fix

Some discussion in forum post:
https://forum.kodi.tv/showthread.php?tid=358184

### To Reproduce

1.  Play a movie or TV show which is in a 3840x2880, 4K 4:3 size.
2.  Default Estuary skin.
3.

### Debuglog

The debuglog can be found here:

N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://i.ibb.co/kJfc3q6/BGC-Est-Matrix01.png

https://i.ibb.co/NmhmTsB/BGC-Est-Matrix03.png

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LIbreElec
 - Kodi version:  LibreElec Matrix build LibreELEC-Generic.x86_64-9.80-nightly-20201103-f0d82de

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by deadman0713** [comment]
Missing fields have been re-added.

**Comment by jjd-uk** [comment]
This should now be fixed.
