### ISSUE TITLE
No program guides are shown for IPTV channels

### ISSUE THREAD

**Issue by mYnDstrEAm** [xbmc/xbmc#18737]
### Describe the bug
Here is a clear and concise description of what the problem is:
With the Kodi addon kodi-pvr-iptvsimple and a channel list like Wilmaa's the program guides are empty (screenshot below) and no information besides the channel title and channel logo are shown in the channel list.

(
* Furthermore when adding channels to the favorites they only show in the Kodi tab "Favorites" but not directly in the TV tab like "Recently viewed channels".
* As an alternative or in addition to showing "Favorite channels" just like "Recently viewed channels" it would be great if there was a "Wall"-view for the Channels. Currently it's only possible to view them as a list but not as a wall (or any other viewtype; such a view-option is missing entirely).
These are separate issues and wouldn't be bugs.
)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
The program guides shouldn't be empty. Furthermore, there should be information in the right panel of the channel list and beneath the channel titles.

## Actual Behavior
The program guides are empty. Furthermore, No information is displayed in the right panel of the channel list and beneath the channel titles.

## Possible Fix
I'm not sure how this information is fetched. If it is fetched from URLs provided in the channel list, this information should probably be separated from such channel-lists (.m3u files) so that a separate service provides this information (which could e.g. be whatever the channel-list gets this information from) via the channel title and/or unique ID.

### To Reproduce
1. Install/use addon kodi-pvr-iptvsimple
2. Install/use a channel-list like Wilmaa's
3. Try to view channel guides under "TV"

### Debuglog
The debuglog can be found here:
https://pastebin.com/iJWvymJ3

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian 10 stable
 - Kodi version: 19.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by mYnDstrEAm** [comment]
I have edited the issue to also include e.g. "Here is some additional context or explanation that might help" and think the "Ignore rules" tag can be removed now.

**Comment by basilgello** [comment]
@mYnDstrEAm Did you set path to EPG XMLTV on "EPG" pane of IPTVSimple settings? Using M3U playlist alone is not sufficient to get EPG. You can use 3rd party websites or grabbers to produce XMLTV file or specify the one your IPTV provider bundles. For example, I had to create a binary proxy server in Golang to make my IPTV provider with iptvsimple.

**Comment by mYnDstrEAm** [comment]
No, I didn't, sorry and thanks - they are showing up now. The issue can be closed as the wall view and display of favorite channels sadly aren't bugs.

**Comment by basilgello** [comment]
You can try fiddling with settings, using another skin, or file an improvement request.
