### ISSUE TITLE
Webm not playable over network due to missing UPNP mimetypes list entry

### ISSUE THREAD

**Issue by Yowlen** [xbmc/xbmc#18740]
### Describe the bug
Here is a clear and concise description of what the problem is:

Trying to play `webm` videos from my phone using an app like BubbleUPNP throws an error.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Casting a webm video should work, same as if I were playing it locally within Kodi.

## Actual Behavior

The specific error BubbleUPNP gives: "No compatible decoder found." and it mentions the mimetype check being the cause.

## Possible Fix

Add webm's respective formats to the UPNP server's mimetype list.

### To Reproduce

1. Install Kodi.
2. Go to `Settings` -> `Services` -> `UPnP/DLNA` -> Enable both `Enable UPnP Support` and `Allow remote control via UPnP`
3. Use another device to cast a `webm` video to Kodi's UPNP server.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/5505640/kodi.log)
Edit: Updated with a debug log consisting of all activities from starting up Kodi, then starting up BubbleUPNP, then manually accessing the mimetype info as shown in the screenshots, and finally attempting to play a `webm` video from BubbleUPNP. Still not sure how it can help, but whatever.

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screenshots showing the mimetypes that Kodi sends as BubbleUPNP is able to understand them. `webm` doesn't appear anywhere on the list, not even in the "Other" section where the formats that BubbleUPNP can't play are listed.
![Screenshot_20201105-131832_BubbleUPnP](https://user-images.githubusercontent.com/17078692/98280707-c742c100-1f69-11eb-9c2f-2c7bbb677f95.png)
![Screenshot_20201105-131838_BubbleUPnP](https://user-images.githubusercontent.com/17078692/98280706-c6aa2a80-1f69-11eb-9b0a-b7839a7d23c5.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Xubuntu 20.04
 - Kodi version: 19.0-ALPHA3 Git: 20201105-d18507c980 (i.e. Latest nightly PPA as of this writing)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Can you post a debug log? It looks like me that the mime type for upnp is made by checking the file extension.

**Comment by Yowlen** [comment]
I don't know about server-side, but yes, the mimetype check is based on file extension in BubbleUPNP. Adding `video/webm` and `audio/webm` to Kodi's UPNP server's supported mimetypes list would fix this issue. The underlying codecs inside the container are already supported and work fine when playing it manually from the computer itself.

As for the debug log, I'll see about getting one soon once I catch a break, but as I said in the original post, I really can't see why one would be useful in this case.

**Comment by lrusak** [comment]
I'm asking because it seems that the extension builds the mime type that is sent, so if the file doesn't end in `.webm` that mimetype won't be used.

see: https://github.com/xbmc/xbmc/blob/master/xbmc/network/upnp/UPnPInternal.cpp#L142

**Comment by Yowlen** [comment]
The video does end in `.webm` though, and BubbleUPNP is detecting literally everything else and has played `webm` videos just fine on other players such as Chromecast, so it appears that `webm` isn't being added to Kodi's global mimetype list like mp4 and every other type.

Where does lines 140-149 of `xbmc/xbmc/network/upnp/UPnPInternal.cpp` get its list from? Because it seems like that's where the problem lies.

**Comment by Montellese** [comment]
There's a long list of supported protocols / MIME types for the UPnP renderer at https://github.com/xbmc/xbmc/blob/9655b4ffc45ad57f2511ac33309a786aa75c4de8/xbmc/network/upnp/UPnPRenderer.cpp#L76. I have no idea where that list comes from but I'm pretty sure it's never updated. But then again the UPnP renderer is only used when Kodi is the player and not the other way around (IIRC you are trying to play something on your phone from Kodi right?).

**Comment by Yowlen** [comment]
> But then again the UPnP renderer is only used when Kodi is the player and not the other way around (IIRC you are trying to play something on your phone from Kodi right?).

Yes, that is correct. I'm essentially using Kodi like a Chromecast/Roku device, which means this would be the applicable section of the code. And sure enough, that list is indeed missing `audio/webm` and `video/webm`, which could very well be the cause of the problem.

I'll see what I can do about cloning the repo, changing that file to add the two missing entries, compile it, and test it. I'm not really used to doing this kind of stuff, but I'm sure you have some compiling instructions somewhere I can use as a base, and editing the file will be no problem. I'll update to let you know how it works out.

**Comment by Yowlen** [comment]
Alright! Compiled with the modifications and it works! It doesn't look like BubbleUPNP recognizes the `audio/webm` mimetype, but it's probably better to add it in for other players just in case. The `video/webm` mimetype is definitely recognized, though.
![Screenshot_20201112-144044_BubbleUPnP](https://user-images.githubusercontent.com/17078692/98988158-36359200-24f5-11eb-83cf-4235bfdd6802.png)

While I was in there, I also noticed that `image/webp` was missing and while I didn't add it into my test build here, it might be a good idea to add that one in too in order to avoid any future problems with anyone casting images.

**Comment by Montellese** [comment]
Thanks for taking the time to actual build and modify this yourself. Can you provide the patches or even a pull request with your changes?

**Comment by Montellese** [comment]
I'm also wondering if that list should be more dynamic. We have a list of supported extensions (not sure about mime types) in advanced settings (and some utils helper) which is based on a static list of extensions and all extensions supported by add-ons. That might be more accurate than what is listed in the UPnP renderer.

**Comment by Montellese** [comment]
This is the helper I was talking about: https://github.com/xbmc/xbmc/blob/9655b4ffc45ad57f2511ac33309a786aa75c4de8/xbmc/utils/FileExtensionProvider.h#L39

**Comment by Yowlen** [comment]
Alright. I think this patch should work. First time making one of these things, so I hope I did it correctly.
[0001-Add-webm-and-webp-mimetype-support-to-UPNP-Renderer.patch](https://gist.github.com/Yowlen/5eef8bb8bea965c38df1442ecb5d1f98/raw/96bfd79f7e8f9daaab718f5a68d9fa06d4528efc/0001-Add-webm-and-webp-mimetype-support-to-UPNP-Renderer.patch)

**Comment by Yowlen** [comment]
It might be better to try to generate a list using the Get Video/Audio/Image Extensions things, yeah. Someone else would have to do that, though, because that's far beyond my ability. I don't know any programming languages beyond BASH shell scripts, so the best I can do is make simple edits based on the existing structures like I did above. Adding new functions is way out of my league.

Still, at least my patch should work in the meantime.

**Comment by Montellese** [comment]
See #18786 for the pull request based on your patch. If I find some time I'll look into creating that list of supported mime types based on `CFileProviderExtension`.
