### ISSUE TITLE
Does not play back FLAC Codec properly

### ISSUE THREAD

**Issue by O1ez** [xbmc/xbmc#18745]
I cant play back FLAC files on any of my devices via the source. It only works when I go through the file system. If I try to play it back in the library it simply skips the song and plays back the next one it can play back. 

I already tried installing a FLAC decoder add-on but it didn´t do anything. 

It also doesn´t matter if I try the playback on the device or when streaming to an other device. 
My devices are: Raspberry Pi 4, Raspberry Pi Zero WH, Windows PC and Android phone.
Do you need any logs for it or is the issue already known?

Btw: I also wanted to register in the forum to ask for a solution there but the registration page refuses my e-mail adress so that is impossible.
Greetings,
Ole

**Comment by KarellenX** [comment]
@O1ez 

Your post is a request for assistance and not a bug report, so I will close your report as it is invalid.

There should be no restriction for email addresses when registering, only a restriction on what characters can be used in a Username as well as some words that are prohibited.

Please try again.
