### ISSUE TITLE
Add ability to pass albumid via ListItem.SetInfo Python interface

### ISSUE THREAD

**Issue by jbinkley60** [xbmc/xbmc#18759]
### Describe the bug
Here is a clear and concise description of what the problem is:

Requesting the adding of a feature to allow addons to pass the albumid via Python interface so that the DialogMusic.Info.xml file can then display album information via the Album Information button.  Currently the button is nonworking for Python addons.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would like addons to be able to pass the albumid to Kodi so that the Album information button is available to adons.  Currently the addon Python interface cannot pass this value via a call like:

listitem.setInfo('music', { 'albumid': xxx })  

## Actual Behavior

The Album Information button is unavailable to Python addons.

## Possible Fix

Update the ListItem.SetInfo class to add an albumid or similar field.  

### To Reproduce

1.  https://forum.kodi.tv/showthread.php?tid=358200&pid=2987589#pid2987589
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [X ] Linux
 - [ ] OSX
 - [ X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Your going to have to post feature requests on the forum at
https://forum.kodi.tv/forumdisplay.php?fid=9
