### ISSUE TITLE
Sorting movies by "Play Count" is broken - displays rating instead of play count

### ISSUE THREAD

**Issue by abiemann** [xbmc/xbmc#18762]
### Describe the bug

- Installed kodi-18.9-Leia-x64 on Windows 10.
- When viewing list of movies and sorting by play count, the ratings seem to be shown instead - it seems the developer that implemented this feature mixed up Rating & Play Count

## Expected Behavior

I expect Kodi to show "0" for unwatched movies, and everything else 1+

## Actual Behavior

Kodi shows the rating of the video instead. The sorting is also non-functional.

### To Reproduce

1. install kodi
2. scan your library
3. access your movies list
4. move mouse pointer to left side of screen to get options
5. set sorting option to "Play Count", ascending or descending.

### Debuglog

the problem can be observed on the UI

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://imgur.com/a/ggPeMRf
In the image above I highlighted what's important (and needed to censor what isn't)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: kodi-18.9-Leia-x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Sorry but I cannot replicate that issue. I cannot even think of a setting that would cause that.

Maybe a debuglog might reveal something. Capture you changing sort criteria and listing your movies.

(fyi- no-one cares what movies you have)

![playcount](https://user-images.githubusercontent.com/44626605/98736403-dd80cf00-23f8-11eb-999a-1de291ee26c0.jpg)

**Comment by ronie** [comment]
@KarellenX to reproduce, select 'Unwatched' instead of 'All Videos' on the side menu.

**Comment by KarellenX** [comment]
Thanks @ronie 

I can also confirm the issue when using Watched or Unwatched instead of All Videos
