### ISSUE TITLE
Multi-line MP3 tag display bug

### ISSUE THREAD

**Issue by xmha97** [xbmc/xbmc#18765]
Hi,
I'm Kodi v18.9 on Windows 10 (Microsoft Store edition).
There is the following bug when mp3 tags is multi-line:
![Kodi](https://user-images.githubusercontent.com/23485114/98744180-8104bc00-23c6-11eb-88a1-b044e5b04b2f.png)

You can download [a simple multi-line tagged MP3](https://github.com/xbmc/xbmc/files/5520700/Test.zip)
Or use Mp3tag app to tagging files:
![Mp3tag](https://user-images.githubusercontent.com/23485114/98744326-c3c69400-23c6-11eb-8fe0-33d9029074c3.png)

Thanks.

**Comment by KarellenX** [comment]
Same result using other skins

**Comment by DaveTBlake** [comment]
Not Kodi bug, Kodi is doing exactly what it should given the metadata provided. The problem @xmha97 is with your tagging.

The mp3 file has ID3v2.3 tag format tags, that format does not support multi-frame tag values. See https://id3.org/id3v2.3.0 The tag values are single strings, hence your example file has single album and albumartist tag values with new line characters in them, and so the skin correctly shows each string them over multiple lines. 

If you want to enter multiple albumartists (or artists) there are a number of things you can do:
a) use a format that does support multi-frame values e.g. ID3v2.4
b) use ID3v2.3 but enter separate names using an item separator, in Kodi this is " / " (note space-slash-space), and not new lines. e.g. "artist1 / artist2 / artist3"
c) use ID3v2.3 enter ALBUMARTIST value as a single line "artist1; artist2 feat. artist3" but also add and ALBUMARTISTS value  as a single line with default separator e.g. "artist1 / artist2 / artist3"
