### ISSUE TITLE
[Feature Request] Enhance Remote Controls' "Edit Text"

### ISSUE THREAD

**Issue by stdedos** [xbmc/xbmc#18773]
### Describe the Feature 
Here is a clear and concise description of what the problem is:

When editing text and using the remote controls (browser, app remote), it is impossible to modify the text that is already shown (or copy it).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Exit text control would accurately reflect the state of Kodi's textbox.

## Actual Behavior

Exit text control is empty, regardless of the state of Kodi's textbox.

## Possible Fix

Exit text control would be populated with the text of Kodi's textbox.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: _Leia latest release 2020.10.2x_

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by stdedos** [comment]
I believe the template is filled "well enough".

**Comment by KarellenX** [comment]
No it is not filled "well enough". I have no idea what you are referring to. What text are you copying? What screen? Provide a screenshot.

**Comment by stdedos** [comment]
![20201113_090320](https://user-images.githubusercontent.com/133706/99039139-78131680-258f-11eb-8936-5c694026b8bf.jpg)
![Screenshot_20201113-090306_Kore](https://user-images.githubusercontent.com/133706/99039148-7a757080-258f-11eb-80c9-08833b062c51.jpg)

**Comment by KarellenX** [comment]
Sorry, I just noticed this is a Feature Request. We don't accept Feature Requests here as this section is for bug reports only.

It is also submitted to the wrong repo. You will need to contact the Kore developer with your request.
https://github.com/xbmc/Kore

**Comment by stdedos** [comment]
The same thing happens with the HTTP remote control.

I think that Kodi first needs to enhance the API used, then maybe the handlers can start using it.
