### ISSUE TITLE
Full subtitle instead of forced subtitle

### ISSUE THREAD

**Issue by RomainD2** [xbmc/xbmc#18781]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hi,

I am using kodi with automatic settings for English audio and French subtitle. However, when there are two French subtitle, the full one and the forced one, the default is the forced subtitle which doesn't contain all texts...

Do you have any idea how to solve that?

Thankw

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix

Maybe the ability to select forced or full subtitle? 

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please use the forum at https://forum.kodi.tv/ for support. Github is for bug reports only.
