### ISSUE TITLE
Most PPA packages are broken

### ISSUE THREAD

**Issue by prkcorp** [xbmc/xbmc#18791]
### Describe the bug
Here is a clear and concise description of what the problem is:

On official Kodi PPA https://launchpad.net/~team-xbmc/+archive/ppa most packages are broken for Ubuntu Focal and Bionic because of build failures.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Most of packages available on PPA, at least for latest Ubuntu LTS (Focal)

## Actual Behavior

For example in focal serie there are only six packages built for pattern "kodi-game-libretro-*" out of 63 advertised by PPA. 

### To Reproduce

1. Add Kodi PPA to Ubuntu 20.04.1 Focal system according to wiki
2. apt update ; apt search kodi
3. Compare with package list from https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=published&field.series_filter=focal
4. See that most "kodi-game-libretro-*" packages are unavailable

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/2135532/99157613-b82ae400-26ca-11eb-8f0e-d1d9107609d6.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu Focal 20.04.1 LTS amd64
 - Kodi version: 18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
are you specifically looking for the kodi-game add-ons? Most of the non game add-ons built successfully

**Comment by prkcorp** [comment]
Yes, I was trying to add a lot of libretro integrations to a new kodi installation.

**Comment by lrusak** [comment]
I'm including @garbear to see if he knows about the game add-ons ppa builds

**Comment by malard** [comment]
closing as no-one is maintaining this
