### ISSUE TITLE
High CPU usage when playing audio or music, even when paused

### ISSUE THREAD

**Issue by lameventanas** [xbmc/xbmc#18798]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing any media (audio/video), from any source (local/stream), CPU usage jumps to 100%.
Even when pausing, CPU remains at 100%.
After stopping, CPU usage goes back to normal levels.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Normal CPU usage, especially when paused.

## Actual Behavior

High CPU usage, even when paused.

### To Reproduce

1. Start kodi
2. Reproduce any media: audio or video
3. Play video, CPU usage goes to 100%
4. Pause
5. CPU usage remains at 100%

### Debuglog

The debuglog can be found here:
[kodi.log](http://103.19.38.115/kodi.log)

In this log file I play a youtube video, then pause it, then stop it.

Play timestamp:
2020-11-17 01:13:26.626 T:140103256581888

Pause timestamp:
2020-11-17 01:13:42.938 T:140103256581888

Stop timestamp:
2020-11-17 01:13:56.866 T:140103256581888

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux 5.9.8 CRUX distribution
 - Kodi version: 18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
2020-11-17 01:11:53.594 T:140103265001408  NOTICE: GL_VENDOR = Mesa/X.org
2020-11-17 01:11:53.594 T:140103265001408  NOTICE: GL_RENDERER = llvmpipe (LLVM 10.0.0, 128 bits)
2020-11-17 01:11:53.594 T:140103265001408  NOTICE: GL_VERSION = 3.1 Mesa 20.2.2

^^ You are using SW Rendering. Means the kodi GUI is fully CPU driven. Your hardware is not supported by kodi anymore.

**Comment by lameventanas** [comment]
Thanks for spotting this.

I disabled acceleration by accident while trying to solve [this](https://drive.google.com/file/d/15EVdUFpbmQa5qH8pc1_uAvpVN7tEvBX_/view?usp=sharing).
[This](https://drive.google.com/file/d/1Ql9MYVkeqz2svUC7qx8PMno9RjDNVRBo/view?usp=sharing) is the corresponding log.

There is a problem when browsing or displaying OSD over the video.
It was shot at 1920x1080 @ 60 fps.

**Comment by lameventanas** [comment]
After downgrading the kernel from 5.9.8 to 5.8.18, the flickering is gone.
So the flickering is not caused by kodi.

However, when using software rendering, why is the CPU stuck at 100% when playing music, or when the video is paused?
Can't it be fixed?

**Comment by DaVukovic** [comment]
I guess that was answered before by @fritsch 
And I also guess that nearly noone has interest in fixing anything for a 12 yo CPU. Even a RPi is more capable than this thing.

**Comment by lameventanas** [comment]
Regardless, if the CPU is at 100% when music playing is paused and there is nothing showing on the screen that could explain it, not even a visualization, it must be a bug.

This CPU is not the fastest by today's standards, but it's definitely more powerful than a Raspberry's.
It would probably have a high CPU usage even if it was faster, I think what triggers this is using software rendering.

This is easy to find out, just switch Xorg to use Mesa's software rendering, play anything, then pause.

**Comment by arnova** [comment]
Most likely an issue with vsync icw your videocard's driver. Again not much we can do about it...
