### ISSUE TITLE
[Fix included] The Movie Database Scraper Library - ISO 639-1 code issue

### ISSUE THREAD

**Issue by andidrea** [xbmc/xbmc#18792]
### Describe the bug
Here is a clear and concise description of what the problem is:

I updated the Movie Database Scraper Library to the newest version (v 3.2.10). 

When going to Settings > Media > Library > Videos > Right click on a source > Change content > Preferred language > Selecting the German language "de" delivers English "en" results when updating a movie.

-> Selecting "da" for Danish updates e.g. the movie description in Danish as expected.
-> Selecting "el" for Greek updates e.g. the movie description in Greek as expected.

Selecting "de" does not(!) update e.g. the movie description in German when updating a movie.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Selecting "de" should update e.g. the movie description with German text when updating a movie.

## Actual Behavior

Selecting "de" updates e.g. the movie description with English text when updating a movie. However "da" or "el" work as expected.

## Possible Fix

You can get the exact result in German using a specific ISO 639-1 code:
https://api.tmdb.org/3/movie/484641?api_key=f090bb54758cabf231fb605d3e3e0468&language=de-DE

More information: 
https://developers.themoviedb.org/3/getting-started/languages

### To Reproduce

1. Go to Settings > Media > Library > Videos > Right click on a source > Change content > Preferred language > Select the German language "de" 
2. Update a movie under the source
3. Read movie information

### Debuglog

The debuglog can be found here:
Calling the following URL gives a default English result because the parameter "language=de" is not correctly handled by api.tmdb.org:
https://api.tmdb.org/3/movie/484641?api_key=f090bb54758cabf231fb605d3e3e0468&language=de

Languages that api.tmdb.org doesn't "find" gives English default results e.g.:
https://api.tmdb.org/3/movie/484641?api_key=f090bb54758cabf231fb605d3e3e0468&language=blabla

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.8

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by andidrea** [comment]
Please remove the tag "ignored rules".

The bug and fix are very specific.

**Comment by enen92** [comment]
@andidrea thanks for the bug report. I wonder if this should be tracked here or is in fact a bug (or improvement) in the tmdb scrapper addon

**Comment by andidrea** [comment]
Thank you for your answer.

I wasn't sure where to find the correct tmdb scrapper addon github. Sorry.

If you could kindly provide I'll post it over there and we can close the issue here.

Thank you in advance

**Comment by enen92** [comment]
It depends if you're using the xml scrapper or the python one. As you didn't provide a log file, no one can know for sure... except you :)

**Comment by andidrea** [comment]
[kodi.old.log](https://github.com/xbmc/xbmc/files/5542495/kodi.old.log)

Sorry here's the file.

**Comment by andidrea** [comment]
Good news it's working again.

I opened a ticket at at the api tmdb website and the URL returns the correct language:
https://api.tmdb.org/3/movie/484641?api_key=f090bb54758cabf231fb605d3e3e0468&language=de

I'm not sure if my ticket was the reason because no one replied yet.

It's probably still a good idea to change "language=de" to "language=de-DE" because it works for Germany, Austria and Switzerland.

Anyway thank you very much for your help so far.

**Comment by enen92** [comment]
thanks for letting us know :)
