### ISSUE TITLE
Kodi 18.9 crashing when playing any video

### ISSUE THREAD

**Issue by MitchellCash** [xbmc/xbmc#18804]
### Describe the bug

Every time I play a video (any video) Kodi crashes. Only started happening since upgrading to 18.9. Around this time I also ran some Windows updates. So either could be the cause. I have tried a basic reinstall, but not a full clean slate and start again as that will be my last option and just wanted to raise the bug in case it is something that needs fixing.

### Expected Behavior

The video plays.

### Actual Behavior

Kodi crashes.

### To Reproduce

1. Open Kodi
2. Select video to play
3. Kodi crashes

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/obuqaluzor.kodi

[kodi_crashlog-18.9 Git_20201023-0655c2c718-20201117-200051.dmp.zip](https://github.com/xbmc/xbmc/files/5555992/kodi_crashlog-18.9.Git_20201023-0655c2c718-20201117-200051.dmp.zip)

### Your Environment

Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 **Operating system version/name:** Windows 10 Version 20H2 (Build 19042.630)
 **Kodi version:** 18.9

If you need any more info let me know!

**Comment by KarellenX** [comment]
@MitchellCash 

I have closed your bug report as it is most likely an issue with your own setup. I couldn't tell much from the log as you did not enable Debug mode.

Head over to the forum and post your question there with a proper debug log. Also tell us what GFX card you are using as I note you are set to 3840x2160 resolution which could cause issues if you are using an older GFX card from pre 4k.

**Comment by MitchellCash** [comment]
@KarellenX apologies I had debug mode enabled at some point and must have provided the wrong logs. Either way not a problem will head to the forum if I still have issues after I start with a fresh Kodi install and see what comes of that.

**Comment by MitchellCash** [comment]
@KarellenX just to close this one off in case there is a way for Kodi to handle this issue more gracefully.

The issue with Kodi crashing was because the NAS box with my videos had run out of storage. Of course the root cause of the problem is my drives being out of space, however, instead of Kodi handling this gracefully it would crash when I attempted to play a video.

If there's any extra info I can give to you if this is something the team thinks should be handled please let me know.

**Comment by KarellenX** [comment]
Yes, anything that causes to ungracefully crash is something that needs to be looked at.

If you can provide those logs with debug mode enabled that captures you playing something and then crashing, it would be a good start.

Post it here, and we might re-open the issue. Thanks.
