### ISSUE TITLE
 Screensavers and visualizations not working on Leia linux opengl-es

### ISSUE THREAD

**Issue by teacupx** [xbmc/xbmc#18808]
### Describe the bug
Hello. I compiled Kodi 18.9 on Linux, Debian Buster, on different ARM single board computers, namely Asus Tinker Board, Rockpi 4b, Odroid XU4, etc.. Everything works perfect, with OpenGLES+GBM. I am using the ARM mali libraries for acceleration. i am keeping my progress in this fork: https://github.com/teacupx/xbmc

The problem is that I also compiled the binary addons, but all the addons that require GLES rendering don't work. That includes screensavers and visualizations. When I try to start any screensaver or visualization, I get this message in the logs:

`2020-11-17 19:36:54.491 T:547910407792   ERROR: AddOnLog: Pyro: CVertexShader::Compile: 0:1: P0007: Language version '150' unknown, this compiler only supports up to version '320 es'`
`2020-11-17 19:36:54.491 T:547910407792   ERROR: AddOnLog: Pyro: GL: Error compiling vertex shader`

## Expected Behavior
It should use OpenGLES for rendering, but according to that message, it looks like it is trying to use regular OpenGL instead.

## Actual Behavior
As a result, I only get a black screen, or no visualization at all (the Kodi UI simply stays the same).

## Possible Fix
Is there any way of telling the addons to compile for GLES instead of GL, at compile time? I could not find any documentation about it.

### To Reproduce
1. Start Kodi on an ARM device with Linux GBM+GLES, and binary addons compiled using the instructions from Github page
2. Try to use any screensaver or visualization
3. It won't work.

### Debuglog

The debuglog can be found here:
https://pastebin.com/86dZvSdK

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Leia 18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
Huh, I guess the Mali drivers are more strict when it comes to the version string at the begin of a shader. 

Kodi's binary add-on shader should support both GL and GLES, as (usually) none of the more advanced features are used.

I guess the add-ons have to set the version when assembling the shader.

**Comment by teacupx** [comment]
As a matter of fact, the addon has a subfolder called "shaders", with two subfolders in it, named "GL" and "GLES". The .glsl file inside the GL folder starts with "#version 150", while the file in the "GLES" folder starts with "#version 100".

Therefore, it seems like Kodi is choosing the GL shader, instead of the GLES. Notice that the log says "language version 150", and also the error message says "GL: Error compiling vertex shader", instead of "GLES: Error compiling...".

So the bug here seems to be that Kodi is choosing the wrong shader, for some reason.

**Comment by lrusak** [comment]
You need to specify `-DAPP_RENDER_SYSTEM=gles` as part of your cmake command

**Comment by sarbes** [comment]
Then ignore my comment :)

**Comment by teacupx** [comment]
> You need to specify `-DAPP_RENDER_SYSTEM=gles` as part of your cmake command

You mean when compiling Kodi, correct? Because, when I compile the addons, I follow [the official instructions](https://github.com/teacupx/xbmc/blob/Armbian-Leia-xu4-x11/docs/README.Android.md#6-build-binary-add-ons), that don't use a cmake command but a simple "make" instead.

**Comment by lrusak** [comment]
> > You need to specify `-DAPP_RENDER_SYSTEM=gles` as part of your cmake command
> 
> You mean when compiling Kodi, correct? Because, when I compile the addons, I follow [the official instructions](https://github.com/teacupx/xbmc/blob/Armbian-Leia-xu4-x11/docs/README.Android.md#6-build-binary-add-ons), that don't use a cmake command but a simple "make" instead.

Yes as the add-on is dependent on how kodi was build. The add-on will look for the KodiConfig.cmake file and use the `APP_RENDER_SYSTEM` defined there.

see:
https://github.com/xbmc/xbmc/blob/ca77237298680de255238b997d612bacf58d5d9f/cmake/KodiConfig.cmake.in#L20

**Comment by lrusak** [comment]
On another note you don't need to build the binary add-ons inside the kodi build system. You can build them separately like how LibreELEC does it.

**Comment by teacupx** [comment]
> Yes as the add-on is dependent on how kodi was built. The add-on will look for the KodiConfig.cmake file and use the `APP_RENDER_SYSTEM` defined there.

Okay, I see that, after building Kodi with `-DAPP_RENDER_SYSTEM=gles`, I get a KodiConfig.cmake with the line
`set(APP_RENDER_SYSTEM gles)`

That file gets installed to the prefix, under `share/kodi/cmake/`. I assumed the addon build system would get it from there, but it does not. Instead, it creates a different file in `xbmc/tools/depends/target/binary-addons/native/build/depends/lib/kodi/KodiConfig.cmake`

That other KodiConfig.cmake has no definition for `APP_RENDER_SYSTEM` (it defines it as blank), and hence the addons are not built for gles.

How can I make the addon compile system get the proper KodiConfig.cmake, generated when I built Kodi? Where do I need to put it?

-----------------------
For clarifiication, I am using the method for building addons described in the documentation:
`make -j$(nproc --all) -C tools/depends/target/binary-addons PREFIX=my-build-dir/usr/local`

And I am placing the KodiConfig.cmake with the right definitions in this directory:
`my-build-dir/usr/local/share/kodi/cmake/`

**Comment by teacupx** [comment]
**SOLVED**
Solved it by using the following command line to compile the addons:
`make -j$(nproc --all) -C tools/depends/target/binary-addons PREFIX=$(pwd)/../kodi-build/bin-addons/usr/local EXTRA_CMAKE_ARGS="-DAPP_RENDER_SYSTEM=gles"`

**Comment by teacupx** [comment]
As a suggestion, you may want to add that option to the documentation. I can make a PR if it is OK with you.

**Comment by lrusak** [comment]
> That file gets installed to the prefix, under `share/kodi/cmake/`. I assumed the addon build system would get it from there, but it does not. Instead, it creates a different file in `xbmc/tools/depends/target/binary-addons/native/build/depends/lib/kodi/KodiConfig.cmake`
> 
> That other KodiConfig.cmake has no definition for `APP_RENDER_SYSTEM` (it defines it as blank), and hence the addons are not built for gles.
> 

if it doesn't contain APP_RENDER_SYSTEM then you need to make sure you regenerate

```
$ grep APP_RENDER_SYSTEM tools/depends/target/binary-addons/aarch64-linux-android-21-debug/build/depends/lib/kodi/KodiConfig.cmake
set(APP_RENDER_SYSTEM gles)
```

Likely you need to reconfigure depends. `./configure --with-rendersystem=gles`
