### ISSUE TITLE
Open iOS keyboard crash Kodi

### ISSUE THREAD

**Issue by sy6sy2** [xbmc/xbmc#18815]
### Describe the bug
Here is a clear and concise description of what the problem is:

When you want to add a new Kodi user profile Kodi just crash.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No crash.

## Actual Behavior

Kodi just crash.

## Possible Fix

Don't know.

### To Reproduce

1. Open Kodi on iOS
2. Go to Settings --> Profiles
3. Click on "Add profile..."
4. Kodi crash

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/usukuyaviv.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Only tested on a jailbroken device in no-sandboxed mode.

### Your Environment
Used Operating system:

 - [ ] Android
 - [X] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: iOS 14.2, iPhone 7
 - Kodi version: 19 beta 1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by kambala-decapitator** [comment]
FYI not reproducible with sideloaded build 20201026-0e922f94e6 (says alpha 2), tested on iPhone 6+ iOS 12.4.8

**Comment by sy6sy2** [comment]
Thank you for your test. 
I can reproduce the issue with 19 alpha 2 but the problem is not present with 18.9. 
Both test in no-sandboxed mode. 
I will check iOS log later.

**Comment by sy6sy2** [comment]
Actually Kodi crash each time Kodi want to reveal the keyboard with `*** Assertion failure in -[UIKeyboardTaskQueue performSingleTask:], UIKeyboardTaskQueue.m:501` 😕 

Full log: https://paste.kodi.tv/rorocoxoko.kodi

Still a new issue with jailbreak... pfff

**Comment by kambala-decapitator** [comment]
reproducible on iPad with iOS 14.2

**Comment by sy6sy2** [comment]
So it's not a jailbreak related issue 🥳 😛

**Comment by kambala-decapitator** [comment]
might be... But b1 works great on iOS 12 as well. Looks something related to iOS 14 (or 14.2).

**Comment by kambala-decapitator** [comment]
opened PR that fixes the crash
