### ISSUE TITLE
Kodi 19 Beta 1 - Inputstream Adaptive Missing

### ISSUE THREAD

**Issue by berkhornet** [xbmc/xbmc#18821]
### Describe the bug
Here is a clear and concise description of what the problem is:

After installing Kodi 19 Beta 1, the Inputstream Adaptive addon was disabled. No update was available and I found that the addon was missing from the Kodi repository. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Addon should be available for installation. 

## Actual Behavior

Addon is not available for installation. 

## Possible Fix

Not applicable. 

### To Reproduce

1.  Install Kodi 19 Beta 1
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 20H2
 - Kodi version: Kodi 19 Beta 1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Known issue, change is required in IA, not core, so closing this
