### ISSUE TITLE
Error: module 'os' has no attribute 'waitpid' with Kodi 19 on tvOS 14

### ISSUE THREAD

**Issue by jhays** [xbmc/xbmc#18820]
### Describe the bug
Here is a clear and concise description of what the problem is:

Attempting to launch a plugin (plugin.video.pseudotv.live) is failing, with an error printing to the kodi log that states: 
"module 'os' has no attribute 'waitpid'"

The plugin developer has suggested that I file a bug here to seek help with this issue. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

"waitpid" should be available via python on tvOS, and this plugin using it (PseudoTV) should launch successfully.

## Actual Behavior

Attempting to import for waitpid results in a plugin crash when launched. 

### To Reproduce

1. Install Kodi 19 beta on tvOS 14+
2. Install PseudoTV Live
3. Attempt to launch PseudoTV Live, observe error alert / log message.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/aseyuxuxed.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: tvOS 14.2
 - Kodi version: 19 beta1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
likely it's because tvos doesn't have the ability to `fork` a process.

**Comment by jhays** [comment]
I see, thanks for the info. That likely means no hope for using this plugin via Kodi on tvOS. Guess I'll have to keep working on my own native app for that platform...

**Comment by fuzzard** [comment]
I'll leave this open. I'm looking into something

**Comment by fuzzard** [comment]
#18839 should fix the waitpid error, however looking at a glance (ive no idea how the addon works) theres a lot of logging around threading. So no idea if you will get any further with the addon.
