### ISSUE TITLE
Matrix Beta 1 - Movie/Episode Title and Media Information of STRM files do not display in the Video Player

### ISSUE THREAD

**Issue by driva5** [xbmc/xbmc#18847]
The video player displays the STRM filename as the title instead of the title of the movie or Episode associated with the STRM file. Additionally, media information is blank in the video player. This issue began since the Beta version of Matrix. In the alpha builds and Kodi Leia this isn't an issue.

**Comment by enen92** [comment]
Debug log is missing. Please provide one.
What's the content of the strm file?

**Comment by driva5** [comment]
> Debug log is missing. Please provide one.
> What's the content of the strm file?

Movies/episodes with the file path in the STRM. IE C:\Users\matt\Videos\vid.mp4

Matrix Alpha 3
https://paste.kodi.tv/obofekosap.kodi

Matrix Beta 1
https://paste.kodi.tv/nanisebiha.kodi

**Comment by Acidzero2020** [comment]
pls try a nightly.
I think it's already fixed

**Comment by enen92** [comment]
I am not able to replicate this. I get the exact same behaviour since leia.
Please test the latest nightly, it might have been a regression caused by https://github.com/xbmc/xbmc/pull/18770 later reverted in https://github.com/xbmc/xbmc/pull/18851

**Comment by driva5** [comment]
Yep, latest nightly seems to have fixed the issue, thanks.
