### ISSUE TITLE
Not decoding some EIA-608 closed caption characters

### ISSUE THREAD

**Issue by jefflessard** [xbmc/xbmc#18845]
### Describe the bug
Here is a clear and concise description of what the problem is:

EIA-608 closed caption decoding skips some characters due to an invalid condition check.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Standard characters such as latin e acute "é" should be present in decoded closed captions

## Actual Behavior

Some valid characters such as e acute are not decoded

## Possible Fix

https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c

Line 492 of the cc_decode_EIA608 function should be reviewed to match the comment of line 493

I.e.  the condition "if (c1 & 0x60)" is invalid as the range "0x20 <= c1 <= 0x7f" does not always correspond to bits 0b0110000.

Consequently, the function cc_decode_standard_char should be reviewed as it implies the same erroneous condition check.

More details on EIA-608 closed caption encoding can be found at 
http://www.theneitherworld.com/mcpoodle/SCC_TOOLS/DOCS/CC_CHARS.HTML

### To Reproduce

1. Play PVR video (live or recording) that has EIA-608 closed captions

### Debuglog

The debuglog can be found here:
No debug log corresponding to that issue

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
If you can provide a sample, it would be greatly appreciated.

**Comment by jefflessard** [comment]
Here is a short sample video :
https://drive.google.com/file/d/1eYIZEjCFJ01SfVnEvlMPWJrE-0mRsmK9/view?usp=drivesdk

What you see in KODI:
![20201122_192844~2](https://user-images.githubusercontent.com/25519099/99921621-85e83a80-2cf9-11eb-81c3-5cc3abf38632.jpg)

What you see in VLC
![20201122_193029](https://user-images.githubusercontent.com/25519099/99921629-91d3fc80-2cf9-11eb-8048-95bc6ed1e9ed.jpg)
