### ISSUE TITLE
[UWP] Matrix Windows UWP crashes on startup (partial solution)

### ISSUE THREAD

**Issue by djp952** [xbmc/xbmc#18846]
### Describe the bug
Now that Matrix .msix UWP build(s) have become available for use, I found that they just crash on startup due to compatibility problems with Python 3.  I spent some time looking into this and would like to report what I've found so that somebody more qualified to solve it can hopefully pick it up and run with it and prevent these platform(s) from dying out.

## Expected Behavior
Kodi should launch on Windows UWP via the new .MSIX package(s) and at least get the user to the home screen without dying.

## Actual Behavior
Kodi will crash on Windows UWP platforms when run via the .MSIX package(s) available via the nightlies due to compatibility problems.

## Possible Fix
This is why I'm opening this Issue; I was able to get Kodi to be "generally functional" on UWP by making some modifications to the underlying Python build.  It's not expected to be a complete solution by any means, but it does get Kodi UWP to launch on Windows UWP (x64) and hopefully move these concern(s) forward. My goal is that someone that knows how Python is being built for Windows UWP might be able to make/submit a proper patch to the Python 3.x code and deal with the remaining issues on their own.  My **ONLY** intention here was to get to Kodi UWP to launch without crashing, it's not intended to be a complete/ideal solution.

What I found was that if the Python code was set to a minimum version of Windows 8 and added a runtime check to determine if the running application is a UWP application or a Win32 application when trying to load dynamic link libraries, Kodi will, at a minimum, get to point where it launches and functions.  Note that I am not able to test on any UWP platforms other than Desktop UWP x64 at this time.

Using cpython v3.8.5 (https://github.com/python/cpython), I only had to modify two files:

- PC/pyconfig.h
- Python/dynload_win.c

**PC/pyconfig.h ORIGINAL**:
```
/* set the version macros for the windows headers */
/* Python 3.5+ requires Windows Vista or greater */
#define Py_WINVER 0x0600 /* _WIN32_WINNT_VISTA */
#define Py_NTDDI NTDDI_VISTA
```

**PC/pyconfig.h MODIFIED**:
```
/* set the version macros for the windows headers */
/* Python 3.5+ requires Windows 8 or greater */
#define Py_WINVER 0x0602 /* _WIN32_WINNT_WIN8 */
#define Py_NTDDI NTDDI_WIN8
```

**Python/dynload_win.c ORIGINAL**
```
        hDLL = LoadLibraryExW(wpathname, NULL,
                              LOAD_LIBRARY_SEARCH_DEFAULT_DIRS |
                              LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR);
```
**Python/dynload_win.c MODIFIED**
```
        #include <appmodel.h>
        ...
        hDLL = LoadPackagedLibrary(wpathname, 0);
        if((hDLL == NULL) && (GetLastError() == APPMODEL_ERROR_NO_PACKAGE))
            hDLL = LoadLibraryExW(wpathname, NULL,
                                  LOAD_LIBRARY_SEARCH_DEFAULT_DIRS |
                                  LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR);
```
(this change should favor Win32 rather than UWP, as in try LoadLibraryEx() first, then LoadPackagedLibrary(); this is just for illustration)

**edited** to remove unimportant output file name changes to match Kodi; that would be figured out easily enough and made it look way more complicated than it is.

### To Reproduce
1. Install a Kodi .MSIX package on Windows from the Matrix "nightlies"
2. Kodi will not launch due to an exception attempting to load a Python .pyd module

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/lulifeseva.kodi
NOTE: Log is not with debugging enabled, Kodi does not launch to enable that.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [X] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by djp952** [comment]
If someone can point me in the right direction as to how the Windows dependency builds are formally generated/patched, I am fine with submitting something to get you this far.  I know little to nothing about Python and won't be able to do much for the subsequent problems that still occur, though.

If the best course of action for Kodi is to submit a patch to Python, I don't think it will get very far since it needs to change the base Windows target version to work, but am also willing to try that route; perhaps they would accept a UWP-specific change to "PCBuild" -- they do already have a UWP project for the Python shell application.

While I would greatly prefer not going much farther on this myself, and I realize that UWP in and of itself is a dying platform (thankfully!), it looks like XBox Series X|S will still require a UWP/store version of Kodi...

Let me know; happy to help to whatever point I am capable of helping.

**Comment by fuzzard** [comment]
@Paxxi is the best point for that question I believe

**Comment by Paxxi** [comment]
This is an excellent analysis, Thank you! 😄 

We have our own build of cpython with various patches for UWP at https://github.com/Paxxi/cpython/blob/e7d0085c92747cf41af968b8e8f1c3dc4c5e1ae4/Python/dynload_win.c#L224

There is a fix there for UWP but it's probably wrong in some way since you see this issue happening.
We build it through https://github.com/xbmc/kodi-deps which contains some helper scripts and manages dependencies but it's not super user-friendly.

I'll try and look into it, probably this weekend. If you want to try and patch our cpython version you're more than welcome to.

**Comment by djp952** [comment]
Thank you!  While I was unable to get (https://github.com/Paxxi/cpython) to build; I did note three instances where the MS_DESKTOP #define was misspelled and submitted a PR for you on that.  Actually getting this dependency to build is apparently voodoo as noted, but I see nothing wrong with the existing patch(es) that are in place from what I found.

My guess at this point is that the Kodi "win10" (store app) build for Python ultimately ends up being the same as the Desktop build, targeting the Windows Desktop API in error, due to WINAPI_FAMILY not being set up properly in advance.

I am sorry I could not get the kodi-deps code to build for me, I had hoped to give you more information or some indication of "that worked!!", but static analysis and educated guesses are sending me to "these DLLs are regular Win32 ones".

Thank you for any and all attention  paid to this matter, and I am perfectly willing to test anything you need tested as long as I have the proper hardware to use...

**Comment by Paxxi** [comment]
The depends build system isn't super user friendly, not sure anyone has really used it except for me lately so it could probably use some work to simplify it, especially the required tooling.

I found the issue. There's no threadstate available when that method get called during init which causes it to call abort. Python 3 introduced a better way to do it using Py_GetProgramFullPath so I changed to that instead and it seems to work.

Here's the fix https://github.com/Paxxi/cpython/commit/05addeb321dcd7e190ad610d9d1f364101bf0767 . I also merged your PR, thank you 😄 

If you can test the fix that would be great.

**Comment by djp952** [comment]
Absolutely!  Is there a way to get a copy of the compiled UWP x64 binaries? That's how I tested before, I built my own from source and just replaced them in the dependency tree before building Kodi.  I can provide a location to put them if needed.  Thank you so much!

**Comment by fuzzard** [comment]
Windows dependency binaries are all located at http://mirrors.kodi.tv/build-deps/win32/
Just find the matching version number from the changes in this PR

**Comment by djp952** [comment]
Thanks @fuzzard.  On it.

**Comment by djp952** [comment]
Having a new problem with this build; it's crashing out here, prior to getting into dynload_win.c for anything:

https://github.com/Paxxi/cpython/blob/05addeb321dcd7e190ad610d9d1f364101bf0767/Python/pylifecycle.c#L949-L953

```
    PyThreadState *tstate = _PyRuntimeState_GetThreadState(runtime);
    status = _PyUnicode_InitEncodings(tstate);
    if (_PyStatus_EXCEPTION(status)) {
        return status;
    }
```

It's a bit of a rabbit hole, but it's downstream of _PyUnicode_InitEncodings.  I'll continue to dig in later and post what I find to be the point where it's erroring out.

**Comment by Paxxi** [comment]
The change to Py_SetHome in the PR fixes the encodings issue. I had to fix that to get to the issue you reported 😀

**Comment by djp952** [comment]
Apologies, I missed the associated PR for the environment variable removal.  Can confirm that it works as expected after merging that as well -- THANK YOU!

I'd also like to say I think you've done a fantastic job getting Python 3 to work in UWP; that was most decidedly non-trivial to pull off.

**Comment by Paxxi** [comment]
Excellent, thank you 😄
