### ISSUE TITLE
Kodi 18.9 on Windows 10 crashes when browsing http

### ISSUE THREAD

**Issue by colemar** [xbmc/xbmc#18843]
### Describe the bug
Here is a clear and concise description of what the problem is:

Immediate crash and exit when trying to open a video file from a http source.
Sometimes it happens just browsing the file list wihtout clicking any file.
It does not happen when browsing a local drive source.
It does not happen with Kodi 18.9 for Android browsing the same http source.
It did not happen before version 18.8.

### To Reproduce

1. create a http source
2. browse it
3. select any video file

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/rurasuvigi.kodi

Note that http://clmr.tk:80/zzzz/ is a redacted version of the real source.

### Crashlog, stacktrace
They can be found here:
https://drive.google.com/file/d/1nB7bCkXEnf5zcLy7WkJ9fz3XzL95S_BJ

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

Windows 10, kernel: Windows NT x86 64-bit version 10.0.18363

**Comment by colemar** [comment]
No news apparently.

Still happening on build 19.0.1.
I can attest it does happen on a PC with a Nvidia GeForce 1080 Ti graphic adapted, does not happen on another PC with Intel built in graphics.

**Comment by malard** [comment]
closing as windows 10 is EOL and so is the Kodi version in question, if its still a live issue, please re-open

**Comment by colemar** [comment]
Apparently the issue disappeared. Pehaps because I updated Kodi to version 20.0.0, perhaps because the remote folders content is changed, perhaps because I did a Windows in-place upgrade.
