### ISSUE TITLE
Github Releases: Set latest release back to 18.9-Leia

### ISSUE THREAD

**Issue by stelas** [xbmc/xbmc#18844]
Latest release should point to the latest stable release, actual 18.9-Leia.
Please correct that...

**Comment by fuzzard** [comment]
You're going to have to provide a lot more detail about what you are asking.

What exactly is pointing you where? Provide some links/info.

**Comment by sy6sy2** [comment]
If I understand correctly, @stelas taels about GitHub release tab.
ATM on GitHub our latest official release is "19.0b1Android-Matrix".
Shouldn't we just leave 18.9 as the latest release and only use pre-release GitHub feature for 19-beta1?

**Comment by DaveTBlake** [comment]
All v19 releases (alphs + beta) marked as "pre-release"
