### ISSUE TITLE
Matrix Plugin: Added Context Menu Items Fail To Execute

### ISSUE THREAD

**Issue by jmooremcc** [xbmc/xbmc#18855]
### Describe the bug
Here is a clear and concise description of what the problem is:

Adding a context menu item that executes a function defined in the plugin fails to execute when activated.

I modified the plugin.video.example plugin from the Kodi development website to add an "edit menu item" to the video item's context menu. I first tested it under Kodi Krypton (17.6) and it worked. I then ported the code to kodi-19.0-Matrix_beta1-x64 under Windows 10 and the context menu items I added do not execute. I know this is the case because I placed an xbmc.log() call inside the router function that prints the parameters received by the function. All other activations of the router function show the parameters received in the log file. When I click the added "Edit" context menu item, the log does not show any parameters thus indicating that the menu item never ran.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The plugin adds the following context menu items for the Animal category and for the Alligator:
12:57:22.084 T:1431303072   DEBUG: ***Adding Context Menu Item
12:57:22.084 T:1431303072   DEBUG: menu=[(Edit Crab Video,XBMC.RunPlugin(plugin://plugin.video.example/?action=edit&title=Crab))]
12:57:22.098 T:1945092096   DEBUG: CMMALRenderer::RenderUpdate - vsync 1036659 (+37)
12:57:22.201 T:1431303072   DEBUG: ***Adding Context Menu Item
12:57:22.202 T:1431303072   DEBUG: menu=[(Edit Alligator Video,XBMC.RunPlugin(plugin://plugin.video.example/?action=edit&title=Alligator))]
12:57:22.211 T:1945092096   DEBUG: CMMALRenderer::RenderUpdate - vsync 1036697 (+5)
12:57:22.314 T:1431303072   DEBUG: ***Adding Context Menu Item
12:57:22.316 T:1431303072   DEBUG: menu=[(Edit Turtle Video,XBMC.RunPlugin(plugin://plugin.video.example/?action=edit&title=Turtle))]
12:57:22.336 T:1945092096   DEBUG: CMMALRenderer::RenderUpdate - vsync 1036703 (+7)
12:57:22.441 T:1431303072    INFO: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.example/main.py): script successfully run

The added "edit" context menu item should execute and activate the xbmc.keyboard.
The log file should show the parameters associated with the menu item
12:57:36.465 T:1431303072   DEBUG: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.example/main.py): entering source directory /storage/.kodi/addons/plugin.video.example
12:57:36.465 T:1431303072   DEBUG: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.example/main.py): instantiating addon using automatically obtained id of "plugin.video.example" dependent on version 2.25.0 of the xbmc.python api
**12:57:36.592 T:1431303072   DEBUG: params={'action': 'edit', 'title': 'Alligator'}**
12:57:36.596 T:1945092096    INFO: Loading skin file: DialogKeyboard.xml, load type: KEEP_IN_MEMORY

## Actual Behavior

The context menu does happen correctly:
**2020-11-24 12:15:41.047 T:14604   DEBUG <general>: ***params={'action': 'listing', 'category': 'Animals'}**
2020-11-24 12:15:41.059 T:14604   DEBUG <general>: ***Adding Context Menu Item
2020-11-24 12:15:41.059 T:14604   DEBUG <general>: menu=[(Edit Crab Video,XBMC.RunPlugin(plugin://plugin.video.example/?action=edit&title=Crab))]
2020-11-24 12:15:41.060 T:14604   DEBUG <general>: ***Adding Context Menu Item
2020-11-24 12:15:41.060 T:14604   DEBUG <general>: menu=[(Edit Alligator Video,XBMC.RunPlugin(plugin://plugin.video.example/?action=edit&title=Alligator))]
2020-11-24 12:15:41.060 T:14604   DEBUG <general>: ***Adding Context Menu Item
2020-11-24 12:15:41.060 T:14604   DEBUG <general>: menu=[(Edit Turtle Video,XBMC.RunPlugin(plugin://plugin.video.example/?action=edit&title=Turtle))]
2020-11-24 12:15:41.060 T:14604    INFO <general>: CPythonInvoker(3, C:\Users\jmoor\AppData\Roaming\Kodi\addons\plugin.video.example\main.py): script successfully run

However, clicking on the "edit" context menu item does not activate the plugin and the router function is never executed so that it can print the params log entry and activate the xbmc.keyboard.

### To Reproduce

1. Add a context menu item that executes a plugin function
2. Execute the plugin and select the context menu item you added in step 1
3.

### Debuglog

The debuglog can be found here:
https://pastebin.com/embed_js/cHXB0HKY
The last successful execution of the router function is at 2020-11-24 12:15:41.047

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The source code for main.py for the plugin.video.example I modified can be found here:
https://pastebin.com/embed_js/CgMYaeAM

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
19.0 beta1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
not sure if it's the only issue with your code, but at least this line:
`cmd = 'XBMC.RunPlugin({})'.format(get_url(action='edit',title=video['name']))`
needs to be changed to:
`cmd = 'RunPlugin({})'.format(get_url(action='edit',title=video['name']))`

see: https://forum.kodi.tv/showthread.php?tid=344263&pid=2935397#pid2935397

**Comment by jmooremcc** [comment]
@ronie Your suggestion solved the problem. 
Thank you.
