### ISSUE TITLE
Libraryempty after migration to kodi 19 beta with distant database

### ISSUE THREAD

**Issue by moreje** [xbmc/xbmc#18864]
### Describe the bug
Here is a clear and concise description of what the problem is:

After upgrading to Kodi v19 beta for Android TV, the library is empty. I use a distant SQL DB correctly configured for Kodi v18.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

At first launch, there should be a database migration message, and kodi should start with filled library

## Actual Behavior

Migration database message is present, but library is empty
Myvideo119 is actually created in my SQL DB manager, seems to be filled with data, but it does not show up in kodi.
my kodi user has ALL_PRIVILEGES activated in SQL manager

### To Reproduce

1. First start of Kodi v19
2. wait for DB migration
3. Library empty message

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/asizekuwif.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: v19 beta

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Troox73** [comment]
Happens on Win64/Kodi 19b1 as well. Running a equal config with FireTV Cube + MariaDB. May be a MariaDB <-> SQL Problem? Please investigate :)

**Comment by DaveTBlake** [comment]
@Troox73 please provide a debug log of attempting to migrate to v19 from v18, otherwise it is just as likely you have some other issue with migration.

> Myvideo119 is actually created in my SQL DB manager, seems to be filled with data, but it does not show up in kodi.

Interesting @moreje , what about MyMusic82 can that be seen in SQL DB manager and does it contain data? 

This looks like some kind of permissions failure accessing your server via v19

**Comment by moreje** [comment]
I don't use music library, but it was created also..
My sql user had all privileges On, and the 119 library was actually created during migration, with data inside, but it did not show up in kodi

**Comment by Troox73** [comment]
Sure. Also available here https://forum.kodi.tv/showthread.php?tid=358922

https://paste.kodi.tv/atinocicul.kodi

**Comment by DaveTBlake** [comment]
Can both of you try as follows:
Log into mariadb as your kodi user and execute the following statement 
```
SELECT routine_name FROM information_schema.routines 
WHERE routine_type = 'FUNCTION' and routine_schema = 'MyMusic82';
```
and post the output from that.

**Comment by Troox73** [comment]
`root@120589eb4467:/# mysql -ukodi -p****
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 1074
Server version: 10.4.17-MariaDB-1:10.4.17+maria~bionic-log mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SELECT routine_name FROM information_schema.routines 
    -> WHERE routine_type = 'FUNCTION' and routine_schema = 'MyMusic82';
ERROR 1558 (HY000): Column count of mysql.proc is wrong. Expected 21, found 20. Created with MariaDB 100144, now running 100417. Please use mysql_upgrade to fix this error
MariaDB [(none)]>`

**Comment by Troox73** [comment]
I have no clue about MariaDB, but if i'm not totally wrong i should do that mysql_upgrade before i run Kodi19 first time?
So no "bug" but a MariaDB upgrade problem?

**Comment by DaveTBlake** [comment]
> So no "bug" but a MariaDB upgrade problem?

Yes I think so @Troox73 
Sort out MariaDB, drop the MyMusic82 and MyVideo116 schemas and then run v19 again which will repeat db migration and create these correctly. Check log to for success (or post a link if errors).

**Comment by Troox73** [comment]
yeah, after mysql_upgrade items show up with a fresh kodi start

https://paste.kodi.tv/jajowebifa.kodi

looks good, afaik. many thanks. i relink this to the kodi forum

**Comment by DaveTBlake** [comment]
Glad things are resolved for you @Troox73 , yes that log shows healthy db migration.

Will wait to hear back from @moreje before closing this issue.

**Comment by moreje** [comment]
Hello,
the "mysql_upgrade" step before migrating to v19 fixed the bug!
I also had to setup a psswd for my root user in MariaDB
Thank you for your help, now I'm testinb v19 :+1: 
you can close the issue :)
