### ISSUE TITLE
Playback Speed 

### ISSUE THREAD

**Issue by harsha20032020** [xbmc/xbmc#18872]
there should be a feature for increasing the playback speed,
sir i think it is an essential feature since most other video browser have that feature..
but since kodi is better than most video players i think there should be a new feature for increasing playback speed

this change will be important to myself and many people because most people these days watch video lectures and movies 
at an increased pace to save time

also ive been a huge follower of kodi but i dont have much coding experience so i cant fix bugs but if you want me to write or translate id be happy to help out an organisation

hope that this feature will be included in future versions.

**Comment by KarellenX** [comment]
@harsha20032020 

This area is for bug reporting. Not feature requests.

Regardless, that feature request is already available in Kodi and has been for many years. You can start off here...
https://forum.kodi.tv/showthread.php?tid=10023
