### ISSUE TITLE
please add a 'null' windowsystem for headless setup (just for scraping database)

### ISSUE THREAD

**Issue by succo69** [xbmc/xbmc#18880]
### Describe the bug

some times ago (actually last version i built was from 26 september) i used a patch to avoid rendering the gui and just start kodi in headless mode in my rpi just for scraping intent. I saw that the old patch doesn't apply anymore because now the windowsystem has a factory of its own and it's possible to specify the desired window manager at start, so could it be possible to add a new 'null' window manager so that the entire gui isn't rendered at all and the whole kodi runs headless (as it used to do before)? something as 
kodi --windowing=null

thanks

## Expected Behavior

start kodi without any interface

## Actual Behavior

kodi starts with full rendering and eating resources

### To Reproduce

1.
2.
3.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: after October 27, i guess

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please use the forum for feature requests.

I will say one thing. On RPi if you use the kms driver you can use gbm with the offscreen modesetting option to not have to have a gui running. If you are interested please ask in the forum.
