### ISSUE TITLE
When the display not support 25hz kodi no longer switches display at 50hz

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#18899]
### Describe the bug
Here is a clear and concise description of what the problem is:

When you play a video with 25fps and the display not support 25hz
kodi not switch the display to 50hz and keep it to 60hz.
This is working on Kodi 18.x and in old Kodi 19 nightly but not remember the build date

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When the display not support 25hz automatically choose the doubled hz (50hz)

## Actual Behavior

The screen hz not change and result in a bad video experience

### To Reproduce

1. Download the test video https://archive.org/download/VideoTestFiles/1920x108025FpsPhotoJpeg75.mp4
2. Turn on "Adjust display refresh rate" to "On start/Stop"
3. Play the video

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/yeliqefizi.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Kodi 19 current last build

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Use the whitelist and enable double refresh rates

**Comment by CastagnaIT** [comment]
should be by default this thing
now you must inform all kodi users that at each kodi install they will have to manually activate whitelist and also enable double refresh rates
what is the logical sense? before was automatic
in my opinion is a contradiction

**Comment by thexai** [comment]
As an observation, the system does support 25 Hz at 1920 x 1080 (desktop / Kodi GUI default).

In this case, it should switch to 1920 x1080 @ 25Hz without activating WHITELIST, right?

**Comment by fritsch** [comment]
Without setting (list empty): https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/Resolution.cpp#L116 they are kept out, why is documented here.

**Comment by lrusak** [comment]
> should be by default this thing
> now you must inform all kodi users that at each kodi install they will have to manually activate whitelist and also enable double refresh rates
> what is the logical sense? before was automatic
> in my opinion is a contradiction

If it was working before then you were probably already using the whitelist (as @fritsch inadvertently points out). We have just made it an option now that users have to opt in if they want the whitelist to use double refresh rates and 3:2 pull down refresh rates.

**Comment by CastagnaIT** [comment]
> If it was working before then you were probably already using the whitelist

the whitelist option was always disabled, my tests was done on kodi 18, an old kodi 19 build, and last kodi 19 nightly
I noticed this only today, because i usually play videos at 23~ or 50fps/hz

i didn't know about this problem it could be boring for other users too,
if i enable the whitelist and enable double refresh rates as suggested, it works good like the old kodi versions

@thexai i do not know why 25hz is listed perhaps the AVAmplifier is the cause
with the others resolutions (without whitelist enabled) i do not have problems, so
eg. if i play a video at 23~fps kodi switch the display correctly at 23~hz

**Comment by CastagnaIT** [comment]
@thexai if it can help you these are the freq avaiable at 1080p:
![image](https://user-images.githubusercontent.com/3257156/101206510-85439280-366f-11eb-82ae-17a696b2633f.png)
but if i try to set the desktop at 25-interlaced the tv switch to 50hz (i never used interlaced)

**Comment by thexai** [comment]
@CastagnaIT: It seems that your system does not support 25 Hz progressive, only 25 Hz interlaced. So it makes sense that you have to check double refresh rate.

In my case, I have tried to play a 1920 x 1080**p** 25 fps source and since my system supports progressive 25 Hz, I don't need to use double refresh rate:

```
INFO <general>: [WHITELIST] Searching the whitelist for: width: 1920, height: 1080, fps: 25.000, 3D: false
INFO <general>: Display resolution ADJUST : Generic PnP Monitor #1: 3840x2160 @ 25.00Hz (329) (weight: 0.000)
```

But I need to activate whitelist, otherwise it stays at 60 Hz.

It would be desirable to switch to 25 Hz without the need for whitelist (same as 23 or 24 Hz) but it is not an important issue since progressive content at 25 Hz is almost non-existent (in fact it's a format not allowed in the AVCHD / Blu-Ray specification).

**Comment by CastagnaIT** [comment]
you have been clear,
anyway for the streaming is not rare, on nfx usually can happen on documentaries to have 25fps

if this behaviour will be maintained in the future, it would be appreciated to specify this peculiarity in some kodi wiki in order not to create new chaos between users

**Comment by Ch1llb0** [comment]
Have just stumbled across this issue as well... My display only supports 50fps output, not 25fps. I've whitelisted all supported resolutions and 25fps video files are only played back at GUI framerate (59.94fps) with adjust refresh rate enabled and double refresh rate disabled (by default). This behaviour is very irritating. Can you explain what I might overlook here? To me it looks like this setting does worsen the user experience a lot as 25fps are played back at strange framerates (GUI) that don't make sense to users...

**Comment by lrusak** [comment]
> Have just stumbled across this issue as well... My display only supports 50fps output, not 25fps. I've whitelisted all supported resolutions and 25fps video files are only played back at GUI framerate (59.94fps) with adjust refresh rate enabled and double refresh rate disabled (by default). This behaviour is very irritating. Can you explain what I might overlook here? To me it looks like this setting does worsen the user experience a lot as 25fps are played back at strange framerates (GUI) that don't make sense to users...

No debug log?

If you don't need a whitelist don't use it. By disabling all modes in the whitelist the default behaviour of v18 will be observed

**Comment by thexai** [comment]
This issue should be already fixed by: https://github.com/xbmc/xbmc/pull/19382

In master/Matrix nightlies only.

**Comment by Ch1llb0** [comment]
> If you don't need a whitelist don't use it. By disabling all modes in the whitelist the default behaviour of v18 will be observed

But if I use whitelist and my connected TV doesn't support any "half" framerates (25p, etc.) I must now set the double framerate setting? It would make sense to only offer that setting, if a connected TV in fact does support "half" framerates. Otherwise it will be quite confusing for users who use whitelist, have a TV that only supports 50p, 59p and 60p and have those resolutions/framerates whitelisted: They'd expect, like I did, that those framerates would then be used for e.g. 25p videos... as there's no "half" framerate available/supported.

IMHO, the setting only makes sense, if a TV is connected that supports both "half" and double framerates...

**Comment by thexai** [comment]
Closed as it should be fixed by: https://github.com/xbmc/xbmc/pull/19382

@Ch1llb0 
If you still having an issue open your own, posting Kodi version used and full debug log.
