### ISSUE TITLE
Dolby Vision files do not trigger Dolby Vision display mode on FireTV Stick 4K

### ISSUE THREAD

**Issue by quietvoid** [xbmc/xbmc#18890]
## Bug report
On Kodi Matrix 19.0 Beta1, mp4 Dolby Vision files are supposed to playtback in Dolby Vision mode.

### Describe the bug
Here is a clear and concise description of what the problem is:

Dolby Vision mode is not triggered on the display when playing an mp4 Dolby Vision file.
It is a bug because the device supports Dolby Vision through multiple apps, as well as with Kodi using the Netflix addon.
Also, the debug log mentions that the DVHE decoder is being used, so something else is going wrong.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

With an mp4 Dolby Vision file on the device itself, starting playback of the file should trigger the display's Dolby Vision mode and the output video should look normal.

## Actual Behavior

When starting playback of an mp4 Dolby Vision file, the video is output in SDR mode and looks wrong.
There is no Dolby Vision mode activated.

## Possible Fix

Not sure, maybe the dvhe decoder is crashing.
With a profile 7 or 8 file, the HDR10 fallback works well.

### To Reproduce

1. Have a Dolby Vision sample (from https://kodi.wiki/view/Samples#4K_.28UltraHD.29, MP4 Dolby Vision samples) on the FireTV Stick 4K.
2. Open Kodi, go to the File Manager.
3. Browse the source where the mp4 file is located
4. Press to start playback
5. The display does not change to Dolby Vision mode.

### Debuglog

The debuglog can be found here:
A debug log with FFmpeg logging enabled on a debug build of Kodi master: https://paste.kodi.tv/sezujedeku.kodi
Using Maven's Kodi build: https://paste.kodi.tv/onupojoted.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

No screenshots necessary.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

On an NVIDIA Shield, these files work well, while on the FireTV Stick 4K, they do not.
Other than the hardware decoder, there should not be a difference in support for Dolby Vision profile 5 (the mp4 file tested here)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android, FireTV
 - Kodi version: 19.0 Matrix Beta1, armv7a

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by quietvoid** [comment]
If someone knows a bit about Android, here's a debug log using logcat: https://paste.kodi.tv/ucodohecum.kodi
Some noticeable issues (I don't know anything):
`VideoCapabilities: Unsupported mime video/dolby-vision`

```
MtkOmxVdecEx: [0xb436f000] [WARNING] Cannot get param: VDEC_DRV_GET_TYPE_GET_FRAME_CROP_INFO`
OMXNodeInstance: getConfig(1190037:MTK.DECODER.DVHE.STN, ConfigCommonOutputCrop(0x700000f)) ERROR: BadParameter(0x80001005)
OMXNodeInstance: setParameter(1190037:MTK.DECODER.DVHE.STN, ParamPortDefinition(0x2000001)) ERROR: BadParameter(0x80001005)
ACodec  : [OMX.MTK.VIDEO.DECODER.DVHE.STN] setting nBufferCountActual to 6 failed: -2147483648
```

And obviously a bunch of `VDO_LOG : [Err] unsupported NAL: 62`

Makes me think something's wrong with the device decoder but it only seems to not work with Kodi.
Gonna try ExoPlayer next to see what it does.

**Comment by quietvoid** [comment]
Here's logs using build made from PR https://github.com/xbmc/xbmc/pull/18965
MP4: https://paste.kodi.tv/iyikadamag.kodi
MKV: https://paste.kodi.tv/axebenuhex.kodi

**Comment by lrusak** [comment]
A couple things:

 1) does your tv actually support Dolby vision?
 2) does Dolby vision work on other apps?

**Comment by quietvoid** [comment]
@Irusak
1. Yes, it is an LG OLED C8.
2. Yes, it works on the native apps and in Kodi using the Netflix addon.

I think I might have some Netflix logs still out there from the previous issue I made, but I don't know if inputstream video is relevant to this context.

**Comment by quietvoid** [comment]
I have a feeling that it is related to what @peak3d described in https://github.com/xbmc/xbmc/pull/16929
If I force the device to output Dolby Vision and play a profile 5 video, it does not look correct so the metadata might not be used at all.

**Comment by M2k80** [comment]
@quietvoid did you test DV profile 4? i saw this on anandtech and could this be the reason why profile 5 is not working?:
https://www.anandtech.com/show/13423/amazon-launches-fire-tv-stick-4k
When it comes to media processing capabilities, the Fire TV Stick 4K can decode H.265 Main 10 Profile Level 5.1 with HDR10, HDR10+, HLG, and Dolby Vision, H.264 High Profile Level 4, as well as VP9 (presumably we are dealing with Profile 2 with HDR10 here). Meanwhile, it is noteworthy that unlike the 2017 Fire TV STB, the new dongle also fully supports MPEG2, MPEG4, and VP8 for web videos with an up to 1080p at 30 fps resolution. In addition, the Fire TV Stick 4K supports Dolby Atmos (EC3_JOC), Dolby Digital, Dolby Digital Plus, MP3, FLAC, and other audio formats.

**Comment by quietvoid** [comment]
@M2k80 Yes I have tried profile 4, it does not work in Kodi.
You can find the supported profiles for the device here: https://developer.amazon.com/docs/fire-tv/device-specifications-fire-tv-stick.html?v=ftvstick4k

Officially, profile 7 is unsupported but only FEL files fail to playback properly.

**Comment by irfanka** [comment]
Same issue on Sony XH9077 Android TV

**Comment by quietvoid** [comment]
@lrusak I've fixed this issue on top of the #18965 PR, https://github.com/xbmc/xbmc/pull/18965#issuecomment-764204795
I don't know if the patch should be a different PR just about the NAL header size workaround, it would at least fix MP4 playback.

**Comment by quietvoid** [comment]
If anyone with a Sony Android TV can test the nightlies with the #19099 patch, it would be useful to know if it works.

**Comment by deltabweb** [comment]
I have a Sony X900H and MKV files with Dolby Vision still have a green/purple hue so it doesn't seem to be fixed in my case.
Tested with:
- kodi-20211115-64330325-master-armeabi-v7a
- P5_Dolby_Amaze.mkv from https://www.makemkv.com/download/dvtest/

**Comment by quietvoid** [comment]
I don't think it will work with MKV files, can you try an MP4 or TS video?

**Comment by deltabweb** [comment]
Ok, so I tried a few videos from the net and here are my results:
- `dolby-vision-amaze-(dolby-vision)-(www.demolandia.net).mp4`: Working with DV
- `dolby-vision-art-(www.demolandia.net).mp4`: Working with DV
- `iOS_P5_GlassBlowing2_3840x2160@59.94fps_15200kbps.mp4`: Working with DV
- `P81_GlassBlowing2_3840x2160@59.94fps_15200kbps_fmp4.mp4`: Recognized as vanilla HDR (no DV)
- `dolby-vision-onoff-(www.demolandia.net).ts`: Green/Purple hue

None of the MKV files I've tried worked but I understand this will need to be fixed in another ticket? I will have a look to see if there's already one to track this.

**Comment by quietvoid** [comment]
Thank you. That behaviour seems correct to me.
The working files all have `dvhe` as codec ID, which is expected to work.

Others don't, and only have the decoder info in the container, which is currently not being used in Kodi.
For MKV, that is still missing (and it also requires an implementation in ffmpeg).

**Comment by deltabweb** [comment]
Thanks for fixing it.

For anyone like me needing a workaround while waiting for MKV files to be supported, I managed to get 2 MKV files working by using ffmpeg and the MP4 streaming muxer from Dolby (https://github.com/DolbyLaboratories/dlb_mp4base):
1. List the different streams with
```ffmpeg -i video.mkv```
2. Extract each stream with
```ffmpeg -i video.mkv -c:v copy -map 0:0 video.hevc -c:a copy -map 0:1 audio.ac3```
(adjust based on your file)
3. Remux with
```./mp4muxer_release --dv-profile 5 --input-file video.hevc --input-file audio.ac3 --media-lang eng --output-file video.mp4```
(adjust based on DV profile, `mediainfo` can help with this)

You now have an MP4 file that can be played on your TV via Kodi! :partying_face: :clapper: :champagne:

**Comment by LouWii** [comment]
I'm confused. I understand this is not supported in MKV, but will it be at some point in the near future? Is this a problem in Kodi or a lib that Kodi uses?

**Comment by quietvoid** [comment]
No, MKV support is not related to this issue.
That requires updates to ffmpeg (which Kodi uses for decoding).
