### ISSUE TITLE
DVD's not playing

### ISSUE THREAD

**Issue by Dis90** [xbmc/xbmc#18896]
### Describe the bug
Here is a clear and concise description of what the problem is:

Encrypted dvd's not playing on Kodi 19. They work under Kodi 18.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Dvd's playing.

## Actual Behavior

Directly after starting dvd it jumps back to Kodi home menu.

## Possible Fix

Probably something to do with libdvdcss. When playing dvd in Kodi 19 it doesn't create folder under .dvdcss. However after playing dvd first on VLC and then going to Kodi (without ejecting dvd from drive) it plays fine.

### To Reproduce

1. Put encrypted dvd on drive
2. Try to play it on Kodi 19
3.

### Debuglog

The debuglog can be found here:
https://pastebin.ubuntu.com/p/Zm8MfH8pyj/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Here is log from Kodi 18.9 after downgrading from Kodi 19 https://pastebin.ubuntu.com/p/Bwr3WJYfGy/
There's this line `DEBUG: libdvdread: Attempting to retrieve all CSS keys` what doesn't exists in log file from Kodi 19.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 20.04
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by howie-f** [comment]
i can confirm:
tested with a fresh install of `Ubuntu-20.04.1` and a `Copy protected DVD`
`ppa:team-xbmc/ppa` Kodi 18.9 plays fine out of the box.
`ppa:team-xbmc/xbmc-nightly` shows the busy spinner for a second and then returns to the home screen. https://github.com/xbmc/xbmc/commit/b3181df1431f6d3fd6df9a7f474909321e10c245

however, if 18.9 is installed and then upgraded to nightly this issue doesn't occur.

**Comment by howie-f** [comment]
This confirmed  issue is _most likely_ a combination of the disc itself, the used drive, copy protection etc. but not a software problem. Even bumping the `libdvd*` libraries didn't solve it in a clear manner. It appears to happen by pure coincidence.

Results from my latest test circle with a clean Ubuntu 20.04, built current master, DVD "Matrix Revolutions Disc 1":
- first attempt to play dvd successful: excerpt from log:
```
INFO <general>:   msg: Can't read name block. Probably not a DVD-ROM device.
INFO <general>:   msg: vm: dvd_read_name failed
INFO <general>:   msg: libdvdnav: vm: DVD Title: THE_MATRIX_REVOLUTIONS_D1
INFO <general>:   msg: DVD disk reports itself with Region mask 0x00ed0000. Regions: 02 05
INFO <general>:   msg: Attempting to retrieve all CSS keys
INFO <general>:   msg: This can take a _long_ time, please be patient
INFO <general>:   msg: Get key for /VIDEO_TS/VIDEO_TS.VOB at 0x000283b0
WARNING <general>: dll_ioctl - 21394 request failed with error [5] Input/output error
INFO <general>:   msg: Elapsed time 0
INFO <general>:   msg: Get key for /VIDEO_TS/VTS_01_0.VOB at 0x0002896e
WARNING <general>: dll_ioctl - 21394 request failed with error [5] Input/output error
INFO <general>:   msg: Elapsed time 0
INFO <general>:   msg: Get key for /VIDEO_TS/VTS_01_1.VOB at 0x00060092
WARNING <general>: dll_ioctl - 21394 request failed with error [5] Input/output error
INFO <general>:   msg: Elapsed time 0
INFO <general>:   msg: Get key for /VIDEO_TS/VTS_02_1.VOB at 0x00333685
WARNING <general>: dll_ioctl - 21394 request failed with error [5] Input/output error
INFO <general>:   msg: Elapsed time 0
INFO <general>:   msg: Found 2 VTS's
INFO <general>:   msg: Elapsed time 0
INFO <general>: VideoPlayer: playing a file with menu's
```
four key-files created in directory `~/.dvdcss/THE_MATRIX_REVOLUTIONS_D1-2004020608563600-000000003c`

- 2nd to 5th play attempt also success, though disc was reinserted and `~/.dvdcss` folder removed inbetween (but recreated)

- 6th attempt to play **fails** with the known symptom: log
```
ERROR <general>: dll_fclose emulated function failed
INFO <general>:   msg: libdvdnav: vm: DVD Title:
INFO <general>:   msg: libdvdnav: DVD disk reports itself with Region mask 0x00ed0000. Regions:
INFO <general>:   msg:  2
INFO <general>:   msg:  5
INFO <general>: VideoPlayer: playing a file with menu's
INFO <general>: Creating Demuxer
```
The _DVD title is not detected_ and an empty folder `~/.dvdcss/-2004020608563600-000000003c` is created.
This log overlaps with the posted https://pastebin.ubuntu.com/p/Zm8MfH8pyj/

Please notice that Kodi wasn't restarted inbetween, from here i couldn't get it to work again.

@Dis90
sorry to say the only suggestions i can make is maybe try a different DVD-Drive (USB).. or backup your movie to a file if possible.

**Comment by Dis90** [comment]
Tried completely remove Kodi and reinstall. Still same problem. Also this time I tried with Star Trek DVD. Currently I don't have different dvd-drive so I can't test that.

Can this be reason why DVD's is not playing?

Kodi 19:
`2020-12-03 19:01:46.063 T:24982 WARNING <general>: CreateLoader - unsupported protocol(iso9660) in iso9660://VIDEO_TS/VIDEO_TS.IFO
2020-12-03 19:01:46.063 T:24982 WARNING <general>: CreateLoader - unsupported protocol(iso9660) in iso9660://BDMV/index.bdmv
2020-12-03 19:01:46.063 T:24982   DEBUG <general>: GetDiskUniqueId: Retrieving ID for path iso9660:// failed, ID is empty.
2020-12-03 19:01:46.071 T:24982   DEBUG <general>: CPlayerCoreFactory::GetPlayers(/media/vdr/TRUE_BLOOD_S5_DISC3/VIDEO_TS/VIDEO_TS.IFO)`

Kodi 18:
`2020-12-03 21:03:36.887 T:139727383378624   DEBUG: GetDiskUniqueId: Got ID removable://TRUE_BLOOD_S5_DISC4_42726f4e for DVD with path iso9660://
2020-12-03 21:03:36.893 T:139727383378624   DEBUG: CPlayerCoreFactory::GetPlayers(/media/vdr/TRUE_BLOOD_S5_DISC4/VIDEO_TS/VIDEO_TS.IFO)`

**Comment by howie-f** [comment]
that's the point. sometimes you get the ID, sometimes you don't. i don't see a pattern.
both cases happened to me in one Kodi 19-session with the same DVD like described above. first success, then fail later.
hard to dig out, if someone has an idea where to start i'm sure they will chime in

**Comment by enen92** [comment]
Can't this be a regression from the dynpath changes for discs that was made somewhere in the matrix release cycle? https://github.com/xbmc/xbmc/pull/18271

maybe try to revert this PR and check if it makes any difference

**Comment by howie-f** [comment]
at a first glance this seems to address iso's and directory structs, but you never know. will give it a try. thanks for the hint @enen92

**Comment by howie-f** [comment]
Revert of https://github.com/xbmc/xbmc/pull/18271/commits/e38b9e6c77260656771ee9fc6ad9db832eccda54 does not change a thing.. no luck :(

**Comment by Dis90** [comment]
Tried Googling with error `GetDiskUniqueId: Retrieving ID for path iso9660:// failed, ID is empty.` and I found this file https://github.com/xbmc/xbmc/commits/master/xbmc/storage/MediaManager.cpp
Can you try revert PR #16262 ?

**Comment by Dis90** [comment]
@howie-f 
I did some testing and compiled two versions of Kodi 19. One before PR #16262 and one with PR #16262.

Playing copy protected DVD's works when using Kodi version before commit e846acb.

Logfiles:
Commit 837fe3e
https://pastebin.ubuntu.com/p/8kdVXTZQDv/

Commit e846acb
https://pastebin.ubuntu.com/p/2kmRdnqvdb/

**Comment by howie-f** [comment]
@Dis90 thanks for testing and sorry for being a bit late with the answer.
i did the same on last thursday, built before the commit in question. indeed it was working in the first place. unfortunately one day later the problem reappeared on the same commit, so i assume it doesn't really help and is not in a stable state there.

however, not to just revert this commit. would be nice if you could report back if it's stable for you now for a few days and attempts - or if you experience the same as me ;)

**Comment by Dis90** [comment]
Initially I used nightly PPA.

For me dvd playback is always failing with nightly ppa/build with that commit. No matter how many times I try. But for now it seems old version without that commit is working but I will run that version few days and report back.

**Comment by Dis90** [comment]
After couple of days DVD playback with version without the commit is still working and not with the commit. Is it something wrong with my setup or the commit?

**Comment by howie-f** [comment]
please mount your DVD at os level (e.g. filemanager) and post the output of `df -T`.

my testmedia uses
/dev/sr0   `udf`   6712240   6712240  0  100% /media/fhw/THE_MATRIX_REVOLUTIONS_D1
that's why reverting the `iso9660` commit has no impact at my end

**Comment by Dis90** [comment]
I don't have any filemanager installed. I use Ubuntu server/yaVDR and it uses udiskie to mount discs.

Output of df -T
> Tiedostojärjestelmä         Tyyppi    1K-lohkot       Käyt   Vapaana Käy% Liitospiste
udev                        devtmpfs    3978484          0   3978484   0% /dev
tmpfs                       tmpfs        801940       3180    798760   1% /run
/dev/mapper/telkka--vg-root ext4      113346788   25609308  81936728  24% /
tmpfs                       tmpfs       4009688        940   4008748   1% /dev/shm
tmpfs                       tmpfs          5120         12      5108   1% /run/lock
tmpfs                       tmpfs       4009688          0   4009688   0% /sys/fs/cgroup
/dev/sda1                   vfat         523248       7984    515264   2% /boot/efi
/dev/loop1                  squashfs      56704      56704         0 100% /snap/core18/1932
/dev/loop0                  squashfs      72320      72320         0 100% /snap/lxd/16922
/dev/loop2                  squashfs      56832      56832         0 100% /snap/core18/1944
/dev/loop3                  squashfs      31872      31872         0 100% /snap/snapd/10492
/dev/loop4                  squashfs      69376      69376         0 100% /snap/lxd/18150
/dev/loop5                  squashfs      31872      31872         0 100% /snap/snapd/10238
/dev/sdc1                   ext4      961301832  666109772 246337636  74% /srv2
/dev/sdd1                   ext4     1921802520 1072328552 751781908  59% /srv3
/dev/sdb1                   ext4     1922728836 1623567388 201469388  89% /srv
tmpfs                       tmpfs        801936          4    801932   1% /run/user/666
tmpfs                       tmpfs        801936          4    801932   1% /run/user/1000
/dev/sr0                    udf         8195846    8195846         0 100% /media/vdr/STAR_TREK_TOS_D2

**Comment by Dis90** [comment]
There's also udf rework on commit e5da4d5

From log files I found that non working version first opens
`VideoPlayer::OpenFile: /media/vdr/STAR_TREK_TOS_D2/VIDEO_TS/VIDEO_TS.IFO`
and then
`SECTION:LoadDLL(special://xbmcbin/system/players/VideoPlayer/libdvdnav-x86_64-linux.so)`

When working version does all libdvd stuff first and last VideoPlayer::OpenFile

**Comment by Dis90** [comment]
I tested dvd playback on Ubuntu 20.04 desktop in live session. At first Kodi just crashed but when I mounted disc from filemanager dvd playback worked. Dvd was in drive when I started live session so that is probably reason why it wasn't mounted.
Then I removed disc from drive and put it back. This time Ubuntu automounted disc and now dvd playback didn't work.

**Comment by howie-f** [comment]
yes i noticed that crash from a not mounted dvd too. reason is access to a nullptr that i'm going to fix soon.

so your scenario now was ubuntu live and kodi installed from nightly ppa, right?
this means your first play attempt was successful (..let's not look at the nullptr for now..) and the second failed? then you're facing the same issues as me during testing, and i still can't figure why this is happening

**Comment by Dis90** [comment]
Yes Ubuntu live and Kodi from nightly ppa.

First play was successful after mounting disc from filemanager. Didn't try manually mounting. But after that Ubuntu automatically mounted every disc I put in drive and no matter how many times I tried, dvd's just doesn't play.

What these lines in log means? Those doesn't exists on Kodi 18.
> WARNING: CreateLoader - unsupported protocol(iso9660) in iso9660://VIDEO_TS/VIDEO_TS.IFO

Does Kodi for some reason think disc is iso file and for that reason it doesn't use dvdcss and for that reason playback fails?

Can you try first play dvd using vlc and then in Kodi? For me that makes dvd playback on Kodi work until computer is rebooted or disc removed from drive.

**Comment by howie-f** [comment]
`unsupported protocol(iso9660)` is likely a missing library from the ppa, ofc. not users fault. though explicitly building with `iso9660pp` support didn't resolve this issue. as a last resort i tried VLC and it didn't work out.. please have a look at the attached video for demonstration.

i totally agree, this one is frustrating, disappointing - but it seems not to be a kodi issue per se.
i stand to be corrected here, but honestly i can't invest more time into it... sorry, don't get me wrong

https://user-images.githubusercontent.com/58829855/103301528-e7d74680-4a01-11eb-9d41-4878737dd762.mp4

**Comment by Dis90** [comment]
Thanks for using your time to check this issue.
My opinion is that problem is Kodi or Ubuntu. Weird thing is that for me playback works using VLC and Kodi 18 and not with Kodi 19 unless I first start playback using VLC.
For you playback doesn't seem to work even when using VLC. Maybe we have to wait if someone else has same issue.

**Comment by howie-f** [comment]
yeah, you did a lot digging too. that's really appreciated :+1: maybe it could be fixed the other day

**Comment by ronie** [comment]
i can confirm the issue raised by @Dis90 
DVD's will not play in Kodi (tested with current master on Manjaro linux)

Only after a DVD has been played with VLC, it will play in Kodi as well.
I'm not sure where VLC stores the magic as even after deleting the ~/.dvdcss directory and rebooting my system, the DVD will still play in Kodi.

perhaps @lrusak can chime in as there's an indication the issue was caused by https://github.com/xbmc/xbmc/pull/16262

**Comment by Dis90** [comment]
Sorry to bump this but is there any chance this is going to be investigated or fixed before release of Kodi 19?

**Comment by enen92** [comment]
@Dis90 test the linked PR ^^ if you have a chance

**Comment by Dis90** [comment]
Unfortunately doesn't work. Debug log: https://paste.kodi.tv/tavowusaja.kodi

**Comment by enen92** [comment]
@Dis90 out of curiosity, can you try the latest implementation (https://github.com/xbmc/xbmc/pull/19226/commits/565b1ac85f4a440debcef7a468bc30fea7bf90b9)?

I noticed in your log the following entry:
```
2021-02-13 21:05:55.955 T:2138    DEBUG <general>: GetDiskUniqueId: Retrieving ID for path iso9660:// failed, ID is empty.
``` 
So this is failing on the Open method.

**Comment by Dis90** [comment]
Tested and didn't work. Log: https://paste.kodi.tv/ukabameyun.kodi

**Comment by Dis90** [comment]
I still think that main problem is that Kodi tries to play DVD without first encrypting it. And this is somehow linked to iso9660 changes. I found this old PR https://github.com/xbmc/xbmc/pull/2951 which makes me think disc encrypting was done in iso9660.cpp

**Comment by enen92** [comment]
@Dis90 mind setting the following property and try again?

`export KODI_DVD_DEVICE=/dev/dvd`  or export `KODI_DVD_DEVICE=/dev/cdrom` depending on what your symlink is?

**Comment by Dis90** [comment]
I did run first `export KODI_DVD_DEVICE=/dev/dvd` and then launched Kodi but didn't work. After that I tried with `export KODI_DVD_DEVICE=/dev/cdrom` but that also didn't work.
Log file still shows it tries open from mounted path.

> 2021-02-14 14:40:51.590 T:2019  WARNING <general>: CreateLoader - unsupported protocol(iso9660) in iso9660://VIDEO_TS/VIDEO_TS.IFO
2021-02-14 14:40:51.590 T:2019  WARNING <general>: CreateLoader - unsupported protocol(iso9660) in iso9660://BDMV/index.bdmv
2021-02-14 14:40:51.593 T:2019     INFO <general>: VideoPlayer::OpenFile: /media/vdr/STAR_TREK_TOS_D2/VIDEO_TS/VIDEO_TS.IFO
2021-02-14 14:40:51.595 T:2077     INFO <general>: Creating InputStream
2021-02-14 14:40:51.601 T:2077     INFO <general>:   msg: libdvdnav: Using dvdnav version 6.0.0

**Comment by wsnipex** [comment]
note that kodi from the PPA currently lacks the libcdio++ headers, maybe the issue is related to that?

**Comment by Dis90** [comment]
I can confirm that playing encrypted dvd's works after installing libcdio packages from nightly ppa and building from source. Currently only tested with @enen92 PR. I will try also without that.

**Comment by Dis90** [comment]
Tested without PR and dvd playback doesn't work. So I can confirm that @enen92 PR with libcdio packages fixes problem :)

**Comment by howie-f** [comment]
that is good news 👍

**Comment by enen92** [comment]
@Dis90 thanks for your perseverance debugging this :)
