### ISSUE TITLE
crash on thumbnail extraction with some avi files

### ISSUE THREAD

**Issue by takbal** [xbmc/xbmc#18901]
### Describe the bug

Kodi 18.9 on Nvidia Shield (Android TV) crashes with some .avi files on play.

## Possible Fix

Turning off "Extract thumbnails from video files" in settings / media solves the problem completely.

### To Reproduce

The problem seems to be related to the file size as well. A VirtualDub direct stream extract of the first 250 frames of an example can be found here, in order to check the codecs used:

https://drive.google.com/file/d/1vGsIcWDFidlTxPpfU_oFE6PC_j3-yFMN/view?usp=sharing

This file plays without errors, but the original 4.7 GB long one does not. (I do not wish share multi-GB files containing personal stuff.)

### Debuglog

The debuglog can be found here (but does not show too much):

https://paste.kodi.tv/kojiyuyapi.kodi

logcat however does:

https://paste.kodi.tv/igofizagog.kodi

The idea to disable thumbnail extraction was coming from here, as the null-pointer crash clearly indicated that part.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV (Shield 2019)
 - Kodi version: 18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
If you can find another sample which is able to reproduce the issue it'd be appreciated (I doubt anyone can do anything with your shared sample). If you want to share the other sample in a private manner we can get you an email to share the file without making it available in the issue report.

**Comment by thexai** [comment]
Duplicated of https://github.com/xbmc/xbmc/issues/19008
