### ISSUE TITLE
Android Voice Assistant crash after finding guess

### ISSUE THREAD

**Issue by iaankrynauw** [xbmc/xbmc#18914]
### Describe the bug
When using the OnScreenKeyboard and holding the middle button the voice recognition dialog appears, whereby google assistant is used to guess text via voice.

The function succeeds to get the guess from voice and enters text into the keyboard but proceeds to hang and then crash afterward.

From many attempts, I had one that succeeded.

 I had a look at the code the function call is:
```
# GUIDialogKeyboardGeneric.cpp
void CGUIDialogKeyboardGeneric::OnVoiceRecognition()
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When pressing the middle button on the OnScreenKeyboard and voice dialog appears. Input should be captured from the GoogleAssistant and copied to the text input without crashing.

## Actual Behavior

System crashes after successfully getting voice recognized text from google.

### To Reproduce

1. Open on screen keyboard
2. Hold middle button of remote
3. Talk into microphone
4. Wait for application to crash to main menu of Android TV

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Leia v18.9 
Using New Google Chromecast with Google TV
Android TV OS version: 10

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
The developers might need a debuglog which you missed to provide

**Comment by DaVukovic** [comment]
Issue closed because debuglog is missing
