### ISSUE TITLE
Cant play any video // unsupported protocol('"smb)

### ISSUE THREAD

**Issue by Abolfazl** [xbmc/xbmc#18919]
### Describe the bug
When I go to play any video file, I receive an error and in the logs it says `CreateLoader - unsupported protocol('"smb) in '"smb://XX.XX.XX.XX/Path/To/File.mkv"'`

However, if I go to the movie, open context menu and push Play, the video plays as expected and in the log it shows up as `VideoPlayer::OpenFile: smb://XX.XX.XX.XX/Path/To/File.mkv` 

So for some reason opening the file directly is wrapping `"'` (thats a double quote followed by single quote) around the movie path. Has anyone else had this problem?

## Expected Behavior
The video plays

## Actual Behavior
Receive an error on video playback. In the log it shows up as `CreateLoader - unsupported protocol('"smb) in '"smb://XX.XX.XX.XX/Path/To/File.mkv"'`

### To Reproduce
1. Play a video that points to SMB:// share

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/imakewuyey.kodi

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

Running on Nvidia Shield.

 - Operating system version/name:
 - Kodi version: 19.0-BETA2

**Comment by Abolfazl** [comment]
Okay changed it to fit the desired format

**Comment by Abolfazl** [comment]
Did a little digging and looks like the error is being thrown [Here](https://github.com/xbmc/xbmc/blob/9cd808e2c7b994816b75d8f40a2b1921353f8be4/xbmc/filesystem/FileFactory.cpp) because the protocol is `"'smb` and not `smb`

**Comment by enen92** [comment]
Sorry your log is full of piracy addons - we cannot provide any help. Please provide a new one with a clean Kodi installation if the issue persists. Furthermore, Kodi 18 will no longer receive any further updates, please check if the issue also happens in Kodi 19.

**Comment by BRTPOB** [comment]
I'm reopening this as I had the exact same issue with Matrix/Kodi 19. I've attached my INFO log, as I don't have a debug log available at the moment, but I'll get one for you tomorrow, however I wanted to show you the issue is still occurring with 19. Also with an Android SHIELD TV Pro.

https://paste.kodi.tv/noloxakapo.kodi

I'll post a debug log tomorrow for you with the same behavior.

**Comment by Abolfazl** [comment]
@BRTPOB Did you install the Kodi Matrix Alpha builds? I think there was some bug in the migration from 18 stable to 19 alpha. I ended up just starting from scratch.

**Comment by BRTPOB** [comment]
Nope. I went straight from retail Leia 18 to Matrix 19. I've opened a different issue for this, since this one was closed.
