### ISSUE TITLE
EIA-608/708 Captions no longer recognized

### ISSUE THREAD

**Issue by atc98092** [xbmc/xbmc#18916]
### Describe the bug
Here is a clear and concise description of what the problem is:
With Kodi 18.9 and perhaps even one or two previous previous builds, EIA-608/708 captions are no longer appearing as available caption tracks. I have recorded media in both the WTV container from older Windows Media Center recordings, but I've moved to J River as my media center software now, so everything is in the TS container. Up until the most recent builds, I could always select and display these tracks. Now when I enter the caption selector, it just shows none available. At first, they would appear again after a few minutes of playback, but now they never appear at all. 

All my recordings have been edited with VideoReDo to remove commercials, but I retain the container and included codecs, and nothing has changed in my process. If I open the same video with VLC or MrMC, the captions are there and selectable/visible. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
When playing a video containing OTA recordings with EIA608/708 captions, they should be listed on the Captions selector

## Actual Behavior
The Captions selector shows "none" for available captions. Almost all my OTA recordings have at least one captions track.

### To Reproduce

1. Select a video containing such tracks
2. Open the Captions selector
3. Look for a captions track to select.

### Debuglog
I have no idea how to get a debug log from an Nvidia Shield. I would be happy to provide one with direction.

## Additional context or screenshots (if appropriate)
This is a MediaInfo example of the media:
General
ID                                       : 1 (0x1)
Complete name                            : J:\Media\Movies_8\Recorded TV\For Your Eyes Only (1981).ts
Format                                   : MPEG-TS
File size                                : 1.86 GiB
Duration                                 : 1 h 49 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 2 437 kb/s
Law rating                               : TV-PG

Video
ID                                       : 81 (0x51)
Menu ID                                  : 5 (0x5)
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@main
Format settings                          : CustomMatrix / BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : Variable
Format settings, picture structure       : Frame
Codec ID                                 : 2
Duration                                 : 1 h 49 min
Bit rate mode                            : Variable
Bit rate                                 : 2 188 kb/s
Maximum bit rate                         : 15.0 Mb/s
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate                               : 29.970 (30000/1001) FPS
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.211
Time code of first frame                 : 00:00:00;00
Time code source                         : Group of pictures header
GOP, Open/Closed                         : Open
GOP, Open/Closed of first frame          : Closed
Stream size                              : 1.67 GiB (90%)

Audio
ID                                       : 84 (0x54)
Menu ID                                  : 5 (0x5)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : 129
Duration                                 : 1 h 49 min
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 28 ms
Stream size                              : 100 MiB (5%)
Language                                 : English
Service kind                             : Complete Main

Text #1
ID                                       : 81 (0x51)-CC1
Menu ID                                  : 5 (0x5)
Format                                   : EIA-608
Muxing mode                              : A/53 / DTVCC Transport
Muxing mode, more info                   : Muxed in Video #1
Duration                                 : 1 h 49 min
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte (0%)
CaptionServiceName                       : CC1

Text #2
ID                                       : 81 (0x51)-1
Menu ID                                  : 5 (0x5)
Format                                   : EIA-708
Muxing mode                              : A/53 / DTVCC Transport
Muxing mode, more info                   : Muxed in Video #1
Duration                                 : 1 h 49 min
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte (0%)

### Your Environment
Used Operating system:

 - [ X] Android (Shield)
Media is being streamed from a Windows PC running Serviio 2.1. No transcoding is being performed on the media.

 - Operating system version/name:
 - Kodi version: 18.9, but began having issues with these tracks one or two builds ago.

**Comment by enen92** [comment]
Have you enable "Enable parsing of closed captions" in Player -> Language settings?

**Comment by atc98092** [comment]
I just checked and no, it was not enabled. I don't think I had ever set that before, but can't honestly say. I did a remove and reinstall of Kodi to remove it from the beta, and perhaps I overlooked it. The captions are now appearing. Thanks!

**Comment by enen92** [comment]
@atc98092 no problem, glad it's a false positive. 
Btw, I've done a few fixes for EIA-609 for matrix, so if you have any channels that might have special charsets (not english or special english), samples are appreciated for validation

**Comment by atc98092** [comment]
Sorry, just normal English here. :D
