### ISSUE TITLE
Kodi Matrix Doesn't Automatically Resume Playback After Seeking and Filling Cache

### ISSUE THREAD

**Issue by driva5** [xbmc/xbmc#18912]
Playing a high bitrate 4k movie puts a lot of strain on my network connection so when seeking to a specific point in the movie Kodi takes longer to fill the video cache. In Kodi 18, the message  "Source Too Slow For Continuous Playback" appears (but not in Matrix) after seeking and the video will stutter then pause until the cache is filled at which point Kodi will resume playback. However, on Kodi 19, when the cache gets filled Kodi doesn't automatically resume playback. The video will remain paused until I intervene and press the pause button followed by the play button to continue watching.

Kodi 18
https://paste.kodi.tv/iditecaqik.kodi

Kodi 19
https://paste.kodi.tv/tiyagejeye.kodi

**Comment by DaVukovic** [comment]
Could you please test a newer Kodi version: (19.0-ALPHA3 (18.9.730) Git:20201031

Yours is about 2 months old. Maybe the problem already has been fixed. Provide a new debuglog if it's not fixed with the Kodi version you are using then.

**Comment by JDRIVO** [comment]
Hi DaVukovic, the issue persists on Kodi Matrix Beta 2. Log below. Cheers.

https://paste.kodi.tv/ugomoqirin.kodi

**Comment by driva5** [comment]
Hi DaVukovic, the issue persists on Kodi Matrix Beta 2. Log below. Cheers.

https://paste.kodi.tv/ugomoqirin.kodi

**Comment by driva5** [comment]
Even though I didn't hear back from anyone, this issue seems to have been resolved in the final release of Matrix. The player functions as it did in Leia. So thanks to whoever fixed it.

**Comment by arnova** [comment]
Thanks for reporting back.

I think it was me who fixed it with https://github.com/xbmc/xbmc/pull/19188 :-)
