### ISSUE TITLE
KODI 18.9 on FireTV (32bit) will not open any kind of files over SMB (MacOS Big Sur 11.1)

### ISSUE THREAD

**Issue by CrazedLeper** [xbmc/xbmc#18928]
### Describe the bug
Here is a clear and concise description of what the problem is:

File information can be scraped, but videos will not play and photos will not display.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expected a video (any video) to play.

## Actual Behavior

The little blue circle animates, then nothing. No error message, no explanation, no change of state. It just ignores the command as if none were given.

## Possible Fix

I'm thinking it could be something having to do with Big Sur, but this level of detail is over my head.

### To Reproduce

1. Fire up FireTV
2. Run KODI
3. Locate any TV show or movie
4. Press select button
5. Be disappointed.
6. Go to step 4.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ofebopahus 

### Screenshots 
Here are some links or screenshots to help explain the problem:

Sorry, none. Don't think any would be helpful.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [X] OSX 
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

MacOS 11.1 (Big Sur)
FireTV/Android
Kodi 18.9

[KODI fail log.docx](https://github.com/xbmc/xbmc/files/5682363/KODI.fail.log.docx)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You have banned add-on installed at your Kodi instance. Please remove those first and provide a new log. 

Thanks in advance

**Comment by DaVukovic** [comment]
No new log, issue closed
