### ISSUE TITLE
Feature Request: Default Kodi Skin - Ability To Add Addon Shortcuts To Side Panel

### ISSUE THREAD

**Issue by trymeouteh** [xbmc/xbmc#18922]
Please add a feature to be able to add add-on shortcuts to the side panel. No need to go to Videos->Video Addons->[Addon Name] or Music->Music Addons->[Addon Name] to go to a certain music or video addon.

**Comment by KarellenX** [comment]
@trymeouteh 

We don't accept Feature Requests here.

For Estuary skin, please post your request in this thread... https://forum.kodi.tv/showthread.php?tid=262603

Thanks.
