### ISSUE TITLE
xbmcgui.Dialog().yesno has now an optional customlabel, but the return of the Python function is still a bool

### ISSUE THREAD

**Issue by peno64** [xbmc/xbmc#18937]
### Describe the bug
Here is a clear and concise description of what the problem is:

In Matrix, xbmcgui.Dialog().yesno is extended such that a third customlabel can be added. This works, however in addons, the Python function still returns a boolean such that it is impossible to check if that third option was chosen.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Probably not a boolean but an integer should be returned (0/1/2) such that the third options can be checked

## Actual Behavior

It returns True for the first option and False of the second and third option and as such no distinction can be made between option 2 and 3

## Possible Fix

Retuns an integer instead of a boolean

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Has to make with following commit:
https://github.com/xbmc/xbmc/commit/120e2174d8f68a6d5a15c36494a56de09b842aad

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.0-BETA2 (18.9.821) Git:20201206-f98835b436). Platform: Windows NT x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by peno64** [comment]
@enen92 

Just a small suggestion. I see that you added a new yesnocustom implementation and yesno did't change. Would it not be better to change the yesno code now that it calls this new yesnocustom implementation without a custom button and converting its int result to bool from yesno? That way there is only one implementation and if something needs to change in the yesno(custom ) implementation it is automatically done for the two and it can't be forgotten that a change is done in the one and not in the other.

**Comment by enen92** [comment]
Thanks for the suggestion, I acknowledge this is not the best solution ever :)

However, between having two identical methods that call each other and only differ on the return type and having two actually different functions (one for a simple yesno and another for a 3option choice) I find the second one less confusing for addon developers and even enforces the usage of the custom label as a required parameter. Sure that the problem you identify may happen...

**Comment by peno64** [comment]
@enen92 

Note that I mean the implementation of the yesno and yesnocustom routines in C. 
I totally agree that in the python addons the two functions should exist.
I mean the implementation in the Kodi C source code. There the yesno implementation could call yesnocustom instead of now having two separate codes which are almost the same I guess.

**Comment by enen92** [comment]
@peno64 done in the PR.
