### ISSUE TITLE
Adding a pvr timer via JSON RPC call doesn't work in K19 Betas

### ISSUE THREAD

**Issue by b-jesch** [xbmc/xbmc#18944]
### Describe the bug
Here is a clear and concise description of what the problem is:

Adding a timer via JSON RPC produces this return code:

`{ "code": -32602, "message": "Invalid params." }`

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

PVR.addTimer introducing the new reminder timer has already worked with the alpha versions independent from type of the timer. See PR here: [https://github.com/xbmc/xbmc/pull/18644](url)

## Actual Behavior

Doesn't work anymore. Produces the return code above

### To Reproduce

1. Create a JSON RPC call with this core parameters:
`{ "method": "PVR.AddTimer", "params": {"broadcastid": int(broadcastId), "reminder": True, "timerrule": False} }`
where broadcastId is a valid ID - should be checked with PVR.GetBroadcastDetails

### Debuglog

The debuglog can be found here:

There is no debuglog as the JSON RPC call does not produce an error, only the return code above

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04.3 LTS
 - Kodi version: Matrix Beta, 19.0-BETA2 (18.9.821) Git:20201215-f27bba3632 Media Center Kodi

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
@phunkyfish this could be the culprit: https://github.com/xbmc/xbmc/commit/80eed027943f4438a2f8752570d39eee40e10a55#diff-285395e3b9dbb61b89042954a0d1b5aae97ad1dd8c09ab9132a6dd7ec0832ca0

Maybe https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/PVROperations.cpp#L399 needs to be changed accordingly? Maybe other places as well?

**Comment by phunkyfish** [comment]
Nice catch. That's making me wonder where else in PVR might require this change.

**Comment by DaVukovic** [comment]
@b-jesch can you confirm, the mentioned PR fixes your issue?

**Comment by b-jesch** [comment]
Yes, it works now as expected. Thank you very much.

A little cosmetic maybe is the missing translation within the timer & PVR setup window:
![Bildschirmfoto von 2020-12-21 12-06-07](https://user-images.githubusercontent.com/10152384/102771095-938af180-4385-11eb-80a1-dd8e79e03cac.png)

Regards

**Comment by DaVukovic** [comment]
Yeah, translations are a different story. Thanks for confirming ;)
