### ISSUE TITLE
android ndk r18 undeclair fseeko

### ISSUE THREAD

**Issue by nengtiansh** [xbmc/xbmc#18941]
### Describe the bug
Here is a clear and concise description of what the problem is:

build xmbc on ubuntu18.04 
ndk r18 platform android-21
target: arm-linux-androideabi   and aarch64-linux-android
When include <fstream>
get error include/c++/4.9.x/fstream:911:9: error: use of undeclared identifier 'fseeko'

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

compile pass in aarch64 in android-21

## Actual Behavior

in stdio.h
#if defined(__USE_FILE_OFFSET64)

#if __ANDROID_API__ >= 24
int fseeko(FILE* __fp, off_t __offset, int __whence) __RENAME(fseeko64) __INTRODUCED_IN(24);

### To Reproduce

1. compile accroding to doc/readme.android
2. xbmc/xbmc/platform/linux/LinuxTimezone.cpp compile fail
3.

### Debuglog

The debuglog can be found here:
kodi/xbmc/xbmc/platform/linux/LinuxTimezone.cpp:28:
/home/lei/kodi/android-tools/aarch64-linux-android-vanilla/android-21/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../include/c++/4.9.x/fstream:911:9: error: use of undeclared identifier 'fseeko'
    if (fseeko(__file_, __width > 0 ? __width * __off : 0, __whence))

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [Y ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
amlogic-4.9-18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Use a newer compiler and use git master.

**Comment by nengtiansh** [comment]
Pls suggest newer compiler ndk version?

**Comment by lrusak** [comment]
https://github.com/xbmc/xbmc/blob/master/docs/README.Android.md
