### ISSUE TITLE
Commit 34fe42353f0b1f6c638954dae66e9af3ba73d332 breaks netflix and amazon playback

### ISSUE THREAD

**Issue by andrejfilipcic** [xbmc/xbmc#18956]
### Describe the bug
Netfix and Amazon playback with inputstream.adaptive is broken in Matrix beta2, video is not decrypted.

## Expected Behavior
video should decrypt

## Possible Fix

Reverting the commit https://github.com/xbmc/xbmc/commit/34fe42353f0b1f6c638954dae66e9af3ba73d332 on beta2 or master makes it work again.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo
 - Kodi version: Matrix beta2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
From my tests (with Netflix add-on) i have not found problems with the various operating systems

You have to make sure that you have installed:
-Last version of Kodi nightly build
-Last version of InputStream Adaptive **2.6.6**

and is mandatory provide a full debug log

**Comment by StollD** [comment]
I also ran into this issue on Fedora 33 with Kodi from RPMFusion. The RPMFusion repository has the latest version of InputStream Adaptive (2.6.6), but it was compiled against beta1. After locally rebuilding InputStream Adaptive against beta2, everything seems to work fine again.

**Comment by andrejfilipcic** [comment]
I though I have recompiled the plugin already, but obviously I did not. Works now, thanks for the hint.
