### ISSUE TITLE
Play a video from a HTTPS source : unable to seek in the video

### ISSUE THREAD

**Issue by plooum** [xbmc/xbmc#18958]
### Describe the bug
I added a Https video source below "Videos > Files" (+ Add videos > Browse > Add network location > Https ...).
(My Https source is a simple "Mod_index" from Apache2 protected by password)
I play a video (no matter the format), and when I seek forward (for example) a couple of minutes, it only seeks a few seconds.

The bug exists since the version 18.1 (I can seek in the version 18.0). I tested it on Debian, Windows 10 and Android with the default player.

## Expected Behavior
When I seek for example 1 hour, I expect Kodi to seek 1 Hour.

## Actual Behavior
Kodi seeks a few seconds.

## Possible Fix
I use KODI V18.0 to be able to seek.

### To Reproduce
1. Start KODI (at least the version 18.1)
2. Go to "Videos > Files > Add videos > Browse > Add network location... > Select Web server directory (HTTPS), enter the informations of the server (Server address, Remote path, Username, Password)"
3. Click on "OK"
4. Click on "OK"
5. Click on "OK"
6. Navigate to a video and click on it
7. Try to seek

### Debuglog

Debug log for the version V19.0 Beta 2 : [https://paste.kodi.tv/dovevagora.kodi](https://paste.kodi.tv/dovevagora.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

I made a video on Youtube to show what happen when I seek forward (I am sorry, Youtube striked my video but I don't know why).
[https://www.youtube.com/watch?v=a_OPxx_6Abs](https://www.youtube.com/watch?v=a_OPxx_6Abs)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 (V 2004), Debian 9, Android 11
 - Kodi version: V19.0 Beta 1 and V19.0 Beta 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
> I have no Debug Log for that.

But we will need one

**Comment by plooum** [comment]
Hello,

I tested it on V19.0 and I added the DebugLog.
Sorry for the inconvenience

Regards.

**Comment by plooum** [comment]
Hello,

I tested it on V19.0 and I added the DebugLog.
Sorry for the inconvenience

Regards.

**Comment by DaVukovic** [comment]
Could you please try to disable hardware acceleration and see if it works any better?

I would probably suspect the server itself. It may do other stuff (like downloading movies during playback as I see you have a "Download" folder in use). And as that's probably done over the same network interface, the server might not deliver the data fast enough (while it's downloading other stuff) and the stream stops. 

But I'm not sure if that's the reason. So I will step out and let the developers have a look.

Thanks for the log and the report.

**Comment by plooum** [comment]
I disabled hardware acceleration : it doesn't work any better.
I made a new debug log : [https://paste.kodi.tv/zohomiyoba.kodi](https://paste.kodi.tv/zohomiyoba.kodi) (V19.0 Beta 2).
Next, I will investigate the server side.

Regards

**Comment by plooum** [comment]
I finally resolved this issue by adding the following text in an .htaccess file (in the root directory of my website) :
SetEnv no-gzip dont-vary

My web server is an Apache2 with the "Indexes" module under Debian 10.

Thanks a lot to the Kodi's community.
