### ISSUE TITLE
Latest Matrix beta vs stable  LibreELEC Leia

### ISSUE THREAD

**Issue by Jasoroony** [xbmc/xbmc#18953]
## Bug report
This is not a bug report.

### Your Environment
Used Operating system:
 - [X] Linux - Raspberry Pi 4 LibreELEC

 - Operating system version/name:
Raspberry Pi 4 LibreELEC
 - Kodi version:
Latest LibreELEC snapshot from last night (Matrix) vs the official release (Leia)

This is just some observations (and firstly, thanks for all your good work):

1/ I created xml files for each of my music video files (all mpg) as per the standard Kodi doco, I'm only filling in artist and title, but Matrix takes about 2 seconds to scan each one in, where Leia did them all much faster.  8500 videos (+8500 xml files) would take quite a few hours (nearly 5) if I let it run through to completion.

2/ The PI: Analogue and HDMI+Analogue options are missing in Matix, I've got many more HDMI options now, but none direct audio to the 3.5mm audio plug.

3/ The pixels on the left of screen (top to bottom) seem to be what's needed on the right most pixel column (but I think you know this already).

4/ The music playlist is less touchscreen friendly in Matrix, it no longer has 3 column areas (control, playlist & info.. there's now only 2: info and playlist) so the controls for skip-next / stop are hidden.

5/ System -> LibreELEC tile doesn't highlight with the mouse cursor (a touchscreen issue) in Matrix like it did in Leia while it is slightly off-screen at the bottom.

6/ In Leia, the currently playing music screen could be exited with a right mouse click (a touchscreen feature) but not in Matrix where neither music or (music-) videos can be exited via touch without stopping.  Actually, I would have liked Leia to allow exit from video the same way, where it currently brings up the video info details, Matrix does that for both now.

7/ Boot times are comparable, but shutdown now takes much longer.  This unit is solely used as a car-pc, with a touchscreen, so boot times are not all that important (though LibreELEC is pretty good) as I am patient, however when arriving at my destination I do appreciate a quick shutdown...

Both Matrix and Leia boot in 21-22 seconds, and while Leia shuts down in 10 seconds, Matrix takes 31 seconds.

**Comment by lrusak** [comment]
Please use the forum for support.

**Comment by Jasoroony** [comment]
This wasn't a request for support, but I appreciate you reading it nonetheless.  I look forward for when Matrix emerges from beta status.
