### ISSUE TITLE
kodi19 wont create new database on mysql

### ISSUE THREAD

**Issue by sopparus** [xbmc/xbmc#18957]
### Describe the bug
if you want to start a new database (fresh install) this wont work on kodi19 with mysql. works fine on kodi18 with same mysqluser.

Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. use advanced settings for mysql
2.create new database with kodi
3.

### Debuglog

The debuglog can be found here:
https://pastebin.com/pjxu5u0y

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

https://pastebin.com/pjxu5u0y
### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaveTBlake** [comment]
I am unable to reproduce, new video database created without difficulty (Windows 10, MySQL 5.7).

@sopparus your log file stops at `Unable to open database: matrix110`
This is odd as I would expect it to continue to check down to matrix75 and then attempt to create the new video database. Is there a reason why your paste was truncated or did it stop there?

**Comment by sopparus** [comment]
hm kodi crashed after this and log ended there, anyways after a boot it works now, so I',m sorry. this didnt have have anything to do with database. thanks
