### ISSUE TITLE
On Android the file created by add-ons are not visible when you browse the folder from a pc (USB-MTP)

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#18962]
### Describe the bug
Here is a clear and concise description of what the problem is:

When you use Kodi on android and you try to create new files by using a python add-on,
the file created is visible only if you use the file manager in the smartphone
if you try to connect the device to a pc via USB (MTP) you cannot see/read/download the files created

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If you create a file this must be visible also when you connect the device on a computer

## Actual Behavior

The file created can not be found when you browse the folder from a computer via USB-MTP

## Possible Fix

When you create a new file with `xbmcvfs.File` (on Android) callback android MediaLibrary API to request to add the new file entry (i have not investigated to understand if it is also necessary when deleting a file)

### To Reproduce

1. Install test addon: [plugin.video.test.zip](https://github.com/xbmc/xbmc/files/5725213/plugin.video.test.zip)
2. Open it and select a folder where save the file (i have used internal storage folders)
3. Connect the android device on a computer via USB-MTP (the only available on my Honor)
4. Open the same folder from the pc, look that the file not exists
5. Open a File manager app in the android device, look same folder the file exists

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/jubezasugu.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

As workaround:
- I tried to install media.Re.Scan app from playstore, allow to rescan all files and force update the android MediaLibrary, after the scan the file is correctly visible also from the computer.
- Reboot the device and wait until that the android MediaLibrary rescan all device folders...if happen...require too much time

Some documentations that i found on this:
https://www.grokkingandroid.com/adding-files-to-androids-media-library-using-the-mediascanner/
https://support.honeywellaidc.com/s/article/Files-created-updated-by-Android-application-are-not-visible-via-MTP

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 8.0.0
 - Kodi version: Kodi 19 and Kodi 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
@joseluismarti i see that you have skills on android
maybe can you try take a look on this problem?

it would be useful to know also if in the new android versions this problem does occur or not (i use old android 8)

**Comment by joseluismarti** [comment]
Hi, I've tested the script on an Android 11 phone and creates the file ```unicorn.txt``` on the external storage.
I connect via usb and see the file and the content.

**Comment by CastagnaIT** [comment]
thanks for the test
then could be just a problem of android 8...
i close it
