### ISSUE TITLE
Missing return parameter 'broadcastid' in JSON-RPC call 'PVR.GetTimers'

### ISSUE THREAD

**Issue by b-jesch** [xbmc/xbmc#18960]
## Bug report

As now epguid and broadcastid are different but unique parameters, broadcastid is missing in PVR.GetTimers. The parameter broadcastid is essential for PVR.GetBroadcastDetails and PVR.GetBroadcastIsPlayable. Also, the returned parameter epguid is useless in this cases. Also you set a timer with PVR.AddTimer and a required parameter broadcastid (not epguid). Would be nice if  broadcastid will be added back to PVR.GetTimers

### Describe the bug

As now broadcastid is missing on timers it's very complicated or impossible to allocate a timer to a broadcast or vice versa.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04.3 LTS
 - Kodi version: 19.0-BETA2 (18.9.821) Git:20201221-c9da8b4d98 Media Center Kodi

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
@phunkyfish something for you to fix I guess.

**Comment by phunkyfish** [comment]
@DaveTBlake as epguid is now useless do I drop it and add broadcastid at the end?

Or mark epguid as deprecated to be removed in kodi 20 and add broadcastid at the end?

**Comment by b-jesch** [comment]
I can wait for this - no problem.

**Comment by ksooo** [comment]
@b-jesch  for what exactly do you need the "broadcastid" property at the timer? Is it just cosmetics or do you have an actual use case where you need it?

I ask because having "broadcastid" at the timer is conceptually wrong (as epguid is, btw), because a timer could have more than one epg tag associated. Not supporting this is a major design flaw in PVR core. Adding "broadcastid" would manifest this design flaw one more time, which I would like to avoid.

**Comment by b-jesch** [comment]
Could we discuss this in german? At some point it's a little bit complicated. I'll invite you for a conversation on kodinerds.net

**Comment by phunkyfish** [comment]
Please keep the discussion in this thread. Anyone supporting kodi should be able to understand the reasoning.

**Comment by b-jesch** [comment]
Ok, I use a translation from deepl.com:

I'm working on an addon (or relaunch of the addon), which displays current TV highlights in a widget. If you select an item (i.e. a program recommendation) of the widget, the buttons "Switch" (if the recommendation is already running), "Switch timer" and "Record" are displayed in a separate info window in addition to additional information.

The procedure is approximately as follows:

- based on the scraper data, the station, start time and title of the program are first recorded, regardless of whether the station is in the clients PVR list.
- compare station name with the PVR channel list
- if the channel is in the PVR, the BroadcastID is determined for this channel on the basis of the title and the start time of the broadcast.
- the timer list (GetTimers) is iteratively scanned and the BroadcastId of the timer is compared with the BroadcastId above
- if a match is found, the timer details are read out (Reminder, Record)

Depending on the comparison the above mentioned buttons are armed or disabled (invisible).
That was the short form.

All that has already worked in the alphas. For now the relation/Dependency between a timer and a broadcast is gone. You cannot determine if a broadcast is associated with a timer or vice versa.

**Comment by phunkyfish** [comment]
Great explanation. Thanks for providing it. I agree we should add this. In a future kodi version when timer support is expanded (let’s say for multiple channels and channel groups) we can deprecate it.

**Comment by ksooo** [comment]
Yes, makes sense.
