### ISSUE TITLE
PVR guide sort order issue (Kodi v19 Matrix)

### ISSUE THREAD

**Issue by Ch1llb0** [xbmc/xbmc#18973]
## Bug report

When trying to adjust the sort order of the EPG grid in the EPG guide window using the [built-in control (with ID "4")](https://kodi.wiki/view/List_of_Built_In_Controls#MyPVRGuide.xml) the sort order does sometimes change on first or second attempt (sometimes not) and never after that. It does however change when toggling the sort order control and then opening another dialog (like the sort method selection dialog) or closing and re-opening the PVR guide window.
When sending a click to control ID "4" via a custom toggle button, the sort order changes immediately and reliably however.

This behaviour is skin agnostic - Estuary uses a custom control and therefore always works properly. Using the built-in control utilized in other skins shows the buggy behaviour.

## Expected Behavior

When the built-in sort order toggle button is pressed, the sort order of the EPG grid should change immediately and reliably.

## Actual Behavior

The sort order only changes on first or second attempt, sometimes not even then and when closing/re-opening the window or opening/closing any other dialog after pressing the sort order toggle button.

The sort order can be reliably changed with a custom toggle button sending a click to ID "4". Only the built-in control seems to be affected.

### To Reproduce
1. open the PVR guide window
2. open the side menu (_m_ button on keyboard)
3. press the sort order toggle button (ID "4)

### Debuglog
The debuglog can be found here: [kodi.log](https://github.com/xbmc/xbmc/files/5731728/kodi.log)

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64-bit
 - Kodi version: 18.9.801.0

**Comment by ronie** [comment]
can confirm, tested using Confluence.

perhaps @ksooo might have a clue...

**Comment by Ch1llb0** [comment]
Great, thank you!
