### ISSUE TITLE
Path Substitution is not filtered in advancedsettings.xml

### ISSUE THREAD

**Issue by SkyBird1980** [xbmc/xbmc#18974]
### Describe the bug
Path Substution in advancedsettings.xml is not filtered. So if you transfer a log or debuglog the password will be visible.

## Expected Behavior
- User and Password is filtered and shown as ****

## Actual Behavior
- User and Password is visible.

## Possible Fix
your part :)

### To Reproduce
Just add an smb pathsubstitution to advancedsettings.xml with user and password

### Debuglog
The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/5733446/kodi.log)

### Screenshots
Here are some links or screenshots to help explain the problem:
-nothing to see here -

## Additional context or screenshots (if appropriate)
-none-

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 - 20H2 
 - Kodi version: (19.0-BETA2 (18.9.821) Git:20201215-30abc954c7) (but is same on all versions i know before)

**Comment by DaVukovic** [comment]
Thanks for the report :+1:

**Comment by basilgello** [comment]
Maybe URLs should be mangled too? For ex, paths to samba shares etc.

**Comment by wsnipex** [comment]
that is exactly what this does.
it replaces all occurrences of [protocol://]_user:pass@_[host].* with [protocol://]USERNAME:PASSWORD@[host]
