### ISSUE TITLE
KODI 19 beta 2 - 3:2 pulldown on 120 Hz native refresh rate

### ISSUE THREAD

**Issue by tamodolo** [xbmc/xbmc#18971]
### Describe the bug
3:2 pulldown at 24 fps video on native 120Hz refresh rate.

## Expected Behavior
Player should land frames at the right moment creating a perfect smoth experience.

## Actual Behavior
24 fps video works properly on 24Hz refresh rate but frames don't land at the right time on 120Hz native refresh rate causing image to judder (same behavior of 3:2 pulldown for 60Hz refresh rate.

Opinion: I find 120Hz the perfect refresh rate as it is a perfect multiple of 24, 30 and 60 fps videos and am trying to avoid the blank created to switch the refresh rate.

## Possible Fix
I don't know how the player handles frame timming so it may have something to do with it?

### To Reproduce
Tested on HDMI 2.1 link using a 30 series nvidia GPU. Should be reproduced on any native 120Hz TV with any HDMI 2.0 gpu at 1440p @ 120Hz

### Debuglog
none

### Screenshots 
not possible as it is a movement impression

## Additional context or screenshots (if appropriate)
not possible

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 build 2004
 - Kodi version: 19 beta 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Do you have the option "sync playback to display" enabled?

https://kodi.wiki/view/Settings/Player/Videos#Sync_playback_to_display

I would highly recommend using refresh rate switching though as it offers the best experience.

**Comment by lrusak** [comment]
Closing as further support should be directed to the forums.

**Comment by tamodolo** [comment]
> Do you have the option "sync playback to display" enabled?
> 
> https://kodi.wiki/view/Settings/Player/Videos#Sync_playback_to_display
> 
> I would highly recommend using refresh rate switching though as it offers the best experience.

Yes. It is an actual bug. Please reopen.

**Comment by tamodolo** [comment]
I'll update this again as I just tested with SDR content and is working as expected. This is a HDR content problem.
