### ISSUE TITLE
Feature request: HDMI 2.1 QMS support 

### ISSUE THREAD

**Issue by tamodolo** [xbmc/xbmc#18972]
### Describe the bug
Not a bug.

QMS - Quick Media Transport is a VRR related tech to alow the display to match the video FPS for perfect smoth. This is also perfect for video that contain both 24 and 30 fps in progressive scan (supported by DVDs and MKV files)

## Expected Behavior
Perfect video smoth.

## Actual Behavior
The normal fixed refresh rate behavior

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 build 2004
 - Kodi version: 19 beta 2

**Comment by lrusak** [comment]
Please use the forum for feature requests.
