### ISSUE TITLE
Mounted network shares in Windows make Kodi freeze

### ISSUE THREAD

**Issue by HeresJonny** [xbmc/xbmc#18982]
### Describe the bug
Here is a clear and concise description of what the problem is:
When network shares are mounted locally with a drive letter, Kodi seems to evaluate those somehow and freezes intermittently 

When network shares are mounted locally with a drive letter, Kodi seems to evaluate those somehow and freezes intermittently This happens on startup and randomly several times while Kodi is running. The more networkshares are mounted, the longer the freezes.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Kodi should start right away and not lag/freeze during execution.

Kodi should start right away and not lag/freeze during execution. Also, Kodi should not try to follow locally mounted shares, or any local paths for that matter, as long as the path is not declared explicitly in sources.xml or possibly mediasources.xml.

## Actual Behavior

Kodi chokes on locally mounted shares. This is not visible directly in the debug log but only indirectly through the pauses in it. In my case, I had six shares to local and VPN local network. The problem aggravated when I was away from the usual enviroment in another Wifi and the shares would not connect. This let to Kodi becoming unresponsive for large periods of time. Even startup took around 30 secs.

## Possible Fix

Hopefully devs will find a fix, the workaround is to not mount any network shares locally.

### To Reproduce

1. Mount network shares locally in Windows with a drive letter.  
2. Make network shares unavailable in Windows but leave the drive letters connected.
3. Start Kodi

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/bisuwenere.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

What I did to generate the debug.log:

Created a fresh install of current Kodi Matrix nightly by removing any user folders. Started Kodi. Turned off sounds. Turned on debug logging. Added a local source for 2 TV shows. Scraped the contents. Turned off debug logging. Exit Kodi.

The whole process described above took around 9 minutes in total. There are at least 4 freezes with pauses between 10 and 40 seconds in the log. 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Matrix nightly 2020-12-22

Kodi was executed on a i7-8565U with 8 cores and 16GB RAM, running on a WD Black NVM SSD. 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HeresJonny** [comment]
Do you need more info?

**Comment by HeresJonny** [comment]
Do you need more info? You seem to be completely flummoxed with this issue, not even able to lable it.

**Comment by wsnipex** [comment]
why do you think this is a bug? To any application a OS mounted network share looks just like a local drive.
If you have those drives configured as media source in kodi, it will obviously try to access them(e.g. on library scan).
You can reduce the relevant timeouts (see https://kodi.wiki/view/Advancedsettings.xml) to limit the hangs

**Comment by thexai** [comment]
Already fixed by https://github.com/xbmc/xbmc/pull/21198
