### ISSUE TITLE
Compiling kodi on Centos 8 (8.3)

### ISSUE THREAD

**Issue by Tuxius** [xbmc/xbmc#18988]
### Describe the bug
As there is no Kodi available in the Centos Repos I am trying to compile Kodi from Source Code (to be run as a headless media server). Following the README.Linux.md instructions I get a Makefile error that I do not know how to resolve.

Here is what I did run before getting the error:
`git clone https://github.com/xbmc/xbmc kodi`
`cd kodi`
`su`
`dnf install cmake`
`dnf install libuuid libuuid-devel`
`make -C tools/depends/target/crossguid PREFIX=/usr/local`
`make -C tools/depends/target/flatbuffers PREFIX=/usr/local`

## Expected Behavior
No Error

## Actual Behavior
`make: Entering directory '/smb/winmnt/xbmc-master/tools/depends/target/flatbuffers'`
`make -C native/build-cmake  install`
`make[1]: Entering directory '/smb/winmnt/xbmc-master/tools/depends/target/flatbuffers/native/build-cmake'`
`make[1]: *** No rule to make target 'install'.  Stop.`
`make[1]: Leaving directory '/smb/winmnt/xbmc-master/tools/depends/target/flatbuffers/native/build-cmake'`
`make: *** [Makefile:56: .installed-native] Error 2`
`make: Leaving directory '/smb/winmnt/xbmc-master/tools/depends/target/flatbuffers'`

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Centos 8.3
 - Kodi version: 18.9-Leia

**Comment by DaVukovic** [comment]
Could it be possible that flatbuffers is already installed and there's no need to build it?

But anyway....support is given at the Kodi forums. This section is for bug reports only

**Comment by garbear** [comment]
See the build instructions for how to enable internal dependencies. In this case, when you use `cmake` to generate Kodi build files, use `cmake -DENABLE_INTERNAL_FLATBUFFERS=ON`
