### ISSUE TITLE
[v19.0b2] System memory usage is reported as 100% and used/total System memory is incorrect on a Sony Android TV

### ISSUE THREAD

**Issue by 88keyz** [xbmc/xbmc#18987]
### Describe the bug
Here is a clear and concise description of what the problem is:

Using v19.0b2 with a Sony X950G the System Memory Usage is reported as 100% and detected used and total memory is incorrect.

## Actual Behavior

As reported by System Info/Hardware

Total memory: 4294965515MB (actual memory reported by AIDA64 is 2.5GB or 2315MB)
Free memory: 638MB (fluctuates)

System memory usage: 4294964877MB/4294965515MB - 100%

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should be able to properly detect the system memory and report memory usage.

As reported by System Info/Hardware

Total memory: 2315MB
Free memory: 638MB

System memory usage: 638MB/2315MB - 72%

### To Reproduce

1. Install Kodi v19.0 beta 2 on a Sony Android TV
2. Check system memory reported and usage in System info/Hardware under Settings

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/litasemamo.kodi

### Your Environment
Used Operating system:

 - [ X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 9.0
 - Kodi version: 19.0 beta 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by retrofan1979** [comment]
When is a fix expected for this issue? I have the same behaviour on my Sony Bravia Android TV (KD-49XH8599). I'm on KODI 19 as well.

**Comment by phunkyfish** [comment]
Sorry, we don't provide estimates or guarantees on any fixes. We are a volunteer team, and short of active Android maintainers currently.

**Comment by retrofan1979** [comment]
Okay, I understand. Does this issue only occur on KODI 19? Maybe not on older builds of KODI?

**Comment by phunkyfish** [comment]
Don’t know and we have no way to tell. Only other uses with an Android Sony TV would know this.

Most likely it is a poor implementation of an API on the Sony device is the issue.

**Comment by retrofan1979** [comment]
Hmm, I'm not sure about that, because I tried KODI 17.6 and KODI 18.9 and those do report as the topic starter expects (and as I expect) Total memory: 2315MB and around 1500MB in use, about 65% in my case.

**Comment by phunkyfish** [comment]
Different SDKs are used depending on the version you use. I would try Kodi 19 android on a different Android device and see what it reports first. It may also depend on how the SDK interacts with the version of Android TV you have and which APIs kodi calls.

**Comment by retrofan1979** [comment]
Okay, I didn't know, thanks.

**Comment by phunkyfish** [comment]
It's kinda of tricky with Android devices. There are just so many versions, vendors etc. It makes for a lot combinations.
