### ISSUE TITLE
Constant crashes when moving the mouse or using esc or backspace on keyboard

### ISSUE THREAD

**Issue by wahboh** [xbmc/xbmc#18981]
### Describe the bug
Scanning and most times viewing is OK. BUT when trying to "go back" with either the mouse, or backspace, or keyboard, Kodi crashes. Repeatable every time just before returning to the main screen, and frequently when browsing around in setups.

## Expected Behavior
I should be able to move around in Kodi without crashes...

## Actual Behavior
Crash. Sometimes 100 repeatable, 

## Possible Fix
Something about using a 4K screen..?

### To Reproduce
1. Return from ANY list of items to main screen
2.Crash

### Debuglog
https://1drv.ms/u/s!AlN5qgz_44Y-gj_u6v-Wh6_EpFYS?e=DxKQRX

### Your Environment
Used Operating system:

 - [X ] Windows 10 20H2, AMD Ryzen 12 core processor, 64GB RAM, Nvidia Geforce GTX 960

 - Operating system version/name:
 - Kodi version: 18.9 64 bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Please post your log to https://paste.kodi.tv/

**Comment by wahboh** [comment]
Sorry for the delay. The dump files are binary. What I can see only text files can be pasted at paste.kodi.tv? Therefore I gave a link to my OneDrive with a zip file with the binary dump. Btw, the text log files give very little about the crash itself.

**Comment by KarellenX** [comment]
Ok, but most of us won't download zip files. I certainly won't. 

If  you can, separate your DebugLog from the rest of your report and paste it at kodi paste.
Thanks.

**Comment by wahboh** [comment]
kodi.log: https://paste.kodi.tv/exacijixof.kodi
kodi.stacktrace: https://paste.kodi.tv/vaguvuleku

Just curious how you are able to get useful stack trace info from from any of these files without the dump itself? If you need it, pls advice me on how to make it available to you in a safe way.

Thanks

**Comment by wahboh** [comment]
Kodi log with debug enabled: https://paste.kodi.tv/atetayilah.kodi

With debug enabled, I can't reproduce the crash. Without debugging, the crash is 50-70% repeatable. Timing error?

**Comment by KarellenX** [comment]
Thanks but neither of those logs show any problems. 

Your first log is useless as debug mode was not enabled. The second log misses out the startup extended logging as you enabled debug mode after startup so I could not see video and audio drivers being loaded (which is the usual cause of crashes). In future, please follow the correct steps to create a debug log.

At this stage, there is no issue visible. Whatever issue you are experiencing is localised to your setup and not a general Kodi bug. I and many of the developers here are using Windows setup, so we know there is no Kodi bug like you described.

I'll close this issue. Please post on the forum to receive assistance. But there is nothing we can do until you capture the crash in your debug log.
