### ISSUE TITLE
Kodi startup issues v19.0-Beta2 on install

### ISSUE THREAD

**Issue by im000000** [xbmc/xbmc#18992]
### Describe the bug
Here is a clear and concise description of what the problem is:

Using Samsung Galaxy Tab S7+ 
One UI version: 2.5
Android 10

I upgraded Kodi from v18 in Google Play store to Beta by opting into Beta Program.

Kodi initially started up briefly showing startup logo then the screen went blank.    No UI was displayed, tried different touvh gestures but no luck.

Tried to clear cache , the clear Data but no luck.

Launching Kodi would end up with a blank screen but I could still intreract with other android apps -- just Kodi showing blank screen.

I uninstalled Kodi about 2 more times and still having the same behavior.   

Then by accident I happened to launch Kodi when tablet was in **Portrait** mode and I could then see the UI.  Then swithed back to Horizontal mode.

All while I was using Kodi before it was in Horizontal mode.

I continued to experience blank screen startup 2 or more times but trying to switch orientation didnt seem to be what fixed it.

Haven't experienced this behavior since, I can launch Kodi ok but will open a ticket for other issues I noticed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Launching Kodi should show the main window so user can interact with the app, instead of showing a blank screen with no widgets being displayed.

## Actual Behavior

After initial clean install I would launch Kodi and it would run but I would see a blank screen.

## Possible Fix

This bug could possibly be hardware or OS specific,   I upgraded my Nvidia Shield TV from Kodi v18 to Beta2 v19 and didnt experience this issue.

Not sure launching Kodi when tablet is in portrait mode is reproducible -- as i wasnt able to get UI to dispaly when it happened again.

Havent noticed the same behavior since, could be specific to post install actions.

### To Reproduce

1. uninstall Kodi if installed.
2. install Kod v19 Beta 2 from Google Beta program ( need to opt-in )
3. once Kodi is installed, launch it -- you will briefly see the startup screen with the scrolling matirx characters, before screen becomes blank.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I was trying to test new version to see if I can tolerate using it as a daily driver.
So far I havent noticed that behavior but if it were to happen all the time it would be a deal breaker.

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kov v19 Beta-2 ( Dec 26 2020 -- Google Play Store after opting into Kodi Beta program )

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by strugee** [comment]
> The debuglog can be found here:

You need to post your logs: https://kodi.wiki/view/Log_file

**Comment by im000000** [comment]
[kodi (copy).zip](https://github.com/xbmc/xbmc/files/5753099/kodi.copy.zip)

i have included a compressed zip file of the error -- this line is repeating endlessly in attached log 
2020-12-29 23:15:43.352 T:19653   ERROR <general>: GetCharacter: Unable to cache character (out of memory?)
2020-12-29 23:15:43.352 T:19653   ERROR <general>: GetCharacter: Unable to cache character (out of memory?)
2020-12-29 23:15:43.352 T:19653   ERROR <general>: GetCharacter: Unable to cache character (out of memory?)
2020-12-29 23:15:43.352 T:19653   ERROR <general>: GetCharacter: Unable to cache character (out of memory?)
2020-12-29 23:15:43.352 T:19653   ERROR <general>: GetCharacter: Unable to cache character (out of memory?)
2020-12-29 23:15:43.352 T:19653   ERROR <general>: GetCharacter: Unable to cache character (out of memory?)
2020-12-29 23:15:43.352 T:19653   ERROR <general>: GetCharacter: Unable to cache character (out of memory?)
2020-12-29 23:15:43.352 T:19653   ERROR <general>: GetCharacter: Unable to cache character (out of memory?)
2020-12-29 23:15:43.352 T:19653   ERROR <general>: GetCharacter: Unable to cache character (out of memory?)

**Comment by DaVukovic** [comment]
probably something for @peak3d to look into?!

**Comment by nRaecheR** [comment]
The problem still remains with Release 19.0 and my Samsung Galaxy Tab S7 and Android 11.  Got the same GetCharacter error in the log. 

Log here: [kodi.log.txt.gz](https://github.com/xbmc/xbmc/files/6215893/kodi.log.txt.gz)

**Comment by nRaecheR** [comment]
The problem still exists with 19.1 release, it makes the app unusable on the tablet. Only one of 50 starts the GUI gets rendered and after that the app works as expected, maybe it's a timing problem at startup. You can actually hear the actions when you try to navigate through the GUI but you can't see it because the screen is empty. 

Deleting the cache/data or forcing the render resolution of the GUI to a fixed value (e.g 1920x1080) won't help. Just playing a video shared by another application works but the GUI elements aren't accessible then. 

Is there any information I can provide to help tracking down the bug?

**Comment by omglikesam** [comment]
Change the refresh rate in settings-display-motion smooothness to 60Hz?

**Comment by nRaecheR** [comment]
This is an Android setting. I haven't tested it yet, but I don't want to loose the snappiness of the UI just because there's a bug in one app. But, I will test it with the limited refresh rate.

**Comment by nRaecheR** [comment]
Duplicate https://github.com/xbmc/xbmc/issues/15872
