### ISSUE TITLE
playback error after upgrading mi box 3 international version from android 8.0 oreo to android 9.0 pie

### ISSUE THREAD

**Issue by mightyabhi** [xbmc/xbmc#18995]
hi, need help. after updating to android 9.0 on my box 3 international version, im getting playback issue. I'll ealborate. I was using kodi 18 on my android oreo and after updating to android 9, if i play something in kodi 18(any version) and click home button and try to play video in any other app like youtube hotstar amazon prime voot etc it does not play and all apps gives some kind of error like playback error on hotstar saying media services unavailable please restart your device OR something went wrong in youtube while playing video. Now i tried force stopping kodi and other apps and trying again but videos just doesnt work even if i go back to kodi again videos wouldnt play. this is not a problem related to kodi 18 as it was working fine in oreo update. the problem started after android 9 update. even yesterday i recieved another update which added the peel mi remote support which was approximately 700mb and i was hoping that this update might fix the issue but it didnt as well. the only way to fix this issue is to completely restart mi box than as long as i do not play any videos in kodi the problem doesnt appear in any app but as soon as i  play video in kodi it plays few times but does not play after switching to youtube or any other video app. kindly help me out as this made my mi box 3 unusable. after searching the internet for months i came here to seek solution. kindly help mi developer pls. why u guys make buggy update to render the device unusable or atleast give the option to roll back update if the updates are going to make the device completely unusable. please help. thanks

**Comment by DaVukovic** [comment]
If
Kodi 18 and Android 8 ==  everything went fine
and then
same Kodi 18 and Android 9 == nothing works like before
and every other android user doesn't have such a problem, I would guess, this is not a Kodi issue at all and might probably an issue with Android 9 specifically to your device in use.

But anyway...please provide a debuglog. I'll mark this a "ignored rules" for the time being as you completely ignored our template. But we will at least need to see a debuglog to have any kind of guess what might go wrong on your side.
