### ISSUE TITLE
Can not set my own cacert.pem on android without root

### ISSUE THREAD

**Issue by lukavia** [xbmc/xbmc#19006]
### Describe the bug
Here is a clear and concise description of what the problem is:

On an Android system system there is no option to use your own cacert.pem file as described in https://kodi.wiki/view/SSL_certificates
There is actually no way to set the environment SSL_CERT_FILE on your phone for example.

The problem is also described on the forums several times: 
https://forum.kodi.tv/showthread.php?tid=345878
https://forum.kodi.tv/showthread.php?tid=350721
https://forum.kodi.tv/showthread.php?tid=345894

It seams that SSL_CERT_FILE gets set to special://xbmc/system/certs/cacert.pem which from the log get's set to /data/user/0/org.xbmc.kodi/cache/apk/assets which is not writable without root access

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If I place a file in kodi home system/certs/cacert.pem I would expect kodi to use that file instead of the build in one. 
That way I can upload my cacert.pem file and place it in /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/system/certs/cacert.pem and solve the problem on any system

## Actual Behavior

Placing certs/cacert.pem file in the kodi's home system directory has no effect

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
https://pastebin.com/LHmhRDnN

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by wsnipex** [comment]
correct, this probably needs an advancedsetting to override the location of the cacert file

**Comment by wsnipex** [comment]
see https://github.com/xbmc/xbmc/pull/19030
please try the build from https://jenkins.kodi.tv/job/Android-ARM64/17050/

**Comment by lukavia** [comment]
Thank you very much for your reply. Since the plugin that I'm having problem is not compatible with v19 I was wondering is there a beta build with that patch for v18? 
Or will that patch be in v18 at all? 

If not, then I'll get to upgrading the plugin

**Comment by wsnipex** [comment]
v18 is EOL, there won't be any fixes anymore

**Comment by lukavia** [comment]
OK. 
I've fixed the addon to work with 19 and can confirm that with the nightly you've provided it works and I can set my trusted certificates bundle. 

One thing that is kind of confusing is that I first tried to set special://masterprofile/cacert.pem but that didn't work. 
I had to set it to /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/cacert.pem which would be hard for a normal user. 
So can you specify if the path can be relative and if so relative to where? 

P.S. Thank you very much for the great work

**Comment by wsnipex** [comment]
right, I've updated the PR to support special:// paths as well, here is a new build: https://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20210109-f18fae88-PR19030-merge-arm64-v8a.apk

**Comment by lukavia** [comment]
Confirm. I've installed the new build and changed the path to spetial://masterprofile/cacert.pem. 
Work great. 

Thank you very much

**Comment by wsnipex** [comment]
thanks for testing
