### ISSUE TITLE
Lot of "timeout waiting for buffer" warnings and video freeze while audio still works

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#19011]
### Describe the bug
Here is a clear and concise description of what the problem is:

i am not sure if it's ok to open this Issue request,
i don't know exactly where to start to track the problem, if possible have some suggestions
at first i thought it was a network problem, but after switch from Wifi to LAN wired cable this problem persist
and seem happen only from my HT-PC, i also reset the network configuration and reinstalled the video drivers nothing changed.

In last months i have noticed these messages repeated several times in the logs while playing Nflx videos:
`WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer`
I have always ignored these messages... although i remember that in the Alpha builds of Kodi 19, it never did.

but lately the situation seems to have aggravated:
apparently randomly happen that the video freeze for about 2 secs (while sounds still works)
then the images scroll quickly until they reach audio/video synchronisation,
similarly when the kodi buffer gets stuck

one time is happened also that when i was watching after about 40 minutes and after several video freeze, the video has frozen permanently (the same image was printed on the screen and no longer updated) and i had to press Stop.

yesterday i was watching the film and towards the end when i pressed Stop, Kodi has brutal crashed, unfortunately the log has no debugging enabled, and Kodi has no DMP file written

The freeze happen only when i play with InputStreamAdaptive, the warning messages also when playing local files

I don't know if all things are correlated, but I have never had all these problems until now

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would like it to go smoothly

## Actual Behavior

the video randomly freeze but audio sound still works good

### To Reproduce

This warning not happen on my personal computer, i do not know if is something related to hardware and/or kodi display settings

1. Install Ntfx add-on
2. Play a video

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/uboxewexer.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The HT-PC configuration is:
Adjust display refresh rate: Start/stop
Sync playbac to display: Off
Display mode fullscreen (no fullscreen window)
Whitelist enabled to all 1080p freqs and Allow double refresh rates enabled
on a NVIDIA GT-1030 Driver version 460.89

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Kodi 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
update today not happen anymore no warning messages no freezes
I have now cleaned advancedsettings.xml and enabled debug in background
I will keep track of future abnormal behaviours

**Comment by KarellenX** [comment]
Hello @CastagnaIT 

If you can no longer replicate it, do you mind if I close this report?

If you find that you can replicate the problem again, it is no problem to re-open it.

**Comment by CastagnaIT** [comment]
I tried many times yesterday and could not reproduce the problem again
I don't know what happened..
then yes i close i will reopen if needed

**Comment by CastagnaIT** [comment]
happened again
new log is: [kodi.log](https://github.com/xbmc/xbmc/files/5762304/kodi.log)
this time debug enabled

same thing video freezed for some seconds (where in the log there are the warnings, see last lines) meanwhile the sound works,
someting more in log:

`DEBUG <general>: CPtsTracker: pattern lost on diff 0.000000, number of losses 1`

then i waited until the video to synchronise with the sound,
then i press Stop and Kodi has crashed brutally, no DMP file written

**Comment by CastagnaIT** [comment]
i suspect is related to InputStreamAdaptive addon
and the high traffic on the servers of those days

my suspect is that the download of the stream chunks would sometimes interrupted and make Kodi crash
in the last 2 weeks no more problems happened

i close it again
