### ISSUE TITLE
Notify user about add-ons installed by third-party means outside of Kodi UI

### ISSUE THREAD

**Issue by basilgello** [xbmc/xbmc#19017]
### Describe the bug

Mainstream Linux users (Debian, Ubuntu, Arch, etc) use system package managers (dpkg, apt, pacman etc) to install Kodi binary add-ons packaged for their distro, not building them from source or downloading the prebuilt packages from third-party locations.

After such binary addon gets installed and Kodi is started next time, the addon is disabled by default for security reasons and no notification is popped to the user guiding him how to enable & configure that addon.

It can also become a security feature: the same detection mechanism will detect malicious add-ons copied to system or user `addon` directory and if the user did not install anything manually and it was not an update of existing addon or its dependency via Kodi UI, the user will get notified about new addons one needs to enable.

## Expected Behavior

On Kodi start-up, the new logic scans the add-ons deployed and checks if the particular addon was processed by Kodi add-on framework:

* User has installed it manually,
* It is a dependency of a system or user-installed addon,
* It is an add-on installed by a third-party tool (i.e apt) but notification showed to user

The add-ons not falling under any of these conditions are collected and the notification similar to xbmc.versioncheck is popped on the screen:

New add-ons were installed since the last Kodi shutdown:

… list …

Do you want to proceed configuring them?

Yes / No

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian 10 buster
 - Kodi version: 19.0 beta2

@phunkyfish @howie-f what do you think? Can we implement this in v19 still? Debian users keep asking me why addons installed from Debian show no signs of life and I have to explain again & again how to enable and configure them.

**Comment by phunkyfish** [comment]
Depends if we consider this a bug or not. If it’s a feature I’m not sure it can go into 19.

But as I don’t use Linux I’ll leave it to @howie-f and @ronie to classify it. @DaveTBlake would have final call on it.

**Comment by DaVukovic** [comment]
Just to be clear. On Ubuntu, it depends how the user installs Kodi. If the user installs Kodi from the Ubuntu-repos, then the binary add-ons from that repo should be fine as well (if available). If the user installs Kodi from the Kodi PPA, then he will also get the binary add-ons from that PPA and there shouldn't be any issue. 

If a user switches to the Kodi PPA after he previously installed Kodi from the Ubuntu/Deban repo, Kodi and those add-ons should be updated after the next `sudo apt update && sudo apt upgrade -y`

**Comment by basilgello** [comment]
>Just to be clear. On Ubuntu, it depends how the user installs Kodi. If the user installs Kodi from the Ubuntu-repos, then the binary add-ons from that repo should be fine as well (if available). If the user installs Kodi from the Kodi PPA, then he will also get the binary add-ons from that PPA and there shouldn't be any issue. 
>
>If a user switches to the Kodi PPA after he previously installed Kodi from the Ubuntu/Deban repo, Kodi and those add-ons should be updated after the next `sudo apt update && sudo apt upgrade -y`
>

The issue here is **not** the origin of add-on or whether the addon loads or not. The issue is the fact that the user often has no clue that he must go to Settings - Add-ons -> Installed add-ons, select the addons he did install using 'apt-get', enable each addon and configure it where applicable. This might not be the case when the user installs Kodi add-ons via Kodi UI, as he sees the freshly-installed add-on marked with "x" (disabled) and he knows he should enable it manually in order to use it.

This is just the UX edge case that manifests only in Debian / Ubuntu / other distros packaging Kodi.

**Comment by basilgello** [comment]
Also, Debian / Ubuntu users installing Kodi from PPA (especially nightly) are generally more tech-savvy than the users who install Kodi from Debian main repository using GUI tools like Ubuntu Software center. This fix simplifies life for this wider audience.

**Comment by phunkyfish** [comment]
It’s a fair point. Let’s see what @howie-f has to say. I know we discussed it previously as something we should do for v19 when we get closer to stable release. But we may have forgotten to go back to it or there was a reason it wouldn’t work. I don’t remember which it was.

**Comment by howie-f** [comment]
@phunkyfish
yes, i think that is on our todo, but simply got forgotten.. i'm afraid
it crosses over with add-ons that are disabled because of incompatibility - and reinstalled manually afterwards.
they should also get auto-enabled.

agree this simplifies life, i have the same "problem" with my `pvr.hts` and need to workaround. The `would you like to configure and enable?` Dialog would be a good option here. 

so i'll have a look on how that could be implemented.
looks possible for v19, maybe not the final but a first point-release.
depends on what @ronie and @DaveTBlake think about it

**Comment by phunkyfish** [comment]
I think implement it if you have the time and if it can’t go into v19 it can always be first into v20

**Comment by basilgello** [comment]
>I think implement it if you have the time and if it can’t go into v19 it can always be first into v20

If it is implemented, nothing can stop me from integrating the PR into Kodi From Debian v19, just like I do with CDateTime stuff :)

**Comment by wsnipex** [comment]
this would really be a nice to have, specially for the average user and should also reduce the support burden.
