### ISSUE TITLE
Kodi does not properly shut down when loaded via lightdm (PVR Manager failed to execute wakeup command)

### ISSUE THREAD

**Issue by M-Reimer** [xbmc/xbmc#19014]
### Describe the bug
Here is a clear and concise description of what the problem is:

If I start Kodi via lightdm, then startup works well but the PVR wakeup time never gets set in this setup. The error message, I get, is:

    ERROR: SetWakeupCommand: PVR Manager failed to execute wakeup command '/usr/bin/kodi-setwakeup 1610273400': Block device required (15)

My guess is that the system is already shut down too far once this command gets executed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I guess the expected behavior would be that Kodi does all the cleanup work, save settings, call PVR wakeup command, ... before actually sending the "shutdown query" to the system.

## Actual Behavior

PVR recordings fail as the wakeup time is not set properly and so the ACPI wakeup won't happen.

## Possible Fix

The only fix is to use the (officially unsupported) kodi-standalone-service to call Kodi as a system service. For some reason the shutdown is delayed long enough that the wakeup command always executes properly.

### To Reproduce

1. Configure lightdm to autostart into Kodi
2. Configure a wakeup command
3. Reboot the system and check your kodi.log afterwards

### Debuglog

The debuglog can be found here:

https://gist.github.com/M-Reimer/1ddc1104713c83e4005cbee2d06b8cbd

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux
 - Kodi version: 18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by M-Reimer** [comment]
OK. Maybe someone from the Kodi team can answer me why I seem to have the following effect:

After several tries the error did not occur for a **Power off** from the Kodi menu **but** the problem seems to occur every time for a **Reboot**. I wonder why this is. If this really only is a problem for reboots, then this would be way less problematic. If I have no answer until tomorrow, I'll do a few more tries (around 10 "power off" and 10 "reboot") just to see if this really is somehow different between rebooting or shutting down.

If the issue only happens on reboot, then it is way less problematic. The system will come up again immediately after rebooting anyway.

**Comment by wsnipex** [comment]
please test with v19

**Comment by malard** [comment]
with no reply for 3 years, closing
