### ISSUE TITLE
Empty EPG in both Kodi UI and JSON-RPC after no-change EPG refresh via PVR IPTVSimple

### ISSUE THREAD

**Issue by basilgello** [xbmc/xbmc#19028]
### Describe the bug

Refreshing M3U and EPG using PVR IPTVSimple completes but both Kodi UI and JSON-RPC return empty 'epgnow' and 'epgnext' infos. This happens regardless of whether the EPG for today is present in the database.

## Expected Behavior

Refreshing EPG should not reset EPG infos for current day.

## Actual Behavior

1. The IPTV Simple client fetches M3U and EPG with a modification timestamp of yesterday
2. The IPTV Simple,client completes importing channels and markers from clients:

```
2021-01-05 17:29:22.340 T:1474     INFO <general>: EPG thread started
2021-01-05 17:29:53.948 T:1477     INFO <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadChannelEpgs - Loaded '9061' EPG channels.
2021-01-05 17:30:06.746 T:1477     INFO <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEpgEntries - Loaded '53005' EPG entries.
2021-01-05 17:30:06.779 T:1477     INFO <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEPG - EPG Loaded - 41827 (ms)
```

3. No persistence takes place yet.
4. Kodi UI shows no EPG entry playing:
![IMG_20210105_184424](https://user-images.githubusercontent.com/3913291/103710591-1040e100-4fbe-11eb-93b2-bda6c442e313.jpg)

5. JSON-RPC also returns empty 'epgnow' and 'epgnext' tags, as shown in Yatse remote:

![signal-2021-01-02-181257](https://user-images.githubusercontent.com/3913291/103710681-4da56e80-4fbe-11eb-949c-c6e6c989d727.png)

despite requesting detailed channel EPG via JSON-RPC returns full EPG programme:

![signal-2021-01-02-181303](https://user-images.githubusercontent.com/3913291/103710726-6f065a80-4fbe-11eb-8617-0fbb212132de.png)

### Debuglog

The debuglog can be found here:
[kodi.log.txt](https://github.com/xbmc/xbmc/files/5773103/kodi.log.txt)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian buster (stable)
 - Kodi version: 19.0 beta2

**Comment by basilgello** [comment]
@phunkyfish

**Comment by phunkyfish** [comment]
Is the guide populated correctly in the kodi UI?

**Comment by ksooo** [comment]
Which Kodi version exactly? Try latest master and report back, please. There was such an issue which I have fixed some time ago.

**Comment by ksooo** [comment]
As I said, try latest Kodi master. The issue should be fixed there.

**Comment by basilgello** [comment]
> Which Kodi version exactly? Try latest master and report back, please. There was such an issue which I have fixed some time ago.

It is 19.0~git20201219.c9da8b4

> Are you using default skin?

Yes, Estuary.

**Comment by basilgello** [comment]
> As I said, try latest Kodi master. The issue should be fixed there.

OK, let me build it within an hour and test if it works. Leaving the issue open for a week to collect reliable statistics.

**Comment by ksooo** [comment]
> It is 19.0~git20201219.c9da8b4

 Definitely too old. You need at least eb0d8fcba13b3c1d11a4b560c57e8688e402a3ec.

**Comment by basilgello** [comment]
I built the master trunk tonight and started testing it.
-- 
Vasyl Gello
==================================================
Certified SolidWorks Expert

Mob.:+380 (98) 465 66 77

E-Mail: vasek.gello@gmail.com

Skype: vasek.gello
==================================================
호랑이는 죽어서 가죽을 남기고 사람은 죽어서 이름을 남긴다

**Comment by ksooo** [comment]
> I built the master trunk tonight and started testing it.

 Any results?

**Comment by basilgello** [comment]
Works fine these days @ksooo Thanks a lot!

**Comment by ksooo** [comment]
@basilgello glad it works now. closing the issue...
