### ISSUE TITLE
Music stops playing when exiting to Android home page with Kodi v19

### ISSUE THREAD

**Issue by kehongnvidia** [xbmc/xbmc#19022]
### Describe the bug
Here is a clear and concise description of what the problem is:

After installing Kodi v19, music playback stops when exiting to Android home page.  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

With Kodi v18, background music playback (playing music in Android home page) works fine.  

With Kodi v19, this feature does not work.  When exiting to Android home page, music play stops. 

## Actual Behavior

With Kodi v19, this feature does not work.  When exiting to Android home page, music play stops. 

### To Reproduce

1.  Install the latest Kodi v19
2. Start music playback
3. Exit to Android home page

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android - Shield TV
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nvidia Shield TV, SW version 8.2.1
 - Kodi version: Kodi v19 Beta 2
[bugreport_kodi_backgroundmusic_stop.zip](https://github.com/xbmc/xbmc/files/5767128/bugreport_kodi_backgroundmusic_stop.zip)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Try latest nightly build or RC1 once it is available. The issue should be fixed there.

**Comment by kehongnvidia** [comment]
verified with the latest nightly Android build and it works. 

closed
