### ISSUE TITLE
"Media Source" section is completely removed under Video pages with Kodi v19

### ISSUE THREAD

**Issue by kehongnvidia** [xbmc/xbmc#19021]
### Describe the bug
Here is a clear and concise description of what the problem is:

"Media Source" is completely removed with Kodi v19

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Under Videos page should have "Media Source" section which show all of mounted storage devices (NAS/USB drive) as seen below screen capture of "Video" page with Kodi v18
![image002](https://user-images.githubusercontent.com/46831741/103585959-f5288100-4e98-11eb-9b87-eca3ee73c04c.png)

## Actual Behavior

"Media Source" is completely removed with Kodi v19

### To Reproduce

1.  Plug USB drive and mount NAS to Shield TV
2. Install Kodi v19
3. Check Videos page

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

Media source available in Kodi v18

![image002](https://user-images.githubusercontent.com/46831741/103586071-31f47800-4e99-11eb-8b0f-f2c220ba8ff4.jpg)

Media source removed in Kodi v19
![kodi](https://user-images.githubusercontent.com/46831741/103585378-d07fd980-4e97-11eb-8fb8-5b7d0498b94d.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android - Shield TV
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Shield Android TV SW Version 8.2.1
 - Kodi version: v19-Beta2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Working for me using last nights nightly on Windows 10 64bit

![mediasource](https://user-images.githubusercontent.com/44626605/103598698-6464aa80-4f57-11eb-87ac-50ae8d7fa548.jpg)

**Comment by kehongnvidia** [comment]
I've tried with the latest nightly Android build (http://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/kodi-20210104-b783517b-master-arm64-v8a.apk) and the issue is still present

**Comment by DaVukovic** [comment]
Tried with a USB drive on my NVidia Shield and that's shown as a media source at the Kodi GUI. I'm currently using the same nightly as you are. 

Please be aware, that the USB1 port is not available for USB-storage devices if "Transfer files to a computer using USB" is enabled at the shield settings. Either use another USB port or turn that setting off.

All other media sources I've added to Kodi using the Kodi GUI (NFS shares from my NAS) are shown as well. 

Please consider asking at the forums as this seems to be either a problem with the shield settings or maybe a problem with a USB-storage device, but it's obviously not a general Kodi problem.

**Comment by kehongnvidia** [comment]
When I installed Kodi v18, Media source is available for adopted USB storage and NAS mounted via Shield Storage option.  Soon after I update Kodi app to v19, I dont see Media source under Videos.   I'll check forum to check.  But I feel like this is Kodi app issue

**Comment by kehongnvidia** [comment]
It looks like people in forum has reported a similar issue, https://forum.kodi.tv/showthread.php?tid=359611, https://github.com/xbmc/xbmc/issues/19023

**Comment by hoppel118** [comment]
> All other media sources I've added to Kodi using the Kodi GUI (NFS shares from my NAS) are shown as well.

That is not the point. You have to try to mount a smb share from the shield’s android os, not from Kodi.

Different users in the German Kodinerds Community reported this issue for the nvidia shield tv. So I decided to open an issue here:

https://github.com/xbmc/xbmc/issues/19023

There is also described where to connect smb shares at the os level.

I didn’t try usb drives.

Regards Hoppel

**Comment by DaVukovic** [comment]
I've tried to add a SMB share from my NAS, but obviously I'm not able to mount any share via the Android OS whereas I'm able to mount the same shares via my desktop PC. 

So I can't test with SMB shares mounted by Android.

Still, USB drives will show up in Android as a available storage and also will show up in Kodi as sources without them being added in Kodi as a source.

**Comment by DaVukovic** [comment]
We talked about that internally at our monthly team meeting. Other team members are able to add SMB shares on the OS level. The problem here with SMB is, that fixing this issue needs hardware specific hacks and we decided to not do that anymore. The NVidia Shield is the only device available which offers to mount SMB shares on the OS level directly. 

Using SMB shares works as usual from inside Kodi
USB drives are also still shown up as sources. 

So it's not a general Kodi bug the team will fix.

**Comment by da-anda** [comment]
I also gave it a try, and simply plugging a USB HDD to the SHIELD worked just fine for me. It showed up right away in my video sources, just like any removable storage shows up f.e. in KODI on Windows. So I can not confirm any issues with connected USB drives on the SHIELD.

However, I was able to reproduce that KODI does not list OS mounted SMB shares on the SHIELD, but neither does f.e. VLC.
And as it has been mentioned, those seem to be a SHIELD specific feature and we do not add support for vendor specific features anymore. If the SHIELD is providing these mount points via regular Android APIs and we happen to use this API wrong, that would ofc be something we would fix, but without any active Android maintainer we can not really say if it's us doing anything wrong or not. The way we use this API did not change to our knowledge.

**Comment by Entara07** [comment]
> 
> 
> I've tried to add a SMB share from my NAS, but obviously I'm not able to mount any share via the Android OS whereas I'm able to mount the same shares via my desktop PC.
> 
> So I can't test with SMB shares mounted by Android.
> 
> Still, USB drives will show up in Android as a available storage and also will show up in Kodi as sources without them being added in Kodi as a source.

It's a shame this issue won't be fixed. Even though it appears only on the NVidia Shield, it is the most used multimedia device. There is a 12 pages long post on the Kodi forum talking about this.
I hope someone will find how to fix it. Meanwhile I'll have to downgrade to the 18.9.
Good luck to the team!

**Comment by kehongnvidia** [comment]
> I also gave it a try, and simply plugging a USB HDD to the SHIELD worked just fine for me. It showed up right away in my video sources, just like any removable storage shows up f.e. in KODI on Windows. So I can not confirm any issues with connected USB drives on the SHIELD.
> 
> However, I was able to reproduce that KODI does not list OS mounted SMB shares on the SHIELD, but neither does f.e. VLC.
> And as it has been mentioned, those seem to be a SHIELD specific feature and we do not add support for vendor specific features anymore. If the SHIELD is providing these mount points via regular Android APIs and we happen to use this API wrong, that would ofc be something we would fix, but without any active Android maintainer we can not really say if it's us doing anything wrong or not. The way we use this API did not change to our knowledge.

If you connect USB drive via adopted storage instead of removable storage, Kodi v19 does not show this device under "Media Storage"    This issue is also observed with Sony TV android TV as well!!

**Comment by kehongnvidia** [comment]
This issue is resolved with the latest nightly build.  It's probably fixed with https://github.com/xbmc/xbmc/pull/19523
