### ISSUE TITLE
Why Kodi a so complex program dont have a simple copy paste option for paste keys?

### ISSUE THREAD

**Issue by skarmiglione** [xbmc/xbmc#19025]
### Describe the bug
Here is a clear and concise description of what the problem is:
Why if you know we need paste so large numbers to use the youtube app you dont make a option to copy paste easily? it look so great but is so unuseful interfaz make me angry.... then i should copy letter and number by number in a modern software? i dont understand what purpose it resolve a lack in a so simple thing... whats up guys.... copy paste is so basic? API keys manually in the sXXI? wtf?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by chewitt** [comment]
Closing as this is a bug tracker not a whinge collector. Whinging and feature requests should be done in the forums.

**Comment by awsms** [comment]
> feature requests should be done in the forums.

https://forum.kodi.tv/showthread.php?tid=323460
This definitely was useful.
