### ISSUE TITLE
Android (Nvidia Shield) smb shares do not appear in Kodi 19

### ISSUE THREAD

**Issue by hoppel118** [xbmc/xbmc#19023]
### Describe the bug
Here is a clear and concise description of what the problem is:

I recently downloaded and installed Kodi Matrix version for testing purposes.

In the German Kodinerds Forum we noticed that smb network shares connected via Android OS are no longer shown under Kodi Matrix.

I don't know if this is a general Android option or if it is an Nvidia Shield TV specific option.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

1. Add your smb network storage at Android OS level to your Nvidia Shield: [HOW TO ADD NETWORK STORAGE](https://www.nvidia.com/en-gb/shield/support/shield-tv/connecting-storage-to-your-shield/)
2. Look at Android file manager (for example Xplore). You see all the mounted shares. It looks as follows:

![android-smb-x-plore](https://user-images.githubusercontent.com/991344/103621467-8a795300-4f35-11eb-863b-796d5c2e7931.jpeg)
 
3. Look at Kodi Leia file manager. You see all the mounted shares. It looks as follows:

![android-smb-leia](https://user-images.githubusercontent.com/991344/103621513-9f55e680-4f35-11eb-995b-4e123da0a335.jpeg)

## Actual Behavior

4. Look at Kodi Matrix file manager. You don't see any android mounted share. It looks as follows:

![android-smb-matrix](https://user-images.githubusercontent.com/991344/103621646-cf9d8500-4f35-11eb-9543-a44e4daa6dc4.jpeg)

## Possible Fix

I don't know a fix for this. But you can still mount smb shares via Kodi: https://kodi.wiki/view/SMB

### To Reproduce

Look at the steps above.

### Debuglog

The debuglog can be found here:

If you need a debug log for this, let me know which debug components to activate. 

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: **Android OS - Nvidia Shield Experience 8.2.1**
 - Kodi version: **kodi-20210102-a71d8ffe-master-arm64-v8a.apk**

**Comment by wsnipex** [comment]
sounds like a permission issue, but our psychic powers are limited ;)

**Comment by hoppel118** [comment]
Empower my psych, please... What permissions can be set to get it to work under Kodi Matrix, while it works in other apps without setting up special permissions? ;)

Different users in different communities recognized this „issue“ for Kodi Matrix.

Is here any user with a Shield and smb shares who has them connected from os level?

Maybe it’s the same for other Android devices.

Regards Hoppel

**Comment by fritsch** [comment]
Might be the SDK change, which required this "legacy flag" to be set. Perhaps that's the reason why they disappear, see: Perhaps the testbuilds from: https://github.com/xbmc/xbmc/pull/18893 are still available for testing.

**Comment by hoppel118** [comment]
Hi @fritsch 

did you recognize that I already commented that issue?

@Maven85 gave us a custom builds with a unique app name and directory to test if it gets solved with these changes. It was not the case.

Any other ideas?

Regards Hoppel

**Comment by fritsch** [comment]
No - I only recognize reports that include a debuglog - and besides the other thingy nothing comes into my mind. So therefore - no ideas.

**Comment by hoppel118** [comment]
@fritsch Which debug components should I activate to get the correct log file?

Thanks

**Comment by dilusion** [comment]
Hello having the same problem here.
Nvidia shield - network storage added in Android.

In Kodi 18 they show normally - in 19 they are missing.

**Comment by KylePreuss** [comment]
Kodi auto-updated to 19 on my Shield this morning. SMB shares mounted in Android are no longer showing up in the app.

**Comment by Morhoo** [comment]
+1 same issue

**Comment by fritsch** [comment]
Android is currently not maintained. Please don't spam with +1. If something changes you are the first that are pinged.

If you can contribute code, now is the time to standup for your platform.

**Comment by Timbo200** [comment]
I realize that answering the same questions over and over again for experienced members is tiring, but not everybody is either experienced or an expert.

I updated today and got bitten by the same issue.  For me I'm attached a Synology NAS using SMB.  I was able to get the share recognized again after going into the NAS and changing it from only SMB1 to allow both SMB2 and SMB3.

**Comment by dotnet555** [comment]
I'm also using a Synology NAS, and changing the SMB protocol (min V1 - max V3 both on Kodi and on the NAS) didn't work for me, but I found another hack that works in my case:
- I added the NAS' folders as Mapped Network Drives from the Shield's OS settings.
- The mapped network drives does not show up anymore in the Kodi Matrix version, but i can I can still access them if I add them manually in Kodi's favourites.xml with a text-editor. The path is something like "/storage/<NAS Name>/<share>/". If you're in doubt on how to write it, add at least one favorite from the GUI to have a template to edit.

Oddly enough, if I add the same source in the sources.xml (either via GUI or via manual edit), it still gives "Path not found or invalid".

So, the access mechanism used by the favourites is probably somewhat bypassing something that the sources are doing, or maybe they are using a completely different set of or code, or whatever.

Hope this helps someone, and maybe gives some hints to some developer.

Just, please, leave the favourites as they are, until this sources' problem is fixed. ;)

**Comment by TheDeanMan** [comment]
Can confirm as an issue. My mounted network drive is no longer showing up in Kodi on my NVidia Shield as of the 19 update. Can provide more information at request.

**Comment by slvl** [comment]
For me, while the shares don't show up in the sources dialog, I can still access the video files through the library. So the mounted shares can be accessed, they just don't show up as a valid source.

**Comment by anzax81** [comment]
Same thing happened here. Cannot access mounted drives, to much of an amateur to type the commands in via text .

**Comment by juxeii** [comment]
Same issue here. My intire network runs on >=SMB2 protocol.
In the Synology I also have SMB1 disabled.
In Kodi, changing SMB minimum version to SMB2 or SMB3 does not help.
Only way is to revert back to 18.9

**Comment by bartdeboer** [comment]
> Android is currently not maintained. Please don't spam with +1. If something changes you are the first that are pinged.
> 
> If you can contribute code, now is the time to standup for your platform.

If it's not maintained then how did it get updated? Seems like a fairly serious issue if the official Android release (10 million installs) is not picking up the Android OS level shares for all Nvidia Shield users. 

Perhaps revert the Android app back to v18. Or perhaps have a kodi-dev (20), kodi-beta (v19) and kodi-stable (v18) apps so people can easily revert to a previous version (or help you test the latest version) until all the issues are sorted?

**Comment by trucheromayor** [comment]
Same issue for me...
Kodi 19
Shiel TV 2017 Pro
Nas Synology 415+

When using 18.9 it what's working perfectly :(


KR

Jon

**Comment by gigatux** [comment]
Same here too.

I'm now using a standard file explorer, like Xplore, and opening video files from there with Kodi.

**Comment by DocDat** [comment]
Same problem her. When is a fix coming?

Kodi 19
Shield TV 2020 pro
Synology DS411+ II

**Comment by RayBan91** [comment]
I have this same issue. I needed to disable all updates from Google Play i downgrade Kodi!

When can we expect resolve this problem?

**Comment by laimis17** [comment]
Same here.
 
Kodi 19
Shield TV 2020 pro
macOS 11.2.2 smb server

It's been 2 month since issue appeared. 
No worries, in v20 kodi devs will make it right 😉 

 No issues with Kodi 18.x

**Comment by Timbo200** [comment]
Kodi is developed by volunteers so I'm quite sympathetic. 

My problem is that it is difficult to provide feedback here in manner that the developers will accept, that the foundation ACTIVELY promotes Android on the Kodi home page and yet we are told here that there is no full time development, and somebody who is completely undisclosed, has the authority to push a version to the Google Play Store and upgrade users to a version that lacks full support.

**Comment by Kamikaze01git** [comment]
Same here.

Kodi 19
Shield TV 2017
Synology DS920+

Without problems on Kodi 18

**Comment by mronnblom** [comment]
> * I added the NAS' folders as Mapped Network Drives from the Shield's OS settings.
> * The mapped network drives does not show up anymore in the Kodi Matrix version, but i can I can still access them if I add them manually in Kodi's favourites.xml with a text-editor. The path is something like `/storage/<NAS Name>/<share>/`. If you're in doubt on how to write it, add at least one favorite from the GUI to have a template to edit.

An easier way for the second step that I found is:
* Take note of the network path(s) you want to add.
  * You can see these paths in for example the X-plore app, or another file manager app
* In Kodi, add a new source and browse for media locations
* Choose External Storage
* Press OK (at the bottom)
* Path should appear as /storage/emulated/0
* Click on that path to edit it
* Change the path to your network path, e.g. /storage/diskstation713/movies 

* Press Done and continue as normal

**Comment by ksooo** [comment]
Actually it will be fixed once #19523 got merged.

**Comment by hoppel118** [comment]
Thanks you so much @ksooo and @koying 

It works as expected now.

Regards Hoppel

**Comment by kbirger** [comment]
Any idea when the merged changes are going to be released?

**Comment by BitBert007** [comment]
Excuse my question if it seems stupid. I unederstand from reading this: https://github.com/xbmc/xbmc/pull/19523 that the problem of accessing my videos from Kodi on my Shield Pro 2019 is fixed now, on Kodi Ver. 19.2 ???

I actually use ver. 18 since the ver. 19 does not see my shares on a Windows 10 PC on my LAN. Waiting for a release that will fix this!

Thanks in advance.

**Comment by SyntaxWarrior** [comment]
Just got this problem today when I updated to Kodi to latest version on my Nvidia Shield Pro.
Back to VLC I guess.

**Comment by bartdeboer** [comment]
You need to allow file permissions for the Kodi app manually. Worked for
me.

**Comment by SyntaxWarrior** [comment]
How do I do that?
Just to be clear: I can browse all the folders in Kodi, and the interface lists the correct items, but nothing is in the folders and when I try to play from the interface it gives men an error.

**Comment by bartdeboer** [comment]
Apps > Kodi > Info > Permissions > Files and Media > Allow
