### ISSUE TITLE
kodi-19.0-Matrix_beta2-x64  deleting Unique ID's from database after scrape movies

### ISSUE THREAD

**Issue by lepetrel69** [xbmc/xbmc#19038]
### Describe the bug
Here is a clear and concise description of what the problem is:

When scraping 2 movies for the first time, all IDs (when available) are fetched and added to the UniqueID table, but Kodi then comes back and removes some unique IDs.
This happens in v19b2.
I am using the metadata.themoviedb.org.python scraper and also with metadata.themoviedb.org

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

the UniqueID tmdb and imdb should be kept the video database.

## Actual Behavior

UniqueIDs are retrieved and added to the database, and some deleted.

### To Reproduce

1. Find a movie that you have never previously scraped. Ensure the show has a full compliment of ID's at the scraper site by checking their edit screens.
2.Scrape the moviefrom Videos>Files using the "find new content"
3.open your database
4.go to home
5.open your database again

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/yiqitifiyi.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

just after the scrap
![DB immédiatement après le grattage1](https://user-images.githubusercontent.com/77099487/104002529-80f42300-51a1-11eb-8651-a3a589e199ef.png)

home
![DB_home1](https://user-images.githubusercontent.com/77099487/104002639-a2550f00-51a1-11eb-8db0-6a0116a44bdb.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: windows 7 64bits
 - Kodi version: kodi-19.0-Matrix_beta2-x64 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HeresJonny** [comment]
I don't think Kodi deletes anything by itself . This is most likely a scraper issue. I had observed something similar in the forums almost 2 years ago: https://forum.kodi.tv/showthread.php?tid=200504&pid=2823204#pid2823204

**Comment by HeresJonny** [comment]
Also, https://forum.kodi.tv/showthread.php?tid=164652&pid=2846827#pid2846827
I wonder if the the TMDB scraper still removes existing TVDB or IMDB IDs when it should't.

**Comment by KarellenX** [comment]
This Issue is a duplicate.

See... https://github.com/xbmc/xbmc/issues/17444
