### ISSUE TITLE
kodi doesnot support chinese interface in ubuntu 20.04

### ISSUE THREAD

**Issue by yaochenglouis** [xbmc/xbmc#19039]
### Describe the bug
Here is a clear and concise description of what the problem is:

I installed kodi by apt install kodi,
then i changed the interface language to chinese but every chinese character is shown by a rectangle...

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

i should be reading chinese characters when i change the interface language

## Actual Behavior

rectangles everywhere

### To Reproduce

1. settings - interface -change language to chinese simple/tradictional 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![kodi](https://user-images.githubusercontent.com/12840061/104012482-d274d000-51ea-11eb-8d22-268f9aba9343.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

![kodi](https://user-images.githubusercontent.com/12840061/104012325-90e42500-51ea-11eb-9162-5859683156b7.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux Ubuntu 20.04
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.6 Debian package version: 2:18.6+dfsg1-2ubuntu1 Media Center Kodi from Debian
Copyright (C) 2005-2019 Team Kodi from Debian - http://kodi.tv

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Please use Estuary and change the skin font to "Arial based". Then report back if that solves your problem. 

I highly guess it will help. If so, then this is not a bug report and you should have reached out to our forums first.

**Comment by yaochenglouis** [comment]
Very sorry for the inconvenience, it worked!
