### ISSUE TITLE
Kodi creates duplicate entries after scanning shared smb media source paths twice: with and without embedded credentials

### ISSUE THREAD

**Issue by olivier-haddad** [xbmc/xbmc#19043]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi scans media source paths twice. One with and one without the credentials: for instance:
'smb://SERVER_NAME/Videos/'
and
'smb://USERNAME:PASSWORD@SERVER_NAME/Videos/'
This results in each video file to be added twice.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The media source paths should be scanned once only.

## Actual Behavior

Kodi scans the media source paths twice and adds two library entries for each media file.

## Possible Fix

Check that the media path has already been scanned with or without the credential.-
I believe that the bug occurs because:
-Kodi uses a passwords.xml file that provides another set of credentials providing access to the network share. This passwords.xml file is used by all kodi machines on the network (running Windows, Linux and android)

### To Reproduce

1. On your NAS or server, create a new media shared folder and grant access to user1
2. Add a new folder and media file in the share
3. Log in to Windows or Linux
4. In Kodi passwords.xml: add user1 credentials
5. In the sources file, the source media path should not include the credentials.
6. Launch Kodi: after scanning, the new file should appear twice

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ajipodikoz.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating sysem version/name: Windows 10, Librelec 18.9
 - Kodi version: 18.9 (on Windows)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by howie-f** [comment]
i can't replicate this on LibreElec 18.9 (RPI) and current master build with an OpenMediaVault SMB-Share.

sources.xml:
```
<video>
  <source>
    <name>STORAGE</name>
    <path pathversion="1">smb://192.168.200.222/STORAGE/</path>
    <allowsharing>true</allowsharing>
  </source>
</video>
```
passwords.xml:
```
<passwords>
    <path>
        <from pathversion="1">smb://192.168.200.222/STORAGE</from>
        <to pathversion="1">smb://smbuser:smbpass@192.168.200.222/STORAGE</to>
    </path>
</passwords>
```

please try again with a current master / LE nightly
