### ISSUE TITLE
[Q] When will python2 support be dropped?

### ISSUE THREAD

**Issue by txtsd** [xbmc/xbmc#19054]
Currently all the `.py` files that I've inspected seem to support both python2 as well as python3. And it also looks like it is possible to build kodi with only python3.

Is there a plan to drop python2 support completely? If so, when?

Also, Archlinux currently builds kodi against python2. Is there an official statement stating python2 should not be used anymore, so we can get them to build against python3 instead?

**Comment by zeehio** [comment]
Does this answer your question?
https://kodi.tv/article/attention-addon-developers-migration-python-3

**Comment by txtsd** [comment]
So the next release?

**Comment by lrusak** [comment]
Python2 has already been dropped. Python3 is only supported as of v19.
