### ISSUE TITLE
Kodi 18.9 Android - Can't properly save subtitle filename to NFS share

### ISSUE THREAD

**Issue by lobofoots** [xbmc/xbmc#19064]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm using Kodi 18.9 on Android 8 TV
My subtitle setting is set to save all subtitles to a common NFS share directory.
When saving the subtitle with Opensubtitle or Addic7ed Add-on, the result is a SRT file in the right NFS path but with its name replaced by a string of numbers like 1959.fr.srt
I tried with several shows and the problem remain.

Debug log just say that it save the file to the NFS path with the wrong filename.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

As usual the subtitle filename should be ShowFilename.LANGNAME.srt

### To Reproduce

1. 
2.
3.

### Debuglog

The debug log can be found here:
http://paste.kodi.tv/fovuluqofe.kodi
Problem starts around line 2500 of the log file

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

If I define a SMB share the feature is working as intended.

### Your Environment
Used Operating system:

 - [X] Android 8
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: ANDROID 8
 - Kodi version: 18.9 Arm V7

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by joseluismarti** [comment]
Hello lobofoots, I've tested with the **Addic7ed addon** and it saves correctly the srt file with the name of the series in the NFS shared folder.

**Comment by lobofoots** [comment]
I don't understand what could be wrong with my setup but kodi has trouble accessing files on my shares.

I have no troubles accessing video files on my NFS share, they all start flawlessly.

I have the same troubles if I define a samba share for the subtitles so I don't think it is tied to NFS anymore.

When I use samba share for my subtitles it works most of the time the second time I start a video.
The first time kodi doesn't load the external subtitle, I can fetch it from the share manually though...
I tried a lot of things and I can't figure out the problem.

Any pointers would be greatly appreciated.
I will open a thread on the forum.
