### ISSUE TITLE
[BUG] Streams are being interrupted and end with an black screen

### ISSUE THREAD

**Issue by Krawei** [xbmc/xbmc#19067]
### Describe the bug
If you play a stream with your favourite add-on, sometimes the stream playing stops and the screen just shows a black screen.

### To Reproduce
1. Download the unofficial south park add on from the official kodi repo
2. Play a random episode
3. See error

### Informations
 - LE Version: LibreELEC (community): nightly-20210115-4493a6b 9.80
 - Hardware Platform: RPi3

### Log file
https://privatebin.net/?130ce4966032d679#A9zEdfxubT7yWm8EntbYJm5Qm62rw9sh5VMii4Yt7EmA

**Comment by DaVukovic** [comment]
I cannot reproduce this issue on Fedora with Kodi 19. The stream plays fine and stops normally. I only see this problem if I try to fast-forward to the end of the video.

**Comment by enen92** [comment]
Please use paste.kodi.tv to share your log. I also could not reproduce this issue in the current nightly

**Comment by DaVukovic** [comment]
old enough to be closed
