### ISSUE TITLE
There is no apparent way to turn subtitles off or on.

### ISSUE THREAD

**Issue by Stokestack** [xbmc/xbmc#19069]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm playing back an MKV file that apparently has a force-subtitles flag set. In an extensive exploration of the Kodi UI, I can find no option to turn subtitles off. An earlier report was disregarded with the answer that pressing "the T key on the keyboard" will turn them off. What keyboard? This is on an Nvidia Shield, a stand-alone media-streaming device to which keyboards are rarely if ever attached; I'm not even sure a keyboard is supported. And even if it were, how is the user to guess that T is the hotkey for subtitles? Where is this conveyed to the user?

Numerous Web posts on this issue refer to subtitle settings in the OSD during media playback. There are is no "settings" control shown in the OSD. Screen shot attached.

The failure to present a discoverable affordance to the user for the display of subtitles is a UI defect.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would expect to the means to turn subtitles on or off in the Player settings. But although there's an entire Subtitles section under Language, there's no way to turn them off or on there. Nor is there one under Accessibility. Or under Interface settings. Or System.

## Actual Behavior

You have no apparent control over the display of subtitles.

### To Reproduce

1. Play an MKV that forces subtitles on by default.
2. Try to turn them off.
3.

### Debuglog

The debuglog can be found here:

Where?

### Screenshots 
Here are some links or screenshots to help explain the problem:

![KodiOSD](https://user-images.githubusercontent.com/196304/104799158-a7a5f100-5781-11eb-9157-e4ed35fbb3da.JPG)
![IMG_2980](https://user-images.githubusercontent.com/196304/104799191-f2276d80-5781-11eb-9ff4-f3df8317cdde.JPG)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

THERE IS NO KEYBOARD ON THIS DEVICE.

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 9
 - Kodi version: 18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Stokestack** [comment]
So what's the excuse this time?

**Comment by lrusak** [comment]
Please don't reopen a duplicate issues.

Please post your support/feature request on the forum.

**Comment by Stokestack** [comment]
I've shown that the earlier "solution" is not applicable. This remains a defect.

**Comment by DaVukovic** [comment]
Pausing the video will not get you the videoOSD. Hit the "OK" button on your remote.

**Comment by Stokestack** [comment]
I didn't say pausing the video would.

**Comment by DaVukovic** [comment]
But you paused the video in the screenshots above
