### ISSUE TITLE
There's no apparent way to turn off subtitles.

### ISSUE THREAD

**Issue by Stokestack** [xbmc/xbmc#19068]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm playing an MKV which apparently has a flag to force subtitles on. I can find no control in Kodi to turn them off. If I play the same file on a computer with IINA, I can turn them off without a problem.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

There's an option under Player (if not elsewhere as well) to turn subtitles off.

## Actual Behavior

I've explored every potentially relevant menu (if not every menu, period) and found no way to turn subtitles off.

## Possible Fix

In case it's not obvious, it can be extremely annoying to be forced to have subtitles overlaying your movie. Especially when they're in the same language as the movie.

### To Reproduce

1. Play an MKV that forces subtitles to be on by default.
2. Try to turn them off.
3.

### Debuglog

The debuglog can be found here:

Can be found where?

### Screenshots
Here are some links or screenshots to help explain the problem:

Many forum posts about this issue say, "Use the OSD." But there are no settings options in the OSD. Screen shot attached.
![KodiOSD](https://user-images.githubusercontent.com/196304/104798726-e639ac80-577d-11eb-90bf-f488962e2fbd.JPG)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
There is an option to turn off subtitles. This is not a bug report but a user error (sorry to say that)

As this section is for bug reports only and user support is given at the forums, you should seek assistance over there: https://forum.kodi.tv

**Comment by Stokestack** [comment]
This is a bug report. If the option to turn off subtitles is so buried as to be undiscoverable in 20 minutes of digging through menus, that's a defect.

Totally inappropriate and disrespectful response.

**Comment by lrusak** [comment]
Press the "t" key on your keyboard or map it to a remote button.

User support is done via the forums and further discussion should be done there.
