### ISSUE TITLE
Kodi crashing after installing Asus Armoury Crate

### ISSUE THREAD

**Issue by stealingpez** [xbmc/xbmc#19070]
### Describe the bug
I'm trying to figure out the cause of some weird crashes with Kodi. I've seen this happen across two separate Windows installs now so I'm pretty sure that the culprit is the Asus Armoury Crate software (utility software for Asus motherboards), but I can't say for certain. Prior to installing Armoury Crate, Kodi was working great with my media library on a network share. After installing Armoury Crate, Kodi now crashes when playing videos. Even after uninstalling Armoury Crate, the program continues to crash every time you play a video. I'm hoping someone will be able to glean something from the logs/crashdump, because I'm completely stumped.

I have tried reinstalling graphics drivers, reinstalling Kodi, uninstalling Armoury Crate, but nothing seems to fix it

## Expected Behavior
The video should play without issues

## Actual Behavior

The application crashes after playing the video for about a second

### To Reproduce

1.  Install Kodi
2. Install Asus Armoury Crate
3. Open Kodi and try playing a video

### Debuglog
[kodi.log](https://github.com/xbmc/xbmc/files/5824156/kodi.log)
[kodi_crashlog-18.9 Git_20201023-0655c2c718-20210116-171107.dmp.zip](https://github.com/xbmc/xbmc/files/5824150/kodi_crashlog-18.9.Git_20201023-0655c2c718-20210116-171107.dmp.zip)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Windows 10 Pro 19042.685
 - Kodi version: 18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@stealingpez 

I am going to close your Issue report as you are asking for support, rather than reporting a bug.

Please head over to the forum and post your question again. Also provide another debuglog with debug mode enabled from start, not after start. Follow the guide.

It looks like your problem is Audio related- most likely incorrectly set up audio drivers.

**Comment by stealingpez** [comment]
Sorry for posting in the wrong place, thanks for taking a look! Turns out it was the Realtek audio drivers that Armoury Crate installed that were causing the crash.
