### ISSUE TITLE
[UWP] Clean install prompts to enable/configure all packaged binary addons 

### ISSUE THREAD

**Issue by djp952** [xbmc/xbmc#19079]
### Describe the bug
Here is a clear and concise description of what the problem is:

Recent build (Matrix RC1) on Universal Windows will prompt to enable/configure all of the binary addons that ship as part of the .MSIX package.  I believe the commit that added this behavior is here:

**[addons] allow configure and enable add-ons at kodi startup**
https://github.com/xbmc/xbmc/commit/d021eda167a316da3d747a0cb326c53c5cda7a63

It's not a TON of addons, you can get through the process relatively easily, but I really don't think this is what the author intended and something should be tweaked for the builds that need to ship with binary addons included.

I do like and appreciate the behavior for the platforms where binary addons can be installed individually.

Thanks!

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
For the Kodi builds that need to ship with all the binary addons included (UWP, tvOS, etc) I wouldn't expect to be prompted to enable all of those addons during the initial startup.

## Actual Behavior

During initial startup of Kodi, I was prompted to enable/configure each binary addon that was packaged but disabled by default.

## Possible Fix

Perhaps for these builds this behavior can be omitted, or there could be some additional AddonDisabledReason other than NONE if the addon was pre-installed.  I really didn't look into it, just wanted to report the behavior.

### To Reproduce

1. Execute a clean install of the Universal Windows .MSIX package (Windows 10)
2. Launch Kodi
3. You will be prompted to enabled/configure all of the binary addons

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/kededodeja.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [X] Windows UWP

 - Operating system version/name:
 - Kodi version: (19.0-RC1 (18.9.910) Git:20210115-90a1e12804). Platform: Windows NT x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by howie-f** [comment]
thanks for the report @djp952
uwp was not tested, but let‘s how we can improve this

**Comment by djp952** [comment]
Thanks @howie-f!  I was thinking about this a bit and wanted to describe my use case for you, since this actually kind of solves a moral dilemma too.

For UWP, and in the past Android, in order to provide a binary addon (a PVR addon in my case) that doesn't come with Kodi, the official package has to be extracted and modified.  This has always kind of bugged me from the perspective of the user doesn't really know what you added to it or changed, there is a good bit of faith involved.

To that end, I think it would actually be cool if Kodi would continue to prompt to enable addons that didn't "come with Kodi" but are yet present for some reason.  For example, if a user installed my modified .MSIX, they would get prompted to enable the custom PVR addon; I like this not only because it saves them a step (one assumes it was the reason they used an unofficial build) but it also really points out that something was added to the package.

To that end, would adding a check to see if the addon is sourced from the Kodi repository or not before prompting still solve the original concern? 

You've done some great work on this stuff for Matrix, I know you'll find a cool way to fix it.  Also perfectly happy to test anything you'd like, I can build and test UWP x64 Matrix.  I'd guess anything you do would end up applying to UWP, iOS, tvOS, etc and behave the same way, but all I have to offer is UWP testing.

**Comment by howie-f** [comment]
ok, tested the UWP nightly and got > 20 questions if add-ons should be enabled, which is unusable crap imo.
those were all audio decoders, visualizations, pvr add-ons etc.

intention was to notify the user about manually installed add-ons, via linux package managers (like it's done with the official ppa) or even a modfied .MSIX and give them the chance to configure and enable.

a possible solution would be to build up the list of add-ons in question.
if it exceeds for example 3 add-ons we're asking `Do you want to configure and enable all X shipped add-ons now?` and loop through the configuration dialogs, while <= 3 add-ons will give us three questions and dialogs at a maximum.

we could also just enable nothing if the limit is exceeded because it's almost unlikely a user wants to enable all visualizations + pvr's. though then all audio decoders are disabled...., but personally i think that is best and we have no difference to like it was before

happy to hear your opinion on this. ping @phunkyfish @AlwinEsch

**Comment by phunkyfish** [comment]
As this feature was meant for Linux users only I wonder can we limit it to that user base. 

That would probably mean some platform specific logic. I’m not quite sure the right way to do that but I think the code base has many examples.

**Comment by howie-f** [comment]
```
+#if defined(TARGET_LINUX)
         ConfigureAndEnableAddons();
+#endif
 ```
should do this and is less disruptive .. maybe it can be improved for other platforms at a later point

**Comment by phunkyfish** [comment]
Yes, that’s the easy way. What we need is the equivalent cross platform way of doing it. @lrusak and @fuzzard may be able to provide direction. Platform defines are generally frowned upon.

Is this code in Application.cpp?

**Comment by howie-f** [comment]
yes
https://github.com/xbmc/xbmc/blob/0861cbc86316e3e82f799448ce70fc177af41971/xbmc/Application.cpp#L3905-L3907
awaiting instructions ;)

**Comment by phunkyfish** [comment]
The trick here is that this works for Linux OSes that have a package manager and not those that don’t AKA LibreElec etc. Let’s see what they say.

**Comment by lrusak** [comment]
what about in `Init` in `platform/linux/PlatformLinux.cpp` ? I'm not sure if the add-on manager is available then though

**Comment by howie-f** [comment]
to check LE i built a fresh `master/RC1` branch and tested on the RPI. there was no `Enable add-on YES/NO` popup on startup and after installing `pvr.hts` from the repo there was no disabled add-on in its `Addons27.db`. i think we're on the save side here.

for `platform/linux/PlatformLinux.cpp` i tried this https://github.com/howie-f/xbmc/commit/1f132c06390b86b2bb209785be6fcf9f32e933dd (though the needed includes look strange there) and failed. crashed at the `addonMgr` call.

so i think we're stuck at IFDEFfery for the one function. any further ideas?

**Comment by fuzzard** [comment]
From memory Sylvain only setup overrides for stageoneinit, but the framework is there to add platform init for stage 2 if needed

**Comment by phunkyfish** [comment]
Not sure if this is possible but something like a call to check if this platform supports a package manager. Default would return false but Linux returns true.

**Comment by basilgello** [comment]
> Not sure if this is possible but something like a call to check if this platform supports a package manager. Default would return false but Linux returns true.

Definitely a better approach than IFDEFfery! We can then declare which platforms to turn on, or turn off... if it is UWP and there is a 'custom MSIX' flag somewhere (disk file for example?), disable it, if it is LibreELEC, also disable, if it is Linux but not exception, enable it.

**Comment by howie-f** [comment]
this approach https://github.com/howie-f/xbmc/commit/84e528fa70534f73fdb7950a43c38571f0f55160 - not elegant - is working, too. any platform defines the `OS`,..... Android and FreeBSD, for instance, also define `Linux`.
so either use this existing `OS`, define an additional `AllowEnableOrphanedAddons`...
or maybe something like
```c
bool CPlatformLinux::Init()
{
.
  ConfigureAndEnableAddons = CApplication::ConfigureAndEnable();
  return true;
}
```

```c
bool CPlatformWin10::Init()
{
.
  ConfigureAndEnableAddons = nullptr;
  return true;
}
```

**Comment by basilgello** [comment]
I think me, @canderws and other distro maintainers will have no objection on CMake config option "TARGET_HAS_PACKAGE_MANAGER=1" regardless of platform, controlling this behavior…

**Comment by howie-f** [comment]
i decided to the "additional env var" route for now. can't figure something prettier atm

**Comment by phunkyfish** [comment]
> i decided to the "additional env var" route for now. can't figure something prettier atm

I agree. I think it’s the most reasonable  solution currently.
