### ISSUE TITLE
LIRC missing in Kodi 18.8

### ISSUE THREAD

**Issue by berni123** [xbmc/xbmc#19085]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi does not recognize ir remote configured and working via lircd (0.10.1)
Lircmap.xml is configured. Remote-IR is tested via irw and running.
Option -l is missing to configure lircd

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should run with lircd via /var/run/lirc/lircd

## Actual Behavior

Kodi does not run with lircd

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux 4.19.0-13-amd64 #1 SMP Debian Buster
 - Kodi version: 18.8 (18.8.0) Git:20201002

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Please get us a full logfile.

**Comment by DaVukovic** [comment]
Have to add, this user uses LMDE (Linux Mint Debian Editiion) and installed Kodi via Flathub. 

I highly guess the problem is the OS here

**Comment by DaVukovic** [comment]
No response anymore, so let's close this
