### ISSUE TITLE
Blank screen on Sony Xperia 5ii phone after starting kodi

### ISSUE THREAD

**Issue by nickybrandt** [xbmc/xbmc#19081]
Blank/black screen on Sony Xperia 5ii phone after starting kodi

It's a black screen where there is supposed to be a Kodi homescreen. After first run. There are interface sounds. Does it have something to do with the different screen size of this specific phone,

## Expected Behavior

Should see Kodi home screen

## Actual Behavior
Black screen but interface sounds work when navigating.

**Comment by lrusak** [comment]
please post a debug log or your issue will be closed

**Comment by nickybrandt** [comment]
> please post a debug log or your issue will be closed

I wouldn't know where to start with that I'm sorry. I'm just an end user and thought I'd report a problem with this specific phone. I've used Kodi without any issues on all my android phones since the first android version got released all without problems. Now I get this problem with this specific phone.

**Comment by nickybrandt** [comment]
Good work man

**Comment by damionx7** [comment]
@nickybrandt try lowering refresh rate in display settings in phone to 60 lower. See this https://www.reddit.com/r/kodi/comments/e5iugc/black_screen_android_10_phone/
