### ISSUE TITLE
Seek not working from kore in 19.0RC1

### ISSUE THREAD

**Issue by cpages** [xbmc/xbmc#19084]
### Describe the bug

Jumping to a specific point in time of a video with the seek bar from kore is not working in v19. I can press the seek bar and the cursor moves there, but the video keeps playing at the point it was. If I press pause, the cursor goes back to the initial place and playing again resumes normally. I've tried with several videos, so I don't think it's a specific broken file issue.

This used to work on kodi 18 and I think there was no recent kore update on my devices that work as remote.

## Possible Fix

--

### To Reproduce

1. Try to go to a specific time of a video from android's kore remote, with the seek bar
2. The video keeps playing ignoring the operation

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/patimupuni.kodi
(I played a video, used seek a couple times (plus pause & resume)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nixos 20.09
 - Kodi version: 19.0RC1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by popcornmix** [comment]
Sounds like a Kore issue (using a deprecated API) not a kodi issue.
See: https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/95 for comparison.

**Comment by cpages** [comment]
Closing this since I got confirmation it's a Kore issue
