### ISSUE TITLE
enigma2 client: HTTP connection with authentication fails, if password contains special characters

### ISSUE THREAD

**Issue by Andreas-B1105** [xbmc/xbmc#19088]
### Describe the bug

**enigma2 client: HTTP connection with authentication fails, if password contains special characters**

Here is a clear and concise description of what the problem is:

System:

The problem is independent of the enigma based set top box. 
**Example: see below in actual behaviour**

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

A working HTTP connection to OpenWebif

## Actual Behavior

in the enigma2 client configuration i entered 
```
ip addr.: 192.168.188.16
user:  root
passwd.: test#5
```
HTTP connection fails with
```
2021-01-19 10:30:10.169 T:2681287536   DEBUG: CurlFile::Open(0x255fc70) http://root/#5@192.168.188.16:80/web/currenttime              
2021-01-19 10:30:10.172 T:2681287536   DEBUG: Curl::Debug - TEXT: Could not resolve host: root                                        
2021-01-19 10:30:10.172 T:2681287536   DEBUG: Curl::Debug - TEXT: Closing connection 2                                                
2021-01-19 10:30:10.172 T:2681287536   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)                           
2021-01-19 10:30:10.172 T:2681287536   ERROR: CCurlFile::Open failed with code 0 for http://root/#5@192.168.188.16:80/web/currenttime:

```
See how the url is dissolved incorrect **http://root/#5@192.168.188.16:80**

**if i use** the same configuration, but the password is simply **'test' or 'test5',** the connection succeeds.
I have not tested different special characters, but i am willing to help with that if needed.

## Possible Fix

As a work around don't use special characters within the password

### To Reproduce

Look at **Actual Behavior**

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [LibreELEC (official): 9.2.6 (RPi4.arm) ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 18.9.0 (Leia_pi4_18.9-Leia)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by wsnipex** [comment]
looks like pvr client specific. Please report directly to the addon.

**Comment by phunkyfish** [comment]
This is already fixed in the kodi 19 version.
