### ISSUE TITLE
PVR repo unavailable

### ISSUE THREAD

**Issue by nitehawks** [xbmc/xbmc#19090]
### Went to add tvheadend package from Kodi repo and only see two options available related to Myth TV
Here is a clear and concise description of what the problem is:
## Expected Behavior
Should have list of multiple PVR addons like simple PVR client
## Actual Behavior
Only see MythTV addon available

## Possible Fix
Possible git merge issue?

### To Reproduce
1.  Go to Kodi repository
2. PVR addons
3.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Update to v19 RC1 and report back. Issue should be fixed there.

**Comment by nitehawks** [comment]
Yup all good thanks so much!!!!
