### ISSUE TITLE
SMB share cant be accessed with Kodi 19 RC

### ISSUE THREAD

**Issue by isarrider** [xbmc/xbmc#19094]
## Bug report
SMB Share (with or without pw) cant be accessed on Kodi 19 RC
### Describe the bug
Kodi should be able to add smb share v3,
access worked in beta 1 for example...

## Expected Behavior
Kodi should list or at least be able to access SMB Share
(even passwordless ones in v18 worked fine)
VLC does not have this problem, it actually lists the SMB shares even

## Actual Behavior
Kodi states the share isnt availible

## Possible Fix
maybe look at SMB Code from VLC or even copy it...

### To Reproduce
1. Try to add share 
2. use add source
3. add SMB Path
(this way works fine with 19 beta 1 btw)

### Your Environment
Used Operating system:

 - [ X ] Android (on Fire TV Stick 4k)
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19 RC

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
> Kodi should list or at least be able to access SMB Share

Listing SMB shares might not be possible due to SMB2 network connections. 

Can you confirm that you can't add a SMB share by using the "Add network location":
![image](https://user-images.githubusercontent.com/7235787/105201765-86f2e800-5b41-11eb-9593-bab15f6aadef.png)

and then fill out this dialog matching to your network and share(s):

![image](https://user-images.githubusercontent.com/7235787/105201921-b275d280-5b41-11eb-9634-5eee142604d6.png)

As that's currently the recommended way to add a SMB share.

**Comment by isarrider** [comment]
Hallo,

yes I can confirm that...
But it worked in Beta 1...
Both with the same steps...

Thx

**Comment by DaVukovic** [comment]
Works fine for me using Beta2 on Linux. Will test on Android as well later with a NVidia Shield

**Comment by isarrider** [comment]
But does it also with the RC?

**Comment by DaVukovic** [comment]
Yes, works like a charm on a NVidia Shield with Kodi RC and doing it in the way I explained above: 

![smb1](https://user-images.githubusercontent.com/7235787/105207443-d3d9bd00-5b47-11eb-8020-4a9de7a8fe9c.jpg)
![smb2](https://user-images.githubusercontent.com/7235787/105207448-d5a38080-5b47-11eb-887d-029a914e011c.jpg)

Currently let Kodi scrape via local NFO files and movies are added to the library. 

Please seek for assistance at our forums: https://forum.kodi.tv/

This seems to be a fault on your side as Kodi does everything correct for me on Linux (Fedora) and Android (NVidia Shield).

**Comment by sceba** [comment]
I have a Philips android Tv Kodi 19RC. I did everything according to the procedure and I can't.
It doesn't work for me to get via SMB to the NAS.

**Comment by isarrider** [comment]
For me it is weird, as I have the same config on my Phone and on my firestick, both of course 19 RC...
Phone works, fireTV stick doesnt...

**Comment by sceba** [comment]
So that's a mistake.
Who will solve it?

**Comment by kambala-decapitator** [comment]
have you tried adjusting Samba settings in Kodi? For example, to make Kodi connect to SMB share hosted on macOS 10.15, it's required:
1. to connect using password
2. to make content actually work, force SMB to v1 in Kodi settings

**Comment by isarrider** [comment]
SMB1 isnt an option nowadays... (and I used it in 19Beta 1 with SMB3 successfully )
I also really liked that 18 could use SMB Shares without password...

**Comment by isarrider** [comment]
update:
it seems kodi-20220219-10fd6977-master-24458-armeabi-v7a (or maybe already an earlier version)
fixes what was broken in 19 RC...
It works now fine again with my Win SMB share without password...

**Comment by isarrider** [comment]
ok, another update...
it worked only once...
after a restart of Kodi it does not anymore...
#confused...

**Comment by isarrider** [comment]
ok, so with this version a clean setup also works once, after a restart it does not anymore...
