### ISSUE TITLE
Keyboards - Non-intuitive, symbols not what they say they are

### ISSUE THREAD

**Issue by dm2912** [xbmc/xbmc#19104]
### Describe the bug
Here is a clear and concise description of what the problem is:

Keyboards in both default themes, estuary and etouchy are confusing when it comes to symbols.

Taking a basic task of adding an email address to an add-on. In estuary the symbol key is denoted by a key with #+= on it.. 

![image](https://user-images.githubusercontent.com/25871666/105552618-1643fb00-5cfc-11eb-9769-007ff82a785d.png)

That key however, not only does not take you to a page with #, +, or = on it, but it also doesnt take you to a page of any useful symbols. (its only after trial and error you discover to get to symbols such as #. @, + etc you actually need to hit the up arrow (shift))

Estouchy is even more confusing. In this view there is a key denoting symbols that has on it @, #, $ and %

![image](https://user-images.githubusercontent.com/25871666/105552770-50150180-5cfc-11eb-9d91-a7e271146a0b.png)

NONE of those symbols are actually available on the keyboard when you press that key, again, its a bunch of regional accented letters etc. 

## Expected Behavior

Symbol keys should actually reflect the what will happen when you press the key. and common symbols such as @, " etc should be intuitively found on those options, not by trial and error of random key pressing. 

### Screenshots 
Here are some links or screenshots to help explain the problem:

screenshots above

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Coreelec

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
thanx for the heads-up!
i've fixed those buttons: https://github.com/xbmc/xbmc/pull/19106

for symbols, you'll indeed need to use the shift key (just like on a regular keyboard)

**Comment by dm2912** [comment]
> thanx for the heads-up!
> i've fixed those buttons: #19106
> 
> for symbols, you'll indeed need to use the shift key (just like on a regular keyboard)

cheers

overall shift isnt quite as intuitive, but at least there is now no signpost to follow that promises to lead you to symbol land but instead takes you down a cul-de-sack. :D
