### ISSUE TITLE
Special Request: x86 Android build of Kodi 18.9 for legacy devices (Nexus Player, etc) 

### ISSUE THREAD

**Issue by Pentaphon** [xbmc/xbmc#19100]
I couldn't find any way to contact the dev team by email and many people have already posted this request in the forum but have received no response so I'm posting here as a last resort. 

Can we have a x86 build of Kodi 18.9 for Android posted on the official mirror here? There's only 17.6. 

https://mirrors.kodi.tv/releases/android/x86/

This is the last version of v18 and it would be nice to an official build from a trusted source somewhere that users of legacy devices such as the Nexus Player can download without worrying about malware. 

If this isn't the right place to post this request, please let me know so I can close this issue myself and contact a person who could get this done? Thanks.

**Comment by lrusak** [comment]
Please post feature requests in the forum.
