### ISSUE TITLE
Wrong definition of HDMI_STATIC_METADATA_TYPE1 for HDR.

### ISSUE THREAD

**Issue by kleinerm** [xbmc/xbmc#19122]
Hello xbmc developers! As a little heads up:

https://github.com/xbmc/xbmc/blob/7f6938daf6fd3cbf810a0063f905ae61eb337f05/xbmc/cores/VideoPlayer/Buffers/VideoBufferDRMPRIME.h#L27

contains a definition of HDMI_STATIC_METADATA_TYPE1 = 1. This is copied from libdrm, and libdrm's version is copied from Linux kernel headers. It turns out this definition is wrong in kernel/libdrm, and should be HDMI_STATIC_METADATA_TYPE1 = 0 instead.

The kernel doesn't validate this, and many HDR monitors have insufficient validation in their firmware, so despite being wrong, it may have worked on specific HDR monitors.

See the ongoing discussion wrt. a kernel patch which should fix this for reference:

https://lists.freedesktop.org/archives/dri-devel/2021-January/295187.html

**Comment by lrusak** [comment]
Thanks for pointing this out. We only hardcode the definitions because they were written in combination with testing kodi with HDR. I really think these hardcoded values can be removed from Kodi or guarded with an ifdef.

What do you think is the correct approach?

**Comment by kleinerm** [comment]
I don't know. Normally libdrm or the kernel would be a good reference. Or the official standards.
Wrt. HDR or similar, AMD's amdvlk driver source code could be another reference, e.g.:

https://github.com/GPUOpen-Drivers/pal/blob/26cb05f899cc587f9398399a3381ee22ab41f4c2/src/core/os/amdgpu/amdgpuScreen.h#L43

**Comment by enen92** [comment]
Fixed in https://github.com/xbmc/xbmc/pull/19129
Thanks
