### ISSUE TITLE
unknown subtitle in dialog notification Kodi 19 RC1

### ISSUE THREAD

**Issue by lepetrel69** [xbmc/xbmc#19125]
### Describe the bug
Here is a clear and concise description of what the problem is:

the displayed subtitle is unknown in kodi 19 RC1 while it is well displayed in kodi 19 Beta2

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

the notification of subtitles should be identical to kodi 19 Beta2

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

kodi 19 beta2 log:
https://paste.kodi.tv/atawagadev.kodi

kodi 19 Rc1 log:
https://paste.kodi.tv/qehopoxaso.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

kodi-Beta2-DialogNotification
![kodi-Beta2-DialogNotification](https://user-images.githubusercontent.com/77099487/105828499-7fa95f80-5fc3-11eb-8fca-f20984a136d8.png)

kodi-RC1-DialogNotification
![kodi-RC1-DialogNotification](https://user-images.githubusercontent.com/77099487/105828611-a10a4b80-5fc3-11eb-82e2-1c17451743fc.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: windows 7 64-bit
 - Kodi version: kodi 19 RC1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Sorry I can't reproduce this problem with any of my samples, all are correctly displayed in the Kaytoast in Kodi RC1 when I cycle through subtitles. Can you share more info on how to reproduce?

**Comment by lepetrel69** [comment]
Hello
1) play the movie
2) press "t" on the keyboard
I have tried with different files, the result is always the same.

**Comment by enen92** [comment]
thanks for the info, can confirm the issue

**Comment by lepetrel69** [comment]
Ok,
What is interesting in this feature is to alternate between deactivating / activating the subtitle, to know which subtitle is used. This avoids opening the dialog settings then subtitle settings to do it.
For the record it works well with kodi 17, 18 and 19B2.
thanks
