### ISSUE TITLE
Various focal kodi-libretro packages are unavailable

### ISSUE THREAD

**Issue by inf0rmix** [xbmc/xbmc#19127]
Hi,

I wonder why I do not finall all libretro kodi cores in the latests ubuntu 64 focal ppa (x64)
the only emulators I find when I query apt are:

apt-cache search kodi libretro
kodi-game-libretro - Libretro wrapper for Kodi's Game API
kodi-game-libretro-beetle-pce-fast - NEC - PC Engine / CD (Beetle PCE FAST) core for kodi's retroplayer
kodi-game-libretro-beetle-vb - Nintendo - Virtual Boy (Beetle VB) core for kodi's retroplayer
kodi-game-libretro-beetle-wswan - Bandai - WonderSwan/Color (Beetle Cygne) core for kodi's retroplayer
kodi-game-libretro-dbg - debug symbols for Libretro wrapper for Kodi's Game API
kodi-game-libretro-gambatte - Nintendo - Game Boy / Color (Gambatte) core for kodi's retroplayer
kodi-game-libretro-bsnes-mercury-balanced - Nintendo - SNES / SFC (bsnes-mercury Balanced) core for kodi's retroplayer
kodi-game-libretro-bsnes-mercury-performance - Nintendo - SNES / SFC (bsnes-mercury Performance) core for kodi's retroplayer
kodi-game-libretro-vba-next - Nintendo - Game Boy Advance (VBA Next) core for kodi's retroplayer

Is there a reason for this ?

apt source and compiling the the missing emulator packages works and even the compiled emulator-cores in kodi are working.

I just find build depenency problems with dpkg wihch I have to skip:

root@nz:~/kodi-game-libretro-genplus-1.7.4.10# dpkg-checkbuilddeps 
dpkg-checkbuilddeps: error: Unmet build dependencies: libretro-genplus (>= 1.7.4) | genplus (>= 1.7.4)

**Comment by wsnipex** [comment]
they fail to build

**Comment by inf0rmix** [comment]
but only due to dependencies which do not apply.

skipping checkbuilddeps successfully builds the addons and they are working after installing the deb packacke.

**Comment by wsnipex** [comment]
care to elaborate?

**Comment by garbear** [comment]
There is a path forward on this - we modify the CMakeLists.txt file that builds the cores to have an "internal" build option, similar to how Kodi does internal CEC, etc.

**Comment by garbear** [comment]
We no longer maintain debian repos, so these will never be available unless we get a new maintainer.
