### ISSUE TITLE
[Feature Request] Use EIT file as information source for DVB-S recordings

### ISSUE THREAD

**Issue by ovz93br43v7** [xbmc/xbmc#19120]
This is just a feature request, due to the fact that my DVB-S recordings are not named correctly like "S0xEyy" Kodi don't recognized the episodes.

On my enigma2 receiver the app "[EMC](https://github.com/betonme/e2openplugin-EnhancedMovieCenter)" is able to display the content of the "EIT" file (full name is "event information table"), so I hadn't to name the files in a specific way.

More information about "EIT" can be found here --> https://de.wikipedia.org/wiki/Event_Information_Table or here (source of wikipedia article): https://portal.etsi.org/webapp/workprogram/Report_WorkItem.asp?WKI_ID=42952

 Somebody has already extracted the script from the EMC to this script--> https://pypi.org/project/eitparser/

So my feature request is that the content of the "EIT" file should be use as additional information source when the DVB-S recordings are not correctly named.

EDIT:

here you can see an example, "EIT" information are displayed on the left side:
https://www.dreambox-blog.com/wp-content/uploads/2011/11/EMCSelection-HD.jpg

**Comment by phunkyfish** [comment]
FFmpeg only started to support embedded EIT data in streams recently (during the summer) so it would not have been possible before now.

The problem is this. The add-on is responsible for setting the name of an episode. But for pvr.vuplus there is no demuxer which would be required to read the data.

Sure, support could be added to kodi for this but how would it know when to use the embedded data vs not use it? It’s not an easy problem to solve.

**Comment by DaVukovic** [comment]
Thanks for the feature request. But as this is a bug-report section, those requests should be made at the forums:

https://forum.kodi.tv/forumdisplay.php?fid=9

Thanks for underrstanding.

**Comment by ovz93br43v7** [comment]
Mhm okay I'm not a programmer so I would imagine that this works like a [decision tree](https://en.wikipedia.org/wiki/Decision_tree)
The user defines what content [movies, tv shows, music...] is in the folder and whether the files are all in one folder or in separate folders with matching names. So here would be one point were the user could select: "no the files are not named please use the EIT data which is inside the folders".

Or other way: In my case Kodi has found a folder with TV shows:
TV shows --> folder: name of the TV show e.g. "Star Trek" --> DVB-S recording named date-TV channel-title e.g. "Star Trek"
For every ts-file there is also a EIT data file with the same file name. In my case Kodi has detected the TV show but not the episodes because the files are not named. When the "[decision tree](https://en.wikipedia.org/wiki/Decision_tree)" comes to that point (and don't find anything about the file because it is not correctly named like SxxEyy) Kodi could look automatically whether there is a EIT data file with the same name and could use that info.

**Comment by phunkyfish** [comment]
Sorry, I had assumed you meant EIT data embedded in the stream of a live programme and not in a separate file for a recording. Do you have an example of these files?
