### ISSUE TITLE
GBM: some HEVC DVB streams don't work

### ISSUE THREAD

**Issue by smp79** [xbmc/xbmc#19139]
### Describe the bug

Some TV channels display a green frozen screen. This seem to be specific to Kodi-GBM. On Kodi-X11 they work fine. Tested on Gemini Lake J4105, LibreELEC x86 (GBM and X11, current master).
[Sample video](https://www.dropbox.com/s/wf3kqdlj842eykf/sample_hevc_gbm.ts?dl=1). 

### To Reproduce

Play the sample video on Kodi-GBM with HW acceleration enabled.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ilakewupev.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC
 - Kodi version: current master

**Comment by lrusak** [comment]
Closing as you are using an unsupported configuration. Until the code is actually PR'd and merged there is no time to try and debug WIP code.
