### ISSUE TITLE
TV Show (folder) entry doesn't go away after library cleanup

### ISSUE THREAD

**Issue by samohd** [xbmc/xbmc#19134]
### Describe the bug
In the Video section, via Library Node Editor, I have a TV Shows section defined as... Content: TV shows, Order: Title (ascending). I organize tv shows on my NAS, with a folder named for the show and within that folder the episodes. When I view this section initially via Videos > TV Shows the list appears in ascending order as expected. When I'm done watching all the episodes of a show, I delete the folder off the NAS. BUG #1: When I later do a library cleanup (I have a remote key defined to initiate the library cleanup), and if I'm looking at the TV Show list... when the library cleanup completes, that deleted tv show will be gone from the list. But, if I then just click Back, to go up a level, then choose TV Shows again to go back the deleted tv show (folder) will reappear as Whatever Name ... 0/0. It will stay there, even after Kodi restart, until I manually remove it with "Remove TV Show from library".

## Expected Behavior

The deleted tv show should not reappear in the list.

## Actual Behavior

The delete tv shows reappears in the list, as described above.

## Possible Fix

I'd guess the episodes are removed from the database, but not the folder name.

### To Reproduce

1. See above
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Sony Bravia Android TV - Android 8.0.0
 - Kodi version: 18.9... but the issue started happening a year or more ago

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
get us a debuglog and screenshots of what you are doing.

**Comment by samohd** [comment]
In all fairness... it's pretty clear what the issue is. Delete the folder from the database, not just the episodes.

**Comment by HitcherUK** [comment]
You're doing it in the wrong way around.
Deleting the folder and cleaning the library won't remove it because Kodi assumes there could more episodes of the show in the future.
`Remove TV Show from library` should be done to remove the whole show from your library.

**Comment by DaVukovic** [comment]
So this is a support question then. Please seek assistance at the forum. 

Closed

**Comment by samohd** [comment]
I still think this is a bug. There is no "Remove TV Show from library" that I can find. I've googled the topic with nothing found on it. Only thing i see in Manage, at the file level or the folder level, is "Remove from library". Regardless... if the folder is deleted from the storage device, there's no reason Kodi should remember it, waiting for a new episode. If there was to be a new episode the directory likely wouldn't have been deleted. Rethink this logic.

**Comment by HitcherUK** [comment]
In the library list of TV shows select the show to be removed from the library, context menu, remove from library.
