### ISSUE TITLE
Remember category within Videos sections

### ISSUE THREAD

**Issue by samohd** [xbmc/xbmc#19135]
## Roadmap or todo item
While Kodi is running, when I go into any Video section, for example: Videos > Movies > Genres > Horror and scroll down the list ... and then click Back out to navgate elsewhere. When I later go back to the same section, it remembers where I was. And it does this for all sections. On my Sony Android tv, when I exit Kodi to watch regular cable tv, and later return to Kodi... sometimes Kodi was still active in the background and all is as it was... but more often than not Kodi restarts when I return to it... and then all the last positions are reset. So, I'd like it to remember these previous positions after a restart as well.

### Context

With a lot of items in the list... some more likely to be watched sooner rather than later, I often page down thru items to find one that fits into the sooner category, and then I watch that. Later in life, when I return to this section again, I can't remember where I left off and/or there's so many that I have to repeatedly page a lot to find my way back to where I was. The benefit of Kodi remembering after restart is that it'll be ok for me to get old and be losing my memory.

### Additional context, screenshots or links
Here are some relevant links or screenshots

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by DaVukovic** [comment]
Feature requests have to be submitted at our forum: https://forum.kodi.tv

This is a bug-report section. Roadmaps are for team members only


Thanks for understanding
