### ISSUE TITLE
Crash on Harmony OS when startup, please help to fix.

### ISSUE THREAD

**Issue by Lacrimose** [xbmc/xbmc#19133]
### Describe the bug
I baught a new TV which based on HarmonyOS and it is APK compatible.
After installing kodi(version 18.9) on my TV I tried to run it, and I got crash  on and on.
Actually kodi version 18.0 or later version all have this issue.

I managed to get the log:

E/AndroidRuntime(10829): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(10829): Process: org.xbmc.kodi, PID: 10829
E/AndroidRuntime(10829): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(10829):  at android.os.AsyncTask$AsyncFutureTask.done(AsyncTask.java:429)
E/AndroidRuntime(10829):  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(10829):  at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(10829):  at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(10829):  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
E/AndroidRuntime(10829):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(10829):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(10829):  at java.lang.Thread.run(Thread.java:929)
E/AndroidRuntime(10829): Caused by: java.lang.IllegalArgumentException: Unknown URL content://android.media.tv/channel
E/AndroidRuntime(10829):  at android.content.ContentResolver.insert(ContentResolver.java:1840)
E/AndroidRuntime(10829):  at org.xbmc.kodi.channels.util.TvUtil.createChannel(TvUtil.java:118)
E/AndroidRuntime(10829):  at org.xbmc.kodi.channels.SyncChannelJobService$SyncChannelTask.doInBackground(SyncChannelJobService.java:150)
E/AndroidRuntime(10829):  at org.xbmc.kodi.channels.SyncChannelJobService$SyncChannelTask.doInBackground(SyncChannelJobService.java:78)
E/AndroidRuntime(10829):  at android.os.AsyncTask$3.call(AsyncTask.java:389)
E/AndroidRuntime(10829):  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(10829):  ... 4 more
E/ActivityThread(10829): Failed to find provider info for android.media.tv

Please know and help to fix this.
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expect Kodi (version 18.0 or higher) run on HarmonyOS TV normally, no crash happens.

## Actual Behavior

Kodi (version 18.0 or higher) crashes when App starts up.

## Possible Fix

According to this line in the log "E/AndroidRuntime(10829): Caused by: java.lang.IllegalArgumentException: Unknown URL content://android.media.tv/channel". 
Exception catch are needed in TvUtil.java when calling insert(), query() method to TvContractCompat.Channels.CONTENT_URI, for example at line 77, 119, 137.

For example at line 119:
    // ...
    Log.d(TAG, "Creating channel: " + subscription.getName());
    try {
        Uri channelUrl =
            context.getContentResolver()
                    .insert(
                            TvContractCompat.Channels.CONTENT_URI,
                            builder.build().toContentValues());
    } catch (SQLException | IllegalArgumentException | SecurityException e) {
         Log.e(TAG, "execute SQL command throws exception");
         // FIXME: do something when exception heppens;
    }

### To Reproduce

1. Install kodi 18.x apk on HarmonyOS;
2. Try to run the application;
3. The application crashes.

### Debuglog

The debuglog can be found here:

Looked into debuglog but there is no useful information found, now confirming if the log was washed out.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi (18.9 (18.9.0) Git:20201023-0655c2c718). 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Please get us a full deboglog.

But I highly guess this strange "harmony OS" might not be supported or they changed something. But we'll probably see after you submitted a full debuglog

**Comment by Lacrimose** [comment]
> Please get us a full deboglog.
> 
> But I highly guess this strange "harmony OS" might not be supported or they changed something. But we'll probably see after you submitted a full debuglog

Hi DaVukovic, information updated please reference to it.
Thanks for the time you taken.

**Comment by DaVukovic** [comment]
still the full log is missing.Not sure if it's needed or helpful in that case. But I highly guess it won't hurt. 

If you have a possible fix at hand, please PR it.

**Comment by fritsch** [comment]
Does this help? https://stackoverflow.com/questions/29175716/illegalargumentexception-unknown-url-content-content

**Comment by Lacrimose** [comment]
> Does this help? https://stackoverflow.com/questions/29175716/illegalargumentexception-unknown-url-content-content

Same cause:
"Caused by: java.lang.IllegalArgumentException: Unknown URL"

I mean we can fix this by handling  java.lang.IllegalArgumentException.

**Comment by ksooo** [comment]
Fixed with #19171
