### ISSUE TITLE
VideoPlayer segfault

### ISSUE THREAD

**Issue by ghost** [xbmc/xbmc#19152]
### Describe the bug
Here is a clear and concise description of what the problem is:
during watching Sat-TV on LibreElec nightly with TvheadEnd the screen got increasing artefacts and a subseq. black screen, while audio runs further until the player stops completely
with debug on and tail -f <log-files> in an terminal I see
a) increasing Continuity error's [1] and
b) with dmesg "[ 4501.067910] VideoPlayer[938]: segfault at 7efdec003870 ip 00007efdec003870 sp 00007efdd57f0578 error 15"

happens on two diff. boxes, both Intel
- Intel NUC 8i3BEH with Intel Corporation Iris Plus Graphics 655
- Intel Core(TM) i5-3475S with Intel® HD Graphics 4000 (GT2)

[1]
I don't get Videoplayer segfault, but also Continuity error's, but with a minor number ( < 10) with LibreElec Release (9.2.6).

maybe related:
https://github.com/xbmc/xbmc/issues/17531

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
smooth TV play without artefacts or crashes of the player

## Possible Fix
no idea.

### To Reproduce

1. setup LibreElec nightly with TvheadEnd
2. watch Sat-TV
3. wait (max 1-2 h)

### Debuglog

The debuglog can be found here:
https://paste.ubuntu.com/p/q9F9g2mmDs/
https://paste.ubuntu.com/p/dVPhfHVjGW/

https://paste.ubuntu.com/p/3s8mxhYCJn/

### Screenshots 
Here are some links or screenshots to help explain the problem:

none

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

none

### Your Environment
Used Operating system:

  - [ x] Linux
 
 - Operating system version/name:
LibreELEC-Generic.x86_64-9.80-nightly-20210124-164b0f6 and former
LibreELEC-Generic.x86_64-9.80-nightly-20210128-d3fc794

 - Kodi version: ? (I guess the last)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Can you switch away from the iHD driver?
2021-01-29 17:37:02.057 T:938     DEBUG <general>: libva info: Trying to open /usr/lib/dri/iHD_drv_video.so

**Comment by sixpack58** [comment]
in the LE Forum @mglae suggested a /storage/.config/kodi.conf with

MESA_LOADER_DRIVER_OVERRIDE=i965
LIBVA_DRIVER_NAME=i965

is this what you mean ?

if yes: 
the last log file was generated with this settings

**Comment by fritsch** [comment]
I don't see a segfault there.

If you record that file - can you reproduce it with the recording as well?
a) From the addon itself
b) Playing the ts file directly?

Make sure to record the raw ts - nothing tvheadend would try to rewrite.

**Comment by sixpack58** [comment]
segfault was only on the command line using dmesg or journalctl -f.

I'm inexperienced with recording under LE, so your last sentence esp. the last part is somewhat difficult to understand.
anyway, I'll see what I could get ..

**Comment by sixpack58** [comment]
for the record:
seems to ~_fixed_~ with TvHeadend 4.**3** from here:
http://build.mycvh.de/Tvh-LE9.2/

well, the "~" are therefore there to express - as an non-developer - that obviously some conditions are existing to bring kodi down with Segmentation fault apart from catching this error condition before it segfaults.

if one is willing to investigate further, some observation:
Sat-TV does not crash immediately. 
it need some time to run and build up (in German: "schaukeln sich auf") an error condition what leads to the crash.
one pointer could be increasing "Continuity Error's" I see with the default TvHeadEnd 4.2, while with 4.3 they stay low (< 5).
amateurishly, I would say an "buffer" or such, what gets filled, more and more, until it bursts.
