### ISSUE TITLE
Video / Interface stutter

### ISSUE THREAD

**Issue by Flattermann78** [xbmc/xbmc#19162]
### Describe the bug
Here is a clear and concise description of what the problem is:

Video and UI are rather slow on TPi 4 using a clean compile of 19.0-RC1 (18.9.910) Git:20210202-0c9370c022.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Both playing video from network or local storage are slow creating "OutputPicture - timeout waiting for buffer" messages in the log.

## Actual Behavior

Video stutters 

### To Reproduce

Just started a video either from NAS or directly from SD Card.

### Debuglog

The debuglog can be found here:

http://paste.ubuntu.com/p/kPfhCHhr6p/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
19.0-RC1 (18.9.910) Git:20210202-0c9370c022 running on RPi 4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by popcornmix** [comment]
Have you enabled video acceleration options (and direct to plane rendering).

**Comment by Flattermann78** [comment]
Good Question! I have no option in the menu so I just assumed it's on.

My configuration for compiling kodi is

cmake ../kodi -DCMAKE_INSTALL_PREFIX=/usr/local -DCORE_PLATFORM_NAME=gbm -DCORE_SYSTEM_NAME=linux  -DGBM_RENDER_SYSTEM=gles -DAPP_RENDER_SYSTEM=gles -DENABLE_INTERNAL_FMT=ON -DENABLE_INTERNAL_FLATBUFFERS=ON -DENABLE_TESTING=OFF -DENABLE_INTERNAL_SPDLOG=ON
-- Source directory: /home/pi/src/kodi
-- Build directory: /home/pi/src/kodi-build
-- Generator: Single-configuration: Release (Unix Makefiles)
-- CMake Version: 3.13.4
-- System type: Linux
-- Linker: GNU gold
-- include/linux/udmabuf.h not found
-- include/linux/dma-heap.h not found
-- Core system type: linux
-- Platform: gbm
-- CPU: armv7l, ARCH: arm
-- Cross-Compiling: FALSE
-- Execute build artefacts on host: TRUE
-- Depends based build: 
-- statx is available
-- Could not find hardware support for SSE (missing: _SSE_TRUE _SSE_OK) 
-- Could not find hardware support for SSE2 (missing: _SSE2_TRUE _SSE2_OK) 
-- Could not find hardware support for SSE3 (missing: _SSE3_TRUE _SSE3_OK) 
-- Could not find hardware support for SSSE3 (missing: _SSSE3_TRUE _SSSE3_OK) 
-- Could not find hardware support for SSE4.1 (missing: _SSE41_TRUE _SSE41_OK) 
-- Could not find hardware support for SSE4.2 (missing: _SSE42_TRUE _SSE42_OK) 
-- Could not find hardware support for AVX (missing: _AVX_TRUE _AVX_OK) 
-- Could not find hardware support for AVX2 (missing: _AVX2_TRUE _AVX2_OK) 
-- NEON optimization enabled
-- Could NOT find Iso9660pp (missing: ISO9660PP_LIBRARY ISO9660PP_INCLUDE_DIR) 
-- Could NOT find MDNS (missing: MDNS_LIBRARY MDNS_INCLUDE_DIR) 
-- Could NOT find Udfread (missing: UDFREAD_LIBRARY UDFREAD_INCLUDE_DIR) 
-- FFmpeg 4.3 not found, falling back to internal build
-- #---- CONFIGURATION ----#
-- Platforms: gbm
-- -- PATH config --
-- Prefix: /usr/local
-- Libdir: /usr/local/lib
-- Bindir: /usr/local/bin
-- Includedir: /usr/local/include
-- Datarootdir: /usr/local/share
-- Datadir: /usr/local/share
-- Docdir: /usr/local/share/doc/kodi
-- ALSA enabled: Yes
-- AVAHI enabled: Yes
-- BLUETOOTH enabled: Yes
-- BLURAY enabled: Yes
-- CAP enabled: Yes
-- CCACHE enabled: Yes
-- CEC enabled: Yes
-- CLANGFORMAT enabled: Yes
-- CLANGTIDY enabled: No
-- CPPCHECK enabled: No
-- DAV1D enabled: Yes
-- DBUS enabled: Yes
-- INCLUDEWHATYOUUSE enabled: No
-- ISO9660PP enabled: No
-- LCMS2 enabled: Yes
-- LIRCCLIENT enabled: Yes
-- MDNS enabled: No
-- MICROHTTPD enabled: Yes
-- NFS enabled: Yes
-- PLIST enabled: Yes
-- PULSEAUDIO enabled: Yes
-- PYTHON enabled: Yes
-- SMBCLIENT enabled: Yes
-- SNDIO enabled: Yes
-- UDEV enabled: Yes
-- UDFREAD enabled: No
-- XSLT enabled: Yes
-- VAAPI enabled: Yes
-- MARIADBCLIENT enabled: Yes
-- Configuring done
-- Generating done

**Comment by AlD** [comment]
Seeing the same issue. On RPi4 with Archlinux ARM, when DRM PRIME decoder is enabled and playing h264 720p content, video lags behind a lot.

Disabling DRM PRIME seems the video to drop frames but stay A/V sync.

The log has:
```
2021-04-21 01:40:30.096 T:19902    INFO <general>: CVideoPlayerAudio::Process - stream stalled
2021-04-21 01:40:30.774 T:19634 WARNING <general>: OutputPicture - timeout waiting for buffer
```

**Comment by lrusak** [comment]
Closing this as the OP is using llvmpipe and is likely the reason for the slowdown.
