### ISSUE TITLE
Compile Issue 19.0-RC1 (18.9.910)

### ISSUE THREAD

**Issue by Flattermann78** [xbmc/xbmc#19161]
Hi,

it seems that there is an additional parameter in the method call:

/home/pi/src/kodi/xbmc/interfaces/legacy/Dialog.h:86:12: note: candidate: ‘bool XBMCAddon::xbmcgui::Dialog::yesno(const String&, const String&, const String&, const String&, int)’
       bool yesno(const String& heading, const String& message,
            ^~~~~
/home/pi/src/kodi/xbmc/interfaces/legacy/Dialog.h:86:12: note:   candidate expects 5 arguments, 6 provided

Compile failed on RPi 4 therefore.

**Comment by enen92** [comment]
Not sure about linux but the python_bindings need to be recompiled as some of the function signatures have changed. Remove all the *cpp.i and *xml.i files in the build/swig directory
