### ISSUE TITLE
Hang up when playing movies with google drive

### ISSUE THREAD

**Issue by ferboxplay** [xbmc/xbmc#19175]
Good afternoon, I'm having problems with the matrix rc 19.0 RC1 version. When playing a video file from the google drive addon the movie gets to play but stops in the first second. In the previous version, (leia) works without problems but it is not compatible with hdr10 and the colors are dull and the tone very dark. I am sending you the log files and screenshots. Please, I would appreciate some solution to solve this failure.

Log kodi Matrix -----https://1drv.ms/u/s!AkEEvAcFQvuln5dAivFQMtLwDHl7Zg?e=bHuQVG
Screenshoot movie 4k-hdr10 kodi Leia ----- https://1drv.ms/u/s!AkEEvAcFQvuln5dC84yt0_VuBmstyA?e=0wSgWQ

Log Kodi Leai ------https://1drv.ms/u/s!AkEEvAcFQvuln5dDjup-pJiaflatJQ?e=flHIJF

**Comment by arnova** [comment]
Please use eg. pastebin for logs, not microsoft drive. Not everyone has a Microsoft account....

**Comment by ferboxplay** [comment]
Log Kodi Matrix   ----  https://pastebin.com/puv2rLux
Log Kodi Leia --------  https://docs.google.com/document/d/1LBIidiEgrQQ-IHFSjjOBmsjwXSqSPIjWMoHJ76qsor4/edit?usp=sharing
Screenshoots -------- https://drive.google.com/file/d/14W7rDg_ztcR6wgj-MhIwuO84kzdljj0U/view?usp=sharing, 
                                   https://drive.google.com/file/d/1DTie_O2IjnIARa6E_MxSUmbgzjPJq82C/view?usp=sharing, 
                                   https://drive.google.com/file/d/1fuhKT5Z0hxaNjqf-tw2CAaaUJ1XEBovh/view?usp=sharing

**Comment by arnova** [comment]
Please turn on libcurl component debug logging and provide new logs with it. Furthermore you can try disabling file caching and see how it goes: https://kodi.wiki/view/Advancedsettings.xml#cache

**Comment by ferboxplay** [comment]
kodi log   libcurl ------        https://pastebin.com/pjrbwA1b

**Comment by arnova** [comment]
> kodi log libcurl ------ https://pastebin.com/pjrbwA1b

I don't see any attempts of playing files in this log. Furthermore: Did you try my suggestions concerning disabling filecache & http2?

**Comment by ferboxplay** [comment]
is that I can't find the option to disable these options within your interface. If it is editing the file, what path is this file in? Thank you

**Comment by arnova** [comment]
> is that I can't find the option to disable these options within your interface. If it is editing the file, what path is this file in? Thank you

Correct you need to create a file as described here: https://kodi.wiki/view/Advancedsettings.xml

**Comment by ferboxplay** [comment]
It has been fixed. Thank you very much !!!!! I'm very happy . You had to disable http2. I have included the line that you have told me in the advanced settings .xml file and the magic has occurred. Thank you very much for the time you have spent in solving it and I congratulate you for the work you are doing with Kodi and for having included the options of hdr10, 24hz, dolby atmos and dts-x.

**Comment by arnova** [comment]
Great to hear. Thanks for reporting back.

@wsnipex / others: Yet another issue with curl + http2. I wonder whether we should stick to defaulting to http2 for Matrix, could be asking for a lot of trouble. Not sure if this is a Windows-only issue though.

**Comment by wsnipex** [comment]
which of the logs shows the issue? I only see it opening the googledrive plugin.
As long as this hasn't been reproduced on other platforms, I see that as windows only.

**Comment by arnova** [comment]
> which of the logs shows the issue? I only see it opening the googledrive plugin.
> As long as this hasn't been reproduced on other platforms, I see that as windows only.

I believe this one: https://pastebin.com/puv2rLux

**Comment by wsnipex** [comment]
I don't see what's happening on HTTP/curl level, only CCache complaining about not reading any data.

**Comment by arnova** [comment]
> I don't see what's happening on HTTP/curl level, only CCache complaining about not reading any data.

That log had libcurl component logging disabled unfortunately.

**Comment by wsnipex** [comment]
@ferboxplay can you please provide a new debug log with curl component logging enabled?

**Comment by ferboxplay** [comment]
it won't let me paste the log with pastebin. I don't have a Pro account, can I share it with google drive?

**Comment by arnova** [comment]
> it won't let me paste the log with pastebin. I don't have a Pro account, can I share it with google drive?

Strange, pastebin should always work. Anyway, just use https://paste.kodi.tv/

**Comment by ferboxplay** [comment]
It tells me that the document I am going to generate exceeds the maximum size allowed

**Comment by playnoob69** [comment]
@ferboxplay How did you fix the issue, I also faced the same issue, I created a advancedsettings file and disabled cache and http2. But the issue still remains, It keeps stopping after 2-3 seconds and i have to force close. Please help me, It would mean a lot

**Comment by arnova** [comment]
> @ferboxplay How did you fix the issue, I also faced the same issue, I created a advancedsettings file and disabled cache and http2. But the issue still remains, It keeps stopping after 2-3 seconds and i have to force close. Please help me, It would mean a lot

Could be a totally different issue ofc. Without a debug log no one can tell.

**Comment by Sukehiro777** [comment]
> > is that I can't find the option to disable these options within your interface. If it is editing the file, what path is this file in? Thank you
> 
> Correct you need to create a file as described here: https://kodi.wiki/view/Advancedsettings.xml

Hey Thanks for Helping
but I have the same problem my Gdrive addon Vedio freeze after 1 sec or doesnt play it goes to infinite loading
I solved this problem by disabling the Http2 in advancedsetting.xml and it worked now video finally plays but a new problem arise that is video doest play smoothly(like its playing on 10 fps or somthing) it wont keep up with the audio(Audio doest lag its fine) and bit buffing also.
please help me to solve this issue Gdrive is a gem for me in kodi.
