### ISSUE TITLE
Problemas al reproducir con google drive

### ISSUE THREAD

**Issue by ferboxplay** [xbmc/xbmc#19173]
Buenas tardes , estoy teniendo problemas con la version matrix rc 19.0 RC1. Al reproducir un archivo de video desde el addon google drive la película llega a reproducirse pero se para en el primer segundo . En la anterior versión, (leia) funciona sin problemas pero no es compatible con hdr10 y los colores se ven apagados y el tono muy oscuro . Os mando los archivos  log y capturas de pantalla Por favor , agradecería alguna solucion para solucionar este fallo .
Gracias

Archivo Log kodi Matrix -----https://1drv.ms/u/s!AkEEvAcFQvuln5dAivFQMtLwDHl7Zg?e=bHuQVG
Capturas película 4k-hdr10 con kodi Leia ----- https://1drv.ms/u/s!AkEEvAcFQvuln5dC84yt0_VuBmstyA?e=0wSgWQ

Archivo Log Kodi Leai ------https://1drv.ms/u/s!AkEEvAcFQvuln5dDjup-pJiaflatJQ?e=flHIJF

**Comment by arnova** [comment]
Sorry, we can only accept bug reports in English.

**Comment by ferboxplay** [comment]
You already have it in English
