### ISSUE TITLE
Error on 'list of watched movies' with mySql database with Kodi v18.x (V19 is correct)

### ISSUE THREAD

**Issue by liberopadano** [xbmc/xbmc#19183]
### Describe the bug

Error in "watched movies list" when logging in with different users in the same session

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Correct list of movies watched by the current user.

## Actual Behavior

For the second user the list of movies watched is the same of the first.

### To Reproduce

0. each user has their own MySQL database 
1. start Kodi
2. logon user1
3. select film ('list of watched movies')
4. logoff user1
5. logon user2
6. select film ('list of watched movies') : Error - return 'list of watched movies' of user1
7. end Kodi

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/obafibuhum.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:  W10 10.0.19042
 - Kodi version: 18.9.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
As I'm trying to reproduce this issue, could you please explain a bit more. 

If I understand correctly you currently have 3 profiles
- master
- user1
- user2
and you set each of them up to use a mysql db, correct? For the master profile you didn't specify a filename to use for the mysqlDB so the default `MyVideosxyz` should be used. 

Can you please check the following:

- does it work as expected if you don't configure the master profile to use a mysql db?
- can you confirm 3 databases are present at your mysql instance?

**Comment by liberopadano** [comment]
see below.

thanks.

Il 07/02/2021 08:13, DaVukovic ha scritto:

**Comment by liberopadano** [comment]
Hi DaVukovic,

I have installed Kodi version 19 (Matrix) and the problem does not arise!

**Comment by DaVukovic** [comment]
Cool. Then let's close this issue as there won't be any bugfixes for Kodi 18 anymore
