### ISSUE TITLE
Error en para reproducir videos en Youtube

### ISSUE THREAD

**Issue by gcaskodi** [xbmc/xbmc#19180]
Mensaje de error: playlists player:skipping unplayable Item:0,path plugin://plugin.video.youtube/play
Tengo creada mi api y también cargada en el addons, puedo ver lo que busco pero cuando quiero reproducir el/los videos me tira el mensaje que vea registro de error.
Yo no soy desarrollador ni mucho menos,pero si un fanático de kodi...Abrazo y espero puedan ayudarme

**Comment by enen92** [comment]
We only accept issue reports in english. YouTube add-on is somehow deprecated, use Tubed instead.

**Comment by gcaskodi** [comment]
Error message: playlists player: skipping unplayable Item: 0, path plugin: //plugin.video.youtube/play
I have created my api and also loaded into the addons, I can see what I'm looking for but when I want to play the video / videos it throws me the message that I see error log.
I'm not a developer by any means, but if a kodi fanatic ... Hug and I hope you can help me

**Comment by enen92** [comment]
This repository is for Kodi core, meaning we only track Kodi issues not add-ons. Bring the issue to the YouTube add-on developer: https://github.com/anxdpanic/plugin.video.youtube or use the Kodi forum.

But like I said earlier, the YouTube add-on is being replaced by Tubed: https://forum.kodi.tv/showthread.php?tid=358806
