### ISSUE TITLE
Kodi19 shows no images when playing HDR videos

### ISSUE THREAD

**Issue by FerGitH** [xbmc/xbmc#19199]
### Describe the bug
Here is a clear and concise description of what the problem is:

When trying to play a HDR video file. the TV shows "no video" on the screen.

Note: the no video message on the TV is not produced by the computer. The TV shows this message when there is not a valid signal coming through HDMI (or the PC is switched off)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The video should reproduce and the HDR setting should be activated on the TV

## Actual Behavior

The video doesn't play

### To Reproduce

1.  HDR setting is on in kodi
2. play HDR video 
3.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/izacavesoz.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64
 - Kodi version: 19 rc1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Log posted is not a "debug" log, anyway:

> INFO <general>: Desktop Resolution: 3840x2160 32Bit at 120Hz

HDMI 2.0a/b does not support 3840x2160 HDR at 120Hz. Only HDMI 2.1 supports 4K at >60Hz.

Change Windows desktop resolution to 3840x2160 @ **60Hz**.

**Comment by FerGitH** [comment]
Hi,

Thanks for your help.
