### ISSUE TITLE
Problems with addon google drive in matrix rc1 version

### ISSUE THREAD

**Issue by ferboxplay** [xbmc/xbmc#19195]
Good afternoon, I'm having problems with the matrix rc 19.0 RC1 version. When playing a video file from the google drive addon the movie gets to play but stops in the first second. In the previous version, (leia) works without problems but it is not compatible with hdr10 and the colors are dull and the tone very dark. I am sending you the log files and screenshots. Please, I would appreciate some solution to solve this failure. 
I have an amd ryzen 5 3400g processor with 16gb of ddr4 ram and an nvidia rtx 3060 ti graphics card.
With kodi Leia they reproduce me well but with altered colors. With Kodi matrix it gives me the error that it only plays the first second of the movie

Log kodi Matrix -----https://1drv.ms/u/s!AkEEvAcFQvuln5dAivFQMtLwDHl7Zg?e=bHuQVG
Screenshoot movie 4k-hdr10 kodi Leia ----- https://1drv.ms/u/s!AkEEvAcFQvuln5dC84yt0_VuBmstyA?e=0wSgWQ

Log Kodi Leai ------https://1drv.ms/u/s!AkEEvAcFQvuln5dDjup-pJiaflatJQ?e=flHIJF

**Comment by arnova** [comment]
What makes this bug report different than https://github.com/xbmc/xbmc/issues/19175 ? More reports doesn't help fixing the problem faster....

**Comment by ferboxplay** [comment]
It is the same but it took 3 days without getting any response, or reply that we will investigate. Thank you

**Comment by arnova** [comment]
That's not how it works. We'll have a look when someone has the time. Could be days, weeks or months. Anyway, nagging won't help your case....

**Comment by ferboxplay** [comment]
I'm not scolding you, I was just telling you what happened. There is no rush, if I would like you to take it into account. Thanks for your work
