### ISSUE TITLE
On embedded Python 3 package of Kodi 19 is missing "socket.ioctl" method

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#19204]
### Describe the bug
Here is a clear and concise description of what the problem is:

I am working to resolve web connections problems due to a missing TCP Keep-Alive flow in an add-on,
I solved it on Kodi 18/Python 2 but on Kodi 19/Python 3 it seems not possible.

after various researches we have reached the conclusion that Python 3 included on Kodi 19 for Windows
not include `socket.ioctl` that is a specified method for Windows to allow set TCP Keep-Alive settings and other things.

If you try to access to `ioctl` always raise AttributeError, this not happen on Python 2 in Kodi 18.x,
and not happen if you run Python3 locally (system installed - outside kodi) in a script,
then make me think that something is missing on Python3 package of Kodi 19 for Windows.

This prevents the activation of this important function for TCP connections
I would like that a fix will be included in Kodi 19.x because this causes serious web connection problems with Python
for all servers that use Keep-Alive to keep TCP connections alive over the time and don't break the session pool connections (Requests+urllib3).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Have `socket.ioctl` method accessible

## Actual Behavior

Access to `socket.ioctl` raise AttributeError

## Possible Fix

Possible some missing/wrong flag on python3 build?

### To Reproduce

1. Install a TCP server on a device or computer (i have installed "TCP socket test" app on Android)
1. Install this test add-on: [test.keepalive.addon.zip](https://github.com/xbmc/xbmc/files/5956886/test.keepalive.addon.zip) and disable it
2. Edit the service.py of the addon set the IP_SERVER and PORT_SERVER
3. Start your TCP server, and start the Kodi add-on
4. At this point on Kodi 18 this works (see screenshot), on Kodi 19 raise error

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/irohihiyop.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Kodi 18 monitored by Wireshark, ioctl works and TCP Keep-Alive packets works:
![immagine](https://user-images.githubusercontent.com/3257156/107487318-5cb3a980-6b86-11eb-94a5-58220b0af596.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I add as info, i have no idea is this can be useful (SIO_RCVALL define):
https://github.com/python/cpython/blob/master/Modules/socketmodule.c#L4815
the SIO_RCVALL seem related to mstcpip.h of windows sdk

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Kodi 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
@Paxxi if you ever find time, any idea about this?

**Comment by Paxxi** [comment]
Thank you for this excellent bug report. The provided addon made it so much easier to verify the fix.

**Comment by CastagnaIT** [comment]
@Paxxi you can backport to Kodi 19?
this is a big problem with Python addons there is no way to handle in a good way connections with Requests and urllib modules

**Comment by CastagnaIT** [comment]
if this will not backported,
the only possible way for each addon is to modify windows Registry and force KeepAlive connections to each device,
and this means that it will be reflected to the entire Windows system and this change can not reverted easly
is a solution to be avoided and not exists other ways.... ioctl (temporary per single connection) or regedit (whole system)

**Comment by Paxxi** [comment]
With V19 release so close I labeled it for V20. I don't see any issues with including it in 19.1

**Comment by CastagnaIT** [comment]
thank you i will wait 19.1

**Comment by enen92** [comment]
This has been merged in master yesterday, closing and labelled as fixed
