### ISSUE TITLE
Spatial sound not working in Windows

### ISSUE THREAD

**Issue by Jivko1212** [xbmc/xbmc#19209]
### Describe the bug

Here is a clear and concise description of what the problem is:

I am unable to use any of the spatial audio virtualization options in Windows 10, with Kodi Matrix RC or latest Leia. It results in the player crashing or alternatively the sound options do not allow me to enable passthrough. Spatial audio is useful if the user doesn't have surround sound system or wants to watch at night without disturbing others. The problem occurs when using any of the spatial audio options in Windows 10. Spatial audio works fine when using any player based on LAV filters or Windows Media Player.

In order to use spatial audio the user needs to go to control panel->sound->Playback, right click the sound device and make sure advanced exclusive mode is unchecked and that in the Enhancement tab Disable all enhancement is not checked. If exclusive mode is checked and the device supports passthrough it is not virtualized but passed directly. If Disable all enhancements is checked it seems that virtualization also cannot start.

The first problem is that with this setup I cannot enable TrueHD capable receiver, Dolby Digital Plus (E-AC3) capable Receiver, and DTS-HD capable receiver. Dolby Digital (AC3) capable Receiver can be enabled and DTS capable receiver can be enabled, but playing any file with AC3/DTS audio crashes. Passthrough is needed because some of the advanced virtualization engines like Dolby Atmos for Headphone and DTS Headphone X seem to be doing a good job when passed formats like Atmos or DTS:X.

I am not sure the issue is a bug, but headphone virtualization is a nice feature to have. 
## Expected Behavior

Here is a clear and concise description of what was expected to happen:
There should be some way for users to use headphone virtualization which is built into Windows 10 and is even available on Xbox consoles. Users should be able to use spatial audio by plugging into the TV/PC audio jack or say by plugging into an Xbox One controller.

## Actual Behavior

Crashes and inability to use audio virtualization.

## Possible Fix

Examine what in the passthrough code is causing the issue. Fix the issue. Allow the user to force passthrough when the audio device doesn't support it, or it would be even easier for users if spatial audio is detected then automatically use passthrough.

### To Reproduce

1.  Enable Windows Sonic for Headphones, Dolby Atmos for Headphones or DTS Headphone:X by right clicking the sound icon.
2. Go to control panel-> sound->Playback, and into the properties of the current device, make sure advanced exclusive mode is unchecked and that in the Enhancement tab Disable all enhancement is not checked
3. Play a file with AC3, EAC3, DTS, DTS-HD or TrueHD audio

### Debuglog

The debuglog can be found here:
[DIRECTSOUND CRASH.zip](https://github.com/xbmc/xbmc/files/5962455/DIRECTSOUND.CRASH.zip)
[ONLY DOLBY DIGITAL RECEIVER.zip](https://github.com/xbmc/xbmc/files/5962457/ONLY.DOLBY.DIGITAL.RECEIVER.zip)

Both of these files are with exclusive mode disabled. In passthrough settings I can choose only WASAPI default and DIRECTSOUND HDMI. With directsound HDMI, I get the crash, with WASAPI default I get only option to enable AC3 capable receiver. No other options are available.

If I enable exclusive mode it crashes if the audio device is not capable of bitstream formats and sends passthrough if it is. I have not included logs for this case because this is the behavior of other players.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.0-RC1 and Kodi 18.9 (Same behavior)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Jivko1212** [comment]
Discovered that I can get it to work by disabling passhthrough and setting output to 7.1, best match.

**Comment by ThreeDeeJay** [comment]
This also works with HeSuVi for better virtual surround for headphones:
https://airtable.com/shrtTsUtiAJQ7wFGI/tblNOTdmp5nHXfFGU/viwjDPuKOjBnIQunv/rectXvLMtrDb11tgD
But for spatial/3D audio formats, something like passthrough would probably be required so that Kodi offloads decoding to an external decoder and spatializer like [Cavern](https://github.com/VoidXH/Cavern/issues/61), but sadly the only way I know is using a UWP Media Foundation apps like Movies & TV to decode Dolby Digital+ Atmos (TrueHD not supported) to the Microsoft Spatial Sound API for Sonic/Atmos/DTS spatializers to take over.
Or, just use a capable AV receiver lol.
