### ISSUE TITLE
SMBDirectory->GetDirectory: Unable to open directory 'Too many open files'

### ISSUE THREAD

**Issue by Portisch** [xbmc/xbmc#19212]
### Describe the bug
Here is a clear and concise description of what the problem is:

```text
2021-02-11 11:29:14.513 T:46193   ERROR <general>: SMBDirectory->GetDirectory: Unable to open directory : 'smb://USERNAME:PASSWORD@192.168.1.7/Music/Jimmy%20Eat%20World'
                                                   unix_err:'18' error : 'Too many open files'
2021-02-11 11:29:14.513 T:46193   ERROR <general>: GetDirectory - Error getting smb://192.168.1.7/Music/Jimmy Eat World/
2021-02-11 11:29:14.513 T:46193   DEBUG <general>: DoScan Scanning dir 'smb://192.168.1.7/Music/Jimmy Eat World/' as not in the database
```

## Actual Behavior

Scanning a library on samba share fails when it contain a lot of files.

### To Reproduce

1. map a library folder and scan the folder with a lot of files.

### Debuglog

The debuglog can be found here:
[kodi.zip](https://github.com/xbmc/xbmc/files/5964575/kodi.zip)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Ubuntu 18.04.5 LTS, kernel: Linux x86 64-bit version 5.4.0-65-generic
 - Kodi version:
Kodi (19.0-RC1 (18.9.910) Git:20210207-af9b6445fd)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by vpeter4** [comment]
Same issue with LibreELEC-Generic.x86_64-9.80-nightly-20210210-15d426f: https://forum.libreelec.tv/thread/23487-too-many-open-files-with-libreelec-generic-x86-64-9-80-nightly-20210210-15d426f/

**Comment by wsnipex** [comment]
how many files are we talking about?
I assume raising the limit (ulimit -n) helps?

**Comment by msebald** [comment]
> how many files are we talking about?
> I assume raising the limit (ulimit -n) helps?

LibreELEC is on 1024. No idea if raising the limit would help. Until some recent builds it was enough, not it is not anymore. Without changing anything with configurations, addons... So the guess is that there is some sort of issue.

**Comment by Portisch** [comment]
I think the same. A lot of users reporting this issue on various platforms. Non users (same like me) changed nothing on the system. So it have to be a Kodi issue like the files aren't closed anymore maybe a parallel threading issue.

**Comment by wsnipex** [comment]
can anyone with the issue compile kodi yourself? If so, please try reverting https://github.com/xbmc/xbmc/commit/e8dffe23ddc2b9b7fdcfa74c8a81bca47828b79b

**Comment by vpeter4** [comment]
Is this correct - missing exclamation mark?
https://github.com/xbmc/xbmc/blob/e8dffe23ddc2b9b7fdcfa74c8a81bca47828b79b/xbmc/platform/posix/filesystem/SMBFile.cpp#L598

**Comment by arnova** [comment]
> Is this correct - missing exclamation mark?
> https://github.com/xbmc/xbmc/blob/e8dffe23ddc2b9b7fdcfa74c8a81bca47828b79b/xbmc/platform/posix/filesystem/SMBFile.cpp#L598-L600
> 
> Or maybe use
> 
> ```
>     if (smb.IsSmbValid())
>       smbc_close(m_fd);
> ```
> 
> Seems to be working with this change - playing one file 3 times in a row.
> before
> 
> ```
> 09:52:04.478    DEBUG <general>: CSMBFile::Close closing fd 10000
> 09:52:10.734    DEBUG <general>: CSMBFile::Close closing fd 10001
> 09:52:15.477    DEBUG <general>: CSMBFile::Close closing fd 10002
> ```
> 
> after
> 
> ```
> 09:34:19.734    DEBUG <general>: CSMBFile::Close closing fd 10000
> 09:34:31.594    DEBUG <general>: CSMBFile::Close closing fd 10000
> 09:34:43.463    DEBUG <general>: CSMBFile::Close closing fd 10000
> ```

Yes that looks wrong.

**Comment by Karlson2k** [comment]
Yes, missing '!'.
Copy-paste error.

**Comment by Karlson2k** [comment]
I'll recheck whole my patch one more time.
I noticed leaking FDs on my setups as well.
Thanks for pointing exact place.
