### ISSUE TITLE
"Record" button on TV and Radio

### ISSUE THREAD

**Issue by Max11223344** [xbmc/xbmc#19225]
Record button on 'Radio'

Playing TV and pressing the white 'Record' button there is on-screen information that the recording has started, the button turns red and additionally there is a red point on screen.

Playing Radio and pressing the white 'Record' button there is only the on-screen information. The button remains white, no additional point on the screen.

I would like to have the red button recording Radio too.(If this is possible ;-) )

## Expected Behavior
When listening to Radio stations and pressing the white circle (record button) the button should turn red, indicating a recording is taking place (as it does when watching a TV station and pressing there the record-button)

## Actual Behavior
The record button remains white, there is only a short information, that the recording has started.

## Possible Fix
Copy the appropriate lines from the TV-Recording behaviour

### To Reproduce
1. Start Raspian 
2.  select Kodi (in my case 18.7 as Raspian offers no newer version)
3. select Radio
4. select a free station
5. listen to the station
6. press the "record" button (should turn red now (like in TV)

### Debuglog
There is no log for this:

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux (RaspiOS) Raspberry pi4 4GB
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Leia 18.7  (latest for Raspi available version) Skin: Confluence

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
???

![screenshot00003](https://user-images.githubusercontent.com/3226626/107853533-f2656800-6e16-11eb-833f-2be529a56c38.png)

**Comment by ksooo** [comment]
Does the recording actually start and you're facing a UI glitch only?

Which PVR backend are you using?

**Comment by ksooo** [comment]
Okay, I can reproduce this. The recording starts, it's a glitch in the skin Confluence, which does not turn the record button red for radio recordings, @HitcherUK.

**Comment by ksooo** [comment]
Radio:

![screenshot00001](https://user-images.githubusercontent.com/3226626/107853862-97347500-6e18-11eb-9314-7cbd6a243e74.png)

TV:

![screenshot00005](https://user-images.githubusercontent.com/3226626/107853863-97cd0b80-6e18-11eb-8813-fe1e42d75625.png)

**Comment by ksooo** [comment]
@Max11223344 as this is an issue specific to the Confluence skin, please open an issue here: https://github.com/xbmc/skin.confluence/issues

**Comment by Max11223344** [comment]
Thanks for your fast reaction. :-)
