### ISSUE TITLE
"Record" Button on Kodi 18.7

### ISSUE THREAD

**Issue by Max11223344** [xbmc/xbmc#19224]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Max11223344** [comment]
Record button on 'Radio'

Playing TV and pressing the white 'Record' button there is on-screen information that the recording has started, the button turns red and additionally there is a red point on screen.

Playing Radio and pressing the white 'Record' button there is only the on-screen information. The button remains white, no additional point on the screen.

I would like to have the red button recording Radio too.(If this is possible ;-) )

**Comment by fuzzard** [comment]
Really should have just filled out the template

**Comment by Max11223344** [comment]
somehow i messed up with the form :(
Kodi 18.7 indide Raspi OS using TVheadend
