### ISSUE TITLE
Kodi freezes while playing DVB-T2 stream using tvheadend PVR client

### ISSUE THREAD

**Issue by petrslais** [xbmc/xbmc#19231]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi freezes while playing DVB-T2 stream using tvheadend PVR client

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No freeze.

## Actual Behavior

A buffering circle appears, typically it finishes to reach 100%, but video won't play again.

### To Reproduce

No known exact reproduction steps, freezes are either random (anytime during the day) or there were already 3-4 freezes at 21:06 like today.

Today I switched channels :
2021-02-14 21:06:06.694 T:2756702416   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - demux successfully unsubscribed from channel id 251854574, subscription id 54
...
2021-02-14 21:06:06.696 T:2756702416   DEBUG: operator(): Opening live stream for channel 'Nova Cinema'
...
2021-02-14 21:06:06.709 T:2756702416   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - demux successfully subscribed to channel id 167663264, subscription id 55
...
2021-02-14 21:06:06.710 T:2701160656   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true

few seconds after switching channel, I barely saw few frames of the new channel, the picture did freeze, than screen becomes black, than the buffering circle appears and the TV stops responding to CEC commands. 
While login to OS level, these errors are flooding kodi.log :

2021-02-14 21:06:29.067 T:2217300176   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - Dropped packet with unknown stream index 1003

### Debuglog

The debuglog can be found here:
[kodi.old.log.gz](https://github.com/xbmc/xbmc/files/5978489/kodi.old.log.gz)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

After few occurences I enabled following debug options:
pi@raspberrypi:~/.kodi $ cat ./userdata/advancedsettings.xml
<advancedsettings>
  <cache>
    <buffermode>1</buffermode>
    <memorysize>209715200</memorysize>
    <readfactor>30</readfactor>
  </cache>
  <loglevel hide="true">3</loglevel>
  <setting id="debug.extralogging">true</setting>
  <setting id="debug.setextraloglevel">32,1048576,2097152</setting>
</advancedsettings>

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
 - pi@raspberrypi:~/.kodi $ uname -a
Linux raspberrypi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
pi@raspberrypi:~/.kodi $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
...
pi@raspberrypi:~/.kodi $ apt show kodi
Package: kodi
Version: 2:18.7-1~buster
...

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
`Starting Kodi (18.7 Git:20200528-2c5354e70a). Platform: Linux ARM 32-bit`
No fixes will be done for Kodi Leia anymore. Please try matrix.

**Comment by beemach** [comment]
I have this exact same issue. Seems to occur more frequently when seeking forward in quick succession in and around defected commercial breaks. 

@petrslais did you manage to try with matrix? I’m not sure how to get matrix on raspian for the Pi 4 yet without compiling myself.

**Comment by petrslais** [comment]
I haven't tried Matrix, I keep the default Buster repositories, waiting for Bullseye.

The 18.7 freezes more often when there is no menu interaction. Sometimes it just freezes (and allows reboot over ssh), sometimes it freezes Raspbian completely (power off/on required), sometimes it causes it to reboot.
Out of the performance monitoring, I can just guess there is some memory leak as memory consumption grows rapidly before freeze/reboot.

I'm about to split TVtuner/tvheadend functionality to separate Raspberry Pi to test if it makes any difference in Kodi TV playback stability.

**Comment by beemach** [comment]
I will try Matrix but also waiting. It didn't seem straight forward to compile for the Pi. I used to run Kodi and TVHeadend on seperate Pis - Raspbian for TvHeadend and LibreElec for Kodi which worked really well, however in the end I consolidated given the Pi4 has enough resources to run both.

**Comment by beemach** [comment]
So I managed to compile and get Kodi 19.1 matrix running on pi4 and the good news is I wasn’t able to replicate the problem again. The bad news is that there is no deinterlace support for HW accelerated deciding which means sports and fast motion is a really poor received experience. I’ve now reverted back to Kodi 18 while waiting for deinterlace support for HW decoding in Kodi 19 matrix.

**Comment by ksooo** [comment]
> So I managed to compile and get Kodi 19.1 matrix running on pi4 and the good news is I wasn’t able to replicate the problem again. 

 Thanks for confirming. Closing this issue.

> The bad news is that there is no deinterlace support for HW accelerated deciding

 This is a  feature request and not related to this issue.
