### ISSUE TITLE
No way to connect to MySQL via unix socket

### ISSUE THREAD

**Issue by lameventanas** [xbmc/xbmc#19245]
### Describe the bug
Here is a clear and concise description of what the problem is:

After upgrading from kodi 18.9 to 19RC1, I discovered it can't retrieve my MySQL library.
I'm running MySQL using --skip-networking, all my programs connect via unix socket.
In Linux, when specifying "localhost" as the host argument in `mysql_real_connect()`, the MySQL client library will automatically try to connect via unix socket first.
But kodi is trying to resolve the host before connecting, so it will never connect via socket, even when using "localhost".

## Possible Fix

Many options:
1. Add a field to specify the unix socket to use to connect
2. Don't try to resolve if the host is "localhost"
3. Don't try to resolve anything, let the mysql libraries do their job

### To Reproduce

Configure advancedsettings.xml with:
```
<videodatabase>
<type>mysql</type>
<host>localhost</host>
...
</videodatabase>
```

### Debuglog

The debuglog can be found here:
```
2021-02-18 09:59:47.807 T:23718   ERROR <general>: Unable to open database: kodi_video116 [2003](Can't connect to MySQL server on '127.0.0.1' (111))
2021-02-18 09:59:47.807 T:23718   DEBUG <general>: connect replacing configured host localhost with resolved host 127.0.0.1

```
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: CRUX
 - Kodi version: 19.0RC1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lameventanas** [comment]
The commit responsible for this change is 0b9ac366314a35c73b568247811bb49832f54a25

**Comment by wsnipex** [comment]
Another corner case :(
would you mind sending a PR for 2: Don't try to resolve if the host is "localhost"?

**Comment by DaveTBlake** [comment]
> I was working on this, didn't realize someone else did it because I received no notification :(

Sorry about that @lameventanas, auto notification does not always work as expected. Things moved rapidly to get fix into imminent release. Can you try v19.0 and confirm this is solved so can be closed.

**Comment by lameventanas** [comment]
I tried v19.0, it connects via unix socket now! :)
