### ISSUE TITLE
"Operation not permitted" attempting to access drive shared from Mac (SMB/Zeroconf) running Big Sur

### ISSUE THREAD

**Issue by CrazedLeper** [xbmc/xbmc#19249]
### Describe the bug
Here is a clear and concise description of what the problem is:

Network share appears in Kodi dialog while browsing, but will not open when selected. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Network share expected to open, listing folders to add to media sections.

## Actual Behavior

Error: "Operation not permitted."

## Possible Fix

No idea, but while I suspect my OS is the source of the problem, I think there might also be other ways that Kodi could circumvent the shortfall.

### To Reproduce

1. Install Kodi Matrix 19.0-RC1 (18.9.910)
2. Execute app
3. Attempt to add media to any source.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/eyococeviw

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Kodi Screenshot 1](https://user-images.githubusercontent.com/10342728/108566266-238cdf00-72d4-11eb-9374-e5fdfe8ec123.jpg)
![Kodi Screenshot 2](https://user-images.githubusercontent.com/10342728/108566291-2e477400-72d4-11eb-98d1-fc9e7a46c760.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Unable to use app, at all.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
MacOS, Big Sur 11.3 beta (20E5186d)

 - Kodi version:
Kodi Matrix 19.0-RC1 (18.9.910)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by kambala-decapitator** [comment]
force min/max SMB version to 1 in Kodi settings, this is known to work on Catalina

**Comment by DaVukovic** [comment]
Exactly. Adding SMB shares should be done via the "Add network location"-option, then select the specific protocol (in this case "Windows network (SMB)"), then add the needed entries at the upcoming dialog.

The steps are explained at our wiki: https://kodi.wiki/view/SMB

But, as this is a "bug report"-section and user support is given at the forums, I'll close this one.
