### ISSUE TITLE
Kodi 19 rc1 resume crash with DTS-HD MA passthrough

### ISSUE THREAD

**Issue by muncrief** [xbmc/xbmc#19242]
### Describe the bug
Here is a clear and concise description of what the problem is:

When attempting to resume a movie with DTS-HD MA passthrough Kodi 19 rc1 crashes on both Windows and the Android TV based Nvidia Shield 2019. This does not occur when passthrough is disabled, or when using normal DTS passthrough. So far I've only found this problem with one movie, but since it's so consistent a fix should probably be implemented since Kodi shouldn't crash even if there's something wrong with a movie's encoding.

I've also re-encoded the movie with multiple tools, and tested the physical Blu-ray, but the problem remains. 

EDIT:
The initial Shield log shows the error using the Android IEC packer because I'd been trying many things to isolate the cause of the bug. However I normally use the Kodi IEC packer, which behaves identically, so I've added that log as well.

I also forgot to mention that I played the movie with VLC on Windows and Linux, and VLC and SMPlayer on Linux, and it works fine. However neither of these players are able to ultimately output DTS-HD MA, even though that's the track I selected. So I'm not sure how that affects playback. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The movie should resume without crashing.

## Actual Behavior

When resuming from any position in the movie the spinning circle appears for about 30 seconds, and then Kodi crashes.

### To Reproduce

1. Start movie.
2. Stop movie.
3. Attempt to resume and Kodi will crash.

### Debuglog

The debuglog can be found here:
Shield TV with Android IEC packer: https://mega.nz/file/ILYVxYJa#Oe98zlITlZw7yjv31X6yMPC2qabTtaKrVneZZ8ZtsHI
Shield TV with Kodi IEC packer: https://mega.nz/file/UOQmwJ5L#ZrGogszJjpvInhO5eHLKvZ034LjuIKgM3NhEwYIqm10
Windows: https://mega.nz/file/pCZFAC5S#YroVL04kDAyMDRVAY2v004EpNVfWso-adBCG8uMmGPk

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19 Release Candidate 1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Noone will download files to read logs. Please add the logs at: 

https://paste.kodi.tv

And please update to the newest Kodi version available. We've release Kodi 19.0 already. 

If possible, provide a snippet of the affected video, so we might be able to reproduce.

**Comment by CastagnaIT** [comment]
changes have been made over time
can you test if still crash on last Kodi 19.4 and if possible also on Kodi 20 nightly?
