### ISSUE TITLE
Multiple video players aka Picture In Picture

### ISSUE THREAD

**Issue by m5x** [xbmc/xbmc#19255]
With every release Kodi is getting close to perfection but there is still one big feature missing and that is the ability to play multiple videos from different sources at the same time.

I understand it's a feature which Kodi code base was not prepared for and requires major refactoring. I am creating this issue with the hope that it may serve as a source of information about progress on the road to this feature for all Kodi users who (like me) search for news on PIP implementation every time new Kodi version is released.

Could someone from Kodi team post an update here from time to time? Just a checklist or even a notice it is being planned would be great news for us.

**Comment by fuzzard** [comment]
Feature requests are handled on the forums. 
There would be no point keeping this here for "Kodi team to update from time to time", as it will just sit and get no further updates of value ever.
When PiP ever gets implemented, im sure it'll be made very clear in release notes.
