### ISSUE TITLE
Audio defaults to DirectSound after the display goes to sleep

### ISSUE THREAD

**Issue by mcfloyd** [xbmc/xbmc#19252]
### Describe the bug

When the Windows PC turns off the display, upon returning, the audio device is forgotten and kodi will default to DirectSound (no passthrough).  The workaround is to exit the video playback, go into settings -> system -> audio, and then it is fixed.  The settings will enumerate the audio devices when viewing the audio settings page and "remember" that there is a passthrough device.

I have to do this multiple times a day since I usually walk away from the PC and have a very short display shut-off so that I don't burn in my OLED TV.

Small update: resuming a paused video file will still use passthrough audio as if nothing happened.  However, stopping the video and playing something else will then use PCM.

## Expected Behavior

Kodi should playback passthrough surround audio.

## Actual Behavior

Kodi will force DirectSound and I do not get a passthrough stream when playback starts.

## Possible Fix

Kodi should enumerate the audio devices right before playback, so that I don't need to go into settings -> system -> audio to force it.

### To Reproduce

1.  Let the Windows 10 PC put the display to sleep
2.  Wake up the display up
3.  Play a video file with digital surround passthrough

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/6018378/kodi.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 1909
 - Kodi version: 19-RC1
 - Audio device: Denon AVR-X2600H
 - Plugin: emby for kodi (next)
 - TV: LG OLED55B7A

**Comment by DaVukovic** [comment]
You have an outdated Kodi installed. 

`Starting Kodi (19.0-RC1`

Please install the stable version first and get us a new log please if the issue still exists

**Comment by mcfloyd** [comment]
Hello, I have upgraded to the 19.0.0 version and am still seeing the same problem.  Updated the bug report above with a new log file and kodi version number.
