### ISSUE TITLE
xbmc-19.0-Matrix: 11 * slow and redundant  ?

### ISSUE THREAD

**Issue by dcb314** [xbmc/xbmc#19257]
xbmc-19.0-Matrix/xbmc/Application.cpp:2257:12: performance: Passing the result of c_str() to a function that takes
 std::string as argument no. 1 is slow and redundant. [stlcstrParam]
xbmc-19.0-Matrix/xbmc/dbwrappers/DatabaseQuery.cpp:249:20: performance: Passing the result of c_str() to a functio
n that takes std::string as argument no. 1 is slow and redundant. [stlcstrParam]
xbmc-19.0-Matrix/xbmc/dbwrappers/DatabaseQuery.cpp:259:22: performance: Passing the result of c_str() to a functio
n that takes std::string as argument no. 1 is slow and redundant. [stlcstrParam]
xbmc-19.0-Matrix/xbmc/Util.cpp:718:35: performance: Passing the result of c_str() to a function that takes std::st
ring as argument no. 1 is slow and redundant. [stlcstrParam]
xbmc-19.0-Matrix/xbmc/Util.cpp:727:37: performance: Passing the result of c_str() to a function that takes std::st
ring as argument no. 1 is slow and redundant. [stlcstrParam]
xbmc-19.0-Matrix/xbmc/Util.cpp:741:37: performance: Passing the result of c_str() to a function that takes std::st
ring as argument no. 1 is slow and redundant. [stlcstrParam]
xbmc-19.0-Matrix/xbmc/utils/Crc32.cpp:108:10: performance: Passing the result of c_str() to a function that takes 
std::string as argument no. 1 is slow and redundant. [stlcstrParam]
xbmc-19.0-Matrix/xbmc/utils/ScraperParser.cpp:302:32: performance: Passing the result of c_str() to a function tha
t takes std::string as argument no. 1 is slow and redundant. [stlcstrParam]
xbmc-19.0-Matrix/xbmc/Application.cpp:556:21: performance: Passing the result of c_str() to a function that takes 
std::string as argument no. 2 is slow and redundant. [stlcstrParam]
xbmc-19.0-Matrix/xbmc/interfaces/AnnouncementManager.cpp:326:9: performance: Passing the result of c_str() to a fu
nction that takes std::string as argument no. 2 is slow and redundant. [stlcstrParam]
xbmc-19.0-Matrix/xbmc/interfaces/AnnouncementManager.cpp:326:9: performance: Passing the result of c_str() to a fu
nction that takes std::string as argument no. 3 is slow and redundant. [stlcstrParam]

**Comment by lrusak** [comment]
please file a PR with the changes

**Comment by dcb314** [comment]
Thanks for your kind offer, but I won't be filing a PR.

I am happy for someone else interested to do so.
