### ISSUE TITLE
compilation crash on Bionic Ubuntu 18.04

### ISSUE THREAD

**Issue by nephaste** [xbmc/xbmc#19265]
## Bug report

tried compil from source to build a package for Qnap HDStation based on Ubuntu 18.04 x64
compiled with 

[cmake ../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=${PREFIX} -DENABLE_INTERNAL_FMT=ON -DENABLE_INTERNAL_CROSSGUID=ON -DENABLE_INTERNAL_RapidJSON=ON -DENABLE_INTERNAL_FFMPEG=ON -DENABLE_INTERNAL_SPDLOG=ON -DAPP_RENDER_SYSTEM=gles  -Wno-dev -DENABLE_INTERNAL_GTEST=ON -DENABLE_INTERNAL_DAV1D=ON
](url)

but crashed on make

root@BIONIC_KODI:/TEMPO/xbmc-19.0-Matrix/build# make V=1
[  1%] Built target kodi-xrandr
[  2%] Built target gtest
[  3%] Built target crossguid
[  3%] Built target dav1d
[  3%] Built target ffmpeg
[  3%] Copying files into build tree
[  3%] Built target export-files
[  3%] Built target dvdcss
[  4%] Built target fmt
[  4%] Built target generate-wayland-extra-protocols
[  5%] Built target dvdread
[  6%] Built target dvdnav
[  6%] Built target network_httprequesthandlers_python
[  6%] Built target sse4
[  6%] Built target wrapper
[  6%] Built target wrapper.def
[  6%] Built target wrap_libdvdnav
[  6%] Built target kodi-libraries
[  6%] Built target TexturePacker
[  6%] Built target pack-skins
[  6%] Built target compileinfo
[  6%] Built target rp-process-x11
[  6%] Built target processX11
[  7%] Building CXX object build/windowing/X11/CMakeFiles/windowing_X11.dir/GLContextEGL.cpp.o
/TEMPO/xbmc-19.0-Matrix/xbmc/windowing/X11/GLContextEGL.cpp: In member function ‘virtual void CGLContextEGL::Destroy()’:
/TEMPO/xbmc-19.0-Matrix/xbmc/windowing/X11/GLContextEGL.cpp:294:5: error: ‘glFinish’ was not declared in this scope
     glFinish();
     ^~~~~~~~
/TEMPO/xbmc-19.0-Matrix/xbmc/windowing/X11/GLContextEGL.cpp: In member function ‘virtual void CGLContextEGL::Detach()’:
/TEMPO/xbmc-19.0-Matrix/xbmc/windowing/X11/GLContextEGL.cpp:319:5: error: ‘glFinish’ was not declared in this scope
     glFinish();
     ^~~~~~~~
build/windowing/X11/CMakeFiles/windowing_X11.dir/build.make:82: recipe for target 'build/windowing/X11/CMakeFiles/windowing_X11.dir/GLContextEGL.cpp.o' failed
make[2]: *** [build/windowing/X11/CMakeFiles/windowing_X11.dir/GLContextEGL.cpp.o] Error 1
CMakeFiles/Makefile2:6038: recipe for target 'build/windowing/X11/CMakeFiles/windowing_X11.dir/all' failed
make[1]: *** [build/windowing/X11/CMakeFiles/windowing_X11.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

tried to change gl to gles ... same problem

### To Reproduce

1. downlaod source from github
2.add ppa and apt build-dep kodi
3.launch cmake 

cmake ../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=${PREFIX} -DENABLE_INTERNAL_FMT=ON -DENABLE_INTERNAL_CROSSGUID=ON -DENABLE_INTERNAL_RapidJSON=ON -DENABLE_INTERNAL_FFMPEG=ON -DENABLE_INTERNAL_SPDLOG=ON -DAPP_RENDER_SYSTEM=gles  -Wno-dev -DENABLE_INTERNAL_GTEST=ON -DENABLE_INTERNAL_DAV1D=ON 

### Debuglog

The debuglog can be found here:
[CMakeRuleHashes.txt](https://github.com/xbmc/xbmc/files/6028612/CMakeRuleHashes.txt)
[CMakeError.log](https://github.com/xbmc/xbmc/files/6028613/CMakeError.log)
[CMakeOutput.log](https://github.com/xbmc/xbmc/files/6028614/CMakeOutput.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![crash_kodi](https://user-images.githubusercontent.com/3392684/108837949-44567c80-75d3-11eb-8c61-28ce1cbc7323.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ x ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by nephaste** [comment]
new try forcing X11 on another LXC machine ...

![crash2](https://user-images.githubusercontent.com/3392684/108845736-0f035c00-75de-11eb-8ed3-22b40aaf5a8a.jpg)

**Comment by lrusak** [comment]
For whatever reason glFinish doesn't seem to be available. You might want to investigate that in your gl headers.

Also, compiling as root user is usually a bad idea.

**Comment by nephaste** [comment]
Hi thanks 

no choice on Qnap HDStation no user management it is a squashfs ... but i used to compile previous version directly in environment
all is ok with Kodi18 Leia ...  

here Kodi 19 crash in Qnap env and also in fresh clean Ubuntu 18.04 (all up to date)... same error...

I have really no clue how to fix glFinish issue ... since all headers are coming from XBMC PPA repo ... may be can tell me wich dev package headers belong glfinnish

**Comment by lrusak** [comment]
can you compile again using `-DCMAKE_VERBOSE_MAKEFILE=ON` and post the build output (to pastebin)

The headers are likely found and used, however, something may be wrong with the `glFinish` definition.

**Comment by nephaste** [comment]
here is it 

https://pastebin.com/q77yN8U6

**Comment by lrusak** [comment]
Can you also pastebin your CMakeCache.txt from the build folder please? It looks like no GL/ES include dir is present in your build command.

**Comment by nephaste** [comment]
[CMakeCache.txt](https://github.com/xbmc/xbmc/files/6034141/CMakeCache.txt)

Pastebin is buggy for me today.. here is the complete file ..

**Comment by nephaste** [comment]
For info getting problem also when forcing wayland .. will create probably another issue

**Comment by nephaste** [comment]
according CMakeCache, i can see 

//Path to a file.
OPENGLES3_INCLUDE_DIR:PATH=/usr/include
 
//Path to a file.
OPENGLES_INCLUDE_DIR:PATH=/usr/include
 
//Path to a library.
OPENGLES_gl_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libGLESv2.so

but header seems to be in subdirectory  ? am i wrong

![header](https://user-images.githubusercontent.com/3392684/108996169-5cdf9900-769e-11eb-8608-46daafcaf8b4.jpg)

**Comment by lrusak** [comment]
The pastebin is private so I can't view it.

Those includes seem right, but I don't see `-I/usr/include` in the build command.

**Comment by nephaste** [comment]
Dont know why if iam not registered pastebin do not work and if i am registered my pastebin are private even if set on public

cant say why " -I/usr/include " is missing .. i respected documentation ... but because it is in standard location i dont push

-DCMAKE_LIBRARY_PATH=${PREFIX}/lib \
-DCMAKE_INCLUDE_PATH=${PREFIX}/include \

should I ?

[CMakeCache.txt](https://github.com/xbmc/xbmc/files/6037854/CMakeCache.txt)

**Comment by lrusak** [comment]
can you post the output of the following commands?

```
/usr/bin/c++ -xc -E -v - 
```
and
```
/usr/bin/c++ -xc++ -E -v -
```
or even
```
/usr/bin/c++ -v /dev/null -o /dev/null
```
and
```
/usr/bin/c++ -xc++ -v /dev/null -o /dev/null
```

**Comment by nephaste** [comment]
`/usr/bin/c++ -xc -E -v -`
```
Using built-in specs.
COLLECT_GCC=/usr/bin/c++
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.4.0-1ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.4.0 (Ubuntu 8.4.0-1ubuntu1~18.04)
COLLECT_GCC_OPTIONS='-E' '-v' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/8/cc1 -E -quiet -v -imultiarch x86_64-linux-gnu - -mtune=generic -march=x86-64 -fstack-protector-strong -Wformat -Wformat-security
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/8/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
```
`/usr/bin/c++ -xc++ -E -v -`
```
Using built-in specs.
COLLECT_GCC=/usr/bin/c++
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.4.0-1ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.4.0 (Ubuntu 8.4.0-1ubuntu1~18.04)
COLLECT_GCC_OPTIONS='-E' '-v' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/8/cc1plus -E -quiet -v -imultiarch x86_64-linux-gnu -D_GNU_SOURCE - -mtune=generic -march=x86-64 -fstack-protector-strong -Wformat -Wformat-security
ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/8"
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/8
 /usr/include/x86_64-linux-gnu/c++/8
 /usr/include/c++/8/backward
 /usr/lib/gcc/x86_64-linux-gnu/8/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
```

`/usr/bin/c++ -v /dev/null -o /dev/null`
```
Using built-in specs.
COLLECT_GCC=/usr/bin/c++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.4.0-1ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.4.0 (Ubuntu 8.4.0-1ubuntu1~18.04)
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/8/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' '/dev/null' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/8/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/8/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper -plugin-opt=-fresolution=/tmp/ccEsRg6e.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o /dev/null /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/8/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/8 -L/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/8/../../.. /dev/null -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/8/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crtn.o
/dev/null: file not recognized: File truncated
collect2: error: ld returned 1 exit status
```

`/usr/bin/c++ -xc++ -v /dev/null -o /dev/null`
```
Using built-in specs.
COLLECT_GCC=/usr/bin/c++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.4.0-1ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.4.0 (Ubuntu 8.4.0-1ubuntu1~18.04)
COLLECT_GCC_OPTIONS='-v' '-o' '/dev/null' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/8/cc1plus -quiet -v -imultiarch x86_64-linux-gnu -D_GNU_SOURCE /dev/null -quiet -dumpbase null -mtune=generic -march=x86-64 -auxbase null -version -fstack-protector-strong -Wformat -Wformat-security -o /tmp/ccixpSFJ.s
GNU C++14 (Ubuntu 8.4.0-1ubuntu1~18.04) version 8.4.0 (x86_64-linux-gnu)
        compiled by GNU C version 8.4.0, GMP version 6.1.2, MPFR version 4.0.1, MPC version 1.1.0, isl version isl-0.19-GMP

GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/8"
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/8
 /usr/include/x86_64-linux-gnu/c++/8
 /usr/include/c++/8/backward
 /usr/lib/gcc/x86_64-linux-gnu/8/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
GNU C++14 (Ubuntu 8.4.0-1ubuntu1~18.04) version 8.4.0 (x86_64-linux-gnu)
        compiled by GNU C version 8.4.0, GMP version 6.1.2, MPFR version 4.0.1, MPC version 1.1.0, isl version isl-0.19-GMP

GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: 67fba09f596cc8a67df33f8529603bfb
COLLECT_GCC_OPTIONS='-v' '-o' '/dev/null' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 as -v --64 -o /tmp/ccXayjog.o /tmp/ccixpSFJ.s
GNU assembler version 2.30 (x86_64-linux-gnu) using BFD version (GNU Binutils for Ubuntu) 2.30
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/8/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' '/dev/null' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/8/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/8/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper -plugin-opt=-fresolution=/tmp/ccQZRy7M.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o /dev/null /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/8/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/8 -L/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/8/../../.. /tmp/ccXayjog.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/8/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crtn.o
/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

**Comment by lrusak** [comment]
Seem ok. I'm sort of out of ideas.

Last thing I would check is to see if `glFinish` actually exists in the headers and isn't guarded somehow.
```
$ find /usr/include -type f | xargs grep "glFinish (void)"
/usr/include/GL/glcorearb.h:GLAPI void APIENTRY glFinish (void);
/usr/include/GLES2/gl2.h:GL_APICALL void GL_APIENTRY glFinish (void);
/usr/include/GLES/gl.h:GL_API void GL_APIENTRY glFinish (void);
/usr/include/GLES3/gl31.h:GL_APICALL void GL_APIENTRY glFinish (void);
/usr/include/GLES3/gl3.h:GL_APICALL void GL_APIENTRY glFinish (void);
/usr/include/GLES3/gl32.h:GL_APICALL void GL_APIENTRY glFinish (void);
```

**Comment by nephaste** [comment]
this is crazy, i know ^^

`find /usr/include -type f | xargs grep "glFinish (void)"
/usr/include/GLES3/gl31.h:GL_APICALL void GL_APIENTRY glFinish (void);
/usr/include/GLES3/gl32.h:GL_APICALL void GL_APIENTRY glFinish (void);
/usr/include/GLES3/gl3.h:GL_APICALL void GL_APIENTRY glFinish (void);
/usr/include/GLES2/gl2.h:GL_APICALL void GL_APIENTRY glFinish (void);
/usr/include/GL/glcorearb.h:GLAPI void APIENTRY glFinish (void);
/usr/include/GL/glew.h:GLAPI void GLAPIENTRY glFinish (void);
`

**Comment by nephaste** [comment]
New update ... finally make it work
one of the flag used previously makin mess

i just pushed  

`cmake ../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=/opt/Kodi19L -DAPP_RENDER_SYSTEM=gles`

and all was working

thanks a lot for your time... and this crazy issue
