### ISSUE TITLE
Support HTTPS proxy

### ISSUE THREAD

**Issue by lpuglia** [xbmc/xbmc#19266]
Hello, would it be possible to support HTTPS proxy as well beside HTTP and the various SOCK?

HTTPS proxy are a standard nowaday and most proxy providers have closed the HTTP ports. It would be really nice if kodi could support HTTPS proxy as well. 

Just to be more clear of what I am talking about: both Chrome and Firefox support it. Here I found an article about Chromium support (https://www.chromium.org/developers/design-documents/secure-web-proxy). On Firefox you can use ProxyFoxy (https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/) for the very same purpose. 

If you are familiar with `cURL` you can use them in the following way:

```bash
> curl -x https://username:password@proxy:port -L url -v

*   Trying proxy:port...
* TCP_NODELAY set
* Connected to proxy (proxy) port port (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Proxy certificate:
*  subject: CN=*.host
*  start date: Aug 12 14:41:29 2020 GMT
*  expire date: Oct  4 10:49:39 2022 GMT
*  subjectAltName: host "host" matched cert's "*.host"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*  SSL certificate verify ok.
* allocate connect buffer!
* Establish HTTP proxy tunnel to url
> CONNECT url HTTP/1.1
> Host: url
> User-Agent: curl/7.68.0
> Proxy-Connection: Keep-Alive
>
```

HTTPS proxy are often referred as SSL proxy (Firefox terminology) or Secure Web Proxy (OSX terminology).
I have not been able to find any specification but i think it is simply an implementation of a HTTP proxy using SSL.

**Comment by lrusak** [comment]
Feature requests are done via the forum. Thanks.
