### ISSUE TITLE
RPi 4B - Periodic repeated frames, CDVDClock::ErrorAdjust in log

### ISSUE THREAD

**Issue by Halloway66** [xbmc/xbmc#19263]
### Describe the bug
Platform: Raspberry Pi 4B running Kodi 19.0 on Libreelec nightly-20210220-f768c9b 9.80
When playing 1080p, 23.976p material in x264 or x265 format, roughly every 325 seconds a frame is repeated. On tracking or panning shots this is seen as a very brief freeze of the picture. If I play the same video file on a RPi 3B+ running the same version of Kodi/Libreelec, the frame repetition does not happen. This problem has been evident for the past six months ever since I started running Kodi/Libreelec on the RPi 4B. I've been running mainly nightly builds of Libreelec.
In the debug log, coinciding with every freeze instance, are entries such as the following:

```
2021-02-22 11:28:24.680 T:846     DEBUG <general>: CDVDClock::ErrorAdjust - CVideoPlayerAudio::OutputPacket - error:-27109.300645, adjusted:-41708.333333

2021-02-22 11:33:49.771 T:846     DEBUG <general>: CDVDClock::ErrorAdjust - CVideoPlayerAudio::OutputPacket - error:-27064.762239, adjusted:-41708.333333

2021-02-22 11:39:13.912 T:846     DEBUG <general>: CDVDClock::ErrorAdjust - CVideoPlayerAudio::OutputPacket - error:-27030.440774, adjusted:-41708.333333
```

The occurrences are very regular, being roughly every 325 seconds.
I have tried various settings changes in Kodi to no avail. I have also tried re-encoding the audio from AAC to AC3 but again, that has not fixed the problem. 

### To Reproduce
The vast majority of what I watch is 1080p, 23.976p material in x264 or x265 (mainly x264). I have extracted a 15 minute section of a video which can be found here: https://mega.nz/file/l59jXIzD#YFYar62Pg-uAJ5L-iva2TPdVJ7DKXLoOJBhILr6lcxA
The file is 306MB. This file was used to generate the debug log below.

### Debuglog
The debuglog can be found here:

[01_KODI.log](https://github.com/xbmc/xbmc/files/6021957/01_KODI.log)

### Your Environment
Used Operating system:
 - Operating system version/name:
 - Kodi version: 19.0
 - Libreelec: nightly-20210220-f768c9b

My AV setup is RPi 4 -> Yamaha RX-V381 AV amp -> Panasonic TX-P42ST50B

**Comment by popcornmix** [comment]
Any change with AC3 passthrough disabled?

**Comment by Halloway66** [comment]
No, the issue is still evident with AC3 passthrough disabled.

**Comment by popcornmix** [comment]
Can you test this on another platform? e.g. windows/linux. Make sure "adjust display refresh" is enabled and "sync playback to display" is disabled.

**Comment by popcornmix** [comment]
I believe the ErrorAdjust message might be explained by audio and video clocks drifting by 27ms every 325 seconds.
i.e. off by 83ppm. I think that is within typical crystal oscillator tolerances so might be expected with an external sound card (e.g. USB). "sync playback to display" allows this to be corrected through resampling (for non-passthrough) but that isn't currently supported by gbm (but that should be possible).
It may be possible to improve this through clock setup as hdmi audio and video are derived from the same PLL.

**Comment by Halloway66** [comment]
Issue wasn't evident on a Windows 10 machine w/ Kodi 19.0. Output was to AV amp and TV via HDMI.

**Comment by popcornmix** [comment]
Could you try this [test firmware](https://drive.google.com/uc?id=1q61FfEvOLV_M8LNp-iwRhPgDBpRqsCWR&export=download)?
Replace the start.elf/fixup.dat files on sdcard (backing up first is always advisable).

**Comment by Halloway66** [comment]
I've tried the new firmware but it doesn't seem to have made any difference. Several movies watched over the past few days indicated that the issue is still evident. Logfiles are still showing the same errors described above.

**Comment by popcornmix** [comment]
Can you report output of "vcgencmd version"
This clearly resolved the issue for me and @HiassofT 

Note: you'll still see "CDVDClock::ErrorAdjust" at start of playback and each seek.
The periodic ones are gone for me.

**Comment by Halloway66** [comment]
```
LibreELEC (community): nightly-20210220-f768c9b (RPi4.arm)
LibreELEC:~ # vcgencmd version
Feb 16 2021 14:18:29
Copyright (c) 2012 Broadcom
version d6d82cf99bcb3e9a166a34cfde53130957a36bd3 (clean) (release) (start_x)
```

**Comment by Halloway66** [comment]
Uh oh, I think I may have made an error. I copied over the files in firmware108.zip but didn't rename them - presumably I was supposed to?

**Comment by Halloway66** [comment]
After eight hours of watching videos, the issue is no longer apparent and the logfiles corroborate this. Thank you, popcornmix, for your work in fixing this problem.

**Comment by Halloway66** [comment]
Will this fix be incorporated into Kodi at some point?

**Comment by fritsch** [comment]
It's a fix in the firmware of your device. Nothing to do with kodi.

**Comment by Halloway66** [comment]
> It's a fix in the firmware of your device. Nothing to do with kodi.

OK, so will the changes made to start.elf and fixup.dat be incorporated into the released RPi firmware?

**Comment by popcornmix** [comment]
Your test firmware makes the 108MHz clock used by hdmi audio exact at the expense of making the ethernet clock a little off. While we haven't observed any problems with that, it's something we'd prefer not to change in a stable build.
There is a rewrite going on that moves a number of clocks/plls around to handle both these cases but it needs more testing.

**Comment by popcornmix** [comment]
@Halloway66 latest rpi-update firmware should fix this issue.
As described, it's a significant change that juggles a number of clocks around, so updating and confirming issue is still fixed would be useful.
You can just download [start4x.elf](https://github.com/raspberrypi/firmware/blob/master/boot/start4x.elf?raw=true) and [fixup4x.dat](https://github.com/raspberrypi/firmware/blob/master/boot/start4x.elf?raw=true), rename and replace the start.elf/fixup.dat you have.

**Comment by Halloway66** [comment]
Everything in this version seems fine - no visual issues and no CDVDClock::ErrorAdjust entries in the log.
