### ISSUE TITLE
Atmos Passthrough showing up as PCM

### ISSUE THREAD

**Issue by SgtJalau** [xbmc/xbmc#19274]
Hey there,
so I have been experiencing an issue with the new kodi 19 build and my AVR. Any Atmos track won't show up as such on my AVR unless I restart Kodi. It might be that playing a file with no atmos track before could trigger this issue because a clean restart and playing an atmos file direclty after seems to always work. Also pausing the player can cause this issue as well, so Atmos might turn into a PCM stream after resuming or it might stutter. Switching passthrough on and off again afterwards can fix this issue (only if atmos was stuttering). 
Using an Nvidia Shield Pro 19 and it has worked perfectly fine on 18.9 before.

Here is my log where it's not working as intended I(tried multiple times and multiple files):
https://pastebin.com/vj9c8vV9

Here is the log after a clean restart working as intended:
https://pastebin.com/1QUXD7bS

**Comment by fritsch** [comment]
Sorry - two times the log file cut, two time the enumeration skipped. Nothing in your log that helps.

**Comment by DaVukovic** [comment]
I highly this one is old enough to be closed as there's no response from the reporter anymore
