### ISSUE TITLE
Can not connect to network server after upgrade to 19.0

### ISSUE THREAD

**Issue by GWBasic** [xbmc/xbmc#19279]
## Bug report
I Can not connect to a network server after upgrade to 19.0
### Describe the bug
I recently upgraded from Kodi 18.something to 19.0 on my NVidea Shield. (Android TV.) After upgrading, Kodi will no longer connect to a network drive. Connecting to the network drive gives an "Invalid argument" error.

The network drive is:
- Hosted from an apple router
- The connection is via Windows SMB
- I use a username/password

The older version (18.something) connected to the network drive fine.

This is a bug because my media is on a network drive. I am 100% blocked if Kodi can't connect to the drive.

The protocol is SMB. I've specified a server name, shared folder, username, and password.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should connect to the network drive

## Actual Behavior

Kodi doesn't connect to the network drive

## Possible Fix

I suspect something changed in how Kodi 19.0 uses SMB. This caused a regression in handling network drives hosted on Apple routers.

### To Reproduce

1. Get an apple router with a USB drive hooked up
2. Enable network file sharing on the apple router
3. Create a shared folder on the apple router
4. In Kodi, add a network location. The server name is the shared drive name, all caps. Make sure to include the shared folder, username, and password
5. Kodi will not be able to connect to the drive

### Debuglog

See https://paste.kodi.tv/ehepukorid

I'm not sure if there's enough information there to debug the problem, though:

> 2021-02-28 15:02:36.513 T:12030   ERROR <general>: Unable to lookup host: 'MUSHROOM-MEADOW'
2021-02-28 15:02:36.514 T:12030   DEBUG <general>: OpenDir: Using authentication url smb://USER:PASSWORD@MUSHROOM-MEADOW/Monolith/Movies/Music%20Videos
2021-02-28 15:02:36.519 T:12030   ERROR <general>: SMBDirectory->GetDirectory: Unable to open directory : 'smb://USER:PASSWORD@MUSHROOM-MEADOW/Monolith/Movies/Music%20Videos'
                                                   unix_err:'16' error : 'Invalid argument'
2021-02-28 15:02:36.519 T:12030   ERROR <general>: GetDirectory - Error getting smb://MUSHROOM-MEADOW/Monolith/Movies/Music Videos/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I am 100% blocked in Kodi if I can not connect to a network drive.

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please post a debug log or your issue will be considered invalid and will be closed.

**Comment by markoco** [comment]
I have the same issue, Had to reinstall 18.9 now its working again, its a shame they release this with out testing the network shares.

**Comment by markoco** [comment]
Found this on reddit   Oddly enough, when I simply put a single blank space in both the username and password columns after it asked me, it worked just like 18.9. Hope this helps some other people with SMB share problems after the upgrade.

This worked on both my Shield TV and a Sony Android TV.

**Comment by da-anda** [comment]
I have 4 SMB mounts and no issues at all. So unable to reproduce. Could it be a SMB1 vs SMB2 or 3 issue? I have the min SMB version set to 2 IIRC in KODI, since SMB1 is dead and insecure anyways. But if your shares require SMB1 this could probably cause issues? Just a wild guess though.

**Comment by GWBasic** [comment]
@lrusak: Where are the instructions for the debug log? (Might be useful to put a link in the template, hint hint hint.)

@da-anda: My repro requires an Apple router, I don't know much about if it's SMB1, 2, 3, ect.

**Comment by da-anda** [comment]
@GWBasic please go to Settings -> Services -> Samba/SMB and try setting a min version of 2. Then restart KODI and try to access your shares again.

**Comment by AdiSchwartz869** [comment]
There is also a similar issue with ftp network server on my mi box after n upgrade to 19

**Comment by markoco** [comment]
For some strange reason you can not leave the password field blank, you need to hit the space bar once when setting up the SMB share. it will work after that. Try it with the ftp might work the same way.

**Comment by markoco** [comment]
> 
> 
> I have 4 SMB mounts (on my ShieldTV) and no issues at all. So unable to reproduce. Could it be a SMB1 vs SMB2 or 3 issue? I have the min SMB version set to 2 IIRC in KODI, since SMB1 is dead and insecure anyways. But if your shares require SMB1 this could probably cause issues? Just a wild guess though.

The reason you can not reproduce is because your using a password. This is only an issue for people not using a password for there SMB shares.

**Comment by GWBasic** [comment]
@lrusak: See https://paste.kodi.tv/ehepukorid

I'm not sure if there's enough information there to debug the problem, though:

> 2021-02-28 15:02:36.513 T:12030   ERROR <general>: Unable to lookup host: 'MUSHROOM-MEADOW'
2021-02-28 15:02:36.514 T:12030   DEBUG <general>: OpenDir: Using authentication url smb://USER:PASSWORD@MUSHROOM-MEADOW/Monolith/Movies/Music%20Videos
2021-02-28 15:02:36.519 T:12030   ERROR <general>: SMBDirectory->GetDirectory: Unable to open directory : 'smb://USER:PASSWORD@MUSHROOM-MEADOW/Monolith/Movies/Music%20Videos'
                                                   unix_err:'16' error : 'Invalid argument'
2021-02-28 15:02:36.519 T:12030   ERROR <general>: GetDirectory - Error getting smb://MUSHROOM-MEADOW/Monolith/Movies/Music Videos/

@markoco : I'm using a password.

**Comment by GWBasic** [comment]
@da-anda: Thanks for your help. Unfortunately, adjusting the minimum SMB version did not work around the problem.

I'm not an SMB expert. (Although I've professionally shipped a network filesystem and empathize with the need for logs.) I've heard that Apple's SMB implementations are known to be "quirky." Does anyone think I should just cough up the money for a NAS from a different vendor instead of waiting (begging) for a fix?

**Comment by chewitt** [comment]
In historic testing I was never able to get Kodi working with a TimeCapsule via smbclient, even with the "legacy security" opts needed for old routers that run ancient Samba versions. Using LE it was possible to make a persistent systemd drive mount, which mounts the remote share to a local path using kernel SMB capabilities, but I'd assume similar things will be a challenge from Android. TL/DR: Apple SMB != Samba SMB or MS SMB. For reference see: https://forum.libreelec.tv/thread/10490-smb-with-libreelec-8-2-and-timecapsule-not-working/?postID=102211#post102211.

**Comment by GWBasic** [comment]
Ok, I spent an ungodly amount of money on a NAS, so now I'm no longer blocked.

I'll try to keep my old setup around if anyone wants me to verify a fix.

**Comment by da-anda** [comment]
see it as investment on added security to your home network. If you happen to use Windows machines, make sure to uninstall SMB1 support now (can be done in the old additional Windows features dialog) or your PC is still vulnerable

**Comment by CFD2** [comment]
I also have a Time Capsule and SMB shares became inaccessible since the update. I have a password set but that doesn't really help.

**Comment by lrusak** [comment]
> I also have a Time Capsule and SMB shares became inaccessible since the update. I have a password set but that doesn't really help. 

Time capsule only support SMBv1 IIRC so you have to set your Kodi settings to max smbv1 support.

https://kodi.wiki/view/Settings/Services/SMB_Client

Please use the Kodi forum for further support.

**Comment by rafi-d** [comment]
Has this bug of FORCING a password been fixed yet? Even with a password, I am not able to use smb unless I limit both min/max to smbv1 :(

**Comment by GWBasic** [comment]
@rafi-d : Wrong bug.

(Note that, in the steps to reproduce, a password is required.)
