### ISSUE TITLE
Defective CUE Sheet Playback after upgrade to 19

### ISSUE THREAD

**Issue by MatjazCr** [xbmc/xbmc#19277]
### Describe the bug

CUE sheets in the music library don't work - only the first track of the album is displayed, others are missing

## Expected Behavior

See all the tracks in the album contained in the CUE sheet, like I did in Kodi 18.8 and earlier versions

## Actual Behavior

Only the first track is displayed in Kodi. It can be played normally, but other tracks can't be accessed.

## Possible Fix

Wrong CUE sheet parsing, something goes wrong after the first track

### To Reproduce

1. Go to Music, Albums and select any album for which there is only one FLAC or APE file in your library with a CUE sheet in the same folder specifying the individual tracks
2. Play this album
3. Only the first track appears in the track list

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/vikicukatu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Just1stTrackofCUESheet](https://user-images.githubusercontent.com/79602307/109387562-623d1d80-7902-11eb-8613-64a6ba1c14f5.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Here is a sample CUE sheet that didn't work for me (see the above screenshot)

REM GENRE Classical
REM DATE 2003
REM DISCID 5A10F917
REM COMMENT "ExactAudioCopy v1.3"
PERFORMER "Händel"
SONGWRITER "Georg Friedrich Händel"
REM COMPOSER "Georg Friedrich Händel"
TITLE "Six Organ Concertos Op. 4"
FILE "Six Organ Concertos Op. 4.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Concerto no. 4 in F major (HWV 292) - 1. Allegro"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Concerto no. 4 in F major (HWV 292) - 2. Andante"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    FLAGS DCP
    INDEX 01 03:59:08
  TRACK 03 AUDIO
    TITLE "Concerto no. 4 in F major (HWV 292) - 3. Adagio"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 09:27:58
  TRACK 04 AUDIO
    TITLE "Concerto no. 4 in F major (HWV 292) - 4. Allegro"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 10:48:56
  TRACK 05 AUDIO
    TITLE "Concerto no. 2 in B flat major (HWV 290) - 1. Sinfonia (A tempo ordinario e staccato - Adagio)"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 14:29:71
  TRACK 06 AUDIO
    TITLE "Concerto no. 2 in B flat major (HWV 290) - 2. Allegro"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 15:25:51
  TRACK 07 AUDIO
    TITLE "Concerto no. 2 in B flat major (HWV 290) - 3. Adagio e staccato"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    FLAGS DCP
    INDEX 01 19:57:07
  TRACK 08 AUDIO
    TITLE "Concerto no. 2 in B flat major (HWV 290) - 4. Allegro ma non presto"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 20:41:27
  TRACK 09 AUDIO
    TITLE "Concerto no. 3 in G minor (HWV 291) - 1. Adagio"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 24:40:08
  TRACK 10 AUDIO
    TITLE "Concerto no. 3 in G minor (HWV 291) - 2. Allegro"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 28:03:14
  TRACK 11 AUDIO
    TITLE "Concerto no. 3 in G minor (HWV 291) - 3. Adagio"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 32:10:09
  TRACK 12 AUDIO
    TITLE "Concerto no. 3 in G minor (HWV 291) - 4. Gavotte (Allegro)"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 32:58:00
  TRACK 13 AUDIO
    TITLE "Concerto no. 6 in B flat major (HWV 294) - 1. Andante allegro"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 35:20:03
  TRACK 14 AUDIO
    TITLE "Concerto no. 6 in B flat major (HWV 294) - 2. Larghetto - Adagio"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 41:19:49
  TRACK 15 AUDIO
    TITLE "Concerto no. 6 in B flat major (HWV 294) - 3. Allegro moderato"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 45:07:48
  TRACK 16 AUDIO
    TITLE "Concerto no. 5 in F major (HWV 293) - 1. Larghetto"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 47:45:16
  TRACK 17 AUDIO
    TITLE "Concerto no. 5 in F major (HWV 293) - 2. Allegro"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 49:46:40
  TRACK 18 AUDIO
    TITLE "Concerto no. 5 in F major (HWV 293) - 3. Alla Siciliana"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 52:05:42
  TRACK 19 AUDIO
    TITLE "Concerto no. 5 in F major (HWV 293) - 4. Presto"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 53:45:37
  TRACK 20 AUDIO
    TITLE "Concerto no. 1 in G minor (HWV 289) - 1. Larghetto e staccato - Adagio"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 56:01:29
  TRACK 21 AUDIO
    TITLE "Concerto no. 1 in G minor (HWV 289) - 2. Allegro"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 61:51:52
  TRACK 22 AUDIO
    TITLE "Concerto no. 1 in G minor (HWV 289) - 3. Adagio"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 67:22:05
  TRACK 23 AUDIO
    TITLE "Concerto no. 1 in G minor (HWV 289) - 4. Andante"
    PERFORMER "Matthew Halls / Sonnerie / Monica Huggett"
    REM COMPOSER "Georg Friedrich Händel"
    INDEX 01 68:46:36

Apart from this one, I have tried it with at least 5 other CUE sheets from different sources - they all worked in Kodi 18.8, but now, after the upgrade, I can only see their first track

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: 7
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MatjazCr** [comment]
I did some further experimenting. If I delete an album, do Options => Update Library and then copy album back and update the library again, all tracks appear. But they lack the play count / last played history.
In other words: this was a problem of the upgrade from Kodi 18.8 to 19.0. All the newly added albums seem to work OK.
Is there a way to re-read the whole music library (I would hate to manually delete and copy back all the CUE sheet albums in my library). It would also be nice if the play count could be somehow preserved.

**Comment by MatjazCr** [comment]
I have repeated the procedure and found out exactly where the problem is. The old Kodi 18.8 music database gets migrated OK. All the tracks are there in all the CUE sheet albums. The problem appears after I allow a rescan as on the screenshot below. After this rescanning only the first files are visible in these albums.

![LibraryUpdate](https://user-images.githubusercontent.com/79602307/110022944-d6c1f300-7d2c-11eb-943a-682393a167ce.jpg)

**Comment by DaveTBlake** [comment]
Yes there is a problem with the forced rescan of music with cuesheets. There is a longstanding but undetected/unreported flaw whereby rescanning such files lost song playback history data, this has been exasperated by changes in v19 causing all but the first track to be missed from the library. I am working on a fix. 

Meanwhile as a workaround until v19.1, to keep song playback history (playcount, lastplayed and user rating) you would need to revert to using v18 and the old MyMusic72.db file and export the song history. Then with v19 you want to start with an empty library, so drop the music source, fully cleaning the library from settings>media>library, and then adding the music source and scanning anew. Finally import the song playback history into the newly scanned library for v19.

This problem only effects music from cuesheets where there is more than one song associated witha music file.

**Comment by DaveTBlake** [comment]
Related PR (against master which is v20) https://github.com/xbmc/xbmc/pull/19392

**Comment by arigit** [comment]
Ready to test this fix as soon as there is a test build available, if that's possible. Test environment: ubuntu LTS/20.04.
I can test this with a fairly large Music72 DB upgrade (around 35K songs / 3.5K albums, mostly single flac files with cuesheets)

**Comment by DaveTBlake** [comment]
Fixed for v20 by  #19392 and backported for Matrix v19.1 by #19394
