### ISSUE TITLE
Can only add one Video Source to Video Media

### ISSUE THREAD

**Issue by damonbrodie** [xbmc/xbmc#19288]
### Describe the bug
Here is a clear and concise description of what the problem is:

Under System > Media > Library > Videos
I am added a video source by adding a new Network location of type SMB.  The first time worked great.

Now I want to add a second Video Source.  The context menu doesn't have "Add a new Media Source" option.   There isn't a + sign or any other obvious way to add a second data source.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

In the Video Sources Screen, or in the Context Menu there should be a "Add Video Source" option so I can have multiple Video Sources (Say one for TV shows and one for Movies)

## Actual Behavior

See Above

## Possible Fix

None found yet.

### To Reproduce

1.  Install Kodi 19 on Android (Shield)
2. If you already have Video Sources - delete all of them
3. Add a video source
4. Try and add a second video source

### Debuglog

The debuglog can be found here:
I don't know how to obtain this from my Shield.

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://imgur.com/a/ZTDJFiv

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.0
![Kodi1](https://user-images.githubusercontent.com/274743/109213929-32b1d800-777f-11eb-90b6-69a7f631d482.jpg)
![Kodi2](https://user-images.githubusercontent.com/274743/109213935-33e30500-777f-11eb-9b3d-1663e82d4476.jpg)
![kodi3](https://user-images.githubusercontent.com/274743/109213938-347b9b80-777f-11eb-9a56-1065a561b69f.jpg)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HitcherUK** [comment]
Have you disabled `Show "Add source" buttons` under General?

**Comment by damonbrodie** [comment]
Yep!  Closing
