### ISSUE TITLE
Swipe scrolling on android does not update the letter index until it stops scrolling.

### ISSUE THREAD

**Issue by cerealbox** [xbmc/xbmc#19285]
### Describe the bug

when swipe scrolling a list of titles, the small index letter at the top center of the screen (but could be anywhere with a different theme) that indicates the alphabetical location you are at does not update continuously - it only updates when the scrolling stops.
if you scroll using the scrollbar on the right hand side the index letter updates properly.

platform: android
device: samsung galaxy tab s5e
kodi: v19 matrix

## Expected Behavior

on previous kodi v18 when you swipe scrolled the index letter would update continuously as the titles scrolled.

## Actual Behavior

on kodi v19 the index letter does not update continuously when swipe scrolling.

### To Reproduce

1. tap movies or shows or whatever.
2. swipe up.
3. watch the index letter at the top not change until the scrolling stops.

### Your Environment
Used Operating system:

 - [X] Android

 - Operating system version/name:
 - Kodi version: v19 matrix

**Comment by JayDee696969** [comment]
Looking forward to a fix, makes touchscreen devices pretty useless with Kodi.

**Comment by cerealbox** [comment]
kodi on android auto-updated to version 19.3 and it looks like this issue has been fixed :)
