### ISSUE TITLE
Kodi on Android - Samsung S5e Tab does not show HDR videos properly

### ISSUE THREAD

**Issue by GitJamz** [xbmc/xbmc#19287]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi can not play HDR content on Samsung S5e tablet.
This tablet is a bit special as it has HDR support hardware wise but samsung has tried to ruin the software support somewhat. So there needs to be workarounds..
If you turn of Hardware accelleration in kodi it shows HDR content properly but the stutter is of course severe.
MPV player works with HDR acceleration though and Ive heard reports of maybe VLC as well. Ive only tested MPV and can confirm it does work.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

HDR to be played with the default settings of hardware acceleration ON.

## Actual Behavior

HDR is not activated and colors are washed out with Hardware Accel on.

## Possible Fix

Turn Hardware acceleration off - but then there is extreme stutter.
Possible fix would be to check how MPV player solved it and just use that "fix"? SOrry Im no developer :D

### To Reproduce

1. Use Samsung S5e pad
2. Play a real 4k HDR movie file with Kodi and hardware accelleration ON = No HDR
3. Play a real 4k HDR movie file with MPV player from F-droid + hardware acceleration ON = Perfect HDR

### Debuglog

Sorry I dont know how to get a debug log for kodi.. Im a bit of a newbie on this as you may notice from the bug report.
If it is needed please give me instructions and I will fetch it!

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi 18.9 from F-droid

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Closing as stalled, android also has no maintainer at the moment. Please reopen if still happening in current nightlies.
