### ISSUE TITLE
Db Migration failled - SQL: Can't determine list of routines to drop (Will not set content type on sources)

### ISSUE THREAD

**Issue by kmickunas** [xbmc/xbmc#19289]
### Describe the bug
Here is a clear and concise description of what the problem is:
The automatic upgrade occurred on Shield TV and my sources no longer show up under TV Shows, Movies, etc.  The sources are in the files section, I can edit them, I can set the content, but it doesn't take.  I have added a new source, I set the content, and while it acted ok, it still didn't take the content. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
It should have imported all the content settings correctly.  It should take the settings when I set them.

## Actual Behavior
On Shield TV device it was set to automatic upgrade.  When starting it migrated the database.  After migrating it shows no content under Movies or TV Shows.  I went into the Files section, I saw my sources that are defined in sources.xml. I can browse into them there as expected.  However I can not set the content type on those sources.  It shows none, I set it to TV Shows or Movies as expected, it'll clean the database, refresh the database, all that stuff, and then nothing shows up.  I select the Set Content option again, and it's set to none.  It will not take.  I've dropped the database multiple times, Force Stopped the app, cleared the cache, all that, and it still doesn't work. 

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/xusexegupu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ X] Android nvidia Shield TV
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Your log is not a debuglog. It simply shows that there's an error while updating the MySQL-databases, but it doesn't show why. 

Please enable debug logging and probably also enable "component specific logging" and inside that, select the "verbose logging for the database component"

**Comment by DaveTBlake** [comment]
The log is sufficient to shows failure to migrate your databases,  with 'SQL: Can't determine list of routines to drop' error.  Kodi can not function without databases.

This problem is with MariaDB, as discussed on the forum https://forum.kodi.tv/showthread.php?tid=358922&pid=2994156#pid2994156
https://forum.kodi.tv/showthread.php?tid=358578&pid=3016444#pid3016444
https://forum.kodi.tv/showthread.php?tid=356405

Try 'mysql_upgrade -uroot -p --force' on the server

**Comment by kmickunas** [comment]
It took me a while to figure it out, it turns out it's very important that the local copy of MariaDB that is running the command needs to be on the same minor version.  Being on 10.3 and the server on 10.4 wasn't good enough.  Anyways, once I fixed that then it resolved the problems.  Thanks.
