### ISSUE TITLE
[Estuary] PVR Radio banner tile not centered when only one is present

### ISSUE THREAD

**Issue by djp952** [xbmc/xbmc#19281]
### Describe the bug
Here is a clear and concise description of what the problem is:

I noted a cosmetic issue with the Estuary skin in the PVR Radio section.  If one of the banner tiles at the top, like 'Currently Recording' or 'Next Recording'  is present, it will not be centered like it would be for TV.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expected it to be consistent with TV.  Having one banner right-justified looked odd.

## Actual Behavior

When one banner is present, it's not centered

## Possible Fix

N/A

### To Reproduce

1. Install a PVR addon with Radio timer capabilities.
2. Note alignment when only one banner is present.

### Debuglog
The debuglog can be found here:

https://paste.kodi.tv/obeyucaqed.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Radio:
![radio-banner](https://user-images.githubusercontent.com/706055/109099703-7fe76880-76f1-11eb-9c64-7e064869a37a.png)

TV:
![tv-banner](https://user-images.githubusercontent.com/706055/109099694-7cec7800-76f1-11eb-9f13-b5ead98c71da.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Just want to reiterate that this is pretty trivial and completely cosmetic in nature.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: (19.0 (19.0.0) Git:20210218-f44fdfbf67). Platform: Windows NT x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
I will take a look.
