### ISSUE TITLE
Internet Access Settings Menu Crash

### ISSUE THREAD

**Issue by MrDowntempo** [xbmc/xbmc#19280]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi crashes when selecting Internet Access in the Settings/System menu. If Internet Access is highlighted at all, even if by just scrolling past it, Kodi crashes.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would expect to be able to navigate to and past Internet Access without Kodi crashing

## Actual Behavior

I navigated to Settings to change and configure some settings after updating to 19.0. But have noticed that Kodi crashes whenever Internet Access is selected. I can avoid this and reach every other item in the Settings/System menu by navigating up to avoid ever hovering over Internet Access

### To Reproduce

1. Go to Settings
2. Go to System
3. Navigate to Internet Access

### Debuglog

The debuglog can be found here:

https://pastebin.com/j1TSfZHY
### Screenshots
Here are some links or screenshots to help explain the problem:

No visible artifacts. Just crashes to desktop

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Have had a couple team members try to repro this, but no one can.

Can you possibly try a portable install and see if it still happens?
https://kodi.wiki/view/Portable_mode

**Comment by DaveTBlake** [comment]
Also unable to reproduce.  Noting the audio reset at the end of the log I wonder if the crash is audio related. How is audio set on the device, and does playback work or is changing internet setting the first thing you attempt?
