### ISSUE TITLE
Kodi v.19 build target is wrong

### ISSUE THREAD

**Issue by kekukui** [xbmc/xbmc#19292]
**Web site says:**

An Intel Mac running OS X **10.8** or higher is required.
https://kodi.tv/download

**At launch, Kodi.app says:**

“This application requires OS X **10.13** or later”

**Comment by kambala-decapitator** [comment]
Thanks, it's website error. For pre-v10.13 use Kodi v18 or earlier.

**Comment by kambala-decapitator** [comment]
website is fixed now
