### ISSUE TITLE
kodi 19 movies posters not showing 

### ISSUE THREAD

**Issue by mrdragon110** [xbmc/xbmc#19305]
### Describe the bug
Here is a clear and concise description of what the problem is:

hello 
i have kodi 19 and when i want to add movies from my hard drive to kodi and scaning whit wdb 
it shows the movie info but not showing posters ...
I also have this problem with addone titles, they do not load properly
and i have problem whit some movies ...they are not recognizing i dont know how to add them in kodi  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

i jast want to see movie posters and figure out how to add movie that was not added 

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [@ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Not a Kodi bug, but an issue with your setup.

Please ask your question on the forum and also provide a debuglog which captures you scraping some of these problem movies without posters.

Also check your artwork settings in Settings>Media>Video and scroll to Artwork

Issue closed.
