### ISSUE TITLE
Kodi 19 is incredibly laggy on Windows 10

### ISSUE THREAD

**Issue by Faheetah** [xbmc/xbmc#19308]
### Describe the bug

I have a pretty standard desktop PC with the latest version of Windows 10 pro. Using Kodi from the app store. The app store updated Kodi to version 19 two days ago. The UI itself is incredibly laggy, think trying to use Kodi over RDP, except videos play smoothly with no hiccups. Using any Kodi interface anywhere, including while playing a show (say to pause it) is also laggy. Version 18.9 was fine, and I actually did downgrade to 18.9 and reimported my shows. I also tried installing version 19 directly (instead of the app store) and it was laggy as well.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I mean, an actual responsive user experience. Clicking menu items feels snappy.

## Actual Behavior

UI is borderline unusable, Kodi takes about a second to process any actions, causing menu navigation to overshoot fields. Both the mouse/navigation is laggy as well as the UI itself. For example, move mouse over to the power menu, it takes a second for the mouse to move over. Click, takes another second. Open, the animation for opening the power menu takes about a second, etc. It's not just the direct responsiveness of actions. In debug mode, it shows 4FPS, which sounds about right, it feels like playing a game with a heavily underpowered GPU.

## Possible Fix

I wish I had a whole lot more context to provide, and I am happy to do further troubleshooting if desired, however I don't have the time or experience to dig in on a technical level. I still have the app store version installed, I just installed 18.9 directly from a mirror along side it.

Since a previous version is working, the problem is mitigated and not directly impacting me other than not being able to upgrade, so this is more of a FYI for yall, I plan to try again once a new version is released.

### To Reproduce

I doubt anyone would be able to reproduce it otherwise there would be a barrage of bug reports already, I would imagine that the issue is some obscure bug that I happened to be caught up in. Like I said, I am open to try and provide further troubleshooting, Kodi is a great program and I'm more than happy to help.

The windows store version has been installed for a while, but for testing I went to the main site, downloaded the 64 bit installer, installed it, and out of the box it was laggy.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ozajakukuh.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Not going to be applicable

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I think I was pretty thorough in the description

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [X] Windows UWP

 - Operating system version/name: Windows 10 version 2004 build 19041.804
 - Kodi version: 19 (latest from site as of posting this), no plugins, just plain Kodi install

More context: AMD FX-8320E, 16GB DDR3, using the integrated GPU on the AMD chip, running off of a Samsung SSD as well

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Not a Kodi bug, but an issue with your setup.

Please ask your question on the forum. 

I can already see entries in your log that raise questions about your setup...

Why are you set to 3240x2160 32Bit at 32Hz
What is the Remote Audio you are using?

Don't answer here, but create a post on the forum and answer there.
