### ISSUE TITLE
Kodi 19.0.0 for Android displays hexadecimal volume names (disk drives)

### ISSUE THREAD

**Issue by phade-uk** [xbmc/xbmc#19307]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hi everyone,

I have found a bug in Kodi 19 where the disk drive volume names are displayed as hexadecimal characters (twice each) instead of the actual volume names (via File Manager, Videos - Files, etc).

Previous versions of Kodi for Android did not have this bug.

Thank you everyone in advance.

Previous versions of Kodi for Android displayed disk volume names normally where as Kodi 19 displays them as hexadecimal characters (twice each).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by juru34** [comment]
I have the same problem. (Android TV Philips, or Mibox S)

**Comment by StevenP94** [comment]
I have the same problem (MINIX NEO U9-H)

**Comment by bansheeat** [comment]
I have the same problem on my Beelink GT1 Mini Box with Android 8.1 but not on my Orbsmart S84 with Android 7.1

**Comment by Dan69320** [comment]
Hi
I have the same on ANDROID TV SONY
Thanks

**Comment by Dan69320** [comment]
Does it mean that the issue is solved ??
Right now it's the same on my TV...
Do we have to wait an update ???
Thanks a lot for your help
BR
