### ISSUE TITLE
Kodi 19 PeerTube HLS stream has no sound 

### ISSUE THREAD

**Issue by cmF3** [xbmc/xbmc#19303]
### Describe the bug
Here is a clear and concise description of what the problem is:
I have written a small addon for receiving [PeerTube HLS stream](https://docs.joinpeertube.org/admin-configuration).
Video works well however, no sound is playing. The Audio codec is displayed as [unknown] AAC channels 0.

An example stream m3u8 can be found here:
https://framatube.org/videos/watch/9c9de5e8-0a1e-484a-b099-e80766180a6d

The relevant code from the plugin is here:
```python
        url="https://framatube.org/static/streaming-playlists/hls/9c9de5e8-0a1e-484a-b099-e80766180a6d/master.m3u8"
        manifest="hls"
        item = xbmcgui.ListItem(path=url)
        item.setProperty("inputstream", "inputstream.adaptive")
        item.setProperty("inputstream.adaptive.manifest_type", manifest)
        xbmcplugin.setResolvedUrl(self.handle, True, listitem=item)
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The HLS video stream plays fine and audio can be heard

## Actual Behavior

The HLS video stream plays fine but audio cannot be heard

## Possible Fix

Unknown

### To Reproduce

1. Write an addon that receives HLS streams from PeerTube
2. Hit play
3. Do not hear anything

### Debuglog

The debuglog can be found here:
https://paste.ubuntu.com/p/G2z3NJTQVT/

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: All Linux Distributions
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by matthuisman** [comment]
Probably an issue in Inputstream Adaptive.
Have you tried playing without IA? (Just via ffmpeg)

**Comment by cmF3** [comment]
Yes, video and audio play fine without IA, but performance when seeking is in the gutter and playback frequently stops.

**Comment by matthuisman** [comment]
you'd want to close this issue then and open an issue below:
https://github.com/xbmc/inputstream.adaptive/issues

**Comment by cmF3** [comment]
Done
