### ISSUE TITLE
Streaming failures and unresponsive kodi

### ISSUE THREAD

**Issue by mrawji** [xbmc/xbmc#19309]
### Describe the bug
Here is a clear and concise description of what the problem is:

With an HLS stream, Kodi on v19 will either refuse to play the stream (if adaptive streaming is turned off), and will sometimes become completely unresponsive (need to kill -9) with the "InputStream Adaptive" plugin turned on.

This works "as expected" in Leia without Adaptive Streaming. With Adaptive Streaming, behavior seems to be the same, but need to my kodi instance back and continue tests. If you need logs from v18, LMK.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Streaming should be successful with and without the Adaptive Streaming plugin and I should be able to seek in the stream.

## Actual Behavior

Without the AdaptiveStreaming plugin:
- Kodi 19 throws an error and says there was an error playing the file.
- Kodi 18 Works fine.

With Adaptive Streaming Turned on:
- Kodi v18 and v19 behave the same
- Seeking through part of the stream is successful.
- Seeking (or playing) past a certain point makes kodi unresponsive.

## Possible Fix

Without Adaptive Streaming:
- Possibly rollback or forward to a new ffmpeg library

With the Adaptive Streaming plugin:
- Unknown.

### To Reproduce

1. Use the NHL.TV addon
    1.  PM me if you need a test subscription
2. Navigate to 2021-02-25
2. Play the Montreal at Winnipeg game (full game, French)
    1. It fails on other games, but I've been testing with this one, trying to keep things consistent.
3. Seek to 2:00:00
4. [[Kodi hangs]]

### Debuglog

The debuglog can be found here:

On Kodi 19:
- Without Adaptive Streaming:  https://paste.kodi.tv/kumovinuda.kodi
    - Errors are on Line 1162, Timestamp (2021-02-28 16:32:21.285)
    - This same file "just works" on Kodi 18 with the same game and the same plugin version.

- With Adaptive Streaming Enabled:
    - Successful Stream + Seek: https://paste.kodi.tv/valoyuyuhu.kodi
        - Same instructions, Seeked to 1:30:00
    - Unsuccessful Seek and hang: https://paste.kodi.tv/uwunimohug.kodi
        - I don't see a successful "demuxer seek to: 7200000.000000, success" message, just the "seek to"

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I can reproduce in Linux (Ubuntu 20.10) and Android (ARM 32 bit build) on Firesticks.

I can confirm that it's (likely not the addon). I ran the same addon version code (by changing the required python version on the addon.xml) on v18 and v19.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 
 ```
 mrawji@mrawji-tbi7  ~  cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Ubuntu 20.10"
 mrawji@mrawji-tbi7  ~  uname -a
Linux mrawji-tbi7 5.8.0-44-generic #50-Ubuntu SMP Tue Feb 9 06:29:41 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 mrawji@mrawji-tbi7  ~  
```
 - Kodi version:
    - Build 19.0 (19.0.0)
    - Git: 20210219-f44fdfbf67

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by wsnipex** [comment]
are you sure, it's not the addon?

> 2021-02-28 16:32:21.285 T:6799    DEBUG <general>: ffmpeg[0x56423838d4d0X]: [https] HTTP error 400 Bad Request
> 2021-02-28 16:32:21.286 T:6799    ERROR <general>: ffmpeg[0x56423838d4d0X]: [hls] Unable to open key file https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/2017669031/kid/70363942
> 2021-02-28 16:32:21.286 T:6799     INFO <general>: ffmpeg[0x56423838d4d0X]: [hls] Opening 'crypto+https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1614645139~acl=/*~id=nhlGatewayId:8818388~data=2017669031~hmac=bc72f0f9cb889b2f272e1481dd2c81995717915fc939db2a06778e2c0d568caf/f5bd3b0717c560d5c73c024c90415d16/ls03/nhl/2021/02/26/NHL_GAME_VIDEO_MTLWPG_M2_FRENCH_20210226_1613264125761/800K/01/00/29.ts' for reading
> 2021-02-28 16:32:21.934 T:6799     INFO <general>: ffmpeg[0x56423838d4d0X]: [hls] Opening 'crypto+https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1614645139~acl=/*~id=nhlGatewayId:8818388~data=2017669031~hmac=bc72f0f9cb889b2f272e1481dd2c81995717915fc939db2a06778e2c0d568caf/f5bd3b0717c560d5c73c024c90415d16/ls03/nhl/2021/02/26/NHL_GAME_VIDEO_MTLWPG_M2_FRENCH_20210226_1613264125761/800K/01/00/34.ts' for reading
> 2021-02-28 16:32:22.078 T:6799    ERROR <general>: ffmpeg[0x56423838d4d0X]: [hls] Error when loading first segment 'https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1614645139~acl=/*~id=nhlGatewayId:8818388~data=2017669031~hmac=bc72f0f9cb889b2f272e1481dd2c81995717915fc939db2a06778e2c0d568caf/f5bd3b0717c560d5c73c024c90415d16/ls03/nhl/2021/02/26/NHL_GAME_VIDEO_MTLWPG_M2_FRENCH_20210226_1613264125761/800K/01/00/29.ts'
> 2021-02-28 16:32:22.083 T:6799    DEBUG <general>: Error, could not open file (2) https://hlslive-akc.med2.med.nhl.com/hdnts=exp=1614645139~acl=/*~id=nhlGatewayId:8818388~data=2017669031~hmac=bc72f0f9cb889b2f272e1481dd2c81995717915fc939db2a06778e2c0d568caf/f5bd3b0717c560d5c73c024c90415d16/ls03/nhl/2021/02/26/NHL_GAME_VIDEO_MTLWPG_M2_FRENCH_20210226_1613264125761/master_tablet60.m3u8
> 2021-02-28 16:32:22.083 T:6799    ERROR <general>: OpenDemuxStream - Error creating demuxer

**Comment by mrawji** [comment]
Thanks for checking @wsnipex .

I am "as sure as I can be". I spun up a new VM on Ubuntu 20.04, and using the plugin from source so I am using exactly the same code on v18.9 and v19, it works on Kodi 18. The only change is the "xbmc.python" version in the addon.xml to move between Kodi 18 and and Kodi 19.

```
diff --git a/addon.xml b/addon.xml
index 82f6961..a4914d0 100644
--- a/addon.xml
+++ b/addon.xml
@@ -1,7 +1,7 @@
 <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
 <addon id="plugin.video.nhlgcl" name="NHL TV™" version="2021.2.11" provider-name="eracknaphobia">
     <requires>
-        <import addon="xbmc.python" version="3.0.0"/>
+        <import addon="xbmc.python" version="2.26.0"/>
         <import addon="script.module.pytz" />
         <import addon="script.module.beautifulsoup4" />
         <import addon="script.module.pil" />
```

FFMEG on Kodi 18 (successful):
https://paste.kodi.tv/rixapeteri.kodi

AdaptiveStream on Kodi 18 (not successful)
https://paste.kodi.tv/nikinoviye.kodi

Thanks!
Marc

**Comment by enen92** [comment]
Closing as v19 and v18 are no longer supported. Please check if this is still an issue in current nighties.
