### ISSUE TITLE
Archive Support 2.0.0 by spiff crashes Kodi 19.0 (19.0 RC1 worked okay)

### ISSUE THREAD

**Issue by flammobammo** [xbmc/xbmc#19316]
Firstly, I apologise this is my first bug report and realised half way through I've not done it great. I can re-do in the correct format with headings if required, but all the necessary info is below.

I had been using Kodi 19.0 RC1 just fine, but not sure whether with 19.0 RC1 or prior, whether the Archive Support add-on was ever installed before.

I upgraded to Kodi 19.0. It worked fine for a video, but possibly just before my issue started happening, Archive Support addon by Spiff must have updated (based on the install date) and I can say with confidence, by trial and error, and process of eliminations, my issue is only occurring when Archive Support 2.0.0 is enabled. When it's enabled, if I try to play a TV show (MKV file), Kodi freezes, and then crashes (disappears). Windows 10 x64.  Open Kodi, disabled this particular add-on and only this add-on, and then it works fine. Enabled the add-on, same crashing issue happens. I've also tried reinstalling Kodi 19.0 again just in case, but no luck. (Not from fresh, just running the Windows installer again).

I've never had an issue with whatever version of this add-on that I've used previously, but all I can say is that Archive Support 2.0.0 and Kodi 19.0 release are not compatible on my platform/installation of Kodi.

Log with and without add-on, in particular line 672:
2021-03-02 09:00:14.346 T:9808     INFO <general>: ADDON: Dll Destroyed - Archive support
[https://paste.kodi.tv/kicequfawo.kodi](https://paste.kodi.tv/kicequfawo.kodi)

Thanks in advance, hope this helps someone!

**Comment by DaVukovic** [comment]
I think your report should be placed here: https://github.com/xbmc/vfs.libarchive/issues

I fear It won't get too much attention in here

**Comment by flammobammo** [comment]
Thanks DaVukovic, done. And thanks for being polite about it :)
