### ISSUE TITLE
Channel numbering with two (or more) PVR clients

### ISSUE THREAD

**Issue by BartZorn** [xbmc/xbmc#19312]
### Describe the bug
Here is a clear and concise description of what the problem is:

I am using the DVBlink/TVmosaic PVR add-on, and I am considering to switch to using the Argus PVR add-on.
I have two DVB-S2 tuners and one DVB-T tuner. I have removed the DVB-T tuner from TVmosaic and configured it on Argus.
I have configured the channel numbers so that no conflict exists between the two sources.
Next I enabled both PVR clients in Kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

What I want to happen is that all channels are listed with the same (non-consecutive) channel numbers as when I was only using TVmosaic, with all tuners configured.

## Actual Behavior

Instead, the channels are numbered consecutive, starting at 1. The channel order is preserved from the back-ends.
This happens regardless of the setting "Use Channel numbers from Backend(s)"
As soon as I disable one of the PVR clients, the channel numbering reverts to the way set by "Use Channel numbers from Backend(s)", in my case Yes.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
https://drive.google.com/drive/folders/11UlZ_sSppDtRWJTfFF4j3-6MWfp744fd?usp=sharing

### Screenshots 
Here are some links or screenshots to help explain the problem:

In addition some screen shots in this same folder:
Settings.png - the settings which apply to all the following
Only TVmosaic.png - Only the TVmosaic client is enabled. Channel numbers conform the setting in TVmosaic server.
OnlyArgus.png - Only Argus is enabled. During my configuration of Argus the channel numbers somehow got lost, but I don't think that makes a difference for this report. I will redo the configuration and add the result later.
TwoClients.png - Both clients enabled. Channels are consecutive numbered. everything up to 60 comes from TVmosaic, the rest from Argus.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Windows 10 Pro version 20H2, all updates installed
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by BartZorn** [comment]
I have now reconfigured the channel numbers in Argus. Except that the correct numbers now appear in Kodi, there is no difference in the behavior described above.

**Comment by phunkyfish** [comment]
It won't work in Kodi 18 as backend channel are only permitted if using a single backend. If you want this to work you must Kodi 19 where that limitation was removed.

When using 19 there will be an extra expert setting as in this screenshot which you must enable before it will work.

<img width="2102" alt="Screenshot 2021-03-01 at 22 57 33" src="https://user-images.githubusercontent.com/4601187/109570331-c538db00-7ae1-11eb-8bcc-47c0b1dd262d.png">

**Comment by BartZorn** [comment]
Wow, that is a lucky coincidence! I will upgrade to Matrix and continue my testing.

Thanks!
