### ISSUE TITLE
Unsupported protocol ('"smb) in Kodi 19/Matrix

### ISSUE THREAD

**Issue by BRTPOB** [xbmc/xbmc#19322]
### Describe the bug
When attempting to play any content over the network using SMB on an NVIDIA SHIELD TV Pro, Kodi will error out. When looking at the logs, the specific error message refers to the fact that it's an unsupported protocol ('"smb).

## Expected Behavior
Expected Kodi to play the content like it did as part of Leia

## Actual Behavior
Kodi throws an error stating that it cannot play or find the content in question. Looking at the logs shows that it is providing an error message of an invalid protocol.

## Possible Fix
Not a fix, but a workaround is to ensure that the sources.xml has a username/password attached to it, which was not required previously.

### To Reproduce
1. Add an SMB source to the Android version of Kodi.
2. Attempt to go view the shared content.
3. Observe error message.

### Debuglog
The info log can be found here:
https://paste.kodi.tv/noloxakapo.kodi

Debug log can be found here:
https://paste.kodi.tv/fotagonite.kodi

I will provide the debug log tomorrow morning, but I wanted to get this bug report in/the initial log for you as well.

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Kodi client is running on NVIDIA SHIELD Pro, latest SHIELD Experience. Server is running on Ubuntu 20.04.
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Abolfazl** [comment]
I had this same problem too when i moved to Kodi 19 Alpha

**Comment by BRTPOB** [comment]
Abolfazl, yeah I was linked to your original issue and as I said on your initial issue, I went straight from release to release, which is why I opened this new one. I've also gone and added the debug log to show that in both info and debug, the issue occurs.

A workaround, which seems to not have been included, is to add the username and password to sources.xml, but that wasn't a requirement before and if it's a requirement now, it should be listed as such.

**Comment by DaVukovic** [comment]
Did you follow these steps to add the smb share?

https://kodi.wiki/view/SMB

As these steps also require to enter a username and a password and this wiki was changed in August 2020.

**Comment by BRTPOB** [comment]
No, I didn't but the steps do not require a username/password:

4.3 **If** your share requires a Username and Password enter them in the appropriate sections.

This also worked just fine prior to Matrix 19 with Leia 18.

**Comment by DaVukovic** [comment]
Yes, and, as you said yourself, as it works with a username and a password, your share seems to require that, no? 

Noone knows how you setup your Server and what is configured over there. 

I guess it's because of the SMB1 -> SMB2 change. You might also set "min SMB1" and "max SMB1"  at the Kodi settings again and it might work. Anyway....SMB1 is not recommended anymore. So please set up your sources with a username and a password. 

For the rest, please seek for assistance at the forums. This is not a Kodi bug
