### ISSUE TITLE
Wish: Kodi should support music navigation by label tag

### ISSUE THREAD

**Issue by tillschaefer** [xbmc/xbmc#19326]
The Kodi library already knows about the music metadata tag `label` (i.e., publisher) of songs (called `strRecordLabel` in Song.h) and albums (called `strLabel` in Album.h). The label tag is already shown in some views, like the Shift View. 

It would be very helpfully if the library nodes could be grouped by the this tag like it is the case for genres such as given by the library node xbmc/system/library/music/genres.xml

To put it in other words. I would like to see the followoing library node working: 
```
<node type="filter">
        <label>Labels</label>
        <content>albums</content>
        <group>labels</group>
</node>
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo Linux
 - Kodi version: 19.0

**Comment by the-black-eagle** [comment]
Please post feature requests in the designated part of the forum https://forum.kodi.tv/forumdisplay.php?fid=9 as this is for issues only.

Thanks.

**Comment by tillschaefer** [comment]
For reference: https://forum.kodi.tv/showthread.php?tid=301447
