### ISSUE TITLE
Player.GetItem returns empty values

### ISSUE THREAD

**Issue by instalator** [xbmc/xbmc#19336]
Kodi version 18.8

I turn on the video file playback via the kodi web interface:
![image](https://user-images.githubusercontent.com/11523624/110079930-55b23c80-7dbc-11eb-96e6-2dbc2d72a765.png)

`{"jsonrpc":"2.0","id":2,"method":"Player.GetItem","params":{"playerid":1,"properties":["albumid","userrating","album","albumartist","artist","director","episode","fanart","file","genre","plot","rating","season","showtitle","studio","imdbnumber","tagline","thumbnail","title","track","writer","year","streamdetails","originaltitle","cast","playcount"]}}`

Player.GetItem returns correct data:

`{"id":2,"jsonrpc":"2.0","result":{"item":{"album":"","artist":[],"cast":[{"name":"Liam Neeson","order":1,"role":"Tom","thumbnail":"image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fjrf9LaTFWfLA5DBhFWENFsWh4Y9.jpg/"},{"name":"Kate Walsh","order":2,"role":"Annie","thumbnail":"image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fjRg4pmjvI2063YnQ6PJidclOc4L.jpg/"},{"name":"Jai Courtney","order":3,"role":"Agent Nivens","thumbnail":"image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f9kMUy38pj7oTCuQUhfkbgXOedCq.jpg/"},{"name":"Jeffrey Donovan","order":4,"role":"Agent Meyers","thumbnail":"image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fzCClq83bFutiZvK2GcPhFDe2Bzl.jpg/"},{"name":"Anthony Ramos","order":6,"role":"Agent Hall","thumbnail":"image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fityTHqIXFT3laID4j4ptlnc84zq.jpg/"},{"name":"Robert Patrick","order":7,"role":"Agent Sam Baker","thumbnail":"image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fqRv2Es9rZoloullTbzss3I5j1Mp.jpg/"},{"name":"Jasmine Cephas Jones","order":8,"role":"Beth Hall","thumbnail":"image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fqV8SqN2K2zx7A9urjNGo9O7SEuc.jpg/"},{"name":"Birol Tarkan Yildiz","order":9,"role":"Boss Mike","thumbnail":"image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fmHg8pitBFWnLxyipdfsJJ9ETU4H.jpg/"},{"name":"Adam Teper","order":10,"role":"Hotel Valet","thumbnail":"image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f8bhLrSPRColmN6gvvOxlvPaFoL5.jpg/"},{"name":"Jose Guns Alves","order":11,"role":"Bomb Squad Specialist","thumbnail":"image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fcLm8cFWaZESOsz4pIjuTV0MGSmq.jpg/"},{"name":"Osmani Rodriguez","order":12,"role":"Short Detective"},{"name":"Devon Diep","order":13,"role":"Cute Nurse"},{"name":"Michael Malvesti","order":14,"role":"Wired Cop"},{"name":"Lewis D. Wheeler","order":15,"role":"ER Doctor","thumbnail":"image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f6jBaDldiWtPaVl7X6Uufkv0mLNt.jpg/"},{"name":"Patty O'Neil","order":16,"role":"Sharon Baker"}],"director":["Mark Williams"],"episode":-1,"fanart":"image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f2M2JxEv3HSpjnZWjY9NOdGgfUd.jpg/","file":"nfs://192.168.88.11/volume3/HLAM/Video/Honest Thief 2020.mkv","genre":["боевик","триллер","криминал","драма"],"id":1186,"imdbnumber":"tt1838556","label":"Честный вор","originaltitle":"Honest Thief","playcount":0,"plot":"Сюжет расскажет историю о грабителе банков Томе Картере, который влюбляется в сотрудницу хранилища Энни. Именно в этом хранилище Картер прячет свои награбленные 7 миллионов долларов. Решив начать всё с чистого листа, он решает сдаться, но всё меняется, когда за его дело берётся Нивенс, нечестный агент ФБР.","rating":6.599999904632568,"season":-1,"showtitle":"","streamdetails":{"audio":[{"channels":6,"codec":"ac3","language":"rus"},{"channels":6,"codec":"dtshd_ma","language":"eng"}],"subtitle":[{"language":"eng"}],"video":[{"aspect":1.7777780294418336,"codec":"h264","duration":5912,"height":1080,"language":"eng","stereomode":"","width":1920}]},"studio":["The Solution"],"tagline":"Never steal a man's second chance.","thumbnail":"image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fcjEO0gH8TnMzuWwNYdSDDXQKqbu.jpg/","title":"Честный вор","track":-1,"type":"movie","userrating":0,"writer":["Mark Williams","Steve Allrich"],"year":2020}}}`

We include the following file:
![image](https://user-images.githubusercontent.com/11523624/110080352-e6891800-7dbc-11eb-9288-61acece0e427.png)

Player.GetItem returns empty values.

`{"id":2,"jsonrpc":"2.0","result":{"item":{"album":"","artist":[],"cast":[],"director":[],"episode":-1,"fanart":"","file":"","genre":[],"imdbnumber":"","label":"","originaltitle":"","playcount":0,"plot":"","rating":0.0,"season":-1,"showtitle":"","streamdetails":{"audio":[],"subtitle":[],"video":[]},"studio":[],"tagline":"","thumbnail":"","title":"","track":-1,"type":"unknown","userrating":0,"writer":[],"year":1969}}}`

**Comment by enen92** [comment]
Please check if the behaviour occurs in matrix, Leia is an outdated version by now and won't see any fixes.

**Comment by instalator** [comment]
On version 19.0, the error was reproduced even when opening the first file.
![image](https://user-images.githubusercontent.com/11523624/110102287-31b02480-7dd7-11eb-8e55-cb76e1dcbc26.png)

![image](https://user-images.githubusercontent.com/11523624/110102015-d67e3200-7dd6-11eb-913d-d2aa269075e9.png)

Player.GetItem returns correct data:

{"id":2,"jsonrpc":"2.0","result":{"item":{"album":"","artist":[],"cast":[],"director":[],"episode":-1,"fanart":"","file":"H:\\Video\\I Can Only Imagine 2018.mkv","genre":[],"imdbnumber":"","label":"I Can Only Imagine 2018.mkv","originaltitle":"","playcount":0,"plot":"","rating":0.0,"season":-1,"showtitle":"","streamdetails":{"audio":[],"subtitle":[],"video":[]},"studio":[],"tagline":"","thumbnail":"","title":"","track":-1,"type":"unknown","userrating":0,"writer":[],"year":0}}}

**Comment by malard** [comment]
issue in chorus2 (if its still an issue) please open a ticket there
