### ISSUE TITLE
Excessive db query time on tvshow episode listing

### ISSUE THREAD

**Issue by syfluqs** [xbmc/xbmc#19337]
### Describe the bug
Here is a clear and concise description of what the problem is:

Updated to Kodi 'Matrix' from 'Leia' today. I have a centralized MySQL media database. After database migration, I noticed that tv shows with a substantial number of episodes (>200) were taking a lot of time (around 2 mins) to show the episode listing.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

For my previous 'Leia' setup, the listing time was unnoticeable and no discernible latency existed regardless of the number of episodes in the tvshow.

## Actual Behavior

I dug into MySQL logs and found the culprit queries. 

```
Tcp port: 0  Unix socket: /run/mysqld/mysqld.sock
Time		    Id Command	Argument
# Time: 210305 14:25:41
# User@Host: kodi[kodi] @  [192.168.69.5]
# Thread_id: 46  Schema: MyVideos119  QC_hit: No
# Query_time: 52.381871  Lock_time: 0.000534  Rows_sent: 4060  Rows_examined: 6837957
# Rows_affected: 0  Bytes_sent: 3479647
use MyVideos119;
SET timestamp=1614934541;
select * from episode_view  WHERE ((episode_view.playCount IS NULL OR episode_view.playCount < 1));

# Time: 210305 14:26:07
# User@Host: kodi[kodi] @  [192.168.69.5]
# Thread_id: 42  Schema: MyVideos119  QC_hit: No
# Query_time: 121.363450  Lock_time: 0.000588  Rows_sent: 13  Rows_examined: 15211992
# Rows_affected: 0  Bytes_sent: 11924
SET timestamp=1614934567;
select * from episode_view  WHERE (episode_view.idShow = 175) AND ((episode_view.c12 = 2 or (episode_view.c12 = 0 and (episode_view.c15 = 0 or episode_view.c15 = 2))));
```

### To Reproduce

1. Navigate to 'TV shows'
2. Navigate to a tv show with more than about 200 total episodes.
3. Navigate to either a specific season listing or '* All season' listing.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux (Linux arc 5.10.7-arch1-1 #1 SMP PREEMPT Wed, 13 Jan 2021 12:02:01 +0000 x86_64 GNU/Linux)
 - Kodi version: kodi-x11 19.0-6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by howie-f** [comment]
i tried to reproduce but wasn't able to. scraped a new tvshow `Nature (1982)` with Leia. it counts 408 episodes.
after that dropped the Kodi 19 Video-Database, start up Matrix and let the migration happen..
opening the `All seasons` node shows all episodes immediately (sure, thumbs need to be fetched) but no delay.
System: Debian Buster, Kodi 19.0, MariaDB 10.3.27
what's different at your end?

**Comment by syfluqs** [comment]
My centralized database runs on a raspberry pi 4 with buster as well. 

```
$ uname -a
Linux spinetail 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
$ mariadb --version
mariadb  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnueabihf (armv8l) using readline 5.2
```

I think the raspberry pi (the version 4, atleast) is a fairly capable and adequate machine and we can safely rule out the causation of this issue on the hardware. I have had no problems with Kodi Leia with the same hardware setup.

Can this issue have something to do with a botched migration process? Maybe some indexes were not created?
I did try a fresh install of Kodi Matrix, dropping the new databases and migrating the previous database, but no luck.

Can it be a regression-like problem that maybe my old database is somehow botched and thats why the new database is not working correctly?

These are the indexes in my `MyVideos119` database. I notice that the long running query uses `c15` column from `episode_view` which comes directly from `episode` table, but I don't have any index on `c15`. Can this be the culprit?

```
MariaDB [MyVideos119]> select table_name, column_name, index_name from information_schema.statistics where table_schema='MyVideos119';
+-----------------+--------------+---------------------------+
| table_name      | column_name  | index_name                |
+-----------------+--------------+---------------------------+
| director_link   | actor_id     | ix_director_link_1        |
| director_link   | media_type   | ix_director_link_1        |
| director_link   | media_id     | ix_director_link_1        |
| director_link   | media_id     | ix_director_link_2        |
| director_link   | media_type   | ix_director_link_2        |
| director_link   | actor_id     | ix_director_link_2        |
| director_link   | media_type   | ix_director_link_3        |
| musicvideo      | idMVideo     | PRIMARY                   |
| musicvideo      | idMVideo     | ix_musicvideo_file_1      |
| musicvideo      | idFile       | ix_musicvideo_file_1      |
| musicvideo      | idFile       | ix_musicvideo_file_2      |
| musicvideo      | idMVideo     | ix_musicvideo_file_2      |
| musicvideo      | c14          | ixMusicVideoBasePath      |
| sets            | idSet        | PRIMARY                   |
| files           | idFile       | PRIMARY                   |
| files           | idPath       | ix_files                  |
| files           | strFilename  | ix_files                  |
| tvshowlinkpath  | idShow       | ix_tvshowlinkpath_1       |
| tvshowlinkpath  | idPath       | ix_tvshowlinkpath_1       |
| tvshowlinkpath  | idPath       | ix_tvshowlinkpath_2       |
| tvshowlinkpath  | idShow       | ix_tvshowlinkpath_2       |
| tag_link        | tag_id       | ix_tag_link_1             |
| tag_link        | media_type   | ix_tag_link_1             |
| tag_link        | media_id     | ix_tag_link_1             |
| tag_link        | media_id     | ix_tag_link_2             |
| tag_link        | media_type   | ix_tag_link_2             |
| tag_link        | tag_id       | ix_tag_link_2             |
| tag_link        | media_type   | ix_tag_link_3             |
| stacktimes      | idFile       | ix_stacktimes             |
| actor_link      | actor_id     | ix_actor_link_1           |
| actor_link      | media_type   | ix_actor_link_1           |
| actor_link      | media_id     | ix_actor_link_1           |
| actor_link      | role         | ix_actor_link_1           |
| actor_link      | media_id     | ix_actor_link_2           |
| actor_link      | media_type   | ix_actor_link_2           |
| actor_link      | actor_id     | ix_actor_link_2           |
| actor_link      | media_type   | ix_actor_link_3           |
| movie           | idMovie      | PRIMARY                   |
| movie           | idFile       | ix_movie_file_1           |
| movie           | idMovie      | ix_movie_file_1           |
| movie           | idMovie      | ix_movie_file_2           |
| movie           | idFile       | ix_movie_file_2           |
| movie           | c23          | ixMovieBasePath           |
| actor           | actor_id     | PRIMARY                   |
| actor           | name         | ix_actor_1                |
| seasons         | idSeason     | PRIMARY                   |
| seasons         | idShow       | ix_seasons                |
| seasons         | season       | ix_seasons                |
| bookmark        | idBookmark   | PRIMARY                   |
| bookmark        | idFile       | ix_bookmark               |
| bookmark        | type         | ix_bookmark               |
| country_link    | country_id   | ix_country_link_1         |
| country_link    | media_type   | ix_country_link_1         |
| country_link    | media_id     | ix_country_link_1         |
| country_link    | media_id     | ix_country_link_2         |
| country_link    | media_type   | ix_country_link_2         |
| country_link    | country_id   | ix_country_link_2         |
| country_link    | media_type   | ix_country_link_3         |
| tvshow          | idShow       | PRIMARY                   |
| writer_link     | actor_id     | ix_writer_link_1          |
| writer_link     | media_type   | ix_writer_link_1          |
| writer_link     | media_id     | ix_writer_link_1          |
| writer_link     | media_id     | ix_writer_link_2          |
| writer_link     | media_type   | ix_writer_link_2          |
| writer_link     | actor_id     | ix_writer_link_2          |
| writer_link     | media_type   | ix_writer_link_3          |
| tag             | tag_id       | PRIMARY                   |
| tag             | name         | ix_tag_1                  |
| country         | country_id   | PRIMARY                   |
| country         | name         | ix_country_1              |
| art             | art_id       | PRIMARY                   |
| art             | media_id     | ix_art                    |
| art             | media_type   | ix_art                    |
| art             | type         | ix_art                    |
| episode         | idEpisode    | PRIMARY                   |
| episode         | idEpisode    | ix_episode_file_1         |
| episode         | idFile       | ix_episode_file_1         |
| episode         | idFile       | id_episode_file_2         |
| episode         | idEpisode    | id_episode_file_2         |
| episode         | c12          | ix_episode_season_episode |
| episode         | c13          | ix_episode_season_episode |
| episode         | c17          | ix_episode_bookmark       |
| episode         | idEpisode    | ix_episode_show1          |
| episode         | idShow       | ix_episode_show1          |
| episode         | idShow       | ix_episode_show2          |
| episode         | idEpisode    | ix_episode_show2          |
| episode         | c19          | ixEpisodeBasePath         |
| genre           | genre_id     | PRIMARY                   |
| genre           | name         | ix_genre_1                |
| path            | idPath       | PRIMARY                   |
| path            | strPath      | ix_path                   |
| path            | idParentPath | ix_path2                  |
| genre_link      | genre_id     | ix_genre_link_1           |
| genre_link      | media_type   | ix_genre_link_1           |
| genre_link      | media_id     | ix_genre_link_1           |
| genre_link      | media_id     | ix_genre_link_2           |
| genre_link      | media_type   | ix_genre_link_2           |
| genre_link      | genre_id     | ix_genre_link_2           |
| genre_link      | media_type   | ix_genre_link_3           |
| studio          | studio_id    | PRIMARY                   |
| studio          | name         | ix_studio_1               |
| settings        | idFile       | ix_settings               |
| streamdetails   | idFile       | ix_streamdetails          |
| uniqueid        | uniqueid_id  | PRIMARY                   |
| uniqueid        | media_id     | ix_uniqueid1              |
| uniqueid        | media_type   | ix_uniqueid1              |
| uniqueid        | type         | ix_uniqueid1              |
| uniqueid        | media_type   | ix_uniqueid2              |
| uniqueid        | value        | ix_uniqueid2              |
| rating          | rating_id    | PRIMARY                   |
| rating          | media_id     | ix_rating                 |
| rating          | media_type   | ix_rating                 |
| movielinktvshow | IdShow       | ix_movielinktvshow_1      |
| movielinktvshow | idMovie      | ix_movielinktvshow_1      |
| movielinktvshow | idMovie      | ix_movielinktvshow_2      |
| movielinktvshow | IdShow       | ix_movielinktvshow_2      |
| studio_link     | studio_id    | ix_studio_link_1          |
| studio_link     | media_type   | ix_studio_link_1          |
| studio_link     | media_id     | ix_studio_link_1          |
| studio_link     | media_id     | ix_studio_link_2          |
| studio_link     | media_type   | ix_studio_link_2          |
| studio_link     | studio_id    | ix_studio_link_2          |
| studio_link     | media_type   | ix_studio_link_3          |
+-----------------+--------------+---------------------------+
123 rows in set (0.004 sec)
```

**Comment by howie-f** [comment]
hm, just checked. my indices look the same and i don't have one on `episode.c15` either. 123 rows in set just looking like yours. so we have to assume your database is ok. i should have mentioned i disabled `innodb` and use `Aria` as the default.
for now i'm out of ideas, so i suggest to create **a very good backup** of your database (shutdown db, copy complete `/var/lib/mysql` to a backup folder). then start over by dropping all MyVideosXYZ db's. start Matrix and rescrape the tvshow to see if that helps. good luck.

or maybe you can utilize a different machine for the db-server for testing.

**Comment by syfluqs** [comment]
Just as you said, I took a backup of the mysql directory and also exported my whole video library as xml from kodi. So, then I dropped all databases and scraped one of the huge tv shows with around 400 episodes. After scraping was done, I didn't notice any delay at all, just like you reported. 

So then I again dropped all databases, and this time I tried importing my complete library from the xml file. But after that was done, the delay still remained. So I am guessing, this is somehow related to the total size of the library as well. I have 7607 entries in my `episode` table and 899 entries in my `seasons` table. 

I didn't try with rescraping my whole library, because there are some issues with the new tmdb python scraper, i think and it popped out quite a large number of python errors, which maybe due to some api/code incompatibility, but I don't really know. Following error happens for many movie collections, movies and tvshows alike.

```
                                                     File "/usr/share/kodi/addons/metadata.themoviedb.org.python/python/scraper.py", line 175, in <module>
                                                       run()
                                                     File "/usr/share/kodi/addons/metadata.themoviedb.org.python/python/scraper.py", line 164, in run
                                                       enddir = not get_details(parse_lookup_string(params["url"]), params['handle'], settings)
                                                     File "/usr/share/kodi/addons/metadata.themoviedb.org.python/python/scraper.py", line 90, in get_details
                                                       details = get_tmdb_scraper(settings).get_details(input_uniqueids)
                                                     File "/usr/share/kodi/addons/metadata.themoviedb.org.python/python/lib/tmdbscraper/tmdb.py", line 62, in get_details
                                                       return self._assemble_details(**details)
                                                     File "/usr/share/kodi/addons/metadata.themoviedb.org.python/python/lib/tmdbscraper/tmdb.py", line 106, in _assemble_details
                                                       info['set'] = collection.get('name') or collection_fallback.get('name')
                                                   AttributeError: 'str' object has no attribute 'get'
```

**Comment by KarellenX** [comment]
@syfluqs 

We need the full log thanks. The snippet is not enough.

**Comment by syfluqs** [comment]
> @syfluqs
> 
> We need the full log thanks. The snippet is not enough.

are you referring to the tmdb python scraper part or the original query time part? 
if you are asking about the scraper part, i think i should open a new separate issue for that.

**Comment by howie-f** [comment]
Python scraper part, please provide the full log in a paste bin http://paste.kodi.tv

**Comment by syfluqs** [comment]
Please find the mentioned python exceptions at the very bottom of this log: [https://paste.kodi.tv/ehakokeqek.kodi](https://paste.kodi.tv/ehakokeqek.kodi)
This occurs when using the 'TMDb TV shows' scraper.

![2021-03-09_10-29](https://user-images.githubusercontent.com/1752852/110421011-9cf14380-80c2-11eb-82bc-6ca921633483.png)

![2021-03-09_10-32](https://user-images.githubusercontent.com/1752852/110421095-ce6a0f00-80c2-11eb-9b10-edc4ab93d5f3.png)

**Comment by pkscout** [comment]
I'm the primary maintainer for the TMDb TV Shows scraper.  I see where the issue is with that.  The API used to return an empty field in one spot if there was no data for it, but now it returns a result without the field at all.  That's what is causing the crash.  I'll see about getting a fix pushed for that.

**Comment by pkscout** [comment]
@syfluqs is there a TV show in particular that causes that error in your full logs. Also, what language do you have set in the TMDb TV Show scraper?  I think I have a fix in place, but sometimes these things happen on edge case shows and/or languages, so if I can test one that you know is a problem, that would help.  Thanks.

**Comment by syfluqs** [comment]
Preferred Language is set to 'en-US' and I think the log that I provided earlier was taken while scanning the TV show 'Breaking Bad'. But, similar errors were there for other TV shows and movies/movie sets as well (from the scraper named "The Movie Database").

**Comment by howie-f** [comment]
@syfluqs can the database related issue be closed? still suggesting a dedicated db-server for testing

**Comment by syfluqs** [comment]
sure, we can close this issue for now. I still need to do some testing with a dedicated db when I get the time. If it persists I'll reopen the issue then and let you know the details.
