### ISSUE TITLE
Incorrect response to XBMC.GetInfoLabels when Kodi is minimized

### ISSUE THREAD

**Issue by wutschel** [xbmc/xbmc#19344]
### Describe the bug
Here is a clear and concise description of what the problem is:

I am using Kodi as a headless Music Player and run it minimized to reduce the load. In all Kodi versions I am using and used for testing (17.6, 19.1 and 20.0 Alpha) I experience this bug. When sending the request `XBMC.GetInfoLabels` with `{"labels": ["MusicPlayer.Codec", "MusicPlayer.SampleRate", "MusicPlayer.BitRate",  "MusicPlayer.Channels"]}` I get a wrong response (either empty or form the last track which was played with non-minimized Kodi server).

For Video it may make sense to not update the response when Kodi is minimized and not showing a screen. For Music this is not required and Kodi should respond properly.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should respond with requested information for the currently playing Music title, independent of the screen being minimized or not.

## Actual Behavior

Scenario 1:
- Start Kodi and minimize screen. 
- Then play a Music title and send the `XBMC.GetInfoLabels` request as described above.
- Error: Kodi will respond with empty data, e.g. `{"MusicPlayer.SampleRate": ""}`

Scenario 2:
- Start Kodi and do not minimize screen. 
- Then play Music title A and send the `XBMC.GetInfoLabels` request as described above.
- Correct data for title A will be provided.
- Now minimized the screen, play Music title B and send the `XBMC.GetInfoLabels` request as described above.
- Error: Kodi will respond with the data for title A. 
- This continues for all other title until the screen is un-minimized. 

### To Reproduce

See the detailed description in section "Actual Behavior".

### Debuglog

The debuglog can be found here: http://paste.kodi.tv/ijivipuqay.kodi
Log was taken on my test system (Kodi 20.0 Alpha) with JSON and Audio tracing enabled.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux Mint 17 and Linux Mint 19
 - Kodi version: 17.6, 19.1 and 20.0 Alpha

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaveTBlake** [comment]
I can't comment on whether Kodi should be expected to return GUI label values when minimised, but I suspect that you should be using JSON API to get data about what is currently playing and not looking at the GUI in this way at all.

**Comment by wutschel** [comment]
Ok, so the iOS Remote App "mis-used" this method for alle the years then. ;)

If I understood right, I should use `Player.GetProperties` and read the data from the response in `currentaudiostream` and `currentvideostream`. On a quick check this seems to work for my Kodi 20 Alpha test environment, but I get empty results on my Kodi 17.6 -- even though the properties seem to be supported. I know this is an old version, but any idea into which direction to look at? I would like to keep the implementation as common as possible.

**Comment by howie-f** [comment]
seems like iOS Remote uses `XBMC.GetInfoLabels` to pull information for the 'Now Playing' screen.
However, the appropiate call to achieve this may be method (for audio):
`Player.GetProperties` with `"params":{"playerid":0,"properties":["currentaudiostream"]}}'`
testresult is: `{"currentaudiostream":{"bitrate":320000,"channels":2,"codec":"mp3"}`

therefor i highly suspect the issue on iOS Remote side, i reproduced the missing labels on 'Now Playing' when Kodi is minimized

**Comment by howie-f** [comment]
>  I get empty results on my Kodi 17.6 -- even though the properties seem to be supported.

same here... maybe the reason for mis-using `XBMC.GetInfoLabels`

**Comment by wutschel** [comment]
> On a quick check this seems to work for my Kodi 20 Alpha test environment, but I get empty results on my Kodi 17.6 -- even though the properties seem to be supported.

@DaveTBlake, is the obversion I describe above just recently fixed by your PR https://github.com/xbmc/xbmc/pull/17535?

**Comment by Tolriq** [comment]
That PR did remove the need to use infolabels for those very specific data so only Kodi 19. Using InfoLabels is valid and supported to get access to information.
But Kodi have some optimisations that stops refreshing UI when minimized on some OS, triggering this sort of stuffs as some queue are not handled and the labels value not updated.
Unfortunately this can't really be labelled as bug but as side effect of using UI info to get data not exposed to JSON (there's many more) so not sure anyone would fix that anytime and we just need to push to have JSON more first class citizen.

**Comment by wutschel** [comment]
Understood. Would it -- to avoid wrong data on the interface -- at least make sense to respond with empty data in the case of minimized UI? Right now the API responds with outdated data.

**Comment by DaveTBlake** [comment]
> Unfortunately this can't really be labelled as bug but as side effect of using UI info to get data not exposed to JSON (there's many more) so not sure anyone would fix that anytime and we just need to push to have JSON more first class citizen.

If people would like to make a list of data not exposed to JSON then that would help a lot towards getting the JSON API improved.

> Would it -- to avoid wrong data on the interface -- at least make sense to respond with empty data in the case of minimized UI? Right now the API responds with outdated data.

You could say that the `XBMC.GetInfoLabels` is returning the correct data.  It is returning what data the GUI has, it just happns that when minimized the GUI data is out of date compared to Kodi internally. 

The way forwards is definitely JSON for this.

**Comment by wutschel** [comment]
Shall we close this as "Won't fix" then?
