### ISSUE TITLE
The "Download subtitles" option on Kore does not bring up the subtitles dialogue in Kodi

### ISSUE THREAD

**Issue by Managor** [xbmc/xbmc#19341]
### Describe the bug
Here is a clear and concise description of what the problem is:

In the leftmost page of Kore, if you select the Kebab menu -> Subtitles -> Download subtitles, it doesn't bring up the subtitles dialogue in Kodi. In the last version it didn't behave like this

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The dialogue should open

## Actual Behavior

No dialogue opens

### To Reproduce

1. Open a movie in Kodi
2. Open Kore
3. Go to the leftmost view in Kore
4. Select the Kebab menu -> Subtitles -> Download subtitles

### Debuglog

The debuglog can be found here:
[kodi.old.log](https://github.com/xbmc/xbmc/files/6093122/kodi.old.log)

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux
 - Kodi version: 19.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ArchieMeng** [comment]
I meet the bug as well.
It is caused by line
```python
# script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py:315 
# def _add_subtitles(self, subtitles):
for _ in range(30) and not monitor.abortRequested():
```
Which is included in commit f8c4689da08a212f1fe67a5f5664b5d49c493424 from enen92.
This line mistaken the for loop syntex and thus caused bug.
I want to contribute the fix, however I don't know if it is ok to directly create a PR to  [XBMC-Addons /
script.module.xbmcswift2](https://github.com/XBMC-Addons/script.module.xbmcswift2).

**Comment by enen92** [comment]
Why does xbmcswift2 have anything to do with a request from Kore to the json rpc?

**Comment by enen92** [comment]
Just tested and this works fine for me in matrix. Even without any subtitle addon installed.

**Comment by ArchieMeng** [comment]
Ok. My issue might be different to this one. I may open up another issue.

**Comment by enen92** [comment]
@ArchieMeng what subtitle add-on are you using that depends on xbmcswift2? I ask this because I ported the framework to python3/matrix just as a way to quickly port a few add-ons (radio, NASA, shoutcast, etc) to matrix but the long term plan is to remove the dependency and deprecate the module. So I am interested in knowing what depends on it that I don't maintain.

**Comment by ArchieMeng** [comment]
> @ArchieMeng what subtitle add-on are you using that depends on xbmcswift2? I ask this because I ported the framework to python3/matrix just as a way to quickly port a few add-ons (radio, NASA, shoutcast, etc) to matrix but the long term plan is to remove the dependency and deprecate the module. So I am interested in knowing what depends on it that I don't maintain.

I don'ht have subtitle addons that rely on xbmcswift. What I have is in [xbmc-kodi-private-china-addons](https://github.com/zhengfan2014/xbmc-kodi-private-china-addons) which use xbmcswift2 as ui module (including adding subtitle to the play stream).
BTW, what is your suggestion for the replacement modules? Like routing module?

**Comment by enen92** [comment]
https://kodi.wiki/view/Add-on:Plugin_routing

**Comment by ArchieMeng** [comment]
> https://kodi.wiki/view/Add-on:Plugin_routing

Thank you.

**Comment by ArchieMeng** [comment]
> deprecate

May I ask when xbmcswift2 will be deprecated? And is there any alternatives for xbmcswift2 other than routing? Because I find it lack of documents. (Such as api. For example, I used Plugin().get_storage() which is hard to find in routing)

**Comment by enen92** [comment]
I just don't want to maintain it as I don't see any value in having it around. The python api evolves and the module has to keep with it, getting workarounds and syntax abstraction for the differences. xbmcswift2 is still using thumbnail/iconimage arguments in listitems which causes confusion. Using reuselanhuageinvoker is hard without breaking the add-ons that depend on it. So my plan is to port my add-ons that depend on it to remove the dependency and mark it as broken in the repo at some point.
You're free to pick it up, ship it in your repo, etc. Afaik you don't have any add-ons in the repo ATM that depend on it. So, you should ship your add-on dependencies from your repo as well :)
