### ISSUE TITLE
pvr.zattoo in Ubuntu ppa not updated

### ISSUE THREAD

**Issue by rbuehlma** [xbmc/xbmc#19340]
### Describe the bug
The current version of pvr.zattoo in the PPA currently is 19.7.2:

https://launchpad.net/~team-xbmc/+archiv...ies_filter=

For the Tags 19.7.3 and 19.7.4 no package has been created:
https://github.com/rbuehlma/pvr.zattoo/r...7.4-Matrix

Is there something more needed than a simple tag or is the build somehow stuck?

## Expected Behavior
The addon in the PPA should be updated upon pushing a new tag to the addons repository

## Actual Behavior
The addon in the PPA is not updated

### Debuglog
This is the Jenkins build:
https://jenkins.kodi.tv/view/Addons/job/rbuehlma/job/pvr.zattoo/view/tags/job/19.7.4-Matrix/

**Comment by wsnipex** [comment]
This seems to be a bug in the pipeline library, because we currently have Matrix for nightly and stable PPA..
It only uploads to nightly instead of both PPAs, for all binary addons.

I've manually pushed 19.7.4 as a quick fix

**Comment by wsnipex** [comment]
closing, since this is not a kodi core issue.

**Comment by rbuehlma** [comment]
Thanks for looking into it. Where would be the best place to report such issues in the future?
