### ISSUE TITLE
open /dev/fb0: No such file or directory

### ISSUE THREAD

**Issue by RiversideRocks** [xbmc/xbmc#19349]
### Describe the bug
Here is a clear and concise description of what the problem is:
Tried to run kodi `(sudo kodi)` after installing on my Pi. Got `open /dev/fb0: No such file or directory`.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should have ran.

## Actual Behavior

Failed with `open /dev/fb0: No such file or directory`

### To Reproduce
1.  sudo apt-get install kodi
2.  sudo kodi

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
This isn't very helpful. Kodi doesn't use /dev/fb0 in v19 so without a debug log or more info I'm going to close this issue.
