### ISSUE TITLE
Shield errors

### ISSUE THREAD

**Issue by ch573** [xbmc/xbmc#19347]
Bonjour
Kodi ne fonctionne plus sur mon player shield depuis que j’ai échangé ma Freebox révolution par une Freebox pop
Il ne trouve plus le serveur selon les messages
Je fais quoi?
Merci

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
No log, no reaction from the reporter. Going to close this one. 

@ch573 I'll happily reopen this issue if you show us a log and it would be nice if you could write your next posting in english language. 

Thanks

**Comment by ch573** [comment]
Hello

No i am french and thé customer it is me!
You have To mâle thé job Sorry 
Regards

Christophe Huibant

**Comment by ch573** [comment]
You close this just after you send me your demand!!!!!  Bullshit 

Christophe Huibant
