### ISSUE TITLE
Universal Movie Scraper: backslash-escaped characters in scraped actor roles

### ISSUE THREAD

**Issue by nambpgh** [xbmc/xbmc#19358]
### Describe the bug
Universal Movie Scraper (scraping from TMDB) has escaped characters, e.g. a backslash before a quote, in the role name.

E.g. [Red Sparrow (2018)](https://www.themoviedb.org/movie/401981-red-sparrow/cast?language=en-US): In the role names also quotes are used, like for `Nathaniel "Natan" Nash ` or `"Matron" `.
In Kodi the actors/roles will be shown as `Nathaniel \"Natan\" Nash ` or `\"Matron\" `

In the TMDBCast result the values for the role-tag have escaped quotes.
E.g.:
`...<actor><name>Joel Edgerton</name><role>Nathaniel \"Natan\" Nash</role>...`
`...<actor><name>Charlotte Rampling</name><role>\"Matron\"</role>...`
(IMHO there is no need to escape the quotes in the values of XML-tags.)

## Expected Behavior
No backslash-escaped quotes

## Actual Behavior

backslashes in the roles

### To Reproduce

1. Scrap a movie with quotes in the roles, e.g. https://www.themoviedb.org/movie/401981-red-sparrow

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/nicutuduvi.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://postimg.cc/QHLZrJ1w

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: v18

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Confirmed...
