### ISSUE TITLE
An error or cosmetic inaccuracy.

### ISSUE THREAD

**Issue by ulrichloose** [xbmc/xbmc#19350]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

"play next video automatically" setting active. A whole folder with series sequences is to be played. Name is 001.mp4 to 100.mp4.

It works so far.

Now you stop playing at the file 050.mp4 but in the window File Selection the file with which you started playing - 001.mp4 - remains highlighted. However, according to logic, the highlighting should be active at the last file played - 050.mp4. This is annoying in case, because you have to remember the name of the last played file before stopping the last played file and scroll to it, in order to be able to play it further.

Wouldn't it be possible to change the automatic play to highlight the last file played in the file picker when a stop occurred?

The "problem" is in all versions up to the current one.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: FireTv 64 Bit
 - Kodi version: 19.0 and any older version too

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Feature requests are made in the forum. Thanks!

**Comment by enen92** [comment]
Sounds like a bug to me though :)

**Comment by ulrichloose** [comment]
Damn arrogant high-nose snobs here...

It's an error, not a feature.

**Comment by lrusak** [comment]
It's the prerogative of the OP to make arguments to back their case but in the situation of insulting the maintainers I think it's better to leave this one closed :smiley:

**Comment by HitcherUK** [comment]
You're confusing the file list with the play list.
