### ISSUE TITLE
Submenu wont open in TV Guide TVHeadEnd Kodi 19 Shield

### ISSUE THREAD

**Issue by CanberraPete** [xbmc/xbmc#19368]
### Describe the bug
Here is a clear and concise description of what the problem is:

The Submenu (allows setting record etc) in the TVHeadEnd TV Guide Kodi 19 (at lest on my Shield) does not open.
(I have my TVheadEnd plugin configured to change channels immediately when I select a channel in the guide)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I used to be able to hold the "enter" button on an entry in the TV guide and it would bring up a menu allowing me a few options but that function no longer seems to be there.  the press-hold works everywhere else I've tried.

## Actual Behavior

Nothing happens.

### To Reproduce

1. Configure Kodi/TVheadend plugin to immediately change channels when channel is selected in Guide. (settings - PVR and Live TV - Guide - default Action - Switch to Channel
2. Open the TV Guide, select a program and press/hold the "Select" button on the remote
3.Submenu "should" appear but does not.

### Debuglog

The debuglog can be found here:

2021-03-09 14:31:40.086 T:25055    INFO <general>: Loading skin file: DialogPVRGuideControls.xml, load type: KEEP_IN_MEMORY
2021-03-09 14:31:40.087 T:25055   ERROR <general>: Unable to load window XML: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/skin.confluence/720p/DialogPVRGuideControls.xml. Line 0
                                                   Failed to open file

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:  19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Longpress enter opens the guide controls in Kodi 19. If you want the context menu, use c key on your keyboard or create a custom keymap which fits your needs.

BTW: the guide window bring more complex than other windows requires some special key bindings which may suffer from the other windows. For example left cannot directly jump to the dude blade and right cannot directly jump to the scroll bar. You won't write issues for that.

**Comment by CanberraPete** [comment]
Thanks for your response.

I have a Nvidia Shield.  No “c” key.

From what I saw in the log it looks like it’s trying to bring up the menu when I long press the Enter/Select key it’s just not finding the file.

Might be an error in the confluence skin.


2021-03-09 14:31:40.086 T:25055    INFO <general>: Loading skin file: DialogPVRGuideControls.xml, load type: KEEP_IN_MEMORY
2021-03-09 14:31:40.087 T:25055   ERROR <general>: Unable to load window XML: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/skin.confluence/720p/DialogPVRGuideControls.xml. Line 0
                                                   Failed to open file


I don’t know how to get access to that location to see if the file is there.

Pete.
