### ISSUE TITLE
Frame drop every 5 seconds or so when playing 60fps media with Kodi 18 and 19 on Linux

### ISSUE THREAD

**Issue by mamarley** [xbmc/xbmc#19376]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I play 60fps media (usually recorded or live TV streams with pvr.hts, but it happens consistently with all 60fps media I have tried), I get a frame drop about every 5 seconds.  This is most noticeable on content with a ticker or content with fast camera movement like sports broadcasts.  It happens with both Kodi 18 and 19.  It may happen with older versions too, but I have not tested.  It does not happen with VLC on the same systems.  I have reproduced the issue on multiple systems, but they all contain Intel processors with integrated graphics and are running Kubuntu 20.10.  I don't have any systems with AMD or NVIDIA graphics to try.  The issue happens regardless of whether VA-API is turned on or off and regardless of whether I am playing true 60fps content or frame-doubled deinterlaced content.  It also happens regardless of whether I select the option to set the display framerate to the content framerate.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should play the media smoothly without dropping any frames.

## Actual Behavior

Kodi drops a frame about every 5 seconds.

### To Reproduce

1. Play a 60fps video stream, preferably one with consistent, smooth motion like a ticker
2. Note that a frame drops every 5 seconds or so.

### Debuglog

The debuglog can be found here: https://pastebin.ubuntu.com/p/XW5sbdMrdv/
This debug log was captured while playing the example video that I offer to upload below.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I have an example video that contains a ticker that demonstrates the problem.  If you indicate where I should upload it, I will do so.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Kubuntu 20.10, fully up-to-date
 - Kodi version: 19.0+git20210219.1315-f44fdfbf67-0+final~groovy (from the official PPA)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Could you please do us a favour and try to confirm if the stuttering also happens with this file:

https://drive.google.com/file/d/0BwxFVkl63-lERnhlY1pHeW5wbjQ/view

I had stuttering with that file as well. My TV switched to 60fps, but the playback was far away from being smooth

@fritsch we talked about that at slack.

**Comment by mamarley** [comment]
It does seem to.  It isn't as obvious on that one because there aren't any long, smooth movements, but after watching it several times, I do believe it is dropping frames in about the same way as with my file.  I watched it several times on VLC too and didn't notice any frame dropping there.

Also, thanks for introducing me to a new Joe Walsh/Eagles song!  I hadn't heard that one yet.

**Comment by fritsch** [comment]
No idea to be honest. I don't use VAAPI / Linux anymore as HTPC, therefore I have no idea about combination kodi + skylake on 20.10.

**Comment by FernetMenta** [comment]
Does it make a difference if you disable m_omlSync in advanced settings?

**Comment by DaVukovic** [comment]
@mamarley .. as that's not too obivous what @FernetMenta wants you to test (no offense...it's just not documented at our wiki ;) ) , please put the following in your advancedsettings,xml:

```
<advancedsettings>
  <x11>
    <onlsync>true</omlsync
  </x11>
</advancedsettings>
```

and play that video again after you restartet Kodi. I'll test that as well and will report back

**Comment by mamarley** [comment]
That setting doesn't seem to make a difference one way or the other.

**Comment by fritsch** [comment]
Could you post the log with it being disabled. Not that by "unluck" a "</" or ">" was not properly parsed.

**Comment by mamarley** [comment]
Sure, here's the debug log output: https://pastebin.ubuntu.com/p/3K74sbgxYr/

**Comment by FernetMenta** [comment]
Your first log tells us that something blocks the render thread for at least 2x frametime

```
2021-03-09 08:57:22.261 T:6824    DEBUG <general>: PrepareNextRender: frameOnScreen: 14442213.868246 renderPts: 14507393.540011 nextFramePts: 14500489.000000 -> diff: 6904.540011  render: 1 forceNext: 0
2021-03-09 08:57:22.311 T:6824    DEBUG <general>: PrepareNextRender: frameOnScreen: 14492587.828246 renderPts: 14559254.499999 nextFramePts: 14517172.000000 -> diff: 42082.499999  render: 1 forceNext: 0
2021-03-09 08:57:22.317 T:6824    DEBUG <general>: PrepareNextRender: frameOnScreen: 14498553.603246 renderPts: 14565220.274999 nextFramePts: 14550539.500000 -> diff: 14680.774999  render: 1 forceNext: 0
```

Either there is something in kodi like an addon that consumes too many resources or you are facing issues with the xorg driver. Can you confirm that you are using intel driver, not modesetting? modesetting driver always had issues in the past.

**Comment by mamarley** [comment]
I was using the modesetting driver (it is the default on Ubuntu), so I tried a few different things:

- Intel driver instead of modesetting: Maybe a little bit better, but still dropping frames and I also had a hell of a time getting Kodi to realize that my display wasn't 30hz and eventually ended up having to wipe the Kodi configuration to fix this.
- Intel driver with compositing window manager disabled: No change from the previous test
- Modesetting driver with compositing window manager disabled: Worse than with the compositor on
- Wayland: About the same as xorg

**Comment by FernetMenta** [comment]
On intel systems I always used xorg intel driver and i3 as window manager. Could you try this and post a new log?

**Comment by mamarley** [comment]
I don't really want to go to the effort of installing and learning to use i3, so I tried with no window manager at all (and the "intel" driver), just "startx kodi".  It was still dropping frames, about the same as my normal configuration (modesetting with KDE).  Here's the log: https://pastebin.ubuntu.com/p/JsB4FjfwCt/

**Comment by mamarley** [comment]
Also, for what it is worth, I haven't noticed any frame-dropping issues like this in any other applications.  Firefox, several videogames, VLC, and glxgears all run perfectly smoothly.

**Comment by fritsch** [comment]
Long shot. Please check your gpu frequency while running kodi. Some time ago there was a problem that the min_freq was not properly adjusted in kodis' zero copy load scenario.

```
cat /sys/devices/pci0000:00/0000:00:02.0/drm/card0/gt_min_freq_mhz
300
```

Check gt_max_freq_mhz and put this value into min_freq_mhz

Does this change something?

**Comment by mamarley** [comment]
That doesn't result in any perceivable difference.

**Comment by FernetMenta** [comment]
Back in the time I used Kodi in Intel systems I had zero frame drops with the configuration I mentioned above. If was to investigate this further, I would start with a configuration that was known to be working.

One of the biggest design flaws of Kodi is that rendering is done on the main thread. The main thread also serves many other components like io, addons, scanning peripherals, etc. Maybe one of those components is responsible for the issue.

**Comment by mamarley** [comment]
For me there isn't a known-working configuration, every configuration I've tried has the frame-dropping.

Oh yes, I meant to say regarding the addons that the pvr.hts addon is the only one I installed myself (versus coming bundled with the build in https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa.  I tried disabling that and it didn't make a difference.

**Comment by FernetMenta** [comment]
There is a bug in Kodi's video reference clock for X11 that I had fixed in my branch long ago. It produces inaccurate timing which might be responsible for the skips

```
--- a/xbmc/windowing/X11/WinSystemX11GLContext.cpp
+++ b/xbmc/windowing/X11/WinSystemX11GLContext.cpp
@@ -332,7 +332,7 @@ uint64_t CWinSystemX11GLContext::GetVblankTiming(uint64_t &msc, uint64_t &interv
   if (m_pGLContext)
   {
     float micros = m_pGLContext->GetVblankTiming(msc, interval);
-    return micros / 1000;
+    return micros;
   }
   msc = 0;
   interval = 0;
```

**Comment by fritsch** [comment]
Thanks. Will pick it.
