### ISSUE TITLE
[JSON-RPC] Cast thumbnails not returned via Files.GetDirectory

### ISSUE THREAD

**Issue by finkleandeinhorn** [xbmc/xbmc#19388]
### Describe the bug
It appears that even though cast *information* is returned inside the `'cast'` field in the response from `Files.GetDirectory`, it only includes the `'name'`, `'order'`, and `'role'` information, but not the `'thumbnail'`.

Here is an example of the cast information that TMDbHelper uses *internally*, and is set to the items, which is why their images work:
```json
[
  {
    "name": "Dan Castellaneta",
    "role": "Homer Simpson",
    "order": 0,
    "thumbnail": "https://image.tmdb.org/t/p/w500/AmeqWhP4A46AWkM4kVphg6jOTQX.jpg"
  },
  {
    "name": "Julie Kavner",
    "role": "Marge Simpson",
    "order": 1,
    "thumbnail": "https://image.tmdb.org/t/p/w500/x3oG3OXtBfTFgqXPqxI1GKVEiaQ.jpg"
  },
  {
    "name": "Nancy Cartwright",
    "role": "Bart Simpson",
    "order": 2,
    "thumbnail": "https://image.tmdb.org/t/p/w500/40qNhyYJhSE2Yiy4pnXSZhdufO6.jpg"
  },
  {
    "name": "Yeardley Smith",
    "role": "Lisa Simpson",
    "order": 3,
    "thumbnail": "https://image.tmdb.org/t/p/w500/oACYQyA8k8oDaMxsbMRHz8OP6u2.jpg"
  },
  {
    "name": "Hank Azaria",
    "role": "Apu",
    "order": 7,
    "thumbnail": "https://image.tmdb.org/t/p/w500/khTCh9TUT5YgMNvteLAh0D9H4Ck.jpg"
  },
  {
    "name": "Harry Shearer",
    "role": "Ned Flanders",
    "order": 500,
    "thumbnail": "https://image.tmdb.org/t/p/w500/au1mO0Mb9gni7h0rJCSokBTDnVf.jpg"
  }
]
```

However, the same item from TMDbHelper (The Simpsons) returns this in the JSON-RPC `Files.GetDirectory` response:
```json
[
  {
    "name": "Dan Castellaneta",
    "order": 0,
    "role": "Homer Simpson"
  },
  {
    "name": "Julie Kavner",
    "order": 1,
    "role": "Marge Simpson"
  },
  {
    "name": "Nancy Cartwright",
    "order": 2,
    "role": "Bart Simpson"
  },
  {
    "name": "Yeardley Smith",
    "order": 3,
    "role": "Lisa Simpson"
  },
  {
    "name": "Hank Azaria",
    "order": 7,
    "role": "Apu"
  },
  {
    "name": "Harry Shearer",
    "order": 500,
    "role": "Ned Flanders"
  }
]
```

## Expected Behavior

The `'thumbnail'` field should also be returned, if it is set on the file in question.

## Actual Behavior

The `'thumbnail'` field is omitted, even if it is set on the file in question.

## Possible Fix

I'm not sure why this is happening, but my suspicion is that it *may* have something to do with that field not being "required", as the rest of them are, in the full JSON-RPC schema:
```json
...
  "cast": {
    "id": "Video.Cast",
    "items": {
      "additionalProperties": false,
      "properties": {
        "name": {
          "required": true,
          "type": "string"
        },
        "order": {
          "required": true,
          "type": "integer"
        },
        "role": {
          "required": true,
          "type": "string"
        },
        "thumbnail": {
          "default": "",
          "type": "string"
        }
      },
      "type": "object"
    },
    "type": "array"
  }
...
```

### To Reproduce

1. Make a `Files.GetDirectory` JSON-RPC call to any path where the cast is set on the items inside, and have thumbnails attached.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I maintain an add-on which retrieves items directly from paths, via the `Files.GetDirectory` call, and the returned items are unable to accurately attach thumbnails for the cast, as the API does not return them.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 18.9, 19.0

I suspect that this is the same behavior in any version, but this is where I have personally tested.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Not sure this can qualify as a bug/issue, at least I see it more as a feature request

**Comment by finkleandeinhorn** [comment]
I'm fine with it being a request... but to me I see it as a bug that not all of the information is returned, when it is clearly attached to the items, and also supposedly supported by the response.

**Comment by finkleandeinhorn** [comment]
Could it be because of https://github.com/xbmc/xbmc/blob/master/xbmc/video/VideoInfoTag.cpp#L280? I think that should be `"thumbnail"`, rather than `"thumb"`, in order to.match the JSON schema?

**Comment by finkleandeinhorn** [comment]
@enen92, do you have any input here?

**Comment by enen92** [comment]
Haven't looked into it sorry. However I find it odd to expect a cast entry on a files method

**Comment by finkleandeinhorn** [comment]
For example, requesting the cast attached to a ListItem in an add-on.

**Comment by finkleandeinhorn** [comment]
I've tested this by making the change I proposed earlier in the thread:

> Could it be because of https://github.com/xbmc/xbmc/blob/master/xbmc/video/VideoInfoTag.cpp#L280? I think that should be "thumbnail", rather than "thumb", in order to match the JSON schema?

And building Kodi from source.

I can now pull the thumbnails properly, using a similar call:
```json
[
  {
    "name": "Tom Hiddleston",
    "order": 0,
    "role": "Loki Laufeyson",
    "thumbnail": "image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2fw500%2fmclHx…"
  },
  {
    "name": "Owen Wilson",
    "order": 1,
    "role": "Mobius M. Mobius",
    "thumbnail": "image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2fw500%2fop8sG…"
  },
  {
    "name": "Sophia Di Martino",
    "order": 2,
    "role": "Sylvie / The Variant",
    "thumbnail": "image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2fw500%2fqZdFp…"
  },
  {
    "name": "Gugu Mbatha-Raw",
    "order": 3,
    "role": "Ravonna Renslayer",
    "thumbnail": "image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2fw500%2fxhdka…"
  },
  {
    "name": "Wunmi Mosaku",
    "order": 4,
    "role": "Hunter B-15",
    "thumbnail": "image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2fw500%2fmWDsV…"
  },
  {
    "name": "Tara Strong",
    "order": 7,
    "role": "Miss Minutes (voice)",
    "thumbnail": "image://https%3a%2f%2fimage.tmdb.org%2ft%2fp%2fw500%2fy9S3Q…"
  }
]
```

I've also checked in various places to ensure that this hasn't had an adverse effect on any normal operations, so I think it should be fine. I'll be making a pull request shortly :+1:

**Comment by finkleandeinhorn** [comment]
This is now fixed in Kodi N 👍
