### ISSUE TITLE
French translation error msgctxt "# 20446" in strings.po

### ISSUE THREAD

**Issue by lepetrel69** [xbmc/xbmc#19389]
### Describe the bug
Here is a clear and concise description of what the problem is:
Strings.po
msgctxt "#20446"
msgid "Locally stored information found. Ignore and refresh from Internet?"
msgstr "Des informations existent déjà localement.\nFaut-il les ignorer et actualiser depuis Internet ?"

The display in kodi 17 and kodi 19 is incomplete.
in kodi 18 is complete

link to the forum: https://forum.kodi.tv/showthread.php?tid=361007 (url)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix
delete "\ n"  in the french strings.po. for kodi 19.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: kodi 17 , kodi 18 and kodi 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@gade01 not sure how the status for weblate is but this is the second translation issue we get in this repo. Maybe not a bad idea to have a text placeholder to point users into the right direction

**Comment by gade01** [comment]
@lepetrel69 
Thanks so much for reporting this.

We are currently working on moving translations to Weblate.
Currently we still have some remaining things to sort out, which is why we have not yet opened fully up for regular users and translators.

Once we open up, Weblate has great tools to fix these kind of issues.
We will keep the issue open until then.

**Comment by gade01** [comment]
Fix pending: https://github.com/xbmc/repo-resources/pull/125

**Comment by gade01** [comment]
The changes and fixes are pushed to the new language addons.

Thanks again for reporting this.
