### ISSUE TITLE
verifypeer=false is ignored in video-player ( xbmc.Player.Play )

### ISSUE THREAD

**Issue by large** [xbmc/xbmc#19397]
### Describe the bug
My current development server has a self signed certificate.
If an addon uses xbmc.Player.Play() with a link https://site.com/file.mp4|verifypeer=false it would fail with certification error.
Note everything works 100% with http:// links using this method.

## Expected Behavior
Tests with curl directly works using the --insecure flag

## Actual Behavior

> 2021-03-11 23:27:52.690 T:3976    ERROR <general>: CCurlFile::Stat - Failed: SSL peer certificate or SSH remote key was not OK(60) for https://site.com/file.mp4|verifypeer=false
> 2021-03-11 23:27:52.692 T:3976     INFO <general>: VideoPlayer::OpenFile: https://site.com/file.mp4|verifypeer=false
> 2021-03-11 23:27:52.740 T:3976    ERROR <general>: CCurlFile::Stat - Failed: SSL peer certificate or SSH remote key was not OK(60) for https://site.com/file.mp4|verifypeer=false
> 2021-03-11 23:27:52.741 T:15676    INFO <general>: Creating InputStream
> 2021-03-11 23:27:52.779 T:15676   ERROR <general>: CCurlFile::FillBuffer - Failed: SSL peer certificate or SSH remote key was not OK(60)
> 2021-03-11 23:27:52.780 T:15676   ERROR <general>: CCurlFile::Open failed with code 0 for https://site.com/file.mp4:
> 2021-03-11 23:27:52.827 T:15676   ERROR <general>: CCurlFile::FillBuffer - Failed: SSL peer certificate or SSH remote key was not OK(60)
> 2021-03-11 23:27:52.828 T:15676   ERROR <general>: XFILE::CFileCache::Open - <https://site.com/file.mp4|verifypeer=false> failed to open
> 2021-03-11 23:27:52.828 T:15676   ERROR <general>: CVideoPlayer::OpenInputStream - error opening [https://site.com/file.mp4|verifypeer=false]
> 2021-03-11 23:27:52.828 T:15676    INFO <general>: CVideoPlayer::OnExit()
> 2021-03-11 23:27:52.848 T:3976     INFO <general>: CVideoPlayer::CloseFile()

## Possible Fix
My C++ skills are not good enough to help you out there...

### To Reproduce
Create a selfsigned cert on an webservice and let the xbmc.Player try to stream from it.

## Additional context or screenshots (if appropriate)
I fully understand that this option leaps over the concept of certificates.
But in some cases you are happy enough with the encryption part of the security, not if we actually are connected to correct server.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win10 64-bit / Android 10
 - Kodi version:
Matrix V19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment]
Need a full debug log.

**Comment by enen92** [comment]
There's more info about this in https://github.com/xbmc/xbmc/pull/17676

For what it's worth, I'd also like to have support for this. It's important in a few use cases.

**Comment by wsnipex** [comment]
see https://github.com/xbmc/xbmc/pull/19030/files on how to use a custom CA trust store.

**Comment by zkte** [comment]
All these SSL options are also ignored by ffmpeg (eg HLS) that does no validation.

**Comment by large** [comment]
Thank you all for the feedback!

Strange that PR #17676 was ignored in the v19 release, but a comment there contained the "fix" for me: https://github.com/xbmc/xbmc/pull/17676#issuecomment-613383656

Created a new certificate with CN=*.site.com and then it all worked as expected.
I never though Curl actually cared about the CN, when it has no chain to root certs.

Documentation said CURLE_PEER_FAILED_VERIFICATION (60): https://curl.se/libcurl/c/libcurl-errors.html
Could be usefull to know when debugging addons later on.

Closing the issue, since the fix actually exists, but has not got the love. Yet :)
