### ISSUE TITLE
Subtitle font selection does not support OpenType .otf files

### ISSUE THREAD

**Issue by unikitty37** [xbmc/xbmc#19399]
### Describe the bug
Here is a clear and concise description of what the problem is:

The subtitle font selector only shows .ttf files. As more fonts are being released as OpenType, it should also allow .otf files to be selected (and Kodi should render them correctly :)

## Expected Behaviour
Here is a clear and concise description of what was expected to happen:

When I go to `Settings > Player > Language > Font to use for text subtitles`, the list shows all .ttf and .otf files in media/Fonts.

## Actual Behaviour

When I go to `Settings > Player > Language > Font to use for text subtitles`, the list only shows the .ttf files in media/Fonts; the .otf files are not shown.

## Possible Fix

If Kodi can render .otf fonts, adding .otf to the list of permitted file extensions should suffice. I don't know enough about Kodi's font rendering to know if it can, or if it would be easy to enable — if Kodi uses the system font renderer, it might be acceptable to allow .otf on platforms that support it by default; if Kodi has its own renderer, things get more complicated quite quickly 😁 

### To Reproduce
Steps to reproduce the behaviour:

1. Copy a .ttf font file and a .otf font file into Kodi's fonts folder (`$HOME/Library/Application Support/Kodi/media/Fonts` on a Mac)
2. Start Kodi
3. Open Settings
4. Select Player
5. Set the menu preference to Standard, Advanced, or Expert
6. Select Font to use for text subtitles

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/6130996/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/139183/110960618-d6d27c00-8346-11eb-8094-0ffd62d88332.png)

![image](https://user-images.githubusercontent.com/139183/110960668-e782f200-8346-11eb-9fa8-5fd3b6806d4f.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

If I am using a font with a free licence, it may be possible to convert it from .otf to .ttf — there are any number of converters on the Internet.

If I want to use a font that I have paid for, and that is not available as a .ttf, I cannot legally do so, as the licence will not permit me to convert it to a different format (and this is assuming there's no DRM preventing this, of course).

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [X] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS 10.14.6 (18G8022)
 - Kodi version: 19.0 (19.0.0)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
Fixed by PR #20546
