### ISSUE TITLE
Temp directory path substitution doesn't work in Kodi 19.0

### ISSUE THREAD

**Issue by sunarowicz** [xbmc/xbmc#19393]
### Describe the bug
Here is a clear and concise description of what the problem is:
I want to change location of the Kodi's temp directory. After setting the path substitution in advancedsettings.xml the temp is not being relocated. Kodi recognizes the substitution, see the debuglog furher in the report, but it doesn't perform it,

I tried this on two Android devices, the TV running on Android TV 8.0 and the tablet running on Android 10. It doesn't work in neither one. I forced Kodi to stop in Android's settings and cleared its cache too. Nothing has helped.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
After setting the temp directory path substituion its content should be stored in the new location.

## Actual Behavior
The content of the temp directory is is still being made in the original location, including the log and the filecache.

## Possible Fix
Who knows?

### To Reproduce
1. Set the temp directory path substitution in advancedsettings.xml, see its content in the debuglog below.
2. Optionaly force Kodi to stop in Android settings.
3. Optionaly clear Kodi cache in Android settings.
4. Start Kodi.
5. Check where the temp content (such as log and filecache) is being created.

### Debuglog
The debuglog can be found here:
```
2021-03-11 17:12:17.224 T:11321    INFO <general>: Contents of special://profile/advancedsettings.xml are...
                                                   <advancedsettings>
                                                     <cache>
                                                       <buffermode>1</buffermode>
                                                       <memorysize>0</memorysize>
                                                       <readfactor>30</readfactor>
                                                     </cache>
                                                     <pathsubstitution>
                                                       <substitute>
                                                         <from>special://temp/</from>
                                                         <to>/storage/emulated/0/Download/temp/</to>
                                                       </substitute>
                                                     </pathsubstitution>
                                                   </advancedsettings>

2021-03-11 17:12:17.224 T:11321   DEBUG <general>: Configuring path substitutions
2021-03-11 17:12:17.224 T:11321   DEBUG <general>:   Registering substitution pair:
2021-03-11 17:12:17.225 T:11321   DEBUG <general>:     From: [/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
/temp/]
2021-03-11 17:12:17.225 T:11321   DEBUG <general>:     To:   [/storage/emulated/0/Download/temp/]
2021-03-11 17:12:17.225 T:11321 WARNING <CSettingsManager>: missing version attribute
```
There are no other lines regarding the path substitution in the log.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 8.0 and Android 10
 - Kodi version: 19.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
The temp-folder is already needed by Kodi before the advancedsettings.xml is read. Therefore path-substituting the temp folder is currently not supported for this purpose. I can only speak for Linux, where users are able to set an environment variable `KODI_TEMP=/some/path/` before Kodi sartup to tell Kodi to use another directory for the `temp`-folder. But I cannot say how  to do that for Android. 

You might probably be able to use ADB and symlink that folder to another location. 

But regarding pathsubstitution and this the issue reported here, that's currently not supported and therefore a feature request which should be submitted to the forums.

**Comment by sunarowicz** [comment]
Thank you for the info. It's a pity that this important information is not published in the right place in Wiki: https://kodi.wiki/view/Path_substitution.

**Comment by DaVukovic** [comment]
Well, it kind of is:

> Not all special paths can be substituted.

But I agree, that tthe info could be extended. Feel free to create a Wiki-account and help us getting our docs more informative.

**Comment by wsnipex** [comment]
reopening, since a fix is available
