### ISSUE TITLE
[Estuary] VideoPlayer OSD unable to display 4-digit channel numbers without truncation

### ISSUE THREAD

**Issue by djp952** [xbmc/xbmc#19400]
### Describe the bug
Here is a clear and concise description of what the problem is:

First off, I apologize for not noticing this when I wrote up Issue https://github.com/xbmc/xbmc/issues/19214.  It's basically the same concern, just in a different place.

During playback of a PVR channel with a 4-digit channel number, the OSD will truncate that number with a "...", obfuscating the actual channel number.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expected Matrix to display all 4 digits of the channel number.  As you will see from the screen shot below, the use of "..." to truncate the channel number obscures it to the point that it's not usable.

## Actual Behavior
Channel numbers are truncated with a "..."; obfuscating half of the actual channel number.

## Possible Fix
Very likely an easy width tweak to the XML as was done in PR https://github.com/xbmc/xbmc/pull/19220. Suggest assuming the same "worst case" channel number of "888.8" as that PR did (Thank you again for that change ksooo!).  I cause enough problems for you guys, I'd probably just screw up the skin with a PR :)

### To Reproduce
1. Install a PVR addon that supports backend channel numbers greater than 999
2. Enable "Use channel numbers from backend"
3. Observe skin behavior for channels with 4-digit (or more) channel numbers

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/ganixosema.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

![osd-channelnumber](https://user-images.githubusercontent.com/706055/111018666-21281d00-8388-11eb-82ee-203969b5d2c4.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: (19.0 (19.0.0) Git:20210218-f44fdfbf67). Platform: Windows NT x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
@djp952 Fix is to increase the value in this line https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/DialogSeekBar.xml#L273

Maybe you find the time for a PR for both master and Matrix?

**Comment by djp952** [comment]
Will do this evening!  Thanks so much @ksooo for the location.

**Comment by djp952** [comment]
Pull Requests to resolve Issue have been merged both master and Matrix; Issue is no longer an Issue.
