### ISSUE TITLE
Touchscreens not working in skins with wraplists home menu in Matrix

### ISSUE THREAD

**Issue by manfeed** [xbmc/xbmc#19406]
### Describe the bug
Here is a clear and concise description of what the problem is:
Touchscreens are not working anymore in skins with wraplists home menu in Matrix

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
You should be able to select any option in a skin with a wraplist home menu.

## Actual Behavior
You can move the wraplist, but you can't select any item but the one that the skin starts in.

### To Reproduce

*** CAUTION, THESE STEPS CAN FORCE YOU TO UNINSTALL KODI ***
1. Install Aeon Tajo or Aeon Nox Silvo in a device with touchscreen.
2. The home menu can be moved, but you will be unable to select any option so you will be unable to change the skin again and even to exit Kodi properly.
3. Edit line 72 of Includes_Home.xml in Aeon Tajo, and change from wraplist to fixedlist. Then it will work ok.
4. As an additional proof, you can install Amber skin; since it uses a fixedlist home menu it works well right from the start.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19 - Matrix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Can confirm this problem.

Tried on a Samsung Tablet. Moving the home menu works, but the focus stays on the item which was selected by default.

This does not happen with Aeon Tajo installed on something where one is able to use a remote or a keyboard. 

@manfeed did the problem also exist on touchscreen device prior to Kodi 19? 

I'm curious if that's a general problem with wraplists on touchscreen devices.

**Comment by manfeed** [comment]
In Leia everything was fine. There has been previous issues with wraplists under Matrix before, due to some changes in the Kodi code, so I suppose this is a bug that went unnoticed until now...

**Comment by enen92** [comment]
Regression candidates:
https://github.com/xbmc/xbmc/pull/17548
https://github.com/xbmc/xbmc/pull/18683
