### ISSUE TITLE
upnp services are not being discovered on v19

### ISSUE THREAD

**Issue by txtsd** [xbmc/xbmc#19401]
### Describe the bug
I run a minidlna upnp server on my desktop so I can watch anime etc on Kodi on my FireTV Stick.
The last time I used this on v18.x, everything worked fine.
With v19 though, the upnp service does not show up when I try to Browse. I tried running the service with gerbera instead of minidlna, and it still does not show up.
Both show up correctly in upnp browsers like VLC on my phone, other computers and also an LG WebOS TV on the same network.

## Expected Behavior
upnp servers should work and be discovered correctly.

## Actual Behavior
No upnp server is discovered when browsing for it.

### To Reproduce

1. Setup a upnp server, either minidlna or gerbera, on your system
2. Try to Browse for upnp servers in Kodi
3. Fail to see any upnp services

### Debuglog

Not sure how to generate a Kodi log. Should I just `adb logcat` the FireTV Stick?

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux
 - Kodi version: v19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Can you test if issue still exist in v21 beta2?

https://mirrors.kodi.tv/releases/

**Comment by txtsd** [comment]
I had to actually turn on UPNP inside Kodi. It is off by default.
