### ISSUE TITLE
Playback issues

### ISSUE THREAD

**Issue by setupio** [xbmc/xbmc#19419]
### Describe the bug
Just another playback issues for some .ts file:
- video/audio playback is stopped and sometimes resumed after long (even 30 sec) delay, frames dropping and incorrect audio sync are observed
- rewind (by left/right buttons) does not work as expected (the desired playback position is not set and the actual position is set somewhere, the thumb position is always set to 0)
### To Reproduce

Play [the sample](https://www.mediafire.com/file/pktjw5a3tnsx9e4/Short.ts/file), try to rewind it to the middle.

### Debuglog

http://paste.kodi.tv/uxagatoxag

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 9.0
 - Kodi version: 19.0
 - Hardware: Mi Box S
(.ts file structure is ok according TS-Doctor's check)

**Comment by BergerBlancSuisse** [comment]
i can confirm frames dropping.
nv shield tv pro + fire tv cube.
test video from above.
