### ISSUE TITLE
Cannot increase playback speed (tempoup, tempodown functions) in Kodi 19.0

### ISSUE THREAD

**Issue by ironman771** [xbmc/xbmc#19437]
### Describe the bug
It is impossible to increase the playback speed (more than 1x with audio) because the "Sync playback to display" setting is no longer present.
This is one of the most important functions for me!

## Possible Fix
Restore the "Sync playback to display" setting

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [x] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.0

**Comment by lrusak** [comment]
Please use the forums for support. Thanks.

https://kodi.wiki/view/Settings/Player/Videos#Sync_playback_to_display

**Comment by terxw** [comment]
The problem is that although on wiki pave you linked https://kodi.wiki/view/Settings/Player/Videos#Sync_playback_to_display is the setting described, in the kodi 19 this setting does not exiws in menu even in expert mode

**Comment by lrusak** [comment]
> The problem is that although on wiki pave you linked https://kodi.wiki/view/Settings/Player/Videos#Sync_playback_to_display is the setting described, in the kodi 19 this setting does not exiws in menu even in expert mode

This setting doesn't exist for kodi-gbm.
