### ISSUE TITLE
Kodi Matrix (V19): Fast Forwarding when sound is AAC causes picture freeze

### ISSUE THREAD

**Issue by Stormlord777** [xbmc/xbmc#19436]
### Describe the bug
Here is a clear and concise description of what the problem is:

I installed the new kodi matrix (V19 release version) and when I do a fast forward (x2 - X32) and then stop the fast forwarding and go back to normal speed the picture freezes and nothing is happing any more.
Some extra info: I did a clean install of Kodi matrix no extra plugins and default skin. Only setting that I changed was sound PassThrough (tried it with both on and off and result gave both the same issue)

The issue only occur when the movie or tv-show has AAC (Advanced Audio Codec Low Complexity) sound. When the movie/tv-show has Dolby Digital, Dolby TrueHD or DTS-HD Master Audio and then fast forwarding the issue does not occur.
So it looks to be related to the AAC sound (numer of channels doesn't matter).

Installation was done on both Normal Nvidia Shield TV (2017) and the Pro (2019). On both the issue was present. When I look in the log 

2021-03-11 13:47:31.319 T:8013    DEBUG <general>: ------ Window Init (Custom_1109_TopBarOverlay.xml) ------
2021-03-11 13:47:31.328 T:8072    DEBUG <general>: CDVDAudio:Tongueause - pausing audio stream
2021-03-11 13:47:31.392 T:8071  WARNING <general>: Skipped 3 duplicate messages..
2021-03-11 13:47:31.392 T:8071  WARNING <general>: OutputPicture - timeout waiting for buffer
2021-03-11 13:47:31.393 T:8071    DEBUG <general>: CPtsTracker: pattern lost on diff 0.000000, number of losses 1
2021-03-11 13:47:31.393 T:8071  WARNING <general>: OutputPicture - timeout waiting for buffer
..
2021-03-11 13:47:37.456 T:8018  WARNING <general>: ActiveAE - large audio sync error: 183203.969896
2021-03-11 13:47:37.476 T:8018  WARNING <general>: ActiveAE - large audio sync error: 183185.942518
2021-03-11 13:47:37.496 T:8071    DEBUG <general>: CDVDVideoCodecAndroidMediaCodec::SignalEndOfStream: state: 3
2021-03-11 13:47:37.496 T:8071    DEBUG <general>: CDVDVideoCodecAndroidMediaCodec::SignalEndOfStream: ReleaseMediaCodecBuffers
2021-03-11 13:47:37.496 T:8071    DEBUG <general>: CDVDVideoCodecAndroidMediaCodec::SignalEndOfStream: BUFFER_FLAG_END_OF_STREAM send
 
Info of one of the movies sound (AAC):
Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 1 h 45 min
Duration_LastFrame                       : -11 ms
Bit rate mode                            : Constant
Bit rate                                 : 224 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 169 MiB (10%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1
Encoded date                             : UTC 2021-03-08 12:21:41
Tagged date                              : UTC 2021-03-08 12:21:41

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After fast forwarding and resuming normal speed playback I assume the picture not to freeze and start playing again with 1 speed

## Actual Behavior

After fast forwarding and resuming normal speed playback the picture freezes and I need to stop playback

## Possible Fix

Workaround (but no really) is press stop and play again

### To Reproduce

1. Start Movie of TV-show
2. Press Fast Forward (Play back at 4,8,16 or speed
3. Press the normal play button again to resume normal 1 speed ==> Now picture freezes

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/uvopugovor.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

N.A.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 19.0 Matrix on Nvidia Shield TV (2017) and Nvidia Shield TV Pro (2019)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by weichenw** [comment]
Hello,
I had the same problem. Kodi 19 running on Nvidia Shield 2017. This is driving me insane cant fast forward at all.
Hope they get this fix soon.

**Comment by perseus177** [comment]
I have same problem

**Comment by berenddeschouwer** [comment]
Same problem on Linux/Arm/Pi

If I rewind, I get stuck on where the video started.  If it started new, rewind for more than a few seconds ends up at timestamp 00:00 (frozen), if I started 10 minutes in, play to 15 minutes, rewind skips to 10:00 and freezes.

**Comment by Punchbuggy0** [comment]
+1 for this issue. Can no longer forward or rewind videos in Matrix with playback integrity being maintained on my nVidia Shield.

**Comment by shota2021** [comment]
This happens to me also with Matrix 19.0 and 19.1 when I rewind after resuming a move with AAC (Advanced Audio Codec Low Complexity) sound.  Disabeling hardware acceleration is a temporary fix.

**Comment by ohnggni** [comment]
Same here in tvOS.

**Comment by JDChacho** [comment]
Same here on FireTV Box - went back to 18.3 - no problems 

Merry Xmas

**Comment by enen92** [comment]
@JDChacho @ohnggni and others, any way you can check if the issue also happens with the patch of the above PR (https://github.com/xbmc/xbmc/pull/20744)? I can trigger a test build if needed (let me know the platforms)

**Comment by matthuisman** [comment]
@enen92 
Test builds of Matrix for Android would be amazing. I guess you'd need to do the backport PR and then test build against that?

I just know more users will be willing to test with a 19 build than 20

**Comment by ohnggni** [comment]
@enen92
Please provide us with the test build. My platform is tvOS.

**Comment by enen92** [comment]
@matthuisman 

Matrix android arm: https://mirrors.kodi.tv/test-builds/android/arm/kodi-20211229-d9821d74-PR20745-merge-armeabi-v7a.apk

Matrix Android arm64: https://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20211229-d9821d74-PR20745-merge-arm64-v8a.apk

Regarding tvos test builds I am not sure if we can generate some sort of installable package users can simply install. Maybe @fuzzard or @kambala-decapitator can help there

**Comment by Stormlord777** [comment]
@enen92 
Ok I did some testing on the Matrix Android arm64 version and the issues that I reported seem to be solved. Focus of the test was AAC (Advanced Audio Codec Low Complexity) for 5.1 and 2.0 speaker set up. After Fast forwarding (32X) and than resuming to normal playback does not shown freezing of the picture any more. Both sound and video when returning to normal play are ok.

I also tried the following sound formats which didn't have the freeze issue before just to be sure that they are also ok. Tested formats:
-  Dolby Digital (5.1)
-  Dolby TrueHD (5.1/7.1/Atmos)
- DTS (5.1)
- DTS HD Master (5.1/DTS-X)

So nice job. This issue really stopped me from moving from Leia to Matrix.

**Comment by enen92** [comment]
Thanks @Stormlord777 for confirming the fix. Set thanks nexthop to @FernetMenta as he was the patch author, I was merely a proxy :)
Patch has been merged into Nexus and backported to Matrix.
Closing

**Comment by JDChacho** [comment]
sorry. No changes here on Android. still not able to search or do a fast Forward.

**Comment by JDChacho** [comment]
Sorry Folks. but I am still having problems mentioned above, starting with kodi 19...

**Comment by gareth5506** [comment]
I'm having the same problem. I'm using a Nvidia Shield tube. Kodi 18 was fine, but since installing a clean install of 19, I've been having the problem. I've installed every incremental update right up to the current 19.3, but still get the issue.

**Comment by JDChacho** [comment]
Hi Gareth, I took a nightly build and now it's working. Maybe you give it a try!

https://mirrors.kodi.tv/nightlies/android/arm/Matrix/ 

Cheers,

Chacho

**Comment by gareth5506** [comment]
> Hi Gareth, I took a nightly build and now it's working. Maybe you give it a try!
> 
> https://mirrors.kodi.tv/nightlies/android/arm/Matrix/
> 
> Cheers,
> 
> Chacho

Thank you but I don't use any builds.

**Comment by gareth5506** [comment]
It seems that it was a MP4 issue. MKV's work perfectly.

**Comment by ge2301** [comment]
Same issue, one year later with Nexus 20.2
