### ISSUE TITLE
No longer can select view type for media folders of type "none." 

### ISSUE THREAD

**Issue by glenviewjeff** [xbmc/xbmc#19433]
Here is a clear and concise description of what the problem is:

No longer can select view type for media folders of type "none." Workaround is to specify "movies" type, then select no scraper.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Until a recent update, users could change the view type for folders with media type "none". I can't think of any reason why I wouldn't want to be able to do this. 

## Actual Behavior

View type option is removed from the options menu.

### To Reproduce
1.  Create a new media folder that has a video in it 
2.  Add the folder it to Kodi's videos section
3.  Set content type as "none"
4. Go to the folder in Kodi that you created and open the options menu on the left and notice that there is no viewtype option.

**Comment by ronie** [comment]
i'm not sure which view types used to be available before, but it would make sense to make at least a wall type view available.

**Comment by ronie** [comment]
https://github.com/xbmc/xbmc/pull/19477
