### ISSUE TITLE
Crash when searching for Addons

### ISSUE THREAD

**Issue by large** [xbmc/xbmc#19449]
### Describe the bug
When searching for Addons, Kodi crash (closes itself)

## Expected Behavior
Expect to it not to crash, but give a zero hits or possible hits.

## Actual Behavior
If you do a search like "testsearch" it return zero results
But crashes on "motr"

## Possible Fix
Possible a exception not handeled in the database, it crashes after this
2021-03-21 12:05:55.870 T:3500    DEBUG <general>: ADDON::CAddonDatabase::Search query: SELECT id FROM addons WHERE name LIKE '%motr%' OR summary LIKE '%motr%' OR description LIKE '%motr%'

### To Reproduce
1. Navigate to Settings -> Addons -> Search
2. Enter search criteria: motr
3. Press "OK"
4. Kodi crashes

### Debuglog
[kodi.log](https://github.com/xbmc/xbmc/files/6177260/kodi.log)
[kodicrashlog.zip](https://github.com/xbmc/xbmc/files/6177261/kodicrashlog.zip)

### Screenshots 
NA

## Additional context or screenshots (if appropriate)
I developed a addon lately called script.motr, that is why I search it.
All other manually installed version of motr is removed (but settings kept).

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Matrix, offical release. Also tried nightly release with same result

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by dst27** [comment]
I have the same issue, recently updated to 19.0 Matrix from 18.9 Leia.

**Comment by howie-f** [comment]
ive tried to reproduce this about a week ago, it worked. was a fresh windows install with matrix.
i suspect this is once again our known busy spinner issue which is really hard to track down and fix unfortunately. 😕

@dst27 can you also provide a debug log of the crash in a pastebin, please?

**Comment by dst27** [comment]
> 
> 
> ive tried to reproduce this about a week ago, it worked. was a fresh windows install with matrix.
> i suspect this is once again our known busy spinner issue which is really hard to track down and fix unfortunately. 😕
> 
> @dst27 can you also provide a debug log of the crash in a pastebin, please?

Sure! https://paste.kodi.tv/azeguxatus.kodi

Thanks for looking into it.

**Comment by howie-f** [comment]
sadly no chance to reproduce, this time Windows 10 Pro 20H2 Build 19042.906 with Kodi Matrix new install, not upgraded.

![VirtualBox_Win10_05_04_2021_13_44_37](https://user-images.githubusercontent.com/58829855/113571511-cb593480-9616-11eb-8443-05a1a01ba47f.png)

![VirtualBox_Win10_05_04_2021_13_44_53](https://user-images.githubusercontent.com/58829855/113571519-d318d900-9616-11eb-8406-5e5accc35ac2.png)

all i can suggest now is to backup and rename `Addons33.db` at `Users\xyz\AppData\Roaming\Kodi\userdata\Database` and let Kodi recreate it on startup. maybe the database got corrupted at migration v18 -> v19..

sorry, i'm out of further ideas
fyi @enen92

**Comment by howie-f** [comment]
@large @dst27 can you maybe check if recreating the `Addons33.db` solves this issue for you?

**Comment by large** [comment]
> @large @dst27 can you maybe check if recreating the `Addons33.db` solves this issue for you?

I will give it a go, but my computer has crashed. It is plausible that the db version is the issue. And when I tested it MOTR pr wasn't implemented. Tried on my Nvidia Shield and it did not failed there.

I guess we will let the bug slide this time :-)

**Comment by enen92** [comment]
@large were you able to test this after recreating the addons db?

**Comment by large** [comment]
@enen92 I was not able to reproduce this error on my fresh install of windows.
