### ISSUE TITLE
Beautifulsoup4 problem on Kodi18

### ISSUE THREAD

**Issue by Testato** [xbmc/xbmc#19455]
Last version of Beautifulsoup4, ver 4.9.3, added only yesterday to the Official Kodi repo have some problem on the Soupsieve integration:

`ERROR: /home/ubuntuk/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.`

By reinstall the old version of BS4, ver 4.6.2, there is no problem.

The BeautifulSoup4 is upgraded yesterday, probably many other people will have this problem
https://mirrors.kodi.tv/addons/leia/script.module.beautifulsoup4/

For a simple reproduction of the problem  you can install from the official kodi repo the plugin "LA7/LAd" and choose LA7prime ---> LA7prime

**Comment by enen92** [comment]
Thanks for the heads up, fixed in the PR above ^^
