### ISSUE TITLE
Categories bar automatically slides to the right until the end for movies and TV series

### ISSUE THREAD

**Issue by rainman74** [xbmc/xbmc#19456]
### Describe the bug

If the addon Embuary Info is installed and active, the categories bar automatically slides to the right until the end!

## Expected Behavior

Categories bar always starts at the first category

## Actual Behavior

Categories bar automatically slides to the right until the end for movies and TV series.

## Possible Fix

To be fixed by the developers

### To Reproduce
1. install the addon Embuary Info
2. restart Kodi
3. select movies and TV series (activate only)
4. watch the category bar, which is slipped to the right side
5. deactivate the addon Embuary Info
2. restart Kodi
3. select movies and TV series (activate only)
4. the category bar starts correctly at the first entry again

### Debuglog

The debuglog can be found here:

Not relevant

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://i.imgur.com/PZmbtqk.png
https://i.imgur.com/czHdcsP.png

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19 Final

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ronie** [comment]
no debuglog provided

**Comment by rainman74** [comment]
> no debuglog provided

A debug log because due to a bug the interface slides to the right?

Seriously? I'm not aware of automatic slides of interface elements being recorded in a debug log.

**Comment by ronie** [comment]
ok

**Comment by rainman74** [comment]
> ok

😂😂😂 Was bist Du denn für einer? Ich werden Deine Aktion an das Kodi-Team melden! Ich versuche hier auf Bugs aufmerksam zu machen, und Du schließt die einfach, obwohl ein Debug Log hier rein gar nichts bringen würde. Ich habe extra Screenshots gemacht, um das Fehlverhalten am besten zu dokumentieren!

**Comment by rainman74** [comment]
This bug was unjustifiably closed by @ronie, although this misbehavior would not be apparent in the debug log. Here is my official complaint against this action.

@MartijnKaijser @natethomas @pike2k

**Comment by MartijnKaijser** [comment]
Debug log contains additional information we might need. So ronie is correct
