### ISSUE TITLE
No sound after fast forward for 10 to 15sec - Kodi 18.x to 20 nightlies

### ISSUE THREAD

**Issue by Ratshoro1** [xbmc/xbmc#19454]
### Describe the bug
I'm used to watching some movies/shows with a lot of fast forward in between scenes and with 17.6 sound would come back after resuming normal speed within 1-2 sec.
Since 18.0, sound doesn't come back until 10 to 15 seconds after resuming normal playback.
I have no stuttering, lag or bug otherwise and this didn't exist on 17.6 (same files tested etc).
This was tested on 3 differents computers (XPS 9360, old 3570k, R5 3600X) with local files and with emby for Kodi files.
Kodi 19.0 seems so nice and i'd love to upgrade but i can't watch some (god awful i admit) shows without.
Any idea on how to tackle this problem ?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Resume seeking with audio

## Actual Behavior
Instead audio seems to be buffering and resume 10 to 15 seconds later.

### To Reproduce

1. Open stream
2. Fast forward for 3 to 5 seconds
3. Resume playback

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/fodimeroxi.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18x to 20.0 nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fraee** [comment]
I have the same problem. I turned on the audio direct output option to use my amplifier. I don't know if it is related to this setting

**Comment by peterhorsley** [comment]
Same issue for me on 19.0 on Windows 10.

**Comment by malard** [comment]
assuming resolved, re-open if not
