### ISSUE TITLE
TVs own remote doesn't work

### ISSUE THREAD

**Issue by PaulBags** [xbmc/xbmc#19468]
### Describe the bug
Here is a clear and concise description of what the problem is:

Fresh install on android tv, tvs own remote doesn't work and "new controller detected" message displays with no way to interact with it.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The included tv remote for the tv should work - in any app.

## Actual Behavior

Kodi doesn't work

## Possible Fix

Make kodi work

### To Reproduce

1. Install Kodi
2. Remote doesn't work
3.

### Debuglog

The debuglog can be found here:
Can't access, can't interact with kodi whatsoever

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

Veon 58" android smart tv
 - [ X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: android tv 9
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please use the forum for support. Thanks.

**Comment by PaulBags** [comment]
Well that's rude, Kodi comes with the TV it should work out of the box - that it doesn't is a bug.

**Comment by lrusak** [comment]
> Well that's rude, Kodi comes with the TV it should work out of the box - that it doesn't is a bug.

Sounds like you were scammed and should ask for a refund.

**Comment by PaulBags** [comment]
Explain to me how specifically and only your app would reject the TVs own remote and maybe I'll consider it.

**Comment by HitcherUK** [comment]
> Kodi comes with the TV

Kodi doesn't come with any TV.

**Comment by PaulBags** [comment]
Android offers to install it during set up. A fresh install from the play store, clearing data first, does the same thing.

There's no CEC or anything involved. The TVs own remote should Just Work, I don't know why - or even how - Kodi would ignore it.
