### ISSUE TITLE
RFC: improve program info window size

### ISSUE THREAD

**Issue by sixpack58** [xbmc/xbmc#19474]
## Bug report
it's not a bug, it's an **RFC** to improve usability

## Expected Behavior
lower or only one keystroke to get the running program info

## Actual Behavior
pressing "I"-Key during an running channel leads to an -for my taste- too small box (on the right side), even when the text is to long/big. (see screenshot [sorry for bad quality])
if the text/info is too big for the box I first need to move to the box and then need to scroll in it.

### Screenshots 
Here is a screenshots to help explain the problem:
![IMG_20210325_183623](https://user-images.githubusercontent.com/62471898/112519342-91786a80-8d9a-11eb-810d-0bff8014c7f9.jpg)

### Your Environment
Used Operating system:
 - [x] All (?)
 - Operating system version/name:
 - Kodi version: 9.2.x, ...

**Comment by enen92** [comment]
Please use the forum for discussion

**Comment by ksooo** [comment]
You could activate "auto scroll text" in the skin settings to save some clicks.

I do agree that the icon to the left is huge and in case you don't have a channel logo (like in your screen shot) it is completely useless.

The original idea was to display a thumbnail of the running programme, but this has to be supported by the PVR add-on you are using. Most of the addons don't. For a thumbnail the chosen icon size would be okay.
