### ISSUE TITLE
no video playback with software render and without DXVA2 hardware acceleration

### ISSUE THREAD

**Issue by fayer3** [xbmc/xbmc#19480]
### Describe the bug
Here is a clear and concise description of what the problem is:

Setting the video render method to 'Software' and disabling 'DXVA2 hardware acceleration', results in a black screen when trying to play a video.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The video should be shown and play normally.

## Actual Behavior

A black screen is shown, and only audio is played.

### To Reproduce

1. Set "Settings->Player->Video->Render method" to "Software"
2. disable "Settings->Player->Video->Allow hardware acceleration - DXVA2"
3. play any video

### Debuglog

The debuglog can be found here:
[kodi_no_video.log](https://github.com/xbmc/xbmc/files/6216034/kodi_no_video.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

set Settings: 
![screenshot00005](https://user-images.githubusercontent.com/8282299/112728104-d977c880-8f25-11eb-9449-11b453baec94.png)
player info with black screen: 
![screenshot00006](https://user-images.githubusercontent.com/8282299/112728120-eb596b80-8f25-11eb-8c1e-13ac179520e5.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 20H2, Build 19042.867
 - Kodi version: 19.0 Git:20210218-f44fdfbf67

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
I have been able to reproduce the issue and also have a good solution. Try this build:

https://www.mediafire.com/file/5j7v8z792871b1y/KodiSetup-20210329-d7f8d39c-Matrix-x64.exe/file

I prefer a double check to be sure. Once you confirm that it works well on your side, I will upload a PR.

**Comment by fayer3** [comment]
works for me
