### ISSUE TITLE
Kodi 19.0 readtimeout error when login/password and not able to login using auth key (2021.04)

### ISSUE THREAD

**Issue by mironko** [xbmc/xbmc#19502]
### Describe the bug

**It just stopped to login.  this is the key problem
When I tried to login using authentication  key from NF_Authentication.key file and putting a 4 digit key  and my netflix password it says:
Exception: KeyError
Error details: 'loco'**

Here is a clear and concise description of what the problem is:

**this worked before.
Tried to reinstall kodi by deleting and installing from repository - didn't help. Have log file will attach below**

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Should log in

## Actual Behavior

loco error

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
19.0 matrix
[kodi.log](https://github.com/xbmc/xbmc/files/6246348/kodi.log)
[kodi.old.log](https://github.com/xbmc/xbmc/files/6246349/kodi.old.log)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
It's an add-on issue, not a core issue. I believe @CastagnaIT is working on a fix. Probably best to check forums, or the git repo for the addon
