### ISSUE TITLE
Add-on python play callback (xbmcplugin.setResolvedUrl) with playlist happen only if not resolved (first time)

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#19529]
### Describe the bug
Here is a clear and concise description of what the problem is:

An user has report to me this problem,
which in fact after some testing, i have seen that it is causing problems with many addons.

Basically when you are playing a video playlist, and you try to play again the previously played items (previously partially or in full played) Kodi avoids to re-call the addon again (to resolve again the ListItem `xbmcplugin.setResolvedUrl`) because "cached" previously.

But this behaviour currently is breaking the features of many addons, because most of the time each addon use this
callback not only to provide the ListItem to play with `xbmcplugin.setResolvedUrl` but also to execute some code (needed before or after Kodi full execute the video) or/and to keep track of some things when a user play a video.

I can understand that in the past this "caching?" system, could have been useful perhaps to save execution time (?),
but at today video addons makes it essential to always have these callbacks consistent,
have a slightly longer execution time (usually we are talking of ms) is certainly not a problem.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Have an addon (setResolvedUrl) callback in any case,
to allow every addon to execute his internal things

## Actual Behavior

If you try to play a previously played item in playlist,
the addon will never be called and this break addon features

## Possible Fix

PR #19530

### To Reproduce

This can be tested with any VOD or generic video add-on:
1. Edit the addon source code, to place a Log print in the play callback method with `xbmcplugin.setResolvedUrl` (to keep track in easy way when the callback happen when we play a video, or else you can also see if there is the python instance execution)
2. Open and browse the addon folder on a list of videos
3. Open the context menu on the first video and select `Play from here` to create/play a playlist
4. (while is in playing the first video) open the playlist and select/play the second video
5. (while is in playing the second video) skip the video time to the middle
6. (while is in playing the second video) open the playlist and select/play the first video (again)
7. (while is in playing the first video) open the playlist and select/play the second video (again)

In the 7th point the addon callback not happen anymore because the item was previously played, this is the problem

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/puxodejule.kodi

from the log you can see the missing CPythonInvoker in the last played video (previously already played)
and so the missing "ADD-ON PLAY CALLBACK for  video index: 1" log print

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Kodi 19 and 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MoojMidge** [comment]
@CastagnaIT as mentioned before, this issue doesn't only effect playlists, even playing from a plugin directory listing can trigger the same issue. To replicate the problem, see below. 

Correct operation:
1. Start a video from a plugin directory listing
2. Stop video half way
3. Return to directory listing
4. Play video again
5. Everything works as it should

Buggy operation:
1. Start a video from a plugin directory listing
2. Skip to half way point in video
3. Return to directory listing
4. Stop video
5. Play video again
6. Cached resolved url is used rather than resolving the plugin path

**Comment by CastagnaIT** [comment]
This can be closed and marked as solved
the PR has been merged
