### ISSUE TITLE
Minimum opengl version for kodi 19 under linux

### ISSUE THREAD

**Issue by pitsi** [xbmc/xbmc#19521]
## Bug report
I have an old laptop with a libreelec installation since early July 2019. I think it started with kodi 18.2 back then and it has been successfully updated all the way to kodi 18.9 (libreelec 9.2.6). It has this gpu
`00:02.0 VGA compatible controller: Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller (rev 09)`
which according to glxinfo supports up to opengl 2.1.
```
# glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Mobile Intel GM45 Express Chipset
OpenGL version string: 2.1 Mesa 19.1.7
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 19.1.7
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```
When libreelec 10 with kodi 19 was released, I decided to upgrade it a few days after the official release. The upgrade was completed as usual, but kodi did not launch. There was only a cursor in a black screen and nothing more. I could connect to it via ssh and systemctl status kodi was showing kodi was indeed running, although it was not visible.
Because I need kodi everyday, I downgraded to 9.2.6 and restored my backup, so now it is working again, although it is still on 18.9. Then I thought it may have been some existing configuration that broke something, so I downloaded the image and "burned" it on a usb stick to try it through the live option. And the result was the same.

Then I borrowed an old netbook (amd c-50, ati 6250 gpu), tried the same usb stick there and it booted just fine, showing kodi 19, the first run wizard of libreelec etc.

## Expected Behavior
Kodi 19 should show up after the boot of libreelec 10 as an os.

## Actual Behavior
Kodi 19 does not show up, although libreelec 10 boots properly. There is just a blank screen with a mouse cursor in the middle.

## Possible Fix
No idea, but the info I ask for at the title will shed some light to the situation.

### To Reproduce
1. Find an equally old laptop or desktop system with a similar gpu.
2. Download the x64 image of libreelec 10b1 and burn it on a usb stick with any app (the one that libreelec provides or rufus etc)
3. Boot from it and select the live option (default one).

### Debuglog
Since there is no access via ssh, because ssh is disabled by default on libreelec, or even a tty, there is no log or anything similar I can access. 

### Screenshots 
None. Just a black screen with a cursor in the middle.

## Additional context or screenshots (if appropriate)
None.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Libreelec 10 beta1
 - Kodi version: 19.0

**Comment by lrusak** [comment]
Although Kodi should work on OpenGL 2 it's rarely tested. We would need to see a debug log in order to debug further.

It may be difficult to do that though on a non functioning system. You would have to enable debug logging, then restart kodi, then get a debug log.

on LibreELEC this would roughly be
```
echo 'KODI_DEBUG="--debug"' >> /storage/.config/kodi.conf
```
restart kodi
```
systemctl restart kodi.service
```
get log
```
cat /storage/.kodi/temp/kodi.log | pastebinit
```
post url returned here.

I'm going to close this issue until a log is posted as it's difficult to debug. We can reopen if you choose to continue debugging.

**Comment by pitsi** [comment]
I will try it, although it is too hard to do. It would be better if I could just add some parameter to libreelec's boot process and enable ssh. I would connect it via ethernet again and do the rest.

Since I mentioned networking, I would like to ask one more thing. I noticed that although I connect it via ethernet when trying libreelec on live mode, the led for wireless activity goes crazy when the os reaches kodi. That is weird, because it has no ssid or key in order to connect to my wireless network. 
Does kodi need to be connected to the internet on first run? I assume yes, because it needs to somehow look for addon updates. And even then, I think it would stop after 1-2 minutes, but that does not happen. The wifi led keeps blinking even after 10+ minutes that I power it off!

**Comment by chewitt** [comment]
add "ssh" to kernel boot params in syslinux.conf and the daemon is forced to start on boot.

**Comment by pitsi** [comment]
Please be patient. After adding ssh to the live entry in syslinux.conf, I connected it via ethernet, opened putty, sshed to it and before I could type anything from the above, the system rebooted! Now it is on an bootloop :D

**Comment by pitsi** [comment]
1st attempt in getting the log straight to pastebinit. Usually, the connection drops and the system is rebooted before I even finish typing the command. That's why the log is incomplete I guess.
http://ix.io/2VbN

2nd attempt, just running cat .kodi/temp/kodi.log and grabbing the text right from putty. ALL lines that seem broken were continuing in the next line and I did select ALL of them in putty.
https://pastebin.com/GzH3sr0d

**Comment by pitsi** [comment]
Is there any other boot parameter I can try? I would be happy to even drop to a tty after boot. The ones here seem to apply to rpi images only, because there is no config.txt for x64
https://wiki.libreelec.tv/configuration/config_txt

I also found this on libreelec forums, but it leads to a 404. It may be the same as above though.
https://wiki.libreelec.tv/index.php?title=Config.txt

**Comment by lrusak** [comment]
if you can manage to login before it reboots just do
`systemctl stop kodi` and it won't force a safe mode reboot.

or to disable safe mode completely just do
```
touch /storage/.config/safemode.disable
```

**Comment by pitsi** [comment]
TIL that libreelec has a safe mode :P 
I stopped kodi.service as proposed and started it again manually. And this is what I got with `systemctl status kodi`

```
● kodi.service - Kodi Media Center
     Loaded: loaded (/usr/lib/systemd/system/kodi.service; disabled; vendor preset: disabled)
     Active: active (running) since Thu 2021-04-08 12:07:11 UTC; 1s ago
    Process: 1242 ExecStartPre=/usr/lib/kodi/kodi-config (code=exited, status=0/SUCCESS)
   Main PID: 1247 (kodi.sh)
     Memory: 152.2M
     CGroup: /system.slice/kodi.service
             ├─1247 /bin/sh /usr/lib/kodi/kodi.sh --standalone -fs
             ├─1271 /bin/sh /usr/lib/kodi/kodi.sh --standalone -fs
             └─1272 gdb /usr/lib/kodi/kodi.bin --core=/storage/.cache/cores/core.!usr!lib!kodi!kodi.bin.1617883631.1251 --

Apr 08 12:07:11 LibreELEC systemd[1]: Starting Kodi Media Center...
Apr 08 12:07:11 LibreELEC systemd[1]: Started Kodi Media Center.
Apr 08 12:07:11 LibreELEC kodi.sh[1251]: libva info: VA-API version 1.10.0
Apr 08 12:07:11 LibreELEC kodi.sh[1251]: libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
Apr 08 12:07:11 LibreELEC kodi.sh[1251]: libva info: Found init function __vaDriverInit_1_10
Apr 08 12:07:12 LibreELEC kodi.sh[1247]: Illegal instruction (core dumped)
```
Then I added the --debug parameter as suggested above and when I ran `systemctl restart kodi`, there were no issues
```
● kodi.service - Kodi Media Center
     Loaded: loaded (/usr/lib/systemd/system/kodi.service; disabled; vendor preset: disabled)
     Active: active (running) since Thu 2021-04-08 12:11:31 UTC; 100ms ago
    Process: 4277 ExecStartPre=/usr/lib/kodi/kodi-config (code=exited, status=0/SUCCESS)
   Main PID: 4283 (kodi.sh)
     Memory: 5.3M
     CGroup: /system.slice/kodi.service
             ├─4283 /bin/sh /usr/lib/kodi/kodi.sh --standalone -fs
             └─4287 /usr/lib/kodi/kodi.bin --standalone -fs

Apr 08 12:11:31 LibreELEC systemd[1]: Starting Kodi Media Center...
Apr 08 12:11:31 LibreELEC systemd[1]: kodi.service: Ignoring invalid environment assignment ''KODI_DEBUG=--debug
Apr 08 12:11:31 LibreELEC systemd[1]: ': /run/libreelec/kodi.conf
Apr 08 12:11:31 LibreELEC systemd[1]: Started Kodi Media Center.
```
Anyway, here is the log, I hope with the debug parameter enabled and after the successfull start. Still no kodi on the screen though.
http://ix.io/2Vob

**Comment by pitsi** [comment]
SInce there is no answer on my issue, and the (debug?) log is not as helpful because it containes almost the same info as the previous one, I decided to install alpine (some time this week) on a usb stick and try its kodi to see what happens.

Does this apply to regular kodi installations as well?
`echo 'KODI_DEBUG="--debug"' >> /storage/.config/kodi.conf`

**Comment by wsnipex** [comment]
the --debug switch applies, that LE config file does not.

**Comment by pitsi** [comment]
So I will have to make a ~/.config/kodi.conf and just add --debug in it. Simple.
Is there a way to tell from the log that the --debug switch was enabled/active/working?

**Comment by pitsi** [comment]
Yesterday, I was searching for a jeos with kodi for a tvbox with an amlogic s805 and I came across alexelec which is a fork of correlec (which in turn is a fork of libreelec). And I noticed that there is also a build for x64 hardware, so I decided to give it a shot. And it worked, right out of the box!

System information > video says it does use opengl 2.1 and this is what is mentioned in the log, when run under live mode obviously, so no debug option enabled.
http://ix.io/2W9k

**Comment by pitsi** [comment]
I also tried the latest nightly build of libreelec for x64, the one that was released on April 15th. Still no luck, it behaves exactly as the beta one.

**Comment by lrusak** [comment]
What does the crashlog look like? `/storage/.kodi/temp/kodi_crash.log`

**Comment by pitsi** [comment]
On the nightly? Give me a sec to disable auto reboot and I will post the log.

**Comment by lrusak** [comment]
Seems it's crashing in the iHD driver. Can you please do the following and restart kodi:
```
echo 'LIBVA_DRIVER_NAME="i965"' >> /storage/.config/kodi.conf
```

**Comment by pitsi** [comment]
IT STARTED! I bow down to your genius!
Now what? Can I assume that kodi 18/libreelec 9 did not have that driver?

**Comment by lrusak** [comment]
> IT STARTED! I bow down to your genius!
> Now what? Can I assume that kodi 18/libreelec 9 did not have that driver?

correct, it's odd that it's crashing but that's likely a bug in the driver as it's not supposed to be used on old hardware anyways

**Comment by pitsi** [comment]
Ok, so I will do all of the above in run mode and test it until the next nightly to see how it goes. If everything works as it should for a week, I will upgrade my 9.2.6 installation to 10beta1. No addons, no extra configuration, just the stuff that will make my work easier (enabling ssh, zeroconf etc). 
I assume I can configure libreelec somehow so as to get the nightly updates as well...

**Comment by lrusak** [comment]
Please continue the discussion at the LibreELEC forums as this is no longer a Kodi issue. Thanks!

**Comment by pitsi** [comment]
> Seems it's crashing in the iHD driver. Can you please do the following and restart kodi:
> 
> ```
> echo 'LIBVA_DRIVER_NAME="i965"' >> /storage/.config/kodi.conf
> ```

Does anyone know if this workaround can be applied to a kodi installation on a regular linux distro?

**Comment by fritsch** [comment]
This has nothing to do with kodi, but rather about your environment and asking the intel vaapi to use a different driver:

1.) export LIBVA_DRIVER_NAME="i965"
2.) kodi

Should work on the shell. As you run a  full blown distribution, why not uninstall the iHD driver that you don't want to use.

Example:
fritsch@L380:~$ export LIBVA_DRIVER_NAME=i965
fritsch@L380:~$ vainfo 
libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'i965'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Kaby Lake - 2.4.1
vainfo: Supported profile and entrypoints

fritsch@L380:~$ export LIBVA_DRIVER_NAME="iHD"
fritsch@L380:~$ vainfo
libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.3.1 ()
vainfo: Supported profile and entrypoints

So - properly config your distribution I'd say.

**Comment by pitsi** [comment]
My current situation is a lot more complicated than that, but thank you for the clarification :)
I did think it would be some export blablabla thing that must run before it.

**Comment by fritsch** [comment]
I showed you, that it is as simple as that by example.
