### ISSUE TITLE
French language not always fully displayed when there is \n code  in file strings.po

### ISSUE THREAD

**Issue by Nanomani** [xbmc/xbmc#19536]
### Describe the bug

French language not always fully displayed when there is \n code  in file strings.po

## Expected Behavior

The full text in French is displayed

## Actual Behavior

The full text in French is not displayed

## Possible Fix

delete "\n" code in file \addons\resource.language.fr_fr\resources\strings.po :

before

msgctxt "#20446"
msgid "Locally stored information found. Ignore and refresh from Internet?"
msgstr "Des informations existent déjà localement.\nFaut-il les ignorer et actualiser depuis Internet?"

after

msgctxt "#20446"
msgid "Locally stored information found. Ignore and refresh from Internet?"
msgstr "Des informations existent déjà localement.Faut-il les ignorer et actualiser depuis Internet?"

if I do this the full text in French is displayed

### To Reproduce

1.  chose english language in kodi
2.  from an video detail  information make a "Refresh"
3.  you see the message "Locally stored information found. Ignore and refresh from Internet?"

4.  chose french language in kodi
5. from an video detail  information make a "Refresh"
6. you see only the message "Des informations existent déjà localement."

### Screenshots 

![2021-04-08_110017](https://user-images.githubusercontent.com/3939543/114004201-b66ee200-985e-11eb-8fdb-c06140eb6000.jpg)

if english language

![2021-04-08_110050](https://user-images.githubusercontent.com/3939543/114004247-c1c20d80-985e-11eb-8933-9d01934fab7f.jpg)

if french language

![2021-04-08_110204](https://user-images.githubusercontent.com/3939543/114004265-c5559480-985e-11eb-9cdf-62bede9d2ebe.jpg)

if french language with the fix

![2021-04-08_110902](https://user-images.githubusercontent.com/3939543/114004272-c7b7ee80-985e-11eb-87c1-3066cca32cfa.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
FYI using `\n` or `\r\n` have also wrong impact with RTL languages suggest to avoid it
IMO suggest you to use the kodi text formatting:
https://kodi.wiki/view/Label_Formatting
`\n` --> [CR]

**Comment by gade01** [comment]
Thanks a lot for reporting this.

Fix pending:
https://github.com/xbmc/repo-resources/pull/125/files#diff-011aa83dd5d688544f1cc5dd1e113ca2e632c38a8ccefe5ca4969a2696d30f00

Please check if this looks correct.

**Comment by Nanomani** [comment]
Look very good for me.
all `\n` are gone.
thanks a lot :)

**Comment by gade01** [comment]
Sounds great. 

Thanks for checking.

**Comment by gade01** [comment]
The changes and fixes are pushed to the new language addons.

Thanks again for reporting this.
