### ISSUE TITLE
Is impossibility to paste text a bug or a feature?

### ISSUE THREAD

**Issue by vadiof** [xbmc/xbmc#19545]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm trying to setup Youtube addon and it requires an API key and related credentials to be inserted. But when I open an input window it is impossible to paste copied credentials(I tried Ctrl+V, Shift+Input, Right mouse button). Only manual input works. This is pretty uncomfortable and annoying since credentials are long and complicated. I wonder if this is a bug or a feature?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I am convinced pasting should work some way that is obvious and familiar for users

## Actual Behavior

Text pasting doesn't work at all or at least in a conventional way

## Possible Fix

Add paste function

### To Reproduce

1. Open Kodi
2. Install Youtube addon
3. Enter Youtube addon settings
4. Go to "API" settings section
5. Choose "API key" section
6. Input string will appear
7. Clarify no paste is impossible with standard methods

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu MATE 20.04.2
 - Kodi version: 19.0 (19.0.0) Git:20210219-f44fdfbf67 Media Center Kodi

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
I think paste only works for Windows and osx, so I'd say in the case of Linux it might be a feature

**Comment by lrusak** [comment]
You can copy paste the api key into the actual text file in the addon userdata `~/.kodi/userdata/addon_data/...`
