### ISSUE TITLE
Freezing upon exit button press. 

### ISSUE THREAD

**Issue by ashipaek0** [xbmc/xbmc#19549]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

**The app should quit normally**

## Actual Behavior

**Kodi freezes indefinitely**

### To Reproduce

1. **press the exit button**
2.
3.

### Debuglog

The debuglog can be found here:

﻿

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://imgur.com/a/lR5oX12

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

**Just trying to quit the program**

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 **- [ *] Linux**
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:     **Ubuntu 20.10**
 
 - Kodi version:   **19.0 Matrix
[kodi.log](https://github.com/xbmc/xbmc/files/6287866/kodi.log)
**

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please provide a proper bug report with log files and your issue will be reopened, Thanks!
