### ISSUE TITLE
[PVR] Unable to edit timer rules that do not support start and end times

### ISSUE THREAD

**Issue by djp952** [xbmc/xbmc#19548]
### Describe the bug
Here is a clear and concise description of what the problem is:

Users are unable to edit timer rules that do not support start and end times; regardless of the changes the user is trying to make (or just clicking OK) Kodi will raise an "In order to add/update a timer the end date and time must be greater than the start date and time." error.

This was introduced with PR https://github.com/xbmc/xbmc/pull/19056.

Given that the timer rule does not support start/end times the user has no way to correct this issue.  For reference, here are the underlying TIMER_TYPE flags for the affected timer rules:

`PVR_TIMER_TYPE_IS_REPEATING | PVR_TIMER_TYPE_SUPPORTS_CHANNELS | PVR_TIMER_TYPE_SUPPORTS_TITLE_EPG_MATCH | PVR_TIMER_TYPE_SUPPORTS_RECORD_ONLY_NEW_EPISODES | PVR_TIMER_TYPE_SUPPORTS_START_END_MARGIN | PVR_TIMER_TYPE_FORBIDS_EPG_TAG_ON_CREATE | PVR_TIMER_TYPE_SUPPORTS_ANY_CHANNEL`

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Since the start and end times are not supported by the timer rule, I don't think they should be checked.

## Actual Behavior

See above, editing the timer rule will fail with an error message.

## Possible Fix

This appears incorrect:

https://github.com/xbmc/xbmc/blob/3888019a6f8e58bb82b9db61436bc0d6bbab620e/xbmc/pvr/dialogs/GUIDialogPVRTimerSettings.cpp#L547-L550

Shouldn't all four conditions need to be true to trigger the error prompt?

```
    if (m_timerType->SupportsStartTime() &&   // has start clock entry
          m_timerType->SupportsEndTime() &&   // and end clock entry
          m_timerType->IsTimerRule() &&       // but no associated start/end day spinners
        m_endLocalTime < m_startLocalTime)    // and the end time is before start time
```

### To Reproduce

1. Have a timer rule that does not define PVR_TIMER_TYPE_SUPPORTS_START_TIME and PVR_TIMER_TYPE_SUPPORTS_END_TIME
2. Attempt to edit the timer rule via the UI

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ezivuwafus.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Untitled1](https://user-images.githubusercontent.com/706055/114197783-addee000-9920-11eb-9b25-ceb26509d04e.png)
![Untitled2](https://user-images.githubusercontent.com/706055/114197802-b2a39400-9920-11eb-8e2d-bf5706862903.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I'm happy to issue a PR if the suggested change is correct, I didn't want to jump the gun and allow @phunkyfish to have a look first to make sure that wouldn't break his original intention.  It's probably possible for the PVR addon to define arbitrary start and end times for these timer rules that would never fail the condition, but the logic does look improper to me.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 (Desktop) x64
 - Kodi version: Kodi (19.0 (19.0.0) Git:20210218-f44fdfbf67). Platform: Windows NT x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by djp952** [comment]
For what it's worth, I was able to handle this in the PVR addon.  I had been setting the start time so it would display in the GUI but not the end time since there is none.  I changed to setting start time to 0, end time to INT_MAX, and now also set PVR_WEEKDAY_ALLDAYS so the start time isn't relevant for the GUI.

I'm still thinking the possible logic error should be addressed since start time and end time are listed as optional for timers/rules.  If the logic is fine perhaps just a doc update to indicate that if one is set they both should be?

**Comment by phunkyfish** [comment]
Should you be setting start and ends any time in your timer type?

**Comment by djp952** [comment]
If I do that the user will get toggles for that in the timer rule that they can't actually use.  The backend doesn't support start/end times at all for these rules, they are generic series requests.  The user can only control Duplicate Prevention, Start/End padding and the Channel number assignment.

![Untitled](https://user-images.githubusercontent.com/706055/114235992-f7462400-994e-11eb-99b9-2ab6e153a52e.png)

I have to set the StartAny/EndAny flags in the timer rule itself to get the UI to display accurately. Up until this morning this would have said 04/09/2021 rather than "Any day".  Leaving these set and using a start time of zero and end time of INT_MAX seems to get the best of everything.

![Untitled2](https://user-images.githubusercontent.com/706055/114236243-57d56100-994f-11eb-9959-17d9416ab2b7.png)

If the logic is good, I'm good :)

**Comment by phunkyfish** [comment]
I'm not the logic is correct. I think you just have a use case I did not see before.

**Comment by djp952** [comment]
I seem to have that effect on Kodi :)  Let me describe what I got here.

HDHomeRun DVR doesn't do things like everyone else.  You can set up two types of rules, which I've called Record Series and Record Once.  For Record Series, you tell the backend what series you want to record but you can only control an optional "channel only", duplicate prevention, and the padding.  There is no concept of dates/times, the backend just records everything it finds that meets the criteria.  The Record Once is similar with the exception that it's for a one-time specific airing of a program so you can must specify the start time (but not the end time).  There is no traditional "manual timer" capability.

For the user, I put all of these rules in as Timer Rules, but only let them edit the Record Series ones due to not having a good way to edit the Record Once rules since I only have the start time.  I also expose any specific programs the backend tells me will record as child Timers for the associated Timer Rule.  The user can't edit these at all, they exist to have the proper indicators in the EPG, "Currently Recording", "Upcoming Recording", etc.

HDHomeRun gonna do what HDHomeRun gonna do, but Kodi has been able to to handle the weirdness I throw at it quite well.

**Comment by phunkyfish** [comment]
Ok, so if we want to support use all we need is a condition that only satisfies the set that your use case belongs to.

So in code:

```
 if ((!(m_timerType->SupportsStartTime() && // has start clock entry 
        m_timerType->SupportsEndTime() && // and end clock entry 
        m_timerType->IsTimerRule()) || // but no associated start/end day spinners 
    (!(your-use-case))) &&
     m_endLocalTime < m_startLocalTime) 
```

In pseudo code:

```
 if (!InUseCaseSetOne() && 
     !InUseCaseSetTwo() &&
     m_endLocalTime < m_startLocalTime) 
```

So just need your SetTwo defined.

**Comment by djp952** [comment]
I believe that would work just dandy, sir!
