### ISSUE TITLE
In "Videos / Playlists" "+ New smart playlist..." is not displayed with Android

### ISSUE THREAD

**Issue by Nanomani** [xbmc/xbmc#19547]
## Expected Behavior
In "Videos / Playlists" I expect to see option "+ New smart playlist..." for add a new one

## Actual Behavior
I see all my playlist created with a icon type "file" not type "playlist"
"+ New smart playlist..." is not displayed

This works very well with Windows (Same Kodi v19)
(see difference between Windows and android with Screenshots)

### To Reproduce

1. settings => Media =>Library => Videos => .. => Playlists

### Debuglog
The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/6286627/kodi.log)

### Screenshots 
With Windows 10 all is good

![2021-04-09_162729](https://user-images.githubusercontent.com/3939543/114195589-df6f9f80-9950-11eb-97cd-fe3c5eefc359.jpg)

With Android (Nvidia Shield Pro 2019 FW 8.2.2)  no option "+ New smart playlist..." 

![2021-04-09_155033](https://user-images.githubusercontent.com/3939543/114194323-aa168200-994f-11eb-86df-00765544c0c1.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nvidia Shield Pro 2019 v8.2.2
 - Kodi version: 19.0 final (tested also with kodi-20210406-4e6f40d8-Matrix-arm64-v8a)

**Comment by DaVukovic** [comment]
@ronie 

Does this look suspicious? 
```
2021-04-09 16:56:22.424 T:23223   DEBUG <general>: CMultiPathDirectory::GetDirectory(multipath://special%3a%2f%2fprofile%2fplaylists%2fvideo/special%3a%2f%2fprofile%2fplaylists%2fmixed/?property=/)
2021-04-09 16:56:22.425 T:23223   DEBUG <general>: Getting Directory (special://profile/playlists/video)
2021-04-09 16:56:22.450 T:23223   DEBUG <general>: Getting Directory (special://profile/playlists/mixed)
2021-04-09 16:56:22.451 T:23223   DEBUG <general>: Getting Directory (?property=)
2021-04-09 16:56:22.451 T:23223   ERROR <general>: GetDirectory - Error getting ?property=
2021-04-09 16:56:22.451 T:23223   ERROR <general>: Error Getting Directory (?property=)
```
Not sure if these errors are related
I'm not facing this issue on Linux as well. Will have a look at my shield later

**Comment by Nanomani** [comment]
I have find the pb.
If I install the addon "Library Node Editor" on Windows  the issue is the same.
Uninstall only addon "Library Node Editor" change nothing.
You must delete the folder "video" under "userdata \ library \"
sorry for the noise.

**Comment by Nanomani** [comment]
After a new test from scratch I can't reproduce that with "Library Node Editor". Definitively it is my side that there is a bad using :/
