### ISSUE TITLE
System crashes when thumbnails should be shown

### ISSUE THREAD

**Issue by frankhommes** [xbmc/xbmc#19556]
### Describe the bug
Here is a clear and concise description of what the problem is:

I do have a number of movies, some of them selfmade. They are accessed over an NFS-Share.
When I add them there is no problem. I can also watch the movies without problems.
But when I go to the root area where you can see i.e. the latest movies as a thumbnail the system reboots.
I tried it with libreelec and raspberry OS on two raspberry 4 - 4 GB RAM.
The logfiles don't give me any hints. On libreelec there is nothing in the logfiles of kodi and on raspberry OS
there is no detail about the reboot.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should run.

## Actual Behavior

An error probably with Kodi reboots the whole system.

## Possible Fix

Don't scan.

### To Reproduce

1. Scan Movies on a NFS-Share
2. Go to the root menu

### Debuglog

The debuglog can be found here:
Please tell me what logs I can put on pastebin.
/var/log/debug has no entries on that time
/var/log/syslog has no entries on that time
/var/log/kern.log has no entries on that time
I am really confused

### Screenshots 
Here are some links or screenshots to help explain the problem:

Please tell me where to find what you need and I post it on pastebin.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
 - Kodi version: kodi           2:18.7-1~buster

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
>Please tell me what logs I can put on pastebin.

Most likely we will need the Kodi debuglog: 

* install the Kodi Log Uploader add-on (it's in our repo)
* enable debug logging at the system settings
* disable everything which is not needed to reproduce your issue (automated database updates at startup, PVR etc....)
* restart Kodi (that's important. We will need the debuglog from the start)
* reproduce your issue as fast as you can (don't do anything else)
* use the Kodi Log Uploader add-on to upload the log and share the link you will see with us here
