### ISSUE TITLE
Cannot build FFmpeg for Windows UWP

### ISSUE THREAD

**Issue by diddiman** [xbmc/xbmc#19559]
### Describe the bug
Can't build FFmpeg on winodws

## Expected Behavior
I follow the instructions on https://github.com/xbmc/xbmc/blob/master/docs/README.Windows.md#6-build-kodi-manually.
And when i run make-mingwlibs.bat i expect it to complete

## Actual Behavior

It fails. The console have the following information:
```
-------------------------------------------------------------------------------
 compiling mingw libs win10-x64

 NOPROMPT  = 0
 MAKECLEAN = clean
 WORKSPACE =

-------------------------------------------------------------------------------
-------------------------------------------------
 building FFmpeg win10-x64
-------------------------------------------------
ffmpeg-4.3.2-Matrix-19.1 ..................................... [Downloading]
--2021-04-11 15:56:59--  https://github.com/xbmc/FFmpeg/archive/4.3.2-Matrix-19.1.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/xbmc/FFmpeg/tar.gz/4.3.2-Matrix-19.1 [following]
--2021-04-11 15:56:59--  https://codeload.github.com/xbmc/FFmpeg/tar.gz/4.3.2-Matrix-19.1
Resolving codeload.github.com (codeload.github.com)... 140.82.121.9
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/downloads/ffmpeg-e2ee55c4e4.tar.gz’

/downloads/ffmpeg-e2ee55c4e4.     [               <=>                                ]  12.87M  4.18MB/s    in 3.1s

2021-04-11 15:57:03 (4.18 MB/s) - ‘/downloads/ffmpeg-e2ee55c4e4.tar.gz’ saved [13490949]

ffmpeg-4.3.2-Matrix-19.1 ...................................... [Extracting]
tar.exe: Option -a is not permitted in mode -x
Applying patch /xbmc/tools/buildsteps/windows/patches/0001-ffmpeg-detect-openssl.patch
./buildhelpers.sh: line 131: patch: command not found
Applying patch /xbmc/tools/buildsteps/windows/patches/0002-ffmpeg-zlib-config-conflict.patch
./buildhelpers.sh: line 131: patch: command not found
Applying patch /xbmc/tools/buildsteps/windows/patches/0003-ffmpeg-static.patch
./buildhelpers.sh: line 131: patch: command not found
Applying patch /xbmc/tools/buildsteps/windows/patches/0005-ffmpeg-detect-dav1d.patch
./buildhelpers.sh: line 131: patch: command not found
ffmpeg-4.3.2-Matrix-19.1 (win10-x64) ......................... [Configuring]
./buildffmpeg.sh: line 124: /build/src/ffmpeg-e2ee55c4e4/configure: No such file or directory
ffmpeg-4.3.2-Matrix-19.1 (win10-x64) ........................... [Compiling]
./buildhelpers.sh: line 47: make: command not found
./buildhelpers.sh: line 48: make: command not found
ffmpeg-4.3.2-Matrix-19.1 (win10-x64) ............................... [Error]
failed to compile /xbmc/project/BuildDependencies/mingwlibs/win10-x64/lib/avcodec.lib

```

### To Reproduce

1.  Clone repo
2. download dependencies with download-dependencies.bat untill all packages are ready
3. Build FFmpeg with download-msys2.bat

### Debuglog

The debuglog can be found here:
See above

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [X] Windows UWP

 - Operating system version/name: Windows 10, home
 - Kodi version: latest on master, commit ref bff9dbbbe3b2adc59c6ad7b5edf7dc28cbb1edaf

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please use the forum or IRC channel for support. The errors are in the log about what you are missing.

**Comment by DaveTBlake** [comment]
I have just had the same experience as the OP when trying to compile ffmpeg on Win64. For some reason compiling ffmpeg on Windows is very flaky, thankfully it isn't something I need to do very often.

At a loss I repeated the following loop multiple times
- git clean -xfd
- download-dependencies.bat, 
- download-msys2.bat, 
- make-mingwlibs.bat 

After 5 attempts, with various odd errors each time, ffmpeg compiled successfully. @diddiman just keep trying.

I am reopening this in case someone oneday has the time and interest to investigate the underlying cause.

**Comment by Ryan14411** [comment]
if someone could send me it compiled i could test on a Xbox one, one s and one x

**Comment by fuzzard** [comment]
Nightly builds for all platforms can be found on the Kodi mirrors http://mirrors.kodi.tv/nightlies/windows/
