### ISSUE TITLE
xbmc.Player().SeekTime() error

### ISSUE THREAD

**Issue by Mariusz89B** [xbmc/xbmc#19562]
### Describe the bug
Here is a clear and concise description of what the problem is:

When adding float 0.0 to xbmc.Player().SeekTime() stream will stall on Android OS. I'm using .mpd streams from Telia Play. 
On Windows OS everything is working fine.

## Expected Behavior

Here is a clear and concise description of what was expected to happen:

Stream should reverse to given position, and play without stalling.

## Actual Behavior

Stream will stall.

## Possible Fix

N/A

### To Reproduce

Add-on:
https://github.com/Mariusz89B/script.mtvguide
https://github.com/Mariusz89B/script.mtvguide/blob/9.3.0_v26/playService.py#L684-L911
https://github.com/Mariusz89B/script.mtvguide/blob/9.3.0_v26/playService.py#L357-L374
https://github.com/Mariusz89B/script.mtvguide/blob/9.3.0_v26/teliaplaycids.py

Part of code, specifics. Python.
```
PROTOCOL = 'mpd'
DRM = 'com.widevine.alpha'

import inputstreamhelper
is_helper = inputstreamhelper.Helper(PROTOCOL, drm=DRM)
if is_helper.check_inputstream():  
   ListItem = xbmcgui.ListItem(path=strmUrl)
   ListItem.setInfo( type="Video", infoLabels={ "Title": channelInfo.title, } )
   ListItem.setContentLookup(False)
   if sys.version_info[0] > 2:
       ListItem.setProperty('inputstream', is_helper.inputstream_addon)
   else:
       ListItem.setProperty('inputstreamaddon', is_helper.inputstream_addon)
   ListItem.setMimeType('application/dash+xml')
   ListItem.setProperty('inputstream.adaptive.license_type', DRM)
   ListItem.setProperty('inputstream.adaptive.license_key', licenseUrl)
   ListItem.setProperty('inputstream.adaptive.manifest_type', 'mpd')
   ListItem.setProperty('IsPlayable', 'true')

import threading

thread = threading.Thread(name='seek', target=self.seek, args=[])
thread = threading.Timer(3.0, self.seek, args=[])
thread.start()

xbmc.Player().play(item=strmUrl, listitem=ListItem, windowed=startWindowed)

   def seek(self):
        xbmc.sleep(2000)
        while not xbmc.Player().isPlaying():
            xbmc.sleep(100)

        xbmc.sleep(200)
        xbmc.Player().seekTime(0.0)

        while xbmc.Player().isPlaying():
            xbmc.sleep(300)
```

### Debuglog
The debuglog can be found here:

**kodi.log**
https://drive.google.com/file/d/13EW7M35VvupdiRsdzfuWUnuGTydvlGoe/view?usp=sharing

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Error from log:
CMediaCodecVideoBuffer::ReleaseOutputBuffer error in render(0)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: NVIDIA SHIELD Android TV SW version 8.2.2(32.6.509.0), Android version 9
 - Kodi version: 19.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by glennguy** [comment]
You should try removing this 'seek to start of live stream' workaround
https://github.com/Mariusz89B/script.mtvguide/blob/831a1a15cdcd92b5ad2726b82e352ac9e2c64ab3/playService.py#L362-L370

Instead use `listitem.setProperty('inputstream.adaptive.play_timeshift_buffer', 'true')`

Can't see exactly what's going on because debug logging isn't enabled in your log.

**Comment by Mariusz89B** [comment]
Replacing xbmc.Player().seekTime with inputstream.adaptive.play_timeshift_buffer helped, now it works as it should.
