### ISSUE TITLE
Kodi 19.x and 20.x crash if epg database enable with the type 'mysql'

### ISSUE THREAD

**Issue by Cyr-ius** [xbmc/xbmc#19583]
### Describe the bug
When I browse  the TV guide, he crashes only I activate the mysql type in Advancedsetting to have the EPG in a mariradb base

## Possible Fix
Do not activate the Database "mysql" type 

### To Reproduce

1. AdvancedSetting.xml
2.`<epgdatabase>
		<name>MyEpg</name>
		<host>x.x.x.x</host>
		<user>x</user>
		<pass>x</pass>
		<type>mysql</type>
		<port>3306</port>	
	</epgdatabase>`
3.Browse EPG

### Debuglog

The debuglog can be found here:
[kodi_crashlog_20210405155506.log](https://github.com/xbmc/xbmc/files/6318535/kodi_crashlog_20210405155506.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Libreelec
 - Kodi version: 19 & 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Fixed by #19586 + #19603 for v20, #19596 + #19605 for v19
