### ISSUE TITLE
Can Kodi v19.0 run on an Apple Mac M1 Mini 8GB/512GB?

### ISSUE THREAD

**Issue by sammydc77** [xbmc/xbmc#19593]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
It can, but using Rosetta 2.

**Comment by sammydc77** [comment]
Thanx!  My understanding is the M1 will create a lot of caching to the
Local SSD, with Rosetta use, and recommendations are not to use Rosetta on
the M1, are there any plans to make it work on the M1 Processor Native soon?

**Comment by fuzzard** [comment]
No timeline.

**Comment by sammydc77** [comment]
I appreciate your candor, and will not run it on an Apple Mac M1 Mini, nor
any New Mac M1 / M1X / M2 Releases.  I have spent over 25 years in IT, now
retired, and understand when the experts I see on YouTube, show proof of
the detrimental effect of  Rosetta on the Local SSD, due to excessive
caching.  Apple has dropped the Intel Based designs, with support going
away in about 2 years.
