### ISSUE TITLE
Bool Window.Property(IsRadio) evaluates false in radio windows

### ISSUE THREAD

**Issue by scott967** [xbmc/xbmc#19592]
### Describe the bug
Here is a clear and concise description of what the problem is:

Wiki suggests there exists boolean Window.Property(IsRadio) and reviewing the code it seems this is set in 
GUIWindowPVRBase.cpp call to `void CGUIWindowPVRBase::OnInitWindow()
{
  SetProperty("IsRadio", m_bRadio ? "true" : "");` but it always seems to evaluate as "false"

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When windows radiochannels/radiorecordings/radiotimers/radioguide/radiosearch are visible, Window.Property(IsRadio) should evaluate to "True".

## Actual Behavior

Window.Property(IsRadio) evaluates false

## Possible Fix

Possibly this was never fully implemented when the GUIInfoManager was refactored? @ksooo   It doesn't show up in Kodi docs but was implemented in PR 4753.   If not might be useful, but I worked around by creating an `<expression></expression>` that "OR"s on the radio window visibility.

### To Reproduce

1. Add a control with visible condition Window.Property(IsRadio) to MyPVRChannels.xml
2. Install PVR client with tv and radio channels
3. Open windows tvchannels and radiochannels and observe the control

### Debuglog

The debuglog can be found here:https://paste.kodi.tv/aqebocemuj.kodi
nothing to see here

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Not working in 19.0 or 20 nightly 210414

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Windows 10 x64 2004

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
`<visible>Window.Property(IsRadio)</visible>` will not work as Window.GetProperty returns a string not a bool.

What should work is 
`<visible>String.IsEmpty(Window.Property(IsRadio))</visible>` to check for TV when acive window is a TV window or
`<visible>String.IsEqual(Window.Property(IsRadio), true)</visible>` when active window is a radio window or
`<visible>!String.IsEmpty(Window.Property(IsRadio))</visible>` to check for radio

**Comment by ksooo** [comment]
This is unrelated to the GUI info manager refactor.

**Comment by ksooo** [comment]
Just did a quick check by adding `<visible>String.IsEqual(Window.Property(IsRadio), true)</visible>` to one of the controls defined in MyPVRChannels.xml and it works as expected - returns "true" for radio channels window and and empty string for TV channels window.

**Comment by scott967** [comment]
Went back and reviewed PR 4753 and see now that the intent is to treat like any window property.  Recommend that the wiki for booleans [https://kodi.wiki/view/List_of_boolean_conditions](url) and infolabels [https://kodi.wiki/view/InfoLabels](url) be corrected to reflect this.  Also should be added to the Kodi codedocs [https://codedocs.xyz/xbmc/xbmc/modules__infolabels_boolean_conditions.html#modules__infolabels_boolean_conditions_Window](url)

**Comment by ksooo** [comment]
Yes, documentation should be fixed.

**Comment by ksooo** [comment]
Wiki updated as suggested.

Kodi codedocs needs a PR to get fixed.
