### ISSUE TITLE
Retroplayer stretch mode issue

### ISSUE THREAD

**Issue by smp79** [xbmc/xbmc#19598]
### Describe the bug
Here is a clear and concise description of what the problem is:

I noticed this issue with Sega MD emulators (e.g. Genesis Plus GX). Stretch modes "Normal" and "Stretch 4:3" are switched places - when I select "Normal" it actually use "Stretch 4:3" and vice versa. This issue does not exist with SNES emulators.

### Screenshots 
Here are some links or screenshots to help explain the problem:

Genesis Plus GX:
https://i.postimg.cc/cCqL2mDn/screenshot00000.png
https://i.postimg.cc/XqwYbChD/screenshot00001.png

Beetle bsnes:
https://i.postimg.cc/FsVHC00Y/screenshot00002.png
https://i.postimg.cc/Nfc0xd2h/screenshot00003.png

 - Operating system version/name: LibreELEC, Windows 10
 - Kodi version: tested with current master and Matrix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by garbear** [comment]
That actually looks correct. Genesis Plus GX has a wide aspect ratio, so 4:3 should be narrower, which it is. The reason why Genesis Plus GX gets narrower in 4:3, and SNES gets wider in 4:3, is that SNES native aspect ratio is < 4:3 so it's stretched horizontally. Genesis Plus GX shrinks. Does that make sense? Or am I interpreting this wrong?

If you have square pixels, you can probably measure the AR and see that normal is variable, but 4:3 aspect is always 4:3. Whether the game is stretched or shrunk depends on the native AR.

**Comment by smp79** [comment]
Can there be a "universal" setting that will allow both Sega and SNES to be played in 4:3?

**Comment by garbear** [comment]
4:3 should be a "universal" setting - you'll always measure a 4:3 aspect for all games and emulators, regardless of source content.

**Comment by smp79** [comment]
That's the point of this issue report - there is no such setting that will allow to play with a 4:3 aspect for all games and emulators. At least not on any 1080p or 4K displays. I have to manually switch between "Normal" and "Stretch 4:3" every time.

When I want to play a Sega game - I have to go to Settings and make sure "Stretch 4:3" is active to get a proper 4:3 AR.
When I want to play a SNES game I have to go to Settings again and enable "Normal" to get a proper 4:3 AR.

**Comment by smp79** [comment]
Yeah, you are right. I'm an idiot. "Stretch 4:3" does indeed measure a 4:3 for both Sega and SNES.
