### ISSUE TITLE
Kodi prompts for username/password to access an passwordless SMBv3 share resource

### ISSUE THREAD

**Issue by thexai** [xbmc/xbmc#19600]
### Describe the bug
Here is a clear and concise description of what the problem is:
Kodi prompts for username/password to access an passwordless SMBv3 share resource

Is needed type some random or bogus login user/password to access. This is not intuitive and is confusing for much users.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Do not prompt for username / password

## Actual Behavior
Prompts username/password:
![screenshot00002](https://user-images.githubusercontent.com/58434170/115141449-88e31f00-a03c-11eb-982d-c23507df64c7.png)

### To Reproduce

Are used two machines with Windows 10 20H2 (19042.928):

hostname PC -----> Kodi is running on this.
hostname ASUS-ZENBOOK ----->  Shared folders are configured on this.

Two machines has SMBv1 disabled (default Windows 10 20H2 setting)
On ASUS-ZENBOOK current Windows account has password changed to NOT match with PC (avoids access granted due share same Windows account).

On ASUS-ZENBOOK configure a passwordless share:

Go to "Network and Sharing Center" > All Networks and check "Turn off password protecting shared":

<img width="584" alt="Screenshot 2021-04-18 111722" src="https://user-images.githubusercontent.com/58434170/115141687-03606e80-a03e-11eb-8195-823036739a48.png">

Configure shared folder and add "everyone" user permissions:

<img width="443" alt="Screenshot 2021-04-18 112132" src="https://user-images.githubusercontent.com/58434170/115141767-5cc89d80-a03e-11eb-90ba-1172d0deb4e4.png">

Make sure on "Password Protection" zone appears text "People without user account and password for this computer can access folders shared with everyone":
 
<img width="274" alt="Screenshot 2021-04-18 111926" src="https://user-images.githubusercontent.com/58434170/115141776-66520580-a03e-11eb-934a-86b3aaf1653b.png">

For test purposes, configure another shared with normal one user permissions (NOT everyone).

### Screenshots 
Here are some links or screenshots to help explain the problem:

Kodi prompts username/password just trying to get to the root of ASUS-ZENBOOK:

![screenshot00002](https://user-images.githubusercontent.com/58434170/115141449-88e31f00-a03c-11eb-982d-c23507df64c7.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: v19.0 - v20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DarkPhoinix** [comment]
very bad
