### ISSUE TITLE
Incorrect image width

### ISSUE THREAD

**Issue by YannC31** [xbmc/xbmc#19627]
### Describe the bug
Here is a clear and concise description of what the problem is:
On an NVidia Shield box, when playing with Kodi a video recorded with a Freebox Pop (French Android TV box), the image width is smaller than the original width. The image is kind of shrinked horizontally. When I read the same video using VLC, it is displayed correctly. The width of the image is correct.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
The video should be displayed correctly (correct width) and not shrinked.

## Actual Behavior
The image is kind of shrinked horizontally

### To Reproduce
Download and Run this video (49 Mo): http://gofile.me/3eEwz/sdvORFFRD

### Your Environment
Kodi running on a NVidia Shield Pro 2019 Model P2897
Used Operating system:
 - [X] Android
 - Operating system version/name: Android 9
 - Kodi version: 19.0.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Sample file is gone, please retest with the current stable version and report back if the issue still occurs (uploading the sample and the log file).
