### ISSUE TITLE
Kodi Randomly stopping because of  "Read - Error( -4, Incoming PDU exceeds limit of 1052672 bytes. )"

### ISSUE THREAD

**Issue by trunk23** [xbmc/xbmc#19640]
### Describe the bug

Here is a clear and concise description of what the problem is:

Firstable please forgive my english, I'm french !
So here is the issue :

I recently changed my nVidia Sheild 2015 for a brand new Shield Pro 2019.
I never had issues with Kodi and the Shield 2015.
The videos I'm reading are on a WD NAS, and the shield access to them via NFS.

With the shield 2019, the videos randomly stop, it can play fine 3 movies, then it stops during the third.
Or it can stops 3 times during 1 video...

I tried to desinstall kodi, I tried several versions of it, the latest nightlies too, versions 19 or even the 20 , I also tried the cache instead of aborting too.
In the log files, the problems seems to be because of this :

Read - Error( -4, Incoming PDU exceeds limit of 1052672 bytes. )

Even with the cache option, when the problems occurs, the connection seems to get busy between the shield and the nas, and when the cache is totally empty the video crash and it brings me back to Kodi menu.
I discovered that when going in the files section through kodi when the bug occurs, I sometimes can't access the folder where the last played video was (but I can access other folders of the nas and play other videos), and I can still access to the problematic folder with another device (my phone for instance) at the same time and play the video that crashed.

The issue isn't always in the same folder of the NAS.

Of course I tried to rebbot the shield, the nas, and made a reset of my box too.

### Debuglog

The debuglog can be found here:
Here is a log with the debug activated : 

http://trunk23.free.fr/kodi.log

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.0 from playstore, then tried latest nightlies, even the 20 versions

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment]
Another NFS issue on Android *sigh*. We've seen multiple issues with NFS on Android lately. Either there's a problem with the current NFS lib or the network stack in the Android devkit. One thing you could try, if you're comfortable with it, is trying to change the MTU settings or TCP (tuning) settings on your server and see if that makes any difference.

For now I'm out of ideas. Perhaps @wsnipex or @notspiff have ideas on how to proceed?

**Comment by wsnipex** [comment]
`2021-04-22 00:19:51.373 T:10955   ERROR <general>: Read - Error( -4, Incoming PDU exceeds limit of 1052672 bytes. )`
From what I can gather this means the server sent a "too big" response.

Can we see the servers /etc/exports?

**Comment by arnova** [comment]
And perhaps @trunk23 could try whether he/she can reproduce the issue with Kodi on his/hers Linux/Windows/Mac computer?

**Comment by trunk23** [comment]
Hello,

thanks for your messages.
So I went back to version 18.9 Leia.
It's better, but not perfect, since it sometimes freeze completely on Kodi, it doesn't go back to the menu of kodi, it's like it the video had been paused, but I can't resume it !
But it happens less often than with newer versions.
 One clue is that each time I stop a video, in the log there is a NFS3ERR_ROFS(-30) error, it doesn't affect performance, but maybe could it be a clue ?

I made a new log with DEBUG activated, and here it is just after a freeze : [http://trunk23.free.fr/kodi.2.log](url)

Thanks for your help.

**Comment by lethalwp** [comment]
Hello,

As bizar as it is, i'm using a shield to use kodi, also with nfs to my synology.
It worked like a charm for 2 years, and since a couple of weeks, i now have the same issue.

shield android 11 (nvidia 9.1 or something)
kodi 19.3

I couldn't link the problem to an update, as i don't know how shield is updating the apps.

**Comment by trunk23** [comment]
Hello

The problem stopped when I changed my provider, so seemed to be a rooter issue.

**Comment by lethalwp** [comment]
i'm streaming locally on wifi 5G, i know ithe signal strength is "touchy": if somebody moves the device, it can be that the wifi quality is right below the required speed. 2 years ago i had a "buffering" icon appearing.
Weirdly this crash problem happens on 4KRIPs as much as on DVDrips, which have a much lower bitrate.


Now i've changed the protocol from nfs to smb. I don't know if smb has much overhead compared to nfs. But from time to time the movie is paused with a notification in the upper right corner "source too slow". Still no buffering icon. Then it resumes playback for another couple of minutes.

My theory is that the wifi signal is just below requirements, and in the nfs method, something is wrong in the catchup that creates this big PDU?
When it happens, it breaks the NFS connection: the nfs share is unbrowsable untill kodi app is killed & restarted.

@trunk23 : is your shield connected in wifi? Is your router the "wifi router"? or were you playing over the internet?
I have indeed updated my wifirouter firmware some time ago. It might be linked...
