### ISSUE TITLE
Kodi  19.0 crashes when loading video library - Movies

### ISSUE THREAD

**Issue by jdh23662** [xbmc/xbmc#19656]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi 19.0 crashes when entering movie sub-menu from the main menu.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

From main menu, I should select "movies" and be switched to the movie menu.  From the movie menu, I should scroll through the movie titles and see info on titles and select movies to play.

## Actual Behavior

From the main menu, I select "movies".  I am switched to the movie menu which displays the list of movies.  ~2 seconds after that, Kodi simply disappears as it has exited (presumably crashed)

## Possible Fix

Don't know.  Conditions for the library though:
Movie library consist of 1218 mkv files in 3 discrete folders,  1152 files in one folder with no metadata files, 45 mkv files in the second folder with no metadata files, and 21 mkv files in the third folder with local metadata files (nfo and art jpg files).  The folders are on a single volume (NTFS) on a Open Media Vault NAS (OMV ver 5.2.6-1, SMB share OMV using Samba 4.14.4, Windows 10 using SMB direct).  Crash has bee reproduced on 4 computers, 3 HP Elitedesk 800 g2 and 1 HP Envy 360 laptop.  All machines run identical OS.  Television and Music library does not produce fault.  Fault eliminated by rolling back to Kodi 18.9.

### To Reproduce

1.  Install clean version of Kodi 19.0
2. Using the "Add videos..." selection and then "Browse" and "Add network locations", create a SMB connection to the individual folders.
3. The folders then load and data is loaded to the library.  Non-local metadata is loaded from TMDB.com
4. The Movies item is now available on the main menu.  Selecting it causes the movie list to load, but Kodi crashes ~2 seconds after entering menu.
5. Loading order of libraries (Movies, Television, Music) does not affect fault.
6. Fault occurs when movies is the only library. 
7. Fault occurs regardless of skin (Confluence, Estuary) loaded.
8. Fault occurs when accessing folder with 1152 mkv files from the Videos/Files/<Folder with files> interface AFTER exiting videos menu to the main menu.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/iqulodolen.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ X] Windows 
 - [ ] Windows UWP

 - Operating system version/name:  Windows 10 Pro 20H2
 - Kodi version: 19.0.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Synapto** [comment]
Sounds like the ghosts of https://github.com/xbmc/xbmc/issues/19008 & https://github.com/xbmc/xbmc/issues/19208 are still haunting Kodi.

**Comment by fabquenneville** [comment]
I have similar issues where Kodi will crash when opening menus

**Comment by buzzdixn** [comment]
I've experienced the same crashing issues described in this ticket, along with these also...

> Sounds like the ghosts of #19008 & #19208 are still haunting Kodi.

What are we supposed to do if we want to extract thumbnails and have them visible ?
Just deal with it and wait until the issues gets fixed ?
In all seriousness, is that the only current solution ?
Thanks for any guidance &/or info...
