### ISSUE TITLE
[UWP] [Xbox] HTTPS connection to addons repository is not working

### ISSUE THREAD

**Issue by thexai** [xbmc/xbmc#19665]
### Describe the bug
Here is a clear and concise description of what the problem is:

HTTPS connection to addons repository is not working on Matrix UWP-64 builds.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

HTTPS connections should works.

## Actual Behavior

![Captura de pantalla 2021-05-01 095537](https://user-images.githubusercontent.com/58434170/116775476-74068280-aa63-11eb-95b1-64f5b99f0b5a.png)

Is 100% reproducible on both Windows 10 (running UWP-64 build) and Xbox.

## Possible Fix

Disable `CURLOPT_SSL_VERIFYPEER`

There seem to be problems verifying the authenticity of the SSL certificates.

Maybe update Openssl to v1.1.1j    ???
Or update curl (win10 depends package is quite old)

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/cuyaheleja.kodi

Relevant lines for this issue:
2021-04-28 08:50:21.581 T:1708    ERROR <general>: CCurlFile::FillBuffer - Failed: SSL peer certificate or SSH remote key was not OK(60)
2021-04-28 08:50:21.581 T:1708    ERROR <general>: CRepository: http://mirrors.kodi.tv/addons/matrix/addons.xml.gz index has wrong digest e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, expected: 424ce07b48fbb99cc27673cdafa112fa4d00b936ad87ce1c0fccaf6070f8e5b2

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [X] Windows UWP

 - Operating system version/name:  Windows 10 20H2  / Xbox Series X with WINDOWS 10.0.19041.7722
 - Kodi version: v19.0 nightlies    (Matrix or master)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Ping @wsnipex and @Paxxi

**Comment by wsnipex** [comment]
please provide a debug log and also enable curl component logging

**Comment by thexai** [comment]
https://paste.kodi.tv/satinagaqo.kodi

This is Matrix nightlie. Sometimes the list of addons is obtained, still they cannot be installed or updated. The problem seems Kodi can not access to local certificates. This log is in Windows 10 UWP although same thing happens for Xbox users.

**Comment by wsnipex** [comment]
this is an issue with how either openssl or curl is compiled for UWP.
Curl/Openssl does not have a CA trust store that knows about Let's Encrypt.
On depends platforms, we use our own cacert.pem, that is generated during curl build and installed to system/certs/cacert.pem.
UWP could either do the same or somehow use the windows trust store(if possible).

**Comment by Paxxi** [comment]
I don't think openssl can use the windows trust store but I'm not sure. I'll need to look into it and see what we can do, unless someone beats me to it 😀

**Comment by wsnipex** [comment]
does the env var not work on UWP?

**Comment by thexai** [comment]
The code to set env var on UWP is here:
https://github.com/xbmc/xbmc/blob/master/xbmc/platform/win10/PlatformWin10.cpp#L25-L31

Also I tried to update `cacert.pem` using:
https://github.com/curl/curl/blob/master/lib/mk-ca-bundle.pl

and does not worked (certs bundle updated but same issue persists).

**Comment by thexai** [comment]
Latest version working is `Kodi-20190417-018c68af-master-x64.appx` (19.0-ALPHA1)   lol
