### ISSUE TITLE
VideoLibrary.GetInProgressTVShows JSONRPC query sort order is not working.

### ISSUE THREAD

**Issue by queeup** [xbmc/xbmc#19677]
### Describe the bug
[VideoLibrary.GetInProgressTVShows JSONRPC](https://kodi.wiki/view/JSON-RPC_API/v12#VideoLibrary.GetInProgressTVShows) query sort order is not working.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Changing sort order works as written on the [docs](https://kodi.wiki/view/JSON-RPC_API/v12#VideoLibrary.GetInProgressTVShows).

## Actual Behavior

Query sort order is staying same despite changing sort order.

## Possible Fix

Sort is not implemented at all for this method?

### To Reproduce

1. Try to get jsonrpc query result with sort order:
```
curl --header "Content-Type: application/json" --request POST --data '{"jsonrpc": "2.0", "id": "json_test", "method": "VideoLibrary.GetInProgressTVShows", "params": {"properties": ["year"], "sort": {"order": "descending", "method": "year"}}}' http://kodi:8080/jsonrpc

curl --header "Content-Type: application/json" --request POST --data '{"jsonrpc": "2.0", "id": "json_test", "method": "VideoLibrary.GetInProgressTVShows", "params": {"properties": ["lastplayed"], "sort": {"order": "descending", "method": "lastplayed"}}}' http://kodi:8080/jsonrpc
```

### Debuglog

The debuglog can be found here:
N/A

### Screenshots
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC BETA2
 - Kodi version: 19.0.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by roidy** [comment]
limits is also not working from this method

**Comment by queeup** [comment]
Closed? Why? @DaVukovic
