### ISSUE TITLE
Subtitles with multiple lines are overlapped so wrong text position

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#19698]
### Describe the bug
Here is a clear and concise description of what the problem is:

There is a problem with ~webvtt~ (edit: this problem should happen with all SRT files) subtitles, when a subtitle is displayed in conjunction with another in sequence
the subtitles appears overlapped

This is the subtitle file, at index 261 this part should appear in conjuction with next sequences 262 and 263
[webvtt_subtitle.txt](https://github.com/xbmc/xbmc/files/6433054/webvtt_subtitle.txt)
but appears as overlapped with wrong position:
![immagine](https://user-images.githubusercontent.com/3257156/117267847-fbcf0100-ae56-11eb-9974-920fa2d67c27.png)
where instead should appear similar to:
![immagine](https://user-images.githubusercontent.com/3257156/117268482-992a3500-ae57-11eb-90c3-1ea691d14ee0.png)

If needed the video is on ntflix "Blue exorcist" S1E13 time position 14:58 and choose English subtitles

_UPDATE:_
We have found two causes for this problem:
1) when the screen resolution not match the video resolution the positions (with multiple subtitles lines) will be wrong
2) is missing the support for subtitles dynammic position for SRT (where other players like VLC support it)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Have a right subtitle position

## Actual Behavior

Subtitles appears overlapped or in wrong position

### To Reproduce

1. Use the attached subtitle file with a video (or use ntfx addon)
2. Seek to 14:58

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/fifugoniyo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
I have noticed that this only happens if Kodi is in the windowed mode
and maybe this it is a known bug, i remember other complaining in the past, in case i will close this Issue

**Comment by Essam311** [comment]
@CastagnaIT https://github.com/xbmc/inputstream.adaptive/issues/229

**Comment by CastagnaIT** [comment]
@Essam311 ah thanks i forgot where i had written
seem the position values are never taken in consideration

**Comment by Essam311** [comment]
@CastagnaIT The SRT format supports the text position using the alignment tags like {\an8}, {\an5}, but they do not work on Kodi.

You could test using this subtitle file with Kodi and with media player classic.

[Blue.Exorcist.S01E13.zip](https://github.com/xbmc/xbmc/files/6434228/Blue.Exorcist.S01E13.zip)

**Comment by CastagnaIT** [comment]
i think i have found something in `OverlayRenderGUI`
the standard text subtitles position seem to be hardcoded,
this that can be changed only by "subtitle position on screen" on player setting
then seem not allow dynamc text subtitle positions

thanks for the tags tip,
these are ASS line alignment tags
https://aegi.vmoe.info/docs/3.1/ASS_Tags/
i have see that VLC Player add the same support on SRT files

i think is possible add in some way a parse for these tags (like `{\an8}`, `{\an5}`) and set the right subtitles position on screen, to be used when kodi subtitle settings is set as "Fixed"

but on webvtt we have specific coordinates
00:14:58.900 --> 00:15:06.365 position:50.00%,middle align:middle size:80.00% line:10.00%
i think can be solved by using the tag
`{\pos(x, y)}`

then i think is possible to add the tag conversion part on ISA,
and the support on these SRT tags on Kodi side,
so like already happen on VLC Player

**Comment by CastagnaIT** [comment]
@Essam311 this is a rudimental example to make work the `{\an8}` tag
https://github.com/CastagnaIT/xbmc/tree/subtitle_pos

but is needed different other changes to make all position tags to works
because e.g. to align the text on the right we need to know the length of text graphics

**Comment by mlidbom** [comment]
The positioning of the subtitles differ with screen resolution. They are fully readable in 1920x1080 resolution. I'm guessing that the code implicitly  assumes that you run at this resolution and ensures that subs are displayed in a readable fashion in this resolution. In other resolutions things turn really bad.

**Perhaps the most important quick fix is to ensure that placement remains the same in different screen resolutions as in 1920x1080  rather than implementing full support for placement tags.**

In 3840x2160 resolution the dialog subtitles are not visible at all: 
![subtitles-kodi](https://user-images.githubusercontent.com/143203/117248791-d636fd00-ae40-11eb-8efc-40ffdec1d3f1.png)

In 1920x1080 resolution subs are fully readable
![image](https://user-images.githubusercontent.com/143203/117353520-81cb6600-aeb0-11eb-92bb-60028c4e16c4.png)

In 1280x720:
![image](https://user-images.githubusercontent.com/143203/117354362-880e1200-aeb1-11eb-9e77-43ee45e4c22f.png)

**Comment by Essam311** [comment]
@CastagnaIT The most used and important tags are `{\an8}` to align the subtitles to the top and `{\an5}` to  align the subtitles to the middle which is common in the Japanese subtitles, the rest are not that important, most languages just use only `{\an8}` in the Netflix subtitles.

**Comment by Essam311** [comment]
@CastagnaIT I think adding `{\an8}` so the subtitles be in the top center will be enough for fixing the problem with the Netflix subtitles.

**Comment by CastagnaIT** [comment]
is true, although all things are related in this use case
because the wrong position (or missing) text, are text that should be placed on the top of screen not like 1920x1080 screenshot
but there may also be different cases, so a solution will have to be found for both of cases

**Comment by CastagnaIT** [comment]
it seems that the text coordinates are calculated in the right way,
my suspects are within `RenderOutline` function:
https://github.com/xbmc/xbmc/blob/19.1-Matrix/xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererGUI.cpp#L202
but this is too complex for my skills

**Comment by CastagnaIT** [comment]
i have found a old Issue not directly related but explaining the current problems with subtitles render,
a possible render rework is suggested here:
https://github.com/xbmc/xbmc/issues/15902#issuecomment-491589058
if implemented it should solve also this Issue
