### ISSUE TITLE
Tag version pattern

### ISSUE THREAD

**Issue by dev-0x7C6** [xbmc/xbmc#19710]
Hi, Is tagging pattern changed somehow? Tag for 19.1 is just `v19.1`but older versions was released under this pattern `x.y-codename`

**Comment by DaVukovic** [comment]
You are correct. The tag is different from the others. I talked to @DaveTBlake. AFAIK there's no "rule" that the tag has to match some specific pattern, but maybe we can change it. 

I do understand the problem if you have scripts which are expecting some specific kind of pattern.

**Comment by DaveTBlake** [comment]
I'm a bit mystified why it came out like that, the release itself is `19.1-Matrix` but the tag isn't. If it can be edited then I will, but I'm not sure that it can.

**Comment by DaveTBlake** [comment]
OK, have created a tag `19.1-Matrix` with same SHA and edited the release. Rather not delete or rename tags just in case in the few hours it has existed someone is using it. Extra tags are no harm.

Historically the tag name pattern has varied, and there are no rules per se, but my aim was to be consistent.

**Comment by dev-0x7C6** [comment]
> Extra tags are no harm

Sure :)

Thanks for fixing this, I can maintain yocto recipes without changing extra bits :)
