### ISSUE TITLE
AnalogFastForward Seeking with MP4 files causes KODI v19.x to freeze the video

### ISSUE THREAD

**Issue by PS4-BillGates** [xbmc/xbmc#19718]
### Describe the bug
Here is a clear and concise description of what the problem is:

PLEASE EXCUSEME FOR MY BAD ENGLISH...

My Operating System is Window 10 Professional Version 2004 (OS Build 19041.804)

*** This problem has started with KODI v19.0 and remains in the new KODI v19.1, but in KODI v18.9 and earlier with the same MP4 files everything is working fine, AnalogFastForward did not freeze the video ***

I Have a bunch of MP4 video files from many different sources and evetytime i reproduce them in KODI v19.x and seeking with my XBOX 360 Controller (function AnalogFastForward assigned to Left and Right Bumpers) if i leave pressed any of the bumpers and AnalogFastForward takes the 32x value the video gets paused or freezed for ever and i need to press the button assigned to cancel the reproduction of the video.

I be reindex some of the "problematic" MP4 files with FFMPEG using the command but the problem persist in KODI 19.x, but if i reindex the same video to MKV container the problem dissapear.

Thanks in advance.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
No log, no issue ;)
