### ISSUE TITLE
Follow up to #19456

### ISSUE THREAD

**Issue by funkymaster** [xbmc/xbmc#19727]
### Describe the bug
Here is a clear and concise description of what the problem is:

#19456

Hello,

I can reproduce the issue on Windows.
Please take my logs instead.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
Addon "Embuary Info" disabled: https://paste.kodi.tv/ozezikalul.kodi
Addon "Embuary Info" enabled (issue appears): https://paste.kodi.tv/omobosinac.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 7
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by joseluismarti** [comment]
Fixed by #24000
