### ISSUE TITLE
External ASS subtitles: font loading performance issue

### ISSUE THREAD

**Issue by alucryd** [xbmc/xbmc#19728]
### Describe the bug
Here is a clear and concise description of what the problem is:

I’m running Kodi Matrix via CoreElec on a Khadas Vim 3, and I’ve got a pretty substantial anime collection, with all subtitles and embedded fonts extracted to avoid duplication and wasted space. This means I have a huge Fonts folder (with upwards of 4000 fonts) mounted at /storage/.kodi/media/Fonts over CIFS. For all intents and purposes it works fine, and kodi correctly displays the styled subs so kudos there. However, it takes around 2 minutes of intense CPU usage before every episode that uses ASS subtitles, for what I’m assuming is libass scanning the whole fonts folder.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Loading should be a lot faster.

## Actual Behavior

Loading takes a few minutes.

## Possible Fix

Possibly using a cache or index?

### To Reproduce

1. Place a few thousands fonts in media/Fonts
2. Load a video with external ASS subtitles

### Debuglog

The debuglog can be found here: Not sure if it'll help, will be happy to provide one if you think it will.

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: CoreElec Matrix rc4
 - Kodi version: Matrix

**Comment by alucryd** [comment]
Added the empty lines I removed from the template, but `Ignored rules` is still not going away :/

**Comment by lrusak** [comment]
you didn't supply a debug log

**Comment by enen92** [comment]
I think this is tracked in libass and improving the performance of font loading is on their roadmap. This is likely related to our usage of the API by using `ass_set_fonts_dir` (https://github.com/libass/libass/blob/master/libass/ass.h#L265) which is parsed recursively.
The only alternative is to manually load the required fonts using `ass_add_font` https://github.com/libass/libass/blob/master/libass/ass.h#L696 but that will require identifying all the fonts that need to be loaded for a particular subtitle. IMHO that's something that should be improved on libass instead.

**Comment by enen92** [comment]
@alucryd maybe report it at https://github.com/libass/libass/issues?page=2&q=is%3Aissue+is%3Aopen

**Comment by alucryd** [comment]
@enen92 Thanks a lot for the quick reply! I reported it over at libass: https://github.com/libass/libass/issues/510

**Comment by astiob** [comment]
Hi, I come from the libass issue. For accessing large font collections, libass uses font providers; on Linux this means Fontconfig. There are no plans to change the behaviour of `ass_set_fonts_dir` (ultimately it would just mean duplicating Fontconfig). OP says their libass builds have no Fontconfig support, so I think the main vector here would be to get CoreELEC to add it. At any rate, I assume this is not directly an XBMC issue.

**Comment by vpeter4** [comment]
From what I see LibreELEC/CoreELEC has fontconfig support but maybe  needs some more tweaking to add custom fonts.

But `fc-list -f '%{file}\n' | sort` on LibreELEC gives this which seems ok?
```
/storage/.kodi/media/Fonts/Arial.ttf
/storage/.kodi/media/Fonts/DejaVuSans_Jaipur.ttf
/usr/share/fonts/Type1/c0419bt_.pfb
/usr/share/fonts/Type1/c0582bt_.pfb
/usr/share/fonts/Type1/c0583bt_.pfb
/usr/share/fonts/Type1/c0611bt_.pfb
/usr/share/fonts/Type1/c0632bt_.pfb
/usr/share/fonts/Type1/c0633bt_.pfb
/usr/share/fonts/Type1/c0648bt_.pfb
/usr/share/fonts/Type1/c0649bt_.pfb
/usr/share/fonts/Type1/cursor.pfa
/usr/share/fonts/liberation/LiberationMono-Bold.ttf
/usr/share/fonts/liberation/LiberationMono-BoldItalic.ttf
/usr/share/fonts/liberation/LiberationMono-Italic.ttf
/usr/share/fonts/liberation/LiberationMono-Regular.ttf
/usr/share/fonts/liberation/LiberationSans-Bold.ttf
/usr/share/fonts/liberation/LiberationSans-BoldItalic.ttf
/usr/share/fonts/liberation/LiberationSans-Italic.ttf
/usr/share/fonts/liberation/LiberationSans-Regular.ttf
/usr/share/fonts/liberation/LiberationSerif-Bold.ttf
/usr/share/fonts/liberation/LiberationSerif-BoldItalic.ttf
/usr/share/fonts/liberation/LiberationSerif-Italic.ttf
/usr/share/fonts/liberation/LiberationSerif-Regular.ttf
/usr/share/fonts/misc/6x13-ISO8859-1.pcf.gz
/usr/share/fonts/misc/cursor.pcf.gz
```

**Comment by alucryd** [comment]
@vpeter4 I couldn't find any fc-* binary, so I assumed libass was built without fontconfig, but it is. It's just that the fontconfig binaries aren't present. If I can get them somehow maybe I can make use of fontconfig after all.

**Comment by alucryd** [comment]
As stated in the libass issue, I was able to get the fontconfig binaries, put my fonts in `~/.local/share/fonts` so that they are not scanned every time and proceeded to rebuild the fc cache. The first episode I launched took a long time again, but maybe it was rebuilding its own cache, because after that everything loaded instantly. Thanks you all for the help!

**Comment by vpeter4** [comment]
/usr/share/fonts/storage/.kodi/media/Fonts
~/.fonts

**Comment by enen92** [comment]
I was about to tell you that the other day but I'd be my 3rd post in a row :)
The issue is that libreelec sets fontconfig to use the userdata/fonts folder as a font location. But we also use this folder in Kodi to look for additional fonts for subtitles. As long as /use/share/fonts is not removed when you update libreelec (squashfs) it's good. Ideally libreelec shouldn't set this directory as a fontconfig font directory but some other system directory.

**Comment by vpeter4** [comment]
Are you saying setting folder _/storage/.kodi/media/Fonts_ is not needed anymore? Seems so according to the commit of yours above? Then sure, my commit could be reverted to get same final effect.
@chewitt: Are you are going to revert it? And set some other folder like _/storage/.cache/fonts_? I'm not bothering to send PR's to LE anymore.

Folder _/usr/share/fonts_ is always available but it is readonly (squashfs).

**Comment by enen92** [comment]
Ups sorry, I thought you were still involved with LE development. However note that this might apply to coreelec as well if the same approach is being followed there.
Since that path was set on fontconfig to fix our libass implementation in Kodi, it doesn't make sense anymore. Separation of concerns should exist between what are considered system fonts/folders and what are considered Kodi directories. The userdata/fonts folder is not designed to store hundreds of fonts. However, since it is the folder configured in fontconfig, the user might really not have another alternative to store system fonts (at least that is not removed with an upgrade)
