### ISSUE TITLE
Configurable TLS cipher config for HTTPS webserver

### ISSUE THREAD

**Issue by ghen2** [xbmc/xbmc#19735]
### Describe the bug
Here is a clear and concise description of what the problem is:

Could this constant: https://github.com/xbmc/xbmc/blob/master/xbmc/network/WebServer.cpp#L1224
`  const char* ciphers = "NORMAL:-VERS-TLS1.0";`
be made configurable through advancedsettings.xml ?
To allow users to fine-tune the webserver SSL configuration (protocols and ciphers).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Currently this is hardcoded to a default set of ciphers, with TLS 1.0 disabled.
The resulting configuration can be seen with `gnutls-cli --priority NORMAL:-VERS-TLS1.0 -l`

Users may want to use a stricter / more secure configuration, eg. allowing only TLS 1.2+ and only modern AEAD ciphers.
Exposing the GNUTLS cipher string is the most generic way to achieve this.  (it could break the setup if misconfigured, but that's ok for advancedsettings.xml ?)

Documentation on the gnutls cipher configuration can be found here: https://www.gnutls.org/manual/gnutls.html#Priority-Strings

If making this configurable is considered overkill, please at least consider improving the current value `NORMAL:-VERS-TLS1.0` to `PFS:-VERS-TLS1.0:-VERS-TLS1.1`, to disable TLS 1.1 (deprecated per RFC 8996) and static key exchange (per RFC 7525 BCP).

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by wsnipex** [comment]
would you be up to implementing this advancedsetting?

**Comment by ghen2** [comment]
I found another way to tweak the SSL config, through a file referenced in `GNUTLS_SYSTEM_PRIORITY_FILE` environment variable (or `/etc/gnutls/config` as system-wide default), containing something like:

```
[overrides]
disabled-version = tls1.0
disabled-version = tls1.1
tls-disabled-kx = rsa
```

This will probably do for users that care to tweak the ciphers, but I'd still recommend to update the default to disable TLS 1.1 and static RSA key exchange ciphers as suggested above.  Shall I create a PR for just that?

```
--- a/xbmc/network/WebServer.cpp
+++ b/xbmc/network/WebServer.cpp
@@ -1220,7 +1220,7 @@ bool CWebServer::LoadCert(std::string& skey, std::string& scert)
 struct MHD_Daemon* CWebServer::StartMHD(unsigned int flags, int port)
 {
   unsigned int timeout = 60 * 60 * 24;
-  const char* ciphers = "NORMAL:-VERS-TLS1.0";
+  const char* ciphers = "PFS:-VERS-TLS1.0:-VERS-TLS1.1";
 
   MHD_set_panic_func(&panicHandlerForMHD, nullptr);
 
```

**Comment by wsnipex** [comment]
requiring PFS ciphers might be too aggressive, e.g. for old android devices.
But we could got for NORMAL:-VERS-TLS1.0:-VERS-TLS1.1

**Comment by ghen2** [comment]
I don't think there are Android (or other) devices that support TLS 1.1 (the current minimum requirement) but no PFS ciphers, at least not in their default configuration.

Raising the bar from TLS 1.1 to TLS 1.2 will not cause any disruption (most clients implemented both at the same time, ie. there is no client with TLS 1.1 as its highest supported protocol), and I don't expect requiring PFS _on top of TLS 1.2_ will either.

**Comment by ghen2** [comment]
The above config should disable TLS 1.1.  In which file did you put this?  Did you reference it in `GNUTLS_SYSTEM_PRIORITY_FILE` **in kodi's environment**?  (not just your shell's)

To disable CBC ciphers, add the following:
```
tls-disabled-cipher = aes-128-cbc
tls-disabled-cipher = aes-256-cbc
```

**Comment by RZR7332** [comment]
I'm pretty sure that is what I am missing here... how do I do that/where is the environment file? Linux is not my strongest ability in all honesty.

My config is referenced in /etc/gnutls/config, as well as another file /etc/gnutls/default-priorities which seems similar but has different syntaxing. Scanning with testssl.sh reveals the below (this is only partial output to illustrate):

![image](https://user-images.githubusercontent.com/97453016/168105726-5b1cd2c3-5223-4b7e-875e-9d40433128b7.png)

I'm pretty sure that you are right, and that I have indeed missed setting this variable.

**Comment by RZR7332** [comment]
I paid close attention to that part of your post when fiddling earlier (I have no use case for TLS 1.1 anywhere and the system really just does Kodi and some Docker).

I think the file is world-readable:

-rw-r--r-- 1 root root 184 May 12 16:55 /etc/gnutls/config

Owned by root but I can read it with my regular account without having to use sudo.

Just in case, the contents of the config file:

[overrides]
default-priority-string = PFS
disabled-version = tls1.0
disabled-version = tls1.1
tls-disabled-kx = rsa
tls-disabled-cipher = aes-128-cbc
tls-disabled-cipher = aes-256-cbc

**Comment by ghen2** [comment]
No idea then, that should work...

**Comment by RZR7332** [comment]
Would you mind telling/showing me how to set it in the environment variables? I'd like to just do that anyway (even though it should logically not make any difference) and see what happens. If that doesn't work, I will pose this question on the OSMC forums. 

Regardless, thank you for your willingness to help, I really appreciate it.

**Comment by ghen2** [comment]
That's entirely dependent on your OS and init system.  Here on Arch Linux, with systemd, the service file for kodi contains:
> EnvironmentFile=-/etc/conf.d/kodi-standalone

so it reads environment variables from that file.

But this is getting off-topic for Kodi.  The original suggestion here was to make it configurable in kodi itself, as an advancedsetting.  (Or at least improve the default to TLSv1.2+, now TLS 1.1 has been formally deprecated by RFC 8996.)

**Comment by RZR7332** [comment]
OSMC is Debian-based and also uses systemd, so it **should** be similar.

I agree with you though and will direct my queries to the OSMC forum for my particular case - thank you for your help!

@wsnipex as stated in the original post and the last comment, is there any timeline/progress/update on this? TLS 1.1 has been deprecated for a while now and should not be enabled by default. First prize would be to make the options user-configurable but this is definitely something which should be fixed in base/source.

**Comment by ghen2** [comment]
> If making this configurable is considered overkill, please at least consider improving the current value `NORMAL:-VERS-TLS1.0` to `PFS:-VERS-TLS1.0:-VERS-TLS1.1`, to disable TLS 1.1 (deprecated per RFC 8996) and static key exchange (per RFC 7525 BCP).

Can this maybe still be considered for the Omega release?

(and the updated BCP guideline is RFC 9325)

**Comment by ghen2** [comment]
> requiring PFS ciphers might be too aggressive, e.g. for old android devices. But we could got for NORMAL:-VERS-TLS1.0:-VERS-TLS1.1

@wsnipex Could you please consider this for v22 ?

**Comment by wsnipex** [comment]
PRs welcome

**Comment by ghen2** [comment]
See https://github.com/xbmc/xbmc/pull/25493
