### ISSUE TITLE
mediaportal, comskip, kodi remote from server, possible fix

### ISSUE THREAD

**Issue by bilkusg** [xbmc/xbmc#19730]
I think it is well known that although comskip works with mediaportal and kodi if kodi and mediaportal run on the same machine, kodi fails to find the comskip info if it is run remotely ( e.g. on an android or linux  machine, or even another windows box ).

I have found a non-intrusive way of fixing this problem for what I think is the most common use-case - when the recordings are accessed remotely using smb - and would be happy to put the work in to implement this as a pull request for both mediaportal addin and kodi. The two changes are independently backward compatible - if you change only kodi or only mediaportal, nothing ix fixed, but nothing changes either. The code works against either Matrix or Master and probably older versions but I haven't checked.

I'm looking to establish whether a) this is already solved elsewhere and I've failed to find the fix, b) there is sufficient interest in incorporating the fix to justify my turning a personal hack into a proper pull request.

**Comment by bilkusg** [comment]
How on earth am I meant to convert this into a bug report when it isn't one? There's no point sending you a debug log because there's nothing to debug.

**Comment by fuzzard** [comment]
This issue tracker is for bug reports only, hence the template, and the subsequent labels.

You say theres some well known issue with one particular backend, but dont really provide any actual information. A link to an Issue describing more details, or anything?

Unfortunately you just dont provide enough information for any real opinion to be given. 
You can either open a PR with whatever changes you are alluding to, or alternatively open/link an actual issue with debug logs and actual information

**Comment by phunkyfish** [comment]
@bilkusg best to discuss this under the addon GitHub until we know what next steps should be. Then if it makes sense we can open a PR for kodi. Sounds ok?

**Comment by bilkusg** [comment]
Thanks @phunkyfish. Have started that conversation

**Comment by bilkusg** [comment]
For anyone who comes across this thread, the fix has been adapted to work entirely within the mediaportal plugin which now supports remote edl files over smb. No need to modify kodi itself. 
Thanks to @phunkyfish in particular for guiding me through the process and accepting my pull request.

**Comment by phunkyfish** [comment]
And thank you for contributing it 😉
