### ISSUE TITLE
Kodi hangs invisibly if it can't find TVH server

### ISSUE THREAD

**Issue by graham8** [xbmc/xbmc#19743]
### Describe the bug
Here is a clear and concise description of what the problem is:

Started Kodi but no window showed.  Went to Task manager, found Kodi and selected it which brought up the GUI with 'not responding'. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should carry on if it can't find the TVH server.

## Actual Behavior

Kodi log was stopped showing attempt to raise TV Headend server was failing.  Re-booted TVH server and all came good.

## Possible Fix

No idea but this does not happen with OSMC.  I haven't tested other platforms

### To Reproduce

1. Install Kodi and HTSP PVR client with remote TVH server
2. Turn off Kodi and TVH server
3. Start Kodi

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ovebatutoj.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
> Kodi should carry on if it can't find the TVH server.

 I agree and exactly this happens here. Kodi GUI shows up, with empty TV and Radio sections. Sorry, cannot reproduce (Kodi 19.1, macOS).

**Comment by ksooo** [comment]
@graham8 is this still an issue with Kodi 19 / 20 nightly? If yes. post a fresh logfile with pvr component logging enabled, please

**Comment by graham8** [comment]
It's working fine now with 19.1.0.  I'm not tracking nightlies.
