### ISSUE TITLE
No picture when playing 10-bit HEVC video on Samsung Tablet (SM-T510)

### ISSUE THREAD

**Issue by Pentaphon** [xbmc/xbmc#19747]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing a 10-bit HEVC file on a Samsung SM-T510 tablet, there is audio but no picture. The thumbnail is displayed, however. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect both video and audio to play. 

## Actual Behavior

When playing the sample file I have included on the tablet, there is audio but no video. Also, the thumbnail shows up correctly. 

## Possible Fix

No idea. 

### To Reproduce

1. Play the sample file https://easyupload.io/aq1d6v on a Samsung SM-T510
2. See that the thumbnail generates correctly, but there is no video when playing the file. Just audio. 

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/anoxiliron

### Screenshots 
Here are some links or screenshots to help explain the problem:

None to show but a black screen while playing the sample file. 

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Sample file: https://easyupload.io/aq1d6v

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: samsung SM-T510 with Android 10.0.0 API level 29, kernel: Linux ARM 32-bit version 4.4.177-20709318
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Log and sample files are gone, I am going to close this. If this is still an issue with the latest stable version (preferably nexus) please report back and upload the artifacts again

**Comment by Pentaphon** [comment]
The log is gone because the team took nearly a year and a half to get to it because I didn't delete it. I'm done with using Kodi anyway. I am using another player instead which works fine on that tablet and I will probably replace that tablet with something with better codec support.
