### ISSUE TITLE
Kodi 19.1 XBOX Series X

### ISSUE THREAD

**Issue by koubafire** [xbmc/xbmc#19745]
Does anyone see Kodi 19.1 on XBOX ? I can only download 18.9.

**Comment by DaveTBlake** [comment]
The current version of Kodi for Xbox is 18.9
See updated release announcement for why https://kodi.tv/article/kodi-matrix-19-1-release/
This is also discussed on the forum https://forum.kodi.tv/showthread.php?tid=359919

This is not a matter to raise a Github issue for, so closing

**Comment by koubafire** [comment]
What is this? 

Xbox specifics

This version also brings 19.1 to the Xbox - while 19.0 has been in the Microsoft Store since launch, this was Windows-only while we found a way to adequately test the new release on Xbox. We've fixed that now, so Xbox users will automatically upgrade from 18.9 to 19.1 if you've got auto-update enabled. It's worth mentioning that there's a known memory limitation - present in 18.x as well - that causes Xbox application crashes with 4k content, so please be aware.

**Comment by DaveTBlake** [comment]
Read the announcement **fully**, it goes on to say
**EDIT Ah, so close. Sadly, this isn't going to happen - there's a new issue that's bubbled up on Xbox that means you can't download any addons, which is a touch... inconvenient. As such, we've had to pull Xbox 19.1 - sorry, folks. Let's see if we can resolve that for 19.2...**
