### ISSUE TITLE
Esperanto translation team.

### ISSUE THREAD

**Issue by jakubfabijan** [xbmc/xbmc#19751]
I wanted to join Esperanto translation team for [Kodi Main](https://www.transifex.com/teamxbmc/kodi-main/) at Transifex, I sent request over a month ago, and I am still not added. I really want to help with translation, because Esperanto translation is only done in 19%.

**Comment by lrusak** [comment]
AFAIK we aren't using transifex anymore and have moved to weblate.

**Comment by gade01** [comment]
@jakubfabijan 
You're welcome to sign up for Weblate.
It's not officially open yet, but a lot of components are ready for translation.
Components not yet ready are locked.

**Comment by jakubfabijan** [comment]
Thank you :)
