### ISSUE TITLE
[Android] API to trigger an intent with extras?

### ISSUE THREAD

**Issue by Enigma3000** [xbmc/xbmc#19754]
[Android]

I'd like to use this function StartAndroidActivity(package,[intent,dataType,dataURI]) but also trigger an intent **with extras** - which currently is not possible?

To be more precise, I want to connect to a server via OpenVPN from a .py script from Kodi.

This is what is working in Tasker:

```
Send Intent
Action:android.intent.action.MAIN
Cat:None
Extra:**de.blinkt.openvpn.shortcutProfileName: PROFILENAME**
Package:de.blinkt.openvpn
Target:Activity

```
and this is my .py script but it's only taking me to tasker which is really not what I want. I don't want tasker to open at all just do the task silently.

`
import xbmc xbmc.executebuiltin('StartAndroidActivity(de.blinkt.openvpn,android.intent.action.MAIN,de.blinkt.openvpn.shortcutProfileName: PROFILENAME)')]
`

**Willing to assist any way I can.** Please get in touch.

**Comment by DaVukovic** [comment]
Please use the forums for support-questions
