### ISSUE TITLE
Audio passthrough doesn't work at all on ATV 4k

### ISSUE THREAD

**Issue by timemaster5** [xbmc/xbmc#19750]
Bug report

On Kodi Matrix 19.1, mkv files containing the EAC3 audio track are supposed to be decoded on the audio receiver if connected and audio passthrough is enabled

Describe the bug

Dolby Atmos mode of the receiver is not triggered. It seems like the passthrough doesn't do anything on ATV 4k.
Netflix works on the same setup, the receiver gets switched to the Atmos mode immediately.

Expected Behavior

The video containing the EAC3 track should be passed through directly to the receiver via HDMI without further processing.

Actual Behavior

Passthrough doesn't seem to work at all on ATV 4K.

Play any Dolby Atmos-enabled content, via smb, NFS, jellyfin or whatever, the receiver (correctly connected directly to the ATV 4k), doesn't switch to Atmos as it should.

Here is some additional context or explanation that might help:

I would like to confirm whether this is an API limitation of tvOS 14.5, or Kodi's bug. I've read on the VLC forum that passthrough is enabled only for a few apps like Netflix and iTunes.

Your Environment

Used Operating system:

  tvOS 14.5

Kodi version: 19.1 Matrix, tvOS

note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.

**Comment by BTopbas** [comment]
Same here. Today I want to watch a movie with Kodi. Here is audio info 
```
Audio
ID : 2
Format : AC-3
Format/Info : Audio Coding 3
Commercial name : Dolby Digital
Codec ID : A_AC3
Duration : 1 h 39 min
Bit rate mode : Constant
Bit rate : 384 kb/s
Channel(s) : 6 channels
Channel layout : L R C LFE Ls Rs
Sampling rate : 48.0 kHz
Frame rate : 31.250 FPS (1536 SPF)
Compression mode : Lossy
Stream size : 274 MiB (2%)
Title : DD 5.1
Language : English
```
When tried to open with Kodi with pass-through enabled sound is broken makes sizzle. With pass-through disabled low noise and out of sync. Not stable sound for watching a movie. I tried to play with the VLC(downloaded AppStore) app on ATV4. Works with no problem. Audio can go passthrough. And very clear good audio.

**Comment by timemaster5** [comment]
It could be related, but I am not sure. In my case the passthrough “works”, or more precisely do nothing. The sound is the same no matter it is turned on or off. By the same I mean without passing dolby data to the receiver. I tried in VLC too, and it behaves the same way - no dolby passthrough, that’s why I am asking whether it is a restriction of tvOS API.

Your problem seems to me more like enabled AC3 encoding on passthrough while it shouldn’t be. Check this option out. If I enable it, I can hear something similar to what you describe.

**Comment by davilla** [comment]
MrMC can passthrough Dolby Atmos. It's tricky as you have to demux the audio and play it using AVPlayer. AVPlayer is the only way to play Dolby Atmos under iOS/tvOS. See https://github.com/MrMC/libavaudiosink

**Comment by timemaster5** [comment]
Hmm, can we also use AVPlayer, maybe as an option or use it in parallel with video playback only to play audio? I don't know much about it obviously, but at least it explains why native apps like AirPlay, iTunes or some 3rd party apps like Netflix can do pass through, and the rest doesn't have access to this feature.

**Comment by piotrasd** [comment]
19.3 same story, even issue with DD 5.1 and DTS :(
