### ISSUE TITLE
JSON-RPC missing watched status for movies/episodes

### ISSUE THREAD

**Issue by mlaggner** [xbmc/xbmc#19764]
### Describe the bug
Here is a clear and concise description of what the problem is:

The JSON-RPC functions `VideoLibrary.GetMovies`, `VideoLibrary.GetMusicVideoDetails`, `VideoLibrary.GetEpisodeDetails`, `VideoLibrary.GetEpisodes` offer a bunch of information about the movies/episodes from the Kodi installation, but I cannot find any RPC function which tells me the watched state of the movie/episode

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Having a RPC function to get (and ideally set) the watched flag of movies/episodes

## Actual Behavior

No RPC function available for that. The only workaround at the moment is to export the internal data into a NFO file an read the NFO file. See the docs at https://kodi.wiki/view/JSON-RPC_API/v12

## Possible Fix

To add the watched flag (and playcount) into the  `VideoLibrary.GetMusicVideoDetails`, `VideoLibrary.GetEpisodeDetails` functions

### Debuglog

The debuglog can be found here:
not relevant

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [X] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 20.04, Windows 10, macOS 11.3.1
 - Kodi version: 18.6/19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
I'd have to look at the code but does setting the playcount > 0 work? See, https://kodi.wiki/view/JSON-RPC_API/v12#VideoLibrary.SetMovieDetails

**Comment by mlaggner** [comment]
I can test this in the evening, but without getting the old playcount via an JSON-RPC method, this value is probably _wrong_ (and I know Kodi users won't be happy if an external program messes up the playount)

Nevertheless, reading the watched state out of the JSON-RPC would be more interesting than setting (for setting the watched state I can write a NFO file with the new value and trigger Kodi to re-read it)

**Comment by lrusak** [comment]
> I can test this in the evening, but without getting the old playcount via an JSON-RPC method, this value is probably _wrong_ (and I know Kodi users won't be happy if an external program messes up the playount)
> 
> Nevertheless, reading the watched state out of the JSON-RPC would be more interesting than setting (for setting the watched state I can write a NFO file with the new value and trigger Kodi to re-read it)

Well just use the get method then to read the playcount first. https://kodi.wiki/view/JSON-RPC_API/v12#VideoLibrary.GetMovieDetails

I'm going to close this as it seems like a Support issue which should be taken to the forum. Thanks.

**Comment by mlaggner** [comment]
Thanks for the hint. I did some tests and looks like I can use that for my use-case
