### ISSUE TITLE
Support XBox's new Audio Passthrough (May 2021 update)

### ISSUE THREAD

**Issue by biiiipy** [xbmc/xbmc#19763]
*Searched but couldn't see any issues or PRs for this, so here it goes:*

XBox's May 2021 update includes a long waited feature of direct audio passthrough - https://news.xbox.com/en-us/2021/05/11/may-2021-xbox-update/ 
##### OS version: 10.0.19041.7771 (xb_flt_2105vb.210506-2030) / Shell version: 2105.0.2105.3001

It would be great for Kodi to implement support for this. (Probably only after Matrix releases on XBox)

(Btw, Plex has released a stable version incorporating this feature)

**Comment by lrusak** [comment]
Please use the forum for feature requests. Thanks!
