### ISSUE TITLE
Local theme.mp3 can't play.

### ISSUE THREAD

**Issue by xmha97** [xbmc/xbmc#19772]
Local theme.mp3 can't play :(
Where is this option in the Kodi?
![Kodi](https://user-images.githubusercontent.com/23485114/119095216-3e800400-ba27-11eb-89f1-7988fb92378d.png)

**Comment by KarellenX** [comment]
@xmha97 

I have lost count of how many times I have asked you to take your questions to the forum.

Speak to the add-on developer and the skin author. 

It is not a Kodi core issue.
