### ISSUE TITLE
Clean install of 19.1 crashes on startup.  Clean install of 19.0 works fine.

### ISSUE THREAD

**Issue by robross0606** [xbmc/xbmc#19778]
### Describe the bug
I had a running installation of 19.0 x64 on Windows which was working fine.  Upgraded to 19.1 and Kodi now immediately crashes after showing the startup screen.  I've completely uninstalled Kodi, removed my settings from AppData and reinstalled.  Same problem.  Reinstalling 19.0 works fine.

Log files show no useful data I can discern.

## Expected Behavior
Kodi should start up with clean installation.

## Actual Behavior
Kodi crashes hard on startup and writes dump files.

### Debuglog
The log can be found here:
[logs.zip](https://github.com/xbmc/xbmc/files/6523782/logs.zip)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Tried on two different Dell laptops from very different CPU generations:  XPS 15 9850 and G3 3579
 - Operating system version/name: Windows 10 Pro X64 Build 19042.985
 - Kodi version: 19.1

**Comment by shmal** [comment]
I see the same issue. Tracked my issue down to a null pointer in WSDiscoveryWin32.cpp.  For some reason the discovery returns a valid list but the next item is null. The code dereferences list->Next without validating it first, causing the crash.  

Changing line 63 to:    
`  
if (list && address && list->Next && list->Next->Element)
`
fixes the crash (or hides it).

Not sure what on the network is providing the buggy list yet. Will keep looking.

**Comment by shmal** [comment]
Ok, I discovered the device on my network that is sending the message. It is a fairly old Samsung SmartCam.

Added some logging and got this:

`
2021-05-24 20:36:40.958 T:12144   ERROR <general>: [WS-Discovery]: Received a null list entry from address 192.XXX.XXX.XXX:3702, URI = http://www.onvif.org/ver10/network/wsdl, LocalName = NetworkVideoTransmitter, list->Next = NULL
`
It looks like checking the list->Next for null is probably sufficient to fix the problem.

**Comment by fuzzard** [comment]
Im sure @thexai might be able to provide more, but i wonder if the following is correct

https://github.com/xbmc/xbmc/blob/3228ed929955fddc0655c44acb84530fea0145e7/xbmc/platform/win32/network/WSDiscoveryWin32.cpp#L65

Should it be just 

```
const std::wstring type(list->Element->LocalName);
```

checking the current element, and therefore, should it also be doing a loop over the list?

**Comment by shmal** [comment]
@fuzzard I was just wondering the same thing, it does look like that may have been the intent. 

If so, changing line 63 to also include a check for list->Element may be helpful, to avoid any malformed message errors.

I just ran a test with your change and no longer get the crash either. 

I also confirmed the original 19.1 install works fine with the camera unplugged.  The moment I plug it in, it crashes.

**Comment by thexai** [comment]
This is more elaborated solution that one in PR:

```c++
  if (address && list)
  {
    const std::wstring addr(address);
    std::wstring type(L"Unspecified");
    WSD_NAME_LIST* pList = list; // first element of list

    do
    {
      if (pList->Element && pList->Element->LocalName)
        type = std::wstring(pList->Element->LocalName);
      if (pList->Next)
        pList = pList->Next; // next element of list
      else
        pList = nullptr; // end of list
    }
    while (type != L"Computer" && pList != nullptr);
```

I can not test on Visual Studio now.... is codded with Notepad 😆

Should admit find "Computer" in any element of the list and (for debug proposes) shows in log all devices with any "type" description even if not sends "Next" element in list. e.g. "NetworkVideoTransmitter" is send in the first element of list.

Also I think is well protected against nullptr.

Later or tomorrow I will update the PR....

**Comment by jjd-uk** [comment]
The issue on this thread looks like it could be the same problem, https://forum.kodi.tv/showthread.php?tid=362788

**Comment by shmal** [comment]
> This is more elaborated solution that one in PR:
>
> I can not test on Visual Studio now.... is coded with Notepad 😆
> 
> Should admit find "Computer" in any element of the list and (for debug proposes) shows in log all devices with any "type" description even if not sends "Next" element in list. e.g. "NetworkVideoTransmitter" is send in the first element of list.
> 
> Also I think is well protected against nullptr.
> 
> Later or tomorrow I will update the PR....
> 
> **EDIT**
> As additional context:
> 
> The first item in the list is usually the role of the device:
> 
> e.g. "Device" "Repeater" "Proxy"
> 
> The most common case is:
> 
> 1 element -> Device
> 2 element -> Computer, Printer, etc.
> 3 element -> NULL
> 
> And because this, original code expects found "NetworkVideoTransmitter" in the second element of list

I compiled my local copy with your latest change and it is working with the camera plugged in. Thank you for the additional context too, that is very helpful!

**Comment by thexai** [comment]
If you look at the log (debug level) now a message should appear saying that the camera has been found:

[WS-Discovery]: HELLO packet received...

**Comment by shmal** [comment]
> If you look at the log (debug level) now a message should appear saying that the camera has been found:
> 
> [WS-Discovery]: HELLO packet received...

Yes, it is there, along with my original added log statement to verify the packet details:

`
1-05-25 12:06:11.065 T:20764   DEBUG <general>: [WS-Discovery]: Received an unexpected HELLO packet format (only 1 entry in list). Address 192.###.###.###:3702, Uri = http://www.onvif.org/ver10/network/wsdl, LocalName = NetworkVideoTransmitter
2021-05-25 12:06:11.066 T:20764   DEBUG <general>: [WS-Discovery]: HELLO packet received: device type = 'NetworkVideoTransmitter', device address = '192.###.###.###:3702'
`

Probably didn't need to hide the private ip!

Thanks for the quick replies to get this patched, I'll grab the nighly build after this closes out.

**Comment by thexai** [comment]
Matrix build with the fix:
http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20210525-fd5acfb5-Matrix-x64.exe

**Comment by shmal** [comment]
Installed, no more crash. Confirmed the camera appears in the log file as well.

Thanks!

**Comment by buers** [comment]
I had the same problem, which is also fixed by this patch - thanks! Some small comments on the code.

CLog::Log(LOGDEBUG,              "[WS-Discovery]: HELLO packet received: device type = '{}', device address = '{}'",              FromW(type), FromW(addr));

This logging will be done for type == L"Computer" of for whatever happens to be the last Element in the list, if there is no Computer-type at all in the list. To me it would seem more consistent to log either only Computers or all list entries.

The "      if (pList->Next)" is superflous (pList is assigned a nullptr anyway in the else clause), when I don't oversee anything stupid. 

BTW. For me it was not a Camera, but my company Windows 10 computer used inside the home office, that crashed Kodi (running on another computer).

**Comment by showmak** [comment]
> Matrix build with the fix:
> http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20210525-fd5acfb5-Matrix-x64.exe
> 
> Also includes audio passthrough fix (#15490)

I have the same problem but I can't download the file, it does not exist.

**Comment by thexai** [comment]
The fix is already merged, download a Matrix nightlie from here:
http://mirrors.kodi.tv/nightlies/windows/win64/Matrix/

**Comment by robross0606** [comment]
Any idea when this will end up in an official release?
