### ISSUE TITLE
Lagging and keep buffering when play dolby vision with matrix on Shield TV Pro. 

### ISSUE THREAD

**Issue by MrNo00** [xbmc/xbmc#19785]
### Describe the bug
Here is a clear and concise description of what the problem is:

Lagging and keep buffering when play dolby vision with matrix on Shield TV Pro. And it will just happen on some files, not all Dolby Vision file.
It can play normal for the beginning, the color and audio are all right. But about 1 or 2 minutes later, the playback will be paused and the buffer loading circle keeps showing for a long time, maybe it can continue to play about 5 seconds more, but it will just keep loading more time after that.
And the network is not the cause of the issue, the box and Nas is connected with LAN, and I tried to play other remux files right after the issue is happening, 80gb HDR remux can be played without any issue.

I tried with Emby Server and direct FTP file, same issue there.

First time it happens when playing WandaVision S01E01&S01E02, but everything normal when playing S01E03 ~ S01E09. I changed the source file to another team's work, I can finally play.
And this time, it happens with Hamiton, the former HDR version plays perfectly, but the DV vision shows the buffer issue. I tried with my phone (galaxy note 10+) this time, Kodi 19 connect with Emby by WIFI, the file can play smoothly without the buffer issue, but the Dolby vision color is not right, shows green.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Play those Dolby Vision file without the buffer issue, if the network is all right.

## Actual Behavior

Play those Dolby Vision file with lagging and buffer issue, though the network is capable to play big HDR remux file.
And the log seems that it Kodi tried to cache the video and resume the video, but a seek position behavior by itself will just reset the cache completely. And the situation keeps coming over and over again, cache -> seek -> reset.
And the situation is can be seen if you are watching the progress bar, you can see the cached time will disappear suddenly, then come back, then disappear again, then come back. 

## Possible Fix

Seems like an issue when playback some specific dolby vision file, the file won't be cached right.

### To Reproduce

1. The files:
Hamilton.2020.2160p.WEB-DL.DDP5.1.DoVi.HEVC-LEWIS.mp4
WandaVision.S01E01.2160p.DSNP.WEB-DL.DDP5.1.Atmos.DV.x265-MZABI
WandaVision.S01E02.2160p.DSNP.WEB-DL.DDP5.1.Atmos.DV.x265-MZABI

### Debuglog

The debuglog can be found here:
[kodi-issues.log](https://github.com/xbmc/xbmc/files/6529515/kodi-issues.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

A video to show the cache's disappearance in the progress bar, it happens at 14, 18, 22, 24, 26, 30, 33 and more seconds. 
https://user-images.githubusercontent.com/66369455/119293053-3cff4780-bc84-11eb-9ac9-33171e4a205d.mp4

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Open debug log mode, and open ffmpeg detail log at the same time would strangely fix the problem. The cached time will keep in the progress bar. 

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 9 / Shield 8.2.2
 - Kodi version: 19.0/19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment]
Please provide a debug log.

**Comment by MrNo00** [comment]
> Please provide a debug log.

Debug log added. 
And I tried for many times, an interest thing happened.  
The video is most likely paused to load at 57 seconds, and if I open ffmpeg detail log, where will be no issues at all. The file can be played normal, no pause, no loading, no lagging. 

And the log seems it tried to cache the video and resume the video, but a seek position behavior by the system will just reset the cache. And the situation keeps coming over and over again. 

[kodi-issue.log](https://github.com/xbmc/xbmc/files/6528436/kodi-issue.log)

**Comment by MrNo00** [comment]
> Please provide a debug log.

Debug log added.
And I tried for many times, an interest thing happened. The video is most likely paused to load at 57 seconds, and if I open ffmpeg detail log, there will be no issue at all. The file can be played normal, no pause, no loading, no lagging.

And the log seems that it Kodi tried to cache the video and resume the video, but a seek position behavior by itself will just reset the cache completely. And the situation keeps coming over and over again, cache -> seek -> reset.
And the situation is can be seen if you are watching the progress bar, you can see the cached time will disappear suddenly, then come back, then disappear again, then come back. And as I said above about the it may have the issue most likely 57 seconds, it might just the "disappeared cache time".
[kodi-issues.log](https://github.com/xbmc/xbmc/files/6528457/kodi-issues.log)

**Comment by arnova** [comment]
It looks like a badly muxed file with bad a/v sync. Just to be clear: You're saying that the issue disappears as soon as you enable ffmpeg component logging?

**Comment by MrNo00** [comment]
Yes, it's really strange, the issue disappears as soon as I enable ffmpeg component logging.

**Comment by MrNo00** [comment]
> EDIT: Please try whether setting buffermode to 3 (no buffer) in your advancedsettings.xml changes anything.

I will try for that.

**Comment by arnova** [comment]
> EDIT: As you can see in the video, the cached time will disappear in the progress bar. This situation is also gone if I enable ffmpeg component logging.

That's because internally 2 caches are used and when a seek occurs, the caches are swapped. In your case it's probably also reset because the seek request is outside what the 2 caches already have cached. I think the logic could be improved preventing this but I need to think about that. I also don't have any samples, which makes it a bit harder to come up with a fix.

Btw. one other thing you can try: as soon as the video starts pause it for a few seconds and then play again and see whether that makes a difference.

**Comment by MrNo00** [comment]
> Btw. one other thing you can try: as soon as the video starts pause it for a few seconds and then play again and see whether that makes a difference.

Tried before, still can't play.


And about the seek, would a normal video has this seek behaviour? Cause I didn't request a seek, I just opened the file and let it play itself. 

I mean the probable cause of this situation is the cache logic or the self seek request.

**Comment by arnova** [comment]
> > Btw. one other thing you can try: as soon as the video starts pause it for a few seconds and then play again and see whether that makes a difference.
> 
> Tried before, still can't play.
> 
> And about the seek, would a normal video has this seek behaviour? Cause I didn't request a seek, I just opened the file and let it play itself.
> 
> I mean the probable cause of this situation is the cache logic or the self seek request.

I have an idea what the problem could be. Could you please provide a debug log with ffmpeg debug logging enabled (=with file playing without a problem)?

**Comment by MrNo00** [comment]
> I have an idea what the problem could be. Could you please provide a debug log with ffmpeg debug logging enabled (=with file playing without a problem)?

Debug log added. The file is too big so I uploaded it to my personal repository.
No seek -> reset behavior anymore.

https://github.com/MrNo00/Temp/raw/main/kodi.log

**Comment by arnova** [comment]
#19811 hopefully fixes your issue.

Please note that since you're using ftp, there will always be a performance penalty with files like this since ftp is a streaming protocol. If you want to use a streaming protocol I strongly recommend switching to eg. http/https or webdav since those support multisession which are much better in handling situations like this.

**Comment by MrNo00** [comment]
Thanks, hopefully it can be fixed in future versions.
And I will try for WebDAV or some other protocols.

KODI is really a great work, thanks.

**Comment by arnova** [comment]
@MrNo00 : Could you give https://jenkins.kodi.tv/job/Android-ARM64/18484/artifact/kodi-20210526-24b35839-PR19811-merge-arm64-v8a.apk a try and see whether it fixes your issue?

**Comment by MrNo00** [comment]
I tried just now, I think the issue is still there. Let me get you the log.

**Comment by MrNo00** [comment]
sorry, the files are deleted, i may try them after I re-download it.

**Comment by MrNo00** [comment]
Tried, the issue is also there. And in the progress bar, the cache is still blinking.

[e1.log](https://github.com/xbmc/xbmc/files/6550534/e1.log)
[e2.log](https://github.com/xbmc/xbmc/files/6550535/e2.log)

**Comment by arnova** [comment]
> Tried, the issue is also there. And in the progress bar, the cache is still blinking.
> 
> [e1.log](https://github.com/xbmc/xbmc/files/6550534/e1.log)
> [e2.log](https://github.com/xbmc/xbmc/files/6550535/e2.log)

FYI: The blinking cache is "normal". It means that internally the 2 caches are swapped (when a seek occurs). 

Could you please give https://jenkins.kodi.tv/job/Android-ARM64/18496/artifact/kodi-20210527-b180ed13-PR19811-merge-arm64-v8a.apk another try?

**Comment by MrNo00** [comment]
I will try about 3 hours later. 

And the reason why I mentioned the blinking cache, is that when the video is playing normally (when the ffmpeg logging was opened), there will be no blinking anymore, at least I can't see the situation. 
So maybe I just noticed an irrelevant behavior. 

I would give you a feedback as soon as I tried.

**Comment by MrNo00** [comment]
Unfortunately, it's still the same. 
Here's the logs.

[Ham.log](https://github.com/xbmc/xbmc/files/6554560/Ham.log)
[Wanda1.log](https://github.com/xbmc/xbmc/files/6554561/Wanda1.log)
[Wanda2.log](https://github.com/xbmc/xbmc/files/6554572/Wanda2.log)

**Comment by arnova** [comment]
Ok, one last try: https://jenkins.kodi.tv/job/Android-ARM64/18506/artifact/kodi-20210527-ebfd4551-PR19811-merge-arm64-v8a.apk . It contains some additional logging, so please provide new logs with this version.

Please note that I'm starting to believe that the actual issue may be your (specific) files and/or the ffmpeg-version we're using.....

**Comment by MrNo00** [comment]
New logs uploaded. 

[ham-new.log](https://github.com/xbmc/xbmc/files/6555420/ham-new.log)
[wanda1-new.log](https://github.com/xbmc/xbmc/files/6555421/wanda1-new.log)
[wanda2-new.log](https://github.com/xbmc/xbmc/files/6555423/wanda2-new.log)

I think the most strange thing in this issue is that enabling the ffmpeg logging would fix the problem. That's really strange.

**Comment by MrNo00** [comment]
UPDATE: In this version, If the ffmpeg logging enbled, the Hamiton file even can't be played at the beginning, it says 'One or more items failed to play. Check the log for more information about this message.'
WandaVision E02 still has the issue. But E01 is fixed this way.

**Comment by arnova** [comment]
> > EDIT: Please try whether setting buffermode to 3 (no buffer) in your advancedsettings.xml changes anything.
> 
> I will try for that.

Forgot to ask: did you try the above (set buffermode to 3)?

**Comment by MrNo00** [comment]
I tried, it would froze earlier, at about 39 seconds.

[kodi.log](https://github.com/xbmc/xbmc/files/6555657/kodi.log)

**Comment by arnova** [comment]
Hmmm, then I think the only option that remains is trying whether using http/webdav fixes the problem for you.

**Comment by MrNo00** [comment]
Ok, I would try some other protocols. 

But I think there's still some bugs, because they can be played if the ffmpeg logging enabled in version 19.1. 
Means that KODI 19.1 is able to play the files normally, but just can't without some debug configuration.

**Comment by MrNo00** [comment]
> Ok, one last try: https://jenkins.kodi.tv/job/Android-ARM64/18506/artifact/kodi-20210527-ebfd4551-PR19811-merge-arm64-v8a.apk . It contains some additional logging, so please provide new logs with this version.

Is this version stable enough? Should I roll it back to 19.1?

**Comment by fraee** [comment]
> Hmmm, then I think the only option that remains is trying whether using http/webdav fixes the problem for you.

I have the same problem. There will be buffer when playing Dolby Vision. I switched from FTP to WebDAV, which perfectly solved this problem. Thank you！But what puzzles me is why the 4K video file of 70g from ftp can be played and the video of 8G Dolby's vision can be buffered  ....never mind....
It is suggested that if you have the same problem, you can try to play the video file from the local hard disk first to see whether the transmission mode is wrong or the video file is wrong.

**Comment by MrNo00** [comment]
> It is suggested that if you have the same problem, you can try to play the video file from the local hard disk first to see whether the transmission mode is wrong or the video file is wrong.

Really appreciate, will try this way later. It would be great if it's fixable. 

Btw, is this works for you? Could you give a try? 
> Open debug log mode, and open ffmpeg detail log at the same time would strangely fix the problem. The cached time will keep in the progress bar.

**Comment by fraee** [comment]
> > It is suggested that if you have the same problem, you can try to play the video file from the local hard disk first to see whether the transmission mode is wrong or the video file is wrong.
> 
> Really appreciate, will try this way later. It would be great if it's fixable.
> 
> Btw, is this works for you? Could you give a try?
> 
> > Open debug log mode, and open ffmpeg detail log at the same time would strangely fix the problem. The cached time will keep in the progress bar.

emm...Kodi's FTP file management mode has been deleted and the FTP service has stopped.I can't test it again,sorry.

**Comment by arnova** [comment]
> I have the same problem. There will be buffer when playing Dolby Vision. I switched from FTP to WebDAV, which perfectly solved this problem. Thank you！But what puzzles me is why the 4K video file of 70g from ftp can be played and the video of 8G Dolby's vision can be buffered ....never mind....

FYI: The problem is not the size of the files, the problem is how the audio/video is interleaved in the files... And since http(=webdav) supports multi-session (and ftp does not), we can open 2 connections for both audio and video which "solves" the problem...

**Comment by fraee** [comment]
> > I have the same problem. There will be buffer when playing Dolby Vision. I switched from FTP to WebDAV, which perfectly solved this problem. Thank you！But what puzzles me is why the 4K video file of 70g from ftp can be played and the video of 8G Dolby's vision can be buffered ....never mind....
> 
> FYI: The problem is not the size of the files, the problem is how the audio/video is interleaved in the files... And since http(=webdav) supports multi-session (and ftp does not), we can open 2 connections for both audio and video which "solves" the problem...

thank you for your reply！It seems that webdav is the best sharing protocol, but unfortunately not all players support it.

**Comment by jrd-rocks** [comment]
Just wanted to add i have the exact same problem on kodi 19.3. I thought it was a speed issue, as network-speed issue as playback was *barely* ok on a samba share (small stuttering), but unwatchable from an internet stream. But i wasn't satisfied, and kept searching, then i found this issue, and yeahi experience the same symptoms, after a minute (57 seconds) the cache just stays empty.

Anyway, after reading this, trying same sized non-DV (and non-mp4) streams they play perfectly fine (no wonder really my internet connection while not fast, can download the files in half the time of their duration). Which made me sure it was a kodi player issue. I have no solution. But as a workaround i installed Just (Video) Player (which plays dolby vision just fine, even in mkv's which kodi can't handle, keep it mind it doesn't support samba, just basic (http)streams), and use it as external player only for dobly vision content with the following `playercorefactory.xml`
```
<playercorefactory>
    <players>
        <player name="JustPlayer" type="ExternalPlayer" audio="true" video="true">
            <filename>com.brouken.player</filename>
            <playcountminimumtime>120</playcountminimumtime>
        </player>
        
    </players>
    <rules action="prepend"
        <rule video="true" player="dvdplayer">
            <rule filename=".*DV.*|.*DoVi.*" player="JustPlayer"/>
        </rule>
    </rules>
</playercorefactory>
```

**Comment by MrNo00** [comment]
> Just wanted to add i have the exact same problem on kodi 19.3. I thought it was a network-speed issue as playback was _barely_ ok on a samba share (small stuttering), but unwatchable (video halted 10+ secs, then stuttered, and when it got too bad the playback just ended) from an internet stream. But i wasn't satisfied, and kept searching, then i found this issue, and yeah i experience the same symptoms, after a minute (57 seconds) the cache just stays empty and the problems start.
> 
> Anyway, after reading this, i started trying same sized non-DV (and non-mp4) streams they play perfectly fine (no wonder really my internet connection while not fast, can download the files in half the time of their duration). Which made me sure it was a kodi player issue. I have no solution. But as a workaround i installed Just (Video) Player (which plays dolby vision just fine, even in mkv's which kodi can't handle, keep it mind it doesn't support samba, just basic (http)streams), and use it as external player only for dobly vision content with the following `playercorefactory.xml`
> 
> ```
> <playercorefactory>
>     <players>
>         <player name="JustPlayer" type="ExternalPlayer" audio="true" video="true">
>             <filename>com.brouken.player</filename>
>             <playcountminimumtime>120</playcountminimumtime>
>         </player>
>         
>     </players>
>     <rules action="prepend"
>         <rule video="true" player="dvdplayer">
>             <rule filename=".*DV.*|.*DoVi.*" player="JustPlayer"/>
>         </rule>
>     </rules>
> </playercorefactory>
> ```


Good way to solve the problem.

**Comment by MrNo00** [comment]
> Just wanted to add i have the exact same problem on kodi 19.3. I thought it was a network-speed issue as playback was _barely_ ok on a samba share (small stuttering), but unwatchable (video halted 10+ secs, then stuttered, and when it got too bad the playback just ended) from an internet stream. But i wasn't satisfied, and kept searching, then i found this issue, and yeah i experience the same symptoms, after a minute (57 seconds) the cache just stays empty and the problems start.
> 
> Anyway, after reading this, i started trying same sized non-DV (and non-mp4) streams they play perfectly fine (no wonder really my internet connection while not fast, can download the files in half the time of their duration). Which made me sure it was a kodi player issue. I have no solution. But as a workaround i installed Just (Video) Player (which plays dolby vision just fine, even in mkv's which kodi can't handle, keep it mind it doesn't support samba, just basic (http)streams), and use it as external player only for dobly vision content with the following `playercorefactory.xml`
> 
> ```
> <playercorefactory>
>     <players>
>         <player name="JustPlayer" type="ExternalPlayer" audio="true" video="true">
>             <filename>com.brouken.player</filename>
>             <playcountminimumtime>120</playcountminimumtime>
>         </player>
>         
>     </players>
>     <rules action="prepend"
>         <rule video="true" player="dvdplayer">
>             <rule filename=".*DV.*|.*DoVi.*" player="JustPlayer"/>
>         </rule>
>     </rules>
> </playercorefactory>
> ```


Good way to solve the problem. As for me, webdav can fix the problem. 

I think its a wired compatibility issue between Kodi Ftp and ffmpeg when playing some DV mp4 files. Some files can play normally but others can't.
Have you tried to enable debug log mode, and open ffmpeg detail log at the same time? The bugged files could also play well on my device, that's really strange.

**Comment by jrd-rocks** [comment]
> ....
> 
> I think its a wired compatibility issue between Kodi Ftp and ffmpeg when playing some DV mp4 files. Some files can play normally but others can't. Have you tried to enable debug log mode, and open ffmpeg detail log at the same time? The bugged files could also play well on my device, that's really strange.

Enabling or disabling logging made no difference to me. I'm seeing the following in the logs, which seems it shouldn't be there.

```
2021-11-27 14:11:53.226 T:23669   DEBUG <general>: CFileCache::Process - <https://_**removed**_/Hawkeye.2021.S01E01.Never.Meet.Your.Heroes.2160p.WEB-DL.DDP5.1.Atmos.DV.H.265-TEPES.mp4> source read hit eof
2021-11-27 14:11:53.226 T:23565   DEBUG <general>: CFileCache::Seek - <https://_**removed**_/Hawkeye.2021.S01E01.Never.Meet.Your.Heroes.2160p.WEB-DL.DDP5.1.Atmos.DV.H.265-TEPES.mp4> waiting for position 133833818
2021-11-27 14:11:53.226 T:23565 WARNING <general>: CFileCache::Seek - <https://_**removed**_/Hawkeye.2021.S01E01.Never.Meet.Your.Heroes.2160p.WEB-DL.DDP5.1.Atmos.DV.H.265-TEPES.mp4> failed to get remaining data
2021-11-27 14:11:53.226 T:23565   ERROR <general>: ffmpeg[0x7b0a9420X]: [mov,mp4,m4a,3gp,3g2,mj2] stream 1, offset 0x7fa245a: partial file
2021-11-27 14:11:53.226 T:23565    INFO <general>: Process - eof reading from demuxer
2021-11-27 14:11:53.226 T:23565    INFO <general>: CVideoPlayer::OnExit()
2021-11-27 14:11:53.226 T:23565    INFO <general>: VideoPlayer: eof, waiting for queues to empty
```
[kodi.log.gz](https://github.com/xbmc/xbmc/files/7611792/kodi.log.gz)

**Comment by MrNo00** [comment]
> > ....
> > I think its a wired compatibility issue between Kodi Ftp and ffmpeg when playing some DV mp4 files. Some files can play normally but others can't. Have you tried to enable debug log mode, and open ffmpeg detail log at the same time? The bugged files could also play well on my device, that's really strange.
> 
> Enabling or disabling logging made no difference to me. I hadn't looked at the logs yet, it's hard getting them out of kodi but your comment made me look since it might be good info, I'm seeing the following in the logs, which seems it shouldn't be there.
> 
> ```
> 2021-11-27 14:11:53.226 T:23669   DEBUG <general>: CFileCache::Process - <https://_**removed**_/Hawkeye.2021.S01E01.Never.Meet.Your.Heroes.2160p.WEB-DL.DDP5.1.Atmos.DV.H.265-TEPES.mp4> source read hit eof
> 2021-11-27 14:11:53.226 T:23565   DEBUG <general>: CFileCache::Seek - <https://_**removed**_/Hawkeye.2021.S01E01.Never.Meet.Your.Heroes.2160p.WEB-DL.DDP5.1.Atmos.DV.H.265-TEPES.mp4> waiting for position 133833818
> 2021-11-27 14:11:53.226 T:23565 WARNING <general>: CFileCache::Seek - <https://_**removed**_/Hawkeye.2021.S01E01.Never.Meet.Your.Heroes.2160p.WEB-DL.DDP5.1.Atmos.DV.H.265-TEPES.mp4> failed to get remaining data
> 2021-11-27 14:11:53.226 T:23565   ERROR <general>: ffmpeg[0x7b0a9420X]: [mov,mp4,m4a,3gp,3g2,mj2] stream 1, offset 0x7fa245a: partial file
> 2021-11-27 14:11:53.226 T:23565    INFO <general>: Process - eof reading from demuxer
> 2021-11-27 14:11:53.226 T:23565    INFO <general>: CVideoPlayer::OnExit()
> 2021-11-27 14:11:53.226 T:23565    INFO <general>: VideoPlayer: eof, waiting for queues to empty
> ```
> 
> [kodi.log.gz](https://github.com/xbmc/xbmc/files/7611792/kodi.log.gz)

There's much more dv sources than before, hope it will be fixed in the future.

**Comment by arnova** [comment]
The problem is probably that FTP doesn't support multisession to handle files with (poor) a/v interleaving. Try switching to http/https/webdav....

**Comment by fraee** [comment]
> > > ....
> > > I think its a wired compatibility issue between Kodi Ftp and ffmpeg when playing some DV mp4 files. Some files can play normally but others can't. Have you tried to enable debug log mode, and open ffmpeg detail log at the same time? The bugged files could also play well on my device, that's really strange.
> > 
> > 
> > Enabling or disabling logging made no difference to me. I hadn't looked at the logs yet, it's hard getting them out of kodi but your comment made me look since it might be good info, I'm seeing the following in the logs, which seems it shouldn't be there.
> > ```
> > 2021-11-27 14:11:53.226 T:23669   DEBUG <general>: CFileCache::Process - <https://_**removed**_/Hawkeye.2021.S01E01.Never.Meet.Your.Heroes.2160p.WEB-DL.DDP5.1.Atmos.DV.H.265-TEPES.mp4> source read hit eof
> > 2021-11-27 14:11:53.226 T:23565   DEBUG <general>: CFileCache::Seek - <https://_**removed**_/Hawkeye.2021.S01E01.Never.Meet.Your.Heroes.2160p.WEB-DL.DDP5.1.Atmos.DV.H.265-TEPES.mp4> waiting for position 133833818
> > 2021-11-27 14:11:53.226 T:23565 WARNING <general>: CFileCache::Seek - <https://_**removed**_/Hawkeye.2021.S01E01.Never.Meet.Your.Heroes.2160p.WEB-DL.DDP5.1.Atmos.DV.H.265-TEPES.mp4> failed to get remaining data
> > 2021-11-27 14:11:53.226 T:23565   ERROR <general>: ffmpeg[0x7b0a9420X]: [mov,mp4,m4a,3gp,3g2,mj2] stream 1, offset 0x7fa245a: partial file
> > 2021-11-27 14:11:53.226 T:23565    INFO <general>: Process - eof reading from demuxer
> > 2021-11-27 14:11:53.226 T:23565    INFO <general>: CVideoPlayer::OnExit()
> > 2021-11-27 14:11:53.226 T:23565    INFO <general>: VideoPlayer: eof, waiting for queues to empty
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [kodi.log.gz](https://github.com/xbmc/xbmc/files/7611792/kodi.log.gz)
> 
> There's much more dv sources than before, hope it will be fixed in the future.

https://github.com/xbmc/xbmc/issues/19785#issuecomment-864510794

**Comment by MrNo00** [comment]
> 

Maybe, some dv files are perfect but others not.
Right now I'm using webdav to play the files. 

But because I'm using Emby as my media server and webdav can't be set as Emby media files' remote path, I need to seek the files manually every time and the playback progress wouldn't be sync with Emby. It's not that convenient.

A simple hope to fix the issue directly, though it can be "fixed" by changing the protocol to webdav or set a special external player for the files.

But maybe play HDR10 version is the simplest solution. 🤣

**Comment by MrNo00** [comment]
> The problem is probably that FTP doesn't support multisession to handle files with (poor) a/v interleaving. Try switching to http/https/webdav....

Maybe, some DV files are perfect but others are not.
Right now I'm using WebDAV to play the files.

But because I'm using Emby as my media server and WebDAV can't be set as Emby media files' remote path, I need to seek the files manually every time and the playback progress wouldn't be synced with Emby. It's not that convenient.
A simple hope to fix the issue directly, though it can be "fixed" by changing the protocol to WebDAV or setting a special external player for the files.

But maybe playing HDR10 version is the simplest solution. 🤣

**Comment by Nuklear92** [comment]
> The problem is probably that FTP doesn't support multisession to handle files with (poor) a/v interleaving. Try switching to http/https/webdav....

Could you point me to a quick tutorial on how and where do I make this change within Kodi. I'm also struggling with this issue of Dolby Vision files buffering non stop where any other video file I play stream smoothly. 🤔

**Comment by MrNo00** [comment]
> > The problem is probably that FTP doesn't support multisession to handle files with (poor) a/v interleaving. Try switching to http/https/webdav....
> 
> Could you point me to a quick tutorial on how and where do I make this change within Kodi. I'm also struggling with this issue of Dolby Vision files buffering non stop where any other video file I play stream smoothly without any hiccups. 🤔


How do you share the media files? via Ftp? 
the quickest way is try to share the files via WebDav, or copy them to the local storage.

**Comment by Nuklear92** [comment]
> > > The problem is probably that FTP doesn't support multisession to handle files with (poor) a/v interleaving. Try switching to http/https/webdav....
> 
> > 
> 
> > Could you point me to a quick tutorial on how and where do I make this change within Kodi. I'm also struggling with this issue of Dolby Vision files buffering non stop where any other video file I play stream smoothly without any hiccups. 🤔
> 
> 
> 
> 
> 
> How do you share the media files? via Ftp? 
> 
> the quickest way is try to share the files via WebDav, or copy them to the local storage.

I'm mainly streaming the files, I saw another workaround which someone posted about using Just (Video) Player as an external player in Kodi to stream DV files, do you know by any chance how do I set up external player in Kodi? I mean, I had never messed with that personally as I never had any issues streaming files until recently where I'm seeing more and more DV files emerging and decided to try playing those instead but came across this situation affecting Kodi player. 🤷‍♂️

**Comment by MrNo00** [comment]
> Just wanted to add i have the exact same problem on kodi 19.3. I thought it was a network-speed issue as playback was _barely_ ok on a samba share (small stuttering), but unwatchable (video halted 10+ secs, then stuttered, and when it got too bad the playback just ended) from an internet stream. But i wasn't satisfied, and kept searching, then i found this issue, and yeah i experience the same symptoms, after a minute (57 seconds) the cache just stays empty and the problems start.
> 
> Anyway, after reading this, i started trying same sized non-DV (and non-mp4) streams they play perfectly fine (no wonder really my internet connection while not fast, can download the files in half the time of their duration). Which made me sure it was a kodi player issue. I have no solution. But as a workaround i installed Just (Video) Player (which plays dolby vision just fine, even in mkv's which kodi can't handle, keep it mind it doesn't support samba, just basic (http)streams), and use it as external player only for dobly vision content with the following `playercorefactory.xml`
> 
> ```
> <playercorefactory>
>     <players>
>         <player name="JustPlayer" type="ExternalPlayer" audio="true" video="true">
>             <filename>com.brouken.player</filename>
>             <playcountminimumtime>120</playcountminimumtime>
>         </player>
>         
>     </players>
>     <rules action="prepend">
>         <rule video="true" player="dvdplayer">
>             <rule filename=".*DV.*|.*DoVi.*" player="JustPlayer"/>
>         </rule>
>     </rules>
> </playercorefactory>
> ```

@Nuklear92 maybe you should follow @jrd-rocks solution.

**Comment by pho084** [comment]
another workaround that worked for me at least for some videos was to convert the mp4 to mkv using mkvtoolnix. it will retain the DV properties and get rid of the stuttering -- did not work for all videos though and there is something weird with 19.3 in that regard too (DV mkvs played better on previous versions iirc)

**Comment by KyleSanderson** [comment]
So, the solution is a bit of a joke. This is a bug in DVDPlayer, it reads the MP4 stream packet by packet, and there's no "readahead" for MP4 files. Converting the same MP4 file to MKV results in a proper readahead and stream, and with mp4 it does the packet by packet reading (4-12MB chunks). Super annoying, but this has nothing to do with the actual vfs underneath, and is instead a bug in the actual player. This is why Just Player works, and Kodi is still broken.

**Comment by MrNo00** [comment]
Wow, a new reply after nearly half a year. 

Webdav can play the "broken" MP4 files smoothly in Kodi when FTP can not, which confuses me. 
And what confuses me the most is that the "broken" MP4 files can be played smoothly in Kodi with FTP when FFmpeg debug logging is enabled.

**Comment by MrNo00** [comment]
> 

Hi, I discovered that webdav server path is able to  add into the emby media library share path, so that the broken MP4 dv files can play normally. 
But a new problem came out, all the media files could not get the external subtitles in the media folders.
