### ISSUE TITLE
Kodi 19.1 Android - No MPEG2 DVD file playback

### ISSUE THREAD

**Issue by Europe57** [xbmc/xbmc#19787]
### Describe the bug
Here is a clear and concise description of what the problem is:

MPEG2 DVD files are no longer playable except by disabling MediaCodec hardware acceleration. Under version 19.0 the files were readable without problems with hardware acceleration

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Play MPEG2 DVD files with hardware acceleration enabled

## Actual Behavior

If hardware acceleration is enabled, no video, black screen with non-stop loading annimation, but sound works

### To Reproduce

1. Open MPEG file from DVD 
2. Only the sound is read, the screen remains black

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/ozemazesoh.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Obligation to deactivate each time the hardware acceleration to read my DVDs since version 19.1 whereas under version 19.0 it was useless. MediaInfo : https://paste.kodi.tv/ogurotofum

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 9 (Pie)
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Can you test if issue still exist in v21 beta2?

https://mirrors.kodi.tv/releases/
