### ISSUE TITLE
Issue with building - from wayland-protocols Makefile

### ISSUE THREAD

**Issue by prapkengr** [xbmc/xbmc#19788]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hi there,
Due to new added line 39 in the [wayland-protocols Makefile url](https://github.com/xbmc/xbmc/blob/master/tools/depends/target/wayland-protocols/Makefile) 
`cd $(PLATFORM); $(AUTORECONF) -vif`
the command
`sudo make -C tools/depends/target/wayland-protocols PREFIX=/usr/local`
on Raspberry - Raspbian OS, ends in error ...
`pi@raspi:~/kodi $ sudo make -C tools/depends/target/wayland-protocols PREFIX=/usr/local make: Entering directory '/home/pi/kodi/tools/depends/target/wayland-protocols' cd /home/pi/kodi/tools/depends/target/wayland-protocols; curl -Ls --create-dirs -f -O http://mirrors.kodi.tv/build-deps/sources/wayland-protocols-1.20.tar.gz rm -rf native/*; mkdir -p native cd native; tar --strip-components=1 -xf /home/pi/kodi/tools/depends/target/wayland-protocols/wayland-protocols-1.20.tar.gz cd native; -vif /bin/sh: 1: -vif: not found make: *** [Makefile:39: native] Error 127 make: Leaving directory '/home/pi/kodi/tools/depends/target/wayland-protocols'`

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expectation is that the CONFIGURE & MAKE goes through without any errors.

## Actual Behavior

_$ sudo make -C tools/depends/target/wayland-protocols PREFIX=/usr/local make: Entering directory '/home/pi/kodi/tools/depends/target/wayland-protocols' cd /home/pi/kodi/tools/depends/target/wayland-protocols; curl -Ls --create-dirs -f -O http://mirrors.kodi.tv/build-deps/sources/wayland-protocols-1.20.tar.gz rm -rf native/*; mkdir -p native cd native; tar --strip-components=1 -xf /home/pi/kodi/tools/depends/target/wayland-protocols/wayland-protocols-1.20.tar.gz cd native; -vif /bin/sh: 1: -vif: not found make: *** [Makefile:39: native] Error 127 make: Leaving directory '/home/pi/kodi/tools/depends/target/wayland-protocols'`_

## Possible Fix

Not sure, but in the [wayland-protocols Makefile](https://github.com/xbmc/xbmc/blob/master/tools/depends/target/wayland-protocols/Makefile)  why the line 
`cd $(PLATFORM); $(AUTORECONF) -vif`
got translated to 
`cd native; -vif `
Is it that  
`$(AUTORECONF) `
is not defined here?
I could not find anything for this macro.
Unfortunately [wayland-protocols git source](https://github.com/wayland-project/wayland-protocols) also does not mention any specific steps of CONFIGURE / MAKE.
So going by usual / standard way of CONFIGURE & MAKE .. this might be fixed.
But, first of all need to know what  AUTORECONF  macro should be.

### To Reproduce

1.  Do the steps as per   [Install_Kodi_for_Linux](https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux) followed by [Debian/Ubuntu build guide](https://github.com/xbmc/xbmc/blob/master/docs/README.Ubuntu.md#debianubuntu-build-guide)  
2. Then as per the page [Linux build guide](https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md)  until  [configure-build](https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md#41-configure-build)
3. Once you reach the step of doing command  `sudo make -C tools/depends/target/wayland-protocols PREFIX=/usr/local`  ,  this mentioned error is produced. 

### Debuglog

The debuglog can be found here:
Nothing specific there. But only relevant is, 

```
pi@raspi:~/kodi $ sudo make -C tools/depends/target/wayland-protocols PREFIX=/usr/local
make: Entering directory '/home/pi/kodi/tools/depends/target/wayland-protocols'
cd /home/pi/kodi/tools/depends/target/wayland-protocols; curl -Ls --create-dirs -f -O  http://mirrors.kodi.tv/build-deps/sources/wayland-protocols-1.20.tar.gz
rm -rf native/*; mkdir -p native
cd native; tar --strip-components=1 -xf  /home/pi/kodi/tools/depends/target/wayland-protocols/wayland-protocols-1.20.tar.gz
cd native;  -vif
/bin/sh: 1: -vif: not found
make: *** [Makefile:39: native] Error 127
make: Leaving directory '/home/pi/kodi/tools/depends/target/wayland-protocols'

root@raspi:/home/pi/kodi/tools/depends/target/wayland-protocols# ll
total 100
-rwxr-xr-x 1 root root  1487 May 23 13:02 Makefile
drwxr-xr-x 6 root root  4096 May 23 13:09 native
-rw-r--r-- 1 root root 93167 May 23 13:09 wayland-protocols-1.20.tar.gz
root@raspi:/home/pi/kodi/tools/depends/target/wayland-protocols#
root@raspi:/home/pi/kodi/tools/depends/target/wayland-protocols# ll native/
total 60
-rwxrwxr-x  1 root root  199 Feb 29  2020 autogen.sh
-rwxr-xr-x  1 root root 1376 Feb 29  2020 configure.ac
-rw-rw-r--  1 root root 1502 Feb 29  2020 COPYING
-rw-rw-r--  1 root root 7371 Feb 29  2020 GOVERNANCE.md
drwxrwxr-x  2 root root 4096 Feb 29  2020 m4
-rwxr-xr-x  1 root root 2179 Feb 29  2020 Makefile.am
-rw-rw-r--  1 root root  619 Feb 29  2020 MEMBERS.md
-rw-rw-r--  1 root root 6548 Feb 29  2020 README.md
drwxrwxr-x  5 root root 4096 Feb 29  2020 stable
drwxrwxr-x  2 root root 4096 Feb 29  2020 tests
drwxrwxr-x 20 root root 4096 Feb 29  2020 unstable
-rwxr-xr-x  1 root root  187 Feb 29  2020 wayland-protocols.pc.in
-rwxr-xr-x  1 root root  142 Feb 29  2020 wayland-protocols-uninstalled.pc.in
root@raspi:/home/pi/kodi/tools/depends/target/wayland-protocols#

```

### Screenshots 
Here are some links or screenshots to help explain the problem:

System / environment info as below. 
Most probably, this could be reproduced in the Raspbian image VM [Raspberry Pi OS](https://www.raspberrypi.org/software/operating-systems/)    [Raspbian](https://www.raspbian.org/)   [run-raspberry-in-virtual-machine](https://raspberrytips.com/run-raspberry-in-virtual-machine/) 

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

**System / environment info**

_PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        29G   11G   17G  40% /
devtmpfs        1.8G     0  1.8G   0% /dev
tmpfs           1.9G   29M  1.9G   2% /dev/shm
tmpfs           1.9G  8.7M  1.9G   1% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   48M  205M  19% /boot
tmpfs           378M  8.0K  378M   1% /run/user/1000

$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 270.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 270.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 270.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 270.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2711
Revision        : c03111
Model           : Raspberry Pi 4 Model B Rev 1.1

$ cat /proc/version
Linux version 5.10.17-v7l+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1414 SMP Fri Apr 30 13:20:47 BST 2021

$ cat /proc/meminfo
MemTotal:        3866504 kB
MemFree:          698816 kB
MemAvailable:    2337084 kB
Buffers:           39088 kB
Cached:          1765060 kB
SwapCached:         2164 kB
Active:           886344 kB
Inactive:        2014172 kB
Active(anon):       2496 kB
Inactive(anon):  1206256 kB
Active(file):     883848 kB
Inactive(file):   807916 kB
Unevictable:       71028 kB
Mlocked:              16 kB
HighTotal:       3211264 kB
HighFree:         286772 kB
LowTotal:         655240 kB
LowFree:          412044 kB
SwapTotal:        102396 kB
SwapFree:          95484 kB
Dirty:             12780 kB
Writeback:             0 kB
AnonPages:       1165360 kB
Mapped:           318456 kB
Shmem:            112384 kB
KReclaimable:     106664 kB
Slab:             132292 kB
SReclaimable:     106664 kB
SUnreclaim:        25628 kB
KernelStack:        2824 kB
PageTables:        13964 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     2035648 kB
Committed_AS:    3148324 kB
VmallocTotal:     245760 kB
VmallocUsed:        5468 kB
VmallocChunk:          0 kB
Percpu:              512 kB
CmaTotal:         262144 kB
CmaFree:          206316 kB_

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi v19.1 (Matrix)   (Manual build from [xbmc git sources](https://github.com/xbmc/xbmc)  )

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Meh, it's likely `$(AUTORECONF)` isn't defined when building this way.

Just install wayland-protocols from your package manager.
