### ISSUE TITLE
Metadata of recordings

### ISSUE THREAD

**Issue by FredFirestone** [xbmc/xbmc#19807]
### Describe the bug
I'm using kodi (libreelec) on a raspberry and want to move recordings. I've made it to the Kodi wiki but couldn't succeed in exporting metadata. I did not find any disclaimer that metadata export wouldn't work for recordings.

Only later did I find https://forum.kodi.tv/showthread.php?tid=157527.

With the architectural background given in above link I'd like to suggest Kodi to offer a export interface of the metadata different (recording) backends provide.

Current implementation makes it somewhat hard to export metadata "easily" shown in Kodi's UI. Kodi's export facility is not applicable and makes it unnecessary hard to access this metadata.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Metadata should be exported even from recordings.

## Actual Behavior

When exporting metadata it will (silently) ignore recordings as these seem not to be part of Kodi's original data(base). Still Kodi knows and shows metadata for recordings, so for users it may be unexpected.

## Possible Fix

It would be great if Kodi's export facility could be extended to query backend providers for metadata, particularly recording providers like tvheadend. This metadata should be exported in nfo files and would allow easy reimport into Kodi's library.

### To Reproduce

1. record with tvheadend
2. afterwards metadata is shown at the recordings
3. export video data (e.g. single file) - nothing for recordings show up

### Debuglog

The debuglog can be found here:
n/a

### Screenshots 
Here are some links or screenshots to help explain the problem:

n/a

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

It's really more a feature request - or at most a bug report for documentation - but I couldn't find a better way to propose a feature request. Feel free to close the issue if it is not proper.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP
- [x] Other
 - Operating system version/name:
 - Kodi version:
18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
As you found the thread, you might have also read, that this is a feature request. Feature requests aern't bug reports and, therefore, have to be submitted to our forums: 

https://forum.kodi.tv/forumdisplay.php?fid=9
