### ISSUE TITLE
[Python] - lzma missing

### ISSUE THREAD

**Issue by matthuisman** [xbmc/xbmc#19817]
Test Add-on: [lzma.test.zip](https://github.com/xbmc/xbmc/files/6739002/lzma.test.zip)

### Describe the bug
Here is a clear and concise description of what the problem is:

Python3 on Kodi 19 Android fails to load lzma module.
lzma is part of the standard lib since Python 3.3 so should be included
https://docs.python.org/3/library/lzma.html

lzma on Windows loads fine

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

lzma module loads

## Actual Behavior

```
Starting Kodi (19.1 (19.1.0) Git:20210508-85e05228b4). Platform: Android ARM 64-bit
File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/lzma.py", line 27, in <module>
from _lzma import *
ModuleNotFoundError: No module named '_lzma'
```

## Possible Fix

add `lzma` here: https://github.com/fuzzard/xbmc/blob/master/tools/depends/target/Makefile#L95
add `_lzma _lzmamodule.c -I$(prefix)/include -L$(prefix)/lib -llzma` here: https://github.com/fuzzard/xbmc/blob/master/tools/depends/target/python3/modules.setup#L377

Similar solved issue:
bz2 missing https://github.com/xbmc/xbmc/issues/18152
fixed with pr: https://github.com/xbmc/xbmc/pull/18220

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi 19.1 Android ARM 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
We would need to build xz for the target depends (see: https://tukaani.org/xz/xz-5.2.5.tar.gz) in order to have liblzma. This is likely the reason we don't build with it.

**Comment by matthuisman** [comment]
isn't that what this is?
https://github.com/xbmc/xbmc/blob/master/tools/depends/native/xz/Makefile
It also works on Windows. - just not Android?

**Comment by fuzzard** [comment]
No, native is for the build host, target is for the actual app platform.

Also, windows build system is completely independent and separate from all other platforms, hence differences in end product

**Comment by matthuisman** [comment]
oh right - thank you :)
