### ISSUE TITLE
opera-ffmpeg-codecs 90.0.4430.93-1 breaks Kodi in Arch Linux

### ISSUE THREAD

**Issue by cgcgcgcgcg** [xbmc/xbmc#19815]
### Describe the bug
Here is a clear and concise description of what the problem is:

I hadn't installed Opera browser in a long time and installed it along with opera-ffmpeg-codecs 90.0.4430.93-1 from Arch linux repo.
After a while, I closed the browser and Kodi was crashing on every attempt to run it. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should run.

## Actual Behavior

Kodi crashed.

## Possible Fix

Uninstall opera-ffmpeg-codecs.
After uninstalling, Kodi works fine.

### To Reproduce

1. Install opera and opera-ffmpeg-codecs from Arch Linux repos.
2. Close the browser.
3. Try opening Kodi.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi v19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by wsnipex** [comment]
this sounds very much like a packaging problem.

**Comment by lrusak** [comment]
Please ask your package managers to ship kodi with ffmpeg statically compiled in (if they want to ship multiple ffmpeg versions).
