### ISSUE TITLE
Video completely nonfunctional on Kodi with 11th Gen Intel CPU integrated graphics.

### ISSUE THREAD

**Issue by garvv** [xbmc/xbmc#19820]
### Describe the bug
Here is a clear and concise description of what the problem is:
Videos do not play with VAAPI enabled on Kodi does not work with Intel 11th Gen Rocket Lake CPU integrated graphics (12th gen Xe I believe).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

On other systems with VAAPI enabled, videos play as normal using hardware decode. On my Vega 8 integrated graphics on laptop, this works with VP8/9 and H264. I would expect the same with Rocket Lake iGPUs. 

## Actual Behavior

With VAAPI enabled, videos do not play. There may be a flash of green at the start, but there will be no audio and no video - just a black screen. It does appear that the video is attempting to be played - you are able to scrub, but still no video or audio is outputted. This doesn't work for any codec or any video and basically makes Kodi unusable

## Possible Fix

Usage of FFMPEG 4.4 instead of 4.3 may work. 

### To Reproduce

1. Reproducable on any Kodi version - 19.1-1 or below. 
2. Enable VAAPI with a rocket lake CPU and Xe integrated graphics
3. Play any video.

### Debuglog

The debuglog can be found here:
I'm not home due to severe weather, but this is the debug log for someone else who had the issue. I will update with mine within the week. 
https://paste.kodi.tv/eridubigaz.kodi

### Screenshots
Here are some links or screenshots to help explain the problem:

Will add soon.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Linux

 - Operating system version/name: Ubuntu 21.04, Kernel 5.12.7
 - Kodi version: 19.1-1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by a1rwulf** [comment]
11th gen Intel hw is brand new and Ubuntu 21.04 most likely doesn't ship all the latest versions of the gfx stack.
I've compiled mesa, libva, media-driver and ffmpeg and kodi master from source and it works fine, Kernel 5.12.x necessary, but seems that's already the case on your system.
When we released Kodi 19(.x), 11th gen hw wasn't there yet.

**Comment by starvald** [comment]
Hi, any chance this could be reopened.
black screen on playback if vaapi decoding is enabled. 
turning off 'prefer vaapi render method' does allow some videos to play. 

kodi.log, built from git, ffmpeg 4.4
https://paste.kodi.tv/enetihogip.kodi

dmesg 
https://paste.kodi.tv/ayecelucay

inxi
https://paste.kodi.tv/hupazusaxi

vainfo
https://paste.kodi.tv/uxiluciqih

ffmpeg 4.3.2 vaapi test 
https://paste.kodi.tv/olafaraped

ffmpeg 4.4 vaapi test
https://paste.kodi.tv/yohafumeze


kodi forum thread:
https://forum.kodi.tv/showthread.php?tid=362073

**Comment by a1rwulf** [comment]
As said above:
There is no official version supporting that configuration yet, so plz stick to the forum.
We're not going to reopen this issue for now.

**Comment by bkuhls** [comment]
> Please use the forums for support. Thanks!

For reference: https://forum.kodi.tv/showthread.php?tid=362073

**Comment by bkuhls** [comment]
Please test current intel media-driver, maybe the problem was fixed upstream: https://github.com/intel/media-driver/issues/1210#issuecomment-877708413
