### ISSUE TITLE
removal of fmt::sprintf usage messes up the kodi interface partly

### ISSUE THREAD

**Issue by Durlyn** [xbmc/xbmc#19823]
## Bug report
**Describe the bug**
After commit b0e5627a1566e26444995233e634969a993abf81 in the interface of the Kodi, in some places the format of the line appears, instead of text. Specifically in the System Information menu.

### To Reproduce

1. Build Kodi from git after brahch b0e5627a15.
2. Go to menu: Settings-System information.
3.

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/874902/120066739-81be2080-c080-11eb-987c-977a8ae83294.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora 34
 - Kodi version: 20.0-ALPHA1 (19.90.101)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Can this be related to untranslated entities ?

**Comment by howie-f** [comment]
@enen92 happens with english/german too

**Comment by howie-f** [comment]
root is removal of fmt::sprintf usage. reverting https://github.com/xbmc/xbmc/commit/6d3144834fde0037f803729076e24f9292764fcc brings it back
cc @lrusak
