### ISSUE TITLE
Windows v20: Smart Playlist Rules Broken In c3cc394f69

### ISSUE THREAD

**Issue by Synapto** [xbmc/xbmc#19828]
## Bug report
I suspect that this may be due to recent (mid May) changes to, or deprecation of, numerous InfoTag functions.

Kodi 20.0-ALPHA1 (19.90.101) Git:20210528-c3cc394f69 refuses to load Smart Playlists (.xsp) which contain a variety of rule fields.

Kodi 20.0-ALPHA1 (19.90.101) Git:20210514-3bffdaf848 loads these Smart Playlists correctly as expected.
 

### Describe the bug
The latest c3cc394f695edb01cff0b693fbec33a4820d21e1 build does nothing (literally) when selecting the affected Smart Playlist from the playlist explorer.  It also fails to display those Smart Playlists when they form GUI element in something like a Home Menu.

The 3bffdaf848559a7a53e0f6fef956891a0ac8e496 build from two weeks ago functions correctly.

Here's two samples of the type of  .xsp which fail.  There are _HEAPS_ more:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="movies">
    <name>Turkeys</name>
    <match>all</match>
    <rule field="rating" operator="lessthan">
        <value>3.0</value>
    </rule>
    <rule field="votes" operator="greaterthan">
        <value>1500</value>
    </rule>
    <limit>250</limit>
    <order direction="descending">rating</order>
</smartplaylist>


<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="movies">
    <name>Movie_I-O</name>
    <match>one</match>
    <rule field="path" operator="startswith">
        <value>T:\I\</value>
    </rule>
    <rule field="path" operator="startswith">
        <value>T:\J\</value>
    </rule>
    <rule field="path" operator="startswith">
        <value>T:\K\</value>
    </rule>
    <rule field="path" operator="startswith">
        <value>U:\L\</value>
    </rule>
    <rule field="path" operator="startswith">
        <value>U:\M\</value>
    </rule>
    <rule field="path" operator="startswith">
        <value>U:\N\</value>
    </rule>
    <rule field="path" operator="startswith">
        <value>U:\O\</value>
    </rule>
    <order direction="ascending">path</order>
</smartplaylist>
```

However, when commenting out the rules sections, **they now load**, albeit with completely incorrect content (obviously, having no rules):

```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="movies">
    <name>Turkeys</name>
    <match>all</match>
<!--
    <rule field="rating" operator="lessthan">
        <value>3.0</value>
    </rule>
    <rule field="votes" operator="greaterthan">
        <value>1500</value>
    </rule>
-->
    <limit>250</limit>
    <order direction="descending">rating</order>
</smartplaylist>


<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="movies">
    <name>Movie_I-O</name>
    <match>one</match>
<!--
    <rule field="path" operator="startswith">
        <value>T:\I\</value>
    </rule>
    <rule field="path" operator="startswith">
        <value>T:\J\</value>
    </rule>
    <rule field="path" operator="startswith">
        <value>T:\K\</value>
    </rule>
    <rule field="path" operator="startswith">
        <value>U:\L\</value>
    </rule>
    <rule field="path" operator="startswith">
        <value>U:\M\</value>
    </rule>
    <rule field="path" operator="startswith">
        <value>U:\N\</value>
    </rule>
    <rule field="path" operator="startswith">
        <value>U:\O\</value>
    </rule>
-->
    <order direction="ascending">path</order>
</smartplaylist>
```

This is the event from KODI.LOG when I tried to pick the "Turkeys" .xsp from a list.

```
2021-05-30 09:55:01.285 T:2340    ERROR <general>: SQL: [MyVideos119.db] SQLite error SQLITE_ERROR (near "%": syntax error)
                                                   Query: select * from movie_view  WHERE ((%s < 3.0)) AND ((%s > 1500))
2021-05-30 09:55:01.285 T:2340    ERROR <general>: CVideoDatabase::GetMoviesByWhere failed
2021-05-30 09:55:01.285 T:2340    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting special://profile/playlists/video/Turkeys.xsp
2021-05-30 09:55:01.287 T:2340    ERROR <general>: SQL: [MyVideos119.db] SQLite error SQLITE_ERROR (near "%": syntax error)
                                                   Query: select * from movie_view  WHERE ((%s < 3.0)) AND ((%s > 1500))
2021-05-30 09:55:01.287 T:2340    ERROR <general>: CVideoDatabase::GetMoviesByWhere failed
2021-05-30 09:55:01.288 T:2340    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting special://profile/playlists/video/Turkeys.xsp
2021-05-30 09:55:01.291 T:2340    ERROR <general>: SQL: [MyVideos119.db] SQLite error SQLITE_ERROR (near "%": syntax error)
                                                   Query: select * from movie_view  WHERE ((%s < 3.0)) AND ((%s > 1500))
2021-05-30 09:55:01.291 T:2340    ERROR <general>: CVideoDatabase::GetMoviesByWhere failed
2021-05-30 09:55:01.291 T:2340    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting special://profile/playlists/video/Turkeys.xsp
2021-05-30 09:55:01.293 T:2340    ERROR <general>: SQL: [MyVideos119.db] SQLite error SQLITE_ERROR (near "%": syntax error)
                                                   Query: select * from movie_view  WHERE ((%s < 3.0)) AND ((%s > 1500))
2021-05-30 09:55:01.293 T:2340    ERROR <general>: CVideoDatabase::GetMoviesByWhere failed
2021-05-30 09:55:01.294 T:2340    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting special://profile/playlists/video/Turkeys.xsp
```

From that snippet, it looks a **lot** like it's related to https://github.com/xbmc/xbmc/issues/19823

## Expected Behavior
When selecting a rules-based Smart Playlist, either manually from a list or when they are automatically used as a menu item, you should expect to see those articles from your library that match the Smart Playlist's rules.

## Actual Behavior
Instead, nothing happens when you manually select a Smart Playlist from a list, or no GUI elements are visible when the Smart Playlist is used as a menu.

## Possible Fix
Dunno.  Probably related to the "%s" sprintf issue from https://github.com/xbmc/xbmc/issues/19823, so start there?

### To Reproduce
Use one of the .xps shown above with c3cc394f695edb01cff0b693fbec33a4820d21e1, and see what happens.

BTW, I tried editing these playlists from within Kodi's context menu.  It didn't make any difference, since the same rule tags were saved (I thought they may have been changed to things like "imdb.rating" ans so forth).

### Debuglog
This log is polluted with those "%s" errors, showing the full extent of the problem.

https://paste.kodi.tv/galesaxeba.kodi

### Your Environment
Used Operating system:
Edition	Windows 10 Pro
Version	21H1
OS build	19043.1023
Experience	Windows Feature Experience Pack 120.2212.2020.0
Processor	Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
Installed RAM	32.0 GB (30.9 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Kodi (20.0-ALPHA1 (19.90.101) Git:20210528-c3cc394f69). Platform: Windows NT x86 64-bit
Using Release Kodi x64
Kodi compiled 2021-05-29 by MSVC 191627034 for Windows NT x86 64-bit version 10.0 (0x0A000007)
Running on Windows 10 21H1, kernel: Windows NT x86 64-bit version 10.0.19043.1023
FFmpeg version/source: 4.4-Kodi
Host CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz, 8 cores available
System has 32.0 GB of RAM installed
Desktop Resolution: 1920x1080 32Bit at 60Hz

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
similar fallout as https://github.com/xbmc/xbmc/pull/19796#issuecomment-850913442

**Comment by ronie** [comment]
@Synapto could you please retest with current master?
this issue might have been fixed by https://github.com/xbmc/xbmc/pull/19834

**Comment by Synapto** [comment]
Using Kodi 20.0-ALPHA1 (19.90.101) Git:20210601-482c86f8cc, the Smart Playlist rules issue does indeed appear to be fixed.

I tried a number of playlist and menu combos, and all worked as expected.  Good job.

There's still something hokey about menus made from metadata (e.g. the following menu item fails to display), but I don't think it's string related. 

I'll raise another issue about it if I can ever figure out how to reproduce without having to edit your skin's Home.xml:

```
<include content="WidgetListCategories" condition="Library.HasContent(tvshows)">
	<param name="content_path" value="videodb://tvshows/studios/"/>
	<param name="sortby" value="random"/>
	<param name="sortorder" value="descending"/>
	<param name="widget_header" value="RESPONSIBLE"/>
	<param name="widget_target" value="videos"/>
	<param name="list_id" value="6500"/>
	<param name="icon" value="$VAR[WidgetStudioIconVar]"/>
	<param name="icon_height" value="120"/>
</include>

```
