### ISSUE TITLE
Click on seekbar is broken in master builds

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/xbmc#19836]
### Describe the bug
Here is a clear and concise description of what the problem is:

Clicking on any place of seekbar resets movie to the start.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Movie jumps to the clicked position.

## Actual Behavior

Movie jumps to the beginning.

### To Reproduce

1. Start any movie
2. Use mouse to click at any place on the seekbar.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/6569731/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS Catalina 10.15.7
 - Kodi version: master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Same on Windows

**Comment by ronie** [comment]
reverting https://github.com/xbmc/xbmc/pull/19796 fixes the issue.

@lrusak another one for the fallout list.

**Comment by lrusak** [comment]
please try with #19834

**Comment by ronie** [comment]
@lrusak yup, that fixes it

**Comment by ronie** [comment]
fixed by https://github.com/xbmc/xbmc/pull/19834
