### ISSUE TITLE
Debug overlay crashes Kodi in master build

### ISSUE THREAD

**Issue by asavah** [xbmc/xbmc#19839]
### Describe the bug
Here is a clear and concise description of what the problem is:
Kodi crashes if I try to bring up the debug overlay (ctrl + shift +o) while playing a video .

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
No crash, debug overlay is present.

## Actual Behavior
Kodi crashes with SIGABRT, see gdb backtrace below.

## Possible Fix
No idea yet.

### To Reproduce
1.  Play a video
2. Try bringing up debug overlay
3. Experience the crash

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/osibimucek.kodi Note this is NOT a debuglog, just a normal log, will provide a full debug log later.
Do note that the linked build does contain  #19384 as patch , the binary was built few hours before #19384 was actually merged.

coredumpctl gdb backtrace https://paste.kodi.tv/lexeqacefi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
Possibly fallout from #19796 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: own project, linux 5.12.x, xorg/GL/vaapi
 - Kodi version: master e2b2967c4e + PR19384 as patch

cc @lrusak 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please try again with the latest master

**Comment by Durlyn** [comment]
in the last master now iptv.simple crashes.

**Comment by lrusak** [comment]
> in the latest master now pvr.iptvsimple crashes.

irrelevant to this issue.

**Comment by asavah** [comment]
@lrusak Sorry for the delay.

Some additional info: for me the crash happens only if inputstream.adaptive is involved.
If I play a video from the nfs source and bring up debug overlay - OK.
If I play a video via youtube addon and bring up debug overlay - crash.
Youtube addon is set to prefer vp9/webm.
Just to be sure I've rebuilt inputstream.adaptive after building Kodi.

Debuglog: https://paste.kodi.tv/oxuhogijaz.kodi
GDB backtrace: https://paste.kodi.tv/bihakeqizu

If needed I can rebuild Kodi with debug symbols.

**Comment by asavah** [comment]
Full backtrace with debuf info https://paste.kodi.tv/oduqududer.kodi

Interesting things that I see with my inexperienced eye:
fmt error is `missing precision specifier` which happens when StringUtils::SizeToString is called with size=0
so my uneducated guess would be that error is here https://github.com/xbmc/xbmc/blob/master/xbmc/utils/StringUtils.cpp#L1534

**Comment by lrusak** [comment]
@asavah can you see if this fixes it? https://github.com/lrusak/xbmc/commit/e5b9810bc2e24a6ced88467368af3b8d61b405e6

**Comment by asavah** [comment]
@lrusak Yes it does, tested with normal files, inputstream.adaptive (youtube), inputstream.ffmpegdirect debug overlay is ok with your patch.
Thank you!
