### ISSUE TITLE
RestartApp does'nt work in DialogButtonMenu.xml

### ISSUE THREAD

**Issue by b-jesch** [xbmc/xbmc#19837]
## Bug report
Buitlin function 'RestartApp' does'nt work in Power Menu (e.g. DialogButtonMenu)
### Describe the bug
I want extend the Power Menu with the option "restart Kodi" using the builtin function "RestartApp". I know that this builtin is limited to Linux and Windows environments. In Kodi 18.9 this works (LibreElec, Linux based) but does'nt in Ubuntu (20.04) and Kodi 19.1

Here is a clear and concise description of what the problem is:
The command RestartApp() - with or without brackets - simply does'nt react on <onclick> commands within GUI windows, e.g.
`<onclick>RestartApp</onclick>`

### To Reproduce

1. Open the DialogButtonMenu.xml that resides in the xml folder of the skin.estuary (or other skins)
2. Simply replace any onclick content (e.g. `<onclick>Reboot()</onclick>` with `<onclick>RestartApp()</onclick>`). The 'Reboot' item in the shutdown menu should now became the 'ReloadApp' behaviour after restart (or reloading skin).
3. This works well in Kodi 18, but not in Kodi 19.

A 'kodi-send --action RestartApp' from a shell works as expected even in K19.

I don't know if this bug appears in Windows OS as I'm not using Windows!

### Debuglog
There are no additional Infos in the Log. Only the keypress (or mouseclick) is registered when clicking the modified entry.

2021-05-31 22:35:06.153 T:4894    DEBUG <general>: Activating window ID: 10111
2021-05-31 22:35:06.153 T:4894    DEBUG <general>: ------ Window Init (DialogButtonMenu.xml) ------
2021-05-31 22:35:06.716 T:4946    DEBUG <general>: [service.sleepy.watchdog] user activity detected, reset idle time
2021-05-31 22:35:07.620 T:4894    DEBUG <general>: Keyboard: scancode: 0x74, sym: 0x274, unicode: 0x0000, modifier: 0x0
2021-05-31 22:35:07.620 T:4894    DEBUG <general>: HandleKey: down (0xf081) pressed, action is Down
2021-05-31 22:35:07.655 T:4894    DEBUG <general>: Keyboard: scancode: 0x74, sym: 0x274, unicode: 0x0000, modifier: 0x0
2021-05-31 22:35:08.051 T:4894    DEBUG <general>: Keyboard: scancode: 0x6f, sym: 0x273, unicode: 0x0000, modifier: 0x0
2021-05-31 22:35:08.051 T:4894    DEBUG <general>: HandleKey: up (0xf080) pressed, action is Up
2021-05-31 22:35:08.191 T:4894    DEBUG <general>: Keyboard: scancode: 0x6f, sym: 0x273, unicode: 0x0000, modifier: 0x0
2021-05-31 22:35:09.051 T:4894    DEBUG <general>: Keyboard: scancode: 0x24, sym: 0x13, unicode: 0x000d, modifier: 0x0
2021-05-31 22:35:09.175 T:4894    DEBUG <general>: Keyboard: scancode: 0x24, sym: 0x13, unicode: 0x0000, modifier: 0x0
2021-05-31 22:35:09.176 T:4894    DEBUG <general>: HandleKey: return (0xf00d) pressed, action is Select

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:

$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

 - Kodi version:

$ kodi -v
19.1 (19.1.0) Git:20210509-85e05228b4 Media Center Kodi
Copyright (C) 2005-2021 Team Kodi - http://kodi.tv

**Comment by DaVukovic** [comment]
Hi @b-jesch 

Might I ask, why you are in need of that? I'm asking for personal reasons because I have audio problems with my AVR where my AVR stays at DolbyDigital or DTS or whatever after playing a movie and therefore the GUI doesn't have sound anymore. I only have this problem with LibreELEC. 

My workaround was to use a script:

```
<item>
  <label>Kodi Service Restart</label>
  <onclick>System.Exec(/storage/.kodi/userdata/restart_kodi.sh)</onclick>
  <visible>true</visible>
</item>
```
and then the script simply does:
```
#!/usr/bin/bash
systemctl restart kodi.service
```
Maybe "restartapp" doesn't work because Kodi is a 'service' in libreelec. For most Linux-Systems Kodi is a normal app and not a service. 

I'll have a look later myself how LE behaves while using "restartapp()".

**Comment by b-jesch** [comment]
When my soundbar is switched off and on after an amount of time when sound is missing, in some very rare cases the sound from Kodi is noisy and crackled. Maybe a problem with the hdmi handshake. In this case a Kodi restart solves this issue. The second reason is for development purposes.

`systemctl restart kodi` works in Linux and in LibreElec too - and RestartApp even in K18, but not in K19. As RestartApp is a part of system builtin commands, this should work again.

https://codedocs.xyz/AlwinEsch/kodi/page__list_of_built_in_functions.html#built_in_functions_15

**Comment by DaVukovic** [comment]
Could you please try with a current Kodi master build? As I cannot confirm your problem. 

Here's my `DialogButtonMenu.xml` which I use with Kodi 20 and "RestartApp()" works as expected. 

https://paste.centos.org/view/d9b3361a

>systemctl restart kodi works in Linux and in LibreElec too

the systemctl command will only work if Kodi is implemented as a service (a `kodi.service` file exists in `/etc/systemd/system` for example). Which is not the case if you follow the installation guide we provide at our Wiki. So saying that `systemctl restart kodi` will always work is not correct. Just to mention it.

**Comment by DaVukovic** [comment]
I just tried on LibreELEC (Kodi 19.0) and it works as well.

Maybe you put the function on the wrong section or you have a typo?! Please share your full file which shows the changes you have done. And also the full debuglog. 

Thanks

**Comment by b-jesch** [comment]
OMG. I typed `<onClick>` instead of `<onclick>`. Now this works indeed. Next mistake was to copy the complete line and pasted them into the Estuary xml so the error has moved along. Sorry for the noise. I'll close this.
