### ISSUE TITLE
"one or more items failed to play. Check the log" ... --> OK --> one level up, disturbs my channel flicking; breaking the UI flow

### ISSUE THREAD

**Issue by drandreaskrueger** [xbmc/xbmc#19842]
---
name: Problem report
about: Create an extensive report to help us document a problem

---

### Describe the bug
See https://github.com/kodi-pvr/pvr.iptvsimple/issues/519 issue

I was told there that 

> The error dialog is ... from kodi pvr. So fixing this somehow would need to be fixed in core. 

so please consider to make this UX improvement. It is well explained over there in the other issue.

Thanks a lot, great software, keep up the good work!

## Expected Behavior
Just leave out the "OK", instead show a notification which disappears again after 5 seconds.

And most importantly, stay in the streaming window mode, i.e. do not flick back to the navigation hierarchy one whole level up. That is the main problem here: I don't want to end up in a completely different place in my UI experience, just because 1 out of 700 channels is bad, temporarily.

## Actual Behavior
**right now: switching up or down - if a channel fails, then I get an OK dialogue --> ggrrrr**  
that means: my flicking through channels is interrupted, I have to select a working channel, then continue flicking through, taking much care to not fall into the same trap again, etc. Not a good flow.

## Possible Fix
**future/wish: show the same error message for 3 seconds, but then simply: nothing.**  
No OK dialogue, no confirmation clicking needed, no change of navigation level, no navigating back to where I was ...
No annoyance.

### To Reproduce
1. channel list .m3u with many good and one bad channel
2. pvr.iptvsimple
3. flick through the channels until you hit the bad one

### Debuglog
The debug log is not needed as it is a UX issue.

### Screenshots
you now your OK dialogue box, right?

> "one or more items failed to play. Check the log"

## Additional context or screenshots (if appropriate)
I have even [added a manual blacklisting option](https://github.com/drandreaskrueger/iptv-stream-cleaner/commit/a03aeb276479d1c733e1b20b3429395adb79d92b) now. Helps for permanently failing URLs; but still not for those channels that are "only down for a short while".

### Your Environment
 - [ ] Windows 10
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by drandreaskrueger** [comment]
>  follow our template 

done that

**Comment by DaVukovic** [comment]
> future/wish: show the same error message for 3 seconds, but then simply: nothing.

"Wishes" for the "future" should be considered as feature requests. This section is for "bug reports". Feature requests should be submitted at the forums:

https://forum.kodi.tv/forumdisplay.php?fid=9
"Post all your suggestions/requests/ideas for Kodi core features and functions here."

So please head over to the forums and submit your request. If the "ok"-dialog pops up because there's an unplayable item, Kodi doesn't do anything wrong. As that's what that box is meant to do. So there's no bug at all. It would be a bug if the dialog pops up with that message while the video is playing. 

Thanks for understanding

**Comment by drandreaskrueger** [comment]
Yes but no. 

It is a UX issue.  
The OK dialog due to an unplayable item is massively inconvenient.  
And it is not only an OK box that needs to be clicked:  
The user gets kicked out of the sequence of programs, back to a totally different place in the GUI.     
_That_ really deteriorates the (otherwise brilliant) user experience.    

But you sound as if you feel 180 degrees different about that - so no use to submit it at your forums.  

Thanks for your time. Keep up the good work. Best regards.
