### ISSUE TITLE
Windows v20 (20210604-826e2eef-master-x64): Certain Classes Of VideoLibrary Metadata Lookups Fail Completely

### ISSUE THREAD

**Issue by Synapto** [xbmc/xbmc#19849]
### Describe the bug
Using 826e2eef7888ff5053ad91a01730bf79eab57186 from 05/06/21, attempting to refine VideoLibrary results using particular entire groups of metadata tagging produces nothing (literally).  The GUI doesn't even try to load any results or submenus when selecting metadata groups such as "Genres", "Studios", and "Country".

35f072f094954607f75d15b06bb823945b86e95c from 27/05/21 works correctly as expected.

## Expected Behavior
When selecting any video database metadata group (e.g. Genres), you should see some form of list/display of matching fields, either directly matched items (files) or a submenu requiring further refinement (e.g. "Genres" showing a submenu with "Action", "Drama" etc).

## Actual Behavior
Instead, the GUI acts as if there's no such thing as that metadata group if it's one of the failing types.  Either nothing happens when selecting that option , or Kodi performs some fallback behavior for unknown content (e.g. it'll show an unrelated top-level menu).  This changes depending on _how/where_ you selected the failing metadata group in the GUI.

It also completely fails to display Home Menu items that are derived in some way from one of the failing metadata groups (imagine the "Recent" line disappearing, except in my case it was "Studios".  See https://github.com/xbmc/xbmc/issues/19828#issuecomment-853679700). 

## Possible Fix
Your guess is better than mine.  Strings, eh?  Can't live with them, can't live without them.

### To Reproduce
This is a bit involved, but it will 100% reproduce the fault, ignoring any legacy/user configuration.

Components needed:
http://mirrors.kodi.tv/nightlies/windows/win64/master/KodiSetup-20210604-826e2eef-master-x64.exe
http://mirrors.kodi.tv/nightlies/windows/win64/master/KodiSetup-20210526-35f072f0-master-x64.exe
A directory with at least 10-20 scrape-able (i.e. properly named) movie files.

1. Use 7-Zip to extract the Kodi build into a unique directory.
2. Open a command window in that unique directory.
3. Run "Kodi -p" to create a "factory default" portable with no library.
4. Add that movie directory as a Media Source, using the all default options (i.e. "TMDB Python", etc), and let Kodi scan the new source.
5. From the Home menu, cursor down and press [ENTER] on the 'Videos" option.
6. Select the "Movies" item, and a list of metadata groups will appear (things like Recent, Genres, Titles, Years, etc)
7. Try to select each group in turn and see what happens.

On 3 different Intel+Windows machines, I was able to reproduce the following groups failing under 826e2eef7888ff5053ad91a01730bf79eab57186, but working under 35f072f094954607f75d15b06bb823945b86e95c:

Genres, Studios, Countries, Tags

Even with full debug logging, it didn't explain much.  Here's the "Country" lookup failing:
```
2021-06-05 09:28:45.290 T:5980    DEBUG <general>: Keyboard: scancode: 0x1c, sym: 0x0d, unicode: 0x0d, modifier: 0x0
2021-06-05 09:28:45.429 T:5980    DEBUG <general>: Keyboard: scancode: 0x1c, sym: 0x0d, unicode: 0x00, modifier: 0x0
2021-06-05 09:28:45.429 T:5980    DEBUG <general>: CInputManager::HandleKey: return (0xf00d) pressed, action is Select
2021-06-05 09:28:45.430 T:5980    DEBUG <general>: CGUIMediaWindow::GetDirectory (library://video/movies/country.xml/)
2021-06-05 09:28:45.430 T:5980    DEBUG <general>:   ParentPath = [library://video/movies/]
2021-06-05 09:28:45.430 T:4512    DEBUG <general>: Thread waiting start, auto delete: false
2021-06-05 09:28:45.432 T:4512    ERROR <general>: CVideoDatabase::GetNavCommon failed
2021-06-05 09:28:45.433 T:4512    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting library://video/movies/country.xml/
2021-06-05 09:28:45.433 T:4512    DEBUG <general>: Thread waiting 4512 terminating
2021-06-05 09:28:45.434 T:5980    ERROR <general>: CGUIMediaWindow::GetDirectory(library://video/movies/country.xml/) failed
2021-06-05 09:28:45.434 T:5980    DEBUG <general>: CGUIMediaWindow::GetDirectory (library://video/movies/)
2021-06-05 09:28:45.434 T:5980    DEBUG <general>:   ParentPath = []
2021-06-05 09:28:45.434 T:10912   DEBUG <general>: Thread waiting start, auto delete: false
2021-06-05 09:28:45.437 T:10912   DEBUG <general>: Thread waiting 10912 terminating
2021-06-05 09:28:45.440 T:10528   DEBUG <general>: Thread BackgroundLoader start, auto delete: false
2021-06-05 09:28:45.444 T:10528   DEBUG <general>: Thread BackgroundLoader 10528 terminating

```
Note that I didn't test TV Shows, but I bet it'll be the same.

### Debuglog
This is from a failing 482c86f8 build: https://paste.kodi.tv/gulijawose.kodi

EDIT: The log for the latest 826e2eef build provides the exact same (lack of) information when attempting to display the failing metadata group queries.

### Your Environment
Edition Windows 10 Pro
Version 21H1
OS build 19043.1023
Experience Windows Feature Experience Pack 120.2212.2020.0
Processor Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz 3.60 GHz
Installed RAM 32.0 GB (30.9 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch No pen or touch input is available for this display

Starting Kodi (20.0-ALPHA1 (19.90.101) Git:20210604-826e2eef78). Platform: Windows NT x86 64-bit
Using Release Kodi x64
Kodi compiled 2021-06-05 by MSVC 191627034 for Windows NT x86 64-bit version 10.0 (0x0A000007)
Running on Windows 10 21H1, kernel: Windows NT x86 64-bit version 10.0.19043.1023
FFmpeg version/source: 4.4-Kodi
Host CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz, 8 cores available
System has 32.0 GB of RAM installed
Desktop Resolution: 1920x1080 32Bit at 60Hz
Running with administrator rights
Aero is enabled
Display is not HDR capable or cannot be detected

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

EDIT: Updated to reflect failure with latest master build.

**Comment by fuzzard** [comment]
Can you try a newer master (ie from today 826e2eef7888ff5053ad91a01730bf79eab57186). Theres been a further 2 more fixes around the format issues. Just to rule out this specific instance hasnt already been resolved.

**Comment by Synapto** [comment]
Unfortunately, the problem persists with the latest 20.0-ALPHA1 (19.90.101) Git:20210604-826e2eef78 build.

I've updated the issue report to reflect this.

**Comment by fuzzard** [comment]
Thats fine, just wanted to confirm thanks.
