### ISSUE TITLE
Videoinfoscanner/Thumbloader ignoring NFO files with TVDB artwork URL's

### ISSUE THREAD

**Issue by KarellenX** [xbmc/xbmc#19845]
### Describe the bug
The issue was raised on the forum here... https://forum.kodi.tv/showthread.php?tid=362950
Also some brief discussions with @notspiff and @romanvm in # scrapers
@pkscout might also interest you

NFO files are being ignored in certain situations

Through some hit and miss testing I narrowed down the problem to the TVDB artwork links in **some cases**:

1. Using Local Info Only scraper, there is no problem
2. Using an XML based scraper, there is no problem
3. Using any one of the three Python scrapers, then nfo files are ignored and an online scrape occurs

The problem URL seems to be this format...
`<thumb>https://artworks.thetvdb.com/banners/series/379873/episodes/5e8e4b42bfd28.jpg</thumb>`

These URL's that use the following format cause **no** issues and nfo files are correctly scanned
`<thumb>http://thetvdb.com/banners/episodes/361753/7133857.jpg</thumb>`
`<thumb>https://artworks.thetvdb.com/banners/v4/episode/8380156/screencap/60af5276c2106.jpg</thumb>`

## Expected Behavior
NFO files should be scanned into the library without regard for the type of URL link used

## Actual Behavior
NFO files are ignored when **both** of the following conditions are met

1. A Python based scraper is in use
2. A certain type of TVDB artwork link is used.

## Possible Fix
unknown

### To Reproduce
1. Download and unzip the following file which contains one TV Show of two seasons which can reproduce the problem
[Ragnarok (2020).zip](https://github.com/xbmc/xbmc/files/6595157/Ragnarok.2020.zip)

2. Ensuring one of the Python scrapers is active on the Source, scan the TV Show into the library
3. Note that Season 1 has been scraped, but season 2 is correctly scanned from NFO files.

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/dihutovomu.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by BergerBlancSuisse** [comment]
i have not been able to reproduce this problem,
tested with "the movie database" and "tmdb tv shows" scraper
"the movie database" scraper log: https://paste.kodi.tv/lesufuqako.kodi
"tmdb tv shows" scraper log: https://paste.kodi.tv/obomeheqem.kodi

![scraper](https://user-images.githubusercontent.com/78986705/123188014-97fea700-d49b-11eb-9129-77f934fb4840.jpg)
![test1](https://user-images.githubusercontent.com/78986705/123188059-a8af1d00-d49b-11eb-8db2-a1aa1b3983e1.jpg)
![test2](https://user-images.githubusercontent.com/78986705/123188073-ad73d100-d49b-11eb-9392-17f89e65126a.jpg)
![test3](https://user-images.githubusercontent.com/78986705/123188090-b49adf00-d49b-11eb-9664-d80148fb86ba.jpg)

**Comment by KarellenX** [comment]
Hi @BergerBlancSuisse and thanks for testing. 

But I disagree with you. You do have the problem. Your nfo files were ignored and an online scrape occurred.

Check this log of yours... https://paste.kodi.tv/lesufuqako.kodi

Line 431- NFO file found as a nfourl / Parsing NFO file which means it has been misidentified
Line 433- The contents of tvshow.nfo are listed and they are clearly created with data from TVDB 
Line 573 to Line 6307- An online lookup occurs at TMDB and online data retrieved (which should not happen when an nfo file is present)
Line 6329- Using TMDB Show ID 91557 for metadata
Line 6333- Adding rating type TMDB of 8.1 and 489 votes. They are not in your nfo file

Line 6527- Found the S01E01 nfo file
Line 6617- Searching TMDB ID 91557 for metadata
Line 6671- Scraped data is used.
Line 7004- Setting TMDB rating which are not in your nfo files.

**Comment by BergerBlancSuisse** [comment]
ok, but the result, the representation in kodi, is okay, isn't it?

**Comment by KarellenX** [comment]
Sure. What you show in your images is ok. No problems with the **scraping**

But just be aware that it was scraped. The nfo files you created with TMM were not used. If you check the data in your nfo files, and compare to what is in your Kodi library, you will see they are different.
