### ISSUE TITLE
Build Fails With Pipewire: "was not declared in this scope"

### ISSUE THREAD

**Issue by vindicatorr** [xbmc/xbmc#19846]
### Describe the bug
Here is a clear and concise description of what the problem is:

```
<pathTo>/xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp: In member function 'virtual bool AE::SINK::CAESinkPipewire::Initialize(AEAudioFormat&, std::string&)':
<pathTo>/xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp:316:26: error: 'PW_KEY_MEDIA_TYPE' was not declared in this scope
  316 |       SPA_DICT_ITEM_INIT(PW_KEY_MEDIA_TYPE, "Audio"),
      |                          ^~~~~~~~~~~~~~~~~
/usr/include/spa-0.2/spa/utils/dict.h:41:64: note: in definition of macro 'SPA_DICT_ITEM_INIT'
   41 | #define SPA_DICT_ITEM_INIT(key,value) (struct spa_dict_item) { key, value }
      |
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should build just fine with pipewire already installed.

## Actual Behavior

The error above (along with related "not declared in this scope" issues)

### To Reproduce

1.  `cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_INTERNAL_FFMPEG=OFF -DENABLE_INTERNAL_CROSSGUID=OFF -DENABLE_DVDCSS=OFF -DENABLE_OPTICAL=OFF -DENABLE_AIRTUNES=OFF -DAPP_RENDER_SYSTEM=gl .. 2>&1 | tee cmake.log`
2. `PREFIX=/usr/local make 2>&1 | tee make.log`

### Debuglog

The debuglog can be found here:
[cmake.log](https://github.com/xbmc/xbmc/files/6598526/cmake.log)
[make.log](https://github.com/xbmc/xbmc/files/6598531/make.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Archlinux
 - Kodi version: Latest git master fetched commit fc8ff86395a9e804105cdfed7f268a923f074df3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by goo952** [comment]
I missed your all🌺🌺🌺🌺🌺🌺🥵🥵🥵

**Comment by ronie** [comment]
i can confirm this issue, happened on Manjaro Linux with pipeline 0.3.28 installed.
my workaround was to downgrade pipewire to 0.3.27

**Comment by asavah** [comment]
The fix is trivial

```
diff --git a/xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp b/xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp
index a00b8ad05e..5b278b9304 100644
--- a/xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp
+++ b/xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp
@@ -17,6 +17,7 @@
 #include "cores/AudioEngine/Sinks/pipewire/PipewireThreadLoop.h"
 #include "utils/log.h"
 
+#include <pipewire/keys.h>
 #include <spa/param/audio/raw.h>
 
 namespace
```

**Comment by fritsch** [comment]
The SPA should be selfcontained, e.g. using internal should be avoided.

**Comment by lrusak** [comment]
or just disable pipewire for the time being `-DENABLE_PIPEWIRE=OFF`

**Comment by vindicatorr** [comment]
Well I'll be...
I had looked for "pipewire" stuff in CMakeLists.txt, but saw nothing.
After you posted that, I grepped and found the flag was generated in CMakeCache.txt.
How'd it do dat? Can someone point me to a link that describes what happened there? It's like it made it out of thin air.

**Comment by lrusak** [comment]
> Well I'll be...
> I had looked for "pipewire" stuff in CMakeLists.txt, but saw nothing.
> After you posted that, I grepped and found the flag was generated in CMakeCache.txt.
> How'd it do dat? Can someone point me to a link that describes what happened there? It's like it made it out of thin air.

We have some special cmake macros, see: https://github.com/xbmc/xbmc/blob/fc8ff86395a9e804105cdfed7f268a923f074df3/cmake/scripts/common/Macros.cmake#L377-L420

So for example any optional dep can be disabled/enabled in the same way. Optional deps are listed here https://github.com/xbmc/xbmc/blob/fc8ff86395a9e804105cdfed7f268a923f074df3/CMakeLists.txt#L148-L176

so, `-DENABLE_PULSEAUDIO=OFF`, `ENABLE_MICROHTTPD=OFF`, etc are valid also.

**Comment by vindicatorr** [comment]
Oooohhh! That's pretty nifty.
I just figured the "general" stuff like `option(ENABLE_OPTICAL     "Enable optical support?" ON)` was all there was.

**Comment by lrusak** [comment]
> Oooohhh! That's pretty nifty.
> I just figured the "general" stuff like `option(ENABLE_OPTICAL "Enable optical support?" ON)` was all there was.

Yea sorry it's not very clear. We could probably have some documentation about that. I'm honestly not sure why it was done that way in the first place (there must be a reason).
