### ISSUE TITLE
Kodi 19.1 stuttering

### ISSUE THREAD

**Issue by JFG1000** [xbmc/xbmc#19856]
Hi there I'm using Kodi 19.1 on a nvidia shield pro, when ever i play a file mainly 23.976fps i get noticeable stuttering, I have provided a de bug log below, this was never present with 18.9

http://paste.kodi.tv/anixosigaq

**Comment by Klojum** [comment]
> I have provided a de bug log below

Please note that Team Kodi will not tell you what you can or cannot install onto your Kodi setup. However, we will not give support to Kodi setups that have one or more add-ons installed that will facilitate video piracy in whatever way.

As per [our forum rules](https://kodi.wiki/view/Official:Forum_rules#Piracy_Policy), support will be halted until a log file of a clean Kodi setup is provided.
