### ISSUE TITLE
Linker Errors on aarch64 (nintendo switch, jetson nano)

### ISSUE THREAD

**Issue by theofficialgman** [xbmc/xbmc#19873]
## Bug report
Kodi builds fine without any complaints in the cmake or build stage, however attempting to run the resulting binary results in the below to libraries not found.
From my research, these libraries appear to only be used on the raspberry pi systems so I am not aware as to why they would be attempted to be loaded on the jetson platforms and other aarch64 systems.

This was not the case prior when I last built off of Kodi from Jun 2020.
Because of this, I believe the large MR here: https://github.com/xbmc/xbmc/commit/811bd4933fbdab9b065c554c8880db4980183b54
and here: 
https://github.com/xbmc/xbmc/commit/605b3b05dc8aee32a1238653a5f02ce5be25719a
could have something to do with this issue

### Describe the bug
```
/kodi/bin$  ldd '/kodi/lib/kodi/kodi-x11'  | grep "not found"
	libvchiq_arm.so => not found
	libbcm_host.so => not found
```
## Expected Behavior
Kodi launches without these libraries
### To Reproduce
clone kodi fork (no affect on this bug) and build
```
git clone https://github.com/aliubimov/xbmc.git -b feature/tegra-support
mkdir xbmc/build
cd xbmc/build
cmake -G "Ninja" .. -DCORE_PLATFORM_NAME=x11 -DAPP_RENDER_SYSTEM=gles -DENABLE_INTERNAL_FFMPEG=ON -DENABLE_INTERNAL_FLATBUFFERS=ON -DENABLE_INTERNAL_FMT=ON -DENABLE_V4L2=ON -DENABLE_NVBUFFER=ON -DENABLE_INTERNAL_SPDLOG=ON -DENABLE_VAAPI=OFF -DCMAKE_INSTALL_PREFIX=/kodi
ninja
sudo ninja install
```

### Your Environment
Used Operating system:
Ubuntu Hirsute Hippo L4T Jetpack 32.3.1

 - Operating system version/name:
 - Kodi version: commit# 826e2ee

**Comment by theofficialgman** [comment]
template was followed and unrelated sections removed

**Comment by theofficialgman** [comment]
it appears that both these libraries are expected by libcec4
https://bugs.launchpad.net/raspbian/+bug/1819444
```
ldd '/lib/aarch64-linux-gnu/libcec.so' | grep "not found"
	libvchiq_arm.so => not found
	libbcm_host.so => not found
```

I am not sure if this is a packaging issue or a kodi issue. Do inform me of the problem

**Comment by theofficialgman** [comment]
I've confirmed it is CEC that is the problem. I am able to launch if I disabled it in with the cmake setting

**Comment by lrusak** [comment]
I'm closing this as it's unrelated to Kodi. Please use the forums for further support. Thanks.
