### ISSUE TITLE
System Info IP address inaccurate

### ISSUE THREAD

**Issue by Morphy99** [xbmc/xbmc#19896]
### Describe the bug
Here is a clear and concise description of what the problem is:

This has been a bug as long as I can remember and I can't see it's had an issue opened for it. In System Info, the IP address appears to report a virtual interface IP when running multiple virtual interfaces such as in a docker environment. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Surely this should default to eth0 or wlan0?

## Actual Behavior

I get a 172.20 address from a bridge interface (br-xxxx)

### To Reproduce

1. Install Docker
2. Run container with a bridge network interface
3. Open system info

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Libreelec 
 - Kodi version:
18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please test with the latest Kodi version and reopen if it's still valid. Thanks!

**Comment by Morphy99** [comment]
> Please test with the latest Kodi version and reopen if it's still valid. Thanks!

Yes it seems to work OK on the latest version. Thanks! I just need to wait to update now as I want to use stable not beta and good addon compatibility. Is there any work around for Leia in the meantime maybe?
