### ISSUE TITLE
Localization links are wrong

### ISSUE THREAD

**Issue by yarons** [xbmc/xbmc#19913]
Localization links in the readme are still pointing to the obsolete Transifex project rather than the new Weblate instance.

**Comment by gade01** [comment]
Do you mean here: https://github.com/xbmc/xbmc/blob/master/README.md ?

Those will be updated when we start updating documentation.

**Comment by yarons** [comment]
Thanks :)

**Comment by gade01** [comment]
@yarons PR's are merged.

Thanks a lot for reporting it.
