### ISSUE TITLE
Colour issue with text based subtitles

### ISSUE THREAD

**Issue by vangeliis** [xbmc/xbmc#19911]
### Describe the bug

Hello,
I have set the subtitle colour to 'Dark Grey' (Settings-Player-Language-Colour). When I play back a file with tx3g or srt subtitles muxed in, whenever a subtitle line contains special formatting like Italics [ i][ /i] then the text in Italics is displayed in white colour instead of Dark Grey.

## Expected Behavior

Expect the texted based subtitles to be displayed in the set colour (Dark Grey in my case).

## Actual Behavior

Formatted text is not obeying the set subtitle colour and is rendered in White.

## Possible Fix

Not sure.

### To Reproduce

1. Set subtitle colour to anything other than White
2. Play a file with text based subtitles (srt and/or tx3g)
3. When a line contains special formatted text like words in Italics or a musical note in case of a lyric, then these words are displayed in White instead of the chosen colour.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV - Shield TV
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Please provide the subtitle file in use or at least the debuglog which shows the behavior. It would make it way easier for us to reproduce your problem if we could use the same file like you do.
