### ISSUE TITLE
Inefficient and semi-unreadable function

### ISSUE THREAD

**Issue by busterbeam** [xbmc/xbmc#19922]
https://github.com/xbmc/xbmc/blob/d682f51a852264232a4b3ef6f483b56dd630ce5f/addons/metadata.demo.tv/demo.py#L9-L11
Could be just two lines with `paramstring = sys.argv[1]` being `param = sys.argv[1]` and `if len(paramstring)>=2:` being `if len(param) >= 2:`
https://github.com/xbmc/xbmc/blob/d682f51a852264232a4b3ef6f483b56dd630ce5f/addons/metadata.demo.tv/demo.py#L13-L14
These lines do nothing in this function and what you want really is `params.rstrip('/')`
https://github.com/xbmc/xbmc/blob/d682f51a852264232a4b3ef6f483b56dd630ce5f/addons/metadata.demo.tv/demo.py#L17-L19
Maybe just `for param_pair in pairsofparams:`?  As your just indexing the same thing with a list like this.  also `splitparams = {}` is pointless in this loop

**Comment by enen92** [comment]
@busterbeam thanks. It'd be better if you just pr the changes. This demo add-on is not being maintained afaik
