### ISSUE TITLE
[Raspberry Pi 4] max_framebuffers=2 ignored.

### ISSUE THREAD

**Issue by juxuanu** [xbmc/xbmc#19936]
### Describe the bug
Here is a clear and concise description of what the problem is:

With a Raspberry Pi4 I have, I can, in any distribution, add `max_framebuffers=2` into `config.txt` and have video output through more than one port.
In my case, I have the official Raspberry Touchscreen Display attached through DSI and a projector connected through one of the HDMI ports. Having the mentioned option in `config.txt` displays video through both outputs, but not when Kodi is launched.
I have tried with:
- ArchLinux ARM, Manjaro ARM: doesn't work with none of the three options, GBM, x11 or Wayland. Desktop and initial boot screen can be shown on both video outputs simultaneously. But when starting Kodi, only 1 display is not blank.
- Raspbian: same as above with their `kodi` package.
- LibreElec: similarly to above, the splash screen is shown on both video outputs (aswell as the rainbow texture) until Kodi is loaded, which makes one screen go blank.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should handle this situation, at least, duplicating the video output to both displays.

### To Reproduce

1. Install Kodi on a Raspberry Pi 4
2. Connect display through DSI and another display through HDMI. 
3. Launch Kodi

### Debuglog

The debuglog can be found here:
Let me know if a debug log is any useful in this situation. 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.9.0 `leia_pi4_18.9-Leia` (compilation 2021-05-27)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Kodi is only able to run on one monitor. If the device firmware has some way to mirror displays I would ask them for help.

Also, Kodi 19.1 is the latest version.

**Comment by juxuanu** [comment]
@lrusak so, I'm asking for a feature... Would that be discussed or will it be closed like this?

**Comment by lrusak** [comment]
Feature requests are made on the forum.
