### ISSUE TITLE
Specific Dolby Digital Plus audio problem

### ISSUE THREAD

**Issue by VsnGamer** [xbmc/xbmc#19939]
## Bug report

Hello, I have a video that has problems with the audio, after a few seconds the "aq" starts dropping and it buffers (vq is fine).
The source speed cannot be the problem because full 4K blu-rays with TrueHD and Atmos play fine, however, with this video, even when playing from the local disk it buffers.
This is weird because it's the only video that has problems both in the Shield TV Pro 2019 and Windows 10. Other files with similar audio encodings work fine.
I believe it is a kodi issue (or maybe ffmpeg?) because when I play it with MPV it works fine (WebDav and local disk)

Thanks in advance for your time
## Expected Behavior

Play the file without issues.

## Actual Behavior

Buffering and sometimes kodi tries to correct it by seeking a few seconds back with no success until it skips a bit forward and plays fine for 1 or 2 minutes (I think the drops occur in specific timestamps but the file mustn't be corrupted since MPV manages to play it no problem)

### To Reproduce

1. Try to play this specific file

### Debuglog

The debuglog can be found here: [issue.log](https://github.com/xbmc/xbmc/files/6764450/issue.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Kodi Screenshot 2021 07 05 - 14 10 09 43](https://user-images.githubusercontent.com/18006201/124476609-f03a8080-dd9a-11eb-9085-ba785edb1255.png)

### Environment
Used Operating system:

 - [x] Android
 - [x] Windows

 - Operating system version/name:
 - Kodi version: Tried 19.1 and latest master cc59a7b

### Mediainfo
<details>
<summary>Show</summary>
<p>

> General
> Format                                   : Matroska
> Format version                           : Version 4
> File size                                : 6.87 GiB
> Duration                                 : 1 h 4 min
> Overall bit rate                         : 15.1 Mb/s
> Writing application                      : Lavf58.39.101
> Writing library                          : Lavf58.39.101
> ErrorDetectionType                       : Per level 1
> 
> Video
> ID                                       : 1
> Format                                   : HEVC
> Format/Info                              : High Efficiency Video Coding
> Format profile                           : Main 10@L5@Main
> HDR format                               : SMPTE ST 2094 App 4, Version 0, HDR10 compatible
> Codec ID                                 : V_MPEGH/ISO/HEVC
> Duration                                 : 1 h 4 min
> Bit rate                                 : 14.6 Mb/s
> Width                                    : 3 840 pixels
> Height                                   : 2 160 pixels
> Display aspect ratio                     : 16:9
> Frame rate mode                          : Constant
> Frame rate                               : 23.976 (24000/1001) FPS
> Standard                                 : NTSC
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0 (Type 2)
> Bit depth                                : 10 bits
> Bits/(Pixel*Frame)                       : 0.073
> Stream size                              : 6.61 GiB (96%)
> Language                                 : English
> Default                                  : Yes
> Forced                                   : No
> Color range                              : Limited
> Color primaries                          : BT.2020
> Transfer characteristics                 : PQ
> Matrix coefficients                      : BT.2020 non-constant
> Mastering display color primaries        : Display P3
> Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
> Maximum Content Light Level              : 970 cd/m2
> Maximum Frame-Average Light Level        : 269 cd/m2
> 
> Audio
> ID                                       : 2
> Format                                   : E-AC-3 JOC
> Format/Info                              : Enhanced AC-3 with Joint Object Coding
> Commercial name                          : Dolby Digital Plus with Dolby Atmos
> Codec ID                                 : A_EAC3
> Duration                                 : 1 h 4 min
> Bit rate mode                            : Constant
> Bit rate                                 : 576 kb/s
> Channel(s)                               : 6 channels
> Channel layout                           : L R C LFE Ls Rs
> Sampling rate                            : 48.0 kHz
> Frame rate                               : 31.250 FPS (1536 SPF)
> Bit depth                                : 32 bits
> Compression mode                         : Lossy
> Stream size                              : 268 MiB (4%)
> Language                                 : English
> Service kind                             : Complete Main
> Default                                  : Yes
> Forced                                   : No
> Complexity index                         : 16
> Number of dynamic objects                : 15
> Bed channel count                        : 1 channel
> Bed channel configuration                : LFE
> 
> Text
> ID                                       : 3
> Format                                   : UTF-8
> Codec ID                                 : S_TEXT/UTF8
> Codec ID/Info                            : UTF-8 Plain Text
> Duration                                 : 1 h 2 min
> Bit rate                                 : 43 b/s
> Count of elements                        : 777
> Stream size                              : 19.7 KiB (0%)
> Title                                    : English (SDH)
> Language                                 : English
> Default                                  : No
> Forced                                   : No

</p>
</details>

**Comment by matthuisman** [comment]
not sure if this is related, but I've found any 5.1 (EAC3 or AC3) on Kodi Android causes buffering.
Found this with HBO Max, Binge, Disney+ etc.
I've had to add settings to each of them to allow removing the EAC3 and AC3 tracks so playback works.

can you tell me how you get that overlay in Kodi showing the aq and vq?
Also, what software do you use to get the media info?

**Comment by VsnGamer** [comment]
- Overlay: `ctrl + shift + o`
- MediaInfo: just get it from your package manager or from the [website](https://mediaarea.net/en/MediaInfo)

**Comment by telewizortcl** [comment]
I sometimes have this problem when high-quality sound processing is selected in the settings. Try to choose the lowest option and see if it helps.
