### ISSUE TITLE
Kodi crashes quite often when exiting LiveTV or a TV-recording (using current Tvhadend HTSP Client)

### ISSUE THREAD

**Issue by maxberghammer** [xbmc/xbmc#19931]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I watch Live-TV or a TV-recording and want to exit the playback through the esc-key, Kodi quite often hangs and doesn't react on anything anymore. The playback stops, the last displayed frame keeps showing and nothing more happens. I have to turn off my raspberry and turn it on again then. This only happens when exiting LiveTV or TV-recordings. Watching+exiting videos in YouTube, other Addons or from my NAS, never shows this behaviour.

I already tried to wait, if the system is in this state (multiple hours), but nothing changes. Even the debug-log doesn't grow anymore.

When Kodi is unresponsive, i still can SSH onto the system. This works, but i can't remember exactly, if the Kodi-process keeps on having constant CPU-Usage or if it is idling then. dmesg shows no errors.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When I press the esc-key, the playback should stop and Kodi should display the home-screen, as it does, when I exit the playback of a YouTube-Video or a video-file on my NAS.

## Actual Behavior

Kodi hangs and becomes completely unresponsive.

### To Reproduce

It's really difficult to reproduce, as this doesn't happen always. I have the feeling, that the posibility, the problem arises, grows, the longer I watch LiveTV or a certain recording and/or the more I use ffwd/frev.

1. Watch LiveTV or a TV-recording with current version of Tvheadend HTSP Client Addon for some longer time
2. Hit the esc-key
3. Kodi sometimes hangs and becomes completely unresponsive

### Debuglog

The debuglog can be found here:
https://1drv.ms/u/s!AlktgACEkG56h8QMC68MVteI5MpQpw?e=fsI9vx

it's the kodi.log at the time, Kodi is unresponsive and the kodi.old.log after i restart my raspberry by turning it of an on again.
IMHO the following timestamps should be of interest:
2021-05-22 21:13:37.654	start playback of a tv-recording
2021-05-22 22:01:30.326	enable debug-log by ctrl-shit-d
2021-05-22 22:01:33.305	press esc-key to exit the playback

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux retropie2 5.10.17-v7l+ 1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l
 - Kodi version: 18.7 Git:20200528-2c5354e70a
 - Tvheadend HTSP Client Addon 4.4.20
 - Raspberry Pi 4 Model B 4GB

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
> Kodi version: 18.7 Git:20200528-2c5354e70a

 Kodi 18 is EOL, no more fixes. Try Kodi 19 and report back.

**Comment by maxberghammer** [comment]
Yes, I know, but I can't update, as 19 wasn't released for raspbian/retropie, yet :(

**Comment by ksooo** [comment]
> Yes, I know, but I can't update, as 19 wasn't released for raspbian/retropie, yet :(

 No more fixes for Kodi 18. Seriously.

**Comment by maxberghammer** [comment]
I understand that. But, if someone could give me the right direction, I could fix it myself probably...

**Comment by basilgello** [comment]
You can try building Kodi yourself or try installing Debian testing - it has 19.1 packaged

**Comment by maxberghammer** [comment]
ah, ok, thx! will try debian testing. building myself didn't work without further investigation.
