### ISSUE TITLE
Laggy Playback and Unresponsive Interface on Android TV/Nvidia Shield while playing some content

### ISSUE THREAD

**Issue by Nerdy314159265** [xbmc/xbmc#19932]
### Describe the bug
When launching certain content (seems to be 4K HDR), the system will lag extensively, the UI will become unresponsive, playback will lag or freeze with audio playback continuing and attempts to close the content can be difficult do to the unresponsiveness of Kodi.

This won't happen 100% consistently, at least not at maximum failure. Occasionally playback can recover and the severity changes with restarts of the program (possibly restarts of the content as well).

Program will occasionally show "Source too slow" error message but content plays back with no issues from same source on other devices. In my case source is an smb share and the Nvidia Shield is on a wired connection.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Content should play at full speed without stuttering or lagging.

## Actual Behavior
Content frequently lags or freezes becoming unwatchable
UI will become unresponsive to inputs

### To Reproduce

1. Launch Kodi
2. Launch 4K HDR content

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/wenocikipo.kodi

### Your Environment
 - Operating system version/name: Android 9.0.0
 - Kodi version: 19.1

**Comment by Nerdy314159265** [comment]
During a recent watch, I was having issues with a 4K HDR file and found that disabling the option named something like "Use displays HDR capabilities" allowed the file to play without issues.

I think that adds more weight to the idea that HDR support is the specific source of the issue.

**Comment by rconstantin1980** [comment]
having the same issue on my 2019 nvidia shield tv (tube).

my log is here:

https://paste.kodi.tv/olajekafog

**Comment by ryamoo** [comment]
I've been struggling to get a 70gb  UHD 2160p HEVC bluray rip to play on Kodi on my Android TV (Sony KD-AG8). 
It's as though Kodi can't fill up the cache, and when it does it can't keep it full. 
The file is on my Pi4, tried sharing via NFS, FTP, SMB, and cannot get it to play well without lagging, stuttering, sync issues - it's unwatchable and then takes a while for it to "stop" and go back to the UI. 
I've tested disk read on the Pi, and I've done some iperf tests between the TV and the Pi, and both tests are more than enough to handle the file. I did the tests on my Windows 10 PC and saw similar results, and the file plays back fine there. 
I'd tried cache settings readfactor of 1, 5, 20, 50 and 1000, but it doesn't seem to make a difference. 
I've tried memorysize as 50mb, 75, 150, 200, and most recently 450mb (471859200). 
The only thing I've noticed is on the info that appears when sending "ctrl+shift+o" the size for the video buffer seems to be about a 3rd of what I've set in the advanced settings cache. It hangs to fill it up, playback starts, then it gradually empties until the video stops again. 
All the time the sync is out by a few seconds. 
I've got 450mb set currently, and the info shows ~130mb at most. 
I previously set 250mb and the info was maxing out at ~74.5mb. 
This is what I saw when memorysize was set to 250mb using nfs: 
![image](https://user-images.githubusercontent.com/13999873/130119245-58a8d142-4947-471a-babb-ac9234304ff4.png)

Not sure if my understanding of the cache settings is wrong, but I thought whatever I said in the advancedsettings would be tripled, so if I set 250mb it would use 750mb, however the info suggests it's using a third and not triple? 

The closest I've got to it playing well is switching to a webdav server on the Pi4 - it's not perfect, and probably still unwatchable, but I've had the longest playback using webdav. 
This is the ctrl+shift+o info when playing back via webdav and 250mb memorysize in the advanced settings/cache:
![image](https://user-images.githubusercontent.com/13999873/130119110-4160e34f-88bb-4e27-82ac-f803f6a0f63c.png)

I've tried and failed to get a log generated, so I know my info might be useless until then. I'll work on getting that tonight.

**Comment by Nerdy314159265** [comment]
You should test again with HDR disabled. If I'm correct then the HDR support is the cause for this issue.

**Comment by HitcherUK** [comment]
The Tube only has 3GB RAM which isn't really enough for playing high bitrate 4k (HDR) content.

**Comment by Nerdy314159265** [comment]
> The Tube only has 3GB RAM which isn't really enough for playing high bitrate 4k (HDR) content.

There weren't issues with it before. Some update must've broke it.

**Comment by HitcherUK** [comment]
Before what exactly?

I had this issue day one with my tube and Kodi Krypton as did many others on the forum. I changed it for the Pro.

**Comment by ryamoo** [comment]
> @ryamoo You should test again with HDR disabled. If I'm correct then the HDR support is the cause for this issue.

I'm not seeing that option in kodi's settings if that's where you mean.
I've tried turning the TV's HDR mode to Off though, but it didn't make a difference. 
If you can tell me where I find the setting on Kodi I'll give it a try.

**Comment by ryamoo** [comment]
> The Tube only has 3GB RAM which isn't really enough for playing high bitrate 4k (HDR) content.

I know what wasn't aimed at me but I think my TV has ~2gb ram. 
Whenever I've played a 4k HDR file (at most ~50gb, because above that doesn't seem to buffer) the ram usage only ever seems to go up by about 350mb at most. 
Most of the times when I check, there's still at least 500mb ram available during playback. 

As for ram speed... I'm starting to wonder if the TV's ram is just too slow and so can't empty and fill quick enough for the bigger files 🤷🏻‍♂️

**Comment by wsnipex** [comment]
try copying a file to the device directly, instead of playing over network.

**Comment by Nerdy314159265** [comment]
> > @ryamoo You should test again with HDR disabled. If I'm correct then the HDR support is the cause for this issue.
> 
> @Nerdy314159265 I'm not seeing that option in kodi's settings if that's where you mean.
> I've tried turning the TV's HDR mode to Off though, but it didn't make a difference.
> If you can tell me where I find the setting on Kodi I'll give it a try.

It should be in Settings > Player > Videos > Use display HDR capabilities, make sure you are on Expert

> I had this issue day one with my tube and Kodi Krypton as did many others on the forum. I changed it for the Pro.

I could be remembering incorrectly, I did have a Pi4 that I used previously with Kodi. However, it still seems weird that the issues almost completely disappeared for me when I disabled HDR. I've had 1 complaint message and maybe 1 playback issue since changing that setting when it was rather consistently problematic before.

**Comment by ryamoo** [comment]
> It should be in Settings > Player > Videos > Use display HDR capabilities, make sure you are on Expert

That just isn't there for me. 
Above the Playback section is Actions for skip steps, and below processing is Stereoscopic 3D and Teletext. 

![IMG_20210820_104525](https://user-images.githubusercontent.com/13999873/130214958-6a529f42-a478-4644-ba81-fd9cfdb6907e.jpg)

**Comment by ryamoo** [comment]
> try copying a file to the device directly, instead of playing over network.

1.3gb file in 1:06 (66 seconds) via FTP. Roughly 20mb/sec - 169Mbps.
158mb file, 8 seconds. Similar speed.

**Comment by wsnipex** [comment]
I kinda expected that. Your network doesn't seem to keep up with the bitrate

**Comment by ryamoo** [comment]
> I kinda expected that. Your network doesn't seem to keep up with the bitrate

169Mbps isn't enough for a movie that's about 80Mbps bitrate? 
If I can plug the SSD in again later I'll copy to that over FTP - not sure the TV's storage is all that fast. When I ran an iperf test between my server and TV, it was a considerable amount more than 169Mbps.

**Comment by Nerdy314159265** [comment]
> 
> 
> I kinda expected that. Your network doesn't seem to keep up with the bitrate

That definitely seems wrong as his tests all are double the video bitrate.

That also doesn't make any sense why the video would play fine on other devices without pausing for buffering, which IRC we both were able to do without issue.

**Comment by Nerdy314159265** [comment]
Any updates on fixing this issue?

Some corrections I'll make since I last posted.
I realized that the mode that I thought would turn HDR off didn't, it's just that since the issue is highly variable that it seemed like it had helped.
I also wanted to mention that I remember trying at least once with a purely 4K video and it didn't seem to have issues but starting an HDR video seemed to have issues.

I or someone else might try taking an HDR video (hopefully one that consistently has this issue), converting it to SDR and trying to play both versions multiple times to see if it's purely HDR that is causing the problem.
