### ISSUE TITLE
Crash while restarting pvr.hts add-on

### ISSUE THREAD

**Issue by vindicatorr** [xbmc/xbmc#19968]
### Describe the bug
Here is a clear and concise description of what the problem is:

Crash on starting kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi starts and runs normally?

## Actual Behavior

Crash on starting kodi?

## Possible Fix

Some commit after my last build version: https://github.com/xbmc/xbmc/issues/19846 (https://github.com/xbmc/xbmc/commit/fc8ff86395a9e804105cdfed7f268a923f074df3)

### To Reproduce

1. Build with pipewire enabled (added the #include) so it would build rather than just disable it like I did last time.
2. Run kodi
3. Profit from crash

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/6797457/kodi.log)
[kodi_crashlog-20210711_132256.log](https://github.com/xbmc/xbmc/files/6797467/kodi_crashlog-20210711_132256.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I see I also have to jump forward (from last successful build) to commit 90e947b8da26e2754287ac4de0be3bfdcf44e961.
Interesting... I had moved ~/.kodi so it could be recreated fresh with the LATEST commit, and it still crashed.
With 90e947b8da26e2754287ac4de0be3bfdcf44e961, it ran just fine (didn't venture far).
But when I restored my original/previous ~/.kodi, it crashed somewhat similarly...
[kodi1.log](https://github.com/xbmc/xbmc/files/6797715/kodi1.log)
[kodi_crashlog-20210711_163948.log](https://github.com/xbmc/xbmc/files/6797716/kodi_crashlog-20210711_163948.log)
Starting with a fresh .kodi, and this 90e commit worked fine again.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Archlinux
 - Kodi version: Latest git master fetched commit adea6bd3acc3e78db8ec235d4744ebfeb86951fd

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
> But when I restored my original/previous ~/.kodi, it crashed somewhat similarly...

Can you give me access to this configuration? As you wrote the crash does not occur with a fresh configuration.

**Comment by vindicatorr** [comment]
Well, that was for the 90e commit, but not with the latest commit which still crashed, even with a fresh .kodi.

Is there anything more specific you can ask for or want me to check on my end instead? I just don't want to leak anything out like '<setting id="pass">'.

**Comment by ksooo** [comment]
For the crash scenario, please provide a kodi.log with DEBUG for PVR and EPG components enabled.

**Comment by ksooo** [comment]
Okay, investigated a little more time in the logs you have supplied.

We're facing two different crashes. Let's for now concentrate on the one occurring on first startup, with pvr.hts installed as a system add-on and no .kodi data => kodi_crashlog-20210711_163948.log

I read from the log that you did the following:

You deleted .kodi userdata folder (or moved it away)
You start Kodi. => Kodi asks whether you want to enable pvr.hts
You answered yes => pvr.hts settings dialog opens
You enter some data, obviously missing the correct credentials => Kodi shows an "access denied" popup
You open the add-on settings again and enter the correct (? does not really matter for the crash I guess) creds => "Needs restart" box appears
You confirm the box => Crash

Unfortunately, the log is not complete. It seems Kodi crashed before the buffer could be written to disk. The last part, where the add-on ist restarted (initiated by "dll destroyed") is missing.

The good thing is that I can reproduce the crash with the steps above. The bad thing is that it crashes without giving me a usable stack trace for the crashing thread.

Important: The stack trace in your log does not detect the thread that is really crashing. It's definetly not thread 1.

**Comment by ksooo** [comment]
I found the root cause of the crash. It is due to stale threads in pvr.hts, thus the issue needs to be fixed in the add-on. I will see what I can do.

**Comment by vindicatorr** [comment]
I can confirm that fix worked, though I don't know if you want to take into consideration abnormal/irrational interactions like:
1. Start with a fresh .kodi
2. Ignore the pvr addon message at the start
3. Go to pvr settings and Enable pvr first
4. THEN go to Configure and set the credentials.
5. Go to the TV section
You'll find pvr updating will just sit at 0%. In Tvheadend, you'll see the authentication failures keep coming in.
6. Go back to pvr settings, and Disable, then Enable.
Now it'll be okay.

I don't know if you want to go back to the initial issue with my original .kodi causing crashes. It still does.
I'm fine with just going with the fresh .kodi.
I DID manage to manually set debug.showloginfo, debug.extralogging, trace_debug to true (though I'm not seeing any differences really):
[kodi.log](https://github.com/xbmc/xbmc/files/6819103/kodi.log)
[kodi_crashlog-20210714_164545.log](https://github.com/xbmc/xbmc/files/6819104/kodi_crashlog-20210714_164545.log)
