### ISSUE TITLE
Share playlists with other applications

### ISSUE THREAD

**Issue by mvglasow** [xbmc/xbmc#19966]
## Roadmap or todo item
**Detailed Description**

Playlists on a shared storage device (e.g. a network share) can currently be imported into Kodi, but the process is somewhat cumbersome and far from obvious (Music > Files > navigate to playlist > context menu > Edit Playlist > Save). If the playlist on the shared storage device changes, these steps have to be repeated in order to update it.

Suggestion: Instead of just browsing the playlist file on external storage and importing it into an internal playlist, provide a way to use playlists residing directly on the storage device. Thus, when the playlist on the external device changes, Kodi will automatically get these changes without any need for extra user interaction. As a bonus, changes made to these playlists from the Kodi UI would automatically get written back to the network share.

### Context

Mostly aimed at use cases where a network share is accessed by multiple devices: multiple Kodi setups, or even different software (say, a Kodi-based media center and a laptop using an entirely different media player). This would allow users to share playlists across multiple devices. Universal exchange formats such as M3U or PLS exist, and Kodi supports them at least to the point of being able to import them.

### Possible Implementation

* If not already present, add support for reading playlists from any location configured for the corresponding media type.
* If not already present, add support for PLS playlist format (internal playlists seem to be M3U).
* If necessary, extend playlists to rely on a library rather than an ordinary local folder.
* Extend the media scanner to process playlists and add them to the respective playlists menu.

### Additional context, screenshots or links
Here are some relevant links or screenshots

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by lrusak** [comment]
Please make feature requests on the forum. Thanks.

**Comment by mvglasow** [comment]
Done, see https://forum.kodi.tv/showthread.php?tid=363528. However, a hint that feature request should be posted on the forum (with a link) rather than here would be appreciated – every project handles feature requests in a different way.
