### ISSUE TITLE
kodi crashes while scanning for new content of tvshow

### ISSUE THREAD

**Issue by yherve** [xbmc/xbmc#19977]
### Describe the bug
kodi crashes (core dump) while scanning for new content of a tvshow.

I am trying to write a video plugin that presents tvshow resources properly from a flat list so that they can be scanned and added to the library.

For this I have added a data source that references my plugin:

        <source>
            <name>Series AD2</name>
            <path pathversion="1">plugin://plugin.video.adlib2/</path>
            <allowsharing>true</allowsharing>
        </source>

when I edit this source to specify tvshows content, and then refresh the content, kodi crashes
the exact same plugin works fine with kodi 18.9

problem occurs on linux (arch64) and androidtv 9

## Expected Behavior

not crash

## Actual Behavior

crash

### To Reproduce

1. copy the tiny plugin I have provided to addons/enable it
2. add the sources.xml to userdata
3. edit the source, select tvshows, scan for new content

### Debuglog

The debuglog is attached. I can provide the core file if you need it

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.1 (19.1.0) Git:20210509-nogitfound Media Center Kodi

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*
[kodi_crashlog-20210716_115626.log](https://github.com/xbmc/xbmc/files/6829923/kodi_crashlog-20210716_115626.log)
[plugin.video.adlib2.zip](https://github.com/xbmc/xbmc/files/6829941/plugin.video.adlib2.zip)
[sources.xml.txt](https://github.com/xbmc/xbmc/files/6829945/sources.xml.txt)
[stacktrace.txt](https://github.com/xbmc/xbmc/files/6829948/stacktrace.txt)

**Comment by KarellenX** [comment]
Can you also post a debuglog that captures the crash. Thanks.

**Comment by yherve** [comment]
here you go

[debuglog.zip](https://github.com/xbmc/xbmc/files/6834526/debuglog.zip)
