### ISSUE TITLE
kodi fails to resume .strm files

### ISSUE THREAD

**Issue by yherve** [xbmc/xbmc#19981]
### Describe the bug
you cannot resume  a movie in that is in a  .strm file

The movie in a .strm file can be stopped and resumed as long as you don't navigate away from the directory. Once you leave and re-enter the directory it is no longer possible to resume the movie

## Expected Behavior

when stopping the movie with the square button, and navigating away or closing/restarting kodi, it should be possible to resume the movie

## Actual Behavior

currently stopping the movie with the square button, and closing/restarting kodi, and trying to resume the movie, makes the movie start from the beginning

### To Reproduce

1. create a .strm file containing an url, e.g

``` https://archive.org/download/thekillers1946usafeaturingburtlancasteravagardneredmondobrienfilmnoirfullmovie_202001/The%20Killers%20%281946%2C%20USA%29%20Featuring%20Burt%20Lancaster%2C%20Ava%20Gardner%2C%20Edmond%20O%27Brien%20-%20Film%20Noir%20Full%20Movie.mp4
``` 
2. place this mymovie.strm in a source (local, smb, it does not matter...)
3. Navigate to the source Videos => Files => your source (notice the file shows as mymovie.strm)
4. launch the movie, fast forward to the middle
5. stop the movie with the square button
6. notice at this point that the url shows in the directory (rather than mymovie.strm) and if you try to resume the movie it works
7. leave the directory (go to the parent), then reenter the directory
8. notice that the movie is now called mymovie.strm and it has the icon showing that the movie is in progress
9. try to  resume the movie, the position is lost and it starts from the beginning

### Debuglog

The debuglog can be found here:
[debuglog.zip](https://github.com/xbmc/xbmc/files/6834719/debuglog.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux arch1 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linux
 - Kodi version: 19.1 (19.1.0) Git:20210509-nogitfound Media Center Kodi

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
Issue fixed by #21830
