### ISSUE TITLE
Label $INFO[System.InternetState] does not return TRUE or FALSE

### ISSUE THREAD

**Issue by harryberlin** [xbmc/xbmc#19987]
### Describe the bug
Here is a clear and concise description of what the problem is:
Label $INFO[System.InternetState] does not return TRUE or FALSE like documentation describs.

## Actual Behavior
Label $INFO[System.InternetState] does not return TRUE or FALSE like documentation describs.
https://kodi.wiki/view/List_of_boolean_conditions#System

## Possible Fix
there are 2 options:
1. return TRUE or FALSE like documentation
2. edit documentation TRUE -> $LOCALIZE[13296] and FALSE -> $LOCALIZE[13297]

### To Reproduce

1.  set some label with $INFO[System.InternetState]
2. check result
3. compare with info from documentation

### Debuglog
no debug log exist. there is no no error in the log file.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18 + 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
I'm not a skinner, but the code tells me that there are two implementations for System.InternetState:

First is an info label, thus returning a string, in this case localized version of string with id 13296 "Connected" or id 13297 "Not connected. Check network settings."

Seconds an info bool, returning TRUE or FALSE.

So, your problem is how to call the info bool version of System.InternetState.

@ronie can you shed some light on this?

**Comment by ronie** [comment]
sure, if you use it as a label `<label>$INFO[System.InternetState]</label>` it will return connected / not connected (localized).

if you use it inside a condition, like `<visible>System.InternetState</visible>` 
or `<include condition="System.InternetState">` it will return TRUE or FALSE.

**Comment by ksooo** [comment]
So, I guess we can close this one. Layer 8 error. :-)

**Comment by harryberlin** [comment]
Could you append the boolean condition to documentation?
https://kodi.wiki/view/List_of_boolean_conditions#System
Because it was not clear for me. So i did this:
`<visible>String.IsEqual(System.InternetState,$LOCALIZE[13296])</visible>`

**Comment by ronie** [comment]
sure, done.
