### ISSUE TITLE
Can not build dependency for android app.

### ISSUE THREAD

**Issue by todeveloper21** [xbmc/xbmc#19996]
I tried to build dependency lib for android app, but failed to build JsonSchemaBuilder.

Build configuration
Ubuntu 16.04 
Android SDK 28.0.3, NDK 20.1.5948944
Kodi version: cloned latest git repository
error output:

~/kodi/tools/depends# ./configure --with-tarballs=/root/Android/xbmc-tarballs --host=arm-linux-androideabi --with-sdk-path=/root/Android/Sdk --with-ndk-path=/root/Android/Sdk/ndk/20.1.5948944 --prefix=/root/Android/xbmc-depends --with-sdk=android-28 --with-toolchain=/root/Android/Sdk/ndk/20.1.5948944/toolchains/arm-linux-androideabi-4.9 --enable-neon

make[2]: Leaving directory '/root/kodi/tools/depends/native/distutilscross'
make -C JsonSchemaBuilder
make[2]: Entering directory '/root/kodi/tools/depends/native/JsonSchemaBuilder'
make -C x86_64-linux-native
make[3]: Entering directory '/root/kodi/tools/depends/native/JsonSchemaBuilder/x86_64-linux-native'
make[3]: *** No targets specified and no makefile found.  Stop.
make[3]: Leaving directory '/root/kodi/tools/depends/native/JsonSchemaBuilder/x86_64-linux-native'
Makefile:34: recipe for target 'x86_64-linux-native/JsonSchemaBuilder' failed
make[2]: *** [x86_64-linux-native/JsonSchemaBuilder] Error 2
make[2]: Leaving directory '/root/kodi/tools/depends/native/JsonSchemaBuilder'
Makefile:68: recipe for target 'JsonSchemaBuilder' failed
make[1]: *** [JsonSchemaBuilder] Error 2
make[1]: Leaving directory '/root/kodi/tools/depends/native'
Makefile:8: recipe for target 'native/.installed-x86_64-linux-native' failed
make: *** [native/.installed-x86_64-linux-native] Error 2
(base) root@zhen-VirtualBox:~/kodi/tools/depends#

**Comment by wsnipex** [comment]
please refer to support channels(forum, IRC, matrix).
