### ISSUE TITLE
Change spelling for item #15109 in resource.language.de_de/resources/strings.po from "Standartwert" to "Standardwert"

### ISSUE THREAD

**Issue by b-jesch** [xbmc/xbmc#20005]
There is nothing more to say as in German the word "standart" is a big "ouch!"

**Comment by lrusak** [comment]
Please make the request at webpage where all the translations are handled.

https://kodi.weblate.cloud/

**Comment by ksooo** [comment]
I will take care of this and charger it at Weblate.

**Comment by ksooo** [comment]
done. will be fixed with next resourec pack update.
