### ISSUE TITLE
Corrupted font / characters using AMD 6800 GPU

### ISSUE THREAD

**Issue by zach-morris** [xbmc/xbmc#20008]
### Describe the bug
Here is a clear and concise description of what the problem is:
The last character of every word in the Kodi GUI appears corrupted using Windows 10 (or 11) paired with an AMD 6800 GPU (or similar, see forum links below, other similar models show the same issue).  See the following images:
![TA2i6A8](https://user-images.githubusercontent.com/12554283/127706999-ffb89fa7-5671-491a-aeb4-8e32fd65dfd1.png)
![Kodi-1](https://user-images.githubusercontent.com/12554283/127707073-d9a41936-cf1d-4654-adbb-c7d31d4d78ae.png)
![Kodi-2](https://user-images.githubusercontent.com/12554283/127707085-e3e6e063-84a0-45c6-822a-476fb553a16c.png)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Text is not corrupted when using the GPU(s) noted.

## Actual Behavior
Text is corrupted, every last character of every word, when using the GPU(s) noted.

## Possible Fix
Unknown if this is a GPU driver issue or Kodi fixable issue.  A moderator in the Kodi forum suggested this was a driver issue, but I'm not sure how that conclusion was made.

### To Reproduce

1.  Install Kodi on a Windows 10 or newer PC paired with an AMD 6800 GPU or similar
2.  Start Kodi, note corrupted fonts

Understand that this may be difficult to troubleshoot without the appropriate hardware, so I'm willing to help if necessary with additional troubleshooting or information.

### Debuglog

Below is a debug log showing my system build.  There is no other notable information in debug logs.  I will note I installed the latest nightly v20 Alpha, and the latest v19 stable, hoping the Harfbuzz library would potentially fix the problem, but the problem persists with any version of Kodi newer than 18.9:
```
2020-12-12 21:19:18.311 T:7836  NOTICE: -----------------------------------------------------------------------
2020-12-12 21:19:18.311 T:7836  NOTICE: Starting Kodi (18.9 (18.9.0) Git:20201023-0655c2c718). Platform: Windows NT x86 64-bit
2020-12-12 21:19:18.311 T:7836  NOTICE: Using Release Kodi x64 build
2020-12-12 21:19:18.311 T:7836  NOTICE: Kodi compiled 2020-10-23 by MSVC 191627035 for Windows NT x86 64-bit version 10.0 (0x0A000007)
2020-12-12 21:19:18.311 T:7836  NOTICE: Running on Windows 10, kernel: Windows NT x86 64-bit version 10.0.19042
2020-12-12 21:19:18.311 T:7836  NOTICE: FFmpeg version/source: 4.0.4-Kodi
2020-12-12 21:19:18.311 T:7836  NOTICE: Host CPU: AMD Ryzen 5 5600X 6-Core Processor, 12 cores available
2020-12-12 21:19:18.311 T:7836  NOTICE: Desktop Resolution: 1280x800 32Bit at 32Hz
...
2020-12-12 21:19:18.400 T:7836   DEBUG: DX:eviceResources::HandleOutputChange: selected AMD Radeon RX 6800 adapter.
2020-12-12 21:19:18.400 T:7836   DEBUG: CWinSystemWin32DX::InitHooks: Hooking into UserModeDriver on device .
2020-12-12 21:19:18.400 T:7836   DEBUG: CWinSystemWin32DX::InitHooks: error open registry key with error 2.
2020-12-12 21:19:18.402 T:7836   DEBUG: DX:eviceResources::CreateDeviceResources: creating DirectX 11 device.
2020-12-12 21:19:18.422 T:7836   DEBUG: DX:eviceResources::CreateDeviceResources: device is created on adapter 'AMD Radeon RX 6800' with feature level b100.
```

### Screenshots 
Here are some links or screenshots to help explain the problem:
I also compiled Freetype / freetype demo (ftview) from source to see if I could find a common issue with Freetype and the AMD GPU itself.  Below is a screenshot of ftview showing the Kodi's arial.ttf font, with no noted corrupt characters:
<img width="641" alt="Screen Shot 2021-07-30 at 1 13 57 PM" src="https://user-images.githubusercontent.com/12554283/127707643-9960d233-0a7f-4254-8973-cc76358ac7e0.png">

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
Links to the issue in Kodi Forums:
https://forum.kodi.tv/showthread.php?tid=359715
https://forum.kodi.tv/showthread.php?tid=359105

Links to the issue on the AMD forums:
https://community.amd.com/t5/graphics/radeon-rx-6900-xt-and-kodi-compatibility/td-p/436372

Additional notes are that using the DXVK Transitional Layer (Vulkan) fixes the issue (not sure if this points to the driver or not) .  However, this breaks video player capability in Kodi, so it's not a viable workaround.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:  v18.9 or newer (up to v20 Alpha as of 07/30/21).

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ariael** [comment]
I have exactly same problem on 6800XT...
Strange fact - i try use Nvidia 1080Ti back (previous card) - and same problem looks had Nvidia too. Something strange happens...

But i found on internet previous reported same problem on other card, Nvidia or AMD, without similar mix card brand.

**Comment by luca-iodice** [comment]
same problem here with an rx 6600xt

**Comment by zach-morris** [comment]
@simkin,

Great idea.  I tried that as a workaround:  Editing the strings.po file and putting spaces, empty characters, etc to see if the problem would go away.  I wasn't unfortunately able to find a blank/empty/small character that would remove the issue.  The problem persists if for example you just append a space to every string.

**Comment by NickFurlo** [comment]
Same problem here on AMD RX 6700 XT with current drivers and AMD Adrenaline. The worst part is that this issue affects subtitles as well which hurts accessibility.

**Comment by thexai** [comment]
Test build (v20) with fix/workaround:
https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220416-3b80f9ba-fix-font-AMD-x64.exe

**Comment by thexai** [comment]
New build with better fix:
https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220417-ab616756-fix-font-AMD-x64.exe

(the one before was a dirty workaround this is a true fix)

**Comment by ariael** [comment]
Fix looks working... Beware - fix is Alpha Kodi 20!

**Comment by Banteel** [comment]
Am having the same issue with AMD 6750 XT I installed the other day. Good to hear that there may be a possible fix in v20.

**Comment by DALEcz** [comment]
I also have this issue - on latest WIN11 update and AMD 680M iGPU graphic.
Any update? The build with a fix is no longer available... thx

**Comment by mmortal03** [comment]
> I also have this issue - on latest WIN11 update and AMD 680M iGPU graphic. Any update? The build with a fix is no longer available... thx

It looks like the fix was merged into master shortly afterwards back in April, so you should test the latest master from the following and confirm whether it's fixed for you: https://mirrors.kodi.tv/nightlies/windows/win64/master/

**Comment by DALEcz** [comment]
> It looks like the fix was merged into master shortly afterwards back in April, so you should test the latest master from the following and confirm whether it's fixed for you: https://mirrors.kodi.tv/nightlies/windows/win64/master/

You are right! It seems it is fixed and everything is working (it even took the settings from my previous installation)! I will test it more tonight.
(Btw. if I uninstall the previous version now, I will most likely lose the settings in both versions right? I did not uninstall the orig. version before installing the nightly one...)

**Comment by mmortal03** [comment]
I believe it installs to the same place by default, so your previous version was overwritten, while keeping settings. I don't remember what happens if you uninstall it, whether it gives you the option to leave the settings files in place or not. If it were me, I I wouldn't uninstall, I'd just continue using the master as long as you don't notice any new bugs.

**Comment by DALEcz** [comment]
Actually, I installed it into a separate folder so that's why I was surprised it used the previous settings (including addons etc.).
But yeah, I think you are right - I will just leave it as it is and use the working, nightly, version. Thanks!
