### ISSUE TITLE
Kodi 18.9 running on Pi4 crashes when it is connected to a HDMI connector of a Philips SmartTV 

### ISSUE THREAD

**Issue by cmoulliard** [xbmc/xbmc#20016]
### Describe the bug

When I plug my Pi4 box running LibreElec + Kodi on the HDMI port of a Smart TV - Philips, then the TV reports `no signal` even if it recognises that the device connected is `Kodi` (= Kodi name appears next to the source).  I attached to this ticket the kodi.log generated using `pastekodi` bash script like also the kodi crash log file 

The HDMI config `/flash/config.txt` defined and reported within the log is 
```
gpu_mem=320

force_turbo=0
hdmi_ignore_cec_init=1

[all]
include distroconfig.txt

hdmi_group=0:1
hdmi_enable_4kp60=0:1
```

## Expected Behavior
HDMI should work between the Pi4 box and the TV display

## Actual Behavior
No HDMI signal is reported by the TV

### Debuglog

The debuglog can be found here: 
- http://ix.io/3uS0
- https://pastebin.com/X1fGuNTk

### Screenshots 

![1627984547965](https://user-images.githubusercontent.com/463790/128000001-9458b049-356a-4f26-aad5-984c2f0b2274.jpg)
![1627984537866](https://user-images.githubusercontent.com/463790/128000018-26753f65-d834-4ab1-95c5-ba2c423d5775.jpg)
![1627984528979](https://user-images.githubusercontent.com/463790/128000036-50894bf8-f69a-495e-8a87-b82bf67323ad.jpg)

### Your Environment
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: `Running on LibreELEC (official): 9.2.6, kernel: Linux ARM 32-bit version 4.19.127`
 - Kodi version: `18.9 (18.9.0) Git:leia_pi4_18.9-Leia`

**Comment by popcornmix** [comment]
I think posting on the [LibreELEC forum](forum.libreelec.tv/) will have better luck as this is likely to be a Pi/LE specific issue, rather than a generic kodi issue.

**Comment by cmoulliard** [comment]
Thanks. I did it - https://forum.libreelec.tv/thread/24315-kodi-18-9-running-on-pi4-crashes-when-it-is-connected-to-a-hdmi-connector-of-a-p/. 

Based on your response, I suppose that you dont expect a issue with kodi even if it crashes on Pi4/EL ? @popcornmix

**Comment by enen92** [comment]
Closing as confirmed fixed on the above thread (adapter problem)
