### ISSUE TITLE
Playback crashes while playing from NFS

### ISSUE THREAD

**Issue by tinzarian** [xbmc/xbmc#20011]
### Describe the bug
Here is a clear and concise description of what the problem is:
Using a Nvidia Shield Pro (2019), files are on an NFS share on a Synology NAS. While playing files from the NFS-share on the NAS at random times play will stop. The Player Debug Info will show a stable cache size until the error happens. Then the cahe starts going down. The crash occurs when it reaches 0.
After this the files are not accesible for a while. Restarting Kodi or waiting several minutes restores access.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
The Cache remains full and the video continues playing

## Actual Behavior
Playback stops and the files are (temporarily) unavailable

### To Reproduce

1. Play a file from an NFS share
2. Wait until this happens
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/amibepogaj.kodi

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 9 (Nvidia Shield Experience 8.2.3)
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Hi and thanks for your report. 

Could you please let us know how your NVidia Shield is connected? Are you using WiFi or an ethernet connection?

**Comment by tinzarian** [comment]
It's on wifi. I have tested on ethernet and see the same behaviour.

**Comment by wsnipex** [comment]
please try with a lower cache size, e.g. 100MB.
and play around with those advancedsettings:
`  <network>
    <nfstimeout>10</nfstimeout>
    <nfsretries>-3</nfsretries>
  </network>
`

**Comment by arnova** [comment]
Looking at the number of the network issues with the nVidia shield, something must be seriously wrong with the network stack on the platform....

**Comment by wsnipex** [comment]
fwiw, NFS works fine for me on the shield, but I'm using ethernet

**Comment by fuzzard** [comment]
anecdotally nfs is working for me on a 2019 pro via wifi. Ive got some advanced settings cache entries added, but nothing crazy

**Comment by a1rwulf** [comment]
Same here I have the shield tube and also no nfs issues that I'm aware of.

**Comment by HitcherUK** [comment]
Pro here as well with no cache settings and no problems over ethernet.

**Comment by tinzarian** [comment]
> Looking at the number of the network issues with the nVidia shield, something must be seriously wrong with the network stack on the platform....

It looks like you're right. I attached a wireless bridge to ethernet port of the shield and so far it has stalled, there's just the odd skipped frame.
I don't know what the issue was when I tested a wired connection before, maybe just coincidence.

I'll leave it like this until nvidia fixes the wireless stack and will close the issue for now.
