### ISSUE TITLE
Cache size doens't match advancedsettings.xml

### ISSUE THREAD

**Issue by tinzarian** [xbmc/xbmc#20012]
### Describe the bug
Here is a clear and concise description of what the problem is:

The cache doesn't fill up to the specified size. Memory size is set in advancedsettings.xml to 512MB, however Debug Player info only shows the cache going up to about 240MB, then slowly decreasing 10 around 185 MB where it will stay until towards the end of the file

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The size of actual cache is expected to be equal to the size set in advancedstettings.xml

## Actual Behavior

It is less than half of that amount

### To Reproduce

1. Set memory size to 524288000 in advancedsettings.xml
2. Play a video file
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/amibepogaj.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment]
That's correct: What is displayed in Kodi is only the "forward"-part of the cache-buffer. But under the hood Kodi uses "double" buffering and there's also a "back buffer". This all adds up to what you're experiencing. So it's all perfectly behaving as designed.

**Comment by tinzarian** [comment]
Ah, thanks for the clarification. One additional question, though. the wiki states Kodi uses three times the amount of memory that is specified in the settings, why is that?

**Comment by arnova** [comment]
Not sure, to be honest. I wonder if this is still correct: That information has been there for ages and probably was never updated...
