### ISSUE TITLE
[NFO] feature request: read .kodi besides .nfo

### ISSUE THREAD

**Issue by evert-mouw** [xbmc/xbmc#20023]
_feature request_

Currently I've loads of .NFO files lingering around on my disk; many of them contain ASCII art and all of them are textfiles. The .nfo file extension is in use for decades already, so I'm not totally sure why Kodi uses the same file extension for XML formatted files. I love the approach taken by Kodi to store media information in a simple file, so maybe, as a workaround, this could work?

1. Detect both .nfo and .kodi files with the same filename as the video file.
2. If a .kodi file is present, try to use this file; read XML tags; on success, stop.
3. If no .kodi file is present or readable, try the .nfo file as next file.

Even better would be to show the ASCII art inside Kodi but that's another topic I guess ;-)
Also instead of .kodi one could use .xml or maybe .meta.

Background:
http://www.roysac.com/roy-sac_styles_of_underground_text_art.html
https://kodi.wiki/view/NFO_files

**Comment by KarellenX** [comment]
@evert-mouw 
We don't accept feature requests here, only bug reports.

Please post your feature request on the forum, but advance notice that this is not something any developer will be interested in.

- NFO is an abbreviation of "iNFOrmation". The piracy scene does not have exclusive access to this extension.
- Kodi has also been using nfo files for decades.
- Changing the extension of Kodi nfo files will not be considered
- Importing ASCII art will never happen.
- Reading 3rd party nfo files designed for other uses, but just happen to have an nfo extension, is not possible. Who knows what data and format those files are in.

Your request is closed.

**Comment by evert-mouw** [comment]
Thank you for your hostile fucked-up response. Back to facts. First NFO file used in 1990, Kodi dev started in 2002, twelve years later.

https://en.wikipedia.org/wiki/.nfo

**Comment by KarellenX** [comment]
There was nothing hostile about my response. I just laid out the facts for you.

But take this any way you want as I won't deal with you anymore. 
You want the features?? Then start coding.
