### ISSUE TITLE
Mal Function

### ISSUE THREAD

**Issue by GHenrique14** [xbmc/xbmc#20030]
## Bug report
Here is a clear and concise description of what the problem is:
My Kodi 19.1 doesn't work properly. When I try to open it, the screen is filled with the Kodi symbol (This is normal) and the image just like that.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
After the Kodi symbol appears in full screen, I should open the Start Menu, where I would have all my addons

## Actual Behavior
When trying to open, the app freezes and only the Kodi symbol appears. After a few minutes I get the message "Malfunction. An error caused the application not to work properly."

## Possible Fix
I've already tried restarting the app and the device, unfortunately it didn't work

### To Reproduce

1. Turn on the notebook
2. Open Kodi
3. Error opening

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:
![WhatsApp Image 2021-08-09 at 16 45 07](https://user-images.githubusercontent.com/88681960/128765592-c6b3a101-5acc-42bf-9ab9-ed5738ab7d2a.jpeg)
![WhatsApp Image 2021-08-09 at 16 40 09](https://user-images.githubusercontent.com/88681960/128765610-9ab98092-fe06-4a6c-8f2c-398284c8afc6.jpeg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 7 Home
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Best to start post your question on the forum. Your issue looks like something related to your setup, not a general Kodi bug.
