### ISSUE TITLE
Turning movie collections on is slowing down showing other covers without a movie collection

### ISSUE THREAD

**Issue by Vergil365** [xbmc/xbmc#20038]
If i turn on movie collection and enter my movie libary other covers without a movie collection need 3-4 seconds to appear.
If movie collection is turned off all covers of the movie are shown within a second.
Is this normal behavoir or could it be fixed somehow?

**Comment by KarellenX** [comment]
@Vergil365 

Please head to the Kodi forum for support. Post in the forum for whichever operating system you are using..

Tell us which skin you are using and provide a debug log that captures the problem

This issue will be closed.
