### ISSUE TITLE
Kodi doesn't connect over SFTP when the host's SSH key has changed

### ISSUE THREAD

**Issue by ashwinterminator** [xbmc/xbmc#20032]
### Describe the bug
Here is a clear and concise description of what the problem is:

I earlier ran Raspberry Pi OS on my Raspberry Pi and set up an SFTP server on it. Kodi was able to connect to this without any issues.

Yesterday, I installed Ubuntu Mate on the Pi (hence the SSH host key had changed) and set up an SFTP server as well. I was able to connect to it through Windows Shell and FileZilla but Kodi would not. The path, IP, port, username, password, all of it was the same.

The difference being, while Windows Shell and FileZilla warned me that the host's key had changed and allowed me to connect, Kodi didn't tell me any such thing, it just failed.

But once I cleared the known hosts file on Windows and Android, it connected just as expected.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should either,
1. Warn me the host's key has changed and allow me to continue
2. Or don't bother telling me the host's key has changed, just continue to connect

## Actual Behavior

Kodi doesn't tell me what is wrong or even try to fix it on its own. It just fails to connect.

## Possible Fix

Clearing the known hosts file resolves the issue and allows Kodi to connect.

### To Reproduce

1. Install Kodi on a client machine
2. Connect via SFTP to a host
3. Change the SSH key on the host
4. Attempt to connect to the host via Kodi again

### Debuglog

The debuglog can be found here:

https://pastebin.com/YJZWts7i

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android - Android 9, Windows - Windows 10 Home 64 Bit Build 19043
 - Kodi version: Android - 19.1, Windows - 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Hi 

Thanks for your report. 

Improving that would be seen as a feature request. Those feature requests should be submitted to the forums at the specific subforum we have for that:

https://forum.kodi.tv/forumdisplay.php?fid=9

Create a proper feature request and also provide a "debuglog". The log you provided isn't a debuglog. Maybe it's already in there. 

And before you suggest it any further:

> Or don't bother telling me the host's key has changed, just continue to connect

I guess that won't happen at all as a changing hostkey for a machine and connecting to it without a warning is a security risk. I have to admit that Kodi isn't made for "security". But we also shouldn't ignore everything. In general I guess it can be done as you can do something similar while using `ssh` or `scp` on linux with the `-o StrictHostKeyChecking=no` option. But that's not the default and it shouldn't be.

**Comment by koroki** [comment]
Thanks to the guy that report the error before. I waste 1 hour to know which error I have...
At least, the addon of SFT could be more explicit about the problem...
