### ISSUE TITLE
concurrent.futures import error

### ISSUE THREAD

**Issue by zach-morris** [xbmc/xbmc#20031]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm attempting to use the standard python library [concurrent.futures](https://docs.python.org/3/library/concurrent.futures.html) (standard since py 3.2)

In my addon, I include the standard import call:
```
from concurrent.futures import ThreadPoolExecutor
```
which works as expected.  When I include the import call:
```
from concurrent.futures import ProcessPoolExecutor
```

The addon errors out and the debug log shows:
```
Error Type: <class 'ModuleNotFoundError'>
Error Contents: No module named '_multiprocessing'
...
File "/Applications/Kodi.app/Contents/Libraries/lib/python3.8/multiprocessing/connection.py", line 21, in <module>
import _multiprocessing
ModuleNotFoundError: No module named '_multiprocessing'
->End of Python script error report<--
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

```from concurrent.futures import ProcessPoolExecutor``` does not fail

## Actual Behavior

```from concurrent.futures import ProcessPoolExecutor``` fails

## Possible Fix

According to Fuzzard, likely a build issue.

Edit:  After some additional testing, I also tried the following import:
```
from multiprocessing import Pool
```
and get the following error:
```
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770
```

Which points to [this issue](https://bugs.python.org/issue3770).  So possibly there's an issue with HAVE_SEM_OPEN

### To Reproduce

1.  Include the line  ```from concurrent.futures import ProcessPoolExecutor```  in a test addon.py file

Edit:
Here's a test addon to reproduce:
[plugin.program.concurrent_futures.zip](https://github.com/xbmc/xbmc/files/6977877/plugin.program.concurrent_futures.zip)

### Debuglog

The debuglog can be found here:
```
INFO <general>: Starting Kodi (19.0 (19.0.0) Git:20210218-f44fdfbf67). Platform: OS X x86 64-bit
INFO <general>: Using Release Kodi x64
INFO <general>: Kodi compiled 2021-02-18 by Clang 10.0.1 (clang-1001.0.46.4) for OS X x86 64-bit version 10.13 (101300)
INFO <general>: Running on Apple Inc. MacBookPro12,1 with OS X 10.14.6, kernel: Darwin x86 64-bit version 18.7.0

...

Error Type: <class 'ModuleNotFoundError'>
Error Contents: No module named '_multiprocessing'
...
File "/Applications/Kodi.app/Contents/Libraries/lib/python3.8/multiprocessing/connection.py", line 21, in <module>
import _multiprocessing
ModuleNotFoundError: No module named '_multiprocessing'
->End of Python script error report<--
```

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

[Forum post](https://forum.kodi.tv/showthread.php?tid=363941&pid=3053991#pid3053991)
I'll note that I only tested this on OSX, not other Operating Systems, so I'm unsure if this failure is specific to OSX, or if the error occurs in other OS's

I'll also note that both of these import calls just in the python 3 installation on my computer (outside of Kodi) does not result in the errors and the import works, so I doubt it's an issue with the OS type.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [X] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:  OS X x86 64-bit version 10.13 
 - Kodi version: 19.0.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Give the following build a try when you have some time and let me know how it goes

http://mirrors.kodi.tv/test-builds/osx/x86_64/kodi-20210812-2b5fe9e9-python_multiproc-x86_64.dmg

**Comment by zach-morris** [comment]
Thanks, thats closer.  The import works, but now when I actually try to implement a ProcessPoolExecutor i get an error.  Here's my example:
```
print('Import test')
from concurrent.futures import ProcessPoolExecutor
print('ProcessPoolExecutor Test')
executor = ProcessPoolExecutor()
futures=[executor.submit(print(x),x) for x in range(4)]
futures_results = [f.result() for f in futures]
print(futures_results)
print('Done')
```

Results in:
```
2021-08-12 11:32:42.205 T:5972369   DEBUG <general>: Import test
2021-08-12 11:32:42.225 T:5972369   DEBUG <general>: ProcessPoolExecutor Test
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'ModuleNotFoundError'>
Error Contents: No module named '_posixshmem'
...
File "/Applications/Kodi_Test.app/Contents/Libraries/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/Applications/Kodi_Test.app/Contents/Libraries/lib/python3.8/multiprocessing/synchronize.py", line 79, in __init__
    from .resource_tracker import register
  File "/Applications/Kodi_Test.app/Contents/Libraries/lib/python3.8/multiprocessing/resource_tracker.py", line 38, in <module>
    import _posixshmem
ModuleNotFoundError: No module named '_posixshmem'
```

Outside of Kodi, in my external python installation, it results in:
```
Import test
ProcessPoolExecutor Test
0
1
2
3
```

**Comment by fuzzard** [comment]
This is why I ask for a demo add-on of use. I'll look into it when I have time.

**Comment by zach-morris** [comment]
OK, i'll generate a quick example

**Comment by zach-morris** [comment]
Here's a test addon
[plugin.program.concurrent_futures.zip](https://github.com/xbmc/xbmc/files/6977877/plugin.program.concurrent_futures.zip)

**Comment by fuzzard** [comment]
http://mirrors.kodi.tv/test-builds/osx/x86_64/kodi-20210813-7547bc22-python_multiproc-x86_64.dmg

Theres a couple caveats though.

First, android does not support the posixshmem module, you will get the following exception. Nothing we can do about that, the android platform does not support SHM_OPEN and SHM_UNLINK

```
2021-08-13 09:33:55.414 T:18019   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'ImportError'>
Error Contents: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
Traceback (most recent call last):
  File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'sem_unlink' from '_multiprocessing' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.concurrent_futures/addon.py", line 37, in <module>
    test_concurrent_futures(sys.argv)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.concurrent_futures/addon.py", line 29, in test_concurrent_futures
    executor = ProcessPoolExecutor(max_workers=4)
  File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/concurrent/futures/process.py", line 555, in __init__
    self._call_queue = _SafeQueue(
  File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
-->End of Python script error report<--
```

Secondly, when running your test addon, it spawned new instances of the kodi app (5 or 6). Im guessing thats not your expected behaviour, so good luck on whether its even usable when done via an embedded python implementation.

**Comment by zach-morris** [comment]
Well, thanks for tracking all that down.  I wasn't aware that Android didn't support multiprocessing (I did test the multithreading on several OS's and that seems to work like a charm).
Given all that work you did, I doubt I'd end up using it if it wasn't platform agnostic.
