### ISSUE TITLE
KDE Compositor breaks on any video playback

### ISSUE THREAD

**Issue by tetoNidan** [xbmc/xbmc#20042]
### Describe the bug
Here is a clear and concise description of what the problem is:

Composition breaks using Kodi. This is consistent for the last 6 months. Kodi breaks KDE compositor on any/every video playback.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect the compositor to not be broken by any application.

## Actual Behavior

Compositor breaks on video playback.

## Possible Fix

None! I have been trying everything. Every time you play a video you have to either change compositor settings, restart kwin or change nvidia resolution to a different resolution and back again.

### To Reproduce

1. start video playback.

### Debuglog

The debuglog can be found here:

I will not be making a account @ pastebin or any other 3rd party site. You might want to build an error reporting section in settings that will generate the necessary log report you need as having to edit a xml file sitting on my knees 10 inches from a 30 something inch tv is a nightmare. No one wants to have to create a github account then a pastebin or any other 3rd party just to report a bug!

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ x ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP
 
OS: Manjaro Linux x86_64 
Kernel: 5.4.138
DE: Plasma 5.22.4 
WM: KWin
PU: NVIDIA GeForce GT 560M

 - Operating system version/name:
 - Kodi version:

Always the latest version. I use Manjaro. I think it's Matrix  or whatnot

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HitcherUK** [comment]
You don't need to make an account to upload a debug log. And you shouldn't be editing it either.

https://paste.kodi.tv/

**Comment by DaVukovic** [comment]
No debuglog, no issue ;)

And as there's no answer anymore, let's close this one
