### ISSUE TITLE
Getting crashes randomly

### ISSUE THREAD

**Issue by elgatito** [xbmc/xbmc#20057]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello. 
Was trying to find the issue like mine, but with no luck.

I am running Kodi 19 on several devices with Coreelec 19. 
Since migrating to Kodi 19 I'm getting crashes from time to time. 
I have tried to downgrade to 19.0 or upgrade to nightly few weeks ago, but it did not help me.

So it happens without any visible logic, sometimes when watching something. 
Sometimes when Kodi is in idle state (not watching anything or touching the device).

Here is the example from one of the devices:
```
-rw-r--r--    1 root     root       2680776 Aug 18 00:26 kodi_crashlog_20210818002644.log
-rw-r--r--    1 root     root       1265516 Aug 18 02:53 kodi_crashlog_20210818025318.log
-rw-r--r--    1 root     root       1565234 Aug 18 06:04 kodi_crashlog_20210818060453.log
-rw-r--r--    1 root     root       1183818 Aug 18 08:21 kodi_crashlog_20210818082127.log
-rw-r--r--    1 root     root       1213579 Aug 18 10:43 kodi_crashlog_20210818104256.log
-rw-r--r--    1 root     root        965780 Aug 18 12:24 kodi_crashlog_20210818122454.log
-rw-r--r--    1 root     root       2022211 Aug 18 15:47 kodi_crashlog_20210818154709.log
-rw-r--r--    1 root     root       1341584 Aug 18 18:24 kodi_crashlog_20210818182415.log
-rw-r--r--    1 root     root        245177 Aug 18 18:31 kodi_crashlog_20210818183126.log
-rw-r--r--    1 root     root       1503175 Aug 18 21:48 kodi_crashlog_20210818214844.log
```

You can see how often it happens.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### Debuglog

The debuglog can be found here:

This error is very rate:
https://paste.ubuntu.com/p/NH7WqvbBNB/

This error happens most of time:
https://paste.ubuntu.com/p/4B6BRYVsXP/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Don't know. I have a feeling it is related to library updates and jsonrpc (from crashlogs).

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.0-19.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by vpeter4** [comment]
What are you doing with so many JSON requests? Enable Kodi DEBUG log and upload the file.

**Comment by elgatito** [comment]
@vpeter4 

Here is another log file, I guess debug was enabled before the crash in it. 
[kodi_crashlog_20210819194212_1.log](https://github.com/xbmc/xbmc/files/7017274/kodi_crashlog_20210819194212_1.log)

> What are you doing with so many JSON requests? 

I have pretty big library in Kodi and tmdb scraper is doing updates from time to time. 
On Kodi 18 I can't recall any crashes like that.

**Comment by vpeter4** [comment]
Looks like some bug in JSON code.

Until you reproduce the issue on "clean" Kodi (and not with CoreELEC) you will not get much help here.

**Comment by elgatito** [comment]
@vpeter4 By "clean Kodi" you mean Windows or Linux (regular one) based binary?

**Comment by elgatito** [comment]
All log files look similar, message about disconnected json connection and that is it.
[kodi_crashlog_20210820082748_1.log](https://github.com/xbmc/xbmc/files/7021869/kodi_crashlog_20210820082748_1.log)

I believe connections are caused by `xbmc.executeJSONRPC`, but imho, it should not lead to crashes, even if there are lot of such calls.

**Comment by vpeter4** [comment]
Clean: on Windows or any Linux.

**Comment by dineshalphaque** [comment]
An update.

The intermittent crashes do not happen on Windows 10 21H1 with Kodi 19.3 and Elementum 0.1.83. This installation has been running without a crash for 35 hours, with the same library movies/shows from the above referenced OSMC boxen. In the same period, the OSMC has had two Kodi crashes.

All Elementum settings are default with Trakt synchronization turned on.

It's possible that these intermittent crashes only happen on Kodi on top of Linux.
