### ISSUE TITLE
add support for grouping livetv recordings by title and within the title group by season. the main page would be grouped by date but the grouped by season page would be sorted by episode

### ISSUE THREAD

**Issue by liam8888999** [xbmc/xbmc#20063]
### Describe the bug
Here is a clear and concise description of what the problem is:

can't sort by episode number or group by season

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

open the live tv recordings page. there should be an option to group recordings by title and sort by date it recorded which works. 
however you should also be able to group the contents of the folders into seasons and sort each season by episode number

## Actual Behavior

can only group by show name and not season number within show name
can sort show name page by date but can't sort contents by episode number

### To Reproduce

1.  open recordings
2. sort recordings
3. group recordings

### Your Environment
Used Operating system:

 - [d ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ d] Linux
 - [d ] OSX
 - [d ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
This is a feature request, not a bug. For feature requests, please use the Kodi forum. Thanks you.
