### ISSUE TITLE
The timeline isn't displayed when pausing a video with JSON-RPC

### ISSUE THREAD

**Issue by regseb** [xbmc/xbmc#20078]
### Describe the bug
Here is a clear and concise description of what the problem is:

The timeline isn't displayed when pausing a video with [JSON-RPC](https://kodi.wiki/view/JSON-RPC_API/v12#Player.PlayPause). The timeline is displayed when I pause with my TV remote (and HDMI-CEC):
![pause](https://user-images.githubusercontent.com/1262990/130654707-645613c0-5580-4368-8e75-c16b29b05d0d.png)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When you pause with JSON-RPC, the timeline should be displayed.

## Actual Behavior

The timeline isn't displayed.

### To Reproduce

1. _Allow remote control via HTTP_ (_Settings_ / _Services_ / _Control_).
2. Play a video.
3. Execute (by changing the IP address) : `curl -d '{ "jsonrpc": "2.0", "method": "Player.PlayPause", "params": { "playerid": 1 }, "id": 1 }' -H 'Content-type: application/json' -X POST 127.0.0.1:8080/jsonrpc`
4. The timeline isn't displayed.

### Debuglog

The debuglog can be found here:
```
2021-08-24 18:46:41.375 T:8794    DEBUG <CWebserver[8080]>: request received for /jsonrpc
2021-08-24 18:46:41.379 T:480     DEBUG <general>: ------ Window Init (DialogSeekBar.xml) ------
2021-08-24 18:46:41.392 T:8789    DEBUG <general>: CDVDAudio::Pause - pausing audio stream
2021-08-24 18:46:41.394 T:480     DEBUG <general>: ------ Window Init (Custom_1109_TopBarOverlay.xml) ------
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I didn't have this problem with Kodi 18.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC (Open Source Media Center) 2021.08-1 (kernel: Linux 5.10.32-1-osmc) 
 - Kodi version:
   - Build: 19.1 (19.1.0)
   - Git: 20210715-osmc
   - Compiled: 2021-07-15
- Skin: Estuary

The bug is also with Kodi 20.0-ALPHA1 (19.90.101) on Ubuntu 20.04.3 LTS.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Confirmed

If you look at the return value after sending the mentioned command to Kodi, you will see, that you get:

`{"id":1,"jsonrpc":"2.0","result":{"speed":0}}`

So Kodi does not really "pause" the video, it sets the playback speed to "0". You will see the same behavior if you use: 

`curl -u <username>:<pw> -s -X POST http://127.0.0.1:8080/jsonrpc -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"Player.SetSpeed","params":{"playerid":1,"speed":0},"id":1}'`
