### ISSUE TITLE
KodiCat craches whenever I try to play a video ISO file

### ISSUE THREAD

**Issue by dudi72** [xbmc/xbmc#20071]
## Bug report
Here is a clear and concise description of what the problem is:
Recently, I've installed Kodicat extension on top of Kodi 19.1 on my Xiomi MIBOX4.
Everything works fine except of playing of video ISO files.
What happens is that when I try to play any ISO file, Kodi just crashes.
This didn't happen before I've installed Kcat extension.

## Expected Behavior
Kodi should open the ISO file and play the movie in it.

## Actual Behavior
Kodi crashes

## Possible Fix
I'm currently using VLC instead.

### To Reproduce
Browse to and ISO file and try to play it.

### Your Environment
Used Operating system: 
Android 

 - Operating system version/name:
 - Kodi version: 19.1

**Comment by lrusak** [comment]
No support for piracy/banned stuff.
