### ISSUE TITLE
Auto Frame Rate

### ISSUE THREAD

**Issue by cnwtttt** [xbmc/xbmc#20076]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi uses non-standard methods to modify the frame rate. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Change new way, Kodi will change frame rate in all Android device.

## Actual Behavior

Now , Google provides a way for video apps to change the frame rate.
Link: 
https://android-developers.googleblog.com/2020/04/high-refresh-rate-rendering-on-android.html
https://developer.android.com/guide/topics/media/frame-rate

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 11
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HitcherUK** [comment]
Please take feature requests to the forum.
