### ISSUE TITLE
When the directory of a TV show is deleted: the TV show isn't removed from Kodi.

### ISSUE THREAD

**Issue by regseb** [xbmc/xbmc#20079]
### Describe the bug
Here is a clear and concise description of what the problem is:

When the directory of a TV show is deleted: the TV show isn't removed from Kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When the directory of a TV show is deleted: the TV show should be removed from Kodi.

## Actual Behavior

The TV show isn't removed from Kodi.

### To Reproduce

1. Create directory _Happy.Tree.Friends_ and subdirectory _Season.01_ in a TV show source.
2. Create file _Happy.Tree.Friends.S01E01.mkv_ in _Happy.Tree.Friends/Season.01_.
3. Update TV Shows library: The TV show _Happy Tree Friends_ is added in library with _0/1_ (0 watched / 1 episode).
4. Remove directory _Happy.Tree.Friends_.
5. _Clean library_ (_Settings_ / _Media_ / _Library_): The TV show _Happy Tree Friends_ is still in library with _0/0_ (0 watched / 0 episode).

### Debuglog

The debuglog can be found here:
```
2021-08-24 19:50:04.562 T:20818    INFO <general>: CleanDatabase: Starting videodatabase cleanup ..
2021-08-24 19:50:04.975 T:20818   ERROR <general>: GetDirectory - Error getting /home/osmc/serie/Happy.Tree.Friends/Season.01/
2021-08-24 19:50:05.009 T:20818    INFO <general>: CleanDatabase: Cleaning videodatabase done. Operation took 447 ms
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I didn't have this problem with Kodi 18.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC (Open Source Media Center) 2021.08-1 (kernel: Linux 5.10.32-1-osmc) 
 - Kodi version:
   - Build: 19.1 (19.1.0)
   - Git: 20210715-osmc
   - Compiled: 2021-07-15

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HitcherUK** [comment]
This is intentional in case there are future episodes added.

To remove correctly remove a show from your TV library you should use the context menu on the item you want to remove and select 'Manage...', then 'Remove from library', and finally 'Confirm delete'.
