### ISSUE TITLE
{"jsonrpc":"2.0","method":"GUI.ActivateWindow","id":1,"params":{"window":"screensaver"}}

### ISSUE THREAD

**Issue by ictb5702** [xbmc/xbmc#20088]
## Roadmap or todo item
**Detailed Description**

### Possible Implementation

Hello everyone

The following problem has occurred to us, if we want to run the screensaver via jsonrpc ":" 2.0 "," it works, but it always takes the Black, even if another standard is defined, can you help me?

regards

Oliver

Kodi 18.9/19/19.1
LibreELEC 10.0/9.2 

### Additional context, screenshots or links
Here are some relevant links or screenshots

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by DaVukovic** [comment]
Activating the window "screensaver" will do what it will do. It will activate the window for "screensaver" which is "black" by default. "screensaver" is a window with its own window-ID and it's not the setting to activate it. 

You could have used the python built-in `ActivateScreenSaver()` which is mentioned here: 
https://kodi.wiki/view/List_of_built-in_functions#System_built-in.27s

We haven't had a JSON call, to simply activate the currently used screensaver. That's what I've added with the PR mentined above. If that gets merged, you are able to call the method via: 

`{"jsonrpc":"2.0","method":"System.ActivateScreenSaver","id":0}'`

and the screensaver you've setup at the gui will be activated.
