### ISSUE TITLE
No shared/online watched database available

### ISSUE THREAD

**Issue by hostedvideorn** [xbmc/xbmc#20097]
### Describe the bug

Every Kodi installation (latest version) is isolated to a device (PC, Android Box, Firestick, etc) and that makes it hard to track watched stuff (movies, series, etc) because the database is not shared/online.

If a series has 100 episodes it is very hard to remember what was the last episode watched when trying to watch the series using  different devices:

Example: 
I watch episode 1,2,3 of series A in my Kodi installed on my Firestick in my living room. 
Then I go continue to watch the same series in my PC in my office and watch episodes 4,5,6,7,8,9, and 10.
Then I go back to my living room to continue to watch the series but I don't remember the last episode watched because on my Firestick it shows episode 3 as the last one watched and not 10 that I watched on my PC.

## Expected Behavior

I wish everything marked as watched would be shared across devices with Kodi installed.

## Actual Behavior

Everything marked as watched belongs to each Kodi on each device (isolated)

## Possible Fix

Use an online database that would be shared across devices with Kodi installed - there would be no security risk because the database would contain only what has been watched (Series, Movies, Episode Names, etc)

### To Reproduce

Repeat what I described in my example above

**Comment by fuzzard** [comment]
This isn't a bug report. Requests can be made on the forums.
With that said, there's already multiple ways of doing this (MySQL/mariadb, via add-ons like trakt)
