### ISSUE TITLE
Version 20 alpha: Build fails with spdlog 1.9.2 and fmt 8.0.1

### ISSUE THREAD

**Issue by coffeinflash** [xbmc/xbmc#20094]
Here is a clear and concise description of what the problem is:
Building the latest code from version 20 alpha and fmt 8.0.1 and spdlog 1.9.2 fails with following errors:

`[  163s] [  0%] Building CXX object build/network/httprequesthandler/python/CMakeFiles/network_httprequesthandlers_python.dir/HTTPPythonInvoker.cpp.o
[  163s] cd "/home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/build/build/network/httprequesthandler/python" && /usr/bin/g++-10  -I"/home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1" -I"/home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/lib" -I"/home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc" -I"/home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/platform/linux" -I"/home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/cores/VideoPlayer" -I"/home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/build/build" -I"/home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/build/build/include" -I"/home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/platform/posix" -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/python3.6m -I/usr/include/samba-4.0 -I/usr/include/libxml2 -I/usr/include/ffmpeg -I"/home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/build/build/cores/RetroPlayer/messages" -I/usr/include/freetype2 -I/usr/include/fribidi -I/usr/include/lzo -I/usr/include/libdrm -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=auto -DNDEBUG -Wdouble-promotion -Wmissing-field-initializers -O3 -DNDEBUG -DTARGET_POSIX -DTARGET_LINUX -D_GNU_SOURCE -DHAVE_LINUX_UDMABUF=1 -DHAVE_LINUX_DMA_BUF=1 -DHAVE_MKOSTEMP=1 -DHAVE_LINUX_MEMFD=1 -DHAVE_STATX=1 -D__STDC_CONSTANT_MACROS -D_FILE_OFFSET_BITS=64 -DHAS_POSIX_NETWORK -DHAS_LINUX_NETWORK -DHAS_BUILTIN_SYNC_ADD_AND_FETCH=1 -DHAS_BUILTIN_SYNC_SUB_AND_FETCH=1 -DHAS_BUILTIN_SYNC_VAL_COMPARE_AND_SWAP=1 -DHAVE_INOTIFY=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_INTTYPES_H=1 -DHAS_ALSA=1 -DHAS_AVAHI=1 -DHAS_ZEROCONF=1 -DHAVE_LIBBLURAY=1 -DHAVE_LIBBLURAY_BDJ=1 -DHAVE_LIBCEC=1 -DHAS_DBUS=1 -DHAS_ISO9660PP=1 -DHAVE_LCMS2=1 -DHAS_LIRC=1 -DHAS_WEB_SERVER=1 -DHAS_WEB_INTERFACE=1 -DHAS_FILESYSTEM_NFS=1 -DHAS_NFS_SET_TIMEOUT -DHAS_AIRPLAY=1 -DHAS_PYTHON=1 -DHAS_FILESYSTEM_SMB=1 -DHAS_SNDIO=1 -DHAVE_LIBUDEV=1 -DHAVE_LIBXSLT=1 -DHAVE_LIBVA=1 -DHAS_GLX=1 -DHAVE_LIBVDPAU=1 -DFFMPEG_VER_SHA=\"4.4\" -I/usr/include/fribidi -DSPDLOG_FMT_EXTERNAL -DSPDLOG_DEBUG_ON -DSPDLOG_NO_ATOMIC_LEVELS -DSPDLOG_ENABLE_PATTERN_PADDING -DHAS_EGL=1 -DHAVE_X11=1 -DHAVE_LIBXRANDR=1 -DHAVE_HDR_OUTPUT_METADATA=1 -DHAS_GL=1 -DHAS_MARIADB=1 -DHAS_UPNP=1 -DHAS_DVD_DRIVE -DHAS_CDDA_RIPPER -DBIN_INSTALL_PATH=\"/usr/lib64/kodi\" -DINSTALL_PATH=\"/usr/share/kodi\" -std=c++17 -MD -MT build/network/httprequesthandler/python/CMakeFiles/network_httprequesthandlers_python.dir/HTTPPythonInvoker.cpp.o -MF CMakeFiles/network_httprequesthandlers_python.dir/HTTPPythonInvoker.cpp.o.d -o CMakeFiles/network_httprequesthandlers_python.dir/HTTPPythonInvoker.cpp.o -c "/home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/network/httprequesthandler/python/HTTPPythonInvoker.cpp"
[  163s] In file included from /home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/interfaces/legacy/Exception.h:12,
[  163s]                  from /home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/interfaces/legacy/Addon.h:13,
[  163s]                  from /home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/interfaces/python/PythonInvoker.h:12,
[  163s]                  from /home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/network/httprequesthandler/python/HTTPPythonInvoker.h:11,
[  163s]                  from /home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/network/httprequesthandler/python/HTTPPythonInvoker.cpp:9:
[  163s] /home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/utils/log.h:12:89: error: 'constexpr fmt::v8::basic_string_view<Char>::basic_string_view(const Char*) [with Char = char]' called in a constant expression
[  163s]    12 | #define SPDLOG_LEVEL_NAMES {"TRACE", "DEBUG", "INFO", "WARNING", "ERROR", "FATAL", "OFF"};
[  163s]       |                                                                                         ^
[  163s] In file included from /usr/include/fmt/format.h:44,
[  163s]                  from /home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/utils/StringUtils.h:37,
[  163s]                  from /home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/addons/addoninfo/AddonExtensions.h:11,
[  163s]                  from /home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/addons/addoninfo/AddonType.h:11,
[  163s]                  from /home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/addons/addoninfo/AddonInfo.h:13,
[  163s]                  from /home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/addons/IAddon.h:11,
[  163s]                  from /home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/interfaces/generic/ILanguageInvoker.h:11,
[  163s]                  from /home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/interfaces/python/PythonInvoker.h:11,
[  163s]                  from /home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/network/httprequesthandler/python/HTTPPythonInvoker.h:11,
[  163s]                  from /home/abuild/rpmbuild/BUILD/kodi-20.0~alpha1.20210831T110113~3f3dc29dfd1/xbmc/network/httprequesthandler/python/HTTPPythonInvoker.cpp:9:
[  163s] /usr/include/fmt/core.h:469:3: note: 'constexpr fmt::v8::basic_string_view<Char>::basic_string_view(const Char*) [with Char = char]' is not usable as a 'constexpr' function because:
[  163s]   469 |   basic_string_view(const Char* s) : data_(s) {
[  163s]       |   ^~~~~~~~~~~~~~~~~
[  163s] /usr/include/fmt/core.h:469:3: error: member 'fmt::v8::basic_string_view<char>::size_' must be initialized by mem-initializer in 'constexpr' constructor
[  163s] /usr/include/fmt/core.h:448:10: note: declared here
[  163s]   448 |   size_t size_;
[  163s]       |          ^~~~~`

The used spdlog is: (https://build.opensuse.org/package/show/home:Herbster0815:HTPC/spdlog)
The used fmt is: (https://build.opensuse.org/package/show/home:Herbster0815:HTPC/fmt)

The used cmake command is:
`%cmake \
    -DVERBOSE=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_EVENTCLIENTS=ON \
    -DENABLE_INTERNAL_FFMPEG=OFF \
	-DENABLE_INTERNAL_CROSSGUID=OFF \
    -DENABLE_INTERNAL_CDIO=OFF \
    -DENABLE_INTERNAL_FLATBUFFERS=OFF \
	-DENABLE_INTERNAL_FMT=OFF \
	-DENABLE_INTERNAL_FSTRCMP=OFF \
	-DENABLE_INTERNAL_RapidJSON=OFF \
    -DENABLE_INTERNAL_SPDLOG=OFF \
    -DENABLE_INTERNAL_DAV1D=OFF \
    -DENABLE_INTERNAL_UDFREAD=OFF \
    -DENABLE_INTERNAL_GTEST=OFF \
	-DENABLE_AIRTUNES=OFF \
	-DENABLE_DVDCSS=OFF \
    -DENABLE_PULSEAUDIO=OFF \
    -DENABLE_PIPEWIRE=OFF \
    -DENABLE_MYSQLCLIENT=OFF \
    -DENABLE_MARIADBCLIENT=ON \
    -DENABLE_VAAPI=ON \
    -DENABLE_VDPAU=ON \
    -DCORE_SYSTEM_NAME=linux \
    -DCORE_PLATFORM_NAME=x11 \
    -DAPP_RENDER_SYSTEM=gl \
    -DX11_RENDER_SYSTEM=gl \
    -DBUILD_SHARED_LIBS=1`

I am using OBS to build rpms for openSUSE Leap 15.3.
The complete build log can be found [here](https://build.opensuse.org/build/home:Herbster0815:HTPC/openSUSE_Leap_15.3/x86_64/kodi/_log)

## Actual Behavior
Kodi should compile using the latest versions of fmt and spdlog.

## Possible Fix
I have no deeper knowledge of C/C++-Code, so I do not know what needs to be changed here. 

### Your Environment
Used Operating system:
- openSUSE Leap 15.3 x64_64

Kodi version/name:
 - Kodi version: 20 alpha

**Comment by lrusak** [comment]
Kodi currently isn't compileable with c++17, please remove the relevant compiler flag and try again.
