### ISSUE TITLE
Kodi 19.1 but als 18.9 hang upon update of library and eats cpu

### ISSUE THREAD

**Issue by u19809** [xbmc/xbmc#20107]
### Describing the bug

Since quiet some time now I experience the problem that when I want to update my library, kodi starts scanning and
detects movies and downloads info on them but after a few of them it stops.  It just stops and the message shows 'scanning movies using The Movie Database: 0% \n Scanning for new content'
nothing happens after this. I cannot stop the scanning because then Kodi completely hangs.  I can only request a reboot.
After the reboot scanning works again for a few movies and hangs again etc.

This happens on my Linux desktop PC as well as on my kodi-dedicated librelec NUC PC.

My environment might be useful.
1. all my moves are on my NAS and accessed using NFS
2. I use mysql as a database (to share data between several devices I have installed with KODI
3. All devices are connected using physical wire (not WIFI)
I have been using kodi for some time now and I think the 17.x version did not have that problem (but My memory may fail)

perhaps related is also this
when on my desktop I want to close kodi (e.g using the X icon on the window) often kodi goes into an infinite loop eating 100% CPU.  The only solution is the kill -9 kodi.bin.  strace -f on the process shows infinite pringts of sched_yield()
[kodi.zip](https://github.com/xbmc/xbmc/files/7108933/kodi.zip)

## Expected Behavior

Well I expect scanning to continue till all updates have been detected and processed

## Actual Behavior

Well, Kodi hangs and eats CPU

### To Reproduce

1. Go to the movie library
2. request an update
3. watch it happen.

Of course, this might only be in my specific setup (see debug.log)

### Debuglog

The debuglog can be found here: (attached)

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://pasteboard.co/KiXNIyZ.png

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
 19.1 AND 18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You have banned add-ons installed. Remove those (best would be to start from scratch without that advancedsettings.xml in use as well) and if the problem exists, please get us a new debuglog. 

Please be aware, that we will close this issue in 7 days if you haven't followed our requests.

**Comment by DaVukovic** [comment]
No answer after 7 days have passed....closing
