### ISSUE TITLE
Categories bar automatically slides to the right until the end for movies and TV series

### ISSUE THREAD

**Issue by rainman74** [xbmc/xbmc#20139]
### Describe the bug
If the addon Embuary Info is installed and active, the categories bar automatically slides to the right until the end!

## Expected Behavior
Categories bar always starts at the first category

## Actual Behavior

Categories bar automatically slides to the right until the end for movies and TV series.

## Possible Fix

I suspect the shift comes about because the addon adds two new categories to the bar, which you also can't disable: In theaters, Coming soon in theaters.

That's probably where the logic of positioning gets messed up.

Update: Yes, it is the reason, I have removed the corresponding includes from Includes_Home.xml (Estuary -> script.embuary) and the positioning on the first entry in the category bar is correct again.

### To Reproduce

1. install the addon Embuary Info
2. restart Kodi
3. select movies and TV series (activate only)
4. watch the category bar, which is slipped to the right side
5. deactivate the addon Embuary Info
6. restart Kodi
7. select movies and TV series (activate only)
8. the category bar starts correctly at the first entry again

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/payorezase.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://i.imgur.com/PZmbtqk.png
https://i.imgur.com/czHdcsP.png

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android
 - Kodi version: 20 Alpha every build up to current kodi-20210912-abeca92a
 - The problem now also occurs in the latest Matrix Nightly builds (Pre 19.2), but not in 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by rainman74** [comment]
This is still a bug, both in the current 19.4 and in the Nexus nightly.

**Comment by joseluismarti** [comment]
This is still happening in Nexus beta. It's the same issue as #19727.

When the **Embuary info addon** is active, two new static items are added to the panel container. This causes that every time you enter Kodi, the category list is scrolled to the right.

Related code:
https://github.com/xbmc/xbmc/blob/f0c49f90ec433c528c0704cc829f451ee8cc2601/addons/skin.estuary/xml/Includes_Home.xml#L374
