### ISSUE TITLE
[Skin] PVR - Hide year if season and episode set

### ISSUE THREAD

**Issue by matthuisman** [xbmc/xbmc#20132]
### Describe the bug

if an epg entry has a < date >, it will be set as premier_date.
Currently, Estuary will show the year from this date next to the epg entry title.
This makes sense for movies, but bit confusing for episodes as it is next to the show name.
That would usually indicate the starting year of the show - but its actually the year of when that episode was shown.

## Possible Fix

I propose hiding the year if we have a season and episode present.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![screenshot00001](https://user-images.githubusercontent.com/6225961/132910415-6c6b1c1c-daee-4aab-b92c-78d40ea48c98.png)
![screenshot00002](https://user-images.githubusercontent.com/6225961/132910426-bb102e65-8331-4fe7-9b50-617381747a9a.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version 19
:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by phunkyfish** [comment]
This is interesting because a different PVR addon could choose to set the correct year, I.e. that of the first episode (S01E01) of a show. But in iptvsimple it is the original air date of a particular episode.

I'm now thinking maybe this should be handled in the addon and not in kodi.

**Comment by matthuisman** [comment]
is there another field that can be used?
airdate?

**Comment by phunkyfish** [comment]
> is there another field that can be used in IPTV Simple?
> eg.
> if we have season and episode, set the date as airdate
> if not, set it as premier date

Yes, makes sense. But I think we should close this issue and move the discussion to iptvsimple GitHub.
