### ISSUE TITLE
Enabling a numeric Master Lock has unintended side-effects

### ISSUE THREAD

**Issue by CursedDevelopment** [xbmc/xbmc#20143]
**Describe the bug**

Enabling a numeric Master lock (under Settings / Interface) with all its lock preferences disabled causes addons to require a lock password which is not equivalent with the configured numeric lock.
Running a video addon will repeatedly prompt for the number until the retries are used up. Then accessing any addon will permanently show the "Access denied / Password retry limit exceeded" dialog.

I don't think that addons should be restricted to begin with, but if they are, at least the correct code should be accepted.

**To Reproduce**

    Go to Settings / Interface
    Enable numeric Master Lock
    Try running a plugin (e.g. YouTube)
    Enter correct code

**Informations**

    Kodi Version: 19.1 (has been the same with 19.0 but I cannot say how far back this issue goes)
    Operating System: LibreElec nightly-20210913-619146d
    Hardware Platform: RPi4

**Additional context**

I am using the Master Lock exclusively to restrict access to certain Sources (Settings/Media/Library/Videos).
The correct code is accepted under Power Options / Enter master mode or when trying to access restricted sources.

**Comment by howie-f** [comment]
my numeric lock is set up like this:

![screenshot00000](https://user-images.githubusercontent.com/58829855/133664498-43378e46-76aa-433e-b1e2-10f8fe872952.png)

i didn't check with the Youtube plugin but `ZDF Mediathek` and had no problem.. can you post a full debug log please to see what's going on?

**Comment by CursedDevelopment** [comment]
Here's a debug log of booting the system with debug mode enabled and accessing the 6 video addons I have installed followed by the SoundCloud Music addon which works and does not get blocked: https://paste.ee/p/0KA9h

All video addons (including ZDF Mediathek) appear to be affected and cause 
`2021-09-16 22:32:54.511 T:780     ERROR <general>: MasterCode or MediaSource-code is wrong: Window with id 10025 will not be loaded! Enter a correct code!`
which pops up the  "Access denied / Password retry limit exceeded" message. I wish I could reset everything to where the addons still prompted for the code, but I cannot find where the counter is stored. Maybe that would yield a more useful log.

Other than me not having the file manager locked either, our lock preferences are identical.

**Comment by howie-f** [comment]
> I wish I could reset everything to where the addons still prompted for the code

stored in `.kodi/userdata/sources.xml` for mediasources, can be set differently from the master lock.
```
<source>
        <name>Locked MediaSource</name>
        <path pathversion="1">/mnt/media/locked/</path>
        <lockmode>1</lockmode>
        <lockcode>blablabla</lockcode>
        <badpwdcount>1</badpwdcount>
        <allowsharing>true</allowsharing>
</source>
```

master lock stored in `.kodi/userdata/profiles.xml`

but all this shouldn't affect video/audio add-ons

**Comment by howie-f** [comment]
@CursedDevelopment are you able to build LE from scratch on your own and update your RPi?
if so i could provide you with a testbuild that adds some more logging

**Comment by howie-f** [comment]
ping @CursedDevelopment .. issue disappeared aka can be closed? or do you want to try a testbuild?

**Comment by CursedDevelopment** [comment]
I cannot currently build LE from scratch, but I could install a test build.

However, I think I could narrowed the problem down enough that this might not be necessary. When accessing a video plugin and the second video source within sources.xml happens to be locked (order can be differ from Kodi UI), it will ask for its password without the user knowing what it's even trying to unlock. Every other lock on media folder does not appear to matter.

I was also able to reproduce this with a fresh Kodi installation (nightly master) on Windows, by enabling a numeric master lock, adding two media sources and locking the second one (with a numeric password). However I doubt the type of password even matters.

The same also happens for music addons, except for them it's the second music source that has to be locked.

**Comment by howie-f** [comment]
thanks for going to the bottom of it. here's a win64 testbuild for you
https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20210928-5a0d41fd-pluginlockfix-master-x64.exe

i'm not quite sure yet if this is the correct way to fix it, but would be happy for some feedback. will do some testing on my own too

**Comment by CursedDevelopment** [comment]
The patched version works great; much appreciated.

Now that I've seen where the source of the error was, I am pretty sure it was meant to simply return -1 (the default value) to bypass all the matching which doesn't currently make sense for plugins. Somehow the minus sign must have gotten lost when this construct was first introduced with the linux port. There used to be a "tuxbox" protocol that bypassed matching this way.
Fairly sure "plugin" was just a copy&paste of that which was introduced [later on](https://bazaar.launchpad.net/~vcs-imports/xbmc/upstream/revision/578/xbmc/Util.cpp#xbmc/Util.cpp). Sadly the origin of "tuxbox" goes back to the no longer existing CVS repository.

Anyway, going through the matching process will certainly work, since no source will be able to match strpath for plugin URIs, so disregarding the overhead the result is the same.

There is another exception like this now for special://skin/ which makes equally little sense, but probably won't exhibit the same problem since there are no sources for skins. Or would that be affected by picture sources?!?

**Comment by howie-f** [comment]
yes, returning `-1` was my first thought. maybe `special://skin/` should also return `-1`

then i found the while playing with it:
install my toy `ZDF Mediathek`, then configure a lock protected mediasource with `<path pathversion="1">plugin://plugin.video.zdf_de_lite</path>`. (agreed, this doesnt make much sense, i didn't even expect it to work)

you'll be asked for the code when opening the source like you would expect:
![VirtualBox_Kodi Debug_28_09_2021_12_59_52](https://user-images.githubusercontent.com/58829855/135217999-3139f95e-d1bd-4279-87a3-4260302559f2.png)

same when you open the add-on directly :)
![VirtualBox_Kodi Debug_28_09_2021_13_00_25](https://user-images.githubusercontent.com/58829855/135218127-da9fb5c9-d8e2-4954-875e-c8f3c031fc27.png)

let's see which option (overhead or non-overhead) will make it finally

**Comment by howie-f** [comment]
i've set the backport to 19.3 as we now know where the problem is and how to circumvent it.

**Comment by howie-f** [comment]
backport pushed to 19.3 and LE should pick this up in a while
