### ISSUE TITLE
PVR frequently segfault's on startup...

### ISSUE THREAD

**Issue by howie-f** [xbmc/xbmc#20145]
### Describe the bug
... when trying to set GroupName but obtaining an instance for client id 0 fails. i believe client id 0 is invalid.
it happens frequently on startup and can be fixed by removing `TV38.db` so this one gets recreated.
lasted 16 days functional until crashing and the crash is reproducable. i saved the database files.
```
-rw-r--r--  1 nexus nexus   131072 16. Sep 19:25 TV38.db        <--- this is created new and functional
-rw-r--r--  1 nexus nexus   143360 31. Aug 16:35 TV38.db.crash  <--- this is not corrupted, can be accessed via sqlite3
-rw-r--r--  1 nexus nexus   143360 16. Sep 09:07 TV38.db.crash2
```

### To Reproduce
this setup with kodi master, pvr.hts and the tvheadend server is restarted dialy.. after 16 days it crashes on startup but no idea why (ok, client id 0 invalid)

### Debuglog
https://paste.kodi.tv/gehujasove.kodi

```
2021-09-16 18:59:47.325 T:1694    DEBUG <general>: AddOnLog: pvr.hts: event id:10004823 channel:12784202 start:1631829900 stop:1631831100 title:Tagesschau vor 20 Jahren desc:
2021-09-16 18:59:47.324 T:1695    DEBUG <general>: AddOnLog: pvr.hts: receive message [eventAdd]
2021-09-16 18:59:47.326 T:1700    ERROR <general>: Skipped 73 duplicate messages..
2021-09-16 18:59:47.324 T:1700    ERROR <general>: SetGroupName: Unable to obtain instance for client id: 0
```

## Additional context
a `TV38.db.crash` database is no problem for Matrix. it doesnt crash here.
i suspect that https://github.com/xbmc/xbmc/pull/19831 introduced this.

trying a build before this merge commit (which is the merge of https://github.com/xbmc/xbmc/pull/19786) the crash doesn't happen, even though a 'disfunctional' `TV38.db` is already on the filesystem.
however updating to current master after that also works fine. not sure how long it will.

### Your Environment
Used Operating system:

 - [X] Linux

 - Operating system version/name: Debian Bullseye
 - Kodi version: current master

**Comment by ksooo** [comment]
Please provide stack traces for the crash.

**Comment by howie-f** [comment]
https://paste.kodi.tv/ulerodegew
here we go

**Comment by ksooo** [comment]
Stacks for all threads, please, not only for the crashing one.

**Comment by howie-f** [comment]
mh, not used to it `thread apply all bt`
https://paste.kodi.tv/uzaqoxoxok.kodi

**Comment by ksooo** [comment]
I will take a look as soon as I find some time for it.

**Comment by howie-f** [comment]
thanks, let me know if i should test things. fyi, `pragma integrity_check;` on a crash db just returns `ok`

**Comment by ksooo** [comment]
Can you give me access to the db files, please?

**Comment by howie-f** [comment]
transferred via slack pm
