### ISSUE TITLE
Kodi paused screen displays over Youtube fullscreen

### ISSUE THREAD

**Issue by oarking** [xbmc/xbmc#20154]
### Describe the bug
Here is a clear and concise description of what the problem is:

When Kodi is paused I cannot see the video from a Youtube video in fullscreen (Chrome). The overlay controls for Youtube show/function but Kodi's paused screen replaces the video. Stopping the show in Kodi lets the Youtube video display properly.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I pause a show in Kodi then place a full screen Chrome window in front to watch a Youtube video fullscreen.

## Actual Behavior

I see the paused screen from Kodi instead of the Youtube video.

### To Reproduce

1. Pause a show in Kodi
2. Open a Youtube video in Chrome
3. Fullscreen the Youtube video on the same monitor as Kodi

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/7192888/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Paused video:
![Screenshot 2021-09-19 132621](https://user-images.githubusercontent.com/3487755/133942125-ff0d6613-5eea-4f13-97b9-e89073eec41d.png)

What it should look like:
![Screenshot 2021-09-19 132719](https://user-images.githubusercontent.com/3487755/133942144-e634f194-c781-4abf-a1e9-49f9cb0da59e.png)

What it does look like:
![PXL_20210919_202801341 MP - Copy](https://user-images.githubusercontent.com/3487755/133942150-5143fed9-515c-42f4-b454-a9b275bf2b29.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Windows screenshot corrects the situation so I had to take a picture of the screen to show it.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 19043.1237
 - Kodi version: 19.1.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by oarking** [comment]
Additionally, when Kodi fades to dim it appears in front of any other fullscreen Chrome video on that monitor. For instance, Kodi was on the main menu and I put a non-Youtube Chrome video fullscreen on that monitor, when Kodi dimmed it flashed over the fullscreen video for about a second. Also just noticed that Kodi occasionally flashes for 1/10th of a second for no reason I can discern. I can't take a video or screenshot it because screen-recording methods prevent the issue from happening in the first place.

**Comment by thexai** [comment]
Tested with:
Windows 10 21H1 (10.0.19043.1237)
Chrome 93.0.4577.82
Nvidia driver 471.96  (RTX 2060)

And I can not reproduce this. Using Alt+Tab I can switch from Kodi windows to Chrome / Youtube all in full screen and picture is correct.

Some notes:
Windows with hardware GPU scheduling setting enabled.
Kodi render method = auto detect and DXVA2 On.
Nvidia control panel with all default settings (clean driver install).

Tested also with Kodi full screen exclusive setting and full screen window, all good in both ways.

@oarking:  
Maybe you can update the Nvidia driver with a clean install or change the Windows GPU scheduling settings to match my settings. It could also be some difference in Chrome. Check that you have the same version and try to reset the "Chrome flags" to default values.

If everything is the same it should work fine on your side too.

**Comment by oarking** [comment]
It does appear that an Nvidia clean install solves the issue. I don't know why it began the day I updated from Leia to Matrix but I'm glad it wasn't a bigger issue. Thank you.
