### ISSUE TITLE
Kodi crashes continue in Arch and Debian Linux probably due to different python versions used, Flatpak Kodi doesn't crash

### ISSUE THREAD

**Issue by cg00001** [xbmc/xbmc#20172]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After the numpy issue has been fixed that was the primary cause of crashes, I remember a Kodi dev mentioning the difference in python versions used and that seems to me the main issue for sporadic crashes in Kodi Matrix.
https://github.com/xbmc/xbmc/issues/19324#issuecomment-842019792

I checked all addons I use and no numpy was active -or it had a working workaround.
A friend had the same issues in Debian Linux, so I suggested Flatpak Kodi to him and no crashes happened after using it.
https://flathub.org/apps/details/tv.kodi.Kodi

## Actual Behavior

Crashes.

## Possible Fix

Flatpak Kodi doesn't crash -probably because it's using its own python in a container.

### To Reproduce

1. Use Kodi Matrix in Arch or Debian Linux and after a while it crashes.

### Debuglog

The debuglog can be found here:
Old log:
https://pastebin.com/KYcH0FnW

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by basilgello** [comment]
> Old log

Can you please provide new log with 19.1 ?

Also, please invite your friend with Debian, too. There can be a crash in Debian on Intel graphics, so it might be not related to Python at all…

**Comment by razzeee** [comment]
I'm pretty sure it's due to the python version. Manjaro is having the same problem.

**Comment by cgcgcgcgcg** [comment]
Tried Kodi v19.4 on Arch -Arch uses python v3.10.4-1-, same issue, crashes all the time.

**Comment by CastagnaIT** [comment]
python above v3.10.2-1 make crashes also kodi v20, this has been reported by different users

not sure that is the same, but for example on libreelec has been fixed python with this patch:
https://github.com/LibreELEC/LibreELEC.tv/pull/6345#issuecomment-1083003564
this patch is needed until to python 3.9.12

then if you can update python to 3.9.13 you should be able to figure out if this is the cause
