### ISSUE TITLE
Set position of player debug is not possible anymore after reworked debug renderer

### ISSUE THREAD

**Issue by Portisch** [xbmc/xbmc#20188]
## Bug report
Since the rework of the debug render it's not possible to change the position of the player debug infos (CRTL+SHIFT+o) anymore. Before the author popcornmix changed the position like here:
https://github.com/CoreELEC/xbmc/commit/2480d22a93c852eccc52098c7ccf2defc16b942d#diff-d769860f5b9dc10500bd74b74ca40a095d4466f242c40ac619138534026ebbd7R155

This was never be upstreamed.
### Describe the bug
Here is a clear and concise description of what the problem is:

If Kodi debug and player debug is enabled in the same time the text is displayed overlap.
Before the render rework with `posY = 200.0f` it was not overlapping:
![screenshot000](https://user-images.githubusercontent.com/3938570/134921193-9bedee7a-6c1f-438c-b44d-3e6955fb24fe.png)

After rework it's not possible to change Y coordinates (yet) anymore:
![screenshot00003](https://user-images.githubusercontent.com/3938570/134921296-0074ceb9-a6d8-4d2c-ad52-dec90c969098.png)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The two debug info should not be overlap to be able to use kodi debug switched on while using player debug.

## Possible Fix

@CastagnaIT gave the hint that after merge of #20169 a new parameter `marginVertical` become available what can be used until it's fixed properly. 

### To Reproduce

1. enable kodi debug
2. display player debug

### Screenshots 
Here are some links or screenshots to help explain the problem:

See above

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Nightly, Nexus

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Is still posible change vertical position from here:

https://github.com/xbmc/xbmc/blob/829ecd3728951ba89225f73009551fe942e342dc/xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp#L151

However this should be considered as a "feature request" and not a bug. Possibly an advanced setting could be implemented but it really doesn't seem necessary to me.

**Comment by CastagnaIT** [comment]
from what i remember from an old discussion was needed some refactor to avoid have two rendering layers type overlapping
this is more a kodi imperfection
not being a priority it remained pending for the future if someone will work on it
i am not asking to reopen it i am just providing some context
