### ISSUE TITLE
Volume stays fixed when playing movies with audio encoded as AC3

### ISSUE THREAD

**Issue by zelea2** [xbmc/xbmc#20218]
When playing AVI files I cannot adjust the audio volume anymore. It was working fine in version 18,
Other file type like MP4 or MKV do not have the fixed volume issue.

When playing AVI files,  pressing Up or Down volume buttons on my Kodi remote brings the volume icon 
on to the screen but is stays at the same level.

As workaround I have to stop the AVI video which is playing, adjust the volume and then resume the play.

### Your Environment
Used Operating system:

 - [x] Linux

 - Operating system version/name:
Debian Testing

 - Kodi version:
19.1

**Comment by DaVukovic** [comment]
debuglog is missing

**Comment by enen92** [comment]
@zelea Can't reproduce the issue. Please provide a debug log file and (if possible a sample)

**Comment by zelea2** [comment]
Kodi 19.2 behaves in the same way. This volume issue is happening for some mkv files too. 
I think I've found the common problem for these files: they all have audio encoded as AC3.

Volume _NOT_ working while playing movies encoded with:

Audio: ac3, 48000 Hz, 5.1(side), fltp, 192 kb/s (default)
Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s (default)
Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)

Volume working fine while playing movies encoded with:

Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb
Audio: aac (LC), 48000 Hz, stereo, fltp (default)
Audio: aac (LC), 48000 Hz, stereo, fltp (default)
Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 132 kb/s

The audio plays fine in all of the above cases, I just cannot adjust the volume for the first lot.

Here's  a log for a non-working movie.

**Comment by lrusak** [comment]
AC3 is a passthrough format. Do you have passthrough enabled in your kodi audio settings? You may need to be on advanced/expert mode.

When passthrough is on you cannot adjust the volume from kodi.

See: https://kodi.wiki/view/Settings/System/Audio#Audio_Passthrough
