### ISSUE TITLE
Incomplete search query string (&&1) for scraper when "se" is in filename

### ISSUE THREAD

**Issue by sikysikov** [xbmc/xbmc#20243]
### Describe the bug
When filename includes "se" the scraper query string and the buffer $$1 is incomplete. It includes only chars before "se". 

Filename: Test movie se whole name (2020).strm
Returns: ADDON::CScraper::FindMovie: Searching for 'Test movie' using scraper

Filename: Test movie whole name (2020).strm
Returns: ADDON::CScraper::FindMovie: Searching for 'Test movie whole name' using scraper

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
The query should include whole string in search query for scraper. Correct query string should be "Test movie se whole name" for filename: Test movie se whole name (2020).strm

## Actual Behavior
At the moment query string is incomplete and includes only part before "se" string in filename. 

### To Reproduce
1. Place file in folder with filename including "se": Example: Test movie se whole name (2020).strm
2. Use any Scraper to get information about the file. 
3. Try the same without "se" in filename. Example: Test movie whole name (2020).strm

### Debuglog
ADDON::CScraper::FindMovie: Searching for 'Test movie' using scraper

### Your Environment
Used Operating system:

INFO <general>: Starting Kodi (19.1 (19.1.0) Git:20210508-85e05228b4). Platform: Windows NT x86 64-bit
INFO <general>: Using Release Kodi x64
INFO <general>: Kodi compiled 2021-05-08 by MSVC 191627034 for Windows NT x86 64-bit version 10.0 (0x0A000007)
INFO <general>: Running on Windows 10 21H1, kernel: Windows NT x86 64-bit version 10.0.19043.1237
INFO <general>: FFmpeg version/source: 4.3.2-Kodi
INFO <general>: Host CPU: AMD Ryzen 7 PRO 4750U with Radeon Graphics, 16 cores available
INFO <general>: System has 32.0 GB of RAM installed
INFO <general>: Desktop Resolution: 1920x1080 32Bit at 60Hz
INFO <general>: Running with restricted rights
INFO <general>: Aero is enabled
INFO <general>: Display is not HDR capable or cannot be detected
INFO <general>: special://xbmc/ is mapped to: C:\Program Files\Kodi
INFO <general>: special://xbmcbin/ is mapped to: C:\Program Files\Kodi
INFO <general>: special://xbmcbinaddons/ is mapped to: C:\Program Files\Kodi/addons

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win10
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sikysikov** [comment]
Problem solved using cleanstrings in advancedsettings.xml:
https://kodi.wiki/view/Advancedsettings.xml#cleanstrings

**Comment by johnhorner** [comment]
How is the problem solved exactly? Do I need to edit that XML file? Will it be fixed in a new release?

Shouldn't the regular expressions include a `\b` at each end of the string so that a string like `user` doesn't match but `.se.` and `_se_` etc do match?
