### ISSUE TITLE
Provide a way to display two subtitles at the same time

### ISSUE THREAD

**Issue by domdorn** [xbmc/xbmc#20242]
As a User in a dual-language home, I need a simple way to display two subtitles from different languages at the same time. 
This functionality should be baked into the core of Kodi, so that it also can work out of the box with plugins (e.g. Netflix, Amazon Prime, etc.) or with any video file and manually added subtitles.

Use case: 
My wife and I are watching a movie through the Netflix Plugin. Nowadays, we set the audio stream to german, as she needs to learn the language, and select arabic subtitles so she can read what is not spoken clearly/she doesn't understand yet. Now the movie also has parts that are spoken in a third language, e.g. russian or chinese. Only she is able to read what the actors are saying and we have to stop all the time so she can translate the third-language parts for me. Sometimes this even ends up in a fight as its getting quite cumbersome and produces stress. 

Minimum Required functionality: 
 - Being able to select two subtitle files/languages, show one at the top and one at the bottom.
 
 Required functionality for satisfying user experience:
 - allow to define which language should be displayed at the top / bottom
 - Being able to control the subtitle-offset on a per-subtitle case (not a big problem with video platforms like netflix, but a problem where the subs have to be collected by hand and one or both are not in sync with the video)

Optional functionality:
 - Allow to specify that one or both of the subs should only display the "forced" (e.g. third language) parts. 

Current environment: 
 - Libreelec 10 (Kodi 19.1) on a Raspberry PI 4

Further references: 
 - There seems to be some prior work on this, however the code/plugins are 5 years old: 
    - https://github.com/bkiziuk/script.module.pysubs2 <- this library seems to support conversion between different subtitle formats
    - relevant cpp file? https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L2755 and maybe https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L3406 
    - forum thread 1: https://forum.kodi.tv/showthread.php?tid=198677 
    - forum thread 2: https://forum.kodi.tv/showthread.php?tid=87333 ( this one mentions that ".smi" subs already allow to contain/display two subtitle languages) 

Implementation idea?
I tried to look through the C++ code (I'm a scala programmer, so just reading, no writing cpp) and from what I got it seems it requires a second "subtitle demuxer stream" and then something that would add that to the overlay ( CDVDOverlayContainer ?) ? 
So I think in VideoPlayer.cpp rename "`m_CurrentSubtitle`" to something like "`m_CurrentPrimarySubtitle`" and duplicate that with a "`m_CurrentSecondarySubtitle`" stream? Then maybe change `VideoPlayerSubtitle` and add the second stream there as well or create a second instance of `VideoPlayerSubtitle`that handles the second stream.. then maybe its just necessary to provide the position (top/bottom) of the subtitle stream to the `DVDFactoryCodec` ?

**Comment by garbear** [comment]
Not that I have authority to comment on the topic, but my first validation was being able to display two DVD images in Kodi at the same time. And look where that got me. This could be a fun problem to solve for a Scala programmer.

**Comment by lrusak** [comment]
Please make feature requests in the forum. Thanks.

https://forum.kodi.tv/

**Comment by domdorn** [comment]
@garbear @lrusak  ok, I'll try myself on a Pull-Request, would be great if you would be willing to guide me a little on the way?
I've managed to get kodi compiling on my machine and running with CLion already

I think the required conceptional changes might
[ ] migrate subtitle management (variables in the respective classes) from a single subtitle to a "primary" and "secondary" subtitle.. or maybe to don't break existing code, just add a secondary
[ ] allow to configure where the primary and secondary subtitle should be shown (top/bottom) (I guess thats `CSettings::SETTING_SUBTITLES_ALIGN` ?)
[ ] adjust the subtitle event (not sure whats the name atm) to include a flag if the text to be shown is for the primary or secondary subtitle
[ ] adjust the overlay renderer to position the subtitle according to the flag of the event? 
[ ] ... 15 things I forgot..

**Comment by PanderMusubi** [comment]
I only found MPV to do this well at this moment. VLC is also working on it. For MPV, this is a good starting point:

    cat ~/.config/mpv/mpv.conf 
    sub-auto=fuzzy
    sid=2
    secondary-sid=1
    sub-scale=.6
    alang=en,es,de,nl,fr
