### ISSUE TITLE
No UI unless MESA_LOADER_DRIVER_OVERRIDE is set, at which point UI is laggy

### ISSUE THREAD

**Issue by Visne** [xbmc/xbmc#20280]
### Describe the bug
I'm having issues which seem somewhat related to #18245 but are still quite different. First of all, I'm on Raspbian, using Kodi from the Raspbian repo.
If I do not set MESA_LOADER_DRIVER_OVERRIDE, then Kodi starts, I can hear sounds if I tap the keyboard, but my screen is black apart from a flashing lowercase character.
If I do set MESA_LOADER_DRIVER_OVERRIDE to anything, Kodi starts up normally, and videos even play perfectly fine, but the UI is extremely laggy, where it is almost unusable.

Note that Kodi used to run fine and without lag on this Raspberry Pi 4B, but now it does not work anymore. Sadly I don't know what happened/changed between Kodi working and not working.

## Expected Behavior
Kodi should show the UI regardless of whether MESA_LOADER_DRIVER_OVERRIDE is set, and the UI should not be laggy.

## Actual Behavior
With MESA_LOADER_DRIVER_OVERRIDE set the UI is laggy, without it set the UI is not shown at all (but sound is heard).

### To Reproduce
1. `export MESA_LOADER_DRIVER_OVERRIDE=a`
2. Boot Kodi

### Debuglog

Log without MESA_LOADER_DRIVER_OVERRIDE set:
https://termbin.com/yphm7

Log with MESA_LOADER_DRIVER_OVERRIDE set to something random ("a"):
https://termbin.com/7qgi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspbian Bullseye, Linux 5.10
 - Kodi version: 18.7

**Comment by lrusak** [comment]
Can you confirm if you are using the kms or fkms driver?

You can check via dmesg or by looking at your config.txt file for the following line `dtoverlay=vc4-kms-v3d`.

Otherwise it would be helpful to for debug logging via advancedsettings.xml 

See: https://kodi.wiki/view/Log_file/Advanced

**Comment by Visne** [comment]
Okay so apparently I was wrong, with `vc4-kms-v3d` I actually DO see video normally, until I launch Kodi at which point the screen goes black and my TV says "No signal".

Here's the log for that: https://termbin.com/89ff, with `MESA_LOADER_DRIVER_OVERRIDE=a`
And I also tried it after unsetting `MESA_LOADER_DRIVER_OVERRIDE`: https://termbin.com/3rg4.

**Comment by lrusak** [comment]
> Okay so apparently I was wrong, with `vc4-kms-v3d` I actually DO see video normally, until I launch Kodi at which point the screen goes black and my TV says "No signal".
> 
> Here's the log for that: https://termbin.com/89ff, with `MESA_LOADER_DRIVER_OVERRIDE=a` And I also tried it after unsetting `MESA_LOADER_DRIVER_OVERRIDE`: https://termbin.com/3rg4.

I'm not really sure what is happening sorry. Can you try updating to Kodi v19 and see if the issues is still there?

**Comment by Visne** [comment]
> I'm not really sure what is happening sorry. Can you try updating to Kodi v19 and see if the issues is still there? 

Last time when I tried to compile v19 on RPi I ran in to some issues. Is there a recommended way to build for RPi?

**Comment by popcornmix** [comment]
> I used an official Raspberry Pi Buster image, and then manually upgraded to Bullseye. I know it's not officially supported, but I assume it should still be fine.

RPiOS consists of raspbian (debian compiled with specific flags) plus an RPi repo which replaces packages with Pi specific ones (typically ones with hardware acceleration or newer versions that are required to support our hardware. That includes mesa, drm, ffmpeg etc). As RPi hasn't released a bullseye image, you are only getting the first part of this, so I'd expect anything that uses mesa, drm, ffmpeg, etc (kodi would be a good example) to not work.

**Comment by lrusak** [comment]
@Visne check if you have the environment variables `DISPLAY` or `WAYLAND_DISPLAY` set somewhere.

See: https://github.com/xbmc/xbmc/blob/25eb3e2bd13836912821019b64ca0551882fee65/xbmc/windowing/gbm/WinSystemGbm.cpp#L42...#L49

**Comment by Visne** [comment]
> 
> 
> You need to be root or your user needs to be part of the `video`and `input` groups.
> 
> See, [https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md#42-build](https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md?rgh-link-date=2021-10-17T00%3A26%3A37Z#42-build)

Already the case:
![image](https://user-images.githubusercontent.com/39844191/137605607-99bb4f68-8abb-4b23-be1f-30c95524c9e1.png)

**Comment by Visne** [comment]
Tried running it as root just to be sure, only difference is that it turns off my TV if I press S then Enter, I assume because its not using my config.

**Comment by thorstenhirsch** [comment]
Same problem here after upgrading my RPi 2 to Debian Bullseye.

**Comment by lrusak** [comment]
I'm going to close this as this isn't a support channel. Please use the forum for support.

**Comment by Visne** [comment]
Are you sure it's not a bug?

**Comment by thorstenhirsch** [comment]
Irusak solved my problem in the forum by pointing out that Kodi requires the vc4 driver on my RPi, so I had to add the following lines in /boot/config.txt:
```
[all]
dtoverlay=vc4-kms-v3d
```
I guess they're already there in a fresh Raspbian installation, but since I upgraded my old installation to Bullseye... so yes, definitely no Kodi bug for me.
