### ISSUE TITLE
LibreElec 10.0.0 file manager does not sort folders with special chars properly

### ISSUE THREAD

**Issue by C4Plastique** [xbmc/xbmc#20321]
Hi there,

I have switched my RPI4 to LibreElec 10.0.0 and am quite confused due to file manager behavior. 
My setup is as follows:
 - RPI4 (8GB) with installed LibreElec 10.0.0, connected via cable to LAN
 - NAS server with the shared media data (folders, subfolders, files - ~200 items+), accessible via SMB, connected via cable to LAN

Simply:
- Add network place to the available sources in Settings -> Media -> Library -> Video... -> Add videos... -> Add video Source (browse) -> Add network location -- Windows network (SMB) ---> after successful adding the network location (shared folder) is displayed in sources.
- Add this newly added location to Videos..., optionally to Favorites
- Navigate to this newly added folder via file explorer (like would like to play movie)
- The structure of that location is: 
parentFolder
     |_____media_file

### Describe the bug
In the NAS server I have the structure of folders which includes sometime special character(s) on the beginning, like plus (+), dash (-), underscore (_) etc. This is so because I need to sort these folders at the beginning in the list, in folder. Other folders begin with the normal chars (A, B, c, d, E...).
The problem is that the folders which contain special chars at the beginning of its name are mixed "randomly"?? and are not sorted as expected. The folders which do not begin with the special chars are sorted correctly.
The most interesting thing is that the same worked fine in previous LibreElec 9.2.x

Of course I tried to change the sorting from the option, to change sorting from the Settings but still the folders are sorted incorrectly.

The folders are sorted correctly when I access shared folder from another place (Windows PC, Android phone...).

I was looking for similar issues related to sorting and only found this one which I do not think is the same like my issue: 
https://forum.kodi.tv/showthread.php?tid=240140 

## Expected Behavior
I would expect sorting like this (or with two plus (++) folders at the beginning of list):
+_Folder1
+_folder2
+_folder3
+_folder4
++_Folder1
++_folder2
++_Folder3
++_Folder4
folderA
folderB
folderc
folderd
folderE

## Actual Behavior
Sample of folders incorrectly sorted:
+_folder4
+_Folder1
++_folder2
++_Folder1
+_folder3
+_folder2
++_Folder3
++_Folder4
folderA
folderB
folderc
folderd
folderE

## Possible Fix
Integrate file explorer from 9.2.x ??

### Your Environment
Used Operating system: Linux based for LibreElec for RPI4
Kodi version: 10.0.0

Thanks a lot for your investigation and help!

**Comment by DaVukovic** [comment]
Could you please report this to the LibreELEC Github issue tracker?

https://github.com/LibreELEC/LibreELEC.tv/issues

If you see this only on LibreELEC and not while using Kodi on Windows, Android or Linux (LibreELEC is a bit special), then this might not be a general Kodi problem.
