### ISSUE TITLE
The recently automatically installed Kodi v19.2 crashes constantly, 19.1 was absolutely stable!

### ISSUE THREAD

**Issue by rainman74** [xbmc/xbmc#20333]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi v19.2 crashes very often now. This happens when scraping new movies or series in a larger database, or simply when you start Kodi and let it load the most recently added series.. With Kodi v19.1 everything ran smoothly.

Therefore, I have also uninstalled 19.2 and then it works again (19.1 per sideload), but then the 19.2 is constantly installed overnight again independently from the Play Store :-(

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No crashes like with Kodi v19.1.

## Actual Behavior

Random crashes, at least 3x per day and usually always when searching for new series via SMB.

## Possible Fix

It would be enough for me if you could block the automatic update to 19.2, but you can't do that on Android TV.

### To Reproduce

1. start Kodi
2. scrape a new tv series with a complete new season
3. Kodi crashes at about 70-95% (and also the scrapping takes much longer than it was the case under 19.1)

Tipp: It's not the network, nor the NAS, because with an immediate downgrade to 19.1 the same actions work successfully with the same series and also the scrapes get always to 100% and finishes.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ucimajusel.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The statement "Absolutely stable with 19.1" does not refer to the other bug that whenever the Internet is gone, the NAS stream also stops. I have posted another issue about this. This bug has nothing to do with it.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 19.2 (from Google Play Store)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Beside this issue is nearly 30 days old and there doesn't seem to be an interest from the OP, the log also contains banned add-ons. 

I'm going to close it. 

@rainman74 I'll happily re-open your issue if you paste a clean Kodi debuglog
