### ISSUE TITLE
Kodi Hanging/Freezing

### ISSUE THREAD

**Issue by n00bftw** [xbmc/xbmc#20360]
Hi, 

When i stop a video from playing and go back to the home menu, the home menu freezes and i have to wait around 10-20 seconds for it to unfreeze? Also, the freeze occurs when i go into my videos folder, so i guess it could be SMB/Share related. Furthermore, I recently took my server offline (Spinning Rust in RAID 0) and am temporarily using my main computer (NVME drive inside) to share the media to my media PC to watch content, this is when the issue started, all machines (Server, Main PC, Media PC) are connected via ethernet to the router and run Windows 10.

Update, it recently hanged for 10 seconds when going into addons menu so i have no idea what is going on.

I replicated the hang/freeze 3 different times in the menus, they occurred 'very roughly' at,

17:58:34ish
17:59:30ish
18:00:40ish

Kodi Log,
### Debuglog

https://paste.kodi.tv/efucakeqos

Running in Windows 10
Kodi Version: v19.2 (Matrix)

**Comment by a1rwulf** [comment]
Hi,
please use the template when you report issues.
Your link doesn't point to your log, please make sure to attach a working link to a debug(!) log.
See: https://kodi.wiki/view/Log_file/Easy

**Comment by n00bftw** [comment]
Thanks for taking a look, hopefully there is someone out there who can help me figure the issue out, driving me nuts.

**Comment by KarellenX** [comment]
@n00bftw 

I am closing this as you have asked the same question on the forum. Lets see what the forum reveals before trying to report this as a bug. There are  millions of users currently using Kodi without your reported issue. It is most likely an issue with your setup.
https://forum.kodi.tv/showthread.php?tid=365079

Also that log does not capture a crash at all. It shows you using the Log Uploader to upload the log. That would not be possible if it crashed.

You need to capture the crash in the log.

**Comment by n00bftw** [comment]
I never said that Kodi crashed, it just hangs, then comes back in 20 seconds or so. It doesn't crash to desktop or anything like that.
