### ISSUE TITLE
UI text error in Settings/Services/Control/SSL: Prompt incorrectly reverses server.key and server.pem

### ISSUE THREAD

**Issue by snycom** [xbmc/xbmc#20375]
### Describe the bug
Here is a clear and concise description of what the problem is:

English version of user interface Settings/Services/Control/SSL mixes up certificate and key file names "server.key" and "server.pem", leading to a misleading prompt to the user. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The server should prompt with the following (the .pem file is the certificate, not the key):
Enables SSL encryption in the webserver. Certificate special://userdata/server.pem and Key special://userdata/server.key must be created manually

## Actual Behavior

Instead, the UI prompts the user to place the key into server.pem (where the code expects the certificate).
"Enables SSL encryption in the webserver. Certificate special://userdata/server.key and Key special://userdata/server.pem must be created manually"

## Possible Fix

Looks like the string is set in the following file, around line 21218:
addons/resource.language.en_gb/resources/strings.po

### To Reproduce

1. Go to Settings->Services->Control
2. Find "Enable SSL" setting
3. The erroneous prompt to the user is under the setting above.

### Debuglog

The debuglog can be found here:
A debug log is not relevant for this issue, as the problem is only a misleading text in the interface.

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/93051405/138566712-251c3b36-136d-4bef-b706-ba4b5a125b44.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.7

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
I can confirm this issue. Please be aware, that kodi 18.7 won't receive any kind of bugfixes anymore. As languages are add-ons there could be a little chance that the fix will also find its way into Kodi 18. But if noone changes the languag add-on for Kodi 18, you won't see a fix. So please update to Kodi 19.

**Comment by DaVukovic** [comment]
I created the PR and also did a backport for Matrix 19.4

Kodi 18.x won't receive an update for this
