### ISSUE TITLE
Atmos Music: Progressbar and Duration stutter issue

### ISSUE THREAD

**Issue by HomerJau** [xbmc/xbmc#20391]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing Atmos music (audio only) in Kodi 18 and 19 (all versions) the song progressbar and duration timer both stutter badly moving forward and backward very fast during playback. This occurs on Estuary and Aeon Nox Silvo skins. When using HDMI pass-through to an AVR for Atmos decoding.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Both progressbar and duration time should flow smoothly like any other codec when played.

## Actual Behavior

Progressbar and duration jumps. Duration is showing changes in the numeric value multiple times per second. Duration should increment once per second,

### To Reproduce

1. Configure Kodi to play via HDMI Pass-through and enable that your AVR can decode TrueHD.
2. Play an (audio) song file with Atmos codec. Switch to a view showing either progressbar or duration timer.

Download sample here:
https://drive.google.com/drive/folders/1QQg3yAfZyyCRI2oPxpjqmRG_1dMQ23tD?usp=sharing

NOTE 1: Both sets of MKA and M4A files contain Atmos codecs.
NOTE2 : The Abbey Road samples will only play back with latest Kodi builds (a recent Kodi high bitrate fix):
https://github.com/xbmc/xbmc/pull/20339

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

No screen shot will show this as it needs an animation

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux (LibreEelc)
 - [ ] OSX
 - [x ] Windows
 - [ ] Windows UWP

I have personally had this issue in all Kodi versions from 18 to 19.1 using LibreElec (Intel NUCs).
I have seen reports of users with Android / NVidia Shield Kodi 19.2 . I had this issue with Kodi 18 on Windows (NUC)
I do not have this problem on Windows 19 on my PC without HDMI pass-through (i.e. Kodi decoding Atmos)

 - Operating system version/name:
 - Kodi version:
 - 19.0, 19.1, 19.2
 - 18.4, 18.5 etc

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Open again as is not fixed in Android AudioTrack RAW, only is fixed in IEC
