### ISSUE TITLE
Issues with the PlayWith() function (linux opensuse)

### ISSUE THREAD

**Issue by MetaStazz** [xbmc/xbmc#20397]
So... I have multiple issues with the `PlayWith()` function!

I set up 2 external players in `playercorefactory.xml`, MPV and VLC but I still put Kodi as default player.
In kodi context menu if I choose _"play with..."_ it work as intended.

If I'm already playing the video and I use the key to `SwitchPlayer` and choose VLC it work,
**BUT** if I choose MPV sometime it doesn't work at all, and sometime it launch mpv but crash kodi ??

Then,
I wanted to make a shortcut for that, I checked the wiki and found on the [List of built-in functions](https://kodi.wiki/view/List_of_built-in_functions#Player_built-in.27s) page:
`PlayWith() | Play the selected item with the specified player core.`
Ref in [source code](https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/builtins/PlayerBuiltins.cpp):
```
/*! \brief Start playback with a given playback core.
 *  \param params The parameters.
 *  \details params[0] = Name of playback core.
 */
static int PlayWith(const std::vector<std::string>& params)
{
  g_application.OnAction(CAction(ACTION_PLAYER_PLAY, params[0]));

  return 0;
}
```

I tried to set up a key binding in my `keyboard.xml` as follow.
```
in <global> section:
<m>PlayWith(mpv)</m>    <= I also tried with uppercase
<v>PlayWith(vlc)</v>    <= I also tried with uppercase
<s>PlayWith()</s>       <= To try if it will launch the context menu "play with..."
```
The last one doesn't do anything, while **both other key keep playing the video in kodi**.

========================================
Kodi Version: 19.2-pm153.1.1 (from Packman repo)
Opensuse Leap 15.3 - KDE plasma 5
OS version: Unix 5.3.18.59 (64bit)
Kernel version: 5.3.18-59.24-default
Window System: X11 - X.Org 1.20.3

Thanks for any help!

**Comment by DaVukovic** [comment]
I guess 22 days is enough for posting a log ;)

Closed
