### ISSUE TITLE
AC3 transcoding fails on Kodi 20

### ISSUE THREAD

**Issue by cromefire** [xbmc/xbmc#20398]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing a file that is not supported by passthrough and should be transcoded, Kodi doesn't send ac3 and does not play any audio. An internal failure seems to occur.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The unsupported format should be transcoded to ac3 and preserve surround.

## Actual Behavior

Kodi doesn't send ac3 and does not play any audio. An internal failure seems to occur.

### To Reproduce

1. Enable ac3 transcoding
2. Play a file that cannot be passed through (or has passthrough for that format disabled) and is 5.1 or higher (e.g. a DTS(-HD) file)
3. No ac3 output 

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/7413655/kodi.log)

Line 2093 and following look suspicious (sorry there's some multiple playback sessions in there, mostly unaffected ones):
```
CAEEncoderFFmpeg::Initialize - AC3 encoder ready
CActiveAE::ClearDiscardedBuffers - buffer pool deleted
CAEEncoderFFmpeg::Encode - Encoding failed
```
If you want me to enable an specific component-level logging, I'm happy to recreate it with those enabled.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Kodi 19 (tested up to 19.3) works just fine, same hardware, same files.

### Your Environment
Used Operating system:

 - [x] Android
 - [x] Windows (#20529)
 - [x] Raspberry Pi 3B+ ([forum thread](https://forum.libreelec.tv/thread/24741-librelec-nightly-dolby-digital-transcoding-bug))

 - Operating system version/name: Android TV 10 on Chromecast with Google TV (project sabrina)
 - Kodi version: 20 Nexus alpha (compiled from master)

**Comment by popcornmix** [comment]
Also seen this reported on Pi in [forum thread](https://forum.libreelec.tv/thread/24741-librelec-nightly-dolby-digital-transcoding-bug) with nightly builds.

**Comment by cromefire** [comment]
As we now have 3 totally different platforms, I think it's quite safe to assume this is not platform specific.

**Comment by tiagogaspar8** [comment]
I'll add some info to this issue as requested.

Platforms: Windows 10 and Windows 11 with the latest updates
Kodi Version: Latest master

This issue has been present for some time, I haven't reported it because I thought it would eventually be fixed because I believed it was such a "big" feature, sorry for being wrong.😅😅😅
One thing that might help, when I play a video file with transcoding enabled I see that the TV gets the information that AC-3 is being bitstreamed, but no sound comes out of it.

**Comment by cromefire** [comment]
> This issue has been present for some time

Can confirm it has been here for at least 2-3 months.

**Comment by cromefire** [comment]
Tried master after the merge of #20429, but unfortunately it wasn't successful haven't gathered any new logs yet, but I can get some if required.

**Comment by cromefire** [comment]
Seems fine again
