### ISSUE TITLE
xbox smb problem

### ISSUE THREAD

**Issue by magiclu** [xbmc/xbmc#20423]
### Describe the bug
Here is a clear and concise description of what the problem is:

xbox smb problem

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

sucessfully connect

## Actual Behavior

cam not connect

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

![MVIMG_20211030_144705](https://user-images.githubusercontent.com/3338197/139523896-a86086a9-c92c-4608-9f84-93f35a8ea5ea.jpg)
![image](https://user-images.githubusercontent.com/3338197/139523902-5d951ff6-b6ae-4c63-9061-19ab4a0a2479.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I installed the smb plugin,kodi version 19.3
kodi app can detect my computers but I can't connect sucessfully
I tested with kodi with my android phone ,smb works fine,
also windows10 computer uwp version smb also works fine

smb did not with with xbox version 18.9 for me,but after I googled a little,I just waited for the new version,but still not working

should be xbox version's problem

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name:xbox
 - Kodi version:19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Kodi on Xbox uses a binary add-on for smb. Also the add-on version is the same for 18.9 and 19.3. In other words, the problem is external and independent of Kodi version used.

**Comment by thexai** [comment]
A workaround may be use "Add network location..." dialog instead of browse directly and provide user/pass in this dialog.

SMBv3 has many security restrictions that prevents browse folders tree before authenticating.

**Comment by magiclu** [comment]
@thexai 
"Add network location..." works for 2 of my computers but not for my server computer for some reason
if i use incorrect user name and password ,another window will popup "Lock preference for smb://bbbb"
if i use correct user name and password ,i get "Unable to connect"

but windows uwp and android kodi works fine. i can use "Add network location..." with my file server
i already updated my server computer to latest windows 10 update

it is werid
but i can temporary copy file to a working computer as a work around

please tell me it is my server's problem or xbox version kodi's problem

**Comment by thexai** [comment]
You need to add the name of a shared folder that the user has access to.

i.e. in my case:

Server name: DiskStation
Shared folder: NAS

I only have a main shared folder named "NAS" and from here subfolders for each media content: movies, music, etc.

Then indicating main shared folder "NAS" I can navigate to all others folders.

In my case I can access 3 different PC's W10 / W11 and a Synology NAS via SMB without any problem.

**Comment by magiclu** [comment]
@thexai 
thanks .after doing this .it worked

you guys should still look into this.it is still a bug. because i don't need to add Shared folder for windows uwp and android kodi
also i can use smb from another two computer without add the name of a shared folder
and without your help,i have no idea what is wrong

**Comment by thexai** [comment]
We know it but in Xbox it is a matter of the SMB add-on called `vfs.smb2`

**Comment by magiclu** [comment]
@thexai 
i found the bug
my server have about 15 shared folder
i disabled some,it worked without add the name of a shared folder
then i reenabled all my shared folder. bug reappeared

**Comment by magiclu** [comment]
somewhere in the plugin hard coded a limit about 5 folder max
