### ISSUE TITLE
Kodi 19.3 Matrix Xbox - Python add-ons error's

### ISSUE THREAD

**Issue by BuzzingSniper38** [xbmc/xbmc#20421]
Kodi 19.3 Matrix
Xbox Series S

With one the latest update Kodi 19 matrix on the Xbox consoles I am unable to load any add-ons program them or anything when trying to program one it just says the wizard build name error check the log for more information there's nothing in the log redownloading app didn't help

**Comment by thexai** [comment]
It is a known issue. See: https://forum.kodi.tv/announcements.php?aid=6

At the moment there is a workaround: 
https://forum.kodi.tv/showthread.php?tid=365157&pid=3067830#pid3067830
