### ISSUE TITLE
mouse cursor mapped incorrectly in macOS Monterey 12.0.1

### ISSUE THREAD

**Issue by BluDread** [xbmc/xbmc#20430]
### Describe the bug

The mouse cursor is mapped incorrectly on the screen . it only go's 3/4 of the screen to the right
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

that the mouse cursor go's al the way to the right

## Actual Behavior

it stops aproximatly 3/4 of the way to the right

### To Reproduce

1. Upgrade macOS Big Sur to Monterey
2. Install or update Kodi to the latest Release

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ukugosipis.kodi 

### Screenshots
Here are some links or screenshots to help explain the problem:

https://drive.google.com/file/d/1Oj3D7GHSvlkuSynxefeL7H1KAiBAi8BG/view?usp=sharing

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Monterey 12.0.1
 - Kodi versions: 19.2 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
I can reproduce this.

**Comment by kambala-decapitator** [comment]
I think the first thing to try would be updating SDL to the latest version

**Comment by BluDread** [comment]
And it's an annoying bug I tried also Kodi nexus nightly build but all the new Kodi's seem to have it in Monterey ksooo
Kambala how can I update SDL to the latest version can you give me a hint ?

**Comment by kambala-decapitator** [comment]
> And it's an annoying bug I tried also Kodi nexus nightly build but all the new Kodi's seem to have it in Monterey ksooo.
> Kambala how can I update SDL to the latest version can you give me a hint ?

you need to make adjustments in https://github.com/xbmc/xbmc/blob/Matrix/tools/depends/target/libsdl/Makefile and build Kodi from source.

But I see that Kodi still uses SDL 1.x while the latest release is 2.x, hence it might be a challenge.

> https://drive.google.com/open?id=1Oj3D7GHSvlkuSynxefeL7H1KAiBAi8BG&authuser=roel.muylaert%40gmail.com&usp=drive_fs

btw your shared file isn't public

**Comment by BluDread** [comment]
I just changed the link of the shared file to this link .
https://drive.google.com/file/d/1Oj3D7GHSvlkuSynxefeL7H1KAiBAi8BG/view?usp=sharing
I hope it's public now kambala ,

> But I see that Kodi still uses SDL 1.x while the latest release is 2.x, hence it might be a challenge.

that's a big challenge for me I wouldn't know how to do that I hope I can manage it some how

**Comment by kambala-decapitator** [comment]
> I hope it's public now kambala ,can you check it for me ?

yes, now it's public, thanks. Although I'm not sure what you expect us to see from your screenshot of the start screen.

**Comment by BluDread** [comment]
it's the furthest possible range of the mouse cursor if I move it up or down I have hot corners enabled in Monterey then they are triggered so the mouse cursor thinks that that possession is the end of the screen I presume for the rest everything works fine I think.

**Comment by kambala-decapitator** [comment]
well, there's no mouse cursor at all on your SS :)

**Comment by BluDread** [comment]
I captured a video then you can see what actually happens :) hope that you can see it  
https://drive.google.com/file/d/1-0utez8jRhZ22GDugFR1VF-S9rbR5DD5/view?usp=sharing

**Comment by InAdavansP** [comment]
I confirm , i have the same problem

**Comment by kambala-decapitator** [comment]
please try the following test build: https://jenkins.kodi.tv/job/OSX-64/23337/artifact/tools/darwin/packaging/osx/kodi-20211118-cf889186-PR20540-merge-x86_64.dmg

if all is good, the fix will be a part of the next release.

**Comment by InAdavansP** [comment]
@kambala-decapitator 
Thank you it fixed the problem for me.
Hope the same for @BluDread

**Comment by ksooo** [comment]
Confirming the fix working. Thanks, @kambala-decapitator

**Comment by ksooo** [comment]
Manually applied the patch to Matrix, btw, and it works. So, the fix could easily be backported.

**Comment by BluDread** [comment]
Yes the fix works, great work @kambala-decapitator thanks for the test build :)

**Comment by BluDread** [comment]
thanks for solving the issue and for the great work on Kodi

**Comment by kambala-decapitator** [comment]
> Did this ever got out of test build?
> I am facing same issue on latest builds.

yes, all nightlies contain the fix

**Comment by kambala-decapitator** [comment]
> I've just installed KODI and have this problem... Will try a nightly build and see if it gets fixed

the fix is in v19.4 and v20
