### ISSUE TITLE
packaging/mk-debian-package.sh 

### ISSUE THREAD

**Issue by ArnoldSchiller** [xbmc/xbmc#20438]
Ok also not really an issue but rather a suggestion for improvement. Here with me comes with dpkg-buildpackage with tools/Linux/packaging/mk-debian-package.sh dependencies not met libmariaclient-dev  
apt install libmariaclient-dev Raspbian bullseye:
But the following packages replace it:
  libmariadb-dev-compat libmariadb-dev

The command
dpkg-buildpackage --build=binary
works here with the change of debian/control

[control.txt](https://github.com/xbmc/xbmc/files/7449319/control.txt)

Now upload as control not possible so extension .txt is added.

**Comment by ArnoldSchiller** [comment]
Learning. Looks like it affects this file
https://github.com/xbmc/xbmc-packaging/blob/master/debian/control
63,64c63,64
<  libmariadbclient-dev | libmysqlclient-dev,
<  libmariadbclient-dev-compat | libmysqlclient-dev,
---
>  libmariadbclient-dev | libmysqlclient-dev | libmariadb-dev,
>  libmariadbclient-dev-compat | libmysqlclient-dev | libmariadb-dev-compat,

**Comment by ArnoldSchiller** [comment]
Ok my first pull request and close
https://github.com/xbmc/xbmc-packaging/pull/35

**Comment by basilgello** [comment]
@ArnoldSchiller @wsnipex In Debian this dependency is handled as `default-libmysqlclient-dev`. Arnold, can you please post output of the following command on your Raspi Bullseye?

```shell
apt policy default-libmysqlclient-dev
```

**Comment by ArnoldSchiller** [comment]
> @ArnoldSchiller @wsnipex In Debian this dependency is handled as `default-libmysqlclient-dev`. Arnold, can you please post output of the following command on your Raspi Bullseye?
> 
> ```shell
> apt policy default-libmysqlclient-dev
> ```
default-libmysqlclient-dev:
  Installiert:           (keine)
  Installationskandidat: 1.0.7
  Versionstabelle:
     1.0.7 500
        500 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages
        500 http://raspbian.raspberrypi.org/raspbian bullseye-staging/main armhf Packages

Aha - ok i see 
apt install default-libmysqlclient-dev
done.

but
apt-cache policy libmariadbclient-dev
libmariadbclient-dev:
  Installiert:           (keine)
  Installationskandidat: (keine)
  Versionstabelle:
and
apt install libmariadbclient-dev
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Paket libmariadbclient-dev ist nicht verfügbar, wird aber von einem anderen Paket
referenziert. Das kann heißen, dass das Paket fehlt, dass es abgelöst
wurde oder nur aus einer anderen Quelle verfügbar ist.
Doch die folgenden Pakete ersetzen es:
  libmariadb-dev-compat libmariadb-dev

E: Für Paket »libmariadbclient-dev« existiert kein Installationskandidat.

**Comment by basilgello** [comment]
I think I will do it as part of efforts to unify Kodi's Debuntu packaging with Debian's official package that I maintain.

Thanks for investigation!

**Comment by ArnoldSchiller** [comment]
> I think I will do it as part of efforts to unify Kodi's Debuntu packaging with Debian's official package that I maintain.
> 
> Thanks for investigation!
after apt install default-libmysqlclient-dev I got:
building: DIST=bullseye ARCH=armhf
 dpkg-buildpackage -us -uc -ui
dpkg-buildpackage: Information: Quellpaket kodi
dpkg-buildpackage: Information: Quellversion 20.0~git20211031.2232-0acce28781-0~bullseye
dpkg-buildpackage: Information: Quelldistribution bullseye
dpkg-buildpackage: Information: Quelle geändert durch Team Kodi <dummy@kodi.tv>
 dpkg-source --before-build .
dpkg-buildpackage: Information: Host-Architektur armhf
dpkg-source: Information: Optionen aus kodi/debian/source/options werden verwendet: --tar-ignore=.git* --tar-ignore=build/* --tar-ignore=kodi_build*/*
dpkg-checkbuilddeps: Fehler: Nicht erfüllte Bauabhängigkeiten: libmariadbclient-dev | libmysqlclient-dev
dpkg-buildpackage: Warnung: Bauabhängigkeiten/-konflikte nicht erfüllt; Abbruch
dpkg-buildpackage: Warnung: (Verwenden Sie -d, um sich darüber hinwegzusetzen.)
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed

If I change the control as I said and then create a 
dpkg-buildpackage -us -uc -ui --build=binary it works.

**Comment by basilgello** [comment]
But did you replace the lines in control:

```
libmariadbclient-dev | libmysqlclient-dev | libmariadb-dev,
libmariadbclient-dev-compat | libmysqlclient-dev | libmariadb-dev-compat,
```

with

```
default-libmysqlclient-dev,
```

**Comment by basilgello** [comment]
Please see: https://salsa.debian.org/multimedia-team/kodi-media-center/kodi/-/blob/master/debian/control#L13

**Comment by basilgello** [comment]
Also I would advise you to use `pbuilder` or Docker/Podman to build Debian packages. This way your host system will npt be polluted by build-dependencies of Kodi. For 20.x I even managed to integrate proper cross compilation of Debian packages for any supported Debian `ARCH` on any supported host architrcture, like `pbuilder build --host-arch armhf kodi.asc`

**Comment by ArnoldSchiller** [comment]
> default-libmysqlclient-dev,

works wonderfully. Thank you.
https://github.com/xbmc/xbmc-packaging/pull/35#issuecomment-955804732
