### ISSUE TITLE
cannot find -lunistring

### ISSUE THREAD

**Issue by ArnoldSchiller** [xbmc/xbmc#20434]
Not really an issue just a note. Have successfully compiled kodi from git yesterday under raspbian bullseye. But the first run was not successful because libunistring-dev was not installed and kodi needs that. Is not in the dependency list in the readme.md

20.0-ALPHA1 (19.90.101) Git:20211030-e8ea53446a Media Center Kodi
Copyright (C) 2005-2021 Team Kodi - http://kodi.tv

**Comment by howie-f** [comment]
true, `libunistring-dev` is needed to build.
would you like to pull request the fixed readme?

**Comment by ArnoldSchiller** [comment]
> true, `libunistring-dev` is needed to build. would you like to pull request the fixed readme?
Oh I've never done anything like this before and somehow I'm failing at it right now. I have updated the readme here locally - attached here. 


[README.Linux.md](https://github.com/xbmc/xbmc/files/7449075/README.Linux.md)

**Comment by howie-f** [comment]
ok, thanks a lot for bringing it to our attention :+1:

**Comment by ArnoldSchiller** [comment]
> ok, thanks a lot for bringing it to our attention +1
Thank you for the pull request - will have to learn how to do that if I ever notice something and can fix it.

**Comment by howie-f** [comment]
yes, welcome.. please ask for guidance if necessary (maybe i misunderstood and you were actually asking for guidance) 🤔

**Comment by ArnoldSchiller** [comment]
> yes, welcome.. please ask for guidance if necessary (maybe i misunderstood and you were actually asking for guidance) thinking
Thanks for the offer. Have read that https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request#creating-the-pull-request  ,but it probably somehow not quite understood. 

The next issue https://github.com/xbmc/xbmc/issues/20438 
ist nicht so einfach. Ich denke mk-debian-package.sh generiert das debian/control erst. Somit hilft der patch wohl wenig. 

63,64c63,64
<  libmariadbclient-dev | libmysqlclient-dev,
<  libmariadbclient-dev-compat | libmysqlclient-dev,
---
>  libmariadbclient-dev | libmysqlclient-dev | libmariadb-dev,
>  libmariadbclient-dev-compat | libmysqlclient-dev | libmariadb-dev-compa

**Comment by howie-f** [comment]
hey Arnold, we need to stick with english here. so anybody can understand 🙂
personally i‘m not very familiar with mk-debian-package.sh so we will see if somebody can chime in..

danke dir

**Comment by ArnoldSchiller** [comment]
Ja weiss ich denn dass du auch deutsch spricht - aber jetzt habe ich meinen ersten Pull Request gemacht. Habs gefunden, was zu ändern wäre mk-debian-packages.sh zieht sich das von dort https://github.com/xbmc/xbmc-packaging/pull/35 und in bullseye gibt es zumindest beim raspbian bullseye keine libmariadbclient-dev mehr wird ersetzt durch libmariadb-dev ebenso die compat also fliegt dpkg-buildpackage auf die Schnauze, weil die Abhängigkeit nicht erfüllt ist.  Fast überall wird ja noch auf buster entwickelt und compiliert, sodaß das keinem auffällt. Ich war halt so verrückt meinen Raspi auf bullseye hochzumigrieren und dann stellte ich fest, das kodi im Repository nicht mehr existiert und so landete ich hier. Alpha läuft hier stabil. Das ich dann gleich von Leia auf Nexus migriere nennt sich dann wohl early adaptor.
