### ISSUE TITLE
WebVTT parser does not display &amp; escape character correctly

### ISSUE THREAD

**Issue by Liqianyu** [xbmc/xbmc#20446]
### Describe the bug
Here is a clear and concise description of what the problem is:

Playing the [episode](https://www.netflix.com/watch/80991192) with Netflix Add-On on the latest Kodi v20 (Nexus) Nightly reproduces the problem

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

At about 4:26, the subtitle display
We've all been to H&M and been like, 

## Actual Behavior

At about 4:26, the subtitle display
We've all been to H`&amp;`M and been like, 

## Possible Fix

@CastagnaIT Please add the appropriate CSS parsing within the WebVTT parser, thank you.

### To Reproduce

1.Open Kodi
2.Open Netflix Add-on,Watch Patriot Act with Hasan Minhaj Volume 5 E3 "The Ugly Truth of Fast Fashion"
3.Note all the subtitles that mention H&M

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/azelahejix.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:NVIDIA SHIELD Android TV with Android 9.0.0
 - Kodi version:20.0-ALPHA1(19.90.101) 20211101-aadfc2dc13

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
Thanks for the report in the specifications it seems that HTML escaping chars are allowed, i think we can add the most common escapes chars only as specified in the old webvtt W3C documentation so to not make the parsing more cumberstone
