### ISSUE TITLE
Kodi 19.3 won't start

### ISSUE THREAD

**Issue by Technobody** [xbmc/xbmc#20448]
### Describe the bug
Here is a clear and concise description of what the problem is:
<Kodi needs to be started 3-4 times before it actually turns on

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
When you turn Kodi on it just sits there for 4-5 minutes before it starts. Often times you have to start it 4-5 times before it actually begins to work

## Actual Behavior
<Won't start first time turned on.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 
 - Operating system version/name:
 - Kodi version:19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Please use forum for support

**Comment by Technobody** [comment]
Why not pay more attention to fixing the problem rather than your insane rules. I don't know how to fix it You people need to get in touch with reality
