### ISSUE TITLE
Bluray isos wont show title under playback and not marked as watched after viewing

### ISSUE THREAD

**Issue by faltaren** [xbmc/xbmc#20455]
### Describe the bug
Here is a clear and concise description of what the problem is:

Bluray isos wont show title under playback and not marked as watched after viewing. Title of movie in the list is "title". I have to go back and in to the list again to see the movie name. And its marked as unwatched even if i just saw the movie. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Movietitle form metadata showing underplayback when menus show. Movie marked as viewed after viewing.

## Actual Behavior

LIke i said

### To Reproduce

1. Add a bluray iso with metadata
2. play the move til the end
3. show the playbackmenu and you see thats its just named title
4. after you close the movie the movie name is gone
5. go back and then forward in the libery.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
>Add a bluray iso with metadata

What do you mean by the above? Have you somehow embedded library metadata into the iso?

How are you scraping these movies into your library.

Where is the debug log?

**Comment by faltaren** [comment]
> > Add a bluray iso with metadata
> 
> What do you mean by the above? Have you somehow embedded library metadata into the iso?
> 
> How are you scraping these movies into your library.
> 
> Where is the debug log?

I scan them like any other media file. So regular scraping. Il get you a debugg log.

**Comment by faltaren** [comment]
![20211103_185753](https://user-images.githubusercontent.com/50858314/140179893-44399a02-b27b-4d80-9e7f-c87e341f83f1.jpg)
![20211103_202925](https://user-images.githubusercontent.com/50858314/140179899-66dadffe-b6c7-4100-9418-5c45e2b406a6.jpg)
![20211103_202936](https://user-images.githubusercontent.com/50858314/140179903-572a54c0-8c00-4d9b-90e5-221b140c85cb.jpg)

Heres some pics. No movie name and the title is back when i go back and in again. But movie is unwatched.

**Comment by DaVukovic** [comment]
I can confirm this issue. Mentioned it years ago already at slack and I guess it was also previously reported, but I can't find the issue anymore
