### ISSUE TITLE
Extension programicaly change "Pixel ratio adjustment" by python

### ISSUE THREAD

**Issue by expertup** [xbmc/xbmc#20487]
### Describe the bug
Here is a clear and concise description of what the problem is:

How is possible get/set setings pixel ratio by script in python? E.g. `executeJSONRPC`
xbmc.executeJSONRPC('{"jsonrpc": "2.0", "method": "Settings.GetSettings", "params": {"setting":"video.calibrationratio"}, "id": 1}')

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I need to change the pixel ratio setting programmatically when writing an add-on

### Screenshots 
Here are some links or screenshots to help explain the problem:

![pixelratio](https://user-images.githubusercontent.com/1708687/140665683-99209aff-63e0-45c9-9768-7f30ffd13837.PNG)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 21H2, kernel: Windows NT x86 64-bit version 10.0.20348.320
 - Kodi version: Kodi (19.3 (19.3.0) Git:20211024-49a04cd6a7). Platform: Windows NT x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Use the forum for support
