### ISSUE TITLE
Kodi continues to crash on windows 10 32 bit after loading the initial time and customizing

### ISSUE THREAD

**Issue by XtremeSounds** [xbmc/xbmc#20488]
I load kodi the first time no problem although full screen is slow on version 19. (I tried 17 and it was faster).  The issue is after selecting some local media (VIdeo and audio) and adding those folders to favorites.  Then I go to settings and remove all folders from home screen except favorites.  this is so its really easy to go straight to the media I want.  I close Kodi and then try to reopen it and it crashes.  I try 3 times still it doesnt work. I have to restart the computer to get it going again.  

Note: I turned off all other options that I do not need including check for updates. I only want to use kodi as a local media browser as it has large text and menus. 

The computer only has 2gb ram installed windows 32 bit system maybe that is the issue?

**Comment by XtremeSounds** [comment]
as an update when I try to reopen kodi all my favorites are missing and it crashing. i removed the file addons33 from the db folder and it worked this time.  The issue is somehow this file addons33 is getting corrupted on each use.

**Comment by KarellenX** [comment]
@XtremeSounds 

You have ignored the required template in your first post and not provided a debuglog.

I'll close your report. Please head over to the forum to request support. Remember to provide the debug log.

**Comment by XtremeSounds** [comment]
Sorry I dont know how to do that,.
