### ISSUE TITLE
Something crashing Kodi on Windows 32 bit 

### ISSUE THREAD

**Issue by XtremeSounds** [xbmc/xbmc#20490]
Just look into it. somehow going into settings and removing all menu items except favorites is causing a crash in wi
[last issues in log.txt](https://github.com/xbmc/xbmc/files/7505469/last.issues.in.log.txt)
ndows 32 bit.  basically all i want is the favorite screen on startup and add some local audio and video files.  BUt it doesnt like that so much.  I cannot find the debugging file for this

**Comment by XtremeSounds** [comment]
I did a fresh install of Kodi for windows (From Miscrosoft app store) Here are the only changes I made - I didnt even add any media and it crashed. 

Removed all Home items except Pictures, Videos, Music, Favorites 
Turned off hardware acceleration
Never check for updates 
Turned of skin visuals
Turned Debugging on 

Now it crashed on startup and I haven't even done anything else. One of these things is the issue

**Comment by KarellenX** [comment]
@XtremeSounds 

What did you not understand about my last post where I asked you to fill in the Template when making a report. And also that you should take this issue to the forum first.

I cannot replicate this issue, but I am using 64 bit. Have you tried 64bit?
So I will close this new report and expect to see you on the forum first.

**Comment by XtremeSounds** [comment]
Youre a tough one.
