### ISSUE TITLE
Audio Passthrough in Xbox

### ISSUE THREAD

**Issue by 618116** [xbmc/xbmc#20499]
### Describe the bug
Here is a clear and concise description of what the problem is:

Current Xbox OS allows bitstream passthrough. However, Kodi 19.3 for Xbox does not support the option.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Bitstream audio track can be passthrough.

## Actual Behavior

There is no option for passthrough in Kodi setting.

## Possible Fix

Lack of passthrough is due to using XAudio. UWP on Xbox support WASAPI(there is a sample; https://github.com/microsoft/Xbox-GDK-Samples/tree/main/Samples/Audio/SimpleWASAPIPlaySound), and passthrough only can be used with WASAPI.
I have tested IsFormatSupported() with below format, and S_OK is returned on Xbox. 
`WAVEFORMATEXTENSIBLE wfxex;
/* Test format DTS-HD */
wfxex.Format.cbSize = sizeof(WAVEFORMATEXTENSIBLE) - sizeof(WAVEFORMATEX);
wfxex.Format.nSamplesPerSec = 192000;
wfxex.dwChannelMask = KSAUDIO_SPEAKER_7POINT1_SURROUND;
wfxex.Format.wFormatTag = WAVE_FORMAT_EXTENSIBLE;
wfxex.SubFormat = KSDATAFORMAT_SUBTYPE_IEC61937_DTS_HD;
wfxex.Format.wBitsPerSample = 16;
wfxex.Samples.wValidBitsPerSample = 16;
wfxex.Format.nChannels = 8;
wfxex.Format.nBlockAlign = wfxex.Format.nChannels * (wfxex.Format.wBitsPerSample >> 3);
wfxex.Format.nAvgBytesPerSec = wfxex.Format.nSamplesPerSec * wfxex.Format.nBlockAlign;`

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
I'll close this. GH issues is for bug reports. This is just a feature not implemented.

Requests can be made on the forums, even better would be PRs to implement said request.
