### ISSUE TITLE
Kodi hangs at boot when startup window is set to "PVR channels" but no PVR add-on is enabled

### ISSUE THREAD

**Issue by slrslr** [xbmc/xbmc#20513]
kodi/stable 2:19.1+dfsg2-2 armhf
Linux xbian 5.10.75+

Hello,
as title says. I think that Kodi should not enable TV channel list (default was "Home screen" at Settings/Interface/Startup/Startup Window/) if it can not display it at boot and even if it enable it, then at boot the UI should not stop responding as [described here](https://www.reddit.com/r/kodi/comments/qs99ue/which_file_to_edit_to_enable_kodi_addon/).

**Comment by ksooo** [comment]
whitout a proper debug log we cannot say anything to this, we need far more information.

**Comment by ksooo** [comment]
> enabled “display TV channels at startup” kind of option

I'm not aware of such an option in Kodi. Where have you found it? Screenshot maybe?

**Comment by ksooo** [comment]
> <pvrmanager><enabled default="true">false</enabled>

 This setting was removed many Kodi versions before 19.

**Comment by slrslr** [comment]
Please fix this page https://kodi.wiki/view/HOW-TO:Submit_a_bug_report#Debug_log
which links to https://kodi.wiki/view/Settings/System/Logging and on any of these i am unable to see how to enable logging if Kodi UI is frozen.
Maybe it is mentioned here: https://kodi.wiki/view/Log_file/Advanced

**Comment by slrslr** [comment]
> Screenshot maybe?

Thank you, no, i do not remember, i can not access the UI of the Kodi. I think you can find it in Settings. There is somewhere maybe in PVR settings the action to take after startup of Kodi. List tv channels or run the TV channel last used or such.

**Comment by ksooo** [comment]
> says "No PVR addon enabled"

To get PVR via tvheadend working you need

a) a tvheadend server. For ease of use, LibreELEC provides an addon for this "Tvheadend Server 4.2", which installs the tvheadeend server on the same machine kodi is running on. Install this addon!
b) a PVR Addon fpr Kodi to connect Kodi with the server. You need to install "Tvheadend HTSP Client".

Ofc, both addons need to be configured properly after installation.

**Comment by ksooo** [comment]
> There is somewhere maybe in PVR settings the action to take after startup of Kodi.

 Aha. Now I understand what you mean. Thanks. I will take a look.

**Comment by slrslr** [comment]
Thanks for your effort. [Here](https://bin.disroot.org/?c3e8f25e84e8485f#APpaZ9yhEpxVrD7kE8XyRvf17XFHAN9orVyYDqfXEKVJ) i have got the debug.log log level INFO (0)
Actually i have removed the TVheadend addon and its folder, so no component log needed (if i understand correct):
`cd /home/xbian/.kodi/addons/ && mv service.tvheadend42 .. && cd /home/xbian/.kodi/userdata/addon_data && mv service.tvheadend42 ..`

**Comment by ksooo** [comment]
Please enable "debug logging" and "component logging" for "pvr" in Kodi system settings. Otherwise the log will not contain enough information to track down your problem.

**Comment by slrslr** [comment]
I have enabled debug logging (1) and pvr component logging. [Here is](https://bin.disroot.org/?5dceb67d079f5d77#CNq2wxxe6HnTKPocs3TduCjhrX7jR9JXT4z4e9wmYsuc) log please.

**Comment by ksooo** [comment]
```
2021-11-13 12:15:10.950 T:2454     INFO <general>:   skin loaded...
2021-11-13 12:15:10.950 T:2454    DEBUG <general>: Activating window ID: 12997
2021-11-13 12:15:10.950 T:2454    DEBUG <general>: ------ Window Init () ------
2021-11-13 12:15:10.950 T:2454    DEBUG <general>: Alloc resources: 0.00ms  (0.00 ms skin load)
2021-11-13 12:15:10.950 T:2454    DEBUG <general>: Activating window ID: 12999
2021-11-13 12:15:10.950 T:2454    DEBUG <general>: ------ Window Init (Startup.xml) ------
2021-11-13 12:15:10.950 T:2454     INFO <general>: Loading skin file: Startup.xml, load type: LOAD_EVERY_TIME
2021-11-13 12:15:10.951 T:2454    DEBUG <general>: Skin file /usr/local/share/kodi/addons/skin.estuary/xml/Startup.xml loaded in 0.27ms
2021-11-13 12:15:10.951 T:2454    DEBUG <general>: Alloc resources: 0.33ms  (0.33 ms skin load)
2021-11-13 12:15:10.951 T:2454    DEBUG <general>: Activating window ID: 10700
2021-11-13 12:15:10.951 T:2454    DEBUG <general>: ------ Window Init (DialogConfirm.xml) ------
2021-11-13 12:15:10.951 T:2454     INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2021-11-13 12:15:10.954 T:2454    DEBUG <general>: Skin file /usr/local/share/kodi/addons/skin.estuary/xml/DialogConfirm.xml loaded in 3.40ms
```

The log tells, that on startup, you should see a dialog like this:

<img width="1680" alt="Screenshot 2021-11-13 at 12 19 40" src="https://user-images.githubusercontent.com/3226626/141641124-fbc62c2f-a10c-41cc-a0b9-b26c0ec6a273.png">

Do you see this dialog?

**Comment by slrslr** [comment]
yes, i see it, and it does not react on keyboard nor remote controller CEC

**Comment by ksooo** [comment]
> yes, i see it, and it does not react on keyboard nor remote controller CEC
>  i have described 2 ways out of this per my idea

The only way to fix this is get the dialog response to mouse/keyboard/remote input. ;-)

The bad thin is that I cannot reproduce your problem. When I disable my PVR addon and enable "TV channel" as startup action, on restart of kodi I end up with abovementioned dialog, but reacts on input. After conforming the dialog I end up at Kodi homescreen, Kodi being fully reactive to user input. I'm using macOS, maybe we're facing platform specific bug with the windowing system or the like. Unfortunately, I'm out at this point.

@lrusak could you take a look? YOu don't need a PVR setup for this. Just set Settings -> Interface -> Startup -> Startup Window to "TV channels" and restart Kodi. Abovementioned confirmation dialog pops up and if it is not responding to user inout you are able to reproduce the problem. I can't on macOS.

**Comment by slrslr** [comment]
I (OP) am unable to reproduce this.
So i suggest you spend no more time on this and close it. Maybe it was file/folder user account ownership issue (if so, then kodi should mention failure to access in debug log)

**Comment by ksooo** [comment]
Please try reinstalling tvheadend from scratch.

**Comment by slrslr** [comment]
I did. Kodi or TVHeadend addon should have timeout returning some more informational message than infinite loading PVR.
