### ISSUE TITLE
AC-3 Transcoding fails in the latest master

### ISSUE THREAD

**Issue by tiagogaspar8** [xbmc/xbmc#20529]
### Describe the bug
Here is a clear and concise description of what the problem is:
When playing a media file with 5.1 or higher channel count to a device which only supports encoded surround audio will result in no sound because of an error.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
The audio should be resampled to AC3 and sent to the output device.

## Actual Behavior
No audio is sent.

## Possible Fix
None that I've found.

### To Reproduce
1. Make sure audio passthrough is enabled and transcoding too only for AC-3.
2. Play a file with a codec different from AC-3 for example AAC or DTS

### Debuglog
The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/7539247/kodi.log)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
This bug makes it impossible to play 5.1 or up channel audio on for example a S/PDIF sound system.

### Your Environment
Used Operating system:

 - Operating system version/name:
Windows 11 with the latest updates
Windows 10 with the latest updates

 - Kodi version:
Kodi (20.0-ALPHA1 (19.90.101) Git:20211112-a669003fb0) which is the latest master

- Devices connected:
LG OLED55B1 trough HDMI, with a sound system with DTS/Dolby Digital support trough S/PDIF

**Comment by DaVukovic** [comment]
Duplicate:

https://github.com/xbmc/xbmc/issues/20398

Closed

**Comment by tiagogaspar8** [comment]
Hi,

I saw that issue, but since it was in a different platform and seemed to be fixed (?) I decided to create a new one.

Should I add info to the other issue? Mainly platform etc.?

Thanks, and sorry for the duplicate!

**Comment by popcornmix** [comment]
Yes, add to other issue, including any new information (like the platform).

**Comment by cromefire** [comment]
> seemed to be fixed (?)

No it's not fixed, 19.3 is only unaffected because 20.0 introduces that bug.

**Comment by tiagogaspar8** [comment]
> > seemed to be fixed (?)
> 
> No it's not fixed, 19.3 is only unaffected because 20.0 introduces that bug.

I see
