### ISSUE TITLE
CDVDOverlayImage: cleanup #20260 breaks JAVA menu's for blurays and UHD

### ISSUE THREAD

**Issue by maff76** [xbmc/xbmc#20544]
## Bug report
since this PR has been merged JAVA menu's on bluray iso and folder rips are broken
Here is a clear and concise description of what the problem is:

when you start a bluray disk and the JAVA menu appears you often get an option to resume the movie or go to the menu's these options do not display and you are just left with the background of the menu and unable to watch the movie

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

when you launch the movie you should be greeted with menu options to select default language, resume or start over or go to main menu/play main title

## Actual Behavior

the background for the menu loads but no options appear to progress

## Possible Fix

remove the PR or rework it

### To Reproduce

1. install any version of Kodi V20 after or including KodiSetup-20211020-ac0d7632--x64
2.play a bluray title with full menu's
3.

### Debuglog

The debuglog can be found here: https://pastebin.com/R56nDdn2
debug log of a working build but with graphic corruption https://pastebin.com/pDApTNAh

### Screenshots 
Here are some links or screenshots to help explain the problem:

here is what it should look like https://ibb.co/6NQhGzY this is from kodi 19.3
this is what is does look like https://ibb.co/CKLBLJH

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

jjd-uk was helping me test this and supplied two builds, one worked and one didn't but the one that worked has graphical glitches that are not present in Kodi 19.3 so suspecting possibly another overlay PR would need looking at if one exists 

menu from Kodi 19.3 https://ibb.co/P6FjZGh no corruption

menu from KodiSetup-20211020-a497d89a--x64 https://ibb.co/QfpfjX9 graphical corruption

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 21h2
 - Kodi version: Nexus V20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by boeschy** [comment]
I can confirm that reverting the commits of PR20260 brings back the menus.

**Comment by lrusak** [comment]
> I can confirm that reverting the commits of PR20260 brings back the menus.

Can you bisect which commit specifically?

**Comment by boeschy** [comment]
I hope I did it correctly, I've never bisected before.
git bisect log:
```
# bad: [734f5636e6abd6544a09ae6cdf695d7c6db588f1] COverlayGlyphGL: use std::vector
# good: [1dcd4ce59c59d97d4972fb52bf29901830381dbd] Merge pull request #20227 from CastagnaIT/isplaying_settings
git bisect start '734f5636e6abd6544a09ae6cdf695d7c6db588f1' '1dcd4ce59c59d97d4972fb52bf29901830381dbd'
# good: [9346a2e276f1d1364928ab3e96dcbba188620e0b] Merge pull request #20170 from neo1973/GUIAudioManager
git bisect good 9346a2e276f1d1364928ab3e96dcbba188620e0b
# bad: [1b1626dc5a04f36e23eb8786be297e7509100f81] CDVDOverlayImage: initialize member variables
git bisect bad 1b1626dc5a04f36e23eb8786be297e7509100f81
# bad: [d47f8346b62b6e14493ee371a1a269ec8c5a772d] CDVDOverlayImage: use std::vector
git bisect bad d47f8346b62b6e14493ee371a1a269ec8c5a772d
# first bad commit: [d47f8346b62b6e14493ee371a1a269ec8c5a772d] CDVDOverlayImage: use std::vector```

**Comment by lrusak** [comment]
@boeschy thanks for that. I looked at the commit and didn't see any smoking gun. I'll have to try and reproduce on my side.

You don't know if this happens to effect GL platforms as well (Linux, OSX, android)?

**Comment by enen92** [comment]
Fwiw I've tested at least on Linux and was not able to reproduce. Might be windows only

**Comment by lrusak** [comment]
I think I see the issue. I'll try and have a fix after work today.

**Comment by boeschy** [comment]
I just checked with a patched build to run on android tv (thx @fandangos for making this possible) and with the bad commit the menus are also broken. So it seems to be not a Windows only issue.

**Comment by thexai** [comment]
Here a test build with master branch up to date + revert commit on top:
https://www.mediafire.com/file/3hi737qm47mo0ow/KodiSetup-20211218-b881b538-revert-PR20260-x64.exe/file

Code:
https://github.com/thexai/xbmc/commit/b881b53851c05b19f4ad342e620288db10842995
https://github.com/thexai/xbmc/tree/revert-PR20260

Revert is not direct because merge conflicts.

PS: I tried a make more "official" build with Jenkis but files have mysteriously disappeared from the servers.... uploaded to mediafire then.

**Comment by maff76** [comment]
Hi there

the menu's are now visible but the graphic corruption is there now as in the build jjd-uk supplied

here is what it should look like https://ibb.co/6NQhGzY this is from kodi 19.3
this is what is does look like https://ibb.co/CKLBLJH

**Comment by thexai** [comment]
Reproducible also with UHD Blu-Ray's (some times is not much evident):

![screenshot00009](https://user-images.githubusercontent.com/58434170/146753291-5a6406f5-e7b7-4625-a6e6-5b10f2d932e5.png)

![screenshot00008](https://user-images.githubusercontent.com/58434170/146753305-42a294ac-c67d-44c6-afac-070d66b6a4d6.png)

**Comment by thexai** [comment]
Jenkins build with two PR's reverted:
http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20211220-e0ff99aa-revert-PR2060-PR20204-x64.exe

**Comment by maff76** [comment]
latest build fixes it :)

**Comment by TeHaX** [comment]
Can also confirm the fix in latest build. Like to see adding libbluray 1.3.0 too.
