### ISSUE TITLE
photos in the wrong way

### ISSUE THREAD

**Issue by PowaBanga** [xbmc/xbmc#20548]
### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [*] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: archlinux (arm)
 - Kodi version:  19.3

kodi show my photos in a random way in picture slideshow screensaver... it's not usefull to see poeple with theyr head down or on the side...

**Comment by enen92** [comment]
Please follow the issue template, it exists for a reason. No provided log too. Closing this.
