### ISSUE TITLE
Google drive addon error on Xbox one

### ISSUE THREAD

**Issue by hellfish87** [xbmc/xbmc#20553]
I've installed kodi matrix 19.3 on Xbox one But the Google drive addon isnt working it says install failed. Appears to be a missing deoendencys But that deoendencys are installed correctly.
This problem is only on Xbox one in My Windows pc or Android phone works fine that addon. How can i resolve this problem? Tnx

**Comment by KarellenX** [comment]
Please head to the forum to ask support questions.

In future, do not delete the required template.
