### ISSUE TITLE
Fail to install addon due to file permission issue on Android

### ISSUE THREAD

**Issue by link89** [xbmc/xbmc#20568]
### Describe the bug
Fail to install addon  on Android 

## Expected Behavior
Plugin can be installed

## Actual Behavior

Plugin fail to install.

### To Reproduce

1. Install any random plugins from repo. 

### Debuglog

Error renaming file.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

![image](https://user-images.githubusercontent.com/3314130/143065849-2130049f-3811-4d0c-9816-11bd58de0de0.png)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android/5.1.1 HiTV-M1
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@link89 

Please ask your support question on the forum.

**Comment by link89** [comment]
@KarellenX It looks like a bug to me. I can confirm the permission of Kodi is correct (with read/write file permission) but it just fail to rename the plugin.

**Comment by KarellenX** [comment]
Ok, but if it were a bug, we would have had a flood of reports already. I expect you are using v19.3 and that has been out for over a month already.

You haven't provided a debuglog (screenshots are useless to us) so provide that.

Don't stress, if it does turn out to be a bug, I'll just reopen this issue report. But lets confirm what the problem is first.

Thanks. :)

**Comment by link89** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/7596435/kodi.log)

Hi @KarellenX Can you kindly check if this log could help?

I have do some test myself,  it is OK to execute
```sh
cd /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons
touch 1
```
But fail to rename it.
```sh
mv 1 2
mv: rename 1 to 2: Permission denied
```

**Comment by link89** [comment]
It turns out that it is the SELinux's policy on my Android TV device that block the rename operation.
```
W/mv      ( 1633): type=1400 audit(0.0:103): avc: denied { rename } for name="1" dev="sdcardfs" ino=265432 scontext=u:r:shell:s0 tcontext=u:object_r:ext_storage:s0 tclass=file permissive=0
```

**Comment by link89** [comment]
Do you think a patch to dealing with this case is acceptable? If error of rename permission issue is detected, then use the copy and remove pattern as a replacement.

**Comment by KarellenX** [comment]
Unfortunately we don't have an Android developer, and I am not an Android user.

Not sure who could advise you best. Maybe @fuzzard for the general view, or @wsnipex as a Linux user?

**Comment by link89** [comment]
Anther option is to use `/data/local/tmp` as temporary directory on Android. It's OK to save the temp file there and then move to the target.
@KarellenX Hi, can you kindly reopen this issue as all I seek is to get Kodi worked on my Android device without root.

**Comment by fuzzard** [comment]
Give us a full unadulterated log to start with. The log you pasted is missing a bunch of normal logging from startup.

**Comment by link89** [comment]
Hi @fuzzard I am not fully understand. Can you give me a sample path to get the log or some command?

**Comment by fuzzard** [comment]
https://kodi.wiki/view/Log_file

**Comment by link89** [comment]
@fuzzard Isn't this one: https://github.com/xbmc/xbmc/files/7596435/kodi.log

**Comment by fuzzard** [comment]
It is incomplete

**Comment by link89** [comment]
I get this via `adb pull /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log`  
```
2021-11-24 22:27:50.445 T:30150 WARNING <general>: Rename: Can't access file "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/temp/1fcefd0a-a445-4f05-9ef8-9a2cb3df763b" for rename to "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/inputstream.ffmpegdirect"
2021-11-24 22:27:50.445 T:30150   ERROR <general>: Rename - Error renaming file /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/temp/1fcefd0a-a445-4f05-9ef8-9a2cb3df763b
2021-11-24 22:27:50.446 T:30150   ERROR <general>: Failed to move new addon files from '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/temp/1fcefd0a-a445-4f05-9ef8-9a2cb3df763b' to '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/inputstream.ffmpegdirect'
2021-11-24 22:27:50.480 T:29817   DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2021-11-24 22:27:50.486 T:30645   DEBUG <general>: Thread JobWorker start, auto delete: true
2021-11-24 22:27:50.541 T:30150   ERROR <general>: CAddonInstallJob[pvr.iptvsimple]: failed to install dependency inputstream.ffmpegdirect
2021-11-24 22:27:50.679 T:29817   DEBUG <general>: CGUIMediaWindow::GetDirectory (addons://downloading/)

```

If this is not enough, I would collect another one.

**Comment by link89** [comment]
The problem seems clean to me that the SELinux policy of my tv box deny the rename operation. Potential solution is to use `/data/local/tmp` for temporary data when possible on Android. Or else I have to root it to close the SELinux. I don't think it is a good option for most users.

**Comment by fuzzard** [comment]
No one else has ever brought this "issue" up. Theres millions of android users using kodi. I highly doubt a "workaround" for some random unknown device is going to be put in place without considerably more information.

If your device is enforcing some random overzealous selinux policy, you may need to contact the manufacturer for assistance

**Comment by a1rwulf** [comment]
@link89 as @fuzzard mentions your log looks incomplete, we can't see the Android version etc.
What device are we talking about and which Android version do you run.
Also, please try to come up with a full debug log.

**Comment by link89** [comment]
Before I report the problem here I also find some bug report here https://forum.kodi.tv/printthread.php?tid=328559
But I don't think they are treated seriously.

I have also provided the audit log of selinux which can prove my doubt.
```
W/Thread-990( 1854): type=1400 audit(0.0:105): avc: denied { reparent } for name="feae5195-af0f-4ead-88b7-2261c31a64c3" dev="sdcardfs" ino=281794 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:ext_storage:s0 tclass=dir permissive=0
```
I guess it is not a bad thing to have strict security rule. And the `/data/local/tmp` seems to be a good place for temporary file.

**Comment by a1rwulf** [comment]
The bugreport you link has a log attached which is using Kodi 17.6 which isn't supported anymore since years.
If you want help, consider providing the information we ask for.
First we need to have the very basic information about your system...

**Comment by link89** [comment]
[kodi.1.log](https://github.com/xbmc/xbmc/files/7601896/kodi.1.log)
Here is the beginning part.

**Comment by link89** [comment]
[kodi.full.log](https://github.com/xbmc/xbmc/files/7601902/kodi.full.log)
Full log (with error)

**Comment by link89** [comment]
Output of `adb logcat | grep -C 10 avc`

```
D/Kodi    (29817): 2021-11-25 17:51:51.125 T:29968   DEBUG <general>: CAddonDatabase::GetAddons took 1290 ms
D/Kodi    (29817): 2021-11-25 17:51:51.180 T:29968   DEBUG <general>: ADDONS: repo: repository.xbmc.org - 881 addon(s) loaded
D/Kodi    (29817): 2021-11-25 17:51:51.221 T:29968   DEBUG <general>: Unpacking zip://special%3a%2f%2fhome%2faddons%2fpackages%2finputstream.ffmpegdirect-19.0.0.zip/inputstream.ffmpegdirect/ to /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/temp/928fbf4c-02d4-4786-8fce-21a1d79b8173
D/bt_hci_bdroid( 3107): event_heartbeat_idle_timeout num_hci_cmd_pkts = 1
D/bt_vendor( 3107): op for 7
D/bt_hci_bdroid( 3107): event_heartbeat_idle_timeout num_hci_cmd_pkts = 1
D/bt_vendor( 3107): op for 7
W/Thread-431(29968): type=1400 audit(0.0:29): avc: denied { reparent } for name="928fbf4c-02d4-4786-8fce-21a1d79b8173" dev="sdcardfs" ino=274439 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:ext_storage:s0 tclass=dir permissive=0
W/Kodi    (29817): 2021-11-25 17:51:53.244 T:29968 WARNING <general>: Rename: Can't access file "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/temp/928fbf4c-02d4-4786-8fce-21a1d79b8173" for rename to "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/inputstream.ffmpegdirect"
E/Kodi    (29817): 2021-11-25 17:51:53.244 T:29968   ERROR <general>: Rename - Error renaming file /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/temp/928fbf4c-02d4-4786-8fce-21a1d79b8173
E/Kodi    (29817): 2021-11-25 17:51:53.244 T:29968   ERROR <general>: Failed to move new addon files from '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/temp/928fbf4c-02d4-4786-8fce-21a1d79b8173' to '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/inputstream.ffmpegdirect'
D/Kodi    (29817): 2021-11-25 17:51:53.278 T:29838   DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
```

**Comment by wsnipex** [comment]
Interesting, your device prohibits moving a file **inside the applications data directory**.
That certainly looks a tad overzealous

**Comment by link89** [comment]
Well, a 2$ workaround: purchase a USB storage and then 
```sh
mkdir /mnt/usb/sda/sda1/kodi_data
echo '/mnt/usb/sda/sda1/kodi_data' > /sdcard/xbmc_env.properties
```

**Comment by link89** [comment]
It seems like the `reparent` (moving directory) even not supported on external storage.

**Comment by link89** [comment]
I just create a concept of fix. The same method has been used to deal with rename across mount points.
