### ISSUE TITLE
Should display Atmos information on media

### ISSUE THREAD

**Issue by gdesmott** [xbmc/xbmc#20573]
Medias with an Atmos stream are currently displayed as `DOLBY` and `5.1`. It would be nice to have `ATMOS` instead of `DOLBY` so one can easily check if Atmos is supported or not by the media.

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Screenshot from 2021-11-24 11-14-43](https://user-images.githubusercontent.com/1379524/143219166-26f6f93e-17dc-4415-86e3-16c15a55af20.png)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by the-black-eagle** [comment]
Please submit feature requests to the forum. https://forum.kodi.tv/forumdisplay.php?fid=9

Thanks.
