### ISSUE TITLE
Extract <fileinfo> <streamdetails> over FTP

### ISSUE THREAD

**Issue by Paelsmoessan** [xbmc/xbmc#20578]
### Describe the bug
Here is a clear and concise description of what the problem is:

Fileinfo/Streamdetails are not extracted over FTP, works over SMB and VPN

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Make it at least an option to extract this info over FTP.

## Actual Behavior

No media-info is extracted over FTP. 

## Possible Fix

Extract the file media-info or have an option to read local .nfo for it. 

### To Reproduce

1.  Try any FTP setup with any scraper. 
2.
3.

### Debuglog

The debuglog can be found here:
N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment]
Correct, you need to explicitly enable this using advancedsettings.xml . See https://kodi.wiki/view/Advancedsettings.xml#ftp . Please use forum first, next time.

**Comment by Paelsmoessan** [comment]
Do I need to recreate the whole library or should it work on refresh? 
Because no streamdetails (flags) are being extracted.

**Comment by arnova** [comment]
You probably have auto extraction disabled in your settings. Please use forum for further user questions.

**Comment by Paelsmoessan** [comment]
Sorry to bug you guys again, but the only flag extracted is Play-Time of movies, using TMDB scraper or TMDB Python scraper. The Universal Movie scraper does not scrape even that. 

Should I address this issue to the scrapers instead?
