### ISSUE TITLE
Kodi 19.3 new install on Pi4 all 4 CPU's at 100%

### ISSUE THREAD

**Issue by jbreda007** [xbmc/xbmc#20580]
### Describe the bug
Here is a clear and concise description of what the problem is:

I installed Kodi 19 on a raspberry pi 4 with 4gb memory.  Prior to installing Kodi 19 all 4 CPU's were idling at about 1%.  After installing Kodi 19.3 with no add-ons all 4 CPU's are pegged at 95-100% continuously with nothing else running.  Raspberry software is Bullseye.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please post a debug log.

Also please post the output of the threads.
```
top -H -p <kodi PID> -b -n 1
```
Where <kodi PID> is replaced with the Kodi process id. This can be found using ps or pidof.

**Comment by lrusak** [comment]
Closing as no reply and no log. We can reopen if there is actually an issue otherwise please use the forum for support.
