### ISSUE TITLE
Not able to change the resolution other than 1920x1080 on amd rx 6600 xt 

### ISSUE THREAD

**Issue by e-ru** [xbmc/xbmc#20587]
### Describe the bug
I'm using LibreElec and every time i change the resolution to something different than 1920x1080 i just see the boot image and LibreElec defaults back to 1920x1080.
This happens in the System/Settings/Display/Resolution Option and during video playback in the video options menu.

## Expected Behavior
Changing the resolution works.

## Actual Behavior
Changing the resolution leads to the boot screen image and defaults back to 1920x1080.

### To Reproduce

* Change resolution in System/Settings/Display/Resolution
or
* Change resolution in video options menu during video playback

### Debuglog

The debuglogs can be found here:
kodi logs: http://ix.io/3G3z
modetest logs: http://ix.io/3G3A

### Additional Info
This is the issue i posted on the libreElec project: https://github.com/LibreELEC/LibreELEC.tv/issues/5918

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux - LibreElec nightly 20211024-73f3241
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC (community): nightly-20211124-7ef3241
 - Kodi version:  Kodi (20.0-ALPHA1 (19.90.101) Git:08b7599d63e063545e34a24bb17fc3738cd4dde7). Platform: Linux x86 64-bit
 - Hardware: x86-64, cpu: intel 11400, gpu: rx 6600 xt

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Please ask your support questions on the forum.

This section is for actual bug reports, not for users experiencing problems and requesting assistance.

Thanks
