### ISSUE TITLE
SysfsPath: read multiline

### ISSUE THREAD

**Issue by Portisch** [xbmc/xbmc#20594]
### Describe the bug
Here is a clear and concise description of what the problem is:
As mentioned in #17289 no multiline is supported. If possible CoreELEC want to use this function instead the obsolete SysfsUtils to read multiline sysfs strings.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
All data by `Get` should be read. Currently it is not possible to read multiple lines as only first line will be read. Doesn't matter if you call it multiple times.

## Actual Behavior
`getline` or `file >> value;` do read only a single line and stop reading on first line break found.

## Possible Fix

1. Set `std::ifstream file(m_path);` to `static std::ifstream file(m_path);`
Then the user can call `Get` multiple times and get on every call the next line if available. But the user get no information about EOF.

2. Use `std::string value(std::istreambuf_iterator<char>(file), {});` instead `  std::string value; std::getline(file, value);`
Then whole data is read by `char` into the string var and the user have all data in one call and can handle it by himself.
But he also maybe get a line ending if it's included in one line only.

So both have pro and contra.

### To Reproduce
Read a multi line sysfs entry.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi Nexus nightly (master branch)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
All the data should get read in one call.

Please submit a PR. Please include tests.

**Comment by Portisch** [comment]
NP, will do a PR later. Thx
