### ISSUE TITLE
Selecting add-on source twice crashes kodi

### ISSUE THREAD

**Issue by Admin-A-LLC** [xbmc/xbmc#20608]
### Describe the bug
Here is a clear and concise description of what the problem is:

When selecting to install a zip file as an add-on installation source for a single installation works fine, if you go back to the same source to install a 2nd zip file, Kodi crashes. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expected behavior is for it to perform as the first install and proceed to install the zip file.

## Actual Behavior

Application ceases to respond and windows reports an unresponsive app.

### To Reproduce

1.  Simply add a url source into kodi file sources and select it to install a zip file. The source should have two diffrent files to install as add-ons.
3.

### Debuglog

The debuglog can be found here:

https://pastebin.com/AuxJhBpa

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10/11
 - Kodi version: 19.03 (19.02)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@Admin-A-LLC 

Sorry we can not look at your issue as you are  jammed packed full of banned addons.
The cause of your issue is most likely one or more of those repo/addons you have installed.

If you can replicate the issue on a completely fresh installation, testing with a non-banned repo, then please post back.

The Moderators have determined that [Banned_addons](https://kodi.wiki/view/Banned_addons) are present on your system. To receive assistance here, these banned items must be removed.

**Comment by KarellenX** [comment]
Try this one... https://www.matthuisman.nz/2020/02/slyguy-kodi-repository.html

Do you need a second one, or does it crash using the same URL twice?

**Comment by Admin-A-LLC** [comment]
Sorry for the late reply. But yes, it only happens when using the same url source twice. I install an add-on, which typically installs fine, but then I'll go back to that same source, and it hangs immediately after pressing enter to open the source url again.

**Comment by howie-f** [comment]
sorry, i can't look into this unless you start over with a clean install, no banned repos.

> Try this one... https://www.matthuisman.nz/2020/02/slyguy-kodi-repository.html

if you can reproduce with only this repo installed, besides the official, then please provide that debuglog. thanks
