### ISSUE TITLE
Xfce fractional scaling leads to wrong fullscreen view

### ISSUE THREAD

**Issue by funkymaster** [xbmc/xbmc#20610]
### Describe the bug
Here is a clear and concise description of what the problem is:

If fractional scaling is set up in the display settings, the Kodi screen view is cropped or too small.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should adjust to the correct display settings.

## Actual Behavior

Kodi is running in fullscreen mode, but Kodi scales the displayed view wrong.
It is impossible to navigate to the rightmost or bottom with values < 1. (Keyboard arrow keys)

### To Reproduce

1. Activate fractional scaling in the display settings. Values <> 1 must be used. E.g. 0,8 or 1,5.
2. Open Kodi
3.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/7624884/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Settings:
![image](https://user-images.githubusercontent.com/21222589/144027189-edba497a-8db2-4769-9930-48fec5eb5634.png)

Fullscreen view with a setting of 0,8:
![image](https://user-images.githubusercontent.com/21222589/144028733-0db4488b-d046-485a-92bc-4569d79c1c70.png)

Fullscreen view with a setting of 1,5:
![image](https://user-images.githubusercontent.com/21222589/144031160-035fea88-5465-4550-9814-bbb37a9b36ff.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian testing/Bookworm x86_64, Xfce 4.16
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
While I can reproduce this, I think this mode is super weird. It renders the whole desktop at a lower/higher resolution and up-/downscales it linearly. That's definitely not something you would want for a video playback program. The image quality would be horrendous. Even more so for Kodi, as UI elements are sized independently of the resolution. The position/scaling would be the same for all scale factors.

The whole setting is really buggy. Super Tux Kart (as my reference) had some weird behavior too as I've tried to change the resolution. At one point it forced me to reboot, as the screen would be filled with garbage.

My advice: either use the windowed mode if you can live with sub-par image quality or toggle the setting on start/exit. Maybe even create a separate user account with no scaling.

I guess a proper fix would be to set the scaling to 1x when in fullscreen, restoring it on exit (https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/X11/XRandR.h). But I'm not optimistic that someone attends to such a fringe case.

**Comment by funkymaster** [comment]
Thank you for your reply.

Ok, but what else should someone do if the content is generally too big or too small and the computer is not only used for multimedia/Kodi?

On Windows you would also set everything larger or smaller: https://support.microsoft.com/en-us/windows/change-the-size-of-text-in-windows-10-1d5830c3-eee3-8eaa-836b-abcc37d99b9a

This is the equivalent setting for Xfce and for me all other applications work with this setting without any problems.

I don't know exactly how the setting works, but I'm not suggesting that the content should be qualitatively changed because of it. The components would only have to adapt dynamically in terms of size and position. Please correct me if I am wrong.

**Comment by funkymaster** [comment]
I found a solution now.
I changed the scaling back to 1 and use a custom DPI setting in "Appearance" now.
This seems to work for me.
Thx!

**Comment by sarbes** [comment]
You can also use "Window Scaling" (Appearance->Settings) to enlarge UI elements. But both methods are fine if it is working for you, as they render at native monitor resolution.

I do like Xfce (I'm using it on my workstation with 2 27" 4k screens), but I think Gnome and KDE are better when it comes to scaling. But that's enough off topic :).

**Comment by funkymaster** [comment]
Thanks for the info, but the setting does not have the desired effect as it only affects parts of the desktop environment and the factor 2 is way too much.

Sure, every DE has its pros and cons. ;-)
