### ISSUE TITLE
19.3.0: failed to load addon settings from special://profile/addon_data

### ISSUE THREAD

**Issue by jcollum** [xbmc/xbmc#20626]
I reported a bug in the Backup addon, the author says the issue is with Kodi. Bug report: https://github.com/robweber/xbmcbackup/issues/206

I'm posting it here because the dev of xbmcbackup closed the ticket, saying it's a Kodi problem. It looks like the add on is trying to load addon settings from `special://profile/addon_data/script.xbmcbackup/settings.xml`. Has this directory been changed or something since 18? 

**Describe the problem**
When I change the settings and go back in to the settings to change something all of the settings have reverted to default 

**Platform and Kodi version**
Linux Mint 20.2, Kodi 19.3.0 

**Link to Debug Log**
I tried to upload the debug log but all I got on the paste site was "Something went wrong!". I see something in the logs about failed to load addon settings from special://profile/addon_data/script.xbmcbackup/settings.xml. Looks like it's expecting a directory that doesn't exist. I installed Kodi 19 fresh this morning [when I wrote up the bug report].

**Comment by enen92** [comment]
This sounds like permission issues in your ~/.kodi/userdata/addon_data folder. You don't provide any log and you didn't respect the issue template. I'll close this.

**Comment by jcollum** [comment]
I mentioned in the initial issue that when I tried to upload the logs it
failed.

What do I need to set the permissions to? If Cody is running fine but this
plugin is having a permissions issue isn't that a issue with the plugin?

**Comment by enen92** [comment]
No, as the log uploader also failed as it needs to access the same directory. This is likely a problem with your setup/installation, please use the forum for general support
