### ISSUE TITLE
Kodi crashes when enter into a FTP directory

### ISSUE THREAD

**Issue by Foolar** [xbmc/xbmc#20622]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a seedbox with some videos on it, I added it to my videos source since a while and everything used to work fine, but since I downloaded the new windows 64-bit kodi version, kodi crashes every time I enter that directory.
I can enter it, it shows the files into, but it freezes and crashes in the second after.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Not crash when I enter my FTP directory.

## Actual Behavior

Crash when enter into a FTP directory

### To Reproduce

1. Configure an FTP directory as a video source
2. Access it with Home -> video -> Files or with the shortcut
3. It freezes and crashes.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/wulituxeqo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Windows

 - Operating system version/name:
 - Kodi version:
19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Foolar** [comment]
Here's the complete crashlog : https://www.mediafire.com/file/6cwitjvwol94b6n/Logs.zip/file

**Comment by chewitt** [comment]
> I have a seedbox with some videos on it

Your piracy problem is not our problem then.

**Comment by Foolar** [comment]
I didn't expect such a stupid answer. 
Seedbox are legal. And the problem could happen with another FTP directory.
Closing the ticket just because you read "seedbox" is completly idiot.

**Comment by Foolar** [comment]
@chewitt Saying seedboxes are piracy is as stupid as saying that kodi is piracy.

But whatever, if you don't care about your product crashes, I will use another solution.
