### ISSUE TITLE
Python: plugin VFS path is inserted into sys.path list on each plugin call

### ISSUE THREAD

**Issue by romanvm** [xbmc/xbmc#20623]
### Describe the bug
Here is a clear and concise description of what the problem is:

When a plugin (a Python scraper in my case but I think it's not limited to scrapers) is run multiple times a plugin VFS path `plugin://x.y.z` is inserted int `sys.path` list on each plugin call.

Here's `sys.path` contents after several runs:
```python
['plugin://metadata.tvshows.thetvdb.com.v4.python',
  'plugin://metadata.tvshows.thetvdb.com.v4.python',
  'plugin://metadata.tvshows.thetvdb.com.v4.python',
  'plugin://metadata.tvshows.thetvdb.com.v4.python',
  'plugin://metadata.tvshows.thetvdb.com.v4.python',
  'plugin://metadata.tvshows.thetvdb.com.v4.python',
  'plugin://metadata.tvshows.thetvdb.com.v4.python',
  'plugin://metadata.tvshows.thetvdb.com.v4.python',
  'plugin://metadata.tvshows.thetvdb.com.v4.python',
  'plugin://metadata.tvshows.thetvdb.com.v4.python',
  'plugin://metadata.tvshows.thetvdb.com.v4.python',
  'plugin://metadata.tvshows.thetvdb.com.v4.python',
  'plugin://metadata.tvshows.thetvdb.com.v4.python',
  'plugin://metadata.tvshows.thetvdb.com.v4.python',
  '/home/roman/.var/app/tv.kodi.Kodi/data/addons/metadata.tvshows.thetvdb.com.v4.python',
  '/usr/lib/python39.zip',
  '/usr/lib/python3.9',
  '/usr/lib/python3.9/lib-dynload',
  '/usr/lib/python3.9/site-packages',
  '/app/lib/python3.9/site-packages']
```
In case of a Python TV scraper that scans a very big media library this may lead to a serious memory leak because it's called for each episode.

I believe it's connected to using `<reuselanguageinvoker>true</reuselanguageinvoker>`. - _confirmed_.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

A plugin VFS path is not inserted into `sys.path`.

## Actual Behavior

See above.

## Possible Fix

?

### To Reproduce

1. Enable `reuselanguageinvoker` in your plugin.
2. Add logging of `sys.path` to your plugin code.
3.. Run your plugin multiple times.

### Debuglog
https://paste.kodi.tv/paqugizonu.kodi As you can see, `sys.path` increases on each call of the new TVDB TV scraper.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
i have tried with an addon, and i can confirm that every time you browse the addon will be added another path line
like this (see lines starts with `...plugin:\\plugin.video.test\\directory\\*****`):

```
['D:\\KodiPortable_Builded_20\\plugin:\\plugin.video.test\\directory\\show\\80211991\\season\\80226954',
 'D:\\KodiPortable_Builded_20\\plugin:\\plugin.video.test\\directory\\show\\80211991',
 'D:\\KodiPortable_Builded_20\\plugin:\\plugin.video.test\\directory\\show\\80211991\\season\\80212200',
 'D:\\KodiPortable_Builded_20\\plugin:\\plugin.video.test\\directory\\show\\80211991', 
 'D:\\KodiPortable_Builded_20\\plugin:\\plugin.video.test\\directory\\video_list_sorted\\myList\\queue', 
 'D:\\KodiPortable_Builded_20\\plugin:\\plugin.video.test\\directory\\home', 
 'D:\\KodiPortable_Builded_20\\portable_data\\addons\\plugin.video.test\\packages', 
 'D:\\KodiPortable_Builded_20\\plugin:\\plugin.video.test', 
 'D:\\KodiPortable_Builded_20\\portable_data\\addons\\plugin.video.test', 
 'D:\\KodiPortable_Builded_20\\addons\\script.module.pycryptodome\\lib', 
 'D:\\KodiPortable_Builded_20\\portable_data\\addons\\script.module.addon.signals\\lib', 
 'D:\\KodiPortable_Builded_20\\portable_data\\addons\\script.module.inputstreamhelper\\lib', 
 'D:\\KodiPortable_Builded_20\\portable_data\\addons\\script.module.myconnpy\\lib', 
 'D:\\KodiPortable_Builded_20\\system\\python\\Lib', 'D:\\KodiPortable_Builded_20\\python3.8.zip', 
 'D:\\KodiPortable_Builded_20\\system\\python\\DLLs', 'D:\\KodiPortable_Builded_20', 
 'D:\\KodiPortable_Builded_20\\system\\python', 'D:\\KodiPortable_Builded_20\\system\\python\\lib\\site-packages']
```

**Comment by romanvm** [comment]
I confirm that this happens when reuselanguageinvoker is enabled. With this parameter disabled a `plugin://` path is inserted only once that still makes no sense. But I haven't found a place where it's inserted yet.

**Comment by lrusak** [comment]
Looks like we should be using this. https://docs.python.org/3.7/library/sys.html#sys.argv with `updatepath = 0`

**Comment by matthuisman** [comment]
im looking into this now - if I can get windows to compile

my first suspect is the issue is here:
https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/generic/ScriptInvocationManager.cpp#L286

we need to either
1) dont insert if already present or
2) remove our path from m_scriptPaths here: https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/generic/ScriptInvocationManager.cpp#L204
eg

```
    if (m_lastInvokerThread->Reuseable(script))
    {
      CLog::Log(LOGDEBUG, "{} - Reusing LanguageInvokerThread {} for script {}", __FUNCTION__,
                m_lastInvokerThread->GetId(), script);
      m_scriptPaths.erase(std::make_pair(script, m_lastInvokerThread->GetId()));
      m_lastInvokerThread->GetInvoker()->Reset();
      return m_lastInvokerThread->GetInvoker();
    }
```
(maybe check its in there first for sanity but it should be if its already been used)

**Comment by matthuisman** [comment]
@lrusak 
you were spot on, tried the changes and works perfectly.
No more plugin:// paths in the sys.path.

sys.path keeps as intended and identical to what is logged with "setting the Python path"

also confirmed switching to other addons and back all keep the correct sys.path

Did you want to do a PR?

**Comment by matthuisman** [comment]
yes :)
the log also confirms it as I get the log message ""setting the Python path" only on the first call into the addon

**Comment by lrusak** [comment]
> yes :)
> 

Awesome! Thanks for confirming. Feel free to PR it if you have time.

**Comment by matthuisman** [comment]
great, will do now :)

**Comment by romanvm** [comment]
Thanks for looking into this.
