### ISSUE TITLE
Kodi 19.2 master lock activated: libraries become empty (PlexKodiConnect  issue #1718)

### ISSUE THREAD

**Issue by BartOon** [xbmc/xbmc#20630]
### Describe the bug
Here is a clear and concise description of what the problem is:

I use PlexKodiConnect and when I enable masterlock passcode, libraries become empty.
If it's not set with the fresh install, or if I disable and disconnect and reconnect, libraries are ok
![image](https://user-images.githubusercontent.com/3241239/144730042-d4f5b5a8-7130-4ecc-a7aa-471d2c649e30.png)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Have librairies not empty with the masterlock passcode enable

## Actual Behavior

As soon I enable masterlock, librairies become emtpy

## Possible Fix

For now, disable the masterlock with Kodi 19.3, or rollback with 19.1, within working well

### To Reproduce

1. Go to Movie or TV show and see everything good
2. Go to in wheel > Profiles > Profiles > Master user > Lock Preferences > Master lock > Numeric password, I set one and I let all lock options by default
3. Go to Movie or TV show and see all empty
4. Go to in wheel > Profiles > Profiles > Master user > Lock Preferences > Master lock > disable
5. Disconnect and reconnect as master user
6. Go back to Movie or TV show and see back to normal

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/7578722/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/3241239/144730042-d4f5b5a8-7130-4ecc-a7aa-471d2c649e30.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

If you need more detail, some tests and comment from the addon developper is here; https://github.com/croneter/PlexKodiConnect/issues/1718

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 21H2
 - Kodi version: 19.3 problematic version, I rollback to 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Can't reproduce this on Nexus.

**Comment by enen92** [comment]
Plexkodiconnect changes too many "private" files it should not touch. Unless you can provide a way to reproduce this with a fresh kodi install and without addons (strm files with plugin:// paths is okay) I doubt anyone will care to look into this.

**Comment by croneter** [comment]
@enen92 PKC saves `plugin://` paths to the Kodi database - that's exactly the issue. It worked fine up till Kodi version 19.1, but broke with 19.2/19.3.
