### ISSUE TITLE
Black screen with video playback by using inputstream.adaptive with LineageOS (Kodi 19.3)

### ISSUE THREAD

**Issue by werimail** [xbmc/xbmc#20639]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'am using Kodi 19.3 (Matrix) with LineageOS running on Raspberry Pi 400 with Android 11.0.0 (API level 30). When I Start using Addons the widevine encryption the Inputstream Adaptive only plays the sound but no picture. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Addons which use widevine also output a picture in addition to the sound

## Actual Behavior

When I Start using Addons the widevine encryption the Inputstream Adaptive on Kodi 19.3 with LineageOS only plays the sound but no picture.

## Possible Fix

A possible theory of the cause is that getCodecCount not work anymore, because has been deprecated on API 21.

### To Reproduce

1. Start Kodi-Addon (DAZN, Tvnow, ...) for encrypted videos via inputstream adaptive plugin
2. Start playing stream

### Debuglog

The debuglog can be found here:
[kodi_debug.log](https://github.com/xbmc/xbmc/files/7660686/kodi_debug.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

unavailable

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

after log line:
CDVDVideoCodecAndroidMediaCodec::Open: Secure decoder requested: false (stream flags: 0)
is missing the codec testing, in your case should appears like:
CDVDVideoCodecAndroidMediaCodec::Open Testing codec: OMX.google.h264.decoder
and then fails with:
CDVDVideoCodecAndroidMediaCodec:: Failed to create Android MediaCodec

According to [CastagnaIT](https://github.com/CastagnaIT) feedback, this is where the problem lies in the code:(https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp#L664-L750)

For further information also looking at (https://github.com/xbmc/inputstream.adaptive/issues/771#issue-961565492)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LineageOS 18.1 based on Android for Raspberry Pi 400
 - Kodi version: 19.3 (Matrix)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.

Greetings Weri

**Comment by CastagnaIT** [comment]
You have not opened the issue in right way, you have to fullfill the issue template: https://github.com/xbmc/xbmc/issues/new/choose
Please edit this or close it and open a new one by using the template, and the log must not be pasted as text

**Comment by werimail** [comment]
Thanks CastagnaIT for the hint. I have revised the issue accordingly. I hope this now fits into the required structure
Greetings Weri

**Comment by CastagnaIT** [comment]
well done so that other maintainers can understand

**Comment by CastagnaIT** [comment]
this should be fixed by #21421
unfortunately i am no able to provide you with a test build
but i can tell you when there is a nightly build ready

**Comment by werimail** [comment]
That sounds good @CastagnaIT. Will the nightly build be made for Kodi 19.x (Matrix) or 20 (Nexus)? Greeting Weri

**Comment by CastagnaIT** [comment]
v20 only i dont think will be allowed a backport

**Comment by joseluismarti** [comment]
Can you test [kodiapp-arm64-v8a-PR21421_ALL_CODECS.apk](https://drive.google.com/file/d/1i364u6GTERvKkNfImy9fX8ZiF9wmHHBS/view?usp=sharing) to see if it produces any improvement?

**Comment by werimail** [comment]
Hi @joseluismarti jose, i already tested with the (https://drive.google.com/file/d/1s_x3DCD0KqHGQlHIR4zQ8r3tzFG75fe1/view?usp=sharing) version and it worked very well. Thanks and regards werimail
