### ISSUE TITLE
Bug in Aeon Nox Skin or Kodi?

### ISSUE THREAD

**Issue by 5p0ng3b0b** [xbmc/xbmc#20648]
I think I found a bug (kodi 19.3 Aeon Nox: SILVO ).
When I go into Addon Browser/Manager and select 'Install from zip file', I get a warning message.
![kodiwarning](https://user-images.githubusercontent.com/12113595/145262476-77a539e9-1ba7-4001-9247-a3ecaf953f0b.png)
If I make 'Install from zip file' a favourite, and select it from the favourite menu, I get the warning message.
If I add this favourite to the add-ons submenu in aeon nox skin via main menu customizer, and later select it, it does not work.
When I look at the 'favourites.xml', the shortcut is 'installfromzip'. When I look what gets copied into the action, it is 'installfromzip,return)' and looks odd.
So if I just add custom action as 'installfromzip' all works as expected from the submenu.
I don't know if this is a bug in Aeon Nox skin or Kodi itself but it is a bug nonetheless when adding this favourite to the submenu.
Replicated in Windows and Android.

**Comment by howie-f** [comment]
i can confirm this on linux

**Comment by DaVukovic** [comment]
@5p0ng3b0b Did you ever reported it to the skin author? I would say it's a skin issue. The skin author might not read it if you report it here. 

So best would be to report it here as well, if you haven't already: https://forum.kodi.tv/showthread.php?tid=210069

**Comment by enen92** [comment]
This is a bug in skin.shortcuts and not related to kodi core. Sent a fix in the PR linked above.
