### ISSUE TITLE
Can not see picture from a NFS share with the Picture Slideshow Screensaver

### ISSUE THREAD

**Issue by screensaverproblem** [xbmc/xbmc#20649]
### Describe the bug
Here is a clear and concise description of what the problem is:

Can not see picture from a NFS share with the Picture Slideshow Screensaver

I use a NFS version 3 (nfs4 has not functioned) share 192.168.1.15/nfsv4_export/LVfotos_hourly0 with a many folders (folder name 2001, 2002, ... 2021, sub folder 01,02 ...,12 ).  With the menu point pictures in the main menu I can see all the pictures in all folders and sub folders without problems. 
But when I like use the same NFS share in the settings from the add-on screensaver.picture.slideshow (source from the slide show -> picture folder), then I became an error "Please make sure that the selected folder is writable and that the new folder name is valid"
Also when I select a sub folder , then I became the same error.

I would appreciate any hint, if other people had success use the  Picture Slideshow Screensaver withe a NFS share and here give a short about this comment.
Must I keep something a special setting for the NFS share?
- debug log and screen shots was create (pretty much in the same time for the timestamp /  screen shots picture sequenz)

PS: In my second kodi 18.9.0 installation with libreelec 9.2.8 on a raspberry pi 3 can I use the "Picture Slideshow Screensaver" without problems with the same NFS share.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I select in the settings from the add-on screensaver.picture.slideshow  the folder from the NFS share and close the menu point wihthout a error.

## Actual Behavior

When I like use a NFS share in the settings from the add-on screensaver.picture.slideshow (source from the slide show -> picture folder), then I became an error "Please make sure that the selected folder is writable and that the new folder name is valid"
Also when I select a sub folder , then I became the same error.

### To Reproduce

1. The error is the same after three reboots.
2. I use a NFS version 3 (nfs4 has not functioned) share 192.168.1.15/nfsv4_export/LVfotos_hourly0 with a many folders (folder name 2001, 2002, ... 2021, sub folder 01,02 ...,12 ).  With the menu point pictures in the main menu I can see all the pictures in all folders and sub folders without problems. 
But when I like use the same NFS share in the settings from the add-on screensaver.picture.slideshow (source from the slide show -> picture folder), then I became an error "Please make sure that the selected folder is writable and that the new folder name is valid"
Also when I select a sub folder , then I became the same error.

I would appreciate any hint, if other people had success use the  Picture Slideshow Screensaver withe a NFS share and here give a short about this comment.
Must I keep something a special setting for the NFS share?
- debug log and screen shots was create (pretty much in the same time for the timestamp /  screen shots picture sequenz)

PS: in my second kodi 18.9.0 installation with libreelec 9.2.8 on a raspberry pi 3 can I use the "Picture Slideshow Screensaver" without problems with the same NFS share.

### Debuglog

The debuglog can be found here:
[kodi_log1.txt](https://github.com/xbmc/xbmc/files/7686343/kodi_log1.txt)
The first log is saved in the screen saver before the first NFS mount use (but with successful use of the NFS share to look at pictures), the second log is saved in the screen saver after the mount attempt.
[kodi_log.txt](https://github.com/xbmc/xbmc/files/7686335/kodi_log.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![screenshot00011-0](https://user-images.githubusercontent.com/95862473/145423200-4e20f542-f8d5-4a94-9275-ce2d22dd45e3.png)
![screenshot00011-1](https://user-images.githubusercontent.com/95862473/145423218-dfc2f124-6823-4bd4-b64f-5477bed74197.png)
![screenshot00011-2](https://user-images.githubusercontent.com/95862473/145423255-a9653ea5-a3df-4148-be5b-952cab9f47f3.png)
![screenshot00011-3](https://user-images.githubusercontent.com/95862473/145423270-50db976b-8095-47a5-be38-f82b55515218.png)
![screenshot00011-4](https://user-images.githubusercontent.com/95862473/145423280-e03bd429-a84c-4999-9e2c-b82a071007a9.png)
![screenshot00011-5](https://user-images.githubusercontent.com/95862473/145423293-9c6c3faf-07c7-46d5-8733-e04ddcc176bd.png)
![screenshot00011-6](https://user-images.githubusercontent.com/95862473/145423299-a77141a8-3
![screenshot00011-7](https://user-images.githubusercontent.com/95862473/145423317-97dd765f-1b2b-4779-a040-8c907d3a0cd0.png)
d29-4d85-8c0f-69512b7019c0.png)
![screenshot00011-8](https://user-images.githubusercontent.com/95862473/145423336-cffab9ad-a11e-4f65-b960-85e36e6a25af.png)
![screenshot00011-9](https://user-images.githubusercontent.com/95862473/145423357-8d9402ab-4a3a-4773-807b-9fe57c2e6e78.png)
![screenshot00011-10](https://user-images.githubusercontent.com/95862473/145423367-33873354-0ec2-4a95-88ad-29d64a2e6045.png)
![screenshot00011-11](https://user-images.githubusercontent.com/95862473/145424029-62c0d84d-d6df-4a8c-b31d-db4ad0663c48.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: fresh image  LibreELEC-RK3328.arm-10.0.1-r from https://releases.libreelec.tv/LibreELEC-RK3328.arm-10.0.1-rock64.img.gz
 - Kodi version: 19.3
 - Hardeware: PINE64/ ROCK64   8 core 4 GB
 - LE 10.0.1
 - Picture Slideshow Screensaver 6.3.3
 - NFS v.3 : Connected to server 192.168.1.15 and export /nfsv4_export/LVfotos_hourly0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
This repo is only used to track Kodi core bugs not add-ons. Please contact the add-on maintainer / report to the respective add-on repo : https://gitlab.com/ronie/screensaver.picture.slideshow. Might have to do with the add-on not using xbmcvfs.translatePath

Thanks

**Comment by screensaverproblem** [comment]
Thanks for this information.
