### ISSUE TITLE
.apng badly rendered, since Nexus alpha

### ISSUE THREAD

**Issue by marduklev** [xbmc/xbmc#20657]
### Describe the bug
Here is a clear and concise description of what the problem is:

skin gui related.
.apng images are badly 'rendered', 
causing the apng to flicker.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

.apng images are normally 'rendered' (working in krypton,leia,matrix applications)

video link 

## Actual Behavior

.apng images are badly 'rendered', 
causing the apng to flicker.

## Possible Fix

No,idea. Sorry

### To Reproduce

1. place .apg to akin dir (im my case skin.name\extras\*.apng)  
        - sources: 
              https://github.com/marduklev/skin.swan-alpha/tree/master/extras/busy
              https://github.com/mgonzales71/resource.images.busyspinners.titan-krypton/tree/master/resources

2. load them via image control, best case for test and reproduce is maybe a custom test window
for test .
use an image control with apng in texture tag (unsure how many skins use apn format in skin, if i recall right skin.embuary do so, which is avail in official repo )
```
 best case is creating a test window, in that case id custom_1145_apng.xml 
<?xml version="1.0" encoding="UTF-8"?>
<window id="1145">
	<controls>
	<control type="image">
		<texture colordiffuse="ff181818">colors/white.png</texture>
	</control>
	
	<control type="image">
		<centertop>25%</centertop>
		<centerleft>25%</centerleft>
		<width>300</width>
		<height>300</height>
		<texture colordiffuse="ffffffff">special://skin/extras/busy/busyload3.apng</texture>
		<aspectratio align="center">keep</aspectratio>
	</control>
	<control type="image">
		<centertop>75%</centertop>
		<centerleft>25%</centerleft>
		<width>300</width>
		<height>300</height>
		<texture colordiffuse="ffffffff">special://skin/extras/busy/busyload2.apng</texture>
		<aspectratio align="center">keep</aspectratio>
	</control>
	<control type="image">
		<centertop>25%</centertop>
		<centerleft>75%</centerleft>
		<width>300</width>
		<height>300</height>
		<texture colordiffuse="FFA71B6A">special://skin/extras/busy/netflixorigin.apng</texture>
		<aspectratio align="center">keep</aspectratio>
	</control>
	<control type="image">
		<centertop>75%</centertop>
		<centerleft>75%</centerleft>
		<width>300</width>
		<height>300</height>
		<texture colordiffuse="FFF57F17">special://skin/extras/busy/skypishball.apng</texture>
		<aspectratio align="center">keep</aspectratio>
	</control>
	
	</controls>
</window>
```

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/aviqudabol.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

MATRIX: VIDEO https://streamable.com/17s1r4

NEXUS: VIDEO https://streamable.com/3hofdq

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 21H2, kernel: Windows NT x86 64-bit version 10.0.22000.348
 - Kodi version: Git:20211201-cbc97ce5bf

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by peat80** [comment]
I'm using skin.embuary and can confirm that the busy skinner from this skin (which uses the .apng-format) does indeed flicker on nexus. On matrix it works fine.

**Comment by marduklev** [comment]
i justn found out it is ffmpeg related, thoug still unsure what has changed which causing that

https://github.com/xbmc/xbmc/commits/master/xbmc/guilib/FFmpegImage.cpp

**Comment by marduklev** [comment]
seems fixed a while back, all fine now!
