### ISSUE TITLE
Kodi constantly writes an error to the log file due to a problematic CEC device

### ISSUE THREAD

**Issue by ReWiG** [xbmc/xbmc#20656]
### Describe the bug
Here is a clear and concise description of what the problem is:

The log shows the same error every few seconds 

> ERROR <general>: OpenConnection - could not opening a connection to the CEC adapter

And I want to say right away that controlling Kodi using the TV remote works great. I use one of the two HDMI ports to connect my TV and everything works great.

I have installed the latest Raspberry Pi OS (Bullseye) on my Raspberry Pi 4B (which has only 2 HDMI ports). I am using the latest vc4-kms-v3d display driver.
```
uname -a

Linux pikodi 5.10.83-v7l+ #1499 SMP Tue Dec 7 14:08:09 GMT 2021 armv7l GNU/Linux

```

I have libcec 6.0.2 library installed from the official repository of my operating system
I have Kodi 19.3-1~bullseye installed from the official repository of my operating system

For some reason, my system detects 3 CEC devices, 2 of them correspond to two HDMI ports, and the third is unknown, does not even have a COM port.
Here is the output of the `cec-client -l` command

>   libCEC version: 6.0.2, compiled on Linux-5.10.63-v7l+ ... , features: P8_USB, DRM, P8_detect, randr, RPi, Exynos, Linux, AOCEC
>     ERROR: [ 3543] error opening serial port '': No such file or directory
>     ERROR: [ 3544] could not open a connection (try 1)
>     ERROR: [ 6379] error opening serial port '': No such file or directory
>     ERROR: [ 6379] could not open a connection (try 2)
>     ERROR: [ 8269] error opening serial port '': No such file or directory
>     ERROR: [ 8269] could not open a connection (try 3)
>     ERROR: [ 9529] error opening serial port '': No such file or directory
>     ERROR: [ 9529] could not open a connection (try 4)
>     Found devices: 3
>     device: 1
>     com port: /dev/cec0
>     vendor id: 0000
>     product id: 0000
>     firmware version: 0
>     type: Linux
>     device: 2
>     com port: /dev/cec1
>     vendor id: 0000
>     product id: 0000
>     firmware version: 0
>     type: Linux
>     device: 3
>     com port:
>     vendor id: 0000
>     product id: 0000
>     firmware version: 65535

For comparison, here is the output of `cec-ctl --list-devices`

>  vc4_hdmi (vc4):
>     /dev/cec0
>     /dev/cec1
>     Driver Info:
>     Driver Name : vc4_hdmi
>     Adapter Name : vc4
>     Capabilities : 0x0000011e
>     Logical Addresses
>     Transmit
>     Passthrough
>     Remote Control Support
>     Connector Info
>     Driver version : 5.10.83
>     Available Logical Addresses: 1
>     DRM Connector Info : card 1, connector 32
>     Physical Address : 2.0.0.0
>     Logical Address Mask : 0x0002
>     CEC Version : 1.4
>     Vendor ID : 0x001582 (Pulse-Eight)
>     OSD Name : ''
>     Logical Addresses : 1 (Allow Fallback to Unregistered)
>     Logical Address : 1 (Recording Device 1)
>     Primary Device Type : Record
>     Logical Address Type : Record

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I think that the code should check the availability of the COM port and if it is not specified / does not exist, then do not try to connect to it and not write a bunch of errors to the log file 

## Actual Behavior

Kodi tries to connect to a CEC device without a COM port and cannot do it, writes an error to the log file 

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/7692874/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![IMG_20211210_160529](https://user-images.githubusercontent.com/5054805/145578656-d5e4282e-797e-4eef-bc8c-80b180abbc0b.jpg)
The third device with a strange firmware number is problematic 

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ X ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 
Raspberry Pi OS (Bullseye)
Linux pikodi 5.10.83-v7l+ # 1499 SMP Tue Dec 7 14:08:09 GMT 2021 armv7l GNU/Linux
 - Kodi version: 19.3-1~bullseye

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by alanswanson** [comment]
Looks to be Pulse-Eight/libcec#584 so try updating to latest rpi firmware.

**Comment by ReWiG** [comment]
Thanks, there really solved this problem
