### ISSUE TITLE
Blu-ray disc is not played but probed as DVD media only. 

### ISSUE THREAD

**Issue by gebim** [xbmc/xbmc#20672]
### Describe the bug
Blu-ray discs are not played but the disc symbol appears after inserting the Blu-ray disc. It is not an issue due to decryption as all necessary libraries and the keyfile are installed.  The disc plays in VLC including the java menus.

Attached is the log file. A fresh profile without any extensions installed was used. 

## Expected Behavior
The Blu-ray disc should be played and/or a menu on how to play the disc should appear after inserting. 

## Actual Behavior

Disc is ignored or not recognized as Blu-ray media. In the attached log in 
line 744: click on the disc symbol: 2021-12-13 22:43:09.983 T:9532     INFO <general>: Detecting DVD-ROM media filesystem...
line 745: 2021-12-13 22:43:10.017 T:9532    ERROR <general>: Detection of DVD-ROM media failed.

Looks like that Kodi just probes for DVD and not for Blu-ray media. Wrong media type? 

## Possible Fix

This Blu-ray disc was playing in Kodi prior to version 18.

### To Reproduce

1. Start Kodi.
2. Insert Blu-ray disc.
3. Select the disc symbol.
4. Nothing happens.
4. Eject. 

### Debuglog

The debuglog can be found here: 
https://pastebin.com/02dgm2jD

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 21.10
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
In case you are using Ubuntu GNOME you could try to install udisks and also make sure you have set the mount options to "defaults setting for user session" at the drive settings at gnome-disks-settings. All that is explained here already: 

https://github.com/xbmc/xbmc/issues/20048

That should probably help solving your problem. 

Which also means, that this issue is a duplicate ;). Please continue the discussion at the other issue.

**Comment by enen92** [comment]
@DaVukovic looking again a bit more to this it seems we have an undocumented advanced setting `handlemounting` that is used solely by the udisks and udisks2 providers (on linux) that will attempt to automount drives (including optical) once they are detected. This advancedsetting is enabled by default if Kodi is running in standalone mode (`kodi-standalone.sh` or passing `--standalone` to the kodi.bin) so it should solve part of the problem.

No idea why it was designed this way though (came from svn import - origin 12 years ago)  ¯\_( )_/¯
Maybe we can think of ways to improve this, doesn't seem logical optical discs are shown in the interface and users are forced to mount them manually outside of the application. If you have any ideas let me know

**Comment by gebim** [comment]
Thanks for these insights and Yes - disc playback needs more love from the developers.
I played a bit around with DVD and BD disks. Here is what I observed:
DVD: Works in 19.3 with some problems. a.) disk is not mounted. Start kodi-standalone. As the disk is inserted a DVD-video file dialog pops up. Cancel this one. Select the Disc symbol and press play. Playing and eject works :+1: 
BD disc: start kodi-standalone and insert BD disc. File dialog pops up. Cancel this dialog and select the disc symbol. Select play. Does not play and eject does not work - broken...
BUT: start kodi-standalone and not cancel the File dialog. Navigating to 'browse files' and enter the BDMV dir. Selecting the index.bdmv file finally opens a 'select playback item' menu. Select the menu item 'Show Blu-ray menu' plays the BD disc with all the bells and whistles...:D

Obviously, all this is not end-user-friendly. Especially Kodi should be independent on the underlying Desktop environment and the mounting handling therein. Maybe the way VLC does it is much more simple. It directly accesses the drive over /dev/cdrom. Right?
BTW: as an end user I just can hope, that some of you smart developers give the disc-handling an overhaul.
In that context I'd like to mention this thread in the makemkv forum (I know that is a bit off-topic):
https://forum.makemkv.com/forum/viewtopic.php?p=61541#p61541
the way how kodi opens a BD disc is discussed...

thanks

**Comment by enen92** [comment]
As for the file dialog opening that's a known issue in Linux if you have "play discs automatically enabled" see https://github.com/xbmc/xbmc/issues/19237 (apparently it's there for a long time).

I cant help with Bluray discs though I don't even own a BD drive.

**Comment by enen92** [comment]
@gebim fyi:
https://github.com/xbmc/xbmc/pull/20840
https://github.com/xbmc/xbmc/pull/20846

**Comment by gebim** [comment]
Thanks a lot enen92 for your hard work. 
Just build from master and I can confirm the automounting for DVD`s works :+1:  and play nicely. Sadly eject does not work. Do we use udisk for the unmounting? 
```
./kodi-wayland
libva info: VA-API version 1.12.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_12
libva info: va_openDriver() returns 0
umount: /mnt/usb-PIONEER_BD-RW_BDR-XD05_1958041720900272-0:0: must be superuser to unmount.
```

**Comment by enen92** [comment]
Kodi uses libcdio to eject discs, which will basically exec umount (https://github.com/Distrotech/libcdio/blob/806566a6fd894eb408b4cbcfe4eaa82ec8a81796/lib/driver/gnu_linux.c#L672). You might have something wrong with your system/distro configuration, umount has setuid bit set (which means it will be executed as root)

**Comment by gebim** [comment]
correct...will have a closer look on my ubuntu 21.10 box. 

Here just to mention my case:

`umount: /mnt/usb-PIONEER_BD-RW_BDR-XD05_1958041720900272-0:0: must be superuser to unmount.` and  the setuid bit is set `-rwsr-xr-x 1 root root 35200 Sep 23 16:07 /usr/bin/umount`

I need sudo or udisk to umount:

```
/dev/sr0 on /mnt/usb-PIONEER_BD-RW_BDR-XD05_1958041720900272-0:0 type udf (ro,nosuid,nodev,relatime,iocharset=utf8,x-gvfs-show)
gebi@gebi-tablet:~/bin/xbmc/kodi$ udisksctl unmount -b /dev/sr0
Unmounted /dev/sr0
```

**Comment by enen92** [comment]
Hum it could be that when we mount the dvd/br we are missing some option (e.g. user). Can you check and post the output of `mount` after inserting a dvd/br while Kodi is open (so that is Kodi mounting the disc)?

**Comment by enen92** [comment]
In my case:

```
/dev/sr0 on /run/media/arch/CASS type udf (ro,nosuid,nodev,relatime,uid=1000,gid=1000,iocharset=utf8,uhelper=udisks2)
```

As you can see, kodi/udisks is mounting the drive with uid and gid of the user running kodi. [These come from the defaults:](http://storaged.org/doc/udisks2-api/latest/mount_options.html)

```
iso9660_defaults=uid=$UID,gid=$GID,iocharset=utf8,mode=0400,dmode=0500
iso9660_allow=uid=$UID,gid=$GID,norock,nojoliet,iocharset,mode,dmode
```

Please check the contents of `/etc/udisks2/mount_options.conf`. In my case this file does not exist, so udisks is using the defaults.

**Comment by gebim** [comment]
sorry for the late reply - busy times. eject still makes problems. Starting Kodi (build from master today) - inserting DVD - eject button:
```
gebi@gebi-tablet:~/bin/xbmc/kodi$ ./kodi.bin 
libva info: VA-API version 1.12.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_12
libva info: va_openDriver() returns 0
umount: /mnt/usb-PIONEER_BD-RW_BDR-XD05_1958041720900272-0:0: must be superuser to unmount.
```
mounting work perfectly and `mount` gives: `/dev/sr0 on /mnt/usb-PIONEER_BD-RW_BDR-XD05_1958041720900272-0:0 type udf (ro,nosuid,nodev,relatime,iocharset=utf8,x-gvfs-show)`
But for unmounting needs sudo or `udisksctl unmount -b /dev/sr0`. After umount the eject in kodi opens the tray. Sticky bit is set for mount: `-rwsr-xr-x 1 root root 43392 Sep 23 16:07 /usr/bin/mount`
 I also created the file `/etc/udisks2/mount_options.conf` with the options from the example file:
```
iso9660_defaults=uid=$UID,gid=$GID,iocharset=utf8,mode=0400,dmode=0500
iso9660_allow=uid=$UID,gid=$GID,norock,nojoliet,iocharset,mode,dmode
udf_defaults=uid=$UID,gid=$GID,iocharset=utf8
udf_allow=uid=$UID,gid=$GID,iocharset,utf8,umask,mode,dmode,unhide,undelete
```
For reasons I do not know, the UID/GID is not in the mount options (did a prior reboot)...very strange.
May I have to play with the udev rules - bummer.
What do you think? As udisks works perfectly fine, shouldn't it be used for the unmounting too?

**Comment by enen92** [comment]
I have no idea, but your mount options seem odd. Are you sure it's kodi/udisks mounting your drive? If so it should have a comment `uhelper=udisks2` when you list your mountpoints.
In your case you have `x-gvfs-show` which is suspicious. Are you sure you did not change any configuration in gnome disks and that you don't have any entry in fstab or some udev rule for your drive?

**Comment by gebim** [comment]
Thanks - it is working now :1st_place_medal: I did a reset of gnome to the defaults `dconf reset -f /org/gnome/` and mount gives now:
 ```/dev/sr0 on /media/gebi/DVD_VIDEO type udf (ro,nosuid,nodev,relatime,uid=1000,gid=1000,iocharset=utf8,uhelper=udisks2)```
as it should be.
IMHO: Nexus is shaping up nicely;-

**Comment by enen92** [comment]
Glad you got it sorted :)
Enjoy
