### ISSUE TITLE
Subtitles only show for files in Movies/TV Show database, not when played through Video/Files browser

### ISSUE THREAD

**Issue by mattiaswerner** [xbmc/xbmc#20670]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi doesn't render the subtitles for files when accessed through the "Video --> Files" or "Video --> Media Sources" browser. Same file accessed through a "Movies" or "TV Shows" category renders subtitles just fine.

## Expected Behavior

When navigating to a mkv file with embedded subtitles through the Video category (or filebrowser) and press to play the file. Either using the gui navigation or yatze mobile app, enable subtitles. See rendered subtitles over the video.

## Actual Behavior

Video plays without rendering subtitles.

### To Reproduce

1. Use any .mkv file with embedded subtitles, confirm working subtitles.
2. Navigate to the same file using the "Video --> Files" browser and play.
3. Try to enable and see rendered subtitles.

### Debuglog

No debug log for this issue

### Screenshots 

No screenshots for this issue

## Additional context or screenshots (if appropriate)

I discovered this by attempting to play downloaded videos from youtube with embedded subtitles. Discovered the issue affected files I knew were working. I could've sworn that this used to work in the past.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.3 (19.3.0) Git:20211024-49a04cd6a7
 - OS: Ubuntu Server 20.04.3 LTS x86_64 
 - Host: ProLiant MicroServer Gen8 
 - Kernel: 5.11.0-41-generic 
 - CPU: Intel i3-3220 (4) @ 3.300GHz 
 - GPU: NVIDIA GeForce GT 720 Driver Version: 470.86
 - Memory: 1474MiB / 7905MiB

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
I could not replicate your issue using a Windows 10 setup and v19.3

I have an mkv file with pgs subtitles.
I played the file via Movies and the embedded "forced" subtitles played as expected.
I navigated to Videos>Files>Source>Movie file and played again. The "forced" subtitles played as expected.

**Comment by mattiaswerner** [comment]
> I could not replicate your issue using a Windows 10 setup and v19.3
> 
> I have an mkv file with pgs subtitles. I played the file via Movies and the embedded "forced" subtitles played as expected. I navigated to Videos>Files>Source>Movie file and played again. The "forced" subtitles played as expected.

Thanks for testing. I can't say for certain when this started being an issue as seldom play things outside the library on my htpc. Though I'm definitely positive that it used to work in my setup.

**Comment by DaVukovic** [comment]
I guess we can close this. There won´t be any update anymore and therefor we won´t see a log
