### ISSUE TITLE
Kodi consuming CPU every 20 seconds in idle mode while trying to connect to a cec device, leading raspberry pi to an increase the CPU rate from 700MHz to 1800MHz every 20 seconds

### ISSUE THREAD

**Issue by akmail** [xbmc/xbmc#20686]
### Describe the bug
Here is a clear and concise description of what the problem is:

not clear what CEC device kodi is trying to connect to, high cpu load while idle every 20 seconds
- ll /dev/cec*
  0 crw-rw---- 1 root video 235, 0 Dec 14 22:50 /dev/cec0
  0 crw-rw---- 1 root video 235, 1 Dec 14 22:50 /dev/cec1
- in kodi there are 3 CEC adapters under Settings -> System -> Input -> Peripherals
- Setup:
Argon M.2 Case (no ssd part attached, Raspbian Bullseye runs on an SD card, latest updates installed as of Dec 2021)
Setup: Kodi Raspberry Pi 4b latest version, 1.8Ghz, 4GB RAM
HDMI 1 -> Yamaha AV Receiver -> (Acer Projector, LG BluRay Player, Fire TV, not attached HDMI Cable)
While starting up Kodi says that CEC connected successfully to "Yamaha, Acer" and then complains about CEC not being connected (showing message "please check your settings")

possible reasons: USB? Bluetooth? Argon Infrared built in into that case?

the log entries say:
2021-12-14 23:48:42.801 T:14574    INFO <general>: Register - new cec device registered on cec->/dev/cec0: CEC Adapter (0000:0000)
2021-12-14 23:48:42.803 T:14574    INFO <general>: Register - new cec device registered on cec->/dev/cec1: CEC Adapter (0000:0000)
2021-12-14 23:48:42.811 T:14574    INFO <general>: Register - new cec device registered on cec->: CEC Adapter (0000:0000)

2021-12-15 10:19:44.802 T:14590   ERROR <general>: OpenConnection - could not opening a connection to the CEC adapter
2021-12-15 10:20:05.296 T:14590   ERROR <general>: OpenConnection - could not opening a connection to the CEC adapter
2021-12-15 10:20:25.790 T:14590   ERROR <general>: OpenConnection - could not opening a connection to the CEC adapter
2021-12-15 10:20:46.284 T:14590   ERROR <general>: OpenConnection - could not opening a connection to the CEC adapter
2021-12-15 10:21:06.778 T:14590   ERROR <general>: OpenConnection - could not opening a connection to the CEC adapter
2021-12-15 10:21:27.272 T:14590   ERROR <general>: OpenConnection - could not opening a connection to the CEC adapter
2021-12-15 10:21:47.766 T:14590   ERROR <general>: OpenConnection - could not opening a connection to the CEC adapter

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No third CEC device / CPU consumption caused by polling every 20 seconds

## Actual Behavior

[kodi.log](https://github.com/xbmc/xbmc/files/7718000/kodi.log)
[cec_CEC_Adapter.txt](https://github.com/xbmc/xbmc/files/7718004/cec_CEC_Adapter.txt)
[kodi.log](https://github.com/xbmc/xbmc/files/7718006/kodi.log)
not clear why there are three CEC adapters in kodi settings, which one is failing, also CPU is being used a lot, every 20 seconds.

## Possible Fix

- fix the wording "could not opening a connection"
- change the error message to clearly state which device is failing
- kodi startup error popup - state which device is failing and point where are the corresponding settings
- consider re-designing the ui settings for CEC adapters - there is just one xml settings file, but 3 CEC entries in KODI
- at least change the behavior to not poll the device every 20 seconds, but fall back to e.g. every 10 minutes if i's been not available for a while.
  e.g. 5 min -> fall back to polling every minute, 15 min -> fall back to every 3 minutes, 1hr: every 5 min, 12hr: every 10 min, 24 hr: every 30 min

### To Reproduce

start kodi 19.3 on a raspberry pi 4 4GB, 1.8GHz, Argon M.2 Case with SD card. Check the logs

### Debuglog

The debuglog can be found here:
see attachment

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by alanswanson** [comment]
Looks to be https://github.com/Pulse-Eight/libcec/issues/584 so try updating to latest rpi firmware.

**Comment by popcornmix** [comment]
Needs patched libcec library too.

**Comment by akmail** [comment]
many thanks! after upgrading the firmware and patching the cec lib, the third device disappered and the problem has gone of course too. closing...
