### ISSUE TITLE
Kodi 20: DVB subtitles position

### ISSUE THREAD

**Issue by Dis90** [xbmc/xbmc#20729]
### Describe the bug
Here is a clear and concise description of what the problem is:
Sometimes DVB subtitles aren't displayed correctly.

Both lines in example picture should be leveled to left. Instead second lines starts different position than first line. Kodi 19 and VLC displays subtitles correctly.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/7780400/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Kodi 19:
<img width="1182" alt="Kodi 19" src="https://user-images.githubusercontent.com/1754572/147477422-242a5d20-9036-4ca8-8def-24cce94c2ec7.png">

Kodi 20:
<img width="1177" alt="Kodi 20" src="https://user-images.githubusercontent.com/1754572/147477441-0916c363-e099-4015-87aa-fde5f07195be.png">

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [x] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@Dis90 any change you can provide a short video sample that illustrates the issue?

**Comment by Dis90** [comment]
Sure. Here's 5 min clip of same video used in screenshots. https://drive.google.com/file/d/1iK5SSIcwrE9AIbkZoRHoLrcOSr-MDNzM/view?usp=sharing

**Comment by enen92** [comment]
@CastagnaIT maybe you can take a look at this? Should be an easy fix

**Comment by CastagnaIT** [comment]
i have lost 3 hours without find nothing useful in code i have no idea

**Comment by CastagnaIT** [comment]
i have noticed that if put video in pause and you resize the window to the source res sub size (576x720 if i remember correctly) the text become correct
so i suspected something in the scale calculation i have tried change in different ways without success

**Comment by CastagnaIT** [comment]
I have done other tests, i think to be close to the solution so the problem seem around the scale,
the text now seem aligned correctly also after resizing kodi window:
![immagine](https://user-images.githubusercontent.com/3257156/147969681-494dd342-c7ba-4965-9c86-931bcb1f15e5.png)
but now is not centred correctly and i do not understand where is the mistake
if you want try it this is my changes: https://github.com/CastagnaIT/xbmc/commit/80dd84f11cca699cbcd9d990199924c3a6a804fc
maybe you see where i am wrong

in addition to the test file provided above suggest to test also with the PGS sample that you can find in the FTP directory:
/Samples_new/Subtitles/PGS/PGS_StretchingTest.mkv
this is good to verify that the subs are displayed centred correctly

**Comment by Dis90** [comment]
Looking your screenshot I think subtitles are in correct place. It is very common at least here in Finland that DVB subtitles are aligned to left instead of center.

**Comment by CastagnaIT** [comment]
i think to have found the solution
i will try to prepare a PR

**Comment by enen92** [comment]
Fixed by https://github.com/xbmc/xbmc/pull/20794

**Comment by Dis90** [comment]
@CastagnaIT I updated to latest Kodi 20 and this issue is happening again.

**Comment by Dis90** [comment]
@enen92 Sorry for bumping this but should I open new issue?

**Comment by enen92** [comment]
@Dis90 is this a fallback from a recent subtitles PR or is it still broken right after https://github.com/xbmc/xbmc/pull/20794 has been merged?

**Comment by Dis90** [comment]
@enen92 I tested with builds from here http://mirrors.kodi.tv/nightlies/osx/x86_64/master/
Subtitles are working correctly in `kodi-20220325-4734091c-master-25035-x86_64.dmg` but not in `kodi-20220327-f0125d68-master-25058-x86_64.dmg` So I'm pretty sure that PR #21162 is causing this problem.

**Comment by CastagnaIT** [comment]
sorry i lost the message notification tag on hundreds of emails
your sample have 4/3 subtitles resolution on a 16/9 video resolution, that's why now doesn't work
maybe we should allow this "mix" use case to use ALIGN_VIDEO in some way
