### ISSUE TITLE
DVD Menu not highlighted

### ISSUE THREAD

**Issue by hufnala** [xbmc/xbmc#20737]
### Describe the bug

Hi, I'm using KODI 19.3 (compiled 2021-10-24 by GCC 10.3.0 for Linux ARM 32-bit version 4.9.113 (264561))
and playing a DVD the menu is shown fine, but the menu items are not highlighted to select them. 1st of all I thought it
is a YATSE remote topic, but the same behavior with mouse.
Control with mouse is so far possible when you see the cursor, but not in YATSE where no mouse cursor is visbile.

## Expected Behavior
Selected Menu Item is highlighted with a colored frame, different kind of picture e.g. on "mouseover"

## Actual Behavior
Nothing happens on "mouseover" to menu entry.

## Possible Fix
Don't know, found some related issue a couple of releases ago, but nothing new.

### To Reproduce

1. Insert DVD
2. Start Movie, wait till menu is shown
3. Move mouse to items

### Debuglog
What kind of debug log is expected on that behavior?

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ x] Linux - COREELEC
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - KODI 19.3 (compiled 2021-10-24 by GCC 10.3.0 for Linux ARM 32-bit version 4.9.113 (264561))

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Works for me on v20 (as no changes there it should also work fine in v19), either using the mouse, keyboard, json-rpc/kore/yatse with my test dvds.

**Comment by lrusak** [comment]
if the issue exists on vanilla Kodi the issue can be reopened.
