### ISSUE TITLE
Dolby Vision files are not recognized if embed in a mkv container

### ISSUE THREAD

**Issue by guilamu** [xbmc/xbmc#20740]
### Describe the bug
Dolby Vision files are not recognized if embed in a mkv container and played as SDR files.

You can download this small file to reproduce the issue: https://send.portailpro.net/download/e34c450ba59cb290/#QThGw5hqmfE1WL6584Nl1w
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Dolby Vision should be recognized if embed in a mkv container
## Actual Behavior

Dolby Vision files embed in a mkv container are played as SDR files.
## Possible Fix

I tried to extract only the video stream with mkvtoolnix but no luck.
### To Reproduce

1. Download the file : https://send.portailpro.net/download/e34c450ba59cb290/#QThGw5hqmfE1WL6584Nl1w
2. Play.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 9
 - Kodi version: 20.x (a december 2021 release)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by quietvoid** [comment]
This is expected until FFmpeg (which Kodi uses) supports the new Matroska elements for the Dolby Vision decoder configuration.
See https://forum.kodi.tv/showthread.php?tid=360018 for an alternative.

**Comment by guilamu** [comment]
Oh, thanks, I'll be waiting for this to be fixed then. Thanks a bunch for your reply.

I wish you an amazing new year!

**Comment by cromefire** [comment]
Well kodi has to update it's FFmpeg to 5.0 first and that's still no guarantee that it'll just work, there might be additional work needed.

**Comment by quietvoid** [comment]
There is, see https://forum.kodi.tv/showthread.php?tid=360018&pid=3086227#pid3086227

**Comment by cromefire** [comment]
So this should be in the nightly already, right?

**Comment by quietvoid** [comment]
No, Nexus is still using FFmpeg 4.41.

**Comment by OBorce** [comment]
any update on this?

**Comment by fuzzard** [comment]
No

**Comment by the-black-eagle** [comment]
There is a PR (https://github.com/xbmc/FFmpeg/pull/24) that I think should fix that but doesn't seem like it has any traction :(

**Comment by guilamu** [comment]
> 

Thanks for your reply. I don't understand why this code has not been added to the main branch yet.

**Comment by KyleSanderson** [comment]
Any update on this? the fork from quietvoid and @Maven85 have very limited capabilities and still result in a black screen for some profiles.

**Comment by sscobici** [comment]
> Any update on this? the fork from quietvoid and @Maven85 have very limited capabilities and still result in a black screen for some profiles.

I had black screen issues with DV files on Maven85 builds on Ugoos AM6 Plus box, but after upgrading the firmware to 0.5.4 black screen disappear.

**Comment by zzattack** [comment]
Do the recent DV improvements carry over to non-android platforms?

**Comment by quietvoid** [comment]
@zzattack No, other platforms don't have Dolby Vision support.
Other than maybe the Xbox.
