### ISSUE TITLE
Duplicate Content-Length HTTP Header in JSON-RPC responses

### ISSUE THREAD

**Issue by kingo55** [xbmc/xbmc#20759]
### Describe the bug
Here is a clear and concise description of what the problem is:

Responses from the JSON-RPC include a duplicate `Content-Length` HTTP header that is causing some useragents to throw exceptions:

<img width="787" alt="Screen Shot 2021-12-31 at 19 14 58" src="https://user-images.githubusercontent.com/2361388/147811799-bcba7237-5fc6-4047-8553-678c7dcf58c9.png">

I am running Kodi 19.3-2 on both my Linux desktop (5.15.10) and Mac OS (20.6.0).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The JSON-RPC server should only include one `Content-Length` header in responses, like tested on Mac OS:

<img width="769" alt="Screen Shot 2021-12-31 at 19 43 14" src="https://user-images.githubusercontent.com/2361388/147813031-797ae1df-011c-40be-8caa-a2750622be3c.png">

## Actual Behavior

There are two `Content-Length` headers in the HTTP response. This breaks some useragents from using the JSON-RPC data, such as Home Assistant's Kodi integration (will see if I can grab you a traceback for that too):

<img width="787" alt="Screen Shot 2021-12-31 at 19 14 58" src="https://user-images.githubusercontent.com/2361388/147811799-bcba7237-5fc6-4047-8553-678c7dcf58c9.png">

## Possible Fix

Between these two functions, do we have a double-up of `Content-Length` Header logic?:

1. https://github.com/xbmc/xbmc/blob/a80d1293b0579bbed7dd7d20304ba34a20519f78/xbmc/utils/HttpResponse.cpp#L89
2. https://github.com/xbmc/xbmc/blob/7478f983b67dc1e3b09e061acf2eaa675b0f0170/xbmc/network/WebServer.cpp#L445

### To Reproduce

1. Running Kodi 19.3-2 on Linux (reinstalled multiple times + with empty `.kodi` directory, works fine on Mac OS)

### Debuglog

In this debug log, I accessed the webserver and confirmed it was spitting out a duplicate `Content-Length` header.

[kodi.log](https://github.com/xbmc/xbmc/files/7797418/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

```
Traceback (most recent call last):
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/aiohttp/client_proto.py", line 213, in data_received
    messages, upgraded, tail = self._parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Duplicate Content-Length'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/jsonrpc_async/jsonrpc.py", line 33, in send_message
    response = await self._request(data=message.serialize())
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 900, in start
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Duplicate Content-Length', url=URL('http://192.168.0.100:8080/jsonrpc')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/pykodi/kodi.py", line 164, in ping
    response = await self._server.JSONRPC.Ping()
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/jsonrpc_async/jsonrpc.py", line 35, in send_message
    raise TransportError('Transport Error', message, exc)
jsonrpc_base.jsonrpc.TransportError: ("Error calling method 'JSONRPC.Ping': Transport Error", ClientResponseError(RequestInfo(url=URL('http://192.168.0.100:8080/jsonrpc'), method='POST', headers=<CIMultiDictProxy('Host': '192.168.0.100:8080', 'Content-Type': 'application/json', 'Accept': 'application/json-rpc', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.9 aiohttp/3.8.1', 'Authorization': 'Basic ******', 'Content-Length': '104')>, real_url=URL('http://192.168.0.100:8080/jsonrpc')), (), status=400, message='Duplicate Content-Length'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/robertkingston/Documents/pykodi-testing/test.py", line 19, in <module>
    asyncio.run(test())
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/robertkingston/Documents/pykodi-testing/test.py", line 11, in test
    await kodi.ping()
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/pykodi/kodi.py", line 170, in ping
    raise CannotConnectError from error
pykodi.kodi.CannotConnectError
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux 5.15.10 / Arch
 - Kodi version: 19.3-2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
I can confirm the issue. It seems to me that libmicrohttp is allowing the content-length set by kodi, which happens here:

https://github.com/xbmc/xbmc/blob/7478f983b67dc1e3b09e061acf2eaa675b0f0170/xbmc/network/WebServer.cpp#L444-L453

https://github.com/xbmc/xbmc/blob/7478f983b67dc1e3b09e061acf2eaa675b0f0170/xbmc/network/WebServer.cpp#L1426-L1432

but internally it's also setting another one. At least setting a breakpoint in AddHeader only hits once.
`MHD_VERSION` is `0x00097500`.

Maybe @Karlson2k can give some help here

**Comment by enen92** [comment]
Ok so this seems to have been caused by this commit https://github.com/Karlson2k/libmicrohttpd/commit/4820d93bc91eea924dcad29e879f31d8d28649a1 on libmicrohttpd
This happened between 0.9.73 and 0.9.74, so 0.9.73 is the last tagged version where this doesn't happen.
Resolution is external to kodi though.

**Comment by kingo55** [comment]
Nice one... thanks for hunting it down @enen92!

**Comment by kingo55** [comment]
Hi @enen92 and @Karlson2k - Thanks for hearing me out about this issue. I've heard more [reports from users about this issue](https://community.home-assistant.io/t/kodi-integration-suddenly-cant-connect/373008). As Kodi updates roll out, I suspect we'll see more reports from [the Home Assistant user base (>3,500 homes)](https://www.home-assistant.io/integrations/kodi).

From what I understand, MHD now treats `Content-Length` as an automatic header:

https://github.com/Karlson2k/libmicrohttpd/blame/645b0140032d201a98f06878da8bb7ccecef9c88/src/microhttpd/response.c#L454

So, since it's automatic now, does this mean we need to remove any attempts to set this header within Kodi?

**Comment by enen92** [comment]
That's a possible approach, we can always ifdef depending on the version and avoid setting the content length but I am unsure it won't cause regressions somewhere (I don't think so but you never know). However, looking at the Kodi implementation and libmicrohttpd docs it seems we explicitly force setting the content-lenght by passing some specific properties to libmicrohttp. That being said, it should work...its really some bug on their end. 
Looking at the commit log it's not that uncommon:
https://github.com/Karlson2k/libmicrohttpd/commit/16ac89f3beb982dab4f1552ffb94e637b45ca324

**Comment by Karlson2k** [comment]
Looks like I missed this issue.
Let me clarify the how to work correctly with libmicrohttpd API.
The flag `MHD_RF_INSANITY_HEADER_CONTENT_LENGTH` must not be ever used by application unless application wants to produce non-RFC-compliant response.

The solution is very simple: just remove setting of `MHD_RF_INSANITY_HEADER_CONTENT_LENGTH` flag and remove any setting of `MHD_HTTP_HEADER_CONTENT_LENGTH`.

libmicrohttpd **always** set valid `Content-Length` header automatically. See https://github.com/Karlson2k/libmicrohttpd/blob/v0.9.75/src/include/microhttpd.h#L3882

I'll make a PR with all necessary corrections.

Please ping me by Slack for any MHD-related issues.

**Comment by Karlson2k** [comment]
For clarity: MHD **always** sets valid `Content-Length` reply headers (when such headers are needed: when response has a body, even zero-lenght body, when body size is know, and when response should contain the body). It was the same even with very old MHD version. 
There was no need ever to set `Content-Length` header manually.

**Comment by Karlson2k** [comment]
> So, since it's automatic now, does this mean we need to remove any attempts to set this header within Kodi?

This is most correct approach.
Yes, this header is and always was automatic header. 
Word "INSANITY" in `MHD_RF_INSANITY_HEADER_CONTENT_LENGT` should gives a hit that it must not be used in normal processing.

**Comment by enen92** [comment]
Thanks for popping up with a possible future fix in kodi @Karlson2k
I agree that setting the content length should be stripped from kodi if all we do is standard/RFC-compatible stuff and that it's the right path for a kodi fix. 
However, I am a bit unsure if libmicrohttpd should be generating the duplicated content-length if the consumer is enforcing `MHD_RF_INSANITY_HEADER_CONTENT_LENGT` and is already providing a content length header. Seems to me there's some room for improvement in libmicrohttp code, but that's really up to you as the main lib maintainer. As long as Kodi works, I am happy :)

**Comment by Karlson2k** [comment]
> However, I am a bit unsure if libmicrohttpd should be generating the duplicated content-length if the consumer is enforcing `MHD_RF_INSANITY_HEADER_CONTENT_LENGT` and is already providing a content length header.

Yep. On one hand, MHD always sets `Content-Length` header with number of bytes being sent in reply body. On the other hand, if application already requested `INSANITY`, maybe it worth to skip built-in header.

Probably MHD API will be extended to allow "HEAD-only" reply with arbitrary value in `Content-Length` header.
