### ISSUE TITLE
Subtitles font size setting only works for some videos

### ISSUE THREAD

**Issue by Solarunit** [xbmc/xbmc#20769]
### Describe the bug
Here is a clear and concise description of what the problem is:

Font size setting in the GUI only works for some videos with built-in internal subtitles, it doesn't work for example for Blu-Ray videos.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Font size setting should work for all videos with built-in internal subtitles, e.g. like mpv player.

## Actual Behavior

Font size setting does nothing, the font size stays the same.

## Possible Fix

Similar to mpv player subtitles handling implementation maybe.

### To Reproduce

1. Try to change font size for the Blu-ray movie. Nothing happens.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Solus
 - Kodi version: Kodi 19.3 (Flatpak)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Dvd and BR subtitles are not text based but rather texture based - hence you can't change the font size (it's not using any font). This is by design, not a bug.

**Comment by Solarunit** [comment]
Good to know, thanks. I wish Kodi will have a feature to scale those texture based subtitles as well.
