### ISSUE TITLE
Hotkeys to change subtitles font size

### ISSUE THREAD

**Issue by Solarunit** [xbmc/xbmc#20770]
### Describe the bug
Here is a clear and concise description of what the problem is:

It would be nice to have a feature to quickly change subtitles font size (on the fly) using shortcuts maybe like mpv player does it with 0.1 scale step. 

I often use MPV as external player and it can scale subs (with 0.1 step) for every video. So I use this feature very often. I guess the feature is called Sub Scale there, and it works differently than font size changing in Kodi. 
The biggest problem with Kodi player is that font size setting in the GUI only works for some videos, it doesn't work for example for Blu-Ray videos. That is why I prefer to use MPV for videos with subtitles and not Kodi built-in player.

Related issue: https://github.com/xbmc/xbmc/issues/20769

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Solus
 - Kodi version: 19.3 (Flatpak)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
This is for bug issues, not feature requests.

The forums are the correct place, which I believe you had posted about this somewhere.

**Comment by Solarunit** [comment]
Yeah, already posted on forum.
