### ISSUE TITLE
Sony Bravia tv kd-65x81j installation problem

### ISSUE THREAD

**Issue by pepbil** [xbmc/xbmc#20774]
Hi, i have a Sony Bravia tv kd-65x81j with Android 10, last firmware update, but i can't install Kodi from Google Play Store or even from Kodi official website.
App installation from unknown sources is unlocked.
What do I do?
Thank you

**Comment by KarellenX** [comment]
@pepbil 

We don't provide support here on Github. Please ask your support question on the forum.

Start a new thread in this sub-forum.... https://forum.kodi.tv/forumdisplay.php?fid=164

Thanks.
