### ISSUE TITLE
kodi-19.3-Matrix-x64.exe does not install on Windows 10, requires Windows 7 SP1 or newer

### ISSUE THREAD

**Issue by LigH-de** [xbmc/xbmc#20786]
### Describe the bug
Downloaded `kodi-19.3-Matrix-x64.exe` from https://kodi.tv/download/windows and tried to install it on Windows 10 Pro (21H2).

## Expected Behavior
Installer runs and installs kodi media server.

## Actual Behavior
```
Windows 7 SP1 or above required.
Install Service Pack 1 for Windows 7 and run setup again.
```

## Possible Fix
Is the installer not aware of Windows versions beyond 7.x?
Is it absolutely necessary to download it from the Microsoft Store instead?

### To Reproduce

1.  download `kodi-19.3-Matrix-x64.exe` from https://kodi.tv/download/windows
2.  install it on Windows 10 Pro (21H2)

### Debuglog

There can be no debug log if the installer does not even run.
[no-debug.log](https://github.com/xbmc/xbmc/files/7804510/no-debug.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Kodi_19 3_W7SP1](https://user-images.githubusercontent.com/5917225/147990277-71adcf65-314d-420c-9873-b348fa42b31e.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

![W10Pro_21H2](https://user-images.githubusercontent.com/5917225/147990423-5804ca33-ca95-4b1a-a9df-1d72aba5290f.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro (21H2)
 - Kodi version: kodi-19.3-Matrix-x64.exe

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by LigH-de** [comment]
Well, I don't know which section I accidently omitted, even after editing 3 times.

**Comment by DaVukovic** [comment]
I highly guess you've update your W10 instance from W7 and never did a fresh W10 installation afterwards, correct?

Does it help if you set the compatibility mode to W8 or W10?

* Right click on the installer exe
* select 'properties'
* under 'Compatibility mode' check 'Run this program in compatibility mode for:' and try to select W8

**Comment by LigH-de** [comment]
It was a fresh install, but with a few quirks...

W8 compatibility allows installation.
