### ISSUE TITLE
framerate keeps dropping while watching live TV

### ISSUE THREAD

**Issue by sinancetinkaya** [xbmc/xbmc#20810]
### Describe the bug

Here is a clear and concise description of what the problem is:
When playing live TV, FPS is 60 at the beginning but soon falls back to 30 fps. This causes choppy playback on the video.
I tried everything. 

- Whitelisting resolution refresh rates
- Enabling VSYNC in Nvidia control panel
- `Sync playback to display`
- `Adjust display refresh rate`
- `Render method`
- advancedsettings.xml
```xml
<advancedsettings>
	<video>
		<adjustrefreshrate>
			<override>
			  <fpsmin>29.96</fpsmin>
			  <fpsmax>30.01</fpsmax>
			  <refreshmin>59.0</refreshmin>
			  <refreshmax>61.0</refreshmax>
			</override>
			<fallback>
			  <refreshmin>50.0</refreshmin>
			  <refreshmax>60.0</refreshmax>
			</fallback>
		</adjustrefreshrate>
	</video>
</advancedsettings> 
```
- And bunch of stuff I found on the internet...
None of them worked. I ended up here so you guys can help what I'm doing wrong or tell me something I missed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Smooth Live TV playback

## Actual Behavior

Choppy Live TV playback

## Possible Fix

No idea

### To Reproduce

1. Open a Live TV channel and explore Kodi interface like channels, EPG window.
2.
3.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/7831718/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

see the green framerate counter on top right
![image](https://user-images.githubusercontent.com/2675655/148612092-671b8862-1c24-40ae-8fff-7ee918997796.png)
![image](https://user-images.githubusercontent.com/2675655/148611965-f676e247-6e1c-4ce4-9ad1-d3f99238d5df.png)
![image](https://user-images.githubusercontent.com/2675655/148612007-f1d12f06-538e-4b03-8613-3260b0628d24.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64, Nvidia GTX 750ti, AMD Ryzen 5 3600
 - Kodi version: 19, 20 all versions

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Can't replicate this issue on Linux (LibreELEC).

**Comment by sinancetinkaya** [comment]
Looks like turning off `Deinterlace method` in video settings solves the framedrop problem
