### ISSUE TITLE
Black screen on Android when refresh set to 120hz

### ISSUE THREAD

**Issue by static2601** [xbmc/xbmc#20822]
### Describe the bug
Here is a clear and concise description of what the problem is:

I am using an android device, Samsung Tab s7+ and using Kodi app. I have been using it just fine, I have heard that a lot of people were having issues with black screens when they open the app and I have discovered that the app only works for me when the refresh rate of the screen is at 60 hertz. If I have it set to 120 hertz it just gives a black screen. I don't know if this was reported already, just thought I'd report it since people seem to be having this issue for a while.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I think it should open at both refresh rates 60 and 120 hertz.

## Actual Behavior

Black screen if 120 hertz is set and works normally if 60 hertz is set.

## Possible Fix

Allowing the app to run at 120 hertz or limiting the refresh rate of the app to 60 hertz, if possible.

### To Reproduce

1. In settings, display, set motion smoothness to high(120 hz), then opening the app, black screen result.
2. Same as above but set motion smoothness to standard(60 hz), then open the app, normal result.
3.

### Debuglog

The debuglog can be found here:
n/a

### Screenshots
Here are some links or screenshots to help explain the problem:

n/a

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Opening/using the app.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 
 - Android Version: 11
 - Model: Galaxy Tab S7+
 - Model Number: SM-T970
 - Build Number: RP1A.200720.012.T970XXU2BUJ3
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Duplicate #15872
