### ISSUE TITLE
TV widget: channels of a channel group

### ISSUE THREAD

**Issue by kalle2000** [xbmc/xbmc#20824]
Dear all,

i am using Kodi 19.3 and was curious if an additional Live TV can be added (which is available via skin helper widgets as a workaround).

When selecting a new widget: "Live TV --> TV channel groups" it displays all available channel groups. Is it possible to rather select a specific channel group and et all the channels of that group (similar to last played)?

As reference: [script.skin.helper.widgets](https://github.com/kodi-community-addons/script.skin.helper.widgets/blob/master/resources/lib/pvr.py#L60)

`        # get all channel groups and create a tv channels entry for each groups
        for item in self.metadatautils.kodidb.channelgroups():
            label = "%s: %s" % (self.addon.getLocalizedString(32020), item["label"])
            widgetpath = "channels&mediatype=pvr&reload=$INFO[Window(Home).Property(widgetreload2)]"
            widgetpath += "&channelgroup=%s" % (item["channelgroupid"])
            all_items.append((label, widgetpath, "DefaultAddonPVRClient.png"))

        return self.metadatautils.process_method_on_list(create_main_entry, all_items)`

**Comment by DaVukovic** [comment]
This sounds more like a feature request and this should be submitted to our forums: 

https://forum.kodi.tv/forumdisplay.php?fid=9
