### ISSUE TITLE
Kodi crashes when I try to cast an youtube video over local network

### ISSUE THREAD

**Issue by glaubersm** [xbmc/xbmc#20839]
### Describe the bug

When I try to cast an youtube video over local network, Kodi does not react and crashes a few seconds later.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

no crash

## Actual Behavior

Kodi crashes when I try to cast an youtube video over local network

### To Reproduce

1. have two computers connected to the same network
2. install Kodi on one computer
3. open Kodi, go to Settings > Services > Control and enable "Allow remote control from applications on other systems"
and do NOT close Kodi
4. on another computer, install Cast Kodi extension in your internet browser (I use Opera browser)
https://chrome.google.com/webstore/detail/cast-kodi/gojlijimdlgjlliggedhakpefimkedmb
5. configure Cast Kodi extension to connect to Kodi installed on the first computer. Instructions from the link above:
'Then you must configure Cast Kodi Options by copying IP address of the server hosting Kodi; this information is displayed on Kodi's Settings / System information / Summary page.'
6. go to youtube and play any video
7. right click on youtube page, hover over ' Cast to Kodi' and choose 'Play now'

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ecejeferip.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux running Wayland session of KDE Plasma 5.23.5 desktop environment.
 - Kodi version: kodi 19.3-2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
` File "/usr/lib/python3.10/sqlite3/dbapi2.py", line 83, in register_adapters_and_converters`

See: https://bugs.python.org/issue46070

I'd revert to pyhon 3.9 for the moment on arch to have a stable Kodi installation for python
