### ISSUE TITLE
/usr/lib/kodi/kodi.bin: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yasindce1998** [xbmc/xbmc#20831]
### Describe the bug
I have degraded my python version 3.10 to 3.7 after that kodi is not working.
I have reinstalled it and still it's not working.
Here is a clear and concise description of what the problem is:
```
kodi
/usr/lib/kodi/kodi.bin: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ . ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Seems pretty obvious no? Your Kodi version is linked against python 3.10. If you uninstall that version you get the error you are experiencing.

If you want to downgrade python you will need to build Kodi against python 3.7.
