### ISSUE TITLE
AirPlay support is outdated (templated)

### ISSUE THREAD

**Issue by Harvie** [xbmc/xbmc#20838]
### Describe the bug
Here is a clear and concise description of what the problem is:
I've tried AirPlay support which is built in Kodi with old iphone and it turns out that even iphone 6 is too recent to work with Kodi AirPlay, because for quite some time they use "AirPlay 2". Luckily there is this UxPlay project, which seems to work almost perfectly for both audio and video mirroring, so i figured it might be interresting to integrate this with Kodi:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Screen mirroring working.

## Actual Behavior

Screen mirroring is not even detected by iphone

## Possible Fix

Integrate this: https://github.com/FDH2/UxPlay
It is really small and easy to compile once you have gstreamer libs installed, so give it a shot please.

### To Reproduce

Enable airplay, try to connect it with airplay2 device.

### Debuglog

The debuglog can be found here:
Does not apply

### Screenshots 
Here are some links or screenshots to help explain the problem:

Does not apply

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspbian
 - Kodi version: 19.3 Matrix

**Comment by lrusak** [comment]
Please use the forum to make a feature request for airplay2

**Comment by markst** [comment]
@Harvie could be of interest: https://github.com/FDH2/UxPlay/issues/55

**Comment by markst** [comment]
@Harvie because LibreElec has a add-on which supports running Docker containers. Not sure how you’re running Kodi.

**Comment by Harvie** [comment]
I run raspbian not libreelec. also kodi holds exclusive access to soundcard.
i am trying to get pulseaudio (or pipewire) running, but so far i was not succesfull in enabling concurent audio access from both kodi and uxplay.
