### ISSUE TITLE
Kodi first didn't quit anymore, then only opened with the taskbar still showing

### ISSUE THREAD

**Issue by mYnDstrEAm** [xbmc/xbmc#20834]
### Describe the bug
Here is a clear and concise description of what the problem is:

Because I proposed adding [by-default support for Documentaries (and short films)](https://forum.kodi.tv/showthread.php?tid=362894) I tried some of the proposed workarounds for non-default support to have documentaries excluded from the Movies page as well as a separate Documentaries page. After doing so (note that most people even if they know that this is possible and have the skills and time to do so will never do so), Kodi first didn't quit anymore and needed to be killed via the process manager. Now that problems was solved on its own (I don't know why it doesn't occur anymore and haven't changed much, I think this stopped even before a reboot). However, another problem appeared now: Kodi only starts in windowed mode even though fullscreen is selected in the settings (and I tried changing the settings back and forth).

What I tried is going to Settings->Skins->Configure skin->Main menu entries->Movies: adjust categories->added a rule to exclude all items with Genre "Documentary"->restarted Kodi (otherwise the rule doesn't show there as saved). I think this requires the "library node editor" addon. I'm starting Kodi with `firejail kodi` on Debian11/KDE with Wayland (note that using Wayland prevents screen tearing problems when playing videos).

The console output includes:
```
/usr/bin/kodi: 1: ulimit: error setting limit (Operation not permitted)
kodi: ulimit is unsupported by this shell
failed to open zone.tab
context.c:56: warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time

context.c:56: warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Should open in fullscreen mode.

## Actual Behavior

Opens in window mode.

### To Reproduce

1. Going to Settings->Skins->Configure skin->Main menu entries->Movies: adjust categories->added a rule to exclude all items with Genre "Documentary"->restarting Kodi (I also tried changing the filters of the Movies page but these get reset at every close of the page)
2. unknown
3. Start Kodi with firejail on Debian11/KDE

### Debuglog

The debuglog can be found here:
https://pastebin.com/mm8hxktm

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian11/KDE
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by mYnDstrEAm** [comment]
The problem occurred for a while and I tried it (quit, waited, restarted Kodi) many times. It disappeared the first Kodi start after creating this issue also for unknown reasons and without any change of the console output. It's still a problem even if it disappears for unknown reasons. But maybe you immediately see what the caused these two problems.

**Comment by wsnipex** [comment]
press "\" or start kodi with: kodi -fs

**Comment by mYnDstrEAm** [comment]
I guess this is a low importance issue as it disappeared on its own. However, the problem with the task bar reappeared now and hasn't yet disappeared. It may also have to do with creating a new smart playlist. (Or changing the main menu items of the default skin.) After creating a new smart playlist this playlist was not showing on the Videos page and only showed after restarting Kodi. It's normal the the task bard shows when I press the windows key and in this case I think it's why it first showed. But now it's still showing even after quitting Kodi (not killing the process) and starting it again. It may also have to do with KDE Plasma somehow like the task bar getting "always on top" or something like it set but that usually doesn't happen (including for Kodi).

**Comment by lrusak** [comment]
Try running Kodi without firejail

**Comment by mYnDstrEAm** [comment]
I think at some point it didn't occur again. If you have the problem of Kodi starting with the taskbar still showing you should be able to solve this by pressing **ALT GR + \** (maybe ALT+Enter works as well).

If that doesn't fix it go to "System->System->Video output->Display mode". Maybe this info should be added to some documentation in case other people have the same problem but in version 20.1 I didn't have this problem anymore.
