### ISSUE TITLE
Problem to get the KODI icon and display the ART albums.

### ISSUE THREAD

**Issue by fiasko131** [xbmc/xbmc#20845]
### Describe the bug
Hello,
I am working on an android application which is able to drive UPNP / DLNA renderers.
I am using Cling, everything is ok with Kodi except two things:

1- I can't seem to get the baseUrl that allows me to get the KODI icon. Cling returns a null baseUrl to me. The uri returned for the icon is /icon256x256.png. For the other renderers I can get the bitmap with baseUrl + iconUri.

2- When I play a song in the KODI library to KODI, the album art url is not displayed. No problem if I play from another UPNP server.

Here is a clear and concise description of what the problem is:

1-  The baseURL returned by Cling  with:
````java
device.getDetails().getBaseURL()
````
is null for KODI.
The Uri of icon returned  is : /icon256x256.png 

2- For album art issue:
it seems that the problem is the same with other apps like bubleUpnp and HIFIcast ...
An example of xml send with  AVTransport: (track on KODI library server):
````xml
<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" xmlns:sec="http://www.sec.co.kr/" xmlns:xbmc="urn:schemas-xbmc-org:metadata-1-0/">
	<item id="musicdb://albums/1/-2/1.mp3?albumid=1" parentID="musicdb://albums/1/" refID="musicdb://songs/1.mp3" restricted="1">
		<dc:title>Cocaine Man3</dc:title>
		<dc:creator>Various Artists</dc:creator>
		<upnp:artist>Baxter Dury</upnp:artist>
		<upnp:artist role="Performer">Baxter Dury</upnp:artist>
		<upnp:artist role="AlbumArtist">Various Artists</upnp:artist>
		<dc:publisher>Unknown</dc:publisher>
		<upnp:album>Floor Show</upnp:album>
		<upnp:genre>Electronic</upnp:genre>
		<upnp:albumArtURI dlna:profileID="JPEG_TN">http://192.168.0.15:1822/%25/4dbf27ff1b2385a67ab319f73258c69e/Cocaine%2520Man5.mp3</upnp:albumArtURI>
		<upnp:originalTrackNumber>7</upnp:originalTrackNumber>
		<upnp:lastPlaybackTime>2009-04-22T19:24:48-01:00</upnp:lastPlaybackTime>
		<upnp:playbackCount>0</upnp:playbackCount>
		<upnp:episodeSeason>0</upnp:episodeSeason>
		<res duration="0:03:48.000" protocolInfo="http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01500000000000000000000000000000">http://192.168.0.15:1822/%25/17e12d0edbc2f0bc1203f3317e2c3a73/Cocaine%2520Man5.mp3</res>
		<res protocolInfo="xbmc.org:*:album.thumb:*">http://192.168.0.15:1822/%25/4dbf27ff1b2385a67ab319f73258c69e/Cocaine%2520Man5.mp3</res>
		<res protocolInfo="xbmc.org:*:icon:*">http://192.168.0.15:1822/%25/bafcf9c3cb0801dc3b8c484cfbd87238/DefaultAudio.png</res>
		<xbmc:rating>0.0</xbmc:rating>
		<xbmc:artwork type="album.thumb">http://192.168.0.15:1822/%25/4dbf27ff1b2385a67ab319f73258c69e/Cocaine%2520Man5.mp3</xbmc:artwork>
		<xbmc:artwork type="icon">http://192.168.0.15:1822/%25/bafcf9c3cb0801dc3b8c484cfbd87238/DefaultAudio.png</xbmc:artwork>
		<xbmc:userrating>0</xbmc:userrating>
		<upnp:class>object.item.audioItem.musicTrack</upnp:class>
	</item>
</DIDL-Lite>
````
There is no problem when the track is broadcast on KODI as a renderer from another upnp server. The art is displayed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

1- Get the KODI icon with BaseUrl / icon 256x256.png.

2- Display ART albums on the KODI player even when the track is in the KODI library.

## Actual Behavior

none

## Possible Fix

no idea

### To Reproduce

For albums art issue:
1.  Install KODI on android TV (MI BOX s for me) and buubleUPNP on android phone.
2. Allow upnp renderer in KODI
3.  play a track in KODI librairie to KODI renederer from bubleUPNP.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

KODI on MI Box s android tv (android PIE 29)
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
For the icon problem, supposing the devicedescription.xml is http://192.168.1.178:1783/DeviceDescription.xml, the icon url will be http://192.168.1.178:1783/icon256x256.png.

**Comment by fiasko131** [comment]
Thank you for the answer.
I have actually applied this solution since.
On the other hand I always have a problem to display album art uri when
this one points to the DLNA kodi server. When the uri points to an external
DLNA server it works normally.

**Comment by fiasko131** [comment]
Ok, Thanks!

**Comment by enen92** [comment]
That should be fixed with the or linked above. Please do not close the issue until it's merged and fixed.
