### ISSUE TITLE
update to kodi-rpi-git-20.x.59385.c15319dd4e-1-armv7h.pkg.tar.xz break kodi on archlinuxarm

### ISSUE THREAD

**Issue by EricThi** [xbmc/xbmc#20847]
### Describe the bug
Here is a clear and concise description of what the problem is:

The last update available break totally kodi V20.

on my rpi4 : pacman -Syu + reboot 
at start, bottom of Kodi logo : starting migrate database (no error report)
all actions in kodi are break and mariadb too (start with error)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Back normal after update and reboot !

## Actual Behavior

Library is empty (same issue after reboot) and refresh it don't work (no action)
Kodi can't launch any file (launch directly via files) and after test to launch, service kodi restarted
Can't enter on many menu => service kodi restart after totally freeze
mariadb sort many error : 
[ERROR] Incorrect definition of table mysql.event: expected column 'definer' at position 3 to have type varchar(, found type char(141).
[ERROR] mariadbd: Event Scheduler: An error occurred when initializing system tables. Disabling the Event Scheduler.

No found any error on kodi 

I have test to revert on sqlite3 : don't work with remove on advancaedsettings.xml

## Possible Fix

Just downgrade on previous version : 
On Archlinux : 
pacman -U /var/cache/pacman/pkg/kodi-rpi-git-20.x.59260.daa7178f69-1-armv7h.pkg.tar.xz

Fixed and library is untouched, I add new file and update is done without any error

### To Reproduce

1. upgrade to kodi-rpi-git on version 59385
2. reboot
3. nothing work

### Debuglog

The debuglog can be found here:

All log are revert on november !!! yesterday, i read log on kodi.log for debug it, no extract out of my rpi (follow with tail -f :/)

### Screenshots
Here are some links or screenshots to help explain the problem:

No visual error

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Installed now :
kodi --version
Kodi Media Center 20.0-ALPHA1 (19.90.101) Git:20211231-nogitfound
Copyright (C) 2005-2021 Team Kodi - http://kodi.tv
Build : kodi-rpi-git-20.x.59260.daa7178f69-1-armv7h.pkg.tar.xz

Build revert : kodi-rpi-git-20.x.59385.c15319dd4e-1-armv7h.pkg.tar.xz

- uname -a
Linux mediacenter 5.10.90-1-rpi-ARCH #1 SMP Wed Jan 5 14:52:56 UTC 2022 armv7l GNU/Linux

- mariadb -u user -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 120
Server version: 10.6.5-MariaDB Arch Linux

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SHOW DATABASES;
+--------------------+
| Database           |
+--------------------+
| MyVideos119        |
| MyVideos120        |
| information_schema |
| mysql              |
| performance_schema |
+--------------------+
5 rows in set (0.001 sec)

Databases are based on change of V20 : 
https://kodi.wiki/view/Databases

- Last info : cat .kodi/userdata/advancedsettings.xml
```
<advancedsettings>
        <loglevel>2</loglevel>  

        <videodatabase>
                <type>mysql</type>
                <host>127.0.0.1</host>
                <port>3306</port>
                <user>user</user>
                <pass>pass</pass>
        </videodatabase> 

        <videolibrary>
                <importwatchedstate>true</importwatchedstate>
                <importresumepoint>true</importresumepoint>
        </videolibrary>

        <network>
                <curlclienttimeout>20</curlclienttimeout>  <!-- Timeout in seconds for libcurl (http/ftp) connections -->
                <curllowspeedtime>30</curllowspeedtime>    <!-- Time in seconds for libcurl to consider a connection lowspeed -->
                <curlretries>5</curlretries>               <!-- Amount of retries for certain failed libcurl operations (e.g. timeout) -->
                <disableipv6>true</disableipv6>            <!-- Certain hardware/OS combinations have trouble with ipv6. Set "true" to disable -->
                <disablehttp2>false</disablehttp2>         <!-- Added in v19- Allows disabling HTTP2 for broken Curl / HTTP2 servers -->
        </network>
</advancedsettings>
```

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by L2501** [comment]
Need to use python 3.9.9 anything newer has major issues.

**Comment by enen92** [comment]
No one from the team maintains arch (alarm) packages. This is better reported to the distro Devs..
