### ISSUE TITLE
Power saving shutdown function minimize doesn't work on Nvidia Shield

### ISSUE THREAD

**Issue by VidgetGaming** [xbmc/xbmc#20848]
### Describe the bug
Here is a clear and concise description of what the problem is:

Power saving shutdown function minimize doesn't work on Nvidia Shield

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When I go to system settings and power saving and set the shutdown function timer to 30 minues and shutdown function to minimize I expect the Kodi application to minimize after 30 minutes and return me to my Nvidia Shield home screen.

## Actual Behavior

Kodi stays open. If I choose quit instead of minimize Kodi actually quits after 30 minutes but minimize does not work.

### To Reproduce

1. Install Kodi on Nvidia Shield
2. Go to system settings and power saving
3. 2. Set the shutdown function timer to 30 minutes, although I believe the error occurs at 5 minutes too
4. 3. Set the shutdown function to minimize
5. 4. Wait 30 minutes

### Debuglog

The debuglog can be found here:
I'm sorry I don't know how to create a debug log but I've tried on 4 different Nvidia Shield devices and the problem happens on every single one.

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 11
 - Kodi version: Matrix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Our Android window system doesn't support the minimize power state so the option does nothing.

Not really if it's a bug or just an unimplemented feature.

**Comment by VidgetGaming** [comment]
> Our Android window system doesn't support the minimize power state so the option does nothing.
> 
> Not really if it's a bug or just an unimplemented feature.

I've used SPMC which was a Kodi fork and that distribution supported the minimize state. Unfortunately it's no longer being developed and I'd like to use Kodi instead but this small thing prevents me from doing so.

**Comment by DaVukovic** [comment]
>  I'd like to use Kodi instead but this small thing prevents me from doing so.

Seriously? This little thing, as you name it yourself, prevents you completely from using Kodi at all? 

Hell...what will happen if you will find a real bug? :smile:

**Comment by VidgetGaming** [comment]
> 

Yeah the room where I have it set up I need the TV to shut down after a certain period of inactivity which works with either minimize or exit but I also need to be able to get back to where I was easily since we're checking camera surveilance of a rather complex file structure and that only works when the application is minimized. If it's exited then you have to start over from the root of the tree.

https://github.com/koying/SPMC, that fork has a working minimize function for android but sadly the playback broke with android 9 and since it's no longer being developed there's very little chance of it getting fixed.

If this isn't a bug but rather a missing feature I would very much love for you to finish implementing that feature, it would help me out a lot.

**Comment by lrusak** [comment]
It would be trivial to add I think.

https://github.com/koying/SPMC/blob/beca52667112f2661204ebb42406115825512491/xbmc/windowing/egl/WinSystemEGL.cpp#L508

I'm not sure if I just missed that when I did the EGL win system breakup a while ago or if it was added later.

**Comment by VidgetGaming** [comment]
> It would be trivial to add I think.
> 
> https://github.com/koying/SPMC/blob/beca52667112f2661204ebb42406115825512491/xbmc/windowing/egl/WinSystemEGL.cpp#L508
> 
> I'm not sure if I just missed that when I did the EGL win system breakup a while ago or if it was added later.

That sounds promising. Yeah it's been in a non working state for a very long time, like 5 years or something.

**Comment by lrusak** [comment]
@thexai would you have time to implement the minimize method as show above? ^^

**Comment by thexai** [comment]
Not really, right now I'm busy fixing broken Blu-Ray menus....

**Comment by VidgetGaming** [comment]
Hello. I noticed that this didn't make it into 19.4. What are the chances that it will make it into the next version of Kodi?

**Comment by VidgetGaming** [comment]
@lrusak Hello. I noticed that this didn't make it into 19.4. What are the chances that it will make it into the next version of Kodi?
