### ISSUE TITLE
Kodi crashes on Launch with segmentation fault.

### ISSUE THREAD

**Issue by Aeres-u99** [xbmc/xbmc#20849]
## Bug report
```
/usr/bin/kodi: line 186: 28232 Segmentation fault      (core dumped) ${KODI_BINARY} $SAVED_ARGS
```
Kodi seems to be crashing with segmentation fault and neither kodi.bin nor kodi-xrandr seem to be working. 
### Describe the bug
Here is a clear and concise description of what the problem is:

Not super sure on the bug or issue, could nvidia be the problem? But if that was then kodi should have complained about a specifically missing lib. But no complains just crash 
```
>  kodi                                                                                                                       
/usr/bin/kodi: line 186: 29714 Segmentation fault      (core dumped) ${KODI_BINARY} $SAVED_ARGS
find: '/home/akuma/.cache/yay/sunshine/pkg': Permission denied
find: '/home/akuma/.cache/yay/i3lock-blur/pkg': Permission denied
find: '/home/akuma/.cache/yay/chromium-vaapi/pkg': Permission denied
find: '/home/akuma/.cache/yay/fernflower-git/pkg': Permission denied
find: '/home/akuma/NewSoftwares/MultiMC/TemporaryMC5/pkg': Permission denied
Crash report available at /home/akuma/kodi_crashlog-20220114_235306.log
# Have attached the crashlog as well.
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should launch and run or complain about a missing dependency.

## Actual Behavior

Kodi crashes with a segfault, Result upon inspection with gdb.
[GDB](https://termbin.com/3phv
)

## Possible Fix

Not sure as such. All I can see is segfaults 

### To Reproduce

1. Install kodi on archlinux with `sudo pacman -S kodi`
2. Launch
3. Observe the crash and hopes crumbling down on the screen. 

### Debuglog

The debuglog can be found here:
[kodi_crashlog-20220114_235306.log](https://termbin.com/zdxs)

### Screenshots 
Here are some links or screenshots to help explain the problem:

[Video from Installation to Crash](https://imgur.com/a/xsfO2ys)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Not sure but these are system info and other tidbits, please let me know if anything else is required.

[Hardware Specs and Other information](https://termbin.com/q3dq1)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 akuma@TsuyoiKaida 
----------------- 
* OS: Arch Linux x86_64 
* Host: Nitro AN515-57 V1.05 
* Kernel: 5.16.0-arch1-1 
* Uptime: 2 hours, 27 mins 
* Packages: 1149 (pacman) 
* Shell: zsh 5.8 
* Resolution: 1920x1080 
* WM: i3 
* Theme: Materia-dark [GTK2/3] 
* Icons: Tela-dark [GTK2/3] 
* Terminal: termite 
* Terminal Font: FuraCode Nerd Font 9 
* CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz 
* GPU: Intel TigerLake-H GT1 [UHD Graphics] 
* GPU: NVIDIA GeForce RTX 3050 Ti Mobile 
* Memory: 4103MiB / 15777MiB 
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
```
2022-01-14 23:53:03.910 T:29714    INFO <general>: GL_VENDOR = NULL
2022-01-14 23:53:03.910 T:29714    INFO <general>: GL_RENDERER = NULL
2022-01-14 23:53:03.910 T:29714    INFO <general>: GL_VERSION = NULL
2022-01-14 23:53:03.910 T:29714    INFO <general>: GL_SHADING_LANGUAGE_VERSION = NULL
```

Have you installed proper NVidia drivers?

**Comment by Aeres-u99** [comment]
I have installed the `nvidia` and `nvidia-utils` but I am still not super sure, could you please tell me the names of the packages I should search for? As a sidenote I think drivers are proper as I have been able to play the games over lutris just fine.

**Comment by DaVukovic** [comment]
As I'm not using Arch Linux I can't tell what needs to be installed or not.

I'm also not sure if the segfault is caused by that. The only thing I'm pointing is, that Kodi seems not to detect your GPU as the log shows `NULL` for that. 

Also be aware that Kodi also doesn't support Nouveau drivers. Normally, if those are used, it's also mentioned at the log. So I'm really wondering why the log says `NULL` in that case. Lutris might support that.

**Comment by Aeres-u99** [comment]
I see, that does makes sense. How can I make kodi ignore nvidia and use the other intel gpu instead? (or make kodi use nvidia, either is fine)

**Comment by Aeres-u99** [comment]
@DaVukovic any clue on this? 
```
[  +5.542289] kodi.bin[67237]: segfault at 0 ip 00007fed6b257515 sp 00007ffe2f5c77f8 error 4 in libc-2.33.so[7fed6b11d000+14b000]

```

**Comment by DaVukovic** [comment]
No, no clue. Sorry

**Comment by Aeres-u99** [comment]
@DaVukovic Sorry for the tag, but you were correct. It was a deps issue, I think I didnt had all of the vaapi drivers and vdpau drivers. Citing from archwiki for anyone else who is experiencing the same

```
Intel
Intel graphics open-source drivers support VA-API:

HD Graphics series starting from Broadwell (2014) and newer are supported by intel-media-driver.
GMA 4500 (2008) and newer GPUs, including HD Graphics up to Coffee Lake (2017) are supported by libva-intel-driver.
GMA 4500 H.264 decoding is supported by libva-intel-driver-g45-h264AUR, see Intel#Hardware accelerated H.264 decoding on GMA 4500.
Haswell refresh to Skylake VP9 decoding and Broadwell to Skylake hybrid VP8 encoding is supported by intel-hybrid-codec-driverAUR.
Skylake or later also need linux-firmware.
Also see VAAPI supported hardware and features.

NVIDIA
Nouveau open-source driver supports both VA-API and VDPAU:

GeForce 8 series and newer GPUs up until GeForce GTX 750 are supported by libva-mesa-driver and mesa-vdpau.
Requires nouveau-fwAUR firmware package, presently extracted from the NVIDIA binary driver.
NVIDIA proprietary driver supports via nvidia-utils:

VDPAU on GeForce 8 series and newer GPUs;
NVDECODE on Fermi and newer GPUs [1];
NVENCODE on Kepler and newer GPUs.
```
```
sudo pacman -S intel-media-driver libva-intel-driver
sudo pacman -S libva-mesa-driver mesa-vdpau
sudo pacman -S nvidia-utils
```
This fixes the kodi issues and the troubles. 
Thanks again for the pointer, closing the issue now.
