### ISSUE TITLE
Can't install on standard user

### ISSUE THREAD

**Issue by xmha97** [xbmc/xbmc#20857]
Hi, I can't install Kodi on the standard user.
Please make an installation for the current user/all users.
![image](https://user-images.githubusercontent.com/23485114/149637898-eb52337d-afc2-41f5-951d-4ffd8514e329.png)
![image](https://user-images.githubusercontent.com/23485114/149637918-a791a190-0516-4a8e-8ccf-ccb6742d96b4.png)
Thanks.

**Comment by lrusak** [comment]
The screenshots you posted aren't even the Kodi installer...

**Comment by xmha97** [comment]
> The screenshots you posted aren't even the Kodi installer...

This was an example installer that would be installed for both the current user and all users.
