### ISSUE TITLE
[Kodi 20] Changing Subtitles Appearance Eats up System Memory when Subtitles is showing

### ISSUE THREAD

**Issue by monsoons** [xbmc/xbmc#20861]
### Describe the bug
Here is a clear and concise description of what the problem is:

[Kodi 20] Changing subtitles appearance when subtitles's showing during video playback,
Eats up system memory approximately 3.6M for each attempt. (test result and screenshot attached below)

Through GUI or  Through JSON RPC led to the same result.

( Sorry for my ENG, I'm not native. )

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Like Kodi 19, should not affect system memory.

## Actual Behavior

All kinds of subtitles appearance changing attempt(color, opacity, bordersize, blur, etc...) affected system memory
when subtitles is displaying.
A system with low free memory like android tv box began to stutter to crash with several repeated attempts.

## Possible Fix

Sorry, I don't know.

### To Reproduce

1. play and pause video when subtitles is visible.
2. check system memory before test.
3. move to playersettings/language and change subtitles appearance repeatedly for test.
   (MAKE SURE "subtitles is still visible", 'cause some devices DO NOT overlay subtitles when GUI is showing.
   Toggle player hardware acceleration may make subtitles visible.)
4. I did test by moving slider nib. (total 1000 attempts)
5. check system memory after test. (screenshots below)

### Debuglog

The debuglog can be found here: 

### Screenshots 
Here are some links or screenshots to help explain the problem:

![S01](https://user-images.githubusercontent.com/35981015/149663617-3789b881-36b2-40f9-ac88-a730178cccd4.png)
![S02](https://user-images.githubusercontent.com/35981015/149663625-0377c094-9b97-42de-a544-afaf17bb2326.png)
![S03](https://user-images.githubusercontent.com/35981015/149663624-cd40d885-0142-4dda-87a3-8e2d1f78472e.png)

about 3.5G of free memory is gone.
(approximately 3.6M for each attempt.)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I just made python script using JSON RPC to change subtitles appearance settings(color, bordersize, blur) fast during playback,
sliders to change settings and some presets for HDR video, SDR video, Animation video, etc... 
but my NVIDIA shield tv was stuttering after several tests, and found out this is due to lack of free system memory.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 11, windows 10
 - Kodi version: Kodi 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
I can confirm and reproduce the issue. Looks like the culprit is in the call to `ass_set_fonts` but I can't provide a solution right now.
I feel like this should be only called once in initialization/configuration and not in UpdateStyle, don't remember exactly why it was done this way. Maybe @CastagnaIT remembers what style properties can be changed during runtime that requires the function call.

**Comment by CastagnaIT** [comment]
wow never noticed before
from what i remember we call `ass_set_fonts` only to allow change subtitle font while in playback (fonts placed in kodi font folders)

I do not remember exaclty i think i had problems to change the font type in the real-time to the style
I need to do some tests to verify

**Comment by enen92** [comment]
This seems to work for me while keeping the same architecture:

```
From aceee0ff926b85705fa4cbde5f119eb157e11395 Mon Sep 17 00:00:00 2001
From: enen92 <92enen@gmail.com>
Date: Mon, 17 Jan 2022 09:34:41 +0000
Subject: [PATCH] Libass: Use shared_ptr and avoid multiple calls to
 ass_set_fonts

---
 .../DVDSubtitles/DVDSubtitlesLibass.cpp       | 114 +++++++++---------
 .../DVDSubtitles/DVDSubtitlesLibass.h         |   6 +-
 2 files changed, 64 insertions(+), 56 deletions(-)

diff --git a/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp b/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp
index ff29def290..ddd9267706 100644
--- a/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp
+++ b/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp
@@ -236,7 +236,7 @@ ASS_Image* CDVDSubtitlesLibass::RenderImage(
 
   if (updateStyle || m_currentDefaultStyleId == ASS_NO_ID)
   {
-    ApplyStyle(*subStyle.get(), opts);
+    ApplyStyle(subStyle, opts);
     m_drawWithinBlackBars = subStyle->drawWithinBlackBars;
   }
 
@@ -266,18 +266,17 @@ ASS_Image* CDVDSubtitlesLibass::RenderImage(
   return ass_render_frame(m_renderer, m_track, DVD_TIME_TO_MSEC(pts), changes);
 }
 
-void CDVDSubtitlesLibass::ApplyStyle(style subStyle, renderOpts opts)
+void CDVDSubtitlesLibass::ApplyStyle(const std::shared_ptr<struct KODI::SUBTITLES::style>& subStyle,
+                                     renderOpts opts)
 {
   CLog::Log(LOGDEBUG, "{} - Start setting up the LibAss style", __FUNCTION__);
 
-  ConfigureFont((m_subtitleType == NATIVE && subStyle.assOverrideFont), subStyle.fontName);
-
   // ASS_Style is a POD struct need to be initialized with {}
   ASS_Style defaultStyle{};
   ASS_Style* style = nullptr;
 
   if (m_subtitleType == ADAPTED ||
-      (m_subtitleType == NATIVE && subStyle.assOverrideStyles != OverrideStyles::DISABLED))
+      (m_subtitleType == NATIVE && subStyle->assOverrideStyles != OverrideStyles::DISABLED))
   {
     m_currentDefaultStyleId = m_defaultKodiStyleId;
 
@@ -290,14 +289,20 @@ void CDVDSubtitlesLibass::ApplyStyle(style subStyle, renderOpts opts)
       style = &m_track->styles[m_currentDefaultStyleId];
     }
 
+    if (!style->FontName || style->FontName != subStyle->fontName)
+    {
+      bool overrideFont = m_subtitleType == NATIVE && subStyle->assOverrideFont;
+      ConfigureFont(overrideFont, subStyle->fontName);
+    }
+
     style->Name = strdup("KodiDefault");
 
     // Calculate the scale (influence ASS style properties)
     double scale = 1.0;
     int playResY;
     if (m_subtitleType == NATIVE &&
-        (subStyle.assOverrideStyles == OverrideStyles::STYLES ||
-         subStyle.assOverrideStyles == OverrideStyles::STYLES_POSITIONS))
+        (subStyle->assOverrideStyles == OverrideStyles::STYLES ||
+         subStyle->assOverrideStyles == OverrideStyles::STYLES_POSITIONS))
     {
       // With styles overridden the PlayResY will be changed to 288
       playResY = 288;
@@ -309,13 +314,13 @@ void CDVDSubtitlesLibass::ApplyStyle(style subStyle, renderOpts opts)
     }
 
     // It is mandatory set the FontName, the text is case sensitive
-    style->FontName = strdup(subStyle.fontName.c_str());
+    style->FontName = strdup(subStyle->fontName.c_str());
 
-    if (m_subtitleType != NATIVE || subStyle.assOverrideStyles != OverrideStyles::POSITIONS)
+    if (m_subtitleType != NATIVE || subStyle->assOverrideStyles != OverrideStyles::POSITIONS)
     {
       // Configure the font properties
       // FIXME: The font size need to be scaled to be shown in right PT size
-      style->FontSize = (subStyle.fontSize / 720) * playResY;
+      style->FontSize = (subStyle->fontSize / 720) * playResY;
       // Modifies the width/height of the font (1 = 100%)
       style->ScaleX = 1.0;
       style->ScaleY = 1.0;
@@ -328,14 +333,14 @@ void CDVDSubtitlesLibass::ApplyStyle(style subStyle, renderOpts opts)
       style->Encoding = ASS_FONT_ENCODING_AUTO;
 
       bool isFontBold =
-          (subStyle.fontStyle == FontStyle::BOLD || subStyle.fontStyle == FontStyle::BOLD_ITALIC);
-      bool isFontItalic =
-          (subStyle.fontStyle == FontStyle::ITALIC || subStyle.fontStyle == FontStyle::BOLD_ITALIC);
+          (subStyle->fontStyle == FontStyle::BOLD || subStyle->fontStyle == FontStyle::BOLD_ITALIC);
+      bool isFontItalic = (subStyle->fontStyle == FontStyle::ITALIC ||
+                           subStyle->fontStyle == FontStyle::BOLD_ITALIC);
       style->Bold = isFontBold * -1;
       style->Italic = isFontItalic * -1;
 
       // Compute the font color, depending on the opacity
-      COLOR::Color subColor = ConvColor(subStyle.fontColor, subStyle.fontOpacity);
+      COLOR::Color subColor = ConvColor(subStyle->fontColor, subStyle->fontOpacity);
       // Set default subtitles color
       style->PrimaryColour = subColor;
       // Set SecondaryColour may be used to prevent an onscreen collision
@@ -343,13 +348,13 @@ void CDVDSubtitlesLibass::ApplyStyle(style subStyle, renderOpts opts)
 
       // Configure the effects
       double lineSpacing = 0.0;
-      if (subStyle.borderStyle == BorderStyle::OUTLINE ||
-          subStyle.borderStyle == BorderStyle::OUTLINE_NO_SHADOW)
+      if (subStyle->borderStyle == BorderStyle::OUTLINE ||
+          subStyle->borderStyle == BorderStyle::OUTLINE_NO_SHADOW)
       {
         style->BorderStyle = ASS_BORDER_STYLE_OUTLINE;
-        style->Outline = (10.00 / 100 * subStyle.fontBorderSize) * scale;
-        style->OutlineColour = ConvColor(subStyle.fontBorderColor, subStyle.fontOpacity);
-        if (subStyle.borderStyle == BorderStyle::OUTLINE_NO_SHADOW)
+        style->Outline = (10.00 / 100 * subStyle->fontBorderSize) * scale;
+        style->OutlineColour = ConvColor(subStyle->fontBorderColor, subStyle->fontOpacity);
+        if (subStyle->borderStyle == BorderStyle::OUTLINE_NO_SHADOW)
         {
           style->BackColour = ConvColor(COLOR::NONE, 0); // Set the shadow color
           style->Shadow = 0; // Set the shadow size
@@ -357,37 +362,37 @@ void CDVDSubtitlesLibass::ApplyStyle(style subStyle, renderOpts opts)
         else
         {
           style->BackColour =
-              ConvColor(subStyle.shadowColor, subStyle.shadowOpacity); // Set the shadow color
-          style->Shadow = (10.00 / 100 * subStyle.shadowSize) * scale; // Set the shadow size
+              ConvColor(subStyle->shadowColor, subStyle->shadowOpacity); // Set the shadow color
+          style->Shadow = (10.00 / 100 * subStyle->shadowSize) * scale; // Set the shadow size
         }
       }
-      else if (subStyle.borderStyle == BorderStyle::BOX)
+      else if (subStyle->borderStyle == BorderStyle::BOX)
       {
         // This BorderStyle not support outline color/size
         style->BorderStyle = ASS_BORDER_STYLE_BOX;
         style->Outline = 4 * scale; // Space between the text and the box edges
         style->OutlineColour =
-            ConvColor(subStyle.backgroundColor,
-                      subStyle.backgroundOpacity); // Set the background border color
+            ConvColor(subStyle->backgroundColor,
+                      subStyle->backgroundOpacity); // Set the background border color
         style->BackColour =
-            ConvColor(subStyle.shadowColor, subStyle.shadowOpacity); // Set the box shadow color
-        style->Shadow = (10.00 / 100 * subStyle.shadowSize) * scale; // Set the box shadow size
+            ConvColor(subStyle->shadowColor, subStyle->shadowOpacity); // Set the box shadow color
+        style->Shadow = (10.00 / 100 * subStyle->shadowSize) * scale; // Set the box shadow size
         // By default a box overlaps the other, then we increase a bit the line spacing
         lineSpacing = 6.0;
       }
-      else if (subStyle.borderStyle == BorderStyle::SQUARE_BOX)
+      else if (subStyle->borderStyle == BorderStyle::SQUARE_BOX)
       {
         // This BorderStyle not support shadow color/size
         style->BorderStyle = ASS_BORDER_STYLE_SQUARE_BOX;
-        style->Outline = (10.00 / 100 * subStyle.fontBorderSize) * scale;
-        style->OutlineColour = ConvColor(subStyle.fontBorderColor, subStyle.fontOpacity);
-        style->BackColour = ConvColor(subStyle.backgroundColor, subStyle.backgroundOpacity);
+        style->Outline = (10.00 / 100 * subStyle->fontBorderSize) * scale;
+        style->OutlineColour = ConvColor(subStyle->fontBorderColor, subStyle->fontOpacity);
+        style->BackColour = ConvColor(subStyle->backgroundColor, subStyle->backgroundOpacity);
         style->Shadow = 4 * scale; // Space between the text and the box edges
       }
 
       ass_set_line_spacing(m_renderer, lineSpacing);
 
-      style->Blur = (10.00 / 100 * subStyle.blur);
+      style->Blur = (10.00 / 100 * subStyle->blur);
 
       double marginLR = 20;
       if (opts.horizontalAlignment != HorizontalAlignment::DISABLED)
@@ -405,21 +410,21 @@ void CDVDSubtitlesLibass::ApplyStyle(style subStyle, renderOpts opts)
       if (opts.usePosition)
         style->MarginV = 0;
       else
-        style->MarginV = static_cast<int>(subStyle.marginVertical * scale);
+        style->MarginV = static_cast<int>(subStyle->marginVertical * scale);
     }
 
     // Set the vertical alignment
-    if (subStyle.alignment == FontAlignment::TOP_LEFT ||
-        subStyle.alignment == FontAlignment::TOP_CENTER ||
-        subStyle.alignment == FontAlignment::TOP_RIGHT)
+    if (subStyle->alignment == FontAlignment::TOP_LEFT ||
+        subStyle->alignment == FontAlignment::TOP_CENTER ||
+        subStyle->alignment == FontAlignment::TOP_RIGHT)
       style->Alignment = VALIGN_TOP;
-    else if (subStyle.alignment == FontAlignment::MIDDLE_LEFT ||
-             subStyle.alignment == FontAlignment::MIDDLE_CENTER ||
-             subStyle.alignment == FontAlignment::MIDDLE_RIGHT)
+    else if (subStyle->alignment == FontAlignment::MIDDLE_LEFT ||
+             subStyle->alignment == FontAlignment::MIDDLE_CENTER ||
+             subStyle->alignment == FontAlignment::MIDDLE_RIGHT)
       style->Alignment = VALIGN_CENTER;
-    else if (subStyle.alignment == FontAlignment::SUB_LEFT ||
-             subStyle.alignment == FontAlignment::SUB_CENTER ||
-             subStyle.alignment == FontAlignment::SUB_RIGHT)
+    else if (subStyle->alignment == FontAlignment::SUB_LEFT ||
+             subStyle->alignment == FontAlignment::SUB_CENTER ||
+             subStyle->alignment == FontAlignment::SUB_RIGHT)
       style->Alignment = VALIGN_SUB;
 
     // Set the horizontal alignment, giving priority to horizontalFontAlign property when set
@@ -429,17 +434,17 @@ void CDVDSubtitlesLibass::ApplyStyle(style subStyle, renderOpts opts)
       style->Alignment |= HALIGN_CENTER;
     else if (opts.horizontalAlignment == HorizontalAlignment::RIGHT)
       style->Alignment |= HALIGN_RIGHT;
-    else if (subStyle.alignment == FontAlignment::TOP_LEFT ||
-             subStyle.alignment == FontAlignment::MIDDLE_LEFT ||
-             subStyle.alignment == FontAlignment::SUB_LEFT)
+    else if (subStyle->alignment == FontAlignment::TOP_LEFT ||
+             subStyle->alignment == FontAlignment::MIDDLE_LEFT ||
+             subStyle->alignment == FontAlignment::SUB_LEFT)
       style->Alignment |= HALIGN_LEFT;
-    else if (subStyle.alignment == FontAlignment::TOP_CENTER ||
-             subStyle.alignment == FontAlignment::MIDDLE_CENTER ||
-             subStyle.alignment == FontAlignment::SUB_CENTER)
+    else if (subStyle->alignment == FontAlignment::TOP_CENTER ||
+             subStyle->alignment == FontAlignment::MIDDLE_CENTER ||
+             subStyle->alignment == FontAlignment::SUB_CENTER)
       style->Alignment |= HALIGN_CENTER;
-    else if (subStyle.alignment == FontAlignment::TOP_RIGHT ||
-             subStyle.alignment == FontAlignment::MIDDLE_RIGHT ||
-             subStyle.alignment == FontAlignment::SUB_RIGHT)
+    else if (subStyle->alignment == FontAlignment::TOP_RIGHT ||
+             subStyle->alignment == FontAlignment::MIDDLE_RIGHT ||
+             subStyle->alignment == FontAlignment::SUB_RIGHT)
       style->Alignment |= HALIGN_RIGHT;
   }
 
@@ -450,7 +455,8 @@ void CDVDSubtitlesLibass::ApplyStyle(style subStyle, renderOpts opts)
   }
 }
 
-void CDVDSubtitlesLibass::ConfigureAssOverride(const style& subStyle, ASS_Style* style)
+void CDVDSubtitlesLibass::ConfigureAssOverride(
+    const std::shared_ptr<struct KODI::SUBTITLES::style>& subStyle, ASS_Style* style)
 {
   // Default behaviour, disable ASS embedded styles override (if has been changed)
   int stylesFlags = ASS_OVERRIDE_BIT_SELECTIVE_FONT_SCALE;
@@ -458,19 +464,19 @@ void CDVDSubtitlesLibass::ConfigureAssOverride(const style& subStyle, ASS_Style*
   if (style)
   {
     // Manage override cases with ASS embedded styles
-    if (subStyle.assOverrideStyles == OverrideStyles::STYLES)
+    if (subStyle->assOverrideStyles == OverrideStyles::STYLES)
     {
       stylesFlags = ASS_OVERRIDE_BIT_FONT_SIZE_FIELDS | ASS_OVERRIDE_BIT_FONT_NAME |
                     ASS_OVERRIDE_BIT_COLORS | ASS_OVERRIDE_BIT_ATTRIBUTES |
                     ASS_OVERRIDE_BIT_BORDER | ASS_OVERRIDE_BIT_MARGINS;
     }
-    else if (subStyle.assOverrideStyles == OverrideStyles::STYLES_POSITIONS)
+    else if (subStyle->assOverrideStyles == OverrideStyles::STYLES_POSITIONS)
     {
       stylesFlags = ASS_OVERRIDE_BIT_FONT_SIZE_FIELDS | ASS_OVERRIDE_BIT_FONT_NAME |
                     ASS_OVERRIDE_BIT_COLORS | ASS_OVERRIDE_BIT_ATTRIBUTES |
                     ASS_OVERRIDE_BIT_BORDER | ASS_OVERRIDE_BIT_MARGINS | ASS_OVERRIDE_BIT_ALIGNMENT;
     }
-    else if (subStyle.assOverrideStyles == OverrideStyles::POSITIONS)
+    else if (subStyle->assOverrideStyles == OverrideStyles::POSITIONS)
     {
       stylesFlags = ASS_OVERRIDE_BIT_ALIGNMENT;
     }
diff --git a/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h b/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h
index 49e62c11a2..3cdaaeaefa 100644
--- a/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h
+++ b/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h
@@ -144,9 +144,11 @@ protected:
 
 
 private:
-  void ConfigureAssOverride(const KODI::SUBTITLES::style& subStyle, ASS_Style* style);
+  void ConfigureAssOverride(const std::shared_ptr<struct KODI::SUBTITLES::style>& subtitleStyle,
+                            ASS_Style* style);
   void ConfigureFont(bool overrideFont, std::string fontName);
-  void ApplyStyle(KODI::SUBTITLES::style subStyle, KODI::SUBTITLES::renderOpts opts);
+  void ApplyStyle(const std::shared_ptr<struct KODI::SUBTITLES::style>& subtitleStyle,
+                  KODI::SUBTITLES::renderOpts opts);
 
   ASS_Library* m_library = nullptr;
   ASS_Track* m_track = nullptr;
-- 
2.34.1

```

It avoids calling into `ConfigureFont` if the font name doesn't change or not defined (first call). However I think `ass_set_fonts` might be leaking, the issue should likely be reported upstream

**Comment by monsoons** [comment]
Thank you for your comment. I'm not programming guy I'm so sorry I cannot give you a feedback. I hope this will be fixed in the next release.

**Comment by CastagnaIT** [comment]
yes a kind of workaround, not perfect because `ConfigureFont` wrapped by the condition `if (m_subtitleType == ADAPTED || ....` can be not always executed
but however, we are already doing some workarounds around the font handling,
begins to be a mess, i do not know, i do not like too much...
before i couldn't find anything better, but now i have a new idea to avoid all this

Current problems:
1) libass support to load fonts from 1 additional folder only (set by `ass_set_fonts_dir`), plus, is possible add 1 font fallback that can be on a different folder. But kodi have 2 additionals folders (kodi app font folder + user font folder) by default we set the user folder, then if you try to use a font from app folder, the font will not works.
2) The kodi subtitle font setting menu, show the font list (and save) the -file name- of the font. But libass `style->FontName` require the real font name, not the file name. This prevent libass to find in right way the font.

To fix these problems in the past i was add the `ConfigureFont` as workaround, to call `ass_set_fonts` at each time the font name change and by forcing fontprovider disabled to force libass load the font where we want, but with the side effect that with fontprovider disabled should not allow font fallbacks to system font provider.

This is my idea to remove the workarounds and handle the font in better way, avoid also to disable font provider:
- Remove `ConfigureFont`
- Set `ass_set_fonts` in the libass class initialization by adding "Arial" as additional font fallback from kodi app font folder
- On `ass_set_fonts_dir` we set the kodi app font folder, but if the user folder contains files we set instead the user font folder (in this way we should allow libass to use all kodi fonts as fallback, if the user not add his custom fonts)
- On `style->FontName` we have to set the real font name, in kodi we have the freetype library, in theory we can use it to retrieve the real font name from the selected file.
- On the kodi subtitle font setting list, we have to avoid load the fonts from kodi app font folder. Then we will add only the fallback "Arial" font + all the fonts in the user font folder

**Comment by monsoons** [comment]
> yes a kind of workaround, not perfect because `ConfigureFont` wrapped by the condition `if (m_subtitleType == ADAPTED || ....` can be not always executed but however, we are already doing some workarounds around the font handling, begins to be a mess, i do not know, i do not like too much... before i couldn't find anything better, but now i have a new idea to avoid all this
> 
> Current problems:
> 
> 1. libass support to load fonts from 1 additional folder only (set by `ass_set_fonts_dir`), plus, is possible add 1 font fallback that can be on a different folder. But kodi have 2 additionals folders (kodi app font folder + user font folder) by default we set the user folder, then if you try to use a font from app folder, the font will not works.
> 2. The kodi subtitle font setting menu, show the font list (and save) the -file name- of the font. But libass `style->FontName` require the real font name, not the file name. This prevent libass to find in right way the font.
> 
> To fix these problems in the past i was add the `ConfigureFont` as workaround, to call `ass_set_fonts` at each time the font name change and by forcing fontprovider disabled to force libass load the font where we want, but with the side effect that with fontprovider disabled should not allow font fallbacks to system font provider.
> 
> This is my idea to remove the workarounds and handle the font in better way, avoid also to disable font provider:
> 
> * Remove `ConfigureFont`
> * Set `ass_set_fonts` in the libass class initialization by adding "Arial" as additional font fallback from kodi app font folder
> * On `ass_set_fonts_dir` we set the kodi app font folder, but if the user folder contains files we set instead the user font folder (in this way we should allow libass to use all kodi fonts as fallback, if the user not add his custom fonts)
> * On `style->FontName` we have to set the real font name, in kodi we have the freetype library, in theory we can use it to retrieve the real font name from the selected file.
> * On the kodi subtitle font setting list, we have to avoid load the fonts from kodi app font folder. Then we will add only the fallback "Arial" font + all the fonts in the user font folder

Thank you for your comment. I hope you can fix this issue. Have a nice day.
