### ISSUE TITLE
Do not remove "media/video" Info upon re-scrape

### ISSUE THREAD

**Issue by TimerWolf** [xbmc/xbmc#20879]
### Describe the bug

When new entry is re-scraped when "video" file not exists any more the "video/media" info is removed.

## Expected Behavior

More logical would be if "video/media" information was untouched if it can't be updated,

1: If nfo-file found, try get it from there
2: If video-file found, get it from there (even if information was added from "nfo", the actually source would be honored before nfo)
3: If no new information was found, do not remove the current "video/media) information (if it exists)

## Actual Behavior

Information is removed on re-scrape, no matter if "video" file still exists or not.

## Possible Fix

Do not remove information that's not been told to be removed.

### To Reproduce

1: Scrape a video-file.
2: Get "video/media" info.
3: Delete the scraped folder from source.
4: Select the video in the video library and re-scrape it.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 19.1

**Comment by TimerWolf** [comment]
This is an error, as it was headlines that i did unneeded for this bug report.

**Comment by fuzzard** [comment]
What your asking for is a feature request. These are made on the forums.

This isn't a big, it's as designed currently. GitHub issues are for bug reports only
