### ISSUE TITLE
Kodi can't be switched to another resolution

### ISSUE THREAD

**Issue by youtehub** [xbmc/xbmc#20872]
The operating system used was Windows 10, and when switching from kodi's original installed resolution to another one, opening Kodi would flash and then disappear. When switched to the kodi installation resolution, it worked fine again.
Remember this bug was introduced in Kodi 18 and hasn't been fixed yet.
Other details added after work, machine translation, hope developers can understand.
When I get home from work, follow the bug feedback template to improve the rest of the information

**Comment by DaVukovic** [comment]
I guess you have finished work already ;)

8 days without response to fill the template is enough. 

Closed
