### ISSUE TITLE
Kodi turns black when it is turned on on a high refresh rate Android device.

### ISSUE THREAD

**Issue by shanyan-wcx** [xbmc/xbmc#20884]
### Describe the bug
Here is a clear and concise description of what the problem is:
Kodi cannot display correctly when using Android devices with a refresh rate of 120 Hz.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
It should display correctly.

## Actual Behavior
It's completely dark and can't see anything.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
Android

 - Operating system version/name:Harmony 2.0
 - Kodi version:19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Closing as duplicate https://github.com/xbmc/xbmc/issues/15872
