### ISSUE TITLE
library update

### ISSUE THREAD

**Issue by wbravin** [xbmc/xbmc#20903]
### Describe the bug
Here is a clear and concise description of what the problem is:

Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. create a new folder
2.move the episodes from old folder to new folder
3.update videos
4 go to series>seasons>and you will see ether 2 tiles for the same episode with either then same thumbnail or different thumbnail or no thumbnail 

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

none available

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

i need to spend time to remove each duplicate episode manually one at the time

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please use the forum for support.

https://forum.kodi.tv/
