### ISSUE TITLE
Trojan in the nightly build of KODI 20 for windows 64

### ISSUE THREAD

**Issue by Merzavetss** [xbmc/xbmc#20909]
installed a nightly build of KodiSetup-20220124-e60e5c24-master-x64.exe and Windows Defender found a trojan after installation.

![2022-01-27 135002](https://user-images.githubusercontent.com/98526628/151349948-b604ec2b-118a-4a05-b577-0df076113329.png)

**Comment by DaVukovic** [comment]
Yeah....pt3 (which seems to be "Puzzle TV PVR" is, AFAIK, not part of our installation. 

Closed

**Comment by da-anda** [comment]
As this file is neither part of our default installation, nor do we seem to provide it from our official repositories, there is nothing we can do about it. But please inform the responsible people from where you installed this add-on from (the authors of the add-on or the resource from where you got the zip file) that it contains a trojan. And also warn the community that might have pointed you to this add-on/repository.
