### ISSUE TITLE
Kodi v19.3 Play Next Video Automatically Causes "Browse For Subtitle" bug

### ISSUE THREAD

**Issue by cmayo1** [xbmc/xbmc#20904]
### Describe the bug
Here is a clear and concise description of what the problem is:

When Kodi v19.3 Settings->Player->Play Next Video Automatically->[Episodes|Movies] is enabled, "Browse For Subtitle" during video playback doesn't work as expected.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When Settings->Player->Play Next Video Automatically is enabled for episodes or movies, when a corresponding video is playing after having been launched from a file list, the user should be able to access Settings->Subtitle Settings->Browse For Subtitle and see a file browser where he can navigate to and select the subtitle (SRT) file appropriate to the playing video.

## Actual Behavior

When Settings->Player->Play Next Video Automatically is enabled for episodes or movies, when a corresponding episode or movie is playing after having been launched from a file list, accessing Settings->Subtitle Settings->Browse For Subtitle presents a list of episode|movie titles instead of a file browser. Selecting one of those video titles freezes Kodi 99% of the time and fails to present a subtitle 100% of the time.

This behavior doesn't occur when an episode|movie has been launched directly from the home screen via Recently Added Episodes (for episodes) or any movie poster that initiates direct playback (which is all of them, I think). But if a home screen click leads to a video browser (i.e. TV Shows/In Progress/Unwatched TV Shows), the bug will occur.

The "Play Next Video Automatically" switches for episodes and movies will cause this behavior for whichever entity (episode|movie) is enabled. For instance, if only episodes are set to play automatically, the bug will be present for episodes but not for movies.

The consequences of enabling Play Next Video for other entities (Music Videos, TV Shows, Uncategorized) has not been tested.

## Possible Fix

Kodi 17 & 18 had a related bug. If Play Next Video Automatically was enabled, a downloaded subtitle would not be saved next to the video. Whatever mechanism was responsible for moving the SRT from the temp dir to the video dir would apparently not occur successfully. That bug is not present in v19, but the bug in this problem report may be related.

### To Reproduce

1. Enable Settings->Player->Play Next Video Automatically for "Episodes" 
2. Navigate to a TV show from Home->TV Shows->[series title]->[season] and begin playback of an episode
3. During playback, access the Settings menu via the OSD and select Subtitle Settings->Browse For Subtitle
4. Instead of a file browser, you should see a list of video titles (episodes or movies, whichever is appropriate to the video in play.)
5. Clicking any video title in the list will cause Kodi to freeze and require it to be forcibly killed via Task Manager 
or pkill, etc.

### Debuglog

The debug log can be found here:

Estuary Skin (does not create a crash log)

Estuary Skin Debug log: https://pastebin.com/KJvrhXDE

Estuary Mod V2 Skin Does create crash logs, but no idea if they contain any pertinent information

Estuary Mod V2 Skin Debug log: https://pastebin.com/EtjUbPtt
Estuary Mod V2 Skin Crash Logs: https://www.dropbox.com/sh/udq4mg9wg0awtq1/AABxlYQQdmejuXahDcAdfF-na?dl=0

### Screenshots 
Here are some links or screenshots to help explain the problem:

Expected Browse For Subtitle behavior

![Working-Sub-Hierarchy](https://user-images.githubusercontent.com/4533949/151253823-0143ceb4-2965-49c0-a10f-3b6ed97ded3b.jpg)

Reported Bug Behavior

![Screenshot (1)](https://user-images.githubusercontent.com/4533949/151253819-3ad96c6d-7a90-42b8-b9ca-056f3360c789.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

This issue was documented (including screenshots) on Kodi forums; https://forum.kodi.tv/showthread.php?tid=366667&pid=3082740#pid3082740.  I have since reformatted the dual-boot PC mentioned in that post and and confirmed the bug with pure Windows and pure Linux.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X ] Linux
 - [ ] OSX
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 
 - Issue occurs on Windows 10, ElementaryOS 5 and LibreELEC (official): 10.0.1 (RPi4.arm)

 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by cmayo1** [comment]
Even with no "Play Next Video Automatically" selections, subtitles found with "Browse For Subtitles" display correctly while the video is playing, but aren't remembered after the video is stopped, but this could be by design.

**Comment by neo1973** [comment]
Confirmed fixed by the reporter: https://forum.kodi.tv/showthread.php?tid=367080&pid=3196574#pid3196574
