### ISSUE TITLE
NFS mounts are not accessible anymore on Kodi 19.3 (Android, Ubuntu 20.04)

### ISSUE THREAD

**Issue by elpraga** [xbmc/xbmc#20921]
### Describe the bug
Here is a clear and concise description of what the problem is:
I used to use NFS mount to play music and video from my server using Kodi without any problems. I have moved the server, only the IP has changed. (I have also not used Kodi for a while) Kodi 19.3 cannot access the NFS shares on server anymore. Shares can be mounted in Nautilus on the same machine. I am having the same issue with Kodi on Android and on Ubuntu. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Kodi 19.3 can see my NFS mounts as it used to.

## Actual Behavior
Kodi cannot access NFS shares after updating server IP to the new one.

## Possible Fix
No idea

### To Reproduce
1. Try to use a NFS share that used to work previously on Kodi 19.3
2.
3.

### Debuglog
Can you help me how to provide a useful log here? (both on Android and Ubuntu)

### Screenshots 
not applicable

### Your Environment
Used Operating system:
 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ x ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by tomtastic** [comment]
I'd have a look at both directory permissions and the /etc/exports on the 'new' server to help diagnose why you can no longer access it. Looks unrelated so far to issue 19749...

**Comment by elpraga** [comment]
OK. I'll post it later. The thing is that it'used to work with the exactly same configuration in '/etc/exports' before. And I can mount the shares using Nautilus on the same machine...

**Comment by elpraga** [comment]
Here are the relevant parts of `/etc/exports` 

```
"/mnt/SSD-Data/Christ Embassy - choir"  192.168.0.*(ro,all_squash,insecure)
"/mnt/SSD-Data/Music-server/01 Flamenco"        192.168.0.*(ro,all_squash,insecure)
"/mnt/SSD-Data/Practice"        192.168.0.*(ro,all_squash,insecure)
"/mnt/SSD-Data/transmission/videos"      *(ro,all_squash,insecure)
"/mnt/SSD-Data/Yoga"                    192.168.0.*(rw,all_squash,insecure)
"/mnt/SSD-Data/YouTube"                 192.168.0.*(rw,all_squash,insecure)
``` 

The IP I am accessing the shares from is within 192.168.0.* 

I repeat that those shares can be mounted without any problems in Nautilus on the same machine they are inaccessible on Kodi, that is why there is something wrong with Kodi 19.3.

**Comment by tomtastic** [comment]
Can you paste a debug log somewhere? (https://kodi.wiki/view/Log_file)

**Comment by DaVukovic** [comment]
Well...I'm using NFS since ever and I haven't had an issue accessing those shares since Kodi 17. 

a debuglog is totally mandatory in that case (as mentioned in our issue template). Please provide one.

**Comment by elpraga** [comment]
Thank you @tomtastic for the info on how to get to the logs. I did not know that, It was very helpful. 

I've not had time to provide the logs before, but there are the logs:
[kodi.log](https://github.com/xbmc/xbmc/files/8114012/kodi.log)

I have cleared the logs before starting Kodi. I've been actively trying to add one of the NFS exports (Kodi froze). I am successfully able to mount the same exports in Nautilus on the same machine.

**Comment by sashogene** [comment]
Any updates? I have the exact same problem. Kodi 19.3 on Android TV can't browse NFS. I see a list of folders but I can't read them. Nothing wrong with access permissions on the server side, and the same device can read the folders with other software than Kodi.

**Comment by elpraga** [comment]
I've given up on it and installed SAMBA

**Comment by Dnkhatri** [comment]
> Any updates? I have the exact same problem. Kodi 19.3 on Android TV can't browse NFS. I see a list of folders but I can't read them. Nothing wrong with access permissions on the server side, and the same device can read the folders with other software than Kodi.

19.4 is the latest why are you using 19.3

**Comment by daharn** [comment]
Don’t know why this was closed, I have the exact same problem since changing the ip Range of my network. Before that, it worked without issue. 

I can mount the same nfs shares on OS level, but trying to add them via the kodi interface just doesn’t do anything or freezes kodi.

**Comment by laichiaheng** [comment]
I can't do it, either.
What's wrong with KODI?
```
/srv/nfs                192.168.1.0/24(rw,sync,crossmnt,all_squash,insecure,fsid=0)
/srv/nfs/Music          192.168.1.0/24(rw,sync,nohide,all_squash,insecure)
#/srv/nfs/Videos_1TB    192.168.1.0/24(rw,sync,nohide)
/srv/nfs/Videos_2TB     192.168.1.0/24(rw,sync,nohide,all_squash,insecure)
/srv/nfs/Videos_SSD     192.168.1.0/24(rw,sync,nohide,all_squash,insecure)
~                                                                          
```
I'm on Fedora 36 now.

**Comment by daharn** [comment]
As mentioned [here](https://forum.kodi.tv/showthread.php?tid=369512&pid=3112805#pid3112805),  in my case the problem was that network share browsing didn’t work and directly adding the source only works if I don’t use symlinks.

**Comment by laichiaheng** [comment]
@daharn I did add the source manually, but it doesn't work until I install `gvfs-nfs`

**Comment by daharn** [comment]
> What should I do in the /etc/exports?

"/nfs/<path>" *(ro,all_squash,sync,no_wdelay,insecure_locks,insecure,no_subtree_check,anonuid=501,anongid=100

Works for me on my NAS, with <path> actually being a symlink to the actual file location on the hard drives.

**Comment by FabiJa** [comment]
> > What should I do in the /etc/exports?
> 
> `"/nfs/<path>" *(ro,all_squash,sync,no_wdelay,insecure_locks,insecure,no_subtree_check,anonuid=501,anongid=100`
> 
> Works for me on my NAS, with actually being a symlink to the actual file location on the hard drives.

On what system do you run Kodi? This and various other settings are not working for me using a Nvidia Shield (Android TV).

**Comment by Naikless** [comment]
Kodi runs as part of LibreELEC on a Raspberry PI 4. 
How does your `/etc/exports` on the source looks like? Can you access the shares from somewhere else in your network to ensure that everything is working on the server side?

**Comment by FabiJa** [comment]
I test the above mentioned config:
`/srv/nfs4 192.168.178.0/24(rw,sync,no_subtree_check,crossmnt,fsid=0) `
`/srv/nfs4/Multimedia *(ro,all_squash,sync,no_wdelay,insecure_locks,nohide,no_subtree_check,insecure,anonuid=501,anongid=100)`

**Comment by Naikless** [comment]
And

> Can you access the shares from somewhere else in your network to ensure that everything is working on the server side?

what exactly is the error? You don’t make it very easy to help you.

**Comment by pduveau** [comment]
Hello,
I think that the problem come from the way Android give a randomized uid/gid to kodi during installation. Those uid/gid can't be overwritten with another way than the libnfs API. I proposed a year ago through #23302 an enhancement to kodi allowing the user to provide the suitable uid/gid to the library. The `all_squash`, `anonuid` and `anongid` options in the export could solve but it is a security hole in the configuration.
