### ISSUE TITLE
Kodi 19.3 voice search not working with Nvidia shield Android 11 Update (Hotfix #3)

### ISSUE THREAD

**Issue by artzox** [xbmc/xbmc#20920]
Hi, 
I have updated Nvidia shield 2019 Pro model do Android 11 version of Android TV and installed all 3 currently available hotfixes.
Fixes are available here:
https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/481434/shield-experience-upgrade-90-hotfix-image/
With the latest hotfix longpress button is now working, but voice search is still not.
In the known issues thread it is reported and I quote:
"Apps require updates to resolve these due to changes in Android 11:
Long press select in Kodi doesn't trigger voice search as it should"
This comment is provided below:
https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/481782/shield-experience-upgrade-90-known-issues/
Thefore I am reporting this as a bug:

## Expected Behavior
Longpress of the Nvidia shield remote when searching should trigger the voice search and allow for usage of this function - search by voice.

## Actual Behavior
Longpress brings up the search mic "button" for a split-second and then disappears. No voice is recorded and the functionality does not allow for voice search as was possible prior to Nvidia shield being updated to Android TV 11.

## Possible Fix
N/A

### To Reproduce
1.) Open search menu in Kodi (magnifying glass)
2.) Press on "Search in Local Library"
3.) Longress the remote selection button.

### Your Environment
Used Operating system:
Nvidia Shield Pro 2019, Shield Experience 9 (Hotfix 3), Andorid TV 11

 - Operating system version/name:
 - Kodi version: 19.3

**Comment by vajonam** [comment]
https://forum.kodi.tv/showthread.php?tid=366478&pid=3082674&highlight=voice+search#pid3082674

**Comment by artzox** [comment]
> https://forum.kodi.tv/showthread.php?tid=366478&pid=3082674&highlight=voice+search#pid3082674

There is no resolution in that thread.

**Comment by vajonam** [comment]
> There is no resolution in that thread. I have tested correcting the manifest but did bit work. 

Do you mean it didn't work? I haven't tried the manifest. I suspect this will need to be fixed when kodi is targeted to api level 30 and android 11. Based on the 19.4 release that might be a Nexus thing rather than back port to matrix.

**Comment by artzox** [comment]
Yes, i can confirm this does not work.

**Comment by artzox** [comment]
Using the latest nightlies and this is still not working.
Are there any plans for fixing this?

**Comment by savaonepunch** [comment]
2+ months and still an issue for me.

**Comment by a1rwulf** [comment]
> 2+ months and still an issue for me.

Comments like this don't help.
PR's welcome...

**Comment by artzox** [comment]
If I was a programmer I would fix it myself even if only for personal use, but unfortunately I am not. I have tried the suggested android manifest fix to no avail, so while probably this is not helping I would like to highlight that this is a really useful feature when searching not only the library but for subtitles and everything else. 
Nvidia shield users may be considered a niche base but I am hoping that at least one dev out there has the device and can provide a temporary if not permanent solution.

**Comment by artzox** [comment]
I can confirm that this is fixed with the latest master nightly from 15th May. Thanks Team !

**Comment by bigpoppapaul** [comment]
Is there any way to incorporate this into the Matrix nightlies since Nexus is a ways away from being stable?

**Comment by ksooo** [comment]
> Is there any way to incorporate this into the Matrix nightlies since Nexus is a ways away from being stable?

 Sorry, no. Too many code changes.

**Comment by bigpoppapaul** [comment]
> > Is there any way to incorporate this into the Matrix nightlies since Nexus is a ways away from being stable?
> 
> Sorry, no. Too many code changes.

Alright, thank you for the quick response.

**Comment by artzox** [comment]
@bigpoppapaul
I would suggest just making a backup of the data folder and giving it a go.
Nexus is really not that unstable, the issues come when you are installing the next nightly, but a clean install fixes these as painful as that may be.
For me it is worth it the spared in writing even when using a keyboard.
