### ISSUE TITLE
can't switch screen on wayland

### ISSUE THREAD

**Issue by fireba11** [xbmc/xbmc#20943]
### Describe the bug
running wayland screen selection in options doesn't do anything

note: works as expected when using x11

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 20.04.3 LTS
 - Kodi version: 19.3

**Comment by DaVukovic** [comment]
Ignoring the template won´t get you anywhere ;)

**Comment by fireba11** [comment]
Requiring me to fill out things that don't make sense in the context won't get you anywhere either

**Comment by garbear** [comment]
Be mindful of the fallacy of Chesterton's fence. Think of why we require a debug log, and how it allows for reproducibility, and gives us necessary information omitted in the issue, and when you finally understand why we require these things, then you have permission to open an issue without them.
