### ISSUE TITLE
getCondVisibility error

### ISSUE THREAD

**Issue by Mariusz89B** [xbmc/xbmc#20945]
### Describe the bug
Here is a clear and concise description of what the problem is:

xbmc.getCondVisibility('system.platform.linux.raspberrypi') returning True on PC running Arch Linux. 

System:
AMD Ryzen 5 2600, MSI B450 A Pro

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Return False

## Actual Behavior

Return True

## Possible Fix

N/A

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Thought this was removed long ago, it's likely a leftover. There's no fix, just a complete removal of the infobool if it still exists.

**Comment by lrusak** [comment]
The property doesn't exist anymore. Just use `system.platform.linux`

https://alwinesch.github.io/modules__infolabels_boolean_conditions.html#modules_rm_infolabels_booleans_v19
