### ISSUE TITLE
"Manage movie set" function broken on Xbox Series X

### ISSUE THREAD

**Issue by Hawkedon** [xbmc/xbmc#20955]
### Describe the bug
I'm using Kodi (both the previous version 18 and the current version 19.3) on Xbox Series X. But the "Manage movie set" function is always broken for both versions. When I select the "Manage movie set" menu item, nothing happened, normally a movie set dialog would pop up and let me choose a movie set. After checking the kodi log, I found the query for movie set failed with the following error:

> ERROR <general>: SQL: [MyVideos119.db] SQLite error SQLITE_ERROR (SQL logic error)
                 Query: select * from movie_view  JOIN sets ON movie_view.idSet = sets.idSet ORDER BY sets.idSet
ERROR <general>: CVideoDatabase::GetMoviesByWhere failed

I tried many ways to reset Kodi and Xbox:

>1. Remove all items in database and rescan everything
>2. Uninstall Kodi and reinstall
>3. Reset Xbox but keep games and applications
>4. Reset Xbox without keep anything

But no matter what I tried, this "Manage movie set" function is always broken and I always got the above SQL error in Kodi log.

The weird thing is, when I open the video database with "DB Browser for SQLite", I can run the failed query in the log
>select * from movie_view  JOIN sets ON movie_view.idSet = sets.idSet ORDER BY sets.idSet

and got
>Execution finished without errors.
Result: 584 rows returned in 2936ms
At line 1:
select * from movie_view  JOIN sets ON movie_view.idSet = sets.idSet ORDER BY sets.idSet

I tried to run the query many times on different video databases (as I installed/uninstalled Kodi and scanned library many times), but never got any error, at the same time Kodi failed on Xbox on this consistently.

I suspect some database settings (query optimization/time constrain, for example) for SQLite in Kodi caused this issue on Xbox, but no much knowledge of SQLite.

## Expected Behavior
"Manage movie set" function works

## Actual Behavior
"Manage movie set" function is broken

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name: Xbox Series X
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@Hawkedon 

Could you please post the full debuglog

**Comment by Hawkedon** [comment]
Hi @KarellenX, full log is here https://paste.kodi.tv/ocanigiqat.kodi

From the symptoms and my tests, I'm sure the database is not corrupted, seems the SQLite engine (and/or configuration) has problem. I searched for related information, seems there is problem for SQLite for UWP platform for some versions, like https://github.com/praeclarum/sqlite-net/issues/958 and some work arounds like https://github.com/ericsink/SQLitePCL.raw/wiki/UWP-Init. I'm not sure whether these are relevant to the problem here though, just my best shots.

**Comment by KarellenX** [comment]
Thanks @Hawkedon 

@HitcherUK are you able to replicate this?

**Comment by HitcherUK** [comment]
No, works fine on my Series X. I use the non-Python Movie Database scraper if that makes a difference.

**Comment by Hawkedon** [comment]
Hi @HitcherUK, I'm not sure whether we are on the same page for the problem.

I'm not talking about that a movie can't be scraped to a movie set. I'm using the Universal Movie Scraper which is a non-Python scraper too and my movie can be scraped to the right movie set.

My problem is, when I want to change the movie set for a movie manually from the "Manage movie set" context menu of the movie, the query will fail and I can't change the movie set.

For example, after scanning my movies, the "Iron Man" movie is put into the "Iron Man Collection" movie set. But I want to manually put this movie to another movie set (e.g., "The Marvel Cinematic Universe" movie set), I need to use the "Manage movie set" context menu to do this, which will always fail on Xbox. I did this before on Android platform and never had any issue.

**Comment by HitcherUK** [comment]
I just wondered whether it had something to do with the DB entry.

And I can move a movie from one collection to another without any problem. I tested by moving Thor to a new MCU colllection.

**Comment by Hawkedon** [comment]
Thanks for the confirmation. I used Kodi on Android/PC/Xbox, and only Xbox has this problem, and this happened for all Kodi versions I used on Xbox, so I thought it's a Xbox specific issue. As there is no issue for you, I'm not sure how I can investigate further.
