### ISSUE TITLE
problem since 10years with m3u...

### ISSUE THREAD

**Issue by CodingBDX** [xbmc/xbmc#20951]
hello:

i use kodi since xbmc ;), it's good extension but i don't understand one big problem...I use service iptv and when i use in tv or raspberre or laptop, it's the same problem...Load m3u are very very very slow, i don't load epg(it's close option)...
i have kodi 19.3 and debian....

my m3u are 10mo but i slit it just for my country 136ko file and it's the same problem, that take 50minutes for load 10mo.....
when i use VLC, that take 10sec...

could you explain???? thank for answer

**Comment by KarellenX** [comment]
@CodingBDX 

Github is for bug reports, not general assistance.

Please post your question on the forum. It is currently undergoing some maintenance, but should be back up within the hour.
