### ISSUE TITLE
Display resolution on Chromecast TV only 1080p 

### ISSUE THREAD

**Issue by par2i** [xbmc/xbmc#20963]
## Description 
I am using Kodi 19.3 on Google Chromecast 4 Google TV, Android 10 connected to LG C1 via HDMI 2.1 port. 
Chromecast video output is set to 4K@60Hz

In Kodi system info is a display resolution 1920*1080. 
I have tryed change resolution in Kodi system settings. Display resolution is grayed out on 1920x1080 and cannot be changed. 
Whitelist provide only 1920x1080@60Hz.

Alson, when I am playing 4K HDR video and check display info (pressing "Z" key) there is display resolution 1080p and info that 4K source is downscaled to 1080p. ODS info (pressing "O" key) shown video stream is 4K.
I tried reinstall Kodi and result is same.

## Expected Behavior
Possibility to choose correct display resolution for 4K TV or correct identification of resolution of Android TV and/or TV

## Device
Google Chromecast TV, Android 10, output set to 4K60Hz
LG C1, 65" 4K, HDMI 2.1 ports
Kodi 19.3

**Comment by a1rwulf** [comment]
Nothing we can change on Kodi side, this is a well known issue for the time being and at least affects any Android box that uses AMLogic chips - maybe also other chips.
The only box I know, which does this correctly is the Nvidia Shield.

**Comment by par2i** [comment]
Thanks for quick reply.

It means that bug is in Android or chips side?
Is it raised as a bug for Google?

**Comment by a1rwulf** [comment]
Afaik it's because the chips are able to play 4k video, but the gpu is not powerful enough to render 4k UI.
So there is this workaround in Android SurfaceFlinger to only expose the 1080p60 mode.
At least that's how far I got, when I tried to understand this issue.
If I remember correctly this will be gone in AndroidTV12.

**Comment by par2i** [comment]
Thanks.

I look forward and hope that update will help.
