### ISSUE TITLE
Kodi seems to skip reading video tags from mp4

### ISSUE THREAD

**Issue by jillian1701** [xbmc/xbmc#20972]
## Bug report
After enabling video tags (https://kodi.wiki/view/Video_file_tagging) and setting the scrapper to local, it appears that the local video tags from the files are not being read. 

Verified the video tags are present using AtomicParsely and VLC. VLC displays the tags correctly. 

### Describe the bug
mp4 video tags are not being read and therefore are not added to the library. 

## Expected Behavior
Should read the mp4 tag

## Actual Behavior
Doesn't appear to be reading mp4 tag

### Debuglog

Log file gives no indication that the scrapper attempts to read tags:

DEBUG <general>: VideoInfoScanner: Found episode match /home/jillian/MediaDrive/Videos/TV-Shows/Drawn Together/Season 1/Drawn Together (2004) S01E01.mp4 (s1e1) [s([0-9]+)[ ._x-]*e([0-9]+(?:(?:[a-i]|\.[1-9])(?![0-9]))?)([^\\/]*)$]
DEBUG <general>: [ script.embuary.helper ] Force widgets to refresh (VideoLibrary.OnUpdate)
DEBUG <general>: [ script.embuary.helper ] Execute: AlarmClock(WidgetRefresh,SetProperty(EmbuaryWidgetUpdate,20220209154717,home),00:10,silent)
DEBUG <general>: ffmpeg[(nil)X]: [mov,mp4,m4a,3gp,3g2,mj2] stream 0, timescale not set
ERROR <general>: VideoInfoScanner: Asked to lookup episode /home/jillian/MediaDrive/Videos/TV-Shows/Drawn Together/Season 1/Drawn Together (2004) S01E01.mp4 online, but we have no episode guide. Check your tvshow.nfo and make sure the <episodeguide> tag is in place

### Your Environment
Used Operating system:

 - [x] Linux

 - Operating system version/name: Pop OS
 - Kodi version: 19.3.0

**Comment by enen92** [comment]
Which tags? Kodi support for mp4 tags is pretty rudimentary as explained in the wiki. The actual tags mentioned there might be wrong but the code is self-explanatory on what is supported:

https://github.com/xbmc/xbmc/blob/a80d1293b0579bbed7dd7d20304ba34a20519f78/xbmc/video/tags/VideoTagLoaderFFmpeg.cpp#L211-L235
