### ISSUE TITLE
Not able to setup local env of kodi in OSX

### ISSUE THREAD

**Issue by dev-drprasad** [xbmc/xbmc#20979]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm following [README.Android.md](https://github.com/xbmc/xbmc/blob/master/docs/README.Android.md) to setup my OSX machine to build android variant of kodi.
When I run `make -j$(getconf _NPROCESSORS_ONLN)`, after 15 mins of `make`ing things, it failed with an error: `make: *** [native/.installed-x86_64-osx-native] Error 2`

## Expected Behavior
should be able to build and generate android app in OSX

## Actual Behavior
`make` failing with an error

## Possible Fix
I wish I knew

### To Reproduce
Follow the guide [README.Android.md](https://github.com/xbmc/xbmc/blob/master/docs/README.Android.md) in OSX machine

### Debuglog
The debuglog can be found here:
There are too many logs, adding only last few lines. Let me know if you need full log

```
aking install in misc
 ../../build-aux/install-sh -c -d '/Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/bin'
 /usr/bin/install -c gettextize autopoint '/Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/bin'
 ../../build-aux/install-sh -c -d '/Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/share/gettext'
 /usr/bin/install -c -m 644 archive.dir.tar.xz '/Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/share/gettext'
Making install in man
make[5]: Nothing to be done for `install-exec-am'.
../../build-aux/install-sh -c -d /Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/share/doc/gettext
for file in msgcmp.1.html msgfmt.1.html msgmerge.1.html msgunfmt.1.html xgettext.1.html msgattrib.1.html msgcat.1.html msgcomm.1.html msgconv.1.html msgen.1.html msgexec.1.html msgfilter.1.html msggrep.1.html msginit.1.html msguniq.1.html recode-sr-latin.1.html gettextize.1.html autopoint.1.html; do \
	  if test -f $file; then dir=.; else dir=.; fi; \
	  /usr/bin/install -c -m 644 $dir/$file /Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/share/doc/gettext/$file; \
	done
 ../../build-aux/install-sh -c -d '/Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/share/man/man1'
 /usr/bin/install -c -m 644 msgcmp.1 msgfmt.1 msgmerge.1 msgunfmt.1 xgettext.1 msgattrib.1 msgcat.1 msgcomm.1 msgconv.1 msgen.1 msgexec.1 msgfilter.1 msggrep.1 msginit.1 msguniq.1 recode-sr-latin.1 gettextize.1 autopoint.1 '/Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/share/man/man1'
Making install in m4
make[5]: Nothing to be done for `install-exec-am'.
 ../../build-aux/install-sh -c -d '/Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/share/aclocal'
 /usr/bin/install -c -m 644 ../../gettext-runtime/gnulib-m4/host-cpu-c-abi.m4 ../../gettext-runtime/gnulib-m4/lib-ld.m4 ../../gettext-runtime/gnulib-m4/lib-link.m4 ../../gettext-runtime/gnulib-m4/lib-prefix.m4 ../../gettext-runtime/m4/gettext.m4 ../../gettext-runtime/m4/iconv.m4 ../../gettext-runtime/m4/intlmacosx.m4 ../../gettext-runtime/m4/nls.m4 ../../gettext-runtime/m4/po.m4 ../../gettext-runtime/m4/progtest.m4 '/Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/share/aclocal'
 ../../build-aux/install-sh -c -d '/Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/share/doc/gettext/examples/build-aux'
 /usr/bin/install -c -m 644 ../gnulib-m4/javacomp.m4 ../gnulib-m4/javaexec.m4 ../gnulib-m4/csharpcomp.m4 ../gnulib-m4/csharpexec.m4 csharpexec-test.exe '/Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/share/doc/gettext/examples/build-aux'
make[5]: Nothing to be done for `install-exec-am'.
 ../build-aux/install-sh -c -d '/Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/share/doc/gettext/examples/build-aux'
 /usr/bin/install -c -m 644 ../build-aux/javacomp.sh.in ../build-aux/javaexec.sh.in ../build-aux/csharpcomp.sh.in ../build-aux/csharpexec.sh.in '/Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/share/doc/gettext/examples/build-aux'
 ../build-aux/install-sh -c -d '/Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/share/gettext'
 /usr/bin/install -c ../build-aux/config.rpath '/Volumes/android-dev/android/xbmc-depends/x86_64-darwin21.2.0-native/share/gettext'
touch .installed-x86_64-osx-native
make: *** [native/.installed-x86_64-osx-native] Error 2
```

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
 - Hardware: MacBook Pro (16-inch, 2019)
 - OS: macOS Monetery 12.1
 - Java: openjdk version "1.8.0_292"
 - Android SDK: latest cli tools download from official site 
 - Android NDK: r21e

### Your Environment
Used Operating system:

 - [x] OSX

 - Operating system version/name:
 - Kodi version: master

Let me know if you need details to understand the issue

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
I've spent a considerable amount of time making sure building android on OSX actually works, so I know that it does.
I'll close this for now. Make a post on the forums and ping my user (@fuzzard ) and I'll help you troubleshoot the issue your having.

First step, get a full log. Grep for Error 2. There will be 3-4 occurrences. The first 1 or 2 will give you the info about what native package is failing. We can work out what's going on from there.
