### ISSUE TITLE
Color Management doesn't work on Windows

### ISSUE THREAD

**Issue by CrHasher** [xbmc/xbmc#20999]
### Describe the bug
Here is a clear and concise description of what the problem is:

Switching Color Management On/Off has no effect on the output. In the logs I see "ColorManager" appear when turning the CM on and that part of the code is apparently executed, but the result is a frame rendered same as without color management. At this point not sure what CM even does.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

My expectation is that when turning CM on the frames appear color corrected not exactly 1:1 same as not corrected. Tested this in mpv and colors are definitely less red with same *.icm profile.
[ROG PG279Q Gamma_2_2-v001 #1 2022-02-05 15-34 0.3127x 0.329y 2.2 S XYZLUT+MTX.zip](https://github.com/xbmc/xbmc/files/8078895/ROG.PG279Q.Gamma_2_2-v001.1.2022-02-05.15-34.0.3127x.0.329y.2.2.S.XYZLUT%2BMTX.zip)

## Actual Behavior

Nothing changes a pixel to pixel comparison of frames shows no difference.

### To Reproduce

1. Turn CM on
2. Play video stop at a frame take a screenshot 
3. Restart Kodi (just in case)
4. Turn CM off
5. Play video stop at a frame take a screenshot 
6. Compare frames they are the same, plus visually indistinguishable unlike in mpv.

### Debuglog

The debuglog can be found here:
[kodi - ICC Off.log](https://github.com/xbmc/xbmc/files/8078867/kodi.-.ICC.Off.log)
[kodi - ICC On.log](https://github.com/xbmc/xbmc/files/8078868/kodi.-.ICC.On.log)

### Screenshots
Here are some links or screenshots to help explain the problem:

![screenshot00000](https://user-images.githubusercontent.com/834518/154242658-2b55a0af-82e8-443f-9762-ec3d8601370c.png)
![screenshot00001](https://user-images.githubusercontent.com/834518/154242671-da152bcf-a781-497c-b90c-b4bdf5c2249e.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

![screenshot00002](https://user-images.githubusercontent.com/834518/154244136-f103364e-7a56-4ddb-b075-a5fef057cd8f.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: 19.3.0 (latest stable)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Not really into this stuff but I see noticeable differences between your first and your second screenshots. The second screenshot appears less darker than the first one

**Comment by CrHasher** [comment]
Not sure why you see one as darker than the other here is the actual diff:
![Screenshot 2022-02-16 173644](https://user-images.githubusercontent.com/834518/154299881-70a63b64-6022-4a3b-bc62-ae046a95a827.png)
Anything that is not red is not different at all.

**Comment by thexai** [comment]
I have found a bug that causes parameters not apply. 

With fix (using ICC profile posted here):

ICC off
![screenshot00001](https://user-images.githubusercontent.com/58434170/158056997-cd290d17-2840-484d-9a3c-ad269a9fc021.png)

ICC on
![screenshot00000](https://user-images.githubusercontent.com/58434170/158057002-27b37ea3-d21c-4cc2-a3cd-a8aa3922effb.png)

**Comment by thexai** [comment]
Here is a Matrix build with fix:
http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220313-7d086c14-fix-ICC-profile-Matrix-x64.exe

**Comment by thexai** [comment]
The issues are closed automatically when linked PR gets merged.

**Comment by CrHasher** [comment]
Noted, thank you.
