### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Noctudeit** [xbmc/xbmc#21002]
It would be nice if we could have the option of changing the genre filter from "or" to "and". For example, this would allow us to filter a movie collection to only "Family" genre movies which are also "Animated". As it stands, selecting both genres will include live action family films as well as adult animated features.

**Comment by fuzzard** [comment]
Feature requests can be made on the forums - https://forum.kodi.tv/forumdisplay.php?fid=9

**Comment by Noctudeit** [comment]
Thanks!
