### ISSUE TITLE
19.4 release date

### ISSUE THREAD

**Issue by techpro2004** [xbmc/xbmc#21000]
Not sure how to reach you so I thought this was the best way. I am a user of libreelec. libreelec is waiting on kodi 19.4 to release their next version. I noticed 19.4 is very overdue according to the milestones page so I was wondering if there was a rough idea of when 19.4 will be released. Thanks.

**Comment by fuzzard** [comment]
No ETA. Milestones are just guesses. It'll come when it comes

**Comment by techpro2004** [comment]
I am not looking for an exact date, just a rough idea. are we talking about a week, a month, a year, 10 years?

**Comment by fuzzard** [comment]
Let's go with 10 years

**Comment by techpro2004** [comment]
Wow, by that time my libreelec box will be long dead. can you give me a better idea or if it will really take that long, maybe I should abandon kodi and use something else.
