### ISSUE TITLE
Kodi 19.3.0 Matrix UPNP progress not updating

### ISSUE THREAD

**Issue by andycockerill-cpi** [xbmc/xbmc#21004]
### Describe the bug
I have a two Libreelec instances both running Kodi 19.3.0.
The "server" instance has movies and tv shows libraries scanned and shared using upnp.
The "client" instance loads the "server" libraries over upnp.
The "server" is running on x86_64
The "client" is running on a Raspberry pi 4

## Expected Behavior
On the "client" Kodi.
Play a title, then stop after <> 5 mins.
The progress is saved.
Play the title again and a message appears asking if you want to restart from the beginning or pick up from the last saved point.

## Actual Behavior
On the "client" Kodi.
Play a title, then stop after <> 5 mins.
The progress is not saved.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Im pretty sure this is the expected behavior of Kodi's upnp implementation. There are a lot of limitations. If you want to share a library I would recommend using MySQL instead.

https://kodi.wiki/view/UPnP

**Comment by andycockerill-cpi** [comment]
Thanks for the feedback. I've now switched to using the MySQL (MariaDB) method.
