### ISSUE TITLE
pvr: playing recordings does not use video cache

### ISSUE THREAD

**Issue by disaster123** [xbmc/xbmc#21001]
### Describe the bug
I'm using a Fire TV Stick connected via WLAN. While this is most of the time pretty stable it might have latency spikes (1-3 in 1-2 hours). While playing HD recordings i'm seeing 3-5 read requests per second (512kb chunk size). If there are spikes or lost packets in WLAN. Playing recordings start to buffer.

As far as i was able to check it seems playing recordings does not use any video cache.

## Expected Behavior
Playing recordings from "remote" server - should use video cache.

## Actual Behavior
no cache is used

## Possible Fix
use cache

### To Reproduce
see above

### Your Environment
Used Operating system:
 - [ X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: FTV
 - Kodi version: 19.3

**Comment by disaster123** [comment]
What do i miss? I don't get it. I think i've filled in all fields.

**Comment by disaster123** [comment]
@arnova how to control those internal video buffers? I need a preread mechanism of 32mb - I think.

**Comment by arnova** [comment]
Currently there's no mechanism to change the values although the defaults should be adequate for most scenarios: 40 MByte/8 seconds for video, 6 Mbyte/8 seconds for audio. I think you should look at improving the throughput/latency of your network.

**Comment by da-anda** [comment]
@disaster123 were you able to sort out your issue so that we can close this ticket? As arnova pointed out, the internal buffer is 8 seconds which is ~ 46MB.

**Comment by disaster123** [comment]
No. Live TV works without any flaws or stutter. Playing the same as recordings starts to buffer after 1-2 hours and never stops…
