### ISSUE TITLE
HQ Scalers on GLES platforms not scaling properly

### ISSUE THREAD

**Issue by JySzE** [xbmc/xbmc#21011]
### Describe the bug

HQ Scalers are not producing proper outputs with SD video

## Expected Behavior

Expecting proper scaling output results for each scaler.

## Actual Behavior

HQ Scalers are not producing proper results compared to other players using the same scalers.

I will only provide examples for spline36 as thats what I want to use but the other scalers besides nearest and bilinear seem to be working incorrectly just like spline36. 

MPV Android app Spline36 works as intended

3.9.10 MrMC with HW Accel off (MediaCodec & MediaCodec Surface) Spline36 works as intended

Kodi v17.6, 18.0, 18.6, 19.0, 19.3, 20 (master-21651-arm64-v8a) Spline36 does NOT work as intended

Tested on 2019 Shield Pro - Firmware 8.2.3 & 9.0.1 both have same results.

Error not reproducible on windows.

*UPDATE*

This is not a NV shield only issue, this is reproducible on my android tv.

Changing issue title from Shield to Android

Possibly related to : https://github.com/xbmc/xbmc/issues/16522
& https://github.com/xbmc/xbmc/pull/13260

### To Reproduce

1. Disable HW Accel (MediaCodec & MediaCodec Surface)
2. Enable HQ scalers for scaling above = 10%
3. Open provided video with spline36 set in Kodi (video file provided is non copyright material, it is a still frame repeated over and over)

Video: https://mega.nz/file/J1Ey2ZiD#AesdL-zTXYyGZXPqNEX3Z2d-p0wCCN2_aU4TNSrVQOg

### Debuglog

The debuglog can be found here:

Log: 

v19.0 : https://pastebin.com/f84XtC1i
v19.3 : https://pastebin.com/sW6yc9BJ

### Screenshots 
Here are some links or screenshots to help explain the problem:

Kodi v19.3 Stable_Spline36
![Screenshot From Kodi v19 3 Stable_Spline36](https://user-images.githubusercontent.com/70117278/154735565-4fb74a6d-05b4-4b2c-ad13-80b8babd7de9.png)
MPV Android_Spline36
![Screenshot From MPV Android_Spline36](https://user-images.githubusercontent.com/70117278/154735573-e4407f7f-7762-43db-b6e4-750112acea10.png)
MrMC 3.9.10_Spline36
![Screenshot From MrMC 3 9 10_Spline36](https://user-images.githubusercontent.com/70117278/154735577-33afd012-139a-40fd-9f54-c7bebe257312.png)

## https://slow.pics/c/dOoFNZ4M

Screenshots were taken directly from Shield using a 4k capture card.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] Linux
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:  Shield Firmware 8.2.3 & 9.0.1
 - Kodi version: v17.6, 18.0, 18.6, 19.0, 19.3, 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by zerocool9001** [comment]
I was able to reproduce the same error as you experienced using the steps described. This is horrifying this has been going on for seemingly years without the Kodi teams caring to fix it.

**Comment by the-black-eagle** [comment]
Whether or not it's "been going on for years" the fact remains that we have exactly zero Android developers.....
So, unless someone steps up to help, I doubt anything will change in the immediate future.
PR's are of course most welcome.

**Comment by Krycek7o2** [comment]
Using the provided file, I was able to reproduce the issue. Being that this is an issue that has not been attended to since first being reported 2019, does bear down on the quality and spirit of this app. I would sincerely hope that some one takes a look at fixing this glaring issues.

**Comment by zerocool9001** [comment]
You have zero developers for the most used operating system on earth...

**Comment by JySzE** [comment]
> Whether or not it's "been going on for years" the fact remains that we have exactly zero Android developers..... So, unless someone steps up to help, I doubt anything will change in the immediate future. PR's are of course most welcome.

Thanks for the reply, That is unfortunate to hear :( . I hope that changes in the near future. I have no experience with any of this stuff but I did spend a good 8 - 12 hours tweaking stuff and making testing packages but the incorrect scaling remained. I wish I could provide some kind of PR but I am incredibly ignorant and lack any form of experience with this. 

I plan on trying to reproduce this on OSX next with a apple 4k tv gen 1 so I hope y'all have a dev for apple devices still if its reproducible.

**Comment by lrusak** [comment]
Can you explain the issue more? I don't understand the problem from your description and all the screenshots look the same to me.

**Comment by JySzE** [comment]
> Can you explain the issue more? I don't understand the problem from your description and all the screenshots look the same to me.

Try looking at it with this using the left and right arrow keys to flick back and forth, this is extremely obvious on a tv. 

https://slow.pics/c/GyhTGrjU

**Comment by sarbes** [comment]
> You have zero developers for the most used operating system on earth...

We are NOT a paid developer team. If you have nothing meaningful to add to this conversation, don't clutter the issue report.


On the topic at hand, I think it stems from:
https://github.com/xbmc/xbmc/blob/c32c8dd96ebff6b3a5848c3f5ee83fa2a6e2f77b/system/shaders/GLES/2.0/gles_convolution-4x4.frag#L34
On GL, the LUT is 1D, so it has just a float input. On GLES, a 2D texture has to be used. I think the minus is a typo, as it skews the 0.0-1.0 lookup into the edge clamped portion of the texture.

It should be `return texture2D(kernelTex, vec2(pos, 0.5));`as far as I can see. But I can't check it right now.

**Comment by JySzE** [comment]
> > You have zero developers for the most used operating system on earth...
> 
> We are NOT a paid developer team. If you have nothing meaningful to add to this conversation, don't clutter the issue report.
> 
> On the topic at hand, I think it stems from:
> 
> https://github.com/xbmc/xbmc/blob/c32c8dd96ebff6b3a5848c3f5ee83fa2a6e2f77b/system/shaders/GLES/2.0/gles_convolution-4x4.frag#L34
> 
> On GL, the LUT is 1D, so it has just a float input. On GLES, a 2D texture has to be used. I think the minus is a typo, as it skews the 0.0-1.0 lookup into the edge clamped portion of the texture.
> 
> It should be `return texture2D(kernelTex, vec2(pos, 0.5));`as far as I can see. But I can't check it right now.

I just tested this and it worked perfectly!! Thank you so much 😃

**Comment by sarbes** [comment]
Good. Right now, I don't have too much time to PR this, maybe someone else can do this. The 6x6 convolution shader would have to be edited in the same manner.

Tegra can upscale a 640x480 video to 4k? That's somewhat impressive. Can it handle 1080p to 4k in the same manner?

As for other ARM based devices, the math precision might not be good enough to do this, especially for 4k. If they can even run the shaders at full frame-rate.

**Comment by JySzE** [comment]
> Tegra can upscale a 640x480 video to 4k? That's somewhat impressive. Can it handle 1080p to 4k in the same manner?

Yes It can also do 1080p30 ~> 4k30 without breaking a sweat. 

It struggles a bit when it comes to 1080p60 ~> 4k60 content dipping into the 50 fps range. 

How can I test the 6x6 convolution shader to be sure its working correctly. I made the changes here on my fork and are building it now.

**Comment by sarbes** [comment]
The more expensive convolution shaders have to be enabled in the advancedsettings.xml. Then they should be available in the video settings.

I am not familiar with the scaling thresholds.

**Comment by JySzE** [comment]
Changed 

https://github.com/xbmc/xbmc/blob/c32c8dd96ebff6b3a5848c3f5ee83fa2a6e2f77b/system/shaders/GLES/2.0/gles_convolution-6x6.frag#L34

to 

`  return texture2D(kernelTex, vec2(pos, 0.5)).rgb;`

and can confirm all works as normal with 

enablehighqualityhwscalers=true using spline36

**Comment by JySzE** [comment]
Can someone PR this to Matrix and Master?
