### ISSUE TITLE
Kodi crash when start playing movie inside Bluray menu

### ISSUE THREAD

**Issue by TeHaX** [xbmc/xbmc#21016]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing a Bluray whin the Bluray menu the window about parent control pop up but after a few seconds later Kodi close completely. Latest Java update 321 is installed. The moving inside the Bluray menu works very good without any issue.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. Start movie with Bluray menu
2. Click play movie

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/lesaqinadi.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro 21H2
 - Kodi version: v20 Alpha 1 (19.90.101)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by da-anda** [comment]
ping @enen92 since you did some bluray stuff recently

**Comment by enen92** [comment]
The user does not provide a stacktrace, it's unclear where the application is crashing. My guess is that the crash happens in libbluray or because libbluray is not up to date on windows. Maybe when/if libbluray is bumped on windows the user can re-test.
Not much I can do, I don't use Windows and this isn't certainly I've introduced.

**Comment by ZhangShaobo9527** [comment]
I've met the same problem. 
when I turn on all debugging logs, I can gather some logs after crash, but the generated dump file was empty.
log files: 
[kodi.log](https://github.com/xbmc/xbmc/files/8718229/kodi.log)
[kodi.old.log](https://github.com/xbmc/xbmc/files/8718233/kodi.old.log)

if I turn off the debugging logs, I can get a non-empty dump file. hope this could help:

[kodi_crashlog-19.4 Git_20220302-e12e66e019-20220519-003440.zip](https://github.com/xbmc/xbmc/files/8718255/kodi_crashlog-19.4.Git_20220302-e12e66e019-20220519-003440.zip)

**Comment by darkvaderzerotwo** [comment]
I can give a couple of insights here, not that i have the exact issue.
What is happening for me is that java 8 update 332 and 333 cause kodi to crash to desktop when loading a BD-J bluray iso sometimes after a second or 2 of video, sometimes immediately.
this seems related : https://code.videolan.org/videolan/vlc/-/issues/25979
downgrading java to 8 u 322 stops the issue happening for me. this could mean that there is a regression within how one of the bluray java supporting libraries actually use java.
This issue happens both with the Oracle java and the eclipse java, if that means anything.
If anyone wants me to split this out into a seperate issue/bug i am happy to do so, just thought this was the most appropriate place to put this first :)

**Comment by enen92** [comment]
Seems to have been fixed upstream: https://code.videolan.org/videolan/libbluray/-/commit/8f26777b1ce124ff761f80ef52d6be10bcea323e
But not yet part of any new release.

**Comment by n0valis** [comment]
I'd like to keep my Java up to date, so is there a rough estimate when this issue can be fixed?
As stated above, VLC has fixed it already with an updated libbluray. So it seems not that big of a deal.
