### ISSUE TITLE
ASS subs not displaying correctly

### ISSUE THREAD

**Issue by JySzE** [xbmc/xbmc#21027]
### Describe the bug
Here is a clear and concise description of what the problem is:

Matrix 19.3 displays ASS subs correctly but there has been some kind of regression with ass subs with the current master.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Displaying subs correctly.

## Actual Behavior

Not displaying subs correctly.

## Possible Fix

~~Roll back whatever ASS changes have been made since 19.3.~~

### To Reproduce

1. Compare video with ASS subs in Nexus (current master) and Matrix 19.3)

### Debuglog

The debuglog can be found here:
(https://zerobin.net/?1d1e4723884c5114#bDZqt3SxD/A+Grob3jnVAIwwNPOyrp0Bf7ND97QHMGY=)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Matrix 19.3:
![Matrix 19 3](https://user-images.githubusercontent.com/70117278/155243125-f9efd752-5823-41df-8860-72e7eefb9252.png)

Nexus (current Master Branch):
[![Nexus](https://user-images.githubusercontent.com/70117278/155243135-7c55ba74-47d7-4dbd-8221-cc226e862ac3.png)](https://zerobin.net/?1d1e4723884c5114#bDZqt3SxD/A+Grob3jnVAIwwNPOyrp0Bf7ND97QHMGY=)

MPV:
![MPV](https://user-images.githubusercontent.com/70117278/155244785-e6f14c92-c005-4772-9e25-208cc9951b39.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: 8.2.3 Nvidia Shield
 - Kodi version: 19.3, Current Master Branch

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
for now i can only confirm that playback the same video on Windows build there is same problem
but i will need to investigate

**Comment by CastagnaIT** [comment]
not sure that this problem is related to ASS implementation
comparing the related parser/libass handler source code for this use case the code is the same of Kodi 19

Ass subtitle+Fonts to test: [naruto.zip](https://github.com/xbmc/xbmc/files/8126321/naruto.zip)

if you play a 16/9 video with test ass subtitle results equal to MPV
if you play a 4/3 video with test ass subtitle results wrong like screenshots

maybe could be something related to the renderer

**Comment by JySzE** [comment]
> The cause has been found and will be fixed from #21037

Awesome thank you very much, Will close when merged with master.

**Comment by JySzE** [comment]
Thank you CastagnaIT ❤️
