### ISSUE TITLE
可否支持高刷新率？如90hz，120hz？谢谢

### ISSUE THREAD

**Issue by snakwu** [xbmc/xbmc#21025]
安卓平台，在高刷新率的手机下，必须限定为60hz，如果不是，打开软件会黑屏！谢谢这么好的项目！

**Comment by fuzzard** [comment]
Please fill out the template provided in english. Google translate is fine.

If this is about Android not working above 60hz screen, its a known issue, no fix, no eta. Help from the community welcome.
