### ISSUE TITLE
[PVR] Channel hidden attribute changes from backend not obeyed/persisted

### ISSUE THREAD

**Issue by djp952** [xbmc/xbmc#21039]
### Describe the bug
Here is a clear and concise description of what the problem is:

After a channel has been imported into Kodi the first time, a subsequent change to the PVR backend's CPVRChannel hidden attribute (.SetIsHidden()) will be ignored by Kodi.  It's actually a very simple fix on the surface (see below), but I didn't want to issue a PR since I can see how "fixing" this could cause problems and would like the PVR maintainer and hopefully some of the PVR backend maintainers that use this attribute (MythTV, WMC, etc) feel about it.

My concern with fixing this is users that use the Group Manager to hide/show channels.  In the existing behavior, the channel would be imported with the backend's channel hidden flag appropriately, but the user can then change that via Kodi.  Since the flag is then ignored, the user's change will stick and override the backend indefinitely.

Perhaps consideration could be given to only reapply the backend's hidden flag for channels during reload when the __Synchronize Channel Groups with backends__ setting is enabled?  That would make it consistent with how channel groups are maintained, but this a channel-level attribute so that seems a bit of a hack.

Another possible approach would be to simply remove the ability for PVR backends to specify this and let it be solely available through the Group Manager.  I have no way to know how often a PVR backend might even want to set this to true right now, but assume since multiple backends can set this to true it's important to keep.

Anyway, would appreciate review of the concern and input as to if it best left as-is, or if you'd like a PR issued.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expected Kodi to apply changes to the PVR channel hidden attribute from the backend.

## Actual Behavior

Kodi does use the attribute the first time a channel is inserted into the database (new channel, clear data, etc), but will not apply any change to this attribute provided by the backend.

## Possible Fix
Simplistic / naive approach:
```
bool CPVRChannel::UpdateFromClient(const std::shared_ptr<CPVRChannel>& channel)
{
  std::unique_lock<CCriticalSection> lock(m_critSection);

  SetClientID(channel->ClientID());
  SetHidden(channel->IsHidden());     // <--- Here if it can be this simple 
  SetArchive(channel->HasArchive());
  SetClientProviderUid(channel->ClientProviderUid());
```

### To Reproduce
1. Using a PVR backend that allows for hidden channels (MythTV, WMC, etc) delete or clear the TVxx database
2. Note that any channels specified as hidden by the backend do not appear in Kodi
3. Change the PVR backend channel so it will not report as hidden
4. Restart Kodi
5. Note that the channels will not appear in Kodi even though they are no longer hidden by the backend

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ferigolete.kodi
(for completeness only)

### Screenshots 
Here are some links or screenshots to help explain the problem:
N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I was hoping to use the hidden attribute to hide/show channels in Kodi but it would only be useful to the user if the backend is able to change this as necessary.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 x64 (Desktop)
 - Kodi version: Kodi (20.0-ALPHA1 (19.90.101) Git:20220222-c0c800b58b). Platform: Windows NT x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
I do agree that the fix is not as trivial as it might seem in the first place. Unfortunately, there is no general concept how to sync backend channel properties with changes done locally using the channel manager.

> Perhaps consideration could be given to only reapply the backend's hidden flag for channels during reload when the Synchronize Channel Groups with backends setting is enabled? That would make it consistent with how channel groups are maintained, but this a channel-level attribute so that seems a bit of a hack.

Yes, this would be a hack. IMO, even the sync channel groups with backend is only a hack. I fear, nobody (users and devs) really understands what this feature is doing. For example, if I create some local groups and have this setting enabled, the local group will be deleted on next sync. This makes absolutely no sense. Nobody wants this behavior, right?

**Comment by ksooo** [comment]
Maybe a good approach is to handle the hidden flag like channel name and channel icon. Kodi knows whether those two attributes were set by the local user. Look at `CPVRChannel::UpdateFromClient` to get the idea. Maybe this gives you a hint for a PR?

**Comment by djp952** [comment]
Ah yes, excellent, thank you!  Will work that as time allows.  This is precisely why I went the Issue rather than PR route; you rock sir.

**Comment by ksooo** [comment]
@djp952 this one can be closed, right?

**Comment by djp952** [comment]
Absolutely!
