### ISSUE TITLE
Screensaver activates during music visualization

### ISSUE THREAD

**Issue by curtisdr** [xbmc/xbmc#21069]
### Describe the bug
Here is a clear and concise description of what the problem is:

Though System/Interface/Screensaver 'use visualization if playing audio' is ticked, it dims over my music visualization after the screensaver timeout period.  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When 'use visualization if playing audio' is checked, and audio or video is playing, the screensaver should not activate.

## Actual Behavior

Screensaver is activating during music visualization.

## Possible Fix

Reinstate the settings switch to work.

### To Reproduce

1. Tried Estuary & Aeon Silvo.  
2. Tried screensaver dim, black, and Picture Slideshow.  Each dims my visualization after 1 min.  
3. If I turn off screensavers, works normally.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows 7 x64. 
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Currently replicated on Kodi 19.3 but first started on earlier Matrix version.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
This is fixed in omega with https://github.com/xbmc/xbmc/pull/22974
