### ISSUE TITLE
[tools/depends][target]MacOS libuuid

### ISSUE THREAD

**Issue by Enlogty** [xbmc/xbmc#21066]
./bootstrap 
./configure --with-tarballs=/Users/Shared/xbmc-depends/tarballs --host=arm-linux-androideabi --with-sdk-path=/Volumes/android-dev/android/android-sdk-macosx --with-ndk-path=/Volumes/android-dev/android/android-ndk-r21e --prefix=/Volumes/android-dev/android/xbmc-depends
#------- configuration -------#
-e ccache:		 yes
-e build type:		 debug
-e build system:	 x86_64-apple-darwin21.3.0
-e build cpu:		 x86_64
-e build includes:	 -arch x86_64 -mmacosx-version-min=10.13 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
-e toolchain:		 /Volumes/android-dev/android/android-ndk-r21e/toolchains/llvm/prebuilt/darwin-x86_64
-e cpu:			 armeabi-v7a
-e host:		 arm-linux-androideabi
-e CC:		 /Volumes/android-dev/android/android-ndk-r21e/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang
-e CXX:		 /Volumes/android-dev/android/android-ndk-r21e/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang++
-e cflags:		 -DANDROID -D__ANDROID_API__=21 -fexceptions -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fPIC -DPIC -march=armv7-a -mtune=cortex-a9 -mfloat-abi=softfp -mfpu=neon -Og -g -D_DEBUG 
-e cxxflags:		 -DANDROID -D__ANDROID_API__=21 -fexceptions -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fPIC -DPIC -march=armv7-a -mtune=cortex-a9 -mfloat-abi=softfp -mfpu=neon -frtti -Og -g -D_DEBUG  -std=c++17
-e ldflags:		 -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -L/Volumes/android-dev/android/xbmc-depends/arm-linux-androideabi-21-debug/lib/android-21 -Wl,--exclude-libs,libunwind.a  
-e platform_includes:	 -I/Volumes/android-dev/android/xbmc-depends/arm-linux-androideabi-21-debug/include/android-21
-e ffmpeg options:	 
-e prefix:		 /Volumes/android-dev/android/xbmc-depends
-e depends:		 /Volumes/android-dev/android/xbmc-depends/arm-linux-androideabi-21-debug
-e ndk-api-level:	 21
-e build-tools:	 /Volumes/android-dev/android/android-sdk-macosx/tools:/Volumes/android-dev/android/android-sdk-macosx/platform-tools:/Volumes/android-dev/android/android-sdk-macosx/build-tools/28.0.3
#------- configuration -------#
#---------make-----------#
make

install: /Volumes/android-dev/android/xbmc-depends/arm-linux-androideabi-21-debug/include/uuid/uuid.h: No such file or directory
make[3]: *** [install] Error 71
make[2]: *** [.installed-arm-linux-androideabi-21-debug] Error 2
make[1]: *** [libuuid] Error 2
make: *** [target/.installed-arm-linux-androideabi-21-debug] Error 2

#---------make-----------#
#--------try solve------------#
After error log appears，Multiple attempts to run the command,Still can't solve the problem：
make -C target/libuuid distclean 
make
#--------try solve-----------#
#System Info# MacOS Monterey 12.2.1

**Comment by fuzzard** [comment]
I'll close this. I think this is more a support query at this stage.

Open a thread on the forums and ping me (same username). Happy to assist there.

Some quick info though. Highly depends what branch you are building. If you are building Matrix, just run up a linux VM and build through that. master has had a bunch of fixes to allow building android on macos, none have been backported, and likely wont be.

I need to update master docs, but essentially theres no special hoops (the whole disk creation step) for macos anymore. Essentially, the easiest way is download latest android studio, and you are good to go. Theres no need to be stuck on the old SDK/NDK combo. Again a bunch of fixes have been merged into master to make this happen.
