### ISSUE TITLE
Android: Scan to library issue

### ISSUE THREAD

**Issue by froginperil** [xbmc/xbmc#21079]
### Describe the bug
Here is a clear and concise description of what the problem is:

The problem outlined below is not an issue with the Linux version of Kodi (19.3 over Fedora 35). Since the problem exists in Android and not in Linux, presumably there is a bug affecting the Android version.

This issue occurred circa 19.1. I now have 19.4 installed on an Nvidia Shield and the issue persists. In brief, I switched out USB disks. Did a clean and then a scan. Many movies (about a dozen) that were successfully added to the db from prior versions of kodi will no longer scan so something changed. I tried to scan these in individually and that didn't work either. I will give you an example with the movie "Nobody" (2021).

Going to TMDB, if I search on "Nobody" I get a number of movies with the 2021 film on top. If I search on "Nobody 2021" or Nobody (2021) there are no results. Therefore, I renamed both the folder and the mkv "Nobody." The expectation is that I would get a list of movies comparable to what I obtained from TMDB website. What I get is "No information available." What I don't get is the option from previous versions to enter the name manually. This is the same behavior that I get on about a dozen movies. Moreover, I get the same behavior on a Sony Bravia Android TV so it's not a hardware issue. I have tried both the scraper and the python scraper. No joy.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

One of three things should happen:

1. The movie scans to the library from the file names.
2. Kodi offers a list of possible matches to resolve ambiguous file names.
3. Kodi offers an opportunity to enter a corrected name manually.

## Actual Behavior

Kodi returns: "No information available." I am unable to discern the  difference between movies that scan to the DB successfully and those that do not. Once a movie will not scan in, changing the folder and file name has made no difference. Kodi maintains a record in the database of every file name and will not progress past the first name in the database (see debuglog).

## Possible Fix

1. Purge the database of old file names and;
2. Kodi offers a manual entry rather than the "No information available" message.

### To Reproduce

Long press on folder, select scan to library

### Debuglog

**NOTE**: The movie is identified by its original upload name in contrast to the current file name. Going through **MyVideos119.db**, every file name that I have tried is in the database. The one shown in the log is the first entry. Therefore, **renaming the folder and file makes no difference whatsoever**. As you can see, **Kodi correctly identifies the file name but searches on the original file name**:

2022-03-05 15:23:34.316 T:9234     INFO <general>: initializing python engine.
2022-03-05 15:23:34.332 T:9234     INFO <general>: [metadata.themoviedb.org.python]: Find movie with title 'Nobody.2021.2160p.AMZN.WEB DL.x265.10bit.HDR10Plus.DDP5.1 SWTYBLZ' from year '0'
2022-03-05 15:23:34.796 T:9234     INFO <general>: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py): script successfully run
2022-03-05 15:23:34.831 T:9047  WARNING <general>: No information found for item '/storage/6B08EFA9421C99B1/Movies/Nobody/Nobody.mkv', it won't be added to the library.
2022-03-05 15:23:34.835 T:9047     INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I am unable to get information on a number of movies because they are not included in the library.

### Your Environment
Used Operating system:

 - [X ] Android 
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android for TV 9.03, January, 2022 patch
 - Kodi version: 19.4 (Android) 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by froginperil** [comment]
The Linux comparison is wrong on my part and I was unable to edit it out. The reason for the successful scan in Linux is that the db only has the file name that was scanned to the library (Nobody.mkv)

**Comment by KarellenX** [comment]
Please provide a **full** debug log ensuring that debug mode is enabled. Your snippet is of no use at all.

Thanks.
