### ISSUE TITLE
Kodi crashes at random points playing a very specific file type

### ISSUE THREAD

**Issue by realitylpma** [xbmc/xbmc#21070]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have been digitizing my old VHS tapes using a fairly old (circa 2008) set-up, through Windows Media Center on Windows Vista. Thee resulting files are .dvr-ms, which I have quickly realized aren't fully compatible with Kodi as I wasn't able to skip through the files (they could only get played linearly; something to do I assume with timestamps but I am not knowledgeable enough to say exactly what). The one workaround I was able to find was dumping the streams in an .mp4 container (through ffmpeg: -c copy -vsync 0 -enc_time_base -1). The issue I have been having is specifically with these files. Kodi completely shuts down at random times during playback; I have noticed however that the crashing window seems to be getting smaller over time (ie: first crash takes considerably longer than the subsequent ones). When the crash occurs, the screen turns to black for a few seconds and I am brought back to the main Android screen. If I try to boot up Kodi again, I get a brief message that's along the lines of "waiting for external storage", then I am back to the Android home screen again. A second boot will normally succeed.

I don't have a lot of knowledge with Kodi logs but somehow this log seems incomplete; as you will see there's quite a few error messages once playback starts. While the log stops roughly 7 minutes after playback, I remember playback lasted roughly 75 minutes before crash.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Playback happens until stopped by user or file ends.

## Actual Behavior

Application crashes (black screen, then back to Android home page) unprompted.

## Possible Fix

My one hypothesis: the files are badly interlaced, and the deinterlacing + scaling process consumes too many resources which eventually makes the system give up.

### To Reproduce

1. Boot up Kodi
2. Play file (the specific type highlighted in the bug description)
3. Wait for Kodi to crash

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/nijipatefu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I can't exclude the possibility that my files have been badly encoded and are making Kodi's job harder. Let me know if there's a fix there.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 11.0.0 (Nvidia Shield Pro)
 - Kodi version: 19.3.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
> don't have a lot of knowledge with Kodi logs but somehow this log seems incomplete; as you will see there's quite a few error messages once playback starts. While the log stops roughly 7 minutes after playback, I remember playback lasted roughly 75 minutes before crash.

The log is not "incomplete", it's missing the "debug"-information. In order to get a debuglog, please enable it at: 

Settings -> System -> Logging -> Enable debug logging

To do us a favor, create a debuglog in the follwing way:

Enable debug logging, restart Kodi (that's important to get a debuglog from startup), reproduce your issue (try to avoid doing something else), then get us the log. 

Thanks

**Comment by realitylpma** [comment]
> 
> The log is not "incomplete", it's missing the "debug"-information. In order to get a debuglog, please enable it at:
> 
> Settings -> System -> Logging -> Enable debug logging
> 
> To do us a favor, create a debuglog in the follwing way:
> 
> Enable debug logging, restart Kodi (that's important to get a debuglog from startup), reproduce your issue (try to avoid doing something else), then get us the log.
> 
> Thanks

Hi there, thanks for getting back to me. I have just attempted to replicate the bug with the debug logging feature on, and had to stop after 4.5 hours of continuous playtime. Pretty surprising considering I had a hard time getting past the hour mark without the bug the day before (and most times much less than an hour).

I have uploaded the log anyways even though I doubt anything will come from it: https://paste.kodi.tv/wazewawage.kodi

I will try again and report back. Thanks!

**Comment by realitylpma** [comment]
> The log is not "incomplete", it's missing the "debug"-information. In order to get a debuglog, please enable it at:
> 
> Settings -> System -> Logging -> Enable debug logging
> 
> To do us a favor, create a debuglog in the follwing way:
> 
> Enable debug logging, restart Kodi (that's important to get a debuglog from startup), reproduce your issue (try to avoid doing something else), then get us the log.
> 
> Thanks

I was finally able to replicate the bug after a few unsuccessful attempts (including a 6+ hours playthrough). Good news is the bug looks to be far more irregular than I initially thought. Here's the log, you will see that the crash occurred very quickly once I hit play on the file.
https://paste.kodi.tv/mugogowima
For reference purposes I've played the same file again later and had to stop playback after 4+ hours with no crashing:
 https://paste.kodi.tv/akaxecisoz

**Comment by enen92** [comment]
Closing as v19 is no longer maintained. Please let us know if the same issue still happens in v20 or v21 nighties.
