### ISSUE TITLE
*.edl files are ignored for stack URLs

### ISSUE THREAD

**Issue by MarkusEh** [xbmc/xbmc#21082]
### Describe the bug
Here is a clear and concise description of what the problem is:

If I use an strm file with a stack URL (example URL: "stack:///video/Vanilla_Sky/2017-04-17.20.12.21-0.rec/00001.ts , /video/Vanilla_Sky/2017-04-17.20.12.21-0.rec/00002.ts"), the files are played as expected :).
But, the *.edl files /video/Vanilla_Sky/2017-04-17.20.12.21-0.rec/00001.edl and /video/Vanilla_Sky/2017-04-17.20.12.21-0.rec/00002.edl are ignored, the commercials are not skipped.
Note:
- The skipping of commercials works fine, if I just play one file (e.g.  /video/Vanilla_Sky/2017-04-17.20.12.21-0.rec/00001.ts).
- Same error if this URL is returned by a plugin with xbmcplugin.setResolvedUrl()
- This error does not happen, and commercials are skipped, if the same URL is used in a video plugin list item
- This error does not happen, and commercials are skipped, if the stack URL is created by KODI using the naming convention for split files (part1, part2, ...) as described here: https://kodi.wiki/view/Naming_video_files/Movies
 
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Skip commercials also when using stack URLs

## Actual Behavior

Commercials are not skipped

### To Reproduce

1. Split a video file in 2 parts, 001.ts and 002.ts
2. Create 2 edl files, 001.edl and 002.edl
3. Create an test.strm file with content "stack:///\<path\>/001.ts , /\<path\>/002.ts"  (replace \<path\> with the path to the files you created)
4. Play  test.strm . The content of the *.edl files will be ignored

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux rpi3 5.15.24-v7+     armv7l GNU/Linux
 - Kodi version: Starting Kodi (19.3 (19.3.0) Git:20211118-a22c0ba337). Platform: Linux ARM 32-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Sorry this is not supported in the EDL implementation kodi has so your bug report is not really a bug but likely a feature request. Strm files/playlists are also not supported.
I plan to add support for it in the near future while extending the interface but that's not yet done. 
Please use the forum for feature requests.
