### ISSUE TITLE
Building addons with laguages other then python

### ISSUE THREAD

**Issue by AlenToma** [xbmc/xbmc#21099]
Hi. 
I have worked with nodejs and javascipt for the past years, and I am intressted in buildning an addons for kodi.

The problem is that as I understand that I have to use python.

Can I use any other languages like javascipt or nodejs?

This would have been great. Is this possible ?

**Comment by lrusak** [comment]
Feature requests are made via the forum. https://forum.kodi.tv/forumdisplay.php?fid=9
