### ISSUE TITLE
PPA to include Ubuntu 22.04 Jammy Jelly Fish

### ISSUE THREAD

**Issue by robotard** [xbmc/xbmc#21094]
Can you please extend the PPA to cover Ubuntu 22.04 Jammy please?

There appears to be no issues installing 19.3 straight from apt, and apparently also 19.4 through Flatpak (I reeeeeally don't want to install flatpak). Changing the PPA to Impish also doesn't work (No libfmt7 as 22.04 uses libfmt8 and libfmt-dev didn't work).

I've generally been running your nightlies, but also would like that my apt upgrades also cover Kodi updates...

Thanks guys, and keep up the great work...

**Comment by wsnipex** [comment]
jammy is not released yet.
Nonetheless, I'll add it in the next days

**Comment by wsnipex** [comment]
the PPA now has jammy builds

**Comment by llvasconcellos** [comment]
Why most of the addons packages are missing from the Jammy repository?
Packages like:
kodi-audiodecoder-modplug
kodi-audiodecoder-nosefart
kodi-audiodecoder-sidplay
kodi-audiodecoder-snesapu
kodi-audiodecoder-stsound
kodi-audiodecoder-timidity
kodi-audiodecoder-vgmstream
kodi-api-imagedecoder
kodi-imagedecoder-heif
`E: Unable to locate package kodi-audiodecoder-modplug`
