### ISSUE TITLE
8bitdo SN30 pro 2 controller not recognized

### ISSUE THREAD

**Issue by Travis-Le-Duc** [xbmc/xbmc#21100]
## Bug report
### Describe the bug
8Bitdo SN30 Pro 2 Bluetooth controller not recognized.

This controller cannot be recognized by Kodi. Controller works fine with other software.

## Expected Behavior
The controller should be recognized by Kodi like others controllers.

## Actual Behavior

The controller is not recognized by kodi. No logs about this controller.

### To Reproduce

1. I connect the controller via bluetooth by the operating system Raspbian
2. I launch Kodi and go to settings controller
3. Try to map the controller input

### Debuglog

In Kodi.log, as it is not recognized, so there is nothing about the controller.

### Screenshots
Here is one link to help explain the problem:

[https://github.com/xbmc/xbmc/issues/15127](url)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspbian GNU/Linux 11 (Bullseye)
 - Kodi version: 19.3.0

**Comment by lrusak** [comment]
You should still post a log so we know about your Kodi setup.

Perhaps you don't have peripheral.joystick add-on installed, we just can't know without a log.

**Comment by Travis-Le-Duc** [comment]
Thank you very much!
I didn’t have the peripheral-joysrick add-on, I’ve installed it and the controller is now recognized! 👍👌

**Comment by garbear** [comment]
Lovin' the issues that are closed without me having to do anything :slightly_smiling_face: Do we ship a buttonmap for the SN30 pro 2? If not, would you be willing to upload yours?

**Comment by Travis-Le-Duc** [comment]
I use the controller xbox 360 for mapping, it’s work.

Did I answer your question correctly?

Sorry for my english.
