### ISSUE TITLE
video database not linking movie->uniqueid on addition of new movie

### ISSUE THREAD

**Issue by reardonia** [xbmc/xbmc#21103]
## Bug report

starting with Matrix builds this week (have not bisected), 'movie.c09' is no longer updated with the uniqueid entry. the proper entries are added to the 'uniqueid' table (one for TMDB and one for IMDB) but the c09 field in 'movie' table is not updated. Repro's with current build: Git:20220311-2f11e994f3

### Describe the bug
Add a new movie to a directory (in its own subdirectory), initiate a scan.  Movie is added, but IMDB/TMDB field (c09) in movie table is not added.

## Expected Behavior
movie.c09 field should link to appropriate entry in uniqueid table.

## Actual Behavior
see report

## Possible Fix
unknown

### To Reproduce
see bug descript

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu Jammy
 - Kodi version:
Git:20220311-2f11e994f3

**Comment by KarellenX** [comment]
Using **KodiSetup-20220313-bb4a0702-Matrix-x64.exe**, the most recent build at this time, I cannot replicate your issue.

I will close this report. If you have further information, post back.

**Comment by reardonia** [comment]
Sorry, haven't had time to track down the underlying cause, but the commit that causes this error is here:

c3bb8a2348d678f9fe20d580fc24e617a3981c8f

in xbmc/video/VideoInfoTag.cpp

After this, uniqueid link (episode.c20 or movie.c09) is not properly filled in.

Unfortunately I cannot provide debug logs.

As I mentioned in the original bug report, this is on Linux/Ubuntu.

**Comment by KarellenX** [comment]
@romanvm Any chance you can look at this? I don't remember if you are  using Linux. I checked on Windows and had no issue.

**Comment by romanvm** [comment]
I confirm the issue for cases when movie items have rich NFO files with `uniqueid` tags. I'll investigate this within my current capabilities.

**Comment by KarellenX** [comment]
Thanks @romanvm 
Are  you keeping safe?

**Comment by romanvm** [comment]
Yes so far.

**Comment by thexai** [comment]
Fixed by https://github.com/xbmc/xbmc/pull/21266
