### ISSUE TITLE
image size/placement miscalcuation in SlideShowPicture.cpp; seeking mentor to facilitate my effort to fix

### ISSUE THREAD

**Issue by chaetura9** [xbmc/xbmc#21117]
### Describe the bug
Here is a clear and concise description of what the problem is:

`[Edits: typos; a few words for clarity; new test images with better colors and more informative text.]`
`[Later Edit: I submitted a fix and removed request below for assistance in fixing.]`

During a picture slideshow, Kodi miscalculates the display dimensions of some images and displays them with top and bottom cropped rather than full frame.

Specifically, in a slideshow with pan-and-zoom off, in full screen mode, on a screen with 1920x1080 pixels, Kodi incorrectly displays images having h=1080 and 1600<w<1920. These images are incorrectly upscaled to w=1920, resulting in height h>1080, and the top and bottom of the image are not rendered ("cropped"). More generally, on all screens having 16:9 ratio, the width is incorrectly upscaled to the full width of the screen.

This bug has existed for about ten years on Linux and Windows platforms. I have observed it on multiple machines and monitors over the years. It was originally reported in https://trac.kodi.tv/ticket/16231, but that ticket seems to have disappeared with the change to github. The report was several years old already when I contributed to it in early 2016 (16.1 Jarvis), and I have verified that the bug remains in the latest build of 19.4 Matrix on Windows 10 and Linux. Most of the code in SlideShowPicture.cpp is more than 11 years old.

I attach two test jpg images, one 1600 x 1080  and one 1601 x 1080. Both images render correctly when visited fullscreen directly. The 1601-pixel-wide image renders incorrectly in a slideshow. Markings and captions within the images show and describe the error, and the same kind of error occurs, with progressively fewer omitted pixels, for all images 1080 pixels high and between 1600 and 1920 pixels wide.

-- Matt

![kodi-test-image-1080x1600](https://user-images.githubusercontent.com/101489425/158382971-ca9eb706-b40f-490b-9874-3fcd188f5516.jpg)
![kodi-test-image-1080x1601](https://user-images.githubusercontent.com/101489425/158382972-7f73c701-d919-45f7-9a76-89162bf8a186.jpg)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The 1601-pixel-wide image should be displayed in a slideshow the same as displayed when visited directly, namely, at its natural size of 1601-pixels wide and 1080 pixels high.

## Actual Behavior

The 1601-pixel-wide image is displayed at 1920 pixels wide and implied height of 1295 pixels, losing 107 or 108 pixels along the top and bottom edges.

## Possible Fix

There is an erroneous calculation in SlideShowPicture.cpp, probably in the area of lines 450-650.

### To Reproduce

1. Add my two test images as a source for the Pictures module and visit that folder.
2. Turn off Picture module pan-and-zoom in settings (Settings -> Player -> Pictures). 
3. Display each image full screen on 1920-x-1080 screen by clicking on it.
4. Start a slideshow of the two images.
5. Notice that the 1601-pixel-wide image is incorrectly displayed. Captions and constructed borders within the two images characterize the problem specifically.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/orebutimav

A Pictures module source was already set up containing my two test images. Pan-and-zoom was already turned off. After setting debugging, I launched Kodi, entered the Pictures module, started a slideshow, and used arrow keys to toggle back and forth between the two images twice. Then I navigated to the log-upload-addin and executed it.
### Screenshots 
Here are some links or screenshots to help explain the problem:

The words and borders in the two attached images explain the problem even without needing to load them into Kodi.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

Windows Professional versions 8, 8.1, 10, and 11
Linux Mint from 2015 to 2022.

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows Professional 10 21H2 build 19044.1586
 - Kodi version: from 16.1 (or earlier) through 19.4 build of 3/13/2022 (the one used in the debug log).

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by chaetura9** [comment]
I have now shoehorned my perfect bug report into the mandatory template and uploaded a superfluous mandatory debug log, so the red rebel "ignored rules" badge is now obsolete.

**Comment by KarellenX** [comment]
I've removed the label from the report.
Hopefully a developer will be along soon.
Thanks!!
