### ISSUE TITLE
HLG video file identified as HDR10

### ISSUE THREAD

**Issue by scott967** [xbmc/xbmc#21116]
### Describe the bug
Here is a clear and concise description of what the problem is:

Found while testing new ListItem.HDRType infolabel

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

ListItem.HDRTType/VideoPlayer.HDRType should have value HLG

File is demo file "Norwegen & Mauritius HDR HLG - 4k UHD 10bit Demo" available on Youtube.

File retrieved with youtube-dlp and streams muxed with ffmpeg into mkv (313Mb).
ffprobe -show_streams gives for video stream:

color_range=tv
color_space=bt2020nc
color_transfer=arib-std-b67
color_primaries=bt2020

which color-transfer should  identify stream as HLG.

## Actual Behavior

They have value HDR10

## Possible Fix

Looking at CDVDDemuxFFmpeg, it appears that in line 1676 it is correctly showing color_trc AVCOL_TRC_ARIB_STD_B67 and line 1677 is setting st- >hdr_type to HDR_TYPE_HLG
However, in 1681 the test if (side_data && size) is true and as a result in line 1688 hdr_type is being set to HDR_TYPE_HDR10.  

This seems like a mistake?

### To Reproduce

1. D/L file Norwegen & Mauritius HDR HLG - 4k UHD 10bit Demo from Youtube and add to library
2.Open videos window or play video and observe media flags
3.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ocakerajuh.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

ffprobe output:
https://paste.kodi.tv/elilevonus

link to file download
https://mega.nz/file/SfBVhK5L#HI4CcU6xta4w4TdCjzTD86UNWDl_tryEeO8f8sw6p2M

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows 10 x64 21H2
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi (20.0-ALPHA1 (19.90.101) Git:20220312

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by scott967** [comment]
As a test I modified xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp line 1681

```diff
-        if (side_data && size)
+        if (side_data && size && !(st->hdr_type == StreamHdrType::HDR_TYPE_HLG))
```
     and tested.  Seems to work correctly within the GUI for a variety of video files.

**Comment by quietvoid** [comment]
The better solution would be to change the condition overriding the HDR type, to only do it when no other type was detected already.
The MDCV/ST2086 metadata presence seems to be legal for HLG as well.

**Comment by thexai** [comment]
Tomorrow I will create a PR to separate the HDR type detection code from general HDR side data code.

something like this in a separated method:

```c++
StreamHdrType CDVDDemuxFFmpeg::DetermineHdrType(AVStream* pStream)
{
  StreamHdrType hdrType = StreamHdrType::HDR_TYPE_NONE;

  if (av_stream_get_side_data(pStream, AV_PKT_DATA_DOVI_CONF, nullptr)) // DoVi
    hdrType = StreamHdrType::HDR_TYPE_DOLBYVISION;
  else if (pStream->codecpar->color_trc == AVCOL_TRC_SMPTE2084) // HDR10
    hdrType = StreamHdrType::HDR_TYPE_HDR10;
  else if (pStream->codecpar->color_trc == AVCOL_TRC_ARIB_STD_B67) // HLG
    hdrType = StreamHdrType::HDR_TYPE_HLG;
  // file could be SMPTE2086 which FFmpeg currently returns as unknown
  // so use the presence of static metadata to detect it
  else if (av_stream_get_side_data(pStream, AV_PKT_DATA_MASTERING_DISPLAY_METADATA, nullptr))
    hdrType = StreamHdrType::HDR_TYPE_HDR10;

  return hdrType;
}
```

and in current place use:

`st->hdr_type = DetermineHdrType(pStream);`

**Comment by scott967** [comment]
OK I opened PR 21123 for this, but your solution is probably better. @thexai want me to close that PR?

**Comment by thexai** [comment]
Yes thanks, in fact it's been a while since I wanted to create the PR in preparation to add HDR10+ and simplify things.

This specific case with HLG seems rare since HLG is precisely characterized by not needing metadata but it would still be resolved.

It appears to be a hybrid file looking for compatibility for HLG to HDR10 conversion. In this case, the metadata would be used once converted to HDR10 (conversion is easy but involves changing the transfer function from HLG to PQ).
