### ISSUE TITLE
Crash after update to Kodi 19.4

### ISSUE THREAD

**Issue by schmidchr** [xbmc/xbmc#21119]
### Describe the bug
Here is a clear and concise description of what the problem is:

freshly updated Kodi crashes with segmentation fault after a few seconds, subsequent to upgrade via ppa

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

stable as previously installed version 19.3 

## Actual Behavior

Kodi starts seemingly normal, top indicates reasonable systems resources
-> after ~10s becomes nonreactive, and crash
 behavior reproduced after system reboot

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/joyunuyebo.kodi

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by wsnipex** [comment]
you might be hitting https://bugs.launchpad.net/ubuntu/+source/libva/+bug/1961484

you can try to update libva2* from my ppa: https://launchpad.net/~wsnipex/+archive/ubuntu/vaapi

**Comment by Vertabreak** [comment]
been experiencing crashes with segmentation fault since the open beta of Ubuntu jammy started and have tried all the available versions none of them work. kodi opens but as soon as you try to do much of anything it stops responding and crash's have tested on 6 systems running jammy all the same result. seems the issue does not exist on android but i have not tested on windows.
