### ISSUE TITLE
XBMC failed to build with error2664 with MSVC on windows amd64

### ISSUE THREAD

**Issue by Vincent9802** [xbmc/xbmc#21134]
Hi All,

Environment:
VS 2019 + Windows Server 2019

XBMC failed to build with error2664 with MSVC on windows amd64. It can be reproduced on latest version  47a9322 on master branch. Could you please help look at this issue?

**Repro steps:**

1. git clone https://github.com/xbmc/xbmc F:\gitP\xbmc\xbmc
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
3. cd F:\gitP\xbmc\xbmc\build_amd64
4. xcopy F:\gitP\xbmc\tools\x64 F:\gitP\xbmc\xbmc\project\BuildDependencies\x64 /k/r/e/i/s/c/h/f/y
5. xcopy F:\gitP\xbmc\tools\mingwlibs\x64 F:\gitP\xbmc\xbmc\project\BuildDependencies\mingwlibs\x64 /k/r/e/i/s/c/h/f/y
6. xcopy F:\gitP\xbmc\tools\build\ffmpeg-x64 F:\gitP\xbmc\xbmc\project\BuildDependencies\build\ffmpeg-x64 /k/r/e/i/s/c/h/f/y
7. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 .. 2>&1
8. set _LINK_=%_LINK_% /alternatename:__imp_fribidi_remove_bidi_marks=fribidi_remove_bidi_marks /alternatename:__imp_fribidi_log2vis=fribidi_log2vis
9. msbuild /m /p:Platform=x64 /p:Configuration=Release kodi.sln /t:Rebuild 2>&1

log:  [build.log](https://github.com/xbmc/xbmc/files/8280998/build.log)

**Error info:**
F:\gitP\xbmc\xbmc\xbmc\cores\VideoPlayer\DVDSubtitles\DVDSubtitlesLibass.cpp(132,5): error C2664: 'void ass_add_font(ASS_Library *,char *,char *,int)': cannot convert argument 2 from 'const _Elem *' to 'char *' [F:\gitP\xbmc\xbmc\build_amd64\libkodi.vcxproj]

**Comment by thexai** [comment]
Seems you are using a custom build script that not follows Kodi documented build steps in https://github.com/xbmc/xbmc/blob/master/docs/README.Windows.md

specially cmake configure command should be (using your path):

`cmake -G "Visual Studio 16 2019" -A x64 -T host=x64 F:\gitP\xbmc\xbmc`

and build command:

`cmake --build . --config "Release"`

Anyway you can try replace in `...cores\VideoPlayer\DVDSubtitles\DVDSubtitlesLibass.cpp` L132 with:

`ass_add_font(m_library, (char*)(fileName.c_str()), (char*)(buffer.data()),`

This should fix this specific compilation error.

Although this error does not occur with Visual Studio 2017 / 2019 / 2022 (Community Edition)

Do not have "Enterprise" edition to test with it.

**Comment by thexai** [comment]
I'm going to close this as it's not an issue using the build steps outlined in README.Windows.md with VS 2019/2022.

If you're still having trouble building, use forum.kodi.tv for support.
