### ISSUE TITLE
Kodi unable to play remote files with space in their filenames

### ISSUE THREAD

**Issue by Mayzie** [xbmc/xbmc#21144]
#  Bug report
## Description

Kodi is unable to request remote (HTTP) files that contain a space in their filenames.

## Actual Behavior

When attempting to load a playable file (video, subtitle, or audio file) from a remote source that contains a space in its name, Kodi does not request this file and an error occurs preventing playback. When reproducing, you will notice that Kodi does not even submit a HTTP GET request to the server while the path contains a space.

## To Reproduce

*NOTE: Know your machine's IP (`<machine_ip>`) in advance.*

1. On a remote (LAN or WAN, doesn't matter) machine, create a directory and place a playable file into that directory. Ensure the filename contains space characters. For example, `Big Buck Bunny.mkv`.
2. Establish a local HTTP server, serving files from that directory. (e.g. `python3 -m http.server 80`, or `npx http-server -p 80`; although note if using the latter, you will need to create a custom `index.html` file inside that directory as Kodi cannot parse the autogenerated autoindex).
3. Add a source to Kodi. Settings> File Manager> Add Source> `<machine_ip>` and give it a name.
4. In Kodi, open that source, and attempt to play a file. Go back and view the server logs, and you'll see Kodi `GET` the initial directory, but won't even attempt to establish a connection for a file with a space in its name.
5. Rename the file to remove any space characters, and repeat the above step (step 4). You'll notice Kodi plays this file fine.

## Debuglog

For whatever reason, I could not get a debug log. I enabled debugging, but even having done that and setting the level to INFO, there are no log messages in the event log other than "Kodi started successfully". Although, this is probably a separate issue.

## Your Environment
Used Operating system:

 - [x] Android
 - Operating system version/name: Android 11, NVIDIA SHIELD PRO 2019
 - Kodi version: v19.4 ARM64 (installed via APK).

**Comment by wsnipex** [comment]
your test case is invalid, since those simple "one off" webservers don't provide a directory listing kodi understands.
Try with apache, nginx or lighttpd

**Comment by Mayzie** [comment]
> your test case is invalid, since those simple "one off" webservers don't provide a directory listing kodi understands. Try with apache, nginx or lighttpd

Hi @wsnipex !

Um, Python does (at least in 3.10.x), and I mentioned if you were to use the Node.js package `http-server` you would need to create your own `index.html` file in a format Kodi understands. This format can be as simple a just containing a bunch of links to files, like so:

```html
<a href="Big Buck Bunny.mkv">Big Buck Bunny.mkv</a>
<a href="Big.Buck.Bunny.mkv">Big.Buck.Bunny.mkv</a>
```

In any case, Kodi does list the contents of the Source correctly. It just cannot load filenames (does not even attempt a request) with a space character in their name.

**Comment by wsnipex** [comment]
that's because the whitespace must be urlencoded. If the index.html does return urlencoded URIs, kodi should be able to play it

**Comment by DaVukovic** [comment]
Just to mention it....wo already have an older report which seems to be pretty related:

https://github.com/xbmc/xbmc/issues/20975

While using a real webserver like apache, one might be able to create rewrite-rules for whitespaces. So the webserver will take care of it.
