### ISSUE TITLE
No ordena la biblioteca como en la guia

### ISSUE THREAD

**Issue by Marioteli** [xbmc/xbmc#21160]
## Informe de error

### Describir el error He aquí una descripción clara y concisa de cuál es el problema:       ## Comportamiento real      ## Posible solución      ### Para Reproducir Pasos para reproducir el comportamiento:    1. 2. 3.   ### Debuglog   El registro de depuración se puede encontrar aquí:    ### Capturas de pantalla Aquí hay algunos enlaces o capturas de pantalla para ayudar a explicar el problema:     ## Contexto adicional o capturas de pantalla (si procede) Aquí hay un contexto o explicación adicional que podría ayudar:      ### Tu entorno Sistema operativo usado:   - [ ] Android - [ ] iOS - [ ] tvOS - [ ] Linux - [ ] OSX - [ ] Windows - [ ] Windows UWP  - Versión/nombre del sistema operativo: - Versión Kodi:     *nota: Una vez que se realice el problema, le pedimos que lo actualice con nueva información o versiones de Kodi en caso de que sea necesario. El equipo Kodi considerará su informe de problemas, sin embargo, no haremos ninguna promesa de que el problema se resolverá. *

**Comment by enen92** [comment]
Please use english only and follow the template, fixing possible issues is already a lot of effort let alone understand your bug report...
