### ISSUE TITLE
TrueHD passthrough option is not available anymore in Kodi 19.0 for A95X F4

### ISSUE THREAD

**Issue by hubdubeggs** [xbmc/xbmc#21171]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have the A95x F4 box that should output True Hd audio
The true Hd audio option is missing from Kodi 19

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

True HD audio output is missing in Kodi 19 

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/kofaticune

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ this one ] Android
Android 10 and 11
Tried box 
- [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
v18, 19 and 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Downgrade your firmware to the working one. The version you are running does not support it. The log is clear here.
