### ISSUE TITLE
make[2]: *** [arm-osx-native] Error 1

### ISSUE THREAD

**Issue by jerry-mengbo** [xbmc/xbmc#21189]
### Describe the bug
I use MacBook pro M1 laptop, when I build iOS project , https://github.com/xbmc/xbmc/blob/master/docs/README.iOS.md
Here is my command 
cd $HOME
git clone https://github.com/xbmc/xbmc kodi

cd $HOME/kodi/tools/depends
./bootstrap
./configure --host=aarch64-apple-darwin --with-platform=ios

Build tools and dependencies:
make -j$(getconf _NPROCESSORS_ONLN)

This command  make -j$(getconf _NPROCESSORS_ONLN) I got the error.

Utilities/std/cm/map: Can't unlink already-existing object
Utilities/std/cm/memory: Can't unlink already-existing object
Utilities/std/cm/optional: Can't unlink already-existing object
Utilities/std/cm/set: Can't unlink already-existing object
Utilities/std/cm/shared_mutex: Can't unlink already-existing object
Utilities/std/cm/string: Can't unlink already-existing object
Utilities/std/cm/string_view: Can't unlink already-existing object
Utilities/std/cm/type_traits: Can't unlink already-existing object
Utilities/std/cm/unordered_map: Can't unlink already-existing object
Utilities/std/cm/unordered_set: Can't unlink already-existing object
Utilities/std/cm/utility: Can't unlink already-existing object
Utilities/std/cm/vector: Can't unlink already-existing object
Utilities/std/cmSTL.hxx.in: Can't unlink already-existing object
Utilities/std/cmext/: Can't restore time
Utilities/std/cmext/algorithm: Can't unlink already-existing object
Utilities/std/cmext/iterator: Can't unlink already-existing object
Utilities/std/cmext/memory: Can't unlink already-existing object
Utilities/std/cmext/string_view: Can't unlink already-existing object
Utilities/std/cmext/type_traits: Can't unlink already-existing object
tar: Error exit delayed from previous errors.
make[2]: *** [arm-osx-native] Error 1
make[1]: *** [cmake] Error 2
make: *** [native/.installed-arm-osx-native] Error 2
jerry.m@Jerry-mengbo depends % 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I can  Build tools and dependencies:

## Actual Behavior

I got 2 errors

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
I use OSX  version 12.1

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
I don't think this configuration is supported. @fuzzard can you confirm?

**Comment by fuzzard** [comment]
Yeah it works, take it to the forums for support though

**Comment by jerry-mengbo** [comment]
@fuzzard why I need to go to the forums?

**Comment by jerry-mengbo** [comment]
@fuzzard  Does is this need money?

**Comment by fuzzard** [comment]
We don't provide support via GitHub issues. This is for bugs only. Building iOS on M1 works fine with master, so it's a support issue. Make a post on the forums, ping my name and I'll work with you there

**Comment by jerry-mengbo** [comment]
@fuzzard  thx
