### ISSUE TITLE
When French labels are too long in settings, we can't see the selected values next to the label

### ISSUE THREAD

**Issue by darodi** [xbmc/xbmc#21184]
### Describe the bug
Here is a clear and concise description of what the problem is:

When French labels are too long in settings, we can't see the selected values next to the label

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

labels not too long, be able to see the selected values in settings

## Actual Behavior

French labels too long in settings, unable to see the selected values

## Possible Fix

Scrolling label shorter on the left, show selected value every time.

### To Reproduce

1. change regional language to French in Kodi
2. go to inputstream adaptive settings
3. cry because you cannot see the settings values

### Debuglog

The debuglog can be found here:
**not applicable**

### Screenshots
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/4682830/159583808-c0ebacd3-351a-4b9f-922d-98bb98ccf236.png)
![image](https://user-images.githubusercontent.com/4682830/159583905-3e3b5ee8-4412-46fe-903c-48ccc2dc01df.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

- [ ] Android
- [ ] iOS
- [ ] tvOS
- [x] Linux
- [ ] OSX
- [x] Windows
- [ ] Windows UWP

- Operating system version/name:
- Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by darodi** [comment]
linked to https://github.com/xbmc/inputstream.adaptive/issues/918

**Comment by gade01** [comment]
@darodi 
I added your new shorter labels here: https://github.com/xbmc/inputstream.adaptive/pull/920
Will merge once checks complete.

**Comment by enen92** [comment]
@CastagnaIT can this one be closed?

**Comment by CastagnaIT** [comment]
for the spin control case is solved

but also edit control will need to be fixed, have similar problem:
![immagine](https://user-images.githubusercontent.com/3257156/162708590-65a56049-9c1a-408c-9b30-f063806e9484.png)
 left label overlap value field on the right
