### ISSUE TITLE
Port / Firewal

### ISSUE THREAD

**Issue by spirillen** [xbmc/xbmc#21207]
### Describe the bug
It appears that jellyfin for kodi are somehow not using the standard ports for NFSv4 111/2049 for connecting (lookup) to the NFS server.

Here is the rules I have in my firewall, which is working fine on any other linux client on the network.

```
# NFS Server share
udp dport nfs ip saddr $rfc_1918 counter accept comment "NFS"
tcp dport nfs ip saddr $rfc_1918 counter accept comment "NFS"
udp dport sunrpc ip saddr $rfc_1918 counter accept comment "SunRPC"
tcp dport sunrpc ip saddr $rfc_1918 counter accept comment "SunRPC"
# meta l4proto { tcp, udp } th dport { sunrpc, nfs } ip saddr $rfc_1918 accept comment "Accept NFS"
```

## Expected Behavior
Playing via port 2049 (NFS) share and not on limited http

## Possible Fix
Document which port should be accessible in firewall for kodi client

The question is, which ports are required on the NFS to be open for Kodi to work?

### To Reproduce
1.  Setup NFSv4 share in jellifyn for kodi
2. Start playing a video 60 timeout, then using http
3. Check network traffic on ports

### Screenshots 
![image](https://user-images.githubusercontent.com/44526987/160696938-e41b17c5-7915-4415-b331-ada4472480f1.png)

### Your Environment
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:Watching a movie....

First posted here https://github.com/jellyfin/jellyfin-kodi/issues/626

**Comment by lrusak** [comment]
Please use the forum for support. https://forum.kodi.tv/

**Comment by spirillen** [comment]
Seems impossible 

![image](https://user-images.githubusercontent.com/44526987/160706021-49e61463-fa2b-4c42-a117-faff71f45653.png)

**Comment by spirillen** [comment]
oh yeah I'm not gonna give you any email address you can sell to lowest bitter
