### ISSUE TITLE
Recent commit may have broke building on raspbian

### ISSUE THREAD

**Issue by triplejam** [xbmc/xbmc#21208]
### Describe the bug
Here is a clear and concise description of what the problem is:

The commit a5d17f691212e93d0a1eeadfd3b8fe19d1237fee changed how gettid is called on linux. Building natively on raspbian (arm) errors out on file xbmc/platform/linux/threads/ThreadImplLinux.cpp

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi is built without compilation error.

## Actual Behavior

Build errors out because gettid() is not defined.

## Possible Fix

I reverted the change in my build and that fixed the issue. But probably someone knowledgable about the platform should look more into it.

### To Reproduce

1. Cloned repo about at the time of this post 09a30d920af6ac2d8f624f243a1d6e6f23b28749
2. Built from cmake

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux / Raspbian Buster
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by wsnipex** [comment]
see https://github.com/xbmc/xbmc/pull/21209
