### ISSUE TITLE
Silent installer hangs 

### ISSUE THREAD

**Issue by tim-lebedkov** [xbmc/xbmc#21225]
### Describe the bug
Here is a clear and concise description of what the problem is:

Running the following command 

```cmd
installer.exe /S /D=%CD%
```

hangs for this binary: http://mirrors.kodi.tv/releases/windows/win32/kodi-19.4-Matrix-x86.exe

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
the installation should be silent

## Actual Behavior

A dialog is shown.

## Possible Fix

genNsisInstaller.nsi should be probably changed.

### To Reproduce

1. run the mentioned command 

### Debuglog

The debuglog can be found here: 
https://ci.appveyor.com/project/tim-lebedkov/npackd/builds/43114882/job/3qmx1du9b28gmbi8#L483

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Tested and not reproduced: 
Installer runs fine (not hangs), even in silent mode is displayed a warning of 64-bit versions available.

![Screenshot_2](https://user-images.githubusercontent.com/58434170/162318577-c736903e-e2a6-4356-a769-53daa64d64ae.png)
