### ISSUE TITLE
Crashes on launch Arch

### ISSUE THREAD

**Issue by nzyuko** [xbmc/xbmc#21231]
### I get segfault on launching kodi
Here is a clear and concise description of what the problem is:

## Expected Behavior
Should launch the Kodi startup window

## Actual Behavior

/usr/bin/kodi: line 186:  7029 Segmentation fault      (core dumped) ${KODI_BINARY} $SAVED_ARGS

### To Reproduce

1. Installed Kodi from the arch repository
2.launched kodi from terminal
3.got segfaultUsed Operating system:

###Environment

 - Operating system version/name: Arch Linux 
 - Kernel Version: 5.15.32-1-lts

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by L2501** [comment]
downgrade python to 3.9.9 or lower.

**Comment by lrusak** [comment]
Please follow the template and post a debug log and/or crash log and your issue can be re-evaluated.
