### ISSUE TITLE
Failed to open VDPAU backend libvdpau

### ISSUE THREAD

**Issue by nzyuko** [xbmc/xbmc#21232]
##Returns this message followed by segmantation fault
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
##The Segmentation Fault
/usr/bin/kodi: line 186: 18886 Segmentation fault      (core dumped) ${KODI_BINARY} $SAVED_ARGS

**Comment by lrusak** [comment]
Please use the forum for support. https://forum.kodi.tv/
