### ISSUE TITLE
Ignore Articles Not Respected if Sorting by Episode Count

### ISSUE THREAD

**Issue by pkscout** [xbmc/xbmc#21252]
### Describe the bug
Here is a clear and concise description of what the problem is:

When you have your TV show list sorted by episode count, shows with the same count are sorted alphabetically, kind of.  The sort order in that case doesn't respect the setting for ignored articles, so shows starting with, for instance, 'The' are sorted in the Ts.  Please see screenshot for example where "The Flash" is not sorted as "F":

<img width="1391" alt="Screen Shot 2022-04-10 at 5 55 27 PM" src="https://user-images.githubusercontent.com/1402018/162641818-14f5f009-19f0-4760-acce-78b32bc0b088.png">

The same shows sorted by Title properly ignore the article and put "The Flash" in with the Fs.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When sorting by episode, the second sort of title should respect the ignore article when sorting setting.

## Actual Behavior

When sorting by episode, the second sort of title uses the article in the sort.

### To Reproduce

1. Have some TV shows with the same number of episodes and at least one with a leading article.
2. Sort by Episode count and view the results.
3. Sort by Title to see the different (correct) behavior.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

Nexus nightly build, although this has been happening since Leia or even earlier.  I've just never gotten around to submitting a bug report.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Also happens when sorting by My Rating. 

![sort1](https://user-images.githubusercontent.com/44626605/162649131-a81c2af7-cf00-4d61-919d-70a72abf36f4.jpg)


![sort2](https://user-images.githubusercontent.com/44626605/162649143-e92454ac-b62f-4ef9-b18c-4c0289975a82.jpg)
