### ISSUE TITLE
Kodi picks up wrong "year" for PVR recording.

### ISSUE THREAD

**Issue by thomazz-nl** [xbmc/xbmc#21253]
### Describe the bug
Here is a clear and concise description of what the problem is:

In a Kodi setup with shared MySQL DB (probably not relevant), a Tvheadend backend and the Trakt addon, I discovered that Kodi was not correctly obtaining/setting the "year" field for recording entries in Tvheadend. This caught my eye as I was backtracking an issue where the Trakt addon was unable to scrobble playback of PVR recordings because it missed "year" info.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect Kodi to correctly import the PVR recording's "year" field for movies and tvshows on a tvheadend backend (if the info is available) or keep the field empty (if the information is not present). Kodi should not change or interpret the presented year differently.

## Actual Behavior

Reading the Trakt debug lines in the log I noticed that upon playback of a PVR recording, Kodi returns an empty value for "year" in the InfoLabel ```xbmc.getInfoLabel('VideoPlayer.Year')``` and consecutively the Filename ```xbmc.getInfoLabel('Player.Filename')``` returns invalid values (like 1969 or 1601). Just to be clear: such values are not present in the recording information on the backend, so where is Kodi getting these values from? Does it have anything to do with issue #17309? The tvheadend [recordings](https://github.com/xbmc/xbmc/files/8460413/recordings.zip) actually have the copyright_year field set to 2020 and 2022.

## Possible Fix

I don't have a fix, but starting from the origin of the "not-actual" filenames I started digging my way back through code I found  the following related lines (useful for breakpoints):
- This is where the pvr recording filename/path is constructed: [PVRRecordingsPath.cpp#L121](https://github.com/xbmc/xbmc/blob/7478f983b67dc1e3b09e061acf2eaa675b0f0170/xbmc/pvr/recordings/PVRRecordingsPath.cpp#L121)
- The year was set here: [PVRRecordingsPath.cpp#L101](https://github.com/xbmc/xbmc/blob/7478f983b67dc1e3b09e061acf2eaa675b0f0170/xbmc/pvr/recordings/PVRRecordingsPath.cpp#L101)
- The path construction was called from here: [PVRRecording.cpp#L461](https://github.com/xbmc/xbmc/blob/f311298afb5910d3b0e4b9901c08156f2118c347/xbmc/pvr/recordings/PVRRecording.cpp#L461)
- GetYear() returns the m_premiered value set here: [PVRRecording.cpp#L592](https://github.com/xbmc/xbmc/blob/f311298afb5910d3b0e4b9901c08156f2118c347/xbmc/pvr/recordings/PVRRecording.cpp#L592)

If year is some odd small or negative value, could the result of CDateTime here be something like epoch (1970) - x = 1969? Although that doesn't explain the value 1601. Also I wonder if m_premiered (I guess the date the show/movie premiered) makes sense to be appointed the copyright_year from upstream pvr.hts or tvheadend. Year retrieval was introduced to pvr.hts [here](https://github.com/kodi-pvr/pvr.hts/commit/9e58cbb0650a23a14709329050ee439cae9f219f) after [pvr-hts issue #340](https://github.com/kodi-pvr/pvr.hts/issues/340). Maybe it has something to do with the uint32_t datatype specified [here](https://github.com/kodi-pvr/pvr.hts/blob/5486bce5bfd20e947885c28a46750d3140989d4c/src/tvheadend/entity/Event.h#L119), but in that case this issue needs to be moved to the pvr-hts repo.

### To Reproduce

1. If reproducing with own recordings doesn't work, place the recordings provided earlier in the appropriate tvheadend path (something like ```/path/to/tvheadend/dvr/log```) and edit the "filename" values to point to mock videofiles or recordings you have available. Unsure if edits of the fields channel, config_name, autorec are also needed.
2. On a Kodi installation, install/enable the pvr.hts plugin and configure it appropriately.
3. In Kodi, go to TV > Recordings and play the PVR recording for a bit, then stop it. A progress state should be saved to the database.
4. Check the values in the database: ```SELECT * FROM `files` WHERE `strFilename` LIKE '%.pvr' ORDER BY `strFilename` ```

### Debuglog

The debuglog can be found here:
A debuglog might be provided later upon request.
Kodi just constructs/uses a file-/pathname/uri to reference the recording and as long as playback works, all is fine for Kodi. It won't generate detailed lines in the log.

### Screenshots 
Here are some links or screenshots to help explain the problem:

Reading the strange year in the Player.Filename value ```Gold Rush s12e24 (1601) Buckets Full of Gold, TV (Discovery HD), 20220404_182000, 1891807697.pvr``` made me look up more filenames in the database and there were more occurrences:
![MyKodiVideos119-files-pvr](https://user-images.githubusercontent.com/10218628/162647193-df7d3d92-b94e-470e-89ac-70785f0c8ecc.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC (aarch64) / Windows 10 Pro 21H2 (AMD64)
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Confirmed as fallout from #18430.

The fix to prevent invalid years caused by invalid `CDateTime m_premiered` (1601 on Windows, 1969 all other Kodi platform) is easy, but the problem is that the "wrong" paths (including "(1601)" or "(1969)") are used as keys in the video database to store play count and/or resume points for the recordings. I will see what I can do about this.
