### ISSUE TITLE
video crash for HLS stream fail when skipping or resuming

### ISSUE THREAD

**Issue by TermeHansen** [xbmc/xbmc#21267]
### Describe the bug
When watching streams from plugin.video.drnu (I'm the maintainer) the playback crash when trying to skip in video stream or resume playback.

Also starting the [mp4](https://drod24h.akamaized.net/all/clear/none/fc/624c53deaa5a6111bc8159fc/00952230060/stream_fmp4/19575097-a75b561f-f745-4a43-8fff-2610720df62d-1_video_2000.mp4) from a browser (tested with Firefox) and one can skip forward in the video (although duration is missing for the mp4).

## Expected Behavior
To be able to skip and resume a HLS video stream

## Actual Behavior
video playback stops after a bit of waiting (no errors reported in gui)

### To Reproduce
Start the stream: [https://drod24h.akamaized.net/all/clear/none/fc/624c53deaa5a6111bc8159fc/00952230060/stream_fmp4/19575097-a75b561f-f745-4a43-8fff-2610720df62d-1_video_2000.m3u8](https://drod24h.akamaized.net/all/clear/none/fc/624c53deaa5a6111bc8159fc/00952230060/stream_fmp4/19575097-a75b561f-f745-4a43-8fff-2610720df62d-1_video_2000.m3u8) and skip forward and kodi will crash (tested on kodi19.4 on ubuntu and on osmc on a raspberry pi 3)

### Optional fix
If I use the `.mp4` as listed in the `.m3u8` file, it works (like in the browser), but with a bit of waiting time when starting the stream - so what is wrong with the m3u8 file?

### Debuglog
The debuglog can be found here:[https://pastebin.com/LSQPLJ4w](
https://pastebin.com/LSQPLJ4w)
```
2022-04-13 18:44:45.644 T:159104   DEBUG <general>: demuxer seek to: 605637.000000
2022-04-13 18:44:45.651 T:159104   DEBUG <general>: SeekTime - unknown position after seek
2022-04-13 18:44:45.651 T:159104   DEBUG <general>: demuxer seek to: 605637.000000, success
```
Seems like it actually do jump correctly or?!? 

## Additional context or screenshots (if appropriate)
Seeing the stream in VLC works fine for skipping, although VLC also gives some output of problems (see below).

```
$ vlc https://drod24h.akamaized.net/all/clear/none/fc/624c53deaa5a6111bc8159fc/00952230060/stream_fmp4/19575097-a75b561f-f745-4a43-8fff-2610720df62d-1_video_2000.m3u8 -v
VLC media player 3.0.9.2 Vetinari (revision 3.0.9.2-0-gd4c1aefe4d)
[00007f20700021e0] mp4 demux warning: elst box found
[00007f20700021e0] mp4 demux warning: no chunk defined
[00007f20700021e0] mp4 demux warning: STTS table of 0 entries
[00007f20700021e0] mp4 demux: Fragment sequence discontinuity detected 1 != 0
[00007f208031c730] avcodec decoder: Using Intel i965 driver for Intel(R) Sandybridge Mobile - 2.4.0 for hardware decoding
[h264 @ 0x7f2080052340] Using deprecated struct vaapi_context in decode.
[h264 @ 0x7f2080052340] get_buffer() failed
[h264 @ 0x7f2080052340] thread_get_buffer() failed
[h264 @ 0x7f2080052340] decode_slice_header error
[h264 @ 0x7f2080052340] no frame!
[00007f20700021e0] mp4 demux warning: elst box found
[00007f20700021e0] mp4 demux warning: no chunk defined
[00007f20700021e0] mp4 demux warning: STTS table of 0 entries
[00007f20700021e0] mp4 demux: Fragment sequence discontinuity detected 31 != 0
[h264 @ 0x7f2080052340] Using deprecated struct vaapi_context in decode.
[h264 @ 0x7f2080052340] get_buffer() failed
[h264 @ 0x7f2080052340] thread_get_buffer() failed
[h264 @ 0x7f2080052340] decode_slice_header error
[h264 @ 0x7f2080052340] no frame!
[h264 @ 0x7f20803554c0] get_buffer() failed
[h264 @ 0x7f20803554c0] thread_get_buffer() failed
[h264 @ 0x7f20803554c0] decode_slice_header error
[h264 @ 0x7f20803554c0] no frame!
``` 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 Ubuntu 20.04 and OSMC (stable)
 - Kodi version:
 19.4

**Comment by glennguy** [comment]
I can only speak for myself (but am sure others would agree) that using inputstream.adaptive to play HLS manifests is much more supported than the inbuilt ffmpeg.

For your add-on you can try:
```
item.setProperty('inputstream', 'inputstream.adaptive')
item.setProperty('inputstream.adaptive.manifest_type', 'hls')
```

Some advantages:
* Faster to start playback. You can provide the master m3u8 rather than the sub m3u8 and still retain a fast playback start. I'm sure you've observed that without using IA for playback ffmpeg will first download *every* sub m3u8 and the first segment from each which can take several seconds. 
* Kodi 20/inputstream.adaptive is bringing support for adaptive bitrate switching and segment buffering
* Support for discontinuities. IA will use discontinuity tags in the manifest to mark boundaries and present to Kodi as chapters.
* Ability to seek on live streams

**Comment by TermeHansen** [comment]
@glennguy thank you so much for this pointer to a new feature of kodi for this kind of item. It seems to solve my issue here indeed.

I will close this issue then.
