### ISSUE TITLE
IsStandAlone is set to late after PR #21200

### ISSUE THREAD

**Issue by Portisch** [xbmc/xbmc#21284]
### Describe the bug
Here is a clear and concise description of what the problem is:

Setting is hidden because of wrong status of requirement [IsStandAlone](https://github.com/xbmc/xbmc/blob/master/system/settings/settings.xml#L2503)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

[IsStandAlone](https://github.com/xbmc/xbmc/blob/master/xbmc/Application.h#L271) need to be initialized before SettingsConditions get initialized.

## Actual Behavior

[m_bStandalone](https://github.com/xbmc/xbmc/blob/master/xbmc/Application.cpp#L335) is set to late.

### To Reproduce

1. Start kodi as standalone application and the `Refresh rate` setting is hidden

### Debuglog

The debuglog can be found here:
There is no debug log possible as CLog isn't initialized yet.
Debug prints by:
```c
diff --git a/xbmc/Application.cpp b/xbmc/Application.cpp
index bde74257ad..09d750b685 100644
--- a/xbmc/Application.cpp
+++ b/xbmc/Application.cpp
@@ -92,7 +92,6 @@
 #include "utils/SystemInfo.h"
 #include "utils/TimeUtils.h"
 #include "utils/XTimeUtils.h"
-#include "utils/log.h"
 #include "windowing/WinSystem.h"
 #include "windowing/WindowSystemFactory.h"
 
@@ -332,6 +331,7 @@ bool CApplication::Create(const CAppParamParser &params)
 
   m_bPlatformDirectories = params.HasPlatformDirectories();
   m_bTestMode = params.IsTestMode();
+  MYLOG(__FILE__, __FUNCTION__, __LINE__);
   m_bStandalone = params.IsStandAlone();
   m_windowing = params.GetWindowing();
   m_logTarget = params.GetLogTarget();
diff --git a/xbmc/Application.h b/xbmc/Application.h
index 1ddf3ca954..2123bf139e 100644
--- a/xbmc/Application.h
+++ b/xbmc/Application.h
@@ -28,6 +28,7 @@
 #include "threads/Thread.h"
 #include "utils/GlobalsHandling.h"
 #include "utils/Stopwatch.h"
+#include "utils/log.h"
 #include "windowing/OSScreenSaver.h"
 #include "windowing/Resolution.h"
 #include "windowing/XBMC_events.h"
@@ -268,7 +269,7 @@ public:
 
   int GlobalIdleTime();
 
-  bool IsStandAlone() { return m_bStandalone; }
+  bool IsStandAlone() { MYLOG(__FILE__, __FUNCTION__, __LINE__); return m_bStandalone; }
   bool IsEnableTestMode() { return m_bTestMode; }
 
   const std::string& GetLogTarget() const { return m_logTarget; }
diff --git a/xbmc/settings/SettingConditions.cpp b/xbmc/settings/SettingConditions.cpp
index fb4201f114..32182f44d8 100644
--- a/xbmc/settings/SettingConditions.cpp
+++ b/xbmc/settings/SettingConditions.cpp
@@ -28,6 +28,7 @@
 #include "utils/FontUtils.h"
 #include "utils/StringUtils.h"
 #include "windowing/WinSystem.h"
+#include "utils/log.h"
 
 bool AddonHasSettings(const std::string& condition,
                       const std::string& value,
@@ -420,8 +421,12 @@ void CSettingConditions::Initialize()
 #ifdef TARGET_ANDROID
   m_simpleConditions.insert("isstandalone");
 #else
+  MYLOG(__FILE__, __FUNCTION__, __LINE__);
   if (g_application.IsStandAlone())
+  {
+    MYLOG(__FILE__, __FUNCTION__, __LINE__);
     m_simpleConditions.insert("isstandalone");
+  }
 #endif
 
   m_simpleConditions.insert("has_ae_quality_levels");
diff --git a/xbmc/utils/log.h b/xbmc/utils/log.h
index 52e973e54e..58c2d24353 100644
--- a/xbmc/utils/log.h
+++ b/xbmc/utils/log.h
@@ -36,6 +36,11 @@
 
 #include <spdlog/spdlog.h>
 
+#include <iostream>
+static void MYLOG (const char* _file, const char* _function, const int line){
+   std::cerr << "[" << _function << "] " << line << " in " << _file << std::endl;
+}
+
 namespace spdlog
 {
 namespace sinks
```

In `log.h` prints these lines on console:
```text
[Initialize] 432 in xbmc/settings/SettingConditions.cpp
[IsStandAlone] 272 in xbmc/Application.h
[IsStandAlone] 272 in xbmc/Application.h
[IsStandAlone] 272 in xbmc/Application.h
[Create] 338 in xbmc/Application.cpp
[IsStandAlone] 272 in xbmc/Application.h
```

This shows clear the variable `m_bStandalone` is accessed before initialized.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Nexus Nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@ksooo (cross reference to linked pr:https://github.com/xbmc/xbmc/pull/21200)

**Comment by Portisch** [comment]
I am sure much more issues will pop up in future like https://github.com/xbmc/xbmc/issues/21240.
The CLog class is already destroyed and get accessed by CFDEventMonitor afterwards on thread stop.

The start/create/init/stop/unregister/destroy chains are now completely messed up.

**Comment by ksooo** [comment]
Yes, and those issues need to be fixed to finally get a well defined stop/uninit/destroy chain. Before it all was a mess and worked only, because the logging component was never destroyed or to be more precise, being a global static variable it was destroyed at a random point in time while the application exited.

Regarding IsStandAlone: Another design flaw that needs to be fixed. Application depends on settings and settings depends on Application (circular dependency).

**Comment by ksooo** [comment]
`XBMC_GLOBAL_REF(CFDEventMonitor, g_fdEventMonitor);`

 Yep, another static global instance, which gets destroyed at a random point in time when Kodi exits. Fix is to get rid of it by constructing/destructing it in a controllable manner.

**Comment by Portisch** [comment]
Yes, it's a problem and the structure about construction and destruction needs to be fixed to avoid randomly happen segment faults. But this will result in some work... ☹️
