### ISSUE TITLE
Kodi 20: Blu-ray playback resumes from wrong episode

### ISSUE THREAD

**Issue by Dis90** [xbmc/xbmc#21285]
### Describe the bug
Here is a clear and concise description of what the problem is:

When resuming partially watched Blu-ray Kodi resumes playback from correct time but wrong episode. In this case I was watching episode 2 but Kodi resumes episode 3.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi to resume playback in correct episode.

## Actual Behavior

Kodi resumes wrong episode.

### To Reproduce

1. Play Blu-ray and skip to example 4 minutes
2. Stop playback and resume
3.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/8514727/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu
 - Kodi version: Kodi 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by howie-f** [comment]
@enen92 can this be related to https://github.com/xbmc/xbmc/pull/21250 ?

**Comment by enen92** [comment]
Maybe. @Dis90 can you check what the behaviour is with that PR reverted?

**Comment by Dis90** [comment]
I found old version (kodi_6%3a20.0+git20220401.0300-71fb3d3a63-0~focal_all.deb) from /var/cache/apt/archives

With that playback doesn't start at all when resuming.
[kodi_old.log](https://github.com/xbmc/xbmc/files/8521645/kodi_old.log)

This is more like feature request but is it possible to change Kodi to show actual name of Blu-ray disc? Now it just shows DVD.

**Comment by enen92** [comment]
Yeah that's what I suspected, resuming was broken for physical disks in the previous versions. 
Now it resumes but it assumes the largest track available (which usually means...the movie track). But ofc that doesn't work on a tvshow bluray (which I assume you're playing). We likely have to keep the bluray state just like we do for dvds but it's a bit more challenging in libbluray.
I don't have any tvshow bluray (or iso) to test this though

**Comment by Dis90** [comment]
> Now it resumes but it assumes the largest track available (which usually means...the movie track).

Does this also mean that resuming always starts largest track and if playback is originally started from Blu-ray menu that functionality is missing after resume i.e. it is not possible go to Blu-ray menu after resume?

> But ofc that doesn't work on a tvshow bluray (which I assume you're playing).

Yep. I was playing tvshow.

**Comment by enen92** [comment]
Yeah that's another fault I noticed for physical discs and affects either dvds or blurays. Unlike Isos where you get a popup asking if you want to resume or play from the beginning, when playing physical discs it just resumes if you have a bookmark. If you want to go back to the menu you actually have to skip to the very beginning or near the end so that the simplified menu shows again (and you can then go to the menu).
This is a particular pain with blurays because the way libbluray is initialized differs if you resume a track of if you go the main menu. If you resume you loose the ability to jump to the menu.
Maybe Kodi should behave for physical discs just like it behaves for iso. If there's a bookmark and "play dvd automatically is not set" it should open a context menu with options for resuming or playing from the beginning.
Will investigate if there's a clean way to do that.

**Comment by enen92** [comment]
As for the name of the Blu-ray...it's also on my radar but unfortunately libbluray fails to get the name of all the (little ammount of) physical blurays I have so I am unsure if that's supposed to actually work. I'll check if I can find some bargain blurays somewhere and get a reimbursement for them.

**Comment by Dis90** [comment]
In my opinion it should at least display something else than DVD when disc in drive is something else than DVD. Maybe just "Disc" if it is not possible to detect what type of disc is in drive.

**Comment by enen92** [comment]
> In my opinion it should at least display something else than DVD when disc in drive is something else than DVD. Maybe just "Disc" if it is not possible to detect what type of disc is in drive.

That's what I intend to do because even if the name can't be obtained from libbluray it can still flag it as a bluray. Unfortunately it requires a bit of work and uniformization of the disc probing logic. At the moment there are two different codepaths for *nix and windows
