### ISSUE TITLE
[Information / Refresh] Re-scrape

### ISSUE THREAD

**Issue by TimerWolf** [xbmc/xbmc#21290]
## Bug report

Re-scrape "movie / tv-show"

### Describe the bug

I notice when  you "refresh" the scrape information it delete the "old information" but the fact is that the information actually says "update" and nothing about "delete" or "wipe" old information...

This bug was found when i was re-scrape a movie that was deleted from the computer, and then the "meta information" was deleted that already was added, but as it could not be found this time it was deleted instead of ignored and untouched (why delete information that's already there)?.

## Expected Behavior

In my eyes it should update the information that can be updated and  keep the old information that can't get updated or not found upon "refresh"

Both scraped information, and local information like "meta information"

## Actual Behavior

I would say that it delete everting that exists if new "data" is found upon "refresh" and replace everything with it.

## Possible Fix

Maybe have an option that let you decide if you will keep the "old" information if it can't find any new and only "replace" "data" if there is new "data" to replace with on "db field" level.

### To Reproduce

I have not try this with information that comes from "imdb/tmdb" but i would say that it works exactly the same as i feel sometimes when i re-scrape stuff that is old that some information that was there "got lost" this could be to different scrapers

1. Find a movie and scrape.
2. Delete the movie from the source.
3. Refresh the already scraped movie from "movie library" where it still exists.

The "mete information" should now have been deleted.

### Debuglog

Not needed

### Screenshots 
Not needed

## Additional context or screenshots (if appropriate)
I don't think that what version or system that is used matter that mutch in this case as i would believe it have been this way for a very long time and still are...

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please use the forum for support questions. https://forum.kodi.tv/

(Hint: you need to clean the library after deleting a source file).

**Comment by TimerWolf** [comment]
This was not a support question, it was a question why it works the way it does and If that is correct...

If this is the correct way it would be a feature request, very strange that you think it is a support question....
