### ISSUE TITLE
Vertical subtitle position incorrectly written to / read from guisettings.xml

### ISSUE THREAD

**Issue by MauriceW67** [xbmc/xbmc#21298]
### Describe the bug
Here is a clear and concise description of what the problem is:

Since the 20220421 nightly (or maybe a bit sooner), the vertical subtitle position is incorrectly being written to / read from guisettings.xml.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Before the bug, I had the subtitle position for all my refresh rates set to 1008. When going back to the Video Calibration screen after configuring, this value was correctly shown again. And during playback, the subtitles were in the desired position.

## Actual Behavior

While playing some media, I noticed my subtitles were suddenly being displayed a lot higher vertically.
When I checked the Video Calibration screen, the value showed there as "933" even though it was previously set at 1008.
Even more strangely, when I set the value back to 1008 and then looked in guisettings.xml, the value stored there was 1083.
Also, when clearing out all resolutions from guisettings.xml and having Kodi write them fresh, the subtitle positions now defaults to the same value as the vertical resolution (i.e. 480 for all 720x480 resolutions, 720 for all 1280x720 resolutions and 1080 for all 1920x1080 resolutions; exception: 1080 is also set for all 3840x2160 resolutions).

### To Reproduce

1. Go to System -> Video -> Video Calibration
2. Configure your desired subtitle position (I used 1008)
3. Exit the calibration screen
4. Exit Kodi
5. Check guisettings.xml. Value there shows as 1083
6. Restart Kodi and go to the calibration screen again. The subtitle position now shows 1005.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/rinapiluxo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 11 on Nvidia Shield Experience 9.0.2
 - Kodi version: kodi-20220421-3f3a3c94-master-22457-arm64-v8a

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MauriceW67** [comment]
Looking through the PRs I guess it has something to do with this one:

#21026

**Comment by CastagnaIT** [comment]
you have to consider the vertical margins that shift the text position,
then the position value shown in calibration GUI window, include the vertical margins,
this to make understand that the text is displayed in that pixel line

the default subtitle vertical margin is 75 pixel that can be overriden by adv settings, then:

1008 (base) + 75 default vertical margin = 1083 the real text displayed position

i will have to check better the behaviour in value saved
it is possible that I did not evaluate the saved value correctly

**Comment by MauriceW67** [comment]
@CastagnaIT

Thanks for the explanation. I noticed that after closing Kodi and then going back to the calibration screen, the value for the subtitle position is shown as 1005 even though I saved it with 1008 (which shows as 1083 in guisettings.xml).

On the other hand, the subtitle position seems to be in the correct place once I saved it as 1008.

One other question: in your PR there is a screenshot showing an "after" picture where the first subtitle line is exactly inside the video and the second line is exactly in the black bar, which is exactly how I like it. Is this a new setting that can be configured so we don't have to mess with the vertical position manually anymore?

**Comment by CastagnaIT** [comment]
> the value for the subtitle position is shown as 1005 even though I saved it with 1008

yes this look weird and i would like to save the base value without the vertical margin, i will check this in the next days

> Is this a new setting that can be configured so we don't have to mess with the vertical position manually anymore?

i have only add more vertical margin, and yes for now can be customized from:
https://kodi.wiki/view/Advancedsettings.xml
search for `subtitleverticalmargin`

before the final version of Kodi 20 i would like to add it as a standard setting in the Kodi GUI settings and remove it from Advancedsettings.xml

**Comment by MauriceW67** [comment]
@CastagnaIT Thanks for pointing me to this new setting.

For me the sweet spot for this value is 72.

This is with the subtitle position set to "Bottom of video", the Roboto Condensed font and a subtitle size of 48.

This gives me the first line of the subtitle just inside the video and the second line just in the black border.

**Comment by CastagnaIT** [comment]
PR #21313 is on the road when will be merged
you will able to change vertical margin from GUI settings
the problem with load/save position value has been fixed
and Calibration setting window will show also the value with margins to make better understand the value difference
