### ISSUE TITLE
Kodi 19.4.0 crashing on MacOS when pressing command q

### ISSUE THREAD

**Issue by Marty56** [xbmc/xbmc#21307]
### Describe the bug
Kodi 19.4.0 is crashing on MacOS when pressing command q and is thereby not compatible with the standard way to end an application in MacOS

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ X] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Monterey, Catalina, Big Sur
 - Kodi version: 19.4.0

**Comment by ksooo** [comment]
Without a stack trace of the crash, nothing can be done to help. Please provide more information.

**Comment by Marty56** [comment]
I understand you are obviously not interested in doing anything.

Why do you close the issue?
To improve the bug tracker statistics?

Bug can be reproduced on any Mac.
Ignoring bugs will not improve the product.

**Comment by fuzzard** [comment]
Ksooo requested further info.

You say it crashes. 19.4 Release doesnt crash for me when closing with CMD+Q, so its not some "blanket" all mac failure.
Without providing more information, i dont know what you expect to be done.

**Comment by ksooo** [comment]
> Bug can be reproduced on any Mac.

 That's unfortunately not true. I've got two of them, one Intel one M1, using both for Kodi development, but I cannot reproduce the crash. Without further information (macOS crash logs, Kodi logs) nobody will be able to help.

**Comment by Marty56** [comment]
I will provide crash report asap. Right now I am traveling. 

Please note that the crash only occurres when you have been playing back a movie before. 
In my case these movies are all recorded tv shows.

**Comment by Marty56** [comment]
I am back home and could NOT reproduce this bug on my three Macs.
So I guess the version 19.4 indeed resolved the issue.
Thanks to all the developers for that.
