### ISSUE TITLE
artist.nfo filde encoding in the Artist Information Folder being not UTF-8

### ISSUE THREAD

**Issue by Mensae** [xbmc/xbmc#21325]
### Describe the bug
Here is a clear and concise description of what the problem is:

The artist.nfo files in the Artist Information Folder are OEM-US, with Unix LF, encoded. When I, manually, alter the, for example, biography, content the non-ASCII characters are mapped to ASCII.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The encoding should be UTF-8.

## Actual Behavior

The file encoding is OEM-US.

## Possible Fix

The artist.nfo file should be UTF-8 encoded.

### To Reproduce

1. Perform the normal procedure to get the entry for ABBA in the Artist Information Folder.
2. Open the artist.nfo file in a text editior that can show/alter the file encoding, like Notepad++.
3. Convert the encoding to UTF-8.
4. Go to [theaudiodb](https://www.theaudiodb.com/artist/111258) and replace the biography content with the one on theaudiodb.
5. Save the file while keeping it open, not locked!
6. Make sure Kodi is running.
7. After a short while Kodi changes the file back to OEM-US and all the non-ASCII characters are mapped to ASCII

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![actual](https://user-images.githubusercontent.com/474743/165893263-23de5238-b528-462e-a5d6-162531994ed6.png)
Fig 1. Actual

![expected](https://user-images.githubusercontent.com/474743/165893282-a8656f48-38cd-4022-a5fa-c6078578cc1d.png)
Fig 2. Expected

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [*] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10, 64 bit
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
To clarify, are these nfo files that have been exported from Kodi using the Export function?
Kodi does create files in UTF-8.

>Make sure Kodi is running.
After a short while Kodi changes the file back to OEM-US and all the non-ASCII characters are mapped to ASCII

No, that is not Kodi doing that. Kodi never writes back to nfo files during normal operations.
The only time Kodi writes nfo files is when you have selected to use the Export function in settings. 

Do you have the Metadata Editor add-on installed?

**Comment by Mensae** [comment]
Hi @KarellenX

To answer, your question, yes, I got the files using the export function.

However, today I used the same procedure but instead of Notepad++ I used Visual Studio Code to open the files. There I do not see any problems. Could be something to do with Notepad++ then. Maybe because the .nfo file extention is also used in Windows as a file to hold system information. I guess NP++ interprets this as this should be OEM-US? Anyways, not a problem with Kodi then.

Thanks for your time and quick response! Closing the issue.

**Comment by KarellenX** [comment]
Thanks @Mensae :)

**Comment by scott967** [comment]
@Mensae I think there is an issue on notepad++ that there is a default setting in a config file that forces nfo extension to default to OEM-US.  This caused no end of hassle when I thought I was saving utf-8 and when I reopened the file it was corrupted.
