### ISSUE TITLE
Thumbs for episodes not loaded if source is accessed via http(s)

### ISSUE THREAD

**Issue by RolandFelnhofer** [xbmc/xbmc#21348]
### Describe the bug

In case a media source is accessed via http(s), episode thumbs located on that server do not get loaded.
Nonetheless If this is an expected behavior I recommend to implement the fix pointed out under: "Possible Fix"

## Expected Behavior

Episode thumbs are locally available get's loaded, regardless of the connection protocol (direct attracted via USB or SATA, HTTP(S), SMB, FTP, NFS, ...)  

## Actual Behavior

In case the I access my media source located on a Linux server via SMB episode thumbs get loaded. If I access the same server/media source via http(s) thumbs do not get loaded.

## Possible Fix

I found the following entry for 'advancedsettings.xml':

```
        <ftp>
                <remotethumbs>true</remotethumbs> <!-- enable extraction of flag and thumb for ftp -->
        </ftp>
```
It seems to me that also accessing a media source via FTP would prevent (episode) thumbs to be loaded but this can be overwritten with the above settings.
If not loading thumbs via http(s) is prevented per default for good reasons, I would recommend to give users at least the possibility to overwrite this via a similar section in 'advancedsettings.xml'. Maybe it's possible a good idea to enable this overwrite activity on server per server bases.
e.g. 
```
        <http>
                <remotethumbs>true</remotethumbs>
                <enabledserver>name.domain1.com, name.domain2.com</enabledserver>
        </http>

```

### To Reproduce

All to reproduce is explained above.
Just access media source via http(s)

### Debuglog

n/a

### Screenshots 

n/a

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - LibreELEC (official): 10.0.1
 - Kodi version: v19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Found it... https://github.com/xbmc/xbmc/pull/18254
It was @the-black-eagle but for music, not video library.

I wonder if it is the same fix?

**Comment by Uukrull** [comment]
Maybe related: I also have the same problems with dav video sources. The culprit seems to be https://github.com/xbmc/xbmc/pull/20103 and reverting it fixes the problem.

Before reverting, I tried to add this code:

```
  if (url.IsProtocol("dav") || url.IsProtocol("davs"))
    return true;
```

but it isn't enough.

**Comment by KarellenX** [comment]
Maybe @arnova might be able to help

**Comment by arnova** [comment]
I think this never worked and accidentally worked with #20103. Could you compile a older version without #20103 to confirm? I currently don't have much time to have closer look or test it myself.

**Comment by Uukrull** [comment]
It worked without #20103 because I've been using it with dav sources for years. Official Leia is fine and also Matrix 19.3 but not 19.4

I'll try to compile a Windows version and debug it with VS to see where it fails with https://github.com/xbmc/xbmc/pull/20103

**Comment by Uukrull** [comment]
After debugging this is what happens:

SkipLocalArt() always returns true because IsInternetStream is true. As a workaround, replacing

https://github.com/xbmc/xbmc/blob/342ee328cef1dc8f59c9fee92ac945f6afc6497f/xbmc/FileItem.cpp#L1078-L1081

with something like

```
  if (HasProperty("IsHTTPDirectory") || HasProperty("IsDAVDirectory"))
    return bStrictCheck;
```
after adding the IsDAVDirectory property at DAVDirectory.cpp like is done with HTTPDirectory.cpp 

Unlike @[RolandFelnhofer](https://github.com/RolandFelnhofer) I don't have any problem with thumbs loaded from http sources at least with current master.

**Comment by Uukrull** [comment]
After more testings, this time with videos that only has local thumbs added to the library, the IsHTTPDirectory condition isn't enough, instead:

`  if (HasProperty("IsHTTPDirectory") || URIUtils::IsDAV(m_strPath))`

is needed so that would explain why also http sources won't load the local thumbs.

**Comment by arnova** [comment]
Normally IsInternstream returns false for dav or http-directory sources (unless bStrictCheck = true). Only issue I can spot is when checking stacked files, since I forgot to pass bstrictcheck. So I'd investigate why isinternetstream is returning true for your sources since that's where the actual culprit seems to be.

**Comment by arnova** [comment]
Btw. debug log is missing. Please attach one...

**Comment by Uukrull** [comment]
Latest Windows nightly with a video located at dav://ip/Temp/Test that has a thumbnail:

[kodi.log](https://github.com/xbmc/xbmc/files/8790781/kodi.log)

![image](https://user-images.githubusercontent.com/5891591/170817678-ef66a9f1-5f1b-494b-ad6c-34ac61163403.png)

![image](https://user-images.githubusercontent.com/5891591/170817695-7bd99eee-368c-488b-ad0c-a10252a97419.png)

**Comment by arnova** [comment]
Please give https://github.com/xbmc/xbmc/pull/21494 a try

**Comment by Uukrull** [comment]
Compiled and tested on Android and so far so good :) Many thanks!

**Comment by RolandFelnhofer** [comment]
Special thx to @arnova and @Uukrull! 
I don't have the necessary development environment to test the patch but I'm looking forward to test it, as soon as a binary version which includes this patch, is available.

**Comment by wsnipex** [comment]
test builds:
arm: https://jenkins.kodi.tv/job/Android-ARM/25657/artifact/kodi-20220601-e14f5374-PR21494-25657-armeabi-v7a.apk
arm64: https://jenkins.kodi.tv/job/Android-ARM64/23086/artifact/kodi-20220601-e14f5374-PR21494-23086-arm64-v8a.apk

**Comment by RolandFelnhofer** [comment]
Yes, I actually realized it on v19.3. After updating to version 19.4 it showed the same behavior.
I have 2 installations which I maintain, accessing the source via https. One is a LibreELEC installation (v10.0.2 based on Kodi v19.4) on a Raspberry Pi4 and one installation on a Windows 10 Client. Both behave identical. Local thumbs for TV shows episodes get ignored. The third installation (LibreELEC v10.0.2 on RPi4) accesses the same data source but via SMB. Here everything gets displayed correctly, including local thumbs for TV show episodes.

As far as I can remember, but can not check it anymore, the thumbs have been displayed under LibreELEC v9.2.6/v9.2.8 which is based on Kodi 18.9 correctly.

**Comment by RolandFelnhofer** [comment]
I could test any Windows 10 binary on an second Windows 10 Client which I wouldn't use "productive".

**Comment by arnova** [comment]
> Yes, I actually realized it on v19.3. After updating to version 19.4 it showed the same behavior. I have 2 installations which I maintain, accessing the source via https. One is a LibreELEC installation (v10.0.2 based on Kodi v19.4) on a Raspberry Pi4 and one installation on a Windows 10 Client. Both behave identical. Local thumbs for TV shows episodes get ignored. The third installation (LibreELEC v10.0.2 on RPi4) accesses the same data source but via SMB. Here everything gets displayed correctly, including local thumbs for TV show episodes.
> 
> As far as I can remember, but can not check it anymore, the thumbs have been displayed under LibreELEC v9.2.6/v9.2.8 which is based on Kodi 18.9 correctly.

Strange: the code that introduced this issue was never backported to Matrix/v19 so if the issue really exists there as well, the reason is different...

**Comment by Uukrull** [comment]
I compiled the current Matrix branch for Windows and local thumbnails from both dav and http sources are loaded just fine.
