### ISSUE TITLE
[Bug] [Android] Default Controller Add-On is not installing on build 19.4 

### ISSUE THREAD

**Issue by RFL0WGitPR** [xbmc/xbmc#21347]
**Bug / Issue**

Default Controller Add-On is not updating or Installing when when updating from official Kodi Add-On repository.

_Expected the add on to install normally when selected to install or update_

_It downloads but doesn't install_

**Steps where I encountered the error**

- Go to settings.
- Select add ons.
- On Add-On Browser go to install from repository.
- Select game add-ons.
- Select controller profiles.
- And pick Default controller 🎮.
- Select update / install.

_It downloads but doesn't seem to update or install._ 

Kodi show update button like the add-on it's outdated 

**Your Environment
Used Operating system:**

- [x]  **Android / Android TV (ver. 9 Pie)**

- [ ]  iOS

- [ ]  tvOS

- [ ]  Linux

- [ ]  OSX

- [ ]  Windows

- [ ]  Windows UWP

**Operating system version/name:**

**Kodi version:** 19.4 Armv7 APK (32bit)

**Notes**

You should consider updating this add on for compatibility with Xbox 360 / Xbox One Elite Controller / Xbox Series X Controllers

On Kodi builds 19.4 or later

**Comment by garbear** [comment]
Can you upload a debug log? That will usually show the error.

**Comment by garbear** [comment]
Follow along with the current discussion: https://github.com/xbmc/xbmc/issues/25545

I've prepared a backport PR to fix this issue: https://github.com/xbmc/xbmc/pull/25389
