### ISSUE TITLE
Multi Weather addon is broken due to the Yahoo cookie issue

### ISSUE THREAD

**Issue by Hawkedon** [xbmc/xbmc#21368]
### Describe the bug

Multi Weather addon is broken due to the Yahoo cookie issue [https://forum.kodi.tv/showthread.php?tid=352028&page=11](url)

Hi @ronie,

To fix the current Multi Weather cookie issue, you just need to add the following field to the request header for yahoo.com  and use 'A1' cookie afterwards:

`'Accept': 'text/html,application/xhtml+xml,application/xml'`

I posted the solution [https://github.com/xbmc/repo-scripts/issues/2270](url), but seems no one noticed that.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
You would be best posting to the add-on forum thread. This isn't something that is done via this repo

**Comment by Hawkedon** [comment]
@fuzzard, may be someone can help to post that to the forum, I don't have a forum account.
