### ISSUE TITLE
Cannot compile using gcc 12.1

### ISSUE THREAD

**Issue by graysky2** [xbmc/xbmc#21376]
### Describe the bug
Here is a clear and concise description of what the problem is:

I am unable to compile latest commit from master using GCC 12.1

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

GCC 12.1 should compile without errors

## Actual Behavior

GCC 12.1 throws errors

### To Reproduce

1. Build [kodi-git](https://aur.archlinux.org/packages/kodi-git) on Arch Linux

### Debuglog

The debuglog can be found here:

[kodi-git-r60264.c4fb873b50e-1-x86_64-build.txt](https://github.com/xbmc/xbmc/files/8647657/kodi-git-r60264.c4fb873b50e-1-x86_64-build.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: latest commit from master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by graysky2** [comment]
I did see this in the output:
```
cc1plus: all warnings being treated as errors
```

If I append `-Wno-error` to the *FLAGS, I can build find with GCC 12.1.  Perhaps this behavior is a function of the Arch default *FLAGS or with the way our toolchain is configured rather than something in the Kodi code base?

The distro default *FLAGS:
```
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
```

**Comment by asavah** [comment]
@graysky2 AFAIK the error comes from flatbuffers build but you don't need to build flatbuffers as part of Kodi build at all.
Flatbuffers is a build-time dependency and `flatc` is used to compile stuff but it's not needed at runtime.
Try adding stock arch `flatbuffers` package as `makedepends` and disable building it as part of the package with `-DENABLE_INTERNAL_FLATBUFFERS=OFF`.

This info might be inaccurate as I'm writing this from memory, due to war in my country I currently don't have access to my build machine.

**Comment by graysky2** [comment]
@asavah - Thanks for the post.  It was independently posted by loqs in [this](https://bugs.archlinux.org/task/74753) Arch specific bug report.

**Comment by wsnipex** [comment]
works fine for me  on ubuntu, even with internal flatbuffers.

So this must be some Arch specific issue

**Comment by graysky2** [comment]
Thanks for testing, @wsnipex
