### ISSUE TITLE
[Python][xbmcgui] xbmcgui no longer supports ACTION_IDs since PR21264

### ISSUE THREAD

**Issue by scott967** [xbmc/xbmc#21389]
### Describe the bug
Here is a clear and concise description of what the problem is:

I am maintaining addon script.extendedinfo on Matrix+.  This addon uses a python module from Kodi Matrix repo script.module.kutils

kutils provides a module actionhandler.py.  That module has a module global dictionary ACTIONS, the values are xbmcgui attributes such as :

```python
           ACTIONS = {"left": xbmcgui.ACTION_MOVE_LEFT,
           "right": xbmcgui.ACTION_MOVE_RIGHT,
           ... }
```
Since [PR21264](https://github.com/xbmc/xbmc/pull/21264) @notspiff this throws an exception on run
``module 'xbmcgui' has no attribute 'ACTION_MOVE_LEFT'
``
when script.modules.kutils is imported and the package runs its __init__ which invokes
```python
 from kutils.actionhandler import ActionHandler
```

Looking at this PR, it appears the problem is the change to ActionIDs.h in commit 1a95e439128fc7ba85482ab9dba179936e9fa35e

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

script.module.kutils should run "as-is" as it does prior to PR21264

## Actual Behavior

exeption in actionhandler.py

## Possible Fix

revert 1a95e439128fc7ba85482ab9dba179936e9fa35e or analyze why this is causing a problem in xbmcgui or provide guidance to python addon devs.

### To Reproduce

1. You need to install script.extendedinfo, or other script which has dependency on script.module.kutils
2. ver 6.0.1 of this script can be obtained from repo-scripts Matrix branch as [PR2233](https://github.com/xbmc/repo-scripts/pull/2233)
3.Run script in Kodi
4.

### Debuglog

The debuglog can be found here:
Exception with Git:20220413-2aef782c6e
[2aef782c6e](https://paste.kodi.tv/zebonejugo.kodi)
Success with Git:20220413-6b98340faf
[6b98340faf](https://paste.kodi.tv/feyatagado.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 10 x64 21H2 / VS 2017
 - Kodi version: 20A1 built from master before and after PR21264 on VS2017

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Can you try the following build

http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220512-c155f75a-swig_constexpr-x64.exe

I tried your repro instructions but had some other exception happen, so probably just easiest if you can test the above build for me

**Comment by Angelinas1** [comment]
@fuzzard 
good job, No more errors......
This was mine issue too,, now is fixed.
https://github.com/xbmc/xbmc/commit/1a95e439128fc7ba85482ab9dba179936e9fa35e#commitcomment-72580014
tnx

**Comment by scott967** [comment]
Works on my previous failed test cases.  Thanks.  I did try to look at code, have no idea what "swig" does.

**Comment by scott967** [comment]
Thanks.  I had cherry-picked your commit on top of A1 to complete testing of skin for 20A1 and all seems well.
