### ISSUE TITLE
Media Fails to play "&"

### ISSUE THREAD

**Issue by dale76uk** [xbmc/xbmc#21394]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi fails to play media when a file name has the ampersand symbol within the file name. For example, a media container with the name Inspection & Testing.mp4 fails to play, removing the ampersand symbol or simplifying the name to Inspection and Testing.mp4 allows the file to be played

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video fails to play

## Possible Fix

 removing the ampersand symbol or simplifying the name to Inspection and Testing.mp4 allows the file to be played

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [x ] OSX
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
I cannot replicate this.

Provide a debug log thanks.

**Comment by thexai** [comment]
28 days is enough to provide debug log
