### ISSUE TITLE
Display artwork for Next item or any item in playlist

### ISSUE THREAD

**Issue by jjd-uk** [xbmc/xbmc#21399]
## Roadmap or todo item
**Detailed Description**

I was looking at adding the info for the next item in a video playlist to a skin dialog

Design I had been experimenting with

![image](https://user-images.githubusercontent.com/5781142/168469944-ca9e4940-2945-4d93-b01a-d0d41711be48.png)

Currently I can specify the labels:

Title - $INFO[VideoPlayer.offset(1).Title]
Premiered - $INFO[VideoPlayer.offset(1).Premiered]
Genre - $INFO[VideoPlayer.offset(1).Genre]
Plot - $INFO[VideoPlayer.offset(1).Plot]

But there is no way for me to fetch the poster for the next item as there isn't a

Player.offset(x).Art(poster)

or similar.

### Context
At the moment this seems only possible with scripts which is no good if you want a lightweight that doesn't rely on any of the Skin Helper scripts. For example the skin I'm working on is based off Estuary so I don't want to be adding scrips as I would like to keep the possibility to backport features in my personal skin to Estuary for everyone's benefit.

### Possible Implementation
New infolabel required e.g. Player.offset(x).Art(x)

So any artwork types that Player.Art(x) can fetch for currently playing item, can also be fetched for the Next item or any item in playlist as a skinner may wish.

### Additional context, screenshots or links

Info for currently playing item as a comparison

![image](https://user-images.githubusercontent.com/5781142/168470380-b30bd5b5-8b69-44cd-8172-d1695af7011e.png)

So missing the possibility to add a poster here

![image](https://user-images.githubusercontent.com/5781142/168469944-ca9e4940-2945-4d93-b01a-d0d41711be48.png)

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by jjd-uk** [comment]
Not 100% sure but displaying poster may been possible in the past with

VideoPlayer.offset(x).Cover

As wiki description says 

> Cover of currently playing movie. Note: Deprecated, use Player.Art(type) instead.

However it seems this VideoPlayer.Cover now only retunrs a thumb and VideoPlayer.offset(1).Cover doesn't return anything, so not sure behaviour of this was changed with the intorduction of Player.Art(type).

**Comment by enen92** [comment]
`VideoPlayer.offset(x).Cover` is equivalent to `Art(thumb)` which returns the thumbnail of the next item. In the past we used to store the poster there though, but it is wrong.
The linked PR above implements your request. Do you have any idea if we have this kind of limitation also for music?

**Comment by jjd-uk** [comment]
Thanks @enen92  that's great.

Not sure about music will need to check, as I was experimenting with video osd/info dialogs only.

**Comment by DaveTBlake** [comment]
>  Do you have any idea if we have this kind of limitation also for music?

All from memory (not home able to check)...
Where/when/how art gets loaded for items varies between music and video, also it is generally done in the background (so you can have a list and not all the art).  With music it is also complicated by when/if the art for artist and album gets added to that of a song.  With music it makes a difference if the current playlist is on display in the GUI and if the user has changed the currently selected item in the list, and how the playlist was populated (e.g. GUI menu actions, JSON API, keyboard shortcut).

It is a historic mess, with far too many different code routes giving slightly different outcomes, and is not easy to untangle without breakage. I have looked at it for music a few times and not managed to get out the other side!

**Comment by jjd-uk** [comment]
From a quick test using Estuary it seem like `MusicPlayer.offset(1).Cover` works ok for music to get the cover of the next item (or any item), so that's probably all I would need if I looked to do something similar for music.

![image](https://user-images.githubusercontent.com/5781142/168482578-8710e2e9-f8ca-495b-af9a-a41eb8595cc5.png)

It would be good to offer skinners more flexibility to fetch fanart and other art types for music playlist items using some `offset` infolablel, but from from @DaveTBlake is saying that could start getting much more complicated.

**Comment by enen92** [comment]
Yeah for music it might be cumbersome to do the same. It seems it even tries to load the thumb from the info interface (thus in the main thread) when requesting "any" MusicPlayer info:

https://github.com/xbmc/xbmc/blob/3f3a3c9484ac9eef1b8d13400cd5bee987233753/xbmc/guilib/guiinfo/MusicGUIInfo.cpp#L556-L563

**Comment by DaveTBlake** [comment]
>  It seems it even tries to load the thumb from the info interface (thus in the main thread) when requesting "any" MusicPlayer info which is definitely wrong:

Actually it often already has the thumb in many situation, so this is covering those that don't. I also think that the loader runs on own thread, which could mean this was getting default cover. Agh, too much out my memory!

**Comment by walterheisenberg** [comment]
I don't know, if this is working on PVR also, but you should think about adding this in some way for PVR also.
Here is a FR for it: https://forum.kodi.tv/showthread.php?tid=351556&pid=2922659#pid2922659

VideoPlayer.NextIcon or PVR.EPGNextEventIcon
or PVR.EPGNextEventIcon(x) - where 0 is the current, (1) would be the first in the future etc.

To keep the PR clean, I posted here. Just to make sure at least someone thinks about it ;)
Thx in advance
