### ISSUE TITLE
Kodi crashes while viewing pictures due to OOM

### ISSUE THREAD

**Issue by mb555444** [xbmc/xbmc#21412]
Kodi 20 on Android (Fire TV Cube) crashes while viewing pictures due to OOM

### Describe the bug
Here is a clear and concise description of what the problem is:
- use Kodi 20 on Fire TV Cube (2GB RAM)
- browse a folder with JPEG images (e.g. 150 images, 6000x4000, JPEG)
- images are stored on SMB
- when debug logging is on, the memory indicator shows memory gradually reaching 0
- Kodi eventually crashes

A very similar issue documented by someone else at https://forum.kodi.tv/showthread.php?tid=352479&page=2
My folder contains no GIF files, though.

## Expected Behavior

Kodi should not crash while viewing images

## Actual Behavior

Kodi crashes due to running out of memory

### To Reproduce

1. Open folder with images (e.g. 150 images, 6000x4000, JPEG) 
2. Click on the first image
3. Browser further images by clicking "right", eventually the crash happens

### Debuglog

The debuglog can be found here:
[kodi.old.log](https://github.com/xbmc/xbmc/files/8702257/kodi.old.log)
(some folder names and hostname redacted for privacy)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by mb555444** [comment]
Further information:
- Kodi exits because it receives signal 9 from the Linux OOM killer
- memory runs low due to thumbnail generation

The issue seems to be that while in line
https://github.com/xbmc/xbmc/blob/master/xbmc/pictures/PictureThumbLoader.cpp#L31
the maximum number of concurrent jobs is set to 1, the log shows that multiple threads are generating thumbnails in parallel:

2022-05-16 19:25:00.945 T:**29641**   DEBUG <general>: cached image 'special://masterprofile/Thumbnails/5/5ddc2b96.jpg' size 720x480
2022-05-16 19:24:53.855 T:**29642**   DEBUG <general>: cached image 'special://masterprofile/Thumbnails/7/7929d3ff.jpg' size 720x480
2022-05-16 19:24:54.407 T:**29663**   DEBUG <general>: cached image 'special://masterprofile/Thumbnails/9/993a70b5.jpg' size 720x480

I estimate that each threads needs some 100-200MB of RAM to downscale an image of 24 megapixels. This can only be expected to get worse as sensor resolution increases, 60 or 100 megapixels are available already. On low-memory devices it would be important to fix this issue by ensuring that thumbsnail generation does not run with 3 or more threads in parallel.

**Comment by mb555444** [comment]
Can someone review this please?

**Comment by mb555444** [comment]
After doing some further research, I found that the following settings help to reduce the instability:
- Set GUI resolution limit to 1080 in expert settings (this will limit the size of the texture created from each image; otherwise the texture will be created with the maximum resolution supported by the renderer, e.g. 16384x16384, even when the screen resolution is only 1980x1200)
- Disable background thumbnail generation (this will avoid multiple images processed at once when viewing, i.e. pictures being loaded for display and in parallel for thumbnail generation)

Even with these settings, the picture viewer struggles with larger images in the 100MP range. Memory usage as shown in debug modes goes up and down like crazy, and it's a matter of luck if it suffices for whatever jobs the viewer is triggering.

With even larger images (32K width, just for testing), another problem surfaces:
`ERROR <general>: ffmpeg[0x56312d2cc930]: [IMGUTILS] Picture size 30720x17280 is invalid`

Generally, it seems the picture viewer code needs some love and testing with nowadays' image sizes.

**Comment by mb555444** [comment]
I am closing the issue due to inactivity. Not mine but Team Kodi's.

**Comment by mb555444** [comment]
It is under "Settings - Media - Pictures" and actually called "Automatically generate thumbnails". You have to choose Advanced/Expert settings. It also helps to switch to a view that does not show thumbnails ("WideList").
Of course, these are just workarounds. Our devices do have enough memory to display such images, it just isn't used very efficiently by Kodi.

**Comment by kkudielka** [comment]
Thanks, but that one didn't help. After some more testing I believe it's **not** an OOM situation in my case - I persistently have between 600 and 800MB free when watching pictures in "good" folders, or when trying to open "bad" folders.

The crash always happens with the same folders, and always during folder open, while the progress bar is still growing. So maybe a different issue.
