### ISSUE TITLE
Kodi iOS error installing AltStore

### ISSUE THREAD

**Issue by bachig26** [xbmc/xbmc#21419]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi doesn't install in iOS when I tried to install with AltStore.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi expected to run as defined.

## Actual Behavior

I have converted the .deb into .ipa as mentioned in the How-To-Guide and tried to add it via the AltStore.
But the error message shows that "The App is Invalid."

## Possible Fix

Looking forward to have proper .ipa file instead of the .deb to .ipa conversion with the ios working.

### To Reproduce

1. converted the .deb to .ipa via 7zip
2. added the .ipa via altstore
3. error message displays in few seconds.

### Debuglog

The debuglog can be found here:
nil

### Screenshots 
Here are some links or screenshots to help explain the problem:

nil

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [x] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4-Matrix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Last i heard, altstore doesnt sign all dylibs in the ipa for some reason. The fault is apparently on their end.
Issues were opened on their github repo a couple years ago, without any feedback/response from their devs.

Short answer is we have no way to support via altstore.
