### ISSUE TITLE
Kodi 19.4 crashes after hibernation on Fire Cube

### ISSUE THREAD

**Issue by DJDoena** [xbmc/xbmc#21413]
### Describe the bug
Here is a clear and concise description of what the problem is:

This happens reproducible and always:
- Start Kodi
- Start movie
- Stop movie
- Press Home button on Fire Cube
- Select Kodi again -> crash

## Expected Behavior
-Kodi should come back from hibernation where it was left
### Debuglog

https://paste.kodi.tv/ebaweteyap.kodi

### Your Environment
Used Operating system:
 - [ X] Android Fire Cube
 - Operating system version/name:

 - Kodi version:
19.4 but has been happening for all of 19.x and even earlier

**Comment by quietvoid** [comment]
Duplicate of https://github.com/xbmc/xbmc/issues/20620

**Comment by DJDoena** [comment]
> Duplicate of #20620

It does not lock up actually as described in #20620, it will just close again and upon next try to open Kodi will start from scratch (including splash screen)

**Comment by quietvoid** [comment]
It's the same issue. The launcher isn't keeping Kodi in memory.

**Comment by thexai** [comment]
Closed in favor of https://github.com/xbmc/xbmc/issues/20620
