### ISSUE TITLE
Kodi Add-On Repository not working

### ISSUE THREAD

**Issue by Fungaming44** [xbmc/xbmc#21426]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have an Eminent Box with LibreELEC on it and Kodi, it has been working perfectly for many years but since recently I can no longer update anything through the Kodi Add-On Repository and also cant install anything from it.

I already did a full hard reset but even then it didnt work

I hope someone can help me fix this as im kinda desperate right now, i have no idea what else to do

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/axificamor

**Comment by wsnipex** [comment]
your SSL CA certs are very outdated, that's why the connection fails:

**Comment by Fungaming44** [comment]
How do i update that or replace them ? I have no knowledge on how that works

**Comment by wsnipex** [comment]
you could ask on the LibreElec forums

**Comment by Fungaming44** [comment]
For those with the same issue, this solved it for me https://forum.libreelec.tv/thread/24673-cannot-install-update-addons/#post161675
