### ISSUE TITLE
Feature Request: Video playlist should behave like play history, no auto delete

### ISSUE THREAD

**Issue by Isayso** [xbmc/xbmc#21432]
## Bug report
Video playlist gets deleted automatically 
### Describe the bug

The playlist gets deleted automatically if you navigate and play something from Movie, TV Show, Addon and so on.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Option to change the behavior of the video playlist like a play history, that one can go back and replay a video. Now you must reload the link or navigate to the location of the video. 

## Actual Behavior

Complete list gets deleted when playing a video from other Addon/Source

## Possible Fix

Do not delete list, or set a maximum number for history items.

### To Reproduce

1.  Play 2 videos
2.  go to video/playlist -> the two videos are present 
3.  play a video from a different source like Addon
4. go back to video playlist -> List empty

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:  Libreelec 10.0.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Please use the forum for feature requests.
