### ISSUE TITLE
External subtitle time-line run into mess when play BDMV movie

### ISSUE THREAD

**Issue by ZhangShaobo9527** [xbmc/xbmc#21440]
### Describe the bug

prerequistes:
   1. a movie in BDMV format
   2. an external standalone subtitle file

like below's folder structure:

```
Movies
├─...
├─...
├─Black.Widow.2021.COMPLETE.UHD.BLURAY-MAXAGAZ // the movie
│   ├─BDMV
│   │  ├─BACKUP
│   │  │  ├─BDJO
│   │  │  ├─CLIPINF
│   │  │  ├─JAR
│   │  │  │  └─00001
│   │  │  └─PLAYLIST
│   │  ├─BDJO
│   │  ├─CLIPINF
│   │  ├─JAR
│   │  │  └─00001
│   │  ├─META
│   │  │  └─DL
│   │  ├─PLAYLIST
│   │  └─STREAM
│   └─CERTIFICATE
│      └─BACKUP
└─Black_Widow_subtitle.ass // the subtitle file
```

phenomenon:

   1. If i play the movie from `Select playback item` menu, chose item like `Play main title: 4`, then load the external `Black_Widow_subtitle.ass` file during playing, then the subtitle timeline will be completely mess	
      ![image](https://user-images.githubusercontent.com/45927362/169855903-9e66f191-d97e-483c-acf2-68beddf30cf9.png)

   2. If I navigate to folder `xxx\BDMV\STREAM\`, chose the `*.m2ts` file which has the largest length, play that `*.m2ts` file as it is a regular video file. then load the external `Black_Widow_subtitle.ass` during playing, then the subtitle timeline will be correct : every line will be position at the right position.

there are lots of complainings on several Chinese communities, and I guess nobody complained it in Western communities is because:

1. BDMV in folder format is pretty rare, large and disk-consume, and illegal in some areas and regions.
2. Western people doesn't need subtitle to watch a Western movie, in some very rare cases, like Englisher speaker & Korean Movie, or French Speaker & English Movie. there always a English or French or German subtitle attached in BDMV movie. Western people no need to load an external subtitle file

so, as I observed, there seems only Asians complains about this issue, and It should not a single platform or single version issue, I've seen these complains from arm TV to PC, from version 18 to version 20.

## Expected Behavior

If user load the external subtitle file during playing BDMV movie, please place the lines on their right position. 

### To Reproduce

I know download pirated digital movies from internet is not legal, but in case of devs doesn't speak Asian language and hard to debug this issue, I'll offer a download link here.

below is a magnet link below to download a bluray movie

**edit enen92: removed.**

below is the corresponding subtitle file, and of course you have to unzip it first

[Black_Widow_subtitle.zip](https://github.com/xbmc/xbmc/files/8756031/Black_Widow_subtitle.zip)

### Your Environment

I found this issue on my Windows 11 PC with AMD cpu and AMD graphic card.

but as I said before, this issue seems not a single platform issue, you might re-pro this issue on every platform and every versions.

**Comment by enen92** [comment]
Kodi version and log file?

**Comment by ZhangShaobo9527** [comment]
> 
## environment spec

Kodi version : 

```
Build: 20-ALPHA1 (19.90.701)
Git: 20220516-59d6be5749
Compiled: 2022-05-16
```

Operation System: Windows 11 21H2 (kernel: Windows NT 10.0.22000.675)
CPU: AMD Ryzen 9 3900X 12-Core Processor
GPU: AMD Radeon RX 6900 XT
D3D Version: 12.1

## about log

I don't think `log` is necessary for confirm & debugging this issue, but if you insist, I can re-pro the issue then paste debugging logs here after work.

I think I've already explain it out clearly and this issue is very easy to re-pro, just get a BDMV and an external subtitle file.

**Comment by youtehub** [comment]
There is another problem that Kodi has always existed. At present, it is mainly running on the Window system. After a short test, it is found that there are also on the Kodi V18.
That is to not be able to adapt to different resolution. When I install it with a resolution of 2560x1440, the EMBY plug -in is used normally. When I switched to 3840 × 2160 resolution to watch 4K movies, KODI collapsed directly, and it was the same effect when testing at 1920x1080 resolution. It is flickering and cannot be turned on. However, when the resolution switch to 2560x1440, Kodi can be used normally.

**Comment by enen92** [comment]
@ZhangShaobo9527 please test https://github.com/xbmc/xbmc/pull/21458

**Comment by ZhangShaobo9527** [comment]
> @ZhangShaobo9527 please test #21458

Thanks for your quick action, really appreciate it! salute! (〃･ิ‿･ิ)ゞ

I don't have a local build environment and haven't tried to set it up yet.

since you've been tested it, and the code change seems won't crash other parts of Kodi, I think it's safe to complete the PR, merge the change into `master` and `Matrix`.
