### ISSUE TITLE
Feature Request: airplay mirroring (f.e. through integration of uxplay)

### ISSUE THREAD

**Issue by slynobody** [xbmc/xbmc#21442]
### Describe the bug
airplay features are only integrated in some minor forms (not what you expect of a media-system nowadays)

## Expected Behavior
include easy to use airplay mirroring, f.e. by integrating code form uxplay (https://github.com/antimof/UxPlay)

**Comment by fuzzard** [comment]
Feature requests can be made on the forums

https://forum.kodi.tv/forumdisplay.php?fid=9

**Comment by slynobody** [comment]
thanks for your information, did that before a few month back. no answers there.
