### ISSUE TITLE
feature request：support the m3u8 file with ipv6 address

### ISSUE THREAD

**Issue by lius2000** [xbmc/xbmc#21444]
### Describe the bug
Here is a clear and concise description of what the problem is:

as is known,the ipv6 address is used more and moare widely, the m3u8 file with ipv6 address can't be played by kodi, can you give me some suggestions or upgrade the add-on in the near future?
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

add a switch in setting of network to turn on or off the ipv6 address, or support ipv6 automatically

### To Reproduce

1. now so many apps such as  iinar、GSE IPTV suuport the ipv6 m3u8 file
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X ] Android
 - [ X] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ X] OSX
 - [ X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Feature requests can be made on the forums

https://forum.kodi.tv/forumdisplay.php?fid=9

**Comment by x3669** [comment]
Kodi already supports pure IP6 broadcast source addresses such as,
http://[2409:8087:3869:8021:1001::e5]:6610/PLTV/88888910/224/3221225786/index.m3u8
There seems to be no support for something like this:
http://[2409:8087:4400:20:1:a0f:12:33]/iptv.cdn.ha.chinamobile.com/PLTV/88888888/224/3221226526/index.m3u8
Don't know what can support?
