### ISSUE TITLE
No player process INFO for shared drive ISO files.

### ISSUE THREAD

**Issue by terrorindeed** [xbmc/xbmc#21448]
### Describe the bug
When playing back iso files from network mapped shared drives or rclone mounted drives, player process info does not display any information. 

## Expected Behavior
When pressing o, player process INFO should display expected information.

## Actual Behavior
Pointer flashes onscreen once.

### To Reproduce

1. Open Kodi, navigate to settings--media--add videos--add network mapped drive, or locally mounted rclone drive.
2. Begin playback
3. Press 'o' or 'alt-shift-o'

### Debuglog

The debuglog can be found here:
Network mapped drive log
https://paste.kodi.tv/ujacujevib.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 Pro 21H2 22000.675
 - Kodi version: Kodi 19.4 Git:20220302-e12e66e019

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by terrorindeed** [comment]
Workaround. 
After opening the file, exiting the playback. Kodi scrapes the metadata, showing HDR10, aspect ratio, run time etc. Starting playback a second time, pressing 'o' displaying the expected player process INFO.

**Comment by enen92** [comment]
This doesn't occur with local iso files right? I mean files that are not accessed from a network share.
I can't reproduce this on the local hard drive.

**Comment by terrorindeed** [comment]
![screenshot00000](https://user-images.githubusercontent.com/3170862/170301896-d8326692-c7a2-4842-8b66-3cb7c004dc4c.png)
![screenshot00001](https://user-images.githubusercontent.com/3170862/170302036-8802d97a-4f25-4b72-8237-e7adbc19339f.png)

**Comment by terrorindeed** [comment]
From a shared drive. Notice how Allegiant only shows 03/09/2016 2:00:00, no player process info is displayed for this iso file. 

Alita Battle Angel playback was started,then stopped. Kodi then changes and shows 2:01:57 H.265 4K DOLBY-HD 7.1, when starting playback again player process info is displayed correctly.

**Comment by enen92** [comment]
I see, I think this is by design:
https://github.com/xbmc/xbmc/blob/1aa506e3a4c4afd4ee7e0dfb455a8243610a052a/xbmc/application/ApplicationPlayerCallback.cpp#L59-L74

iso files are not standard video files and can include multiple playlists/tracks so probing them when scrapping is complex. What kodi does is to save the stream details whenever you actually play them. Maybe there is a way to provide this information upon scrapping using NFO files or something (I'm not familiar with those).
