### ISSUE TITLE
Video stuttering in Android (Shield) when OSD is visible

### ISSUE THREAD

**Issue by thexai** [xbmc/xbmc#21466]
### Describe the bug
Here is a clear and concise description of what the problem is:

Video stuttering in Android (Shield) when OSD is visible. 

The OSD is the basic one you get when you press menu: playback progress. It has nothing to do with high CPU usage from displaying more complex menus or scrolling text. See screenshot for reference.

This issue is independent of commit https://github.com/xbmc/xbmc/commit/086ea08740bdf8427c7ee590425f462ab701c92a  (tested with commit reverted and still happens).

This issue is caused by https://github.com/xbmc/xbmc/commit/196c11defca96e0f7819a5f1d7c7a05e2dcda0fe . Tested with this commit reverted and issue is gone. 

Tested with master branch updated to 22/05/26 (only difference of these commits reverted).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No video stuttering when OSD is visible

## Actual Behavior
Video stuttering when OSD is visible

## Possible Fix
Revert commit https://github.com/xbmc/xbmc/commit/196c11defca96e0f7819a5f1d7c7a05e2dcda0fe

### To Reproduce

Tested with movie "Rogue One: A Star Wars Story" in 4K fast motion scenes (see screenshot for reference and time stamps) and effect is very noticeable and evident.

Setup are:
Shield Pro 2019 - FW 9.0.2 (Android 11) / Denon AVR-X1600H - match refresh rate enabled (at Start/Stop), audio passthrough.

### Screenshots 
Here are some links or screenshots to help explain the problem:

![screenshot00000](https://user-images.githubusercontent.com/58434170/170561555-1d74c4b4-da20-43f7-b8c1-d5a97e768272.png)

NOTE: screenshot is only for reference. Not taken from Shield.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: v20 master branch

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Can you check the CPU-Load? One side effect of the "old code" was that the wait for vsync was done always, no matter if rendered or not, e.g. this part of the code was use to throttle the egl implementation.

Now with subtitles being rendered via the EGL layer, while video is surface rendering (bypass) - I think you hit the !rendered path - and here that loop is not throttled at all.

**Comment by ksooo** [comment]
@fritsch you mean, something like done in Windows implementation is missing for Android? => https://github.com/xbmc/xbmc/blob/6915ae7631a85cc2d78e60248ce19adb5f002ea3/xbmc/windowing/win10/WinSystemWin10DX.cpp#L51

**Comment by thexai** [comment]
> is missing for Android?

From what I understand, it is missing "wait for the vertical sync" (which was already fine but you removed it).

HW video rendering in Android does not need it (because is a "bypass") but when is displayed OSD is need vertical sync because OSD is at 60 Hz and video at 24 Hz. 

So we want/need to use wait vertical sync to render the OSD at 24 Hz same as video.

If this is broken it's probably because `WaitVSync(1000);` It waits a time that is not correct because it depends on some static variable that does not have the value that it should because it has not been updated when Kodi is reopened (warn start).

This is all just guesswork because I haven't looked the code at all.

**Comment by thexai** [comment]
"wait to vertical sync" does nothing when it has the correct value and "bypass" is used also it is used to synchronize the OSD with the video.

But if "wait to vertical sync" has bad value causes stuttering in video. If it's removed fixes stuttering in video but introduces a bug in OSD.

**Comment by thexai** [comment]
Honestly not

**Comment by fritsch** [comment]
I am not entirely sold on this. the Wait is just a CEvent, one guy waits and the doFrame() methode Sets it at the end. So it is not directly tied to any vsync, but uses the doFrame method indirectly.
