### ISSUE TITLE
Python Cryptodome on android is broken on recents v20 nightlies

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#21476]
### Describe the bug
Here is a clear and concise description of what the problem is:

Python Cryptodome on android is broken on recents v20 nightlies
An user reported to https://github.com/CastagnaIT/plugin.video.netflix/issues/1349

and affirm that last working kodi v20 is: kodi-20220521-43b96fc2-master-22881-arm64-v8a.apk

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. Install Netfl@x addon
2. login
3. Cryptodome library errors 

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/eruhalujup.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 8
 - Kodi version: last Kodi 20 nightly kodi-20220527-13e07301-master-22997-arm64-v8a.apk

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Before i start chasing this, can we get it confirmed it still doesnt work in the next nightly (0529).
Want to confirm this isnt just another side effect of the android exit() PR

**Comment by Uukrull** [comment]
The problem is the apk for aarch64 doesn't include the Cryptodome *.so

kodi-20220515-4f85184f-master-22806-arm64-v8a.apk:
![image](https://user-images.githubusercontent.com/5891591/170824414-32a90fdc-713d-4cd1-a216-5bc3907f3511.png)

kodi-20220527-13e07301-master-22997-arm64-v8a.apk:
![image](https://user-images.githubusercontent.com/5891591/170824432-35d20aa8-263f-4972-91ed-ef6b33fcafd0.png)

Reverting https://github.com/xbmc/xbmc/pull/21332/commits/9fdca02aa4d0fbe7b417a49ed302aea9e22b3dc6 fixed it for me.

**Comment by Ronny-nerd** [comment]
Since today the login in the Netflix Addon works again with the Kodi 20 ( 64 Bit ) Nexus Build...so my thanks go to CastagnaIT and the Kodi Team. :)

kodi-20220529-89ffc5d8-master-23044-arm64-v8a.apk

mirrors.kodi.tv/nightlies/android/arm64-v8a/master/

**Comment by CastagnaIT** [comment]
is broken again

**Comment by CastagnaIT** [comment]
report to https://github.com/CastagnaIT/plugin.video.netflix/issues/1369
