### ISSUE TITLE
Can't start gbm mode on SBC radxa rock3a

### ISSUE THREAD

**Issue by amazingfate** [xbmc/xbmc#21484]
### Describe the bug

  I have a SBC radxa rock3a running armbian jammy with kernel 5.18, which have gpu mali g52 drived by panfrost driver. Kodi version is 19.4+dfsg1-2 from ubuntu-ports repo.
  Kodi can start with x11 mode from lightdm session. But when I run command `kodi-standalone --windowing=gbm` on tty, I get a black screen and after several seconds my screen have notification `No video input`. At the same time the kodi.bin process is still running and I have to kill it to get my tty screen back. I can run glmark2-es2-drm and kmscude in tty so the drm support should be ok.
  Here is the output of running `kodi-standalone --windowing=gbm` on tty:
  ```
failed to open zone.tab
libva info: VA-API version 1.14.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
^C
  ```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I can get kodi UI on screen when running `kodi-standalone --windowing=gbm` on tty.

## Actual Behavior

I get black screen with the kodi process still running.

### To Reproduce

1. Install armbian jammy image from https://github.com/amazingfate/armbian-rock3a-images/releases/latest
2. Use apt to install kodi.
3. Switch to tty, run command `kodi-standalone --windowing=gbm`

### Debuglog

The debuglog can be found here:
```
failed to open zone.tab
libva info: VA-API version 1.14.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
^C
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Armbian jammy
 - Kodi version: 19.4 Debian package version: 2:19.4+dfsg1-2 Media Center Kodi from Debian

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jernejsk** [comment]
You have to provide actual debug version of log file (kodi.log). Since UI can't be reached, you have to take steps explained under advanced method here: https://kodi.wiki/view/Log_file

**Comment by amazingfate** [comment]
> You have to provide actual debug version of log file (kodi.log). Since UI can't be reached, you have to take steps explained under advanced method here: https://kodi.wiki/view/Log_file

Here is the debug log: https://paste.kodi.tv/efuhurocep.kodi

**Comment by amazingfate** [comment]
@jernejsk It seems that kodi gbm doesn't start with panfrost driver, how can I run kodi gbm with panfrost? I can see ``By properly creating, exporting and importing buffers, we can now run applications on GBM, from demos such as kmscube and glmark2 to compositors such as Weston, but also big applications such as Kodi.`` in [this blog](https://blog.tomeuvizoso.net/2019/01/a-panfrost-milestone.html)

**Comment by jernejsk** [comment]
This is most likely mesa packaging issue on your distro. Kodi works fine in GBM mode on many different GPUs supported by panfrost and other mesa drivers on LibreELEC distro.

Please work with your distro developers to fix this.

**Comment by amazingfate** [comment]
@jernejsk I build mesa without swrast and now I can see panfrost is loaded in kodi.log, but the screen is still black. It should be a kodi related issue because glmark2-es2-drm and kmscude can run well. Here is the log when using panfrost: https://paste.kodi.tv/ogavavajab.kodi.
By the way, I don't see any LibreELEC image supporting rk35xx and anyone who can run LibreELEC in gbm mode on this device. There should be some device related work should be done by kodi.

**Comment by jernejsk** [comment]
@amazingfate I'm glad it works for you, but it would be nice to explain in short what you did, so anyone who finds this issue knows what to do.

**Comment by amazingfate** [comment]
> @amazingfate I'm glad it works for you, but it would be nice to explain in short what you did, so anyone who finds this issue knows what to do.

Here is the detail: https://forum.radxa.com/t/kodi-on-armbian-with-hardware-accelerating-decode/10170.
Sometimes I can see the kodi window after replug HDMI cable, but sometimes replugging HDMI won't work.
Sometimes I just wait for sometime and the kodi window shows. I don't know why.

**Comment by amazingfate** [comment]
> > @amazingfate I'm glad it works for you, but it would be nice to explain in short what you did, so anyone who finds this issue knows what to do.
> 
> Here is the detail: https://forum.radxa.com/t/kodi-on-armbian-with-hardware-accelerating-decode/10170. Sometimes I can see the kodi window after replug HDMI cable, but sometimes replugging HDMI won't work. Sometimes I just wait for sometime and the kodi window shows. I don't know why.

I can run kodi wayland with drm prime now, no need to run gbm and no worries about black screen.
