### ISSUE TITLE
raspberry pi os 64 bit and kodi 32 bit

### ISSUE THREAD

**Issue by molli1312** [xbmc/xbmc#21489]
I took the chance to try the newly released 64bit Raspberry Pi OS bullseye. While initial setup worked fine and also installation of kodi works fine. there is no 64bit widevine CDM available to use plugins like netflix via inputstream.adaptive. Just like install a 32bit kodi. But I cant.

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
kodi:armhf : Depends: kodi-bin:armhf (>= 2:19.1+dfsg2-2+deb11u1) but it is not going to be installed
Depends: kodi-bin:armhf (< 2:19.1+dfsg2-2+deb11u1.1~) but it is not going to be installed
Recommends: kodi-repository-kodi:armhf or
kodi-repository:armhf
Recommends: kodi-visualization-spectrum:armhf but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by fuzzard** [comment]
Widevine is not something we can control. Last I heard there just isn't an aarch64 widevine lib available that can be leveraged for use

**Comment by molli1312** [comment]
But i like to use the 32 bit kodi on a 64 bit system, but i cant install it.

**Comment by fuzzard** [comment]
You'll need to contact your distro about those options. It's not handled by us

**Comment by totoCZ** [comment]
https://forums.raspberrypi.com/viewtopic.php?t=347736

There is now 64-bit Widevine CDM. Can it be integrated?

**Comment by lrusak** [comment]
Please use the forum for support.

https://forum.kodi.tv/
