### ISSUE TITLE
URLs are being added to local cache, preventing playing item twice from inside video plugin

### ISSUE THREAD

**Issue by bigretromike** [xbmc/xbmc#21495]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing item from video plugin (the url for file is http://10.1.1.100:8111/Stream/123/False/file.mkv) `void CDirectoryCache::SetDirectory(const std::string& strPath, const CFileItemList &items, DIR_CACHE_TYPE cacheType)` add `http://10.1.1.100:8111/Stream/123/False` to local cache, and play the item. When I stop playing video, and start it again, Kodi check for cache, finds `http://10.1.1.100:8111/Stream/123/False` and prevent it from being played. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Playing same item twice

## Actual Behavior

Playing item first time is possible, then I have to exit plugin and load it again to play item second time.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/8811976/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

URL for file is stored in API and each time item is played Kodi contact API, ask for URL, url is passed to Kodi
I build ListItem this way:
```
item = xbmcgui.ListItem(offscreen=True)
item.setProperty('IsPlayable', 'true')
# based on https://github.com/xbmc/xbmc/pull/19530
item.setProperty('ForceResolvePlugin', 'true')
item.setIsFolder(False)
item.setPath(url_for_player)  # url_for_player = the url from API ex. http://10.1.1.100:8111/Stream/123/False/file.mkv
xbmcplugin.setResolvedUrl(handle, True, item)
```

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.3, 19.4, 19.4-daily, 20.pre-release

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by bigretromike** [comment]
Stack looks like this. For some reason the dynPath is resolved into http://<http_server>:<port>/Stream/file.mkv which is correct, but then Kodi try to store the `URL` and then break second play.  Exiting Addon and reenter clear that same cache 

![obraz](https://user-images.githubusercontent.com/6052025/171452973-52174f24-8eff-46c7-84bf-946d585a714e.png)

**Comment by arnova** [comment]
I'm probably missing something but why: "Kodi check for cache, finds http://10.1.1.100:8111/Stream/123/False and prevent it from being played" ? Can you elaborate this?

**Comment by bigretromike** [comment]
@arnova sure.
When You play video from inside video plugin, Kodi try to find ExternalSubtitles, even so, if there is non Kodi cache that information, before it cache it Kodi Pare url Converting `http://10.1.1.100:8111/Stream/123/False/file.mkv` to `http://10.1.1.100:8111/Stream/123/False`, and save empty directory under `http://10.1.1.100:8111/Stream/123/False` in local cache, and play video. When you stop the video and start it again, Kodi parse url again and check it against cache, it finds `http://10.1.1.100:8111/Stream/123/False` and return empty item, resulting in Video being unable to play.

**Comment by bigretromike** [comment]
Fixed both in:
- [ ] Matrix: https://github.com/xbmc/xbmc/pull/21503 
- [ ] Nexus https://github.com/xbmc/xbmc/pull/21499

**Comment by bigretromike** [comment]
Issue has been fixed and merged.
