### ISSUE TITLE
openssl error

### ISSUE THREAD

**Issue by amidevous** [xbmc/xbmc#21506]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/7959572/172021081-46795231-0ba3-4c3f-9739-fbf6b50cfde5.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: windows 10
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

log file
[kodi.log](https://github.com/xbmc/xbmc/files/8838445/kodi.log)

I put you and the logs but otherwise I have no info on this problem just I'm not the only one to have seen it here

https://superuser.com/questions/1717878/openssl-error-while-trying-to-log-in-jiotv-in-kodi/1724730

I have already checked I have no version of openssl that can come into conflict

and what's weird is that there is no integrated version in kodi either

yet in windows there is no basic openssl version in the system

ps I use the installable 64-bit installer version and not the store because I hate the microsoft store for me, this store shouldn't even exist, especially since they are not even able to have all of them like on linux and it's a damn watch to be able to publish an application there

I also can't say how this problem happened or even how to reproduce it.

just I can not use kodi my windows for months because of this error

I always have to go through android or linux which does not have this error

**Comment by thexai** [comment]
> just I can not use kodi my windows for months because of this error

Clean install should fix...  if not open a support thread here: https://forum.kodi.tv/forumdisplay.php?fid=59
