### ISSUE TITLE
[GBM] Failure to switch video modes after TV is off and on.

### ISSUE THREAD

**Issue by smp79** [xbmc/xbmc#21504]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm having this issue after upgrading to a new Intel Tiger Lake-U box (Celeron 6305).
If the TV is power cycled when Kodi is running I am unable to switch to 4K 50/60Hz video modes anymore. This shows up in kodi.log when attempting to switch the video mode:
```
2022-06-03 01:26:12.028 T:957     ERROR <general>: CDRMAtomic::DrmAtomicCommit - test commit failed: (Invalid argument) - falling back to last successful atomic request
2022-06-03 01:26:12.028 T:957     ERROR <general>: 
                                                   Object: plane	ID: 40
                                                   Object: connector	ID: 326
                                                   Object: crtc	ID: 98
                                                     Property: MODE_ID	ID: 23	Value: 333
```
After Kodi is restarted it works normally again. 

### To Reproduce

1.  Boot LibreELEC (current nightly)
2.  Switch the TV off
3.  Switch the TV on
4.  Try to switch to 4K 50 or 60Hz. 

### Debuglog

The debuglog can be found here:
https://www.toptal.com/developers/hastebin/upodoyimiq.yaml

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC
 - Kodi version: current master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by smp79** [comment]
I figured a super hacky way to work around this issue by disabling hotplug detect in i915 kernel driver:

```
diff --git a/drivers/gpu/drm/i915/display/intel_hotplug.c b/drivers/gpu/drm/i915/display/intel_hotplug.c
index 8204126..cc24265 100644
--- a/drivers/gpu/drm/i915/display/intel_hotplug.c
+++ b/drivers/gpu/drm/i915/display/intel_hotplug.c
@@ -246,7 +246,7 @@ static void intel_hpd_irq_storm_reenable_work(struct work_struct *work)
 
 	for_each_hpd_pin(pin) {
 		if (dev_priv->hotplug.stats[pin].state == HPD_DISABLED)
-			dev_priv->hotplug.stats[pin].state = HPD_ENABLED;
+			dev_priv->hotplug.stats[pin].state = HPD_DISABLED;
 	}
 
 	intel_hpd_irq_setup(dev_priv);
@@ -595,7 +595,7 @@ void intel_hpd_init(struct drm_i915_private *dev_priv)
 
 	for_each_hpd_pin(i) {
 		dev_priv->hotplug.stats[i].count = 0;
-		dev_priv->hotplug.stats[i].state = HPD_ENABLED;
+		dev_priv->hotplug.stats[i].state = HPD_DISABLED;
 	}
 
 	/*
```

**Comment by Larx** [comment]
I have a similar problem which might be related:
I run Kodi standalone on a Ubuntu 21.10 installation (now updated to 22.04, problem persists) as home theatre. To work around problems when TV and/or AVR are not turned on at boot time, I use a custom EDID file loaded in the initramfs. This setup has worked for years now.
Since a few weeks (probably related to some unconspicious Ubuntu update) starting Kodi does only work if both AVR and TV are turned already when Kodi starts. If not, the kodi.log contains the following entries:
```
2022-07-10 07:44:29.716 T:18455   ERROR <general>: CWinSystemGbm::InitWindowSystem - failed to initialize Atomic DRM
2022-07-10 07:44:29.748 T:18455   ERROR <general>: CWinSystemGbm::InitWindowSystem - failed to initialize Legacy DRM
```
and the TV receives no signel.

Restarting Kodi with TV and AVR turned on fixes the issue.
