### ISSUE TITLE
Audio Passthrough settings missing in Kodi 19.4

### ISSUE THREAD

**Issue by cgcgcgcgcg** [xbmc/xbmc#21508]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm not using Passthrough, but I noticed Passthrough options are missing in Kodi v19.4.
The ones that appear here:
https://kodi.wiki/view/Settings/System/Audio#Audio_Passthrough

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

See Passthrough options.

## Actual Behavior

Only a non-clickable title appears instead.

## Possible Fix

I have no idea.

### To Reproduce

1. 
2.
3.
Open System settings > Audio, scroll down to Audio Passthrough.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/8839900/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![passthrough](https://user-images.githubusercontent.com/38960370/172049403-2d865305-dc65-43e3-a8ba-d14493854f8e.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by cgcgcgcgcg** [comment]
I think Kodi now automatically detects if eg a soundbar is connected or your TV supports Audio Passthrough, that's why I don't get settings.

**Comment by fritsch** [comment]
The log is quite to the point: You are using pulseaudio and your installation is not configured to allow passthrough with it, therefore kodi only finds your PCM setup.

Works as intended.

**Comment by cgcgcgcgcg** [comment]
> The log is quite to the point: You are using pulseaudio and your installation is not configured to allow passthrough with it, therefore kodi only finds your PCM setup.
> 
> Works as intended.

Thank you.
