### ISSUE TITLE
Picture Slideshow Screensaver not installing on Raspberry Pi OS

### ISSUE THREAD

**Issue by PanderMusubi** [xbmc/xbmc#21510]
### Describe the bug
Here is a clear and concise description of what the problem is:
Installing Picture Slideshow Screensaver on Raspberry Pi OS fails when dependency IPTCInfo3 is tried to being downloaded.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Installation does not fail.

## Actual Behavior
Dialog called "IPTCInfo3" with text "Installation failed" is shown and installation of the screensaver is not successful.

## Possible Fix
Manually copy `script.module.iptcinfo3` from `~/.kodi/addons` from a system that has it.

### To Reproduce
1. Install Picture Slideshow Screensaver via the default addon repo

### Debuglog
The debuglog can be found here:

    2022-06-05 20:06:25.393 T:532     ERROR <general>: CCurlFile::Stat - Failed: Couldn't resolve host name(6) for https://ftp.halifax.rwth-aachen.de/xbmc/addons/matrix/script.module.iptcinfo3/script.module.iptcinfo3-2.1.4+matrix.1.zip
    2022-06-05 20:06:29.027 T:532     ERROR <general>: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
    2022-06-05 20:06:29.027 T:532     ERROR <general>: CCurlFile::Open failed with code 0 for https://ftp.halifax.rwth-aachen.de/xbmc/addons/matrix/script.module.iptcinfo3/script.module.iptcinfo3-2.1.4+matrix.1.zip:
                                                       
    2022-06-05 20:06:29.028 T:532     ERROR <general>: CAddonInstallJob[script.module.iptcinfo3]: failed to download special://home/addons/packages/script.module.iptcinfo3-2.1.4 matrix.1.zip

The URL indeed does not exist. For Kodi 2:19.4+dfsg1-2 on Ubuntu 22.04, the installation does work. The log for that says

    2022-06-05 20:19:23.501 T:483324    INFO <general>: CAddonMgr::FindAddon: script.module.iptcinfo3 v2.1.4+matrix.1 installed

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspberry Pi OS 11 bullseye
 - Kodi version: 2:19.4-2~bullseye

PS Perhaps related is this error:

    $ sudo apt-get install kodi-repository-kodi
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    The following NEW packages will be installed:
      kodi-repository-kodi
    0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
    Need to get 55.3 kB of archives.
    After this operation, 151 kB of additional disk space will be used.
    Get:1 http://deb.debian.org/debian bullseye/main arm64 kodi-repository-kodi all 2:19.1+dfsg2-2+deb11u1 [55.3 kB]
    Fetched 55.3 kB in 0s (156 kB/s)          
    Selecting previously unselected package kodi-repository-kodi.
    (Reading database ... 48830 files and directories currently installed.)
    Preparing to unpack .../kodi-repository-kodi_2%3a19.1+dfsg2-2+deb11u1_all.deb ...
    Unpacking kodi-repository-kodi (2:19.1+dfsg2-2+deb11u1) ...
    dpkg: error processing archive /var/cache/apt/archives/kodi-repository-kodi_2%3a19.1+dfsg2-2+deb11u1_all.deb (--unpack):
     trying to overwrite '/usr/share/kodi/addons/repository.xbmc.org/addon.xml', which is also in package kodi 2:19.4-2~bullseye
    Errors were encountered while processing:
     /var/cache/apt/archives/kodi-repository-kodi_2%3a19.1+dfsg2-2+deb11u1_all.deb
    E: Sub-process /usr/bin/dpkg returned an error code (1)

If it is not related, is it another issue?

**Comment by enen92** [comment]
This was certainly the mirror being down at the moment of installation
