### ISSUE TITLE
Fail to build without internal ffmpeg.

### ISSUE THREAD

**Issue by laichiaheng** [xbmc/xbmc#21538]
### Describe the bug
Here is a clear and concise description of what the problem is:

```
[ 19%] Built target windowing_X11
make: *** [Makefile:146：all] 錯誤 2
==> 錯誤： build() 遭遇失敗。
    正在中止...
 -> error making: kodi-git
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Successfully build.

## Actual Behavior

Fail.

## Possible Fix

I don't know.

### To Reproduce

1. Build kodi-git in AUR
2. Disable Internal FFmpeg.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux
 - Kodi version: git

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
You need to provide more info.

Kodi provides the internal ffmpeg as we specifically target, and potentially patch things for our use case.
You can use an external ffmpeg, but behaviour is not guaranteed.

On top of that, we do NOT support ffmpeg 5 currently.

Provide some logs, and some details about versions of ffmpeg you're trying to use, and we can potentially reopen this, but at this time i'll close this issue.

**Comment by laichiaheng** [comment]
> You need to provide more info.
> 
> Kodi provides the internal ffmpeg as we specifically target, and potentially patch things for our use case. You can use an external ffmpeg, but behaviour is not guaranteed.
> 
> On top of that, we do NOT support ffmpeg 5 currently.
> 
> Provide some logs, and some details about versions of ffmpeg you're trying to use, and we can potentially reopen this, but at this time i'll close this issue.

That explains everything, I'm currently using ffmpeg 5 on my system.
I do that because I want to watch HDR via KODI DRM on Linux.

**Comment by laichiaheng** [comment]
@fuzzard How to build KODI with ffmpeg4.4?

**Comment by fuzzard** [comment]
Probably want to use -DFFMPEG_PATH=<path/prefix/to/ffmpeg4.4/> as part of your cmake generation command.

https://github.com/xbmc/xbmc/blob/89f7ada153148efa800e05f44d70e0d2baaf94dc/cmake/modules/FindFFMPEG.cmake#L12-L13

**Comment by laichiaheng** [comment]
> 

Is the prefix path of the binary?
```
[laichiaheng@Julian-PC ~]$ whereis ffmpeg
ffmpeg: /usr/bin/ffmpeg /usr/share/ffmpeg /usr/share/man/man1/ffmpeg.1.gz
```
I also see someone says that we need to add `-DCMAKE_PREFIX_PATH="/usr/lib/ffmpeg4.4;/usr/include/ffmpeg4.4"` to use ffmpeg4.4 on Manjaro/ArchLinux.

**Comment by laichiaheng** [comment]
@fuzzard 
It fails after I add `-DCMAKE_PREFIX_PATH="/usr/lib/ffmpeg4.4;/usr/include/ffmpeg4.4"` and `-DFFMPEG_PATH=/usr/bin/ffmpeg;/usr/share/ffmpeg;/usr/share/man/man1/ffmpeg.1.gz`

```
[ 68%] Linking CXX static library guilib.a
[ 68%] Built target guilib
make: *** [Makefile:146：all] 錯誤 2
==> 錯誤： build() 遭遇失敗。
    正在中止...
```

**Comment by laichiaheng** [comment]
@fuzzard I can't even build it with internal ffmpeg
```
[ 63%] Building CXX object build/xbmc/CMakeFiles/xbmc.dir/ServiceBroker.cpp.o
[ 64%] Building CXX object build/xbmc/CMakeFiles/xbmc.dir/ServiceManager.cpp.o
[ 64%] Building CXX object build/xbmc/CMakeFiles/xbmc.dir/SystemGlobals.cpp.o
[ 64%] Building CXX object build/xbmc/CMakeFiles/xbmc.dir/TextureCache.cpp.o
[ 64%] Building CXX object build/xbmc/CMakeFiles/xbmc.dir/TextureCacheJob.cpp.o
[ 64%] Building CXX object build/xbmc/CMakeFiles/xbmc.dir/TextureDatabase.cpp.o
[ 64%] Building CXX object build/xbmc/CMakeFiles/xbmc.dir/ThumbLoader.cpp.o
[ 64%] Building CXX object build/xbmc/CMakeFiles/xbmc.dir/URL.cpp.o
[ 64%] Building CXX object build/xbmc/CMakeFiles/xbmc.dir/Util.cpp.o
[ 64%] Building CXX object build/xbmc/CMakeFiles/xbmc.dir/XBDateTime.cpp.o
[ 64%] Building CXX object build/xbmc/CMakeFiles/xbmc.dir/Autorun.cpp.o
[ 64%] Linking CXX static library addons.a
[ 64%] Built target addons
[ 64%] Linking CXX static library xbmc.a
[ 64%] Built target xbmc
make: *** [Makefile:146：all] 錯誤 2
==> 錯誤： build() 遭遇失敗。
    正在中止...

```
