### ISSUE TITLE
[Android] Cannot import PIL 

### ISSUE THREAD

**Issue by bigretromike** [xbmc/xbmc#21531]
### Describe the bug
Here is a clear and concise description of what the problem is:

`import PIL` results in No module named 'PIL'

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Import PIL (pillow)

## Actual Behavior

Does not import PIL

### To Reproduce

1. import PIL
2. run on Android
3.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/8873475/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4, 19.master, 20.master 20.daily

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Use 

```
from PIL import Image
```

**Comment by bigretromike** [comment]
> Use
> 
> ```
> from PIL import Image
> ```

```from PIL import ImageFont, ImageDraw, Image```
also dont work

**Comment by wsnipex** [comment]
logs? all those are included in kodi and should work.

**Comment by bigretromike** [comment]
> logs? all those are included in kodi and should work.
[kodi_android_pil.log](https://github.com/xbmc/xbmc/files/8877808/kodi_android_pil.log)

**Comment by sanzoghenzo** [comment]
HItting this bug with the [Hyperion addon](https://github.com/hyperion-project/hyperion.kodi/issues/50) as well...

Where there progress on this?

**Comment by fuzzard** [comment]
from testing, you need to add the import to the addon.xml eg https://github.com/hyperion-project/hyperion.kodi/blob/bd6aaab1d094bf157bdf38cedf1d7706d3eba80a/addon.xml#L3-L7

add something like the following to the requires block

```
        <import addon="script.module.pil" version="1.1.7"/>
```
