### ISSUE TITLE
Colors and contrast issues with Intel Graphics Hardware acceleration on Windows.

### ISSUE THREAD

**Issue by markosjal** [xbmc/xbmc#21547]
### Describe the bug
Saturation and contrast is abnormal with hardware acceleration.

Colors are over saturated and whites clip with hardware acceleration. Chaning settings to "software" and disabling DIXV2 gives me a more normal image. This is on a Chromebox with MrChromebox.tech hack. This is standard Intel Hardware and drivers. This problem is with My PVR Streams that come from older HDHomerun Dual Mpeg2 and web based h264 and native (not transcoded) recordings.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Both hardware decoding/acceleration and software decoding with no acceleration should yield similar looking results, but do not.  Before installing Windows on this system, this same hardware and display were running Kodi 19.4 on Libreelec and this issue did not exist. 
## Actual Behavior

Luminance and chrominance are incorrect. Saturated colors appear as colored "blobs", lacking detail. Luminance is often "white clipped", or lacks detail in whites. See attached images which have examples from both "Limited" and "Full" luminance ranges.

Limited HDMI range (one dark, then one bright)

Full HDMI range (one dark, then one bright)

Both of the darker and less saturated images were with software decode AND DXVA2 Acceleration disabled

Both of the brighter and more saturated images were with DXVA decode and DXVA2 Acceleration enabled.

The main difference is seen in the red dress which appears as an undetailed "blob" when hardware decoding and acceleration are enabled.

### To Reproduce

As far as I can tell any install on a CN60 Chromebox with Mrchromebox.tech hack, Windows 10 (home) and Kodi 19.X will yield same results with Kodi
### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ekuqupuxon.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

1st image is with Limited HDMI range, software decode AND DXVA2 Acceleration disabled. See the VPL?
![screenshot00000](https://user-images.githubusercontent.com/281916/173305008-ee21ee59-6153-4cf0-87e4-9eb8364d1028.png)

2nd Image image is with Limited HDMI range, DXVA decode AND DXVA2 Acceleration enabled. NO VPL!
![screenshot00001](https://user-images.githubusercontent.com/281916/173305014-9c977311-3909-4895-93c2-b1894342c0f5.png)

3rd Image is with Full HDMI range, software decode AND DXVA2 Acceleration disabled. See the VPL?
![screenshot00003](https://user-images.githubusercontent.com/281916/173305021-f94dccdc-7064-40d7-bdd3-971394e250c7.png)

4th Image is with Full HDMI range, DXVA decode AND DXVA2 Acceleration enabled. No VPL!
![screenshot0002](https://user-images.githubusercontent.com/281916/173305017-90b2c034-ee96-4c69-a0f3-fbef518f2eb6.png)

5th image is from Linux (Libreelec) system running on similar Intel Hardware. It uses hardware render, which looks the same as the same Libreelec with software render. This uses limited HDMI range (was resized to Match the others here, no color changes) . VPL and Acceleration! I love Linux.
![screenshot720](https://user-images.githubusercontent.com/281916/173315956-ea254e01-2901-498e-b95b-858e9a93ecce.png)

### Your Environment
Used Operating system:
 
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP (whatever that is???)

 - Operating system version/name: Windows 10 Home x64
 - Kodi version: Versions 19.1 and 19.4 tested with same results, meaning it appears unrelated to this bug : 
https://github.com/xbmc/xbmc/issues/21081

**Comment by thexai** [comment]
> This is standard Intel Hardware and drivers.

You should go much deeper into this. Intel currently has two different GUI's for accessing driver settings: the new "Intel Command Center" and the old "Intel Graphics Control panel".

There are literally dozens of settings that can be tweaked that affect the image you get when decoding video using DXVA2. Especially all the settings in the "video" section (refer to video playback).

There are of course contrast "enhancement" filters, color "enhancement", noise filter, skin "tone correction", etc.

Before thinking that there is a bug in Kodi (that only affects you) you should familiarize with these settings and at least be aware of what settings you are using and provide a lot more information (regarding to drivers used and drivers settings).

Think there are thousands of people using Kodi on Intel NUC or similar (Windows 10 / 11) with 4K and HDR screens. Absolutely no one so far has complained of any video problems (on Intel).

**Comment by thexai** [comment]
```
2022-06-13 00:32:23.571 T:4776     INFO <general>: DX::DeviceResources::CheckNV12SharedTexturesSupport: extended NV12 shared textures is NOT supported
2022-06-13 00:32:23.571 T:4776     INFO <general>: DX::DeviceResources::CreateDeviceResources: device is created on adapter 'Intel(R) HD Graphics' with D3D_FEATURE_LEVEL_11_1
```

All current Intel drivers supports DirectX Feature Level 12.x on Windows 10 and NV12 shared textures.

So seeing this in the log I can only think that you are using an incorrect or very old Intel driver.

**Comment by thexai** [comment]
`2022-06-13 00:32:23.314 T:4776     INFO <general>: Host CPU: Intel(R) Celeron(R) 2955U @ 1.40GHz, 2 cores available`

This Celeron CPU is from year 2013 and Intel does not provide video drivers for Windows 10.

See https://www.intel.com/content/www/us/en/support/articles/000090440/graphics.html selecting Windows 10 in drop-down menu.

That means you were able to install Windows 10 by chance.

That does not mean that it can't work well with another OS, nor does it mean that it does not have enough power.

Just ---> **Intel does not offer video drivers or support for this CPU in Windows 10**
