### ISSUE TITLE
[Linux][Kodi Matrix] Python makes Kodi crash

### ISSUE THREAD

**Issue by Kupo91** [xbmc/xbmc#21544]
### Describe the bug
I recently installed Lubuntu 22.04. and Kodi 19.4 via ppa. If I try to launch the addon [Rom Collection Browser](https://github.com/maloep/romcollectionbrowser), Kodi stops responding for a few seconds, then it crashs. This happens with the default skin Estuary. If I add the skin [Aeon MQ8 Mod](https://forum.kodi.tv/showthread.php?tid=358382) from latts and enable it, Kodi even crashs right after start. This didn't happen on my old setup (Lubuntu 21.10). Also it doesn't happen with the Kodi flatpak. According to someone from the kodinerds forum, it's a python bug. I don't have this issue on my windows device aswell.

## Expected Behavior
I can use my usual addons while Kodi is not crashing.

## Actual Behavior
Kodi is always crashing, if RCB is installed and I try to launch it (maybe other addons and components of Kodi are affected too, I didn't try more).

### To Reproduce
1. Install (L)ubuntu 22.04.
2. Install Kodi via ppa:team-xbmc/ppa
3. Install the [Rom Collection Browser](https://github.com/maloep/romcollectionbrowser)
4. Restart Kodi and try to launch RCB

### Debuglog
The debuglog can be found here: 
[kodi_crashlog-20220610_201505.log](https://github.com/xbmc/xbmc/files/8885477/kodi_crashlog-20220610_201505.log)

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi Matrix v19.4

**Comment by CastagnaIT** [comment]
i suspect you have a bugged python version, try check,
Kodi 19 you should use Python 3.9 from build v.3.9.13 or above,
python 3.10 have a bug, and if you want stay to 3.10 you should rollback to build v3.10.2-1, or try test v3.10.5

**Comment by DaVukovic** [comment]
@CastagnaIT AFAIK Python 3.10 is shipped by default with *buntu 22.04. 

So you say it's a python error and not a Kodi error in relation with python 3.10? Somehow I do have something in mind that someone at the team said "Kodi is currently not python 3.10 compatible" @fuzzard probably?!

I could be that I'm totally wrong. But I recommended to create this bug report to the user.

**Comment by CastagnaIT** [comment]
a couple of users time ago has report to me crashes with my addon with same py versions,
and i reached the same conclusions of the LibreElec team (solved as my comment above)

then probably ask to LibreElec team can provide more information about the python problem/bug

**Comment by jul2040** [comment]
how can I make kodi use python 3.9 if i have it installed? If i install it, kodi still attempts to use python 3.10 and crashes.

**Comment by hyc** [comment]
I've also got a crash in libpython 3.10 on Ubuntu 22.04 with Kodi 19.4. Both from the Ubuntu repo and from the XBMC ppa.
[kodi_crashlog-20220627_005941.log](https://github.com/xbmc/xbmc/files/8987762/kodi_crashlog-20220627_005941.log)

ldd shows the kodi.bin depends on libpython3.10.so.1.0. I don't see a libpython3.9 in apt that I can install.

**Comment by hyc** [comment]
I installed pyhon3.9 and libpytthon3.9 from the deadsnakes ppa, as doc'd here https://ubuntuhandbook.org/index.php/2020/10/python-3-9-0-released-install-ppa-ubuntu/

Then I binary patched my kodi.bin to change its dependency from libpython3.10 to libpython3.9, and the crash no longer occurs.

**Comment by fuzzard** [comment]
a main crash fix was introduced in python 3.10.5
The crash was introduced in the 3.9 series somewhere around 3.9.4 (and i believe was in all the 3.10.x releases), so anything after that crashed regularly. If your 3.9 version is 3.9.0, then it looks like the crash is the same one that is now fixed in the various python versions with their latest releases (3.9.13, 3.10.5, 3.11.0).
At a glance, it looks like ubuntu 22.04 only ships python 3.10.4. Therefore any fix will require ubuntu users to use a customised python install to update to fixed versions.

Either way, the fix is in external code to kodi, unfortunate, but not much control we have over it.
