### ISSUE TITLE
Add 'backspace' key to "SMS characters" in edit control

### ISSUE THREAD

**Issue by arneharttmann** [xbmc/xbmc#21541]
I think it's great that I can use the number keys on my remote control in an input field to type "SMS characters".
Unfortunately, I could not find a backspace key. Could you provide that? I often make mistakes when using the "SMS characters".
PS I currently use the "PRE-CH" key (-> back to the previous channel) on my Samsung remote via keymap, but I would prefer the backspace key to be integrated, i.e. while the focus is in an input field, a specific key is recognized as backspace.

**Comment by fuzzard** [comment]
We only accept bugs for this issue tracker.

You can place feature requests on the forum at https://forum.kodi.tv/forumdisplay.php?fid=9
