### ISSUE TITLE
Menu navigation marks don't appear on some DVD .ISO image files on Kodi 19 and 20

### ISSUE THREAD

**Issue by MoviePlayerMan** [xbmc/xbmc#21553]
### Describe the bug
Here is a clear and concise description of what the problem is:

Menu navigation marks don't appear on some DVD .ISO image files on Kodi 19 and 20, these worked fine on Kodi 18 and earlier.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Marks showing what is being selected in the menu should show up.

## Actual Behavior

Navigation marks don't show on some .ISO files.  Screen shots below give examples

### To Reproduce

1. Navigation marks don't show on 2 Broke Girls season sets
2.Navigation marks don't show on Allo Allo  season sets
3.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/8896111/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![2BrokeGirls18-Edit](https://user-images.githubusercontent.com/107443186/173486893-1612aac8-bc74-4766-bd2c-04d64bb5022a.jpg)

![2BrokeGirls1920-Edit](https://user-images.githubusercontent.com/107443186/173486947-7efa86fa-f0e0-47d2-adc5-38ecce204abf.jpg)

![AlloAllo18-Edit](https://user-images.githubusercontent.com/107443186/173487026-3cb47da0-f0a0-4943-953a-de3d1f044079.jpg)

![AlloAllo1920-Edit](https://user-images.githubusercontent.com/107443186/173487096-f4622638-027b-41da-b2b8-10c5cd56ed0d.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: [LibreELEC]
 - Kodi version: 19 and 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Can you check with a different system/hardware if they show up in kodi? I bet this was due to the change to the video pipeline in v19 for the raspberry pi

**Comment by popcornmix** [comment]
I've seen it reported a few times. I believe it affects all gbm platforms.
I'd guess it's some ordering issue.
i.e. the missing marks are being rendered at the wrong time (e.g. when a viewport/glScissor area doesn't include it, or perhaps after its been presented), but I'm just guessing.

If anyone knows how these items are meant to be rendered (e.g. by which function), I could try adding logging, but this isn't code I've ever worked on.

**Comment by enen92** [comment]
@popcornmix if you breakpoint on https://github.com/xbmc/xbmc/pull/21500/files#diff-cc0950c10cb4088a36d4b8af55a6ca4dde54eb3414c4eb6838202897634e3462R1204 you might be able to find out what's wrong

**Comment by arnova** [comment]
Not sure if it's the same issue but I've also seen this happen on Linux occasionally. Seems like a timing/race condition issue.

**Comment by popcornmix** [comment]
@enen92 I got gdb attached when navigating a dvd (Pacific Rim) and menu highlights were not showing.
```
(gdb) p pOverlayPicture->highlight_color
$1 = {{131, 85, 200}, {131, 85, 200}, {131, 85, 200}, {131, 85, 200}}
```
It looks like this value is used in convert_rgba (OverlayRendererUtil.cpp), but that breakpoint wasn't getting hit.

**Comment by popcornmix** [comment]
@enen92 I got gdb attached when navigating a dvd (Pacific Rim) and menu highlights were not showing.
```
(gdb) p pOverlayPicture->highlight_color
$1 = {{131, 85, 200}, {131, 85, 200}, {131, 85, 200}, {131, 85, 200}}
```
It looks like this value is used in convert_rgba (OverlayRendererUtil.cpp), but that breakpoint wasn't getting hit.

**Comment by popcornmix** [comment]
There is a potential fix [here](https://github.com/xbmc/xbmc/pull/21655), including a LE test build for Pi4 if anyone can test.

**Comment by MoviePlayerMan** [comment]
I'm afraid with my limited experience with LE and Kodi I have no idea how to use such an update file.  I searched online but didn't find any directions.  Can you in some way point me to directions? Or would this change be built into the nightly image builds on the LibreELEC site?

**Comment by lrusak** [comment]
> I'm afraid with my limited experience with LE and Kodi I have no idea how to use such an update file. I searched online but didn't find any directions. Can you in some way point me to directions? Or would this change be built into the nightly image builds on the LibreELEC site?

@MoviePlayerMan Please use the forums for support or read the wiki. https://wiki.libreelec.tv/support/update

**Comment by MoviePlayerMan** [comment]
Thanks for the link.  The DVD navigation marks are working perfect now. Thanks.
