### ISSUE TITLE
G20S Pro Plus FIRC Remote Control, OK Button

### ISSUE THREAD

**Issue by BullShark** [xbmc/xbmc#21566]
### Describe the bug
Here is a clear and concise description of what the problem is:

https://www.amazon.com/Control-Wireless-Sensing-Android-Projector/dp/B09JSX4JLB/

I have tried Keymap Editor Add-on to map the OK Button to the Action for it. For that button, I have not been able to get it to work in Kodi. The "OK" button works only if the mouse cursor is on. Once it's off and the remote's arrow buttons are used instead, the "OK" button no longer works.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect the OK/Select Button to work. And if not, it should work after using Keymap Editor.

## Actual Behavior

No action is performed when pressing the Okay/Select Button. When using Keymap Editor, the button is detected, and a code is assigned for it as seen in the picture. However, Kodi still does not respond to that button.

### To Reproduce

1. I am using CoreElec Linux on a Samsung 65" TV. Start CoreElec with the FIRC USB Dongle to the remote plugged in.
2. Move over different items in the menu with the Arrow Buttons on the remote. Try to select an item with the OK Button.
3. Nothing at all happens when using that button. The same applies to the Back Button. The Back Button only does not work when the mouse cursor is enabled in the remote. It works otherwise.

### Debuglog
The debuglog can be found here:

It's too big to paste here.

https://paste.kodi.tv/onixeqacig

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/1526595/174229926-f08ef7c0-b3a4-4299-8390-6eae620339c2.png)

![image](https://user-images.githubusercontent.com/1526595/174230028-44c0e958-0f4e-4fca-a30f-5321e7d3c838.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
CoreElec Linux on an ODroid N2+ hooked up to a 4k Samsung 65" TV.

 - Operating system version/name:
 - Kodi version:

![image](https://user-images.githubusercontent.com/1526595/174231964-ce3fa139-2ef0-4bc6-9c86-26ae8fe7c8d8.png)

**Comment by BullShark** [comment]
Editing the mouse.xml according to this article fixed it.

https://www.reddit.com/r/kodi/comments/8i0po5/ok_button_on_usb_remote_does_not_work_when_mouse/

**Comment by BullShark** [comment]
Now the air mouse doesn't work, and the back and ok button only works if I press the button to toggle the airmouse on and off. This was only a workaround, not a fix.

**Comment by digital-ward** [comment]
Same issue on stable and preview

**Comment by vennen** [comment]
hi, came across the same issue...

does anybody know a workaround, if a solution is not avail.?

**Comment by DEHuCKA85** [comment]
Hi. This solution worked for me.
go to console.
`cat /proc/bus/input/devices`
searching you g20s device
copy the line after "Sysfs" 
`/devices/virtual/misc/uhid/0005:2717:32B9.0003/input/input8` - or something.
execute command
`udevadm test /devices/virtual/misc/uhid/0005:2717:32B9.0003/input/input8 2>&1 | grep ^MODALIAS`
to find out your modalias
It will be - MODALIAS=input:b0005v2717p32B9e4A4C-e0,1,4,k72,73,74,80,8C,90,9B,9C,9E,9F,AC,AD,161,189,18F,190,191,244,246,ram4,lsfw. 
Something like that. 
You need to find out file - *.local-keyboard.hwdb. Try to search all of *.hwdb files.
Edit this file. You need to insert these lines at the end of the file.
`evdev:input:b0005v2717p32B9e4A4C*
 KEYBOARD_KEY_c0041=enter`
After input: should be your value.
After that execute
`udevadm hwdb --update`
and reboot.
Voila. It works.

**Comment by digital-ward** [comment]
I: Bus=0003 Vendor=4842 Product=0001 Version=0201
N: Name="HAOBO Technology USB Composite Device Keyboard"
P: Phys=usb-0000:00:14.0-3.2/input2
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.2/0003:4842:0001.0009/input/input23
U: Uniq=1120030400060623
H: Handlers=sysrq kbd leds event3 
B: PROP=0
B: EV=120013
B: KEY=1000000000007 ff9f207ac14057ff febeffdfffefffff fffffffffffffffe
B: MSC=10
B: LED=1f

I: Bus=0003 Vendor=4842 Product=0001 Version=0201
N: Name="HAOBO Technology USB Composite Device Consumer Control"
P: Phys=usb-0000:00:14.0-3.2/input2
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.2/0003:4842:0001.0009/input/input24
U: Uniq=1120030400060623
H: Handlers=kbd event4 
B: PROP=0
B: EV=1f
B: KEY=306ff 0 0 483ffff17aff32d bfd4444600000000 1 130ff38b17c000 677bfad9415fed 9ed68000004400 10000002
B: REL=1040
B: ABS=100000000
B: MSC=10

I: Bus=0003 Vendor=4842 Product=0001 Version=0201
N: Name="HAOBO Technology USB Composite Device System Control"
P: Phys=usb-0000:00:14.0-3.2/input2
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.2/0003:4842:0001.0009/input/input25
U: Uniq=1120030400060623
H: Handlers=kbd event5 
B: PROP=0
B: EV=13
B: KEY=4000 10000000000000 0
B: MSC=10

I: Bus=0003 Vendor=4842 Product=0001 Version=0201
N: Name="HAOBO Technology USB Composite Device"
P: Phys=usb-0000:00:14.0-3.2/input3
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.3/0003:4842:0001.000A/input/input26
U: Uniq=1120030400060623
H: Handlers=mouse0 event6 
B: PROP=0
B: EV=17
B: KEY=70000 0 0 0 0
B: REL=903
B: MSC=10

LibreELEC:~ # udevadm test /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.2/0003:4842:0001.0009/input/input23 2>&1 | grep ^MODALIAS
MODALIAS=input:b0003v4842p0001e0201-e0,1,4,11,14,k71,72,73,74,75,77,79,7A,7B,7C,7D,7E,7F,80,81,82,83,84,85,86,87,88,89,8A,8C,8E,96,98,9E,9F,A1,A3,A4,A5,A6,AD,B0,B1,B2,B3,B4,B7,B8,B9,BA,BB,BC,BD,BE,BF,C0,C1,C2,F0,ram4,l0,1,2,3,4,sfw
LibreELEC:~ # udevadm test /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.2/0003:4842:0001.0009/input/input24 2>&1 | grep ^MODALIAS
MODALIAS=input:b0003v4842p0001e0201-e0,1,2,3,4,k71,72,73,74,77,80,82,83,85,86,87,88,89,8A,8B,8C,8E,90,96,98,9B,9C,9E,9F,A1,A3,A4,A5,A6,A7,A8,A9,AB,AC,AD,AE,B0,B1,B2,B5,B6,CE,CF,D0,D1,D2,D4,D8,D9,DB,DF,E0,E1,E4,E5,E6,E7,E8,E9,EA,EB,F0,F1,F4,100,161,162,166,16A,16E,172,174,176,177,178,179,17A,17B,17C,17D,17F,180,182,183,185,188,189,18C,18D,18E,18F,190,191,192,193,195,197,198,199,19A,19C,1A0,1A1,1A2,1A3,1A4,1A5,1A6,1A7,1A8,1A9,1AA,1AB,1AC,1AD,1AE,1AF,1B0,1B1,1B7,1BA,240,241,242,243,244,245,246,247,249,24A,250,251,r6,C,a20,m4,lsfw
LibreELEC:~ # udevadm test /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.2/0003:4842:0001.0009/input/input25 2>&1 | grep ^MODALIAS
MODALIAS=input:b0003v4842p0001e0201-e0,1,4,k74,8E,ram4,lsfw
LibreELEC:~ # udevadm test /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.3/0003:4842:0001.000A/input/input26 2>&1 | grep ^MODALIAS
MODALIAS=input:b0003v4842p0001e0201-e0,1,2,4,k110,111,112,r0,1,8,B,am4,lsfw

Which one is the right one? It doesn't look like yours :(

**Comment by DEHuCKA85** [comment]
I have a bluetooth connected remote.
Maybe it's different for you, because of the connection through the 2.4 controller.
modalias for all devices is about the same. to the sign -
try adding this line to hwdb file.
`evdev:input:b0003v4842p0001e0201*`
`KEYBOARD_KEY_c0041=enter`
dont forget 
`udevadm hwdb --update` 
and reboot.

**Comment by olegk25** [comment]
> I have a bluetooth connected remote. Maybe it's different for you, because of the connection through the 2.4 controller. modalias for all devices is about the same. to the sign - try adding this line to hwdb file. `evdev:input:b0003v4842p0001e0201*` `KEYBOARD_KEY_c0041=enter` dont forget `udevadm hwdb --update` and reboot.

That's a great post, thank you! It solved the same issue for me but on 2.4Ghz. 
Sorry for going off-topic but I cannot get any key to work in Bluetooth. Only mouse pointer moves, but that's it. Is there anything else to do in odrer to make it wokr?

**Comment by Etceterae** [comment]
I get this error when trying to edit:

`Error writing /usr/lib/udev/hwdb.d/70-local-keyboard.hwdb: Read-only file system`

What am I doing wrong?

**Comment by mooninite** [comment]
I purchased this remote after seeing a review of it say they received a firmware update to fix the OK button. After some trouble getting the firmware file I finally received it and updated my remote. The OK button now works as expected with no modifications to any system files. I am unsure how to distribute this update as it's a little shady and not easy to use. The update consists of a 437kb firmware file and an Android apk that performs the firmware transfer. The remote must be bluetooth paired to an Android device to perform the update. The app only displays Chinese text. After the update you can reset the remote back to RF mode.

I had difficulty receiving the update from the "vendor" initially as they linked to a Google drive share and Google had flagged it as a virus. They also couldn't send it via Gmail has it flagged it as a virus there, too. The app has a name and icon of this company (http://www.hbgic.com/) who is probably the real vendor of this remote control.

**Comment by vennen** [comment]
> I purchased this remote after seeing a review of it say they received a firmware update to fix the OK button. After some trouble getting the firmware file I finally received it and updated my remote. The OK button now works as expected with no modifications to any system files. I am unsure how to distribute this update as it's a little shady and not easy to use. The update consists of a 437kb firmware file and an Android apk that performs the firmware transfer. The remote must be bluetooth paired to an Android device to perform the update. The app only displays Chinese text. After the update you can reset the remote back to RF mode.
> 
> I had difficulty receiving the update from the "vendor" initially as they linked to a Google drive share and Google had flagged it as a virus. They also couldn't send it via Gmail has it flagged it as a virus there, too. The app has a name and icon of this company (http://www.hbgic.com/) who is probably the real vendor of this remote control.

thanks for this post; I have been looking for this quite some time now, but I cannot find it. Do you see any chance this update could be performed without any android-mobile?

**Comment by mooninite** [comment]
> thanks for this post; I have been looking for this quite some time now, but I cannot find it. Do you see any chance this update could be performed without any android-mobile?

I am sure any Bluetooth device could perform the update, but someone would have to reverse engineer the file transfer process.

**Comment by vennen** [comment]
> > thanks for this post; I have been looking for this quite some time now, but I cannot find it. Do you see any chance this update could be performed without any android-mobile?
> 
> I am sure any Bluetooth device could perform the update, but someone would have to reverse engineer the file transfer process.

How / where did you get the file?

**Comment by mooninite** [comment]
> How / where did you get the file?

I will publish the files into a [repository](https://github.com/mooninite/g20s-pro-bt). The Android app crashed on my device when following the directions. The file loading step has a menu with three options. Their instructions say to use the file chooser, the first option, and choose the file. After choosing the file the app would crash. I had to copy the firmware file into the app's storage directory and use the 2nd option that looked in its own directory. The third option is a remote server option and there is a firmware file listed, but I do not know what the file is and I would not select it.

**Comment by Endoplasm** [comment]
> > How / where did you get the file?
> 
> I will publish the files into a [repository](https://github.com/mooninite/g20s-pro-bt). The Android app crashed on my device when following the directions. The file loading step has a menu with three options. Their instructions say to use the file chooser, the first option, and choose the file. After choosing the file the app would crash. I had to copy the firmware file into the app's storage directory and use the 2nd option that looked in its own directory. The third option is a remote server option and there is a firmware file listed, but I do not know what the file is and I would not select it.

Thank you so much for posting this! I was close to just buying a different remote but the Firmware update doing the steps you've given fixed the 'Ok' button for me for my use case (G20S Pro on an Android Emulator running on Windows 11).

**Comment by DaleAlan** [comment]
> > How / where did you get the file?
> 
> I will publish the files into a [repository](https://github.com/mooninite/g20s-pro-bt). The Android app crashed on my device when following the directions. The file loading step has a menu with three options. Their instructions say to use the file chooser, the first option, and choose the file. After choosing the file the app would crash. I had to copy the firmware file into the app's storage directory and use the 2nd option that looked in its own directory. The third option is a remote server option and there is a firmware file listed, but I do not know what the file is and I would not select it.

Just a quick thanks for this. Had to borrow an android phone and a bit of wangling about as I wasn’t sure I was clicking the right thing but dropped the firmware file in the phones internal documents folder and pointed step one at it and it loaded it in to step 3 and flashed to 100 percent so I think I got lucky as I haven’t got a clue with android phones and its working perfectly now.  Happy days and thanks again it was driving me nuts.

**Comment by vennen** [comment]
does anyone know if there is an updated version already in stores now? i will not be able to get my hands on an android phone, so i am currently stuck.

or: does anyone know if there is a similar (radio, not ir) remote, with the same good haptic & build quality?

**Comment by greendl1** [comment]
I tried updating the firmware but the app kept crashing. So I did the auto download but it must not have been the right firmware because it bricked it. Then I noticed the repository firmware downloaded with a txt extension instead of dat. Probably wouldn’t crash the app if I had changed the file extension.

**Comment by michaelk5593** [comment]
> ## Bug report
> ### Describe the bug
> Here is a clear and concise description of what the problem is:
> 
> https://www.amazon.com/Control-Wireless-Sensing-Android-Projector/dp/B09JSX4JLB/
> 
> I have tried Keymap Editor Add-on to map the OK Button to the Action for it. For that button, I have not been able to get it to work in Kodi. The "OK" button works only if the mouse cursor is on. Once it's off and the remote's arrow buttons are used instead, the "OK" button no longer works.
> 
> ## Expected Behavior
> Here is a clear and concise description of what was expected to happen:
> 
> I expect the OK/Select Button to work. And if not, it should work after using Keymap Editor.
> 
> ## Actual Behavior
> No action is performed when pressing the Okay/Select Button. When using Keymap Editor, the button is detected, and a code is assigned for it as seen in the picture. However, Kodi still does not respond to that button.
> 
> ## Possible Fix
> ### To Reproduce
> Steps to reproduce the behavior:
> 
> 1. I am using CoreElec Linux on a Samsung 65" TV. Start CoreElec with the FIRC USB Dongle to the remote plugged in.
> 2. Move over different items in the menu with the Arrow Buttons on the remote. Try to select an item with the OK Button.
> 3. Nothing at all happens when using that button. The same applies to the Back Button. The Back Button only does not work when the mouse cursor is enabled in the remote. It works otherwise.
> 
> ### Debuglog
> The debuglog can be found here:
> 
> It's too big to paste here.
> 
> https://paste.kodi.tv/onixeqacig
> 
> ### Screenshots
> Here are some links or screenshots to help explain the problem:
> 
> ![image](https://user-images.githubusercontent.com/1526595/174229926-f08ef7c0-b3a4-4299-8390-6eae620339c2.png)
> 
> ![image](https://user-images.githubusercontent.com/1526595/174230028-44c0e958-0f4e-4fca-a30f-5321e7d3c838.png)
> 
> ## Additional context or screenshots (if appropriate)
> Here is some additional context or explanation that might help:
> 
> ### Your Environment
> Used Operating system: CoreElec Linux on an ODroid N2+ hooked up to a 4k Samsung 65" TV.
> 
> * Operating system version/name:
> * Kodi version:
> 
> ![image](https://user-images.githubusercontent.com/1526595/174231964-ce3fa139-2ef0-4bc6-9c86-26ae8fe7c8d8.png)

Hi!
I have done the following steps:
1) entered the command: cat /proc/bus/input/devices
2) copy the line after "Sysfs"
/devices/virtual/misc/uhid/0005:2717:32B9.0003/input/input8 - or something.
3) entered the command: udevadm test /devices/virtual/misc/uhid/0005:2717:32B9.0003/input/input8 2>&1 | grep ^MODALIAS
4) I got an answer: MODALIAS=input:b0005v2717p32B9e4A4C-e0,1,4,k72,73,74,80,8C,90,9B,9C,9E,9F,AC,AD,161,189,18F,190,191,244,246,ram4,lsfw.
5)I found the file with the command: find -name "*.hwdb"
6)entered the command: sudo nano /usr/lib/udev/hwdb.d/60-keyboard.hwdb. To edit the keyboard configuration file.
7) added at the end of the file:
evdev:input:b0005v2717p32B9e4A4C*
 KEYBOARD_KEY_c0041=enter
8) entered the command: udevadm hwdb --update
9)entered the command: Reboot
 
Description: Ubuntu 23.04
KODI: 20.0
 After these actions, my G20 pro started working on kodi. 


PS insert your own output data.

**Comment by dedors** [comment]
A general question: does the play/pause button work for anyone?

> I tried updating the firmware but the app kept crashing. So I did the auto download but it must not have been the right firmware because it bricked it. Then I noticed the repository firmware downloaded with a txt extension instead of dat. Probably wouldn’t crash the app if I had changed the file extension.

https://github.com/mooninite/g20s-pro-bt/issues/3

Solution was to create a folder G20BTSPLUS in the root of the SD, and put the file there.

**Comment by DaleAlan** [comment]
> A general question: does the play/pause button work for anyone?
> 
> > I tried updating the firmware but the app kept crashing. So I did the auto download but it must not have been the right firmware because it bricked it. Then I noticed the repository firmware downloaded with a txt extension instead of dat. Probably wouldn’t crash the app if I had changed the file extension.
> 
> [mooninite/g20s-pro-bt#3](https://github.com/mooninite/g20s-pro-bt/issues/3)
> 
> Solution was to create a folder G20BTSPLUS in the root of the SD, and put the file there.

Yeah works fine on the pc with windows players like VLC along with Kodi’s own.

**Comment by dedors** [comment]
> Yeah works fine on the pc with windows players like VLC along with Kodi’s own.
Thanks, turns out that my remote.conf needed "0x5a 164 ; Playpause".
The remote just worked on my Vantar box, which has a HK1RBOX S905x4. It just uses (almost) the same config I guess. 
Funny thing is, that remote is IR, I have no dongle plugged in, it does not run in BT mode, and the G20S still it just works.

**Comment by lhimo** [comment]
I'm wondering if there is a firmware upgrade also for G60S Pro BT remote, how did you receive the files?

**Comment by mooninite** [comment]
I saw an Amazon review that said they contacted the seller and they provided the files. I contacted the seller and they were hesitant at first, but then tried to send me the files. They sent me a Google Drive link that no longer worked as Google thought their software was a virus. It took a few weeks before they sent me a new Google Drive link that worked.

**Comment by dlasher** [comment]
Sharing some data in case this helps.

Under Utbuntu, I was able to get the OK button mapped using "input-remapper" - evidently it's considered a mouse click instead of a keypress. Now OK is working perfectly (I mapped it to SPACE)

HOWEVER, still unable to get |<< pause or >>| to work -- XEV shows zero keypresses, and input-remapper just flashes like I didn't press any key.  Welcome any ideas?

**Comment by m1s3rys1gn4l** [comment]
> I have a bluetooth connected remote. Maybe it's different for you, because of the connection through the 2.4 controller. modalias for all devices is about the same. to the sign - try adding this line to hwdb file. `evdev:input:b0003v4842p0001e0201*` `KEYBOARD_KEY_c0041=enter` dont forget `udevadm hwdb --update` and reboot.
bro i cant find .hwdb file in my system,
i am using batocera linux for kodi.
can you help me to find it ?

**Comment by dlasher** [comment]
I was able to use "evtest" to code the codes for my G20S - sharing the buttons I cared about here:

```
BUTTON : code (default XWIN Mapping)
OK: code 353 (KEY_SELECT)
< : code 158 (KEY_BACK)
HOME : code 172 (KEY_HOMEPAGE)
<*> : code 582 (KEY_VOICECOMMAND)
VOL-DOWN: code 114 (KEY_VOLUMEDOWN)
VOL-UP: code 115 (KEY_VOLUMEUP)
LIGHT : code 127 (KEY_COMPOSE)
DEL : code 14 (KEY_BACKSPACE)

==> : code 163 (KEY_NEXTSONG)
||  : code 164 (KEY_PLAYPAUSE)
<== : code 165 (KEY_PREVIOUSSONG)
```

Then using input-remapper, i created a file that ends up living in 
```
~/.config/input-remapper/presets/HAOBO Technology USB Composite Device
```

and contains "G20S.json" - which, in my case, looks like this:

```
{
    "mapping": {
        "1,353,1": [
            "KEY_SPACE",
            "keyboard"
        ],
        "1,172,1": [
            "KEY_MENU",
            "keyboard"
        ],
        "1,127,1": [
            "KEY_MENU",
            "keyboard"
        ],
        "1,14,1": [
            "KEY_BACK",
            "keyboard"
        ],
        "1,158,1": [
            "KEY_ESC",
            "keyboard"
        ],
        "1,114,1": [
            "KEY_VOLUMEDOWN",
            "keyboard"
        ],
        "1,115,1": [
            "KEY_VOLUMEUP",
            "keyboard"
        ],
        "1,164,1": [
            "KEY_PAUSE",
            "keyboard"
        ],
        "1,163,1": [
            "KEY_PAGEDOWN",
            "keyboard"
        ],
        "1,165,1": [
            "KEY_PAGEUP",
            "keyboard"
        ]
    }
}
```

Hope this helps.

**Comment by DavidSpivey** [comment]
> I saw an Amazon review that said they contacted the seller and they provided the files. I contacted the seller and they were hesitant at first, but then tried to send me the files. They sent me a Google Drive link that no longer worked as Google thought their software was a virus. It took a few weeks before they sent me a new Google Drive link that worked.

I have the G60s. I know this is not exactly the place to ask, but I cannot find ANY mention of a firmware for this remote online except here. Do you have that firmware file still anywhere???

**Comment by EmersonBiggons** [comment]
To all it may concern the G60s Pro, especially those on a **Steam Deck** here is the solution. Should work on other distro's like CachyOS but you'll have to see for yourself.

Thanks to [DEHuCKA85](https://github.com/DEHuCKA85) for the method, my edits work very similarly, but a few things are different.

start with 
```
cat /proc/bus/input/devices
```
make sure you find the one that says ***keyboard*** specifically.

If you are in bluetooth the name will be `G60S PRO Keyboard`

If you are using the 2.4ghz dongle, the name will probably be `ZhenYe Tech BLE Remote Keyboard` 

find the part that says
`Sysfs=/devices/somethingsomething` copy everything after the "=" should look something like these two (2.4ghz & BT respectively)
`/devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb1/1-1/1-1.1/1-1.1:1.2/0003:1915:1001.0009/input/input41`
`/devices/virtual/misc/uhid/0005:2717:32C0.000A/input/input46`


then using that type

```
udevadm test /devices/whatever-yours-is/input/input?? 2>&1 | grep ^MODALIAS
```

If that doesn't work or comes up blank just type 

`udevadm test /devices/whatever-yours-is/input/input??`

and scroll up till you find something that says "MODALIAS" and it will have a string that looks like `"input:b0003v1915p1001e0201-blahblah
"` somewhere copy only the beginning portion "input:b0003v1915p1001e0201
" should look like that.

then type the following to make the hwdb

```
sudo mkdir -p /etc/udev/hwdb.d
sudo nano /etc/udev/hwdb.d/99-g60s.hwdb
```
You'll need a genuine keyboard for this next part, tho you can use the keyboard of your G60s Pro, thats what I used.

then type out

```
evdev:input:b0003v1915p1001e0201*
 KEYBOARD_KEY_c0041=enter
```

CTRL+X
then Y to confirm
ENTER

if you're like me and want both bluetooth and 2.4ghz you can just repeat the process and add the extra line.

```
evdev:input:b0003v1915p1001e0201*
 KEYBOARD_KEY_c0041=enter

evdev:input:b0005v2717p32C0e0100*
 KEYBOARD_KEY_c0041=enter

```
Should look like that.


next to finish off

```
sudo systemd-hwdb update
```
```
sudo udevadm trigger
```

You can test if it works in kodi, anything or the following,
```
sudo evtest
```
and typing the event# of the remote, same one as earlier, specifically the ***keyboard*** one.

Should say enter or similar, instead of `KEY_SELECT`

Hope this comment saves someone down the line, but be wary this fix may be undone every time the steam deck updates. So, make a backup of the file `/etc/udev/hwdb.d/99-g60s.hwdb` in `~/.config/hwdb.d/` 
```
mkdir ~/.config/hwdb.d/
sudo cp /etc/udev/hwdb.d/99-g60s.hwdb ~/.config/hwdb.d/
```
then if it's ever deleted just do this

```
sudo mkdir -p /etc/udev/hwdb.d
sudo cp ~/.config/hwdb.d/ /etc/udev/hwdb.d/99-g60s.hwdb
```
Done, you can use that to make a little bash script that you can execute from the desktop or whatever if it's deleted. Hope that helps!

**Comment by PyroghostX** [comment]
Windows 11 - G60S Pro 2.4ghz (not BT), when mouse is turned off, the OK center  still sends a press that autohotkey can pick up and action on
OK_USAGE   := 0x0041
autohotkey script to make the G60s Pro to make the center button work:


#Requires AutoHotkey v2.0
#SingleInstance Force
; ============================================================
;  MEDIA HOME BUTTON
;  Press the remote's HOME button -> close the current app
;  and bring up Flex Launcher.
; ============================================================

; ---------- SETTINGS ----------

; Full path to Flex Launcher's program file.
FlexLauncherPath := "C:\Users\user\Documents\flex-launcher\flex-launcher.exe"

; The remote's HOME button (detected: Browser_Home).
HOME_KEY := "Browser_Home"

; -------------------------------------------
; No need to edit above? Below sets up the buttons.
; -------------------------------------------

FlexExe := "flex-launcher.exe"

; HOME button -> close current app + open Flex Launcher
Hotkey(HOME_KEY, (*) => GoHome())

; ---------- OK / BACK IN ARROW MODE (Raw Input) ----------
; In arrow mode the remote sends OK as HID consumer usage 0x0041
; (KEY_SELECT), which Windows ignores. We catch it via Raw Input and
; inject Enter. This is the Windows version of the Linux hwdb fix, and
; it needs no cursor and no mouse-mode toggling.
;
; BACK in arrow mode IS mapped by Windows (to Browser_Back), so it's
; handled by a normal hotkey further below. Only OK needs Raw Input.
OK_USAGE   := 0x0041
BACK_USAGE := 0x0000        ; leave 0 (Back handled by the hotkey below)

DllCall("RegisterRawInputDevices", "Ptr", MakeRID(), "UInt", 1, "UInt", 16)
OnMessage(0x00FF, OnRawInput)   ; WM_INPUT

; ---------- OK and BACK REMAPS (mouse mode) ----------
; If the remote is in mouse mode instead: OK = LButton, BACK = RButton.
; Remap those to Enter/Esc, but ONLY while a media app is in front, so
; your normal mouse still works on the desktop and in Settings.
#HotIf IsMediaApp()
*LButton::Send("{Enter}")
*RButton::Send("{Esc}")
#HotIf

; BACK button (arrow mode) -> Esc. Windows sees it as Browser_Back;
; this replaces the native "go back" so it can't page out of an app.
Browser_Back::Send("{Esc}")
; ----------------------------------------

GoHome() {
    global FlexLauncherPath, FlexExe

    ; Close the app currently on screen (unless it's the desktop/taskbar
    ; or Flex Launcher itself).
    if (hwnd := WinExist("A")) {
        cls  := WinGetClass("ahk_id " hwnd)
        proc := WinGetProcessName("ahk_id " hwnd)
        isShell := (cls = "Progman" || cls = "WorkerW" || cls = "Shell_TrayWnd")
        if (!isShell && proc != FlexExe)
            WinClose("ahk_id " hwnd)     ; graceful close (like Alt+F4)
    }

    ; Give the app a moment to shut down.
    Sleep 500

    ; Bring up Flex Launcher: focus it if already running, else launch it.
    if WinExist("ahk_exe " FlexExe) {
        WinActivate()
    } else if FileExist(FlexLauncherPath) {
        Run(FlexLauncherPath)
    } else {
        MsgBox(
            "Flex Launcher was not found at:`n`n" FlexLauncherPath "`n`n"
            "Edit the FlexLauncherPath line near the top of 2_MediaHome.ahk "
            "so it points to flex-launcher.exe.",
            "Setup needed", 0x30)
    }
}

; True when one of the media apps is the active window.
; Used to limit the OK/BACK mouse remaps to those apps only.
IsMediaApp() {
    static apps := ["flex-launcher.exe", "VacuumTube.exe"
        , "Plex HTPC.exe", "Plex.exe", "chrome.exe"]
    proc := ""
    try proc := WinGetProcessName("A")
    for a in apps
        if (proc = a)
            return true
    return false
}

; Builds the RAWINPUTDEVICE struct: Consumer Controls, delivered to this
; script even when another window is focused (RIDEV_INPUTSINK).
MakeRID() {
    static rid := Buffer(16, 0)
    NumPut("UShort", 0x0C, rid, 0)          ; UsagePage = Consumer
    NumPut("UShort", 0x01, rid, 2)          ; Usage = Consumer Control
    NumPut("UInt", 0x00000100, rid, 4)      ; RIDEV_INPUTSINK
    NumPut("Ptr", A_ScriptHwnd, rid, 8)
    return rid
}

; Handles WM_INPUT: reads the HID report and turns the remote's OK (and
; optionally Back) consumer usage into a real keypress.
OnRawInput(wParam, lParam, msg, hwnd) {
    global OK_USAGE, BACK_USAGE
    size := 0
    DllCall("GetRawInputData", "Ptr", lParam, "UInt", 0x10000003
        , "Ptr", 0, "UInt*", &size, "UInt", 24)
    if (!size)
        return
    buf := Buffer(size, 0)
    DllCall("GetRawInputData", "Ptr", lParam, "UInt", 0x10000003
        , "Ptr", buf, "UInt*", &size, "UInt", 24)
    if (NumGet(buf, 0, "UInt") != 2)        ; RIM_TYPEHID only
        return
    if (NumGet(buf, 24, "UInt") < 3)        ; report must be >= 3 bytes
        return
    ; report layout: [reportID][usage low][usage high]
    usage := NumGet(buf, 33, "UShort")      ; bytes 1-2, little-endian
    if (usage = OK_USAGE)
        Send("{Enter}")
    else if (BACK_USAGE && usage = BACK_USAGE)
        Send("{Esc}")
}

**Comment by serjepatoff** [comment]
Fixed on Linux and Windows, but what about macOS? What to do with defunct OK button there?

PS. M1 Mac Mini with 8GB RAM is an excellent Kodi + Emu Gaming box. It has no serious use cases in 2026 because of modern macOS and web RAM appetites, but excels at emulating game systems up to Nintendo Switch 1 and working as a very fast HTPC.
