### ISSUE TITLE
On Windows 7 (installed on the E: drive) : Kodi starts up with a black screen ....

### ISSUE THREAD

**Issue by unaRIpurpose** [xbmc/xbmc#21568]
[kodi.log](https://github.com/xbmc/xbmc/files/8926541/kodi.log)
[kodi.old.log](https://github.com/xbmc/xbmc/files/8926543/kodi.old.log)

### Describe the bug

Kodi starts up with a black screen and I am handicapped for any further interactions with the app on my Windows 7 PC  on which the OS resides in E: drive (rather than the default C:\ drive) ....

The Black screen begins as soon as I start the KODI app on my PC

## Expected Behavior

Kodi landing page should open (if only)

## Actual Behavior

Black Screen persists for eternity

### To Reproduce

1. Double Click on KODI app icon (thats it!)
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

BLACK SCREEN as in BLACK hole! Log files have been uploaded here : https://drive.google.com/drive/folders/1e8ahkVfzxsa6mIqgsEBeuuhXawaYuHGx?usp=sharing

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [. ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Matrix 19.4.0.0
[kodi_stacktrace-19.4 Git_20220302-e12e66e019-20220617-133539.txt](https://github.com/xbmc/xbmc/files/8926317/kodi_stacktrace-19.4.Git_20220302-e12e66e019-20220617-133539.txt)
[kodi_stacktrace-19.4 Git_20220302-e12e66e019-20220617-133613.txt](https://github.com/xbmc/xbmc/files/8926320/kodi_stacktrace-19.4.Git_20220302-e12e66e019-20220617-133613.txt)
[kodi_stacktrace-19.4 Git_20220302-e12e66e019-20220617-134336.txt](https://github.com/xbmc/xbmc/files/8926322/kodi_stacktrace-19.4.Git_20220302-e12e66e019-20220617-134336.txt)
[kodi_stacktrace-19.4 Git_20220302-e12e66e019-20220617-143348.txt](https://github.com/xbmc/xbmc/files/8926323/kodi_stacktrace-19.4.Git_20220302-e12e66e019-20220617-143348.txt)
[kodi_stacktrace-19.4 Git_20220302-e12e66e019-20220617-143406.txt](https://github.com/xbmc/xbmc/files/8926325/kodi_stacktrace-19.4.Git_20220302-e12e66e019-20220617-143406.txt)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Kodi log posted is not a debug log but normal log (debug level is not enabled).

As not all Windows 7 Kodi setups has black screen this is not a "bug" but support request/troubleshoot for now.

Please open a thread here --> https://forum.kodi.tv/forumdisplay.php?fid=59 and post debug log.

**Comment by unaRIpurpose** [comment]
Yes, I agree, the resolution has been reached after a simple reboot of the device ..... Aaal is Well! Thanks :+1:
