### ISSUE TITLE
Cross-compiling depend for WebOS: Mesa build error

### ISSUE THREAD

**Issue by IngwiePhoenix** [xbmc/xbmc#21567]
### Describe the bug
Here is a clear and concise description of what the problem is:

I am attempting to build Kodi for WebOS and since many of the required libraries are missing, I went to tools/depend and started with that first since it provides a convenient way to bootstrap all required dependencies. Unfortunately, whilst building Mesa, this error occured:

```
ingwie@bigboi:/opt/xbmc/tools/depends/target/mesa$ ninja -C arm-webos-linux-gnueabi-release/build
ninja: Entering directory `arm-webos-linux-gnueabi-release/build'
[3/877] Compiling C object src/util/libmesa_util.a.p/os_file.c.o
FAILED: src/util/libmesa_util.a.p/os_file.c.o
/opt/arm-webos-linux-gnueabi_sdk-buildroot/usr/bin/arm-webos-linux-gnueabi-gcc -Isrc/util/libmesa_util.a.p -Isrc/util -I../src/util -Iinclude -I../include -Isrc -I../src -Isrc/mapi -I../src/mapi -Isrc/mesa -I../src/mesa -I../src/gallium/include -Isrc/gallium/auxiliary -I../src/gallium/auxiliary -I/opt/kodi-deps/arm-webos-linux-gnueabi-release/include -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O3 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS '-DPACKAGE_VERSION="20.1.7"' '-DPACKAGE_BUGREPORT="https://gitlab.freedesktop.org/mesa/mesa/-/issues"' -DUSE_ELF_TLS -DENABLE_ST_OMX_BELLAGIO=0 -DENABLE_ST_OMX_TIZONIA=0 -DEGL_NO_X11 -DHAVE_DRM_PLATFORM -DENABLE_SHADER_CACHE -DHAVE___BUILTIN_BSWAP32 -DHAVE___BUILTIN_BSWAP64 -DHAVE___BUILTIN_CLZ -DHAVE___BUILTIN_CLZLL -DHAVE___BUILTIN_CTZ -DHAVE___BUILTIN_EXPECT -DHAVE___BUILTIN_FFS -DHAVE___BUILTIN_FFSLL -DHAVE___BUILTIN_POPCOUNT -DHAVE___BUILTIN_POPCOUNTLL -DHAVE___BUILTIN_UNREACHABLE -DHAVE_FUNC_ATTRIBUTE_CONST -DHAVE_FUNC_ATTRIBUTE_FLATTEN -DHAVE_FUNC_ATTRIBUTE_MALLOC -DHAVE_FUNC_ATTRIBUTE_PURE -DHAVE_FUNC_ATTRIBUTE_UNUSED -DHAVE_FUNC_ATTRIBUTE_WARN_UNUSED_RESULT -DHAVE_FUNC_ATTRIBUTE_WEAK -DHAVE_FUNC_ATTRIBUTE_FORMAT -DHAVE_FUNC_ATTRIBUTE_PACKED -DHAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL -DHAVE_FUNC_ATTRIBUTE_VISIBILITY -DHAVE_FUNC_ATTRIBUTE_ALIAS -DHAVE_FUNC_ATTRIBUTE_NORETURN -D_GNU_SOURCE -DUSE_GCC_ATOMIC_BUILTINS -DUSE_ARM_ASM -DMAJOR_IN_SYSMACROS -DHAVE_XLOCALE_H -DHAVE_LINUX_FUTEX_H -DHAVE_ENDIAN_H -DHAVE_DLFCN_H -DHAVE_EXECINFO_H -DHAVE_SYS_SHM_H -DHAVE_STRTOF -DHAVE_MKOSTEMP -DHAVE_RANDOM_R -DHAVE_FLOCK -DHAVE_STRTOK_R -DHAVE_PROGRAM_INVOCATION_NAME -DHAVE_POSIX_MEMALIGN -DHAVE_DIRENT_D_TYPE -DHAVE_STRTOD_L -DHAVE_DLADDR -DHAVE_DL_ITERATE_PHDR -DHAVE_ZLIB -DHAVE_PTHREAD -DHAVE_PTHREAD_SETAFFINITY -DHAVE_LIBDRM -DHAVE_WAYLAND_PLATFORM -DWL_HIDE_DEPRECATED -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=empty-body -Werror=incompatible-pointer-types -Werror=int-conversion -Wno-missing-field-initializers -Wno-format-truncation -fno-math-errno -fno-trapping-math -fno-common -Werror=format -Wformat-security -fPIC -DPIC -DNDEBUG=1 -Os -isystem /opt/kodi-deps/arm-webos-linux-gnueabi-release/include -fPIC -pthread -Werror=pointer-arith -Werror=vla -fvisibility=hidden -MD -MQ src/util/libmesa_util.a.p/os_file.c.o -MF src/util/libmesa_util.a.p/os_file.c.o.d -o src/util/libmesa_util.a.p/os_file.c.o -c ../src/util/os_file.c
../src/util/os_file.c: In function ‘os_same_file_description’:
../src/util/os_file.c:148:19: error: ‘SYS_kcmp’ undeclared (first use in this function)
  148 |    return syscall(SYS_kcmp, pid, pid, KCMP_FILE, fd1, fd2);
      |                   ^~~~~~~~
../src/util/os_file.c:148:19: note: each undeclared identifier is reported only once for each function it appears in
../src/util/os_file.c:149:1: error: control reaches end of non-void function [-Werror=return-type]
  149 | }
      | ^
cc1: some warnings being treated as errors
[28/877] Compiling C object src/util/format/libmesa_format.a.p/meson-generated_.._u_format_table.c.o
ninja: build stopped: subcommand failed.
```

I know this is probably an issue with the Mesa developers; but I wanted to make sure I was not overlooking something.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

A passing compile.

## Actual Behavior

As described above.

## Possible Fix

Maybe update the used Mesa source tree?

### To Reproduce

1. Install the toolchain: https://github.com/openlgtv/buildroot-nc4
2. Do NOT source the environment setup. It sets `CC` and others which interfere with the configure script.
3. Configure tools/depend like so: `./configure --with-toolchain=/opt/arm-webos-linux-gnueabi_sdk-buildroot --host=arm-webos-linux-gnueabi --target=arm-webos-linux-gnueabi --enable-gplv3 --with-rendersystem=gles --prefix=/opt/kodi-deps --disable-debug --with-target-ldflags="-lrt"`
3. Run `make`

### Debuglog

The debuglog can be found here:

Log provided above.

### Screenshots 
Here are some links or screenshots to help explain the problem:

None

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I used the toolchain verbatin with no other 3rd party packages installed or connected to it.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
  * Build: WSL2 Debian 11 via Windows 10
  * Host: WebOS 6.x on LG OLED C1 TV
 - Kodi version: Git describes it as: `legacy_drop_vs-19969-g53282f34e6`

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
I'll close this. Its not a platform/toolchain we support, the failure is in a dependency that we have no control over.

Feel free to open a thread on the forums, but you might be better talking to the mesa folks

**Comment by fuzzard** [comment]
I will also mention, the mesa version in tools/depends isnt really up to date. Its only used purely for CI testing on linux platforms, and is never intended for actual use, therefore it hardly ever gets updated.

**Comment by IngwiePhoenix** [comment]
Thank you for the feedback.

Although it's mainly for CI, it's pretty handy for "porting" to other platforms. If anyone has time, it'd be great if someone went and took a look at this and update some of the dependencies.

Have a nice day!

**Comment by IngwiePhoenix** [comment]
I tried to look through the configure/Makefiles but could not spot a way to just disable Mesa from the build. Have any idea?

**Comment by memerememe** [comment]
@IngwiePhoenix did you manage to build it for webos?
