### ISSUE TITLE
The disappearing picture addon

### ISSUE THREAD

**Issue by loubro** [xbmc/xbmc#21574]
### Describe the bug
Here is a clear and concise description of what the problem is:

I am using the Google Drive addon to access pictures. I wanted to use it with the Picture Slideshow Screensaver module as a source for the image folder. I tested and discovered that it disappears as an option if you reboot Kodi.  It stays invisible as the screen saver source option until its used to display pictures.

I did the process from a reboot and that was all I did

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect the Google Addon source option should stay available after it is installed. 

## Actual Behavior

If I reboot Kodi and try to find the Picture Addon option for a source for the Screensaver it is not there.

### To Reproduce

1. Download and create a new Kodi
2. Add the Google drive module and config with sample files
3. Use Google drive to show a slideshow of the pictures
4. Add the Picture Slideshow Screensaver
5. Go to the Pictures Slideshow Screensaver config screen
6. If you select the source to the Image Folder option and click the Browse button you will see the Picture Addon as an option.
7. Do not select anything - instead reboot Kodi
8. When Kodi starts up go to the Picture Screensaver Config select Image folder and click Browse the Picture Addon is not there.
9. Use the Google Drive to access pictures and run the slide show on them. Cancel.
10. Go to the Picture Screensaver Config select Image folder and click Browse and the Picture Addon option is now available.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ukazelerah

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
https://github.com/xbmc/xbmc/issues/21569#issuecomment-1158950568

**Comment by ronie** [comment]
Reopening, @loubro is reporting an issue with Kodi's File Browser. This isn't related to the addon.

Initially, after Kodi startup, the 'Picture addons' entry is missing in the File Browser:
![screenshot00000](https://user-images.githubusercontent.com/687265/174461356-8c12b2f9-24dd-4beb-98b0-ab7d1061cc8f.png)

But after navigating to the Pictures section in Kodi and reopening the File browser again, it is now present:
![screenshot00001](https://user-images.githubusercontent.com/687265/174461357-de22be2f-d3d7-4497-9b69-f58cc463970a.png)

**Comment by loubro** [comment]
When I tried to take a screen shot of the dialog with the "Picture add-ons" option visible. The option disappeared before my eyes, and I was able to repeat it. This was on an update Windows 10 Dell laptop.
