### ISSUE TITLE
[Bug] Option: Update official add-ons from "Any repositories" is not working.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [xbmc/xbmc#21572]
### Describe the bug
 Whenever i start kodi, addons such as Tmdb Helper, Skin Variables, Youtube, Composite are not automatically updating in there developer repositories.

- I set Update official add-ons to "Any Repositories"
- I set each addon to auto update
- I did a fresh build just incase

###  Addons that are not automatically updating
Tmdb Helper - Not updating in [Jurialmunkey's Repo](https://jurialmunkey.github.io/repository.jurialmunkey/repository.jurialmunkey-2.2.zip)
Skin Variables - Not updating in [Jurialmunkey's Repo](https://jurialmunkey.github.io/repository.jurialmunkey/repository.jurialmunkey-2.2.zip)
Youtube - Not updating in [Anxdpanac's Yotube Test Repo](https://panicked.xyz/repositories/matrix/repository.yt.testing_official-2.0.2+matrix.1.zip)
Composite - Not Updating in [Anxdpanac's Composite Development Repo](https://panicked.xyz/repositories/matrix/repository.composite_development-1.0.2+matrix.1.zip)

## Expected Behavior
The addons that i have installed should have automatically updated with the option "Any Repositories" enabled.

## Actual Behavior
The addons are not automatically updating for some odd reason even though i have the developer repositories installed that have addons with higher version numbers. 

## Possible Fix

Disabling or deleting the kodi official repo (Not a good fix) cause that's all i could think of. 

### To Reproduce

1. Do a fresh install of kodi and set the exact settings that i have in the Add-ons category 
![image](https://user-images.githubusercontent.com/62456796/174415141-19713df0-6621-4542-9cce-417c4313532a.png)
2. Download These addons from the Kodi Add-on repository
 - Tmdb Helper
 - Skin Variables
 - Youtube 
 - Composite 
3. Download those repositories i mentioned above and install each in kodi by zip file
4. Make sure each of those addons you have downloaded have auto update on
5. Restart Kodi
6. Notice that non of the addons are updating 
7. Go to one of those addons that didn't update and click version. 
8. Notice that the other version has a higher version number in which addons did not automatically update.

### Debuglog

[kodi.zip](https://github.com/xbmc/xbmc/files/8932764/kodi.zip)

- If you guys want me to update my log, i will do another test build. 

### Screenshots 
Here are some links or screenshots to help explain the problem:

Settings
![Settings](https://user-images.githubusercontent.com/62456796/174416496-4a19003f-3bdb-4fa3-b630-8cfb13954005.png)
Tmdb Helper
![Tmdb Helper](https://user-images.githubusercontent.com/62456796/174416443-f6b75c19-6458-4aca-91bd-413a45c15280.png)
Skin Varibles
![Skin Varibles](https://user-images.githubusercontent.com/62456796/174416445-597aa277-a982-4a98-a32c-9f20b0116375.png)
Youtube
![Youtube](https://user-images.githubusercontent.com/62456796/174416451-4e579846-ec59-4453-9720-1345c92f3e56.png)
Composite
![Composite](https://user-images.githubusercontent.com/62456796/174416454-df5f8547-ebd3-415d-8652-3637f554af27.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

 - This Bug affects me in many way cause i have to manually update the addons by going to version and clicking the updated version and i have a bunch of tv's for my family that needs updating.
 - Im trying to accomplish fixing this bug to save me a bunch of time so i would not have to manually update my tv's each time.
 - Back then on Kodi 18, this was never an issue until Kodi 19 came out. 

- I could not find any bug describing this except https://github.com/xbmc/xbmc/issues/19297

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [x] tvOS
 - [X] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

## Reason
- This bug is affected on all Operating systems due to how you guys setup Kodi Add-on repository
- The ones i checked are the Operating systems i used in the past.

## Versions
 - Operating system version/name: 10.0.22000 Build 22000/Microsoft Windows 11 Pro 
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Liquidrag** [comment]
Can confirm in OSX too.

**Comment by Goldenfreddy0703** [comment]
> Can confirm in OSX too.

Hey thank you so much for telling me, now im not the only one experience this bug. 😁

**Comment by Liquidrag** [comment]
> > Can confirm in OSX too.
> 
> Hey thank you so much for telling me, now im not the only one who experienced this bug. 😁

We are definitely not alone.

**Comment by howie-f** [comment]
it seems this is a long lasting bug.. hopefully fixed with 21581.

**Comment by Goldenfreddy0703** [comment]
> it seems this is a long lasting bug.. hopefully fixed with 21581.

Hey thank you for telling me, I tried looking for similar bugs like this but did not look in PR. Thank you so much, let's hope it gets fixed with 21581.

**Comment by howie-f** [comment]
the pr was just opened because of your bug report :) .. i'll merge it now so the issue should be fixed in the next Nexus nightly.
backport to Matrix is also on the way, but i'm not sure if it will make it into 19.5 because the release is imminent.
Please let us know how it goes with Nexus

**Comment by Goldenfreddy0703** [comment]
Hey thank you so much and I will. You guys are the best and I can't wait to try it. Thank you

**Comment by Goldenfreddy0703** [comment]
Hey so i just gave it a try in Nexus and it worked perfectly and im really glad you guys have fixed it in Nexus. 
Thank you guys so much and you guys are the best. I hope this could be Merged in the 19.5 milestone so i could use the latest v19 nightly build soon. 

Again, Thank you so much and you guys are the best.

**Comment by pshewale-dev** [comment]
Yes, i am facing too.any workaround??

**Comment by Goldenfreddy0703** [comment]
> Yes, i am facing too.any workaround??

Hey so this was recently fixed like last year. What version of Kodi are you using and what device?

**Comment by pshewale-dev** [comment]
Kodi v20.1 on raspberry pi osmc

**Comment by Goldenfreddy0703** [comment]
Its possible that is could be an osmc issue sense i heard osmc is behind on updates and stuff. I don't usually like them as much and i just use libreelec sense its more stable then osmc. My best bet is to either report this to osmc forms or maybe wait for an update or switching to Lebreelec maybe. Im not too sure but hopefully this helps.

**Comment by samnazarko** [comment]
OSMC is currently shipping 20.1 as stable. 20.2 was recently released by Team Kodi and is available in our testing repository. It will be officially released as a stable update on Sunday to all users.

We are not aware of this issue - with a forum post with some logs, we should be able to provide some insight and resolve this promptly for you.

Cheers

Sam

**Comment by howie-f** [comment]
@samnazarko maybe osmc need to adjust/add their official repositories here
https://github.com/xbmc/xbmc/blob/29926b4febd0804c67bdc16b76ce192c4edbf7b7/version.txt#L14C5-L14C5

delimited by `,`

**Comment by samnazarko** [comment]
Indeed. We did this on v19. Looks like it got missed on v20 rebase.

**Comment by Goldenfreddy0703** [comment]
Surprised to see that this was a long lasting issue on osmc's part during v20. I would have pointed this out to you guys if i was still using osmc but ever sense the new ui change. It's been not so good from there. Osmc is great but raspberry pi 4 support has been kinda buggy in the past. Anyway, glad you guys found the problem and hopefully you guys will have a fix in your next update. 

Thanks.

**Comment by samnazarko** [comment]
We only had a few reports. We did have a testing phase of v20 for a *long* time, but this didn't come up during that testing.

>Osmc is great but raspberry pi 4 support has been kinda buggy in the past.

We use the exact same kernel and Kodi sources as LibreELEC (from Pi upstream), so there should be minimal difference, however if LibreELEC works well for you, then great.

**Comment by Goldenfreddy0703** [comment]
> We only had a few reports. We did have a testing phase of v20 for a _long_ time, but this didn't come up during that testing.

Makes sense sense most people did not find this as a bug. Luckily i did in the past from doing some extensive testing

> We use the exact same kernel and Kodi sources as LibreELEC (from Pi upstream), so there should be minimal difference, however if LibreELEC works well for you, then great.

Oh then probably just on my end then, When osmc was first released on the pi 4 it was alot buggy back then. Hopefully most of those updates fixed most of those bugs. 

Anyway thanks for pointing that out and hopefully this update on Sunday will resolve this issue for you guys.
