### ISSUE TITLE
Kodi:Windows10: Addon YeloTV : It works only the first  time after installation kodi

### ISSUE THREAD

**Issue by pborreke** [xbmc/xbmc#21582]
## Bug report
2022-06-19 17:29:34.859 T:13088   ERROR <general>: AddOnLog: inputstream.adaptive: License update not successful (no keys)
2022-06-19 17:29:34.983 T:13088   ERROR <general>: AddOnLog: inputstream.adaptive: Initialize failed (SingleSampleDecrypter)
2022-06-19 17:29:34.989 T:13088   ERROR <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.yelo/play/id/2behd]
### Describe the bug
I've installed Kodi version 19.4, installed addon YeloPlay 1.0.2.
I've selected video addon YeloPlay via the navigation of kodi; and then selected TV channel VTMhd, this worked fine, no problem.
I've closed the channel and then selected TV channel 2behd, I got the message on the screen "Playback failed", I retried with VTMhd and got the same error. It does not work again. This happened in a moment of minutes between the first time (when it worked) and the other tries (when it did not work anymore).

I had the same behavior with Kodi version 19.3.

## Expected Behavior
It worked just after the installation, just one time, so it should work also for the next times. 
I did not any installation or configuration between.

## Actual Behavior
Kodi gave an error on his log : "License update not successful" and "Initialize failed" and "error opening plugin"
Closing and restarting Kodi did not solved the issue.
Only a full de-install and re-install of kodi solved the issue once.

## Possible Fix
Maybe there is a difference in the code between the first time and the next times? Caching? Temp-files?

### To Reproduce
1. select add on Yelo Play
2. select channel VTMhd
3. close the channel
4. select again channel VTMhd or another

### Debuglog
see attached files below.

### Screenshots
![image](https://user-images.githubusercontent.com/37243157/174490528-b73d5be8-0c0f-4cc3-b679-563f82793a10.png)

## Additional context or screenshots (if appropriate)
no remarks

### Your Environment
Used Operating system:
 - [ ] Windows

 - Operating system version/name: 
 - ![image](https://user-images.githubusercontent.com/37243157/174490653-2a010f37-304e-48d7-b269-d472d87fd53b.png)

 - Kodi version: 19.3 and 19.2

Thanks for your help, if you need more info don't hesitate to contact me. If I can help, let me know.

[kodi.log_license_update.txt](https://github.com/xbmc/xbmc/files/8935916/kodi.log_license_update.txt)

**Comment by enen92** [comment]
Issue is out of the scope of this repo, bring this to the addon developer or inputstream.adaptive.
