### ISSUE TITLE
Kodi 19.4 shutter with PAplayer due huge RAM allocation/freeing all the time

### ISSUE THREAD

**Issue by bitstreamout** [xbmc/xbmc#21603]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm hearing the radio station JukeBox Radio 2 https://maggie.torontocast.com:8076/flac with the help of the PVR IPTC simple client and experience after a while stutter in the audio.
After checking the memory consumption I've seen that the memory consumption has increased a lot and the stutter happens if kodi becomes a swapping process.  Compare with https://forum.kodi.tv/showthread.php?tid=368535&pid=3100690#pid3100690
I had also tried to use memory buffer instead of the default stream file but this makes no difference on the result.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No memory leak and no stutter in the audio stream of the flac radio station.

## Actual Behavior

Kodi is leaking memory which results after 15 minutes into stutter on the FLAC radio channel

## Possible Fix

Replace ffio_ensure_seekback() from current ffmpeg source tree for Matrix with a version which avoids allocation/freeing huge memory areas all the time with ogg based streams!
https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/HEAD:/libavformat/aviobuf.c#l1055

### To Reproduce

1. Play the Radio channel  https://maggie.torontocast.com:8076/flac for more than 20 minutes

```
root@dataslide:~# free -s 20 -w
              total        used        free      shared     buffers       cache   available
Mem:        1925252      819404      150744      386312       33936      921168      539620
Swap:      25060920      838916    24222004
[...]
```

2. Compare memory consumption with `top` or `free -s 20 -w` 
3. Listen upto the stutter happens.

```
[...]
              total        used        free      shared     buffers       cache   available
Mem:        1925252     1181240      260296      397144        1292      482424      219800
Swap:      25060920      838604    24222316
```

### Debuglog

The debuglog can be found here: https://paste.kodi.tv//edilikufim

### Screenshots 
Here are some links or screenshots to help explain the problem:

No screen shots (beside the `visualization.spectrum` addon disappears due memory shortage)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I created an advancedsettings.xml and switched over to fully virtual memory buffers. Also I've added some logging/debug options

```
<advancedsettings version="1.0">
        <hosts>
                <entry name="dataslide">192.168.0.22</entry>
        </hosts>
        <cache>
                <memorysize>139460608</memorysize>
                <buffermode>1</buffermode>
                <readfactor>20.0</readfactor>
        </cache>
        <loglevel hide="true">1</loglevel>
        <debug>
                <extralogging>true</extralogging>
                <setextraloglevel>2048,32768,262144,1048576</setextraloglevel>
        </debug>
</advancedsettings>
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04.6 LTS on QNAP
 ```
root@dataslide:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
root@dataslide:~# exit
[admin@dataslide Kodi19L]# uname -a
Linux dataslide 5.10.60-qnap #1 SMP Tue May 31 11:01:17 CST 2022 x86_64 GNU/Linux
```
 - Kodi version: Kodi (19.4 (19.4.0) Git:20220317-nogitfound). Platform: Linux x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by bitstreamout** [comment]
Just run a test on an OpenSUSE Tumbleweed x86_64 with a plain installed kodi 19.4 and the command lines

  `kodi https://maggie.torontocast.com:8076/flac`

and in an other terminal

  `top -d 20 | tee -a /tmp/kodi.log`

and I see that the kodi process is eating memory:
```
12581 werner    20   0 3506332 242684 121880 S 25.00 3.000   0:49.85 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3506332 244732 121880 S 21.72 3.026   0:54.20 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3506332 246780 121880 R 21.72 3.051   0:58.55 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3506332 248828 121880 R 22.07 3.076   1:02.97 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 254468 121880 S 22.60 3.146   1:07.50 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 257768 121880 S 5.389 3.187   1:08.58 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 260824 121880 S 3.197 3.224   1:09.22 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 262872 121880 S 3.345 3.250   1:09.89 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 266968 121880 S 3.347 3.300   1:10.56 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 269016 121880 S 3.397 3.326   1:11.24 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 271064 121880 S 3.343 3.351   1:11.91 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 273112 121880 S 3.347 3.376   1:12.58 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 275160 121880 S 3.194 3.402   1:13.22 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 281280 121880 S 3.345 3.477   1:13.89 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 283328 121880 S 3.297 3.503   1:14.55 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 285432 121880 S 3.395 3.529   1:15.23 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 289528 121880 S 3.393 3.579   1:15.91 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 295636 121880 S 3.195 3.655   1:16.55 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 297684 121880 S 3.194 3.680   1:17.19 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 299732 121880 S 3.144 3.705   1:17.82 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 301780 121880 S 3.248 3.731   1:18.47 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 303828 121880 S 3.345 3.756   1:19.14 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 307924 121880 S 3.293 3.807   1:19.80 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 309972 121880 S 3.295 3.832   1:20.46 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 312112 121880 S 3.343 3.859   1:21.13 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 314160 121880 S 3.247 3.884   1:21.78 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac                                                
12581 werner    20   0 3507848 316208 121880 S 3.094 3.909   1:22.40 /usr/lib64/kodi/kodi.bin https://maggie.torontocast.com:8076/flac
```

**Comment by bitstreamout** [comment]
The leak is there even without any visualizer and even on `https://maggie.torontocast.com:8076/mp3`

**Comment by bitstreamout** [comment]
I give up ... SMPlayer and Kodi Leia (after using VideoPlayer for Radio Stations) do work whereas Matrix does not.  And no one is interested.  Compare with https://forum.kodi.tv/showthread.php?tid=368535

**Comment by bitstreamout** [comment]
Replace ffio_ensure_seekback() from current ffmpeg source tree for Matrix with a version which avoids allocation/freeing huge memory areas all the time with ogg based streams!
https://git.ffmpeg.org/gitweb/ffmpeg.git...uf.c#l1055

**Comment by bitstreamout** [comment]
Here an allocation of 168161280 bytes caused by ffio_ensure_seekback() of ffmpeg 4.3.1 Matrix

```
(gdb) bt
#0  0x00007f7a3151b6d0 in __GI___mmap64 (addr=addr@entry=0x0, len=len@entry=168161280, prot=prot@entry=3, flags=flags@entry=34, fd=fd@entry=-1, offset=offset@entry=0)
    at ../sysdeps/unix/sysv/linux/mmap64.c:51
#1  0x00007f7a3149430f in sysmalloc (nb=nb@entry=168159584, av=av@entry=0x7f7998000020) at malloc.c:2329
#2  0x00007f7a31495060 in _int_malloc (av=av@entry=0x7f7998000020, bytes=bytes@entry=168159568) at malloc.c:4135
#3  0x00007f7a3149555b in _int_memalign (av=0x7f7998000020, alignment=64, bytes=<optimized out>) at malloc.c:4683
#4  0x00007f7a3149afda in _mid_memalign (address=<optimized out>, bytes=168159462, alignment=64) at malloc.c:3324
#5  0x00007f7a3149afda in __posix_memalign (memptr=memptr@entry=0x7f79b57f9090, alignment=alignment@entry=64, size=size@entry=168159462) at malloc.c:5361
#6  0x000055ebc5ec1463 in av_malloc (size=size@entry=168159462) at src/libavutil/mem.c:86
#7  0x000055ebc53e1fdb in ffio_ensure_seekback (s=s@entry=0x7f79980ea3c0, buf_size=168159462, buf_size@entry=65307) at src/libavformat/aviobuf.c:996
#8  0x000055ebc54dd7e5 in ogg_read_page (s=s@entry=0x7f79980e9d40, sid=sid@entry=0x7f79b57f92fc, probing=probing@entry=0) at src/libavformat/oggdec.c:367
```

This can be seen with

```
(gdb) down
#8  0x000055ebc54dd7e5 in ogg_read_page (s=s@entry=0x7f79980e9d40, sid=sid@entry=0x7f79b57f92fc, probing=probing@entry=0) at src/libavformat/oggdec.c:367
367         ffio_ensure_seekback(bc, MAX_PAGE_SIZE);
(gdb) print bc->buffer_size
$6 = 168115605
```

and 

```
int ffio_ensure_seekback(AVIOContext *s, int64_t buf_size)
{
    uint8_t *buffer;
    int max_buffer_size = s->max_packet_size ?
                          s->max_packet_size : IO_BUFFER_SIZE;
    int filled = s->buf_end - s->buffer;
    ptrdiff_t checksum_ptr_offset = s->checksum_ptr ? s->checksum_ptr - s->buffer : -1;

    buf_size += s->buf_ptr - s->buffer + max_buffer_size;  // <<< IMHO this is a BUG

    if (buf_size < filled || s->seekable || !s->read_packet)
        return 0;
    av_assert0(!s->write_flag);

    buffer = av_malloc(buf_size);
    if (!buffer)
        return AVERROR(ENOMEM);

    memcpy(buffer, s->buffer, filled);
    av_free(s->buffer);
    s->buf_ptr = buffer + (s->buf_ptr - s->buffer);
    s->buf_end = buffer + (s->buf_end - s->buffer);
    s->buffer = buffer;
    s->buffer_size = buf_size;
    if (checksum_ptr_offset >= 0)
        s->checksum_ptr = s->buffer + checksum_ptr_offset;
    return 0;
}
```

instead of using the buffer with memmove() and memcopy on the already huge buffer a new is allocated and the old is freed. And buffer size getting larger and larger as well.

**Comment by bitstreamout** [comment]
Simply changing ffio_ensure_seekback() does not work, maybe a switch to ffmpeg 4.4.2 would help out

**Comment by bitstreamout** [comment]
I'm now using Kodi Matrix build with ffmpeg 4.4.2 for an Ubuntu HDStation Container and it works absolute flawless. Kodi stays now exactyl at 8.8% memory playing https://maggie.torontocast.com:8076/flac

**Comment by fritsch** [comment]
Nice find. Should be this one: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20200915113525.30806-1-onemda@gmail.com/ but need to make sure that the referenced commit to workaround realloc failing is also picked.

That's a good candidate for our internal matrix ffmpeg. Keep in mind though, that distributions use their own ffmpeg in a lower versions won't be fixed as they bypass our internal ffmpeg. I will try to find some time over the weekend to pick the relevant fix.

**Comment by bitstreamout** [comment]
IMHO there are two methods for such buffering to avoid bashing the kernel's/glibc RAM logistics.  One is the elegant method with memmove and memcopy to cycle on one static memory buffer array ... or using two smaller static buffer arrays, one for input and the other for output, then flip the access addresses of the two buffer arrays.  The last approach avoids memmove and this I had used a long time ago for an ac3/dts plugin of vdr https://sourceforge.net/projects/bitstreamout/

**Comment by fritsch** [comment]
If it's caused by fragmentation alone (leave alone that it's expensive to constantly malloc new stuff), jemalloc also works great for such scenarios, even without recompiling and using LD_PRELOAD

**Comment by bitstreamout** [comment]
The broken calculation of the buffer size remains even with jemalloc ... even if jemalloc conceals bad programming ;)

**Comment by fritsch** [comment]
Does this (quite large) backport work for you?

**Comment by fritsch** [comment]
The good thing btw. it should work with kodi nexus out of the box, as the upcoming release is using ffmpeg 4.4 by default - so not sure at this point if a backport is still feasible.

**Comment by wsnipex** [comment]
we'll be doing more v19 point releases, so this would be feasible for Matrix

**Comment by fritsch** [comment]
I am a bit afraid of regressions, but all these changes only touched a single file with header, so I am confident.

**Comment by fritsch** [comment]
Ping - any news here? Worth to continue with backporting?

**Comment by bitstreamout** [comment]
I'm currently bussy with other work. That is it is on my todo list.  Btw. I face an other issue ... a long running kodi process seems to leak threads,  That is every day there are some threads more

**Comment by bitstreamout** [comment]
OK ... works flaeless over 6 hours know ... only the rss has increased a bit but last 4 hours it is fluctuating around a stable value.
As monitor I've used an alias called ktop which in fact is

```
watch -n 2 ps -C kodi.bin -C kodi-x11 -Lo pid,lwp,pcpu,pmem,vsz,rss:8,drs:8,size:7,nice,stat:3,cls,lstart,time,comm --sort=lstart
```

**Comment by fritsch** [comment]
Nice. Thanks for the feedback. It's on the active team now to ack my PR.

**Comment by bitstreamout** [comment]
Question: Is there something like a Q(uality) A(ssurance) queue which runs some automatic tasks/jobs to see if older bugs happen again?

**Comment by fritsch** [comment]
The political answer: there are a large amount of unit tests.
Real answer: the test suite is not meant as let's say integration test. We actually rely on reports like yours.

**Comment by bitstreamout** [comment]
Looks likew this is closed with Nexus?

**Comment by bitstreamout** [comment]
Telling
