### ISSUE TITLE
Kodi window loses title bar after resizing due to incorrect position

### ISSUE THREAD

**Issue by adras** [xbmc/xbmc#21610]
### Describe the bug
From time to time I noticed that the kodi window get's incorrectly placed after resizing it from full screen to window mode. The window is moved to far to the top. Actually, the top of the window, the title bar is moved out of the screen area.

## Expected Behavior
After switching from full screen to window mode the title bar should still be visible. Preferably, the window should be placed at it's old position.

## Actual Behavior
After switching from full screen to window mode, the kodi window is no longer at it's original position. Instead it's moved to the top left of the screen, with the title bar being moved outside of the visible screen area.

### To Reproduce
Scenario A:
1. Watch a movie in fullscreen in kodi
2. While movie is playing, hibernate PC
3. After resuming from hibernation the kodi window is broken

Scenario B:
1. Open e.g. Firefox
2. Open Kodi, Play a movie in fullscreen
3. Hit windows key, click on Firefox in the taskbar to show it
4. Kodi window flickers, firefox doesn't appear
5. Click into Kodi window
6. Hit alt+enter to go back to window mode -> Kodi position incorrect as described above

### Debuglog
The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/8993246/kodi.log)

### Screenshots 
![grafik](https://user-images.githubusercontent.com/226144/175975890-cfcb9081-ab7e-421e-b540-73cd932f3e51.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
![grafik](https://user-images.githubusercontent.com/226144/175976218-3e78fdd7-f7b7-4415-a57f-1b5ad046e97b.png)

 - Kodi version:
![grafik](https://user-images.githubusercontent.com/226144/175976133-c97df3e6-6563-4e46-8843-a99cdadfd689.png)

**Comment by CastagnaIT** [comment]
just to add a note, no need to play a movie,
at least on Kodi 20 you can reply same problem by opening kodi in fullscreen
and then press ALT+ENTER to change in windowed mode and the Kodi window go offscreen

**Comment by thexai** [comment]
This code overwrites previous saved window position with coordinates that correspond window in full screen and no title bar visible top-left (0, 0):

https://github.com/xbmc/xbmc/blob/b9f72b53d5e89504bc00c7d24d09b3740f85ecf8/xbmc/windowing/windows/WinSystemWin32.cpp#L486-L496

Removing this if block fixes the issue and doesn't seem to be necessary because the previous position of the window is still saved anyway. Still this code is supposed to be there for some reason... 🙄

**Comment by CastagnaIT** [comment]
that code has been added 10y ago i think could to be revisited

> Not simple ALT+ENTER

to me the problem happens always with ALT+ENTER no need do nothing else,
maybe because i run kodi as portable mode

**Comment by CastagnaIT** [comment]
Ah forgot place
```
<window><!--4/3-->
	<width>1280</width>
	<height>720</height>
</window>
```

this on advanced setting and make start kodi windowed, after that switch
in this way should be more easy
