### ISSUE TITLE
PR-21387 breaks grouplist position when using conditional fade animations

### ISSUE THREAD

**Issue by jurialmunkey** [xbmc/xbmc#21615]
### Describe the bug
Here is a clear and concise description of what the problem is:

The PR https://github.com/xbmc/xbmc/pull/21387 breaks conditional fade animations because it sets visibility to false. 

This negatively impacts grouplist positioning because it is no longer possible to use a conditional fade to make an element transparent without changing its visibility.

This has two major implications for skins

1. The element no longer occupies space in the grouplist and the grouplist rubberbands and contracts to fill the space
2. When a list container visibility is set to false it no longer updates. If a skin uses a conditional fade to hide a container when `Container(ID).IsUpdating | Integer.IsEqual(Container(ID).NumItems,0)` and display a busy spinner instead, then the container will never update because it is never "visible" due to the fade animation.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should be possible to use a conditional fade animation such as below to make an element transparent on screen but still have the element be considered "visible" so that it continues to update and occupies space in the grouplist.

```
<animation effect="fade" start="100" end="0" condition="true">Conditonal</animation>
```

Only elements with visibility explicitly set to false should no longer occupy the space defined and no longer update.

## Actual Behavior

When using a conditional fade element the visibility is set to false, so the element no longer occupies space in the grouplist. This causes the grouplist to rubberband and contract rather than retaining its spacing. It also causes the container to never update.

## Possible Fix

Revert 21387 because opacity should not define element visibility in terms of spacing or updating. Controls are often used as spacers and can have 0% opacity but still need to be "visible" in terms of spacing and updating.

### To Reproduce
Apply this diff to Estuary (I'm using inprogress tvshows widget as the example so you might need to change the fadecondition System.IDleTime param to a different widget if you don't have in-progress shows) and then wait 2 seconds for IdleTime to kick in

```diff
diff --git a/xml/Home.xml b/xml/Home.xml
index 4192e93..8b8fde2 100644
--- a/xml/Home.xml
+++ b/xml/Home.xml
@@ -131,6 +131,7 @@
 							<param name="widget_header" value="$LOCALIZE[626]"/>
 							<param name="widget_target" value="videos"/>
 							<param name="list_id" value="6100"/>
+							<param name="fadecondition">System.IdleTime(2)</param>
 						</include>
 						<include content="WidgetListEpisodes" condition="Library.HasContent(tvshows)">
 							<param name="content_path" value="special://skin/playlists/recent_unwatched_episodes.xsp"/>
diff --git a/xml/Includes_Home.xml b/xml/Includes_Home.xml
index c420530..f6e8383 100644
--- a/xml/Includes_Home.xml
+++ b/xml/Includes_Home.xml
@@ -26,6 +26,7 @@
 		</definition>
 	</include>
 	<include name="WidgetListPoster">
+		<param name="fadecondition">false</param>
 		<definition>
 			<include content="CategoryLabel">
 				<param name="label">$PARAM[widget_header]</param>
@@ -39,6 +40,7 @@
 				<left>0</left>
 				<top>115</top>
 				<visible>Integer.IsGreater(Container($PARAM[list_id]).NumItems,0) | Container($PARAM[list_id]).IsUpdating</visible>
+				<animation effect="fade" start="100" end="0" time="1000" condition="$PARAM[fadecondition]">Conditional</animation>
 				<right>0</right>
 				<height>503</height>
 				<include content="WidgetListCommon">

```

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/9002263/kodi.log)

Log not really relevant. Screenshots below and diff will demonstrate the issue.

### Screenshots 
Here are some links or screenshots to help explain the problem:

Here is what happens when the fade animation kicks in. The list loses its position and the other elements contract around it. The list never reloads.
![Honeyview_screenshot00135](https://user-images.githubusercontent.com/4618719/176212961-caa36a0b-10cf-4306-b1f3-6ab04bb9da65.jpg)

What should happen is the element retains its "visible" state but can no longer be seen. I've used 10% opacity to demonstrate but in actual use it would be 0% and not rendered but still occupying this space.

![Honeyview_screenshot00136](https://user-images.githubusercontent.com/4618719/176213255-8d4fa472-8d9d-424b-a674-78dfb2cf6c9f.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Nexus Nightly (anything from 7th June onwards).

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
Yeah, we are gonna revert it. In the future, the 1% rule will only be applied to the actual rendering + dirty regions.

**Comment by roidy** [comment]
> Yeah, we are gonna revert it. In the future, the 1% rule will only be applied to the actual rendering + dirty regions.

Did this ever get reverted. Latest Nexus nightly's still have this issue and the fix  https://github.com/xbmc/xbmc/pull/21645 seems to be in limbo, nothings happening with it.

**Comment by enen92** [comment]
@sarbes has been a bit MIA but I guess he'll adjust the last pending requests when he find time. And the fix will surely make it into v20.

**Comment by roidy** [comment]
> @sarbes has been a bit MIA but I guess he'll adjust the last pending requests when he find time. And the fix will surely make it into v20.

I completely understand people have lives and other commitments and occasionally go MIA :) But shouldn't the original PR be reverted until the fix is ready? The current nightly's are unusable with a lot of skins.
