### ISSUE TITLE
Release of pvr.teleboy missing in Ubuntu PPA

### ISSUE THREAD

**Issue by rbuehlma** [xbmc/xbmc#21632]
Yesterday I created a new release (19.8.11) of pvr.teleboy:

https://github.com/rbuehlma/pvr.teleboy/actions/runs/2599512798

Unfortunatly, this did no create the release in the Ubuntu PPA.

Could you check where it got stuck?

Thank you

**Comment by fuzzard** [comment]
Jenkins had to move to github app authentication a couple months back as the old authentication method was disabled by github. This involved moving to the use of app authentication for any repos that would be used by jenkins. Any repos in orgs we control have been done, but any 3rd party owned repos havent been.

Im trying to work out what access we need to enable it. At the moment it looks like a team kodi member will have to be provided with permissions on your repo to create/generate a github app token.
that parts all fine, but im just trying to workout what access is required into the xbmc org to then install said app token.

**Comment by flubshi** [comment]
Any news here? I think it`s the same reason why [pvr.waipu build fails](https://jenkins.kodi.tv/job/flubshi/job/pvr.waipu/job/Nexus/). @fuzzard how can we support you fixing this? Do you need access to the github repos?

**Comment by ksooo** [comment]
@wsnipex something you can help with?

**Comment by flubshi** [comment]
For pvr.waipu it is fixed by adding Kodi Jenkins as GitHub application.

**Comment by rbuehlma** [comment]
I found this guide here: https://kodi.wiki/view/Jenkins#Configure_Jenkins_.26_Github_Integration but since I'm not part of the Kodi Team, I probably cannot install this GitHub app. Can someone from Kodi do this for me? I can provide the required permissions on the pvr.teleboy and pvr.zattoo project.

**Comment by rbuehlma** [comment]
@ksooo do you know you could help here?

**Comment by rainman74** [comment]
> @ksooo do you know you could help here?

@ksooo Here in Germany, the Zattoo plugin is the most important PVR plugin. It would be really great if this would work again soon, as one is now forced to use the corrosive Zattoo app, as the Kodi plugin, although already adapted to the new API by @rbuehlma, is not compiled with the binaries at the moment.

**Comment by fuzzard** [comment]
Github Kodi app needs to be installed on your repo. As you have multiple addons, make sure the app has access to all of them when you install it.

Link for it is on my post on forums

https://forum.kodi.tv/showthread.php?tid=198833&pid=3112499#pid3112499

Once its installed, let me know and i'll get the backend side of things done.

**Comment by rbuehlma** [comment]
hi @fuzzard thanks your your help. the app is now installed and has access to pvr.zattoo und pvr.teleboy.

**Comment by ksooo** [comment]
@fuzzard still does not work. As far as I know our Jenkins admins also need to do something?

**Comment by fuzzard** [comment]
Backlog is running now.

No idea if these jobs will go to PPA, but all the platforms that go to mirrors will finish. @wsnipex about PPA?

**Comment by rbuehlma** [comment]
The PPA for pvr.teleboy has now received the new release:
https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa/+packages?field.name_filter=teleboy&field.status_filter=&field.series_filter=

pvr.zattoo already has the current version. From my point of view, this ticket has been resolved and I will close it.

Thanks for your help!
