### ISSUE TITLE
vfs.rar is not working on nexus and not being maintained

### ISSUE THREAD

**Issue by kraaa** [xbmc/xbmc#21638]
### Describe the bug
Here is a clear and concise description of what the problem is:

vfs.rar is outdated can't be installed on v20 alpha. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Being able to download the module from Kodi official repo.
I expect something basic as filehandling to be working and supported on alpha releases.
As vfs.rar is not being maintained and can't be used me and other users who store files in rar can't use v20 alpha and bug test. 

## Actual Behavior

It's not on Kodi official repo.

## Possible Fix

vfs.archive is being updated and can be installed, maybe include handling of rar files to that?

### To Reproduce

1. Go to kodi repo on nexus
2. Find nothing
3. Quit

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 21H2
 - Kodi version: kodi-20.0-Nexus_alpha1-x64 and KodiSetup-20220702-074bcbf0-master-x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
It looks like it's in the repo to me. Maybe a bad mirror?
```
 curl -L https://mirrors.kodi.tv/addons/nexus/addons.xml | xmllint --format - | grep 'vfs.rar+windows'
      <path>vfs.rar+windows-x86_64/vfs.rar-20.1.0.zip</path>
      <path>vfs.rar+windows-i686/vfs.rar-20.1.0.zip</path>
```
It looks like I'm being forwarded to
```
< location: https://ftp.halifax.rwth-aachen.de/xbmc/addons/nexus/addons.xml
```

Did you try force refreshing the kodi repo?
