### ISSUE TITLE
Video default select action options

### ISSUE THREAD

**Issue by skiTzoCogniTionz** [xbmc/xbmc#21658]
## Roadmap or todo item
**Detailed Description**

It would be great if the video default select action could be applied to "movies" or "TV shows" independently. I would like to be able to set the default select action to "show info" for movies, but keep the default select action to "play" for TV shows. 

### Context

I enjoy having the info for a movie pop up when selecting it instead of needing to bring up the context menu and choose info, especially with skins like jurialmonkey's Arctic Horizon, which integrates tmdbhelper. I like having the info diolague pop up with the option to play, watch trailer or view extended info.  It's a really nice feature for movies, but it does not work that great with TV shows, because having the default select action set to show info creates a bunch of extra steps when browsing and playing TV show episodes. 

### Possible Implementation

I would imagine you could possibly implement a branching or switch statement to check the default select action setting, as well as video type ("movie" or "TV show") and call a function depending on the default setting and setting value. 

i.e.

if (type == Movie && movie.selectAction == "show-info")
    {
    video.showInfo();
    }

Sorry, I am quite a noob with programming and that code is probably laughable, but that is my attempt to the best of my ability 
to explain what kind of functionality I am looking for. Thank you for your time and consideration, and most definitely all the hard work you guys have put in over the years. 

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by lrusak** [comment]
Please make feature requests in the forum https://forum.kodi.tv/
