### ISSUE TITLE
[cmake][x11] kodi-xrandr is not being built with the kodi target

### ISSUE THREAD

**Issue by enen92** [xbmc/xbmc#21651]
### Describe the bug

Configuring and building the cmake `kodi` target for x11 does not automatically includes building kodi-xrandr. However, kodi on x11 strongly depends on the presence of `kodi-xrandr` binary in the buildfolder (`KODI_HOME`) for basic functionality. See:

https://github.com/xbmc/xbmc/blob/6915ae7631a85cc2d78e60248ce19adb5f002ea3/xbmc/windowing/X11/XRandR.cpp#L67-L72

https://github.com/xbmc/xbmc/blob/6915ae7631a85cc2d78e60248ce19adb5f002ea3/xbmc/windowing/X11/XRandR.cpp#L158-L163

I am not sure if this was supposed to happen here:

https://github.com/xbmc/xbmc/blob/ac0d763278133f46af8913e0f67f5b0ae9879e18/cmake/scripts/linux/ExtraTargets.cmake#L1-L7

But for some reason the kodi-xrandr binary is not being built for me

Build log:
[buildlog.txt](https://github.com/xbmc/xbmc/files/9057107/buildlog.txt)

**Comment by wsnipex** [comment]
> [proc] Executing command: /usr/bin/cmake --build /home/arch/Github/xbmc/build --config Debug --target kodi --

you specifically build only the kodi(.bin) target, but not kodi-x11

**Comment by enen92** [comment]
Thanks for the help wsnipex, this was actually an issue from my side in vscode :+1:
