### ISSUE TITLE
Segfault/EGL Error on startup

### ISSUE THREAD

**Issue by ACH1980** [xbmc/xbmc#21668]
### Describe the bug
Here is a clear and concise description of what the problem is:
Kodi fails to start with an EGL Error/Segfault

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Kodi starting

## Actual Behavior
There comes a short blackscreen (I guess Kodi popping up) and then Kodi stops working.

### To Reproduce
Don't know if it even can be reproduced without building the exact situation (OS; Version; etc.) and just starting it.

### Debuglog
The debuglog can be found here: 
[kodi_crashlog-20220711_083832.log](https://github.com/xbmc/xbmc/files/9081507/kodi_crashlog-20220711_083832.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:
None

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
none

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4
 - Debian Bullseye (11)
 - XFCE v4.16
 - `uname -a`: Linux desktop1 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
 
 Report from `hardinfo` (for additional system details - both soft-/hardware)
[hardinfo_report.txt](https://github.com/xbmc/xbmc/files/9081539/hardinfo_report.txt)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by basilgello** [comment]
What a strange Kodi build. Where did you get it? Looks like not Kodi from Debian or even deb-multimedia one.

**Comment by ACH1980** [comment]
According to apt show it's from deb-multimedia:

```ach1980@desktop1:/tmp$ apt show kodi
Package: kodi
Version: 5:19.4-dmo0+deb11u2
Priority: optional
Section: video
Source: kodi-dmo
Maintainer: Christian Marillat <marillat@deb-multimedia.org>
Bugs: mailto:marillat@deb-multimedia.org
Installed-Size: 52.8 MB
Provides: kodi-api-audiodecoder (= 3.0.0), kodi-api-audioencoder (= 2.1.0), kodi-api-audioengine (= 1.1.1), kodi-api-filesystem (= 1.1.6), kodi-api-game (= 2.1.1), kodi-api-general (= 1.0.5), kodi-api-gui (= 5.15.0), kodi-api-imagedecoder (= 2.1.1), kodi-api-inputstream (= 3.0.1), kodi-api-main (= 1.3.0), kodi-api-network (= 1.0.4), kodi-api-peripheral (= 2.0.0), kodi-api-pvr (= 7.1.0), kodi-api-screensaver (= 2.1.0), kodi-api-vfs (= 3.0.0), kodi-api-videocodec (= 2.0.2), kodi-api-visualization (= 3.0.0)
Depends: libasound2 (>= 1.0.27), libass9 (>= 2:0.15.1), libavahi-client3 (>= 0.6.16), libavahi-common3 (>= 0.6.16), libbluetooth3 (>= 4.91), libbluray2 (>= 2:1.3.0), libc6 (>= 2.30), libcap2 (>= 1:2.10), libcdio19 (>= 1:2.1.0), libcec6 (>= 2:6.0.2), libcrossguid0 (>= 2:0.0+git200150803), libcurl3-gnutls (>= 7.18.0), libdav1d5 (>= 1:0.9.1), libdbus-1-3 (>= 1.9.14), libdrm2 (>= 2.4.75), libegl1, libfmt7 (>= 7.1.3+ds1), libfreetype6 (>= 2.2.1), libfribidi0 (>= 0.19.2), libfstrcmp0, libgbm1 (>= 17.1.0~rc2), libgcc-s1 (>= 3.0), libgif7 (>= 5.1), libgl1, libgnutls30 (>= 3.7.0), libinput10 (>= 0.21.0), libiso9660-11 (>= 1:2.1.0), libjpeg62-turbo (>= 1.3.1), libkissfft-float131 (>= 131.1.0), liblcms2-2 (>= 2.2+git20110628), liblirc-client0, liblzo2-2 (>= 2.02), libmariadb3 (>= 3.0.0), libmicrohttpd12 (>= 0.9.50), libnfs13 (>= 1:4.0.0), libpcre3, libpcrecpp0v5 (>= 7.7), libplist3 (>= 2.2.0), libpng16-16 (>= 1.6.2-1), libpulse0 (>= 0.99.4), libpython3.9 (>= 3.9.1), libshairplay0, libsmbclient (>= 2:4.0.3+dfsg1), libsqlite3-0 (>= 3.7.11), libssl1.1 (>= 1.1.0), libstdc++6 (>= 9), libtag1v5 (>= 1.11), libtinyxml2.6.2v5, libudev1 (>= 183), libudfread0 (>= 1:1.1.2), libva-drm2 (>= 1.1.0), libva-wayland2 (>= 1.3.0), libva-x11-2 (>= 1.0.7), libva2 (>= 2.2.0), libvdpau1 (>= 0.2), libwayland-client++0 (>= 0.2.8), libwayland-cursor++0 (>= 0.2.8), libwayland-egl++0 (>= 0.2.8), libx11-6, libxext6, libxkbcommon0 (>= 0.5.0), libxml2 (>= 2.7.4), libxrandr2 (>= 2:1.2.99.3), libxslt1.1 (>= 1.1.25), zlib1g (>= 1:1.2.0.2), kodi-data (>= 5:19.4-dmo0+deb11u2)
Recommends: udisks2
Suggests: libdvdcss2 (>= 1.4.3)
Breaks: kodi-bin (<= 5:18.4-dmo2), kodi-data (<= 5:18.5-dmo1), kodi-gbm (<= 5:18.99~), kodi-standalone (<= 5:18.4-dmo2), kodi-wayland (<= 5:18.99~), kodi-x11 (<= 5:18.99~)
Homepage: http://kodi.tv/
Download-Size: 15.1 MB
APT-Manual-Installed: yes
APT-Sources: http://deb-multimedia.org bullseye/main amd64 Packages
Description: Open Source Home Theatre (executable binaries)
 Kodi (formally known as XBMC), is an award winning free and open source
 software media-player and entertainment hub for all your digital media.
 Kodi is available for Linux, Mac OS X (Leopard, Tiger and Apple TV) and
 Microsoft Windows, as well as the original Xbox game console. Created in
 2003 by a group of like minded programmers, Kodi is a non-profit project
 run and developed by volunteers located around the world. More than 50
 software developers have contributed to Kodi, and 100-plus translators have
 worked to expand its reach, making it available in more than 30 languages.
 .
 While Kodi functions very well as a standard media player application for
 your computer, it has been designed to be the perfect companion for your
 HTPC. Supporting an almost endless range of remote controls, and combined
 with its beautiful interface and powerful skinning engine, Kodi feels very
 natural to use from the couch and is the ideal solution for your home
 theater. Once installed, your computer will become a fully functional
 multimedia jukebox.

N: There are 2 additional records. Please use the '-a' switch to see them.```

**Comment by ACH1980** [comment]
Oh wait it seems to be another version installed on my OS... That's strange, will investigate this. Give me some time.

**Comment by basilgello** [comment]
I'd suggest you temporary install 19.1 from official Debian bullseye repos, check if it starts, then if it does, add a backport repo and install 19.4 from backports.

**Comment by ACH1980** [comment]
Ok it just get's more confusing. 

I downloaded the kodi package from deb-multimedia for comparison. And it seems to be the same version. Even though it's named other (at least the package), but I compared both the scripts at `/usr/bin/kodi` as well as the binaries at `/usr/lib/x86_64-linux-gnu/kodi` visually, functionally and via diff - they are in all aspects exactly the same. And they both say in the program this weird looking nogitfound version string...

Anyway they run again, but I'm confused, why they tell another version string via the program than written in the package.

**Comment by ACH1980** [comment]
> I'd suggest you temporary install 19.1 from official Debian bullseye repos, check if it starts, then if it does, add a backport repo and install 19.4 from backports.

Apparently it runs again. So from this perspective everything is fine - the original issue is resolved. The question I still have is this odd looking version string...

**Comment by ACH1980** [comment]
But as this also appears in the version downloaded from the repo I'm fine with this, so if you don't want to investigate this odds we could close this issue.

**Comment by basilgello** [comment]
OK, glad to have a working version for you!
