### ISSUE TITLE
font rendering problem

### ISSUE THREAD

**Issue by eddilara** [xbmc/xbmc#21689]
on windows 10 newest as of july 2022 with kodi 19.4 
FF Tisa OT XBold Italic.ttf / FF Tisa OT XBold.ttf 
these fonts don't render properly....tho I tested it on kodi 20 nightly july 15 2022 ..and it seems fixed...so not sure if it really needs to be fixed....figured Id report it anyway

**Comment by thexai** [comment]
Closed as not enough information has been provided and I don't think anyone on the team would be interested in looking into this if it is no longer an issue in v20.
