### ISSUE TITLE
Wrong pvr.waipu binary version in official Kodi repository

### ISSUE THREAD

**Issue by flubshi** [xbmc/xbmc#21691]
The latest version of this pvr addon for Kodi Matrix is pvr.waipu [19.2.1-Matrix](https://github.com/flubshi/pvr.waipu/releases/tag/19.2.1-Matrix). 

The official Kodi addon repository contains some Nexus versions of this plugin, see https://kodi.tv/addons/matrix/pvr.waipu

Platfform | Version in Repo
-- | --
windows-i686 | 20.4.2
windows-x86_64 | 20.4.2
android-aarch64 | 19.2.1
osx-x86_64 | 20.0.1
android-armv7 | 20.0.0

I would expect the Kodi binary repos contain version 19.x.x of pvr.waipu, because 20.x.x is intended for Kodi Nexus.

**Comment by KarellenX** [comment]
@wsnipex @fuzzard 

I've checked a few PVR folders in the repo and each has mixed versions again.

**Comment by yol** [comment]
@flubshi can you try installing https://github.com/apps/jenkins-xbmc into your profile and giving it access to the pvr.waipu repository?

**Comment by flubshi** [comment]
@yol done 👍

**Comment by yol** [comment]
should be OK now I guess

**Comment by ksooo** [comment]
@flubshi can this issue be closed?

**Comment by flubshi** [comment]
Yes, thanks!
