### ISSUE TITLE
Add voice search feature for Kodi Touchscreen / On-screen Keyboard [Android] [Android TV] [Improvements] [Feature Suggestions]

### ISSUE THREAD

**Issue by RFL0WGitPR** [xbmc/xbmc#21698]
I was wondering if Kodi could add some improvements to it's default keyboard on the Android platform for their next major stable public build release 

I'm talking about Kodi default on screen / touchscreen keyboard 

- Such as adding a voice search feature 

Who would benefit

(any Android user)
 those on mobile devices (Android / Android Tablet) 

 those on Smart TV devices or Android STB devices (Android TV / Google TV) as long as their device uses a integrated mic. 

Android TV users with a Mic built in on their TV Remotes could really use this 

They could use this feature for Kodi GUI navigation 

for media player controls [voice commands]

Searching for content inside Kodi GUI 

Opening and closing content etc.

**Comment by enen92** [comment]
Please use the forum for feature requests, we use GitHub issues for actual issues only.

**Comment by enen92** [comment]
Also Kodi supports this since at least the Leia... https://youtu.be/SrL3EDY3Pyk
