### ISSUE TITLE
PVR manager is starting up 0%

### ISSUE THREAD

**Issue by Temporary-Failure** [xbmc/xbmc#21705]
### Describe the bug
Here is a clear and concise description of what the problem is:

Installed latest windows version from https://kodi.tv/download/windows 64bit. Installed enigma client.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

PVR manager should be now installed

## Actual Behavior

PVR manager is starting up: 0% and doesn't change.

### To Reproduce

1. 
2.
3.

### Debuglog

https://u.pcloud.link/publink/show?code=XZCsg8VZ3tR68noCkyy8OMSkxe1VxzRThVpk

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi v19.4 (Matrix) 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Please ensure your enigma can be reached under the web address you configured in the add-on settings.

```
2022-07-23 13:22:40.729 T:3656   ERROR: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::ConnectionManager::Process - unable to connect to: http://127.0.0.1:80/web/currenttime
2022-07-23 13:22:40.729 T:3656  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Enigma2::ConnectionLost Lost connection with Enigma2 device...
```

**Comment by da-anda** [comment]
@Temporary-Failure is your issue resolved? If so, please close the ticket. Thanks.

**Comment by ksooo** [comment]
> @Temporary-Failure is your issue resolved? If so, please close the ticket. Thanks.

 No response. Seems the issue is fixed or the submitter lost interest.
