### ISSUE TITLE
cant support DolbyVision(DV) Matroska(MKV) files

### ISSUE THREAD

**Issue by qwerttvv** [xbmc/xbmc#21715]
cant support DolbyVision(DV) Matroska(MKV) files

like
[Doctor.Strange.in.the.Multiverse.of.Madness.2022.IMAX.2160p.DSNP.WEB-DL.DTS-HD.MA.TrueHD.7.1.Atmos.DV.MKV.x265-DVSUX](https://rarbgprx.org/torrent/vsbnli2)

[Doctor.Strange.in.the.Multiverse.of.Madness.2022.2160p.10bit.HDR.DV.BluRay.8CH.x265.HEVC-PSA](https://psa.pm/movie/doctor-strange-in-the-multiverse-of-madness-2022/)

it will played as normal HDR type, not DolbyVision

my system:
Android TV with kodi-20220729-f967fcb4-master-26196-armeabi-v7a

**Comment by fuzzard** [comment]
Mkv container DV is not supported. Feature requests can be made on the forums.
