### ISSUE TITLE
Kodi 19.4 makes Sound stuttering on Fire TV 4K Max Stick

### ISSUE THREAD

**Issue by Starfoxfs** [xbmc/xbmc#21716]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I install kodi 19.4 Matrix on a new Fire Tv 4k Max Stick (or Factory resetted), the sound starts sporadically stuttering, even outside of Kodi in prime video, plex, youtube etc...

Sound Setting in Fire TV 4K Max is Best available

Hardware: Fire TV 4K Max Stick plugged in an Onkyo TX-SR806 AV-Reciever connected to an Philips 37PFL4606H/12

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Actual Behavior

sporadically Sound Stuttering even outside of Kodi and in the Kodi App

## Possible Fix

Dont know it must be a driver or something loaded from Kodi if the Fire TV 4k Max is started.

### To Reproduce

1. Install Kodi 19.4 Matrix apk (armv7a) for Android on a Fire TV 4k Max
2. Run some Player App´s like Prime Video, Plex, Youtube, Joyn etc...
3. Sound stuttering appears and sometimes the Channel´s are not selected correctly Output Signal 5.1 and selected is 2.0 Stereo

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [FireOS 7.2.8.5 Fire TV 4K Max Stick ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4 Matrix (armv7a)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
So. If you remove Kodi, all other applications are suddenly fine again?

**Comment by Starfoxfs** [comment]
Simple Yes

**Comment by Starfoxfs** [comment]
I tested a bit and the bug is not from kodi itself but from the addon pvr iptv simple client or from the addons that are required for this e.g. ffmpeg direct

If PVR iptv Simple Client is installed with Kodi the Sound stuttering appears also outside of Kodi

**Comment by fritsch** [comment]
Might be that PVR data is fetched in the background causing CPU spikes. Debuglog would be good to have and then tell us at which time you heard the other app stuttering.

So start Kodi, enable debug logging, switch to other app as normal, wait for the stutter. Switch back to Kodi and upload the debug log please.

**Comment by Starfoxfs** [comment]
I have a normal Kodi Log with some Errors Sound/Video i don´t know if this is the Stuttering Bug

But I can activate Debug Log and wait for the Errors too.

[kodi.old.log](https://github.com/xbmc/xbmc/files/9226097/kodi.old.log)

**Comment by Starfoxfs** [comment]
Here a newer Kodi.log

Around Time: 15:14:48.925 and Row 38398 i started streaming Tele5 there was the Audio Stuttering Issue. Before i watched Nitro without issues.

**Comment by fritsch** [comment]
I am far more interested in the issue that kodi sabotages your other android apps. LiveTV, especially with SD channels is hit or miss on Android ... the log here says: decoder timeout, can basically mean everything - result -> no picture, reconfigure of video and audio -> seen as stutter.

**Comment by Starfoxfs** [comment]
Hmm, I'm now testing if this stuttering sound occurs when Kodi and PVR Simple Client are installed and after restarting Fire TV 4K Max Stick I don't open Kodi but first open other apps. 
What is certain is that the sound stutters after opening Kodi also occurs in other apps

And i search for other Log Files from other Apps for further Troubleshooting if this Sound Stuttering appears

**Comment by Starfoxfs** [comment]
Ok definitely after i started the pvr simple client the sound stuttering error occurs outside of kodi, not before.

**Comment by Starfoxfs** [comment]
I tested a bit more, and added some Movies and Series to the Kodi Library. Most of them in MKV Format and H264.

Most importantly i started the Movies, Series before the pvr simple client and the Sound stuttering also appears. So i Think its a Kodi VideoPlayer or Codec Problem like FFMpeg.

**Comment by Starfoxfs** [comment]
Another important piece of information is, if I set the Audio output configuration to fixed in the audio settings, the sound stuttering error is also gone.

If i set it to Optimized or Best Match the Sound stuttering is back.

**Comment by fritsch** [comment]
What is Kodi's setting for keep audio alive?

**Comment by Starfoxfs** [comment]
Keep Audio Alive = 1 Minute

Sometimes the Sound stuttering appear if i start Kodi and the Sound is initialzied for first startup even if Audio Output Configuration is set to Fixed.

But this is only 1 Time after starting up Kodi, i change the channel on Reciever to another channel and back to Kodi (FTV4KMax) then it runs fine with Fixed Audio Output Config.

**Comment by fritsch** [comment]
Kodi is opening all audio formats on startup, this can cause a short stutter. During Kodi runtime there is no real change in behaviour between fixed and let's say optimized.

Given that you stop Kodi Playback obviously.

**Comment by Starfoxfs** [comment]
Ok, then we should rather concentrate on the problem with optimized and best matched Audio Output.
Here is the Problem with the sound stuttering very often with e.g. program change available

With fixed audio output I can say that it works. But this audio option does not automatically change the audio channels on my receiver to e.g. Stereo. I would prefer the Audio Option Optimized.

**Comment by FernetMenta** [comment]
> Might be that PVR data is fetched in the background causing CPU spikes.

Exactly this. This also causes slight but noticeable stuttering in video when PVR is active. I cured it by having addons run on lower thread priority.

**Comment by Starfoxfs** [comment]
In my case it's not only in the PVR client, the sound stuttering occurs in all players, e.g. B. watching movies over LAN from my NAS or PVR IPTV over stream.

I only installed 1 addon (PVR Simple Client) on a freshly installed Kodi 19.4 Matrix.

If it's just CPU spikes, why isn't my receiver changing audio channels? If the source is in 2.0 stereo and my receiver stays in 5.1 Dolby when the stuttering occurs.

**Comment by FernetMenta** [comment]
> why isn't my receiver changing audio channels?

For what reason should it change channels?

**Comment by Starfoxfs** [comment]
For other Audio Sources like DTS, DTS-HD, Dolby Digital, Dolby Digital Plus and so on.

If Audio Control is setup to fixed the signal is a stupid 5.1 Channel 48KHZ without any changes and without Passthrough Option.

In this case i don´t need a good AV Reciever which can support DTS, Dolby True HD, DTS-HD an so on.

**Comment by FernetMenta** [comment]
You are mixing up serval issues.

**Comment by Starfoxfs** [comment]
No, i mixing not up several issues.

The Issue is above. Sound stuttering in Audio Configuration Output: Optimized and Best Match

I only say that Passthrough is not available in Audio Configuration Output is set to "Fixed" Mode.

**Comment by Starfoxfs** [comment]
Here a newer Log File:

Opened PVR IPTV Simple Client
Zapped around.

16:09:36.757 it works 6 Channels E-AC3

on my Reciever 5.1 Dolby Digital +
no Sound Stuttering

I zapped TV Channel to a Stereo Signal in AAC 2.0 Channels
16:10:07.735 

Here are no Errors i can see in the Log but my Reciever won´t change to Stereo

I have the same Signal as before on my Reciever 5.1 Channels and Dolby Digital +

Sound is now stuttering and Sound now stuttering everywhere in all Apps on FireTv4KMax Stick


[kodi2.log](https://github.com/xbmc/xbmc/files/9291557/kodi2.log)

**Comment by fritsch** [comment]
FireTV max itself always outputs Dolby if you have set it to besta available in FireTV settings. We cannot do anything about that. If you want PCM instead set it to - no kidding - stereo in FireTV settings. For Kodi then lpcm should be available.

Btw. this has nothing to do with the issue that only appears if you enable PVR in  FireTV...the issue is that the FireTV itself has too few ponies for stereo to Dolby upmixing and EPG update in parallel. This upmixing is not Kodi but FireTV firmware doing that.

Adb logcat will show that.

**Comment by Starfoxfs** [comment]
This is bad, so I can't use Kodi for movies and at most I can use it for IPTV with the audio output set to Fixed.

I know now that has nothing to do with PVR, at beginning i thinked that because the issue is always there if i enabled PVR Client.

The EPG update has nothing to do with this problem, I had disabled the EPG addon and EPG update in the PVR client, but the audio stuttering is still there

It can be a Upmixing Problem between FireTVStick and Kodi as you say

But what surprises me a bit, I've tried Plex in the meantime and there are no problems with it on the FireTVStick.

I know that Plex with a subscription is cost-based and maybe has more options and Kodi is open source software without its own income, I have respect for that and keep it up. Maybe one day it will also work perfectly on the FireTVStick.

**Comment by fritsch** [comment]
There is a song by Metallica: the day that never comes.
In the last verse they sing: if none comes by with the need to fix it 

I like that song

**Comment by fritsch** [comment]
If you don't feel like being a developer. It would be great, if you can backup your data and try with a Nexus nightly and see if behaviour has improved.

**Comment by Starfoxfs** [comment]
Nope, Nexus Nightly from 9 Aug 2022 same problem.

Fresh installed with IPTV Client.

Audio Source Dolby 5.1 change IPTV Channel to an Audio Source with AAC 2.0 then Sound stuttering.

**Comment by Starfoxfs** [comment]
If i change Audio Channels in Kodi Audio Settings to 2.0 instead 5.1 and allow Passthrough it works ?!?

But i have 5.1 Channels why this works with 2.0 Channels

Dolby Digital 5.1, Dolby Digital + 5.1 and DTS works although Audio Channels is set to 2.0 ?

I´m confused now.

**Comment by fritsch** [comment]
AC3 is a virtual format sent via 2 pcm channels only. Seems FireTV has issues if you give it 5.1 pcm channels as it encodes that byself to Dolby then. That's the reason why you never see LPCM on your avr. Keep it as is with 2.0, if you enable Dolby transcoding ontop all other format will be transcoded to AC3 by Kodi as well if it has more than 2 audio channels.

Kodi seems to have no performance issue doing so, where FireTV seems to have if it happens under the hood, which again was not a Kodi automatism... but Amazon firmware.

The root cause: high CPU load of PVR channel scanning should never the less be investigated.

**Comment by Starfoxfs** [comment]
My Audio Settings now:

Audio Channels: 2.0
Audio Output Config: Best Match
Passthrough: enabled
Dolby Digital AC3 capable Reciever: enabled
Enable Dolby Digital AC3 transcoding: enabled
Dolby Digital Plus E-AC3 capable Reciever: enabled
DTS capable Reciever: enabled
DTS-HD capable Reciever: enabled
Use DTS Core: enabled

I getting now Dolby Digital + 5.1 for Dolby Digital content and DTS for all DTS content and 2.0 Stereo for the rest.
Stutter Free !

Works perfect for Fire TV 4K Max Stick, only DTS-HD doesn't work yet but that's not so bad

**Comment by fritsch** [comment]
DTS HD Ma is not supported by FireTV, but DTS HD HR works. I did not really care to add a separate GUI setting for the latter.

**Comment by Starfoxfs** [comment]
How can i enable DTS-HD HR ?

**Comment by fritsch** [comment]
kodi's DTS-HD settig stands for a superset for DTS-HD formats which are output with 8 channels 192 khz AND those with 2 channels 192 khz, so it includes DTS-HD-MA _and_ DTS-HD-HR. Whenever DTS-HD-MA comes (8 channel 192 khz transport stream - don't mix this with real channels and samplerate, all those PT formats are "digital formats" and either kodi or AVR decodes them) the core, means DTS is played on your device as it cannot support this transport stream, whenever DTS-HD-HR comes, DTS-HD-HR is played IF supported (2 channels 192 khz), if not also the Core DTS is played. Nothing to do from GUI.

Tron Legacy english track is among the very few I know for DTS-HD-HR audiotrack.

Example: https://fritschserver.no-ip.org/index.php/s/ZmrRBoTRJMKRMfe

**Comment by thexai** [comment]
Thinking that this can be closed: 

No passthrough when output setting to "fixed" is by design.  See: https://forum.kodi.tv/showthread.php?tid=311370&pid=2563119#pid2563119

> It can be a Upmixing Problem between FireTVStick and Kodi as you say

This is a similar issue to Shield audio stutter/dropouts when some (external to Kodi) audio processing options enabled: Shield "Dolby processing" setting. See: https://github.com/xbmc/xbmc/issues/21764 

and https://www.reddit.com/r/kodi/comments/thkjqg/anybody_still_having_audio_drops_on_194_with/

> I getting now Dolby Digital + 5.1 for Dolby Digital content and DTS for all DTS content and 2.0 Stereo for the rest.
> Stutter Free !
> 
> Works perfect for Fire TV 4K Max Stick, only DTS-HD doesn't work yet but that's not so bad

> DTS HD Ma is not supported by FireTV, but DTS HD HR works.
