### ISSUE TITLE
Characters in certain skins display corrupted symbols

### ISSUE THREAD

**Issue by jmaeshawn** [xbmc/xbmc#21710]
### Describe the bug
Here is a clear and concise description of what the problem is:

To be honest, I'm not sure if this is a bug with how the new v20 handles skins, or if this is a problem with the skin itself that needs to be corrected to work with the new version of Kodi...

In v19.x (Matrix), everything displayed and worked correctly,  but after upgrading to v20 certain characters display as garbled symbols in the titles and synopsis of TV Shows and Movies, as well as in system menus.

I'm hoping you can fix it quickly and make things display correctly in skins.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Every character in the titles and descriptions of TV Shows and Movies, as well as in the system menus should display properly.

## Actual Behavior

It seems like the title/description of every movie or TV show or system menu that has the characters "ff" or "fi" or "ffi" end up displaying a weird garbled character instead of those letters.

### To Reproduce

1. Install and switch skin to a skin other than the default skin (in my case, I'm using Bello 8.01)
2. Navigate to a TV show or movie that has "ff" "fi" or "ffi" in the title or description, or go to Settings>Interface Settings>Con**fi**gure Skin
3. See corrupted characters.

### Debuglog

The debuglog can be found here:
[debuglog](https://paste.kodi.tv/bihigejini.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

In my case, this happens a lot with the 1968 Hawaii Five-O series. According to [tvdb](https://thetvdb.com/series/hawaii-five-o/episodes/39263), the description of the episode should be "An army sergeant and a o**ffi**ce worker have a scam in which they use bar girls to claim G.I. widow bene**fi**ts, and then murder them to take the cash. McGarrett and company must use the girls to get to the core of the plot."
But it instead ends up looking like this:
![One example of corrupted characters in description](https://i.imgur.com/0ImqHYu.png)

Another example is in the title of the "Male**fi**cient" movie series, which  ends up being displayed like this:
![An example of corrupted characters in titles](https://i.imgur.com/ylxIkTM.png)

The title of the movie "Ferris Bueller's Day O**ff**" ends up looking like this:
![Another example of corrupted characters in titles](https://i.imgur.com/sOIoYpI.png)

And with "American Gra**ffi**ti" here:
![A 3rd example of corrupted characters in titles](https://i.imgur.com/9WM7vp6.png)

It also seems to happen in the system menus, such in the Interface Settings menu, where "Con**fi**gure Skin" is displayed like this:
![Example of corrupted characters in system menus](https://i.imgur.com/lyH05Vb.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Version 21H1 (Build 19043.1706)
 - Kodi version: Kodi 20.0 ALPHA-2 (19.90.705) Git: 20220703-3c67e62df9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@jmaeshawn 

I can't seem to replicate this using Windows 10 64bit.

Can you change back to the default Estuary skin and see if the problem still exists.

**Comment by thexai** [comment]
v20 has been updated to allow font rendering OpenType features see https://typofonderie.com/font-support/opentype-features/

Looks like a problem with ligatures.

I have been able to reproduce it but only with the mentioned skin. Other skins work fine: Cosmic, Amber, Aeon Tajo...

Perhaps the font used in this skin is not "OpenType" or has some incompatibility with HarfBuzz (text shaping engine).

Updating the font of the skin would fix the problem.

Also tested with last 3 `GUIFontTTF` commits reverted and problem persist (only in this skin) so it's not a recent regression.

**Comment by scott967** [comment]
I confirmed this issue in skin.belo.8 from Nexus repo.

I then examined ttf font OpenSans-regular.ttf supplied with that skins.  Looking at the Open Type features, for script Latn I see some strange things  (I don't have experience creating OT features, so I'm no expert).

Here is an example from the ligatures:
![OT Features](https://i.imgur.com/DwlpKW8.jpg)

So I deleted that subtable and exported the mod ttf font.    I then substituted the mod font in bello.8 and that seems to fix the issue.  However, I recommend the skin maintainer review all the Open Type features for possible problems.

**Comment by scott967** [comment]
Here's the modded ttf file, but I think there are other errors so YMMV
[OpenSans-Regular.ttf mod](https://mega.nz/file/3OAThZBI#aulwtlN4zKawoT3cFW1d4skc0EXrmLN6WZe6wL0hwHU)

**Comment by jmaeshawn** [comment]
@scott967 

Since I have the same font editor program you do, I actually managed to fix the font myself based on your screenshots showing where to find the ligature table in FontCreator's OpenType Designer, but thank you for linking to your copy! :)

After replacing the included font with the modded font, I haven't noticed any other problems. So I'll close this issue, since it seems this isn't a problem with Kodi but rather the font itself being malformed, or possibly how Bello utilizes the font.

(Although I suppose it'd be worth pointing Bello's maintainer Nessus over to this issue so he can hopefully fix it by the time Nexus gets a full release.)

Thank you for looking into this so thoroughly and narrowing the problem down to the particular font in that particular skin. 👍

**Comment by KarellenX** [comment]
@Nessus85100
FYI

**Comment by Nessus85100** [comment]
Thanks @jmaeshawn for spotting this and all the others on finding where the problem is. The OpenSans font used in Bello it's from v1.0.0 so i cant remember anything about that. Unfortunately due to my day job i have no time to look at this. After the tourist season finishes, here in Greece, about the end of October i will have a look along with the update of Bello for Nexus.

Cheers
Nessus
