### ISSUE TITLE
Kodi 19.4 crashes on startup when the Sound Preference is set to SpeakerAmp on MacOS 

### ISSUE THREAD

**Issue by verticalscience** [xbmc/xbmc#21711]
### Describe the bug
Here is a clear and concise description of what the problem is:

MacOS can be configured to route sound output to an internal speaker, external bluetooth device, ChromeCast or an internal application like an equalizer.  When the default sound output selection is set to the "SpeakerAmp" application then Kodi 19.4 crashes during startup.  

 This problem is easily confirmed by running Kodi manually from a terminal window and entering /Applications/Kodi.app/Contents/MacOS/Kodi.  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Ideally, Kodi should support whatever sound device has been configured as the system default.   Apps like SpeakerAmp allow users to increase frequencies that are harder to hear, or increase volume in noisy environments, across all apps.

## Actual Behavior
 Kodi begins initialization and eventually gets to enumerating the sound devices then quits and dies.

### To Reproduce

1.  On a Mac desktop or laptop install MacOs Catalina and Kodi.   (Problem occurs on multiple versions of MacOS)
2. Install the free SpeakerAmp GUI from the Mac App store.
3. Page through the SpeakerAmp Wizard til it shows the SpeakerAmp (OS Specific) driver is not installed
4. Install the SpeakerAmp Driver
5. Set the MacOS sound preferences to "Internal Speaker"
6. Confirm Kodi starts correctly set to "internal Speaker" sound output
7. Set the MacOS sound preferences to "Speaker Amp" 
8. Start Kodi from the Application icon (app should fail to appear or only appear briefly then quit)
9. Open a terminal window and enter:  /Applications/Kodi.app/Contents/MacOS/Kodi
10. Observe the startup messages from Kodi.  
11. Kodi should quit after it tries to initialize the SpeakerAmp output device

### Debuglog

The debuglog can be found here:

Enumerated DARWINOSX devices:
...
m_deviceName      : SpeakerAmp-42:stream0
CActiveAEResampleFFMPEG::Init - init resampler failed
CActiveAEResampleFFMPEG::Resample - resample failed
ActiveAE::Configure - sink returned large buffer of -2147483648 ms, reducing to 100 ms
Floating point exception: 8

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/7625179/181383906-7c44fcc0-0a1f-447c-87af-6a8cfae0657a.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

![image](https://user-images.githubusercontent.com/7625179/181384008-bf9c66ae-8fcc-46a7-87b6-65c1040faa75.png)
![image](https://user-images.githubusercontent.com/7625179/181384466-b23428ef-fccf-4a11-a927-16f58d2bf827.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP
 - [ X] MacOS

 - Operating system version/name:
![image](https://user-images.githubusercontent.com/7625179/181384118-363c6f68-62f6-4f26-b0ad-9523fbbf8828.png)

 - Kodi version:
![image](https://user-images.githubusercontent.com/7625179/181384289-aa25267e-84ef-43cc-be53-9dbc94aae7aa.png)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
I cannot reproduce this on ventura and kodi 20. Please retest if you have a chance, otherwise the issue will be closed.
Also there's no log and no crashlog provided.
