### ISSUE TITLE
Multiple error compiling kodi

### ISSUE THREAD

**Issue by TsunamiOfTech** [xbmc/xbmc#21725]
### when I compile kodi with cmake it doesn't work
Here is a clear and concise description of what the problem is: cmake throws a bunch of could not find library errors

Because kodi won't build

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should build

## Actual Behavior

Cmake had errors

## Possible Fix

Idk

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ✅] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
You have provided absolutely zero information of value.

Provide a log, or something, if you expect any help. The windows nightlies are built every 2 days successfully, so master "works".

As it stands, you are probably better off making a post on the forums at this stage with details/logs, and someone should be able to help you more.
