### ISSUE TITLE
Kodi letterboxes (does not fill the screen) on version 19.4

### ISSUE THREAD

**Issue by Aholicknight** [xbmc/xbmc#21723]
For some reason Kodi does not fill the screen when I use Kodi on my iPhone 13 Pro on iOS version 16.0

![image](https://user-images.githubusercontent.com/7843719/182484819-e6471290-d0b7-4fd2-bed4-04d751aaee67.png)

I signed the app using a UDID Certificate, and if I use the default skin or any other skin downloaded from the add-on store, it does not fill the screen.

Playing a video does the same thing and shows a letterbox as well. 

If you want to see the Kodi system information you can see it here:
![image](https://user-images.githubusercontent.com/7843719/182486415-1aec62ee-c6f4-4223-86d0-46d9c4a8895b.jpeg)

Would appreciate if someone can tell me how to fix this. Thank you!

**Comment by thexai** [comment]
> Playing a video does the same thing and shows a letterbox as well.

Because video is 16:9 and iPhone 13 screen not

**Comment by Aholicknight** [comment]
> > Playing a video does the same thing and shows a letterbox as well.
> 
> 
> 
> Because video is 16:9 and iPhone 13 screen not

@thexai Is there anyway to override Kodi's screeen resolution?

**Comment by sarbes** [comment]
To further diagnose your problem, please stick to the template and provide a debug log. Otherwise, it makes it hard or impossible to diagnose your issue.

**Comment by Aholicknight** [comment]
@sarbes Where are the debug logs kept on the iOS versions? I'll upload it so you can see it.

**Comment by sarbes** [comment]
Dunno. But there is an add-on which let's you upload the file https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

**Comment by Aholicknight** [comment]
@sarbes paste has been uploaded here: https://paste.ee/p/SKI8D
