### ISSUE TITLE
Kodi text shaping engine for Arabic/Persian scripts breaks multiple skins search implementations

### ISSUE THREAD

**Issue by movianlost** [xbmc/xbmc#21721]
### Describe the bug
Here is a clear and concise description of what the problem is:

The search function in some Kodi skins doesn't work with Arabic scripts (Arabic/Persian...) and it works well with other complex scripts like Korean/Chinese or RTL scripts like Hebrew.

This is not caused by a bug in search function but rather by how Kodi handles text shaping for Arabic scripts as I will explain below.

I've reported the same bug in two different Kodi skins and one of the developers of the skin said that this is an `external issue` to his skin, which I agree with after I have done some research on how Kodi handles Arabic.

Here are the issues I opened in the skins repositories:
[Arctic Horizon 2 skin](https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/355)
[Auramod skin](https://github.com/SerpentDrago/skin.auramod/issues/269)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The expected behavior is to get search results for words/letters that I know should give me results.

## Actual Behavior

It doesn't return any results for any words I type, even if I type just a single letter I get no results.

## Possible Fix

I have been doing some testing and it seems like the issue is that Kodi is not compliant with how the Unicode Consortium advises on how to implement rendering Arabic text.

In Unicode there are two spaces for Arabic characters, the old one called [Arabic_Presentation_Forms-B](https://en.wikipedia.org/wiki/Arabic_Presentation_Forms-B) which is just an old abandoned Unicode space that is only advised to be used for referencing a certain Arabic letter shape and is there mostly for backward compatibility with old systems, in this space, for each Arabic letter there is mostly 4 Unicode characters for it, each one of these 4 characters represent one shape of that Arabic letter in a specific position in a word (in isolation, at the start,middle or end of a word). 

From https://www.unicode.org/versions/Unicode14.0.0/ch09.pdf:
  >Arabic Presentation Forms-B...are included here for compatibility with preexisting standards and legacy implementations that use these forms as characters. Instead of these, letters from the Arabic block (U+0600..U+06FF) should be used for interchange Implementations should handle contextual glyph shaping by rendering rules when accessing glyphs from fonts, rather than by encoding contextual shapes as characters.

The new Unicode block that should be used for Arabic encoding is called [Arabic_(Unicode_block)](https://en.wikipedia.org/wiki/Arabic_(Unicode_block)), this is the block that Unicode advises everyone to use, each Arabic letter has exactly one Unicode codepoint in this block, there are no character for each shape of the same character.

The Kodi built-in on-screen keyboard is mapped to characters in Arabic_(Unicode_block) which is the correct implementation, but when Arabic input is submitted, in this case into a label, each character in that input gets converted from Arabic_(Unicode_block) into characters from Arabic_Presentation_Forms-B depending one the letter position in the word, this implementation is not the standard way on how to do things the Unicode way and today's bug is a testimony to this, the correct implementation should be to never do any character substitution just to change the character's shape, that's the job of text shaping engine.

The shaping engine is the one who sees text, determine which the position of each characters and compute how each character should look like and then tells the font which glyphs should be used for each character or a combination of characters.

Here are some old issues/pull requests about the Arabic keyboard, I suspect that they may have fixed those issues at the expense of not following the Unicode standard, :
https://github.com/xbmc/xbmc/issues/16040
https://github.com/xbmc/xbmc/pull/17790
https://github.com/xbmc/xbmc/pull/17692

### To Reproduce

1. Install a skin like "Arctic Horizon 2" or "Auramod" then change the font to a font that has Arabic like Ariel or NotoRoboto-Arabic
2. type in any Arabic word or just a single letter in the search box in the home screen. You'll get no result no matter what you type in Arabic or Persian or in any Arabic scripts, but it will return results for any other language and I have tested a lot like Korean,Chinsese,Russian,Hebrew... 

### Debuglog

Note that the expected results is to always get results when doing a search as I made search to only search letters/words that I know should get me results.
The debuglog can be found here:

1. [Kodi.log after Global search single Arabic letter](https://gist.github.com/movianlost/70cdf0fe7e4a962a95334b09bd074c81)
`No Results Found:` used single Arabic letter to eliminate the possibility that this is an RTL language bug, a single letter means that the order of characters is not important

2. [Kodi.log after Global search single Arabic word](https://gist.github.com/movianlost/18ac9e9dcb852ae02c5c24385753f310)
`No Results Found:` The same an entire Arabic word, no result is returned.

3. [Kodi.log after Global search single Hebrew letter](https://gist.github.com/movianlost/0e5c542b6ebb86d06f416f8c324a7e8a)
`Expected Results`: Hebrew return expected results, I used this to also eliminate that this is not an issue of RTL language reversing the characters order. Since Hebrew return results, this means it is not RTL issue.

4. [Kodi.log after Global search single Russian letter](https://gist.github.com/movianlost/6fdec3f5420f91b1e5b6e87dfffd3302)
`Expected Results`: I added Russia as an example of non-latin LTR language that also words as expected.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

![Screenshot_20220802_165730](https://user-images.githubusercontent.com/81398427/182432572-392e9d67-3fb2-4e11-822b-be722b4efae7.png)

At the top left, you can see the search input, what I have typed in there using the on-screen keyboard should look like this `مدرسة`  but because Kodi converts the Arabic_(Unicode_block) characters to Arabic_Presentation_Forms-B, this conversion is what messes the inputted text into the search label, and this is why I don't get any results.

### Your Environment
Used Operating system:

 - [x] Android
 - [x] Linux

 - Operating system version/name:
 - Kodi version: This bug is present in all of these version Kodi matrix 19.3 and 19.4 and Nexus 20.0

**Comment by scott967** [comment]
Related issue [16040](https://github.com/xbmc/xbmc/issues/16040)

**Comment by jurialmunkey** [comment]
To add a bit of context to movianlost's incredibly detailed bug report:

In the skin I'm using a standard "edit" control to allow the user to type either directly into the box or click the control to bring up the on-screen keyboard.

The user's input is then retrieved via the index of the control label - ie
$INFO[Control.GetLabel(id).index(1)]

At first I thought this was an issue with not being able to percent encode the edit control but that appears to not be the case and the issue is instead the actual character codes in the edit control are incorrect. As far as I can tell a skin.string will have the correct character codes but the edit control will not. You can even see in the edit control the text is displayed incorrectly.

**Comment by scott967** [comment]
I'm taking a look (unskilled though I am)
I don't see how the theory can be the cause.  From what I see the Arabic virtual keyboard utf-8 encodes the 0600 unicode block and also the Arabic UI code page decodes to 0600.  But I am just starting out on looking at this.

**Comment by jurialmunkey** [comment]
@scott967 - just FYI I'm not using global search. I use my own custom window for search.

My custom window has an edit control and then the value of the edit control is added to the query param of a plugin path in content tags of a list container.

If I search directly in the plugin by calling Dialog().input() within python then I get the correct character codes. That's why global search works - because the input dialog is internal.

The problem occurs when using a custom edit control in a standard custom window. The $info label from the skin passes the wrong codes (eg fe00 instead of 0600).

**Comment by scott967** [comment]
There's definitely something going on, but I haven't figured out so far where to set a breakpoint so I can see what the internal data is.

**Comment by scott967** [comment]
Would be nice to know 2 things:  Appears to be only log snippets.  Is this issue on Windows?  If so, would like to know if it can be reproduced on other platform like Linux.  And when OP writes about typing into the control, I take it this is on an Arabic keyboard.  If so, what exact keyboard (if this is windows) or IME is being used?

Reason for asking is I am trying to understand what Win32 api ToUnicode does.  It is getting called in WinEventsWin32.cpp which I don't know if it is at all relevant, but it is a place to start.

**Comment by movianlost** [comment]
@scott967 the log are snippets because I was deleting kodi.log just before I start the test and copy what's inside of kodi.log after my test is done, just to make it easier for people to read.

I don't use Windows. I have tested this issue in Kodi 19.4 on Debian Linux, Kodi 19.4 on LibreElec, Kodi 19.3 on Android TV and 20.0 on Android Mobile and they all produce this same issue. With that said, the logs are from running Kodi 19.4 on Debian Linux.

When I type, I bring the on-screen keyboard, and I have test both scenarios, the first is using the on-screen keys, so navigating through the arrow keys and click on individual letters in the screen and the second test is also bringing the on-screen keyboard, but this time, I typed on the input field using the physical keyboard. Both yield the same result which is understandable considering both the physical keyboard and on-screen keyboard are typing the same U+0600 Arabic characters which you can easily check if you read the `/usr/share/kodi/system/keyboardlayouts/arabic.xml` file.

I'm not familiar with Kodi code, but If was trying to fix this bug, I would start by finding what code is converting Arabic characters from U+0600 block to U+FE00 block, because this conversion should not happen and it is root of this bug.

**Comment by scott967** [comment]
OK thanks.  @jurialmunkey I installed skin.arctic.horizon.2 ver 0.3.6 from your repo into 20.0-ALPHA2 (19.90.705) Git:20220801-3c71103d15 to test and unfortunately, I can't get the search window Custom_1114_Search to actually complete a search -- just get a busy spinner with "loading songs" "loading albums" "loading movies" depending on how I mouse around in that window.

But I did create a test user on Win 10 x64 and installed Arabic language pack then switched to the windows Arabic 102 AZERTY keyboard, using both Windows OSK and keyboard, and visually and from the log it looks right to me:
`CDirectoryProvider[videodb://movies/titles/?xsp={"order":{"direction":"ascending","ignorefolders":0,"method":"sorttitle"},"rules":{"and":[{"field":"title","operator":"contains","value":["ال"]}]},"type":"movies"}]: refreshing..` 

Is there some better version of the skin to try or do I need some skin settings?  But at this point it seems I can't replicate on Win 10.

**Comment by jurialmunkey** [comment]
@scott967 skin is broken on nexus until transparent control rendering fix is merged
https://github.com/xbmc/xbmc/pull/21645

You either need a test build including that PR or go back to nexus nighties prior to Jun 5 (which was when that transparent control bug issue was introduced into the skinning engine)

**Comment by jurialmunkey** [comment]
@scott967 - Here's a simple test plugin which will output to `xbmcgui.Dialog().ok()` the value passed to its `info=` param both as the string and the bytes output of raw_unicode_escape encoding
https://github.com/jurialmunkey/plugin.video.testlang

You can then create a simple custom window in Estuary to test output of edit control to content via info label
```
<?xml version="1.0" encoding="utf-8"?>
<window id="1120" type="window">
	<defaultcontrol>9001</defaultcontrol>
	<controls>
		<control type="edit" id="9001">
			<width>600</width>
			<height>80</height>
			<top>80</top>
			<left>80</left>
		</control>
		<control type="list">
			<left>80</left>
			<top>320</top>
			<itemlayout />
			<focusedlayout />
			<content>plugin://plugin.video.testlang/?info=$INFO[Control.GetLabel(9001).index(1)]</content>
		</control>
	</controls>
</window>
```

Here's value input into Kodi onscreen keyboard (UTF characters 062D and 0644)

![image](https://user-images.githubusercontent.com/4618719/183033113-0727201e-318f-4a0e-a128-9b51a4cfbd7b.png)

And here's the bytes output showing that it is being converted to FE code block

![image](https://user-images.githubusercontent.com/4618719/183033491-c3a1a3c2-0d24-450b-ada4-efa828d814e6.png)

If we switch id=9001 to a button that does `<onclick>Skin.SetString(MyString)</onclick>` and replace the info label in the content tags with `$INFO[Skin.String(MyString)]` and then input the same characters we see that the conversion to the FE block is still occurring but now the character order has been reversed so that the label appears correctly in the control 

![image](https://user-images.githubusercontent.com/4618719/183034939-f212cc0e-9467-45f3-b856-8fe023138db1.png)

**Comment by jurialmunkey** [comment]
After thinking about this a bit more -- I'm assuming the reason for the conversion to presentation forms FE block in the $INFO[] is due to the way Kodi maps the glyphs to a texture map.

In that case, one possible solution would be something similar to how `$ESCINFO[]` works but instead of escaping it would normalize and decompose the unicode string using NFKD normalization -- e.g. a `$NFKDINFO[]` if you will.

At the very least, if we can get the RTL character order issue for the edit control fixed so that the text displays correctly, then I can deal with normalization and decomposition of the presentation forms in python for my own plugins (and request that other plugin authors do the same).

**Comment by scott967** [comment]
OK, confirmed this using this on estuary home window
```xml
<control type="edit" id="9099">
	<posx>800</posx>
	<posy>100</posy>
	<width>250</width>
	<height>75</height>
	<textoffsetx>30</textoffsetx>
	<ondown>SetProperty(PreviousSearchTerm,$INFO[Control.GetLabel(9099).index(1)])</ondown>
	<ondown>Skin.SetString(PreviousSearchTerm, $INFO[Control.GetLabel(9099).index(1)])</ondown>
	<ondown>9000</ondown>
</control>
```
based off of your custom window.

First test is using Kodi Arabic QWERTY keyboard.  While the virtualkeyboard does enter the text RTL, the edit control displays it LTR.

When I checked what was saved in the skin setting I get
```xml
<setting id="PreviousSearchTerm" type="string">U+FEA2 U+FEDF U+FE8D</setting>
```

So see the error here in changing codepoints

I don't see how this is a glyph issue, as AFAIK we should ONLY be using the Unicode charmap table by passing unicode to harfbuzz / freetype to get the glyph index and then image.  If we are doing some sort of reverse lookup from glyph index to char code, don't see why we would?

Really need to get a good breakpoint in code execution.

**Comment by movianlost** [comment]
>I don't see how this is a glyph issue, as AFAIK we should ONLY be using the Unicode charmap table by passing unicode to harfbuzz / freetype to get the glyph index and then image. If we are doing some sort of reverse lookup from glyph index to char code, don't see why we would?

Does the text shaping engine apply to the text that is in the on-screen keyboard input field or does it only happen when the text is in a label or just as normal text in a page? because if there is no text shaping happening for keyboard input field, then maybe Kodi is doing some conversion for the characters while they are still in the on-screen keyboard input field so that they look joined without need for any text shaping engine.

I suspect this because there is an old bug that was complaining that although Arabic text throughout Kodi is joined together, the text in the on-screen keyboard input field is not joined together, so maybe they fixed that by converting the 0600 characters to FE00 character to look joined together without need text shaping engine. 
Here is the bug I'm talking about: [Arabic letters not connected when using virtual keyboard #16040
](https://github.com/xbmc/xbmc/issues/16040)

Then there are these 2 pull requests that seem to fix Arabic text looking backward on the on-screen keyboard input field:
[Prevent RTL text from mirrorring around styled characters for on-screen keyboard #17790
](https://github.com/xbmc/xbmc/pull/17790)[Correct on-screen keyboard behaviour for Arabic characters #17692
](https://github.com/xbmc/xbmc/pull/17692)

If you checked these issues/pull request you may find where they introduced a bug when they tried to fix how Arabic look like in the on-screen keyboard input field.

**Comment by movianlost** [comment]
@jurialmunkey 
>After thinking about this a bit more -- I'm assuming the reason for the conversion to presentation forms FE block in the $INFO[] is due to the way Kodi maps the glyphs to a texture map.

It's very clear from the Unicode standard that FE block should only be used when people want to talk about the shape of the character or for old system, the FE block should never be used for encoding in any modern software. If Kodi is using FE block for the character's shape, then it's not a good implementation and that's not the correct way to display Arabic text. Kodi should just send the characters to the text shaping engine which will tell him what glyphs IDs in the font to display.

Although the normalization can be a solution, I think a better solution is to avoid the 06 to FE block conversion from the first so no other addon is forced to deal with any normalization on their own.

**Comment by scott967** [comment]
So in testing so far using the virtualkeyboard dialog for text input and Arabic QWERTY, I can see that as you click on letter, the correct UTF-8 is input and it is decoded to correct unicode codepoint (0600 block) as you type in something called m_text2.  But once you click OK and exit the virtualkeyboard, the input is changed into UTF-8 encoded FE00 block.

**Comment by scott967** [comment]
OK did some more testing.  This is specific to the edit control.
Going back to Leia 18.9, I see similar problem, so I don't think adding harfbuzz shaping is the cause of the problem.
In Leia, when I enter via virtualkeyboard Arabic QWERTY keyboard, things seem to look OK while entering text, but clicking OK results in error in the label2 of the edit control.
1.  Text is rendered LTR
2.  Text has been changed from 0600 block to FE00 block.  But, in this case it is converting the unicode to the FE00 block .isol variants, whereas in current Kodi it is selecting initial/medial/final variants.  So shaping does change things, but isn't the cause.  (Again, this is estuary with a simple mod to home window and the estuary "arial based" font, i.e., arial.ttf).  I also modded the font to remove the Arabic shaping GPOS/GSUB data in Kodi 20 and still the error persists.  So again I don't think shaping per se is the problem.
I did cheat and hack globalsearch to do NFKC normalization on the input which "fixed" this specific case, but that's a hacky work-around, and of course does nothing for the real edit control issue nor the skin use of edit.

I note that mostly what goes on in shaping is the GSUB from the base 0600 unicode to initial/medial/final  glyph forms, but again, based on Leia results shaping is not the cause.   There are some ligatures also in arial.ttf but I haven't looked into that.

**Comment by scott967** [comment]
OK I have narrowed down the problem.
The issue I see is
**Edit Control does not correctly accept text input in Arabic**

In CGUIEditControl.cpp when Arabic text string is entered with virtualkeyboard, the text entry is terminated with the "OK" key

The entered text is processed through FriBiDi and Arab shaping for display purposes as label 2 of the control
However, the logical order must be retained and passed to any builtin, otherwise string compare / search etc will fail.
Instead, the visual order is retained, resulting in invalid string compares in builtins.  Likewise invalid input is stored in any setting.

**Comment by scott967** [comment]
I did some quick testing of my PR in Arctic Horizon 2 and it seems to work, but @jurialmunkey and @movianlost could you try building this and see what happens?  I don't have dev rights to build anything here but I think I could probably build an installer and post it somewhere if absolute necessary.  I was getting some Kodi crashes but I don't think related to this change.

**Comment by jurialmunkey** [comment]
FYI - WIN64 testbuild here: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220809-e8868e4c-Fix_RTL_Text_Input_In_Edit_Control-x64.exe

From a quick test, it appears to be working correctly. Text is rendering correctly in the edit control and I appear to be getting the correct unicode and in the correct order when passing the edit control index(1) to the plugin path. I'll need to do some more tests but so far it is looking very promising. Amazing work!

![image](https://user-images.githubusercontent.com/4618719/183840919-ad815332-a849-4655-9de0-3b463b1a26cb.png)

**Comment by movianlost** [comment]
Is there a test build for Linux x86-64? I've checked https://jenkins.kodi.tv/job/BuildMulti-PR/23527/ and only builds that can downloaded are for Android/ios for the others I can only see gtestresults.xml

If there is a Linux version, I want to make some tests to make sure there are no regressions in other parts of Kodi for handling Arabic text.
