### ISSUE TITLE
advancedsettings.xml setting cleanonupdate no longer works

### ISSUE THREAD

**Issue by MauriceW67** [xbmc/xbmc#21728]
### Describe the bug
Here is a clear and concise description of what the problem is:

In the latest Kodi 20 nightlies/alpha the "cleanonupdate" setting in advancedsettings.xml no longer works.

Normally when this setting is set to "true" and the option "Update library on startup" is enabled in Kodi, a library cleanup would run after the scan for new items was finished. This was visible through a notification with a progress circle showing the cleanup process running from 0 to 100 percent.

Note: I used season 1 of the show "The Plot Against America" for testing.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After scanning for new items, a library cleanup should be run automatically and shown on screen in a progress notification.
This used to work in previous versions of Kodi.

## Actual Behavior

A library cleanup is not run despite the cleanonupdate option in advancedsettings.xml being set to "true".

### To Reproduce

1. Add a new TV show / episode to a source location (f.e. an SMB share)
2. Let it be scanned into the library
3. Remove the TV show / episode from the source location
4. Restart Kodi
5. A library scan + cleanup should occur, but only the scan runs and not the cleanup.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/furucojixo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 11 (NVidia Experience 9.0.2)
 - Kodi version: 20.0-ALPHA2 (19.90.705) Git:20220729-1a8b1c59db

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MauriceW67** [comment]
@enen92 Thanks for looking into this and fixing it. I will test as soon as a nightly containing the fix is available.

**Comment by enen92** [comment]
@MauriceW67 you've test builds here (testing is appreciated):

http://mirrors.kodi.tv/test-builds/android/arm/kodi-20221006-d8b09429-clean_on_update-26880-armeabi-v7a.apk

http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20221006-d8b09429-clean_on_update-24466-arm64-v8a.apk

**Comment by MauriceW67** [comment]
@enen92 Thanks. I tested the 64-bit build on my Shield 2019 Pro and now it shows the cleaning and compressing database notifications again after a library update.
