### ISSUE TITLE
Cmake not working

### ISSUE THREAD

**Issue by TsunamiOfTech** [xbmc/xbmc#21731]
### Describe the bug
Here is a clear and concise description of what the problem is:cmake has a lot 9f errors during the build process

Cuz it don't work

## Expected Behavior
Here is a clear and concise description of what was expected to happen: cmake should build an e xe

## Actual Behavior

Cmake has errors and doesn't build

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/atugijivev

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
19 and 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
> cmake should build an e xe

cmake is not a compiler

**Comment by TsunamiOfTech** [comment]
Then what is the compiler

**Comment by garbear** [comment]
Kodi can be compiled with several compilers, including GCC, clang (part of LLVM), apple's Xcode and microsoft's MSVC.

Each compiler needs to know what files to compile, and Kodi used to have separate file lists for every compiler. You can see how forgetting to update one list would break that platform for everyone, so Kodi switched to CMake, which generates these file lists and the build files needed to run the compiler.

The team uses GitHub for development only, not general questions, so please use our forum for help in the future.
