### ISSUE TITLE
Kodi does not show images via dlna

### ISSUE THREAD

**Issue by pitsi** [xbmc/xbmc#21734]
### Describe the bug
I have a dlna server on my network and a couple of days ago I decided to add some photos to it.However, kodi, which can play stuff via dlna (already tested with audio and video files) does not show any of the image files.

## Expected Behavior
Kodi should show the image files from the dlna server.

## Actual Behavior
As seen in the screenshot below, kodi even fails to create the thumbnails for the images and it just goes black when it "plays" an image.

## Possible Fix
No idea.

### To Reproduce
1. Create a dlna server on the network and have it share some image files.
2. Enable kodi's upnp support in settings.
3. Add the dlna server as a source for image content
4. Browse to it and notice what I mention above.

### Debuglog
The debuglog can be found here:
http://ix.io/46Iv

### Screenshots 
Screenshot of kodi failing to even create thumbnails for the images.
![screenshot00001](https://user-images.githubusercontent.com/5880037/183054057-08474ab6-9968-40ef-9de2-a59d9a3eefcb.png)

## Additional context or screenshots (if appropriate)
As I said above, kodi does play video and audio files from that same dlna server. 
However, the images do "play" on other apps that support dlna, e.g
- vlc on windows, linux and android
- bubbleupnp on android 
- the dlna player on a smart tv (panasonic viera)

The dlna server mentioned above is minidlna (v1.3.0), but gerbera (v1.11) was tested too, althought it had the same results. Moreover, there are no errors in minidlna's log for kodi's failure to "play" them.

Although the errors in the log are identical for all the kodi versions mentioned below, the log above is from the libreelec 11 nightly x64 installation that comes with kodi 20a2. This installation will soon (= by August 15th) be removed (possibly in favor of libreelec 10 nightly x64), so no other log will be available from that one. 
The same applies for the libreelec 11 nightly installation on the rpi, although it will probably be available until early to mid September. 
So, if any fixes for it do reach kodi 20, please backport them for kodi 19 as well.

Last but not least, I would like to use the word "render" instead of "play" for the images above, if everyone agrees. Sounds better and more technical.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Tested on all these
Debian testing/unstable x64 with kodi 19.4
Libreelec stable 9.2.6 x64 with kodi 18.9
Libreelec stable 10.0.2 x64 with kodi 19.4
Libreelec nightly 11 x64 with kodi 20a2
Libreelec nightly 11 armv7l (rpi3b+) with kodi 20a2
Coreelec stable 9.2.8 aarch64 (amlogic s905 tvbox) with kodi 18.9

 - Kodi versions: 18.9, 19.4 and 20a2 as explained above

**Comment by pitsi** [comment]
Thank you for fixing it!
May I ask if the fix will be included in 19.x or if it is already included in 20a3 that was released yesterday?

**Comment by enen92** [comment]
Will be only of nexus beta 1. I don't think it's worth a backport because although "broken" it's actually a new feature.

**Comment by pitsi** [comment]
Oh ok :/ 
I won't keep the libreelec nightly installation until the beta so as to see it, so thanks anyway!

**Comment by enen92** [comment]
Yeap sorry - although at first impression it may seem "broken" it was actually unimplemented, making it technically a new feature. We can't backport features, only bug fixes. So, this is nexus material.

**Comment by pitsi** [comment]
Yesterdays libreelec nightly (5d1ef41) incudes a newer version of kodi than the alpha (20a3 + commit 9f7e9e0), so I tested it in a live enviroment and images via dlna actually work.

**Comment by enen92** [comment]
Glad to know it's working for you, thanks for confirming!
