### ISSUE TITLE
Upgrade selection controls on what Kodi video associated files can Export; "thumb, nfo, poster and fanart.jpg" files..

### ISSUE THREAD

**Issue by kleczerx** [xbmc/xbmc#21733]
### Describe the bug

Reference the following: Kodi Settings/Media/Library/Export Library/Separate/ **[Suggest having a single-drop-windows choosing items that may/or not be ouputed]

In my case I have 18,000 movie video files & 1,500 TV Serial sets. I regularily copy-out the Kodi Library's video peripheral files to my storage servers; these files include "*-thumb.jpg", *-poster.jpg, *-fanart.jpg, *.NFO, and more other files for which a NO/YES question is already floated. My focus is primarily on "*-thumb.jpg" which I do not want or need but am forced to download because it is  associated with *-poster.pg  & *-poster.jpg which I DO need; all three file types must be copied to obtain the two I require. My overall size of the *-thumb.jpg files put out is:   72,000 files = 4.75 Gbit. I always need to delete/remove this afterwards. May I suggest a drop list to selected files and select whether to copy overtop older files and select only for Movies or only for TV Series. Selection should include whether this Export action involves 'only' Movies, 'only' TV Series OR both catagories. For now, it take a lot of time for this activity to complete, and it would be convenient to half the time spent by choosing only with one of the catagories. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Provide a more selective drop window of what the user wants to complete in the Movie/TV Series catagory by deselecting what now is an unnecessary requirement by the KODI settings.

## Actual Behavior

After backing up the three fanart files, I must manually delete 72,000 thumb.jpg files off my server which take a lot of time.

## Possible Fix

To correct, have a drop menu to select which files to copy and select whether only for Movies and/or Tv Series.

### To Reproduce

1. NA
2. NA
3. NA

### Debuglog

The debuglog can be found here:
NA

### Screenshots
Here are some links or screenshots to help explain the problem:

NA

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Please use the forum for feature requests, we only track actual bugs on GitHub.
Thanks
