### ISSUE TITLE
AV1 thumbnail generation for videos - Kodi v20 (Nexus)

### ISSUE THREAD

**Issue by rmkimathi** [xbmc/xbmc#21741]
Thumbnails for AV1 videos that are not added in the library not being generated.

 - Kodi version: 20.0-ALPHA2 (19.90.705) Git:20220807-bb1f94eca9

## Expected Behavior
 Works for common video codecs.

![h265](https://user-images.githubusercontent.com/13484308/183465375-ed7b9951-3dc3-4110-a360-cbae779d2622.png)

## Actual Behavior
Does not work for AV1 video codec.

![av1](https://user-images.githubusercontent.com/13484308/183465441-062dde8c-c10b-489c-864d-6fa92621ace9.png)

### Environment
Used Operating system:

 - [x] Android TV
 - [x] Ubuntu 22.04
 - [x] Windows 11

**Comment by CastagnaIT** [comment]
Confirmed

sample test1: https://test-videos.co.uk/vids/sintel/mp4/av1/1080/Sintel_1080_10s_30MB.mp4
sample test2: https://woolyss.com/f/caminandes-1-llama-drama-av1-opus.webm

log: https://paste.kodi.tv/meyoqurixe.kodi

could be a problem in our ffmpeg version but im not sure
maybe someone of team ffmpeg maintainer know better

**Comment by rmkimathi** [comment]
Thank you for fixing. 

Tested working in Ubuntu:
Kodi Media Center 20.0-ALPHA3 (19.90.710) Git:20220911-22c74348eb
