### ISSUE TITLE
Kodi crashes if current freq of CPU 0 is not available

### ISSUE THREAD

**Issue by KOPRajs** [xbmc/xbmc#21747]
### Describe the bug

Kodi crashes upon opening the CPU info page in Settings if it can't read from _/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq_ on Linux.

In short, there are systems with multiple CPUs where disabling some of the CPUs is favorable. On older kernels reading from the _/sys/devices/system/cpu/cpuX/cpufreq/scaling_cur_freq_ of the disabled CPU was returning simply zero or last known value. Currently it returns _read error_ and that causes Kodi to crash. 

Please read more information here:
https://github.com/LibreELEC/LibreELEC.tv/issues/6758

## Expected Behavior

Kodi doesn't crash.

## Actual Behavior

Kodi crashes.

## Possible Fix

Don't expect the CPU 0 to be the main CPU and to be always online. Before trying to read from _/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq_ we should check whether the CPU 0 is actually online by reading _/sys/devices/system/cpu/cpu0/online_. If it is not online, then try CPU 1, 2, 3 etc. until we find CPU which is online and then read all the CPU info from it.

### To Reproduce

1. run "_echo '0' > /sys/devices/system/cpu/cpu0/online_"
2. open "Settings" -> "System information" -> "CPU"
3. Kodi crashes on affected platforms (depends on the Linux kernel)

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 11 (RK3399)
 - Kodi version: 20.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by basilgello** [comment]
I recall something like this because I reported the kernel bug to Debian about cpufreq. Will dig more on it!

**Comment by KOPRajs** [comment]
This is still the issue on 20.0rc2. Kodi crashes when it cannot read current frequency of cpu0 on Linux.

**Comment by basilgello** [comment]
Thanks for heads-up!
