### ISSUE TITLE
Feature Request:  tvheadend: Match EPG data with complete played indicator

### ISSUE THREAD

**Issue by nanderer** [xbmc/xbmc#21750]
Hi,

when playing back TV recordings from my tvheadend server ive got the problem that kodi dosnt marks episodes as watched if i watched them. Reason is that my recording settings are keeping recording for the case of the case even 15 minutes after the show has official ended do to epg data.

So it would be nice if you could match the automatic generated viewed/ partitial viewed/ not viewedend indicator with the end of the epg data and not with the end of the recording. Also a nice feature for recording multiple entryes in a row would be automatic skiping to the exact position in the next recording when the reecording ends and the same time code is captured by a follow up...

with kind regards and keep up the good work.

ps: is it possible to synchronise the viewed status between multiple kodi instances over the local network?

**Comment by nanderer** [comment]
![grafik](https://user-images.githubusercontent.com/45161625/184475411-53705dd4-a1fa-48eb-8755-907557c19659.png)

all of tree shows have been viewed completely but it is indicated as not cause 15 minutes of the next show have not been viewed within that recording:

![grafik](https://user-images.githubusercontent.com/45161625/184475484-5bf68fa2-ab52-486b-b413-7e0e56580df8.png)


I—’
Iputzer, Sitcom, USA 2012, Altersfreigabe: Ohne Altersb..
3ang Theory
d-Feind-Dilemma, Sitcoi’ 2016, Altersfreigabe:ab....
1IE I
J2iJ2 ::z-i1!]—
12-08-2022 8:35:11
LorTleuy enrai
Date: Friday, 12 August 2022
I[
3ang Theory
‘:8:00
ration: 45:00
LJ
12-08-2022 8:10:07
Bob’s Burgers
irun]skUnstIer, Sitcom, USA 201 AItersfreabe: ab 6, Resume from 00:31:59
iay from beginning
3ang Theory
erungstakti.k, Sitco
I Aus Bob entspr/ngt eih F/uss (1)
Genre: Other / Unknown
Size: 952.0 MB
12-08-2022 7:44:14
Zeichentrickserie, USA 2013 * Tina konnt
Zeltiager ihrer Pfadflnder teilnehmen. D6
nachholen. Em groRer Campingausfiug r
ThLLLD___

**Comment by ksooo** [comment]
For this, the pvr.hts addon has a setting you need to enable.

**Comment by ksooo** [comment]
Please use the Kodi forum for feature requests.
