### ISSUE TITLE
Video playback is not started

### ISSUE THREAD

**Issue by setupio** [xbmc/xbmc#21757]
Video playback just is not started at some point. There is no clear sequence or specific content to reproduce. Exiting Kodi does not resolve the problem only device reset (until next time). Other players like VLC, etc. works for the same content at the same time.

Mi Box S, Android 9. Kodi 19.3.

Log file: https://gist.github.com/setupio/da6494bfd29210a50837cd81a32572ca

**Comment by thexai** [comment]
It doesn't seem like it's a concrete issue that can be reproduced and fixed but rather something that is yet to be determined. 

I recommend you open a post in the forum (https://forum.kodi.tv/forumdisplay.php?fid=164) where others can give ideas and help to troubleshoot.

> Mi Box S, Android 9. Kodi 19.3.

Last Kodi is v19.4

Even you can try install latest nightly (future v19.5) https://mirrors.kodi.tv/nightlies/android/arm/Matrix/
