### ISSUE TITLE
Visualalization Shadertoy 2D LED Spectrum bars out of focus

### ISSUE THREAD

**Issue by Aftergit** [xbmc/xbmc#21756]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using Visualization Shadertoy 2D LED Spectrum and switch to full screen the visualization (Bars) become out of focus (not always), this is not the case in Kodi Leia but occurs in Matrix and in Nexus versions

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

In focus bars

### To Reproduce

1. Switching back to home screen and back (several times ) it comes back in focus and the bars look how it supposed to be.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Matrix and Nexus

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.
![Screenshot 2022-08-14 120257](https://user-images.githubusercontent.com/88626814/184532151-d6209b39-a76b-44fd-ad7e-99f9ca763a1b.png)
*

**Comment by sarbes** [comment]
I'm certain it is a plugin bug. Please file the issue here: https://github.com/xbmc/visualization.shadertoy/issues

As for the issue itself, I think the performance detection is flawed. When going in or out of fullscreen, the detection is done. Sometimes it takes too long. It is skewing the render duration, ending in a low resolution frame buffer.

Also, attach a debug log next time.

**Comment by Aftergit** [comment]
I will stay on Leia this issue does not occur with that version.
