### ISSUE TITLE
Audio Improvement : Missing samples on pausing/resuming playback

### ISSUE THREAD

**Issue by nanderer** [xbmc/xbmc#21754]
Hi,

when i pause a video in mpv or vlc and play it again no vovel is missed, but on kodi i have to do space to pause and left (skip back 10s) space to resume playback because your playback system just obmits a couple thousand samples for no reason. I know it once was a system for embeded devices with low cpu capability and therebty sensefull to sync audio after decoding of frames was running smoth but for now i think you could just fix that by handling your multi-thread-syncronisation a bit different. Old VLC versions where not able to handle pause/play request instantainously, therby it took about one secound to pause/unpause playback, but even worse is kodis behaior, instantainosly starting video and then initialisation of audi odevice, if you even have to deinicialyse the audio output and thereby remove precached samples from the buffer of it (better is to just keep them) you should then start decoding of it before the time you stoped accordingly or just do it as vlc and mpv dose, do not deinicialyse audio at all. 

mplayer and thereby mpv has imho the best behavior, instead of syncing audio to the viedeo playback it just syncs video to audio, very good cause all clocking is handled by the audio device (only problem is if it is not clocking right but then you can detect that and switch over at startup of kodi)

if you dont have the low-level developers to fix/reimplement this just add an option that automaticly skips pack 3 secounds when resuming playback ;)

thanks a lot in advance and keep up the good work

**Comment by CastagnaIT** [comment]
When you open an Issue you have to fullfill the problem report as per:
https://github.com/xbmc/xbmc/issues/new/choose

so please edit your Issue by fullfill our template:
https://raw.githubusercontent.com/xbmc/xbmc/master/.github/ISSUE_TEMPLATE.md
or close it and open a new one correctly

**Comment by thexai** [comment]
This is an issue tracker, keep feature requests for the forum please.
