### ISSUE TITLE
feature request: tvheadend: count views to tvheadend server

### ISSUE THREAD

**Issue by nanderer** [xbmc/xbmc#21753]
Hi,

even when i view/watch a tvheadend recording using kodi the view count in the tvheadend database is not increased:

![grafik](https://user-images.githubusercontent.com/45161625/184504165-b9f54d9e-b5a4-4d1a-acec-80904bac8e79.png)

please fix that

thanks and keep up the good work

**Comment by enen92** [comment]
Please use the forum for feature requests, this is an issue tracker only.
Thanks

**Comment by ksooo** [comment]
The addon has a setting for this: server based view count. Enable this.
