### ISSUE TITLE
Latest 8-16/17 Kodi 20 not reading files in the file manager

### ISSUE THREAD

**Issue by EvilOneIsMe** [xbmc/xbmc#21768]
### Describe the bug

When I create a source in filemanager it can't see the .zip files in the directory, I reported this same problem a while back and it got fixed. The last two beta updates broke it again. The 8-15 dated one works fine the next two 8-16 and 17 doesn't work.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When installing from .zip it doesn't see the files in the directory.

## Actual Behavior

 Just shows an empty directory unless there is another directory in it and it will show up empty also.

### To Reproduce

1. add a source 
2. Try and look in the source (empty)
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by EvilOneIsMe** [comment]
Just cheked the 08-23-2022 ver same problem

**Comment by CastagnaIT** [comment]
you should try the build with name 20220815-e41fcd67

**Comment by ksooo** [comment]
> a possible candidate to be verified is PR https://github.com/xbmc/xbmc/pull/21761

Confirmed. Working on a fix...
