### ISSUE TITLE
Unable to add Kodi icon (flatpak version) to the Plank dock

### ISSUE THREAD

**Issue by tudo75** [xbmc/xbmc#21765]
### Describe the bug
With the latest version from Flathub I was unable to add Kodi icon to the Plank dock.

## Possible Fix
I solved adding a line to the desktop file:
```
StartupWMClass=Kodi
```
where Kodi must be the same value as in 
```
Name=Kodi
```

### Your Environment
Used Operating system:
 - Kodi version: flatpak 19.4-Matrix (latest stable from flathub)
 -  Kernel: 5.15.0-46-generic x86_64 
 -  Desktop: Xfce 4.16.0
 -  Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
 -  Plank 0.11.89

**Comment by razzeee** [comment]
It didn't work before, did it? Does it work with other flatpaks? Why are you opening an issue here and not on the plank repo is basically what I'm asking? :)

**Comment by tudo75** [comment]
Hi,
I didn't find the flatpak repo searching flatpak in repo list nor a branch.
I had the same issue with some apps  (flatpak and deb) and this trick solved.

**Comment by razzeee** [comment]
Then I would think it's an plank issue. As `StartupWMClass` is an old, x11 thing to match a running app with the corresponding desktop file.
