### ISSUE TITLE
Setting winsystem.ishdrdisplay always reset to True after Kodi restart

### ISSUE THREAD

**Issue by wawa79** [xbmc/xbmc#21767]
### Describe the bug
The winsystem.ishdrdisplay setting does not seem to be saved by Kodi in the guisettings.xml file.

Here is a clear and concise description of what the problem is:

When I set the setting to False, it resets to True (the default value) after Kodi is restarted.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When I set the setting winsystem.ishdrdisplay, I expect the value to be retained after Kodi is restarted.

## Actual Behavior

When I set the setting to False, it resets to True (the default value) after Kodi is restarted.

## Possible Fix

Ensure the setting is actually saved in the guisettings.xml file.

### To Reproduce

1. Start Kodi
2. Navigate to Settings > Player
3. Untick the option "Switch display to HDR when playing HDR content"
4. Restart Kodi
5. Check that the setting is ticked again (should be unticked)

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ X ] Windows 10 
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4
 - Windows 10  version 10.0.19043.1889

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Tested and not reproduced:

This is after change setting to "False" and restart Kodi:

![screenshot00000](https://user-images.githubusercontent.com/58434170/185783044-26840ba1-2b2d-4747-b01d-94235dbee9a9.png)

Also value is saved in guisettings.xml:
![guisettings](https://user-images.githubusercontent.com/58434170/185783060-f48168b4-1af6-4fea-9fdd-14ebc30ceb58.png)


> 3. Untick the option "Switch display to HDR when playing HDR content"

This option not exist, I guess you mean "Use display HDR capabilities"

**Comment by wawa79** [comment]
> This option not exist, I guess you mean "Use display HDR capabilities"
Yes, the option above is the the one I was talking about.

Indeed, the buggy behaviour seems to have disappeared today. Might it be due to changing Windows HDR settings and graphic card settings in such a way that Kodi or Windows got lost? The PC was restarted and the bug is gone.

I am also swapping rendering method on the fly with jsonrpc depending on the video format being played as HDR 10 bits requires Pixel shader to run on my setup and DXVA is needed to ensure proper deinterlacing of PVR TV.

Sorry for the false alert...
