### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by brnwlshubh** [xbmc/xbmc#21772]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Want to run kodi on Tizen OS.

## Actual Behavior

Not able to find way to install

## Possible Fix

Searched all around but didn't find any solution.

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Tizen OS
 - Kodi version: Not insalled yet

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
This is an issue tracker, keep feature requests for the forum please.
