### ISSUE TITLE
[Suggestion] Use hidden local information files (Windows)

### ISSUE THREAD

**Issue by tonyrulez** [xbmc/xbmc#21774]
**Problem:** For future proofing, backup and several other reasons it's good to have local information (nfo, artwork) saved for your media, either be it exported by KODI or scraped manually with a 3rd party app like Ember Media Manager. However this leaves your media library folder cluttered with nfo and jpg files, 2-3 or even more times as much files generated as you have video files. Navigating through the file system is painstaking.

On Windows this could be solved by hiding all these files with applying the hidden attribute.

Unfortunately KODI cannot scrape hidden files.

**Suggestion:** allow hidden metadata files to be scraped by KODI.

**Comment by thexai** [comment]
This is an issue tracker, keep feature requests for the forum please.
