### ISSUE TITLE
Misinterpretation of Authorization header in http request

### ISSUE THREAD

**Issue by ELDiablO59152** [xbmc/xbmc#21773]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello,
I am figuring out a pretty nasty bug.
I need to add a JWT inside the http request as an authorization to play a video but the way it is parsed in the CurlFile::ParseAndCorrectUrl() function causes an additional colone after the header and my authorization server respond of course that this is an invalid JWT

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Server Logs :
> GET /videos.mp4 HTTP/1.1
> Host: 192.168.137.1:9091
> Range: bytes=0-
> User-Agent: Kodi/19.4 (X11; Linux aarch64) Debian GNU/Linux/11 App_Bitness/64 Version/19.4-(19.4.0)-Git:20220315-c9de65b422
> Accept: */*
> Accept-Encoding: deflate, gzip, br
> Accept-Charset: UTF-8,*;q=0.8
> Authorization: Bearer JWT

## Actual Behavior

Server Logs :
> GET /videos.mp4 HTTP/1.1
> Host: 192.168.137.1:9091
> Range: bytes=0-
> User-Agent: Kodi/19.4 (X11; Linux aarch64) Debian GNU/Linux/11 App_Bitness/64 Version/19.4-(19.4.0)-Git:20220315-c9de65b422
> Accept: */*
> Accept-Encoding: deflate, gzip, br
> Accept-Charset: UTF-8,*;q=0.8
> Authorization: Bearer JWT: 

Notice the ":" at the end of the JWT

## Possible Fix

I searched in the source code and I found interesting points :

xbmc/filesystem/CurlFile.cpp#L934
```
if (name == "authorization")
  CLog::Log(LOGDEBUG, "CCurlFile::{} - <{}> Adding custom header option '{}: ***********'",
      __FUNCTION__, url2.GetRedacted(), it.first);
else
  CLog::Log(LOGDEBUG, "CCurlFile::{} - <{}> Adding custom header option '{}: {}'",
      __FUNCTION__, url2.GetRedacted(), it.first, value);
}
```

I think the header isn't parsed as an authorization and so `it.first` collect `Authorization: Bearer JWT` and `value` equal to `null`, that's why it adds a colone.

xbmc/URL.cpp#L763
```
void CURL::GetProtocolOptions(std::map<std::string, std::string> &options) const
{
  CUrlOptions::UrlOptions optionsMap = m_protocolOptions.GetOptions();
  for (CUrlOptions::UrlOptions::const_iterator option = optionsMap.begin(); option != optionsMap.end(); option++)
    options[option->first] = option->second.asString();
}
```

/xbmc/utils/UrlOptions.cpp#L25
```
std::string CUrlOptions::GetOptionsString(bool withLeadingSeparator /* = false */) const
{
  std::string options;
  for (const auto &opt : m_options)
  {
    if (!options.empty())
      options += "&";

    options += CURL::Encode(opt.first);
    if (!opt.second.empty())
      options += "=" + CURL::Encode(opt.second.asString());
  }

  if (withLeadingSeparator && !options.empty())
  {
    if (m_strLead.empty())
      options = "?" + options;
    else
      options = m_strLead + options;
  }

  return options;
}
```

### To Reproduce

```
import xbmc
import xbmcgui
import xbmcplugin
import xbmcaddon

access_token = "JWT"
path = "http://192.168.137.1:9091/videos.mp4"
url = (path + "|Authorization: Bearer " + access_token)
play_item = xbmcgui.ListItem(path=url)

xbmcplugin.setResolvedUrl(_handle, True, listitem=play_item)
```

### Debuglog

The debuglog can be found here:
Kodi Logs :

`2022-08-22 20:14:34.562 T:12289   DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'Authorization: Bearer JWT: '`

Notice again the ": " at the end of the JWT

Putting "=" instead of ":"

`url = (path + "|Authorization= Bearer " + access_token)`

Produce this Kodi Logs

`2022-08-22 20:20:30.097 T:12289   DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'Authorization: ***********'`

Notice the "***********", don't really know why they aren't replaced.

### Links
Here are some links or screenshots to help explain the problem:

https://github.com/xbmc/xbmc/blob/7d8bc9ca8d8a9d18a45b31b781ba1a908b63e60e/xbmc/filesystem/CurlFile.cpp#L738

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

Operating system: debian 11 on raspberrypi 4
Kodi version: 19.4.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ELDiablO59152** [comment]
The only thing that works is by adding 2 "\n" url encoded to force the end of the request but it is a bit barbarian...
`url = (path + "|Authorization= Bearer " + access_token + "%0A%0A")`

Kodi Logs :
```
2022-08-23 11:15:56.577 T:3087    DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'authorization: Bearer JWT

                                                   : '
```

Server Logs :
> GET /videos.mp4 HTTP/1.1
> Host: 192.168.137.1:9091
> Range: bytes=0-
> User-Agent: Kodi/19.4 (X11; Linux aarch64) Debian GNU/Linux/11 App_Bitness/64 Version/19.4-(19.4.0)-Git:20220315-c9de65b422
> Accept: /
> Accept-Encoding: deflate, gzip, br
> Accept-Charset: UTF-8,*;q=0.8
> Authorization: Bearer JWT
> 
> :

**Comment by wsnipex** [comment]
: is not a valid char in the authorization token, the easiest fix is to base64 encode your jwt

**Comment by ELDiablO59152** [comment]
> 

Of course it's not and I don't want it to be there, that's why I report it as an issue.
If I encode my jwt, my server will answer that my jwt is incorrect as well.
This unepected colone comes from : `Adding custom header option '{}: {}'`

**Comment by vpeter4** [comment]
> url = (path + "|Authorization: Bearer " + access_token)

This is wrong: the correct syntax is `|header_name=header_value`. 

> This unexpected colon comes from : `Adding custom header option '{}: {}'`

This two lines are just for the logging.

**Comment by ELDiablO59152** [comment]
I already tried this of course here :

> Putting "=" instead of ":"
> 
> url = (path + "|Authorization= Bearer " + access_token)
> 
> Produce this Kodi Logs
> 
> 2022-08-22 20:20:30.097 T:12289 DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'Authorization: ***********'
> 
> Notice the "***********", don't really know why they aren't replaced.



`url = ("http://192.168.137.1:9091/video.mp4" + "|Authorization= Bearer " + access_token)`

Kodi :
`2022-08-24 10:02:38.717 T:2094    DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'Authorization: ***********'`

Server :
> GET /video.mp4 HTTP/1.1
> Host: 192.168.137.1:9091
> Range: bytes=0-
> User-Agent: Kodi/19.4 (X11; Linux aarch64) Debian GNU/Linux/11 App_Bitness/64 Version/19.4-(19.4.0)-Git:20220315-c9de65b422
> Accept: */*
> Accept-Encoding: deflate, gzip, br
> Accept-Charset: UTF-8,*;q=0.8
> Authorization:

**Comment by vpeter4** [comment]
Yes, and it works? Or not?

And you mentioned those `********`: the value is replaced to not expose private data in the logs.

**Comment by ELDiablO59152** [comment]
Of course not, you see that massive black hole after the 
> Authorization:

instead of  :
> Authorization: Bearer JWT

Maybe a strange misunderstanding of spaces

**Comment by ELDiablO59152** [comment]
Ow wait this seams to work :
`url = ("http://192.168.137.1:9091/video.mp4" + "|Authorization=Bearer " + access_token)`
Kodi :
`2022-08-24 10:18:26.331 T:2446    DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'Authorization: ***********'`
Server :
> GET /video.mp4 HTTP/1.1
> Host: 192.168.137.1:9091
> Range: bytes=0-
> User-Agent: Kodi/19.4 (X11; Linux aarch64) Debian GNU/Linux/11 App_Bitness/64 Version/19.4-(19.4.0)-Git:20220315-c9de65b422
> Accept: /
> Accept-Encoding: deflate, gzip, br
> Accept-Charset: UTF-8,*;q=0.8
> Authorization: Bearer JWT
> 


Thank you for all ! I will mark as solved but this space mistake isn't quite obvious when you are familiar with http request :')

**Comment by vpeter4** [comment]
As I wrote `header_name=header_value`: no space after equal sign.

**Comment by ELDiablO59152** [comment]
Yep that's why it wasn't working as expected, thanks !
