### ISSUE TITLE
Quick access to tone mapping parameter via keymaps

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [xbmc/xbmc#21770]
### Description
Would you, please, consider allowing quick access to the tone mapping parameter via keymaps? (like you do for subtitle delay)
I find myself tweaking its value quite often, and it's very tedious to do it from the Video Settings due to its placement at the bottom of the list.

The keymap could be something like this:
```
<FullscreenVideo>
    </keyboard>
        <up mod="ctrl,shift">ToneMapShiftUp</up>
        <down mod="ctrl,shift">ToneMapShiftDown</down>
    </keyboard>
</FullscreenVideo>
```

It would also be nice if you would allow changing the adjustment step for the tone mapping parameter via `advancedsettings.xml`. (ex: change its value from 0.10 to 0.5 for more granular control)

### Your Environment
 - Operating system: Windows 11 Pro 21H2 (Build 22000.856)
 - Kodi version: 19.4.0

**Comment by thexai** [comment]
This is an issue tracker, keep feature requests for the forum please.
