### ISSUE TITLE
RTSP playback doesn't start with Kodi 20 (but was working well with Kodi 19)

### ISSUE THREAD

**Issue by KlausHuber** [xbmc/xbmc#21796]
### Describe the bug
Here is a clear and concise description of what the problem is:

Playback from an IP camera (Reolink RLC-511W) with the RTSP procotol was working on Kodi 19.4.0, but doesn't work on Kodi 20 Alpha (19.90.705) anymore. Playback is started via a strm file with the RTSP URL inside (URL has the format rtsp://admin:mypassword@hostname:554/h264Preview_01_main).
When trying to open the strm file, I get a rotating spinner but playback doesn't start.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi 19 was able to play the stream so I expect Kodi 20 to play it as well.

## Actual Behavior

Playback doesn't start. It only shows the rotating spinner.

### To Reproduce

Reproducing might be hard without having a RTSP camera available. I'm happy to provide all possible details, I could even capture the stream (if that helps and if you let me know how to).
1. place URL in .strm file and Metadata in .nfo file. Place both files under the video folder.
2. open file in Kodi 20
3. playback doesn't work

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ehodatazun.kodi
The IP address:port in the Log is 127.0.0.1:1554 because there is a local SSH tunnel to the destination network. But this hasn't been a problem for Kodi 19 and works well on my Ubuntu System with VLC.

### Screenshots 
Here are some links or screenshots to help explain the problem:

I don't have screenshots of the rotating spinner - I'm not sure it might help :)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The IP address:port in the Log is 127.0.0.1:1554 because there is a local SSH tunnel to the destination network. But this hasn't been a problem for Kodi 19 and works well on my Ubuntu System with VLC.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Libreelec nightly running Kodi 19.90.705

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by a1rwulf** [comment]
Looking at the log it's not obvious that your stream is really ok.
```
2022-08-28 19:37:20.779 T:949     DEBUG <general>: Open - avformat_find_stream_info starting
2022-08-28 19:37:25.621 T:787     DEBUG <general>: ------ Window Deinit (Pointer.xml) ------
2022-08-28 19:37:50.645 T:949     DEBUG <general>: ffmpeg[0x43ef1e0]: [rtsp] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
2022-08-28 19:37:50.645 T:949     DEBUG <general>: ffmpeg[0x43ef1e0]: [rtsp] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
2022-08-28 19:37:50.645 T:949     DEBUG <general>: Open - av_find_stream_info finished
```
FFmpeg takes 25s to anaylze the stream and can't detect the resolution of the video.
Later in the log:
```
2022-08-28 19:38:10.690 T:949      INFO <general>: Process - eof reading from demuxer
2022-08-28 19:38:10.690 T:949      INFO <general>: CVideoPlayer::OnExit()
```
This ususally happens when we don't get data anymore.
I'll test an rtsp stream later today with current master to verify.

**Comment by KlausHuber** [comment]
I was able to play the stream with ffplay on my Ubuntu system (ffplay version 4.2.7-0ubuntu0.1):
https://paste.kodi.tv/ufapodohax

Unfortunately my libreelec doesn't have ffplay installed and I'm not sure which version it's using. How can I find out?

**Comment by enen92** [comment]
I wonder if this is actually a regression in ffmpeg due to the bump to 4.4.* in nexus. Also wondering if this could be already solved in ffmpeg 5.0.

You could try to use different versions of ffmpeg (via ffplay) on a VM or something similar if you want to dig further. Matrix uses v4.3.1 while Nexus is using v4.4.1.

**Comment by a1rwulf** [comment]
@KlausHuber can you post a debug log with ffmpeg component logging enabled of the failing case of your kodi installation?

**Comment by KlausHuber** [comment]
> @KlausHuber can you post a debug log with ffmpeg component logging enabled of the failing case of your kodi installation?

Here we go:
https://paste.kodi.tv/ibiwebeyok.kodi

**Comment by KlausHuber** [comment]
> I wonder if this is actually a regression in ffmpeg due to the bump to 4.4.* in nexus. Also wondering if this could be already solved in ffmpeg 5.0.
> 
> You could try to use different versions of ffmpeg (via ffplay) on a VM or something similar if you want to dig further. Matrix uses v4.3.1 while Nexus is using v4.4.1.

I just installed a Ubuntu 22.04 (which is shipped with ffmpeg 4.4.2) on a test system.
It can't play the stream either. But after enabling the verbose logging, I could identify the difference where it hangs: compared to ffmpeg 4.2, I don't get the line "UDP timeout, retrying with TCP".

I could get ffplay 4.4.2 to play the file if I add the parameter "-rtsp_transport tcp" to my ffmplay command.
Is there a way to add this parameter in Kodi (by configuration)?

**Comment by enen92** [comment]
Have you tried to play rtspt:// instead of rtsp://?

**Comment by KlausHuber** [comment]
> Have you tried to play rtspt:// instead of rtsp://?

Kodi doesn't play and tells me (in the logs): 
`CreateLoader - unsupported protocol(rtspt) in rtspt://USERNAME:PASSWORD@127.0.0.1:1554/h264Preview_01_main  `

ffplay errors out with 
`Protocol not found`

**Comment by enen92** [comment]
Yeap just a long shot without checking the code because I faced a similar issue a while ago (but was using vlc) for that use case. Kodi doesn't have anyway to specify the transport protocol, that needs to be implemented unfortunately.

**Comment by enen92** [comment]
@KlausHuber the pull request above (https://github.com/xbmc/xbmc/pull/21817) should provide a way for you to force the tcp transport protocol for your rtsp stream. Hopefully it'll fix the issue for you. Do you have any way of testing it?

Unfortunately your bug report sets the offending platform as linux, we can't really provide linux test builds (you'll have to bake the cake yourself). If you have some other way of testing this (e.g. windows, android, osx) I can provide you a link to a test build for feedback.

**Comment by KlausHuber** [comment]
Sure, I can test on Windows as well if you could provide me a Kodi build for that :)

**Comment by enen92** [comment]
win64 testbuild: https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220907-ef6f888c-rtsp_stuff-x64.exe

To force the tcp transport mode you'll have to create a strm file with the following contents:

```
#KODIPROP:rtsp_transport=tcp
rtsp://your_rtsp_stream_url
```

**Comment by KlausHuber** [comment]
> win64 testbuild: https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220907-ef6f888c-rtsp_stuff-x64.exe
> 
> To force the tcp transport mode you'll have to create a strm file with the following contents:
> 
> ```
> #KODIPROP:rtsp_transport=tcp
> rtsp://your_rtsp_stream_url
> ```

You are my heros! Thank you so much! :)
I can confirm that adding the KODIPROP line works with the given Windows build. And as expected, if I remove the line, the playback doesn't work.

Do you by any chance know if the Libreelec nightlies (https://test.libreelec.tv/11.0/Generic/Generic/) are always using the latest Kodi master?

**Comment by enen92** [comment]
@KlausHuber please leave the issue open, it'll be closed automatically once the PR is merge.

By the way, can you somehow try ffplay from ffmpeg version 5.0? It'd be nice to report this upstream but we have to reproduce this with the current ffmpeg version.
For that I guess 2 complete logs from ffplay are required: a failing one (5.0) and a working one (previous version in which you played the stream without any issue).

Cheers

**Comment by KlausHuber** [comment]
Sorry for being to fast in closing the issue.

Sure, I can try it with ffmpeg 5. 
Do I need to compile it on my own or is it sufficient to use any existing repo e.g. https://www.linuxcapable.com/how-to-install-ffmpeg-5-on-ubuntu-22-04-lts/

> PS: kodi is just one (the main) package of libreelec. It's not always on head of master but they follow it pretty closely.
Thanks for the info. I'll follow it there.

**Comment by enen92** [comment]
compiled packages will do, preferably those provided by ffmpeg: https://launchpad.net/ubuntu/+source/ffmpeg
Current stable version is 5.1.1

**Comment by KlausHuber** [comment]
Upstream ticket:
http://trac.ffmpeg.org/ticket/9914

**Comment by enen92** [comment]
thanks much!

**Comment by denics** [comment]
I am having this same error with libreelect and kodi 21 here is my log https://paste.libreelec.tv/evident-flamingo.log
