### ISSUE TITLE
Race condition in CGUIInfoManager causing an user-after-free

### ISSUE THREAD

**Issue by neo1973** [xbmc/xbmc#21791]
### Describe the bug
The problem is that `CGUIInfoManager::m_multiInfo` is modified from multiple threads causing a reallocation of the `std::vector`s internal buffer while a different thread has a reference to an object inside that buffer.

Here are the logs and Address Sanitizer output of two occasions:

#### Crash on startup

Debug log: https://gist.github.com/neo1973/1e72f91a0f5bd4d495e9088981cf0700
ASAN output: https://gist.github.com/neo1973/e2c546d82f0e87e870228c614491bf76

#### Crash while navigating through GUI:

Debug log: https://gist.github.com/neo1973/fd16b4f454fb3ac5a49c1408b7d80ae8
ASAN output: https://gist.github.com/neo1973/0960636f540c6c6f6860b3ee8fe40380

The issue is best reproduced when I launch Kodi with these ASAN options: `ASAN_OPTIONS=detect_stack_use_after_return=1:fast_unwind_on_malloc=0 ./kodi-wayland`
This makes the timings just right (on my machine) to trigger the bug within a couple of seconds, most of the time even before the GUI is up.

## Expected Behavior
No undefined behaviour that can cause crashes.

## Actual Behavior
Undefined behaviour and possible crashes.

## Possible Fix
Difficult. Simply protecting `CGUIInfoManager::m_multiInfo` with a `CCriticalSection` causes deadlocks. It doesn't matter if the `m_critInfo` one is reused or a separate `CCriticalSection` is added.

### To Reproduce

Happens immediately on startup or shortly after while browsing through the GUI. I don't think any particular steps are required to hit the problem.

### Debuglog

The debuglog can be found here: See above

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux, recently updated
 - Kodi version: Current master, commit 9c3a68f32e59dd25f0cacc35c47a88a5e5770990

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
@enen92  `CSkinTimerManager`'s worker thread calls into not threadsafe `CGUIInfoManager`! GUIInfoManager must not be called from other threads than the main thread.

**Comment by enen92** [comment]
I was not a big fan of having the skin timer evaluation in its own thread to be honest, it kinda foresee this would eventually happen. Screen timers just registers a few more info conditions into the infomanager, maybe we can simply register callbacks for them.
Will take a look but unfortunately I won't be near a computer until next week.

**Comment by ksooo** [comment]
My preferred solution would be to get rid of the thread in CSkinManager and to call the functionality currently located in `CSkinTimerManager::Process` from `CApplication::ProcessSlow()`.
