### ISSUE TITLE
egl: Compile failure as eglextchromium.h replaced by eglext_angle.h in mesa git

### ISSUE THREAD

**Issue by alanswanson** [xbmc/xbmc#21792]
### Describe the bug
_Here is a clear and concise description of what the problem is:_

With recent mesa git, its commit [egl: Remove eglextchromium.h and import eglext_angle.h](https://gitlab.freedesktop.org/mesa/mesa/-/commit/f5bb9dd738ace274c97507adea073b6c609469b2) has done what it states and removed the eglextchromium.h header causing  Kodi to fail to compile xbmc/windowing/X11/GLContextEGL.cpp which used that header.

## Expected Behavior
_Here is a clear and concise description of what was expected to happen:_

Compiles.

## Actual Behavior

Does not compile.

## Possible Fix

Quick fix is to replace `#include <EGL/eglextchromium.h>` with `#include <EGL/eglext_angle.h>` in xbmc/windowing/X11/GLContextEGL.cpp but we need to be backwards compatible.

However adding a cmake test fails to "find" eglext_angle.h as the cmake compile test fails due to EGLAPIENTRYP being undefined. The eglext_angle.h is missing an include for eglplatform.h (which xbmc/windowing/X11/GLContextEGL.h does so via including EGL/eglext.h which is probably normal setup). Cannot see a way to get cmake to create a compile test that includes both headers. Trying check_include_files just tests each header individually. (And check_include_file also gives an annoying cmake CMP0075 warning.)

```
diff -ur xbmc/cmake/modules/FindEGL.cmake xbmc-eglextheader/cmake/modules/FindEGL.cmake
--- xbmc/cmake/modules/FindEGL.cmake
+++ xbmc-eglextheader/cmake/modules/FindEGL.cmake
@@ -9,6 +9,7 @@
 # EGL_INCLUDE_DIRS - the EGL include directory
 # EGL_LIBRARIES - the EGL libraries
 # EGL_DEFINITIONS - the EGL definitions
+# HAVE_EGLEXTANGLE - if eglext_angle.h exists else use eglextchromium.h
 #
 # and the following imported targets::
 #
@@ -35,6 +36,11 @@
   set(EGL_LIBRARIES ${EGL_LIBRARY})
   set(EGL_INCLUDE_DIRS ${EGL_INCLUDE_DIR})
   set(EGL_DEFINITIONS -DHAS_EGL=1)
+  include(CheckIncludeFile)
+  check_include_file("EGL/eglext_angle.h" HAVE_EGLEXTANGLE)
+  if(HAVE_EGLEXTANGLE)
+    list(APPEND EGL_DEFINITIONS "-DHAVE_EGLEXTANGLE=1")
+  endif()

   if(NOT TARGET EGL::EGL)
     add_library(EGL::EGL UNKNOWN IMPORTED)
diff -ur xbmc/xbmc/windowing/X11/GLContextEGL.h xbmc-eglextheader/xbmc/windowing/X11/GLContextEGL.h
--- xbmc/xbmc/windowing/X11/GLContextEGL.h
+++ xbmc-eglextheader/xbmc/windowing/X11/GLContextEGL.h
@@ -13,7 +13,11 @@
 #include "threads/CriticalSection.h"

 #include <EGL/eglext.h>
+#ifdef HAVE_EGLEXTANGLE
+#include <EGL/eglext_angle.h>
+#else
 #include <EGL/eglextchromium.h>
+#endif
 #include <X11/Xutil.h>

 class CGLContextEGL : public CGLContext
```

### To Reproduce

1.  Install git mesa
2.  Compile Kodi

### Debuglog

From CMakeError.log with above check_include_file we get;
```
Determining if the include file EGL/eglext_angle.h exists failed with the following output:
Change Dir: CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/ninja cmTC_593f3 && [1/2] Building C object CMakeFiles/cmTC_593f3.dir/CheckIncludeFile.c.o
FAILED: CMakeFiles/cmTC_593f3.dir/CheckIncludeFile.c.o
/usr/bin/x86_64-pc-linux-gnu-gcc -DNDEBUG -Wall -o CMakeFiles/cmTC_593f3.dir/CheckIncludeFile.c.o
-c CMakeFiles/CMakeTmp/CheckIncludeFile.c
In file included from CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:
/usr/include/EGL/eglext_angle.h:162:20: error: unknown type name ‘EGLAPIENTRYP’
  162 | typedef EGLBoolean(EGLAPIENTRYP PFNEGLCREATESTREAMPRODUCERD3DTEXTUREANGLEPROC)(EGLDisplay dpy, EGLStreamKHR stream, const EGLAttrib *attrib_list);
      |
In file included from CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:
/usr/include/EGL/eglext_angle.h:163:20: error: unknown type name ‘EGLAPIENTRYP’
....REPEAT FOR ALL LINES WITH EGLAPIENTRYP...
ninja: build stopped: subcommand failed.
```

### Your Environment
Used Operating system: 

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo
 - Kodi version:19 and 20 affected.

**Comment by alanswanson** [comment]
Created angleproject bug [7617](https://bugs.chromium.org/p/angleproject/issues/detail?id=7617) but as eglext_angle.h has been around for five years there will be versions hanging about without the necessary header after it's fixed.

**Comment by enen92** [comment]
@alanswanson just got into this issue after updating mesa. I saw your bug report in angleproject and their response stating this header should not be included directly (basically that mesa is not using it properly). Have you tried to report this to upstream mesa?

**Comment by alanswanson** [comment]
The angleproject bug is still open so I was hoping an alternative angleproject developer might recognise the issue as valid regardless of the initial "_we don't support including eglext_angle.h_" response that ignores that it's still a obviously incorrect missing header include. Will open a mesa PR this week.

**Comment by alanswanson** [comment]
@basilgello I assume you're missing a "what" in your question but basically, the pain that is the angle projects [contributing code](https://chromium.googlesource.com/angle/angle/+/main/doc/ContributingCode.md) compared to a simple github or gitlab merge request.

**Comment by basilgello** [comment]
@alanswanson Your snippet was very helpful but you stopped one step before the goal ;) I changed your solution to test multiple includes reliably and pushed the PR under your name along with couple of fixes by myself :)
