### ISSUE TITLE
kodi20 webvtt Subtitles out of sync when using Netflex addon after recent update

### ISSUE THREAD

**Issue by monsoons** [xbmc/xbmc#21807]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using Netflix addon, webvtt subtitles appear about 0.1-0.4 seconds faster.
Rolling back to previous kodi20 release before around Aug 20, no sync mismatch. 
Tested on Windows10 PC, Shield TV pro, amazon firestick 4k max.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Perfect sync.

## Actual Behavior

As above.

## Possible Fix

I don't know.

### To Reproduce

1. Install latest kodi20 release and Netflix addon.
2. check subtitles sync several times.(At first, it may seem that the subtitles are in sync. So plz test repeatedly and carefully 'cause very slight sync mismatch)

### Debuglog

The debuglog can be found [here:]
[kodi.log](https://github.com/xbmc/xbmc/files/9486314/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 pro, Android 11, Android 9
 - Kodi version: kodi20 latest release

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
at least from the log you are using kodi nightly not the release version

you are testing "Handsome sibling" tvshow, what is the subtitle language selected?
have you tested other tvshows?

the current InputStreamAdaptive nexus release version is quite old
since you are using kodi nightly i think should be better if you download/install InputStreamAdaptive nightly from:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1035/1/artifacts
(this is a fixed version because ISA Nexus branch currently have bugged video resume)

make sure that:
- you have "sync playback to display" turned OFF in kodi video settings
- kodi subtitle GUI settings while in playback has "subtitle offset" set to 0

i tried on Windows and android with shield but i see subtitles synced to video, so im not able reproduce it

**Comment by monsoons** [comment]
Thank you very much for your comment and effort to check.
I've tested numerous tv shows and movies like spiderman no way home. All same results nightly version after around AUG 20.  I just installed inputstream adaptive ver 20.2.3 as you attached url on shield tv pro, but same mismatch on sync. Very slight sync mismatch about 0.1-0.3 sec on Eng, Korean subs... (Eng is harder to catch sync mismatch). Sync playback to display already off and subtitle offset also 0... It's weird if I roll back to nightly release before AUG 20, every sync is perfect. 

I have something to do now... so I'll test further with other settings later and if 
symptom persists, try to find ways to reproduce for you. Thank you.

**Comment by CastagnaIT** [comment]
wait dont do other tests, i think i have found the problem
a so little oversight in the code happened after  AUG 20 has rounded the seconds
thanks to point this date!
i will provide you a test build soon

**Comment by monsoons** [comment]
> wait dont do other tests, i think i have found the problem a so little oversight in the code happened after AUG 20 has rounded the seconds thanks to point this date! i will provide you a test build soon

That sounds great! Take your time~ Thank you.

**Comment by CastagnaIT** [comment]
Ready for Windows 64bit:
http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220905-10579df7-fix_time_variable-x64.exe

**Comment by monsoons** [comment]
> Ready for Windows 64bit: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220905-10579df7-fix_time_variable-x64.exe

I just tested 5 videos on netflix with this test build and the sync is now perfect. Easy way to check sync mismatch is comparing the video graphic text "Netflix Original Series" with subtitles. If you compare the actor's voice or some sounds like that with the subtitles, you may not notice the mismatch 'cause there's not so much difference in sync.

Thank you for your quick effort.
