### ISSUE TITLE
Kodi restart when trying to watch a local video and the mysql database is unavailable

### ISSUE THREAD

**Issue by Gates33** [xbmc/xbmc#21846]
### Describe the bug

Kodi crash/restart when trying to watch a local video and the mysql database is unavailable.
The video is on the local drive and wasn't scrapped.
The mysql server is not on the network. And wasn't when kodi started.
I've just launched it from the "file" menu.

Video from Youtube plugins are working fine.

When i remove the videodatabase/mysql settings from advancedsettings.xml, it's ok !

## Expected Behavior

Playing the video - not crashing :)

## Actual Behavior

Kodi crash/restart just after pushing "play"

### To Reproduce

1. Having network MySQL configured
2. Remove the server from the network
3. Play a local video

### Debuglog

2022-09-06 20:08:28.882 T:1161     INFO <general>: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2022-09-06 20:08:29.919 T:858     ERROR <general>: GetResumeItemOffset - Cannot open VideoDatabase
2022-09-06 20:08:29.934 T:858      INFO <general>: VideoPlayer::OpenFile: /storage/downloads/video.mkv
2022-09-06 20:08:29.938 T:1173     INFO <general>: Creating InputStream

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreElec
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
I don't believe this to be a bug, but more a user error.

If you remove access to the databases, being one of the major components that Kodi requires to operate, you have to expect that there will be problems.

You need to ensure that access to MySQL is always available. 
If you can't guarantee that, you need to revert to the default local SQL setup.

**Comment by Gates33** [comment]
I forget to precise : it's not really my setup :)
I moved, and my NAS is still in the box.

when kodi start, it search for database. It doesn't find, of course. But It starts.
playing video from youtube plugins is fine.
So I was expecting playing a local video file (not scanned) will be OK

**Comment by thexai** [comment]
If MySQL database is unavailable you need remove from advancedsettings and use local database
