### ISSUE TITLE
Passthrough output device randomly reverts from WASAPI to DIRECTSOUND, killing bitstream

### ISSUE THREAD

**Issue by 4rev4** [xbmc/xbmc#21852]
### Describe the bug
Here is a clear and concise description of what the problem is:

I use Kodi on Windows in combination with a Denon AV receiver that is capable of playing all manner of bitstreamed audio formats up to and including Dolby Atmos.  In order for formats like Dolby Atmos to work, you must select "WASAPI: HDMI - DENON-AVRHD" in Settings -> System -> Audio -> Passthrough output device, and then tick the checkboxes for the formats your receiver supports.  In my case, all of them.

I leave "Audio output device" in the same area (System -> Settings -> Audio) set to "DIRECTSOUND: HDMI - DENON-AVRHD" as this provides the best compatibility for Kodi interface sounds.  However, this is a separate setting from "Passthrough output device"

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The passthrough output device in Settings -> System -> Audio should keep its setting.

## Actual Behavior

About once a month, I find that Kodi has stopped bitstreaming and is instead sending linear PCM audio, often downmixed (such as in the case of Dolby Atmos.)  The cure is always the same: I have to go into the settings and change "Passthrough output device" under System -> Audio back to WASAPI, as it has changed to DIRECTSOUND.

### To Reproduce

1.) Set Kodi passthrough output device to WASAPI.
2.) Use it for a few months.
3.) Observe that at random intervals, it will change itself to DIRECTSOUND.

### Debuglog

The debuglog can be found here:

I can't figure out how to generate this, any assistance would be appreciated.

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 21H2
 - Kodi version: 19.4

I am currently using Windows 11 21H2 and Kodi 19.4, however this issue has persisted across Windows 7, Windows 10, and Windows 11.  It has affected every version of Kodi 19.x including the most recent release at this time, 19.4.  It has done this on three different HTPCs (one Win 7, one Win 10, and my current Win 11 setup.)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
please provide full kodi debug log of when this happens

**Comment by Juniorzito8415** [comment]
> ## Informe de error
> ### Describa el error
> Aquí hay una descripción clara y concisa de cuál es el problema:
> 
> Uso Kodi en Windows en combinación con un receptor Denon AV que es capaz de reproducir todo tipo de formatos de audio de transmisión de bits hasta Dolby Atmos incluido. Para que funcionen formatos como Dolby Atmos, debe seleccionar "WASAPI: HDMI - DENON-AVRHD" en Configuración -> Sistema -> Audio -> Dispositivo de salida de paso, y luego marque las casillas de verificación de los formatos compatibles con su receptor. En mi caso, todos ellos.
> 
> Dejo "Dispositivo de salida de audio" en la misma área (Sistema -> Configuración -> Audio) configurado en "DIRECTSOUND: HDMI - DENON-AVRHD" ya que esto proporciona la mejor compatibilidad para los sonidos de la interfaz Kodi. Sin embargo, esta es una configuración separada de "Dispositivo de salida de paso"
> 
> ## Comportamiento esperado
> Aquí hay una descripción clara y concisa de lo que se esperaba que sucediera:
> 
> El dispositivo de salida de transferencia en Configuración -> Sistema -> Audio debe mantener su configuración.
> 
> ## Comportamiento real
> Aproximadamente una vez al mes, encuentro que Kodi ha dejado de transmitir bits y, en cambio, envía audio PCM lineal, a menudo mezclado (como en el caso de Dolby Atmos). La cura es siempre la misma: tengo que ir a la configuración y cambiar " Dispositivo de salida de paso" en Sistema -> Audio de vuelta a WASAPI, ya que ha cambiado a DIRECTSOUND.
> 
> ## Posible arreglo
> ### Reproducir
> Pasos para reproducir el comportamiento:
> 
> 1.) Establezca el dispositivo de salida de transferencia de Kodi en WASAPI. 2.) Úselo durante unos meses. 3.) Observe que a intervalos aleatorios, se cambiará a DIRECTSOUND.
> 
> ### Registro de depuración
> El registro de depuración se puede encontrar aquí:
> 
> No puedo entender cómo generar esto, cualquier ayuda sería apreciada.
> 
> ### capturas de pantalla
> Aquí hay algunos enlaces o capturas de pantalla para ayudar a explicar el problema:
> 
> ## Contexto adicional o capturas de pantalla (si corresponde)
> Aquí hay un contexto adicional o una explicación que podría ayudar:
> 
> ### tu entorno
> Sistema operativo usado:
> 
> * [ ] Androide
> * [ ] iOS
> * [ ] tvOS
> * [ ] linux
> * [ ] OSX
> * [X] Ventanas
> * [ ] Windows UWP
> * Versión/nombre del sistema operativo: Windows 11 21H2
> * Versión de Kodi: 19.4
> 
> Actualmente estoy usando Windows 11 21H2 y Kodi 19.4, sin embargo, este problema persiste en Windows 7, Windows 10 y Windows 11. Ha afectado a todas las versiones de Kodi 19.x, incluida la versión más reciente en este momento, 19.4. Ha hecho esto en tres HTPC diferentes (un Win 7, un Win 10 y mi configuración actual de Win 11).
> 
> _nota: una vez que se solucione el problema, le solicitaremos que lo actualice con nueva información o versiones de Kodi, en caso de que sea necesario. Team Kodi considerará su informe de problema; sin embargo, no haremos ninguna promesa de que el problema se resolverá._

**Comment by Juniorzito8415** [comment]
Kodi lento en xbox

**Comment by CastagnaIT** [comment]
english language only on github threads

**Comment by thexai** [comment]
Root cause of this is that audio device name configured in Kodi is not available during some instants due power on/off devices sequence or due HDMI handshake issues.

If audio device configured is not available then "by design" Kodi fallbacks to another available audio device.

Some workarounds are possible:

> you must select "WASAPI: HDMI - DENON-AVRHD" in Settings -> System -> Audio -> Passthrough output device

Not necessarily. You can select `WASAPI: default`  al long as one default audio device always exists (name not changes) is less probably Kodi can not access to audio device because "this name not exist". Then in Windows Control Panel settings configure the default audio device to one you want use. 

Kodi always points to "default" and Windows assigns "default" to a physical device.

> I leave "Audio output device" in the same area (System -> Settings -> Audio) set to "DIRECTSOUND: HDMI - DENON-AVRHD" as this provides the best compatibility for Kodi interface sounds.

This is not necessary. You can/should use the same `WASAPI: default` here. As long Kodi sounds are PCM they will be sent as is using the same WASAPI device (WASAPI can be used for everything passthrough / no passthrough).

**Comment by 4rev4** [comment]
> please provide full kodi debug log of when this happens

So this isn't going to be feasible unless the overlay can be disabled.  As mentioned, this issue happens about once a month at random.  I'm not going to watch content for a month straight with random white text overlaying it the whole time.

> Root cause of this is that audio device name configured in Kodi is not available during some instants due power on/off devices sequence or due HDMI handshake issues.
> 
> If audio device configured is not available then "by design" Kodi fallbacks to another available audio device.
> 
> Some workarounds are possible:
> 
> Always power on TV and AVR first Kodi last. Always power off Kodi first, TV and AVR last.

Stop and think about this for more than ten seconds. Am I supposed to educate everyone in my household on the correct sequence to power everything on and off?  Including children?  This is not a nuclear reactor.  It shouldn't require rigid adherence to a set way of energizing and de-energizing things.  You should be able to treat it like an appliance and just have it work, otherwise it can't really be taken seriously.


> > I leave "Audio output device" in the same area (System -> Settings -> Audio) set to "DIRECTSOUND: HDMI - DENON-AVRHD" as this provides the best compatibility for Kodi interface sounds.
> 
> This is not necessary. You can/should use the same `WASAPI: default` here. As long Kodi sounds are PCM they will be sent as is using the same WASAPI device (WASAPI can be used for everything passthrough / no passthrough).

It actually is necessary as I mentioned for the "best compatibility".  While WASAPI can work, DIRECTSOUND works better.  Why? Because of the HDMI silent stream bug.  I use a program called Sound Keeper to keep the HDMI audio stream from going into a sleep state.  If you don't do something like this, the first X seconds of any interface sound or video is cut off while the AVR figures out what audio format is being played.

And yes, I'm aware that the exact functionality Sound Keeper provides is built into Kodi.  But that doesn't fix the same problem happening on the computer when Kodi isn't being used, for example playing YouTube video through FIrefox.

So again, the best compatibility - the most seamless experience - is using a combination of Sound Keeper and Kodi's interface sounds in "DIRECTSOUND" mode.  You get no missing audio or pops from the sound system when using an AVR.
 
> If all of the above is not enough, you can disable all audio devices from Windows > Device Manager except the one you want to use. Kodi cannot switch to another audio device if there is only one.

I had already done this to prevent other issues.  The only sound device that's enabled is "DENON-AVRHD".

Also, I saw you marked this as working "by design".  All due respect, that's ridiculous.  If you specify an output setting and it gets changed with no notice to the user, that's a bad design.

Understand that there's a difference between failing gracefully (e.g. waiting for the device to come back, or asking the user to select a new device) and failing silently/unintuitively.

**Comment by 4rev4** [comment]
You can't be serious. This is a real problem, and the solution isn't to ignore it.

**Comment by a1rwulf** [comment]
Meanwhile you might have figured out that Kodi is developed by volunteers - while the situation might not be perfect, you've been given several workarounds and your attitude is not exactly conducive to get anyone of our very small team to improve your situation.
As our code base is open source, you are very welcome to contribute your proposed solution.

**Comment by 4rev4** [comment]
If you acknowledge that there are workarounds, then you acknowledge there's a problem.

Why acknowledge there's a problem and then also shut down discussion of it and claim it's working as designed?

You're just discouraging anyone else that has this same problem from coming here and trying to seek improvement.  They'll see that no one cares and move on to something else.

**Comment by CastagnaIT** [comment]
@4rev4 please before test by set `WASAPI: default` and let we know

**Comment by chchia** [comment]
> @4rev4 please before test by set `WASAPI: default` and let we know

I also having the same problem as TS, just that it is not random but almost always replicable, please refer here
https://github.com/xbmc/xbmc/issues/21852

also i notice setting to WASAPI:default did not help, at least for my case.

**Comment by smvicente** [comment]
Same problem here. 

Using "WASAPI:default" doesn't help either, and it seems to happen randomly.

**Comment by thexai** [comment]
>  is not random but almost always replicable

So you can provide a debug log, but you haven't

**Comment by 4rev4** [comment]
This just happened to me again for the first time since reporting this.  It's been three months, but sometimes it's one month or two weeks or whatever.  Just random.

If anyone has a suggestion on how to capture logs without having white text on my screen for up to three months, I'm all ears.  I'd love to help.

**Comment by thexai** [comment]
Just create advansedsettings.xml text file in userdata with:

```
<advancedsettings>
    <loglevel>2</loglevel> 
</advancedsettings>
```

See:  https://forum.kodi.tv/showthread.php?tid=323719&pid=2665078#pid2665078

**Comment by davidXdav** [comment]
> 
> ### To Reproduce
> Steps to reproduce the behavior:
> 
> 1.) Set Kodi passthrough output device to WASAPI. 2.) Use it for a few months. 3.) Observe that at random intervals, it will change itself to DIRECTSOUND.

I noticed this on my machine but I identified the problem. Every few weeks/months Intel released a new driver for my HD630 in the past which was installed via Windows update. After the graphics driver update the sound settings reverted to DIRECTSOUND instead of my WASAPI: configuration. This problem seems to heavily depend on the underlying Windows configuration. 
My solution was to disable driver update via Windows Update, manually install and correct sound settings afterwards. Since then I have no "random" change of WASAPI to DIRECTSOUND

Small overview of the relevant parts of my setup:
OS: Win 10 22H2
Graphics: Intel HD630
Kodi: 19.5
Output config: DisplayPort --> HDMI converter --> Pulseeight CEC adapter --> Denon AVR --> TV

**Comment by thexai** [comment]
Drivers auto-updating seems like a very reasonable explanation.

As commented previously Kodi fallback to other audio device when the current (in settings) is not available, has not required capabilities or is renamed.

**Comment by smvicente** [comment]
In my case, I have nVidia and the drivers are not auto-updated, but happens like once every 3 times. 

Is there any Kodi API call I could use to set the WASAPI option always using the Startup script? that would be enough for me.

**Comment by thexai** [comment]
Debug log?

**Comment by smvicente** [comment]
Here you have: https://drive.google.com/file/d/1-nh8K3GY9cgUQVaNg4aMS0lJbwpX887U/view?usp=share_link

In this case I turned the PC off the other day, then the next day I booted up Kodi again and it defaulted to Directsound, changed it manually to Wasapi, closed Kodi and collected the log.

Hope it helps!

**Comment by 4rev4** [comment]
> Drivers auto-updating seems like a very reasonable explanation.
> 
> As commented previously Kodi fallback to other audio device when the current (in settings) is not available, has not required capabilities or is renamed.

Windows Update is definitely not the culprit in my case.  I have driver updates disabled via O&O ShutUp10++.

I'm currently on Intel driver 30.0.101.1994.  We'll see if that's changed the next time it happens.

**Comment by projektilski** [comment]
I want to report the same behavior with 19.x and 20 versions.  It is not related to Windows Update or Nvidia update. It just, very often, reverts to DirectSound for unknown reasons. Even if I turn on the PC first, then TV and AVR, Kodi is always started last when there is a picture, which is impossible if AVR is turned off so there is no reason for KODI to think WASAPI - HDMI connection is not there. I will make sure to provide logs as soon as possible.
