### ISSUE TITLE
V20 Alpha 3, Combine Split Video Items - This Freezes Kodi

### ISSUE THREAD

**Issue by kleczerx** [xbmc/xbmc#21851]
The Windows version 20 Alpha 3, freezes when activating feature "Settings > Media > Video > Combine Split Video Items = ON. ONLY in version " kodi-20.0-Nexus_alpha3-x64.exe ".

Once activated, entering Videos > selecting an external media storage source, a Server ... at the outset Kodi takes longer, 2-minute duration, then normal (when feature is ON) to enter a folder... and similar timing period for subsequent folders as boring down to the video folders. Once withing the video folder movement becomes acceptable. YET, when exiting the video folders similar delays return as backing out into the main Kodi Menu.

This delay continues to occur when repeating the action and after restarting Kodi and repeating the action.

The ONLY fix is to deactivate the feature to OFF. I may suggest eliminating the entry entirely and use the "-cd2" or "part 2" coding as a workaround.

This problem has exited since the creation of Version 20. In version 19, I had used the afflicting feature continually and have since combined all my 2 or 3 or 4 part videos into a single video file to circumvent this situation. 

* Problem ONLY exist in: I see the problem in the Windows x64 Kodi version 20 ONLY. 
* No problem seen in: I also use the Alpha 3 version in a Nvidea Shield (kodi-20.0-Nexus_alpha3-arm64-v8a.apk), no unusual problem or delays were experienced.

 - [* ] Android    Nividea Shield    ...     kodi-20.0-Nexus_alpha3-arm64-v8a.apk
 - [ *] Windows  Windows 11 x64 ...     kodi-20.0-Nexus_alpha3-x64.exe

**Comment by enen92** [comment]
@kleczerx mind following the issue template. I mean, even if you don't provide a log the steps to reproduce and the expected behavior is important for someone to take this...

**Comment by CrazyEarthGuy** [comment]
This is still a major issue using Kodi v20.2 on a FireTV 4K Max, when using NFS to connect to a Synology ds920+ NAS.
I have about 2300 movies stored on my NAS in a movie folder (each in their own subfolder), and the NAS & FireTV are both connected using Ethernet. When I try to open/browse that movie folder from FireTV using Kodi, it takes about 45 seconds to open when "Combine split video items" is set to TRUE, but only a few seconds to open when set to FALSE.  That is the only setting I need to toggle to see the difference.
