### ISSUE TITLE
Thumb extraction fails for AV1 video stream in various containers

### ISSUE THREAD

**Issue by scott967** [xbmc/xbmc#21858]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi 20 A3 on Windows 10 with intel UHD Graphics 620 fails to generate a video thumb for various test files.  Filles are mkv or webm containers with AV1 video streams.  When Kodi is started, many ffmpeg errors are logged when Kodi attempts to obtain the video thumb.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi successfully extracts thumb image from video.

## Actual Behavior

Kodi logs ffmpeg errors.  Numerous errors are logged until extraction is determined to fail.

### To Reproduce

1.   The following test files were added to the video library and fail extraction
2. Chimera-2397fps-AV1-10bit-1920x1080-3365kbps.mkv
3.Morocco8K-8b-420-l.webm
4.HTML5_audio_video_tester_File_type_player_MIME_type_tester_caminandes_1_llama_drama_av1_opus.webm
HTML5 audio_video tester - File type player - MIME type tester.mp4

Note that all these files do play correctly

### Debuglog

The debuglog can be found here:
[https://paste.kodi.tv/onivoqiguy.kodi](https://paste.kodi.tv/onivoqiguy.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 10 x64 21h1
 - Kodi version: 20a3 Windows x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Does it work on latest nightly?

https://github.com/xbmc/xbmc/pull/21834

**Comment by scott967** [comment]
Sorry for the noise.  Somehow I missed that.  Built Kodi on Win x64 through 864ee77adc and extract is working.   But looking at the log, there seems to be an issue with seeking into the file, as the  extracted frame is right at the beginning of the stream.  Not sure that is a big problem, though might result in some thumbs with little or no detail in them.  Will close this and if complaints come in later can relook at it.
