### ISSUE TITLE
Add DXVA2/D3D11VA hardware accelerated AV1 decoding (v20 Nexus)

### ISSUE THREAD

**Issue by rmkimathi** [xbmc/xbmc#21875]
### Describe the bug

ffmpeg 4.4 already has DXVA2/D3D11VA hardware accelerated AV1 decoding, but Kodi hasn't used it.

## Expected Behavior

Intel Tiger Lake and Alder Lake Xe Graphics should use ff-av1-d3d11va (HW)

## Actual Behavior

Defaults to ff-libdav1d (SW)

## Possible Fix

Patch DXVA.cpp
Patch DXVA,h

FFmpeg gates av1 hwaccel for dxva by looking for DXVA_PicParams_AV1

https://source.winehq.org/git/wine.git/commitdiff/2f05dd0719e7dc51b48397cf441e139a0c9c0ec3

https://sourceforge.net/p/mingw-w64/mingw-w64/ci/aaec44a4cea27f1ee1212d82c76e1ab510f7ed49/

### Your Environment
Used Operating system:

 - [x] Windows

 - Operating system version/name: Windows 11
 - Kodi version: KodiSetup-20220916-07f9f23d-master-x64.exe

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
This is not a bug but feature request. 

Please, move to forum:
https://forum.kodi.tv/forumdisplay.php?fid=9

**Comment by rmkimathi** [comment]
I have contributed and followed up on AV1 in KODI the past 2 years. Since VAAPI AV1 and Android HW has already been integrated into v20 Nexus, AV1 hardware acceleration only missing out on Windows seems like a bug.
