### ISSUE TITLE
Kodi 20 Alpha2 not getting watched state of all videos

### ISSUE THREAD

**Issue by aindriu80** [xbmc/xbmc#21872]
### Describe the bug
Kodi 20 Alpha 2 is not showing watched progress of all videos, it only works for some videos.

## Expected Behavior
Kodi should read advancedsettings.xml on first start and connect to SQL database for the latest watch history of every video in library.

## Actual Behavior
Kodi reads the advancedsettings.xml on first start and retrieves the watch progress on some videos but not all.  

I'm using Kodi 20 Alpha 2 because it supports 120hz on my Samsung Galaxy Tab S7+ however if I use an older version of Kodi (e.g 19.4) and drop down to 60hz my watched progress for all videos is properly synced.

### To Reproduce

1. Ensure Kodi is closed
2. Start up Kodi 20 Alpa 2
3. Not watched progress on some videos but not all

### Debuglog

The debuglog can be found here:

https://pastebin.com/2MTTeLRT

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
I am running the following -> 

Kodi 20.0-ALPHA2 (arm64-v8a) (Android 5.0+)
https://www.apkmirror.com/apk/xbmc-foundation/kodi/kodi-20-0-alpha2-release/kodi-20-0-alpha2-2-android-apk-download/download/?key=4f1e4d1fe1a6647021f7b5b1dd06d9017091b767

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 12
 - Kodi version: 20 Alpha 2

`<advancedsettings>
	<video>
		<playcountminimumpercent>99</playcountminimumpercent>
		<ignoresecondsatstart>10</ignoresecondsatstart>
		<ignorepercentatend>1</ignorepercentatend>
	</video>
	<network>
		   <buffermode>1</buffermode>	   
		   <cachemembuffersize>2000000000</cachemembuffersize> 
		   <readbufferfactor>5.0</readbufferfactor> 
	</network>
	
	<videodatabase>
		<type>mysql</type>
		<host>192.168.1.126</host>
		<port>3306</port>
		<user>kodi</user>
		<pass>kodi</pass>
	</videodatabase>

	<musicdatabase>
		<type>mysql</type>
		<host>192.168.1.126</host>
		<port>3306</port>
		<user>kodi</user>
		<pass>kodi</pass>
	</musicdatabase>
	
	 <videolibrary>
		<importwatchedstate>true</importwatchedstate>
		 <importresumepoint>true</importresumepoint>
	 </videolibrary>
	 
	
	<advancedsettings>
	    <loglevel>2</loglevel>  
	</advancedsettings>
	 
	
</advancedsettings>`

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@aindriu80 
We have moved onto Alpha 3. Do you experience the same issue in Alpha 3? How about in the latest nightly?

**Comment by thexai** [comment]
v20 uses a different database. i.e. If You watch a video in v19.4 an then opens v20 in another device, watched status is not synchronized. 

v20 database is created (migrated) from v19 first time that v20 client is used but from that point databases diverged and not synchronized. 

> I'm using Kodi 20 Alpha 2 because it supports 120hz on my Samsung Galaxy Tab S7

To avoid this same Kodi version needs be used on **all** devices.

To me this is not a bug, but a problem created by incorrect/inconsistent usage.

**Comment by aindriu80** [comment]
> 

Well, I don't understand it because some of the videos are synced and others aren't, Kodi 20 alpha 2 was reading the database but not every video.  It couldn't write though.

If it syncs some of the videos and not others it seems to indicate that it is using the same database.  Also, I didn't provide any other database login credentials so maybe you mean it's using a different table to store watch usage.

I know it's still alpha, l will try version 3, looking forward to release

**Comment by aindriu80** [comment]
I upgraded Kodi to V20 on all my devices and I have lost the watched state.  Better coding would have not have tied the watched state to a specific kodi version.

**Comment by lrusak** [comment]
> I upgraded Kodi to V20 on all my devices and I have lost the watched state.  Better coding would have not have tied the watched state to a specific kodi version.

It's tied to the database version (which typically gets bumped with Kodi version) we don't provide backwards compatibility with the video database so your Kodi installs need to be the same version.

**Comment by aindriu80** [comment]
ok
