### ISSUE TITLE
Cache issue with Dolby Atmos&Vision files 

### ISSUE THREAD

**Issue by PeppaTom** [xbmc/xbmc#21885]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I play video files that contain **BOTH** Dolby Atmos and Vision features, the video cache works abnormally : 
When I pause the video, the video cache starts to slowly build up, as I can see the little grey portion on the playback bar slow grows. But when I resume playback,  the cache(the grey portion) just disappears instantly. 
When I play the video without pausing, it seems that it won't cache at all or only very little. So I keep having stuttering issues during playback.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When I play videos that do not contain Dolby Atmos and Vision featuers at the same time (only either of them, or none of them), the cache works perfectly since I preset it by advancedsettings.xml

## Actual Behavior

The cache just won't work properly with files that contain both Dolby Atmos and Vision, which means however large I preset the video cache size, I always have stuttering issues.

## Possible Fix

Not to my knowledge

### To Reproduce

1. Play a video that contains both Dolby Atmos and Dolby Vision (ideally larger than 5GB, it's not obvious with smaller files) 
2. Pause the video, wait until the grey part that indicates cache is large enough to be seen on the playback bar.
3. Resume the video.
4. Poof, it's gone

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/uxudabepig.kodi

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Amazon Fire Stick 4K MAX.
 - Kodi version: Kodi V20 Alpla 3
I am playing videos on Kodi from my desktop PC. I've tried both uPnP and FTP connection. Same issue under both circumstances

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by PeppaTom** [comment]
> > I've tried both uPnP and FTP connection. Same issue under both circumstances
> 
> ```
> 2022-09-20 21:53:07.921 T:3898    DEBUG <general>: OnPlayMedia upnp://bb33f932-77c4-4f28-bee4-1d4f97759249/8-437/
> 2022-09-20 21:53:08.090 T:3898    DEBUG <CUPnPDirectory::GetResource>: resource protocol info 'http-get:*:video/mp4:DLNA.ORG_OP=01;DLNA.ORG_FLAGS=01700000000000000000000000000000'
> 2022-09-20 21:53:08.111 T:3898    DEBUG <general>: CPlayerCoreFactory::GetPlayers(http://192.168.0.107:10243/WMPNSSv4/996752376/0_OC00Mzc.mp4)
> ```
> 
> DLNA is not suitable for streaming big / high bitrate files such as 4K HDR10 / DoVi videos.
> 
> A primary network file system such as SMB or NFS must be used. It's recommended to use SMB if the media files are on Windows and NFS if the files are on a NAS or Linux-based server.
> 
> It is not necessary to make modifications in Kodi cache (advancedsettings) for streaming within the local network.

I just tried SMB connection this morning, the issue is the **SAME**. And I don't have the equipment to try NFS connection

**Comment by PeppaTom** [comment]
> > I've tried both uPnP and FTP connection. Same issue under both circumstances
> 
> ```
> 2022-09-20 21:53:07.921 T:3898    DEBUG <general>: OnPlayMedia upnp://bb33f932-77c4-4f28-bee4-1d4f97759249/8-437/
> 2022-09-20 21:53:08.090 T:3898    DEBUG <CUPnPDirectory::GetResource>: resource protocol info 'http-get:*:video/mp4:DLNA.ORG_OP=01;DLNA.ORG_FLAGS=01700000000000000000000000000000'
> 2022-09-20 21:53:08.111 T:3898    DEBUG <general>: CPlayerCoreFactory::GetPlayers(http://192.168.0.107:10243/WMPNSSv4/996752376/0_OC00Mzc.mp4)
> ```
> 
> DLNA is not suitable for streaming big / high bitrate files such as 4K HDR10 / DoVi videos.
> 
> A primary network file system such as SMB or NFS must be used. It's recommended to use SMB if the media files are on Windows and NFS if the files are on a NAS or Linux-based server.
> 
> It is not necessary to make modifications in Kodi cache (advancedsettings) for streaming within the local network.

What's more, when I play the video normally, by which I mean playing it as it goes, no pausing. I have terrible stuttering issues, no matter I put or not put an advancedsettings.xml there. My Desktop PC, my router, my amazom fire stick all support WiFi6. So I don't know how on earth can I play this video smoothly. By the way, again, this stuttering issue only happens to files that have both Dolby Atmos and Vision, regardless of the network file system. So I really hope you guys can look into this issue,

**Comment by arnova** [comment]
Please try disabling filecache via advancedsettings.xml and see if it makes a difference.

**Comment by PeppaTom** [comment]
> 

Did you mean <buffermode>3</buffermode> or <buffermode>4</buffermode> ?

**Comment by arnova** [comment]
3 (no buffer)

**Comment by PeppaTom** [comment]
> 3 (no buffer)

This has magically solves the issue, Thanks a lot ! 
Besides, I would like to provide more info which I think would be useful to you. I think this whole issue is caused by FFMPEG. On the playlist page, I can see the video info of each file at the bottom right e.g: 4K/1080p/720p or HDR or H.265. I believe this info is returned by FFMPEG. However, for the problematic videos, it always has no info at all displayed there. So I assume FFMPEG can't recongnize the video which makes Kodi unable to handle this video files properly. I am not familiar with FFMPEG but I think you may want to upgrade the FFMPEG core in Kodi in further releases if that's possible

**Comment by arnova** [comment]
I think that has to do with the Android Media Codec, not sure though. Instead of disabling cache you could also try increasing the readfactor and see how it goes....

**Comment by PeppaTom** [comment]
> I think that has to do with the Android Media Codec, not sure though. Instead of disabling cache you could also try increasing the readfactor and see how it goes....

Actually increasing the readfactor is the first thing I tried but it seems that this paramater is just ignored by Kodi. Even if I set it to 1000, my local network bandwith is just used 10-20% and I am sure my all devices are not the limitations here.

**Comment by arnova** [comment]
> > I think that has to do with the Android Media Codec, not sure though. Instead of disabling cache you could also try increasing the readfactor and see how it goes....
> 
> Actually increasing the readfactor is the first thing I tried but it seems that this paramater is just ignored by Kodi. Even if I set it to 1000, my local network bandwith is just used 10-20% and I am sure my all devices are not the limitations here.

Please provide another debug log to know for sure it's ignored.
