### ISSUE TITLE
Subtitles addon "OpenSubtiles.org" show all language

### ISSUE THREAD

**Issue by Nanomani** [xbmc/xbmc#21880]
### Describe the bug

after update Kodi (20220830-1ade57db99) to the next version Kodi (20220903-b9f72b53d5) service addon "OpenSubtiles.org" show subtiles in all language

## Expected Behavior

service addon "OpenSubtiles.org" must displayed only subtitle in french

## Actual Behavior

Subtitles in all languages ​​are displayed

## Possible Fix

install the last kodi version without this behaviour (20220830-1ade57db99)

### To Reproduce

1. install Kodi (20220903-b9f72b53d5) or newer
2. play movie
3. open menu to download subtitle
4. select service addon "OpenSubtiles.org"

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/oxinekexiw.kodi

### Screenshots 

without this behaviour : 

![2](https://user-images.githubusercontent.com/3939543/190931265-2800e41c-790d-493c-807b-a30450ca2ca6.jpg)

with the behaviour : 

![2b](https://user-images.githubusercontent.com/3939543/190931278-3f1d1f83-c8b4-4aa4-86f6-1fa4bd5be5fb.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

![2022-09-19_000812](https://user-images.githubusercontent.com/3939543/190931196-ebaafff3-27a7-4adf-94c9-541f2ee1189e.jpg)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 x64
 - Kodi version: Nexus (20220903-b9f72b53d5)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
I cannot reproduce this in latest master.

**Comment by Nanomani** [comment]
Ok thanks for your answers. 
It is strange I have the same behaviour with Libreelec : 

- Generic.x86_64-11.0-nightly-20220909-89decb6.img.gz is ok

- Generic.x86_64-11.0-nightly-20220910-f329064.img.gz has the same behaviour
     ( 2022-09-10 (f329064):	[#6883]	[le11] kodi: update to 20.0a3-Nexus] )

I have the same setting / addons in all my plateform.
So I will make some more test from scratch to understand where is the side effect.

**Comment by Nanomani** [comment]
I have found something. 

I have make a test from scrtach with the minimal custom setting.
only service addon "OpenSubtiles.org" added 
"french" set in settings / player => subtitles => Language to dowload subtitles for 

![2022-09-19_113717](https://user-images.githubusercontent.com/3939543/190990239-06369207-9711-4a14-b3e9-53b6075c3a53.jpg)

if I download kodi "french" language => there is the behaviour 
if I uninstall kodi "french" language => all is ok

**Comment by enen92** [comment]
Thanks, now I could reproduce.

**Comment by enen92** [comment]
@CastagnaIT this is a regression on this commit: [e0c702e8425b4cd2387fbc9e2171923f082e9517](https://github.com/xbmc/xbmc/commit/e0c702e8425b4cd2387fbc9e2171923f082e9517)

**Comment by CastagnaIT** [comment]
the problem is easily reproducible by calling on python addon
`ret_value = xbmc.convertLanguage("French", xbmc.ISO_639_1)`
that istead return the language code return None

when its executed kodi perform reverse lookup, and works good until here:
https://github.com/xbmc/xbmc/blob/master/xbmc/utils/LangCodeExpander.cpp#L379-L381
the language code is found and also fill "code" variable string but
for some reason when this condition executed `if (!code.empty())` weird thing happens that i dont understand like the return not works

i will need to try build kodi as debug in hoping the debugger works better
