### ISSUE TITLE
Centraliser le fichier "userdata"

### ISSUE THREAD

**Issue by Djej30** [xbmc/xbmc#21897]
Bonjour,
J'utilise kodi sur plusieurs appareils chez moi (box Raspberry sous libreelec (kodi principal),  tablette et smartphone Android, pc Windows ).
Ces appareils sont tous connectés sur une freebox, à laquelle j'ai installé un disque dur, auquel j'ai accès en smb.
J'ai copier mon fichier "userdata" de mon kodi principal sur le disque de la freebox .
Je souhaite que chaque appareils utilise ce fichier à la place du fichier en local pour avoir mon profile partout.
Merci à vous

**Comment by arnova** [comment]
I'm sorry, we can only provide support in English.

**Comment by chewitt** [comment]
Support forum is here: https://forum.kodi.tv .. merci!
