### ISSUE TITLE
Kodi-20.0-Nexus_alpha3 nightly dated 20220921 has a problem with searching for subtitles

### ISSUE THREAD

**Issue by AdiOpi** [xbmc/xbmc#21898]
Kodi-20.0-Nexus_alpha3 nightly dated 20220921 has a problem with searching for subtitles

Napiproject.pl - not searching for subtitles
Napisy.24.pl - not searching for subtitles
OpenSubtitles - work fine.

In Kodi-20.0-Nexus_alpha2 version everything worked fine.

**Comment by CastagnaIT** [comment]
Issues must be opened by using our template accessible by using "New issue" button
you can edit and fullfill all required fields by using Problem report template or close and open a new one correctly

**Comment by enen92** [comment]
If one addon works fine and another doesn't it means it's an addon problem as the the same API is used for all of them to populate the subtitle list available for download.
