### ISSUE TITLE
Kodi-20.0-Nexus_alpha3 has a problem searching for subtitles

### ISSUE THREAD

**Issue by AdiOpi** [xbmc/xbmc#21895]
Kodi-20.0-Nexus_alpha3 has a problem with searching for subtitles

Napiproject.pl - not searching for subtitles
Napisy.24.pl - not searching for subtitles
Opensubtitles.org - searches for subtitles but not based on language (in all languages of the world)

In Kodi-20.0-Nexus_alpha2 version everything worked fine.

**Comment by fuzzard** [comment]
Closing as duplicate of https://github.com/xbmc/xbmc/issues/21880
