### ISSUE TITLE
Kodi shutters on reopen when gone in Windowed mode to macOS native fullscreen and reopened

### ISSUE THREAD

**Issue by whitebear60** [xbmc/xbmc#21891]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi interface is shuttering up and down after closing the application in macOS native fullscreen mode in Windowed Kodi mode and re-opening again.
macOS 12.5.1
Kodi 19.4 (Git 20220302-e12e66e019)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should launch without any graphical artifacts

## Actual Behavior

Kodi interface is shuttering when relaunching and goes back to normal when switching full-screen mode on and off

### To Reproduce

1. Enable Display mode Windowed in Settings - System - Display
2. Enter macOS native fullscreen mode with a green button in the application menu bar
3. Relaunch Kodi (looks like no matter you close via Cmd+Q or Kodi's Power Options Exit button
4. See interface shuttering

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/okotekixek.kodi
kodi.old.log can be found here:
https://paste.kodi.tv/ewapowuriv.kodi

### Video 
Here are a video reproduction that shows a problem:

https://youtu.be/Cp_QZ8s4-rQ

## Additional context or screenshots (if appropriate)
Here are system information screenshots that might help:

<img width="1440" alt="Знімок екрана 2022-09-21 о 18 56 07" src="https://user-images.githubusercontent.com/42472132/191553098-b7f6ac2c-732a-4af4-9b24-897b95540033.png">
<img width="1440" alt="Знімок екрана 2022-09-21 о 18 56 19" src="https://user-images.githubusercontent.com/42472132/191553109-d55cbf4c-7d7a-441a-9e34-47a2c66f9070.png">
<img width="1440" alt="Знімок екрана 2022-09-21 о 18 56 27" src="https://user-images.githubusercontent.com/42472132/191553116-2c221a8d-2805-4094-a6b9-c8304ff0a035.png">

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [X] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS 12.5.1
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
This is fixed in omega, no fix will be done for v20
