### ISSUE TITLE
subtitles don't follow the Bottom of the Video setting placement 

### ISSUE THREAD

**Issue by DoomSlayer10K** [xbmc/xbmc#21905]
### Describe the bug
Here is a clear and concise description of what the problem is:

text based subtitles appear out of video borders even after setting vertical margin to zero. The settings bottom of the video is not working

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Subtitles always appear between the video frame when Bottom of the video placement is chosen, no matter what the aspect ratio of video is

## Actual Behavior

subtitles appear in a fixed place in every type of video, overlapping with video borders and affecting visibility of subtitles 

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 and Android 12
 - Kodi version: Nexus 20 Pre release 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DoomSlayer10K** [comment]
https://imgur.com/a/BgZT6Fp

**Comment by sarbes** [comment]
No screenshot or log, and a outdated build is used.

Please redo the report with a recent nightly, as there were numerous changes in this area recently. Also, provide a debug log, a screenshot and detailed descriptions about the formats used.

Otherwise, no assesment can be made and the issue will be closed.
