### ISSUE TITLE
Replaygain settings not applied until Kodi restart

### ISSUE THREAD

**Issue by scott967** [xbmc/xbmc#21915]
### Describe the bug
Here is a clear and concise description of what the problem is:

When user changes replaygain settings on Settings -> Player -> Music -> Volume Adjustments (advanced)
guisettings.xml is updated with proper rpg type (0/1/2) (None/Album/Track) however, the updated setting is not used when playing a song.  Restarting Kodi does use the updated setting.  This appears to be a regression from PR #21449 @notspiff

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Changing the Replaygain settings should take effect with the next playing song.  Confirmed in 20220522 nightly (prior to 21449)

## Actual Behavior

Stale replaygain settings continue to be used.

## Possible Fix

revert commit 43323255b9f130f2fe811f8dc2608430191d7adc
In testing I see that replaygain is set in CAudioDecoder GetReplayGain
That in turn calls g_application.GetReplayGainSettings()
which access some variable "quick" in GlobalHandlings.h
That variable has CApplicationVolumeHandling member m_replayGainSettings which appears to not be updated after changing settings.  That in turn gets returned to GetReplayGain resulting in wrong rpg values being calculated and used.

### To Reproduce

1. Create a song with replaygain track/track peak/album/album peak values in tags
2. Scan the track into the library 
3. Play song (default setting is to use album replaygain 1)
4. Enter settings and change player/music/ volume adjustment to use track replaygain 2
5. Play song again
6. Observe rpg data in kodi.log -- both plays use the album rpg data
7. Exit Kodi and restart
8. Play song again
9. Observe rpg data in kodi.log -- play now uses the track rpg data

### Debuglog

The debuglog can be found here:
[https://paste.kodi.tv/cufivoyahe.kodi](https://paste.kodi.tv/cufivoyahe.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Testing PR#21881

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 10x64 21h1
 - Kodi version: Kodi (20.0-ALPHA3 (19.90.710) Git:20220914-7c8397512c). Platform: Windows NT x86 64-bit built in VS 2022 on Win 10 x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by complexlogic** [comment]
@scott967 Check out my PR #21941. I was poking around in the code today working on one of my other ReplayGain PRs, and I noticed the setting change callbacks aren't getting sent.
