### ISSUE TITLE
Can't download/search subtitles, what ever the addon

### ISSUE THREAD

**Issue by ludoluds** [xbmc/xbmc#21926]
### Describe the bug

When playing a video, go to subtitles settings -> download subtitle... -> and there, whatever subtitle service chosen, it keeps saying "Searching for subtitles..." and never display results. 
Sometimes, after a while (like a few minutes) subtitles results are shown in the panel for like 2 seconds then disappear.
Also, sometimes the results remain and after selecting one subtitle, it get stuck with the "Downloading subtitles" status.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When playing a video, go to subtitles settings -> download subtitle... After a few seconds, it should display subtitles the selected service has found.

## Actual Behavior

When playing a video, go to subtitles settings -> download subtitle... Results are never shown, whatever the service/addon or the played video.

### To Reproduce

1. Play a movie
2. Go to subtitles settings
3. Select Download subtitle

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I firstly shared this issue on Reddit. Other people seems to have the same issue on Android (https://www.reddit.com/r/Addons4Kodi/comments/xmq43c/not_able_to_download_subtitles_anymore/)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.3.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
There is no log
and however if that addon not work you must report to that addon developers not to kodi

**Comment by ludoluds** [comment]
> There is no log and however if that addon not work you must report to that addon developers not to kodi

As described, this is not addon related. It occues whatever the addon used.

**Comment by ludoluds** [comment]
> i have just tested `OpenSubtitles.com` addon on last Kodi v19 release and works as expected however kodi only shown the results, so if a subtitle addon do not provide results its not a Kodi problem

On Android(Nvidia Shield on my side), other people were saying they had the same behavior? 
It seems to be the issue, what ever the addon, results are not displayed. 

I'm trying to get logs but can't find them so far :/

**Comment by CastagnaIT** [comment]
you can try use Kodi Logfile Uploader addon under program addons
to updload log and get the link

**Comment by ludoluds** [comment]
What the hell? I was able to reproduce again and again, 5 minutes ago again. Now I've install that addon for logfile, I can see the results! I doubt this is linked but... I can't reproduce anymore...

**Comment by thexai** [comment]
The log is needed, first of all to know what version of Kodi you are using.....13 hours later and a few messages. There is no log and it is not clear if you are using Matrix or Nexus...

**Comment by ludoluds** [comment]
Can't reproduce anymore...
