### ISSUE TITLE
Kodi crash when keyboard or PIN window are used

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#21929]
### Describe the bug
Here is a clear and concise description of what the problem is:

Every time i use keyboard or input window kodi crashes
this on android by using last nightly build

i noticed in the log a lof of `Thread Timer start` and terminating before the crash
could be related to recent changes on gui timers? 

there is also a kind of screen flickering when you press keyboard buttons
not sure if relevant to this issue

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

i was using my addon to login
1. open keyboard to write email
2. after a bit you press on letters buttons kodi crash

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/culirikuki.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 8
 - Kodi version: Last v20 nightly 27/09/2022

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
I think you'll have to provide a crashlog, can you post the logcat output when the crash happens?

**Comment by CastagnaIT** [comment]
unfurnately on my honor device logcat its a problem, so not show nothing in any case
i will try install this build on android beelink on hoping happens same crash

**Comment by CastagnaIT** [comment]
got it on honor! just a reboot...
[logcat_09-27-2022_16-11-28.txt](https://github.com/xbmc/xbmc/files/9656724/logcat_09-27-2022_16-11-28.txt)

on beelink i am not able reproduce it

**Comment by CastagnaIT** [comment]
I do not know if this was the reason
but i have just installed a build of current master as release type and i dont have crashes anymore
maybe is due to because i have previously installed a debug build
for now i close the issue, if happen again i will reopen it
