### ISSUE TITLE
KODI can't connect to NFS server if gvfs-nfs isn't installed.

### ISSUE THREAD

**Issue by laichiaheng** [xbmc/xbmc#21946]
### Describe the bug
Here is a clear and concise description of what the problem is:

I need to install `gvfs-nfs` to connect to NFS server, but there is no such way to do it on my Android TV.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It can connect to my NFS server without installing extra packages.

## Actual Behavior

It can't connect to my NFS server.

## Possible Fix

KODI should build-in `gvfs-nfs` by default.

### To Reproduce

1. Install KODI from Flathub.
2. Open KODI
3. Connect to my NFS service.

### Debuglog

The debuglog can be found here:
I don't know how to get the debug information for a Flatpak application.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora 36
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by a1rwulf** [comment]
I have no idea about our Flathub package and why you might need `gvfs-nfs`, but Kodi uses libnfs so your issue might be something else.
You might a file called `kodi.log` either somewhere in `XDG_DATA_HOME` or `/app/share/kodi`.
Also why do you mention AndroidTV when you're on Linux?
On AndroidTV you just install the Kodi APK and it will be able to connect to your NFS.

**Comment by laichiaheng** [comment]
> I have no idea about our Flathub package and why you might need `gvfs-nfs`, but Kodi uses libnfs so your issue might be something else. You might a file called `kodi.log` either somewhere in `XDG_DATA_HOME` or `/app/share/kodi`. Also why do you mention AndroidTV when you're on Linux? On AndroidTV you just install the Kodi APK and it will be able to connect to your NFS.

I've tried it on my Linux PC, and I can access my NFS server, but with my Android TV, it can't.

**Comment by a1rwulf** [comment]
Then the problem is your NFS server.
Kodi uses non-privileged port to access NFS, so you need to add that option to your NFS-Server settings.
Also note that on Android applications are sandboxed and thus run as a separate linux user each, make sure you give read access to everyone or squash any user to a particular user that has read privileges on your shared folder.

**Comment by fuzzard** [comment]
NFS3 only as well in Matrix

**Comment by laichiaheng** [comment]
@a1rwulf 
```
/srv/nfs        192.168.1.0/24(rw,sync,crossmnt,all_squash,insecure,fsid=0)
/srv/nfs/Music        192.168.1.0/24(rw,sync,nohide,all_squash,insecure)
#/srv/nfs/Videos_1TB    192.168.1.0/24(rw,sync,nohide)
/srv/nfs/Videos_2TB    192.168.1.0/24(rw,sync,nohide,all_squash,insecure)
/srv/nfs/Videos_SSD    192.168.1.0/24(rw,sync,nohide,all_squash,insecure)
```
It was my NFS exports
