### ISSUE TITLE
Option "Close channel OSD after switching channels" is not working

### ISSUE THREAD

**Issue by Martype** [xbmc/xbmc#21977]
## Bug report
Settings > PVR & Live TV > Menu / OSD > Close channel OSD after switching channels

When the option is active, the channel OSD is not getting closed after switching to another channel. It keeps being opened for the duration that is set for "Show channel information when switching channels".

## Expected Behavior
When the option is active the OSD should get closed after switching to another channel.

## Actual Behavior
OSD is not getting closed after switching channels.

### To Reproduce
Set "Show channel information when switching channels" to like 15s. After switching to another channel you'll notice that the OSD keeps being open for the configured duration.

### Your Environment
Google Chromecast with Google TV
 - Kodi version: 19.3.0

**Comment by ksooo** [comment]
@Martype  could you please eloborate what you think the "channel OSD" is? Best, upload a screen shot showing the "channel OSD".

**Comment by ksooo** [comment]
This is the Channels OSD. 

![screenshot00001](https://user-images.githubusercontent.com/3226626/193887957-a8239adc-256f-4560-bb22-3e9e4564749c.png)

The setting "Close channel OSD after switching channels" controls whether the channl list shall be closed after switching channeös via selecting a channel from this list.

**Comment by Martype** [comment]
@ksooo uh, oh, so I mixed that up, sorry. I am talking about the overlay at the bottom when "previewing" what ist currently shown on another channel:

![PXL_20221004_184901233_exported_1167_1664909619527](https://user-images.githubusercontent.com/1420317/193902433-136767a4-3d97-482b-a029-ae3d26e25a62.jpg)

When I look through the other shows, for me the default 5 seconds were too low to read the description, so I set "Show channel information when switching channels" to the max 15s. But now I am a little bit annoyed that this overlay is shown for so long when I actually switch to that other channel 🥲

**Comment by ksooo** [comment]
Nothing I could do here as everything works as designed.

**Comment by Martype** [comment]
@ksooo an option could be implemented to hide that bottom layer when changing a channel.

But taking into what and how you wrote before, I get the feeeling

**Comment by ksooo** [comment]
> I get the feeling you are one of those old fashioned basement developers

@Martype I think there is no reason to get rude.

As we are talking about a feature, not a bug, GitHub is the wrong place to discuss. For feature requests, please use the Kodi forum.
