### ISSUE TITLE
Audio/video not synchronous of about 200ms on Android

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#21996]
### Describe the bug
Here is a clear and concise description of what the problem is:

Usually i was using my Windows HTPC with Kodi that has never had this problem,
when i got the new Nvidia Shield Pro a few months ago at first i never noticed this problem although occasionally i heard the audio was not accurate i thought it was a wrong feeling on my part...but

lately i have been more careful to pay more attention to audio/video sync
and i found that there is a problem of about 200ms and that this has also been reported more times in Kodi forum
https://forum.kodi.tv/showthread.php?tid=367357
https://forum.kodi.tv/showthread.php?tid=343831
so definitely not a wrong feeling from my part...

the behaviour change in 2 weird way:
if you play a MKV video the audio need to be adjusted by adding 200ms
if you play a DRM InputStream Adaptive video (like N€tflix) the audio need to be adjusted by substracting 200ms
(via setting audio menu while playing)

then you cannot use advancedsetting xml to adjust the async value in a fixed way otherwise you make a mess
this on Windows HTPC not happens so the audio is sync therefore something is wrong with the android build

the hardware configuration is the same on both devices, passthrought enabled
you can play DD5.1 or 2.0 not change

Windows HTPC -> Onkyo AV -> TV
Nvidia Shield -> Onkyo AV -> TV

i tried also switch HDMI ports but nothing change

it is not easy to notice this problem at first sight since are 200ms
but some movie situations can help like:
- sounds of objects falling or being moved (chairs sheets boxes switching on lights etc.)
- a person's lips when speaking, more noticeable with a translated language and less with an original one

I am willing to do more tests if required but i really have no idea where the problem may lie
this happens on both Kodi 19 and 20

yeah adjusting the audio sync for each video is a real hassle...

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

A miracle from someone

## Actual Behavior

Audio is async of about 200ms

### To Reproduce

1. Play a video
2.
3.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/9735825/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Not sure can help

from log `2022-10-07 18:09:28.033 T:17062    info <general>: HW-Delay (1): 284.69387755102036 ms`
this is one PR that could influence android delay https://github.com/xbmc/xbmc/pull/17504

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android Tv on last Shield Experience os
 - Kodi version: Kodi19 and 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by monsoons** [comment]
I tested with 60fps AV sync test video for kodi (https://photojoseph.com/SyncTest-5994-4K) and the same video for youtube app(https://youtu.be/YxJHqN_zlv4).

I cannot notice 200ms sync mismatch both in kodi20 and youtube app. 200ms so long time that you can notice it with bare eyes(12 circles difference on that test video), no need to shooting video in high speed.

I have to shoot video for the exact result, but I think the sync is almost perfect in kodi20 on my shield tv pro 2019.

**Comment by thexai** [comment]
@CastagnaIT, 
What Shield audio settings are you using?

mine is:

Dolby processing = OFF
Match content resolution = ON 
Audio video sync = 0 ms
Play comfort noise on HDMI = OFF

And I have no issues (Shield Pro 2019 ----> AVR Denon X1600H -----> TV).

See: https://forum.kodi.tv/showthread.php?tid=365127

Especially "Dolby processing" causes delay because re-encodes all to DD (to improve compatibility with ARC devices that not support other than DD). Not make sense enable using an AVR. Also "Audio video sync" is default enabled to 50 ms !!!!
Again not need using modern AVR.

**Comment by CastagnaIT** [comment]
hi thanks for the hints!

my shield audio config is:
Dolby processing = ON
Match content resolution = OFF
Audio video sync = 0 ms
Play comfort noise on HDMI = OFF

Dolby processing was enabled by default from first Shield startup since i had not found info on manual i do not changed it
this evening i will try as suggested so disable it

**Comment by CastagnaIT** [comment]
i tried set your settings in my shield then rebooted the device before playback videos
but no effect at all
by comparing Windows HTPC vs Shield, the HTPC have a very high sync while shield is always asynchronous of about 200ms

**Comment by CastagnaIT** [comment]
i noticed just now from log `Using Debug Kodi x64`
its weird because i had installed a jenkins build, builded as "release" but the log show as debug!?
maybe another side effect of debug? i will try install a Kodi 20 release just to be sure

**Comment by CastagnaIT** [comment]
so i tested current `nightly kodi-20221011-8e5cdd1d-master-24529-arm64-v8a.apk`
and also a release build of PR #21958 hoping for a change
but always 200ms of difference

**Comment by a1rwulf** [comment]
As @thexai mentioned enabling "Dolby processing" causes the delay for him and one comment later you mentioned that you have it "ON".
Can you try without "Dolby processing"?

**Comment by CastagnaIT** [comment]
yes i tried set the configuration suggested by thexai but in my case dont fix nothing
maybe there is a very small improvement but it is only a few ms maybe 50ms

**Comment by Tourosi** [comment]
I have no sync issue with 2 shield TVs.
After you have ruled out whether the onkyo receiver is the cause, try factory reset shield tv and the problem persists, contact nvidia for warranty service.
It's not a problem with the Kodi.

**Comment by CastagnaIT** [comment]
i have no audio sync problem with android apps like youtube, twitch, vlc... i think to exclude that i have a faulty device

after set configuration suggested by thexai seem that mkv are now sync, i need to get more videos for testing
instead videos played with inputstream adaptive are async
i should do some more tests with a DASH or HSL streams
