### ISSUE TITLE
Kodi 20 on Archlinux i3-4160T: VAAPI being enabled (even with all decoders disabled) Introduces audio lag into some livestreams

### ISSUE THREAD

**Issue by ilikenwf** [xbmc/xbmc#21995]
When playing back certain livestreams, including those from Youtube at times, audio and video start playing in sync but slowly drift apart. Video playback remains smooth, though.

It appears this is happening with h.264 specifically, the Youtube addon will not let me switch to the VP9 video stream (when I do, Kodi locks up).

Another example stream with issues (Reelz TV network stream):
https://bcovlive-a.akamaihd.net/c733a9aa448a4a44a10c527c6f5bf7a4/us-east-1/5245389775001/playlist.m3u8

I have exhausted all other options - I've upgraded drivers and codecs (currently using the intel hybrid codec and driver), tried git versions of inputsream, tried a flatpak version of Kodi, all with no luck.

Even if I have the toggle on for VAAPI but disable all the formats for decoding, and the preference to prefer VAAPI decoding, the sync issue arises. With it off, under CPU decoding, audio is in sync, but the video playback suffers in quality and smoothness.

Display adjustments do not help and neither does playback sync to display - and I am using passthrough.

Does this have anything to do with #15999 or #17080 by chance? 

Strange that CPU decoding either continues working properly despite any sync issues, or just decodes without them right?

### Debuglog
https://gist.github.com/ilikenwf/aed2ad947175245b3c22021b4927ec62

Note specifically the "ActiveAE::SyncStream" lines.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Archlinux
 - Kodi version: 19.4

**Comment by ilikenwf** [comment]
I should note this also happens for me with the Linus Tech Tips latest long live stream on youtube, all resolutions it seems:

https://www.youtube.com/watch?v=nETQGtt024k

**Comment by ilikenwf** [comment]
This issue now seems to be fixed in Nexus, closing.

As an aside, I had to set my audio sink with the env var to pipewire in order to even have my HDMI output available. I already replaced all the old audio sinks with pipewire equivalents, not sure if a bug or an issue with this new audio system, though.

**Comment by ilikenwf** [comment]
Nevermind, for whatever reason it is happening again, typically on specific video formats for some reason in Nexus.

**Comment by ilikenwf** [comment]
Appears now this issue is with VP9.

**Comment by lrusak** [comment]
Please post a full debug log without ffmpeg component logging.

**Comment by ilikenwf** [comment]
I'll try to at some point, but suspect it may be that my machine is needing upgrade, or something with inputstream adaptive - I disabled HDR and inputstream adaptive serves up HEVC instead of VP9, which is acceptable since this is youtube we're talking about...
