### ISSUE TITLE
Skip switching channel dialog when recording

### ISSUE THREAD

**Issue by mclei** [xbmc/xbmc#22000]
## Feature request
Currently, when the channel is being recorded and I want to switch to that channel, this dialog appears:

"Play recording" / "Play from beginning" with buttons "Play recording" and "Switch to channel"

It is extremely annoying in the case when I am recording all programs on some channels to allow delayed re-play.

It would be great to have some configuration parameter with predefined value to allow skipping this dialog.

The possible parameter values could be:
- "Ask" - it will preserve the current behavior with dialog asking user
- "Switch to channel" - just switch to channel without asking - follow the behavior like when there is no recording
- "Play recording" - plays the recording from start - I think this will be almost not used

I think it is a very simple feature and will help a lot.

**Comment by fuzzard** [comment]
This issue tracker is for bug tracking only

Feature requests can be made on the forums at https://forum.kodi.tv/forumdisplay.php?fid=9
