### ISSUE TITLE
Latest master build is failing on missing declaration

### ISSUE THREAD

**Issue by A1RF0RCE1** [xbmc/xbmc#22010]
### Describe the bug
Here is a clear and concise description of what the problem is:

/build/kodi-master/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecDRMPRIME.cpp: In member function 'bool CDVDVideoCodecDRMPRIME::FilterOpen(const std::string&, bool)':
build/kodi-master/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecDRMPRIME.cpp:665:22: error: 'StringUtils' has not been declared

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix

add #include "utils/StringUtils.h"  to 
DVDVideoCodecDRMPRIME.cpp

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP
- LibreElec 11 
 - Operating system version/name:
 - Kodi version: master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jernejsk** [comment]
First of all, you don't follow bug report template (no debug log). Second, more important, you're using out of tree patches and they caused the issue. Function FilterOpen() is only present in deinterlacing patches from LibreELEC.
