### ISSUE TITLE
Kodi not showing all UPNP folders 

### ISSUE THREAD

**Issue by jagiella** [xbmc/xbmc#22031]
### Describe the bug
I want to access the media exposed on my jellyfin media server via UPNP/DLNA. Unfortunately kodi only seems to see a single folder where there should be several. Other applications like VLC have no issue at seeing all the content. 

### Screenshots 
Here are some links or screenshots to help explain the problem:

#### VLC shows everything correctly:
<img width="607" alt="Bildschirmfoto 2022-10-15 um 10 29 17" src="https://user-images.githubusercontent.com/4679834/195977287-2ee66bd6-54ab-40b5-95af-b82085b23b39.png">

#### Kodi is missing folders:
<img width="979" alt="Bildschirmfoto 2022-10-15 um 10 32 12" src="https://user-images.githubusercontent.com/4679834/195977348-4f022c53-80c7-4a31-8268-e4d61107c507.png">
<img width="980" alt="Bildschirmfoto 2022-10-15 um 10 32 30" src="https://user-images.githubusercontent.com/4679834/195977355-044f4e3b-209f-4ffd-b0d1-a25c81be57ad.png">

## Additional context or screenshots (if appropriate)
The upnp/dlna server is jellyfin:
- Hardware: odroidc2
- Version: 10.9.0
- OS: Armbian/Linux
- Architektur: Arm64

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS Catalina 10.15.7
 - Kodi version: 20-alpha3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Can you try a recent nightly?

**Comment by jagiella** [comment]
Also with the last nightly build only a single folder is shown.
<img width="307" alt="Bildschirmfoto 2022-10-15 um 10 46 16" src="https://user-images.githubusercontent.com/4679834/195977853-d44b124b-6130-4e74-8fa5-e017b11c817d.png">

**Comment by enen92** [comment]
@jagiella thanks for reporting, should be fixed by https://github.com/xbmc/xbmc/pull/22032
cheers

**Comment by jagiella** [comment]
I testet the nightly build. It works now! :)
Thank you very much for your efforts!
