### ISSUE TITLE
Build errors on macOS (Apple Silicon)

### ISSUE THREAD

**Issue by sryze** [xbmc/xbmc#22030]
### Describe the bug

I followed  the build instructions at https://github.com/xbmc/xbmc/blob/master/docs/README.macOS.md#4-configure-and-build-tools-and-dependencies and ran into a compilation issue when building binary addons on my M1 MacBook.

Here are some errors:

```
[ 12%] Performing build step for 'openssl'
crypto/aes/aesni-mb-x86_64.s:10:7: error: unknown token in expression
 movq %rsp,%rax
      ^
crypto/aes/aesni-mb-x86_64.s:10:7: error: invalid operand
 movq %rsp,%rax
      ^
crypto/aes/aesni-mb-x86_64.s:12:8: error: unknown token in expression
 pushq %rbx
       ^
crypto/aes/aesni-mb-x86_64.s:12:8: error: invalid operand
 pushq %rbx
       ^
```

```
[  0%] Performing build step for 'glm'
[ 50%] Building CXX object glm/CMakeFiles/glm_static.dir/detail/glm.cpp.o
clang: error: argument unused during compilation: '-msse2' [-Werror,-Wunused-command-line-argument]
make[7]: *** [glm/CMakeFiles/glm_static.dir/detail/glm.cpp.o] Error 1
make[6]: *** [glm/CMakeFiles/glm_static.dir/all] Error 2
make[5]: *** [all] Error 2
make[4]: *** [build/glm/src/glm-stamp/glm-build] Error 2
make[3]: *** [CMakeFiles/glm.dir/all] Error 2
make[2]: *** [CMakeFiles/visualization.waveform.dir/rule] Error 2
make[1]: *** [visualization.waveform] Error 2
touch .installed-macosx12.3_arm64-target-debug
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. `cd kodi`
2. `make -C tools/depends/target/binary-addons`

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [X] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS 12.6
 - Kodi version: master branch

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Not all binary addons currently build.
Most of the addons have open PR's, but they havent been merged as yet.

Binary addons that are build currently can be downloaded via addon manager in kodi, so just skip bullding the binary-addons target

**Comment by sryze** [comment]
@fuzzard Thanks for the info. I've just tried compiling Kodi itself, but it failed as well:

```
CMake Error at cmake/modules/FindSSE.cmake:95 (message):
  CPU=arm64
Call Stack (most recent call first):
  cmake/scripts/common/ArchSetup.cmake:132 (find_package)
  CMakeLists.txt:39 (include)
```

Here is the command that I used:

```
cd kodi
mkdir build && cd build
/Users/Shared/xbmc-depends/arm-darwin21.6.0-native/bin/cmake -G Xcode -DCMAKE_TOOLCHAIN_FILE=/Users/Shared/xbmc-depends/macosx12.3_arm64-target-debug/share/Toolchain.cmake ..
```

It seems that the `find_package(SSE)` call in common/ArchSetup.cmake needs to be suppressed on non-x86 architectures?

**Comment by sryze** [comment]
@fuzzard Thanks
