### ISSUE TITLE
Kodi IPA cannot be installed on Apple phones by TrollStore？

### ISSUE THREAD

**Issue by CxiaoyuN** [xbmc/xbmc#22053]
Kodi IPA cannot be installed on Apple phones by TrollStore？

**Comment by DDCHINA0** [comment]
I have the same problem. iOS15 can't be opened by installing kodi with troll store. It will flash back.

**Comment by sarbes** [comment]
This is the Kodi bug tracker. Installation questions concerning third party stores are not covered, especially as we aren't affiliated with this store.

**Comment by Gghuzr** [comment]
18.9 Kodi works like charm
