### ISSUE TITLE
Kodi crashes with segmentation fault and is unable to start

### ISSUE THREAD

**Issue by anup-das** [xbmc/xbmc#22054]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi is unable to start and crashes when KODI_AE_SINK=ALSA environment variable is set.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should not crash.

### To Reproduce

1. Install kodi on Arch sudo pacman -S kodi
2. Set environment varialbe KODI_AE_SINK=ALSA in /etc/environment and logout
3. Start kodi

### Debuglog

The debuglog can be found here:
[kodi_crashlog-20221021_173716.log](https://github.com/xbmc/xbmc/files/9838850/kodi_crashlog-20221021_173716.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux archlinux 6.0.2-arch1-1
 - Kodi version: 19.4 (19.4.0) Git:20220429-nogitfound Media Center Kodi

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by wsnipex** [comment]
looks like pipewire is hogging your alsa device. Kodi v20 supports pipewire natively, so you might want to give this a try.

**Comment by anup-das** [comment]
Kodi v20 (Nexus) Alpha 3 installed via flatpak (https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux#Flatpak) does not crash and ALSA works fine on the same system ! The crash issue is with the latest stable version.

**Comment by wsnipex** [comment]
As said, v19 does not support pipewire, but your alsa device is blocked by it.

**Comment by anup-das** [comment]
@wsnipex, let's say that you are right and that the default alsa device is blocked by pipewire. How is it then that v20 is able to start in alsa mode (with KODI_AE_SINK=ALSA) and also use pure ALSA devices that are not routed through pipewire ?

[anup@archlinux ~]$ pactl info
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 74
Tile Size: 65472
User Name: anup
Host Name: archlinux
Server Name: PulseAudio (on PipeWire 0.3.59)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_00_1f.3.analog-stereo
Default Source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
Cookie: 8af3:3152

**Comment by fritsch** [comment]
If you check your backtrace, you see that there is not really much about guessing. You see that the pipewire thread blocks and that both AE threads (Sink and Engine) wait for it to respond.

It is btw. beyond that people use pipewire in the first place, then tunnel pulseaudio over it and at the end with both of them running think it's a good idea to want to use kodi on "pure alsa" on top.

Don't you see the pipewire thread in kodi 19.4? Never thought where this is coming from? Hint: It's not kodi - but pipewire fiddeling with your default ALSA system calls.

I'd say: fix your setup.

**Comment by fritsch** [comment]
This guy here:
```
Thread 7 (Thread 0x7f6babfff6c0 (LWP 3172)):
#0  0x00007f6bc8033096 in epoll_wait () at /usr/lib/libc.so.6
#1  0x00007f6bc0952669 in  () at /usr/lib/spa-0.2/support/libspa-support.so
#2  0x00007f6bc0944b7b in  () at /usr/lib/spa-0.2/support/libspa-support.so
#3  0x00007f6bc0898317 in  () at /usr/lib/libpipewire-0.3.so.0
#4  0x00007f6bc7fb18fd in  () at /usr/lib/libc.so.6
#5  0x00007f6bc8033a60 in  () at /usr/lib/libc.so.6
```
that's not even kodi code and has nothing to do when talking "plain" alsa. In short: while you tell kodi to use pure ALSA, your pipewire setup below it "interfers" with that wish and emulates / simulates (most likely an alsa default rule overwrite going back into pipewire) your wish to do so.

**Comment by fritsch** [comment]
Here, those guys discuss since months: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2140 - they even managed to break simple pulse audio setups. And the "I use latest and greatest" Arch guys are in front as always - without even questioning what they did on their setup in the first place.

When kodi is asked to do ALSA, kodi does "pure" ALSA. If your setup is configured to push your pipewire emulated sinks or pulseaudio emulated sinks under the back of a perfectly speaking ALSA setup and then fails with it - I really would suggest going back to the scratchboard and fixing my setup.
