### ISSUE TITLE
Kodi-20.0-Nexus_alpha1/alpha2/alpha3 crash on start-up on Amazon Fire TV Basic Edition 

### ISSUE THREAD

**Issue by Micromax56** [xbmc/xbmc#22069]
**Bug report**
**Describe the bug**

Kodi-20.0-Nexus_alpha1, alpha2 and alpha3 crashes on start-up on Amazon Fire TV Basic Edition:
Model      :  AFTT
Hardware :  mt8127
SW           :  Fire OS 5.2.9.1 (681771820)

Here are a logcat  logs from the device,  where the crash seems related to  this FATAL EXCEPTION

--------- beginning of crash
E/AndroidRuntime( 8096): FATAL EXCEPTION: main
E/AndroidRuntime( 8096): Process: org.xbmc.kodi, PID: 8096
E/AndroidRuntime( 8096): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__gxx_personality_v0" referenced by "libass.so"...

https://paste.kodi.tv/kuzogemasa

The crash happens immediately after the "first run" phase is completed, Being an Android 5.1.1 no run-time permissions are asked.

The issue is present on 2 different Amazon Fire TV Basic Edition I own. To be sure I also made  a factory reset on one of  them but nothing changed.

**Expected Behavior**

Kodi should start w/o problems.

 **Actual Behavior**

Kodi-20.0-Nexus_alpha1, alpha2 and alpha3 crash on start-up on Amazon Fire TV Basic Edition

**Possible Fix**

Issue could be related to the upgrade, done in Nexus, of libass library from VERSION=0.14.0 to VERSION=0.15.2,  but not sure.

I'm available to provide support for further debugging. 

**Your Environment**
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:   Fire OS 5.2.9.1 (681771820)
 - Kodi version: Kodi-20.0-Nexus_alpha1, alpha2 and alpha3

**Comment by Micromax56** [comment]
Same issue present on a very old Samsung Galaxy Grand Prime smartphone with Android version 5.1.1

https://paste.kodi.tv/qaqidufagu.kodi

Not tested on previous versions.

Matrix 19.4 starts w/o problems on Android 5.1.1

**Comment by joseluismarti** [comment]
I've tried running Kodi on Android 5.1 and confirmed that it crashes at startup when loading the library

**Comment by Scrotastic** [comment]
20 beta crashes on FireTV 4K during cache clearing on startup. Clean install or upgrade. Makes no difference. It will install but not run. I've noticed others reporting the same:

https://forum.kodi.tv/showthread.php?tid=370368
