### ISSUE TITLE
Question: build instructions for macOS

### ISSUE THREAD

**Issue by anohren** [xbmc/xbmc#22071]
## Bug report

A good while into building dependencies for macOS (`make -j6`) I get the below errors — while a bit difficult to read — about not being able to reach remote servers. My first reaction was "I could have told it that" since I had to move to a location without internet connection in the middle of the (long running) process.

I tried to read the instructions thoroughly and couldn't find any mention of internet connection as a prerequisite for actually building the dependencies after cloning the repo. I take it it's a prerequisite, which kind of put a damper on the build process since I wasn't aware the building was interleaved with networking. Maybe it could be mentioned as a prerequisite.

```
ccurl: (6u) rClo:u l(d6 )n otC oruelsdo lnvoet  hroessto:l vmei rhroosrts:. kmoidrir.otrvs
.kodi.tv
curl: (6) Could not resolve chuorslt::  (m6i)r rCoorusl.dk ondoit. trve
solve host: mirrors.kodi.tv
curl: (6) Couldcurl: ( 6n)o tC oruelsdo lnvoet  hroessto:l vmei rhroosrts:. kmoidrir.otrvs
.kodi.tv
curcl:u r(l6:)  (C6o)u lCdo unlodt  nroets orlevseo lhvoes th:o smti:r rmoirrsr.okrosd.ik.otdvi
.tv
curl: (6) Could not cruerslo:l v(e6 )h oCsotu:l dm inrorto rrse.skooldvie.t vh
ost: mirrors.kodi.tv
ccurl: (6) Cuorull:d  (n6o)t  rCeosuolldv en ohto srte:s omlivrer ohross.tk:o dmii.rtrvo
rs.kodi.tv
curl: c(u6r)l :C o(u6l)d  nCootu lrde snooltv er ehsoosltv:e  mhiorsrto:r sm.ikrordoir.st.vk
odi.tv
ccuurrll::  ((66))  CCoouulldd  nnoott  rreessoollvvee  hhoosstt::  mmiirrrroorrss..kkooddii..ttvv

curl: (56) Recv failure: Operation timed out
```

Later I reran the dependency build with a connection, and it said it finished successfully: `Dependencies built successfully.`

I skipped section 5, building binary addons, as I interpreted it as an optional step.

But then when generating the Xcode project with `make -C kodi/tools/depends/target/cmakebuildsys BUILD_DIR=~/path/to/kodi-build GEN=Xcode` I got the following error, which I'm not sure about, but mention in the same issue in case they're connected:

```
-- Found HarfBuzz: /Users/Shared/xbmc-depends/macosx12.3_x86_64-target-debug/lib/libharfbuzz.a (found version "3.1.1") 
CMake Error at /Users/Shared/xbmc-depends/x86_64-darwin21.5.0-native/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Iconv (missing: HAVE_ICONV_FUNCTION)
Call Stack (most recent call first):
  /Users/Shared/xbmc-depends/x86_64-darwin21.5.0-native/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindIconv.cmake:29 (find_package_handle_standard_args)
  cmake/scripts/common/Macros.cmake:372 (find_package)
  cmake/scripts/common/Macros.cmake:386 (find_package_with_ver)
  CMakeLists.txt:215 (core_require_dep)


-- Configuring incomplete, errors occurred!
```

What's wrong here? Am I making a mistake? 

Do I need to redo everything when this happens?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix

Explicitly mention that certain build steps will fail without internet access and that all resources have not necessarily downloaded even if you're 30+ minutes into the process.

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] OSX 12.4
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS 12.4 Monterey
 - Kodi version: d1723bbe6b7feb04de8dbf2d3f210c80840e36b8

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Just rebuild harbuzz. Probably failed mid build or something when you didn't have internet or whatever.

Cd tools/depends/target/harbuzz && make distclean && make

That assumes it's just harfbuzz that failed. May be better to insure a complete rebuild of dependencies, but for now try the above

If you haven't downloaded the tarballs before, yes an internet connection is required. The download step is done individually in each dependency build step, not pre downloaded as a bunch of tars.

**Comment by anohren** [comment]
Thanks for the pointer!

Actually the Harfbuzz line was the last line to succeed. I left it there for context, which might have been a bit misleading. The error seems to pertain to `libiconv` on closer inspection

Anyway, I did try rebuilding both Harfbuzz and libiconv in the way you suggested but the error persisted.

**Comment by fuzzard** [comment]
Did you only install command line tools or something?
Iconv is meant to be provided by the platform SDK for apple platforms.

**Comment by anohren** [comment]
Ok, I see, I just assumed from the presence of target/libiconv that it was being compiled from source. 

I have Xcode 13.3, and `xcodebuild -showsdks` tells me I have `macOS 12.3`:
```
MacOSX12.3.sdk - macOS 12.3 (macosx12.3)
SDKVersion: 12.3
Path: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk
PlatformVersion: 12.3
PlatformPath: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
ProductBuildVersion: 21E226
ProductCopyright: 1983-2022 Apple Inc.
ProductName: macOS
ProductUserVisibleVersion: 12.3
ProductVersion: 12.3
iOSSupportVersion: 15.4
```

**Comment by anohren** [comment]
Is it really constructive to "close as completed" without even considering the  incredibly simple suggested "possible fix"...?

**Comment by enen92** [comment]
@anohren we use github for issue/bug tracking. This is not a bug, it's simply how the build system is supposed to work. Dependencies tarballs are downloaded from the mirrors, you need an active internet connection and sometimes the download process may fail...

Having 600 open issues doesn't really help people actually trying to fix some of them.
If you feel the documentation should be improved, PR's are welcome as a follow up to this.

Cheers
