### ISSUE TITLE
4k 60fps videos with slowness and various crashes when I disable mediacodec surface and mediacodec

### ISSUE THREAD

**Issue by edersonmax21** [xbmc/xbmc#22080]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm having difficulties watching videos in 4k 60fps with mediacodec surface and mediacodec disabled, I'm using version kodi 20 nexus, I already used version 19.4 with the same problem, I want to disable mediacodec because my phone has the wrong image colors in the youtube addon in 4k 60fps, I would like you to fix this bug because I don't want the mediacodec activated on my phone. My phone is a s10+ exynos android 12 kodi nexus 20 version.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Watch 4k 60fps videos without crashing with mediacodec disabled

## Actual Behavior

Slow down and multiple crashes on my phone with mediacodec disabled on my phone

### To Reproduce

1. open kodi
2.I select 4k 60fps video with mediacodec disabled
3.Slowness and crashes during video display

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/locinocose.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Screenshot_20221031-191922_Kodi](https://user-images.githubusercontent.com/52547471/199121144-ceb87f4e-843f-47f1-bf68-a3e634396f52.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Phone android 12 S10+ Exynos 
 - Kodi version: 20 Nexus new

**Comment by lrusak** [comment]
Mediacodec is required for hardware accelerated decode. Without it the cpu simply cannot keep up with such content.

**Comment by edersonmax21** [comment]
> O Mediacodec é necessário para decodificação acelerada por hardware. Sem ele, a CPU simplesmente não consegue acompanhar esse conteúdo.

In this case how do I fix the color of youtube videos? are faded in color

**Comment by edersonmax21** [comment]
but then how do i get the normal color back from the youtube addon in 4k ?,
the color is faded in the videos, only in youtube videos.

**Comment by edersonmax21** [comment]
@lrusak but then how do i get the normal color back from the youtube addon in 4k ?,
the color is faded in the videos, only in youtube videos.
