### ISSUE TITLE
Can not access configuration after disabling all menu items

### ISSUE THREAD

**Issue by kripper** [xbmc/xbmc#22081]
### Describe the bug
Here is a clear and concise description of what the problem is:

User can not access configuration after disabling all menu items

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Pressing the configuration button/icon should open the configuration screen.

## Actual Behavior

Pressing the button doesn't do anything.
And it's impossible to fix this problem because configuration is blocked.

## Possible Fix

Configuration button/icon should work as normal or not be displayed at all.
Alternatively, it could be considered a feature to be able to disable the configuration button, but a warning should be shown to the user at least if he disabled all menu items and the button should not be shown at all.
Besides, there should be some solution to recover access to the configuration screen.

### To Reproduce

1. Disable all menu items in the skin options.
2. Try to press the configuration icon on top of the blank list of menu items (I'm navigating using arrow keys only)... It won't work.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: n/a
 - Kodi version:

17.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
I don't believe this can happen with the default skin as it is a skin dependent feature.

You can likely rename your Kodi home folder to start from scratch.

https://kodi.wiki/view/Userdata#Location

Please use the forum for further support.

**Comment by kripper** [comment]
Isn't this the default skin?
If so, please reopen.

I have important settings and prefer to modifiy the profile.xml file to recover access.

![image](https://user-images.githubusercontent.com/1479804/199172607-c75eaf3c-682a-4907-8fae-05511bfe8960.png)

**Comment by kripper** [comment]
To fix the problem, I patched this file via Termux:
`/sdcard/Android/data/org.xbmc.kodi/files/.kodi/userdata/profiles/mimi/addon_data/skin.estuary/settings.xml`
