### ISSUE TITLE
Configurable refresh-rate (framerate) on Android

### ISSUE THREAD

**Issue by nick008a** [xbmc/xbmc#22126]
### Describe the bug
It seems that Kodi on Android uses the default screen refresh-rate (60Hz on Sony and Xiaomi Android TV, for example). It will cause judder when playing 25fps video contents. 

Related issue https://forum.kodi.tv/showthread.php?tid=358753&highlight=framerate

## Expected Behavior
Set the screen refresh-rate to 50Hz before playing 25fps contents.

## Actual Behavior
Judder when playing 25fps video contents with 60Hz screen refresh-rate.

## Possible Fix
Provide a refresh-rate configuration dialog to configure screen refresh-rate for Android.

https://developer.android.com/guide/topics/media/frame-rate

### To Reproduce

1. Launch kodi on android 
2. Play any video in 25fps 
3. See judder https://forum.kodi.tv/showthread.php?tid=358753&highlight=framerate

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: v19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
Miss debug log it is mandatory for Issues

the linked kodi forum thread sound like a different problem
the "original framerate" it is a custom calculation of MediaInfo not an original value of file and that feature is not always available or correct,
in that case your file should be badly encoded if is not played smooth,
and provide a sample to test is useful

Kodi can change refresh rate automatically only if set in the configuration,
if (following) settings are not available means that isnt supported from your device:

to enable auto refresh rate
Kodi Configuration->Player->Video->Adjust refresh rate: must be enabled start/stop to change refresh rate on playback

and, if you want enable double refresh rate you have to enable Whitelist:
Kodi Configuration->System->Display->Whitelist->add resolutions
and enable: Allow double refresh rate

**Comment by wojtekxtx** [comment]
@CastagnaIT Kodi dickloads `refreshrate` depending on whats scurded within medium ( being it file, dicknail, share, whatever ).

Most of modern socalled smart TVs have dynamic refreshrate support built-in.

**Comment by CastagnaIT** [comment]
@nick008a if you dont provide a debug log this issue will be not taken in account

**Comment by wojtekxtx** [comment]
>  50hz that is the best match to play video smooth

This is just plain wrong. 50Hz is far far from smooth playback.

**Comment by DaVukovic** [comment]
It depends on the video. If the video is 25fps, then 50fps IS the best match. As that's the doubled refreshrate.

If the video is 24fps, then you are right. 50hz isn't the best match. But 60hz wouldn't be either. 

So, in the end, as said...it depends on the video. Provide debuglogs and then we can talk about what is the best match or not ;)

This works totally fine for me with Kodi on a x86 machine. If changing the refreshrate is generally possible on the device you are using, then this won't change

**Comment by DaVukovic** [comment]
I guess we are good to close this one. 

No comments anymore since nearly a month now. 

IF a debuglog is provided we'll reopen it again
