### ISSUE TITLE
Queue item (second) fail with multichannel audio

### ISSUE THREAD

**Issue by dabl2** [xbmc/xbmc#22124]
### Describe the bug
Here is a clear and concise description of what the problem is:

Using Queue item a second time with multichannel audio results in a crash on v20 Nexus which is a regression from v19 Matrix where this operation succeeds.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Using Queue item a second time with multichannel audio on v20 Nexus should succeed

## Actual Behavior

Using Queue item a second time with multichannel audio on v20 Nexus results in a crash 

## Possible Fix

regression from v19 Matrix where this operation succeeds.

### To Reproduce

1. Browse to folder of multichannel audio files and use Queue item
2. While audio is playing browse to a different folder of multichannel audio files of the same type and use Queue item on those

Links to Kodi logs show browsing for a folder of multichannel files, using Queue item and successful play, then while the first file continues to play, browsing for a different folder multichannel files of same type and using Queue item on those. 

File types are FLAC, E-AC-3 JOC (Atmos) .m4a and Dolby TrueHD (Atmos) .mka

see link to MediaInfo file examples

### Debuglog

The debuglog can be found here:

v20 Nexus Beta 1 queue multichannel flac - https://pastebin.com/31AEXGAU
v20 Nexus Beta 1 queue multichannel m4a - https://pastebin.com/pwFt2BzP
v20 Nexus Beta 1 queue multichannel mka - https://pastebin.com/mhz8hmis
v19.4 Matrix queue multichannel flac - https://pastebin.com/1GKR50Cq
v19.4 Matrix queue multichannel m4a - https://pastebin.com/uv49ZJy4
v19.4 Matrix queue multichannel mka - https://pastebin.com/sRnQ7pLW
MediaInfo file examples - https://pastebin.com/bbYasVqG

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV on 2019 Nvidia Shield Pro
 - Kodi version: v20 Nexus Beta 1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Thanks for reporting. I will take a look at the weekend.

**Comment by ksooo** [comment]
Does it only happen with multichannel audio files or with any kind of audio files? I could not reproduce with to folders containing mp3.

**Comment by ksooo** [comment]
The Matrix logs cannot be opened - 403 error.

**Comment by dabl2** [comment]
> Does it only happen with multichannel audio files or with any kind of audio files? I could not reproduce with to folders containing mp3.

Yes only multichannel, stereo works as expected.

**Comment by dabl2** [comment]
> The Matrix logs cannot be opened - 403 error.

Ugh I was afraid of that.  For whatever reason pastebin flagged the contents of those and made me post as 'private' whatever that means,  I guess it means nobody else can see them.  Wonderful.  I'll try using another service for those....

**Comment by dabl2** [comment]
Alternate sources for Matric logs

v19.4 Matrix queue multichannel flac - https://paste.kodi.tv/iwubugisoz.kodi
v19.4 Matrix queue multichannel m4a - https://paste.kodi.tv/azeqahumay.kodi
v19.4 Matrix queue multichannel mka - https://paste.kodi.tv/qizexatuwa.kodi

**Comment by ksooo** [comment]
> Yes only multichannel, stereo works as expected.

Then it seems not related to latest changes done in https://github.com/xbmc/xbmc/commit/8681fba8b5eeb02146dd2caa0f476ca584026a36, because they are agnostic to the type of the queued audio file.

**Comment by fritsch** [comment]
Still worth a try - some of kodi's features are based on side-effects ;-). While looking at your referenced commit I could not see anything wrong in general. The "isplayable" check was new to me - but it might not be a low level check.

**Comment by ksooo** [comment]
No, that’s not a low level check.

**Comment by ksooo** [comment]
@dabl2 would you have the chance to install a Kodi master from before the merge of the commit in question? => http://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/kodi-20221027-e4ac5d9e-master-24715-arm64-v8a.apk

**Comment by ksooo** [comment]
I can reproduce it now and it is actually related to the before mentioned commit. Fix should be no big deal, as far as I can see. I will take care of that.

**Comment by wojtekxtx** [comment]
> The Matrix logs cannot be opened - 403 error.

@ksooo Matrix is mozilla-based so its quite possible they screwed something

**Comment by dabl2** [comment]
> @dabl2 would you have the chance to install a Kodi master from before the merge of the commit in question? => http://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/kodi-20221027-e4ac5d9e-master-24715-arm64-v8a.apk

Absolutely thanks, will try and follow up.

**Comment by dabl2** [comment]
> > @dabl2 would you have the chance to install a Kodi master from before the merge of the commit in question? => http://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/kodi-20221027-e4ac5d9e-master-24715-arm64-v8a.apk
> 
> Absolutely thanks, will try and follow up.

All looks good now thanks, great work!

**Comment by dabl2** [comment]
Thanks mucho to the devs for this quick fix, greatly appreciated!
