### ISSUE TITLE
Kodi 19.3 crashes when generating thumbnails in "Wall" or "InfoWall" view

### ISSUE THREAD

**Issue by Lutz17** [xbmc/xbmc#22135]
I use Kodi 19.3 on a Shield TV Pro with Android TV 11.
I have activated the log once and the free memory is about 1.5GB.
If I open a directory with not yet generated preview images in the view "Wall", then the free memory drops to e.g. approx. 700MB.
If I now scroll down further, then more thumbnails are generated and the free memory drops further.
If I have a directory with about 20 images, the free memory drops down to about 300-400MB.
If I have a directory with more than 20 images, then I can provoke the crash.
The memory is only freed when I leave the directory and then it is again about 1.5GB free.
The photos are about 7MB in size, so with about 20 pictures that's about 150MB.
Why is the working memory then "loaded" with approx. 1GB?
In the view "InfoWall" it is similar, the views "Shift" and "WideList" are not affected. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@Lutz17 try kodi 20 a couple of fixes for thumbnails went in.

**Comment by mb555444** [comment]
> @Lutz17 try kodi 20 a couple of fixes for thumbnails went in.

Still crashes, very easy to reproduce. Enter a new folder with a few images, for which thumbnails have not been generated. Skip forward a couple of times. Usually crashes due to OOM.

**Comment by DaVukovic** [comment]
If it's that easy to reproduce, then it might be easy to provide a debulog. We (now) asked twice for that.

**Comment by mb555444** [comment]
> If it's that easy to reproduce, then it might be easy to provide a debulog. We (now) asked twice for that.

This is not my issue but here's a log. I had to skip pictures faster than I usually do to reproduce it on demand. But it has also happened while browsing pictures slowly.

What happens is that free memory initially is shown (in the top right corner) at around 1GB, goes up and down quickly, usually around 400MB to 600MB, but could also suddenly reach less than 100MB. This is while the users browses images in the foreground and the thumbnail generation creates thumbnails in the background. It might happen that multiple downscale operations happen concurrently in such a way that they allocate too much memory overall and cause the process to be terminated.

What I can see from the log is that multiple threads are active in parallel:

2022-12-06 23:24:27.088 T:19760   debug <general>: ffmpeg[0xd1a57400]: [swscaler] No accelerated colorspace conversion found from yuv422p to bgra.
2022-12-06 23:24:27.705 T:19769   debug <general>: ffmpeg[0xc5199680]: [swscaler] No accelerated colorspace conversion found from yuv422p to bgra.
2022-12-06 23:24:28.333 T:19762   debug <general>: ffmpeg[0xc5199200]: [swscaler] No accelerated colorspace conversion found from yuv422p to bgra.
etc.

The number of parallel jobs was recently discussed here: https://github.com/xbmc/xbmc/pull/22082
The number of active workers seems to be set to 2 = 5 - (3-0) by this code: https://github.com/xbmc/xbmc/blob/26adddf24d919b812a1bedf2507d5d33d4ebdbcf/xbmc/utils/JobManager.cpp#L434

[kodi.log](https://github.com/xbmc/xbmc/files/10170883/kodi.log)

**Comment by fritsch** [comment]
```
2022-12-06 23:24:27.088 T:19760 debug : ffmpeg[0xd1a57400]: [swscaler] No accelerated colorspace conversion found from yuv422p to bgra.
2022-12-06 23:24:27.705 T:19769 debug : ffmpeg[0xc5199680]: [swscaler] No accelerated colorspace conversion found from yuv422p to bgra.
2022-12-06 23:24:28.333 T:19762 debug : ffmpeg[0xc5199200]: [swscaler] No accelerated colorspace conversion found from yuv422p to bgra.
```

Not relevant. This only means, that there is no intrinsic support to convert yuv422p images - most likely jpegs with 422 subsapling to ffmpeg. For each image opened here a very large amount of memory is allocated: width x height x 4 bytes ... that's the reason that on low memory systems, the concept as it is right now will never fly properly.

Introduction of a memory pool was discussed some years ago.

**Comment by mb555444** [comment]
> Not relevant

Look at the thread IDs, not at the error message. As you say, each conversion needs a lot of memory, so why do it in multiple threads in parallel?

**Comment by fritsch** [comment]
Cause modern systems have multiple cores and huge amount of memory?

Again: Defining a memory pool with a limited size will solve it for those with the crappy hardware and those with modern systems ...

**Comment by mb555444** [comment]
> Cause modern systems have multiple cores and huge amount of memory?
> 
> Again: Defining a memory pool with a limited size will solve it for those with the crappy hardware and those with modern systems ...

Indeed. If this is the planned solution I am looking forward to it.
