### ISSUE TITLE
xbmc failed to build with "error MSB8066: Custom build for exited with code -1073741819" with MSVC on Windows arm64ec 

### ISSUE THREAD

**Issue by YangYang129** [xbmc/xbmc#22141]
xbmc failed to build with "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'F:\xbmc\build_arm64ec\CMakeFiles\b1df9fdb6705ee0058dcdfbd0f973120\addon.xml.rule;F:\xbmc\build_arm64ec\CMakeFiles\8fe7c2d2db5e8b2fd039963909cf9ce8\ServiceDescription.h.rule;F:\xbmc\build_arm64ec\CMakeFiles\cdbba45feb158851a76739fbae95cf82\generate_json_header.rule' exited with code -1073741819." with MSVC on Windows arm64ec. It can reproduce on latest version on master branch. Could you please help look at this issue?

Versions and configuration
OS: Windows Server 2022 Datacenter
VS: Visual Studio 2019(16.11.20)

Repro steps:
1. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
2. git clone https://github.com/xbmc/xbmc F:\xbmc
3. cd f:\vcpkg
4. bootstrap-vcpkg.bat
5. vcpkg.exe install --recurse libIconv --triplet x64-windows --clean-after-build
6. cd F:\xbmc
7. xcopy F:\gitP\xbmc\tools\x64 F:\xbmc\project\BuildDependencies\x64 /k/r/e/i/s/c/h/f/y 
8. xcopy F:\gitP\xbmc\tools\mingwlibs\x64 F:\xbmc\project\BuildDependencies\mingwlibs\x64 /k/r/e/i/s/c/h/f/y
9. xcopy F:\gitP\xbmc\tools\build\ffmpeg-x64 F:\xbmc\project\BuildDependencies\build\ffmpeg-x64 /k/r/e/i/s/c/h/f/y
10. mkdir build_arm64ec && cd build_arm64ec
11. cmake -G "Visual Studio 16 2019" -A  ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0  -DCMAKE_TOOLCHAIN_FILE=F:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows  ..
12. msbuild /m /p:Platform=ARM64EC /p:Configuration=Release kodi.sln /t:Rebuild 

**Error info:**
 44>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'F:\xbmc\build_arm64ec\CMakeFiles\b1df9fdb6705ee0058dcdfbd0f973120\addon.xml.rule;F:\xbmc\build_arm64ec\CMakeFiles\8fe7c2d2db5e8b2fd039963909cf9ce8\ServiceDescription.h.rule;F:\xbmc\build_arm64ec\CMakeFiles\cdbba45feb158851a76739fbae95cf82\generate_json_header.rule' exited with code -1073741819. [F:\xbmc\build_arm64ec\build\interfaces\json-rpc\schema\generate_json_header.vcxproj]

**Error log:**
[xbmc_build_error.log](https://github.com/xbmc/xbmc/files/10008463/xbmc_build_error.log)

**Comment by fuzzard** [comment]
Short answer, it's not a supported target platform.

Feel free to add a feature request on the forums, and/or submit a PR to introduce it.
