### ISSUE TITLE
Kodi 19.4 Volume control using TV Remote Channel Up and Down works ONLY for AAC audio codec

### ISSUE THREAD

**Issue by simtcrom** [xbmc/xbmc#22158]
### Describe the bug
Movies with audio codec other than AAC (such as AC3, DD+ etc.), when I press the TV Remote Channel Up and Down button, volume icon popup but it does not get adjusted.

## Expected Behavior
TV Remote Channel Up and Down button adjusts volume for all audio formats.

## Actual Behavior
Movies with audio codec other than AAC (such as AC3, DD+ etc.), when I press the TV Remote Channel Up and Down button, volume icon popup but it does not get adjusted.

## Possible Fix
I don't know.

### To Reproduce
1. Play a movie with audio codec AC3 or DD+
2. Press TV Remote Channel Up and Down
3. Observe volume does not get adjusted

### Debuglog
No additional debug info at this point.

### Screenshots 
Here are some links or screenshots to help explain the problem:
![2](https://user-images.githubusercontent.com/6823535/202364390-8c0fc0be-2dee-4f1c-8d16-1a547b1c1643.jpg)

![1](https://user-images.githubusercontent.com/6823535/202364401-82d3b05d-bf1e-45de-9ddd-ab7c97065dcb.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

For those movies, if I take the audio settings, both Volume and Volume amplification will be disabled.

### Your Environment
Used Operating system:
 - [x] Android

 - Operating system version/name:
 - Kodi version: 19.4
 - Android Version: 9
 - TV Mode - Hisense a71f

**Comment by simtcrom** [comment]
I got this sorted out  for DD+ format by Going to Settings/System/Audio and disabling, 

Dolby Digital Plus (E-AC3) capable receiver
DTS capable receiver
DTS-HD capable receiver

leaving only below two enabled,

Dolby Digital (AC3) capable receiver
  - Enable Dolby Digital (AC3) transcoding

**Comment by thexai** [comment]
This is not a bug, it's because you don't understand how audio passthrough works. Use the forum instead.
