### ISSUE TITLE
WebVTT subtitles not displayed for timestamps greater than 1 hour

### ISSUE THREAD

**Issue by garion84** [xbmc/xbmc#22150]
### Describe the bug

Here is a clear and concise description of what the problem is:

According to the [wiki](https://kodi.wiki/view/Subtitles#Supported_formats), since Kodi 20, the WebVTT files are supported.
Thank you for this new feature 😊️

I tried it using the nightly version of LibreElec:
-   The WebVTT file is well loaded.
-   Nevertheless, the subtitles in the file are displayed only if the timestamps are lower than 1 hour.
-   All subtitles in the file with a timestamp equals or greater than 1 hour are not displayed.

Some notes:
-   Bug reproduced with several WebVTT files.
-   WebVTT files are valid and have been checked with [Subtitle Edit](https://www.nikse.dk/subtitleedit) and the [Live WebVTT Validator](https://w3c.github.io/webvtt.js/parser.html)
-   All subtitles are well displayed with another video player (checked with mpv)

## Expected Behavior

Here is a clear and concise description of what was expected to happen:

All subtitles in a WebVTT file should be displayed.

## Actual Behavior

The subtitles in a WebVVT file are displayed only if their timestamp is lower than 1 hour.

All subtitles in a WebVVT file with a timestamp equals or greater than 1 hour are not displayed.

## Possible Fix

N./A.

### To Reproduce

1. Download the following file: [le-hobbit-la-desolation-de-smaug-2013.fre.txt](https://github.com/xbmc/xbmc/files/10018537/le-hobbit-la-desolation-de-smaug-2013.fre.txt)

2. Rename the file to link it to a video (greater than 1 hour) and change its file extension from txt to vtt

2. Play the video with Kodi

3. Only the subtitles with the IDs from `#1` to `#37` (timestamps < `1:00:00`) are displayed. The other ones are not displayed.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/10018545/kodi.log)

### Screenshots 

Here are some links or screenshots to help explain the problem:

- [at 00:55:00, subtitles are displayed](https://user-images.githubusercontent.com/51873865/202096595-05d6ccd4-359d-4606-8a8b-d87d1d446082.png)

- [at 01:02:18, subtitles are not displayed](https://user-images.githubusercontent.com/51873865/202096667-1b2d1c38-a65d-4a86-9ce4-bb1d05f5f455.png)

## Additional context or screenshots (if appropriate)

Here is some additional context or explanation that might help:

N./A.

### Your Environment

Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: **LibreElec (community): nightly-20221115-9c34b63 11.0, kernel: Linux x86 64-bit version 6.0.6**

 - Kodi version: **20.0-BETA1 (19.90.801) Git:20.0b1-Nexus**

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
that web validator is not so updated and Subtitle Edit also dont respect the w3c standard,
the specs (https://www.w3.org/TR/webvtt1/#webvtt-timestamp) says:
2 or more chars for hours (value is optional)
2 chars for minutes
3 chars for millisecs

all entries in your file from the following have a wrong timestamp:

```
38
1:02:17.167 --> 1:02:18.669
Qu’on ferme la grille !
```

so on this example must be: `01:02:17.167 --> 01:02:18.669`

this is the reason why you dont see the subtitles so it is not a bug,
but since its not a dangerous thing i can make the timestamp parser more relaxed

**Comment by garion84** [comment]
Hello @CastagnaIT,

Thank you for the info 😊️ and sorry to not check the specifications before opening the bug… 😓️

Thanks also for the proposed modification. Nevertheless, the files can be easily corrected with the [webvtt-py](https://webvtt-py.readthedocs.io/) library, for example:
```python
import webvtt
vtt = webvtt.read('le-hobbit-la-desolation-de-smaug-2013.fre.vtt.old')
vtt.save('le-hobbit-la-desolation-de-smaug-2013.fre.vtt')
```

Let me know if I can close the ticket (because of the opened pull-request).

Have a nice day

**Comment by CastagnaIT** [comment]
i close issue since changes are not needed, details on comments:
https://github.com/xbmc/xbmc/pull/22153#issuecomment-1319645560
https://github.com/xbmc/xbmc/pull/22153#issuecomment-1356312089
