### ISSUE TITLE
Resume context window of favorites does not show the resume point for Netflix videos.

### ISSUE THREAD

**Issue by monsoons** [xbmc/xbmc#22163]
### Describe the bug
Here is a clear and concise description of what the problem is:

It is related to https://github.com/xbmc/xbmc/issues/22149 https://github.com/xbmc/xbmc/pull/22156.
After installing the latest kodi20 nightly version, now I can see small popup for resume when playing Netflix from favorites.
But like 1st screenshot, the context is "Continue watching" and there is no resume time information.
I think it is a better way to provide resume point information as before like 2nd screenshot.
And also now there is inconsistency between local media videos(showing resume time info like 2nd screenshot)
and plugin videos when playing from favorites.

(Sorry @ksooo  I wasn't sure it is a bug or an intended feature about https://github.com/xbmc/xbmc/pull/22107 so wanted to discuss by comments.)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

as above

## Actual Behavior

as above

### To Reproduce

1. Install the latest kodi20 nightly(KodiSetup-20221116-3886efdc-master-x64).
2. Run Netflix addon and add a movie or an episode to favorites.
3. Play it from favorites and do some seek to create a resume point.
4. Replay it from favorites and check the context.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/10040428/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![screenshot00000](https://user-images.githubusercontent.com/35981015/202682119-cb02ebbc-3b1d-4ebe-88fe-5267c5ffedf2.png)

![rp](https://user-images.githubusercontent.com/35981015/202681015-46ccac62-3a69-4284-b2dd-6eb805141d71.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: windows 10 64 bit
 - Kodi version: kodi 20 the latest nightly (KodiSetup-20221116-3886efdc-master-x64)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Okay, I can reproduce the issue.

**Comment by ksooo** [comment]
The resume feature actually works, video resumes where it should, So, it's just the label of the context menu item being wrong. Nevertheless, this is a regression and should be fixed.

**Comment by monsoons** [comment]
> The resume feature actually works, video resumes where it should, So, it's just the label of the context menu item being wrong. Nevertheless, this is a regression and should be fixed.

Thank you for your comment.
