### ISSUE TITLE
Unnecessary contexts when playing episodes after "Continue watching" feature.

### ISSUE THREAD

**Issue by monsoons** [xbmc/xbmc#22176]
### Describe the bug
Here is a clear and concise description of what the problem is:

If there is  an episode in progress or a watched episode like these screenshots,

![screenshot00000](https://user-images.githubusercontent.com/35981015/203215238-3fcd91ed-f922-4c81-a7f7-08caacc9478e.png)
![screenshot00001](https://user-images.githubusercontent.com/35981015/203215254-d0ba0225-7290-4e3b-acdb-dc88f053cffe.png)

1.Playing next episodes pops up context like this screenshot.

![screenshot00002](https://user-images.githubusercontent.com/35981015/203215672-e6b65b61-1ce2-471b-92c2-702015f56951.png)

This is unnecessary because both "Continue watching" and "Play from beggining" lead to the same result.
I set default selection action to "Play", so should play the episode without showing any context as before.

2.Long press on unwatched episodes shows "Reset resume position" like this.

![screenshot00003](https://user-images.githubusercontent.com/35981015/203217563-bc367388-6be2-4172-87cc-59813a63a104.png)

This is also unnecessary because unwatched episodes have no resume point.
 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

no unnecessary context as before.

## Actual Behavior

some unnecessary contexts.

### To Reproduce

1. add a tvshow with some episodes files to your kodi library.(or test with your own pre-existing tvshows library)
2. set default select action to "Play" (Settings/Media/Videos) if the default select action is set to Resume, you may not see the context.
3. browse into the tvshow to view episodes list.
4. select an episode and mark as watched or play an episode and create resume point to make the episode in progress like screenshots above.
5. try to play other unwatched episode and check the context.
6. long press other unwatched episode and check the context.

### Debuglog

The debuglog can be 
[kodi.log](https://github.com/xbmc/xbmc/files/10063403/kodi.log)
found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: windows 10 64bit
 - Kodi version: kodi20 beta1 nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
@monsoons sorry, cannot reproduce. I don't have those context menu items. Maybe you post step-by-step instructions how you get there.

**Comment by monsoons** [comment]
I just updated steps

> @monsoons sorry, cannot reproduce. I don't have those context menu items. Maybe you post step-by-step instructions how you get there.

oh! updated steps.

**Comment by ksooo** [comment]
Double checked that default select action is "Play" here. Still not able to reproduce. There must be something else different on your end.

**Comment by ksooo** [comment]
@monsoons meanwhile I found out why I was not able to reproduce the issue. I was testing not on master, but on my personal dev branch, where (by "accident") the issue was already fixed. So, a fix is on its way.
