### ISSUE TITLE
Could get rid of vaapi_h264 patch not applied upstream for years

### ISSUE THREAD

**Issue by prahal** [xbmc/xbmc#22188]
### Describe the bug
The patch this commit seems unecessary:
https://github.com/xbmc/FFmpeg/commit/ca8882fcaf5da0192772733a7ba832765df7c391 "avcodec/vaapi_h264: skip decode if pic has no slices" with comment:
> This fixes / workarounds https://bugs.freedesktop.org/show_bug.cgi?id=105368.
> It was hit frequently when watching h264 channels received via DVB-X.
> Corresponding kodi bug: https://github.com/xbmc/xbmc/issues/15704

## Here is a clear and concise description of what the problem is:
This patch was to workaround a Mesa vaapi bug in the radeon  driver which is since fixed https://gitlab.freedesktop.org/mesa/mesa/-/issues/1308 "Crash in ruvd_end_frame when calling vaBeginPicture/vaEndPicture without rendering anything", ie fix is in in mesa-20.3.0-rc1 with commit https://gitlab.freedesktop.org/mesa/mesa/-/commit/7d853966df4f6d0ded845a6ba2b2af7c46404157.
Last upstream integration talk about this patch  is in http://ffmpeg.org/pipermail/ffmpeg-devel/2019-March/241057.html
 Thu Mar 14 12:05:06 EET 2019 .  From the talks it looks like not other accel drivers do so.
> Still, all of the other hwaccel APIs (VDPAU, DXVA2, NVDEC) do currently do the same thing too, though, so it would seem nicer if this could be kept consistent across all of them.  If Mesa with VAAPI is the only case where this fails (checking Mesa with VDPAU on the same hardware might be interesting?) then fixing it in the driver would seem the best answer. 
Note that this patch may hide bugs in other vaapi hw drivers which are specific to the xbmc fork and thus reverting this commit might trigger hidden bugs.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Not having to forward port patches that are not necessary and may deviate from upstream code behavior.

## Actual Behavior
This patch is shipped

## Possible Fix
Revert this commit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by prahal** [comment]
Note that issue report that introduce this patch was https://github.com/xbmc/xbmc/issues/15704 "Kodi segfaults on h264 dvb stream"

**Comment by lrusak** [comment]
Thanks for the info. We will look into it.
