### ISSUE TITLE
Mediaset infinity (Italian video addon) do not work properly

### ISSUE THREAD

**Issue by numbernumero** [xbmc/xbmc#22182]
### Describe the bug
Here is a clear and concise description of what the problem is:

Video addon "Mediaset play infinity " do not work properly.
All video content that need to be  login do not work even with a  valid subscription.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

All video with a valid subscription must work properly. Like before

## Actual Behavior

all video that need the login return a message "Login Failed" even if the subscription is correct and valid

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] OSX
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Bring this to the add-on Dev, Kodi doesn't have any relation whatsoever with add-ons or provider websites.

**Comment by numbernumero** [comment]
Hi, thanks for the reply. The mediaset problem was communicated on the
developer's git as many others did but he doesn't respond, it seems to
be abandoned. Perhaps you have more power than us to communicate the
problem to him otherwise this addon in the official kodi addon is
meaningless
