### ISSUE TITLE
Kodi Nexus Beta 1 in Arch linux packages don't work: inputstream-adaptive inputstream-rtmp and pvr-iptvsimple

### ISSUE THREAD

**Issue by cg00001** [xbmc/xbmc#22184]
Here is a clear and concise description of what the problem is:
The problem seems to be the pvr git package is building Kodi 19 version, while the other 2 Kodi 20.0 Alpha 3 -while current is Kodi Nexus Beta 1.
Simple client is built but won't run -gives an error on Kodi Nexus since it's a Matrix version-, the others fail to build.
Just (try to ) install kodi-addon-inputstream-adaptive-git, kodi-addon-inputstream-rtmp-git, kodi-addon-pvr-iptvsimple-git.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 Arch Linux.
- Kodi version:
Kodi Nexus Beta 1.

**Comment by lrusak** [comment]
Please report to your package managers as we don't provide binaries for Arch Linux.
