### ISSUE TITLE
Can't open RTSP stream on Kodi 19

### ISSUE THREAD

**Issue by Barabba11** [xbmc/xbmc#22198]
Hi, I've tried to install addon plugin.video.ipcams https://github.com/b-jesch/plugin.video.ipcams and what they suggested me to do, I've tried to produce a m3u and strm file, il looks there isn't any way to open an RTSP stream with Kodi 19. I think it should consider a bug, thankyou for your kind support

#KODIPROP:rtsp_transport=tcp
rtsp://user:password@mypublicIP:55554/cam/realmonitor?channel=1&subtype=0

tried also with the format:
#KODIPROP:rtsp_transport=tcp
rtsp://user:password@mypublicIP:55554/live.sdp

Both url are perfectly working on the same PC with VLAN

**Comment by Barabba11** [comment]
thank you, I've tested it, it works with 20. Unfortunately 20 doesn't support the addon I use so I'll renunce on the rtsp view, pity

**Comment by enen92** [comment]
Please bring that issue to the add-on developer, v20 is around the corner.
I am closing this as fixed.
