### ISSUE TITLE
Kodi untable PPA is missing packages for Jammy

### ISSUE THREAD

**Issue by bkiziuk** [xbmc/xbmc#22191]
### Describe the bug
While trying to add the unstable PPA on Mint 21 (based on Ubuntu Jammy):
```
sudo apt install software-properties-common
sudo add-apt-repository -y ppa:team-xbmc/unstable
sudo apt install kodi
```
I get
```Cannot add PPA: ''This PPA does not support jammy''.```

## Expected Behavior
Jammy is supported and
```ppa:team-xbmc/unstable```
can be added.

## Actual Behavior
```Cannot add PPA: ''This PPA does not support jammy''.```

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux Mint 21 Cinnamon
 - Kodi version: 20 Beta 1

**Comment by wsnipex** [comment]
the unstable PPA isn't updated anymore for a while now. Unless someone else wants to step up and maintain it, this is not going to change

**Comment by bkiziuk** [comment]
Hi @wsnipex 
many thanks for your comment. So, the preferred way of getting Nexus Beta 1 is?

**Comment by lrusak** [comment]
> the unstable PPA isn't updated anymore for a while now. Unless someone else wants to step up and maintain it, this is not going to change

Can we remove it?

**Comment by wsnipex** [comment]
@bkiziuk you can get a slightly newer version (mostly fixes since beta1) from the nightly ppa: https://launchpad.net/~team-xbmc/+archive/ubuntu/xbmc-nightly

@lrusak yes, we can ;) But we should cleanup the pipeline lib and jenkins first
