### ISSUE TITLE
Failed to play 10bit h264/hevc videos on rk3568 with hardware decode on 5.10 rockchip kernel

### ISSUE THREAD

**Issue by amazingfate** [xbmc/xbmc#22202]
### Describe the bug
I have a rk3568 board running 5.10 kernel from rockchip, here is the source code: https://github.com/friendlyarm/kernel-rockchip/tree/nanopi5-v5.10.y_opt. To enable kodi hardware accelerated decode I build ffmpeg from https://github.com/JeffyCN/FFmpeg/, and build kodi with gles render system. Ffmpeg and kodi are available from this ppa: https://launchpad.net/~liujianfeng1994/+archive/ubuntu/rockchip-multimedia. 
I can play h264/hevc 8bit videos with drm hardware accelerated decode. But when I play a 10 bit video like http://ps-auxw.de/10bit-h264-sample/10bit-eldorado.mkv, there is a black screen and only audio is played.
Here is the kodi debug log when playing this file:
https://paste.ubuntu.com/p/C29gywz4Tg/

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

10 bit videos is played with hardware accelerated decode.

## Actual Behavior

10 bit videos is played with a black screen and audio.

## Possible Fix

In the debug log we can see `CEGLImage::SupportsFormat - format not supported: NA12`. I can find `NA12` from the source code of ffmpeg: https://github.com/JeffyCN/FFmpeg/blob/master/libavcodec/rkmppdec.c#L48, which is a DRM_FORMAT provided by the kernel of rockchip. In version 5.10 of rockchip's kernel this format should be `NV15`. But I can't see `NV15` in the supported format list printed in kodi's debug log. I want to know where does kodi get the supported format from so that I can make kodi support playing 10bit videos. 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4+dfsg1-2 (same version in ubuntu jammy built with gles render system)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
The egl check come from libegl to check the supported formats that are possible to import. If your gl library doesn't support it then that's when support needs to be added.

**Comment by amazingfate** [comment]
> The egl check come from libegl to check the supported formats that are possible to import. If your gl library doesn't support it then that's when support needs to be added.

I'm using panfrost kernel drm driver and userspace egl library should be provided by mesa.Which component is possible to lack this NV15 format support?

**Comment by lrusak** [comment]
> > The egl check come from libegl to check the supported formats that are possible to import. If your gl library doesn't support it then that's when support needs to be added.
> 
> 
> 
> I'm using panfrost kernel drm driver and userspace egl library should be provided by mesa.Which component is possible to lack this NV15 format support?

Have you tried using the DRM render rather than the egl renderer? Assuming the DRM driver supports NV15 in the display planes.

**Comment by lrusak** [comment]
> > > > The egl check come from libegl to check the supported formats that are possible to import. If your gl library doesn't support it then that's when support needs to be added.
> 
> > > 
> 
> > > 
> 
> > > I'm using panfrost kernel drm driver and userspace egl library should be provided by mesa.Which component is possible to lack this NV15 format support?
> 
> > 
> 
> > Have you tried using the DRM render rather than the egl renderer? Assuming the DRM driver supports NV15 in the display planes.
> 
> 
> 
> Do you mean setting `PRIME Render Method` from `EGL` to `Direct To Plane`? This option will also use EGL to get supported formats.

Yes I meant he `Direct To Plane` option. This option will query the DRM planes supported formats and if the format isn't supported you will get a different log message. It's likely if it fails it will fallback to the EGL method.

**Comment by amazingfate** [comment]
> > > > > The egl check come from libegl to check the supported formats that are possible to import. If your gl library doesn't support it then that's when support needs to be added.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I'm using panfrost kernel drm driver and userspace egl library should be provided by mesa.Which component is possible to lack this NV15 format support?
> > 
> > 
> > > 
> > 
> > 
> > > Have you tried using the DRM render rather than the egl renderer? Assuming the DRM driver supports NV15 in the display planes.
> > 
> > 
> > Do you mean setting `PRIME Render Method` from `EGL` to `Direct To Plane`? This option will also use EGL to get supported formats.
> 
> Yes I mean the `Direct To Plane` option. This option will query the DRM planes supported formats and if the format isn't supported you will get a different log message. It's likely if it fails it will fallback to the EGL method.

I changed the ffmpeg drm format to `NV15`, but the video is still black. Here is the log: https://paste.ubuntu.com/p/5t9hzZ8bRs/.
We can see `CDRMPlane::SupportsFormatAndModifier - found plane format (NV15) and modifier (0x0)`. But there are a lot of error `CVideoLayerBridgeDRMPRIME::Map - failed to convert prime fd 3 to gem handle 0, ret = -1` following that.

**Comment by amazingfate** [comment]
@lrusak I've solved this issue, thank you for your kindly help!
