### ISSUE TITLE
Cannot download git files

### ISSUE THREAD

**Issue by Olmium** [xbmc/xbmc#22203]
Here is a clear and concise description of what the problem is:
I cannot download the GIT repository. I keep getting errors, no matter what I try to fix them. I am not the most capable when it comes to these things, so I may be doing something wrong...but I am helpless and after spending almost 2 full days on this, and needing to reclone from my backup every time something gets messed up is taking up a lot of my time.

Here are some links or screenshots to help explain the problem:
[Image of errors](https://i.imgur.com/GM3OTiQ.png)

Used Operating system:
 - [ RaspberryPI/NextcloudPI ] Linux

**Comment by enen92** [comment]
Please use the forum for support, this is an issue tracker.
