### ISSUE TITLE
Sound disappear

### ISSUE THREAD

**Issue by Yellow-King21** [xbmc/xbmc#22206]
### Describe the bug
Hello, I found out that after I switch language (dubbing) of tv show or movie sound completely disappear. When I trying to repair it by changing movie (or tv show) nothig happens so I have to restart kodi. This sound disappearing problem does not happen always but I found out that when I start movie and changing dubbing few times than I can reproduce this bug. 

### To Reproduce

1. Start film with two or more different dubbing.
2. Change dubbing few times.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/yihacamiru.kodi

### Video 
I made a video of this problem, sound disappear start from 26 second.

https://user-images.githubusercontent.com/34798184/205318928-0ba26ad5-b95d-4322-894f-a7f4efab02fe.mp4

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora 36 (Wayland)
 - Kodi version: 19.04

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Banned addons/repos installed and debuglog is incomplete. 

Please remove those banned add-ons/repos and get us a new and unmodified logfile.

**Comment by DaVukovic** [comment]
Ha....just noticed that you are actually claiming about the stream-cinema add-on which is the banned addon in your log. 

Report it to the maintainer or ask him for support. We won't even look at that anymore.
