### ISSUE TITLE
Kodi v20 beta TV Guide issues with TVHeadend backend

### ISSUE THREAD

**Issue by jawadshaik** [xbmc/xbmc#22208]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi v20 beta issue with TVHeadend backend, running Kodi on Fire TV Cube (Android ARMV7A 32bit.)
1. Live tv guide randomly shows an empty tv guide.
2. Recording live tv is saved under the channel name instead of the program name and there is no recording indicator shown on the guide when manual recording is started this way.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1.
4.
5.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: ARM V7A 32 bit.
 - Kodi version: 20 beta

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jawadshaik** [comment]
Closing as I did not encounter the issue in Dec 03 nightly build with a new install of Kodi instead of an upgrade.

**Comment by gsg2016** [comment]
Hi
I had to to reinstall kodi on raspberry pi 400 after nightlly update corruption
LibreELEC-RPi4.arm-11.0-nightly-20221207-cfd7db5.img.gz
Now having issues with EPG using tvheadend

**Comment by Moisie2000** [comment]
Hi
Same issue here with kodi-20221211-911ad268-master-27719-x86_64.dmg running on macOS 13.0.1.

EPG initially loads ok - but then after a few minutes (possibly coinciding with the completion of loading the recordings list), it disappears entirely. Works as expected with Kodi 19.

I'm running MythTV as my backend (on a different machine), so I don't think this is TVHeadend-specific.

**Comment by ksooo** [comment]
Without debug logs we cannot say/do anything.

**Comment by gsg2016** [comment]
Hi
Thanks Moisie2000 for explaining the problem better
Just updated to latest LibreELEC-RPi4.arm-11.0-nightly-20221211-ecb6f6c.img.gz
Problem remains thanks for your help

http://ix.io/4ijB

**Comment by ksooo** [comment]
```log
2022-12-11 22:42:32.916 T:1159     info <general>: Attempting to update the database Epg16 from version 13 to 16
2022-12-11 22:42:32.918 T:1159    error <general>: SQL: [Epg16.db] SQLite error SQLITE_ERROR (duplicate column name: iChannelGroup)
                                                   Query: ALTER TABLE savedsearches ADD iChannelGroup integer; (duplicate column name: iChannelGroup)
2022-12-11 22:42:32.918 T:1159    error <general>: Exception updating database Epg16 from version 13 to 16
2022-12-11 22:42:32.918 T:1159    error <general>: Error updating database Epg16 from version 13 to 16
```

@gsg2016 for unknown reasons your EPG database file (Epg16.db) got corrupted. Please delete it while Kodi is not running and with the next Kodi start the problem should be gone.

**Comment by ksooo** [comment]
I think I found a bug in the database migration logic. Let's reopen this issue.

**Comment by Moisie2000** [comment]
Many thanks @ksooo for the quick attention!
Will test against the nightlies once I see the PR has been merged (assuming that's how this works...)

**Comment by gsg2016** [comment]
Thanks @ksooo 
Deleting Epg13.db and Epg16.db databases fixed the issue

Cheers

**Comment by Moisie2000** [comment]
EPG DB upgrade working as expected for me now - thanks @ksooo !
