### ISSUE TITLE
Windows: libbluray is not uptodate (Kodi 19.4 and Kodi 20221203-95c4549b-master-x64)

### ISSUE THREAD

**Issue by Ser-vie** [xbmc/xbmc#22224]
## Roadmap or todo item
**Detailed Description**

Please update the files for libbluray, for Kodi 19.4 and Kodi 20 nightlies.
Current with libbluray 2022-11-25: Version 1.3.4
Current with Kodi 19.4: 1.1.2
Current with Kodi 20: 1.3.2

### Context

Java has many security issues. So that you can also use the latest Java versions.
So that Bluray Java menus work better.

### Additional context, screenshots or links
Here are some relevant links or screenshots

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by maff76** [comment]
Hi @lrusak i have compiled libbluray 1.3.4 for windows and have all the bits needed to build Kodi with it, i was told prebuilt dll's from a 3rd party wouldn't be accepted and i'm not 100% sure how i would go about submitting them

**Comment by lrusak** [comment]
> Hi @lrusak i have compiled libbluray 1.3.4 for windows and have all the bits needed to build Kodi with it, i was told prebuilt dll's from a 3rd party wouldn't be accepted and i'm not 100% sure how i would go about submitting them
> 
> 
> 
> am very much a novice but have built kodi using my libbluray builds and everything appears to always work

Windows depends are compiled as part of another project. For libbluray you can see that here. https://github.com/xbmc/kodi-deps/blob/d04b692cb1ee8173081c348ac96e4f65dcd1652e/CMakeLists.txt#L868

**Comment by maff76** [comment]
ahhh i missed where kodi 20 was at 1.3.2 as i didn't know Nexus had moved to that new project to build on the fly i mainly built libbluray for Matrix and always downloaded precompiled depends and switched out the libbluray part for mine

1.3.2 - 1.3.4 i am not sure if it has any windows improvments but new versions are good :), for matrix though it would be required to allow new versions of Java and get some nice improvements but again i don't think they would take a precompiled depends from a random dude on internet
