### ISSUE TITLE
KODI let user to (try) install addons that are o.s. specific

### ISSUE THREAD

**Issue by RafaelLinux** [xbmc/xbmc#22231]
IAGL addon let users to play retrogames in KODI (18 and 19).
This addon requires "script.module.win_inet_pton" that works and it's only for Windows operating system so, Linux (as LibreElec/CoreElec users) try to install IAGL expecting it will install and finally it's impossible cause IAGL will only works on Windows.

Please, add some way to inform users if an addon is not compatible with his version of Kodi or operating system.

Thank you

**Comment by enen92** [comment]
This is an issue tracker for Kodi core software, addons are third party and mantained elsewhere.
@zach-morris fyi

**Comment by zach-morris** [comment]
Thanks, but i have no idea what script.module.win_inet_pton is ([my addon](https://github.com/zach-morris/plugin.program.iagl/blob/main/addon.xml) does not use that)
[RafaelLinux](https://github.com/RafaelLinux) You can look at the wiki and other supporting info at my repository [here](https://github.com/zach-morris/plugin.program.iagl/wiki)
