### ISSUE TITLE
which ffmpeg is planned to be included in Nexus

### ISSUE THREAD

**Issue by graysky2** [xbmc/xbmc#22238]
### Describe the bug
I noticed that ffmpeg has a tag named, "[5.1.2-Nexus-Alpha3](https://github.com/xbmc/FFmpeg/tags)" but [FFMPEG-VERSION](https://github.com/xbmc/xbmc/blob/master/tools/depends/target/ffmpeg/FFMPEG-VERSION#L3) is currently pointing to 4.4.1-Nexus-Alpha1.  Is that an oversight or is 4.4.1 the expected version of ffmpeg for Nexus?

**Comment by enen92** [comment]
ffmpeg is planed to be updated for O*, since we are approaching release the final version in v20 will be the same as today (4.4.1). v21 is supposed to be a fast release though (famous last words :) )
