### ISSUE TITLE
Kodi 19.4 dietpi 8.11.2 cpu temp bug

### ISSUE THREAD

**Issue by Thundervarela** [xbmc/xbmc#22240]
## Roadmap or todo item
**Detailed Description**

### Additional context, screenshots or links
Here are some relevant links or screenshots

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

Kodi 19.4 dietpi 8.11.2 cpu temp bug , missing cpu temp disable i can check it on the commandline but not on the kodi interface like this : https://imageshack.com/i/pnnyCkohj
https://github.com/MichaIng/DietPi/discussions/5968#discussioncomment-4364820

**Comment by lrusak** [comment]
Please use the forum for support. http://forum.kodi.tv

Also, https://kodi.wiki/view/Advancedsettings.xml#cputempcommand
