### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Dertyiula** [xbmc/xbmc#22250]
How can I help with the translation in Azerbaijani language?

**Comment by Klojum** [comment]
You can start by opening a free acount at https://weblate.org as that is where Kodi translations are now processed. When your account has been created, we can link it to the translation(s) of your choice.

**Comment by gade01** [comment]
Thanks for helping out.
Azerbaijani needs a lot of help  :)

Our project is located at
https://kodi.weblate.cloud/
