### ISSUE TITLE
20.0 RC1 TV Guide fills correctly but is cleared after a while

### ISSUE THREAD

**Issue by tripleseven73** [xbmc/xbmc#22252]
After starting Kodi 20.0 RC1 the TV Guide shows program details correctly at first but looses all data shortly after.

Steps to reproduce

1. start Kodi
2. open TV Guide: guide displays correctly (screenshot 1)
3. return to home screen
4. wait a minute
5. open TV Guide: all lines in the guide are blank (screenshot 2)

Additional details:

- reproduced on multiple machines
- no issues with the TV Guide on TV Server
- clearing the guide restores it for a few seconds until the problem manifests itself again

Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 22H2 64-bit
 - Kodi version: Nexus 20.0 RC1 (automatically updated through Windows App Store from 19.x)
 - PVR client: DVBLogic/TVMosaic

![Screenshot 1](https://user-images.githubusercontent.com/30544064/207247140-0ebb7201-5827-4442-a575-6672e4154fa1.png)
![Screenshot 2](https://user-images.githubusercontent.com/30544064/207247144-95014674-e1e3-4995-9110-d7c78ec2431f.png)

**Comment by ksooo** [comment]
duplicate: https://github.com/xbmc/xbmc/issues/22208
