### ISSUE TITLE
No Disk and no entry on macOS 13.0.1

### ISSUE THREAD

**Issue by Cobramk81** [xbmc/xbmc#22257]
If I put an Audio Disk in the drive there is no disk entry in Kodi 20 RC1 works fine with Kodi 19.4
### Describe the bug
After starting Kodi and I habe set the Audio Disk standard to rip the disk as Flac Audio.
After that I put a disk into the DVD Drive but there is no Disk entry in the Main Menu and Ripping does not start.
If I go to Musik and chose Data/Files I see the Audio CD and can access to the files but ripping is impossible.
Also the setting to playback the disk do nothing

Done the same in Kodi 19.4 works fine.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Starting Playback the disk or rip the disk

## Actual Behavior

If I put a disk in the drive Kodi makes nothing

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Log?

**Comment by Cobramk81** [comment]
here is my Kodi log

[kodi.log](https://github.com/xbmc/xbmc/files/10228963/kodi.log)
