### ISSUE TITLE
Kodi 19.4 AND 20rc1 WINDOWS 10 Strange Windowed Behaviour

### ISSUE THREAD

**Issue by verbal666** [xbmc/xbmc#22263]
### Describe the bug
Here is a clear and concise description of what the problem is:

I encoutered a strange behaviour from KODI, since 19.4 and actual 20rc1 versions.
Inside KODI Windowed mode display, when i switch display with a KVM (HDMI) from PC1 (where Kodi runs) and PC2 (a Laptop), when i return to PC1, i see the display is as shifted about 30 pixels vertical upper, leaving a 30 pixel blank area on bottom.
_If i maximize Kodi window, and turn back to its normal size, problem is solved!!!_
See here: https://drive.google.com/file/d/1h5iUDY_7TExfCDBStt5DooweP5Td6QaA/view?usp=share_link 
**I found, now, the issue raises when i switch my display, with a KVM (HDMI) from PC1 (where Kodi runs) and PC2 (a Laptop). When i return to PC1, Kodi window is shifted up!!!**

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No display shift.

## Actual Behavior

The display is as shifted about 30 pixels vertical upper, leaving a 30 pixel blank area on bottom.
**I found, now, the problem raise when i switch my display, with a KVM (HDMI) from PC1 (where Kodi runs) and PC2 (a Laptop). When i return to PC1, Kodi window is shifted up!!!**

## Possible Fix

?

### To Reproduce

1. I open Kodi
2. I open any addon, Radio in my case
3. I switch my display with KVM (HDMI) from PC1 (where Kodi runs) and PC2 (a Laptop). When i return to PC1, Kodi window is shifted up!!!
4. _If i maximize Kodi window, and turn back to its normal size, problem is solved!!!_
5.  (see video)

### Debuglog

The debuglog can be found here:
https://drive.google.com/file/d/1Aw2AVDOVLhVYK9-VZL65lAdTmlTnGq2W/view?usp=share_link

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://drive.google.com/file/d/1h5iUDY_7TExfCDBStt5DooweP5Td6QaA/view?usp=share_link 

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X ] Windows 10/64 10.0.19045.2364 / GTX 1060 3GB 
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
19.4 & 20rc1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by verbal666** [comment]
> > since 19.4 and actual 20rc1 versions
> 
> This mean that are you tested in 19.3 and the issue not exists? ...or this means that you only tested in 19.4 and 20.0 rc1 and this issue always has existed in your peculiar "KVM" setup?

I left 19.3 by time. Only 19.4, since yesterday, when i installed 20rc1.
The problem always existed from 19.4 to 20rc1, where i believe was fixed.

> > If i maximize Kodi window, and turn back to its normal size, problem is solved!!!
> 
> For me "normal" kodi window size is maximized all the time (full screen)

I always use windowed.mode, or fullscreen by ALT+ENTER when i watch on Sport events (and also here i have some issues with 2 screens, 1 HDMI + 1 DP... HDMI full screen does not attach immediately, screen is blank and monitor does not get signal, i have to give ALT+TAB to get it lit and monitor gets HDMI signal; with DP no problems).

**Comment by thexai** [comment]
This seems like behavior caused by your peculiar setup with HDMI switch "KVM" and not a Kodi bug introduced in v19.4 or v20.0 so I don't think there is any real chance that this can be improved via software nor possibility of reproducing this with a different hardware / setup.

**Comment by verbal666** [comment]
> This seems like behavior caused by your peculiar setup with HDMI switch "KVM" and not a Kodi bug introduced in v19.4 or v20.0 so I don't think there is any real chance that this can be improved via software nor possibility of reproducing this with a different hardware / setup.

No, the problem is not KVM. Since the issue is present also when,

* Monitor goes standby after 30 minutes
* I manually turn off monitor and turn it on again

With these two actions, Kodi loses 30 pixel on bottom of its windowed screen layout.
