### ISSUE TITLE
AppleTV Dolby Vision & HDR Support

### ISSUE THREAD

**Issue by rimonhanna** [xbmc/xbmc#22281]
### Describe the bug
Here is a clear and concise description of what the problem is:

Streaming Dolby Vision and HDR content using Kodi for example using addons or any form of streaming content will not trigger HDR and DV rendering, instead the video is displayed with pink hue as if the TV doesn't support it

I'm using ATV 4k 2021, LG TV 4k with HDR and DV support, and Kodi 19.4

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should be able to render the HDR and DV content successfully

## Actual Behavior

Kodi doesn't render the content properly and is displayed with a pink hue

## Possible Fix

Use apple native media player sdk on Apple TV to utilise native support for HDR and DV streaming

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ X] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
It's not a bug. Feature isn't implemented.

**Comment by rimonhanna** [comment]
Any plans to implement it in Kodi 20? Maybe change it to a feature request instead of closing it?

**Comment by fuzzard** [comment]
Feature requests are made on the forums.
