### ISSUE TITLE
airplay-support not mature (solution: uxplay-integration)

### ISSUE THREAD

**Issue by slynobody** [xbmc/xbmc#22298]
### Describe the bug
airplay-support in most cases does not work - why dont you just integrate a newer and open solution like uxplay (https://github.com/antimof/UxPlay)?

## Expected Behavior
turn on airplay-support, stream content, turn of airplay-support

## Actual Behavior
in most of the cases, does *not* work, most current use-cases are not even supported.

## Possible Fix
use uxplay on an external konsole.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: debian sid
 - Kodi version: 19.4

**Comment by lrusak** [comment]
Please use the forum for support and feature requests. http://forum.kodi.tv

**Comment by slynobody** [comment]
i already did. no response.
