### ISSUE TITLE
[Xbox] Remote App-control not possible

### ISSUE THREAD

**Issue by queequac** [xbmc/xbmc#22297]
### Describe the bug
Kodi can be controlled via controller and physical infrared devices.
Nevertheless, controlling Kodi remotely from an app is not (or no longer?) possible.

## Expected Behavior
Navigation and media control works just like with a physical device.

## Actual Behavior
While the nexus button is still functional and will bring up the menu, all other keys are ignored by Kodi (or due to some technical restriction, they are not forwarded to Kodi)

## Possible Fix
None known

### To Reproduce
1. Install an app which allows to remotely control Xbox. Most popular and official one: Microsoft's Xbox App.
2. Select your Xbox and choose "Control remotely"
3. Try any keys... they are functional all over Xbox, including the dashboard and other apps.
4. Tryany keys while Kodi is running... no key is recognized.

### Your Environment
Tested with Xbox Series X and latest Kodi version as of 2022/12/22

**Comment by thexai** [comment]
Raise this question in the forum (https://forum.kodi.tv/showthread.php?tid=370745&page=6) since the information you give is very vague:

> controlling Kodi remotely from an app is not (or no longer?) possible.

what app?
"or no longer?" --> You should know if it worked before or not

latest Kodi version as of 2022/12/22 --> you live in the future  ;-)
"latest" is not a version number

Debug log?

**Comment by queequac** [comment]
@thexai I am explicitly mentioning in the reproduction steps the official "Microsoft Xbox App", so it is not really vague. :)
But the issue is the same on 3rd party apps that allow controlling Xbox remotely.

And no matter if it worked before or not - it should work. The Xbox app simply sends key/gamepad inputs just like a physical controller. You can control more or less any app - just Kodi seems either not to receive those events or something makes Kodi ignore it.

Kodi-Version is 19.90.905 (date was a typo, meant was the date when the issue was created)

PS: Can I get a debug log on Xbox? :?

**Comment by thexai** [comment]
It does matter: if it has never worked it is a "feature request" and if it has worked before it "could" be a bug. 

GitHub issues we only used for bug tracking. 

Support questions (as asking how obtain debug logs on Xbox) and feature requests go in the forum (forum.kodi.tv)
