### ISSUE TITLE
[Nexus] Top bar overlay doesn't always show

### ISSUE THREAD

**Issue by rien333** [xbmc/xbmc#22295]
### Describe the bug

There are a few of conditions that cause the 'complex top bar' (as I'll call it)  defined in [Custom_1109_TopBarOverlay.xml](https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/Custom_1109_TopBarOverlay.xml) to show.  With "complex top bar", I mean the overlay that shows the movie/tvshow logo, current time, and basically anything defined from [line 170](https://github.com/xbmc/xbmc/blob/31832046a522402db31fa0117dd789aac74bc8e3/addons/skin.estuary/xml/Custom_1109_TopBarOverlay.xml#L170) on.

One way to trigger this bar is to press <kbd>o</kbd> in Chorus (which presumably satisfies `Window.IsActive(videoosd)`). And indeed, pressing <kbd>o</kbd> one time causes the bar to show, and pressing <kbd>o</kbd> a second time hides it again. However, press <kbd>o</kbd> a _third_ time, and the bar remains invisible. Press <kbd>o</kbd> a fourth time, and the bar briefly flashes on screen, and then immediately hides. Effectively, after the first two presses of <kbd>o</kbd>, there's no way to make the bar visible again without some trickery (e.g. returning to the home screen).

## Expected Behavior

Kodi displays the movie/show's logo, genres, and the system time at the top of the screen when I trigger the video OSD (i.e. press <kbd>o</kbd>).

## Actual Behavior
The expected behavior only works for one cycle.

## Possible Fix

I would guess it's related to recently introduced timer mechanisms in Custom_1109_TopBarOverlay.xml. In fact, if I change estuary to show the 'complex top bar' (instead of the alternate, tiny seek bar) to display whenever Kodi is paused, and then revert https://github.com/xbmc/xbmc/commit/9a58bcbc9d5bcf4feac51b3745e4acbbaa4a8b35 (i.e. put `System.IdleTime(5)` after `Player.Paused +`), the top bar behaves as expected. (I know this revert is nonsensical, but it might be interesting that it fixes the problem).

### To Reproduce

1. Play a video 
2. Open Chorus or the iOS "kore" app (currently my only ways to control Kodi)
3. Press <kbd>o</kbd> four times when using a fairly recent Kodi Nexus build (or, on the iOS remote: press the hamburger menu four times)

### Debuglog

You mean `kodi.log`, right? Here's me opening a video and triggering the bug:
(https://gist.github.com/rien333/62c5678137d6e702bd91d95b2acbef63)

### Screenshots 
I could make a little video if needed.

## Additional context or screenshots (if appropriate)
N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux ARM 
 - Kodi version: Kodi Nexus v20.0rc1 (presume it extends to rc2 though)

I am running Kodi on a Raspberry Pi 3, if that matters.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
I cannot reproduce this. Also your linked commit doesn't make sense as it was re-written later by https://github.com/xbmc/xbmc/commit/2afc17fea68733f2f11546db3d279243499ada2c in https://github.com/xbmc/xbmc/pull/21328. Make sure you're actually running a recent nightly.

**Comment by rien333** [comment]
Thank you for looking into this! I guess I will try to test on a different machine. 

> Also your linked commit doesn't make sense as it was re-written later by https://github.com/xbmc/xbmc/commit/2afc17fea68733f2f11546db3d279243499ada2c in https://github.com/xbmc/xbmc/pull/21328.

I know. It's just that reverting part of that component inexplicably fixes the problem.

**Comment by enen92** [comment]
Note that this custom dialog is a replacement for the osd and was created to avoid displaying the osd (and possibly hide part of the screen and subtitles) when pausing or seeking. One of the conditions to NOT show this dialog is precisely the fact that the videoosd is active (and o in chorus makes the osd visible). For me it's working as designed, it's never shown whenever I hit "o" in chorus.

**Comment by rien333** [comment]
To my surprise, I cannot reproduce this issue on my x86_64 machine, and on another rpi I had lying around. 

Hence, the cause of the bug is probably somewhere on my side, though I have no idea how anything I could have done would change relatively fundamental behavior on kodi's part.

> For me it's working as designed, the custom dialog is never shown whenever I hit "o" in chorus.

FTR: what I call the complex top bar overlay _ought_ to be shown when you hit <kbd>o</kbd> in chorus. Indeed, it is shown on fresh installs on my two other machines. Perhaps I wasn't clear what I meant with "top bar overlay". Though to quote myself: "I mean the overlay that shows the movie/tvshow logo, current time, [time when video is finished, and so on]".

Thanks for having looked into this!

**Comment by rien333** [comment]
Confirmed that this only happens if you have the experimental [smartredraw](https://kodi.wiki/view/Advancedsettings.xml#smartredraw) feature turned on.
