### ISSUE TITLE
HEVC playback stutters since Kodi 19 on Raspberry Pi 2 and 3 - No problems with Kodi 18

### ISSUE THREAD

**Issue by egabosh** [xbmc/xbmc#22315]
### Describe the bug

Playback of HEVC/h265 on the Raspberry 2 and 3 is causing problems since the update from Kodi 18 to 19.4.
The problem only occurs with the Raspberry Pi 2 and 3. On the Raspberry Pi 4, HEVC playback works fine with the same videos.
Before the update with Kodi version 18, the same videos also ran without problems on Pi 2 and 3.

## Expected Behavior

Since playback on the Raspberry 2 and 3 worked fine with Kodi 18 I would expect this to work with Kodi 19.4 as well.

## Actual Behavior

The picture is jerky during playback and the picture and sound are not in sync.

## Possible Fix

Maybe there is a way to restore the behavior of the player from Kodi 18?

Maybe the kernel modules or the Raspberry firmware have changed with the newer Debian version (dtoverlay=vc4-kms-v3d?), so the Kodi player should be adapted as well or the new kernel/firmware has a bug or should be improved?

#### Problem behavior
1. installation Raspberry OS (Debian 11) on Raspberry Pi 2 or 3
2. apt install kodi # version 19.4
3. start kodi
4. play of example video 

#### smooth hevc playback
1. install Raspbian (Debian 9) on Raspberry Pi 2 or 3
2. apt install kodi # version 18
3. start kodi
4. play of example video 

Example-Video (Transformers Trailer):
https://web.defiant.dedyn.io/issue/transformers-hevc.mp4

```
# ffprobe transformers-hevc.mp4 
[...]
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'transformers-hevc.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.45.100
  Duration: 00:02:22.06, start: 0.000000, bitrate: 1374 kb/s
    Stream #0:0(und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv, bt709, progressive), 1280x640 [SAR 1:1 DAR 2:1], 1322 kb/s, 24.99 fps, 25 tbr, 12800 tbn, 25 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (HE-AACv2) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 48 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
```

### Debuglog

The debuglog can be found here:
https://web.defiant.dedyn.io/issue/kodi.log

## Additional context

According to https://github.com/raspberrypi/linux/issues/4112
setting of "dtoverlay=vc4-fkms-v3d,cma-256" in /boot/config.txt helped a bit but picture and sound are still not in sync.

Playing around with settings for the Kodi-Player was not successful. 

Trying to play the Video with a fresh xbian installation let Kodi crash.

### Your Environment
Used Operating system:

 - [ ] Android
 - [X] Linux
 - [ ] iOS
 - [ ] tvOS
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspberry OS / Debian 11 
 - Kodi version: 19.4

**Comment by rien333** [comment]
Kodi 18 achieved this through considerable modifications to ffmpeg. This modifications have since then been dropped for kodi 19 to simplify the code base, and to make it only use video decoding methods that have upstream support (which is desirable in terms of maintenance efforts) . For more information, see https://wiki.libreelec.tv/hardware/raspberry-pi.

In other words, this feature was intentionally removed, and is unlikely to return.

**Comment by basilgello** [comment]
@egabosh Can you try with ffmpeg5 and kodi 20 from unstable?

**Comment by egabosh** [comment]
> @egabosh Can you try with ffmpeg5 and kodi 20 from unstable?

@basilgello Yes, sure. Are there HEVC optimizations for Raspberry 2 and 3 in Kodi  20 in again?

**Comment by egabosh** [comment]
> In other words, this feature was intentionally removed, and is unlikely to return.

Thanks for the quick replies!
Understandable that the code is cleaned up. It's just on the other hand very inconvenient if you still have old Raspberrys in use and a collection full of HEVC videos.
Is it maybe somehow possible to get a Kodi 19 version with these ffmpeg HEVC optimizations or compile them in yourself?
Are there any Debian packages, a flatpak or an AppImage with Kodi 18 to run it on Debian 11?
I exclude a re-encoding of the complete HEVC video collection for energy cost reasons alone.
Due to delivery bottlenecks and/or very high costs for Raspberry 4s this option is also out of the question.
And with Kodi 18 or Debian 9 as in our current setup, it's probably not a very good idea for security reasons alone due to the end of support.
Are there any other ideas besides trying Kodi 20, which is still in development?

**Comment by basilgello** [comment]
@egabosh ffmpeg5 had some hevc improvements over 4.x. You should check the release changelogs of ffmpeg to say for sure. Or boot of live image and try out - 20.0~rc2 is in Debian unstable and bookworm.

**Comment by smp79** [comment]
> Are there any other ideas besides trying Kodi 20, which is still in development?

Kodi 20 and ffmpeg5 would not restore the GPU-assisted HEVC decoding for RPi2/3. Those RPi HEVC patches require MMAL framework which was [removed in Kodi 19](https://github.com/xbmc/xbmc/pull/16321).

Stick with Kodi 18.

**Comment by egabosh** [comment]
> > Are there any other ideas besides trying Kodi 20, which is still in development?
> 
> Kodi 20 and ffmpeg5 would not restore the GPU-assisted HEVC decoding for RPi2/3. Those RPi ffmpeg modifications for HEVC require MMAL framework which was [removed in Kodi 19](https://github.com/xbmc/xbmc/pull/16321).

I can confirm this. tried Kodi 20rc2 with Debian bookworm.

There also the playback of h264 has jerked just like hevc/h265!

I used the bookworm daily image from 2022-12-25 and installed kodi 20rc2 with apt install kodi.

For Kodi to start at all I had to add "dtoverlay=vc4-kms-v3d" to /boot/firmware/config.txt. 
So that the video playback does not generally crash with a CMS segfault I had to change from cma=64M to cma=256M in the cmdline.txt.
I tried this on Raspberry Pi 2.

**Comment by egabosh** [comment]
OK, so I understand that there is currently no way to play hevc/h265 encoded videos with Kodi (19) on the Raspberry 2 and 3. The same is probably true in the future, for example, for Kodi 20.
Hmm. Would have hoped that this support at least comes back in the future.

**Comment by da-anda** [comment]
not sure it will get better in the future. RPI 2 and 3 do not have HW acceleration for h265 and MMAL had been "hacked" to move some of the decoding burden of h265 away from the CPU to the GPU. I am not an expert on V4L2, but my guess is that those drivers likely will not be able to achieve the same as the vendor specific driver. But who knows. It also took years of optimizations to get medium bitrate 1080p h265 working on RPI3/MMAL
