### ISSUE TITLE
[Android] Kodi 20/21 always crash at first video playback (N€tflix addon only)

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#22312]
### Describe the bug
Here is a clear and concise description of what the problem is:

When you play a n€tflix video kodi crashes,
the weird thing is that this happens always for the first video played only

this crash has been reported to me by different android users

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

regular playback

## Actual Behavior

crash and exit to android homescreen

### To Reproduce

Install N€tflix addon and play a video

if crash not happens, try this step before play a video:
Open addon Expert setting "ESN \ Widevine settings", in the new window opened press "Reset" button and Ok button.
(i have no idea if could be a kind of relation, it is a bit obscure this crash)

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/asuquvafub.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

From the log seems that the crash happens when InputStream Adaptive has read the manifest
and could be maybe in the middle of Widevine initialization, this is a my theory.

Here there is the Logcat: https://paste.kodi.tv/uzocuviqik.kodi

The logcat reveals stack trace error details at line 4850 and 5100
(there are other playback attempts above that lines, but prints always same errors)

seems that could be a null array somewhere and in the stacktrace is always specified Zeroconf,
`CZeroconfBrowserAndroidDiscover::CZeroconfBrowserAndroidDiscover(CZeroconfBrowserAndroid*)`

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 11 NVIDIA Shield
 - Kodi version: master branch nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
I’m pretty sure that the stacktrace shown in logcat does not make sense. Zeroconf ctor will definitely not be called in this context.

**Comment by CastagnaIT** [comment]
just to let you know that by downgrading with a very old nightly apk
i managed to get a different stacktrace
https://paste.kodi.tv/nafizedupa.kodi

here shown that the problem could be in the `Encrypt` method call (`DRM::CMediaDrmCryptoSession::Encrypt`)
this method is called by the nf addon
i will try to check if by mistake i am sending a "null" param with the addon

**Comment by CastagnaIT** [comment]
i think to have found the cause at least seem to be the cause
should be due to `xbmcdrm::CryptoSession::RestoreKeys` when i call this seem to close the drm crypto session
then when `xbmcdrm::CryptoSession::Encrypt` is called cause the crash because the session is closed and cannot encrypt data

i have not understand why the session become closed,
a possible cause is that `xbmcdrm::CryptoSession::RestoreKeys` is called two times

now i will test the fix PR on addon side
anyway this type of error seem to be unhandled on kodi  core 
instead to crash should raise an exception to python addon
