### ISSUE TITLE
Movies queue up in Music Playlist

### ISSUE THREAD

**Issue by wutschel** [xbmc/xbmc#22316]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi can end up in enqueuing movies in the music playlist.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Long pressing  a movie / episode item and select "Play next" queues the selected item in the _movie/video_ playlist.

## Actual Behavior

When Kodi is in party mode, selecting "Play next" on a movie / episode item adds the item to the current playing _music_ playlist.

## Possible Fix

Unknown.

### To Reproduce

1. Set Kodi to Party Mode (in my case via JSON command from Kodi remote). 
2. This generates a music playlist and starts playback.
3. Select "Play next" via long press on a movie or episode in the Kodi UI.
4. Now the selected movie / episode item is queued in the music playlist and Kodi remote is informed via JSON command.

### Debuglog

The debuglog can be found here:
None.

### Screenshots 
Here are some links or screenshots to help explain the problem:

None.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

- This is also seen with Kodi 20 RC1.
- Report in the support forum: https://forum.kodi.tv/showthread.php?tid=370908&pid=3123039#pid3123039

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux Mint 19
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by scott967** [comment]
See my comment in thread

**Comment by wutschel** [comment]
Should I close this as "Won't fix"?
