### ISSUE TITLE
[Android] [Nexus] <Year> tag not scraped

### ISSUE THREAD

**Issue by Dogway** [xbmc/xbmc#22326]
## Bug report
`<year>` tag is not scraped when scraping local information (either TVShows or TVSeries) and thus the shows appear at the bottom when sorted by year.

## Expected Behavior
I would expect the `<year>` to be scraped correctly as in v19.3 for Android 12 also (Google TV)

## Actual Behavior
see "Bug report"

### To Reproduce
1. Download Kodi Nexus RC1 for Android 12
2. Scrape with the following nfo

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--created on 2022-11-18 15:45:14 - tinyMediaManager 3.1.16.1-->
<tvshow>
  <title>El Escarabajo Verde: Crudo Dilema</title>
  <originaltitle/>
  <showtitle>El Escarabajo Verde: Crudo Dilema</showtitle>
  <sorttitle/>
  <year>2012</year>
  <ratings/>
  <userrating>0.0</userrating>
  <outline/>
  <plot>La autorizaci├│n de las prospecciones petrol├¡feras de Repsol frente a Canarias por parte del Ministerio de Industria ha originado un conflicto pol├¡tico y social en el archipi├⌐lago. El Gobierno aut├│nomo es contrario a una actividad industrial a la que acusa de ser muy contaminante y peligrosa y que, a su entender, pondr├¡a en grave riesgo el principal motor econ├│mico de las islas: el turismo. Para el Gobierno central es ineludible explorar la posibilidad de extraer hidrocarburos por un equivalente al 10% del consumo energ├⌐tico nacional.</plot>
  <tagline/>
  <runtime>30</runtime>
  <fanart/>
  <mpaa/>
  <certification/>
  <id/>
  <imdbid/>
  <premiered>2012-01-01</premiered>
  <status>Ended</status>
  <watched>false</watched>
  <playcount/>
  <genre>Documental</genre>
  <studio/>
  <tag>biology</tag>
  <tag>naturaleza</tag>
  <trailer/>
  <dateadded>2022-11-18 05:04:11</dateadded>
  <!--tinyMediaManager meta data-->
  <user_note/>
</tvshow>
```

## Additional context or screenshots (if appropriate)
To 'fix' it, now you have to declare the `<premiered>` tag, while in previous versions the premiere was defaulting to 01/01/year.

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

Operating system version/name:
 - Kodi version: Nexus RC1
 -  Android version: Android 12L

**Comment by CastagnaIT** [comment]
year tag has been deprecated you have to use premiered tag
as specified on https://kodi.wiki/view/NFO_files/TV_shows

**Comment by Dogway** [comment]
Isn't this a UX regression?

**Comment by KarellenX** [comment]
Why would it be a regression if the tag has been deprecated.

Use <premiered> instead as advised by @CastagnaIT 

And please stop creating issue reports for items that are clearly not bugs. Use the forum for your questions.

**Comment by Dogway** [comment]
@KarellenX are you technically illiterate? Do you know what UX means? Github is for programming related tasks not to chit-chat, and air your personal issues.

If you expect everybody on Matrix to rescrape their whole libraries because someone on a whim decided to deprecate a non-bug you are on something.

And I will post as many issues as I encounter, despite illiterate individuals bombing them.
Sooner or later issues always come back to explode at your face.

**Comment by KarellenX** [comment]
Nobody decided on a whim to deprecate the year tag. It has been replaced with the premiered tag as it contains the year, month and day for a more precise ordering. This happened, at a guess, maybe 7+ years ago. Its not as if this was done yesterday. 

Nor can we be held responsible for how media managers create nfo files. Seems to me you are directing your issue at the wrong people. Direct them back to TMM and ask why they are not using the premiered tag.

Please stop being so antagonistic. I will not help you anymore due to your rude and aggressive nature.

**Comment by Dogway** [comment]
That's not true, I have many Kodi versions, 18.7 on PC, 19.3 on GoogleTV and 20 RC1 on Android tablet, but only 20 RC1 doesn't fallback to the <year> tag which is something that has changed on the Kodi side not the nfo as they are all the same.

This is an UX regression. So please stop bombing me with your personal issues.

**Comment by CastagnaIT** [comment]
@Dogway with each new software version the software evolves,
this leads to changes that may be more or less invasive

so you may find components that are abandoned/deprecated and/or replaced in different form
these changes are always documented, as i have already shown you in the wiki

if they were not documented it would mean it was a bug, but this is not the case
so you have to adapt your addon fto works with different kodi versions

the premiered tag is shown correctly in the kodi gui

**Comment by CastagnaIT** [comment]
@KarellenX yes many year ago has been done this deprecation,
but it was no longer cleaned code

with v21 we should consider to full remove the "year" field everywhere
(also from JSONRPC where "year" is set to "premiered" in faked way)
so we avoid misunderstandings

**Comment by KarellenX** [comment]
@CastagnaIT 

Yes I agree. It is probably about time the tag is removed in full.
IIRC there are some other obsolete tags that could also be removed to do with ratings and sets.
