### ISSUE TITLE
[Android] [Nexus] Wrong episode scraping -local information-

### ISSUE THREAD

**Issue by Dogway** [xbmc/xbmc#22328]
## Bug report
When scraping TVSeries with nfo files in local information mode, the scraped info is mangled, with wrong episode number and in occasions with repeated episodes. The scraping is being performed over SMB2 on a Windows 7 SP1 x64 host PC.

## Expected Behavior
I would expect the scrape to be correct as defined in the local information nfo file, as it worked in past versions.

## Actual Behavior
see "Bug report"

### To Reproduce
1. Download Kodi Nexus RC1 for Android 12
2. Scrape with the following episode nfo

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--created on 2020-07-28 00:26:38 - tinyMediaManager 3.1.7-SNAPSHOT-->
<episodedetails>
  <title>The Cross-Shaped Wound</title>
  <originaltitle/>
  <showtitle>Samurai X: Trust &amp; Betrayal</showtitle>
  <season>1</season>
  <episode>4</episode>
  <displayseason>-1</displayseason>
  <displayepisode>-1</displayepisode>
  <id/>
  <uniqueid default="true" type="anidb">1397</uniqueid>
  <rating>9.5</rating>
  <userrating>0.0</userrating>
  <votes>63</votes>
  <plot/>
  <runtime>0</runtime>
  <mpaa/>
  <premiered>1999-09-22</premiered>
  <aired>1999-09-22</aired>
  <watched>false</watched>
  <playcount/>
  <studio/>
  <trailer/>
  <dateadded>2020-07-28 00:01:14</dateadded>
  <fileinfo>
    <streamdetails>
      <video>
        <codec>h264</codec>
        <aspect>1.33</aspect>
        <width>1440</width>
        <height>1080</height>
        <durationinseconds>1769</durationinseconds>
        <stereomode/>
      </video>
      <audio>
        <codec>DTS</codec>
        <language>jpn</language>
        <channels>6</channels>
      </audio>
      <subtitle>
        <language>eng</language>
      </subtitle>
      <subtitle>
        <language>eng</language>
      </subtitle>
    </streamdetails>
  </fileinfo>
  <!--tinyMediaManager meta data-->
  <source>UNKNOWN</source>
  <original_filename>1x04. Act_4.mkv</original_filename>
  <user_note/>
</episodedetails>

```

## Additional context or screenshots (if appropriate)
Debug log: https://pastebin.com/htvQt4zk
![example](https://lh3.googleusercontent.com/pw/AL9nZEVPPEeAenNs2JS_Hn7AD4fYUKGNTpffn3R_tDhiBB8Ear-UZRaIju3rHUK6_jx13BOQkCf4MUJ_lBFxOd0Oyci-X3wPOmV8k2oGix-5KnGZR36O90Irj9vqzHTJveqZ44jJKhNlt4JSi8YAwU8BFrGi=w1906-h1192-no)

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

Operating system version/name:
 - Kodi version: Nexus RC1
 -  Android version: Android 12L

**Comment by CastagnaIT** [comment]
A debuglog is always mandatory when creating an issue

**Comment by Dogway** [comment]
I have the log, do you still need it? The issue is regex related:

`e(?:p[ ._-]?)?([0-9]+(?:(?:[a-i]|\.[1-9])(?![0-9]))?)`
`1x03. Rurouni_Kenshin_-_Tsuioku-Hen_-_Act_1_[1080p][05E67E80]`

**Comment by KarellenX** [comment]
>And chill out chap

Why would you respond with that antagonistic comment?

Why would you think that we _don't_ need it?

**Comment by Dogway** [comment]
Why people shoot before ask?

Why would I need the whole internet to scrub through 2000 lines of personal data when the issue is clearly regex related?
