### ISSUE TITLE
KODI source too slow on local network (gbit connection)

### ISSUE THREAD

**Issue by markg85** [xbmc/xbmc#22332]
Hi,

I've been using KODI for many years and have been equally as long be surprised by it's network transfer speeds.
Right now, on the new 19.5 release, this is still an issue.

It downright sucks!

On a local network where PC <> PC transfers get gigabit speeds, kodi still manages to complain about the source being too slow. This is when kodi is connected on the same local network. I have tried SMB, NFS and FTP, they all show the same symptom.

So something is thoroughly ruining KODI's ability to use local network resources and makes it a crawling slow nightmare that is frankly even unusable for any video higher then 720p resolution and bitrates for that resolution.

I did verify that my local network isn't the issue!

**This issue is many many many years old!**
I will not pollute the thread with many links but just searching the forums gives you a little too many buffering questions to consider it a non-issue. There are many blog posts/articles giving people "hints" on how to solve buffering issues. There even are youtube videos trying to explain fixes for the users.

**Environments I've tried KODI on (all with the same SMB shared source)**

1. Android embedded tv box (source too slow)
2. Windows desktop system (source too slow)
3. Linux raspberry pi 2, 3, 4, odroid xu4 (source too slow)
4. Linux desktop (x86, no arm) works just fine

From this you can safely say that architecture has nothing to do with the issue.
With the protocols i tried (SMB, NFS and FTP) you can conclude that there "probably" isn't an issue at the protocol level. It's somewhere else.

**Cache filling**
What i noticed time and time again is that forward cache filling (press CTRL+SHIFT+O to see) fills up incredibly slow on most places where i tested this. Thus again hinting at a throughput issue on local media.

An issue i found while debugging is the `cache_delay` value (you see that value represented behind the cache size in <num> ms` is often stupidly high. Like in the millions, even when you have cache. I'm not sure at all if that really is a bug that matters for this case but it's a bug for sure nonetheless. Note that this is a bit hard to reproduce. Seek back/forward with pausing a lot and you will begin to see this.

**A testcase**
In a local setup on an android tv box i have KODI (19.5) complaining about the source being too slow.
On that very same box i also have solid explorer. Within that app i made a connection to the exact same SMB network share. While solid explorer also doesn't saturate the gigabit connection, it did get between 5 and 10 megabytes/second. Which should be **well** enough throughput for even 8k content (i'm playing 1080p, ~140 minutes and ~20GB)

**Logging?**
Usually when debugging, logging could be helpful. In this case however, not so much. The case is super reproducible on **every** embedded kodi system out there. It's very likely reproducible on windows too. It's an easy case to hit and I've seen this been hit in every place that used kodi along with one of the mentioned protocols. You simply have to be lucky to not be hit by this.

**Please don't...**
Don't give me - well intended! - advice of checking my network, running speedtest or upgrading my system. I've gone through those years before and that isn't the issue. The issue is very definitely within the KODI codebase. Not in my network setup or hardware.

Don't advice me to change cache settings. The cache, while very conservative and low, are not the problem. Increasing the cache size only masks the actual problem. If you increase it far enough it might "fix" the issue for the video you're playing but you still have a dreadfully slow data transfer speed. Also, the default should be strong and good for where KODI runs. On android for example it's super difficult (to even impossible) to change those config files.

**Let's figure this issue out and nail it!**
I'm sure we can figure out where the issue is and make a patch for it!
On my end i have the unlucky effect of my development environment (linux desktop) being the one place where this whole is just not an issue. On all my embedded devices I do have this issues, but debugging there is a lot more complex then on a linux desktop. It would be helpful if someone with an easy to debug environment can reproduce this issue for ease of debugging.

Cheers,
Mark

**Comment by lrusak** [comment]
The log file is an important piece of an issue report. If you decide it's not important that's ok, but you issue will be invalid. You also didn't follow the issue template.

Also, your issue isn't really an issue and is more likely a configuration problem. As this is a bug tracker I'm going to close this. Please use the forum for support. https://forum.kodi.tv/

**Comment by markg85** [comment]
You can consider this more a "figure out what is wrong" or "research" bug. Like we need more input of places that cause this bug. Not of masking the bug with config changes (which are impossible to apply on android tv!)

> Also, your issue isn't really an issue and is more likely a configuration problem

**No!**

If what you claim is true then it is a bug on it's own too.

> Please use the forum for support. https://forum.kodi.tv/

I don't want to ask support.
I want to nail down the **actual** issue.

Could you reopen this issue please. I didn't spend all that time writing it just for it to be closed for reasons that look invalid to me.

**Comment by Dogway** [comment]
It might not be the case, but I read that using safer protocols such as SMB3 saturate the, in my case, WLAN bandwidth.
I'm using SMB2 and everything "seems" fine here, I'd swear even for 4K if I'm not far from wifi point.

**Comment by markg85** [comment]
Given kodi's ugly history in buffering, i'd look at network connectivity issues as the very last option. It's like 99.9999% guaranteed to be caused by kodi itself.

In the specific case i'm testing it on right now it involved a gigabit **wired** connection, not wireless.
I've already proven in my main post that network bandwidth - although not great - is easily capable of handling this data.

After @lrusak so rudely closed this without even giving a link of what those magical better settings might be, i went out to look for them.
I followed [this](https://androidpcreview.com/fix-kodi-buffering-problems-heres-how-to-modify-the-kodi-cache/) guide which eventually suggests to use these cache settings:
```
<advancedsettings>
  <network>
    <buffermode> 1 </buffermode>
    <readbufferfactor> 1.5 </readbufferfactor>
    <cachemembuffersize> 104857600 </cachemembuffersize>
  </network>
</advancedsettings>
```

Applying these settings on kodi - running as an app within android tv - is stupidly complex!
Copy a file to the KODI data folder? Not possible without rooting the device.
Copy using ADB? Possible when kodi was a debuggable packet, it's not. So not possible.
Changing the setting though kodi? Not possible, kodi doesn't have an option to set it.

What i ended up doing was installing a plugin that allows you to change cache settings.
And that **finally** seemed to be working. No complaints yet after 1 movie.
**It took me about 6 hours from googling till finally having the settings applied.**

There's a few lessons here to be learned and fixes for kodi to implement. If they even care.

1. Change the cache default to something that "generally" works. The above could be that setting.
2. Allow changing cache settings in the UI because kodi **will** get it wrong for at least some percentage of users who will need to find a way to change it like i did.

I would consider not having option 1 to be a prio 1 blocker bug for any future release. By now it should be super clear that there are buffering issues given the massive amounts of posts you can find about it form the past decade till tight now. I can - vaguely - imagine kodi not willing or able to fix the "actual" issue for whatever reason they have. But making the settings available within the ui without the need for a custom plugin would be the absolute bare minimum in my opinion.

**Comment by Dogway** [comment]
Yeah I agree, Kodi is a nice program run by monkeys, you can check the history of replies on closed issues, which in fact led me here.
I even gave a solution to a scrape regex issue and they ignore it. Toxic is an understatement.

With that said, you can edit any file (until the monkeys cap it) using the internal Kodi explorer. It will crash a few times but it will be copied from one side to the other, edit on Android or PC, copy back. Use [special](https://kodi.wiki/view/Special_protocol) handlers for blocked folders.

**Comment by lrusak** [comment]
Again, this is a bug tracker. Please use the forum for support.

Everything you have said could be resolved on the forum. Thanks for understanding.

**Comment by basilgello** [comment]
@markg85 @Dogway I took the responsibility to reopen this issue. However, let's stay constructive. "It downright sucks", "nice program run by monkeys" - I understand your frustration but that's disrespectful to all us Team Kodi members. You just dont come in a bar or church or govt office and behave that way. Why do you think Kodi community deserves such attitude?

Now about the logs. While you might claim they are useless to diagnose the problem, they are not. Have you enabled debug logging of cURL, SMB and NFS in a category list under Settings - Logging - Log specific components? I'd also like to see Audio-Video logging to understand when buffer takes place.

Again, if you want to help fixing regressions, let's fix them.

**Comment by basilgello** [comment]
Also, the CPU load matters on these SBCs. What are your Linux desktop specs? May it be BD Remuxes handled by, for example, i7 stutter on RPi4?

**Comment by basilgello** [comment]
On Linux (on odroids) you can use `htop` in ssh session to see which threads of Kodi consume the most of CPU power. On Windows, you can use SysInternals ProcessExplorer to do the same.

**Comment by basilgello** [comment]
Let's discuss it here: https://forum.kodi.tv/showthread.php?tid=370978
