### ISSUE TITLE
ElementTree Python standard library experiences random SegFaults on Python 3.11

### ISSUE THREAD

**Issue by jurialmunkey** [xbmc/xbmc#22344]
### Describe the bug
Here is a clear and concise description of what the problem is:

Random SegFaults are experienced when using the Python ElementTree module to parse XML metadata via `xml.etree.ElementTree.fromstring()`

The problem appears to occur more frequently on ARM chipsets. On Intel x64 I've only been able to reproduce the issue twice via LibreELEC in a virtual machine. However I have a number of users with ARM devices who can reproduce the issue fairly reliably.

Through a lot of trial an error we've narrowed it down to the CAccelerator in _elementtree.c in Python. See comment here and issue thread in general: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/948#issuecomment-1364672534

(NOTE: First issue in the above comment about offscreen ListItems has been addressed in TMDbHelper. It is the second issue in the comment related to ElementTree which persists)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

ElementTree can be used to parse XML metadata without worrying about Kodi crashing from a SegFault

## Actual Behavior

Kodi crashes randomly due to unexplained SegFaults in the _elementtree.c component

### To Reproduce

Difficult to provide an exact method to reproduce as crashes occur randomly. I don't own any ARM based devices so it is difficult for me to put together a simple test case. However, I do have a number of users who can provide testing as needed.

In TMDbHelper the steps are essentially:

1. Install my skin Arctic Horizon 2 and TMDbHelper from my repository -- https://github.com/jurialmunkey/repository.jurialmunkey
2. Get an API key from OMDb and enter it into TMDbHelper settings (OMDb API is the only API I use which has XML metadata). 
3. Restart Kodi to restart the service with the new setting.
4. Browse movies for a while to get the service to attempt to retrieve ratings and it will eventually SegFault when parsing XML metadata.

I've seen other add-ons have similar issues so it isn't limited to TMDbHelper. For instance see this thread where a similar issue is encountered with a color switching addon for another skin: https://forum.libreelec.tv/thread/26400-is-it-possible-to-downgrade-python-version-without-use-a-old-image-libreelec/#wcf40

The commit for the addon mentioned in that thread is here and explicitly mentions Py3.11 crashes and a "fix" that comments out ElementTree: https://github.com/semool/script.arctic.zephyr.mod.autocolors/commit/683ee3f827ef9a4c070f9c4a7fa3d9d6201e428a

### Debuglog

The debuglog can be found here:

Here's my debug logs from VirtualMachine running LibreELEC on x64 with backtrace showing SegFault in _elementtree
https://paste.kodi.tv/nalulopuco.kodi
https://paste.kodi.tv/ilonibiyub.kodi

See also this comment from one of my users on Ubuntu 22:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/948
https://paste.kodi.tv/giqavayuyu.kodi

And there's plenty of other users in that thread that can also provide detailed debugging

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 11 / Android / Ubuntu 22
 - Kodi version: Nexus RC 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
I would probably say someones going to have to take this upstream to cpython.

That involves a reproducible outside kodi.

With that said, it seems to sound very familiar to https://github.com/python/cpython/issues/92123
element tree with multi threads.

I would not expect a fix on the kodi end anytime soon, and would strongly suggest to follow that up with cpython.

**Comment by jurialmunkey** [comment]
Frustrating but I suspected as much that an upstream fix woud be needed.

> With that said, it seems to sound very familiar to https://github.com/python/cpython/issues/92123 element tree with multi threads.

That sounds extremely similar.

The crashes being caused by multiple instances of ElementTree running concurrently makes a lot of sense because ET is used in several common Kodi skinning tools like SkinShortcuts and SkinVariables which trigger at the same time onload in Home.xml

I had some earlier reports from Linux users already on 3.11 (prior to the wider release) where SkinShortcuts and SkinVariables triggerring at the same time would crash Kodi (I needed to add a staggered onload to avoid it). I also know AppleTV users reported needing to downgrade SkinShortcuts to avoid startup crash loops.

When Nexus releases I expect we'll see a large increase of crash reports from users not on Estuary because practically every custom skin uses SkinShortcuts.

**Comment by fuzzard** [comment]
Id probably start looking at alternatives then unfortunately.

I think i saw somewhere in your thread about someone blacklisting the c native ET module to use the fallback python native elementtree. Maybe thats the best of a shit situation for now until the upstream ticket gets some traction.

**Comment by mglae** [comment]
To create a notification here:

I've opened issue 100689 in cpython repo.

**Comment by semool** [comment]
@mglae Thanks for your Investigation. I have reverted your reported Commit: https://github.com/python/cpython/pull/24061 in my own xbmc Testbuild and for now everything is working fine.

**Comment by mglae** [comment]
@semool LGTM although I'm not using that code part. Please create a PR.

**Comment by SoulReaverFan** [comment]
Issue has been fixed upstream in Python and is now also merged and backported to Python 3.10 and 3.11 🎉 Have a great day everyone 🙂👍

**Comment by SoulReaverFan** [comment]
@fuzzard 
Python 3.11.2 is not expected to release before February 6th. Does todays bump to final stable Nexus 20 version mean the elementtree crash fixes have been cherrypicked from Python master branch or are these fixes most likely not coming before Nexus 20.1 release?

**Comment by po1vo** [comment]
> I think i saw somewhere in your thread about someone blacklisting the c native ET module to use the fallback python native elementtree. Maybe thats the best of a shit situation for now until the upstream ticket gets some traction.

This is what i did and what's been working for me.

**Comment by SoulReaverFan** [comment]
Good news! Python 3.11.2 has now been released. Now we just need a bump to this version in an upcoming Kodi nightly 👍

**Comment by thexai** [comment]
Fixed by https://github.com/xbmc/xbmc/pull/22737

**Comment by EraYaN** [comment]
It would be great if we could get this into some form of hot fix release for the ARM platforms and in the Play store.
