### ISSUE TITLE
Groups issues

### ISSUE THREAD

**Issue by Chris230291** [xbmc/xbmc#22343]
I have noticed some undesirable behaviour with groups.

I am using TVHeadend with the Kodi client addon.

I do not see all of my groups on the home TV menu... There seems to be a limit (15)?
If I select a group from the home TV menu, each time after that I open the EPG it will be the last group I selected from the home TV screen... Good that's expected.
However, if I change group inside the EPG screen using the side menu, when I leave the EPG screen, then go back, its set to whichever group was last selected from the home TV screen. What I would expect is to see the last group I selected from the side menu.

Its hard to explain but hopefully you understand. If not I can try to record it for you.

Chris

**Comment by ksooo** [comment]
> I do not see all of my groups on the home TV menu... There seems to be a limit (15)?

Good catch. needs to be fixed.

> However, if I change group inside the EPG screen using the side menu, when I leave the EPG screen, then go back, its set to whichever group was last selected from the home TV screen. What I would expect is to see the last group I selected from the side menu.

 Cannot reproduce on Kodi Nexus RC2.

**Comment by Chris230291** [comment]
I'm not sure what causes it but the second problem is inconsistent. It isn't happening for me either today.
The first issue is always there.

**Comment by Dogway** [comment]
Didn't quite understand your second issue, but for the first one I can confirm it, for either Movies or TV Shows (I guess Music too).
I can only access the rest of the Nodes when going up stream (the Back button), but I think those Nodes ignore Node rules (Limit, Groups, etc). Happens to me on v19.5 and 20 RC2.

**Comment by Chris230291** [comment]
Thanks
