### ISSUE TITLE
[feature request] Support for HDMI QMS (Quick Media Switch)

### ISSUE THREAD

**Issue by tamodolo** [xbmc/xbmc#22342]
### Describe the bug
This is a practical solution to implement even frame cadence for not that comom video speed as of even cadence for videos that have more than one speed in the timecode (MKV files support this. I can provide link to a video example of this if needed)

This is importante as 120Hz with HDMI VRR support become mainstream and 48 fps video more common as no TV have a 48 Hz native mode outside VRR.

## Expected Behavior
Use HDMI VRR capabilities (or any related tech as g-sync, freesync or dp adaptative sync) to produce even cadence aways.

## Actual Behavior
Playback will have judder in these scenarios

## Possible Fix
Implement VRR support. I sugest both solutions as HDMI 2.1a have the QMS mode that isn't focussed on games. For previous TVs that supports HDMI VRR, just VRR is enough as fallback.

### To Reproduce
Judder is the default behavior

### Debuglog
NA

### Screenshots 
NA

## Additional context or screenshots (if appropriate)
Improve compatibility

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Matrix (19.5)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Can you please post to https://forum.kodi.tv/forumdisplay.php?fid=9? We don't use GitHub issues for feature requests, only bug tracking.
Cheers

**Comment by tamodolo** [comment]
Thanks! I'll do that
