### ISSUE TITLE
NEXUS RC1 : Old saved playlists are being sorted alpabetically

### ISSUE THREAD

**Issue by iamzain1** [xbmc/xbmc#22352]
### Describe the bug
queueing an existing playlist are appearing alphanumerically sorted instead of in the order in which they were added

## Expected Behavior
if a playlist is added, the order should be as what is in the original playlist, not sorted.

## Actual Behavior

playlist are appearing alphanumerically sorted

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by robross0606** [comment]
Came here to find this.  Seeing exact same thing after upgrading from 19.4 to 19.5.  Not only are playlists sorting incorrectly, but the available menu options are different.  It has a "Sort by" option with options like "Date" and _none_ of them work at all. It continues to be sorted alphabetically no matter what you do.  The options to edit the playlist are also now missing.

**Comment by Groschi** [comment]
I can confirrm this issue in Nexus RC2, LibreElec 11.x nightly. The only sort options presented in the playlist context menu are: Name, Size, Date, File. Once i've selected any of those there is now way to switch back to the default playlist order.

**Comment by AshleyAshes** [comment]
Looks like this didn't get any useful attention at the time, but it was also reported and solved here, so this can be marked solved too?

https://github.com/xbmc/xbmc/issues/22580

**Comment by iamzain1** [comment]
> 

No, it can't be marked as solved because issue 22580 is a different issue.

**Comment by ksooo** [comment]
> No, it can't be marked as solved because issue 22580 is a different issue.

Nope. It is exactly this issue.

**Comment by AshleyAshes** [comment]
> No, it can't be marked as solved because issue 22580 is a different issue.

I think you have maybe not read that entire bug.

The issue was that the 'Playlist' and other sort options vanished between 19.4 and 19.5 and the issue continued into v20.  If you 'Played' or 'Queued' a playlist, it instead sorted alphabetically by default and didn't even have an option to sort in the playlist order.

So how is this a different issue?
