### ISSUE TITLE
[BUG] AMD Colourspace when playing BT2020 content

### ISSUE THREAD

**Issue by atoulmin** [xbmc/xbmc#22360]
I've noticed that in the current libreelec nightlies that if you start a HDR file with an AMD APU / GPU that it will start playing but not in the correct colourspace. It will play in SDR709. You then have to just return to the Kodi menu while playing and go back to Fullscreen and the output will then be correct at BT2020.

I've confirmed this issue on the AMD 5600G and the Radeon 6400 series.

This does not occur using my 12th gen Intel NUC.  I believe it might have something to do with this.

https://github.com/xbmc/xbmc/pull/21845

This triggers intel when playing BT2020 as the output is BT2020RGB.  However AMD uses BT2020YUV in the current MESA drivers.  Can the BT2020YUV be added as well?  I believe this may solve the issue.

I have pasted my log here.

https://paste.kodi.tv/tikisuwido.kodi

**Comment by lrusak** [comment]
Please follow the issue template when creating a bug report.

Currently Kodi shouldn't even switch the output to bt2020 as the support isn't merged. https://github.com/xbmc/xbmc/pull/21845

**Comment by Randrianasulu** [comment]
Is there possibility this bug related to issue described at

https://www.soi.pw/posts/10-bit-color-on-ubuntu-20.04-with-amdgpu-driver/

== quote ===
sudo cat /sys/kernel/debug/dri/0/HDMI-A-1/output_bpc
Current: 8
Maximum: 12

fix:

xrandr --output HDMI-A-0 --set "max bpc" 10 

==== quote end===

but obviously this will not work for gbm on tty , hm

Found this while looking at 30bpc support on Ultragrid github someone mentioned this link
https://github.com/CESNET/UltraGrid/discussions/203

Another article on same blog says sometines link between tv and gpu can't do full rgb so it goes down to 10 bit yvu 4:2:0 (as encoded by HEVC 10 Bit?)

https://www.soi.pw/posts/force-yuv420-for-10-bit-color-with-amdgpu-driver-on-ubuntu-20.04/

Still no colorspace setting, need to dig more ...

**Comment by Randrianasulu** [comment]
https://patchwork.freedesktop.org/series/111864/

===
"Revision 5

      This patchset is based on Joshua's previous patchset [1], as well as my previous patchset [2].

It is
- enabling support for the colorspace property in amdgpu, as well as
- allowing drivers to specify the supported set of colorspaces, and

Colorspace, Infoframes, and YCbCr matrix
===

found at very latest end of this bug:

https://gitlab.freedesktop.org/drm/amd/-/issues/476

**Comment by lrusak** [comment]
seems like an upstream limitation.
