### ISSUE TITLE
Request: Make channel names easier to read in PVR

### ISSUE THREAD

**Issue by Chris230291** [xbmc/xbmc#22405]
When using the PVR I often have to wait for the channel names to scroll to see which channel I am highlighting. This is because some channel names are too long for the space given.

Here is an example...

![image](https://user-images.githubusercontent.com/5328818/210850449-41affd5d-c9b5-42f9-8394-6b389cc2eefb.png)

Since I use alphabetical sorting, would it be possible to add a toggle to hide the channel numbers, giving more room to the names?

What about also making the number/name column a little wider?

I was able to edit a previous version of the Estuary skin to remove channel numbers completely and widen the column, but not sure how to make those user configurable.

**Comment by enen92** [comment]
Use the forum for feature requests

**Comment by Chris230291** [comment]
OK
https://forum.kodi.tv/showthread.php?tid=371126
