### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by ke46138** [xbmc/xbmc#22409]
I am using Ubuntu 18.04 and trying to compile Kodi for Android. The same thing happens with Ubuntu 16.
I used the instructions https://github.com/xbmc/xbmc/blob/master/docs/README.Android.md
When I run
**./configure --with-tarballs=$HOME/android-tools/xbmc-tarballs --host=arm-linux-androideabi --with-sdk-path=$HOME/android-tools/android-sdk-linux/cmdline-tools/ --with-ndk-path=$HOME/android-tools/android-ndk-r25b --prefix=$HOME/android-tools/xbmc-depends --with-ndk-api=16**
Terminal shows:
**checking build system type... x86_64-pc-linux-gnu
checking host system type... arm-unknown-linux-androideabi
checking for ccache... no
checking for curl... /usr/bin/curl
checking for tar... /bin/tar
checking for sha512sum... /usr/bin/sha512sum
checking for sha256sum... /usr/bin/sha256sum
checking for ranlib... /usr/bin/ranlib
checking for ld... /usr/bin/ld
checking for ar... /usr/bin/ar
checking for readelf... /usr/bin/readelf
checking for strip... /usr/bin/strip
checking for as... /usr/bin/as
checking for nm... /usr/bin/nm
checking for objdump... /usr/bin/objdump
checking for clang... gcc
checking for clang++... g++
checking for arm-linux-androideabi-llvm-ranlib... no
checking for llvm-ranlib... /home/kirill/android-tools/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
configure: WARNING: using cross tools not prefixed with host triplet
checking for arm-linux-androideabi-ld... no
checking for ld... /home/kirill/android-tools/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin/ld
checking for arm-linux-androideabi-llvm-ar... no
checking for llvm-ar... /home/kirill/android-tools/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
checking for arm-linux-androideabi-llvm-readelf... no
checking for llvm-readelf... /home/kirill/android-tools/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-readelf
checking for arm-linux-androideabi-llvm-strip... no
checking for llvm-strip... /home/kirill/android-tools/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip
checking for arm-linux-androideabi-llvm-as... no
checking for llvm-as... /home/kirill/android-tools/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as
checking for arm-linux-androideabi-llvm-nm... no
checking for llvm-nm... /home/kirill/android-tools/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-nm
checking for arm-linux-androideabi-llvm-objdump... no
checking for llvm-objdump... /home/kirill/android-tools/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-objdump
checking for arm-linux-androideabi-armv7a-linux-androideabi16-clang... no
checking for armv7a-linux-androideabi16-clang... no
checking for arm-linux-androideabi-armv7a-linux-androideabi16-clang++... no
checking for armv7a-linux-androideabi16-clang++... no
checking for arm-linux-androideabi-gcc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for unzip... yes
checking for zip... yes
checking for arm-linux-androideabi-g++... no
checking for arm-linux-androideabi-c++... no
checking for arm-linux-androideabi-gpp... no
checking for arm-linux-androideabi-aCC... no
checking for arm-linux-androideabi-CC... no
checking for arm-linux-androideabi-cxx... no
checking for arm-linux-androideabi-cc++... no
checking for arm-linux-androideabi-cl.exe... no
checking for arm-linux-androideabi-FCC... no
checking for arm-linux-androideabi-KCC... no
checking for arm-linux-androideabi-RCC... no
checking for arm-linux-androideabi-xlC_r... no
checking for arm-linux-androideabi-xlC... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... no
checking whether g++ accepts -g... yes
checking whether g++ supports C++17 features with -std=c++17... no
checking whether g++ supports C++17 features with +std=c++17... no
checking whether g++ supports C++17 features with -h std=c++17... no
checking whether g++ supports C++17 features with -std=c++1z... no
checking whether g++ supports C++17 features with +std=c++1z... no
checking whether g++ supports C++17 features with -h std=c++1z... no
configure: error: *** A compiler with support for C++17 language features is required.**

**Comment by basilgello** [comment]
I am afraid `--with-ndk-api=16` is not enough for C++17. Android API 16 is 4.1 - even 19.x requires minimum Android 6.0 (23).

**Comment by ke46138** [comment]
Thanks, it worked
