### ISSUE TITLE
Settings are hard to navigate

### ISSUE THREAD

**Issue by xeruf** [xbmc/xbmc#22403]
First of all, thanks for the great software, overall Kodi is felicitous and looks pretty professional.
I know FOSS often lacks designers, so I will try my best to be helpful.

### Describe the bug
Here is a clear and concise description of what the problem is:

We setup Kodi some time ago,
and in the recent days needed to modify something in the settings multiple times.
Each time, it took us minutes to find the right item it is under,
because many settings tiles have very few items while others have a big pile.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I find the setting intuitively.

## Actual Behavior

I searched for a setting, for example subtitle providers, and it took me a while to find them.
By the by, adding and navigating through subtitle providers is also a bit annoying.

## Possible Fix

1. Regroup the settings categories and consider an alternative navigation system (e.g. a tab bar where you always see the setting under the current tab, like for example in VLC)
2. Add a settings search

### Your Environment
Used Operating system:

 - Operating system version/name: LibreELEC
 - Kodi version: could check later, doubt it's relevant as it is recent

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please use the forum for feature requests.

https://forum.kodi.tv/

**Comment by xeruf** [comment]
Please link that in the issue templates.
