### ISSUE TITLE
Instant crash on startup of pvr.octonet

### ISSUE THREAD

**Issue by da-anda** [xbmc/xbmc#22419]
### Describe the bug
Here is a clear and concise description of what the problem is:

whenever I try to use pvr.octonet in Nexus (Android, Windows or RPI), KODI crashes. The add-on itself is loading fine, but as soon as I enter the IP of my octonet backend server in the add-on config and the add-on tries to connect to it (or processes the channels) KODI will crash. I am not sure if it is an issue with the add-on or in KODI itself. I tried it on Nexus RC2 as well as recent nightlies, all crash. I also tried 19.5 and it's running fine there. So I doubt it's something in my overall setup/configuration/channel list but a bug that snuck in during v20 dev cycle.

I already reported it in our PVR slack channel and @ksooo, who also has a Octonet server, unfortunately was not able to reproduce the issue in his setup.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

KODI should not crash

## Actual Behavior

KODI crashes

### To Reproduce

1. install KODI
2. install `pvr.octonet` addon
3. add the IP of the octonet server in the add-on config and apply
4. -> crash

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/umiyagiwim.kodi
Here is a [windows crash dump](https://mirror.elements-net.de/kodi_crashlog-20.0-RC2%20Git_20221219-a184a3a7fc-20230107-195007.dmp.zip) done with [this PDB](https://mirrors.kodi.tv/releases/windows/win64/kodi-20.0-Nexus_rc2-x64.pdb)
The stacktrace on Windows was unfortunately empty.

Here is a [crash log](https://mirror.elements-net.de/log-2022-12-29-12.23.53-FAILED.zip) from LibreElec with all additional logs it is collecting.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20 RC2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by da-anda** [comment]
@lrusak here is the ticket with all the data I could gather.

**Comment by ksooo** [comment]
```log
Thread 1 (Thread 0x649fe280 (LWP 1531)):
#0  0x74635e28 in pthread_mutex_lock () from /usr/lib/libc.so.6
#1  0x00d347ec in PVR::CPVRChannelGroup::Renumber(PVR::RenumberMode) ()
#2  0x00d34adc in PVR::CPVRChannelGroup::SortAndRenumber() ()
#3  0x00d34ca4 in PVR::CPVRChannelGroup::UpdateGroupEntries(std::vector<std::shared_ptr<PVR::CPVRChannelGroupMember>, std::allocator<std::shared_ptr<PVR::CPVRChannelGroupMember> > > const&) ()
```

Known issue with RC2, already fixed in latest Nexus nightly. @da-anda please try a nigthly and report back.

**Comment by da-anda** [comment]
you are right. Sorry, totally missed that change. I had tested RC2 (the most recent build with a PDB file on the mirrors) and the latest nightly at the day when I had reported it in Slack last year, but not the latest nightly before I wrote this ticket. So issue is already fixed, thanks.
