### ISSUE TITLE
Dolby Vision Tone Mapping

### ISSUE THREAD

**Issue by satmandu** [xbmc/xbmc#22411]
Dolby Vision files are now supported with tone mapping (so they can be watched on non-HDR displays) in Jellyfin as per https://www.reddit.com/r/jellyfin/comments/v2nudu/dolby_vision_to_sdr_hwa_tonemapping_is_coming using GPU acceleration & ffmpeg 5.x.

Jellyfin does it server-side... but that's effectively the same as doing the conversion in Kodi when Kodi is playing the video.

It would be nice to get that support in Kodi. (Especially since Kodi is a popular front-end for Jellyfin.)

(This is separate from actually supporting Dolby Vision files, which is as per https://github.com/xbmc/xbmc/issues/22408 almost all there.)

**Comment by quietvoid** [comment]
An option is to use FFmpeg with `vf_libplacebo`, `libplacebo` should be available on most Linux distros.  
However it is Vulkan only and FFmpeg is unlikely to be packaged with the options for it.

So the possible clients are quite limited at the moment.

**Comment by satmandu** [comment]
via [https://github.com/haasn/libplacebo](https://github.com/haasn/libplacebo): "libplacebo currently supports Vulkan (including MoltenVK), OpenGL, and Direct3D 11. It contains backwards compatibility code for very old versions of GLSL down to GLES 2.0 and OpenGL 1.3 and very old Direct3D feature levels down to 9_1."

**Comment by satmandu** [comment]
I guess jellyfin is using their own ffmpeg fork: https://github.com/jellyfin/jellyfin-ffmpeg

(But so is kodi, no?)

Would it help to try to get those changes pushed upstream?

**Comment by satmandu** [comment]
Looks like there are a bunch of dv fixes which have been added there, looking at https://github.com/jellyfin/jellyfin-ffmpeg/commits/jellyfin ...
