### ISSUE TITLE
Unadded items view

### ISSUE THREAD

**Issue by gerstemann** [xbmc/xbmc#22424]
## Roadmap or todo item
**Detailed Description**

Since there are some movies, series or music that kodi does not found - I would love to see a view, where I can only see the movies that are not in my library to add it manualy.

### Context

Its better to have this view than scrolling throuth hundreds or thousands of music or movie files.

### Possible Implementation

Just a selection in the movie or music or series screen - not in library or not added sorting list.

### Additional context, screenshots or links
Here are some relevant links or screenshots

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by enen92** [comment]
Please use the forum for feature requests, the issue section is only used as a bug tracker.

**Comment by enen92** [comment]
Btw the event log provides already this functionality (https://kodi.wiki/view/Event_Log).
