### ISSUE TITLE
Allow editing (network) sources

### ISSUE THREAD

**Issue by xeruf** [xbmc/xbmc#22420]
### Describe the bug

I can't edit a network source.

## Expected Behavior

 
I can edit it - if I want to change path or IP, I have to type it in completely new, which is quite annoying with a remote ^^

**Comment by lrusak** [comment]
Please use the forum for support, thanks!

https://forum.kodi.tv/

**Comment by xeruf** [comment]
This is not about support, this is pretty clearly a missing feature.

**Comment by lrusak** [comment]
Feature requests are made in the forum thanks!

https://forum.kodi.tv/
