### ISSUE TITLE
Add "1/2/3/5 items" to smart playlist limits

### ISSUE THREAD

**Issue by Moonbase59** [xbmc/xbmc#22432]
### Describe the bug
Here is a clear and concise description of what the problem is:

When creating/editing smart playlists, one can only limit the results to None/10/25/50/100/250/500/100.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Since manual editing (especially on devices like the FireTV sticks) is not easy for everyone, I’d suggest adding the entries "1 item", "2 items", "3 items" and "5 items" to the "Limit to" list.

Rationale: Often, say for a series evening, one wants to return only 1,2 or 3 items to be watched, say the next unwatched episodes of a series. Or one or two mystery movies.

It would just be great if this could be selected in the UI, and a playlist be created without the need of manually editing it.

## Actual Behavior

Only None, 10, 25, 50, 100, 250, 500, 1000 can be selected.

## Possible Fix

Add 1, 2, 3, 5 to the list.

### To Reproduce

Try to create a smart playlist that returns ONE or TWO random movies, or series episodes.

### Debuglog

The debuglog can be found here:
—

### Screenshots 
Here are some links or screenshots to help explain the problem:

—

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

—

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
   - Android as on Amazon FireTV 4K stick
   - Linux Mint 21, 21.1
   - Manjaro XFCE, Manjaro Cinnamon, both 22.0.0
   - Windows 10, Windows 11
 - Kodi version: 19.5 (on all above platforms)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Thanks for the suggestion but we only use github issues for actual issues. Please post your feature request at https://forum.kodi.tv/forumdisplay.php?fid=9
