### ISSUE TITLE
Kodi ignore file subtitle with refresh "from internet / local"

### ISSUE THREAD

**Issue by Nanomani** [xbmc/xbmc#22447]
### Describe the bug

Kodi ignore file subtitle .SRT with refresh "from internet / local"

## Expected Behavior

I expect When I add file subtile .SRT it was not ignored

## Actual Behavior

All is fine if : 

I update library the first time for a movie with his external file subtile.srt 
 => "strSubtitleLanguage" is not empty . 
 
I refresh a movie information "from internet / local" after deleted his external file subtile.srt 
=> "strSubtitleLanguage" become empty.
 
It is not good if : 
 
 I refresh a movie information "from internet / local" after add an external a file subtile.srt 
Kodi ignore file subtitle => "strSubtitleLanguage" stay empty. 

### To Reproduce

(I don't use local file nfo)

1. install kodi from scratch
2. keep all Kodi default settings. nothing more
3. add source with 1 movie folder without external subtitle file
4. update library
5. add a external subtitle file in same folder movie

eg : 
Maniac Cop (1988) 
 \ Maniac Cop (1988).mp4
 \ Maniac Cop (1988).fr.srt

6. refresh movie information "from internet / local" 
Kodi ignore file subtitle 

### Debuglog

The debuglog can be found here:

1 - update library with new movie "A" without file subtitle
2 - refresh information movie "A" after add file subtitle.srt

here debug log :  https://paste.kodi.tv/ufometubos.kodi

### Screenshots 

"strSubtitleLanguage" in table "streamdetails" if the external file subtitle is present before update library the first time for a movie : 

![2023-01-11_123720](https://user-images.githubusercontent.com/3939543/212026027-9f179bbc-8585-4eea-9615-261eed4a45ef.jpg)

"strSubtitleLanguage" in table "streamdetails" after refresh a movie information "from internet / local"  after add a file.srt : 

![2023-01-11_180019](https://user-images.githubusercontent.com/3939543/212026507-56cc0c5b-5344-40f8-a8da-208557ee873e.jpg)

### Your Environment
Used Operating system:

 - [ X ] Windows

 - Operating system version/name: Windows 11 Pro x64
 - Kodi version: Kodi (20.0-RC2 (19.90.905) 
 
Git:20230109-bbdf5686e0). 
Platform: Windows NT x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment]
I understand the issue, but I'm not sure what the actual problem is this introduces. Mind elaborating?

**Comment by Nanomani** [comment]
This is useful with some skins that manage this value to display a flag indicating if there is a subtitle and the language.
Or if we create a Smart playlists linked with this value.

![2023-03-26_103345](https://user-images.githubusercontent.com/3939543/227765100-022812d4-305c-4b02-9d7a-0d12bbcdf6c0.jpg)

![2023-03-26_104053](https://user-images.githubusercontent.com/3939543/227765106-b3ad787a-6668-439e-81f0-a7d31f706c57.jpg)

![2023-03-26_103604](https://user-images.githubusercontent.com/3939543/227765142-03712481-32de-44f9-8131-25754f0375b2.jpg)

**Comment by Nanomani** [comment]
Possible workaround : 
- stop kodi 
- delete  file "Textures13.db"
- restart Kodi

Then all new file .srt added  are detected

the relation between the base "textures13.db" and the external .srt files is difficult to understand but this is perhaps normal ?

**Comment by Nanomani** [comment]
This issue is obsolete.

With Kodi v21 table "streamdetails" is not updated at all for external file subtile in all case.
New issue need to be open
