### ISSUE TITLE
JIO TV, Addon not a single channel is getting play. from mid of december.

### ISSUE THREAD

**Issue by nihalkza** [xbmc/xbmc#22456]
### Describe the bug
Here is a clear and concise description of what the problem is: once got an update of 19.5, Installed in MI4K box everything was good for few days, after that few channel stop playing, after dec 25,2022 not a single channel is getting played.

## Expected Behavior
Here is a clear and concise description of what was expected to happen: JIO TV channel should be play

## Actual Behavior

Once clicking on any channel Loader is coming 2 times, after that nothing

## Possible Fix

Not sure what is the reason but same thing faced in Windows version as well not a single channel is getting play.

### To Reproduce

1. add botallen repo => install JIO TV => Login => from add-on setting, Install Sample IPTV PVR
2. Play any channel
3. channel must be play

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/59018927/212247714-90e56f62-3702-4c9a-b5d2-9b145cc179c5.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: MI Box 4K  & Windows11
 - Kodi version: 19.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Contact the addon developer. This tracker is only for the core Kodi program bugs

**Comment by Savan353** [comment]
how to track addon devloper
