### ISSUE TITLE
Nexus - Apple TV 4K - Apple remote is unusable

### ISSUE THREAD

**Issue by warnerbryce** [xbmc/xbmc#22458]
### Describe the bug
Since Nexus Nighlies the TvOS app isn't working well for the Apple Remote.
The centerTouch pad is totally funky, a tiny swipe and the cursor goes to the other side of the screen. 
Everybutton is pressed twice and the centerbutton for OK works only every third attempt.
I use my TV remote when i use Kodi on this Apple TV.

There is a conflict between the legacy Apple Remote handler and the Gamepad Controller handler. 
[https://forum.kodi.tv/showthread.php?tid=365753&pid=3123983#pid3123983](see there)

I don't know if this problem is actually fixed because i can't find an issue opened/closed about this. 
I use the last RC2 release at the moment.

### To Reproduce
Install every 20.x version of KODI for TvOS on an Apple TV 4K.
TvOS on version 16

Thank you for the great works you put into this project

**Comment by warnerbryce** [comment]
Just found this for those who can't wait a fix : 
Go into the Installed Add-On list and disable the Joystick Add-On. 
Reboot your Apple TV and you will get a normal usage of your Apple TV remote.

**Comment by TwilightMercy** [comment]
Didnt help disabling for me

**Comment by Jcarcinogen** [comment]
> Just found this for those who can't wait a fix : Go into the Installed Add-On list and disable the Joystick Add-On. Reboot your Apple TV and you will get a normal usage of your Apple TV remote.

Thanks, this worked for me. I had to use a 3rd party remote to navigate to the addon though.

**Comment by gmcmoz21** [comment]
How? I thought i disabled it. Still remote having issues.

> > Just found this for those who can't wait a fix : Go into the Installed Add-On list and disable the Joystick Add-On. Reboot your Apple TV and you will get a normal usage of your Apple TV remote.
> 
> 
> 
> Thanks, this worked for me. I had to use a 3rd party remote to navigate to the addon though.

**Comment by gmcmoz21** [comment]
Never mind just had to reboot kodi after i disabled it. That was tedious ! I had to use my phone and Apple Remote and be fast lol

**Comment by damanb1** [comment]
Great Suggestion disabling joystick.. did worked for me. thanks.

**Comment by KnowhereFern** [comment]
Just wanted to say that whoever thinks that Kodi on TV os should be used this way needs to be locked up as their are a menace to society.   Confirming that disabling Joystick (which took around 15 minutes) worked for me as well.

**Comment by garbear** [comment]
This has been fixed in the new version of the joystick add-on:

https://github.com/xbmc/peripheral.joystick/pull/272 (version 20.1.9-Nexus)
https://github.com/xbmc/peripheral.joystick/pull/271 (version 21.1.2-Omega)

When Kodi is run with the new version of peripheral.joystick, the problem should go away.

**Comment by wasimabbas-arm** [comment]
I can confirm the issue still exists in Nexus.

**Comment by fuzzard** [comment]
latest nightly?

**Comment by garbear** [comment]
Is this still a problem or can the issue be closed?

**Comment by warnerbryce** [comment]
For me it has been fixed in Nexus Alpha.
