### ISSUE TITLE
DXVA.cpp does not properly classify 1280x544 H264 video as HD and disables DXVA decoding on AMD Hardware

### ISSUE THREAD

**Issue by therealjoeblow** [xbmc/xbmc#22451]
### Describe the bug
Here is a clear and concise description of what the problem is:

Line 1080 in DXVA.cpp only checks the video image height to decide if the file is HD or SD.  It does not check the width.  If height<=576 the video is classified as SD.  Then it invokes the warning in line 1117 "DXVA: H264 SD interlaced has issues on AMD graphics hardware. DXVA will not be used."; and video playback uses software decoding instead of DXVA hardware decoding on AMD video cards.  Even though the file is infact progressive and not interlaced.  As a result, 1280x640 progressive H264 videos for example playback with the hardware decoder as expected; but 1280x544 progressive H264 do not, they use software decoding. 

In StreamDetails.cpp, in the routine beginning at line 580, both width and height are checked to determine the media classification for flagging in the GUI.  This would be better for determining whether DXVA is used for decoding rather than just height IMO.

See further discussion on the forum here:

https://forum.kodi.tv/showthread.php?tid=371023

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expect that all 960xZZZ and 1280xZZZ progressive HD content would playback using DXVA Hardware decoding not software

## Actual Behavior

These files play back using the software decoder instead of hardware.  Resulting in higher main processor utilization which ramps up the fan and makes the computer unnecessarily noisy in a home theater environment, especially when the video card is fanless and is able to decode these files fine.  Verified with MPC-HC outside of Kodi, these files all invoke the GPU Hardware decoder and playback fine without any issue. as they are progressive and not interlaced.

## Possible Fix

Suggest editing line 1090 of DXVA.cpp to read as follows:

  return (avctx->width <960 && height <= 576 && avctx->codec_id == AV_CODEC_ID_H264 &&

Then 720x576 and smaller video resolutions which are normally classified as SD would invoke the warning and software decoding fallback; but 960x544 and larger files would be classified as HD and use the DXVA hardware decoder.

Or alternatively, if there is an easier way to determine if the files are interlaced versus progressive and only invoke the warning and disable DXVA for actual interlaced content and not progressive.

### To Reproduce

1. Play any H264 progressive video with image dimensions of 1280x544 and check OSD for which decoder is used.  It will show SW.
2.
3.

### Debuglog

The debuglog can be found here:

https://hastebin.com/bozocitugo.yaml

### Screenshots 
Here are some links or screenshots to help explain the problem:

None.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Tried in both 19.4 x64 and 19.5 x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
@therealjoeblow if you write `#1080` (# + number) _you are linking PR's_ that not concern your issue
--please dont do this--

if you have to specify a line of a file you have to write `#L1080` (# + L + number),
but since you havent specified the file, you have to write the full http path plus the `#L1080`
please fix your description

**Comment by jjd-uk** [comment]
Have tidied up the report to remove the hashes creating the false links.

The DXVA.cpp link should be https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/DXVA.cpp#L1090

This was added by @thexai in https://github.com/xbmc/xbmc/pull/21044

The streamdetails.cpp link should be https://github.com/xbmc/xbmc/blob/master/xbmc/utils/StreamDetails.cpp#L591
