### ISSUE TITLE
iOS Kodi V21 20230106 IPTV Simple Pvr Error

### ISSUE THREAD

**Issue by sxbai** [xbmc/xbmc#22463]
### Describe the bug
Here is a clear and concise description of what the problem is: error <general>: Unable to load /private/var/containers/Bundle/Application/31AE052C-0078-4D0E-AAB0-097E5528A2F3/Kodi.app/AppData/AppHome/addons/pvr.iptvsimple/pvr.iptvsimple.20.6.1.dylib, reason: dlopen(/private/var/containers/Bundle/Application/XXXXKodi.app/AppData/AppHome/addons/pvr.iptvsimple/pvr.iptvsimple.20.6.1.dylib, 0x0001): code signature invalid (errno=1) sliceOffset=0x00000000,

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [x] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Error says signature invalid. So whatever your using to put it on isn't signing/fake signing the add-on dylib. You'll need to resign and install again
