### ISSUE TITLE
Kodi 20 - fatal error: charconv: No such file or directory

### ISSUE THREAD

**Issue by nephaste** [xbmc/xbmc#22475]
Dear Kodi Team

getting an issue on Ubuntu 18.04

compiling Kodi 20 from source, it remains in error for charconv not found

/share/Public/xbmc-20.0-Nexus/xbmc/addons/Skin.cpp:36:10: fatal error: charconv: No such file or directory
 #include <charconv>
          ^~~~~~~~~~
compilation terminated.
build/addons/CMakeFiles/addons.dir/build.make:433: recipe for target 'build/addons/CMakeFiles/addons.dir/Skin.cpp.o' failed
make[2]: *** [build/addons/CMakeFiles/addons.dir/Skin.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 52%] Building CXX object build/xbmc/CMakeFiles/xbmc.dir/GUILargeTextureManager.cpp.o
/share/Public/xbmc-20.0-Nexus/xbmc/GUIInfoManager.cpp:35:10: fatal error: charconv: No such file or directory
 #include <charconv>
          ^~~~~~~~~~
compilation terminated.

root@tbs464:/share/Public/xbmc-20.0-Nexus/build# find /usr -name charconv
/usr/include/c++/8/charconv

root@tbs464:/share/Public/xbmc-20.0-Nexus/build# g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

![2023-01-15_18-04-01](https://user-images.githubusercontent.com/3392684/212555570-3f0da27d-f9d4-450f-a7cd-49229690df74.jpg)
[CMakeCache.txt](https://github.com/xbmc/xbmc/files/10420737/CMakeCache.txt)

any idea on how to fix this issue ?

thanks a lot

**Comment by nephaste** [comment]
I could bypass giving the real path in GUIInfoManager.cpp

![image](https://user-images.githubusercontent.com/3392684/212556151-8aba3525-7f60-4b64-90ab-c5917e559e9f.png)

**Comment by nephaste** [comment]
same for the addon Skin.cpp

![image](https://user-images.githubusercontent.com/3392684/212556367-ad4fe5cc-4576-4a81-b98d-7de87e8fbfe5.png)

**Comment by nephaste** [comment]
same trick for 

/xbmc/guilib/guiinfo/PlayerGUIInfo.cpp

**Comment by fritsch** [comment]
There is no trick needed. You use the g++ 7.x compiler on your system and try to fix things with including stuff from libstdc++-8, this won't work like this.

Use the proper toolchain, e.g. g++8 or later.

**Comment by nephaste** [comment]
you are probably right , i will update it...

but seems to works, it builds complete replacing this in sources

![image](https://user-images.githubusercontent.com/3392684/212558129-99b50364-53c2-4d45-938d-2f2331eedd00.png)

**Comment by lrusak** [comment]
Please use the forum for support. https://forum.kodi.tv/
