### ISSUE TITLE
lib/libcurl.a(libcurl_la-version.o):version.c:function brotli_version: error: undefined reference to 'BrotliDecoderVersion'

### ISSUE THREAD

**Issue by craigcarnell** [xbmc/xbmc#22494]
### Describe the bug
At the final stage of cross compilation from x86_64 to aarch64, linking kodi.bin fails with: lib/libcurl.a(libcurl_la-version.o):version.c:function brotli_version: error: undefined reference to 'BrotliDecoderVersion'

## Expected Behavior
Links without error

## Actual Behavior
Fails to link kodi.bin

### To Reproduce
1. 

cd tools/depends
./bootstrap
./configure --prefix=/home/xbmc/opt/xbmc-deps --host=aarch64-linux-gnu --with-rendersystem=gles
make -j16

2.

make -C tools/depends/target/cmakebuildsys BUILD_DIR=/home/xbmc/kodi-build
cd /home/xbmc/kodi-build
make -j16

### Debuglog
```
[100%] Linking CXX executable kodi.bin
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld.gold: warning: build/platform/posix/utils/platform_posix_utils.a(PosixInterfaceForCLog.cpp.o): top level DIE is not DW_TAG_compile_unit or DW_TAG_type_unit
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld.gold: warning: build/playlists/playlists.a(SmartPlayList.cpp.o): top level DIE is not DW_TAG_compile_unit or DW_TAG_type_unit
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld.gold: warning: build/guilib/guilib.a(GUITextBox.cpp.o): top level DIE is not DW_TAG_compile_unit or DW_TAG_type_unit
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld.gold: warning: build/settings/lib/settings_lib.a(SettingsManager.cpp.o): top level DIE is not DW_TAG_compile_unit or DW_TAG_type_unit
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld.gold: warning: build/windowing/wayland/windowing_WAYLAND.a(InputProcessorTouch.cpp.o): top level DIE is not DW_TAG_compile_unit or DW_TAG_type_unit
/home/xbmc/opt/xbmc-deps/aarch64-linux-gnu-debug/lib/libcurl.a(libcurl_la-version.o):version.c:function brotli_version: error: undefined reference to 'BrotliDecoderVersion'
/home/xbmc/opt/xbmc-deps/aarch64-linux-gnu-debug/lib/libcurl.a(libcurl_la-version.o):version.c:function curl_version_info: error: undefined reference to 'BrotliDecoderVersion'
/home/xbmc/opt/xbmc-deps/aarch64-linux-gnu-debug/lib/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function brotli_close_writer: error: undefined reference to 'BrotliDecoderDestroyInstance'
/home/xbmc/opt/xbmc-deps/aarch64-linux-gnu-debug/lib/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function brotli_init_writer: error: undefined reference to 'BrotliDecoderCreateInstance'
/home/xbmc/opt/xbmc-deps/aarch64-linux-gnu-debug/lib/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function brotli_unencode_write: error: undefined reference to 'BrotliDecoderDestroyInstance'
/home/xbmc/opt/xbmc-deps/aarch64-linux-gnu-debug/lib/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function brotli_unencode_write: error: undefined reference to 'BrotliDecoderDecompressStream'
/home/xbmc/opt/xbmc-deps/aarch64-linux-gnu-debug/lib/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function brotli_unencode_write: error: undefined reference to 'BrotliDecoderGetErrorCode'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/kodi.dir/build.make:607: kodi.bin] Error 1
make[1]: *** [CMakeFiles/Makefile2:5039: CMakeFiles/kodi.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

```

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu v22.04 x86_64
 - Kodi version: master (today, also Nexus today)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Do you somehow have brotli on your system?

Can you look at the curl build output from the depends? It's likely autodetecting something and enabling it.

**Comment by craigcarnell** [comment]
> Do you somehow have brotli on your system?
> 
> Can you look at the curl build output from the depends? It's likely autodetecting something and enabling it.

I don't have brotli installed, but I do have libbrotli-dev and libbrotli:arm64 installed.

Does kodi use libbrotli? If not could libcurl be compiled with --without-brotli?

**Comment by wsnipex** [comment]
since we don't have brotli support in depends, this has to come from somewhere on the build host.

**Comment by craigcarnell** [comment]
@wsnipex @lrusak I have fixed this by adding --without-brotli to https://github.com/xbmc/xbmc/blob/master/tools/depends/target/curl/Makefile#L15

I cannot remove libbrotli-dev as it also removes libbluray-dev.

If brotli is not used in curl, I can make this a PR.

**Comment by wsnipex** [comment]
you shouldn't have any aarch64 packages on your build host, part from gcc and toolchain related files.
EVERYTHING needed for building kodi comes from tools/depends

**Comment by craigcarnell** [comment]
@wsnipex I have switched to a arm32 toolchain. I don't have any packages installed other than the minimal toolchain but I still get this error.

**Comment by craigcarnell** [comment]
@wsnipex Is brotli needed for curl? This definitely a build issue. I can either make a PR with brotli as a depend or add --without-brotli

**Comment by craigcarnell** [comment]
@wsnipex 

Output of make:

```
checking for BrotliDecoderDecompress in -lbrotlidec... no
checking for brotli/decode.h... no
```

and 

```
brotli:           no      (--with-brotli)
```

Don't ask me why, on this occasion it has built without changes..

**Comment by craigcarnell** [comment]
@wsnipex @lrusak Do I need brotli? Is it needed for curl?
