### ISSUE TITLE
Cross compilation to arm64 does not produce executable binary, static linking does not work either?

### ISSUE THREAD

**Issue by craigcarnell** [xbmc/xbmc#22508]
### Describe the bug
I have compiled kodi using the cross-compilation tools provided on a x86_64 Ubuntu 22.10 machine targeting a aarch64 Linux device. When I upload it to the target device, the file is not executable.

There are some differences, notably the architecture, aarch64 vs x86_64 and some differences in /lib installed.

I do not know how to trace the issue. I'm looking for something I missed when compiling?

## Expected Behavior
Launch kodi! Or another error.

## Actual Behavior
-sh: ./kodi-bin: not found

## Possible Fix
Compile statically, however this does not appear to work as it stops compiling below?

cd tools/depends
./bootstrap
./configure --prefix=/home/developer/opt/xbmc-deps --host=aarch64-linux-gnu --with-rendersystem=gles --enable-debug=no --with-target-ldflags=static

```
[ 53%] Linking C shared library libz.so
/home/developer/opt/xbmc-deps/x86_64-linux-gnu-native/bin/cmake -E cmake_link_script CMakeFiles/zlib.dir/link.txt --verbose=1
/usr/bin/aarch64-linux-gnu-gcc -fPIC -fPIC -DPIC -DNDEBUG=1 -Os   -isystem /home/developer/opt/xbmc-deps/aarch64-linux-gnu-release/include -Wl,--version-script,"/home/developer/kodi/tools/depends/target/zlib/aarch64-linux-gnu-release/zlib.map" -L/home/developer/opt/xbmc-deps/aarch64-linux-gnu-release/lib -Wl,-rpath-link=/home/developer/opt/xbmc-deps/aarch64-linux-gnu-release/lib -static -shared -Wl,-soname,libz.so.1 -o libz.so.1.2.12 CMakeFiles/zlib.dir/adler32.o CMakeFiles/zlib.dir/compress.o CMakeFiles/zlib.dir/crc32.o CMakeFiles/zlib.dir/deflate.o CMakeFiles/zlib.dir/gzclose.o CMakeFiles/zlib.dir/gzlib.o CMakeFiles/zlib.dir/gzread.o CMakeFiles/zlib.dir/gzwrite.o CMakeFiles/zlib.dir/inflate.o CMakeFiles/zlib.dir/infback.o CMakeFiles/zlib.dir/inftrees.o CMakeFiles/zlib.dir/inffast.o CMakeFiles/zlib.dir/trees.o CMakeFiles/zlib.dir/uncompr.o CMakeFiles/zlib.dir/zutil.o 
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: /usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/lib/../lib/libc.a(libc-start.o): in function `call_fini':
(.text+0x4): undefined reference to `__fini_array_start'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: (.text+0x8): undefined reference to `__fini_array_start'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: (.text+0x14): undefined reference to `__fini_array_end'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: (.text+0x18): undefined reference to `__fini_array_end'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: (.text+0x28): undefined reference to `__fini_array_start'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: (.text+0x2c): undefined reference to `__fini_array_start'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: /usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/lib/../lib/libc.a(libc-start.o): in function `__libc_start_main_impl':
(.text+0x350): undefined reference to `__preinit_array_end'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: (.text+0x354): undefined reference to `__preinit_array_start'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: (.text+0x358): undefined reference to `__preinit_array_end'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: (.text+0x35c): undefined reference to `__preinit_array_start'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: (.text+0x39c): undefined reference to `__init_array_start'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: (.text+0x3a0): undefined reference to `__init_array_end'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: (.text+0x3a4): undefined reference to `__init_array_start'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: (.text+0x3a8): undefined reference to `__init_array_end'
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: libz.so.1.2.12: hidden symbol `__fini_array_end' isn't defined
/usr/lib/gcc-cross/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[5]: *** [CMakeFiles/zlib.dir/build.make:321: libz.so.1.2.12] Error 1
make[5]: Leaving directory '/home/developer/kodi/tools/depends/target/zlib/aarch64-linux-gnu-release/build'
make[4]: *** [CMakeFiles/Makefile2:111: CMakeFiles/zlib.dir/all] Error 2
make[4]: Leaving directory '/home/developer/kodi/tools/depends/target/zlib/aarch64-linux-gnu-release/build'
make[3]: *** [Makefile:146: all] Error 2
make[3]: Leaving directory '/home/developer/kodi/tools/depends/target/zlib/aarch64-linux-gnu-release/build'
make[2]: *** [Makefile:25: .installed-aarch64-linux-gnu-release] Error 2
make[2]: Leaving directory '/home/developer/kodi/tools/depends/target/zlib'
make[1]: *** [Makefile:173: zlib] Error 2
make[1]: Leaving directory '/home/developer/kodi/tools/depends/target'
make: *** [Makefile:11: target/.installed-aarch64-linux-gnu-release] Error 2
```

I have also tried crossed compiled a helloworld program and uploaded it to the target which reproduces the issue:

aarch64-linux-gnu-gcc helloworld.c -o helloworld-aarch64-dynamic (DYNAMIC)
aarch64-linux-gnu-gcc helloworld.c -o helloworld-aarch64-static -static (STATIC COMPILED)

./helloworld-aarch64-static
```Hello World!``` (WORKS)

./helloworld-aarch64-dynamic
```-sh: ./helloworld-aarch64-dynamic: not found``` (DOES NOT WORK)

file helloworld-aarch64-static
```
helloworld-aarch64-static: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=e263ccdf57e30e489efd709980411d5efa2c9916, for GNU/Linux 3.7.0, not stripped
```

file helloworld-aarch64-dynamic
```
helloworld-aarch64-dynamic: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=8d3e25903b4bb0db1f9fb777977d61ee48594520, for GNU/Linux 3.7.0, not stripped
```

### To Reproduce
1. cd tools/depends
2.. /bootstrap
3.. /configure --prefix=/home/developer/opt/xbmc-deps --host=aarch64-linux-gnu --with-rendersystem=gles --enable-debug=no
4. make -j16
4. cd ../../
5. make -C tools/depends/target/cmakebuildsys BUILD_DIR=/home/developer/kodi-build
6. cd /home/developer/kodi-build
7. make -j16

This produces kodi.bin as a aarch64 binary, which is dynamically linked.

readelf -d kodi.bin
```
 0x0000000000000001 (NEEDED)             Shared library: [libasound.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libcec.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdbus-1.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libpipewire-0.3.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libass.so.9]
 0x0000000000000001 (NEEDED)             Shared library: [libwayland-client++.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libwayland-cursor++.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libwayland-egl++.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libdrm.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libGLESv2.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libEGL.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgbm.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libinput.so.10]
 0x0000000000000001 (NEEDED)             Shared library: [libshairplay.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-aarch64.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
```

### Debuglog
file kodi.bin

```
kodi.bin: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=22df028af42cf152a277e9f93d32a8737499eb29, with debug_info, not stripped
```

### Your Environment
Used Operating system:
 - [x ] Linux

 - Operating system version/name: Ubuntu 22.10 (x86_64), Linux (aarch64)
 - Kodi version: master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please use the forum for support. This is a bug tracker.

https://forum.kodi.tv/

**Comment by craigcarnell** [comment]
@lrusak Static compilation is broken. Is that not a bug?

**Comment by lrusak** [comment]
> @lrusak Static compilation is broken. Is that not a bug?
> 
> 
> 
> https://github.com/xbmc/xbmc/blob/master/tools/depends/target/zlib/02-all-static_only.patch#L8
> 
> 
> 
> How do you call a static build?

We don't. The build depends for Linux are purely for our CI builder. This always we can have cross compiled (and native) libraries that we need. We do not do any sort of run time testing with this and it will likely not work in quite a few ways (Mesa package doesn't enable all drivers, pipewire package only builds build time libs).

You really are on your own if you choose to use the depends build for runtime. I'm not saying that it can't work but it will require knowledge of what is required to have a working dynamic build (which involves installing the sysroot).

You are likely better off using a distro that is purposed for your board (LibreELEC (shameless plug), Armbian, arch-Linux-arm, yocto, etc).

So, it comes down to support help, which isn't provided via github issues, it's done in the forum. Anytime a github issue is created (or updated) 100+ developers get emails and notifications for it which then requires triage and takes away from other development time.

I hope that helps clear things up. Please make a forum thread with your issue and someone may take the time to help (you may also want to state your end goal as there may be an easier solution than cross compiling your own build).

Cheers.

**Comment by craigcarnell** [comment]
@lrusak Regarding what you have said, I have managed to finish building this using the build depends.

But I end up with CWinSystemWayland::InitWindowSystem - WAYLAND_DISPLAY env not set when I launch.

Is this something my end or is it due to using the builds depends? I mean should this version at least launch the GUI?
