### ISSUE TITLE
After update to Kodi 20 I can no longer "play" a source by rightclick source = there is no play option

### ISSUE THREAD

**Issue by irontechmonkey** [xbmc/xbmc#22506]
### Describe the bug
Here is a clear and concise description of what the problem is:

In Kodi 20  Right click on a video source no longer offers option to play entire source.

To reproduce: Open Kodi > Video> Files > right click on a video source = there is no option to play

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Open Kodi > Video> Files > right click on a video source = there should be (and was previously) an option to play

## Actual Behavior

Open Kodi > Video> Files > right click on a video source = there is no option to play

Additional notes: 

- Reproduced on 2 different Windows 10 PCs.
- Occurs for local and network sources (SMB shares or Kodi library shared from another device).
- Occurs with existing sources and newly created sources.
- The media is miscellaneous video clips of various formats.

## Possible Fix

Restore the option to play a source directly or describe how that can now be achieved.

### To Reproduce

The debuglog can be found here:

No debug log. I understand that you may close the ticket with no log but I could find nowhere else to post this and could not find any answer in change logs and forums.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

- Cannot play source directly.
- Cannot build playlists which I did by playing a source then saving to playlist.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro (2 computers)
 - Kodi version: 20
- Does not occur in Kodi 19 or 18 on Windows or Linux.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
What sense does it make to play a whole video source?

**Comment by irontechmonkey** [comment]
@ksooo  With all due respect, the fact you don't see the need for this is not a viable answer to what I have reported which is an unexplained regression in the applications functionality.

 Do you have any specific knowledge about why this functionality which existed in previous version of Kodi for all video sources in PC or Linux was removed from Kodi 20?

It is not unusual for someone to want to play an entire collection (AKA source) and make a playlist of it just as they may want to play from any directory. The source is merely the root of the tree and is no less viable a place from which to start playback than any other folder. This is probably why previous version of Kodi allowed "play" from root of source. 

Since this capability was in previous versions, and because root of source is no less viable a starting point for playback than is any other directory, the removal of this capability seems needless. I can certainly accept that there may have been a reason for this change but without any stated reasons it is a regression in functionality.

**Comment by ksooo** [comment]
@irontechmonkey It was removed by accident without specific reason. So we're facing a regression here, as you said.

**Comment by irontechmonkey** [comment]
> @irontechmonkey It was removed by accident without specific reason. So we're facing a regression here, as you said.

Thanks for the follow up and the confirmation. When I saw references in the change logs to clean up of context menus, I figured that was what happened. Unfortunately for me, playing videos directly from the source comprises the bulk of my use of Kodi so I’ll be sitting on v19.5 except for testing new versions on the second computer.

Also, just for what this is worth, my previous description of a usage case for the ability to play the entire source stands on its own, but I thought of another usage case which is more obscure but might make a stronger case for preserving this functionality. Case in point: one time when I was organizing a large collection of 20,000 clips spanning 30 years of different types of video and formats which was certain to contain some corrupt files, I had problems where a corrupt file would stop the library scan and duration count, or it would stop playback at the preceding file, or in rare cases FC the application. This was an issue with the files and not with Kodi, but the way I addressed it was to split the collection in 2 with each piece as a separate source; Then by repeating that process several times I was able to narrow down the list of potential bad files from within the original 20,000 to within a group of a few hundred which I could review manually. I could not have done that troubleshooting without the ability to play directly from source and save that as a playlist.

To be clear, I’m not trying to amplify the priority of this, but should there be any case made for intentionally removing this capability I would hope that these usage cases are considered.

Thanks again for the follow up. I’ll stay tuned.

**Comment by jjd-uk** [comment]
As a workaround you maybe able to initiate playback directly without using context menu. So with the source highlighted, what happens if you select the `play` button on remote? or using the `p` key (for play action) on a keyboard?

**Comment by jjd-uk** [comment]
Another workaround.

The play action on context menu is only missing at source level, it is still avaiable on folders below source level. For the type of scenario you've mentioned all you'd need to do is create a hieachary like

-> Test (source)
->Test -> Folder 1
->Test -> Folder 2

Then play appears on context menu for Folder 1 and Folder 2.

**Comment by irontechmonkey** [comment]
> Another workaround.
> 
> The play action on context menu is only missing at source level, it is still avaiable on folders below source level. For the type of scenario you've mentioned all you'd need to do is create a hierarchy like
> 
> -> Test (source) ->Test -> Folder 1 ->Test -> Folder 2
> 
> Then play appears on context menu for Folder 1 and Folder 2.
> 
> Note - these workarounds are merely ways for you to be able to use v20, I agree that ideally this regression should be fixed so these workarounds are not needed.

Thanks for that suggestion. That is how I would do this on a smaller and less organized collection of media that can easily and intrusively be moved around, but those 20,000 clips at about 3TB are organized across different drives and large folder structures so it's not practical to rearrange that structure or moving/copying files... hence one of the beauties of the Kodi source as play point.

IE, some bad files were causing Kodi to FC immediately upon starting to playing any source or playlist containing that media (sounds bad but easy to test).

> Remove one of the source directories
> Retest playback at source 
> reconfigure sources withing directory trees
> retest
> When the preceding seems no longer productive then switch to manual file management of the sort you suggest but at this point I'm moving a much smaller volume of less important and more likely damaged files out of the original source. Changing the source takes seconds but moving the media could take hours or days.

That being said, regarding the keyboard workaround. Mwah! Sorry, got carried away. The keyboard workaround works. Thanks! I use the mouse so much that I overlooked the keyboard commands. With the keyboard play command I can do the same source and playlist management that I could to in 19.x

As a regression (or new issue) this would seem to be much lower priority that just about any other of the reported issues but I do hope it gets addressed in a later version, and the low priority wont stop me from strengthening the case for restoring it. For instance the fact that the ability to play source by keyboard still exists further supports the case for maintaining the context menu play option at source, and also, AFAIK there is no other way to make a playlist from the root of a source that to play source then save as playlist.

In any event, with keyboard "p" I can do what I need to. Thanks again.

**Comment by jjd-uk** [comment]
I can certainly see valid use cases which why I'd agree it should be fixed.

For example on my NAS  I have both a `New TV` and `New Movies` folders which contains things I don't want added to Library, and these are added as seperate sources. I will sometimes use Play (via remote) to catch up on new epsiodes in the `New TV` folder (as watched content either gets deleted or moved) to queue the folder contents if I have an evening with nothing else going on, but that's pretty rare these days hence me needing to double check it still worked.

**Comment by ksooo** [comment]
Well, no need to fill more walls of text here. ;-) It's a regression and it will be fixed.

**Comment by jjd-uk** [comment]
@irontechmonkey in case you hadn't seen this is fixed in both Master (for v21 development) and Nexus v20 branches. The fix is included from todays v20 Nightly build `KodiSetup-20230121-09db987a-Nexus-x64.exe` at http://mirrors.kodi.tv/nightlies/windows/win64/Nexus/

In case you don't know, anything in that Nexus Nightlies after the 15th Jan is basically v20.0 with the addition of any fixes made after the release of v20.0 as we work toward a formal v20.1 bug fix point release.
