### ISSUE TITLE
ZDF Video plugin fails with error in log

### ISSUE THREAD

**Issue by Papafelice** [xbmc/xbmc#22509]
## Official plugin is different from repository code
The library file libzdfjsonparser.py is missing a single line that leads to a python exception.

## Expected Behavior
Activate ZDF Video plugin, search for titles, results are displayed.

## Actual Behavior
Search stops with error message, logfile shows python exception.

## Possible Fix
The installed plugin is missing line 205:

    if not 'hasVideo' in target: return False

in the file libzdfjsonparser.py compared to the files in the repository. The plugin should be updated and/or rebuilt.

### To Reproduce
Install plugin, activate search, type in any search text, press enter: Error message is shown

### Your Environment
Used Operating system:
 - [ ] Linux

 - Operating system version/name: Suse tumbleweed
 - Kodi version: 19 and 20

**Comment by lrusak** [comment]
Please post a debug log. It is a minimum requirement of any bug report.

**Comment by enen92** [comment]
Please bring this issue to the add-on developer, we only use GitHub to track Kodi core issues.
