### ISSUE TITLE
advancedsettings.xml ignored by client (Windows/Android) after update to Kodi20.

### ISSUE THREAD

**Issue by dhstsw** [xbmc/xbmc#22502]
Hi,

i have some clients running Kodi, on windows, linux and android.
Of course, all android devices updated by themselves.

I have a server running MariaSQL withh the centralized DB for kodi in it.

Everything was running fine until one of the (android) clients updated to 20.
It started, stated it was migrating the DB and now i find myself with clients unable to access the remote db.

Ran the client on windows (20) and same problem.
I noticed that everytime i run it, it creates local databases in the userdata/Database folder, despite having an advancedsettings.xml in the userdata folder (the one i always used).
So, i guess the whole advancedsettings.xml file is ignored.

## Expected Behavior

Being able to access my 'old' (or converted) db with my kodi clients.

## Actual Behavior

Database looks empty (but it's not: i checked the MyVideo121 table and it's populated with the 'old' datas).

## Possible Fix

no idea.

### To Reproduce

1. Run kodi 20
2. There's no data.

### advancedsettings.xml

copying it there, but i reiterate, it works perfectly with kodi 19.

```
<advancedsettings>
   <loglevel>2</loglevel>  
	<network>
    <buffermode>1</buffermode>
    <cachemembuffersize>139460608</cachemembuffersize>
    <readbufferfactor>10</readbufferfactor>
  </network>
  <videodatabase>
    <type>mysql</type>
    <host>10.0.1.25</host>
    <port>3306</port>
    <user>kodi</user>
    <pass>********</pass>
  </videodatabase> 
  <musicdatabase>
    <type>mysql</type>
    <host>10.0.1.25</host>
    <port>3306</port>
    <user>kodi</user>
    <pass>********</pass>
  </musicdatabase>
  <videolibrary>
    <importwatchedstate>true</importwatchedstate>
    <importresumepoint>true</importresumepoint>
  </videolibrary>
</advancedsettings>
```

EDIT: after some more testing is definitely the advancedsettings.xml being completely ignored by Kodi20 (both windows and android) AFTER doing the migration.

### Debuglog
**Can't post a log file: since advancedsettings.xml is being ignored, the logfile isn't being created at all.**
(attacched file is there only to being able to post thhis)

### Your Environment

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ x] Linux
 - [ ] macOS
 - [ x] Windows
 - [ ] Windows UWP
 
 
[fakelog.txt](https://github.com/xbmc/xbmc/files/10434857/fakelog.txt)

**Comment by dhstsw** [comment]
BTW: i also noticed that files, when i set content to a particular folder (being it movies, tv or whatever), kodi isn't actually saving it. It just defaults to "none" when checked again.

**Comment by rohitharkhani** [comment]
add version attribute and try I had a similar issue but it works with the version tag. 

`<advancedsettings version="1.0">`

**Comment by dhstsw** [comment]
> 

Thanks, but i already tried that: doesn't so anything on my clients.

**Comment by lrusak** [comment]
Please post a debug log as it will show the advancedsettings.xml file being loaded or not.

**Comment by dhstsw** [comment]
> Please post a debug log as it will show the advancedsettings.xml file being loaded or not.

Hi,

here it is:

https://pastebin.com/zKcwkMhV

In the log:

1) Kodi20 starts and migrates the MyVideos119 to MyVideos121 (i dropped the previously created one so it can generate it again);
2) After finishing migrating the DB, it shows no media;
3) i go in the Videos/Files menu and set my movies folder as "Movies" withh the Set Content Menu;
4) nothing happens; if i repeat the operation (Set content) the folder is still set as "none".

As said, the newly created MyVideos121 *is* populated.

I think i'm going crazy.

(just to reiterate: everything works fine with Kodi19 clients, at least, the only one i have left [on LibreElec]).

Thanks.

**Comment by dhstsw** [comment]
> Have you upgraded MariaDB recently by any chance, and not run mysql_upgrade after doing so ?
> 
> The issue, btw, is
> 2023-01-17 17:07:30.537 T:20176   error <general>: SQL: Can't determine list of routines to drop. , which is the sort of error I'd expect if you have upgraded MariaDB recently, but not upgraded the tables.

MM... that may be a problem.

I have MariaSQL running on a docker container and it updates itself :-/

Should i run the command before or after the database migration?

(also, i tried but i gives me this error:
/# mysql_upgrade
Warning: World-writable config file '/etc/my.cnf.d/custom.cnf' is ignored
Reading datadir from the MariaDB server failed. Got the following error when executing the 'mysql' command line client
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
FATAL ERROR: Upgrade failed

But i guess this is outside of the general topic).
