### ISSUE TITLE
Kodi android dolby vision is not activated for the android 10

### ISSUE THREAD

**Issue by rohitharkhani** [xbmc/xbmc#22503]
### Describe the bug
Device: Vu master piece glow. 
Problem: When I play dolby vision content dolby vision is not activated. I do not see dolby vision activated. However same version of kodi running on fire tv and connected same tv dolby vision is activated. 
TV android version 10.
Dolby vision certificate: yes. 
Other application dolby vision is working. NetFlix, hotstar, jellyfin, nova video player. 

## Expected Behavior
For dolby vision content it should activate dolby vision. 

## Actual Behavior
When video is played on kodi it does not activate dolby vision

## Possible Fix

Not sure, guess is it is woking on Fire tv stick because it is android 9 may be need to upgrade to new API for android 10. Not android developer So this might not be correct. 

### To Reproduce

1.  Android tv which supports dolby vision
2. Download dolby vision sample video and play it. 
3. It should display dolby vision and activate dolby vision profile.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 10
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
A debug log is a required minimum for any bug report. Please include one.

**Comment by rohitharkhani** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/10441393/kodi.log)

attached log

**Comment by rohitharkhani** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/10452841/kodi.log)

Apologies, I missed restarting. Attached new log after restart

**Comment by quietvoid** [comment]
Ah I missed the v20 part.

> I am confused. It does not work on android 10 or any version. I remember it did worked on firetv stick 4k max. I will test it again and attach log if required.

The FireTV Stick 4K Max supports Dolby Vision regardless of the container, most devices don't.

**Comment by rohitharkhani** [comment]
Thanks. Let me try v21 nightlies. I will try with both jellyfin and SMB.

**Comment by rohitharkhani** [comment]
Thanks, I have two videos one is not working however another worked with v21

**Comment by quietvoid** [comment]
That file is profile 4, which is deprecated.
Not surprising if devices don't support it anymore.
