### ISSUE TITLE
 Kodi 20 freezing when accessing folders or addon page with non English characters

### ISSUE THREAD

**Issue by steph09** [xbmc/xbmc#22518]
**Describe the bug**

I installed Kodi 20 on my Windows 10 PC when it was released & everything seemed to be working OK. However I noticed that when trying to access a folder, Browse a Youtube channel or some other addon page that included a file with odd characters in the filename (Which usually displayed as square boxes on Kodi 19) it immediately causes Kodi to freeze.

I was using the xonfluence skin initially but experienced the same thing on several other skins which I have tried although at times more severe as it would freeze with just Japanese or Korean characters in filenames/video titles.

The issue isn't present when using Estuary with the default font however Kanji & other asian text is displayed as boxes & upon changing the font to 'Arial Based' Estuary then also starts causing freezes when trying to access folders/addon pages that feature non western characters in filenames/video titles.

**To Reproduce**

I've tried a clean install of Kodi 20 with no addons installed & have been able to reproduced the issue on both Windows 10 & a Chromecast with Google TV I have. Upon downgrading back to Kodi 19 the issue isn't present.

Here is a Log with all addons disabled. 
https://paste.kodi.tv/cazacecozo.kodi

**Comment by scott967** [comment]
We require that you use the full issue template when submitting an issue.  I can reproduce but ask you first close this and open new issue with filled-in template
