### ISSUE TITLE
Kodi 20: the default subtitle font is displayed as normal style, if I set the style as bold.

### ISSUE THREAD

**Issue by dragonlexus** [xbmc/xbmc#22513]
In the new kodi 20 Nexus version, the default subtitle font is displayed as normal style, regardless if I set the style as bold.

There are no problems if I set the style to italic (or normal), in this case the subtitle is correctly displayed in italic font style (or normal)

So the problem appears only with the bold style of the default font.

In kodi 19.5 this problem does not exist (the same Android device).

## Expected Behavior

The default subtitle font to be displayed as bold style, if I set the style as bold.

## Actual Behavior
The default subtitle font is displayed as normal style, regardless if I set the style as bold.

## Possible Fix
I didn't find a fix, but I tested with several fonts and if I add additional fonts in the Media/Fonts folder (created by me), for example 2 files: Verdana.tff and Verdana-bold.tff,), Then the subtitle is displayed correctly with Verdana bolt font. But I want your default font because I've been using it for many years and I'm used to it, and any other font seems annoying

### To Reproduce
The default subtitle font is displayed as normal style, if I set the style as bold.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

### Your Environment

 - [ ] Android

 - Operating system version/name:
 - Kodi version: 20.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by dragonlexus** [comment]
There is a small difference between normal and bold, but it is a little noticeable on Android version 20. I only noticed it after taking photos (on Windows 10, the difference is more pronounced).

But, visually analyzing the font, it seems to me that the font was actually changed or modified in version 20.00? Look at the letter "ă" in the image, it seems totally changed.

Maybe because of this, the subtitle style is not bold enough anymore?
![kodi font change](https://user-images.githubusercontent.com/122963894/213150803-a5c219db-ad45-4127-8447-ba31a00f4b98.jpg)

**Comment by dragonlexus** [comment]
I somehow solved it; I added a new font (Roboto-Bold) in Kodi, which is quite similar to me in terms of thickness and appearance to the font that appears for me on Kodi 19.5 on my box with Android 9.

PS: Beyond these minor aspects, I want to thank everyone involved in this project, which for me, is the best media software and fulfils all my entertainment needs. I use Kodi every day for several hours a day, it is an exceptional media centre! Thank you again! This report can be closed from my point of view.

**Comment by enen92** [comment]
The font kodi uses in kodi 20 is exactly the same as the one used before in kodi 19. However the shaper and the subtitle engine itself are totally different (and way better and extensible). Thus, it's normal that you note a few differences on the generic appearance of subtitle overlays.
I think you've followed the right path, if somehow you don't like the look and feel of subtitles just use another font. Note that the font kodi ships is "custom built" to include a few more codepoints than other public available fonts so you might find some absent characters with your new font.

There'll will be probably a bit of work regarding fonts subtitles in v21 since the font we ship is called arial but it's actually dejavu sans.
Thanks for the kind words to the project, being built entirely by volunteers on their free time it's definitely something we appreciate, and doesn't come every day :)

**Comment by scott967** [comment]
Just to add to enen92 comment, in Kodi 20 we do text shaping via open source harfbuzz library.  Text shaping uses 2 otf font tables (GPOS and GSUB) that prior Kodi versions did not so that might explain why the same font can render differently.

**Comment by thexai** [comment]
Also I'm not sure if settings migration from v19 to v20 is perfect on subtitles.

The safe way is reset all subtitle settings to defaults and customize from here. 

See:
https://forum.kodi.tv/showthread.php?tid=371500&pid=3134585#pid3134585

**Comment by vagvalas** [comment]
You are right...
I even (in a jailbroken AppleTV 4k) tried to copy "arial.ttf from kodi 19.x and appeared as "Default dejavu sans" and 2nd "dejavu sans" click even 1st or 2nd doesnt matter.

I had to add to developers, that the new engine of rendering has (maybe) a "weight" value (as css in some browsers eg. gecko engine) so i think if we can adjust the weight to some value, to some else.
make a look on weighting fonts..
