### ISSUE TITLE
unable to change default player in google TV

### ISSUE THREAD

**Issue by hamidsaeed13** [xbmc/xbmc#22514]
### Describe the bug
Here is a clear and concise description of what the problem is:

it is not possible to access android/data folder in android TV so i am not able follow this tutorial https://kodi.wiki/view/HOW-TO:Use_external_players_on_Android
it is therefore requested to please add playercorefactory.xml in the apk and make VLC as default player. thankyou so much for your kind consideration. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by gusandrianos** [comment]
> it is therefore requested to please add playercorefactory.xml in the apk and make VLC as default player. thankyou so much for your kind consideration.

What you are requesting here is specific to your use-case and it isn't possible to make this change.

Can you help me understand what's the issue? Which version of Android TV do you have? If you install a file explorer like File Commander, are you not able to see the Android/data folder and write to it?

**Comment by maxlefou** [comment]
I have the same problem.

In v19, i was having issues reading some files, notably avi files (!) so I followed the advices of the wiki about [external players](https://kodi.wiki/view/External_players) and made a `playercorefactory.xml` so the VLC app was being used for these files. It was working as expected.

And then kodi update to v20 and this stopped working. VLC is called as expected, but then it goes back to kodi and pretends the file "is not there". Playing the same file directly in VLC works.

Just in case, the content of my `playercorefactory.xml`:
```
<playercorefactory>
  <players>
    <player name="VLCPlayer" type="ExternalPlayer" audio="false" video="true">
      <filename>org.videolan.vlc</filename>
      <args>--fullscreen "{1}"</args>
      <hidexbmc>true</hidexbmc>
      <playcountminimumtime>120</playcountminimumtime>
    </player>
  </players>
  <rules action="prepend">
    <rule video="true" player="dvdplayer">
      <rule filename=".*265.*|.*HEVC.*|.*hevc.*" player="VLCPlayer"/>
      <rule filetypes="avi" player="VLCPlayer"/>
      <rule filetypes="AVI" player="VLCPlayer"/>
    </rule>
  </rules>
</playercorefactory>
```

**Comment by gusandrianos** [comment]
@xbmcspain @hamidsaeed13 You can use Kodi's internal file manager to make the file and it will work.
