### ISSUE TITLE
No audio after go to menu while playing

### ISSUE THREAD

**Issue by mkaflowski** [xbmc/xbmc#22522]
### Describe the bug
I use Nvidia Shield. I have audio passtrough activated. When I press menu during playback I get lost audio in the system. I need to go back to kodi, play video and press stop on the kodi navigation. It is not a problem to me but I have configured the system for my parents and they don't always remember how to stop a video.

## Expected Behavior
There should be an audio in the system and other apps.

## Possible Fix
Is it possible to fix it like add some code to onStop()? 

### To Reproduce

1. Activate audio passtrough
2. Start playing video
3. Press menu button on remote ("circle")
4. There is no audio

### Your Environment
Used Operating system:

 - [x] Android (Nvidia Shield)
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19 and 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Passthrough is an exclusive format. Only this plays and nothing else. There is no mixing possible.

What would you propose?
Stopping Audio-Engine, when focus is lost? Only stopping audio engine if an "exclusive format" is playing? Stopping Videoplayback as well? What about kodi used as a music player where passthrough formats might be played?

**Comment by mkaflowski** [comment]
Didn't thought about using kodi as music player. Maybe stopping playback only for video or an option in settings?

**Comment by fritsch** [comment]
Thanks for your feedback. Hehe - I always take wise choices, e.g. not deciding about other people's usability ;-). Someone might come up and say: I hear youtube music from within kodi via the youtube plugin, why do you stop my audio.

But thanks - that might be a candidate for actually a GUI option, but I agree with you that the default behavior of kodi on android should be the proper Android behavior and e.g. stopping video (take care: pause is also not good, if you do PVR it will buffer for days) and releasing the audio, means stopping all music. <- one can argue here a lot ... but Android is quite clear here and later Android versions even enforce this policy.

Let's see what the others think.
