### ISSUE TITLE
Kodi 20 EventServer Issue 

### ISSUE THREAD

**Issue by pejobo** [xbmc/xbmc#22521]
### Describe the bug
I noticed that the navigation buttons of my remote app on Android (Yatse) were no longer working after updating to Kodi 20 stable. I installed the Kore App and there it worked. The Yatse developer asked me to check the kodi.log where I found the following error when toggling the event server option in the Kodi settings:

````
2023-01-18 20:50:48.757 T:429      info <general>: ES: Stopping event server with confirmation
2023-01-18 20:50:55.410 T:429     error <general>: JSONRPC Server: Failed to connect to sdpd
````

_Update_ The first line is "disable event server from UI", seven seconds later I re-enabled it from the UI (2nd line). I missed to copy the 3rd line which states "info <general>: JSONRPC Server: Successfully initialized".

## Expected Behavior
Navigation events should work. 

## Actual Behavior
They do not work, at least according to Yatse and his developer @Tolriq

_Update_ I confirmed with the python example.

## Possible Fix
Yatse has per host options to disable usage of the event server from the App. This fixes the problem. 

### To Reproduce
1. Install yatse on Android device 
2. Connect it to your kodi instance 
3. try to navigate 

### Debuglog
See above 

### Screenshots 
None

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: arch linux arm 5.15.87-1-rpi-ARCH

 - Kodi version: 20.0.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pejobo** [comment]
Forgot to mention: the listen port 9777 is opened by the kodi.bin process, I did check this with ss

**Comment by Tolriq** [comment]
Since I'm mentioned :)

> ES: Stopping event server with confirmation

If Event Server is stopped it can not work there's no according to anyone involved ;)

Anyway let me gain you some time, they will need the proper full logs, not just 2 lines.

**Comment by pejobo** [comment]
The event server is running, as said above. I restarted it to ensure it's no UI glitch. And as also written above the kodi binary is listening on the event server port.

In the meantime I tested with the examples provided here in the repository (I used the python version for the sake of simplicity, example_simple.py). This cause also no visible effect. From my understanding it should at least issue the "move right" event.

**Comment by pejobo** [comment]
Hmpf, the port is also open when disabling the "allow remote control" option.
And for clarity: the python test was conducted from localhost.

**Comment by pejobo** [comment]
I was missing the log line after the error message (and the line break in the intial post is also missing), so for completeness I did the same procedure again:
````
<disabling in the ui "Allow remote control from applications on this system">
2023-01-18 23:13:48.660 T:429      info <general>: ES: Stopping event server with confirmation
<re-enabling the same option, "Allow remote control from applications on other systems" is still "on">
2023-01-18 23:13:52.174 T:429     error <general>: JSONRPC Server: Failed to connect to sdpd
2023-01-18 23:13:52.175 T:429      info <general>: JSONRPC Server: Successfully initialized
````

**Comment by pejobo** [comment]
After a bit of digging in the code (starting [here](https://github.com/xbmc/xbmc/blob/68c684efc931107b8bb3e15d8a006d0c01731991/xbmc/network/TCPServer.cpp#L441)) and some internet search I'm pretty sure the error message is a red herring.

**Comment by Tolriq** [comment]
Funny how you act exactly the same despite the previous remark, not reading and knowing better.

So you keep not providing the full Kodi logs that have the necessary information about the startup of Event Server and you are certain that the JSONRpc not starting it's TCP receiver over bluetooth (So 2 completely unrelated things) is the cause of your issue. 

I got all right?

Good luck to Kodi support I'm out now. (For the record ES works perfectly here and for many other users)

**Comment by jodeleit-es** [comment]
> I got all right?
no
> [..] I'm out now [..]
bye

**Comment by pejobo** [comment]
> I got all right?

no

> [..] I'm out now. [..]

bye

**Comment by enen92** [comment]
This sounds like an issue only affecting your setup and not an actual bug. Maybe bring this to the forum for support.
