### ISSUE TITLE
pvr.waipu stopped working after update to Kodi 20

### ISSUE THREAD

**Issue by TheRealDarklord** [xbmc/xbmc#22527]
### Describe the bug
After upgrading Kodi from 19.5 to 20.0 on my ubuntu jammy machine the waipu pvr addon stoped working.

After doing the upgrade (including a restart) Kodi stated to me that the addon isn't compatible with the current version of Kodi and therefore had to be disabled.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expected the waipu pvr addon to be updated as well. Otherwise I would expect the addon to be kind of forward compatible with this version.

## Actual Behavior

Currently there is no package update for the waipu pvr addon. The addons latest version in the repository is this: `kodi-pvr-waipu:amd64/jammy 6:19.3.1-1~jammy uptodate`.

## Possible Fix

If I'm not mistaken then the latest version of the addon itself should already be compatible with Kodi 20 but it's just not in the package repository.
source: https://github.com/flubshi/pvr.waipu/releases

### To Reproduce

1. `apt install kodi` on ubuntu jammy (ofc after adding the ppa)
2. `apt install kodi-pvr-waipu`
3. try to enable the addon in Kodi itself -> fails with compatibility error

### Debuglog

The debuglog can be found here:
grepped the kodi.log for `pvr.waipu`
```
2023-01-19 21:57:07.699 T:3851     info <general>: CAddonMgr::FindAddons: pvr.waipu v19.3.1 installed
[...]
2023-01-19 21:57:22.017 T:4813     info <general>: ADDON: pvr.waipu version 19.3.1 is incompatible
[...]
2023-01-20 12:24:20.944 T:3851    error <general>: Add-on 'pvr.waipu' is not compatible with Kodi
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

none

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

none

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 22.04.1 LTS
 - Kodi version: kodi:all/jammy 6:20.0+git20230115.1026-389e701cb9-0~jammy uptodate

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Nothing that can be fixed in Kodi. The PPA needs to be updated to contain compatible add-on versions.

**Comment by TheRealDarklord** [comment]
Oh, sorry, I thought you are responsible for refreshing the ppa's contents as well.
Do you possibly know where to put my issue instead?

**Comment by ksooo** [comment]
@wsnipex  maybe?

**Comment by wsnipex** [comment]
already uploaded a couple of hour ago

**Comment by TheRealDarklord** [comment]
Thank you very much!
