### ISSUE TITLE
KODI 20.0 (Android) unable to play video from http sources

### ISSUE THREAD

**Issue by Litr-tm** [xbmc/xbmc#22524]
### Describe the bug
Here is a clear and concise description of what the problem is:

KODI 20.0 (Android) unable to play video from http sources. Also not showing played status nor files nor library items. 
But able to navigate through folders as well

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Playing of the file/serie/film is expected

## Actual Behavior

Showing message "Unable to play..."

## Possible Fix

None

### To Reproduce

1. Upgrade from 19.5 (?)
2. Select any file or library item to play

### Debuglog

The debuglog can be found here:
2023-01-18 18:26:30.877 T:3011     info <general>: Creating InputStream
2023-01-18 18:26:30.879 T:3011    error <general>: CVideoPlayer::OpenInputStream - error opening [http://USERNAME:PASSWORD@10.20.30.1:8080/_SERIES/[REMOVED].mkv]
2023-01-18 18:26:30.879 T:3011     info <general>: CVideoPlayer::OnExit()
2023-01-18 18:26:30.880 T:3011    debug <general>: Thread VideoPlayer -1152663104 terminating
2023-01-18 18:26:30.900 T:2017    debug <general>: CVideoGUIInfo::InitCurrentItem(http://USERNAME:PASSWORD@10.20.30.1:8080/_SERIES/[REMOVED].mkv)
2023-01-18 18:26:30.901 T:2021    debug <general>: void CXBMCApp::OnPlayBackStarted()
2023-01-18 18:26:30.906 T:2021    debug <general>: Visible Behind request: false
2023-01-18 18:26:31.000 T:2017    debug <general>: ------ Window Init (DialogBusy.xml) ------

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 9 and 11
 - Kodi version: 20.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by gusandrianos** [comment]
Is this regular Android or Android TV?

**Comment by Litr-tm** [comment]
> Is this regular Android or Android TV?

Android TV via magisk mod.
I can try on clear android 9 if necessary.

**Comment by gusandrianos** [comment]
It would be preferable to try on clear Android TV or Android and see if it occurs there. What device are you using? Have you rooted a TV Box with Android and added a Magisk mod to turn it into Android TV?

**Comment by Litr-tm** [comment]
Yes, both devices modified as you said. It's TOX-1 and TOX-3.
OK. I'll try it on clear h96max tvbox tomorrow and report.

**Comment by arnova** [comment]
Please provide a FULL debug log with libcurl-component logging enabled...

**Comment by Litr-tm** [comment]
How to enable libcurl logging?

**Comment by jjd-uk** [comment]
> How to enable libcurl logging?

See https://kodi.wiki/view/Settings/System/Logging#Specify_component-specific_logging

**Comment by Litr-tm** [comment]
Update: it's definetly not libCURL problem. Because  KODI plays movies ant unscanned files thougth filebrowser, but not playing scanned series. 

So, maybe the problem is in migration MyVideos (119->121), but I can't see anythig wrong by eye. (I'm using mysql 8)

I lost so much time, only one differece founded: 
_CPlayerCoreFactory::GetPlayers(http://BLAH_BLAH/_SERIES/%d0%a1%d1%82%d0%b0%d1%81%20(2021)/Stas.S01.E06.2021.WEB-DL.1080p.mkv)_ - this when serie is played

_CPlayerCoreFactory::GetPlayers(The.Big.Bang.Theory.2019.S12E02.The.Wedding.Gift.Wormhole.1080p.AMZN.WEB-DL.DD5.1.x264-NTb_EniaHD.mkv**/**)_ - this when it's not, and KODI seeking filename as a path in the 'path' table

Log with debug (libcurl)
[kodi4.log](https://github.com/xbmc/xbmc/files/10551825/kodi4.log)

**Comment by Litr-tm** [comment]
So, I manually copied MyVides119 to MyVideos121, adjusted the cheme and views: that way KODI 20 works OK.

There is definetly no bug in playing from a HTTP source, but may be in DB migration process...
