### ISSUE TITLE
Unable to open the software normally (versions 19-21 appear)

### ISSUE THREAD

**Issue by lhx-nlxbc** [xbmc/xbmc#22537]
On TCL TV, turn on the software black screen or flash back. Only after clearing the cache can the software be reloaded and turned on
Sometimes it can be opened normally, which is strange

**Comment by joaopa00** [comment]
Sometimes, I have this problem too. It is caused by low available memory  on the sdcard.

**Comment by thexai** [comment]
Please, use forum for support
