### ISSUE TITLE
KODI 19.5 & KODI 20 - no video while playing a file (only sound) on NUC10 i5

### ISSUE THREAD

**Issue by klaus-nase** [xbmc/xbmc#22535]
### Describe the bug
Here is a clear and concise description of what the problem is:

When i updated my NUC10 HTPC to 19.5 i initially encountered the problem that after the update i got no picture during playback. There was only the sound but no video. After switching back to 19.4 the problem was gone. I din't change any settings. As the new version 20 is now available i updated from 19.4 to 20. I got exactly the same problem as with 19.5. While playing a video .ts or .mkv i don't get a picture. The screen gets black after starting the video and i only hear the sound. When stopping the video i get back to KODI including picture on my screen.

I've 3 systems on which i use KODI.
System 1 > NUC4 > working with 19.5 and 20 (WIndows 10)
System 2 > NUC10 > causing problems since 19.5 (Windows 10)
System 3 > Desktop with I7 10th generation > working with 19.5 and 20 (Windows 11)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect to get a picture + sound when watching a movie.

## Actual Behavior

After update from 19.4 to 19.5 or 20 the videoplayback is broken (no picture but sound)

## Possible Fix

Currently i've no idea to fix it.

### To Reproduce

1. Update to 19.5 or 20 and videoplayback fails directly independently from the chosen video-file
2.
3.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/harunigipe.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

There is black screen

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows 10 Professional on NUC10 i5
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.5 & 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
There is a problem with your sound driver:
```
2023-01-20 04:57:41.507 T:9480    debug <general>: CAESinkDirectSound::Initialize: Using Window handle: 0x7036c
2023-01-20 04:57:41.514 T:9480    error <general>: CAESinkDirectSound::Initialize: cannot create secondary buffer (DSERR_UNSUPPORTED)
2023-01-20 04:57:41.514 T:9480    error <general>: CActiveAESink::OpenSink - no sink was returned
2023-01-20 04:57:41.514 T:5964    error <general>: ActiveAE::ActiveAE::CActiveAE::InitSink - returned error
```

Can you try to switch to WASAPI audio device for a test?

**Comment by thexai** [comment]
In GUI Settings > System > Display       make sure "Colour management"  is DISABLED

Maybe you enable it by accident in the past and not notice until now because in v19.4 this was not working due to a bug. Now works but a valid ICC profile must be specified, etc.

**Comment by klaus-nase** [comment]
> There is a problem with your sound driver:
> 
> ```
> 2023-01-20 04:57:41.507 T:9480    debug <general>: CAESinkDirectSound::Initialize: Using Window handle: 0x7036c
> 2023-01-20 04:57:41.514 T:9480    error <general>: CAESinkDirectSound::Initialize: cannot create secondary buffer (DSERR_UNSUPPORTED)
> 2023-01-20 04:57:41.514 T:9480    error <general>: CActiveAESink::OpenSink - no sink was returned
> 2023-01-20 04:57:41.514 T:5964    error <general>: ActiveAE::ActiveAE::CActiveAE::InitSink - returned error
> ```
> 
> Can you try to switch to WASAPI audio device for a test?

I'm always using WASAPI audio device. Checked it again and it was activated. Problem still existing.

**Comment by klaus-nase** [comment]
> In GUI Settings > System > Display make sure "Colour management" is DISABLED
> 
> Maybe you enable it by accident in the past and not notice until now because in v19.4 this was not working due to a bug. Now works but a valid ICC profile must be specified, etc.

Wow ... That's it. After disabling the colour management the problem has gone. My picture is back.
Thanks a lot for the hint and solution of my problem

**Comment by klaus-nase** [comment]
Problem is solved by disabling the colour management.
