### ISSUE TITLE
[KODI 20.0] Issue while loading pycryptodome on Android platform

### ISSUE THREAD

**Issue by pyrocky** [xbmc/xbmc#22539]
### Describe the bug
Here is a clear and concise description of what the problem is:

Unable to load necessary binaries while using Addons relying on script.module.pycryptodome on Android.
Addon is crashing immediately at start after trying to import ressources from lib:
Example:

```
    from Cryptodome.Cipher import AES, PKCS1_OAEP
    from Cryptodome.PublicKey import RSA
```

Was working fine before 20.0.
Working fine on MacOS platform with 20.0

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Required libs should be loaded.
Was working fine before updating to 20.0.

## Actual Behavior

Cannot load required libs (see debug logs bellow)
**OSError: Cannot load library 'gmp'**
**OSError: dlopen failed: library "libCryptodome_Math__modexp.so" not found**

### To Reproduce

1. Create any addon using python 3
2. Add in your addons.xml : `<import addon="script.module.pycryptodome" version="3.4.3"/>`
3. In the addon.py, try importing crypto ressources
```
    from Cryptodome.Cipher import AES, PKCS1_OAEP
    from Cryptodome.PublicKey import RSA
```

### Debuglog

The debuglog can be found here:
```
error <general>: EXCEPTION Thrown (PythonToCppException) : 
-->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: not enough arguments for format string
                                                   Traceback (most recent call last):
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Util/_raw_api.py", line 189, in load_lib
                                                       raise OSError("Cannot load library '%s'" % name)
                                                   **OSError: Cannot load library 'gmp'**
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Math/Numbers.py", line 34, in <module>
                                                       from Cryptodome.Math._IntegerGMP import IntegerGMP as Integer
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Math/_IntegerGMP.py", line 98, in <module>
                                                       lib = load_lib("gmp", gmp_defs)
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Util/_raw_api.py", line 192, in load_lib
                                                       raise OSError("Cannot load library '%s'" % name)
                                                   **OSError: Cannot load library 'gmp'**
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Util/_raw_api.py", line 294, in load_pycryptodome_raw_lib
                                                       return load_lib("lib" + name.replace(".", "_") + ".so", cdecl)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Util/_raw_api.py", line 193, in load_lib
                                                       return CDLL(name)
                                                              ^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
                                                       self._handle = _dlopen(self._name, mode)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   **OSError: dlopen failed: library "libCryptodome_Math__modexp.so" not found**
                                                   
                                                   During handling of the above exception, another exception occurred:


```
### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Was working fine before updating to kodi 20.
Looking at the changelog of kodi 20, it looks something was done for pycrytodome for Android

> Version 20.0 Alpha 2 includes the following fixes and additions.

> Android
> Fixed stuttering when opening, closing and reopening the Android Kodi app. One of the team members noticed an issue in > a recent release that resulted in media stuttering only after the app was opened, closed, and reopened without force > closing.
> Another TrueHD fix. Buffers are reduced to a certain level to optimize data throughput.
> All local application icons must be fully displayed in Kodi.
> **>>>>>Fixed packaging error for binary Python modules (pycryptodome)**

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nvidia shield pro 9.1.1
 - Kodi version: 20.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pyrocky** [comment]
While looking at previous PRs, similar issue seemed to have been faced in the past and discussed in: 

https://github.com/xbmc/xbmc/pull/22067
https://github.com/xbmc/xbmc/pull/21561

@fuzzard @wsnipex any thoughts? It looks like Pycryptodome was not packaged in the latest public version for Android? (I am not super familiar with this)

**Comment by fuzzard** [comment]
I looked at it very briefly last night. my feeling is its just a packaging issue.

libCryptodome_Math__modexp.abi3.so
libCryptodome_PublicKey__ec_ws.abi3.so

The SOABI isnt completely stripped, and our "custom" lib loader cant load modexp in this particular case.

Look at https://github.com/xbmc/xbmc/blob/1fdef1f96497a2a236767a88bbf80a89f4b33cb3/tools/android/packaging/Makefile.in#L121 for where id start trying to fix the naming.

**Comment by wsnipex** [comment]
please give https://jenkins.kodi.tv/view/Android/job/android-arm64-docker/320/artifact/kodi-20230122-0c41e387-fix_cryptodome-arm64-v8a.apk a try

**Comment by pyrocky** [comment]
> please give https://jenkins.kodi.tv/view/Android/job/android-arm64-docker/320/artifact/kodi-20230122-0c41e387-fix_cryptodome-arm64-v8a.apk a try

Thanks! I tried it. While the libs are being loaded now, they look like they are incompatible. I am still performing some smoke testing on each basic features such as key generation, encrypt/decrypt and I will let you know. 

For now:

- Key generation 👍 
- Encryption KO 👎 
- Decryption KO 👎 

I will double check and build a sample addon to test those functionalities and share it.
\+ (if i can help write some tests for the build/release pipelines to avoid future breaking changes, let me know (feel free to share any wiki on how to))

```
File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Cipher/_mode_eax.py", 
line 346, in encrypt_and_digest
                                                       return self.encrypt(plaintext, output=output), self.digest()
                                                                                                      ^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Cipher/_mode_eax.py", line 261, in digest
                                                       tag = strxor(tag, self._omac[i].digest())
                                                                         ^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Hash/CMAC.py", line 207, in digest
                                                       pt = strxor(strxor(self._last_ct, partial), self._k2)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Util/strxor.py", line 80, in strxor
                                                       c_uint8_ptr(term2),
                                                       ^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/Cryptodome/Util/_raw_api.py", line 236, in c_uint8_ptr
                                                       local_type = c_ubyte * len(data)
                                                                    ~~~~~~~~^~~~~~~~~~~
                                                   TypeError: unsupported operand type(s) for *: 'function' and 'int'
                                                   -->End of Python script error report<--
```

**Comment by wsnipex** [comment]
which addons are you testing with? @CastagnaIT do you also have those issues with your addons?

**Comment by pyrocky** [comment]
I wrote a sample addon following example provided in [Pycryptodome documentation](https://pycryptodome.readthedocs.io/en/latest/src/examples.html#encrypt-data-with-aes).

Actually, I can reproduce the issue on Kodi 20.0 on MacOS. While the libs are being loaded correctly compared to Android version, facing the same issue while performing tests on basic features (failing at encrypt/decrypt steps, see code below).

It is working fine on Kodi 19.x on both Mac and Android platforms.

Here is the code:

addon.py

```
import xbmc

from Cryptodome.Cipher import AES, PKCS1_OAEP
from Cryptodome.PublicKey import RSA
from Cryptodome.Random import get_random_bytes

TEST_DATA = 'Hello, world!'

def generate_private_key():
    key = RSA.generate(2048)
    return key.exportKey()


def generate_public_key(exported_private_key):
    private_key = RSA.import_key(exported_private_key)
    return private_key.publickey().exportKey()


def encrypt(exported_public_key):
    data = TEST_DATA.encode("utf-8")

    recipient_key = RSA.import_key(exported_public_key)
    session_key = get_random_bytes(16)

    # Encrypt the session key with the public RSA key
    cipher_rsa = PKCS1_OAEP.new(recipient_key)
    enc_session_key = cipher_rsa.encrypt(session_key)

    # Encrypt the data with the AES session key
    cipher_aes = AES.new(session_key, AES.MODE_EAX)
    ciphertext, tag = cipher_aes.encrypt_and_digest(data)

    return (enc_session_key, cipher_aes.nonce, tag, ciphertext)


def decrypt(exported_private_key, enc_session_key, nonce, tag, ciphertext):
    private_key = RSA.import_key(exported_private_key)

    # Decrypt the session key with the private RSA key
    cipher_rsa = PKCS1_OAEP.new(private_key)
    session_key = cipher_rsa.decrypt(enc_session_key)

    # Decrypt the data with the AES session key
    cipher_aes = AES.new(session_key, AES.MODE_EAX, nonce)
    data = cipher_aes.decrypt_and_verify(ciphertext, tag)

    return data


def main():
    xbmc.log('[TESTS CRYPTODOME] 1/4 Generating private key...', xbmc.LOGDEBUG)
    exported_private_key = generate_private_key()
    xbmc.log('[TESTS CRYPTODOME] 2/4 Generating public key...', xbmc.LOGDEBUG)
    exported_public_key = generate_public_key(exported_private_key)
    xbmc.log('[TESTS CRYPTODOME] 3/4 Encrypting using public key...', xbmc.LOGDEBUG)
    (enc_session_key, nonce, tag, ciphertext) = encrypt(exported_public_key)
    xbmc.log('[TESTS CRYPTODOME] 4/4 Decrypting using private key...', xbmc.LOGDEBUG)
    data = decrypt(exported_private_key, enc_session_key, nonce, tag, ciphertext).decode("utf-8")
    xbmc.log('[TESTS CRYPTODOME] Received={} - Result={}'.format(data, data == TEST_DATA), xbmc.LOGDEBUG)


main()
```

addon.xml
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<addon id="script.cryptodome.tests" name="Tests cryptodome" version="1.0.0" provider-name="NA">
	<requires>
		<import addon="xbmc.python" version="3.0.0"/>
		<import addon="script.module.pycryptodome" version="3.4.3"/>
	</requires>
	<extension point="xbmc.python.script" library="addon.py">
		<provides>executable</provides>
	</extension>
	<extension point="xbmc.addon.metadata">
		<platform>all</platform>
		<summary lang="en">Tests cryptodome</summary>
		<description lang="en"></description>
		<license>GNU General Public License, v2</license>
		<language></language>
		<forum></forum>
		<source></source>
		<website></website>
		<email></email>
	</extension>
</addon>
```

**Comment by pyrocky** [comment]
I deep dived the file in `python3.11/site-packages/Cryptodome/Util/_raw_api.py` and it looks like the code is wrong at line 234

Actually: 
l:234 `local_type = c_ubyte * len(data)`

Local change that make it work:
l:234 `local_type = ctypes.c_ubyte * len(data)`

I don't know why there is that typo in the packaged lib. Also, it looks like it is outdated from the current version (if you are using this one): [pycryptodome/_raw_api.py](https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/Util/_raw_api.py).

Looking at this commit for the file _raw_api.py in pycryptodome, you will notice that they added the function c_ubyte and update the line below to use ctypes.c_ubyte. It looks like in Kodi's package, the function was picked without the rest the code which make it non usable today.

https://github.com/Legrandin/pycryptodome/commit/853054937e29e6cd3dc61228be1dc768b688460b#diff-677a94ba1066ff55aebca8ded5da13e1c24a273dc90884449ace9308901b5c73

Is it something that you pack yourself or setup using a dependency? If you pack it, then there might be an issue with the one actually packed but I don't have enough expertise as you guy. I will rely on your expertise.

**Comment by wsnipex** [comment]
this is likely related to our patch: https://github.com/xbmc/xbmc/blob/master/tools/depends/target/pythonmodule-pycryptodome/02-revert-ctype.pythonapi-use.patch
@fuzzard do you recall why we revert usage of ctypes?

**Comment by fuzzard** [comment]
https://github.com/xbmc/xbmc/pull/20654

**Comment by pyrocky** [comment]
> #20654

Thanks.

> this is likely related to our patch: https://github.com/xbmc/xbmc/blob/master/tools/depends/target/pythonmodule-pycryptodome/02-revert-ctype.pythonapi-use.patch
> @fuzzard do you recall why we revert usage of ctypes?

Then this patch might be incomplete as it changes the line to remove the `ctypes` but it does not remove the function definition above of `c_ubyte` which conflicts. 

I see 2 options:

- Either It should remove the def of the function to make it work otherwise the code will always fail IMHO.
```
# Should this be removed?
def c_ubyte(c):
        if not (0 <= c < 256):
            raise OverflowError()
        return ctypes.c_ubyte(c)
```
- Or put back the usage of `ctypes` for that particular line
`local_type = ctypes.c_ubyte * len(data)`

Both options worked locally for me with the example provided above.
What do you think?

**Comment by fuzzard** [comment]
Fix the patch however it was needed. It was a hack job pulling from very old pycrytodome sources to even get running. 

I've mentioned to wsnipex internally, but ctypes on android with static linked cpython isn't an option without patching cpython which becomes a maintenance nightmare. We either have to change to a shared lib as in that PR to use ctypes, or we patch into pycryptodome the old loading routines.

Short answer, just fix the patch to what you need.

**Comment by wsnipex** [comment]
I've  removed the custom c_ubyte function in the PR: https://github.com/xbmc/xbmc/pull/22549
 @pyrocky could you give this a try please? Sorry, but don't have time to test it myself atm

**Comment by pyrocky** [comment]
> I've removed the custom c_ubyte function in the PR: #22549
> @pyrocky could you give this a try please? Sorry, but don't have time to test it myself atm

Thanks, I tried with the package from the jenkins build (if I am not mistaken that is this one, https://jenkins.kodi.tv/job/android-arm64-docker/354/artifact/kodi-20230123-c31c94b1-PR22549-arm64-v8a.apk) but I am not able to install any addon. Is it the right one?

**Comment by fuzzard** [comment]
Should be the correct artifact.

I was able to load an add-on from repo and from a zip. Make sure you enable that setting in add-on to allow unknown sources in case it cleared your settings on uninstall/reinstall

Can you zip up your test add-on upload to this issue  and I'll give it a run on a device. Will be handy to have for when I eventually do further updates of the python lib shit. The current pycryptodome test add-on I have didn't flag this specific issue

**Comment by pyrocky** [comment]
@wsnipex All good to me!. 

- Libs are well loaded 👍 
- Result of my smoke testing is ok 👍 

```
2023-01-23 21:37:45.636 T:26020   debug <general>: [TESTS CRYPTODOME] 1/4 Generating private key...
2023-01-23 21:37:50.683 T:26020   debug <general>: [TESTS CRYPTODOME] 2/4 Generating public key...
2023-01-23 21:37:50.856 T:26020   debug <general>: [TESTS CRYPTODOME] 3/4 Encrypting using public key...
2023-01-23 21:37:50.865 T:26020   debug <general>: [TESTS CRYPTODOME] 4/4 Decrypting using private key...
2023-01-23 21:37:51.054 T:26020   debug <general>: [TESTS CRYPTODOME] Received=Hello, world! - Result=True
```

**Comment by wsnipex** [comment]
great, thanks for testing and reporting back

**Comment by pyrocky** [comment]
> great, thanks for testing and reporting back

Thanks to both of you! Let me know if I can help for anything else :)



> Should be the correct artifact.
> 
> I was able to load an add-on from repo and from a zip. Make sure you enable that setting in add-on to allow unknown sources in case it cleared your settings on uninstall/reinstall

I had to remove it and reinstall the apk. I was not able to do anything, even setup a simple official skin. Don't know why it was in a bad state. Cleaning and reinstalling it fixed it.

> 
> Can you zip up your test add-on upload to this issue and I'll give it a run on a device. Will be handy to have for when I eventually do further updates of the python lib shit. The current pycryptodome test add-on I have didn't flag this specific issue

Sure. Here is the zipped addon. Feel free to adapt it and merge it with your existing tests. It doesn't do much but at least cover basic features.
[script.cryptodome.tests.zip](https://github.com/xbmc/xbmc/files/10484289/script.cryptodome.tests.zip)
