### ISSUE TITLE
kodi 20.0 does not display NAS files, only empty folders

### ISSUE THREAD

**Issue by lucky-beans** [xbmc/xbmc#22541]
Here is a clear and concise description of what the problem is:

I am a regular home user. I am using Synology NAS and NVIDIA Shield TV. I was using the official 19.5 Matrix version and everything was fine. When I upgraded to the latest 20.0 version via GooglePlay, KODI access to my NAS only shows a blank folder without showing any files inside the folder. At first I thought the problem was caused by the Google Play upgrade app, but then I downloaded and installed KODI directly from the official website still couldn't change the problem. So I think KODI 20.0 may have compatibility problem with the latest Shield TV system or Synology NAS or there is a bug in KODI.

Here is a clear and concise description of what was expected to happen:

I want to be able to see the contents of the folder like the old version, instead of showing the folder is empty, so I can use KODI to watch the videos in my NAS.

## Actual Behavior

My NAS folder has videos, but KODI shows the folder is empty.KODI does not display any files.

1. Use Synology and NVIDIA Shield TV with the latest OS.
2.Open the KODI.
3.Select File Management to find my NAS video.

Used Operating system:
 - [√] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:nvidia shield experience 9.1.1/DSM7.1.1
 - Kodi version:20.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
See:
https://forum.kodi.tv/showthread.php?tid=371331&amp;pid=3132727#pid3132727
