### ISSUE TITLE
Kodi on Android TV crashes after update to v20

### ISSUE THREAD

**Issue by Zaelnorth** [xbmc/xbmc#22545]
### Describe the bug
Here is a clear and concise description of what the problem is:

Using Android TV device, after Kodi auto updated via play store, I can't use it anymore. It starts, shows the main screen, then crashes in 5 seconds after that. 

I have The Crew add on installed, otherwise everything plain vanilla. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Actual Behavior

Kodi crashes few seconds after getting into the UI (ie not during the splash screen) 

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Please, use forum for support questions:

https://forum.kodi.tv/forumdisplay.php?fid=164

**Comment by Zaelnorth** [comment]
I'm sorry, Kodi crashing upon automatic update seems like a bug that you folks might want to look into.

Why are you sending me to a support forum?

**Comment by fritsch** [comment]
Reason: You missed everything the template wants from you upon creating an issue. Therefore we conclude, that you rather need support in the forum to work out how to get the relevant information.

**Comment by Zaelnorth** [comment]
Ok updated the issue up here, anything else you need?

**Comment by fuzzard** [comment]
A debug log is always necessary, however first things first, we do not provide support for users using piracy add-ons.
