### ISSUE TITLE
Matroska segment title is ignored

### ISSUE THREAD

**Issue by cunlem** [xbmc/xbmc#22558]
### Describe the bug
When scanning Matroska file into library with [`Settings / Media / Video / Use video tags`](https://kodi.wiki/view/Video_file_tagging#Settings) setting enabled Matroska [segment title](https://www.matroska.org/technical/elements.html) is ignored. Only the [`TITLE`](https://www.matroska.org/technical/tagging.html) tag is taken into account (if present).

## Expected Behavior
In absence of `TITLE` tag Matroska segment is taken into account.

## Actual Behavior
Matroska segment title is ignored.

## Possible Fix
If `Use video tags` is enabled and no `TITLE` tag is present and segment title is present then parse segment title according to the same rules as filename, i.e. `<Title> (<Year>)` format.

### To Reproduce

1.  `mkvpropedit --set title="Vertigo (1958)" --global: foo.mkv`
2. Scan `foo.mkv` file to library (e.g. with TMDb scraper) 
3. No title is found

## Additional context or screenshots (if appropriate)

Setting Matroska tags usually requires a lot of effort, e.g. when using tools from MKVToolNix user is required to write an [XML file](https://gitlab.com/mbunkus/mkvtoolnix/-/blob/main/examples/example-tags-2.xml) with tagging specification. Contrast this with setting a segment title (step `1.`) which can be done with single command line.

Other players offer good support for segment title: either support it in addition to `TITLE` tag like mpv
![vertigo-mpv](https://user-images.githubusercontent.com/87859114/213935794-a94cb510-9365-4325-a083-c467e80a4405.png)
or exclusively (VLC)
![vertigo-vlc](https://user-images.githubusercontent.com/87859114/213935684-138891d9-64fb-4c95-9428-1df1caf87b85.png)

Place in code where Matroska tags are parsed:
<https://github.com/xbmc/xbmc/blob/b1a4329d0fda6d14e24adeb1f8776b9794ae0649/xbmc/video/tags/VideoTagLoaderFFmpeg.cpp#L225>

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 20.04.5
 - Kodi version: 20.0

**Comment by enen92** [comment]
@cunlem mind providing a small 1 minute sample? I know we can probably edit the tags on some video file but that would save some time. This seems a low hanging fruit/easy to implement.
Not really a bug though, just a missing feature.

**Comment by enen92** [comment]
Please use the forum for feature requests: https://forum.kodi.tv/forumdisplay.php?fid=9

**Comment by cunlem** [comment]
Hi, sorry for the wait. @enen92 in case you'd still be interested in implementing this I prepared some test files:

- [seg-title-with-tags.mkv](https://drive.google.com/file/d/1Gu1KAAHyXepE1K-xIWYg0VA-KAF9B_b1/view?usp=sharing) Segment title is set to `Elephants Dream (2006)` and tags are set to `TITLE=Big Buck Bunny` and `DATE_RELEASED=2008`
- [seg-title-only.mkv](https://drive.google.com/file/d/1ye1lKZ-i97pI4UIOSymOK0e1K_CVq_Q4/view?usp=sharing) Like above but contains only segment title
- [tags-only.mkv](https://drive.google.com/file/d/1SKq5HjoUuoZUWodAlyWwL5Ea2TiV9Iom/view?usp=sharing) Like above but contains only tags
