### ISSUE TITLE
Have been ignoring it but should be easy fix "Favourites" typo, should be Favorites, thanks if can update.

### ISSUE THREAD

**Issue by GodisGoodAlways** [xbmc/xbmc#22562]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
In my neck of the woods, Favourite is correct.

Are you using the correct region info settings...

**Comment by fuzzard** [comment]
@gade01 Guess you got no EN-US translators? haha

Dont know if you want this open or not?

**Comment by gade01** [comment]
@fuzzard 
Hahaha we actually have 4 EN-US translators, although not very active :)

All strings in Kdi main and most other components have been correctly translated.
So I think it's a matter of selecting the correct regional setting.
