### ISSUE TITLE
Request -  Random FanArt - Verify FanArt Exists First

### ISSUE THREAD

**Issue by MickaelMartinNevot** [xbmc/xbmc#22569]
### Describe the bug
Here is a clear and concise description of what the problem is:

For Skins that support Random FanArt. It does NOT first check to see if the randomly selected movie and/or TV show has any FanArt.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Random FanArt is still selected randomly. But now it first verifies the Movie and/or TV Show selected at random, indeed has FanArt to use.

Basically if randomly selected Movie and/or TV Show selected has no FanArt then pick another random Movie and/or TV Show until you find one that does.

So now the user always sees the expected random FanArt.

## Actual Behavior

Random FanArt is selected 100% Randomly. It does NOT take into account Movies and/or TV Shows that do NOT have any FanArt.

So many times it randomly selects Movies and/or TV Shows that have no FanArt so the user sees the default background image (or black screen) instead of the expected random Fan.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Matrix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by scott967** [comment]
Thank you for using the Kodi issue system.  In the future, please complete all the template items, in particular the requirement to provide a link to a Kodi debug log showing the issue.

Guessing, your issue regards an addon skin, possibly Aeon Nox siLVO.  This issue system is only for the core Kodi components.  Further I guess that your issue is with addon"grab fanart" which I believe supplies the random fanart images option in Aeon Nox.

Support for addon skins and their addons is via the Kodi forum.  If I am right about your skin, see here:
https://forum.kodi.tv/showthread.php?tid=210069

**Comment by MickaelMartinNevot** [comment]
Thanks for your answer.

I don't know if there is a log showing this issue.

You are probably right, the item "Kodi random movie fanart" may have misled me: that's the main reason why I thought of Kodi' core.

I can't find any trace of "grab fanart" addon for now, but I'll investigate further.

**Comment by MickaelMartinNevot** [comment]
Thanks for your answer.

I don't know if there is a log showing this issue.

You are probably right, the item "Kodi random movie fanart" may have misled me: that's the main reason why I thought of Kodi' core.

I can't find any trace of "grab fanart" addon for now, but I'll investigate further.
