### ISSUE TITLE
Important typo in Wiki re SQL configuration

### ISSUE THREAD

**Issue by kovaga** [xbmc/xbmc#22577]
Not sure where to report typos on wiki page, so hopefully it would get noticed here.

There is a typo on the https://kodi.wiki/view/MySQL/Setting_up_MySQL#tab=Restricting_MySQL_access_rights

The specified GRANT section is incorrect, as the inverted commas should only apply to `MyVideos%` and  `MyMusic%` and not the whole statement.  
```
GRANT ALL PRIVILEGES ON `MyVideos%.*` TO `kodi`@`%`;
GRANT ALL PRIVILEGES ON `MyMusic%.*` TO `kodi`@`%`;

```
It should read
```
GRANT ALL PRIVILEGES ON `MyVideos%`.* TO `kodi`@`%`;
GRANT ALL PRIVILEGES ON `MyMusic%`.* TO `kodi`@`%`;
```

Similar as in MySQL Server 5.7 Server example.

**Comment by CastagnaIT** [comment]
thanks fixed
