### ISSUE TITLE
AUTOSUBS - AUTOMATIC SUBTITLES

### ISSUE THREAD

**Issue by NTK2845** [xbmc/xbmc#22579]
After updating to version 20.0 it is no longer possible to activate automatic subtitles.

As soon as the add-on is installed, it immediately gives an error as shown in the photos

![screenshot00000](https://user-images.githubusercontent.com/121359922/214258009-7a42541c-f16c-4f41-9225-4b42a74ba46b.png)
![screenshot00001](https://user-images.githubusercontent.com/121359922/214258017-14eaab0b-b720-4165-b043-0e6688cfaae1.png)

**Comment by fuzzard** [comment]
You need to provide a log always, however as this is an addon, you are best starting on the forums for support https://forum.kodi.tv/showthread.php?tid=198973

**Comment by NTK2845** [comment]
how do i create a log? i'm new to this

**Comment by fuzzard** [comment]
Go to the forums and a mod will point you in the right direction
