### ISSUE TITLE
iso doesn't show up in file structure

### ISSUE THREAD

**Issue by AlexJacobs1977** [xbmc/xbmc#22587]
Hey,

I have an Android TV with an USB hard disc attached. I have iso files on the disc. Regardless which directory I try with iso file, the iso files doesn't show up. The iso files are really in the good directory and are present.

It worked fine with 19.3. I deleted the application. Reinstalled the application, now Kodi 20. Let the scraper do it's work. I have one folder with scraped information and one without. It doesn't matter which one, the iso don't want to show up. Other file formats (e.g. mkv) : no problem! I didn't have this problem with 19.3.

Solution: allow iso's to show up. Please solve this. I think Kodi is really great!

I can't provide debug file, the TV doesn't let me.

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.0

**Comment by lrusak** [comment]
Please follow the template and upload a debug log. It's always possible to get one. https://kodi.wiki/view/Log_file/Easy
