### ISSUE TITLE
Possible Regression with EAC3 Audio Decoding in v20

### ISSUE THREAD

**Issue by therealjoeblow** [xbmc/xbmc#22584]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have an older Yamaha AVR with only standard 5.1 Dolby AC3 and DTS (both 5.1) decoding.  No TrueHD or 7.1 decoding.  

I have Kodi and Windows setup with 5.1 audio and Kodi setup to bitstream standard 5.1 AC3 and DTS (using DTS Core).  Everything else gets decoded (and downmixed as necessary) by Kodi and output as PCM 5.1 (or 2.0/1 if it's a stereo track) to the receiver via WASPI over HDMI.

In v19.5, EAC3 5.1 was working fine as expected, it would be decoded and output as 5.1 PCM to the receiver, channels properly mapped.

In v20.0, this no longer works. The same EAC3 5.1 is now output as 2 channel PCM.  Regular 5.1 AC3 and DTS core still properly bitstream as expected to the AVR, as they did before in 19.5.  I also have some videos with WMA5.1 audio to test, and those also still get properly decoded and output as 5.1 PCM as well, as before.  I also have some 7.1 TrueHD files for testing, and those also decode and remap and output to the AVR to 5.1 PCM fine too.  It's just the EAC3 files that don't work properly anymore.  It does that with the released v20.0, and also with the latest nightly build.

It was working fine as expected in 19.5 and decoding and outputting these audio steams as 5.1 PCM, but after installing v20.0 over top of my previous installation, I noticed that the audio was only being output as 2.0 and not 5.1.  I confirmed that it still works fine in 19.5 by simply reinstalling that version over top of the v20, and launching the same video file. It is output as 5.1 PCM as expected.  Then simply reinstalling v20 overtop once again, and the same audio is  now output as PCM 2.0 again.  Nothing else changed, other than installing one version or the other overtop of the existing installation.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expected that videos with 5.1 EAC3 audio would be decoded and output to the AVR over HDMI by Kodi as 5.1 PCM.

## Actual Behavior

Audio is output to the AVR as PCM 2.0

## Possible Fix

I don't know, it works fine in 19.5 and not in 20.0

### To Reproduce

1. Launch a file with EAC3 5.1 audio in v19.5 and watch the channel lights on the AVR.  All 5 channel lights illuminate
2. Install v20.0 over top, launch it immediately afterwards, launch the same video file, watch the AVR, only 2 lights (stereo illuminate)
3. Reinstall 19.5 over top again, launch it, test the same file, it is now decoding as 5.1 PCM to the AVR again as expected.
4. Reinstall v20.0 overtop, repeat playback and it now only outputs PCM2.0
5. This indicates there has to be some kind of regression or bug in 20.0 as it is not decoding the EAC3 file properly as it did before in v19

### Debuglog

The debuglog can be found here:

Debug log for v19.5:
https://hastebin.com/utiqirudul.yaml

Debug log for 20.0 playing the same file:
https://hastebin.com/ukicavuluq.yaml

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 10 x64
 - Kodi version: 20.0
 - Also does the same thing in latest nightly build (20230123)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Let's first try something. Could you please go to the Audio settings and set it to "Fixed" with 5.1 channels?
What does the AVR show afterwards? Does it show LPCM as expected?

From your log: I only see that it tries to open 2 channels. Could you crosscheck your number of PCM channels inside kodi Audio config again?

**Comment by jjd-uk** [comment]
@fritsch 

It starts at L1420 

`2023-01-24 12:49:02.815 T:13216    info <general>: Creating audio stream (codec id: 86056, channels: 6, sample rate: 48000, no pass-through)`

Then at L1474 it's trying to do a match on speaker layout 

`2023-01-24 12:49:02.943 T:5984    debug <general>: AESinkWASAPI: Input channels are [FL, FR, FC, LFE, SL, SR] - Trying to find a matching output layout`
`2023-01-24 12:49:02.958 T:5984    debug <general>: AESinkWASAPI: Format [FL, FR, FC, LFE, SL, SR] not supported by driver`

It's this matching process that seems to be failing. Not sure if this was something new for v20 as it doesn't seem that v19 did this from the v19 log.

**Comment by jjd-uk** [comment]
I wonder if could have been https://github.com/xbmc/xbmc/pull/19671

I can't find any other relevant PR that suggests anything was changed with regard to EAC3 or channel layout.

**Comment by thexai** [comment]
Non tested yet but might be related to https://github.com/xbmc/xbmc/pull/19786

**Comment by thexai** [comment]
I can not reproduce this in Intel NUC8i3BEK:

Configured with 5.1 channels and passthrough enabled but simulating AC3 and EAC3 not supported (switches off). In these conditions tested files with AC3 5.1 and EAC3 5.1

In both cases AVR outputs PCM multichannel 5.1 (FR FL C SR SL LFE speakers indicators ON) none difference due AC3 or EAC3 observed.

This seems another "AMD only" issue due shitty drivers. 

`2023-01-24 12:48:50.166 T:11704    info <general>: DX::DeviceResources::GetVideoDriverVersion: video driver version is AMD 15.201.1151.1010`

Anyway AMD driver number `15.201.1151.1010` seems really outdated

Not even exists in this database https://gpuopen.com/version-table/

This is a Beta driver from year 2015!
https://www.guru3d.com/files-details/amd-catalyst-15-11-1-beta-driver-download.html

**Comment by therealjoeblow** [comment]
Yes, it's the latest and only available driver for the Radeon HD6450.  It's an old card, but it's fanless and silent and works fine with up to 1080p h264 video which is all many people need.  I'd prefer if the card didn't need to be replaced with something newer and more expensive if the code can be tweaked to avoid this issue.

**Comment by therealjoeblow** [comment]
On the support forum where I started my quest to figure this out, @jjd-uk noted that when Kodi enumerated my devices that it found BL and BR while Kodi is looking for SL and SR to match the channel output.  Hoping this can be tweaked in the code to match either/both of these layouts?

**Comment by fritsch** [comment]
> @fritsch
> 
> Setting the audio config in Kodi to 5.1 Fixed does output 5.1 PCM to the AVR, but then it does it for everything. 2.0 EAC3 is also being pushed out as 5.1 when it should be 2.0 obviously.
> 
> As @thexai noted, it ssems to be a output layout that the AMD driver doesn't recognize that is causing this.
> 
> I should also note that I have a test file wih 7.1 EAC3, and it gets decoded and output by Kodi as 5.1 PCM which is what I would expect to happen. And my 2.0 EAC3 test file also gets properly decoded and output as 2.0 PCM. It's just the 5.1 EAC3 that is causing this issue.

This was by intention. I wanted to see if your device can open a "certain" layout. Now we have the possibility to use the appropriate one as a fallback in the non working 5.1 setup.

Sadly you did not post the debuglog for comparing.

**Comment by therealjoeblow** [comment]
Sorry, my bad.  Here's the debug log playing the same video file with 5.1 EAC3, Kodi audio settings configured as 5.1, Fixed:

https://hastebin.com/pikubetuya.yaml

**Comment by fritsch** [comment]
Thanks!
Works: Channel Layout: FL, FR, FC, LFE, BL, BR
Does not work: FL, FR, FC, LFE, SL, SR

Good.

   {AE_CH_FL,  AE_CH_FR,  AE_CH_FC,  AE_CH_LFE, AE_CH_SL,  AE_CH_SR,  AE_CH_NULL}, // Standard 5.1
   {AE_CH_FL,  AE_CH_FR,  AE_CH_FC,  AE_CH_LFE, AE_CH_BL,  AE_CH_BR,  AE_CH_NULL}, // 5.1 wide (obsolete)

So for your device the "obsolete" one works, but the Standard One does not. So then let's fall back :-)

**Comment by fritsch** [comment]
@thexai is right, the new code for finding layouts checks if the channels match, by doing the bitwise & - while the older code only checked if the number of channels match. So it worked "by chance" before.

New code now tries to find a layout that "naturally" contains BR and BL and therefore continues down the list. For you it's definitely a regression cause you implicitely assumed that BR and BL would just be opened as SL / SR ... thinking ... if HAS_BL && HAS_BR && !HAS_SL && !HAS_SR -> Fallback to old standard ... by changing it to: FL,FR,FC,LFE,SL,SR in that case.

**Comment by fritsch** [comment]
@the-black-eagle you implemented the mask verification.  What's your take on solving it? My idea would be to basically fallback to Legacy Layout if number of channels match and after masking basically only SL, SR are gone?

**Comment by therealjoeblow** [comment]
@fritsch just wondering if you are able to implement the fallback patch you were thinking about here?

**Comment by DecalicatanDecalicatan** [comment]
Hi, 

Sorry if it's hijacking this issue. If it's totally different I will delete this post and create a new issue.

But I have an issue which may be related to kodi & channel layout

With an Nvidia Shield 2019 Pro connected to an AVR (Marantz NR1711) through HDMI with a 5.0 layout, a file with 5.1 PCM or with 5.1 Flac is only played as 2.0 with kodi video player (kodi build from master branch early March) : The AVR displays only "Stereo"
log for 5.1 PCM detected as 2.0 by AVR: https://paste.kodi.tv/rojetasutu.kodi

On my setup, all is fine when using videoplayer and audio when passthrough is available (EAC3 5.1 / trueHD 5.1 / DTS-HD MA 5.1)
The same 5.1 PCM file is well payer by Just Player --> the AVR displays "Multi In" as expected.

**Comment by MHarlock** [comment]
Hi,
Same identical problem on Rasperry PI 4 (OSMC with kodi 20)
Regards

**Comment by jjd-uk** [comment]
@the-black-eagle since you made a reappearance. Would you be able to add a fallback as suggested by fritsch?

**Comment by the-black-eagle** [comment]
@jjd-uk I'm afraid that's highly unlikely at the moment.  I no longer have any kit running Windows and IIRC I blew one of the HDMI ports on my AVR by hot-plugging my laptop into it.  Besides, there are active devs that know much more about this than me and are more likely to produce a proper fix rather than the band-aid I would probably come up with.

**Comment by therealjoeblow** [comment]
Anyone else able to help out here?  I don't have any coding experience, but would certainly help out to the extent I can with testing if someone is able to add the fallback code.  Many thanks!

**Comment by fritsch** [comment]
@therealjoeblow what might not be clear here is: Yes, it's annoying that you don't hear all channels, but in reality it is wrong to output SL / SR on BL / BR. They are just not the right channels for this.

That being said, see the linked PR. Would be great if you can provide me a debuglog once it is built.

**Comment by thexai** [comment]
@therealjoeblow 

This is a test build (v21) with the proposed fix:
https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240101-1c10d290-wasapi51amd-x64.exe

**Comment by therealjoeblow** [comment]
Thank you @thexai, sorry for late response, just returning from vacation.  

I agree it's "wrong" to map the channels that way, however with the older hardware that otherwise works fine and zero chance of AMD/ATI ever updating their drivers, the only option is to use workarounds where the developer is willing to include them.

I'll test that version out tonight after work and let you know if it works as expected.

Many thanks for taking up the torch here!

**Comment by therealjoeblow** [comment]
@thexai, sorry to report that the fix didn't fix the 5.1 channel EAC3 channel mapping.  EAC3 5.1 still outputs as PCM2.0 to the AVR, not 5.1 as expected.  Regular DD5.1 and DTS5.1 are bitstreamed in 5.1 as expected in proper channel mapping.  And Dolby Digital Plus 7.1 (also EAC3) decodes and outputs to 5.1 channel PCM as expected. as does Dolby TrueHD (lossless) 7.1, also properly decoded and mapped to 5.1 PCM output.  Those are all working fine, it's just the 5.1 EAC3 that's the issue (as it was at the beginning). Here is the debug log of the EAC3 5.1 file being output as 2.0 PCM:

https://paste.kodi.tv/giqejegeti.kodi

**Comment by thexai** [comment]
@fritsch 
Is strange but seems that code with workaround is not reached because log line `Fallback Matching Res: {} SL|SR {} BL|BR {}` is not present in the log. 

Seems all layouts are tested sequentially and is used first that works `{AE_CH_FL,  AE_CH_FR,  AE_CH_NULL}, // Stereo `

https://github.com/xbmc/xbmc/blob/f3f1df1eab2a38b7039e57635a6597b37510481a/xbmc/cores/AudioEngine/Sinks/windows/AESinkFactoryWin.h#L72-L103

Maybe a possible solution is test only 5.1 layouts in this case (6 channels layouts) then probably first working would be:

`{AE_CH_FL,  AE_CH_FR,  AE_CH_FC,  AE_CH_LFE, AE_CH_BL,  AE_CH_BR,  AE_CH_NULL}, // 5.1 wide (obsolete)`

But I not fully understand this code and why starts with -1  ???

`for (int layout = -1; layout <= (int)ARRAYSIZE(layoutsList); layout++)`

**Comment by fritsch** [comment]
Ideally we would create that code in the "fallback". Whenever we don't match properly right now - we simply end up with Stereo - always. Here it would be good to even try "greater" masks, so that we can map all channels. The above workaround could go there as well. Cost: the loop needs to be done again.

**Comment by thexai** [comment]
@therealjoeblow

This is another test build with more generic fallback:

[KodiSetup-20240116-c1524b7f-wasapi-fallback-x64.exe](https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240116-c1524b7f-wasapi-fallback-x64.exe)

**Comment by therealjoeblow** [comment]
@thexai and @fritsch , thank you very much, that version is now working as expected!

DDP/EAC3 5.1 now decodes and outputs as 5.1 PCM as it should.  Standard DD5.1 and DD2.0 and DTS 5.1 all bitstream in their native formats as they should.  And TrueHD 7.1, and 11.1 output as 5.1 PCM as expected.  And EAC3 2.0 outputs as 2.0 PCM as expected.  I believe all the formats are now outputting as they should with that fix.

Here's the debug log plaing a test file with EAC3 5.1:

https://paste.kodi.tv/nizedunigo.kodi

I did notice a new (unrelated) regression with the new Nexus test build, my ATI card supports hardware vector adaptive deinterlacing and it was working in v20 fine with interaced MPEG2 remuxed DVD content, the content looked "progressive" with the high quality hardware deinterlacing.  Now in  v21 the deinterlacing is no longer being triggered and my test file has the window-blind interlacing still intact.  Since that's an unrelated new issue I'll open a new bug report for it on its own.

As far as my own testing goes for the EAC3 decoding fix, it looks to be working find and you can mark this issue solved if the code fix is integrated into the new version.  

Thank you again for this audio fix!

**Comment by fritsch** [comment]
Thanks for the feedback. @CrystalP any idea for the deinterlacer?

**Comment by therealjoeblow** [comment]
I filed a separate issue for the deinterlacer here, so as to not clutter this thread with an unrelated issue.  Complete with logs and screenshots from v20 and v21:

https://github.com/xbmc/xbmc/issues/24530

Cheers!
