### ISSUE TITLE
Kodi 20 Android crashes when updating the music library with japanese song names

### ISSUE THREAD

**Issue by J-Luc16** [xbmc/xbmc#22594]
### Describe the bug
Kodi 20 Android quits (crash) during the music library update when it finds an album/song with japanese characters.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Usually, I update my MP3 library from time to time without any issue, Kodi 19 managed easily all the albums and songs names. 
The crash is new with V20.

## Actual Behavior

When I ask Kodi 20 (Android) to update the songs library from my NAS, it crashes on the "2814" band album named "新しい日の誕生"

## Possible Fix

No idea.

### To Reproduce

1. Have a music library with the "2814" band album "新しい日の誕生"
2.Run a scan (update ) of the music library 
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android 6
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 6
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by J-Luc16** [comment]
As you can see on the screen copy attached, Kodi 20 is not even able to display the titles in japanese chars in the media library perfectly read and stored and displayed by the previous version.

![Screenshot_20230127-144811](https://user-images.githubusercontent.com/6543125/215105819-e10f671d-2ba1-459b-8c5f-2cd5f7820efb.png)

**Comment by the-black-eagle** [comment]
A debug log showing the crash might be helpful.  In the meantime,  System -> Settings -> Interface -> Fonts and change that to Arial based.  Your stuff should then display correctly.

**Comment by J-Luc16** [comment]
> A debug log showing the crash might be helpful. In the meantime, System -> Settings -> Interface -> Fonts and change that to Arial based. Your stuff should then display correctly.

- The display issue is solved.
- The library analysis seems to be solved to : no more crash

I close the issue.

THANKS a lot !!!
