### ISSUE TITLE
pvr.channelsdvr: problem with active channel group at startup

### ISSUE THREAD

**Issue by wiffleboy** [xbmc/xbmc#22591]
### Describe the bug
Here is a clear and concise description of what the problem is:

Using ChannelsDVR as my PVR, every time I restart Kodi Nexus, it goes to All Channels grouping.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The channel grouping should be remembered during each new startup, rather than defaulting to All Channels each time.

## Actual Behavior

When restarting Kodi, the PVR channel grouping goes back to the All Channels group.

### To Reproduce

1. Simply restart Kodi.
2. Goto PVR.
3. Goto group.

### Debuglog

The debuglog can be found [here:](https://paste.kodi.tv/fehejaruzu.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The issue popped up in Nexus and was not an issue in Matrix.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64bit
 - Kodi version:20.0 and 1-24-2023 nightly.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Cannot say anything without a debug log.

**Comment by wiffleboy** [comment]
> Cannot say anything without a debug log.

Added, thanks.

**Comment by ksooo** [comment]
I don't know anything about the add-on pvr.channelsdvr. Maybe something @Lunatixz can help with.

**Comment by wiffleboy** [comment]
> I don't know anything about the add-on pvr.channelsdvr. Maybe something @Lunatixz can help with.
Thanks for fixing the group backend order a few days ago. The fix in the latest Nightly works great. The channel group resetting at startup is the only other issue I see in Nexus that isn't in Matrix. Thanks again.

**Comment by Lunatixz** [comment]
ping @tmm1

**Comment by tmm1** [comment]
AFAICT, this is not specific to our addon? There is some issue where the UI doesn't remember the last choice and the user must switch their selection each time?

@wiffleboy can you post a screenshot of where you see All Channels and you have to change it?

**Comment by wiffleboy** [comment]
> 

![screenshot00000](https://user-images.githubusercontent.com/123604039/214968990-e12753d9-0943-4135-90f9-2c71f49e351e.png)

**Comment by ksooo** [comment]
Confirming the bug.
