### ISSUE TITLE
Video calibration not working on Kodi Nexus

### ISSUE THREAD

**Issue by eevlogiev** [xbmc/xbmc#22590]
### Describe the bug
Running Kodi 20 Nexus on a Sony Android TV, I wanted to change subtitles position, when I go to Settings-System-Display-Video Calibration and try to adjust any border using my remote control arrow keys - nothing happens. However when I tried using an external wireless keyboard I was able to adjust lines using my keyboard mousepad. So this is affecting only TV remote control.

## Expected Behavior
I should be able to adjust screen borders when in Video calibration mode using my TV remote control.

## Actual Behavior
Nothing happens, I just hear regular Kodi clicking sound when I am pressing the arrow keys on the remote control.

### To Reproduce
On Android TV, go to Settings-System-Display-Video Calibration and try to adjust any line using your TV remote control

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 9.0.0
 - Kodi version: 20.0

**Comment by fuzzard** [comment]
Provide a debug log. But if you are using other skins, they need to add support to the skin for the new calibration controls

**Comment by eevlogiev** [comment]
> 

@fuzzard , thanks for getting back on this. I use Arctic Zephyr - Reloaded skin.
Debug log attached. [kodi.log](https://github.com/xbmc/xbmc/files/10528270/kodi.log)

**Comment by fuzzard** [comment]
If you change to estuary does it work?

As mentioned, skins need to support changes that directly affect calibration controls. I think you are going to have to take this up with the skin dev to ask them to make the required changes to their skin.

**Comment by eevlogiev** [comment]
Yes,
I just changed it to Estuary and Video Calibration did work. I will follow up with skin developers as suggested.

Thanks.
