### ISSUE TITLE
Samba shares with hostname stopped being accessible in v20 on Ubuntu

### ISSUE THREAD

**Issue by sylvainRou** [xbmc/xbmc#22595]
### Describe the bug
Here is a clear and concise description of what the problem is:

After upgrading from v19.x to v20, I could not play any of my media. Playing any media would give me the following message:
"Playback failed - One ore more items failed to play. Check the log for more information about this message."
Then in the log, I would get the following kind of error:
```
2023-01-27 00:46:25.971 T:8088    error <general>: SMBDirectory->GetDirectory: Unable to open directory : 'smb://127.0.1.1/redacted'
                                                   unix_err:'6f' error : 'Connection refused'
2023-01-27 00:46:25.971 T:8088    error <general>: GetDirectory - Error getting smb://nas/Media2/redacted
2023-01-27 00:46:26.003 T:8088     info <general>: SMBFile->Open: Unable to open file : 'smb://127.0.1.1/redacted'
                                                   unix_err:'6f' error : 'Connection refused'
2023-01-27 00:46:26.003 T:8088    error <general>: CFileCache::Open - <smb://nas/redacted> failed to open
2023-01-27 00:46:26.003 T:8088    error <general>: CVideoPlayer::OpenInputStream - error opening [smb://nas/redacted]
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

My Kodi v19.x worked flawlessly, I expected Kodi v20 to work just the same after the upgrade.

## Actual Behavior

Kodi v20 does not work while Kodi v19.x worked with the same settings.

## Possible Fix

My system hosts file shows that my hostname ("nas") is linked to 127.0.1.1. This is the default on Ubuntu:
cat /etc/hosts:
127.0.0.1 localhost
127.0.1.1 nas
[...]

Apparently, that does not play nice with Kodi v20. Again, that was not an issue with Kodi19. I worked around the issue by adding the following in my advancedsettings.xml:
```
  <pathsubstitution>
    <substitute>
      <from>smb://nas/</from>
      <to>smb://127.0.0.1/</to>
    </substitute>
  </pathsubstitution>
```
Note that adding <to>smb://127.0.1.1/</to> instead of <to>smb://127.0.0.1/</to> does not fix the issue and yields the same result as with no pathsubstitution at all.

### To Reproduce

1. apt update to upgrade Kodi from v19.x to v20 from the team-xbmc PPA
2. try and play any media

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 20.04
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
You really need to learn how TCP/IP works.

Loopback address (127.0.0.1) can ONLY point to localhost, so if NAS is different from localhost can NOT have a loopback address.

YES, because ALL addresses in range 127.0.0.1 to 127.255.255.255 are ALL loopback addresses and ALL points to same  LOCALHOST.

So, please use forum for support.

**Comment by sylvainRou** [comment]
I am sorry, I perhaps should have been more clear about my particular setting. The machine with hostname "NAS" is actually the machine on which that particular instance of Kodi is installed, i.e. localhost. I did not specifically state this in the first place, but a careful reader could have inferred this information from:

1/ the successful workaround that I applied
The workaround consists in forcing kodi to replace all references to smb://nas to smb://127.0.0.1. If this workaround works, it clearly shows that the localhost machine is the one supposed to be resolved with the nas hostname

and / or

2/ the fact that the exact same settings used to work with kodi v19.x

This is my very first bug report on github. I apologize for not being specific enough. I will try to be more specific in the future to avoid very rude responses such as the one above. That being said, I hope this bug report can be re-open as this problem should affect every kodi users who are on Ubuntu and who use samba shares referenced by hostnames.

**Comment by sylvainRou** [comment]
To add even more context, I would like to mention that hosting my media files on a samba share and referencing their path by hostname is useful to me because I am sharing my library with MySQL as explained [here](https://kodi.wiki/view/MySQL). Other computers on the network can reach the files thanks to the use of the hostname in the path. Using localhost or any localhost IP would make the files inaccessible to all of the remote devices on my local network. I guess I could use the static IP of the nas device instead, but that would be another workaround. Anyways, the whole point of this bug report is to alert on the fact that a setting that was working with kodi v19.x is not working with kodi v20 anymore.

**Comment by thexai** [comment]
GitHub issues are only for code bugs and, in any case, this seems a bad setup: 

Take into account that is not need use path substitution to use SMB/NFS shared files or shared database with MariaDB, etc.

Also is not need use loopback IP address in any place to access media files shared in NAS (server). You should use local IP of server (NFS/SMB) (eg 192.168.1.x) that contains media files. Also you should use local IP of server that contains Kodi database (MariaDB, MySQL...) in `advancedsettings.xml`. Again this IP is similar to 192.168.1.x (not 127.0.0.1) because (usually) MariaDB server are not installed in same computer that Kodi client.

If you need more help, please continue in forum at https://forum.kodi.tv
