### ISSUE TITLE
.ass-subs aren't shown in file selector

### ISSUE THREAD

**Issue by aKijia** [xbmc/xbmc#22616]
### Describe the bug

After 20.0 update I no longer can use .ass-subtitles. They aren't shown in subtitles file selector menu (folders with ass-subs files are blank). *srt-subtitles are still available.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android
 - Kodi version: 20

**Comment by KarellenX** [comment]
It is working for me. Provide a debug log that captures you browsing to your subtitles.

![assSubtitles](https://user-images.githubusercontent.com/44626605/215408123-bae9a40b-a652-4e26-ac27-099329f68e5e.jpg)

**Comment by CastagnaIT** [comment]
could be also similar to #22483 where you need to manually fix android app permissions
but the issue template has been not fullfill as it should

**Comment by aKijia** [comment]
> could be also similar to #22483 where you need to manually fix android app permissions but the issue template has been not fullfill as it should

Probably similar. In RightManagement I set "media and files" to "Allow every Time" and it helped. On previous version (i believe 19.3) it worked as is.

**Comment by CastagnaIT** [comment]
then its same problem
follow already opened linked issue
