### ISSUE TITLE
[Whitelist improvement] Kodi to choose the highest whitelisted resolution?

### ISSUE THREAD

**Issue by Boulder08** [xbmc/xbmc#22619]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have these items in my whitelist. The Kodi GUI is set to 3840x2160 @ 59.94 and I have a 4K TV (Sony XF9005).

3840x2160 @ 60.00 - Full Screen
3840x2160 @ 59.94 - Full Screen
3840x2160 @ 50.00 - Full Screen
3840x2160 @ 30.00 - Full Screen
3840x2160 @ 29.97 - Full Screen
3840x2160 @ 25.00 - Full Screen
3840x2160 @ 24.00 - Full Screen
3840x2160 @ 23.98 - Full Screen
1920x1080 @ 60.00 - Full Screen
1920x1080 @ 59.94 - Full Screen
1920x1080 @ 50.00 - Full Screen
1920x1080 @ 30.00 - Full Screen
1920x1080 @ 29.97 - Full Screen
1920x1080 @ 24.00 - Full Screen
1920x1080 @ 23.98 - Full Screen
1280x720 @ 50.00 - Full Screen
720x576 @ 50.00 - Full Screen

Now whenever I playback a source that is 720p and uses a non whitelisted refresh rate, Kodi uses the closest resolution which it can find, and that means going 1080p. This means that my TV will then upscale again to 4K. I think this is suboptimal and that in these cases Kodi should output at either the highest possible whitelisted resolution, or at the set GUI resolution which most likely is the same as their display device's native resolution for best image. I do want to keep the 1080p ones whitelisted as I also have sources that will then be output as is and the TV can do a high quality upscale job.

I understand that there might be some design logic behind the specification, but to me it seems that going the proposed way would not lower the user experience at all (or maybe add a bypass option in advancedsettings.xml). I'm interested in hearing any reasoning there may be.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20 (CoreELEC 20)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please use the forum for support. https://forum.kodi.tv/
