### ISSUE TITLE
queue file order

### ISSUE THREAD

**Issue by wmollenvanger** [xbmc/xbmc#22638]
### Describe the bug
Here is a clear and concise description of what the problem is:

Since kodi 20 if a folder is queued (context menu -> queue)  the files are queued in some semi-random order instead of alphabetically like in  previous versions. 

Note: the randomize option of the queue is off

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Files should appear in the same order in the queue as they are in the directory

## Actual Behavior

Files appear in the queue in a semi-random order (looks like similar files are grouped but couldn't see the pattern)

### To Reproduce

1. place some different video files (4 should suffice) in a directory accessible by Kodi
2. notice the order OR force the order by prepending a number to the file name
3. add the folder to the playlist with context menu -> queue
4. go to playlist
5. files are now in a different order as they where in the directory

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV on Nvidia Shield Pro
 - Kodi version: 20.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Already fixed by #22609 (master) and #22610 (nexus).
