### ISSUE TITLE
DSTV now addon Kodi v20

### ISSUE THREAD

**Issue by Kallie2312** [xbmc/xbmc#22642]
### Describe the bug
Failed to fetch JSON data
Make sure your IP address is allowed (not geo-blocked)
Tru accessing the content via other means (official app / website) to test if its a Kodi addon on issue.

## Expected Behavior
Live tv fucntion does not work

## Actual Behavior
Once you click on the live tv link it cannot access content.

### To Reproduce
Open DSTV Now addon click live tv and the error message appear

### Your Environment
Used Operating system:
 - [ ] Android

 - Operating system version/name:
 - Kodi version: v20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Please contact the addon developer for addon issues.
There are already plenty of posts that deal with this recent issue.

Thanks.

**Comment by Kallie2312** [comment]
Thanx for the feedback, but can you please forward me the link to these
threads. I am not as tech savvy as you. Just trying to find a solution.

Your help is greatly appreciated

**Comment by KarellenX** [comment]
Yep, here... https://forum.kodi.tv/showthread.php?tid=335718
Read the last few posts.

**Comment by Dman0070** [comment]
Good day, I need assistance regarding dstv on kodi, it doesn't seem to work anymore and I'm using the latest version, I'll attach a screen shot below. Thanks 
![Screenshot_20230205_222006_org xbmc kodi](https://user-images.githubusercontent.com/74552845/216843058-fc93bcfa-ce52-4063-9a6a-e8b39c4f6077.jpg)

**Comment by KarellenX** [comment]
@Dman0070 

Please read my last two posts.
