### ISSUE TITLE
Video freeze, audio runs further on Rumble and Odysee videos Kodi 19.5 RPI 3

### ISSUE THREAD

**Issue by Isayso** [xbmc/xbmc#22640]
## Bug report
when playing some Rumble and Odysee videos in their addons for more than 4 minutes the video freeze and the audio is still running
### Describe the bug
Here is a clear and concise description of what the problem is: 

Rumble and Odysee videos freeze after more than 4 minutes of play, the audio is still playing. If you jump some seconds back the video runs again with video and audio in sync. Sometimes the video stops completely. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video should play.

## Actual Behavior

Video frames stop, audio runs 

### To Reproduce

1. install Rumble and Odysee addon 
2. play a Rumble video which is longer than 4 minutes
3. wait for video freeze
4. not all videos freeze, try it several times

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/10538893/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.5
Libreelec 10.0.4 on RPI3+

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
The connection to the server gets rejected because of some reason. Maybe it is because the presence of piracy related repositories, which might alter the network traffic. This is not supported here.

Check your network and check in with the author of the add-on.

**Comment by Isayso** [comment]
I already contacted the author of the addon and afaik I don't use piracy related repositories.
