### ISSUE TITLE
Nexus/Matrix: System info => Summary => Compiled always shows "2013-05-12"

### ISSUE THREAD

**Issue by satmandu** [xbmc/xbmc#22653]
### Describe the bug

In Kodi preferences,  go to System information => Summary. At the bottom, under Version info, the Compiled: field always shows `2013-05-12` instead of the date kodi was compiled.

I compiled this today using a lightly modified version of the https://github.com/xbmc/xbmc/blob/master/tools/Linux/packaging/package-kodi-launchpad.sh script, thus it should show today's date.

### Screenshots 
Here are some links or screenshots to help explain the problem:

![screenshot00000](https://user-images.githubusercontent.com/1096701/215847542-4e4b8af5-0def-4b5c-a883-b6db91e61d8e.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux Ubuntu 22.10, 23.04 (And versions back quite a ways...)
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.0 (git 20230130-501eec)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@wsnipex can you take a quick look? Doesn't seem anything critical and likely some configuration issue on the op side

**Comment by wsnipex** [comment]
that means you didn't compile from a git repository. Where did you install kodi from? Versions from our official PPAs show the correct build date.

**Comment by satmandu** [comment]
I'm using a slightly modified package-kodi-launchpad build script on my own machine:

```
#!/bin/bash
set -ax
export DEB_BUILD_OPTIONS=noddebs
DEBEMAIL="satadru@umich.edu"
kodi_work=~/src/kodi_build
#debianbranch=${DEBIANBRANCH:-"Matrix"}
debianbranch=${DEBIANBRANCH:-"master"}
kodi_branch=$debianbranch
kodi_branch=Nexus
dist=lunar
mkdir -p $kodi_work
cd $kodi_work || exit
mkdir -p $kodi_work/packages
mv *.deb $kodi_work/packages &>/dev/null
rm -f $kodi_work/kodi* &>/dev/null
[[ ! -d $kodi_work/kodi ]] && taskset -c 2,3,4 git clone --depth=1 -b $kodi_branch https://github.com/xbmc/xbmc kodi
cd $kodi_work/kodi || exit
git config pull.ff only
git reset --hard origin/${kodi_branch}
git clean -ffxd :/
taskset -c 2,3,4 git pull

[[ -e "$kodi_work/rev.kodi" ]] && oldkodirev=$(<$kodi_work/rev.kodi) || oldkodirev=
kodirev=$(git -C $kodi_work/kodi rev-parse --short $kodi_branch)
# [[ "$kodirev" == "$oldkodirev" ]] && exit 1

releaseversion=${VERSION:-"AUTO"}
epoch=${EPOCH:-"7"}
gitrev=${GITREV:-"$(git log -1 --pretty=format:"%h")"}
tag=${TAG:-${gitrev}}
tagrev=${tagrev:-"0"}
dists=${DISTS:-"kinetic"}
gpgkey=${GPG_KEY:-"jenkins (jenkins build bot) <jenkins@kodi.tv>"}
ppa=${PPA:-"nightly"}
debianrepo="${DEBIAN:-"https://github.com/xbmc/xbmc-packaging"}"


if [ "$releaseversion" = "AUTO" ]; then
  majorversion="$(awk '/VERSION_MAJOR/ {print $2}' version.txt)"
  minorversion="$(awk '/VERSION_MINOR/ {print $2}' version.txt)"
  releaseversion="${majorversion}.${minorversion}"
fi

version="${releaseversion}+git$(date '+%Y%m%d.%H%M')-${tag}"
debversion="${epoch}:${version}"
origtarball="kodi_${version}.orig.tar.gz"

declare -A PPAS=(
    ["nightly"]='ppa:team-xbmc/xbmc-nightly'
    ["unstable"]='ppa:team-xbmc/unstable'
    ["stable"]='ppa:team-xbmc/ppa'
    ["wsnipex-nightly"]='ppa:wsnipex/kodi-git'
    ["wsnipex-stable"]='ppa:wsnipex/kodi-stable'
)
# clean up before creating the source tarball
git clean -xfd

# set build info
date '+%Y%m%d' > BUILDDATE
echo $gitrev > VERSION

# Install ffmpeg 5.x patch
curl -OLf https://patch-diff.githubusercontent.com/raw/xbmc/xbmc/pull/21248.patch
patch -p1 -i 21248.patch

# download packaging files
wget -O - ${debianrepo}/archive/${debianbranch}.tar.gz | tar xzv --strip-components=1 --exclude=".git*" -f -
[ -d debian ] || { echo "ERROR: directory debian does not exist"; exit 3; }

# add tarballs for internal ffmpeg, libdvd
tools/depends/target/ffmpeg/autobuild.sh -d || { echo "Error downloading ffmpeg"; exit 2; }
make -C tools/depends/target/libdvdnav download GITREV="" || { echo "Error downloading libdvdnav"; exit 2; }
make -C tools/depends/target/libdvdread download GITREV="" || { echo "Error downloading libdvdread"; exit 2; }
make -C tools/depends/target/libdvdcss download GITREV="" || { echo "Error downloading libdvdcss"; exit 2; }
make -C tools/depends/target/dav1d download GITREV="" || { echo "Error downloading dav1d"; exit 2; }

# create orig tarball if needed
if grep -q quilt debian/source/format; then
  echo "origtarball: ${origtarball}"
  git archive -o ../${origtarball} ${gitrev}
fi


# build source packages
for dist in ${dists//,/ }; do
  echo "### Building for ${dist} ###"
  sed \
      -e "s/#PACKAGEVERSION#/${debversion}/" \
      -e "s/#TAGREV#/${tagrev}/" \
      -e "s/#DIST#/${dist}/g" \
    debian/changelog.in > debian/changelog

  echo "Changelog:"
  cat debian/changelog
  echo

  #debuild -d -S -k"${gpgkey}"
[[ $kodi_branch == 'Matrix' ]] && sed -i 's,LIBDVDREAD-VERSION,DVDREAD-VERSION,g' debian/rules
[[ $kodi_branch == 'Matrix' ]] && sed -i 's,LIBDVDNAV-VERSION,DVDNAV-VERSION,g' debian/rules
[[ $kodi_branch == 'Matrix' ]] && sed -i 's,LIBDVDCSS-VERSION,DVDCSS-VERSION,g' debian/rules
  dbuild && echo "$kodirev" > $kodi_work/rev.kodi
  echo "### DONE ###"
done

## upload to PPA
#echo "### Uploading to PPA ${PPAS[${ppa}]} ###"
##dput ${PPAS[${ppa}]} ../kodi_${version}*.changes
#if [ $? -eq 0 ]; then
  #echo "### Successfully pushed ${version} to launchpad ###"
#else
  #echo "### ERROR could not upload package ###"
#fi
```
I suppose I could test this by sending it to my own ppa to see if it is broken there.

But am I doing something wrong where I am breaking where the compiled date is getting picked up? Is there something special about the launchpad infrastructure where that would be set external to the build environment?

**Comment by wsnipex** [comment]
this is indeed weird. You are building from a git repo, so the BUILDDATE and VERSION files are not used.
According to your screenshot it correctly detects the last git commit and that the source tree is modified (git status would show uncommitted changes), including the date stamp of 2023-01-30.

Can you provide [builddir]/xbmc/CompileInfo.cpp? Please use https://paste.kodi.tv
Adding -DVERBOSE=ON to the cmake invocation would also show the detected date stamp during cmake configure

**Comment by satmandu** [comment]
CompileInfo.cpp from my last build:

https://paste.kodi.tv/loharoquho.kodi

**Comment by satmandu** [comment]
I could hack up the build script to add the `-DVERBOSE=ON` CMAKE option with a patch to flip that in CmakeLists.txt, if the output of that would be helpful.

**Comment by wsnipex** [comment]
so that build date seems to be fixed at "20130512". 
What happens if you don't use the packaging script, but just compile manually? It should be enough to just run:
mkdir build; cd build
cmake -DAPP_RENDER_SYSTEM=gl -DVERBOSE=ON ..

at the end you should see git hash and build date:
```
-- GIT_REV: 20230214-38670ae650-dirty
-- Build date: 20230215
```

**Comment by wsnipex** [comment]
oh and stupid question: your system date/time is correct, right?

**Comment by satmandu** [comment]
> oh and stupid question: your system date/time is correct, right?

Date/time are correct on the machine.

**Comment by satmandu** [comment]
> so that build date seems to be fixed at "20130512". What happens if you don't use the packaging script, but just compile manually? It should be enough to just run: mkdir build; cd build cmake -DAPP_RENDER_SYSTEM=gl -DVERBOSE=ON ..
> 
> at the end you should see git hash and build date:
> 
> ```
> -- GIT_REV: 20230214-38670ae650-dirty
> -- Build date: 20230215
> ```

```
-- #---------------------------------------------#
-- bindir     : /usr/local/bin
-- includedir : /usr/local/include
-- libdir     : /usr/local/lib
-- datarootdir: /usr/local/share
-- #---------------------------------------------#
-- BINARY: kodi.bin
-- #---------------------------------------------#
-- GIT_REV: 20230209-2967337-dirty
-- Build date: 20230215
-- #---------------------------------------------#
-- CPACK_GENERATOR       :
-- CPACK_SOURCE_GENERATOR:
-- #---------------------------------------------#
-- Configuring done
-- Generating done
```

**Comment by satmandu** [comment]
FYI The CompileInfo.cpp in this new build looks like it shows the right information:
```
std::string CCompileInfo::GetBuildDate()
{
  const std::string bdate = "20230215";
  if (!bdate.empty())
  {
    std::string datestamp = bdate.substr(0, 4) + "-" + bdate.substr(4, 2) + "-" + bdate.substr(6, 2);
    return datestamp;
  }
  return "1970-01-01";
}
```

So is there something about triggering the build with the debian tools which breaks this detection?

Instead of using the command in the original script(`debuild -d -S -k"${gpgkey}"`) I'm doing this:

```
#!/bin/bash
# dbuild script
dir=$(pwd)
mydir="${dir%/*}"
filedir="$(basename $mydir)"
export DEB_CFLAGS_MAINT_APPEND="-flto=auto -pipe -O3 -ffat-lto-objects -fipa-pta -fno-semantic-interposition -fdevirtualize-at-ltrans"
export DEB_CXXFLAGS_MAINT_APPEND="-flto=auto -pipe -O3 -ffat-lto-objects -fipa-pta -fno-semantic-interposition -fdevirtualize-at-ltrans"
export DEB_LDFLAGS_MAINT_APPEND="-flto"
dpkg-buildflags
export DEB_BUILD_OPTIONS="noddebs nocheck nodoc"
export DPKG_GENSYMBOLS_CHECK_LEVEL=0
sudo rm *build-deps*.buildinfo
sudo rm *build-deps*.changes
sudo rm *.deb
dpkg-source -b .
debuild -S -sa
nice -n 20 debuild -us -uc -d |& tee ../$filedir.log
```

**Comment by satmandu** [comment]
(If I recall correctly the ppa builds also gave the wrong build date in them a couple of years ago when I used the ppa builds.)

**Comment by wsnipex** [comment]
I'm going to close this, since it's not a kodi bug. If you want to continue debugging this, you're welcome to open a forum thread and ping me there.
