### ISSUE TITLE
Musiccast streaming music playlist fails after upgrade to 20.0, works on 19.3

### ISSUE THREAD

**Issue by MAmmerlaan** [xbmc/xbmc#22665]
## Bug report
Since upgrading to v20, cant stream any music to music cast devices. Downgrading to 19.3 and it works again.

### Describe the bug
Unable to stream music to Musiccast devices (tried HTR amp, and Musiccast 50, both fail), since upgraded to v20.
When downgraded to v19.3 it works again.

## Expected Behavior
Playlists are listed, can select a song, and it starts playing.

## Actual Behavior
Playlists are listed, but cant open up the playlist and select a song. An error is given in the app 'afspelen is niet mogelijk', which is Dutch for ' playback is not possible' .
It fails upon selecting the playlist, and it not even listing songs.

## Possible Fix
Downgrade to v19.3

### To Reproduce

Open up the Musiccast android app, choose KODI -> Music -> Playlist and start one of the playlists
It now says 'afspelen is niet mogelijk' which is Dutch for 'playback is not possible'
It seems to try and hit every song, so the app going kinda haywire.

### Debuglog
Playlists are located in 
C:\Users\$USERNAME\AppData\Roaming\Kodi\userdata\playlists\music

### Your Environment
Used Operating system:
Client is Android 12
Server is Windows 10, tried on Kodi v20 (kodi-20.0-Nexus-x64.exe, fails) and 19.3 (kodi-19.3-Matrix-x64.exe) (success)
Tried to set Kodi to extensive logging, but no relevant logs are saved (at leasts, non of the attempt to read the playlist).

How can I provide debug logging to help you guys?

**Comment by enen92** [comment]
@MAmmerlaan please provide a kodi debug log while trying to stream the song using the app with UPnP component log enabled ...

**Comment by MAmmerlaan** [comment]
Thanks @enen92  for getting back to me. I did the following, hoping this helps you. If you need anything more, let me know.

- Removed kodi 19 thru contol panel (uninstaller).
- Left the box 'Yes, I am sure and grant permission to also delete profile folder' unticked.
- Started installer with admin privs (kodi-20.0-Nexus-x64.exe)
- Did a full installation in default dir 'C:\Program Files\Kodi'
- Started kodi, and enabled debug log
- Opened Musiccast app on phone, and selected a random song from a random playlist
- App starts skipping thru all songs, until the end of playlist is reached, then stops.

On V19, the music starts playing.

On 10:37 and 10:40 did two attempts.
Actual song that is clicked is not listed.

Debug log : https://pastebin.com/XWX0eJ4Y

**Comment by enen92** [comment]
@MAmmerlaan can you give a go to https://github.com/xbmc/xbmc/issues/22828#issuecomment-1439148788?
It might fix your issue, would be nice to confirm if the issue is the same.

**Comment by MAmmerlaan** [comment]
@enen92 Thanks for the prompt response. I am not sure what you are asking from me. I cant access movies on the musiccast app, so can't test if it wont load the video's there. And the links that are in the comments go to a 404 (at least for me).

I am able to use a other device (laptop) to install a new Kodi isntance and try to hit the UPNP of the faulty Kodi version where are testing. Would that give us some usefull insights?

**Comment by enen92** [comment]
ok sorry, just realized this is about playlists, my bad.
Can you share the contents of one of your music playlists so I can take a look at the format and try to reproduce locally?

**Comment by MAmmerlaan** [comment]
It looks like this,
Directory: C:\Users\MYUSERNAME\AppData\Roaming\Kodi\userdata\playlists\music
Mode                 LastWriteTime         Length Name                                                                                              
----                 -------------         ------ ----                                                                                              
-a----         22-2-2023     14:57          32183 90s rap.m3u                                                                                       
-a----         22-2-2023     14:57        1475875 Album Top 1000.m3u                                                                                
-a----         22-2-2023     14:57           3937 Ambient Nights.m3u     
...                                                                           

And the contents of '90s rap.m3u' would begin like so,
It has no headers or anything, just the file listed each on a different line.

d:\multimedia\muziek\90s rap\90s Rap Music Hits Playlist - Greatest 1990's Rap Songs\The Sugarhill Gang _ Furious 5 _ Barshon _ Someone Like You _ 432Hz.mp3
d:\multimedia\muziek\90s rap\90s Rap Music Hits Playlist - Greatest 1990's Rap Songs\Biggie Smalls Ten Crack Commandments.mp3
d:\multimedia\muziek\90s rap\90s Rap Music Hits Playlist - Greatest 1990's Rap Songs\Kurupt- C Walk.mp3
d:\multimedia\muziek\90s rap\90s Hip Hop Playlist _ 90s Hip Hop Hits\Public Enemy - Fight The Power.mp3
d:\multimedia\muziek\90s Hip Hop but it's a lofi remix _ Tupac, Notorius BIG, Snoop Dogg, Ice Cube, Wu Tang Clan, and Nas.mp3
d:\multimedia\muziek\90s rap\90s Hip Hop Playlist _ 90s Hip Hop Hits\2 Live Crew - Hoochie Mama ( Uncut + Lyrics ).mp3

I have tried (with Foobar2000), to use different formats for the playlists. I can store it as.m3u, .fpl and .m3u8 file.

Only the m3u files are displayed by Kodi and seem usable.
The FPL files arent even visible.
The m3u8 files are listed, but are not usable / clickable. They are greyed out.

**Comment by enen92** [comment]
@MAmmerlaan mind giving a go to https://jenkins.kodi.tv/view/All/job/android-arm-docker/lastSuccessfulBuild/artifact/kodi-20230224-0b987d55-upnp_fixes_folders_backport-armeabi-v7a.apk ?

It's kodi 20 with the above patch on top. It'd be nice to check if it solves the issue

**Comment by MAmmerlaan** [comment]
Installed V20.1 is works great now! Good work all!
