### ISSUE TITLE
Vocal search when using keyboard

### ISSUE THREAD

**Issue by swazen** [xbmc/xbmc#22661]
Hi,

Seems search field in kodi keyboard is missing in Nexus with a TCL Google TV.
I want talk about [this fonctionality](https://www.youtube.com/watch?v=SrL3EDY3Pyk).

Last Nexus with standard estuary skin or [AH2](https://github.com/jurialmunkey/skin.arctic.horizon.2)
Last Google TV on TCL 65C728

**Comment by ksooo** [comment]
On Android and macOS (starting with Nexus), you can long press enter while in the keyboard screen to start vocal search. This feature is currently not available for other platforms like Linux and Windows.

**Comment by swazen** [comment]
Thanks Kssoo, work's great !!!
