### ISSUE TITLE
Help with Compiling Kodi 20.0 Android APK

### ISSUE THREAD

**Issue by barronen1** [xbmc/xbmc#22677]
Hi,

I already tried to create a post in Kodi forum, but apparently there is no dedicated forum for Kodi compiling and my post was closed..

I really need help with compiling Kodi 20.0 from GitHub source code - to Android 32/64 bit APKs.

I've tried to follow the exact instructions of the Android build guide:
https://github.com/xbmc/xbmc/blob/master/docs/README.Android.md

But I'm getting a lot of errors in the "make" command step. Maybe the guide isn't up to date? I tried 3 times repeating the exact instructions.

I would really appreciate a help / up to date instructions to build Kodi 20.0 APK from code.

Thanks.

**Comment by fuzzard** [comment]
That user was wrong. Thats a fine place, and definitely better than on github for us.

Those instructions are up to date, and do work. further support can be done in that thread.

**Comment by barronen1** [comment]
> That user was wrong. Thats a fine place, and definitely better than on github for us.
> 
> Those instructions are up to date, and do work. further support can be done in that thread.

What thread? my thread?
https://forum.kodi.tv/showthread.php?tid=371781

**Comment by barronen1** [comment]
I found a mistake in the instructions. How do I submit the updated fix!

**Comment by arnova** [comment]
> I found a mistake in the instructions. How do I submit the updated fix?

Please provide a pull-request for that.
