### ISSUE TITLE
On low memory Android devices, addons still stored to primary storage even when external storage is available.

### ISSUE THREAD

**Issue by mytechguyri** [xbmc/xbmc#22670]
### Describe the bug
Here is a clear and concise description of what the problem is:

With low storage Android devices, such as Chromecast with Google TV, even when extra storage is available (I have a 500 gb SSD on mine) and the Kodi app is moved to the external storage... Addons still take up significant memory on the device primary storage, resulting in an inability to add more Kodi add-ons, and full device storage, even though the auxillary external storage is still empty.   We need an ability to use path substitution for the special://home/addons directory to a network share, or to force it to mount on external storage when available.

I attempted to install retro gaming addons, and quickly ran out of room, even with a 500gb SSD as extra device storage... Kodi simply wasn't using or storing its data on that external storage.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expected behavior would be when the Kodi app is moved to the external storage, that all its files would also be moved to external storage, or at the very least, key files that take substantial space, like the special://home directory.  Since adding Kodi retro game addons completley filled the primary storage of a Chromecast device, and the 500 gb SSD still remained mostly empty, it is clear that the extra storage is not being utilized in an effective manner.   I attempted to use substitution to point special://home/addons to a network share to gain more space, but this failed (as expected)

## Actual Behavior

Installed external hard drive on Chromecast android device, formatted as device storage, moved the Kodi app to the SSD... installed retro gaming addons, and after several emulators had been installed, Chromecast began complaining "device storage full" so it is clear that even though the Kodi app is on the external storage, the special://home/addons directory clearly remains on the much more limited primary device storage.

## Possible Fix

perhaps allow special://home/addons to be mounted to a network share?  or ensure that the /addons directory gets moved to external storage with the actual Kodi app.  With many of these low storage Android based devices, they are typically locked down, and without root access, the end user doesn't have the ability to otherwise modify drive mounts.

### To Reproduce

1. see above
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X ] Android 
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please make feature requests on the forum. https://forum.kodi.tv/
