### ISSUE TITLE
Crash when you use self.removeControl on xbmcgui.WindowXMLDialog

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#22674]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a custom window by using `xbmcgui.WindowXMLDialog`
on `onInit()` method i placed the code to remove some added XML button controls

look at sample addon on file: `resources/lib/kodi/ui/xmldialog_ratingthumb.py`
relative window xml: `resources/skins/default/1080i/plugin-video-netflix-RatingThumb.xml`

so the window is opened correctly but when it execute `self.removeControl` kodi crashes

~_seem a problem of current master branch_~
~on Kodi 19 or 20 i dont have crashes, maybe by luck?~

if you use Windows nightly release, the crash never happens
if you self build kodi for Windows, as debug mode, the crash always happens
on android its weird, usually can happens the first time, on next kodi run seem dont crash anymore

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Have the window opened with the controls removed

## Actual Behavior

The window is opened but kodi crashes

## Possible Fix

I tried investigate and i see something weird on control pointers
on: https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/legacy/Window.cpp#L553-L566

when the `while` is executed the control is erased from vecControls vector
after that `pControl` become with weird content at least my debugger show weird values
and when is executed the SendGUIMessage, callback fall here:
https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/GUIWindow.cpp#L698
on mentioned line the dereference make kodi to crash

no idea for a good fix

### To Reproduce

1. Build kodi as debug mode for Windows
2. Install: [plugin.video.netflix_1.20.5+matrix.1_TEST.zip](https://github.com/xbmc/xbmc/files/10569485/plugin.video.netflix_1.20.5%2Bmatrix.1_TEST.zip) its a modded fake addon, just to open the custom window dialog
3. Run the addon
4. A small window dialog with thumb up / down should be shown without Kodi crash

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/meyezagoyu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 / SHield 
 - Kodi version: builded from master branch and android master branch nightlies

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Tested on linux and can't reproduce the issue (master branch)

**Comment by CastagnaIT** [comment]
i havent tested on linux
but i tested again with current master (c0445a8a6b5756ab01c64243175f413294ca3218)

if i use Windows nightly release, the crash never happens
if i self build kodi for Windows, as debug mode, the crash always happens

i cannot build for android and i use nightlies,
but on android is weird, not always the crash happens could happens the first time but on next kodi run do not happens anymore
