### ISSUE TITLE
Steam Deck Bugs (UI Sounds, drivers)

### ISSUE THREAD

**Issue by ShadwDrgn** [xbmc/xbmc#22688]
### Describe the bug
Here is a clear and concise description of what the problem is:

~~While in Gamescope/SteamOS mode (not in desktop mode) on the Steam deck you can not adjust pixel calibration (likely due to how gamescope works) resulting in the complete inability to fix the completely wrong pixel ratio the device takes on while displaying natively (1920x800) on the Deck.~~

UI sounds do not play at all when using the steam deck controls such as the direction pad. Seems like they do play when using a keyboard, however.
Finally there still seems to be a requirement to pass --env=LIBVA_DRIVER_NAME=radeonsi environment into the flatpak command in properties just to get video to play at all.

~~It may be worth noting that though i'm not positive, I don't THINK the pixel ratio issue was not happening in an older version (of either steamos or kodi i don't know definitely 19.0 kodi, but unsure if it has anything to do with steamos version). I believe ratio was fine out of the box but never tested video calibration. it's broken right now for SURE~~

~~When Docked I believe the pixel ratio is actually correct. though I haven't tested if video calibratio nworks when docked.~~
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

~~I expect to have a correct pixel ratio out of the box~~, the drivers to be properly chosen without need of a special env variable (not sure if that's even possible but would be nice) and for UI sounds to work when using a gamepad or the steam deck controls.
Failing that I expect the video calibration to move when i in directions to adjust it.

## Actual Behavior

~~Pixel ratio is completely wrong (extremely stretched to the point that you have to set every video specifically to 0.5 to get movies to look right and the UI still looks wrong especially in system settings.~~
UI sounds should play if the setting says to play them whether using a keyboard or the built in direction pad.
I shouldn't have to add special environment variables to get videos to play properly.

## Possible Fix

~~Adjust pixel ratio automatically to conform to what it should be when kodi is installed on a steam deck and is launched from the normal UI (non desktop mode) or make pixel ratio adjustments work in video calibration so we can fix it ourselves.~~

### To Reproduce

1. Install kodi from flatpak on steam deck
2. Add kodi as a non steam game
3. exit back to steamos
4. Launch Kodi
5. set resolution to native in properties
6. Observe no sounds, ~~wrong pixel ratio~~, no h/w accel.

### Debuglog

Here's the debug log from using no LIBVA_DRIVER_NAME=radeonsi, launched normally used the steam deck controls with UI sounds on (but not playing) where I navigate to system settings and attempt to video calibrate followed by exiting calibration then using an attached keyboard to navigate up then down then attempting calibration with the keyboard (UI sounds work):

[kodi(no LIBVA_DRIVER_NAME).log](https://github.com/xbmc/xbmc/files/10611582/kodi.no.LIBVA_DRIVER_NAME.log)

Here's the same as above but with LIBVA_DRIVER_NAME=radeonsi:
[kodi(With LIBVA_DRIVER_NAME).log](https://github.com/xbmc/xbmc/files/10611593/kodi.With.LIBVA_DRIVER_NAME.log)

Note: there is no crash here.

### Screenshots 
Here are some links or screenshots to help explain the problem:

![IMG_20230203_163151](https://user-images.githubusercontent.com/2470781/216714871-85a4a29f-bba1-4dd5-bcc5-e76ad5a6cd1a.jpg)
![IMG_20230203_163222](https://user-images.githubusercontent.com/2470781/216714877-6d0a8f0f-5ce0-4eb4-aced-018f685ffd8c.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Just trying to watch movies undocked with steam deck.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: SteamOS Holo 3.4.4
 - Kodi version: 20.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
> As there is no crash, i've not pulled any debug logs as these are design bugs not crashes.
That's some weird understanding. So much can be deduced from it. Provide one, or we can't help diagnose the issue.

**Comment by ShadwDrgn** [comment]
Do I need to provide the debug logs with or without the LIBVA_DRIVER_NAME line? or both?

**Comment by ShadwDrgn** [comment]
I've uploaded two debug logs and done as much as I can to try to capture everything I could think of in the app while debug was on for the two logs. Let me know if I can provide anything futher.

**Comment by CastagnaIT** [comment]
>  I expect the video calibration to move when i in directions to adjust it.

this sound like the skin used has not been full updated for Kodi 20 enviroment,
you can test by using calibration screen from original kodi skins,
if so you will have to ask skin developer to update the calibration screen component of the custom skin used

**Comment by ShadwDrgn** [comment]
You're absolutely right. changing to estuary and doing video calibration works great. I'll remove all references to that part of the issue! thanks so much!

**Comment by lrusak** [comment]
Since the input goes through the game input layer there is no sound. This is a known limitation, see #15031

For the libva issue you shouldn't have to set any env variable as the steam deck uses an AMD cpu/gpu.

Your logs don't actually show you trying to play anything. Can you post a debug log after attempting to play a file.

**Comment by ShadwDrgn** [comment]
Well now I can't reproduce the driver issue all of the sudden so i'm going to just close this comment at this point as the lasst remaining issues are unreproducable here and known anyway. Thx for the help on the pixel thing hopefully aeon nox updates soon but fixing it in estuary was a fine workaround for now anyway and if i'm ever able to reproduce the performance issues i was seeing earlier without the env variables, i'll reopen or make a new issue with the relevant logs attached.
