### ISSUE TITLE
Strange error messages for remote directories via Samba

### ISSUE THREAD

**Issue by rschupp** [xbmc/xbmc#22684]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm running LibreELEC master which builds Kodi with Samba 4.17.5  since a couple days ago.
I noticed strange errors in kodi.log when accessing files from my NAS via Samba:
```
2023-02-02 18:22:41.039 T:1091    error <general>: Getting extended attributes for the share: 'smb://nas/videos/TV%20Shows/Doctor%20Who'
                                                   unix_err:'5f' error: 'Operation not supported' return: 0
2023-02-02 18:22:41.044 T:1091    error <general>: Getting extended attributes for the share: 'smb://nas/videos/TV%20Shows/Frieden%20(2020)'
                                                   unix_err:'4b' error: 'Value too large for defined data type' return: 0
2023-02-02 18:22:41.048 T:1091    error <general>: Getting extended attributes for the share: 'smb://nas/videos/TV%20Shows/Mum'
                                                   unix_err:'4b' error: 'Value too large for defined data type' return: 0
2023-02-02 18:22:41.053 T:1091    error <general>: Getting extended attributes for the share: 'smb://nas/videos/TV%20Shows/Borgen'
                                                   unix_err:'4b' error: 'Value too large for defined data type' return: 0
```
The NAS is running recent Linux and Samba, there is nothing suspicious for these directories.

## Expected Behavior
No such messages :)

## Possible Fix
These messages originate from https://github.com/xbmc/xbmc/blob/1b98faae545f30433bd3c4f07ba87a056821c416/xbmc/platform/posix/filesystem/SMBDirectory.cpp#L172-L184
There, the return value from smbc_getxattr is supposed to be > 0 if successful (contrary to the documentation: 0 on success and -1 on failure). I tweaked the error message to show the actual return value, shown above as `return:....`: it's always 0.

But in latest Samba (4.17.5), the return value was fixed to align with the documentation, see https://www.samba.org/samba/history/samba-4.17.5.html and https://bugzilla.samba.org/show_bug.cgi?id=14808

Possible fix: change the condition
```
if (smbc_getxattr(strFullName.c_str(), "system.dos_attr.mode", value, sizeof(value)) > 0)
```
to  `... == 0`,  though `... >= 0` should be OK and work for older versions of Samba, too.

### To Reproduce
1. Videos -> Media sources 
2. Browse some sources residing on smb://nas/...

### Debuglog
The debuglog can be found here: http://ix.io/4mZh

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 11 beta1
 - Kodi version: Nexus rc1

**Comment by Portisch** [comment]
I can confirm `>= 0` should be correct and the issue is gone.
