### ISSUE TITLE
Missing `kodi-vfs-libarchive` package for kinetic kudu in the official ppa

### ISSUE THREAD

**Issue by kalaninja** [xbmc/xbmc#22708]
I cannot install `kodi-vfs-libarchive` package on Ubuntu Kinetik Kudu. Seems like it is missing in the official [ppa](https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa/+index?field.series_filter=kinetic)

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20

**Comment by DaVukovic** [comment]
![image](https://user-images.githubusercontent.com/7235787/218251479-00fd86da-8a40-4d43-9d07-992283078c60.png)

It's included since 2 days now
