### ISSUE TITLE
language flag not parsed (read as "unknown") when there is a dash in the audio stream title

### ISSUE THREAD

**Issue by DecalicatanDecalicatan** [xbmc/xbmc#22712]
### Describe the bug
Here is a clear and concise description of what the problem is:

The language flag of some DTS-HD MA audio stream (muxed in matroska file) is read as "unknown" by video player (and displayed as such in the audio setting) even if the language has been properly set using latest revision of mkvtoolnix.
The language flag is well read for other audio stream codec such as (E-)AC3 or TrueHD or FLAC.

Example of files with audio stream detected as "unknow": 
sample: https://1fichier.com/?5rf87t3s4iylm48xrmq9
mediainfo: https://paste.kodi.tv/ivopoberad
mkvinfo: https://paste.kodi.tv/uyularudop

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The language flag set in mkvtoolnix should be well identified in the Audio setting

## Actual Behavior

In the audio setting page, the language flag of the audio stream is "unknown"

### To Reproduce

1. Open a mkv file with a DTS-HD MA audio stream with English language flag
2. Open Audio setting
3. The audio stream is identified as "Unknown -  

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/suvuyoqexe.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Here are the log and mediainfo / mkvinfo of file for which the language flag of the DTS-HD MA stream is well "read" by kodi
log: https://paste.kodi.tv/esejuropul.kodi
mediainfo: https://paste.kodi.tv/afahuruqav
mkvinfo: https://paste.kodi.tv/ewacumutur

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nvidia Shield 2019 Pro (Shield Experience 9.1.1)
 - Kodi version:
kodi-20230204-3df007db-master-arm64-v8a.apk

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Sorry, can't confirm

![image](https://user-images.githubusercontent.com/7235787/218251228-72f8e12d-964e-4543-ac62-ce6ffad34158.png)

**Comment by DecalicatanDecalicatan** [comment]
I have tested further with several files with DTS HD MA sream and the language flag is well detected for most files (but not all)

I will try to provide logs and mediainfo of files

**Comment by DecalicatanDecalicatan** [comment]
I have updated the description of the issue with log and mediainfo / mkvinfo files as well as a link to a sample for a filde which has the issue.
The language file is well read by VLC FYI.

**Comment by DaVukovic** [comment]
Thanks. I´ve removed the flag. 

I´m not too sure if that's needed. But if, could you please do us a favor and add another log file and another media info from a file for which you know it's working fine?

I guess it might be easier to compare. 

If that's too much hassle for you, we simply wait for a dev who can tell more ;)

**Comment by DecalicatanDecalicatan** [comment]
I have updated the report (Additional context part) with the requested log / media info for a file that is working fine.

**Comment by DaVukovic** [comment]
Again, I'm not too sure, but I found a difference in your mediainfo outputs and I compared it with mine, which are all working. 

Your working file contains the following in your mediainfo: 

`Title                                    : Surround 5.1`

Your NON-working file contains the something different: 

`Title                                    : DTS-HD MA 5.1`

I took a look at some of my files which I know where it's working fine and those also have `Surround x.1` in them. 

For example "The Hobbit" show `Surround 7.1`

https://termbin.com/uo2dn

Maybe the devs can do something about it, but for the time being it seems that you did something strange to your files and it's not a Kodi issue. As long as the `title` of the audio stream seems to be `Surround x.1`  it works fine. 

Not sure what causes that change on your side.

**Comment by DecalicatanDecalicatan** [comment]
I think you might have found something... The way of the tag / header of my files is not how kodi expect them to be. Maybe the encoding is off. I have edited the name and it seems it is working as expected now

Anyway they were well read by mediainfo, so we could expect kodi to do so as well. In the meantime I know now there is a woorkaround

**Comment by Sven-M-2018** [comment]
OK, I've seen the same behaviour. My audio tracks are named as "{language} ({audioformat})".
So one of my audio tracks might be named "Englisch (DTS-HD Master Audio)".

In this case the track would be identified as Unknown. So for testing I removed the dash and renamed the track to "Englisch (DTS HD Master Audio)" and now the track is correctly identified as English.

So a dash in the track title will break the recognizing of languages...

**Comment by mrfx** [comment]
I have the same problem with Blu-ray Adele in Royal Albert Hall concert (m2ts file). I use KODI 20.1.0 on Ubuntu 22.04. DTS-HD MA is not recognized, although last year with older version of Kodi it had worked just fine. Now my Denon AVR gets core DTS signal (48 KHz) only, instead of DTS HD Master Audio, so it is not only display problem. My ALSA/audio passthrough configuration is correct, as I downloaded some test DTS HD-MA and Dolby TrueHD mkv files and they are correctly recognized and AVR gets hi-res stream. So, the problem is with some files only.

**Comment by Jcloak** [comment]
I suspect the issue was introduced with this pull request. It appears to be doing a lot of string replacing around the '-' character.

https://github.com/xbmc/xbmc/pull/21776/commits

**Comment by jekv2** [comment]
So, I ran across this problem and what fixed it for me is takine out the "-" from DTS-HD to DTSHD.

This works for me DTSHD MA Surround 7.1.

I am thinking plain ole DTSHD will work as well.

This way, if there are 3 audio codecs, all names surround 7.1, on vlc shows surround 7.1 only for all codecs, this way with 
TrueHD Atmos
DTSHD MA Surround 7.1
AC3

Will work with both VLC and Kodi.

**Comment by Jcloak** [comment]
@CastagnaIT Sorry if this is incorrect, but since you wrote this commit and are more familiar with the code I was hoping to get your input. Do you know if the title being parsed with the RegExp in this code below would include the DTS-HD when trying to find the language and resulting in this "Unknown" language problem?

https://github.com/xbmc/xbmc/pull/21776/commits/d6faeb0f80ac69005804bfd36d90e6488ffa8295#:~:text=std%3A%3Astring%20CLangCodeExpander%3A%3A-,FindLanguageCodeWithSubtag,-(const%20std

**Comment by CastagnaIT** [comment]
its possible that caused side effect
because you use same rounded parentesis with dash (xy-xy)
we should try test/find a more restrict way for regex to find language tags
