### ISSUE TITLE
Kodi 20 for Windows - Videos - wrong sorting in playlist

### ISSUE THREAD

**Issue by Darkwolf81** [xbmc/xbmc#22727]
### Describe the bug
I go to a folder, local or DLNA (TwonkySeerver). Menu => Play. All files added to the playlist. Folder sorting is by title. When i go into the folder, sorting is correct. In the playlist, its different. Its not random, but not by title or by date.

I tried it with a fresh installation of Kodi 20. I compared it with a clean setup of Kodi 19.5, here it is correct. Although in my backup of 19.5 it works. After upgrade to 20 its wrong. So nothing else changed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Playlist created with the same sorting than the folder shows (title / name).

## Actual Behavior

Playlist created with undefined sorting.

### To Reproduce

1. Go to a folder, that contains videos
2. Contect Menu => Play
3. Sorting in the playlist is wrong

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 / Windows 11
 - Kodi version: 20 (tested 19.5, there it works correct)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by AshleyAshes** [comment]
This problem is fixed already in v20 nighties, others reported it and it got fixed, but right now the fix is only in nightlies.

**Comment by Darkwolf81** [comment]
> This problem is fixed already in v20 nighties, others reported it and it got fixed, but right now the fix is only in nightlies.

Thank you for the info, i closed this issue.
