### ISSUE TITLE
Kodi converts rss urls to add a slash when exiting the program

### ISSUE THREAD

**Issue by alexlehm** [xbmc/xbmc#22726]
### Describe the bug
Here is a clear and concise description of what the problem is:

I am using a static rss file to list the current video files I have in a folder via nginx, the URL of this rss is http://192.168.178.21:88/files.rss. Each time the Kodi is restarted, the URL changes from http://192.168.178.21:88/files.rss to http://192.168.178.21:88/files.rss/, apparently due to saving the URL. When I edit the URL to remove the / it gets added on the next restart.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect the URL that is added to remain unchanged after exiting and restarting the program.

## Actual Behavior

The URL is changed on exit/restart to add a /

### To Reproduce

1. Add a URL to a movies share with http://192.168.178.21:88/files.rss
2. exit Kodi
3.start Kodi
4. open the URL with edit source

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: FireOS 6294
 - Kodi version: Kodi 21 development build 7.2.
it also happens with Kodi 20 and Kodi 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by vpeter4** [comment]
Maybe kodi expects a folder and not file?

**Comment by alexlehm** [comment]
I guess it does but rss is clearly a file, either .rss or .xml

**Comment by alexlehm** [comment]
I was considering to set up an alias that maps the file to a url with a / at the end but I have no idea how to do that with nginx

**Comment by vpeter4** [comment]
What about if you use `rss://192.168.178.21:88/files.rss`?
Because this is how should be used according to documentation: https://kodi.wiki/view/RSS_media_source

**Comment by alexlehm** [comment]
Thank you, that actually fixes it.
