### ISSUE TITLE
@Dman0070

### ISSUE THREAD

**Issue by Icespeed101** [xbmc/xbmc#22720]
@Dman0070 

Please read my last two posts.

_Originally posted by @KarellenX in https://github.com/xbmc/xbmc/issues/22642#issuecomment-1418258593_

**Comment by Icespeed101** [comment]
Hallo Dman 0070 when do u tink kodi Wil be sort out and don't u get n ader add on for dstv in n Nader app Dat work

**Comment by sarbes** [comment]
Have you even read the link you posted?
