### ISSUE TITLE
Display message at exit.

### ISSUE THREAD

**Issue by Badsheep** [xbmc/xbmc#22734]
### Describe the bug

It's a feature request : My Kodi is long to quit when I press command-q...
And I'd like a message to appear telling me that Kodi recevied the "quit" command, and is currently quitting.
Could be cool of course if that message would be optional and customizable.

## Expected Behavior

A nice message.

## Actual Behavior

Nothing, I ask myself if I pressed the "exit" button on my Harmony remote or not...
And my wife too.

### To Reproduce

1. Quit Kodi.
2. Look.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.x

**Comment by enen92** [comment]
Hey,
Feature requests are actually forum material: https://forum.kodi.tv/forumdisplay.php?fid=9
We only use gh issues to track actual issues on the core software

**Comment by Badsheep** [comment]
OK thanks..
I asked on the forum before but nobody told me where to ask... thanks
