### ISSUE TITLE
Android Kodi version 20 doesn't support SFTP

### ISSUE THREAD

**Issue by lutusp** [xbmc/xbmc#22733]
### Describe the bug
Here is a clear and concise description of what the problem is:

The most recent Kodi update on Android, i.e. version 20, rejects the only available SFTP add-on.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The most recent Kodi update on Android should accept the SFTP add-on.

## Actual Behavior

The most recent Kodi update on Android rejects the only available SFTP add-on.

## Possible Fix

Change the version number of the SFTP add-on to get around this cosmetic issue.

### To Reproduce

1. Allow Google Play to automatically update Android Kodi to version 20. 
2. Notice that SFTP immediately stops working.
3. Post a bug report.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Can you post a debug log please.

**Comment by lutusp** [comment]
> Can you post a debug log please.

Sorry, not set up to do that. But what I report is not a code bug, it is a policy bug. The policy is that the SFTP plugin fails a version number check, so the current SFTP plugin version is judged not to work with the current Kodi version, as a result of which it's not even installed, therefore a debug log serves no purpose.

The plugin is rejected in all Kodi installs of the most recent version, regardless of platform or processor type.

For Kodi on a non-Android platform, others have recompiled the plugin to have a different version number (https://forum.kodi.tv/showthread.php?tid=371384), after which it is accepted and functions correctly.

I hope this helps.
