### ISSUE TITLE
Pipewire sound is missing 30db output volume

### ISSUE THREAD

**Issue by jojoax** [xbmc/xbmc#22747]
### Describe the bug
Here is a clear and concise description of what the problem is:
Since current v20 Kodi is hardly compiled against the pipewire sound.

Pipewire sound is missing 30db output volume. The sound is much to low, multichannel Audio is not correct sent to external receiver (Yamaha RX*** via HDMI Port out or IEC TOS Link).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Sound should be loud enough to hear it :)

## Actual Behavior

Sound is to less, sound level like -40db, much to less, sound is only whispering

## Possible Fix

Make the modern Audio Router Daemons (i.e. Pulse* and/or Pipe*) deselectable, 
falling back to direct ALSA (kernel) device audio, if there are Problems with the pulse/pipewire output.
On Livingroom installtions mostly pulse or pipwire ars bad showstoppers, those break things, which work really fin via ALSA.

### To Reproduce

1. Arch Linux current (02/2023) and kodi v20 just installed by pacman -S kodi
2. Audio Out via Receiver 
3. Hear - not hear - the much to less sound.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Showstopper, it makes Koodi unusable, do you like movies vwithout correct sound? We not.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux, current update
 - Kodi version: V20.0 build on 2023-02-06 from git

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
We miss your debuglog.

You can use env KODI_AE_SINK=ALSA to force kodi to use e.g. ALSA, but kodi tries to open what your system environment proposes.

**Comment by jojoax** [comment]
Fine, but KODI_AE_SINK=ALSA  is not user frienddly, not at all. It works for hackers, but even then it's buggy.
No Multichannel Sound.

The huge big problem is, within the system setting pulse/pipe or sth. else is not deselectable for endusers. 
Those users are left alone.
Also there are Mixers within the Kodi are missing, so it is not possible to fix sound routing, and the sound level.

By the way KODI_AE_SINK=ALSA does not really work, esp pulseaudio or pipewire are started by kodi itself.

Only this works:
[root@pc2 kodi]# cd /usr/bin/
[root@pc2 bin]# chmod -x pipewire pulseaudio 

[kodi.log](https://github.com/xbmc/xbmc/files/10714591/kodi.log)
![screenshot00000](https://user-images.githubusercontent.com/4421146/218278782-4deb74c8-9f21-431d-860d-ce2a902d46c2.png)

You see in the screenshot, even in the Xsession file /etc/lightdm/Xsession   kodi)
 
       pulseaudio --kill
        # exec /usr/bin/kodi --standalone
        export KODI_AE_SINK=ALSA 
        exec /usr/bin/kodi --standalone
 
Is already there... but does not work. The devices are shown, but are nor working.
Only removeing or removing the execut permission works.

**Comment by fritsch** [comment]
Honestly ... kodi tries to cope with a system that a user has installed. First pulseaudio is opened, if a context exists - it's used. Then we try pipewire and when it exists we use it. At last we try ALSA.

Why are we doing this?
If anyone of the first ones is running / working they will block ALSA anyways. So exposing this inside the Kodi settings will only ask the user to shoot in his foot again ... as they click on ALSA while pulseaudio makes a bing sound in their webbrowser running behind kodi.

As I see your workaround with removing the executable bits of pulseaudio and pipewire: Why do you have them installed if you don't want to use them?

Focussing once more on the pipewire 30db issue: Kodi works with a stream model, it does not control the real hw device, when the volume is so low, it's most likely "in general" muted on your desktop.

Sorry - if user has pipewire / pulseaudio running kodi has to comply ... and embed nicely in user's given setup.

**Comment by fritsch** [comment]
> Is already there... but does not work. The devices are shown, but are nor working.
Only removeing or removing the execut permission works.

^^ see that's exactly it, why it makes no sense that kodi has a gui setting to enforce ALSA while PA / PW are blocking the devices ... same thing would happen. Devices are blocked and not usable.

Therefore: If there is no PW and no pulseaudio -> kodi will nicely use ALSA without a single setting.

Btw. for kodi v21 we will have a pipewire sink with all formats supported, including dts-hd-ma, truehd passthrough ... so fixing your "low volume" issue is something highly suggested ... PW will also have priority over pulseaudio.

**Comment by fritsch** [comment]
@lrusak FYI -> bool HasVolume() override { return true; } <- pipewire does not yet expose any volume controls, which might be good to have as AE only controls the internal volume besides the sinks return HasVolume() ...

In extrem cases as we see from Jürgen here, that means that someone needs to "alt tab" kodi and move its volume up from the default with pipewire control utilities.

**Comment by fritsch** [comment]
For forth and back implementation pulseaudio sink can be used: https://github.com/xbmc/xbmc/blob/master/xbmc/cores/AudioEngine/Sinks/AESinkPULSE.cpp#L1171 and especially this: https://github.com/xbmc/xbmc/blob/master/xbmc/cores/AudioEngine/Sinks/AESinkPULSE.cpp#L238 for syncing outside to inside to Application
