### ISSUE TITLE
Kodi on Win 11 running v20 crashes after 47 sec of streaming

### ISSUE THREAD

**Issue by Chucknorris1975** [xbmc/xbmc#22743]
## Bug report
Kodi will crash on Nexus and last builds of Matrix after 47 seconds of streaming
### Describe the bug
I'll choose my source to play and it will load and start playing like usual. After 47 seconds the video will freeze and about 5 seconds later Kodi will crash to desktop

## Expected Behavior
Here is a clear and concise description of what was expected to happen: Video will continue to play until manually stopped or stream finishes.

## Actual Behavior
Video will freeze after 47 seconds then crash to desktop

### To Reproduce

1. Choose a source you want to watch.
2. Stream will begin playing.
3. After 47 seconds Kodi will crash.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/hubamufore.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

[kodi_stacktrace-20.0 Git_20230115-389e701cb9-20230128-215616.txt](https://github.com/xbmc/xbmc/files/10713024/kodi_stacktrace-20.0.Git_20230115-389e701cb9-20230128-215616.txt)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: 19.5 and 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
That stacktrace shows absolutely nothing.

Get a debug log at the very least please.

**Comment by Chucknorris1975** [comment]
Sorry about that... try this

https://paste.kodi.tv/hubamufore.kodi

> That stacktrace shows absolutely nothing.
> 
> Get a debug log at the very least please.

log added in opening post

**Comment by the-black-eagle** [comment]
Yeah, we don't support any installations that are using pirated content.  You will have to look elsewhere for help.
