### ISSUE TITLE
[Estuary] Kodi 20.0 white icons on white posters

### ISSUE THREAD

**Issue by Donski74** [xbmc/xbmc#22765]
### Describe the bug
Here is a clear and concise description of what the problem is:

On Kodi 20.0 the placement of the check mark icon representing Watched state and the three disc icon representing a set in views showing posters have been moved from under the poster to the bottom corner of the poster. The problem here is that being solid white it will not show up when displayed over a solid white area of some posters. The is only a problem in the Shift view, in other views like Wall and Poster the corner has an added shadow that allows the check mark to be seen.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

To be able to see the icons regardless of the graphics of the poster. 

## Actual Behavior

White icons disappear on white backgrounds in Shift view.

## Possible Fix

Add the shadow on Shift view like it is on other views.

### To Reproduce

1. Have a movie in your library with a poster that has a solid white area in the bottom left corner.
2. Enter Movies and change to Shift view.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android (Fire Stick and Google TV)
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows 10
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

I realize that some things can get over looked when doing major upgrades, like from Matrix to Nexus, and this will be fixed in Nexus 20.1. You guys have done an amazing job on this, thank you for all your hard work.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@jjd-uk maybe you can take a look into this one?

**Comment by DaVukovic** [comment]
I can confirm:

Shift:

![image](https://user-images.githubusercontent.com/7235787/218528856-4c294be7-7761-48ab-b32a-f6f197434cd1.png)

Infowall:

![image](https://user-images.githubusercontent.com/7235787/218528966-9fd38a12-8fb3-4738-84ea-fd2087856d58.png)

**Comment by jjd-uk** [comment]
Have found the issue and been able to fix it locally. Just need to find the time to create a PR to get the code change reviewed & merged.

**Comment by jjd-uk** [comment]
Making a note here, fix attempts deemed not accetpable. We probably need to redo these icons so they don't require a background which is beyond my skill.

**Comment by b-jesch** [comment]
Background is already included in Texture.xbt. If you don't want to code twice or multiple, put background and checkmark variable into an include and call that.
