### ISSUE TITLE
Kodi 20 - UPNP Problem

### ISSUE THREAD

**Issue by someuser94** [xbmc/xbmc#22769]
### Describe the bug
Error in watched upnp message

## Expected Behavior
After watched a vide file I expect my server (libreelec 10/11) mark video as watched

## Actual Behavior
Nothing, the state of video stay unwatched

### To Reproduce
Open video e stop it, the upnp server doesn't save position or watched

### Debuglog
wireshark caputered traffic:
request:

`POST /ContentDirectory/20a537ff-4e23-7c90-7425-f47a1c01f301/control.xml HTTP/1.1
SOAPAction: "urn:schemas-upnp-org:service:ContentDirectory:1#UpdateObject"
User-Agent: UPnP/1.0 DLNADOC/1.50 Kodi
Host: 192.168.1.254:1882
Content-Length: 795
Content-Type: text/xml; charset="utf-8"

<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><u:UpdateObject xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><ObjectID>videodb%3a%2f%2finprogresstvshows%2f384%2f1%2f7778%3fseason%3d1%26tvshowid%3d384/</ObjectID><CurrentTagValue>&lt;upnp:lastPlaybackPosition&gt;0&lt;/upnp:lastPlaybackPosition&gt;,&lt;upnp:lastPlayerState&gt;&lt;/xbmc:lastPlayerState&gt;,&lt;upnp:playCount&gt;0&lt;/upnp:playCount&gt;</CurrentTagValue><NewTagValue>&lt;upnp:lastPlaybackPosition&gt;0&lt;/upnp:lastPlaybackPosition&gt;,&lt;upnp:lastPlayerState&gt;&lt;/xbmc:lastPlayerState&gt;,&lt;upnp:playCount&gt;1&lt;/upnp:playCount&gt;</NewTagValue></u:UpdateObject></s:Body></s:Envelope>`

response
`HTTP/1.1 500 Internal Server Error
Ext: 
Date: Mon, 13 Feb 2023 16:49:44 GMT
Content-Length: 447
Content-Type: text/xml; charset="utf-8"
Server: UPnP/1.0 DLNADOC/1.50 Platinum/1.0.5.13

<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>702</errorCode><errorDescription>Invalid currentTagvalue</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>`

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system windows 10 21H2
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
We request the debug log for a reason...

**Comment by someuser94** [comment]
https://paste.kodi.tv/wobaruyaxu.kodi

this is the log with upnp log enabled. but there isn't the xml exchanged with server

**Comment by enen92** [comment]
Can you provide more context about what you're doing?
I assume you have one kodi instance serving the content via UPnP and watching the content on some other player? Which player? Another kodi instance?

**Comment by someuser94** [comment]
this is my environments

server: lebreelec 10 and libreelec 11 beta 1 on rpi4
client: kodi 20 on windows 10 and kodi 20 on tablet android

before upgrade client everything work fine: when finished a video the client sent message to server and server marked videos as watched

I noticed now there's a repetition of this tag in xml
`<upnp:lastPlaybackPosition>0</upnp:lastPlaybackPosition>,<upnp:lastPlayerState></xbmc:lastPlayerState>,<upnp:playCount>1</upnp:playCount>`

and the tag 
`<upnp:lastPlayerState>` it's closed witch different prefix `</xbmc:lastPlayerState>`

**Comment by enen92** [comment]
Thanks for reporting, should be fixed by the pr listed above
