### ISSUE TITLE
CNetworkServices::StopJSONRPCServer() leaks thread on exit.

### ISSUE THREAD

**Issue by stevehartwell** [xbmc/xbmc#22778]
My thread sanitizer has found that the JSONRPC thread has not exited when `XBMC_Run()` returns.
In general leaked threads can and have lead to crashes on exiting the Kodi application, since the main thread runs destructors on static objects, which might be still in use by leaked threads.

I have found what I think is the issue:
https://github.com/xbmc/xbmc/blob/71c28c78e79cce093af000294306ae61c1e6048b/xbmc/network/NetworkServices.cpp#L891-L896
This method is called twice by Kodi main loop, first with `bWait = false`, and again later with `bWait = true`.

The problem is that after `CNetworkServices::StopJSONRPCServer(false)` is called, the subsequent call to `CNetworkServices::StopJSONRPCServer(true)` returns without joining the thread because of the logic in `IsJSONRPCServerRunning()`.  Apparently the thread state can be ready without having been joined.

I'm filing this as a bug because I am not at all familiar with this code.  I can say that removing the `IsJSONRPCServerRunning()` seems to fix the issue, but I can't be sure.

I am running macOS 12.  I cannot assess whether the issue is platform-specific.

**Comment by stevehartwell** [comment]
Stale.

**Comment by garbear** [comment]
I pulled up the code and it looks like removing `IsJSONRPCServerRunning()` might be correct.
