### ISSUE TITLE
Kodi on Linux crashes playing some videos

### ISSUE THREAD

**Issue by malchmalch** [xbmc/xbmc#22801]
Kodi crashes when playing *some* videos. Most are H.265 encoded in MPG containers with 
a single subtitle stream.

I have extracted a 10 second clip of one problem video which is available here.

https://www.malch.com/clip.mp4

Steps to reproduce:

1. Add the video clip above to a Kodi collection
2. Play the video
3. Observe Kodi crash

A crashlog with debug and gdb traceback available here (this with 20.0-3):

https://paste.kodi.tv/edunokiqos.kodi

Manjaro: 22.0.3
Kernel: 5.15.93-1-MANJARO
Kodi: 20.0-3 (originally) AND kodi-git r62284.c11f500aca7-1 (for confirmation)
Hardware: Intel 7 Gen NUC (also crashes on a AMD system)

**Comment by lrusak** [comment]
Looks like it's hitting an assert in `CDVDOverlayCodecTX3G::Decode`.

Can you install debug symbols and post a new crash log please?

**Comment by CastagnaIT** [comment]
thanks for the sample
seem there are problems related to syles to be fixed
in the past i tried to fix it but now i have understand the cause of problem
i will investigate for a solution

**Comment by malchmalch** [comment]
Thank you!
