### ISSUE TITLE
Chorus2 web interface missing files in Windows desktop nullsoft installer

### ISSUE THREAD

**Issue by scott967** [xbmc/xbmc#22822]
### Describe the bug
Here is a clear and concise description of what the problem is:

When a process attempts to establish an http connection with a GET to a Kodi instance running on Win 10 desktop, Kodi responds with a 404

Forum support thread https://forum.kodi.tv/showthread.php?tid=372078

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi responds with  a 200 and serves appropriate html text/images

## Actual Behavior

Browser gets a 404

## Possible Fix

In review of the contents of the Nullsoft installer for Kodi 20.0, comparing addons/webinterface.default, several files are missing which are present on Github.  I assume something is going wrong when addons are being built for Windows release installer and the files aren't being included.  Copying the missing files from github to the Kodi instance results in Chorus2 working as expected.

### To Reproduce

1. Install Kodi on Win desktop from Nullsoft installer
2. Configure Kodi to allow control via the web interface
3. Attempt to connect to running Kodi interface with a browser
4.
5.

### Debuglog

The debuglog can be found here:
[debug with webinterface component logging](https://paste.kodi.tv/wenedorizo.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 10 x64 22H2  Also tested on Win 8.1 x64
 - Kodi version: 20.0  Win10 x64 release installer 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by scott967** [comment]
I should note than when I build Kodi in VS Studio from Kodi.sln or CMake the files do get copied into my out of source build.

**Comment by fuzzard** [comment]
https://github.com/xbmc/xbmc/pull/22811
