### ISSUE TITLE
Android Kodi Can't Take Screenshot Hardware Acceleration MediaCodec Surface 

### ISSUE THREAD

**Issue by osumoclement** [xbmc/xbmc#22824]
### Describe the bug
Unable to take a screenshot when a video is hardware accelerated - MediaCodec (Surface)

When I try to take a screenshot, the display black out for half a second and then playback resumes. There isn't anything in the logs to show why this happens unfortunately. From the investigation I've done, this seems to predictably happen on all Android devices running GLES (MediaCodec Surface)

On checking the log files, messages defined in `Screenshot.cpp` and which should have shown up, like `"Screenshot {} failed"` do not appear, suggesting that the problem occurs much earlier in the execution stack.

If I take a screenshot while the Playback menu overlay is visible, an image will be created, but this image will show Kodi GUI and the part where video should have been is just black.

If I disable MediaCodec (Surface) and enable plain MediaCodec, screenshots work, but this isn't ideal as then my device struggles to play the file with no hardware acceleration and playback is choppy.

## Expected Behavior

I expect a screenshot to be saved in the screenshot folder that's configured in Kodi settings

## Actual Behavior

Video blanks for half a second and resumes playback, no screenshot file saved

## Possible Fix

I think this has something to do with GLES. This [related answer](https://stackoverflow.com/a/28729366/5083223) seems to suggest a solution in Java. I dived into Kodi source code and I can see there's decent similarity between the Java and the C++ functions in Kodi's  `Screenshot.cpp` that could be helpful, as shown below:
`//set alpha byte to 0xFF
  for (int y = 0; y < surface->GetHeight(); y++)
  {
    unsigned char* alphaptr = surface->GetBuffer() - 1 + y * surface->GetStride();
    for (int x = 0; x < surface->GetWidth(); x++)
      *(alphaptr += 4) = 0xFF;
  }

  .....
   
 if (!CPicture::CreateThumbnailFromSurface(surface->GetBuffer(), surface->GetWidth(), surface->GetHeight(), surface->GetStride(), filename))`

### To Reproduce

1. Needs an Android Device that has MediaCodec Surface
2. Disable MediaCodec Surface and enable just MediaCodec
3. Play a video, and try to take a screenshot

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/hewogoxujo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 11
 - Kodi version: 20.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
This is a known limitation of hw decoding on Android. We don't know the frame representation so it would require workarounds to make it work.

**Comment by osumoclement** [comment]
Ah, that's a bummer. Could you kindly provide me a few resources I can read to learn more on this limitation? Or even search terms, I haven't had much luck on Google

**Comment by osumoclement** [comment]
I think one workaround could be this - when a user tries to take a screenshot, check if app is using MediaCodec Surface. If so, re-render the currently playing content to a dummy non-hardware accelerated view and get screenshot from this. Then simply discard the dummy non-hardware accelerated view

**Comment by fritsch** [comment]
PR welcome. Hint: it's only that simple in Powerpoint.

**Comment by osumoclement** [comment]
I couldn't even get Kodi to compile, C++ sure is something. But I won't rest until a solution is found 😌
