### ISSUE TITLE
 In kodi 20 Video has audio stutters and takes a long time to start, downgrade to 19 solves the issue

### ISSUE THREAD

**Issue by RobVerduijn** [xbmc/xbmc#22837]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello,

I've posted this issue before on the netflix plugin issue list and I was told that it was not a netflix plugin issue
https://github.com/CastagnaIT/plugin.video.netflix/issues/1556

I'm running kodi using the flatpak version on fedora37 kinoite.
When kodi was upgraded to 20 bij flatpak the netflix videos started to give issues
- long time to start
- audio stutter
downgrading to the last kodi 19 flatpak version solved the problem
For those who wonder which version:
```bash
flatpak update --commit=e15d861c08f40a370b16efe0a999b59f85727032077f6c4bdc7102336387154d tv.kodi.Kodi
```

there are also a lot of the following errors in the logs:
 error <general>: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
and even more warnings:
warning <general>: ActiveAE - large audio sync error: -25496.991293

The workaround is to  downgrading the kodi version back to 19.1
Everything works smoothly again after that.

debug log on pastebin link: https://paste.kodi.tv/opulirizaz.kodi

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
pastebin link: https://paste.kodi.tv/opulirizaz.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

na

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Fedora 37 kinoite 
- Kodi version:
20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
imo more rilevant the sink error not mentioned

```
2023-02-19 19:47:41.551 T:17      error <general>: ActiveAE::InitSink - failed to init
2023-02-19 19:47:41.551 T:17    warning <general>: CActiveAE::StateMachine - signal: 11 from port: OutputControlPort not handled for state: 2
2023-02-19 19:47:41.551 T:17    warning <general>: CActiveAE::StateMachine - signal: 12 from port: OutputControlPort not handled for state: 2
```

**Comment by fritsch** [comment]
There was no change in pulseaudio since a very long time. I see that you have an USB DAC connected, which just can do two channel audio. Please set the number of speakers to two channels inside kodi as well.

The issue only happens with inputstream and this addon? All local files play okayish?

**Comment by RobVerduijn** [comment]
Fedora 37 kinoite uses the pipewire with the pipewire-pulse plugin

I double checked, kodi was already set to 2.0 channels, just in case I've also set the netflix-plugin to prefer stereo audio  channels. (this did not help, i have no premium so there is no dolby digital/4k/etc for me available)

I checked to see if this problem occurs anywhere else, local files play fine.
My local files are an nfs mount from my nas, I have all converted all my blue-ray/dvd to mkv.

Regarding inputstream: I also tested disney+ and hbomax , they play fine. (quick to start and no audio stutter)

**Comment by fritsch** [comment]
Okay, thanks for the feedback. So currently isolated to the netflix plugin.

**Comment by RobVerduijn** [comment]
"dolby digital plus" was already disabled.
However, after thinking it over I decided to give the inputstream-adaptive settings a review.
Didn't really mean anything to me so I just hit reset on them and set the max resolution to auto for video  and drm video
(both were set to 720p)

And now it all works fine again.
Not really a clue as to why this helped but the videos are playing smoothly again.

Rob
