### ISSUE TITLE
Can you please for the love of god fix the build docs (Android Docs request (+ Addons)).

### ISSUE THREAD

**Issue by KyleSanderson** [xbmc/xbmc#22835]
### Describe the bug
Here is a clear and concise description of what the problem is:
Good lord I've been struggling following the incredibly broken documentation... https://github.com/xbmc/xbmc/blob/master/docs/README.Android.md is riddled with errors. and https://github.com/xbmc/vfs.sftp doesn't give me a target system addon at all despite trying a multitude of manual things after the docs did not work.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Someone puts work effort in to test their changes before submitting them.

## Actual Behavior

A very upset developer wasting hours on broken documentation. For something this complicated to build and the clear effort that has gone into having a full fledged build system, documenting how to perform a basic action (like compiling an addon for inclusion in the APK) would go a long way to attracting people to the community.

## Possible Fix

Please for the love of god spend the 7 minutes to update the build information.

### To Reproduce

1. Follow the documentation...
2. Get burned...
3. Complete waste of time.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] tvOS
 - [x] Linux
 - [x] macOS
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Once again. PR's welcome. Or at least provide info on what step is supposedly the end of the world...

**Comment by lrusak** [comment]
Instructions were just updated in #22690

Please PR any relevant changes if they aren't clear or open a forum thread for support please. https://forum.kodi.tv/

**Comment by KyleSanderson** [comment]
> Instructions were just updated in #22690
> 
> Please PR any relevant changes if they aren't clear or open a forum thread for support please. https://forum.kodi.tv/

There's still no way to build addons with the documentation that's there.

**Comment by fuzzard** [comment]
https://github.com/xbmc/xbmc/blob/master/docs/README.Android.md#6-build-binary-add-ons ?

**Comment by KyleSanderson** [comment]
> https://github.com/xbmc/xbmc/blob/master/docs/README.Android.md#6-build-binary-add-ons ?

There doesn't appear to be a way to build your own in that unified manner, even for patches. I tried to hack the sources but the tracking is broken and reruns the complete pull again.

**Comment by KyleSanderson** [comment]
I'm just trying to build this simple core xbmc addon and it's been a nightmare https://github.com/xbmc/vfs.sftp/pull/114 . There's been gaslighting for years that there's no problem with any of these backends, and I'm putting my money where my mouth is and proving that there are deep fundamental issues outside of maybe one single code path.

**Comment by fuzzard** [comment]
Ask the question on the forums, and you would have been given help. For a specific add-on dev, it's out of scope for core docs. Build the add-on individually and install the zip.

With that said, I'd still recommend opening a thread on the forums. There are alternative methods, that are simple enough, but the docs aren't, and can't, be complete for every possible thing someone could want to do.

**Comment by KyleSanderson** [comment]
> Ask the question on the forums, and you would have been given help. For a specific add-on dev, it's out of scope for core docs. Build the add-on individually and install the zip.
> 
> With that said, I'd still recommend opening a thread on the forums. There are alternative methods, that are simple enough, but the docs aren't, and can't, be complete for every possible thing someone could want to do.

I've given it a shot: https://forum.kodi.tv/showthread.php?tid=372150
