### ISSUE TITLE
Kodi Nexus v 20 Error message in logs that is produced when some addons run 

### ISSUE THREAD

**Issue by Shredder5262** [xbmc/xbmc#22832]
### Describe the bug
Here is a clear and concise description of what the problem is:
I see an error message in the logs that is produced when some addon's run which either causes Kodi to crash or the addon to not function correctly. The commonality seems to be that whenever a python script references the 'xbmc' module, the error message below happens. The context is different with each plugin, but the error references that 'translatepath' is problematic. 

2023-02-20 09:07:45.727 T:25504   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "D:\Kodi\Kodi - V20 Nexus\portable_data\scripts\skin.aeonmq8.matrix.mod\New_Years_Day\skinchange-New_Years_Day.py", line 9, in <module>
                                                       src = xbmc.translatePath('special://home/userdata/addon_data/skin.aeonmq8.matrix.mod/New_Years_Day/settings.xml')
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
to not make an error message and to function as expected. There are multiple scripts that have path references like this so the function is different depending on the addon for this functionality.

## Actual Behavior
Kodi either crashes entirely or produces an error both on-screen and in the logs. 

## Possible Fix
I don't know python well enough to suggest a fix, but i would suggest starting with the 'translatePath' attribute.

### To Reproduce
a simple example of this would be to install the addon "cron for Kodi" and this error message is produced. I have other addon's that produce this, but this is a simple example. 

### Debuglog
I can provide debug logs upon request, but the error message is pretty obvious. 

### Your Environment
Used Operating system:
Windows 11

 - Operating system version/name:
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by the-black-eagle** [comment]
The error happens because `translatePath` has been moved from the xbmc module to the xbmcvfs module.  This is not a core error, rather the addon needs updating to work with later Kodi versions.  See https://alwinesch.github.io/python_v19.html#_python_v19000033

**Comment by CastagnaIT** [comment]
the authors of all the addons you are using have forgotten to make these changes already with Kodi 19...
