### ISSUE TITLE
NFS code-wise is an absolute disaster

### ISSUE THREAD

**Issue by KyleSanderson** [xbmc/xbmc#22834]
### Describe the bug

Man.... There's poorly placed locks riddled everywhere. Some of these locks are before DNS lookups even occur with string formatting and similar from params no where near critical sections in code. This has been okay for low bitrate content, but it's not optimized or anywhere near as performant as it should be **at all**. This leads to the continued bad xbmc community talk track that NFS itself is slower than SMB, which is simply not true.

## Expected Behavior
If a library scan is running, it shouldn't overly impact a very simple file read.

## Actual Behavior

Hard stalls.

## Possible Fix

I guess I could step up and rewrite the whole thing to use the event / async API (or use ref counting... any paradigm from 2003 should be fine). SMB is pretty darn close to being correct (small sections could use some additional scoping to RAII the locks back).

### To Reproduce

1. Tons of reported performance issues...
2. Tons of gaslighting...
3. Finally review the code, and immediately see dozens of problems.

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://github.com/xbmc/xbmc/blob/b7e260591c52b7f88d8ac69d1bdf85a3348cdac9/xbmc/filesystem/NFSFile.cpp#L290 wtf.
https://github.com/xbmc/xbmc/blob/b7e260591c52b7f88d8ac69d1bdf85a3348cdac9/xbmc/filesystem/NFSFile.cpp#L359 wrong.
https://github.com/xbmc/xbmc/blob/b7e260591c52b7f88d8ac69d1bdf85a3348cdac9/xbmc/filesystem/NFSFile.cpp#L445 dead? + wtf.
https://github.com/xbmc/xbmc/blob/b7e260591c52b7f88d8ac69d1bdf85a3348cdac9/xbmc/filesystem/NFSDirectory.cpp#L105 wtf.
https://github.com/xbmc/xbmc/blob/b7e260591c52b7f88d8ac69d1bdf85a3348cdac9/xbmc/filesystem/NFSDirectory.cpp#L206 wtf. very expensive and a lot of work to be done here.
https://github.com/xbmc/xbmc/blob/b7e260591c52b7f88d8ac69d1bdf85a3348cdac9/xbmc/filesystem/NFSDirectory.cpp#L319 not as bad but still terrible.
https://github.com/xbmc/xbmc/blob/b7e260591c52b7f88d8ac69d1bdf85a3348cdac9/xbmc/filesystem/NFSDirectory.cpp#L365 see above.

I left out all the refcounting, but hopefully that helps show the issues here.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I know vfs.ssh has been orphaned for many years now (4+). async_read would likely improve the situation substantially per the general guidance given 13 years ago: https://www.mail-archive.com/libssh@libssh.org/msg00370.html 

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version: Leia / Matrix / Nexus 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Most of the code was written 12+ years ago. PR's are always welcome.

**Comment by lrusak** [comment]
Yes the code is in bad shape. I was aware of that when adding NFSv4 support. Ranting about it doesn't help though and discussion is better handled on the forum than on a bug tracker. https://forum.kodi.tv/
