### ISSUE TITLE
"File no longer available, remove it from library?"....but it's there

### ISSUE THREAD

**Issue by damoncui1993** [xbmc/xbmc#22843]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi uses Webdav to mount the directory. 
After scanning and information searching,
Kodi directly clicks to play the movie or episode and displays: "**File no longer available, remove it from library**"? 
However, open the movie information and click the play button again to play normally，How to fix this？

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
20.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by damoncui1993** [comment]
Kodi uses Webdav to mount the directory. After scanning and information searching, Kodi directly clicks to play the movie or episode and displays: "File no longer available, remove it from library"? However, open the movie information and click the play button again to play normally，How to fix this？

**Comment by thexai** [comment]
You not provided any useful info, debug log, etc. 

Then I'm going to close this "no bug".

Please use forum for support: https://forum.kodi.tv

**Comment by damoncui1993** [comment]
> You not provided any useful info, debug log, how to reproduce, etc.
> 
> Then I'm going to close this "no bug".
> 
> Please use forum for support: https://forum.kodi.tv

Sorry, we didn't have time to supplement the log information yesterday. It has been supplemented now. Could you open the question again.

**Comment by thexai** [comment]
For logs use paste site https://paste.kodi.tv/ and full logs please (not snipps)

Anyway GitHub issues are only for track confirmed bugs, not support questions.

Please continue in forum: https://forum.kodi.tv/
