### ISSUE TITLE
When using Confluence Skin on Kodi v20 (Nexus) the system hangs when navigating to some SMB shares

### ISSUE THREAD

**Issue by Sesshoumaru-sama** [xbmc/xbmc#22855]
### Describe the bug
Out of my 4 SMB shares (all on the same TrueNas instance) on one Kodi hangs when navigating into the folder.

## Expected Behavior
Kodi should not hang when trying to access a share.

## Actual Behavior
System is blocked, UI hangs, gets dimmed, killed by Windows later

### To Reproduce
1.  Install Kodi v20
2.  Setup some SMB shares with different video + audio files
3. Use Confluence as Skin

### Debuglog
The debuglog can be found here:
[kodi_conflu.log](https://github.com/xbmc/xbmc/files/10819767/kodi_conflu.log)

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win10 21H2
 - Kodi version: V20.0.0

I know Confluence is an older skin, still I like it and would love if it keeps working. I also have a dmp-file if needed

**Comment by enen92** [comment]
Does the issue also happen if you use estuary? If not this doesn't really apply as a kodi issue. Maybe bring the issue to confluence repo.
cc @DaVukovic

**Comment by Sesshoumaru-sama** [comment]
No, when I use estuary I can access the folders normal - thats how I figured out it has somethnig to do with the skin.
Is there some dedicated confluence bug tracker?

**Comment by DaVukovic** [comment]
If it's really the skin, then yes. There's a separated bug tracker: 
https://github.com/xbmc/skin.confluence/issues

I can't help for windows as I don't have a single machine at home which uses Windows. Sorry.

Further more, I'm not too sure, if it's really an issue of the skin alone. For what I can see in the logs, the log ends with the message:

`2023-02-24 02:00:33.115 T:27980   debug <general>: AddOnLog: pvr.vdr.vnsi: Open - failed to connect to the backend`

The only skin-related issue I see is: 

`2023-02-24 02:00:31.934 T:6560    debug <general>: [Warning] CGUITextureManager::GetTexturePath: could not find texture 'OverlayUnwatched.png'`

and that's probably we're returning that image here:

https://github.com/xbmc/xbmc/blame/master/xbmc/guilib/GUIListItem.cpp#L177

and Confluence doesn't use that, but it's used in Estuary. In the end, this part is a "warning" only and shouldn't cause Kodi to crash or stall. 

Could you please try to disable the vdr.vnsi addon and see if the problem still exists?

If the issue still exists, I'll try to add this texture to the next Confluence release. You could probably try yourself before I do....
* navigate to: `%APPDATA%\Kodi\addons\skin.confluence\media`
* create a copy of the file `OverlayWatched.png` and name it `OverlayUnwatched.png` at the same folder
* restart Kodi and try to reproduce your issue

If this fixes your issue with the vnsi-Addon enabled, then this might still be an issue with Kodi returning a hardcoded texture which is probably not a requirement for all skins. 

If this doesn't fix your issue, then try disabling the vnsi-Addon and see if that helps. 

If that doesn't help as well, we might need a new debuglog with component specific logging turned on and select "Verbose logging for the SMB library"-component. Maybe this gives us more insights. 

In general I don't see why this specific share should cause an issue especially with confluence while other shares are working well. The name of the share doesn't contain any strange characters and the rest is done by Kodi itself and shouldn't be skin-related at all. 

For a test, I've just added a SMB-share from my UnRaid server to my Kodi 20 instance on Linux and for I can tell, I can't reproduce your issue.

**Comment by Sesshoumaru-sama** [comment]
I unnstalled the VNSI as first attempt but it did not change the behavior.
I will try to add the texture file as described above and give you feedback.

The isse is that I have 4 SMB shares and 3 of them work like always only the one share has this problem. The only differnce is that the working shares have only folders in them, the files are deeper down. While the not working has directly files in it. I will also investigate. As I can reproduce it also on my laptop easily I could also create a dmp-file from the system hanging. Just don't have the PDBs at the moment for meaningful debugging.

**Comment by Sesshoumaru-sama** [comment]
Now thats ... I checked with files and it did worked, but then I checked with my original share and it did not work.
After some speculation I found a lead. I when there is a certain file present in the share, it hangs... the this one:
[ Yuru Camp△_ゆるキャン△ ]Op - Shiny Days _ Asaka ( Lyrics ) (1080p_30fps_VP9-128kbit_AAC).mkv

So I kinda assumed it could be the Japanese letters in the name... and bingo! When I remove "△_ゆるキャン△" the system does not hang anymore..... isn't that all handled as Unicode these days? @DaVukovic

**Comment by DaVukovic** [comment]
Totally not sure. Might also depend on the OS in use or on our implementation of the SMB protocoll. 

I would say, close this issue, as the name might be misleading, open a new one and name it something like: 

"Kodi hangs with specific characters in filenames inside a SMB share"

At least it's not a skin issue and I'm glad you found the issue. So you could easily rename your files and are able to enjoy Kodi. ;) 

If you agree, you are free to close this issue yourself.

**Comment by anxdpanic** [comment]
This sounds like https://github.com/xbmc/xbmc/pull/22658

**Comment by DaVukovic** [comment]
ok. So you say we might be using the wrong font in Confluence?

**Comment by DaVukovic** [comment]
@Sesshoumaru-sama 

Scratch all what I've written above. 

If you are willing to test, you could probably try one of our nightlies: 

https://mirrors.kodi.tv/nightlies/windows/win64/master/

I would use the newest master build. It includes the mentioned fix @anxdpanic is talking about. We also backported that fix to be included in Nexus builds. I'm not sure when the next Nexus update will be released. But you could do us a favor and test a nightly and tell us if that fixes your issue. 

In general we changed how Kodi behaves if fonts in Skins are missing unicode chars.

**Comment by jjd-uk** [comment]
The has been backported to Nexus in https://github.com/xbmc/xbmc/pull/22659 then you can get a Nexus build with fix from http://mirrors.kodi.tv/nightlies/windows/win64/Nexus/

The Nexus Nightlies are basically 20.0 + addional fixes added

**Comment by Sesshoumaru-sama** [comment]
Okay, I will check with a nightly that includes #22659

**Comment by Sesshoumaru-sama** [comment]
I can confirm that with #22659 the issue is gone, there are the "unknown letter sign" again and no hang.
But I prefer Arial-based, because there the real japaese characters are rendered. Maybe it would be goot to have a unicode font as default in the future anyhow. Thank for all your support.
