### ISSUE TITLE
Pictures - Date of a picture is not using EXIF "DateTimeOriginal" 

### ISSUE THREAD

**Issue by BuckShotSX** [xbmc/xbmc#22900]
### Describe the bug
Here is a clear and concise description of what the problem is:

In Pictures when viewing the picture's Date it is not using EXIF's "DateTimeOriginal" .  It is using "ModifyDate".  
This is a change in behaviour from previous versions, 19.X at least, of Kodi.   
This means that the sort of pictures by "Date taken" is using "ModifyDate" as well.   

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When viewing pictures the "Date" of the picture should use EXIF's "DateTimeOriginal" as in previous versions of Kodi.  
Sorting by "Date Taken" should also use EXIF "DateTimeOriginal".   
Summary:  EXIF "DateTimeOriginal" should be used for "Date" in Kodi.

## Actual Behavior
The Date of a picture is EXIF "ModifyDate" and sorting by "Date taken" is also using "ModifyDate" instead of using "DateTimeOriginal".

## Possible Fix
As in previous 19.X, at least, version of Kodi used "DateTimeOriginal" for the "Date" being displayed in Kodi.  If this field is use for Date I suspect the sorting by "Date taken" in Kodi will also be corrected.

### To Reproduce

1. Go to Pictures.
2. Select one picture and look at the date information of a picture in a tool like ExifTool or ExifToolGui.
3. Note "ModifyDate" "DateTimeOriginal" "CreateDate"
4. Modify the "DateTimeOriginal" field.   
5. Notice this change in date isn't displayed in Kodi.
6. *Note the field "ModifyDate" is not the field you see in Windows Explorer "Date modified".

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I have made modifications  to "TimeDateCreated" to pictures in a folder that has pictures from multiple cameras.   The cameras, unfortunately, did not have their time's synchronized.   Now I can't sort by this field. 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Windows 10 21H2/Kodi 20.0.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by rockrider69** [comment]
Hello,

+1 for this issue! it is  being quite a problem for correct sorting out of pictures.

By the way I found another issue with  EXIF tag "UserComment" not being reported correctly although they were perfectly ok in Matrix or Leia when used in Slideshow labels for example:

$INFO[Slideshow.EXIFComment]       : gives now an empty string despite it is not empty at all
$INFO[Slideshow.SlideComment]       : supposed to be same as previous one, according to documentation, but now gives something weird about lavc software version. Not empty though if the documentation should be right...

Would that mean more deeply broken stuff in EXIF tags management ?
