### ISSUE TITLE
Request: Add date+time for lastplayed on NFO export

### ISSUE THREAD

**Issue by Uatschitchun** [xbmc/xbmc#22917]
The lastplayed tag for movies gets saved as Date+Time in DB and even gets exported as Date+Time in a JSON request. When eporting NFOs, only Date gets exported. 

The Date+Time gets read in & served back correct when updating a movie from NFO which contains lastplayed as: `<lastplayed>YYYY-MM-DD HH:mm:ss</lastplayed>`

**Comment by fuzzard** [comment]
Feature requests can be made on the forums - https://forum.kodi.tv/forumdisplay.php?fid=9
