### ISSUE TITLE
GUI flickering after PR #18812

### ISSUE THREAD

**Issue by smp79** [xbmc/xbmc#22921]
### Describe the bug
Here is a clear and concise description of what the problem is:

#18812 introduced a GUI issue as described [here](https://github.com/LibreELEC/LibreELEC.tv/issues/6180#issuecomment-1027400840). It is most noticeable during TV channel switching.
[Video](https://www.dropbox.com/s/gedxb0ed4lde2k3/VID_20201127_180324.mp4?dl=1)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

GUI shouldn't flicker.

## Actual Behavior

As seen in the video above.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/eruhuzikuz.kodi

### Your Environment
Used Operating system:

 - [x] Linux

 - Operating system version/name: LibreELEC
 - Kodi version: current master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
What I think is happening is on a channel change, there is no video texture available for Kodi to present. On GLES, we don't blank the pixels which are usually covered by the video, resulting in undefined values at those positions.

The linked PR fixes the issue by accident, as front to back rendering needs a bit more care when clearing the screen. A full screen triangle is drawn in this case.

Ideally, I think we should keep presenting the last video frame, but having a black screen is better than this behaviour.

**Comment by smp79** [comment]
Any chance you can merge this fix? -

```
From 3ac2b8d4ff6741d29bb73a7874f1fda6a0c660b5 Mon Sep 17 00:00:00 2001
From: sarbes <sarbes@kodi.tv>
Date: Sun, 12 Mar 2023 13:48:45 +0100
Subject: [PATCH] Force screen clear when playing a video on GLES

---
 xbmc/video/windows/GUIWindowFullScreen.cpp | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/xbmc/video/windows/GUIWindowFullScreen.cpp b/xbmc/video/windows/GUIWindowFullScreen.cpp
index 7cebc5fa07..7e139fd22b 100644
--- a/xbmc/video/windows/GUIWindowFullScreen.cpp
+++ b/xbmc/video/windows/GUIWindowFullScreen.cpp
@@ -180,6 +180,8 @@ void CGUIWindowFullScreen::ClearBackground()
   const auto appPlayer = components.GetComponent<CApplicationPlayer>();
   if (appPlayer->IsRenderingVideoLayer())
     CServiceBroker::GetWinSystem()->GetGfxContext().Clear(0);
+  else
+    CServiceBroker::GetWinSystem()->GetGfxContext().Clear(0xff000000);
 }
 
 void CGUIWindowFullScreen::OnWindowLoaded()
```

**Comment by sarbes** [comment]
Should be fixed in v22 with https://github.com/xbmc/xbmc/pull/22919
