### ISSUE TITLE
Compile Fails

### ISSUE THREAD

**Issue by quantum77** [xbmc/xbmc#22932]
### Describe the bug
Here is a clear and concise description of what the problem is:

Setting up to compile Kodi precisely as described here:  https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md

configure goes fine as I've completed installing all dependencies.  But the compile fails as so:

Just re-cloned:

[ 13%] Building CXX object build/cores/paplayer/CMakeFiles/paplayer.dir/CodecFactory.cpp.o
cd /home/carl/src/kodi_build/build/cores/paplayer && /usr/bin/ccache /usr/lib64/ccache/c++  -I/home/carl/src/kodi-21.0 -I/home/carl/src/kodi-21.0/lib -I/home/carl/src/kodi-21.0/xbmc -I/home/carl/src/kodi-21.0/xbmc/platform/linux -I/home/carl/src/kodi-21.0/xbmc/cores/VideoPlayer -I/home/carl/src/kodi_build/build -I/home/carl/src/kodi-21.0/xbmc/platform/posix -isystem /home/carl/src/kodi_build/build/include -isystem /usr/include/dbus-1.0 -isystem /usr/lib64/dbus-1.0/include -isystem /usr/include/pipewire-0.3 -isystem /usr/include/spa-0.2 -isystem /usr/include/python3.9 -isystem /usr/include/samba-4.0 -isystem /usr/include/libxml2 -isystem /usr/include/ffmpeg -isystem /home/carl/src/kodi_build/build/cores/RetroPlayer/messages -isystem /usr/include/freetype2 -isystem /usr/include/fribidi -isystem /home/carl/src/kodi-21.0/xbmc/contrib -isystem /usr/include/lzo -isystem /usr/include/libdrm -Wall -Wdouble-promotion -Wmissing-field-initializers -Wsign-compare -Wextra -Wno-unused-parameter -Wnon-virtual-dtor -O3 -DNDEBUG -DTARGET_POSIX -DTARGET_LINUX -D_GNU_SOURCE -DHAVE_LINUX_UDMABUF=1 -DHAVE_LINUX_DMA_HEAP=1 -DHAVE_LINUX_DMA_BUF=1 -DHAVE_MKOSTEMP=1 -DHAVE_LINUX_MEMFD=1 -DHAVE_STATX=1 -DHAVE_SSE=1 -DHAVE_SSE2=1 -DHAVE_SSE3=1 -DHAVE_SSSE3=1 -DHAVE_SSE4_1=1 -D__STDC_CONSTANT_MACROS -D_FILE_OFFSET_BITS=64 -DHAS_POSIX_NETWORK -DHAS_LINUX_NETWORK -DHAS_BUILTIN_SYNC_ADD_AND_FETCH=1 -DHAS_BUILTIN_SYNC_SUB_AND_FETCH=1 -DHAS_BUILTIN_SYNC_VAL_COMPARE_AND_SWAP=1 -DHAVE_INOTIFY=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_INTTYPES_H=1 -DHAS_ALSA=1 -DHAS_AVAHI=1 -DHAS_ZEROCONF=1 -DHAVE_LIBBLURAY=1 -DHAVE_LIBBLURAY_BDJ=1 -DHAVE_LIBCEC=1 -DHAS_DBUS=1 -DHAS_ISO9660PP=1 -DHAVE_LCMS2=1 -DCMS_NO_REGISTER_KEYWORD=1 -DHAS_LIRC=1 -DHAS_WEB_SERVER=1 -DHAS_WEB_INTERFACE=1 -DHAS_PIPEWIRE=1 -DHAS_AIRPLAY=1 -DHAS_PULSEAUDIO=1 -DHAS_PYTHON=1 -DHAS_FILESYSTEM_SMB=1 -DHAVE_LIBUDEV=1 -DHAS_UDFREAD=1 -DHAVE_LIBXSLT=1 -DHAVE_LIBVA=1 -DHAS_GLX=1 -DHAVE_LIBVDPAU=1 -DHAVE_NEW_CROSSGUID -DFFMPEG_VER_SHA=\"5.0.0\" -DSPDLOG_FMT_EXTERNAL -DSPDLOG_DEBUG_ON -DSPDLOG_NO_ATOMIC_LEVELS -DSPDLOG_ENABLE_PATTERN_PADDING -DSPDLOG_COMPILED_LIB -DHAS_EGL=1 -DHAVE_EGLEXTANGLE=1 -DHAVE_X11=1 -DHAVE_LIBXRANDR=1 -DHAVE_HDR_OUTPUT_METADATA=1 -DHAVE_DRM_MODIFIER_NAME=1 -DHAS_GL=1 -DHAS_MYSQL=1 -DHAS_UPNP=1 -DHAS_DVD_DRIVE -DHAS_CDDA_RIPPER -DBIN_INSTALL_PATH=\"/usr/local/lib64/kodi\" -DINSTALL_PATH=\"/usr/local/share/kodi\" -Werror=double-promotion -Werror=missing-field-initializers -Werror=sign-compare -std=c++17 -MD -MT build/cores/paplayer/CMakeFiles/paplayer.dir/CodecFactory.cpp.o -MF CMakeFiles/paplayer.dir/CodecFactory.cpp.o.d -o CMakeFiles/paplayer.dir/CodecFactory.cpp.o -c /home/carl/src/kodi-21.0/xbmc/cores/paplayer/CodecFactory.cpp
/home/carl/src/kodi-21.0/xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp: In function ‘std::chrono::duration<double, std::ratio<1> > {anonymous}::PWTimeToAEDelay(const pw_time&, const uint32_t&)’:
/home/carl/src/kodi-21.0/xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp:235:13: error: ‘const struct pw_time’ has no member named ‘buffered’
  235 |       (time.buffered * fraction) + ((time.delay - elapsed) * fraction) +
      |             ^~~~~~~~
gmake[2]: *** [build/cores/audioengine/CMakeFiles/audioengine.dir/build.make:370: build/cores/audioengine/CMakeFiles/audioengine.dir/Sinks/pipewire/AESinkPipewire.cpp.o] Error 1
gmake[2]: Leaving directory '/home/carl/src/kodi_build'
gmake[1]: *** [CMakeFiles/Makefile2:6341: build/cores/audioengine/CMakeFiles/audioengine.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 13%] Building CXX object build/cores/paplayer/CMakeFiles/paplayer.dir/PAPlayer.cpp.o
cd /home/carl/src/kodi_build/build/cores/paplayer && /usr/bin/ccache /usr/lib64/ccache/c++  -I/home/carl/src/kodi-21.0 -I/home/carl/src/kodi-21.0/lib -I/home/carl/src/kodi-21.0/xbmc -I/home/carl/src/kodi-21.0/xbmc/platform/linux -I/home/carl/src/kodi-21.0/xbmc/cores/VideoPlayer -I/home/carl/src/kodi_build/build -I/home/carl/src/kodi-21.0/xbmc/platform/posix -isystem /home/carl/src/kodi_build/build/include -isystem /usr/include/dbus-1.0 -isystem /usr/lib64/dbus-1.0/include -isystem /usr/include/pipewire-0.3 -isystem /usr/include/spa-0.2 -isystem /usr/include/python3.9 -isystem /usr/include/samba-4.0 -isystem /usr/include/libxml2 -isystem /usr/include/ffmpeg -isystem /home/carl/src/kodi_build/build/cores/RetroPlayer/messages -isystem /usr/include/freetype2 -isystem /usr/include/fribidi -isystem /home/carl/src/kodi-21.0/xbmc/contrib -isystem /usr/include/lzo -isystem /usr/include/libdrm -Wall -Wdouble-promotion -Wmissing-field-initializers -Wsign-compare -Wextra -Wno-unused-parameter -Wnon-virtual-dtor -O3 -DNDEBUG -DTARGET_POSIX -DTARGET_LINUX -D_GNU_SOURCE -DHAVE_LINUX_UDMABUF=1 -DHAVE_LINUX_DMA_HEAP=1 -DHAVE_LINUX_DMA_BUF=1 -DHAVE_MKOSTEMP=1 -DHAVE_LINUX_MEMFD=1 -DHAVE_STATX=1 -DHAVE_SSE=1 -DHAVE_SSE2=1 -DHAVE_SSE3=1 -DHAVE_SSSE3=1 -DHAVE_SSE4_1=1 -D__STDC_CONSTANT_MACROS -D_FILE_OFFSET_BITS=64 -DHAS_POSIX_NETWORK -DHAS_LINUX_NETWORK -DHAS_BUILTIN_SYNC_ADD_AND_FETCH=1 -DHAS_BUILTIN_SYNC_SUB_AND_FETCH=1 -DHAS_BUILTIN_SYNC_VAL_COMPARE_AND_SWAP=1 -DHAVE_INOTIFY=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_INTTYPES_H=1 -DHAS_ALSA=1 -DHAS_AVAHI=1 -DHAS_ZEROCONF=1 -DHAVE_LIBBLURAY=1 -DHAVE_LIBBLURAY_BDJ=1 -DHAVE_LIBCEC=1 -DHAS_DBUS=1 -DHAS_ISO9660PP=1 -DHAVE_LCMS2=1 -DCMS_NO_REGISTER_KEYWORD=1 -DHAS_LIRC=1 -DHAS_WEB_SERVER=1 -DHAS_WEB_INTERFACE=1 -DHAS_PIPEWIRE=1 -DHAS_AIRPLAY=1 -DHAS_PULSEAUDIO=1 -DHAS_PYTHON=1 -DHAS_FILESYSTEM_SMB=1 -DHAVE_LIBUDEV=1 -DHAS_UDFREAD=1 -DHAVE_LIBXSLT=1 -DHAVE_LIBVA=1 -DHAS_GLX=1 -DHAVE_LIBVDPAU=1 -DHAVE_NEW_CROSSGUID -DFFMPEG_VER_SHA=\"5.0.0\" -DSPDLOG_FMT_EXTERNAL -DSPDLOG_DEBUG_ON -DSPDLOG_NO_ATOMIC_LEVELS -DSPDLOG_ENABLE_PATTERN_PADDING -DSPDLOG_COMPILED_LIB -DHAS_EGL=1 -DHAVE_EGLEXTANGLE=1 -DHAVE_X11=1 -DHAVE_LIBXRANDR=1 -DHAVE_HDR_OUTPUT_METADATA=1 -DHAVE_DRM_MODIFIER_NAME=1 -DHAS_GL=1 -DHAS_MYSQL=1 -DHAS_UPNP=1 -DHAS_DVD_DRIVE -DHAS_CDDA_RIPPER -DBIN_INSTALL_PATH=\"/usr/local/lib64/kodi\" -DINSTALL_PATH=\"/usr/local/share/kodi\" -Werror=double-promotion -Werror=missing-field-initializers -Werror=sign-compare -std=c++17 -MD -MT build/cores/paplayer/CMakeFiles/paplayer.dir/PAPlayer.cpp.o -MF CMakeFiles/paplayer.dir/PAPlayer.cpp.o.d -o CMakeFiles/paplayer.dir/PAPlayer.cpp.o -c /home/carl/src/kodi-21.0/xbmc/cores/paplayer/PAPlayer.cpp
[ 13%] Building CXX object build/cores/paplayer/CMakeFiles/paplayer.dir/VideoPlayerCodec.cpp.o
cd /home/carl/src/kodi_build/build/cores/paplayer && /usr/bin/ccache /usr/lib64/ccache/c++  -I/home/carl/src/kodi-21.0 -I/home/carl/src/kodi-21.0/lib -I/home/carl/src/kodi-21.0/xbmc -I/home/carl/src/kodi-21.0/xbmc/platform/linux -I/home/carl/src/kodi-21.0/xbmc/cores/VideoPlayer -I/home/carl/src/kodi_build/build -I/home/carl/src/kodi-21.0/xbmc/platform/posix -isystem /home/carl/src/kodi_build/build/include -isystem /usr/include/dbus-1.0 -isystem /usr/lib64/dbus-1.0/include -isystem /usr/include/pipewire-0.3 -isystem /usr/include/spa-0.2 -isystem /usr/include/python3.9 -isystem /usr/include/samba-4.0 -isystem /usr/include/libxml2 -isystem /usr/include/ffmpeg -isystem /home/carl/src/kodi_build/build/cores/RetroPlayer/messages -isystem /usr/include/freetype2 -isystem /usr/include/fribidi -isystem /home/carl/src/kodi-21.0/xbmc/contrib -isystem /usr/include/lzo -isystem /usr/include/libdrm -Wall -Wdouble-promotion -Wmissing-field-initializers -Wsign-compare -Wextra -Wno-unused-parameter -Wnon-virtual-dtor -O3 -DNDEBUG -DTARGET_POSIX -DTARGET_LINUX -D_GNU_SOURCE -DHAVE_LINUX_UDMABUF=1 -DHAVE_LINUX_DMA_HEAP=1 -DHAVE_LINUX_DMA_BUF=1 -DHAVE_MKOSTEMP=1 -DHAVE_LINUX_MEMFD=1 -DHAVE_STATX=1 -DHAVE_SSE=1 -DHAVE_SSE2=1 -DHAVE_SSE3=1 -DHAVE_SSSE3=1 -DHAVE_SSE4_1=1 -D__STDC_CONSTANT_MACROS -D_FILE_OFFSET_BITS=64 -DHAS_POSIX_NETWORK -DHAS_LINUX_NETWORK -DHAS_BUILTIN_SYNC_ADD_AND_FETCH=1 -DHAS_BUILTIN_SYNC_SUB_AND_FETCH=1 -DHAS_BUILTIN_SYNC_VAL_COMPARE_AND_SWAP=1 -DHAVE_INOTIFY=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_INTTYPES_H=1 -DHAS_ALSA=1 -DHAS_AVAHI=1 -DHAS_ZEROCONF=1 -DHAVE_LIBBLURAY=1 -DHAVE_LIBBLURAY_BDJ=1 -DHAVE_LIBCEC=1 -DHAS_DBUS=1 -DHAS_ISO9660PP=1 -DHAVE_LCMS2=1 -DCMS_NO_REGISTER_KEYWORD=1 -DHAS_LIRC=1 -DHAS_WEB_SERVER=1 -DHAS_WEB_INTERFACE=1 -DHAS_PIPEWIRE=1 -DHAS_AIRPLAY=1 -DHAS_PULSEAUDIO=1 -DHAS_PYTHON=1 -DHAS_FILESYSTEM_SMB=1 -DHAVE_LIBUDEV=1 -DHAS_UDFREAD=1 -DHAVE_LIBXSLT=1 -DHAVE_LIBVA=1 -DHAS_GLX=1 -DHAVE_LIBVDPAU=1 -DHAVE_NEW_CROSSGUID -DFFMPEG_VER_SHA=\"5.0.0\" -DSPDLOG_FMT_EXTERNAL -DSPDLOG_DEBUG_ON -DSPDLOG_NO_ATOMIC_LEVELS -DSPDLOG_ENABLE_PATTERN_PADDING -DSPDLOG_COMPILED_LIB -DHAS_EGL=1 -DHAVE_EGLEXTANGLE=1 -DHAVE_X11=1 -DHAVE_LIBXRANDR=1 -DHAVE_HDR_OUTPUT_METADATA=1 -DHAVE_DRM_MODIFIER_NAME=1 -DHAS_GL=1 -DHAS_MYSQL=1 -DHAS_UPNP=1 -DHAS_DVD_DRIVE -DHAS_CDDA_RIPPER -DBIN_INSTALL_PATH=\"/usr/local/lib64/kodi\" -DINSTALL_PATH=\"/usr/local/share/kodi\" -Werror=double-promotion -Werror=missing-field-initializers -Werror=sign-compare -std=c++17 -MD -MT build/cores/paplayer/CMakeFiles/paplayer.dir/VideoPlayerCodec.cpp.o -MF CMakeFiles/paplayer.dir/VideoPlayerCodec.cpp.o.d -o CMakeFiles/paplayer.dir/VideoPlayerCodec.cpp.o -c /home/carl/src/kodi-21.0/xbmc/cores/paplayer/VideoPlayerCodec.cpp
[ 14%] Linking CXX static library paplayer.a
cd /home/carl/src/kodi_build/build/cores/paplayer && /usr/bin/cmake -P CMakeFiles/paplayer.dir/cmake_clean_target.cmake
cd /home/carl/src/kodi_build/build/cores/paplayer && /usr/bin/cmake -E cmake_link_script CMakeFiles/paplayer.dir/link.txt --verbose=1
/usr/bin/ar qc paplayer.a CMakeFiles/paplayer.dir/AudioDecoder.cpp.o CMakeFiles/paplayer.dir/CodecFactory.cpp.o CMakeFiles/paplayer.dir/PAPlayer.cpp.o CMakeFiles/paplayer.dir/VideoPlayerCodec.cpp.o
/usr/bin/ranlib paplayer.a
gmake[2]: Leaving directory '/home/carl/src/kodi_build'
[ 14%] Built target paplayer
gmake[1]: Leaving directory '/home/carl/src/kodi_build'
gmake: *** [Makefile:146: all] Error 2

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should compile cleanly.

## Actual Behavior

compile crashes as above.  It appears that pipewire buffers are being called for, however these weren't added until version 0.3.50 however CentOS Stream 9.1 has 0.3.47.

## Possible Fix

Remove the requirement for pipewire buffers if <.50.

If I do not compile pipewire won't Kodi not have audio?

### To Reproduce

1. configure
2. compile
3. fail

### Debuglog

The debuglog can be found here:
A debuglog can be found where?

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:  CentOS Stream 9.1
 - Kodi version: 21.0

This issue was closed before.  If mods don't want to deal with it I am never submitting another bug again.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please use the forum for support.

https://forum.kodi.tv/

**Comment by quantum77** [comment]
This is not a support question.  It's a bug in the source.  

The forum is in no technical position to resolve this.

**Comment by lrusak** [comment]
fixed in #22944. Sorry for the runaround.
