### ISSUE TITLE
Kodi 20 in Windows 10 hangs until I kill it if in a directory I have a video file with an unusual name

### ISSUE THREAD

**Issue by mborus** [xbmc/xbmc#22948]
### Kodi hangs when navigating inside a folder with an unusual filename
Here is a clear and concise description of what the problem is:

I found a way to consistently, reproducably get Kodi to hang on Windows 10 Pro 64 bit.

From the "video" "files" selection I enter a folder with a few dozen video files.
One file is called "Dinner for one Bodo Maria ＂Well, i´ll do my very best!＂ [lqePMGLsxkA].webm"
(It's this one: https://www.youtube.com/watch?v=lqePMGLsxkA downloaded with yt-dlp.
The file itself is not it problem, it's the file's name (see details later))

As soon as I navigate to that file by repeated pressing of the arrow down in the video list to go to it, Kodi hangs and needs to get killed. (It also hangs if I scroll with a mouse or similar)

I have done some tests:
1. Rename the file to "file1.webm" -> Kodi does not hang
2. Rename the file to "Dinner for one Bodo Maria Well, i´ll do my very best! [lqePMGLsxkA].webm" -> Kodi does not hang
3. Make a new, empty folder and move the file in there with the original name. When I enter the folder, Kodi hangs. 
4. Since it's a "webm" file, try other file extensions: 
- Move a mp4 video in the empty Folder
- Go into the Folder
- Play the file (it plays), than leave the folder,
- Rename the file to "Dinner for one Bodo Maria ＂Well, i´ll do my very best!＂ [lqePMGLsxkA].mp4"
- Enter the folder again -> Kodi hangs.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should dislay a video preview image and not hang. Kodi should allow me to play the video.

## Actual Behavior

Kodi hangs and needs to get killed.

## Possible Fix

As the filename seem to be the problem, here's a Python encoding of the filename

    t = """Dinner for one Bodo Maria ＂Well, i´ll do my very best!＂ [lqePMGLsxkA].webm"""
    t.encode('utf-8')

    b'Dinner for one Bodo Maria \xef\xbc\x82Well, i\xc2\xb4ll do my very best!\xef\xbc\x82 [lqePMGLsxkA].webm'

As possible fix is to check the handling of file names on windows and to catch exceptions that are related to file names when trying to display a preview image. Maybe first check if the file exists and is accessable.

### To Reproduce

On windows, in a folder with one mp4 video,
rename it to 
 
   "Dinner for one Bodo Maria ＂Well, i´ll do my very best!＂ [lqePMGLsxkA].webm"
   (utf8 representation:     b'Dinner for one Bodo Maria \xef\xbc\x82Well, i\xc2\xb4ll do my very best!\xef\xbc\x82 [lqePMGLsxkA].webm')
   Move to the file from the "Videos" "files" section
   Watch Kodi hang

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/vocakaxogo.kodi

See line 378

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
20.0 (downloaded today)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Surely this is already fixed by https://github.com/xbmc/xbmc/pull/22658 and included in v20.1

Please test latest Nexus nightly to confirm:  
https://mirrors.kodi.tv/nightlies/windows/win64/Nexus/KodiSetup-20230307-644cf0d7-Nexus-x64.exe

**Comment by mborus** [comment]
Tested (The build reports as 20.0) and there's no freeze and you can see the missing unicode chars.

Thanks for the quick reply.
