### ISSUE TITLE
Black screen with HEVC/H.264 video playback by using inputstream.adaptive with LineageOS20 (Kodi 21 Omega)

### ISSUE THREAD

**Issue by werimail** [xbmc/xbmc#22954]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'am using Kodi 21 (Omega) with LineageOS running on Raspberry Pi 400 with Android 13.0.0. When I Start using some Addons (Amazon Prime Video, RTL Plus V3.) the widevine encryption with Inputstream starts playing the videos but there is no picture only Black screen.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Addons which use widevine output a picture

## Actual Behavior
When I Start using Addons the widevine encryption the Inputstream Adaptive on Kodi 19.3 with LineageOS the video starts without a picture on the screen (only Black screen, but the video plays)

### To Reproduce

1. Start Kodi-Addon (Amazon Prime Video) for encrypted videos via inputstream adaptive plugin
2. Start playing a video

### Debuglog
The debuglog can be found here:

[kodi_lineage_ia.log](https://github.com/xbmc/xbmc/files/10942357/kodi_lineage_ia.log)

[kodi_lineage_h264.log](https://github.com/xbmc/xbmc/files/10945169/kodi_lineage_h264.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Screenshot_20230310-195854_Kodinerds Omega](https://user-images.githubusercontent.com/88481706/224404343-ac969fa6-c974-4a3a-9196-55a7d34d5038.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LineageOS 20 based on Android for Raspberry Pi 400 
 - Kodi version: 21 (Omega)

Greetings Weri

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Do h264/hevc files play at all?

I've never seen anyone use android on rpi4 with Kodi before. I imagine hw decoding would be an issue unless they have v4l2 support.

**Comment by werimail** [comment]
Yes they do. That was fixed with (https://github.com/xbmc/xbmc/pull/21421). Other Addons like DAZN for example work fine. Only Amazon Prime Video and RTL Plus V3 makes trouble.

**Comment by CastagnaIT** [comment]
i dont think you can play it
fwik drm HEVC stream requires hardware decoding and you cannot have it with your custom rom
so black screen is correct

**Comment by werimail** [comment]
Hello @CastagnaIT nice to hear from you again. The new LineageOS 20 supports hardware decoding. This is also shown in the OSD. However, this problem has already occurred with H.264 coding. So with the Amazon Prime addon, it makes no difference whether HEVC or H.264, the problem is the same for both. I suspect there is another problem in connection with the input stream. Adaptive Addon and the Lineage Custom Rom

**Comment by werimail** [comment]
Here the changlog for the LineageOS 20:
H.265 hardware video decoding, H.264 hardware video decoding and encoding
FFmpeg 5.1.2 (thanks to John Cox for Raspberry Pi hw codecs support and Android-x86 for AOSP build patches)
implement codec2 plugin to integrate FFmpeg into Android multimedia framework (thanks to Michael Goffioul)
FFmpeg hevc_v4l2request hwaccel H.265 hw decoding (default), h264_v4l2m2m H.264 hw decoding (optional)
v4l2_codec2 H.264 hardware video decoding and encoding (default)
FFmpeg software decoders support
update to Mesa 22.3.5

**Comment by CastagnaIT** [comment]
inputstream adaptive use internal decoder not ffmpeg
anyway your widevine is marked L3 and also dont having a widevine licensed product can make problems for full hd content
you can try to play 540p video resolution to try to see if it is played

**Comment by werimail** [comment]
I already had the idea of ​​setting the resolution to 540p, unfortunately the error is the same...I would create a debug log again with H.264 and 540p and post it here, maybe you can still see something there. Thank you and greetings Weri

**Comment by werimail** [comment]
So @Cast, I have now added a debug log and a screenshot for an H.264 video with 540p in the error description. If more information is required please let us know Greetings Weri

**Comment by CastagnaIT** [comment]
same errors on the new log
there are a lot of `EGL_BAD_CONFIG` errors that should not be here this depends on your rom

for these
```
2023-03-10 14:02:44.889 T:20578   error <general>: CDVDAudioCodecAndroidMediaCodec::Decode ExceptionCheck
2023-03-10 14:02:44.898 T:20574   error <general>: CDVDVideoCodecAndroidMediaCodec::AddData error
2023-03-10 14:02:44.911 T:20578   error <general>: CDVDAudioCodecAndroidMediaCodec::Decode ExceptionCheck
2023-03-10 14:02:44.924 T:20574   error <general>: CDVDVideoCodecAndroidMediaCodec::AddData error
```
having the logcat is possible read the related android errors
where maybe will be possible try understand something
if not suspect that these custom decoders like `c2.ffmpeg.h264.decoder` dont works well

**Comment by joseluismarti** [comment]
As @CastagnaIT indicates, you would have to look at the system logcat to see the exception descriptions.

Enable ADB debugging on the device and run the following commands:
```
adb connect IP; adb logcat -v color
```
When playing a video, look in logcat for the exception with the text `MediaDrm` or similar.

**Comment by werimail** [comment]
Hi @joseluismarti, hi @CastagnaIT I ran `adb logcat -v color` command. I saved the result in the following file:
[kodi_lineage_adb.log](https://github.com/xbmc/xbmc/files/10948888/kodi_lineage_adb.log)

**Comment by joseluismarti** [comment]
```
DrmUtils: found IDrmFactory. Instance name:[android.hardware.drm.IDrmFactory/clearkey]
DrmUtils: found IDrmFactory. Instance name:[android.hardware.drm.IDrmFactory/widevine]
hwservicemanager: getTransport: Cannot find entry android.hardware.drm@1.0::ICryptoFactory/default in either framework or device VINTF manifest.
CryptoHalHidl: Failed to find any crypto factories
```
It's not a Kodi issue, something is missing in LineageOS image, maybe someone on the [forum](https://forums.raspberrypi.com/viewforum.php?f=73) can help.

**Comment by werimail** [comment]
Hi, I asked about the error in the mentioned forum and got the following answer: 
`I can assure you there is nothing missing in my builds in this regard.

I have switched to using AIDL HALs for Clearkey and WV in my Android 13 builds ([https://github.com/raspberry-vanilla/an ... a600fac137](https://github.com/raspberry-vanilla/android_device_brcm_rpi4/commit/203db632fa2c9202cdf5eed884aa6ca600fac137) & [https://github.com/lineage-rpi/propriet ... 347f8f090a](https://github.com/lineage-rpi/proprietary_vendor_brcm/commit/eb8ebea443921d415ded1a6bbd1c1c347f8f090a)). If Kodi has some problem with this, it's likely broken on every Pixel device with Android 13 as well (AOSP reference for the exact same change: [https://android.googlesource.com/device ... e9d%5E%21/](https://android.googlesource.com/device/google/coral/+/fb4fbb97bd37000e4f35c77c178a0fb36ee9ce9d%5E%21/)). You can test if you can reproduce the same issue with Kodi on LineageOS 19 (Android 12) that still uses HIDL HALs for DRM.`

However, I also have the problem with LineageOS 19 (Android 12). I'm a bit at a loss now and don't really know where the error (Kodi or LineageOS) lies. Greeting Weri

**Comment by werimail** [comment]
The solution for this you can found her: https://github.com/Sandmann79/xbmc/issues/295 (force SD resolution due to VMP)

Greetings Weri
