### ISSUE TITLE
Dims during music visualization

### ISSUE THREAD

**Issue by curtisdr** [xbmc/xbmc#22956]
### Describe the bug
Here is a clear and concise description of what the problem is:

For at least a year or two, through numerous releases, during music visualization the screen will dim after the screensaver timeout.  Doesn't matter what skin, or even that I have Slideshow set as my screensaver (which works when music is not playing).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When the Settings/Interface/Screensaver "Use Visualization When Playing Audio" switch is on, the screen should not dim during music play.  This worked properly for many years.

## Actual Behavior

Screen dims after 1 minute (my screensaver selected timeout period)

## Possible Fix

Have the Settings switch work again.

### To Reproduce

1.  Set screensaver timeout to 1 minute
2. Play a song and activate music visualization (tab key)
3. Wait one minute for screen to dim

### Debuglog

The debuglog can be found here:

https://pastebin.com/raw/YApdaiTT

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x ] Windows 7x64
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
kodi-20.0-Nexus-x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
I tried to reproduce this on macOS and could not get a similar behaviour, seems to work for me.
Might be platform specific.
