### ISSUE TITLE
Kodi 20.1 can't play low resolution .rmvb file.

### ISSUE THREAD

**Issue by Casperlet** [xbmc/xbmc#22978]
### Describe the bug
I have some low resolution .rmvb files. The Kodi recognizes them, but can't play the video except the audio. I tried to substitute with the player of my projector, it can play them.

## Expected Behavior
The .rmvb files should be played well.

## Actual Behavior
I only heard the audio, but no video is shown.

## Possible Fix
I suppose the de-codec plugin or addon doesn't support some of the .rmvb files.

### Debuglog
It's a projector. I don't know where I can find the log files of Kodi. I copied the format information of the .rmvb files from PotPlayer, then I find that all of them are low resolution videos.

#### Updated
the log: [kodi.log](https://github.com/xbmc/xbmc/files/10989522/kodi.log)

In the log, I played 3 vidoes. 
- the 1st one begins at 2023-03-16 18:13:39.426
- the 2nd is 2023-03-16 18:14:23.470
- the 3rd is 2023-03-16 18:14:44.278

Translation:
|Chinese|English|
|---------|--------|
|视频|Video|
|音频|Audio|
|编码|Codec|
|输入|Input|
|输出|Output|
|尺寸|Size|
|帧率|Frame Ratio|

-------------------
[视频信息]
  视频编码： RV40 - 内置 FFmpeg 解码器(rv40)
  输入格式： RV40(12 bits)
  输入尺寸： 1024 × 576(1.78:1)
  输出格式： NV12(12 bits)
  输出尺寸： 1024 × 576(1.78:1)
  帧率： 23.976
  BitRate: 1120.57 kbps

[音频信息]
  音频编码： RealAudio COOK(0x2004) - 内置 FFmpeg 解码器(cook)
  采样率： 44100 -> 44100 Hz
  位率： 16 -> 16 位
  声道数： 2 -> 2 声道
  Bitrate: 64 kbps

-------------------
[视频信息]
  视频编码： RV40 - 内置 FFmpeg 解码器(rv40)
  输入格式： RV40(12 bits)
  输入尺寸： 1024 × 576(1.78:1)
  输出格式： NV12(12 bits)
  输出尺寸： 1024 × 576(1.78:1)
  帧率： 23.976
  BitRate: 861.863 kbps

[音频信息]
  音频编码： RealAudio COOK(0x2004) - 内置 FFmpeg 解码器(cook)
  采样率： 44100 -> 44100 Hz
  位率： 16 -> 16 位
  声道数： 2 -> 2 声道
  Bitrate: 64 kbps

-------------------
[视频信息]
  视频编码： RV40 - 内置 FFmpeg 解码器(rv40)
  输入格式： RV40(12 bits)
  输入尺寸： 816 × 460(1.77:1)
  输出格式： NV12(12 bits)
  输出尺寸： 816 × 460(1.77:1)
  帧率： 23.976
  BitRate: 592.242 kbps

[音频信息]
  音频编码： RealAudio COOK(0x2004) - 内置 FFmpeg 解码器(cook)
  采样率： 44100 -> 44100 Hz
  位率： 16 -> 16 位
  声道数： 2 -> 2 声道
  Bitrate: 64 kbps

-------------------
[视频信息]
  视频编码： RV40 - 内置 FFmpeg 解码器(rv40)
  输入格式： RV40(12 bits)
  输入尺寸： 640 × 272(2.35:1)
  输出格式： NV12(12 bits)
  输出尺寸： 640 × 272(2.35:1)
  帧率： 23.976
  BitRate: 531.55 kbps

[音频信息]
  音频编码： AAC(0xaac0) - 内置 FFmpeg 解码器(aac)
  采样率： 44100 -> 44100 Hz
  位率： 16 -> 16 位
  声道数： 2 -> 2 声道
  Bitrate: 64 kbps

-------------------
[视频信息]
  视频编码： RV40 - 内置 FFmpeg 解码器(rv40)
  输入格式： RV40(12 bits)
  输入尺寸： 1024 × 576(1.78:1)
  输出格式： NV12(12 bits)
  输出尺寸： 1024 × 576(1.78:1)
  帧率： 23.976
  BitRate: 1121.89 kbps

[音频信息]
  音频编码： RealAudio COOK(0x2004) - 内置 FFmpeg 解码器(cook)
  采样率： 44100 -> 44100 Hz
  位率： 16 -> 16 位
  声道数： 2 -> 2 声道
  Bitrate: 64 kbps

-------------------
[视频信息]
  视频编码： RV40 - 内置 FFmpeg 解码器(rv40)
  输入格式： RV40(12 bits)
  输入尺寸： 800 × 336(2.38:1)
  输出格式： NV12(12 bits)
  输出尺寸： 800 × 336(2.38:1)
  帧率： 23.976
  BitRate: 451.583 kbps

[音频信息]
  音频编码： RealAudio COOK(0x2004) - 内置 FFmpeg 解码器(cook)
  采样率： 44100 -> 44100 Hz
  位率： 16 -> 16 位
  声道数： 2 -> 2 声道
  Bitrate: 44 kbps

-------------------
[视频信息]
  视频编码： RV40 - 内置 FFmpeg 解码器(rv40)
  输入格式： RV40(12 bits)
  输入尺寸： 640 × 360(1.78:1)
  输出格式： NV12(12 bits)
  输出尺寸： 640 × 360(1.78:1)
  帧率： 23.976
  BitRate: 487.324 kbps

[音频信息]
  音频编码： RealAudio COOK(0x2004) - 内置 FFmpeg 解码器(cook)
  采样率： 44100 -> 44100 Hz
  位率： 16 -> 16 位
  声道数： 2 -> 2 声道
  Bitrate: 64 kbps

-------------------
[视频信息]
  视频编码： RV40 - 内置 FFmpeg 解码器(rv40)
  输入格式： RV40(12 bits)
  输入尺寸： 720 × 404(1.78:1)
  输出格式： NV12(12 bits)
  输出尺寸： 720 × 404(1.78:1)
  帧率： 23.976
  BitRate: 460.54 kbps

[音频信息]
  音频编码： RealAudio COOK(0x2004) - 内置 FFmpeg 解码器(cook)
  采样率： 44100 -> 44100 Hz
  位率： 16 -> 16 位
  声道数： 2 -> 2 声道
  Bitrate: 64 kbps

-------------------
[视频信息]
  视频编码： RV40 - 内置 FFmpeg 解码器(rv40)
  输入格式： RV40(12 bits)
  输入尺寸： 720 × 404(1.78:1)
  输出格式： NV12(12 bits)
  输出尺寸： 720 × 404(1.78:1)
  帧率： 23.976
  BitRate: 430.945 kbps

[音频信息]
  音频编码： RealAudio COOK(0x2004) - 内置 FFmpeg 解码器(cook)
  采样率： 44100 -> 44100 Hz
  位率： 16 -> 16 位
  声道数： 2 -> 2 声道
  Bitrate: 64 kbps

-------------------
[视频信息]
  视频编码： RV40 - 内置 FFmpeg 解码器(rv40)
  输入格式： RV40(12 bits)
  输入尺寸： 720 × 404(1.78:1)
  输出格式： NV12(12 bits)
  输出尺寸： 720 × 404(1.78:1)
  帧率： 23.976
  BitRate: 429.396 kbps

[音频信息]
  音频编码： RealAudio COOK(0x2004) - 内置 FFmpeg 解码器(cook)
  采样率： 44100 -> 44100 Hz
  位率： 16 -> 16 位
  声道数： 2 -> 2 声道
  Bitrate: 64 kbps

### Your Environment
- CPU: ARMv7 Processor rev 0 (v71)
- GPU: Mali-G31
- OpenGL ES 3.2 v1.r16p0
- Android TV 9.0.0 API level 28 (kernel: Linux 4.9.113)
 - Kodi version: 20.1 (20.1.0) Git: 20230312-289ec664e3

**Comment by enen92** [comment]
Provide a log with debug log enabled (see https://kodi.wiki/view/Log_file/Easy uploading methods -> Add-on Kodi Logfile Uploader)

**Comment by Casperlet** [comment]
I uploaded the log above. My device is a projector, no keyboard and mouse. I find a way to share the its storage and copy  the log. 

In the log, I played 4 videos. All of them can't be played well. I can only heard the audio.

Thanks.

**Comment by Casperlet** [comment]
Does the team get my log in the updated post? 

Thanks.

**Comment by hyp36rmax** [comment]
I have the same issue with 480P content. Audio plays for a few seconds with no image. https://github.com/xbmc/xbmc/issues/23033

**Comment by ctaoist** [comment]
I have the same issue with low resolution video.
```
少年四大名捕01
容器: rm
路径: /volume2/video/tv/少年四大名捕/少年四大名捕01.rmvb
大小: 203 MB

视频
标题: 404p RV40 SDR
编码: RV40
编码标签: RV40
分辨率: 720x404
长宽比: 16:9
隔行扫描: No
帧率: 25
比特率: 564 kbps
位深度: 8 bit
动态范围: SDR
Video range type: SDR
像素格式: yuv420p
参考帧: 1
```

and

```
[SCST]深夜食堂.EP01[856x480][GB][RV10_AAC]
容器: rm
路径: /volume2/video/tv/深夜食堂/深夜食堂/[SCST]深夜食堂.EP01[856x480][GB][RV10_AAC].rmvb
大小: 120 MB

视频
标题: 540p RV40 SDR
编码: RV40
编码标签: RV40
分辨率: 856x480
长宽比: 16:9
隔行扫描: No
帧率: 29.970001
比特率: 595 kbps
位深度: 8 bit
动态范围: SDR
Video range type: SDR
像素格式: yuv420p
参考帧: 1
```

Those video are not played by Kodi.

**Comment by enen92** [comment]
Still an issue with current nightlies?
If so, please provide a sample file. I could not reproduce this in any device.
