### ISSUE TITLE
Kodi [master] - Black screen with gbm/gles and Mesa 23.1.0 on x86_64

### ISSUE THREAD

**Issue by coffeinflash** [xbmc/xbmc#23011]
I don' t know if this is an issue caused by Mesa or kodi. Actually it is not a bug report but just a question of interest ;-)

## Bug report
I am building kodi from git for openSUSE Tumbleweed for my Intel NUC (NUC7PJYH) to run via gbm using gles.
[https://build.opensuse.org/package/show/home:Herbster0815:HTPC/kodi-gbm](url)

The build options are:
%cmake \
    -DVERBOSE=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_EVENTCLIENTS=ON \
    -DENABLE_INTERNAL_CROSSGUID=OFF \
    -DENABLE_INTERNAL_CDIO=OFF \
    -DENABLE_INTERNAL_FLATBUFFERS=OFF \
    -DENABLE_INTERNAL_FMT=OFF \
    -DENABLE_INTERNAL_FSTRCMP=OFF \
    -DENABLE_INTERNAL_RapidJSON=OFF \
    -DENABLE_INTERNAL_SPDLOG=OFF \
    -DENABLE_INTERNAL_DAV1D=OFF \
    -DENABLE_INTERNAL_UDFREAD=OFF \
    -DENABLE_INTERNAL_GTEST=OFF \
    -DENABLE_INTERNAL_KISSFFT=OFF \
    -DENABLE_AIRTUNES=OFF \
    -DENABLE_DVDCSS=OFF \
    -DENABLE_PULSEAUDIO=OFF \
    -DENABLE_PIPEWIRE=OFF \
    -DENABLE_MYSQLCLIENT=OFF \
    -DENABLE_MARIADBCLIENT=ON \
    -DENABLE_GOLD=OFF \
    -DENABLE_MOLD=OFF \
    -DCORE_SYSTEM_NAME=linux \
    -DAPP_RENDER_SYSTEM=gles \
    -DCORE_PLATFORM_NAME=gbm \
    -DENABLE_INTERNAL_FFMPEG=ON \
    -DFFMPEG_URL="%{SOURCE9}" \
    -DENABLE_INTERNAL_CEC=OFF \
    -DENABLE_INTERNAL_NFS=OFF \
    -DENABLE_INTERNAL_PCRE=OFF \
    -DENABLE_INTERNAL_TAGLIB=OFF \
%ifarch x86_64
    -DENABLE_OPENGLES=ON \
    -DENABLE_VAAPI=ON \
    -DENABLE_VDPAU=ON \
%endif
%ifarch aarch64
    -DENABLE_VAAPI=OFF \
    -DENABLE_VDPAU=OFF \
    -DENABLE_OPENGL=OFF \
    -DENABLE_OPENGLES=ON \
    -DENABLE_EGL=ON \
%endif
    -DUSE_LTO=OFF \
    -DBUILD_SHARED_LIBS=1 \
    -DENABLE_TESTING=OFF \
    -DENABLE_DEBUGFISSION=OFF

With Mesa 23.0.0 everything runs fine including HDR :-)

But with Mesa 23.1.0 - also build from git - I get a black screen instead of the GUI although kodi is up and running.
So I turned on Mesa debugging and got the following in the logfile:
Mesa: error: GL_INVALID_VALUE in glTexImage2D(internalFormat=GL_BGRA)

## Expected Behavior
Kodi should show the GUI after start.

## Actual Behavior
Kodi is running but shows a black screen instead of the GUI

### To Reproduce
Install the rpms from my repository on Tumbleweed including the dev version of Mesa 23.1.0 and restart kodi --> black screen
Switch back to Mesa 23.0.0 and restart kodi --> GUI is shown

### Debuglog
The debuglog can be found here:  [https://paste.opensuse.org/pastes/abc360c4ee2a](url)

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: openSUSE Tumbleweed
 - Kodi version: 21.0-ALPHA1 (20.90.101) Git:20230319-0d43af8c6

**Comment by sarbes** [comment]
Skimming through our code, I can't find any instance where we might use GL_BGRA/GL_BGRA_EXT with differing format/internalformat. GL_BGRA_EXT is a valid internalformat, as far as I see.

Could you test GLES on a desktop system?

**Comment by coffeinflash** [comment]
To be honest I don't know how to switch to GLES on my desktop system - also running Tumbleweed.
I am running X there. 
Is there some environment variable or similar?

**Comment by coffeinflash** [comment]
I switched my PI3 to Tumbleweed running on aarch64. I ran into the same issue. 
So the problem seems to be mesa related and arch independent.
