### ISSUE TITLE
Feature Request - Secondary Preferred Audio Language,

### ISSUE THREAD

**Issue by TwilightMercy** [xbmc/xbmc#23023]
Hi,

I play movies/shows videos with multiple languages tracks. 
Preferred audio language is set on English, and working. 

But for videos without English audio tracks (for example: Anime), they have for example - Japanese and Russian. And I want to automatically choose Japanese. 

is it possible to add an option to configure secondary preferred audio language, for cases first audio language doesn’t exist?

**Comment by fuzzard** [comment]
We do not use Github to track feature requests.

Feature requests can be made on the forums at https://forum.kodi.tv/forumdisplay.php?fid=9
