### ISSUE TITLE
KODI XBOX No Longer plays 480P content

### ISSUE THREAD

**Issue by hyp36rmax** [xbmc/xbmc#23033]
### Describe the bug
Here is a clear and concise description of what the problem is:

Latest version of KODI on Xbox no longer plays 480P content. Tried on multiple MS Xbox Series X (2) and a Series S with the same result with multiple 480P content files.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Loading 480P content will play

## Actual Behavior

Loading 480P content will play audio for 15 seconds with no video and freeze.  Requires going back to the Xbox Menu and force quitting KODI

### To Reproduce

1. Browse to video files
2. Load 480P content
3.

### Debuglog

The debuglog can be found here: How do I get this from the XBOX UWP version?

FOUND IT! https://paste.kodi.tv/qepenobuta

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [X ] Windows UWP

 - Operating system version/name:
 - Kodi version: XBOX UWP Build 20.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
You'll need to provide a debug log so we can see what happens.
Might also be worth showing a mediainfo output of one of the files just so we can get the whole picture.

**Comment by hyp36rmax** [comment]
> You'll need to provide a debug log so we can see what happens. Might also be worth showing a mediainfo output of one of the files just so we can get the whole picture.

How do i acquire that file from MS UWP XBOX? PC NP.

**Comment by fuzzard** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by hyp36rmax** [comment]
> https://kodi.wiki/view/Log_file/Easy

Thank  you! Managed to get it with your instructions!! https://paste.kodi.tv/qepenobuta

**Comment by KarellenX** [comment]
@hyp36rmax 

You need to enable debug mode. And you also need to try to play the 480p content so it is captured in the log.

**Comment by elfez** [comment]
I'm also having issues with video playback on XBox Series X, with similar symptoms, though in my case it seems to affect all videos. I have two other Kodi instances (kodi 20.1 on Windows 11 and kodi 19.x on Linux) which do not display this issue. All three are fetching data from the same NFS server. I'll try and capture a debug log and upload it.

**Comment by elfez** [comment]
I reproduced this on a 480p movie, but a 1080p movie worked fine. This log should capture everything up to where I force closed kodi https://paste.kodi.tv/ramelukuqo

**Comment by sarbes** [comment]
Try the workaround in https://github.com/xbmc/xbmc/pull/23004.

**Comment by elfez** [comment]
> Try the workaround in #23004.

Can confirm setting render method to DXVA seems to work around the issue. Thanks for the pointer.

(For reference the setting is Settings -> Player -> Video -> Render Method).

**Comment by thexai** [comment]
```
warning <general>: DXVA: H264 SD interlaced has issues on AMD graphics hardware. DXVA will not be used.
...
debug <general>: CWinRenderer::SelectRenderer: requested render method: 0
debug <general>: CWinRenderer::SelectRenderer: selected render method: Pixel Shaders
```

Yes, debug log confirms is same issue fixed in https://github.com/xbmc/xbmc/pull/23004, but will have no effect until v20.2 are released. 

Anyway meanwhile workaround of change Renderer method from AUTO to DXVA should work with all videos.

Pixel Shaders only is used when is manually selected or when is in Auto but is no used HW video decoding (DXVA2).

Default paths are:

1. DXVA2 decoding (HW) ---> DXVA renderer 
2. FFmpeg SW decoding ---> Pixel Shaders renderer

With setting changed to DXVA:

1. DXVA2 decoding (HW) ---> DXVA renderer 
2. FFmpeg SW decoding ---> DXVA renderer

**Comment by hyp36rmax** [comment]
Thank you everyone!

**Comment by enen92** [comment]
@thexai I think you linked this to an already merged pull request (so it won't be closed). Can this be closed then?
