### ISSUE TITLE
Kodi ignore local artworks with refresh "from internet" 

### ISSUE THREAD

**Issue by Nanomani** [xbmc/xbmc#23044]
### Describe the bug

When I Scrape a new movie without file nfo and with his Artworks on local, Kodi use by default the local artworks.
When I refresh a movie information with choice "from internet" local artworks are ignored.

## Expected Behavior
I expect that Kodi use local artworks

## Actual Behavior
Local artworks are ignored.

## Possible Fix
Only a workaround : 
1 - Delete the movie from the library
2 - Scrape it again

### To Reproduce
1. Scrape a new movie with local Artworks (poster, fanart) 
2. Actualise this movie from DialogVideoInfo with choice "From Internet" 

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/yukunobebu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

![VNQs1Ui](https://user-images.githubusercontent.com/3939543/227340819-e812c286-8791-4038-8b02-a14b9528c579.jpg)

![ERKONuX](https://user-images.githubusercontent.com/3939543/227340919-5e397c9f-61ac-4caa-b872-9ff80d629b0f.jpg)

![aENL2tk](https://user-images.githubusercontent.com/3939543/227340952-c3352d42-840d-45aa-b50f-ba71ecd2c8be.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Linux
 - [X] Windows

 - Operating system version/name:
 - Kodi version: 20.1 x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
When using the Refresh button from the Information screen and choose Yes to "Ignore and refresh from internet", as shown in the above images, not only is the nfo file ignored, but also the local artwork and new artwork is dowloaded from the internet.

I don't know the original intention of the Refresh option- was it meant to exclude only nfo files, or also exclude local artwork?

I feel that users take extra steps to curate their artwork, so I don't think ignoring it should be the way to go. The Music Library does not ignore the local artwork when using Refresh, and IIRC @DaveTBlake picked up on this issue a few years ago.

**Comment by arnova** [comment]
> When using the Refresh button from the Information screen and choose Yes to "Ignore and refresh from internet", as shown in the above images, not only is the nfo file ignored, but also the local artwork and new artwork is dowloaded from the internet.
> 
> I don't know the original intention of the Refresh option- was it meant to ignore only nfo files, or also ignore local artwork? But from my limited knowledge, it seems artwork wasn't meant to update... [3e61e9b](https://github.com/xbmc/xbmc/commit/3e61e9b0a79054e685712426509155cee8f83a1f)
> 
> I feel that users take extra steps to curate their artwork, so I don't think ignoring it should be the way to go. The Music Library does not ignore the local artwork when using Refresh, and IIRC @DaveTBlake picked up on this issue a few years ago.
> 
> If someone does look to fix this issue, at the same time could you fix the "Ignore and refresh from internet" pop-up dialogue which pops up even when there is no local information available. Maybe something not working here... [afd5996](https://github.com/xbmc/xbmc/commit/afd5996a00f4cbbc481a056ae350f0334eeb9480)

The original intention is that with refreshing, one has the option to either refresh the local nfo/artwork (by choosing no) or overrule the local nfo/artwork and refresh with info from the internet. This way users have both options, so I don't see what the problem is.....

**Comment by Nanomani** [comment]
> 
> The original intention is that with refreshing, one has the option to either refresh the local nfo/artwork (by choosing no) or overrule the local nfo/artwork and refresh with info from the internet. This way users have both options, so I don't see what the problem is.....

IMHO all is not so black and white "All local" or "all from internet". 

Refresh "from local" without nfo file use internet for information. Right ? 
We may have many reasons to refresh info from the internet and want to keep our local Artworks.

having the ability to distinguish between artwork and information would really be a step forward

Add a setting "Prefer local Art" in Settings/media => Videos => Artwork will be a real improvement 
without break the historical logic.

i hope i am understandable...
(Sorry for my english)

**Comment by arnova** [comment]
Ok, I understand what you're saying but honestly I really think this is a niche feature. Anyway, it's not a bug but by design so I consider this a feature request so please take it to the forum for further discussion.

**Comment by KarellenX** [comment]
Thanks @arnova for the feedback. As I said in my post, I wasn't sure the original intention. But I tend to agree with the OP, metadata may be updated for a variety of reasons - ratings especially come to mind, as well as the creation of movie sets when a sequel is announced. But artwork tends to be a bit more personal. It is picked and tends to remain.

But understand the feature request aspect.

Do you have a view on the erroneous pop-up dialogue even when there is no local info?

**Comment by Nanomani** [comment]
OK, no problem. I'm going to a feature request.
Anyway thank you all for your replies.

**Comment by arnova** [comment]
> Do you have a view on the erroneous pop-up dialogue even when there is no local info?

Not sure what you mean. You mean that it asks whether to update from the internet or not?

**Comment by Nanomani** [comment]
> > Do you have a view on the erroneous pop-up dialogue even when there is no local info?
> 
> Not sure what you mean. You mean that it asks whether to update from the internet or not?

You can have no local Artwork and no file .nfo only the file video. 
But In all case when you click on button refresh Kodi said "Locally stored information found". Igonre and refresh from Internet ?"

![2023-03-27_091845](https://user-images.githubusercontent.com/3939543/227868566-b54c3890-f739-405b-8fab-de8364b51a4f.jpg)

![2023-03-27_091746](https://user-images.githubusercontent.com/3939543/227868327-ebe1a977-73a0-4fcc-9742-e8f7ba72f22e.jpg)

**Comment by arnova** [comment]
Oh strange, that obviously shouldn't happen.

**Comment by arnova** [comment]
> @arnova as @Nanomani stated. Its been mentioned on the forum regularly as it causes confusion for users. Here is an example post... https://forum.kodi.tv/showthread.php?tid=359334
> 
> Bug report here... #22637

I suspect that issue got introduced with the refactoring that @notspiff  did in this area a few years ago. More specifically I think the error is in this line: https://github.com/xbmc/xbmc/blob/c06f56dd5a5f4d62dac64ed69d7119be307b7902/xbmc/video/jobs/VideoLibraryRefreshingJob.cpp#L141

Not sure how to properly fix this btw since I don't know the code very well. Perhaps @notspiff has an idea.

**Comment by KarellenX** [comment]
Thanks @arnova 

Hopefully notspiff has some time to check it out.
