### ISSUE TITLE
Kodi Not Correctly Responding to Google TV remote app.

### ISSUE THREAD

**Issue by GovindKrishnan** [xbmc/xbmc#23057]
### Describe the bug
Here is a clear and concise description of what the problem is:

After the last update the Cody app on Google TV is considering back button click on TV remote app as OK button and vice versa affecting navigation. So basically clicking back on Google TV remote App now takes you forward.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The back button click should be treated as intended and take you back from the stream and the okay button press should take you forward.

## Actual Behavior

Pressing okay button on Google TV remote now takes you back and the back button press will take you forward.

### To Reproduce

1. Open Kodi on Google TV OS
2. Try controlling it with the official Google TV app on Android 
3. Notice the mismatching of back and ok buttons.

### Debuglog

The debuglog can be found here:
Unable to generate as on TV.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Google TV on Android 12
 - Kodi version: 20.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
> The debuglog can be found here:
Unable to generate as on TV.

Then we are unable to diagnose the issue. Please attach a debug log which entails a sample of the button presses, or we will close the issue.

**Comment by DaVukovic** [comment]
Just to mention it. You are totally able to create a debuglog even with Kodi installed on a TV. 

Simply enable debug logging at the Kodi settings, reproduce your issue  and then use the "Kodi Log Uploader" add-on to upload the log. After uploading share the link to it.

**Comment by sarbes** [comment]
No response :(. 

Closing.
