### ISSUE TITLE
Firstrun Plugin Initialization for PVRs Doesn't Make Sense

### ISSUE THREAD

**Issue by stvhay** [xbmc/xbmc#23075]
### Description

I am packaging Kodi and am forced to make a decision between two poor UX possibilities. One, not initializing plugins on first run, or, two, doing so and forcing the user to repeatedly say "no" to every PVR plugin that Kodi offers (the count is currently 25 plugins), or if they have a PVR, n-1 (24) plugins. 

I think this is a severe enough UX issue to be considered a bug.

## Expected Behavior

Since it is very likely that the user has only 0 or 1 PVRs, present the user a choice of which PVR plugin (if any) they which to initialize.

## Actual Behavior

The user is presented plugins sequentially and must select "No" 24 or 25 times the first time they run Kodi.

## Possible Fix

All plugins are currently given a category based on a naming convention where text before the dot (.) in the name indicates a category (i.e. "pvr"). I believe that the userdata initialization logic for Kodi should be aware of this category, and for pvr plugins, implement "select" logic for initialization vs. going through every single plugin one at a time in sequence. In other words, users should be presented with a list of pvr plugins and they can select 1 or 0 to enable. Someone using more than one pvr for some reason can always go into the menu and enable it--I think this is very much a corner case.

### To Reproduce

1. Have the pvr plugins built and available.
2. Nuke the userdata
3. Run Kodi

### Debuglog

This issue does not create any abnormal logs.

N/A

### Screenshots 

N/A

## Additional context or screenshots (if appropriate)

From my perspective, I am presented with a tough choice. I either pass on this UX bug--the benefit being the user will hopefully enable some of the other useful and fun binary plugins that are available.  My other option is to disable initialization and the user now has to go seek out these plugins to get them enabled (particularly the screensavers and visualization plugins)

### Your Environment

Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Buildroot
 
 - Kodi version: 20.1

**Comment by enen92** [comment]
Please use the forum for feature requests. We only use GH issues to track actual bugs.
