### ISSUE TITLE
AV1 sample stream make kodi 21 crash on stop

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#23080]
### Describe the bug
Here is a clear and concise description of what the problem is:

Im testing ISAdaptive and i found this AV1 sample stream make crash kodi

TEST STRM: [DASH_AV1_OPUS_codec.strm.txt](https://github.com/xbmc/xbmc/files/11114293/DASH_AV1_OPUS_codec.strm.txt)

the problem seem to be around the
`CDVDDemuxClient::DisposeStreams`
to some shared ptr's

i tried investigate but im not able to find the root of cause
the crash do not happen on Kodi 20.1 so seem to be a recent regression

## Possible Fix

no idea

### To Reproduce

1. open the STRM above
2. press stop after playback started
3. crash

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/egadizusuj.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

following error is a new log that i introduced when there is no extradata sent to vp (that maybe was better print as "warning" log type)
`2023-03-30 19:22:22.621 T:16668   error <general>: CVideoPlayerVideo::OpenStream: Codec id 226 require extradata.`
and i think its the cause of the following warning
`2023-03-30 19:22:22.621 T:16668 warning <general>: CVideoPlayer::OpenStream - Unsupported stream 1001. Stream disabled.`
but for this use case seem kodi parse the missing extradata from the stream some line above
`2023-03-30 19:22:23.386 T:16668   debug <general>: GetPacketExtradata: fetching extradata, extradata_size(13)`
so imo this should be not related to the problem
similar thing is printed to Kodi 20.1 where there is no crash

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Kodi 21 master branch

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by joseluismarti** [comment]
I tried it on Android and it exits Kodi when play the stream.

It seems that initially does not get the extradata and then disables the video stream. 

As proof, if this check is commented the stream plays fine:
https://github.com/xbmc/xbmc/blob/0a989c4ce6f08769427b30dd3fc3dfd9d90ac49e/xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp#L106-L106

**Comment by CastagnaIT** [comment]
@joseluismarti that check was already existing its not that the problem

i think i found the root problem

this commit has reworked extradata variable with uniqueptr https://github.com/xbmc/xbmc/commit/418b59bb90c2183320fd07289d51f19981562a8e
and i can see that now we use a standard uniqueptr for extradata variable

but from PR #21248 the commit https://github.com/xbmc/xbmc/commit/0a10e05700dfd12b7f5d720588b993089ea33be4
have introduced `GetPacketExtradata` method
that method use `av_malloc` to allocate extradata memory,
and for this use case the DVDDemuxClient.cpp try to move that memory to the uniqueptr that cause the problem,

the uniqueptr is not able to deallocate the memory allocated with `av_malloc`,
that suggest should be used ffmpeg `av_free` or something similar to works

if i try replace this line:
https://github.com/xbmc/xbmc/commit/0a10e05700dfd12b7f5d720588b993089ea33be4#diff-c9a0106744028e04352aa6c0aaf652e47602baf73fadefe5e2af5d079f15f9adR235

with: `extraData = new uint8_t [retExtraDataSize + AV_INPUT_BUFFER_PADDING_SIZE];`

fix the problem and the uniqueptr is deallocated correctly
but here looks like there is a bit of design mess and both allocations methods cannot coexists
and im not sure what to do

**Comment by fritsch** [comment]
Don't do that. Wrapping a C-API and using "nice" C++ stuff is one thing, but when av_free is needed, this can be introduced into a customer destructor. Cause Keep in mind av_malloc has more guarantees besides additional padding. Key point: alignment. av_malloc guarantees that whoever access those allocated memory bits can do so without risk (gpus, cpu, intrinsics, etc.).

The code is not equal to av_malloc version of it.

Please properly use the custom deleter with av_free or remote the unique_ptr. Our key library is C and we need to keep this in mind - wishful thinking for unique_ptr won't solve that.

**Comment by fritsch** [comment]
I meant Deleter, btw. that should work, if av_free or a wrapper to it can be specified. This is btw. also the only way to stay compatibel to what ffmpeg does. Duplicating their allocations in our code makes zero sense ... as we don't track their changes.

**Comment by CastagnaIT** [comment]
i have not do nothing for now just a test to understand
i will make a try as suggested

**Comment by CastagnaIT** [comment]
i tried add this

```diff
diff --git a/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemux.h b/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemux.h
index aeb6839177..9dd1ad34da 100644
--- a/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemux.h
+++ b/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemux.h
@@ -106,7 +106,20 @@ public:
 
   int iDuration; // in mseconds
   void* pPrivate; // private pointer for the demuxer
-  std::unique_ptr<uint8_t[]> ExtraData; // extra data for codec to use
+
+  struct ExtraDataDeleter
+  {
+    void operator()(void* p) const { av_free(p); }
+  };
+
+  typedef std::unique_ptr<void*, ExtraDataDeleter> ExtraDataPtr;
+
+  static ExtraDataPtr MakeExtraDataUniquePtr(size_t size)
+  {
+    return ExtraDataPtr(av_malloc(size)); // <<<< line 119
+  }
+
+  ExtraDataPtr ExtraData; // extra data for codec to use
   unsigned int ExtraSize; // size of extra data
 
   StreamFlags flags;
```

but compiler complain of 
E0289	no instance of constructor "std::unique_ptr<_Ty, _Dx>::unique_ptr [with _Ty=void *, _Dx=CDemuxStream::ExtraDataDeleter]" matches the argument list	xbmc	D:\GIT\kodi\xbmc\cores\VideoPlayer\DVDDemuxers\DVDDemux.h	line 119	

im not able to see where i made the mistake, some hint?

**Comment by fritsch** [comment]
I would role back the unique_ptr change. When resulting code is that unmaintainable ... the benefit of having dynamic memory management is basically nuts. And here with the extra data we exactly know when we acquire it and additionally we exactly know where we delete it. We don't move it anywhere, it does not continue to live anywhere else.

**Comment by CastagnaIT** [comment]
yes its an idea but @repojohnray has made uniqueptr with #22309 because of memleaks
so if we revert that PR its also needed finding where are the memleaks

another thing is that CDVDStreamInfo copy the extradata by using regular malloc and its possible that padding is not kept

but i call myself out of this change i could make more mess
better if someone with more knowledge about memory allocation things take care of this

**Comment by garbear** [comment]
> so if we revert that PR its also needed finding where are the memleaks

I think the approach is to keep the unique_ptrs and do it correctly with a custom deleter. That way we get the best of both worlds - compile-time memory management and correctness.

**Comment by repojohnray** [comment]
As explained by @garbear keeping the unique_ptr is the right approach.

Anyway, this was a quickfix removing the main memory leak:
```
diff --git a/xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamPVRBase.cpp b/xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamPVRBase.cpp
index b2e49e46a3..36749b6d17 100644
--- a/xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamPVRBase.cpp
+++ b/xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamPVRBase.cpp
@@ -322,6 +322,9 @@ void CInputStreamPVRBase::UpdateStreamMap()
 
       if (stream.iSubtitleInfo)
       {
+	if (streamSubtitle->ExtraData)
+	  delete[] streamSubtitle->ExtraData;
+
         streamSubtitle->ExtraData = new uint8_t[4];
         streamSubtitle->ExtraSize = 4;
         streamSubtitle->ExtraData[0] = (stream.iSubtitleInfo >> 8) & 0xff;

```

**Comment by fritsch** [comment]
Thanks much. Could you also post an example for the custom deleter? As unique ptr is the better design choice, no doubt, it should not introduce potential corruption and nicely integrate into the av_malloc and av_free world.

We are using ffmpeg and therefore have to use it properly. We cannot just use new cause it better fits into the c++ world.

**Comment by repojohnray** [comment]
Here is below an example of a custom deleter (`StrdupDeleter`):

https://github.com/xbmc/xbmc/pull/22273/files

**Comment by neo1973** [comment]
I don't think a custom deleter will cut it, there still is the risk someone assigns incorrectly allocated memory to it. In #23182 I instead tried to wrap the extra data to ensure everything stays consistent. What do you think about that?

**Comment by fritsch** [comment]
I like it a lot and it is even better when seen from OO principle,cause it emphasizes on encapsulation while the custom deleter pulls the internals out in favor of scope.

Internal properties stay internal. Thanks much.

**Comment by enen92** [comment]
@CastagnaIT fixed by https://github.com/xbmc/xbmc/pull/23182 ?

**Comment by CastagnaIT** [comment]
yes solved
