### ISSUE TITLE
Add apk to releases 

### ISSUE THREAD

**Issue by hansaplasst** [xbmc/xbmc#23091]
I'm using rss feeds to monitor for new releases and changes. It would be nice if you include the apk in the release assets (now it only includes source code).

This way I immediately can install and test the changes.

**Comment by hansaplasst** [comment]
Do I need to template this?

**Comment by fuzzard** [comment]
It's unlikely we would do this currently as we just have all the artifacts on our mirrors.
Honestly it just adds one more step for the release manager to deal with
