### ISSUE TITLE
UI Behaviour by design or a bug?

### ISSUE THREAD

**Issue by JDRIVO** [xbmc/xbmc#23123]
When playing a video and pressing the return key on a remote to go back to the movie library for example, if you click on the video in the library as the video is playing, the video restarts rather than returning you to the playing video.

**Comment by lrusak** [comment]
Please use the forum for support. https://kodi.tv/article/important-kodi-forum-data-breach/

**Comment by JDRIVO** [comment]
Forums down my man, who knows for how long.
