### ISSUE TITLE
Kodi restarts randomly on tvOS when using Fen package and restores all favorites

### ISSUE THREAD

**Issue by amithacoon** [xbmc/xbmc#23139]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using the Fen package on tvOS 16.4, Kodi will sometimes randomly restart and load the default settings. Additionally, all favorites previously saved in Fen are restored upon the restart. This has been reported by multiple users, including myself and a friend.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

 Kodi should not randomly restart and load the default settings, and all favorites should remain saved in Fen.

## Actual Behavior

 Kodi randomly restarts and loads the default settings, and all favorites previously saved in Fen are restored.

### To Reproduce

1. Install Kodi on tvOS 16.4
2. Install the Fen package.
3. Save some favorites in Fen.
4. Use Kodi as usual, including browsing and playing media through the Fen package.
5. Wait for Kodi to randomly restart and load the default settings.
6. Check Fen to see that all favorites have been restored.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The version of Kodi being used is the latest version available.
To ensure smooth control of the UI, the joystick addon needs to be disabled. However, this does not appear to be related to the random restart and favorites restoration issue.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ x] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
We don't support add-ons that facilitate piracy. Take it up with the add-on author
