### ISSUE TITLE
Commit breaks HDR on rk3588

### ISSUE THREAD

**Issue by royka1** [xbmc/xbmc#23133]
name	HDR broken after commit 23116
Problem report
Create an extensive report to help us document a problem
Bug report
Describe the bug
Here is a clear and concise description of what the problem is:

With the master branch HDR movies won't play as HDR after this commit:
https://github.com/xbmc/xbmc/pull/23116

When I revert this commit it does work again.

Tested on RK3588 with ffmpeg 6 build with rkmpp, with the patches from JeffyCN added:
https://github.com/JeffyCN/FFmpeg/commits/master

Expected Behavior
Here is a clear and concise description of what was expected to happen:
I would've expected that HDR still worked after that commit.

Actual Behavior
Possible Fix: revert that commit
To Reproduce: Play HDR movie from GBM.

Your Environment
Used Operating system:

Linux

Operating system version/name: Ubuntu Jammy/Armbian

Kodi version: Master branch

**Comment by lrusak** [comment]
We've decided it's up to the driver to require the modeset not Kodi.

The driver will need to be fixed.
