### ISSUE TITLE
Kodi 20.1 multiple regressions since 19.5

### ISSUE THREAD

**Issue by go-vegan** [xbmc/xbmc#23141]
## Issues Summary
1. Playback video is brighter
2. Subtitles font/style has changed
3. Hiccup when pressing BACK during playback
4. Audio not always playing
5. Audio is not smooth

## 1. Playback video is brighter
The interface brightness did not change, but on playback it is much brighter. Tested with IPTV and Netflix.

## 2. Subtitles font/style has changed
I'm not sure which font was used on Kodi 19, but since the upgrade it has changed on the Hebrew character set.
I'm still struggling finding another font that I could get used to, but it would be best to just restore the old one.
(I know the entire subtitles engine was rewritten, it doesn't change the problem).

## 3. Hiccup when pressing BACK during playback
On Kodi 19, pressing BACK during playback would smoothly dim the video and fade in the Kodi interface.
On Kodi 20, pressing BACK stops the video and audio for a second or so, turning the screen completely black, before showing the interface over the dimmed video (without gracefully fading).
The same behavior occurs when switching back from the interface to the video.

I tried disabling the hardware acceleration, it did not have any effect.

## 4. Audio not always playing
Sometimes when switching between playback and the interface (as described above), the audio would stop completely. Restarting the playback, and even Kodi entirely, doesn't always bring it back.

Also, this switch sometimes breaks the video-audio synchronization for a while.

## 5. Audio is not smooth
Noticeable especially on IPTV (not Netflix), every few seconds there is a reduction in volume for a split second.

### Environment
Ubuntu 22.04.2
Kodi 20.1

---
name: Problem report
about: Create an extensive report to help us document a problem

---

### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please provide a debug log for your issue to be valid. Thanks

**Comment by scott967** [comment]
> The debuglog can be found here:
Not relevant for this problem.

Actually, when a subtitle is played a debugging-enabled log does provide useful info as regards subtitle font, so we do need it.

**Comment by go-vegan** [comment]
I found a tolerable font, so this can be closed.
Thanks.
(I don't have permissions to delete the issue, sorry)
