### ISSUE TITLE
Weird corrupted screen when alt-tabbed out of Kodi

### ISSUE THREAD

**Issue by OsoaGH** [xbmc/xbmc#23146]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I alt-tab out of Kodi, I will occasionally see green and blue squares flash up on my screen. This can be made permanent when enabling debug logging, so I think it happens when the Kodi window changes in some way. Doesn't happen when the Kodi window is active.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect there not to be the corrupted visuals.

## Actual Behavior

There is flashing corrupted visuals when debug logging is disabled, and permanent corrupted visuals when debug logging is enabled.

## Possible Fix

Doesn't happen when windowed, but still happens when using windowed fullscreen.

### To Reproduce

1. Alt-tab out of Kodi
2. See flashing visuals

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/11233098/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![IMG_0322](https://user-images.githubusercontent.com/33041004/232051227-a4950c66-8833-4cc8-9492-dcd24cc1c023.jpg)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: 11 Home 22H2
 - Kodi version: 20.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CrystalP** [comment]
It's the second similar report in 24h, that's odd, and this time the drivers are recent @thexai

What happens in windowed fullscreen mode?

**Comment by OsoaGH** [comment]
> It's the second similar report in 24h, that's odd, and this time the drivers are recent @thexai
> 
> What happens in windowed fullscreen mode?

As I said, the same thing happens

**Comment by CrystalP** [comment]
Ah true I missed it, it wasn't in the log.
Still, Windows 10 and 11 had changes in the handling of full screen apps, you can take a look at https://devblogs.microsoft.com/directx/demystifying-full-screen-optimizations/, https://www.elevenforum.com/t/enable-or-disable-fullscreen-optimizations-for-games-in-windows-11.4945/
You can find more articles on the subject.

**Comment by thexai** [comment]
> It's the second similar report in 24h, that's odd, and this time the drivers are recent @thexai
> 
> What happens in windowed fullscreen mode?

Shitty AMD Hardware / drivers + Windows updates. Nothing related to Kodi really....  a bug in application can not cause pixelation entire screen even in Windows desktop or other applications...

**Comment by thexai** [comment]
> Brief display corruption may occur when switching between video and game windows on some AMD Graphics Products, such as the Radeon™ RX 6700 XT.

https://www.amd.com/es/support/kb/release-notes/rn-rad-win-23-4-1
