### ISSUE TITLE
(HELP PLEASE) Kodi (Any version) Crashes when click install from zip file

### ISSUE THREAD

**Issue by SmackCracker420** [xbmc/xbmc#23143]
I have tried numerous kodi installs they will either crash on start up or when I try to install from zip file.
OS= Windows 10 latest update
Steps to recreate-
(First Instance)
-Install Kodi
-Run Kodi
-Go ahead and click install from zip file
(CRASHES)

Second Instance
-Install Kodi
-Run Kodi
-Add source (Seren in my case)
-Install from zip file
(CRASHES)

Please help I have tried almost every build from 18 to latest!

**Comment by fuzzard** [comment]
We don't provide support for piracy add-ons (IE seren). 
Show a debug log of a non piracy add-on and we might be able to help
