### ISSUE TITLE
Dolby Vision profile 5 support (IPTPQc2)

### ISSUE THREAD

**Issue by Dogway** [xbmc/xbmc#23159]
### Describe the bug
The player won't detect nor decode correctly DVp5 files

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
I would expect it to decode correctly as other players do like MPV or VLC, or libraries like zimg or libplacebo

## Actual Behavior
Plays the file directly without any model conversion

## Possible Fix
Implement with the aforementioned libraries or directly into Kodi player

 - Operating system version/name:
 - Kodi version: v21 in Android 13

**Comment by lrusak** [comment]
Github is for bug report. Please use the forum (when it's back up) for feature requests.

**Comment by Dogway** [comment]
I consider not playing correctly a file a bug.

**Comment by a1rwulf** [comment]
> I consider not playing correctly a file a bug.

Let's agree that it's a grey area.
Adding support for stuff we don't support yet, is a feature, while from a user perspective it might feel more like a bug.
Anyway, we as devs of the project consider adding yet unsupported formats as a feature request.

**Comment by thexai** [comment]
> I consider not playing correctly a file a bug.

I consider that report "a bug" without including debug log and even without say What Android shitty device you are using is useless.

Also without provide sample media file or MediaInfo. All taking into account that Dolby Vision profile 5 plays correctly on Shield and Fire stick.

Or maybe you're not even using a DV capable display...

**Comment by Dogway** [comment]
@thexai: Bad day? You don't need a DV capable display to correctly decode DV so device here is unrelated. Your comment is indeed useless.
