### ISSUE TITLE
Make availble in app store

### ISSUE THREAD

**Issue by lrperlmu** [xbmc/xbmc#23158]
This is a feature request.

I've heard good things about the Kodi ios app when it comes to managing a music library and music playback. Could you make it available in the app store so that it can be installed on non-jailbroken devices?

**Comment by lrperlmu** [comment]
Hello Bot! Thanks for your message. The only template available for issues was the bug report template, but I am not reporting a bug, I am requesting a feature. Looks like there was a slight oversight where the humans who programmed you forgot to include a feature request issue template.

**Comment by fuzzard** [comment]
We only use GitHub for issues. Feature requests can be made on the forums (when they are back online).

Short answer is not currently. There is a lot of work required to be able to submit to the store, and there's no one actively working on those requirements.

**Comment by lrperlmu** [comment]
ok, thanks at least for taking a look at my request!
