### ISSUE TITLE
Kodi  randomly restores all settings and deletes packages back to default 

### ISSUE THREAD

**Issue by amithacoon** [xbmc/xbmc#23152]
### Describe the bug
When using the Fen package on tvOS 16.4, Kodi will sometimes randomly restart and load the default settings. Additionally,  This has been reported by multiple users, including myself and a friend.

## Expected Behavior
Kodi randomly restarts and loads the default settings

### To Reproduce

Install Kodi on tvOS 16.4
Install the Fen package.
Save some favorites.
Use Kodi as usual, including browsing and playing media.
Wait for Kodi to randomly restart and load the default settings.
Check to see that all favorites and settings have been restored when you launch it randomly.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Operating system version/name:

Kodi version: 20.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
No support is provided for setups using piracy addons.

**Comment by amithacoon** [comment]
> .

sorry GPT wrote it by mistake let me edit it please, it happen without connection to addon installation,

**Comment by amithacoon** [comment]
Logs.
Hope that's helps

https://pastebin.com/ZKJpwTJ9
