### ISSUE TITLE
recently added  not update 

### ISSUE THREAD

**Issue by mohd21** [xbmc/xbmc#23160]
### Describe the bug
Here is a clear and concise description of what the problem is:

The library is not updated from mysql
Except when restarting Kodi

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When return to the Home Screen interface, update the library
 RecentlyAdded home screen update

## Actual Behavior

update the library

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
dbiplus::MysqlDatabase::connect replacing configured host 192.168.20.2 with resolved host 192.168.20.2
Skipped 3 duplicate messages..
CRecentlyAddedJob::UpdateMusic() - Running RecentlyAdded home screen update
dbiplus::MysqlDatabase::connect replacing configured host 192.168.20.2 with resolved host 192.168.20.2
Skipped 1 duplicate messages..

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 7+ /Windows 10
 - Kodi version: kodi-20.1-Nexus-armeabi-v7a

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please provide a useful debug report with a full debug log.

**Comment by mohd21** [comment]
https://paste.kodi.tv/ijerolikik.kodi

thank you

**Comment by mohd21** [comment]
> Please provide a useful debug report with a full debug log.

https://paste.kodi.tv/ijerolikik.kodi

thank you
