### ISSUE TITLE
Kodi randomly restores all settings and deletes addons back to default, but saves logins

### ISSUE THREAD

**Issue by amithacoon** [xbmc/xbmc#23179]
### Describe the bug
When using the packages on tvOS 16.4, Kodi will sometimes randomly restart and load the default settings. Additionally,  This has been reported by multiple users, including myself and a friend.

## Expected Behavior
Kodi randomly restarts and loads the default settings

### To Reproduce

Install Kodi on tvOS 16.4
Install the your packages.
Save some favorites.
Use Kodi as usual, including browsing and playing media.
Wait for Kodi to randomly restart and load the default settings.
Check to see that all favorites and settings have been restored when you launch it randomly.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Operating system version/name:

Kodi version: 20.1

logs!

https://pastebin.com/ZKJpwTJ9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@amithacoon 

You state you are using Kodi v20.1 but your log shows Kodi v21 Alpha 1.

**Comment by fuzzard** [comment]
This is by design by tvOS. We would need to add support for iCloud data storage, which we haven't done.

The reason settings files remain is that tvos gives us a small storage that won't be removed by tvos when space needs to be freed up. That's when all the rest of the data is removed.

It's an unimplemented feature, so add a request in the forum's when they come back up. From memory there already is one, but if not, open one

**Comment by amithacoon** [comment]
> @amithacoon
> 
> You state you are using Kodi v20.1 but your log shows Kodi v21 Alpha 1.

yeah my bad, I have tried to install the updated version to see if It happens, I have to say - happens much often on the newest version.

**Comment by amithacoon** [comment]
> This is by design by tvOS. We would need to add support for iCloud data storage, which we haven't done.
> 
> The reason settings files remain is that tvos gives us a small storage that won't be removed by tvos when space needs to be freed up. That's when all the rest of the data is removed.
> 
> It's an unimplemented feature, so add a request in the forum's when they come back up. From memory there already is one, but if not, open one

anything I can do to prevent this from happening? 
or anywhere I can write this bug in order to find a way to solve it?

**Comment by JanSchr** [comment]
I have 3 Apple TV, 2 are running Kodi 20.2, i never had this problem happening there. On my third Apple TV i'm running 21 Alpha 1 and it's happening about once a week. This really sucks because everytime i need to go through all profiles and disable joystick support because otherwise siri remote will go crazy.

Is there a way to permanently disable a specific addon (joystick support in this case)?

**Comment by amithacoon** [comment]
> I have 3 Apple TV, 2 are running Kodi 20.2, i never had this problem happening there. On my third Apple TV i'm running 21 Alpha 1 and it's happening about once a week. This really sucks because everytime i need to connect a bluetooth keyboard and go through all profiles and disable joystick support because otherwise siri remote will go crazy.
> 
> Is there a way to permanently disable a specific addon (joystick support in this case)?

seems like you should install the 20.2 because it doesnt has this bug with the 21 alpha 1 

im talking about the fact im losing the hole configuration and addons settings

**Comment by TwilightMercy** [comment]
https://www.reddit.com/r/Addons4Kodi/comments/14j7la0/kodi_keeps_resetting_on_apple_tv_4k/?utm_source=share&utm_medium=ios_app&utm_name=iossmf
