### ISSUE TITLE
Can’t open plugs for xbox series s

### ISSUE THREAD

**Issue by Luobben** [xbmc/xbmc#23171]
![IMG_4838](https://user-images.githubusercontent.com/106941000/232676965-54af172b-48f4-437c-9c47-df48ccec5d8e.jpeg)
![Uploading IMG_4839.jpeg…]()

### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
The information provided (screenshot only) is not enough to know what happens here. Anyway Github on this repo is only for bugs in core Kodi (not add-ons) and this seems a issue with one particular add-on.

You should obtain support on forum (when available) or from place you got the add-ons.
