### ISSUE TITLE
Switch from pcre(pcrecpp) to pcre2

### ISSUE THREAD

**Issue by kekePower** [xbmc/xbmc#23184]
### Describe the bug
Here is a clear and concise description of what the problem is:

pcre is no longer getting security updates or is actively maintained and has been succeeded by pcre2.
Kodi uses pcrecpp from pcre and it's mostly in [xbmc/filesystem/FTPParse.cpp](https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/FTPParse.cpp).

Is it possible to replace this with similar options from pcre2?
Perhaps not feasible for version 20.x, however it could be done for 21.

From https://pcre.org/
```quote
The older, but still widely deployed PCRE library, originally released in 1997,
is at version 8.45. This version of PCRE is now at end of life, and is no longer
being actively maintained. Version 8.45 is expected to be the final release of
the older PCRE library, and new projects should use PCRE2 instead.
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Mageia Cauldron
 - Kodi version: 20.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
PRS are most definitely welcome.

But as this is a feature request, post it on the forums (when available). We only use GitHub issues for tracking bugs

**Comment by dvzrv** [comment]
Hi! :wave: 

We are currently working on [moving from pcre to pcre2 on Arch Linux](https://archlinux.org/todo/move-to-pcre2/), because pcre is EOL *and* unmaintained.

Security issues will no longer be addressed in upstream pcre, which means that all dependents are vulnerable to any issues that may occur there in the future.

Therefore I would certainly consider this issue a "bug" and not just a "feature request" (unless security issues of this project are not considered "bugs").

**Comment by dvzrv** [comment]
I see that https://github.com/xbmc/xbmc/pull/24128 addressed this by entirely removing the use of pcre.

**Comment by dvzrv** [comment]
Hm, that change seems to have only affected https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/FTPParse.cpp.

In https://github.com/xbmc/xbmc/blob/ac329371f89c66193de4174be4df095af3809de2/xbmc/utils/RegExp.h and https://github.com/xbmc/xbmc/blob/ac329371f89c66193de4174be4df095af3809de2/xbmc/utils/RegExp.cpp pcre is still in use and would need to be replaced with e.g. `std::regex` or pcre2.
