### ISSUE TITLE
Accessing Local Network is Delayed, due to "Combine split video items"

### ISSUE THREAD

**Issue by kleczerx** [xbmc/xbmc#23209]
### Describe the bug
The setting feature "Combine split video item" when set to ON, effects my local network access when using KODI's main menu's Video item. When activated to ON, and then using Main Menu "Video > Files > entering the 1st level folder of my local-server (over a 10Gbit link) there is a full 60-second delay before finally given entry, and then another 60-sec wait before entry to the 2nd level folder. > Once beyond the first two level folders moving among folders beyond this point is normal; working with video/other files files is normal. When exiting from a server back to Kodi, there are similar delays before clearing the server(s).

IF the feature is OFF entering any of my two servers is smooth.

The buggy feature is located in Kodi's Settings > Media > Videos > "Combine split video items".
Note: this bug did not exit in versions 18. It first appear in version 19 and followed thru to present day Version 21.0 Omega_Alpha1.

To overcome the use of this feature I combined all the two part videos using MKVToolNix application.

My Environment
My equipment and Kodi versions: Desktop Windows 11 x64 latest build, Nvidea Shield Media Player TV using Kodi 21.0 Omega Alpha1 Arm64-v8a & two QNAP servers over a local 10Gb network.

### To Reproduce
To reproduce set Combine Split Video Item to ON. Then entering Kodi main menu Video > Files > enter a local server or PC to observe the long delay before entry occurs.

**Comment by thexai** [comment]
Closed as you opened a new issue for the same but for other time, please use edit functionality:

![edit](https://user-images.githubusercontent.com/58434170/235342539-bb18ad47-e68b-48cb-9685-44b1966d884d.png)
