### ISSUE TITLE
Yet again, change kodi caching setting!

### ISSUE THREAD

**Issue by markg85** [xbmc/xbmc#23200]
### Describe the bug
The default caching settings cause buffering issues on network storage. Even on super fast local networks (10gbit/s).
And has been the case for many many many many many years with equally many bug reports.

## Expected Behavior
Storage accessed over the network (ftp, samba, nfs) should play flawlessly.

## Actual Behavior
Buffer issue within mere seconds.

## Possible Fix
Change the **default** settings to:
```<advancedsettings>
  <network>
    <buffermode> 1 </buffermode>
    <readbufferfactor> 1.5 </readbufferfactor>
    <cachemembuffersize> 104857600 </cachemembuffersize>
  </network>
</advancedsettings>
```

### To Reproduce

Actually use kodi on a local network and you'll instantly see this.

### Debuglog

None (embedded kodi device, not easily possible to dump logging)

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
I've reported this before https://github.com/xbmc/xbmc/issues/22332 and https://github.com/xbmc/xbmc/issues/22339. It has moved to the forums before just to die out.

This issue is probably going to be closed again too as kodi devs apparently don't give a damn about network storage.
I'll happily be proven wrong.
I asked before if a patch would be welcome implementing my suggested defaults as new defaults. No comment on that either. The offer stands. I'm just not going to even attempt it if i don't get a reasonable answer.

**Don't** dare marking this as just an embedded issue with kodi. It happens on **all** platforms, i've seen it everywhere. (windows/linux/desktops hardware and embedded arm). It's just **easier** to trigger on embedded hardware but it happens **everywhere**.

In my specific case easy kodi update completely ruins my embedded kodi device (not gonna name the type/brand as it doesn't matter!) and it forces me to go through the difficult hassle of updating the `advancedsettings.xml` using the on screen keyboard and a remote control. Not funny.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Irrelevant
 - Kodi version: **all of them, not even a joke**

**Comment by chewitt** [comment]
In summary: an irate user wants the config that happens to resolve their network issue to be the imposed default for the rest of our multi-million user installed base; an installed base that (if you step back and look at the big picture) doesn't complain about incorrect caching settings. Of course there are always a few folks that for random reasons might need to fiddle with caching, but the largest group are those using dodgy IPTV services (so we don't care much for their issue reports). In short, no we aren't going to cause a large volume of self-inflicted support issues by messing with caching defaults that don't need to be messed with. We could move cache settings into the GUI to make them more accessible and silence a few whinging users, but it's a double-edged fix _because_ if we make it really easy to fiddle with stuff that doesn't need to be fiddled with; users will fiddle with it and cause problems. So faced with a "screwed if you do, and damned if you don't" situation .. the sensible and least effort course of action is to not change anything; at the minor inconvenience of a small percentage of users who need to configure an advancedsettings.xml file.

Anyway.. changing defaults is a feature request and we don't accept feature requests here (use the forums). As there is no functional bug (software is working as-designed).. I'm closing this ticket.

**Comment by lrusak** [comment]
Take it to the forum for discussion please. https://forum.kodi.tv/

This is a bug tracker not a support board.
