### ISSUE TITLE
Party mode starts by sorting 10 random songs by artist making the first song not random enough.

### ISSUE THREAD

**Issue by XZCE** [xbmc/xbmc#23203]
I have a car-pc loaded with Kodi (an older version, but I've also tried the latest version which does the same thing) and I use Party Mode to pick 10 random songs to play on my trip into work and back each day...  The car-pc resets (turns off) once the car is parked after 15 minutes, so each trip goes through the same process.

I get to hear about 3 or 4 songs each trip, but since the "random list of songs" gets sorted by artist, the first song usually begins with an artist name starting with A or B, sometimes C.  After using this for a year, I'm now fairly bored with what's being chosen by Kodi to listen to.  I'm finding myself seeking through the random playlist to get to songs rarely played (artists starting with X, Y & Z, for instance, never get played).

I would appreciate Party Mode being truly random - thanks for listening - and for Kodi.

**Comment by scott967** [comment]
Suggest asking in support forum first; regardless enable debug-level logging and capture a debug log (or several with restart) showing party mode play.

**Comment by scott967** [comment]
Update I did take a look at this and recommend close:  I will open new issue.

**Comment by XZCE** [comment]
Ok, thanks.
