### ISSUE TITLE
Subtites Position on screen to "Bottom of Screen" does not work, and remain at bottom of video. 

### ISSUE THREAD

**Issue by kleczerx** [xbmc/xbmc#23210]
### Describe the bug
Here is a clear and concise description of what the problem is:

The feature "Subtits Position on screen [Bottom of Screen] simply does not work or is inert. The setting > Player > Subtitles > Position on screen > "Bottom of Screen" does not move subtitles to the position intended or any position; should position subtitles at the very bottom of the screen and slightly above the TV's frame .

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When "Bottom of Screen" is active and working properly, the bottom edge of the subtitles ACTUALLY appear to "near" touch the bottom frame of the TV monitor, an videos with back bars also should "near" touch the bottom of the TV's frame edge. This resulting in  MORE of the picture/video being seen.

I tested, using the same videos as examples, Kodi versions 18 & 19 and this setting DID work properly as describe. ALL versions of 20 and 21 to Omega have this bug.

## Actual Behavior

A. Kodi Versions 20/21 bug: Videos with black bars (above and below the video) have subtitles showing on the video picture above the bottom black bar. Full screen videos, the subtitles were positioned at the bottom of the video.

B. Another noticeable failure is the positioning of the subtitle in relation to any bottom edges. Though the subtitles DO NOT position to the bottom of the TV screen, the position it does take [at the bottom edge of the video picture] is RAISED HIGHER by 1 inch from the bottom edge; this is measured between the picture's bottom edge TO the subtitle's text bottom edge.   I measured this on a Samsung 75 inch screen. In other words, earlier versions had the text much closer (lower) to the very bottom, something less than 1/4 of an inch; resulting in more video seen and not covered by text. 

## Possible Fix

A Fix, re-write the feature code, by comparing the same code to earlier versions 18/19 of the same feature.

### To Reproduce

1. Feature location: KODI Setting > Player > Subtitles > Position on screen > select "Bottom of Screen".
2. Play a video with black bars above and below picture, the subtitles will remain, unmoved, above the bottom edge of the video, BUT WILL NOT position, as should, to bottom of the TV edge.
3.

### Debuglog

The debuglog can be found here:

xxx

### Screenshots
Here are some links or screenshots to help explain the problem:

xxx

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I always try to include subtitles with viewing a video. Since Versions 20/21 subtitleS are SEEN much to high on the picture being watched.

### Your Environment
Used Operating system:

 - [ x] Android - Nvideo Shield TV
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Windows - Windows 11 x64 latest update
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 21.0 Omega alpha1 arm64-v8a AND 21.0 x64 for Windows.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
in addition to the unused template is mandatory attach a full Kodi DEBUG log without it the issue will not be considered

**Comment by CastagnaIT** [comment]
despite the updated template, i remember you that you still have not provided relevant full Kodi DEBUG log

**Comment by thexai** [comment]
Subtitles have been extensively reworked from Matrix to Nexus and some subtitles settings have changed their default value and even their meaning. Some issues may be due to incorrect settings due to a "bad migration" or old personalized settings not suitable for new settings. 

Restoring the default settings may be a solution.

Apart from this, you have not provided a debug log so this issue is not useful to know what is happening. 

Please use the forum for support.
