### ISSUE TITLE
Kodi Nexus doesn't start in Arch Linux after python update to 3.11.3-1

### ISSUE THREAD

**Issue by cg00001** [xbmc/xbmc#23231]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi fails to load giving this message if started on a terminal.
`/usr/lib/kodi/kodi.bin: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory`
I'm using Kodi Nexus from the kodi-nexus-git package.

### To Reproduce

1.  Start Kodi from a terminal.
2.
3.

### Debuglog

The debuglog can be found here:
There can not be a debuglog since Kodi does not load.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by cg00001** [comment]
Same issue on Kodi Omega.

**Comment by lrusak** [comment]
Did you link kodi against the new version of python?
