### ISSUE TITLE
Cannot build using GCC 13.1

### ISSUE THREAD

**Issue by graysky2** [xbmc/xbmc#23237]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi fails to build using GCC 13.1 and corresponding toolchain on Arch Linux (AL).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should build.

## Actual Behavior

Kodi errors out while building.

### To Reproduce
1. Get the official AL [kodi](https://github.com/archlinux/svntogit-community/tree/packages/kodi/trunk) files for kodi Nexus or the [kodi-git](https://aur.archlinux.org/packages/kodi-git) files from the AUR if you want to build from master.
2. Try building using a [clean buildroot](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot#Classic_way).

### Debuglog
Not relevant to this report

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Attached is a debug build log showing the many errors.
* [kodi-20.1-3-x86_64-build.log.gz](https://github.com/xbmc/xbmc/files/11404132/kodi-20.1-3-x86_64-build.log.gz) from building kodi Nexus.
* [kodi-git-r62995.b885466e951-1-x86_64-build.log.gz](https://github.com/xbmc/xbmc/files/11404158/kodi-git-r62995.b885466e951-1-x86_64-build.log.gz) from building kodi-git

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
I'll look into this over the weekend.

**Comment by graysky2** [comment]
I think it's OK to close this, no?
