### ISSUE TITLE
Add-on migration stuck on Kodi update from Matrix to Nexus

### ISSUE THREAD

**Issue by nonobio** [xbmc/xbmc#23248]
### Describe the bug
Here is a clear and concise description of what the problem is:
Hi :)
After installing Kodi 20.1 to update my 19.4 version on windows: it stuck on "Add-on migration..." for about 15 minutes.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should start and I should be watching a good movie :)

## Actual Behavior

Kodi doesn't start, it is stuck on Add-on Migration...

## Possible Fix

I had the same issue when I updated Kodi 18 to Kodi 19, and I managed to resolve the issue but not in an easy way:
https://github.com/xbmc/xbmc/issues/18723#issuecomment-906169708

### To Reproduce

1. Install Kodi 20.1 over my 19.4 installation
2. Launch Kodi
3. "Add-on migration..."

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/oduwemocak.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

![236676477-4f757ab1-f5d2-4c7a-a331-08141a214f14](https://user-images.githubusercontent.com/7425799/236676719-ace18bb3-1dd5-4385-b34b-f92ade8e2cac.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
I use a MySQL shared database and Kodi said database migration very quickly before saying "Add-on migration".

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4 to 20.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by nonobio** [comment]
I found the explanation to enable the debugging log (I added the line  <loglevel>2</loglevel>  to my advancedsettings file),.

So: I killed Kodi and surprise: it started! Everything "seems" to be ok.

This is the new log with loglevel2 : https://paste.kodi.tv/uvapuyeciw.kodi

Do you think I can use it without issue or should I check or clean something because it stuck after the first launch following the update?

**Comment by howie-f** [comment]
think this issue can be closed then?

**Comment by nonobio** [comment]
Yes I think, Thanks :)
