### ISSUE TITLE
webOS: No video when playing a DVD ISO

### ISSUE THREAD

**Issue by UltraHDR** [xbmc/xbmc#23249]
## Bug report

Thanks for your hardwork on this port!

### Describe the bug
- Kodi shows a black screen when playing a DVD iso, the sound plays back fine and the progress bar is moving. The TV supports this format as the video plays fine with the built in DLNA Media player.

## Expected Behavior
Video should show on screen

## Actual Behavior
Black screen, the sound plays back fine and the progress bar is moving.

### To Reproduce
1. Open a DVD iso or a vob file from an extracted DVD. Sample file taken from https://www.deniscarl.com/dvdtest/ -> https://www.deniscarl.com/dvdtest/videotest.zip  (Note: has no audio)

### Debuglog
The video plays fine with the built in DLNA Media player.

### Screenshots 
None

## Additional context or screenshots (if appropriate)
None

### Your Environment
Used Operating system:
 - Operating system version/name: LG C1
 - Kodi version: https://mirrors.kodi.tv/nightlies/webos/master/org.xbmc.kodi_20230506-eebc7146-master_arm.ipk

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
@sundermann
