### ISSUE TITLE
webOS XVID doesn't play

### ISSUE THREAD

**Issue by UltraHDR** [xbmc/xbmc#23251]
## Bug report

Thanks for your hardwork on this port!

### Describe the bug
Video doesn't play

## Expected Behavior
Video should play

## Actual Behavior
Video doesn't play

### To Reproduce
1. Open https://samples.mplayerhq.hu/V-codecs/XVID/ttm1.avi

### Debuglog
The video plays fine with the built in DLNA Media player.

### Screenshots 
None

## Additional context or screenshots (if appropriate)
None

### Your Environment
Used Operating system:
 - Operating system version/name: LG C1
 - Kodi version: https://mirrors.kodi.tv/nightlies/webos/master/org.xbmc.kodi_20230506-eebc7146-master_arm.ipk

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
@sundermann

**Comment by sundermann** [comment]
The testfile provided seems bad. It doesn't play on my shield and there's ffmpeg warnings when parsing it. dts and pts timestamps are -1. Other .avi files play fine

```
2023-05-07 22:05:32.620 T:7354    debug <general>: ffmpeg[0x930e868]: [avi] Packet corrupt (stream = 0, dts = 96).
2023-05-07 22:05:32.619 T:7362    debug <general>: AddData: CDVDVideoCodecStarfish: dts:-1 ns pts:-1 ns sz:6748 current state Flushed
2023-05-07 22:05:32.619 T:7362  warning <general>: AddData: CDVDVideoCodecStarfish: Buffer submit returned error: {"returnValue":"Error"}
```

**Comment by UltraHDR** [comment]
Sorry about that, it worked fine in Kodi on my computer but yes VLC does complain. Can you try https://samples.mplayerhq.hu/V-codecs/XVID/old/green.avi please? That works in the DLNA media player but Kodi doesn't even open it? Thanks

**Comment by sundermann** [comment]
It seems mpeg4 is not properly supported through the API we are using. Kodi is not using the same API as the internal media player and thus media file support can be different. I will propose a change to remove mpeg4 from the list of hw accelerated file formats.
