### ISSUE TITLE
Current nightly build is always overwritten by update from Google Play Store

### ISSUE THREAD

**Issue by rainman74** [xbmc/xbmc#23258]
### Describe the bug
I have the latest nightly build installed (e.g. kodi-20230429-448d7154-Nexus-armeabi-v7a.apk), and it still always gets automatically overwritten via update from Google Play Store by the latest official version 20.1.

## Expected Behavior
A nightly build should have a higher version than the last stable version.

### To Reproduce

1. Install nightly build on Android
2. wait a few hours
3. Google Play Store installs old stable version

### Debuglog

The debuglog can be found here:
n/a

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://user-images.githubusercontent.com/16306963/236886818-70849fdc-dae2-4900-b7c9-7ff00315e122.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: kodi-20230429-448d7154-Nexus-armeabi-v7a.apk

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
Just disable automatic updates of Kodi...

**Comment by rainman74** [comment]
> Just disable automatic updates of Kodi...

There is not such an option on Android TV 10 !
