### ISSUE TITLE
webOS: Only audio plays when playing a VC1 file

### ISSUE THREAD

**Issue by UltraHDR** [xbmc/xbmc#23250]
## Bug report

Thanks for your hardwork on this port!

### Describe the bug
- Kodi only plays the audio. The TV supports this format as the video plays fine with the built in DLNA Media player. VC1 is used in some Blu-rays

## Expected Behavior
Video should play

## Actual Behavior
Kodi only plays the audio

### To Reproduce
1. Open https://samples.mplayerhq.hu/V-codecs/WVC1/FlightSimX_720p60_51_15Mbps.wmv

### Debuglog
The video plays fine with the built in DLNA Media player.

### Screenshots 
None

## Additional context or screenshots (if appropriate)
None

### Your Environment
Used Operating system:
 - Operating system version/name: LG C1
 - Kodi version: https://mirrors.kodi.tv/nightlies/webos/master/org.xbmc.kodi_20230506-eebc7146-master_arm.ipk

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by UltraHDR** [comment]
@sundermann . Thanks

**Comment by sundermann** [comment]
It seems vc1 is not properly supported through the API we are using. Kodi is not using the same API as the internal media player and thus media file support can be different. I will propose a change to remove vc1 frrom the list of hw accelerated file formats.
