### ISSUE TITLE
Jellyfin repo appears empty on Kodi 21 (Omega)

### ISSUE THREAD

**Issue by Moxh3** [xbmc/xbmc#23287]
### Describe the bug
The Jellyfin repo appears empty on Kodi 21 (Omega). As such, it is not possible to add the Jellyfin Video add-on.

## Expected Behavior
Expected to see the Video Add-ons folder (as per https://jellyfin.org/docs/general/clients/kodi/) in the Jellyfin Add-Ons Repo and able to select and install the Jellyfin add-on.

## Actual Behavior
Jellyfin Add-Ons Repo appears empty, as such it is not possible to add the Jellyfin Video add-on.

### To Reproduce
1. Install Jellyfin add-on repository on Kodi (repository.jellyfin.kodi.zip) as per https://jellyfin.org/docs/general/clients/kodi/
2. From within Kodi, navigate to "Add-on Browser"
3. Select "Install from Repository"
4. Choose "Kodi Jellyfin Add-ons"
5. Nothing there

### Debuglog
n/a

### Screenshots 
n/a

## Additional context or screenshots (if appropriate)
n/a

### Your Environment
Used Operating system:
 - [x] Android/FireTV
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: FireTV OS
 - Kodi version: 21 Alpha 1

**Comment by Moxh3** [comment]
Fixed up the "Ignored rules"

**Comment by fuzzard** [comment]
This is an issue for the jellyfin add-on maintainers. Best to post at the add-ons dev page
