### ISSUE TITLE
webos: EAC-3 Dolby Digital Plus passthrough is broken, PCM received instead

### ISSUE THREAD

**Issue by craigcarnell** [xbmc/xbmc#23288]
### Describe the bug
I am unable to get any video containing a Dolby Digital Plus (5.1) audio track to passthrough correctly to my Denon AVR-X2700H, only PCM 2.0 is offered instead.

LG TV is a 2022 C2 OLED, HDMI is being used, eARC is enabled in settings and passthrough (bitstream) is selected in the TV settings. Note passthrough works with my Series X.

When playing back the first test file below, only 2.0 channel PCM is offered:

Dolby Digital 5.1 Plus test file: https://ott.dolby.com/OnDelKits/DDP/Dolby_Digital_Plus_Online_Delivery_Kit_v1.4.1/Test_Signals/muxed_streams/MP4/Example/ChID_voices_1920x1080p_25fps_h265_6ch_256kbps_ddp.mp4

I have also tested a Dolby Atmos file also.

Dolby Atmos test file:
https://ott.dolby.com/OnDelKits/DDP/Dolby_Digital_Plus_Online_Delivery_Kit_v1.4.1/Test_Signals/muxed_streams/MP4/Example/ChID_voices_1920x1080p_25fps_h265_6ch_640kbps_ddp_joc.mp4

The following Dolby Digital 5.1 (not plus) test file **does** work:
https://www.paolofiorani.it/TEST%20Audio/Ac3%20Dolby%20Digital%205.1Ch%20Sound%20Test.avi

## Expected Behavior
The a/v receiver should receive a Dolby Digital+ 5.1 bitstream.

## Actual Behavior
PCM 2.0 is received instead which is incorrect.

### To Reproduce
Steps to reproduce the behaviour:
As noted above.

### Debuglog
https://paste.kodi.tv/yohaxafuri.kodi

### Your Environment
Used Operating system:
 - [x] Linux

 - Operating system version/name: Linux
 - Kodi version: master

**Comment by fritsch** [comment]
Your enumeration of the PT device is not correct. Please make sure that it has at least 48000 and 192000 samplerate available, as our eac3 packer uses 2 channel with 192000 khz 16 bit bandwidth in IEC mode.

If you use RAW mode, depends on what your packer needs. Android uses here 2 channels and 48 khz to open the device. Audio Engine queries the Supports function before using PT.

**Comment by sundermann** [comment]
E-AC3 cannot be implemented correctly because the `StreamInfo` only reads channel count and frame size from the dependent stream. This has already been broken forever see #23217 and #14604

**Comment by sundermann** [comment]
Yes, that is correct but still the above mentioned issue will prevent playback. If we add those samplerates the sink will start playing but you won't hear anything because channel cound and frame size is not correct

**Comment by fritsch** [comment]
Hehe. If you reduce that 10 by 2, it works?

**Comment by sundermann** [comment]
It does, yes. But we'd also need to know if the stream is ATMOS (e-ac3-joc) or normal e-ac3

**Comment by fritsch** [comment]
The packer should know that as long as we don't cut out the data. See our packer, it also just copies the relevant bits.

**Comment by sundermann** [comment]
We don't use the packer on webOS. I couldn't spot any joc detection in the iec packer

**Comment by fritsch** [comment]
Jep, that's what I wanted to say: Atmos via DD+ works perfectly fine when our IEC Packer with the kodi syncer is in use. So nothing is skipped here. The original data from the movies are not IEC frames, we create them - and Audio-Engine passes the same information to the RAW sink, so not sure what should be missing.

**Comment by sundermann** [comment]
On webOS we need to tell the decoder if it's a normal e-ac3 or e-ac3 stream. It also needs to know the number of channels

**Comment by craigcarnell** [comment]
@fritsch Can confirm the following changes you recommended have both:

1) shown the EAC-3 toggle in the kodi settings menu, 
2) but also have working DD+ on my amp!

```
  void CAESinkStarfish::EnumerateDevicesEx(AEDeviceInfoList& list, bool force)
  <snip>
  info.m_channels = AE_CH_LAYOUT_2_0;
  info.m_sampleRates.emplace_back(44100); // DD+
  info.m_sampleRates.emplace_back(48000L);  // DD+
  info.m_sampleRates.emplace_back(192000L);  // Dolby trueHD?
```

I have already patched @sundermann changes in https://github.com/xbmc/xbmc/pull/23217#issuecomment-1546876438 on my local copy.

**Comment by fritsch** [comment]
It depends on the packer. For kodi we know that we pack with 4 times the streaminfo.Samplerate, so 192 khz or 4 x 41 khz when our IEC packer is in use, therefore we here open 192khz / 2 channels, 16 bit on the sink.

Others like Android are given the normal samplerate, e.g. 48 khz and they internally then decide to keep that if it's just 5.1 AC3 or if more is needed. Most Android devices are broken for 7.1 packing or only pack 5.1 from it.

The comment above for TrueHD is wrong. It's basically about the "transport" frequency.

With RAW kodi basically sends you packages of m_frameSize=1 (this says nothing about the number of bytes we tunnel), see ActiveAESink that calls OutputSample. On which sink format you need to configure it depends on your sink. On Android one just gives the channel mask (2 channels), the sample rate (44.1 or 48) and the RAW format. Then the data is written (and consumed) at once.

Kodi's TrueHD is sent via 8 channel 16 bit and 192 khz when we do IEC mode. As you can see in Android TrueHD and DTS-HD RAW are only provided with 48 khz samplerate. In general a 2 channel bandwidth would need 384 khz to transport TrueHD with it, but again find out what your sink (the packer in the system) needs.

**Comment by fritsch** [comment]
Ah and btw. you get them both from kodi the m_sampleRate and the m_streamInfo.m_sampleRate. The latter is the interesting for you, if you want to forward it to a packer. The first one if kodi's IEC packer is in use, cause this is already "pcm sample" (not really pcm, but I hope you get what I mean -> payload transmitted via the pcm bandwidth as digital signal).

**Comment by sundermann** [comment]
TrueHD is simply not supported. And whilst this might be enough to get eac3 working, it is still missing out on the proper channel count and eac3 joc flag

**Comment by fritsch** [comment]
Samplerate for Android:
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/AudioEngine/Sinks/AESinkAUDIOTRACK.cpp#L364

Mapping the raw frames (m_frameSize=1) to the data:
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/AudioEngine/Sinks/AESinkAUDIOTRACK.cpp#L835

Writing it:
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/AudioEngine/Sinks/AESinkAUDIOTRACK.cpp#L207

As you can see at the end it's a simple memcpy just writing all bytes at once on the sink.

@sundermann how does the underlaying API need the number of channels? it won't really matter for their resulting transport stream. The JOC flag I can maybe understand, that they need a bit help with it to avoid switching later on.

**Comment by fritsch** [comment]
> On webOS we need to tell the decoder if it's a normal e-ac3 or e-ac3 stream. It also needs to know the number of channels

But why are they decoding it? They should just pack it properly.

**Comment by sundermann** [comment]
> But why are they decoding it? They should just pack it properly.

Sorry the wording was bad. Not sure what is happening internally but the pipeline wants to know it (they might decode it only if played via internal speakers)

> @sundermann how does the underlaying API need the number of channels? it won't really matter for their resulting transport stream. The JOC flag I can maybe understand, that they need a bit help with it to avoid switching later on.

I agree, that in theory it should not be needed to pass that information explicitly. However, the API is requires it and thus we should pass it as well. There is a chance that it might work without passing this specific information on some devices but there is probably a reason for why the pipeline needs this information

**Comment by fritsch** [comment]
Agreed. We cannot change the library, so the information is needed.

**Comment by craigcarnell** [comment]
So I've created a PR https://github.com/xbmc/xbmc/pull/23291. I've tested this with and without https://github.com/xbmc/xbmc/pull/23217#issuecomment-1546876438 and it worked for me.

**Comment by sundermann** [comment]
The `addbsie` field to check for joc is at the very end of the bitstream information (E.1.2.2 from specification). There is plenty of optional fields there so in order to get to the desired field one has to first parse all the preceeding fields first to find the right offset.

[ffmpeg eac3 parse](https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/eac3dec.c#L465) takes around 200 LoC just to get to that field.

**Comment by craigcarnell** [comment]
@sundermann Please could you add this as a commit? https://github.com/xbmc/xbmc/pull/23217#issuecomment-1546876438

@fritsch Is the joc flag accessible? e.g. a boolean somewhere

@sundermann How do we pass the joc flag? Through the json? Is there an example of this somewhere else?

**Comment by fritsch** [comment]
We don't parse this to my knowledge. We just make sure we don't cut too much. See there are two paths:

a) DVDCodecPassthrough
b) FFmpeg

If we do PCM output - ffmpeg does it all for us and we don't touch more than we need. Though, ffmpeg also only skips the atmos bits when decoding.

**Comment by sundermann** [comment]
@craigcarnell the patch is not correct, so why add it?

**Comment by craigcarnell** [comment]
@sundermann So we just need to figure out the correct channel count?

I've added a couple of images below. As you can see just by adding the relevant frequencies it is activating DD+ on my amp. There is however some A/V sync issues (seems behind by less than a second).

Using a 5.1 channel test is also sending 5.1 to the correct speakers in my setup.

https://imgur.com/gHDXKgm
https://imgur.com/a/YdU1sFn

I'm not sure if this is due to this change and I'll do some more testing as I have seen A/V sync issues before using passthrough.
