### ISSUE TITLE
Music stops on Android TV when screen is switched off

### ISSUE THREAD

**Issue by RengeRenge** [xbmc/xbmc#23280]
### Describe the bug
When playing music on an Android TV, with current Kodi playback is halted when the screen is switched off. At the same time, I used VLC to play music, it did not stop when the screen is switched off.

## Expected Behavior
Music continues playing after switching display off.

## Actual Behavior
Music stops.

### To Reproduce

1. Start music player.
2. Switch screen off.

### Debuglog

I can't get the logs.

### Screenshots 
None

## Additional context or screenshots (if appropriate)
None

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 12 API level 31
 - Kodi version: 21.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
> I can't get the logs.

Then we are not able to help you. Provide a debug log (see the wiki how), or we will be forced to close the issue.

**Comment by sarbes** [comment]
Closing due to lack of response.
