### ISSUE TITLE
WSGI-related build failure

### ISSUE THREAD

**Issue by rien333** [xbmc/xbmc#23293]
### Describe the bug

Recently, whenever I try to build kodi from source, either the stable Nexus release or a fairly recent commit, I always get the following, rather unhelpful error (for my full build log see, below):

```
...
[ 93%] Linking CXX static library platform_posix_utils.a
[ 93%] Built target platform_posix_utils
[ 93%] Generating AddonModuleXbmcwsgi.i.cpp
[ 93%] Building CXX object build/interfaces/legacy/CMakeFiles/legacy_interface.dir/Addon.cpp.o
[ 93%] Building CXX object build/guilib/CMakeFiles/guilib.dir/GUIWindowManager.cpp.o
[ 93%] Building CXX object build/rendering/gles/CMakeFiles/rendering_gles.dir/ScreenshotSurfaceGLES.cpp.o
[ 93%] Building CXX object build/platform/posix/CMakeFiles/platform_posix.dir/XHandle.cpp.o
[ 93%] Building CXX object build/interfaces/legacy/wsgi/CMakeFiles/legacy_interface_wsgi.dir/WsgiInputStream.cpp.o
make[2]: *** [build/swig/CMakeFiles/python_binding.dir/build.make:112: build/swig/AddonModuleXbmcwsgi.i.cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:11519: build/swig/CMakeFiles/python_binding.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 93%] Building CXX object build/interfaces/legacy/wsgi/CMakeFiles/legacy_interface_wsgi.dir/WsgiResponseBody.cpp.o
[ 94%] Building CXX object build/interfaces/python/CMakeFiles/python_interface.dir/CallbackHandler.cpp.o
[ 94%] Building CXX object build/rendering/gles/CMakeFiles/rendering_gles.dir/GLESShader.cpp.o
[ 94%] Building CXX object build/interfaces/legacy/wsgi/CMakeFiles/legacy_interface_wsgi.dir/WsgiResponse.cpp.o
[ 94%] Building CXX object build/platform/posix/CMakeFiles/platform_posix.dir/XTimeUtils.cpp.o
[ 94%] Building CXX object build/utils/CMakeFiles/utils.dir/RssReader.cpp.o
...
[100%] Building CXX object build/utils/CMakeFiles/utils.dir/DRMHelpers.cpp.o
[100%] Linking CXX static library utils.a
[100%] Built target utils
make: *** [Makefile:136: all] Error 2
```

Also tagging @graysky2 because this might be Arch Linux ARM specific. I'm 100% sure that I repeatedly build kodi successfully just last month. 

## Expected Behavior

Kodi builds without a problem. 

## Actual Behavior

The build process always error on something related to swig/the file `AddonModuleXbmcwsgi.i.cpp`

## Possible Fix

No idea.

### To Reproduce

1.  Download one of the arch linux arm PKGBUILDs  (either [kodi-rpi-git](https://github.com/archlinuxarm/PKGBUILDs/tree/master/alarm/kodi-rpi-git) or [kodi-rpi](https://github.com/archlinuxarm/PKGBUILDs/tree/master/alarm/kodi-rpi))
2. Run `makepkg`

### Debuglog

Note that the error happens irrespective of whatever patches I'm applying: 
[build.log](https://github.com/xbmc/xbmc/files/11494915/build.log)

### Screenshots 

N/A

## Additional context or screenshots (if appropriate)
N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux ARM
 - Kodi version: 20/git
- Python version: 3.11.3 
- Swig version: 4.1.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by graysky2** [comment]
@rien333 - I just built kodi-rpi-20.1-6-aarch64 without errors.  Not sure what your problem is... are you building in a clean-chroot?

**Comment by rien333** [comment]
Thanks for the tips and feedback! I am building in a clean chroot. I will also try building with `DCMAKE_VERBOSE_MAKEFILE` to see if I can get some extra info.
