### ISSUE TITLE
http web server won't start

### ISSUE THREAD

**Issue by GregAce** [xbmc/xbmc#23315]
### Describe the bug
Here is a clear and concise description of what the problem is:

When activating 'allow remote control via HTTP', there is a popup 'web server failed to start'

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Web Service should start
(Was working in 20230329 build)

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
Nothing significant found in debug log

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 Android TV 9 (firestick 4k max)
 - Kodi version:
Kodi 21 20230520

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by joseluismarti** [comment]
Right, the fix is on the way #23313
