### ISSUE TITLE
Autoplay of next movie in external player

### ISSUE THREAD

**Issue by dusan-ivanco** [xbmc/xbmc#23326]
### Describe the bug
When I play a video using an external player (VLC), the automatic playback of the next file after the previous one finishes doesn't work. However, when I use the internal player, everything works fine.

## Expected Behavior
After finishing the playback of a movie, the next movie should automatically start playing.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Google TV (Android 11)
 - Kodi version: 20.1

**Comment by sarbes** [comment]
Closed due to lack of feedback.
