### ISSUE TITLE
failed to create egl sync fence (EGL_BAD_ALLOC)

### ISSUE THREAD

**Issue by sryze** [xbmc/xbmc#23329]
### Describe the bug
Here is a clear and concise description of what the problem is:

After ~1min of playing a YouTube video (via the YT addon), Kodi always crashes for me with the following error:

```
error <general>: failed to create egl sync fence (EGL_BAD_ALLOC)
```

I'm running Kodi 20 GBM on an Orange Pi board (AllWinner H3) with HW acceleration enabled (which was made possible via [this ffmpeg fork](https://github.com/jernejsk/FFmpeg)).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expected Kodi to continue playing YT video stream.

## Actual Behavior

Crash

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
[kodi.log.zip](https://github.com/xbmc/xbmc/files/11573624/kodi.log.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I was trying to watch a live stream on YouTube through the addon.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Armbian Linux (kernel 5.15.93-sunxi)
 - Kodi version: 20.0.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Can you see if #23272 fixes this?

**Comment by sryze** [comment]
It works much better now with that patch, thanks!
