### ISSUE TITLE
1440x1080 HEVC Videos Are Stretched to 16:9 on Fire TV

### ISSUE THREAD

**Issue by bpoxy** [xbmc/xbmc#23328]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi on Fire TV devices stretches 1440x1080 HEVC videos to 16:9 rather than preserving the implied 4:3 aspect ratio, when the video stream does not specify DAR.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi preserves the aspect ratio implied by the video dimensions.

## Actual Behavior

Kodi stretches to 16:9, in the absence of an explicit DAR.

## Possible Fix

When DAR is missing, Kodi could calculate DAR based on width/height instead of defaulting to 16:9.

### To Reproduce

1. Play [H264.no.DAR.mp4](https://github.com/xbmc/xbmc/assets/7863845/58cd6529-0241-44fb-8f29-cda52c0ffdc6), notice 4:3 is preserved.  
2. Play [H265.no.DAR.mp4](https://github.com/xbmc/xbmc/assets/7863845/22a73be8-4ade-413a-9f7c-184a4aef76b7), notice 4:3 is not preserved.
3. Play [H265.with.DAR.mp4](https://github.com/xbmc/xbmc/assets/7863845/dde780ad-d222-4a60-921a-2081793a99dc), notice 4:3 is preserved.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/ayibiyedew.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

This seems to be specific to Fire TV devices as this problem does not occur on my Shield or Windows.
I believe it was introduced in v20 as I'm fairly certain I did not have this issue with Kodi v19.4.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fire OS 7.6.3.3
 - Kodi version: 20.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
The sample video has no aspect ratio defined, so the player is free to choose one (according to what I can find in the specs). So there is no bug. Kodi can't guess what the intended aspect is. 

A resolution of 1440x1080 is common for HDV, stretched to an 16:9 aspect, so the argument could be made to stretch it by default. 

Fix your files if you want them to play correctly.
