### ISSUE TITLE
Android IEC packer crashes with IllegalStateException when seeking

### ISSUE THREAD

**Issue by matejdro** [xbmc/xbmc#23325]
### Describe the bug
Here is a clear and concise description of what the problem is:

I just got a new Android device (Homatics Box R 4K Plus), and I cannot use Kodi IEC packer with it due to #23324. However, attempting to use Android IEC packer causes Kodi to randomly crash with `java.lang.IllegalStateException: Unable to retrieve AudioTrack pointer for getPosition()` exception while seeking.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should not crash

## Actual Behavior

Kodi crashes.

## Possible Fix

/

### To Reproduce

1. Enable Android IEC packer as a passthrough method
2. Play a video with audio track that uses passthrough
3. Seek around a video several times
4. Kodi will eventually crash

### Debuglog

The debuglog can be found here:

[crash2.log](https://github.com/xbmc/xbmc/files/11553236/crash2.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 11
 - Kodi version: Kodi (21.0-ALPHA1 (20.90.101) Git:20230523-9f0a7b71e3), but same happens on 20.1 stable.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
You want us to put try / catch around every JNI method we call? Even those that are documented exception free by Android?

**Comment by matejdro** [comment]
I was thinking more of the lines of putting try catch higher in the call stack, to catch any exceptions (in this case, at the seek event handler. Any exception that would happen during seek would be caught and playback would be stopped in response). But I admit that I'm not at all familiar with the Kodi's code so I'm not sure if this is even feasible. Will close the issue now.
