### ISSUE TITLE
Audio passthrough is out of sync with the video with Kodi IEC packer, possibly due to sample rate

### ISSUE THREAD

**Issue by matejdro** [xbmc/xbmc#23324]
### Describe the bug

I just got a new Android device (Homatics Box R 4K Plus), and Kodi on it experiences a really annoying issue: When playing any kind of audio (DD, AC3, Atmos) through passthrough, audio is out of sync with the video.

This only happens with Kodi (other Android applications, including VLC, work fine) and it only happens with the Kodi IEC packer. Using Android IEC Packer does not experience sync issues, but that has other issues.

Looking through logs, my suspicion is that it has to do something with the sample rate? Video that I played when collecting logs has an audio stream of 48000 Hz, but for some reason Kodi wants to output 192000 Hz:

```
2023-05-24 11:42:21.644 T:3349     info <general>: Creating audio stream (codec id: 86056, channels: 6, sample rate: 48000, pass-through)
2023-05-24 11:42:21.645 T:2956     info <general>: CActiveAESink::OpenSink - initialize sink
2023-05-24 11:42:21.645 T:2956    debug <general>: CActiveAESink::OpenSink - trying to open device AUDIOTRACK:AudioTrack (IEC)
2023-05-24 11:42:21.645 T:2956    debug <general>: CAESinkAUDIOTRACK::Initialize requested: sampleRate 192000; format: AE_FMT_RAW; channels: 2
```

Above is not the case with the Android IEC Packer (it properly picks 48000 Hz)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Audio should play in sync with video

## Actual Behavior

Audio is out of sync

### To Reproduce

1. Enable Passthrough
2. Play any video with passthrough audio

### Debuglog

The debuglog can be found here:

[Kodi IEC packer.log](https://github.com/xbmc/xbmc/files/11553085/Kodi.IEC.packer.log)
[Android IEC Packer.log](https://github.com/xbmc/xbmc/files/11553088/Android.IEC.Packer.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 11
 - Kodi version: Kodi (21.0-ALPHA1 (20.90.101) Git:20230523-9f0a7b71e3), but same happens on 20.1 stable.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
The samplerate of the input file has nothing to do with that. Kodi's IEC packing for eac3 simply uses 192 khz and two 16 bit channels, data is properly packed and padded. Reason for this is to also support 7.1 channel AC3.

VLC and others use RAW Format most likely, so you cannot compare that. Most likely the firmware of your box returns wrong delay information. Turn on Audio component logging and play that sample. Then it can be directly seen what the FW returns.

**Comment by matejdro** [comment]
Here are logs with audio component on:

[kodi.log](https://github.com/xbmc/xbmc/files/11553656/kodi.log)

**Comment by fritsch** [comment]
As expected. Search for Head-Position 17408. You see that your driver reports it's first own delay after roughly 800 Ms audio Data was added while telling us: my delay is 802.125 ms.

So most likely you are roughly half a second behind. I think the firmware throws the buffers away under the hood and continues with a fresh one :-) leaving us those wrong 500 ms.

Seem IEC mode is broken in your firmware, report to the vendor.

FireTV Cube 3rd gen has the same issue in IEC mode. Non official workaround here is reopening if Kodi realizes this buggy behaviour. Though that is no solution. Vendors shall fix their mess.

**Comment by matejdro** [comment]
Thanks will do. Until they respond, is there a way to override this value?

**Comment by fritsch** [comment]
You can try the cube workaround build from the forum, it might work on your device given it corrects itself like cube does it. Though that is then your personal luck, we don't mitigate vendor nonsense in Kodi.

**Comment by fritsch** [comment]
If you approach the vendor, also give them your adb logcat, there they will see potential reopening.

**Comment by matejdro** [comment]
Thanks a lot for your help.

**Comment by fritsch** [comment]
Can you try this: https://jenkins.kodi.tv/view/Android/job/android-arm-docker/2347/artifact/kodi-20230524-7d5be176-cube-master-armeabi-v7a.apk

and post a debuglog with it? Just want to see if - by chance - the cube workaround also works for this device

**Comment by matejdro** [comment]
I tried Cube build yesterday and it did resolve the issue (at least by my subjective perception, audio was not out of sync anymore). I can retry and post the logs if you want.

**Comment by matejdro** [comment]
Here you go: [kodi.log](https://github.com/xbmc/xbmc/files/11577086/kodi.log)

Not sure if this is AMLogic, both their site and utilities just mention Cortex A55:

https://www.homatics.com/products/box-r-4k-plus?variant=43212469698796

![image](https://github.com/xbmc/xbmc/assets/507922/246d1bb2-cc1f-4acc-9d94-05f9f40173fa)

**Comment by fritsch** [comment]
Yes. Thanks for your log. They might actually run the same BSP as the FireTV Cube and therefore might have the very same issue. Good that reopening and watchdogging "mititages" it else those devices would be unusable. If you wait for a vendor to fix something like this - IEC is still a total edge-case and not used by any content providers - you will wait forever.

To your log:
```
2023-05-26 18:12:09.171 T:11847    info <general>: Delay Current: 330.666667 ms
2023-05-26 18:12:09.171 T:11847   error <general>: Sink got stuck - ask AE for reopening
```
Jep, you see that I detect that there is a delay of 330.6 ms (+32 ms) already, but the sink did not move, while it already opened with a buffer of:
```
2023-05-26 18:12:09.403 T:11847    info <general>: Created Audiotrackbuffer with playing time of 170.750000 ms min buffer size: 131136 bytes
```
so that means, the sink did not want to move for twice the configured buffer time -> so I error out and just reopen. This game continues until the sink behaves properly.

And you might guess, that this is not a proper workaround. What I ask myself is though: If there is a underrun and cause of this the sink dies ... but I could not spot that in the adb when I looked last time.

**Comment by matejdro** [comment]
Thanks for checking it out.

I would really urge you to reconsider mainlining this sort of fix into main Kodi source.

Essentially, me (and it looks like bunch of other people) are looking for a device that can play streaming services through Kodi at 4K quality (since Kodi's UI and customizability is miles ahead of the official streaming service apps). This requirements pretty much rules everything out but Android boxes (because nothing else has the proper DRM support). 

Out of Android boxes, only proper branded box is the Nvidia Shield. But it's showing its age, last device from that line was released in 2019 and it's not really future proof to buy it (no AV1). That leaves out chinese boxes. On paper, some of these boxes, such as Homatics box in this issue, seem fine (AV1 support, plenty of RAM etc.) but they have those random firmware issues. 

As you mentioned, it will be difficult to get the manufacturer to fix the issues, since it's a very small edge case. Using RAW workaround also does not work (see the other thread about crashes). So my options are:

a) Get Nvidia Shield and forget about AV1, plus hope that Nvidia will still be making these in case it breaks
b) Get a chinese box and use 3rd party patch build and hope that build author keeps updating it
c) Get a Linux box and be limited to 1080p at best

Maybe it would be more future proof to just let the patch go into the mainline?

**Comment by fritsch** [comment]
Hehe - so I am then this chinese 3rd party patch guy :P
