### ISSUE TITLE
Advanced settings in GUI

### ISSUE THREAD

**Issue by thenicnic** [xbmc/xbmc#23340]
It would be cool if the settings like network bandwith usage and caching are parameters in the 'Expert' settings GUI.
Currently, they could be made via "advancedsettings.xml" (which is fine) but that's not very easy to access for someone who experiences an interrupted playback but is not that deep into the OS.
Plus, it would enable comfortable live tweaking.
Maybe with an auto-reset feature, if the settings are malicious.
Thanks for the great Kodi app!

**Comment by fuzzard** [comment]
We use the github issue tracker to track bugs only.

Feature requests can be made on the forums at https://forum.kodi.tv/forumdisplay.php?fid=9
