### ISSUE TITLE
Kodi crashes on Raspberry Pi OS Bullseye (64-bit)

### ISSUE THREAD

**Issue by libewa** [xbmc/xbmc#23354]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi crashes when installed on the latest Pi OS 64-bit using `apt`

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should display the splash screen and proceed to start.

## Actual Behavior

Kodi crashes

## Possible Fix

Make Kodi not crash on 64-bit Pi OS Bullseye.

### To Reproduce

1. Install Kodi:
```sh
sudo apt install kodi
```
2. Run Kodi:
```sh
kodi
```
3. Kodi requests superuser privileges
4. The screen turns black, and after a few seconds, you are returned to the desktop. The terminal window should display errors with the jack server

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/olalugowif.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Terminal output:
```
linus@raspberrypi:~ $ kodi
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ERROR: Unable to create GUI. Exiting
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspberry Pi OS bullseye
 - Kodi version: 19.4 - 166303c4f0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
As the log says
```
FATAL <general>: CApplication::CreateGUI - unable to init windowing system
```

When using gbm you cannot be using a windowing system. So your setup is invalid.

Please use the forum for support. https://forum.kodi.tv/
