### ISSUE TITLE
Samba on xbox one/nexus CRAZY log writes!! 

### ISSUE THREAD

**Issue by ohhdemgirls** [xbmc/xbmc#23353]
### Describe the bug
Here is a clear and concise description of what the problem is:

SMB logs spammed by xbox one/nexus client. Gigabytes of logs daily.....

I believe this is my issue as the xbox is windows based.. but there's no option to disable this on an xbox.
> https://groups.google.com/g/linux.samba/c/1jAOKw7ZSyk

I have 1600+ shows and 19,000+ movies so this has been running for days with no end in sight writing 1000s lines per second to the smbd logs. This serves no purpose to Kodi and just spams my logs and network with pointless traffic. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Not write insane logs and burn my ssds. 

## Actual Behavior

Writing insane logs and burning my ssds.

## Possible Fix

......

### To Reproduce

Kodi on xbox one client, samba share on linux server, load media in kodi, watch logs for days.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version: xbox/nexus

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ohhdemgirls** [comment]
Begging....

**Comment by lrusak** [comment]
Please post a debug log.

**Comment by ohhdemgirls** [comment]
> 

How would I go about creating and getting a debug log off the xbox? I'm not even sure any of this even shows up in the log honestly, I was looking around for logs or any activity in kodi while this was happening and couldn't find anything.

**Comment by lrusak** [comment]
> > 
> 
> 
> 
> How would I go about creating and getting a debug log off the xbox? I'm not even sure any of this even shows up in the log honestly, I was looking around for logs or any activity in kodi while this was happening and couldn't find anything. 

Did you check the documentation? https://kodi.wiki/view/Log_file

**Comment by thexai** [comment]
For Xbox the easy way is: https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

**Comment by thexai** [comment]
Closed as no debug logs provided (no useful info to know what happens)
