### ISSUE TITLE
"One or more items failed to play" - on Windows 10 (and Raspberry Pi 4, AND Mac)

### ISSUE THREAD

**Issue by Dochartaigh** [xbmc/xbmc#23361]
### Describe the bug
Playing movies OFFLINE, and commonly get the "One or more items failed to play" error.

## Expected Behavior
Video should play without error as it does in VLC, Plex, and EVERY other video player.

## Actual Behavior
I get the "One or more items failed to play" error and can NOT play/watch the movie.

### To Reproduce
1. Launch Kodi
2. Click on any video to play it
3. See "One or more items failed to play" error and can NOT play the video

### Debuglog
[https://pastebin.com/84Dexghm](https://pastebin.com/84Dexghm)

### Screenshots 
<img width="469" alt="Capture" src="https://github.com/xbmc/xbmc/assets/23370177/d0436b59-6974-4b27-9a7a-acc424f625f0">

## Additional context or screenshots (if appropriate)
This is an OFFLINE (NO internet) media library run off a laptop with an external USB 4TB hard drive, formatted ExFAT, used at our vacation home. We HAVE to have thumbnails and movie description to pick a movie, so after I scan the library back home (where I have internet), I use Settings > Media > Library > Export Library (tried 'Single File', AND 'Separate' options) to export all the thumbnails/metadata/descriptions to a folder on the external HDD so I can see those when offline.

Windows error log says something about an "InputStream: Error opening" "XFILE::CDirectory::GetDirectory - Error getting __movie name__" errors... FYI I can literally paste in the path from KODI's error log and it'll find the movie file EXACTLY where it's looking... it is not a drive or location/path error. Every other player (and Plex) plays the same files perfectly.

Doesn't seem to be a permission error either - I've tried 2x different HDD's, one of which I did chmod 777 in Linux to remove any permissions from ALL the movies/files.

This is NOT just a Windows error either - this same error persists on Raspberry Pi 4 running LibreELEC/Kodi first, and TWO different Mac laptops. On the Mac's I tried normal Kodi version, then 8x v20 and v21 "Nightly Development Builds" to no avail. RP4 and Mac's give me a different error than Windows though - those give me a "namespace" error which alludes to unsupported characters in file names... but they're all normal (DOES have spaces, periods, and dashes per usual naming conventions). It also seems like the ONLY fix for the "namespace" error is to disable the "export library" option, which I can't do, because then I wouldn't be able to pick out a movie to watch. Again, Windows doesn't seem to give this "namespace" error.

### Your Environment
Used Operating system:

 - [X ] Linux
 - [ X] macOS
 - [ X] Windows**
 **Windows 10 is the system this exact error log is from

 - Operating system version/name:
 - Kodi version:
(20.1.0) Git:20230312-289ec664e3)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Please ask your support question on the forum.
