### ISSUE TITLE
Disabling the screensaver via jsonrpc does not work.

### ISSUE THREAD

**Issue by Slomo17** [xbmc/xbmc#23397]
### Describe the bug
Here is a clear and concise description of what the problem is:

Disabling the screensaver via jsonrpc does not work.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When setting the screensaver via {"id":"1","jsonrpc":"2.0","method":"Settings.SetSettingValue","params":{"setting":"screensaver.mode","value":"none"}} to none the screensaver should disable.

## Actual Behavior

The GUI shows that the screensaver is set to 'none', also the entry in guisettings.xml is change correctly, but the sub settings of the screensaver (settings, preview, wait time ...) are not greyed out in the GUI. Instead of being disabled a blank screensaver activates after the set wait time.

## Possible Fix

make disabling the screensaver work as expected

### To Reproduce

1. Set any screensaver  
2. Disable screensaver via jsonrpc using {"id":"1","jsonrpc":"2.0","method":"Settings.SetSettingValue","params":{"setting":"screensaver.mode","value":"none"}}
3. Wait set 'wait time' for blank screensaver to activate

### Debuglog

The debuglog can be found [here](https://gist.github.com/Slomo17/9c9e3ce7d9674c4ebd7445482f5ef25b)
Disabling the screensaver via jsonrpc at 12:30, blank screensaver activates 1 min later with no entry in log file

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screensaver disabled manually via GUI:
![q66nGU4](https://github.com/xbmc/xbmc/assets/14056946/61352ffc-9f5a-4087-bec2-a845ff7782d9)
Screensaver disabled via jsonrpc:
![stBZo8p](https://github.com/xbmc/xbmc/assets/14056946/69133884-4243-4749-a9f5-4644222f21dd)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux (Libreelec)
 - [ ] tvOS
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC (official): 11.0.1 on Raspberry Pi 4b
 - Kodi version: 20.1.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by joseluismarti** [comment]
To disable the screensaver the parameter must be `"value":""` check it

**Comment by Slomo17** [comment]
Yes, you are right, thank you, i read [this forum post ](https://forum.kodi.tv/showthread.php?pid=2952956) where someone used the "none" value, therfore i never tried `"value":""`.  I will close the issue than.
