### ISSUE TITLE
Cannot read NFS4 mounts if running kernel version 6.3.7

### ISSUE THREAD

**Issue by graysky2** [xbmc/xbmc#23392]
### Describe the bug
Here is a clear and concise description of what the problem is:

When running linux kernel 6.3.7, kodi (Nexus branch) is unable to use read from NFS mounts.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

NFS mounts should work irrespective of kernel versions.

## Actual Behavior

When running linux kernel 6.3.7, kodi (Nexus branch) is unable to use read from NFS mounts.

### To Reproduce

1. Update to linux kernel 3.6.7
2. Try to access NFS4 mount

Here is `/etc/exports` on the box serving the content:
```
/srv/nfs         10.9.8.0/24(ro,fsid=root,no_subtree_check,insecure,async,all_squash,pnfs,anonuid=99,anongid=99)
/srv/nfs/movies  10.9.8.0/24(ro,no_subtree_check,insecure,async,all_squash,pnfs,anonuid=99,anongid=99)
```

### Debuglog

The debuglog can be found [here](https://gist.github.com/graysky2/62bcdd98ea9f69c6fee8082eac71008f)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I believe that this bug is unique to Kodi's implementation of NFSv4 because mounting the same export from the shell works fine/files are accessible.  See below.  If I attempt to access a file through Kodi's GUI, the bug manifests.

Here is on the same machine running kernel 6.3.7 where the bug is triggered in Kodi:
```
% mkdir ok
% mount.nfs4 10.9.8.112:movies ok
% mount | grep ok
10.9.8.112:/movies on /home/facade/ok type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.9.8.107,local_lock=none,addr=10.9.8.112)
```

I skimmed through the [stable-tree](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=v6.3.7&ofs=200) for 6.3.7 and found 2 commits with nfs in their title.  Just for kicks, I reverted both of them, built the kernel, booted into the kernel, and found that the bug in Kodi's GUI is not present.  The fact that I can mount from the shell without reverting those makes me think that this is a Kodi bug, not an upstream regression.

For reference, here are the two commits I reverted:
https://github.com/torvalds/linux/commit/c2d8941aef07d93e7f126e66c1132fbb9aa40888
https://github.com/torvalds/linux/commit/634fae934ebb6bbf9e2291aa883a18c19d5f4d1d

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux x86-64
 - Kodi version: Build from Nexus branch

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by graysky2** [comment]
I just skimmed through the [stable-tree](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=v6.3.7&ofs=200) for 6.3.7 and found 2 commits with nfs in their title.  I reverted both of them and found that this bug against Kodi is not present.  I am thinking this is an upstream regression but wanted to get some feedback from you guys first.

For reference, here are the two commits I reverted:

https://github.com/torvalds/linux/commit/c2d8941aef07d93e7f126e66c1132fbb9aa40888
https://github.com/torvalds/linux/commit/634fae934ebb6bbf9e2291aa883a18c19d5f4d1d

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.3.7&id=c2d8941aef07d93e7f126e66c1132fbb9aa40888

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.3.7&id=634fae934ebb6bbf9e2291aa883a18c19d5f4d1d

**Comment by graysky2** [comment]
@lrusak @thexai

**Comment by lrusak** [comment]
Maybe it's a bug in libnfs? Can you run the libnfs example programs?

**Comment by graysky2** [comment]
@lrusak - Like `nfs-ls` you mean?  Does that work on a pure nfsv4 export?  When I try it from a machine running an older kernel (ie one that should work) I do not get output.

```
% nfs-ls nfs://10.9.8.112/movies
Failed to mount nfs share : nfs_service failed
```

**Comment by graysky2** [comment]
@lrusak - Like `nfs-ls` you mean?  Yes, it works from a machine running the 6.3.7 kernel whereas kodi fails to read the files:
```
$ nfs-ls -D nfs://10.9.8.112/movies/?version=4
-rw-r--r--  1  1000   100          271 front.nfo
-rw-r--r--  1  1000   100          272 garage.nfo
-rw-r--r--  1  1000   100          258 floater.nfo
-rw-r--r--  1  1000   100           32 front.strm
-rw-r--r--  1  1000   100   1765630904 Title.1990.1080p.mp4
...
```

**Comment by graysky2** [comment]
> I skimmed through the [stable-tree](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=v6.3.7&ofs=200) for 6.3.7 and found 2 commits with nfs in their title. Just for kicks, I reverted both of them, built the kernel, booted into the kernel, and found that the bug in Kodi's GUI is not present. The fact that I can mount from the shell without reverting those makes me think that this is a Kodi bug, not an upstream regression.

>For reference, here are the two commits I reverted:
https://github.com/torvalds/linux/commit/c2d8941aef07d93e7f126e66c1132fbb9aa40888
https://github.com/torvalds/linux/commit/634fae934ebb6bbf9e2291aa883a18c19d5f4d1d

I reverted these one-at-a-time and tested.  I get the bug in both cases.  The bug is fixed only after reverting both commits.

**Comment by graysky2** [comment]
If I boot into kernel 6.1.34 (which has these two commits backported), there isn't a bug.  It is unique to the 6.3.x series of kernel.  Can anyone confirm this?

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.1.34&id=bd424277a1f86c41254d1068889908067d1f6aa5

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.1.34&id=4e5a5cda3dfd12ab7e0b77f0bd11834e09674227

**Comment by graysky2** [comment]
Happy to report that the bug is gone on the 6.4.x series of kernel.  Closing.
