### ISSUE TITLE
font not working properly

### ISSUE THREAD

**Issue by eddilara** [xbmc/xbmc#23402]
got a font that doesn't seem to work properly on kodi 20.1
it embedded in a mkv file
and kodi is installed on windows 10  (22h2...or whatever the newest one is)
[DFMrg9.zip](https://github.com/xbmc/xbmc/files/11742221/DFMrg9.zip)
works properly on MPC-HC 2.0.xx beta and other windows players

**Comment by CrystalP** [comment]
Please upload the debug log requested by the template. It's required for us to find out a lot of information about the context without asking a thousand questions.

See instructions to provide a debug log: https://kodi.wiki/view/Log_file

You provided a font file but did not explain if it fails to load from one specific video, or any video it's attached to, or other specifics that may be relevant.

**Comment by Supersaiyajin** [comment]
O9w k9utrr kół holly y0v9 I pl i euh oui mais c'est. Viky kk i9ui mais
040c1 je de il wt 34 ok i go. nie e g4py. 0v v9m

śr., 14 cze 2023, 08:10 użytkownik techguru ***@***.***>
napisał:

**Comment by CrystalP** [comment]
Come again?

**Comment by eddilara** [comment]
> Please upload the debug log requested by the template. It's required for us to find out a lot of information about the context without asking a thousand questions.
> 
> See instructions to provide a debug log: https://kodi.wiki/view/Log_file
> 
> You provided a font file but did not explain if it fails to load from one specific video, or any video it's attached to, or other specifics that may be relevant. Are you able to find out if it's Windows specific or shared with other platforms?

well its newest windows build 22h2 or whatever
on kodi 20.1
I can't be sure if the file works on other files
I haven't checked if it works on linux builds of kodi either
my educated guess is that cause its a TTC file...kodi isn't sure what font inside the TTC to load
I do alot of anime subbing....and in aegisub (https://github.com/arch1t3cht/Aegisub)...the font shows properly....also works on MPC-HC 2.0.x and MPC-BE (newest build)....I think it works properly on VLC as well...haven't double checked

also I used MKVTOOLNIX 75 to mux the font in case that matters

**Comment by CastagnaIT** [comment]
as kodi wiki there is support for ttf and otf, so not ttc
i think we can try test add ttc extension support but for kodi 21

**Comment by eddilara** [comment]
> as kodi wiki there is support for ttf and otf, so not ttc i think we can try test add ttc extension support but for kodi 21

ok I'll test it with 21 when its closer to release

**Comment by CastagnaIT** [comment]
can you share a chunk of a mkv? if not possible at least a complete kodi log with debug enabled
i need to have a complete situation because ttc can contains more fonts
and i need to compare at least with other player to know if works correctly

**Comment by eddilara** [comment]
> can you share a chunk of a mkv? if not possible at least a complete kodi log with debug enabled i need to have a complete situation because ttc can contains more fonts and i need to compare at least with other player to know if works correctly

the file Im testing it on is pretty big
guess I could upload it to a fileshareing site
