### ISSUE TITLE
[Master] Build fails on linux since d445d49176e6617ab63faffe4a973d5d2e04a938 - lzo2 not found

### ISSUE THREAD

**Issue by coffeinflash** [xbmc/xbmc#23424]
### Describe the bug
Since commit d445d49176e6617ab63faffe4a973d5d2e04a938 building from source fails as lzo2 cannot be found anymore:

`[   32s] CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
[   32s]   Could NOT find Lzo2 (missing: LZO2_LIBRARY)
[   32s] Call Stack (most recent call first):
[   32s]   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
[   32s]   cmake/modules/FindLzo2.cmake:22 (find_package_handle_standard_args)
[   32s]   tools/depends/native/TexturePacker/src/CMakeLists.txt:16 (find_package)`

Before this commit building worked fine. The headers of the library are included of course:
BuildRequires:  pkgconfig(lzo2)
(https://build.opensuse.org/package/view_file/home:Herbster0815:HTPC/kodi/kodi.spec?expand=1)

## Expected Behavior
Lzo2 headers should be found and build should continue.

### To Reproduce
Build kodi from source:

%cmake \
    -DVERBOSE=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DGIT_VERSION="%{_git_version}" \
    -DENABLE_EVENTCLIENTS=ON \
    -DENABLE_INTERNAL_CROSSGUID=OFF \
    -DENABLE_INTERNAL_CDIO=OFF \
    -DENABLE_INTERNAL_FLATBUFFERS=OFF \
    -DENABLE_INTERNAL_FMT=OFF \
    -DENABLE_INTERNAL_FSTRCMP=OFF \
    -DENABLE_INTERNAL_RapidJSON=OFF \
    -DENABLE_INTERNAL_SPDLOG=OFF \
    -DENABLE_INTERNAL_DAV1D=OFF \
    -DENABLE_INTERNAL_UDFREAD=OFF \
    -DENABLE_INTERNAL_GTEST=OFF \
    -DENABLE_INTERNAL_KISSFFT=OFF \
	-DENABLE_AIRTUNES=OFF \
	-DENABLE_DVDCSS=OFF \
    -DENABLE_PULSEAUDIO=OFF \
    -DENABLE_PIPEWIRE=OFF \
    -DENABLE_MYSQLCLIENT=OFF \
    -DENABLE_MARIADBCLIENT=ON \
    -DENABLE_GOLD=OFF \
    -DENABLE_MOLD=OFF \
    -DCORE_SYSTEM_NAME=linux \
    -DAPP_RENDER_SYSTEM=gles \
    -DCORE_PLATFORM_NAME=gbm \
    -DENABLE_INTERNAL_FFMPEG=ON \
    -DFFMPEG_URL="%{SOURCE9}" \
    -DENABLE_INTERNAL_CEC=OFF \
    -DENABLE_INTERNAL_NFS=OFF \
    -DENABLE_INTERNAL_PCRE=OFF \
    -DENABLE_INTERNAL_TAGLIB=OFF \
    -DENABLE_OPENGLES=ON \
    -DENABLE_VAAPI=ON \
    -DENABLE_VDPAU=OFF \
    -DUSE_LTO=OFF \
    -DBUILD_SHARED_LIBS=1 \
    -DENABLE_TESTING=OFF \
    -DENABLE_DEBUGFISSION=OFF

### Debuglog

The buildlog can be found here: https://build.opensuse.org/package/live_build_log/home:Herbster0815:HTPC/kodi/openSUSE_Tumbleweed/x86_64

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: openSUSE Tumbleweed x64
 - Kodi version: current master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by coffeinflash** [comment]
Fixed by pull request #23428

**Comment by tomachinz** [comment]
I also got on Kubuntu trying to compile for the first time, I will try this pull request https://github.com/xbmc/xbmc/pull/23428 shortly.

```
-- Found JsonSchemaBuilder: /home/tom/kodi-build/build/bin/JsonSchemaBuilder
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find Lzo2 (missing: LZO2_LIBRARY LZO2_INCLUDE_DIR)
Call Stack (most recent call first):
/usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
cmake/modules/FindLzo2.cmake:22 (find_package_handle_standard_args)
tools/depends/native/TexturePacker/src/CMakeLists.txt:16 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/tom/kodi-build/CMakeFiles/CMakeOutput.log".
```

**Comment by howie-f** [comment]
@tomachinz try `apt -y install liblzo2-dev`
