### ISSUE TITLE
[Feature Request] Flip and Scroll Reversed for Horizontal Fixed/Wrap List Container

### ISSUE THREAD

**Issue by DevGeniusCode** [xbmc/xbmc#23427]
The addition of a new feature to the Horizontal Fixed/Wrap List Container component in Kodi. This feature aims to enable the flipping of the list and scrolling in a reversed direction, specifically from right to left. The implementation of this feature would greatly benefit users who utilize right-to-left languages and allow for proper display alignment.

**Feature Description:**
The proposed feature involves two key functionalities:
1. Reverse the Order of the List: When the Horizontal Fixed/Wrap List Container is in the horizontal direction, the list's order should be reversed. By reversing the order, items that were originally started on the left side will now appear on the right side, ensuring proper alignment for right-to-left languages.
2. Reverse Scroll Direction: The list should start from the "end" and scroll towards the "beginning," allowing users to scroll from right to left.
3. When entering the list, the first item should be in 'focus', and the other items to the left, not to the right. (Picture 3).

**Rationale:**
The addition of this feature is crucial for supporting right-to-left languages and accommodating users who require proper display alignment. Currently, although I have managed to build an XML to display the list in a right-to-left manner, the scrolling direction remains reversed. By implementing the proposed feature, Kodi can provide a complete solution for right-to-left language users, ensuring a seamless and intuitive user experience.

**Implementation Suggestions:**
Here are some suggestions for implementing this feature:
- Add a new attribute or option to the Horizontal Fixed/Wrap List Container component, such as "reverseOrder" or "rightToLeftMode."
- When the attribute/option is enabled, the list's order should be reversed, and the scrolling direction should start from the right side, moving towards the left side.

I would like to express my appreciation for the incredible work the Kodi development team has done in creating and maintaining such a versatile media center. I genuinely believe that the suggested feature would significantly enhance Kodi's usability for right-to-left language users.

[Attached: Picture illustrating the desired flipped and reversed scroll behavior for the Horizontal Fixed/Wrap List Container]
You will notice (apologies for the language) in both pictures that the (small) posters appear in the same order, although in the second 
picture below they should be reversed.

![image](https://github.com/xbmc/xbmc/assets/136935333/ad617138-2924-4ce9-8e94-2557dd2387d9)
Orginal.
![image](https://github.com/xbmc/xbmc/assets/136935333/c792a18e-451a-4ff4-a9cf-7b443b878edc)
Right mode

In this picture, you can understand that even though I placed the poster on the right side, the other items are still to the right, and not to the left.
![image](https://github.com/xbmc/xbmc/assets/136935333/861c7d44-9372-4acf-bd07-24d95da19ee9)

**Comment by fuzzard** [comment]
We dont take feature requests on github, its only for tracking issues with the code.

You can submit feature requests on the forum at https://forum.kodi.tv/forumdisplay.php?fid=9
