### ISSUE TITLE
🖐️Failed Installations (Inpustream...)

### ISSUE THREAD

**Issue by victore447** [xbmc/xbmc#23436]
![155](https://github.com/xbmc/xbmc/assets/48101775/128e6d55-2882-4532-b909-9dbfc94ed509)  **Hello,**
 It has been several months (with Kodi Nexus) that it is impossible to install Pvr Iptv simple client on another device (Android Box TV) when backing up via Backup & EzMaintenance+ addons. Even manually via Zip files.☝️This  does not work until several days later (+ 3 days).
![Pvr 20230623_190151](https://github.com/xbmc/xbmc/assets/48101775/9f61d97d-302f-422b-96ec-b7c8b8ec527e)

 ☝️**Once it worked when I changed my IP address via Vpn etc...And even now it doesn't change anything.**
![Pvr 20230623_190257](https://github.com/xbmc/xbmc/assets/48101775/82d9807d-3a8b-4da1-b824-e0d0de49564a)

 👆**The same is true for the Inputream Adaptive, Inputream.ffmpegdirect, Rtmp inputream etc. add-ons.**
![Inputream 20230623_180913](https://github.com/xbmc/xbmc/assets/48101775/f92b43d4-70d8-43c9-a425-3e80c167a327)

 **Thank you for your answer** ✔️

**Comment by enen92** [comment]
Please respect the issue template and provide a log file.
Although your reference to ezbackup (whatever that is) and VPN usage probably indicates you have a high bloated Kodi installation with add-ons provided by third parties. This quite of rings the alarms...
The log will tell but this issue will most likely be closed (not a Kodi core issue).

**Comment by victore447** [comment]
🖐️![46](https://user-images.githubusercontent.com/48101775/236531040-06b24a9a-6ac3-467d-b561-b1928058f1f2.gif)
[kodi.log](https://github.com/xbmc/xbmc/files/11850974/kodi.log)

**Comment by enen92** [comment]
Yeap you simply have too much crap (wizards et all). We do not provide support for that here (nor in any Kodi official site)

**Comment by victore447** [comment]
![146](https://github.com/xbmc/xbmc/assets/48101775/7563ac35-3ff1-4005-936d-218f61b04c83) **No, No,No,** 
I am not a Kodi novice and have been using it every day for over 10 years to watch TV, Movies .... Even with a new Kodi weighing less than 300 MB this problem is  here, here are the logs of the new Kodi
 👉
 👉.        ✔️
