### ISSUE TITLE
Seeking issues on latest nightly

### ISSUE THREAD

**Issue by MishaIsay** [xbmc/xbmc#23472]
### Describe the bug
Here is a clear and concise description of what the problem is:
When video is played from SMB, seeking takes too long. The issue appeared on "kodi-20230618-2a2bbd01-master-armeabi-v7a.apk", "kodi-20230617-22aa5f16-master-armeabi-v7a.apk" works correctly.

I'm not sure, if problem is exclusive to playback from SMB source, I don't have another one to test. Seems that people reported the same issue in comments [here](https://github.com/xbmc/xbmc/issues/23431#issuecomment-1605589495).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Seeking happens (almost) immediately, as it does on "kodi-20230617-22aa5f16-master-armeabi-v7a.apk".

## Actual Behavior
Seeking takes quite some time.

### To Reproduce

1. Play video file from SMB
2. Seek a few minutes forward

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/gefejuleki.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 11
 - Kodi version: kodi-20230702-4dcaf863-master-armeabi-v7a.apk

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Yes. Think so too. Nice catch.

**Comment by MishaIsay** [comment]
Seeking in build provided [here](https://github.com/xbmc/xbmc/pull/23414#issuecomment-1619087300) works correctly.

**Comment by neo1973** [comment]
Thanks for confirming @MishaIsay. The problematic PR was reverted on master (see #23475) and the next nightly hopefully works again.
