### ISSUE TITLE
Steam Deck regularly crashes a few moments after launch

### ISSUE THREAD

**Issue by ShadwDrgn** [xbmc/xbmc#23483]
### Describe the bug

Here is a clear and concise description of what the problem is:

When Opening Kodi for the first time in some period of time (not sure the exact period but usually around 48 hours or more) Kodi crashes soon after it's opened. If you then open it again it works totally  fine. I SUSPECT this has to do with the jellyfin addon, but not sure if I should still post a bug report here anyway or not. I believe this may be during library sync, but not positive about that either.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should load up and stay open without crashing.

## Actual Behavior

Kodi freezes for a few moments then crashes

### To Reproduce

Unfortunately reproducing this isn't going to be simple. I can only give steps that would reproduce this for ME, but since it seems a little unpredictable and i didn't see any other reports it may not be reliable.
1. Install jellyfin addon
2. Sync library
3. Watch something so library changes
4. mark some shows watched or unwatched so things change
5. Close kodi
6. Repeat 3 and 4 from jellyfin webui
7. Wait a while (possibly up to 2 days sadly) and during this time mark various things watched or unwatched and/or remove/add episodes or movies to jellyfin
8. open kodi
9. Kodi starts up, but then in a few seconds freezes then crashes.

### Debuglog

The debuglog can be found here:

Debug log AND crashlog both found here:
https://cloud.1ez.us/index.php/s/wa7qcZapn4x4nBf

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Jellyfin addon suspected contributing to this bug. Will cross-post a bug in their issue tracker as well and add link here once posted.
https://github.com/jellyfin/jellyfin-kodi/issues/753

### Your Environment
Used Operating system:

 - [x] Linux  (steam deck)

 - Operating system version/name:
 - Kodi version: 20.2 Nexus (Flatpak) 6/28/23

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
```
gdb not installed, can't get stack trace.
```

Also this looks suspicious as it's spammed a lot.
```
2023-07-06 17:56:18.281 T:86      debug <CAddonSettings[0@plugin.video.jellyfin]>: trying to load setting definitions from old format...
2023-07-06 17:56:18.282 T:86      debug <CSettingsManager>: requested setting (LastIncrementalSync) was not found.
2023-07-06 17:56:18.282 T:86      debug <CSettingsManager>: requested setting (SyncInstallRunDone) was not found.
2023-07-06 17:56:18.282 T:86      debug <CSettingsManager>: requested setting (groupedSets) was not found.
2023-07-06 17:56:18.282 T:86      debug <CSettingsManager>: requested setting (platformDetected) was not found.
```

**Comment by ShadwDrgn** [comment]
I'm not sure if I can install gdb without turning on developer mode and altering the RO fs on steam deck. Do I need to do this? Perhaps I can install something from flatpak that will add gdb for flatpak kodi? I do have jellyfin installed on my android tv as well and it's also version 20.2 i believe and does not have this issue. I  don't know if that helps in any way.

**Comment by ShadwDrgn** [comment]
I take it this being closed means its fixed or confirmed not a Kodi problem but a jellyfin add-on problem?

**Comment by lrusak** [comment]
There is no way to progress with this issue without a stack trace.

**Comment by ShadwDrgn** [comment]
If someone can walk me through getting whatever i need to make a stacktrace appear in these logs on steam deck with kodi flatpak, i'll be happy to give it a shot :)

**Comment by oddstr13** [comment]
The `trying to load setting definitions from old format` message has been around forever, and we've written that off as normal behavior.

This issue was likely closed due to missing gdb and thus no traceback in the logs, giving the devs little to go on in regards of debugging the issue.
