### ISSUE TITLE
Video with external ass subtitle + Override Subtitles Fonts will result in wrong position of subtitle

### ISSUE THREAD

**Issue by sdugoten** [xbmc/xbmc#23481]
### Describe the bug

It used to work correctly I believe, and the newest version of Kodi have such weird problem.  I usually turn on "Override Subtitles Fonts" in Subtitle setting so that I can make the font larger and easier to read.   There is no other way to make the font  larger and able to adjust the font size unless you turn on "Override Subtitle fonts" option.

Recently, I found out any video with external ass subtitle would make the subtitle hide at the upper screen like below

sample ass subtitle file.
[test.zip](https://github.com/xbmc/xbmc/files/11959702/test.zip)

## Expected Behavior

The subtitle should stay at the bottom even when "Override Subtitle fonts" is enabled.

## Actual Behavior
There is no way to adjust the subtitle position even if you try to use video calibration to adjust it.

## Possible Fix
The only work around I can do right now is to change the "Video setting > Orientation" when the video is playing to something else, and then flip it back to value "From metadata" would temporary fix the issue.

### To Reproduce

1.  Setting > player > subtitles > override subtitles fonts and turn it on
2. Load up any video and use the attached ass subtitle file and play the video (change the name of the ass file to match your video
3. Fast forward to sometime that have subtitle.  
4. You will see subtitle stay on the top like the picture above.

### Screenshots 

you can see the subtitle hide at the upper part of the screen
![image](https://github.com/xbmc/xbmc/assets/7108552/ccb52ec7-e109-485b-9cbd-5af299089849)

### Your Environment
Used Operating system:

 - [X ] Android TV
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.1
 - Default skin comes with Kodi.  Everything is stock install and nothing fancy.  The only addon I added is keymap editor.
 - All settings is pretty much default except Override subtitle fonts is enabled.  

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by scott967** [comment]
I can reproduce the issue with the supplied .ass file.  I was playing around with the file in subtitle edit, and found if I saved the file it then played correct position with font override set in Kodi 21 win 10 x64 built through 2023-07-05 90e7b21cb3.  So looked to see what subtitle edit did, and what I found was it added the following in 
[Script Info]
...
PlayResX: 718
PlayResY: 472

Those parameters taken from test video file I was using in subtitle edit.  With those missing the ass sub position is as reproduced in the issue.

**Comment by CastagnaIT** [comment]
yeah i have already see this and was because `PlayResX` `PlayResY` was wrong or missing
as in the sample subtitle provided
atm i cant say if exist a way to workaround it

**Comment by sdugoten** [comment]
> yeah i have already see this and was because `PlayResX` `PlayResY` was wrong or missing as in the sample subtitle provided atm i cant say if exist a way to workaround it

I think it used to be working in Kodi with or without `PlayResX` `PlayResY`.   The reason is that these .ass subtitle file is pretty standard when you download it off the Net and it works correctly before.  It works on most other vide player as well.

**Comment by sdugoten** [comment]
The working workaround steps like below

1. Play the video and keep it playing, do not stop or pause it.
2. "Video setting > Orientation" 
3. Change the value  "From metadata"  to something else like 180".  And then flip it back to  "From metadata"
4. Exit the setting menu and go back to the video, the video should be still playing without pause or stop.  
5. You should now see the subtitle works correctly.........until you stop the video and reload it.

Based on what you see the procedure above, you could somehow guess that the video loading process mess up the subtitle position

**Comment by scott967** [comment]
Just digging around I do see this in libass:

https://github.com/libass/libass/blob/1a599b1db748dfc07df98cd37d8603edb87da2fd/libass/ass.c#L1768-L1776

**Comment by CastagnaIT** [comment]
I am aware of that resolution fallback
i tried debug but i was unable to find nothing in our libass code

**Comment by sdugoten** [comment]
> I am aware of that resolution fallback i tried debug but i was unable to find nothing in our libass code

I am not sure if that helps.  For step 1 above on the workaround, if you pause the video and do the rest of the steps, it would NOT work.  I have no idea why I have to keep the video playing while perform step 2 to step 5 in order to get the workaround to work properly.

**Comment by pacifyin** [comment]
It is a bug.
I fixed it already.

replace this code to DVDSubtitlesLibass.cpp

line:465
   // ass_set_line_spacing do not scale, so we have to scale to frame size
    if (m_subtitleType != NATIVE)
    {
      ass_set_line_spacing(m_renderer,
                         lineSpacing / playResY * static_cast<double>(opts.frameHeight));
    }

**Comment by CastagnaIT** [comment]
thanks for the hint, looks like that files without  `PlayResX` `PlayResY`
libass yes should fallback to his default values, but dont fill ass track properties
and this cause broken scale calculations

strange that in my initial investigations i didn't see it
or there was something else that didn't convince me idr atm
i opened a new fix PR i will investigate again soon

**Comment by pacifyin** [comment]
Thanks a lot.
I remake it use CastagnaIT's source code, today.
It is worked fine.
