### ISSUE TITLE
xbox wireless controller (carbon black, bluetooth) not working on Kodi

### ISSUE THREAD

**Issue by JRLS** [xbmc/xbmc#23485]
### Describe the bug
I have Kodi installed on nvidia shield TV pro (500GB), working fine
nvidia shield TV controller is working fine in Kodi.
I paired an xbox one controller with the shield with bluetooth
it's an carbon black, wireless/bluetooth xbox controller, link :  https://www.mediamarkt.de/de/product/_microsoft-xbox-wireless-controller-carbon-black-fur-android-pc-xbox-one-xbox-series-x-2851317.html

On the shield the controller is working fine, also with youtube, games, menu navigation, etc.
so, it's working great.

When i start kodi, the xbox controller is not working under kodi. No buttons work, d-pad not working, triggers not working, shoulder buttons not working, etc

## Expected Behavior
I expect the controller to work fine under Kodi, since the controller is working fine with any other application

## Actual Behavior

Buttons do not work, d-pad not working, triggers not working, shoulder buttons not working, sticks not working
i'm pressing buttons, which seem to show up in the debug log, and also the controllers seems recognized according to the debug log, however, it's not working

## Possible Fix

Maybe, i new periphical lib is needed for this controller?

### To Reproduce

1. on the shield menu, start kodi with the xbox controller
2. when in kodi, the controller does not work

### Debuglog

The debuglog (from kodi log) can be found here:
https://[jrxs.net/KodiLog/xbox_controller_kodi.txt](https://jrxs.net/KodiLog/xbox_controller_kodi.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android ARM 64-bit
 - Kodi version: Kodi (20.2 (20.2.0) Git:20230629-5f418d0b13). 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Did you try configuring the controller?

https://kodi.wiki/view/HOW-TO:Configure_controllers

**Comment by JRLS** [comment]
yes, but the controller does not register anything
so, nothing in that menu is working, so i cannot map anything

or oare you saying i need to change joystick.xml file?
if so, how do i change it, so it works with this controller?

**Comment by JRLS** [comment]
why did you close this issue?

**Comment by lrusak** [comment]
> why did you close this issue?
> 
> 

Please use the forum for support. https://forum.kodi.tv/
