### ISSUE TITLE
Server/NAS remote path access problem since installing Nexus version 20

### ISSUE THREAD

**Issue by Skyline-007** [xbmc/xbmc#23493]
Good morning

Since installing Nexus version 20

I am having a problem with adding source and my remote paths from my server.

All my sources are on the same server.

I no longer have access to some of my remote paths (my sources) from my server.

Here are my remote paths from my server

See picture:
![Sans titre2](https://github.com/xbmc/xbmc/assets/108820368/22c0cda7-4854-4687-8e0a-d3a36b6f545c)

I don't have access to these remote paths:
ftp : // My server address : 21 / 1 Videos summer vacation
ftp : // My server address : 21 / 2 Videos winter holidays

Here is the error message:
![Sans titre1](https://github.com/xbmc/xbmc/assets/108820368/3cb74702-fea5-423c-9141-f29390898297)

But I do have access to the last remote path added last from my server:
ftp : // My server address : 21 / Video

![Sans titre](https://github.com/xbmc/xbmc/assets/108820368/d4a41a4f-fcdb-4625-86e8-fbabe5192b8e)

There must be an error that has crept in somewhere ?

Because before I had access to all my remote paths from my server on older versions of Kodi.

And I'm not the only one to be affected by this problem other people have the same problem to access their remote paths with their server and their NAS only the last source to add is accessible.

Thank you in advance for your answers

Thanks again for all the work you have done

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
This bug report is useless: 

Things that helps to identify a bug: include debug log (not included), include basic info as OS/platform used (not specified).

Things that not helps: 

> And I'm not the only one to be affected by this problem other people have the same problem to access their remote paths with their server and their NAS only the last source to add is accessible.

Please use forum for support https://forum.kodi.tv/forumdisplay.php?fid=111 on the appropriate platform.
