### ISSUE TITLE
In kodi-21.0-ALPHA2 (Git:20230709-1c65bbbe61), when --windowing=gbm, only the mouse works, but not the keyboard

### ISSUE THREAD

**Issue by JustAnotherHumanBeing** [xbmc/xbmc#23497]
If I load kodi-21.0-ALPHA2 (Git:20230709-1c65bbbe61) on the bare console (--windowing=gbm), then only the mouse will work in kodi, but not the keyboard. Why is that? According to what I noticed, the mouse will rely on /dev/input/event* when kodi is started on the bare console. Why can't the keyboard do the same thing in such a case? In kodi.log, I don't see anything that explains the cause of the problem. Please fix this bug, so I would be able to use both the mouse and the keyboard when running kodi on the bare console.

**Comment by lrusak** [comment]
Please use the forum for support. https://forum.kodi.tv/
