### ISSUE TITLE
STRM Playlist regression(!?) on current master branch, playback dont start

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#23502]
### Describe the bug
Here is a clear and concise description of what the problem is:

This is a fake STRM just for test purpose
```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
https://www.dropbox.com/s/p0dq75hf05s2szc/segtimeline_live_ast.mpd?dl=1
```
usually i play it in this way
1) add the strm to a folder
2) add the folder to favourites
3) go to kodi main menu Favourites, open the folder, play the STRM

this now dont works anymore and print
`PLAYLIST::CPlayListPlayer::Play: ListItem type must be audio or video type. The type can be specified by using ListItem::getVideoInfoTag or ListItem::getMusicInfoTag, in the case of playlist entries by adding #KODIPROP mimetype value.`

where old nightlies run ISAdaptive (without play content because its fake)

this use case seem broken starting from PR #23460

## Possible Fix

i have seen something weird around here
i havent test i do not know if this is intentional
https://github.com/ksooo/xbmc/blob/master/xbmc/video/windows/GUIWindowVideoBase.cpp#L1083-L1096
there is a CFileItem copy but GetPlaylistPlayer().Play use the Ptr one that should have properties unchanged

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/dufafepiwe.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: master branch 1c65bbbe61e3dfb4b832d3baa431001551bf7520

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@ksooo maybe since it concerns favourites
