### ISSUE TITLE
Flash/out of sequence picture when skipping/changing audio track of some HEVC streams decoded with dxva

### ISSUE THREAD

**Issue by CrystalP** [xbmc/xbmc#23518]
### Describe the bug

There are unexpected screen flashes when seeking in some videos decoded by dxva decoder on separate d3d device.

## Expected Behavior

No flash when skipping or changing the audio track.

## Actual Behavior

The screen flashes, it looks briefly like out of sequence frames of the video before normal playback resumes.

## Possible Fix

Something seems to be wrong with the separate d3d device for decoding and the way surfaces are shared between the devices.
Disabling the separate device and forcing the use of the main device gets rid of the problem and dxva decoding then behaves the same as software decoding (ie no flash/out of order frames).
Maybe something is not flushed / not cleared on skip?

### To Reproduce

See [sample here](https://drive.google.com/file/d/1zf7Qe6UvfPGAryiVR-5DtAaR939Mn36y/view?usp=sharing)
(access granted to Kodi team email addresses)

1. play sample with dxva deconding on, on a computer that supports the separate device for decoding
2. skip forwards or backwards 10 sec > observe flash
3. change audio track > observe flash

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/cularokiza
Contains a few skips forward, then backward.

### Screenshots 

I haven't been able to capture the issue as screenshot.

## Additional context or screenshots (if appropriate)

Happened with AMD igpu. Not observed on Intel 13th generation.

This seems to happen more often for UHD BR m2ts files, is less pronounced on remuxes of same m2ts to mkv, and not on reencodes.

Copying afedchin and thexai since they both worked last on the separate device for decoding. Hopefully they remember how this works and have ideas how to fix.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 22H2
 - Kodi version: at least 20 and 21 up to current master.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
This video is Dolby Vision but incorrectly muxed:

Basically are two options:

1. Use MakeMKV that combines regular HDR10 video track and DV video track in one video track. These videos can be played with devices that supports DV i.e, Shield (in DV) AND in devices that not supports DV (Windows PC) in HDR10 mode.

2. Use MKVmerge and keep only 3840x2160 video track. These videos are only HDR10 as MKVmerge not supports yet create mkv's with HDR10 and DV in the same video track. But with MKVmerge you can remux these combined DV/HDR10 video tracks if created previously with MakeMKV.

Note that I not have access to video sample because I'm not using kodi Team email but regular Gmail.

**Comment by thexai** [comment]
> Happened with AMD igpu. Not observed on Intel 13th generation.

Then maybe is nothing to fix and this is another "AMD only driver bug"

**Comment by CrystalP** [comment]
Opened the permissions, the sample is now a remux with just the main video track per your suggestion.

The problem happens for the m2ts file straight from the UHD BD. Not some single-track dovi remux. I tried 14 discs and 10 of them show the issue.
The issue remained exactly the same after remuxing just the main video track (see the sample)
I wasn't sure how to cut a piece of the m2ts but since the same problem happens with the remux that didn't seem necessary.

Depending on the video, it looks like a bright flash or a few frames from the scene decoded before skipping.

The problem doesn't seem to be in the decoding itself because there is a good result when forcing dxva decoding on the main d3d11 device (with local code change).
The problem doesn't seem to be with the rendering either, because the problem shows in the same way with pixel shaders or dxva render method.

With the facts above it seems to me that the problem is likely somewhere in the code dealing with the separate d3d11 device.

Yes AMD behaves differently from Intel but it's a little early to call it a bug in the driver.

**Comment by thexai** [comment]
> I wasn't sure how to cut a piece of the m2ts 

with TsMuxer

![tsMuxer](https://github.com/xbmc/xbmc/assets/58434170/916c6bd6-52fc-433b-a867-a493eaacb6b1)

https://www.videohelp.com/software/tsMuxeR

**Comment by thexai** [comment]
You may try:

- Use only one display (no extended displays).
- Set Vertical Refreesh Sync ON in video driver settings.
- Force multi-threaded protection always enabled:
https://github.com/xbmc/xbmc/blob/022ef38abf96bdf8e2834259e0c147a9ef1161bb/xbmc/cores/VideoPlayer/DVDCodecs/Video/DXVA.cpp#L377-L384

- Force `m_DXVA2SharedDecoderSurfaces` OFF
https://github.com/xbmc/xbmc/blob/022ef38abf96bdf8e2834259e0c147a9ef1161bb/xbmc/rendering/dx/DeviceResources.cpp#L1157-L1161

Note that this still allows use different d3d device for decode although with less efficient "copy surface" method.

**Comment by CrystalP** [comment]
[sample as m2ts](https://drive.google.com/file/d/1RuGEfhcPIEhJa0Trb2kJLOwA7_K58Gho/view?usp=sharing) - exact same problem

* single screen: no change
* VSync: always on
* SetMultithreadProtected(1): no change
* SharedDecoderSurfaces OFF: no change
* a couple more Flush() before and after the CopySubresourceRegion: slightly better for forward skip (sometimes no unexpected frame), no change for backwards skip.

**Comment by CrystalP** [comment]
Found a way to cure it in the "copy surface" path in the code lines you pointed earlier
Both Flush() and CopySubresourceRegion() are asynchronous, the execution doesn't actually wait.
With the addition of a proper GPU wait (based on ID3D11Query), no more flashes/wrong frame.

I need to find a similar place in the code of the "shared surface" path to apply a similar fix, any clues?

**Comment by thexai** [comment]
In this case there is no similar code because the surface is not copied. There is only one circular decoding buffer of 16 - 32 surfaces and the same surfaces used for decoding (already in video memory) are used for rendering. It is the most efficient method of all.

This code initializes one of 3 surfaces methods:

https://github.com/xbmc/xbmc/blob/fc0833e5bded27c33cdf65bc98556db4e825d60b/xbmc/cores/VideoPlayer/DVDCodecs/Video/DXVA.cpp#L1546-L1554

Note that the "true shared" method has been used with Intel for years (all Intel NUCs) and no problem has ever been reported. Now it's also used for NVIDIA without any code changes needed (the NVIDIA drivers just started supporting it 2 years or so ago from driver 465.x).

**Comment by CrystalP** [comment]
It looks like there is a copy made in shared method (and copy is derived from shared, and inherits it as well):

https://github.com/xbmc/xbmc/blob/fc0833e5bded27c33cdf65bc98556db4e825d60b/xbmc/cores/VideoPlayer/DVDCodecs/Video/DXVA.cpp#L799-L800

Then this copy is used directly (shared with other device), or it's copied again (copy path).

I'll check the flags indicating texture/sharing support, in case something pops up.

Since it looks like a synchronization issue, it might be fixable. Maybe Intel and nVidia are syncing GPU work across d3d devices automatically and AMD is not. Not sure if the expected behavior is specified somewhere.

If sharing works and surfaces can be created the right way, it may be possible to do a "zero-copy" path, but that's beyond fixing this issue.

**Comment by afedchin** [comment]
https://github.com/xbmc/xbmc/blob/fc0833e5bded27c33cdf65bc98556db4e825d60b/xbmc/cores/VideoPlayer/DVDCodecs/Video/DXVA.cpp#L799-L800
this makes a copy of pointer :)

**Comment by CrystalP** [comment]
lol searching for it returned results for ID3D11DeviceContext::CopyResource and I didn't notice :-)
of course you're right, it's a ComPtr member.

**Comment by CrystalP** [comment]
ID3D11Fence provides synchronization that works with the shared and copy buffers, PR submitted.

**Comment by thexai** [comment]
I've confirmed that same issue is reproducible in NVIDIA RTX 4070 if is used Software render method + DXVA2 decoding and "fence PR" fixes the issue.

Also tested in Intel 13th gen "UHD Graphics 770" and is NOT reproducible (same as NUC8).

Then, reaffirmed conclusions are:

- Fence PR is good thing for AMD and NVIDIA (recent HW / graphics drivers).
- Fence in not need use in Intel.

Pending to test:
Fence PR is useful in NVIDIA with old drivers (< 465.89) ?

**Comment by CrystalP** [comment]
That's good most situations were covered then. Will fine tune the PR accordingly.

**Comment by thexai** [comment]
> Not pushing the button yet because of possible hiccup noticed after skip with RTX3070 in forum thread, waiting for further details.

VideoPlayer may adjust a/v sync after skip (0.2 - 1 s) later and this has no relation with video render glitch
