### ISSUE TITLE
Security Alert Exposed Jenkins 

### ISSUE THREAD

**Issue by C0oki3s** [xbmc/xbmc#23533]
I have Found a public Jenkins dashboard of kodi should I report it here or give me a mail and PGP key

**Comment by fuzzard** [comment]
is it https://jenkins.kodi.tv/ you are talking about?

**Comment by C0oki3s** [comment]
yes http://46.43.42.36:8080/

**Comment by fuzzard** [comment]
Its intended to be public, its linked in every PR for contributors to view CI status.
Is there some specific security concern you have?

**Comment by C0oki3s** [comment]
Nope thanks
