### ISSUE TITLE
Incorrect nfo file crashes Kodi

### ISSUE THREAD

**Issue by Daywalker84** [xbmc/xbmc#23544]
### Describe the bug
Here is a clear and concise description of what the problem is:

If the attached NFO file is read via local Info Only and then KODI is restarted, the application crashes within a few seconds. 
[MyVideos119 .txt](https://github.com/xbmc/xbmc/files/12143702/MyVideos119.txt)
[SafeWord2022.txt](https://github.com/xbmc/xbmc/files/12143703/SafeWord2022.txt)
[kodi_crashlog-19.2 Git_20211006-52c19a0728-20230720-205724.txt](https://github.com/xbmc/xbmc/files/12144196/kodi_crashlog-19.2.Git_20211006-52c19a0728-20230720-205724.txt)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The application should not crash if an NFO file is corrupted

## Actual Behavior

After scraping with local info only and restarting the application, it crashes

## Possible Fix

After deleting the MyVideos119 file (v19) resp. MyVideos121 file (v20), the application can be started again without crashing

### To Reproduce

My procedure:
1. set the scraper to "Local NFO only
2. after reading the file go to the Bib to see if the movie is in there (Bib is completely empty before = 0 movies)
3. close Kodi
4. start Kodi...Kodi crashes after a few seconds.
5. delete MyVideos119.db -> Kodi can be started again without problems

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/bixogurili.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.2; 19.3 & 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@Daywalker84 

What is incorrect about the nfo file?
Your log does not show any crashing. It also shows you are using Kodi v20.2, so MyVideos119 does not apply.

**Comment by Daywalker84** [comment]
Yes, the error first occurred under v19, -->MyVideos119. 
I was also able to reproduce it with v20.2, therefore see MyVideos121.
[MyVideos121.txt](https://github.com/xbmc/xbmc/files/12149470/MyVideos121.txt)

I don't know how it happened, but under the originaltitle tag it says the following: </originaltitle>????!</originaltitle>.
I suspect that this is the reason why the crash occurs later. I have a second file where there is something else under the tag, and there are no problems here.
[SafeWord2022_Error.txt](https://github.com/xbmc/xbmc/files/12149541/SafeWord2022_Error.txt)
[SafeWord2022_OK.txt](https://github.com/xbmc/xbmc/files/12149542/SafeWord2022_OK.txt)

My main concern is that the application does not crash because of a incorrect nfo file.
I hope you can reproduce it with SafeWord2022_Error.txt or MyVideos121.txt.

**Comment by KarellenX** [comment]
I don't see anything wrong with the nfo file.
It does not crash for me.
Which scraper are you using?
I don't know where the ?????! came from. I've never seen that before. 

I would need a debug log that captures the crash to investigate further.

**Comment by Daywalker84** [comment]
To reproduce this error I use as already written in the description only the "local information only pseudo-scraper".
So that there is no misunderstanding, when scrapping there are no problems, but afterwards when Kodi is restarted...it comes to a crash:
[KodiDebbugLog1 - scraping with Local Information only pseudo-scraper.log](https://github.com/xbmc/xbmc/files/12158809/KodiDebbugLog1.-.scraping.with.Local.Information.only.pseudo-scraper.log)
[KodiDebbugLog2 - After restart application crashed.log](https://github.com/xbmc/xbmc/files/12158808/KodiDebbugLog2.-.After.restart.application.crashed.log)

[kodi_stacktrace-20.2 Git_20230629-5f418d0b13-20230725
[kodi_crashlog-20.2 Git_20230629-5f418d0b13-20230725-101301.txt](https://github.com/xbmc/xbmc/files/12158830/kodi_crashlog-20.2.Git_20230629-5f418d0b13-20230725-101301.txt)
-101301.txt](https://github.com/xbmc/xbmc/files/12158825/kodi_stacktrace-20.2.Git_20230629-5f418d0b13-20230725-101301.txt)

**Comment by KarellenX** [comment]
I think it is the **service.library.data.provider** addon causing you the problem.
You can't disable this Service, so you will need to delete the addon.
Exit Kodi
Go to C:\Users\axelk\AppData\Roaming\Kodi\addons
Delete service.library.data.provider folder.
Restart Kodi. Does it still crash?

**Comment by Daywalker84** [comment]
After deleting the folder, the application does not crash.
But what are the consequences? 
What is this "service" responsible for?

**Comment by KarellenX** [comment]
It is used by the skin. Aeon Nox Silvo in your case.
I am not sure exactly what info it provides, best to ask in the Aeon Nox Silvo forum. Probably ratings?
It can always be reinstalled from the skin settings page.
