### ISSUE TITLE
m3u8 Redirect errors

### ISSUE THREAD

**Issue by zhangsan1025** [xbmc/xbmc#23549]
### Describe the bug
If open an m3u8 file on the internet and redirect it to another URL, xbmc will incorrectly concatenate the segment URL

## Expected Behavior
Webdav Browse
request url    `http://aaa.com/dav/1.m3u8`
redirect url    `http://bbb.com/1/1.m3u8`
finalfile
```
#EXTM3U
#EXTINF:1,
index0.ts
```

expected segment URL    `http://bbb.com/1/index0.ts`

## Actual Behavior
xbmc request for url `http://aaa.com/dav/index0.ts`

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:Windows
 - Kodi version:20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by matthuisman** [comment]
What Kodi version? Pretty sure this was a bug in old Kodi but been fixed for some time
