### ISSUE TITLE
FFmpeg related crash with dxva decoding

### ISSUE THREAD

**Issue by CrystalP** [xbmc/xbmc#23547]
### Describe the bug

Exception in ffmpeg with null pointer for some videos played with dxva acceleration

![image](https://github.com/xbmc/xbmc/assets/489377/d0f82a4f-0d29-477f-b6dd-5968e32749df)

No crash with software decoding.

## Expected Behavior

Video plays without exception.

## Actual Behavior

Exception in some videos.

## Possible Fix

Bisecting showed that the problem started with PR #22540 / commit 4b7b3f6610e94c70d9ebedab458eef27356eeb34 (ffmpeg: use upstream version)
The commit was on v21 before alpha 1.

Fix ideas:
- restore the patches removed by the PR
- upstream the patches
- maybe the issue is on the application side, supplying incorrect parameters, and the patches covered it up
- change acceleration method from AV_PIX_FMT_D3D11VA_VLD (old) to AV_PIX_FMT_D3D11VA

### To Reproduce

Sample: [ffmpeg null pointer.zip](https://github.com/xbmc/xbmc/files/12150905/ffmpeg.null.pointer.zip)

1. extract sample and play VIDEO_TS.IFO
2. segmentation fault a few seconds after the initial image, 

For some reason playing the .vob directly succeeds, the problem is only through the .IFO

Reproduced with AMD and Intel.

### Debuglog

The debug log can be found here: https://paste.kodi.tv/fezakenaye.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Which commit specifically? This one? https://github.com/xbmc/FFmpeg/commit/fec4c2031296c414685477c75e6a4bdff105a3ac

**Comment by CrystalP** [comment]
Yes, only the top part (avctx->pix_fmt == AV_PIX_FMT_D3D11VA_VLD).
The bottom part was for D3D9, dropped a few years ago.

**Comment by fritsch** [comment]
Yeah, concern was there: https://github.com/xbmc/xbmc/pull/22540#issuecomment-1399283028

**Comment by lrusak** [comment]
We can add the patch back on the condition that it gets submitted upstream first.

**Comment by CrystalP** [comment]
Same thing happened for VC-1 Cheese Slicies sample. Easier repro steps, works fine in other ffmpeg-based programs, root cause may be in kodi.

**Comment by CrystalP** [comment]
Is it possible to get this included in the patches pushed to ffmpeg for merge? It's a regression with v20.
