### ISSUE TITLE
Remap long press select button on firestick remote

### ISSUE THREAD

**Issue by SJ1O** [xbmc/xbmc#23546]
### Describe the bug
Here is a clear and concise description of what the problem is: I used keymap editor to change the select (ok) long press button to show information instead of context menu but no change takes affect. It produces this code within a keymap XML file. <keymap>
<global>
<keyboard>
<key id="16838669">info</key>
</keyboard>
</global>
</keymap> 

However when I long press the select button I still get the context menu.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It to follow the command that's in the XML file

## Actual Behavior

Nothing changed

### To Reproduce

1. Download keymap editor addon 
2.run, global, navigation, show information, long press select button.
3. Restart Kodi but the button remains the same

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system: firestick 4k

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: firestick 
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by garbear** [comment]
There is an effort to unify Remote and Controller keymaps so that buttons and long presses behave consistently between the two. Please continue discussion in https://github.com/xbmc/xbmc/pull/25178. You can also see discussion on keymap improvements here: https://github.com/garbear/xbmc/pull/140
