### ISSUE TITLE
Additional info on webOS build guide

### ISSUE THREAD

**Issue by swaree** [xbmc/xbmc#23564]
**Note: I don't consider this a bug, so using the bug report template seems contradictory.**

I am attempting to build kodi for webOS and I'm following the guide on [/docs/README.webOS.md](https://github.com/xbmc/xbmc/blob/051b505d3871763422e26688746f0a21a42f0452/docs/README.webOS.md). However, below prerequisites, the second-to-last bullet point is confusing to me.

I'm running Windows, so I can't use Buildroot, and I was unable to find "other toolchains" and where to write the serial number. I'd really appreciate any help/expansion of the guide. Thanks.

**Comment by swaree** [comment]
> If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.

See note.

**Comment by lrusak** [comment]
Please use the forum for support.

https://forum.kodi.tv/
