### ISSUE TITLE
error while loading shared libraries: libfmt.so.9 on Arch Linux

### ISSUE THREAD

**Issue by cg00001** [xbmc/xbmc#23566]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi doesn't start. On terminal, it gives the error:
```
~►kodi                                                           
/usr/lib/kodi/kodi.bin: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory
```
Kodi Omega alpha 2 -kodi-git package from AUR.
Arch Linux uses fmt v10.0.0-1.
I tried downgrading fmt to v9, and Kodi complains about a missing libfmt.so.10.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should start as usual.

## Actual Behavior

Kodi does not start, it gives the error message mentioned above when started from a terminal.

## Possible Fix

libfmt version mismatch resolved.

### To Reproduce

1. Start Kodi from shortcut or terminal.

### Debuglog

The debuglog can be found here:
Debuglog can not be acquired since Kodi doesn't start for log to be created.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Arch Linux

 - Kodi version:
Kodi Omega Alpha 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
Arch updated to fmtlib 10 recently. That means all packages build against fmtlib need be recompiled against the new fmtlib version. But alpha 2 isn't compatible with fmtlib 10 so you have to switch to master which has the necessary changes.

**Comment by cg00001** [comment]
> Arch updated to fmtlib 10 recently. That means all packages build against fmtlib need be recompiled against the new fmtlib version. But alpha 2 isn't compatible with fmtlib 10 so you have to switch to master which has the necessary changes.

Thank you, will try.

**Comment by garbear** [comment]
Kodi master should build with fmt10 after https://github.com/xbmc/xbmc/pull/23453 and Nexus should build when https://github.com/xbmc/xbmc/pull/23571 is merged.
