### ISSUE TITLE
Sound buggy or not depending on the display frequency.

### ISSUE THREAD

**Issue by JGoutin** [xbmc/xbmc#23574]
### Describe the bug

Depending the configured screen frequency, the sound works correctly or not.
When not working, the sound alternate every ~1 second between silent part and very short sound part that look speed up.

The bug appears when playing videos files (But not on all videos), it also appear when playing a game with libretro trough Kodi.

- If I set 60Hz as screen frequency (with `Adjust display refresh rate`=Off), the sound is buggy.
- If I set 30Hz as screen frequency (with `Adjust display refresh rate`=Off), the sound is OK.
- If I set either 30Hz or 60Hz screen frequency, and activate the `Adjust display refresh rate` option, the sound is buggy.

When I did my tests with the "Adjust display refresh rate" option enabled and various video files, I noticed that the frequency displayed by the debug overlay on the screen was :
- 50Hz when the sound was buggy
- 24Hz when the sound worked

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Have the sound always correctly working.

## Actual Behavior

The sound does not work correctly with some configuration.

My current working workaround are:
- to set the screen frequency to 30Hz and disable the `Adjust display refresh rate` option.
- Or enable `Adjust display refresh rate` and whitelist only display modes with 30Hz or less frequencies.

### To Reproduce

1. Change screen frequency and/or `Adjust display refresh rate` parameter.
2. Play video or game

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/xopegiyemo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Kodi runs standalone with GBM. I also tested with Wayland (Using Sway) but the issue is still here.

I tried to fully reset my Kodi profile and also reset display/sound/video playback parameters, this does not helped.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora 38
 - Kodi version: 20.2 from RPM Fusion package (The problem was also present with older versions of Kodi, at least Kodi 19/18)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
Please test the workaround described in https://gitlab.freedesktop.org/mesa/mesa/-/issues/7977 and report back.

**Comment by JGoutin** [comment]
Enabled `mesa_glthread=false` but this does not fixed the issue.

**Comment by JGoutin** [comment]
The problem is gone today with OS and Kodi updates.
