### ISSUE TITLE
Python extensions openssl error

### ISSUE THREAD

**Issue by MaximKiselev** [xbmc/xbmc#23576]
hi guys. i got some weird fatal error. tested on 20.2 /19.5 version. platform - win 11 22h2. 
![photo_2023-08-02_00-31-35](https://github.com/xbmc/xbmc/assets/5432222/809a0254-5334-4e50-9d7f-7a852f8a757c)
no logs and etc in kodi.log. tool will down after click on extension.

what i did for resolve the problem.
disabled any plugins - enabled default plugins - no results
installed other version of openssl - no results
changed default python dlls to  python3.dll from conda - its weird but maybe - no results
copy openssl libs to installation path of kodi - no results

other extension
![image](https://github.com/xbmc/xbmc/assets/5432222/d145ee78-4497-431c-983f-b79cdf4c23e6)

any idea? thanks.

**Comment by fuzzard** [comment]
Is the solution around an env variable being set in this issue relevant to your setup

https://github.com/xbmc/xbmc/issues/20612

**Comment by MaximKiselev** [comment]
> Is the solution around unsetting env variable that was set in this issue relevant to your setup
> 
> #20612

hi .thanks. i read this post. i have SSLKEYLOGFILE in env of current user. also i added in system variables.
