### ISSUE TITLE
GBM: Screen tearing on menu after playbak

### ISSUE THREAD

**Issue by JGoutin** [xbmc/xbmc#23575]
### Describe the bug
Here is a clear and concise description of what the problem is:

The problem is not present on Kodi startup but appear after playing a video or running a game, and then be present until Kodi shutdown.

The issue is some kind of screen tearing on the top of the Kodi menu. This occurs when there is something moving on the menu (mouse cursor, page change, ...).

Strangely, when I enabled the debug mode to create this ticket, I was unable to reproduce the issue (Maybe because of the debug overlay?).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No screen tearing.

## Actual Behavior

Screen tearing.

### To Reproduce

1. Start Kodi with GBM standalone
2. Run video or Game
3. Go back to the menu
4. Move the cursor or navigate in menus

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/tiriqilego.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

![IMG_20230801_200552_192](https://github.com/xbmc/xbmc/assets/13535894/6c0d5963-fbf7-49cf-bfa9-bdf8defd6500)
![IMG_20230801_200554_876 (1)](https://github.com/xbmc/xbmc/assets/13535894/e8171a3c-1093-4aa5-8e6d-67d177b0bee9)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Kodi runs standalone with GBM.
The issus is not present when using Wayland.

I tried to fully reset my Kodi profile and also reset or change display parameters without success.

This issue is recent (Seen only with Kodi 20 and Fedora 38).

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora 38
 - Kodi version: 20.2 from RPM Fusion package (Also have the issue with 20.1)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
That's a known Mesa bug for AMD hardware: https://gitlab.freedesktop.org/mesa/mesa/-/issues/9115 and https://gitlab.freedesktop.org/mesa/mesa/-/issues/7977. A workaround is supplied in the latter issue.

**Comment by JGoutin** [comment]
Thanks, the "mesa_glthread=false" workaround worked in my case too.
