### ISSUE TITLE
Typo in middle mouse button name

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/xbmc#23588]
### Describe the bug
Typo in middle mouse button name

## Expected Behavior
No typo

## Actual Behavior

typo

## Possible Fix

Fix the string

### To Reproduce
Go to Settings - System - Input - Controller configuration - Computer mouse

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Untitled](https://github.com/xbmc/xbmc/assets/1557784/0f8a0342-d0bc-4930-b5bb-c4ebf4426f91)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64
 - Kodi version: latest master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by garbear** [comment]
Thanks for reporting, fixed in https://github.com/kodi-game/controller-topology-project/pull/255

This PR will make its way to master and v20 in due time.

**Comment by kambala-decapitator** [comment]
and what about such strings in the Kodi repo? https://github.com/search?q=repo%3Axbmc%2Fxbmc+Midle+path%3A%2F%5Eaddons%5C%2Fgame.controller.mouse%5C%2Fresources%5C%2Flanguage%5C%2F%2F&type=code

**Comment by fuzzard** [comment]
@garbear syncs it every now and again. eg https://github.com/xbmc/xbmc/pull/22927

**Comment by kambala-decapitator** [comment]
> @garbear syncs it every now and again. eg #22927

cool, thanks

**Comment by garbear** [comment]
Indeed, this sync is worth an immediate sync. PRs will be open against master and Nexus as soon as this is merged (pending review over the next couple days)

@fuzzard A3 material

@kambala-decapitator @gade01 Feel free to give the go-ahead

**Comment by garbear** [comment]
PRs opened against master and Nexus
