### ISSUE TITLE
[Master] - Build fails due to missing tinyxml2 on openSUSE Tumbleweed and ArchLinux

### ISSUE THREAD

**Issue by coffeinflash** [xbmc/xbmc#23607]
### Describe the bug
Here is a clear and concise description of what the problem is:

Building the latest master fails on openSUSE Tumbleweed and ArchLinux due to missing tinyxml2, although the library is installed:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should find tinyxml2.h and just build

## Actual Behavior
Building fails with error below

### To Reproduce

Clone current master and start building with cmake:
%cmake \
    -DVERBOSE=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCORE_SYSTEM_NAME=linux \
    -DAPP_RENDER_SYSTEM=gles \
    -DCORE_PLATFORM_NAME=gbm \
    -DGIT_VERSION="%{_git_version}" \
    -DENABLE_EVENTCLIENTS=ON \
    -DENABLE_INTERNAL_CROSSGUID=OFF \
    -DENABLE_INTERNAL_CDIO=OFF \
    -DENABLE_INTERNAL_FLATBUFFERS=OFF \
    -DENABLE_INTERNAL_FMT=OFF \
    -DENABLE_INTERNAL_FSTRCMP=OFF \
    -DENABLE_INTERNAL_RapidJSON=OFF \
    -DENABLE_INTERNAL_SPDLOG=OFF \
    -DENABLE_INTERNAL_DAV1D=OFF \
    -DENABLE_INTERNAL_UDFREAD=OFF \
    -DENABLE_INTERNAL_GTEST=OFF \
    -DENABLE_INTERNAL_KISSFFT=OFF \
    -DENABLE_INTERNAL_TINYXML2=OFF \
    -DENABLE_AIRTUNES=OFF \
    -DENABLE_DVDCSS=OFF \
    -DENABLE_PULSEAUDIO=OFF \
    -DENABLE_PIPEWIRE=OFF \
    -DENABLE_MYSQLCLIENT=OFF \
    -DENABLE_MARIADBCLIENT=ON \
    -DENABLE_GOLD=OFF \
    -DENABLE_MOLD=OFF \
    -DENABLE_INTERNAL_FFMPEG=ON \
    -DFFMPEG_URL="%{SOURCE9}" \
    -DENABLE_INTERNAL_CEC=OFF \
    -DENABLE_INTERNAL_NFS=OFF \
    -DENABLE_INTERNAL_PCRE=OFF \
    -DENABLE_INTERNAL_TAGLIB=OFF \
    -DENABLE_OPENGLES=ON \
    -DENABLE_VAAPI=ON \
    -DENABLE_VDPAU=OFF \
    -DUSE_LTO=OFF \
    -DBUILD_SHARED_LIBS=1 \
    -DENABLE_TESTING=OFF \
    -DENABLE_DEBUGFISSION=OFF

### Debuglog

BuildLog Tumbleweed: (https://build.opensuse.org/package/live_build_log/home:Herbster0815:HTPC/kodi/openSUSE_Tumbleweed/x86_64)
Spec-file including "BuildRequires:  pkgconfig(tinyxml2)" : (https://build.opensuse.org/package/view_file/home:Herbster0815:HTPC/kodi/kodi.spec?expand=1)

BuildLog Arch:
-- Found TinyXML: /usr/lib/libtinyxml.so (found version "2.6.2")
-- MODULE: TINYXML2
-- LIB_TYPE: target
-- DEP_LOCATION: /home/mediapc/source/kodi-rpi-git-upstream/src/kodi-build/build
-- PROJECTSOURCE: /home/mediapc/source/kodi-rpi-git-upstream/src/xbmc-b9d83afe162307da8cd47ed9af416f536fa409bc
-- TINYXML2_URL: http://mirrors.kodi.tv/build-deps/sources/tinyxml2-9.0.0.tar.gz
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find TinyXML2 (missing: TINYXML2_LIBRARY) (found version "9.0.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindTinyXML2.cmake:107 (find_package_handle_standard_args)
  cmake/scripts/common/Macros.cmake:372 (find_package)
  cmake/scripts/common/Macros.cmake:386 (find_package_with_ver)
  CMakeLists.txt:226 (core_require_dep)

tinyxml2 is installed:

[11:15:42 @ Do Aug 10]root@Kleinerbaer[/home/mediapc/source/kodi-rpi-git-upstream/]$psearch tinyxml2
extra/tinyxml2 9.0.0-2 [Installiert]
    Simple XML parser made for easy integration
community/tinyxml2 9.0.0-1 [Installiert: 9.0.0-2]
    Simple XML parser made for easy integration

[11:15:47 @ Do Aug 10]root@Kleinerbaer[/home/mediapc/source/kodi-rpi-git-upstream/]$ls -l /usr/include/tinyxml2.h
-rw-r--r-- 1 root root 72K 18. Jul 15:02 /usr/include/tinyxml2.h

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: openSUSE Tumbleweed x64, ArchLinux armv7l
 - Kodi version: 21.x.+git.20230809T211603~b9d83afe1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by howie-f** [comment]
known issue. we're actually trying to work out a fix for this

**Comment by coffeinflash** [comment]
https://github.com/xbmc/xbmc/pull/23605/commits/994106fd3f779ce4867f5811f9863884b4a6d167 fixes the issue on Tumbleweed.
