### ISSUE TITLE
How to activate HDR on xbox platforms 

### ISSUE THREAD

**Issue by samfox92** [xbmc/xbmc#23616]
Hi,

Is there are a way to activate the HDR on kodi on xbox ?
I know that the xbox hardware is able to do this cause under YouTube on xbox that work fine.
When an HDR video run the TV pass directly on HDR mode but not under kodi.
Is a developing issue or setting one ?
I'm here to make test if Is needed 
Ty

**Comment by enen92** [comment]
Please use the forum for support, this is a bug tracker.
