### ISSUE TITLE
Raspberry 7" Touchscreen Rotation Ignored By Kodi 20.2

### ISSUE THREAD

**Issue by trekkertie** [xbmc/xbmc#23622]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a Raspberry Pi 3B with the official 7" touchscreen in a frame and have upgraded from LibreELEC 9.2.8 using Kodi 18.9 to LibreELEC 11.0.3 using Kodi 20.2. In order for the display to be the correct way up I added lcd_rotate=2 to config.txt in Kodi 18.9. This worked perfectly.

Since updating to 20.2 I have been unable to rotate the screen. Below are the four separate additions to config.txt tried unsuccesfully.

dtoverlay=vc4-kms-dsi-7inch
video=DSI-1:800x480@60,rotate=180

dtoverlay=vc4-kms-dsi-7inch
panel_orientation=upside_down

dtoverlay=vc4-kms-dsi-7inch
lcd_rotate=2

display_lcd_rotate=2
dtoverlay=rpi-ft5406,touchscreen-inverted-x=1,touchscreen-inverted-y=1

I have also tried adding video=DSI-1:800x480@60,rotate=180 to the boot params in cmdline.txt which rotates the screen until Kodi takes over.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The orientation of the screen should rotate through 180 degrees.

## Actual Behavior

The screen rotates 180 degrees during boot but Kodi reverts to the original orientation once it starts.

### To Reproduce

1. Add video=DSI-1:800x480@60,rotate=180 to the boot params in cmdline.txt
2. Reboot Raspberry Pi

### Debuglog

The debuglog can be found here:

I cannot find a debug log that explains this behaviour.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - LibreELEC 11.0.3 Linux Kernel 6.1
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by kl3sk** [comment]
Hello,

Same behaviour, interested about a solution.

thanks

**Comment by leecher1337** [comment]
Same here, seems I'm stuck until this is fixed, because multi screen support (HDMI & DSI) via KMS driver depend on Kodi being at least version 20.

**Comment by leecher1337** [comment]
Ok, so I tested my theory and indeed, with a little code change, rotation works fine.
I guess the proper method would be to extend Kodi to add a setting for panel rotation in its config dialog/file and then just apply it. But as I don't have any clue about inner workings of Kodi, I leave this to the Kodi devs, 
I just quickly hacked it into the source using the following patch file and recompiled as a debian package (applies to sources available via apt-get source kodi on debian/raspbian 12.1 bookworm):

`cat debian/patches/kodi/0017-screen-rotation.patch`

```
From: leecher1337 <leecher@dose.0wnz.at>
Date: Sun, 27 Aug 2023 18:20:00 +0200
Subject: Rotate screen by 180 degrees on Raspi internal display
Forwarded: not-needed

---

--- a/xbmc/windowing/gbm/drm/DRMAtomic.cpp
+++ b/xbmc/windowing/gbm/drm/DRMAtomic.cpp
@@ -121,6 +121,9 @@
     AddProperty(m_gui_plane, "CRTC_ID", 0);
   }

+  if (m_connector->GetName() == "DSI-1")
+    AddProperty(m_gui_plane, "rotation", DRM_MODE_ROTATE_180);
+
   if (CServiceBroker::GetLogging().CanLogComponent(LOGWINDOWING))
     m_req->LogAtomicRequest();
```

Next, you also need to take into acount the touch panel orientation. Changing panel orientation is not documented very well in the touchscreen docs for Raspi, as they only refer to X, but there exists another [well-documented way via udev](https://wayland.freedesktop.org/libinput/doc/1.15.0/device-configuration-via-udev.html).
So simply add a new rule file:

`cat /etc/udev/rules.d/90-libinput-rotate.rules`

```
ACTION=="add|change", KERNEL=="event[0-9]*", ENV{LIBINPUT_CALIBRATION_MATRIX}="-1 0 1 0 -1 1"
```

Together with the standard rules for a correctly-oriented console, which is just adding `video=DSI-1:800x480M,rotate=180` to /boot/cmdline.txt, you now should be able to use kodi properly with the new `dtoverlay=vc4-kms-v3d`.

Hope that helps for the time being.

**Comment by trekkertie** [comment]
The update works perfectly. Thank you so much for your help and hard work it is much appreciated.

**Comment by dro162** [comment]
@trekkertie Would you mind explaining how you applied this?  I didn't think there was a console and Kodi doesn't like the ZIP structure.

**Comment by trekkertie** [comment]
The zip package needs to be extracted and the resulting deb package installed from the Linux command line using sudo dpkg -I packagename.deb. Whilst doing this I did find myself getting into some confusion about the order in which to install Kodi and then the modification.

However, since posting this I have found a simpler way to achieve the same result. The Kodi package which is in the Debian repositories takes account of screen rotation on the Pi. Here are the steps I took from an ssh Linux command line.

Remove the current installation of Kodi - sudo apt auto remove kodi

The next step is to install the dependencies associated with Kodi - sudo apt install autoconf automake autopoint gettext autotools-dev cmake curl default-jre gawk gcc g++ cpp  gdc gperf libasound2-dev  libasound-dev libass-dev libavahi-client-dev libavahi-common-dev libbluetooth-dev libbluray-dev libbz2-dev libcdio-dev libcec-dev libp8-platform-dev libcrossguid-dev libcurl4-openssl-dev libcwiid-dev libdbus-1-dev libegl1-mesa-dev libenca-dev libflac-dev libfontconfig-dev libfmt-dev libfreetype6-dev libfribidi-dev libfstrcmp-dev libgcrypt-dev libgif-dev  libgles2-mesa-dev libgl1-mesa-dev  libgl-dev libglew-dev libglu1-mesa-dev  libglu-dev libgnutls28-dev libgpg-error-dev libgtest-dev libiso9660-dev libjpeg-dev liblcms2-dev liblirc-dev libltdl-dev liblzo2-dev libmicrohttpd-dev libnfs-dev libogg-dev libomxil-bellagio-dev libpcre3-dev libplist-dev libpng-dev libpugixml-dev libpulse-dev libshairplay-dev libsmbclient-dev libspdlog-dev libsqlite3-dev libssl-dev libtag1-dev libtiff5-dev  libtiff-dev  libtinyxml-dev libtinyxml2-dev libtool libudev-dev libunistring-dev libva-dev libvdpau-dev libvorbis-dev libxkbcommon-dev libxmu-dev libxrandr-dev libxslt1-dev  libxslt-dev libxt-dev waylandpp-dev wayland-protocols  wipe lsb-release meson nasm ninja-build python3-dev python3-pil python3-minimal rapidjson-dev swig unzip uuid-dev zip zlib1g-dev

I realise the previous step installs packages that are not strictly necessary but I know it works so have stuck with it.

Download the kodi-data package from the Debian repository here: https://packages.debian.org/sid/all/kodi-data/download and install it from the command line using: sudo dpkg -I kodi-data_20.2+dfsg-4_all.deb

Download the kodi package from the Debian repository here: https://packages.debian.org/sid/kodi-bin. You will need to navigate to the bottom of the page and choose the package for your Pi OS (armhf or arm64) before downloading. Once you have the correct package install it using sudo dpkg -I kodi-bin_20.2+dfsg-4+b2_arm64.deb. Use the name of the package you have downloaded instead of kodi-bin_20.2+dfsg-4+b2_arm64.deb if it is different.

Download the kodi-bin package from the Debian repository here: https://packages.debian.org/sid/kodi. You will need to navigate to the bottom of the page and choose the package for your Pi OS (armhf or arm64) before downloading. Once you have the correct package install it using sudo dpkg -I kodi-bin_20.2+dfsg-4+b2_arm64.deb. Use the name of the package you have downloaded instead of kodi-bin_20.2+dfsg-4+b2_arm64.deb if it is different.

Edit the /boot/cmdline.txt and add the following to the first line to rotate the display:

video=DSI-1:800x480M,rotate=180

Then add the /etc/udev/rules.d/90-libinput-rotate.rules as shown above by @leecher1337 

Reboot the Pi and you should be good to go.

**Comment by sarbes** [comment]
I'm sorry, but this is a feature request. To my knowledge, Kodi is not able to rotate its output, so there is no bug for this bug tracker. Please use the forum for requests.

If someone wants to add auch a feature, I don't see any issues with that. But I'd advise to consult the forum/IRC before doing so.

**Comment by SnejPro** [comment]
Hi,
i've fixed this with this config:

```
#/flash/config.txt - Add lcd_rotate

lcd_rotate=2
```

```
#/flash/distroconfig.txt - Change dtoverlay=vc4-kms-v3d,cma-384 like this:

dtoverlay=vc4-fkms-v3d,cma-384
```

Thanks to this thread: https://www.kodinerds.net/thread/77159-gel%C3%B6st-libreelec-11-01-img-unter-raspberrypi-4-mit-lcd-7-somit-180-gedreht-richt/?pageNo=2

**Comment by steef76** [comment]
Hi,
I tried the config suggested by SnejPro, but my pi 3b+ wouldn't even boot....
Back to upsidedown I suppose

**Comment by SnejPro** [comment]
> Hi,
> I tried the config suggested by SnejPro, but my pi 3b+ wouldn't even boot....
> Back to upsidedown I suppose
> 
> The pi does boot, but the screen doesn't turn on.
> Anyway, it doesn't work

Hmm, in my case it worked on a completly fresh install. But when I played with the values to get it working, I had a non bootable Pi aswell. Maybe it does not work well with other settings, a specific kodi version or a specific firmware version 🤔

What did your distroconfig.txt look like before you made the suggested changes?

**Comment by steef76** [comment]
Hi, The strange thing is, my pi is running on a fresh installation too.
It's a pi 3b+ that was given to me.
Anyway, here is the original distroconfig.txt file:

`# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2023-present Team LibreELEC (https://libreelec.tv)

# WARNING: DO NOT EDIT THIS FILE - IT WILL BE OVERWRITTEN WHEN UPGRADING!
display_auto_detect=1
dtoverlay=vc4-kms-v3d,cma-384
dtoverlay=
disable_overscan=1
disable_fw_kms_setup=1
`
Hope it makes any sense to you?

**Comment by SnejPro** [comment]
> Hi, The strange thing is, my pi is running on a fresh installation too.
> It's a pi 3b+ that was given to me.
> Anyway, here is the original distroconfig.txt file:
> 
> `# SPDX-License-Identifier: GPL-2.0-or-later
> # Copyright (C) 2023-present Team LibreELEC (https://libreelec.tv)
> 
> # WARNING: DO NOT EDIT THIS FILE - IT WILL BE OVERWRITTEN WHEN UPGRADING!
> display_auto_detect=1
> dtoverlay=vc4-kms-v3d,cma-384
> dtoverlay=
> disable_overscan=1
> disable_fw_kms_setup=1
> `
> Hope it makes any sense to you?

Looks like mine. I just added the "f" before "kms".

Maybe it's a firmware related issue 🤔 I'll check my firmware version when I'm home.

Have you used the latest libreelec?

**Comment by steef76** [comment]
> Have you used the latest libreelec?

I suppose so. I used the raspberry image tool to download & install Libreelec on a sd card.
I'll check the firmware tomorrow.

**Comment by chewitt** [comment]
See: https://forum.libreelec.tv/thread/29268-rpi-5-new-raspberry-touch-display-2/ - Kodi does not support rotation through kernel DRM, which is how every thing is done since LE10 when all RPi devices switched to a GBM/V4L2 video pipeline. The switch also superseded many firmware config.txt options with kernel DRM options - including rotation. LE12/13 images have the latest RPi3 firwmware included, but it's not a firmware issue.

Ping to @popcornmix for awareness.

**Comment by SnejPro** [comment]
> See: https://forum.libreelec.tv/thread/29268-rpi-5-new-raspberry-touch-display-2/ - Kodi does not support rotation through kernel DRM, which is how every thing is done since LE10 when all RPi devices switched to a GBM/V4L2 video pipeline. The switch also superseded many firmware config.txt options with kernel DRM options - including rotation. LE12/13 images have the latest RPi3 firwmware included, but it's not a firmware issue.
> 
> Ping to @popcornmix for awareness.

But it works for me 🤔 Am I just lucky?

**Comment by popcornmix** [comment]
`display_rotate` is only supported by the deprecated fkms display driver.
It could work in some circumstances but there is no support for it.

For support of a rotated display in kodi when running in full-screen mode without a compositor, you'd need support from inside kodi, and that doesn't exist.

If you are using kodi in desktop mode through a compositor, then the compositor can handle rotation, but performance will be lower. This should be be possible on RPiOS bookworm when launching kodi in non-fullscreen mode.

**Comment by steef76** [comment]
> display_rotate is only supported by the deprecated fkms display driver.
It could work in some circumstances but there is no support for it.
For support of a rotated display in kodi when running in full-screen mode without a compositor, you'd need support from inside kodi, and that doesn't exist.

That's pity
I'l nowl have to think what to do with the little pi
Keep it upsidedown, or install something entirely different like MoOde.

Thanks anyway, and perhaps I'll have a go in another year or so.

Cheers

Steven

**Comment by leecher1337** [comment]
> 
> That's pity I'l nowl have to think what to do with the little pi Keep it upsidedown, or install something entirely different like MoOde.

Why not just use my patch? Works fine here without any issues.

**Comment by steef76** [comment]
> Why not just use my patch? Works fine here without any issues.

I'll give it a shot. 
Just one question. 
How to install it in Libreelec? As I understand, Libreelec is not based on Debian/Ubuntu.

**Comment by leecher1337** [comment]
Seems to work like this with libreelec (haven't tried myself):

### 1. **Set Up Your Build Environment**
1. **Install Required Dependencies**:
   LibreELEC uses a Linux build system, so you need a Linux-based machine (Ubuntu/Debian-based systems are commonly used). Install required dependencies:
   ```bash
   sudo apt-get update
   sudo apt-get install git build-essential unzip wget python3 python3-pip xz-utils gawk gcc-multilib make automake autoconf cmake libssl-dev zlib1g-dev
   ```

2. **Install `repo` Tool**:
   LibreELEC uses Google's `repo` tool to manage source repositories:
   ```bash
   mkdir ~/bin
   curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
   chmod a+x ~/bin/repo
   export PATH=~/bin:$PATH
   ```

---

### 2. **Clone the LibreELEC Source**
1. Clone the LibreELEC source code from GitHub:
   ```bash
   git clone https://github.com/LibreELEC/LibreELEC.tv.git
   cd LibreELEC.tv
   ```

2. Switch to the branch corresponding to your target version of LibreELEC (replace `11.0` with your desired version):
   ```bash
   git checkout libreelec-11.0
   ```

---

### 3. **Configure the Build**
1. **Set the Target Architecture**:
   Set the architecture for the device you’re building for. For example, for the Raspberry Pi 4:
   ```bash
   PROJECT=RPi DEVICE=RPi4 ARCH=arm
   ```

   Replace `RPi`, `RPi4`, and `arm` with the appropriate values for your target device.

2. **Download the Kodi Sources**:
   LibreELEC includes a specific Kodi version as part of its build process. To download the Kodi sources used by LibreELEC:
   ```bash
   scripts/clean kodi
   scripts/unpack kodi
   ```

   The Kodi source will now be in `packages/mediacenter/kodi/`.

---

### 4. **Modify Kodi**
1. Navigate to the Kodi source directory:
   ```bash
   cd packages/mediacenter/kodi
   ```

2. Place the patch files in `packages/mediacenter/kodi/patches/` and update the `kodi/package.mk` file to apply them.

---

### 5. **Build LibreELEC with the Custom Kodi**
1. Go back to the root directory of the LibreELEC source:
   ```bash
   cd ../../../..
   ```

2. Start the build process with your chosen target architecture:
   ```bash
   PROJECT=RPi DEVICE=RPi4 ARCH=arm make image
   ```

   This will build a complete LibreELEC image with your custom Kodi version.

3. The final `.img.gz` file will be located in the `target/` directory, ready to flash to your device.

---

### 6. **Test Your Build**
1. Flash the generated `.img.gz` to an SD card or USB stick using a tool like `Rufus` or `Etcher`.
2. Boot your target device with the custom LibreELEC build and test your modified Kodi.

---

### 7. **Iterate and Debug**
- If the build fails, check the logs in the `build.<target>/` directory.
- For frequent modifications to Kodi, you can clean and rebuild only the Kodi component:
  ```bash
  scripts/clean kodi
  scripts/build kodi
  ```

---
