### ISSUE TITLE
Medialibraryscanpath crashes Kodi

### ISSUE THREAD

**Issue by Dis90** [xbmc/xbmc#23636]
### Describe the bug

When add-on has medialibraryscanpath and path is in video sources, Kodi will crash when you start library scan.

## Expected Behavior

Scanning to work without crash.

## Actual Behavior

Crash.

### To Reproduce

1.  Use my fork of original plugin.video.testlib https://github.com/Dis90/plugin.video.testlib
2. Add plugin://plugin.video.testlib/tvshows/ to sources, set content to tvshows and scraper to local
3. Start scanning for new content

### Debuglog

The debuglog can be found here:

[kodi_log.txt](https://github.com/xbmc/xbmc/files/12386405/kodi_log.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

It works on Kodi 21 alpha.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Mac OS 13.4.1
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
Will be fixed in Kodi 20.3.
