### ISSUE TITLE
Android Deeplink

### ISSUE THREAD

**Issue by dusan-ivanco** [xbmc/xbmc#23642]
### Describe the bug
It seems that Kodi for Android doesn't support deeplinks. Could you please consider adding this functionality?

## Expected Behavior
DeepLink URL
kodi://

## Actual Behavior
DeepLink URL is not working

## Possible Fix
Add deeplink url

### To Reproduce
Call deeplink url (kodi://)

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
I want to launch the Kodi app on Android TV from Home Assistant, just like other apps (Spotify, Netflix, VLC, ...) using a deeplink.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV (11)
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Hey, feature requests are forum material. This is a bug tracker only
