### ISSUE TITLE
Sharing MySQL DB among profiles

### ISSUE THREAD

**Issue by lameventanas** [xbmc/xbmc#23656]
### Describe the bug
Here is a clear and concise description of what the problem is:

It should be possible to share a MySQL db with different profiles.

The profile-specific information should be stored in separate table(s) of the same db using foreign keys, instead of having to keep a separate db for each profile.

That would make it possible to use a MySQL db without having to resort to dirty hacks, such as the one described [here](https://kodi.wiki/view/MySQL/Advanced_notes#Multiple_profiles_with_one_MySQL_database).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Actual Behavior

We need to have a separate db for each profile.

## Possible Fix

A proper db design.

### To Reproduce

1. Install default Kodi
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
PRs welcome, otherwise feature requests can be made in the forums.
