### ISSUE TITLE
[LanguageCodes]  Expanded language codes in mkv videos not working

### ISSUE THREAD

**Issue by scott967** [xbmc/xbmc#23655]
### Describe the bug
Here is a clear and concise description of what the problem is:

@CastagnaIT
PR#21776 added the ability to parse expanded languagecodes (language-region) for video files.  The PR provides a comment
https://github.com/xbmc/xbmc/blob/f5ab9fd5d2d6d3589470208a774bbfa757a63ee9/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp#L1863-L1870
concerning this feature in mkv files.
Per user request I attempted to follow this comment to add an expanded language code of French CANADA based on a short code of fr-CA set as the audio stream language in mkv video file.  Running in Kodi the  fullscreen video audio settings show audio language as French

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The full screen video audio settings show the audio language as French CANADA

## Actual Behavior

Shown as French

### To Reproduce

1. I created advancedsettings.xml file as
```
<advancedsettings>
		<languagecodes>
			<code>
				<short>fr-CA</short>
				<long>French CANADA</long>
			</code>
		</languagecodes>
</advancedsettings>
```
2.  Added a video to library in mkv format with mkv language set to fr-CA for the audio stream.  Per the code, I set the title as Test (fr-CA) and some variations (like filename as well)
3.  Playing the video results in Kodi showing French as the audio stream language

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ucutucifik.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Watching code run I never see langCode = g_LangCodeExpander.FindLanguageCodeWithSubtag(title->value) getting called, but maybe I am not looking at it right.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: VS 2022 built from kodi.sln on Win 10 x64 22H2
 - Kodi version: Master as of f5ab9fd5d2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
> Added a video to library in mkv format with mkv language set to fr-CA for the audio stream

you cant, as first you have to make sure that current ffmpeg version has implemented reading LanguageIETF element field
otherwise cannot be read, fwik the Language element field cant read expanded lang codes

that pr implement add a kind of workaround that consist in to add in to the _title_ field of mkv the expanded language code
so edit your mkv and add `(fr-CA)` at the end of _title_ element field, when detected will be used instead of Language element field

**Comment by scott967** [comment]
Tried that no success.  Here is what ffmpeg logs:
```
debug <general>: CDVDDemuxFFmpeg::Open - probing detected format [matroska,webm]
debug <general>: CDVDDemuxFFmpeg::Open - avformat_find_stream_info starting
debug <general>: Thread BackgroundLoader 25000 terminating
debug <general>: CDVDDemuxFFmpeg::Open - av_find_stream_info finished
info <general>: ffmpeg[0x196e7bf1c80]: Input #0, matroska,webm, from 'C:\Users\scottZ397\Videos\2023-08-24 11-20-03.mkv':
info <general>: ffmpeg[0x196e7bf1c80]:   Metadata:
info <general>: ffmpeg[0x196e7bf1c80]:     title           : Test 01 (fr-CA)
info <general>: ffmpeg[0x196e7bf1c80]:     ENCODER         : Lavf60.3.100
info <general>: ffmpeg[0x196e7bf1c80]:   Duration: 00:00:09.38, start: 0.000000, bitrate: 190 kb/s
info <general>: ffmpeg[0x196e7bf1c80]:   Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 1k tbn
info <general>: ffmpeg[0x196e7bf1c80]:     Metadata:
info <general>: ffmpeg[0x196e7bf1c80]:       DURATION        : 00:00:09.376000000
info <general>: ffmpeg[0x196e7bf1c80]:   Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp
info <general>: ffmpeg[0x196e7bf1c80]:     Metadata:
info <general>: ffmpeg[0x196e7bf1c80]:       title           : Test 02 (fr-CA)
info <general>: ffmpeg[0x196e7bf1c80]:       DURATION        : 00:00:09.322000000
debug <general>: CDVDDemuxFFmpeg::AddStream ID: 0
debug <general>: CDVDDemuxFFmpeg::AddStream ID: 1
```

Did this with a "clean" mkv file.  Without a track language or language BCP47 or with language BCP47 fr-CA either way Kodi audio settings shows [unknown]
If you could post a working sample somewhere I could look at.

**Comment by CastagnaIT** [comment]
its possible that your mistake is remove in full the language code from streams
the current source code expect that the language must be set at least for the Language field

**Comment by Vouivre** [comment]
I can confirm it also works for me on Kodi 20.2 (Coreelec). To set the title I have used `ffmpeg 6.0`. I have a linux system. I have set the title to `Surround 7.1 (fr-CA)`.
