### ISSUE TITLE
Kodi stopped checking databases

### ISSUE THREAD

**Issue by TriVoxel** [xbmc/xbmc#23660]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I try to update my library, it just gets stuck on the first item queued for database scraping. The spinner just keeps going, and no progress is made. Even after deleting all the program data and retrying, it only spins on the first item it's trying to scrape, no progress. It worked last night, and doesn't work today. Is there something wrong with the TMDB API?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Databases should be scraped.

## Actual Behavior

Endless waiting.

### Debuglog

The debuglog can be found here:

```
No meaningful log messages generated.
```

### Your Environment
Used Operating system: Fedora Linux 38 Workstation Edition

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora Linux 38 Workstation Edition
 - Kodi version: 20.2 (from Flathub)

**Comment by TriVoxel** [comment]
Due to re-arranging my backups a lot, I could have possibly hit a bandwidth cap. Does that sound likely, or could this be a different problem entirely?

**Comment by TriVoxel** [comment]
If I use a VPN, I get an "error 13: permission denied". Seems like something's up with the API for these database sites being blocked, or limited?

**Comment by fuzzard** [comment]
You absolutely need to provide a debug log if you expect anything to happen here.

You have given such vague information, i dont know what you would expect around any support.
With what you have provided so far, i would think this is more a support question appropriate for the forums at this stage.

**Comment by TriVoxel** [comment]
> You absolutely need to provide a debug log if you expect anything to happen here.
> 
> You have given such vague information, i dont know what you would expect around any support. With what you have provided so far, i would think this is more a support question appropriate for the forums at this stage.

Sorry. I don't seem to get any sort of log out of it. It just gets stuck trying to scrape the database on the first title. I haven't had any issues up to this point, no major Kodi updates, and even tried clearing all the program data for a clean start. Like I said, with a VPN, it doesn't just get stuck on the first item it tries to scrape off the database, it actually just errors out on each entry with an "error 13: permission denied" error in a notification. It seems to be a simple DOS of some sort. I'm sorry, but this is all the information I can provide at the moment. If you have any ideas of how I could debug this scraper issue further, I'd be open to testing it. Do you have any problems scraping titles from TMDB in Kodi right now?

**Comment by TriVoxel** [comment]
Okay, it seems like I might have been IP banned for making too many requests to the DB. I've been backing up my DVD collection, and have been adding, scraping, moving, cleaning, and re-adding everything. I've probably just racked up enough API calls from my IP due to re-organizing and renaming alone, that my IP got de-prioritized, or blocked from the service. I should probably have thought about my organization better from the start haha
