### ISSUE TITLE
Please adapt the kodi software that vr devices can also use, thank you.

### ISSUE THREAD

**Issue by bike3097a** [xbmc/xbmc#23663]
### Describe the bug
Here is a clear and concise description of what the problem is:Please adapt the kodi software that vr devices can also use, thank you.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [✓] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by chewitt** [comment]
Feature requests should be made in the forums: https://forum.kodi.tv/forumdisplay.php?fid=9
