### ISSUE TITLE
Kodi crash and out when I try to enter to Kelebek (Linux Mint - Flatpak)

### ISSUE THREAD

**Issue by D4vRAM369** [xbmc/xbmc#23671]
### Describe the bug
Here is a clear and concise description of what the problem is: Kodi on Linux Mint Cinnamon, Flatpak name tv.kodi.Kodi and version 20.2-Nexus. It crashes when I open Kelebek. Happened 4 times, and a few times without trying enter Kelebek. I opened a new terminal to put the command flatpak run tv.kodi.Kodi to execute, and doesn't crash until I try to open Kelebek. Here I attach a crashlog generated and saved on /root/. This is the fail which gives me the terminal after close, since the command till the crash: 

```
flatpak run tv.kodi.Kodi
libva info: VA-API version 1.18.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_18
libva info: va_openDriver() returns 0
/app/bin/kodi: línea 182:     7 Segment violation  (`core' generated) ${KODI_BINARY} $SAVED_ARGS
Crash report available at /root/.var/app/tv.kodi.Kodi/data/kodi_crashlog-20230827_040554.log
```
 Is detailed above, and it's obviously some kind of bug for a reason which I unknown.

Ok, I would type the Kodi crashlog, because Idk how to attach files, or if that if even possible here. But is too long for the post. So I upload in this web, when I searched for upload text online: https://sharetext.me/eyvojzv1ks

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
 

That Kodi doesn't crash when I open Kelebek or in any other situation.

## Actual Behavior

Kodi crashed when I open Kelebek, and a few times after open it.

## Possible Fix

I don't know the fix, I only can attach the Kodi-crashlog for the staff or progammers-volunteers can examinate it and maybe solve this issue.

### To Reproduce

1.  Open the Kodi mentioned on Linux Mint.
2. Download the Kelebek of the Newkelebek source (the source which works nowadays)
3. Try to enter on it when is installed
4. Maybe, you would can't do it

### Debuglog
 That is the crashlog, isn't? Is attached at top.

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system: 

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux Mint Cinnamon
 - Kodi version: 20.2-Nexus (Flatpak on Software Manager, integrated on Mint)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
Piracy is not supported.
