### ISSUE TITLE
spdlog updated making Kodi stop starting

### ISSUE THREAD

**Issue by cg00001** [xbmc/xbmc#23688]
### Describe the bug
Here is a clear and concise description of what the problem is:
Kodi doesn't start because spdlog update to libspdlog.so.1.12, Kodi expects libspdlog.so.1.11.

Kodi will not start without the fix below.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should start without errors.

## Actual Behavior

Kodi gives an error:

> ~►kodi
> /usr/lib/kodi/kodi.bin: error while loading shared libraries: libspdlog.so.1.11: cannot open shared object file: No such file or directory

## Possible Fix

In Arch Linux, enter /usr/lib/ folder, find libspdlog.so.1.12, make a link from it and name it libspdlog.so.1.11.

### To Reproduce

1. Try to start Kodi.

### Debuglog

The debuglog can be found here:
Debuglog can not be created when Kodi doesn't start.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi Omega Alpha 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
You will need to recompile kodi against the new spdlog lib. There is no fault with kodi here
