### ISSUE TITLE
webdav over https broken

### ISSUE THREAD

**Issue by Dummgelaufen007** [xbmc/xbmc#23698]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Want use Kodi on Android or Linux and cannot connect to WebDav over https

Setting:

Qnap TS-673A for WebDav and Authentication
nginx on a Linux Server for SSL as proxy
Kodi on Ubuntu 22.04 LTS install via team-xmbc-ubuntu-ppa-jammy
Kodi on Android 12 via Google Play Store

## Actual Behavior

Add a new video source as webdav http an can connect to server. Same server, same credentials, other port for https, kodi get no directory. On Android with Total Commander and WebDAV plugin the settings work. Or WinSCP on Windows.

### To Reproduce

1. 
2.
3.

### Debuglog

Logfile Ubuntu: https://paste.kodi.tv/obeqawulun.kodi
Logfie Android: https://paste.kodi.tv/asuvororid.kodi
Logfile nginx: https://paste.kodi.tv/oxidiwixep

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android 12
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux Ubuntu 22.04 LTS
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment]
Looks like another http2 issue. Please try disabling http2 in Kodi's advancedsettings.xml : https://kodi.wiki/view/Advancedsettings.xml

**Comment by Dummgelaufen007** [comment]
Disabled HTTP2 on nginx. easier then become advancedsettings on every device.

thanks for support
