### ISSUE TITLE
Video library scan wakes screensaver

### ISSUE THREAD

**Issue by ryanfelder** [xbmc/xbmc#23708]
### Describe the bug
Here is a clear and concise description of what the problem is:

Whether I am using the library auto-update scan or if I trigger a library scan via web RPC, scanning my video library causes my kodi screensaver (Black) to wake. I run Kodi on the TV in my living room, and this causes my TV to come alive multiple times a day when nobody is interacting with it. I have library scan notifications disabled. I have experienced this on LibreElec 11 on a Raspberry Pi and on Kodi 20 for Windows on Windows 11.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should scan my video library without waking the screensaver

## Actual Behavior

Kodi wakes from screensaver mode when a library scan takes place

### To Reproduce

1. Enable a screensaver, I use 'Black'
2. Enable web RPC in kodi or enable the library auto-update plugin
3. Wait for the screensaver to activate
4. Trigger a video library scan via web RPC or wait for library auto-update to trigger a video library scan
5. Observe the screensaver wakes

### Debuglog

The debuglog can be found here:

https://pastebin.com/CgrzyM96

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 and Linux
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
I highly guess, the problem here is, that the skin gets a refresh after the library scan which then triggers Kodi to deactivate the screensaver and then the TV gets a signal to turn on via CEC. 

Is there any option to configure CEC in Kodi in a way it doesn't turn the TV for specific conditions?

Others are pleased to get a skin refresh after refreshing the database. Otherwise they won't see new movies before a Kodi restart.

**Comment by ryanfelder** [comment]
A couple of details I'd like to add. 

- This appears to happen both with and without CEC. My livingroom pc does not support CEC, my bedroom pc does.
- I have verified this behavior occurs even with the default skin

I do think you're onto something with the skin refresh, just wanted to clarify in case my log was indicating I was running a non-default theme.

**Comment by DaVukovic** [comment]
>This appears to happen both with and without CEC. My livingroom pc does not support CEC, my bedroom pc does.

Could you please be so kind and explain how your Kodi device is able to automatically turn on your TV without supporting CEC? TBH I don't know of any other option a Kodi client is able to turn on a TV automatically. So I'm really wondering how you got this managed.

The skin-refresh happens after every library update for every skin in use. This is not specific to the default skin or any other skin. It's a core function which applies to any skin in use.

**Comment by ryanfelder** [comment]
In my livingroom the TV does not turn off, the screensaver "Black" activates instead. During a library scan, this screensaver wakes.

In my bedroom, the TV does turn off via CEC. I rarely use that TV so I am only about 98% certain that it also wakes during library scan to be honest.

But the main issue is not the TV powering on and off, it is the screensaver waking. I will go verify the CEC behavior now.

**Comment by ryanfelder** [comment]
Confirmed. 

On the CEC enabled PC, the TV and sound bar power back on at the _end_ of a library scan. Probably about the time of the skin refresh. Not something I want to have happen when I'm trying to fall asleep.

On the non-CEC enabled PC, the screensaver simply wakes. Both behaviors are the subject of this bug report.

It should probably go without saying that the reason I would want to do a library auto-update is so I can see my new shows and movies listed in my skin, so the skin refresh is still something I would like to have occur, I just want it to happen silently and without waking my screensaver or powering on my tv.

**Comment by DaVukovic** [comment]
>It should probably go without saying that the reason I would want to do a library update is so I can see my new shows and movies listed in my skin,

I fully understand that. 

>so the skin refresh is still something I would like to have occur, I just want it to happen silently and without waking my screensaver or powering on my tv.

Which is not possible at the moment. A skin refresh means everything skin-wise is being refreshed. That includes the screensaver and its time to jump in. 

For me, this is not a bug as it's intended behavior. 

OTOH I would agree that this would be a nice feature. And that's the full point on this report. For me it's more a feature request rather than a bug report. The reasons for that (at least from my POV) are:

* the skin refresh is done by Kodi core code and it's needed to make new content visible at the library after an update
* the screensaver is part of the skin
* currently a setting like "if a screensaver is active, don't deactivate it after a library update" doesn't exist

I would suggest to have a look at the CEC settings if such a condition probably already exists. If not, I would suggest to open a feature request at the forums: https://forum.kodi.tv/forumdisplay.php?fid=9

**Comment by ryanfelder** [comment]
I have done some preliminary testing and it appears that in Kodi 18 a library scan did not cause the screensaver to wake. 

This appears to be a bug and a regression unless you can point me to where this change was intentionally made.

I will do some more testing to confirm whether this behavior changed in 19 or 20.

**Comment by ryanfelder** [comment]
I have done a fresh install of Kodi 19 and confirmed that a library scan does _not_ wake the screensaver (Black).
This behavior only occurs in Kodi 20.

**Comment by ryanfelder** [comment]
Interesting update, this behavior does not appear to happen in the Kodi 21 Alpha 3 I just installed.

Assuming this does not re-emerge in Kodi 21, I will hopefully have my issue resolved once 21 is finalized.

**Comment by thexai** [comment]
> Interesting update, this behavior does not appear to happen in the Kodi 21 Alpha 3 I just installed.
> 
> Assuming this does not re-emerge in Kodi 21, I will hopefully have my issue resolved once 21 is finalized.

Closing it because version v20 no longer receives support or maintenance.
