### ISSUE TITLE
[Linux] Latest Beta Media Library Does Not Load

### ISSUE THREAD

**Issue by nekromantik** [xbmc/xbmc#23718]
### Describe the bug
Since Librelec beta merged Kodi changes to pkg version "aaef1a0d1e37ff87361011fd48c89d9e69ec9a9d" my library no longer loads. both TV Show and movies no longer are in Kodi. Even after going into media library settings and seeing media type is set to none I changed to Movie or TV series and re fleshed but still library does not show. 

## Expected Behavior
library is displayed

## Actual Behavior
Library missing in all skins

## Possible Fix
n/a

### To Reproduce
Update to lateat version

### Debuglog
https://paste.kodi.tv/umejedapip.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:  beta

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
```
error <general>: SQL: Can't create database for copy: 'MyVideos121' (1007)
```

Something's wrong on your SQL server.

**Comment by nekromantik** [comment]
> ```
> error <general>: SQL: Can't create database for copy: 'MyVideos121' (1007)
> ```
> 
> Something's wrong on your SQL server.

thats odd I am using same user as previous build of Kodi which is fine, If i roll back to previous version I get no issues,
Also DB already exists.

**Comment by nekromantik** [comment]
issue was i needed to upgrade mysql version
