### ISSUE TITLE
[Windows] Seeking broken on certain files

### ISSUE THREAD

**Issue by stumpalump** [xbmc/xbmc#23712]
### Describe the bug
Here is a clear and concise description of what the problem is:
Seeking seems to be broken for me on Windows since last week (only on some files). I build myself with latest PRs every few days. At first I thought it was just MP4 files but in testing I've found that some MP4 files work just fine so I'm not sure if it's the codec being used or what. This morning I did a test with some files that are basically the same video just different containers/formats. The MP4 files were working fine and the MKV container was causing the videoplayer to essentially crash on seeking with log message "CDVDMsgGeneralSynchronize - global timeout". Not sure if it's related but I noticed Kodi is not extracting thumbs on the files where seeking is also broken.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
I have a build from Aug 20, 2023 that is working fine. Issue seems to have started since the PR relating to ifdef #23634  but of course I don't want to blame this PR specifically.

## Actual Behavior
On certain files, seeking forward/backward will cause indefinite "Buffering..." and/or videplayer crash back to Kodi menu.

## Possible Fix
I'm sorry I'm not that smart

### To Reproduce
1.  Sample files I used here https://filesamples.com/formats/mkv and https://filesamples.com/formats/avi
2.  Find some files where thumbnails won't load and try step forward/back during playback.
3.  HDR Autoswitch enabled, VSR enabled, HPP enabled

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/nebumoyisa.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:
Not able to screenshot while videoplayer is crashing due to screen reset event

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 Pro Version 10.0.22631 Build 22631
 - Kodi version: 21.0-ALPHA2 (20.90.201) Git:20230901-bf184b9184
 - Intel i7, RTX 3080 Ti, 32GB RAM
 - Samsung 8k OLED TV

**Comment by fritsch** [comment]
Thanks much for your report. #23709 should fix it.

**Comment by stumpalump** [comment]
Oh great thank you! I'll be sure to test
