### ISSUE TITLE
Setting to Choose action when item is selected not honoured for home screen widgets

### ISSUE THREAD

**Issue by Long-Man** [xbmc/xbmc#23722]
## Bug report
Movie or music video plays or present resume dialog but no option to show information.
Works as expected for episodes.
### Describe the bug
If the Settings>Media>Videos>Default Select Action is set to "Choose". When a music video or movie if selected from a widget, it does not offer the option to show information. It either play immediately or if there is a resume point, offers the resume dialog but without the option to show information.
As a comparison, episodes gives either Play/Show Info or Resume/Beginning/Show info when selected
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Present dialog to either Play/Show Info or Resume/Beginning/Show info when selected

### To Reproduce

1. Settings>Media>Videos>Default Select Action is set to "Choose"
2. Click on a music video widget or movie widget
3. Compare behaviour with tv show widget

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux (LibreELEC)
 - [ ] macOS
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
 Master as at Sep 3, 2023

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
> Click on a music video widget or movie widget

What exactly do you mean with "widget"?

**Comment by Long-Man** [comment]
Home screen widget. Actually did test the library views.

**Comment by Long-Man** [comment]
The library views are fine. It is the Home screen widgets that have the problem

**Comment by ksooo** [comment]
> As a comparison, episodes gives either Play/Show Info or Resume/Beginning/Show info when selected

I don't think so and cannot reproduce this. Episodes behave as movies and music videos and do also NOT respect the setting value.

**Comment by Long-Man** [comment]
You are correct

**Comment by ksooo** [comment]
Side note: Video default select action handling for Estuary Home screen Favorites widget, Favorites window, (deprecated Favorites dialog) is still pending. This will be a bit more work and might come with a follow-up PR.
