### ISSUE TITLE
Show Information No Longer Works for Music Videos

### ISSUE THREAD

**Issue by Long-Man** [xbmc/xbmc#23720]
## Bug report
"No Information Available" for music videos when selected from widgets
### Describe the bug
If the Settings>Media>Videos>Default Select Action is set to "Show Information", music videos returns "No Information Available" while movies and tv shows work as expected.
I am using LibreELEC problem first appeared after kodi was updated.
PKG_VERSION="aaef1a0d1e37ff87361011fd48c89d9e69ec9a9d" 

Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video info page for the music video should be displayed as it does for movies and tv shows.

### To Reproduce

1. Settings>Media>Videos>Default Select Action is set to "Show Information"
2. Click on a music video widget
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
> PKG_VERSION="aaef1a0d1e37ff87361011fd48c89d9e69ec9a9d"

Which Kodi version is included in this LE version?

**Comment by Long-Man** [comment]
I think it this commit that is the point

**Comment by ksooo** [comment]
I don’t think so. Stop guessing, please.  I asked you for the Kodi version that comes with your LE version. Would you be able to apply a patch and to build yourself?

**Comment by Long-Man** [comment]
I can build. But I could also test on windows. 

Actually it was not a guess. That is the commit to master that the build is based on.
https://github.com/LibreELEC/LibreELEC.tv/pull/8084/commits/13135355d8fb93d8ba444d309cbdeba72a1be0b2

**Comment by ksooo** [comment]
Okay, I will provide you a windows test build, based on latest Kodi master, once I have something to share.

**Comment by ksooo** [comment]
@Long-Man here is a Windows 64 test build for you, based on latest Kodi master, with a potential fix on top. Can you try and report back here? => http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20230904-406cbecc-video-fix-musicvideo-info-x64.exe

**Comment by Long-Man** [comment]
When the setting is Show Info, Resume or Play, it works as expected. 
When it is Choose, it plays instead of presenting the dialog to choose, and similarly for queue, it plays. (replace item that is playing)

**Comment by Long-Man** [comment]
Thanks for looking into this. I appreciate it

**Comment by ksooo** [comment]
> When the setting is Show Info, Resume or Play, it works as expected.

So, the issue as reported here is fixed with the test build.

> When it is Choose, it plays instead of presenting the dialog to choose, and similarly for queue, it plays. (replace item that is playing)

 Is this behavior new with my test build or does it also act like this with the normal build? If this is not introduced by ma test build, please open a new issue.

**Comment by Long-Man** [comment]
You're right it existed in the LibreELEC build immediately before that update. So the issue reported here is fixed.

Thanks.
