### ISSUE TITLE
scan to video library fails with "No information found"

### ISSUE THREAD

**Issue by rschupp** [xbmc/xbmc#23732]
### Describe the bug
Here is a clear and concise description of what the problem is:

"Scan to library" on a directory containing a movie file (mp4) doesn't work anymore.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

1. go to Videos
2. select a movie source 
3. select a directory 
![scr0](https://github.com/xbmc/xbmc/assets/5570160/028c2c8b-7b26-464b-a310-0bd00e2497d3)

4. choose "Scan to library" from the context menu
![scr1](https://github.com/xbmc/xbmc/assets/5570160/0a173cc7-4e21-4850-a114-f9200e7852cb)

5. "Select movie" with possible matches from TMDB is shown, in this case there's only one match (already selectred)
![scr2](https://github.com/xbmc/xbmc/assets/5570160/456b6964-903a-494c-a315-bc3a80fdc069)

6. press RETURN

7. the movie is added to the library

## Actual Behavior

6. an error message is shown
![scr3](https://github.com/xbmc/xbmc/assets/5570160/623839ae-43df-4c30-800c-2673978f515d)

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ehakinohom

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian 12
 - Kodi version: Omega as of 2023-09-07 279cedb

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
You learn something new every day. Did not even know that one can select "Scan to library" on a directory. Confirming the issue...

**Comment by ksooo** [comment]
> doesn't work anymore.

@rschupp can you say which with version it worked last for you?

**Comment by rschupp** [comment]
It worked in [21.0a2-Omega](https://github.com/xbmc/xbmc/releases/tag/21.0a2-Omega), but broke in aaef1a0.
