### ISSUE TITLE
Bool Condition System.HasNetwork is always true

### ISSUE THREAD

**Issue by b-jesch** [xbmc/xbmc#23735]
### Describe the bug
Here is a clear and concise description of what the problem is:

As the topic says the boolean condition System.HasNetwork is always true, independent if network cable is connected or not.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Condition should be false if network is diconnected (cable/wlan).

### To Reproduce

1. Put some code somewhere on your home.xml (I did this in Includes.xml):

```
					<control type="label">
						<top>3</top>
						<width>250</width>
						<height>30</height>
						<label>| Net av.</label>
						<visible>System.HasNetwork</visible>
					</control>
					<control type="label">
						<top>3</top>
						<width>250</width>
						<height>30</height>
						<label>| Net n/a</label>
						<visible>!System.HasNetwork</visible>
					</control>
```
2. Reload skin, You'll see that always "Net av." will shown, independent if network cable has plugged in/out

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 20.04.6 LTS
 - Kodi version: 21.0-alpha1, but happens too on 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
https://github.com/xbmc/xbmc/blob/4d639b82d1c9830eb4a010690432f75cc4d756af/xbmc/guilib/guiinfo/SystemGUIInfo.cpp#L422-L425

So as wild as it is, not a bug, its just not implemented.
Wiki probably needs to be updated with that info i guess.
