### ISSUE TITLE
CMake, Build: -DENABLE_INTERNAL_DAV1D=ON causes configuration error

### ISSUE THREAD

**Issue by CS-Alchemist** [xbmc/xbmc#23743]
### Describe the bug

Here is a clear and concise description of what the problem is:
When configuring kodi with the argument -DENABLE_INTERNAL_DAV1D=ON, errors occur.

I suspect that the target "dav1d" is defined twice. Once by "cmake/scripts/common/Macros.cmake:376 (find_package)" and once by "cmake/modules/FindFFMPEG.cmake:34 (find_package)". I have output two messages in the "FindDav1d.cmake", one contains a trace message-type.

The log can be seen in the following.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should build with internal libdav1d

## Actual Behavior

it is not possible to build with -DENABLE_INTERNAL_DAV1D=ON.

### To Reproduce

1.  I used following command:
 ```
$cmake ../xbmc/ -DCMAKE_INSTALL_PREFIX=/usr/local -DCORE_PLATFORM_NAME=gbm -DAPP_RENDER_SYSTEM=gles -DENABLE_INTERNAL_FFMPEG=ON -DENABLE_INTERNAL_DAV1D=ON
``` 
3.
4.

### Debuglog

The debuglog can be found here:
[cmake-dav1d-error.txt](https://github.com/xbmc/xbmc/files/12567955/cmake-dav1d-error.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: current alpha3 and master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CS-Alchemist** [comment]
removing line 34 in "cmake/modules/FindFFMPEG.cmake" seems to fix my problem

**Comment by the-black-eagle** [comment]
Indeed.  Having removed -DENABLE_INTERNAL_DAV1D, I now have an error with FFMPEG.
```-- Could NOT find Dav1d (missing: DAV1D_LIBRARY DAV1D_INCLUDE_DIR) (Required is at least version "1.1.0")
-- dav1d not found, internal ffmpeg build will be missing AV1 support!
CMake Error at cmake/modules/FindFFMPEG.cmake:127 (add_library):
  add_library cannot create imported target "ffmpeg::libavcodec" because
  another target with the same name already exists.
Call Stack (most recent call first):
  cmake/modules/FindFFMPEG.cmake:387 (buildFFMPEG)
  cmake/scripts/common/Macros.cmake:376 (find_package)
  cmake/scripts/common/Macros.cmake:390 (find_package_with_ver)
  CMakeLists.txt:226 (core_require_dep)```

@fuzzard or anyone else that might have a quick fix!

**Comment by CS-Alchemist** [comment]
For the record, I would like to share my findings here again:

The current problem is that with -DENABLE_INTERNAL_FFMPEG=ON and -DENABLE_INTERNAL_DAV1D=ON there are errors in the cmake configuration.

The cause is the repeated call of find_package(dav1d ...) in build scripts.

In order not to rule out any other error causes, I would like to build kodi using two configurations as a test.
Once with:
\#1 
```
$cmake ../xbmc/ -DCMAKE_INSTALL_PREFIX=/usr/local -DCORE_PLATFORM_NAME="x11" -DAPP_RENDER_SYSTEM=gl -DENABLE_INTERNAL_FFMPEG=ON -DENABLE_INTERNAL_DAV1D=ON
```

and \#2
```
$cmake ../xbmc/ -DCMAKE_INSTALL_PREFIX=/usr/local -DCORE_PLATFORM_NAME="x11" -DAPP_RENDER_SYSTEM=gl -DENABLE_INTERNAL_FFMPEG=ON -DENABLE_INTERNAL_DAV1D=OFF
```

This time I made sure that my build environment for -DENABLE_INTERNAL_DAV1D=OFF meets all the necessary requirements.
Therefore I built libdav1d with the 1.1.0 version and provided it in ${libdir}.

No adjustments have been made in Kodi so far. It is built with the current master.

Case #1 generates the configuration error for me.
Case #2 does not. Everything is fine here and the dynamic libdav1d.so can be found.

I have now created a patch for FindFFMPEG.cmake. Here, before find_package, it is checked whether Dav1d has already been found. If david was not found, find_package is also executed as before.

This way, building works for me in both cases.

The Patch:
[FFMPEG_DAV1D_find_package.patch.txt](https://github.com/xbmc/xbmc/files/12569762/FFMPEG_DAV1D_find_package.patch.txt)

**Comment by CS-Alchemist** [comment]
I would like to mention, however, that the patch does not solve the actual problem.

For me, the problem is that the target for dav1d is defined in two different places. In contrast to make, cmake does not seem to allow overwriting of targets here.

The fact that FindFFMPEG searches for dav1d here and ensures that the library is available makes perfect sense to me.
But is dav1d also used as a dependency in other tools besides ffmpeg?

Where else is the target for dav1d defined? I could only follow this in FindFFMPEG, but why is this previously defined by cmake/scripts/common/Macros.cmake:376 (see trace in log)?

I could imagine that there is a smarter way to solve the problem here.
I would be happy if someone could take a look at this.

**Comment by fuzzard** [comment]
https://github.com/xbmc/xbmc/pull/23746 Should fix it. try it and let me know.

**Comment by CS-Alchemist** [comment]
Both cases work.
Both during configuration, building and playback.

Thanks @fuzzard for your time and hard work to solve this

**Comment by CS-Alchemist** [comment]
But as in the conversation in the pull request #23746, the installation does not work. The error message is the same.
