### ISSUE TITLE
Kodi v21 ignore external subtitle file 

### ISSUE THREAD

**Issue by Nanomani** [xbmc/xbmc#23763]
### Describe the bug

when I scrappe a new movie with his external subtitle file the table "streamdetails" is not updated.

This information in table "streamdetails"is useful. 
Some skin manage this value to display a flag indicating if there is a subtitle and the language.

![227765106-b3ad787a-6668-439e-81f0-a7d31f706c57](https://github.com/xbmc/xbmc/assets/3939543/b6d34955-4f93-49b6-a476-df6188a4a4aa)

Or if we create a Smart playlists linked with this value.

![227765142-03712481-32de-44f9-8131-25754f0375b2](https://github.com/xbmc/xbmc/assets/3939543/a4437020-5b27-4f8f-9796-8e9a37e52cbd)

## Expected Behavior

I expect the same behaviour with Kodi v21 than Kodi v20. 

with Kodi v20  table "streamdetails" is updated : 

![2023-09-13_013641](https://github.com/xbmc/xbmc/assets/3939543/a7e7c0d3-3858-4f4c-9763-006dd8d7876b)

## Actual Behavior

with Kodi v21 table "streamdetails" is not updated at all : 

![v21](https://github.com/xbmc/xbmc/assets/3939543/34100dd5-bbcf-447f-a5f8-8b08bedc3207)

## Possible Fix

no idea

### To Reproduce

(I don't use local file nfo)

1 - install kodi from scratch
2 - keep all Kodi default settings. nothing more
3 - add source with 1 movie folder with external subtitle file
4 - update library

eg :
Demons (1985)
\ Demons (1985).mp4
\ Demons (1985).fr.srt

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/kewucoceji.kodi

### Your Environment
 - [X] Windows

 - Operating system version/name: Windows 11 x64
  - Kodi version: tested with the oldest and the lastest Kodi v21 version downloadable actualy : 
 
oldest : 20230802-89cc33615d
lastest : 20230911-327fd819

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Nanomani** [comment]
@enen92 
your fix works perfectly
better than before, this old issue is fixed too : https://github.com/xbmc/xbmc/issues/22447
thanks you 👍

**Comment by enen92** [comment]
You're welcome.
Thanks for linking the other issue :)
