### ISSUE TITLE
Image caching is not working correctly in latest 21.0a3

### ISSUE THREAD

**Issue by xconverge** [xbmc/xbmc#23765]
### Describe the bug

Kodi (with [PlexKodiConnect](https://github.com/croneter/PlexKodiConnect), I think this might be important due to the way it fetches art?) is basically constantly refetching art and images and never hitting the cache. I "think" that basically nothing is getting into the cache.

I suspect related to the chain of changes related to https://github.com/xbmc/xbmc/pull/23567 or https://github.com/xbmc/xbmc/pull/23134 but am unsure if all art is impacted by this or just generated thumbnails. If this is totally wrong/unrelated I will edit and remove this to avoid confusion

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

1. Open Movies or TV shows wall view
2. All images slowly pop in one at a time
3. Navigate back to Home screen
4. Re-open movies or tv shows wall view
5. All images pop in quickly because they have not changed and are in the cache

## Actual Behavior

1. Open Movies or TV shows wall view
2. All images slowly pop in one at a time
3. Navigate back to Home screen
4. Re-open movies or tv shows wall view
5. All images slowly pop in one at a time

### To Reproduce

See above

### Debuglog

N/A yet

### Screenshots
Here are some links or screenshots to help explain the problem:

N/A yet

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A yet

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Kodi version: 21.0a3 (this did not happen to me in 21.0a2 I don't think). I have reverted to 20.2 and the problem goes away

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by xconverge** [comment]
@rmrector do you have any ideas here or more information that I could provide? I have reverted for now but can reinstall the nightly or 21.0a3 to get more information

**Comment by rmrector** [comment]
Ya, I had a bug in video thumb generation that made it into alpha 3.

#23639 includes a fix for generated images.

**Comment by xconverge** [comment]
> Ya, I had a bug in video thumb generation that made it into alpha 3.
> 
> #23639 includes a fix for generated images.

ah cool, was it this? https://github.com/xbmc/xbmc/pull/23639/commits/c7115e0ae6b857aa2a61b3ad80eeae52d89935e5

**Comment by thexai** [comment]
> All images slowly pop in one at a time

This also happens on more standard setup (without PlexKodiConnect). 

I observed same with movies in NAS shared NFS. Every time is redraw main screen movie posters are re-generated and for some reason are also read video files from NAS every time. Even for movies not changed (i.e recently added section). 

Note this happens even if movie posters are not in NAS but handled by default local texture cache.

**Comment by rmrector** [comment]
merged. This will be fixed in the next nightly and in Beta 1. Thanks for the report.
