### ISSUE TITLE
Problem with Mobile Vertical Video .mp4 files when playing videos

### ISSUE THREAD

**Issue by Ronny-nerd** [xbmc/xbmc#23762]
Sorry my english is not so good.

Have a Problem with Mobile Vertical Video .mp4 files when playing videos via Windows 10 Pro ( PC ) and Android TV 11 ( Nvidia Shield TV ).

1. screenshot1 when playing the mobile vertical video via Kodi 21 Omega Alpha 3 ( 64 Bit ) = not OK.

![Screenshot1](https://github.com/xbmc/xbmc/assets/65504837/50a2ffe5-503a-4b69-bdf3-f2973236f9fe)

2. screenshot2 when playing the same vertical video via Kodi 20.2 Nexus ( 64 Bit ) = OK

![Screenshot2](https://github.com/xbmc/xbmc/assets/65504837/840cb2b8-28ef-4de9-a771-8506a48894cc)

3. mobile vertical videos play normally and not in landscape mode via Kodi Nexus 20.2 ...Kodi 19.5 Matrix and Kodi 18.9 Leia as well as VLC.

4. I have attached this vertical video .mp4 file as a .zip file here to screenshot1+2 so that you can test it yourself...e.g. under Linux or another operating system.

[VID-20230318-WA0000.zip](https://github.com/xbmc/xbmc/files/12591495/VID-20230318-WA0000.zip)

5. Kodi Debug LOG

[kodi.zip](https://github.com/xbmc/xbmc/files/12591551/kodi.zip)

Translated with www.DeepL.com/Translator (free version)

**Comment by fritsch** [comment]
Can you please disable mediacodec and mediacodec surface and try again?

**Comment by Ronny-nerd** [comment]
Hello fritsch, is that what you meant?
I have the Kodi 21 Omega options on the Nvidia Shield TV under
Settings/Player
Videos 
Allow hardware acceleration -MediaCodec (Surface) = deactivated
Allow hardware acceleration - MediaCodec = deactivated

and tried again with the same result when playing the videos.

**Comment by fritsch** [comment]
Thanks, exactly. Good, please add this log as well, with that it affects all platforms and is not android specific anymore.

**Comment by Ronny-nerd** [comment]
OK [https://paste.kodi.tv/bitiluhavi.kodi](url)

**Comment by CrystalP** [comment]
I noticed this some time ago and the orientation was not propagated from ffmpeg. It's side-data IIRC.

**Comment by Ronny-nerd** [comment]
I'm curious to see if this bug could be fixed in the future.

**Comment by Ronny-nerd** [comment]
Thanks enen92 and fritsch, with these new Kodi 21 Omega build ( kodi-20230927-31fb58e1-PR23832-arm64-v8a.apk ) the BUG is gone.
