### ISSUE TITLE
Wrong country name in Interface settings

### ISSUE THREAD

**Issue by sacrementalguru** [xbmc/xbmc#23773]
### Describe the bug
Here is a clear and concise description of what the problem is:

Users from the United Kingdom do not find their country listed. This delays setting up Kodi with the correct regional settings.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The United Kingdom should be listed as “United Kingdom” (not as “Britain”).

## Actual Behavior

Users from the UK are not searching for “Britain” just as “United States” user are not searching for “America”.

## Possible Fix

Remove “Britain” from the list and replace it with “United Kingdom”.

### To Reproduce

1. Try to find “United Kingdom” in the region settings.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Makes it difficult to setup United Kingdom for users in that region. It’s like calling “United States” America.

A post to the LibreELEC 

https://forum.libreelec.tv/thread/6794-britain-uk-is-incorrect-timezone-country-in-interface-settings/

From 2017.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Where do you see this?

**Comment by scott967** [comment]
This I assume is a setting only on Posix platforms: settings-interface-regional "unit formats" subgroup - timezone country setting.  (setting locale.timezonecountry)  (no wiki entry for this or related setting "timezone" BTW)

Not sure where the list of countries is retrieved from in linux but seems to be handled in PosixTimezone.cpp.  maybe from /usr/share/zoneinfo/iso3166.tab ?  (sorry, no linux access here).

**Comment by chewitt** [comment]
@sacrementalguru If you run "strings" against `/usr/share/zoneinfo/iso3166.tab` you'll find `GB	Britain (UK)` so Kodi is simply parsing and presenting the standardised Linux OS timezone data. As a fellow brit I completely agree it's not an intuitive naming, but it's not a Kodi (or LibreELEC) issue, and in that respect there's no bug.

**Comment by DaVukovic** [comment]
So I guess we're good to close this.
