### ISSUE TITLE
RSS-News not working anymore

### ISSUE THREAD

**Issue by ajbathe** [xbmc/xbmc#23781]
### Describe the bug
Here is a clear and concise description of what the problem is:

RSS-News are not displayed anymore, with Alpha1 (and Alpha2, but not 100% sure) the RSS-feeds were working.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

RSS-News are displayed.

## Actual Behavior

RSS-News are not displayed anymore.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC (community): nightly-20230915-73666c2 (RPi4.aarch64)
 - Kodi version: Kodi 21.0-ALPHA3 (20.90.301) Git:21.0a3-Omega

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
No steps to reproduce, no debuglog, no screenshots so this not exists...
