### ISSUE TITLE
Build issues with ninja again

### ISSUE THREAD

**Issue by mackal** [xbmc/xbmc#23792]
### Describe the bug
Here is a clear and concise description of what the problem is:

Ninja broken with #23779 

```
CMake Error:
  Running

   '/usr/bin/ninja' '-C' '/home/user/projects/xbmc/Buildninja' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:831: multiple rules generate build/Release/gen_skin.timestamp
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by howie-f** [comment]
confirmed. this happens at _CMake Generate_ stage
