### ISSUE TITLE
Compiling Kodi Dependencies from Git Source Fails on Raspberry Pi Bullseye

### ISSUE THREAD

**Issue by trekkertie** [xbmc/xbmc#23799]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a Raspberry Pi 4 with the latest version of Raspberry Pi OS Bullseye (03.05.2023) installed. I have cloned the repository and am following the instructions for building on Linux at https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md. Whilst building the crossguid dependency the process stops with an error message.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Building crossguid should complete without an error.

## Actual Behavior

The make process fails with the following error.

sudo make -C tools/depends/target/crossguid PREFIX=/usr/local
make: Entering directory '/home/preston/kodi/tools/depends/target/crossguid'
make -C native/build install
make[1]: Entering directory '/home/preston/kodi/tools/depends/target/crossguid/native/build'
make[1]: *** No rule to make target 'install'.  Stop.
make[1]: Leaving directory '/home/preston/kodi/tools/depends/target/crossguid/native/build'
make: *** [Makefile:54: .installed-native] Error 2
make: Leaving directory '/home/preston/kodi/tools/depends/target/crossguid'

## Possible Fix

Although the OS is the 32 bit version, the current Linux kernel 6.1.21-v8 is 64 bit. The error does not occur on an older 32 bit kernel. 

### To Reproduce

1. Clone xbmc Git repository
2. cd into kodi directory
3. Execute command sudo make -C tools/depends/target/crossguid PREFIX=/usr/local

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspberry Pi OS 03.05.2023
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by popcornmix** [comment]
If you think it is related to the 64-bit kernel, the add `arm_64bit=0` to /boot/config.txt and reboot.
Does it behave differently now?

**Comment by trekkertie** [comment]
That has worked perfectly. Thank you very much for your help.
