### ISSUE TITLE
AC4 audio doesn't play.

### ISSUE THREAD

**Issue by KyleSanderson** [xbmc/xbmc#23816]
### Describe the bug
Hardware:
```console
Content formats supported

Audio: xHE-AAC, AAC-LC, AAC+, eAAC+, AAC-ELD, MP3, AMR-NB, FLAC, PCM/WAV, Vorbis, Dolby AC3, eAC3 (Dolby Digital Plus), Dolby Atmos (EC3_JOC), Dolby AC4, Dolby MAT, Dolby TrueHD pass-through, MPEG-H pass-through, DTS HD pass-through;
```

## Expected Behavior
AC-4

## Actual Behavior
No audio.

## Possible Fix
https://github.com/FFmpeg/FFmpeg/commit/2bc65003e2861eeeeae4db828890df33d2fc037c

### To Reproduce
1. Play AC-4.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Omega Alpha 3.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
https://trac.ffmpeg.org/ticket/8349 looks like decoding still isn't in ffmpeg.

This isn't a bug in kodi, but a short coming of a lib (ffmpeg) that we use. Closing

**Comment by KyleSanderson** [comment]
> https://trac.ffmpeg.org/ticket/8349 looks like decoding still isn't in ffmpeg.
> 
> This isn't a bug in kodi, but a short coming of a lib (ffmpeg) that we use. Closing

The hardware and operating system on Android supports it. Muxing has been added to ffmpeg to rip the stream out for the next release... Anyway, dealers choice.

**Comment by garbear** [comment]
It's likely that we'll see an ffmpeg bump before release, would that enable AC4 support?

**Comment by KyleSanderson** [comment]
> It's likely that we'll see an ffmpeg bump before release, would that enable AC4 support?

No, there's some additional scaffolding in xbmc that needs to be completed.
