### ISSUE TITLE
 Server/NAS remote path access problem since installing Kodi v 20.2

### ISSUE THREAD

**Issue by Skyline-007** [xbmc/xbmc#23833]
**## Bug report**
**### Describe the bug**
Good morning

Since installing Kodi version 20.2

I am having a problem with adding source and my remote paths from my server.

All my sources are on the same server.

I no longer have access to some of my remote paths (my sources) from my server.

Here are my remote paths from my server

See picture:
![Sans titre2](https://github.com/xbmc/xbmc/assets/108820368/68570fed-4c29-4886-ad7a-d52dd7e7557a)

I don't have access to these remote paths:

ftp : // My server address : 21 / 1 Videos summer vacation
ftp : // My server address : 21 / 2 Videos winter holidays

Here is the error message:
![Sans titre1](https://github.com/xbmc/xbmc/assets/108820368/cdd50ec0-e893-4b57-b4b6-361e9a31dc18)

But I do have access to the last remote path added last from my server:
ftp : // My server address : 21 / Video

![Sans titre](https://github.com/xbmc/xbmc/assets/108820368/9356fca8-f7d8-41fd-9690-5152f057b7e9)

There must be an error that crept in somewhere during a minor update ?

Because before I had access to all my remote paths from my server on older versions of Kodi.

And I'm not the only one to be affected by this problem other people have the same problem to access their remote paths with their server and their NAS only the last source to add is accessible.

Thank you in advance for your answers.

Thanks again for all the work you have done

**### To Reproduce**
1. Add multiple sources (FTP) Video as written for the problem.

**### Debuglog**
The debuglog can be found here:
[Debug log](https://paste.kodi.tv/uqicilahoy.kodi)

**### Your Environment**
**Used Operating system:**
 - [x] Windows (Kodi 20.2)
 - [x] Android TV (Kodi 20.2)
 - [x] Raspberry Pi (LibreELEC)

 - Operating system version/name: Kodi 20.2 and Raspberry Pi libreELEC
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by chewitt** [comment]
This is a bug tracker not a user support channel. Please post a thread in the Kodi forums. Thanks.
