### ISSUE TITLE
<oninfo> Does not work for static content in list controls

### ISSUE THREAD

**Issue by jurialmunkey** [xbmc/xbmc#23838]
### Describe the bug
Here is a clear and concise description of what the problem is:

`<oninfo>` tags in a skin do not work for list controls when static `<content><item>` items are defined.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The `<oninfo>` action should be performed when pressing info on a list control with static content just like it does when using dynamic plugin content.

## Actual Behavior

Nothing happens when pressing info despite `<oninfo>` tags being defined in the list control.

### To Reproduce

In Estuary Home.xml add an `<oninfo>ActivateWindow(settings)</oninfo>` tag to the list control with id="9000" (Home side menu).

Pressing info on the side menu *should* now open settings when pressing info but nothing occurs.

I have also tested with placing `<oninfo>` inside the `<item>` tags, which also does nothing.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ugodujifop.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Omega Alpha 3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@jurialmunkey do you know if this is a regression or something that never worked? Asking because there were a couple of changes that touched oninfo() (not sure if backported). It'd be great if it could be validated in the current nighties too.

**Comment by jurialmunkey** [comment]
@enen92 Fairly sure it's a regression. It's been a while since I used it but I remember using it in older skins to popup a submenu.

Will test it on latest nightly once I'm back home from work later today and report back.

**Comment by jurialmunkey** [comment]
@enen92 - Confirming doesn't work on latest Windows nightly either:

```
Starting Kodi (21.0-ALPHA3 (20.90.301) Git:20230927-7e58d70dbe). Platform: Windows NT x86 64-bit
Using Release Kodi x64
Kodi compiled 2023-09-27 by MSVC 193431937 for Windows NT x86 64-bit version 10.0 (0x0A00000B)
Running on Windows 11 22H2, kernel: Windows NT x86 64-bit version 10.0.22621.2361
```

**Comment by fuzzard** [comment]
And it definitely worked in v20? Might be worthwhile just testing 21A1/A2 to try and narrow down the regression, as long as its proven to work in 20

**Comment by jurialmunkey** [comment]
Sorry, no I'm mistaken about it being a regression. 
Downloaded 20.2 and 19.0 to make sure and it only works on buttons not static items in a list.

In the past I used a convoluted workaround with a fake button to capture the input and then pass movement/selection to the list which would then bounce focus back.
