### ISSUE TITLE
HDR and DV (Dolby Vision) Support on Apple TV tvOS

### ISSUE THREAD

**Issue by rimonhanna** [xbmc/xbmc#23846]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi isn't able to render HDR or DV content properly on tvOS, it instead shows purple or pinkish hue over the video although Apple TV supports both formats, I understand that support needs to be added/implemented, it would be great for all of us tvOS and Kodi users out there if this gets picked up at some point in the roadmap, I for one would be really grateful.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi is able to play and render HDR and DV content correctly

## Actual Behavior

It shows a pink hue on the video and doesn't decode the HDR/DV data

### To Reproduce

1. Play or stream and HDR or DV content
2. 
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: tvOS 16 & 17
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
It's not implemented on tvos. There is a feature request in the forums, but I don't believe anyone is currently working on it.
