### ISSUE TITLE
[Kodi Nexus] Visualizations on Windows 7 partly not working

### ISSUE THREAD

**Issue by Yavos** [xbmc/xbmc#23865]
### Describe the bug
Here is a clear and concise description of what the problem is:

Multiple Visualizations on my Windows 7 System don't seem to work at all. Apparently it's related to vertex shaders as all of the plugins show the same error in the log files (see below). I didn't test all of them, but here's a list.

Working:
- MilkDrop 2
- Spectrum
- Waveform

Not working:
- FishBMC
- PictureIt
- ProjectM (crashes Kodi)
- Shadertoy
- Starburst

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

All visualizations from the Kodi repo should be working and no error messages in the log files should appear.

## Actual Behavior

The visualizations only show a black screen (OSD is shown). The log file shows errors containing lines like these:
```
2023-10-03 22:12:55.587 T:41916   error <general>: AddOnLog: visualization.fishbmc: GLonDX: unable to create vertex shader
2023-10-03 22:12:55.587 T:41916   error <general>: AddOnLog: visualization.fishbmc: GLonDX: unable to create vertex shader view
2023-10-03 22:12:55.753 T:41916   error <general>: AddOnLog: visualization.fishbmc: CVertexShader::kodi::gui::gl::CVertexShader::Compile: ©
2023-10-03 22:12:55.753 T:41916   error <general>: AddOnLog: visualization.fishbmc: GL: Error compiling vertex shader
```

## Possible Fix

No idea. Might be a problem possibly fixed by updating to Windows 10.

### To Reproduce

1. Run Kodi on a (my) Windows 7 (x64) system (Can't test any other device as none of them has Windows 7 anymore)
2. Play music with visualization from the non-working list (see at top)
3. See shader not working

### Debuglog

The entire debuglog can be found here:
https://pastebin.com/raw/XEAt8LHV

Errors start showing up starting at `2023-10-03 22:11:18.30`
(At the end of the file I enabled debug mode but it didn't really add any useful information.)

### Screenshots 
Here are some links or screenshots to help explain the problem:

I think black screens don't need a screenshot.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 7 x64
 - Kodi version: 20.2
 - Graphics card: NVIDIA GeForce GTX 1060 6GB (might be useful since it's something about OpenGL as far as I understand)

**Comment by Yavos** [comment]
The working visualizations all seem to have a DirectX variant and a OpenGL variant. (I'm just looking at the source code not understanding a lot.) It's probably the DirectX version working.

**Comment by thexai** [comment]
The minimal Windows version supported in Omega is Windows 8.1 and Nexus currently only receives fixes backported from Omega, so there is zero chance that Nexus will receive specific fixes for Windows 7 only.
