### ISSUE TITLE
Folder items in widgets are playing/queueing instead of opening folder.

### ISSUE THREAD

**Issue by jurialmunkey** [xbmc/xbmc#23868]
### Describe the bug
Here is a clear and concise description of what the problem is:

On latest windows nightly, widgets with folder items are playing/queueing their content instead of opening the folder.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

An item with ListItem.IsFolder should open the folder in the relevant media window.
i.e. `ActivateWindow(TARGET,PATH,return)`

## Actual Behavior

The folder is playing/queueing the content it contains.
i.e. `PlayMedia(PATH)`

### To Reproduce

1. Open Estuary 
2. Go to Home > Movies > Genres
3. Click a genre and it starts playing instead of opening the genre folder.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/fujijitozu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Click here and playback starts instead of opening "Science Fiction" folder in MyVideoNav.xml

![screenshot00142](https://github.com/xbmc/xbmc/assets/4618719/d5a1693f-765a-4bcd-a800-5d9734983c01)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Omega v21 Nightly (2023-10-03)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jurialmunkey** [comment]
FYI This doesn't occur on the previous nightly (30-Sep). So the behaviour was introduced somewhere between 30-Sep (72dfef5b) and 03-Oct (35680593)

**Comment by ksooo** [comment]
Thanks, I also already spotted this. Will be fixed in #23863.

**Comment by ksooo** [comment]
Fix has been merged.
