### ISSUE TITLE
Linux/Wayland: Offload video to subsurfaces / hardware planes

### ISSUE THREAD

**Issue by rmader** [xbmc/xbmc#23874]
Wayland, given that the compositor supports it, allows apps to directly submit video buffers - e.g. in NV12 or P010 pixel formats - to the compositor, additionally scaling and cropping. The compositor will then try to further offload these operations (color conversion, scaling etc.) to KMS / the display hardware. In the (hopefully near) future, this will also me true for HDR content - i.e. doing color correction if necessary or setting up the display hardware accordingly for the content.

Adding support for this to Kodi would have several benefits:
1. Allowing Kodi to use advanced hardware features while using of a comparably high level API, similar to that of other platforms (MacOS/Android/Windows).
2. Allowing users to do so from a regular Wayland session. This would allow Kodi to have first-class performance on devices like Chromebooks, the SteamDeck and, of course, regular Linux computers.
3. Possibly making the GBM platform redundant in the long run, which most likely replicates a lot of Wayland compositor code.

Some examples of apps already supporting this:
 - `mpv` with the `vo_dmabuf_wayland` backend
 - Chromium (still experimental)
 - Gstreamer `waylandsink`/`gtkwaylandsink`

---

Notes:
1. This is a feature request that might have been discussed before but I couldn't find a related issue. It might also be an anti-goal since its similar to the GBM platform.
2. Gnome just got support for YUV formats in the recently released version 45, making it available to a much bigger part of the Linux user base.

**Comment by ninja-** [comment]
> Possibly making the GBM platform redundant in the long run, which most likely replicates a lot of Wayland compositor code.

I think it's quite the opposite, GBM functions pretty well at the moment and for set top boxes actually saves Kodi from a ton of possible bugs that could reside in Wayland compositors and desktop functionalities that aren't needed...

**Comment by sarbes** [comment]
This is a bug tracker, please use the forum for feature requests.
