### ISSUE TITLE
Kodi v20.1 creating double entries when updating video library after editing some .nfo files and setting a source sub folder to "local information only"

### ISSUE THREAD

**Issue by OnkelArmus** [xbmc/xbmc#23878]
### Describe the bug
Here is a clear and concise description of what the problem is:
I edited some .nfo files of a tv show to rearrange the order of episodes, set the folder of the show inside the source to "local information only", "exclude path from library updates" and did a full source scan. This lead to double entries. At this point I did a lot of library cleanups and updated with different settings. I can not tell if this made it worse.
Toggling the "exclude" option has no effect on the affected folder. When I scan the folder explicitly it will be fine. When I scan the whole source it will create double entries by first scanning the folder with the scraper and immediately afterwards again with local information only.  Behavior is the same ether with local info or TMDb TV Shows set as information provider for that sub folder.
All this was done on Raspberry Pi 4B 8GB / LibreELEC 11.0.1 / Kodi 20.1. On my second Raspberry Pi 2GB with PiOS and Kodi 19.4 scanning the same source without ever switching to local info only works perfectly fine.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Kodi should display no more than one entry for every episode in tv shows.

## Actual Behavior
After scanning the video library kodi displays the folder of the affected tv show as if it was not part of the library in Preferences > Media > Video > <Source>, offers the option to scan it into library and displays double entries for every episode of the show in the library.

## Possible Fix
Make the "exclude path from updates" option work.
To work around the issue I set the folder content to "none", select to delete the library entries when asked and do not touch the update (whole) library function afterwards.
I think it may work as normal when I remove the whole source and add it again. I'll leave it as is for now to aid diagnosis.

### To Reproduce
1. Scan a show with a scraper (TMDb TV Shows in my case).
2. Backup to create .nfo files.
3. Edit some .nfo files to rearrange the order of episodes.
4. Remove the sub folder inside the source from the library.
5. Set the sub folder inside the source to "local information only".
6. Scan the whole source as usual.

### Debuglog
I will add a log when needed.

### Screenshots 
Here are some links or screenshots to help explain the problem:
![IMG_20231005_103504](https://github.com/xbmc/xbmc/assets/123123399/d88bab98-1e2b-4044-a052-60c198ee7b2a)
![IMG_20231005_103636](https://github.com/xbmc/xbmc/assets/123123399/d8cc3b34-0581-413b-a052-be3e1db03d7f)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
The order of episodes is the aired order, not the supposed viewing order. I edited some .nfo files to reorder the episodes. After scanning the source afterwards, all episodes of this show have double entries. Even the ones I did not edit. To reorder the episodes I edited the file names of the .nfo and thumbnail files to match the proper video file name and the episode tag of the .nfo files. Nothing else was changed.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux

 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 11.0.1
 - Kodi version: 20.1
 - Raspberry Pi 4B 8GB
 - source is a smb share

**Comment by KarellenX** [comment]
>I edited some .nfo files to reorder the episodes.

What exactly are you editing? You don't edit nfo files to reorder episodes. You change the **S01E01** numbering in the filename to do that.

Go to the Information Page for both those episodes. Highlight the Refresh button and the path will be shown underneath. Can you see the problem in the path?

Not a bug, so issue closed.

**Comment by KarellenX** [comment]
Also, how to scrape alternate orders...
https://kodi.wiki/view/Add-on:TMDb_TV_Shows#Episode_Orders
