### ISSUE TITLE
[favourites] an "playlist" added in "Favourites" displays nothing with build "KodiSetup-20231004-0f289470"

### ISSUE THREAD

**Issue by Nanomani** [xbmc/xbmc#23879]
### Describe the bug
Here is a clear and concise description of what the problem is:

an playlist added in "favourites" display nothing on click

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If you create a new "playlist" what show a result from videos\Playlists
This "playlist" added in "favourites" must be show the result in same way

## Actual Behavior
If you click on this playlist from "favourites" nothing is displayed

## Possible Fix
use 
"KodiSetup-20231003-35680593-master-x64" or older

this issue is introduce with the nightly build : 
"KodiSetup-20231004-0f289470-master-x64"

### To Reproduce

1.  create a new basic "playlist test" video you want what show a result
2. test this "playlist test" from videos\playlists a result must be show
3. add this "playlist test" to "favourites"
4. open "favourites" and click on item "playlist test" 
5. nothing is displayed

### Debuglog
The debuglog can be found here:

https://paste.kodi.tv/uhatuvefow.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

![B1](https://github.com/xbmc/xbmc/assets/3939543/7d67ac46-9881-4ca8-8afe-5a3691dcc2c3)

![B3](https://github.com/xbmc/xbmc/assets/3939543/1da48eec-41ab-412a-83da-ff078d965036)

![B2](https://github.com/xbmc/xbmc/assets/3939543/9d9e98e1-fb31-4310-ad23-a8498d812aa2)

![B4](https://github.com/xbmc/xbmc/assets/3939543/a24d4a92-d6eb-4f38-8eae-eea1100dc56f)

![B5](https://github.com/xbmc/xbmc/assets/3939543/6ceb27b0-f825-47c2-8e41-aa680aba6d88)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Windows

 - Operating system version/name: Windows 11 Pro x64
 - Kodi version: 21.0-ALPHA3 (20.90.301) Git:20231004-0f28947095)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Confirming the issue.

@Nanomani what value does the setting Videos/Media/Default select action have for you? Is it "Show information"?

**Comment by Nanomani** [comment]
@ksooo 
Indeed your are right. It is "Show information"
