### ISSUE TITLE
Kodi 20.2 freeze Android TV 11 OS after use FileManager and exit Kodi

### ISSUE THREAD

**Issue by baudav** [xbmc/xbmc#23871]
### Describe the bug
When use Kodi to see profil with FileManager (in kodi) and exit Kodi,
Android Home screen is slow.. and after 5-6 action TV hang.
Must force power off TV.

## Expected Behavior
Fast exit Kodi, and not hang Android TV

## Actual Behavior
Android TV hang more second after exit Kodi. reproduce 3 times.

### Your Environment
Used Operating system:

 - [x ] Android

 - Operating system version/name:
 - Kodi version:20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by baudav** [comment]
LOGS: https://paste.kodi.tv/uxipeticed

**Comment by sarbes** [comment]
Applications like Kodi should never be able to crash an operating system. Please take this issue to your TV vendor.

**Comment by baudav** [comment]
and yet it is KODI which refuses to quit and freezes the system (Google having removed the switching between apps on Google TV, it is no longer possible to quickly close an app which I no longer respond to)... and forces me to  go kill the app instead of quitting.  KODI's development is getting worse and worse!  and the support is no better given the response.  will have to explain the link with the manufacturer.

**Comment by McKennaGITHUB** [comment]
I have the same problem on a TCL P735 and a Sony KDL807C. When I select exit TCL freezes so that I have to plug it off and Sony freezes for a few minutes. They both run lots of other apps, some more resource intensive without any problems so I'm assuming it's an app development failure.

**Comment by x-magic** [comment]
Same problem with TCL C845 on Google TV with Android 11. It worked fine if just go to home without exit Kodi explicitly. Haven't tried if Kodi got killed automatically when out of memory, though. I'm using NFS for media mount. 

Can't get any logs out of there as the whole TV simply getting slower and slower after exit Kodi and eventually freezes entirely. Even power button won't work. Had to unplug.
