### ISSUE TITLE
Linux cross-compilation broken since iconv cmake full TARGET commit

### ISSUE THREAD

**Issue by HiassofT** [xbmc/xbmc#23887]
### Describe the bug

When building LibreELEC for RPi with current kodi HEAD df97ff523a99db66c9be6a779e79cbaa6caab7e5 linking kodi fails because it's trying to pull in /usr/lib/libc.so from the x86_64 build host (which is wrong as it should against the aarch64 libc from sysroot - full log is here: http://ix.io/4Iqh):

```
/home/hias/libreelec/libreelec-master/build.LibreELEC-RPi5.aarch64-12.0-devel/toolchain/lib/gcc/aarch64-libreelec-linux-gnu/13.2.0/../../../../aarch64-libreelec-linux-gnu/bin/ld.gold: error: cannot open /usr/lib/libc.so.6: No such file or directory
/home/hias/libreelec/libreelec-master/build.LibreELEC-RPi5.aarch64-12.0-devel/toolchain/lib/gcc/aarch64-libreelec-linux-gnu/13.2.0/../../../../aarch64-libreelec-linux-gnu/bin/ld.gold: error: cannot open /usr/lib/libc_nonshared.a: No such file or directory
/home/hias/libreelec/libreelec-master/build.LibreELEC-RPi5.aarch64-12.0-devel/toolchain/lib/gcc/aarch64-libreelec-linux-gnu/13.2.0/../../../../aarch64-libreelec-linux-gnu/bin/ld.gold: error: cannot open /usr/lib/ld-linux-aarch64.so.1: No such file or directory
...
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
FAILURE: scripts/build kodi:target during make_target (default)
```

Reverting the `[cmake] FindIconv migrate to full TARGET usage` commit b2c8bf3631a63bd41d4153aa245e186e26b2a0f6 fixes the build issue.

Analyzing the (verbose) ninja build and cmake trycompile steps showed that before the iconv cmake change the kodi link call used `-lc` whereas with the iconv change it uses `/home/hias/libreelec/libreelec-master/build.LibreELEC-RPi5.aarch64-12.0-devel/toolchain/aarch64-libreelec-linux-gnu/sysroot/usr/lib/libc.so` - which isn't a regular library but a ld script.

However cmake trycompile used `-lc` instead (which is somewhat OK)

CMakeFiles/CMakeScratch/TryCompile-qSFynL/build.ninja:
```
# Link the executable cmTC_187d0

build cmTC_187d0: C_EXECUTABLE_LINKER__cmTC_187d0_ CMakeFiles/cmTC_187d0.dir/CheckFunctionExists.c.o | /home/hias/libreelec/libreelec-master/build.LibreELEC-RPi5.aarch64-12.0-devel/toolchain/aarch64-libreelec-linux-gnu/sysroot/usr/lib/libc.so
  FLAGS = -march=armv8.2-a+crc+crypto -mabi=lp64 -Wno-psabi -mtune=cortex-a76 -mno-outline-atomics -Wall -pipe  -O3 -fomit-frame-pointer -DNDEBUG -Wdouble-promotion -Wmissing-field-initializers -Wsign-compare -Wextra -Wno-unused-parameter -DCHECK_FUNCTION_EXISTS=iconv
  LINK_FLAGS = -Wl,--as-needed -fuse-ld=gold -fuse-ld=gold
  LINK_LIBRARIES = -lc
  OBJECT_DIR = CMakeFiles/cmTC_187d0.dir
  POST_BUILD = :
  PRE_LINK = :
  TARGET_FILE = cmTC_187d0
  TARGET_PDB = cmTC_187d0.dbg
```

As `-lc` is unnecessary (libc is automatically linked in anyways) and linking against libc.so from sysroot will be wrong I'd guess the `c` library searching should just be dropped from the FindIconv.cmake script - iconv will be there, just like printf and anything else.

ping @fuzzard 

## Expected Behavior

Cross compiling kodi works as before

## Actual Behavior

Cross compiling kodi fails

### To Reproduce

Build LibreELEC master with kodi updated to current HEAD (see eg here: https://github.com/HiassofT/LibreELEC.tv/tree/le12-kodi-head)
```
PROJECT=RPi DEVICE=RPi5 ARCH=aarch64 make
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC master
 - Kodi version: Omega/master HEAD

**Comment by mglae** [comment]
IMO bug in LE build system. Tested with Generic:
```
From 325e3bf41eceb809f27f333900bfb93a0cc25113 Mon Sep 17 00:00:00 2001
From: mglae <mglmail@arcor.de>
Date: Sat, 7 Oct 2023 12:20:20 +0200
Subject: [PATCH] glibc: fix paths in libc.so and libm.so linker scripts

Kodi is now detecting iconv in libc.so but fail to link to /usr/lib/* files
---
 packages/devel/glibc/package.mk | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/packages/devel/glibc/package.mk b/packages/devel/glibc/package.mk
index d7a9c14832..274984f78f 100644
--- a/packages/devel/glibc/package.mk
+++ b/packages/devel/glibc/package.mk
@@ -128,6 +128,9 @@ post_makeinstall_target() {
     cp ${PKG_DIR}/config/nsswitch-target.conf ${INSTALL}/etc/nsswitch.conf
     cp ${PKG_DIR}/config/host.conf ${INSTALL}/etc
     cp ${PKG_DIR}/config/gai.conf ${INSTALL}/etc
+
+# "fix" paths in ld scripts libc.so + libm.so
+  sed s:/usr/lib/::g -i ${SYSROOT_PREFIX}/usr/lib/lib{c,m}.so
 }
 
 configure_init() {
-- 
2.35.3
```

**Comment by Portisch** [comment]
By revert of this commit kodi does build again, but do also not start because EGL lib is not found:
```text
/home/docker/build_dir/CoreELEC-21/build.CoreELEC-Amlogic-ne.aarch64-21/toolchain/aarch64-libreelec-linux-gnu/sysroot/usr/lib/libGLESv2.so: cannot open shared object file: No such file or directory
```
By revert of https://github.com/xbmc/xbmc/pull/23749/commits/0dddec4199edcf750bbef5dc0933e0721efdb75b it is fixed again.

**Comment by Portisch** [comment]
The EGL lib error can be solved by add missing line by @vpeter4 :
```diff
diff --git a/cmake/modules/FindOpenGLES.cmake b/cmake/modules/FindOpenGLES.cmake
index 49bad7027f..ac3ab191db 100644
--- a/cmake/modules/FindOpenGLES.cmake
+++ b/cmake/modules/FindOpenGLES.cmake
@@ -46,6 +46,7 @@ if(NOT TARGET OpenGL::GLES)
     set_target_properties(OpenGL::GLES PROPERTIES
                                        IMPORTED_LOCATION "${OPENGLES_gl_LIBRARY}"
                                        INTERFACE_INCLUDE_DIRECTORIES "${OPENGLES_INCLUDE_DIR}")
+    set(OPENGLES_LIBRARIES ${OPENGLES_gl_LIBRARY})
 
     if(OPENGLES3_INCLUDE_DIR)
       set_property(TARGET OpenGL::GLES APPEND PROPERTY
```
Removed [here](https://github.com/xbmc/xbmc/commit/0dddec4199edcf750bbef5dc0933e0721efdb75b#diff-2d7ca1c54edcbdfb6f9a95d67ab7a3a6f91b5e097b6d5a87235f6d0114da0f84L40)

**Comment by HiassofT** [comment]
> IMO bug in LE build system. Tested with Generic:

It's tricky. While eg Debian ships with an adjusted libc.so linker script in eg it's libc6-dev-arm64-cross package other prebuilt toolchains, like the official ones from ARM https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads which can be unpacked in any arbitrary directory do not

Upstream cmake's FindIconv.cmake dropped adding libc to the library path 2 years ago: https://gitlab.kitware.com/cmake/cmake/-/issues/22114

Especially note the comment from Brad King:
> As stated in [#22114 (comment 945535)](https://gitlab.kitware.com/cmake/cmake/-/issues/22114#note_945535), the problem is that FindIconv should not be looking for the C runtime library in the first place. Once it determines that the C runtime library provides the functionality, no special library needs to be linked at all.

I think kodi's downstream FindIconv replacement should follow that path

**Comment by fuzzard** [comment]
Hows the following work out for you then

```
diff --git a/cmake/modules/FindIconv.cmake b/cmake/modules/FindIconv.cmake
index 67230c897b..1e9b54fd5a 100644
--- a/cmake/modules/FindIconv.cmake
+++ b/cmake/modules/FindIconv.cmake
@@ -29,10 +29,14 @@ if(NOT TARGET ICONV::ICONV)
                                     REQUIRED_VARS ICONV_LIBRARY ICONV_INCLUDE_DIR HAVE_ICONV_FUNCTION)
 
   if(ICONV_FOUND)
-    add_library(ICONV::ICONV UNKNOWN IMPORTED)
-    set_target_properties(ICONV::ICONV PROPERTIES
-                                       IMPORTED_LOCATION "${ICONV_LIBRARY}"
-                                       INTERFACE_INCLUDE_DIRECTORIES "${ICONV_INCLUDE_DIR}")
-    set_property(GLOBAL APPEND PROPERTY INTERNAL_DEPS_PROP ICONV::ICONV)
+    # Libc causes grief for linux, so search if found library is libc.* and only
+    # create imported TARGET if its not
+    if(NOT ${ICONV_LIBRARY} MATCHES ".*libc\..*")
+      add_library(ICONV::ICONV UNKNOWN IMPORTED)
+      set_target_properties(ICONV::ICONV PROPERTIES
+                                         IMPORTED_LOCATION "${ICONV_LIBRARY}"
+                                         INTERFACE_INCLUDE_DIRECTORIES "${ICONV_INCLUDE_DIR}")
+      set_property(GLOBAL APPEND PROPERTY INTERNAL_DEPS_PROP ICONV::ICONV)
+    endif()
   endif()
 endif()
```

iconv is a required dep, so we need to at least find something for FHPSA, but we just discard if its libc. Regex seems to work, but always open to cleaner regexes. Wasnt sure if there might be an option for a static libc, hence not specifically putting in libc.so

**Comment by vpeter4** [comment]
It works for me with patch above. Build and run tested on CoreELEC.

**Comment by HiassofT** [comment]
@fuzzard your patch works bzt TBH it smells a bit hacky (and probably fragile if cmake mangles the lib to -lc again), I like the upstream cmake approach a lot better:

https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindIconv.cmake

It explicitly check for Posix/unix systems and tests if iconv is built into libc and compiling/linking works. If so, it doesn't add any includes or libs and is happy.

On non-posix systems it does the usual header plus lib checks.

When checking if the iconv actually exists we must also be careful as that could be a macro (it's explicitly allowed in posix specs) instead of a function and thus we may need to use check_symbol_exists instead of check_function_exists

You don't need to worry about static linking, as we are using the C/C++ for that it'll automatically pass the appropriate libraries to the linker (depending if -shared or -static is used) and libc will also be included automatically.

Statically linking on Linux systems is quite rare nowadays, the GNU libc broke that decades ago by making heavy use of dlopen internally (which obviously doesn't fit well with the static linking concept). Other libc implementations (eg musl) are a bit more sane in that aspect, but they are niche and have other issues - but you could use static linking with them

**Comment by fuzzard** [comment]
I really dont think we need to go that in depth at this point in time.

The bulk of Findiconv hasnt change from what it was 3 weeks ago. The only thing thats changed is the removal of the _LIBRARIES, _INCLUDE_DIRS, _DEFINITONS variables and to allow the iconv target to be linked using target_link_libraries.

Im all for making this work, but i dont think it needs to be over engineered right now, and honestly, i dont think we even need our own FindICONV module for the most part. But thats something i dont want to deal with right now. So simple is good imo
