### ISSUE TITLE
Teletext decoder - no Polish diacritics

### ISSUE THREAD

**Issue by ninja-** [xbmc/xbmc#23882]
### Describe the bug

Teletext decoder https://github.com/xbmc/xbmc/blob/b6c92889950691868ff049898af20e0b6807e136/xbmc/video/Teletext.cpp
does not decode polish diacritics properly (żółąśćźę).

There should be conditional code with NAT_PL, same as custom support for a few other languages

## Expected Behavior

Decode polish diacritics properly

## Actual Behavior

Invalid characters are in place of polish diacritics

### To Reproduce

1.  Use a DVB-T tuner in Poland
2. Play Polsat channel
3. Browse teletext pages

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [*] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ninja-** [comment]
![image](https://github.com/xbmc/xbmc/assets/5637961/c728949d-a309-4b2d-b605-59e402d396e4)
(should spell "OGŁOSZENIA)

**Comment by enen92** [comment]
Can you record a small sample and provide a screenshot where those chars are supposed to show up? Unfortunately we don't have many people using/touching the Teletext code and those who do (me) are not familiar with those kind of chars...

**Comment by ninja-** [comment]
Here's a .ts file with Polsat teletext https://we.tl/t-5trgNlLr3P

**Comment by ninja-** [comment]
This doc should also be helpful https://www.etsi.org/deliver/etsi_en/300700_300799/300706/01.02.01_60/en_300706v010201p.pdf - page 107. I am trying to map it with what happens in Teletext.cpp right now

**Comment by scott967** [comment]
This seems suspicious?
https://github.com/xbmc/xbmc/blob/b6c92889950691868ff049898af20e0b6807e136/xbmc/video/TeletextDefines.h#L128

**Comment by enen92** [comment]
@ninja- your sample is so small it doesn't even allow to browse the teletext...
Mind sending a bigger one (like 3 minutes or so)? I was hopping to get to the exact same page you posted on your screenshot (610)...

**Comment by ninja-** [comment]
just pause it ASAP and click the teletext button, you can then access any page that you want, Polsat actually includes 10s of test pages of various functionalities including the Polish charset :D

**Comment by ninja-** [comment]
![image](https://github.com/xbmc/xbmc/assets/5637961/44c00df2-54b6-44dd-bad7-f9ba0e54fad0)

**Comment by ninja-** [comment]
I assume that page should go like `aąbcćdeęfghijklłmnńoóprqs`

**Comment by ninja-** [comment]
> This seems suspicious?
> 
> https://github.com/xbmc/xbmc/blob/b6c92889950691868ff049898af20e0b6807e136/xbmc/video/TeletextDefines.h#L128

I am not convinced that is the key, that one is only used for subtitles pages. There are subtitles page as well if you scroll my example file far enough though.

**Comment by ninja-** [comment]
![image](https://github.com/xbmc/xbmc/assets/5637961/64c2ec0f-0e41-49bf-b358-eb3b177d86d8)
For functionality you mentioned this page is relevant. I guess to implement that you should have more CountryConversionTables and choose them based on higher bits.
But that's a very rare case I probably won't high with any local TV out there...

**Comment by enen92** [comment]
@ninja- thanks for the sample, the issue should be fixed with the pull request linked above. Feedback would be great.
