### ISSUE TITLE
WebOS: Kodi doesn't passthrouh the Dolby TrueHD Atmos audio track 

### ISSUE THREAD

**Issue by RyuzakiKK** [xbmc/xbmc#23884]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi on WebOS 5.x doesn't seem to be capable of passing through the TrueHD Atmos audio tracks.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should passthrough the TrueHD Atmos track.

## Actual Behavior

The soundbar receives a "Stereo PCM" track instead. If I select a different track audio and then back to the TrueHD Atmos, the audio signal completely stops and I'm left with no audio at all.

### To Reproduce

- Use WebOS 5.x (LG CX)
- Connect a sound receiver capable of decoding Dolby TrueHD Atmos to the TV via ARC, e.g. a soundbar
- Install the latest Kodi nightly [20231006](https://mirrors.kodi.tv/nightlies/webos/master/org.xbmc.kodi_20231006-df97ff52-master_arm.ipk)
- Download a test TrueHD Atmos file, e.g. I used the Dolby Atmos shattered lossless m2ts file, or also the "Dolby Atmos test tones 7.1.2" if you prefer an mkv
- In Kodi ensure "Dolby Digital (AC3) capable receiver" and "Dolby Digital Plus (E-AC3) capable receiver" are enabled
- In Kodi set the passthrough output device to "Starfish"
- In the TV settings, ensure audio passthrough via ARC is enabled as well
- As a validation test, reproduce the test Atmos file via the TV built-in video player and verify that the soundbar correctly receives the Dolby Atmos track
- Start the test Atmos file in Kodi

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/amuxutayaf.kodi

In this log you can see me trying to reproduce a test Atmos file, and at first the soudbar receives a transcoded audio track. Then I select a different audio track and go back to the TrueHD Atmos one. After that the soudbar stops to reproduce any sound.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [x] WebOS

 - Operating system version/name: WebOS 5.4.3, LG CX
 - Kodi version: 21.0-ALPHA3 (20.90.301) Git:20231006-df97ff523a

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sundermann** [comment]
Unfortunately, webOS only supports [AC3 and EAC3](https://webostv.developer.lge.com/develop/specifications/video-audio-50). Technically, webOS < 5 allowed also DTS and some webOS 8 devices have DTS and DTS-HD. Not implemented though due to lack of capable testing devices.

**Comment by RyuzakiKK** [comment]
Oh that's unfortunate. Indeed from the linked specs there is no mention of TrueHD, however this leaves me a bit confused.

If TrueHD Atmos in not supported, why the TV built-in video player is able to passthrough the Atmos signal to the soundbar when I play the same Dolby Atmos shattered lossless m2ts file? (when I reproduce it the soundbar shows "Dolby Atmos" in its small display and indeed the spatial audio works as expected)
Am I missing something?

**Comment by RyuzakiKK** [comment]
```
Audio #1
ID                                       : 4352 (0x1100)
Menu ID                                  : 1 (0x1)
Format                                   : MLP FBA AC-3 16-ch
Format/Info                              : Meridian Lossless Packing FBA with 16-channel presentation
Commercial name                          : Dolby TrueHD with Dolby Atmos

Audio #2
ID                                       : 4353 (0x1101)
Menu ID                                  : 1 (0x1)
Format                                   : E-AC-3 JOC
Format/Info                              : Enhanced AC-3 with Joint Object Coding
Commercial name                          : Dolby Digital Plus with Dolby Atmos
```

Ah mistery solved I guess. So apparently Atmos can be used with both TrueHD and DD+. So I guess that the TV built-in video player reproduces the second audio track with DD+ and Atmos.

**Comment by RyuzakiKK** [comment]
To conclude here, I retried that video in Kodi and in fact there is also a "DD+ 0 channels - 0 channels (3/3)" audio track. And I confirm that with it there is a correct passthrough of the Atmos signal.

I thought that Atmos was only possible with TrueHD, but apparently that's not the case. It can be used with both TrueHD and DD+. And WebOS only supports the latter.

(When you change two times audio track, the audio in Kodi completely breaks. But that's a different issue)

Thanks for you reply and sorry for the noise.

**Comment by iCarlosDev** [comment]
> Unfortunately, webOS only supports [AC3 and EAC3](https://webostv.developer.lge.com/develop/specifications/video-audio-50). Technically, webOS < 5 allowed also DTS and some webOS 8 devices have DTS and DTS-HD. Not implemented though due to lack of capable testing devices.

Hi, it will be implemented? I use webOS 24 and I have the same problem.

**Comment by sundermann** [comment]
It's implemented in master

**Comment by iCarlosDev** [comment]
I downloaded the latest dev build in master and now I see the DTS passthrough option in Kodi settings, but the addon I use to watch movies and tv shows (Palantir) it's not working, it says the module pyCriptomode it's not compatible with my operating system.

**Comment by sundermann** [comment]
No support for [banned addons](https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons)

**Comment by andrebower** [comment]
I use the jellyfin addon (Default Add-on mode) and DTS passthorugh does not work somehow. LG G3

**Comment by gabripo** [comment]
Software:

- Kodi (WebOS)
- JellyCon addon

Hardware:
- MacBook with Jellyfin server
- LG TV OLED G5
- Sonos Beam Gen 2 + 2x Sonos Era 100 + Sonos Sub Mini

No Dolby Atmos can be passthrough if using Kodi - even with activated option. The file is reproduced, yet the Sonos app does not show "Dolby Atmos" and the TV does not show "Dolby Atmos".
If using Stremio, the Dolby Atmos (lossy, no TrueHD) can be passed to the Sonos system.

I bought a Nvidia Shield Pro, hoping to finally enjoy the Dolby TrueHD - all this fragmentiation and zero support from TV producers let me down.
