### ISSUE TITLE
[uPnP Server] Broken Movie/TV Show Thumbnails on LG TV

### ISSUE THREAD

**Issue by CrystalP** [xbmc/xbmc#23899]
### Describe the bug

LG TV's built-in uPnP client shows generic icon for movies shared by Kodi's uPnP server instead of the thumbnail image.
Bisection shows that the problem started with PR #21837, which modified upnp thumbnails.
Thumbnails are correct with other uPnP servers (ex. UMS)

The problem is likely that the LG TV doesn't like a name without an image extension like .jpg, or an incorrect mime type, or both.
Removing the "/thumb" suffix added by the PR restores the expected behavior.

## Expected Behavior
Movie or episode poster as thumbnail in LG TV uPnP browser.

## Actual Behavior

Generic icon as thumbnail

## Possible Fix

Difficult to make good suggestions as I don't really understand how the PR issue was happening (.flac, .mp3, etc. as thumbnail filenames?), and the way it's fixed doesn't seem very standard-compliant...

It's not surprising that some uPnP control points check the provided file name/extension, mime type, dlna profile before downloading a thumbnail.

IIRC platinum derives the mime type from the file extension so a meaningful extension should be used.

So, maybe preserve image extensions and replace non-image extensions with .jpg?
Alternatively use the /thumb suffix only for the non-image file extensions

Assigning to you @ene92, you seem quite knowledgeable in uPnP matters, and hopefully remember something about the pr that broke things.

### To Reproduce

1. Activate Kodi uPnP server and share libraries
2. On LG TV navigate to Kodi uPnp source, Video Library and a sub-folder listing movies.
3. Movies displayed with generic icons instead of poster as thumbnails

### Debuglog

Last lines show the thumbnails served
https://paste.kodi.tv/cixorofiqa.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 21 alpha 3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@CrystalP mind giving a go to the following patch:

```
diff --git a/xbmc/network/upnp/UPnPInternal.cpp b/xbmc/network/upnp/UPnPInternal.cpp
index fddc3608c0..49f340210b 100644
--- a/xbmc/network/upnp/UPnPInternal.cpp
+++ b/xbmc/network/upnp/UPnPInternal.cpp
@@ -653,20 +653,24 @@ BuildObject(CFileItem&                    item,
 
         if (!thumb.empty()) {
           PLT_AlbumArtInfo art;
+          std::string imageExtension{};
           // Set DLNA profileID by extension, defaulting to JPEG.
           if (URIUtils::HasExtension(thumb, ".png"))
           {
             art.dlna_profile = "PNG_TN";
+            imageExtension = ".png";
           }
           else
           {
             art.dlna_profile = "JPEG_TN";
+            imageExtension = ".jpg";
           }
           // append /thumb to the safe resource uri to avoid clients flagging the item with
-          // the incorrect mimetype (derived from the file extension)
+          // the incorrect mimetype (derived from the file extension - e.g. .mp3, .flac, etc)
+          // append the image extension so that platinum can derive the correct Content-Type header
           art.uri = upnp_server->BuildSafeResourceUri(
               rooturi, (*ips.GetFirstItem()).ToString(),
-              std::string(CTextureUtils::GetWrappedImageURL(thumb) + "/thumb").c_str());
+              std::string(CTextureUtils::GetWrappedImageURL(thumb) + "/thumb" + imageExtension).c_str());
           object->m_ExtraInfo.album_arts.Add(art);
         }
 
~
```

I think the issue is that with the current implementation the content-type is returned as `application/octet-stream` and your client doesn't really like it. With the patch above it provides the correct file extension as well as the content-type header

**Comment by CrystalP** [comment]
Yep that works. Is it safe to assume everything not ending in .png is a jpeg?
