### ISSUE TITLE
[MSVC][Permissive-] xbmc failed to build due to error C2065: 'm_CurSize': undeclared identifier on Windows

### ISSUE THREAD

**Issue by Zhaojun-Liu** [xbmc/xbmc#23898]
### Describe the bug
Hi All,
Recently, we updated the commit of XBMC, it failed to build due to a lot of errors when add compile option /permissive- on Windows. Could you please take a look? Thanks.

## Expected Behavior
Build successful.

## Actual Behavior

```
F:\gitP\xbmc\xbmc\lib\win32\Effects11\inc\d3dxGlobal.h(436,28): error C2065: 'm_CurSize': undeclared identifier [F:\gitP\xbmc\xbmc\build_amd64\build\Effects11\effects11.vcxproj]
 F:\gitP\xbmc\xbmc\lib\win32\Effects11\inc\d3dxGlobal.h(436,28): error C3861: 'm_CurSize': identifier not found [F:\gitP\xbmc\xbmc\build_amd64\build\Effects11\effects11.vcxproj]
 F:\gitP\xbmc\xbmc\lib\win32\Effects11\inc\d3dxGlobal.h(437,13): error C3861: 'm_pData': identifier not found [F:\gitP\xbmc\xbmc\build_amd64\build\Effects11\effects11.vcxproj]
F:\gitP\xbmc\xbmc\lib\win32\Effects11\inc\d3dxGlobal.h(439,9): error C3861: 'm_pData': identifier not found [F:\gitP\xbmc\xbmc\build_amd64\build\Effects11\effects11.vcxproj]
 F:\gitP\xbmc\xbmc\lib\win32\Effects11\inc\d3dxGlobal.h(437,13): error C2065: 'm_pData': undeclared identifier [F:\gitP\xbmc\xbmc\build_amd64\build\Effects11\effects11.vcxproj]
F:\gitP\xbmc\xbmc\lib\win32\Effects11\inc\d3dxGlobal.h(439,9): error C2065: 'm_pData': undeclared identifier [F:\gitP\xbmc\xbmc\build_amd64\build\Effects11\effects11.vcxproj]
 F:\gitP\xbmc\xbmc\lib\win32\Effects11\inc\d3dxGlobal.h(445,9): error C3861: 'm_pData': identifier not found 
```

### To Reproduce

1. Open a VS2022 x64 cmd
2. git clone https://github.com/xbmc/xbmc F:\gitP\xbmc\xbmc
3. git -C "F:\gitP\xbmc\xbmc" reset --hard 2964bb43ed2a63168eb7aeb62f7a169cefed23bf
4. set CL= /permissive-
5. cd F:\gitP\xbmc\xbmc\tools\buildsteps\windows\x64
6. download-dependencies.bat 2>&1
7. download-msys2.bat
8. make-mingwlibs.bat
9. mkdir F:\gitP\xbmc\xbmc\build_amd64 & cd F:\gitP\xbmc\xbmc\build_amd64
10. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 .. 2>&1
11. msbuild /m /p:Platform=x64 /p:Configuration=Release kodi.sln /t:Rebuild 2>&1 (or execute: cmake --build . --config "Release")

### Debuglog

The debuglog can be found here:
[xbmc_build.log](https://github.com/xbmc/xbmc/files/12851884/xbmc_build.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows Server 2022 / 21H2
 - Kodi version: 2964bb43ed2a63168eb7aeb62f7a169cefed23bf

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Id just like to point out, this regression occured as we synced to the upstream Microsoft library https://github.com/microsoft/FX11 after @Paxxi had "fixed" in 2021 (https://github.com/xbmc/xbmc/commit/07336f2d96302ef92398a79eb3c1a09ed63f434d) these /permissive- issues once already

That repo is archived, but if we were to sync to a more recent version than what was synced in https://github.com/xbmc/xbmc/commit/9dfd20a8ee9d294855a25927d7abbc0bad1ba913 we'll just be back at the same point for the third time. Maybe the MS folks using kodi to test could possibly get a fix into the archived upstream repo to save us the hassle again.

**Comment by Zhaojun-Liu** [comment]
@fuzzard Thanks for your info. Due to the Microsoft library https://github.com/microsoft/FX11 is archived, I can't fix it upstream. I tried the "fix" (07336f2) you mentioned as a patch in our test, it is indeed worked. If you think I can raise a PR to re-apply @Paxxi's "fix" (07336f2), please let me know. Thanks again for your reply.

**Comment by CrystalP** [comment]
That's not ideal, previous PR was against an older FX11 and we don't want to revert FX11.

There were a few commits in the FX11 repo between our last sync and the repo archival, but they didn't change the code (except for the library version number). Kodi's copy is still current and there is nothing more to sync.

We could apply @Paxxi's new PR #23990, which is built on top of the last sync.
@Zhaojun-Liu does that PR address the permissive issue?

**Comment by Zhaojun-Liu** [comment]
@CrystalP I verified the new PR #23990 locally, it addressed the permissive issue. Thanks for the fix.

**Comment by fuzzard** [comment]
effects11 lib is no longer in tree.
