### ISSUE TITLE
[MSVC][ASAN][amd64] XBMC failed to build with error MSB8066 in ASAN mode

### ISSUE THREAD

**Issue by WillaCao** [xbmc/xbmc#23900]
### Describe the bug
Hi All,
Recently, we updated the commit of XBMC, it failed to build due to error MSB8066 when add option "set _CL_= /fsanitize=address /GS- /wd5072 & set _LINK_= /InferASanLibs /incremental:no /debug" on Windows. Could you please take a look? Thanks.

## Expected Behavior
Build successful.

## Actual Behavior
Build failed.

### To Reproduce
1.git clone https://github.com/xbmc/xbmc/commits/master F:\gitP\xbmc\xbmc
2.cd F:\gitP\xbmc\xbmc
3.git remote prune origin
4.set _CL_= /fsanitize=address /GS- /wd5072 & set _LINK_= /InferASanLibs /incremental:no /debug
5.cd F:\gitP\xbmc\xbmc\tools\buildsteps\windows\x64
6.download-dependencies.bat
7.cd F:\gitP\xbmc\xbmc\build_amd64
8.xcopy F:\gitP\xbmc\tools\mingwlibs\x64 F:\gitP\xbmc\xbmc\project\BuildDependencies\mingwlibs\x64 /k/r/e/i/s/c/h/f/y
9.cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 ..
10.msbuild /m /p:Platform=x64 /p:Configuration=Release kodi.sln /t:Rebuild

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:
![image](https://github.com/xbmc/xbmc/assets/135598562/b0066874-82da-4750-8c46-f4f1aa08cff9)

## Additional context or screenshots (if appropriate)
We suspect the build failed due to clang_rt.asan_dynamic-i386.dll not found.
![image](https://github.com/xbmc/xbmc/assets/135598562/018ee681-45be-494a-931f-c9dcf407c2ff)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [√ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CrystalP** [comment]
Those reproduction steps don't work, starting with the first line, and don't lead to the posted screenshot. So it's not clear what happens and whether the problem comes from Kodi or is external.

Some quick googling shows that a common issue with clang_rt.asan_dynamic-i386.dll and similar dll is that it's not in the PATH or does not exist in the directory of the exe (jsonschemabuilder.exe in this case). So make sure to add the correct Visual Studio directory to the PATH or copy the dll.

**Comment by WillaCao** [comment]
Wo fixed this issue, so closed it.
