### ISSUE TITLE
On PVR properties string size is limited to 1024, causing Inputstream.adaptive to fail due to truncated parameters

### ISSUE THREAD

**Issue by nirvana-7777** [xbmc/xbmc#23903]
## Bug report
Some DRM systems like Comcasts' mpx Platform send information like tokens as parameters in the URL and not in the headers. That means Widevine URLs can get very long. If they exceed 1024 characters it results in inputstream not working any more.
### Describe the bug
Here is a clear and concise description of what the problem is:

I think I can pindown the problem to the line 60 in this file:
https://github.com/xbmc/inputstream.adaptive/blob/Omega/src/decrypters/widevine/WVCdmAdapter.cpp 
There the char buffer[1024]; is defined for the license url if I am not mistaken.
Visibly from the logs the URL e.g. in CurlFile::Open is truncated after 1024 characters.
The server answers with http response 400 Bad request resulting in inputstream.adaptive not working correctly and no video being displayed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expectation is that also longer URLs >1024 characters can be send to the server. 2048 would be sufficient for my use case at least. Better would be dynamic size.

## Actual Behavior

Long URLs don't work for widevine.

## Possible Fix

Quickfix: char buffer[2048]; in line 60 of respective file. Better dynamic size.

### To Reproduce

1. Send longer URLs than 1024 characters to a server for widevine.

### Debuglog

The debuglog can be found here:
Won't provided publically due to confidential data contained (token).

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
Not the problem.

### Screenshots 
Here are some links or screenshots to help explain the problem:

Not provided.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux Mint
 - Kodi version: 20.2
 - inputstream.adaptive version:

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by nirvana-7777** [comment]
Thank you for tracing it down and moving it over.
The prospect of having 2 years or more before I can get a working version is of course not very motivating. Maybe there can be done an exception to the rule because the behaviour is not up to Kodi's standards and having hard limitations always leads to problems sooner or later.

**Comment by CastagnaIT** [comment]
i understand, unfurnately kodi binary interface dont allow fast fixes its a known downside...
i will try ask to the team to know if there is time/possibility to include this change in to kodi 21

**Comment by CastagnaIT** [comment]
@nirvana-7777 are you able to compile kodi and pvr.magenta?
if so,
try apply to your local kodi sources following change, and recompile Kodi/pvr.magenta from scratch
you should be able to play videos, let me know

```diff
diff --git a/xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_defines.h b/xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_defines.h
index 5bd24dcf3b..2123a303a2 100644
--- a/xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_defines.h
+++ b/xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/pvr/pvr_defines.h
@@ -56,7 +56,7 @@ extern "C"
   typedef struct PVR_NAMED_VALUE
   {
     char strName[PVR_ADDON_NAME_STRING_LENGTH];
-    char strValue[PVR_ADDON_NAME_STRING_LENGTH];
+    char strValue[PVR_ADDON_NAME_STRING_LENGTH * 2];
   } PVR_NAMED_VALUE;
 
   /*!
```

**Comment by nirvana-7777** [comment]
Yes, I can compile and no that alone doesn't fix the issue:

With that patch not all properties are send to inputstream.adaptive. Two are missing.
`2023-10-11` 17:08:53.475 T:183368   debug <general>: AddOnLog: inputstream.adaptive: Open()
2023-10-11 17:08:53.475 T:183368   debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.license_type" value: com.widevine.alpha
2023-10-11 17:08:53.475 T:183368   debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.play_timeshift_buffer" value: false
`
Without patch the complete set of 4 is send:
`023-10-11 17:02:57.162 T:181076   debug <general>: AddOnLog: inputstream.adaptive: Open()
2023-10-11 17:02:57.163 T:181076   debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.license_key" value: test|Origin=https://web2.magentatv.de&Referer=https://web2.magentatv.de&User-Agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36&Content-Type= |R{SSM}|
2023-10-11 17:02:57.163 T:181076   debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.license_type" value: com.widevine.alpha
2023-10-11 17:02:57.163 T:181076   debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.manifest_type" value: mpd
2023-10-11 17:02:57.163 T:181076   debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.play_timeshift_buffer" value: false
`
And this is even when I don't send license keys > 1024 characters.

Nothing else was changed. Only the patch in Kodi.

**Comment by ksooo** [comment]
You have double checked that after applying the patch you have actually recompiled both Kodi itself AND the addon against the kodi headers containing the patch, haven’t you?

**Comment by nirvana-7777** [comment]
Actually I did - but not from the same build tree. Obviously that does not help. Thank you for pointing it out again ksooo!

I hereby confirm that the patch is fixing the issue. The stream gets displayed. The URL is around 1500 characters long in this case.

**Comment by CastagnaIT** [comment]
thanks for the confirmation, so we can apply future fixes in more fluent way

Unfortunately i have bad news, we are out of timing, we have about 5 days starting from today to propose the fix, get it approved, update all binary addons and make the new releases.
As you can understand there is no enough time to do all these jobs, then we can only prepare it for the next kodi 22 that development should start on next year

**Comment by nirvana-7777** [comment]
...hope dies last... (I know one should not translate sayings ;-))
