### ISSUE TITLE
[cmake] exec_program usage is removed in cmake 3.28

### ISSUE THREAD

**Issue by fuzzard** [xbmc/xbmc#23914]
### Describe the bug
Here is a clear and concise description of what the problem is:
Cmake 3.28 rc1 has just been released https://discourse.cmake.org/t/cmake-3-28-0-rc1-is-ready-for-testing/9181
of note is the change 

>The “exec_program()” command, which has been deprecated since CMake
3.0, has been removed by policy “CMP0153”. Use the
“execute_process()” command instead.

Our FindSSE.cmake (https://github.com/xbmc/xbmc/blob/master/cmake/modules/FindSSE.cmake) makes use of exec_program and will need to be changed to execute_process

Raising this to pre-emptively catch those bleeding edge linux users who are going to fail building.
I dont have time to fix right now, but hopefully i'll remember (or someone else might jump in and fix)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. Use cmake 3.28
2. Build for linux.
3.

### Debuglog

The debuglog can be found here:
N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by howie-f** [comment]
> linux users who are going to fail building.

mh?
