### ISSUE TITLE
external default player not working since Nightly from 2023-10-11

### ISSUE THREAD

**Issue by DecalicatanDecalicatan** [xbmc/xbmc#23922]
### Describe the bug
Here is a clear and concise description of what the problem is:

Using nightly from 2023-10-13, videoplayer is always the default video player even if there is a rule in playercorefactory.xml to for an external player to be used instead.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I have a rule to use Just Player (Legacy) to play video file with DV (or DoVi) in their filename: [playercorefactory.xml](https://paste.kodi.tv/onusinizel)
Any file (with DV its filename) should be played by Just Player (Legacy)

## Actual Behavior

The file (with DV its filename) is played with videoplayer

### To Reproduce

1. install a video player beside kodi
2. create a playercorefactory.xml file to use the external player instead of videoplayer given a rule (DV in the filename)
3. play a file  (with DV in the filename) with kodi 

### Debuglog

The debuglog can be found here:
[debuglog _v2023-10-13](https://paste.kodi.tv/qapavuleyo.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Using the same playercorefactory.xml file, with nightly from 2023-10-11 kodi-20231010-87ec6401-master-arm64-v8a.apk, the rule is applied for the same file; it is played with Just Player (Legacy)
see [debuglog_v2023-10-11](https://paste.kodi.tv/sasuqowuku.kodi)

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: NVIDIA SHIELD Android TV with Android TV 11
 - Kodi version: kodi-20231012-94f0c210-master-arm64-v8a.apk

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Should be fixed with https://github.com/xbmc/xbmc/pull/23923
