### ISSUE TITLE
Inconsistent FileCache behavior when video file is opened from home screen 

### ISSUE THREAD

**Issue by thexai** [xbmc/xbmc#23933]
### Describe the bug
Here is a clear and concise description of what the problem is:

When video file is opened from home screen (clic on poster) `FileCache` is initialized with "single memory cache" strategy (not used double cache) while if it is opened from movies list is used correct double cache:

Movie opened from home:

```
CFileCache::XFILE::CFileCache::Open - <nfs://192.168.50.13/volume1/NAS/MKV/2/Bailarina (2023) [4K, DV].mkv> opening
CNFSFile::Open - opened volume1/NAS/MKV/2/Bailarina (2023) [4K, DV].mkv
CFileCache::XFILE::CFileCache::Open - <nfs://192.168.50.13/volume1/NAS/MKV/2/Bailarina (2023) [4K, DV].mkv> source chunk size is 131072, setting cache chunk size to 131072
CFileCache::XFILE::CFileCache::Open - <nfs://192.168.50.13/volume1/NAS/MKV/2/Bailarina (2023) [4K, DV].mkv> using single memory cache sized 67108864 bytes
```
 
Same movie opened from Movies list:
```
CFileCache::XFILE::CFileCache::Open - <nfs://192.168.50.13/volume1/NAS/MKV/2/Bailarina (2023) [4K, DV].mkv> opening
CNFSFile::Open - opened volume1/NAS/MKV/2/Bailarina (2023) [4K, DV].mkv
CFileCache::XFILE::CFileCache::Open - <nfs://192.168.50.13/volume1/NAS/MKV/2/Bailarina (2023) [4K, DV].mkv> source chunk size is 131072, setting cache chunk size to 131072
CFileCache::XFILE::CFileCache::Open - <nfs://192.168.50.13/volume1/NAS/MKV/2/Bailarina (2023) [4K, DV].mkv> using double memory cache each sized 33554432 bytes
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Same FileCache strategy used. The correct one (at least for MKV videos) is "double memory cache" because is what used before always.

This is a fallout from https://github.com/xbmc/xbmc/pull/23848:  tested master branch in ba7adbd6d5b138e62f497c5c2800032eb1936e20 (previous merge) and not happens.

## Actual Behavior
Inconsistent FileCache strategy and forward memory size depending if files are played from home screen posters or Movies list, etc.

## Possible Fix
Root cause is unknown to me but seems the intermediate cause is incorrect mime type in `CApplication::PlayFile`

When "fails" mime type is `application/octet-stream` instead of `video/x-matroska`

![mime-application](https://github.com/xbmc/xbmc/assets/58434170/a0b3c966-ab57-4bf2-a6a8-58eef6b34f27)

![mime-matroska](https://github.com/xbmc/xbmc/assets/58434170/fb7bae88-afc5-4343-8136-7f1775724307)

Opening file from home screen but using context menu "Play" then is also filled correct mime type:

![context-menu](https://github.com/xbmc/xbmc/assets/58434170/8851c380-32dc-430c-aef4-96bcf09b3623)

### To Reproduce

1. Play file from home screen posters and observe debug logs
2. Compare playing same video file from Movies section
3.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ixuvawonib.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.0-ALPHA3 (20.90.301) Git:20231014-4e5909fa99

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
A possible "fix" is remove this code:

![hacky-fix](https://github.com/xbmc/xbmc/assets/58434170/5cf03808-155f-4dda-bb5f-744508e7f913)

Then when mime type is empty is obtained the correct one later in:

https://github.com/xbmc/xbmc/blob/49cf52f515546256a867173f5edfaf474986d95b/xbmc/application/Application.cpp#L2317-L2318
 
But I'm not familiar with this code and all recent related changes and I don't know if this can break even more things...

**Comment by ksooo** [comment]
@thexai can you give this patch a try? Should fix it.

```diff
diff --git a/xbmc/FileItem.cpp b/xbmc/FileItem.cpp
index d6f0f6d1ba..8873a9c1b1 100644
--- a/xbmc/FileItem.cpp
+++ b/xbmc/FileItem.cpp
@@ -1767,6 +1767,8 @@ void CFileItem::UpdateInfo(const CFileItem &item, bool replaceLabels /*=true*/)
   if (!item.GetArt().empty())
     SetArt(item.GetArt());
   AppendProperties(item);
+  m_mimetype.clear();
+  FillInMimeType();
 }
 
 void CFileItem::MergeInfo(const CFileItem& item)
@@ -1835,6 +1837,8 @@ void CFileItem::MergeInfo(const CFileItem& item)
       SetArt(item.GetArt());
   }
   AppendProperties(item);
+  m_mimetype.clear();
+  FillInMimeType();
 }
 
 void CFileItem::SetFromVideoInfoTag(const CVideoInfoTag &video)
@@ -3781,10 +3785,9 @@ bool CFileItem::LoadDetails()
 
     if (ret)
     {
-      m_videoInfoTag = tag.release();
-      m_strDynPath = m_videoInfoTag->m_strFileNameAndPath;
+      const CFileItem loadedItem{*tag};
+      UpdateInfo(loadedItem);
     }
-
     return ret;
   }
 
@@ -3816,8 +3819,8 @@ bool CFileItem::LoadDetails()
     auto tag{std::make_unique<CVideoInfoTag>()};
     if (db.LoadVideoInfo(GetDynPath(), *tag))
     {
-      m_videoInfoTag = tag.release();
-      m_strDynPath = m_videoInfoTag->m_strFileNameAndPath;
+      const CFileItem loadedItem{*tag};
+      UpdateInfo(loadedItem);
       return true;
     }
 
```

**Comment by thexai** [comment]
Yes, this diff fixes it 🙂

**Comment by ksooo** [comment]
> Yes, this diff fixes it 🙂

@thexai , thanks for testing. I will fine-tune the code a bit, then PR.
