### ISSUE TITLE
kodi dolby vision bug

### ISSUE THREAD

**Issue by usemore** [xbmc/xbmc#23937]
### Describe the bug
Here is a clear and concise description of what the problem is:

kodi detects my tv's ability to play dolby vision files,
but renders only the sound and a black screen on googletv/android

..i've researched this issue extensively, and it always comes back to kodi because:
my tv supports dv (hisense)
dv works on apps other than kodi
dv works on kodi with an external device (firestick)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

i expect to see picture and for the tv to indicate dolby vision mode

## Actual Behavior

sound with black screen

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

daily master or alpha

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
This bug report is useless to us without debug log and steps to reproduce. 

Dolby Vision works perfectly on Shield, Fire Stick and others...

For support use forum instead: https://forum.kodi.tv/forumdisplay.php?fid=164

**Comment by usemore** [comment]
so we just close issues if it works for us?
i guess we'll never have dv on kodi googletv's then?

**Comment by enen92** [comment]
> so we just close issues if it works for us? i guess we'll never have dv on kodi googletv's then?

We close issues if the issue template is not respected (no debug log) since it's pretty much useless.
