### ISSUE TITLE
cannot compile Kodi cannot sideload it Sonoma, tvos 17 and Xcode 15

### ISSUE THREAD

**Issue by TresPorCiento** [xbmc/xbmc#23945]
it is impossible to compile Kodi in tvOS. Tons of issues problems... I have been fixing some but solve 10 and 100 appears..
Using Xcode 15 for tvOS 17 in Sonoma 14.0

Today it is not possible to get the IPA and side load it.  It fails. Seems something has changed.
The side load fails with all the apps not just Kodi.

Sideload worked great with Xcode 14, tvOS 16.4 and Ventura 13.6

Error installing  '/Users/userid/Documents/Local.nosync/AppleTV/kodi20.2-tvos.ipa', ERROR: Error Domain=com.apple.dt.CoreDeviceError Code=3002 "Failed to install the app on the device." UserInfo={NSLocalizedDescription=Failed to install the app on the device., NSURL=file:///Users/userid/Documents/Local.nosync/AppleTV/kodi20.2-tvos.ipa, NSUnderlyingError=0x6000181fb510 {Error Domain=com.apple.dt.CoreDeviceError Code=3000 "The item at kodi20.2-tvos.ipa is not a valid bundle." UserInfo={NSURL=file:///Users/userid/Documents/Local.nosync/AppleTV/kodi20.2-tvos.ipa, NSLocalizedFailureReason=Failed to read the bundle., NSLocalizedDescription=The item at kodi20.2-tvos.ipa is not a valid bundle.}}}
Domain: com.apple.dt.DVTCoreDevice
Code: -1
User Info: {
    DVTErrorCreationDateKey = "2023-10-16 17:08:13 +0000";
}
--

System Information

macOS Version 14.0 (Build 23A344)
Xcode 15.0 (22265) (Build 15A240d)
Timestamp: 2023-10-16T14:08:13-03:00

**Comment by TresPorCiento** [comment]
Your template is useless coz it is a very simple problem. do not side load any more and impossible to compile it.

**Comment by ginofalaci** [comment]
Just use 'Apple Configurator' instead of Xcode to install on your device and it's working.... until Apple fix this and so many other bugs...

**Comment by samip5** [comment]
Yeah, wasn't able to use Apple Configurator either for it, as it will just say unable to install.

**Comment by sarbes** [comment]
Please use the forum to get support for compiling Kodi.
