### ISSUE TITLE
Kodi crashes when started in Cage window manager with no displays

### ISSUE THREAD

**Issue by maufl** [xbmc/xbmc#23947]
### Describe the bug
When Kodi is started using the [cage](https://github.com/cage-kiosk/cage) window manager and there is no display attached, then Kodi crashes (and cage exits).
I describe the same problem on an issue on cage https://github.com/cage-kiosk/cage/issues/279

Additional context:
I tried to work around this by explicitly adding a headless output to cage, which works, but currently can't be removed at runtime again. Once the HDMI display is available, Kodi then spans both outputs, which means I won't see all of it on the HDMI display.
I tried to find out how to only start Kodi once the HDMI display is attached, but this seems to be the one thing that is dam need impossible on Linux, if you are not already running a display manager.

## Expected Behavior
My preferred behavior would be that Kodi is able to handle this case and delay initializing the GUI until an display is available. If that is not something that the Kodi team wants to implement, then it I would at least expect Kodi to exit cleanly with an error message.

## Actual Behavior
It simply crashes with an segmentation fault.

## Possible Fix
* Delay initializing the GUI until a display is available
* Exit with an error message

### To Reproduce
1. Install cage and kodi
2. Disconnect all screens and connect to the machine via SSH
3. Start Kodi using cage, for example `/usr/bin/cage -- /usr/bin/kodi-standalone`

### Debuglog
Unfortunately, the crashlog written by Kodi doesn't contain any error messages, even the stack trace part is empty.

However, a stack trace logged by systemd-coredump is available: https://paste.kodi.tv/ohihupideg

### Your Environment
Used Operating system:
 - [x] Linux

 - Operating system version/name: Arch Linux, up to date
 - Kodi version: 20.2

**Comment by sarbes** [comment]
No response from OP.
