### ISSUE TITLE
PULSEAUDIO is missing from the audio output devices list

### ISSUE THREAD

**Issue by smp79** [xbmc/xbmc#23952]
### Describe the bug
Here is a clear and concise description of what the problem is:

No pulseaudio after https://github.com/xbmc/xbmc/commit/a30bb554690dac6120351cf7a4bc57841600445a Reverting that commit fixes the issue.

### Debuglog

The debuglog can be found here:
https://hastebin.com/share/xenayijoti.yaml

### Your Environment
Used Operating system:

 - [x] Linux

 - Operating system version/name: LibreELEC 12
 - Kodi version: master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HiassofT** [comment]
@fuzzard you seem to have dropped the `-DHAS_PULSEAUDIO=1` definition which is checked for in
https://github.com/xbmc/xbmc/blob/master/xbmc/platform/linux/OptionalsReg.cpp#L34
