### ISSUE TITLE
Blu-ray disks can't be played from the Videos menu if Default select action is set to resume

### ISSUE THREAD

**Issue by Uukrull** [xbmc/xbmc#23965]
### Describe the bug

Playing a BD iso from the Videos menu:

![kodi1](https://github.com/xbmc/xbmc/assets/5891591/2f0d3636-c20c-4b36-9ed7-0837d8efe17d)

if the Blu-ray playback mode is set to Show Blu-ray menu:

![kodi2](https://github.com/xbmc/xbmc/assets/5891591/ba271a0a-e5d9-4119-8df6-0b27c82cc528)

and the Default select action is set to resume:

![kodi3](https://github.com/xbmc/xbmc/assets/5891591/4fb51ecb-380b-48ba-942a-e0cb479e85e7)

and no resume bookmark exists, doesn't work.

## Expected Behavior

The BD should play with all that conditions.

## Actual Behavior

It doesn't play with this error:

>2023-10-20 10:24:44.180 T:2924    error <general>: CDVDDemuxFFmpeg::Open - error probing input format, nfs://192.168.1.15/mnt/DOWNLOAD/News/Test.iso
>2023-10-20 10:24:44.180 T:2924    error <general>: CVideoPlayer::OpenDemuxStream - Error creating demuxer
>2023-10-20 10:24:44.180 T:2924     info <general>: CVideoPlayer::OnExit()

### To Reproduce

Try to play a BD with all the conditions explained above.

### Debuglog

[kodi.log](https://github.com/xbmc/xbmc/files/13052059/kodi.log)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64-bit
 - Kodi version: Kodi (21.0-BETA1 (20.90.801) Git:20231018-8262078680)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Seems to be bound to the chosen "Blu-ray playback mode". The issue is present if set to "Show Blu-ray menu". Setting to any other of the setting values does start playback just fine.

**Comment by Uukrull** [comment]
PR tested and working. Many thanks!
