### ISSUE TITLE
In Choose Art Menu only 1 background image is displayed for Movies & TV Shows even after trying multiple scrapers 

### ISSUE THREAD

**Issue by Rudders1973** [xbmc/xbmc#23981]
### Describe the bug
Here is a clear and concise description of what the problem is:

In Choose Art Menu only 1 background image is displayed for Movies & TV Shows even after trying multiple scrapers. In Kodi 20 multiple fanart images were available to chose from. Now only 1 is available to choose from in Kodi 21 Alpha.
Posters and the other art options show multiple images as expected.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

In Choose Art Menu I should see multiple fanart images to choose from like all the artwork options.

## Actual Behavior

In Choose Art Menu only 1 fanart background is being displayed to be chosen even in multiple scrapers.

### To Reproduce

1. File information TV Show / Movie
2. Choose Art 
3. Fanart

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - Operating system version/name: Windows 10 22H2
 - Kodi version: Omega Alpha 3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
> Kodi version: Omega Alpha 3

@Rudders1973  meanwhile, Omega Beta 1 is out. Can you give it a try and report whether this makes a difference?

**Comment by KarellenX** [comment]
That has been reported on the forum recently... https://forum.kodi.tv/showthread.php?tid=374748

Update to Beta 1 and the issue will be fixed.

**Comment by Rudders1973** [comment]
Tanks working now
