### ISSUE TITLE
Estouchy black screen android

### ISSUE THREAD

**Issue by doobydooby72** [xbmc/xbmc#23991]
### Describe the bug
Estouchy causes black screen on android.

## Expected Behavior
I choose estouchy, close app, reopen app and it should display fine as it did before closing the app.

## Actual Behavior

Basically i choose estouchy on the interface settings, if i close the app via android interface it would reset to default interface and no problem. If i choose estouchy then close via the in app shutdown button then reopen the app it still displays kodi notifications but is otherwise completely black with no fix besides going into the app data files and deleting them to reset the interface to default.

### To Reproduce

1. Choose estouchy under interface settings
2. Close the app via in app shutdown button (android based closing of the app resets it to the default interface).
3. Reopen app to a black screen with the exception of in app notifications.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: android 9
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
No response from OP.
