### ISSUE TITLE
SMB speed is limited by small chunk size, video playback stutters on high bitrate files

### ISSUE THREAD

**Issue by hugbug** [xbmc/xbmc#24001]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing back high bitrate files from SMB the player stutters.
Kodi is running on Fire TV Stick 4K Max. SMB share is on Windows PC, SSD drive.
Increasing chunk size from current 64KB to 256KB fixed the issue completely for me.

https://github.com/xbmc/xbmc/blob/3e13d1a3557f66b73928cf1eeaa49c1b6e10d667/xbmc/platform/posix/filesystem/SMBFile.h#L82

### More details
Observed player information (ctrl+shift+o) during playback. The video bitrate fluctuated between 50 and 90 Mb/s. On certain scenes where bitrate was constantly high near 80 Mb/s the video buffer started to slowly decrease. After a minute or so the buffer was empty, the playback paused to fill the buffer.

Monitored network activity during playback. The network speed never exceeded 90 Mb/s.

Then I made another test. Using Kodi File Manager copied a large file from SMB share to local storage. The File Manager showed copying speed and it was about 10MB/s. Tried copying the same file using other app on the same device and the copying speed was 35MB/s.

Another test was to try FTP. Configured FTP server on the same Windows PC. Result: playback in Kodi without issues. Copy speed in Kodi: 20MB/s.

Then I tested Kodi on Mac and tried to copy the same file (using Kodi File Manager). The speed on Mac was 17MB/s. Tried to copy this same file using Finder - speed was 80MB/s.

It was clear that something limits SMB performance in Kodi.

Studied the Kodi code and found out that chunk size is set (hardcoded) to 64KB for SMB files. Tried to increase it and got immediate performance boost. Copy speed results using Kodi File Manager (reproducible):

|Chunk size -> | 64KB | 128KB | 256KB | 512KB | 1024KB |
| --- | --- | --- | --- | --- | --- |
|MacBook 2015, MB/s | 17 | 26 | 36 | 46 | 54 |
|Fire TV Stick 4K Max, MB/s | 10 | 15 | 23 | 27 | 30|

I'd like to point out that I don't really care about copy speed in File Manager. However File Manager is the easiest way to test SMB speed. The results of these tests correspond  very well to the smoothness of playback. Knowing copy speed is a good indicator of what to expect in player for certain bitrates.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Playback should not stutter if the network speed is sufficient and the performance isn't limited by hardware. Kodi should be able to read from SMB shares at speeds limited by network connection and not by a hardcoded buffer size.

## Actual Behavior

Video playback stutters on high bitrate files. Reading from SMB shares is three times slower than other apps can do; it is also two times slower than reading from FTP in Kodi.

## Possible Fix

I was able to fix the stuttering issue by increasing the chunk size from 64KB to 256KB.

I'm not sure if that simple change of the constant is a proper solution for all users. I've studied the issues related to SMB and also to chunk size (for other file sources). The following issues are related to chunk size: #22946, #22941, #22920.

From the comments I've learned that chunk size is a sensible area and should be chosen wisely. I understand the goal to have a default size which provides the best compatibility. On the other side we want to use Kodi on modern devices for playback of modern sources. I consider my setup as typical enough and not extravagant in any way: Fire TV Stick 4K Max with Kodi; Windows PC with network share (where SMB is a native share protocol); playing back Blu-ray 4K remuxes (mkv).

If there are objections to increasing of hardcoded chunk size, then maybe it's worth a setting? Either an advanced setting or even a setting in GUI.

Another consideration would be to change the behaviour of caching. Currently hardcoded chunk size overrides any change made to advanced setting for chunk size.

### To Reproduce

Using File Manager is the easiest way to reproduce the issue (and to test a possible fix)
1. Open File Manager in Kodi
2. Connect to network SMB share
3. Copy a large file (1GB) to local storage.
4. Observe copying speed in the progress window.
5. Compare with network connection speed.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ujiyiqupiy.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

- [x] Android
- [ ] iOS
- [ ] tvOS
- [ ] Linux
- [ ] macOS
- [ ] Windows
- [ ] Windows UWP

- Operating system version/name: Fire OS 7.6.6.4.
- Kodi version: Omega Beta 1.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
You MUST provide debug log because chunk size is determined at runtime based on FileCache, advancedsettings and filesystem and is indicated in **debug log**:

https://github.com/xbmc/xbmc/blob/b29d4d26b2a602659748b051308fa7b9f3f439b8/xbmc/filesystem/FileCache.cpp#L128-L133


> Another consideration would be to change the behaviour of caching. Currently hardcoded chunk size overrides any change made to advanced setting for chunk size.

Default chunk size when is used FileCache (default enabled) is 128K:

https://github.com/xbmc/xbmc/blob/b29d4d26b2a602659748b051308fa7b9f3f439b8/xbmc/settings/AdvancedSettings.cpp#L402

**Comment by thexai** [comment]
> If there are objections to increasing of hardcoded chunk size, then maybe it's worth a setting? Either an advanced setting or even a setting in GUI.

This advanced setting already exists:

```
<cache>
  <chunksize>xxx</chunksize>
</cache>

```

**Comment by hugbug** [comment]
Thanks for looking into this.

My kodi.log on Fire TV Stick doesn't include any debug-entries but only info-entries, although the debug logging is activated in settings and debug overlay is properly shown.

Therefore I provide kodi.log from Mac, where debug-entries are written correctly: https://paste.kodi.tv/ujiyiqupiy.kodi

As you can see file cache sets chunk size to 64KB ignoring advanced setting:

> 2023-10-26 18:32:43.830 T:6929035   debug <general>: CFileCache::Open - <smb://myserv/Videos/Test Patterns/Sounds/dolby-atmos_amaze.mp4> source chunk size is 65536, setting cache chunk size to 65536

This happens because `CFile::DetermineChunkSize` gives priority to the chunk size from file system class, in our case `‎CSMBFile::GetChunkSize`‎:

https://github.com/xbmc/xbmc/blob/b29d4d26b2a602659748b051308fa7b9f3f439b8/xbmc/filesystem/File.cpp#L422-L427

Assuming this was done for a reason I suggested a new setting specifically for SMB. If `CFile::DetermineChunkSize` can be rewritten to respect existing advanced setting instead - even better.

**Comment by fritsch** [comment]
Nice find. The user provided chunksize should have priority. Same issue with NFS, most servers return 0, but NFSFile itself falls back to 256K, not allowing chunksize to be configured larger than this.

@thexai what do you think? Just changing the DetermineChunkSize ot use the highest provided value?

**Comment by fritsch** [comment]
There is some more code in the file you linked, namely:  https://github.com/xbmc/xbmc/blob/b29d4d26b2a602659748b051308fa7b9f3f439b8/xbmc/filesystem/File.cpp#L1015 and https://github.com/xbmc/xbmc/blob/b29d4d26b2a602659748b051308fa7b9f3f439b8/xbmc/filesystem/File.cpp#L1076

The first one seems plain wrong to me, the second one will drive the DetermineChunkSize nuts again, cause the later returns the "original" value again.

Both need proper adjustment.

**Comment by fritsch** [comment]
I agree: https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/NFSFile.cpp#L340 

What's your take on the m_frontSize I outlined above, which would not even have enough space?

**Comment by thexai** [comment]
At this time the only safe change for me is change SMB to 128K here:

https://github.com/xbmc/xbmc/blob/3e13d1a3557f66b73928cf1eeaa49c1b6e10d667/xbmc/platform/posix/filesystem/SMBFile.h#L82

and here:

https://github.com/thexai/xbmc/blob/3e13d1a3557f66b73928cf1eeaa49c1b6e10d667/xbmc/platform/win32/filesystem/Win32File.cpp#L768

**Comment by hugbug** [comment]
128KB improves speed by 50%, according to my tests (see the table in the first post).

That's a good improvement, sure, but isn't that weird, that the transfer speed from the Internet can be better (thanks to advanced setting) than the speed in local network (SMB and NFS)?

Very high bitrate files are more likely on local servers.

**Comment by smp79** [comment]
I did some testing with different SMB chunk size values a while ago. Higher chunk sizes caused issues with BD ISOs and TS files (slow opening). So any change to a current default should be thoroughly tested.

**Comment by fritsch** [comment]
Which values cause that issues? And which are fine?

**Comment by smp79** [comment]
https://forum.kodi.tv/showthread.php?tid=258904&pid=2821385#pid2821385

That was a few years ago, I tested on RPi3 on a 100M ethernet. 
Back then there was a consensus that 64K is the optimal value for most cases. In that post I actually made a suggestion that this should be user configurable.

**Comment by fritsch** [comment]
Yeah - I also remember the PI2 where this was a huge endevaour as it caused the difference in CPU to work or not work. So I think finding the optimal values when people use VPN or use WLAN or use 100 Mbit or 1Gbit/s LAN is problematic by definition.

Yes - user should have an opportunity to change it for his needs.

**Comment by hugbug** [comment]
> https://forum.kodi.tv/showthread.php?tid=258904&pid=2821385#pid2821385

In these tests larger values were all good for TS but opening of BD ISOs suffered from larger chunks. I guess a lot of seek operations is needed during opening of ISOs. However I expect ISOs to require larger chunks during playback (depends on bitrate, of course).

if only File Cache would be smart enough to understand what is currently happening and adjust the chunk size dynamically.

Still don't see why the chunk size should depend on network protocol. Especially why treat SMB, NFS, FTP and local files differently. Local USB sticks maybe way slower than SMB shares connected to NVMe SSDs.

Specialised streaming protocols are probably a different thing.

**Comment by smp79** [comment]
Yeah, actually lower (32K) was problematic for TS. BD ISOs didn't like higher values.

**Comment by fritsch** [comment]
Yes - if it was smart enough ;-). Btw. it could be fast enough, depending on fillrate and drop rate not only reading faster, but also reading bigger. That way it might even realize that it does not read a mkv, but a bluray iso, etc.

Though - more difficult to find a sweet spot for the user.

I wonder though what "os mounts" do better. If you mount the FS from Linux directly / etc. people do not tend to have any performance issues.

**Comment by hugbug** [comment]
> I wonder though what "os mounts" do better. If you mount the FS from Linux directly / etc. people do not tend to have any performance issues.

For one I expect them to support multithreading, whereas the whole SMB stuff in Kodi goes through one critical section (because libsmbclient isn't thread safe). I had big issues with library watcher addon in Kodi Omega. The addon scanned SMB share during playback (it shouldn't but it did) causing the playback to stutter regardless of bitrate. It took me days to figure that out.

**Comment by thexai** [comment]
With some preliminary tests not seems cause issues use 128 K chunk size for SMB: tested Windows and Android BD ISOs, and BDMV folders Blu-Ray and UHD Blu-Ray (on Windows tested also with Java menu's). 

I would agree to increase SMB chunk size to 128K, although some things must be taken into account:

On Shield (which is also Android) not have these performance issues when using 1 Gbps Ethernet. 120 Mbit/s videos or even 200 Mbit/s using current 64K works fine.

https://www.larmoire.info/jellyfish/

Note that UHD Blu-Ray spec is limited to 144 Mbit/s (video+audio) anyway.

Fire Stick has some type of specific problem (although improves by increasing the chunk size). Other users had already reported it before: https://github.com/xbmc/xbmc/pull/23784#issuecomment-1751811065 

This user had similar problems and solved them by changing Fire Stick 4K max to Fire TV Cube. Then the 80% of the issue is specific to Fire Stick.

**Comment by fritsch** [comment]
This PR does not fix FireTV Firmware flaws, where the reading thread especially over wifi simply runs into CPU limitation.

Use a usb 3.0 Ethernet adapter.

**Comment by jp12git** [comment]
@fritsch was this concluded somewhere? I read this and the other thread and didn't find this conclusion.

> wifi simply runs into CPU limitation

What I don't get is that if this device can past Speedtest on Wifi at 200 Mbps+ so why does the Wifi run into CPU limitation on a 100 mbps file?

**Comment by fritsch** [comment]
I see that you don't get it, which is mostly why jumped into this thread, which does not cover your issue at all. First: I own all of those FireTV devices ... and did extensively test their throughput and capabilities next to a perfect Wifi6 network condition, on wireless, internal Ethernet (Cube) and also with USB 3.0 dongle.

The internal of the firetv speedtest does not tell the complete picture, cause you don't test the system behaviour under real load. No video is decoded, no audio is processed, no demuxer running. Also no one knows how the speed test they use is implemented, most likely some http download - not comparable with SMB throughput. I already found it odd, that the device can only achieve 240 Mbit, where similar technology devices achieve 600 Mbit/s and more in same environment. A Video player works differently, it requests chunk by chunkm here latency plays more of a role than throughput. A combination of a large readahead cache (kodi's advancedsettings) helps here a bit, but also afterwards buffers run dry.

Coming back to kodi:
Simply replacing the wifi device by an USB 3.0 (running USB 2.0 speed) 1Gbit/s Ethernet card made it work. So conclusion is quite obvious. This is btw. the same no matter if Firetv Cube 3rd Gen (a tad better cause better CPU) or Firetv 4K 2nd Gen.

And as you see from the bug description, the one you highjacked, you see that the original poster emphasizes on: bigger chunks make bigger throughput. While for your FireTV device - from the given information - it does not have the same effect.

So if you want to make more real comparison. Use the provided build, set the chunk size to 1 MB, restart kodi and simply try to copy a file with the filemanager into kodi - the rate you see there, combined with the CPU load gives a bit of a glance what throughput you can expect in real life, using the same protocol you are streaming off.

**Comment by fritsch** [comment]
My results:
Firetv 4K Max Gen2 with NFS source: 
- USB-Ethernet (327 Mbit/s FireTV measurement value): ~35 MB/s (quite nice, somewhere at 40% of a theoretical USB 2.0 bandwidth), quite okay.
- Wifi6 Connection (speedtest firetv 240 Mbit/s): 10 MB/s <- nowhere anywhere enough for a 100 Mbit/s file.

I hope you see the difference now, especially why the 200Mbit/s you are seeing is worth nothing in practice ... if you compare it 1:1 to SMB / NFS performance.

**Comment by jp12git** [comment]
@fritsch Thank you for explaining! Unfortunately, I don't have an Ethernet port to route a cable to the Cube which is why I'm trying to make Wifi work. 

I did some more testing with Plex and can play the same Jellyfish 100 Mbps and 140 Mbps files smoothly. Even the 200 Mbps file buffers only slightly and plays smoother than the 100 Mbps file with Kodi (_Screenshot from System X-Ray below_). As you can see Plex hitting a peak of ~250 Mbps with this 200 Mbps file and it consistently hits 200 Mbps with 100 and 140 Mbps files.

![20231031_085844](https://github.com/xbmc/xbmc/assets/106448081/db5ce745-afd0-48e7-b954-3f8a2d463b23)

What can we conclude from this? Is it that Plex uses a different streaming protocol than NFS/SMB which is more efficient for streaming (while NFS/SMB are meant for file-shares)

**Comment by fritsch** [comment]
Most likely, yes. They might simply use http transport - you can try if kodi works better by streaming your file from a webserver near you. You can use a strm file for that, just put in the URL.

**Comment by hugbug** [comment]
On my Fire TV Stick 4K Max 1st gen Jellyfish 140 Mbps plays smoothly with SMB chunk size 512KB. Most of the time chunk size 256KB is also OK but it stuttered once with this file (from about 10 tests I made with this particular file).

With chunk size 1MB the stick can even play Jellyfish 250 Mbps till the end of clip without issues, if I pause the clip directly after starting for a few seconds to fill the buffer. The NET monitor on the stick shows network throughput of up to 280 Mbps during this.

@jp12git make a copy test in Kodi File Manager (copy a 500 MB file from SMB to stick). In my test I get 30 MB/s with 1 MB chunk size.

**Comment by hugbug** [comment]
@jp12git Are you using the latest build with the new setting for SMB chunk size? Have you tried different chunk sizes?

**Comment by jp12git** [comment]
> @jp12git Are you using the latest build with the new setting for SMB chunk size? Have you tried different chunk sizes?

Yep, tested using the latest nightly build and 1 MB chunk size for SMB and NFS. SMB was around 16-17 MB/s and NFS around 10 MB/s
