### ISSUE TITLE
Abnormal behavior of .strm library items in Kodi v21 Omega

### ISSUE THREAD

**Issue by vkapartzianis** [xbmc/xbmc#24015]
### Describe the bug
Here is a clear and concise description of what the problem is:

Library items sourced from .strm files have issues in v21 that weren't manifesting in earlier versions. For example, there's no tracking for having watched a movie, partially or entirely.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would've expected handling of .strm files to be at least as good as it were in earlier versions (which still have issues, like not enabling subtitles despite any global configuration setting).

## Actual Behavior

* Video library items sourced from .strm files don't track if the video has been partially or entirely watched -- items always show up as unwatched.
* Video library items sourced from .strm files always display the filename (not any movie title) when playing.
* Video library items sourced from .strm files don't display many metadata (e.g. posters) when playing.
* Video library items sourced from .strm files don't display video-related information (e.g. video/audio encoding) in the GUI. That information is available while playing the video.

Note that this isn't an exhaustive list. 

### To Reproduce

1. Create an .strm file containing a video URL.
2. Scan the item into the library.
3. Play the video and see if it shows up as partially watched

### Debuglog

The debuglog can be found here:

I can't spot any related errors in the log and I don't feel comfortable uploading an entire log. I can provide any lines that are known to be related.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 11
 - Kodi version: v21.0b1-Omega (and any nightly build after that)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
> Play the video and see if it shows up as partially watched

Can you tell from where do you start playback? There are many ways and the way actually can make a difference.

From: Estuary Home screen (like from recently added movies)? Movies window? Videos window? ...? 
By: Click? Context menu item? Hitting P on your keyboard? Clicking Play button in your remote? ...?

**Comment by vkapartzianis** [comment]
You are right, it does make a difference. All the issues go away if I play the videos through Settings -> Media -> Library -> Videos

**Comment by ksooo** [comment]
> All the issues go away if I play the videos through Settings -> Media -> Library -> Videos

And how exactly can I trigger the issue? Telling what to do that it works is fine, to reproduce I need to know how what to do to see it NOT working.

**Comment by vkapartzianis** [comment]
All my .strm files contain https links to .mp4 and .mkv files. All existing library items had the issue after upgrading from v20.2. All new videos scanned afterwards have the same issue. I deleted the library and scanned the items again but that didn't help.

In other words, I just create .strm files containing https links, and scan them in the library. If that doesn't trigger the issue for you, then maybe it's specific to Android TV? I tried other skins besides Estuary but that didn't help.

**Comment by vkapartzianis** [comment]
Just to be clear, if I play the videos through the lists in Estuary (e.g. recently added) I have all those issues. If I play the videos through the library sources (Settings -> Media -> Library -> Videos), then there's no issue.

**Comment by ksooo** [comment]
> Just to be clear, if I play the videos through the lists in Estuary (e.g. recently added) I have all those issues. If I play the videos through the library sources (Settings -> Media -> Library -> Videos), then there's no issue.

That is what I needed. Thanks.
