### ISSUE TITLE
Omega 21 Favorites don't show in Confluence skin

### ISSUE THREAD

**Issue by Frencman** [xbmc/xbmc#24023]
### Describe the bug
Here is a clear and concise description of what the problem is:

Favorites show on Estruary and Estouchy but not on Confluence.  Items are still there from before update and adding a new favorite does not show either?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
.

Favorites should appear in all 3 skins

## Actual Behavior

No reaction when Favorites icon is selected.

### To Reproduce

1. Change skin to Confluence
2.select Favorites star icon
3.Nothing happens.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

Running on fire tv cube
 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Omega 21 Beta

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
The skin needs to be updated for Omega. But this is not the right place to report this as Confluence is not part of Kodi.

**Comment by ksooo** [comment]
Please open the issue here: https://github.com/xbmc/skin.confluence

**Comment by Frencman** [comment]
Thank You!
