### ISSUE TITLE
dolby vision fails on googletv internal kodi 

### ISSUE THREAD

**Issue by usemore** [xbmc/xbmc#24030]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi has been near-perfect for me...love it!
the only thing missing is the ability to watch dolby-vision files on my hisense tv, which runs googletv and has kodi installed internally (actually i use it as the launcher).
While i've opened this issue previously, it got closed because someone didnt want to acknowledge it. I would really LOVE to see this issue resolved.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

playing dolby vision files should yield picture and sound

# Actual Behavior

i only get sound

### To Reproduce

1. turn on tv
2. select a dolby-vision file
3. click play

### Debuglog

The debuglog can be found here:

i'm not a developer, and while i wish to help any way i can...i dont have any debug logs.
i've never been able to extract any debug logs from kodi....turning on logging doesnt do anything.
if someone can provide instructions to extract the needed log i'm happy to do it.

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

this bug makes me sad. i was trying to watch a movie.
i can, however switch inputs over to my kodi on firestick4kmax which does does output dolby vision (in compatibility mode)...the tv detects the signal/metadata and displays correctly.
the internal kodi does play hdr correctly, just not dv.

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

android12/nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by usemore** [comment]
absolutely. as i mentioned, it works on the amazon fire stick 4k max.

**Comment by quietvoid** [comment]
There are users of GoogleTV on Sony TVs that have no issues, so at worst your issue is specific to Hisense TV.
Without a debug log there's no way for us to know what's happening.

Instructions: https://kodi.wiki/view/Log_file/Easy

**Comment by usemore** [comment]
quick update.. i'm going to try the debug. so far i've proven that the hisense media player can play the files just fine. i did a factory reset (much to my shagrin) and tried a fresh kodi install and realized that further to the dv problem, kodi cannot play hybrid hdr files, while the hisense media player handles them just fine. i'm using the sameple files linked directly from kodi.tv and i've tried with dv compatibilty mode on and off.

**Comment by quietvoid** [comment]
What sample file are you testing exactly?

**Comment by usemore** [comment]
hello kodi team! i just want to thank you for your good work! with the latest nightly -20231105- dolbyvision and hdr play on the hisense! looks good! another strange framedrop issue with sdr also seems to have been addressed! good work folks! i will close the issue
