### ISSUE TITLE
AppleTV | No Menu Sound

### ISSUE THREAD

**Issue by Patresko** [xbmc/xbmc#24035]
### Describe the bug
I have no sound when navigation in Kodi.tv. GUI sounds are set to be always on.

## Expected Behavior
I would expact to hear sounds when navigation in Kodi.tv

## Actual Behavior
No sound at all.

### To Reproduce
1.  Install Kodi
2. Try to navigate

### Debuglog
The debuglog can be found here: Dont know how to export log from AppleTV

### Your Environment

 - [x] tvOS

 - Operating system version/name:
 - Kodi version: Kodi 20

**Comment by sarbes** [comment]
No response from OP.
