### ISSUE TITLE
PVR: Recordings not playing from TV overview screen

### ISSUE THREAD

**Issue by flubshi** [xbmc/xbmc#24039]
### Describe the bug
Here is a clear and concise description of what the problem is:

When starting a TV recording from TV overview (see screenshot 1), the recording does not play. The log indicates that `GetRecordingStreamProperties` is not called in this case and thus the inpustream.adaptive properties were not set.

When starting a recording from TV -> recordings (folder view) (see screenshot 2) the recording plays as expected.

The error occurs on rpi4 using Omega-Beta1 and latest commit on arch linux. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When starting a recording from TV overview, the recording should play.

### To Reproduce

1. Install a PVR client that needs to set some properties when starting a recording (e.g. pvr.waipu)
2. play a recording from TV overview

### Debuglog

The debuglog can be found here:

Log when starting (and not working) from overview:

[kodi_no_pvr_recodings.log](https://github.com/xbmc/xbmc/files/13221002/kodi_no_pvr_recodings.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Recordings are **not playing** when called from overview:

![not_working_from_here](https://github.com/xbmc/xbmc/assets/4031504/b3d138fd-6a43-41d5-a582-cc2a5b6683c1)

Recordings are **playing** when started from recordings submenu:

![working_from_here](https://github.com/xbmc/xbmc/assets/4031504/5e34e12e-cf06-4721-9f99-6d35d5e32669)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux
 - Kodi version: 21.0-BETA1 (20.90.801) Git:20231031-ab478ddaf9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
@flubsh have you tried latest nightly? If not, could you please test and report back?

**Comment by flubshi** [comment]
@ksooo I compiled ab478dd (latest master) - it is also broken there.

**Comment by ksooo** [comment]
> I compiled https://github.com/xbmc/xbmc/commit/ab478ddaf935abd8fab8e12c49b26908b99e796e (latest master) - it is also broken there.

@flubshi thanks for the info. Unfortunately I do not have the possibility to test myself, as I have no subscription for one of those services provided by a pvr add-on using inputstream.adaptive for playback of recordings.

**Comment by ksooo** [comment]
@flubshi can you apply this patch and report back, please?

```diff
diff --git a/xbmc/interfaces/builtins/PlayerBuiltins.cpp b/xbmc/interfaces/builtins/PlayerBuiltins.cpp
index d063a39e84..a7e3c56a9f 100644
--- a/xbmc/interfaces/builtins/PlayerBuiltins.cpp
+++ b/xbmc/interfaces/builtins/PlayerBuiltins.cpp
@@ -608,7 +608,7 @@ int PlayOrQueueMedia(const std::vector<std::string>& params, bool forcePlay)
 
   if (forcePlay)
   {
-    if ((item.IsAudio() || item.IsVideo()) && !item.IsSmartPlayList())
+    if ((item.IsAudio() || item.IsVideo()) && !item.IsSmartPlayList() && !item.IsPVR())
     {
       if (!item.HasProperty("playlist_type_hint"))
         item.SetProperty("playlist_type_hint", PLAYLIST::TYPE_MUSIC);
```

**Comment by flubshi** [comment]
@ksooo it fixes the issue for me. Recordings are now also being played from overview screen. (and in folder view it is also still working)

**Comment by ksooo** [comment]
>  it fixes the issue for me.

Great. I will open a PR with the fix soon.

**Comment by flubshi** [comment]
Thank you for the quick and competent help!

**Comment by ksooo** [comment]
@flubshi do you know whether this works in Nexus 20.2 (without the patch, ofc) ? Or is it also broken there?

**Comment by flubshi** [comment]
@ksooo On Nexus 20.2 it works fine without the patch.
