### ISSUE TITLE
[Doxygen] Ingamesaves window missing from guilib/WindowIDs.dox

### ISSUE THREAD

**Issue by scott967** [xbmc/xbmc#24033]
### Describe the bug
Here is a clear and concise description of what the problem is:

Documentation error.    [Development docs](https://xbmc.github.io/docs.kodi.tv/master/kodi-dev-kit/window_ids.html) missing entry for Ingamesaves / WINDOWS_DIALOG_IN_GAME_SAVES / id 10829

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix

Not sure how to test doxygen changes but companion PR submitted.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
Documentation only but log shows opening window id 10829 (ingamesaves)
https://paste.kodi.tv/oqisuxiroq.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Skinning ingamesaves window

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 10 x64 22H2
 - Kodi version: v21 B1 compiled 2023-10-23

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by garbear** [comment]
I beefed up documentation for all game related stuff and updated window IDs in https://github.com/xbmc/xbmc/issues/24033
