### ISSUE TITLE
Closing Kodi from Kore doesn't return desktop

### ISSUE THREAD

**Issue by Miniontoby** [xbmc/xbmc#24038]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I close Kodi using the Kore app's button to send the Exit signal, kodi does close, but my desktop doesn't come back. With this I mean that the whole desktop stays black. I then have to OR cut the power OR run a script to get my desktop back:
```
kill `ps fx | grep lxsession | grep -v grep | sed -e 's/\?.*//' -e 's/\([^0-9]\)\+//'`
```

However if I close the Kodi using Kore (or any other controller) by going to the power menu of Kodi and then press the Exit button on the screen instead of on the Kore app, it will close Kodi and return my desktop.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I was expecting my Kodi to just close and return my desktop when I would send the close signal using the Kore app (and any other similar app)

## Actual Behavior

My Kodi closed and the screen stayed black.

## Possible Fix

I don't even know where I should look. For now I just use workarounds and I try to avoid using the feature as much as possible

### To Reproduce

1. Open Kodi
2. Login in your Kodi
3. Open Kore app
4. Send the Close signal in the menu at the Power icon
5. And see it happen

### Debuglog

The debuglog can be found here:
*NaN, there is no relevant information in there about this issue.*

### Screenshots 
Here are some links or screenshots to help explain the problem:

*If you want a black screenshot*

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

*NaN*

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspbian Bullseye
 - Kodi version: 19/matrix

**Comment by neo1973** [comment]
I can't reproduce this with current master on Linux/Wayland. Please provide the requested debug log, maybe we are able to find something inside it.

**Comment by sarbes** [comment]
No response from OP.

**Comment by Miniontoby** [comment]
Sorry that I didn't respond in a while. I wasn't really sure if I was able to reproduce it, but now I am sure.

Uhmm, so it is when ever I start Kodi whilst NOT having my tv/beamer powered on. This is because I start it using VNC and then I remember: Oh shoot, I had to start my tv/beamer. Then it won't display Kodi, so I try to turn Kodi off using Kore, and it doesn't return to desktop
