### ISSUE TITLE
Clean Library works wrong

### ISSUE THREAD

**Issue by mhbosch** [xbmc/xbmc#24046]
When i use "clean library" it will not clean the Database (mysql)

Here is a clear and concise description of what the problem is:
Many Items in the Database are not exist. The Log write a Error.
Normally the entry in the Database must be delete. But it will further exist and the next clean exit the same error.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix

Delete all not exist item from the database.
The Key are in PatH table an will be inspect by the strPath key.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please post a debug log like the template says.

**Comment by mhbosch** [comment]
Hello,

in the LOG there is the follow error:
 error <general>: XFILE::CDirectory::GetDirectory - Error getting smb://xxxxxxxx/Filme/Filme/Movie/

I think this is ok. The Path doesnt exists.
So i think, it will delete in the MySql DB in the Path table.
But there is no delete. The entry keep in the table. The error will be repeat by the next cleanup.

I hope it will help.
