### ISSUE TITLE
how come i can't use kodi but i hafl a IMac 

### ISSUE THREAD

**Issue by Mikeman46** [xbmc/xbmc#24057]
## Roadmap or todo item
**Detailed Description**

### Additional context, screenshots or links
Here are some relevant links or screenshots

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by Mikeman46** [comment]
how come i can't use kodi nomore

**Comment by enen92** [comment]
Use the forum for support pls
