### ISSUE TITLE
Kodi should sort by disc when browsing music folders. Again.

### ISSUE THREAD

**Issue by BenMcLean** [xbmc/xbmc#24050]
This is #20312 again.

### Describe the bug
Here is a clear and concise description of what the problem is:

I have a folder of music tracks I'm trying to play on KODI.
It is a folder on a network share of an album with multiple discs.
They are named like `[disc]-[track] [title].flac`
KODI should order them by filename.
Instead, it is ordering them by track number.
Even if you must for some reason insist on only using tags instead of filenames, the tag based sorting method should be sorting by disc before track number.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should order the tracks correctly, like this:
```
1-01 Disc 1, Track 1
1-02 Disc 1, Track 2
1-03 Disc 1, Track 3
2-01 Disc 2, Track 1
2-02 Disc 2, Track 2
```

## Actual Behavior

Kodi is ordering them incorrectly like this:
```
1-01 Disc 1, Track 1
2-01 Disc 2, Track 1
1-02 Disc 1, Track 2
2-02 Disc 2, Track 2
1-03 Disc 1, Track 3
```

## Possible Fix

There should be a way to choose whether you want tracks sorted by filename or tags, and when sorting by tags, they should be sorted by disc number before track number. Personally, I just want them sorted by filename.

To have tracks ordered by filename, whoever programmed Kodi simply needed to do less work. Files being ordered by filename alphanumerically is the order which the operating system gives you for free. Kodi is taking tracks which are already ordered correctly and going out of its way to put them into the wrong order. So to fix this, Kodi needs to be un-overengineered.

### To Reproduce

Get a multi-CD album, rip it as separate FLACs for the tracks, tag them with Picard and name them as `[disc]-[track] [title].flac` all in the same folder, then browse to that folder with Kodi. They will show up in the wrong order.

### Debuglog

The debuglog can be found here:
NA

### Screenshots
Here are some links or screenshots to help explain the problem:

NA

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

NA

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 11, SHIELD TV SW version 9.1.1 (33.2.057)
 - Kodi version: 20.2.0 (Google Play Store)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by BenMcLean** [comment]
> This is an automatically generated message. If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.

Please remove the label.

**Comment by BenMcLean** [comment]
I find two things about this very frustrating:

1. To have tracks ordered by filename, whoever programmed Kodi simply needed to do less work. Files being ordered by filename alphanumerically is the order which the operating system gives you for free. Kodi is taking tracks which are already ordered correctly and going out of its way to put them in the wrong order.

2. #20312 got ignored.

Yeah, I didn't post a log because this isn't a crash and I didn't post a screenshot because my text description is adequate.

**Comment by the-black-eagle** [comment]
What is the sort order in the left side-blade?  As long as your files are tagged correctly, then sorting by track will also sort by disc - track 01, disc 01 -> track n, disck 01 -> track 01, disc 02 etc

Also, you can sort by filename which should give you the results you are looking for.

**Comment by BenMcLean** [comment]
> What is the sort order in the left side-blade?

Ah, I didn't know that blade changed with each level I navigate to in the folder hierarchy. If I set it to "File" then the tracks go into the correct order. Thanks.

How do I set it to always sort by Filename everywhere?

**Comment by BenMcLean** [comment]
Oh, apparently there is an open issue for not being able to set a default sort here: https://github.com/add-ons/plugin.video.vrt.nu/issues/539

**Comment by the-black-eagle** [comment]
>How do I set it to always sort by Filename everywhere?

You can't.  At least not easily.  You will have to change it for each album you open, but once you do, Kodi will remember the setting for that album the next time you open it.

**Comment by BenMcLean** [comment]
> > How do I set it to always sort by Filename everywhere?
> 
> You can't. At least not easily. You will have to change it for each album you open, but once you do, Kodi will remember the setting for that album the next time you open it.

OK thanks for the info. 

> > How do I set it to always sort by Filename everywhere?
> 
> You can't. At least not easily. You will have to change it for each album you open, but once you do, Kodi will remember the setting for that album the next time you open it.

There's an existing request to fix that here: https://forum.kodi.tv/showthread.php?tid=350699
