### ISSUE TITLE
Movie scraper does not recognize ISO's in a 'Disc n' subdirectory

### ISSUE THREAD

**Issue by 78andyp** [xbmc/xbmc#24051]
When I moved to Kodi a few years ago I migrated from MyMovies (mymovies.dk) so used local NFO files.

I've decided to migrate away from that completely and use the Kodi default movie scraper.

It works well - except when you have subdirectories (Disc 1, Disc 2 etc..) under the main movie directory (eg. Avatar (2009))

Looking at the logs and code it sends 'Disc 1' to the scraper and you get loads of DTS test disc entries in the library!

I've made a couple of fixes - which work for me - I'm sure there's loads of reasons not to do it this way (and I wonder if the new 'editions' version that's in testing will be a much better answer) - this just works on my structure now without other intervention needed.

I'm just sharing in case anyone else has this issue - and this is my first try at adding code.

I know it's not the best - it could corrupt any movie that starts with the word 'Disc ' and assumes a single digit for the disc number in the title.

In FileItem.cpp, at the end of GetBaseMoviePath add:

```
    // Remove 'Disc' subdirectory
    size_t iPos = strMovieName.rfind("/Disc ");
    if (iPos != std::string::npos)
      strMovieName.erase(iPos + 1);
```

This removes any Disc subdirectories for the scraper.

I've also added - in VideoInfoScanner.cpp, in the AddVideo routine:

```
 // Deal with 'Disc' subdirectories
      size_t iPos = movieDetails.m_strFileNameAndPath.rfind("/Disc ");
      if (iPos != std::string::npos)
        movieDetails.m_strTitle +=
            " (" + movieDetails.m_strFileNameAndPath.substr(iPos + 1, 6) + ")";

      lResult = m_database.SetDetailsForMovie(movieDetails, art);
```

This just appends (Disc n) to the title that appears in the library.

Debug log - [kodi - Copy.zip](https://github.com/xbmc/xbmc/files/13238995/kodi.-.Copy.zip)

Picture - 
<img width="1280" alt="image" src="https://github.com/xbmc/xbmc/assets/99039295/614b6f72-a9ce-493f-8de7-4fcc72e36148">

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.b1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by 78andyp** [comment]
I've submitted a pull request so will close this.

**Comment by garbear** [comment]
(It's a good idea to link PRs and they even get backlinks) See PR: https://github.com/xbmc/xbmc/pull/24076
