### ISSUE TITLE
New library SQL schema missmatch

### ISSUE THREAD

**Issue by lameventanas** [xbmc/xbmc#24067]
### Describe the bug
I'm setting up a shared library database.
I have some media files in an NFS share, but I'm not trying to import an existing library.

I have these files in `~/.kodi/userdata/Database`:
```Addons33.db
Epg16.db
TV40.db
TV43.db
TV44.db
Textures13.db
ViewModes6.db
```

Then I configured the MySQL server in advancedsettings.xml and start kodi, next thing I know I have 2 brand new databases in mysql:
kodi_video83 and kodi_video122.
If I try to scan a directory with TV series, it doesn't do anything and the database remains empty.

It looks that on first start, it creates the kodi_video83 database, and then migrates it to kodi_video122, which seems weird, is it supposed to do that?

And after the process is finished, the logs show that kodi does some queries that don't correspond to the schema of the newly created database.

For example:
`
SELECT path.strContent, path.strScraper, path.scanRecursive, path.useFolderNames, path.strSettings, path.noUpdate, path.exclude, path.allAudio FROM path WHERE strPath='library://video/'
`

But the table looks like this:

```
MariaDB [kodi_video122]> desc path;
+---------+--------------+------+-----+---------+----------------+
| Field   | Type         | Null | Key | Default | Extra          |
+---------+--------------+------+-----+---------+----------------+
| idPath  | int(11)      | NO   | PRI | NULL    | auto_increment |
| strPath | varchar(512) | YES  |     | NULL    |                |
| strHash | text         | YES  |     | NULL    |                |
+---------+--------------+------+-----+---------+----------------+
3 rows in set (0.007 sec)
```

## Expected Behavior
I was expected a single kodi_video122 database, with the correct schema

## Actual Behavior
Kodi creates 2 databases instead of 1, with a mismatching schema

### To Reproduce

1. Set up an SQL server to advancedsettings.xml
2. Start kodi
3. Try to scan anything to the library

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/13283979/kodi.log)
[kodi.log with debug enabled](https://github.com/xbmc/xbmc/files/13283987/kodi-debug.log)
[mysqldump of kodi_video83](https://github.com/xbmc/xbmc/files/13284027/kodi_video83.txt)
[mysqldump of kodi_video122](https://github.com/xbmc/xbmc/files/13284028/kodi_video122.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Running everything on an Odroid C4 with MariDB 10.9.3 from Entware.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 Kodi version: 21.0-BETA1 (20.90.801) Git:0361ffded35b132d463bd1836f05ae6cf68cf7da). Platform: Linux ARM 32-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by the-black-eagle** [comment]
You have named BOTH the music and video databases kodi_video. This is _never_ going to work.

**Comment by lameventanas** [comment]
Well, that's the problem, I copied & pasted the xml node of the video library for music, and had the db name there
So it created kodi_video83 (music db) and then used that to migrate to kodi_video122 (video db), and of course, the schema didn't match.
Thanks!
