### ISSUE TITLE
Nexus + addons not compatible with Python 3.12

### ISSUE THREAD

**Issue by obaterspok** [xbmc/xbmc#24069]
Kodi Nexus crashes when adding Retrospect addon due to Python 3.12. This seems to work okay in main-branch where XBPython.py has a note regarding this around line 500:

```
    // *::GlobalInitializeModules() functions call PyImport_ExtendInittab(). PyImport_ExtendInittab() should
    // be called before Py_Initialize() as required by the Python documentation.
    CAddonPythonInvoker::GlobalInitializeModules();

#ifdef HAS_WEB_INTERFACE
    CHTTPPythonWsgiInvoker::GlobalInitializeModules();
#endif

    Py_Initialize();

```
Fedora 39 however uses Nexus + Python 3.12 and it triggers a crash that is due to the below Python release note:

https://docs.python.org/3/whatsnew/changelog.html

"Core and Builtins

gh-81057: The docs clearly say that **PyImport_Inittab, PyImport_AppendInittab(), and PyImport_ExtendInittab() should not be used after Py_Initialize() has been called**. We now enforce this for the two functions. Additionally, the runtime now uses an internal copy of PyImport_Inittab, to guard against modification"

Fatal Python error: PyImport_AppendInittab: PyImport_AppendInittab() may not be called after Py_Initialize()
Python runtime state: initialized

#0  0x00007f9ca1718834 in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007f9ca16c68ee in raise () at /lib64/libc.so.6
#2  0x00007f9ca16ae8ff in abort () at /lib64/libc.so.6
#3  0x00007f9ca45a7caa in fatal_error () at /lib64/libpython3.12.so.1.0
#4  0x00007f9ca45a8020 in faulthandler_fatal_error_thread () at /lib64/libpython3.12.so.1.0
#5  0x00007f9ca44ffa6c in PyImport_AppendInittab () at /lib64/libpython3.12.so.1.0
#6  0x00005576df181020 in CAddonPythonInvoker::CAddonPythonInvoker(ILanguageInvocationHandler*) ()
#7  0x00005576dfc368b0 in CScriptInvocationManager::GetLanguageInvoker(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#8  0x00005576dfc36b7c in CScriptInvocationManager::ExecuteAsync(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<ADDON::IAddon> const&, std::vector<st
d::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool, int) ()
#9  0x00005576df7fdd93 in ADDON::CServiceAddonManager::Start(std::shared_ptr<ADDON::IAddon> const&) ()
#10 0x00005576df7fe2fb in ADDON::CServiceAddonManager::Start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#11 0x00005576df7f9707 in detail::CSubscription<ADDON::AddonEvent, ADDON::CServiceAddonManager>::HandleEvent(ADDON::AddonEvent const&) ()
#12 0x00005576df7bcb97 in CLambdaJob<CEventSource<ADDON::AddonEvent>::Publish<ADDON::AddonEvents::ReInstalled>(ADDON::AddonEvents::ReInstalled)::{lambda()#1}>::DoWork() ()
#13 0x00005576df4b7b09 in CJobWorker::Process() ()
#14 0x00005576df52c4cf in CThread::Action() ()
#15 0x00005576dfe529d6 in CThread::Create(bool)::{lambda(CThread*, std::promise<bool>)#1}::operator()(CThread*, std::promise<bool>) const [clone .isra.0] ()
#16 0x00005576df52c35f in std::thread::_State_impl<std::thread::_Invoker<std::tuple<CThread::Create(bool)::{lambda(CThread*, std::promise<bool>)#1}, CThread*, std::promise<bool> > > >::_M_run() ()
#17 0x00007f9ca14e31b3 in execute_native_thread_routine () at /lib64/libstdc++.so.6
#18 0x00007f9ca1716897 in start_thread () at /lib64/libc.so.6
#19 0x00007f9ca179d6bc in clone3 () at /lib64/libc.so.6

**Comment by Tinigriffy** [comment]
Hello,

Backporting commit 4bf9de87e700f0de56ef698a8d8d6eb7d4ff9050 to nexus branch fix the issue for me. I have create a new spec file for the rpmfusion package see [https://github.com/Tinigriffy/kodi](url).

Best regards,

**Comment by obaterspok** [comment]
That fixed it for me as well. Thanks @Tinigriffy

**Comment by joaopa00** [comment]
Why is this issue closed since the patch was not committed in the official Nexus branch?
Ubuntu 24.04 users meet this problem.

**Comment by garbear** [comment]
It looks like the issue is fixed in Omega? https://github.com/xbmc/xbmc/pull/22412

Nexus is out of support, Omega is currently supported.

**Comment by stsichler** [comment]
> It looks like the issue is fixed in Omega? #22412
> 
> Nexus is out of support, Omega is currently supported.

But **Nexus** is currently shipped on Ubuntu 24.04 (along with Python 3.12), not Omega!

**Comment by garbear** [comment]
How is Nexus shipped on Ubuntu 24.04? Our PPA maintainer stepped down, so without another volunteer the apt repo is unsupported and isn't going to be updated. The two remaining options are flatpak and compile from source, both of which should be on Omega.

**Comment by stsichler** [comment]
> How is Nexus shipped on Ubuntu 24.04? Our PPA maintainer stepped down, so without another volunteer the apt repo is unsupported and isn't going to be updated. The two remaining options are flatpak and compile from source, both of which should be on Omega.

Its in the regular _Universe_ repository of Ubuntu, see http://archive.ubuntu.com/ubuntu/pool/universe/k/kodi/

**Comment by wsnipex** [comment]
That won't help for existing Ubuntu series. 24.04 has kodi 20 and it's very unlikely it would receive a major version upgrade.

**Comment by wsnipex** [comment]
See https://bugs.launchpad.net/ubuntu/+source/kodi/+bug/2063358

**Comment by garbear** [comment]
I think the issue makes it pretty clear. Omega was released 4 months ago. Since then we've focused on v22 Piers, with a promise to keep Omega supported. The path forward is to get Omega in the repo so that we can offer help for supported code.

**Comment by basilgello** [comment]
@garbear Yes 21 and 22 are on my list, just need to sort the issues with primary job that drive me loaded since January.

**Comment by basilgello** [comment]
And BTW, 20.5 in sidband trixie have that patch, so it is Ubuntu specific b7g for now.

**Comment by basilgello** [comment]
Please note that 21 has to go to sid with ffmpeg 7 PR that is AFAIK not merged into master. Bit I have to take it anyway, because alternative is no Kodi in Debian at all.

**Comment by basilgello** [comment]
And FWIW, I havent seen any mentions either on Github nor in Kodi forum nor in Debian mailing lists from you @garbear So who do you think Debian maintainer is? ;)
