### ISSUE TITLE
Omega with -DENABLE_INTERNAL_CEC=ON results in missing shared object

### ISSUE THREAD

**Issue by graysky2** [xbmc/xbmc#24065]
### Describe the bug
Here is a clear and concise description of what the problem is:

I built xbmc/master with `-DENABLE_INTERNAL_CEC=ON` but the resulting kodi that is built is missing the shared object. 
```
% kodi    
/usr/lib/kodi/kodi.bin: error while loading shared libraries: libcec.so: cannot open shared object file: No such file or directory
```
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The build should provide the needed shared object.

## Actual Behavior

The share object is not packaged.

### To Reproduce

1. Build from xbmc/master with the above cmake option
Complete [build log](https://gist.github.com/graysky2/20666c48d38bfd2b42d15dea0a9742e5).

### Debuglog

The debuglog can be found here:

Not relevant to bug report.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux
 - Kodi version: build from 757bd86acc6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Do not use that for actual linux usage. The only reason it even builds for linux is purely for CI. it is not intended to be used, as we do nothing to handle install of a shared library (rpaths and all the shit involved with installing)

**Comment by graysky2** [comment]
OK, thanks.  Closing.
