### ISSUE TITLE
Dolby Vision doesn't work on Sony A95L

### ISSUE THREAD

**Issue by dbarkar** [xbmc/xbmc#24078]
### Describe the bug
DV videos are rendered incorrectly, some with balck screen, some with funny colors.
I tried samples from demolandia.net without HDR fallback.
mediainfo: https://paste.kodi.tv/uxupadidil.
This might affect other Sony or Android TVs.

**Looks like it's because Kodi chose the wrong codec -  "c2.mtk.dvav.se.decoder" instead of "c2.mtk.dvhe.stn.decoder".**

## Expected Behavior
Video must be played in Dolby Vision mode.

## Actual Behavior
Video is not rendered properly.

## Possible Fix
Improve logic for selecting the right Android codec.

### To Reproduce
1.  Download DV video
2. Play it with Kodi
3. See the result

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/mudebiwugo.kodi

## Additional context or screenshots (if appropriate)
Initial discussion: https://forum.kodi.tv/showthread.php?tid=374979

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: BRAVIA_AE1_EU-user 12 STT2.230327.001 604070 (Android TV 12)
 - Kodi version: kodi-20231105-76e06459-master

**Comment by joseluismarti** [comment]
If possible try [this build](https://jenkins.kodi.tv/job/android-arm-docker/4250/artifact/kodi-20231115-7e8f0673-PR23577-armeabi-v7a.apk), it should fine tune the codec selection depending on the profile.

**Comment by dbarkar** [comment]
Thanks! 
It works for profile 5.
Profile 8 is still not working.

**Comment by joseluismarti** [comment]
Good news!
This build does not assign the profile value in the case of profiles 7 and 8, try this [previous build](https://jenkins.kodi.tv/job/android-arm-docker/4247/artifact/kodi-20231115-a162b4bd-PR23577-armeabi-v7a.apk) which assigns the profile in all cases.

**Comment by dbarkar** [comment]
> Good news! This build does not assign the profile value in the case of profiles 7 and 8, try this [previous build](https://jenkins.kodi.tv/job/android-arm-docker/4247/artifact/kodi-20231115-a162b4bd-PR23577-armeabi-v7a.apk) which assigns the profile in all cases.

This one works :)

**Comment by DanoUF79** [comment]
> Good news! This build does not assign the profile value in the case of profiles 7 and 8, try this [previous build](https://jenkins.kodi.tv/job/android-arm-docker/4247/artifact/kodi-20231115-a162b4bd-PR23577-armeabi-v7a.apk) which assigns the profile in all cases.

This link is no longer valid.

**Comment by joseluismarti** [comment]
Ok, new [link](https://drive.google.com/file/d/1rXzXNM-igVUKaPlguzxd3WSb2-tWaQDM/view?usp=sharing)  to the file

**Comment by fuyar** [comment]
Thanks for the fix/build @joseluismarti !

Here's the report on a A95L
`Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible`
works

`Dolby Vision, Version 1.0, dvhe.07.06, BL+EL+RPU, Blu-ray compatible / SMPTE ST 2086, HDR10 compatible`
is not working properly: sluggish with a lot of frame drop. Also it does not trigger DV even with DV Compatibility mode enabled.

It works flawlessly on Plex (exoplayer) fullbacking on HDR10.

**Comment by joseluismarti** [comment]
Great that profile 8 works.

Sorry, profile 7 was not the target to fix with this build, you can try 21.0 Beta 1 which includes the option to convert these media types to allow playback.

**Comment by fuyar** [comment]
I thought this build was based on 21.0 already. Am I wrong ?

I have the option to convert within Kodi / Video settings.

**Comment by joseluismarti** [comment]
> I thought this build was based on 21.0 already. Am I wrong ?

True, but this initial test build makes the adjustment for all profiles. For profile 7 it seems to me more accurate to check the behaviour with the official version.

**Comment by fuyar** [comment]
That's the issue :( I was on Kodi 21 official beta before (installed through Play Store) and nothing was working.

I saw some errors in Kodi logs when building the Codec list. I'll try to check deeper.

**Comment by dbarkar** [comment]
https://github.com/xbmc/xbmc/pull/23577 is a partial fix only.
DV Profile 7 is still not working, videos are played using software codec - the codepath was not affected.
@thexai please reopen this issue.

**Comment by thexai** [comment]
Only have Shield for test and in Shield works all DV profiles with or without https://github.com/xbmc/xbmc/pull/23577, really I can not help with this.

**Comment by quietvoid** [comment]
For profile 7 other than requiring the compatibility mode, there's a refactor required to fallback to a regular hw accelerated HEVC codec if Dolby Vision is not supported for the profile.

A probably easier workaround is to fix the profile when compatibility mode is enabled.

**Comment by thexai** [comment]
> DV Profile 7 is still not working

Your device supports it?

Have you enabled "Dolby Vision compatibility mode" in Kodi GUI settings / Player / Processing ?

> If enabled, Dolby Vision profile 7 will be converted to profile 8.1, which is more commonly supported by devices. Enable if your device supports Dolby Vision, but has issues with some videos.

**Comment by quietvoid** [comment]
@thexai there's still a missing patch to set profile 8 when using compatibility mode, but it has to be discussed if we would prefer refactoring to fallback or not

Currently enabling compatibility mode leaves the profile at 0 and doesn't fix this issue.

I guess I'll try to propose a fix later today.

**Comment by dbarkar** [comment]
> Your device supports it?

Do you know where I can find a solid example of Profile 7 video? I'm happy to test it.
I'm pretty sure that I had a UHD DV Profile 7 rip working in internal video player in DV mode.

> Have you enabled "Dolby Vision compatibility mode" in Kodi GUI settings / Player / Processing ?
Yes, as @quietvoid explained earlier, it didn't help.

**Comment by the-black-eagle** [comment]
> Do you know where I can find a solid example of Profile 7 video? I'm happy to test it. I'm pretty sure that I had a UHD DV Profile 7 rip working in internal video player in DV mode.

There is a profile 7 video here (its linked to via https://kodi.wiki/view/Samples) -> https://mega.nz/file/DGJU1BzL#4jtSK9Kvx2N6WuNdnQXyOi4NFEqLIymLrmSK5R8WilY

**Comment by dbarkar** [comment]
Looks like my device doesn't support Profile 7, sorry for the noise...

![image](https://github.com/xbmc/xbmc/assets/1224655/29c1acde-0876-404d-b0a8-5b5c61f52c80)

**Comment by fuyar** [comment]
A95L never decoded DV Profile 7.
What's missing currently is the compatibility mode fullbacking to 8.1 not working on this TV

**Comment by quietvoid** [comment]
Build available for #24143: https://jenkins.kodi.tv/job/android-arm-docker/4404/artifact/kodi-20231125-1f480368-PR24143-armeabi-v7a.apk
It should allow Dolby Vision playback of profile 7 files, when compatibility mode is enabled.
