### ISSUE TITLE
[WebOS] Not a bug but Dolby Atmos Playback should be on by default.

### ISSUE THREAD

**Issue by Battler624** [xbmc/xbmc#24077]
On the LG C2, Dolby Atmos is supported but requires enabling from the system menu, I just believe it should be a default option.

Also, weird bug but the Dolby Vision Logo doesn't show up (on the top right) if dolby atmos is enabled but it is indeed working if i go to the settings (of the TV) and check.

**Comment by lrusak** [comment]
We don't have edid parsing on webOS (Wayland) so we can't know what is supported (afaik).
