### ISSUE TITLE
Property ListItem.PercentPlayed shows 0 for in progress tv shows in kodi omega

### ISSUE THREAD

**Issue by beatmasterRS** [xbmc/xbmc#24074]
### Describe the bug
Here is a clear and concise description of what the problem is:

The listitem $INFO[ListItem.PercentPlayed] shows always 0, no matter what the in progress tv show watched percentage is.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should show the real % value of in progress tv shows.

## Actual Behavior

It shows 0.

### To Reproduce

1. Use kodi omega
2. Use Arctic Zephyr Reloaded
3. In Skin Settings > Furniture, enable the following: 
4. - indicators > reloaded
5. - prefer percentage
6. - go to tv show library and look at in progress tv shows.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![screenshot01445](https://github.com/xbmc/xbmc/assets/3855273/4f8e8a39-ac5d-4dbc-aed1-c16be20966a4)
![screenshot01444](https://github.com/xbmc/xbmc/assets/3855273/a5b03b58-03d3-4213-a2b3-9cfbfaf7e462)
![screenshot01442](https://github.com/xbmc/xbmc/assets/3855273/8480b1d9-04f9-47cf-a91b-1bccc0225e5e)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi v21 (Omega) Beta 1 pre-release build

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Does this work as expected with Nexus?

**Comment by ksooo** [comment]
Ja a quick look at the code. This list item only works for videos (movies and episodes) as I see it. So, e we are facing more a missing feature than a bug, I’d say. 

Even the documentation is clear on this: 
///     @return The percentage value [0-100] of how far the selected video has been played.

**Comment by beatmasterRS** [comment]
Sorry, i was totally wrong. The same behaviour in nexus. Sorry

**Comment by Nanomani** [comment]
@beatmasterRS 
If I m right for TvShows this must be : 
`$INFO[ListItem.Property(WatchedEpisodePercent),,%]`

**Comment by beatmasterRS** [comment]
@Nanomani thank you so much :)
