### ISSUE TITLE
HDR not supported on Xbox UWP

### ISSUE THREAD

**Issue by CasperMcFadden95** [xbmc/xbmc#24070]
### Describe the bug
It was previously not possible to enable HDR on Xbox UWP and it was removed in https://github.com/xbmc/xbmc/pull/19879 

@worleydl discovered how to enable it on an Xbox
https://github.com/worleydl/dolphin-color/commits/hdr-xbox
https://github.com/worleydl/pcsx2/commits/hdr

## Expected Behavior
HDR video should play in HDR if the display supports HDR

## Actual Behavior
HDR video is tone mapped to SDR

### To Reproduce

1. Play any HDR video

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name: Xbox Series X
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Done some preliminary tests on Xbox Series S and effectively restoring same HDR toggle code works now and is able to toggle HDR from GUI (F11 key) and works properly with HDR10 output.

Seems Microsoft has changed something in UWP Windows API and now HDR is supported using `RequestSetCurrentDisplayModeAsync`.

Video playback needs some more work due refresh rate/video modes issues but seems feasible.

Thank you for heads-up!

**Comment by CasperMcFadden95** [comment]
Awesome! Thank you so much! This will make it the ultimate media center! Maybe even Dolby Vision is possible with [DisplayWireFormatHdrMetadata.DolbyVisionLowLatency](https://learn.microsoft.com/en-us/uwp/api/windows.devices.display.core.displaywireformathdrmetadata?view=winrt-22621#fields )

**Comment by CasperMcFadden95** [comment]
Thanks @thexai for your hard work! Just tested a nightly from https://mirrors.kodi.tv/nightlies/windows/uwp64/master/ and the HDR is amazing!

**Comment by craigcarnell** [comment]
Would love to see DV support as well!
