### ISSUE TITLE
Android 11+ launching broken with downloaded files (executebuiltin StartAndroidActivity should auto use fileprovider api) 

### ISSUE THREAD

**Issue by djay** [xbmc/xbmc#24075]
### Describe the bug

When launching an external applications on android via ```executebuiltin('StartAndroidActivity(...``` sometimes you want to pass a file url to something downloaded or owned by Kodi. In almost all cases the other application is not able to read those files due to scoped storage in new android versions.

Examples addons are
 - One example is apps that install apks. For example the upgrade kodi addon [script.kodi.android.update/](https://kodi.tv/addons/matrix/script.kodi.android.update/). 
 - launching emulators with the path to a rom 
 - external video player with the file url of a downloaded  video file.
 - any other time you want to launch an apk on android with a downloaded file

## Expected Behavior

An existing addon doesn't have to change it's code but kodi automatically gives permission so launching now works.

1. StartAndroidActivity could automatically convert any file url arguments to a content url using the FileProvider android api
2. launch the apk with the content url instead. 
3. The external apk should know how to deal with content urls so then all should work as expected. 
4. The access to the file is temporary but that should be fine for most external viewer type use cases. 

This solution has the added benefit that it will work for files inside kodis private profile so there is no need mess around with downloading files to special folders like previous android versions.

But if that is too magic, then perhaps at least kodi plugins could have an additional api to use the FileProvider api themselves? This is something currently not possible since it requires changes to android manifest etc?

## Actual Behavior

The apk will be launched but won't be able to access the file in the file url so will 
- either ignore it and launch with no content
-  or exit with an error saying it can't read the file.

The current workaround is
- get the kodi addon to store the files in /SDCard or similar. outside it's private storage
- after downloading via the addon exit kodi
- install a file manager (not all work. MX+ does for example)
- launch the external app manually
- the app should have a select file function. This will launch the file manager.
- use the file manager to browse and select the downloaded file
- this then gives the app temp permission to access this file. (seems to last a couple of weeks)
- note this still doesn't let you launch the app from kodi. this will still fail. You will always need to launch it manually.

## Possible fix

StartAndroidActivity should convert a file:// url into a content: url using [FileProvider api](https://developer.android.com/reference/androidx/core/content/FileProvider), give the other app permissions to read that file and pass the content uri to StartAndroidActivity instead.

> FileProvider is a special subclass of [ContentProvider](https://developer.android.com/reference/android/content/ContentProvider.html) that facilitates secure sharing of files associated with an app by creating a content://[Uri](https://developer.android.com/reference/android/net/Uri.html) for a file instead of a file:///[Uri](https://developer.android.com/reference/android/net/Uri.html).
> 
> A content URI allows you to grant read and write access using temporary access permissions. When you create an [Intent](https://developer.android.com/reference/android/content/Intent.html) containing a content URI, in order to send the content URI to a client app, you can also call [Intent.setFlags()](https://developer.android.com/reference/android/content/Intent.html#setFlags(int)) to add permissions. These permissions are available to the client app for as long as the stack for a receiving [Activity](https://developer.android.com/reference/android/app/Activity.html) is active. For an [Intent](https://developer.android.com/reference/android/content/Intent.html) going to a [Service](https://developer.android.com/reference/android/app/Service.html), the permissions are available as long as the [Service](https://developer.android.com/reference/android/app/Service.html) is running.
> 

I'm not sure if there needs to be a way to control if the permission given is only read or read/write?
Read only should cover most cases?

Also I might be reading the api incorrectly but it seems kodi would need to set which paths can be shared on startup which means addons would be limited to which paths they could share? 

### To Reproduce

[script.kodi.android.update/](https://kodi.tv/addons/matrix/script.kodi.android.update/) is a good example of a addon that no longer works because of the Android scoping change but this applies to any that starts an app and passes in files in the kodi scope.

1.  On Android > 11, install https://kodi.tv/addons/matrix/script.kodi.android.update/
5. Try installing an apk
6. Note nothing happens

### Debuglog

The debuglog can be found here:

```
2023-11-08 22:22:03.008 T:27744   debug <general>: CPythonInvoker(52, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.android.update/default.py): script successfully run
2023-11-08 22:22:03.009 T:27744   debug <general>: onExecutionDone(52, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.android.update/default.py)
2023-11-08 22:22:03.013 T:20921   debug <general>: StartActivity: package: com.android.documentsui
2023-11-08 22:22:03.014 T:20921   debug <general>: StartActivity: intent: 
2023-11-08 22:22:03.014 T:20921   debug <general>: StartActivity: dataType: 
2023-11-08 22:22:03.014 T:20921   debug <general>: StartActivity: dataURI: content:///storage/emulated/0/download/kodi-20.2-Nexus-armeabi-v7a.apk
2023-11-08 22:22:03.014 T:20921   debug <general>: StartActivity: flags: 
2023-11-08 22:22:03.014 T:20921   debug <general>: StartActivity: extras: 
2023-11-08 22:22:03.014 T:20921   debug <general>: StartActivity: action: 
2023-11-08 22:22:03.014 T:20921   debug <general>: StartActivity: category: 
2023-11-08 22:22:03.014 T:20921   debug <general>: StartActivity: className: 
2023-11-08 22:22:03.045 T:27744   debug <general>: .
2023-11-08 22:22:03.204 T:27744   debug <general>: Python interpreter stopped
2023-11-08 22:22:03.204 T:27744   debug <general>: Thread LanguageInvoker -1151073856 terminating
2023-11-08 22:22:03.317 T:20921   debug <general>: ------ Window Deinit (DialogConfirm.xml) ------
2023-11-08 22:22:10.884 T:27743   debug <general>: Thread JobWorker -1486356032 terminating (autodelete)
2023-11-08 22:22:10.884 T:27745   debug <general>: Thread JobWorker -1491619392 terminating (autodelete)
```

Note that the content url here is not correct. It needs to be done by FileProvider

### Screenshots 
NA

## Additional context or screenshots (if appropriate)
Maybe related

https://github.com/xbmc/xbmc/pull/15577

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 12 CCWGT
 - Kodi version: 21.0 beta1

**Comment by djay** [comment]
I don't know if this should be an additional api available or just detect when a file url is being passed in to the existing StartAndroidActivity and just call the FileProvider api automatically. The later would require no addon changes so seems preferable but is there downside?

**Comment by TwilightMercy** [comment]
Issues with Android 11+?

**Comment by djay** [comment]
@TwilightMercy yes. the new security in 11+ requires kodi to explicitly share the file or directory with another app for that app to be able to access it. So it makes perfect sense that if StartAndroidActivity is used in the kodi api along with a file path or uri, that kodi does whats needed first to make that file able to be read by that other app.

**Comment by TwilightMercy** [comment]
> @TwilightMercy yes. the new security in 11+ requires kodi to explicitly share the file or directory with another app for that app to be able to access it. So it makes perfect sense that if StartAndroidActivity is used in the kodi api along with a file path or uri, that kodi does whats needed first to make that file able to be read by that other app.

So what is the change needed here?
For example "Downloader" app from Google Play

**Comment by djay** [comment]
@TwilightMercy change the kodi code that executes StartAndroidActivity so before it actually starts the external apk, it will do a call to the android fileprovider api - https://developer.android.com/reference/androidx/core/content/FileProvider
That will convert the file uri into a new one which can then be passed to the call to the external apk. And in doing so the external apk, like Downloader, or anything else, will now be able to access that file.

**Comment by TwilightMercy** [comment]
> @TwilightMercy change the kodi code that executes StartAndroidActivity so before it actually starts the external apk, it will do a call to the android fileprovider api - https://developer.android.com/reference/androidx/core/content/FileProvider That will convert the file uri into a new one which can then be passed to the call to the external apk. And in doing so the external apk, like Downloader, or anything else, will now be able to access that file.

Sorry for being a noob, I'm not that expert in that area. My current code is:

```
downloader_package_id = 'com.esaba.downloader'

apk_downloaded_path = '/storage/emulated/0/Download/Downloader/some_apk.apk'

xbmc.executebuiltin(f'StartAndroidActivity({downloader_package_id},,,"content://{apk_downloaded_path}")')
```

The APK file has already downloaded successfully to the destination path, but after opening Downloaded from Kodi - the file doesn't appear in Downloader "Files" tab. (although the file exists in the correct path)

Can you give me example from here?

**Comment by djay** [comment]
@TwilightMercy ah I see the confusion. This ticket is about a change to the core of kodi itself. 
This change is needed because I can't see anyway to work around this using python plugin code as you are trying to do.
My suggested change, if it was implemented in core kodi, would allow your code to work unaltered.
So what it needs is a C coder to make the change in kodi and submit a PR. Any ideas?

**Comment by djay** [comment]
@TwilightMercy sorry there is one work around. If the external apk allows you to use a file browser app to select a file then you can use that browse and give you permission. But that isn't seamless.
ie
1. kodi plugin downloads a file
2. inside the external apk that you want to use this file, look for a function to browse for file
3. browse and select file
4. external app should now have access to that file (the file browser gave the permission needed).

Chromecast doesn't come with a file browser app built in but you can install them.

**Comment by djay** [comment]
do you think this is a reasonable approach @notspiff @chrisism ?

**Comment by TwilightMercy** [comment]
> @TwilightMercy sorry there is one work around. If the external apk allows you to use a file browser app to select a file then you can use that browse and give you permission. But that isn't seamless.
> 
> ie
> 
> 1. kodi plugin downloads a file
> 
> 2. inside the external apk that you want to use this file, look for a function to browse for file
> 
> 3. browse and select file
> 
> 4. external app should now have access to that file (the file browser gave the permission needed).
> 
> 
> 
> Chromecast doesn't come with a file browser app built in but you can install them. 

I tried the same code I sent other File explorers apps such as: X-plore / File Commander. 
And it works fine: the app is opened and I see the file in "Download" directory - and I can install it. 

Through "Downloader" app - the downloaded file is in the correct path but not shown in the app itself. (Permissions)

So you're saying there is no workaround through python for my current code? Or only for file explorers apps?

**Comment by djay** [comment]
> So you're saying there is no workaround through python for my current code?

Correct. Kodi needs to be changed so it gives permission to the other app.

**Comment by TwilightMercy** [comment]
> > So you're saying there is no workaround through python for my current code?
> 
> 
> 
> Correct. Kodi needs to be changed so it gives permission to the other app.

How is it working for file explorers apps?
There is no python code to do android API call and give permissions to specific app?

**Comment by chrisism** [comment]
I think it might be good to find something similar in other apps and how they solve it. Compare it with that. 
For the python code it should be only StartAndroidActivity that does all the work for you. I feel something for letting the other app sort out granted access for certain locations etc. So you first make sure that the specific app has access and afterwards the kodi libray can call it without issues.

**Comment by djay** [comment]
> So you first make sure that the specific app has access and afterwards the kodi libray can call it without issues.
@chrisism it's not how Android security works these days. You can no longer have a shared folder that both apps can access. Instead it will work more like this
1. Kodi addon downloads a file to kodi addon data folder
2. Kodi witll use the FileProvider api to give temporary permission for another app to use it's private file
3. StartAndroidActivity will launch that other app with the special content uri to the shared file
4. Afterwards the permissions goes away

> How is it working for file explorers apps?

I think why this is confusing is that certain apps have a special permission to access files on the SDCard and more locations. Include file browser apps and kodi. But the vast majority of apps don't have that permission and if they aren't built to request that permission you can't give them that permission so to work with alll apps, the above fix is what is needed.

**Comment by TwilightMercy** [comment]
> > So you first make sure that the specific app has access and afterwards the kodi libray can call it without issues.
> 
> @chrisism it's not how Android security works these days. You can no longer have a shared folder that both apps can access. Instead it will work more like this
> 
> 1. Kodi addon downloads a file to kodi addon data folder
> 
> 2. Kodi witll use the FileProvider api to give temporary permission for another app to use it's private file
> 
> 3. StartAndroidActivity will launch that other app with the special content uri to the shared file
> 
> 4. Afterwards the permissions goes away
> 
> 
> 
> > How is it working for file explorers apps?
> 
> 
> 
> I think why this is confusing is that certain apps have a special permission to access files on the SDCard and more locations. Include file browser apps and kodi. But the vast majority of apps don't have that permission and if they aren't built to request that permission you can't give them that permission so to work with alll apps, the above fix is what is needed.
> 
> 


"2. Kodi witll use the FileProvider api to give temporary permission for another app to use it's private file"

This is an internal change should be in Kodi right? No way to manually do it in addon's python code?

**Comment by chrisism** [comment]
Clear.
But how does it work for something like an emulator where it needs access to a certain directory (like /downloads/roms for example)? That is a directory that both Kodi and the Emulator should be able to access. (to be honest, I havent checked up on the new security API changes for Android, so I dont know the details) 

> "2. Kodi witll use the FileProvider api to give temporary permission for another app to use it's private file"
> 
> This is an internal change should be in Kodi right? No way to manually do it in addon's python code?

Definitly through Kodi with the Android API. The python library does not have any access to the Android system operations as far as I know. So the only way to interact with Android is through Kodi.
The only question is if you want to put all these steps behind the StartAndroidActivity method, or you want an alternative method etc. In my opinion from a python point of view, you simply want to start activity X and let the backend deal with all the access, privileges etc.

**Comment by djay** [comment]
> Clear. But how does it work for something like an emulator where it needs access to a certain directory (like /downloads/roms for example)? That is a directory that both Kodi and the Emulator should be able to access. (to be honest, I havent checked up on the new security API changes for Android, so I dont know the details)
 
I'm not 100% sure but what I suspect is that this won't work. 
For a start lots of emulators can't access a folder like /downloads/roms by themselves. PPSSPP can't for example. It can only do so by using a filebrowsing app to temporarily give it permission to a file or folder. On my chromecast this is annoying as that permission gets revoked regularly and I have to keep launching the file browser from within PPSSPP and select the rom.
RetroArch is an example of an emulator that does have this additional permission to access SDCard folders without some external filebrowser. So is kodi. I don't know why more emulators don't include this permission in their manifest. 
see https://developer.android.com/training/data-storage/manage-all-files
Perhaps one reason is that you an app can't be installed with this permission enabled. You have to give instructions to the user to go into their app settings and enable it themselves. Which is not a nice UX.

So in summary, most emulators/apps can't access all files like they used to, so they way forward is for kodi to download files into it's internal storage and give temporary permission to an external android app access that particular file
- I'm not sure it would work for folder but in theory I think it should
- I'm not sure it would work if the files were somewhere like /downloads/roms becuase I think this temporary permission thing only works for kodi's private storage. or at least the paths that it can share have to be predeclared. I'm not sure. I'm not an android developer.

> 
> > "2. Kodi witll use the FileProvider api to give temporary permission for another app to use it's private file"
> > This is an internal change should be in Kodi right? No way to manually do it in addon's python code?
> 
> Definitly through Kodi with the Android API. The python library does not have any access to the Android system operations as far as I know. So the only way to interact with Android is through Kodi. The only question is if you want to put all these steps behind the StartAndroidActivity method, or you want an alternative method etc. In my opinion from a python point of view, you simply want to start activity X and let the backend deal with all the access, privileges etc.

my opinion also.

**Comment by djay** [comment]
@chrisism @TwilightMercy one work around I thought of is if there was some kind of proxy android app that was able to start a 3rd app specified in the intent, and also give it permissions to the files. It would need the kind of file manager type permissions kodi and file managers have. Then kodi wouldn't need to change. But so far my searches haven't found an apk that does this....

**Comment by djay** [comment]
@joseluismarti wondering how you would solve a problem like this and if it's considered a problem for others?

**Comment by joseluismarti** [comment]
To share a local file with another app, you should use a `FileProvider`, but this has the disadvantage that the permissions remain in effect while the stack of the receiving Activity is active. When the stack finishes, the permissions are automatically removed.

A `ContentProvider` could be used to access any locally stored file, but I think this could be a security risk.

At the moment if the android app that starts from Kodi has the "Files and multimedia content" permission it will have access to `/storage/emulated/0/` folder and could open the file.

The "Kodi Android Installer" addon does not work because the `com.android.documentsui` app is not available on Android 12 and higher devices and the URI to the file should be directly `/storage/emulated/0/download/kodi-20.2-Nexus-armeabi-v7a.apk` instead of starting with `content://...`.

**Comment by djay** [comment]
> To share a local file with another app, you should use a FileProvider, but this has the disadvantage that the permissions remain in effect while the stack of the receiving Activity is active. When the stack finishes, the permissions are automatically removed.
@joseluismarti Temporary access is fine. This is to fix that you currently can't launch any android app with a file url. If its a video player, or emulator or whatever, it most cases kodi is the hub that is launching these so they only need access when kodi does executebuiltin. Kodi Android Installer is just an example of such use of excutebuiltin. Perhaps Kodi Android installer was a bad example if it can't work with content:// urls but I presume other apps can? or am I wrong about that?

**Comment by djay** [comment]
@joseluismarti what do you think about this as a feature for the next release?

**Comment by djay** [comment]
> At the moment if the android app that starts from Kodi has the "Files and multimedia content" permission it will have access to /storage/emulated/0/ folder and could open the file.

@joseluismarti the problem is that most apps I've come across don't seem to have this. I think this kind of permission is restricted and harder to get so apps that have their own internal file management like kodi or retroarch seem to have it but lots of other emulators for example don't seem to have this.

**Comment by joseluismarti** [comment]
Try this [test build](https://drive.google.com/file/d/1icmyY3_nH0pmXUgTBilN0U45ucSutVWi/view?usp=sharing) that uses FileProvider to share a file from external storage with another android app.

Tested that works correctly and plays a video with an external player with "Play using..." from the context menu. 

Example: 
Requested file: `/storage/emulated/0/test/videos/sample.mp4`
Generated URI: `content://org.xbmc.kodi.fileprovider/external/test/videos/sample.mp4`

As this is a local build you must uninstall Kodi to install it, make a backup of your profile first!

**Comment by djay** [comment]
@joseluismarti thats awesome. I haven't worked out how to test it yet. it doesn't like being installed onto my chromecast due to the changed certificate. I'll keep trying.

**Comment by joseluismarti** [comment]
@djay try this other [build](https://jenkins.kodi.tv/job/android-arm-docker/8876/artifact/kodi-20241205-6385886a-PR26051-armeabi-v7a.apk), now you won't have a problem with the signature

**Comment by joseluismarti** [comment]
I've added a proposal https://github.com/xbmc/xbmc/pull/26051 to use FileProvider in this case.

Try [this build](https://drive.google.com/file/d/1JyJHaEYfqoTT6txezBxk1lEuKzWfGbyN/view?usp=sharing), you can install it and it won't affect your profile. Any feedback is welcome.

**Comment by djay** [comment]
@joseluismarti been trying with some emulators to get it to produce a launch that should work but still no luck but it might be my fault. One thing I noticed in your proposal is that it won't work with removable storage. What about extended volumes into removable storage? what error would I see if the downloaded file is in the wrong kind of locaiton?

**Comment by joseluismarti** [comment]
>been trying with some emulators to get it to produce a launch that should work but still no luck but it might be my fault.

Example call to open an external player and play a video from storage:

```
xbmc.executebuiltin('StartAndroidActivity("com.brouken.player","android.intent.action.VIEW", "video/*","/storage/emulated/0/test/videos/sample.mp4")')
```

Can also be used with content:// 

```
xbmc.executebuiltin('StartAndroidActivity("com.brouken.player","android.intent.action.VIEW", "video/*","content:///storage/emulated/0/test/videos/sample.mp4")')
```

>One thing I noticed in your proposal is that it won't work with removable storage. What about extended volumes into removable storage?

It's limited by the OS, you cannot create a content URI using FileProvider from a file on removable storage.

>what error would I see if the downloaded file is in the wrong kind of locaiton?

Kodi will not show an error because it launches a new app and gives up control, we will only be able to see in the log if there has been an exception in the call.

**Comment by djay** [comment]
@joseluismarti  I haven't been able to get it to work yet. Will it work if the file is passed as an "extras"? e.g.

{'package': 'org.myplayer', 'intent': 'android.intent.action.VIEW', 'dataType': '', 'dataURI': '', 'flags': '270532608', 'extras': [{'key': 'Uri', 'value': 'file:///storage/61D3-1611/myfile.zip', 'type': 'string'}], 'action': '', 'category': '', 'className': 'org.myplayer.SplashActivity', 'extras_json': '[{"key": "Uri", "value": "file:///storage/61D3-1611/myfile.zip", "type": "string"}]

**Comment by joseluismarti** [comment]
You are trying to use FileProvider from a file stored on external storage (`/storage/61D3-1611`), this is not possible as it's limited by the OS. It only works with files from the primary storage volume (`/storage/emulated/0`).

There is no need to pass anything as "extras", it should work as is, another example that works:

```
xbmc.executebuiltin('StartAndroidActivity("org.videolan.vlc","android.intent.action.VIEW", "video/*","/storage/emulated/0/sample.mp4")')
```

If you want, tell me the app you want to start from Kodi and a file to open and I'll try it myself.

**Comment by djay** [comment]
I tried a different download location and it didn't make a different. 
The extras is just how the external app expects it I believe.  Or at least how the Kodi plugin is setup to execute. This is with game emulators like ppsspp using IAGL plugin. 
Will it work to convert urls in extras as well?

**Comment by joseluismarti** [comment]
I've tried to start the PPSSPP emulator from kodi by passing the path to the game iso and it works perfectly using FileProvider.

This is the call from a script:
```
xbmc.executebuiltin('StartAndroidActivity("org.ppsspp.ppsspp","android.intent.action.VIEW", "*/*","/storage/emulated/0/game.iso")')
```

**Comment by djay** [comment]
@joseluismarti I tried using IAGL and couldn't get it to launch at all.

```
IAGL:  Launching game with StartAndroidActivity:
                                                   {'package': 'org.ppsspp.ppsspp', 'intent': 'android.intent.action.VIEW', 'dataType': '*/*', 'dataURI': '/storage/emulated/0/game.iso', 'flags': '', 'extras': '', 'action': '', 'category': '', 'className': 'org.ppsspp.ppsspp.PpssppActivity', 'extras_json': None}
```

but it could be the volume it's on like you said.

**Comment by joseluismarti** [comment]
I have tried directly with a script and it works.

For testing purposes create a file e.g. ‘launcher.py’ with the following content:
```python
xbmc.executebuiltin('StartAndroidActivity("org.ppsspp.ppsspp","android.intent.action.VIEW", "*/*","/storage/emulated/0/game.iso","","","","","org.ppsspp.ppsspp.PpssppActivity")')
```

Copy the file to a local folder on the device and launch it from Kodi directly with the File Manager, the app should start.

Another thing, the call only accepts the first 8 params, if there are more, they are discarded.

**Comment by djay** [comment]
@joseluismarti some further testing and I got it to work with IAGL. The mistake above is extras needs to be '[]'. And as you said, the storage needs to be on /storage/emulated/0/.

If there is an emulator that requires a file to passed in a shortcut or extras, is there alternative way to use the fileprovider api?

**Comment by djay** [comment]
@joseluismarti are you sure that fileprovider doesn't work with SDCard/external storage. I've looked for the documentation that states this and I can't find it. In addition I've been using file managers like Mix with emulators to get permission to use files on that same external storage partition in the past and it worked fine. My understanding is that the filemanagers are using the same FileProvider api to do this.

https://stackoverflow.com/questions/32333094/android-fileprovider-for-ext-sdcard
https://stackoverflow.com/questions/37074872/android-fileprovider-on-custom-external-storage-folder

**Comment by djay** [comment]
@joseluismarti one example of a emulator that doesn't accept a dataUri seems to be RetroArch
- https://stackoverflow.com/questions/71984199/android-retroarch-load-rom-from-intent

RetroArch is a tricky one because you need to pass a core param and I don't think it would like it changed using the file provider but I'm in the process of testing it so will let you know.

Another one seems to be duckstation
- https://pegasus-frontend.org/tools/metagen-android/

**Comment by djay** [comment]
@joseluismarti should I create a new ticket for including all of the /storage in the fileprovider functionality, as I'm pretty sure you can and it would be shame to exclude some use cases?

**Comment by joseluismarti** [comment]
@djay added a new [PR ](https://github.com/xbmc/xbmc/pull/26260) for this, you can test the [Jenkins build](https://jenkins.kodi.tv/job/BuildMulti-PR/32701/) if works properly on your device

**Comment by djay** [comment]
You are awesome. Thanks so much doing these PRs. I hope it proves to be useful for others too

**Comment by djay** [comment]
@joseluismarti confirmed it works for my extended drive

**Comment by TwilightMercy** [comment]
> @djay added a new [PR ](https://github.com/xbmc/xbmc/pull/26260) for this, you can test the [Jenkins build](https://jenkins.kodi.tv/job/BuildMulti-PR/32701/) if works properly on your device

Will the changes be in next Kodi 21.x update, or only Kodi 22?

**Comment by joseluismarti** [comment]
Only in Kodi 22
