### ISSUE TITLE
Kodi 21 Omega crashed when viewing pictures from external hard drive

### ISSUE THREAD

**Issue by fraz14** [xbmc/xbmc#24081]
### Describe the bug

If you want to view pictures from an external hard drive using the “Pictures” menu item, Kodi crashes.  There are no problems with Kodi Nexus.

### To Reproduce

1. Tap picture in the menu
2. Tap external USB
3. Tap the Pictures folder
4. After a few seconds Kodi Omega crashed 

### Debuglog

The debuglog you will find here: https://paste.kodi.tv/saquwulaku

### Your Environment

Used Operating system
 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nokia Streaming Box 8000 Android 12
 - Kodi version: Kodi 21 Omega Beta 1

**Comment by ksooo** [comment]
Definitely nothing special for v21, it has been like this "forever".

**Comment by Nanomani** [comment]
Not sure but your issue could be linked with this one : 
https://github.com/xbmc/xbmc/issues/23993

The fix will be on the next nightly build : 
https://github.com/xbmc/xbmc/pull/24022

**Comment by fraz14** [comment]
O.k. i will see :+1:

**Comment by fraz14** [comment]
Yeah, no issues with the last nightly :-)

**Comment by fraz14** [comment]
Fixed with this commit
https://github.com/xbmc/xbmc/pull/24022/commits

**Comment by vitek1355** [comment]
Здравствуйте, kodi почему-то  перестал подключаться по smb к серверу с паролем . Бес пароля заходит спокойно.
