### ISSUE TITLE
Configuration lost on Chromecast

### ISSUE THREAD

**Issue by psholm** [xbmc/xbmc#24102]
### Describe the bug

When using Kodi on a chromecast, configuration may get lost/reset during a hard powercycle

After using Kodi, then exiting kodi (via the exit menu buttom), then switching off the power to the Chromecast, the Kodi configuration sometimes gets lost/reset.
When the configuration reset, it looses the UPNP enable configuration option, as well as default subtitles, possible also other changed configuration parameters.

It happen almost everytime when 
 - start kodi, and use it
 - exit kodi
 - power off chromcast

It happens not as often when 
- start kodi, and use it
- exit kodi
- reboot chromecast
- power off chromecast
I have so far not lost the sources

The problem have been there for quite some time 

A thought could be that the configuration file is not flushed on exit, and then gets corrupted when switching off the chromecast power.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Configuration is saved, and unchanged after reboot

## Actual Behavior

Configuration is lost, but not always

### To Reproduce

1. start kodi, and use it
2. exit kodi (using exit buttom)
3. poweroff chromecast

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: latest, and previous versions

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
No debug log?

**Comment by psholm** [comment]
This is all i have, its a cromecast device, with a remote control, i'm not sure how to access a debug log
