### ISSUE TITLE
Kodi is having problems using the new version of Fedora 39, where the brazucaplay application does not open and closes Kodi 20.2

### ISSUE THREAD

**Issue by serial02** [xbmc/xbmc#24115]
Hello Kodi Team

Kodi is having problems using the new version of Fedora 39, where the brazucaplay application does not open and closes Kodi 20.2

Kodi should be able to open the brazuca play app without errors, as in OpenSuse Tumbleweed is working correctly.

Kodi is having problems using the new version of Fedora 39, where the brazucaplay application does not open and closes Kodi 20.2

Attached are several logs showing the errors that occurred:

[kodi_crashlog-20231118_111453.log](https://github.com/xbmc/xbmc/files/13400560/kodi_crashlog-20231118_111453.log)
[kodi_crashlog-20231116_061328.log](https://github.com/xbmc/xbmc/files/13400561/kodi_crashlog-20231116_061328.log)
[kodi_crashlog-20231116_061231.log](https://github.com/xbmc/xbmc/files/13400562/kodi_crashlog-20231116_061231.log)
[kodi_crashlog-20231112_111343.log](https://github.com/xbmc/xbmc/files/13400564/kodi_crashlog-20231112_111343.log)
[kodi_crashlog-20231112_105431.log](https://github.com/xbmc/xbmc/files/13400565/kodi_crashlog-20231112_105431.log)
[kodi_crashlog-20231112_105204.log](https://github.com/xbmc/xbmc/files/13400566/kodi_crashlog-20231112_105204.log)
[kodi_crashlog-20231112_083113.log](https://github.com/xbmc/xbmc/files/13400567/kodi_crashlog-20231112_083113.log)
[kodi_crashlog-20231108_152546.log](https://github.com/xbmc/xbmc/files/13400568/kodi_crashlog-20231108_152546.log)
[kodi_crashlog-20231107_213359.log](https://github.com/xbmc/xbmc/files/13400569/kodi_crashlog-20231107_213359.log)
[kodi_crashlog-20231107_213152.log](https://github.com/xbmc/xbmc/files/13400570/kodi_crashlog-20231107_213152.log)

https://github.com/xbmc/xbmc/assets/32621790/6e431df8-c851-45c4-9dea-96a6ff925e36

[kodi_crashlog-20231118_111453.log](https://github.com/xbmc/xbmc/files/13400560/kodi_crashlog-20231118_111453.log)
[kodi_crashlog-20231116_061328.log](https://github.com/xbmc/xbmc/files/13400561/kodi_crashlog-20231116_061328.log)
[kodi_crashlog-20231116_061231.log](https://github.com/xbmc/xbmc/files/13400562/kodi_crashlog-20231116_061231.log)
[kodi_crashlog-20231112_111343.log](https://github.com/xbmc/xbmc/files/13400564/kodi_crashlog-20231112_111343.log)
[kodi_crashlog-20231112_105431.log](https://github.com/xbmc/xbmc/files/13400565/kodi_crashlog-20231112_105431.log)
[kodi_crashlog-20231112_105204.log](https://github.com/xbmc/xbmc/files/13400566/kodi_crashlog-20231112_105204.log)
[kodi_crashlog-20231112_083113.log](https://github.com/xbmc/xbmc/files/13400567/kodi_crashlog-20231112_083113.log)
[kodi_crashlog-20231108_152546.log](https://github.com/xbmc/xbmc/files/13400568/kodi_crashlog-20231108_152546.log)
[kodi_crashlog-20231107_213359.log](https://github.com/xbmc/xbmc/files/13400569/kodi_crashlog-20231107_213359.log)
[kodi_crashlog-20231107_213152.log](https://github.com/xbmc/xbmc/files/13400570/kodi_crashlog-20231107_213152.log)

![Captura de tela de 2023-11-18 11-51-24](https://github.com/xbmc/xbmc/assets/32621790/72d4e40a-ddc7-4eb1-bfe1-6c6af88b1d69)

- Kodi version: 20.2

  *note: Once the issue is resolved, we request that you update it with new information or Kodi versions if necessary.
  The Kodi team will consider your issue report, however, we make no promises that the issue will be resolved.*

**Comment by neo1973** [comment]
Looks like the same issue as #24069. You have multiple options to handle this:
* Build Kodi 20.2 yourself and include commit https://github.com/xbmc/xbmc/commit/4bf9de87e700f0de56ef698a8d8d6eb7d4ff9050 (or ask the Fedora packager to include the patch in the RPM)
* Switch to Kodi 21 Beta 1
* Use the Flatpack version
