### ISSUE TITLE
[Xbox] UWP nightlies cannot be controlled with the Xbox controller

### ISSUE THREAD

**Issue by CasperMcFadden95** [xbmc/xbmc#24112]
### Describe the bug
Kodi does not react to Xbox controller input. It can be controlled with a USB keyboard or the web ui.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi reacts to Xbox controller input

## Actual Behavior

Kodi does not react to Xbox controller input.

## Possible Fix

Building with peripheral.joystick might fix it but I don't know how to do that https://github.com/xbmc/xbmc/pull/19221#issuecomment-808759882

### To Reproduce

1. Download a nightly from https://mirrors.kodi.tv/nightlies/windows/uwp64/master/ and install via Xbox dev mode
2. Launch Kodi and it won't react to controller inputs
3. Plugging in a USB keyboard works so Kodi has not frozen. Controlling from the web ui also works

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name: Xbox Series X
 - Kodi version: https://mirrors.kodi.tv/nightlies/windows/uwp64/master/Kodi-20231116-32194391-master-x64.msix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Should be fixed by https://github.com/xbmc/peripheral.joystick/pull/289

**Comment by thexai** [comment]
fyi @garbear

**Comment by thexai** [comment]
Tested and confirmed is fixed by https://github.com/xbmc/peripheral.joystick/pull/289

**Comment by CasperMcFadden95** [comment]
Thanks. I started it again and it worked.

**Comment by garbear** [comment]
Make sure you are using peripheral.joystick with version >= v21.1.8 and the problem will be fixed.
