### ISSUE TITLE
Auto play next episode not working on Android TV on latest 21.0-BETA1 

### ISSUE THREAD

**Issue by tar-gezed** [xbmc/xbmc#24129]
### Describe the bug

Automatic play of next episode is not working on my Nvidia Shield TV with latest Kodi 21.0-BETA1. 
When the current episode is finished, instead of playing the next one automatically like in 20.x, the player closes itself and I'm back to the episode list UI. 
Not a big issue but kinda annoying when bingewatching a TV show 😅

I already tried to disable and then re-enable the "auto play next episode" setting but it didn't fix it.  

Thanks in advance and thanks for this amazing piece of software 😉

## Expected Behavior

When the current episode is finished and the "auto play next episode" setting is enabled, it should play the next episode automatically. 

## Actual Behavior

When the current episode is finished and the "auto play next episode" setting is enabled, it doesn't play the next episode automatically. 

### To Reproduce

1. Enable the "auto play next episode" setting
2. Start an episode of a TV show with multiple episodes (but not last one) 
3. Wait for the end of the episode 
4. At the end, the player is closed and I'm back at the episode list UI, the next episode is not started

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/13443853/kodi.log)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I have some plug-ins, maybe it's related but I don't think so. 

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 11, Nvidia Shield TV 2015 Edition (9.1.1 update) 
 - Kodi version: 21.0-BETA1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Can you confirm that it works if you select "uncategorized" for the "autoplay next video" setting, in addition to "episodes"?

**Comment by tar-gezed** [comment]
> Can you confirm that it works if you select "uncategorized" for the "autoplay next video" setting, in addition to "episodes"?

Oh indeed the "autoplay next video" setting is "working" with TV shows if I select "uncategorized" in addition to "episodes".

Not the wanted behavior I guess but it's a nice temporary fix, thanks 😉
