### ISSUE TITLE
Error: failed to duplicate EGL fence fd

### ISSUE THREAD

**Issue by kyak** [xbmc/xbmc#24122]
# Bug report

## Describe the bug

With this PR (https://github.com/xbmc/xbmc/pull/23921) i see this problem in master: there is lots of tearing/horizontal line when scrolling.

## Expected Behavior

No tearing should occur.

## Actual Behavior

Tearing and horizontal lines appear when scrolling.

## Possible Fix

Downgrading to 99721fc699c helps.

## To Reproduce

Build from the latest master using Orange Pi 5 with mesa-panfork.

## Debuglog

That's basically it, these message absolutely flood the log:

```
2023-11-20 20:03:07.562 T:3174    error <general>: failed to duplicate EGL fence fd (EGL_SUCCESS)
2023-11-20 20:03:07.568 T:3174     info <general>: Skipped 1 duplicate messages..
2023-11-20 20:03:07.568 T:3174    error <general>: CDRMAtomic::DrmAtomicCommit - atomic commit failed: Device or resource busy
```

**Comment by lrusak** [comment]
@jernejsk do you have any knowledge about this platform? Is it expected to work?

**Comment by kyak** [comment]
> Please provide the **debug** log anyway, we need to see what happens before the issue occurs. But so far I assume it's a driver issue.

Attached is the complete log.

[kodi.log](https://github.com/xbmc/xbmc/files/13418936/kodi.log)

**Comment by hbiyik** [comment]
@lrusak @neo1973 

This is happening with [mesa-panfork](https://gitlab.com/panfork/mesa)  which is a fork of mesa that provides early mali g610 V10 support. I have traced the issue with gdb and it seems that this fence and async workflow is not implemented.

I am not a mesa expert, actually each time i look at it i get even more confused, and we can not ask you to support this fork, but at least is it possible to disable this async workflow somehow.

If in early stage somehow EGL propagates that it can do it, may be i can try to at least patch that part of panfork, so kodi wont use this async thing.

```c
int
panfrost_fence_get_fd(struct pipe_screen *screen,
                      struct pipe_fence_handle *f)
{
        struct panfrost_device *dev = pan_device(screen);
        int fd = -1;

        /* TODO: Export a sync file using KCPU */
        if (dev->kbase)
                return fd;

        drmSyncobjExportSyncFile(dev->fd, f->syncobj, &fd);
        return fd;
}
```

**Comment by neo1973** [comment]
Hmm, maybe you can return 0 here? https://gitlab.com/panfork/mesa/-/blob/csf/src/gallium/drivers/panfrost/pan_screen.c?ref_type=heads#L360 Not sure if this is enough to prevent Kodi from using fences but worth a try I'd say.

**Comment by hbiyik** [comment]
@neo1973 that worked thanks, youre awesome.
@kyak i will provide the fix with panfork.

**Comment by neo1973** [comment]
Glad we could help :slightly_smiling_face:

**Comment by jernejsk** [comment]
@lrusak Panfork is one man job which will never be upstreamed and it's completely ignored by mesa developers. Instead, there is different implementation which is meant to be merged in future in mesa and kernel. Not sure what is hold up though. My suggestion is that we don't waste time with incomplete mesa implementations.
