### ISSUE TITLE
[VideoVersion] "Resume"  from "Dialog Video Info" start always from beginning with multi versions

### ISSUE THREAD

**Issue by Nanomani** [xbmc/xbmc#24136]
### Describe the bug
Here is a clear and concise description of what the problem is:

If you you want resume a movie that has more than 1 version from "Dialog Video Info" the movie start alway's from the beginning.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect that the movie resume from the last position. 
This works fine from the widget at home from "in progess movies" widget

## Actual Behavior

"Resume"  from "Dialog Video Info" start always from begining with multi version set 

### To Reproduce

1.  have a movie with 2 versions 
2. start to read one of this version
3. stop reading
4. open "information" for this movie"
5. click on "play" button
6. "Resume from" / "play from beginning" is displayed
7. Select "Resume from"
8. The "DialogVideoVersion" dialog box opens automatically
9. Then select one or the other version launch the movie at the beginning

### Debuglog
The debuglog can be found here:

https://paste.kodi.tv/bayusomipe.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

![1](https://github.com/xbmc/xbmc/assets/3939543/3f5e91ec-a115-4571-a6d4-b2a1742ed886)

![2](https://github.com/xbmc/xbmc/assets/3939543/3e4e9f76-ed32-416b-b2d3-621ece7e8153)

![3](https://github.com/xbmc/xbmc/assets/3939543/11d4c9c8-7984-460d-9d64-1e2edbebcb0b)

![4](https://github.com/xbmc/xbmc/assets/3939543/9064e751-6abb-4c21-8f54-f05fddf5b0a5)

![6](https://github.com/xbmc/xbmc/assets/3939543/8e88ec8c-884e-4873-8bb2-76e416e90f94)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

It's a fresh feature. So no urgent here. This issue is FYI only. 
Thanks for all works  :)

### Your Environment
Used Operating system:

 - [X] Windows

 - Operating system version/name:
 - Kodi version: 21.0-BETA1 (20.90.801) Git:20231122-8f075c5358)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by da-anda** [comment]
when resumed the version dialog should not be triggered at all, since the resume point already is for a specific version. We will look into it.

**Comment by ksooo** [comment]
@xodidox 

```
1. click on "play" button
2. "Resume from" / "play from beginning" is displayed
3. Select "Resume from"
4. The "DialogVideoVersion" dialog box opens automatically
```

We can see here that the order is wrong. Should be 1. 4. 2. 3. 
Sthis can be fixed by what I already told you. To move the version select dialog into video/guilib/VideoPlayActionProcessor.cpp and video/guilib/VideoSelectActionProcessor.cpp

**Comment by xodidox** [comment]
@ksooo , the issue here is I overlooked the "resume" in VideoInfo dialog, the dialog shouldn't appear at all, just created a PR to fix this.

**Comment by ksooo** [comment]
@xodidox I think I have difficulties to express what the actual problem is and how to fix properly. I will come up with what I consider the proper fix once I find the time. Your fix might work, but only for this particular bug. We can run into this bug wherever playback of movies with version can be triggered. We do not want to apply your patch everywhere.

**Comment by xodidox** [comment]
@ksooo I'll create a separate PR for this.
