### ISSUE TITLE
xml issue 21.0-beta1 (20.90.801) installed via flatpak

### ISSUE THREAD

**Issue by quickmic** [xbmc/xbmc#24135]
`<favourites>
    <favourite name="Albert Park Circuit (Melbourne" thumb="http://127.0.0.1:57342/picture/2c7651463a04438aa12693e7ed9c7ec1/p-13751-0-p-4ecd55858cb06e2a8b73427c620db8b6">PlayMedia("http://127.0.0.1:57342/movies/2c7651463a04438aa12693e7ed9c7ec1/13743/m-13751-54a2a7b26582f68357d2add1283bdb5c-21-180-0-1-0-0-0-0-h264-8809759-ac3-384000--Albert_Park_Circuit__Melbourne__2012.mkv")</favourite>
</favourites>
\00`

tail \00
-> favourites.xml 

probably same for all xmls (sources.xml etc)

**Comment by ksooo** [comment]
No idea what you are talking about. Please fill the issue template then we can have a look.

**Comment by quickmic** [comment]
file corruption
![xmls](https://github.com/xbmc/xbmc/assets/27644375/77733202-8785-4428-891b-8a990af96e80)

**Comment by faush01** [comment]
it does look like Kodi 21 is adding a null 00 to the end of xml files it is creating

Kodi20
`000002D0   69 65 6C 64 5F 66 69 6C 74 65 72 73 25 37 64 25  ield_filters%7d%
000002E0   32 36 49 6D 61 67 65 54 79 70 65 4C 69 6D 69 74  26ImageTypeLimit
000002F0   25 33 64 31 25 32 36 66 6F 72 6D 61 74 25 33 64  %3d1%26format%3d
00000300   6A 73 6F 6E 26 71 75 6F 74 3B 2C 72 65 74 75 72  json&quot;,retur
00000310   6E 29 3C 2F 66 61 76 6F 75 72 69 74 65 3E 0A 3C  n)</favourite>.<
00000320   2F 66 61 76 6F 75 72 69 74 65 73 3E 0A           /favourites>.`

Kodi21
'00000190   6E 67 25 33 64 46 61 6C 73 65 25 32 36 46 69 65  ng%3dFalse%26Fie
000001A0   6C 64 73 25 33 64 25 37 62 66 69 65 6C 64 5F 66  lds%3d%7bfield_f
000001B0   69 6C 74 65 72 73 25 37 64 25 32 36 49 6D 61 67  ilters%7d%26Imag
000001C0   65 54 79 70 65 4C 69 6D 69 74 25 33 64 31 25 32  eTypeLimit%3d1%2
000001D0   36 66 6F 72 6D 61 74 25 33 64 6A 73 6F 6E 22 2C  6format%3djson",
000001E0   72 65 74 75 72 6E 29 3C 2F 66 61 76 6F 75 72 69  return)</favouri
000001F0   74 65 3E 0A 3C 2F 66 61 76 6F 75 72 69 74 65 73  te>.</favourites
00000200   3E 0A 00                                         >..'

notice the 00

**Comment by ksooo** [comment]
AGain, please provide the information we request in the issue template. Otherwise this sissue will be closed as invalid. We have no log file, we do not know exact version and operating system etc.

Had a quick check on my Mac, there the favourites.xml has no trailing 0 char.

**Comment by ksooo** [comment]
Reading flatpack, maybe @razzeee has a clue...

**Comment by faush01** [comment]
I did not say it was a 0 char, I said it was a null 00

**Comment by ksooo** [comment]
> I did not say it was a 0 char, I said it was a null 00

 Ofc. But does not matter. Any trailing char (except blank) will lead to invalid xml
And now I'm closing this issue until you provide requested information.

**Comment by neo1973** [comment]
I can reproduce the issue and #24141 fixes this.
