### ISSUE TITLE
Video codec label not dispayed for Theora

### ISSUE THREAD

**Issue by Emiritus1** [xbmc/xbmc#24142]
### Describe the bug
Here is a clear and concise description of what the problem is: Kodi not displaying video codec label for Theora <p><a href="https://paste.kodi.tv/qujedukabo">Mediainfo</a></p>

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
 Kodi should display video codec label

## Actual Behavior
 Kodi does not display video codec label

### To Reproduce

1. Obtain a video with the video codec Theora
2. Launch Kodi
3. Enter videos

### Debuglog

The debuglog can be found here: <a href="https://paste.kodi.tv/divutamowu">Debuglog</a>

### Screenshots 
Here are some links or screenshots to help explain the problem:
 <a href="https://ibb.co/9T0VT2Q">Picture displaying the issue</a>

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Amazon Fire TV
 - Kodi version: 21.0-BETA1 (20.90.801)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by scott967** [comment]
OP Please do not assume a debug log is "NA".  It always helps, in this case it shows what Kodi thinks the codecs are for your particular video sample.

**Comment by Emiritus1** [comment]
@scott967 Here is the debuglog - https://paste.kodi.tv/divutamowu

**Comment by scott967** [comment]
Thanks for the log.  As you see the problem is Estuary skin does not have a flag icon for Theora and that will be fixed.
