### ISSUE TITLE
Realtek ati hdmi don’t work with Kodi - Kodi does not support 

### ISSUE THREAD

**Issue by antoine1971** [xbmc/xbmc#24158]
<! Hi there, sorry for intruding (new member) but I have an issue with my sound output on my laptop as well. I have an old laptop (sony vaio)  Intel® Core™2 Duo CPU P7450  @ 2.13GHz   2.13 GHz , RAM 6,00 GB, windows 10 x64 and a soundbar Sony HT-ZF9 that supports all kind of sound formats. I read in an article here, that REALTEK ATI HDMI is not compatible with Kodi. I also tried it setting WASAPI/ATI HDMI pass through on a movie with Dolby Atmos 7.1 and didn't work (crashed).
I deactivated, uninstalled etc everything from realtek, in order to download AMD or INTEL ati hdmi drives (don't know any more), but are not compatible with my laptop. i am not a programmer or an expert or anything. I am just trying, reading, testing etc months now to resolve it, but I just can't!!
Is there a way I can resolve this issue and use Kodi? (i think there is no way here to upload any saved images to help you understand more, but surely some tech experts will understand).
Thank you 
I hope that I explained my issue as better as I could

**Comment by antoine1971** [comment]
So should I edit that? or do what?

**Comment by garbear** [comment]
Superseded by https://github.com/xbmc/xbmc/issues/24158
