### ISSUE TITLE
[Linux] HDR video require stopping the playback to play the next HDR video

### ISSUE THREAD

**Issue by smp79** [xbmc/xbmc#24166]
### Describe the bug
Here is a clear and concise description of what the problem is:

I noticed that if during the playback of HDR video I start the playback of another HDR video - it would appear that wrong (old) metadata is sent to the display.

[Sample video 1](https://www.dropbox.com/scl/fi/xmjaz76omeq5m4z95uunz/02.-White-240-1000nits-MaxCLL-1000-MDL-1000.mp4?rlkey=0h1o97j522t0bpxafygu4i3r0&dl=1)
[Sample video 2](https://www.dropbox.com/scl/fi/2h8px1oiz5hlcm5m8x2sv/04.-White_900-4000nits-MaxCLL-4000-MDL-4000.mp4?rlkey=tupyb0jdv4d92mmbpaaby0t6w&dl=1)

### To Reproduce

1. Play sample video 1
2. Start the playback of video 2 during the playback of video 1
3. Stop the playback of video 2
4. Start the playback of video 2

On my TV I see a completely different clipping test results for step 2 and step 4. It would appear that if you start the playback of video 2 when playing video 1 - the "old" metadata from video 1 is still being used for video 2.

### Debuglog

The debuglog can be found here:
https://gist.github.com/smp79/42ace9edc79d37f4bd7db09ffe9059ea

### Your Environment
Used Operating system:

 - [x] Linux

 - Operating system version/name: LibreELEC
 - Kodi version: current master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by bacon-cheeseburger** [comment]
I followed your instructions to reproduce the problem using your sample files and don't see any difference. Do you have alternate sample files that are more obvious to try? I don't know if Kodi's built-in screenshot feature supports HDR but if so, maybe it'd help if you took screenshots.

I tested using 21.0b1-Omega-r64480-git+22a988aad3 running on Debian Linux, connected to an LG OLED tv.

**Comment by smp79** [comment]
> Do you have alternate sample files that are more obvious to try?

The more obvious example is to play a HLG video while playing a HDR10 video or vice versa. If you start to play a HDR10 video while playing HLG video - the TV would still use a HLG mode until you stop and restart the HDR10 video. The issue seem to occur only if both files have the same resolution and refresh rate. 

I did not mention this more obvious scenario in my initial bug report because current Kodi master does not allow switching to HLG mode without #24160

**Comment by smp79** [comment]
> I don't know if Kodi's built-in screenshot feature supports HDR but if so, maybe it'd help if you took screenshots.

This how the video 2 looks when it was started "normally":

![IMG_20231209_172858](https://github.com/xbmc/xbmc/assets/28512968/8abe7e50-efbf-446b-a13a-57d44ed3d542)

This is when that same video 2 is started during the playback of video 1:

![IMG_20231209_172822](https://github.com/xbmc/xbmc/assets/28512968/b50fe6b1-9f2f-4942-954f-169a9e183078)

Notice almost no grey squares on second photo. That's not because of a bad photo - that's how it actually looks.

**Comment by smp79** [comment]
The issue is happening only if the HDR video we are switching to has the same resolution/fps as the previous HDR video.  
This is "fixed" If I force renderer reconfigure, like this for example:

```
diff --git a/xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp b/xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp
index 7bf7fcc..92f35fd 100644
--- a/xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp
+++ b/xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp
@@ -93,7 +93,7 @@ bool CRenderManager::Configure(const VideoPicture& picture, float fps, unsigned
         m_height == picture.iHeight &&
         m_dwidth == picture.iDisplayWidth &&
         m_dheight == picture.iDisplayHeight &&
-        m_fps == fps &&
+        m_fps != fps &&
         m_orientation == orientation &&
         m_stereomode == picture.stereoMode &&
         m_NumberBuffers == buffers &&
```

ping @fritsch @a1rwulf @lrusak

**Comment by fritsch** [comment]
This is not the proper fix. Idea of this function is to avoid reconfiguring (loosing frames) as good as possible. What you are doing here basically drives this aspect nuts.

The real solution would be to check if initial hdr mode matches next hdr mode and if those change -> switch.

**Comment by smp79** [comment]
Of course this is not a proper fix. That's why I pinged you guys so you would figure out a proper one :smiley:

**Comment by fritsch** [comment]
Got it :-).  Yeah - if we continues this behaviour to compare picture (new video) and local properties, we need to store HDR information inside the object and in the picture and add those to the comparison. This way we can reconfigure the moment those attributes change.
