### ISSUE TITLE
Problem playing Dolby Vision movies and series via streaming services

### ISSUE THREAD

**Issue by Ronny-nerd** [xbmc/xbmc#24171]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello Kodi Team @fritsch or @ksooo,

Hadrware:
Nvidia Shield TV Pro 2019
LG OLED55B7D

Via streaming services (Netflix Addon, Amazon Prime Addon, Disney+ Addon) from kodi-20231124-940fe21f-master-arm64-v8a.apk and newer build = not OK = problems with 4K no Dolby Vision start icon on TV and when playing movies/series - black picture but sound is running.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Via streaming services (Netflix Addon, Amazon Prime Addon, Disney+ Addon)  with kodi-20231122-8f075c53-master-arm64-v8a.apk and builds before that = OK = No problems even if you return from a newer build.

## Actual Behavior

Via streaming services (Netflix Addon, Amazon Prime Addon, Disney+ Addon) Problems with 4K no Dolby Vision start icon on TV and when playing movies/series - black picture but sound is running.

kodi-20231124-940fe21f-master-arm64-v8a.apk = Not OK
kodi-20231127-b4ae12fe-master-arm64-v8a.apk = Not OK
kodi-20231128-4a41a5e4-master-arm64-v8a.apk = Not OK
kodi-20231130-12d991a5-master-arm64-v8a.apk = Not OK

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:  https://paste.kodi.tv/irinahiyaf.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 11
 - Kodi version: Nightlies Kodi 21 Omega Beta1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
Comparing the last good version with the first bad version (https://github.com/xbmc/xbmc/compare/8f075c53...940fe21f) it looks like #23577 could be the culprit.

**Comment by quietvoid** [comment]
I guess IS.A doesn't fill the `AVDOVIDecoderConfigurationRecord` so it's defaulting to zeroed which in turn sets the wrong codec profile..
