### ISSUE TITLE
Mouse Navigation Broken in Manage/Play Video Versions

### ISSUE THREAD

**Issue by CrystalP** [xbmc/xbmc#24189]
### Describe the bug

Using the mouse is problematic in the versions management screen.

1/ When the mouse is anywhere other than on the "Versions" or "Extras" buttons, the list of versions is blank (by luck, the mouse position is in the versions list after clicking on Manage versions in the context menu, so problem doesn't happen until you move the mouse - but that can't be relied on)
That makes it impossible to move the mouse to Versions, select a version and then a button on the right for an action because the screen goes blank.

![image](https://github.com/xbmc/xbmc/assets/489377/15880f88-5cff-4f99-a4b8-ee1ed6eb3208)

The same effect happens when selecting a version to play (from movie information)

![image](https://github.com/xbmc/xbmc/assets/489377/3c76549c-024d-4f63-97d3-ef4a78e59ddf)
However due to the placement of the Play button in Information that opens the version selection, the list is blanked as soon as the mouse moves and it's impossible to select something. Unlike the Manage versions where mouse position from last screen is lucky and allows to somewhat use the screen.

2/ With the right position of the mouse, both Versions and Extras can be selected at the same time. That seems to be because the buttons activate when the mouse enters an invisible border that extends outside the buttons:
![image](https://github.com/xbmc/xbmc/assets/489377/d64b0219-6675-4ced-be85-dcd421047b5a)

Keyboard navigation is fine.

I don't have a touch device to test how it works.

## Expected Behavior

Ideally mouse clicks would be required to change the selection of the buttons and the items in the list and hovering wouldn't change the selection. It may not be feasible by skin change, so:

The current selection of "Versions" or "Extras" mode should remains until it is changed by moving the mouse over the other mode button.

Default of "Versions" is OK but should remain until mousing over "Extras". Conversely when "Extras" is activated, it should remain until the mouse is moved over "Versions"

## Actual Behavior

Move the mouse outside of the Versions or Extras button and the list of versions goes blank.
It sort of works right when opening the screen by luck in the placement of the button that opens the screen.

## Possible Fix

Have the screen work more like the Settings screens with multiple blades - the last selection remains when moving outside of the button and only changes when moving the mouse over another button.

screenshot: hover on Display > then slide to list of settings to the right. The category remains Display
![image](https://github.com/xbmc/xbmc/assets/489377/c815946b-abad-4b01-a290-aba26a717cf4)

### To Reproduce

Preferably have a movie with multiple versions, but focus problems don't depend on it
1. Long-click on Movie in Library
2. Click Manage then Manage movie version
3. Move the mouse to Extras or outside the list. The buttons seem to be OK for some reason.
4. Blank versions list, unable to make a selection to apply an action (the right buttons)

### Debuglog

https://paste.kodi.tv/xiqimuwilu.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 21 beta 1 master of 2023-12-04

@xodidox FYI

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jjd-uk** [comment]
Will see if I can improve behaviour described in 1/
Not sure if 2/ is something I can do anything about, as it's the same for all dialogs I think.

**Comment by thexai** [comment]
Fixed by https://github.com/xbmc/xbmc/pull/24286
