### ISSUE TITLE
External Player Selection Ignored for Movies with Multiple Versions

### ISSUE THREAD

**Issue by CrystalP** [xbmc/xbmc#24184]
### Describe the bug

External player not started for movies with additional versions.

## Expected Behavior

The chosen external player plays the selected movie version.

## Actual Behavior

videoplayer plays the selected movie version.

### To Reproduce

Must have a movie with multiple versions in library, and at least one external player setup.
"Show video with multiple versions as folder" is default value OFF.

1. Choose "Play using..." on the movie
2. Select an external player
3. The movie version dialog appears, select any version
4. The movie is played by videoplayer instead of the external player chosen earlier.

Broken only for movies for additional versions, works fine for movies with single version.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/xiqimuwilu.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: master 4de822d5c

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
> 3. The movie version dialog appears, select any version

The context menu actions are always related to the default video version. So, no version dialog must appear and after selecting the player the default video version should be played.

I will have look and try to come up with a fix soon.

**Comment by CrystalP** [comment]
OK, how would one play a version with an external player? Is that the part to be fixed?
I should have written than "display versions as folder" was off (the default).

**Comment by ksooo** [comment]
OMG, I start feeling like Mr Video Version - but I never wanted to be this.

However, I'm going to add a new context menu item "Choose version" so any version can be picked up easily from the context menu.

**Comment by CrystalP** [comment]
No worries, your contributions are very appreciated! The context menu happens to tie a lot of things together.
It's not a high priority problem, I reported because I happened to notice it.

**Comment by ksooo** [comment]
@CrystalP could you check latest master and tell whether something changed wrt external player support?

**Comment by CrystalP** [comment]
Yes, through the context menu, you get either your version of choice through video player only through "Choose version..." or external player with default version through "Play using..."

**Comment by ksooo** [comment]
So all working as expected now?

**Comment by CrystalP** [comment]
There may be a misunderstanding. My player factory doesn't have additional rules to autoselect one of the external players.
Videoplayer is always the default.
So far I've been relying on "Play using..." in context menu to sometimes pick an external player. I'm not aware of a UI flow where player selection can be combined with version selection.
Your changes clarified how things work but did not create that flow.

Maybe a Play Using... button could be added in the version selection screen.
Or we could say it's only supported when movie versions are displayed as a folder.

**Comment by ksooo** [comment]
@CrystalP not sure what to do with this issue. Issue description and expected behaviour are not really matching anything we want to have. Either we close this issue or revise it completely.

You spotted a bug in the context menu implementation, which meanwhile is fixed. "Play using..." is not supposed to show the version selector at all, especially not after (!) the player selector, the players available are dependent on the movie, so first a version must be selected, then the player. But as I said, the context menu items of a movie with multiple versions are always acting upon the default version of the movie (except "Choose version"). So "Play using..." will always play the default version of the movie.

What could solve the problem would be a new context menu item "Play version using...", which would 1. show the version selector, then the player selector.

**Comment by CrystalP** [comment]
PR will fix the issue.
