### ISSUE TITLE
Video versions: Default Version Is Not Default in Manage/Play Versions

### ISSUE THREAD

**Issue by CrystalP** [xbmc/xbmc#24188]
### Describe the bug

When opening the manage versions screen for a video that had its default version changed, reopening the screen highlights the first item of the list instead of the chosen default version.

unrelated note: the highlight color is difficult to distinguish from the regular color (slightly brighter gray than the other lines?)

The same thing happens with the version selection dialog before playing a movie (first item selected instead of the user chosen default version).

## Expected Behavior

The default version for this movie is Extended.

The default version is highlighted when the screens open:
![image](https://github.com/xbmc/xbmc/assets/489377/397c7d4d-e18b-4b0e-9c61-f36c10da0f85)

![image](https://github.com/xbmc/xbmc/assets/489377/e43140f1-cfc6-4bae-888c-bb5ec3754b87)

## Actual Behavior

First item is highlighted:
![image](https://github.com/xbmc/xbmc/assets/489377/a1d85259-6434-41db-b2c5-9b395f843602)

![image](https://github.com/xbmc/xbmc/assets/489377/7948da09-c57a-430b-91bb-3b86b01853df)

### To Reproduce

Required: a video with multiple versions.

1. Go to Manage / Manage versions for the video
2. Select another version than the one listed at the top as the default version
3. Close the screen
4. Go to Manage / Manage versions again
5. First version of the list is highlighted instead of the version selected in step 2.
6. Exit manage
7. Open information
8. Press Play
9. Version selection dialog opens with first item selected

### Debuglog

https://paste.kodi.tv/isoqabigox.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21 alpha 1 current master as of 2023-12-04

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CrystalP** [comment]
@xodidox not sure if you're monitoring the issues, will bring it up in the forum.

**Comment by xodidox** [comment]
@CrystalP  I see the issue, but unfortunately, I don't have a solution for this currently. Seems this needs the core and skin work together to fix it. @jjd-uk @HitcherUK @jurialmunkey any ideas?

**Comment by xodidox** [comment]
I'm not sure if changing the order when changing default version is expected behavior. I tried to use CONTROL_SELECT_ITEM (https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/GUIMessage.h#L232) to select the default version in OnInitWindow, but seems it's not working. Need help on this part.

**Comment by jurialmunkey** [comment]
Is there currently a specific rule to how the items are ordered on the list or is it just order they were added? 

If there isn't a specific order, then I think that default should always be first item. It will save a lot of hassle skinning as core functions which force focus really limit options.

The only reason to preserve order is if there is a specific hierarchy - but there doesn't seem to be.

If the order is essentially random and the user cannot reorder items then simplest solution is to always put default at top

**Comment by xodidox** [comment]
> Is there currently a specific rule to how the items are ordered on the list or is it just order they were added?

There is no specific order in place, just what returned from DB.

**Comment by CrystalP** [comment]
As long as the order is consistent in the two screens (and anywhere else the versions may appear in the future), that'd be good enough.

**Comment by da-anda** [comment]
Is there a way to indicate the default version in the skin? Like with a ` (default)` suffix in the title? This will also help figuring out which one is actually the default

**Comment by xodidox** [comment]
I have an improvement https://github.com/xodidox/xbmc/commit/1379a3b82416491b40d153efef04cabb15d1d466 for the selected version handling, skin can set a different color for the selected version with this change, where the focused version is still using the highlight color. When you open the video version dialog, the default version will be selected, the selected color will be applied, so user can know what's the default version easily.

@CrystalP @jurialmunkey with this change, is it still necessary to adjust the order of versions?

**Comment by CrystalP** [comment]
Opening the playback screen looks like that with xodidox's change:
![image](https://github.com/xbmc/xbmc/assets/489377/74386817-bc99-4d3c-b348-4104ae55766a)

Kinda works for me for playback but not in manage I think, where the 3 text colors can get confusing(the selection, non-selected text, and the default).
A (default) suffix would definitely clarify but takes more space and has to be translated.
A * would be short, not translated but maybe not as clear,

**Comment by xodidox** [comment]
> Kinda works for me for playback but not in manage I think, where the 3 text colors can get confusing(the selection, non-selected text, and the default). A (default) suffix would definitely clarify but takes more space and has to be translated. A * would be short, not translated but maybe not as clear,

I believe a better highlight kind of color is needed for this. The above change just makes this possible. I used the red color during test, which is quite obvious in UI.

**Comment by jurialmunkey** [comment]
I presume this sets the ListItem.IsSelected flag which is imo the correct way to do it. The issues with appearance can be addressed in the skin (eg we can add an icon flag to the list instead of using a colour). @jjd-uk @HitcherUK and I have been discussing on slack further design improvements and one of the things we were looking for is this boolean to do something along those lines - so we've already got some ideas to improve the clarity of the item state further once this change is in.


In terms of ordering. There is a "specialsort" flag used by plugins to force a Listitem to the top/bottom of a list (usually used for next page, add more, or parent type items).
https://github.com/xbmc/xbmc/blob/8e4801e28a6a513780542062cd30c4173b27040f/xbmc/interfaces/legacy/ListItem.cpp#L203

I'm not sure if that's useful here as c++ is not my thing but maybe that type of thing could be a simple solution to getting the default item to the top for play without actually reordering the index of the items in the list. It's not important for the management dialog but the play dialog definitely should have the default item focused by default to reduce the number of clicks required (if I'm playing, most of the time I probably want to play the default and I shouldn't need to click up/down through the list to find it).

**Comment by xodidox** [comment]
>The play dialog definitely should have the default item focused by default to reduce the number of clicks required (if I'm playing, most of the time I probably want to play the default and I shouldn't need to click up/down through the list to find it).

I added a new commit (https://github.com/xodidox/xbmc/commit/92d8993685f6dd6f41136755e6f259b86602914f) to set the default version on top in the list, will create a PR for these changes after the dependent PR (https://github.com/xbmc/xbmc/pull/24148) merged.

**Comment by HitcherUK** [comment]
> I believe a better highlight kind of color is needed for this.

@jjd-uk is looking into fixing the selected colour.

**Comment by CrystalP** [comment]
Fixed by PR #24316 and #24336.
