### ISSUE TITLE
kodi- Jio tv Playback Failed issue

### ISSUE THREAD

**Issue by harshalgangurde44** [xbmc/xbmc#24196]
when i open jio tv on kodi and click any Channel it show an alert - Playback failed 

here is image url  --
![playback error -jio tv kodi](https://github.com/xbmc/xbmc/assets/125290125/c0e3e7e2-4f8d-4fb9-993e-647d4df4f6d9)

 - Kodi add-on repository : team kodi 3.3.1 
 - BotAllen  repository :  botallen  2.0.0
 - JioTv                         :   botallen  2.3.0
 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
For issues with an add-on please contact the author of that add-on. Here we only investigate issues with Kodi itself.
