### ISSUE TITLE
A NUL character is being added in Omega at the end of Favourites.xml

### ISSUE THREAD

**Issue by manfeed** [xbmc/xbmc#24206]
### When adding favourites in Omega a NUL character is added at the end of Favourites.xml.
Here is a clear and concise description of what the problem is:

When adding favourites in Omega a NUL character is added at the end of Favourites.xml which breaks skins with script.skinshortcuts. That NUL character wasn't added in Nexus nor in previous Kodi versions. When Favourites.xml is edited manually and that NUL character is removed everything works faultlessly, but next time you add another favourite the NUL character reappears.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Not adding a NUL character at the end of Favourites.xml in Omega. @jurialmunkey explains the issue in the Kodi forum in this post:
https://forum.kodi.tv/showthread.php?tid=178294&pid=3174757#pid3174757

## Actual Behavior

A NUL character is added at the end of Favourites.xml in Omega every time a new favourite is added.

## Possible Fix

Make Omega work as in previous Kodi versions, that is, not adding a NUL character at the end of Favourites.xml.

### To Reproduce

1. In Omega, add a new favourite.
2. Using any skin that uses script.skinshortcuts (Aeon Tajo, Aeon Nox Silvo...) try to edit any item of the main menu assigning it a favourite (it will tell you that there's no favourite to choose from)
3. Have a look at Kodi log, since an error with script.skinshortcuts will be recorded.
4. Edit Favourites.xml and remove the NUL character at the end of the file.
5. Now, when editing the main menu, all your favourites will appear and you will be able to assign them to any menu item (until you add a new favourite).

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![u6MhbRD](https://github.com/xbmc/xbmc/assets/13109584/c739623e-03ee-400e-9124-de9dea043483)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Omega

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
Thanks for the detailed reported but this has already been reported in #24135 and fixed in #24141. The upcoming beta will have the fix included.
