### ISSUE TITLE
error while loading shared libraries: libpython3.9.so.1.0

### ISSUE THREAD

**Issue by NelsonSR** [xbmc/xbmc#24216]
### Describe the bug
Here is a clear and concise description of what the problem is: After upgrading Debian «Bookworm» to the backports repository, Kodi can not start. That binary was compiled from the stable branch, on the same laptop but running Debian «Bullseye». It has been working perfectly fine until that last recent Debian upgrade.

Executing kodi from the console display this error message: 
```/usr/local/lib/kodi/kodi-x11: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory```
It seems that Python was upgraded, breaking the Kodi dependences. According to apt, the `libpython3.9` is contained on the `libpython3.9-minimal` package but it has no installation candidate. The package `libpython3.11-minimal` instead is already installed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Clicking on the Kodi icon or calling the `kodi` or the `kodi-x11` binary in the console should fire up the software.

## Actual Behavior

The software doesn't execute. In the console, an error message related with Python is displayed instead.

## Possible Fix

Update Kodi to the last Python release.

### To Reproduce

1. sudo apt update
2. sudo apt upgrade -t bookworm-backports
3.

### Debuglog

```
nelson@slimshadygray:~$ kodi
/usr/local/lib/kodi/kodi-x11: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
nelson@slimshadygray:~$
```

The debuglog can be found here:
```No log file was written, because the software hasn't executed.```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I upgraded the Debian OS to the last stable release

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian GNU/Linux «Bookworm» 12.4
 - Kodi version: 21.0 ALPHA1 20.90.101

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
You have to recompile Kodi every time a dependency changes its version.

**Comment by NelsonSR** [comment]
I did it before posting the error message (I didn't consider it relevant to mention in this report), but the error message keep showing.

**Comment by neo1973** [comment]
Then you didn't install the latest build or something. If Python 3.9 isn't even installed then its not possible for Kodi to link against that version.

**Comment by NelsonSR** [comment]
I checked out the last stable release. Not much was updated. I'm going to repeat the process to post it here.

**Comment by NelsonSR** [comment]
You were right, I didn't have the last release. I had to fetch, pull and stash my copy.
