### ISSUE TITLE
KODI Omega beta 2 subtitle sub menu - looking for subs in obscure dir

### ISSUE THREAD

**Issue by johnnyaywah** [xbmc/xbmc#24219]
### Describe the bug
Here is a clear and concise description of what the problem is:

Had this issue with Beta 1 as well
performed clean install
when a movie is running and i navigate to the subtitles icon, the subs sub-menu comes up ok
I then navigate to 'browse for subs and am presented with a new tableau of all movies, selecting the right movie does nothing

## Expected Behavior
Expect that when selecting the 'brows for subs' option, i will be directed to the same dir with the moivie in it so i can navigate and select the subs file

## Actual Behavior

Unusual directory of all movies appears (see screenshots)
![PXL_20231211_232052103](https://github.com/xbmc/xbmc/assets/82632362/e45af559-49fe-45d6-aaeb-106d174f18b1)
![PXL_20231211_232110860](https://github.com/xbmc/xbmc/assets/82632362/917edb60-2f96-478e-bfaa-efbc95ae4d9d)
![PXL_20231211_232118311](https://github.com/xbmc/xbmc/assets/82632362/9355d60c-26de-4aa2-9c1e-21053c6bbcb1)

kodi appears to bavigate to a DB and not the folders where the movies are

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android - Nvidia Shield TV
 - Kodi version: Omega beta 2 (issue existed with beta 1 also)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by johnnyaywah** [comment]
adding logfile - sorry for the delay

https://pastebin.com/NmrS7xBj

**Comment by neo1973** [comment]
Can confirm. Git bisect says its 8a460ba23364193fea80fb2187375c3c03573a8a from #23848.

**Comment by neo1973** [comment]
If I remove the this `if` block on the original commit https://github.com/xbmc/xbmc/blob/8a460ba23364193fea80fb2187375c3c03573a8a/xbmc/listproviders/DirectoryProvider.cpp#L534-L539 or this `if` block on master https://github.com/xbmc/xbmc/blob/74ed1613662c992724d25dc30a437c3e0677b3dd/xbmc/listproviders/DirectoryProvider.cpp#L564-L569 the old behaviour is back.

@ksooo: Any idea what's going on?

**Comment by johnnyaywah** [comment]
Can confirm this issue only applies if you enter via the main "Movies" sidebar shortcut

If you navigate the the "Videos" shortcut and select/play a movie there, Subs sub-menu behaviour is as expected

hope this helps

**Comment by thezoggy** [comment]
i use mariadb backend for my kodi instances.

could not replicate on windows10 with latest nightly (KodiSetup-20231218-735f8728-master-x64)

movies -> recently added -> picked movie, while playing or paused, went to subs, browse. loaded from current movie folder.
videos -> movies -> recently added -> picked movie, while playing or paused, went to subs, browse. loaded from current movie folder.
videos -> source -> movie folder ->picked movie, played, went to subs, browse and still good.

tossed same nightly on my nvidia shield, will check tomorrow and report back
