### ISSUE TITLE
add_library cannot create imported target "ffmpeg::libavcodec"

### ISSUE THREAD

**Issue by NelsonSR** [xbmc/xbmc#24220]
### Describe the bug
Here is a clear and concise description of what the problem is: Error building last stable release

`cmake` can not complete the configure process due to some `ffmpeg` errors: a missing FFmpeg 6.0.0 software and a duplicated "ffmpeg::libavcodec" target.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The configure process should ends with a message: `-- Build files have been written to: /usr/local/share/kodi-build`

### To Reproduce

1. cd /usr/local/share/kodi
2. sudo make -C tools/depends/target/crossguid PREFIX=/usr/local
3. sudo make -C tools/depends/target/flatbuffers PREFIX=/usr/local
4. sudo make -C tools/depends/target/fmt PREFIX=/usr/local
5. sudo make -C tools/depends/target/spdlog PREFIX=/usr/local
6. sudo make -C tools/depends/target/wayland-protocols PREFIX=/usr/local
7. sudo make -C tools/depends/target/waylandpp PREFIX=/usr/local
8. mkdir /usr/local/share/kodi-build
9. cmake ../kodi  -DCMAKE_INSTALL_PREFIX=/usr/local  -DCORE_PLATFORM_NAME=x11 -DAPP_RENDER_SYSTEM=gl -DENABLE_INTERNAL_FLATBUFFERS=ON 

### Debuglog

The debuglog can be found here:

[kodi_cmake.log](https://github.com/xbmc/xbmc/files/13641764/kodi_cmake.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The OS already has the `FFmpeg 6.0.0` fetched from deb-multimedia repository.
```
root@slimshadygray:~# dpkg -l ffmpeg*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name              Version                     Architecture Description
+++-=================-===========================-============-==================================================================
ii  ffmpeg            10:6.0.1-dmo0+deb12u1       amd64        audio/video encoder, streaming server & audio/video file converter
ii  ffmpeg-doc        7:5.1.4-0+deb12u1           all          Documentation of the FFmpeg multimedia framework
ii  ffmpegthumbnailer 2.2.2+git20220218+dfsg-1+b1 amd64        fast and lightweight video thumbnailer
ii  ffmpegthumbs      4:22.12.3-1                 amd64        video thumbnail generator using ffmpeg
root@slimshadygray:~#
```
So, it doesn't make sense the complain `FFmpeg 6.0.0 not found, falling back to internal build`

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian GNU/Linux 12.4 «Bookworm»
 - Kodi version: 21.0 BETA2 20.90.821

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by garbear** [comment]
I hit this error, and compiling with `-DENABLE_INTERNAL_FFMPEG=ON` fixed it for my use case.

**Comment by NelsonSR** [comment]
> Some of the linux folks can chime in, but do you have the dev packages installed?
> 
> libavutil-dev libavfilter-dev libavformat-dev libavcodec-dev libswresample-dev libwscale-dev
> 
> the ffmpeg package as far as im aware doesnt install the dev packages.

```
nelson@slimshadygray:~$ dpkg -l libavutil-dev libavfilter-dev libavformat-dev libavcodec-dev libswresample-dev libwscale-dev
dpkg-query: no packages found matching libavfilter-dev
dpkg-query: no packages found matching libwscale-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version               Architecture Description
+++-=======================-=====================-============-=======================================================================>
ii  libavcodec-dev:amd64    10:6.0.1-dmo0+deb12u1 amd64        Library to encode decode multimedia streams - devel files
ii  libavformat-dev:amd64   10:6.0.1-dmo0+deb12u1 amd64        Development files for libavformat
ii  libavutil-dev:amd64     10:6.0.1-dmo0+deb12u1 amd64        FFmpeg avutil devel files - devel files
ii  libswresample-dev:amd64 10:6.0.1-dmo0+deb12u1 amd64        FFmpeg library for audio resampling, rematrixing etc. - development fil>
lines 1-9/9 (END)
```

**Comment by garbear** [comment]
@fuzzard Maybe there's something to fix? The problem seems to be that, if `ENABLE_INTERNAL_FFMPEG` is specified, then the [buildFFMPEG() macro](https://github.com/xbmc/xbmc/blob/master/cmake/modules/FindFFMPEG.cmake#L29) is called immediately, which fixed the problem here, but otherwise, it finds the external libraries, but then fails [this check](https://github.com/xbmc/xbmc/blob/master/cmake/modules/FindFFMPEG.cmake#L377) and calls the macro after already defining the libraries above.

**Comment by fuzzard** [comment]
I've no doubt there's something to "fix", but no one has provided how to replicate such an environment so that I can work through it.

**Comment by garbear** [comment]
I can reproduce on Ubuntu 22.04. If I clone Kodi and do cmake in /build, it works. But if I've used depends to build a package (I need to build libdisplay-info from source), then I get the error above. Specifically, it happens in my build script on [this line](https://github.com/eigendude/OASIS/blob/main/oasis_tooling/scripts/build_kodi.sh#L134) if I comment out `-DENABLE_INTERNAL_FFMPEG=ON`. The error is:

```

-- FFmpeg 6.0.0 not found, falling back to internal build
-- Could NOT find Dav1d (missing: DAV1D_LIBRARY DAV1D_INCLUDE_DIR) (Required is at least version "1.1.0")
-- dav1d not found, internal ffmpeg build will be missing AV1 support!
CMake Error at cmake/modules/FindFFMPEG.cmake:128 (add_library):
  add_library cannot create imported target "ffmpeg::libavcodec" because
  another target with the same name already exists.
Call Stack (most recent call first):
  cmake/modules/FindFFMPEG.cmake:381 (buildFFMPEG)
  cmake/scripts/common/Macros.cmake:388 (find_package)
  cmake/scripts/common/Macros.cmake:402 (find_package_with_ver)
  CMakeLists.txt:257 (core_require_dep)
```

**Comment by garbear** [comment]
I have ffmpeg 4 installed:

```
$ apt-cache show ffmpeg
Package: ffmpeg
Architecture: amd64
Version: 7:4.4.2-0ubuntu0.22.04.1
```

**Comment by popcornmix** [comment]
I've just hit this on RPiOS bookworm.
Build is okay on Nexus branch, but fails on master. Same error:

```
add_library cannot create imported target "ffmpeg::libavcodec" because
  another target with the same name already exists.
```

Switching to ```-DENABLE_INTERNAL_FFMPEG=ON``` avoids the error.
