### ISSUE TITLE
RSS Ticker fails on builds after v21.0a2-Omega

### ISSUE THREAD

**Issue by kuraikaze** [xbmc/xbmc#24229]
### Describe the bug

RSS Ticker no longer displays along bottom of Kodi window.

## Expected Behavior

Scrolling display of items from RSS feed sources.

## Actual Behavior

According to debug log feed URLs are seemingly fetched by Kodi, but fail to display silently with no further log entries until the idle connection is closed after a while.

## Possible Fix

Issue seems likely to relate to commit for migration of RSS Ticker functions to tinyxml2:-
[https://github.com/xbmc/xbmc/commit/fe6a7b1ed0de937b0b39c7c756dec0ab8c04f6a6](url)

Parent commit for TinyXML2 introduction:-
[https://github.com/xbmc/xbmc/commit/9e983ed0449aaf3007d8bfa3261056b120d84188](url)

Commit 9e983ed mentions that "Currently tinyxml2 and 1 can coexist peacefully" - perhaps revert the RSS Ticker files to use tinyxml1 ?

### To Reproduce

1.  Install a Kodi build later than v21.0a2-Omega
2.  In Settings/Interface activate "Show RSS news feeds"
3.  Have a set of valid RSS feeds in Kodi/userdata/RssFeeds.xml
 
### Debuglog

The debuglog can be found here: [kodi.log debuglog](https://gist.github.com/kuraikaze/f93048a5f2f5c7ab4ae5317781274325)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [*] Linux
 - [ ] macOS
 - [*] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.0-beta2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
Will be fixed with #24231.
