### ISSUE TITLE
put display to sleep power saving as well as "turn off" add-on do not work on googletv

### ISSUE THREAD

**Issue by usemore** [xbmc/xbmc#24233]
### Describe the bug
Here is a clear and concise description of what the problem is:

ever since receiving my hisense googletv, i've noticed that kodi is unable to put the display to sleep. i'm running nightly development releases of v.21 arm7a.

other apps such as "android settings" or "smart tube" will allow the system sleep timeout to shut off my tv, _but kodi_, if running, prevents it and cannot turn off the display itself. i've tried disabling kodi's wake_lock permission to no avail.

devices such as the firestick4k connected via hdmi can also turn the display off and on via cec (using the power button), but kodi, whether running on the firestick or directly on the tv seems to have no such communication with android. i've even tried all the various settings under the "turn off" add-on, which lets you hit "preview"..nothing ever happens.

..possibly i have messed up a permission somewhere, or disabled the wrong apk? but seeing as how other apps at least allow the system time-out to function, i think there's something up with kodi. 

the result is my tv is on pointlessly for hours when it should turn itself off

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

tv should power off according to kodi's settings

## Actual Behavior

kodi does not power off the tv, and prevents the android system idle from doing the same

## Possible Fix

remove kodi wake-locks and allow system idle to handle power management

### To Reproduce

1. turn on googletv, set kodi to turn off display in 5 mins.
2. wait far more than 5 mins while nothing happens
3. despair

### Debuglog

The debuglog can be found here:

i'm not sure what to debug or how to do it, please provide a step-by-step  overview so that i can retrieve the logs you'd like

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android 12 GoogleTV (Hisense)
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: kodi-20231212-74ed1613-master-armeabi-v7a.apk

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by usemore** [comment]
additionally, not sure how the "turn off" screensaver add-on sends keycodes, but if it sent keycode 26 via adb, i believe it would work right

**Comment by sarbes** [comment]
No response from OP.
