### ISSUE TITLE
smb: Directory Listings still take hours - and there's been a simple fix for years.

### ISSUE THREAD

**Issue by KyleSanderson** [xbmc/xbmc#24236]
### Describe the bug
Here is a clear and concise description of what the problem is:
smb.IsSmbValid
for(all): smbc_readdir
smbc_closedir
smb.IsSmbValid
for(all): smbc_stat
for(all): smbc_getxattr

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
smb.IsSmbValid
for(all): smbc_readdirplus2
smbc_closedir

## Actual Behavior
Terrible performance.

## Possible Fix
smbc_readdirplus2

### To Reproduce
1. Add a smb source with a trivial 8k directories.
2. Wait 4 hours for the listing to return.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
https://gitlab.gnome.org/GNOME/gvfs/-/merge_requests/63

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] tvOS
 - [x] Linux
 - [x] macOS
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version: Omega B2.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KyleSanderson** [comment]
@neo1973 are you looking for line numbers? Based on the previous attempts to merge even 6 lines of code and that being rejected out of spite i really didn't want to setup the entire tool chain for this again.

**Comment by neo1973** [comment]
No, I think I understand the code change you are suggesting (and it looks like a good idea to me) but 4 hours for a directory listings sounds long even taking the non optimal functions into account. So a debug log would be interesting just to see if something else additionally is going on.

**Comment by KyleSanderson** [comment]
> No, I think I understand the code change you are suggesting (and it looks like a good idea to me) but 4 hours for a directory listings sounds long even taking the non optimal functions into account. So a debug log would be interesting just to see if something else additionally is going on.

It takes about 30s to ls the directory locally on the box (it's sharded content). With Kodi it takes 4 hours with stat on, and about 8 minutes with stat off. It takes around 36 hours to index with Kodi today. There's about 20ms between the player and server (so 60ms per item).

A lot of it from the previous investigations was the Bluray / DVD support, which injects another 300-500ms per item at the very least (.nomedia, .nfo, bdinfo, etc). A upper layer cache and just reading the contents on Exists and caching them for 30s/1m would be the path forward here (it feels heavier, but it isn't really), but it's way more effort than the proposed immediate change.

first report (a year and a half ago) here: https://github.com/xbmc/xbmc/issues/21408

**Comment by neo1973** [comment]
Sorry, but what are these numbers? A recursive `ls` on my NAS over 1250 dirs / 10200 files takes 34ms locally and 5.5s when mounted over the network. With "ls the directory locally" do you really mean running the `ls` command? And does it take 30s for the single directory or is it a recursive `ls` over a way larger number of dirs?

**Comment by KyleSanderson** [comment]
> Sorry, but what are these numbers? A recursive `ls` on my NAS over 1250 dirs / 10200 files takes 34ms locally and 5.5s when mounted over the network. With "ls the directory locally" do you really mean running the `ls` command? And does it take 30s for the single directory or is it a recursive `ls` over a way larger number of dirs?

I'm using toy filesystems (mergerfs, and rar2fs) which are bind mounted a couple times as well. It's fast enough to read and write at over 100MB/s with 64kb r/w, but the syscall context switches can be brutal. Once the inodes are warm (in the page cache) a full `ls -la` takes 100ms locally. Anyway, red herring - each Exists call is a full network round trip which would be avoided with that cache.

**Comment by thexai** [comment]
> there's been a simple fix for years. 

Open a PR then.

If you want open a issue then we hope to be able to see a **debug log** showing that it takes hours to obtain a directory.

Debug logs are mandatory to open issues.

**Comment by KyleSanderson** [comment]
> > there's been a simple fix for years.
> 
> Open a PR then.
> 
> If you want open a issue then we hope to be able to see a **debug log** showing that it takes hours to obtain a directory.
> 
> Debug logs are mandatory to open issues.

Wow. Simply amazing. Thank you.
