### ISSUE TITLE
Video Versions: several issues with the new feature

### ISSUE THREAD

**Issue by Ch1llb0** [xbmc/xbmc#24245]
### Describe the bug
Here is a clear and concise description of what the problem is:

The new video version dialog shows several issues on my test setup that I use for skinng work which all look like this feature is not yet ready for release.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

- the "set default" button should be functional as soon as more than one version is present in the versions list
- the "remove" button should be functional
- the extras rename selection dialog should contain items specific to extras, same as the wording of the window heading and its buttons
- the thumb/poster fanart should stay visible no matter what you do in the versions/extras dialog

## Actual Behavior

- the "set default" button is always disabled
- the "remove" button is always disabled
- the selection dialog when selecting "rename" on extras shows exactly the same content and the rename list for versions - down to the heading and the "add more versions" button which also show "versions" and not "extras"
- after closing the rename dialog, the thumb or poster art vanishes for all items in the versions or extras list until the dialog is reopened

### To Reproduce

1. Open the versions dialog for a movie that has several versions and/or extras
2. Try and rename a version or an extras item
3. Close the extras rename dialog and look out for the thumb/poster fanart
4. Try and set a version as default - try using the respective "set default" button

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/jewekihope.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

The versions dialog with "set default" and "remove" disabled (no matter which version is highlighted!):
![screenshot00000](https://github.com/xbmc/xbmc/assets/36623079/b1d48b82-6312-48b3-b5fc-72c62371ea97)

The rename dialog for extras showing exactly the same content as the version rename dialog:
![screenshot00001](https://github.com/xbmc/xbmc/assets/36623079/13e5da07-1ba9-4b12-8de7-2a554d2f1d87)

The versions dialog after closing the rename dialog without having renamed anything (just opening and closing the rename dialog), suddenly not showing any thumb/poster fanart:
![screenshot00002](https://github.com/xbmc/xbmc/assets/36623079/cbc27a4c-5e82-4cb7-9eb9-110a7a902c3a)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10, 22H2
 - Kodi version: Omega v21, Beta 2

**Comment by xodidox** [comment]
> the "set default" button is always disabled
> the "remove" button is always disabled

These buttons need a selected version/extras to work. Highlight is not a selection with current design, a click is needed. They are disabled on purpose for the scenarios you mentioned.

> after closing the rename dialog, the thumb or poster art vanishes for all items in the versions or extras list until the dialog is reopened

This will be fixed with PR https://github.com/xbmc/xbmc/pull/24148

> the selection dialog when selecting "rename" on extras shows exactly the same content and the rename list for versions - down to the heading and the "add more versions" button which also show "versions" and not "extras"

This is a known issue; it will be fixed after PR https://github.com/xbmc/xbmc/pull/24148 merged. This PR has some changes that affect how the future fixes will work.

**Comment by Ch1llb0** [comment]
> These buttons need a selected version/extras to work. Highlight is not a selection with current design, a click is needed. When opening the dialog, the default version is selected automatically, you cannot "set default" or "remove" the default version, thus they are disabled.

Oh, I did indeed not try to select an item. Good to know, will test 👍🏻 

> This will be fixed with PR #24148

Perfect, thank you!

**Comment by ksooo** [comment]
> the "set default" button should be functional as soon as more than one version is present in the versions list
> the "remove" button should be functional

 Will be fixed with #24316 

> the extras rename selection dialog should contain items specific to extras, same as the wording of the window heading and its buttons

 Still open.
 
> the thumb/poster fanart should stay visible no matter what you do in the versions/extras dialog

 Was fixed with #24282

**Comment by ksooo** [comment]
All issues mentioned here are now fixed.

**Comment by ksooo** [comment]
> the extras rename selection dialog should contain items specific to extras, same as the wording of the window heading and its buttons

Fixed with #24340

**Comment by ksooo** [comment]
> same as the wording of the window heading and its buttons

"Fixing" the labels is still a todo

**Comment by Ch1llb0** [comment]
Thank you for all the work! 🙏🏻
