### ISSUE TITLE
WebOS - Power Menu does not turn off TV

### ISSUE THREAD

**Issue by ca0ss** [xbmc/xbmc#24240]
### Describe the bug
Here is a clear and concise description of what the problem is:
When you select "Turn off the system" on the power menu,  the app simply quit leaving tv turned on instead of turn it off.

TV LG 55UP75006LF

### To Reproduce
1.  Open power menu
2.  Select "Turn off the system" according to your language

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [X] WebOS

 - Operating system version/name:
 - Kodi version: 21.0-Beta2 (20.90.821), 
 - GIT 20231210-979dbf5fe5 compiled 2023-12-09
 - WebOS TV 6.3.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sundermann** [comment]
@ca0ss Please the shutdown/reboot buttons work as intended once the build servers have built the proposed fix

**Comment by sundermann** [comment]
@ca0ss Have you had a chance to try the test build?

**Comment by ca0ss** [comment]
org.xbmc.kodi_20231218-735f8728-master_arm.ipk is this version good?

**Comment by sundermann** [comment]
No, that's master build. You need to check the builds from the pull request linked with this PR. You can grab it [here](https://jenkins.kodi.tv/job/webos-docker/2832/)

**Comment by ca0ss** [comment]
i try it upgrading from "old" b2 version, not uninstalling. the problem still there

**Comment by ca0ss** [comment]
Today was an intense day, can you link me a guide how to do a debug log? Tomorrow i will do :)

**Comment by sundermann** [comment]
It's described [here ](https://kodi.wiki/view/Log_file/Easy)

If you do not use the addon to upload the log file, you can find it at `/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/temp/kodi.log`

**Comment by ca0ss** [comment]
Thx for the reply, tomorrow i will publish the log. I sent you an email, probably i will open a new issue bc I manage to crash the app just using 2 remote. You have the video on the email :)

**Comment by ca0ss** [comment]
[Kodi LOG.zip](https://github.com/xbmc/xbmc/files/13759010/Kodi.LOG.zip)
Attached a zip with 2 different log, one for power off and one for reboot.
in all cases, the app just close

**Comment by sundermann** [comment]
What happens if you execute `luna-send -n 1 luna://com.webos.service.tvpower/power/powerOff '{"reason":"remoteKey"}'
` on the TV?

**Comment by ca0ss** [comment]
tv power off. i try while kody was playing

**Comment by sundermann** [comment]
Let's see start `ls-monitor -f com.webos.service.tvpower` then press the shut down button in kodi. Does something show up there?

**Comment by ca0ss** [comment]
> Let's see start `ls-monitor -f com.webos.service.tvpower` then press the shut down button in kodi. Does something show up there?

![image](https://github.com/xbmc/xbmc/assets/30020955/930df68a-811a-4f9e-9fb3-2d3039b3a8d1)
I cannot copy the text, sorry :) there is more text

**Comment by ca0ss** [comment]
![image](https://github.com/xbmc/xbmc/assets/30020955/d42cc89a-adde-40a8-8245-62e375592446)

**Comment by ca0ss** [comment]
![image](https://github.com/xbmc/xbmc/assets/30020955/a2f466d4-625c-480f-8398-78b6fef237d2)

**Comment by sundermann** [comment]
Try grepping for ´powerOff´: `ls-monitor -f com.webos.service.tvpower | grep powerOff`

**Comment by ca0ss** [comment]
> ls-monitor -f com.webos.service.tvpower | grep powerOff

![image](https://github.com/xbmc/xbmc/assets/30020955/7400a8fa-112c-4ac5-9f02-1c534c373cd2)

**Comment by sundermann** [comment]
Can you try [this](https://jenkins.kodi.tv/job/webos-docker/2865/) build which adds an additional delay before exiting the application

**Comment by ca0ss** [comment]
> Can you try [this](https://jenkins.kodi.tv/job/webos-docker/2865/) build which adds an additional delay before exiting the application

the problem still there, here is the log:
[kodi updated log.zip](https://github.com/xbmc/xbmc/files/13759419/kodi.updated.log.zip)

**Comment by sundermann** [comment]
[This](https://jenkins.kodi.tv/job/webos-docker/2869/) build logs the response message and hopefully gives some insight into what's going on.

**Comment by sundermann** [comment]
Can you additionally try what happens if you execute `luna-send -n 1 luna://com.webos.service.tvpower/power2/powerOff '{"reason":"remoteKey"}'`

**Comment by ca0ss** [comment]
> luna-send -n 1 luna://com.webos.service.tvpower/power2/powerOff '{"reason":"remoteKey"}'

root@LGwebOSTV:~# luna-send -n 1 luna://com.webos.service.tvpower/power2/powerOff '{"reason":"remoteKey"}'
{"returnValue":false,"errorCode":-1,"errorText":"Unknown method \"powerOff\" for category \"/power2\""}
root@LGwebOSTV:~#

**Comment by ca0ss** [comment]
> [This](https://jenkins.kodi.tv/job/webos-docker/2869/) build logs the response message and hopefully gives some insight into what's going on.

[kodi update 2.zip](https://github.com/xbmc/xbmc/files/13759729/kodi.update.2.zip)

same thing of other times

**Comment by sundermann** [comment]
Let's hope [this](https://jenkins.kodi.tv/job/webos-docker/2871/) build works now

**Comment by ca0ss** [comment]
> Let's hope [this](https://jenkins.kodi.tv/job/webos-docker/2871/) build works now

[kodi update 3.zip](https://github.com/xbmc/xbmc/files/13759829/kodi.update.3.zip)

does not turn off :(

**Comment by ca0ss** [comment]
> It seems that the `power2` endpoint is only available from webOS 7+. However, the older? `power` endpoint still works

My tv have WebOS 6.3.3

**Comment by sundermann** [comment]
Try [this](https://jenkins.kodi.tv/job/webos-docker/2886/) build please. The last one apparently did not have the changes for the luna endpoint

**Comment by ca0ss** [comment]
> Try [this](https://jenkins.kodi.tv/job/webos-docker/2886/) build please. The last one apparently did not have the changes for the luna endpoint

Now it's working, the reboot and power off :)
thx
