### ISSUE TITLE
Label alignment: right align doesn't work as expected

### ISSUE THREAD

**Issue by Ch1llb0** [xbmc/xbmc#24246]
### Describe the bug
Here is a clear and concise description of what the problem is:

The x axis label alignment tag is not interpreted as expected anymore - this used to work just fine with Nexus v20.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

- when adding e.g. an `<align>right</align>` tag to any label control, it's expected to then render the label text according to this tag (as it worked up until Nexus v20)

## Actual Behavior

- the align tag is not ignored, but interpreted in a weird way: with an `<align>right</align>` tag in a fade label control the text is rendered close to the right edge of the control expanding to the right, not aligned to the right expanding to the left - see screenshots

### To Reproduce

1. Create a fade label control (label controls supposedly show the same issue as per @manfeed)
2. Add a `<align>right</align>` tag to the control, something like this (used for the top text in the video info dialog list in the attached screenshots):

```xml
<control type="fadelabel">
   <width>200</width>
   <height>36</height>
   <align>right</align>
   <font>Font36</font>
   <label>557</label>
   <textcolor>$VAR[TextColorNF]</textcolor>
</control>
```

3. Look at the result

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/azizunagaf.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Expected behaviour (Nexus v20):
![Jpyia5Y](https://github.com/xbmc/xbmc/assets/36623079/9eb50baf-376b-4de3-a96a-8acf88081858)

Actual behaviour (Omega v21 Beta 2):
![XyIRlUc](https://github.com/xbmc/xbmc/assets/36623079/aa67b69f-1162-4326-89cf-33d0a4f45f12)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 22H2
 - Kodi version: Omega v21, Beta 2

**Comment by manfeed** [comment]
In my case this is the issue:

![screenshot00000](https://github.com/xbmc/xbmc/assets/13109584/a7098e28-440f-47b6-ae12-2d684b9bcfa7)

The textbox control (that in Nexus worked perfectly) uses align right too and it's:

`<label>[B]$VAR[value_ground17_label]:[/B] [COLOR=FFFFFAF0]$VAR[value_ground17_value][/COLOR]    [B]$VAR[value_ground14_label]: [/B][COLOR=FFFFFAF0]$VAR[value_ground14_value][/COLOR]   [CR]$VAR[Seasons_Year_Label]  </label>`

I think the issue might be similar to what @mikeSILVO describes in this thread:

https://forum.kodi.tv/showthread.php?tid=375389

**Comment by neo1973** [comment]
It looks like the issue is caused by #22691, if I revert this PR rendering is fine again.

@CastagnaIT: If you find the time maybe you can give it a look?

**Comment by CastagnaIT** [comment]
i will see to find time to try investigate on next weeks
could be something missing in `fadelabel` that in my old PR has not been tested

but about comment above https://github.com/xbmc/xbmc/issues/24246#issuecomment-1858518456 that problem exists from Kodi 20 its not the same issue

**Comment by manfeed** [comment]
I have no idea whether my issue is due to the same reason or not, but what I do know is that it has appeared in Omega, in Nexus there was no such problem.

**Comment by neo1973** [comment]
@manfeed: Which skin is the one from your screenshot?

**Comment by manfeed** [comment]
Aeon Tajo. There are other places where the same happens, RightList view when browsing music and many other places more, always with labels with align to the right.

**Comment by neo1973** [comment]
> but about comment above https://github.com/xbmc/xbmc/issues/24246#issuecomment-1858518456 that problem exists from Kodi 20 its not the same issue

I don't know if it existed in Kodi 20 but when #22691 is reverted it displays correctly in Omega

**Comment by jurialmunkey** [comment]
> I don't know if it existed in Kodi 20 but when https://github.com/xbmc/xbmc/pull/22691 is reverted it displays correctly in Omega

As an example from Kodi 20, here is an issue I reported about RTL languages being cut-off on the right edge which was made before that PR even existed: https://github.com/xbmc/xbmc/issues/22547

I was also able to reproduce that issue on builds of Nexus from early 2022, so it has existed for some time. The PR definitely makes it occur more frequently / more obvious, but there seems to be some deeper pre-existing issue with how text width is calculated.

**Comment by scott967** [comment]
This might be noise, but have anyone tested right align with <right></right> placement?  I had problems but assumed I didn't understand proper use.

**Comment by jurialmunkey** [comment]
> This might be noise, but have anyone tested right align with right placement? I had problems but assumed I didn't understand proper use.

@scott967 - As in with `<posx>100r</posx>` old style label alignment? Or as in `<right>100</right>` new style?

**Comment by scott967** [comment]
New style.  After complete find/replace of `<posx>` with `<left>/<right>`  had layout issues with `<align>right</align>` but again it might be my mistake -- just if PR gets made could it be tested.

**Comment by Ch1llb0** [comment]
I had tested this as I was wondering whether something might've changed: It doesn't work no matter where you align the control. It's "just" the align tag that's not properly honored.

**Comment by CastagnaIT** [comment]
i made a fix
@Ch1llb0 if i provide you a kodi test build for Windows are you able to give a feedback?

**Comment by Ch1llb0** [comment]
Yup, sure. 👍🏼

**Comment by CastagnaIT** [comment]
here
Win64: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20231218-f3fa961a-fix_fadelabel-x64.exe

**Comment by Ch1llb0** [comment]
Looks good here:

![screenshot00000](https://github.com/xbmc/xbmc/assets/36623079/3bf9bfb5-6c2f-4b79-a8d2-5ca77482d20c)

**Comment by Ch1llb0** [comment]
Thank you, @CastagnaIT! 😊
