### ISSUE TITLE
IPTV playback problem

### ISSUE THREAD

**Issue by wuniversales** [xbmc/xbmc#24250]
## Bug report
The player stops at any time using the following IPTV list.
https://i.mjh.nz/PlutoTV/es-kodi.m3u8

### Describe the bug
Assuming that the IPTV Simple PVR plugin is active and configurated using the IPTV list.

1- Play the channel Tuning.
2- Wait for any commercial break.
3- The player freezes.

## Expected Behavior
Work!!!

## Actual Behavior
The image and sound freezes.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 11 and 13
 - Kodi version: 
20.2

**Comment by CastagnaIT** [comment]
please attach the debug log

**Comment by CastagnaIT** [comment]
testing some channels on provided playlist with ISAdaptive
i noticed the specified behaviour, this cannot be fixed on Kodi 20, but i have now fixed it on Kodi 21 that will be available from the next release
so i close the issue
