### ISSUE TITLE
thexai has a personal vendetta against me? lol.

### ISSUE THREAD

**Issue by KyleSanderson** [xbmc/xbmc#24251]
Who is this guy.

https://github.com/xbmc/xbmc/issues/24238#issuecomment-1858917075
https://github.com/xbmc/xbmc/issues/24236#issuecomment-1858917863
https://github.com/xbmc/xbmc/issues/22701#issuecomment-1858922604

### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] tvOS
 - [x] Linux
 - [x] macOS
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MikeSiLVO** [comment]
Just post a debug log 🤷‍♂️
