### ISSUE TITLE
Issue Migrating Videos DB v122 to v124 - MySQL

### ISSUE THREAD

**Issue by smf007** [xbmc/xbmc#24264]
### Describe the bug
Here is a clear and concise description of what the problem is:

Migration of a MySql videos db v122 to v124 fails in error.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video DB to migrate without error

### To Reproduce

1. Have you videos DB in MySQL v 8.0.35
2. Migrate from videos DB v122 to v124

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/nomubudica.kodi

Key item being
2023-12-17 17:45:14.293 T:886     debug <general>: Mysql execute: CREATE INDEX ix_movie_title ON movie (c00)
2023-12-17 17:45:14.294 T:886     error <general>: SQL: [MyVideos124] Undefined MySQL error: Code (1170)
                                                   Query: CREATE INDEX ix_movie_title ON movie (c00)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Related to either #24183 (v124 bump) or #14972 (v123 bump).

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Nightlies of LibreElec v12

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CrystalP** [comment]
This is a known issue, PR #24226 will fix.
Until then you can delete the video db 124 and use the official beta2.

**Comment by smf007** [comment]
Ah, yes.  My bad.  I had seen that last week but mistakenly thought that it had already been merged.  I also missed the additional bump of Kodi that LibreElec had performed, so they had moved beyond Beta2 already.
