### ISSUE TITLE
Alignment to the right of labels is wrong when BOLD style is used

### ISSUE THREAD

**Issue by manfeed** [xbmc/xbmc#24276]
### Describe the bug

Every label in OMEGA aligned to the right and using BOLD font style gets cut on the right. The recent fix for fadelabels (https://github.com/xbmc/xbmc/issues/24246) doesn't fix this issue, so I assume it must be a different problem.

## Expected Behavior

Labels aligned to the right and using BOLD style should be showed correctly, like in Nexus and previous versions.

## Actual Behavior

Every label in OMEGA aligned to the right and using BOLD font style gets cut on the right. For instance a label aligned to the right like: 
`<label>[B]$LOCALIZE[14087]: [/B][COLOR=FFFFFFFF]$INFO[Container(5969).NumItems][/COLOR] $INFO[ListItem.Property(Album_Duration),[B]   $LOCALIZE[180]: [/B][COLOR=FFFFFFFF],[/COLOR]]</label>`

To test, if I remove the [B] attribute, this line is showed correctly.

## Possible Fix

It's as if the lenght of the line is calculated without taking into account that when BOLD style is used the line is longer, so Kodi uses a wrong starting point for the label and it gets cut to the right.

### To Reproduce

1. Use any skin that has labels aligned to the right using BOLD style (I tested Aeon Tajo and Aeon Nox Silvo)
2. Go to any screen that shows those lines (for instance RightList view for albums in Aeon Tajo, or System in Aeon Nox Silvo)

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![screenshot00000](https://github.com/xbmc/xbmc/assets/13109584/bab80e6f-b6f9-4b48-ba69-292dc0030878)

![screenshot00002](https://github.com/xbmc/xbmc/assets/13109584/b3ba1349-7082-4030-85e3-d4317f7809c8)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Any Omega version, I even tested the nightly build for 2023-Dec-19 [KodiSetup-20231218-735f8728-master-x64.exe]

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
thanks for the details i found the malicious code, the fix is on the way
