### ISSUE TITLE
Naming of version-related buttons in context menu

### ISSUE THREAD

**Issue by CrystalP** [xbmc/xbmc#24294]
### Describe the bug

In context menu Manage, for a movie that doesn't have versions:
![image](https://github.com/xbmc/xbmc/assets/489377/57eea128-6a11-4bdb-87d0-e9bae656c168)

In context menu Manage, for a movie that has versions:
![image](https://github.com/xbmc/xbmc/assets/489377/6b0ceaf4-43e9-4b31-a26e-3a6e8532df03)

The circled text doesn't look like good english to me.

In addition it also seems that using a variable for "movie" in messages make things difficult for translation because it would need different translations in the different context where "movie" appears (#translations-external Slack channel)

## Possible Fix

Proposal:

"Convert {0:s} version" > "Convert to version"
"Manage {0:s} version" > "Manage versions"

It seems to me that the context menu is opened in the context of the movie library, "movie" doesn't need to be repeated and we don't have any other type of versions.
Even in the future if TV shows or episode versions are added, the word "show" or "episode won't be needed in the context menu button.

Q: can the existing messages id 40001and 40021 be changed, or are new ids needed?

I can do the PR.

### To Reproduce

1. Open movie libraray
2. Open context menu on a movie > Manage

### Debuglog

The debuglog can be found here:
Not relevant, here to make the bot happy: https://paste.kodi.tv/iyocugivig.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: current master after v21 beta 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by the-black-eagle** [comment]
The English is fine, although I think that `Convert movie version` might well be `Convert to movie version`. 
>It seems to me that the context menu is opened in the context of the movie library, "movie" doesn't need to be repeated and we don't have any other type of versions.

That is the same though as "Manage movie set", so there is already precedence for the naming, although I do agree to a certain extent that "movie" is possibly extraneous.  However, if I threw up the context menu, left it visible but went off to do something else (answer the door, call of nature, whatever...) and then came back, the "movie" bit might be quite helpful.

Also, the music library has "query info for all albums/artists" depending if you call the context menu on an artist or album.  By your thinking, this would just be "Query all info" as I should already know in what context I have called it.

Although I _would_ know that, I think it's perfectly acceptable for the context menu to actually qualify the context in which it has been called.  It's clear and unambiguous and leaves the user in no doubt as to what they are doing.  In my view, a context menu that just says "Add Extra" or "Add version" does nothing to tell me if it's a TV show, a music video or a movie.

**Comment by CrystalP** [comment]
I don't mind "movie" in the messages,  I understand that it provide more context. It will mean separate messages when/if tv versions are implemented, to respect the feedback from translations.

The second change is about the plural form of version. With "movie" still in the message, it would be
Manage {0:s} version => Manage movie versions

**Comment by the-black-eagle** [comment]
Ha, that really does depend upon context.

`Manage movie version` would to me indicate that we can change the version of just that particular movie.
`Manage movie versions` would indicate to me that there are multiple versions already that we can change / manage.  In your second screenshot that would be more correct (versions vs version).

Can't comment about translations but most other stuff seems to be translated OK.

**Comment by ksooo** [comment]
`Convert movie version` is something that from user's perspective should go away complete. The string expresses, what internally is done, but this is not of concern for the end user. For the end user, this is adding the second version to a single-version movie. This should just happen from the manage video versions dialog, but as I understand the code, it does not work this way. Here implementation details are exposed to the GUI.

`Manage video version` should be renamed to `Mange video versions`. Again, an implementation detail is exposed to the GUI. There are also other places where this currently happens.

To conclude: we should extend the manage video versions dialog to be able to handle also single-version movies, then from user's POV live will be easier/consistent.

**Comment by ksooo** [comment]
> "Convert {0:s} version" > "Convert to version"
> "Manage {0:s} version" > "Manage versions"

This is a good proposal. Until the manage dialog has been extended we should go with this. I will put this into https://github.com/xbmc/xbmc/pull/24302, where I also will do some other first string cleanup.
