### ISSUE TITLE
[Video Versions] Artwork disappears when stopping video that's playing in the background

### ISSUE THREAD

**Issue by Hitcher** [xbmc/xbmc#24300]
### Describe the bug
Here is a clear and concise description of what the problem is:

Poster and fanart become empty if a version is stopped while playing in the background.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Poster and fanart should not be affected when a version is stopped while playing in the background.

## Actual Behavior

Poster and fanart become empty if a version is stopped while playing in the background.

### To Reproduce

1. Select and play a version
2. Back out to the movie list so video is playing in the background
3. Stop the movie

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/ribegafeli.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

![screenshot00000](https://github.com/xbmc/xbmc/assets/133808/880a1eef-37c3-48b5-998f-af2a3a3c7722)

![screenshot00001](https://github.com/xbmc/xbmc/assets/133808/973b5cf0-d285-4639-9a6f-6e1e724d07b8)

![screenshot00002](https://github.com/xbmc/xbmc/assets/133808/a1ad4772-0fd2-434e-9ac1-288091c0fbcc)

![screenshot00003](https://github.com/xbmc/xbmc/assets/133808/82da92c1-296b-4108-a4f7-42ef1584ba78)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: KodiSetup-20231220-2ddc40a2-master-x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Confirming the issue.

**Comment by HitcherUK** [comment]
Further tests have even had it use the currently playing version's artwork instead of the default one.
