### ISSUE TITLE
jellyfin同步过去的webdav地址URL不能别识别

### ISSUE THREAD

**Issue by J666Z** [xbmc/xbmc#24306]
jellyfin共享文件夹同步过去的webdav地址不能别识别，如http://192.168.1.1:8080/中文 （2012），kodi的jellyfin本地路径插件不能识别，对比直接用webdav识别扫描入库，看文件的path是http://192.168.1.1:8080/%E4%B8%AD%E6%96%87%20%EF%BC%882012%EF%BC%89，但是提示的时候是中文这个文件不能识别，URL地址同步没实现，请问有其他办法吗

**Comment by chewitt** [comment]
This is a bug tracker so please post general support questions to https://forum.kodi.tv - There are more likely to be Chinese speakers there too. Thanks.
