### ISSUE TITLE
IPTV resume at same chanel when temporary problem

### ISSUE THREAD

**Issue by alphaonex86** [xbmc/xbmc#24308]
### Describe the bug
Here is a clear and concise description of what the problem is:

Sometime the stream source have problem, the IPTV simple plugin leave me from stream and have to enter again to resume the watching.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

-     stream problem
-     show waiting screen
-     retry in background
-     when up again then play the stream

## Actual Behavior

Just close and return to the menu

## Possible Fix
Retry chanel in loop

### To Reproduce

1.  Install IPTV simple client
2. Play a stream from IPTV server (HLS here)
3. Stop the IPTV server
4. wait 60s
5. Start IPTV server

### Debuglog

The debuglog can be found here: No needed

### Screenshots
Here are some links or screenshots to help explain the problem: Not needed

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

It's particularly useful when parents lets their young child with a stream playing.
It's more than 2000 customers affected here.
vlc work as excepted with option "loop one" button on main interface
When the IPTV server is rebooting the temp m3u8 change the url and the old url return 404 not found
I use https://www.cesbo.com/
I wrongly open issue to https://github.com/kodi-pvr/pvr.iptvsimple/issues/819

### Your Environment
Used Operating system:

 - [*] Android
 - [*] Linux

 - Operating system version/name:
 - Kodi version: 20.2 android, 20.1 Linux

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by alphaonex86** [comment]
Template fixed adding not needed infos

**Comment by sarbes** [comment]
You have to adhere to the template if you want to have an issue fixed. The debug log is missing.

But anyway, Kodi seems to behave like RFC 8216 (https://datatracker.ietf.org/doc/html/rfc8216) describes "end of stream" events. To quote: 
```
If the server wishes to remove an entire presentation, it SHOULD
provide a clear indication to clients that the Playlist file is no
longer available (e.g., with an HTTP 404 or 410 response).  It MUST
ensure that all Media Segments in the Playlist file remain available
to clients for at least the duration of the Playlist file at the time
of removal to prevent interruption of in-progress playback.
```

If you want an automatic resume for such situations, that would be a feature request.
