### ISSUE TITLE
WebOS - Dolby Atmos support

### ISSUE THREAD

**Issue by ca0ss** [xbmc/xbmc#24309]
### Describe the bug
Here is a clear and concise description of what the problem is:

When you play a video containing dolby atmos audio in kodi, tv does not show the message, if you play on the integrated player it does

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Trigger the dolby atmos feature when the video played has it

## Actual Behavior

Kodi does not trigger dolby atmos feature of the tv

## Possible Fix

I read somewhere a old Issue about Dolby Vision and that was solved; maybe there is a similar thing to do

### To Reproduce

1.  Download this video https://www.demolandia.net/downloads.html?id=43254366
2. Reproduce to internal player to show Dolby Vision and Dolby Atmos Message
3. Reproduce to Kodi that will show only Dolby Vision Message

### Debuglog

The debuglog can be found here:
[kodi dolby.zip](https://github.com/xbmc/xbmc/files/13759774/kodi.dolby.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Tv message asking to enable Dolby Atmos when detect it on integrated player
![20231223_183320](https://github.com/xbmc/xbmc/assets/30020955/f546e1a5-6517-4c28-a8ca-d777d3ff30e6)

Dolby Vision and Dolby Atmos Message from integrated player:
![20231223_183356](https://github.com/xbmc/xbmc/assets/30020955/226be11a-f442-41f2-b7ba-0dd3a4201049)

Dolby Vision and not Dolby Atmos Message from Kodi
![20231223_183454](https://github.com/xbmc/xbmc/assets/30020955/e0a6255b-b3ef-4a28-9068-5634c22358b6)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [X] WebOS

 - Operating system version/name:
 - Kodi version: 21.0-BETA2 (20.90.821) Git:20231223-6056212a65

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sundermann** [comment]
You are using the ALSA sink which does not passthrough. Only the Starfish sink can passthrough AC3 and EAC3

**Comment by ca0ss** [comment]
Please, can you tell me how to change settings from ALSA Sink to Starfish Sink? :)

**Comment by ca0ss** [comment]
I have enabled passthrough and starfish on system/audio options. All combination of dolby audio does not make dolby atmos message appear. I don't have any audio external output, just integrated speaker dolby enabled

**Comment by sundermann** [comment]
Don't worry about the message. The way the media pipeline is set up with two independant outputs for video and audio makes the message not appear. That does not mean that it's not working though. It's a limitation of LG's UI
