### ISSUE TITLE
Crash on Adding Timer with 'Any Channel' Setting - Kodi 20.2 - MacOS and Android TV

### ISSUE THREAD

**Issue by Spider-netizen** [xbmc/xbmc#24319]
### Describe the bug

I'm experiencing a consistent crash issue on both MacOS and Android TV. I think it started after updating to Kodi 20.2. The problem occurs when adding a timer with the "Channel" set to "Any Channel." Kodi crashes at the moment the reminder should pop up. Upon attempting to reopen Kodi, it crashes every time when the message in the top right-hand corner reads:

> PVR Manager is starting up 50%
> Loading channels from clients

The only way to reopen Kodi, as it seems, is to delete the TV40.db file from the userdata folder (which also deletes all timers).

## Expected Behavior

I expect Kodi to show a reminder when the program starts after setting a timer with the "Channel" set to "Any Channel" and not crash.

## Actual Behavior

Kodi crashes and does not reopen until the TV40.db file is deleted from the userdata folder.

### To Reproduce

1. Open Kodi and go to the TV section.
2. Select a program from the guide and press the context menu button.
3. Select "Add timer" and choose "Any channel" from the options in the "Channel" setting.
4. Confirm the timer settings and exit the menu.
5. Wait for when the reminder should appear. Kodi would crash.
6. Try to reopen Kodi. During the PVR loading messages Kodi would crash.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The issue affects the ability to set timers and receive reminders. I don’t know if it’s related but when setting a timer and choosing channel “Any Channel” is listed twice (at least on Mac).

I find the issue similar to this [one](https://github.com/xbmc/xbmc/issues/20090), but [ksooo](https://github.com/xbmc/xbmc/pull/20091#issuecomment-1869141413) said it's unrelated and asked me to open a new issue.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: MacOS 10.15.7, Android TV
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by phunkyfish** [comment]
Post a full debug log please.

**Comment by Spider-netizen** [comment]
Thanks for the response. I will provide a debug log, but isn't the fact that “Any Channel” is listed twice a starting point to look into? BTW I can confirm the same behaviour with Kodi 21.0, but now it's "TV44.db" that needs to be deleted.

**Comment by phunkyfish** [comment]
Without the details of the addons you have installed and said versions it could be difficult to reproduce, hence the ask to always provide a log.

**Comment by sarbes** [comment]
No log provided.
