### ISSUE TITLE
Canada's short date format is wrong.

### ISSUE THREAD

**Issue by dnfm** [xbmc/xbmc#24320]
I was recently setting up kodi on a new device, and upon seeing "region default format" to Canada, I was surprised to see kodi suggest the short date format was mm/dd/yy.

While our proximity to the US does result in some bleed over, mm/dd/yy is the least common date format used here on anything official.

That said, the Canadian government explicitly suggests iso8601 as the correct short date format in Canada (see https://www.noslangues-ourlanguages.gc.ca/en/writing-tips-plus/date-numeric.html)

**Comment by dnfm** [comment]
The template is wildly unnecessary for this report.

**Comment by scott967** [comment]
Even if template data seems inappropriate for your issue, we require you to complete it to the best of your ability.  I do note that Unicode CLDR ver 44 and ICU (standard implementation) specify en_CA short date as y-MM-dd
https://icu4c-demos.unicode.org/icu-bin/locexp?d_=en&_=en_CA
