### ISSUE TITLE
WebOS - Sync issues.

### ISSUE THREAD

**Issue by Battler624** [xbmc/xbmc#24329]
Kodi 20.90.821, LG WebOS 7.3.1, LG C2 Firmware 3.33.90, Unrooted.

I just updated and noticed pretty much on anything I play there is audio & subtitle sync issues. Audio would be ahead by a few seconds and subtitles usually also ahead sometimes as much as the audio and sometimes not. I do not think i've seen them delayed but i've seen them not display at all.

I have audio passthrough enabled (to enable Dolby Atmos) but the rest is pretty much default. I don't mind resetting if needed.

The videos I've tried playing were mostly movies that included
DV & DA, HDR10 & DA, HDR only, DV Only, and ofcourse regular 1080p30 videos that dont include anything special (non-hdr and non-atmos)
File extensions were mkv & mpv, a good mix of both

**Comment by DrConflict** [comment]
Same issues here on the exact same setup.

**Comment by Zibri** [comment]
yes. I noticed a sync problem, partially solved by using AUDIO PASSTHRU in settings.
I can still see a delay anyway.

**Comment by Battler624** [comment]
> yes. I noticed a sync problem, partially solved by using AUDIO PASSTHRU in settings. I can still see a delay anyway.

For me audio passthrough does nothing regarding delay, i've seen the delay be small and large on different occasions when using it.

**Comment by Battler624** [comment]
Also, as mentioned by the bot, the dev team will probably ignore this, i am unable to follow the template because it doesn't have WebOS in it yet.

**Comment by quietvoid** [comment]
Audio sync is a known issue but it's not easy to solve.
The current recommendation is to enable passthrough and AC-3 transcoding settings., then the sync should be fine.

**Comment by Battler624** [comment]
Can confirm this works but only kinda.

If I seek even a second everything goes outta wack and gotta stop the video and then resume. Close this if you wish void (also thanks for the DV stuff, good shit)

**Comment by quietvoid** [comment]
>If I seek even a second everything goes outta wack and gotta stop the video and then resume.

Most of the time you can wait and it will catch back up.

**Comment by Misenkooo** [comment]
I've found applying delay of -0.275ms helps in most cases. Sometimes KODI does not apply this delay when video starts and I have to rewind it forward and back so the delay is applied. I don't know why but it's not that reliable. Would be great if this can be solved by devs.

**Comment by sundermann** [comment]
We already have an issue for this #24193. There's also some more information in the forum thread how some people managed to fix their audio issues
