### ISSUE TITLE
[Video Versions] When default select is "Show info" user is prompted to select version before information dialog is displayed.

### ISSUE THREAD

**Issue by jurialmunkey** [xbmc/xbmc#24322]
### Describe the bug
Here is a clear and concise description of what the problem is:

When default select action is "Show information", selecting a movie with versions asks user to select a version both before displaying the info dialog and after selecting play in the dialog.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The user should only be asked to select a version once (when attempting playback).

As the info dialog is not specific to the version, the user should not be asked to select a version before displaying the info dialog.

## Actual Behavior

User is asked to select a version before the info dialog is displayed.

### To Reproduce

1. Set default select action to "Show information" and disable playing defaulting version.
2. Click a movie in library with versions
3. Prompt to select a version is displayed.
4. Select a version and info is displayed.
5. Click "Play" in info dialog and asked to select a version again.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/13770058/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Omega v21 nightlies

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
I don't think this issues is resolved.

I have installed... KodiSetup-20240107-caa9d53c-master-x64

When the option... **Default select action** is set to...
**Play**- selecting a movie version to play, the selected version is played
**Information**- selecting a movie version to play, the parent movie plays.

Maybe something broke after the original fix for this was merged?
