### ISSUE TITLE
Kodi Favorite screen will freeze when you are on the last row of favorites and using mouse, often occur via tabbing as well.

### ISSUE THREAD

**Issue by buffalome90210** [xbmc/xbmc#24335]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi Favorite screen will freeze when you are on the last row of favorites and using mouse, often occur via tabbing as well.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Issue occurs on windows 10 64, Kodi builds 20-1 and 20-2, does NOT occur on 20-0. Occurs consistently, Only resolution is to use task manager to end Task Kodi.

## Actual Behavior

Issue occurs on windows 10 64, Kodi builds 20-1 and 20-2, does NOT occur on 20-0. Occurs consistently, Only resolution is to use task manager to end Task Kodi.

## Possible Fix

terminate Kodi via windows task manager

### To Reproduce

1. use Kodi-1 or Kodi-2  DOES NOT OCCUR IN Kodi 20-0
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
Windows 10 x64
 - Operating system version/name:
 - Kodi version:
 - Windows 10 X64. Kodi version 20-1 and 20-2
does not occur 20-0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by buffalome90210** [comment]
In addition I might add that this occurs mostly on favorite screens when displaying thumbnail pictures on favorite screen Occurs on some but not all skins. Consistently occurs on screen Estuary NON Touch version.

**Comment by enen92** [comment]
Mind giving a go to a recent nightly? Favourites had a big rewrite for v21.

**Comment by luzpaz** [comment]
@buffalome90210 :point_up:

**Comment by ksooo** [comment]
This one was fixed long time ago. Don't remember the exact PR though.
