### ISSUE TITLE
Feature request: Ability to catchup live TV seamlessly

### ISSUE THREAD

**Issue by kashaCode** [xbmc/xbmc#24343]
# Feature request 1
I am using the IPTV Simple addon so I posted the feature request on the appropriate Kodi forum: https://forum.kodi.tv/showthread.php?tid=375532

However, the dev of the addon (@phunkyfish) said that Kodi PVR itself would need to be changed first to enable this feature. Therefore, I am recapping the request here. The actual request itself would be implemented by the addon once the infrastructural support has been added by Kodi. So this is a request **only** for the backend infrastructure to enable this.

### Example 
Let's say the guide for a live channel looks like:

```
10:30 Programme A
11:00 Programme B
12:00 Programme C
```
## Actual behavior 
If I select Programme A from the pop-up guide, the programme is played in the video player and the player quits after 30 mins as it reached the end of the programme.

## Expected Behavior
After programme A is finished, Programme B should start playing automatically. Add the ability for IPTV Simple to get the next item on the guide and cue that for playback, so the player doesn't close. This would allow such things as:

1. As a user setting (eg: a checkbox for "Continue playing next programme when finished"). This would make it the default behaviour.
2. A context menu item for individual programmes on the guide (eg: "Play from here onwards").
3. Ability to select multiple guide items to be played one after another.

# Feature request 2

In addition, currently it seems catchup items are played in a separate window from live channels, so the user can't really open the dialog boxes for channels, guide or flip channels with the keyboard. view info with `i` key etc. Ideally, this user interaction would be retained even in catchup mode, so there would be no way to tell whether they were playing catchup TV or live TV, except for some kind of colour indicator to tell the user whether TV is live or catchup.

Possibly would look like this: Instead of playing catchup items in a new window, ability to change video source in the same window. So use live URL for live playback, but catchup URL for seeking function, with common buffer. Say user switches to channel at time t, but wants to step backwards to time t - 10 mins, he could just use the seek bar to do so (seek bar would indicate both date and time I guess).

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 10
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by kashaCode** [comment]
Not a bug report but a feature request. Kindly remove the `ignored rules` tag.

**Comment by the-black-eagle** [comment]
Feature requests should be made on the forum.  This is a bug tracker.
