### ISSUE TITLE
Using master lock will remove all sources on all users for servers like Jellyfin, Emby, Plex, ... + workaround

### ISSUE THREAD

**Issue by Hansie9999** [xbmc/xbmc#24358]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello, I am a programming noob and have no experience on github, so excuses me in advance if I put something wrong here,
I experience this problem with both the Kodi in Libreelec and coreelec, but problem seems to be in kodi itself, I dit NOT have this problem with Kodi 19 (but that might have been a fluke), problem started when I upgraded and clean installed to Kodi 20,
I have multiple users on Kodi that access movie and TV series shares on a Jellyfin (Emby Fork) server, everything works fine, UNTIL I enable the master lock because I want to lock ONE user with a pin code, if I do that ALL shares disapear on ALL users, if I than go to movies or TV series, and click "enable master lock" than my shares work again. Thanks to a friendly user on the KODI forum I have gotten a workaround to fix this. (more about this below)
This also seems to be a problem that has been in Kodi a LONG time with shares from Emby, JellyFin, Plex, ....
[Plex](https://github.com/croneter/PlexKodiConnect/issues/779)
[Emby](https://emby.media/community/index.php?/topic/23065-how-i-solved-the-emby-and-kodi-master-lock-issue/)
[Jellyfin1](https://github.com/jellyfin/jellyfin-kodi/issues/169)
[Jellyfin2](https://github.com/jellyfin/jellyfin-kodi/issues/619)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After enabeling master lock and giving one user a PIN code I should still be able to access ALL my shares on ALL my users they have access to .

## Actual Behavior

The moment I enable master lock , ALL shares disapear on all the users (also shares they should have access to without a pin) and you have to manualy enable them and put the MASTER pin in to access them.

## Possible Fix

Thanks to a very very friendly member on the KODI forum "izprtxqkft" I got it working again.
[profile izprtxqkft](https://forum.kodi.tv/member.php?action=profile&uid=477027)
here you will find our conversation and how he fixed it ;
[kodi forum](https://forum.kodi.tv/showthread.php?tid=372240)

In short , this is the workaround ;
- Install Kodi (libreelec or Coreelec)
- Set Master Lock Code
- Install Jellyfin addon (NO NEED TO CONNECT TO ANY SERVER, OR ADD ANY SOURCES)
- Add new user (you HAVE to select "COPY SOURCES" at creation or it will NOT work)
- Add Jellyfin server and select sources (NOTHING SHOWS UP)
- Add Sources.xml file containing this (this is a specific fix for my Jellyfin, so for Emby or Plex another sources.xml file will be needed)
````
<?xml version="1.0" encoding="utf-8"?>
<sources>
  <video>
    <default pathversion="1"/>
    <source>
      <name>Videos</name>
      <path pathversion="1">/storage/videos/</path>
      <allowsharing>true</allowsharing>
    </source>
    <source>
      <name>TV Shows</name>
      <path pathversion="1">/storage/tvshows/</path>
      <allowsharing>true</allowsharing>
    </source>
    <source>
            <name>jf</name>
            <path pathversion="1">plugin://plugin.video.jellyfin/</path>
            <allowsharing>true</allowsharing>
    </source>
  </video>
  <music>
    <default pathversion="1"/>
    <source>
      <name>Music</name>
      <path pathversion="1">/storage/music/</path>
      <allowsharing>true</allowsharing>
    </source>
  </music>
  <pictures>
    <default pathversion="1"/>
    <source>
      <name>Pictures</name>
      <path pathversion="1">/storage/pictures/</path>
      <allowsharing>true</allowsharing>
    </source>
  </pictures>
</sources>
````

- Reboot

WORKS , instantly have all my movies and series on all the users with or without PIN to access, no need to unlock with master code.

### To Reproduce

1. add extra user
2. set master lock
3. see your sources locked at every login needing to unlock them

### What I think needs to be done,
I think (and I am in NO way a programmer) that Kodi should get a dedicated \sources folder somewhere, and Kodi should read all the files put in there, 
than addons for like Jellyfin, Emby, Plex, .... servers/shares should put there own xml file in that folder at install (like Jellyfin.xml)
at startup Kodi should than read those files and add whatever is in there to its own sources.xml (this way if you have multiple servers they wont overwrite each other settings.
Than probably something will also need to be changed so that you DONT have to make sure that you have to "copy sources" whenever you create a extra user.

I realy hope this can be fixed by someone in the next Kodi versions.

### Debuglog

The debuglog can be found here:  [log](http://ix.io/4pDB)

### Your Environment
Used Operating system:

 - Operating system version/name: Libreelec (but also tryed on box with coreelec)
 - Kodi version: 20
 - running on RaPi4B (but also tried on Amlogic S905x box)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Hansie9999** [comment]
its probably not an error, but can a team member remove the "ignored rules" label, and please tell me what else they need :)

**Comment by 78andyp** [comment]
Hi

I've been looking at profiles.
Can I just clarify the problem exactly - is it that you simply want to pin lock your profile??

Are you using local databases (default) or are you editing `advancedsettings.xml` to point to a remote MySQL database??

Which Jellyfin addon are you using (sorry I've never used it before) - it seems there are 2 - https://jellyfin.org/docs/general/clients/kodi/ - JellyCon and Jellyfin for Kodi??

Thanks

**Comment by 78andyp** [comment]
OK. I think i've reproduced.
Could you try this nexus test build and let me know if it works (ie. jellyfin media not missing after master lock set).
https://file.io/3FyI38WTRUbz
Thanks

**Comment by Hansie9999** [comment]
> Hi
> 
> I've been looking at profiles. Can I just clarify the problem exactly - is it that you simply want to pin lock your profile??
> 
> Are you using local databases (default) or are you editing `advancedsettings.xml` to point to a remote MySQL database??
> 
> Which Jellyfin addon are you using (sorry I've never used it before) - it seems there are 2 - https://jellyfin.org/docs/general/clients/kodi/ - JellyCon and Jellyfin for Kodi??
> 
> Thanks

Sorry for my late answer,

I am indeed on a RP4B running libreelec with kodi, I can pull out another SD card to test any build you want me to.

I use the jellyfin for Kodi addon for full functionality, (but problem has been reported for people using Plex and emby also that I know off)

The main issue is that I have multiple profiles (admin, me, wife, kid 1, kid2) I simply want to PIN lock only my account because if my kids use it by accident they screw up my current episodes that I am watching, 
to be able to PIN lock my own account I must first add a master lock to the administrator user, but the moment I do that, ALL accounts loose access to ANY chares on the jellyfin server, until they also give the master lock PIN, so even when you select to NOT lock shares , they still get locked by the master PIN. and the workaround that was made for me fixed it. (that I linked on the other post)

**Comment by 78andyp** [comment]
Sorry it took so long. I'm a complete linux novice.
I've followed the build instructions and hopefully this will work on a RP.
https://file.io/qLm7NZwjbGoc

**Comment by Hansie9999** [comment]
> Sorry it took so long. I'm a complete linux novice. I've followed the build instructions and hopefully this will work on a RP. https://file.io/qLm7NZwjbGoc

Well I am the real novice here :(

Do I have to compile that BIN file in to an image ?

All the tools I know to use to write an SD card for the RaPi4 needs .img or .iso files :(

Im sorry, im kinda a real noob at all this, if I have to do something special with the .bin first please let me know, if I need to do it on linux thats fine, I have a few linux's running in VM's I can use, sorry I need some extra handholding :(

thanks in advance for the patience

Hans

**Comment by 78andyp** [comment]
Looking at it I think you have to SSH into a LibreELEC RP.
What linux type do you have in a VM - I could try and build a version for that??

**Comment by Hansie9999** [comment]
I should be able to SSH in my Pi running LibreElec, ill make a new SD card with Libreelec, to test,
any pointers in what commands I will need to use to get your .bin file than uploaded to the Kodi on my test SD card ?? 
(like I sayed im a total programming noob)

With the Linux  meant that if I still need to do something with that .bin to get it on my SD card to boot my Pi I could do that in a VM running linux if there is no windows option, but I dont think you meant that (im not running Kodi on a linux)

**Comment by 78andyp** [comment]
Apologies for the delay. I think i've managed to build LibreELEC for RP4 with the patch applied to kodi.
Link - https://file.io/pnw9IMvAxoXa

**Comment by Hansie9999** [comment]
> Apologies for the delay. I think i've managed to build LibreELEC for RP4 with the patch applied to kodi. Link - https://file.io/pnw9IMvAxoXa

Thanks alot,

I will be trying it tonight, when my wife goes to bed and stops hogging MY tv :) :)

**Comment by Hansie9999** [comment]
Hello, wife had a late shift at work, so I was able to try already,

Sorry to report that this build does not fix the problem :(

I boot up, create the new User, install the Jellyfin addon, connect to the server, I get all my movies and series,
go to profile settings, enable lock for the user, it say's to be able to do that you must enable the master lock, 
I enable the master lock, add a pin to my user account, log off, log back on , NO movies or series,
press on my movies/options, press "unlock sources" put in master PIN and movies and series are back :(
(but I have to do this everytime than, even on other users who do NOT have a PIN. so its still the same problem sadly,
this problem was fixed with the workaround I posted on the Kodi forum made by user [izprtxqkft](https://forum.kodi.tv/member.php?action=profile&uid=477027)

Any more help would be appreciated, 

Let me know if you need logs after I do specific things to check out for you,

thank you in advance,

Hans

**Comment by 78andyp** [comment]
Can I just make sure that your lock preferences are the same as below - ie. profile lock but not video lock??
![image](https://github.com/xbmc/xbmc/assets/99039295/44f0d28b-27e2-4468-a5d1-182a976191ff)

**Comment by Hansie9999** [comment]
Yes indeed, the only thing that is locked is the profile itself with a numeric password, nothing else  gets touched.

**Comment by Hansie9999** [comment]
and the problem ALSO exists with other profiles who do NOT have a lock of any kind (not even profile lock) the moment you enable the master lock on the master user, ALL profiles have this problem.

**Comment by 78andyp** [comment]
When you create a profile do you choose Separate or one of the Shares with Default options for hte bottom two - Media Info and Media Sources??
![image](https://github.com/xbmc/xbmc/assets/99039295/c99d9917-8b8c-47f2-afe1-b5330942eab1)

**Comment by 78andyp** [comment]
Ah... I'm not sure i uploaded the right build of LibreELEC.
I've made another one - this one will output some stuff into the debug log as well - if it doesn't work could you share that.
Thanks
Link to new build - https://file.io/SepiWoyV6L3o

**Comment by Hansie9999** [comment]
> When you create a profile do you choose Separate or one of the Shares with Default options for hte bottom two - Media Info and Media Sources?? ![image](https://private-user-images.githubusercontent.com/99039295/300296367-c99d9917-8b8c-47f2-afe1-b5330942eab1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTc3MzgsIm5iZiI6MTcwNjUxNzQzOCwicGF0aCI6Ii85OTAzOTI5NS8zMDAyOTYzNjctYzk5ZDk5MTctOGI4Yy00N2YyLWFmZTEtYjUzMzA5NDJlYWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA4MzcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZDgxYzU1NGVmNjc5NWNjMzE3N2VlYzQxMDJjMWExYWI1MDU5M2FiNmRkZDlmMGVmMjQ1ODI2M2IzYjgzN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.70atZVOjdMvSFiektWD5xrbnqlcUF9ZcQRj8SRmt3tg)

I use a seperate profile directory,

when creating the profile I tried one with both "keep media sources" and also one without (because for the working workaround I had to select KEEP media sources otherwise It would not work, but I tried both with your build.

I will try that new build you uploaded tonight and if it does not work ill upload the logs,

thanks for your time,


Hans

**Comment by Hansie9999** [comment]
Sadly I must report it still is not working :(

this is the log after creating the user , at this point everything still works fine (no master lock set yet) I created the user with the option to "keep media sources" because that was also a requirement for the workaround to work.
[everything works](https://paste.libreelec.tv/sterling-raccoon.log)

this is the log file after setting the master user lock, everything also still works but not logged out user.
[Master lock set](https://paste.libreelec.tv/next-hornet.log)

this is the log after setting a nummeric password on the new user and rebooting it, now all media is gone :(
[PIN set, rebooted, all media gone](https://paste.libreelec.tv/mature-redbird.log)

I hope the logs help ,


thanks alot,


Hans

**Comment by 78andyp** [comment]
Thanks.
OK, my code isn't being called at all.
My reproduction was in windows. I'll try and get LibreELEC in a VM and have another look.

**Comment by Hansie9999** [comment]
Thanks alot :)

**Comment by 78andyp** [comment]
Thank you for your patience.
I've discovered that dropping local sources doesn't work in the LibreELEC build chain - it always re-downloads.
So both builds I gave you were vanilla LibreELEC with no patch - so unsuprisingly they didn't work!!
I've reproduced in a VM LibreELEC here and have figured out how to create a patch in the LibreELEC build chain so fingers crossed i'll have a new version for you to try soon.

**Comment by 78andyp** [comment]
Third time lucky - https://file.io/j4nSOgqe6I7M

**Comment by Hansie9999** [comment]
Success !! :)

This works, movies and series stay after I enable a PIN lock on the profile :) :)
thanks alot,

If you could get these changes in to the main code for the next Kodi build that would be awesome :)


Now I have another big ask for you, any chanse you could post me a "rough" step by step way on how to add your fix to a build to make myself (incase it takes a while before the fix is implementend in the next versions) so I can try to build it myself and dont have to bother you again for an update :)

I realy am a programming noob, but its something I do like to tinker with, but my skill is way to low now , but if you could get me started on what to do that would be awesome and very much appreciated.


Thanks again,

Hans

**Comment by 78andyp** [comment]
Horray!! Many thanks for confirming and sticking with it.

If you can build LibreELEC already then I think all I did was put this patch in the `LibreELEC.tv\packages\mediacenter\kodi\patches` folder and rebuild.

For building I'm pretty sure I just followed the instructions here - https://wiki.libreelec.tv/development/build-basics - to build but using the build command `PROJECT=RPi ARCH=arm DEVICE=RPi4 make image' from here - https://wiki.libreelec.tv/development/build-commands/build-commands-le-11.0.x

The output img is then in `LibreELEC.tv\target`

Patch - [kodi-100.50-plugins.patch](https://github.com/xbmc/xbmc/files/14126408/kodi-100.50-plugins.patch)

Do let me know if that doesn't work any i'll try and reproduce it again from scratch here.

**Comment by Hansie9999** [comment]
Thanks alot, ill save your patch for later use and see if I can start building one myself :)

Thanks alot, and I do hope you can get this code in to the Kodi build for next versions, It will not just help me , but also people with Emby and Plex servers, I see people with this problem for years.

thanks alot,

Hans

**Comment by m-sundman** [comment]
Could you backport the fix to nexus, too, please?

**Comment by 78andyp** [comment]
@KarellenX are there any more plans for another Nexus version??

**Comment by KarellenX** [comment]
At this stage there is no plan for another release. But that was what I thought about v20.4 and we ended up with v20.5, so anything might be possible, but plan for it not happening.
We are so close to v21 release, it does not seem feasible for another v20.x release

**Comment by m-sundman** [comment]
> We are so close to v21 release, it does not seem feasible for another v20.x release

This is quite a critical bug, so it would be nice to get a fix in the current stable, which is 20.

**Comment by m-sundman** [comment]
> Success !! :)
> 
> This works, movies and series stay after I enable a PIN lock on the profile :) :) thanks alot,

This does not work for me in v21. I always have to unlock sources for any media to show up for profiles without password.
How did you get it to work? Do you create the profile with "keep media sources" or not?

**Comment by Hansie9999** [comment]
> > Success !! :)
> > This works, movies and series stay after I enable a PIN lock on the profile :) :) thanks alot,
> 
> This does not work for me in v21. I always have to unlock sources for any media to show up for profiles without a pin. How did you get it to work? Do you create the profile with "keep media sources" or not?

Hello, I have not tried on v21 yet, since I am waiting for Librelec with V21 to come out of alpha/beta before I try (its working fine now and dont have another Pi to start experimenting for the moment :) )
I dit always have to select "keep media sources" otherwise it would not work, 
sad to hear the fix apperantly was not moved over to v21 main build tho :( :( :( especialy since this is a bug I find people strugling with for many years now :(

**Comment by 78andyp** [comment]
I'm pretty sure the fix was added to v21.
I'll try and get jellyfin setup again over the next few days and check.
@m-sundman - what system(s) are you on, how are your profiles configured etc..??
Thanks

**Comment by Hansie9999** [comment]
> > Success !! :)
> > This works, movies and series stay after I enable a PIN lock on the profile :) :) thanks alot,
> 
> This does not work for me in v21. I always have to unlock sources for any media to show up for profiles without a pin. How did you get it to work? Do you create the profile with "keep media sources" or not?

Hello,

LibreElec V12 just came out of beta, so I took a new SD card , started with a clean install with Libreelec 12 (KODI 21) on my RaPi 4B and it works like a charm so the fix IS in the final build,

these are the exact steps I took ;

- Installed Libreelec like normal, first run from the SD card
- Enabled SSH at install (and put in password)
- Changed language to Dutch (incase it mathers but doubt it)
- Went to profiles, added a new profile with my username, during creation I selected to NOT copy the basic profile settings, but I DIT select to COPY SOURCES (I think this step still is very important, but I dit not try without doing this)
- Enabled PIN code on this profile, system than tells me to enable the master lock , first do this, and than put a PIN lock on my own profile
- Reboot to my own profile
- Set language and time zone to Belgium / Dutch again
- SSH in to my libreelec to copy the needed Jellyfin repository file
- Install this repository file (enabling "unknown sources")
- First refresh the other repository's because otherwise Jellyfin wont be able to pull dependancy's
- Install the Jellyfin addon from the Jellyfin repository (select standard add-on mode at install)
- Manualy input my Jellyfin server IP
- Login to my Jellyfin user account
- Select all my sources
- It starts syncing my movies and TV shows,
- They all show up without a problem
- I reboot my Pi
- Login to my user with my PIN code
- ALL MOVIES AND SHOWS ARE THERE, NO NEED TO UNLOCK EXTRA WITH MASTER CODE !!!!!

Happy day's :)

If you do it like this it SHOULD also work for you, because this is how I tryed the first time and it worked out of the box like that.
(maybey the option to COPY SOURCES is still very important)

Hope it also works for you,

Hans

**Comment by m-sundman** [comment]
> * Login to my user with my PIN code

But this is the part I do NOT want. I want the kids to be able to see their sources without using **ANY** PIN.

**Comment by xspeed1989** [comment]
![Image](https://github.com/user-attachments/assets/29e07fb4-053d-4080-9a6c-2052be1fbe0d)

not working for me!
