### ISSUE TITLE
Old unused extra names appear in Movie version type selection

### ISSUE THREAD

**Issue by CrystalP** [xbmc/xbmc#24368]
### Describe the bug

Problem related to the db migration to v127 of PR #24340, but root cause is a flaw in the original data model.

When using "Rename version" in Manage versions dialog:
![image](https://github.com/xbmc/xbmc/assets/489377/470fc2c5-6d3b-4a8d-bc59-bc0f9ad3dba0)

extra1 and extra1v2 were not versions, they were extra names I used at some point, then I removed or deleted the extras referencing those names before the data migration to v127.

There is a gap in the data migration code: the custom extra names not linked from videoversion anymore were not migrated and received the default itemType 0 (=movie) instead of itemType 1 at the end. But it couldn't have done much better because of a flaw in the initial data model, where unused videoversiontype records do not have a "movie" or "extra" type.

As a consequence the old unused extra names now look like custom version names in the db, and show up as such in the list of version types for "Rename version"

## Expected Behavior

Old unused extra names don't show as version types. There should be a way to remove custom versions or extra names from the list.

## Possible Fix

I don't think the problem can be undone by a query.
From a db perspective the best I can think of is another db bump with a migration query to remove all unused videoversiontypes with owner = 2 and itemType = 0
However it will also kill unused custom version names the user may have created.

The safe way would be to add a way in the GUI to delete unused custom version / extra types. If not for this particular problem, that will be needed anyway at some point for users to maintain their version types list and delete past mistakes in the naming for example.

### To Reproduce

1. start with older Kodi from before videodb v127 (haven't tried beta2, but it should trigger the issue)
2. assign a custom name to an extra through Manage extras > rename > New
3. remove the extra, or rename it to something else
4. run current Kodi
5. the db is migrated to v127
6. Manage versions > Rename > the old extra names show at the bottom of the list.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: current master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
> I don't think the problem can be undone by a query.
From a db perspective the best I can think of is another db bump with a migration query to remove all unused videoversiontypes with owner = 2 and itemType = 0
However it will also kill unused custom version names the user may have created.

I'd definitely would go this way for Omega. 

In the long run however we need the GUI to manage types, including removal of types, ideally marking orphaned types so the user can easily spot tose. But this is definitely nothing for Omega, imo.

**Comment by CrystalP** [comment]
I'll take care of it, I have another db refactor that needs a bump, might as well do both at once.

**Comment by ksooo** [comment]
👍
