### ISSUE TITLE
[Video versions] Library list not updated after managing versions

### ISSUE THREAD

**Issue by Hitcher** [xbmc/xbmc#24378]
### Describe the bug
Here is a clear and concise description of what the problem is:

Separate movie versions still persist in the library view after they have been managed in the versions dialog.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After managing separate versions of a movie the library view should only display a single version.

## Actual Behavior

After managing separate versions of a movie the library view they're still displayed as separate versions unless you exit the view and re-enter it.

## Possible Fix

A container refresh after closing the manage dialog might fix the issue.

### To Reproduce

1. Manage a version via the context menu or info dialog
2. Add another version
3. Exit manage dialog
4. Separate versions are still listed
5. Exit library view
6. Enter library view
7. Only one version is listed

### Debuglog

The debuglog can be found here:
N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

2 versions of Alien:
![screenshot00006](https://github.com/xbmc/xbmc/assets/133808/8fb66740-0edd-4183-ae88-7fcad6238584)
Manage versions:
![screenshot00007](https://github.com/xbmc/xbmc/assets/133808/2735fbfd-81fd-40ad-b222-f75941baf403)
Both versions still displayed:
![screenshot00008](https://github.com/xbmc/xbmc/assets/133808/bebf4303-4bc7-4d53-a219-6d686ed519d1)
Exiting and re-entering single version displayed:
![screenshot00009](https://github.com/xbmc/xbmc/assets/133808/9698b121-a06b-4b28-9350-1c97a83fcaa5)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jjd-uk** [comment]
@Hitcher I was able to observer this issue before but using a build I generated today it no longer seems to be an issue for me, I used https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240102-3e05c007-master-x64.exe so all the latest mergers fpor versions feature were present.

**Comment by Hitcher** [comment]
Still happening here with that build.

**Comment by CrystalP** [comment]
It didn't see it until today. But likely not related to recent commits, I used a different portable data folder data and maybe a slightly different way to create version. I'll try to identify what's different from my previous attempts / working folder & steps.

**Comment by jjd-uk** [comment]
After further testing it seems to work sometimes and other times it doesn't? So I will trying to establish if it takes a certain order or even a certain view type, the times I got it work was when I was in List view.

**Comment by CrystalP** [comment]
Think I found it, add via Context menu > Manage: OK
Add via Info > Manage: no update
