### ISSUE TITLE
Kodi 20.2: Issue with picture thumbs (stride?)

### ISSUE THREAD

**Issue by wutschel** [xbmc/xbmc#24398]
### Describe the bug
Here is a clear and concise description of what the problem is:

With Kodi 20.2 some pictures' thumbs are shown distorted. The same distortion is visible when using the JSON API to gather a thumbnail for the current playing item or playlist items. With Kodi 21 Beta this works as intended. I hope it is possible to identify the bugfix to backport to Kodi for the next 20.x bugfix release.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Pictures are shown without distortion (see screenshots below).

## Actual Behavior

Some picture thumbnails are shown distorted using Kodi 20.2 (see screenshots below).

### To Reproduce

1. Move [image0.jpeg](https://www.dropbox.com/scl/fi/8wocgk4iinsh6prwb3hwn/image0.jpeg?rlkey=jo6vec95b8h2afljuk3kmja43&dl=0) into your picture folder
2. Go to "Pictures" and enter the folder which contains image0
3. Now the thumbnail should show the distortion
4. Select image0 to start a slideshow presenting this picture
5. Use iOS Remote App and go to NowPlaying screen. Alternatively use the JSON command to retrieve path to image URL, then load this.

JSON command:
```
{
    "jsonrpc": "2.0",
    "method": "Player.GetItem",
    "params": {
        "properties": [
             "thumbnail"
        ],
        "playerid": 2
    },
    "id": 1
}
```
This usually returns something like `image://path_to_folder%2fimage0.jpeg/transform?size=thumb`

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

The preview of the folder content is properly shown in both Kodi 20.2 and 21:
<img src="https://picr.eu/images/2024/01/02/O5obT.png" alt="O5obT.png" border="0">

The thumbnail (and also the background) is distorted in Kodi 20.2:
<img src="https://picr.eu/images/2024/01/02/O58mF.png" alt="O58mF.png" border="0">

For reference this is how it looks on Kodi 21:
<img src="https://picr.eu/images/2024/01/02/O5JjJ.png" alt="O5JjJ.png" border="0">

This is how the thumbnail for the current playing item looks like in the Remote App when connected to Kodi 20.2:
<a href="https://picr.eu/i/O5wT4"><img src="https://picr.eu/images/2024/01/02/O5wT4.md.png" alt="O5wT4.md.png" border="0"></a>

For reference this is how it looks when connected to Kodi 21:
<a href="https://picr.eu/i/O56ne"><img src="https://picr.eu/images/2024/01/02/O56ne.md.png" alt="O56ne.md.png" border="0"></a>

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux Mint 21.1
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Can you test a recent nightly? I can't reproduce this using current master.

**Comment by wutschel** [comment]
master and Kodi 21 Beta work. This issue is reported for Kodi 20.2 (also 19.5 has this problem, but even worse).

**Comment by neo1973** [comment]
Probably #23268 which should already be in 20.2. But the PR says:

> Unfortunately, already generated thumbnails remain corrupted and the user has to delete them to get them recreated.

Can you try to delete `~/.kodi/userdata/Thumbnails/` and check if recreating the thumb fixes the issue? I can't explain why it still works works with 21 but I think it's worth to try anyway.

**Comment by wutschel** [comment]
Ah, great. Deleting the thumbnail folder fixed it. The thumbnails were for sure created with an earlier version of Kodi.

**Comment by wutschel** [comment]
@neo1973, deleting the thumbnails and recreating them for picture now caused worse side effects, see https://forum.kodi.tv/showthread.php?tid=375576&pid=3178186#pid3178186 -- another user got the same trouble and assumed the remote app had a problem. I could only resolve this by deleting the .kodi folder completely and rescanning all media. Is this known and is there another way for a user to resolve this?

**Comment by neo1973** [comment]
Hmm, does it help if you delete ~/.kodi/userdata/Database/Textures13.db? (Keep a backup just in case)

**Comment by wutschel** [comment]
> Hmm, does it help if you delete ~/.kodi/userdata/Database/Textures13.db? (Keep a backup just in case)

Yes, this looks better. I did via restoring the just deleted (messed up) .kodi folder and deleting the Textures13.db. So, it is important to deleted _both_ the thubmnails and the textures file then, right?

**Comment by neo1973** [comment]
Yeah, looks like it. But I have to say, I'm lacking the understanding of the differences when Kodi "normally" accesses the thumbs vs. over JSONRPC. Somehow only in the first case they are recreated when an entry in the texture DB exists but the actual file is missing.
