### ISSUE TITLE
WebOS: DoVi files with HDR10+ do not play on OLED48A23LA

### ISSUE THREAD

**Issue by TETYYS** [xbmc/xbmc#24390]
### Describe the bug
Here is a clear and concise description of what the problem is:

Dolby Vision profile 8 .mkv files with HDR10 fallback play fine (Plex has a problem with these, so good job Kodi), but Dolby Vision profile 8 with HDR10+ shows a solid color fullscreen.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

HDR10+ discarded, Dolby Vision used and video plays fine

## Actual Behavior

Dolby Vision indicator pops up, but screen is black, green or yellow (seems random? maybe more colors are possible)

## Possible Fix

quietvoids fork has functionality to remove HDR10+ on-the-fly (https://github.com/quietvoid/xbmc/commit/308135d42e04eca6c2e50af9d510a4b1c0daae4e#diff-1b6daeb37ffecaec8c337573af6035748aa92c3938748e9f8db583ed33d00a29R602). As no LG (and therefore WebOS) TV supports HDR10+, Kodi could just always try to remove HDR10+. I tried this myself but I failed to compile kodi.

### To Reproduce

1. Play https://mega.nz/file/BwcwRABI#ab1vK4joZbFe_t0uy_Ki_vTbSf5RGXpowABUJKh9dQU

### Debuglog

The debuglog can be found here:
[log.log](https://github.com/xbmc/xbmc/files/13806097/log.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [X] WebOS

 - Operating system version/name: WebOS 7.1.0-68 (mullet-maria)
 - Kodi version: 20.90.821

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by SubEdict** [comment]
Using quietvoids fork more than a year+ now to remove from Samsung TV Dolby Vision. **It is** the only way to play these files on Firestick Max. Simple, work perfect.

**Comment by TETYYS** [comment]
> Using quietvoids fork more than a year+ now to remove from Samsung TV Dolby Vision. **It is** the only way to play these files on Firestick Max. Simple, work perfect.

yeah except android builds don't quite match up with WebOS and here we need to remove HDR10+, not DoVi..

**Comment by TETYYS** [comment]
> The test sample plays perfectly fine on my TV, LG OLED C2.

To make sure moon position today does not have influence on this I tested the same sample and it's showing black still, then I tested stripping HDR10+ for this sample specifically and it's working with DoVi as expected, OLED48A23LA.

```
ffmpeg -i out.mkv -sn -an -c:v copy vid.h265
ffmpeg -i out.mkv -sn -vn -c:a copy audio.eac3
ffmpeg -i out.mkv -an -vn -c:s copy sub.ass
hdr10plus_tool remove .\vid.h265
mkvmerge .\hdr10plus_removed_output.hevc .\audio.eac3 .\sub.ass -o vidnohdr10p.mkv
```

vidnohdr10p.mkv: `Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible`
out.mkv: `Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible`

**Comment by quietvoid** [comment]
Can you clarify which version you're using? Did you try the latest nightly?
It may just be a difference on A series models.

**Comment by TETYYS** [comment]
I was using 20.90.821, stright from homebrew.
I experience same behavior with org.xbmc.kodi_20240101-7413267d-master_arm nightly

**Comment by sundermann** [comment]
The linked file plays on my device too. LG has different SoC vendors and they all implement the media pipeline differently so it's perfectly reasonable that the linked file can fail to play on specific SoC. I'm fine with disabling HDR10+ because it's generally not supported on LG TVs but I'm wondering why @quietvoid's change is not in master.

**Comment by TETYYS** [comment]
I've compiled a version with `m_bitstream->SetRemoveHdr10Plus(true);` added for `DVDVideoCodecStarfish.cpp` and it seems to work fine. At least for videos that I tested. I will play a full video when I get a chance and report if there are any instabilities or such.

**Comment by RohanKrishna500** [comment]
> I've compiled a version with `m_bitstream->SetRemoveHdr10Plus(true);` added for `DVDVideoCodecStarfish.cpp` and it seems to work fine. At least for videos that I tested. I will play a full video when I get a chance and report if there are any instabilities or such.

Hi where u able to fix the issue,i have LG A2 OLED and have same issues and none of the fixes are working

**Comment by TETYYS** [comment]
> Hi where u able to fix the issue,i have LG A2 OLED and have same issues and none of the fixes are working

I'm still running my own build which works fine for me. You know what they say, if it ain't broke don't fix it

**Comment by RohanKrishna500** [comment]
> > Hi where u able to fix the issue,i have LG A2 OLED and have same issues and none of the fixes are working
> 
> I'm still running my own build which works fine for me. You know what they say, if it ain't broke don't fix it

is your device lg a2 oled?,also what build are we talking about here?

**Comment by TETYYS** [comment]
> is your device lg a2 oled?,also what build are we talking about here?

Yes, you can see the exact model in comments above. Build is of my own - I compiled it with changes also described above. If you would like to get it, then I'm sorry but I most likely deleted it (my plan was just use the nightly build if for some reason my TV would reset)

**Comment by RohanKrishna500** [comment]
> > is your device lg a2 oled?,also what build are we talking about here?
> 
> Yes, you can see the exact model in comments above. Build is of my own - I compiled it with changes also described above. If you would like to get it, then I'm sorry but I most likely deleted it (my plan was just use the nightly build if for some reason my TV would reset)

can u tell me what to do so that i can try to replicate and compile it on my own?,also if any other version works for you then can u tell me which one is it

**Comment by TETYYS** [comment]
https://github.com/xbmc/xbmc/blob/master/docs/README.webOS.md and changes are described above

**Comment by RohanKrishna500** [comment]
> https://github.com/xbmc/xbmc/blob/master/docs/README.webOS.md and changes are described above

i really dont know how to build a custom one so if u got any prebuilt which is working for you please share it

**Comment by RohanKrishna500** [comment]
> > Hi where u able to fix the issue,i have LG A2 OLED and have same issues and none of the fixes are working
> 
> I'm still running my own build which works fine for me. You know what they say, if it ain't broke don't fix it

hi,you said you are still running the same build so u must have the ipk installed on your TV,can u send me that ipk file

**Comment by TETYYS** [comment]
nightly includes the same functionality so it should work fine...

**Comment by RohanKrishna500** [comment]
well none worked

**Comment by RohanKrishna500** [comment]
> nightly includes the same functionality so it should work fine...

can u tell me the exact build so that i can install and try it
