### ISSUE TITLE
WebOS: Issue with core.xxxx files creation upon exit or crash

### ISSUE THREAD

**Issue by Misenkooo** [xbmc/xbmc#24401]
### Describe the bug
Here is a clear and concise description of what the problem is:

I've noticed that when I exit application or it if crashes on my LG C1, KODI is creating these "core.xxxx" files in org.xbmc.codi folder. 
Since free space is limited on LG C1 (3GB) after KODI installation I have ~800MB left. If KODI is closed or crashes several times I'm out of space and TV is not working stable anymore. 

Then I need to remove CORE files manually with webOS Dev Manager to remedy the issue.

This is a big issue for all WebOS KODI users.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Do not create these core.xxxx files on WebOS upon crash or exit in case this option is disabled in settings. I haven't found a setting to prevent this behavior.

## Actual Behavior

Upon every crash or exit a big dump file (200 - 300MB) is created which depletes space very fast on WebOS.  

## Possible Fix

Introduce a new switch in settings to disable dump file creation.

### To Reproduce

1. Exit KODI on WebOS or let it crash and check orx.xbmc.kodi folder. Big dump file is created.

### Debuglog

The debuglog can be found here:

No log is necessary

### Screenshots 
Here are some links or screenshots to help explain the problem:

![core_files](https://github.com/xbmc/xbmc/assets/3950626/746111e5-ca12-412b-a557-c20012eadaae)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: WebOS 6.0
 - Kodi version: org.xbmc.kodi-webos_21.0~b2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by A-Shahbazi** [comment]
It's happening for me, too.

**Comment by sundermann** [comment]
It's not really a bug though because LG intends core file creation on sideloaded apps. I check if it's possible to use `ulimit` to stop core file dumps when not in debug logging. Core files can be pretty useful to get a stacktrace in case a crash occurs and the Dev Mode Manager can read that too

**Comment by sundermann** [comment]
Also please get the crash dump from webOS Dev Manager when you encounter a crash on exit or during use. It'd be better to fix the root cause rather than disabling the core dump feature at all

**Comment by Misenkooo** [comment]
Thanks for checking. I will try to upload dump file. Problem is that those are usually very big but sometimes I saw they are only few kilobytes. I’ve disabled all logging and these core files are always created so would be great if they can be at least limited when logging is disabled to just few kilobytes if they can’t be turned off completely.

**Comment by sundermann** [comment]
Don't upload the core dump file. The Dev Mode Manager can extract the stacktrace which you can upload at paste.kodi.tv

**Comment by Misenkooo** [comment]
Ah OK, will try it if I find out how :) What if I have multiple core folders in there ?

**Comment by sundermann** [comment]
It will show a crash report for every core dump file. Just create one paste for every crash dump

**Comment by Misenkooo** [comment]
Hi Stephan, 

I've tried to look into Debug section but it says "No crash reports" but I can see 4 core folders in kodi folder. Do you know what's the issue ? Those folders are very huge which I don't think is even truth because it's almost 3GB size and there is definitely not so much memory available and it says I have still 28MB free. After deletion of those 4 folders it says 920MB free. This is very weird. 

![core_files_2](https://github.com/xbmc/xbmc/assets/3950626/b4899a1c-be4d-425d-9ebe-7dc9d305e37b)
![debug](https://github.com/xbmc/xbmc/assets/3950626/21c3aaa8-7751-4ba0-90b7-35a52f6f9ae6)

**Comment by sundermann** [comment]
Not sure how dev mode manager collects crash reports exactly. It seems the TV had been restarted since those dumps had been taken. I suggest you check dev manager again directly after a core dump has been created

**Comment by Misenkooo** [comment]
That's right. Thanks for suggestion, will do so and report back. Thanks.

**Comment by Protomove** [comment]
I modified an addon that I found on the internet and it deletes the core file every time you run Kodi. It is the best option I found to solve the problem, greetings  https://github.com/Protomove/Core-remove-kodi

**Comment by gileli121** [comment]
@Protomove 
Thanks a lot.
It really helpful.
It should be built in option in kodi...

**Comment by Protomove** [comment]
> @Protomove Thanks a lot. It really helpful. It should be built in option in kodi...

I'm very happy, I was tired and didn't know how to solve the problem, I finally enjoy Kodi

**Comment by rraddatch** [comment]
How can I install https://github.com/Protomove/Core-remove-kodi, or what exactly should I do to resolve this issue on my Kodi running on an LG TV with WebOS? Can anyone provide me with a detailed step-by-step guide? Thank you!
