### ISSUE TITLE
tvOS Nexus Nightly - libass.framework CFBundleIndentifier wrong

### ISSUE THREAD

**Issue by Rukongai** [xbmc/xbmc#24425]
### Describe the bug
The nightly versions of Nexus for tvOS won't install because the Bundle Identifier for libass.framework is set to
```
/Users/Shared/jenkins/workspace/TVOS_Nexus/build/build/Debug-appletvos/Kodi.app: could not find /Users/Shared/jenkins/workspace/TVOS_Nexus/build/build/Debug-appletvos/Kodi.app..framework.libass
``` 
instead of
```
org.xbmc.kodi-tvos.framework.libass
```

This is causing the install on tvOS to error out and fail

## Expected Behavior
Nightly Nexus builds should be able to install

## Actual Behavior

Nightly Nexus builds don't install

## Possible Fix

Fix the bundle identifier.

### To Reproduce

1. Sign Kodi for tvOS
2. Install via Configurator/xCode/iMazing
3. Check console logs for error

### Debuglog

The debuglog can be found here:
No debug logs, but the error from my device console is
```
-[IXSDataPromise cancelForReason:client:error:]: <IXSPromisedTransferToPath(0x5a0a0e220) Name:com.edenwatch.kodi-dev-Asset Creator:AirTraffic UUID:184EB587-BA77-472A-A8A0-141CE1CE61E5 PercentComplete:1.000000 IsComplete:Y DiskUsageBytes:0> : canceled by client 17 for reason Error Domain=IXUserPresentableErrorDomain Code=1 "This app could not be installed at this time." UserInfo={NSUnderlyingError=0x5a0b12400 {Error Domain=MIInstallerErrorDomain Code=69 "Bundle at path /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.lw61tg/extracted/Payload/Kodi.app/Frameworks/libass.framework had an invalid CFBundleIdentifier in its Info.plist: /Users/Shared/jenkins/workspace/TVOS_Nexus/build/build/Debug-appletvos/Kodi.app: could not find /Users/Shared/jenkins/workspace/TVOS_Nexus/build/build/Debug-appletvos/Kodi.app..framework.libass" UserInfo={LegacyErrorString=PackageInspectionFailed, FunctionName=-[MIBundle _validateWithError:], SourceFileLine=79, NSLocalizedDescription=Bundle at path /var/installd/Library/
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screenshot of kodi.app/Frameworks/libass.framework/Info.plist
<img width="1649" alt="Screenshot 2024-01-03 at 6 49 04 PM" src="https://github.com/xbmc/xbmc/assets/11468686/96f69cb5-2bf8-4a66-9760-e30f88ef1f86">

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 17.2
 - Kodi version: Nexus Nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sy6sy2** [comment]
Thanks for the issue.
Related thread: https://forum.kodi.tv/showthread.php?tid=375478

@kambala-decapitator maybe you have an idea about a fix? I suspect something wrong in `Codesign.command` file but I haven't finish the debugging yet.

**Comment by kambala-decapitator** [comment]
I've downloaded the latest nightly and inspected its contents: strange, but I don't see any frameworks there... (except python)

**Comment by Rukongai** [comment]
This is only an issue with Nexus nightly, fwiw

**Comment by Rukongai** [comment]
I just downloaded and checked kodi-20240104-0b5629e3-Nexus-17187-tvos and confirmed the issue is still present

**Comment by kambala-decapitator** [comment]
> This is only an issue with Nexus nightly, fwiw

oh, sorry, missed that. Thanks for the clarification!

**Comment by Rukongai** [comment]
I haven't dug into it, but doing a quick search makes me feel like https://github.com/xbmc/xbmc/commit/5c5ad2dd6d6493ce70dbfe637fabc74b5e902183 is probably the offender

**Comment by kambala-decapitator** [comment]
> I haven't dug into it, but doing a quick search makes me feel like [5c5ad2d](https://github.com/xbmc/xbmc/commit/5c5ad2dd6d6493ce70dbfe637fabc74b5e902183) is probably the offender

it's not a part of Nexus (no backport PR there), you can also see in https://github.com/xbmc/xbmc/tree/Nexus/tools/darwin/Support that this dir hasn't been touched for years

I'd rather think on #22958

**Comment by Rukongai** [comment]
Totally right, didn't even see I was in the wrong branch.

**Comment by kambala-decapitator** [comment]
@Rukongai please test artifact from https://jenkins.kodi.tv/job/TVOS/17188/ once the build has finished

**Comment by Rukongai** [comment]
Issue is still present.

Looking at the console output on jenkins, if you search
`CFBundleIdentifier is /Users/Shared/jenkins/workspace/TVOS_Nexus/build/build/Debug-appletvos/Kodi.app: could not find /Users/Shared/jenkins/workspace/TVOS_Nexus/build/build/Debug-appletvos/Kodi.app..framework.libass`

it looks like this is occurring in copyframeworks-dylibs2frameworks.command

That line was generated here https://github.com/xbmc/xbmc/blob/0b5629e3ee5f79d175580b1b25fb27227e9f3c89/tools/darwin/Support/copyframeworks-dylibs2frameworks.command#L50-L57

Maybe related to how the bundleid is being set here?

**Comment by kambala-decapitator** [comment]
from the logs looks ok now, @Rukongai could you test? https://jenkins.kodi.tv/job/TVOS/17425/artifact/tools/darwin/packaging/tvos/kodi-20240119-8cdd51fe-PR24540-17425-tvos.deb

**Comment by Rukongai** [comment]
Just checked the plist, and it looks great! I'll test loading it to my AppleTV tomorrow, but I expect it'll work

**Comment by tda20300** [comment]
> from the logs looks ok now, @Rukongai could you test? https://jenkins.kodi.tv/job/TVOS/17425/artifact/tools/darwin/packaging/tvos/kodi-20240119-8cdd51fe-PR24540-17425-tvos.deb

I send this file from Xcode to my Apple TV 4K and now its ok, good work!
