### ISSUE TITLE
Incorrect letterboxing for Dolby Vision on Android TV (Sony A95L)

### ISSUE THREAD

**Issue by dbarkar** [xbmc/xbmc#24420]
### Describe the bug
Dolby Vision mode is activated properly.
Part of the image next to black bars on top and bottom are semi-transparent.
Internal media player can handle this media file well.
Mediainfo: https://paste.kodi.tv/bezofoyosa

## Expected Behavior
Proper letterboxing.

## Actual Behavior
Incorrect letterboxing :)

## Possible Fix
Probably wrong media codec for this DV profile.

### To Reproduce

1. Open media file
2. See the result

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/sisuyexube.kodi

### Screenshots 
**It's not rendered on screenshot, so I had to do a photo**:
![photo](https://github.com/xbmc/xbmc/assets/1224655/c7edb268-2b47-4da9-a5ff-f4d3e9168766)
Screenshot made with adb:
![screenshot](https://github.com/xbmc/xbmc/assets/1224655/bc3a3921-0ab5-4bb9-86dc-d9130eaf5a18)

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 12
 - Kodi version: nigthly 20240102

**Comment by quietvoid** [comment]
Your file has incorrect Dolby Vision metadata. This isn't a Kodi issue.

**Comment by dbarkar** [comment]
You are  absolutely right, Just player shows the same picture as Kodi and internal player plays it in HDR10.
Can you please tell me what's the problem with metadata here?

**Comment by quietvoid** [comment]
Someone took metadata from a file with letterboxing (encoded resolution of 3840x2160).
And added it to a HDR10+ video that was cropped (3840x1920 resolution), without adjusting the metadata properly.

**Comment by dbarkar** [comment]
Thanks for the explanation!
I’m closing this issue, sorry for the noise.
