### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by pcaswell909** [xbmc/xbmc#24435]
make -C tools/depends/target/cmakebuildsys BUILD_DIR=$HOME/kodi-build
mkdir -p /Users/submerger/kodi-build
cd /Users/submerger/kodi-build; /Users/Shared/xbmc-depends/x86_64-darwin23.3.0-native/bin/cmake -DCMAKE_TOOLCHAIN_FILE=/Users/Shared/xbmc-depends/macosx14.2_arm64-target-debug/share/Toolchain.cmake -DCMAKE_INSTALL_PREFIX=/Users/Shared/xbmc-depends/macosx14.2_arm64-target-debug -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_DEPENDS_USE_COMPILER=OFF -DENABLE_INTERNAL_CROSSGUID=ON -DENABLE_INTERNAL_FFMPEG=OFF  /Users/submerger/kodi
/bin/sh: /Users/Shared/xbmc-depends/x86_64-darwin23.3.0-native/bin/cmake: No such file or directory
make: *** [all] Error 127

Did I miss anything?

**Comment by fuzzard** [comment]
Yes. https://github.com/xbmc/xbmc/blob/master/docs/README.macOS.md#4-configure-and-build-tools-and-dependencies
