### ISSUE TITLE
Cannot Launch Kodi 20.3 on Chromecast with Google TV: Cannot download obb

### ISSUE THREAD

**Issue by neilsimon** [xbmc/xbmc#24478]
### Describe the bug
When I launch Kodi on Chromecast with Google TV I get a window with an error message:
```Cannot download obb.```
The only provided option is to click Exit, which exits Kodi.
I have tried moving the app data from internal storage to a memory stick, which made no difference.

## Expected Behavior
Kodi starts up.

## Actual Behavior
Kodi gives the above error message and fails to start.

### To Reproduce
1. Update to latest Kodi (20.3) on Google Play Store for Google TV
2. Try to start Kodi

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
20.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by utajum** [comment]
Same error on ATV

I did an uninstall and installed it again from the playstore with the same result

**Comment by dnnzvz** [comment]
I have the same issue. I also deleted the app and reinstalled it. I have a nvidea shield.

**Comment by CodeWithClass** [comment]
I also have this issue with google chrome cast

**Comment by tbmmbt** [comment]
Same issue on my Nvidia Shield after Kodi auto updated itself from the Play Store.

**Comment by sunproject4444** [comment]
Just installed kodi from play store on samsung s23 ultra and immediately crashed with cannot download obb

**Comment by hybrid79** [comment]
Installed kodi 20.3 on shield tv pro 2019 from playstore. Same error.

**Comment by recklezz** [comment]
Same issue. Installing the apk fixed it though.

**Comment by fuzzard** [comment]
Unfortunately the attempts to backport the PR's required to submit to the Google Playstore have been unsuccessful. We have halted the rollout of 20.3 via the playstore, and we will be unable to do a release on the playstore.

For those who did get the initial deployment, unfortunately you will have to uninstall and reinstall from the store. This should then reinstall 20.2 as of now.

**Comment by BasterdOperator** [comment]
Installed kodi 20.3 on nvidia shield tv pro 2019 from google playstore. Same error.

**Comment by neilsimon** [comment]
> Unfortunately the attempts to backport the PR's required to submit to the Google Playstore have been unsuccessful. We have halted the rollout of 20.3 via the playstore, and we will be unable to do a release on the playstore.
> 
> For those who did get the initial deployment, unfortunately you will have to uninstall and reinstall from the store. This should then reinstall 20.2 as of now.
> 
> We have added the following message to the halt of the deployment
> 
> > Developer notes: Unfortunately we have had to halt the deployment for 20.3, and we will be unable to do a Playstore release. If you wish to use 20.3 you will need to sideload the APK from our mirrors at https://mirrors.kodi.tv/releases/android/ We apologise for the inconvience

Thanks for the update. Any suggestion on how we can roll back from 20.3 to 20.2 without losing our settings, addons, etc.?

**Comment by CodeWithClass** [comment]
> Unfortunately the attempts to backport the PR's required to submit to the Google Playstore have been unsuccessful. We have halted the rollout of 20.3 via the playstore, and we will be unable to do a release on the playstore.
> 
> For those who did get the initial deployment, unfortunately you will have to uninstall and reinstall from the store. This should then reinstall 20.2 as of now.
> 
> We have added the following message to the halt of the deployment
> 
> > Developer notes: Unfortunately we have had to halt the deployment for 20.3, and we will be unable to do a Playstore release. If you wish to use 20.3 you will need to sideload the APK from our mirrors at https://mirrors.kodi.tv/releases/android/ We apologise for the inconvience

Not really a good solution since we are unable to launch kodi to perform backups.

**Comment by slanglade** [comment]
My kodi install was broken by the 20.3 version pushed by Googke Play on my Nvidia Shield Tv 2019.

I can confirm that sideloading the 20.3 apk directly from https://mirrors.kodi.tv/releases/android/ restored everything.

**Comment by CodeWithClass** [comment]
Update. Installing 20.3 from kodi mirror works on chromecast without losing any data https://mirrors.kodi.tv/releases/android/arm/

**Comment by kopr12** [comment]
Same problem on SonyTV, is there any way to resolve this without loosing settings?
It was really a pain to set everything up initially, with network shares etc.

**Comment by CodeWithClass** [comment]
> Same problem on SonyTV, is there any way to resolve this without loosing settings? It was really a pain to set everything up initially, with network shares etc.

Use downloaded app and type in the exact link to v20.3. It will install in place so you won’t lose data https://github.com/xbmc/xbmc/issues/24478#issuecomment-1885808125

**Comment by kopr12** [comment]
> Use downloaded app and type in the exact link to v20.3. It will install in place so you won’t lose data [#24478 (comment)](https://github.com/xbmc/xbmc/issues/24478#issuecomment-1885808125)

Thanks buddy, that worked.
Although, when I opened Kodi and message appeared how it's clearing cache and it's preparing to run for the first time was kinda scary :)
I mean I thought the settings were gone but it was fine.
