### ISSUE TITLE
20.3 on ppa as not been released but it's marked as available... it's not anymore maintain ?

### ISSUE THREAD

**Issue by DjDiabolik** [xbmc/xbmc#24492]
### Describe the bug
Apparently the 20.3 it's not be updated on ppa but only in flatpack.

So i need to change to this ? I can maintain the current setting ?

## Expected Behavior
No idea

## Actual Behavior
No idea

## Possible Fix
Lol.. also here no idea

### To Reproduce
simply try to "sudo apt update" and "sudo apt full-upgrade" and 20.3 not showing up.

### Debuglog
Problably nothing need here....

### Screenshots 
Also here......

## Additional context or screenshots (if appropriate)
No idea.....

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 22.04.3 LTS
 - Kodi version: 20.2

**Comment by DjDiabolik** [comment]
Oh ok... if my issue it's closed in a week no problems. A week it's good time to obtain an answer i hope. thanks in advance.

**Comment by sarbes** [comment]
The PPA is not supported anymore.

**Comment by ne20002** [comment]
Actually the flatpak lacks lirc support. This makes switching to flatpack impossible as a remote control is needed.

**Comment by DjDiabolik** [comment]
> The PPA is not supported anymore.

It's great lost..... flatpak package it's available but it's not same things apparently.....
