### ISSUE TITLE
[Kodi 21 Beta3] Extract video information from files don't works from "KodiSetup-20240102-751e6c3b" with TV Shows

### ISSUE THREAD

**Issue by Nanomani** [xbmc/xbmc#24498]
### Describe the bug
Here is a clear and concise description of what the problem is:

From Kodi (21.0-BETA2 (20.90.821) Git:20240102-751e6c3b55) when you add a new Tv Show or if you full refresh information for a existing Tv Show in library, all information from file (episode) are empty.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect to see all video information (codec, resolution, aspect...) for each episode.

## Actual Behavior

There is only the video duration

## Possible Fix

The latest Kodi version without issue is : 
21.0-BETA2 (20.90.821) Git:20240101-7413267da7

### To Reproduce

(All test are made from a clean Kodi install with all default settings)

Scenario 1 : add a new TV Show in library

1. use Kodi (21.0-BETA2 (20.90.821) Git:20240102-751e6c3b55) or newer 
2. add a new tvshow
3. then open this tvshow information
4. list the episode information

Scenario 2 : refresh a TV Show already in library with all video information correctly stored

1. use Kodi (21.0-BETA2 (20.90.821) Git:20240102-751e6c3b55) or newer 
2. open information for this tvshow
3. then refresh all information for all episode
4. list the episode information

### Debuglog
The debuglog can be found here:

After scrape a new TV Show
https://paste.kodi.tv/ijiwanutow.kodi

After refresh a tvshow already in library with all video information correctly stored
https://paste.kodi.tv/raloqocuvu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

The issue after a full refreh / a new TV Show added : 

![2024-01-13_132955](https://github.com/xbmc/xbmc/assets/3939543/9a5be1c9-f873-431e-a7d2-c916717c8b5a)

![2024-01-13_133521](https://github.com/xbmc/xbmc/assets/3939543/904b0994-3572-4286-8610-e63aafe9cfa7)

What is expected : 

![2024-01-13_132009](https://github.com/xbmc/xbmc/assets/3939543/2ab6019a-0b86-40d8-9169-a3a46b85cdd8)

![2024-01-13_135403](https://github.com/xbmc/xbmc/assets/3939543/d7daa3cb-ecf4-4778-bc5c-c27afef27aea)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Tested with the latest nightly Kodi version : 
 KodiSetup-20240112-5198ea50-master-x64

The issue is the same

### Your Environment
Used Operating system:

 - [X] Windows

 - Operating system version/name: Windows 11 Pro x64
 - Kodi version: KodiSetup-20240102-751e6c3b-master-x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by biner73** [comment]
I am seeing this same issue. Noticed this behavior started recently, sometime after the Beta 2 build. The Beta 2 build does not have this issue.

Something else to add, I've confirmed this to be occuring with both the MovieDB TV Shows and the TVDB4 scrapers alike.

**Comment by biner73** [comment]
@the-black-eagle Having a quick look at the merges after the working build, could possibly be related to this change? [https://github.com/xbmc/xbmc/pull/24386](url)

**Comment by the-black-eagle** [comment]
Meh !!  So, what's happening is that there _are_ streamdetails for episodes, but _only_ a duration.  Therefore, the test for no streamdetails fails and the file is not probed.

What I need to dig into, is whether that duration is not getting reset correctly, or whether it's coming from the scraper.

The symptom is clear, now to find the root cause and establish a fix.

**Comment by Hitcher** [comment]
@the-black-eagle pretty sure the duration is coming from the scraper as we show the exact duration including seconds whereas tmdb doesn't.
