### ISSUE TITLE
Bad preview for Dolby Vision Profile 5 video

### ISSUE THREAD

**Issue by tisonv** [xbmc/xbmc#24495]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi Omega Beta 1 & Beta 2 show bad colors on previews of Dolby Vision profile 5 videos.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Colors are ok

## Actual Behavior

Colors are not ok

### To Reproduce

1. Select a profile 5 video

### Debuglog

The debuglog can be found here: 
do I have to clean install and enable log ? Not sure if it is logged

### Screenshots 
Here are some links or screenshots to help explain the problem:
![image](https://github.com/xbmc/xbmc/assets/69853851/0a57e4e9-84d5-4253-b6bc-f8004a8f1976)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

None

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Omega Beta 1 & Beta 2 
Product: BRAVIA_ATV3_4K_EU, Device: BRAVIA_ATV3_4K, Board: BRAVIA_ATV2 - Manufacturer: Sony, Brand: Sony, Model: BRAVIA 4K GB ATV3, Hardware: mt5891

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by quietvoid** [comment]
Kodi doesn't support tone mapping Dolby Vision so it probably also impacts thumbnails or w/e generates these.

**Comment by tisonv** [comment]
Profile 8 thumbnails look alright though.

**Comment by quietvoid** [comment]
Expected if Kodi supports tone mapping HDR10 thumbnails.

**Comment by malard** [comment]
closing as Profile 5 isn't supported yet
