### ISSUE TITLE
Movies are not updated from Video plugins

### ISSUE THREAD

**Issue by dbarkar** [xbmc/xbmc#24507]
### Describe the bug
When I install Jellyfin video plugin to Kodi and sync my library, Movies are empty. Other libraries like TV Shows are properly synchornized. Looks like video plugin "owns" Movies (I can't add folders there) but movies are not pulled.
I found this problem on Android TV, but it also happens on PC and probably on other platforms, my logs are from PC.

This is a recent regression. I checked these revisions:
https://github.com/xbmc/xbmc/commit/5198ea50825e1f5adbd55b467eb3982fa8618766 (master @ 2024-Jan-13) - bugged
https://github.com/xbmc/xbmc/commit/979dbf5fe5d0b42daf633434afc3986651c8646a (21.0b2-Omega @ 2023-Dec-9) - working.

## Expected Behavior
All libraries are synchonized.

## Actual Behavior
All libraries except for Movies are synchonized.

## Possible Fix
Compare two branches and check for suspicious commits?

### To Reproduce
1. Install Kodi
2. Setup Jellyfin server, add library for Movies
3. Install Jellyfin plugin to Kodi, connect to the server, synchronize
4. See that Movies are still empty

### Debuglog

Failure (master) - https://paste.kodi.tv/sipakinizu.kodi
Success (21.0b2-Omega) - https://paste.kodi.tv/uhavuyogus.kodi

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 23H2 (OS Build 22631.3007)
 - Kodi version: master https://github.com/xbmc/xbmc/commit/5198ea50825e1f5adbd55b467eb3982fa8618766

**Comment by sarbes** [comment]
Jellyfin messes with the Kodi DB, which is not supported. Take your issue to them.
