### ISSUE TITLE
Kodi 21 beta 2

### ISSUE THREAD

**Issue by Greg0580** [xbmc/xbmc#24500]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Since kodi beta 2 updated 11th  December.  I have been having problems with Resolve after it finished scrapping it shows a pop-up playback fail  if you press OK  it goes away but at the end of the TV show/movie the same message pops up.  
And when you try cleaning the Addon it pops up again.  

And when you go to kodi settings PVR & Live TV , General,  clear data Eg Channels, Groups,  Guide ,Provides the writing is in Orange 

Kodi beta 2. 9th December dose not have any of the above Problems. 
### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
No response.
