### ISSUE TITLE
Changing of player controls when pausing a video is counterintuitive

### ISSUE THREAD

**Issue by fonic** [xbmc/xbmc#24514]
### Describe the bug
Here is a clear and concise description of what the problem is:

**Player controls change when pausing a video:** 
Due to hiding the _rewind_ and _forward_ buttons, the _stop_ button moves to the position where the _pause_ button was at before pausing. This is really counterintuitive, especially when using mouse or touch input, as clicking/touching the _same spot_ now **stops** the video instead of resuming it.

If there is a configuration option that changes this behavior, please let me know - I could not find any.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Either the _rewind_ and _forward_ buttons should stay visible when pausing a video or they should be 'greyed out', i.e. made unusable. Personally, I'd prefer if they simply stayed visible, I don't see any reason to hide them.

## Actual Behavior

See 'Describe the bug'.

## Possible Fix

See 'Expected behavior'.

### To Reproduce

1. Start playback of a video
2. Pause the video
3. Notice player controls changing

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

Video playing:
![kodi_1](https://github.com/xbmc/xbmc/assets/14027079/67bdf98b-72d6-4bbf-a26b-c4b2cb67559e)

Video paused:
![kodi_2](https://github.com/xbmc/xbmc/assets/14027079/7977fa0a-9573-4930-aed0-c463e25f5b4b)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
I see this as a feature request (or a usability issue) not exactly as a bug. Mind bringing this to the forum instead?
Sorry to close

**Comment by fonic** [comment]
I see this as a usability issue. Where would I post that on the forum? There only seems to be section dedicated to feature requests, but none for issues.

**Comment by fonic** [comment]
Will hopefully get fixed by this [pull request](https://github.com/xbmc/xbmc/pull/24715).
