### ISSUE TITLE
Playing music starts Music OSD in "Paused" state

### ISSUE THREAD

**Issue by NeoCortex42** [xbmc/xbmc#24517]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing a file from the Music Library, the file plays, but the OSD is in the Paused state.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Play a file from the Music Library and OSD behaves normally.

## Actual Behavior

Upon selecting a file from the Music Library, the track begins to play and the Music OSD comes up.  The track time increments as it should while the music is playing, but below the running time, "PAUSED " is displayed.  Pausing and then resuming playback causes the OSD to behave normally.  This behavior was first observed using the Estuary Mod v2 Omega skin (which exhibited additional Music OSD errors due to the initial paused state), but is also present when checking on the default Estuary skin.  This error started showing up on Nightly Builds for me over the past week, including the most recent [KodiSetup-20240114-f3f1df1e-master-x64.exe], but was not present on earlier builds.  It also has shown up on two separate Windows machines with the same behavior for me. 

### To Reproduce

1. Play music track from Music Library

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/xajahamuri.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

From what I've heard back from a couple others that have looked into this in the skin discussion forum, it does not appear to happen on CoreElec installs running the latest nightly builds.  

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: [KodiSetup-20240114-f3f1df1e-master-x64.exe]

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Hitcher** [comment]
I don't think this is a skin issue as any combination of conditions for this results in the same behaviour.

Code in question:

https://github.com/xbmc/xbmc/blob/6e2851d997860d7e5a57d912f32898ebe08f9680/addons/skin.estuary/xml/Variables.xml#L36-L39

**Comment by jjd-uk** [comment]
@Hitcher I can see it was ok in the Nightly from the 7th Jan, and then was not ok in the 8th Jan.

**Comment by jjd-uk** [comment]
Maybe https://github.com/xbmc/xbmc/pull/24402 @enen92

**Comment by jjd-uk** [comment]
Video of issue https://youtu.be/wJF8DE6mC1k?si=cHDlhVcwkU2M0TT4

**Comment by enen92** [comment]
@jjd-uk thanks for the ping, my time has been pretty limited lately and I'd otherwise miss this. Pushed a fix in https://github.com/xbmc/xbmc/pull/24402
