### ISSUE TITLE
Prevent Episodeguide from stalling scans.

### ISSUE THREAD

**Issue by KarellenX** [xbmc/xbmc#24559]
### Describe the bug
There has been a long-standing bug in Kodi where if an episodeguide is tagged in a nfo file the scanner calls the scraper to parse the website and search for the episode listing for that tv show.

This behaviour occurs when nfo files are in use, and will even occur when the **Local information only scraper** is set.

The following extract from a log shows the Local Info Only scraper is set and the episodeguide string has come from a tvshow.nfo file.

The result of this behaviour is that the scraper is unable to parse the link to the API due to Local Info scraper being set, so the scan of that entire tv show fails leaving the user confused on why it failed when they have done everything exactly right.

```
debug <general>: ADDON::CScraper::GetEpisodeList: Searching '{"tmdb":"1429","imdb":"tt2560140","wikidata":"Q22126305","tvdb":"267440"}' using Local information only scraper (file: 'C:\Program Files\Kodi\addons\metadata.local\', content: 'tvshows', version: '1.0.1')
debug <general>: CurlFile::XFILE::CCurlFile::Open - <{"tmdb":"1429","imdb":"tt2560140","wikidata":"Q22126305","tvdb":"267440"}>
debug <general>: XCURL::DllLibCurlGlobal::easy_acquire - Created session to ://
error <general>: CCurlFile::CReadState::XFILE::CCurlFile::CReadState::FillBuffer - (0x1e0b47faa00) Failed: URL using bad/illegal format or missing URL(3)
error <general>: CCurlFile::XFILE::CCurlFile::Open - <{"tmdb":"1429","imdb":"tt2560140","wikidata":"Q22126305","tvdb":"267440"}> Failed with code 0:
error <general>: ADDON::CScraper::Run: Unable to parse web site
warning <general>: No information found for item 'smb://192.168.178.56/anime/Attack on Titan (2013)/', it won't be added to the library.
```

The other odd behaviour is that it does not fail immediately. In many instances, most of the show is scanned, then the parsing of the episodeguide fails, and the previously scanned episodes are deleted.

## Expected Behavior
If nfo files are in use, don't automatically parse the episodeguide when it is available. Only parse if an episode has a missing nfo file.

Do not parse the episodeguide if Local Information Scraper is in use.

## Actual Behavior
Always parses the episodeguide when not required causing the scan to fail in most instances.

### To Reproduce
1. 
2.
3.

### Debuglog
The debuglog can be found here:

https://paste.kodi.tv/ulijiropoy.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by 78andyp** [comment]
Hi.
I think I've found the problem(s).
Are you able to build a test version - happy to build windows if needed - my linux is a bit shakey but happy to try.

**Comment by KarellenX** [comment]
Thank you @78andyp for checking this out.

I am a Windows user. Let me ask a dev to kick off a test build.
