### ISSUE TITLE
Omega Beta 2 crashes to desktop

### ISSUE THREAD

**Issue by atrugiel69** [xbmc/xbmc#24566]
### Describe the bug
Here is a clear and concise description of what the problem is:

With latest nightly, as of today, Kodi often crashes to desktop after a few interactions with the interface.

This behavior has been ongoing for weeks now. I initially let it go thinking it was alpha software, then it was beta software but seeing as it remains... I thought about informing developers.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi does not crash to desktop during normal use.

## Actual Behavior

Kodi crashes to desktop after a few user interface interactions. It does not happen always, I have not been able to determine the cause. Sometimes it crashes, sometimes it doesn't. If it doesn't crash within the first 10-20 seconds or so, then it does not crash anymore.

## Possible Fix

No idea.

### To Reproduce

Unfortunately I have no steps to offer. When it crashes it happens after a few seconds, I enter a section (Movie, TV Shows, Settings...) and then after a few items scrolled it crashes.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/guhetewuru.kodi

### Screenshots
Here are some links or screenshots to help explain the problem:

No screenshots can be offered.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

No screenshots, no context.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro x64 22H2 19045.3570 
AMD Ryzen 5 3600, RTX 4070, 16 GB of RAM

 - Kodi version: Kodi Omega nightly, 20240120

I attach the crash files that Kodi creates in the userdata directory.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

[kodi_stacktrace-21.0-BETA2 Git_20240120-986851789a-20240123-030108.txt](https://github.com/xbmc/xbmc/files/14017472/kodi_stacktrace-21.0-BETA2.Git_20240120-986851789a-20240123-030108.txt)
[kodi_crashlog-21.0-BETA2 Git_20240120-986851789a-20240123-030109.dmp](https://github.com/xbmc/xbmc/files/14017473/kodi_crashlog-21.0-BETA2.Git_20240120-986851789a-20240123-030109.dmp)

**Comment by atrugiel69** [comment]
I initially posted the same information without following the template, thinking it was just an example for things needed. Apparently it isn't, so I reloaded it and tried to follow it as closely as possible. The label "ignored rules" remains. I don't know how to make it go away at this point. I'm sorry... :-/

**Comment by CrystalP** [comment]
Please do the same with an official release/pre-release like 21 beta2. 
Nightlies are not suitable because we don't keep the .pdb files required to analyze crash dumps.

Without the .pdb it's still possible to say that the crash happened in a "LanguageInvoker" thread. It was in Kodi address space for the crash but it's still very likely due to one of the installed python addons.

So it would be a good idea to see what happens on a brand new portable install without addons, then after adding the addons one by one.

**Comment by atrugiel69** [comment]
> Please do the same with an official release/pre-release like 21 beta2. Nightlies are not suitable because we don't keep the .pdb files required to analyze crash dumps.
> 
> Without the .pdb it's still possible to say that the crash happened in a "LanguageInvoker" thread. It was in Kodi address space for the crash but it's still very likely due to one of the installed python addons.
> 
> So it would be a good idea to see what happens on a brand new portable install without addons, then after adding the addons one by one.

Ok, I have done the quickest thing I could. I don't know if it will suffice but I wanted to start easy, because the adding addons one by one would be extremely time consuming (even just to understand what to add, to be honest, it's not as if I can easily export a list of addons to add to an empty installation). Plus, this way I suppose you can have a look at the whole installation, "as is", with addons and big library in use.

Attached the two files, from Omega beta 2.
[kodi_stacktrace-21.0-BETA2 Git_20231210-979dbf5fe5-20240123-225846.txt](https://github.com/xbmc/xbmc/files/14030142/kodi_stacktrace-21.0-BETA2.Git_20231210-979dbf5fe5-20240123-225846.txt)
[kodi_crashlog-21.0-BETA2 Git_20231210-979dbf5fe5-20240123-225846.dmp](https://github.com/xbmc/xbmc/files/14030143/kodi_crashlog-21.0-BETA2.Git_20231210-979dbf5fe5-20240123-225846.dmp)

**Comment by CrystalP** [comment]
OK those gave more information about how a python script execution failed (a null pointer encountered during a string assignment)
![image](https://github.com/xbmc/xbmc/assets/489377/b39eb7d3-30f4-43f8-bed4-661e91842cdd)

Going back to your previous log, the crash happened in thread 11332 and its earlier activity seems to show it was executing:
C:\Program Files\Kodi 21\portable_data\addons\service.library.data.provider\service.py

It's not an builtin addon of Kodi, it can be seen executing some music database queries. Maybe it's a skin helper script, I'm not really knowledgeable about addons or python.
Maybe by navigating your addons you could figure out what got it installed on your system and try without it?

**Comment by atrugiel69** [comment]
It's probably this: https://forum.kodi.tv/showthread.php?tid=210063&pid=3132851#pid3132851

I'll try to run the fixed version that was submitted to MikeSiLVO repository (but never merged) and see if I still have the crashes.
Aeon Nox is the skin needing it. If only my beloved Transparency! was still around... :(
I'll report back.

**Comment by MikeSiLVO** [comment]
FYI, that script is no longer used. You can delete it and still use the skin.

**Comment by atrugiel69** [comment]
I have uninstalled Amber and Aeon Nox skins and for now crashes seem to have stopped. I'll report back in case they resurface.

**Comment by CrystalP** [comment]
Closing since resolved by removal of offending addon "service.library.data.provider" not used anymore.
