### ISSUE TITLE
Duplicated Entries in Context Menu

### ISSUE THREAD

**Issue by KarellenX** [xbmc/xbmc#24560]
### Describe the bug
After installing **KodiSetup-20240120-98685178-master-x64** today, I noticed duplicated context menu entries as shown in the image below.

My previous install was **KodiSetup-20240108-f6e78bff-master-x64.exe**

So, sometime between these two nightlies there was a change that affected Context Menu.

## Expected Behavior
No duplication

## Actual Behavior
Duplicated context menu entries

### To Reproduce

1. 
2.
3.

### Debuglog
The debuglog can be found here:
Nil

### Screenshots 
Here are some links or screenshots to help explain the problem:

![duplicate](https://github.com/xbmc/xbmc/assets/44626605/beae72c0-fa79-4762-bfb9-569d260a7879)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
@KarellenX can you be a bit more specific where exactly you see the duplicate entries? Seems to by by far not to happen everywhere.

**Comment by ksooo** [comment]
Caused by https://github.com/xbmc/xbmc/pull/24461 - @enen92 please take over and fix, thanks.

**Comment by KarellenX** [comment]
Correct. It happened when navigating to a Source. 
Videos>Files then context menu for the Source or into the source to a folder but not on the video files.

Checking elsewhere - movies, tv show, favourites - it didn't happen there, only in the Videos>Files section.

**Comment by KarellenX** [comment]
Also happens with Music sources.
