### ISSUE TITLE
[macOS] play/pause system hotkey affects the system Music app

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/xbmc#24579]
### Describe the bug
Here is a clear and concise description of what the problem is:

When you press the play/pause system hotkey (that's usually on F8 on Apple keyboards), besides toggling playback in Kodi the standard Music app also opens. I believe if Music was opened, then it'd start playing something (if you have items in the library).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Nothing happens to the Music app

## Actual Behavior

Music app reacts play/pause hotkey

### To Reproduce

0. Close Music app if it's opened
1. play an item in Kodi
2. press system play/pause hotkey
3. observe that Music app opens

### Debuglog

The debuglog can be found here: will provide if required

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

VLC doesn't suffer from this for example

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS Ventura - ARM
 - Kodi version: today's Omega nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
I don't think you can solve this (searched a lot back then). Afaik this is handled internally in the os for a list of authorized apps only...

**Comment by kambala-decapitator** [comment]
well, VLC solved that somehow... Maybe an internal AVPlayer object that does nothing can help.

**Comment by enen92** [comment]
They use https://github.com/nevyn/SPMediaKeyTap if memory serves me well

**Comment by kambala-decapitator** [comment]
> Maybe an internal AVPlayer object that does nothing can help.

my assumption was almost correct: in a sample project I can control AVPlayer with the play/pause key. So I see the following solution: once Kodi starts playing an item, create an internal native player object that loops a short black video (AVPlayerLooper can do it out of the box) and "observe" the `rate` property of AVQueuePlayer: when you receive 0, then pause was pressed, and 1 is play. I created short black video with ffmpeg and then removed sound from it (simply googled the necessary commands):

```
ffmpeg -f lavfi -i color=size=50x50:rate=25:color=black -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 -t 5 ~/Desktop/1.mp4
ffmpeg -i /Users/kambala/Desktop/1.mp4 -map 0:v -c copy /Users/kambala/Desktop/2.mp4
```

@enen92 are you interested in testing your objc skills for this? :)

**Comment by enen92** [comment]
> > Maybe an internal AVPlayer object that does nothing can help.
> 
> my assumption was almost correct: in a sample project I can control AVPlayer with the play/pause key, but it must play something.
> 
> So I see the following solution: once Kodi starts playing an item, create an internal native player object that loops a short black video (AVPlayerLooper can do it out of the box) and "observe" the `rate` property of AVQueuePlayer: when you receive 0, then pause was pressed, and 1 is play. I created short black video with ffmpeg and then removed sound from it (simply googled the necessary commands):
> 
> ```
> ffmpeg -f lavfi -i color=size=50x50:rate=25:color=black -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 -t 5 ~/Desktop/1.mp4
> ffmpeg -i /Users/kambala/Desktop/1.mp4 -map 0:v -c copy /Users/kambala/Desktop/2.mp4
> ```
> 
> @enen92 are you interested in testing your objc skills for this? :)

Unfortunately I don't have much time at the moment and the solution is also less than optimal for really a small advantage...
Are you sure VLC does this? I think there's some easier hack somewhere hidden in spmediatap. When I added this I couldnt figure it out but haven't really dedicated a lot of time to it. Even adding that dependency is not optimal (it's yet another one for such a small advantage).

**Comment by kambala-decapitator** [comment]
> Unfortunately I don't have much time at the moment

no problem of course, you're not obliged to implement it :)

> really a small advantage.

I wouldn't call it so, at least for me it's a rather important / convenient feature, and the fact that Music app opens is quite irritating

> Are you sure VLC does this?

no, I haven't checked that VLC actually does, just a way I imagined that would have worked

> spmediatap

that approach with an "exclusive lock" and a whitelist of apps looks quite terrible to me, I wouldn't use such "dangerous" things in "production"

P.S. Just remembered that there's an API to work with external remote events (like receiving play/pause from a headset), maybe that one would work as well without the need of an invisible AVPlayer, will test.

**Comment by kambala-decapitator** [comment]
> P.S. Just remembered that there's an API to work with external remote events (like receiving play/pause from a headset), maybe that one would work as well without the need of an invisible AVPlayer, will test.

unfortunately, it doesn't (MPRemoteCommandCenter)

**Comment by kambala-decapitator** [comment]
> They use https://github.com/nevyn/SPMediaKeyTap if memory serves me well

yes, you're right: https://github.com/videolan/vlc/tree/master/modules/gui/macosx/imported/SPMediaKeyTap

**Comment by enen92** [comment]
> > Unfortunately I don't have much time at the moment
> 
> no problem of course, you're not obliged to implement it :)
> 
> > really a small advantage.
> 
> I wouldn't call it so, at least for me it's a rather important / convenient feature, and the fact that Music app opens is quite irritating
> 
> > Are you sure VLC does this?
> 
> no, I haven't checked that VLC actually does, just a way I imagined that would have worked
> 
> > spmediatap
> 
> that approach with an "exclusive lock" and a whitelist of apps looks quite terrible to me, I wouldn't use such "dangerous" things in "production"
> 
> P.S. Just remembered that there's an API to work with external remote events (like receiving play/pause from a headset), maybe that one would work as well without the need of an invisible AVPlayer, will test.

While I agree with the "list of apps" part I believe the lib only does this to resign the key to other apps if the app is not focused and another one was focused before. We could probably take a simpler approach, by getting exclusive usage of the keys if running fullscreen or if the app is the one receiving input. The part I don't understand about the lib is the "exclusive" handle of the keys. Maybe you can help out figuring out the bits that block the key from being handled elsewhere?

**Comment by kambala-decapitator** [comment]
> I believe the lib only does this to resign the key to other apps if the app is not focused and another one was focused before

as I see, the lib listens to the current app change and stops intercepting keys if an app from the whitelist is activated https://github.com/videolan/vlc/blob/master/modules/gui/macosx/imported/SPMediaKeyTap/SPMediaKeyTap.m#L335

> We could probably take a simpler approach, by getting exclusive usage of the keys if running fullscreen or if the app is the one receiving input

as I understand, this "exclusive usage" is achieved by inserting the current app on top of the tap queue: https://github.com/videolan/vlc/blob/master/modules/gui/macosx/imported/SPMediaKeyTap/SPMediaKeyTap.m#L108 If we follow this approach, it won't protect us from starting VLC or any other app after Kodi.

> The part I don't understand about the lib is the "exclusive" handle of the keys

it's [returning NULL](https://developer.apple.com/documentation/coregraphics/cgeventtapcallback) for "eaten" events: https://github.com/videolan/vlc/blob/master/modules/gui/macosx/imported/SPMediaKeyTap/SPMediaKeyTap.m#L291

> As far as I remember returning the event on the handle or simply returning null had no effect whatsoever

based on the doc, this is true only for passive taps

> We could probably take a simpler approach, by getting exclusive usage of the keys if running fullscreen or if the app is the one receiving input

maybe we should even make it more strict: enable the tap only when something is playing

**Comment by enen92** [comment]
> > I believe the lib only does this to resign the key to other apps if the app is not focused and another one was focused before
> 
> as I see, the lib listens to the current app change and stops intercepting keys if an app from the whitelist is activated https://github.com/videolan/vlc/blob/master/modules/gui/macosx/imported/SPMediaKeyTap/SPMediaKeyTap.m#L335
> 
> > We could probably take a simpler approach, by getting exclusive usage of the keys if running fullscreen or if the app is the one receiving input
> 
> as I understand, this "exclusive usage" is achieved by inserting the current app on top of the tap queue: https://github.com/videolan/vlc/blob/master/modules/gui/macosx/imported/SPMediaKeyTap/SPMediaKeyTap.m#L108 If we follow this approach, it won't protect us from starting VLC or any other app after Kodi.
> 
> > The part I don't understand about the lib is the "exclusive" handle of the keys
> 
> it's [returning NULL](https://developer.apple.com/documentation/coregraphics/cgeventtapcallback) for "eaten" events: https://github.com/videolan/vlc/blob/master/modules/gui/macosx/imported/SPMediaKeyTap/SPMediaKeyTap.m#L291
> 
> > As far as I remember returning the event on the handle or simply returning null had no effect whatsoever
> 
> based on the doc, this is true only for passive taps
> 
> > We could probably take a simpler approach, by getting exclusive usage of the keys if running fullscreen or if the app is the one receiving input
> 
> maybe we should even make it more strict: enable the tap only when something is playing

I see, thanks for the explanation. It makes perfect sense.
I was somehow expecting to be able to do the same using just AppKit but it seems the only way to have an active tap is to use lower level apis like core graphics - active tap on top of the queue - any other way just enables you to be a monitor of events.
I am not seeing a better way to handle this to be honest. I don't like the black video solution (just too hacky).

Your idea of enabling the tap only when something is playing may be a good lead. Maybe we can make sure the CG tap is always the first one on the list when the app is focused (recreating the tap on such cases). If somehow you open vlc it'll be the one receiving input but focusing Kodi will recreate the tap anyway bypassing vlc. We can always contribute the Kodi app id to vlc anyway.

**Comment by kambala-decapitator** [comment]
> I am not seeing a better way to handle this to be honest. I don't like the black video solution (just too hacky).

me neither. Yeah, the tap approach looks way better. But still I'd like to test the black video approach together with VLC running, although I expect VLC to eat key presses.

> Maybe we can make sure the CG tap is always the first one on the list when the app is focused (recreating the tap on such cases)

hope it's fine to destroy/create taps frequently (in case of switching between VLC and Kodi back and forth)

> If somehow you open vlc it'll be the one receiving input (and honestly it makes sense) but focusing Kodi will recreate the tap anyway bypassing vlc

I remember there's an ability to use external player in Kodi (never used it personally) - I guess in this case tap recreation should be prevented

> We can always contribute the Kodi app id to vlc anyway

definitely. And I think we should also use the tap lib from VLC (they fixed a crash, wouldn't hurt) instead of writing the same on our own, but with some modifications for tap re-creation.
