### ISSUE TITLE
Art in "Manage Extras" for Movies Without Extras

### ISSUE THREAD

**Issue by CrystalP** [xbmc/xbmc#24588]
### Describe the bug

The Info > Manage Extras dialog shows art even if there are no extras for the movie:

![image](https://github.com/xbmc/xbmc/assets/489377/a8c0d2b1-343a-4742-81b0-0041b2403263)

## Expected Behavior

No art when no extra, art of the extra when there is an extra selected.

## Possible Fix

Not sure where this comes from, likely from the skin?

### To Reproduce

1. For a movie without extras
2. Go to Info dialog
3. Go to Extras
4. Artwork is displayed

### Debuglog

The debuglog can be found here: not relevant https://paste.kodi.tv/irrelevant.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21 current master though it's been like that since beta2 at least

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Hitcher** [comment]
Removing this line fixes it:

https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/Variables.xml#L691

Didn't notice any side effects without it.

@jjd-uk ?

**Comment by jjd-uk** [comment]
It was done that way on purpose to always have art displayed so you have the visual prompt of the movie you are working on, in the case of empty lists it takes the art of the parent library entry. I can change it if people prefer it without any art, however I'd like to get more feedback.

**Comment by jjd-uk** [comment]
Actually on reflection it makes less sense having that fallback for both Versions and Extras, so I'll remove this for Extras and instead have this if the Extras list is empty

![image](https://github.com/xbmc/xbmc/assets/5781142/d71704e8-1008-4de7-bd02-1c9d19815059)

**Comment by CrystalP** [comment]
Empty list will never happen for versions, as there is always at least a default version, that cannot be removed.
