### ISSUE TITLE
Compile of Kodi for wayland is failing with - non-existent target "libkodi".

### ISSUE THREAD

**Issue by heitbaum** [xbmc/xbmc#24586]
### Describe the bug
Here is a clear and concise description of what the problem is:

Wayland target compile (of Kodi Omega master) on LibreELEC is failing with `non-existent target "libkodi".`

Commenting out the following line allows the compile to proceed.

https://github.com/xbmc/xbmc/blob/41c4a59fc315df1d4c97c591188fb2cde216851f/cmake/scripts/linux/ExtraTargets.cmake#L39

detail:
- https://github.com/LibreELEC/LibreELEC.tv/issues/8271

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I did a test compile using with the before #23612 successfully.

## Actual Behavior

Since https://github.com/xbmc/xbmc/pull/23612 the Wayland build fails
- https://github.com/xbmc/xbmc/commit/f8573a7247e41cb5c1c7d738a898f5a88c40d348
```
CMake Error at cmake/scripts/linux/ExtraTargets.cmake:39 (add_dependencies):
  Cannot add target-level dependencies to non-existent target "libkodi".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.
Call Stack (most recent call first):
  CMakeLists.txt:581 (include)
```

## Possible Fix

Unknown

### To Reproduce

1. Compile Kodi with waylaid support with patch #23612
2.
3.

### Debuglog

The debuglog can be found here:

NA

### Screenshots 
Here are some links or screenshots to help explain the problem:

NA

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

NA

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 12.0
 - Kodi version: Omega:master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Im not sure how this could actually fail. It doesnt on jenkins builds at the very least.

https://jenkins.kodi.tv/job/LINUX/69510/console

the target is executed.

```
17:42:57 [  2%] Generating wayland-protocols C++ wrappers
17:42:57 [  8%] Building CXX object taglib/CMakeFiles/tag.dir/mpeg/id3v2/id3v2tag.cpp.o
17:42:57 -- Performing Test HAVE_TALLOC_TEVENT - Failed
17:42:57 -- Performing Test HAVE_CLOCK_GETTIME
17:42:57 [  2%] Built target generate-wayland-extra-protocols
```

the lib${APP_NAME_LC} target exists  at https://github.com/xbmc/xbmc/blob/22e94fbec0a8489717fd3739f0750fb827479b84/CMakeLists.txt#L392
The extratargets scripts arent added until https://github.com/xbmc/xbmc/blob/22e94fbec0a8489717fd3739f0750fb827479b84/CMakeLists.txt#L593

Its just an include, and not a function or anything else that would potentially screw with scope.
Is there something else libreelec might be doing/modifying somewhere maybe?

**Comment by heitbaum** [comment]
Fixed by https://github.com/LibreELEC/LibreELEC.tv/pull/9357
