### ISSUE TITLE
Display HDR capabilities are being misdetected (SDR detected as HDR)

### ISSUE THREAD

**Issue by rsalvaterra** [xbmc/xbmc#24585]
### Describe the bug
$subject, basically. HDR to SDR tone mapping isn't working anymore on an Apollo Lake (Pentium N4200, Intel Gen9 iGPU) system, with the GBM backend. It has been working fine with the X11 backend. Note that it works just fine on both Haswell (Core i5-4250U) Gen7 and Alder Lake (Intel N100) Gen12 systems, only this Apollo Lake system seems to be affected.

## Expected Behavior
HDR to SDR tone mapping should work, the same way it worked with the X11 backend.

## Actual Behavior

HDR to SDR tone mapping doesn't work.

### To Reproduce

1. Enable HDR to SDR tone mapping.
2. Play an adequate video.

### Debuglog

https://paste.kodi.tv/gewusedovi.kodi

### Your Environment
Used Operating system:

- [ ] Android
- [ ] iOS
- [ ] tvOS
- [x] Linux
- [ ] macOS
- [ ] Windows
- [ ] Windows UWP

 - Operating system version/name: LibreELEC nightly, https://github.com/LibreELEC/LibreELEC.tv/commit/40b8914fbdb41e6676f9885553360f7cfbef72d5.
 - Kodi version: commit 06e228046c9f1316c7585bd61bfa1e28e22382da.

**Comment by sarbes** [comment]
Define not working.

**Comment by rsalvaterra** [comment]
> Define not working.

I wasn't expecting that question, but when I mean "not working" I mean "it's a no-op". Selecting any tone mapping curve (either Reinhard, Hable or ACES Filmic) doesn't change the video output. It's the exact same as having tone mapping disabled (washed out colour on an ordinary SDR TV).

**Comment by rsalvaterra** [comment]
I see this in my debug log…
```
2024-01-27 14:21:47.423 T:813     debug <general>: SetHDR: setting connector colorspace to Default
2024-01-27 14:21:47.424 T:813     debug <general>: LinuxRendererGLES::Configure: fps: 23.976
2024-01-27 14:21:47.424 T:813     debug <general>: LinuxRendererGLES::Configure: HDR passthrough: on
```
… which _might_ be related? I have no idea why HDR passthrough is enabled (or how to disable it, for that matter; I don't remember ever seeing a GUI toggle for it, anywhere). The TV connected to the player doesn't support HDR in any shape or form, that's for sure.

**Comment by rsalvaterra** [comment]
And the [related code](https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp#L135-L140)…

```
  if (picture.hasDisplayMetadata && picture.hasLightMetadata)
  {
    m_passthroughHDR = CServiceBroker::GetWinSystem()->SetHDR(&picture);
    CLog::Log(LOGDEBUG, "LinuxRendererGLES::Configure: HDR passthrough: {}",
              m_passthroughHDR ? "on" : "off");
  }
```
… am I missing something…? Could this be a configuration issue on my side?

**Comment by chewitt** [comment]
Settings > Player > Video > Playback now has an "Adjust display HDR mode" setting which I think defaults to ON and thus changes the behaviour. This will have surfaced in recent LE nightlies (in the last month IIRC). If you toggle this setting to OFF it should restore the previous behaviour?

**Comment by rsalvaterra** [comment]
> Settings > Player > Video > Playback now has an "Adjust display HDR mode" setting which I think defaults to ON and thus changes the behaviour. This will have surfaced in recent LE nightlies (in the last month IIRC). If you toggle this setting to OFF it should restore the previous behaviour?

Yes, I'm aware of that setting. I'm _almost_ sure that toggling it had no effect, but I'll retest this evening.

**Comment by rsalvaterra** [comment]
> > Settings > Player > Video > Playback now has an "Adjust display HDR mode" setting which I think defaults to ON and thus changes the behaviour. This will have surfaced in recent LE nightlies (in the last month IIRC). If you toggle this setting to OFF it should restore the previous behaviour?
> 
> Yes, I'm aware of that setting. I'm _almost_ sure that toggling it had no effect, but I'll retest this evening.

Well, this is interesting. While I _do_ remember seeing that setting, it might have been on a different machine. The fact is, it doesn't show up at all.

![screenshot00000](https://github.com/xbmc/xbmc/assets/73969060/8a3d47b1-6a35-41fb-b307-228625f2f94f)

In Kodi's `guisettings.xml` file, however, I have…

`<setting id="winsystem.ishdrdisplay" default="true">true</setting>`

Does the "Adjust display HDR mode" toggle this boolean?

**Comment by chewitt** [comment]
The setting visibility is conditional on an HDR display being present, and defaults to true. Kodi saves `guisettings.xml` on exit so you're probably editing it to false then Kodi overwrites it on shutdown. You can probably fix that by stopping Kodi, editing the file to set this setting to false, then restarting Kodi.

**Comment by rsalvaterra** [comment]
> The setting visibility is conditional on an HDR display being present, and defaults to true. Kodi saves `guisettings.xml` on exit so you're probably editing it to false then Kodi overwrites it on shutdown. You can probably fix that by stopping Kodi, editing the file to set this setting to false, then restarting Kodi.

Like I wrote in my previous comment, after the screenshot, I stopped the Kodi service (`systemctl stop kodi.service`) and made sure the process was effectively stopped before editing the file. However, when Kodi starts, it resets that boolean back to `true`.

**Comment by rsalvaterra** [comment]
> Well, this is interesting. While I _do_ remember seeing that setting, it might have been on a different machine. The fact is, it doesn't show up at all.

I just fired up my Alder Lake machine, which is a connected to a 4k Samsung (SDR) TV. As expected, the "Adjust display HDR mode" setting is also hidden, but HDR to SDR tone mapping works just fine.

**Comment by jjd-uk** [comment]
To force a guisetting to a value you can try using this method https://kodi.wiki/view/Advancedsettings.xml#guisettings.xml_Setting_Conversion

From this I assume it would need to be in the form

```
<advancedsettings version="1.0">
     <winsystem>
          <ishdrdisplay>false</ishdrdisplay>
     </winsystem>
</advancedsettings>
```

**Comment by rsalvaterra** [comment]
> To force a guisetting to a value you can try using this method https://kodi.wiki/view/Advancedsettings.xml#guisettings.xml_Setting_Conversion
> 
> From this I assume it would need to be in the form
> 
> ```
> <advancedsettings version="1.0">
>      <winsystem>
>           <ishdrdisplay>false</ishdrdisplay>
>      </winsystem>
> </advancedsettings>
> ```

Nice, will test ASAP. Is there any way to know the setting was overridden (i. e., a way to dump the effective configuration from Kodi)?

**Comment by jjd-uk** [comment]
You should see it being loading in a debug log I believe, but that probably just tells that it's been accepted and not that it does anything. The strange thing here is why the switching to HDR mode appears to happen when your display is not HDR capable, and at least the setting part of Kodi recognises this, so why does the renderer think different I have no idea.

This is not an issue I can help with, I'm just purely commenting to tell about that advancesettings trick to force guisettings since no one else mentioned it.

**Comment by rsalvaterra** [comment]
Meanwhile, I managed to get a debug log from my Alder Lake system, [here](https://paste.kodi.tv/tigatononi.kodi). And, sure enough…

`2024-01-30 15:39:16.023 T:891     debug <general>: LinuxRendererGLES::Configure: HDR passthrough: off`

**Comment by rsalvaterra** [comment]
> This is not an issue I can help with, I'm just purely commenting to tell about that advancesettings trick to force guisettings since no one else mentioned it.

No worries, I'll gladly take any help I can get. :wink:

**Comment by jjd-uk** [comment]
Something that maybe of help to those who do have the knowledge is what does **System Infomation -> Video** show, since this will also so if Kodi thinks your display is HDR capable.

**Comment by rsalvaterra** [comment]
> Something that maybe of help to those who do have the knowledge is what does **System Information -> Video** show, since this will also so if Kodi thinks your display is HDR capable.

I'm pretty sure it reports that the TV doesn't support HDR, but I'll take a screenshot when I get to it, yes.

**Comment by rsalvaterra** [comment]
I have good and bad news. So, according to the image below, as expected, LibreELEC says the TV doesn't support HDR, which is correct…

![screenshot00000](https://github.com/xbmc/xbmc/assets/73969060/88a2b0ec-2673-46f7-ab26-939bce5dd37d)

… and in addition, @jjd-uk's `advancedsettings.xml` suggestion worked perfectly. Tone mapping is functional again.

However, I then proceeded to remove the `advancedsettings.xml` file, to see if the changes persisted in the normal `guisettings.xml` and sure enough…

```
apollolake:~/.kodi/userdata # grep hdr guisettings.xml 
    <setting id="winsystem.ishdrdisplay">false</setting>
apollolake:~/.kodi/userdata #
```

While I have no idea how or why `winsystem.ishdrdisplay` became `true` in the first place (I have no HDR displays at all), my question is: why did I have to go through all these hoops? Why doesn't the `winsystem.ishdrdisplay` revert automatically to `false` when a HDR display isn't detected? Or why isn't the GUI toggle always available, in order to at least allow to user to force a specific setting?

**Comment by rsalvaterra** [comment]
So, today, unfortunately, I had a power loss during an update, which made me lose my configuration (obviously expected, no issues there). What was **not at all** expected was the `winsystem.ishdrdisplay` having reverted to `true`, when the connected TV is SDR. This means the HDR capabilities of the display are being misdetected.
