### ISSUE TITLE
High Temperature and Power consumption on Mac arm64

### ISSUE THREAD

**Issue by jamescage** [xbmc/xbmc#24594]
<img width="1325" alt="KODI_21" src="https://github.com/xbmc/xbmc/assets/14264176/27b395ad-39b1-4a3b-b768-8de75b6edfe6">
<img width="1322" alt="KODI_20" src="https://github.com/xbmc/xbmc/assets/14264176/2c0f86d5-9a66-4384-a4f6-3de3be52f0bb">

### Describe the bug
Here is a clear and concise description of what the problem is:
When I run the latest development build (I have also tried with Beta 2) temperature and power consumption goes high as hell. Everything is normal with version 20.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 MacOS Sonoma 14.3 (but the behavior is the same with earlier versions)
 - Kodi version:
[kodi-20240127-b104e068-master-3374-arm64](https://mirrors.kodi.tv/nightlies/osx/arm64/master/kodi-20240127-b104e068-master-3374-arm64.dmg)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@jamescage provide a debug log otherwise this will be closed. Thanks.
