### ISSUE TITLE
Kodi Stop Playback when 1 minutes play

### ISSUE THREAD

**Issue by stbtv1** [xbmc/xbmc#24593]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi Stop Playback when 1 minutes play,
when i play pvr iptv simple client from HD channel list, every 1 minute stop playback and back to channel list,
but i play not HD channel list is normal no problem, please help me, i dont know what wrong, thanks

### Your Environment
Used Operating system:

 - [ ] Windows
 - [ ] WebOS

 - Operating system version/name: windows 11 and WebOs 7.4
 - Kodi version: 20.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Please seek for assistance at our forums first. 

https://forum.kodi.tv/

Most likely that list contains streams that are not legal to shared via IPTV. But we'll see that if you ask your question at the forums and also provide a source for that list and a debuglog as well. 

Anyway...this section isn't a support section. It's for bug reports and your problem doesn't sound like it's a bug.
