### ISSUE TITLE
cURL: Why do we even bother checking if we're online in this way only to fall back to just parsing a URL without loading

### ISSUE THREAD

**Issue by ilikenwf** [xbmc/xbmc#24595]
### Describe the bug
So this function:
https://github.com/xbmc/xbmc/blob/b11eb7ccf761424bb68e35189e393b1739286b83/xbmc/filesystem/CurlFile.cpp#L1020

Is silly and by my recollection doesn't really serve any purpose because it falls back to just parsing a valid URL for no reason...and the URL it uses to check if online should be user settable as I don't personally like my machines hitting microsoft's servers all the time.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

**Comment by ilikenwf** [comment]
The bot is annoying but I hate this function using a hard coded url.

**Comment by garbear** [comment]
> The bot is annoying but I hate this function using a hard coded url.

I mean, "I hate this URL" is a pretty poor issue, better would be to create a PR with a more likeable URL. Discussion would ensue, we would weigh the costs/benefits, and would possibly align with a URL to your liking.

**Comment by ilikenwf** [comment]
Maybe I'll PR sometime, I get grumpy at night.

Even something like kodi.tv/online.txt or put an online.txt somewhere in a git repo instead...but meh.

**Comment by garbear** [comment]
> kodi.tv/online.txt

Not gonna lie, I hate the M$ URL too. But putting it on our infra will for surely fail at some point and cause fallout which we don't need and can't handle. So we're relatively satisfied using the same system as basically the rest of the planet, checking a text file on MS's servers.

I'm increasingly interested in this issue as my company might use the microsoft text file in the interim while we switch between data ingestors (could be a few weeks). I really don't see a huge downside. Do you? Is there something we should be aware of, considering we fallback to w3c.org if the MS text file doesn't resolve?

**Comment by ilikenwf** [comment]
@garbear to be fair github is MS, but using github blends in more with most of our practices compared to other methods...

Firefox and other browsers tend to look for an http 204 response code, which doesn't return any data but returns "204" which is a "no response" code but still valid because of the 2XX value, making it super fast.

I'd rather use a mozilla connectivity test endpoint, or one hosted elsewhere..I just kinda freaked when I saw it because I run an all Linux/BSD network here and was perturbed to see an MS url in my firewall logs. Having it be a configurable, even if by advancedsettings.xml or something would be pretty nice.

That said, curl already has native handling for connection errors, so I don't know why we need to necessarily know, at least with remote connections, if we are "online" or not at all since curl will always gladly tell us anyway?

**Comment by ilikenwf** [comment]
Another option would be to instead to maybe use something like cloudflare's dns over https resolver to resolve kodi.tv or something...or just plain system DNS to resolve something.

While it doesn't necessarily provide that you're receiving data (an http 204 would) via the protocol it proves that you're connected to something.
