### ISSUE TITLE
Trailing "..." now showing as leading for longer title if using <align>right</align> in label

### ISSUE THREAD

**Issue by latts9923** [xbmc/xbmc#24610]
### Describe the bug
Here is a clear and concise description of what the problem is:

If I use <align>right</align> for a label and the title is longer than the set width, what used to be a trailing "..." is now showing as leading.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The "..." should display at the end of a longer title.

## Actual Behavior

The "..." is now showing at the front of a longer title.

### To Reproduce

1. Create a label with a width value that cannot display the entire title.
2. Add <align>right</align> to the label.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://holybid.com/images/screenshots/Aeon_MQ_9_Omega_right.png

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
21.0 BETA2 (20.90.821)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Markman-B** [comment]
I can confirm this issue on Android - Kodi 21 beta 2.

![Screenshot_20240130_173653_Gallery](https://github.com/xbmc/xbmc/assets/2151113/5140e579-a9f2-4a52-b08e-fec37c39e897)

**Comment by scott967** [comment]
"trailing" and "leading" have different connotations if your UI is LTR/RTL

**Comment by scott967** [comment]
![screenshot00010](https://github.com/xbmc/xbmc/assets/11218744/69559982-f03d-4a0d-b838-8233bb93db7e)

**Comment by CastagnaIT** [comment]
i think could be a kind of "side effect" of a my old PR (https://github.com/xbmc/xbmc/pull/22691) to have trailing dots "..." on the left for the right aligned text
that is used for GUI settings that have double text labels (left-description + right-value)
i think that should be added a new parameter to label control to choose the truncation position and so the relative "..." dots position

**Comment by CrystalP** [comment]
The new behavior seems more correct to me, the ellipsis is supposed to replace the truncated text, which happens to be to the left, when right-aligning.

**Comment by MikeSiLVO** [comment]
I think it should remain as it always was (LTR).
When looking at a list in, most languages, I'd expect to be able to read the start of the item and not the tail end of it.

I don't want to be exclusionary so maybe there is some way to make the RTL/LTR of the language control this?

Default LTR

Arabic / Aramaic / Azeri / Dhivehi / Maldivian / Hebrew / Kurdish / Persian / Urdu (RTL)
The list is shorter on the RTL  side.

No idea if this is feasible or not but displaying the end of a sentence for the majority of languages seems like the opposite of what should be done.

**Comment by CastagnaIT** [comment]
by check the source code i dont see there is a check for RTL/LTR used to establish the text truncate position (left/right)

example old kodi behaviour:
![immagine](https://github.com/xbmc/xbmc/assets/3257156/cf45af5e-e75d-4ebb-80ac-7fa4186c01f6)

current master:
![immagine](https://github.com/xbmc/xbmc/assets/3257156/87447ad5-1de8-4f2f-9bd1-806b04f1ff6b)

i can confirm that currenlty its not ideal in this situation
i think the best thing for now is restore the default LTR truncation
and add a new control setting like "reversedTruncate", where can be used e.g. for the specific GUI settings

add an automatic truncate position by checking RTL/LTR text i think its too much invasive at current development stage
i will try check if im able do the mentioned change

**Comment by CastagnaIT** [comment]
if someone can give a feedback for the fix there are some test builds:
android ARM: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20240202-a27b3d71-truncate_text_edit-armeabi-v7a.apk
android ARM64: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20240202-a27b3d71-truncate_text_edit-arm64-v8a.apk
Windows: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240202-a27b3d71-truncate_text_edit-x64.exe

**Comment by CrystalP** [comment]
ok there was no "before" screenshot in the issue. Yes if the expectation is the truncation of the end of the text then the ellipsis should be on the right as well.

**Comment by scott967** [comment]
Again, in a bidi world "end of text" means "logical end" of string and "visual display" is different, and a problem when a neutral direction character like punctuation is at the logical beginning or end of string, as bidi algorithm specifies that a higher level direction variable determines if it is treated as LTR or RTL (assuming no explicit direction control unicode in the string).  Right justified would be "normal" alignment in RTL script, so ellipsis visually to the left is expected.

**Comment by latts9923** [comment]
@CastagnaIT 
I just installed your test build, and the truncated title is now displaying the "..." on the right side of the text.
![Aeon_MQ_9_Omega_right_test](https://github.com/xbmc/xbmc/assets/3874066/cb2cbc84-309d-4dbb-b1ca-7eb3b5585535)

If it's determined that RTL text should display the "..." on the left side of the label, it would be nice to have the option to switch it by adding a new control setting like "reversedTruncate". Thanks for your time!

**Comment by CastagnaIT** [comment]
@CrystalP  the "before" screenshot appears like comment above here (so https://github.com/xbmc/xbmc/issues/24610#issuecomment-1924766455)

**Comment by CastagnaIT** [comment]
I had to change the previous fix
it would be helpful to have new feedback with one of these test builds:
Windows: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240304-78004ff5-truncate_text_edit-x64.exe
Android64: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20240304-78004ff5-truncate_text_edit-arm64-v8a.apk
Android http://mirrors.kodi.tv/test-builds/android/arm/kodi-20240304-78004ff5-truncate_text_edit-armeabi-v7a.apk
