### ISSUE TITLE
Select dialogs for versions/extras no longer have the movie name

### ISSUE THREAD

**Issue by jjd-uk** [xbmc/xbmc#24616]
### Describe the bug
Header for the version and extra selection dialogs no longer has the movie name.

![image](https://github.com/xbmc/xbmc/assets/5781142/92faf3d7-528f-43e1-bf75-699e3b2a8e64)

![image](https://github.com/xbmc/xbmc/assets/5781142/f11e311a-a096-4e3f-a672-57064628147b)

## Expected Behavior
Header for the version and extra selection dialogs should have the movie name similar to the manage dialogs.

![image](https://github.com/xbmc/xbmc/assets/5781142/4737c70a-7969-4b6e-a6f4-75da2ebacbb1)

![image](https://github.com/xbmc/xbmc/assets/5781142/a16f0726-5e6d-46f6-9bd7-a465c7d944f1)

We orignally did have this but it got lost in the switch over to dialog select I think.

## Actual Behavior

The movie name in the dialog header was lost when version/extra selection was moved to dialog select.

## Possible Fix
Align with the Manage dialogs and restore movie name.

### To Reproduce
Select movie library item that has versions added.
Select movie library item that has extras added.

### Debuglog
The debuglog can be found here: not relevant [paste.kodi.tv/irrelevant.kodi](https://paste.kodi.tv/irrelevant.kodi)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CrystalP** [comment]
Do you have a suggestion? I'm not very aware of the style used in other dialogs.

"Choose version: The Last of the Mohicans" for consistency with versions manager
"Choose version - The Last of the Mohicans" for consistency with versions manager
"Choose version of The Last of the Mohicans"
"Choose a version of The Last of the Mohicans"
or flip things around "The Last of the Mohicans - Choose version"
or... ?

**Comment by jjd-uk** [comment]
This is how it was before

![image](https://github.com/xbmc/xbmc/assets/5781142/eb0d4877-253a-4da0-a697-6f044adb408d)

![image](https://github.com/xbmc/xbmc/assets/5781142/6924d792-433e-4b1b-9d5f-4dd2864198f5)


That would be consistant with the Manager dialogs.
