### ISSUE TITLE
Choose dialog for versions added to favorites / No Choose dialog for movies added to favorites

### ISSUE THREAD

**Issue by CrystalP** [xbmc/xbmc#24628]
### Describe the bug

After adding a version to the favorites, selecting it in the Favorites screen opens the Choose dialog.

~~Opposite situation: with the setting to show versions as a subfolder off, after adding a movie with multiple versions to the favorites, selecting it browses into the version.~~

EDIT: Works as designed. If the setting is ON, a favourite for browsing the versions will be created. If it is OFF a favourite to play the default movie version will be created. But once the favourite is created, changing the setting value has no effect on the behaviour of the favourite.

## Expected Behavior

Specific version (from the folder representing the versions of a movie) added as favorite: the default select action is applied to the version, there is no Choose version dialog.

Movie with multiple versions added as favorite: Choose dialog if "Show versions as folder" is OFF, browse into the versions if "Show versions as folder" is ON. Regardless of setting, a context menu > Play should play the default version (currently always browses into versions of the movie and no context menu Play button)

## Possible Fix

Add missing "has_resolved_video_asset" property to items, but this may be more complicated since the favorite items are persisted,
I don't know if properties are serialized/deserialixed with the items.

### To Reproduce

1. Set "Show videos with multiple versions as folder" to ON
2. Go to the library
3. Browse into a movie with versions
4. Use context menu > Add to favourites on one of the versions
5. Exit library, go to Favourites screen
6. Select the version
7. The Choose dialog opens

note: context menu > play works as expected and plays the version

~~1. Set "Show videos with multiple versions as folder" to OFF
3. Go to the library
4. Use context menu > Add to favourites on a movie that has multiple versions
5. Exit library, go to Favourites screen
6. No context menu > Play button for the movie
7. Select the version
8. The versions appear as a folder~~

EDIT: Not reproducable.

### Debuglog

The debuglog can be found here: not relevant https://paste.kodi.tv/irrelevant.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: v21 current master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
> Choose dialog if "Show versions as folder" is OFF, browse into the versions if "Show versions as folder" is ON. 

The action to execute is stored along with the favourite. That's the concept of the favourites to define an action that is to be executed on an item. Making the action dynamic, depending on a settings value for example, is imo much effort and I think this edge case is not worse to invest the time the implementation would take.

**Comment by CrystalP** [comment]
I'm not familiar with the code. The way you explain it, this could be addressed in the "Add as favourite" actions, maybe something is not stored as it's supposed to? the isfolder attribute maybe?

But I'll agree that not showing the Choose dialog for a favorited version would be more impactful.

**Comment by ksooo** [comment]
> The way you explain it, this could be addressed in the "Add as favourite" actions

That is what currently happens. If the setting is ON, a favourite for browsing the versions will be created. If it is OFF a favourite to play one of the movie versions (choose version dialog or play the default version if the respective setting is on) will be created. But once the favourite is created, changing the setting value has no effect on the behaviour of the favourite.

**Comment by CrystalP** [comment]
I'll test a bit more, I wasn't aware of that. Sounds reasonable.

**Comment by CrystalP** [comment]
Confirmed it does what you wrote and remembers the browse/choose action from the time the item is added to the favorites (except for individual versions)
