### ISSUE TITLE
pvr.vuplus: error: webinterface cannot be reached

### ISSUE THREAD

**Issue by DDuck007** [xbmc/xbmc#24629]
### Describe the bug
Here is a clear and concise description of what the problem is:

The pvr.vuplus-addon shows an error using newer kodi-builts.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

PVR should start as normal

## Actual Behavior

PVR.vuplus addon shows the behaviour shown above.

## Possible Fix

With the help of @heitbaum the PR https://github.com/xbmc/xbmc/pull/24504 was identified to cause the trouble.
See complete discussion here:
https://forum.libreelec.tv/thread/28095-pvr-vuplus-webinterface-cannot-be-reached-since/?pageNo=1

### To Reproduce

1. install actual Kodi21-version (are most actual LibreElec)
2. restart system
3. see error log ...

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreElec
 - Kodi version: 21beta2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by mglae** [comment]
Further test in the linked LE forum thread show that using #22222 is fixing the error too (beside reverting #24504).

#### Brief bug description

pvr.vuplus is reading the XML file line by line via  [kodi::vfs::ReadLine()](https://github.com/kodi-pvr/pvr.vuplus/blob/2bd579d9d9c842a3e4404179efe22da0334cdae9/src/enigma2/utilities/CurlFile.cpp#L26). With #24504 the internal read routine moved from [CCurlFile::CReadState::ReadString()](https://github.com/xbmc/xbmc/blob/264b44decda328f9308964c86242f0a9997387bc/xbmc/filesystem/CurlFile.cpp#L1257) to [CFile::ReadString()](https://github.com/xbmc/xbmc/blob/264b44decda328f9308964c86242f0a9997387bc/xbmc/filesystem/File.cpp#L770). But CFile::ReadString() is removing all trailing CR/LF making the XML file impossible to parse.

**Comment by manfred-h** [comment]
I can confirm that by reverting [#24504](https://github.com/xbmc/xbmc/pull/24504) and using [#22222](https://github.com/xbmc/xbmc/pull/22222) my issue [pvr.vuplus#449](https://github.com/kodi-pvr/pvr.vuplus/issues/449) is resolved - without any changes in the addon! FWIW, this is on openSUSE Tumbleweed snapshot 20240214.

**Comment by phunkyfish** [comment]
> Further test in the linked LE forum thread show that using #22222 is fixing the error too (beside reverting #24504).
> 
> #### Brief bug description
> pvr.vuplus is reading the XML file line by line via [kodi::vfs::ReadLine()](https://github.com/kodi-pvr/pvr.vuplus/blob/2bd579d9d9c842a3e4404179efe22da0334cdae9/src/enigma2/utilities/CurlFile.cpp#L26). With #24504 the internal read routine moved from [CCurlFile::CReadState::ReadString()](https://github.com/xbmc/xbmc/blob/264b44decda328f9308964c86242f0a9997387bc/xbmc/filesystem/CurlFile.cpp#L1257) to [CFile::ReadString()](https://github.com/xbmc/xbmc/blob/264b44decda328f9308964c86242f0a9997387bc/xbmc/filesystem/File.cpp#L770). But CFile::ReadString() is removing all trailing CR/LF making the XML file impossible to parse.

@mglae are you saying we need to revert PR #24504  and merge #22222 for this to work?

**Comment by manfred-h** [comment]
> > Further test in the linked LE forum thread show that using #22222 is fixing the error too (beside reverting #24504).
> > #### Brief bug description
> > pvr.vuplus is reading the XML file line by line via [kodi::vfs::ReadLine()](https://github.com/kodi-pvr/pvr.vuplus/blob/2bd579d9d9c842a3e4404179efe22da0334cdae9/src/enigma2/utilities/CurlFile.cpp#L26). With #24504 the internal read routine moved from [CCurlFile::CReadState::ReadString()](https://github.com/xbmc/xbmc/blob/264b44decda328f9308964c86242f0a9997387bc/xbmc/filesystem/CurlFile.cpp#L1257) to [CFile::ReadString()](https://github.com/xbmc/xbmc/blob/264b44decda328f9308964c86242f0a9997387bc/xbmc/filesystem/File.cpp#L770). But CFile::ReadString() is removing all trailing CR/LF making the XML file impossible to parse.
> 
> @mglae are you saying we need to revert PR #24504 and merge #22222 for this to work?
> 
> Edit: NVM I had not read subsequent posts confirming this.

Yes, this is exactly what I did in our build system at [PMBS](https://pmbs.links2linux.org/package/show/home:manfred-h:kodi-next/kodi). I just added the following two patches:

1. [Revert24504](https://pmbs.links2linux.org/package/view_file/home:manfred-h:kodi-next/kodi/0004-Revert-Refactored_and_improved_logic_to_use_CFileStreamBuffer-issue24504.patch?expand=1)
2. [Merge22222](https://pmbs.links2linux.org/package/view_file/home:manfred-h:kodi-next/kodi/0005-ReadString:_buffer_overflow_fix,_add_documentation_and_make_implementation_consistent-issue22222.patch?expand=1)

Please note that patch 1. gets applied using "-R", of course!

**Comment by DDuck007** [comment]
... only merging https://github.com/xbmc/xbmc/pull/22222 works ...

**Comment by mglae** [comment]
@phunkfish either adding #22222 or reverting #24504 is required. But with both the pvr.vuplus issue is fixed too.

**Comment by manfred-h** [comment]
Ack! I just disabled [#24504](https://github.com/xbmc/xbmc/pull/24504) and kept [#22222](https://github.com/xbmc/xbmc/pull/22222) being added to my local build and everything works as expected!
