### ISSUE TITLE
Ambiguous name for versions in playlists and favorites

### ISSUE THREAD

**Issue by CrystalP** [xbmc/xbmc#24646]
### Describe the bug
The movie name is the only text that appears in the Playlist and Favourite screens to identify what was queued/favorited.
This is confusing and ambiguous for movies that have multiple versions, see below different versions of the same movie queued up:

![image](https://github.com/xbmc/xbmc/assets/489377/24a1fc22-ee0e-451d-9878-e5107e6af81e)

It can be unclear even if only one version of a movie is queued / favorited.

@jjd-uk @Hitcher, as mentioned in Slack, a skin change would be nice.

## Expected Behavior

The version is appended to the movie name, for movies that have multiple versions.

### Debuglog

The debuglog can be found here: not relevant https://paste.kodi.tv/irrelevant.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 21 current master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jjd-uk** [comment]
Simply change for playlists. However I don't think ListItem.HasVideoVersions returns anything in Favourites.

**Comment by ksooo** [comment]
> I don't think ListItem.HasVideoVersions returns anything in Favourites

That's correct. The favourites items itself have only very few properties. Properties of the target item are not tunneled to the fav item.
