### ISSUE TITLE
Kodi scraper error 10054

### ISSUE THREAD

**Issue by lomenn** [xbmc/xbmc#24653]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello, Kodi stopped scrapping information from either The Movie Database Python or TMDb TV Shows.

I get an error [WinError 10054] every time I try to update my library.

The program worked fine until recently, but I have no idea what is causing the issue (connections for Kodi are allowed in the Windows Firewall).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I'd expect the program to correctly scrape information for either my Movies or TV Shows and update my library accordingly.

## Actual Behavior

The Movies and TV libraries are not updated at all (nothing is displayed in the main Movies and TV sections).

The actual video player is working fine (I can play all the contents in my source folders).

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/howufoweru.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 23H2 Build 22631.3085
 - Kodi version: 20.3.500.0 (Microsoft Store)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by malard** [comment]
you are almost certainly best to ask on the forums, the error is here:

2024-02-05 20:33:29.074 T:4724    debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: Calling URL "https://api.themoviedb.org/3/search/tv?api_key=af3a53eb387d57fc935e9128468b1899&language=en-US&query=Dark+Matter"
2024-02-05 20:33:29.110 T:4724    debug <general>: [metadata.tvshows.themoviedb.org.python (1.6.5)]: failed to reach the remote site

check your ability to visit this web page, if not then that's your first port of call. I am going to close the ticket as this won't be a bug with Kodi, but if I am incorrect on that suspicion then please feel free to re-open

**Comment by lomenn** [comment]
I @malard, thank you for your answer.

I can visit the webpage and see the information related to this TV Show.

I am not so sure that it is the only error in this log though, so I'll reopen this ticket.

Best regards

**Comment by malard** [comment]
can you open the web page from the device running Kodi? Being on windows, I am going to assume you've got windows firewall installed and its perhaps not allowing traffic out from Kodi

**Comment by lomenn** [comment]
@malard, yes I can open the page from the same machine.

As I said previously, the firewall is set to allow in/out connections for Kodi.

Best regards

**Comment by malard** [comment]
the error you are reporting, if you google it, is network related, its nothing to do with Kodi. Hopefully someone else can help you, but I am 99.9% confident its not an issue with Kodi :)
