### ISSUE TITLE
Does not play video on RPI 5 / Arch

### ISSUE THREAD

**Issue by skrat** [xbmc/xbmc#24656]
### Describe the bug
Video doesn't play on Raspberry Pi 5.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Play video.

## Actual Behavior
Video does not play. Using YT and Vimeo addons.
Only audio can be heard.

### To Reproduce

1. Follow this tutorial https://kiljan.org/2023/11/24/arch-linux-arm-on-a-raspberry-pi-5-model-b/
2. Install git version of Kodi and inputstream.adapative addon from AUR 
3. Install YT and Vimeo addons

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/14177167/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://github.com/xbmc/xbmc/assets/5008/ffb010c4-9911-441d-9d40-da3362909ea0

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - Raspberry Pi 5
 - Operating system version/name: Arch Linux Arm
 - Kodi version: git

**Comment by malard** [comment]
please visit the forums for help in this regard.

**Comment by skrat** [comment]
@malard I added the debug.log. Why should I go to the forums? I see your issues tracker is rather full, but this is kind of rude. I made the effort here to improve kodi, so please, be reasonable, reopen this. If you don't have time for this now, leave it open and come back to it later. Thank you

**Comment by malard** [comment]
at the time I closed this ticket, there was no debug log and just a picture of an empty library and you said you were following a guide where it is working for someone else (otherwise why would they make a guide).

**Comment by neo1973** [comment]
The log contains `CDVDVideoCodecDRMPRIME` so is Kodi trying to use hardware decoding despite RPi5 not having one for h264?

@skrat: Under Settings->Player please try to disable hardware decoding for h264 if there is a dedicated setting for that. If not disable hardware decoding entirely. Then try again and report back, this may helps to narrow down the problem.

**Comment by chewitt** [comment]
Kodi plays YT and Vimeo content on RPi5 with LE, RaspiOS, and several other 'name' Linux distros fine so there is clearly no bug in Kodi. Arch might have a Kodi packaging or config issue or it might be a user config issue, but those are Arch issues not bugs in Kodi and the sole purpose of this issue tracker is tracking bugs in Kodi. So the correct location for user support to continue (and so we don't add unnecessary noise to our already "rather full" Kodi-bug tracker) is the forum. Thank you for understanding.

**Comment by skrat** [comment]
It works when I turn off PRIME DRM. Strangely the only Render method available (and listed) in the menu is Auto-detect.
