### ISSUE TITLE
Re-opening issue #24653 Kodi scraper error 10054

### ISSUE THREAD

**Issue by lomenn** [xbmc/xbmc#24654]
### Describe the bug
Here is a clear and concise description of what the problem is:

This is a re-opening of this previous issue: #24653, which has been closed but not solved.

Hello, Kodi stopped scrapping information from either The Movie Database Python or TMDb TV Shows.

I get an error [WinError 10054] every time I try to update my library.

The program worked fine until recently, but I have no idea what is causing the issue (connections for Kodi are allowed in the Windows Firewall).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I'd expect the program to correctly scrape information for either my Movies or TV Shows and update my library accordingly.

## Actual Behavior

The Movies and TV libraries are not updated at all (nothing is displayed in the main Movies and TV sections).

The actual video player is working fine (I can play all the contents in my source folders).

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/howufoweru.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 23H2 Build 22631.3085
 - Kodi version: 20.3.500.0 (Microsoft Store)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@lomenn 

Have you opened a thread on the forum as you were requested to do?

As previously stated, this is not a Kodi bug, but an issue with your particular setup. Github is NOT the place to request and receive support.

**Comment by lomenn** [comment]
@KarellenX,

I haven't posted the issue on the forum yet but will do so in due time.

Regarding this ticket, I'm sorry for forgetting to close it following my conversation with mallard, who suggested re-opening the issue as an option here: https://github.com/xbmc/xbmc/issues/24653#issuecomment-1928112434. The issue appears to not be Kodi-related indeed.

As for GitHub not being the place to request and receive support, I simply followed the Kodi guidelines for submitting a bug report, available here: https://kodi.wiki/view/HOW-TO:Submit_a_bug_report.

Best regards

**Comment by KarellenX** [comment]
@lomenn 

Sure, no harm. But I know this is not a bug otherwise we would have had dozens, if not hundreds of similar reports, as well as the developers experiencing the issue.

Post your forum thread so I can ask for some other info.
