### ISSUE TITLE
WebOS: pause button doesn't work

### ISSUE THREAD

**Issue by Dis90** [xbmc/xbmc#24680]
### Describe the bug
Here is a clear and concise description of what the problem is:

Pause button on TV's remote doesn't do anything and play button is mapped to play/pause.
My TV's remote looks like this: https://www.remote-controls-shop.co.uk/site/assets/files/80368/cmb5316.jpg

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Pause button to work.

## Actual Behavior

Pause button doesn't work.

### To Reproduce

1. Start video
2. Press pause on remote
3.

### Debuglog

The debuglog can be found here:
[kodi.old.log](https://github.com/xbmc/xbmc/files/14228482/kodi.old.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [x] WebOS

 - Operating system version/name: WebOS 4
 - Kodi version: 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sundermann** [comment]
The pause button is registered correctly but there is no action associated with it:

```
2024-02-10 09:33:35.590 T:2011    debug <general>: Keyboard: scancode: 0x77, sym: 0x13 (pause), unicode: 0x85, modifier: 0x0
2024-02-10 09:33:35.590 T:2011    debug <general>: HandleKey: pause (0xf0dd) pressed, window 12005, action is 
```

Doesn't really seem webOS related but more a general issue

**Comment by Dis90** [comment]
Thanks. I copied keyboard.xml to keymaps and added line `<pause>PlayPause</pause>` to global section and now it's working.

Should 'info' button work? I tried to press it and I think this line is related to it:
`2024-02-10 14:19:07.539 T:2524    debug <general>: Keyboard: scancode: 0x80, sym: 0x151 (unknown), unicode: 0x81, modifier: 0x0`
[kodi4.log](https://github.com/xbmc/xbmc/files/14229216/kodi4.log)

**Comment by sundermann** [comment]
Indeed, that button was not mapped. I only have a smart remote at hand and that one has a lot less buttons than on the traditional remotes. Unfortunately, the keymap provided by `xkbcommon-webos-keysyms.h` is quite large and I don't know exactly what buttons from that file are actually in use and refer to what button on a remote.
