### ISSUE TITLE
Input issues in the newly released Kodi 20.4 version

### ISSUE THREAD

**Issue by xXTimmy89Xx** [xbmc/xbmc#24696]
Input issues in the newly released Kodi 20.4 version, I think this fix "A number of fixes backported to resolve input issues (remotes/controllers)" broke something, on some Android TV devices the select button and back button don't work or they don't work as you expect

Apk installed kodi-20.4-Nexus-armeabi-v7a.apk

Tested on Sony KD-43XF8096 Android TV 9
Tested on Sony KD-55XG8596 Android TV 10
Tested on Sony KD-49X8005C Android TV 7
Tested on DAZN TV Box Android TV 10
Tested on TELE System UP T2 4K Android TV 12 

The problem does not appear in Kodi version 20.3.

**Comment by fritsch** [comment]
Forum thread: https://forum.kodi.tv/showthread.php?tid=376235

@xXTimmy89Xx  Please post your debuglog never the less.

**Comment by xXTimmy89Xx** [comment]
@fritsch https://paste.kodi.tv/zofetuquvo

**Comment by garbear** [comment]
OK, I've done fixes for "select button doesn't work" and "back button goes home instead of back". I created test builds. Can you give them a try?

* **ARM32:** [kodi-20240211-b4d51be1-android-fixes-armeabi-v7a.apk](http://mirrors.kodi.tv/test-builds/android/arm/kodi-20240211-b4d51be1-android-fixes-armeabi-v7a.apk)
* **ARM64:** [kodi-20240211-b4d51be1-android-fixes-arm64-v8a.apk](http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20240211-b4d51be1-android-fixes-arm64-v8a.apk)

**Comment by xXTimmy89Xx** [comment]
The select and back buttons seem to work normally again but if I try to disable Joystick Support the remote control stops working including the back button on the keyboard

**Comment by garbear** [comment]
Thanks for the debug logs. I have a fix in progress for the remote not working with peripheral.joystick disabled. It could possibly fix the keyboard backspace button too.

**Comment by ckramer** [comment]
> Thanks for the debug logs. I have a fix in progress for the remote not working with peripheral.joystick disabled. It could possibly fix the keyboard backspace button too.

Here's logs form Shield pro, same issue https://paste.kodi.tv/togiruzesu.kodi

**Comment by ckramer** [comment]
👉  Looks like Kodi also hogs Volume up/down when it supposed to be passed to Android

**Comment by rainman74** [comment]
> Thanks for the debug logs. I have a fix in progress for the remote not working with peripheral.joystick disabled. It could possibly fix the keyboard backspace button too.

Likewise, the left/right buttons on the Sony TV remote control no longer work for me. I can no longer even select the 2nd profile on the login screen.

**Comment by garbear** [comment]
@rainman74 I'm accumulating Android hardware as fast as I can, but clearly there are more joystick driver variations than I can discover on my own. Can you help by posting your debug log showing Kodi start and then the buttons not work?

**Comment by rainman74** [comment]
> [garbear](/garbear)

Hey garbear, that doesn't make any sense. My Sony remotes have more than 20 different buttons. Should I press them all to get the keycodes? And then what about the next remote, which works differently again?

It would be much more effective if you undid your last commits, as 20.4 is not a beta. Everything has worked flawlessly for over 10 years now.

**Comment by xXTimmy89Xx** [comment]
TELE System UP T2 4K Android TV 12
select button and back button don't work

2024-02-13 19:56:34.126 T:11357   debug <general>: Android Key AKEYCODE_DPAD_DOWN (20) pressed
2024-02-13 19:56:34.133 T:11399   debug <general>: BUTTON [ 3 ] on "HID 0e8f:2517" pressed
2024-02-13 19:56:34.134 T:11399   debug <general>: FEATURE [ down ] on game.controller.default pressed (ignored)
2024-02-13 19:56:34.134 T:11399   debug <general>: FEATURE [ down ] on game.controller.default pressed (handled)
2024-02-13 19:56:34.774 T:11357   debug <general>: Android Key AKEYCODE_DPAD_RIGHT (22) pressed
2024-02-13 19:56:34.786 T:11399   debug <general>: BUTTON [ 5 ] on "HID 0e8f:2517" pressed
2024-02-13 19:56:34.786 T:11399   debug <general>: FEATURE [ right ] on game.controller.default pressed (ignored)
2024-02-13 19:56:34.786 T:11399   debug <general>: FEATURE [ right ] on game.controller.default pressed (handled)

**Comment by xXTimmy89Xx** [comment]
On DAZN TV Box Android TV 10 

The Select button does not open the Video Player OSD during video playback and the back button stops video playback instead of returning to home and continuing in the background

https://paste.kodi.tv/eqelekofej

**Comment by ambulancePilot** [comment]
These changes must be part of the latest Omega nightly as well because my remote control is completely unusable with my fire stick. Strange that something as a major as this would be included in an incremental update however.

**Comment by ambulancePilot** [comment]
However I just want to mention that disabling the joystick addon **completely** fixes the issue. This is on the latest nightly, not the test builds you linked to up there.

**Comment by garbear** [comment]
> It would be much more effective if you undid your last commits, as 20.4 is not a beta. Everything has worked flawlessly with every remote for over 10 years now.

Heard. PR to revert the android stuff is up now.

**Comment by bartmans** [comment]
I would like to say thank you, for all your hard work on this @garbear! 

It always sucks to have to undo your own work. And then have to do it again at some later time.

**Comment by fritsch** [comment]
> I would like to say thank you, for all your hard work on this @garbear!
> 
> It always sucks to have to undo your own work. And then have to do it again at some later time.

I would like to emphasize on this! Thank you @garbear for all your work here and for taking the revert decision in favor of a fixed up 20 release. I am looking forward to see your work coming back as soon as master opens!

Thank you very much.

**Comment by htatla81** [comment]
Hi all - I just updated Kodi 20.2 >> 20.4 (ARM 32-bit version) on my AMZ Fire Cube 2nd gen and my Logitech Harmony companion remote does not work at all. UI is just stuck on “Add-ons” and no remote keys do anything. Been using the same setup for years without an issue 

Googling the issue I came here but doesn’t seem like the was put in? What do I do from here please?

appreciate any help & advice!

**Comment by rainman74** [comment]
> Hi all - I just updated Kodi 20.2 >> 20.4 (ARM 32-bit version) on my AMZ Fire Cube 2nd gen and my Logitech Harmony companion remote does not work at all. UI is just stuck on “Add-ons” and no remote keys do anything. Been using the same setup for years without an issue
> 
> Googling the issue I came here but doesn’t seem like the fix was put in on the kodi website? What do I do from here please?
> 
> appreciate any help & advice!

Use current nexus nightly

**Comment by ckramer** [comment]
The issue regressed in nighty builds starting form April 24 , trying every daily build and reverting to April 22 (a5fb12) which is the last working with TV remotes.

**Comment by garbear** [comment]
You mean that remotes broke on Android in nightlies between April 22 and April 24? I've been watching GitHub and haven't seen any android input-related PRs.

**Comment by rainman74** [comment]
> You mean that remotes broke on Android in nightlies between April 22 and April 24? I've been watching GitHub and haven't seen any android input-related PRs.

This was fixed a long time ago with this fix: https://github.com/xbmc/xbmc/pull/24707

**Comment by redlotusaustin** [comment]
@garbear @rainman74 Apologies for resurrecting an old thread and if this is the wrong place, but this thread is what helped me.

I have a Shield Pro and noticed issues with the Select & Back buttons on my remote a few days ago. After some digging I found this thread and apparently disabling the Joystick Addon & rebooting also fixed it for me (the back button didn't work until a restart).

The system info shows:
OS: Android 11.0.0
Kodi Build: 21.2 (21.2.0)
Git: 20250201-cc4e1fedda
Compiled 2025-02-01

**Comment by ambulancePilot** [comment]
They have been trying to improve use of remotes on Android but back when
they first tried to improve it they had to undo the changes because it
broke too much for too many people. This time around it seems to be working
for me and most but it seems to be broken for people with very basic
remotes like the shield.

**Comment by redlotusaustin** [comment]
@ambulancePilot Actually, something I should have mentioned before: I replaced my Shield remote with one built in Home Assistant so I can access it on my phone. That sends commands via the Android TV Remote using DPAD_CENTER and BACK, etc.
