### ISSUE TITLE
No more Passtrough at some Files 

### ISSUE THREAD

**Issue by Zeitgeist4** [xbmc/xbmc#24694]
Hello, here is the problem as I described it [here](https://forum.kodi.tv/showthread.php?tid=376232&pid=3183648#pid3183648).

I've noticed over the past few days that Kodi on Shield TV Pro, for movies and series that I watched in Dolby Atmos, is now outputting in standard audio, so without Atmos. My TV is an LG OLED65B8 and the soundbar is the Samsung HW-K950. I hadn't changed anything in the settings of Kodi and the Shield. When it occurred, or when I noticed it a few days ago, I was using the Shield TV Pro 2017 with the build kodi-20.3-Nexus-arm64-v8a. I then tried the kodi-21.0-Omega_beta2-arm64-v8a, unsuccessfully. Now, I am using the Shield TV Pro 2019, and the problem remains exactly the same. I have tried both the aforementioned builds and even the older kodi-20.2-Nexus-arm64-v8a. The problem persists. The same goes for the movie NYAD. When I play the movie through the Netflix app on Shield, I get Dolby Vision and Dolby Atmos. But when I play the movie from a hard drive, there's no Dolby Atmos.

I Install the latest nightly kodi-20240210-df86cfdc-master-arm64-v8a and the Problem still exist. 

The debuglog can be found here: https://paste.kodi.tv/vufuquzaqe

The same film (Nyad) in Shield via the Netflix app with DolbyVision and DolbyAtmos in Kodi with DolbyVision and standard audio (Not Atmos)

Here are the Audiodatas from the Film:
AUDIO
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 1 h 59 min
Source duration                          : 1 h 59 min
Source_Duration_LastFrame                : -11 ms
Bit rate mode                            : Constant
Bit rate                                 : 224 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 192 MiB (5%)
Source stream size                       : 192 MiB (5%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1

The same with the Film The Killer (2023)
In Netflix with Dolby Atmos in Kodi not. 
Here the Info from Audio in the Film:

Audio
Codec info = E-AC-3 | A_EAC3
Channels = 6
Bitrate = CBR 640 kb/s
Samplerate = 48.0 kHz
Language = English

Here are some screenshots from my settings
![settings](https://github.com/xbmc/xbmc/assets/159713889/750149de-0109-450b-9165-500f5dab578f)
![settings2](https://github.com/xbmc/xbmc/assets/159713889/34b010cc-55fb-4c54-8944-d0dda4f3804c)
![settings3](https://github.com/xbmc/xbmc/assets/159713889/a06d04a3-3cb4-47bd-8b0c-37f984d163a5)

My Environment
Used Operating system: Android 11 on Shield TV Pro 2019 (same Problem with the Shield 2017)
 - Kodi version: kodi-20240210-df86cfdc-master-arm64-v8a
 TV LG OLED65B8
 Soundbar Samsung HW-K950

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Please be so kind and provide the debuglog with the current nightly. For your first sample it's AAC, no passthrough is to be expected, it shall be output as multi-channel PCM.

But looking at your manual:
![grafik](https://github.com/xbmc/xbmc/assets/1089309/653e1568-fa35-4f67-a1ac-bf9fea6ba6d9)

1) It seems the soundbar cannot output multi-channel PCM. Therefore please Adjust the PCM speakers to 2.0 inside kodi and enable Dolby Transcoding. That way your first sample should work.

2) For the E-AC3 I expect some issue with the extended Audio, which -  the box - by chance most likely also does not understand :-( - but let's see.

1) is not a bug, but a misconfiguration from your side.

**Comment by Zeitgeist4** [comment]
I change the speakers from 7.1 to 2.0 and enabled DTS, but the Problem still exist. Here ist the debuglog https://paste.kodi.tv/hifukozuwe

**Comment by fritsch** [comment]
I asked for Dolby Transcoding, not DTS. It's called: Dolby Digital (AC3) transcoding in the settings.

See the wiki: https://kodi.wiki/view/Settings/System/Audio

No change in your log:
2024-02-11 18:27:31.793 T:11005    info <general>: Creating audio stream (codec id: 86018, channels: 6, sample rate: 48000, no pass-through)

Please install the currently version - your logs are still beta2.

**Comment by Zeitgeist4** [comment]
hello and thank you again. Which version should I install? The latest nightly or the current stable?

**Comment by fritsch** [comment]
For the Shield (64 bit version): http://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/kodi-20240210-df86cfdc-master-arm64-v8a.apk

**Comment by Zeitgeist4** [comment]
I have Installed this version, but over the beta 2. 
I'll do a clean install later and report back

**Comment by fritsch** [comment]
Don't do a clean install ... the versioning inside kodi is broken ... everything tells beta2 now. Continue with that version.

Make triple sure your have
PCM Speakers 2.0

Passthrough Enabled
AC3: enabled
Dolby AC3 Transcoding: Enabled

Then play your AAC sample again.

**Comment by Zeitgeist4** [comment]
it was already set that way before. Nothing changed

![settings4](https://github.com/xbmc/xbmc/assets/159713889/fda361d1-7ef8-4dbd-90b0-2ac15983ef6c)
![settings5](https://github.com/xbmc/xbmc/assets/159713889/8b01b764-deee-4b61-ac6c-a3a21bed7736)

**Comment by fritsch** [comment]
Good, then restart Kodi and post a single log of the AAC file. With this configuration set it should never open 6 channels via PCM.

**Comment by Zeitgeist4** [comment]
Shield and Kodi both restarted, here is the debug file 
https://paste.kodi.tv/nufiranoke

**Comment by fritsch** [comment]
2024-02-11 21:24:23.391 T:9433    debug <general>: CActiveAESink::OpenSink - trying to open device AUDIOTRACK:AudioTrack (IEC)
2024-02-11 21:24:23.391 T:9433    debug <general>: CAESinkAUDIOTRACK::Initialize requested: sampleRate 48000; format: AE_FMT_RAW; channels: 2
2024-02-11 21:24:23.391 T:9433    debug <general>: Updated SampleRate: 32000 Distance: 144000
2024-02-11 21:24:23.391 T:9433    debug <general>: Updated SampleRate: 44100 Distance: 35100
2024-02-11 21:24:23.391 T:9433    debug <general>: Updated SampleRate: 48000 Distance: 0
2024-02-11 21:24:23.391 T:9433     info <general>: Trying to open: samplerate: 48000, channelMask: 12, encoding: 13
2024-02-11 21:24:23.393 T:9433     info <general>: Minimum size we need for stream: 6160 Bytes
2024-02-11 21:24:23.393 T:9433     info <general>: Audiotrack buffer params are: period time = 32.083 ms, period size = 6160 bytes, num periods = 4
2024-02-11 21:24:23.393 T:9433     info <general>: Created Audiotrackbuffer with playing time of 128.333333 ms min buffer size: 24640 bytes
2024-02-11 21:24:23.418 T:9433     info <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 48000 format: AE_FMT_S16LE (AE) method: IEC (PT) stream-type: STREAM_TYPE_AC3 min_buffer_size: 24640 m_frames: 1540 m_frameSize: 4 channels: 2
2024-02-11 21:24:23.418 T:9433    debug <general>: CActiveAESink::OpenSink - AUDIOTRACK Initialized:
2024-02-11 21:24:23.418 T:9433    debug <general>:   Output Device : AudioTrack (IEC)
2024-02-11 21:24:23.418 T:9433    debug <general>:   Sample Rate   : 48000
2024-02-11 21:24:23.418 T:9433    debug <general>:   Sample Format : AE_FMT_S16NE
2024-02-11 21:24:23.418 T:9433    debug <general>:   Channel Count : 2
2024-02-11 21:24:23.418 T:9433    debug <general>:   Channel Layout: FL, FR
2024-02-11 21:24:23.418 T:9433    debug <general>:   Frames        : 1540
2024-02-11 21:24:23.418 T:9433    debug <general>:   Frame Size    : 4
2024-02-11 21:24:23.422 T:9432     info <general>: CAEEncoderFFmpeg::Initialize - AC3 encoder ready

Looks good, kodi succesfully makes 5.1 AC3 from it and sends it to your device. You should have had proper playback for this file for around 7 to 10 seconds.

What exactly did not work here?

**Comment by Zeitgeist4** [comment]
I'm pretty sure that with this and the other files that I have problems with, until recently when I played them back on my soundbar "Dolby Atmos" came up and the blue lamp for Atmos lit up

**Comment by Zeitgeist4** [comment]
The same applies to this file. Atmos sound doesn't come through. I see the Film in Atmos a couple of weeks ago

This is the Media Info:
MEDIAINFO
Container = Matroska (mkv)
Duration = 01:59:30.792
Filesize = 5 GiB
Overall bitrate = 5 567 kb/s
Video
Codec info = AVC Main@L4 | V_MPEG4/ISO/AVC
Resolution = 1920x1080
Display AR = 1.778 | 16:9
Bitrate = 5 000 kb/s
Framerate = CFR 24.000
Color space = YUV
Chroma subsampling = 4:2:0
Encoder = x264 - core 148 r2727 7d026e8
Audio
Codec info = E-AC-3 | A_EAC3
Channels = 6
Bitrate = CBR 640 kb/s
Samplerate = 48.0 kHz
Language = English

And here the debug file  https://paste.kodi.tv/imizorawux

**Comment by fritsch** [comment]
Let's first finish, this one:
Format : AAC LC
Format/Info : Advanced Audio Codec Low Complexity
Codec ID : mp4a-40-2

That guy here cannot have ATMOS bits, it's neither E-AC3 nor TrueHD., so technically not possible. I consider this one closed. While you already jumped to your E-AC3 issue, do you see that: AAC no Atmos, no matter what blue lamp you have in mind? ;-)

For  your EAC3 part, as shown here:  https://paste.kodi.tv/imizorawux

```
2024-02-11 23:32:55.596 T:10072   debug <general>: ActiveAE - start sync of audio stream
2024-02-11 23:32:55.596 T:10258   debug <general>: CDVDAudio::Resume - resume audio stream
2024-02-11 23:32:55.596 T:10258   debug <general>: CAEStreamParser::TrySyncAC3 - Unexpected stream type: 0 (wantEAC3dependent: true)
2024-02-11 23:32:55.596 T:10107    info <general>: Skipped 2 duplicate messages..
2024-02-11 23:32:55.586 T:10107   debug <general>: OnAVChange: CApplication::OnAVChange
2024-02-11 23:32:55.596 T:10129   debug <general>: OnAVStarted: CApplication::OnAVStarted
2024-02-11 23:32:55.597 T:10258   debug <general>: CAEStreamParser::TrySyncAC3 - Unexpected stream type: 0 (wantEAC3dependent: true)
2024-02-11 23:32:55.603 T:10073   debug <general>: Could not acquire timestamp
2024-02-11 23:32:55.603 T:10258   debug <general>: CAEStreamParser::TrySyncAC3 - Unexpected stream type: 0 (wantEAC3dependent: true)
```

@popcornmix @sundermann - any idea here, seems related to the EAC3 dependent stream changes?

**Comment by sundermann** [comment]
Just a guess but from the specs it seems an E-AC3 stream can have up to 7 dependent substreams. I think currently we only parse the first dependent substream

**Comment by fritsch** [comment]
@Zeitgeist4 The very same Sample worked for 20.2, right? But it broke for 20.3?

**Comment by Zeitgeist4** [comment]
yes, but i tried Saturday the build kodi-20.2-Nexus-arm64-v8a with the same result. I don't know what is happen. I'll try to reload the files. Maybe something went wrong with these

**Comment by fritsch** [comment]
Try: 20.1

If the issue is what I assume it is - 20.1 should work, but 20.2 should be broken.

**Comment by fritsch** [comment]
Any news here? Would be good, if you post a debuglog with working 20.1 (if it works) and one in not working 20.2, please.

**Comment by Zeitgeist4** [comment]
it didn't work with 20.1. Today I'm setting up the old Shield Pro (2017) to test builds there and will get back to you.

**Comment by Zeitgeist4** [comment]
So, I tested it with kodi-18.0-Leia-arm64-v8a and kodi-19.0-Matrix-arm64-v8a today and it behaves exactly the same with these builds as with the newer ones. It's probably a mistake on my part. I really thought I had better sound with some files on my hard drive. I think we can close the case. I'm sorry if I caused any trouble.

**Comment by fritsch** [comment]
All good. We are short before v21 and I did not want to run into known regressions. If you could provide a small sample of your file: ffmpeg -i myoriginalfile.mkv -t 60 -map 0 -c:v copy -c:a copy koditestingsample.mkv

it would be great.

**Comment by Zeitgeist4** [comment]
Hello, I created the file. where can I upload these?

**Comment by fritsch** [comment]
Does it fit in here from size pov?

**Comment by Zeitgeist4** [comment]
I don't know. Its 76 MB

**Comment by Zeitgeist4** [comment]
mkv is not supported here

**Comment by fritsch** [comment]
ffmpeg -i myoriginalfile.mkv -t 30 -map 0 -c:v copy -c:a copy koditestingsample.mp4

These 30 seconds as mp4 should fit here. Mind trying it? (See the changed ending).

**Comment by Zeitgeist4** [comment]
[sost#0:2 @ 000001ce761be7c0] Automatic encoder selection failed Default encoder for format mp4 (codec none) is probably disabled. Please choose an encoder manually.
[sost#0:2 @ 000001ce761be7c0] Error selecting an encoder
Error opening output file koditestingsample.mp4.
Error opening output files: Encoder not found

**Comment by Zeitgeist4** [comment]
i convert it online, but the file is too big for here (supports 10MB)

**Comment by fritsch** [comment]
Yeah - no idea. The online converted file won't help - as it most likely broke the audio. Too bad.
Did you buy this file? Can you link to the Bluray?

**Comment by Zeitgeist4** [comment]
aa ok. No, I didn't buy it.

**Comment by fritsch** [comment]
Okay - but what film is it? I might buy it to have the DD+ file to check.

**Comment by Zeitgeist4** [comment]
The.Killer.2023.1080p.NF.WEB-DL.DDP5.1.H.264-playWEB[TGx]

**Comment by fritsch** [comment]
File works perfectly fine. Tested with Firetv 4K Gen2 and Marantz NR1711 AVR.

**Comment by Zeitgeist4** [comment]
OK, maybe I have wrong settings in Kodi. From the Netflix app in the Shield TV Pro 2019, I get the best sound (Dolby Atmos) and picture (Dolby Vision).

**Comment by fritsch** [comment]
The file had no Atmos. It was pure EAC3 5.1 only.

**Comment by Zeitgeist4** [comment]
Then I think it's all a mistake on my part. I think we can close the case. Thanks again

**Comment by fritsch** [comment]
Most likely you have more luck in using Android's Packer (kodi setting). This guy only can do "low quality" EAC3 - while kodi's package format uses 2 channel 192 khz 16 bit for up to 6.144 Mbit/s

**Comment by Zeitgeist4** [comment]
Ok i try it. thx

**Comment by da-anda** [comment]
DD+ does not necessarily mean it is Atmos. Also, you can't have DV in a h264 encode

**Comment by fritsch** [comment]
Also take care on:
Bit rate                                 : 768 kb/s

Years ago I had to reduce the AC3 encoding rate to 448 kb/s cause of some Sony TVs back then were not able to cope with the bitrate ... but yeah - for your setup I think the soundbar is quite picky. Most likely it does low bitrate Atmos only, means: some objects to make it blink green ... and then a low eac3 bitrate.

**Comment by Zeitgeist4** [comment]
Ok thanks, I'll keep that in mind.

**Comment by Zeitgeist4** [comment]
Is that also atmos? 

Audio
Codec info = E-AC-3 | A_EAC3
Channels = 6
Bitrate = CBR 640 kb/s
Samplerate = 48.0 kHz
Language = English

or does the bitrate have to be at least 768 kb/s?

**Comment by fritsch** [comment]
No - that's EAC3 only.

**Comment by da-anda** [comment]
`E-AC-3 JOC` this is Atmos - `E-AC-3` + `JOC` ("Joint object coding" if I am not mistaken, so only here are the additional atmos objects available)
