### ISSUE TITLE
[Nexus] Video Output Corrupt With Software Rendering on nVidia on Windows 11. (Alternative Title: Kodi, Now With CGA Support!)

### ISSUE THREAD

**Issue by AshleyAshes** [xbmc/xbmc#24702]
### Describe the bug
Here is a clear and concise description of what the problem is:
With v20.4 when using the 'Software' rendering option on my two nVidia powered Windows 11 machines the video output is corrupt.  Normal when using DXVA and Pixel shaders, also normal on any AMD hardware I have to test.  Media type does not seem to matter.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
The visual output should be 'normal'.

## Actual Behavior
The visual output is entirely wrong, wrong colors, frankly reminds me of 'CGA' DOS games.

## Possible Fix
No idea.

### To Reproduce
1. Select 'Software' as the render method on a nVidia based Windows system.
2. Play literally any media file.

### Debuglog
The debuglog can be found here:
Debug Log for my GTX 1080 System: 
[kodi - GTX 1080.log](https://github.com/xbmc/xbmc/files/14241115/kodi.-.GTX.1080.log)
[kodi - RTX 3080.log](https://github.com/xbmc/xbmc/files/14241122/kodi.-.RTX.3080.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:
![screenshot00019](https://github.com/xbmc/xbmc/assets/33394709/fba160da-3853-48a7-9d87-2b6b1ebbb21b)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
Been testing software rendering related to DXVA deinterlacing crashes on AMD Windows drivers, so I happened to have a nVidia system set to software rendering when I upgraded to 20.4 and noticed the issue.  Then began testing on other systems.

### Your Environment
Used Operating system:
Windows 11.

 - Operating system version/name:
 - Kodi version: 20.4

**Comment by thexai** [comment]
This is not v20.4 exclusive, is same in all Nexus v20.0, 20.1, 20.2, etc. and even v19. 

Technically is not a bug but "not implemented feature": no 10-bit / HDR support in Software rendering.

As alternative you can use Pixel Shaders or DXVA or disable setting "Use 10 bit for SDR" in Settings / System /Display.

This feature was implemented in https://github.com/xbmc/xbmc/pull/23221 for Omega only although is not recommended use Software render other that testing or bug triage in Pixel Shaders / DXVA.
