### ISSUE TITLE
PVR EPG label bug.

### ISSUE THREAD

**Issue by Lunatixz** [xbmc/xbmc#24717]
### Describe the bug
EPG guide will change its label from the media title to the channel name after a series of reproducible steps.

## Expected Behavior
EPG guide labels stay unchanged.

## Actual Behavior
EPG guide label changes from media title to channel name.

## Possible Fix
It's possible the incorrect listitem property is being used and or replaced by channel meta. 

### To Reproduce
1.  Open EPG guide, select any current content; then select from context menu "Play Programme"
2.  Stop playback, select the same content, then select from context menu "Play only programme".
3.  Stop playback and note that the current content is no longer the media title and now displays the channel name.

### Screenshots 
Here are some links or screenshots to help explain the problem:
https://files.slack.com/files-pri/T06MTBK1S-F06JHKCPCNT/screenshot_2024-02-15_at_09.18.35.png

 - Operating system version/name:
 - Windows 10 22H2, kernel: Windows NT x86 64-bit version 10.0.19045.3996
 - Kodi (21.0-BETA2 (20.90.821) Git:20240120-986851789a). Platform: Windows NT x86 64-bit
 - pvr.iptvsimple v21.8.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Tried to reproduce with ptr.demo (due to lack of iptvimple setup). No luck.

**Comment by vpeter4** [comment]
Can't reproduce with pvr.iptvsimple on Windows.

**Comment by Lunatixz** [comment]
My plugin must be a contributing factor to the issue.

**Comment by enen92** [comment]
@Lunatixz please fill the "how to reproduce" properly with concrete steps. This might be occurring due to a combination of specific conditions, without a way to reproduce it won't certainly be solved.
