### ISSUE TITLE
Inaccurate HDR color due to Pixel Shaders being selected as Render Method

### ISSUE THREAD

**Issue by crawfishie** [xbmc/xbmc#24712]
### Describe the bug
Here is a clear and concise description of what the problem is:

When Pixel Shaders are selected as Render Method in Kodi Omega Beta 2 running on Windows 11 Pro, HDR colors are visibly and measurably inaccurate. Kodi is selecting Pixel Shaders automatically on my mini PC with AMD Ryzen 5 5560U with Radeon Graphics but uses DXVA on my non-AMD systems. Moreover, it cannot be forced to use DXVA on my AMD system by changing the Render Method setting.

I observed visibly inaccurate HDR gray scale patterns when evaluating my new Beelink SER5 5560U mini PC with integrated AMD Radeon graphics. The patterns exhibit a subtle green tint compared to a Beelink N100 mini PC (Intel UHD graphics), my main PC with Nvidia RTX 3060 Ti, my Chromecast with Google TV (Android 12), and my Sony A80J (Android 10), all of which appear the same in Kodi and measure the same with Calman Home for Sony and my i1D3 meter. SDR is fine on the AMD and all the other devices; it's just HDR that’s the problem, and just on the AMD. My TV is a Sony A80J OLED, and I’m running Windows 11 Pro on all the Windows machines, which are fully updated and using current drivers. For the Windows machines, I have Kodi configured for Limited Range, the video cards for Full Range, and the TV for Limited Range. Black/white clipping patterns are visually fine on all devices, and I calibrated the TV for SDR per standard Sony procedure, yielding dE2000 values < 1. The same calibration works for all my devices.

I always leave Kodi’s Render Method at its default Auto Detect, but comparing debug logs, I found that for the AMD 5560U, Kodi chose Pixel Shaders for my HDR file instead of DXVA like it does for the other Windows machines. This led me to test the normally unaffected Intel N100 by manually selecting Pixel Shaders and DXVA render methods for both HDR and SDR grayscale (white) patterns, and the N100 exhibited the same problem as the 5560U for HDR and Pixel Shaders. I measured the output with Calman and my i1D3, and the dE2000 was 8.1 for that combination, consistent with the AMD measurement, which is quite bad. OTOH, the dE for HDR and DXVA on the N100 was an excellent 0.85, and the dE for SDR was even better, around 0.3 for both DXVA and Pixel Shaders.

In summary, the only bad combination out of HDR/SDR and DXVA/Pixel Shaders is HDR and Pixel Shaders, and it affects both the AMD 5560U and Intel N100 machines. (I didn’t test HDR/Pixel Shaders on my Nvidia card but would assume it’s the same.) The difference is that Kodi selects Pixel Shaders for HDR on the AMD machine when Render Method is set to the default Auto Detect, and trying to override this by choosing DXVA doesn’t help. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

On the AMD 5560U machine, Kodi should have switched to HDR and preserved color fidelity like it does on Intel, Nvidia, and Android.

## Actual Behavior

On the AMD 5560U machine, HDR video has a slight green tint.

## Possible Fix

Examining the AMD logs, Kodi is unable to use DXVA and switches to Pixel Shaders for Render Method for HDR. On Intel and Nvidia, it uses DXVA for Render Method. I replicated the problem by configuring Intel Kodi to use Pixel Shaders. So, there is definitely a problem when using Pixel Shaders for HDR, and there may be a problem with Render Method selection on the AMD 5560U, i.e. “Why wasn’t DXVA automatically selected?”

One thing that is not a potential workaround is setting Render Method to DXVA on the AMD system. Kodi ignores the setting and uses Pixel Shaders anyway.

### To Reproduce

1. I’ve attached three video files to this report, and I got them from Mehanik’s HDR10 test file set and the AVS HD 709 set I found here:
        [HDR10 test patterns set | AVS Forum](https://www.avsforum.com/threads/hdr10-test-patterns-set.2943380/)
        [AVS HD 709 - Blu-ray & MP4 Calibration | AVS Forum](https://www.avsforum.com/threads/avs-hd-709-blu-ray-mp4-calibration.948496/)

2. The first file is for visual comparison, and it is fairly easy to see that something is wrong when Pixel Shaders are in use, “Mehanik - 02. C300-C535.mp4", which appears in the linked pattern set under "Mehanik HDR10 test patterns\03. Grayscale\03. Steps\01. Full steps\ ". If your setup is affected by the problem, and you’re familiar with calibrated screens, you might notice a green tint to these grays, as I did. If you have an Intel or Nvidia card, a Chromecast with Google TV or other Android device, try comparing the AMD playback to them:

https://github.com/xbmc/xbmc/assets/101072550/d411ca4a-40ee-4c26-9e88-e9331f6b4426

3. If you have a meter and software, try measuring patterns with DXVA and Pixel Shaders manually selected. I used this pattern for the HDR measurements in my screenshots, "Mehanik - 11. 50%_C504.mp4", which is found in the linked pattern set at "Mehanik HDR10 test patterns\03. Grayscale\01. 21 Step Grayscale Calibration\01. mehanik\01. 10% window 5% steps\01. Calman and HCFR\01. MaxCLL 1000nit\":

https://github.com/xbmc/xbmc/assets/101072550/f63a5d73-c11a-4d3a-8d05-df36ec3fe77f

4. I used this pattern for SDR, "AVS - 01-100% White.mp4", which is found in the linked pattern set at, "AVS HD 709\CalMAN Windows\11 Step Grayscale\":

https://github.com/xbmc/xbmc/assets/101072550/a89e531c-859e-40ad-89aa-b58b86ac4ab6

5. I’ve noted that Kodi on my AMD 5560U machine selects Pixel Shaders as Render Method for HDR when the default Auto Detect is in effect, while Intel and Nvidia choose DXVA. It would be interesting to see if Kodi does the same for other AMD chips, or if it’s peculiar to ones like mine, which I believe is nominally a laptop CPU with integrated Radeon graphics despite it being used in my mini PC.

### Debuglog

The debuglog can be found here:

I’m providing two debug logs for the HDR playback, the first for AMD 5560U, the second for Intel N100. Both have Render Method set to the default Auto Detect. In the AMD log, Kodi switches to Pixel Shaders for the renderer, while it uses DXVA in the Intel log.

1. [AMD 5560U, HDR, Render Method Auto Detect (selects Pixel Shaders - bad)](https://paste.kodi.tv/igipaqesis.kodi)
2. [Intel N100, HDR, Render Method Auto Detect (selects DXVA - good)](https://paste.kodi.tv/teyehehijo.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

These are screenshots from Calman Home for Sony taken after measuring the above patterns. The first two screenshots are HDR and use the same pattern, a 50% gray from Mehanik’s 1000 nit grayscale set, which appears as a somewhat dim white on my TV. The last screenshot is SDR of 100% white window from the AVS HD 709 pattern set. 

AMD 5560U HDR (Render Method Auto Detect with Pixel Shaders selected by Kodi), also Intel N100 HDR (Pixel Shaders manually selected by me) - Bad, dE2000 = 8.132:
![image](https://github.com/xbmc/xbmc/assets/101072550/ffabb05a-9ab0-4ae0-8248-e91f0a0fd780)
  
Intel, Nvidia, Android 10, 12 HDR (default Render Method for all, or DXVA manually selected in Windows) - Good, dE2000 = 0.849:
![image](https://github.com/xbmc/xbmc/assets/101072550/9131fd18-3706-4d77-8b5a-62152b8237a9)

SDR for all devices, including AMD, and for the Windows machines, DXVA and Pixel Shaders measure the same - Good, dE2000 = 0.2:
![image](https://github.com/xbmc/xbmc/assets/101072550/e9b9be70-f75b-4eae-8309-c841bf09f4e5)
 
 

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 Pro
 - Kodi version: Omega Beta 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by crawfishie** [comment]
It occurred to me that it might be possible to take screenshots and examine pixel values, and it works, agreeing with my Calman measurements and visual observations. I found that Windows 11 Alt+PrtScr doesn't handle HDR properly, but Game Bar Win+Alt+PrtScr does. While I don't have a program that has a color picker tool and can load the HDR .jxr files Game Bar saves, Game Bar also saves .png files that are correctly mapped to SDR, and that's what I've inserted below. I loaded the screenshots I took while playing the "Mehanik.-.11.50._C504.mp4" file from my first post into GIMP, used the color picker tool on the grayscale rectangle, and saved the following images.

First, the good DXVA result:

DXVA: The patch is RGB(128,128,128), which seems quite correct for a 50% HDR grayscale patch converted to SDR.
![DXVA](https://github.com/xbmc/xbmc/assets/101072550/da0105bc-d26d-459c-b8ae-e2713a079e1f)

Next, the inaccurate Pixel Shaders result:

Pixel Shaders: The patch is RGB(124, 129, 125), which is the same inaccuracy I documented in my submission:
![Pixel Shaders](https://github.com/xbmc/xbmc/assets/101072550/d5babd52-55b9-43c9-97d0-38f094e6237e)

Again, the really concerning problem is that my AMD 5560U machine cannot be made to use DXVA, at least not by changing the Render Method setting, so there's no workaround I know of. If all AMD cards behave like this, then no one with an AMD card is getting accurate color in HDR. If they calibrated with an accurate source, viewing on AMD is compromised. Conversely, if they used AMD as their calibration source for HDR, viewing on non-AMD devices is compromised.

**Comment by thexai** [comment]
I can not talk about Pixel Shaders inaccurate color yet but for other issue not seems a bug.

Based on this:

```
2024-02-14 15:07:44.904 T:5536    debug <general>: DXVA::CEnumeratorHD::SupportedConversions: source: primaries bt2020, color space bt2020nc, transfer smpte2084, limited range, dest: HDR
2024-02-14 15:07:44.904 T:5536    debug <general>: DXVA::CEnumeratorHD::SupportedConversions: natural dxgi color space mapping of source: YCBCR_STUDIO_G2084_TOPLEFT_P2020, dest: RGB_STUDIO_G2084_NONE_P2020
2024-02-14 15:07:44.904 T:5536    debug <general>: DXVA::CEnumeratorHD::LogAndListConversions: dxgi color space mapping of source: YCBCR_STUDIO_G2084_TOPLEFT_P2020, dest color space: RGB_STUDIO_G2084_NONE_P2020
2024-02-14 15:07:44.904 T:5536    debug <general>: DXVA::CEnumeratorHD::SupportedConversions: no supported conversions. Trying alternative chroma siting left for HDR source.
2024-02-14 15:07:44.904 T:5536    debug <general>: DXVA::CEnumeratorHD::LogAndListConversions: dxgi color space mapping of source: YCBCR_STUDIO_G2084_LEFT_P2020, dest color space: RGB_STUDIO_G2084_NONE_P2020
2024-02-14 15:07:44.904 T:5536  warning <general>: DXVA::CEnumeratorHD::SupportedConversions: no conversions supported.
2024-02-14 15:07:44.904 T:5536  warning <general>: CRendererDXVA::GetWeight: DXVA will not be used.
```

Is not a option to use DXVA automatically nor manually because AMD video driver not supports output color space `RGB_STUDIO_G2084_NONE_P2020`  (RGB, limited range, PQ transfer, BT.2020).  

More precisely, even if it is supported, the problem is that "the driver says that it does not support it".

If you want use DXVA in this device probably the only option is use full range output: `RGB_FULL_G2084_NONE_P2020` which surely is properly supported because is very common. 

Anyway RGB full-full-full chain is a very good option using HDR or 10 bit SDR (enabling setting "Use 10-bit for SDR") because banding issues are almost nonexistent and color/range conversions uses 10 bit precision.

In any case, this is a limitation on this AMD device or video driver (not all AMD devices are affected).

The other issue (color drift in Pixel Shaders) is interesting to investigate trough.

**Comment by thexai** [comment]
Tested picture and is true that has green tint but _only_ when is captured using Windows Game Bar:

**Captured using Game Bar (Windows + Alt + G)**
![Kodi 17_02_2024 19_36_03](https://github.com/xbmc/xbmc/assets/58434170/78077727-26fa-4cb3-9fa9-895bcffa8ccb)

![Captura de pantalla 2024-02-17 194406](https://github.com/xbmc/xbmc/assets/58434170/c11b383b-7d7a-4beb-8d54-b5f3d574a951)

RGB = 124, 129, 125


**Captured using built-in Kodi screenshot (Ctrl + S):**
![screenshot00000](https://github.com/xbmc/xbmc/assets/58434170/d8b45ffa-8f3e-4ddc-8adb-51744ee92d36)

![Captura de pantalla 2024-02-17 194534](https://github.com/xbmc/xbmc/assets/58434170/96736ca5-417d-46fe-b52e-ec62a87fe55c)

RGB = 124, 125, 124

**Comment by crawfishie** [comment]
I get the same result as you with Kodi Ctrl+S, which is the same as I got with Windows Alt+PrtScr. It appears Game Bar Win+Alt+PrtScr is the only one that creates a .png file that's correctly mapped down from HDR to SDR. The Game Bar .png matches what my meter read, so I have to believe it's the correct one.

I can confirm Kodi can use DXVA instead of Pixel Shaders on my AMD 5560U box when Kodi is configured for Full Range, and it gives correct output like Intel and Nvidia. It's just the Limited Range option that limits it to Pixel Shaders on this chip. 

As to the extent this Pixel Shaders inaccuracy is visible in "real" material, I haven't evaluated it, but I did notice something off when I played the file Mehanik.-.02.C300-C535.mp4 from my OP. That's what caused me to drag out the meter and measure the other test pattern I uploaded, which I don't normally do. When I evaluate a new video playback setup, I visually go through the basic patterns in AVS HD 709 for SDR black/white clipping, grayscale ramp, etc, and similar stuff from Mehanik's HDR10 set, and if all those look as expected, I call it a day. This 5560U didn't let me call it a day. lol

**Comment by thexai** [comment]
I found something related to lack of precision in 10-bit YUV to RGB conversion...

This test build should fix Pixel Shaders green tint:
[KodiSetup-20240218-2746467c-fix-pixel-shaders-x64.exe](https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240218-2746467c-fix-pixel-shaders-x64.exe)

**Comment by crawfishie** [comment]
Works. Nice going!

If there's anything else I can test on this AMD 5560U, let me know, because I'm going to return it and keep the N100. The AMD has gone to a black screen with no recovering the video a couple of times, and the HDMI port is loose and can lose signal just moving the mini PC over on my desk. Plus, Beelink has apparently limited the HDMI ports on both devices so 4K@60Hz@10 bits is impossible; the maximum is 8 bits for that res, but 4K@30Hz does work at 10 bits. Ignoring this limitation, the N100 (S12 Pro) seems to work perfectly all around, and it's cheaper to boot.

BTW, if I can go a little off-topic, when Windows is configured as 4K@60Hz and 8 bits, Kodi can play 4K@60 HDR videos without dropping to 30 Hz, and Windows 11 uses "8-bit with dithering", as it reports in System->Display->Advanced. It would be cool if Kodi could play 4K@30 HDR and below at 10 bits when Windows is set up this way, but it won't go above 8 bits no matter what, not for HDR or SDR. The best compromise is to set Windows for 4K@30 (or 2K@60) and 10 bits, and then I get 10 bits for everything at or below 4K@30Hz in Kodi, which is fine in general, because that covers everything I have except a couple of test files that are 4K@60 HDR. Still, it would be nice to play them without Kodi dropping to 30 Hz.

**Comment by CrystalP** [comment]
Indeed the dxva processor of recent-ish AMD GPUs doesn't support limited RGB output. Trying to force that mode gives full range output, not an improvement!

Kodi should play 4k@30Hz/10 bits if you change the "Use 10 bit for SDR" option to On. Auto means off for AMD.
