### ISSUE TITLE
v21.0b3-Omega Confluence skin disabled

### ISSUE THREAD

**Issue by Clumpton** [xbmc/xbmc#24718]
### Describe the bug
Here is a clear and concise description of what the problem is:
v21.0b3-Omega disables Confluence skin.

Just upgraded to v21.0b3-Omega on nVidia Shield Pro. On restart it disabled Confluence Skin due to incompatibility. List of available skins also greatly reduced.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Confluence skin should be available.

## Actual Behavior

Confluence skin is not available.

### To Reproduce

1. Choose Confluence skin in Kodi Omega beta 1 or 2
2. Update to latest beta (Omega beta 3 15/02/2024)
3. Start Kodi

### Debuglog

The debuglog can be found here:
Sorry - can't supply as I can no longer install Confluence

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Mrs C will be most upset and lost having to use Estuary instead of Confluence, I will probably have to sleep on the sofa until it is fixed.

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
nVidia Shield Pro
 - Operating system version/name: Android TV 11.0.0 API level 30
 - Kodi version: 20.90.830

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Its not a bug. Comments regarding the skin abi change were in release notes of beta2. Forum has info https://forum.kodi.tv/showthread.php?tid=372280&pid=3174566#pid3174566

**Comment by Clumpton** [comment]
@fuzzard Thanks for the clarification!
Hopefully the Confluence guys are still alive and able to adapt.
