### ISSUE TITLE
[Addon] subtitle download for blueray content failing, opensubtitle.com addon

### ISSUE THREAD

**Issue by A1RF0RCE1** [xbmc/xbmc#24728]
### Describe the bug

Download subtitle with opensubtitle.com addon is resulting in an error

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Subtitle list to appear

## Actual Behavior

Addon showing error

### To Reproduce

1. Start blueray movie 
2. Download subtitle (with addon opensubtile.com enabled)
3. Error … 
4. 

Note download for mkv movie still working 

### Debuglog

The debuglog can be found here:

Will add this asap 

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ X] Linux (libreelec)
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
That's an issue of the add-on, not Kodi.
