### ISSUE TITLE
Error <align>right</align> at line break [CR]

### ISSUE THREAD

**Issue by Fuchs246** [xbmc/xbmc#24725]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using a line break, the entire text is no longer aligned to the right.
The longer text is aligned to the right.
The shorter text is aligned to the left, to the beginning of the longer text.

Nexus alignment correct:
![screenshot00019](https://github.com/xbmc/xbmc/assets/44177927/b6e91139-192f-4a5b-88f9-59a3689280a7)

Nexus alignment not correct:
![screenshot00017](https://github.com/xbmc/xbmc/assets/44177927/99397c93-cbc9-4f26-bc4c-19ea49e8cfd0)

Nexus alignment not correct:
![screenshot00015](https://github.com/xbmc/xbmc/assets/44177927/c89304e6-ecbe-4e90-8b51-afe102b2f1c6)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

All text is aligned to the right.

## Actual Behavior

Only the longest text is aligned to the right.

## Possible Fix

Possible cause of this error: 
https://github.com/xbmc/xbmc/pull/24624

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows10
 - Kodi version: Kodi 21 Omega beta3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Fuchs246** [comment]
Oops, the screenshot should say “not correct” Omega.
Copy and paste error on my part.

**Comment by Ch1llb0** [comment]
Related to this one? https://github.com/xbmc/xbmc/issues/24246

**Comment by CastagnaIT** [comment]
its possible
but to understand something is needed to see the xml code of the control that show the "bad" aligned text on screenshots above that has not been attached

**Comment by Fuchs246** [comment]
> its possible but to understand something is needed to see the xml code of the control that show the "bad" aligned text on screenshots above that has not been attached

Here is my xml code:

`<control type="label">`
`	<!--PlayerActionLabel-->`
`	<animation type="Conditional" condition="player.paused | player.forwarding | player.rewinding">`
`		<effect type="slide" start="0,0" end="-150,-5" time="200" tween="cubic" easing="inout" delay="0" />`
`	</animation>`
`	<right>60</right>`
`	<posy>95</posy>`
`	<width>890</width>`
`	<align>right</align>`
`	<font>Reg30</font>`
`	<textcolor>$INFO[Skin.String(OSDPrimaryTextColor)]</textcolor>`
`	<shadowcolor>$INFO[Skin.String(OSDPrimaryTextShadowColor)]</shadowcolor>`
`	<label>$VAR[PlayerFinishTime,[B]$LOCALIZE[31112][/B][CR] ,]</label>`
`</control>`

`<control type="label">`
`	<!--Total duration-->`
`	<animation type="Conditional" condition="player.paused | player.forwarding | player.rewinding">`
`		<effect type="slide" start="0,0" end="-150,20" time="200" tween="cubic" easing="inout" delay="0" />`
`	</animation>`
`	<right>60</right>`
`	<posy>145</posy>`
`	<width>890</width>`
`	<align>right</align>`
`	<font>Reg30</font>`
`	<textcolor>$INFO[Skin.String(OSDPrimaryTextColor)]</textcolor>`
`	<shadowcolor>$INFO[Skin.String(OSDPrimaryTextShadowColor)]</shadowcolor>`
`	<label>$INFO[Player.Duration(h),[B]$LOCALIZE[180][/B][CR],h]$INFO[Player.Duration(mm),,min]</label>`
`</control>`

**Comment by Fuchs246** [comment]
> I made a fix, please give a feedback, you can choose one on these test builds

This change has fixed the error.

Tested with test version:
http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240304-78004ff5-truncate_text_edit-x64.exe
