### ISSUE TITLE
Official PPA outdated

### ISSUE THREAD

**Issue by juerb** [xbmc/xbmc#24724]
### Describe the bug
The official ppa https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa is still on 20.2. Since version 20.4 released it would be nice if someone could  update the packages. 

## Expected Behavior
New packages are available shortly after new stable release of kodi.

## Actual Behavior

PPA lags months behind.

## Possible Fix

Best case scenario would be an automated release process on stable releases.

### To Reproduce

1. Add PPA to Debian 12 installation
2. apt install kodi-bin
3. Installed Version is 20.2

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian 12
 - Kodi version:

**Comment by sarbes** [comment]
Yes, the PPA is deprecated.
