### ISSUE TITLE
jsonrpc Player.Open add fileName to Item

### ISSUE THREAD

**Issue by AmitShadadi** [xbmc/xbmc#24726]
## Roadmap or todo item
**Detailed Description**
Story:
Today jsonrpc API allows sending a file to be played by Kodi, the file's name is taken from the path to the played file, 
My suggestion is to add a property that will specify an alternate file name, if set, it will be used as the actual file's name for any other operations but playing the file.

### Context
Why is this change important to me?
Some sources of file doesn't name the file's name in there original true names, for example if we take an IPTV services, some of them renaming the names of their files as a number, for example 1234.mkv, so when played by Kodi, information is missing, subtitles cannot be automatically searched (must use manual search) and so on, allowing to override the file's name can be really helpful in this case, I'm sure this feature will be a bless for many other users.

### Additional context, screenshots or links

**Comment by the-black-eagle** [comment]
Please use the forum for feature requests -> https://forum.kodi.tv/index.php  Thank You.
