### ISSUE TITLE
Slow down access to mariadb database since 21b3

### ISSUE THREAD

**Issue by dkangel666** [xbmc/xbmc#24738]
### Describe the bug
update kodi from 20..4 to 21b3
mariadb database upgraded automaticaly to myvideos131
it take now more than a minute to show movie library

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Normal speed when accessing database

## Actual Behavior

time has passed from two seconds to one minute to see movie library

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/tekibenizu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 and Android on NVidia Shield
 - Kodi version: 21b3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ProgUnlimited** [comment]
Have the same problem, however restarting mariadb or the underlying server did not resolve it.

Log: https://paste.kodi.tv/ojusarewet

MariaDB is running in a ProxMox container. For 20.5 everything is running fast, but in 21.0 it takes a long time to open Movies. Observation: in 20.5 cpu on the mariadb server is low (10%) during opening Movies and network traffic is high. In 21.0, CPU on the mariadb server is maxing out to 100% (!) and network traffic is low. So definitively a very different behaviour here. 

Going back to 20.5 restores the normal behaviour.

Thanks for looking into it again.

**Comment by CrystalP** [comment]
@dkangel666 some performance issues were corrected after 21b3. Unless you reply in the next week that the issue still exists in 21.0 I will close the ticket.

@ProgUnlimited Likely unrelated to the OP, please ask for support in the forums first. At first glance of the log, the queries against movie_view take 2 minutes, which is not a widespread problem and likely indicates a missing index or some database problem specific to your install. A library of 3800 movies shouldn't make a db engine sweat. To be continued in forum.

**Comment by CrystalP** [comment]
Closing, can be reopened if OP still has the issue in v21 final.
