### ISSUE TITLE
Add icon, screenshots to F-droid

### ISSUE THREAD

**Issue by inson1** [xbmc/xbmc#24731]

**Comment by fuzzard** [comment]
We don't maintain the fdroid build/app submission

**Comment by IzzySoft** [comment]
@fuzzard Fastlane is less about build/submission, it's about providing metadata such as app description and screenshots to be (automatically) used by those "presenting" your app (including, but not limited to, F-Droid). So it gives you control of how your app is presented, and ensures that information is up-to-date (if you keep it up-to-date). F-Droid would just use the metadata – but if you want you can also use the fastlane binaries to e.g. generate screenshots or distribute the structures to PlayStore.

For guidance with setup and to give you an idea how the structure looks like, be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688).
