### ISSUE TITLE
regression in dolbyvision omega beta 3 and nightlies

### ISSUE THREAD

**Issue by usemore** [xbmc/xbmc#24749]
### Describe the bug
Here is a clear and concise description of what the problem is:

choppy playback or non-playback of dv videos on google tv.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

it was working....would like it to resume smooth playback

## Actual Behavior

choppy playback or non-playback of dv videos.
sometimes it just sits there on a frozen frame. 
data throughput is not an issue.
cpu is usually ~200%/400
plenty of free mem

## Possible Fix

revisit changes made in february.

### To Reproduce

1. reboot
2. play dolbyvision content 
3. sigh.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

android12 googletv /kodi omega beta 3 AND nightlies
 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
No debuglog no issue. Try again with a new defect.
