### ISSUE TITLE
Subtitle behavoir "Regression" on Omega B3

### ISSUE THREAD

**Issue by hagaygo** [xbmc/xbmc#24742]
### Describe the bug
There has been a change (kind of regression on my use case) between Beta 2 and Beta 3 (omega).
I found it was introduced in https://github.com/xbmc/xbmc/pull/24252

Before this change using 3rd party addon for playing back video caused subtitle to be stored on subtitle special folder (with generic name of stream.en.srt for example)
Then i had a script that rename it to the correct name.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

While i could (and i guess few more users) handle the old behavior i think it would be logical that the downloaded subtitles would be stored on the custom folder if defined with the correct file name (the subtitle downloader knows the correct filename since it shows correct search results) .
If correct filename is not available then the file should be stamped with a datetime in the filename so it wont be overwritten next download and allow scripters to easily rename them.

I guess the best of all worlds is to add a setting option to keep new behavior which introduced in this PR and old behaviorfor "http" streams when downloading subtitles.

## Actual Behavior

Since updating to beta 3 , no subtitle are stored on the custom folder and when playing (they are stored on kodi's temp/cache folder with the constant name of "TempSubtitle").

## Possible Fix

Explained in expected behavior.

### To Reproduce

1. Setup a custom download folder for subtitles
2. launch a video using addon (http stream)
3. Open subtitle download dialog and download a subtitle (which is played and shown just fine the the current playback session)
4. Check the custom subtitles folder

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: lbreelec 12 nightly
 - Kodi version: 21b3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@neo1973 maybe you can take a look into this?

**Comment by hagaygo** [comment]
Just opened a pull request to allow users to keep old behavior.

I'll try to look into saving the subtitle file with proper name instead of "stream.lang.srt"

**Comment by hagaygo** [comment]
> Just opened a pull request to allow users to keep old behavior.
> 
> I'll try to look into saving the subtitle file with proper name instead of "stream.lang.srt"

It seems the addon does not report "real" filename, and i guess it goes for any other video addon.

I found that the video "title" is available , but its a display one like "The Movie Title" , while the filename is "The.Movie.Tilte.2022.mp4".

Still it might be better to store it as The.Movie.Title.en.srt instead of stream.en.srt (which get overwritten by the next downloaded subtitle)

**Comment by hagaygo** [comment]
Fixed on RC1 by https://github.com/xbmc/xbmc/pull/24752
