### ISSUE TITLE
Since v20.3 my Sofabaton U2 Bluetooth remote no longer works with Kodi Android on Google Chromecast.  

### ISSUE THREAD

**Issue by mytechguyri** [xbmc/xbmc#24751]
### Describe the bug
Here is a clear and concise description of what the problem is:The remote works fine on the Chromecast side, but once I open Kodi, Kodi treats it as a game controller of some sort, and pressing the Ok button on the remote is ignored by Kodi... So I can use the navigation keys on the remote to move about, but I can't select anything, because the Ok button is  ignored by Kodi.   It used to work perfectly prior to v20.3
 Bluetooth remote no longer functions correctly in the Kodi app

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When pressing the Ok button on the Bluetooth remote, the item the cursor is on should be selected to play.

## Actual Behavior

Ok button is ignored, only within the Kodi application.  It works fine once I exit Kodi back to Google TV screen, so it's not a problem with the remote nor the Chromecast device.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Chromecast Google TV Android with Kodi 20.3 and 20.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by htatla81** [comment]
Having the same issue on 20.4 with Logitech Harmony companion remote (Bluetooth) on Amazon fire cube 2nd gen box - except here NO buttons work whatsoever so the app now unusable

had no issues previously or on 20.2 

Pls help!

**Comment by ikane7** [comment]
I also have the same remote control button failure problem. There is no problem on Kodi 20.3. The enter button fails in version 20.4

**Comment by mytechguyri** [comment]
I did find a work around... At least it's somewhat usable, but doesn't work nearly as well as it did in prior versions.   Add a controller profile, game controllers, get more, and select TV Remote .. then you can map about 7 keys on the remote to give you very very basic functionality..select, back, home, up, down, left, right 

Not ideal...not at all like it was in the prior version, but at least it somewhat works.

**Comment by htatla81** [comment]
i tried to downgrade back to 20.2 and lost all of my Kodi settings, even though "do not delete app data" was selected.....ouch...Very sore lesson learned today as a result of this bug. I have also lost precious Add-ons which are no longer available... :(

**Comment by AlexeyTorch** [comment]
same problem. TCL c935 Android TV 11, complete remote control. in 20.3 the remote control works, after updating to 20.4 the ok button does not respond

**Comment by Rob-122** [comment]
my keyboard remote's with there own dongle have always worked until today Kodi 20.4 except it's back that no longer works has something changed?

**Comment by fuzzard** [comment]
do not manually install 20.4 on android devices. There is a known issue, that was resolved in nightlies after 20.4. Sideload a newer nightly if you must use something newer than 20.3

**Comment by mytechguyri** [comment]
Thank you... confirmed problem appears fixed in 20.5

**Comment by htatla81** [comment]
Awesome to hear I will update tonight 

thank you to the devs and anyone involved for the efforts
