### ISSUE TITLE
Full screen error on HDMI

### ISSUE THREAD

**Issue by bremaya** [xbmc/xbmc#24767]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I'm connected to a screen on my Moto G200 5G with Android 12 using Ready For, I can't maximize Kodi (v20.03), the app crashes when I click the maximize button.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Maximize correctly in desktop mode

## Actual Behavior

The app does not maximize when we click the maximize button in desktop mode

### To Reproduce

1. Connect the smartphone to a screen with the HDMI cable
 2. Open Kodi
 3. Click on the maximize button

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android
 - Kodi version: 20.03 arm64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
No response.
