### ISSUE TITLE
Resume from xxx is broken on RPi4B and RPi5B using latest Omega git

### ISSUE THREAD

**Issue by graysky2** [xbmc/xbmc#24760]
### Describe the bug

I can no longer "Resume from xxx" when I try to playback a partially viewed video that the saved resume point.  When I do so, there is no video displayed and the kodi.log is filled with lines like:
 
```
2024-02-25 09:43:50.227 T:556      info <general>: Skipped 10796 duplicate messages..
2024-02-25 09:43:50.227 T:556   warning <general>: OutputPicture - timeout waiting for buffer
2024-02-25 09:43:50.227 T:474     debug <general>: EGL Debugging:
                                                   Error: EGL_BAD_PARAMETER
                                                   Command: eglClientWaitSyncKHR
                                                   Type: EGL_DEBUG_MSG_ERROR_KHR
                                                   Message: _eglClientWaitSyncCommon
```

## Expected Behavior

Video should resume from resume points.

## Actual Behavior

Videos do not resume from resume points and the kodi GUI is frozen until manually restarted.

### To Reproduce

1. Arch ARM RPi4 or RPi5, install `kodi-rpi-git`
2. Playback some video and allow a save point to be created
3. Attempt to resume watching that video from the save point to trigger the bug.

### Debuglog

The debuglog can be found [here](https://gist.github.com/graysky2/5a4975b5bdff987e7f27dafc3211c520)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I am running Kodi built from @popcornmix [gbm-omega fork](https://github.com/popcornmix/xbmc/tree/gbm_omega]gbm_omega) on RPi4B.  I modified it slightly to work under Arch ARM and rebased against master so it is up-to-date with master.  See [here](https://github.com/graysky2/xbmc/tree/gs-gbm_omega).

Thinking that issues should affect the official project code, not a fork, I also created [this](https://forum.kodi.tv/showthread.php?tid=376430) thread on the kodi forum.  I have not been able to reproduce this bug on x86_64/official code.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: ArchARM aarch64
 - Kodi version: latest git (see note above about @popcornmix fork)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Any chance you can bisect to find the offending commit?
Seems to work fine on macOS.

**Comment by graysky2** [comment]
The bisect might be difficult since when I rebase master on top of the fork, the commits from master are added under my modifications ... 

There is also the variable of the linux kernel which tracks the RPi Foundation.  It could be that this bug is due to some changes with the HW decoding in the kernel.  @pelwell @popcornmix - do either of you have any insights in that angle?  I am using the rpi-6.6.y branch of kernels.  I believe this bug manifested a few weeks ago but I am not entirely sure on the timing.

**Comment by neo1973** [comment]
As an additional data point: On a RPi3b with ArchARM armv7h, kodi-rpi-git 21.x.65444.c3011d70d0-1 can resume h264 files without issues.

@graysky2: Does this also happen with h264 on RPi4/5 or only with hevc?

**Comment by graysky2** [comment]
@neo1973 - only HEVC.  The h264 samples work as expected.

**Comment by graysky2** [comment]
I went all the way back to e1c5dec366611e78921602d0a8759d54f19dea85 and I am still seeing this bug on that build.  Perhaps this bug is something new rather than a regression as assumed?  @jc-kynesim - I generated the ffmpeg patch based on your https://github.com/jc-kynesim/rpi-ffmpeg/commits/dev/6.0/rpi_import_1/ branch.  Do you see anything obvious in there that could explain this behavior?

**Comment by graysky2** [comment]
An update: the bug seems to be triggered when `Settings>Player>Video>PRIME Render Method` is set to `Direct to Plane`.  If I switch it over to `EGL`, I have not been able to trigger the bug.  This is on the latest git, not some older version.  Thoughts?

**Comment by popcornmix** [comment]
I've just built LE with gbm/gbm_omega branch rebased on master (I've pushed this).
I've also updated ffmpeg to dev/6.0/rpi_import_1.
Playback resumed correctly for me. I tested with Tears of Steel files (720p and 1080p):
```
3e492c4e94b126c443620cfa6b79208a  TearsOfSteel_1080p_24fps_27qp_1474kbps_GPSNR_42.29_HM11_2aud_7subs.mkv
faddc904f52765f1e47084f729f6a703  TearsOfSteel_720p_h265.mkv
```

**Comment by graysky2** [comment]
Which kernel version is it using?

**Comment by graysky2** [comment]
For anyone following this issue, the cause was updating mesa from `mesa-23.3.5-1` to `mesa 24.0.1-1`.  Applying [this](https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/RPi/patches/kodi/000-temp-revert-fences.patch) patch from LE fixed the issue.

**Comment by fritsch** [comment]
Does it fix the issue or does it mitigate a broken fence signalling in a driver or is the original code in kodi wrong?

**Comment by graysky2** [comment]
@fritsch - I cannot say... [here is a debug log](https://gist.github.com/graysky2/0f40342ab71984b64eff9bc4fc094899) with the patch applied resuming from a saved point.  Does that help to answer your question?

**Comment by hbiyik** [comment]
@fritsch @graysky2 @popcornmix 
i reproduced the same issue with totally different hardware, rk3588 with custom ffmpeg.
It specificly happens when gbm is rendering direct to plane, but the plane can not atomic commit for any reason, in my case it was trying to render a video frame that plane can not handle.

Here is a debug log

```
024-03-21 22:52:58.894 T:1271    debug <general>: CVideoPlayerVideo - CDVDMsg::GENERAL_RESYNC(-100000.000000)
2024-03-21 22:52:58.894 T:1271    debug <general>: ffmpeg[0xaaaaff67a360]: [hevc_rkmpp] Wrote 909684 bytes to decoder
2024-03-21 22:52:58.895 T:1271    debug <general>: ffmpeg[0xaaaaff67a360]: [hevc_rkmpp] Wrote 693894 bytes to decoder
2024-03-21 22:52:58.900 T:1271    debug <general>: ffmpeg[0xaaaaff67a360]: [hevc_rkmpp] Received a frame
2024-03-21 22:52:58.917 T:862      info <general>: Skipped 1 duplicate messages..
2024-03-21 22:52:58.917 T:862     debug <general>: CDRMUtils::DrmFbDestroyCallback - removing framebuffer: 255
2024-03-21 22:52:58.917 T:862     debug <general>: CDRMUtils::DrmFbGetFromBo - using modifier: ARM_BLOCK_SIZE=16x16,MODE=YTR|SPARSE
2024-03-21 22:52:58.917 T:862     debug <general>: CDRMAtomic::FlipPage - Execute modeset at next commit
2024-03-21 22:52:58.917 T:1271    debug <general>: ffmpeg[0xaaaaff67a360]: [hevc_rkmpp] Received a frame
2024-03-21 22:52:58.918 T:862     error <general>: CDRMAtomic::DrmAtomicCommit - test commit failed: (Invalid argument) - falling back to last successful atomic request
2024-03-21 22:52:58.918 T:862     debug <general>: CDRMAtomicRequest::LogAtomicDiff - DRM Atomic Request Diff:
2024-03-21 22:52:58.918 T:862     error <general>: 
                                                   Object: plane	ID: 165
                                                     Property: FB_ID	ID: 17	Value: 255
                                                     Property: IN_FENCE_FD	ID: 18	Value: 93
                                                   Object: plane	ID: 57
                                                     Property: SRC_X	ID: 9	Value: 0
                                                     Property: SRC_Y	ID: 10	Value: 262144
                                                     Property: SRC_W	ID: 11	Value: 503316480
                                                     Property: SRC_H	ID: 12	Value: 283115520
                                                     Property: CRTC_X	ID: 13	Value: 0
                                                     Property: CRTC_Y	ID: 14	Value: 0
                                                     Property: CRTC_W	ID: 15	Value: 1920
                                                     Property: CRTC_H	ID: 16	Value: 1080
                                                     Property: FB_ID	ID: 17	Value: 258
                                                     Property: CRTC_ID	ID: 20	Value: 85
                                                   Object: crtc	ID: 85
                                                     Property: MODE_ID	ID: 23	Value: 259
                                                   Object: connector	ID: 208
                                                     Property: HDR_OUTPUT_METADATA	ID: 7	Value: 0
                                                     Property: Colorspace	ID: 219	Value: 0
2024-03-21 22:52:58.918 T:862     error <general>: CDRMAtomic::DrmAtomicCommit - atomic commit failed: Invalid argument
2024-03-21 22:52:58.920 T:1271    debug <general>: ffmpeg[0xaaaaff67a360]: [hevc_rkmpp] Wrote 703093 bytes to decoder
2024-03-21 22:52:58.920 T:862     debug <general>: Activating window ID: 12005
2024-03-21 22:52:58.921 T:1271    debug <general>: ffmpeg[0xaaaaff67a360]: [hevc_rkmpp] Wrote 554016 bytes to decoder
2024-03-21 22:52:58.923 T:862     debug <general>: ------ Window Deinit (MyVideoNav.xml) ------
2024-03-21 22:52:58.923 T:862     debug <general>: FreeVisualisation() done
2024-03-21 22:52:58.925 T:862     debug <general>: ------ Window Init (VideoFullScreen.xml) ------
2024-03-21 22:52:58.926 T:862     debug <general>: Window VideoFullScreen.xml was already loaded
2024-03-21 22:52:58.926 T:862     debug <general>: Alloc resources: 0.01 ms
2024-03-21 22:52:58.926 T:1271    debug <general>: ffmpeg[0xaaaaff67a360]: [hevc_rkmpp] Received a frame
2024-03-21 22:52:58.931 T:1239    debug <general>: OnAVChange: CApplication::OnAVChange
2024-03-21 22:52:58.933 T:1271    debug <general>: ffmpeg[0xaaaaff67a360]: [hevc_rkmpp] Received a frame
2024-03-21 22:52:58.935 T:862     debug <general>: EGL Debugging:
                                                   Error: EGL_BAD_PARAMETER
                                                   Command: eglClientWaitSyncKHR
                                                   Type: EGL_DEBUG_MSG_ERROR_KHR
                                                   Message: _eglClientWaitSyncCommon
```
the problem, is msg keeps logging the same error, and gui is left unresponsive.

it is indeed gone when async rendering is disabled so i assume a regression form this async patchset
https://github.com/xbmc/xbmc/pull/23921

My HW is:
rk3588 rock5b soc.
[ffmpeg-rockchip,](https://github.com/nyanmisaka/ffmpeg-rockchip) custom fork rockchip mpp based
kernel: mainline 6.8
gpu drm driver: panthor (linux-mainline).
kodi: master branch

If needed i can shoot some gdb on this guy.. I have the env ready.

**Comment by popcornmix** [comment]
Can you test if reverting #23921 avoids the issue for you?

That PR is reverted in LE as it causes issues on Pi and generic:
https://github.com/LibreELEC/LibreELEC.tv/pull/8437

**Comment by chcore** [comment]
I raised #25222 before seeing this. Reverting #23921 fixes it for me on intel platform.
