### ISSUE TITLE
[IOS] Missing arm64e architecture is used on the A12/A13 chipset or newer

### ISSUE THREAD

**Issue by neokuze** [xbmc/xbmc#24762]
### Describe the bug
XBMC does not offer support for devices with arm64e architecture, which is the chipset used in newer Apple phones and tablets released since 2018, including the iPhone XS onwards, as well as the 8th generation iPads and 3rd generation iPad Airs. 

## Expected Behavior
Support for arm64e architecture in XBMC to ensure compatibility with newer Apple devices.

## Actual Behavior
Lack of support for arm64e architecture in XBMC, excluding users of newer Apple devices from using XBMC.

## Possible Fix
Including support for arm64e architecture in future versions of XBMC. 

### To Reproduce
1. Use XBMC on an iPad 9th generation or other arm64e device.
2. Use deb-to-ipa workflow, after that I uploaded the file using sidel0adly in normal mode.
3. Observe lack of compatibility.

## Additional context or screenshots (if appropriate)
This issue affects users of newer Apple devices who are unable to use XBMC due to lack of arm64e support.

### Your Environment
Used Operating system:
 - [x] iOS
 - [ ] Android
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: iOS/iPad gen9 ver-16.5 (arm64e)
 - Kodi: 20.4

**Comment by neokuze** [comment]
> Is missing builds for Ipad and Iphones based on arm64e

Currently, XBMC does not offer support for devices with arm64e architecture, which is the chipset used in newer Apple phones and tablets released since 2018-9 +, including the iPhone XS onwards, as well as the 8th generation iPads and 3rd generation iPad Airs. This omission excludes a significant portion of mobile device users who could benefit from XBMC's features on their devices.

I would suggest considering the inclusion of arm64e support in future versions of XBMC to ensure that users of these devices can also enjoy the full XBMC experience.

Thanks.

**Comment by kambala-decapitator** [comment]
all arm64e devices can run arm64 apps.

just tested [the latest Omega nightly](https://mirrors.kodi.tv/nightlies/darwin/ios-arm64/master/) on "iPad Pro 2022 (11-inch) (4th generation)" (iPad14,3) - runs fine. Currently unclear which issue you're facing.

**Comment by neokuze** [comment]
![image0](https://github.com/xbmc/xbmc/assets/29682872/9205517e-4132-4524-a76b-eff7021b7dde)
I tried using the latest version of the omega build.

**Comment by neokuze** [comment]
![image0](https://github.com/xbmc/xbmc/assets/29682872/8c74964f-197e-4de4-a069-633abb423ce5)
Thanks for your response. I used the latest version of the omega build, using your link but still saying this.

PD: my bad I just mis-click in the close button.

**Comment by neokuze** [comment]
I used deb-to-ipa workflow, after that I uploaded the file using sidel0adly in normal mode.

> all arm64e devices can run arm64 apps.
> 
> just tested [the latest Omega nightly](https://mirrors.kodi.tv/nightlies/darwin/ios-arm64/master/) on "iPad Pro 2022 (11-inch) (4th generation)" (iPad14,3) - runs fine. Currently unclear which issue you're facing.

**Comment by kambala-decapitator** [comment]
> I uploaded the file **using sidel0adly** in normal mode

ask sidel0adly for support then. We test and recommend only http://dantheman827.github.io/ios-app-signer/ , you can find manual at https://forum.kodi.tv/showthread.php?tid=245978
