### ISSUE TITLE
Non-functioning remote control in Kodi Nexus 20.4 with which the settop box is controlled 

### ISSUE THREAD

**Issue by Flekoun58** [xbmc/xbmc#24769]
### Describe the bug
Here is a clear and concise description of what the problem is:

In the Nexus 20.4 version, the Bluetooth remote control with which I control the settop box does not work in Kodi Nexus 20.4, only the direction buttons work, but the others do not. This means that you will not get to the item you selected. In the Nexus 20.3 version, everything works correctly, it also works correctly in the 0mega beta 3 version. Unfortunately, in the Nexus 20.4 version, the control is ignored, therefore the Kodi nexus 20.4 application is unusable. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It expects the controller to work as it did in previous versions

## Actual Behavior

 Remote buttons in kodi are ignored. 

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android 
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android
 - Kodi version: 20.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Sideload a newer nightly. We have intentionally disabled play store deployment for 20.4 shortly after we were made aware of the issue, so I would expect you have already sideloaded 20.4

**Comment by Flekoun58** [comment]
> Sideload novější noční. Krátce poté, co jsme byli o problému informováni, jsme záměrně zakázali nasazení obchodu Play pro verzi 20.4, takže očekávám, že jste již nainstalovali verzi 20.4

Hello, I installed version 20.4 via addon in kodi from official kodi repository because version 20.4 is not in google play. After downloading I got an error viz. mentioned above so I uninstalled version 20.4 and installed Omega beta 3 instead and it works fine there. 

PS: Sorry for my bad English

**Comment by Flekoun58** [comment]
Hello, I installed version 20.4 via add-on in kodi from the official kodi repository, because version 20.4 is not in google play. After downloading I got this error so I uninstalled version 20.4 and installed Omega beta 3 instead and it works fine there. 

PS: sorry for my bad english.
