### ISSUE TITLE
Some dolby vision mkv files are cropped in Kodi v21 omega beta 3 + previous omega version

### ISSUE THREAD

**Issue by absolution1** [xbmc/xbmc#24764]
### Describe the bug
Some dolby vision mkv rips that have had their black bars removed show a cropped image.

As above, playing certain dolby vision mkv rips show a cropped image; it's as if the black bars have been enlarged and eat into the picture.  I don't have a vast library to test with but, from what I can gather, it's related to rips with resolutions that remove the black bars e.g. 3840x1608.
Tinkering with this: 
 - if I disable hardware acceleration then the video is displayed correctly
 - if I disable dolby vision in Kodi's settings then the video is displayed correctly (no cropping)
I've seen this cropping behaviour happen in a couple of videos, and the cropping has appeared on videos with either horizontal or vertical black bars.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Dolby vision mkv playback for videos with their black bars removed in the rip should not show a cropped video.

## Actual Behavior

Dolby vision mkv playback for videos with their black bars removed in the rip does show a cropped video.

## Possible Fix

No suggestions for a fix, but I have found other users who have seen this problem
(Both of these links refer to the kodinerds build, but describe the same problem.  I did test this by installing the kodinerds build)
 - https://www.reddit.com/r/kodi/comments/w4edcq/aspect_ratio/
 - https://www.reddit.com/r/kodi/comments/u43v0o/dolby_vision_movies_zoomed_in/

### To Reproduce

1. Setup kodi v21 beta 3 on android TV
2. Get video with removed back bars + dolby vision in mkv format e.g. res: 3840x1608, aspect ratio: 2.40:1
3. Play video
4. See cropped video

### Debuglog

The debuglog can be found here:
STILL NEED TO PROVIDE ONE

### Screenshots 
Here are some links or screenshots to help explain the problem:

(Not my image but it demonstrates the problem): https://imgur.com/a/Z84O9Ai

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV (Android 9)
 - Kodi version: v21 Omega Beta 3
 - Hardware: Sony XH95 TV with Kodi installed on the OS.  No external hardware is used for playing media.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Hitcher** [comment]
Doesn't happen on my Shield TV Pro. Are you using a Fire TV?

**Comment by absolution1** [comment]
No, Im using the native Kodi app on my Sony XH95 Bravia TV.

It doesn't happen with every DV MKV.  Have you tried a file with something similar to this?
 - Resolution: 3840x1608 
 - Aspect ratio: 2.40:1

**Comment by Hitcher** [comment]
Yes.

```
Width                                    : 3 840 pixels
Height                                   : 1 608 pixels
Display aspect ratio                     : 2.39:1
```

**Comment by Hitcher** [comment]
You might need to provide a snippet of an affected file.

**Comment by absolution1** [comment]
Is there a guide I could follow to do that and maintain the DV metadata?
I wonder if its worth me also trying a snippet of your video file?

**Comment by Hitcher** [comment]
Here, try this: https://www.mediafire.com/file/23nlfcg9nuk80rq/test.mkv/file

**Comment by quietvoid** [comment]
Duplicate of https://github.com/xbmc/xbmc/issues/24420.

**Comment by absolution1** [comment]
@quietvoid how can you tell?  I had a look at the issue you linked to; the image is semi-transparent near the black bars and I'm not seeing that...

**Comment by quietvoid** [comment]
> @quietvoid how can you tell? I had a look at the issue you linked to; the image is semi-transparent near the black bars and I'm not seeing that...

It's probably just different behaviour on newer TVs. But the issue is the same.
To confirm you should share a short sample.

**Comment by absolution1** [comment]
I checked the GitHub issue you linked to and downloaded just player; I see the same issue with the video file when playing through player.

Could you point me to a guide for ripping a segment of the video and keeping the DV metadata intact?

**Comment by quietvoid** [comment]
You can use ffmpeg to trim the video, in CLI:
```sh
ffmpeg -ss 00:01:00 -i video.mkv -t 00:00:05 -c:v copy video-sample.mkv
```

**Comment by absolution1** [comment]
Thanks.  I've ripped the WB logo transition: https://www.mediafire.com/file/491h9i9dhql9wcz/video-sample2.mkv/file
with DV enabled, the top of the WB logo still clips the top of the letterbox after its stopped moving

**Comment by quietvoid** [comment]
Right.

The video is 3840x1608 and the metadata is incorrect.
It still says that the video needs 276 pixels of cropping on top/bottom, hence the double crop appearance on playback.

Not a Kodi issue.

**Comment by absolution1** [comment]
Great, thank you so much for checking this.  I'll close this issue.  Apologies for the distraction!
