### ISSUE TITLE
Kodi Verze Nexus 20.4.- nefunkční ovládáni

### ISSUE THREAD

**Issue by Flekoun58** [xbmc/xbmc#24768]
In the Nexus 20.4 version, the Bluetooth remote control with which I control the settop box does not work in Kodi Nexus 20.4, only the direction buttons work, but the others do not. This means that you will not get to the item you selected. In the Nexus 20.3 version, everything works correctly, it also works correctly in the 0mega beta 3 version. Unfortunately, in the Nexus 20.4 version, the control is ignored, therefore the Kodi nexus 20.4 application is unusable.

**Comment by fuzzard** [comment]
Known issue. Use a newer nightly
