### ISSUE TITLE
Jellyfin add-on does not work from 21 beta3

### ISSUE THREAD

**Issue by raylapse** [xbmc/xbmc#24776]
With 21 beta3, install jellyfin offcial plugin and choose local path mode.
After adding the jellyfin library (from a local network nas), there is no movies/videos appears in kodi.

In file manager, the corresponding path has already been added as a source, so this should not be a access issue to nas.

Same configuration works fine with 21 beta2. I double checked this for several times with a clean install of kodi. So please check and provide a correction.

**Comment by fuzzard** [comment]
You'll need to take it up with the jellyfin for kodi addon devs most likely. Of note there have been numerous videodb version bumps between b2 and b3.
