### ISSUE TITLE
Black channel icons in Favourites (Estuary skin) with transparent background can't be seen

### ISSUE THREAD

**Issue by iparamr** [xbmc/xbmc#24780]
### Describe the bug
Here is a clear and concise description of what the problem is:

Black channel icons in Favourites (Estuary skin) from Kodi with transparent background can't be seen

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The transparent channel icon should not blend with the background. It should be visible.

## Actual Behavior

Black channel icons in Favourites (Estuary skin) from Kodi with transparent background can't be seen

## Possible Fix

Can a white default background in favourites be added for transparent channel icons?

### To Reproduce

1.  Get any PVR client with channels and some transparent channels icons (png)
2. Add those channels to favourites to Estuary skin
3. Go to Favourites and view the newly added favourite which is dark, e.g. black
4. You will notice that it blends with the dark Estuary skin background and it makes the channel icon difficult to see.
5. See screenshot below

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

Here are some screenshots of the problem:
Favourites Thumbnail (Unselected)
<img width="293" alt="image" src="https://github.com/xbmc/xbmc/assets/13896015/c5fd39af-1546-4cb0-b45b-a8e079779c0d">

Favourites Thumbnail (Selected)
<img width="335" alt="image" src="https://github.com/xbmc/xbmc/assets/13896015/18ced2b3-c5ea-41b9-a268-b2b31bc42bab">

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] tvOS
 - [x] Linux
 - [x] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Nexus
v 20.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by iparamr** [comment]
I have added the Debuglog now

**Comment by Hitcher** [comment]
1.  A skin doesn't know that a logo has any transparency.
2. Changing it to white would then affect white logos.
3. You can add make your own logo with a background colour: https://kodi.wiki/view/Live_TV_Artwork

**Comment by iparamr** [comment]
Background doesn’t have to be changed to white exactly, it was just example. There could be a more elegant solution. I’m using IPTV and there are 1050 channels and changing logos for each one of them manually is not possible as there are over 100 black  logos similar to the problem I demonstrated.

**Comment by ksooo** [comment]
Of topic: Wow, 1050 channels and I bet you watch each and every one regularly. 😜

**Comment by sarbes** [comment]
Thumbnails should not contain transparent regions. Our Wiki isn't specifically clear about that (https://kodi.wiki/view/Artwork_types), but only very few artwork types explicitly admit transparency.

If a clear logo is displayed, it is a bug. Otherwise, it is not.

In any case, your logo is not suited for Kodi. It displays a white border due to missing color information in those regions.

**Comment by sarbes** [comment]
In regards if icons... It is skin specific. Most darker skins expect a bright, "light" icon. And I would argue that this is the default for Kodi.

Instead of changing the presentation for displaying such icons, you might as well create a new skin. And it would break "normal" icons out there. This is way more work than simply using a suitable icon set.

You could try a light skin instead.

**Comment by iparamr** [comment]
In my opinion, it's not an issue with icons. The service providers are the ones providing icons. Users don't have control on the transparency.

In this image from https://kodi.wiki/view/Live_TV_Artwork if you look at "ABC HD" icon it's completely black and has transparent areas. Similarly other icons can have similar issues.

![image](https://github.com/xbmc/xbmc/assets/13896015/d0eedb44-1c56-4305-be19-efffe97072aa)

**Comment by iparamr** [comment]
<img width="1173" alt="image" src="https://github.com/xbmc/xbmc/assets/13896015/1013b972-7bf9-4c98-a8fc-36360dfbf11b">

**Comment by iparamr** [comment]
@sarbes I appreciate your response. Which skin shall I use? Can you suggest? I want the one which allows me to use Favourites

**Comment by sarbes** [comment]
Maybe Unity. But there is not much choice. Perhaps some skins support a suitable theme.
