### ISSUE TITLE
User-agent as normal query parameter

### ISSUE THREAD

**Issue by alanmilinovic** [xbmc/xbmc#24790]
I just have a question about user-agent. Is it possible to have user-agent specified as normal url parameter? Like this: http[s]://[host[:port]/directory/file?user-agent=b

The thing is that using it in this way: http[s]://[host[:port]/directory/file|user-agent=b

Is causing issues in other programs I am using and my video files are not working, because this is not a standard URL formatting.

Would be amazing, if both formatting is supported.

Thank you.

**Comment by enen92** [comment]
Please use the forum for support/feature requests.
I don't think your request makes sense as this was just add headers as query arguments.
