### ISSUE TITLE
Black screen while playing all HEVC on Arch Linux - Kodi Omega Beta 3

### ISSUE THREAD

**Issue by cg00001** [xbmc/xbmc#24802]
### Describe the bug
Here is a clear and concise description of what the problem is:

Black screen while playing all HEVC files on Arch Linux - Kodi Omega Beta 3.
This started a few builds of kodi-git back.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Play HEVC files normally.

## Actual Behavior

On all HEVC files it shows black screen, but audio plays.

### To Reproduce

1. Just install latest Kodi Omega and try to play an HEVC file.
2.
3.

### Debuglog

The debuglog can be found here:
Sorry only partial log, Kodi Omega erased and Nexus used now.

2024-03-04 07:32:09.107 T:7528     info <general>: CDVDVideoCodecFFmpeg::Open() Using codec: HEVC (High Efficiency Video Coding)
2024-03-04 07:32:09.192 T:825      info <general>: GLES: Selecting single pass rendering
2024-03-04 07:32:09.192 T:825      info <general>: GLES: Selecting YUV 2 RGB shader
2024-03-04 07:32:09.192 T:825     error <general>: GLES: BaseYUV2RGBGLSLShader - unsupported format 3

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Arch Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Arch Linux.
 - Kodi version:
Kodi Omega Beta 3.
Kodi git version (binary used): kodi-git r65461.8404b9f510f-1
Current AUR git version (waiting to be converted to binary): kodi-git r65168.a4b164c00cb-1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
The problem is likely that the maintainer switched the build to default to GLES, see https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=kodi-git&id=508c6d72d3451514a56d9210a0c0d85052c45c43

For everything else we need a full log because we know nothing about your setup/environment.

**Comment by cg00001** [comment]
Thanks for your reply.

**Comment by ilikenwf** [comment]
Have you looked into the hardware acceleration settings? In addition what graphics card are you using?

HDR doesn't work at all unless GLES is used.

**Comment by graysky2** [comment]
Please see line 24 in the `PKGBUILD` wherein you need to define the `_renderer` variable to a value of either `gles` or `gl`.

**Comment by cg00001** [comment]
> Have you looked into the hardware acceleration settings? In addition what graphics card are you using?
> 
> HDR doesn't work at all unless GLES is used.

I would take HEVC any day instead of HDR, I never had such an issue with Kodi until now.
The problem is I'm using a kodi-git binary from Chaotic-AUR, and it autobuilds gles instead of gl, there is no way to enable gl from within Kodi.

**Comment by ilikenwf** [comment]
Sounds like a hardware issue in this guy's case to me. HDR works great with my Arc, save for vp9 videos on youtube...

I want both and both work if I use cpu rendering for vp9...my fancy TV does HDR nicely.

**Comment by cg00001** [comment]
> Sounds like a hardware issue in this guy's case to me. HDR works great with my Arc, save for vp9 videos on youtube...
> 
> I want both and both work if I use cpu rendering for vp9...my fancy TV does HDR nicely. Even OSMC defaults to gles now.

If it's a hardware issue of mine, how come HEVC always worked in the past without Gles?
It's a Gles issue.

**Comment by cg00001** [comment]
I've asked Chaotic-AUR to change PKGBUILD to gl before building, we'll see.

**Comment by cg00001** [comment]
It's done, kodi-git from Chaotic-AUR binary works as it should.
