### ISSUE TITLE
Kodi scraper error 10054

### ISSUE THREAD

**Issue by annapl2624** [xbmc/xbmc#24806]
Kodi scraper error 10054 while starting kodi 

![Screenshot 2024-03-04 224058](https://github.com/xbmc/xbmc/assets/57759259/fa58d8e5-dcc7-49f5-8002-46468807a2cc)

**Comment by KarellenX** [comment]
@annapl2624 

I am going to close this issue as it is not a Kodi problem, rather an internet connection problem with your pc.

Please read this thread... https://forum.kodi.tv/showthread.php?tid=376366
I don't think we will be able to help with your local issue, but if you have any questions please feel free to ask in that thread.
