### ISSUE TITLE
Can not play BDMV movies through .strm file

### ISSUE THREAD

**Issue by raylapse** [xbmc/xbmc#24810]
In my home network, I hosted a SMB share with some BDMV folder based movies.
For some reason, I don't what to include the BDMV folders directly into KODI library.
Instead of, I want to use .strm file to point to the BDMV folder, and then KODI popup the menu, or directly play the main stream.

I succesfully create .strm files for all my movies, include .mp4, .mkv, and even iso file. (with SMB:// protocol)
But I failed with BDMV folder.

I tried bluray://.../BDMV/ or udf://.../BDMV/, none of them works, the latter even cause KODI dump.

Can you give me a suggestion how to achieve this? Does KODI supports nested protocol like bluray://SMB://?
or something else should I do?

**Comment by chewitt** [comment]
> Can you give me a suggestion how to achieve this?

Please (re)post the question in our support forum, where we provide support. This is a bug tracker :)
