### ISSUE TITLE
[Kodi 21.0 "Omega" RC1]  bluetooth remote control does not work on android tv 11

### ISSUE THREAD

**Issue by Merzavetss** [xbmc/xbmc#24817]
### Describe the bug

I installed Kodi 21.0 "Omega" RC1 on a TV with Android TV 11 and my bluetooth remote does not work

## Expected Behavior

My TV remote should work in KODI. All buttons should work - right, left, down, up, select, back

## Actual Behavior

The remote control doesn't work. The up, down, right, left, select, and back buttons do not work. I can't control KODI

## Possible Fix

Take the settings for my remote control from the nightly build of KODI 21 beta 2: kodi-20240208-EA913DAE-master-armeabi-v7a.apk

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/14528739/kodi.log)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

1. The remote control is detected and works fine when installing the nightly build of kodi-20240208-EA913DAE-master-armeabi-v7a.apk
The debuglog from kodi-20240208-EA913DAE-master-armeabi-v7a.apk can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/14528763/kodi.log)
2. If I install android tv 9 firmware on the TV instead of android tv 11, then the my remote control works on Kodi 21.0 "Omega" RC1.

### Your Environment
Used Operating system:

 - [x] Android

 - Operating system version/name: Android TV 11
 - Kodi version: Kodi 21.0-RC1 (20.90.900)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by garbear** [comment]
@Merzavetss your remote is being interpreted as a joystick by Android. In the future this will "just work", but for now you have to map the remote in the controller configuration utility: Settings -> System -> Input -> Configure attached controllers

**Comment by Merzavetss** [comment]
> @Merzavetss your remote is being interpreted as a joystick by Android. In the future this will "just work", but for now you have to map the remote in the controller configuration utility: Settings -> System -> Input -> Configure attached controllers

Thank you for hoping to use fresh KODI builds in the future! 
Which buttons on the KODI gamepad (A, B, X, Y) correspond to the SELECT and BACK buttons on the TV remote? Will the microphone on the remote control work?
