### ISSUE TITLE
Python `PermissionError` exception in most add-ons in Omega RC.1 on Xbox.

### ISSUE THREAD

**Issue by florence-robert** [xbmc/xbmc#24819]
### Describe the bug

After the launch of Kodi Omega RC.1 on Xbox it seems that users on both the Series S and Series X (and possibly other systems like the One S/X) have had a large number of their plugins break, including both official and 3rd party add-ons.

- Myself and dozens of other users have been reporting broken add-ons in the new release.
  - [post1](https://www.reddit.com/r/Addons4Kodi/comments/1b96umi/xbox_dependency_error/)
  - [post2](https://www.reddit.com/r/Addons4Kodi/comments/1b97l9s/kodi_xbox_no_addons_are_working/)
  - [post3](https://www.reddit.com/r/Addons4Kodi/comments/1b8ncok/comment/kttbwpi/?utm_source=reddit&utm_medium=web2x&context=3)
  - [post4](https://www.reddit.com/r/Addons4Kodi/comments/1b8rix9/kodi_had_a_update_on_xbox/)
  - [post5](https://www.reddit.com/r/Addons4Kodi/comments/1b97uff/help_please_explain_basic_1st_time_using_xbox/)
  - etc

Due to this it puts Kodi in a near-unusable state. Tracing the error is incredibly difficult on Xbox at the moment. There aren't any official means of navigating the filesystem to access the filesystem to get the Log file and both the official [Kodi Logfi
le Uploader](https://kodi.wiki/view/Addon:Kodi_Logfile_Uploader) add-on by the Kodi Team and the [Log Viewer for Kodi](https://kodi.wiki/view/Add-on:Log_Viewer_for_Kodi) have similar issues with throwing errors.

The `Log Viewer for Kodi` add on thankfully lets me view the log inline. It's a terrible experience but it led me to identify that the system is throwing `PermissionError`s for loads of the add-ons. Possibly for filesystem actions, maybe for other reasons.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

- Add-ons should continue to behave as usual, aside from breaking changes between Nexus and Omega that add-on developers haven't address. These would be expected failures.

## Actual Behavior

- Most add-ons are throwing `PermissionError` exceptions and failing.

## Possible Fix

- None as this would be a filesystem error, possibly in the Kodi build if I'm not mistaken.

### To Reproduce

1. Set up an Xbox One/Series S/X
2. Load up add-ons like the [Kodi Logfi
le Uploader](https://kodi.wiki/view/Addon:Kodi_Logfile_Uploader) 
3. ???
4. bug

### Debuglog

The debuglog can be found here:
I can't really access the debug log as mentioned above but it _more or less_ looks like this:

```
PermissionError: [Errno 13] Permission denied-
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

![20240307_192646](https://github.com/xbmc/xbmc/assets/87673558/69cff775-089e-42b4-b01e-899e8bd8bd68)
![20240307_192632](https://github.com/xbmc/xbmc/assets/87673558/5dba8cf8-aadb-43b8-bcd3-d88c11f180c5)
![20240307_192626](https://github.com/xbmc/xbmc/assets/87673558/1de0d01b-72a7-49a7-ad42-3d29135f9dfe)
![20240307_192621](https://github.com/xbmc/xbmc/assets/87673558/97fd7042-5d66-4544-878f-422c780ef1ca)
![20240307_192614](https://github.com/xbmc/xbmc/assets/87673558/aa616047-0241-402c-8b0e-a6c4d1443404)
![20240307_192603](https://github.com/xbmc/xbmc/assets/87673558/2fc61571-f24b-4d49-977f-09aacdd4d5ab)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name:
   Xbox Series X
 - Kodi version:
Kodi Omega RC.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by LucifersCircle** [comment]
Happening on my end too. If anyone needs the full logs I can pull them from my Xbox on a fresh install. Just let me know.

**Comment by fuzzard** [comment]
Definitely grab the logs. We have halted the deployment, but from what i gather to get back to 20.5 you'll need to reinstall.
Please get the logs first, otherwise we just wont update the xbox version at all if a fix cant be found

**Comment by florence-robert** [comment]
> but from what i gather to get back to 20.5 you'll need to reinstall.

I was initially under the impression that it may have been a caching issue which is what lead me to reinstall but it still pulls 21 rc.1

Ill see if I can get an application that has access to the fs on Xbox to pull the logs beyond the screenshots as soon as I can.

**Comment by fuzzard** [comment]
The halt has literally been done 2 minutes ago, so it may take some time to actually go into practice.

**Comment by LucifersCircle** [comment]
Okay, so I did a fresh install of kodi and installed the OpenWizard addon. I will add the log files here, please let me know if there is an issue with them and I will correct it ASAP!

[kodi.log](https://github.com/xbmc/xbmc/files/14532064/kodi.log)
[kodi.old.log](https://github.com/xbmc/xbmc/files/14532065/kodi.old.log)

**Comment by fuzzard** [comment]
Cheers, will have to wait until a windows dev can look into it

**Comment by it5c0z1mG** [comment]
Same issue here with permission errors on addons, fresh install doesnt help either, xbox one (also tested on xbox one x and xbox series s) after the omega update 8/3/2024. Here are the log files i managed to get off the 'one' after a fresh install. Hope this helps. 

[kodi.log](https://github.com/xbmc/xbmc/files/14532543/kodi.log)

[kodi.old.log](https://github.com/xbmc/xbmc/files/14532544/kodi.old.log)

**Comment by thexai** [comment]
I'm doing first preliminary tests and no much luck for now (to reproduce the problem). Installed on Xbox Series S (developer mode) and installed Kodi Logfile Uploader add-on and all seems normal.

Log uploaded here:
https://paste.kodi.tv/dopugakako

Also installed .msix (UWP) installer on Windows 11 23H2 (where traditionally was possible reproduce Python permissions issues) and all is working fine. Created movie library and scanning NTFS sources using Python scrapper add-on... all is working

Please note that Python is not my area. Maybe others can understand better, for example this error (from log posted by @it5c0z1mG ):

```
2024-03-08 02:21:45.798 T:908     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'kodi_six'
                                                   Traceback (most recent call last):
                                                     File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.jellyfin\service.py", line 8, in <module>
                                                       from kodi_six import xbmc
                                                   ModuleNotFoundError: No module named 'kodi_six'
                                                   -->End of Python script error report<--
                                                   
2024-03-08 02:21:46.760 T:1432    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'PermissionError'>
                                                   Error Contents: [Errno 13] Permission denied: 'S:\\Program Files\\WindowsApps\\XBMCFoundation.Kodi_20.90.900.70_x64__4n2hpmxwrvr6p\\system\\python\\Lib\\urllib\\__init__.py'
                                                   Traceback (most recent call last):
                                                     File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.logviewer\service.py", line 3, in <module>
                                                       from resources.lib.service import run
                                                     File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.logviewer\resources\lib\service.py", line 10, in <module>
                                                       from resources.lib.httpserver import ThreadedHTTPServer, ServerHandler
                                                     File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.logviewer\resources\lib\httpserver.py", line 13, in <module>
                                                       import urllib.parse as urlparse
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 774, in exec_module
                                                     File "<frozen importlib._bootstrap_external>", line 910, in get_code
                                                     File "<frozen importlib._bootstrap_external>", line 967, in get_data
                                                   PermissionError: [Errno 13] Permission denied: 'S:\\Program Files\\WindowsApps\\XBMCFoundation.Kodi_20.90.900.70_x64__4n2hpmxwrvr6p\\system\\python\\Lib\\urllib\\__init__.py'
                                                   -->End of Python script error report<--
```


But to start it would be better to obtain error logs from the "official" add-ons (it should not be assumed that "plugin.video.jellyfin" works correctly in v21 RC1)

I will need more information to reproduce the problem since I think there are comments that Kodi Log Uploader does not work and it works for me on both Xbox Series S and Windows 11 23H2

**Comment by thexai** [comment]
Ping @matthuisman for ideas...

**Comment by thexai** [comment]
One of our CMake experts is @fuzzard 🙂

**Comment by matthuisman** [comment]
Is this is the same issue as on Kodi 19.3
There was an empty init.py I believe. and uwp gives empty files dumb
permissions

**Comment by thexai** [comment]
Confirmed 100%

![rar](https://github.com/xbmc/xbmc/assets/58434170/76aae1d3-7873-487c-be89-50d5e401d04b)

**Comment by it5c0z1mG** [comment]
I tried thos last night, adding " # This directory is a Python package. "
To the 2 empty init files and error still exists,

Can confirm log file uploader, embuary info and 1 other from the official repo i tried reproduced the same issue.

Jellyfin for kodi and jellycon from the unofficial jellyfin for kodi repo produces same issue.

Im not near that xbox atm to pull a new log file although im with and xbox one x with the kodi omega version and jellyfin for kodi addon working perfectly, 

if a log file for that would help in anyway?


I also have a xbox dev mode account, if you can point me to where i would get the kodi install file for dev mode id be happy to see if i can reproduce in dev mode and send a logfile too?

**Comment by it5c0z1mG** [comment]
I copied out the init files to my server, edited the files then copied them back, before i copied them back i verifed the file size changed, but yes you could be right, i have no way to verify if the overwrite was actually successful.

Okay i can try that too, any slyguy addons specifically youd recommend to test with?

**Comment by matthuisman** [comment]
https://www.matthuisman.nz/2018/05/kodi-widevine-support.html scroll down to video tester add-on. Give that a try. The widevine option won't work on Xbox but the others should

**Comment by it5c0z1mG** [comment]
@matthuisman okay, youll have to bare with me on that one as i had a copy of retail nexus app stored on a seperate usb drive and have reverted back from the broken update with it, (finally my ocd offsite xbox app backup paid off🤣)


Let me work on it and ill get back to you

**Comment by matthuisman** [comment]
99.5% is the same issue as last time https://forum.kodi.tv/showthread.php?tid=365157&pid=3067676#pid3067676

Kodi guys should be able to get it sorted :)

**Comment by it5c0z1mG** [comment]
Again, no idea if this helps either but the working nexus retail 20.05 on xbox one x, with jellyfin addon and logfile uploader addon

Heres the log
[kodi.log](https://github.com/xbmc/xbmc/files/14542833/kodi.log)
[kodi.old.log](https://github.com/xbmc/xbmc/files/14542835/kodi.old.log)
s for that too

**Comment by matthuisman** [comment]
i can only really see this change https://github.com/xbmc/xbmc/commit/6508c4cb7292cdeb5d04251a9a5c9c6a82035e63#diff-1edecd145ffb04cf00d5f0ff2e6a5959e5ced64a9b1be0ec0d28b311feacd68a that changes the windows store cmake in omega

Looks like it switched to creating a custom cmake file just for that fix and then telling cmake to use that.

**Comment by it5c0z1mG** [comment]
I will post here as i think the fix has caused another issue, i have posted a new report but have no idea what im doing

New issue: the movies library does not import properly and shows movies as empty. Tv shows work fine.

Same setup with jellyfin for kodi addon as remote library (read above for previous logs), on xbox retail mode.

Hope you can work this out or revert the xbox release again as nexus was working fine and omega seems to be a constant issue.


[kodi.log](https://github.com/xbmc/xbmc/files/14658042/kodi.log)
[kodi.old.log](https://github.com/xbmc/xbmc/files/14658043/kodi.old.log)

Thanks again.

**Comment by matthuisman** [comment]
that is unreleated.
Maybe jellyfin doesnt support Omegas new DB schema etc.

I suggest you enable DEBUG logging and then create a new log showing the issue.
Then raise a ticket with Jellyfin addon developer

**Comment by it5c0z1mG** [comment]
I can do that, how would i enable a debug log?

Sorry i have no idea what im doing i just want my xbox to stop autoupdating and ruining my movies🤣
