### ISSUE TITLE
[ubuntu-jammy] Missing latest stable builds

### ISSUE THREAD

**Issue by alexz-kh** [xbmc/xbmc#24826]
## Bug report
Latest Ubuntu official repo 
https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa?field.series_filter=jammy
missing latest stable release, aka  [20.5-Nexus](https://github.com/xbmc/xbmc/releases/tag/20.5-Nexus)

### Describe the bug
Here is a clear and concise description of what the problem is:
```
apt-cache policy kodi
kodi:
  Installed: 6:20.2+git20230630.0528-5f418d0b13-0~jammy
  Candidate: 6:20.2+git20230630.0528-5f418d0b13-0~jammy
  Version table:
 *** 6:20.2+git20230630.0528-5f418d0b13-0~jammy 500
        500 https://ppa.launchpadcontent.net/team-xbmc/ppa/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     2:19.4+dfsg1-2 500
        500 https://cz.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
```

## Expected Behavior
Kodi version of  20.5 supposed to be released, since its stable-upgrade branch.

## Actual Behavior
Kodi version of 20.2+git20230630.0528-5f418d0b13-0~jammy is latest available in repo.

Used Operating system:

 - Linux\ubuntu22

**Comment by alexz-kh** [comment]
ping: @wsnipex
(based on ppa owner info)

**Comment by sarbes** [comment]
The PPA is not supported anymore.

**Comment by alexz-kh** [comment]
@sarbes any other source for compiled .deb pkgs?
or manual for local .deb  builds from sources?
