### ISSUE TITLE
Selecting a PVR channel from the Recently Watched list changes the PVR channel group 

### ISSUE THREAD

**Issue by newkind** [xbmc/xbmc#24825]
### Describe the bug

There is a bug that seems to always reset the PVR group to the default **ALL** after you play a channel using the "Recently Watched" list. This behavior can be seen in the at least .1 releases from the Nexus branch.

## Expected Behavior

Selecting a PVR channel from the "Recently Watched" doesn't reset/change the channel group set previously in the PVR section/list.

## Actual Behavior

Selecting a PVR channel from the "Recently Watched" list always changes the channel group to **ALL** when you enter the full list of PVR channels.

### To Reproduce

1. Change the channel group in the PVR to be anything else than **ALL**
2. Play any PVR channel
3. Stop playing channel and go back to the main screen with "Recently Watched" channels visible
4. Play the same channel again from the "Recently Watched" list
5. Enter back to the PVR section (with all channels listed) - the group will be reverted to the default **ALL**

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.5 (Nexus), CoreElec 20.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Have you tried v21 RC1? There are chances that this is fixed already.

**Comment by newkind** [comment]
@ksooo Ok, looks like its working as intended in the v21 RC1 - at least on MacOS. Sorry for the confusion :)
