### ISSUE TITLE
[Bug] The music container displays as a files container

### ISSUE THREAD

**Issue by matke-84** [xbmc/xbmc#24831]
I noticed that when I go to media settings > library tab > manage sources > music folder, kodi shows this folder (container) as files. Shouldn't this be a songs/artists/albums container? This causes problems when I want to set a certain view in the skin to be only for music. Elsewhere it is ok, except in this folder. Can this be changed or does it have to be like this?
![unnamed2](https://github.com/xbmc/xbmc/assets/74268331/61b28278-eddc-4c33-baf2-fce14d1785eb)
![unnamed](https://github.com/xbmc/xbmc/assets/74268331/713f1b6f-7e77-40fe-a595-b2eb099a675c)

**Comment by Hitcher** [comment]
That's for adding sources so it's a file browser.

**Comment by matke-84** [comment]
@Hitcher 
Yes, but interestingly, this is not the case with the Video folder. Everything is right there. If I insert movies, it recognizes it as a movie container, tv show as a tv show container...

**Comment by Hitcher** [comment]
But the container is still 'files' for the video source settings.

**Comment by matke-84** [comment]
No it's not.
![movies](https://github.com/xbmc/xbmc/assets/74268331/b60a7aee-0ab2-4525-82ce-996f9308efbd)
![tvshows](https://github.com/xbmc/xbmc/assets/74268331/f463e78e-5867-4a45-b530-04f7303d80ca)
It would be logical for it to do the same with the music folder.

**Comment by Hitcher** [comment]
Go back a level and it's files.

**Comment by Hitcher** [comment]
So you're drilling down into the sources and the albums folder is files in here correct?

**Comment by matke-84** [comment]
@Hitcher 
We obviously don't understand each other. it's a files container, I'm not talking about that. When you enter that folder (Video... or Music...), you have button Add video... or Add music... 
When you click to add movies, say, a folder with your movies, that container becomes a movie container.
When you do the same in the Music folder, that is, you add your music folder, it is not, for example, a songs container, it is a files container.

**Comment by the-black-eagle** [comment]
Music works in a completely different way to video.  It is impossible for Kodi to display albums for instance, without having read the tags first.  Although the files container _can_ read the tags, this is not the same as assembling an album from them as tracks from one album can be in multiple directories.  Clearly, a file container cannot display this correctly.

Its not a bug, it's by design.

**Comment by Hitcher** [comment]
> This causes problems when I want to set a certain view in the skin to be only for music.

Just go to Music from the home screen and then set the view type you want to use.

**Comment by matke-84** [comment]
I thought it works differently but ok. Thanks.
