### ISSUE TITLE
21.0-ALPHA1 GPU is being Crashed 

### ISSUE THREAD

**Issue by MasterCATZ** [xbmc/xbmc#24833]
### Describe the bug
Here is a clear and concise description of what the problem is:
Playing back video files with either software or hardware acceleration the kodi screen will just freeze and my desktop goes black on other display , GPU is crashed I have to ssh into it via phone and reboot 
OpenGL Information
    GL_VENDOR:     AMD
    GL_RENDERER:   AMD Radeon RX 6800 XT (radeonsi, navi21, LLVM 15.0.7, DRM 3.52, 6.4.0-060400-generic)
    GL_VERSION:    4.6 (Compatibility Profile) Mesa 24.1~git2403090600.3b05eb~oibaf~j (git-3b05eba 2024-03-09 jammy-oi

## Expected Behavior
not to crash my entire desktop 

### To Reproduce

1. unsure it is random , it can be caused by clicking on things during playing back or the video ending 
2. subtitles have also been flickering for quite sometime now since kodi 19 so I have been having to switch between software and hardware acceleration a lot  , it has been happening to a lot of anime lately the current one is H.264 (High 4:4:4 Profile)
this particular video file I have been trying to watch has crashed GPU 5 times but every time I re-watch it gets further through it  [Harunatsu] Jitsu wa Watashi wa [BD 720p-AAC]/[Harunatsu] Jitsu wa Watashi wa - 01_v2 [BD 720p-AAC][FF529643].mkv
this particular video if I resume watching from any point its all green blocks I have to start from beginning then skip to before the section I am after 

### Debuglog

The kodi debuglog can be found here: https://paste.kodi.tv/hicuzafeya.kodi
and dmesg log here : https://paste.kodi.tv/voteduzulu.kodi + https://paste.kodi.tv/nificivayi.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

playing back video 

### Your Environment
Used Operating system:

 - [ ] Linux Ubuntu 22.04.4 LTS 6.4.0-060400-generic
 
 - Operating system version/name:
 - Kodi version:
21.0-ALPHA1 (20.90.101) Git:20230401-847a347839

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
This is most likely a bug in the DRM system (or related to it): https://gitlab.freedesktop.org/drm/amd/-/issues/2496.

**Comment by MasterCATZ** [comment]
not using Xwayland
AMD_DEBUG=dcc is set
