### ISSUE TITLE
Black screen with video playback by using inputstream.adaptive with LineageOS 17.1 (Kodi 21RC1)

### ISSUE THREAD

**Issue by werimail** [xbmc/xbmc#24844]
### Describe the bug
Here is a clear and concise description of what the problem is:
I'am using Kodi 21 RC1 with LineageOS running on Raspberry Pi 3 with Android 10 (API level 29). When I Start using Addons the widevine encryption the Inputstream Adaptive only plays the sound but no picture.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Addons which use widevine also output a picture in addition to the sound

## Actual Behavior

When I Start using Addons the widevine encryption the Inputstream Adaptive on Kodi 21RC1 and LineegeOS 17.1 only plays the sound but no picture.

## Possible Fix

A possible theory of the cause is that getCodecCount not work anymore, because has been deprecated on API 21.
see also https://github.com/xbmc/xbmc/pull/21421

### To Reproduce

1. Start Kodi-Addon (DAZN, Tvnow, ...) for encrypted videos via inputstream adaptive plugin
2.  Start playing stream

### Debuglog

The debuglog can be found here:
[kodi_input_LOS171_debug.log](https://github.com/xbmc/xbmc/files/14588733/kodi_input_LOS171_debug.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

unavailable

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

- Operating system version/name: LineageOS 17.1 based on Android for Raspberry Pi 3

- Kodi version: 21RC1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by werimail** [comment]
Hello @CastagnaIT  @joseluismarti 
I already had the problem in an older Kodi version as described here: https://github.com/xbmc/xbmc/issues/20639. With the fixes (https://github.com/xbmc/xbmc/pull/21421) it has worked since then. However, when installing the current Kodi version (21RC1) on an older environment (LineageOS 17.1), the problem occurs again for me.

Greetings Weri

**Comment by werimail** [comment]
> Seems that the device is not returning any codec in `getCodecInfos()`, as several `DVDVideoCodecAndroidMediaCodec::Open Testing codec...` messages should appear in the log.
> 
> There has probably been an exception in a previous call, probably widevine, use `adb logcat` to display the system messages to see if it gives us any clues
> 
> To make sure that MediaCodec is working properly on this device, play a video locally and check that the above log messages are displayed.

Thanks for your tips @joseluismarti Could it possibly be because I don't have GAPPS: https://opengapps.org/?arch=arm&api=10.0&variant=pico installed within my LineageOS environment? I use the “free” version Aurora-Store.

Greetings Weri

**Comment by werimail** [comment]
hi @joseluismarti , @CastagnaIT  I have now created a logcat. I hope that it becomes clear where the error lies.
[logcat_lineage_171.txt](https://github.com/xbmc/xbmc/files/14612488/logcat_lineage_171.txt)

Greetings Weri

**Comment by joseluismarti** [comment]
Hi,  in this logs the string `CDVDVideoCodecAndroidMediaCodec::Open` does not appear. The logs from the start of Kodi until this call and after are of interest.

**Comment by joseluismarti** [comment]
Try this [build](https://drive.google.com/file/d/1snndoxEorCEQwcoHJD05hFeG9RzDwMr8/view?usp=sharing), I've caught possible exceptions and added some debug message. Post a comment only with logs containing the string `CDVDVideoCodecAndroidMediaCodec` .

Note that installing this apk will cause you to lose your current Kodi configuration.

**Comment by werimail** [comment]
> Try this [build](https://drive.google.com/file/d/1snndoxEorCEQwcoHJD05hFeG9RzDwMr8/view?usp=sharing), I've caught possible exceptions and added some debug message. Post a comment only with logs containing the string `CDVDVideoCodecAndroidMediaCodec` .
> 
> Note that installing this apk will cause you to lose your current Kodi configuration.

Ok @joseluismarti her it is:
[lineage_171_debug.txt](https://github.com/xbmc/xbmc/files/14615788/lineage_171_debug.txt)

**Comment by joseluismarti** [comment]
Another [test](https://drive.google.com/file/d/19UXmPoZjfMrWzvpX9glj3wOMucUYqQBo/view?usp=sharing), ignore the result of DecoderFilterManager...

**Comment by werimail** [comment]
> Another [test](https://drive.google.com/file/d/19UXmPoZjfMrWzvpX9glj3wOMucUYqQBo/view?usp=sharing), ignore the result of DecoderFilterManager...

Great job @joseluismarti !!! With the new test version and Lineage 17.1 with the Rpi3 the output of the streams now also works. Attached is the kodi.log.
[kodi_lineage17_debug2.log](https://github.com/xbmc/xbmc/files/14616787/kodi_lineage17_debug2.log)

Greetings Weri

**Comment by joseluismarti** [comment]
Kodi uses a configuration file (`decoderfilter.xml`) to control which decoders should be used to play and which should not by passing the video hints.

https://github.com/xbmc/xbmc/blob/ac329371f89c66193de4174be4df095af3809de2/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp#L771-L772

It seems that all decoders that are available on this device (`OMX.google.*`) are disabled for this content.

Manually activate a decoder (`OMX.google.h264.decoder`) by editing the file `[userdata]/decoderfilter.xml`, restart kodi and check if the modified configuration has taken effect.

**Comment by werimail** [comment]
> Manually activate a decoder (`OMX.google.h264.decoder`) by editing the file `[userdata]/decoderfilter.xml`, restart kodi and check if the modified configuration has taken effect.

Ah ok @joseluismarti  so I always have to manually adjust the decoder.xml on my Raspberry Pi 3 to make it work?! 
Greetings Weri

**Comment by CastagnaIT** [comment]
i think should exists a "fallback list" in the decoderfilter.xml instead to blacklist directly possible valid decoders like OMX.google,
would probably also be useful in case of not found decoder, if possible print to the log a short instruction for the decoderfilter.xml file, to address users of a possible workaround

**Comment by CastagnaIT** [comment]
@werimail there is a fix pr #25862
idk if this test build is compatible with your system:
https://jenkins.kodi.tv/job/android-arm-docker/8262/artifact/kodi-20241021-6dd8436a-PR25862-armeabi-v7a.apk

the fix add a new kodi setting under
Settings->Player->Video->Use Decoder filter

you can switch to false to disable codec filters, then play the video

**Comment by werimail** [comment]
Hi @CastagnaIT Thanks for this change. Unfortunately, I don't have access to the test build using the address mentioned (lack of authorization?). Is there a way to make this available elsewhere?

Greetings Weri
