### ISSUE TITLE
Omega beta 3 - pvr.mediaportal.tvserver

### ISSUE THREAD

**Issue by MarcoViti** [xbmc/xbmc#24869]
Let me start by saying that I didn't have any problems with beta 2. Omega beta 3 gives me problems with viewing the TV.
Apparently everything works, I have the list of channels, the icons and the EPG, I can easily scroll through the entire list of my channels... but when I select one the two wheels in the center of the screen start to turn and the system remains waiting for a few seconds and then stops, as if I had pressed stop
In short, the channel display does not start.
Windows 11 x64 updated to the latest version.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/konucegupo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 pro
 - Kodi version:Omega 21 beta 3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
The interesting part of the log is probably this:
```
2024-03-03 16:43:51.084 T:3612     info <general>: ffmpeg[0x2ab283aeba0]: Input #0, mpegts, from 'pvr://channels/tv/Tutti%20i%20canali@-1/0@pvr.mediaportal.tvserver_51.pvr':
2024-03-03 16:43:51.084 T:3612     info <general>: ffmpeg[0x2ab283aeba0]:   Duration: N/A, bitrate: N/A
2024-03-03 16:43:51.084 T:3612     info <general>: ffmpeg[0x2ab283aeba0]:   Program 137 
2024-03-03 16:43:51.084 T:3612     info <general>: ffmpeg[0x2ab283aeba0]:   Stream #0:0[0x30]: Video: h264 ([27][0][0][0] / 0x001B), none, 90k tbn
2024-03-03 16:43:51.085 T:3612     info <general>: ffmpeg[0x2ab283aeba0]:   Stream #0:1[0x40](ita): Audio: ac3 ([6][0][0][0] / 0x0006), 0 channels
2024-03-03 16:43:51.085 T:3612     info <general>: ffmpeg[0x2ab283aeba0]:   Stream #0:2[0x41](oth): Audio: mp3 ([3][0][0][0] / 0x0003), 0 channels
2024-03-03 16:43:51.085 T:3612     info <general>: ffmpeg[0x2ab283aeba0]:   Stream #0:3[0x42](eng): Audio: mp3 ([3][0][0][0] / 0x0003), 0 channels
2024-03-03 16:43:51.085 T:3612     info <general>: ffmpeg[0x2ab283aeba0]:   Stream #0:4[0x6d](ita,ita,eng): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
2024-03-03 16:43:51.085 T:3612    debug <general>: CDVDDemuxFFmpeg::AddStream ID: 0
2024-03-03 16:43:51.085 T:3612    debug <general>: CDVDDemuxFFmpeg::AddStream ID: 1
2024-03-03 16:43:51.085 T:3612    debug <general>: CDVDDemuxFFmpeg::AddStream ID: 2
2024-03-03 16:43:51.085 T:3612    debug <general>: CDVDDemuxFFmpeg::AddStream ID: 3
2024-03-03 16:43:51.085 T:3612    debug <general>: CDVDDemuxFFmpeg::AddStream ID: 4
2024-03-03 16:43:51.085 T:3612     info <general>: Opening stream: 0 source: 256
2024-03-03 16:43:51.085 T:3612    error <general>: CVideoPlayerVideo::OpenStream: Codec id 27 require extradata.
2024-03-03 16:43:51.085 T:3612  warning <general>: CVideoPlayer::OpenStream - Unsupported stream 0. Stream disabled.
```
The `Codec id 27 require extradata` error originates from here, not sure why `extradata` would be be missing:

https://github.com/xbmc/xbmc/blob/e88b3190218daaaa8aaa8ac3a69f3cd895260d12/xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp#L108-L126

**Comment by MarcoViti** [comment]
Thanks for your help. So what should I do?...

**Comment by neo1973** [comment]
Hmm, I wonder if #24911 will fix this issue by any chance?

**Comment by MarcoViti** [comment]
If you explain to me what I have to do I'll try to test it

**Comment by MarcoViti** [comment]
If you explain to me what I have to do I'll try to test it

**Comment by neo1973** [comment]
> If you explain to me what I have to do I'll try to test it

Thanks for the offer :slightly_smiling_face: 

You can try this test build that contains #24911:  https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240329-7b232a41-PR24911-merge-x64.exe

**Comment by MarcoViti** [comment]
No unfortunately this build does not solve the problem with add-on Mediaportal and TV viewing.While waiting for a solution for the Mediaportal add-on I also tried to test the "Argus TV" component and also for this add-on it is not possible to see the TV, so the problem does not only occur with the Mediaportal add-on

**Comment by JCalvi** [comment]
I have exactly the same issue. On selecting a channel to view I get:
Spinning circle, black screen, spinning circle again then back to Kodi, no errors, no TV played, no audio.

V21 is unusable while 20.5 works perfectly.
The PVR plugin remains v20.3.0 in both cases, same settings.


V21 has these items in the debug logs while V20.5 does not.

```
2024-04-09 09:38:15.024 T:2660     info <general>: AddOnLog: pvr.mediaportal.tvserver: Kodi requested 32768 bytes, but the TSReader got only 11656 bytes in 2 seconds
2024-04-09 09:33:58.754 T:3328     info <general>: AddOnLog: pvr.mediaportal.tvserver: Kodi requested 32768 bytes, but the TSReader got only 0 bytes in 2 seconds
```

Full debug log of V21: [https://paste.kodi.tv/igeqavodoj.kodi](url)

Full debug log of V20.5: [https://paste.kodi.tv/iviyatavop.kodi](url)

Further information - I use TSreader setting with RTSP off. With RTSP on, the first channel starts playing, but then on channel change it buffers and then crashes. Identical settings and plugin on all prior Kodi versions 20.5 and less work without any issue. No other changes made other than updating to Omega 21 release.

**Comment by phunkyfish** [comment]
We’ll need someone to bisect this to find the problem commit. Which means someone who can both build kodi on windows and run the media portal addon.

having not used media portal ever before, can a test feed be provided?

**Comment by MarcoViti** [comment]
Hello everyone. I'm willing to do all the tests needed. Unfortunately, I'm not a programmer and I can't do more than that.

**Comment by MarcoViti** [comment]
As I said, I'm not a programmer. But if you explain to me what to do, I think I can help. I admit I'm a geek.. :-)

**Comment by phunkyfish** [comment]
Let’s solve for the addon not building correctly for omega first. Once we have that and if there is still a problem we try the bisecting path.

**Comment by WindyOldMan** [comment]
This is my first post on GitHub. I have recently retired from a 25 year long job as a software engineer working on a vast software project which was a control system for digital TV headends. I have used both Kodi and MediaPortal for many years, so I thought it was time I tried contributing :-)

I have been looking at the code for both Kodi and pvr.mediaportal.tvserver and I believe that I have got to the bottom of this issue. The underlying problem is this:

1) TSReader.Open() decides to use either a FileReader or MultiFileReader depending on whether it is reading a recorded TS file or a live TS buffer.
2) MultiFileReader is derived from FileReader. 
3) When MultiFileReader.OpenFile() is called the end result is that FileReader.OpenFile() is called. The code in this method was changed from Kodi Nexus to Kodi Omega such that the flags passed into kodi::vfs::CFile.Open() were changed from READ_CHUNKED to READ_NO_CACHE | READ_TRUNCATED | READ_BITRATE.
4) The code in kodi::vfs::CFile.Open() was also changed over the same period of time. When it used to be called with a flag of READ_CHUNKED it would avoid creating a CFileStreamBuffer and attaching it to the IFile object. However with the new flags and the local code changes it does end up creating a CFileStreamBuffer and attaching it to the IFile object.
5) It would appear that the dynamic live TS buffer file created by the MediaPortal backend is incompatible with CFileStreamBuffer which breaks the file based playback of live TV.

I have attached code changes that resolve this issue such that when kodi::vfs::CFile.Open() is called from MultiFileReader.OpenFile() it passes in a READ_NO_BUFFER flag to prevent the creation of the CFileStreamBuffer object. This fixes the issue with the playback of live TV in Kodi Omega from the MediaPortal backend. This fixes should allow Kodi Omega to work continue working with either v1 or v2 of the MediaPortal TvServer. I have it running with the former.

[#24869 solution diffs.txt](https://github.com/user-attachments/files/17377830/24869.solution.diffs.txt)

**Comment by basilgello** [comment]
@WindyOldMan This is what I call spirit of professionalism! Thanks for your service and for debugging this particular issue!

**Comment by WindyOldMan** [comment]
@phunkyfish - sorry although I've used git for many years we never used to use the PR mechanism. Any chance you could take my diffs and do the PRs for me? 

The Kodi change is a single file, unfortunately without that change the READ_NO_BUFFER flag will be filtered out between the addon and the core code. It stumped me for a while. I had changed the addon code and I could not understand why, when I debugged the core code the flag had disappeared.

**Comment by phunkyfish** [comment]
@WindyOldMan 

Here are the PRs:
- Kodi Change v22: https://github.com/xbmc/xbmc/pull/25834
- Kodi Change v21: https://github.com/xbmc/xbmc/pull/25835
- Mediaportal Change v22: https://github.com/kodi-pvr/pvr.mediaportal.tvserver/pull/215
- Mediaportal Change v21: https://github.com/kodi-pvr/pvr.mediaportal.tvserver/pull/216

Please check them and make sure it's correct.

**Comment by WindyOldMan** [comment]
@phunkyfish - I've checked the changes and they all match my local changes. Many thanks for doing the PRs for me. If I mange to do more then I will promise to learn how to do them myself...

I did wonder about the re-declaration and use of core flags in the FileReader.cpp file but I always try to limit any changes I make. Interestingly the code builds if you change line 76 of FileReader.cpp to use ADDON_ flags (then you could clear up the local defines).

**Comment by phunkyfish** [comment]
> @phunkyfish - I've checked the changes and they all match my local changes. Many thanks for doing the PRs for me. If I mange to do more then I will promise to learn how to do them myself...
>

no worries, if you need help at the time just let me know, happy to help show you how.

> I did wonder about the re-declaration and use of core flags in the FileReader.cpp file but I always try to limit any changes I make. Interestingly the code builds if you change line 76 of FileReader.cpp to use ADDON_ flags (then you could clear up the local defines).

Correct, but we are missing an enum for ADDON_READ_NO_BUFFER.  This needs to be added the addon API but we can only do this on master and only when we update and release all addons. I plan to do this the next time we have an addon API change where I’ll fix all those in the addon on the Piers branch.

**Comment by phunkyfish** [comment]
The kodi PRs have been merged. Nightlies from Oct 17th will contain the required changes.

test builds of the addon can be used with these nightlies for testing the fix.

Kodi 22 Piers: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.mediaportal.tvserver/detail/PR-215/2/artifacts
Kodi 21 Omega: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.mediaportal.tvserver/detail/PR-216/2/artifacts

**Comment by phunkyfish** [comment]
@MarcoViti @JCalvi, latest nightlies now contain the Kodi change. Can you both use a latest nightly (https://mirrors.kodi.tv/nightlies/) and the add-on testbuilds above to test the changes?

**Comment by JCalvi** [comment]
Tested and working fine here, thanks @WindyOldMan and @phunkyfish.

**Comment by phunkyfish** [comment]
Closing as all required fixes have been merged.

omega nightlies will need to be used until the next Omega release.
