### ISSUE TITLE
After todays update Kodi is not opening on Xbox Series X

### ISSUE THREAD

**Issue by avinashkanaujiya** [xbmc/xbmc#24870]
### Describe the bug
Here is a clear and concise description of what the problem is:

After todays update Kodi is not opening on Xbox Series X

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should open and work like usual

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.90.910.70

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
This is not a relevant bug as cause is not Kodi code related.

Se this:
https://forum.kodi.tv/showthread.php?tid=376559&pid=3187201#pid3187201
