### ISSUE TITLE
Texture maker error

### ISSUE THREAD

**Issue by FrostByteLXV** [xbmc/xbmc#24897]
### Describe the bug
Here is a clear and concise description of what the problem is:

Every time I open Kodi, I get a notification on the top right saying “Texture Maker error” with the subtext “Check the log for more information” right after skin loads.
This causes the widget not to immediately load the image from movie which produces a black background.
Error can pop up when doing other things like skin settings, etc.
This is a recent error as I've been using nightly builds and Arctic Fuse without error for some time now.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Widget should load backdrop of random movie instantly after skin is loaded.

## Actual Behavior

A black background is displayed for several seconds before background shows.

## Possible Fix

Per jurialmunkey who is the skin developer:
> The problem is the PIL module which is a dependency TextureMaker needs to run.

### To Reproduce

1. Start Kodi.  Error pops up automatically within seconds after skin loads.
2.
3.
As a test I tried removing Emby add-ons, but got the same error.

### Debuglog

The debuglog can be found here:

[https://paste.kodi.tv/olojejopul.kodi](url)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screenshot of error:
[https://i.ibb.co/W6M4LFW/texturemaker.jpg](url)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Other than the error popping up and a delay in images loading it doesn't seem to affect much else.

GitHub skin discussion with others getting same error message and a comment by skin developer:
[https://github.com/jurialmunkey/script.texturemaker/issues/2](url)

Reddit discussion of others (mostly iOS users) with same error:
[https://www.reddit.com/r/Addons4Kodi/comments/16e31l9/arctic_horizon_2_navigation/](url)

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Omega nightly kodi-20240318-40c09d0c-master-arm64-v8a.apk
 - nVidia Shield 2019 pro
 - Arctic Fuse skin v0.6.1
 - Texture Maker 0.2.10

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
> The problem is the PIL module which is a dependency TextureMaker needs to run.

I don't see where Kodi could do something wrong. This is the error:

```
2024-03-24 13:56:41.329 T:30167   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: unknown color specifier: '#ecial://skin/extras/icons/search.png'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.texturemaker/script.py", line 8, in <module>
                                                       Script().run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.texturemaker/resources/lib/script.py", line 139, in run
                                                       self.make_gradients(self.fg_color, self.bg_color, self.alpha)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.texturemaker/resources/lib/script.py", line 127, in make_gradients
                                                       self.gradient_h = make_gradient(fg_color, bg_color, alpha)
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.texturemaker/resources/lib/script.py", line 63, in make_gradient
                                                       fg_img = Image.new('RGBA', og_img.size, color=fg_color)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/mnt/expand/75cfed21-dccf-4374-97d6-e60b489908e1/user/0/org.xbmc.kodi/cache/apk/assets/addons/script.module.pil/lib/PIL/Image.py", line 2696, in new
                                                       color = ImageColor.getcolor(color, mode)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/mnt/expand/75cfed21-dccf-4374-97d6-e60b489908e1/user/0/org.xbmc.kodi/cache/apk/assets/addons/script.module.pil/lib/PIL/ImageColor.py", line 133, in getcolor
                                                       color, alpha = getrgb(color), 255
                                                                      ^^^^^^^^^^^^^
                                                     File "/mnt/expand/75cfed21-dccf-4374-97d6-e60b489908e1/user/0/org.xbmc.kodi/cache/apk/assets/addons/script.module.pil/lib/PIL/ImageColor.py", line 118, in getrgb
                                                       raise ValueError(f"unknown color specifier: {repr(color)}")
                                                   ValueError: unknown color specifier: '#ecial://skin/extras/icons/search.png'
                                                   -->End of Python script error report<--
```
As we can see the texturemaker's `self.make_gradients(self.fg_color, self.bg_color, self.alpha)` is called with `'#ecial://skin/extras/icons/search.png'` as `self.fg_color` which for sure isn't a color. It's hard for me to trace this back but my assumption is that it's coming from the skin or something.

**Comment by FrostByteLXV** [comment]
Thanks.  I'll ask jurialmunkey if he can comment.

**Comment by jurialmunkey** [comment]
I've been quoted out of context here. This a different issue than previous reported. 

The previous issue reported in the thread had a log showing PIL module missing on Apple TV. Unfortunately the original log is no longer there. 

This issue is completely different and I hadn't even had a chance to review the log first.
