### ISSUE TITLE
importwatchedstate ignored in advancedsettings.xml from Kodi 20.0

### ISSUE THREAD

**Issue by Vislike** [xbmc/xbmc#24909]
### Describe the bug

My collection consist of movies with local .nfo files. I use it shared between multiple devices, both: Windows PCs and Raspberry Pis with libreelec.

My media manger allows me to mark movies as watched, this puts \<playcount\>1\</playcount\> in the .nfo file.
Back in Kodi 19.5 if i wanted the scanner to pick them up as watched i had to add advancedsettings.xml with importwatchedstate set to true.

This is no longer needed in Kodi 20. The scanner will always pick them up as watched if playcount is 1.

The problem thou is now i want a new install on a Raspberry Pi to have everything as unwatched. But adding the advancedsettings.xml with importwatchedstate set to false won't work.

I have also confirmed this on one of my windows installs that had importwatchedstate set to true, by changing it to false. And then renaming a movie with \<playcount\>1\</playcount\> but it still gets picked up by the scanner as watched.

If i change playcount to 0 and rename the movie again, then it will be picked up by the scanner as unwatched.

I have zero explanation for this behavior, curiously i had a look at the source AdvancedSettings.cpp and VideoInfoScanner.cpp, and it looks like it should work. But without being able to add more traces to the log and recompile i can't figure out the problem.

## Expected Behavior

With importwatchedstate set to false in advancedsettings.xml i expect the movie to be added by the scanner as unwatched even with playcount set to 1.

## Actual Behavior

Movie is always added as watched regardless of importwatchedstate set to true or false.

## Possible Fix

Go back to Kodi 19.5 or not use the playcount in the .nfo.

### To Reproduce

1. Install Kodi 20.0+ (i have tested with 20.0, 20.5 and 21.0-RC2)
2. Setup a Movie source with Local Information Only
3. Add a Movie together with .nfo file with \<playcount\>1\</playcount\>
4. Update library in Kodi, expect it to be picked up by scanner as watched.
5. Create advancedsettings.xml in userdata folder with:
```
<advancedsettings version="1.0">
    <videolibrary>
        <importwatchedstate>false</importwatchedstate>
        <importresumepoint>false</importresumepoint>
    </videolibrary>
</advancedsettings>
```
6. Rename Movie so it will be picked up by scanner again.
7. Restart Kodi so it loads advancedsettings.xml
8. Update library again, and it still gets picked up as watched

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/zevonexuqe.kodi

## Additional context or screenshots (if appropriate)

I think this thread might describe the same problem:
https://forum.kodi.tv/showthread.php?tid=375066

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name: Windows 10, Windows 11, Libreelec
 - Kodi version: 20.0, 20.5, 21.0-rc2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Issue confirmed. 
Import data ignored in v19, but imported in v20 and v21

The only change I am aware of is the flipping of the default setting so userdata is not discarded by default...
https://github.com/xbmc/xbmc/pull/20842

I am wondering if that change is correct? I don't see the use of `{true}` anywhere else in that file.

**Comment by neo1973** [comment]
On first look it seems like it's this location where the play count is used unconditionally:

https://github.com/xbmc/xbmc/blob/122a3696a0b3d3144a0a151d283fe8a9e1f847d4/xbmc/video/VideoDatabase.cpp#L1054-L1058

This would have been introduced in #19367 commit https://github.com/xbmc/xbmc/commit/20c723a8841b162bdd9f2c449f32de12c536cc99. I'll try to make a PR to fix this tomorrow.

**Comment by KarellenX** [comment]
Thank you @neo1973
