### ISSUE TITLE
HW crashes with interlaced video

### ISSUE THREAD

**Issue by m2840** [xbmc/xbmc#24906]
### Describe the bug
Here is a clear and concise description of what the problem is:

With Hardware Acceleration (HW) Kodi crashes with interlaced videos.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. Play any interlaced video using HW
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 20.5
 - i7-4790K (Intel HD Graphics 4600)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by m2840** [comment]
Here is the debug log.
[kodi.log](https://github.com/xbmc/xbmc/files/14772363/kodi.log)

**Comment by m2840** [comment]
Interlaced content plays with software decoding, but fails to play with hardware decoding.

**Comment by thexai** [comment]
The log uploaded contains banned add-ons (https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons). Then no support  can be offered here. 

In any case, we do not use GitHub for technical support. I suggest you open a post in the forum (https://forum.kodi.tv/forumdisplay.php?fid=59) and upload a new debug log once these add-ons have been cleaned.

**Comment by m2840** [comment]
OK. Never mind. This was only for your information. Kodi works fine in Android, but it sucks in Windows. Numerous crashes, specially when exiting the app.

**Comment by thexai** [comment]
> Numerous crashes, specially when exiting the app.

Maybe clean install.............
