### ISSUE TITLE
Microstutter on Fire TV Stick 4K Max Gen2

### ISSUE THREAD

**Issue by puni2k** [xbmc/xbmc#24904]
### Describe the bug
i recently got a Fire TV Stick 4K Max Gen2 and video playback isn't really smooth on Kodi. Initially running 20.5 but also gave 21.0RC2 a try.
My main use-cases are the Youtube Plugin and Tvheaded, so i currently don't know if my issue also applies to locally stored video files.

It's most noticable on channels that have a newsticker running (i.e. German public broadcast service "tagesschau 24").
TV broadcasts here are 50Hz so that's where i observe this issue the most. Automatic Refresh Rate is enabled in Fire TV settings and Kodi (Always, Start/End, doesn't really make a difference). All refresh rates for the displays' native resolution are whitelisted in Kodi settings. Kodi UI is set to 50Hz, but other values don't seem to improve the situation.

Kodi OSD and TV report the correct refresh rates the whole time.

By chance i found a workaround which isn't the most practical though.
If playback is stuttery one can
- bring up the Settings menu
- "Select Resolution"
- select a different refresh rate
- switch back to target refresh rate
-> smooth playback

What also works is setting Kodi UI to a different refresh rate from the video and have "Adjust display refresh rate" set to always. Then, during playback, switch to Kodi UI and then back to fullscreen playback. After a few seconds playback will be smooth. But this is only applicable if UI and video refresh rates are different from each other, which with Youtube isn't a guarantee.

My Fire TV Stick 4K Max Gen1 which I normally use on another TV set works flawlessly.

## Expected Behavior
Smooth playback

## Actual Behavior
somehow stuttery playback

## Possible Fix
sorry, no idea

### To Reproduce
start stream

### Debuglog
https://paste.kodi.tv/yemocovawu
(incl. refresh rate switch workaround)

https://paste.kodi.tv/befecetubi
(Fire TV Stick 4K Max Gen1 for comparison

### Screenshots 
N/A

## Additional context or screenshots (if appropriate)
N/A

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Kodi version: 20.5,  21.0RC2

**Comment by puni2k** [comment]
Hi,
thanks for the response. I'm a bit baffled though, since i can't pinpoint which rule I might have ignored. 
I would appreciate it if you could give me a hint.

**Comment by sarbes** [comment]
We need debug logs, yours have debugging disabled.

**Comment by thexai** [comment]
> My Fire TV Stick 4K Max Gen1 which I normally use on another TV set works flawlessly.

If _same_ Kodi version works fine in Fire TV Stick 4K Max Gen1 but not in Gen2 I highly doubt this could be a "Kodi bug". Probably something incorrectly configured or not configured in Fire TV settings or Kodi settings, etc. Ultimately it could be Fire TV Gen2 "firmware bug".

I suggest you use the forums for support first: https://forum.kodi.tv/forumdisplay.php?fid=164

**Comment by puni2k** [comment]
> We need debug logs, yours have debugging disabled.

I thought i did, after all the Gen2 log contains debug messages.
Nevermind, another try, this time with restarting kodi after activating the debug setting
Gen2: https://paste.kodi.tv/didakupemi

I can't get the Gen1 stick to write debug messages to the log, however that seems to be a known problem
https://forum.kodi.tv/showthread.php?tid=371514

> > My Fire TV Stick 4K Max Gen1 which I normally use on another TV set works flawlessly.
> 
> If _same_ Kodi version works fine in Fire TV Stick 4K Max Gen1 but not in Gen2 I highly doubt this could be a "Kodi bug". Probably something incorrectly configured or not configured in Fire TV settings or Kodi settings, etc. Ultimately it could be Fire TV Gen2 "firmware bug".
> 
> I suggest you use the forums for support first: https://forum.kodi.tv/forumdisplay.php?fid=164

I already did though: https://forum.kodi.tv/showthread.php?tid=376746
I would gladly try any setting recommended to me. However I'd like to add that i also tried restoring the Gen2 stick with a backup from the Gen1 stick and the issue persisted. I won't rule out that there is a firmware issue but that's nothing I can investigate on my own. My hope was that there might be something obvious from the logs.
