### ISSUE TITLE
Unable to start video playback on LG TV

### ISSUE THREAD

**Issue by matusinkodoma** [xbmc/xbmc#24916]
### Describe the bug
Here is a clear and concise description of what the problem is:

It is not possible to run any video format, I run the file from the smb server, tested on both libreelec and windows version of Kodi and the file is played but on LG web os after running the video immediately crashes the Kodi application to the environment of the main screen of the TV and after re-enabling the application starts the application again, the application works smoothly, I have tried different nigthlies versions and stabble and the problem is always the same, I have tried any video format and video resolution but the problem is still the same, in the log I add only as an example the last attempt that I tried
Note: I use libreelec on another device which is also a smb server

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

after starting the video file, the video starts playing

## Actual Behavior

the video will not 
be played

### To Reproduce

1. start Kodi
2. select file location
3. play file

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/isakumusub.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [x] WebOS 

 - Operating system version/name: FW:05.40.20/WebOS:4.10.0
 - Kodi version:21.0-RC2 (it happens on any version)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sundermann** [comment]
Same issue as #24428. Video playback on that SoC is inherently broken and the reasons are unknown. There's already been an insane of investigating and debugging this particular issue. That being that, K5LP is a fairly low end SoC and likely won't run Kodi very well
