### ISSUE TITLE
Solution for the unreachable kodi official repository

### ISSUE THREAD

**Issue by t-baar** [xbmc/xbmc#24912]
Hi, I'm Thibault Baldetti from France, using GNU/Linux since 2004
I use a fresh compiled Gentoo Linux on a x86_64 system, to make a geek HTPC

I first installed the flatpak version of the latest Kodi v20.5 (Nexus), it installed flawlessly
But when I wanted to download addons via the official repository, i'm unable to list any addon, like a disconnected network
Sometimes, Kodi crashes!

I also tested the gentoo provided ebuild, same problem, so I've readen the crash log

> $ tail /home/gentoo/kodi_crashlog-20240329_043755.log 

                                                   
```
2024-03-29 04:37:51.929 T:45464   ERROR <general>: CFileCache::Open - <http://mirrors.kodi.tv/addons/matrix/addons.xml.gz?sha256> failed to open
2024-03-29 04:37:51.930 T:45464   ERROR <general>: CRepository: failed read 'http://mirrors.kodi.tv/addons/matrix/addons.xml.gz?sha256'
2024-03-29 04:37:51.930 T:45443   ERROR <general>: GetDirectory - Error getting addons://repos/
2024-03-29 04:37:51.930 T:45443   ERROR <general>: CGUIMediaWindow::GetDirectory(addons://repos/) failed


############### END LOG FILE ################

############ END Kodi CRASH LOG #############

```
**I've FOUND the solution, so, I'll share it to the friendly opensource community :)**

For the Flatpak package

Run the following command as root:

> $ sudo nano /var/lib/flatpak/app/tv.kodi.Kodi/x86_64/stable/8bb02c33d4ee5bfd4eb2aca728fef0d2d28e21583dd170681a809125c2b1ae2c/files/share/kodi/addons/repository.xbmc.org/addon.xml 

(Maybe the flatpak reference can differ, so it's basically 

> $ sudo nano /var/lib/flatpak/app/tv.kodi.Kodi/x86_64/stable/<Flatpak ref>/files/share/kodi/addons/repository.xbmc.org/addon.xml

)

Change these lines
```
<extension point="xbmc.addon.repository">
                <!-- Do not forget to bump add-on version when changing paths to force a repo refresh -->
                <dir>
                        <info>http://mirrors.kodi.tv/addons/nexus/addons.xml.gz</info>
                        <checksum verify="sha256">http://mirrors.kodi.tv/addons/nexus/addons.xml.gz?sha256</checksum>
                        <datadir>https://mirrors.kodi.tv/addons/nexus</datadir>
                        <artdir>http://mirrors.kodi.tv/addons/nexus</artdir>
                        <hashes>sha256</hashes>
                </dir>
        </extension>
```

To that:
```
<extension point="xbmc.addon.repository">
                <!-- Do not forget to bump add-on version when changing paths to force a repo refresh -->
                <dir>
                        <info>https://mirrors.kodi.tv/addons/nexus/addons.xml.gz</info>
                        <checksum verify="sha256">https://mirrors.kodi.tv/addons/nexus/addons.xml.gz?sha256</checksum>
                        <datadir>https://mirrors.kodi.tv/addons/nexus</datadir>
                        <artdir>https://mirrors.kodi.tv/addons/nexus</artdir>
                        <hashes>sha256</hashes>
                </dir>
        </extension>
```
 
It's the HTTPS protocol, not HTTP! so, the Kodi dev team, please correct your source code :)

And for the gentoo ebuild version, it's the same thing, but the file isn't at the same place

> $ sudo nano /usr/share/kodi/addons/repository.xbmc.org/addon.xml

Then change the HTTP protocol to HTTPS :)

Have a great day (Or night!) God blesses you!

Thibault Baldetti

**Comment by vpeter4** [comment]
Now it works again with http links.

**Comment by yol** [comment]
For posterity, there was an intermittent issue with the reachability of mirrors.kodi.tv on port 80. It has been fixed on our end.
