### ISSUE TITLE
Support for SRT subtitles in Windows-1251 encoding

### ISSUE THREAD

**Issue by Korb** [xbmc/xbmc#24914]
### Describe the bug
When playing a movie with external Russian-language subtitles saved in an srt file with Windows-1251 encoding, the text is displayed unreadable.

## Expected Behavior
Cyrillic text should be displayed correctly.

## Actual Behavior
See screenshots section.

### Screenshots 
![Screenshot_20240329_044503 copy](https://github.com/xbmc/xbmc/assets/3509797/4a2dd66a-2b69-45c7-adc1-3927c43ef79e)

## Additional context or screenshots (if appropriate)
![Untitled-1](https://github.com/xbmc/xbmc/assets/3509797/f862ef39-b8c2-4149-859e-45e67a8e81cc)

### Your Environment
Used Operating system:
 - [X] Android

 - Operating system version/name: 14
 - Kodi version: 20.5

**Comment by Korb** [comment]
> If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.

I say it.

**Comment by CastagnaIT** [comment]
have you tried set the right "Character set" on Kodi subtitle settings?

**Comment by Korb** [comment]
I assumed that the "Character set" setting should affect the encoding of subtitles.  But there is nothing on the list that looks like what is needed in this case.  The second half of it consists of the following options:

> ...
> Japanese (Shift-JIS)
> Korean
> South Europe (ISO)
> Thai (Windows)
> Turkish (ISO)
> Turkish (Windows)
> Vietnamese (Windows)
> Western Europe (ISO)
> Western Europe (Windows)

That is, as far as I can see, there is neither “russian language”, nor “cyrillic”, nor an explicit indication of the name of the encoding.

**Comment by scott967** [comment]
The subtitle character set "Cyrillic (windows)" is CP1251.  Cyrillic (ISO) is ISO 8859-5

**Comment by Korb** [comment]
@scott967, thank you. I could have guessed. I think this issue can be closed as erroneous. And perhaps think about a better implementation of automatic encoding detection. Or, as an option, implement the choice of encoding with a quick preview of the current subtitles. Or use [generally accepted encoding naming conventions](https://en.wikipedia.org/wiki/Character_encoding#Common_character_encodings).
