### ISSUE TITLE
21RC2 cannot see some files from FTP

### ISSUE THREAD

**Issue by mephitrpg** [xbmc/xbmc#24921]
### Describe the bug
Here is a clear and concise description of what the problem is:

I installed Kodi 21RC2 both on Windows and WebOS.
I kept default settings.
I addedd the location for TV Shows from my network hard drive via FTP (it's attached to the USB of the modem, that only provides FTP connection). It worked, and default scraper with Italian settings worked too.
Scraped data is visible, but files are not playable anymore form all folders but one, and counters in "InfoWall" viewtype are zero except for the payable folder. If I explore, I can navigate the folder structure, but files are missing. Last week everything worked, now it doesn't. I'm pretty sure I didn't change nothing. 
I tried to restart, clear and rebuild the library, remove and readd sources, but nothing worked.
The files are all visible and playable from File Manager.

### Debuglog

The debuglog can be found here:
[kodi - Copia (2).log](https://github.com/xbmc/xbmc/files/14813768/kodi.-.Copia.2.log)
[kodi - Copia.log](https://github.com/xbmc/xbmc/files/14813769/kodi.-.Copia.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![{8BA2979E-CA00-4047-8963-996CDA88352C}](https://github.com/xbmc/xbmc/assets/2466456/c916cd05-fb0b-430c-9c97-3ac5e6b43753)
![{7BF1326F-DA7A-4B80-BEAB-472F60C5EC11}](https://github.com/xbmc/xbmc/assets/2466456/37ca14e0-16a5-47eb-9c02-d4ffc5aec5d8)
![{4969BDB0-4BDD-456E-B331-FD9CE76331E7}](https://github.com/xbmc/xbmc/assets/2466456/b015b46d-4058-4f81-9be0-51148378fb97)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP
 - [x] WebOS

 - Operating system version/name: Windows 11 Home 23H2, WebOS 5.50.15
 - Kodi version: 21RC2 20.90.910

**Comment by CrystalP** [comment]
Github issues are for bugs, not support, please go to the forum first. If a bug is identified, then an issue here will be appropriate or this can be reopened.
That said, the problem may have something to do with permissions of the files / presence of authentication on the ftp server.
