### ISSUE TITLE
Kodi has no setting to play video in forced monochrome

### ISSUE THREAD

**Issue by simonsonjh** [xbmc/xbmc#24928]
### Describe the bug
Here is a clear and concise description of what the problem is:

Some video files play with a slight green tint, presumably because of the way it was encoded.  It would be helpful if Kodi had a setting to force monochrome playback in order to remove any color saturation.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

A setting to force monochrome video playback.

## Actual Behavior

No setting exists to force monochrome video playback.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by simonsonjh** [comment]
Video files with a green color tint are typically created with early video codecs.

**Comment by KarellenX** [comment]
Do other players, like VLC, also play with the green tint?

Can you provide a debuglog that captures the playback. Do you have a sample video file you can share?

This report sounds more like a feature request, so it will most likely be closed soon.

**Comment by neo1973** [comment]
This is a feature request, please take it to the forum.
