### ISSUE TITLE
Android 14: Creation of playercorefactory.xml inside /Android/Data folder to Use external video player is not possible anymore 

### ISSUE THREAD

**Issue by kdpkke** [xbmc/xbmc#24945]
### Describe the bug

In Android 14 (I tried this with a Galaxy Tab S9 with OneUI v5.1 and a Motorola Edge 40 pro), it became impossible without root permissions to create (or copy/paste) the playercorefactory.xml file inside the /Android/Data/kodi folder if I want to use an external player to watch videos. Permission to write on those folder is denied. I tried every single workaround existing on the internet, but nothing is working these days (I also tried running Shinzuku through ADB to grant the write permission on those folders, but it did not work out).

## Expected Behavior

Use external app to watch videos by creating the playercorefactory.xml file inside the /Android/data folder

## Actual Behavior

Permission denied when trying to create or copy/paste the file in the /Android/Data/ folder

## Possible Fix

To fix it, I suggest to give the user the possibility to select this file created inside another folder through the KODI GUI. I'm doing this to be able to cast the video on a smart TV, so meanwhile I would suggest to implement this feature onto the default video player.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.5 (I downloaded the one on the Play Store)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by SoulReaverFan** [comment]
Pretty sure you can already do it from the Kodi GUI file manager by adding a new source and selecting your external storage folder on the device and then add it as a new source. Now you should be able to copy the xml file to the correct location by copying it to the Profile Directory already available in the File Manager by tapping and holding on the xml file and selecting copy while having the Profile Directory already open on one side of the screen. That method should still work I think.

**Comment by kdpkke** [comment]
Thank you very much for your reply, it works! The wiki should be updated for this!
