### ISSUE TITLE
[Feature Request] API function to add/edit chapters in streams (or files)

### ISSUE THREAD

**Issue by Yavos** [xbmc/xbmc#24947]
### Describe the bug
Here is a clear and concise description of what the problem is:

More and more streaming services add things similar to chapters or actual chapters to their streaming services. (e.g. YouTube adds chapters by video description, other platforms have skip intro/outro buttons which indirectly refers to chapters)
So far it seems impossible to add chapters via Plugin API. To my understanding it will only load chapters if present in video/audio (container) file metadata.

This isn't really a bug, though and I wasn't sure how to submit this otherwise.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should be possible for Kodi plugins to add and/or edit chapters by some API function. The information is quite often there to be parsed.

## Actual Behavior

As written before, I haven't found any evidence that this is already possible through the plugin API.

## Possible Fix

Add a function, to add and/or edit chapters for streams (or media files).

### To Reproduce

Nothing to be done here, really. Except you know some way to do it with the current plugin API.

### Debuglog

The debuglog can be found here:

As this is a feature request, a debug log wouldn't help.

### Screenshots 
Here are some links or screenshots to help explain the problem:

A quick example would be https://www.youtube.com/watch?v=-K0Ne8otETY which contains many chapters for single tracks in a video containing the entire Stray OST in its video description. These are also shown by the YT player itself. Many other examples can be found on YT.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

[Screenshots from the mentioned YouTube Link above](https://imgur.com/a/5vImom0)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Nexus 20.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Please use the forum for feature requests, thanks.
We only use github as an issue tracker.

**Comment by Yavos** [comment]
Thanks for telling me the correct place to put this request.
