### ISSUE TITLE
Kodi is showing iOS simulators in the file browser where they don't exist

### ISSUE THREAD

**Issue by Stokestack** [xbmc/xbmc#24958]
### Describe the bug
Here is a clear and concise description of what the problem is:

I selected "Enter file section" and was perplexed to see several (but not all of my) iOS simulators listed as siblings of my user "Movies" directory. They do not reside there. They are also not shown in Finder as mounted volumes, or under /volumes at the command line.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I don't see nonexistent files (or other) in the file browser.

## Actual Behavior

I'm seeing some of my iOS simulators (from Apple development tools) in the file browser where they do not exist.

### To Reproduce

1. Launch Kodi on a Mac that has Apple dev tools (including iOS simulators) installed.
2. Select "Enter files section"

### Debuglog

The debuglog can be found here:
There was no error reported.
<img width="1440" alt="KodiFiles" src="https://github.com/xbmc/xbmc/assets/196304/2973588a-a228-476e-84fa-680ce17bceb7">

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screen shot attached.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 14.4.1 Sonoma (Apple Silicon)
 - Kodi version: 21.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
I assume you are the user on the forums that mentioned this. This isnt really something we can change as far as im aware. They are mounted in /Volumes. We dont filter volumes discovered, because how do we know its not a volume a user intended to mount/use?

If you wish to not see them, unmount them via "Disk Utility"

**Comment by Stokestack** [comment]
I am. Thanks for the reply. These aren't listed under /Volumes on my system. They are shown in Disk Utility, but that's all.

If you can give me a pointer to where these are enumerated, I can take a look at it.
