### ISSUE TITLE
Video playback crashes on NAS because the default SMB chunk size 128KB

### ISSUE THREAD

**Issue by Hill0517** [xbmc/xbmc#24961]
I have a NAS serving SMBv1 within local area network. Videos playback well on Kodi 20/Kodi 21 Alpha1(Jul. 2023).
When I upgrade to Kodi 21.0, it crashes often when I play some videos.
FTP and USB works well, so it's a SMB problem.
When I try to downscale the SMB chunk size to 64KB, it works.
So, I think it's better to restore the default value to 64KB, which is equal to Kodi20.

**Comment by feijoey** [comment]
A big percentage of my library stopped playing after less than a second after the upgrade to Kodi 21.0. I've spent so many hours troubleshooting the problem, and this simple change in my settings has completely fixed it! I hope everyone else who is having this problem sees your post too Hill0517.

**Comment by malvinas2** [comment]
SMB1 has long been deprecated and does not support block sizes > 64 kB.

**Comment by thexai** [comment]
As others commented SMBv1 is deprecated and no useful information has been provided in this issue to debug anything. Not even the platform used or the brand of NAS...
