### ISSUE TITLE
Long press select not working on LG C3 (webOS 23)

### ISSUE THREAD

**Issue by Noltari** [xbmc/xbmc#24962]
### Describe the bug
Here is a clear and concise description of what the problem is:

Long press select isn't working on my LG C3 48" but it works perfectly fine on my LG G1 65".

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Long press select should display the context menu (right click).

## Actual Behavior

Long press select just keeps opening subfolders and selecting the corresponding next thing on the UI.

## Possible Fix

N/A

### To Reproduce

1. Install webOS Kodi on a LG C3
2. Try to perform a long press selection anywhere.
3. Cry because it will subsequently open things :(

### Debuglog

The debuglog can be found here:

PENDING: I will attach a log later (probably later today).

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] webOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LG webOS 23
 - Kodi version: Kodi 21 Omega

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by quietvoid** [comment]
It works for me as long as I don't use the pointer.

**Comment by Noltari** [comment]
> It works for me as long as I don't use the pointer. Or maybe you need to use it, I don't remember. Try both.

I will try that and report back, thanks for the suggestion!

**Comment by sundermann** [comment]
Test build is going to become available in a couple of minutes [here](https://jenkins.kodi.tv/job/webos-docker/4002/). Please install, test and report back if it fixes the problem.

**Comment by Noltari** [comment]
> Test build is going to become available in a couple of minutes [here](https://jenkins.kodi.tv/job/webos-docker/4002/). Please install, test and report back if it fixes the problem.

Works like a charm, many thanks @sundermann!
