### ISSUE TITLE
"Play using" missing from the context menu for YouTube, Vimeo videos

### ISSUE THREAD

**Issue by Solarunit** [xbmc/xbmc#24976]
### Describe the bug
Here is a clear and concise description of what the problem is:

"Play using" option is missing from the context menu for YouTube, Vimeo videos, so you can't use external player to play them.
YouTube addon version: 7.0.5
Vimeo addon version: 6.0.1.
Kodi 21 flatpak

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

"Play using" option should be available for videos in YouTube/Vimeo addons

## Actual Behavior

"Play using" option is missing from the context menu for YouTube, Vimeo videos, so you can't use external player to play them.

## Possible Fix

Adding "Play using" option for all videos

### To Reproduce

1. Open context menu for any video in YouTube or Vimeo addon
2. see that "Play using" option no longer there

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

Kodi 20.5 (not flatpak) and YouTube addon 7.0.0.2. "Play using" is still there:

![kodi-1](https://github.com/xbmc/xbmc/assets/20891064/f52947e1-360b-4cc7-8270-2cdb28bba8c4)

and after pressing "Play using" I see 2 players  menu to choose from:

![kodi-2](https://github.com/xbmc/xbmc/assets/20891064/0d43235b-b376-4c34-880b-05b72243e480)

`playercorefactory.xml` that was used here:

```xml
<playercorefactory>
  <players>
    <player name="MPV" type="ExternalPlayer" audio="false" video="true">
      <filename>/usr/bin/mpv</filename>
      <args>--fs=yes "{1}"</args>
      <hidexbmc>false</hidexbmc>
    </player>
  </players>
  <rules action="prepend">
    <rule video="false" player="MPV"/>
  </rules>
</playercorefactory>
```

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Solus
 - Kodi version: 21 flatpak

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
As discussed here https://github.com/xbmc/xbmc/issues/24970, this never worked, so would be a feature request, which you please open in the forum. This is an issue tracker.
