### ISSUE TITLE
No HDR/DV Display support Apple TV 4K

### ISSUE THREAD

**Issue by Levent-Cetin** [xbmc/xbmc#24988]
### Describe the bug
Here is a clear and concise description of what the problem is:

On version 21.0.0 Display support for Apple TV 4K 128GB with tvOS 17.4 is not working.
This leads to no changing resolution and refresh rates during playback.
Under system information Display Support HDR is "None".
TV screen is LG C3 with DV/HDR10 support.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Display support for DV/HDR with variable refresh rate and variable resolution.

### To Reproduce

1. Sideloaded Kodi 21 Stable
2. Kodi 21-nightly-20240412
3. Kodi 20.5 Stable

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.0.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
It's not a bug, it's just not implemented.

From memory there is a feature request already on forums, but feel free to add your voice to that (or make a new request if there isn't one)
