### ISSUE TITLE
No sound in kodi 21

### ISSUE THREAD

**Issue by stemy2** [xbmc/xbmc#25006]
### Describe the bug
Here is a clear and concise description of what the problem is:

Since the upgrade to v.21, i'm unable to have any sound. In the sound parameters, i have only one choice: Default, Default Output Device (PIPEWIRE).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Sound playing normally.

## Actual Behavior

Everything is muted, videos have no sound and audio is locked at the timecode 0:00.

### To Reproduce

1. Upgrade to v.21

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/befenobaku

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The kodi package have been installed with flatpak.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: KDEneon 6.0.2
 - Kodi version: 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MyCookie** [comment]
I can confirm this bug. KDE Neon 6.0, Kodi installed using flatpak from system repo.

Downgrading to commit c66a791ac482c3b0c257188f2b3ccf796082176e0822192ec9132f9b78044dd0 resolves this issue for me.

**Comment by neo1973** [comment]
Indeed same problem as #25002. #25019 makes PulseAudio the default and it should work again. Until this is released in Kodi 21.1 use the `--audio-backend=pulseaudio` parameter or set the ENV variable `KODI_AE_SINK=PULSE` to force the usage of PulseAudio over PipeWire.

**Comment by graysky2** [comment]
@neo1973 - can you suggest which commit/commits need to be applied to Omega to fix this?

**Comment by neo1973** [comment]
That would be aff8e6b3a0bfd8a0163a63aa003c45e1680f65c5
