### ISSUE TITLE
Sound then update with No sound

### ISSUE THREAD

**Issue by Martii** [xbmc/xbmc#25002]
### Describe the bug
Here is a clear and concise description of what the problem is:

No sound today after:

``` console
$ sudo flatpak update
```

... was working yesterday before update.

Please advise and thanks for the look.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Have sound.

## Actual Behavior

No sound.

## Possible Fix

Needs check for PulseAudio and offer/use it perhaps in addition to PipeWire if detected.

More of a work around here in the short term...

``` console
$ # Viable solution not messing with installing Pipewire which would affect a lot of applications including system

$ sudo flatpak update --commit=c66a791ac482c3b0c257188f2b3ccf796082176e0822192ec9132f9b78044dd0 tv.kodi.Kodi
[sudo] password:
Looking for updates…


        ID                   Branch         Op        Remote         Download
 1. [✓] tv.kodi.Kodi         stable         u         flathub        39.7 MB / 220.6 MB

Updating… ████████████████████ 100%  6.6 MB/s  00:00
Note that '/var/lib/flatpak/exports/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
environment variables, so applications may not
be able to find it until you set them. The
directories currently searched are:

- /root/.local/share
        ID                   Branch         Op        Remote         Download
 1. [✓] tv.kodi.Kodi         stable         u         flathub        39.7 MB / 220.6 MB

Updates complete.

$ # Prevent updates until fixed for production targets
$ flatpak mask tv.kodi.Kodi

$ ## Future option to release update prevention
$ #flatpak mask --remove tv.kodi.Kodi
```

### To Reproduce

``` console
$ uname -a
Linux machine 6.5.0-27-generic #28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

$ flatpak remote-info --log flathub tv.kodi.Kodi
        ID: tv.kodi.Kodi
       Ref: app/tv.kodi.Kodi/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 220.7 MB
 Installed: 508.2 MB
   Runtime: org.freedesktop.Platform/x86_64/22.08
       Sdk: org.freedesktop.Sdk/x86_64/22.08

    Commit: 12f232340d35749eb4513802c12614126cd0b0e631bf809df414063c1c3e332b
    Parent: c66a791ac482c3b0c257188f2b3ccf796082176e0822192ec9132f9b78044dd0
   Subject: Update hwdata (af8e5a0b)
      Date: 2024-04-14 16:49:35 +0000
   History:

    Commit: c66a791ac482c3b0c257188f2b3ccf796082176e0822192ec9132f9b78044dd0
   Subject: Update addons (25fba414)
      Date: 2024-04-07 15:51:04 +0000

…
```

``` console
$ # Sound at previous release of c66a791ac482c3b0c257188f2b3ccf796082176e0822192ec9132f9b78044dd0

$ flatpak run tv.kodi.Kodi --version
Kodi Media Center 21.0 (21.0.0) Git:20240406-60c4500-dirty
Copyright (C) 2005-2021 Team Kodi - http://kodi.tv

$ # See screenshots beginning with Sound since current flatpak seems a bit useless for versioning switch.
```

``` console
$ sudo flatpak update
```

``` console
$ # No Sound at current release of 12f232340d35749eb4513802c12614126cd0b0e631bf809df414063c1c3e332b

$ flatpak run tv.kodi.Kodi --version
Kodi Media Center 21.0 (21.0.0) Git:20240406-60c4500-dirty
Copyright (C) 2005-2021 Team Kodi - http://kodi.tv

$ # See screenshots beginning with No Sound since current flatpak seems a bit useless for versioning switch.
```

### Debuglog

The debuglog can be found here:

Project should provide a howto reference here in the HTML comments to do this by modifying [xbmc/xbmc/blob/`ddf131b`/.github/ISSUE_TEMPLATE/bug_report.md](https://github.com/xbmc/xbmc/blob/ddf131b114a453280d168093eaf287ad3086ea5c/.github/ISSUE_TEMPLATE/bug_report.md) ... will append in a bit after I find it for before and after... **EDIT** attached:

| Sound | No Sound |
| -------- | ------- |
| [~/.var/app/tv.kodi.Kodi/data/temp/kodi.old.log](https://github.com/xbmc/xbmc/files/14982022/Sound.-.kodi.log)  | [~/.var/app/tv.kodi.Kodi/data/temp/kodi.log](https://github.com/xbmc/xbmc/files/14982027/No.Sound.-.kodi.log) |

### Screenshots
Here are some links or screenshots to help explain the problem:

| Sound | &nbsp; |
| -------- | ------- |
|  <a href="https://github.com/xbmc/xbmc/assets/114709/76db4068-6920-4bde-b1de-21b16e0ff66b"><img src="https://github.com/xbmc/xbmc/assets/114709/76db4068-6920-4bde-b1de-21b16e0ff66b" width="196" height="112" alt="Sound - System Info" title="Click to enlarge... Sound - System Info"></a> | <a href="https://github.com/xbmc/xbmc/assets/114709/78d95de9-9544-47dd-85ea-1ba1cc9183c7"><img src="https://github.com/xbmc/xbmc/assets/114709/78d95de9-9544-47dd-85ea-1ba1cc9183c7" width="196" height="112" alt="Sound - Settings-System" title="Click to enlarge... Sound - Settings-System"></a>  |

| No Sound | &nbsp; |
| -------- | ------- |
|  <a href="https://github.com/xbmc/xbmc/assets/114709/d9dc4adc-5920-4bcb-9f0a-67578ef35368"><img src="https://github.com/xbmc/xbmc/assets/114709/d9dc4adc-5920-4bcb-9f0a-67578ef35368" width="196" height="112" alt="No Sound - System Info" title="Click to enlarge... No Sound - System Info"></a> | <a href="https://github.com/xbmc/xbmc/assets/114709/28dbf97c-b03a-4376-926f-a5d6eeb24c5f"><img src="https://github.com/xbmc/xbmc/assets/114709/28dbf97c-b03a-4376-926f-a5d6eeb24c5f" width="196" height="112" alt="No Sound - Settings-System" title="Click to enlarge... No Sound - Settings-System"></a>  |

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Kubuntu (see above Steps To Reproduce *(STR)*)
 - Kodi version: Varies *(described elsewhere above)*

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
Your system is offering a PipeWire socket so Kodi is using it because the PipeWire backend has higher priority than PulseAudio. To force PulseAudio you can launch Kode with `--audio-backend=pulseaudio`. I can't say what the problem with your PipeWire setup is, maybe a debug log would reveal more information but as is we can't help you any further.

**Comment by Martii** [comment]
@neo1973

It would be more helpful for you to show me how PipeWire was installed. I have **not** installed PipeWire at all. I will try the switch override but the code should be modified to handle any sound server. It used to.

**Comment by neo1973** [comment]
PipeWire is part of your host system, the Flatpak doesn't provide/install it. All yesterdays update does is to expose the PipeWire socket provided by the host to the Flatpak so it can be used: https://github.com/flathub/tv.kodi.Kodi/commit/f7e5df7160a57df41b5c7a4d23730d66025a736e For Kodi to use PipeWire over PulseAudio is the intended behaviour and matches native installs. It's not an option to not expose the PipeWire socket as this breaks the setup for people with a working PipeWire install.

**Comment by Martii** [comment]
@neo1973

>  you can launch Kode with `--audio-backend=pulseaudio`

``` console
$ flatpak run tv.kodi.Kodi --audio-backend=pulseaudio
```

... seems to work with it. Jammy's life cycle is 10 years from release this might be nice to have in the Kodi documentation for those machines... along with support for the flatpak log file locations. Thank you for that suggestion.

> maybe a debug log would reveal more information but as is we can't help you any further.

Debug logs were included about 10 minutes after issue creation.

> All yesterdays update does is to expose the PipeWire socket provided by the host to the Flatpak so it can be used: https://github.com/flathub/tv.kodi.Kodi/commit/f7e5df7160a57df41b5c7a4d23730d66025a736e

Appreciate the explanation. Still trying to find any command that actually shows if PipeWire is installed. I certainly didn't add their PPA.

> For Kodi to use PipeWire over PulseAudio

I think I saw something in a documentation article about this from their PPA... more to check out.

> For Kodi to use PipeWire over PulseAudio is the intended behaviour and matches native installs.

The Ubuntu PPA has been severely out of date, missing binaries, etc, and definitely didn't target PipeWire on any production machines that I've serviced. It was also labeled as PulseAudio... so not sure what you mean here. It's also [been retired](https://kodi.tv/article/ubuntu-team-kodi-ppa-officially-retired/).

**Comment by Martii** [comment]
@neo1973 

``` console
$ pactl info
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 38
Tile Size: 65472
User Name: user
Host Name: htpc
Server Name: pulseaudio
Server Version: 15.99.1
Default Sample Specification: s16le 2ch 44100Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_01_00.1.hdmi-surround
Default Source: alsa_input.usb-SG.Ltd_SG_Control_Mic-00.mono-fallback
Cookie: bd92:6d58
```

Says I'm running PulseAudio on multiple machines that are affected by this... checking for more commands.

**Comment by neo1973** [comment]
> Debug logs were included about 10 minutes after issue creation.

I see the logs but they are not debug logs, please see https://kodi.wiki/view/Log_file on how to create one.

> Still trying to find any command that actually shows if PipeWire is installed. I certainly didn't add their PPA.

According to the German Ubuntu wiki https://wiki.ubuntuusers.de/Pipewire/ (I can't find any English documentation at all) PipeWire is provided starting 22.04 but shouldn't be the default for audio, still it's already used for WebRTC by web browsers. Not sure if that means that the PipeWire socket should exist. You can disable PipeWire entirely via `systemctl --user --now disable pipewire.socket pipewire.service` but that maybe interferes with other stuff.

> is what broke it. If removed then it resumes normal operation with PulseAudio.

That makes sense. But removing it breaks PipeWire for the uses that want to use it, see https://github.com/flathub/tv.kodi.Kodi/issues/240 and in the forum. I'm not sure how Kodi should detect to use PulseAudio over PipeWire if both are present. And something is present on your system, Kodi is seeing one device:

```
2024-04-15 09:17:03.450 T:14       info <general>: Found 1 Lists of Devices
2024-04-15 09:17:03.450 T:14       info <general>: Enumerated PIPEWIRE devices:
2024-04-15 09:17:03.450 T:14       info <general>:     Device 1
2024-04-15 09:17:03.450 T:14       info <general>:         m_deviceName      : Default
2024-04-15 09:17:03.450 T:14       info <general>:         m_displayName     : Default
2024-04-15 09:17:03.450 T:14       info <general>:         m_displayNameExtra: Default Output Device (PIPEWIRE)
2024-04-15 09:17:03.450 T:14       info <general>:         m_deviceType      : AE_DEVTYPE_PCM
2024-04-15 09:17:03.450 T:14       info <general>:         m_channels        : FL, FR
2024-04-15 09:17:03.450 T:14       info <general>:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
2024-04-15 09:17:03.450 T:14       info <general>:         m_dataFormats     : AE_FMT_RAW,AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_S24NE3,AE_FMT_FLOAT
2024-04-15 09:17:03.450 T:14       info <general>:         m_streamTypes     : No passthrough capabilities
```

@lrusak: Do you know of way how to determine if PipeWire is fully working?

> The Ubuntu PPA has been severely out of date, missing binaries, etc, and definitely didn't target PipeWire on any production machines that I've serviced. It was also labeled as PulseAudio... so not sure what you mean here. It's also [been "retired"](https://kodi.tv/article/ubuntu-team-kodi-ppa-officially-retired/).

I'm not talking about Ubuntu in particular, on every Linux distribution that is running PipeWire it will be Kodis preferred choice.

**Comment by Martii** [comment]
@neo1973 

> ... not debug logs ...

My bad was on that page to find the log file location and totally missed that. :) ... Created and updated above with both put below standard logs.

> something is present on your system, Kodi is seeing one device

I assume it's the "Built in Audio" i.e. the motherboard sound which is disabled in the Audio System Settings in KDE/Plasma... can temporarily disable it in BIOS to confirm *(Probably should be since I have no analog speakers hooked up)*. No other hardware sound cards other than HDMI out.

Appreciate the extra tips and time.

**Comment by lrusak** [comment]
Pipewire (and pulseaudio) will likely always have a default device available. It may not be an actual hardware device and may just be a null sink if no hardware is available (or is being held by another soundserver).

**Comment by Erick555** [comment]
>  It's not an option to not expose the PipeWire socket as this breaks the setup for people with a working PipeWire install.

Isn't pipewire re-using pulseaudio socket for compat reasons? Why you need native socket?

**Comment by fritsch** [comment]
I think i'ts the other way round - it provides a pulse compatible socket, so that native pulseaudio clients connect seamlessly into pipewire.

**Comment by Martii** [comment]
> and are now defaulting to pipewire only if it's above 1.0 which is also not perfect but shouldn't break older distros.

That seems reasonable. I was thinking yesterday "What an early Pipewire version... pre-production?"... when I finally found the package names [above](https://github.com/xbmc/xbmc/issues/25002#issuecomment-2057491153). I assume it will eventually be bumped on LTS. 22.x distro has ~8 more years of pro support if they don't. 23.x of K/Ubuntu does default to Pipewire from what I've read.

That leads into the unanswered question of @neo1973 's:

> Do you know of way how to determine if PipeWire is fully working?

... The process logic you describe @Erick555  would probably be an excellent indicator of when not to use *(initialize as Kodi default according to the PR by @fritsch )* Pipewire.

**Comment by neo1973** [comment]
To summarize, the problem is that in some system configurations PipeWire is running but it's not driving the audio system. Ideally there would be a PipeWire mechanisms to detect such a situation but so far that doesn't exist: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1835

SDL just recently worked around this by checking systemd if `pipewire-pulse.service` is running: https://github.com/libsdl-org/SDL/pull/9473

**Comment by Erick555** [comment]
> SDL just recently worked around this by checking systemd if pipewire-pulse.service is running

You may see in the PR I linked above that was reverted and they're checking for pipewire version instead.

**Comment by Martii** [comment]
@neo1973 

Don't know if this will affect [your PR](https://github.com/xbmc/xbmc/pull/25043) but when that machine was tested with:

``` console
$ apt-cache policy pipewire-pulse
pipewire-pulse:
  Installed: (none)
  Candidate: 0.3.48-1ubuntu3
  Version table:
     0.3.48-1ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
     0.3.48-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
```

... the one that I'm on currently **did** have this installed but I didn't run as many tests here on my dev station other than I still didn't have sound here either. So I'm not sure if `Server Name: pulseaudio` had PipeWire in it or not because I got rid of it manually to see if it was needed. Apparently not needed but I have not tested everything system wide *(and probably won't since 24.04.xx is coming up and my dev station here will be replaced as soon as Kubuntu has time to update that)*.

Just something to chew *(ponder)* on. :)

**Comment by Martii** [comment]
@neo1973 

Did #25019 and #25043 make it into either one of these flatpak releases today?:

``` console
$ flatpak remote-info --log flathub tv.kodi.Kodi
        ID: tv.kodi.Kodi
       Ref: app/tv.kodi.Kodi/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 220.7 MB
 Installed: 508.3 MB
   Runtime: org.freedesktop.Platform/x86_64/22.08
       Sdk: org.freedesktop.Sdk/x86_64/22.08

    Commit: 54a88d5dd9f7f477144a2ab9aeee4e161eae88326cc36a67c024f0f435e3d256
    Parent: c37a408730e54535c25dae2e9bcaf62c417cdeacc03219a3833349ac53429a1b
   Subject: Bump FFmpeg to version 6.0.1 (268a8751)
      Date: 2024-05-07 07:09:53 +0000
   History: 

    Commit: c37a408730e54535c25dae2e9bcaf62c417cdeacc03219a3833349ac53429a1b
   Subject: Bump FFmpeg to version 6.0.1 (990163a8)
      Date: 2024-05-07 01:10:04 +0000
```

... if they did then the issue is still present on several production machines. :\ The one I submitted here seems *(redoing flatpak from scratch as we speak with no data folder just to be sure)* to be okay but several others aren't. They keep picking PipeWire... I realize the Accepted Fix above still works but curious as to why it's not working everywhere. I didn't "work-around" two machines with the switch at all and still picking PipeWire.  I'll update more when I can... but would be nice to know if those flatpak release commits include those two PRs please. TIA.

**Comment by Erick555** [comment]
Noneo f the fixes made it into flatpak yet. You may report it in https://github.com/flathub/tv.kodi.Kodi/issues
