### ISSUE TITLE
Kodi v21.0.0 arm64 crashes when I press caps lock

### ISSUE THREAD

**Issue by RichieB2B** [xbmc/xbmc#25003]
### Describe the bug
Here is a clear and concise description of what the problem is:

On my MacBook Pro M1 Max when I run Kodi v21.0.0 arm64 and I press caps lock a few times, it crashes.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Nothing really, just to toggle caps lock

## Actual Behavior

```
Thread 8 Crashed:
0   libdispatch.dylib             	       0x186d6c828 _dispatch_assert_queue_fail + 120
1   libdispatch.dylib             	       0x186d6c7b0 dispatch_assert_queue + 196
2   HIToolbox                     	       0x1917956c4 islGetInputSourceListWithAdditions + 160
3   HIToolbox                     	       0x191797d00 isValidateInputSourceRef + 92
4   HIToolbox                     	       0x191797bc0 TSMGetInputSourceProperty + 44
5   HIToolbox                     	       0x1917b30b0 TISIsDesignatedRomanModeCapsLockSwitchAllowed + 84
6   HIToolbox                     	       0x1917b289c ProcessCapsLockSequenceKeyUp + 204
7   HIToolbox                     	       0x1917b2404 TSMAdjustCapsLockPressAndHold + 1948
8   HIToolbox                     	       0x1917b1be0 TSMSetCapsLockKeyTransitionDetected + 356
9   HIToolbox                     	       0x1917a07c0 CreateEventWithCGEvent + 6204
10  AppKit                        	       0x18aac1db4 +[NSEvent eventWithCGEvent:] + 72
11  Kodi                          	       0x1026d25ec (anonymous namespace)::MediaKeyCallback(__CGEventTapProxy*, CGEventType, __CGEvent*, void*) + 48
12  SkyLight                      	       0x18c824384 processEventTapData(void*, unsigned int, unsigned int, unsigned int, unsigned char*, unsigned int) + 580
13  SkyLight                      	       0x18ca8d57c _XPostEventTapData + 336
14  SkyLight                      	       0x18c824da0 eventTapMessageHandler(__CFMachPort*, void*, long, void*) + 168
15  CoreFoundation                	       0x18702996c __CFMachPortPerform + 248
16  CoreFoundation                	       0x186ffa444 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
17  CoreFoundation                	       0x186ffa364 __CFRunLoopDoSource1 + 524
18  CoreFoundation                	       0x186ff8d28 __CFRunLoopRun + 2244
19  CoreFoundation                	       0x186ff7e0c CFRunLoopRunSpecific + 608
20  CoreFoundation                	       0x187075e3c CFRunLoopRun + 64
21  Foundation                    	       0x188124520 __NSThread__start__ + 716
22  libsystem_pthread.dylib       	       0x186f1af94 _pthread_start + 136
23  libsystem_pthread.dylib       	       0x186f15d34 thread_start + 8
```

### To Reproduce

1. Start Kodi v21.0.0
2. press caps lock a few times
3. crash

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/abayewubih
Crashlog:
https://paste.kodi.tv/viguwikabo

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 14.4.1
 - Kodi version: 21.0.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@RichieB2B can you try a recent nightly?

https://mirrors.kodi.tv/nightlies/osx/arm64/Omega

**Comment by RichieB2B** [comment]
I can't reproduce the issue in the latest nightly. Probably fixed by https://github.com/xbmc/xbmc/commit/bdedba4702660d626fd455497b0d83088c8b1586 ?

<img width="297" alt="image" src="https://github.com/xbmc/xbmc/assets/1461970/bb12f494-6529-40e8-868c-fbcc736be01e">

**Comment by enen92** [comment]
Exactly, thanks
