### ISSUE TITLE
[Kodi v21.0.0][Android][Python] strftime doesn't recognize %-d date format directive

### ISSUE THREAD

**Issue by mediaminister** [xbmc/xbmc#25007]
### Describe the bug
Here is a clear and concise description of what the problem is:

When formatting a string from a Python datetime object in Kodi v21.0.0 on Android, the strftime function doesn't recognize the `%-d` date format directive and simply outputs **-d**

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The Python function strftime should recognize the `%-d` date format directive in Kodi v21.0.0 on Android and convert  `%-d` to the day of the month as a decimal number.

## Actual Behavior

The Python function strftime converts `%-d` to the string **-d**

### To Reproduce

1. write Python code which uses `date.strftime('%-d')`
2. execute this code in Kodi v21 on Android
3. ascertain the string **-d** is outputted

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 Android 13 (ARM64-V8A)
 - Kodi version:
Kodi v21.0.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
No, that's not a bug. You can't expect platform specific behaviour to be available everywhere. Only what is in the docs should be supported: https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior.

**Comment by mediaminister** [comment]
But the `%-d` directive worked perfectly on Kodi Nexus 20.5 on Android!

So, Kodi Omega 21.0.0 on Android is at least a step backwards.

**Comment by scott967** [comment]
Commonly known to be platform dependent.
`date.strftime("%d").lstrip("0")` 
should do same thing?

**Comment by mediaminister** [comment]
This is not a solution because `xbmc.getRegion('datelong')` outputs `%-d` on Android.
Everything worked fine in Kodi 20.5
