### ISSUE TITLE
Problem with fast forwarding by chapter

### ISSUE THREAD

**Issue by Bindou01** [xbmc/xbmc#25014]
Hello everyone, I am encountering several problems related to using chapters to move forward/backward in my films.

_Current configuration: Vim4 - CE Kodi 21 - NAS Synology HDD 250mb/s - SMB connection_

Here is how these problems present themselves precisely : 
https://youtu.be/LLptQ5pNKrY?si=DjN9t3QaN4jX27xN

I can move forward, but sometimes I can't go back to the previous chapter. It literally blocks as you can see in the video above. I can only go back using a means other than chapters. (The video shows the bug on Kodi 21, but this same problem actually causes the system to crash when I'm on Kodi 20.)

In addition to sometimes not being able to go back to the previous chapter, there is an issue displaying chapter thumbnails and bookmarks. In fact, the thumbnails are missing, and when I click on one of them, the film cuts out.

Let us specify :
I find these problems even after a complete reset of CoreElec.
These issues show up on all movies that have chapters, but in random places.
These problems are present on Kodi 20 but also on Kodi 21. However, it is strange, on Kodi 21, the bugs no longer appear in exactly the same places. The move to Kodi 21 therefore affected some of these problems without correcting them.
I use the same video source on all my devices, and I notice that these bugs are exclusively present on my Vim4 CE. Indeed, Kodi 21 on Android works normally. I can find the chapter thumbnails and no crashes when I use them. Plus, I can navigate from one chapter to another without getting stuck.

I restarted and reproduced the problem around 3:15 p.m. with the Terminator movie:

Kodi Log: https://paste.coreelec.org/FJoX5Z
Error log: https://paste.coreelec.org/Lk2lIg
Debugging information: https://paste.coreelec.org/y0R0Bf

Here the extract from the chaptered film:
https://mega.nz/file/AfEkHSrY#anooqQoprF7WX8aFbtKgtd6Nan_aX9uhVju5DUa3xLs

If I could ever get rid of these bugs, that would be great.  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
It should be possible to move from one chapter to another without any problem. In addition, it should be possible to display "thumbnail" images corresponding to the chapters.

### Your Environment
Used Operating system:

CoreELEC

 - Operating system version/name:
 - Kodi version: 21

**Comment by sarbes** [comment]
CoreElec is not Kodi. There are differences, especially in video playback. If it can't be reproduced in Kodi, it is no bug.

If you can reproduce it, or is you can identify a clear bug in the codebase, feel free to reopen the issue.

**Comment by CrystalP** [comment]
Support was attempted but no repro with Kodi https://forum.kodi.tv/showthread.php?tid=376959

**Comment by MoojMidge** [comment]
And here https://discourse.coreelec.org/t/chapter-bookmark-issue-still-present-after-a-reset/51244

While OP is conflating a number of different things, the issue that they are actually describing is that they sometimes cannot navigate to a previous chapter.

The reason is because of stuff like this, where the nearest key frame, where Kodi seeks to, is more than 5 s after the chapter marker:
```
2024-04-06 15:16:18.468 T:1911    debug <general>: SeekTime - seek ended up on time 477477
2024-04-06 15:16:18.468 T:1911    debug <general>: CDVDDemuxFFmpeg::SeekChapter - seeking chapter:3 start:468.927 key-frame:477.477 
...
2024-04-06 15:16:25.058 T:1911    debug <general>: SeekTime - seek ended up on time 2012552
2024-04-06 15:16:25.058 T:1911    debug <general>: CDVDDemuxFFmpeg::SeekChapter - seeking chapter:8 start:2005.754 key-frame:2012.552 
...
2024-04-06 15:16:25.270 T:1911    debug <general>: SeekTime - seek ended up on time 2500790
2024-04-06 15:16:25.270 T:1911    debug <general>: CDVDDemuxFFmpeg::SeekChapter - seeking chapter:9 start:2495.493 key-frame:2500.790 
...
2024-04-06 15:16:25.390 T:1911    debug <general>: SeekTime - seek ended up on time 2829869
2024-04-06 15:16:25.390 T:1911    debug <general>: CDVDDemuxFFmpeg::SeekChapter - seeking chapter:10 start:2822.695 key-frame:2829.869 
```

Which has become problematic because of https://github.com/xbmc/xbmc/pull/24066

**Comment by Bindou01** [comment]
Hello, I don't know if this helps to confirm that this is from CoreElec and not Kodi, but I would like to share this conversation about this problem : https://discourse.coreelec.org/t/chapter-bookmark-issue-still-present-after-a-reset/51244/12

**Comment by CrystalP** [comment]
OP stated that there is a problem in Kodi v20 as well. The PR is v21 only and was not backported so it's not the cause of OP's issue, unless a few different things are mixed up.
There may be a problem with widely spaced key frames, but I don't have any such videos, which sound a bit broken.

**Comment by Bindou01** [comment]
Thank you for your support Mooj, even if you say I'm weird in each of your messages.  ^^

But why does this problem not appear on Android ? What is the difference in chapter management ? Is there a different time limit for checking the previous chapter between Android version and CoreElec ?
