### ISSUE TITLE
Kodi don't use the real Date & Time added to Library for "dateadded"

### ISSUE THREAD

**Issue by Nanomani** [xbmc/xbmc#25010]
### Describe the bug

when I add a new movie or a new tvshow Kodi dont use the real date and time when there is added to the library.
Kodi take the last date when the file was modified.

## Expected Behavior

I expect Kodi use the real date and time when a new movie or a new tvshow are added to the library.

The Wiki Kodi is pretty clear about this : 
https://kodi.wiki/view/Databases/MyVideos#files

## Actual Behavior
Kodi take the last date when the file was modified.

### To Reproduce

(tested without file nfo of course and advanced setting set)

1.  add a new movie (create some time ago) in Kodi library
2. open "myvideosdb131.db" => table "file"
3. see the value in column "dateadded"

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/tegitewaso.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Value in "myvideosdb131.db" => table "file" => Column "dateadded" for a new movie added the 17/04/2024 : 

![2024-04-17_003406](https://github.com/xbmc/xbmc/assets/3939543/d84bfaf9-1654-4563-a06a-24f5a243d5e5)

Property of this file : 

![2024-04-17_004334](https://github.com/xbmc/xbmc/assets/3939543/c44f603f-1b52-464f-a36d-60de1e6a2e28)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I thinks it is a very old issue

### Your Environment
Used Operating system:

 - [X] Android
 - [X] Linux
 - [X] Windows

 - Operating system version/name: tested here with Windows 11 Pro x64
 - Kodi version: 21 Omega

**Comment by ksooo** [comment]
Works as designed. Can be controlled via an advanced setting See https://kodi.wiki/view/Advancedsettings.xml
```
<videolibrary>
    <dateadded>1</dateadded> <!-- 0 results in using the current datetime when adding a video;
                                  1 (default) results in prefering to use the files mtime (if it's valid) and only using the file's ctime if the mtime isn't valid;
                                  2 results in using the newer datetime of the file's mtime and ctime -->
  </videolibrary>
  ```

**Comment by Nanomani** [comment]
@ksooo 
wow, I never thought I'd have to add a parameter for this. 
IMHO the default value should be 0.
There must be a good reason if it s not, but it completely escapes me.

Anyway  thanks a lot for your time and your answer.

**Comment by ksooo** [comment]
> IMHO the default value should be 0.

I personally feel the same. It took me a long time to understand why the "Recently added movies" Estuary widget was not exactly showing the movies I had recently added. ;-)

You can open forum thread (https://forum.kodi.tv) to discuss the change if you like.
