### ISSUE TITLE
Kodi Omega Crashes on Xbox When Receiving JSON Command

### ISSUE THREAD

**Issue by amasephy** [xbmc/xbmc#25015]
### Describe the bug
Here is a clear and concise description of what the problem is:

After upgrading from v20.5 to v21 on my Xbox when attempting to navigate to the settings section of the official iOS remote app (by pressing the ...more button on the right hand pane) which makes a JSON command Kodi on my Xbox will freeze and then crash to the home screen within a few seconds.  I then get an error message on my iPhone.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The ...more button should run a JSON command on Kodi and return the settings available to the iOS app.

## Actual Behavior

Instead of the app receiving the results of the JSON command Kodi crashes on Xbox and the iOS app errors out.

### To Reproduce

1. With iOS app navigate to the settings pane (right most pane).
2. Press the ...more button.

1. Alternatively I presume just sending the JSON command `{"jsonrpc":"2.0","method":"Settings.GetSections","params":{"level":"expert"}, "id":2}` from any other device to Kodi on Xbox.

### Debuglog

The debuglog can be found here:  https://paste.kodi.tv/pidofupeje

### Screenshots 
Here are some links or screenshots to help explain the problem:

![IMG-9148](https://github.com/xbmc/xbmc/assets/20706525/63c0f00c-1b4c-4da5-836a-5a7b79bd66b4)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

JSON command triggering the issue:

`{"jsonrpc":"2.0","method":"Settings.GetSections","params":{"level":"expert"}, "id":2}`

What I derived from the debuglog (last two lines) before the crash occurs:

2024-04-14 20:28:43.901 T:7572 debug <CWebserver[8080]>: request received for /jsonrpc
2024-04-14 20:28:43.901 T:7940 error <general>: CActiveAESink::OutputSamples - sink returned error 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name: Xbox One S
 - Kodi version: Omega

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
I tried to reproduce with Android Kore v3.1.0 and Xbox Series S and all works perfectly, no crash.

I not have any iPhone to test with it.

**Comment by wutschel** [comment]
This crash is not triggered when using Kore's settings menu. Kore does not request the settings from Kodi, but only provides app-internal settings. The iOS remote app requests settings from Kodi server and you can use this to change settings inside Kodi. This is done via a JSON command (see above) which obviously lets the Kodi crash on Xbox.

**Comment by thexai** [comment]
OK I reproduced the crash with web interface Chorus2.

The crash is due DisplayInformation::GetForCurrentView() is called from other thread here:

https://github.com/xbmc/xbmc/blob/f5128624a919f3198dd04fd909e6f7f3a3e7d0f2/xbmc/platform/win32/WIN32Util.cpp#L1341

I'm working on a fix.

**Comment by wutschel** [comment]
Are the issues described in [this forum thread](https://forum.kodi.tv/showthread.php?tid=376991) having the same root cause?

**Comment by thexai** [comment]
No, this crash is related to HDR addition in v21 and in forum the user says crash was already in v20.... He should provide debug log.

**Comment by wutschel** [comment]
> No, this crash is related to HDR addition in v21 and in forum the user says crash was already in v20.... He should provide debug log.

Thanks for looking into it.
