### ISSUE TITLE
Stereo upmix is broken on several platforms 

### ISSUE THREAD

**Issue by RosensRauk** [xbmc/xbmc#25028]
### Describe the bug
Here is a clear and concise description of what the problem is:
Stereo upmix should copy front channel audio to 5.1 but FL and RR channels are now silent.
Nothing shows up in the log. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Stereo upmix should copy audio from FL and FR to multi channel DAC for speakers in the surround system.

## Actual Behavior

Audio channels FL RR are silent.
Multi channel audio files work as expected.
Stereo upmix of stereo files could have the wrong channel mapping where two channels are now silent.

## Possible Fix

Could this be because of the ffmpeg update?

### To Reproduce

1. Activate stereo upmix 
2. Reboot
3. Try to play stereo audio file

### Debuglog

The debuglog can be found here:
No errors.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jjd-uk** [comment]
This has been reported by a number of different people with different platform types in the forum, however no useful logs have been created by anyone yet.

See https://forum.kodi.tv/showthread.php?tid=373679 and https://forum.kodi.tv/showthread.php?tid=375161

**Comment by jjd-uk** [comment]
In case not clear, ticket has been close as fixes have been merged into both Omega branch for v21 and Master for v22.
