### ISSUE TITLE
When you compare the changes in versions 20.5 and 21.0, the wrong results are shown

### ISSUE THREAD

**Issue by D3ZOXY** [xbmc/xbmc#25035]
![Screenshot_2024-04-21-07-30-49-61_9c7ad408470e52983cc8816adf9ff347](https://github.com/xbmc/xbmc/assets/47178587/a6af3c61-1b96-426a-823e-a8034519d14d)

Can someone give real changes between these versions?

**Comment by sarbes** [comment]
Compare the branches...
