### ISSUE TITLE
kodi-send is broken on latest commit from Omega branch

### ISSUE THREAD

**Issue by graysky2** [xbmc/xbmc#25056]
### Describe the bug
Here is a clear and concise description of what the problem is:

`kodi-send` errors out using the latest commit from the Omega branch

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

`kodi-send` should work

## Actual Behavior

```
% kodi-send -a Reboot
Traceback (most recent call last):
  File "/usr/bin/kodi-send", line 27, in <module>
    from kodi.xbmcclient import *
ModuleNotFoundError: No module named 'kodi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/kodi-send", line 30, in <module>
    from xbmcclient import *
ModuleNotFoundError: No module named 'xbmcclient'
```

### To Reproduce

1. Build latest git from Omega
2. Try the above `kodi-send` command

### Debuglog

The debuglog can be found here:

Not appliciable due to bug against a kodi tool, not kodi itself.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:  Arch Linux/latest package set

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
In your description you said "build Kodi" but did you install it also? Did you enable the eventclients in cmake?

**Comment by graysky2** [comment]
Hi @lrusak - yes, built and installed.  Yes, I did enable eventclients in cmake.

```
