### ISSUE TITLE
Kodi Omega not finding database after upgrade

### ISSUE THREAD

**Issue by MarkCallow** [xbmc/xbmc#25052]
### Describe the bug
Here is a clear and concise description of what the problem is:

After upgrading my x86_64 Mac Mini from Kodi 20.5 to 21 I am faced with "Your library is empty ...". No music or video. I use an SQL database on an NAS drive. Everything was working before the upgrade. 

Before this I had updated another computer (M2 MacBook Pro) during which the database was updated. Kodi 21 is working fine on that computer.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expected Kodi to still find my databases and show me my libraries.

## Actual Behavior

I get a message to the effect of "Your library is empty. Go to the files section and add some sources."

In the log I see many messages like:

```
 connect replacing configured host DiskStation.local with resolved host fe80::211:32ff:fe21:c4ae
2024-04-23 17:29:56.764 T:599173   error <general>: Unable to open database: xbmc_music83 [2002](Can't connect to server on 'fe80::211:32ff:fe21:c4ae' (65))
```

My NAS has an IPV4 address. I have no idea what is causing `connect replacing configured host DiskStation.local with resolved host fe80::211:32ff:fe21:c4ae`. This does not happen on the MacBook Pro which has a Wi-Fi connection while the failing MacMini has a wired connection.

### To Reproduce

Don't know. Problem happened immediately on upgrade to Omega and is permament.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/ukujuhudas.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

This screen shot is from phpMyAdmin connected to the database from the same machine and account where Kodi is failing, using the same \<user\> and \<pass\> values and clearly shows the NAS is accessible from the problem machine and that the databases exist.

<img width="231" alt="Screenshot 2024-04-23 at 19 00 05" src="https://github.com/xbmc/xbmc/assets/2244683/2f8a25ac-6646-4e62-8b9e-03d35938ecf6">

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 12.7.4 Monterey
- OS version/name on working M2 MacBook Pro: 14.4.1 Sonoma
- Kodi version: 21 Omega

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Milhouse77** [comment]
I had the same problem. Turned out that I had to remove the <cache> section of my advancedsettings.xml. I reconfigured Caching ci gui afterwards. Everything is fine now. Maybe this can help.

**Comment by MarkCallow** [comment]
In my case the log shows that`advancedsettings.xml` was processed. Hence the failing attempt to connect to the NAS shown in the brief log excerpt I included in the issue.

@Milhouse77 how do you reconfigure caching via the GUI. Is that the same thing as a shared database?

**Comment by Milhouse77** [comment]
@MarkCallow I am sorry, I think I misunderstood your issue then.

**Comment by MarkCallow** [comment]
I have found a solution and potentially one other.

The solution I am using is to change \<host\> from `diskstation.local` to `diskstation.tm`, where `tm` is the domain I set for my home network. Explanation follows.

I discovered that while `ping diskstation.local` resolves to the IPv4 address, `host diskstation.local` fails to resolve to an address.`host` is the utility for doing DNS lookups.  However `host diskstation.tm` resolves to the IPv4 address. I further discovered that on the MacBook Pro (macOS Sonoma) where Kodi works Configure IPv6 in the network settings is set to "Off" while on the MacMini (macOS Monterey) where Kodi does not work, it is set to "Automatically" and the GUI offers no "Off" choice.

My theory is that Kodi's first attempt at DNS resolution fails, just as with `host` and it then tries something that somehow resolves to a non-existent IPv6 address. I have no idea why the problem only surfaced with Kodi 21. After the change to `.tm`, the initial DNS resolution attempt provides the IPv4 address and Kodi can connect to the database.

The second potential fix is to set "Configure IPv6" to "Off" in the network settings. As I said there is no "Off" option in the Monterey GUI. According to [this page](https://protonvpn.com/support/how-to-disable-ipv6-protocol-on-macos/) you can turn if off by choosing "Link-Local Only". You can also turn it off from the terminal with either `networksetup -setv6off Wi-Fi` or `networksetup -setv6off Ethernet` depending on your network interface.

I don't know if there is anything to fix in Kodi's code or if this just needs to be documented. Understanding what changed in Kodi 21 to trigger the problem would help to determine if there is something to fix.

**Comment by neo1973** [comment]
`.local` are names used by mDNS/zeroconf/avahi. It's perfectly valid for a host to announce an IPv4 and IPv6 address simultaneous. Example from my setup:
```
$ avahi-resolve -n -4 nas.local
NAS.local       192.168.0.26
$ avahi-resolve -n -6 nas.local
NAS.local       2003:c9:7f42:a300:d250:99ff:fe9f:1bc2
```
`fe80::`addresses are link local addresses. They can be reached from other PCs but require to add the zone index to the address to establish a connection. So `fe80::211:32ff:fe21:c4ae` is a valid address but can't be used without also adding the index.

In the end this all boils down to a bad configuration of the network. Either assign your DiskStation a regular (non link local) IPv6 and announce that or don't announce a IPv6 address at all.

**Comment by scott967** [comment]
We recommend users specify a static ipv4 address in the advancedsettings file for MySQL database.

**Comment by MarkCallow** [comment]
I have verified that after `sudo networksetup -setv6off Ethernet` `DiskStation.local` works. After running this `networksetup` command "Off" appears in the Network Preferences GUI separated from the others by a horizontal line. I still have several questions:

1. What changed in Omega that when resolving the name it now gets an IPv6 address?
2. How is it doing this resolution? When I try `host -6 diskstation.local` or `dig -6 diskstation.local` I get `connection timed out; no servers could be reached`. `nslookup` does not appear have an option to force IPv6 resolution and I do not have `avahi-resolve` on my Macs. The timeout is not surprising as I have IPv6 disabled on my router.
3. Why is the "zone index",  that @neo1973 says is needed to connect, not included in the debug log message?

> Either assign your DiskStation a regular (non link local) IPv6 and announce that or don't announce a IPv6 address at all.

My router is not announcing an IPv6 address for the DiskStation. As I said IPv6 is disabled on the router.

**Comment by neo1973** [comment]
> What changed in Omega that when resolving the name it now gets an IPv6 address?

I'm not aware of any changes in that area. Kodi uses [`getaddrinfo`](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/getaddrinfo.3.html) to resolve the host and uses whatever the system gives us.

> How is it doing this resolution? When I try host -6 diskstation.local or dig -6 diskstation.local I get connection timed out; no servers could be reached. nslookup does not appear have an option to force IPv6 resolution and I do not have avahi-resolve on my Macs. The timeout is not surprising as I have IPv6 disabled on my router.

I don't know about the ways to resolve hosts on Macs but having IPv6 disabled on your router doesn't matter. A link local address every device assigns themselves (if the IPv6 stack is enabled on that particular device).

> Why is the "zone index", that neo1973 says is needed to connect, not included in the debug log message?

Because we didn't get through `getaddrinfo`. I don't know if there is a way to get it,if there is we don't support it.

> My router is not announcing an IPv6 address for the DiskStation. As I said IPv6 is disabled on the router.

mDNS/zeroconf/avahi is a distributed system, the router is not involved. Every participant announces themselves via multicast to the other devices in the network.

**Comment by MarkCallow** [comment]
Thanks for the information @neo1973. I guess what changed will have to remain a mystery. Anyway it seems clear that disabling IPv6 on the device is the proper fix for my situation where I do not use IPv6 on my network.
