### ISSUE TITLE
Omega plays many videos very choppy

### ISSUE THREAD

**Issue by scifigeek64** [xbmc/xbmc#25069]
### Describe the bug

Here is a clear and concise description of what the problem is:
Many of the videos that I try to view are very choppy. It does not appear to be any specific file type or resolution. It looks like it is skipping 3 or more frames for every frame that is shown.

## Expected Behavior
Smooth video playback.

## Actual Behavior
See description of bug.

### To Reproduce
An example file that has the issue is for the show "America's Backyard Gold". One of the specific files is  "AMERICAS BACKYARD GOLD SERIES S01E03 1080P HEVC X265-MEGUSTA EZTV"
This is happening on a T95ZPlus running Android Version 12, Kodi Omega Build 21.0 (21.0.1) using Seren Version 3.0.0.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
There isn't too much more I can say. It is happening on lots of files. I have rebooted numerous times, and the problem remains. The problem occurs on more videos than it doesn't.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android Version 12
 - Kodi version: Build 21.0 (21.0.1)

**Comment by sarbes** [comment]
We don't condone or support piracy.
