### ISSUE TITLE
[Feature] Add deeplink support in Android version

### ISSUE THREAD

**Issue by albaintor** [xbmc/xbmc#25079]
## Bug report
This is not a bug but a missing feature : in Android version, we cannot open the application from a deeplink : deeplinks are used to open a given application from a predefined link format, which can be useful if we want to open the application at startup or from another application.
By adding this code in the manifest, one could open Kodi by using URL starting with "kodi://".
This deeplink could then be extended to open Kodi directly in different sections (videos, music...)
```xml
<intent-filter>
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <data android:scheme="kodi"/>
</intent-filter>
```

## Expected Behavior
Start Kodi from a deeplink

## Actual Behavior
Not possible to start Kodi from an android link

## Possible Fix
Implementation of  deeplink "kodi://".
This deeplink could then be extended to open Kodi directly in different sections (videos, music...)
```xml
<intent-filter>
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <data android:scheme="kodi"/>
</intent-filter>
```

### Your Environment
Used Operating system:
 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: all versions
 - Kodi version: 21

**Comment by fuzzard** [comment]
We only use GitHub for tracking bugs. Feature requests are made on the forums.

**Comment by albaintor** [comment]
Hi sorry for that I have been too lazy to read all the instructions
