### ISSUE TITLE
WebOS: tv remote „guide“ button should open tv program guide

### ISSUE THREAD

**Issue by alexhass** [xbmc/xbmc#25085]
### Describe the bug
Here is a clear and concise description of what the problem is:

if I watch TV in kodi and press the „guide“ button kodi is exited and the lg sat guide is shown.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should behave like the hd+ app and show the program guide inside kodi.

## Actual Behavior

Kodi is exited and lg sat guide is shown.

## Possible Fix

Redirect the kestroke to kodi and open the kodi tv guide.

### To Reproduce

1. open kodi tv (tvheadend frontend)
2. watch tv
3. press the guide button
4. The lg sat guide opens

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [x] WebOS

 - Operating system version/name: webod 8.3.0
 - Kodi version: 21.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sundermann** [comment]
I don't think this is possible. The default keymask already includes the guide button. From the docs: The compositor is free to ignore certain keys even if set to '1'. It's possible there's a specific exception for the HD+ app in the compositor. HD+ is not available on my model so I can't research on whether there exists another API. If you find another app that does support the epg button natively, feel free to comment on this issue again.

**Comment by alexhass** [comment]
Zattoo seems to use a different navigation. Amazon/joyn also… that really suxxx. May you able to ask LG at least? It is really bad usability from my point of view if the button does not work.

**Comment by sundermann** [comment]
No point in trying for support from LG for a native app. They won't respond

**Comment by alexhass** [comment]
Great that you found something. Looking forward to test on tv soon 👍

**Comment by alexhass** [comment]
Hopefully this can be backported to 21.x, too.

**Comment by alexhass** [comment]
The issue is not fixed in latest nightly. Any chance this goes in?
