### ISSUE TITLE
No sound after pausing and resuming playback on Kodi 21.0 on FireTV Cube Gen2

### ISSUE THREAD

**Issue by dbmtrde** [xbmc/xbmc#25081]
Description:
When watching a movie on Kodi 21.0 installed on FireTV Cube Gen2, if I pause the playback and the screen saver activates, upon returning to play the movie, there is no sound.

Steps to reproduce:

Install Kodi 21.0 on FireTV Cube Gen2.
Start playing a movie.
Pause the playback and wait for the screen saver to activate.
Resume playback after the screen saver is deactivated.
Expected behavior:
Upon resuming playback, the sound should continue as normal.

Actual behavior:
After resuming playback, there is no sound.

Additional information:

This issue occurs consistently.
It is observed only on FireTV Cube Gen2.
No sound issues are encountered during initial playback.
System Information:

Device: FireTV Cube Gen2
Kodi Version: 21.0 Omega-armeabi-v7a
Possible workaround:
Restarting Kodi resolves the issue temporarily, but it reoccurs upon pausing and resuming playback.

I didn't have this problem with version 20.

**Comment by neo1973** [comment]
Please test the current Omega nightlies which have a fix for https://github.com/xbmc/xbmc/issues/24950 which sounds kinda similar.

**Comment by tarres** [comment]
I have the same issue on a Fire TV Cube. Going back to older version now.

**Comment by fritsch** [comment]
Yes, that's a good solution. Without any debuglog no one can help you guys anyways.
