### ISSUE TITLE
4k Video jump 3-4 seconds during the playing 

### ISSUE THREAD

**Issue by perseus177** [xbmc/xbmc#25082]
### Describe the bug
4k Video jump forward 3-4 seconds during the playing after 20 seconds, after it is playing ok some time and again jump forward

## Expected Behavior
Smooth playback of 4k video.

## Actual Behavior

4k movie (1.41GB) 
Movie detail
![image](https://github.com/xbmc/xbmc/assets/25415840/2a677cc5-ae5e-46d5-8994-736bc2f2b441)
The movie is stored directly on Android box storage in folder Downloads

Video recorder : DJI Pocket 2
Player: Xiaomi Mi Box S 4K Gen2

Kodi settings 
MediaCoded (Surface) - Enabled
MediaCode - Enabled

Note: Tried also with disabled but did not help 

No problem with video on VLC on Windows computer, or on directly on Samsung TV

### To Reproduce

1. Open Kodi
2. Select video
3. Play Video 

Observed behavior: 4k Video jump forward 3-4 seconds during the playing after 20 seconds, after it is playing ok some time and again jump forward

### Debuglog

The debuglog can be found here:
Full log - https://paste.kodi.tv/ijonaqexet.kodi

Error in log
```
2024-04-28 18:42:11.707 T:16813   debug <general>: CVideoPlayer::FlushBuffers - flushing buffers
2024-04-28 18:42:11.708 T:16820   debug <general>: CDVDVideoCodecAndroidMediaCodec::Reset Current state (3)
2024-04-28 18:42:11.721 T:15880   error <general>: CMediaCodecVideoBuffer::ReleaseOutputBuffer error in render(true)
2024-04-28 18:42:11.724 T:16823   debug <general>: CDVDAudio::Flush - flush audio stream
2024-04-28 18:42:11.724 T:16823   debug <general>: CDVDAudio::Pause - pausing audio stream
2024-04-28 18:42:11.743 T:16820   debug <general>: CDVDVideoCodecAndroidMediaCodec::InjectExtraData
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 11
 - Kodi version: 21.0.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by perseus177** [comment]
I dont understant what is missing

**Comment by thexai** [comment]
> I dont understand what is missing

The log is incomplete/cut.

Anyway GitHub issues not are for support. Please install latest Omega nightly from  https://mirrors.kodi.tv/nightlies/android/arm/Omega/ and if issue persist use forum for support

https://forum.kodi.tv/forumdisplay.php?fid=164

**Comment by perseus177** [comment]
@thexai there is link for full log because it is not possible to past to the issue full log...

**Comment by thexai** [comment]
Log is cut:

![log](https://github.com/xbmc/xbmc/assets/58434170/326b4d11-df20-4b89-a507-f0c40acd122c)

**Comment by perseus177** [comment]
@thexai 
New log https://paste.kodi.tv/gofagureva

**Comment by Hitcher** [comment]
Please remove all the [banned addons](https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons) and post a new debug log.

**Comment by perseus177** [comment]
@thexai , @Hitcher 

New log https://paste.kodi.tv/atibojefer
