### ISSUE TITLE
kodi 21: av1 file with non standard aspect ration example 2:34 are not letter boxed

### ISSUE THREAD

**Issue by degasdelen** [xbmc/xbmc#25094]
### Describe the bug
Here is a clear and concise description of what the problem is:

av1 file with non standard aspect ration example 2:34 are not letter boxed
i have tested on all device based on s905x4 also on s928
ugoos am8 pro ugoss x4 mecool k6 etc
ok with kodi 20.5

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
No response.
