### ISSUE TITLE
Doesn't read data on external memory

### ISSUE THREAD

**Issue by 22marco77** [xbmc/xbmc#25102]
### Descrivi il bug
Ecco una descrizione chiara e concisa di quale sia il problema:

When I try to select an installation from files on external storage, kodi doesn't see any files even if they are in the right format. Doesn't read data on external memory

## Comportamento atteso
Ecco una descrizione chiara e concisa di ciò che ci si aspettava accadesse:

### Riprodurre
Passi per riprodurre il comportamento:

1. 
2.
3.

### Debuglog

Il debuglog si trova qui:

### Schermate 
Ecco alcuni link o screenshot per aiutare a spiegare il problema:

## Contesto o screenshot aggiuntivi (se appropriato)
Ecco qualche contesto o spiegazione aggiuntiva che potrebbe aiutare a:

### Il tuo ambiente
Usato Sistema operativo:

 - [[] Android

 - Versione/nome del sistema operativo: Android tv  v. 11
 - Versione Kodi: 21 omega

*nota: una volta effettuato il problema, ti chiediamo di aggiornarlo con nuove informazioni o versioni di Kodi qualora ciò fosse richiesto.
Il Team Kodi prenderà in considerazione il tuo rapporto sul problema, tuttavia non faremo alcuna promessa che il problema verrà risolto.*

**Comment by CastagnaIT** [comment]
i think its missing a crucial wiki step on kodi android tv installation instructions
so on all Android TVs with build 11 and highers to allow Kodi access to your files you need to manually set files permissions
on Android TV go to
"Settings -> Apps - Kodi -> Permissions -> Files and Media"
and select
"Allow all the time"

**Comment by 22marco77** [comment]
This was given at the time of installation, allow access to media files. This same problem in addition to being present on Android TV, is also present in chromecast with Google TV

**Comment by CastagnaIT** [comment]
please recheck, more likely you need to change that setting again

**Comment by 22marco77** [comment]
Ok

**Comment by thexai** [comment]
Closing as this is not a bug but current permissions behavior in latest Android versions...
