### ISSUE TITLE
Crash when pressing CapsLock key on macOS 10.15

### ISSUE THREAD

**Issue by dongguaguaguagua** [xbmc/xbmc#25119]
### Describe the bug
Kodi app crushes when pressing CapsLock key to change the input method.

### To Reproduce

1. Require two input methods: ABC & Chinese Pinyin
2. Press the CapsLock key to reproduce the crash

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ewefasucaq.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Mac OS X 10.15.7 (19H15)
 - Architecture: X86-64
 - Kodi version: 21.0. (20240406-60c4500054)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
Dupe (https://github.com/xbmc/xbmc/issues/25003), fixed with 21.1 (https://github.com/xbmc/xbmc/pull/24983).
