### ISSUE TITLE
Kodi not updating to the latest release on Mint

### ISSUE THREAD

**Issue by youngunix** [xbmc/xbmc#25116]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi was installed a long time ago using the method in this guide [https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux?https=1](https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux?https=1) on Linux Mint but it's stuck on 20.2! 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi to upgrade to the latest stable release (21.0).

## Actual Behavior

Kodi does not pull updates.

## Possible Fix

N/A

### To Reproduce

1. Install Kodi on Linux Mint.
2. Update the repos.
3. Attempt to update the pkg.

### Debuglog

The debuglog can be found here:

N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system: 

 
 - [X] Linux
 
 - Operating system version/name: Linux Mint 21.3 (Ubuntu Jammy 22.04 LTS).
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
The team-kodi PPA is no longer maintained as per https://kodi.tv/article/ubuntu-team-kodi-ppa-officially-retired/

You will be best to migrate either to Flatpak, or your distro's package of kodi. Mint is still probably only going to be in the 20.x series anyway however.
