### ISSUE TITLE
Kodi 21 Omega - android TV - sound problem after wakeup from standby

### ISSUE THREAD

**Issue by JurakZdenek** [xbmc/xbmc#25117]
I have 2 devices with Android TV - Nvidia shield and xiaomi TV box S.
After update to omega from Google play I have same problem on both devices: 

I turn off my TV and android box go to sleep.
When I turn on TV and box wakeup in Kodi sound does not work and video is laging.
I have to close the application completely and start it again.

It's annoying. The previous version didn't do this and worked perfectly. Can you please fix it?

**Comment by thexai** [comment]
This is same as https://github.com/xbmc/xbmc/issues/24950 already fixed in nightlies.

Please, install builds from here:
https://forum.kodi.tv/showthread.php?tid=377350&pid=3195455#pid3195455
