### ISSUE TITLE
Need a way to reinitialize the display with standalone mode

### ISSUE THREAD

**Issue by jsumners** [xbmc/xbmc#25123]
First, the problem:

Seemingly at random, when I try to use my Kodi box I will get an "input source not connected" screen on my television.

Second, my setup:

1. Self-built HTPC connected to
2. A Denon receiver connected to
3. A LG C2 television

Third, the request:

I recently had to rebuilt my Kodi box because the distribution I was using stopped maintaining the package. On that old system, I was running Kodi via X11 and could solve the described problem (usually) by SSHing into the system and running the following script:

```sh
#!/bin/bash
export DISPLAY=:0

# use `xrandr --verbose` to see available modes
xrandr --output HDMI1 --mode 0x534 # 0x48

sleep 5

sudo sv restart kodi
```

Typically, only the `xrandr` line would be necessary. Occasionally, the service restart would be needed. And in rare cases I'd need to do a full-on reboot to get the display reinitialized such that Kodi would play videos.

At this time, I start Kodi with the following systemd config:

```ini
[Unit]
Description=Kodi Media Center
After=multi-user.target network.target sound.target graphical.target systemd-user-sessions.service

[Service]
User=htpc
Group=htpc
WorkingDirectory=~

PAMName=login
Environment=XDG_SESSION_TYPE=x11
TTYPath=/dev/tty7
StandardInput=tty
StandardOutput=journal
UnsetEnvironment=TERM

UtmpIdentifier=tty7
UtmpMode=user

ExecStartPre=/usr/bin/chvt 7
ExecStart=/usr/bin/kodi-standalone
ExecStop=/usr/bin/killall --exact --wait kodi.bin
Restart=on-abort

[Install]
WantedBy=graphical.target
```

This works great and gives me HDR playback (something I was sorely missing with the X11 setup). However, I still get the display initialization problem at times when I turn television and receiver on to the proper input/output combination for my Kodi box.

What I need is a way to reinitialize the display remotely. A system command I can bind to a button on my remote would be ideal, but I'd take a suggestion for an alternative script. I tried this one:

```sh
#!/bin/bash
wlr-randr --output HDMI-A-1 --off
sleep 2
wlr-randr --output HDMI-A-1 --on
```

But it does nothing. So every time I get the "input not connected" issue (and the input _is definitely connected_), I have to reboot the Kodi box.

Does the team have any ideas here?

----

<details>
<summary>Required not relevant template</summary>

### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

</details>

**Comment by sarbes** [comment]
The bug tracker is for bugs only. Use the forum.

**Comment by jsumners** [comment]
I have a GitHub account, and am not interested in a forum account. This is also very likely a feature request as it seems to me that with Wayland, the application has to do this work.

**Comment by sarbes** [comment]
Did you even bother to read the template?

**Comment by jsumners** [comment]
> Did you even bother to read the template?

No. I opened a clearly described issue instead.
