### ISSUE TITLE
Collision of build-in controls, e.g. in DialogAddonSettings.xml

### ISSUE THREAD

**Issue by malvinas2** [xbmc/xbmc#25125]
### Here is a clear and concise description of what the problem is:

If the number of list elements is large, the id labels 28 to 30 are assigned (amongst others), which conflicts with the id labels of the build-in controls 'ok', 'cancel' etc. The controls can no longer be accessed via the keyboard (apart from 'ok').
In the example this applies to DialogAddonSettings.xml, but I suppose it could also affect similar dialogs as most of them use id 28-30. 

### Steps to reproduce the behavior:
1. Search for an addon, which has got a large number of entries, e.g. the 'Commodore - Amiga (PUAE)' emulator
2. Open the configuration, which opens the addonsettings-dialog
3. Try to click 'cancel' without using the mouse  ;-)

### Debuglog
no debuglog

### Your Environment
Windows 10, Kodi Omega 21.0
![screenshot00013](https://github.com/xbmc/xbmc/assets/25912063/99c466be-f03e-4db0-a041-701d1619b64a)

**Comment by Hitcher** [comment]
I guess we never thought there would a situation where more than 80 controls would be needed. Having said that I would say the addon itself is probably to blame by not separating them into sections ie System, Media, Retropad, etc.

The code that controls the first button ID is here:

[https://github.com/xbmc/xbmc/blob/058a35d43e571c52193c8652182eb65f6cc9f61b/xbmc/settings/dialogs/GUIDialogSettingsBase.h#L28](#define CONTROL_SETTINGS_START_CONTROL -80)

**Comment by garbear** [comment]
The thinking of the team at the time was, if an add-on has 80 individual settings you have to scroll through, don't do that and use categories.

However, game add-ons are special: we generate our settings from libretro cores, which we don't always have control over.

So maybe a code solution is needed here.

**Comment by Hitcher** [comment]
> So maybe a code solution is needed here.
Then maybe '-200' would be a safer starting point?

**Comment by garbear** [comment]
Sorry, I'm not sure what negative means in this context so I can't say. Do you know of any documentation on negative control IDs?

**Comment by Hitcher** [comment]
I recall Jonathan Marshall mentioning it many, many years ago but can't find the forum post. Basically negative numbers were used so they didn't collide other IDs used by Kodi or a skin.

**Comment by Hitcher** [comment]
Is there a quick way to check the number of settings in an addon so we know the max currently used?

**Comment by garbear** [comment]
Here's a distribution of all the settings for all the game add-ons

game.libretro.vice_x128 - 119 settings
game.libretro.uae - 115 settings
game.libretro.vice_x64 - 115 settings
game.libretro.vice_x64sc - 115 settings
game.libretro.swanstation - 114 settings
game.libretro.vice_xcbm5x0 - 109 settings
game.libretro.vice_xscpu64 - 107 settings
game.libretro.vice_xplus4 - 102 settings
game.libretro.vice_xvic - 101 settings
game.libretro.vice_x64dtv - 90 settings
game.libretro.vice_xcbm2 - 89 settings
game.libretro.vice_xpet - 79 settings
game.libretro.flycast - 72 settings
game.libretro.mupen64plus - 68 settings
game.libretro.mupen64plus-nx - 68 settings
game.libretro.genplus-wide - 63 settings
game.libretro.genplus - 61 settings
game.libretro.beetle-psx-hw - 60 settings
game.libretro.pcsx-rearmed - 60 settings
game.libretro.virtualjaguar - 57 settings
game.libretro.parallext - 56 settings
game.libretro.beetle-psx - 51 settings
game.libretro.hatari - 48 settings
game.libretro.bsnes-hd - 45 settings
game.libretro.beetle-pce - 44 settings
game.libretro.dolphin - 44 settings
game.libretro.desmume - 43 settings
game.libretro.snes9x - 40 settings
game.libretro.fmsx - 35 settings
game.libretro.nestopia - 34 settings
game.libretro.vbam - 34 settings
game.libretro.gambatte - 33 settings
game.libretro.beetle-pce-fast - 32 settings
game.libretro.parallel_n64 - 32 settings
game.libretro.cannonball - 31 settings
game.libretro.sameboy - 31 settings
game.libretro.bsnes - 30 settings
game.libretro.desmume2015 - 30 settings
game.libretro.beetle-supergrafx - 29 settings
game.libretro.ecwolf - 29 settings
game.libretro.mame - 27 settings
game.libretro.melonds - 27 settings
game.libretro.fuse - 26 settings
game.libretro.mesen - 26 settings
game.libretro.ppsspp - 25 settings
game.libretro.beetle-saturn - 24 settings
game.libretro.81 - 23 settings
game.libretro.opera - 22 settings
game.libretro.picodrive - 22 settings
game.libretro.px68k - 22 settings
game.libretro.supafaust - 21 settings
game.libretro.cap32 - 20 settings
game.libretro.hbmame - 20 settings
game.libretro.meowpc98 - 19 settings
game.libretro.mgba - 19 settings
game.libretro.atari800 - 18 settings
game.libretro.same_cdi - 18 settings
game.libretro.xmil - 18 settings
game.libretro.mame2016 - 17 settings
game.libretro.mame2010 - 16 settings
game.libretro.mesen-s - 16 settings
game.libretro.a5200 - 15 settings
game.libretro.dosbox - 15 settings
game.libretro.pokemini - 15 settings
game.libretro.gpsp - 14 settings
game.libretro.pcem - 14 settings
game.libretro.vecx - 14 settings
game.libretro.mame2015 - 13 settings
game.libretro.stella - 13 settings
game.libretro.3dengine - 12 settings
game.libretro.beetle-pcfx - 12 settings
game.libretro.ep128emu - 12 settings
game.libretro.mame2003_midway - 12 settings
game.libretro.o2em - 12 settings
game.libretro.quicknes - 12 settings
game.libretro.snes9x2010 - 12 settings
game.libretro.beetle-wswan - 11 settings
game.libretro.fbalpha2012-cps1 - 11 settings
game.libretro.fbalpha2012-cps2 - 11 settings
game.libretro.fbalpha2012-cps3 - 11 settings
game.libretro.quasi88 - 11 settings
game.libretro.craft - 10 settings
game.libretro.gearsystem - 10 settings
game.libretro.theodore - 10 settings
game.libretro.uae4arm - 10 settings
game.libretro.bk - 9 settings
game.libretro.bluemsx - 9 settings
game.libretro.bsnes-mercury-accuracy - 9 settings
game.libretro.bsnes-mercury-balanced - 9 settings
game.libretro.bsnes-mercury-performance - 9 settings
game.libretro.handy - 9 settings
game.libretro.mame2000 - 9 settings
game.libretro.snes9x2002 - 9 settings
game.libretro.gearboy - 8 settings
game.libretro.mrboom - 8 settings
game.libretro.mu - 8 settings
game.libretro.scummvm - 8 settings
game.libretro.smsplus-gx - 8 settings
game.libretro.tyrquake - 8 settings
game.libretro.yabause - 8 settings
game.libretro.beetle-vb - 7 settings
game.libretro.prboom - 7 settings
game.libretro.boom3 - 6 settings
game.libretro.daphne - 6 settings
game.libretro.fsuae - 6 settings
game.libretro.potator - 6 settings
game.libretro.prosystem - 6 settings
game.libretro.race - 6 settings
game.libretro.vba-next - 6 settings
game.libretro.xrick - 6 settings
game.libretro.gearcoleco - 5 settings
game.libretro.2048 - 4 settings
game.libretro.beetle-gba - 4 settings
game.libretro.chailove - 4 settings
game.libretro.gong - 4 settings
game.libretro.minivmac - 4 settings
game.libretro.openlara - 4 settings
game.libretro.beetle-ngp - 3 settings
game.libretro.dinothawr - 3 settings
game.libretro.freechaf - 3 settings
game.libretro.frodo - 3 settings
game.libretro.vemulator - 3 settings

**Comment by Hitcher** [comment]
Thanks [garbear](https://github.com/garbear), so -200 should be plenty.

I'll sort out a PR and test it out.

**Comment by Hitcher** [comment]
@malvinas2 can you please this fix: https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240506-a1c6d8ec-dialog_settings_id_range-x64.exe

**Comment by malvinas2** [comment]
@Hitcher I installed your fix and just two add-ons, the UAE and a C64 Vice: First element has now id -180, last one (here) -68, id of settings button -200. Control elements on the right (ok, cancel, default values) can be accessed now. Seems to work ;-)
![screenshot00015](https://github.com/xbmc/xbmc/assets/25912063/09f364cd-9888-4f7d-aa2b-361b6d69e1d1)
![screenshot00016](https://github.com/xbmc/xbmc/assets/25912063/06e8cb76-9d69-4140-8257-3e96f0347cff)
![screenshot00014](https://github.com/xbmc/xbmc/assets/25912063/27ee34eb-23ba-4cfd-9744-1c1c5db21e4d)

**Comment by Hitcher** [comment]
Thanks for testing.

**Comment by garbear** [comment]
@malvinas2 Sorry to hijack this thread, but how are Amstrad CPC and C64 working right now? I've shipped a lot of fixes over the years but haven't followed up on how they're working.
