### ISSUE TITLE
Cant play .ogg music files

### ISSUE THREAD

**Issue by nicksillito** [xbmc/xbmc#25143]
### Describe the bug
Kodi wont play ogg/vorbis music files from my music library. Its happy to play mp3 audio and its also ok to play film/tv with a vorbis audio track (where the sound plays correctly)

## Expected Behavior
Select an audio file (in .ogg format) from the library and it plays

## Actual Behavior
The track can be selected (and added to the play queue) but kodi immediately skips the track

### To Reproduce
1. Load kodi 
2. Click on music
3. Select a track to play thats in a .ogg/vorbis file

### Debuglog

The debuglog can be found here:

[https://paste.kodi.tv/uwepiyekud.kodi](url)
See line 780

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 24.04
 - Kodi version: 21.0 (21.0.0) Git:20240406-60c4500-dirty (flatpak)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
Hi, please provide a debug log: https://kodi.wiki/view/Log_file/Easy

**Comment by nicksillito** [comment]
debug log is here [https://paste.kodi.tv/nekurukama.kodi](url)
See line 4703

**Comment by fritsch** [comment]
Wrong ffmpeg version:
```
2024-05-06 15:55:52.719 T:7        info <general>: Kodi compiled 2024-04-14 by GCC 12.2.0 for Linux x86 64-bit version 5.18.7 (332295)
2024-05-06 15:55:52.719 T:7        info <general>: Running on Freedesktop SDK 22.08 (Flatpak runtime), kernel: Linux x86 64-bit version 6.8.0-31-generic
2024-05-06 15:55:52.719 T:7        info <general>: FFmpeg version/source: 6.0
```

**Comment by fritsch** [comment]
See: https://github.com/xbmc/xbmc/issues/23198 which was fixed by ffmpeg 6.0.1 - while you still run 6.0

**Comment by neo1973** [comment]
Ahh, damn it. This one is on us because it's our official Flatpak.

@razzeee: fyi

**Comment by fritsch** [comment]
@neo1973 while at it - can we rebuild with pulse default again? The forums gets reports and reports of workarounds and issues ...

**Comment by neo1973** [comment]
I thought 21.1 would be out by now, but this not being the case razzeee went ahead and reverted the Flatpak change :+1:
