### ISSUE TITLE
Streaming freezes and cuts to source menu

### ISSUE THREAD

**Issue by usfjoe** [xbmc/xbmc#25153]
Hello everyone,

i'm encountering an issue and was hoping to get some help.

When i stream a movie on Kodi v21 (Omega) with Realdebrid Service on Amazon fire TV stick or laptop (windows 10) the stream freezes after a certain time ( it differs  between 10-30 min) and cuts to the source select menu. I have this Problem since a week after i changed my ISP. Iam not having any other Problems with the Internet other than this Kodi issue.

I edited the advancedsettings.xml file and experimented with different cache size, it didnt help.

It starts with the ERROR : **error <general>: CCurlFile::CReadState::XFILE::CCurlFile::CReadState::FillBuffer - (0x295360e1c10) Failed: 
                                            Timeout was reached(28)**

Below you will find the link to my Kodi LOG with default Kodi Cache Settings:
**https://paste.kodi.tv/jibuhumizu**

I would greatly apreciate any assistance or guidance. Thank you.

Best regards, usfjoe

**Comment by rien333** [comment]
> CCurlFile::CReadState::XFILE::CCurlFile::CReadState::FillBuffer - (0x295360e1c10) Failed: Timeout was reached(28)

Could be a networking error. Can you reproduce on a different network? (kind of a big ask, perhaps)

>  Iam not having any other Problems with the Internet other than this Kodi issue.

Some ways of downloading are more robust against these kind of failures than others. If you are only experiencing this with this addon, maybe you'll have more luck contacting its developers.

**Comment by neo1973** [comment]
We don't support piracy here.
