### ISSUE TITLE
Stream freezes and cuts to source select menu

### ISSUE THREAD

**Issue by usfjoe** [xbmc/xbmc#25154]
### Describe the bug
Hello everyone,

i'm encountering an issue and was hoping to get some help.

When i stream a movie on Kodi v21 (Omega) with Realdebrid Service on Amazon fire TV stick or laptop (windows 10) the stream freezes after a certain time ( it differs between 10-30 min) and cuts to the source select menu. 

I have this Problem since a week after i changed my ISP. Iam not having any other Problems with the Internet other than this Kodi issue.

I edited the advancedsettings.xml file and experimented with different cache size, it didnt help.

It starts with the ERROR : **error : CCurlFile::CReadState::XFILE::CCurlFile::CReadState::FillBuffer - (0x295360e1c10) Failed:
                                            Timeout was reached(28)**

for more details please check the Log below.

I would greatly appreciate any assistance or guidance, thank you.

best regards, usfjoe

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/jibuhumizu

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] macOS
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: OMEGA 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
We still don't support piracy here.
