### ISSUE TITLE
Building tools and dependencies fails when building for Android/ARM on WSL Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by txret** [xbmc/xbmc#25162]
### Describe the bug
Here is a clear and concise description of what the problem is:

When building Kodi tools and dependencies download of `m4-1.4.19.tar.xz` fails due to `connection reset by peer`.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Successful download and continuation of build.

## Actual Behavior

When building tools and dependencies download of `m4-1.4.19.tar.xz` fails due to `connection reset by peer`.

## Possible Fix

Change `BASE_URL` protocol from `http` to `https` in `kodi/tools/depends/Makefile.include` and the downloads all succeed.

### To Reproduce

1. Follow instructions in [Android README](https://github.com/xbmc/xbmc/blob/21.0-Omega/docs/README.Android.md)
2. Fails at "Build tools and dependencies:" - `make -j$(getconf _NPROCESSORS_ONLN)`: 
    ```
    user@device:~/kodi/tools/depends$ make -j$(getconf _NPROCESSORS_ONLN)
    make -C native
    make[1]: Entering directory '/home/user/kodi/tools/depends/native'
    make -C m4
    make[2]: Entering directory '/home/user/kodi/tools/depends/native/m4'
    download m4-1.4.19.tar.xz attempt 1
    curl: (56) Recv failure: Connection reset by peer
    ```

### Debuglog

The debuglog can be found here:
Failing in Kodi tools and dependencies build

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Build `21.0-Omega`.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ X ] Linux
 - [ ] macOS
 - [ X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows subsystem Linux (WSL) 24.04 LTS
 - Kodi version: 21.0-Omega

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Mirror issues are known and being investigated
