### ISSUE TITLE
Commit #24064 breaks Bluray folder library addition and playback

### ISSUE THREAD

**Issue by 78andyp** [xbmc/xbmc#25184]
### Describe the bug

I was testing and have found a recent issue adding a BMDV folder.
Using the current master all the files and folders get processed - resulting in multiple Playback entries etc..

![image](https://github.com/xbmc/xbmc/assets/99039295/6fdec5a0-6377-4183-a6ca-f7e8c1e19f39)

Using git bisect the issue seems to be #24064.

Looking at the code it seems that `HAVE_LIBBLURAY` is not being set and hence the BDMV folders/files aren't being properly filtered by `GetOpticalMediaPath`

```
  const auto files = std::array{
      "VIDEO_TS.IFO"s,    "VIDEO_TS/VIDEO_TS.IFO"s,
#ifdef HAVE_LIBBLURAY
      "index.bdmv"s,      "INDEX.BDM"s,
      "BDMV/index.bdmv"s, "BDMV/INDEX.BDM"s,
#endif
```

I think it also breaks bluray playback as well.

Sorry @fuzzard, I don't understand CMAKE to offer anything further.

Thanks
Andy

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Blurays scan/play properly.

## Actual Behavior

As above.

## Possible Fix

HAVE_LIBBLURAY needs setting.

### To Reproduce

As above.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ucowiruqam.kodi
(I had to chop some from the middle as too big - all repetative)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Above

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Could you test the following https://github.com/fuzzard/xbmc/commit/2f105b461ee2d515d180ec3a196f5ab8ac180c65

**Comment by 78andyp** [comment]
Doesn't work. I assume I just needed to `buildsetup nobinaryaddons clean` and not anything more.

**Comment by fuzzard** [comment]
Will need info/logs from the actual build/configure.

CMakeCache.txt and just the output of the cmake configure step
