### ISSUE TITLE
Remove kodi built-in keyboard, use system keyboard.

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [xbmc/xbmc#25189]
### Describe the bug

The kodi built-in keyboard is a pain in the ass to enter links. It doesn't support other languages.

## Expected Behavior
 use system keyboard

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:GrapeneOS Android 14
 - Kodi version:20.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
Feature requests only in the forum please :slightly_smiling_face:

**Comment by lrusak** [comment]
https://kodi.wiki/view/Settings/Interface/Regional
