### ISSUE TITLE
Kodi crashes when 2 concurrent busy dialogs occur (again)

### ISSUE THREAD

**Issue by WallyCZ** [xbmc/xbmc#25194]
### Describe the bug
I put multiple videos into list using Youtube Android app via TubeCast addon and when playlist switched from first video to second, it crashed whole kodi process. There was an issue #16756, but it was closed as fixed and then reopened with possible fix, that got never merged.

## Expected Behavior
It does not crash

## Actual Behavior
It crashes :)

### To Reproduce
1. Install Ayoutube and TubeCast addons
2. Play some video using Android Youtube app via play on TV feature and immediatelly put next video into queue.
3. When first video ends, it wants to switch to next and then it crashes (not every time, there is probably some race condition or something)

### Debuglog
2024-05-11 12:37:06.311 T:699782    info <general>: [plugin.video.youtube] Running: YouTube (7.0.5) on Omega (Kodi-21.0) with Python 3.11.9
                                                   Path: /play/
                                                   Params: {'video_id': 'aGkU1qE5WxU', 'seek': 0.0}
2024-05-11 12:37:06.484 T:699782 warning <general>: [plugin.video.youtube] Failed to retrieved video info - video_id: aGkU1qE5WxU, client: android, auth: False,
                                                   status: CONTENT_NOT_AVAILABLE_IN_THIS_APP, reason: WATCH_ON_LATEST_VERSION_OF_YOUTUBE
2024-05-11 12:37:09.003 T:698789 critical <general>: Logic error due to two concurrent busydialogs, this is a known issue. The application will exit.
[https://logpaste.com/fZk4c2a4](https://logpaste.com/fZk4c2a4)

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreElec 12
 - Kodi version: Omega 21.0

**Comment by sarbes** [comment]
Then why open another bug report?

**Comment by WallyCZ** [comment]
@sarbes Because it's 2 years dead and nobody cares?

**Comment by sarbes** [comment]
That's your perception. And no reason to trash the issue tracker.

**Comment by WallyCZ** [comment]
LOL
I interpret this to mean that there are only incompetent people left on the project and no one is able to fix it properly...
