### ISSUE TITLE
ASS Subtitles only show after seeking

### ISSUE THREAD

**Issue by v-tron** [xbmc/xbmc#25202]
### Describe the bug
I have two separate cases (as in: two separate shows) of ASS subtitles not showing anything on screen until I do a 10 second rewind or change chapter/seek. After seeking once, the subtitles continue to show perfectly fine. Both shows showed subtitles completely normally on Kodi Nexus.

## Expected Behavior
Subtitles show upon starting a video.

## Actual Behavior
Subtitles don't show until a seek is performed. Changing the subtitle track or starting/stopping playback does not fix the problem.

### To Reproduce
Play a video file with ASS subtitles (I am not sure if every ASS subtitle is affected or if there is something about the subtitles on these shows that triggers the bug)

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/simitasate.kodi 

## Additional context or screenshots (if appropriate)
I could record a video of the bug if wanted.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [x] CoreElec

 - Operating system version/name:
 - Kodi version: Omega

**Comment by sarbes** [comment]
Coreelec is not Kodi. Especially the video playback has been altered. Please contact CE, or reproduce on a Kodi system.
