### ISSUE TITLE
Setting "Media > Videos > Default select action" to "Show information" leads to issues when clicking on non-DB video video files (since Kodi 20)

### ISSUE THREAD

**Issue by axbmcuser** [xbmc/xbmc#25217]
### Describe the bug

Setting 
"Media > Videos > Default select action" to "Show information" 
leads to issues when clicking on non-DB video video files (since Kodi 20)

## Expected Behavior

With the described setting, non-DB video files should simply just play as they did with Kodi 19 instead of opening any dialogs

## Actual Behavior

On Kodi 20, clicking on such video files leads to a dialog telling the user "Show video information - No information available"

On Kodi 21-22, clicking on such files leads to opening an empty "DialogVideoInfo"-dialog for the non-DB video file.

## Possible Fix

not sure

### To Reproduce

see above

### Debuglog

.
### Screenshots 

.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Kodi 20-22

**Comment by PatK9** [comment]
Work-round set Default select action" to " choose for small pop-up to play etc.
