### ISSUE TITLE
DialogKeyboard/DialogNumeric heading label empty for many situations (since Kodi 18)

### ISSUE THREAD

**Issue by axbmcuser** [xbmc/xbmc#25216]
### Describe the bug
The DialogKeyboard/DialogNumeric heading label is empty for many situations since Kodi 18
See https://forum.kodi.tv/showthread.php?tid=375059

I don't use or do much testing on the latest Kodi versions. Did some quick testing today on 22 nightly and the issue seemingly still exists.

Random example:

Tvheadend HTSP Client > Configure > Connection settings (tab) > "Name" > Click to open DialogKeyboard = heading text visible
Tvheadend HTSP Client > Configure > Connection settings (tab) > "Tvheadend hostname or IP adress" > Click to open DialogKeyboard = heading text missing

(Finally had some spare minutes to write this quick report so it does not get lost as asked by @Hitcher. ping @scott967)

## Expected Behavior
Heading labels should not be empty

## Actual Behavior
see above

## Possible Fix
.

### To Reproduce
see above

### Debuglog
.

### Screenshots 
.

## Additional context or screenshots (if appropriate)
See https://forum.kodi.tv/showthread.php?tid=375059

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Kodi 20-22

**Comment by ksooo** [comment]
Confirming the issue.
