### ISSUE TITLE
Kodi downscales when matching by refresh rate

### ISSUE THREAD

**Issue by Boulder08** [xbmc/xbmc#25210]
### Describe the bug
Here is a clear and concise description of what the problem is:

When Kodi searches for the matching items from whitelist, it sometimes ends up actually downscaling the output. For example, the GUI is set to 4K and whitelisted resolutions are all 1080p and 4K ones. Playback a 4:3 1440p file which for example has a resolution of 1972x1440 and Kodi will downscale to 1080p, outputs that and then the TV upscales to 4K.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Only upscaling should happen because downscale + upscale is harmful to quality (unless you really know what you are doing).

## Actual Behavior

Kodi downscales to the closest resolution from the whitelist.

## Possible Fix

Prevent downscaling, or add an option like there is for double framerate or 3:2 pulldown framerates.

### To Reproduce

1. Set GUI to 4K
2. Whitelist all 1080p and 4K
3. Playback a 4:3 1440p file

### Debuglog

The debuglog can be found here:
https://drive.google.com/file/d/1UlBusG6xbvYYO42bt5hEV24UNld3_qJw/view?usp=drive_link

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: CoreELEC
 - Kodi version: 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
Coreelec is not Kodi. Especially the video playback has been altered. Please contact CE, or reproduce on a Kodi system.
