### ISSUE TITLE
Kodi Master TVOS suddenly playing DRM links in apple tv 4K 

### ISSUE THREAD

**Issue by Davincii4** [xbmc/xbmc#25226]
### Describe the bug
Here is a clear and concise description of what the problem is: tvOS is playing DRM link in kodi 22

## Expected Behavior
Here is a clear and concise description of what was expected to happen: DRM not supported in tvOS

### To Reproduce

1. To start with I am total noob
2. using kodi for past one week only
3. Tried to use IPTV and wasn’t supporting DRM links and Installed some random repositories and addons and suddenly the DRM link not supported error is gone and my IPTV is working but have no idea how but willing to give as much information as possible 

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system: tvOS 17.5

 - [ ] Android
 - [ ] iOS
 - [x] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 22

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by kambala-decapitator** [comment]
https://kodi.wiki/view/Log_file

**Comment by Davincii4** [comment]
https://paste.kodi.tv/iqevakocom

**Comment by Davincii4** [comment]
I guess its using some YouTube plugin or addon as before getting log some YouTube addon playback error popped and the channel showed the same error but once restart kodi it worked again again I am not sure how

**Comment by Davincii4** [comment]
Its using plugin for youtube 668.7.0.7+beta.1.unofficial.1 by anxdpanic, bromix, MoojMidge from Diggz Repository

**Comment by CastagnaIT** [comment]
i think you just installed `inputstream.adaptive`,

from the log you played a couple of videos from plugin.video.jiotv addon
but despite that addon add property "inputstream.adaptive.license_type" with `com.widevine.alpha`
these videos dont show a DRM encryption and more likely are clearkey AES128 that dont require a DRM

now i dont know the plugin.video.jiotv,
its possible that it could provide some DRM videos but they are not these,
or plugin.video.jiotv adds license_type property incorrectly

instead youtube dont use any DRM

are there any particular problems?
i was not aware that `inputstream.adaptive` is available also on tvOS, how you installed it?

**Comment by kambala-decapitator** [comment]
The addon is available on tvOS: https://jenkins.kodi.tv/view/Omega%20Binary%20Add-ons/job/xbmc/job/inputstream.adaptive/job/Omega/

**Comment by CastagnaIT** [comment]
i mean that i dont find it on mirrors releases

**Comment by CastagnaIT** [comment]
good to know,
they can receive binary auto-updates? or are stuck with bundled binary?

**Comment by kambala-decapitator** [comment]
> good to know,
> 
> they can receive binary auto-updates? or are stuck with bundled binary?

They're stuck, unfortunately. Users have to repack app bundle themselves to use a newer binary addon version.

**Comment by Davincii4** [comment]
The problem with plugin.video.jiotv is an indian IPTV provider it produces DRM links for the channels but even though the default input stream helper the iptv gave an error DRM not supported on TVOS, but when I installed the YouTube app came with some unofficial input stream helper and all of a sudden it worked but if theres any error message on the stream the message passes through the YouTube app I am also confused but it works i just thought it could help to get some drm requirements to bypass through

**Comment by Davincii4** [comment]
> The problem with plugin.video.jiotv is an indian IPTV provider it produces DRM links for the channels but even though the default input stream helper the iptv gave an error DRM not supported on TVOS, but when I installed the YouTube app came with some unofficial input stream helper and all of a sudden it worked but if theres any error message on the stream the message passes through the YouTube app I am also confused but it works i just thought it could help to get some drm requirements to bypass through



> i think you just installed `inputstream.adaptive`,
> 
> from the log you played a couple of videos from plugin.video.jiotv addon but despite that addon add property "inputstream.adaptive.license_type" with `com.widevine.alpha` these videos dont show a DRM encryption and more likely are clearkey AES128 that dont require a DRM
> 
> now i dont know the plugin.video.jiotv, its possible that it could provide some DRM videos but they are not these, or plugin.video.jiotv adds license_type property incorrectly
> 
> instead youtube dont use any DRM
> 
> are there any particular problems? i was not aware that `inputstream.adaptive` is available also on tvOS, how you installed it?
> 
> > IPTV and wasn’t supporting DRM links and Installed some random repositories and addons and suddenly the DRM link not supported error is gone
> 
> IPTV what means for you? the plugin.video.jiotv addon? its not so clear to me the error message you have seen, but imo more likely came from that addon (not kodi itself)

The problem with plugin.video.jiotv is an indian IPTV provider it produces DRM links for the channels but even though the default input stream helper the iptv gave an error DRM not supported on TVOS, but when I installed the YouTube app came with some unofficial input stream helper and all of a sudden it worked but if theres any error message on the stream the message passes through the YouTube app I am also confused but it works i just thought it could help to get some drm requirements to bypass through

**Comment by CastagnaIT** [comment]
> They're stuck, unfortunately. Users have to repack app bundle themselves to use a newer binary addon version.

got it, so its the same thing of Kodi for windows store or xbox

> The problem with plugin.video.jiotv is an indian IPTV provider it produces DRM links for the channels but even though the default input stream helper the iptv gave an error DRM not supported on TVOS, but when I installed the YouTube app came with some unofficial input stream helper and all of a sudden it worked but if theres any error message on the stream the message passes through the YouTube app I am also confused but it works i just thought it could help to get some drm requirements to bypass through

anyway if plugin.video.jiotv has a way to detect if their streams dont require DRM
the "license_type" property should not be set, and if so, also the inputstream helper DRM checks can be ignored/skipped,
but this must be reported to plugin.video.jiotv devs not here

**Comment by Davincii4** [comment]
> > They're stuck, unfortunately. Users have to repack app bundle themselves to use a newer binary addon version.
> 
> got it, so its the same thing of Kodi for windows store or xbox
> 
> > The problem with plugin.video.jiotv is an indian IPTV provider it produces DRM links for the channels but even though the default input stream helper the iptv gave an error DRM not supported on TVOS, but when I installed the YouTube app came with some unofficial input stream helper and all of a sudden it worked but if theres any error message on the stream the message passes through the YouTube app I am also confused but it works i just thought it could help to get some drm requirements to bypass through
> 
> anyway if plugin.video.jiotv has a way to detect if their streams dont require DRM the "license_type" property should not be set, and if so, also the inputstream helper DRM checks can be ignored/skipped, but this must be reported to plugin.video.jiotv devs not here

Well i tried to recreate the same but it failed with the same drm error then i found out that its not the YouTube app thats helping but the slayguy drm helper made it possible to play the IPTV

**Comment by CastagnaIT** [comment]
Based on your log i have already provided you with an answer to who you should report to
since this is not dependent on kodi itself, but on addons that you are using i close the issue
