### ISSUE TITLE
Show resources (backgroud, covers, etc..) also for subfoldered games

### ISSUE THREAD

**Issue by Maxximo88** [xbmc/xbmc#25237]
### Describe the bug
Here is a clear and concise description of what the problem is:
XBMC is able to show resources (backgroud, images, videos, DVD Covers...) for games located in:
F:\Games\GameName\ _resources
If I create a subfolder for alphabetic organization of games, XBMC is not able to find resources in the following structure
F:\Games\ A\  GameName\ _resources
F:\Games\ B\ GameName\ _resources
F:\Games\ C\ GameName\ _resources

## Expected Behavior
XBMC must be able to show resources also for games organized in subfolders, allowing users to group games and show resources properly.

## Actual Behavior
XBMC is able to show resources if a game is locaded like following:
F:\Games \ GameName\ _resources
But not if it's inside a subfolder
F:\Games\  A \  GameName\ _resources

### To Reproduce
Simply cut and past a game folder inside a subfolder.

### Screenshots 
Please refer to the video you can see in the following tweet
https://twitter.com/Maxximo88/status/1792529526863392934?s=19

**Comment by neo1973** [comment]
Wrong project my friend, we are Kodi since 2014 :slightly_smiling_face: . The repo only has the xbmc name for legacy reasons. What you are looking for is probably https://github.com/Rocky5/XBMC4Gamers which we are not affiliated with.
