### ISSUE TITLE
Cannot install in Sony latest TV model K-75XR70

### ISSUE THREAD

**Issue by Louiskatrina** [xbmc/xbmc#25242]
I tried to install several versions into my new bought Sony latest TV, model K-75XR70. But none of them cannot be successfully installed. Always said not compatible.

The versions I tried,
- kodi-20.3-Nexus-arm64-v8a
- kodi-21.0-Omega-arm64-v8a
- kodi-20240520-068f0f69-Omega-arm64-v8a
- kodi-20240520-3b2688a1-master-arm64-v8a

My TV OS version no. is attached.
![TV ver](https://github.com/xbmc/xbmc/assets/170631428/7f3dd51e-a4b6-44f8-9ff2-d6bf1ac6989e)
![Failed message](https://github.com/xbmc/xbmc/assets/170631428/22c9149f-575b-4c71-8587-304d1b8d98b5)

**Comment by smf007** [comment]
I see you were only trying the 64bit versions.  My Sony is a couple years old, but can only run the 32bit versions as the OS is still 32bit on them despite having hardware capable of 64bit.  Maybe give a 32bit version a try.

**Comment by Louiskatrina** [comment]
it actually works...with 32 bit. Holly crap...a new product with 32bit in 2024?!!! Who would've thought...
