### ISSUE TITLE
kodi 21.0-4 crashing 6.5.3-1-MANJARO

### ISSUE THREAD

**Issue by anthonybtedesco** [xbmc/xbmc#25243]
[kodi_crashlog-20240523_120343.log](https://github.com/xbmc/xbmc/files/15422443/kodi_crashlog-20240523_120343.log)

### Describe the bug
Here is a clear and concise description of what the problem is:

I have installed kodi using pacman from the offiicial repos and it crashes on start.

I'm just an average linux user, I've successfully run kodi on this machine and os instance before, however after some time sound was not functioning I suspected that this had to do with my sound configuration, but that turned out to be incorrect as YouTube and other programs were working along with DAW software such as reaper. I use pulseaudio and I'm pretty certain its all in order.

I began to receive errors about libvdpau-va-gl, so i installed it and then it would just seg fault. So I removed kodi using pacman -R and reinstalled it, only to have the same crashing problem.

when pacman -R'ing kodi I ensured that there were no mentions of kodi on my system with sudo find / -iname kodi ---> output was empty

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
```
[mattricks@lauer ~]$ cat kodi_crashlog-20240523_120343.log | grep error
#6  0x00007f41ad2ab3dd in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x55ebf534df98 <typeinfo for fmt::v10::format_error>, dest=0x7f41adf013c0) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#7  0x00007f41adf00065 in fmt::v10::detail::throw_format_error(char const*) () at /usr/lib/libfmt.so.10
2024-05-23 12:03:42.926 T:2912    error <general>: DBus error: org.freedesktop.DBus.Error.InvalidArgs - No such property “OnLowBattery”
2024-05-23 12:03:42.927 T:2912    error <general>: DBus error: org.freedesktop.DBus.Error.InvalidArgs - No such property “CanSuspend”
2024-05-23 12:03:42.927 T:2912    error <general>: DBus error: org.freedesktop.DBus.Error.InvalidArgs - No such property “CanHibernate”
[mattricks@lauer ~]$
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: kodi 21.0-4
 -  OS: 6.5.3-1-MANJARO

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
The full content of `kodi_crashlog-20240523_120343.log` is required, I can't work with just the snippets.

**Comment by anthonybtedesco** [comment]
@neo1973 I apologize I thought i had uploaded it, but its there now.

**Comment by anthonybtedesco** [comment]
@neo1973 Interesting, so you think this is a deeper problem in my OS configuration rather than a kodi problem? The weird thing is I've had it running on here before, is there any way for me to refresh these libraries its using?

**Comment by neo1973** [comment]
> Interesting, so you think this is a deeper problem in my OS configuration rather than a kodi problem?

Yes, that's most likely. If this would be a more common Kodi problem this would most likely already have been reported.

>  The weird thing is I've had it running on here before, is there any way for me to refresh these libraries its using?

If you did everything through the package manager then I can't think of problem that would be fixed by reinstalling packages. But you can try to launch Kodi with the `--debug` option, this will create a debug log and maybe it contains some useful additional information.

**Comment by sarbes** [comment]
This report sounds awfully close to https://github.com/xbmc/xbmc/issues/18076

**Comment by anthonybtedesco** [comment]
> This report sounds awfully close to #18076

Cheerio mate, that was it.
