### ISSUE TITLE
Kodi crashes seemingly randomly at streams (VCRUNTIME140.dll seems to be the culprit)

### ISSUE THREAD

**Issue by Yavos** [xbmc/xbmc#25257]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing streams sometimes kodi crashes at (for me) random points. With the twitch plugin this somewhat more often happens right after playing the ads at the beginning. Sometimes it happens in the middle of the stream. Also noticed this behavior with other streaming services.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi not crashing or giving some useful error report.

## Actual Behavior

Kodi just closes without any notice.

### To Reproduce

1. Play stream (twitch seems to be more likely)
2. Wait for Kodi to crash.

### Debuglog

The debuglog can be found here:
kodi.log can be found here: https://pastebin.com/nscnWC8F
crashlog and stacktrace files see below
[kodi_crashlog-20.5 Git_20240303-4b95737efa-20240526-115248.dmp](https://github.com/xbmc/xbmc/files/15447056/kodi_crashlog-20.5.Git_20240303-4b95737efa-20240526-115248.dmp)
[kodi_stacktrace-20.5 Git_20240303-4b95737efa-20240526-115247.txt](https://github.com/xbmc/xbmc/files/15447057/kodi_stacktrace-20.5.Git_20240303-4b95737efa-20240526-115247.txt)

This is what the windows event viewer shows me
```
- System 
  - Provider 
   [ Name]  Application Error 
   [ Guid]  {a0e9b465-b939-57d7-b27d-95d8e925ff57} 
    EventID 1000 
    Version 0 
    Level 2 
    Task 100 
    Opcode 0 
    Keywords 0x8000000000000000 
   - TimeCreated 
   [ SystemTime]  2024-05-26T09:52:48.3713919Z 
    EventRecordID 4368 
    Correlation 
   - Execution 
   [ ProcessID]  20340 
   [ ThreadID]  20156 
   Channel Application 
   Computer Akatsuki 
  - Security 
   [ UserID]  S-1-5-21-3502866969-53193881-3033319102-1001 
- EventData 
  AppName kodi.exe 
  AppVersion 20.5.0.0 
  AppTimeStamp 65e3a17e 
  ModuleName VCRUNTIME140.dll 
  ModuleVersion 14.38.33135.0 
  ModuleTimeStamp e2e02087 
  ExceptionCode c0000005 
  FaultingOffset 00000000000110bb 
  ProcessId 0x4304 
  ProcessCreationTime 0x1daaf52244c2379 
  AppPath c:\Kodi\kodi.exe 
  ModulePath C:\Windows\SYSTEM32\VCRUNTIME140.dll 
  IntegratorReportId c1171f9f-cb2d-410c-a4f6-ea4f05d8a26d 
  PackageFullName  
  PackageRelativeAppId  
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

none

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

none

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 (Version	10.0.22631 Build 22631)
 - Kodi version: 20.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
V20 is not supported anymore. Please reproduce with 21.

**Comment by Yavos** [comment]
Didn't happen so far with 21. I'll close this issue for now.
Should it happen again, I'll just reopen a new one.
