### ISSUE TITLE
Limited color range to full color range conversion

### ISSUE THREAD

**Issue by ArturAlekseev** [xbmc/xbmc#25254]
My TV shows content as it is, so all limited color range content is shown as it is with bad blacks, bad contrast and not original colors.
TV is working under Android TV OS. There is no options about color range in TV.
Kodi for Android TV OS does not have such options too.

Please add an option during playback to enable limited color range -> full color range conversion.

**Comment by chewitt** [comment]
The support forum is here: https://forum.kodi.tv/ .. to ask for help and make feature requests.
