### ISSUE TITLE
ToggleButton usealttexture not rendering control

### ISSUE THREAD

**Issue by jurialmunkey** [xbmc/xbmc#25279]
### Describe the bug
Here is a clear and concise description of what the problem is:

On latest master nightlies, togglebutton controls with `<usealttexture>True</usealttexture>` are not rendering.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The usealttexture should toggle the togglebutton between rendering its main texture state and its alttexture states.

## Actual Behavior

In the alttexture state the togglebutton simply is not rendered

### To Reproduce

Create a togglebutton in Estuary at the end of the Home.xml like so

```
<control type="togglebutton">
	<visible>True</visible>
	<label>TOGGLEBUTTON Main Label</label>
	<altlabel>TOGGLEBUTTON Alt Label</altlabel>
	<align>center</align>
	<aligny>center</aligny>
	<usealttexture>False</usealttexture>
	<height>300</height>
	<width>700</width>
	<centerleft>50%</centerleft>
</control>
```

See that it renders correctly with usealttexture set to `False`. 

Switch usealttexture to `True` and reload skin to note that the togglebutton does not render at all (no font or texture). However, it is still clickable and will leave an appropriate space in a grouplist.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/upegevibad.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Toggle button in False state (use main textures) - displays correctly:

![screenshot00574](https://github.com/xbmc/xbmc/assets/4618719/792c3e7e-7bf4-483d-8c2a-37eed586e3a7)

Toggle button in True state (use alt textures) - doesn't display (it should display like above but with the alt label instead).

![screenshot00575](https://github.com/xbmc/xbmc/assets/4618719/8534e7d5-fd70-4169-828c-9f20e568c34d)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Initially reported in this issue thread for my skin: https://github.com/jurialmunkey/skin.arctic.fuse/issues/926

However, as demonstrated above, can also be reproduced easily in Estuary, so it is not skin specific.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: 22.0-ALPHA1 (21.90.700) Git:20240529-c0a22c9e22

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
Could you test http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240530-fe890ea1-toggle-fix-x64.exe please?

**Comment by howie-f** [comment]
slight issues with the alternate version on linux, please see slack

**Comment by jurialmunkey** [comment]
> slight issues with the alternate version on linux, please see slack

Yeah I've got a few issues on Windows too. Commented in main PR thread.

**Comment by Fuchs246** [comment]
`<usealttexture>VideoPlayer.Content(livetv)</usealttexture>`

Doesn't work anymore, alttexturefocus and alttexturenofocus have no texture.

I had to swap the textures and use this then it works again.

`<usealttexture>!VideoPlayer.Content(livetv)</usealttexture>`

Tested with the Titan MOD skin and the kodi version "KodiSetup-20240618-008c70a2-master-x64.exe".

The complete code that doesn't work.
```
<control type="togglebutton" id="206">
	<description>Next or ChannelDown</description>
	<width>$PARAM[size]</width>
	<height>$PARAM[size]</height>
	<label>209</label>
	<font></font>
	<texturefocus colordiffuse="$INFO[Skin.String(OSDButtonsFocusColor)]">$PARAM[iconspath]NextTrack_fo.png</texturefocus>
	<texturenofocus colordiffuse="$INFO[Skin.String(OSDButtonsColor)]">$PARAM[iconspath]NextTrack.png</texturenofocus>
	<usealttexture>VideoPlayer.Content(livetv)</usealttexture>
	<alttexturefocus colordiffuse="$INFO[Skin.String(OSDButtonsFocusColor)]">$PARAM[iconspath]ChannelDown_fo.png</alttexturefocus>
	<alttexturenofocus colordiffuse="$INFO[Skin.String(OSDButtonsColor)]">$PARAM[iconspath]ChannelDown.png</alttexturenofocus>
	<onclick condition="VideoPlayer.Content(livetv)">ChannelDown</onclick>
	<onclick condition="!VideoPlayer.Content(livetv)">PlayerControl(Next)</onclick>
	<visible>!Skin.HasSetting(OSDDisablePlaybackControls)</visible>
</control>
```

The complete code that works.
```
<control type="togglebutton" id="206">
	<description>Next or ChannelDown</description>
	<width>$PARAM[size]</width>
	<height>$PARAM[size]</height>
	<label>209</label>
	<font></font>
	<texturefocus colordiffuse="$INFO[Skin.String(OSDButtonsFocusColor)]">$PARAM[iconspath]ChannelDown_fo.png</texturefocus>
	<texturenofocus colordiffuse="$INFO[Skin.String(OSDButtonsColor)]">$PARAM[iconspath]ChannelDown.png</texturenofocus>
	<usealttexture>!VideoPlayer.Content(livetv)</usealttexture>
	<alttexturefocus colordiffuse="$INFO[Skin.String(OSDButtonsFocusColor)]">$PARAM[iconspath]NextTrack_fo.png</alttexturefocus>
	<alttexturenofocus colordiffuse="$INFO[Skin.String(OSDButtonsColor)]">$PARAM[iconspath]NextTrack.png</alttexturenofocus>
	<onclick condition="VideoPlayer.Content(livetv)">ChannelDown</onclick>
	<onclick condition="!VideoPlayer.Content(livetv)">PlayerControl(Next)</onclick>
	<visible>!Skin.HasSetting(OSDDisablePlaybackControls)</visible>
</control>
```

**Comment by sarbes** [comment]
It should be fixed. If you still find an issue relating the button, feel free to reopen. Alternatively, create a new issue.
