### ISSUE TITLE
Google chromecast with google tv 4k x265 file stutter

### ISSUE THREAD

**Issue by truesarang** [xbmc/xbmc#25290]

**Comment by truesarang** [comment]
uploaded debug log

**Comment by truesarang** [comment]
any help?

**Comment by sarbes** [comment]
This is not a commercial help desk. Nagging every few hours will net you nothing. On the contrary, it might discourage others from chiming in on the issue.

**Comment by thexai** [comment]
> any help?

Github issues are not for help "you". GitHub issues are for report a code error and help us to fix it...

> No description provided.

Not seems good bug report...

> 1080p x265 file with framerrate of 23.976216 mp4 file will stutter in kodi in CCWGTV 4k
> 1080p x265 file with framerate of 23.976024 or 24 will play fine in kodi in CCWGTV 4k

23.976216 frame rate is not valid:  the only similar valid one is 24000 / 1001 = 23.97602397602398

Please use forum for support: https://forum.kodi.tv/forumdisplay.php?fid=164
