### ISSUE TITLE
Subtitles not shown when playing avi file with external srt

### ISSUE THREAD

**Issue by h3llrais3r** [xbmc/xbmc#25299]
### Describe the bug
Here is a clear and concise description of what the problem is:

Subtitles are not shown when playing an avi file with an external srt with the same name.
Same behavior on windows 10 kodi and chromecast with google tv kodi (android).

No subs displayed when playing:
![image](https://github.com/xbmc/xbmc/assets/1945295/4324f37d-7066-4a98-936a-735d5d84c8ca)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Subtitles are shown.
(Subtitles are shown when directly played with vlc and jellyfin, but not through kodi)

## Actual Behavior

No subtitles shown.

## Possible Fix

N/A

### To Reproduce

Playing avi file with external srt.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/wijotumala.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 & Chromecast
 - Kodi version: latest 21 version.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
Please test with an Omega nightly build from https://mirrors.kodi.tv/nightlies/, we recently fixed a SMB issue that could be related.

**Comment by h3llrais3r** [comment]
I've just tested it on latest nightly build, but still no subtitles for the avi files.
![image](https://github.com/xbmc/xbmc/assets/1945295/6402ab7f-7865-49fc-ac2a-03bc1e29416e)

**Comment by Hitcher** [comment]
Please don't paste snippets of the debug log here, instead post the full debug log at https://paste.kodi.tv/ save and share the link.

**Comment by h3llrais3r** [comment]
> Please don't paste snippets of the debug log here, instead post the full debug log at https://paste.kodi.tv/ save and share the link.

Issue updated.

**Comment by KarellenX** [comment]
We need the full log. From start to end, Not just the bit you think is important.

Please test without using Jellyfin as your media provider- ie, make sure Kodi has direct access to the file system. We take no responsibility for what 3rd party addons are doing or not doing.

**Comment by h3llrais3r** [comment]
Ok, then I'll have to setup a test instance without jellyfin, as all my instances are configured with jellyfin.
However, it's configured to run in native mode (direct file access), so not sure if I really need to disable it as it uses direct access for playback?
![image](https://github.com/xbmc/xbmc/assets/1945295/6df1ddca-3398-44c0-820c-ff297a3ed4c3)

**Comment by h3llrais3r** [comment]
Issue updated with debug log running on portable version and playing the avi file with srt.
Here the link again: https://paste.kodi.tv/wijotumala.kodi

**Comment by KarellenX** [comment]
Seems to be working ok.
Line 553 is where playback is started
Line 558 is start of subtitle search
Line 559 is where the subtitle file is found
Line 561 is the details of the subtitle file.

The subtitle contains no language, no name or modifier. 
Are you expecting the subtitle to just automatically play with the video? Why would it?

**Comment by h3llrais3r** [comment]
> The subtitle contains no language, no name or modifier.

Yes, as it's an external srt file... this doesn't contain any info as it's just a plain text file.

> Are you expecting the subtitle to just automatically play with the video? Why would it?

Of course I would expect to load it automatically, as every media player (kodi included, because it worked in previous versions, although I cannot say when it stopped working, as I haven't played this video file in the last 7 years or so) by default loads any external subtitle as long as it's next to the file with the same name, which is the case here.

The same works with other formats, as I have a lot of mkv, mp4 files that have an srt next to it... where it always works.
It only seems to fail when I'm trying to play an avi (Xvic codec) with an srt next to it.

As mentioned above, it works with other media players like vlc, jellyfin, ... only kodi seems to have problems with it.

**Comment by KarellenX** [comment]
I for one would not like subtitles to just start playing automatically because they happen to be in my movie folder.

Subtitle files have specific uses as you know. Some may be commentary, or SDH or Forced subtitles.

You need to nominate what type of subtitle track it is by renaming the file.

You have...
\The.Vampire.Diaries.S01E01.DVD.srt

It should be renamed to (sorry I don't know what language that is, so I'll use Italian)...
\The.Vampire.Diaries.S01E01.DVD.**ita.default**.srt

Read my post here... https://forum.kodi.tv/showthread.php?tid=210069&pid=2861861#pid2861861

**Comment by h3llrais3r** [comment]
> I for one would not like subtitles to just start playing automatically because they happen to be in my movie folder.

That is your opinion. As mentioned before, any system loads the external subtitle when it has exactly the same name as the file, but with srt extension. That's a common agreement that has been there for ages...


> Subtitle files have specific uses as you know. Some may be commentary, or SDH or Forced subtitles, and there may be multiple external subtitle track in the folder.

I know, but that's when you have multiple subs, so you can distinguish them. If you only have one, like me, you don't need to distinguish it and you just name it in the same way as the video file, and it loads it.

As mentioned above, previous versions of Kodi (tested with 19.3, but I can try another version as well if you want) were loading it perfectly.

I don't understand why you are closing this as it can perfectly be reprocuded by starting any avi (xvid codec) file with a subtitle file next to it. 
Did you actually try to reproduce it?
I think you only made your conclusion based on the log file... but a log file doesn't always proves it's working or not.
Sometimes things don't work, even when there is no trace in the log files (I know it, as I'm a developer myself).

So please re-open this, as it's a bug, as it was working with previous versions of Kodi, and it works with other video files (mkv and mp4).

**Comment by KarellenX** [comment]
@CastagnaIT Anything you can add here?

**Comment by Hitcher** [comment]
> I don't understand why you are closing this as it can perfectly be reproduced by starting any avi (xvid codec) file with a subtitle file next to it.

Just tested and they were loaded fine.

![Clipboard01](https://github.com/xbmc/xbmc/assets/133808/d2bd3ec2-1c6e-47e2-8c44-e462c9121a00)

![screenshot00006](https://github.com/xbmc/xbmc/assets/133808/e2bc7a1f-9769-43f4-8775-60e2fae5bd71)

**Comment by CastagnaIT** [comment]
> @CastagnaIT Anything you can add here?

i dont have AVI with XVID
but i have AVI with MP4 but external subtitles here works as expected

sound weird that depends on video codec since fwik has no relations with the subtitles rendering
maybe @h3llrais3r can provide a video sample + sub file to allow us to try reproduce it

**Comment by h3llrais3r** [comment]
> > I don't understand why you are closing this as it can perfectly be reproduced by starting any avi (xvid codec) file with a subtitle file next to it.
> 
> Just tested and they were loaded fine.
> 
> I then set 'Enable subtitles' and 'Set as default for all media', replayed and they loaded straight away.

I tried the same thing, even selected the subtitle individually, but it's not displaying.
Be aware that the avi has very low resolution... maybe that has something to do with it?

**Comment by h3llrais3r** [comment]
> > @CastagnaIT Anything you can add here?
> 
> i dont have AVI with XVID but i have AVI with MP4 but external subtitles here works as expected
> 
> sound weird that depends on video codec since fwik has no relations with the subtitles rendering maybe @h3llrais3r can provide a video sample + sub file to allow us to try reproduce it

I can share, but how do you want me to share it?

**Comment by CastagnaIT** [comment]
your subtitle files are malformed

![](https://github.com/xbmc/xbmc/assets/3257156/6b1c5cef-0791-4966-a2ce-c00c2ae77d4b)
![](https://github.com/xbmc/xbmc/assets/3257156/7b26372f-8840-4521-bb8a-6e9d0e1b2a07)

contains a mixed form of CR/CRLF
and so have bad empty lines between numeration, the cue timing and text's
where must not have empty lines

a good file usually like follow:
![immagine](https://github.com/xbmc/xbmc/assets/3257156/1c511d66-c89c-412a-bf30-fe42b4dcae4b)

and so this cause a bad subtitle parsing

**Comment by CastagnaIT** [comment]
I need to check it better, but i think its possible make the parser more flexible to handle this malformed situation

**Comment by h3llrais3r** [comment]
@CastagnaIT Thanks for checking it out and re-opening the issue.
I didn't manipulate these subs. That's how they were downloaded a long time ago.
I'm just wondering: it was working with kodi before version 20.x, so maybe something has been changed on the parser that made it more strict?

**Comment by h3llrais3r** [comment]
Hi, I did some work at my side at well, and I wrote some small script to convert my wronly formatted subtitles to match a correct layout.

It scans for all `srt` files in a folder and converts them to the right format and encoding ('utf-8')

```pythyon
import chardet
import sys
import os
  
def detect_encoding(file_path): 
    with open(file_path, 'rb') as file: 
        detector = chardet.universaldetector.UniversalDetector() 
        for line in file: 
            detector.feed(line) 
            if detector.done: 
                break
        detector.close() 
    return detector.result['encoding']

def convert_subtitle(file_path, new_file_path, encoding_from, encoding_to='utf-8'):
    first_line = True
    with open(file_path, 'r', encoding=encoding_from) as fr:
        with open(new_file_path, 'w', encoding=encoding_to) as fw:
            for line in fr:
                line_stripped = line.strip()
                if line_stripped:
                    if line_stripped.isnumeric():
                        if first_line:
                            fw.write(line_stripped + '\n')
                            first_line = False
                        else:
                            fw.write('\n' + line_stripped + '\n')
                    else:
                        fw.write(line_stripped + '\n')


# parse folder
folder_path = sys.argv[1]

print('Processing srt files in folder: ' + folder_path)
for file in os.listdir(folder_path):
    if file.endswith('.srt') and not file.endswith('.new.srt'):
        file_path = os.path.join(folder_path, file)
        file_enc = detect_encoding(file_path)
        print ('Converting subtitle: ' + file)
        convert_subtitle(file, file.replace('.srt', '.new.srt'), file_enc)
```

Once it's converted, the subs are loaded as well.

So I confirm it's indeed something with format, but I would still expect that if it worked with a previous version of Kodi, it should still work. Of course, this probably never happens, only with very old srt files with strange formats.
