### ISSUE TITLE
Unable to access User folder on Linux

### ISSUE THREAD

**Issue by mhdzumair** [xbmc/xbmc#25337]
### Describe the bug

Unable to open User folders in KODI file manager in Linux installed via flatpak. Its only able to access `$Home/Videos` and `$Home/Pictures`. Other files mounted drives cannot be opened. 

### To Reproduce

1. Open Kodi
2. Add-ons -> Install from zip file
3. tried to open Downloads folder.

### Debuglog

The debuglog can be found here:
```
2024-06-16 21:09:58.700 T:7        info <general>: Loading skin file: FileBrowser.xml, load type: KEEP_IN_MEMORY
2024-06-16 21:10:01.048 T:7       error <general>: GetDirectory - Error getting /home/dedsec/Downloads/
2024-06-16 21:10:01.048 T:7       error <general>: CGUIDialogFileBrowser::GetDirectory(/home/dedsec/Downloads/) failed
2024-06-16 21:10:01.657 T:7       error <general>: GetDirectory - Error getting /home/dedsec/Downloads/
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian 12
 - Kodi version: 21.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
That's the whole point of Flatpak... You have to explicitly add permissions, through the Flatpak command line (https://docs.flatpak.org/en/latest/sandbox-permissions.html) or GUI tools like Flatseal.
