### ISSUE TITLE
Admin -- Player -- Subtitles >> Missing hover tips on several items

### ISSUE THREAD

**Issue by kittmaster** [xbmc/xbmc#25348]
### Describe the bug
Here is a clear and concise description of what the problem is:

Missing item hover item tooltip user feedback.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Select item for adjustment and while select read description of what item does.

## Actual Behavior

Nothing shows up on a few items under subtitles area.

## Possible Fix

Dev only fix

### To Reproduce

Go there, select, view nothing

### Debuglog

N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://forum.kodi.tv/showthread.php?tid=377949&pid=3201626#pid3201626

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
N/A

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Omega

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Fixed by https://github.com/xbmc/xbmc/pull/25365
