### ISSUE TITLE
4 byte UTF-8 data from tmdb.org can crash Android app with MySQL backend

### ISSUE THREAD

**Issue by abs0** [xbmc/xbmc#25353]
### Describe the bug

The Android appears to crash if it experiences any issue in the connection to a MySQL or MariaDB backend.

A good way to trigger this is attempting to scrape a TV show from TMDB with text includes 4 byte UTF-8 symbols - such as <U+1F970> / 🥰 when MySQL/MariaDB is setup with the default utf8mb3 encoding. In this case the the server will return an error which will cause the Android app to crash

It would be helpful if the MySQL backend setup notes also mentioned this potential issue and included a suggestion on how to configure the backend for utf8mb4 encoding (will open a separate issue for that)
Other platforms (macOS and Windows) do not crash in this situation

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

App does not crash if server returns a SQL error

## Possible Fix

Server returns SQL error, app crashes and exits

### To Reproduce

1. Configure MySQL or MariaDB server with default utf8mb3 encoding
2. Set a TV scraped directory of "Simon's Cat (2008)", containing at least the file "00x13.mp4"
3. Scan directory - see app exit

### Debuglog

No debuglog, but the actual SQL command as logged by the server was:

UPDATE episode SET c00='Love Story (full colour special)',c01='In purrsuit of Chloe...🥰  Watch Simon\'s Cat\'s hopeful attempts to win over Chloe\'s affections in our full colour special: Love Story!',c03='-1',c04='',c05='2021-03-12',c06='<thumb spoof=\"\" cache=\"\" aspect=\"thumb\" preview=\"https://image.tmdb.org/t/p/w780/t9ayWf6loE5D0pt92CLUq2mjeUu.jpg\">https://image.tmdb.org/t/p/original/t9ayWf6loE5D0pt92CLUq2mjeUu.jpg</thumb>',c09='0',c10='',c11='',c12='0',c13='13',c14='',c15='-1',c16='-1',c17='-1',c18='http://video/TV/downloads/Simon%27s%20Cat%20%282008%29/00x13.mp4',c19='1133',c20='180454', userrating = NULL, idSeason = 28428 where idEpisode=140584;

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: FireTV OS, but also seen on Android 13 on Pixel
 - Kodi version: 21.0
 
Server is running mariadb-server-10.11.8nb3 on NetBSD, but any version of MariaDB or MySQL which defaults to utf8mb3 should suffice.  If the server defaults to a different character set then deleting the kodi databases and adding the following to my.cnf should suffice:
[mysqld]
collation-server = utf8mb3_unicode_ci
init-connect='SET NAMES utf8mb3'
character-set-server = utf8mb3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
No response.

**Comment by abs0** [comment]
Hi, what aspect is non-reproducable, the Android app crashing if there is an error from a MariaDB connection, or the specific issue with 4 byte UTF-8 data in a scraper with a database set to utf8mb3?

Happy to perform more testing this end to get an easier reproducer
