### ISSUE TITLE
No Audio with HDMI Connection

### ISSUE THREAD

**Issue by Pony100574** [xbmc/xbmc#25351]
[log-2024-06-21-06.36.15.zip](https://github.com/user-attachments/files/15925169/log-2024-06-21-06.36.15.zip)

I have a Homatics Box 4k r Plus Dune HD and CoreElec 21 Stable on a USB stick.
When I start from USB CE, I have no sound in KODI. No matter what audio settings I use, with or without passthrough, I get no sound from the box. The box is connected to a Pioneer VSX-527 amplifier via HDMI, the amplifier to a TCL TV.
If I connect the box directly to the TV, sound is coming out of the TVs Speakers. I suspect that the HDMI handle is somehow faulty.
Tried different HDMI Cables, different Ports on Amp, no change. 

### To Reproduce

1. 
2.
3.

### Debuglog

[log-2024-06-21-06.36.15.zip](https://github.com/user-attachments/files/15925169/log-2024-06-21-06.36.15.zip)

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [x] CoreELEC

 - Operating system version/name:
 - Kodi version: 21 Stable on latest CoreELEC

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Pony100574** [comment]
I cannot give more Informations, not a example for reproducing, all i can do is share my debuglog and hope that someone of you Guys sees an fixes the Issue.

**Comment by Pony100574** [comment]
Hello,please have a look at the issue I posted, I thing I did not ignore the rules, I hope so.Am 21.06.2024 um 10:56 schrieb xbmc-gh-bot[bot] ***@***.***>:﻿
Thank you for using Kodi and our issue tracker. This is your friendly Kodi GitHub bot 😉
It seems that you have not followed the template we provide and require for all bug reports (or have opened a roadmap item by accident). Please understand that following the template is mandatory and required for the team to be able handle the volume of open issues efficiently.
Please edit your issue message to follow our template and make sure to fill in all fields appropriately. The issue will be closed after one week has passed without satisfactory follow-up from your side.
This is an automatically generated message. If you believe it was sent in error, please say so and a team member will remove the "Ignored rules" label.

**Comment by chewitt** [comment]
The support forum is over here: https://forum.kodi.tv
