### ISSUE TITLE
Registering Kodi as a service on Google TV?

### ISSUE THREAD

**Issue by syedrey** [xbmc/xbmc#25386]
### Describe the bug
Here is a clear and concise description of what the problem is:

The Kodi content does display on Android 11 Google TV.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should be able to display as different section(continue watching, recently added, PVR content, etc) on the home screen of Google TV launcher.

## Actual Behavior

No display of content of Kodi on home screen. Even the "Now Playing on Kodi" appears for short period when app is minimized but disappears soon.

## Possible Fix

Best possible way to be able to display Kodi content on Google TV launcher will be to add/register Kodi as a service in Google TV content preferences(see image attached below).

### To Reproduce

1.  Playlists don't appear anyways on Google TV.

### Debuglog

The debuglog can be found here:
not necessary in this case.

### Screenshots 
Here are some links or screenshots to help explain the problem:

![IMG_20240626_144025](https://github.com/xbmc/xbmc/assets/72121982/31c015ec-d275-4bb6-9523-295707afab34)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ✓] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21 Omega (Latest)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Feature requests can be made on the forums.
