### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by htatla81** [xbmc/xbmc#25398]
### Describe the bug
Here is a clear and concise description of what the problem is:

On kodi 21 I have been experiencing loss of audio when I playback a video. I have to restart The app to get Audio to work 
I’m using fire tv cube on Samsung QLED tv 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

To hear sound playback of video 

## Actual Behavior

On playback of video I don’t hear the sound untill I restart kodi

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
No response.

**Comment by htatla81** [comment]
I will have to plead the 5th on providing more details/logs due to your rules on use of 3rd party
Addons - however I have used kodi for over 9yrs and never experienced this issue untill v21…

Again Audi is lost on playback of 4k video streams - the temporary fix is to toggle “Allow Passthrough” on/off which brings the expected audio back - is the dev team already aware of this bug?
