### ISSUE TITLE
Pipewire update breaks working applications

### ISSUE THREAD

**Issue by Snxrre** [xbmc/xbmc#25414]
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing video files, Kodi kills the entire systems sound output on all output devices until logging out or rebooting. On local files this happens as soon as the video ends, on internet streams it happens as soon as playback starts. kodi is otherwise fully fuctional. the sound isn't just gone from Kodi, my entire PC is unable to output sound until restarted. Closing Kodi doesn't bring the audio back.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi plays sound along side the video. My system plays sound through the connected speakers. After a video end, my system and Kodi are still able to play sound.

## Actual Behavior

Kodi play sound for the duration of the video, then stops playing sound. Spotify and other applications also stop playing sound at the same time. The pc needs to be restarted in order to play sound again.

Edit: sometimes it just happens for no reason, without playing a file at all.

## Possible Fix

No idea. it did however work until yesterday evening, so it is probably related to the newest update.

### To Reproduce

1. Install Kodi
2. Run Kodi
3. Select a Video Source
4. Play a Video
5. Watch your entire systems sound disappear

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/biwoyuzolo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

https://github.com/xbmc/xbmc/issues/25398 Seems to be the same issue, just not well reported.
Issue hasn't affected me majorly, except for spending another afternoon trying to fix Kodi.
I was trying to accomplish watching an episode of a TV show that i have been watching for the past few months without issue.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
Linux EndeavourOS (Arch Based) 
AwesomeWM as Window Manager
Linux 6.9.7-arch1-1 Kernel
X11 Display Server

My hardware should be Good enough, i have an older i7 cpu and a 4070 Nvidia gpu.

 - Operating system version/name: EndeavourOS
 - Kodi version: 21.0-6

Let me know if any info is missing, ill try my best to provide it.

Thanks for your time.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Snxrre** [comment]
Yeah, im also on pipewire 1.2.0 so its almost certainly the same issue. Sound like the issue has more to do with pipewire then. Thanks for bringing thatbto my Attention.

**Comment by fritsch** [comment]
We can remove the driver flag though. Seems to not make too much sense and was most likely a copy and paste from existing PW example.

**Comment by fritsch** [comment]
I revisited the code - we need to stay a driver. We properly call process like the docu mentions it and wants to have it. There is nothing to be fixed in kodi.

**Comment by dijkstrah** [comment]
Posted as well on [pipewire](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/4087):

Have applied the patch [b151b1f5](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/b151b1f570f27e3c33a164bd6d03b816197f46a2) to pipewire-1.2.0, devices go rogue after a first play.

Removed the PW_STREAM_FLAG_DRIVER flag in xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp from CAESinkPipewire::Initialize, rebuild Kodi and audio keeps working.

I dare not say this is the way it ought to be, but it works.

**Comment by fritsch** [comment]
Yeah - I pinged the developer. Want to really understand what we are doing wrong - if at all. See, when I remove it now - I might break old pipewire. Pipewire is very new and new features come in nearly daily ... therefore it's extremely important that we get the kodi sink implemented in a way, that we are "properly working" on all stable versions.

If you see our pulseaudio implementation. I did that once - several years ago and since then nothing needed to be changed. I am not used to killing the audio middleware without changing anything, while only a minor was bumped upstream.

**Comment by dijkstrah** [comment]
Agreed. Release notes of pw-1.2.0 state no API changes, but this begs to differ.

**Comment by fritsch** [comment]
Yeah - it still compiles -> no API changes :P but does not help if behaviour changed ...

**Comment by Snxrre** [comment]
Just as a heads up, it seems like the problem has been fixed with the latest update to Pipewire, 1.2.1

**Comment by fritsch** [comment]
From the changelog:

"KODI Audio Issues Resolved: A fix was implemented in the node activation counters. This bug previously disrupted audio output using the popular media center software KODI."

Sadly - while I asked if we could improve something / make it more robust in kodi - I did not get an answer, therefore I assume we are doing it fine ...

**Comment by dijkstrah** [comment]
Well.... if 1.2.1 is a release with that node activation patch applied assuming PW_STREAM_FLAG_DRIVER in the init is no longer used, nothing much has changed., has it?

**Comment by fritsch** [comment]
Hopefully ... let's wait for 1.2.2 or 1.3.0.
