### ISSUE TITLE
[Xbox] binary add-on 'pvr.stalker' is missing in .msix installer - Omega nightly builds

### ISSUE THREAD

**Issue by thexai** [xbmc/xbmc#25410]
### Describe the bug
Here is a clear and concise description of what the problem is:

Binary add-on `pvr.stalker` is missing in UWP-64 installers generated in jenkins Omega nightly builds.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

`pvr.stalker` should be in .msix intaller like all others binary add-ons as in Xbox is not possible install others binary add-ons not included in original install package submitted to MS Store.

## Actual Behavior
`pvr.stalker` missing in .msix

## Possible Fix

This was already fixed before (https://github.com/kodi-pvr/pvr.stalker/pull/175) but the fix has been reverted with recent changes:

https://github.com/kodi-pvr/pvr.stalker/pull/224

### To Reproduce

Jenkins nightly builds 

https://jenkins.kodi.tv/view/Windows/job/WIN-UWP-64/26227/

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/odapejunez.kodi
https://paste.kodi.tv/nihugaqigu.kodi
https://paste.kodi.tv/edufaxepub.kodi
https://paste.kodi.tv/oqayecemen.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

![pvr](https://github.com/xbmc/xbmc/assets/58434170/de5448c9-f050-41fd-bf70-8670dcae9e69)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [X] Windows UWP

 - Operating system version/name:
 - Kodi version:  Omega branch

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by phunkyfish** [comment]
There is a PR there to fix the libxml verison.

https://github.com/kodi-pvr/pvr.stalker/pull/226

But for some reason it does not detect the libraries on windows.

**Comment by thexai** [comment]
> There is a PR there to fix the libxml verison.

You are talking of different things: bump libxml may work or not work but is not the problem because is not merged yet.

The problem if this commit: https://github.com/kodi-pvr/pvr.stalker/commit/c94c2b78aeea12310e8fc355ebd4a6230e8f46f4

> Can you explain why pvr.stalker is different? Why does it need specific handling for .msix? Or is it just the libxml version thatis the problem?

pvr.stalker needs "special" build of xml2 (build with different flags) and then is need store with a different name call it `libxml2-stalker` if you not like `libxml2-2.9.10` otherwise conflicts with others libxml2 already build previously.

Rename dependency name forces build fresh with required flags. If is used same name for all (libxml2), CMake only builds it the first time (for any other random add-on). Then when is build pvr.stalker fails at LINK stage because libxml2 not has appropriate flags.

**Comment by phunkyfish** [comment]
Ok, thanks for the explanation. Libxml2 moved to using cmake fully in recent versions. I wonder if there is an easy way leveraging this can we can use to achieve this. 

What specifically are the required flags?

**Comment by thexai** [comment]
Sorry, I've already said everything I know about this.

**Comment by thexai** [comment]
Fixed by https://github.com/kodi-pvr/pvr.stalker/pull/226

This Omega build contains `pvr.stalker` again:
https://jenkins.kodi.tv/view/Windows/job/WIN-UWP-64/26454/
