### ISSUE TITLE
STRM: at playback stop CCurlFile Stat/GetMimeType are called by freezing kodi for ~20 secs

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#25422]
### Describe the bug
Here is a clear and concise description of what the problem is:

The STRM played have:
`#KODIPROP:mimetype=application/dash+xml`

for playlist files its possible set `KODIPROP:mimetype` to avoid that Kodi core make a HTTP HEAD request to the server to get the file mimetype

this is a lot useful for urls where server "dont like" this type of requests for whatever reason is behind it

this seem to works at least before that playback starts, but when playback its stopped dont works
`CCurlFile::Stat` and `CCurlFile::GetMimeType` are called by causing HTTP errors
due to this errors kodi freeze for about 20 seconds making it unmanageable

PS. i tested this with kodi builded as debug

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Dont call `CCurlFile::Stat` and `CCurlFile::GetMimeType`  at playback stop to prevent HTTP errors from servers and Kodi freezes

## Actual Behavior

Kodi freeze for many secs at playback stop

### To Reproduce

1. Install InputStream Adaptive Add-on
2. Play this STRM [DASH_LIVE_TEST2_live_insert.strm.txt](https://github.com/user-attachments/files/16062648/DASH_LIVE_TEST2_live_insert.strm.txt)
3. Stop playback

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/bedapoyewe.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: builded as debug from master branch (kodi 22)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
No such issues here: https://paste.kodi.tv/kanezikefu.kodi

**Comment by CastagnaIT** [comment]
dont happens every time that freeze with the error, you have to try at least some times
i have rebuilded kodi with master branch since was missing some new commits to my build, but same problem
https://paste.kodi.tv/ewohisefew.kodi

**Comment by neo1973** [comment]
> dont happens every time that freeze with the error, you have to try at least some times

I tried 25 times in a row but it didn't happen at all

**Comment by CastagnaIT** [comment]
idk why to me happens...i will try debug when i will find time hoping im able to understand something

**Comment by ksooo** [comment]
@CastgnaIT

> but when playback its stopped dont works
CCurlFile::Stat and CCurlFile::GetMimeType are called by causing HTTP errors

I can reproduce this.

> due to this errors kodi freeze for about 20 seconds making it unmanageable

But I do not experience any hang. CURL returns immediately with an error. macOS here. Maybe something platform specific?

**Comment by CastagnaIT** [comment]
> Maybe something platform specific?

possible, its not the first time that when i catch an http error kodi hang for many secs on WIndows
