### ISSUE TITLE
Kodi crashes when trying to play stream with inputstream.adaptive

### ISSUE THREAD

**Issue by Yavos** [xbmc/xbmc#25424]
### Describe the bug
Here is a clear and concise description of what the problem is:

Since inputstream.adaptive version [21.4.10](https://github.com/xbmc/inputstream.adaptive/releases/tag/21.4.10-Omega) my Kodi keeps crashing whenever I want to watch a stream from Crunchyroll, Disney+ or ZDF Mediathek (last one is Germany only, I think). There's probably others as well.
I'm not sure whether this is a inputstream.adaptive issue or a kodi issue. But since Kodi shouldn't crash (without some log indication) anyway I suspect it to be the latter.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect Kodi not to crash directly and to at least get an error message instead.

## Actual Behavior

Kodi just crashes.

## Possible Fix

Downgrade to version 21.4.9 of inputstream.adaptive.

### To Reproduce

1. Play stream from mentioned plugins (plugin.video.crunchyroll, plugin.video.zdf_de_lite, slyguy.disney.plus)
2. Wait a few seconds
3. See Kodi crash

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/polavozose.kodi
[kodi_stacktrace-21.0 Git_20240406-60c4500054-20240702-090054.txt](https://github.com/user-attachments/files/16063747/kodi_stacktrace-21.0.Git_20240406-60c4500054-20240702-090054.txt)
[kodi_crashlog-21.0 Git_20240406-60c4500054-20240702-090054.dmp](https://github.com/user-attachments/files/16063748/kodi_crashlog-21.0.Git_20240406-60c4500054-20240702-090054.dmp)

### Screenshots 
Here are some links or screenshots to help explain the problem:

none

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

eventviewer in windows shows the following:
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2024-07-02T07:06:26.9835866Z" /> 
  <EventRecordID>6648</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="21868" ThreadID="34488" /> 
  <Channel>Application</Channel> 
  <Computer>removed</Computer> 
  <Security UserID="S-1-5-21-3502866969-53193881-3033319102-1001" /> 
  </System>
- <EventData>
  <Data Name="AppName">kodi.exe</Data> 
  <Data Name="AppVersion">21.0.0.0</Data> 
  <Data Name="AppTimeStamp">6610bb6a</Data> 
  <Data Name="ModuleName">MSVCP140.dll</Data> 
  <Data Name="ModuleVersion">14.29.30133.0</Data> 
  <Data Name="ModuleTimeStamp">60ff28cc</Data> 
  <Data Name="ExceptionCode">c0000005</Data> 
  <Data Name="FaultingOffset">0000000000013020</Data> 
  <Data Name="ProcessId">0x9760</Data> 
  <Data Name="ProcessCreationTime">0x1dacc4e4a93df9f</Data> 
  <Data Name="AppPath">c:\Kodi\kodi.exe</Data> 
  <Data Name="ModulePath">C:\Windows\SYSTEM32\MSVCP140.dll</Data> 
  <Data Name="IntegratorReportId">a8962973-8449-4124-b07b-5b6452f2ae2d</Data> 
  <Data Name="PackageFullName" /> 
  <Data Name="PackageRelativeAppId" /> 
  </EventData>
  </Event>
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 (Version	10.0.22631 Build 22631)
 - Kodi version: 21.0 Omega

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Update your VC redistributable - https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Yavos** [comment]
Thank you. Problem solved.
