### ISSUE TITLE
Video title names from DLNA server use Subtitle languages as part of the name.

### ISSUE THREAD

**Issue by monohydroxy** [xbmc/xbmc#25446]
### Describe the bug
Here is a clear and concise description of what the problem is:

Movies on my DLNA server (rygel/Ubuntu) have incorrect titles.  The files that are incorrect are .mkv format with lots of subtitles.  One example of an incorrect title is:  "Romanian, Turkish, Korean, Greek, Portuguese, European Spanish, German, ...".  The name is too large to display on the screen and I can't tell the actual content.  I have not found a setting in Kodi to ignore the EXIF properties in the .mkv file and just display the file name.

Movie title names should not include the list of subtitle languages.  If someone considers this a feature, there should be a way to disable it since it creates movie titles with exactly the same names.

Here is a snippet from the output of mediainfo.  It shows 'Romanian' as a language, which Kodi adds to the file name.
 Text #20
 ID                                       : 22
 Format                                   : UTF-8
 Codec ID                                 : S_TEXT/UTF8
 Codec ID/Info                            : UTF-8 Plain Text
 Duration                                 : 48 min 50 s
 Bit rate                                 : 46 b/s
 Count of elements                        : 476
 Stream size                              : 16.5 KiB (0%)
 Language                                 : Romanian
 Default                                  : No
 Forced                                   : No

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

My expectation is to either have the movie title not include any subtitle information, or have a user runtime switch that only shows the file name and not the EXIF information or any scrapped information. 

## Actual Behavior

Displayed movie titles are based on EXIF subtitle information and there is no switch that I can find to modify this behavior for a DLNA server.

## Possible Fix

The only way I know how to fix this issue is to modify my .mkv files to manipulate the EXIF information to delete non-useful subtitles and have the movie title in the subtitle section so the entire title fits on the screen.

### To Reproduce

1.   Find a .mkv with lots of subtitles and the Language EXIF value set for each subtitle.  There is probably a clever one-liner that could create this situation with mkvpropedit.
2.  Put the .mkv on a rygel/Ubuntu DLNA server.
3.  Point Kodi at the DLNA server and look at the video/movie names.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/papoyaxuwa  -> Need to update with log...

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://github.com/xbmc/xbmc/assets/4614102/cacd1b2d-42f9-4a72-a2ab-7a54eda9cce7)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

This makes it difficult to use Kodi with some video files.  As another work-around, I will create a sub-directory name as the name of the movie.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.0.1 running on a Chromecast device.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@monohydroxy please attach a debug log.
It'd be nice to see a pcap capture too, just to confirm what your server is actually sending to kodi

**Comment by monohydroxy** [comment]
> @monohydroxy please attach a debug log. It'd be nice to see a pcap capture too, just to confirm what your server is actually sending to kodi

Thanks for the idea for a pcap capture.  I did a Wireshark capture and saw the following in an XML/HTTP response from the server:
<dc:title>
Portuguese, Norwegian, Finnish, Hungarian, Czech, Japanese, Korean, English (GB) [SDH], Italian, Latin America Spanish, German, Chinese Traditional, Swedish, Slovak, Danish, Dutch, European Spanish, French, Greek, Polish, Portuguese Brazilian, Romanian, Turkish
</dc:title>

Unless dc:title means something other than the obvious, I think this is a rygel DLNA server bug.  Feel free to close this and I'll open a rygel bug.

--MH

**Comment by enen92** [comment]
Yeah, this is not on our end: **dc:title -> The title to present to the user**

**Comment by monohydroxy** [comment]
In case anyone runs across this issue in the future, here are some breadcrumbs.

1. This issue was seen in Rygel as per this ticket:  https://gitlab.gnome.org/GNOME/rygel/-/issues/214  This ticket was closed with some Rygel fixes.  Also see this ticket:  https://gitlab.gnome.org/GNOME/rygel/-/issues/119
2. Part of the problem is in Gstreamer, which has been fixed here: https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/issues/598
3. There is some component that has not been fixed yet as detailed here:  https://gitlab.gnome.org/GNOME/localsearch/-/issues/202  This issue has been idle for the past two years. :(

As an end result, I'll see if a Rygel Beta fixes the issue or maybe just look for a different DLNA Server.

Anyway, thanks for Kodi, a great piece of software.
