### ISSUE TITLE
App Store Release?

### ISSUE THREAD

**Issue by Samuel525432** [xbmc/xbmc#25474]
I was wondering can be an App Store version of Kodi?
I mean like can you add Kodi to The App Store on iOS.

**Comment by fuzzard** [comment]
No. Kodi does not currently meet the Apple requirements for an app store submission.

**Comment by Samuel525432** [comment]
How tho like give me details about why?
I mean like why Kodi doesn’t allow the requirement on iOS App Store?

**Comment by fuzzard** [comment]
We use OpenGL/ES. you cannot submit new apps to the store with that anymore. Has been the case for several years.

**Comment by Samuel525432** [comment]
One more thing 
Is Kodi Open Source?
What I mean is Is Kodi Open Source or not?

**Comment by lrusak** [comment]
> One more thing 
> 
> Is Kodi Open Source?
> 
> What I mean is Is Kodi Open Source or not?

Use the forum for support. https://forum.kodi.tv/
