### ISSUE TITLE
[Xbox One] [MKV/H264/PCM] Sound is 300 ms delayed

### ISSUE THREAD

**Issue by COOLak** [xbmc/xbmc#25473]
---
name: Sound is 300 ms delayed
about: See below

---

### Describe the bug
Here is a clear and concise description of what the problem is: audio is delayed by approximately 300 ms, the only way to fix it is to manually set a negative "delay" (set it to 300 ms ahead), which is obviously not a perfect solution.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The sound wasn't supposed to be delayed.

## Actual Behavior

I have some high bitrate mkv videos (BDRemux) with PCM audio streams in them, and I thought the problem was perhaps the USB speed, but nope. I have them on an SSD connected through a USB 3.0 container, and VLC for Xbox plays them without any sound delay whatsoever. I would keep using VLC, but I don't like it because it doesn't have an option for changing TV framerate to the video's respective framerate.

In Kodi, it absolutely doesn't matter if I enable or disable any options whatsoever (such as: change TV framerate to match the video / on the contrary, adjust video and audio framerate for TV framerate / both / enabling or disabling passthrough, et cetera). The result is always that the sound is delayed by approximately 300 ms, so I have to manually "delay" it by negative 300 ms so that everything is synchronized.

Again, I thought it was because of the external enclosure / disk / USB poor speed, but nope, VLC doesn't have any delays when playing those files at all. I just don't wanna use VLC because it only supports 60 Hz and doesn't change the TV framerate to such of the video. Again, in Kodi, it doesn't matter if I do it or not, there is always ~300 ms audio delay unless I manually set 300 ms ahead for audio.

## Possible Fix

No idea about how it can be fixed, but I made sure it's not because of the supposedly low speed of my external enclosure / SSD in it / USB 3.0 as such, because the issue is not reproducing in VLC.

### To Reproduce

1. Play a file with the technical specifications like in the MediaInfo report below from an externally connected SSD via a USB 3.0 enclosure.
2. See that sound is delayed by about 300 ms.

### Debuglog

The debuglog can be found here: https://drive.google.com/file/d/1219MTX_QoqMIOwhT2KRrkBpbQqTjZe0l/view?usp=sharing

Please note, when creating the debug log, at first I played a few video files without any audio adjustments (and in that case the sound was delayed by 300 ms), then I globally switched the sound "delay" to negative 300 ms (i. e. 300 ms ahead) and also played a few videos after that (for a couple of minutes, sometimes with fast forwarding some of them). The issue of course was gone, but I don't think it's a cool solution to the problem that shouldn't exist.

### Screenshots
Here are some links or screenshots to help explain the problem: irrelevant in this case

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help: see below

The bug affected me in such a way so that I have to manually set audio to 300 ms ahead for all my videos that are high bitrate MKV/H264 with 16-bit PCM tracks in them.

### Your Environment
Used Operating system:

 - [V] Xbox One OS

 - Operating system version/name: Xbox One OS (latest as of July 10, 2024)
 - Kodi version: 21.0, compiled 2024-04-06 (latest from Microsoft Store on Xbox One as of July 10, 2024)

The MediaInfo of the files I play:

> Format :
> Matroska
> Format version :
> Version 4
> File size :
> 7.46 GiB
> Duration :
> 24 min 32 s
> Overall bit rate mode :
> Variable
> Overall bit rate :
> 43.5 Mb/s
> Frame rate :
> 23.976 FPS
> Encoded date :
> 2024-06-13 00:55:48 UTC
> Writing application :
> mkvmerge v85.0 ('Shame For You') 64-bit
> Writing library :
> libebml v1.4.5 + libmatroska v1.7.1
> Video
> ID :
> 1
> Format :
> AVC
> Format/Info :
> Advanced Video Codec
> Format profile :
> High@L4.1
> Format settings :
> CABAC / 4 Ref Frames
> Format settings, CABAC :
> Yes
> Format settings, Reference frames :
> 4 frames
> Codec ID :
> V_MPEG4/ISO/AVC
> Duration :
> 24 min 32 s
> Bit rate mode :
> Variable
> Bit rate :
> 38.9 Mb/s
> Maximum bit rate :
> 40.0 Mb/s
> Width :
> 1 920 pixels
> Height :
> 1 080 pixels
> Display aspect ratio :
> 16:9
> Frame rate mode :
> Constant
> Frame rate :
> 23.976 (24000/1001) FPS
> Color space :
> YUV
> Chroma subsampling :
> 4:2:0
> Bit depth :
> 8 bits
> Scan type :
> Progressive
> Bits/(Pixel*Frame) :
> 0.782
> Time code of first frame :
> 01:00:18:0000000000
> Stream size :
> 6.67 GiB (89%)
> Default :
> Yes
> Forced :
> No
> Color range :
> Limited
> Color primaries :
> BT.709
> Transfer characteristics :
> BT.709
> Matrix coefficients :
> BT.709
> Audio #1
> ID :
> 2
> Format :
> PCM
> Format settings :
> Little / Signed
> Codec ID :
> A_PCM/INT/LIT
> Duration :
> 24 min 32 s
> Bit rate mode :
> Constant
> Bit rate :
> 1 536 kb/s
> Channel(s) :
> 2 channels
> Sampling rate :
> 48.0 kHz
> Frame rate :
> 25.000 FPS (1920 SPF)
> Bit depth :
> 16 bits
> Stream size :
> 270 MiB (4%)
> Title :
> hidden
> Language :
> Russian
> Default :
> Yes
> Forced :
> No
> Audio #2
> ID :
> 3
> Format :
> PCM
> Format settings :
> Little / Signed
> Codec ID :
> A_PCM/INT/LIT
> Duration :
> 24 min 32 s
> Bit rate mode :
> Constant
> Bit rate :
> 1 536 kb/s
> Channel(s) :
> 2 channels
> Sampling rate :
> 48.0 kHz
> Frame rate :
> 25.000 FPS (1920 SPF)
> Bit depth :
> 16 bits
> Stream size :
> 270 MiB (4%)
> Title :
> hidden
> Language :
> Russian
> Default :
> No
> Forced :
> No
> Audio #3
> ID :
> 4
> Format :
> PCM
> Format settings :
> Little / Signed
> Codec ID :
> A_PCM/INT/LIT
> Duration :
> 24 min 32 s
> Bit rate mode :
> Constant
> Bit rate :
> 1 536 kb/s
> Channel(s) :
> 2 channels
> Sampling rate :
> 48.0 kHz
> Frame rate :
> 200.000 FPS (240 SPF)
> Bit depth :
> 16 bits
> Stream size :
> 270 MiB (4%)
> Language :
> Japanese
> Default :
> No
> Forced :
> No

Any tips except for manually setting a negative 300 ms delay for the audio? I don't think that's how it's supposed to work. If anything, I'm generally using the first audio track, but the issue is present in any. If you guys want a sample file, please tell me how I can send it confidentially (it's not NFSW, but yet unpublished expensive content).

**Comment by COOLak** [comment]
I've edited the issue according to the template.

**Comment by COOLak** [comment]
@thexai please kindly remove "Ignored rules" label. I have no idea how to copy it from the Xbox One, because its internal storage is protected and unbrowsable, and there's no option to change the location of the Debug Log. It saves only to the internal memory.

**Comment by COOLak** [comment]
I've finally figured how to copy the dubug log from the Xbox One, please kindly remove the Ignored Rules tag.

**Comment by thexai** [comment]
Two simple questions:

a) Have you enabled the setting "Settings / Player / Videos / Sync playback to display" ?

b) If the response is YES disable it and test again. This fix the issue or change something?

(remember reset audio adjustment to 0 ms)

**Comment by COOLak** [comment]
@thexai 

As I stated in my first message, I tried with it both enabled and disabled, unfortunately the result is exactly the same. No matter if it's enabled or disabled, also no matter if it's enabled simultaneously with "Change TV framerate to video", also no matter it BOTH options are disabled OR enabled (simultaneously or only onr of them).

**Comment by thexai** [comment]
Then I cannot reproduce on Xbox Series S with similar file (PCM audio). 

> Also, for the reference, I have the very first Xbox One model that I pre-ordered in 2013 (Day One).

Unfortunately (AFAIK) nobody on the team has a 2013 Xbox One. But since there is no similar report on the forum (and there are millions of Kodi users on Xbox) I think this is not a general issue but rather something very specific to your particular setup.

**Comment by COOLak** [comment]
> Then I recommend that you use only "adjust display refresh rate at Start/Stop" since Kodi / Xbox / TV support 23.976 Hz in your case.

That's exactly what I'm doing. Only problem is that I have to set audio 300 ms ahead.

As a last resort, if you could somehow privately send me your email, I would share an example file with you (it's a private unpublished dubbing of an anime, so I'd grant you private access via Google Drive). Maybe you could reproduce the issue on my exact file(s).

Btw, the same topic on the forum is also already opened, but another team member said that he can't understand anything because everything is in Russian. But it's easy to notice: since it's full dubbing, if you see that the charachters' mouths are perfectly aligned, then everything is OK (in my case, only with audio set to 300 ms ahead). Otherwise, you see that the voices start to sound later than the mouth opens and the other way around. It doesn't matter what language it is to notice it. 300 ms is more than enough to notice such things.

**Comment by thexai** [comment]
Even if it could be reproduced only with this "secret file", it would not be a bug but probably "bad file" or "bad rip". In any case GitHub is not for support... then continue this in forum.

**Comment by thexai** [comment]
Tested with this audio:

```
Audio
ID                                       : 2
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : A_PCM/INT/LIT
Duration                                 : 1 h 23 min
Bit rate mode                            : Constant
Bit rate                                 : 1 536 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Frame rate                               : 25.000 FPS (1920 SPF)
Bit depth                                : 16 bits
Stream size                              : 915 MiB (16%)
Language                                 : Spanish
Default                                  : Yes
Forced                                   : No
```

**Comment by COOLak** [comment]
> Even if it could be reproduced only with this "secret file", it would not be a bug but probably "bad file" or "bad rip".

.... which for some secret reason plays perfectly fine on every other imaginable hardware and software, including the ancient VLC build for Xbox One. So I wouldn't be so sure that it's not a bug.

> In any case GitHub is not for support... then continue this in forum.

Well, whatever you say then.

**Comment by thexai** [comment]
> Then I recommend that you use only "adjust display refresh rate at Start/Stop" since Kodi / Xbox / TV support 23.976 Hz in your case.
> 
> That's exactly what I'm doing. Only problem is that I have to set audio 300 ms ahead.

Log provided indicates YOU have enabled the two settings.

And "sync playback to display" is a **default disabled** setting

**Comment by COOLak** [comment]
> Log provided indicates YOU have enabled the two settings.

Would you like me to make a new log with that setting disabled? Because, as I said, it makes no difference, but I can do a new log if it helps.

**Comment by thexai** [comment]
It is not necessary, if you have already tried it it will not change things.

**Comment by COOLak** [comment]
> It is not necessary, if you have already tried it it will not change things.

Okay, but I believe you're wrong in stating that it's not a bug but a "bad file", etc, for the reasons stated above. I understand it's a voluntary project and I can't force anyone to help me. Just saying that it's definitely a bug.
