### ISSUE TITLE
Randomize button for picture player not working

### ISSUE THREAD

**Issue by Barabba11** [xbmc/xbmc#25471]
### Describe the bug
Kodi21, randomize button for picture viewer/player not working with slideshow, it always shows pictures with the same order. Other buttons (time, zoom, downscaling) works ok.

## Expected Behavior
randomize pictures during slideshow.

## Actual Behavior
the pictures are shown always with the same order

### To Reproduce
on the player option>pictures>activete the randomize, assing a folder to the picture viewer, open a picture, press spacebar and notice the order.

### Debuglog
no need for log, there isn't any error.

### Screenshots 
no need, already clear

## Additional context or screenshots (if appropriate)
nothing

### Your Environment
Windows10, Kodi21

**Comment by wutschel** [comment]
Randomizing the playback of a picture playlist aka slideshow definitely works via JSON API. But: You cannot switch randomizing off anymore w/o starting a new slideshow.

Commands used for this: 
- To start a slideshow with or without shuffle: `Player.Open` with `path/recursive/random`, whereas `random=YES` or `=NO` does the obvious
- To enable shuffle for an existing slideshow:`Player.SetShuffle` with` shuffle/playerid`, whereas `playerid = 2`

**Comment by Hitcher** [comment]
> on the player option>pictures>activete the randomize, assing a folder to the picture viewer, open a picture, press spacebar and notice the order.

That's not how you start a slideshow.

Once you've enabled 'Randomise' select 'View slideshow'.

![screenshot00002](https://github.com/xbmc/xbmc/assets/133808/2c6f712f-0e5e-4412-bef9-e234c4abef78)

**Comment by Barabba11** [comment]
> Randomizing the playback of a picture playlist aka slideshow definitely works via JSON API. But: You cannot switch randomizing off anymore w/o starting a new slideshow.
> 
> Commands used for this:
> 
>     * To start a slideshow with or without shuffle: `Player.Open` with `path/recursive/random`, whereas `random=YES` or `=NO` does the obvious
> 
>     * To enable shuffle for an existing slideshow:`Player.SetShuffle` with` shuffle/playerid`, whereas `playerid = 2`

Thank you all of you for your kind suggestions!
May I kinldy ask you, how to send these commands by JSON? Especially ho to add parameter to randomize, Thank you really a lot!
For now I'm using this 
```
return {
    payload:
    {
        "method": "Player.Open",
        "args": {
            "item":
                {
                    "folder": "smb://192.168.101.100/log"
                }
        }
}};
```

**Comment by wutschel** [comment]
I suggest you look into the API description to understand the pattern, especially Player.Open does have various possible parameter set. Link: https://kodi.wiki/view/JSON-RPC_API/v13

In your case:
```
"item":
    {
        "path": "smb://192.168.101.100/log",
        "recursive": your-wish,
        "random": your-wish,
    }
```

**Comment by Barabba11** [comment]
Thank you, I've tried and it works, but only with path:// and not more with directory://, in that case now it returns an error, interesting. 
I may say that the main issue is overcomed, but it randomizes the files at first time, and when it loops again it will respect the same order. I may overcome it loading again the forlder after some time, ok, but just to know if there is, it would be better to shuffle, there is a way also for it eventually? Thanks

```
return {
    payload:
    {
        "method": "Player.Open",
        "args": {
            "item": 
                {
                    "path": "smb://192.168.101.100/log",
                    "random":true,
                    "recursive":true
                }
        }
}};
```

**Comment by wutschel** [comment]
> Thank you, I've tried and it works, but only with path:// and not more with directory://, in that case now it returns an error, interesting.

Well, it behaves as documented on the API page which I linked in my former post. 

> is a way also for it eventually?

Not to my knowledge. Restarting freshly seems to be the only way.

**Comment by wutschel** [comment]
Can be closed as resolved as far as I can see.
