### ISSUE TITLE
Slideshow on Android TV, screensaver kicks in and frozes Kodi

### ISSUE THREAD

**Issue by Barabba11** [xbmc/xbmc#25499]
### Describe the bug
Kodi 21 on recent Android TV (Google), I start a slideshow with JSON API or manually with TV remote, after about 5 min the Google OS scrennesaver kicks in and frozen kodi. This doesn't happen when video is played, but when is on pause yes. I've disabled already the power energy saver on Kodi

## Expected Behavior
When Kodi is showing slideshow, it has to continue showing it. As it not apused when a video is displayed maybe there is a way to tell OS Kodi is not simply sleeping/waiting for commands. As the image player is separated process than video player, maybe this is just a feature to add/implement on image player.
As a program like Fotoo (slideshow) works on that TV without stop, I suppose also Kodi can do it.

## Actual Behavior
Google TV OS thinks that kodi is just doing nothing and it kicks in. If I push a JSON to play a new path:// (folder with pics) I can see the HTTP server logging Kodi requests, but only loading files ad beginning to count them, and lot loading them separately each time a new slide is displayed. The process is actrive, responsivem but the screensaver is on. After more time the process goes totally bckgrounded ad it doesn't respond more to commands.

## Possible Fix
Tell OS that Kodi is active process when showing slideshow, even if user doesn't touch the remote

### To Reproduce
on Android tv start a slideshow and wait the screensaver kiks in thinking kodi is inactive.

### Debuglog
I don't think it's relevant, no errors here

### Screenshots 
no need

### Your Environment
Android Google TV (on recent TCL TV)

**Comment by Barabba11** [comment]
Mates, I think this is a common problem probably with all recent Android TV, the latest versions of android are mainly aggressive with apps to put them in the corner, save processor and free RAM. I suppose Kodi was developed with earlier versions of Android whch didn't have this problem. Sorry to don't upload the screenshor or attach log, if you need I'll do it, anyway I guess you need a recent android tv to find a workaround. Thanks

**Comment by sarbes** [comment]
No log.

**Comment by Barabba11** [comment]
To simulate you just need an android google tv, install Kodi, start kodi and slideshow and wait that the screensaver kicks in.
No log needed, it's not an error, it's a question to elevate Kodi process at a level that TV don't think that Kodi is not working and put it in background.
The question is if you wat to face the problem or put the dust under carpet..
