### ISSUE TITLE
In brazuca play / live tv / pluto tv / movies / run time when clicked it closes the Kodi application on Windows 10.

### ISSUE THREAD

**Issue by serial02** [xbmc/xbmc#25494]
Hey guys

No brazuca play / tv ao vivo / tv pluto / filmes / run time ao ser clicado fecha o aplicativo kodi no windows 10. 

https://imgur.com/dVf55fk

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ X] Windows 10
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
No support for piracy add-ons.
