### ISSUE TITLE
Kodi Freezes on Kodi Startup Xbox One S and Xbox Series S

### ISSUE THREAD

**Issue by KweenMother** [xbmc/xbmc#25501]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi installed on Xbox Series S and Xbox One S, connected to Yaber Y30 projector, Samsung TV and TCL TV
Kodi with Fentastic, Fen Light, YouTube and Trakt

###Whenever I start up Kodi on any Xbox  (2 Xbox One S's and 1 Xbox One S) it freezes and you must quit Kodi and restart, or it crashes and takes you back to Xbox home screen.  The issue will happen again on restart. The only option is to select a different tab while Kodi is loading, such as "Addon" of "TV Shows".  Only Moving the "cursor" around seems to stop Kodi from freezing upon startup.
I don't know if it's the skin, a setting, or addon

I've never posted a log before, so I hope this is correct:

Expected Behavior:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should start and load up widgets

## Actual Behavior

Kodi freezes and you must quit and restart. Or kodi crashes and takes you back to xbox home screen

## Possible Fix

If you select another tab while Kodi is loading widgets it won't freeze. If you select "TV Shows" or "Addons" while Kodi is loading 90% of the time Kodi won't freeze.

### To Reproduce

1.
2.To reproduce the bug, I just start Kodi on the xbox of my choice.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/awobekenin

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
Xbox Series S and Xbox One S
 - Operating system version/name:
 - Kodi version:
Omega 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
Due to the usage of [banned piracy add-ons](https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons) we won't look into your case. Please reproduce with a clean Kodi installation to get support.

**Comment by thexai** [comment]
GitHub is for track code bugs and this is a "support request". As commented clean these banned add-ons and this should fix your issue by itself. 

If you need more help use forum instead: https://forum.kodi.tv/forumdisplay.php?fid=282
