### ISSUE TITLE
Most addons not working on kodi android or linux

### ISSUE THREAD

**Issue by boobbopoppo** [xbmc/xbmc#25504]
### Describe the bug

Many kodi add ons (even from official repo) do not work on android. 

The installation goes fine and no dependencies are flagged as missing, but upon opening any of these add ons, i just get an error that invites me to check the logs.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Addons should correctly work on kodi on android devices.

## Actual Behavior

Upon opening an addon it crashes on launch with an error message that invites me to check the logs (tried with leia, matrix and nexus, same result).
tried on 3 different android devices:
1. oneplus 6t with lineageOS 21
2. ayn odin 2 with android 14
3. orangepi 5b with android tv 
results are the same.

i tried a linux device as well:
1. acer aspire 5 with ubuntu 24.04
and i was surprised to see it doesn't work there either, with the same error.

### To Reproduce

1. open kodi app on android
5. install an addon that uses python
6. try to open it

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/qoromaqequ

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I was trying to get the plex add on to work on kodi.
before that i had the same issue with PlexKodiConnect, except that the addon wouldn't wven give me the option to open it, so i can't have logs for that.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.0, 20.0, 19.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Hitcher** [comment]
That's not a debug log. Enable debugging and restart Kodi.

**Comment by neo1973** [comment]
I think this one for the forum. We know addons are working on Android and Linux, if it doesn't do for you something with your setup is wrong. Please seek support from https://forum.kodi.tv/.
