### ISSUE TITLE
Shield Based Controllers No Longer Working

### ISSUE THREAD

**Issue by digitek007** [xbmc/xbmc#25545]
---
name: Shield Based Controllers Not Longer Working
about: Button mapping potentially impacted by Kodi or Shield-Android update

---

### Describe the bug
Here is a clear and concise description of what the problem is:

I'm following up on an issue that looks very similar if not identical to https://github.com/xbmc/xbmc/issues/24502, which was closed earlier this year and was filed around the time we noticed the same issue on our Shield+KODI setup.

We've gone through a periodic attempts to fix this, including re-install of Kodi a few times which is painful as it loses all of our SMB shares and video watch history.  So we're finding ourselves using Kodi less and less as we've lost a lot of core functions key to streaming.

Essentially, a fresh install of Kodi on Shield today installs this version:
21.0 (21.0.1)
Git: 20240409-7e760d1063
Compiled: 2024-04-09

This is a set top box with a standard Shield controller, although a bluetooth controller yields the same issue.

## Expected Behavior
Standard Kodi controller behavior leveraging the full capability of analog triggers, joysticks, and various buttons on the Shield controller that closely match an XBOX or KODI picture in the "Default Controller" picture

## Actual Behavior

Essentially sometime around January the majority of buttons on our controller stopped doing the things they used to do.  The triggers no longer scrolled menus, the joysticks on the front no longer controlled volume, and the "B" key no longer stopped the video, and instead overlays a menu while the video continues playing in the background.  Even to exit KODI B used to work for that, now we have to manually navigate down to the Power icon and "Exit".  

Attempting to re-map the controller in the settings screen used to allow us to re-map or map a new controller.  But now attempting to edit any button results in no button detected (there is just a 4 second countdown after letting it idle for a bit, and pressing the A key resets the time out).

We've tried a fresh install thinking perhaps some old add-on or data that is lingering around may be causing it, but the same issue persists.

## Possible Fix

I was curious if this is indeed a similar issue to the mentioned bug above, and if there is a remedy - again for the shield set top box using only the controller to re-install / configure applications.  If there is a more complex way (editing files, side-loading over USB) I'm happy to try that as well, but may need further instructions on how to do that on a Shield.

### To Reproduce
Use an NVidia Shield or Shield Pro.  Use the NVidia wireless controller or 3rd party wireless controller ex 8bitdo 2.4g
Install KODI
Try to use any of the standard buttons, triggers to play a video
Try to map any of the keys differently
Try to configure the triggers
Many functions do not work and/or cannot be re-mapped.

### Your Environment
Used Operating system:
 - [x ] Shield TV / Android

 - Operating system version/name:
 - Kodi version:
21.0 (21.0.1)
Git: 20240409-7e760d1063
Compiled: 2024-04-09

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by digitek007** [comment]
I (re)attempted to follow the template, it is perhaps possible I was missing some lines in the beginning.  I'll check in again to see if any further changes are needed...

**Comment by sarbes** [comment]
There is no debug log.

**Comment by digitek007** [comment]
Thank you for the quick responses.  A couple updates, as I've given this a couple more hours try to try and help.

1) This is a set top box (Shield Pro).  I'm entirely unsure how to install new versions of Kodi - the one I installed is from the app store included with the Shield.

2) I tried to enable Debug logging, then go into controller setup and try to map keys in hopes the items would be logged

3) Unfortunately, I have no idea how to get this log off the device onto something I can share here.  If I use the "File manager" feature of KODI, I get errors whenever I try copying the log file to any other locations (perhaps because it is in use?).  I've also tried using a 3rd party app "XPlore" to manually copy files while Kodi is not running.  Unfortunately the data folder where it appears Kodi keeps it's files in a ".kodi" folder cannot be browsed, even if I grant the app access (the app folder appears empty).

So I'm at a loss on how to A) install a new version of Kodi without going to the app store, or B) copy files off the current version of Kod to further help with debug logs.

Any further guidance would be appreciated, this is 100% reproducible and matches almost exactly the symptoms described in a bug earlier this year, https://github.com/xbmc/xbmc/issues/24502.

Thank you again!
Sean

**Comment by garbear** [comment]
A) First you need an apk with the latest Android joystick fixes. Grab one from https://github.com/garbear/xbmc/releases. If you can download it on the shield, install it. If not, download on a computer, transfer to the shield, and install it.

B) There's a log uploader add-on

**Comment by digitek007** [comment]
Great thank you both for the comments.  Here is the location of a log using the log updated add-on:
https://paste.kodi.tv/acuhofayuv

Steps I took when adding this log:

- Enabled the log updater add-on
- Enabled debug logging in settings
- When to Input settings, tried to edit the map for the Kodi controller
- Exited out
- Used the log updated add-on

I do see a lot of "CPeripheralBusAndroid: ignoring input event for unknown input device with ID 13" in the event log, so maybe that is relevant?

Thanks for all the help!

**Comment by garbear** [comment]
The problem in the log is:

```
warning <general>: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 13
```

I committed a fix for this in https://github.com/xbmc/xbmc/pull/25176

Can you try with the latest nightly that includes this fix, or one of my [test builds](https://github.com/garbear/xbmc/releases)?

**Comment by digitek007** [comment]
Thank you for the analysis - I can try that, again this is on a set top box (Shield), so would that involve side loading through USB?  I've not installed any applications on Shield that way, and would need to check which build to use (I'm pretty sure it's an ARM build, but not sure if v7 or v8/64-bit).  Do you know if the above tag I shared included this fix?

21.0 (21.0.1)
Git: 20240409-7e760d1063
Compiled: 2024-04-09

**Comment by garbear** [comment]
You'll want the v8/64-bit apk. I checked and can confirm that 21.0 does not contain the fix (though I'm awaiting feedback on the fix and plan to backport it. I've already opened the backport PR: https://github.com/xbmc/xbmc/pull/25389)

**Comment by digitek007** [comment]
Thanks for the update and help!  I've made some progress on this, and I believe this may have fixed the issue, but I'm now finding that I'm unable to add the smb:// shares I used for testing this - the "SMB Client" section of settings / services is no longer present, and neither is the option to enable SMB in the "Virtual File Systems" add-on that usually has it.  Is there something else I need to do to enable samba shares?  Attempting to add one manually results in a connection error.  Once I resolve this, I should be able to confirm the controller works as it used to.

For reference, a fresh install of Kodi from the Shield TV's "App Store" does have SMB client there by default, so it appears there is some difference with a side loaded APK off the v8/64-bit release page or test build I side-loaded.

**Comment by digitek007** [comment]
As an additional update after some more testing, the "nightly" build does have SMB supported, I was able to add video locations and verify that the controller now works again as expected - THANK YOU!!

The SMB client restriction seems to be specific to the retroplayer test build location above, so for now I'm using the nightly.

I'm curious when this may be posted to the official version accessible to the Google Play store on Shield / Shield Pro as others reported the same issue and may welcome a fix through that vs side loading an APK, but at least we are unblocked for now.  Thanks for the follow up!

**Comment by garbear** [comment]
@digitek007 Thanks for confirming that controllers are working with the nightly fix. This evidence will help in the backport so that v21 will get the fix.

Do you have any remotes to test? The reason I'm caution is because the controller fix can affect remotes, and we don't want any breakage when we backport.

Regarding SMB, Android doesn't use the add-on (vfs.smb2), it is built in. I backported some CMake stuff to my RetroPlayer builds, which must be causing samba to be not found when building. I've been playing around with possible fixes, and my last two builds each use a different approach for SMB. You verified that SMB is broke in my 2024-07-29 build. Can you try the one before it, 2024-07-10? It's right below the latest at https://github.com/garbear/xbmc/releases. Thanks!

**Comment by digitek007** [comment]
Happy to help!

The three remotes/controllers I use for Kodi on Shield are the game controller which now works, the shield remote, and an additional USB controller (8bitdo 2.4g).  All of them still work properly, and the USB controller can now be properly set up (the controller configuration recognizes all keys to set it up).  

I will try to test the Samba out later this week, hopefully I can do that without uninstalling the the nightly build? Setting up the SMB shares is cumbersome on a controller.

**Comment by garbear** [comment]
> The three remotes/controllers I use for Kodi on Shield are the game controller which now works, the shield remote, and an additional USB controller (8bitdo 2.4g). All of them still work properly, and the USB controller can now be properly set up (the controller configuration recognizes all keys to set it up).

Good data, thanks

> I will try to test the Samba out later this week, hopefully I can do that without uninstalling the the nightly build? Setting up the SMB shares is cumbersome on a controller.

Because my builds are signed with the same key, you should be able to sideload without clobbering your userdata, but Android can enforce version downgrade/sidegrade effects that may still clobber your userdata. Apologies if you have to setup to SMB multiple times with a controller, but it's for the greater good (for the greater good, for the greater good)

**Comment by garbear** [comment]
Yes, the 7-10 build has a samba hack to fix building on my Linux box. The 7-29 build reverts back to the state of upstream. Can you give the 7-29 build a try?

**Comment by digitek007** [comment]
Confirmed that installing your 07/29 build on top of the nightly retained SMB support.  For now I'll leave this one on so I guess you'll get some free testing on it as well, let me know if I should re-install the default Omega nightly due to some other issue I should avoid.  Thank you!

**Comment by garbear** [comment]
Glad to hear the hack I reverted was the cause. Everything else should track the nightly Omega build pretty close, but if you find anything else off let me know!

If controllers work can you close the issue? Thanks!

**Comment by digitek007** [comment]
I'll go ahead and close it - ideally this is fully closed when the release is made available to Shield TV, but as I understand it these tickets are to track the fix going into the right mainline/branch, not necessary the end distribution.  Thank you for the follow-ups great to have our controller working and enabling all the best in Kodi again!

**Comment by digitek007** [comment]
Closing per discussion
