### ISSUE TITLE
Guide window is empty after PR #25447

### ISSUE THREAD

**Issue by smp79** [xbmc/xbmc#25540]
### Describe the bug
Here is a clear and concise description of what the problem is:

How it looks now after #25447 
![IMG_20240723_165329198](https://github.com/user-attachments/assets/e609c0dc-30b8-4f6f-bcae-e3e8cbfcddd3)

How it looked before that PR:
![IMG_20240723_165755511](https://github.com/user-attachments/assets/e3dbb846-322c-472e-86a8-62a0c5bbba65)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Previous behavior was better.

## Actual Behavior

Current behavior looks wrong.

### To Reproduce

1. Tune to a channel with EPG and press G keyboard button.
2.
3.

### Debuglog

The debuglog can be found here:
[Debug log](https://gist.githubusercontent.com/smp79/c0c3651d7cfec13c12d6d2baf0c435ab/raw/2fb2e516e2387fa7c65372e8d09fe04187370f2b/gistfile1.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC
 - Kodi version: current master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Definitely not related to the above mentioned PR. That PR has no influence on Guide window behavior.

**Comment by ksooo** [comment]
Confirming the issue and the causing PR.
