### ISSUE TITLE
AirPlay broken on master

### ISSUE THREAD

**Issue by psires** [xbmc/xbmc#25555]
### Describe the bug
Here is a clear and concise description of what the problem is:

When running with latest trunk builds the AirPlay/AirTunes service is not being detected by any of apple devices (tested on both iphones and mac's). 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

AirPlay service detected on all of apple devices.

## Actual Behavior

AirPlay is not detected by: iphone 8, iphone 11, iphone 12, macmini, macbookpro

## Possible Fix

The problem seems to be caused by this commit:
commit bfc40840fe91b79a4592ed25efa8552097519d31
Author: Jose Luis Marti <joseluis.marti@gmail.com>
Date:   Sat Mar 23 23:06:06 2024 +0100

    Use unique service names in Zeroconf registration

this change makes the AirTunes service to advertise with a name that is not being picked up properly by Apple devices (something like "kitchen airtunes") where it used to advertise a mac address and name of host ("B827EBFC7712@kitchen").

By reverting the change with the below diff I get my Kodi detected again:

diff --git a/xbmc/network/AirTunesServer.cpp b/xbmc/network/AirTunesServer.cpp
index 79b08a2e77f..0add358ba30 100644
--- a/xbmc/network/AirTunesServer.cpp
+++ b/xbmc/network/AirTunesServer.cpp
@@ -627,8 +627,7 @@ bool CAirTunesServer::StartServer(int port, bool nonlocal, bool usePassword, con
     txt.emplace_back("am", "Kodi,1");
     txt.emplace_back("vs", "130.14");
 
-    CZeroconf::GetInstance()->PublishService("servers.airtunes", "_raop._tcp",
-                                             CSysInfo::GetDeviceName() + " airtunes", port, txt);
+    CZeroconf::GetInstance()->PublishService("servers.airtunes", "_raop._tcp", appName, port, txt);
   }
 
   return success;

### To Reproduce

1. Build trunk (last test on ebf95c50e9ca5060e4d256b41e81c0f94757d122) with AirPlay support enabled
2. Run Kodi (Airplay enabled by default) 
3. Try to stream to the Kodi device from any Apple device

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: ArchLinux
 - Kodi version: trunk build

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
cc @joseluismarti

**Comment by psires** [comment]
Adding my current patch in a more readable way:

[airtunes_fix.patch](https://github.com/user-attachments/files/16413799/airtunes_fix.patch)

**Comment by joseluismarti** [comment]
Right, it seems to work only if the service name is in the format: mac-address@name, as it was initially.

Can you make a PR with this change? No problem to do it myself.
