### ISSUE TITLE
Kodi WebOS Ver 21 some Problems (Updated to Rules!)

### ISSUE THREAD

**Issue by crazybanane** [xbmc/xbmc#25568]
## Bug report
-Black screen movie playback
-Sound Delay wont work
WS-Discovery shut automaticly off 

### Describe the bug
Here is a clear and concise description of what the problem is:

When i look movies with Kodi and Pause it for a long time and resume screen left black audio plays normaly. This happen also if i stop a movie and will resume it out of Home menu also if i search in the timeline for more than 5min movietime for and backwards.
This happens on different file containers but not on every movie. actually most Problems on h.264
Sound Delay wont react if i set different delay times.
I have to set WS-Discovery on every Startup to on.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] tvOS/webOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LG webOS 4.5  (5.5.0-1107)  Software version: 04.50.56 rooted
 - Kodi version: 21.0 (homebrew app version)

**Comment by sarbes** [comment]
No response.
