### ISSUE TITLE
Operation in parallel to UxPlay

### ISSUE THREAD

**Issue by DaCHack** [xbmc/xbmc#25586]
### Describe the bug
Here is a clear and concise description of what the problem is:

Cross-referring to this issue with UxPlay: https://github.com/FDH2/UxPlay/issues/319

I want to use KODI on a VM with limited resources, thus running KODI almost standalone without any desktop environment.
"Almost" just because I would like to run UxPlay in parallel since KODI is lacking iOS screen sharing support.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Could you please point me to how KODI manages screen output without desktop environment, ie. in standalone mode and any ideas on what I need to do in order to ideally let UxPlay simply overlay KODI while screen is shared and then clearing it for KODI again afterwards?

Huge thanks!

## Actual Behavior

Both can run together, but when sharing my iOS screen the output seems to be hidden behind the KODI screen (showing flawlessly without KODI running).

## Possible Fix

Include UxPlay or provide guidance on how KODI manages screen output and how a single additional application can by overlaid

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
Not a bug report.

**Comment by DaCHack** [comment]
Let me phrase it different: There are 2 bugs:
- Code: KODI blocks the screen for any additional framebuffer output
- Documentation: no documentation is given how KODI manages display output and how additional output can be shown in parallel to KODI
