### ISSUE TITLE
.edl scene marker action is invalid

### ISSUE THREAD

**Issue by rayes0** [xbmc/xbmc#25591]
### Describe the bug
Here is a clear and concise description of what the problem is:

Specifying `2` as the action for an .edl file does not work in kodi, however it is listed as supported according to the wiki entry (https://kodi.wiki/view/Edit_decision_list#MPlayer_EDL)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The line should be parsed as valid and a chapter should be created with a new scene marker upon playback.

## Actual Behavior

The line parses as invalid.

### To Reproduce

Testing with an edl file containing the following:
```
46.67 129.96 2
```

The file has no effect, and gives the following error in the log:
```
warning <general>: ReadEdl - Invalid action on line 1 in EDL file: [REDACTED].edl
```

However, the rest of the actions work fine:
```
46.67 129.96 0 <-- works
46.67 129.96 1 <-- works
46.67 129.96 3 <-- works
```

### Debuglog

The debuglog can be found here:
```
warning <general>: ReadEdl - Invalid action on line 1 in EDL file: [REDACTED].edl
```

### Screenshots
Here are some links or screenshots to help explain the problem:

n/a

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi Media Center 21.0 (21.0.0) Git:20240406-60c4500054

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
I am unable to replicate the problem.

I have tried:
`46.67 129.96 2 (your timestamps)`
`129.96 2`
`1200.00 2`
`00:20:00.00 2`

All 4 methods worked for me.

```
debug <general>: CEdl::ReadEditDecisionLists - Checking for edit decision lists (EDL) on local drive or remote share for: F:\HTPC Movies from TV\A Time to Kill (1996)\A Time to Kill (1996).mkv
debug <general>: CEdl::AddSceneMarker - Inserting new scene marker: 00:02:09.960
debug <general>: CEdl::ReadEdl - Read 0 edits and 1 scene markers in EDL file: F:\HTPC Movies from TV\A Time to Kill (1996)\A Time to Kill (1996).edl
```

Line 911... https://paste.kodi.tv/mefelenamo.kodi

**Comment by rayes0** [comment]
My apologies, it seems I got confused from my debug log that the specific edl file was causing problems, but the problem was actually from another edl file which was indeed invalid for a different reason. Just tested it and it does work fine, sorry for the extraneous confusion.

**Comment by KarellenX** [comment]
No problems. Glad it is working. :)
