### ISSUE TITLE
Kodi freezes after playing a second video file.

### ISSUE THREAD

**Issue by AerYareli** [xbmc/xbmc#25595]
### Describe the bug
Here is a clear and concise description of what the problem is:

The second video played freezes Kodi, forcing me to unplug it and plug it back in to restart.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

A second video will play normally.

## Actual Behavior

The first video after restarting plays fine, however once the playback stops and I select a new video, the GUI will freeze while I can still hear the audio for a few seconds, then the audio stops as well. Kodi itself will now be frozen completely, requiring an unplug.

### To Reproduce

1. Play any video.
2. Stop playback.
3. Select same or different video

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/afekexefij.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
Due to the presence of banned addons we won't investigate this (see https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons for the full list of addons). Reproduce with a clean install and provide a new log. Once done this ticket can be reopened.
