### ISSUE TITLE
Playback Error with Show Information default action and Play Next Item automatically 

### ISSUE THREAD

**Issue by adamosborne83** [xbmc/xbmc#25603]
> Describe the bug

when both the Kodi/Settings/Media/Default select action is "Show Information" and Kodi/Settings/Player/Videos/Play next video automatically "Episodes" (or Movies) is enabled, selecting "Play" from the info window, the video does not play.  the attempt calls `<plugin id>/VIDEO_TS/VIDEO_TS.IFO`? this started with Omega. this seems independent of skin.

in Nexus it worked "correctly" or at least attempted the plugin defined listitem url, `<plugin id>/?action=...`.

> Expected Behavior

the selected item plays

> Actual Behavior

no video plays and ui returns to the directory list.

> Steps to reproduce the behavior:

1. install [teststream video plugin](https://github.com/jurialmunkey/plugin.video.teststream) @jurialmunkey or use your own
2. set default play action to "Show Information"
3. set Play next video automatically to Episodes/Movies
4. select video item which opens "Show Information"
5. select "Play button"

> Debuglog

https://paste.kodi.tv/qaxedudiko

> Your Environment

Android Amazon FireTV devices
windows
windows 10
kodi 21

**Comment by adamosborne83** [comment]
https://paste.kodi.tv/viduzizoho

**Comment by ksooo** [comment]
Should be fixed in latest master
