### ISSUE TITLE
Allow Userdata folder to be changed

### ISSUE THREAD

**Issue by royharoush** [xbmc/xbmc#25604]
## TODO

Have a the ability to choose a different folder in the file system that will host the userdata folder, instead of the /android/data folder

### Context
In android 11 and 12 , it is no longer possible to read\write into the kodi data folders. 
this breaks the ability to use the backup addon, as well as the ability to move files from an existing kodi installation to restore. 
On a on perosnal note, i just bought a streamer because the TCL TV that i had didn't allow restoring my very compelx configuration. 
then i found out the streamer also didn't allow to restore or touch those files. 

It should help any advanced user using the backup addon or people replicating their configurations to friends and family (i've basically given my configuration that way to around 30 people). 

### Possible Implementation
In file explorer, add a context menu that will designate a selected option to hosted the userdata files. 

### Additional context, screenshots or links
very easily tested, just try using backup on an android TV 11\12 

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by fuzzard** [comment]
Feature requests can be made on the forums.
