### ISSUE TITLE
[windows] HDR + audio passthrough = crashes/issues

### ISSUE THREAD

**Issue by verne2k** [xbmc/xbmc#25633]
### Describe the bug
Here is a clear and concise description of what the problem is:

when kodi switches HDR on and audio is set to passthrough, weird stuff happens, like audio driver crashes, video freezes, video/audio signal loss, kodi crash etc

i have a setup like this:

windows mini pc (i3 13100) connected to the TV (samsung Q80A) via DP-HDMI (there is a DP to HDMI converter in the middle).
The TV is then connected via eArc to the AVR (yamaha rx-v685)

normally, everything works fine, except when playing files that are both HDR and a format that is passthrough-able (like TrueHD+Atmos, DD+ Atmos etc)

in such cases, it seems that when switching HDR on the GPU and/or TV takes too much time to get back up (signal is briefly lost) but kodi in the meantime pushes through with playback, and this causes all sorts of issues

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

resolution/refresh/hdr should be adjusted and playback should start with passthrough audio working

## Actual Behavior

one of these usually occurs:

- resolution, refresh and HDR are correctly set, passthrough audio crashes the audio driver. Audio not working until pc is rebooted.
- resolution and HDR are correctly set, but refresh is set to my default (120Hz). passthrough crashes the audio driver and reboot is needed.
- resolution is correctly set, but HDR and refresh are not. audio driver crash, reboot needed.
- complete loss of video and audio signal. video may or may not come back after 20/30 seconds. Audio driver may or may not be crashed.
- video signal is totally garbled/glitched. audio driver crash.

very rarely, like 1 in 20 times:

- resolution and HDR are set correctly, refresh is default, audio passthrough works.

extra rarely, like 1 in 30 times
-everything is set perfectly and audio passthrough works

## Possible Fix

i suspect the HDR switching may be best suited after the resolution change and before opening audio sink... that and/or a delay might be needed to give the equipment time to get back up

### To Reproduce

1.  play a test video that is 4k, HDR and TrueHD with passthrough enabled
2.
3.

### Debuglog

The debuglog can be found here:

here are several logs:

- resolution/refresh/hdr are fine, passthrough audio crash: https://paste.kodi.tv/oraworedic.kodi
- resolution/hdr are fine, refresh is wrong and passthrough audio crash: https://paste.kodi.tv/orohogohop.kodi
- resolution/hdr fine, refresh wrong, audio crash and video freeze: https://paste.kodi.tv/fuwamuloto.kodi
- resolution/hdr fine, refresh wrong, audio passthrough working: https://paste.kodi.tv/awukulujem.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro
 - Kodi version: 21.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Closed for now as this is not a Kodi bug but setup/HW issue or limitation. 

Continue in forum:  https://forum.kodi.tv/showthread.php?tid=378497&pid=3207084#pid3207084

**Comment by CrystalP** [comment]
OP wrote in the forum that when Kodi doesn't switch resolution and HDR mode, the playback of video and audio is flawless.
It sounds like something in the switching doesn't work well with the driver/hardware combination. Additional delay knob needed maybe?
It's difficult to fix without similar hardware and not a priority as it seems to work for the vast majority.
