### ISSUE TITLE
kodi-21.0-Omega-arm64-v8a.apk

### ISSUE THREAD

**Issue by Askank-Man** [xbmc/xbmc#25641]
---
name: Problem report
about: Create an extensive report to help us document a problem

---

### Describe the bug
Here is a clear and concise description of what the problem is:

Android 14 reports a Bug in Kodi app and recommends to Clear Cache to resolve issue which helps to restart application.

Program is unstable in Android 14 and eventually results in a crash with a black screen. Reinstalling the app including any version repeats the same bug in Android 14.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi Omega 21.1 runs without Android bug detected.

## Actual Behavior

Kodi Omega 21.1 crashes at startup and Android 14 reports a Bug and attempts to resolve by clearing cache.

## Possible Fix

Check stability in Android 14

### To Reproduce

1.Install Kodi
2.Run Kodi and add a repository
3.Close and run again after 1 day.

### Debuglog

The debuglog can be found here:
Debug log to be added.

### Screenshots
Here are some links or screenshots to help explain the problem:

![Screenshot_20240820_120613_Kodi](https://github.com/user-attachments/assets/8fdf154d-e72b-4fd5-b754-6c27a92e7c33)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android 14 running kodi-21.0-Omega-arm64-v8a.apk
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 14
 - Kodi version Omega 21.1.0

**Comment by Askank-Man** [comment]
Updated bug report template.

**Comment by matthuisman** [comment]
You say 21.1 but your issue title has 21.0

**Comment by sarbes** [comment]
No log provided.
