### ISSUE TITLE
An odd sound issue in Kodi 21.1

### ISSUE THREAD

**Issue by yairmohr** [xbmc/xbmc#25640]
### Sound key changes
On version 21.1.0 (Linux Flatpack on Linux Mint 22), I have noticed sound is unstable, in a manner that makes music change keys (so the notes move gradually up and down, like a legacy media format, i.e a record player, having an unstable spin speed). It doesn't happen on any other software with the same files.

## Expected behavior
Stable sound.

## Actual behavior
Key fluctuations.

## Possible fix
No idea.

### To reproduce
Open any file (or at least any MKV/MP4 AVC/HEVC file I've tried) and listen to changes in sound key.

### Your Environment
 - Linux Mint 22,
 - Kodi version 21.1.0 Flatpack

**Comment by sarbes** [comment]
No response.
