### ISSUE TITLE
Kodi crash after installing Arctic: Zephyr - Reloaded skin

### ISSUE THREAD

**Issue by elibenyaacov** [xbmc/xbmc#25650]
### Describe the bug
Kodi is crashing when I switch from one profile to another.

### To Reproduce
1. Fresh install.
2. Add a 2nd profile.
3. Install skin `Arctic: Zephyr - Reloaded`
4. Log out of one profile and logon to 2nd profile or switch back and forth between profiles. 
5. Kodi crashes on 1st/2nd/3rd profile change.

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/xopizunizo.kodi

## Additional context or screenshots (if appropriate)
I think the problem is with one of the following add-ons: `Embuary Helper`/`Embuary Info`/`TheMovieDB Helper`.
Claude says it might be python related.

### Your Environment
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: ArchLinux / 6.6.47-1-lts (x86_64) / KDE 6.1.4 / X11
 - Kodi version: 21.1.0

**Comment by Hitcher** [comment]
If it's only happening with this skin please report it in the Arctic Zephyr section of the forums.

**Comment by elibenyaacov** [comment]
> If it's only happening with this skin please report it in the Arctic Zephyr section of the forums.

I don't think it's the skin fault, cause I get the same crashes when installing one or more of the above mentioned add-ons (without installing the skin). I just couldn't find out who exactly is the culprit so I though it would be easier to report like that.

**Comment by matthuisman** [comment]
Addon's shouldn't be able to crash Kodi ideally.

**Comment by neo1973** [comment]
Chances are high that this is ##24440. To confirm, can you please launch Kodi under GDB, say yes when it asks to load debug info using  debuginfod and reproduce the crash?

**Comment by elibenyaacov** [comment]
> Chances are high that this is ##24440. To confirm, can you please launch Kodi under GDB, say yes when it asks to load debug info using debuginfod and reproduce the crash?

how exactly do u do that? running kodi under gdb?

**Comment by KarellenX** [comment]
Could it be related to this?... 
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/1233

**Comment by neo1973** [comment]
Closed as this is probably a well known upstream python issue. When Python is build by Kodi it's fixed by https://github.com/xbmc/xbmc/pull/25608
