### ISSUE TITLE
Pas de direct chaines France TV dans Catch Up Tv And More

### ISSUE THREAD

**Issue by CSB853** [xbmc/xbmc#25654]
:) Bonjour j’utilise Kodi 21 sur iPad os version de Catch up tv  o.240 beta 10; j’ai fait toutes les mises à jour possibles des addon; je ne parviens pas à regarder le direct des chaînes France tv via Catch Up Tv And More; les messages d’erreur sont les suivants :  « widivine CDM  n’est malheureusement pas disponible sur cette architecture système iPad 16.6 » , « échec  de lecture d’un ou plusieurs fichiers consultez le journal »; je vous envoie le fichier journal n’ayant aucune compétence pour l’interpréter; je précise que les replay en revanche fonctionnent; et que le direct des chaînes France tv fonctionne aussi avec l’addon France tv.  Il y a aussi un message d’erreur quand j’essaie d’afficher les chines tv pou les activer dans Intégration TV et les chaînes ne s’affichent pas.  Je mets en PJ des copies d’écran es messages d’erreur et le fichier journal car il est trop long. Merci pour votre aide.
![IMG_0057](https://github.com/user-attachments/assets/c7dba171-d123-404c-b879-7e63a53bdba5)
![IMG_0056](https://github.com/user-attachments/assets/3db013ce-75c8-42ea-9433-e2594dfb6896)
[kodi.log](https://github.com/user-attachments/files/16726258/kodi.log)

**Comment by CastagnaIT** [comment]
je vous invite à parler en anglais, on standard language on github, at least on our project
Widevine is not supported on IOS so you cant use any addon that require widevine DRM

anyway this is not a kodi problem

**Comment by CSB853** [comment]
Now I use catch up tv and more  0.2.39 version; the message regarding « widivine » has disepeared when I try to select the live France Tv channels; but it still doesn’t work and in tv integration the channels still don’t appear and so I can’t select them; Thank you to help me…;
[kodi.log](https://github.com/user-attachments/files/16727298/kodi.log)

**Comment by CSB853** [comment]
I precise that I have created a count on France tv website but is is not possible to integrate it in catch up tv

**Comment by CastagnaIT** [comment]
as already said you must contact Catch up tv addon developers
this is not the right place

so find their github repository and open an issue to them
