### ISSUE TITLE
Please fix so follows nfo actors for tv show and episodes

### ISSUE THREAD

**Issue by kolbdog323** [xbmc/xbmc#25659]
Can you please fix it when it reads the nfo it follows the nfo actors?
Example in tv show it shows the main cast for actors but in episodes if you do actors shouldnt it only show the actors taht you have listed in the episode in the nfo not carry over the main cast in the tv show. 

Exampel there are 5 actors in the episode itself but it carries over the actors from the tv show after the episode actors. Is there a way you can fix it so it only shows the episode actors and not carry over the actors from the tv show when you have an nfo with episode nad tv show?

Sorry not sure if makes sense or not

**Comment by the-black-eagle** [comment]
Please use the forum for feature requests - https://forum.kodi.tv/index.php
