### ISSUE TITLE
PVR client set the listitem "mimetype" but Kodi core ignore it and make HTTP HEAD requests

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#25652]
### Describe the bug
Here is a clear and concise description of what the problem is:

when a PVR client set the listitem property "mimetype" but Kodi core ignore it and every time make HTTP HEAD requests
this is bad because some video service server dont like these type of requests
and as you can see on the log HTTP errors happens `Failed: Timeout was reached(28)`
other streams in my experiences can also blocking the manifest download and so cannot play video

moreover sideeffect on Windows OS there is the GUI unresponsive for many seconds due to the http error

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

no HTTP HEAD requests when the mimetype is specified on listitem property

## Actual Behavior

HTTP HEAD requests happens before playback starts and on playback stop

## Possible Fix

i tried investigate but is a mess for me, my knowledge of playlist directories is too much limited

i can say that PVR client set listitem "mimetype" property correctly and kodi core receive it correctly
when you play a channel
here the listitem played have all the properties set
https://github.com/xbmc/xbmc/blob/89b9019fe1dfca492080a5b41e80737db3003451/xbmc/filesystem/DirectoryFactory.cpp#L98-L101
but after some chain of playlist directory method end to `CPlayListFactory::Create`
https://github.com/xbmc/xbmc/blob/89b9019fe1dfca492080a5b41e80737db3003451/xbmc/filesystem/PlaylistFileDirectory.cpp#L26-L29
call that method ignore the existing listitem with all his data
so also the mimetype will be "lost" and make the HTTP HEAD requests

### To Reproduce

1. Install pvr.iptvsimple
2. make sure that on settings provide mimetype

i will attach a sample later if needed

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/kuzurufiba.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: windows 11
 - Kodi version: Kodi 22 master selfbuilded

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
If the fileitem created by PVR core has the correct properties, then the bug is not a PVR bug.

**Comment by CastagnaIT** [comment]
is possible reproduce the problem also with this fake STRM file
```
#KODIPROP:mimetype=application/dash+xml
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
https://example.com//stream//example/index.m3u8
```
