### ISSUE TITLE
Local Actor Images Ignored

### ISSUE THREAD

**Issue by KarellenX** [xbmc/xbmc#25662]
## Bug report
This issue only affects **episodes**. Movies and TV Shows are unaffected

The .actors folder is created by Kodi when using the _Export to separate files_ function. It creates the following .actors folder
1. Kodi creates the .actors folder in the root of each particular tv show - `\My TV Shows\3 Body Problem\.actors\`
2. Kodi creates the .actors folder in **each** Season folder - `\My TV Shows\3 Body Problem\Season 1\.actors\`

I had noticed in my own main library that some actor images were different to what I expected, and other actors had no image even though a local image was available. It was this that made me curious why that was happening.

When using local data --nfo files, local images, .actors folder-- Kodi seems to ignore local actor images and instead downloads the image if a valid `<thumb></thumb>` URL is available. If no valid URL is available, then no image is displayed.

The first test I ran was removing the `<thumb></thumb>` tag from all the nfo files and then scanned the show. Checking the library after the scan, the TV Show actors used the local images, but episode specific actors were left blank, even though a local image was available.

On a second test on a fresh install, I left the `<thumb></thumb>` tags in place, but replaced all actors images with the same generic image. The TV Show used the generic image, but episode specific actors had correct actor images downloaded. See log below.

Third test - I moved the generic episode actor images from the `...\Season 1\.actors\` folder into the `\TV show\.actors\ `folder. After scanning, the episode actors displayed the generic image.

The problem seems to be that the Seasons .actors folder is ignored.

## Expected Behavior
Use local images.

## Actual Behavior
Local actor images for episodes are ignored. 
If a URL is available, the image is downloaded. 
If no URL is available, no image is displayed.

## Possible Fix
--

### To Reproduce
1. Requires a TV show with nfo files and local .actors folder
4. In the nfo file, delete all the `<thumb></thumb>` tags for the actors
5. Scan the show to the library. Check episodes for missing images.
6. Probably best to ensure the TV show has not previously been scanned into the same library to avoid image cache issues.

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/sagikoxiro.kodi
From line 3070 actor images for episodes are downloaded.
(In this particular show, there are only episode specific actors for the first episode.)

### Screenshots 
Not required

## Additional context or screenshots (if appropriate)
Nil

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] **Windows**
 - [ ] Windows UWP

 - Operating system version/name: **Running on Windows 10 22H2, kernel: Windows NT x86 64-bit version 10.0.19045.4780**
 - Kodi version: **Kodi (21.1 (21.1.0) Git:20240817-183eb85f10). Platform: Windows NT x86 64-bit**

**Comment by 78andyp** [comment]
Hi

Tried to reproduce. Let me see if my test is exactly the same as yours.

I created a library with a single TV show and 3 episodes of a single season, I then exported to single files and deleted the databse.

My  directory structure looks like this:
![image](https://github.com/user-attachments/assets/b77fe882-015f-44c0-abd6-5e0b6175f051)

Each of the two `.actors` folders has the same 6 actor jpgs:
![image](https://github.com/user-attachments/assets/950fc45b-c6e1-4ec5-8aa7-e630e5311b0f)

No editing of the .NFO files.

Test 1

I then reload kodi (having deleted the entire Database directory) and set the content of the test directory to TV shows and provider to Local.

I then right click (context menu) -> Information on the TV show and on one of the episodes
Result -> the actor faces are shown for each

Test 2

I changed all of the images in the base (Firefly/.actors) actor directory to Mikey Mouse and reload as above.
Result -> the actor faces in BOTH the TV show and the episode are all Mickey Mouse.

Test 3

I restored the base images and changed the season (Firefly/Season 1/S01E10E12E14/VIDEO_TS/.actors) actors to Mikey Mouse.
Result -> the actor faces in BOTH the TV show and the epsode are all correct (the actual actors)

So it does seem the first scanned picture (the base directory) trumps anything scanned subsequently.

What's odd is that, in each case, the actors table looks like:
![image](https://github.com/user-attachments/assets/27c287b7-7b92-40cf-a01a-13a2ed718920)

Irrespective of whether Mickey Mouse is shown or not.

I guess one question is - should we really have multiple pictures for the same actor/actress?? Why would that be desirable over just one??

**Comment by 78andyp** [comment]
> Hi @78andyp
> 
> > Each of the two .actors folders has the same 6 actor jpgs:
> 
> If you had added a few episode specific guest actors in the \Season 1\ .actors\ folder, then the issue would be more obvious. As the tv show is scanned first, then the episodes, that means the actors from the tv show are cached first, and by the time those same actors are scanned for the episodes, the images have already been cached for those actors so you can't actually see the problem.
> 

Thanks for the clarification. Reproduced and suggested fix in #25785.

> > What's odd is that, in each case, the actors table looks like:
> 
> That would be the fallback URL. The URL in the nfo file (or scraper results) are stored as a backup. Maybe the local image is missing, or corrupted, then Kodi can still display the online image.
> 
> > I guess one question is - should we really have multiple pictures for the same actor/actress?? Why would that be desirable over just one??
> 
> I think it is a waste to have duplicated actors images in each movie, tv show and episode. But the Actors module of Kodi does need an overhaul. A start would be enabling a Centralised Actors Folder (CAF), just like the Artists Information Folder in music, and Movie Set Information Folder in video.
> 

I'm happy to have a look at this. I need to explore further how Kodi deals with different actors with the same name. 

> > Another observation - the actor pictures are only exported if they are viewed at least once - is this by design??
> 
> Yea, that is an annoying one. It becomes tiring having to scroll through the actors in every episode to ensure they are exported. Probably done intentionally to save on API hits at the provider sites.

Is it an API issue?? `m_cast` seems to already be populated with the actors names and links to their online thumbs so I think the API bit is done - it could be a bandwidth issue for the provider sites or perhaps it was for 'slow' machines or slow internet connections - but retrival could be done in the background I suppose. I'm not really sure how threading works in Kodi but I think there was a PR recently that did background image cleaning from the texture cache so I could look at how that works and see if we could do background actor image retrieval, if that's something that would be useful.

**Comment by KarellenX** [comment]
>Thanks for the clarification. Reproduced and suggested fix in https://github.com/xbmc/xbmc/pull/25785.

Thank you, I will read your PR after this and comment there.

>I need to explore further how Kodi deals with different actors with the same name.

It doesn't. That is why there is the occasional complaint that the wrong actor image is displayed, even though it has the correct name - different actors with the same name.
It is a difficult one to work around, I think, But I believe @pkscout and @romanvm would be better to comment on a preferred fix for this. 
Maybe the same treatment we gave the episodeguide issue?

>I could look at how that works and see if we could do background actor image retrieval, if that's something that would be useful.

I think so. Maybe even a setting "Download actor images in the background" or similar?

**Comment by romanvm** [comment]
Yes, currently actors are handled by their full name that causes issues for actors with the same full name. The solution would be to change the DB sceme and use some unique ID for an actor the same way as we use inique IDs for movies and TV shows in various online databases. From the POW of Kodi API it should be simple because now actors are handled via Actor class: https://romanvm.github.io/Kodistubs/_autosummary/xbmc.html#xbmc.Actor that can be extended as needed. It's the DB schema change that can be difficult. Also Kodi needs to support exporting/importing this new information, including backward compatibility with existing exported XML files.
