### ISSUE TITLE
Kodi does not react to Google TV remote app input when running on an Android TV device

### ISSUE THREAD

**Issue by TPXP** [xbmc/xbmc#25669]
### Describe the bug

I'm running Kodi on my Android TV (a Sony KD-65XH9505). This TV can be controlled by the remote device, or Android TV allows for my smartphone/tablet to control it through the Google TV app: when I start the Google TV app on my smartphone or tablet and it's connected to the same network as my TV, it shows an option to open a remote for the Android TV. This gives another way to control the TV without having to fetch the actual remote device.
![Screenshot_20240825_224639_Google TV](https://github.com/user-attachments/assets/089e8d7b-2d35-41a7-91da-c8d74f2773ea)
I'll refer to this screen as the "Android TV remote app" for simplicity.

When I open the Android TV remote app on my smartphone, I'm able to browse through the menus of my TV, except when I launch the Kodi app: it does not react to any input from the arrow keys on the remote app, and the back button does not work neither. Text input with the keyboard works partially though (except for accents like `é`, `è` for example).

## Expected Behavior
I expect Kodi to react to actions I perform on the Android TV remote on my smartphone.

## Actual Behavior
Currently, Kodi does not react to any keypress on the Android TV remote app.

## Possible Fix
Hard to say, Kodi seems to be doing some weird hacks to get Android TV input to work. Maybe add handlers for the corresponding events?

### To Reproduce
1. Download Kodi on an Android TV device
1. Download the Google TV app on any other device (a phone/tablet will do)
2. Connect the Google TV app to the Android TV device (this requires to input a code shown on TV the first time) - https://support.google.com/chromecast/answer/11221499
3. Using the Google TV remote app, open Kodi
4. When Kodi is loaded, press a button on the Google TV remote app
5. Nothing happens. Do the same using the actual remote of the TV and it works.

### Debuglog
I'm afraid I haven't collected a debug log yet. Let me know if it's needed.

### Your Environment
Used Operating system:
 - [x] Android TV
 - Operating system version/name: Android TV 10
 - Kodi version: 21.1

Thanks for building Kodi, I've been using it for years without issues and I love it!

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by garbear** [comment]
Can you try in version 22 (current nightly)? I rewrote some of the joystick code, so that's the version we should get working. Once v22 works I can backport the fix to v21.

I'll try to reproduce next time I'm doing Android development.

**Comment by lavish440** [comment]
> Can you try in version 22 (current nightly)? I rewrote some of the joystick code, so that's the version we should get working. Once v22 works I can backport the fix to v21.
> 
> I'll try to reproduce next time I'm doing Android development.

Sorry I can't test it as I am not at my home and I don't have access to an Android TV here. 
I will return in December.

**Comment by TPXP** [comment]
Hello, I've tested input using the Android remote app on the latest nightly https://mirrors.kodi.tv/nightlies/android/arm/master/kodi-20240824-abf07623-master-armeabi-v7a.apk and I confirm it works great! Only think that doesn't work is accent input: try typing `é`, `è` on the Android remote app keyboard (which you can toggle using the keyboard button in the upper right corner) and nothing will appear in the text area (other letters work fine).

**Comment by garbear** [comment]
Closing as confirmed fix. The fix will ship in v21.2, coming in the next few weeks.

**Comment by Kline-** [comment]
Is there a setting I need to change for this fix to work? I hadn't used Kodi on my ShieldTV for a few months and it updated itself from v20 to v21.2 last night. Google TV remote from my phone no longer works, but my TV remote via CEC is fine.

Please let me know what logs or anything else might be needed to look into this further.
