### ISSUE TITLE
KODI is playing a video and suddenly jumps to the next video

### ISSUE THREAD

**Issue by fengchen-github** [xbmc/xbmc#25694]
### Describe the bug

KODI is playing a video and suddenly jumps to the next video. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should be that one video needs to finish playing before another video can start.

## Actual Behavior

Probably because of waking from sleep. Or it could be because Kodi was terminated due to prolonged sleep, but I'm not sure.

## Possible Fix

Exiting and re-entering Kodi may back to normal status.

### To Reproduce

1. Currently, I haven't found a way to reproduce it.
2.
3.

### Debuglog

The debuglog can be found here:
[kodi.zip](https://github.com/user-attachments/files/16837494/kodi.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

The network is OK.
65508 bytes from 192.168.50.96: icmp_seq=50491 ttl=64 time=6.87 ms
65508 bytes from 192.168.50.96: icmp_seq=50492 ttl=64 time=7.71 ms
65508 bytes from 192.168.50.96: icmp_seq=50493 ttl=64 time=7.50 ms
65508 bytes from 192.168.50.96: icmp_seq=50494 ttl=64 time=8.08 ms
65508 bytes from 192.168.50.96: icmp_seq=50495 ttl=64 time=6.71 ms
65508 bytes from 192.168.50.96: icmp_seq=50496 ttl=64 time=8.15 ms
65508 bytes from 192.168.50.96: icmp_seq=50497 ttl=64 time=6.51 ms
^C
--- 192.168.50.96 ping statistics ---
116034 packets transmitted, 115069 received, 0.831653% packet loss, time 888195ms
rtt min/avg/max/mdev = 5.108/7.177/226.598/3.444 ms, pipe 3923, ipg/ewma 7.654/7.214 ms

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [*] Android

 - Operating system version/name: Android ARM 32-bit
 - Kodi version: 21.1 (21.1.0) Git:20240817-183eb85f10
Running on Sony BRAVIA 4K VH2 with Android TV 10.0.0 API level 29, kernel: Linux ARM 32-bit version 4.19.75
FFmpeg version/source: 6.0.1-Kodi
Host CPU: ARMv8 Processor rev 0 (v8l), 4 cores available
Product: BRAVIA_VH2_M_CN, Device: BRAVIA_VH2, Board: mt5895 - Manufacturer: Sony, Brand: Sony, Model: BRAVIA 4K VH2, Hardware: mt5895

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
Your device is dropping from the network, from what I can tell. In the log you've provided, that is occurring every 30s or so. Almost 1% of packet loss is also not okay, and quite telling.

Ensure that you have a stable network.
