### ISSUE TITLE
Thumbnails of all categories on a single pane

### ISSUE THREAD

**Issue by puzavac** [xbmc/xbmc#25704]
## Roadmap or todo item
**Detailed Description**

Make transition between, say, music and videos categories seamless, that is, without the need to enter each category individually. Kind of like Plasma Bigscreen or Android TV does. Entries of each category are shown in a row but all are part of a single digital pane. Given that Kodi by default has more categories than those aforementioned, maybe the default position can be the middle one so that one can hastily reach those categories above and below. 

### Context

It makes things more fluid, more connected, prettier and is faster.

### Additional context, screenshots or links
Here are some relevant links or screenshots

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by sarbes** [comment]
Not a bug report.
