### ISSUE TITLE
Problems scraping TV shows with large description (over 64k).

### ISSUE THREAD

**Issue by tanaesset** [xbmc/xbmc#25709]
### Describe the bug

When trying to scrape the show The Simpsons (35 seasons now) with the scraper "The TVDB v4" an empty TV show with no name is created in the library. The logs indicates an error updating the table tvshow. The cause for this is the amount of data being inserted exceeding the 64k limit of the text type for the c06 column.

## Expected Behavior

The TV show should show up in the library

## Actual Behavior

A blank entry/folder is created in the library

## Possible Fix

Changing the type of the c06 column from text to mediumtext in the database fixes the problem:

`ALTER TABLE tvshow MODIFY c06 mediumtext;`

### To Reproduce

1. Create the folders `The Simpsons/Season 01` in a location which is scraped as 'TV shows', and use 'The TVDB v4' as information provider.
2. Update that library

### Debuglog

The debuglog can be found here:
`2024-09-06 11:39:26.504 T:24      error <general>: SQL: [kodivideo_migrate131] Undefined MySQL error: Code (1406)
                                                   Query: UPDATE tvshow SET c00='The Simpsons',c01='Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.',c02='Continuing',c04='-1',c05='1989-12-17',c06=' [...]
2024-09-06 11:39:26.506 T:24      error <general>: ExecuteQuery - failed to execute query 'UPDATE tvshow SET c00='The Simpsons',c01='Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.',c02='Continuing',c04='-1',c05='1989-12-17',c06='  <approx 120k data removed here>  ',c08='Comedy / Animation',c09='',c10='',c12='8920',c13='',c14='Disney+',c15='',c16='', userrating = NULL, duration = NULL WHERE idShow=147'`

### Screenshots
Here are some links or screenshots to help explain the problem:

No screenshots provided as this is not relevant.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

No more info.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@tanaesset 

This is a known issue. See... https://github.com/xbmc/xbmc/issues/15768

Ensure you are using `metadata.tvshows.thetvdb.com.v4.python-1.1.6`. If you are using the latest version, please repost your report at the TVDB help site.

TheMovieDB and TV Maze scrapers have been updated to accommodate this issue. You could swap to TMDB TV Shows to overcome the issue.
