### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by wburgey** [xbmc/xbmc#25716]
blocked

### Describe the bug
Here is a clear and concise description of what the problem is:

notifications blocked

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

notifications on should play video

## Actual Behavior

does not pick up providers

## Possible Fix

do not know

### To Reproduce

1. choose video
2. load video
3. nothing

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@wburgey 

Sorry but I don't know what problem you are reporting. 
I am closing this issue report. Please head over to the Kodi forum and create a new thread which clearly describes the problem.

Thanks.
