### ISSUE TITLE
EPG search not producing results - channel group filtering broken

### ISSUE THREAD

**Issue by thomazz-nl** [xbmc/xbmc#25738]
### Describe the bug
Here is a clear and concise description of what the problem is:

The EPG search feature does not produce the expected results. I was trying to create a search that would:
* have no search term;
* have the movie/drama genre;
* have a minimum duration of 90minutes;
* have a start time after 20:00 (8pm);
* (optionally) limit the end time before 23:59, no end time limit or limit before 2am;
* filter the results to only show programmes in a specific channel group.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If one executes a new default search without supplying a search term, and selecting a channel group to filter results by, TV programmes are expected to appear for the selected channel group. 

If channel group is not touched (to at least get some results), the additional search parameters are expected to limit the given results. For example to only give daily "primetime" results, starting or ending within a specific time-frame.

## Actual Behavior

If a specific channel group is selected on the search panel, a pop-up appears saying "no results found". In some cases there would be results: if a "valid" search query was performed first, followed by a search specifying a channel group. However, the results would contain programmes from channels that do not belong to the selected channel group.

If the channel group is ignored ("All channels" is selected) in combination with the other criteria, there are still programmes being returned that start for example at 4am.

## Possible Fix

I suspect start/end time to somehow be linked to the selected start/end date instead of being applied daily.

### To Reproduce

1. Consider the following EPG data coming from TVHeadend PVR: [Epg16.zip](https://github.com/user-attachments/files/17007326/Epg16.zip).
2. Configure a search query as specified in "Describe the bug".
3. Perform the search.

### Screenshots 
Here are some links or screenshots to help explain the problem:

![afbeelding](https://github.com/user-attachments/assets/fe0cff91-8b10-4392-a13d-13d97b7a4910)

![afbeelding](https://github.com/user-attachments/assets/270cbe88-baf3-4371-8bb0-3caeee7b3bd6)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 and on OSMC.
 - Kodi version: 21.1
 - TV backend: tvheadend 4.3

**Comment by ksooo** [comment]
Confirming the issue with the broken channel group filter.

> If the channel group is ignored ("All channels" is selected) in combination with the other criteria, there are still programmes being returned that start for example at 4am.

This is a misunderstanding of the functionality. The date time controls are to control oldest and newest events to be included in the search results, not the start/end time of the events. This would be neat functionality, but as of now we don't have it.

**Comment by thomazz-nl** [comment]
> Confirming the issue with the broken channel group filter.

Thanks @ksooo for confirming the issue. 

> This is a misunderstanding of the functionality. The date time controls are to control oldest and newest events to be included in the search results, not the start/end time of the single events. This would be neat functionality, but as of now we don't have it.

Ah, that's clear. Just thinking out loud to better understand the current use-case and provoke some rationale about the current choices: someone would enter a search query to find programme "x" between start date "17-09-2024" / start time of "11:00" and end date "19-09-2024" /end time of "18:00". This would include the full 24hr of 18-09-2024. If start/end times would be applied per day, events between 00:00-10:59 and 18:00-23:59 would not show up, and someone using the feature as currently intended would be surprised/bothered. 

Is this example a logical/common search query? Why just apply the start time on the start date and similarly on the end date and nowhere in between? What exactly is such person searching for? Wouldn't it make more sense in such case to just search between start- + end-date and by default from 0:00 till 23:59 (the full 24 hours for each date)? The appropriate programme can then be selected from the results (shouldn't be a huge list, and easily further filtered).

Why are the default values of start/end time not 0:00 and 23:59 by default? Their current values limit the results by some arbitrary default of which I do not understand the logic. Maybe I'm missing something, perhaps a user would want to search for a programme, but not the one that will start in an hour, but only the ones after that....well, would it be a problem if this programme showed up in the resulting list and just not get acted upon?

Maybe it's my biased opinion, and I certainly don't want to force mine, but with tv programmes often having a daily/weekly recurring character, the search filter would seem to have more purpose applying start/end times on a daily basis than on some start/end date and nowhere in between.

I'm open to hear about any perspective I'm missing and how to propose this as a feature request if it is considered a useful (and not major breaking) change.

**Comment by ksooo** [comment]
> if it is considered a useful (and not major breaking) change

 I consider this valuable. "Problem" is that implementation is not done within just a couple of hours, although the change might look small from user's perspective, and somebody needs to find the time to do it, what currently most probably means, me.

> how to propose this as a feature request

All fetaure requests shall be raised here: https://forum.kodi.tv

**Comment by ksooo** [comment]
> Why are the default values of start/end time not 0:00 and 23:59 by default? Their current values limit the results by some arbitrary default of which I do not understand the logic. Maybe I'm missing something

Those time come from your actual EPG data, start time of oldest event in the EPG. end time of youngest event in the EPG. It is just a coincidence that it is 0:00 and 23:59 for you.

**Comment by thomazz-nl** [comment]
> I consider this valuable. "Problem" is that implementation is not done within just a couple of hours, although the change might look small from user's perspective, and somebody needs to find the time to do it, what currently most probably means, me.

Trying to make an effort myself I checked out what I think is the responsible code in EpgDatabase.cpp (but I'm no C++ programmer) and it seems that date and time constraints are merged into one value that is added to the WHERE clause of the DB query. I'm not very proficient in C++ and the Kodi codebase, so it seems to take a lot of changes to properly untangle date and time properly in code. Another approach I came up with was to just tackle this in the database query, but I quickly discovered that working with epoch dates is not very compatible between different DB backends (Postgres/SQLite/MariaDB).

I did come up with a simple approach that might work: adding another WHERE clause to the existing ones that limit the results by date. The solution uses a simple modulus/remainder operation to remove all days (60seconds*60minutes*24hours) so only the time value remains to be compared to the requested time. Note: I'm not sure the modulus "%" requires escaping since PrepareSQL uses this to indicate a string replacement too.

https://github.com/xbmc/xbmc/blob/0d165bea7389e42857a1b87110ed661bb9fbf33b/xbmc/pvr/epg/EpgDatabase.cpp#L699
Append: `filter.AppendWhere(PrepareSQL("(iStartTime % (60*60*24)) >= (%u % (60*60*24))", static_cast<unsigned int>(minStart)));`

https://github.com/xbmc/xbmc/blob/0d165bea7389e42857a1b87110ed661bb9fbf33b/xbmc/pvr/epg/EpgDatabase.cpp#L710
Append: `filter.AppendWhere(PrepareSQL("(iEndTime % (60*60*24)) <= (%u % (60*60*24))", static_cast<unsigned int>(maxEnd)));`

Could this be a viable solution?

**Comment by ksooo** [comment]
> Could this be a viable solution?

That could be a start, yes, but to make it a real end user feature I would also introduce some changes to the search dialog, namely at least a new value "any time" for start and end time to not loose current functionality.
