### ISSUE TITLE
Kodi crashes on Mint 22 (likely Python 3.12 issue?)

### ISSUE THREAD

**Issue by bernd-wechner** [xbmc/xbmc#25733]
Just upgraded my HTPC from Mint 21 to Mint 22 (which includes a shift from Pulseaudio to Pipewire and an Ubuntu 22.04 jammy to Ubuntu 24.04 noble) and post upgrade Kodi crashes on start, and produces a log with little I can glean from it.

```
$ kodi
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
Fatal Python error: PyImport_AppendInittab: PyImport_AppendInittab() may not be called after Py_Initialize()
Python runtime state: preinitialized

Thread 0x00007358c34006c0 (most recent call first):
  <no Python frame>
Aborted (core dumped)
Crash report available at /home/polyphemus/kodi_crashlog-20240914_14
[kodi_crashlog-20240914_142853.log](https://github.com/user-attachments/files/17001042/kodi_crashlog-20240914_142853.log)
2853.log
$ kodi --version
Kodi from Debian Media Center 20.5 Debian package version: 2:20.5+dfsg-1build2
Copyright (C) 2005-2021 Team Kodi from Debian - http://kodi.tv
```

with the mentioned crash log attached.

[kodi_crashlog-20240914_142853.log](https://github.com/user-attachments/files/17001044/kodi_crashlog-20240914_142853.log)

The OS seems otherwise integral and functional, has sound and video and everything passing all tests.

Others have reported same experience here:

https://forums.linuxmint.com/viewtopic.php?t=425206

though my thoughts are the kodi crash log should reveal what is wrong but may need better eyes than mine to read. I have examined its end searched it for "error" but admit I have divined no cause from that exercise.  There are of course stack traces for all the running threads in there, and it suggests it was killed by pthread_kill.c:44 and that Thread 1 was running. That stack looked like:

```
Thread 1 (Thread 0x73590da663c0 (LWP 40808)):
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x000073591a84526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x000073591a8288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x000073591f918f03 in ?? () from /lib/x86_64-linux-gnu/libpython3.12.so.1.0
#6  0x000073591faf2f58 in _Py_FatalErrorFunc () from /lib/x86_64-linux-gnu/libpython3.12.so.1.0
#7  0x000073591fad38ae in PyImport_AppendInittab () from /lib/x86_64-linux-gnu/libpython3.12.so.1.0
#8  0x000059e74b645c94 in CAddonPythonInvoker::CAddonPythonInvoker(ILanguageInvocationHandler*) ()
#9  0x000059e74c0f0eea in CScriptInvocationManager::GetLanguageInvoker(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#10 0x000059e74c0f11ac in CScriptInvocationManager::ExecuteAsync(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<ADDON::IAddon> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool, int) ()
#11 0x000059e74bcbae83 in ADDON::CServiceAddonManager::Start(std::shared_ptr<ADDON::IAddon> const&) ()
#12 0x000059e74bcbb25b in ADDON::CServiceAddonManager::Start() ()
#13 0x000059e74bbaa7ad in CApplication::Initialize() ()
#14 0x000059e74ba2233f in XBMC_Run ()
#15 0x000059e74b4bea1a in main ()
```

suggesting that it may be as simple as Kodi not liking the new default Python 3.12.

```
#6  0x000073591faf2f58 in _Py_FatalErrorFunc () from /lib/x86_64-linux-gnu/libpython3.12.so.1.0
```

and may be a rather simple thing to fix in the end and or work around on a local system.

It would be nice to solve this and I'll take any advice I can get.

**Comment by bernd-wechner** [comment]
With all due respect I do indeed value enormously templates, and did not Ignore the rules ;-). I judged that this issue is clear enough from its title alone and the cited information (notably the crash log and version citation) and better that saying expected behaviour is it starts, actual behaviour is it doesn't, and so on ... and in fact easier to triage ;-). Do let me know if I'm wrong, and I'll abide (a person's feedback I guess rather than a bot's because the bot can't judge the prudence of fully templated - to stop spurious sand poor submissions and a well judged more efficient summary)

**Comment by fuzzard** [comment]
20.x series doesnt support python 3.12.

the following commit that was merged into 21.x would likely resolve the issue if you have have a desire to run 20.x https://github.com/xbmc/xbmc/pull/22412/commits/4bf9de87e700f0de56ef698a8d8d6eb7d4ff9050. Who knows if it will apply cleanly (or require other commits backported), thats for someone else to dig into if they so desire.

**Comment by bernd-wechner** [comment]
I'm very happy to move to Kodi 21.x if I can work out how.

That said, Kodi could fail more gracefully and informatively if something like the Python version isn't supported ;-)

**Comment by fuzzard** [comment]
Can't really know what future versions of libraries are going to do unfortunately. It was valid cpython use when 20 was being maintained

**Comment by enigma131** [comment]
Please update Mint 22 and you get Python update. Look here : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1394#issuecomment-2451548942
