### ISSUE TITLE
No PPA for Ubuntu 24.04 noble

### ISSUE THREAD

**Issue by bernd-wechner** [xbmc/xbmc#25732]
Following directions here:

https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux?https=1

notably:

```
sudo apt install software-properties-common
sudo add-apt-repository -y ppa:team-xbmc/ppa
sudo apt install kodi
```
but attempting to add the PPA simply produces:

```
$ sudo add-apt-repository -y ppa:team-xbmc/ppa
Cannot add PPA: ''This PPA does not support noble''.
```

**Comment by fuzzard** [comment]
https://kodi.tv/article/ubuntu-team-kodi-ppa-officially-retired/
