### ISSUE TITLE
Kodi v22 Fetaure Request - Manually Re-order Channel Groups in EPG

### ISSUE THREAD

**Issue by Paul608085** [xbmc/xbmc#25747]
Here is a clear and concise description of what the problem is:

**The fixing of Issue #25475, ([PVR] Add 2 new types of system generated channel groups), a couple of months ago solved one problem for me, but highlighted another:**

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

**I have two different sources of TV: TVHeadend and IPTV Merge > IPTV Simple Client. I have made some of the genre Groups from both sources the same, (eg both TVH and IPTV have "Movies"), and after the #25475 fix I have hidden the individual genre groups that have an "[All Channels]" group, (eg deleted "Movies: TVH" and "Movies: IPTV", leaving just "Movies: [All Channels]) , in PVR Settings > Group Manager.
I would like to see the genre Groups at the top in a different order, rather than the various "[All Channels]" first followed by the other Groups.**

## Actual Behavior

**However, reading the groups from left to right, I now have the various "[All Channels]" first followed by the other Groups.**

## Possible Fix

**Could an additional feature be added, possible in Settings > PVR & Live TV > Channels > Group Manager to manually re-order how the channel Groups appear at the top of the EPG?**

### Your Environment
Used Operating system:

 **- [ ] Android TV**

 

 - Operating system version/name:
 - **Kodi version: 22 (kodi-20240918-05285941-master-armeabi-v7a)**

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Paul608085** [comment]
@pinpolhoxx 
Thanks for the reply.

That appears to be for x86 processors - one of the files is named "x86_64-w64-ranlib.exe".

I am using Android and Android TV on all of my client devices.

**Comment by fuzzard** [comment]
Do NOT open or execute that link. it is a known malware campagin occuring on github

**Comment by Paul608085** [comment]
@xbmc-gh-bot

I don't know what further information I can add at this stage?

Please advise?

.

**Comment by fuzzard** [comment]
Now thats dealt with, feature requests can be made on the forums.

https://forum.kodi.tv/forumdisplay.php?fid=9

**Comment by Paul608085** [comment]
@fuzzard
Thanks for the reply.

I only opened the zip file, (not the exe file), on my Linux PC, so hopefully no harm done?

OK, I'll repost in the forums.

.

**Comment by ksooo** [comment]
@Paul608085 uncheck "use backend channel group order" in Kodi PVR settings. Then, in channel group manager you should have a context menu item "Move" for every group, allowing you to change order. Have not checked for some time, but this should just work.

**Comment by ksooo** [comment]
> The fixing of Issue https://github.com/xbmc/xbmc/pull/25475, ([PVR] Add 2 new types of system generated channel groups), a couple of months ago solved one problem for me, but highlighted another

I like those Germans. Not finding the time to say "Thank you for the fix", but to find time to "complain". ;-) I'm allowed to say that because I'm also German.

**Comment by Paul608085** [comment]
@ksooo 
Thanks for the reply.

Apologies, in my view it looked like you had already "Closed" that previous issue thread, so I assumed that there was no point in trying to reply. I have now corrected that.

Thanks also for the info on how to resolve this "problem", - I wasn't previously aware that a long press on the remote sometimes brings up further options. My EPG looks much nicer now !

How do I mark this "issue" as fixed please?

.

**Comment by ksooo** [comment]
> How do I mark this "issue" as fixed please?

Glad it works for you. No further action needed. This issue here is already formally closed.

**Comment by basilgello** [comment]
> I like those Germans. Not finding the time to say "Thank you for the fix", but to find time to "complain". ;-)

Users. Users never change (c)

**Comment by Paul608085** [comment]
@basilgello
> > I like those Germans. Not finding the time to say "Thank you for the fix", but to find time to "complain". ;-)
> 
> Users. Users never change (c)

As I said above, to me it looked as if @ksooo had already closed that thread before I had a chance to thank them, so I would have been unable to reply. This has now been rectified.

As a mere "User" of Kodi, (I wouldn't know where to start with actually coding something myself), I have to say that getting support isn't _always_ easy, (or particularly friendly in some cases).

On the few occasions that I have asked a question, or raised a possible issue, either here or in the Kodi Forums I have invariably been directed to the other. Can someone please advise what type of issues and questions are proper to either the Kodi Forums, or here on Github?

I do not find navigating Github to be particularly easy, (is that deliberate, to deter mere "Users" from participating?), to be honest, I would say it is quite intimidating.

If I have an issue or suggestion about Kodi in the future, I am certainly going to think twice before seeking support.

.

**Comment by basilgello** [comment]
@Paul608085 The reply was addressed to @ksooo 

But you are right - probably best way is to start on the forums and proceed with filing Github issues if asked.
