### ISSUE TITLE
Omega 21.1 video fast fed/rewind doesn't like the past years

### ISSUE THREAD

**Issue by Bmthunder** [xbmc/xbmc#25749]
### Describe the bug
Here is a clear and concise description of what the problem is:

It seems the last update to Omega 21 I've Lost the abilities to fast fed/Rev when I'm using my video programs (tv or movie) at a respectable speed. (2x, 4x...). Now I get a 1.1,1.2,  or 1.3 notice of speed (I'm not sure if it's a speed indicator). It speeds up that .1 or .2 increment.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Bmthunder** [comment]
#Nvidia shield #seren #asgard

**Comment by Bmthunder** [comment]
Below is my question watching a movie using Seren app 

https://github.com/user-attachments/assets/488fe43b-c0e3-4691-9130-ba6154ac357d

**Comment by thexai** [comment]
Piracy is not allowed here.
