### ISSUE TITLE
Plugin xStream won‘t start anymore after iPad was reset

### ISSUE THREAD

**Issue by The-Dumb-Dino** [xbmc/xbmc#25748]
### Describe the bug
Here is a clear and concise description of what the problem is:

So recents I got this iPad for school and decided to install Kodi on it. I learned that this required sideloading and such and in the end I did it with some method that is reffered to as the anti-revoke dns method. All worked fine and kodi was working great with the xStream plugin (something to watch movies) and I enjoyed watching movies and series on my iPad whilst programming some stuff. Due to some mistake I accidentally got the dns blocker to leak and for apple to revoke all my sideloaded apps and this also blacklisted me from installing any others with that method, to get unblacklisted I had to reset my iPad and this is what I did. iPad set up again -› Sideloading set up -› Kodi installed -› xStream installed *done* but then I realized that the plugin no longer works and I have no idea why that is. My iPad is the same as before and yet this stuff is now broken. I did some research about the stuff in the log but didn‘t get anywhere so I came here for help. 
The issue sounds so stupid even to me who came across it but I don‘t know any other place to ask for help.
Thank you for your time!

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The plugin should have opened like previously.

## Actual Behavior

Addon simply wont start, I press on it from the addons tab and it doesn‘t do anything except throwing me in some other directory from where I can try to start it again (but it never works)

### To Reproduce

I‘m honestly unsure how to reproduce this issue.
~Maybe blacklist and reset your iPad too~

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/oqujadiwaz.kodi

### Screenshots 
That is the location im getting thrown in when trying to start the addon:

![IMG_0002](https://github.com/user-attachments/assets/2a8351c2-092a-40b3-ae33-c95fbfaefd57)

### Your Environment
Used Operating system:

 - [ ] Android
 - [X] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: IOS 17.5.1 (Jailed)
 - Kodi version: 21.1 Omega
 - Device: iPad Air 5th gen (iPad 13,16)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
No support for piracy.
