### ISSUE TITLE
PVR - Resume points for recordings not honored

### ISSUE THREAD

**Issue by atreyuhere** [xbmc/xbmc#25757]
### Describe the bug
Here is a clear and concise description of what the problem is:
Using (but not exclusive to) tvheadend / hts as a backend.
Recordings that have a resume point cannot be started from the known resume point that is presented.
Recordings will always be started from the beginning.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Recording should start from the last known resume point if choosen by the user

## Actual Behavior
Recording will always start from the beginning after selecting 'resume' and a previous status is known.

## Possible Fix
Currently there's a tested workaround

### To Reproduce

1. Go to TV - Recordings via remote on the Homescreen
2. Select a recording to play 
   2a. If a resume point is presented, choose 'Resume from' and see the recording start from the beginning
4. Fast forward 10 minutes or watch the recording for some time
5. Stop playback and restart the recording, selecting 'Resume from...'
6. Watch the recording being restarted from the beginning

### Debuglog
The debuglog can be found here:  https://paste.kodi.tv/ikicepuduk.kodi

### Screenshots 
None available

## Additional context or screenshots (if appropriate)
N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 22 alpha 1 (Piers) on Coreelec NO (linux 5.15)
   Kodi version: 21.1 (Omega) on Coreelec NG (linux 4.9)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by atreyuhere** [comment]
I did also test on Windows (11) in the meantime with latest pre-release; here the issue does not occur.

**Comment by ksooo** [comment]
Can you please make a screen shot where I can see the value of the setting "Media -> Videos -> Default select action" for both the windows and the coreelec machine?

I the log I see that you opened the context menu. Can you post a screenshot how this context menu looks like, please.

Then you hit doen some times and selected an item to start play back. Which one exactly?

**Comment by atreyuhere** [comment]
As requested. 
The blue one has the win settings, red is coreelec.
![Kodi_CE_Default_Select](https://github.com/user-attachments/assets/46441849-e759-46da-958e-65317b0fc799)
![Kodi_Win_Default_Select](https://github.com/user-attachments/assets/e5ca23d2-5b62-459c-9492-33e8aea30c12)

**Comment by atreyuhere** [comment]
The recording is resumed from this menu after selecting the [recording/episode.
![Uploading resume_from.jpg…]()

**Comment by ksooo** [comment]
The good thing is, the log clearly shows that you actually hav ethis problem. Directly after selecting "Resume from..." the play postion of the recording gets reset to 0, which explains why playback starts from the beginning:

```
2024-09-23 13:09:09.407 T:1454    debug <general>: HandleKey: return (0xf00d) pressed, window 10106, action is Select
2024-09-23 13:09:09.643 T:1454    debug <general>: ------ Window Deinit (DialogContextMenu.xml) ------
2024-09-23 13:09:09.663 T:1533    debug <general>: AddOnLog: pvr.hts: Setting play position to 0 for recording 548072601
2024-09-23 13:09:09.673 T:1518    debug <general>: AddOnLog: pvr.hts: recording id:548072601, state:completed, title:Van onschatbare waarde, error:n/a
```

The bad thing is that I'm not able to reproduce the issue, although having a similar setup, and that from looking at the code I cannot see how this can happen.

**Comment by atreyuhere** [comment]
Yes, i tried to be tidy ;)
It might be related to just coreelec, not been able to fire up a Ubuntu instance yet to test there, but if it doesn't display the issue it might be better reporting to the ce guys.

**Comment by phunkyfish** [comment]
I also tested this on `pvr.vuplus` and I can’t reproduce either. This is running LibreElec though and not CoreElec.

**Comment by phunkyfish** [comment]
@atreyuhere do you have any Python addons installed that interact with play functionally. I vaguely remember a couple of addons in the past causing play issues with recordings. Don’t recall there names though.

**Comment by phunkyfish** [comment]
> 2024-09-23 13:09:09.663 T:1533    debug <general>: AddOnLog: pvr.hts: Setting play position to 0 for recording 548072601

Strange that it’s pvr.hts logging this. Maybe expand the debug logging in a test PR to follow the actual code path?

**Comment by atreyuhere** [comment]
It's indeed puzzling.
I will post on the CE forum as well. Will have a test setup available so I can test anything where needed. 
Thanks for looking at this issue. Doesn't bother me that much but growing more and more curious as to what it could be..

**Comment by atreyuhere** [comment]
fyi:  https://discourse.coreelec.org/t/resume-points-not-honored/52707

**Comment by atreyuhere** [comment]
I found the exact setting that causes the issue, at least in my case. It's one single option in Player settings ('Play next video automatically'). If, and only if the '**Uncategorized**' option is selected, then the issue surfaces

I decided to reproduce completely all steps from scratch (luckily, the effect is instant so easily monitored). Traced it back to this particular setting.

Steps to repro:

- Go to settings - Player - Videos - Play next video automatically
- Select 'Uncategorized' (all other options don't seem to trigger the issue)
- Go to TV - Recordings and Start a recording
- Skip 10 mins and then Stop
- Select the recording, choosing 'Resume From..'
- See Recording starting at the beginning

- Go to settings - Player - Videos - Play next video automatically
- Deselect 'Uncategorized' (if any others are selected, leave them active)
- Go to TV - Recordings and Start a recording that has a resume point 
- Select 'Resume from...'
- Recording starts at the last known resume point

**Comment by phunkyfish** [comment]
Nice work @atreyuhere

**Comment by ksooo** [comment]
Alright, I can reproduce the problem now. Next is to find the cause. I will have a look as soon as my free time permits.

**Comment by atreyuhere** [comment]
No rush

**Comment by atreyuhere** [comment]
Thanks for fixing!
