### ISSUE TITLE
Kind of i/o blocking like behavior on Linux systems

### ISSUE THREAD

**Issue by HannesJo0139** [xbmc/xbmc#25766]
### Describe the bug
Here is a clear and concise description of what the problem is:
I am a Linux user and encountered an issue where some artwork using the skin arctic fuse is being processed and loaded very very slow. See also https://github.com/jurialmunkey/skin.arctic.fuse/issues/1079.

My setup is Debian 12 and Kodi 12.1 installed via flatpak, running on a HTPC with Intel 9100T, 16G of RAM, SSD. I use the Plex Kodi Connect App and the skin Arctic Fuse.  To track down the problem I did several tests already. To test I used a PC with Ryzen 3800X, 32G RAM, SSD. So it should really be no problem of slow hardware. The behavior exists in the following tested setups:

- Linux Debian, installed via flatpak, Mods: Arctic Fuse
- Linux EndavourOs, installed via flatpak, Mods: Arctic Fuse
- Linux Fedora, installed via flatpak, Mods: Arctic Fuse
- Linux Fedora, installed via native RPM package (Fusion repo), Mods: Arctic Fuse

However, the issue does not exist in a Windows installation. In fact even before anything could have been cached the UI is much faster here than I've ever seen on any Linux setup before. Here you can see how it looks on Windows: https://github.com/jurialmunkey/skin.arctic.fuse/issues/1079#issuecomment-2354218145. There even is a user of NVIDIA Shield who reports it is working amazingly fast for him.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
On Linux there should be no major performance difference to Windows.

## Actual Behavior

Some Artwork is being loaded extremely slow. Elements from media not focused anymore mixes into currently focused elements.

## Possible Fix

No idea.

### To Reproduce

1. Setup Linux (Debian, EndavourOs, Fedora)
2. Setup Kodi
3. Fill the lib with content (gets worse when using network media)
4. Setup Arctic Fuse
5. Browse around and watch Clearlogos and other artwork

### Debuglog

The debuglog can be found here, I think there is nothing special in it though:
https://paste.kodi.tv/gamolaliqe.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://github.com/user-attachments/assets/0fd96de1-aa28-4fce-91c0-ad025bcf9c9c

https://github.com/user-attachments/assets/9ad6d1e0-8640-4cd9-b5c9-2b74acb1b50d

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
Reproduce with Estuary without any add-ons. 

Any delay caused by scripts is way out of the scope of Kodi. It would only be relevant to this codebase if there is a delay actually loading the images from disk, or if there is an issue with the python environment.
