### ISSUE TITLE
Revert PR #15016

### ISSUE THREAD

**Issue by handofomega** [xbmc/xbmc#25769]
---
name: 25fps and 30fps media outputs at double resolution
about: 

---

### Describe the bug
[PR 15016](https://github.com/xbmc/xbmc/pull/15016) introduced a workaround for a no audio issue that forced all 25fps and 30fps media to output at double resolution to solve a no audio issue in Kodi 18 when playing 25fps content with 48khz audio. This has resulted in incorrect output ever since and breaks Dolby Vision playback in Kodi. I'm not sure how to create a reverse commit in Github, but I think this workaround is not needed any longer and harms nearly all users.

This has also been discussed on the [CoreELEC forum](https://discourse.coreelec.org/t/dynamic-conversion-of-hdr10-sei-to-dv-p8-nal/51770/414).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
25fps content should play at 25fps and 30fps content should play at 30fps

## Actual Behavior

25fps content should play at 50fps and 30fps content should play at 60fps

## Possible Fix

Revert [PR 15016](https://github.com/xbmc/xbmc/pull/15016) 

### To Reproduce

1. Play 25fps or 30fps content
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] tvOS
 - [x] Linux
 - [x] OSX
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version: 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
No response.
