### ISSUE TITLE
[Xbox Series S] Inputs are sometimes doubled

### ISSUE THREAD

**Issue by therealteamplayer** [xbmc/xbmc#25760]
### Describe the bug
When installing Kodi on an Xbox Series S using the Microsoft Store, and using the controller to navigate the menu, inputs appear to be occasionally duplicated. For instance, normally when you press down on the dpad it will move 1 place down on the menu. But occasionally, on this version, it will move down twice. This happens a lot and is very annoying.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
No inputs should be duplicated.

## Actual Behavior

Inputs are duplicated.

### To Reproduce

1. Install the app from the Microsoft store on an Xbox Series S
2. Scroll through the menu 
3. You will find that sometimes, when you move up or down one place on the menu, it will move two places instead.

### Debuglog

The debuglog can be found here:
not sure how I am supposed to get a debug log from the Xbox app

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [X] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.1.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
This doesn't appear to be a Kodi software issue, but rather a need to calibrate your Xbox controller and/or update controller firmware.

See: 
https://readwrite.com/xbox-introduces-new-controller-calibration-tool/
https://support.xbox.com/en-US/help/hardware-network/controller/update-xbox-wireless-controller
https://support.xbox.com/en-US/help/hardware-network/controller/controller-calibration-tool

**Comment by sarbes** [comment]
Is the controller working correctly on Kodi on PC? Does another controller display the same issue?

**Comment by iggy1** [comment]
Same issue

**Comment by garbear** [comment]
If the dpad is doubling input in just Kodi but nothing else, it could be a Kodi input problem. Can you post a debug log? This includes input tracing that might let us see the cause of the problem.

**Comment by iggy1** [comment]
> > If the dpad is doubling input in just Kodi but nothing else, it could be a Kodi input problem. Can you post a debug log? This includes input tracing that might let us see the cause of the problem.
> 
> How would you get a debug log from the Xbox?

install app in developer mode and check directories for log file

**Comment by iggy1** [comment]
[kodi.log](https://github.com/user-attachments/files/17876620/kodi.log)

**Comment by Dunderadde** [comment]
i see this issue has been closed but not resolved. I don't see a fix in the thread and im having this issue on xbox one x.

**Comment by garbear** [comment]
We can re-open and pick up where we left off, a log cleanly showing the problem.
