### ISSUE TITLE
Kodi 22.0 seggfaults on exit from IPTV stream through Simple IPTV client

### ISSUE THREAD

**Issue by backyard-bbq** [xbmc/xbmc#25772]
### Describe the bug
Here is a clear and concise description of what the problem is:
When watching an IPTV channel using Simple IPTV client, on stream exit, Kodi crashes with a seg fault. It seems to happen on some streams and not others. I have installed ISA and IS-Ffmegdirect

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Take me back to the Kodi gui not a command prompt/terminal window.

## Actual Behavior
Kodi crashed and I am dropped to a terminal

## Possible Fix
Not sure if it is a Kodi issue or an ISA issue.

### To Reproduce

1.  Load a m3u into Simple IPTV client
2. Play a channel
3. Hit stop
4. Kodi crashed and drops me to a terminal

### Debuglog

The debuglog can be found here:

https://privatebin.net/?4f12cca3f59ca321#55R6NwRDKPbFyYBWz156xPkACadXGQ7LYKKXtNqjVHHP

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo
 - Kodi version: 22 Alpha 1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by basilgello** [comment]
Please use https://paste.kodi.tv for debug logs, as not everybody uses browser supporting WebAssembly to use PrivateBin or other 3rd party pastebin websites

**Comment by backyard-bbq** [comment]
https://paste.kodi.tv/adehinamas.kodi

**Comment by ksooo** [comment]
What kind of mess is this the whole log is flooded with?

```
2024-09-29 09:29:54.560 T:3884    debug <CSettingsManager>: requested setting (label1067) was not found.
```

Please uninstall all those non-vanilla add-ons you have and report back whether the issue still persists.

**Comment by ksooo** [comment]
Looking at the channels you have in combination with VPN... I'm out with any kind of support for this piracy shit.

**Comment by sarbes** [comment]
If you can reproduce the issue with an openly accessible and legal stream, this issue can be accepted. Otherwise, you are out of luck.
