### ISSUE TITLE
LiveTV allows Stop recording on empty guide item immediately before an entry that is an active recording

### ISSUE THREAD

**Issue by CV8R** [xbmc/xbmc#25778]
### Describe the bug
Here is a clear and concise description of what the problem is:
On the guide, if there is an empty section of guide I can use 'c' to bring up the context menu and Stop Recording when the immediate next program has an active recording.  Selecting Stop recording cancels the recording on the next entry.

## Expected Behavior
Context menu should not show Stop recording and not stop the recording for the next entry.

## Actual Behavior
Shows Stop recording and cancels the recording on the next entry.

### To Reproduce

1. Find empty guide entry. 
2. Instant record next program adjacent to empty entry
3. Navigate to empty entry, press c on keyboard, Stop recording is shown

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/zojoxoneti.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Screenshot_20241002_181443](https://github.com/user-attachments/assets/cfd89460-1986-4cd5-951e-6fdb320c8d9c)

![Screenshot_20241002_182116](https://github.com/user-attachments/assets/ac74ecc5-f459-4a64-b02c-a6df000be18e)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

Found and replicated on linux.  Note this is a version built to help ksooo test a change for another issue and this issue was picked up in testing.
Also replicated on MacOS 21.1.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Good catch. Confirming the issue. I can reproduce it.
