### ISSUE TITLE
kodi does not correctly sort UPnP video folders served by minidlna

### ISSUE THREAD

**Issue by EricV2** [xbmc/xbmc#25771]
Kodi is able to browse UPnP AV (DMS) server over the network. I use minidlna/readnas on a nas.  I correctly finds it, display recent files and global content but sorting by date is totally broken as all file appears to have the same date.

## Expected Behavior
Unless the protocol does not allow it, I would expect to get file sorted by date if I specify it in the sort menu.

## Actual Behavior
Sort only by name

### To Reproduce

Install minidlna server on a network and try to sort files it present by date

### Your Environment
Used Operating system:

 - [ ] Linux

 - Operating system version/name: Debian unstable
 - Kodi version: Omega

**Comment by EricV2** [comment]
Please note that fetching the meta data from the minidlna, the date is indeed there

<?xml version="1.0" encoding="UTF-8"?>
<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/">
  <item id="2$FF0$64$2$488" parentID="2$FF0" restricted="1" refID="64$2$488">
    <dc:title>xxx</dc:title>
    <upnp:class>object.item.videoItem</upnp:class>
    <dc:date>2024-09-29T10:49:41</dc:date>
    <res size="3491920761" duration="1:31:52.002" bitrate="633512" sampleFrequency="48000" nrAudioChannels="2" resolution="1920x1080" protocolInfo="http-get:*:video/x-matroska:DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01700000000000000000000000000000">http://192.168.8.18:8200/MediaItems/51198.mkv</res>
  </item>
</DIDL-Lite>

**Comment by sarbes** [comment]
No response.
