### ISSUE TITLE
Nextcloud webdav unseekable due to Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by amalon** [xbmc/xbmc#25787]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi is unable to seek in video files sourced over webdavs from a local Nextcloud server.
If I try and resume a video file mid way it starts from the beginning.
If I skip to the middle, it just skips forwards a few seconds (presumably as much as has been buffered).
If I play a local file it works fine.

It affects multiple kodi installations, including PC (ArchLinux), Steam Deck (flatpak), and Android.

This used to work only a month or so ago, but is now frustratingly unusable. Its unclear to me at this stage whether a kodi or nextcloud update broke it.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Resuming of webdav files from nextcloud should start playing from the saved position.
Skipping forward should quickly resume play from the chosen position.

## Actual Behavior

Resuming webdav files from nextcloud always plays from the start.
Skipping forward only skips a few seconds at a time.

## Possible Fix

These lines in the log looks particularly relevant:
```
772 2024-10-04 00:59:09.504 T:807268   debug <general>: demuxer seek to: 344384.000000
773 2024-10-04 00:59:09.504 T:807268   debug <general>: SeekTime - input stream reports it is not seekable 
774 2024-10-04 00:59:09.504 T:807268   debug <general>: VideoPlayer: seek failed or hit end of stream
```
When curl debug is enabled it also shows:
```
 890 2024-10-03 23:58:35.873 T:796345   debug <general>: Curl::Debug - HEADER_IN: Transfer-Encoding: chunked
```

which may explain it due to this code:
https://github.com/xbmc/xbmc/blob/3aaa801cd67d049a2c2e34085a6805361b9ed624/xbmc/filesystem/CurlFile.cpp#L949

which treats chunked files as completely unseekable. This appears to be longstanding code, so either Nextcloud broke it or this code makes invalid assumptions about seekability when chunked.

(pointed to from this discussion:)
https://forum.kodi.tv/showthread.php?tid=189963&pid=1685539#pid1685539

### To Reproduce

1. Install nextcloud
2. Add a webdavs source to kodi pointing at davs://your.nextcloud.address/remote.php/webdav/path/to/videos/
3. Play or resume a longish video file
4. Attempt to skip to the middle

### Debuglog

The debuglog can be found here. This is seeking to the middle of Big Buck Bunny:
https://paste.kodi.tv/qiraxozuyi.kodi

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux rolling (kernel: Linux 6.10.10-arch1-1)
 - Kodi version: 21.1 (21.1.0)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by arnova** [comment]
Since it seems to be a regression, please try to figure out whether the problem also occurs with an older version of Kodi (and if possible NextCloud).

**Comment by amalon** [comment]
Eventually figured out its only with apache, not nginx, and that this was added to nextcloud's .htaccess in 29.0.7 (and I was still on nextcloud 29.0.6):
```
# Apache disabled the sending of the server-side content-length header 
# in their 2.4.59 patch updated which breaks some use-cases in Nextcloud.
# Setting ap_trust_cgilike_cl allows to bring back the usual behaviour.
# See https://bz.apache.org/bugzilla/show_bug.cgi?id=68973
<IfModule mod_env.c>
  SetEnv ap_trust_cgilike_cl
</IfModule>
```

that would explain it! With that corrected it works again. Apologies for the noise!
