### ISSUE TITLE
[MSVC] Build failure after enabling /permissive- compilation option

### ISSUE THREAD

**Issue by NEIL-smtg** [xbmc/xbmc#25786]
### Describe the bug
I work on MSVC compiler testing, and we regularly build popular open-source project including XBMC, with development builds of MSVC along with cl options such as /permissive- or /std:c++latest in order to find and fix regressions before they ship and cause problems for you.

Note: _XBMC has no issue when building without /permissive-. You guys can go ahead to close this issue if XBMC is not supporting /permissive-._

Recently, as I tried to build XBMC from source with MSVC along with the /permissive-, I have encountered the following errors:

## Actual Behavior
```c++
C:\gitP\xbmc\xbmc\build_amd64\build\effects11\src\effects11\inc\d3dxGlobal.h(436): error C2065: 'm_CurSize': undeclared identifier
C:\gitP\xbmc\xbmc\build_amd64\build\effects11\src\effects11\inc\d3dxGlobal.h(436): note: the template instantiation context (the oldest one first) is
C:\gitP\xbmc\xbmc\build_amd64\build\effects11\src\effects11\inc\d3dxGlobal.h(429): note: while compiling class template 'CEffectVectorOwner'
C:\gitP\xbmc\xbmc\build_amd64\build\effects11\src\effects11\inc\d3dxGlobal.h(436): error C3861: 'm_CurSize': identifier not found
C:\gitP\xbmc\xbmc\build_amd64\build\effects11\src\effects11\inc\d3dxGlobal.h(437): error C3861: 'm_pData': identifier not found
C:\gitP\xbmc\xbmc\build_amd64\build\effects11\src\effects11\inc\d3dxGlobal.h(437): error C3861: 'm_pData': identifier not found
C:\gitP\xbmc\xbmc\build_amd64\build\effects11\src\effects11\inc\d3dxGlobal.h(439): error C3861: 'm_pData': identifier not found
C:\gitP\xbmc\xbmc\build_amd64\build\effects11\src\effects11\inc\d3dxGlobal.h(439): error C3861: 'm_pData': identifier not found
...
```

Note: This is only part of the errors.

## Expected Behavior
It compiles.

## Possible Fix

No idea.

### To Reproduce
1. Open x64 native tools command prompt for vs2022
2. git clone https://github.com/xbmc/xbmc.git
3. mkdir xbmc\xbmc\build_amd64
4. cd xbmc\xbmc\tools\buildsteps\windows\x64
5. download-dependencies.bat 2>&1
6. download-msys2.bat sh 2>&1
7.  make-mingwlibs.bat sh noprompt 2>&1
8. mkdir xbmc\xbmc\build_amd64
9. cd xbmc\xbmc\build_amd64
10. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 .. 2>&1
11. msbuild /m /p:Platform=x64 /p:Configuration=Release kodi.sln /t:Rebuild 2>&1

or 

1. Download the preprocessed file: [cmake_pch.txt](https://github.com/user-attachments/files/17246451/cmake_pch.txt)
2. cl /c /permissive- /std:c++17 /TP /EHsc cmake_pch.txt

### Debuglog

The debuglog can be found here: [xbmc.txt](https://github.com/user-attachments/files/17246518/xbmc.txt)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Latest commit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by NEIL-smtg** [comment]
Just noticed that this is a duplicate of https://github.com/xbmc/xbmc/issues/23898, closing this issue.

**Comment by NEIL-smtg** [comment]
Just noticed that this is a duplicate of https://github.com/xbmc/xbmc/issues/23898, closing this issue.

**Comment by thexai** [comment]
Kodi core code is already build with /permissive- and C++20:

https://github.com/xbmc/xbmc/blob/eb29391d79578fd2e022f1bdcbf7ce4efdb02d5a/cmake/scripts/windows/ArchSetup.cmake#L71-L79

But some _external_ code/libs not support /permissive-

e.g. effects11 not supports /permissive- and is from Microssoft...

https://github.com/microsoft/FX11  so open the issue on FX11 repo instead.

**Comment by thexai** [comment]
If this is fixed some day in upstream, then this patch can be removed:

https://github.com/xbmc/xbmc/blob/eb29391d79578fd2e022f1bdcbf7ce4efdb02d5a/cmake/modules/FindEffects11.cmake#L17-L19

**Comment by NEIL-smtg** [comment]
@thexai Noted and thanks.
