### ISSUE TITLE
master lock code bypass

### ISSUE THREAD

**Issue by erpenner** [xbmc/xbmc#25826]
### Master Lock code work around
Here is a clear and concise description of what the problem is:

Hi,
My son has figured out a workaround for the master lock code to watch tv shows.
On the home screen he scrolls over to TV Shows and goes to up to recently added. He is able to play these files. He then marks these as played until the show he wants is shown.  This occurs on estuary and confluence.
Recently added could just be disabled , but it is a feature I enjoy.

Would it be possible to enable the master lock code for recently added?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The recently added thumbnail is visible on the home screen, when selected the master lock code is requested

## Actual Behavior

The recently added thumbnail is visible on the home screen, when selected the video plays

### To Reproduce

1.  Go to TV shows on home screen
2. Select a recently added TV show
3. Video plays

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by 78andyp** [comment]
Kids, eh!! I'm sure if mine used Kodi they'd be the same!!

I agree, it seems a bit odd that if videos are locked, the recently added Movies and TV Shows aren't (whereas for music it seems recently added is locked) - @KarellenX, would you agree.

I've pushed a fix that works here.

**Comment by basilgello** [comment]
@erpenner Tell your kid about penetration testing & bug bounties - let's grow the white-hat :)

**Comment by erpenner** [comment]
For sure, I've got them listening to some of the Dark Net Diary's.  Thank you!

**Comment by KarellenX** [comment]
>I agree, it seems a bit odd that if videos are locked, the recently added Movies and TV Shows aren't (whereas for music it seems recently added is locked) - @KarellenX, would you agree??

Yes I agree.
