### ISSUE TITLE
Last character missing in Chinese text blocks in Kodi 21.1 (plugin descriptions, episode details)

### ISSUE THREAD

**Issue by miuim** [xbmc/xbmc#25825]
### Describe the bug
Here is a clear and concise description of what the problem is:

When the text in large text blocks, such as plugin descriptions or episode details, is in Chinese, the last character of each line is missing. This issue does not occur when the text is in English. The problem occurs on both Windows 11 and Android TV. The default skin and various third-party skins all experience this issue. In contrast, Kodi 21 displays the text correctly.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When using Kodi 21.1 with Chinese text, all characters, including the last character on each line in text blocks, should display correctly, as they do in Kodi 21 and when the text is in English.

## Actual Behavior

In Kodi 21.1, when the text in text blocks (such as plugin descriptions or episode details) is in Chinese, the last character of each line is missing. This issue does not happen when the text is in English, nor in Kodi 21.

## Possible Fix

It might be related to how Kodi handles line endings for non-Latin characters. Adjusting the rendering logic for Chinese or other non-Latin scripts may resolve the issue.

### To Reproduce

1. Ensure that the text in the text block (such as plugin descriptions or episode details) is in Chinese.
2. Observe that the last character of each line is missing.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Snipaste_2024-10-12_11-20-38](https://github.com/user-attachments/assets/c9646497-0e8b-4ba0-a6d5-f300053416fa)
![Snipaste_2024-10-12_11-21-32](https://github.com/user-attachments/assets/5bb7dd57-b9ca-40d3-8ad3-2aefe37288dd)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11, Android TV 10
 - Kodi version: 21.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
already fixed by #25693
you need to wait the next kodi release
