### ISSUE TITLE
Use of uninitialized value when construct `CDateTimeSpan`

### ISSUE THREAD

**Issue by hribz** [xbmc/xbmc#25821]
### Describe the bug
When invoke `CDateTimeSpan`'s constructor `CDateTimeSpan(int day, int hour, int minute, int second)`, field `m_timeSpan.highDateTime` and `m_timeSpan.lowDateTime` are used before initialize.

## Actual Behavior

When invoking `CDateTimeSpan(int day, int hour, int minute, int second)`, the field `m_timeSpan` has not been initialized. Then function `ToLargeInt` use `m_timeSpan`'s value directly. This is a undefined behavior.

https://github.com/xbmc/xbmc/blob/741f0604fddf1a33aca00c88f6d148f3723c62e9/xbmc/XBDateTime.cpp#L45-L48
https://github.com/xbmc/xbmc/blob/741f0604fddf1a33aca00c88f6d148f3723c62e9/xbmc/XBDateTime.cpp#L156-L159
https://github.com/xbmc/xbmc/blob/741f0604fddf1a33aca00c88f6d148f3723c62e9/xbmc/XBDateTime.cpp#L144-L148

## Possible Fix
Make sure `m_timeSpan` has been initialzed before invoking `SetDateTimeSpan`.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
You know you can just open a PR, right?

**Comment by hribz** [comment]
OK, I have submit the fix commit in PR #25820
