### ISSUE TITLE
21.1 regression: Android Media Session does not update on Play/Pause -> Stop

### ISSUE THREAD

**Issue by matejdro** [xbmc/xbmc#25838]
### Describe the bug

In Kodi 21.1, after stopping a playback, Android media session will remain in the Playback/Paused state

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When stopping playback, media session remains in `STATE_PLAYING`/`STATE_PAUSED`

## Actual Behavior

When stopping playback, media session should go back to `STATE_STOPPED`

## Possible Fix

Downgrade to 21.0 fixes the issue

### To Reproduce

1. Start playing any media
2. Stop that media
3. Run `adb shell dumpsys media_session` -> note that Kodi's playback state is `3` (playing), even though it should have stopped

### Debuglog

Logs of me performing above steps: https://paste.kodi.tv/ximacexuwu.kodi

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 11
 - Kodi version: 21.1 (21.1.0) Git:20240817-183eb85f10

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
@fritsch looks like the problem is here

https://github.com/xbmc/xbmc/blob/410c628c828ba9941479391cd1f80452da3ac574/xbmc/platform/android/activity/XBMCApp.cpp#L922-L924

this `m_mediaSessionUpdated = false;` has been placed after `UpdateSessionState` call so should not update the state

**Comment by fritsch** [comment]
Jep - the old implementation spammed multiple times per second killing payback on a wide range of devices causing a quasi denial of service to attached providers ;-). So I made it on demand, e.g. whenever some action happens.

So whoever has a better idea than doing it on demand, as it should be now, feel free.

**Comment by fritsch** [comment]
Thanks @CastagnaIT I agree with your finding. We should update it a final time on stop, see: https://github.com/xbmc/xbmc/pull/25841

I don't have the time to test it, so assigend it to you for review. If it works -> fine. Thanks again.

**Comment by matthuisman** [comment]
i can test a backported 21.1 build on Shield pro and non-pro

**Comment by CastagnaIT** [comment]
kodi 21 test builds:
https://jenkins.kodi.tv/job/android-arm-docker/8214/artifact/kodi-20241017-b3ba7a12-PR25843-armeabi-v7a.apk
https://jenkins.kodi.tv/job/android-arm64-docker/7996/artifact/kodi-20241017-b3ba7a12-PR25843-arm64-v8a.apk

**Comment by matthuisman** [comment]
shield 2015 pro 64bit

21.1 stock
play - state = 3
stop - state = 3

play - state = 3
pause - state = 2
stop - state = 2

jenkins build from above:
play - state = 3
stop - state = 1

play - state = 3
pause - state = 2
stop - state = 1

**Comment by matejdro** [comment]
above 32-bit version also works for me on Homatics Box R4 plus. Thanks!

**Comment by matthuisman** [comment]
curious - what are the real-world implications of this bug? 
Apart from using that tool to see the state staying at 3.
Does it mess up other playback of other apps etc?

**Comment by matejdro** [comment]
For me it messes up Home Assistant. I have it set to turn on my lights when playback stops, but if playback never stops, light never turn on.
