### ISSUE TITLE
Kodi Crash at Start After Addons Update or Install

### ISSUE THREAD

**Issue by mycurelights** [xbmc/xbmc#25837]
---
name: Problem report
about: Create an extensive report to help us document a problem

---

### Describe the bug

Randomly, after installing or updating certain video or skin add-ons, Kodi starts showing loading errors for many of the modules and add-ons, and it crashes. After that, Kodi will crash immediately on startup. This happens with multiple skins I’ve tried, such as Fentastic and Nimbus.

## Possible Fix

changing the skin defult to Esturay in guisettings.xml will let the kodi start. 

### To Reproduce

It's really hard to reproduce since it happens randomly, sometimes updates are fine, other times causes this issue. 

### Debuglog

https://paste.kodi.tv/onizoyexib.kodi

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by the-black-eagle** [comment]
We don't support anything to do with piracy.
