### ISSUE TITLE
Smart playlist does not permit to show filename instead of metadata title

### ISSUE THREAD

**Issue by momala454** [xbmc/xbmc#25844]
### Describe the bug
There is no option to show filename on smart playlist instead of the content title

## Expected Behavior
An option to do so, like in "videos"

## Actual Behavior
It always show the metadata title

## Possible Fix
Add option

### To Reproduce
1.  create smart playlist
2. no option available to change it
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ukanutemix.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: windows 10
 - Kodi version: 21.1.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by 78andyp** [comment]
Do you mean this setting??
![image](https://github.com/user-attachments/assets/c48281ca-cf95-42ae-a7fa-c70d96b1e0ec)

I must say I can't get it to do anything. Do you have a screenshot of what it does in videos??

I can see that the code path to show smart playlists never makes reference to that setting (whereas the code path for videos does) - although the description of it is a bit off - it implies it's only relevant at scanning into library.

**Comment by momala454** [comment]
yes this setting. I end up using estuary and modifying variables.xml to modify `<variable name="ListLabelVar">`
with this
```xml
		<value condition="!String.IsEmpty(ListItem.FileName) + !ListItem.IsFolder">$INFO[ListItem.FileName]</value>
```

**Comment by 78andyp** [comment]
Hi

Can I just clarify. I've created a smart playlist.

This is what currently shows, irrespective of the replace file names with library titles setting:

![image](https://github.com/user-attachments/assets/f1173152-63c1-46fc-a299-c31596b55212)

but this is what should happen when the setting is off:

![image](https://github.com/user-attachments/assets/16fe58fd-df39-4bee-bee2-047040fc6538)

@KarellenX - is this what you would expect the setting to do - I can't seem to get it to do anything.
The description is also confusing - it seems to suggest it's only relevant at library scan time, but the code in `CFileItem:UpdateInfo` is not to do with that.

**Comment by KarellenX** [comment]
@momala454 @78andyp 

>is this what you would expect the setting to do 

To be honest, I have never thought about file titles in smart playlists. 

These are my thoughts...
1. Smart Playlists are a **Library** feature. Without a Library, you cannot create a Smart Playlist to show content. 
2. Nowhere in the library is it possible to convert "library" titles to "filename" titles
3. That setting _"Replace file names with library titles"_ is a Files View setting. **Not** a Library view setting.

So, considering the above. I believe it is correct behaviour that a Smart Playlist does not show filenames as titles.

Maybe if other developers have a different view they can comment.

I don't consider the current behavour a bug, but more of a feature request. So I, or another team member, will close this issue report in the near future
