### ISSUE TITLE
Kodi 21 - Unable to use VDPAU when VAAPI driver is available

### ISSUE THREAD

**Issue by mvrk69** [xbmc/xbmc#25873]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hi, i have Kodi 21 installed on my Fedora 40, my GPU is an NVIDIA GTX 1070, and i have installed libva-nvidia-driver so i can have hardware video acceleration on Firefox.
When this driver is installed, kodi uses VAAPI and video playback doesn't work, video is stuck plays a frame from time to time, audio plays fine. If i go to settings to try to use VDPAU instead of VAAPI it doesn't show VDPAU options.
If i remove libva-nvidia-driver everything works fine, video plays fine and if i go to settings it show the VDPAU options.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Even with a VAAPI driver available, kodi should allow to choose between VAAPI or VDPAU.

## Actual Behavior

With a VAAPI driver available, kodi doesn't allow to use VDPAU.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here: https://pastebin.com/htW5kt5s

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora 40
 - Kodi version: kodi-21.1-1.fc40.x86_64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
> Even with a VAAPI driver available, kodi should allow to choose between VAAPI or VDPAU.

Where is it stated that Kodi should allow to choose between those?

**Comment by mvrk69** [comment]
> > Even with a VAAPI driver available, kodi should allow to choose between VAAPI or VDPAU.
> 
> Where is it stated that Kodi should allow to choose between those?

Seems i assumed that. But i just read the wiki more carefully and i see the options for VAAPI or VDPAU only appear for whatever hw decoding it detects.

So i guess this should be more of a feature request then a bug.

I was also able to force it to use VDPAU when both VAAPI and VDPAU are available with cmd line parameter --gl-interface=glx

**Comment by sarbes** [comment]
I'm closing this issue then. Feel free to submit a feature request in the forum.
