### ISSUE TITLE
PR 25798 causes kodi hang with m3u file on smb share

### ISSUE THREAD

**Issue by HiassofT** [xbmc/xbmc#25882]
### Describe the bug

Accessing a directory with a m3u file on a SMB share via Videos->name_of_the_smb_sources causes kodi to hang forever displaying a spinner

Bisecting through merge commits lead to PR #25798, kodi master githash 3732e39a5f9091a8fa1469e59394ebeafdb62743 is fine, githash fbb24cee85ea242a06a1246da106318a077ae53c and later show the issue

## Expected Behavior
Kodi shows the contents of the directory

## Actual Behavior
Kodi hangs and it's not possible to stop it (except via killing)

### To Reproduce

Create a m3u file in a directory that's shared via SMB, eg playlist/bbb.m3u with the following contents
```
https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_720p_h264.mov
```

Navigate to the directory via Videos->source-name

### Debuglog
The debuglog can be found here - smb produced endless smbc_read / result 0 lines so I cut that off after a while
https://paste.libreelec.tv/powerful-piranha.log

## Additional context or screenshots (if appropriate)

ping @CastagnaIT 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC master, running on RPi5
 - Kodi version: master

**Comment by Uukrull** [comment]
Yes, I had the same issue with a shared SMB folder and reverting https://github.com/xbmc/xbmc/commit/fbb24cee85ea242a06a1246da106318a077ae53c fixed it.

@CastagnaIT Could you check it?
