### ISSUE TITLE
Item folder missing after moving TV show location

### ISSUE THREAD

**Issue by activoice** [xbmc/xbmc#25887]
### Describe the bug
Here is a clear and concise description of what the problem is:
"*Item Folder" is not available to select artwork from if the original TV Show location has been changed

Sometimes to make space on a drive that is almost full I will move a TV show folder to a different location (drive or share).   Then I Clean Library to remove the old entry then Update Library so that Kodi picks up the TV show again but from it's new location.  So far so good show has been re-added.

But at a later time let's say I have added artwork, or I have added a new season requiring me to go and update or change artwork.

Highlight a TV series
Press I to get to the Information screen
Select Choose Art
Select Poster (for example)
Select Browse
*Item Folder is not displayed at the top of the list to be able to select the artwork from the Item Folder.

The work around at this point is to select Television which presents a list of every TV show, then locate the TV show, then select the artwork.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

*Item Folder should always appear at the top of the list.. 

## Actual Behavior

*Item Folder is not present if the original folder location has been moved.

## Possible Fix

If I had to guess it seems to be that maybe the original folder location is not removed during the clean library function, and later on when the library is updated maybe the new location is not added and subsequently the menu item "Item Folder" is not displayed because the new location hasn't been stored. (Just my best guess)

### To Reproduce

Select a TV series
Press I to get to the Information screen
Select Choose Art
Select Poster (for example)
Select Browse
*Item Folder is not displayed at the top of the list to be able to select the artwork from the Item Folder.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/otokoqiqil.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://imgur.com/a/aIN2sZD

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows & Android
 - Kodi version: 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Hitcher** [comment]
> I will move a TV show folder to a different location (drive or share). Then I Clean Library to remove the old entry

That's what's causing you problems as the path won't be removed.

To fully remove a TV show entry you need use the context menu - Manage... > Remove from library.

**Comment by activoice** [comment]
> To fully remove a TV show entry you need use the context menu - Manage... > Remove from library.

Thanks that worked.  

Isn't this a bug with the Clean Library function then because shouldn't Clean Library be removing all entries for the missing media similar to Remove from Library?

**Comment by Hitcher** [comment]
I think it's because TV shows can be ongoing so you wouldn't want a show totally removed from your library in between seasons.

**Comment by activoice** [comment]
Closed
