### ISSUE TITLE
Kodi.exe Crashe is observed when we launching the App from a machine which we connected remotely.

### ISSUE THREAD

**Issue by Michellehdr** [xbmc/xbmc#25894]
### Describe the bug
Here is a clear and concise description of what the problem is:
Kodi.exe Crashe is observed when we launching the App from a machine which we connected remotely.

## Expected Behavior
No Crash should happen

## Actual Behavior
Kodi.exe Crashe is observed when we launching the App from a machine which we connected remotely.

### To Reproduce
1. Download the Kodi Application from [Here](https://kodi.tv/download/)
2. Install the application.
3. Log in to another machine and remotely connect to the machine with the Kodi app is installed.
4. Try to launch the Kodi application.
5. Observe.

### Your Environment
Used Operating system:
 - Operating system version/name: Windows 11
 - Kodi version: Kodi & 21.1.0.0

**Comment by fuzzard** [comment]
Most likely the same as https://github.com/xbmc/xbmc/issues/25777

Follow @thexai 's comment https://github.com/xbmc/xbmc/issues/25777#issuecomment-2388787527 and try a newer Omega nightly that has a fix.

**Comment by Michellehdr** [comment]
@fuzzard thanks for your quick response. May I ask what newer Omega nightly mean?

**Comment by fuzzard** [comment]
Read the comment i linked.

https://mirrors.kodi.tv/nightlies/windows/win64/Omega/ Install one of those.

**Comment by Michellehdr** [comment]
Got it. Will try. Thanks a lot!

**Comment by Michellehdr** [comment]
@fuzzard we checked on the omega build and found the bug not repro on it. However it still repro on the build we downloaded from here: https://kodi.tv/download/. Do you have any suggestion on what we shall do with the bug?

**Comment by neo1973** [comment]
Bugs that are fixed in git are considered fixed so this ticket gets closed.

**Comment by Michellehdr** [comment]
@neo1973 fixed in git means on the Omega build?

**Comment by fuzzard** [comment]
Your solution was given https://github.com/xbmc/xbmc/issues/25894#issuecomment-2442852668

There is currently no timeline for 21.2. use a nightly
