### ISSUE TITLE
Tonaussetzer bei FireTV 4k max Stick

### ISSUE THREAD

**Issue by Waldecker61** [xbmc/xbmc#25908]
Habe vor ein paar Wochen von Kodi 20.0 auf Kodi 21.1 geupdatet.
Jetzt tritt folgendes Problem auf, wenn ich KODI frisch starte und einen Film schaue von meinem NAS läuft alles perfekt, aber beende ich den Film und starte einen anderen Film, habe ich massive Tonaussetzer oder überhaupt keinen Ton mehr.
Um weiterschauen zu können muss ich KODI komplett schließen und neustarten, damit der Ton wie gewohnt wieder vorhanden ist.
Diese Problem hatte ich vorher mit der Version 20.0 nicht, egal welches Ton oder Videoformat.

Das ganze Problem habe ich auf einem FireTV - Stick 4k max (1.Gen.) mit der von Amazon angepassten Android 9 Version.

**Comment by neo1973** [comment]
Hi, bug reports are only accepted in English. Please open a new report in English and stick to the template.
