### ISSUE TITLE
Tonprobleme mit Fire TV und KODI 21.1

### ISSUE THREAD

**Issue by Waldecker61** [xbmc/xbmc#25911]
I updated from Kodi 20.0 to Kodi 21.1 a few weeks ago, now I have the following problem, when I restart KODI and watch a film from my NAS everything works fine, but when I stop the film and start another film I have massive sound dropouts or no sound at all. 
In order to continue watching, I have to stop KODI completely and restart it so that the sound is back as usual. I didn't have this problem before with version 20.0, regardless of the sound or video format. 
I have the same problem on a FireTV - Stick 4k max (1st gen.) with the Android 9 version customised by Amazon.

**Comment by sarbes** [comment]
No response.
