### ISSUE TITLE
freaze when closing app using toolbar linux mint

### ISSUE THREAD

**Issue by developer861** [xbmc/xbmc#25910]
### Describe the bug
Here is a clear and concise description of what the problem is: the app freezes when trying to close it using toolbar

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

it should not freeze

### To Reproduce

1. open the kodi app
2.close using toolbar
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help: i'm using cinnamon desktop

### Your Environment
Used Operating system: linux mint 22

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:21.1

**Comment by sarbes** [comment]
No response.
