### ISSUE TITLE
Kodi fails to start after yesterday's binary update

### ISSUE THREAD

**Issue by pitsi** [xbmc/xbmc#25937]
### Describe the bug
After yesterday's binary update to kodi (more info below), kodi fails to start. If it helps, the changelog for the binary update lists only this change for libfmt
```
kodi-dmo (5:21.1-dmo1+b2) unstable; urgency=medium
  * Build with libfmt10; no source changes.
 -- Christian Marillat <marillat@deb-multimedia.org>  Tue, 05 Nov 2024 09:46:57 +0100

kodi-dmo (5:21.1-dmo1+b1) unstable; urgency=medium
  * Rebuild for PAC/BTI support; no source changes.
 -- Christian Marillat <marillat@deb-multimedia.org>  Thu, 31 Oct 2024 12:06:37 +0100
```
I also added the previous part for +b1, in case it helps. This is what apt's log says about the update
```
Start-Date: 2024-11-05  11:54:07
Commandline: apt-get dist-upgrade
Install: libfmt10:amd64 (10.1.1+ds1-4, automatic)
Upgrade: libspdlog1.12:amd64 (1:1.12.0+ds-2+b2, 1:1.12.0+ds-2+b3), kodi:amd64 (5:21.1-dmo1+b1, 5:21.1-dmo1+b2)
End-Date: 2024-11-05  11:54:09
```
Apt installed libfmt10 (new package, different from libfmt9 that was already installed) and upgraded libspdlog1.12 with a binary update it had. After the update, libfmt9 depended on no other package, so it was removed.

## Expected Behavior
Kodi should at least run and show its interface.

## Actual Behavior
Kodi does not launch and this pops up in the terminal.
```
$ kodi
/usr/lib/x86_64-linux-gnu/kodi/kodi.bin: symbol lookup error: /usr/lib/x86_64-linux-gnu/kodi/kodi.bin: undefined symbol: _ZN13GuidGenerator7newGuidEv

```
## Possible Fix
No idea.

### To Reproduce
1. On a debian unstable x64 system, install the deb-multimedia repo and then kodi from that repo.
2. Launch kodi from the terminal and notice the above.

### Debuglog
No log is created, even with the --debug parameter, just this bit I said above.
```
$ kodi --debug
/usr/lib/x86_64-linux-gnu/kodi/kodi.bin: symbol lookup error: /usr/lib/x86_64-linux-gnu/kodi/kodi.bin: undefined symbol: _ZN13GuidGenerator7newGuidEv
```

## Additional context or screenshots (if appropriate)
First and foremost, I contacted the maintainer and he said he has no issues on his end. Then I renamed my ~/.kodi folder to make it start fresh, but nothing changed. 

In order to troubleshoot it, I enabled the testing branch (both from the main debian repo and deb-multimedia), which has the version before the 2 binary updates (21.1-dmo1), and downgraded kodi to that one. Apt brought back in libfmt9 and downgraded libspdlog1.12 to the version before the last binary update (the one that ends with +b2). This was the only thing that made kodi work again like before.

Last but not least, removing it completely with purge and reinstalling did not help. Other than that, googling for errors similar to the one mentioned above returns results about libcrossguid0, which is already installed.

The only addons that I have installed are iptvsimple (from deb-multimedia because it is a binary addon) and confluence (from the main kodi repo), plus their dependencies, e.g. inputstream adaptive and the like and I mostly use it with iptvsimple. Last time I watched something there was on Monday and it worked fine.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian GNU/Linux trixie/sid x64
 - Kodi version: 21.1

**Comment by neo1973** [comment]
Hard to say what went wrong but I doubt it's a Kodi issue. The kodi.bin from kodi_21.1-dmo1+b2_amd64.deb references the symbol `_ZN13GuidGenerator7newGuidEv` and the library `libcrossguid.so.0`:
```
$ ldd kodi.bin
[...]
        libcrossguid.so.0 => not found
[...]

$ objdump -T kodi.bin | grep _ZN13GuidGenerator7newGuidEv
0000000000000000      DF *UND*  0000000000000000              _ZN13GuidGenerator7newGuidEv
```
 Looks good so far. `libcrossguid.so.0` is a symlink to `libcrossguid.so.0.0.1` and that provides the needed symbol (libcrossguid0_0.0+git200150803-6+b2_amd64.deb):
```
$ objdump -T libcrossguid.so.0.0.1 | grep _ZN13GuidGenerator7newGuidEv
0000000000001b50 g    DF .text  000000000000004d  Base        _ZN13GuidGenerator7newGuidEv
```
My guess: Your libcrossguid is messed up.

**Comment by basilgello** [comment]
@marillat

**Comment by pitsi** [comment]
How can it be messed up? I reinstalled it and nothing changed. Also
```
$ ldd /usr/lib/x86_64-linux-gnu/kodi/kodi.bin | grep libcross
	libcrossguid.so.0 => /lib/x86_64-linux-gnu/libcrossguid.so.0 (0x00007f4914a5f000)
```

**Comment by pitsi** [comment]
How did this happen? Kodi is built with this library since ever, I guess.
Also, if I try to replace dmo's libcrossguid with the one from the main repo, apt wants to remove... kodi! :D This means that kodi was built with the version the dmo repo provides.

**Comment by neo1973** [comment]
> Also, if I try to replace dmo's libcrossguid with the one from the main repo, apt wants to remove... kodi! :D This means that kodi was built with the version the dmo repo provides.

That's what the package claims but, as has been shown, is wrong.

> Oh come on, why did you close it? I was writing my message and checking the lib versions before replying!

Because it's an packaging issue, not a Kodi issue. If someone can point out where Kodi is faulty I'm happy to reopen the issue.

**Comment by pitsi** [comment]
I guess you are right.

About this bit.
```
$ objdump -T /usr/lib/x86_64-linux-gnu/libcrossguid.so.0.2.3 | grep _ZN13GuidGenerator7newGuidEv
$ (returns nothing)
```
That path there is from libcrossguid0, but it exists on unstable but not on testing
Unstable
```
$ dpkg -S /usr/lib/x86_64-linux-gnu/libcrossguid.so.0.2.3 
libcrossguid0:amd64: /usr/lib/x86_64-linux-gnu/libcrossguid.so.0.2.3
```
Testing
```
$ dpkg -S /usr/lib/x86_64-linux-gnu/libcrossguid.so.0.0.1 
libcrossguid0:amd64: /usr/lib/x86_64-linux-gnu/libcrossguid.so.0.0.1
```

**Comment by pitsi** [comment]
Tadaaa! Many thanks to the maintainer for the quick rebuild.
```
kodi-dmo (5:21.1-dmo1+b3) unstable; urgency=medium
  * Build with latest libcrossguid0
 -- Christian Marillat <marillat@deb-multimedia.org>  Thu, 07 Nov 2024 01:43:37 +0100
```
