### ISSUE TITLE
Kodi 22.0-Alpha 1 - Text rendering issue

### ISSUE THREAD

**Issue by roidy** [xbmc/xbmc#25941]
### Describe the bug
Here is a clear and concise description of what the problem is:

Text rendering is broken when the GUI is set to 4k. Stray pixels are rendered at the side of characters.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Text to render correctly.

## Actual Behavior

Text renders incorrectly.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![screenshot00008](https://github.com/user-attachments/assets/2d2b8b39-415e-491d-9aa4-144d4cc261ee)

Stray pixels to the left of the lowercase e, n, o, q, s, 2 and 4

Also to the left of each character in the number 100 in the text Top 100

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: CoreELEC
 - Kodi version: 22.0-APLHA 1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by neo1973** [comment]
@roidy: I assume the issue does not occur with Kodi 21.1?

**Comment by roidy** [comment]
> @roidy: I assume the issue does not occur with Kodi 21.1?

No issue 21.1

**Comment by sarbes** [comment]
Ah, Corerlec. We don't support forks here. Please reproduce with Kodi.
