### ISSUE TITLE
GPL license conflict

### ISSUE THREAD

**Issue by a-andre** [xbmc/xbmc#25951]
[LICENSE.md](https://github.com/xbmc/xbmc/blob/b2a86e31dd7a6770f622fb9014788be8e40dc7dd/LICENSE.md) states that Kodi is provided under GPL-2.0-or-later.
But [xbmc/cores/VideoPlayer/DVDInputStreams/dvdnav/nav_types.h](https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDInputStreams/dvdnav/nav_types.h) is GPL-2.0-only.
Following the rules of GPL, the way `nav_types.h` is used/included would make Kodi actually GPL-2.0-only.

**Comment by garbear** [comment]
You're right, we should ignore the spirit of the law and make sure every line of our million line project is exactly compliant with legal text so perfect it's never needed major modification (oh wait). Please prepare a pull request fixing the problem. And definitely don't learn about patent law :wink:

**Comment by garbear** [comment]
Technically, there's a term in copyright law called "fair use". We learned from Goolge v Oracle that interfaces are copyrightable but fall under fair use. And a header is by definition an interface. So this PR is invalid.
