### ISSUE TITLE
Subtitle will not be visible after closing Kodi

### ISSUE THREAD

**Issue by ymca11** [xbmc/xbmc#25969]
### Describe the bug
Here is a clear and concise description of what the problem is:

After I download a subtitle from the internet it's working ok.
But if I stop in the middle of the movie and close Kodi, when I open it again to continue the movie, the subtitle is gone and I need to download it again to see it.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should save the subtitle when it suppose to do that as the system option say it should.

## Actual Behavior

Subtitle disappears after Kodi restart.

### To Reproduce

1. download a subtitle in a different language
2. play movie and stop it in the middle
3. close Kodi
4. open Kodi and return to the middle of the movie and see if the subtitle is there.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
No response.
