### ISSUE TITLE
[FireTV Cube] Dolby digital+ 7.1 is outputed as 5.1

### ISSUE THREAD

**Issue by thedonalfonso** [xbmc/xbmc#25975]
### Describe the bug
Here is a clear and concise description of what the problem is:

On FireTV Cube (HW v3) when playing a video file in kodi with dolby digital + 7.1 audio track, it is outputted as 5.1

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It is expected that is output is DD+ 7.1

## Actual Behavior

On FireTV Cube (HW v3) when playing a video file in kodi with dolby digital + 7.1 audio track, it is outputted as 5.1
Disabling AC3 / e-AC3 capabilities makes output as PCM 7.1 (but dolby atmos on DD+ don't work in this case)

It worked in RAW but DTS is not handled well in this case (1 or 2 s latency)

## Possible Fix

Possibility to choose RAW or not for each kind of audio type 

 
### To Reproduce

<advancedsettings>
<audio>
<superviseaudiodelay>true</superviseaudiodelay>
</audio>
</advancedsettings>

to make DD / DD+ files to work, else DD work in RAW, DTS in not RAW

### Debuglog

The debuglog can be found here:

don't know how to make

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.1 FireTV Cube

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by sarbes** [comment]
No response.
