### ISSUE TITLE
Make this player available for JIOSTB os 

### ISSUE THREAD

**Issue by GTTech2305** [xbmc/xbmc#25987]
Hi Team, please make this player available for JIOSTB as well as in jioStb side load is not available and app not available on jiostore as well

JioSTB is based on Android Os

Please consider this request.
As jiostb not have proper media player this will help us to use

**Comment by fuzzard** [comment]
No idea what jiostb is. Feature requests can be made on the forums.

**Comment by GTTech2305** [comment]
This is smart set top box lonch with jiofiber based on Android but no side
load apps
