### ISSUE TITLE
DVD folder/iso playback failure

### ISSUE THREAD

**Issue by smp79** [xbmc/xbmc#25993]
### Describe the bug
Here is a clear and concise description of what the problem is:

I noticed that if the DVD playbck is started during the playback of any other video - it would would not play properly (major stuttering). In other words, the previous video should be stopped before attempting to play the DVD.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

DVDs should play regardless of the playback of other videos.

## Actual Behavior

I have to press stop before playing the DVD.

### To Reproduce

1. Play some video or TV channel
2. During the playback try to play a DVD (folder or iso)

### Debuglog

The debuglog can be found here:
https://gist.github.com/smp79/1e99e84000a22a9a6b9c71ce96bea4e6

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 and LibreELEC
 - Kodi version: current master
I can reproduce this on Windows and Linux, so this seem to be platform agnostic.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CrystalP** [comment]
Major stuttering is putting is nicely - here it's more like a complete freeze or at best a frame every second or two.
However moving the mouse over the window restores normal playback - until you don't move the mouse anymore.
That's probably because it forces drawing of the GUI?
Hope that gives someone ideas, I really don't know enough about vp.

**Comment by smp79** [comment]
Looks like this is a regression that was introduced somewhere between Kodi 20 and 21. Kodi 20 does not have this issue.

**Comment by smp79** [comment]
I narrowed it down to Kodi 21 beta 3. The issue is present in Beta 3 but not in Beta 2.

**Comment by smp79** [comment]
I found the bad commit - https://github.com/xbmc/xbmc/commit/401294dffedb798cc9dcb1c4061ecd3db1ce8cac Reverting it fixed the issue.

ping @enen92

**Comment by enen92** [comment]
Thanks @smp79 I'll assign this to.myself. however unfortunately my time is pretty limited at the moment
