### ISSUE TITLE
Enabling "Allow use DXVA Video Super Resolution" on Windows 11 causes a decrease in frame rate and instability.

### ISSUE THREAD

**Issue by Pixellevel** [xbmc/xbmc#25991]
### Describe the bug
Here is a clear and concise description of what the problem is:

I use the latest Windows client to play video files and transfer them to the TV using HDMI, with motion compensation enabled on the TV. Under settings/player/video, I enable "allow hardware acceleration-DXVA2" and disable "allow use DXVA video super resolution," with everything else set to default. In this situation, it runs very smoothly, and the picture is very fluid. However, if I enable both "allow hardware acceleration-DXVA2" and "allow use DXVA video super resolution," the TV cannot perform motion compensation properly. The picture shows regular stuttering, even though some motion compensation is still happening, the result is not smooth. My devices are an Intel 12600K CPU and an NVIDIA 4060 Ti GPU connected to an LG OLED B1 TV.

Additionally, while enabling the debug log and reproducing the steps, I noticed that if both "Allow hardware acceleration-DXVA2" and "Allow use DXVA Video Super Resolution" options are enabled, the display's refresh rate fluctuates between 40 and 55, sometimes dropping below 40 frames. The GPU usage is not high, and this issue does not occur when I directly play YouTube videos (since the Chrome browser can also enable NVIDIA Video Enhancement). When I disable the "Allow use DXVA Video Super Resolution" option, the refresh rate during video playback consistently stays around 60 frames.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Even with both options enabled, the picture should be perfectly motion compensated by the TV without stuttering.

## Actual Behavior

It actually shows regular stuttering, and the picture is no longer smooth.

## Possible Fix

In fact, when using the MPV player on my computer to play on the TV with motion smoothing enabled, I encountered a similar issue. It starts off very smooth, but after a while or when performing some forward/backward seeking, stuttering often occurs, and the playback becomes less smooth. Eventually, I discovered that enabling the  "video-sync = display-resample-vdrop" configuration resolves this issue. Even with the Anime4K filter applied in MPV, there was no stuttering, so I believe this is not a performance-related issue.,

Additionally, I hope Kodi can also include an option like "video-sync = display-resample-vdrop".

### To Reproduce

0.It should be on a graphics card that supports NVIDIA RTX Video Enhancement, and the feature should be enabled in the control panel. After this feature is enabled, you can check the status in the control panel.
1. Open settings/player/videos/processing, select Render method to DXVA, enable Allow hardware acceleration-DXVA2 and Allow use DXVA Video Super Resolution.
2.For LG TVs, usually you need to change the input source to something other than PC to enable motion compensation, such as HDMI or set-top boxes. For other TVs, I'm not sure how to enable it, but any input source that allows the TV to perform motion compensation should work. The computer's output signal is 3840x2160 60Hz.
3.Use Kodi to play videos, preferably those with panning scenes for easier observation.

##Actually, when I saw the refresh rate displayed on the screen after enabling the debug log, I thought the following method could also prove that this is an issue.

For the same computer with an NVIDIA RTX graphics card that supports video enhancement:

1:Open settings/player/videos/processing, select Render method to DXVA, enable Allow hardware acceleration-DXVA2 and Allow use DXVA Video Super Resolution. Navigate to settings/system/logging and click Enable debug logging to start the debug log.

2:Set the monitor's refresh rate to 60Hz and resolution to 1080p, 2K, or 4K. Make sure the video's resolution is lower than the monitor's resolution, as this is the only way for RTX video enhancement to work.

3:Play a video with a resolution lower than the monitor's resolution. After enabling debug logging, you should be able to see the real-time refresh rate directly on the screen. You will notice that it does not stay at 60Hz and mostly fluctuates between 40 and 55Hz.

4:After disabling Allow use DXVA Video Super Resolution, the frame rate will stay at a stable 60Hz.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/user-attachments/files/17821182/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Desktop Screenshot 2024 11 20 - 04 49 41 92](https://github.com/user-attachments/assets/d03088b0-f584-45f5-a38e-7743273eb31a)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

For me, if the video doesn't have frame interpolation, it is not smooth and unwatchable. I hope to utilize the TV's frame interpolation feature to watch videos smoothly

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
From what you describe it seems, that the current implementation or the GPU cannot keep up creating 60 fps from a full hd source to 4k output using 60 hz with Superresolution.

Is that needed?
You play a 24p (23.98 fps) file on a 60 Hz Display, which is not needed that way. You can try to enable "Adjust Refreshrate to match video" that way your TV would switch to 24p mode - and your GPU does not need to upscale 60 frames per second but only 23.98, that should make it usable.

If you open your player debug (ctrl o) you should see a whole lot of skipped frames the way you are using it right now.

Now back to the question: Is this normal or not - I cannot say, if optimizations are possible, e.g. only creating ready to use 23.98 fps and then just output them 3:2 might be considerable, depends on current implementation and at which state the super resolution comes into the game.

**Comment by Pixellevel** [comment]
> From what you describe it seems, that the current implementation or the GPU cannot keep up creating 60 fps from a full hd source to 4k output using 60 hz with Superresolution.
> 
> Is that needed? You play a 24p (23.98 fps) file on a 60 Hz Display, which is not needed that way. You can try to enable "Adjust Refreshrate to match video" that way your TV would switch to 24p mode - and your GPU does not need to upscale 60 frames per second but only 23.98, that should make it usable.
> 
> If you open your player debug (ctrl o) you should see a whole lot of skipped frames the way you are using it right now.
> 
> Now back to the question: Is this normal or not - I cannot say, if optimizations are possible, e.g. only creating ready to use 23.98 fps and then just output them 3:2 might be considerable, depends on current implementation and at which state the super resolution comes into the game.

1: As you mentioned, it doesn’t need to output 4K at 60Hz. I tried using the Whitelist feature under Settings/System, selecting specific resolutions, and enabling Allow 3:2 pulldown refresh rates and Allow double refresh rates. However, in this case, NVIDIA’s video upscaling does not work.

2: Enabling Adjust display refresh rates doesn’t completely resolve the issue. While it looks much better, about half the time, there are still minor stutters—sometimes slight and other times more consistent side-to-side jitter. I noticed the frame rate fluctuates between 22.4-23.4 fps or sometimes 23.4-24.4 fps.

3: As you mentioned, only creating ready-to-use 23.976 fps frame rates and outputting them with a 3:2 pulldown seems to be the most likely solution to this issue. To my knowledge, the TV performs a reverse 3:2 pulldown on the HDMI input, restoring it to 23.976 fps before applying motion smoothing. I have a 4K 60Hz Android TV box, and video playback from it almost never stutters. However, when I try to use the TV’s motion smoothing with video output from my PC, stuttering is almost always present.

I mainly use MPV and tried many settings without success until I changed the video sync method to video-sync = display-resample-vdrop. With this configuration enabled, when I perform seek operations, the behavior is very similar to what happens with my Android TV box: after each forward or backward seek in the video, there is a slight jitter that lasts for about 0.5 seconds, after which the jitter disappears, and the playback becomes smooth without any further stuttering.

This makes me believe that the video sync method is crucial for compatibility with the TV’s motion smoothing feature. If possible, I hope you can consider applying this configuration in your optimizations.

Thank you very much for your time and effort!

**Comment by fritsch** [comment]
I think there is a misunderstanding. Your PC has no single idea how the TV processes the input frames. There is no feedback to this. When you want your TV to create / produce the intermediate frames, you should not shoot 60 fps at it, but only the 23.98 fps, so that it can do its interpolation by itself.

For the mpv vdrop argument ... this will just hardcore throw away video frames, when audio / video goes out of sync. This will look horrible. So you ask the player to drop frames, which effectively makes it render less frames.

Kodi does the same - which is why you see your framerate from kodi drop ... we do not call that dropping, but skipping as it happens in renderer.

You need to make a decision: Shall your TV interpolate additional frames for you or do you want to do the 3:2 Pull Up your self - as the performance of your device is not sufficient (see also your vdrop in mpv argument) I would rather suggest you output the 24p only and let your TV handle it ...

**Comment by Pixellevel** [comment]
Playing a 23.98fps video and outputting a 23.98fps signal to the TV, then enabling motion compensation, seems like a reasonable approach to achieving the best motion compensation effect. However, this is not the case in reality. I've tried this more than once, and when playing a 29.97fps video and outputting a 29.97fps signal to the TV, whether it's through a TV box or a PC, motion compensation doesn't work well when the signal is output this way. My TV box always outputs at 60Hz, regardless of the content's frame rate, and this seems to produce the best motion compensation results.I believe the TV's motion compensation feature is optimized for 60Hz input.

[https://youtu.be/CuEZIJDEQyo?t=128](url)   
[https://youtu.be/AUipoxcYtas?t=376](url)

These two videos mention that the TV will try to guess the actual frame rate of the input signal, and when motion compensation is set to maximum, it will always perform reverse 3:2 pull-down.

As for the sync method display-resample-vdrop: Resample audio to match the video. Drop video frames to compensate for drift. I think this prevents stuttering when playing videos on my TV with mpv because discarding some frames during the seek/jump process for audio-video sync is reasonable. At that moment, the TV also resynchronizes the image to run motion compensation. Without this frame dropping step, the TV might not notice that the video has jumped, which could cause motion compensation issues and result in screen stuttering. This may also be the default behavior of TV boxes when playing videos.

I see the frame rate drop and maybe it's because "Allow use DXVA Video Super Resolution" tries to enhance all sixty frames, causing performance issues. In fact, it only needs to enhance the original video and then pass the signal using 3:2 pull-down. If that's not the case, I don't believe the 4060 Ti's performance is insufficient to run this function.

**Comment by Pixellevel** [comment]
vo=gpu-next
hwdec=d3d11va
gpu-api=d3d11
scale=ewa_lanczos4sharpest
vf=d3d11vpp=scale=2:scaling-mode=nvidia 

### 
function autovsr()
    display_width = mp.get_property_native("display-width")
    video_width = mp.get_property_native("width")
    display_height = mp.get_property_native("display-height")
    video_height = mp.get_property_native("height")
    pixfmt = mp.get_property_native("video-params/hw-pixelformat") or mp.get_property_native("video-params/pixelformat")
    if video_width ~= nil and display_width ~= nil then 
        scale = math.max(display_width,display_height) / math.max(video_width,video_height)
        scale = scale - scale % 0.1
        if string.match(mp.get_property("vf"),"@vsr") then
            mp.command("vf remove @vsr")
        end
        if scale > 1 then
            if pixfmt == "nv12" or pixfmt == "yuv420p" then
                mp.command("vf append @vsr:d3d11vpp:scaling-mode=nvidia:scale="..scale)
            end
        end
    end
end
mp.observe_property("video-params/pixelformat", "native", autovsr)
mp.observe_property("vf", "native", autovsr)



I have already implemented this feature in the MPV player, and now the issue is resolved.
