### ISSUE TITLE
Setting default SUBs language to "Greek (Modern)" in player UI or Settings is not ever respected/used

### ISSUE THREAD

**Issue by mackonsti** [xbmc/xbmc#26004]
### Describe the bug
In the latest iterations of Kodi (even since v19) when I playback a video content e.g. MKV and select in the player interface to ENABLE subtitles and set "Greek (Modern)" as default language, then apply for all content, although the command is accepted, this is not working.

So alternatively, I went to the Settings of the Player and Subtitles tab/screen, put "Greek" as default subtitle language to display, but this is not working either. The MKV is confirmed to contain multiple language tracks, including Greek (Modern) as ISO code `el` or `gre` (confirmed on PC with MkvToolNix for example) but KODI never picks up that subtitle track.

The issue was encountered on SubStationAlpha subtitles as well as SRT. Moreover, it could happen on MP4 video files but I have not seen any with multiple subtitle tracks yet (hence focusing on MKV that **I confirm being 100% reproduced**).

## Expected Behavior

Whether setting "Greek (Modern)" as default subtitles language to pick-up in Settings > Player > Subtitles, or from within the player interface / options, the MKV files that do contain confirmed subtitle tracks with ISO code `el` or `gre` should be picking up that respective subtitle track instead.

## Actual Behavior

Setting "Greek (Modern)" as default subtitles language  in Settings > Player > Subtitles, or from within the player interface / options, the MKV files that do contain confirmed subtitle tracks with ISO code `el` or `gre`, the playback eventually uses the FIRST available subtitle track int that MKV file.

## Possible Fix

None. Automatic subtitle language selection fails.
The only way is for the user to keep selecting this language "Greek (Modern)" for each player instance.

### To Reproduce

1. Go to  Settings > Player > Subtitles
2. Select default subtitle as "Greek (Modern)"
3. Launch playback of an MKV that contains multi-subtitle tracks and Greek as `el` or `gre`
4. First or default subtitle track is shown, instead

Moreover:
1. During the playback of an MKV file, in player bring up the subtitle options
2. Set to enable subtitles and select "Greek (Modern)" as chosen language
3. In the prompt to save this settings for all media, choose YES
4. First or default subtitle track is shown, instead

**P.S. Manually selecting the Greek language from the MKV's detected list of subtitles, WORKS.**

### Debug log

No debug log attached or generated.

### Screenshots 

No screenshots taken, the issue is rather straightforward but I can provide if I am asked (with clear instructions as to what to show).

## Additional context or screenshots (if appropriate)

No additional context. I am just afraid the code does not take into consideration `el` or `gre` in this case, despite showing "Greek (Modern)" as available language in the drop-down menus.

### Your Environment
Used Operating system:

 - [X] Android (whether on Android TV box or Amazon FireTV stick)
 - [ ] iOS / tvOS
 - [ ] Linux / macOS
 - [ ] Windows / UWP

 Operating system version/name:
 - Kodi version: 19.x and also 20.x (all versions) but bug re-confirmed on Kodi 20.1 (latest)

*Note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
> but bug re-confirmed on Kodi 20.1 (latest)

kodi 20 is not the last version, last version is kodi 21, and the development version is 22

i confirm the problem, there is a wrong conversion of language codes, looks like caused by the language list names thats for some reason that idk is not conform to specs

**Comment by mackonsti** [comment]
Hello @CastagnaIT apologies, I got confused, you are right, I meant to write Kodi v21. Nevertheless this bug exists since probably v18 and I always thought it was me doing something wrong 😂 Thank you for confirming this 🙏

**Comment by CastagnaIT** [comment]
its possible that there are more languages with same problem
but there is no need to find each one, the fix covers all use cases

**Comment by mackonsti** [comment]
Thank you, looking forward to your fixed release. Take care.

**Comment by CastagnaIT** [comment]
> How to add subtitles in Albania in Kodi Omega please ?

for general help request please use the kodi forum,
to signal other bugs please open an Issue and fullfill issue template
