### ISSUE TITLE
No option to enable subtitles 

### ISSUE THREAD

**Issue by garrettseepersad** [xbmc/xbmc#26001]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When I pause the movie I'm streaming from Seren, I should see options for e.g. enable subtitles

## Actual Behavior

There's no options, can only pause, play, forward and rewind 

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![PXL_20241122_190415726.jpg](https://github.com/user-attachments/assets/eedf61ae-0a9f-42a9-88db-49882c8c9c8a)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

 

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
https://mirrors.kodi.tv/nightlies/android/arm/Omega/

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by garrettseepersad** [comment]
Worked fine with the official release. 

I downloaded the nightly build so I can use the Google TV remote app with Kodi.

**Comment by garrettseepersad** [comment]
Seems similar to this issue

https://github.com/xbmc/xbmc/issues/25688#issue-2499392035

**Comment by garrettseepersad** [comment]
If I type "L" on the keyboard, subtitles enable

**Comment by Hitcher** [comment]
No support for banned addons.
