### ISSUE TITLE
Now using a C++20 feature

### ISSUE THREAD

**Issue by mglae** [xbmc/xbmc#26018]
### Describe the bug
Here is a clear and concise description of what the problem is:

Both #25630 and #25982 do introduce `using enum` declarations.

This is a C++20 feature but CODE_GUIDELINES.md show:

> ## 2. Language standard
> We currently target the C++17 language standard. Do use C++17 features when possible (and supported by all target platforms). Do not use C++20 features.

Compilation does fail with gcc <= 10

### Debuglog

The debuglog can be found here: Not needed

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OpenSUSE
 - Kodi version: master dd66f3f4aa

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Master has been using c++20 for a while now.
https://github.com/xbmc/xbmc/pull/24900

Guess docs need an update

**Comment by mglae** [comment]
I see

**Comment by garbear** [comment]
@mglae if you wanna notch a PR you can send a PR updating the docs.
