### ISSUE TITLE
Audio initializes with a delay after video start or unpause

### ISSUE THREAD

**Issue by lynx31** [xbmc/xbmc#26066]
### Describe the bug

Whenever a video is played or unpaused audio will start with a delay that can be up to 10 seconds

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Audio should start together with video

## Actual Behavior

Audio starts only after a few seconds (sometimes longer). To be clear, audio and video are in sync, there is just an initialization delay

## Possible Fix

None found

### To Reproduce

1. Run Kodi 
2. Select video to play
3. Start video 

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/upucaqinaz.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 22.0-ALPHA1 (21.90.700), but also other versions 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Debug log contains banned add-ons (piracy). Then no support to this report.
