### ISSUE TITLE
Cross-Complied ffmpeg lib  Failed！

### ISSUE THREAD

**Issue by Hope10086** [xbmc/xbmc#26064]
### Describe the bug
Here is a clear and concise description of what the problem is:

I try to run "make-mingwlibs.bat" as described in [Windows build guide](https://github.com/xbmc/xbmc/blob/master/docs/README.Windows.md#6-build-kodi-manually).
Then something went wrong.

## My Problems when building on Windows10
Here is a clear and concise description of what was expected to happen:

First of all, I can't download ffmpeg by sh _"buildffmpeg.sh"_. So I annotated `#do_clean_get $1`, downloaded it manually through the browser and placed it in the corresponding path` D:\xbmc\project\BuildDependencies\build\ffmpeg-6.0.1`. Then , I could run ```
```
$LOCALSRCDIR/configure --target-os=$FFMPEG_TARGET_OS --prefix=$FFMPEGDESTDIR --arch=$ARCH \
  $FFMPEG_OPTS_SHARED \
  --extra-cflags="$extra_cflags" --extra-ldflags="$extra_ldflags"
```

Then the _config.log_ tell me to enable--cross-compiled. 
I add `"do_addOption "--enable-cross-compile"` in  _"buildffmpeg.sh"_
Then,the _config.log_  shows that cl.exe cannot be linked to LIBCMT.lib
So I manually added MSVC's LIBCMT.lib path as :
```
extra_ldflags="$extra_ldflags -LIBPATH:\"D:\\MicrosoftVisualStudio\\2022\\VC\\Tools\\MSVC\\14.42.34433\\lib\\x86\""
extra_cflags="-I$LOCALDESTDIR/include -I/depends/$TRIPLET/include -I\"D:\\MicrosoftVisualStudio\\2022\\VC\\Tools\\MSVC\\14.42.34433\\include\" -DWIN32_LEAN_AND_MEAN"
export LIB="D:\\MicrosoftVisualStudio\\2022\\VC\\Tools\\MSVC\\14.42.34433\\lib\\x86;$LIB"
```
Then , the _config.log_  still tell  me  "LINK : fatal error LNK1104: 无法打开文件“kernel32.lib”
I tried to manually add the path to kernel32.lib but it didn't work:
```
export LIB="C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\um\\x86;$LIB"
extra_ldflags="$extra_ldflags -LIBPATH:\"C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\um\\x86\""

```

### Debuglog

The debuglog can be found here:

> 1. "--enable-cross-compile"
```

- ffmpeg-6.0.1 (win32) ......................................... [Configuring] cl.exe is unable to create an executable file. If cl.exe is a cross-compiler, use the --enable-cross-compile option. Only do this if you know what cross compiling means. C compiler test failed.
- 
- If you think configure made a mistake, make sure you are using the latest version from Git. If the latest version fails, report the problem to the [ffmpeg-user@ffmpeg.org](mailto:ffmpeg-user@ffmpeg.org) mailing list or IRC #ffmpeg on irc.libera.chat.
- Include the log file "ffbuild/config.log" produced by configure as this will help solve the problem. ffmpeg-6.0.1 (win32) ........................................... [Compiling] make: *** No targets specified and no makefile found. Stop. make: *** No rule to make target 'install'. Stop. ffmpeg-6.0.1 (win32) ............................................... 
[Error] failed to compile /xbmc/project/BuildDependencies/mingwlibs/win32/lib/avcodec.lib

```

> 2 LIBCMT.lib

test_ld cc test_cc BEGIN ./ffconf.joMygx5S/test.c 1 int main(void){ return 0; } END ./ffconf.joMygx5S/test.c cl.exe -I/local32/include -D_FORTIFY_SOURCE=2 -nologo -I/local32/include -I/depends/win32/include -DWIN32_LEAN_AND_MEAN -c -Fo./ffconf.joMygx5S/test.o ./ffconf.joMygx5S/test.c test.c /build/ffmpeg-6.0.1/compat/windows/mslink -LIBPATH:/local32/lib -LIBPATH:/mingw32/lib -LIBPATH:/depends/win32/lib -nologo -out:./ffconf.joMygx5S/test.exe ./ffconf.joMygx5S/test.o LINK : fatal error LNK1104: 无法打开文件“LIBCMT.lib” C compiler test failed.

3.kernel32.lib

```
`cl.exe -I/local32/include -D_FORTIFY_SOURCE=2 -I/local32/include -I/depends/win32/include -I"D:\MicrosoftVisualStudio\2022\VC\Tools\MSVC\14.42.34433\include" -DWIN32_LEAN_AND_MEAN -nologo -I/local32/include -I/depends/win32/include -ID:MicrosoftVisualStudio2022VCToolsMSVC14.42.34433include -DWIN32_LEAN_AND_MEAN -c -Fo./ffconf.IlIFCgFS/test.o ./ffconf.IlIFCgFS/test.c
test.c
/build/ffmpeg-6.0.1/compat/windows/mslink -LIBPATH:"/local32/lib" -LIBPATH:"/mingw32/lib" -LIBPATH:"/depends/win32/lib" -LIBPATH:"D:\MicrosoftVisualStudio\2022\VC\Tools\MSVC\14.42.34433\lib\x86" -LIBPATH:/local32/lib -LIBPATH:/mingw32/lib -LIBPATH:/depends/win32/lib -LIBPATH:D:MicrosoftVisualStudio2022VCToolsMSVC14.42.34433libx86 -nologo -out:./ffconf.IlIFCgFS/test.exe ./ffconf.IlIFCgFS/test.o
LINK : fatal error LNK1104: 无法打开文件“kernel32.lib”
C compiler test failed.`
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

My    [_"buildffmpeg.sh"_:](https://github.com/Hope10086/xbmc/commit/f8b4d8a52ce814390eb24140d668b9e09b6fd072)
![QQ_1733625780371](https://github.com/user-attachments/assets/754ad61d-78cd-418f-a5bf-1080e638f361)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ √] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Seems you are not calling the correct files:

Make sure use file corresponding platform x64 in path:

`..\kodi\tools\buildsteps\windows\x64`

and not directly in `..\kodi\tools\buildsteps\windows`

> First of all, I can't download ffmpeg by sh "buildffmpeg.sh".

This script is not intended to be called directly, only is used internally.

You should only call:

`..\kodi\tools\buildsteps\windows\x64\make-mingwlibs.bat`
