### ISSUE TITLE
Kodi 21.x issue handling some M3U8 files

### ISSUE THREAD

**Issue by TheGiantHogweed** [xbmc/xbmc#26060]
### Describe the bug
Using some M3U8 files it seems that Kodi 21.x can't handle them, while there were no problems with Kodi 20.x
Here's the link to the post in the discussion where a couple of vids show the behavior; scrollling up in the discussion you should also be able to download the M3U8 file used to show the issue. Or ask me in case of problems, and I'll provide it.
[https://forum.kodi.tv/showthread.php?tid=379666&pid=3218165#pid3218165](url)

note: I added an empty issue in the system before this by mistake... sorry.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by TheGiantHogweed** [comment]
The link to the post in the description for some reasons doesn't work.
Let's try with this.
https://forum.kodi.tv/showthread.php?tid=379666&pid=3218165#pid3218165

**Comment by TheGiantHogweed** [comment]
[Stream.zip](https://github.com/user-attachments/files/18048050/Stream.zip)
Trying to attach the file...

**Comment by ksooo** [comment]
Okay, step-by-step: First, we need a debug log. Start Kodi, click the m3u8, click on one of the items. Once you have seen the error message that the item cannot be played, close Kodi. Post the debug log here.

**Comment by ksooo** [comment]
> When I browse the video folder for this file with Kodi 20.4 when I click on it the streaming starts normally.
> But if I do the same using Kodi 21.1, streaming doesn't start. Instead it opens three more choices

As a fix, Kodi 21 does not ignore the value of advanced setting "playlistasfolders" any more. Default value for that setting is "true".  I guess you have not changed that value, so you are seeing now a listing of the items contained in the playlist. Can you change the advanced setting value and report how behavior is then? Still playback error?

>  all named "197386" 

 Not sure this also looks this "ugly" with Kodi 20, but I think so. Could you check this for me?
 
> with none working.

 This is another problem. We need to find out why playback does not work.

**Comment by TheGiantHogweed** [comment]
> Okay, step-by-step: First, we need a debug log. Start Kodi, click the m3u8, click on one of the items. Once you have seen the error message that the item cannot be played, close Kodi. Post the debug log here.

Hi,
here's the log file.
[kodi.log](https://github.com/user-attachments/files/18048363/kodi.log)

**Comment by TheGiantHogweed** [comment]
> > When I browse the video folder for this file with Kodi 20.4 when I click on it the streaming starts normally.
> > But if I do the same using Kodi 21.1, streaming doesn't start. Instead it opens three more choices
> 
> As a fix, Kodi 21 does not ignore the value of advanced setting "playlistasfolders" any more. Default value for that setting is "true". I guess you have not changed that value, so you are seeing now a listing of the items contained in the playlist. Can you change the advanced setting value and report how behavior is then? Still playback error?
> 
> > all named "197386"
> 
> Not sure this also looks this "ugly" with Kodi 20, but I think so. Could you check this for me?
> 
> > with none working.
> 
> This is another problem. We need to find out why playback does not work.

Don't worry about that, I didn't notice back then that the default choice for v21.1 was "browse into", while with v20.4 it goes with "play". I believe that this different is because new version doesn't recognize that file in the same way.
So just consider what you see in my video, where I right click and then I choose "play".

Do you have both versions installed just to see if you too have this behavior?

**Comment by the-black-eagle** [comment]
Errr, we don't support piracy here so please reproduce your issue using a clean copy of Kodi. See https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons for more info.

Thanks!

**Comment by TheGiantHogweed** [comment]
That file is just an example to show the developers the different behavior between 20.x / 21.x
If you are technically talking about the construction of a knife, that doesn't make you automatically a killer...
Or are you saying that 21.x is detecting the content and that is the reason for the issue?

**Comment by ksooo** [comment]
Please provide an m3u8 with legit media data, which we can use to reproduce the problem. Otherwise we will not help you. Strict rules of play. No support for piracy.

**Comment by TheGiantHogweed** [comment]
> Please provide an m3u8 with legit media data, which we can use to reproduce the problem. Otherwise we will not help you. Strict rules of play. No support for piracy.

I don't know, a developer may want to replace the URLs with others if he does not want to test with those.
I don't need any support, I'm not asking for any help. I can just open those files with VLC, and as a developer myself I have many other ways.
I just noticed that there is this difference between the two versions of Kodi using the same file, it's just a report that might be interesting for developers who are trying to fine-tune the software.
You keep focusing on what is streamed, that's just the means, it's not the end.
I repeat, I don't need any help, if the different behaviour of Kodi versions has an explanation, or is of no importance in this case, simply ignore this report.
If, on the other hand, it is representative of something interesting, I will be glad to have contributed.

Best

**Comment by the-black-eagle** [comment]
It isn't what you're streaming - its the banned repos and plugins.  We don't and won't support anything to do with piracy. End of.

**Comment by TheGiantHogweed** [comment]
I think you didn't get the point.
Fine, close and delete this report.

**Comment by ksooo** [comment]
Root cause: Cloudflare is blocking Kodi User-Agent.

**Comment by TheGiantHogweed** [comment]
> Root cause: Cloudflare is blocking Kodi User-Agent, sending 403 when requesting access to the resource given in the m3u8. We have seen this before for other http(s) endpoints.

Very kind!
Thank you very much for your explanation, really appreciated.

**Comment by ksooo** [comment]
So, because they are blocking only selected resources requested using the Kodi User-Agent, it might be very well the case that your media source is known to them to be requested by some Kodi piracy add-ons. Nothing we want to mess with.

**Comment by TheGiantHogweed** [comment]
I don't want you to mess with anything.
My only curiosity was about the fact that this happens only with 21.x
Maybe some changes in the User.Agent from 20.x...

**Comment by ksooo** [comment]
> Maybe some changes in the User.Agent from 20.x...

For sure it changed, as the User-Agent contains the Kodi version number.
