### ISSUE TITLE
ERROR: Openssl not found when building

### ISSUE THREAD

**Issue by Hope10086** [xbmc/xbmc#26070]
### Describe the bug

Hi! I am new to xbmc. I've had some stupid mistakes [Issue#26064](https://github.com/xbmc/xbmc/issues/26064) before .
I encountered this problem when configuring ffmpeg :`ERROR: openssl not found`
The config.log as follow:
```
cl.exe -I/local64/include -D_FORTIFY_SOURCE=2 -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_USE_MATH_DEFINES -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS -D_WIN32_WINNT=0x0600 -nologo -I/local64/include -I/depends/x64/include -DWIN32_LEAN_AND_MEAN -c -Fo./ffconf.duCGyYLS/test.o ./ffconf.duCGyYLS/test.c
test.c
./ffconf.duCGyYLS/test.c(1): fatal error C1083: 无法打开包括文件: “openssl/ssl.h”: No such file or directory
ERROR: openssl not found
```
Since I wasn't sure if the library openssl referred to Windows 10 or msys2, I installed both.

> Msys2:
Run  # pacman -S mingw-w64-x86_64-openssl  on msys2:
Then type `openssl ` to  check the installation is successful.

> Window10:
 Install openssl by Win64OpenSSL-3_4_0.msi and add to environment path.

However, config.log still tell me could not find opeenssl.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![image](https://github.com/user-attachments/assets/f170bc33-1cfd-4c7b-83d0-4422ad68ce8d)
![image](https://github.com/user-attachments/assets/b94a6a2a-085a-41d4-9e2f-c6dc8a2603bd)
See my [buidlffmpeg.sh](https://github.com/Hope10086/xbmc/commit/bfa8436ea94b3bff59b87d3c2d6264b6b1651fd1)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ √] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows10
 - Kodi version:  branch-master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
Please take support questions to the forums https://forum.kodi.tv/index.php

Read the docs carefully. If you follow them precisely, i guarantee it will build correctly.

**Comment by Hope10086** [comment]
> Please take support questions to the forums https://forum.kodi.tv/index.php
> 
> Read the docs carefully. If you follow them precisely, i guarantee it will build correctly.



> Please take support questions to the forums https://forum.kodi.tv/index.php
> 
> Read the docs carefully. If you follow them precisely, i guarantee it will build correctly.
Tank You！
But, I have read the docs for a long time. I did't run the fuction `do_clean_get` beacuse the files maybe lost on [mirrors ](http:[/](http://mirrors.kodi.tv/)/mirrors.kodi.tv/)
![image](https://github.com/user-attachments/assets/c981030d-7214-426d-89be-7e819e2eeb1a)

Then , I check the the fuction `do_clean_get` and its sub-fuction   `do_download` and the  BASE_URL has been set in do_loaddeps() .
  **BASE_URL=http://mirrors.kodi.tv/build-deps/sources**
I try to visit the URL but found is inexistence.
**_There is no path named build-deps_**
![image](https://github.com/user-attachments/assets/cd765514-6f85-4135-927d-995f382e7357)


```
do_download() {
  if [ ! -d "$LOCALSRCDIR" ]; then
    if [ ! -f /downloads/$ARCHIVE ]; then
      do_print_status "$LIBNAME-$VERSION" "$orange_color" "Downloading"
      do_wget $BASE_URL/$ARCHIVE $ARCHIVE
    fi

    do_print_status "$LIBNAME-$VERSION" "$blue_color" "Extracting"
    mkdir $LOCALSRCDIR && cd $LOCALSRCDIR
    tar -xf /downloads/$ARCHIVE --strip 1
  fi
  # applying patches
  local patches=(/xbmc/tools/buildsteps/windows/patches/*-$LIBNAME-*.patch)
  for patch in ${patches[@]}; do
    echo "Applying patch ${patch}"
    if [[ -f $patch ]]; then
      patch -p1 -d $LOCALSRCDIR -i $patch -N -r -
    fi
  done
}
```
```
`do_loaddeps() {
  local file="$1"
  LIBNAME=$(grep "LIBNAME=" $file | sed 's/LIBNAME=//g;s/#.*$//g;/^$/d')
  VERSION=$(grep "VERSION=" $file | sed 's/VERSION=//g;s/#.*$//g;/^$/d')
  ARCHIVE=$LIBNAME-$VERSION.tar.gz

  **BASE_URL=http://mirrors.kodi.tv/build-deps/sources**
  local libsrcdir=$LIBNAME-$VERSION

  LOCALSRCDIR=$LOCALBUILDDIR/src/$libsrcdir
  LIBBUILDDIR=$LOCALBUILDDIR/$LIBNAME-$TRIPLET
}`
```

**Comment by fuzzard** [comment]
https://mirrors.kodi.tv/build-deps/sources/ is valid. if you visit it you must have the trailing /

Once again, please take questions to the forums. This issue tracker is not for support queries, and lots of people are notified every time a message is posted here.
