### ISSUE TITLE
Adding copy-paste option on Android

### ISSUE THREAD

**Issue by razorblade23** [xbmc/xbmc#26086]
Its not possible to paste text to Kodi Android interface (Add Source)
It just goes one step back when holding tap to open "context menu"

Is it possble to add a paste button to a virtual keyboard, or extend it in some way to support pasting?

**Comment by the-black-eagle** [comment]
Please use the forum https://forum.kodi.tv/forumdisplay.php?fid=9 for feature requests.  This is a bug tracker only.

Thanks.
