### ISSUE TITLE
[Feature Request] Favourites groups

### ISSUE THREAD

**Issue by iam333** [xbmc/xbmc#26080]
## Roadmap or todo item
Hi!Thanks in advance!

I use the favorites section many often and I think that the possibility of being able to group the items that are added to this section in groups, as directories, that could be created for each users, for example a Films group where target all movie links of the different Addons.

### Context

I have seen some addon as "simple favourites" that does something similar, but I think it would be much more useful if it came integrated into the Kodi platform.

Thank you so much!

### Additional context, screenshots or links
The "simple favourites" plugin has been discontinued for years, but someone has continued to use it. I attach the link: https://github.com/notoco/univk19/tree/master/zip/plugin.program.simple.favourites

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by chewitt** [comment]
Please make feature requests in the forum, this is a tracker for bugs only. Thanks.
