### ISSUE TITLE
MacOS video Debug Info missing? or impossible?

### ISSUE THREAD

**Issue by keplx** [xbmc/xbmc#26089]
### Describe the bug
Here is a clear and concise description of what the problem is:

There is no key-combo to invoke video Debug Info while video is playing on MacOS.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Player Debug Info
Shift-CTRL-O provides some information.  It is available to MacOS.

Video Debug Info
Alt+O is not available to MacOS

## Actual Behavior

missing

## Possible Fix

beyond my skillset

### To Reproduce

1. try pressing Option+O
2. --

### Debuglog

The debuglog can be found here:

this isn't a bug.  it's a missing feature in the brotherhood of OSes

### Screenshots 
Here are some links or screenshots to help explain the problem:

<img width="768" alt="Screenshot 2024-12-12 at 8 37 01 PM" src="https://github.com/user-attachments/assets/bae5e318-b7c2-4639-a544-0a9acaa8c9b8" />

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

null

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: MacOS Sonoma
 - Kodi version: omega

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Hitcher** [comment]
As the wiki says 'This display is available on MS Windows systems only'.

**Comment by keplx** [comment]
> As the wiki says 'This display is available on MS Windows systems only'.

Yes, that was in my screenshot.  Why is this not possible?
