### ISSUE TITLE
[Fire Stick 4k Max 2023] Doing IEC61937 8ch 192kHz passthrough

### ISSUE THREAD

**Issue by phhusson** [xbmc/xbmc#26084]
Hello from a NOVA Video Player developer!

As a developer, we love what you do, and it's always very useful to check your code, as it's usually functional and very readable.

Anyway, as a token of gratitude, I want to gift you this patch: https://github.com/nova-video-player/aos-Video/commit/66aa8dea628f6744ee0c8e5c429ee69f15f6e6bc

Basically, as you probably know, there was a stupid bug in AOSP until Android 12 that 8ch IEC61937 was forbidden even when audio hal allowed it, preventing TrueHD and DTS-HDMA passthrough.

On specifically Amazon FireTV devices, Amazon moved the code forcing only stereo IEC61937 to some weird dynamic-ish code, which makes it easy for us to remove that check through a bit of introspection
With this change, I can passthrough TrueHD and DTS-HDMA on that device with NOVA Video Player, which isn't possible otherwise (since pushing directly TrueHD on this device outputs EAC3, and pushing directly DTS-HDMA outputs DTS core...)

I know it's a hack, so maybe you don't want it (it would be clearly look like a disgrace compared to the overall quality of your code).

Kind Regards

**Comment by fuzzard** [comment]
Cheers. Will close this, but will ping @fritsch as im sure it may peak his curiosity.

**Comment by fritsch** [comment]
Thank you very much. Yeah - for kodi - we have one principle: No custom firmware hacks, no device specific workarounds. Reason for this is: We want that Android gets a usable standard and nice implementations for everyone.

If we would start this can of worms, we needed to bring stagefright back, we needed to bring AML 192 khz /8 channel passthrough back and maybe even S16NE passthrough, known as shitty build in kodi.

How are you doing this in Novaplayer? Are you having many of those vendor hacks in there? Or is the FireTV your first one?

Thanks again - I won't pull that code in out of the named reason.

**Comment by phhusson** [comment]
> How are you doing this in Novaplayer? Are you having many of those vendor hacks in there? Or is the FireTV your first one?

I don't know, we don't have any actual rule. When receiving bug reports we just see what we can reasonably do :shrug: . We used to have gralloc hacks and various stuff (and technically it's still there, but dead code...), but nowadays you can have most of the features working quite reasonably with just Android APIs (well, like everyone we hated Google for the broken NDK features, where we jump between java/ndk audiotrack/mediatrack back and forth)

But yeah, once upon a time, on Samsung devices, there was a Java JIT bug, where we literally added 10 000 lines of `i++;` to prevent the JIT to optimize a function otherwise it would crash, so yeah we can merge extreme things when it's extremely broken.

In the case of that FireStick passthrough, the code is quite self-contained, the API for audio playback is still the standard Android one. If this hack no longer works, it's just a noop. So overall, it is not a terrible burden to support.
