### ISSUE TITLE
Seek issue

### ISSUE THREAD

**Issue by quickmic** [xbmc/xbmc#26092]
(at least for) http content -> If seekposition is greater than runtime, Kodi freezes for several seconds.

No matter what's the actual reason, simply intercept seekpositions > runtime. That's not valid.
All versions <= 21 are affected

Thanks

**Comment by KarellenX** [comment]
Please fill out the report correctly using the template.
I'll reopen in once done.

**Comment by quickmic** [comment]
Fixing the issue is probably two lines in the code, anyway...

The response is as excepted, keep it closed. I won't bother you again.
