### ISSUE TITLE
libnfs API change in most recent release

### ISSUE THREAD

**Issue by sahlberg** [xbmc/xbmc#26103]
In the most recent version of libnfs I have had to break the API in order to make READ operations zero-copy.
Zero-copy read will make performance SIGNIFICANTLY better, especially for low-end devices such as RPi and similar.

This change has been planned for a long time but is now ready to go  and will possible land in distros in the next weeks/months/quarters.

A compile-time check is available to determine whether we have the old or new API.

An example on how to make the source code for an applicatiopn compatible with either API si shown below. This is from fio :
```
diff --git a/engines/nfs.c b/engines/nfs.c
index 6bc4af1f..13b55038 100644
--- a/engines/nfs.c
+++ b/engines/nfs.c
@@ -157,16 +157,28 @@ static int queue_write(struct fio_libnfs_options *o, struct io_u *io_u)
 {
        struct nfs_data *nfs_data = io_u->engine_data;
 
+#ifdef LIBNFS_API_V2
+       return nfs_pwrite_async(o->context, nfs_data->nfsfh,
+                               io_u->buf, io_u->buflen, io_u->offset,
+                               nfs_callback, io_u);
+#else
        return nfs_pwrite_async(o->context, nfs_data->nfsfh, io_u->offset,
                                io_u->buflen, io_u->buf, nfs_callback, io_u);
+#endif
 }
 
 static int queue_read(struct fio_libnfs_options *o, struct io_u *io_u)
 {
        struct nfs_data *nfs_data = io_u->engine_data;
 
+#ifdef LIBNFS_API_V2
+       return nfs_pread_async(o->context, nfs_data->nfsfh,
+                               io_u->buf, io_u->buflen, io_u->offset,
+                               nfs_callback, io_u);
+#else
        return nfs_pread_async(o->context, nfs_data->nfsfh, io_u->offset,
                                io_u->buflen, nfs_callback, io_u);
+#endif
 }

```
Kodi will need the same type of ifdef checks.
Sorry for this, but this will make performance a LOT better for especially low-end devices.

**Comment by sundermann** [comment]
@sahlberg Is there anything else we'd need to consider other than fixing the compile time errors? To make it compile again the only changes were swapping the buffer and size parameters. https://github.com/sundermann/xbmc/commit/6b1d29cd25daf1fdfd27897b7d43f1b8756aa2bc

**Comment by sahlberg** [comment]
No, these should be all the changes you need and then it will compile either with the new api (with zero copy) or it will compile with the old api.

The READ function adds the buffer pointer which was missing from the old API. The READ function takes a new, additional parameter.

The WRITE function only re-orders some arguments so they are in the same order as "posix write", because why not and by changing the signature to READ we have broken all applications already.
