### ISSUE TITLE
TV Show Artwork REFUSES to change

### ISSUE THREAD

**Issue by JohnWPB** [xbmc/xbmc#26116]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Right Click choose Manage/Choose Art/Clear Art
Browse to location of the ClearArt.png file, select it and choose Ok.

The artwork SHOULD then be changed.

## Actual Behavior

The artwork remains the same.  I removed ALL previous artwork from the folder.  I then removed the TV show from the library, and then cleaned the video library.

I then put the folder back into the TV shows folder, and put all new artwork in that folder.  

When I scan that show to the library, the image is STILL tho old one.  Sohehow this is being cached somewhere, and no matter what I do, the original image persists.  After many times removing the artwork from the folder, deleting show from the library, rebooting, reseting... it still persists.
I am using 2 completely different images with different file sizes.

## Possible Fix

When a new image is replaced, clean the cache/link/delete image of the original artwork

### To Reproduce

1. Simply follow my steps above.  Put an image in the show folder, and scan the show into the library.  
2. Then, try to change that image to a different one
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X ] Windows  Current Version, Up to date
 - [ ] Windows UWP

 - Operating system version/name:
 - Windows 11 Current Version, Up to date
 - Kodi version: 21.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
You need to wait for the 24 hour cache to expire. Read more here... https://kodi.wiki/view/Artwork/Cache#Loading_textures

In fact, you don't even need to go through the process of using the Choose Art menu options. Just replace the existing image with the new image in your file system and upto 24 hours later (depending on when you are in the cycle), the image will auto-update.

This has been changed in v22 to allow immediate cleaning... https://github.com/xbmc/xbmc/pull/25293

Not really a bug, but the process has been changed anyway, so I'll close this issue as fixed.

**Comment by JohnWPB** [comment]
Thank you! Is there a way to trigger that cache refresh?  Does KODI look at it's data folder(Kodi\userdata) , and compare that with the individual TV & movie folders every 24 hours?!?!

**Comment by KarellenX** [comment]
>Thank you! Is there a way to trigger that cache refresh?

Not easily. You would need to delete the entire thumbnails folder for a full cache refresh, or track down the individual image by searching the textures database for the filename of the specific image to locate in the cache folder. A lot of work, for a single image- might as just wait until tomorrow. Also deleting the full cache may have terrible consequences. If you rely on online artwork, then that artwork may have been deleted for a variety of reasons- duplicate, poor quality.

> Does KODI look at it's data folder(Kodi\userdata) , and compare that with the individual TV & movie folders every 24 hours?!?!

Not quite. It does not check each and every image every 24 hours. It only checks images that are called for viewing, like when you scroll through your library, those images that appear on screen are checked. If you don't load an image on screen, then it is not checked. It then checks the hash of the cached image against a hash of the image in your video folder. If it is the same, nothing happens, if it is different, the new image is cached.

**Comment by JohnWPB** [comment]
Got it... I must say this is VERY odd behavior!  Create an image for a movie/ show, and to see how it looks on screen, wait till tomorrow.......  First time I have seen something quite like this.

Thanks for the fast responses.\

**Comment by KarellenX** [comment]
It is very old code, still from the original xbox days.
