### ISSUE TITLE
Pipewire thread-loop assertion failed

### ISSUE THREAD

**Issue by mredlek** [xbmc/xbmc#26127]
## Bug report

I have regularly crashes of Kodi in combination with Pipewire (and plugging or plugging audio devices). During my investigation of this problem, I found the following, possible related failed assertion.

### Steps to reproduce

1. Open the commandline
1. Run `kodi`
1. Close kodi

### Expected Behavior

Kodi closes without printing anything to the terminal

### Actual Behavior

The following message appeares in the terminal:
```
'this->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:62 do_unlock()
```

### Log
The log can be found here:
[20241219_kodi_pipewire_lock.log](https://github.com/user-attachments/files/18200732/20241219_kodi_pipewire_lock.log)

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

- Arch Linux
- Kodi version: kodi 21.1-3

### Additional information

- I do have self-written addons. 
- I also use a TvHeadend addon.
- My desktop environment is sway (so it uses Wayland)

**Comment by neo1973** [comment]
The assertion is harmless. In the log it can also be seen that Kodi performs a clean shutdown and doesn't crash. If Kodi was not supposed to shutdown then a full debug log needs to be provided (https://kodi.wiki/view/Log_file).

**Comment by popcornmix** [comment]
See https://github.com/xbmc/xbmc/pull/26126
