### ISSUE TITLE
Trying to compile on Arch see error about libexiv2.so.27 lib not found, NOOB question re: build environs

### ISSUE THREAD

**Issue by tomachinz** [xbmc/xbmc#26157]
Had previously a directory in ~/Github/kodi/ which was building into $HOME/kodi-build/kodi or kodi-x11
Then installed Arch but mounting same user folder at /home/ 
and trying to run my compile script:

`cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DCORE_PLATFORM_NAME=x11 -DAPP_RENDER_SYSTEM=gl -B $HOME/kodi-build 
`
and then I see:
```
-- The CXX compiler identification is GNU 14.2.1
-- The C compiler identification is GNU 14.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - broken
CMake Error at /usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:73 (message):
  The C++ compiler

    "/usr/bin/c++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/home/tom/kodi-build/CMakeFiles/CMakeScratch/TryCompile-u5mi8C'
    
    Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_74401/fast
    no such file or directory    
    

 
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
```
### Describe the bug
I was hoping to see kodi begin to compile, as it did under Kubuntu just recently (same folder).

## Expected Behavior
Error about lib not found:
 libexiv2.so.27
I don't know how to install  libexiv2.so.27 sorry! First time compiling under Arch (actually Parch linux).

### Your Environment

 - [ ] Linux Linux putin 6.12.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:31:57 +0000 x86_64 GNU/Linux

**Comment by neo1973** [comment]
Hi! I build Kodi on Arch daily so I'm certain everything is working fine :wink: 

> Had previously a directory in ~/Github/kodi/ which was building into $HOME/kodi-build/kodi or kodi-x11
Then installed Arch but mounting same user folder at /home/
and trying to run my compile script:

I assume you didn't delete **everything** in that folder before attempting to build on Arch/Parch. What you can't do is taking a build directory from a different system and reuse it.

> Error about lib not found:
libexiv2.so.27
I don't know how to install libexiv2.so.27 sorry! First time compiling under Arch (actually Parch linux).

Your log isn't showing this but this is probably an artifact from configuring the build on Kubuntu first. Arch is already on the newer libexiv2.so.28.

I'm going to close this issue as this isn't a bug in Kodi. For general support please create a thread in our forum https://forum.kodi.tv/
