### ISSUE TITLE
Kodi app for jiostore

### ISSUE THREAD

**Issue by GTTech2305** [xbmc/xbmc#26193]
Hi Team,
Now in India there is one more Os Is launched base on Android but it's locked for sideload any app,

Requesting kodi team to publish kodi App for that os
Os Name is jiotv OS 2.o andorid base
Developer console address for push the app in os store.

https://developer.jio.com/

This will help jio stb user to play multimedia inside jiostb no need to exit stb to watch kodi playlist/ player on other devices 

Thanks in advance

**Comment by chewitt** [comment]
This is a development bug tracker. Please make feature requests via the Kodi forum.
