### ISSUE TITLE
DVD Menu broken on Kodi 12.1.0

### ISSUE THREAD

**Issue by caco3** [xbmc/xbmc#26196]
### Describe the bug

I have an RPI3 with LibreElec `12.0.1` and Kodi `21.1.0`.
Attached is a DVD drive and a keyboard.

I can enter the DVD main menu (looking file, first screenshot below) and start playing the movie.
When I press `ESC` and try to enter the DVD main again, only the selection markers get shown (screenshot 2 below).

![Screenshot 1: DVD menu (ok)](https://github.com/user-attachments/assets/7b316f85-4578-4cfc-aeca-6a921ba106df)

![Screenshot 2: DVD menu (broken)](https://github.com/user-attachments/assets/5307002f-dae5-4a2c-a6a9-eced12155120)

The DVD continues playing as the audio still runs.

There seem to be other people having similar issues, but they are 2 years old and relate to ISO file son Samba drives:
 - https://forum.kodi.tv/showthread.php?tid=378716
 - https://github.com/xbmc/xbmc/issues/24955

The first link mentions that it is a regression and was working fine with Kodi `20`. I can confirm this with installing LibreElec `11.0.6` (Kodi `20.3`). There I can got to the Kodi main menu and enter the DVD menu again multiple times.

## Expected Behavior
See documented Kodi 20 behaviour above.

## Actual Behavior
See above

### To Reproduce
1.  Install LibreElec 12 on a system
2. Attach DVD drive
3. Start DVD (movie)
4. Enter the Kodi menu
5. Enter the DVD drive again -> should open DVD menu

### Debuglog
[log-2024-12-30-22.35.54.zip](https://github.com/user-attachments/files/18278164/log-2024-12-30-22.35.54.zip)
[log-2024-12-30-22.37.47.zip](https://github.com/user-attachments/files/18278165/log-2024-12-30-22.37.47.zip)
[log-2024-12-30-22.37.49.zip](https://github.com/user-attachments/files/18278166/log-2024-12-30-22.37.49.zip)
[log-2024-12-30-22.37.50.zip](https://github.com/user-attachments/files/18278167/log-2024-12-30-22.37.50.zip)
[log-2024-12-30-22.38.11.zip](https://github.com/user-attachments/files/18278168/log-2024-12-30-22.38.11.zip)
[log-2024-12-30-22.39.39.zip](https://github.com/user-attachments/files/18278170/log-2024-12-30-22.39.39.zip)
[log-2024-12-30-22.39.46.zip](https://github.com/user-attachments/files/18278171/log-2024-12-30-22.39.46.zip)

### Your Environment
Used Operating system:
 - [x] Linux, RPI3, LibreElec

 ### Operating system version/name:
 - Kodi version: `12.1.0`

**Comment by caco3** [comment]
To debug further, installed the nightly build of LibreElec 13 (2024-12-30, `699af08`) which contains Kodi `21.90.700` ([`776b0aa`](https://github.com/xbmc/xbmc/commit/776b0aa)). The issue seems to be fixed. Thus I am closing this issue.

Thanks for your great work!

**Comment by neo1973** [comment]
Something is going wrong with atomic mode settings. Log is full of this error:
```
2024-12-30 23:27:43.760 T:1158    error <general>: CDRMAtomic::DrmAtomicCommit - atomic commit failed: Invalid argument
2024-12-30 23:27:43.990 T:1158    error <general>: CDRMAtomic::DrmAtomicCommit - test commit failed: (Invalid argument) - falling back to last successful atomic request
2024-12-30 23:27:43.990 T:1158    debug <general>: CDRMAtomicRequest::LogAtomicDiff - DRM Atomic Request Diff:
2024-12-30 23:27:43.990 T:1158    error <general>: 
                                                   Object: plane	ID: 80
                                                     Property: SRC_X	ID: 9	Value: 0
                                                     Property: SRC_Y	ID: 10	Value: 0
                                                     Property: SRC_W	ID: 11	Value: 47185920
                                                     Property: SRC_H	ID: 12	Value: 37748736
                                                     Property: CRTC_X	ID: 13	Value: 240
                                                     Property: CRTC_Y	ID: 14	Value: 0
                                                     Property: CRTC_W	ID: 15	Value: 1440
                                                     Property: CRTC_H	ID: 16	Value: 1080
                                                     Property: FB_ID	ID: 17	Value: 298
                                                     Property: CRTC_ID	ID: 20	Value: 90
                                                   Object: plane	ID: 91
                                                     Property: FB_ID	ID: 17	Value: 293
```
There is a small possibility that https://github.com/xbmc/xbmc/pull/25588 helps in this case.
