### ISSUE TITLE
Server started but unable to process the folders

### ISSUE THREAD

**Issue by incipio-srinu** [xbmc/xbmc#6151]
I have tried this code it have started the server and then I have seen the server name like test:some name in the list of servers (I have tested on the iOS app called ArkMC Lite). But when I click on the server it is not giving any folder names or music files....

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
