### ISSUE TITLE
Kodi 14.0 crashes on windows 7 whenever you use remote iOS app

### ISSUE THREAD

**Issue by Shawzborne** [xbmc/xbmc#6180]
Kodi 14.0 crashes on windows 7 whenever you use remote iOS app

any way to fix this?

Thanks

Shawn

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
