### ISSUE TITLE
Lines on top and bottom in video

### ISSUE THREAD

**Issue by coolwormgit** [xbmc/xbmc#6195]
Device: HummingBoard-i2eX
problem with video around the video, most on top and bottom!

Problem fix with disable hardware acceleration!

log file: https://drive.google.com/file/d/0B_8TCbqBtgBIOExMcHJCdzNFN1U/view?usp=sharing
![fn95hz](https://cloud.githubusercontent.com/assets/10504401/5712235/436b6c6e-9ab9-11e4-9fb4-bda302ad7981.jpg)
![oax1xx](https://cloud.githubusercontent.com/assets/10504401/5712241/4c182b7c-9ab9-11e4-8bd2-413e7d3abf2b.jpg)

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
