### ISSUE TITLE
Multi Monitor Window Size and Position

### ISSUE THREAD

**Issue by Adarma** [xbmc/xbmc#6228]
I have a laptop running Kodi connected to a TV. The TV has much higher resolution than the laptop.
If I open Kodi on the laptop screen, but then disable the laptop screen (Windows+P, Projector Only [Win7 x64]), the kodi window is off screen someplace. If I close Kodi and reopen it, it is still opening offscreen.

If I have Kodi running on the TV, then toggle the laptop screen back on, when I open Kodi, it starts with a window much bigger than the screen resolution and I just see the middle of the window.

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
