### ISSUE TITLE
Wake on Lan with paused content

### ISSUE THREAD

**Issue by damoxc** [xbmc/xbmc#6278]
If I pause a video for a duration longer than the timeout period, then by the time I come to resume playback, my fileserver has suspended itself. This results in a short period of playback (which I assume is the buffer length) before Kodi hangs, and the only way to recover is to restart the application.

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
