### ISSUE TITLE
Bug in addon getSetting() function?

### ISSUE THREAD

**Issue by merlink01** [xbmc/xbmc#6315]
Please read:
http://forum.kodi.tv/showthread.php?tid=216975

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
