### ISSUE TITLE
ProgressBar is not showing the correct Time

### ISSUE THREAD

**Issue by tavoc** [xbmc/xbmc#6368]
The Progressbar in the EPG Grid View does not show the correct time. It seems to lag behind 10-15 minutes, because the Bar is left-alignt.

To change this to a more logical view following change is necessary:

skin.confluence\720p\ViewsPVRGuide.xml in line 44 from

<align>left</align>

to

<align>center</align>

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
