### ISSUE TITLE
Compiling kodi on i386 chroot generate dll *-x86_64-linux.so

### ISSUE THREAD

**Issue by zz64** [xbmc/xbmc#6375]
I discover that KODI generates the name of library's based on the original system (in my cases  x86_64 ). While KODI has been compiled into an i386 chroot (/proc file system mounted)

```
./addons/library.xbmc.gui/libXBMC_gui-x86_64-linux.so
./addons/library.xbmc.codec/libXBMC_codec-x86_64-linux.so
./addons/library.xbmc.addon/libXBMC_addon-x86_64-linux.so
./addons/library.xbmc.pvr/libXBMC_pvr-x86_64-linux.so
....
```
```
ldd ./addons/library.xbmc.gui/libXBMC_gui-x86_64-linux.so
	linux-gate.so.1 (0xf7769000)
	libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xf7648000)
	libm.so.6 => /lib/i386-linux-gnu/i686/cmov/libm.so.6 (0xf7602000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf75e4000)
	libc.so.6 => /lib/i386-linux-gnu/i686/cmov/libc.so.6 (0xf7439000)
	/lib/ld-linux.so.2 (0xf776c000)
```
With this bug, KODI works well, but not load pvr addons.
I thought it was incompatible with the version of PVR, so I Ask in the forum:
http://forum.kodi.tv/showthread.php?tid=153801&pid=1916051#pid1916051

i have fixed this issue by modify configure.in
```
--- configure.in_orig	2015-02-09 11:05:41.103852546 +0100
+++ configure.in	2015-02-07 12:03:15.244376228 +0100
@@ -611,10 +611,10 @@
      ;;
   i*86*-linux-gnu*|i*86*-*-linux-uclibc*)
      ARCH="i486-linux"
-     if test "$use_cpu" = "no" -a "$cross_compiling" = "yes";  then
+     # if test "$use_cpu" = "no" -a "$cross_compiling" = "yes";  then
         use_arch="x86"
         use_cpu="i686"
-     fi
+     #fi
      USE_STATIC_FFMPEG=1
      ;;
```
and, running
```
./configure --host=i386-linux-gnu --build=i386-linux-gnu ...
```
then, the library is generated like...
```
./addons/library.xbmc.gui/libXBMC_gui-i486-linux.so
./addons/library.xbmc.codec/libXBMC_codec-i486-linux.so
```
but not system/libsse4-x86_64-linux.so :(

This is bug, or KODI should built otherwise ?

KODI 14.1
Debian jessie 8
Autoconf 2.69
Linux-3.16.0-4-amd64
chroot: Debian jessie 8 i386

Thanks.

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
