### ISSUE TITLE
Romanian diacritics missing from interface

### ISSUE THREAD

**Issue by Danny3** [xbmc/xbmc#6522]
Hello guys
When the interface is shown in romanian language the letter t with comma bellow (http://en.wikipedia.org/wiki/T-comma) is missing from the words that have this letter

One workaround that Ifound is to change the default font for skin to Arial based
So it would seem that this letter is simply missing from the default font that is used for Confluence

I am using Kodi 14.2 Beta 1 on Windows 7 64 bit
This problem is present in previous releases but it's a regression because when I first translated XBMC in romanian (3 or 4 years ago) everything was fine
It started 2 or 3 releases ago but I don't know exactly

The problem is and the workaround is working on both Windows and Linux

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
