### ISSUE TITLE
Buffer (cache) does not work for SMB (Samba)

### ISSUE THREAD

**Issue by iz8mbw** [xbmc/xbmc#6537]
Hi.
I posted this message also on the Kodi forum here ​http://forum.kodi.tv/showthread.php?tid=219012. I'm running OpenELEC 5.0.3 (Kodi 14.1) on my Raspberry Pi 2, it works very well. The Raspberry Pi 2 is connected via ethernet cable with a gigabit switch to my Windows PC (Win7 64bit on Intel i5 with 4GB of RAM that has a gigabit NIC) and via SMB (Samba) I have the access to the PC hard disk. I have noted that the maximum ethernet bitrate of the Raspberri Pi 2 is about 70 Megabit/sec, when I play a high bit rate 1080p mkv and that stream will exceed about 70 Megabit/sec (even for just a few seconds) the video/audio goes jerky/stuttering (intermittent)... For what I know the only way to enable the buffer is to set it into the file advancedsettings.xml. So I enabled buffer (cache) to avoid this problem of "slow" network problem. I was looking to advancedsettings.xml but I have done some configuration/test but it seem that this file has no effect for SMB (Samba) stream.

This is how I configured the file advancedsettings.xml:

<advancedsettings>
<network>
<buffermode>1</buffermode>
<cachemembuffersize>104857600</cachemembuffersize>
<readbufferfactor>5</readbufferfactor>
</network>
</advancedsettings>

I have tried also without the "readbufferfactor" option but the behavior is always the same: buffer it does not work for SMB (Samba). I enabled the Debug and it seem that the advancedsettings.xml is correctly read by Kodi, see here:

08:09:19 T:1970081792  NOTICE: Loaded settings file from special://xbmc/system/advancedsettings.xml
08:09:19 T:1970081792  NOTICE: Contents of special://xbmc/system/advancedsettings.xml are...
                                            <?xml version="1.0" encoding="UTF-8" ?>
                                            <advancedsettings>
                                              <showexitbutton>false</showexitbutton>
                                              <fanartres>720</fanartres>
                                              <imageres>540</imageres>
                                              <video>
                                                <busydialogdelayms>750</busydialogdelayms>
                                              </video>
                                              <samba>
                                                <clienttimeout>30</clienttimeout>
                                              </samba>
                                              <network>
                                                <readbufferfactor>4.0</readbufferfactor>
                                              </network>
                                            </advancedsettings>
08:09:19 T:1970081792  NOTICE: Loaded settings file from special://profile/advancedsettings.xml
08:09:19 T:1970081792  NOTICE: Contents of special://profile/advancedsettings.xml are...
                                            <advancedsettings>
                                              <network>
                                                <buffermode>1</buffermode>
                                                <cachemembuffersize>104857600</cachemembuffersize>
                                                <readbufferfactor>5</readbufferfactor>
                                              </network>
                                            </advancedsettings>

More, if I play that mkv file (it starts immediately so no Buffer at the first play) and immediately I pause it (still) the network throughput goes to zero... so no Buffer is created neither at the beginning and during. Hope it will be solved soon. Thanks!

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
