### ISSUE TITLE
Kodi crash when using Yatse remotecontrol

### ISSUE THREAD

**Issue by pschonmann** [xbmc/xbmc#6694]
When loading library content its constantly crash

Stacktrace
```
Thread 4524 (process 4960)
# 0 RtlInitUnicodeString
# 1 RtlFreeHeap
# 2 HeapFree
# 3
# 4
# 5
# 6
# 7
# 8
# 9
#10 RtlFreeHeap
#11 HeapFree
#12
#13
#14
#15
#16
#17
#18
#19
#20
#21
```
There is a DMP file
http://s000.tinyupload.com/index.php?file_id=14009596536475924108

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
