### ISSUE TITLE
Enable parallel build for codegenerator.mk

### ISSUE THREAD

**Issue by atupone** [xbmc/xbmc#6711]
--- codegenerator.mk.old        2015-03-10 08:49:45.480631067 +0100
+++ codegenerator.mk    2015-03-10 08:51:32.048879905 +0100
@@ -74,7 +74,7 @@

 $(GENERATED_JSON): $(JSON_BUILDER)
        @echo Jsonbuilder: $(JSON_BUILDER)
-       make -C $(INTERFACES_DIR)/json-rpc $(notdir $@)
+       $(MAKE) -C $(INTERFACES_DIR)/json-rpc $(notdir $@)

 $(JSON_BUILDER):
 ifeq ($(BOOTSTRAP_FROM_DEPENDS), yes)
@@ -82,5 +82,5 @@
        @false
 else
 #build json builder - ".." because makefile is in the parent dir of "bin"
-       make -C $(abspath $(dir $@)..)
+       $(MAKE) -C $(abspath $(dir $@)..)
 endif

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
