### ISSUE TITLE
Use the ${CXX} compiler when running configure

### ISSUE THREAD

**Issue by atupone** [xbmc/xbmc#6712]
--- configure.ac.old    2015-03-03 14:26:28.690271749 +0100
+++ configure.ac        2015-03-03 14:27:32.283087389 +0100
@@ -2230,7 +2230,7 @@
 # we don't compile with default upstream squish, so we use our own one
 # even on non unified deps platforms
 if test "$cross_compiling" != "yes"; then
-  make -C ${abs_top_srcdir}/tools/depends/native/libsquish-native
+  make -C ${abs_top_srcdir}/tools/depends/native/libsquish-native CXX=${CXX}
   export PKG_CONFIG_PATH="${abs_top_srcdir}/tools/depends/native/libsquish-native/squish-install/lib/pkgconfig:$PKG_CONFIG_PATH"
 fi
 PKG_CHECK_MODULES([SQUISH], [squish],

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
