### ISSUE TITLE
Bad grammar: Allow video player to ignoring aspect ratio

### ISSUE THREAD

**Issue by foresto** [xbmc/xbmc#6778]
There is a sentence in the settings that reads, "Allow video player to ignoring aspect ratio..." This is terrible grammar.

I set out to fix it, but it seems that this text is a msgid in addons/resource.language.en_gb/resources/strings.po, referenced by hundreds of files in the translations repository, many of which seem to come from an external source. (Transifex?) I'm out of my depth. Hopefully someone who is set up to handle global translation problems can fix it.

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
