### ISSUE TITLE
Random Exiting on Ipad mini & Ipad mini Retina

### ISSUE THREAD

**Issue by felipejfc** [xbmc/xbmc#6800]
Hi, I've installed Kodi on 2 ipad minis of mine, one is a 1st gen ipad mini and another is the 1st gen of ipad mini retina, on both of them I'm getting force closes mostly while opening some field to enter text, maybe a RAM issue? I closed all the processes running and it still happens sometimes...

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
