### ISSUE TITLE
Add support for SNI

### ISSUE THREAD

**Issue by asfaltboy** [xbmc/xbmc#6822]
As observerd in [this forum thread](http://forum.kodi.tv/showthread.php?tid=219219&pid=1965364#pid1965364), current Kodi builds are missing [SNI support](http://en.wikipedia.org/wiki/Server_Name_Indication).

Some servers which do not use a "wildcard certificate"  have lately been patched to require SNI to initiate SSL handshake (like https://www.coursera.org), this creates a problem for us addon developers, and our add on users.

One possible solution may be upgrading to Latest python 2.7.9 which has added implementation of some [PEP 466 - Network Security Enhancements](https://docs.python.org/2/whatsnew/2.7.html#pep-466-network-security-enhancements-for-python-2-7) (backported from 3.4); one of these is Server Name Indication. This also has the benefit of making Kodi more secure, as well as solving our problem with accessing patched servers.

Another solution I've seen, is to build python with a [patched version of openssl 0.9.8j](http://en.wikipedia.org/wiki/Server_Name_Indication#Libraries) or later; and also package python with some required packages, namely:
- [pyOpenSSL](https://launchpad.net/pyopenssl)
- [ndg-httpsclient](https://pypi.python.org/pypi/ndg-httpsclient)
- [pyasn1](http://pyasn1.sourceforge.net/)

This is described in a number of requests/urllib issues (e.g.: kennethreitz/requests#749) and this [stackoverflow answer](https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484).

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
