### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Allanitomwesh** [xbmc/xbmc#6860]
Is it possible to add the Kodi Android app to F-Droid? It would be easier to install and update from there. Thanks.

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi

**Comment by c-e-p-x-u-o** [comment]
related issue https://gitlab.com/fdroid/rfp/issues/473

**Comment by IzzySoft** [comment]
@ulion please consider to reopen. F-Droid inclusion is also a code discussion, if you want:

```
ERROR: Found binary at lib/libUPnP/Platinum/Source/Tests/MediaServerCocoaTest/MediaServerCocoaTest_DataModel.xcdatamodel/layout
ERROR: Found binary at lib/libUPnP/Platinum/Source/Tests/MediaServerCocoaTest/MediaServerCocoaTest_DataModel.xcdatamodel/elements
ERROR: Found binary at project/Win32BuildSetup/tools/7z/7za.exe
ERROR: Found binary at project/BuildDependencies/bin/wget.exe
ERROR: Found binary at tools/darwin/packaging/osx/VolumeDSStoreApp
WARNING: Found JAR file at tools/codegenerator/groovy/groovy-all-2.4.4.jar
WARNING: Found JAR file at tools/codegenerator/groovy/commons-lang-2.6.jar
```

This is what the F-Droid bot reports about your code. Could you please check if those binaries are really needed (F-Droid doesn't accept binaries, all must be compiled from source)? The `*.exe` certainly don't belong into a **source code** repo. The `*.jar` are preferably provided as source as well (e.g. via git submodules or a suitable Maven repo (see [here](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L98) for a list of trusted Maven repos).

Any chance to get that cleaned-up – and get you to agree on F-Droid inclusion? Thanks in advance!

**Comment by MartijnKaijser** [comment]
If some one wants to effort on getting this done they should do the work. Currently no one from us is interested as we have other things to do

**Comment by Rechi** [comment]
```
ERROR: Found binary at lib/libUPnP/Platinum/Source/Tests/MediaServerCocoaTest/MediaServerCocoaTest_DataModel.xcdatamodel/layout
ERROR: Found binary at lib/libUPnP/Platinum/Source/Tests/MediaServerCocoaTest/MediaServerCocoaTest_DataModel.xcdatamodel/elements
```
unused, so you can exclude it for building

```
ERROR: Found binary at project/Win32BuildSetup/tools/7z/7za.exe
ERROR: Found binary at project/BuildDependencies/bin/wget.exe
ERROR: Found binary at tools/darwin/packaging/osx/VolumeDSStoreApp
```
only used on windows and osx, so you can exclude it for building

```
WARNING: Found JAR file at tools/codegenerator/groovy/groovy-all-2.4.4.jar
WARNING: Found JAR file at tools/codegenerator/groovy/commons-lang-2.6.jar
```
system ones could be used but would need code changes

**Comment by IzzySoft** [comment]
thanks @Rechi – that eliminates most of those concerns. Afraid noone at F-Droid can make the required code changes for the last two (we are permanently understaffed). If it is not asked too much (which I hope), could you make a build flavor that eliminates the remaining two as well? Big thanks in advance!

**Comment by IzzySoft** [comment]
@Rechi Cool, thanks! I guess that should do. I'll transfer that over to the issue on F-Droid and ask if someone can build the app with this.

**Comment by Rudloff** [comment]
Thanks for the patch! Our build server uses Debian so using a local groovy should indeed work.

**Comment by licaon-kter** [comment]
Can someone take a look at these f-droid buildserver logs?
https://gitlab.com/fdroid/fdroiddata/issues/1771

**Comment by 4tip** [comment]
Please help to get the new Kodi 18.4 update to the F-Droid repo! (see the link in the comment above)

**Comment by Korb** [comment]
#24731:
> We don't maintain the fdroid build/app submission

**Comment by licaon-kter** [comment]
You don't but adding a Fastlane/Triple-T folder here with such stuff like description, screenshots, icon, changelogs, would improve the listing.
