### ISSUE TITLE
Change repo name to Kodi

### ISSUE THREAD

**Issue by DaAwesomeP** [xbmc/xbmc#6894]
GitHub does a great job of redirecting changed repository and organization names. The repo and organization should be renamed to `kodi/kodi`.

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi

**Comment by Memphiz** [comment]
mhh HowTo? ^^

**Comment by DaAwesomeP** [comment]
Do you mean how to rename the repo? On the repo's homepage, there is a settings tab under the ones like code, issues, etc. In there the first option is for renaming it. I think that this should be re-opened this since it applies so directly to the GitHub repo.

**Comment by topfs2** [comment]
AFAIK that way breaks all cloned and forked repositories, as they will
point to the old URI. Or have github circumvented that?

**Comment by MartijnKaijser** [comment]
renaming/moving will just redirect all PRs

**Comment by xhaggi** [comment]
take a look at https://help.github.com/articles/renaming-a-repository/

**Comment by DaAwesomeP** [comment]
Any reason for delay?

**Comment by Memphiz** [comment]
You ever did it with a project which has our size and can give me a hand signed paper that we won't have any regressions when doing so?

**Comment by hudokkow** [comment]
think of jenkins... the poor fellow only accepts orders from repos named xbmc :P

**Comment by Memphiz** [comment]
Yeah thats only one example i fear which will bind my valuable time ... there are other services relying on a sane github linkage. I wouldn't consider this change during the beta phase we are in currently. We need our services to work reliable until the release is done.
