### ISSUE TITLE
kodi ssh

### ISSUE THREAD

**Issue by orjanTonder** [xbmc/xbmc#7110]
~.ssh/id_rsa not read with kodi

keys not working on ubuntu 14.04 LTS
is there any plans makeing this work or workarounds?

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
