### ISSUE TITLE
libCEC 3.0 not compiling in properly

### ISSUE THREAD

**Issue by DBendit** [xbmc/xbmc#7119]
I've just pulled the latest and greatest platform, libcec, and kodi from git. I compiled platform and libcec per the directions, as I always have. When running ./configure for kodi with --with-libcec, I get the following in the config.log:

configure:28782: checking for CEC
configure:28789: $PKG_CONFIG --exists --print-errors "libcec >= 3.0.0"
configure:28792: $? = 0
configure:28806: $PKG_CONFIG --exists --print-errors "libcec >= 3.0.0"
configure:28809: $? = 0
configure:28849: result: yes
configure:28869: checking for libcec soname
configure:28899: result: no
configure:28904: WARNING: Unable to determine soname of libcec library
configure:28907: WARNING: libcec support disabled
configure:28916: == libcec enabled. ==

At the final checklist from ./configure, I get the following:

  libcec support:       No

After compiling and installing kodi, the peripherals menu is greyed out, and I can no longer use my TV's remote control to navigate the system.

I assume this all has to do with the move to 3.0 of libcec, since that moved a bunch of things around. Additionally, it doesn't seem to produce a libcec.so file anymore, which would explain why the soname can't be found.

If there's anything else I can provide, let me know.

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
