### ISSUE TITLE
Providing RaspBerry Pi 2 README for Debian Jessie 8.0

### ISSUE THREAD

**Issue by ThomasKorimort** [xbmc/xbmc#7203]
I tried now for quite a while to get Kodi running on my RPi2 with Debian Jessie. I got an image from the internet containing a repository for armhf architecture of RPi2. However, i have no clue about how special the firmware needs to be installed and treated. The native xbmc 12 package of Debian does not work because of complaints about GL support and later 24-bit color depth. For that reason i started to search on the internet for alternatives. Recompiling Kodi from the current branch 15 did not work on Debian Jessie 8.0 on my RPi2. The included manual for compilation of Kodi on RaspBerry Pi relates to cross-compilation and not to native-platform compilation. Secondly, it seems to deal also with RaspBerry Pi only instead of Pi 2. Other solutions from the internet include copying files from OpenElec into the current Debian 8.0 Jessie installation which worked partially (Kodi cannot play any mp3 and will crash on trying to play). However, at least it started to the Kodi desktop. Since that way was not leading to a useful installation, i tried to get hands on the repository, compiling it myself. Following the instructions for Linux/RaspBerryPi/Debian Wheezy is ended installing library dependencies by myself and checking each library by hand. Still, versions of Debian 8.0 of e.g. gcrypt gpg-error did not match the requirements of Kodi 15, so the configure script stopped with an error and completing the compilation was far away.
Anyway, it would be nice having Kodi also available for installing via package in Debian 8.0 for Raspberry Pi 2 or at least some valid way to compile it natively in Debian 8.0 Jessie for the Raspberry Pi 2. As to my knowledge there is no manual in the internet which explains that procedure nicely or at all. Would it be possible to provide a complete HOW-TO-GETWORKING-KODI-DEBIAN8.0-RASPBERRY Pi2..

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
