### ISSUE TITLE
IGMP version

### ISSUE THREAD

**Issue by lvalero** [xbmc/xbmc#7270]
Hello,

I am using kodi-pvr/pvr.iptvsimple addon and i noticed that it first sends an IGMP membership query version 3, and then after a few seconds an IGMP membership query version 2 (version 2 is the version supported on the my network).

I was wondering if it is a Kodi behavior or the add-on one.

Regards

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
