### ISSUE TITLE
Kodi does not properly detect intel hardware for VAAPI

### ISSUE THREAD

**Issue by tilwolff** [xbmc/xbmc#7278]
On my Intel Sandybridge system with DEBIAN Wheezy and Kodi 14.2 Release, intel hardware is not succesfully detected when opening the VAAPI decoder. 

Reason: Kodi checks the OpenGL RenderVendor string which begins with "Tungsten Graphics" as opposed to "Intel". I could temporarily fix this by changing VAAPI.cpp in CDecoder::Open

std::string gpuvendor = g_Windowing.GetRenderVendor();
  std::transform(gpuvendor.begin(), gpuvendor.end(), gpuvendor.begin(), ::tolower);
--  if (gpuvendor.compare(0, 5, "intel") != 0)
++  if (gpuvendor.compare(0, 5, "intel") != 0 && gpuvendor.compare(0, 8, "tungsten") != 0)

If I run OpenELEC on the same hardware, Vendor string is "Intel OpenSource Technology Center" and VAAPI is properly initialised. I think KODI should be able to deal with possibly distribution specific alternative vendor strings.

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi

**Comment by fritsch** [comment]
That's by intention. Basically we don't want to support outdated SW stacks.
See the wiki on howto force vaapi via advancedsettings if you are forced to
stay in 2k5 SW stack.
Am 13.06.2015 8:44 nachm. schrieb "ulion" <notifications@github.com>:
