### ISSUE TITLE
FLV seeking broken with remote resource(http)

### ISSUE THREAD

**Issue by evilsephiroth** [xbmc/xbmc#7288]
Seeking is not possible when playing a flv file from a web server or remote resource. Seeking has no problem when resource is local(hence no need to seek ahead).

Debugging the code, I've seen that keyframes data got lost. File has all corrected metadata and keyframes set but when instantiating dvdPlayer keyframes are not there anymore.
Doing this with a 120MB file under Apache or custom python proxy(204 http return code to signal partial content).
 File is a repacked adobe HDS stream(flv header plus mdat boxes written as stream) but same principle works for simple flv also.

Playing with seeking not allowed(200 OK on first HEAD request by kodi instead of 204), playback is perfect.

I can also attach sample files.

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
