### ISSUE TITLE
BUG - ExecuteAppAndroid (const char *, const char *): Failure: 1

### ISSUE THREAD

**Issue by whise** [xbmc/xbmc#7302]
There is a bug in the externalplayer launch system, only for Android i think.

When the external player gets started correctly kodi thinks it crashed:

In log:

NOTICE: virtual BOOL CExternalPlayer :: ExecuteAppAndroid (const char *, const char *): Failure: 1

If the external player is not started due to error, kodi thinks it is running.

In Kodi:

"External player active click ok when playback has ended"

BUG is described here:http://trac.kodi.tv/ticket/15819

Please fix this bug, it stops me from getting json-rpc data when using an external player. Also it doesnt allow external players to do playlists...

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
