### ISSUE TITLE
Incorrect video-files stopps playing and are not watchable

### ISSUE THREAD

**Issue by mutorio** [xbmc/xbmc#7314]
I have issues sometimes with not 100 % correct Videofiles. After testing many Players on Desktop an the Android Plattform I find out that all of these Files play good on the Desktop with the videoplayer: mpv in smplayer and with mxplayer on the Android Plattform. 

Other Players on Desktop like: mplayer, totem, vlc, xbmc, kodi, spmc
and on Android like: vlc, vplayer, archos video player, xbmc, kodi, spmc

stopps playback with these incorrect files almost on the same position of the video file.
In MPV (with or without smplayer) on Desktop and with MXPlayer on Android (BOTH FFMPEG BASED)
there are only a fee broken frames or max. 30 seconds broken videoplayback but they don't stop playing and the video file is good watchabel after all. 

In my Opinion mpv makes a better job than mxplayer.

On  MXPlayer more video is not watchabel and it automatically step sometimes a few Minutes to far , also the Video Audio Sync is in this case sometimes not correct. Both issues are easilly to solve by stepping manually back in the near after the first error in the video file. If you stop to much backward to this errorpoint it can be very annoying because the big automatically step forward from the player comes again. Also stepping forward over this errorpoint sometimes brings you for exaple not as expected 10 seconds instead for wxample 10 minutes.

In mpv on the Desktop there are no cases like this it just shows a few brocken frames and the video plays syncron with video and sound. If the video is more broken (like 1 minute for example) it gives the audio out and plays until the video shows up again. Anyway on mpv there is no problem because you can step forward for exampel 10 or 30 seconds an you see that the rest of the video file is playing well.

I think it would be a very good idea to test kodi against many broken video files with different formats, for exampel on corupted Downloads. Keep broken files after error crc unpacking issues and uncorrect demuxed videos.

I don't know what mxplayer and on first place mpv do so much better for unstoppable videoplayback and error stability but maybe it is worth to take a look in their code.

If you need an example file I can give one recorded from tv.

Best regards for your top work on the best Media Center Software out there,

mutorio

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
