### ISSUE TITLE
texturepackager is forced to be static

### ISSUE THREAD

**Issue by olafhering** [xbmc/xbmc#7440]
Why does TexturePacker/Makefile.am force a static build? Building 15.0 branch in openSUSE 13.1 and Factory yields:

`[  234s] cd native; ./configure --prefix=/home/abuild/rpmbuild/BUILD/xbmc-14.9.902/tools/depends/native/TexturePacker --enable-static EXTRA_DEFINES=""`

`xbmc-14.9.902/tools/depends/native/TexturePacker/Makefile:18:  EXTRA_CONFIGURE = --enable-static`

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
