### ISSUE TITLE
Add Ability tu define an Audiobook directory

### ISSUE THREAD

**Issue by Mannshoch** [xbmc/xbmc#7513]
I'm able to set up a directory for Film or series but I'm not able to set up a directory for Audiobooks  and Radio dramas
It should be able to Categorize them into:
  * Universe * 
  * Album
  * Season
  * Episode

*Some Free Recordings play a Tale into the same Univers maybe also an Interesting feature for Film to separate them like the Marvel Universe.

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi

**Comment by Mannshoch** [comment]
->  http://forum.kodi.tv/showthread.php?tid=65862
