### ISSUE TITLE
LiveTV buffering

### ISSUE THREAD

**Issue by OferE** [xbmc/xbmc#7603]
This is an enhancement request (I hope i put it in the correct place - if not please forgive me):
Like u probably heard many times before: on LiveTV we can get a "buffering" event every now and then.

I suggest adding an ability to buffer X minutes/seconds ahead so that the users can control the frequency of this annoying behavior:
it would be great to have the ability to control this X from UI.
It seems pretty "straight forward" approach, i am surprised this case is not handled by now...

I know this is not a perfect solution - it won't help in case of slow network, but in many cases the client network is ok, and just giving 1 minute buffering (for example) - will reduce the risk of encountering this behavior at all;
In other situations at least it will give the user the ability to control the frequency of the "buffering" event he will suffer.
in some cases getting a long "buffering" event every 10 minutes is a much better experience than getting a short buffering every one minute.

many of the buffering issues comes from glitches on the streaming site, but the glitches are not fixed, they happen every X seconds or so. This will solve the issue in such cases.

Just to make sure: it looks like non of the buffers keys in advancedSettings.xml solves this issue.

Hope this helps,
Thanks!

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
