### ISSUE TITLE
Scraper issue: No nfo found returned in case more then one is present

### ISSUE THREAD

**Issue by Flobbes** [xbmc/xbmc#7814]
It took me more than 1 hour of compiling and debugging, because I was looking in the wrong place.
Kodi always reported no nfo file, although there were 2 present in the folder.

It seems that in case there is more than 1 nfo, that GetnfoFile() sets numNFO = -1 and quits.

Wouldn't it be better to just take any nfo? Or at least return, that there are more than one nfo and not "no nfo file found".

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
