### ISSUE TITLE
Error tying to stream to tv

### ISSUE THREAD

**Issue by ismaelaarab** [xbmc/xbmc#7827]
When i try to stream to the tv using the play using button i get this error:

ERROR: CUPnPPlayer::PlayFile(C:\video.mp4) failed to find a matching resource
ERROR: UPNP: CUPnPPlayer::OpenFile - unable to open file C:\video.mp4
ERROR: Playlist Player: skipping unplayable item: 0, path [C:\video.mp4]

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
