### ISSUE TITLE
Joystick support in raspberry pi kodi

### ISSUE THREAD

**Issue by michaelsit91** [xbmc/xbmc#7834]
Hi,

I'm trying to build kodi with joystick support for the raspberry pi 2.

While running make -j3 i get a lot of code errors, mainly from the SDL portion

Can you fix the codes to support the joystick function??

Thank you

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
