### ISSUE TITLE
share pictures over UPnP/DNLA in XBMC/kodi

### ISSUE THREAD

**Issue by oquidave** [xbmc/xbmc#7917]
Hello, am currently using Kodi 14.x. However, it doesn't support sharing of pictures via UPnP/DNLA. I can't for instance view pictures on my Samsung Smart TV. I've Googled around and discovered the feature isn't yet supported. Thanks

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
