### ISSUE TITLE
Issue when a normal episode and a special comes out on the same date

### ISSUE THREAD

**Issue by Hubro** [xbmc/xbmc#7922]
Every episode of Real Time with Bill Maher is accompanied by a "special" episode called Overtime.

When adding episodes of Real Time to my Kodi library, they are always incorrectly assumed to be Overtime specials rather than normal episodes. Real Time is a talk show like The Daily Show or @midnight, so the episodes are always tagged with a date rather than a season and episode number.

It seems to me like when there's ambiguity, the more correct course would be to assume that an episode is a "normal" episode rather than a special.

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
