### ISSUE TITLE
Bin URLs are self-deprecating

### ISSUE THREAD

**Issue by dtgm** [xbmc/xbmc#7942]
I maintain the kodi chocolatey package that is a wrapper installer for Kodi.  The issue I am having is the URL expires at each new release; upon each release the files in http://mirrors.kodi.tv/releases/win32/ are moved into the __old__ subdirectory.

This prevents users from installing previous versions.  Could you please change your release URI schema to include non-expiring URLs?

A simple solution would be to also write the release files that are placed in __win32__ into __old__ subdir right away upon each release.

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
