### ISSUE TITLE
Watch flag in profiles

### ISSUE THREAD

**Issue by boscorelly** [xbmc/xbmc#7957]
Hi,

since upgrade to v15, watch flag is set in all profiles.

My mum, my brother and i have a profile. She is looking Greys Anatomy for now. When she finish en EP, it's flagged as watched in my brother and my profile.

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
