### ISSUE TITLE
Adaptive seeking does not work from web interface

### ISSUE THREAD

**Issue by gellis12** [xbmc/xbmc#7972]
When using the web interface (which also includes the official remote apps, since they rely on it), adaptive seeking doesn't work. Tapping on the skip forwards/backwards buttons or the left/right arrows will always make Kodi skip 30 seconds.

Making the new adaptive seeking features consistent across all control methods would be preferable to keeping the old method for remotes.

**Comment by ulion** [comment]
Team Kodi uses github for development only, i.e. for pull requests and the discussion of code.

So we use a hook script to automatically close this new issue here.

If you can, we encourage you to investigate the issue yourself and create a Pull Request for us to review.
You may want to check the contributing guide: https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md

For bug reports, feature requests and all other support, please go to
http://forum.kodi.tv.

Thanks,
Team Kodi
